ECCE @ EIC Software: G4Scatterer Class Reference
G4Scatterer Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4Scatterer.hh>
Classes
struct Register
Public Member Functions
G4Scatterer ()
virtual ~G4Scatterer ()
virtual G4double GetTimeToInteraction (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double GetCrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4KineticTrackVector * Scatter (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const std::vector
< G4CollisionInitialState * > & GetCollisions (G4KineticTrack *aProjectile, std::vector< G4KineticTrack * > &someCandidates, G4double aCurrentTime)
virtual G4KineticTrackVector * GetFinalState (G4KineticTrack *aProjectile, std::vector< G4KineticTrack * > &theTargets)
Public Member Functions inherited from G4VScatterer
G4VScatterer ()
virtual ~G4VScatterer ()
Public Member Functions inherited from G4BCAction
G4BCAction ()
virtual ~G4BCAction ()
Private Member Functions
const G4VCollision * FindCollision (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Attributes
std::vector
< G4CollisionInitialState * > theCollisions
Static Private Attributes
static G4CollisionVector collisions
Detailed Description
Definition at line 43 of file G4Scatterer.hh.
View newest version in sPHENIX GitHub at line 43 of file G4Scatterer.hh
Constructor & Destructor Documentation
G4Scatterer::G4Scatterer ()
Definition at line 62 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 62 of file G4Scatterer.cc
References G4ForEach< group >::Apply().
G4Scatterer::~G4Scatterer () virtual
Definition at line 75 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 75 of file G4Scatterer.cc
References collisions.
Member Function Documentation
const G4VCollision * G4Scatterer::FindCollision (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const private
Definition at line 394 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 394 of file G4Scatterer.cc
References collisions, and G4VCollision::IsInCharge().
Referenced by GetCrossSection(), GetTimeToInteraction(), and Scatter().
const std::vector< G4CollisionInitialState * > & G4Scatterer::GetCollisions (G4KineticTrack * aProjectile, std::vector< G4KineticTrack * > & someCandidates, G4double aCurrentTime) virtual
Implements G4BCAction.
Definition at line 438 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 438 of file G4Scatterer.cc
References DBL_MAX, GetTimeToInteraction(), and theCollisions.
G4double G4Scatterer::GetCrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const
Definition at line 423 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 423 of file G4Scatterer.cc
References G4VCollision::CrossSection(), and FindCollision().
G4KineticTrackVector * G4Scatterer::GetFinalState (G4KineticTrack * aProjectile, std::vector< G4KineticTrack * > & theTargets) virtual
Implements G4BCAction.
Definition at line 462 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 462 of file G4Scatterer.cc
References Scatter().
G4double G4Scatterer::GetTimeToInteraction (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VScatterer.
Definition at line 84 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 84 of file G4Scatterer.cc
References kdfinder::abs(), source.hepunit::c_light, G4VCollision::CrossSection(), DBL_MAX, e, CLHEP::HepLorentzVector::e(), FindCollision(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4KineticTrack::GetPosition(), G4KineticTrack::GetTrackingMomentum(), GeV, CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), millibarn, mom, G4Neutron::Neutron(), pi, pos(), Acts::VectorHelpers::time(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), and CLHEP::HepLorentzVector::z().
Referenced by GetCollisions().
G4KineticTrackVector * G4Scatterer::Scatter (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VScatterer.
Definition at line 283 of file G4Scatterer.cc.
View newest version in sPHENIX GitHub at line 283 of file G4Scatterer.cc
References G4VCollision::CrossSection(), FatalException, G4VCollision::FinalState(), FindCollision(), G4cout, G4endl, G4Exception(), G4lrint(), G4KineticTrack::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), CLHEP::HepLorentzVector::mag(), MeV, CLHEP::HepLorentzVector::t(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision(), GetFinalState(), and G4BinaryCascade::Propagate1H1().
Member Data Documentation
G4CollisionVector G4Scatterer::collisions static private
Definition at line 83 of file G4Scatterer.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Scatterer.hh
Referenced by FindCollision(), and ~G4Scatterer().
std::vector<G4CollisionInitialState *> G4Scatterer::theCollisions private
Definition at line 84 of file G4Scatterer.hh.
View newest version in sPHENIX GitHub at line 84 of file G4Scatterer.hh
Referenced by GetCollisions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4Scatterer.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4Scatterer.cc