ECCE @ EIC Software: G4IntersectionSolid Class Reference
G4IntersectionSolid Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/Boolean/include/G4IntersectionSolid.hh>
Public Member Functions
G4IntersectionSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB)
G4IntersectionSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, G4RotationMatrix *rotMatrix, const G4ThreeVector &transVector)
G4IntersectionSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, const G4Transform3D &transform)
virtual ~G4IntersectionSolid ()
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
G4IntersectionSolid (__void__ &)
G4IntersectionSolid (const G4IntersectionSolid &rhs)
G4IntersectionSolid & operator= (const G4IntersectionSolid &rhs)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=0, G4ThreeVector *n=0) const
G4double DistanceToOut (const G4ThreeVector &p) const
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
Public Member Functions inherited from G4BooleanSolid
G4BooleanSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB)
G4BooleanSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, G4RotationMatrix *rotMatrix, const G4ThreeVector &transVector)
G4BooleanSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, const G4Transform3D &transform)
virtual ~G4BooleanSolid ()
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
virtual G4Polyhedron * GetPolyhedron () const
std::ostream & StreamInfo (std::ostream &os) const
G4int GetCubVolStatistics () const
G4double GetCubVolEpsilon () const
void SetCubVolStatistics (G4int st)
void SetCubVolEpsilon (G4double ep)
G4int GetAreaStatistics () const
G4double GetAreaAccuracy () const
void SetAreaStatistics (G4int st)
void SetAreaAccuracy (G4double ep)
G4ThreeVector GetPointOnSurface () const
G4BooleanSolid (__void__ &)
G4BooleanSolid (const G4BooleanSolid &rhs)
G4BooleanSolid & operator= (const G4BooleanSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Additional Inherited Members
Protected Member Functions inherited from G4BooleanSolid
void GetListOfPrimitives (std::vector< std::pair< G4VSolid *, G4Transform3D >> &, const G4Transform3D &) const
G4Polyhedron * StackPolyhedron (HepPolyhedronProcessor &, const G4VSolid *) const
Protected Attributes inherited from G4BooleanSolid
G4VSolid * fPtrSolidA = nullptr
G4VSolid * fPtrSolidB = nullptr
Detailed Description
Definition at line 45 of file G4IntersectionSolid.hh.
View newest version in sPHENIX GitHub at line 45 of file G4IntersectionSolid.hh
Constructor & Destructor Documentation
G4IntersectionSolid::G4IntersectionSolid (const G4String & pName, G4VSolid * pSolidA, G4VSolid * pSolidB)
Definition at line 49 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 49 of file G4IntersectionSolid.cc
Referenced by Clone().
G4IntersectionSolid::G4IntersectionSolid (const G4String & pName, G4VSolid * pSolidA, G4VSolid * pSolidB, G4RotationMatrix * rotMatrix, const G4ThreeVector & transVector)
Definition at line 59 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 59 of file G4IntersectionSolid.cc
G4IntersectionSolid::G4IntersectionSolid (const G4String & pName, G4VSolid * pSolidA, G4VSolid * pSolidB, const G4Transform3D & transform)
Definition at line 72 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 72 of file G4IntersectionSolid.cc
G4IntersectionSolid::~G4IntersectionSolid () virtual
Definition at line 94 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 94 of file G4IntersectionSolid.cc
G4IntersectionSolid::G4IntersectionSolid (__void__ & a)
Definition at line 85 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 85 of file G4IntersectionSolid.cc
G4IntersectionSolid::G4IntersectionSolid (const G4IntersectionSolid & rhs)
Definition at line 102 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 102 of file G4IntersectionSolid.cc
Member Function Documentation
void G4IntersectionSolid::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 130 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 130 of file G4IntersectionSolid.cc
References G4VSolid::BoundingLimits(), G4VSolid::DumpInfo(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4Exception(), G4VSolid::GetName(), JustWarning, max, maxA, message(), min, pMax, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4bool G4IntersectionSolid::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 165 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 165 of file G4IntersectionSolid.cc
References G4VSolid::CalculateExtent(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, max, maxA, min, and pMin.
G4VSolid * G4IntersectionSolid::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 529 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 529 of file G4IntersectionSolid.cc
References G4IntersectionSolid().
void G4IntersectionSolid::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 510 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 510 of file G4IntersectionSolid.cc
G4Polyhedron * G4IntersectionSolid::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 549 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 549 of file G4IntersectionSolid.cc
References HepPolyhedronProcessor::execute(), processor, and G4BooleanSolid::StackPolyhedron().
void G4IntersectionSolid::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 539 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 539 of file G4IntersectionSolid.cc
References G4VGraphicsScene::AddSolid().
G4double G4IntersectionSolid::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 275 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 275 of file G4IntersectionSolid.cc
References G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, G4Exception(), Inside(), G4VSolid::Inside(), JustWarning, kInfinity, kInside, kSurface, and v.
G4double G4IntersectionSolid::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 382 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 382 of file G4IntersectionSolid.cc
References G4VSolid::DistanceToIn(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), G4VSolid::Inside(), kInside, kOutside, and min.
G4double G4IntersectionSolid::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = 0, G4ThreeVector * n = 0) const virtual
Implements G4VSolid.
Definition at line 425 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 425 of file G4IntersectionSolid.cc
References distA, G4VSolid::DistanceToOut(), distB, G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), kOutside, min, mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4IntersectionSolid::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 484 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 484 of file G4IntersectionSolid.cc
References G4VSolid::DistanceToOut(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), kOutside, and min.
G4GeometryType G4IntersectionSolid::GetEntityType () const virtual
Reimplemented from G4BooleanSolid.
Definition at line 520 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 520 of file G4IntersectionSolid.cc
EInside G4IntersectionSolid::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 197 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 197 of file G4IntersectionSolid.cc
References G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4VSolid::Inside(), kInside, kOutside, and kSurface.
Referenced by DistanceToIn(), and DistanceToOut().
G4IntersectionSolid & G4IntersectionSolid::operator= (const G4IntersectionSolid & rhs)
Definition at line 112 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 112 of file G4IntersectionSolid.cc
References G4BooleanSolid::operator=().
G4ThreeVector G4IntersectionSolid::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 213 of file G4IntersectionSolid.cc.
View newest version in sPHENIX GitHub at line 213 of file G4IntersectionSolid.cc
References G4VSolid::DistanceToOut(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, G4VSolid::Inside(), kOutside, kSurface, CLHEP::normal(), and G4VSolid::SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/Boolean/include/G4IntersectionSolid.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/Boolean/src/G4IntersectionSolid.cc