ECCE @ EIC Software: G4DeexParametersMessenger Class Reference
G4DeexParametersMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4DeexParametersMessenger.hh>
Public Member Functions
G4DeexParametersMessenger (G4DeexPrecoParameters *)
virtual ~G4DeexParametersMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String) override
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4DeexPrecoParameters * theParameters
G4UIdirectory * fDirectory
G4UIcmdWithABool * readCmd
G4UIcmdWithABool * icCmd
G4UIcmdWithABool * corgCmd
G4UIcmdWithAnInteger * maxjCmd
G4UIcmdWithAnInteger * verbCmd
G4UIcmdWithAnInteger * upCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 67 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4DeexParametersMessenger.hh
Constructor & Destructor Documentation
G4DeexParametersMessenger::G4DeexParametersMessenger (G4DeexPrecoParameters * ptr) explicit
Definition at line 61 of file G4DeexParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 61 of file G4DeexParametersMessenger.cc
References G4UIcommand::AvailableForStates(), corgCmd, fDirectory, G4State_PreInit, icCmd, maxjCmd, readCmd, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), upCmd, and verbCmd.
G4DeexParametersMessenger::~G4DeexParametersMessenger () virtual
Definition at line 106 of file G4DeexParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 106 of file G4DeexParametersMessenger.cc
References corgCmd, fDirectory, icCmd, maxjCmd, readCmd, upCmd, and verbCmd.
Member Function Documentation
void G4DeexParametersMessenger::SetNewValue (G4UIcommand * command, G4String newValue) override virtual
Reimplemented from G4UImessenger.
Definition at line 120 of file G4DeexParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 120 of file G4DeexParametersMessenger.cc
References corgCmd, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithAnInteger::GetNewIntValue(), icCmd, maxjCmd, readCmd, G4DeexPrecoParameters::SetCorrelatedGamma(), G4DeexPrecoParameters::SetInternalConversionFlag(), G4DeexPrecoParameters::SetStoreICLevelData(), G4DeexPrecoParameters::SetTwoJMAX(), G4DeexPrecoParameters::SetUploadZ(), G4DeexPrecoParameters::SetVerbose(), theParameters, upCmd, and verbCmd.
Member Data Documentation
G4UIcmdWithABool* G4DeexParametersMessenger::corgCmd private
Definition at line 84 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), SetNewValue(), and ~G4DeexParametersMessenger().
G4UIdirectory* G4DeexParametersMessenger::fDirectory private
Definition at line 80 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), and ~G4DeexParametersMessenger().
G4UIcmdWithABool* G4DeexParametersMessenger::icCmd private
Definition at line 83 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), SetNewValue(), and ~G4DeexParametersMessenger().
G4UIcmdWithAnInteger* G4DeexParametersMessenger::maxjCmd private
Definition at line 86 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), SetNewValue(), and ~G4DeexParametersMessenger().
G4UIcmdWithABool* G4DeexParametersMessenger::readCmd private
Definition at line 82 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), SetNewValue(), and ~G4DeexParametersMessenger().
G4DeexPrecoParameters* G4DeexParametersMessenger::theParameters private
Definition at line 78 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4DeexParametersMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAnInteger* G4DeexParametersMessenger::upCmd private
Definition at line 88 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), SetNewValue(), and ~G4DeexParametersMessenger().
G4UIcmdWithAnInteger* G4DeexParametersMessenger::verbCmd private
Definition at line 87 of file G4DeexParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4DeexParametersMessenger.hh
Referenced by G4DeexParametersMessenger(), SetNewValue(), and ~G4DeexParametersMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4DeexParametersMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/src/G4DeexParametersMessenger.cc