ECCE @ EIC Software: G4ParticleGun Class Reference
G4ParticleGun Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4ParticleGun.hh>
Public Member Functions
G4ParticleGun ()
G4ParticleGun (G4int numberofparticles)
G4ParticleGun (G4ParticleDefinition *particleDef, G4int numberofparticles=1)
virtual ~G4ParticleGun ()
virtual void GeneratePrimaryVertex (G4Event *evt)
void SetParticleDefinition (G4ParticleDefinition *aParticleDefinition)
void SetParticleEnergy (G4double aKineticEnergy)
void SetParticleMomentum (G4double aMomentum)
void SetParticleMomentum (G4ParticleMomentum aMomentum)
void SetParticleMomentumDirection (G4ParticleMomentum aMomentumDirection)
void SetParticleCharge (G4double aCharge)
void SetParticlePolarization (G4ThreeVector aVal)
void SetNumberOfParticles (G4int i)
G4ParticleDefinition * GetParticleDefinition () const
G4ParticleMomentum GetParticleMomentumDirection () const
G4double GetParticleEnergy () const
G4double GetParticleMomentum () const
G4double GetParticleCharge () const
G4ThreeVector GetParticlePolarization () const
G4int GetNumberOfParticles () const
Public Member Functions inherited from G4VPrimaryGenerator
G4VPrimaryGenerator ()
virtual ~G4VPrimaryGenerator ()
G4ThreeVector GetParticlePosition ()
G4double GetParticleTime ()
void SetParticlePosition (G4ThreeVector aPosition)
void SetParticleTime (G4double aTime)
Protected Member Functions
virtual void SetInitialValues ()
Protected Attributes
G4int NumberOfParticlesToBeGenerated
G4ParticleDefinition * particle_definition
G4ParticleMomentum particle_momentum_direction
G4double particle_energy
G4double particle_momentum
G4double particle_charge
G4ThreeVector particle_polarization
Protected Attributes inherited from G4VPrimaryGenerator
G4ThreeVector particle_position
G4double particle_time
Private Member Functions
G4ParticleGun (const G4ParticleGun &)=delete
const G4ParticleGun & operator= (const G4ParticleGun &)=delete
G4bool operator== (const G4ParticleGun &) const =delete
G4bool operator!= (const G4ParticleGun &) const =delete
Private Attributes
G4ParticleGunMessenger * theMessenger
Additional Inherited Members
Static Public Member Functions inherited from G4VPrimaryGenerator
static G4bool CheckVertexInsideWorld (const G4ThreeVector &pos)
Detailed Description
Definition at line 61 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleGun.hh
Constructor & Destructor Documentation
G4ParticleGun::G4ParticleGun ()
Definition at line 37 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleGun.cc
References SetInitialValues().
G4ParticleGun::G4ParticleGun (G4int numberofparticles)
Definition at line 42 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleGun.cc
References NumberOfParticlesToBeGenerated, and SetInitialValues().
G4ParticleGun::G4ParticleGun (G4ParticleDefinition * particleDef, G4int numberofparticles = 1)
Definition at line 49 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleGun.cc
G4ParticleGun::~G4ParticleGun () virtual
Definition at line 71 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleGun.cc
References theMessenger.
G4ParticleGun::G4ParticleGun (const G4ParticleGun & right) private delete
Definition at line 46 of file pyG4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 46 of file pyG4ParticleGun.cc
References right.
Member Function Documentation
void G4ParticleGun::GeneratePrimaryVertex (G4Event * evt) virtual
Implements G4VPrimaryGenerator.
Definition at line 211 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 211 of file G4ParticleGun.cc
References G4Event::AddPrimaryVertex(), FatalException, G4endl, G4Exception(), G4ParticleDefinition::GetPDGMass(), mass, NumberOfParticlesToBeGenerated, particle, particle_charge, particle_definition, particle_energy, particle_momentum_direction, particle_polarization, G4VPrimaryGenerator::particle_position, G4VPrimaryGenerator::particle_time, G4PrimaryParticle::SetCharge(), G4PrimaryParticle::SetKineticEnergy(), G4PrimaryParticle::SetMass(), G4PrimaryParticle::SetMomentumDirection(), G4PrimaryParticle::SetPolarization(), G4PrimaryVertex::SetPrimary(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by export_G4ParticleGun(), GB01PrimaryGeneratorAction::GeneratePrimaries(), GB02PrimaryGeneratorAction::GeneratePrimaries(), GB03PrimaryGeneratorAction::GeneratePrimaries(), GB06PrimaryGeneratorAction::GeneratePrimaries(), GB07PrimaryGeneratorAction::GeneratePrimaries(), B02PrimaryGeneratorAction::GeneratePrimaries(), B03PrimaryGeneratorAction::GeneratePrimaries(), B01PrimaryGeneratorAction::GeneratePrimaries(), GB04PrimaryGeneratorAction::GeneratePrimaries(), GB05PrimaryGeneratorAction::GeneratePrimaries(), RE06PrimaryGeneratorAction::GeneratePrimaries(), Par01PrimaryGeneratorAction::GeneratePrimaries(), RE03PrimaryGeneratorAction::GeneratePrimaries(), ExTGPrimaryGeneratorAction::GeneratePrimaries(), LXePrimaryGeneratorAction::GeneratePrimaries(), eRositaPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction::GeneratePrimaries(), Par02PrimaryGeneratorAction::GeneratePrimaries(), FCALPrimaryGeneratorAction::GeneratePrimaries(), ExUCNPrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), F05PrimaryGeneratorAction::GeneratePrimaries(), F06PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction1::GeneratePrimaries(), ExN02PrimaryGeneratorAction::GeneratePrimaries(), G01PrimaryGeneratorAction::GeneratePrimaries(), G04PrimaryGeneratorAction::GeneratePrimaries(), ExP02PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction0::GeneratePrimaries(), B2PrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), OpNovicePrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction4::GeneratePrimaries(), PrimaryGeneratorAction3::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction2::GeneratePrimaries(), RE04PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), ExP01PrimaryGeneratorAction::GeneratePrimaries(), F04PrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), F01PrimaryGeneratorAction::GeneratePrimaries(), F02PrimaryGeneratorAction::GeneratePrimaries(), F03PrimaryGeneratorAction::GeneratePrimaries(), RE02PrimaryGeneratorAction::GeneratePrimaries(), GunPrimaryGeneratorAction::GeneratePrimaries(), PurgMagPrimaryGeneratorAction::GeneratePrimaries(), MyPrimaryGeneratorActionFromFile::GeneratePrimaries(), G03PrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), G02PrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), CexmcPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), CCalPrimaryGeneratorAction::GeneratePrimaries(), and CML2PrimaryGenerationAction::GeneratePrimaries().
G4int G4ParticleGun::GetNumberOfParticles () const inline
Definition at line 117 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleGun.hh
References NumberOfParticlesToBeGenerated.
Referenced by export_G4ParticleGun(), G4ParticleGunMessenger::GetCurrentValue(), and CCalPrimaryGeneratorAction::print().
G4double G4ParticleGun::GetParticleCharge () const inline
Definition at line 113 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleGun.hh
References particle_charge.
Referenced by export_G4ParticleGun().
G4ParticleDefinition* G4ParticleGun::GetParticleDefinition () const inline
Definition at line 105 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleGun.hh
References particle_definition.
Referenced by RunAction::BeginOfRunAction(), RunAction::ComputeMscHighland(), Run::EndOfRun(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), export_G4ParticleGun(), Run::FillPerEvent(), B3PrimaryGeneratorAction::GeneratePrimaries(), F02PrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), F01PrimaryGeneratorAction::GeneratePrimaries(), F03PrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), CML2PrimaryGenerationAction::GeneratePrimaries(), G4ParticleGunMessenger::GetCurrentValue(), CCalPrimaryGeneratorAction::print(), CexmcChargeExchangeReconstructor::Reconstruct(), Run::Run(), OpNovicePrimaryGeneratorAction::SetOptPhotonPolar(), PrimaryGeneratorAction::SetOptPhotonPolar(), and CexmcChargeExchangeReconstructor::SetupBeamParticle().
G4double G4ParticleGun::GetParticleEnergy () const inline
Definition at line 109 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleGun.hh
References particle_energy.
Referenced by RunAction::BeginOfRunAction(), RunAction::ComputeMscHighland(), RunAction::ComputeTheory(), EventAction::EndOfEventAction(), Run::EndOfRun(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), export_G4ParticleGun(), Run::FillPerEvent(), FCALPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4ParticleGunMessenger::GetCurrentValue(), CCalPrimaryGeneratorAction::GetParticleEnergy(), CCalPrimaryGeneratorAction::print(), Run::Run(), Run::SurveyConvergence(), and EventAction::WriteFibers().
G4double G4ParticleGun::GetParticleMomentum () const inline
Definition at line 111 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleGun.hh
References particle_momentum.
Referenced by G4ParticleGunMessenger::GetCurrentValue().
G4ParticleMomentum G4ParticleGun::GetParticleMomentumDirection () const inline
Definition at line 107 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleGun.hh
References particle_momentum_direction.
Referenced by export_G4ParticleGun(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4ParticleGunMessenger::GetCurrentValue(), CCalPrimaryGeneratorAction::print(), OpNovicePrimaryGeneratorAction::SetOptPhotonPolar(), PrimaryGeneratorAction::SetOptPhotonPolar(), and EventAction::WriteFibers().
G4ThreeVector G4ParticleGun::GetParticlePolarization () const inline
Definition at line 115 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParticleGun.hh
References particle_polarization.
Referenced by export_G4ParticleGun(), and G4ParticleGunMessenger::GetCurrentValue().
G4bool G4ParticleGun::operator!= (const G4ParticleGun & right) const private delete
Definition at line 74 of file pyG4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 74 of file pyG4ParticleGun.cc
const G4ParticleGun & G4ParticleGun::operator= (const G4ParticleGun & right) private delete
Definition at line 53 of file pyG4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 53 of file pyG4ParticleGun.cc
References NumberOfParticlesToBeGenerated, particle_charge, particle_definition, particle_energy, particle_momentum_direction, and particle_polarization.
G4bool G4ParticleGun::operator== (const G4ParticleGun & right) const private delete
Definition at line 67 of file pyG4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 67 of file pyG4ParticleGun.cc
void G4ParticleGun::SetInitialValues () protected virtual
Definition at line 56 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleGun.cc
References NumberOfParticlesToBeGenerated, particle_charge, particle_definition, particle_energy, particle_momentum, particle_momentum_direction, particle_polarization, G4VPrimaryGenerator::particle_position, G4VPrimaryGenerator::particle_time, theMessenger, and zero.
Referenced by G4ParticleGun().
void G4ParticleGun::SetNumberOfParticles (G4int i) inline
Definition at line 101 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleGun.hh
References NumberOfParticlesToBeGenerated.
Referenced by export_G4ParticleGun(), CML2PrimaryGenerationAction::setGunCalculatedPhaseSpace(), CML2PrimaryGenerationAction::setGunRandom(), and G4ParticleGunMessenger::SetNewValue().
void G4ParticleGun::SetParticleCharge (G4double aCharge) inline
Definition at line 97 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleGun.hh
References particle_charge.
Referenced by export_G4ParticleGun(), B3PrimaryGeneratorAction::GeneratePrimaries(), G4ParticleGunMessenger::IonCommand(), and G4ParticleGunMessenger::IonLevelCommand().
void G4ParticleGun::SetParticleDefinition (G4ParticleDefinition * aParticleDefinition)
Definition at line 101 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleGun.cc
References FatalException, G4endl, G4Exception(), G4ParticleDefinition::GetDecayTable(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::IsShortLived(), JustWarning, and mass.
Referenced by B01PrimaryGeneratorAction::B01PrimaryGeneratorAction(), B02PrimaryGeneratorAction::B02PrimaryGeneratorAction(), B03PrimaryGeneratorAction::B03PrimaryGeneratorAction(), B1PrimaryGeneratorAction::B1PrimaryGeneratorAction(), B2PrimaryGeneratorAction::B2PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), B4PrimaryGeneratorAction::B4PrimaryGeneratorAction(), B5PrimaryGeneratorAction::B5PrimaryGeneratorAction(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction(), eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction(), ExN02PrimaryGeneratorAction::ExN02PrimaryGeneratorAction(), ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction(), ExP02PrimaryGeneratorAction::ExP02PrimaryGeneratorAction(), export_G4ParticleGun(), ExTGPrimaryGeneratorAction::ExTGPrimaryGeneratorAction(), ExUCNPrimaryGeneratorAction::ExUCNPrimaryGeneratorAction(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F04PrimaryGeneratorAction::F04PrimaryGeneratorAction(), F05PrimaryGeneratorAction::F05PrimaryGeneratorAction(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), FCALPrimaryGeneratorAction::FCALPrimaryGeneratorAction(), FFPrimaryGeneratorAction::FFPrimaryGeneratorAction(), G01PrimaryGeneratorAction::G01PrimaryGeneratorAction(), G02PrimaryGeneratorAction::G02PrimaryGeneratorAction(), G03PrimaryGeneratorAction::G03PrimaryGeneratorAction(), G04PrimaryGeneratorAction::G04PrimaryGeneratorAction(), G4ParticleGunMessenger::G4ParticleGunMessenger(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), GB07PrimaryGeneratorAction::GB07PrimaryGeneratorAction(), CML2PrimaryGenerationAction::GenerateFromCalculatedPhaseSpace(), B3PrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), G4ParticleGunMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), LXePrimaryGeneratorAction::LXePrimaryGeneratorAction(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), PurgMagPrimaryGeneratorAction::PurgMagPrimaryGeneratorAction(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::RE06PrimaryGeneratorAction(), CexmcParticleGun::SetBeamParticle(), PrimaryGeneratorAction::SetDefaultKinematic(), CML2PrimaryGenerationAction::setGunRandom(), G4ParticleGunMessenger::SetNewValue(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction(), and XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction().
void G4ParticleGun::SetParticleEnergy (G4double aKineticEnergy)
Definition at line 131 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 131 of file G4ParticleGun.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), GeV, particle_definition, particle_energy, and particle_momentum.
Referenced by B01PrimaryGeneratorAction::B01PrimaryGeneratorAction(), B02PrimaryGeneratorAction::B02PrimaryGeneratorAction(), B03PrimaryGeneratorAction::B03PrimaryGeneratorAction(), B1PrimaryGeneratorAction::B1PrimaryGeneratorAction(), B2PrimaryGeneratorAction::B2PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), B4PrimaryGeneratorAction::B4PrimaryGeneratorAction(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction(), eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction(), ExN02PrimaryGeneratorAction::ExN02PrimaryGeneratorAction(), ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction(), ExP02PrimaryGeneratorAction::ExP02PrimaryGeneratorAction(), export_G4ParticleGun(), ExTGPrimaryGeneratorAction::ExTGPrimaryGeneratorAction(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F04PrimaryGeneratorAction::F04PrimaryGeneratorAction(), FCALPrimaryGeneratorAction::FCALPrimaryGeneratorAction(), FFPrimaryGeneratorAction::FFPrimaryGeneratorAction(), G01PrimaryGeneratorAction::G01PrimaryGeneratorAction(), G02PrimaryGeneratorAction::G02PrimaryGeneratorAction(), G03PrimaryGeneratorAction::G03PrimaryGeneratorAction(), G04PrimaryGeneratorAction::G04PrimaryGeneratorAction(), G4ParticleGunMessenger::G4ParticleGunMessenger(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), GB07PrimaryGeneratorAction::GB07PrimaryGeneratorAction(), PrimaryGeneratorAction1::GeneratePrimaries(), ExUCNPrimaryGeneratorAction::GeneratePrimaries(), F05PrimaryGeneratorAction::GeneratePrimaries(), F06PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction2::GeneratePrimaries(), PrimaryGeneratorAction3::GeneratePrimaries(), PrimaryGeneratorAction4::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), MyPrimaryGeneratorActionFromFile::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), CCalPrimaryGeneratorAction::GeneratePrimaries(), CML2PrimaryGenerationAction::GeneratePrimaries(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), LXePrimaryGeneratorAction::LXePrimaryGeneratorAction(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), PurgMagPrimaryGeneratorAction::PurgMagPrimaryGeneratorAction(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::RE06PrimaryGeneratorAction(), PrimaryGeneratorAction::SetDefaultKinematic(), G4ParticleGunMessenger::SetNewValue(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction(), and XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction().
void G4ParticleGun::SetParticleMomentum (G4double aMomentum)
Definition at line 149 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 149 of file G4ParticleGun.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), GeV, mass, particle_definition, particle_energy, and particle_momentum.
Referenced by export_G4ParticleGun(), CexmcPrimaryGeneratorAction::GeneratePrimaries(), and G4ParticleGunMessenger::SetNewValue().
void G4ParticleGun::SetParticleMomentum (G4ParticleMomentum aMomentum)
Definition at line 179 of file G4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleGun.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), GeV, CLHEP::Hep3Vector::mag(), mass, particle_definition, particle_energy, particle_momentum, particle_momentum_direction, and CLHEP::Hep3Vector::unit().
void G4ParticleGun::SetParticleMomentumDirection (G4ParticleMomentum aMomentumDirection) inline
Definition at line 95 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleGun.hh
References particle_momentum_direction, and CLHEP::Hep3Vector::unit().
Referenced by B01PrimaryGeneratorAction::B01PrimaryGeneratorAction(), B02PrimaryGeneratorAction::B02PrimaryGeneratorAction(), B03PrimaryGeneratorAction::B03PrimaryGeneratorAction(), B1PrimaryGeneratorAction::B1PrimaryGeneratorAction(), B2PrimaryGeneratorAction::B2PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), B4PrimaryGeneratorAction::B4PrimaryGeneratorAction(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction(), eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction(), ExN02PrimaryGeneratorAction::ExN02PrimaryGeneratorAction(), ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction(), export_G4ParticleGun(), ExTGPrimaryGeneratorAction::ExTGPrimaryGeneratorAction(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F04PrimaryGeneratorAction::F04PrimaryGeneratorAction(), G02PrimaryGeneratorAction::G02PrimaryGeneratorAction(), G03PrimaryGeneratorAction::G03PrimaryGeneratorAction(), G4ParticleGunMessenger::G4ParticleGunMessenger(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), GB07PrimaryGeneratorAction::GB07PrimaryGeneratorAction(), FCALPrimaryGeneratorAction::GeneratePrimaries(), ExP02PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction0::GeneratePrimaries(), G04PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction1::GeneratePrimaries(), ExUCNPrimaryGeneratorAction::GeneratePrimaries(), F05PrimaryGeneratorAction::GeneratePrimaries(), F06PrimaryGeneratorAction::GeneratePrimaries(), G01PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction2::GeneratePrimaries(), PrimaryGeneratorAction3::GeneratePrimaries(), PrimaryGeneratorAction4::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), F04PrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), MyPrimaryGeneratorActionFromFile::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), CexmcPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), CCalPrimaryGeneratorAction::GeneratePrimaries(), CML2PrimaryGenerationAction::GeneratePrimaries(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), LXePrimaryGeneratorAction::LXePrimaryGeneratorAction(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), PurgMagPrimaryGeneratorAction::PurgMagPrimaryGeneratorAction(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::RE06PrimaryGeneratorAction(), PrimaryGeneratorAction::SetDefaultKinematic(), G4ParticleGunMessenger::SetNewValue(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction(), and XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction().
void G4ParticleGun::SetParticlePolarization (G4ThreeVector aVal) inline
Definition at line 99 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleGun.hh
References particle_polarization.
Referenced by export_G4ParticleGun(), F05PrimaryGeneratorAction::GeneratePrimaries(), F06PrimaryGeneratorAction::GeneratePrimaries(), ExUCNPrimaryGeneratorAction::GeneratePrimaries(), G4ParticleGunMessenger::SetNewValue(), OpNovicePrimaryGeneratorAction::SetOptPhotonPolar(), and PrimaryGeneratorAction::SetOptPhotonPolar().
Member Data Documentation
G4int G4ParticleGun::NumberOfParticlesToBeGenerated protected
Definition at line 123 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ParticleGun.hh
Referenced by G4ParticleGun(), GeneratePrimaryVertex(), GetNumberOfParticles(), operator=(), SetInitialValues(), and SetNumberOfParticles().
G4double G4ParticleGun::particle_charge protected
Definition at line 128 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleGun.hh
Referenced by GeneratePrimaryVertex(), GetParticleCharge(), operator=(), SetInitialValues(), and SetParticleCharge().
G4ParticleDefinition* G4ParticleGun::particle_definition protected
Definition at line 124 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ParticleGun.hh
Referenced by GeneratePrimaryVertex(), GetParticleDefinition(), operator=(), SetInitialValues(), SetParticleEnergy(), and SetParticleMomentum().
G4double G4ParticleGun::particle_energy protected
Definition at line 126 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleGun.hh
Referenced by GeneratePrimaryVertex(), GetParticleEnergy(), operator=(), CexmcParticleGun::PrepareForNewEvent(), SetInitialValues(), SetParticleEnergy(), and SetParticleMomentum().
G4double G4ParticleGun::particle_momentum protected
Definition at line 127 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ParticleGun.hh
Referenced by GetParticleMomentum(), CexmcParticleGun::PrepareForNewEvent(), SetInitialValues(), SetParticleEnergy(), and SetParticleMomentum().
G4ParticleMomentum G4ParticleGun::particle_momentum_direction protected
Definition at line 125 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleGun.hh
Referenced by GeneratePrimaryVertex(), GetParticleMomentumDirection(), operator=(), SetInitialValues(), SetParticleMomentum(), and SetParticleMomentumDirection().
G4ThreeVector G4ParticleGun::particle_polarization protected
Definition at line 129 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ParticleGun.hh
Referenced by GeneratePrimaryVertex(), GetParticlePolarization(), operator=(), SetInitialValues(), and SetParticlePolarization().
G4ParticleGunMessenger* G4ParticleGun::theMessenger private
Definition at line 132 of file G4ParticleGun.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleGun.hh
Referenced by SetInitialValues(), and ~G4ParticleGun().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4ParticleGun.hh
geant4/tree/geant4-10.6-release/environments/g4py/source/event/pyG4ParticleGun.cc
geant4/tree/geant4-10.6-release/source/event/src/G4ParticleGun.cc