ECCE @ EIC Software: G4VhNuclearStoppingPower Class Reference
G4VhNuclearStoppingPower Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VhNuclearStoppingPower.hh>
Public Member Functions
G4VhNuclearStoppingPower ()
virtual ~G4VhNuclearStoppingPower ()
void SetNuclearStoppingFluctuationsOn ()
void SetNuclearStoppingFluctuationsOff ()
virtual G4double NuclearStoppingPower (G4double kineticEnergy, G4double z1, G4double z2, G4double m1, G4double m2) const =0
Protected Attributes
G4bool lossFlucFlag
Private Member Functions
G4VhNuclearStoppingPower & operator= (const G4VhNuclearStoppingPower &right)
G4VhNuclearStoppingPower (const G4VhNuclearStoppingPower &)
Detailed Description
Definition at line 56 of file G4VhNuclearStoppingPower.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VhNuclearStoppingPower.hh
Constructor & Destructor Documentation
G4VhNuclearStoppingPower::G4VhNuclearStoppingPower ()
Definition at line 56 of file G4VhNuclearStoppingPower.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VhNuclearStoppingPower.cc
G4VhNuclearStoppingPower::~G4VhNuclearStoppingPower () virtual
Definition at line 62 of file G4VhNuclearStoppingPower.cc.
View newest version in sPHENIX GitHub at line 62 of file G4VhNuclearStoppingPower.cc
G4VhNuclearStoppingPower::G4VhNuclearStoppingPower (const G4VhNuclearStoppingPower &) private
Member Function Documentation
virtual G4double G4VhNuclearStoppingPower::NuclearStoppingPower (G4double kineticEnergy, G4double z1, G4double z2, G4double m1, G4double m2) const pure virtual
Implemented in G4hZiegler1985Nuclear, and G4hICRU49Nuclear.
G4VhNuclearStoppingPower& G4VhNuclearStoppingPower::operator= (const G4VhNuclearStoppingPower & right) private
void G4VhNuclearStoppingPower::SetNuclearStoppingFluctuationsOff () inline
Definition at line 67 of file G4VhNuclearStoppingPower.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VhNuclearStoppingPower.hh
References lossFlucFlag.
Referenced by G4hNuclearStoppingModel::InitializeMe(), and G4hNuclearStoppingModel::SetNuclearStoppingFluctuationsOff().
void G4VhNuclearStoppingPower::SetNuclearStoppingFluctuationsOn () inline
Definition at line 65 of file G4VhNuclearStoppingPower.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VhNuclearStoppingPower.hh
References lossFlucFlag.
Referenced by G4hNuclearStoppingModel::SetNuclearStoppingFluctuationsOn().
Member Data Documentation
G4bool G4VhNuclearStoppingPower::lossFlucFlag protected
Definition at line 74 of file G4VhNuclearStoppingPower.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VhNuclearStoppingPower.hh
Referenced by G4hICRU49Nuclear::NuclearStoppingPower(), G4hZiegler1985Nuclear::NuclearStoppingPower(), SetNuclearStoppingFluctuationsOff(), and SetNuclearStoppingFluctuationsOn().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VhNuclearStoppingPower.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VhNuclearStoppingPower.cc