ECCE @ EIC Software: G4PrimaryParticle Class Reference
G4PrimaryParticle Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4PrimaryParticle.hh>
Public Member Functions
void * operator new (size_t)
void operator delete (void *aStackedTrack)
G4PrimaryParticle ()
G4PrimaryParticle (G4int Pcode)
G4PrimaryParticle (G4int Pcode, G4double px, G4double py, G4double pz)
G4PrimaryParticle (G4int Pcode, G4double px, G4double py, G4double pz, G4double E)
G4PrimaryParticle (const G4ParticleDefinition *Gcode)
G4PrimaryParticle (const G4ParticleDefinition *Gcode, G4double px, G4double py, G4double pz)
G4PrimaryParticle (const G4ParticleDefinition *Gcode, G4double px, G4double py, G4double pz, G4double E)
virtual ~G4PrimaryParticle ()
G4PrimaryParticle (const G4PrimaryParticle &right)
G4PrimaryParticle & operator= (const G4PrimaryParticle &right)
G4bool operator== (const G4PrimaryParticle &right) const
G4bool operator!= (const G4PrimaryParticle &right) const
void Print () const
G4int GetPDGcode () const
void SetPDGcode (G4int Pcode)
G4ParticleDefinition * GetG4code () const
void SetG4code (const G4ParticleDefinition *Gcode)
const G4ParticleDefinition * GetParticleDefinition () const
void SetParticleDefinition (const G4ParticleDefinition *pdef)
G4double GetMass () const
void SetMass (G4double mas)
G4double GetCharge () const
void SetCharge (G4double chg)
G4double GetKineticEnergy () const
void SetKineticEnergy (G4double eKin)
const G4ThreeVector & GetMomentumDirection () const
void SetMomentumDirection (const G4ThreeVector &p)
G4double GetTotalMomentum () const
void Set4Momentum (G4double px, G4double py, G4double pz, G4double E)
G4double GetTotalEnergy () const
void SetTotalEnergy (G4double eTot)
G4ThreeVector GetMomentum () const
void SetMomentum (G4double px, G4double py, G4double pz)
G4double GetPx () const
G4double GetPy () const
G4double GetPz () const
G4PrimaryParticle * GetNext () const
void SetNext (G4PrimaryParticle *np)
void ClearNext ()
G4PrimaryParticle * GetDaughter () const
void SetDaughter (G4PrimaryParticle *np)
G4int GetTrackID () const
void SetTrackID (G4int id)
G4ThreeVector GetPolarization () const
void SetPolarization (const G4ThreeVector &pol)
void SetPolarization (G4double px, G4double py, G4double pz)
G4double GetPolX () const
G4double GetPolY () const
G4double GetPolZ () const
G4double GetWeight () const
void SetWeight (G4double w)
G4double GetProperTime () const
void SetProperTime (G4double t)
G4VUserPrimaryParticleInformation * GetUserInformation () const
void SetUserInformation (G4VUserPrimaryParticleInformation *anInfo)
Private Attributes
G4int PDGcode
const G4ParticleDefinition * G4code
G4ThreeVector direction
G4double kinE
G4PrimaryParticle * nextParticle
G4PrimaryParticle * daughterParticle
G4int trackID
G4double mass
G4double charge
G4double polX
G4double polY
G4double polZ
G4double Weight0
G4double properTime
G4VUserPrimaryParticleInformation * userInfo
Detailed Description
Definition at line 67 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PrimaryParticle.hh
Constructor & Destructor Documentation
G4PrimaryParticle::G4PrimaryParticle ()
Definition at line 42 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 42 of file G4PrimaryParticle.cc
Referenced by operator=().
G4PrimaryParticle::G4PrimaryParticle (G4int Pcode)
Definition at line 50 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PrimaryParticle.cc
References charge, G4ParticleTable::FindParticle(), G4code, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), and mass.
G4PrimaryParticle::G4PrimaryParticle (G4int Pcode, G4double px, G4double py, G4double pz)
Definition at line 64 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 64 of file G4PrimaryParticle.cc
References charge, G4ParticleTable::FindParticle(), G4code, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, and SetMomentum().
G4PrimaryParticle::G4PrimaryParticle (G4int Pcode, G4double px, G4double py, G4double pz, G4double E)
Definition at line 80 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 80 of file G4PrimaryParticle.cc
References charge, G4ParticleTable::FindParticle(), G4code, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, and Set4Momentum().
G4PrimaryParticle::G4PrimaryParticle (const G4ParticleDefinition * Gcode)
Definition at line 96 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 96 of file G4PrimaryParticle.cc
References charge, G4code, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), mass, and PDGcode.
G4PrimaryParticle::G4PrimaryParticle (const G4ParticleDefinition * Gcode, G4double px, G4double py, G4double pz)
Definition at line 110 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 110 of file G4PrimaryParticle.cc
References charge, G4code, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), mass, PDGcode, and SetMomentum().
G4PrimaryParticle::G4PrimaryParticle (const G4ParticleDefinition * Gcode, G4double px, G4double py, G4double pz, G4double E)
Definition at line 126 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 126 of file G4PrimaryParticle.cc
References charge, G4code, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), mass, PDGcode, and Set4Momentum().
G4PrimaryParticle::~G4PrimaryParticle () virtual
Definition at line 193 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 193 of file G4PrimaryParticle.cc
References daughterParticle, nextParticle, and userInfo.
G4PrimaryParticle::G4PrimaryParticle (const G4PrimaryParticle & right)
Definition at line 142 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 142 of file G4PrimaryParticle.cc
References right.
Member Function Documentation
void G4PrimaryParticle::ClearNext () inline
Definition at line 304 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 304 of file G4PrimaryParticle.hh
References nextParticle.
Referenced by G4PrimaryVertex::~G4PrimaryVertex().
G4double G4PrimaryParticle::GetCharge () const inline
Definition at line 200 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 200 of file G4PrimaryParticle.hh
References charge.
Referenced by export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), RE01Trajectory::RE01Trajectory(), and G4PrimaryTransformer::SetDecayProducts().
G4PrimaryParticle * G4PrimaryParticle::GetDaughter () const inline
Definition at line 257 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 257 of file G4PrimaryParticle.hh
References daughterParticle.
Referenced by G4PrimaryTransformer::GenerateSingleTrack(), RE01EventAction::PrintPrimary(), and G4PrimaryTransformer::SetDecayProducts().
G4ParticleDefinition * G4PrimaryParticle::GetG4code () const inline
Definition at line 206 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 206 of file G4PrimaryParticle.hh
References G4code.
Referenced by RMC01AnalysisManager::EndOfEventForForwardSimulation(), export_G4PrimaryParticle(), G4PrimaryTransformer::GetDefinition(), RE01EventAction::PrintPrimary(), and RE01Trajectory::RE01Trajectory().
G4double G4PrimaryParticle::GetKineticEnergy () const inline
Definition at line 248 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 248 of file G4PrimaryParticle.hh
References kinE.
Referenced by G4PrimaryTransformer::GenerateSingleTrack().
G4double G4PrimaryParticle::GetMass () const inline
Definition at line 197 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 197 of file G4PrimaryParticle.hh
References mass.
Referenced by export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), and G4PrimaryTransformer::SetDecayProducts().
G4ThreeVector G4PrimaryParticle::GetMomentum () const inline
Definition at line 218 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 218 of file G4PrimaryParticle.hh
References direction, and GetTotalMomentum().
Referenced by ExGflashEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), export_G4PrimaryParticle(), Par02PrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), G4PrimaryTransformer::GenerateSingleTrack(), RE01EventAction::PrintPrimary(), and G4PrimaryTransformer::SetDecayProducts().
const G4ThreeVector & G4PrimaryParticle::GetMomentumDirection () const inline
Definition at line 221 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 221 of file G4PrimaryParticle.hh
References direction.
Referenced by G4PrimaryTransformer::GenerateSingleTrack().
G4PrimaryParticle * G4PrimaryParticle::GetNext () const inline
Definition at line 254 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 254 of file G4PrimaryParticle.hh
References nextParticle.
Referenced by PHG4TruthEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), G4PrimaryTransformer::GenerateTracks(), G4PrimaryVertex::GetPrimary(), G4PrimaryVertex::operator=(), RE01EventAction::PrintPrimary(), G4PrimaryTransformer::SetDecayProducts(), and G4PrimaryVertex::~G4PrimaryVertex().
const G4ParticleDefinition * G4PrimaryParticle::GetParticleDefinition () const inline
Definition at line 209 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 209 of file G4PrimaryParticle.hh
References G4code.
G4int G4PrimaryParticle::GetPDGcode () const inline
Definition at line 203 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 203 of file G4PrimaryParticle.hh
References PDGcode.
Referenced by export_G4PrimaryParticle(), Par02PrimaryGeneratorAction::GeneratePrimaries(), G4PrimaryTransformer::GenerateSingleTrack(), G4PrimaryTransformer::GetDefinition(), RE01EventAction::PrintPrimary(), RE01Trajectory::RE01Trajectory(), and G4PrimaryTransformer::SetDecayProducts().
G4ThreeVector G4PrimaryParticle::GetPolarization () const inline
Definition at line 263 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 263 of file G4PrimaryParticle.hh
References polX, polY, and polZ.
Referenced by export_G4PrimaryParticle(), and G4PrimaryTransformer::GenerateSingleTrack().
G4double G4PrimaryParticle::GetPolX () const inline
Definition at line 266 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 266 of file G4PrimaryParticle.hh
References polX.
Referenced by export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), and G4PrimaryTransformer::SetDecayProducts().
G4double G4PrimaryParticle::GetPolY () const inline
Definition at line 269 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 269 of file G4PrimaryParticle.hh
References polY.
Referenced by export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), and G4PrimaryTransformer::SetDecayProducts().
G4double G4PrimaryParticle::GetPolZ () const inline
Definition at line 272 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 272 of file G4PrimaryParticle.hh
References polZ.
Referenced by export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), and G4PrimaryTransformer::SetDecayProducts().
G4double G4PrimaryParticle::GetProperTime () const inline
Definition at line 284 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 284 of file G4PrimaryParticle.hh
References properTime.
Referenced by export_G4PrimaryParticle(), G4PrimaryTransformer::GenerateSingleTrack(), and G4PrimaryTransformer::SetDecayProducts().
G4double G4PrimaryParticle::GetPx () const inline
Definition at line 227 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 227 of file G4PrimaryParticle.hh
References direction, GetTotalMomentum(), and CLHEP::Hep3Vector::x().
Referenced by export_G4PrimaryParticle().
G4double G4PrimaryParticle::GetPy () const inline
Definition at line 230 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 230 of file G4PrimaryParticle.hh
References direction, GetTotalMomentum(), and CLHEP::Hep3Vector::y().
Referenced by export_G4PrimaryParticle().
G4double G4PrimaryParticle::GetPz () const inline
Definition at line 233 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 233 of file G4PrimaryParticle.hh
References direction, GetTotalMomentum(), and CLHEP::Hep3Vector::z().
Referenced by export_G4PrimaryParticle().
G4double G4PrimaryParticle::GetTotalEnergy () const inline
Definition at line 236 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 236 of file G4PrimaryParticle.hh
References kinE, and mass.
G4double G4PrimaryParticle::GetTotalMomentum () const inline
Definition at line 212 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 212 of file G4PrimaryParticle.hh
References kinE, and mass.
Referenced by GetMomentum(), GetPx(), GetPy(), GetPz(), and Print().
G4int G4PrimaryParticle::GetTrackID () const inline
Definition at line 260 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 260 of file G4PrimaryParticle.hh
References trackID.
Referenced by export_G4PrimaryParticle(), and RE01EventAction::PrintPrimary().
G4VUserPrimaryParticleInformation * G4PrimaryParticle::GetUserInformation () const inline
Definition at line 290 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 290 of file G4PrimaryParticle.hh
References userInfo.
Referenced by PHG4TruthEventAction::EndOfEventAction(), Par02TrackingAction::PostUserTrackingAction(), and PHG4TruthTrackingAction::PreUserTrackingAction().
G4double G4PrimaryParticle::GetWeight () const inline
Definition at line 275 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 275 of file G4PrimaryParticle.hh
References Weight0.
Referenced by export_G4PrimaryParticle(), and G4PrimaryTransformer::GenerateSingleTrack().
void G4PrimaryParticle::operator delete (void * aStackedTrack) inline
Definition at line 192 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 192 of file G4PrimaryParticle.hh
References aPrimaryParticleAllocator().
void * G4PrimaryParticle::operator new (size_t) inline
Definition at line 183 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 183 of file G4PrimaryParticle.hh
References aPrimaryParticleAllocator().
G4bool G4PrimaryParticle::operator!= (const G4PrimaryParticle & right) const
Definition at line 190 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 190 of file G4PrimaryParticle.cc
G4PrimaryParticle & G4PrimaryParticle::operator= (const G4PrimaryParticle & right)
Definition at line 152 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 152 of file G4PrimaryParticle.cc
References charge, daughterParticle, direction, G4code, G4PrimaryParticle(), kinE, mass, nextParticle, PDGcode, polX, polY, polZ, properTime, trackID, userInfo, and Weight0.
G4bool G4PrimaryParticle::operator== (const G4PrimaryParticle & right) const
Definition at line 187 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 187 of file G4PrimaryParticle.cc
void G4PrimaryParticle::Print (void) const
Definition at line 263 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 263 of file G4PrimaryParticle.cc
References charge, daughterParticle, direction, eplus, G4code, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), GetTotalMomentum(), GeV, kinE, mass, nextParticle, ns, PDGcode, polX, polY, polZ, G4VUserPrimaryParticleInformation::Print(), Print(), properTime, userInfo, Weight0, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by export_G4PrimaryParticle(), G4PrimaryVertex::Print(), and Print().
void G4PrimaryParticle::Set4Momentum (G4double px, G4double py, G4double pz, G4double E)
Definition at line 223 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 223 of file G4PrimaryParticle.cc
References direction, G4code, G4ParticleDefinition::GetPDGMass(), kinE, mass, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by export_G4PrimaryParticle(), and G4PrimaryParticle().
void G4PrimaryParticle::SetCharge (G4double chg) inline
Definition at line 321 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 321 of file G4PrimaryParticle.hh
References charge.
Referenced by export_G4PrimaryParticle(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), and G4SingleParticleSource::GeneratePrimaryVertex().
void G4PrimaryParticle::SetDaughter (G4PrimaryParticle * np) inline
Definition at line 309 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 309 of file G4PrimaryParticle.hh
References daughterParticle, and SetNext().
Referenced by G4HEPEvtInterface::GeneratePrimaryVertex().
void G4PrimaryParticle::SetG4code (const G4ParticleDefinition * Gcode) inline
Definition at line 293 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 293 of file G4PrimaryParticle.hh
References SetParticleDefinition().
void G4PrimaryParticle::SetKineticEnergy (G4double eKin) inline
Definition at line 251 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 251 of file G4PrimaryParticle.hh
References kinE.
Referenced by PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGenerator::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
void G4PrimaryParticle::SetMass (G4double mas) inline
Definition at line 318 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 318 of file G4PrimaryParticle.hh
References mass.
Referenced by export_G4PrimaryParticle(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
void G4PrimaryParticle::SetMomentum (G4double px, G4double py, G4double pz)
Definition at line 209 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 209 of file G4PrimaryParticle.cc
References direction, G4code, G4ParticleDefinition::GetPDGMass(), kinE, mass, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by G4PrimaryParticle(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), and G4HEPEvtInterface::GeneratePrimaryVertex().
void G4PrimaryParticle::SetMomentumDirection (const G4ThreeVector & p) inline
Definition at line 224 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 224 of file G4PrimaryParticle.hh
References direction.
Referenced by export_G4PrimaryParticle(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGenerator::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
void G4PrimaryParticle::SetNext (G4PrimaryParticle * np) inline
Definition at line 298 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 298 of file G4PrimaryParticle.hh
References nextParticle, and SetNext().
Referenced by SetDaughter(), SetNext(), and G4PrimaryVertex::SetPrimary().
void G4PrimaryParticle::SetParticleDefinition (const G4ParticleDefinition * pdef)
Definition at line 253 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 253 of file G4PrimaryParticle.cc
References charge, G4code, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), mass, and PDGcode.
Referenced by SetG4code().
void G4PrimaryParticle::SetPDGcode (G4int Pcode)
Definition at line 243 of file G4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 243 of file G4PrimaryParticle.cc
References charge, G4ParticleTable::FindParticle(), G4code, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, and PDGcode.
void G4PrimaryParticle::SetPolarization (const G4ThreeVector & pol) inline
Definition at line 331 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 331 of file G4PrimaryParticle.hh
References polX, polY, polZ, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
void G4PrimaryParticle::SetPolarization (G4double px, G4double py, G4double pz) inline
Definition at line 324 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 324 of file G4PrimaryParticle.hh
References polX, polY, and polZ.
void G4PrimaryParticle::SetProperTime (G4double t) inline
Definition at line 281 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 281 of file G4PrimaryParticle.hh
References properTime, and t.
void G4PrimaryParticle::SetTotalEnergy (G4double eTot) inline
Definition at line 242 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 242 of file G4PrimaryParticle.hh
References kinE, and mass.
void G4PrimaryParticle::SetTrackID (G4int id) inline
Definition at line 315 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 315 of file G4PrimaryParticle.hh
References trackID.
Referenced by G4PrimaryTransformer::GenerateSingleTrack(), and G4EventManager::StackTracks().
void G4PrimaryParticle::SetUserInformation (G4VUserPrimaryParticleInformation * anInfo) inline
Definition at line 287 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 287 of file G4PrimaryParticle.hh
References userInfo.
Referenced by PHG4PrimaryGeneratorAction::GeneratePrimaries(), and Par02PrimaryGeneratorAction::GeneratePrimaries().
void G4PrimaryParticle::SetWeight (G4double w) inline
Definition at line 278 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 278 of file G4PrimaryParticle.hh
References w, and Weight0.
Referenced by export_G4PrimaryParticle(), and G4SingleParticleSource::GeneratePrimaryVertex().
Member Data Documentation
G4double G4PrimaryParticle::charge private
Definition at line 171 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 171 of file G4PrimaryParticle.hh
Referenced by G4PrimaryParticle(), GetCharge(), operator=(), Print(), SetCharge(), SetParticleDefinition(), and SetPDGcode().
G4PrimaryParticle* G4PrimaryParticle::daughterParticle private
Definition at line 164 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 164 of file G4PrimaryParticle.hh
Referenced by GetDaughter(), operator=(), Print(), SetDaughter(), and ~G4PrimaryParticle().
G4ThreeVector G4PrimaryParticle::direction private
Definition at line 160 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 160 of file G4PrimaryParticle.hh
Referenced by GetMomentum(), GetMomentumDirection(), GetPx(), GetPy(), GetPz(), operator=(), Print(), Set4Momentum(), SetMomentum(), and SetMomentumDirection().
const G4ParticleDefinition* G4PrimaryParticle::G4code private
Definition at line 158 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 158 of file G4PrimaryParticle.hh
Referenced by G4PrimaryParticle(), GetG4code(), GetParticleDefinition(), operator=(), Print(), Set4Momentum(), SetMomentum(), SetParticleDefinition(), and SetPDGcode().
G4double G4PrimaryParticle::kinE private
Definition at line 161 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 161 of file G4PrimaryParticle.hh
Referenced by GetKineticEnergy(), GetTotalEnergy(), GetTotalMomentum(), operator=(), Print(), Set4Momentum(), SetKineticEnergy(), SetMomentum(), and SetTotalEnergy().
G4double G4PrimaryParticle::mass private
Definition at line 170 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PrimaryParticle.hh
Referenced by G4PrimaryParticle(), GetMass(), GetTotalEnergy(), GetTotalMomentum(), operator=(), Print(), Set4Momentum(), SetMass(), SetMomentum(), SetParticleDefinition(), SetPDGcode(), and SetTotalEnergy().
G4PrimaryParticle* G4PrimaryParticle::nextParticle private
Definition at line 163 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 163 of file G4PrimaryParticle.hh
Referenced by ClearNext(), GetNext(), operator=(), Print(), SetNext(), and ~G4PrimaryParticle().
G4int G4PrimaryParticle::PDGcode private
Definition at line 157 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 157 of file G4PrimaryParticle.hh
Referenced by G4PrimaryParticle(), GetPDGcode(), operator=(), Print(), SetParticleDefinition(), and SetPDGcode().
G4double G4PrimaryParticle::polX private
Definition at line 172 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 172 of file G4PrimaryParticle.hh
Referenced by GetPolarization(), GetPolX(), operator=(), Print(), and SetPolarization().
G4double G4PrimaryParticle::polY private
Definition at line 173 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 173 of file G4PrimaryParticle.hh
Referenced by GetPolarization(), GetPolY(), operator=(), Print(), and SetPolarization().
G4double G4PrimaryParticle::polZ private
Definition at line 174 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 174 of file G4PrimaryParticle.hh
Referenced by GetPolarization(), GetPolZ(), operator=(), Print(), and SetPolarization().
G4double G4PrimaryParticle::properTime private
Definition at line 176 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 176 of file G4PrimaryParticle.hh
Referenced by GetProperTime(), operator=(), Print(), and SetProperTime().
G4int G4PrimaryParticle::trackID private
Definition at line 166 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PrimaryParticle.hh
Referenced by GetTrackID(), operator=(), and SetTrackID().
G4VUserPrimaryParticleInformation* G4PrimaryParticle::userInfo private
Definition at line 177 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 177 of file G4PrimaryParticle.hh
Referenced by GetUserInformation(), operator=(), Print(), SetUserInformation(), and ~G4PrimaryParticle().
G4double G4PrimaryParticle::Weight0 private
Definition at line 175 of file G4PrimaryParticle.hh.
View newest version in sPHENIX GitHub at line 175 of file G4PrimaryParticle.hh
Referenced by GetWeight(), operator=(), Print(), and SetWeight().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4PrimaryParticle.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4PrimaryParticle.cc