ECCE @ EIC Software: HEPREP::HepRepFactory Class Reference
HEPREP::HepRepFactory Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepFactory.h>
Public Member Functions
virtual ~HepRepFactory ()
Destructor.
virtual HepRepReader * createHepRepReader (std::istream *in)=0
virtual HepRepReader * createHepRepReader (std::string inputFileName)=0
virtual HepRepWriter * createHepRepWriter (std::ostream *out, bool randomAccess, bool compress)=0
virtual HepRepPoint * createHepRepPoint (HepRepInstance *instance, double x, double y, double z)=0
virtual HepRepInstance * createHepRepInstance (HepRepInstance *parent, HepRepType *type)=0
virtual HepRepInstance * createHepRepInstance (HepRepInstanceTree *parent, HepRepType *type)=0
virtual HepRepTreeID * createHepRepTreeID (std::string name, std::string version, std::string qualifier="top-level")=0
virtual HepRepAction * createHepRepAction (std::string name, std::string expression)=0
virtual HepRepInstanceTree * createHepRepInstanceTree (std::string name, std::string version, HepRepTreeID *typeTree)=0
virtual HepRepType * createHepRepType (HepRepTypeTree *parent, std::string name)=0
virtual HepRepType * createHepRepType (HepRepType *parent, std::string name)=0
virtual HepRepTypeTree * createHepRepTypeTree (HepRepTreeID *treeID)=0
virtual HepRep * createHepRep ()=0
Detailed Description
HepRepFactory interface.
Author
Mark Donszelmann
Definition at line 33 of file HepRepFactory.h.
View newest version in sPHENIX GitHub at line 33 of file HepRepFactory.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepFactory::~HepRepFactory () inline virtual
Destructor.
Definition at line 37 of file HepRepFactory.h.
View newest version in sPHENIX GitHub at line 37 of file HepRepFactory.h
Member Function Documentation
virtual HepRep* HEPREP::HepRepFactory::createHepRep () pure virtual
Creates a HepRep.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::getHepRep(), and G4HepRepSceneHandler::getHepRepGeometry().
virtual HepRepAction* HEPREP::HepRepFactory::createHepRepAction (std::string name, std::string expression) pure virtual
Creates a HepRepAction.
Parameters
name of the action.
expression of the action.
Implemented in cheprep::DefaultHepRepFactory.
virtual HepRepInstance* HEPREP::HepRepFactory::createHepRepInstance (HepRepInstance * parent, HepRepType * type) pure virtual
Creates a HepRepInstance.
to add the instance to. type the associated type.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddSolid(), G4HepRepSceneHandler::getEventInstance(), G4HepRepSceneHandler::getGeometryInstance(), G4HepRepSceneHandler::getGeometryOrEventInstance(), and G4HepRepSceneHandler::getGeometryRootInstance().
virtual HepRepInstance* HEPREP::HepRepFactory::createHepRepInstance (HepRepInstanceTree * parent, HepRepType * type) pure virtual
Creates a HepRepInstance.
to add the instance to. type the associated type.
Implemented in cheprep::DefaultHepRepFactory.
virtual HepRepInstanceTree* HEPREP::HepRepFactory::createHepRepInstanceTree (std::string name, std::string version, HepRepTreeID * typeTree) pure virtual
Creates a HepRepInstanceTree.
The tree needs to be added to the HepRep.
Parameters
name of the instancetree.
version of the instancetree.
typeTree associated typetree.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::getEventInstanceTree(), and G4HepRepSceneHandler::getGeometryInstanceTree().
virtual HepRepPoint* HEPREP::HepRepFactory::createHepRepPoint (HepRepInstance * instance, double x, double y, double z) pure virtual
Creates a HepRepPoint.
Parameters
instance to add the point to.
x x coordinate of point.
y y coordinate of point.
z z coordinate of point.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::AddPrimitive(), and G4HepRepSceneHandler::AddSolid().
virtual HepRepReader* HEPREP::HepRepFactory::createHepRepReader (std::istream * in) pure virtual
Creates a HepRepReader from a stream.
Parameters
in input stream.
Implemented in cheprep::DefaultHepRepFactory, and cheprep::XMLHepRepFactory.
virtual HepRepReader* HEPREP::HepRepFactory::createHepRepReader (std::string inputFileName) pure virtual
Creates a HepRepReader from a file name.
Parameters
inputFileName file name.
Implemented in cheprep::DefaultHepRepFactory, and cheprep::XMLHepRepFactory.
virtual HepRepTreeID* HEPREP::HepRepFactory::createHepRepTreeID (std::string name, std::string version, std::string qualifier = "top-level") pure virtual
Creates a HepRepTreeID.
Parameters
name of the treeID.
version of the treeID.
qualifier of the treeID.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::closeHepRep(), G4HepRepSceneHandler::getEventTypeTree(), and G4HepRepSceneHandler::getGeometryTypeTree().
virtual HepRepType* HEPREP::HepRepFactory::createHepRepType (HepRepTypeTree * parent, std::string name) pure virtual
Creates a HepRepType.
Parameters
parent to add this type to.
name of the type to create.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::getCalHitFaceType(), G4HepRepSceneHandler::getCalHitType(), G4HepRepSceneHandler::getEventType(), G4HepRepSceneHandler::getFullTypeName(), G4HepRepSceneHandler::getGeometryRootType(), G4HepRepSceneHandler::getGeometryType(), G4HepRepSceneHandler::getHitType(), and G4HepRepSceneHandler::getTrajectoryType().
virtual HepRepType* HEPREP::HepRepFactory::createHepRepType (HepRepType * parent, std::string name) pure virtual
Creates a HepRepType.
Parameters
parent to add this type to.
name of the type to create.
Implemented in cheprep::DefaultHepRepFactory.
virtual HepRepTypeTree* HEPREP::HepRepFactory::createHepRepTypeTree (HepRepTreeID * treeID) pure virtual
Creates a HepRepTypeTree.
The tree needs to be added to the HepRep.
Parameters
treeID to name the tree being created.
Implemented in cheprep::DefaultHepRepFactory.
Referenced by G4HepRepSceneHandler::getEventTypeTree(), and G4HepRepSceneHandler::getGeometryTypeTree().
virtual HepRepWriter* HEPREP::HepRepFactory::createHepRepWriter (std::ostream * out, bool randomAccess, bool compress) pure virtual
Creates a HepRepWriter.
Parameters
out output stream.
randomAccess create a writer in a format that will allow random access (may be ignored).
compress create a writer that uses compression (may be ignored).
Implemented in cheprep::DefaultHepRepFactory, and cheprep::XMLHepRepFactory.
Referenced by G4HepRepSceneHandler::open(), and G4HepRepSceneHandler::openFile().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepFactory.h