ECCE @ EIC Software: F04SteppingAction Class Reference
F04SteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04SteppingAction.hh>
Public Member Functions
F04SteppingAction ()
virtual ~F04SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
F04SteppingActionMessenger * fSteppingMessenger
G4LogicalVolume * fTargetVolume
G4LogicalVolume * fTestPlaneVolume
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 42 of file F04SteppingAction.hh.
View newest version in sPHENIX GitHub at line 42 of file F04SteppingAction.hh
Constructor & Destructor Documentation
F04SteppingAction::F04SteppingAction ()
Definition at line 44 of file F04SteppingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file F04SteppingAction.cc
References fSteppingMessenger.
F04SteppingAction::~F04SteppingAction () virtual
Definition at line 55 of file F04SteppingAction.cc.
View newest version in sPHENIX GitHub at line 55 of file F04SteppingAction.cc
References fSteppingMessenger.
Member Function Documentation
void F04SteppingAction::UserSteppingAction (const G4Step * theStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 62 of file F04SteppingAction.cc.
View newest version in sPHENIX GitHub at line 62 of file F04SteppingAction.cc
References fAlive, fStopAndKill, fTargetVolume, fTestPlaneVolume, G4LogicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMomentumDirection(), G4Track::GetParentID(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4Step::GetTrack(), G4Track::GetTrackStatus(), F04UserTrackInformation::GetTrackStatusFlag(), G4Track::GetUserInformation(), G4Track::GetVertexMomentumDirection(), G4LogicalVolumeStore::GetVolume(), reverse, G4Track::SetTrackStatus(), F04UserTrackInformation::SetTrackStatusFlag(), and CLHEP::Hep3Vector::z().
Member Data Documentation
F04SteppingActionMessenger* F04SteppingAction::fSteppingMessenger private
Definition at line 53 of file F04SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file F04SteppingAction.hh
Referenced by F04SteppingAction(), and ~F04SteppingAction().
G4LogicalVolume* F04SteppingAction::fTargetVolume private
Definition at line 54 of file F04SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file F04SteppingAction.hh
Referenced by UserSteppingAction().
G4LogicalVolume* F04SteppingAction::fTestPlaneVolume private
Definition at line 55 of file F04SteppingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file F04SteppingAction.hh
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04SteppingAction.cc