ECCE @ EIC Software: G4VFilter< T > Class Template Reference
G4VFilter< T > Class Template Reference abstract
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VFilter.hh>
Public Types
typedef T Type
Public Member Functions
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
virtual G4bool Accept (const T &) const =0
virtual void PrintAll (std::ostream &ostr) const =0
virtual void Reset ()=0
G4String Name () const
G4String GetName () const
Private Attributes
G4String fName
Detailed Description
template<typename T>
class G4VFilter< T >
Definition at line 39 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VFilter.hh
Member Typedef Documentation
template<typename T> typedef T G4VFilter< T >::Type
Definition at line 43 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VFilter.hh
Constructor & Destructor Documentation
template<typename T > G4VFilter< T >::G4VFilter (const G4String & name)
Definition at line 71 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VFilter.hh
template<typename T > G4VFilter< T >::~G4VFilter () virtual
Definition at line 76 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VFilter.hh
Member Function Documentation
template<typename T> virtual G4bool G4VFilter< T >::Accept (const T &) const pure virtual
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >, G4SmartFilter< T >, G4SmartFilter< G4VTrajectory >, and G4VAttValueFilter.
template<typename T > G4String G4VFilter< T >::GetName (void) const
Definition at line 87 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VFilter.hh
References configureMap::Name.
template<typename T > G4String G4VFilter< T >::Name () const
Definition at line 80 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VFilter.hh
References fName.
Referenced by G4SmartFilter< T >::Accept(), G4AttributeFilterT< T >::Print(), and G4SmartFilter< T >::PrintAll().
template<typename T> virtual void G4VFilter< T >::PrintAll (std::ostream & ostr) const pure virtual
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >, G4SmartFilter< T >, G4SmartFilter< G4VTrajectory >, and G4VAttValueFilter.
template<typename T> virtual void G4VFilter< T >::Reset () pure virtual
Implemented in G4AttValueFilterT< T, ConversionErrorPolicy >, G4SmartFilter< T >, G4SmartFilter< G4VTrajectory >, and G4VAttValueFilter.
Member Data Documentation
template<typename T> G4String G4VFilter< T >::fName private
Definition at line 66 of file G4VFilter.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VFilter.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VFilter.hh