ECCE @ EIC Software: G4Para Class Reference
G4Para Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Para.hh>
Public Member Functions
G4Para (const G4String &pName, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
G4Para (const G4String &pName, const G4ThreeVector pt[8])
virtual ~G4Para ()
G4double GetZHalfLength () const
G4ThreeVector GetSymAxis () const
G4double GetYHalfLength () const
G4double GetXHalfLength () const
G4double GetTanAlpha () const
void SetXHalfLength (G4double val)
void SetYHalfLength (G4double val)
void SetZHalfLength (G4double val)
void SetAlpha (G4double alpha)
void SetTanAlpha (G4double val)
void SetThetaAndPhi (double pTheta, double pPhi)
void SetAllParameters (G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Para (__void__ &)
G4Para (const G4Para &rhs)
G4Para & operator= (const G4Para &rhs)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
void CheckParameters ()
void MakePlanes ()
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double halfCarTolerance
G4double fDx
G4double fDy
G4double fDz
G4double fTalpha
G4double fTthetaCphi
G4double fTthetaSphi
struct {
G4double a
G4double b
G4double c
G4double d
} fPlanes [4]
Additional Inherited Members
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 78 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 78 of file G4Para.hh
Constructor & Destructor Documentation
G4Para::G4Para (const G4String & pName, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Definition at line 53 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 53 of file G4Para.cc
References G4CSGSolid::fRebuildPolyhedron, and SetAllParameters().
Referenced by Clone().
G4Para::G4Para (const G4String & pName, const G4ThreeVector pt[8])
Definition at line 66 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 66 of file G4Para.cc
References kdfinder::abs(), CheckParameters(), FatalException, fDx, fDy, fDz, fTalpha, fTthetaCphi, fTthetaSphi, G4cout, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, MakePlanes(), max, message(), CLHEP::Hep3Vector::set(), v, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
G4Para::~G4Para () virtual
Definition at line 137 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 137 of file G4Para.cc
G4Para::G4Para (__void__ & a)
Definition at line 126 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 126 of file G4Para.cc
References G4CSGSolid::fRebuildPolyhedron, and SetAllParameters().
G4Para::G4Para (const G4Para & rhs)
Definition at line 145 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 145 of file G4Para.cc
References fPlanes.
Member Function Documentation
G4ThreeVector G4Para::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 515 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 515 of file G4Para.cc
References a, kdfinder::abs(), b, c, d, DBL_MAX, fDz, fPlanes, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4Para::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 316 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 316 of file G4Para.cc
References G4VSolid::DumpInfo(), dx, dy, dz, fTthetaCphi, fTthetaSphi, G4Exception(), G4VSolid::GetName(), GetTanAlpha(), GetXHalfLength(), GetYHalfLength(), GetZHalfLength(), JustWarning, max, message(), min, pMax, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), x1, xmax, xmin, CLHEP::Hep3Vector::y(), ymax, ymin, and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Para::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 359 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 359 of file G4Para.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), dx, dy, dz, fTthetaCphi, fTthetaSphi, GetTanAlpha(), GetXHalfLength(), GetYHalfLength(), GetZHalfLength(), pMax, and x1.
void G4Para::CheckParameters () private
Definition at line 209 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 209 of file G4Para.cc
References FatalException, fDx, fDy, fDz, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, and message().
Referenced by G4Para(), and SetAllParameters().
G4VSolid * G4Para::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 803 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 803 of file G4Para.cc
References G4Para().
void G4Para::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 305 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 305 of file G4Para.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Para::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 900 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 900 of file G4Para.cc
References alpha, fDx, fDy, fDz, fTalpha, fTthetaCphi, fTthetaSphi, phi, and theta().
void G4Para::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 895 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 895 of file G4Para.cc
References G4VGraphicsScene::AddSolid().
G4double G4Para::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 539 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 539 of file G4Para.cc
References kdfinder::abs(), DBL_MAX, dz, fDz, fPlanes, halfCarTolerance, kInfinity, tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Para::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 629 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 629 of file G4Para.cc
References kdfinder::abs(), dx, dy, dz, fDz, fPlanes, max, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Para::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 650 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 650 of file G4Para.cc
References a, kdfinder::abs(), b, c, DBL_MAX, fDz, fPlanes, halfCarTolerance, CLHEP::Hep3Vector::set(), tmp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Para::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 759 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 759 of file G4Para.cc
References kdfinder::abs(), G4VSolid::DumpInfo(), dx, dy, dz, fDz, fPlanes, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), Inside(), JustWarning, kOutside, max, message(), mm, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Para::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 269 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 269 of file G4Para.cc
References G4CSGSolid::fCubicVolume, fDx, fDy, and fDz.
G4GeometryType G4Para::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 794 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 794 of file G4Para.cc
G4ThreeVector G4Para::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 842 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 842 of file G4Para.cc
References CLHEP::Hep3Vector::cross(), fDx, fDy, fDz, fTalpha, fTthetaCphi, fTthetaSphi, G4UniformRand, k, pt, CLHEP::Hep3Vector::set(), Acts::UnitConstants::u, and v.
G4double G4Para::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 283 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 283 of file G4Para.cc
References CLHEP::Hep3Vector::cross(), fDx, fDy, fDz, G4CSGSolid::fSurfaceArea, fTalpha, fTthetaCphi, and fTthetaSphi.
G4ThreeVector G4Para::GetSymAxis () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaZ::ComputeTransformation(), export_G4Para(), G4VParameterisationPara::G4VParameterisationPara(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), and G4GDMLWriteSolids::ParaWrite().
G4double G4Para::GetTanAlpha () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaY::ComputeTransformation(), export_G4Para(), G4VParameterisationPara::G4VParameterisationPara(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), and G4GDMLWriteSolids::ParaWrite().
G4double G4Para::GetXHalfLength () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaX::ComputeTransformation(), export_G4Para(), G4ParameterisationParaX::G4ParameterisationParaX(), G4VParameterisationPara::G4VParameterisationPara(), G4ParameterisationParaX::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), and G4GDMLWriteSolids::ParaWrite().
G4double G4Para::GetYHalfLength () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationParaY::ComputeTransformation(), export_G4Para(), G4ParameterisationParaY::G4ParameterisationParaY(), G4VParameterisationPara::G4VParameterisationPara(), G4ParameterisationParaY::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), and G4GDMLWriteSolids::ParaWrite().
G4double G4Para::GetZHalfLength () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeTransformation(), export_G4Para(), G4ParameterisationParaZ::G4ParameterisationParaZ(), G4VParameterisationPara::G4VParameterisationPara(), G4ParameterisationParaZ::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteSolids::ParaWrite(), and G4GDMLWriteSolids::ParaWrite().
EInside G4Para::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 414 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 414 of file G4Para.cc
References kdfinder::abs(), dx, dy, dz, fDz, fPlanes, halfCarTolerance, kInside, kOutside, kSurface, max, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToOut().
void G4Para::MakePlanes () private
Definition at line 230 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 230 of file G4Para.cc
References CLHEP::Hep3Vector::cross(), fDx, fDy, fPlanes, fTalpha, fTthetaCphi, fTthetaSphi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4Para(), and SetAllParameters().
G4Para & G4Para::operator= (const G4Para & rhs)
Definition at line 157 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 157 of file G4Para.cc
References fDx, fDy, fDz, fPlanes, fTalpha, fTthetaCphi, fTthetaSphi, halfCarTolerance, and G4CSGSolid::operator=().
void G4Para::SetAllParameters (G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Definition at line 185 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 185 of file G4Para.cc
References CheckParameters(), G4CSGSolid::fCubicVolume, fDx, fDy, fDz, G4CSGSolid::fRebuildPolyhedron, G4CSGSolid::fSurfaceArea, fTalpha, fTthetaCphi, fTthetaSphi, and MakePlanes().
Referenced by G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), export_G4Para(), and G4Para().
void G4Para::SetAlpha (G4double alpha) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
void G4Para::SetTanAlpha (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
void G4Para::SetThetaAndPhi (double pTheta, double pPhi) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
void G4Para::SetXHalfLength (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
void G4Para::SetYHalfLength (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
void G4Para::SetZHalfLength (G4double val) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Para().
std::ostream & G4Para::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 812 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 812 of file G4Para.cc
References alpha, degree, fDx, fDy, fDz, fTalpha, fTthetaCphi, fTthetaSphi, G4VSolid::GetName(), mm, phi, and theta().
G4ThreeVector G4Para::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 434 of file G4Para.cc.
View newest version in sPHENIX GitHub at line 434 of file G4Para.cc
References kdfinder::abs(), ApproxSurfaceNormal(), d, G4VSolid::DumpInfo(), dz, fDz, fPlanes, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), halfCarTolerance, JustWarning, message(), mm, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Para::a
Definition at line 182 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Para.hh
Referenced by ApproxSurfaceNormal(), and DistanceToOut().
G4double G4Para::b
Definition at line 182 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Para.hh
Referenced by ApproxSurfaceNormal(), and DistanceToOut().
G4double G4Para::c
Definition at line 182 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Para.hh
Referenced by ApproxSurfaceNormal(), and DistanceToOut().
G4double G4Para::d
Definition at line 182 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Para.hh
Referenced by ApproxSurfaceNormal(), and SurfaceNormal().
G4double G4Para::fDx private
Definition at line 180 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 180 of file G4Para.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Para(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Para::fDy private
Definition at line 180 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 180 of file G4Para.hh
Referenced by CheckParameters(), CreatePolyhedron(), G4Para(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Para::fDz private
Definition at line 180 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 180 of file G4Para.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Para(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), SetAllParameters(), StreamInfo(), and SurfaceNormal().
struct { ... } G4Para::fPlanes[4]
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4Para(), Inside(), MakePlanes(), operator=(), and SurfaceNormal().
G4double G4Para::fTalpha private
Definition at line 181 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Para.hh
Referenced by CreatePolyhedron(), G4Para(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Para::fTthetaCphi private
Definition at line 181 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Para.hh
Referenced by BoundingLimits(), CalculateExtent(), CreatePolyhedron(), G4Para(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Para::fTthetaSphi private
Definition at line 181 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Para.hh
Referenced by BoundingLimits(), CalculateExtent(), CreatePolyhedron(), G4Para(), GetPointOnSurface(), GetSurfaceArea(), MakePlanes(), operator=(), SetAllParameters(), and StreamInfo().
G4double G4Para::halfCarTolerance private
Definition at line 179 of file G4Para.hh.
View newest version in sPHENIX GitHub at line 179 of file G4Para.hh
Referenced by DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Para.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4Para.cc