ECCE @ EIC Software: G4Sphere Class Reference
G4Sphere Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Sphere.hh>
Public Member Functions
G4Sphere (const G4String &pName, G4double pRmin, G4double pRmax, G4double pSPhi, G4double pDPhi, G4double pSTheta, G4double pDTheta)
~G4Sphere ()
G4double GetInnerRadius () const
G4double GetOuterRadius () const
G4double GetStartPhiAngle () const
G4double GetDeltaPhiAngle () const
G4double GetStartThetaAngle () const
G4double GetDeltaThetaAngle () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
G4double GetSinStartTheta () const
G4double GetCosStartTheta () const
G4double GetSinEndTheta () const
G4double GetCosEndTheta () const
void SetInnerRadius (G4double newRMin)
void SetOuterRadius (G4double newRmax)
void SetStartPhiAngle (G4double newSphi, G4bool trig=true)
void SetDeltaPhiAngle (G4double newDphi)
void SetStartThetaAngle (G4double newSTheta)
void SetDeltaThetaAngle (G4double newDTheta)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4VisExtent GetExtent () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Sphere (__void__ &)
G4Sphere (const G4Sphere &rhs)
G4Sphere & operator= (const G4Sphere &rhs)
G4double GetRmin () const
G4double GetRmax () const
G4double GetSPhi () const
G4double GetDPhi () const
G4double GetSTheta () const
G4double GetDTheta () const
G4double GetInsideRadius () const
void SetInsideRadius (G4double newRmin)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Types
enum ESide {
kNull, kRMin, kRMax, kSPhi,
kEPhi, kSTheta, kETheta
}
enum ENorm {
kNRMin, kNRMax, kNSPhi, kNEPhi,
kNSTheta, kNETheta
}
Private Member Functions
void Initialize ()
void CheckThetaAngles (G4double sTheta, G4double dTheta)
void CheckSPhiAngle (G4double sPhi)
void CheckDPhiAngle (G4double dPhi)
void CheckPhiAngles (G4double sPhi, G4double dPhi)
void InitializePhiTrigonometry ()
void InitializeThetaTrigonometry ()
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double fRminTolerance
G4double fRmaxTolerance
G4double kAngTolerance
G4double kRadTolerance
G4double fEpsilon = 2.e-11
G4double fRmin
G4double fRmax
G4double fSPhi
G4double fDPhi
G4double fSTheta
G4double fDTheta
G4double sinCPhi
G4double cosCPhi
G4double cosHDPhi
G4double cosHDPhiOT
G4double cosHDPhiIT
G4double sinSPhi
G4double cosSPhi
G4double sinEPhi
G4double cosEPhi
G4double hDPhi
G4double cPhi
G4double ePhi
G4double sinSTheta
G4double cosSTheta
G4double sinETheta
G4double cosETheta
G4double tanSTheta
G4double tanSTheta2
G4double tanETheta
G4double tanETheta2
G4double eTheta
G4bool fFullPhiSphere =false
G4bool fFullThetaSphere =false
G4bool fFullSphere =true
G4double halfCarTolerance
G4double halfAngTolerance
Additional Inherited Members
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 80 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 80 of file G4Sphere.hh
Member Enumeration Documentation
enum G4Sphere::ENorm private
Enumerator:
kNRMin
kNRMax
kNSPhi
kNEPhi
kNSTheta
kNETheta
Definition at line 223 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Sphere.hh
enum G4Sphere::ESide private
Enumerator:
kNull
kRMin
kRMax
kSPhi
kEPhi
kSTheta
kETheta
Definition at line 219 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Sphere.hh
Constructor & Destructor Documentation
G4Sphere::G4Sphere (const G4String & pName, G4double pRmin, G4double pRmax, G4double pSPhi, G4double pDPhi, G4double pSTheta, G4double pDTheta)
Definition at line 72 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 72 of file G4Sphere.cc
References CheckPhiAngles(), CheckThetaAngles(), FatalException, fEpsilon, fRmax, fRmaxTolerance, fRmin, fRminTolerance, G4endl, G4Exception(), G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4VSolid::GetName(), G4GeometryTolerance::GetRadialTolerance(), halfAngTolerance, halfCarTolerance, kAngTolerance, G4VSolid::kCarTolerance, kRadTolerance, max, and message().
Referenced by Clone().
G4Sphere::~G4Sphere ()
Definition at line 126 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 126 of file G4Sphere.cc
G4Sphere::G4Sphere (__void__ & a)
Definition at line 109 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 109 of file G4Sphere.cc
G4Sphere::G4Sphere (const G4Sphere & rhs)
Definition at line 134 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 134 of file G4Sphere.cc
Member Function Documentation
G4ThreeVector G4Sphere::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 531 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 531 of file G4Sphere.cc
References cosEPhi, cosETheta, cosSPhi, cosSTheta, G4VSolid::DumpInfo(), fDPhi, fDTheta, fFullPhiSphere, fFullThetaSphere, fRmax, fRmin, fSPhi, fSTheta, G4Exception(), JustWarning, kNEPhi, kNETheta, kNRMax, kNRMin, kNSPhi, kNSTheta, norm, radius, sinEPhi, sinETheta, sinSPhi, sinSTheta, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4Sphere::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 210 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 210 of file G4Sphere.cc
References G4GeomTools::DiskExtent(), G4VSolid::DumpInfo(), G4Exception(), GetCosEndPhi(), GetCosEndTheta(), GetCosStartPhi(), GetCosStartTheta(), GetDeltaPhiAngle(), GetDeltaThetaAngle(), GetInnerRadius(), G4VSolid::GetName(), GetOuterRadius(), GetSinEndPhi(), GetSinEndTheta(), GetSinStartPhi(), GetSinStartTheta(), GetStartThetaAngle(), halfpi, JustWarning, max, message(), min, pi, pMax, rmax(), CLHEP::Hep3Vector::set(), twopi, CLHEP::Hep2Vector::x(), CLHEP::Hep3Vector::x(), CLHEP::Hep2Vector::y(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Sphere::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 267 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 267 of file G4Sphere.cc
References BoundingLimits(), and G4BoundingEnvelope::CalculateExtent().
void G4Sphere::CheckDPhiAngle (G4double dPhi) inline private
void G4Sphere::CheckPhiAngles (G4double sPhi, G4double dPhi) inline private
Referenced by G4Sphere().
void G4Sphere::CheckSPhiAngle (G4double sPhi) inline private
void G4Sphere::CheckThetaAngles (G4double sTheta, G4double dTheta) inline private
Referenced by G4Sphere().
G4VSolid * G4Sphere::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 2742 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2742 of file G4Sphere.cc
References G4Sphere().
void G4Sphere::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 199 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 199 of file G4Sphere.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Sphere::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 2915 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2915 of file G4Sphere.cc
References fDPhi, fDTheta, fRmax, fRmin, fSPhi, and fSTheta.
void G4Sphere::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 2910 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2910 of file G4Sphere.cc
References G4VGraphicsScene::AddSolid().
G4double G4Sphere::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 704 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 704 of file G4Sphere.cc
References b, c, cosCPhi, cosEPhi, cosHDPhiIT, cosHDPhiOT, cosSPhi, d, d2, eTheta, fFullPhiSphere, fFullThetaSphere, fRmax, fRmaxTolerance, fRmin, fRminTolerance, fSTheta, halfAngTolerance, halfCarTolerance, halfpi, kAngTolerance, G4VSolid::kCarTolerance, kInfinity, pi, sinCPhi, sinEPhi, sinSPhi, t1, t2, tanETheta2, tanSTheta2, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Sphere::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1653 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 1653 of file G4Sphere.cc
References cosCPhi, cosEPhi, cosHDPhi, cosSPhi, eTheta, fFullPhiSphere, fFullThetaSphere, fRmax, fRmin, fSTheta, pi, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Sphere::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 1749 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 1749 of file G4Sphere.cc
References b, c, cosCPhi, cosEPhi, cosSPhi, d, d2, G4VSolid::DumpInfo(), ePhi, eTheta, fDPhi, fFullPhiSphere, fFullThetaSphere, fRmax, fRmaxTolerance, fRmin, fRminTolerance, fSPhi, fSTheta, G4cout, G4endl, G4Exception(), halfAngTolerance, halfCarTolerance, halfpi, JustWarning, kAngTolerance, G4VSolid::kCarTolerance, kEPhi, kETheta, kInfinity, kNull, kRMax, kRMin, kSPhi, kSTheta, message(), mm, pi, sinCPhi, sinEPhi, sinETheta, sinSPhi, t1, t2, tanETheta, tanETheta2, tanSTheta, tanSTheta2, true, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Sphere::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 2640 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2640 of file G4Sphere.cc
References cosCPhi, cosEPhi, cosSPhi, G4VSolid::DumpInfo(), eTheta, fFullPhiSphere, fFullThetaSphere, fRmax, fRmin, fSTheta, G4cout, G4endl, G4Exception(), Inside(), JustWarning, kInfinity, kOutside, min, mm, pi, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Sphere::GetCosEndPhi () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetCosEndTheta () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetCosStartPhi () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetCosStartTheta () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
G4double G4Sphere::GetDeltaPhiAngle () const inline
Referenced by BoundingLimits(), export_G4Sphere(), G4tgbGeometryDumper::GetSolidParams(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteSolids::SphereWrite(), and G4GDMLWriteSolids::SphereWrite().
G4double G4Sphere::GetDeltaThetaAngle () const inline
Referenced by BoundingLimits(), export_G4Sphere(), G4tgbGeometryDumper::GetSolidParams(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteSolids::SphereWrite(), and G4GDMLWriteSolids::SphereWrite().
G4double G4Sphere::GetDPhi () const inline
G4double G4Sphere::GetDTheta () const inline
G4GeometryType G4Sphere::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 2733 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2733 of file G4Sphere.cc
G4VisExtent G4Sphere::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 2904 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2904 of file G4Sphere.cc
References fRmax.
G4double G4Sphere::GetInnerRadius () const inline
Referenced by BoundingLimits(), G4tgbGeometryDumper::GetSolidParams(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteSolids::SphereWrite(), and G4GDMLWriteSolids::SphereWrite().
G4double G4Sphere::GetInsideRadius () const inline
Referenced by export_G4Sphere().
G4double G4Sphere::GetOuterRadius () const inline
Referenced by BoundingLimits(), export_G4Sphere(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteSolids::SphereWrite(), and G4GDMLWriteSolids::SphereWrite().
G4ThreeVector G4Sphere::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 2775 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2775 of file G4Sphere.cc
References cosEPhi, cosETheta, cosSPhi, cosSTheta, ePhi, eTheta, fDPhi, fDTheta, fFullPhiSphere, fRmax, fRmin, fSPhi, fSTheta, G4CSGSolid::GetRadiusInRing(), halfpi, phi, pi, G4INCL::DeJongSpin::shoot(), sinEPhi, sinETheta, sinSPhi, sinSTheta, sqr(), tanETheta, and tanSTheta.
G4double G4Sphere::GetRmax () const inline
G4double G4Sphere::GetRmin () const inline
G4double G4Sphere::GetSinEndPhi () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetSinEndTheta () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetSinStartPhi () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetSinStartTheta () const inline
Referenced by BoundingLimits().
G4double G4Sphere::GetSPhi () const inline
G4double G4Sphere::GetStartPhiAngle () const inline
Referenced by export_G4Sphere(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteSolids::SphereWrite(), and G4GDMLWriteSolids::SphereWrite().
G4double G4Sphere::GetStartThetaAngle () const inline
Referenced by BoundingLimits(), export_G4Sphere(), G4tgbGeometryDumper::GetSolidParams(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteParamvol::Sphere_dimensionsWrite(), PHG4GDMLWriteSolids::SphereWrite(), and G4GDMLWriteSolids::SphereWrite().
G4double G4Sphere::GetSTheta () const inline
G4double G4Sphere::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 2857 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2857 of file G4Sphere.cc
References cosETheta, cosSTheta, eTheta, fDPhi, fDTheta, fFullPhiSphere, fRmax, fRmin, fSTheta, G4CSGSolid::fSurfaceArea, pi, sinETheta, sinSTheta, and twopi.
void G4Sphere::Initialize () inline private
void G4Sphere::InitializePhiTrigonometry () inline private
void G4Sphere::InitializeThetaTrigonometry () inline private
EInside G4Sphere::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 288 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 288 of file G4Sphere.cc
References ePhi, eTheta, fFullPhiSphere, fFullThetaSphere, fRmax, fRmaxTolerance, fRmin, fRminTolerance, fSPhi, fSTheta, halfAngTolerance, in, kInside, kOutside, kSurface, max, pi, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToOut().
G4Sphere & G4Sphere::operator= (const G4Sphere & rhs)
Definition at line 160 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 160 of file G4Sphere.cc
References cosCPhi, cosEPhi, cosETheta, cosHDPhi, cosHDPhiIT, cosHDPhiOT, cosSPhi, cosSTheta, cPhi, ePhi, eTheta, fDPhi, fDTheta, fEpsilon, fFullPhiSphere, fFullSphere, fFullThetaSphere, fRmax, fRmaxTolerance, fRmin, fRminTolerance, fSPhi, fSTheta, halfAngTolerance, halfCarTolerance, hDPhi, kAngTolerance, kRadTolerance, G4CSGSolid::operator=(), sinCPhi, sinEPhi, sinETheta, sinSPhi, sinSTheta, tanETheta, tanETheta2, tanSTheta, and tanSTheta2.
void G4Sphere::SetDeltaPhiAngle (G4double newDphi) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Sphere().
void G4Sphere::SetDeltaThetaAngle (G4double newDTheta) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Sphere().
void G4Sphere::SetInnerRadius (G4double newRMin) inline
Referenced by G4GDMLParameterisation::ComputeDimensions().
void G4Sphere::SetInsideRadius (G4double newRmin) inline
Referenced by export_G4Sphere().
void G4Sphere::SetOuterRadius (G4double newRmax) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Sphere().
void G4Sphere::SetStartPhiAngle (G4double newSphi, G4bool trig = true) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Sphere().
void G4Sphere::SetStartThetaAngle (G4double newSTheta) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Sphere().
std::ostream & G4Sphere::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 2751 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 2751 of file G4Sphere.cc
References degree, fDPhi, fDTheta, fRmax, fRmin, fSPhi, fSTheta, G4VSolid::GetName(), and mm.
G4ThreeVector G4Sphere::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 402 of file G4Sphere.cc.
View newest version in sPHENIX GitHub at line 402 of file G4Sphere.cc
References ApproxSurfaceNormal(), cosEPhi, cosETheta, cosSPhi, cosSTheta, ePhi, eTheta, fFullPhiSphere, fFullSphere, fFullThetaSphere, fRmax, fRmin, fSPhi, fSTheta, G4Exception(), halfAngTolerance, halfCarTolerance, JustWarning, kInfinity, norm, pi, radius, sinEPhi, sinETheta, sinSPhi, sinSTheta, twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Sphere::cosCPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Sphere::cosEPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Sphere::cosETheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and SurfaceNormal().
G4double G4Sphere::cosHDPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Sphere::cosHDPhiIT private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Sphere::cosHDPhiOT private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Sphere::cosSPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Sphere::cosSTheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and SurfaceNormal().
G4double G4Sphere::cPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by operator=().
G4double G4Sphere::ePhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), and SurfaceNormal().
G4double G4Sphere::eTheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), and SurfaceNormal().
G4double G4Sphere::fDPhi private
Definition at line 230 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and StreamInfo().
G4double G4Sphere::fDTheta private
Definition at line 230 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and StreamInfo().
G4double G4Sphere::fEpsilon = 2.e-11 private
Definition at line 226 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 226 of file G4Sphere.hh
Referenced by G4Sphere(), and operator=().
G4bool G4Sphere::fFullPhiSphere =false private
Definition at line 244 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 244 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), and SurfaceNormal().
G4bool G4Sphere::fFullSphere =true private
Definition at line 244 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 244 of file G4Sphere.hh
Referenced by operator=(), and SurfaceNormal().
G4bool G4Sphere::fFullThetaSphere =false private
Definition at line 244 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 244 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Sphere::fRmax private
Definition at line 230 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Sphere(), GetExtent(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Sphere::fRmaxTolerance private
Definition at line 225 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 225 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Sphere(), Inside(), and operator=().
G4double G4Sphere::fRmin private
Definition at line 230 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), G4Sphere(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Sphere::fRminTolerance private
Definition at line 225 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 225 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Sphere(), Inside(), and operator=().
G4double G4Sphere::fSPhi private
Definition at line 230 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Sphere::fSTheta private
Definition at line 230 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Sphere::halfAngTolerance private
Definition at line 248 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 248 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Sphere(), Inside(), operator=(), and SurfaceNormal().
G4double G4Sphere::halfCarTolerance private
Definition at line 248 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 248 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Sphere(), operator=(), and SurfaceNormal().
G4double G4Sphere::hDPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by operator=().
G4double G4Sphere::kAngTolerance private
Definition at line 225 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 225 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Sphere(), and operator=().
G4double G4Sphere::kRadTolerance private
Definition at line 225 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 225 of file G4Sphere.hh
Referenced by G4Sphere(), and operator=().
G4double G4Sphere::sinCPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Sphere::sinEPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Sphere::sinETheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToOut(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and SurfaceNormal().
G4double G4Sphere::sinSPhi private
Definition at line 234 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Sphere::sinSTheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by ApproxSurfaceNormal(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and SurfaceNormal().
G4double G4Sphere::tanETheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by DistanceToOut(), GetPointOnSurface(), and operator=().
G4double G4Sphere::tanETheta2 private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Sphere::tanSTheta private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by DistanceToOut(), GetPointOnSurface(), and operator=().
G4double G4Sphere::tanSTheta2 private
Definition at line 239 of file G4Sphere.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Sphere.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Sphere.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4Sphere.cc