ECCE @ EIC Software: G4XmlRNtupleManager Class Reference
G4XmlRNtupleManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/xml/include/G4XmlRNtupleManager.hh>
Protected Member Functions
G4XmlRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4XmlRNtupleManager ()
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, std::vector< G4int > &vector) final
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, std::vector< G4float > &vector) final
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, std::vector< G4double > &vector) final
Protected Member Functions inherited from G4TRNtupleManager< tools::aida::ntuple >
G4TRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4TRNtupleManager ()
G4bool IsEmpty () const
G4bool Reset ()
tools::aida::ntuple * GetNtuple () const
tools::aida::ntuple * GetNtuple (G4int ntupleId) const
G4int SetNtuple (G4TRNtupleDescription< tools::aida::ntuple > *rntupleDescription)
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, G4int &value) final
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, G4float &value) final
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, G4double &value) final
virtual G4bool SetNtupleSColumn (G4int ntupleId, const G4String &columnName, G4String &value) final
virtual G4bool GetNtupleRow (G4int ntupleId) final
virtual G4int GetNofNtuples () const final
G4TRNtupleDescription
< tools::aida::ntuple > * GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn=true) const
Protected Member Functions inherited from G4BaseRNtupleManager
virtual G4bool SetNtupleIColumn (const G4String &columnName, G4int &value) final
virtual G4bool SetNtupleFColumn (const G4String &columnName, G4float &value) final
virtual G4bool SetNtupleDColumn (const G4String &columnName, G4double &value) final
virtual G4bool SetNtupleSColumn (const G4String &columnName, G4String &value) final
virtual G4bool SetNtupleIColumn (const G4String &columnName, std::vector< G4int > &vector) final
virtual G4bool SetNtupleFColumn (const G4String &columnName, std::vector< G4float > &vector) final
virtual G4bool SetNtupleDColumn (const G4String &columnName, std::vector< G4double > &vector) final
virtual G4bool GetNtupleRow () final
Private Member Functions
virtual G4bool GetTNtupleRow (G4TRNtupleDescription< tools::aida::ntuple > *ntupleDescription) final
Friends
class G4XmlAnalysisReader
Additional Inherited Members
Public Member Functions inherited from G4BaseRNtupleManager
G4BaseRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseRNtupleManager ()
G4BaseRNtupleManager (const G4BaseRNtupleManager &rhs)=delete
G4BaseRNtupleManager & operator= (const G4BaseRNtupleManager &rhs)=delete
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 44 of file G4XmlRNtupleManager.hh.
View newest version in sPHENIX GitHub at line 44 of file G4XmlRNtupleManager.hh
Constructor & Destructor Documentation
G4XmlRNtupleManager::G4XmlRNtupleManager (const G4AnalysisManagerState & state) protected
Definition at line 60 of file G4XmlRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 60 of file G4XmlRNtupleManager.cc
G4XmlRNtupleManager::~G4XmlRNtupleManager () protected virtual
Definition at line 65 of file G4XmlRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 65 of file G4XmlRNtupleManager.cc
Member Function Documentation
G4bool G4XmlRNtupleManager::GetTNtupleRow (G4TRNtupleDescription< tools::aida::ntuple > * ntupleDescription) final private virtual
Implements G4TRNtupleManager< tools::aida::ntuple >.
Definition at line 187 of file G4XmlRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 187 of file G4XmlRNtupleManager.cc
References G4TRNtupleDescription< TNTUPLE >::fDVectorBindingMap, G4TRNtupleDescription< TNTUPLE >::fFVectorBindingMap, G4TRNtupleDescription< TNTUPLE >::fIsInitialized, G4TRNtupleDescription< TNTUPLE >::fIVectorBindingMap, G4TRNtupleDescription< TNTUPLE >::fNtuple, G4TRNtupleDescription< TNTUPLE >::fNtupleBinding, G4Exception(), G4INCL::Random::isInitialized(), it, JustWarning, and ntuple.
G4bool G4XmlRNtupleManager::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, std::vector< G4double > & vector) final protected virtual
Reimplemented from G4TRNtupleManager< tools::aida::ntuple >.
Definition at line 149 of file G4XmlRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 149 of file G4XmlRNtupleManager.cc
References G4BaseAnalysisManager::fState, G4cout, G4TRNtupleManager< tools::aida::ntuple >::GetNtupleDescriptionInFunction(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and ntuple.
G4bool G4XmlRNtupleManager::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, std::vector< G4float > & vector) final protected virtual
Reimplemented from G4TRNtupleManager< tools::aida::ntuple >.
Definition at line 111 of file G4XmlRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 111 of file G4XmlRNtupleManager.cc
References G4BaseAnalysisManager::fState, G4cout, G4TRNtupleManager< tools::aida::ntuple >::GetNtupleDescriptionInFunction(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and ntuple.
G4bool G4XmlRNtupleManager::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, std::vector< G4int > & vector) final protected virtual
Reimplemented from G4TRNtupleManager< tools::aida::ntuple >.
Definition at line 73 of file G4XmlRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 73 of file G4XmlRNtupleManager.cc
References G4BaseAnalysisManager::fState, G4cout, G4TRNtupleManager< tools::aida::ntuple >::GetNtupleDescriptionInFunction(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and ntuple.
Friends And Related Function Documentation
friend class G4XmlAnalysisReader friend
Definition at line 46 of file G4XmlRNtupleManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4XmlRNtupleManager.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/xml/include/G4XmlRNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/xml/src/G4XmlRNtupleManager.cc