ECCE @ EIC Software: G4VXResonance Class Reference
G4VXResonance Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VXResonance.hh>
Public Member Functions
G4VXResonance ()
virtual ~G4VXResonance ()
G4bool operator== (const G4VXResonance &right) const
G4bool operator!= (const G4VXResonance &right) const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual const
G4CrossSectionVector * GetComponents () const =0
virtual G4String Name () const =0
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsValid (G4double e) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Protected Member Functions
G4VXResonance (const G4VXResonance &right)
G4VXResonance & operator= (const G4VXResonance &right)
G4double DegeneracyFactor (const G4KineticTrack &trk1, const G4KineticTrack &trk2, G4double iSpinOut1, G4double iSpinOut2) const
G4double DetailedBalance (const G4KineticTrack &trk1, const G4KineticTrack &trk2, G4int isoOut1, G4int isoOut2, G4double iSpinOut1, G4double iSpinOut2, G4double mOut1, G4double mOut2) const
G4double IsospinCorrection (const G4KineticTrack &trk1, const G4KineticTrack &trk2, G4int isoOut1, G4int isoOut2, G4double iSpinOut1, G4double iSpinOut2) const
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Attributes
G4Clebsch clebsch
Detailed Description
Definition at line 54 of file G4VXResonance.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VXResonance.hh
Constructor & Destructor Documentation
G4VXResonance::G4VXResonance ()
Definition at line 50 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VXResonance.cc
G4VXResonance::~G4VXResonance () virtual
Definition at line 54 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VXResonance.cc
G4VXResonance::G4VXResonance (const G4VXResonance & right) protected
Member Function Documentation
G4double G4VXResonance::DegeneracyFactor (const G4KineticTrack & trk1, const G4KineticTrack & trk2, G4double iSpinOut1, G4double iSpinOut2) const protected
Definition at line 186 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 186 of file G4VXResonance.cc
References denom, G4KineticTrack::GetDefinition(), and G4ParticleDefinition::GetPDGiSpin().
Referenced by DetailedBalance(), and IsospinCorrection().
G4double G4VXResonance::DetailedBalance (const G4KineticTrack & trk1, const G4KineticTrack & trk2, G4int isoOut1, G4int isoOut2, G4double iSpinOut1, G4double iSpinOut2, G4double mOut1, G4double mOut2) const protected
Definition at line 124 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 124 of file G4VXResonance.cc
References clebsch, degeneracy, DegeneracyFactor(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetPDGMass(), G4DetailedBalancePhaseSpaceIntegral::GetPhaseSpaceIntegral(), G4ParticleDefinition::IsShortLived(), S(), weight, and G4Clebsch::Weight().
Referenced by G4XResonance::CrossSection().
G4double G4VXResonance::IsospinCorrection (const G4KineticTrack & trk1, const G4KineticTrack & trk2, G4int isoOut1, G4int isoOut2, G4double iSpinOut1, G4double iSpinOut2) const protected
Definition at line 70 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 70 of file G4VXResonance.cc
References clebsch, DBL_MIN, DegeneracyFactor(), G4lrint(), G4Clebsch::GenerateIso3(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::IsShortLived(), G4Proton::ProtonDefinition(), weight, and G4Clebsch::Weight().
Referenced by G4XResonance::CrossSection().
G4bool G4VXResonance::operator!= (const G4VXResonance & right) const
Definition at line 64 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VXResonance.cc
G4VXResonance& G4VXResonance::operator= (const G4VXResonance & right) protected
G4bool G4VXResonance::operator== (const G4VXResonance & right) const
Definition at line 58 of file G4VXResonance.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VXResonance.cc
Member Data Documentation
G4Clebsch G4VXResonance::clebsch private
Definition at line 90 of file G4VXResonance.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VXResonance.hh
Referenced by DetailedBalance(), and IsospinCorrection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VXResonance.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4VXResonance.cc