ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G01/load_gdml.cc File Reference
load_gdml.cc File Reference
Main program of the persistency/gdml/G01 example.
#include <vector>
#include "G4Types.hh"
#include "G4RunManager.hh"
#include "G4UImanager.hh"
#include "G4LogicalVolumeStore.hh"
#include "G4TransportationManager.hh"
#include "G01PrimaryGeneratorAction.hh"
#include "G01DetectorConstruction.hh"
#include "G01ActionInitialization.hh"
#include "FTFP_BERT.hh"
#include "G4VisExecutive.hh"
#include "G4UIExecutive.hh"
#include "G4GDMLParser.hh"
Functions
void print_aux (const G4GDMLAuxListType *auxInfoList, G4String prepend="|")
int main (int argc, char **argv)
Detailed Description
Main program of the persistency/gdml/G01 example.
Definition in file load_gdml.cc.
Function Documentation
int main (int argc, char ** argv)
Definition at line 81 of file load_gdml.cc.
View newest version in sPHENIX GitHub at line 81 of file load_gdml.cc
References G4UImanager::ApplyCommand(), G4RunManager::BeamOn(), G4cout, G4endl, G4GDMLParser::GetAuxList(), G4LogicalVolumeStore::GetInstance(), G4TransportationManager::GetTransportationManager(), G4UImanager::GetUIpointer(), G4GDMLParser::GetVolumeAuxiliaryInformation(), G4GDMLParser::GetWorldVolume(), G4RunManager::Initialize(), G4VisManager::Initialize(), parser(), print_aux(), G4GDMLParser::Read(), G4UIExecutive::SessionStart(), G4GDMLParser::SetOverlapCheck(), G4GDMLParser::SetRegionExport(), G4RunManager::SetUserInitialization(), and G4GDMLParser::Write().
void print_aux (const G4GDMLAuxListType * auxInfoList, G4String prepend = "|")
Definition at line 63 of file load_gdml.cc.
View newest version in sPHENIX GitHub at line 63 of file load_gdml.cc
References G4cout, and G4endl.
Referenced by main().