ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcCommon.hh File Reference
CexmcCommon.hh File Reference
#include <vector>
#include <limits>
#include <G4String.hh>
#include <G4Types.hh>
Macros
#define CEXMC_LINE_START "--- Cexmc --- "
Typedefs
typedef std::vector< G4double > CexmcEnergyDepositCrystalRowCollection
typedef std::vector
< CexmcEnergyDepositCrystalRowCollection > CexmcEnergyDepositCalorimeterCollection
Enumerations
enum CexmcBasePhysicsUsed { CexmcNoBasePhysics, Cexmc_QGSP_BERT, Cexmc_QGSP_BIC_EMY, Cexmc_FTFP_BERT }
enum CexmcProductionModelType { CexmcUnknownProductionModel, CexmcPionZeroProduction, CexmcEtaProduction }
enum CexmcTriggerType { CexmcTPT, CexmcEDT, CexmcRT }
enum CexmcEventCountPolicy { CexmcCountAllEvents, CexmcCountEventsWithInteraction, CexmcCountEventsWithTrigger }
enum CexmcTrackType {
CexmcInsipidTrack, CexmcBeamParticleTrack, CexmcOutputParticleTrack, CexmcNucleusParticleTrack,
CexmcOutputParticleDecayProductTrack
}
enum CexmcTrackTypeInfo { CexmcBasicTrackType, CexmcIncidentParticleTrackType }
enum CexmcSide { CexmcLeft, CexmcRight }
enum CexmcOuterCrystalsVetoAlgorithm { CexmcNoOuterCrystalsVeto, CexmcMaximumEDInASingleOuterCrystalVeto, CexmcFractionOfEDInOuterCrystalsVeto }
enum CexmcCalorimeterTriggerAlgorithm { CexmcAllCrystalsMakeEDTriggerThreshold, CexmcInnerCrystalsMakeEDTriggerThreshold }
enum CexmcCalorimeterEntryPointDefinitionAlgorithm { CexmcEntryPointInTheCenter, CexmcEntryPointInTheCenterOfCrystalWithMaxED, CexmcEntryPointByLinearEDWeights, CexmcEntryPointBySqrtEDWeights }
enum CexmcCalorimeterEntryPointDepthDefinitionAlgorithm { CexmcEntryPointDepthPlain, CexmcEntryPointDepthSphere }
enum CexmcCrystalSelectionAlgorithm { CexmcSelectAllCrystals, CexmcSelectAdjacentCrystals }
enum CexmcEDCollectionAlgoritm { CexmcCollectEDInAllCrystals, CexmcCollectEDInAdjacentCrystals }
enum CexmcEventDataVerboseLevel { CexmcWriteNoEventData, CexmcWriteEventDataOnEveryEDT, CexmcWriteEventDataOnEveryTPT }
enum CexmcOutputDataType { CexmcOutputRun, CexmcOutputGeometry, CexmcOutputEvents }
Functions
const G4double CexmcDblMax (std::numeric_limits< double >::max())
const G4String CexmcStudiedProcessFullName (CexmcStudiedProcessFirstName+CexmcStudiedProcessLastName)
const G4String CexmcChargeExchangeInteractionName ("Cexmc"+CexmcChargeExchangeProductionModelName)
const G4double CexmcFwhmToStddev (0.42466)
const G4double CexmcInvalidCosTheta (2.0)
const G4int CexmcInvalidTrackId (-1)
Variables
const G4String CexmcStudiedProcessFirstName ("studiedProcess_")
const G4String CexmcStudiedProcessLastName ("Cexmc")
const G4String CexmcChargeExchangeProductionModelName ("ChargeExchange")
const G4String CexmcEDDigitizerName ("EDDig")
const G4String CexmcTPDigitizerName ("TPDig")
const G4String CexmcScenePrimitivesDescription ("CexmcScenePrimitives")
Macro Definition Documentation
#define CEXMC_LINE_START "--- Cexmc --- "
Definition at line 52 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 52 of file CexmcCommon.hh
Referenced by CexmcHadronicProcess::CalculateTargetNucleus(), main(), CexmcProductionModel::PrintInitialData(), CexmcSetup::SetupSpecialVolumes(), and CexmcException::what().
Typedef Documentation
typedef std::vector< CexmcEnergyDepositCrystalRowCollection > CexmcEnergyDepositCalorimeterCollection
Definition at line 58 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 58 of file CexmcCommon.hh
typedef std::vector< G4double > CexmcEnergyDepositCrystalRowCollection
Definition at line 55 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 55 of file CexmcCommon.hh
Enumeration Type Documentation
enum CexmcBasePhysicsUsed
Enumerator:
CexmcNoBasePhysics
Cexmc_QGSP_BERT
Cexmc_QGSP_BIC_EMY
Cexmc_FTFP_BERT
Definition at line 82 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 82 of file CexmcCommon.hh
enum CexmcCalorimeterEntryPointDefinitionAlgorithm
Enumerator:
CexmcEntryPointInTheCenter
CexmcEntryPointInTheCenterOfCrystalWithMaxED
CexmcEntryPointByLinearEDWeights
CexmcEntryPointBySqrtEDWeights
Definition at line 154 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 154 of file CexmcCommon.hh
enum CexmcCalorimeterEntryPointDepthDefinitionAlgorithm
Enumerator:
CexmcEntryPointDepthPlain
CexmcEntryPointDepthSphere
Definition at line 163 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 163 of file CexmcCommon.hh
enum CexmcCalorimeterTriggerAlgorithm
Enumerator:
CexmcAllCrystalsMakeEDTriggerThreshold
CexmcInnerCrystalsMakeEDTriggerThreshold
Definition at line 147 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 147 of file CexmcCommon.hh
enum CexmcCrystalSelectionAlgorithm
Enumerator:
CexmcSelectAllCrystals
CexmcSelectAdjacentCrystals
Definition at line 170 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 170 of file CexmcCommon.hh
enum CexmcEDCollectionAlgoritm
Enumerator:
CexmcCollectEDInAllCrystals
CexmcCollectEDInAdjacentCrystals
Definition at line 177 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 177 of file CexmcCommon.hh
enum CexmcEventCountPolicy
Enumerator:
CexmcCountAllEvents
CexmcCountEventsWithInteraction
CexmcCountEventsWithTrigger
Definition at line 107 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 107 of file CexmcCommon.hh
enum CexmcEventDataVerboseLevel
Enumerator:
CexmcWriteNoEventData
CexmcWriteEventDataOnEveryEDT
CexmcWriteEventDataOnEveryTPT
Definition at line 184 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 184 of file CexmcCommon.hh
enum CexmcOuterCrystalsVetoAlgorithm
Enumerator:
CexmcNoOuterCrystalsVeto
CexmcMaximumEDInASingleOuterCrystalVeto
CexmcFractionOfEDInOuterCrystalsVeto
Definition at line 139 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 139 of file CexmcCommon.hh
enum CexmcOutputDataType
Enumerator:
CexmcOutputRun
CexmcOutputGeometry
CexmcOutputEvents
Definition at line 192 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 192 of file CexmcCommon.hh
enum CexmcProductionModelType
Enumerator:
CexmcUnknownProductionModel
CexmcPionZeroProduction
CexmcEtaProduction
Definition at line 91 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 91 of file CexmcCommon.hh
enum CexmcSide
Enumerator:
CexmcLeft
CexmcRight
Definition at line 132 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 132 of file CexmcCommon.hh
enum CexmcTrackType
Enumerator:
CexmcInsipidTrack
CexmcBeamParticleTrack
CexmcOutputParticleTrack
CexmcNucleusParticleTrack
CexmcOutputParticleDecayProductTrack
Definition at line 115 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 115 of file CexmcCommon.hh
enum CexmcTrackTypeInfo
Enumerator:
CexmcBasicTrackType
CexmcIncidentParticleTrackType
Definition at line 125 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 125 of file CexmcCommon.hh
enum CexmcTriggerType
Enumerator:
CexmcTPT
CexmcEDT
CexmcRT
Definition at line 99 of file CexmcCommon.hh.
View newest version in sPHENIX GitHub at line 99 of file CexmcCommon.hh
Function Documentation
const G4String CexmcChargeExchangeInteractionName ("Cexmc"+ CexmcChargeExchangeProductionModelName)
const G4double CexmcDblMax (std::numeric_limits< double >:: max())
Referenced by CexmcStudiedProcess::PostStepGetPhysicalInteractionLength().
const G4double CexmcFwhmToStddev (0. 42466)
Referenced by CexmcEnergyDepositDigitizer::Digitize(), and CexmcPrimaryGeneratorAction::GeneratePrimaries().
const G4double CexmcInvalidCosTheta (2. 0)
const G4int CexmcInvalidTrackId (- 1)
Referenced by CexmcTrackPointsDigitizer::InitializeData(), CexmcTrackPointInfo::IsValid(), and CexmcTrackingAction::ResetOutputParticleTrackId().
const G4String CexmcStudiedProcessFullName (CexmcStudiedProcessFirstName+ CexmcStudiedProcessLastName)
Referenced by CexmcTrackingAction::PreUserTrackingAction().
Variable Documentation
const G4String CexmcChargeExchangeProductionModelName("ChargeExchange")
const G4String CexmcEDDigitizerName("EDDig")
Referenced by CexmcEventAction::CexmcEventAction(), and CexmcEventAction::EndOfEventAction().
const G4String CexmcScenePrimitivesDescription("CexmcScenePrimitives")
Referenced by CexmcScenePrimitives::CexmcScenePrimitives(), and CexmcRunManager::RegisterScenePrimitives().
const G4String CexmcStudiedProcessFirstName("studiedProcess_")
const G4String CexmcStudiedProcessLastName("Cexmc")
const G4String CexmcTPDigitizerName("TPDig")
Referenced by CexmcEventAction::CexmcEventAction(), and CexmcEventAction::EndOfEventAction().