ECCE @ EIC Software: G4VPVParameterisation Class Reference
G4VPVParameterisation Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VPVParameterisation.hh>
Public Member Functions
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual void ComputeTransformation (const G4int, G4VPhysicalVolume *) const =0
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
Detailed Description
Definition at line 68 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPVParameterisation.hh
Constructor & Destructor Documentation
G4VPVParameterisation::G4VPVParameterisation ()
Definition at line 37 of file G4VPVParameterisation.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VPVParameterisation.cc
G4VPVParameterisation::~G4VPVParameterisation () virtual
Definition at line 41 of file G4VPVParameterisation.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VPVParameterisation.cc
Member Function Documentation
virtual void G4VPVParameterisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, G4ParameterisationBoxY, RE02NestedPhantomParameterisation, G4VNestedParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, DicomNestedPhantomParameterisation, G4ParameterisationPolyconeRho, ChromosomeParameterisation, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, RE05CalorimeterParametrisation, UltraFresnelLensParameterisation, RE04ParallelWorldParam, RE01TrackerParametrisation, RE01CalorimeterParametrisation, G4PhantomParameterisation, G4GDMLParameterisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, G02ChamberParameterisation, ExP01ChamberParameterisation, G4ParameterisationBoxX, ExN02ChamberParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, G4EzVoxelParameterization, CellParameterisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 91 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VPVParameterisation.hh
Referenced by G4Box::ComputeDimensions(), G4Orb::ComputeDimensions(), G4Hype::ComputeDimensions(), G4Ellipsoid::ComputeDimensions(), G4Trd::ComputeDimensions(), G4Polyhedra::ComputeDimensions(), G4Polycone::ComputeDimensions(), G4Tubs::ComputeDimensions(), G4Para::ComputeDimensions(), G4Cons::ComputeDimensions(), G4Sphere::ComputeDimensions(), G4Torus::ComputeDimensions(), G4Trap::ComputeDimensions(), G4tgbGeometryDumper::DumpPVParameterised(), G4GDMLWriteParamvol::ParametersWrite(), and PHG4GDMLWriteParamvol::ParametersWrite().
virtual void G4VPVParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationTubsPhi, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4VNestedParameterisation, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, UltraFresnelLensParameterisation, ChromosomeParameterisation, G4PhantomParameterisation, G4ParameterisationTubsRho, B2bChamberParameterisation, B2bChamberParameterisation, VoxelParam, VoxelParam, VoxelParam, RE01CalorimeterParametrisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, CellParameterisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, PHG4EtaPhiParameterization, and PHG4EtaParameterization.
Definition at line 95 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationParaZ, G4ParameterisationTrdZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationParaY, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationParaX, G4ParameterisationPolyhedraRho, ChromosomeParameterisation, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationTrdX, G4ParameterisationBoxX, UltraFresnelLensParameterisation, G4ParameterisationConsRho, G4PhantomParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, G4ParameterisationTubsRho, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, CellParameterisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 99 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 99 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationTrdZ, G4ParameterisationPolyconeZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationTrdY, G4ParameterisationPolyhedraPhi, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationParaX, G4ParameterisationPolyhedraRho, ChromosomeParameterisation, G4ParameterisationBoxX, G4ParameterisationPolyconeRho, G4ParameterisationTrdX, RE04ParallelWorldParam, G4ParameterisationConsRho, G4PhantomParameterisation, UltraFresnelLensParameterisation, G02ChamberParameterisation, G4ParameterisationTubsRho, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, CellParameterisation, RE01CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 103 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationTubsZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationPolyconePhi, G4ParameterisationTrdY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4VNestedParameterisation, G4ParameterisationPolyhedraRho, DicomNestedPhantomParameterisation, G4ParameterisationPolyconeRho, ChromosomeParameterisation, G4ParameterisationTubsRho, G4ParameterisationTrdX, RE04ParallelWorldParam, G4PhantomParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, G4ParameterisationParaX, ExN02ChamberParameterisation, G4ParameterisationBoxX, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, G4ParameterisationConsRho, UltraFresnelLensParameterisation, CellParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 107 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4ParameterisationBoxY, G4VNestedParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4PhantomParameterisation, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, UltraFresnelLensParameterisation, G4ParameterisationBoxX, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, CellParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 111 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4ParameterisationBoxY, G4VNestedParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationTubsRho, G4PhantomParameterisation, G4ParameterisationBoxX, G02ChamberParameterisation, UltraFresnelLensParameterisation, ExP01ChamberParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE01TrackerParametrisation, CellParameterisation, RE01CalorimeterParametrisation, RE05CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 115 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4ParameterisationBoxY, ChromosomeParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationConsRho, G4PhantomParameterisation, G4ParameterisationParaX, G4ParameterisationTubsRho, G4ParameterisationBoxX, UltraFresnelLensParameterisation, G02ChamberParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, CellParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 119 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationParaY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4ParameterisationBoxY, G4VNestedParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationConsRho, G4PhantomParameterisation, G4ParameterisationParaX, G4ParameterisationTubsRho, G4ParameterisationBoxX, UltraFresnelLensParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, CellParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 123 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 123 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationBoxZ, G4ParameterisationParaZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, G4VNestedParameterisation, RE02NestedPhantomParameterisation, G4ParameterisationBoxY, G4ParameterisationParaY, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationConsRho, G4PhantomParameterisation, G4ParameterisationTubsRho, G4ParameterisationBoxX, B2bChamberParameterisation, B2bChamberParameterisation, UltraFresnelLensParameterisation, CellParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE05CalorimeterParametrisation, G4ParameterisationParaX, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 127 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyconeZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, G4ParameterisationPolyconePhi, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, RE04ParallelWorldParam, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, G4ParameterisationTubsRho, G4PhantomParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, CellParameterisation, G02ChamberParameterisation, UltraFresnelLensParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, G4ParameterisationPolyconeRho, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 131 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 131 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraZ, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, G4VNestedParameterisation, RE02NestedPhantomParameterisation, G4ParameterisationPolyhedraPhi, ChromosomeParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, G4ParameterisationConsRho, G4ParameterisationParaX, G4ParameterisationBoxX, G4ParameterisationTubsRho, G4PhantomParameterisation, CellParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, G02ChamberParameterisation, UltraFresnelLensParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, G4ParameterisationPolyhedraRho, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, VoxelParam, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, and ExN04TrackerParametrisation.
Definition at line 135 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 135 of file G4VPVParameterisation.hh
virtual void G4VPVParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented in G4ParameterisationPolyhedraZ, G4ParameterisationPolyconeZ, G4ParameterisationTrdZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4VNestedParameterisation, G4ParameterisationParaY, G4ParameterisationBoxY, G4ParameterisationConsPhi, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, DicomNestedPhantomParameterisation, ChromosomeParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, RE04ParallelWorldParam, CellParameterisation, G4ParameterisationConsRho, G4ParameterisationParaX, G4PhantomParameterisation, G4ParameterisationBoxX, G4ParameterisationTubsRho, B2bChamberParameterisation, B2bChamberParameterisation, UltraFresnelLensParameterisation, G02ChamberParameterisation, ExP01ChamberParameterisation, ExN02ChamberParameterisation, G4GDMLParameterisation, RE05CalorimeterParametrisation, RE01TrackerParametrisation, RE01CalorimeterParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, RE05TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, VoxelParam, VoxelParam, and VoxelParam.
Definition at line 139 of file G4VPVParameterisation.hh.
View newest version in sPHENIX GitHub at line 139 of file G4VPVParameterisation.hh
G4Material * G4VPVParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = nullptr) virtual
Reimplemented in G4VNestedParameterisation, CellParameterisation, RE04ParallelWorldParam, G4PhantomParameterisation, G4PartialPhantomParameterisation, and DicomPhantomParameterisationColour.
Definition at line 53 of file G4VPVParameterisation.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VPVParameterisation.cc
References G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::GetMaterial().
Referenced by G4tgbGeometryDumper::DumpPVParameterised(), G4LogicalVolume::GetMass(), G4ParameterisedNavigation::LevelLocate(), and G4Region::ScanVolumeTree().
G4VSolid * G4VPVParameterisation::ComputeSolid (const G4int , G4VPhysicalVolume * pPhysicalVol) virtual
Reimplemented in G4VNestedParameterisation, G4ParameterisationTrdX, G4PhantomParameterisation, and G4VDivisionParameterisation.
Definition at line 46 of file G4VPVParameterisation.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VPVParameterisation.cc
References G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::GetSolid().
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4VDivisionParameterisation::ComputeSolid(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4tgbGeometryDumper::DumpPVParameterised(), G4LogicalVolume::GetMass(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
virtual void G4VPVParameterisation::ComputeTransformation (const G4int , G4VPhysicalVolume *) const pure virtual
Implemented in G4ParameterisationPolyhedraZ, G4ParameterisationTrdZ, G4ParameterisationPolyconeZ, G4ParameterisationParaZ, G4ParameterisationBoxZ, G4ParameterisationConsZ, G4ParameterisationTubsZ, G4ParameterisationPolyhedraPhi, G4ParameterisationTrdY, G4ParameterisationPolyconePhi, G4ParameterisationParaY, G4ParameterisationConsPhi, G4ParameterisationBoxY, G4ParameterisationTubsPhi, RE02NestedPhantomParameterisation, G4VNestedParameterisation, DicomNestedPhantomParameterisation, G4ParameterisationPolyhedraRho, G4ParameterisationTrdX, G4ParameterisationPolyconeRho, G4GDMLParameterisation, ChromosomeParameterisation, G4ParameterisationConsRho, G02ChamberParameterisation, G4ParameterisationBoxX, G4ParameterisationParaX, UltraFresnelLensParameterisation, ExP01ChamberParameterisation, RE04ParallelWorldParam, G4ParameterisationTubsRho, ExN02ChamberParameterisation, G4PhantomParameterisation, B2bChamberParameterisation, B2bChamberParameterisation, RE01CalorimeterParametrisation, RE01TrackerParametrisation, RE05CalorimeterParametrisation, RE05TrackerParametrisation, G4VDivisionParameterisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, ExN04CalorimeterParametrisation, ExN04TrackerParametrisation, G4PartialPhantomParameterisation, G4tgbPlaceParamCircle, G4tgbPlaceParameterisation, G4tgbPlaceParamLinear, G4EzVoxelParameterization, G4tgbPlaceParamSquare, CellParameterisation, B5CellParameterisation, VoxelParam, VoxelParam, VoxelParam, PHG4EtaPhiParameterization, PHG4EtaParameterization, and PHG4InttFPHXParameterisation.
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4tgbGeometryDumper::DumpPVParameterised(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
G4VVolumeMaterialScanner * G4VPVParameterisation::GetMaterialScanner () virtual
Reimplemented in G4VNestedParameterisation.
Definition at line 67 of file G4VPVParameterisation.cc.
View newest version in sPHENIX GitHub at line 67 of file G4VPVParameterisation.cc
Referenced by G4Region::ScanVolumeTree().
G4bool G4VPVParameterisation::IsNested () const virtual
Reimplemented in G4VNestedParameterisation.
Definition at line 61 of file G4VPVParameterisation.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VPVParameterisation.cc
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VPVParameterisation.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4VPVParameterisation.cc