ECCE @ EIC Software: G4He3 Class Reference
G4He3 Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4He3.hh>
Static Public Member Functions
static G4He3 * Definition ()
static G4He3 * He3Definition ()
static G4He3 * He3 ()
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4He3 ()
~G4He3 ()
Static Private Attributes
static G4He3 * theInstance = 0
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 50 of file G4He3.hh.
View newest version in sPHENIX GitHub at line 50 of file G4He3.hh
Constructor & Destructor Documentation
G4He3::G4He3 () inline private
Definition at line 54 of file G4He3.hh.
View newest version in sPHENIX GitHub at line 54 of file G4He3.hh
G4He3::~G4He3 () inline private
Definition at line 55 of file G4He3.hh.
View newest version in sPHENIX GitHub at line 55 of file G4He3.hh
Member Function Documentation
G4He3 * G4He3::Definition () static
Definition at line 49 of file G4He3.cc.
View newest version in sPHENIX GitHub at line 49 of file G4He3.cc
References source.hepunit::c_squared, eplus, G4ParticleTable::FindParticle(), G4Ions::G4Ions(), G4ParticleTable::GetParticleTable(), GeV, source.hepunit::hbar_Planck, MeV, source.hepunit::proton_mass_c2, G4ParticleDefinition::SetPDGMagneticMoment(), and theInstance.
Referenced by He3(), He3Definition(), G4InuclElementaryParticle::makeDefinition(), and G4InuclElementaryParticle::type().
G4He3 * G4He3::He3 () static
Definition at line 93 of file G4He3.cc.
View newest version in sPHENIX GitHub at line 93 of file G4He3.cc
References Definition().
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPHe3InelasticFS::ApplyYourself(), G4ParticleHPNHe3InelasticFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4He3Builder::Build(), G4He3PHPBuilder::Build(), G4EmLivermorePhysics::ConstructParticle(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), IonPhysics::ConstructProcess(), G4IonPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4ChargeExchange::G4ChargeExchange(), G4ChargeExchangeProcess::G4ChargeExchangeProcess(), G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface(), G4HadronNucleonXsc::G4HadronNucleonXsc(), G4LENDManager::G4LENDManager(), G4ParticleHPData::G4ParticleHPData(), G4ParticleHPInelastic::G4ParticleHPInelastic(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4WilsonAblationModel::G4WilsonAblationModel(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4ParticleHPT2AInelasticFS::Init(), G4ParticleHPD2AInelasticFS::Init(), G4ParticleHP2NAInelasticFS::Init(), G4ParticleHP2NInelasticFS::Init(), G4ParticleHPPInelasticFS::Init(), G4ParticleHPDAInelasticFS::Init(), G4ParticleHPNPAInelasticFS::Init(), G4ParticleHPNPInelasticFS::Init(), G4ParticleHPNInelasticFS::Init(), G4ParticleHPN2PInelasticFS::Init(), G4ParticleHPND2AInelasticFS::Init(), G4ParticleHP2N2AInelasticFS::Init(), G4ParticleHPTInelasticFS::Init(), G4ParticleHPNT2AInelasticFS::Init(), G4ParticleHPNAInelasticFS::Init(), G4ParticleHP2PInelasticFS::Init(), G4ParticleHPNXInelasticFS::Init(), G4ParticleHPNHe3InelasticFS::Init(), G4ParticleHPPAInelasticFS::Init(), G4ParticleHPHe3InelasticFS::Init(), G4ParticleHPPTInelasticFS::Init(), G4ParticleHPN2AInelasticFS::Init(), G4ParticleHPDInelasticFS::Init(), G4ParticleHP3AInelasticFS::Init(), G4ParticleHPN3AInelasticFS::Init(), G4ParticleHP2NDInelasticFS::Init(), G4ParticleHP2NPInelasticFS::Init(), G4ParticleHPNDInelasticFS::Init(), G4ParticleHPNTInelasticFS::Init(), G4ParticleHPPDInelasticFS::Init(), G4ParticleHP2AInelasticFS::Init(), G4ParticleHP3NAInelasticFS::Init(), G4ParticleHPAInelasticFS::Init(), G4ParticleHP3NPInelasticFS::Init(), G4ParticleHP3NInelasticFS::Init(), G4ParticleHP4NInelasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4AntiNuclElastic::SampleInvariantT(), G4QuasiElRatios::Scatter(), G4WilsonAblationModel::SelectSecondariesByEvaporation(), G4AblaInterface::toG4ParticleDefinition(), G4INCLXXInterface::toG4ParticleDefinition(), and G4INCLXXInterface::toINCLParticleType().
G4He3 * G4He3::He3Definition () static
Definition at line 88 of file G4He3.cc.
View newest version in sPHENIX GitHub at line 88 of file G4He3.cc
References Definition().
Referenced by G4IonConstructor::ConstructLightIons(), GammaKnifeParticles::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), G4ExcitationHandler::G4ExcitationHandler(), and G4BinaryCascade::HighEnergyModelFSProducts().
Member Data Documentation
G4He3 * G4He3::theInstance = 0 static private
Definition at line 53 of file G4He3.hh.
View newest version in sPHENIX GitHub at line 53 of file G4He3.hh
Referenced by Definition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4He3.hh
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/src/G4He3.cc