ECCE @ EIC Software: F01RunAction Class Reference
F01RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01RunAction.hh>
Public Member Functions
F01RunAction ()
virtual ~F01RunAction ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void EndOfRunAction (const G4Run *aRun)
void ChangeLooperParameters (const G4ParticleDefinition *particleDef)
std::pair< G4Transportation
*, G4CoupledTransportation * > findTransportation (const G4ParticleDefinition *particleDef, bool reportError=true)
void SetNumberOfTrials (G4int val)
void SetWarningEnergy (double val)
void SetImportantEnergy (double val)
G4int GetNumberOfTrials ()
G4double GetWarningEnergy ()
G4double GetImportantEnergy ()
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4int theNumberOfTrials = 0
G4double theWarningEnergy = -1.0
G4double theImportantEnergy = -1.0
int theVerboseLevel = 0
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 37 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 37 of file F01RunAction.hh
Constructor & Destructor Documentation
F01RunAction::F01RunAction ()
Definition at line 37 of file F01RunAction.cc.
View newest version in sPHENIX GitHub at line 37 of file F01RunAction.cc
References CLHEP::kiloelectronvolt, theImportantEnergy, theNumberOfTrials, and theWarningEnergy.
F01RunAction::~F01RunAction () virtual
Definition at line 46 of file F01RunAction.cc.
View newest version in sPHENIX GitHub at line 46 of file F01RunAction.cc
Member Function Documentation
void F01RunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 50 of file F01RunAction.cc.
View newest version in sPHENIX GitHub at line 50 of file F01RunAction.cc
References ChangeLooperParameters(), G4Electron::Definition(), G4cout, G4endl, and G4Run::GetRunID().
void F01RunAction::ChangeLooperParameters (const G4ParticleDefinition * particleDef)
Definition at line 60 of file F01RunAction.cc.
View newest version in sPHENIX GitHub at line 60 of file F01RunAction.cc
References G4Electron::Definition(), findTransportation(), theImportantEnergy, theNumberOfTrials, and theWarningEnergy.
Referenced by BeginOfRunAction().
void F01RunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 92 of file F01RunAction.cc.
View newest version in sPHENIX GitHub at line 92 of file F01RunAction.cc
References G4Electron::Definition(), findTransportation(), G4cout, G4endl, and theVerboseLevel.
std::pair< G4Transportation *, G4CoupledTransportation * > F01RunAction::findTransportation (const G4ParticleDefinition * particleDef, bool reportError = true)
Definition at line 110 of file F01RunAction.cc.
View newest version in sPHENIX GitHub at line 110 of file F01RunAction.cc
References G4cerr, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), and G4ParticleDefinition::GetProcessManager().
Referenced by ChangeLooperParameters(), and EndOfRunAction().
G4double F01RunAction::GetImportantEnergy () inline
Definition at line 61 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 61 of file F01RunAction.hh
References theImportantEnergy.
G4int F01RunAction::GetNumberOfTrials () inline
Definition at line 59 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 59 of file F01RunAction.hh
References theNumberOfTrials.
G4double F01RunAction::GetWarningEnergy () inline
Definition at line 60 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file F01RunAction.hh
References theWarningEnergy.
void F01RunAction::SetImportantEnergy (double val) inline
Definition at line 58 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file F01RunAction.hh
References theImportantEnergy.
void F01RunAction::SetNumberOfTrials (G4int val) inline
Definition at line 56 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file F01RunAction.hh
References theNumberOfTrials.
void F01RunAction::SetWarningEnergy (double val) inline
Definition at line 57 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 57 of file F01RunAction.hh
References theWarningEnergy.
Member Data Documentation
G4double F01RunAction::theImportantEnergy = -1.0 private
Definition at line 68 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file F01RunAction.hh
Referenced by ChangeLooperParameters(), F01RunAction(), GetImportantEnergy(), and SetImportantEnergy().
G4int F01RunAction::theNumberOfTrials = 0 private
Definition at line 66 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file F01RunAction.hh
Referenced by ChangeLooperParameters(), F01RunAction(), GetNumberOfTrials(), and SetNumberOfTrials().
int F01RunAction::theVerboseLevel = 0 private
Definition at line 70 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 70 of file F01RunAction.hh
Referenced by EndOfRunAction().
G4double F01RunAction::theWarningEnergy = -1.0 private
Definition at line 67 of file F01RunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file F01RunAction.hh
Referenced by ChangeLooperParameters(), F01RunAction(), GetWarningEnergy(), and SetWarningEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field01/src/F01RunAction.cc