ECCE @ EIC Software: G4fissionEvent Class Reference
G4fissionEvent Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4fissionEvent.hh>
Public Member Functions
G4fissionEvent (G4int isotope, G4double time, G4double nubar, G4double eng)
~G4fissionEvent ()
G4int getNeutronNu ()
G4int getPhotonNu ()
G4double getNeutronEnergy (G4int index)
G4double getNeutronVelocity (G4int index)
G4double getNeutronDircosu (G4int index)
G4double getNeutronDircosv (G4int index)
G4double getNeutronDircosw (G4int index)
G4double getPhotonEnergy (G4int index)
G4double getPhotonVelocity (G4int index)
G4double getPhotonDircosu (G4int index)
G4double getPhotonDircosv (G4int index)
G4double getPhotonDircosw (G4int index)
G4double getNeutronAge (G4int index)
G4double getPhotonAge (G4int index)
Static Public Member Functions
static void setDelayOption (G4int delay)
static void setCorrelationOption (G4int correlation)
static void setNudistOption (G4int nudist)
static void setCf252Option (G4int ndist, G4int neng)
static void setRNGf (float(*funcptr)(void))
static void setRNGd (G4double(*funcptr)(void))
Private Member Functions
G4int G4SmpNuDistDataU232_234_236_238 (G4double nubar)
G4int G4SmpNuDistDataU232_234_236_238_MC (G4double nubar)
G4int G4SmpNuDistDataU233_235 (G4double nubar)
G4int G4SmpNuDistDataU233_235_MC (G4double nubar)
G4int G4SmpNuDistDataU235 (G4double erg, G4int option)
G4int G4SmpNuDistDataPu239 (G4double erg)
G4double G4SmpNVel (G4double eng, G4double *cosdiru, G4double *cosdirv, G4double *cosdirw)
G4double G4SmpNEngCf252 (G4int option)
void G4SmpIsoDir (G4double *cosdiru, G4double *cosdirv, G4double *cosdirw)
G4double G4SmpGEng ()
G4int G4SmpNuDistDataPu239_241 (G4double nubar)
G4int G4SmpNuDistDataPu239_241_MC (G4double nubar)
G4int G4SmpNuDistDataU238 (G4double erg)
G4int G4SmpNugDist (G4int isotope, G4double nubar)
G4double G4SmpPVel (G4double eng, G4double *cosdiru, G4double *cosdirv, G4double *cosdirw)
G4int G4SmpSpNuDistData (G4int isotope, G4int Cf252option)
G4double G4SmpSpNubarData (G4int isotope)
G4int G4SmpSpNugDistData (G4int isotope)
G4double G4SmpTerrell (G4double nubar)
G4double G4SmpWatt (G4double ePart, G4int iso)
void G4fissionerr (G4int iSever, std::string chSubNam, std::string chMsg)
Static Private Member Functions
static G4double fisslibrng (void)
static G4double rngf2d (void)
Private Attributes
G4int neutronNu
G4double * neutronEnergies
G4double * neutronVelocities
G4double * neutronDircosu
G4double * neutronDircosv
G4double * neutronDircosw
G4double * neutronAges
G4int photonNu
G4double * photonEnergies
G4double * photonVelocities
G4double * photonDircosu
G4double * photonDircosv
G4double * photonDircosw
G4double * photonAges
Static Private Attributes
static G4int delayoption =0
static G4int correlationoption =0
static G4int nudistoption =3
static G4int Cf252ndistoption =0
static G4int Cf252nengoption =0
static G4double(* rngdptr)(void)
static float(* rngfptr)(void)
Detailed Description
Definition at line 62 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 62 of file G4fissionEvent.hh
Constructor & Destructor Documentation
G4fissionEvent::G4fissionEvent (G4int isotope, G4double time, G4double nubar, G4double eng)
Definition at line 65 of file G4fissionEvent.cc.
View newest version in sPHENIX GitHub at line 65 of file G4fissionEvent.cc
References Cf252ndistoption, Cf252nengoption, G4SmpGEng(), G4SmpNEngCf252(), G4SmpNuDistDataPu239(), G4SmpNuDistDataPu239_241(), G4SmpNuDistDataPu239_241_MC(), G4SmpNuDistDataU232_234_236_238(), G4SmpNuDistDataU232_234_236_238_MC(), G4SmpNuDistDataU233_235(), G4SmpNuDistDataU233_235_MC(), G4SmpNuDistDataU235(), G4SmpNuDistDataU238(), G4SmpNugDist(), G4SmpNVel(), G4SmpPVel(), G4SmpSpNuDistData(), G4SmpSpNugDistData(), G4SmpTerrell(), G4SmpWatt(), neutronAges, neutronDircosu, neutronDircosv, neutronDircosw, neutronEnergies, neutronNu, neutronVelocities, nudistoption, photonAges, photonDircosu, photonDircosv, photonDircosw, photonEnergies, photonNu, photonVelocities, and Acts::VectorHelpers::time().
G4fissionEvent::~G4fissionEvent ()
Definition at line 181 of file G4fissionEvent.cc.
View newest version in sPHENIX GitHub at line 181 of file G4fissionEvent.cc
References neutronAges, neutronDircosu, neutronDircosv, neutronDircosw, neutronEnergies, neutronNu, neutronVelocities, photonAges, photonDircosu, photonDircosv, photonDircosw, photonEnergies, photonNu, and photonVelocities.
Member Function Documentation
G4double G4fissionEvent::fisslibrng (void) static private
Definition at line 64 of file G4rngc.cc.
View newest version in sPHENIX GitHub at line 64 of file G4rngc.cc
References G4UniformRand.
Referenced by G4SmpGEng(), G4SmpIsoDir(), G4SmpNEngCf252(), G4SmpNuDistDataPu239(), G4SmpNuDistDataPu239_241(), G4SmpNuDistDataPu239_241_MC(), G4SmpNuDistDataU232_234_236_238(), G4SmpNuDistDataU232_234_236_238_MC(), G4SmpNuDistDataU233_235(), G4SmpNuDistDataU233_235_MC(), G4SmpNuDistDataU235(), G4SmpNuDistDataU238(), G4SmpNugDist(), G4SmpSpNuDistData(), G4SmpSpNugDistData(), G4SmpTerrell(), and G4SmpWatt().
void G4fissionEvent::G4fissionerr (G4int iSever, std::string chSubNam, std::string chMsg) private
Definition at line 64 of file G4fissionerr.cc.
View newest version in sPHENIX GitHub at line 64 of file G4fissionerr.cc
References FatalException, G4Exception(), and itoa().
Referenced by G4SmpTerrell(), and G4SmpWatt().
G4double G4fissionEvent::G4SmpGEng () private
Definition at line 63 of file G4SmpGEng.cc.
View newest version in sPHENIX GitHub at line 63 of file G4SmpGEng.cc
References fisslibrng(), G4cout, G4endl, G4Log(), G4Pow::GetInstance(), G4Pow::powA(), and r.
Referenced by G4fissionEvent().
void G4fissionEvent::G4SmpIsoDir (G4double * cosdiru, G4double * cosdirv, G4double * cosdirw) private
Definition at line 62 of file G4SmpIsoDir.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpIsoDir.cc
References fisslibrng(), phi, and twopi.
Referenced by G4SmpNVel(), and G4SmpPVel().
G4double G4fissionEvent::G4SmpNEngCf252 (G4int option) private
Definition at line 63 of file G4SmpNEngCf252.cc.
View newest version in sPHENIX GitHub at line 63 of file G4SmpNEngCf252.cc
References a, b, e, fisslibrng(), G4cout, G4endl, G4Log(), G4Pow::GetInstance(), G4Pow::powA(), G4Pow::powN(), and r.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataPu239 (G4double erg) private
Definition at line 62 of file G4SmpNuDistDataPu239.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpNuDistDataPu239.cc
References fisslibrng(), G4Pow::GetInstance(), G4Pow::powN(), and r.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataPu239_241 (G4double nubar) private
Definition at line 62 of file G4SmpNuDistDataPu239_241.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpNuDistDataPu239_241.cc
References fisslibrng(), G4SmpTerrell(), G4Pow::GetInstance(), G4Pow::powN(), r, and sum.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataPu239_241_MC (G4double nubar) private
Definition at line 61 of file G4SmpNuDistDataPu239_241_MC.cc.
View newest version in sPHENIX GitHub at line 61 of file G4SmpNuDistDataPu239_241_MC.cc
References fisslibrng(), G4SmpTerrell(), and r.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataU232_234_236_238 (G4double nubar) private
Definition at line 62 of file G4SmpNuDistDataU232_234_236_238.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpNuDistDataU232_234_236_238.cc
References fisslibrng(), G4SmpTerrell(), G4Pow::GetInstance(), G4Pow::powN(), r, and sum.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataU232_234_236_238_MC (G4double nubar) private
Definition at line 61 of file G4SmpNuDistDataU232_234_236_238_MC.cc.
View newest version in sPHENIX GitHub at line 61 of file G4SmpNuDistDataU232_234_236_238_MC.cc
References fisslibrng(), G4SmpTerrell(), and r.
Referenced by G4fissionEvent().
int G4fissionEvent::G4SmpNuDistDataU233_235 (G4double nubar) private
Definition at line 63 of file G4SmpNuDistDataU233_235.cc.
View newest version in sPHENIX GitHub at line 63 of file G4SmpNuDistDataU233_235.cc
References fisslibrng(), G4Exp(), G4SmpTerrell(), G4Pow::GetInstance(), G4Pow::powA(), G4Pow::powN(), r, and sum.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataU233_235_MC (G4double nubar) private
Definition at line 61 of file G4SmpNuDistDataU233_235_MC.cc.
View newest version in sPHENIX GitHub at line 61 of file G4SmpNuDistDataU233_235_MC.cc
References fisslibrng(), G4SmpTerrell(), and r.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataU235 (G4double erg, G4int option) private
Definition at line 62 of file G4SmpNuDistDataU235.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpNuDistDataU235.cc
References fisslibrng(), G4cout, G4endl, G4Pow::GetInstance(), G4Pow::powN(), and r.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNuDistDataU238 (G4double erg) private
Definition at line 62 of file G4SmpNuDistDataU238.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpNuDistDataU238.cc
References fisslibrng(), G4Pow::GetInstance(), G4Pow::powN(), and r.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpNugDist (G4int isotope, G4double nubar) private
Definition at line 67 of file G4SmpNugDist.cc.
View newest version in sPHENIX GitHub at line 67 of file G4SmpNugDist.cc
References A(), G4Pow::A13(), alphanegbin, fisslibrng(), G4cout, G4endl, G4Exp(), G4Log(), G4Pow::GetInstance(), nfissg, G4Pow::powA(), r, and Z.
Referenced by G4fissionEvent(), and G4SmpSpNugDistData().
G4double G4fissionEvent::G4SmpNVel (G4double eng, G4double * cosdiru, G4double * cosdirv, G4double * cosdirw) private
Definition at line 61 of file G4SmpNVel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4SmpNVel.cc
References e, G4SmpIsoDir(), and ratio.
Referenced by G4fissionEvent().
G4double G4fissionEvent::G4SmpPVel (G4double eng, G4double * cosdiru, G4double * cosdirv, G4double * cosdirw) private
Definition at line 61 of file G4SmpPVel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4SmpPVel.cc
References G4SmpIsoDir().
Referenced by G4fissionEvent().
G4double G4fissionEvent::G4SmpSpNubarData (G4int isotope) private
Definition at line 62 of file G4SmpSpNubarData.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpSpNubarData.cc
References nSPfissNubarIso.
Referenced by G4SmpSpNuDistData(), and G4SmpSpNugDistData().
G4int G4fissionEvent::G4SmpSpNuDistData (G4int isotope, G4int Cf252option) private
Definition at line 63 of file G4SmpSpNuDistData.cc.
View newest version in sPHENIX GitHub at line 63 of file G4SmpSpNuDistData.cc
References fisslibrng(), G4cout, G4endl, G4SmpSpNubarData(), G4SmpTerrell(), nSPfissIso, nSPfissn, r, and sum.
Referenced by G4fissionEvent().
G4int G4fissionEvent::G4SmpSpNugDistData (G4int isotope) private
Definition at line 62 of file G4SmpSpNugDistData.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmpSpNugDistData.cc
References fisslibrng(), G4SmpNugDist(), G4SmpSpNubarData(), nSPfissg, r, and sum.
Referenced by G4fissionEvent().
G4double G4fissionEvent::G4SmpTerrell (G4double nubar) private
Definition at line 68 of file G4SmpTerrell.cc.
View newest version in sPHENIX GitHub at line 68 of file G4SmpTerrell.cc
References BSHIFT, fisslibrng(), G4cout, G4endl, G4Exp(), G4fissionerr(), G4Log(), SQRT2, temp1, temp2, theta(), TWOPI, WIDTH, and width.
Referenced by G4fissionEvent(), G4SmpNuDistDataPu239_241(), G4SmpNuDistDataPu239_241_MC(), G4SmpNuDistDataU232_234_236_238(), G4SmpNuDistDataU232_234_236_238_MC(), G4SmpNuDistDataU233_235(), G4SmpNuDistDataU233_235_MC(), and G4SmpSpNuDistData().
G4double G4fissionEvent::G4SmpWatt (G4double ePart, G4int iso) private
Definition at line 66 of file G4SmpWatt.cc.
View newest version in sPHENIX GitHub at line 66 of file G4SmpWatt.cc
References a, b, fisslibrng(), G4cout, G4endl, G4fissionerr(), G4Log(), nZAfis, ds::rand1, ds::rand2, WATTEMAX, x, y, and z.
Referenced by G4fissionEvent().
G4double G4fissionEvent::getNeutronAge (G4int index) inline
Definition at line 139 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 139 of file G4fissionEvent.hh
References neutronAges, and neutronNu.
G4double G4fissionEvent::getNeutronDircosu (G4int index) inline
Definition at line 107 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 107 of file G4fissionEvent.hh
References neutronDircosu, and neutronNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4double G4fissionEvent::getNeutronDircosv (G4int index) inline
Definition at line 111 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 111 of file G4fissionEvent.hh
References neutronDircosv, and neutronNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4double G4fissionEvent::getNeutronDircosw (G4int index) inline
Definition at line 115 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 115 of file G4fissionEvent.hh
References neutronDircosw, and neutronNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4double G4fissionEvent::getNeutronEnergy (G4int index) inline
Definition at line 99 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 99 of file G4fissionEvent.hh
References neutronEnergies, and neutronNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4int G4fissionEvent::getNeutronNu () inline
Definition at line 93 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4fissionEvent.hh
References neutronNu.
Referenced by G4SFDecay::DecayIt(), and G4FissionLibrary::SampleMult().
G4double G4fissionEvent::getNeutronVelocity (G4int index) inline
Definition at line 103 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 103 of file G4fissionEvent.hh
References neutronNu, and neutronVelocities.
G4double G4fissionEvent::getPhotonAge (G4int index) inline
Definition at line 143 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 143 of file G4fissionEvent.hh
References photonAges, and photonNu.
G4double G4fissionEvent::getPhotonDircosu (G4int index) inline
Definition at line 127 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 127 of file G4fissionEvent.hh
References photonDircosu, and photonNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4double G4fissionEvent::getPhotonDircosv (G4int index) inline
Definition at line 131 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 131 of file G4fissionEvent.hh
References photonDircosv, and photonNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4double G4fissionEvent::getPhotonDircosw (G4int index) inline
Definition at line 135 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 135 of file G4fissionEvent.hh
References photonDircosw, and photonNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4double G4fissionEvent::getPhotonEnergy (G4int index) inline
Definition at line 119 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 119 of file G4fissionEvent.hh
References photonEnergies, and photonNu.
Referenced by G4FissionLibrary::ApplyYourself(), and G4SFDecay::DecayIt().
G4int G4fissionEvent::getPhotonNu () inline
Definition at line 96 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 96 of file G4fissionEvent.hh
References photonNu.
Referenced by G4SFDecay::DecayIt(), and G4FissionLibrary::SampleMult().
G4double G4fissionEvent::getPhotonVelocity (G4int index) inline
Definition at line 123 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 123 of file G4fissionEvent.hh
References photonNu, and photonVelocities.
G4double G4fissionEvent::rngf2d (void) static private
Definition at line 74 of file G4rngc.cc.
View newest version in sPHENIX GitHub at line 74 of file G4rngc.cc
References rngfptr.
Referenced by setRNGf().
static void G4fissionEvent::setCf252Option (G4int ndist, G4int neng) inline static
Definition at line 156 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 156 of file G4fissionEvent.hh
References Cf252ndistoption, and Cf252nengoption.
static void G4fissionEvent::setCorrelationOption (G4int correlation) inline static
Definition at line 150 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 150 of file G4fissionEvent.hh
References correlationoption.
static void G4fissionEvent::setDelayOption (G4int delay) inline static
Definition at line 147 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 147 of file G4fissionEvent.hh
References delayoption.
static void G4fissionEvent::setNudistOption (G4int nudist) inline static
Definition at line 153 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 153 of file G4fissionEvent.hh
References nudistoption.
static void G4fissionEvent::setRNGd (G4double(*)(void) funcptr) inline static
Definition at line 164 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 164 of file G4fissionEvent.hh
References rngdptr.
Referenced by setrngd_().
static void G4fissionEvent::setRNGf (float(*)(void) funcptr) inline static
Definition at line 160 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 160 of file G4fissionEvent.hh
References rngdptr, rngf2d(), and rngfptr.
Referenced by setrngf_().
Member Data Documentation
G4int G4fissionEvent::Cf252ndistoption =0 static private
Definition at line 84 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 84 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), and setCf252Option().
G4int G4fissionEvent::Cf252nengoption =0 static private
Definition at line 85 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 85 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), and setCf252Option().
G4int G4fissionEvent::correlationoption =0 static private
Definition at line 82 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 82 of file G4fissionEvent.hh
Referenced by setCorrelationOption().
G4int G4fissionEvent::delayoption =0 static private
Definition at line 81 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 81 of file G4fissionEvent.hh
Referenced by setDelayOption().
G4double* G4fissionEvent::neutronAges private
Definition at line 70 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 70 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronAge(), and ~G4fissionEvent().
G4double* G4fissionEvent::neutronDircosu private
Definition at line 67 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 67 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronDircosu(), and ~G4fissionEvent().
G4double* G4fissionEvent::neutronDircosv private
Definition at line 68 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 68 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronDircosv(), and ~G4fissionEvent().
G4double* G4fissionEvent::neutronDircosw private
Definition at line 69 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 69 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronDircosw(), and ~G4fissionEvent().
G4double* G4fissionEvent::neutronEnergies private
Definition at line 65 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 65 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronEnergy(), and ~G4fissionEvent().
G4int G4fissionEvent::neutronNu private
Definition at line 64 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 64 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronAge(), getNeutronDircosu(), getNeutronDircosv(), getNeutronDircosw(), getNeutronEnergy(), getNeutronNu(), getNeutronVelocity(), and ~G4fissionEvent().
G4double* G4fissionEvent::neutronVelocities private
Definition at line 66 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 66 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getNeutronVelocity(), and ~G4fissionEvent().
G4int G4fissionEvent::nudistoption =3 static private
Definition at line 83 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 83 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), and setNudistOption().
G4double* G4fissionEvent::photonAges private
Definition at line 78 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 78 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonAge(), and ~G4fissionEvent().
G4double* G4fissionEvent::photonDircosu private
Definition at line 75 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 75 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonDircosu(), and ~G4fissionEvent().
G4double* G4fissionEvent::photonDircosv private
Definition at line 76 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 76 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonDircosv(), and ~G4fissionEvent().
G4double* G4fissionEvent::photonDircosw private
Definition at line 77 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 77 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonDircosw(), and ~G4fissionEvent().
G4double* G4fissionEvent::photonEnergies private
Definition at line 73 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 73 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonEnergy(), and ~G4fissionEvent().
G4int G4fissionEvent::photonNu private
Definition at line 72 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 72 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonAge(), getPhotonDircosu(), getPhotonDircosv(), getPhotonDircosw(), getPhotonEnergy(), getPhotonNu(), getPhotonVelocity(), and ~G4fissionEvent().
G4double* G4fissionEvent::photonVelocities private
Definition at line 74 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 74 of file G4fissionEvent.hh
Referenced by G4fissionEvent(), getPhotonVelocity(), and ~G4fissionEvent().
G4double(* G4fissionEvent::rngdptr)(void)=0 static private
Definition at line 86 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 86 of file G4fissionEvent.hh
Referenced by setRNGd(), and setRNGf().
G4float(* G4fissionEvent::rngfptr)(void)=0 static private
Definition at line 87 of file G4fissionEvent.hh.
View newest version in sPHENIX GitHub at line 87 of file G4fissionEvent.hh
Referenced by rngf2d(), and setRNGf().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4fissionEvent.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4fissionerr.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4fissionEvent.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4rngc.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpGEng.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpIsoDir.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNEngCf252.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataPu239.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataPu239_241.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataPu239_241_MC.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataU232_234_236_238.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataU232_234_236_238_MC.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataU233_235.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataU233_235_MC.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataU235.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNuDistDataU238.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNugDist.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpNVel.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpPVel.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpSpNubarData.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpSpNuDistData.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpSpNugDistData.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpTerrell.cc
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4SmpWatt.cc