ECCE @ EIC Software: G4RootRFileManager Class Reference
G4RootRFileManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootRFileManager.hh>
Public Member Functions
G4RootRFileManager (const G4AnalysisManagerState &state)
virtual ~G4RootRFileManager ()
virtual G4bool OpenRFile (const G4String &fileName, G4bool isPerThread)
tools::rroot::file * GetRFile (const G4String &fileName, G4bool isPerThread) const
Public Member Functions inherited from G4BaseFileManager
G4BaseFileManager (const G4AnalysisManagerState &state)
virtual ~G4BaseFileManager ()
virtual G4bool SetFileName (const G4String &fileName)
G4String GetFileName () const
G4String GetFullFileName (const G4String &baseFileName="", G4bool isPerThread=true) const
G4String GetHnFileName (const G4String &hnType, const G4String &hnName) const
G4String GetNtupleFileName (const G4String &ntupleName) const
G4String GetNtupleFileName (G4int ntupleFileNumber) const
G4String GetPlotFileName () const
G4String GetFileType () const
Private Attributes
std::map< G4String,
tools::rroot::file * > fRFiles
Additional Inherited Members
Protected Member Functions inherited from G4BaseFileManager
G4String TakeOffExtension (G4String &name) const
Protected Attributes inherited from G4BaseFileManager
const G4AnalysisManagerState & fState
G4String fFileName
Detailed Description
Definition at line 46 of file G4RootRFileManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4RootRFileManager.hh
Constructor & Destructor Documentation
G4RootRFileManager::G4RootRFileManager (const G4AnalysisManagerState & state) explicit
Definition at line 39 of file G4RootRFileManager.cc.
View newest version in sPHENIX GitHub at line 39 of file G4RootRFileManager.cc
G4RootRFileManager::~G4RootRFileManager () virtual
Definition at line 46 of file G4RootRFileManager.cc.
View newest version in sPHENIX GitHub at line 46 of file G4RootRFileManager.cc
References fRFiles.
Member Function Documentation
tools::rroot::file * G4RootRFileManager::GetRFile (const G4String & fileName, G4bool isPerThread) const
Definition at line 103 of file G4RootRFileManager.cc.
View newest version in sPHENIX GitHub at line 103 of file G4RootRFileManager.cc
References fRFiles, G4BaseFileManager::GetFullFileName(), and it.
Referenced by G4RootAnalysisReader::GetBuffer(), and G4RootAnalysisReader::ReadNtupleImpl().
G4bool G4RootRFileManager::OpenRFile (const G4String & fileName, G4bool isPerThread) virtual
Definition at line 58 of file G4RootRFileManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RootRFileManager.cc
References file, fRFiles, G4BaseFileManager::fState, G4cout, G4Exception(), G4BaseFileManager::GetFullFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), it, JustWarning, and G4AnalysisVerbose::Message().
Referenced by G4RootAnalysisReader::GetBuffer(), and G4RootAnalysisReader::ReadNtupleImpl().
Member Data Documentation
std::map<G4String, tools::rroot::file*> G4RootRFileManager::fRFiles private
Definition at line 62 of file G4RootRFileManager.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RootRFileManager.hh
Referenced by GetRFile(), OpenRFile(), and ~G4RootRFileManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootRFileManager.hh
geant4/tree/geant4-10.6-release/source/analysis/root/src/G4RootRFileManager.cc