ECCE @ EIC Software: G4DNAPARSER::CommandLineParser Class Reference
G4DNAPARSER::CommandLineParser Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/CommandLineParser.hh>
Public Member Functions
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
CommandLineParser ()
~CommandLineParser ()
int Parse (int &argc, char **argv)
void PrintHelp ()
bool CheckIfNotHandledOptionsExists (int &argc, char **argv)
void CorrectRemainingOptions (int &argc, char **argv)
void AddCommand (const G4String &marker, Command::Type, const G4String &description="", const G4String &defaultOption="", const G4String &optionName="")
Command * FindCommand (const G4String &marker)
Command * GetCommandIfActive (const G4String &marker)
G4bool WereOptionsSetup ()
Static Public Member Functions
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
static CommandLineParser * GetParser ()
static void DeleteInstance ()
Private Attributes
std::map< G4String, Command * > fCommandMap
G4bool fOptionsWereSetup
G4int fMaxMarkerLength
G4int fMaxOptionNameLength
G4int fVerbose
Static Private Attributes
static CommandLineParser * fpInstance
Detailed Description
Definition at line 105 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 105 of file CommandLineParser.hh
Constructor & Destructor Documentation
CommandLineParser::CommandLineParser ()
Definition at line 58 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.cc
CommandLineParser::~CommandLineParser ()
Definition at line 82 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 82 of file CommandLineParser.cc
References it.
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
G4DNAPARSER::CommandLineParser::CommandLineParser ()
G4DNAPARSER::CommandLineParser::~CommandLineParser ()
Member Function Documentation
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void CommandLineParser::AddCommand (const G4String & marker, Command::Type type, const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
Definition at line 273 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 273 of file CommandLineParser.cc
References fCommandMap, fMaxMarkerLength, fMaxOptionNameLength, and G4DNAPARSER::Command::WithoutOption.
Referenced by Parse().
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
void G4DNAPARSER::CommandLineParser::AddCommand (const G4String & marker, Command::Type , const G4String & description = "", const G4String & defaultOption = "", const G4String & optionName = "")
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
Definition at line 374 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 374 of file CommandLineParser.cc
References G4cerr, G4cout, G4endl, and PrintHelp().
Referenced by Parse().
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
bool G4DNAPARSER::CommandLineParser::CheckIfNotHandledOptionsExists (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
void CommandLineParser::CorrectRemainingOptions (int & argc, char ** argv)
Definition at line 256 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 256 of file CommandLineParser.cc
Referenced by Parse().
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
void CommandLineParser::DeleteInstance () static
Definition at line 93 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 93 of file CommandLineParser.cc
Referenced by main(), and Parse().
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
static void G4DNAPARSER::CommandLineParser::DeleteInstance () static
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command * CommandLineParser::FindCommand (const G4String & marker)
Definition at line 331 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 331 of file CommandLineParser.cc
References fCommandMap, and it.
Referenced by GetCommandIfActive(), and Parse().
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::FindCommand (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command * CommandLineParser::GetCommandIfActive (const G4String & marker)
Definition at line 344 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 344 of file CommandLineParser.cc
References G4DNAPARSER::Command::fActive, FatalException, FindCommand(), G4endl, and G4Exception().
Referenced by RunAction::CreateNtuple(), main(), Parse(), and SetSeed().
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
Command* G4DNAPARSER::CommandLineParser::GetCommandIfActive (const G4String & marker)
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
CommandLineParser * CommandLineParser::GetParser () static
Definition at line 74 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 74 of file CommandLineParser.cc
Referenced by Parse().
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
static CommandLineParser* G4DNAPARSER::CommandLineParser::GetParser () static
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int CommandLineParser::Parse (int & argc, char ** argv)
Definition at line 126 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 126 of file CommandLineParser.cc
References CorrectRemainingOptions(), G4DNAPARSER::Command::fActive, FindCommand(), fOptionsWereSetup, G4DNAPARSER::Command::fType, fVerbose, G4cerr, G4cout, G4endl, GetCommandIfActive(), G4DNAPARSER::Command::OptionNotCompulsory, PrintHelp(), G4DNAPARSER::Command::SetOption(), and G4DNAPARSER::Command::WithOption.
Referenced by Parse().
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
int G4DNAPARSER::CommandLineParser::Parse (int & argc, char ** argv)
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void CommandLineParser::PrintHelp ()
Definition at line 215 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 215 of file CommandLineParser.cc
References fCommandMap, fMaxMarkerLength, fMaxOptionNameLength, G4cout, G4endl, G4DNAPARSER::Command::GetDefaultOption(), G4DNAPARSER::Command::GetDescription(), it, and left.
Referenced by CheckIfNotHandledOptionsExists(), and Parse().
void G4DNAPARSER::CommandLineParser::PrintHelp ()
void G4DNAPARSER::CommandLineParser::PrintHelp ()
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 122 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 122 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
G4bool G4DNAPARSER::CommandLineParser::WereOptionsSetup () inline
Definition at line 129 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 129 of file CommandLineParser.hh
References fOptionsWereSetup.
Member Data Documentation
std::map< G4String, Command * > G4DNAPARSER::CommandLineParser::fCommandMap private
Definition at line 108 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 108 of file CommandLineParser.hh
Referenced by AddCommand(), FindCommand(), and PrintHelp().
G4int G4DNAPARSER::CommandLineParser::fMaxMarkerLength private
Definition at line 110 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 110 of file CommandLineParser.hh
Referenced by AddCommand(), and PrintHelp().
G4int G4DNAPARSER::CommandLineParser::fMaxOptionNameLength private
Definition at line 111 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 111 of file CommandLineParser.hh
Referenced by AddCommand(), and PrintHelp().
G4bool G4DNAPARSER::CommandLineParser::fOptionsWereSetup private
Definition at line 109 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 109 of file CommandLineParser.hh
Referenced by Parse(), and WereOptionsSetup().
CommandLineParser * CommandLineParser::fpInstance static private
Definition at line 107 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 107 of file CommandLineParser.hh
G4int G4DNAPARSER::CommandLineParser::fVerbose private
Definition at line 112 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 112 of file CommandLineParser.hh
Referenced by Parse().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/src/CommandLineParser.cc