ECCE @ EIC Software: G4SingleScatter Class Reference
G4SingleScatter Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh>
Public Member Functions
G4SingleScatter ()
virtual void DoCollisionStep (class G4ScreenedNuclearRecoil *master, const class G4Track &aTrack, const class G4Step &aStep)
virtual ~G4SingleScatter ()
Public Member Functions inherited from G4ScreenedCoulombCrossSectionInfo
G4ScreenedCoulombCrossSectionInfo ()
~G4ScreenedCoulombCrossSectionInfo ()
Public Member Functions inherited from G4ScreenedCollisionStage
virtual ~G4ScreenedCollisionStage ()
Additional Inherited Members
Static Public Member Functions inherited from G4ScreenedCoulombCrossSectionInfo
static const char * CVSHeaderVers ()
static const char * CVSFileVers ()
Detailed Description
Definition at line 192 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ScreenedNuclearRecoil.hh
Constructor & Destructor Documentation
G4SingleScatter::G4SingleScatter () inline
Definition at line 196 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ScreenedNuclearRecoil.hh
virtual G4SingleScatter::~G4SingleScatter () inline virtual
Definition at line 199 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 199 of file G4ScreenedNuclearRecoil.hh
Member Function Documentation
void G4SingleScatter::DoCollisionStep (class G4ScreenedNuclearRecoil * master, const class G4Track & aTrack, const class G4Step & aStep) virtual
Implements G4ScreenedCollisionStage.
Definition at line 751 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 751 of file G4ScreenedNuclearRecoil.cc
References G4CoulombKinematicsInfo::a2, G4ParticleChange::AddSecondary(), source.hepunit::amu_c2, G4CoulombKinematicsInfo::cosZeta, G4CoulombKinematicsInfo::eRecoil, G4UniformRand, G4Track::GetDynamicParticle(), G4ParticleChange::GetEnergy(), G4ScreenedNuclearRecoil::GetKinematics(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4ScreenedNuclearRecoil::GetParticleChange(), G4ScreenedNuclearRecoil::GetValidCollision(), pi, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4CoulombKinematicsInfo::recoilIon, CLHEP::Hep3Vector::rotateUz(), G4VParticleChange::SetNumberOfSecondaries(), G4CoulombKinematicsInfo::sinZeta, and CLHEP::Hep3Vector::unit().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/G4ScreenedNuclearRecoil.cc