ECCE @ EIC Software: G4GoudsmitSaundersonMscModel Class Reference
G4GoudsmitSaundersonMscModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4GoudsmitSaundersonMscModel.hh>
Public Member Functions
G4GoudsmitSaundersonMscModel (const G4String &nam="GoudsmitSaunderson")
virtual ~G4GoudsmitSaundersonMscModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseLocal (const G4ParticleDefinition *p, G4VEmModel *masterModel)
virtual G4ThreeVector & SampleScattering (const G4ThreeVector &, G4double safety)
virtual G4double ComputeTruePathLengthLimit (const G4Track &track, G4double &currentMinimalStep)
virtual G4double ComputeGeomPathLength (G4double truePathLength)
virtual G4double ComputeTrueStepLength (G4double geomStepLength)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
void StartTracking (G4Track *)
void SampleMSC ()
G4double GetTransportMeanFreePath (const G4ParticleDefinition *, G4double)
void SetOptionPWACorrection (G4bool opt)
G4bool GetOptionPWACorrection () const
void SetOptionMottCorrection (G4bool opt)
G4bool GetOptionMottCorrection () const
G4GoudsmitSaundersonTable * GetGSTable ()
G4GSPWACorrections * GetPWACorrection ()
Public Member Functions inherited from G4VMscModel
G4VMscModel (const G4String &nam)
~G4VMscModel () override
void InitialiseParameters (const G4ParticleDefinition *)
void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double tmax) override
void SetStepLimitType (G4MscStepLimitType)
void SetLateralDisplasmentFlag (G4bool val)
void SetRangeFactor (G4double)
void SetGeomFactor (G4double)
void SetSkin (G4double)
void SetLambdaLimit (G4double)
void SetSafetyFactor (G4double)
void SetSampleZ (G4bool)
G4VEnergyLossProcess * GetIonisation () const
void SetIonisation (G4VEnergyLossProcess *, const G4ParticleDefinition *part)
G4double ComputeSafety (const G4ThreeVector &position, G4double limit=DBL_MAX)
G4double ComputeGeomLimit (const G4Track &, G4double &presafety, G4double limit)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double GetEnergy (const G4ParticleDefinition *part, G4double range, const G4MaterialCutsCouple *couple)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy, G4double logKinEnergy)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void SetParticle (const G4ParticleDefinition *p)
G4double GetLambda (G4double)
G4GoudsmitSaundersonMscModel & operator= (const G4GoudsmitSaundersonMscModel &right)
G4GoudsmitSaundersonMscModel (const G4GoudsmitSaundersonMscModel &)
G4double GetTransportMeanFreePathOnly (const G4ParticleDefinition *, G4double)
G4double Randomizetlimit ()
Private Attributes
CLHEP::HepRandomEngine * rndmEngineMod
G4double currentKinEnergy
G4double currentRange
G4double fr
G4double rangeinit
G4double geombig
G4double geomlimit
G4double tlimit
G4double tgeom
G4double par1
G4double par2
G4double par3
G4double tlimitminfix2
G4double tausmall
G4double mass
G4double taulim
G4double presafety
G4double fZeff
G4int charge
G4int currentMaterialIndex
G4bool firstStep
G4LossTableManager * theManager
const G4ParticleDefinition * particle
G4ParticleChangeForMSC * fParticleChange
const G4MaterialCutsCouple * currentCouple
G4GoudsmitSaundersonTable * fGSTable
G4GSPWACorrections * fPWACorrection
G4bool fIsUsePWACorrection
G4bool fIsUseMottCorrection
G4double fLambda0
G4double fLambda1
G4double fScrA
G4double fG1
G4double fMCtoScrA
G4double fMCtoQ1
G4double fMCtoG2PerG1
G4double fTheTrueStepLenght
G4double fTheTransportDistance
G4double fTheZPathLenght
G4ThreeVector fTheDisplacementVector
G4ThreeVector fTheNewDirection
G4bool fIsEndedUpOnBoundary
G4bool fIsMultipleSacettring
G4bool fIsSingleScattering
G4bool fIsEverythingWasDone
G4bool fIsNoScatteringInMSC
G4bool fIsNoDisplace
G4bool fIsInsideSkin
G4bool fIsWasOnBoundary
G4bool fIsFirstRealStep
Static Private Attributes
static G4bool gIsUseAccurate = true
static G4bool gIsOptimizationOn = true
Additional Inherited Members
Protected Member Functions inherited from G4VMscModel
G4ParticleChangeForMSC * GetParticleChangeForMSC (const G4ParticleDefinition *p=nullptr)
G4double ConvertTrueToGeom (G4double &tLength, G4double &gLength)
Protected Attributes inherited from G4VMscModel
G4double facrange
G4double facgeom
G4double facsafety
G4double skin
G4double dtrl
G4double lambdalimit
G4double geomMin
G4double geomMax
G4ThreeVector fDisplacement
G4MscStepLimitType steppingAlgorithm
G4bool samplez
G4bool latDisplasment
Detailed Description
Definition at line 138 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4GoudsmitSaundersonMscModel.hh
Constructor & Destructor Documentation
G4GoudsmitSaundersonMscModel::G4GoudsmitSaundersonMscModel (const G4String & nam = "GoudsmitSaunderson")
Definition at line 163 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 163 of file G4GoudsmitSaundersonMscModel.cc
References charge, currentCouple, currentKinEnergy, currentMaterialIndex, currentRange, source.hepunit::electron_mass_c2, fG1, fGSTable, firstStep, fIsEndedUpOnBoundary, fIsEverythingWasDone, fIsFirstRealStep, fIsInsideSkin, fIsMultipleSacettring, fIsNoDisplace, fIsNoScatteringInMSC, fIsSingleScattering, fIsUseMottCorrection, fIsUsePWACorrection, fIsWasOnBoundary, fLambda0, fLambda1, fMCtoG2PerG1, fMCtoQ1, fMCtoScrA, fParticleChange, fPWACorrection, fr, fScrA, fTheDisplacementVector, fTheNewDirection, fTheTransportDistance, fTheTrueStepLenght, fTheZPathLenght, fZeff, geombig, geomlimit, G4LossTableManager::Instance(), mass, mm, nm, par1, par2, par3, particle, presafety, rangeinit, rndmEngineMod, CLHEP::Hep3Vector::set(), taulim, tausmall, tgeom, theManager, tlimit, and tlimitminfix2.
G4GoudsmitSaundersonMscModel::~G4GoudsmitSaundersonMscModel () virtual
Definition at line 237 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 237 of file G4GoudsmitSaundersonMscModel.cc
References fGSTable, fPWACorrection, and G4VEmModel::IsMaster().
G4GoudsmitSaundersonMscModel::G4GoudsmitSaundersonMscModel (const G4GoudsmitSaundersonMscModel &) private
Member Function Documentation
G4double G4GoudsmitSaundersonMscModel::ComputeGeomPathLength (G4double truePathLength) virtual
Implements G4VMscModel.
Definition at line 781 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 781 of file G4GoudsmitSaundersonMscModel.cc
References currentCouple, currentKinEnergy, currentRange, G4VMscModel::dtrl, fIsEverythingWasDone, fLambda1, fTheTrueStepLenght, fTheZPathLenght, G4Exp(), G4VMscModel::GetEnergy(), G4Pow::GetInstance(), GetTransportMeanFreePathOnly(), mass, max, min, par1, par2, par3, particle, G4Pow::powA(), T1, taulim, tausmall, and tlimitminfix2.
G4double G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit (const G4Track & track, G4double & currentMinimalStep) virtual
Implements G4VMscModel.
Definition at line 469 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 469 of file G4GoudsmitSaundersonMscModel.cc
References G4VMscModel::ComputeGeomLimit(), G4VMscModel::ComputeSafety(), G4VMscModel::ConvertTrueToGeom(), currentCouple, currentKinEnergy, currentMaterialIndex, currentRange, e, CLHEP::electron_mass_c2, G4VMscModel::facgeom, G4VMscModel::facrange, G4VMscModel::facsafety, fGeomBoundary, fGSTable, firstStep, fIsEverythingWasDone, fIsFirstRealStep, fIsInsideSkin, fIsMultipleSacettring, fIsNoDisplace, fIsNoScatteringInMSC, fIsSingleScattering, fIsWasOnBoundary, fLambda0, fLambda1, fr, fScrA, fTheDisplacementVector, fTheNewDirection, fTheTransportDistance, fTheTrueStepLenght, fTheZPathLenght, fUndefined, fUseDistanceToBoundary, fUseSafetyPlus, fZeff, G4Log(), G4UniformRand, geombig, geomlimit, G4Track::GetDynamicParticle(), G4Material::GetIndex(), G4Material::GetIonisation(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4VMscModel::GetRange(), G4StepPoint::GetSafety(), G4Track::GetStep(), G4StepPoint::GetStepStatus(), GetTransportMeanFreePath(), G4IonisParamMat::GetZeffective(), gIsOptimizationOn, max, min, particle, phi, presafety, pt2, Randomizetlimit(), rangeinit, SampleMSC(), CLHEP::Hep3Vector::set(), G4VEmModel::SetCurrentCouple(), G4GoudsmitSaundersonTable::SingleScattering(), G4VMscModel::skin, G4InuclParticleNames::sp, G4VMscModel::steppingAlgorithm, tgeom, tlimit, and CLHEP::twopi.
G4double G4GoudsmitSaundersonMscModel::ComputeTrueStepLength (G4double geomStepLength) virtual
Implements G4VMscModel.
Definition at line 833 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 833 of file G4GoudsmitSaundersonMscModel.cc
References currentRange, fIsEndedUpOnBoundary, fIsEverythingWasDone, fIsMultipleSacettring, fLambda1, fTheTrueStepLenght, fTheZPathLenght, G4Log(), G4Pow::GetInstance(), par1, par3, G4Pow::powA(), tausmall, and tlimitminfix2.
G4double G4GoudsmitSaundersonMscModel::CrossSectionPerVolume (const G4Material * mat, const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 309 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 309 of file G4GoudsmitSaundersonMscModel.cc
References source.hepunit::electron_mass_c2, CLHEP::eV, fG1, fGSTable, fIsUseMottCorrection, fIsUsePWACorrection, fLambda0, fLambda1, fMCtoG2PerG1, fMCtoQ1, fMCtoScrA, fPWACorrection, fScrA, G4Log(), G4Material::GetIndex(), G4GoudsmitSaundersonTable::GetMoliereBc(), G4GoudsmitSaundersonTable::GetMoliereXc2(), G4GoudsmitSaundersonTable::GetMottCorrectionFactors(), G4GSPWACorrections::GetPWACorrectionFactors(), max, and pt2.
G4GoudsmitSaundersonTable* G4GoudsmitSaundersonMscModel::GetGSTable () inline
Definition at line 178 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 178 of file G4GoudsmitSaundersonMscModel.hh
References fGSTable.
Referenced by InitialiseLocal().
G4double G4GoudsmitSaundersonMscModel::GetLambda (G4double) inline private
G4bool G4GoudsmitSaundersonMscModel::GetOptionMottCorrection () const inline
Definition at line 176 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4GoudsmitSaundersonMscModel.hh
References fIsUseMottCorrection.
Referenced by InitialiseLocal().
G4bool G4GoudsmitSaundersonMscModel::GetOptionPWACorrection () const inline
Definition at line 172 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4GoudsmitSaundersonMscModel.hh
References fIsUsePWACorrection.
Referenced by InitialiseLocal().
G4GSPWACorrections* G4GoudsmitSaundersonMscModel::GetPWACorrection () inline
Definition at line 180 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4GoudsmitSaundersonMscModel.hh
References fPWACorrection.
Referenced by InitialiseLocal().
G4double G4GoudsmitSaundersonMscModel::GetTransportMeanFreePath (const G4ParticleDefinition * , G4double kineticEnergy)
Definition at line 365 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 365 of file G4GoudsmitSaundersonMscModel.cc
References G4GoudsmitSaundersonTable::ComputeScatteringPowerCorrection(), currentCouple, source.hepunit::electron_mass_c2, CLHEP::eV, fG1, fGSTable, fIsUseMottCorrection, fIsUsePWACorrection, fLambda0, fLambda1, fMCtoG2PerG1, fMCtoQ1, fMCtoScrA, fPWACorrection, fScrA, G4Log(), G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4GoudsmitSaundersonTable::GetMoliereBc(), G4GoudsmitSaundersonTable::GetMoliereXc2(), G4GoudsmitSaundersonTable::GetMottCorrectionFactors(), G4GSPWACorrections::GetPWACorrectionFactors(), mat, and pt2.
Referenced by ComputeTruePathLengthLimit(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::GetTransportMeanFreePathOnly (const G4ParticleDefinition * , G4double kineticEnergy) private
Definition at line 420 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 420 of file G4GoudsmitSaundersonMscModel.cc
References G4GoudsmitSaundersonTable::ComputeScatteringPowerCorrection(), currentCouple, source.hepunit::electron_mass_c2, CLHEP::eV, fGSTable, fIsUseMottCorrection, fIsUsePWACorrection, fPWACorrection, G4Log(), G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4GoudsmitSaundersonTable::GetMoliereBc(), G4GoudsmitSaundersonTable::GetMoliereXc2(), G4GoudsmitSaundersonTable::GetMottCorrectionFactors(), G4GSPWACorrections::GetPWACorrectionFactors(), mat, and pt2.
Referenced by ComputeGeomPathLength().
void G4GoudsmitSaundersonMscModel::Initialise (const G4ParticleDefinition * p, const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 251 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 251 of file G4GoudsmitSaundersonMscModel.cc
References fGSTable, fIsUseMottCorrection, fIsUsePWACorrection, fParticleChange, fPWACorrection, G4VMscModel::GetParticleChangeForMSC(), G4ParticleDefinition::GetPDGCharge(), G4VEmModel::HighEnergyLimit(), G4GSPWACorrections::Initialise(), G4GoudsmitSaundersonTable::Initialise(), G4VMscModel::InitialiseParameters(), G4EmParameters::Instance(), G4InuclParticleNames::isElectron(), G4VEmModel::IsMaster(), G4VEmModel::LowEnergyLimit(), G4GoudsmitSaundersonTable::SetOptionMottCorrection(), G4GoudsmitSaundersonTable::SetOptionPWACorrection(), and SetParticle().
void G4GoudsmitSaundersonMscModel::InitialiseLocal (const G4ParticleDefinition * p, G4VEmModel * masterModel) virtual
Reimplemented from G4VEmModel.
Definition at line 300 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 300 of file G4GoudsmitSaundersonMscModel.cc
References fGSTable, fIsUseMottCorrection, fIsUsePWACorrection, fPWACorrection, GetGSTable(), GetOptionMottCorrection(), GetOptionPWACorrection(), and GetPWACorrection().
G4GoudsmitSaundersonMscModel& G4GoudsmitSaundersonMscModel::operator= (const G4GoudsmitSaundersonMscModel & right) private
G4double G4GoudsmitSaundersonMscModel::Randomizetlimit () inline private
Definition at line 279 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 279 of file G4GoudsmitSaundersonMscModel.hh
References rndmEngineMod, G4INCL::DeJongSpin::shoot(), and tlimit.
Referenced by ComputeTruePathLengthLimit().
void G4GoudsmitSaundersonMscModel::SampleMSC ()
Definition at line 923 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 923 of file G4GoudsmitSaundersonMscModel.cc
References b, c, currentCouple, currentKinEnergy, currentMaterialIndex, currentRange, Acts::Test::delta, e, CLHEP::electron_mass_c2, source.hepunit::electron_mass_c2, Acts::VectorHelpers::eta(), fG1, fGSTable, fIsEverythingWasDone, fIsNoDisplace, fIsNoScatteringInMSC, fLambda0, fLambda1, fMCtoG2PerG1, fMCtoQ1, fScrA, fTheDisplacementVector, fTheNewDirection, fTheTrueStepLenght, fTheZPathLenght, G4Exp(), G4Log(), G4UniformRand, G4VMscModel::GetEnergy(), GetTransportMeanFreePath(), gIsUseAccurate, particle, pt2, G4GoudsmitSaundersonTable::Sampling(), CLHEP::Hep3Vector::set(), temp1, CLHEP::twopi, v2, and zz.
Referenced by ComputeTruePathLengthLimit(), and SampleScattering().
G4ThreeVector & G4GoudsmitSaundersonMscModel::SampleScattering (const G4ThreeVector & oldDirection, G4double safety) virtual
Implements G4VMscModel.
Definition at line 878 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 878 of file G4GoudsmitSaundersonMscModel.cc
References fIsEndedUpOnBoundary, fIsEverythingWasDone, fIsMultipleSacettring, fIsNoDisplace, fIsNoScatteringInMSC, fIsSingleScattering, fParticleChange, fTheDisplacementVector, fTheNewDirection, fUseDistanceToBoundary, fUseSafetyPlus, G4ParticleChangeForMSC::ProposeMomentumDirection(), CLHEP::Hep3Vector::rotateUz(), SampleMSC(), and G4VMscModel::steppingAlgorithm.
void G4GoudsmitSaundersonMscModel::SetOptionMottCorrection (G4bool opt) inline
Definition at line 174 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4GoudsmitSaundersonMscModel.hh
References fIsUseMottCorrection.
Referenced by G4EmModelActivator::GetGSModel().
void G4GoudsmitSaundersonMscModel::SetOptionPWACorrection (G4bool opt) inline
Definition at line 170 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4GoudsmitSaundersonMscModel.hh
References fIsUsePWACorrection.
void G4GoudsmitSaundersonMscModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 267 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 267 of file G4GoudsmitSaundersonMscModel.hh
References charge, CLHEP::eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, and particle.
Referenced by Initialise(), and StartTracking().
void G4GoudsmitSaundersonMscModel::StartTracking (G4Track * track) virtual
Reimplemented from G4VEmModel.
Definition at line 461 of file G4GoudsmitSaundersonMscModel.cc.
View newest version in sPHENIX GitHub at line 461 of file G4GoudsmitSaundersonMscModel.cc
References firstStep, geombig, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), rangeinit, SetParticle(), tgeom, and tlimit.
Member Data Documentation
G4int G4GoudsmitSaundersonMscModel::charge private
Definition at line 219 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 219 of file G4GoudsmitSaundersonMscModel.hh
Referenced by G4GoudsmitSaundersonMscModel(), and SetParticle().
const G4MaterialCutsCouple* G4GoudsmitSaundersonMscModel::currentCouple private
Definition at line 227 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 227 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), GetTransportMeanFreePathOnly(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::currentKinEnergy private
Definition at line 197 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 197 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and SampleMSC().
G4int G4GoudsmitSaundersonMscModel::currentMaterialIndex private
Definition at line 220 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 220 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::currentRange private
Definition at line 198 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 198 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fG1 private
Definition at line 238 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 238 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), and SampleMSC().
G4GoudsmitSaundersonTable* G4GoudsmitSaundersonMscModel::fGSTable private
Definition at line 229 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 229 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetGSTable(), GetTransportMeanFreePath(), GetTransportMeanFreePathOnly(), Initialise(), InitialiseLocal(), SampleMSC(), and ~G4GoudsmitSaundersonMscModel().
G4bool G4GoudsmitSaundersonMscModel::firstStep private
Definition at line 222 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 222 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and StartTracking().
G4bool G4GoudsmitSaundersonMscModel::fIsEndedUpOnBoundary private
Definition at line 251 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 251 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel(), and SampleScattering().
G4bool G4GoudsmitSaundersonMscModel::fIsEverythingWasDone private
Definition at line 254 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 254 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel(), SampleMSC(), and SampleScattering().
G4bool G4GoudsmitSaundersonMscModel::fIsFirstRealStep private
Definition at line 259 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 259 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4bool G4GoudsmitSaundersonMscModel::fIsInsideSkin private
Definition at line 257 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 257 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4bool G4GoudsmitSaundersonMscModel::fIsMultipleSacettring private
Definition at line 252 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 252 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel(), and SampleScattering().
G4bool G4GoudsmitSaundersonMscModel::fIsNoDisplace private
Definition at line 256 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 256 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), SampleMSC(), and SampleScattering().
G4bool G4GoudsmitSaundersonMscModel::fIsNoScatteringInMSC private
Definition at line 255 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 255 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), SampleMSC(), and SampleScattering().
G4bool G4GoudsmitSaundersonMscModel::fIsSingleScattering private
Definition at line 253 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 253 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and SampleScattering().
G4bool G4GoudsmitSaundersonMscModel::fIsUseMottCorrection private
Definition at line 233 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 233 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetOptionMottCorrection(), GetTransportMeanFreePath(), GetTransportMeanFreePathOnly(), Initialise(), InitialiseLocal(), and SetOptionMottCorrection().
G4bool G4GoudsmitSaundersonMscModel::fIsUsePWACorrection private
Definition at line 232 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 232 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetOptionPWACorrection(), GetTransportMeanFreePath(), GetTransportMeanFreePathOnly(), Initialise(), InitialiseLocal(), and SetOptionPWACorrection().
G4bool G4GoudsmitSaundersonMscModel::fIsWasOnBoundary private
Definition at line 258 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 258 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::fLambda0 private
Definition at line 235 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 235 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fLambda1 private
Definition at line 236 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 236 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fMCtoG2PerG1 private
Definition at line 242 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 242 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fMCtoQ1 private
Definition at line 241 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 241 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fMCtoScrA private
Definition at line 240 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 240 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), and GetTransportMeanFreePath().
G4ParticleChangeForMSC* G4GoudsmitSaundersonMscModel::fParticleChange private
Definition at line 226 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 226 of file G4GoudsmitSaundersonMscModel.hh
Referenced by G4GoudsmitSaundersonMscModel(), Initialise(), and SampleScattering().
G4GSPWACorrections* G4GoudsmitSaundersonMscModel::fPWACorrection private
Definition at line 230 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 230 of file G4GoudsmitSaundersonMscModel.hh
Referenced by CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetPWACorrection(), GetTransportMeanFreePath(), GetTransportMeanFreePathOnly(), Initialise(), InitialiseLocal(), and ~G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::fr private
Definition at line 200 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 200 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::fScrA private
Definition at line 237 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 237 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel(), GetTransportMeanFreePath(), and SampleMSC().
G4ThreeVector G4GoudsmitSaundersonMscModel::fTheDisplacementVector private
Definition at line 248 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 248 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), SampleMSC(), and SampleScattering().
G4ThreeVector G4GoudsmitSaundersonMscModel::fTheNewDirection private
Definition at line 249 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 249 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), SampleMSC(), and SampleScattering().
G4double G4GoudsmitSaundersonMscModel::fTheTransportDistance private
Definition at line 245 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 245 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::fTheTrueStepLenght private
Definition at line 244 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 244 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fTheZPathLenght private
Definition at line 246 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 246 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), ComputeTrueStepLength(), G4GoudsmitSaundersonMscModel(), and SampleMSC().
G4double G4GoudsmitSaundersonMscModel::fZeff private
Definition at line 217 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 217 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::geombig private
Definition at line 202 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 202 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and StartTracking().
G4double G4GoudsmitSaundersonMscModel::geomlimit private
Definition at line 203 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 203 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4bool G4GoudsmitSaundersonMscModel::gIsOptimizationOn = true static private
Definition at line 262 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 262 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit().
G4bool G4GoudsmitSaundersonMscModel::gIsUseAccurate = true static private
Definition at line 261 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 261 of file G4GoudsmitSaundersonMscModel.hh
Referenced by SampleMSC().
G4double G4GoudsmitSaundersonMscModel::mass private
Definition at line 212 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 212 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), G4GoudsmitSaundersonMscModel(), and SetParticle().
G4double G4GoudsmitSaundersonMscModel::par1 private
Definition at line 207 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 207 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::par2 private
Definition at line 208 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 208 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::par3 private
Definition at line 209 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 209 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), and G4GoudsmitSaundersonMscModel().
const G4ParticleDefinition* G4GoudsmitSaundersonMscModel::particle private
Definition at line 225 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 225 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), SampleMSC(), and SetParticle().
G4double G4GoudsmitSaundersonMscModel::presafety private
Definition at line 216 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 216 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::rangeinit private
Definition at line 201 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 201 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and StartTracking().
CLHEP::HepRandomEngine* G4GoudsmitSaundersonMscModel::rndmEngineMod private
Definition at line 195 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 195 of file G4GoudsmitSaundersonMscModel.hh
Referenced by G4GoudsmitSaundersonMscModel(), and Randomizetlimit().
G4double G4GoudsmitSaundersonMscModel::taulim private
Definition at line 213 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 213 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::tausmall private
Definition at line 211 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 211 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), and G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::tgeom private
Definition at line 205 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 205 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), and StartTracking().
G4LossTableManager* G4GoudsmitSaundersonMscModel::theManager private
Definition at line 224 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 224 of file G4GoudsmitSaundersonMscModel.hh
Referenced by G4GoudsmitSaundersonMscModel().
G4double G4GoudsmitSaundersonMscModel::tlimit private
Definition at line 204 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 204 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel(), Randomizetlimit(), and StartTracking().
G4double G4GoudsmitSaundersonMscModel::tlimitminfix2 private
Definition at line 210 of file G4GoudsmitSaundersonMscModel.hh.
View newest version in sPHENIX GitHub at line 210 of file G4GoudsmitSaundersonMscModel.hh
Referenced by ComputeGeomPathLength(), ComputeTrueStepLength(), and G4GoudsmitSaundersonMscModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4GoudsmitSaundersonMscModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4GoudsmitSaundersonMscModel.cc