ECCE @ EIC Software: G4RKPropagation Class Reference
G4RKPropagation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4RKPropagation.hh>
Public Member Functions
G4RKPropagation ()
virtual ~G4RKPropagation ()
virtual void Init (G4V3DNucleus *nucleus)
virtual void Transport (G4KineticTrackVector &theActive, const G4KineticTrackVector &theSpectators, G4double theTimeStep)
G4bool GetSphereIntersectionTimes (const G4KineticTrack *track, G4double &t1, G4double &t2)
G4ThreeVector GetMomentumTransfer () const
G4double GetBarrier (G4int encoding)
G4double GetField (G4int encoding, G4ThreeVector pos)
Public Member Functions inherited from G4VFieldPropagation
G4VFieldPropagation ()
virtual ~G4VFieldPropagation ()
Private Member Functions
G4RKPropagation (const G4RKPropagation &right)
const G4RKPropagation & operator= (const G4RKPropagation &right)
G4bool operator== (const G4RKPropagation &right) const
G4bool operator!= (const G4RKPropagation &right) const
G4bool GetSphereIntersectionTimes (const G4double radius, const G4ThreeVector &currentPos, const G4LorentzVector &momentum, G4double &t1, G4double &t2)
G4bool FieldTransport (G4KineticTrack *track, const G4double timestep)
G4bool FreeTransport (G4KineticTrack *track, const G4double timestep)
void delete_FieldsAndMap (std::map< G4int, G4VNuclearField *, std::less< G4int > > *aMap)
void delete_EquationsAndMap (std::map< G4int, G4Mag_EqRhs *, std::less< G4int > > *aMap)
Private Attributes
G4double theOuterRadius
G4V3DNucleus * theNucleus
std::map< G4int,
G4VNuclearField *, std::less
< G4int > > * theFieldMap
std::map< G4int, G4Mag_EqRhs
*, std::less< G4int > > * theEquationMap
G4KM_DummyField * theField
G4ThreeVector theMomentumTranfer
Detailed Description
Definition at line 38 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 38 of file G4RKPropagation.hh
Constructor & Destructor Documentation
G4RKPropagation::G4RKPropagation ()
Definition at line 80 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 80 of file G4RKPropagation.cc
G4RKPropagation::~G4RKPropagation () virtual
Definition at line 87 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 87 of file G4RKPropagation.cc
References delete_EquationsAndMap(), delete_FieldsAndMap(), theEquationMap, theField, and theFieldMap.
G4RKPropagation::G4RKPropagation (const G4RKPropagation & right) private
Member Function Documentation
void G4RKPropagation::delete_EquationsAndMap (std::map< G4int, G4Mag_EqRhs *, std::less< G4int > > * aMap) private
Definition at line 644 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 644 of file G4RKPropagation.cc
Referenced by Init(), and ~G4RKPropagation().
void G4RKPropagation::delete_FieldsAndMap (std::map< G4int, G4VNuclearField *, std::less< G4int > > * aMap) private
Definition at line 627 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 627 of file G4RKPropagation.cc
Referenced by Init(), and ~G4RKPropagation().
G4bool G4RKPropagation::FieldTransport (G4KineticTrack * track, const G4double timestep) private
Definition at line 479 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 479 of file G4RKPropagation.cc
References G4MagInt_Driver::AccurateAdvance(), CLHEP::HepLorentzVector::beta(), source.hepunit::c_light, CLHEP::HepLorentzVector::e(), eps, G4endl, G4KineticTrack::GetActualMass(), G4KineticTrack::GetDefinition(), G4V3DNucleus::GetMass(), G4ParticleDefinition::GetPDGEncoding(), G4KineticTrack::GetPosition(), G4KineticTrack::GetTrackingMomentum(), CLHEP::Hep3Vector::mag2(), mom, second, G4KineticTrack::SetPosition(), G4KineticTrack::SetTrackingMomentum(), sqr(), propagation_timing::stepper, theMomentumTranfer, theNucleus, track, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by Transport().
G4bool G4RKPropagation::FreeTransport (G4KineticTrack * track, const G4double timestep) private
Definition at line 553 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 553 of file G4RKPropagation.cc
References source.hepunit::c_light, CLHEP::HepLorentzVector::e(), G4KineticTrack::GetPosition(), G4KineticTrack::GetTrackingMomentum(), G4KineticTrack::SetPosition(), and CLHEP::HepLorentzVector::vect().
Referenced by Transport().
G4double G4RKPropagation::GetBarrier (G4int encoding) inline
Definition at line 84 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RKPropagation.hh
References theFieldMap.
Referenced by G4BinaryCascade::Capture(), G4BinaryCascade::CorrectBarionsOnBoundary(), and G4BinaryCascade::DebugApplyCollision().
G4double G4RKPropagation::GetField (G4int encoding, G4ThreeVector pos) inline
Definition at line 92 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RKPropagation.hh
References theFieldMap.
Referenced by G4BinaryCascade::Capture(), and G4BinaryCascade::DebugApplyCollision().
G4ThreeVector G4RKPropagation::GetMomentumTransfer () const virtual
Implements G4VFieldPropagation.
Definition at line 471 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 471 of file G4RKPropagation.cc
References theMomentumTranfer.
G4bool G4RKPropagation::GetSphereIntersectionTimes (const G4KineticTrack * track, G4double & t1, G4double & t2)
Definition at line 606 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 606 of file G4RKPropagation.cc
References source.hepunit::c_light, CLHEP::Hep3Vector::dot(), CLHEP::HepLorentzVector::e(), fermi, G4KineticTrack::GetPosition(), G4KineticTrack::GetTrackingMomentum(), CLHEP::Hep3Vector::mag2(), radius, theOuterRadius, and CLHEP::HepLorentzVector::vect().
Referenced by Transport().
G4bool G4RKPropagation::GetSphereIntersectionTimes (const G4double radius, const G4ThreeVector & currentPos, const G4LorentzVector & momentum, G4double & t1, G4double & t2) private
Definition at line 584 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 584 of file G4RKPropagation.cc
References source.hepunit::c_light, CLHEP::Hep3Vector::dot(), CLHEP::HepLorentzVector::e(), CLHEP::Hep3Vector::mag2(), radius, and CLHEP::HepLorentzVector::vect().
void G4RKPropagation::Init (G4V3DNucleus * nucleus) virtual
Implements G4VFieldPropagation.
Definition at line 99 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 99 of file G4RKPropagation.cc
References G4AntiProton::AntiProton(), delete_EquationsAndMap(), delete_FieldsAndMap(), G4V3DNucleus::GetOuterRadius(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZero::KaonZero(), mass, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4Proton::Proton(), G4KM_OpticalEqRhs::SetFactor(), G4KM_NucleonEqRhs::SetMass(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), theEquationMap, theField, theFieldMap, theNucleus, and theOuterRadius.
G4bool G4RKPropagation::operator!= (const G4RKPropagation & right) const private
const G4RKPropagation& G4RKPropagation::operator= (const G4RKPropagation & right) private
G4bool G4RKPropagation::operator== (const G4RKPropagation & right) const private
void G4RKPropagation::Transport (G4KineticTrackVector & theActive, const G4KineticTrackVector & theSpectators, G4double theTimeStep) virtual
Implements G4VFieldPropagation.
Definition at line 223 of file G4RKPropagation.cc.
View newest version in sPHENIX GitHub at line 223 of file G4RKPropagation.cc
References kdfinder::abs(), G4KineticTrack::captured, DBL_MAX, CLHEP::HepLorentzVector::e(), FieldTransport(), FreeTransport(), G4cerr, G4cout, G4endl, G4KineticTrack::GetActualMass(), G4KineticTrack::GetDefinition(), G4VNuclearField::GetField(), G4V3DNucleus::GetMass(), G4ParticleDefinition::GetPDGEncoding(), G4KineticTrack::GetPosition(), G4KineticTrack::GetProjectilePotential(), GetSphereIntersectionTimes(), G4KineticTrack::GetState(), G4KineticTrack::GetTrackingMomentum(), G4KineticTrack::gone_out, G4KineticTrack::inside, CLHEP::HepLorentzVector::mag(), G4KineticTrack::miss_nucleus, G4Neutron::Neutron(), G4KineticTrack::outside, G4Proton::Proton(), G4KineticTrack::SetState(), G4KineticTrack::SetTrackingMomentum(), sqr(), theFieldMap, theMomentumTranfer, theNucleus, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Member Data Documentation
std::map<G4int, G4Mag_EqRhs *, std::less<G4int> >* G4RKPropagation::theEquationMap private
Definition at line 64 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RKPropagation.hh
Referenced by Init(), and ~G4RKPropagation().
G4KM_DummyField* G4RKPropagation::theField private
Definition at line 65 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RKPropagation.hh
Referenced by Init(), and ~G4RKPropagation().
std::map<G4int, G4VNuclearField *, std::less<G4int> >* G4RKPropagation::theFieldMap private
Definition at line 63 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RKPropagation.hh
Referenced by GetBarrier(), GetField(), Init(), Transport(), and ~G4RKPropagation().
G4ThreeVector G4RKPropagation::theMomentumTranfer private
Definition at line 67 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RKPropagation.hh
Referenced by FieldTransport(), GetMomentumTransfer(), and Transport().
G4V3DNucleus* G4RKPropagation::theNucleus private
Definition at line 62 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RKPropagation.hh
Referenced by FieldTransport(), Init(), and Transport().
G4double G4RKPropagation::theOuterRadius private
Definition at line 61 of file G4RKPropagation.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RKPropagation.hh
Referenced by GetSphereIntersectionTimes(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4RKPropagation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4RKPropagation.cc