ECCE @ EIC Software: G4HCtable Class Reference
G4HCtable Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4HCtable.hh>
Public Member Functions
G4HCtable ()
~G4HCtable ()
G4int Registor (G4String SDname, G4String HCname)
G4int GetCollectionID (G4String HCname) const
G4int GetCollectionID (G4VSensitiveDetector *aSD) const
G4int entries () const
G4String GetSDname (G4int i) const
G4String GetHCname (G4int i) const
Private Attributes
std::vector< G4String > SDlist
std::vector< G4String > HClist
Detailed Description
Definition at line 49 of file G4HCtable.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HCtable.hh
Constructor & Destructor Documentation
G4HCtable::G4HCtable ()
Definition at line 32 of file G4HCtable.cc.
View newest version in sPHENIX GitHub at line 32 of file G4HCtable.cc
G4HCtable::~G4HCtable ()
Definition at line 34 of file G4HCtable.cc.
View newest version in sPHENIX GitHub at line 34 of file G4HCtable.cc
Member Function Documentation
G4int G4HCtable::entries () const inline
Definition at line 65 of file G4HCtable.hh.
View newest version in sPHENIX GitHub at line 65 of file G4HCtable.hh
References HClist.
Referenced by G4SDManager::GetCollectionCapacity(), GetHCname(), GetSDname(), and G4SDManager::PrepareNewEvent().
G4int G4HCtable::GetCollectionID (G4String HCname) const
Definition at line 45 of file G4HCtable.cc.
View newest version in sPHENIX GitHub at line 45 of file G4HCtable.cc
References HClist, G4String::index(), and SDlist.
Referenced by G4SDManager::GetCollectionID().
G4int G4HCtable::GetCollectionID (G4VSensitiveDetector * aSD) const
Definition at line 76 of file G4HCtable.cc.
View newest version in sPHENIX GitHub at line 76 of file G4HCtable.cc
References G4cerr, G4endl, G4VSensitiveDetector::GetCollectionName(), G4VSensitiveDetector::GetName(), G4VSensitiveDetector::GetNumberOfCollections(), k, and SDlist.
G4String G4HCtable::GetHCname (G4int i) const inline
Definition at line 72 of file G4HCtable.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HCtable.hh
References entries(), and HClist.
G4String G4HCtable::GetSDname (G4int i) const inline
Definition at line 67 of file G4HCtable.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HCtable.hh
References entries(), and SDlist.
G4int G4HCtable::Registor (G4String SDname, G4String HCname)
Definition at line 36 of file G4HCtable.cc.
View newest version in sPHENIX GitHub at line 36 of file G4HCtable.cc
References HClist, and SDlist.
Referenced by G4SDManager::AddNewCollection().
Member Data Documentation
std::vector<G4String> G4HCtable::HClist private
Definition at line 62 of file G4HCtable.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HCtable.hh
Referenced by entries(), GetCollectionID(), GetHCname(), and Registor().
std::vector<G4String> G4HCtable::SDlist private
Definition at line 61 of file G4HCtable.hh.
View newest version in sPHENIX GitHub at line 61 of file G4HCtable.hh
Referenced by GetCollectionID(), GetSDname(), and Registor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4HCtable.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4HCtable.cc