ECCE @ EIC Software: G4ChatterjeeCrossSection Class Reference
G4ChatterjeeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4ChatterjeeCrossSection.hh>
Static Public Member Functions
static G4double ComputeCrossSection (G4double K, G4double cb, G4double resA13, G4double amu1, G4int idx, G4int Z, G4int resA)
Detailed Description
Definition at line 40 of file G4ChatterjeeCrossSection.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ChatterjeeCrossSection.hh
Member Function Documentation
G4double G4ChatterjeeCrossSection::ComputeCrossSection (G4double K, G4double cb, G4double resA13, G4double amu1, G4int idx, G4int Z, G4int resA) static
Definition at line 56 of file G4ChatterjeeCrossSection.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ChatterjeeCrossSection.cc
References kdfinder::abs(), Acts::Test::cb, emax, incremental_prev_tag::idx, max, min, paramC, and r.
Referenced by G4PreCompoundFragment::CrossSection(), and G4EvaporationProbability::CrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4ChatterjeeCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/src/G4ChatterjeeCrossSection.cc