ECCE @ EIC Software: CLHEP::HepLorentzRotation Class Reference
CLHEP::HepLorentzRotation Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/LorentzRotation.h>
Classes
class HepLorentzRotation_row
Public Member Functions
HepLorentzRotation ()
HepLorentzRotation (const HepLorentzRotation &r)
HepLorentzRotation (HepLorentzRotation &&r)=default
HepLorentzRotation (const HepRotation &r)
HepLorentzRotation (const HepRotationX &r)
HepLorentzRotation (const HepRotationY &r)
HepLorentzRotation (const HepRotationZ &r)
HepLorentzRotation (const HepBoost &b)
HepLorentzRotation (const HepBoostX &b)
HepLorentzRotation (const HepBoostY &b)
HepLorentzRotation (const HepBoostZ &b)
HepLorentzRotation & operator= (HepLorentzRotation &&m)=default
HepLorentzRotation & operator= (const HepLorentzRotation &m)
HepLorentzRotation & operator= (const HepRotation &m)
HepLorentzRotation & operator= (const HepBoost &m)
HepLorentzRotation & set (double bx, double by, double bz)
HepLorentzRotation & set (const Hep3Vector &p)
HepLorentzRotation & set (const HepRotation &r)
HepLorentzRotation & set (const HepRotationX &r)
HepLorentzRotation & set (const HepRotationY &r)
HepLorentzRotation & set (const HepRotationZ &r)
HepLorentzRotation & set (const HepBoost &boost)
HepLorentzRotation & set (const HepBoostX &boost)
HepLorentzRotation & set (const HepBoostY &boost)
HepLorentzRotation & set (const HepBoostZ &boost)
HepLorentzRotation (double bx, double by, double bz)
HepLorentzRotation (const Hep3Vector &p)
HepLorentzRotation & set (const HepBoost &B, const HepRotation &R)
HepLorentzRotation (const HepBoost &B, const HepRotation &R)
HepLorentzRotation & set (const HepRotation &R, const HepBoost &B)
HepLorentzRotation (const HepRotation &R, const HepBoost &B)
HepLorentzRotation (const HepLorentzVector &col1, const HepLorentzVector &col2, const HepLorentzVector &col3, const HepLorentzVector &col4)
HepLorentzRotation & set (const HepLorentzVector &col1, const HepLorentzVector &col2, const HepLorentzVector &col3, const HepLorentzVector &col4)
HepLorentzRotation & setRows (const HepLorentzVector &row1, const HepLorentzVector &row2, const HepLorentzVector &row3, const HepLorentzVector &row4)
HepLorentzRotation & set (const HepRep4x4 &rep)
HepLorentzRotation (const HepRep4x4 &rep)
double xx () const
double xy () const
double xz () const
double xt () const
double yx () const
double yy () const
double yz () const
double yt () const
double zx () const
double zy () const
double zz () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
HepRep4x4 rep4x4 () const
const HepLorentzRotation_row operator[] (int) const
double operator() (int, int) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
void decompose (HepBoost &boost, HepRotation &rotation) const
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (HepRotation &rotation, HepBoost &boost) const
int compare (const HepLorentzRotation &m) const
bool operator== (const HepLorentzRotation &) const
bool operator!= (const HepLorentzRotation &) const
bool operator<= (const HepLorentzRotation &) const
bool operator>= (const HepLorentzRotation &) const
bool operator< (const HepLorentzRotation &) const
bool operator> (const HepLorentzRotation &) const
bool isIdentity () const
double distance2 (const HepBoost &b) const
double distance2 (const HepRotation &r) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &b) const
double howNear (const HepRotation &r) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoost &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
HepLorentzVector vectorMultiplication (const HepLorentzVector &) const
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &p) const
HepLorentzRotation matrixMultiplication (const HepRep4x4 &m) const
HepLorentzRotation operator* (const HepBoost &b) const
HepLorentzRotation operator* (const HepRotation &r) const
HepLorentzRotation operator* (const HepLorentzRotation &lt) const
HepLorentzRotation & operator*= (const HepBoost &b)
HepLorentzRotation & operator*= (const HepRotation &r)
HepLorentzRotation & operator*= (const HepLorentzRotation &lt)
HepLorentzRotation & transform (const HepBoost &b)
HepLorentzRotation & transform (const HepRotation &r)
HepLorentzRotation & transform (const HepLorentzRotation &lt)
HepLorentzRotation & rotateX (double delta)
HepLorentzRotation & rotateY (double delta)
HepLorentzRotation & rotateZ (double delta)
HepLorentzRotation & rotate (double delta, const Hep3Vector &axis)
HepLorentzRotation & rotate (double delta, const Hep3Vector *axis)
HepLorentzRotation & boostX (double beta)
HepLorentzRotation & boostY (double beta)
HepLorentzRotation & boostZ (double beta)
HepLorentzRotation & boost (double, double, double)
HepLorentzRotation & boost (const Hep3Vector &)
HepLorentzRotation inverse () const
HepLorentzRotation & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Static Public Attributes
static DLL_API const
HepLorentzRotation IDENTITY
Protected Member Functions
HepLorentzRotation (double mxx, double mxy, double mxz, double mxt, double myx, double myy, double myz, double myt, double mzx, double mzy, double mzz, double mzt, double mtx, double mty, double mtz, double mtt)
void setBoost (double, double, double)
Protected Attributes
double mxx
double mxy
double mxz
double mxt
double myx
double myy
double myz
double myt
double mzx
double mzy
double mzz
double mzt
double mtx
double mty
double mtz
double mtt
Friends
HepLorentzRotation inverseOf (const HepLorentzRotation &lt)
Detailed Description
Author
Definition at line 52 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 52 of file LorentzRotation.h
Constructor & Destructor Documentation
CLHEP::HepLorentzRotation::HepLorentzRotation () inline
Referenced by matrixMultiplication(), and set().
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepLorentzRotation & r) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (HepLorentzRotation && r) inline default
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepRotation & r) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepRotationX & r) inline explicit
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepRotationY & r) inline explicit
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepRotationZ & r) inline explicit
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepBoost & b) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepBoostX & b) inline explicit
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepBoostY & b) inline explicit
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepBoostZ & b) inline explicit
CLHEP::HepLorentzRotation::HepLorentzRotation (double bx, double by, double bz) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (const Hep3Vector & p) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepBoost & B, const HepRotation & R) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepRotation & R, const HepBoost & B) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepLorentzVector & col1, const HepLorentzVector & col2, const HepLorentzVector & col3, const HepLorentzVector & col4)
Definition at line 198 of file LorentzRotationC.cc.
View newest version in sPHENIX GitHub at line 198 of file LorentzRotationC.cc
CLHEP::HepLorentzRotation::HepLorentzRotation (const HepRep4x4 & rep) inline
CLHEP::HepLorentzRotation::HepLorentzRotation (double mxx, double mxy, double mxz, double mxt, double myx, double myy, double myz, double myt, double mzx, double mzy, double mzz, double mzt, double mtx, double mty, double mtz, double mtt) inline protected
Member Function Documentation
HepLorentzRotation& CLHEP::HepLorentzRotation::boost (double , double , double) inline
Referenced by avscatcen(), getscatterer(), maxscatcen(), and medinit().
HepLorentzRotation& CLHEP::HepLorentzRotation::boost (const Hep3Vector &) inline
HepLorentzRotation & CLHEP::HepLorentzRotation::boostX (double beta)
Definition at line 185 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 185 of file LorentzRotation.cc
References mtt, mtx, mty, mtz, mxt, mxx, mxy, mxz, r1, row1(), row4(), CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
HepLorentzRotation & CLHEP::HepLorentzRotation::boostY (double beta)
Definition at line 203 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 203 of file LorentzRotation.cc
References mtt, mtx, mty, mtz, myt, myx, myy, myz, r2, row2(), row4(), CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
HepLorentzRotation & CLHEP::HepLorentzRotation::boostZ (double beta)
Definition at line 221 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 221 of file LorentzRotation.cc
References mtt, mtx, mty, mtz, mzt, mzx, mzy, mzz, row3(), row4(), CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
HepLorentzVector CLHEP::HepLorentzRotation::col1 () const inline
HepLorentzVector CLHEP::HepLorentzRotation::col2 () const inline
HepLorentzVector CLHEP::HepLorentzRotation::col3 () const inline
HepLorentzVector CLHEP::HepLorentzRotation::col4 () const inline
int CLHEP::HepLorentzRotation::compare (const HepLorentzRotation & m) const
Definition at line 98 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 98 of file LorentzRotation.cc
References mtt, mtx, mty, mtz, mxt, mxx, mxy, mxz, myt, myx, myy, myz, mzt, mzx, mzy, and mzz.
void CLHEP::HepLorentzRotation::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 47 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 47 of file LorentzRotationD.cc
References CLHEP::HepRotation::axisAngle(), b, CLHEP::HepBoost::boostVector(), and r.
Referenced by CLHEP::HepBoostX::distance2(), CLHEP::HepBoostZ::distance2(), CLHEP::HepBoostY::distance2(), CLHEP::HepBoost::distance2(), CLHEP::HepRotationY::distance2(), CLHEP::HepRotationZ::distance2(), CLHEP::HepRotationX::distance2(), distance2(), CLHEP::HepRotation::distance2(), CLHEP::HepBoostZ::isNear(), CLHEP::HepBoostX::isNear(), CLHEP::HepBoostY::isNear(), CLHEP::HepBoost::isNear(), isNear(), and norm2().
void CLHEP::HepLorentzRotation::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 20 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 20 of file LorentzRotationD.cc
References B(), Acts::IntegrationTest::R, CLHEP::HepRotation::rectify(), CLHEP::HepBoost::set(), CLHEP::HepRotation::set(), xx(), xy(), xz(), yx(), yy(), yz(), zx(), zy(), and zz().
void CLHEP::HepLorentzRotation::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 80 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 80 of file LorentzRotationD.cc
References CLHEP::HepRotation::axisAngle(), b, CLHEP::HepBoost::boostVector(), and r.
void CLHEP::HepLorentzRotation::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 57 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 57 of file LorentzRotationD.cc
References B(), Acts::IntegrationTest::R, CLHEP::HepRotation::rectify(), CLHEP::HepBoost::set(), CLHEP::HepRotation::set(), xx(), xy(), xz(), yx(), yy(), yz(), zx(), zy(), and zz().
double CLHEP::HepLorentzRotation::distance2 (const HepBoost & b) const
Definition at line 89 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 89 of file LorentzRotationD.cc
References decompose(), CLHEP::HepBoost::distance2(), CLHEP::HepRotation::norm2(), and r1.
Referenced by howNear().
double CLHEP::HepLorentzRotation::distance2 (const HepRotation & r) const
Definition at line 98 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 98 of file LorentzRotationD.cc
References decompose(), CLHEP::HepRotation::distance2(), CLHEP::HepBoost::norm2(), and r1.
double CLHEP::HepLorentzRotation::distance2 (const HepLorentzRotation & lt) const
Definition at line 107 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 107 of file LorentzRotationD.cc
References decompose(), CLHEP::HepBoost::distance2(), CLHEP::HepRotation::distance2(), r1, and r2.
static double CLHEP::HepLorentzRotation::getTolerance () inline static
double CLHEP::HepLorentzRotation::howNear (const HepBoost & b) const
Definition at line 120 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 120 of file LorentzRotationD.cc
References distance2().
double CLHEP::HepLorentzRotation::howNear (const HepRotation & r) const
Definition at line 123 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 123 of file LorentzRotationD.cc
References distance2().
double CLHEP::HepLorentzRotation::howNear (const HepLorentzRotation & lt) const
Definition at line 126 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 126 of file LorentzRotationD.cc
References distance2().
HepLorentzRotation CLHEP::HepLorentzRotation::inverse () const inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4BinaryLightIonReaction::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4BinaryCascade::CorrectFinalPandE(), G4DiffractiveExcitation::ExciteParticipants(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4QGSMFragmentation::FragmentString(), PHHepMCGenEventv1::get_LorentzRotation_Lab2EvtGen(), G4MesonAbsorption::GetFinalState(), G4HadProjectile::InitialiseLocal(), G4LundStringFragmentation::Loop_toFragmentString(), G4ParticleHPEnAngCorrelation::Sample(), G4VPartonStringModel::Scatter(), and G4LundStringFragmentation::SplitLast().
HepLorentzRotation& CLHEP::HepLorentzRotation::invert () inline
bool CLHEP::HepLorentzRotation::isIdentity () const inline
bool CLHEP::HepLorentzRotation::isNear (const HepBoost & b, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 130 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 130 of file LorentzRotationD.cc
References decompose(), CLHEP::HepBoost::distance2(), CLHEP::HepRotation::norm2(), and r1.
bool CLHEP::HepLorentzRotation::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 143 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 143 of file LorentzRotationD.cc
References decompose(), CLHEP::HepRotation::distance2(), CLHEP::HepBoost::norm2(), and r1.
bool CLHEP::HepLorentzRotation::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 156 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 156 of file LorentzRotationD.cc
References decompose(), CLHEP::HepBoost::distance2(), CLHEP::HepRotation::distance2(), r1, and r2.
HepLorentzRotation CLHEP::HepLorentzRotation::matrixMultiplication (const HepRep4x4 & m) const
Definition at line 126 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 126 of file LorentzRotation.cc
References HepLorentzRotation(), mtt, mtx, mty, mtz, mxt, mxx, mxy, mxz, myt, myx, myy, myz, mzt, mzx, mzy, mzz, CLHEP::HepRep4x4::tt_, CLHEP::HepRep4x4::tx_, CLHEP::HepRep4x4::ty_, CLHEP::HepRep4x4::tz_, CLHEP::HepRep4x4::xt_, CLHEP::HepRep4x4::xx_, CLHEP::HepRep4x4::xy_, CLHEP::HepRep4x4::xz_, CLHEP::HepRep4x4::yt_, CLHEP::HepRep4x4::yx_, CLHEP::HepRep4x4::yy_, CLHEP::HepRep4x4::yz_, CLHEP::HepRep4x4::zt_, CLHEP::HepRep4x4::zx_, CLHEP::HepRep4x4::zy_, and CLHEP::HepRep4x4::zz_.
double CLHEP::HepLorentzRotation::norm2 () const
Definition at line 172 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 172 of file LorentzRotationD.cc
References b, decompose(), CLHEP::HepBoost::norm2(), CLHEP::HepRotation::norm2(), and r.
bool CLHEP::HepLorentzRotation::operator!= (const HepLorentzRotation &) const inline
double CLHEP::HepLorentzRotation::operator() (int i, int j) const
Definition at line 66 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 66 of file LorentzRotation.cc
References tt(), tx(), ty(), tz(), xt(), xx(), xy(), xz(), yt(), yx(), yy(), yz(), zt(), zx(), zy(), and zz().
HepLorentzVector CLHEP::HepLorentzRotation::operator() (const HepLorentzVector & w) const inline
HepLorentzVector CLHEP::HepLorentzRotation::operator* (const HepLorentzVector & p) const inline
HepLorentzRotation CLHEP::HepLorentzRotation::operator* (const HepBoost & b) const inline
HepLorentzRotation CLHEP::HepLorentzRotation::operator* (const HepRotation & r) const inline
HepLorentzRotation CLHEP::HepLorentzRotation::operator* (const HepLorentzRotation & lt) const inline
HepLorentzRotation& CLHEP::HepLorentzRotation::operator*= (const HepBoost & b) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::operator*= (const HepRotation & r) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::operator*= (const HepLorentzRotation & lt) inline
bool CLHEP::HepLorentzRotation::operator< (const HepLorentzRotation &) const inline
bool CLHEP::HepLorentzRotation::operator<= (const HepLorentzRotation &) const inline
HepLorentzRotation& CLHEP::HepLorentzRotation::operator= (HepLorentzRotation && m) inline default
HepLorentzRotation& CLHEP::HepLorentzRotation::operator= (const HepLorentzRotation & m) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::operator= (const HepRotation & m) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::operator= (const HepBoost & m) inline
bool CLHEP::HepLorentzRotation::operator== (const HepLorentzRotation &) const inline
bool CLHEP::HepLorentzRotation::operator> (const HepLorentzRotation &) const inline
bool CLHEP::HepLorentzRotation::operator>= (const HepLorentzRotation &) const inline
const HepLorentzRotation_row CLHEP::HepLorentzRotation::operator[] (int) const inline
std::ostream & CLHEP::HepLorentzRotation::print (std::ostream & os) const
Definition at line 239 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 239 of file LorentzRotation.cc
References tt(), tx(), ty(), tz(), xt(), xx(), xy(), xz(), yt(), yx(), yy(), yz(), zt(), zx(), zy(), and zz().
void CLHEP::HepLorentzRotation::rectify ()
Definition at line 179 of file LorentzRotationD.cc.
View newest version in sPHENIX GitHub at line 179 of file LorentzRotationD.cc
References G4InuclParticleNames::gam, Acts::IntegrationTest::R, tt(), tx(), ty(), tz(), xx(), xy(), xz(), yx(), yy(), yz(), zx(), zy(), and zz().
HepRep4x4 CLHEP::HepLorentzRotation::rep4x4 () const inline
Referenced by CLHEP::operator*(), and CLHEP::HepBoost::operator*().
HepLorentzRotation& CLHEP::HepLorentzRotation::rotate (double delta, const Hep3Vector & axis) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::rotate (double delta, const Hep3Vector * axis) inline
HepLorentzRotation & CLHEP::HepLorentzRotation::rotateX (double delta)
Definition at line 149 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 149 of file LorentzRotation.cc
References c1, myt, myx, myy, myz, mzt, mzx, mzy, mzz, r2, row2(), row3(), s1, CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
HepLorentzRotation & CLHEP::HepLorentzRotation::rotateY (double delta)
Definition at line 161 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 161 of file LorentzRotation.cc
References c1, mxt, mxx, mxy, mxz, mzt, mzx, mzy, mzz, r1, row1(), row3(), s1, CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4BinaryLightIonReaction::ApplyYourself(), G4Fancy3DNucleus::ChoosePositions(), G4DiffractiveExcitation::CreateStrings(), G4DiffractiveExcitation::ExciteParticipants(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4HadProjectile::InitialiseLocal(), G4ParticleHPEnAngCorrelation::Sample(), and G4VPartonStringModel::Scatter().
HepLorentzRotation & CLHEP::HepLorentzRotation::rotateZ (double delta)
Definition at line 173 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 173 of file LorentzRotation.cc
References c1, mxt, mxx, mxy, mxz, myt, myx, myy, myz, r1, r2, row1(), row2(), s1, CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4BinaryLightIonReaction::ApplyYourself(), G4Fancy3DNucleus::ChoosePositions(), G4DiffractiveExcitation::CreateStrings(), G4DiffractiveExcitation::ExciteParticipants(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4HadProjectile::InitialiseLocal(), G4ParticleHPEnAngCorrelation::Sample(), and G4VPartonStringModel::Scatter().
HepLorentzVector CLHEP::HepLorentzRotation::row1 () const inline
Referenced by boostX(), rotateY(), and rotateZ().
HepLorentzVector CLHEP::HepLorentzRotation::row2 () const inline
Referenced by boostY(), rotateX(), and rotateZ().
HepLorentzVector CLHEP::HepLorentzRotation::row3 () const inline
Referenced by boostZ(), rotateX(), and rotateY().
HepLorentzVector CLHEP::HepLorentzRotation::row4 () const inline
Referenced by boostX(), boostY(), and boostZ().
HepLorentzRotation & CLHEP::HepLorentzRotation::set (double bx, double by, double bz)
Definition at line 26 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 26 of file LorentzRotation.cc
Referenced by G4BinaryCascade::DecayVoidNucleus(), and G4BinaryCascade::GetFinalNucleusMomentum().
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const Hep3Vector & p) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepRotation & r) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepRotationX & r) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepRotationY & r) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepRotationZ & r) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepBoost & boost) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepBoostX & boost) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepBoostY & boost) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepBoostZ & boost) inline
HepLorentzRotation & CLHEP::HepLorentzRotation::set (const HepBoost & B, const HepRotation & R)
Definition at line 49 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 49 of file LorentzRotation.cc
References CLHEP::HepBoost::rep4x4(), and CLHEP::HepRotation::rep4x4().
HepLorentzRotation & CLHEP::HepLorentzRotation::set (const HepRotation & R, const HepBoost & B)
Definition at line 56 of file LorentzRotation.cc.
View newest version in sPHENIX GitHub at line 56 of file LorentzRotation.cc
References CLHEP::HepBoost::rep4x4(), and CLHEP::HepRotation::rep4x4().
HepLorentzRotation & CLHEP::HepLorentzRotation::set (const HepLorentzVector & col1, const HepLorentzVector & col2, const HepLorentzVector & col3, const HepLorentzVector & col4)
Definition at line 23 of file LorentzRotationC.cc.
View newest version in sPHENIX GitHub at line 23 of file LorentzRotationC.cc
References a, b, c, d, CLHEP::HepLorentzVector::dot(), CLHEP::HepLorentzVector::getT(), HepLorentzRotation(), mtt, mtx, mty, mtz, mxt, mxx, mxy, mxz, myt, myx, myy, myz, mzt, mzx, mzy, mzz, norm, CLHEP::HepLorentzVector::setMetric(), CLHEP::HepLorentzVector::t(), CLHEP::T_HAT4, CLHEP::TimePositive, CLHEP::HepLorentzVector::x(), CLHEP::X_HAT4, CLHEP::HepLorentzVector::y(), CLHEP::Y_HAT4, CLHEP::HepLorentzVector::z(), and CLHEP::Z_HAT4.
HepLorentzRotation& CLHEP::HepLorentzRotation::set (const HepRep4x4 & rep) inline
void CLHEP::HepLorentzRotation::setBoost (double , double , double) inline protected
HepLorentzRotation & CLHEP::HepLorentzRotation::setRows (const HepLorentzVector & row1, const HepLorentzVector & row2, const HepLorentzVector & row3, const HepLorentzVector & row4)
Definition at line 181 of file LorentzRotationC.cc.
View newest version in sPHENIX GitHub at line 181 of file LorentzRotationC.cc
static double CLHEP::HepLorentzRotation::setTolerance (double tol) inline static
HepLorentzRotation& CLHEP::HepLorentzRotation::transform (const HepBoost & b) inline
Referenced by G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), and G4QGSDiffractiveExcitation::ExciteParticipants().
HepLorentzRotation& CLHEP::HepLorentzRotation::transform (const HepRotation & r) inline
HepLorentzRotation& CLHEP::HepLorentzRotation::transform (const HepLorentzRotation & lt) inline
double CLHEP::HepLorentzRotation::tt () const inline
Referenced by operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::tx () const inline
Referenced by operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::ty () const inline
Referenced by operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::tz () const inline
Referenced by operator()(), CLHEP::operator*(), print(), and rectify().
HepLorentzVector CLHEP::HepLorentzRotation::vectorMultiplication (const HepLorentzVector &) const inline
Referenced by CLHEP::HepLorentzVector::operator*=(), and CLHEP::HepLorentzVector::transform().
double CLHEP::HepLorentzRotation::xt () const inline
Referenced by operator()(), CLHEP::operator*(), and print().
double CLHEP::HepLorentzRotation::xx () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::xy () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::xz () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::yt () const inline
Referenced by operator()(), CLHEP::operator*(), and print().
double CLHEP::HepLorentzRotation::yx () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::yy () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::yz () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::zt () const inline
Referenced by operator()(), CLHEP::operator*(), and print().
double CLHEP::HepLorentzRotation::zx () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::zy () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
double CLHEP::HepLorentzRotation::zz () const inline
Referenced by decompose(), operator()(), CLHEP::operator*(), print(), and rectify().
Friends And Related Function Documentation
HepLorentzRotation inverseOf (const HepLorentzRotation & lt) friend
Member Data Documentation
const HepLorentzRotation CLHEP::HepLorentzRotation::IDENTITY static
Definition at line 57 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 57 of file LorentzRotation.h
Referenced by PHHepMCGenEvent::get_LorentzRotation_EvtGen2Lab(), and PHHepMCGenEvent::get_LorentzRotation_Lab2EvtGen().
double CLHEP::HepLorentzRotation::mtt protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), boostY(), boostZ(), compare(), matrixMultiplication(), and set().
double CLHEP::HepLorentzRotation::mtx protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), boostY(), boostZ(), compare(), matrixMultiplication(), and set().
double CLHEP::HepLorentzRotation::mty protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), boostY(), boostZ(), compare(), matrixMultiplication(), and set().
double CLHEP::HepLorentzRotation::mtz protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), boostY(), boostZ(), compare(), matrixMultiplication(), and set().
double CLHEP::HepLorentzRotation::mxt protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), compare(), matrixMultiplication(), rotateY(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::mxx protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), compare(), matrixMultiplication(), rotateY(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::mxy protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), compare(), matrixMultiplication(), rotateY(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::mxz protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostX(), compare(), matrixMultiplication(), rotateY(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::myt protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostY(), compare(), matrixMultiplication(), rotateX(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::myx protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostY(), compare(), matrixMultiplication(), rotateX(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::myy protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostY(), compare(), matrixMultiplication(), rotateX(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::myz protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostY(), compare(), matrixMultiplication(), rotateX(), rotateZ(), and set().
double CLHEP::HepLorentzRotation::mzt protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostZ(), compare(), matrixMultiplication(), rotateX(), rotateY(), and set().
double CLHEP::HepLorentzRotation::mzx protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostZ(), compare(), matrixMultiplication(), rotateX(), rotateY(), and set().
double CLHEP::HepLorentzRotation::mzy protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostZ(), compare(), matrixMultiplication(), rotateX(), rotateY(), and set().
double CLHEP::HepLorentzRotation::mzz protected
Definition at line 340 of file LorentzRotation.h.
View newest version in sPHENIX GitHub at line 340 of file LorentzRotation.h
Referenced by boostZ(), compare(), matrixMultiplication(), rotateX(), rotateY(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/LorentzRotation.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzRotation.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzRotationC.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzRotationD.cc