ECCE @ EIC Software: G3toG4RotationMatrix Class Reference
G3toG4RotationMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3toG4RotationMatrix.hh>
Public Member Functions
G3toG4RotationMatrix ()
void SetRotationMatrixByCol (const G4ThreeVector &Col1, const G4ThreeVector &Col2, const G4ThreeVector &Col3)
void SetRotationMatrixByRow (const G4ThreeVector &Row1, const G4ThreeVector &Row2, const G4ThreeVector &Row3)
~G3toG4RotationMatrix ()
Public Member Functions inherited from CLHEP::HepRotation
HepRotation ()
HepRotation (const HepRotation &m)
HepRotation (HepRotation &&m)=default
HepRotation (const HepRotationX &m)
HepRotation (const HepRotationY &m)
HepRotation (const HepRotationZ &m)
HepRotation & set (const Hep3Vector &axis, double delta)
HepRotation (const Hep3Vector &axis, double delta)
HepRotation & set (const HepAxisAngle &ax)
HepRotation (const HepAxisAngle &ax)
HepRotation & set (double phi, double theta, double psi)
HepRotation (double phi, double theta, double psi)
HepRotation & set (const HepEulerAngles &e)
HepRotation (const HepEulerAngles &e)
HepRotation (const Hep3Vector &colX, const Hep3Vector &colY, const Hep3Vector &colZ)
HepRotation & set (const Hep3Vector &colX, const Hep3Vector &colY, const Hep3Vector &colZ)
HepRotation & setRows (const Hep3Vector &rowX, const Hep3Vector &rowY, const Hep3Vector &rowZ)
HepRotation & set (const HepRotationX &r)
HepRotation & set (const HepRotationY &r)
HepRotation & set (const HepRotationZ &r)
HepRotation & operator= (const HepRotation &r)
HepRotation & operator= (HepRotation &&r)=default
HepRotation & operator= (const HepRotationX &r)
HepRotation & operator= (const HepRotationY &r)
HepRotation & operator= (const HepRotationZ &r)
HepRotation & set (const HepRep3x3 &m)
HepRotation (const HepRep3x3 &m)
~HepRotation ()
Hep3Vector colX () const
Hep3Vector colY () const
Hep3Vector colZ () const
Hep3Vector rowX () const
Hep3Vector rowY () const
Hep3Vector rowZ () const
double xx () const
double xy () const
double xz () const
double yx () const
double yy () const
double yz () const
double zx () const
double zy () const
double zz () const
HepRep3x3 rep3x3 () const
const HepRotation_row operator[] (int) const
double operator() (int, int) const
double getPhi () const
double getTheta () const
double getPsi () const
double phi () const
double theta () const
double psi () const
HepEulerAngles eulerAngles () const
double getDelta () const
Hep3Vector getAxis () const
double delta () const
Hep3Vector axis () const
HepAxisAngle axisAngle () const
void getAngleAxis (double &delta, Hep3Vector &axis) const
double phiX () const
double phiY () const
double phiZ () const
double thetaX () const
double thetaY () const
double thetaZ () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
double xt () const
double yt () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepRep4x4 rep4x4 () const
void setPhi (double phi)
void setTheta (double theta)
void setPsi (double psi)
void setAxis (const Hep3Vector &axis)
void setDelta (double delta)
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
bool isIdentity () const
int compare (const HepRotation &r) const
bool operator== (const HepRotation &r) const
bool operator!= (const HepRotation &r) const
bool operator< (const HepRotation &r) const
bool operator> (const HepRotation &r) const
bool operator<= (const HepRotation &r) const
bool operator>= (const HepRotation &r) const
double distance2 (const HepRotation &r) const
double howNear (const HepRotation &r) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
double distance2 (const HepBoost &lt) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &lt) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoost &lt, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
Hep3Vector operator() (const Hep3Vector &p) const
Hep3Vector operator* (const Hep3Vector &p) const
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepRotation operator* (const HepRotation &r) const
HepRotation operator* (const HepRotationX &rx) const
HepRotation operator* (const HepRotationY &ry) const
HepRotation operator* (const HepRotationZ &rz) const
HepRotation & operator*= (const HepRotation &r)
HepRotation & transform (const HepRotation &r)
HepRotation & operator*= (const HepRotationX &r)
HepRotation & operator*= (const HepRotationY &r)
HepRotation & operator*= (const HepRotationZ &r)
HepRotation & transform (const HepRotationX &r)
HepRotation & transform (const HepRotationY &r)
HepRotation & transform (const HepRotationZ &r)
HepRotation & rotateX (double delta)
HepRotation & rotateY (double delta)
HepRotation & rotateZ (double delta)
HepRotation & rotate (double delta, const Hep3Vector &axis)
HepRotation & rotate (double delta, const Hep3Vector *axis)
HepRotation & rotateAxes (const Hep3Vector &newX, const Hep3Vector &newY, const Hep3Vector &newZ)
HepRotation inverse () const
HepRotation & invert ()
std::ostream & print (std::ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from CLHEP::HepRotation
static double getTolerance ()
static double setTolerance (double tol)
Static Public Attributes inherited from CLHEP::HepRotation
static DLL_API const HepRotation IDENTITY
Protected Member Functions inherited from CLHEP::HepRotation
HepRotation (double mxx, double mxy, double mxz, double myx, double myy, double myz, double mzx, double mzy, double mzz)
Protected Attributes inherited from CLHEP::HepRotation
double rxx
double rxy
double rxz
double ryx
double ryy
double ryz
double rzx
double rzy
double rzz
Detailed Description
Definition at line 46 of file G3toG4RotationMatrix.hh.
View newest version in sPHENIX GitHub at line 46 of file G3toG4RotationMatrix.hh
Constructor & Destructor Documentation
G3toG4RotationMatrix::G3toG4RotationMatrix ()
Definition at line 30 of file G3toG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 30 of file G3toG4RotationMatrix.cc
References CLHEP::HepRotation::rxx, CLHEP::HepRotation::rxy, CLHEP::HepRotation::rxz, CLHEP::HepRotation::ryx, CLHEP::HepRotation::ryy, CLHEP::HepRotation::ryz, CLHEP::HepRotation::rzx, CLHEP::HepRotation::rzy, and CLHEP::HepRotation::rzz.
G3toG4RotationMatrix::~G3toG4RotationMatrix ()
Definition at line 43 of file G3toG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 43 of file G3toG4RotationMatrix.cc
Member Function Documentation
void G3toG4RotationMatrix::SetRotationMatrixByCol (const G4ThreeVector & Col1, const G4ThreeVector & Col2, const G4ThreeVector & Col3)
Definition at line 49 of file G3toG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 49 of file G3toG4RotationMatrix.cc
References CLHEP::HepRotation::rxx, CLHEP::HepRotation::rxy, CLHEP::HepRotation::rxz, CLHEP::HepRotation::ryx, CLHEP::HepRotation::ryy, CLHEP::HepRotation::ryz, CLHEP::HepRotation::rzx, CLHEP::HepRotation::rzy, CLHEP::HepRotation::rzz, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G3toG4RotationMatrix::SetRotationMatrixByRow (const G4ThreeVector & Row1, const G4ThreeVector & Row2, const G4ThreeVector & Row3)
Definition at line 68 of file G3toG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 68 of file G3toG4RotationMatrix.cc
References CLHEP::HepRotation::rxx, CLHEP::HepRotation::rxy, CLHEP::HepRotation::rxz, CLHEP::HepRotation::ryx, CLHEP::HepRotation::ryy, CLHEP::HepRotation::ryz, CLHEP::HepRotation::rzx, CLHEP::HepRotation::rzy, CLHEP::HepRotation::rzz, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4gsrotm().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3toG4RotationMatrix.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3toG4RotationMatrix.cc