ECCE @ EIC Software: G4ParticleHPKallbachMannSyst Class Reference
G4ParticleHPKallbachMannSyst Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPKallbachMannSyst.hh>
Public Member Functions
G4ParticleHPKallbachMannSyst (G4double aCompoundFraction, G4double anIncidentEnergy, G4double anIncidentMass, G4double aProductEnergy, G4double aProductMass, G4double aResidualMass, G4int aResidualA, G4int aResidualZ, G4double aTargetMass, G4int aTargetA, G4int aTargetZ, G4int aProjectileA, G4int aProjectileZ, G4int aProductA, G4int aProductZ)
~G4ParticleHPKallbachMannSyst ()
G4double Sample (G4double anEnergy)
G4double Kallbach (G4double cosTh, G4double anEnergy)
G4double GetKallbachZero (G4double anEnergy)
G4double A (G4double anEnergy)
G4double SeparationEnergy (G4int Ac, G4int Nc, G4int AA, G4int ZA, G4int Abinding, G4int Zbinding)
Private Attributes
G4double theCompoundFraction
G4double theIncidentEnergy
G4double theIncidentMass
G4double theProductEnergy
G4double theProductMass
G4double theResidualMass
G4double theTargetMass
G4int theResidualA
G4int theResidualZ
G4int theTargetA
G4int theTargetZ
G4int theProjectileA
G4int theProjectileZ
G4int theProductA
G4int theProductZ
Detailed Description
Definition at line 36 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPKallbachMannSyst.hh
Constructor & Destructor Documentation
G4ParticleHPKallbachMannSyst::G4ParticleHPKallbachMannSyst (G4double aCompoundFraction, G4double anIncidentEnergy, G4double anIncidentMass, G4double aProductEnergy, G4double aProductMass, G4double aResidualMass, G4int aResidualA, G4int aResidualZ, G4double aTargetMass, G4int aTargetA, G4int aTargetZ, G4int aProjectileA, G4int aProjectileZ, G4int aProductA, G4int aProductZ) inline
Definition at line 40 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPKallbachMannSyst.hh
References theCompoundFraction, theIncidentEnergy, theIncidentMass, theProductA, theProductEnergy, theProductMass, theProductZ, theProjectileA, theProjectileZ, theResidualA, theResidualMass, theResidualZ, theTargetA, theTargetMass, and theTargetZ.
G4ParticleHPKallbachMannSyst::~G4ParticleHPKallbachMannSyst () inline
Definition at line 64 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPKallbachMannSyst.hh
Member Function Documentation
G4double G4ParticleHPKallbachMannSyst::A (G4double anEnergy)
Definition at line 100 of file G4ParticleHPKallbachMannSyst.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPKallbachMannSyst.cc
References C1, C2, C3, G4Pow::GetInstance(), MeV, min, G4Pow::powN(), SeparationEnergy(), theIncidentMass, theProductA, theProductEnergy, theProductMass, theProductZ, theProjectileA, theProjectileZ, theResidualA, theResidualMass, theResidualZ, theTargetA, theTargetMass, theTargetZ, and X1.
Referenced by GetKallbachZero(), and Kallbach().
G4double G4ParticleHPKallbachMannSyst::GetKallbachZero (G4double anEnergy)
Definition at line 86 of file G4ParticleHPKallbachMannSyst.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPKallbachMannSyst.cc
References A(), kdfinder::abs(), Acts::Test::delta, G4Log(), and theCompoundFraction.
Referenced by Sample().
G4double G4ParticleHPKallbachMannSyst::Kallbach (G4double cosTh, G4double anEnergy)
Definition at line 76 of file G4ParticleHPKallbachMannSyst.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPKallbachMannSyst.cc
References A(), G4Exp(), and theCompoundFraction.
Referenced by Sample().
G4double G4ParticleHPKallbachMannSyst::Sample (G4double anEnergy)
Definition at line 44 of file G4ParticleHPKallbachMannSyst.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPKallbachMannSyst.cc
References G4cout, G4endl, G4UniformRand, GetKallbachZero(), Kallbach(), max, and zero.
Referenced by G4ParticleHPContAngularPar::Sample().
G4double G4ParticleHPKallbachMannSyst::SeparationEnergy (G4int Ac, G4int Nc, G4int AA, G4int ZA, G4int Abinding, G4int Zbinding)
Definition at line 143 of file G4ParticleHPKallbachMannSyst.cc.
View newest version in sPHENIX GitHub at line 143 of file G4ParticleHPKallbachMannSyst.cc
References G4Pow::A13(), G4Pow::A23(), G4Pow::GetInstance(), MeV, G4Pow::powA(), and Zc.
Referenced by A().
Member Data Documentation
G4double G4ParticleHPKallbachMannSyst::theCompoundFraction private
Definition at line 78 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPKallbachMannSyst.hh
Referenced by G4ParticleHPKallbachMannSyst(), GetKallbachZero(), and Kallbach().
G4double G4ParticleHPKallbachMannSyst::theIncidentEnergy private
Definition at line 79 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPKallbachMannSyst.hh
Referenced by G4ParticleHPKallbachMannSyst().
G4double G4ParticleHPKallbachMannSyst::theIncidentMass private
Definition at line 80 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theProductA private
Definition at line 91 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4double G4ParticleHPKallbachMannSyst::theProductEnergy private
Definition at line 81 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4double G4ParticleHPKallbachMannSyst::theProductMass private
Definition at line 82 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theProductZ private
Definition at line 92 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theProjectileA private
Definition at line 89 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theProjectileZ private
Definition at line 90 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theResidualA private
Definition at line 85 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4double G4ParticleHPKallbachMannSyst::theResidualMass private
Definition at line 83 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theResidualZ private
Definition at line 86 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theTargetA private
Definition at line 87 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4double G4ParticleHPKallbachMannSyst::theTargetMass private
Definition at line 84 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
G4int G4ParticleHPKallbachMannSyst::theTargetZ private
Definition at line 88 of file G4ParticleHPKallbachMannSyst.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPKallbachMannSyst.hh
Referenced by A(), and G4ParticleHPKallbachMannSyst().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPKallbachMannSyst.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPKallbachMannSyst.cc