ECCE @ EIC Software: G4Ions Class Reference
G4Ions Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4Ions.hh>
Public Types
enum G4FloatLevelBase
Public Member Functions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Static Public Member Functions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions
G4Ions ()
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Private Attributes
G4double theExcitationEnergy
G4int theIsomerLevel
G4FloatLevelBase floatLevelBase
Additional Inherited Members
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 50 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 50 of file G4Ions.hh
Member Enumeration Documentation
enum G4Ions::G4FloatLevelBase
Definition at line 94 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 94 of file G4Ions.hh
Constructor & Destructor Documentation
G4Ions::G4Ions () inline protected
Definition at line 61 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 61 of file G4Ions.hh
Referenced by G4Neutron::Definition(), G4Triton::Definition(), G4He3::Definition(), G4Proton::Definition(), G4AntiAlpha::Definition(), G4AntiTriton::Definition(), G4AntiHe3::Definition(), G4AntiDeuteron::Definition(), G4Deuteron::Definition(), G4Alpha::Definition(), and G4GenericIon::Definition().
G4Ions::G4Ions (const G4String & aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String & pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable * decaytable, G4bool shortlived, const G4String & subType = "", G4int anti_encoding = 0, G4double excitation = 0.0, G4int isomer = 0)
Definition at line 47 of file G4Ions.cc.
View newest version in sPHENIX GitHub at line 47 of file G4Ions.cc
References kdfinder::abs(), eplus, false, G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::isGeneralIon, G4ParticleDefinition::SetAtomicMass(), G4ParticleDefinition::SetAtomicNumber(), and theExcitationEnergy.
G4Ions::~G4Ions () virtual
Definition at line 98 of file G4Ions.cc.
View newest version in sPHENIX GitHub at line 98 of file G4Ions.cc
Member Function Documentation
G4Ions::G4FloatLevelBase G4Ions::FloatLevelBase (char flbChar) inline static
Definition at line 188 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Ions.hh
References noFloat, plusA, plusB, plusC, plusD, plusE, plusR, plusS, plusT, plusU, plusV, plusW, plusX, plusY, and plusZ.
Referenced by G4ExcitationHandler::BreakItUp(), G4ITDecay::DecayIt(), G4IonTable::FindIon(), G4IonTable::GetIon(), G4IonTable::GetLifeTime(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4IsotopeProperty::SetFloatLevelBase(), SetFloatLevelBase(), and G4NuclideTable::StripFloatLevelBase().
G4Ions::G4FloatLevelBase G4Ions::FloatLevelBase (G4int flbIdx) inline static
Definition at line 242 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 242 of file G4Ions.hh
References noFloat, plusA, plusB, plusC, plusD, plusE, plusR, plusS, plusT, plusU, plusV, plusW, plusX, plusY, and plusZ.
char G4Ions::FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb) inline static
Definition at line 252 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 252 of file G4Ions.hh
Referenced by G4IonTable::CreateIon(), G4IsotopeProperty::DumpInfo(), and G4IonTable::GetIonName().
G4double G4Ions::GetExcitationEnergy () const inline
Definition at line 146 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 146 of file G4Ions.hh
References theExcitationEnergy.
G4Ions::G4FloatLevelBase G4Ions::GetFloatLevelBase () const inline
Definition at line 158 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 158 of file G4Ions.hh
References floatLevelBase.
G4int G4Ions::GetFloatLevelBaseIndex () const inline
Definition at line 164 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 164 of file G4Ions.hh
References floatLevelBase.
G4int G4Ions::GetIsomerLevel () const inline
Definition at line 152 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 152 of file G4Ions.hh
References theIsomerLevel.
G4Ions * G4Ions::Ions () inline
Definition at line 140 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 140 of file G4Ions.hh
G4Ions * G4Ions::IonsDefinition () inline
Definition at line 134 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 134 of file G4Ions.hh
void G4Ions::SetFloatLevelBase (G4Ions::G4FloatLevelBase flb) inline
Definition at line 170 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 170 of file G4Ions.hh
References floatLevelBase.
Referenced by G4MuonicAtom::G4MuonicAtom().
void G4Ions::SetFloatLevelBase (char flbChar) inline
Definition at line 176 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 176 of file G4Ions.hh
References FloatLevelBase(), and floatLevelBase.
void G4Ions::SetFloatLevelBase (G4int flbIdx) inline
Definition at line 182 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Ions.hh
References FloatLevelBase(), and floatLevelBase.
Member Data Documentation
G4FloatLevelBase G4Ions::floatLevelBase private
Definition at line 113 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 113 of file G4Ions.hh
Referenced by GetFloatLevelBase(), GetFloatLevelBaseIndex(), and SetFloatLevelBase().
G4double G4Ions::theExcitationEnergy private
Definition at line 111 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Ions.hh
Referenced by G4Ions(), and GetExcitationEnergy().
G4int G4Ions::theIsomerLevel private
Definition at line 112 of file G4Ions.hh.
View newest version in sPHENIX GitHub at line 112 of file G4Ions.hh
Referenced by GetIsomerLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4Ions.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4Ions.cc