ECCE @ EIC Software: G4NeutronField Class Reference
G4NeutronField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4NeutronField.hh>
Public Member Functions
G4NeutronField (G4V3DNucleus *nucleus)
virtual ~G4NeutronField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
virtual G4double GetCoeff ()
Private Member Functions
G4NeutronField (const G4NeutronField &right)
const G4NeutronField & operator= (const G4NeutronField &right)
G4bool operator== (const G4NeutronField &right) const
G4bool operator!= (const G4NeutronField &right) const
G4double GetDensity (const G4ThreeVector &aPosition)
G4double GetFermiMomentum (const G4double aDensity)
Private Attributes
G4FermiMomentum theFermi
G4int theA
G4int theZ
const G4VNuclearDensity * theDensity
G4double theR
std::vector< G4double > theFermiMomBuffer
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 48 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 48 of file G4NeutronField.hh
Constructor & Destructor Documentation
G4NeutronField::G4NeutronField (G4V3DNucleus * nucleus)
Definition at line 45 of file G4NeutronField.cc.
View newest version in sPHENIX GitHub at line 45 of file G4NeutronField.cc
References fermi, G4V3DNucleus::GetCharge(), GetDensity(), GetFermiMomentum(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetOuterRadius(), G4FermiMomentum::Init(), m, theA, theFermi, theFermiMomBuffer, G4VNuclearField::theNucleus, theR, and theZ.
G4NeutronField::~G4NeutronField () virtual
Definition at line 75 of file G4NeutronField.cc.
View newest version in sPHENIX GitHub at line 75 of file G4NeutronField.cc
G4NeutronField::G4NeutronField (const G4NeutronField & right) private
Member Function Documentation
G4double G4NeutronField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 91 of file G4NeutronField.cc.
View newest version in sPHENIX GitHub at line 91 of file G4NeutronField.cc
G4double G4NeutronField::GetDensity (const G4ThreeVector & aPosition) inline private
Definition at line 68 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 68 of file G4NeutronField.hh
References G4VNuclearDensity::GetDensity(), and theDensity.
Referenced by G4NeutronField().
G4double G4NeutronField::GetFermiMomentum (const G4double aDensity) inline private
Definition at line 73 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 73 of file G4NeutronField.hh
References G4FermiMomentum::GetFermiMomentum(), and theFermi.
Referenced by G4NeutronField().
G4double G4NeutronField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 78 of file G4NeutronField.cc.
View newest version in sPHENIX GitHub at line 78 of file G4NeutronField.cc
References fermi, CLHEP::Hep3Vector::mag(), source.hepunit::neutron_mass_c2, theFermiMomBuffer, x, x1, x2, y1, and y2.
G4bool G4NeutronField::operator!= (const G4NeutronField & right) const private
const G4NeutronField& G4NeutronField::operator= (const G4NeutronField & right) private
G4bool G4NeutronField::operator== (const G4NeutronField & right) const private
Member Data Documentation
G4int G4NeutronField::theA private
Definition at line 79 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 79 of file G4NeutronField.hh
Referenced by G4NeutronField().
const G4VNuclearDensity* G4NeutronField::theDensity private
Definition at line 81 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 81 of file G4NeutronField.hh
Referenced by GetDensity().
G4FermiMomentum G4NeutronField::theFermi private
Definition at line 78 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 78 of file G4NeutronField.hh
Referenced by G4NeutronField(), and GetFermiMomentum().
std::vector<G4double> G4NeutronField::theFermiMomBuffer private
Definition at line 84 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 84 of file G4NeutronField.hh
Referenced by G4NeutronField(), and GetField().
G4double G4NeutronField::theR private
Definition at line 82 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 82 of file G4NeutronField.hh
Referenced by G4NeutronField().
G4int G4NeutronField::theZ private
Definition at line 80 of file G4NeutronField.hh.
View newest version in sPHENIX GitHub at line 80 of file G4NeutronField.hh
Referenced by G4NeutronField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4NeutronField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4NeutronField.cc