ECCE @ EIC Software: G4VSDFilter Class Reference
G4VSDFilter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4VSDFilter.hh>
Public Member Functions
G4VSDFilter (G4String name)
virtual ~G4VSDFilter ()
virtual G4bool Accept (const G4Step *) const =0
G4String GetName () const
Protected Attributes
G4String filterName
Detailed Description
Definition at line 40 of file G4VSDFilter.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VSDFilter.hh
Constructor & Destructor Documentation
G4VSDFilter::G4VSDFilter (G4String name)
Definition at line 32 of file G4VSDFilter.cc.
View newest version in sPHENIX GitHub at line 32 of file G4VSDFilter.cc
References G4SDManager::GetSDMpointer(), and G4SDManager::RegisterSDFilter().
G4VSDFilter::~G4VSDFilter () virtual
Definition at line 38 of file G4VSDFilter.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VSDFilter.cc
References G4SDManager::DeRegisterSDFilter(), and G4SDManager::GetSDMpointer().
Member Function Documentation
virtual G4bool G4VSDFilter::Accept (const G4Step *) const pure virtual
Implemented in G4SDParticleFilter, G4SDKineticEnergyFilter, CexmcTrackPointsFilter, G4SDParticleWithEnergyFilter, G4SDNeutralFilter, and G4SDChargedFilter.
Referenced by G4VSensitiveDetector::Hit(), and G4VPrimitiveScorer::HitPrimitive().
G4String G4VSDFilter::GetName (void) const inline
Definition at line 56 of file G4VSDFilter.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VSDFilter.hh
References filterName.
Referenced by G4VScoringMesh::List(), G4VScoringMesh::SetFilter(), and G4SDKineticEnergyFilter::show().
Member Data Documentation
G4String G4VSDFilter::filterName protected
Definition at line 53 of file G4VSDFilter.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VSDFilter.hh
Referenced by GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4VSDFilter.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4VSDFilter.cc