ECCE @ EIC Software: G4INCL::Cluster Class Reference
G4INCL::Cluster Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCluster.hh>
Public Member Functions
Cluster (const G4int Z, const G4int A, const G4int S, const G4bool createParticleSampler=true)
Standard Cluster constructor.
template<class Iterator >
Cluster (Iterator begin, Iterator end)
virtual ~Cluster ()
Cluster (const Cluster &rhs)
Copy constructor.
Cluster & operator= (const Cluster &rhs)
Assignment operator.
void swap (Cluster &rhs)
Helper method for the assignment operator.
ParticleSpecies getSpecies () const
Get the particle species.
void deleteParticles ()
void clearParticles ()
void setZ (const G4int Z)
Set the charge number of the cluster.
void setA (const G4int A)
Set the mass number of the cluster.
void setS (const G4int S)
Set the strangess number of the cluster.
G4double getExcitationEnergy () const
Get the excitation energy of the cluster.
void setExcitationEnergy (const G4double e)
Set the excitation energy of the cluster.
virtual G4double getTableMass () const
Get the real particle mass.
ParticleList const & getParticles () const
void removeParticle (Particle *const p)
Remove a particle from the cluster components.
void addParticle (Particle *const p)
void updateClusterParameters ()
Set total cluster mass, energy, size, etc. from the particles.
void addParticles (ParticleList const &pL)
Add a list of particles to the cluster.
ParticleList getParticleList () const
Returns the list of particles that make up the cluster.
std::string print () const
virtual void initializeParticles ()
Initialise the NuclearDensity pointer and sample the particles.
void internalBoostToCM ()
Boost to the CM of the component particles.
void putParticlesOffShell ()
Put the cluster components off shell.
void setPosition (const ThreeVector &position)
Set the position of the cluster.
void boost (const ThreeVector &aBoostVector)
Boost the cluster with the indicated velocity.
void freezeInternalMotion ()
Freeze the internal motion of the particles.
virtual void rotatePosition (const G4double angle, const ThreeVector &axis)
Rotate position of all the particles.
virtual void rotateMomentum (const G4double angle, const ThreeVector &axis)
Rotate momentum of all the particles.
virtual void makeProjectileSpectator ()
Make all the components projectile spectators, too.
virtual void makeTargetSpectator ()
Make all the components target spectators, too.
virtual void makeParticipant ()
Make all the components participants, too.
ThreeVector const & getSpin () const
Get the spin of the nucleus.
void setSpin (const ThreeVector &j)
Set the spin of the nucleus.
G4INCL::ThreeVector getAngularMomentum () const
Get the total angular momentum (orbital + spin)
Public Member Functions inherited from G4INCL::Particle
Particle ()
Particle (ParticleType t, G4double energy, ThreeVector const &momentum, ThreeVector const &position)
Particle (ParticleType t, ThreeVector const &momentum, ThreeVector const &position)
virtual ~Particle ()
Particle (const Particle &rhs)
Copy constructor.
Particle & operator= (const Particle &rhs)
Assignment operator.
G4INCL::ParticleType getType () const
void setType (ParticleType t)
G4bool isNucleon () const
ParticipantType getParticipantType () const
void setParticipantType (ParticipantType const p)
G4bool isParticipant () const
G4bool isTargetSpectator () const
G4bool isProjectileSpectator () const
G4bool isPion () const
Is this a pion?
G4bool isEta () const
Is this an eta?
G4bool isOmega () const
Is this an omega?
G4bool isEtaPrime () const
Is this an etaprime?
G4bool isPhoton () const
Is this a photon?
G4bool isResonance () const
Is it a resonance?
G4bool isDelta () const
Is it a Delta?
G4bool isSigma () const
Is this a Sigma?
G4bool isKaon () const
Is this a Kaon?
G4bool isAntiKaon () const
Is this an antiKaon?
G4bool isLambda () const
Is this a Lambda?
G4bool isNucleonorLambda () const
Is this a Nucleon or a Lambda?
G4bool isHyperon () const
Is this an Hyperon?
G4bool isMeson () const
Is this a Meson?
G4bool isBaryon () const
Is this a Baryon?
G4bool isStrange () const
Is this an Strange?
G4int getA () const
Returns the baryon number.
G4int getZ () const
Returns the charge number.
G4int getS () const
Returns the strangeness number.
G4double getBeta () const
ThreeVector boostVector () const
void boost (const ThreeVector &aBoostVector)
void lorentzContract (const ThreeVector &aBoostVector, const ThreeVector &refPos)
Lorentz-contract the particle position around some center.
G4double getMass () const
Get the cached particle mass.
G4double getINCLMass () const
Get the INCL particle mass.
G4double getRealMass () const
Get the real particle mass.
void setRealMass ()
Set the mass of the Particle to its real mass.
void setTableMass ()
Set the mass of the Particle to its table mass.
void setINCLMass ()
Set the mass of the Particle to its table mass.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const
Computes correction on the emission Q-value.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const
Computes correction on the transfer Q-value.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const
Computes correction on the emission Q-value for hypernuclei.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const
Computes correction on the transfer Q-value for hypernuclei.
G4double getInvariantMass () const
Get the the particle invariant mass.
G4double getKineticEnergy () const
Get the particle kinetic energy.
G4double getPotentialEnergy () const
Get the particle potential energy.
void setPotentialEnergy (G4double v)
Set the particle potential energy.
G4double getEnergy () const
void setMass (G4double mass)
void setEnergy (G4double energy)
const G4INCL::ThreeVector & getMomentum () const
virtual void setMomentum (const G4INCL::ThreeVector &momentum)
const G4INCL::ThreeVector & getPosition () const
G4double getHelicity ()
void setHelicity (G4double h)
void propagate (G4double step)
G4int getNumberOfCollisions () const
Return the number of collisions undergone by the particle.
void setNumberOfCollisions (G4int n)
Set the number of collisions undergone by the particle.
void incrementNumberOfCollisions ()
Increment the number of collisions undergone by the particle.
G4int getNumberOfDecays () const
Return the number of decays undergone by the particle.
void setNumberOfDecays (G4int n)
Set the number of decays undergone by the particle.
void incrementNumberOfDecays ()
Increment the number of decays undergone by the particle.
void setOutOfWell ()
Mark the particle as out of its potential well.
G4bool isOutOfWell () const
Check if the particle is out of its potential well.
void setEmissionTime (G4double t)
G4double getEmissionTime ()
ThreeVector getTransversePosition () const
Transverse component of the position w.r.t. the momentum.
ThreeVector getLongitudinalPosition () const
Longitudinal component of the position w.r.t. the momentum.
const ThreeVector & adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
G4double adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
G4bool isCluster () const
void setFrozenMomentum (const ThreeVector &momentum)
Set the frozen particle momentum.
void setFrozenEnergy (const G4double energy)
Set the frozen particle momentum.
ThreeVector getFrozenMomentum () const
Get the frozen particle momentum.
G4double getFrozenEnergy () const
Get the frozen particle momentum.
ThreeVector getPropagationVelocity () const
Get the propagation velocity of the particle.
void freezePropagation ()
Freeze particle propagation.
void thawPropagation ()
Unfreeze particle propagation.
virtual void rotatePositionAndMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle position and momentum.
std::string print () const
std::string dump () const
long getID () const
ParticleList const * getParticles () const
G4double getReflectionMomentum () const
Return the reflection momentum.
void setUncorrelatedMomentum (const G4double p)
Set the uncorrelated momentum.
void rpCorrelate ()
Make the particle follow a strict r-p correlation.
void rpDecorrelate ()
Make the particle not follow a strict r-p correlation.
G4double getCosRPAngle () const
Get the cosine of the angle between position and momentum.
G4double getParticleBias () const
Get the particle bias.
void setParticleBias (G4double ParticleBias)
Set the particle bias.
std::vector< G4int > getBiasCollisionVector () const
Get the vector list of biased vertices on the particle path.
void setBiasCollisionVector (std::vector< G4int > BiasCollisionVector)
Set the vector list of biased vertices on the particle path.
G4int getNumberOfKaon () const
Number of Kaon inside de nucleus.
void setNumberOfKaon (const G4int NK)
Protected Attributes
ParticleList particles
G4double theExcitationEnergy
ThreeVector theSpin
ParticleSampler * theParticleSampler
Protected Attributes inherited from G4INCL::Particle
G4int theZ
G4int theA
G4int theS
ParticipantType theParticipantType
G4INCL::ParticleType theType
G4double theEnergy
G4double * thePropagationEnergy
G4double theFrozenEnergy
G4INCL::ThreeVector theMomentum
G4INCL::ThreeVector * thePropagationMomentum
G4INCL::ThreeVector theFrozenMomentum
G4INCL::ThreeVector thePosition
G4int nCollisions
G4int nDecays
G4double thePotentialEnergy
long ID
G4bool rpCorrelated
G4double uncorrelatedMomentum
G4double theParticleBias
G4int theNKaon
The number of Kaons inside the nucleus (update during the cascade)
Private Member Functions
G4double computeDynamicalPotential ()
Compute the dynamical cluster potential.
Additional Inherited Members
Static Public Member Functions inherited from G4INCL::Particle
static G4double getTotalBias ()
General bias vector function.
static void setINCLBiasVector (std::vector< G4double > NewVector)
static void FillINCLBiasVector (G4double newBias)
static G4double getBiasFromVector (std::vector< G4int > VectorBias)
static std::vector< G4int > MergeVectorBias (Particle const *const p1, Particle const *const p2)
static std::vector< G4int > MergeVectorBias (std::vector< G4int > p1, Particle const *const p2)
Static Public Attributes inherited from G4INCL::Particle
static std::vector< G4double > INCLBiasVector
Time ordered vector of all bias applied.
static G4ThreadLocal G4int nextBiasedCollisionID = 0
Protected Member Functions inherited from G4INCL::Particle
void swap (Particle &rhs)
Helper method for the assignment operator.
Detailed Description
Cluster is a particle (inherits from the Particle class) that is actually a collection of elementary particles.
Definition at line 52 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 52 of file G4INCLCluster.hh
Constructor & Destructor Documentation
G4INCL::Cluster::Cluster (const G4int Z, const G4int A, const G4int S, const G4bool createParticleSampler = true) inline
Standard Cluster constructor.
This constructor should mainly be used when constructing Nucleus or when constructing Clusters to be used as composite projectiles.
Definition at line 60 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLCluster.hh
References A(), G4INCL::Composite, S(), G4INCL::Particle::setINCLMass(), G4INCL::Particle::setType(), G4INCL::Particle::theA, theParticleSampler, G4INCL::Particle::theS, G4INCL::Particle::theZ, and Z.
template<class Iterator > G4INCL::Cluster::Cluster (Iterator begin, Iterator end) inline
A cluster can be directly built from a list of particles.
Definition at line 79 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 79 of file G4INCLCluster.hh
References addParticle(), G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::Composite, G4INCL::Particle::setINCLMass(), G4INCL::Particle::setType(), G4INCL::Particle::theA, and G4INCL::Particle::thePosition.
virtual G4INCL::Cluster::~Cluster () inline virtual
Definition at line 94 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 94 of file G4INCLCluster.hh
References theParticleSampler.
G4INCL::Cluster::Cluster (const Cluster & rhs) inline
Copy constructor.
Definition at line 99 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 99 of file G4INCLCluster.hh
References e, G4INCL::Particle::Particle(), particles, G4INCL::Particle::theA, theParticleSampler, and G4INCL::Particle::theZ.
Member Function Documentation
void G4INCL::Cluster::addParticle (Particle *const p) inline
Add one particle to the cluster. This updates the cluster mass, energy, size, etc.
Definition at line 178 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 178 of file G4INCLCluster.hh
References G4INCL::Particle::getA(), G4INCL::Particle::getEnergy(), G4INCL::Particle::getMomentum(), G4INCL::Particle::getNumberOfCollisions(), G4INCL::Particle::getPosition(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getS(), G4INCL::Particle::getZ(), G4INCL::Particle::nCollisions, particles, G4INCL::Particle::theA, G4INCL::Particle::theEnergy, G4INCL::Particle::theMomentum, G4INCL::Particle::thePosition, G4INCL::Particle::thePotentialEnergy, G4INCL::Particle::theS, and G4INCL::Particle::theZ.
Referenced by Cluster(), and G4INCL::ProjectileRemnant::reset().
void G4INCL::Cluster::addParticles (ParticleList const & pL) inline
Add a list of particles to the cluster.
Definition at line 213 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 213 of file G4INCLCluster.hh
References particles, and updateClusterParameters().
void G4INCL::Cluster::boost (const ThreeVector & aBoostVector) inline
Boost the cluster with the indicated velocity.
The Cluster is boosted as a whole, just like any Particle object; moreover, the internal components (particles list) are also boosted, according to Alain Boudard's off-shell recipe.
Parameters
aBoostVector the velocity to boost to [c]
Definition at line 344 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 344 of file G4INCLCluster.hh
References G4INCL::Particle::boost(), e, G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), INCL_DEBUG, particles, print(), and G4INCL::Particle::thePosition.
Referenced by G4INCL::ProjectileRemnant::ProjectileRemnant(), and G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor().
void G4INCL::Cluster::clearParticles () inline
Definition at line 143 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 143 of file G4INCLCluster.hh
References particles.
Referenced by deleteParticles().
G4double G4INCL::Cluster::computeDynamicalPotential () inline private
Compute the dynamical cluster potential.
Alain Boudard's boost prescription for low-energy beams requires to define a "dynamical potential" that allows us to conserve momentum and energy when boosting the projectile cluster.
Definition at line 439 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 439 of file G4INCLCluster.hh
References e, getTableMass(), particles, and G4INCL::Particle::theA.
Referenced by putParticlesOffShell().
void G4INCL::Cluster::deleteParticles () inline
Definition at line 136 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 136 of file G4INCLCluster.hh
References clearParticles(), e, and particles.
Referenced by G4INCL::Store::clearOutgoing(), G4INCL::Nucleus::decayOutgoingClusters(), G4INCL::ProjectileRemnant::reset(), and G4INCL::ProjectileRemnant::~ProjectileRemnant().
void G4INCL::Cluster::freezeInternalMotion () inline
Freeze the internal motion of the particles.
Each particle is assigned a frozen momentum four-vector determined by the collective cluster velocity. This is used for propagation, but not for dynamics. Normal propagation is restored by calling the Particle::thawPropagation() method, which should be done in InteractionAvatar::postInteraction.
Definition at line 367 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 367 of file G4INCLCluster.hh
References e, G4INCL::Particle::getMass(), G4INCL::ThreeVector::mag2(), particles, and G4INCL::Particle::theMomentum.
Referenced by G4INCL::ProjectileRemnant::ProjectileRemnant().
G4INCL::ThreeVector G4INCL::Cluster::getAngularMomentum () const inline virtual
Get the total angular momentum (orbital + spin)
Reimplemented from G4INCL::Particle.
Definition at line 428 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 428 of file G4INCLCluster.hh
References G4INCL::Particle::getAngularMomentum(), and getSpin().
Referenced by G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::INCL::makeCompoundNucleus(), and G4INCL::StandardPropagationModel::shootComposite().
G4double G4INCL::Cluster::getExcitationEnergy () const inline
Get the excitation energy of the cluster.
Definition at line 155 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 155 of file G4INCLCluster.hh
References theExcitationEnergy.
Referenced by G4INCL::Nucleus::fillEventInfo(), and G4INCL::Nucleus::getConservationBalance().
ParticleList G4INCL::Cluster::getParticleList () const inline
Returns the list of particles that make up the cluster.
Definition at line 219 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 219 of file G4INCLCluster.hh
References particles.
ParticleList const& G4INCL::Cluster::getParticles () const inline
Get the list of particles in the cluster.
Definition at line 169 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 169 of file G4INCLCluster.hh
References particles.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::CoulombNone::bringToSurface(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::makeProjectileRemnant(), G4INCL::INCL::postCascade(), and G4INCL::SurfaceAvatar::postInteraction().
ParticleSpecies G4INCL::Cluster::getSpecies () const inline virtual
Get the particle species.
Reimplemented from G4INCL::Particle.
Definition at line 132 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 132 of file G4INCLCluster.hh
References G4INCL::Particle::theA, G4INCL::Particle::theS, and G4INCL::Particle::theZ.
ThreeVector const& G4INCL::Cluster::getSpin () const inline
Get the spin of the nucleus.
Definition at line 422 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 422 of file G4INCLCluster.hh
References theSpin.
Referenced by G4INCL::Nucleus::fillEventInfo(), and getAngularMomentum().
virtual G4double G4INCL::Cluster::getTableMass () const inline virtual
Get the real particle mass.
Overloads the Particle method.
Reimplemented from G4INCL::Particle.
Definition at line 164 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 164 of file G4INCLCluster.hh
References G4INCL::Particle::getRealMass().
Referenced by computeDynamicalPotential(), G4INCL::CoulombNonRelativistic::minimumDistance(), and G4INCL::Nucleus::useFusionKinematics().
void G4INCL::Cluster::initializeParticles () virtual
Initialise the NuclearDensity pointer and sample the particles.
Reimplemented in G4INCL::Nucleus.
Definition at line 43 of file G4INCLCluster.cc.
View newest version in sPHENIX GitHub at line 43 of file G4INCLCluster.cc
References INCL_DEBUG, particles, print(), G4INCL::ParticleSampler::sampleParticlesIntoList(), G4INCL::Particle::theA, theParticleSampler, G4INCL::Particle::thePosition, G4INCL::Particle::theZ, and updateClusterParameters().
Referenced by G4INCL::Nucleus::initializeParticles(), and G4INCL::ProjectileRemnant::ProjectileRemnant().
void G4INCL::Cluster::internalBoostToCM () inline
Boost to the CM of the component particles.
The position of all particles in the particles list is shifted so that their centre of mass is in the origin and their total momentum is zero.
Definition at line 254 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 254 of file G4INCLCluster.hh
References e, G4INCL::Particle::getMass(), INCL_DEBUG, particles, print(), G4INCL::ThreeVector::setX(), G4INCL::ThreeVector::setY(), G4INCL::ThreeVector::setZ(), G4INCL::Particle::theA, G4INCL::Particle::theEnergy, G4INCL::Particle::theMomentum, and G4INCL::Particle::thePosition.
Referenced by G4INCL::ProjectileRemnant::ProjectileRemnant().
virtual void G4INCL::Cluster::makeParticipant () inline virtual
Make all the components participants, too.
Reimplemented from G4INCL::Particle.
Definition at line 414 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 414 of file G4INCLCluster.hh
References e, G4INCL::Particle::makeParticipant(), and particles.
virtual void G4INCL::Cluster::makeProjectileSpectator () inline virtual
Make all the components projectile spectators, too.
Reimplemented from G4INCL::Particle.
Definition at line 398 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 398 of file G4INCLCluster.hh
References e, G4INCL::Particle::makeProjectileSpectator(), and particles.
Referenced by G4INCL::ProjectileRemnant::ProjectileRemnant().
virtual void G4INCL::Cluster::makeTargetSpectator () inline virtual
Make all the components target spectators, too.
Reimplemented from G4INCL::Particle.
Definition at line 406 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 406 of file G4INCLCluster.hh
References e, G4INCL::Particle::makeTargetSpectator(), and particles.
Cluster& G4INCL::Cluster::operator= (const Cluster & rhs) inline
Assignment operator.
Definition at line 114 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 114 of file G4INCLCluster.hh
References G4INCL::Particle::operator=(), and swap().
std::string G4INCL::Cluster::print () const inline
Definition at line 221 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 221 of file G4INCLCluster.hh
References e, G4INCL::Particle::getMass(), G4INCL::ParticleTable::getName(), G4INCL::Particle::ID, particles, G4INCL::ThreeVector::print(), G4INCL::Particle::theA, G4INCL::Particle::theEnergy, G4INCL::Particle::theMomentum, G4INCL::Particle::thePosition, G4INCL::Particle::theS, G4INCL::Particle::theType, and G4INCL::Particle::theZ.
Referenced by boost(), G4INCL::SurfaceAvatar::getChannel(), initializeParticles(), internalBoostToCM(), putParticlesOffShell(), G4INCL::ProjectileRemnant::removeParticle(), and G4INCL::ProjectileRemnant::reset().
void G4INCL::Cluster::putParticlesOffShell () inline
Put the cluster components off shell.
The Cluster components are put off shell in such a way that their total energy equals the cluster mass.
Definition at line 306 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 306 of file G4INCLCluster.hh
References computeDynamicalPotential(), e, energy, INCL_DEBUG, G4INCL::ThreeVector::mag2(), momentum, particles, and print().
Referenced by G4INCL::ProjectileRemnant::ProjectileRemnant().
void G4INCL::Cluster::removeParticle (Particle *const p) inline
Remove a particle from the cluster components.
Definition at line 172 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 172 of file G4INCLCluster.hh
References particles, and G4INCL::UnorderedVector< T >::remove().
Referenced by G4INCL::ProjectileRemnant::removeParticle().
void G4INCL::Cluster::rotateMomentum (const G4double angle, const ThreeVector & axis) virtual
Rotate momentum of all the particles.
This includes the cluster components. Overloads Particle::rotateMomentum().
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Reimplemented from G4INCL::Particle.
Definition at line 64 of file G4INCLCluster.cc.
View newest version in sPHENIX GitHub at line 64 of file G4INCLCluster.cc
References e, particles, and G4INCL::Particle::rotateMomentum().
void G4INCL::Cluster::rotatePosition (const G4double angle, const ThreeVector & axis) virtual
Rotate position of all the particles.
This includes the cluster components. Overloads Particle::rotateMomentum().
Parameters
angle the rotation angle
axis a unit vector representing the rotation axis
Reimplemented from G4INCL::Particle.
Definition at line 57 of file G4INCLCluster.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLCluster.cc
References e, particles, and G4INCL::Particle::rotatePosition().
void G4INCL::Cluster::setA (const G4int A) inline
Set the mass number of the cluster.
Definition at line 149 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 149 of file G4INCLCluster.hh
References A(), and G4INCL::Particle::theA.
Referenced by G4INCL::INCL::makeCompoundNucleus().
void G4INCL::Cluster::setExcitationEnergy (const G4double e) inline
Set the excitation energy of the cluster.
Definition at line 158 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 158 of file G4INCLCluster.hh
References e, and theExcitationEnergy.
Referenced by G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
void G4INCL::Cluster::setPosition (const ThreeVector & position) inline virtual
Set the position of the cluster.
This overloads the Particle method to take into account that the positions of the cluster members must be updated as well.
Reimplemented from G4INCL::Particle.
Definition at line 328 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 328 of file G4INCLCluster.hh
References e, particles, G4INCL::Particle::setPosition(), and G4INCL::Particle::thePosition.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
void G4INCL::Cluster::setS (const G4int S) inline
Set the strangess number of the cluster.
Definition at line 152 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 152 of file G4INCLCluster.hh
References S(), and G4INCL::Particle::theS.
Referenced by G4INCL::INCL::makeCompoundNucleus().
void G4INCL::Cluster::setSpin (const ThreeVector & j) inline
Set the spin of the nucleus.
Definition at line 425 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 425 of file G4INCLCluster.hh
References theSpin.
Referenced by G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::INCL::makeCompoundNucleus(), and G4INCL::Nucleus::useFusionKinematics().
void G4INCL::Cluster::setZ (const G4int Z) inline
Set the charge number of the cluster.
Definition at line 146 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 146 of file G4INCLCluster.hh
References G4INCL::Particle::theZ, and Z.
Referenced by G4INCL::INCL::makeCompoundNucleus().
void G4INCL::Cluster::swap (Cluster & rhs) inline
Helper method for the assignment operator.
Definition at line 122 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 122 of file G4INCLCluster.hh
References particles, G4INCL::Particle::swap(), boost::swap(), theExcitationEnergy, theParticleSampler, and theSpin.
Referenced by operator=().
void G4INCL::Cluster::updateClusterParameters () inline
Set total cluster mass, energy, size, etc. from the particles.
Definition at line 191 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 191 of file G4INCLCluster.hh
References e, G4INCL::Particle::nCollisions, particles, G4INCL::Particle::theA, G4INCL::Particle::theEnergy, G4INCL::Particle::theMomentum, G4INCL::Particle::thePosition, G4INCL::Particle::thePotentialEnergy, G4INCL::Particle::theS, and G4INCL::Particle::theZ.
Referenced by addParticles(), and initializeParticles().
Member Data Documentation
ParticleList G4INCL::Cluster::particles protected
Definition at line 451 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 451 of file G4INCLCluster.hh
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), addParticle(), addParticles(), boost(), clearParticles(), Cluster(), computeDynamicalPotential(), deleteParticles(), freezeInternalMotion(), getParticleList(), getParticles(), G4INCL::ProjectileRemnant::getPresentEnergyLevelsExcept(), G4INCL::ProjectileRemnant::getPresentEnergyLevelsWith(), G4INCL::Nucleus::initializeParticles(), initializeParticles(), internalBoostToCM(), makeParticipant(), makeProjectileSpectator(), makeTargetSpectator(), print(), putParticlesOffShell(), G4INCL::ProjectileRemnant::removeParticle(), removeParticle(), rotateMomentum(), rotatePosition(), setPosition(), G4INCL::ProjectileRemnant::storeComponents(), G4INCL::ProjectileRemnant::storeEnergyLevels(), swap(), and updateClusterParameters().
G4double G4INCL::Cluster::theExcitationEnergy protected
Definition at line 452 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 452 of file G4INCLCluster.hh
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::computeRecoilKinematics(), getExcitationEnergy(), G4INCL::Nucleus::getExcitationEnergy(), setExcitationEnergy(), swap(), and G4INCL::Nucleus::useFusionKinematics().
ParticleSampler* G4INCL::Cluster::theParticleSampler protected
Definition at line 454 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 454 of file G4INCLCluster.hh
Referenced by Cluster(), initializeParticles(), G4INCL::Nucleus::Nucleus(), G4INCL::Nucleus::setDensity(), swap(), and ~Cluster().
ThreeVector G4INCL::Cluster::theSpin protected
Definition at line 453 of file G4INCLCluster.hh.
View newest version in sPHENIX GitHub at line 453 of file G4INCLCluster.hh
Referenced by G4INCL::Nucleus::computeRecoilKinematics(), getSpin(), setSpin(), and swap().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCluster.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCluster.cc