ECCE @ EIC Software: G4DNABornAngle Class Reference
G4DNABornAngle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNABornAngle.hh>
Public Member Functions
G4DNABornAngle (const G4String &name="")
virtual ~G4DNABornAngle ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double kinEnergyFinal, G4int Z, const G4Material *mat=0)
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double kinEnergyFinal, G4int Z, G4int shellIdx, const G4Material *mat=0)
void PrintGeneratorInformation () const
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Private Member Functions
G4DNABornAngle & operator= (const G4DNABornAngle &right)
G4DNABornAngle (const G4DNABornAngle &)
Private Attributes
const G4ParticleDefinition * fElectron
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 56 of file G4DNABornAngle.hh.
View newest version in sPHENIX GitHub at line 56 of file G4DNABornAngle.hh
Constructor & Destructor Documentation
G4DNABornAngle::G4DNABornAngle (const G4String & name = "")
Definition at line 58 of file G4DNABornAngle.cc.
View newest version in sPHENIX GitHub at line 58 of file G4DNABornAngle.cc
References G4Electron::Electron(), and fElectron.
G4DNABornAngle::~G4DNABornAngle () virtual
Definition at line 64 of file G4DNABornAngle.cc.
View newest version in sPHENIX GitHub at line 64 of file G4DNABornAngle.cc
G4DNABornAngle::G4DNABornAngle (const G4DNABornAngle &) private
Member Function Documentation
G4DNABornAngle& G4DNABornAngle::operator= (const G4DNABornAngle & right) private
void G4DNABornAngle::PrintGeneratorInformation () const
Definition at line 120 of file G4DNABornAngle.cc.
View newest version in sPHENIX GitHub at line 120 of file G4DNABornAngle.cc
G4ThreeVector & G4DNABornAngle::SampleDirection (const G4DynamicParticle * dp, G4double kinEnergyFinal, G4int Z, const G4Material * mat = 0) virtual
Implements G4VEmAngularDistribution.
Definition at line 113 of file G4DNABornAngle.cc.
View newest version in sPHENIX GitHub at line 113 of file G4DNABornAngle.cc
References SampleDirectionForShell().
G4ThreeVector & G4DNABornAngle::SampleDirectionForShell (const G4DynamicParticle * dp, G4double kinEnergyFinal, G4int Z, G4int shellIdx, const G4Material * mat = 0) virtual
Reimplemented from G4VEmAngularDistribution.
Definition at line 68 of file G4DNABornAngle.cc.
View newest version in sPHENIX GitHub at line 68 of file G4DNABornAngle.cc
References source.hepunit::electron_mass_c2, eV, fElectron, G4VEmAngularDistribution::fLocalDirection, G4UniformRand, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), k, mass, phi, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), and twopi.
Referenced by SampleDirection().
Member Data Documentation
const G4ParticleDefinition* G4DNABornAngle::fElectron private
Definition at line 84 of file G4DNABornAngle.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DNABornAngle.hh
Referenced by G4DNABornAngle(), and SampleDirectionForShell().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNABornAngle.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNABornAngle.cc