ECCE @ EIC Software: G4AtomicDeexcitation Class Reference
G4AtomicDeexcitation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AtomicDeexcitation.hh>
Public Member Functions
G4AtomicDeexcitation ()
~G4AtomicDeexcitation ()
std::vector< G4DynamicParticle * > * GenerateParticles (G4int Z, G4int shellId)
void SetCutForSecondaryPhotons (G4double cut)
void SetCutForAugerElectrons (G4double cut)
void ActivateAugerElectronProduction (G4bool val)
Private Member Functions
G4int SelectTypeOfTransition (G4int Z, G4int shellId)
G4DynamicParticle * GenerateFluorescence (G4int Z, G4int shellId, G4int provShellId)
G4DynamicParticle * GenerateAuger (G4int Z, G4int shellId)
Private Attributes
G4int newShellId
G4double minGammaEnergy
G4double minElectronEnergy
G4bool fAuger
G4int augerVacancyId
Detailed Description
Definition at line 51 of file G4AtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 51 of file G4AtomicDeexcitation.hh
Constructor & Destructor Documentation
G4AtomicDeexcitation::G4AtomicDeexcitation ()
Definition at line 48 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 48 of file G4AtomicDeexcitation.cc
References augerVacancyId, G4cout, G4endl, and newShellId.
G4AtomicDeexcitation::~G4AtomicDeexcitation ()
Definition at line 68 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 68 of file G4AtomicDeexcitation.cc
Member Function Documentation
void G4AtomicDeexcitation::ActivateAugerElectronProduction (G4bool val)
Definition at line 491 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 491 of file G4AtomicDeexcitation.cc
References fAuger.
Referenced by G4hImpactIonisation::ActivateAugerElectronProduction().
G4DynamicParticle * G4AtomicDeexcitation::GenerateAuger (G4int Z, G4int shellId) private
Definition at line 276 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 276 of file G4AtomicDeexcitation.cc
References G4AugerTransition::AugerTransitionEnergy(), G4AugerTransition::AugerTransitionProbabilities(), G4AugerTransition::AugerTransitionProbability(), G4Electron::Electron(), fAuger, G4AugerTransition::FinalShellId(), G4Exception(), G4UniformRand, G4AtomicTransitionManager::Instance(), JustWarning, newShellId, G4AtomicTransitionManager::NumberOfReachableAugerShells(), pos(), G4AtomicTransitionManager::ReachableAugerShell(), G4AugerTransition::TransitionOriginatingShellIds(), and twopi.
Referenced by GenerateParticles().
G4DynamicParticle * G4AtomicDeexcitation::GenerateFluorescence (G4int Z, G4int shellId, G4int provShellId) private
Definition at line 210 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 210 of file G4AtomicDeexcitation.cc
References G4UniformRand, G4Gamma::Gamma(), G4AtomicTransitionManager::Instance(), newShellId, G4AtomicTransitionManager::NumberOfReachableShells(), and twopi.
Referenced by GenerateParticles().
std::vector< G4DynamicParticle * > * G4AtomicDeexcitation::GenerateParticles (G4int Z, G4int shellId)
Definition at line 71 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 71 of file G4AtomicDeexcitation.cc
References G4Exception(), GenerateAuger(), GenerateFluorescence(), JustWarning, newShellId, and SelectTypeOfTransition().
Referenced by G4hImpactIonisation::PostStepDoIt().
G4int G4AtomicDeexcitation::SelectTypeOfTransition (G4int Z, G4int shellId) private
Definition at line 138 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 138 of file G4AtomicDeexcitation.cc
References G4FluoTransition::FinalShellId(), G4Exception(), G4UniformRand, G4AtomicTransitionManager::Instance(), JustWarning, G4AtomicTransitionManager::NumberOfReachableShells(), G4FluoTransition::OriginatingShellId(), G4AtomicTransitionManager::ReachableShell(), G4FluoTransition::TransitionProbabilities(), and G4FluoTransition::TransitionProbability().
Referenced by GenerateParticles().
void G4AtomicDeexcitation::SetCutForAugerElectrons (G4double cut)
Definition at line 486 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 486 of file G4AtomicDeexcitation.cc
References minElectronEnergy.
void G4AtomicDeexcitation::SetCutForSecondaryPhotons (G4double cut)
Definition at line 481 of file G4AtomicDeexcitation.cc.
View newest version in sPHENIX GitHub at line 481 of file G4AtomicDeexcitation.cc
References minGammaEnergy.
Member Data Documentation
G4int G4AtomicDeexcitation::augerVacancyId private
Definition at line 94 of file G4AtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4AtomicDeexcitation.hh
Referenced by G4AtomicDeexcitation().
G4bool G4AtomicDeexcitation::fAuger private
Definition at line 90 of file G4AtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4AtomicDeexcitation.hh
Referenced by ActivateAugerElectronProduction(), and GenerateAuger().
G4double G4AtomicDeexcitation::minElectronEnergy private
Definition at line 89 of file G4AtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 89 of file G4AtomicDeexcitation.hh
Referenced by SetCutForAugerElectrons().
G4double G4AtomicDeexcitation::minGammaEnergy private
Definition at line 88 of file G4AtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 88 of file G4AtomicDeexcitation.hh
Referenced by SetCutForSecondaryPhotons().
G4int G4AtomicDeexcitation::newShellId private
Definition at line 86 of file G4AtomicDeexcitation.hh.
View newest version in sPHENIX GitHub at line 86 of file G4AtomicDeexcitation.hh
Referenced by G4AtomicDeexcitation(), GenerateAuger(), GenerateFluorescence(), and GenerateParticles().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AtomicDeexcitation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4AtomicDeexcitation.cc