ECCE @ EIC Software: G4MolecularConfiguration Class Reference
G4MolecularConfiguration Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularConfiguration.hh>
Classes
class G4MolecularConfigurationManager
Public Types
typedef std::function< double(const
G4Material *, double, const
G4MolecularConfiguration *)> G4DiffCoeffParam
Public Member Functions
void AddDiffCoeffParameterization (const G4DiffCoeffParam &)
const G4MoleculeDefinition * GetDefinition () const
const G4String & GetName () const
const G4String & GetFormatedName () const
G4int GetAtomsNumber () const
G4MolecularConfiguration * ExciteMolecule (G4int) const
G4MolecularConfiguration * IonizeMolecule (G4int) const
G4MolecularConfiguration * AddElectron (G4int orbit, G4int n=1) const
G4MolecularConfiguration * RemoveElectron (G4int, G4int number=1) const
G4MolecularConfiguration * MoveOneElectron (G4int, G4int) const
G4double GetNbElectrons () const
void PrintState () const
const std::vector< const
G4MolecularDissociationChannel * > * GetDissociationChannels () const
G4int GetFakeParticleID () const
G4int GetMoleculeID () const
void SetDiffusionCoefficient (G4double)
G4double GetDiffusionCoefficient () const
G4double GetDiffusionCoefficient (const G4Material *, double temperature) const
void SetDecayTime (G4double)
G4double GetDecayTime () const
void SetVanDerVaalsRadius (G4double)
G4double GetVanDerVaalsRadius () const
const G4ElectronOccupancy * GetElectronOccupancy () const
G4int GetCharge () const
void SetMass (G4double)
G4double GetMass () const
void SetLabel (const G4String &)
const G4String & GetLabel () const
void Finalize ()
const G4String & GetUserID () const
void Serialize (std::ostream &)
void Unserialize (std::istream &)
Static Public Member Functions
static G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *)
static G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *, const G4ElectronOccupancy &eOcc)
static G4MolecularConfiguration * GetOrCreateMolecularConfiguration (const G4MoleculeDefinition *, int charge)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, bool &wasAlreadyCreated)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, const G4String &label, const G4ElectronOccupancy &eOcc, bool &wasAlreadyCreated)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, int charge, const G4String &label, bool &wasAlreadyCreated)
static G4MolecularConfiguration * CreateMolecularConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *, const G4String &label, bool &wasAlreadyCreated)
static G4MolecularConfiguration * GetMolecularConfiguration (const G4MoleculeDefinition *, const G4String &label)
static G4MolecularConfiguration * GetMolecularConfiguration (int moleculeID)
static G4MolecularConfiguration * GetMolecularConfiguration (const G4String &userID)
static int GetNumberOfSpecies ()
static std::map< G4String,
G4MolecularConfiguration * > & GetUserIDTable ()
static void DeleteManager ()
static double DiffCoeffWater (double temperature_K)
static void FinalizeAll ()
static void SetGlobalTemperature (G4double)
static G4double GetGlobalTemperature ()
static G4MolecularConfiguration * Load (std::istream &)
Protected Member Functions
G4MolecularConfiguration (const G4MoleculeDefinition *, const G4ElectronOccupancy &, const G4String &label="")
G4MolecularConfiguration (const G4MoleculeDefinition *, int charge)
G4MolecularConfiguration (const G4MoleculeDefinition *, const G4String &label, int charge)
G4MolecularConfiguration (std::istream &)
G4MolecularConfiguration (const G4MolecularConfiguration &)
G4MolecularConfiguration & operator= (G4MolecularConfiguration &right)
~G4MolecularConfiguration ()
G4MolecularConfiguration * ChangeConfiguration (const G4ElectronOccupancy &newElectronOccupancy) const
G4MolecularConfiguration * ChangeConfiguration (int charge) const
void CheckElectronOccupancy (const char *line) const
void MakeExceptionIfFinalized ()
void SetUserID (const G4String &userID)
void CreateDefaultDiffCoeffParam ()
Static Protected Member Functions
static void ScaleAllDiffusionCoefficientsOnWater (double temperature_K)
static
G4MolecularConfigurationManager * GetManager ()
static double ReturnDefaultDiffCoeff (const G4Material *, double, const G4MolecularConfiguration *molConf)
Protected Attributes
const G4MoleculeDefinition * fMoleculeDefinition
const G4ElectronOccupancy * fElectronOccupancy
G4String * fLabel
G4double fDynDiffusionCoefficient
G4double fDynVanDerVaalsRadius
G4double fDynDecayTime
G4double fDynMass
G4int fDynCharge
G4int fMoleculeID
G4String fFormatedName
G4String fName
G4String fUserIdentifier
G4bool fIsFinalized
G4DiffCoeffParam fDiffParam
Static Protected Attributes
static
G4MolecularConfigurationManager * fgManager = 0
static double fgTemperature = 298
Detailed Description
The pointer G4MolecularConfiguration will be shared by all the molecules having the same molecule definition and the same electron occupancy BE CAREFUlL !!! : If you change the mass for instance of a OH^-, this will affect all the OH^- molecule diffusing around
Definition at line 98 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 98 of file G4MolecularConfiguration.hh
Member Typedef Documentation
typedef std::function<double(const G4Material*, double, const G4MolecularConfiguration*)> G4MolecularConfiguration::G4DiffCoeffParam
Definition at line 104 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 104 of file G4MolecularConfiguration.hh
Constructor & Destructor Documentation
G4MolecularConfiguration::G4MolecularConfiguration (const G4MoleculeDefinition * moleculeDef, const G4ElectronOccupancy & elecOcc, const G4String & label = "") protected
Definition at line 437 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 437 of file G4MolecularConfiguration.cc
References G4UIcommand::ConvertToString(), fName, G4MoleculeDefinition::GetCharge(), G4MoleculeDefinition::GetNbElectrons(), and ReturnDefaultDiffCoeff().
G4MolecularConfiguration::G4MolecularConfiguration (const G4MoleculeDefinition * moleculeDef, int charge) protected
Definition at line 490 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 490 of file G4MolecularConfiguration.cc
References charge, G4UIcommand::ConvertToString(), fName, and ReturnDefaultDiffCoeff().
G4MolecularConfiguration::G4MolecularConfiguration (const G4MoleculeDefinition * moleculeDef, const G4String & label, int charge) protected
Definition at line 79 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 79 of file G4MolecularConfiguration.cc
References charge, G4UIcommand::ConvertToString(), fName, and ReturnDefaultDiffCoeff().
G4MolecularConfiguration::G4MolecularConfiguration (std::istream & in) protected
Definition at line 1443 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1443 of file G4MolecularConfiguration.cc
G4MolecularConfiguration::G4MolecularConfiguration (const G4MolecularConfiguration &) protected
G4MolecularConfiguration::~G4MolecularConfiguration () protected
Definition at line 526 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 526 of file G4MolecularConfiguration.cc
Member Function Documentation
void G4MolecularConfiguration::AddDiffCoeffParameterization (const G4DiffCoeffParam & para) inline
Definition at line 582 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 582 of file G4MolecularConfiguration.hh
G4MolecularConfiguration * G4MolecularConfiguration::AddElectron (G4int orbit, G4int n = 1) const
Add n electrons to a given orbit. Note : You can add as many electrons to a given orbit, the result may be unrealist.
Definition at line 635 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 635 of file G4MolecularConfiguration.cc
References G4ElectronOccupancy::AddElectron().
Referenced by G4Molecule::AddElectron().
G4MolecularConfiguration * G4MolecularConfiguration::ChangeConfiguration (const G4ElectronOccupancy & newElectronOccupancy) const protected
Definition at line 544 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 544 of file G4MolecularConfiguration.cc
References GetMolecularConfiguration().
G4MolecularConfiguration * G4MolecularConfiguration::ChangeConfiguration (int charge) const protected
Definition at line 561 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 561 of file G4MolecularConfiguration.cc
References GetMolecularConfiguration().
void G4MolecularConfiguration::CheckElectronOccupancy (const char * line) const protected
Definition at line 823 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 823 of file G4MolecularConfiguration.cc
References FatalErrorInArgument, and G4Exception().
void G4MolecularConfiguration::CreateDefaultDiffCoeffParam () protected
Definition at line 1515 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1515 of file G4MolecularConfiguration.cc
References ReturnDefaultDiffCoeff().
Referenced by Finalize().
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, bool & wasAlreadyCreated) static
Definition at line 1098 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1098 of file G4MolecularConfiguration.cc
References FatalErrorInArgument, fUserIdentifier, G4Exception(), G4MoleculeDefinition::GetCharge(), GetDefinition(), G4MoleculeDefinition::GetGroundStateElectronOccupancy(), GetMolecularConfiguration(), G4MoleculeDefinition::GetName(), and JustWarning.
Referenced by G4MoleculeTable::CreateConfiguration(), G4MoleculeDefinition::NewConfiguration(), and G4MoleculeDefinition::NewConfigurationWithElectronOccupancy().
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, const G4String & label, const G4ElectronOccupancy & eOcc, bool & wasAlreadyCreated) static
Definition at line 1245 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1245 of file G4MolecularConfiguration.cc
References FatalErrorInArgument, fLabel, fUserIdentifier, G4Exception(), GetElectronOccupancy(), GetMolecularConfiguration(), G4MoleculeDefinition::GetName(), PrintState(), and SetLabel().
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, int charge, const G4String & label, bool & wasAlreadyCreated) static
Definition at line 1005 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1005 of file G4MolecularConfiguration.cc
References FatalErrorInArgument, fLabel, fUserIdentifier, G4Exception(), GetLabel(), GetMolecularConfiguration(), G4MoleculeDefinition::GetName(), JustWarning, and SetLabel().
G4MolecularConfiguration * G4MolecularConfiguration::CreateMolecularConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, const G4String & label, bool & wasAlreadyCreated) static
Definition at line 1179 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1179 of file G4MolecularConfiguration.cc
References FatalErrorInArgument, fLabel, fUserIdentifier, G4Exception(), G4MoleculeDefinition::GetCharge(), GetLabel(), GetMolecularConfiguration(), G4MoleculeDefinition::GetName(), PrintState(), and SetLabel().
void G4MolecularConfiguration::DeleteManager () static
Definition at line 426 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 426 of file G4MolecularConfiguration.cc
References G4MolecularConfiguration::G4MolecularConfigurationManager::fManagerCreationMutex, and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by G4DNAChemistryManager::Clear().
double G4MolecularConfiguration::DiffCoeffWater (double temperature_K) static
Definition at line 1482 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1482 of file G4MolecularConfiguration.cc
References e, e3, e5, and m2.
Referenced by G4DNAMolecularReactionData::ScaledParameterization().
G4MolecularConfiguration * G4MolecularConfiguration::ExciteMolecule (G4int ExcitedLevel) const
Method used in Geant4-DNA to excite water molecules
Definition at line 587 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 587 of file G4MolecularConfiguration.cc
References G4ElectronOccupancy::AddElectron(), and G4ElectronOccupancy::RemoveElectron().
Referenced by G4Molecule::ExciteMolecule().
void G4MolecularConfiguration::Finalize () inline
Definition at line 570 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 570 of file G4MolecularConfiguration.hh
References CreateDefaultDiffCoeffParam(), and fIsFinalized.
void G4MolecularConfiguration::FinalizeAll () static
Definition at line 1561 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1561 of file G4MolecularConfiguration.cc
Referenced by G4MoleculeTable::Finalize().
G4int G4MolecularConfiguration::GetAtomsNumber () const
Returns the nomber of atoms compouning the molecule
Definition at line 736 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 736 of file G4MolecularConfiguration.cc
Referenced by G4Molecule::GetAtomsNumber().
G4int G4MolecularConfiguration::GetCharge () const inline
Returns the charge of molecule.
Definition at line 527 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 527 of file G4MolecularConfiguration.hh
References fDynCharge.
Referenced by G4Molecule::GetCharge().
G4double G4MolecularConfiguration::GetDecayTime () const inline
Returns the decay time of the molecule.
Definition at line 511 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 511 of file G4MolecularConfiguration.hh
References fDynDecayTime.
Referenced by G4Molecule::GetDecayTime().
const G4MoleculeDefinition * G4MolecularConfiguration::GetDefinition () const inline
Definition at line 484 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 484 of file G4MolecularConfiguration.hh
References fMoleculeDefinition.
Referenced by G4MoleculeCounter::AddAMoleculeAtTime(), G4Molecule::BuildTrack(), G4Molecule::ChangeConfigurationToLabel(), CreateMolecularConfiguration(), G4Molecule::GetDefinition(), G4MoleculeCounter::RemoveAMoleculeAtTime(), G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable(), and G4Molecule::SetElectronOccupancy().
G4double G4MolecularConfiguration::GetDiffusionCoefficient () const inline
Returns the diffusion coefficient D.
Definition at line 500 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 500 of file G4MolecularConfiguration.hh
References fDynDiffusionCoefficient.
Referenced by G4DNAMolecularReactionData::ComputeEffectiveRadius(), G4Molecule::GetDiffusionCoefficient(), ScaleAllDiffusionCoefficientsOnWater(), and G4DNAMoleculeEncounterStepper::Utils::Utils().
G4double G4MolecularConfiguration::GetDiffusionCoefficient (const G4Material * material, double temperature) const inline
Definition at line 588 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 588 of file G4MolecularConfiguration.hh
References fDiffParam.
const vector< const G4MolecularDissociationChannel * > * G4MolecularConfiguration::GetDissociationChannels () const
Definition at line 789 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 789 of file G4MolecularConfiguration.cc
Referenced by G4Molecule::GetDissociationChannels().
const G4ElectronOccupancy * G4MolecularConfiguration::GetElectronOccupancy () const inline
Returns the object ElectronOccupancy describing the electronic configuration of the molecule.
Definition at line 489 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 489 of file G4MolecularConfiguration.hh
References fElectronOccupancy.
Referenced by CreateMolecularConfiguration(), G4Molecule::GetElectronOccupancy(), and G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable().
G4int G4MolecularConfiguration::GetFakeParticleID () const
Definition at line 797 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 797 of file G4MolecularConfiguration.cc
References FatalErrorInArgument, G4Exception(), and INT_MAX.
Referenced by G4Molecule::GetFakeParticleID().
const G4String & G4MolecularConfiguration::GetFormatedName () const
Returns the formated name of the molecule
Definition at line 721 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 721 of file G4MolecularConfiguration.cc
Referenced by G4Molecule::GetFormatedName().
G4double G4MolecularConfiguration::GetGlobalTemperature () static
Definition at line 1533 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1533 of file G4MolecularConfiguration.cc
Referenced by G4DNAChemistryManager::GetCurrentValue(), and G4Molecule::GetDiffusionVelocity().
const G4String & G4MolecularConfiguration::GetLabel () const inline
Definition at line 562 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 562 of file G4MolecularConfiguration.hh
References fLabel.
Referenced by CreateMolecularConfiguration(), and G4Molecule::GetLabel().
G4MolecularConfiguration::G4MolecularConfigurationManager * G4MolecularConfiguration::GetManager () static protected
Definition at line 130 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 130 of file G4MolecularConfiguration.cc
References G4MolecularConfiguration::G4MolecularConfigurationManager::fManagerCreationMutex, and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by GetUserIDTable().
G4double G4MolecularConfiguration::GetMass () const inline
Returns the total mass of the molecule.
Definition at line 538 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 538 of file G4MolecularConfiguration.hh
References fDynMass.
Referenced by G4Molecule::GetDiffusionVelocity(), G4Molecule::GetKineticEnergy(), and G4Molecule::GetMass().
G4MolecularConfiguration * G4MolecularConfiguration::GetMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4String & label) static
Definition at line 988 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 988 of file G4MolecularConfiguration.cc
References GetMolecularConfiguration().
Referenced by G4MoleculeDefinition::AddDecayChannel(), ChangeConfiguration(), G4Molecule::ChangeConfigurationToLabel(), CreateMolecularConfiguration(), G4MoleculeTable::GetConfiguration(), G4MoleculeDefinition::GetConfigurationWithLabel(), GetMolecularConfiguration(), and GetOrCreateMolecularConfiguration().
G4MolecularConfiguration * G4MolecularConfiguration::GetMolecularConfiguration (int moleculeID) static
Definition at line 997 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 997 of file G4MolecularConfiguration.cc
References GetMolecularConfiguration().
G4MolecularConfiguration * G4MolecularConfiguration::GetMolecularConfiguration (const G4String & userID) static
Definition at line 1554 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1554 of file G4MolecularConfiguration.cc
References GetMolecularConfiguration().
G4int G4MolecularConfiguration::GetMoleculeID () const inline
Definition at line 543 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 543 of file G4MolecularConfiguration.hh
References fMoleculeID.
Referenced by G4Molecule::GetMoleculeID().
const G4String & G4MolecularConfiguration::GetName (void) const
Returns the name of the molecule
Definition at line 706 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 706 of file G4MolecularConfiguration.cc
References fName.
Referenced by G4MoleculeCounter::AddAMoleculeAtTime(), G4DNAMolecularReactionTable::CanReactWith(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4Molecule::GetName(), G4DNAMolecularReactionTable::GetReactionData(), G4DNAMolecularReactionTable::GetReativesNData(), G4DNAMolecularReactionTable::PrintTable(), G4MoleculeCounter::RemoveAMoleculeAtTime(), and ScoreSpecies::WriteWithAnalysisManager().
G4double G4MolecularConfiguration::GetNbElectrons () const
Returns the number of electron.
Definition at line 743 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 743 of file G4MolecularConfiguration.cc
Referenced by G4Molecule::GetNbElectrons().
int G4MolecularConfiguration::GetNumberOfSpecies () static
Definition at line 66 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 66 of file G4MolecularConfiguration.cc
Referenced by G4MoleculeTable::GetNumberOfDefinedSpecies().
G4MolecularConfiguration * G4MolecularConfiguration::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef) static
Definition at line 338 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 338 of file G4MolecularConfiguration.cc
References G4MoleculeDefinition::GetCharge(), G4MoleculeDefinition::GetGroundStateElectronOccupancy(), GetMolecularConfiguration(), G4MoleculeDefinition::GetName(), and SetUserID().
Referenced by G4Molecule::G4Molecule(), GetOrCreateMolecularConfiguration(), G4MoleculeTable::PrepareMolecularConfiguration(), and G4Molecule::SetElectronOccupancy().
G4MolecularConfiguration * G4MolecularConfiguration::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef, const G4ElectronOccupancy & eOcc) static
Definition at line 382 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 382 of file G4MolecularConfiguration.cc
References GetOrCreateMolecularConfiguration().
G4MolecularConfiguration * G4MolecularConfiguration::GetOrCreateMolecularConfiguration (const G4MoleculeDefinition * molDef, int charge) static
Definition at line 406 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 406 of file G4MolecularConfiguration.cc
References GetMolecularConfiguration().
const G4String & G4MolecularConfiguration::GetUserID () const inline
Definition at line 576 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 576 of file G4MolecularConfiguration.hh
References fUserIdentifier.
static std::map<G4String, G4MolecularConfiguration*>& G4MolecularConfiguration::GetUserIDTable () inline static
Definition at line 169 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 169 of file G4MolecularConfiguration.hh
References GetManager(), and G4MolecularConfiguration::G4MolecularConfigurationManager::GetUserIDTable().
Referenced by G4MoleculeTable::GetConfigurationIterator().
G4double G4MolecularConfiguration::GetVanDerVaalsRadius () const inline
Definition at line 522 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 522 of file G4MolecularConfiguration.hh
References fDynVanDerVaalsRadius.
Referenced by G4Molecule::GetVanDerVaalsRadius().
G4MolecularConfiguration * G4MolecularConfiguration::IonizeMolecule (G4int IonizedLevel) const
Method used in Geant4-DNA to ionize water molecules
Definition at line 604 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 604 of file G4MolecularConfiguration.cc
References G4UIcommand::ConvertToString(), FatalErrorInArgument, G4Exception(), G4ElectronOccupancy::GetOccupancy(), and G4ElectronOccupancy::RemoveElectron().
Referenced by G4Molecule::IonizeMolecule().
G4MolecularConfiguration * G4MolecularConfiguration::Load (std::istream & in) static
Definition at line 1436 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1436 of file G4MolecularConfiguration.cc
void G4MolecularConfiguration::MakeExceptionIfFinalized () protected
Definition at line 114 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 114 of file G4MolecularConfiguration.cc
References FatalException, and G4Exception().
Referenced by SetDecayTime(), SetDiffusionCoefficient(), SetMass(), and SetVanDerVaalsRadius().
G4MolecularConfiguration * G4MolecularConfiguration::MoveOneElectron (G4int orbitToFree, G4int orbitToFill) const
Move one electron from an orbit to another.
Definition at line 677 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 677 of file G4MolecularConfiguration.cc
References G4ElectronOccupancy::AddElectron(), G4UIcommand::ConvertToString(), FatalErrorInArgument, G4Exception(), G4ElectronOccupancy::GetOccupancy(), and G4ElectronOccupancy::RemoveElectron().
Referenced by G4Molecule::MoveOneElectron().
G4MolecularConfiguration & G4MolecularConfiguration::operator= (G4MolecularConfiguration & right) protected
Definition at line 576 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 576 of file G4MolecularConfiguration.cc
void G4MolecularConfiguration::PrintState () const
Display the electronic state of the molecule.
Definition at line 751 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 751 of file G4MolecularConfiguration.cc
References G4cout, and G4endl.
Referenced by CreateMolecularConfiguration(), G4Molecule::PrintState(), and G4MoleculeCounter::RemoveAMoleculeAtTime().
G4MolecularConfiguration * G4MolecularConfiguration::RemoveElectron (G4int orbit, G4int number = 1) const
Remove n electrons to a given orbit.
Definition at line 648 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 648 of file G4MolecularConfiguration.cc
References G4UIcommand::ConvertToString(), G4Exception(), G4ElectronOccupancy::GetOccupancy(), JustWarning, and G4ElectronOccupancy::RemoveElectron().
Referenced by G4Molecule::RemoveElectron().
double G4MolecularConfiguration::ReturnDefaultDiffCoeff (const G4Material * , double , const G4MolecularConfiguration * molConf) static protected
Definition at line 71 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 71 of file G4MolecularConfiguration.cc
References fDynDiffusionCoefficient.
Referenced by CreateDefaultDiffCoeffParam(), and G4MolecularConfiguration().
void G4MolecularConfiguration::ScaleAllDiffusionCoefficientsOnWater (double temperature_K) static protected
Definition at line 1494 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1494 of file G4MolecularConfiguration.cc
References G4cout, G4endl, G4MoleculeTable::GetConfigurationIterator(), GetDiffusionCoefficient(), G4MoleculeTable::Instance(), it, SetDiffusionCoefficient(), and G4MoleculeIterator< MOLECULE >::value().
void G4MolecularConfiguration::Serialize (std::ostream & out)
Definition at line 1386 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1386 of file G4MolecularConfiguration.cc
References fName, and WRITE().
void G4MolecularConfiguration::SetDecayTime (G4double dynDecayTime) inline
Set the decay time of the molecule.
Definition at line 505 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 505 of file G4MolecularConfiguration.hh
References fDynDecayTime, and MakeExceptionIfFinalized().
Referenced by G4MoleculeDefinition::NewConfigurationWithElectronOccupancy().
void G4MolecularConfiguration::SetDiffusionCoefficient (G4double dynDiffusionCoefficient) inline
Sets the diffusion coefficient D of the molecule used in diffusion processes to calculate the mean square jump distance between two changes of direction. In three dimension : <x^2> = 6 D t where t is the mean jump time between two changes of direction.
Note : Diffusion Coefficient in one medium only For the time being, we will consider only one diffusion coefficient for the all simulation => diffusion in one medium only If the user needs to use the diffusion in different materials, she/he should contact the developpers/mainteners of this package
Definition at line 494 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 494 of file G4MolecularConfiguration.hh
References fDynDiffusionCoefficient, and MakeExceptionIfFinalized().
Referenced by G4EmDNAChemistry_option1::ConstructMolecule(), G4MoleculeTable::CreateConfiguration(), and ScaleAllDiffusionCoefficientsOnWater().
void G4MolecularConfiguration::SetGlobalTemperature (G4double temperature) static
Definition at line 1525 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1525 of file G4MolecularConfiguration.cc
Referenced by G4DNAChemistryManager::SetGlobalTemperature().
void G4MolecularConfiguration::SetLabel (const G4String & label) inline
Definition at line 548 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 548 of file G4MolecularConfiguration.hh
References fgManager, fLabel, and G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration().
Referenced by CreateMolecularConfiguration().
void G4MolecularConfiguration::SetMass (G4double aMass) inline
Set the total mass of the molecule.
Definition at line 532 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 532 of file G4MolecularConfiguration.hh
References fDynMass, and MakeExceptionIfFinalized().
Referenced by G4EmDNAChemistry::ConstructMolecule(), G4EmDNAChemistry_option1::ConstructMolecule(), and G4EmDNAChemistry_option2::ConstructMolecule().
void G4MolecularConfiguration::SetUserID (const G4String & userID) protected
Definition at line 1473 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1473 of file G4MolecularConfiguration.cc
Referenced by GetOrCreateMolecularConfiguration().
void G4MolecularConfiguration::SetVanDerVaalsRadius (G4double dynVanDerVaalsRadius) inline
The Van Der Valls Radius of the molecule
Definition at line 516 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 516 of file G4MolecularConfiguration.hh
References fDynVanDerVaalsRadius, and MakeExceptionIfFinalized().
void G4MolecularConfiguration::Unserialize (std::istream & in)
Definition at line 1408 of file G4MolecularConfiguration.cc.
View newest version in sPHENIX GitHub at line 1408 of file G4MolecularConfiguration.cc
References fName, G4MoleculeTable::GetMoleculeDefinition(), G4MoleculeTable::Instance(), and READ().
Member Data Documentation
G4DiffCoeffParam G4MolecularConfiguration::fDiffParam protected
Definition at line 475 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 475 of file G4MolecularConfiguration.hh
Referenced by GetDiffusionCoefficient().
G4int G4MolecularConfiguration::fDynCharge protected
Definition at line 468 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 468 of file G4MolecularConfiguration.hh
Referenced by GetCharge().
G4double G4MolecularConfiguration::fDynDecayTime protected
Definition at line 466 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 466 of file G4MolecularConfiguration.hh
Referenced by GetDecayTime(), and SetDecayTime().
G4double G4MolecularConfiguration::fDynDiffusionCoefficient protected
Definition at line 464 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 464 of file G4MolecularConfiguration.hh
Referenced by GetDiffusionCoefficient(), ReturnDefaultDiffCoeff(), and SetDiffusionCoefficient().
G4double G4MolecularConfiguration::fDynMass protected
Definition at line 467 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 467 of file G4MolecularConfiguration.hh
Referenced by GetMass(), and SetMass().
G4double G4MolecularConfiguration::fDynVanDerVaalsRadius protected
Definition at line 465 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 465 of file G4MolecularConfiguration.hh
Referenced by GetVanDerVaalsRadius(), and SetVanDerVaalsRadius().
const G4ElectronOccupancy* G4MolecularConfiguration::fElectronOccupancy protected
Definition at line 460 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 460 of file G4MolecularConfiguration.hh
Referenced by GetElectronOccupancy(), and G4MolecularConfiguration::G4MolecularConfigurationManager::RemoveMolecularConfigurationFromTable().
G4String G4MolecularConfiguration::fFormatedName protected
Definition at line 470 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 470 of file G4MolecularConfiguration.hh
MolecularConfigurationManager * G4MolecularConfiguration::fgManager = 0 static protected
Definition at line 456 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 456 of file G4MolecularConfiguration.hh
Referenced by SetLabel().
G4double G4MolecularConfiguration::fgTemperature = 298 static protected
Definition at line 476 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 476 of file G4MolecularConfiguration.hh
G4bool G4MolecularConfiguration::fIsFinalized protected
Definition at line 473 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 473 of file G4MolecularConfiguration.hh
Referenced by Finalize().
G4String* G4MolecularConfiguration::fLabel mutable protected
Definition at line 462 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 462 of file G4MolecularConfiguration.hh
Referenced by CreateMolecularConfiguration(), GetLabel(), G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration(), and SetLabel().
const G4MoleculeDefinition* G4MolecularConfiguration::fMoleculeDefinition protected
Definition at line 459 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 459 of file G4MolecularConfiguration.hh
Referenced by GetDefinition(), and G4MolecularConfiguration::G4MolecularConfigurationManager::RecordNewlyLabeledConfiguration().
G4int G4MolecularConfiguration::fMoleculeID protected
Definition at line 469 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 469 of file G4MolecularConfiguration.hh
Referenced by GetMoleculeID().
G4String G4MolecularConfiguration::fName protected
Definition at line 471 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 471 of file G4MolecularConfiguration.hh
G4String G4MolecularConfiguration::fUserIdentifier protected
Definition at line 472 of file G4MolecularConfiguration.hh.
View newest version in sPHENIX GitHub at line 472 of file G4MolecularConfiguration.hh
Referenced by CreateMolecularConfiguration(), and GetUserID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularConfiguration.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4MolecularConfiguration.cc