ECCE @ EIC Software: G4LFission Class Reference
G4LFission Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4LFission.hh>
Public Member Functions
G4LFission (const G4String &name="G4LFission")
~G4LFission ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual void ModelDescription (std::ostream &outFile) const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Static Public Member Functions
static G4double Atomas (const G4double A, const G4double Z)
Private Member Functions
void init ()
Private Attributes
G4double spneut [10]
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 64 of file G4LFission.hh.
View newest version in sPHENIX GitHub at line 64 of file G4LFission.hh
Constructor & Destructor Documentation
G4LFission::G4LFission (const G4String & name = "G4LFission")
Definition at line 52 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 52 of file G4LFission.cc
References DBL_MAX, GeV, init(), G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4LFission::~G4LFission ()
Definition at line 61 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 61 of file G4LFission.cc
References G4HadFinalState::Clear(), and G4HadronicInteraction::theParticleChange.
Member Function Documentation
G4HadFinalState * G4LFission::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 96 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 96 of file G4LFission.cc
References a, kdfinder::abs(), G4HadFinalState::AddSecondary(), Atomas(), G4HadFinalState::Clear(), E, e, e1, G4cout, G4endl, G4Log(), G4UniformRand, G4Gamma::GammaDefinition(), G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4HadSecondary::GetParticle(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4HadFinalState::GetSecondary(), G4HadProjectile::GetTotalEnergy(), G4DynamicParticle::GetTotalEnergy(), G4HadProjectile::GetTotalMomentum(), G4DynamicParticle::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), MeV, N, G4Neutron::NeutronDefinition(), G4InuclParticleNames::nn, P, phi, G4InuclParticleNames::pp, Q, ran(), G4DynamicParticle::SetKineticEnergy(), G4DynamicParticle::SetMomentumDirection(), G4HadFinalState::SetStatusChange(), G4INCL::DeJongSpin::shoot(), spneut, stopAndKill, G4HadronicInteraction::theParticleChange, twopi, CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
G4double G4LFission::Atomas (const G4double A, const G4double Z) static
Definition at line 245 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 245 of file G4LFission.cc
References G4Pow::A13(), G4Pow::A23(), G4Alpha::AlphaDefinition(), G4Deuteron::DeuteronDefinition(), G4Electron::ElectronDefinition(), G4Pow::GetInstance(), G4ParticleDefinition::GetPDGMass(), mass, MeV, G4Neutron::NeutronDefinition(), G4Pow::powA(), G4Proton::ProtonDefinition(), and Z.
Referenced by ApplyYourself().
const std::pair< G4double, G4double > G4LFission::GetFatalEnergyCheckLevels () const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 282 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 282 of file G4LFission.cc
References GeV, and perCent.
void G4LFission::init (void) private
Definition at line 77 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 77 of file G4LFission.cc
References G4cout, G4endl, G4Exp(), spneut, G4HadronicInteraction::verboseLevel, and xx.
Referenced by G4LFission().
void G4LFission::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 67 of file G4LFission.cc.
View newest version in sPHENIX GitHub at line 67 of file G4LFission.cc
Member Data Documentation
G4double G4LFission::spneut[10] private
Definition at line 83 of file G4LFission.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LFission.hh
Referenced by ApplyYourself(), and init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4LFission.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4LFission.cc