ECCE @ EIC Software: G4NistManager Class Reference
G4NistManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4NistManager.hh>
Public Member Functions
~G4NistManager ()
G4Element * GetElement (size_t index) const
G4Element * FindElement (G4int Z) const
G4Element * FindOrBuildElement (G4int Z, G4bool isotopes=true)
G4Element * FindOrBuildElement (const G4String &symb, G4bool isotopes=true)
size_t GetNumberOfElements () const
G4int GetZ (const G4String &symb) const
G4double GetAtomicMassAmu (const G4String &symb) const
G4double GetAtomicMassAmu (G4int Z) const
G4double GetIsotopeMass (G4int Z, G4int N) const
G4double GetAtomicMass (G4int Z, G4int N) const
G4double GetTotalElectronBindingEnergy (G4int Z) const
G4int GetNistFirstIsotopeN (G4int Z) const
G4int GetNumberOfNistIsotopes (G4int Z) const
G4double GetIsotopeAbundance (G4int Z, G4int N) const
void PrintElement (G4int Z) const
void PrintElement (const G4String &) const
void PrintG4Element (const G4String &) const
const std::vector< G4String > & GetNistElementNames () const
G4double GetMeanIonisationEnergy (G4int Z) const
G4double GetNominalDensity (G4int Z) const
G4Material * GetMaterial (size_t index) const
G4Material * FindMaterial (const G4String &name) const
G4Material * FindOrBuildMaterial (const G4String &name, G4bool isotopes=true, G4bool warning=false)
G4Material * FindSimpleMaterial (G4int Z) const
G4Material * FindOrBuildSimpleMaterial (G4int Z, G4bool warning=false)
G4Material * BuildMaterialWithNewDensity (const G4String &name, const G4String &basename, G4double density=0.0, G4double temp=NTP_Temperature, G4double pres=CLHEP::STP_Pressure)
G4Material * ConstructNewMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4int > &nbAtoms, G4double dens, G4bool isotopes=true, G4State state=kStateSolid, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material * ConstructNewMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4double > &weight, G4double dens, G4bool isotopes=true, G4State state=kStateSolid, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material * ConstructNewGasMaterial (const G4String &name, const G4String &nameNist, G4double temp, G4double pres, G4bool isotopes=true)
G4Material * ConstructNewIdealGasMaterial (const G4String &name, const std::vector< G4String > &elm, const std::vector< G4int > &nbAtoms, G4bool isotopes=true, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
void SetDensityEffectCalculatorFlag (const G4String &, G4bool)
void SetDensityEffectCalculatorFlag (G4Material *, G4bool)
size_t GetNumberOfMaterials () const
G4int GetVerbose () const
void SetVerbose (G4int)
void PrintG4Material (const G4String &) const
void ListMaterials (const G4String &) const
const std::vector< G4String > & GetNistMaterialNames () const
G4double GetZ13 (G4double Z) const
G4double GetZ13 (G4int Z) const
G4double GetA27 (G4int Z) const
G4double GetLOGZ (G4int Z) const
G4double GetLOGAMU (G4int Z) const
G4ICRU90StoppingData * GetICRU90StoppingData ()
Static Public Member Functions
static G4NistManager * Instance ()
Private Member Functions
G4NistManager ()
Private Attributes
std::vector< G4Element * > elements
std::vector< G4Material * > materials
G4ICRU90StoppingData * fICRU90
G4NistElementBuilder * elmBuilder
G4NistMaterialBuilder * matBuilder
G4NistMessenger * messenger
G4Pow * g4pow
G4double POWERA27 [101]
G4double LOGAZ [101]
size_t nElements
size_t nMaterials
G4int verbose
Static Private Attributes
static G4NistManager * instance = nullptr
Detailed Description
Definition at line 83 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4NistManager.hh
Constructor & Destructor Documentation
G4NistManager::~G4NistManager ()
Definition at line 89 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 89 of file G4NistManager.cc
References elmBuilder, fICRU90, G4Element::GetElementTable(), G4Isotope::GetIsotopeTable(), G4Material::GetMaterialTable(), matBuilder, and messenger.
G4NistManager::G4NistManager () explicit private
Definition at line 212 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 212 of file G4NistManager.cc
References A(), elmBuilder, fICRU90, g4pow, G4NistElementBuilder::GetAtomicMassAmu(), G4Pow::GetInstance(), LOGAZ, matBuilder, messenger, nElements, nMaterials, POWERA27, and verbose.
Member Function Documentation
G4Material * G4NistManager::BuildMaterialWithNewDensity (const G4String & name, const G4String & basename, G4double density = 0.0, G4double temp = NTP_Temperature, G4double pres = CLHEP::STP_Pressure)
Definition at line 121 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 121 of file G4NistManager.cc
References FatalException, FindOrBuildMaterial(), G4cout, G4endl, G4Exception(), G4Material::GetDensity(), G4Material::GetPressure(), G4Material::GetState(), G4Material::GetTemperature(), and mat.
Referenced by doiPETDetectorConstruction::DefineMaterials().
G4Material * G4NistManager::ConstructNewGasMaterial (const G4String & name, const G4String & nameNist, G4double temp, G4double pres, G4bool isotopes = true) inline
Definition at line 548 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 548 of file G4NistManager.hh
References G4NistMaterialBuilder::ConstructNewGasMaterial(), and matBuilder.
Referenced by export_G4NistManager().
G4Material * G4NistManager::ConstructNewIdealGasMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4int > & nbAtoms, G4bool isotopes = true, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure) inline
Definition at line 560 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 560 of file G4NistManager.hh
References G4NistMaterialBuilder::ConstructNewIdealGasMaterial(), and matBuilder.
G4Material * G4NistManager::ConstructNewMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4int > & nbAtoms, G4double dens, G4bool isotopes = true, G4State state = kStateSolid, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure) inline
Definition at line 516 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 516 of file G4NistManager.hh
References G4NistMaterialBuilder::ConstructNewMaterial(), and matBuilder.
Referenced by XrayFluoNistMaterials::CreateMaterials().
G4Material * G4NistManager::ConstructNewMaterial (const G4String & name, const std::vector< G4String > & elm, const std::vector< G4double > & weight, G4double dens, G4bool isotopes = true, G4State state = kStateSolid, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure) inline
Definition at line 533 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 533 of file G4NistManager.hh
References G4NistMaterialBuilder::ConstructNewMaterial(), and matBuilder.
G4Element * G4NistManager::FindElement (G4int Z) const inline
Definition at line 338 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 338 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::FindElement().
G4Material * G4NistManager::FindMaterial (const G4String & name) const inline
Definition at line 483 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 483 of file G4NistManager.hh
References G4NistMaterialBuilder::FindMaterial(), and matBuilder.
Referenced by SetDensityEffectCalculatorFlag().
G4Element * G4NistManager::FindOrBuildElement (G4int Z, G4bool isotopes = true) inline
Definition at line 346 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 346 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::FindOrBuildElement().
Referenced by GammaKnifeDetectorConstruction::ConstructBeamLine(), ExN04DetectorConstruction::DefineMaterials(), B3DetectorConstruction::DefineMaterials(), ElectronBenchmarkDetector::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), FFDetectorConstruction::DefineMaterials(), HistoManager::EndOfRun(), G4tgbMaterialMgr::FindOrBuildG4Element(), G4Material::G4Material(), PHG4Detector::GetDetectorElement(), G4GDMLReadMaterials::GetElement(), EICG4ZDCStructure::Materials(), LaserDrivenBeamLine::SetDefaultDimensions(), Collimator70BeamLine::SetDefaultDimensions(), Collimator40BeamLine::SetDefaultDimensions(), Collimator100BeamLine::SetDefaultDimensions(), Collimator60BeamLine::SetDefaultDimensions(), Collimator50BeamLine::SetDefaultDimensions(), Collimator80BeamLine::SetDefaultDimensions(), PassiveCarbonBeamLine::SetDefaultDimensions(), TrentoPassiveProtonBeamLine::SetDefaultDimensions(), PassiveProtonBeamLine::SetDefaultDimensions(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
G4Element * G4NistManager::FindOrBuildElement (const G4String & symb, G4bool isotopes = true) inline
Definition at line 354 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 354 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::FindOrBuildElement().
G4Material * G4NistManager::FindOrBuildMaterial (const G4String & name, G4bool isotopes = true, G4bool warning = false) inline
Definition at line 491 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 491 of file G4NistManager.hh
References G4NistMaterialBuilder::FindOrBuildMaterial(), and matBuilder.
Referenced by PHG4TTLDetector::BuildBarrelTTL(), CML2AccSaturn::buildMaterial_Kapton(), CML2AccSaturn::buildMaterial_SSteel(), CML2AccSaturn::buildMaterial_WNICU(), CML2AccSaturn::buildMaterial_XC10(), BuildMaterialWithNewDensity(), HadrontherapyModulator::BuildModulator(), DicomPhantomZSliceHeader::CheckMaterialExists(), Par01ParallelWorldForPion::Construct(), H02DetectorConstruction::Construct(), Par01DetectorConstruction::Construct(), ExTGDetectorConstructionWithCpp::Construct(), RE01DetectorConstruction::Construct(), B1DetectorConstruction::Construct(), ExGflash2DetectorConstruction::Construct(), GB07DetectorConstruction::Construct(), ExGflash1DetectorConstruction::Construct(), ExGflash3DetectorConstruction::Construct(), B3DetectorConstruction::Construct(), GB02DetectorConstruction::Construct(), GB06DetectorConstruction::Construct(), GB01DetectorConstruction::Construct(), STCyclotronDetectorConstruction::Construct(), GB04DetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2PhantomConstruction::Construct(), ExErrorDetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), CML2AcceleratorConstruction::Construct(), RE02DetectorConstruction::Construct(), GammaKnifeDetectorConstruction::ConstructBeamLine(), Collimator100BeamLine::ConstructCollimator100BeamLine(), Collimator40BeamLine::ConstructCollimator40BeamLine(), Collimator50BeamLine::ConstructCollimator50BeamLine(), Collimator60BeamLine::ConstructCollimator60BeamLine(), Collimator70BeamLine::ConstructCollimator70BeamLine(), Collimator80BeamLine::ConstructCollimator80BeamLine(), DetectorConstruction::ConstructMaterials(), TSDetectorConstruction::ConstructMaterials(), PHG4FCalDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4FPbScDetector::ConstructMe(), PassiveCarbonBeamLine::ConstructPassiveCarbonBeamLine(), PassiveProtonBeamLine::ConstructPassiveProtonBeamLine(), ExGflash2ParallelWorld::ConstructSD(), ExGflash1DetectorConstruction::ConstructSDandField(), PHG4ForwardDualReadoutDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTowerFCStyle(), TrentoPassiveProtonBeamLine::ConstructTrentoPassiveProtonBeamLine(), CML2WorldConstruction::create(), DNAParser::CreateLogicVolume(), F04Materials::CreateMaterials(), WLSMaterials::CreateMaterials(), ExN04DetectorConstruction::DefineMaterials(), XDetectorConstruction::DefineMaterials(), RE03DetectorConstruction::DefineMaterials(), RE04DetectorConstruction::DefineMaterials(), ElectronBenchmarkDetector::DefineMaterials(), B2aDetectorConstruction::DefineMaterials(), B2bDetectorConstruction::DefineMaterials(), ExUCNDetectorConstruction::DefineMaterials(), F06DetectorConstruction::DefineMaterials(), F05DetectorConstruction::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), FFDetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), HistoManager::EndOfRun(), Par01EMShowerModel::Explode(), export_G4NistManager(), G4tgbMaterialMgr::FindOrBuildG4Material(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), G4DNABrownianTransportation::G4DNABrownianTransportation(), G4MicroElecElasticModel::G4MicroElecElasticModel(), G4MicroElecInelasticModel::G4MicroElecInelasticModel(), G4MuElecElasticModel::G4MuElecElasticModel(), G4MuElecInelasticModel::G4MuElecInelasticModel(), PHG4Detector::GetDetectorMaterial(), ePHENIXRICH::ePHENIXRICHConstruction::GetDetectorMaterial(), F04Materials::GetMaterial(), WLSMaterials::GetMaterial(), XrayFluoNistMaterials::GetMaterial(), G4GDMLReadMaterials::GetMaterial(), HadrontherapyInteractionParameters::GetNistMaterial(), G4NeutronElectronElXsc::Initialise(), PHG4Reco::InitRun(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2AccSaturn::ionizationChamber(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2AccSaturn::Jaw2X(), CML2Acc2::Jaw2Y(), CML2AccSaturn::Jaw2Y(), main(), EICG4LumiDetector::MakeTower(), EICG4ZDCStructure::Materials(), CML2Acc2::mirror(), CML2Acc1::mirror(), CML2Acc1::MLC(), CML2Acc2::MLC(), DetectorConstruction::OtherMaterial(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), CML2AccSaturn::primaryCollimator(), DicomDetectorConstruction::ReadPhantomDataNew(), DetectorConstruction::SetAbsMaterial(), DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorMaterial(), B2aDetectorConstruction::SetChamberMaterial(), B2bDetectorConstruction::SetChamberMaterial(), DetectorConstruction::SetContainerMaterial(), DetectorConstruction::SetContainMaterial(), LaserDrivenBeamLine::SetDefaultDimensions(), Collimator100BeamLine::SetDefaultDimensions(), Collimator40BeamLine::SetDefaultDimensions(), Collimator60BeamLine::SetDefaultDimensions(), Collimator50BeamLine::SetDefaultDimensions(), Collimator80BeamLine::SetDefaultDimensions(), Collimator70BeamLine::SetDefaultDimensions(), PassiveCarbonBeamLine::SetDefaultDimensions(), TrentoPassiveProtonBeamLine::SetDefaultDimensions(), PassiveProtonBeamLine::SetDefaultDimensions(), F04DetectorConstruction::SetDegraderMaterial(), DetectorConstruction::SetDetectorMaterial(), DetectorConstruction::SetEcalMaterial(), STCyclotronDetectorConstruction::SetFoilMaterial(), DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGasMaterial(), DetectorConstruction::SetMaterial(), ExGflashDetectorConstruction::SetMaterial(), DetectorConstruction::SetTankMaterial(), DetectorConstruction::SetTarget1Material(), DetectorConstruction::SetTarget2Material(), B2bDetectorConstruction::SetTargetMaterial(), B2aDetectorConstruction::SetTargetMaterial(), DetectorConstruction::SetTargetMaterial(), STCyclotronDetectorConstruction::SetTargetMaterial(), F04DetectorConstruction::SetTargetMaterial(), ParallelWorld::SetupChemistryGeometry(), G4EmCalculator::SetupMaterial(), F04DetectorConstruction::SetWorldMaterial(), CML2Acc1::target(), CML2Acc2::target(), CML2AccSaturn::target(), CML2Acc1::vacuumWindow(), CML2Acc2::vacuumWindow(), CML2AccSaturn::vacuumWindow(), and HadrontherapyDetectorConstruction::VirtualLayer().
G4Material * G4NistManager::FindOrBuildSimpleMaterial (G4int Z, G4bool warning = false) inline
Definition at line 509 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 509 of file G4NistManager.hh
References G4NistMaterialBuilder::FindOrBuildSimpleMaterial(), and matBuilder.
Referenced by G4EmCalculator::CheckMaterial().
G4Material * G4NistManager::FindSimpleMaterial (G4int Z) const inline
Definition at line 501 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 501 of file G4NistManager.hh
References G4NistMaterialBuilder::FindSimpleMaterial(), and matBuilder.
G4double G4NistManager::GetA27 (G4int Z) const inline
Definition at line 603 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 603 of file G4NistManager.hh
References POWERA27, and Z.
Referenced by G4GammaConversionToMuons::ComputeCrossSectionPerAtom(), G4hBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4MuBremsstrahlungModel::G4MuBremsstrahlungModel(), G4WentzelOKandVIxSection::InitialiseA(), G4GammaConversionToMuons::PostStepDoIt(), G4AtimaEnergyLossModel::SetupParameters(), G4LindhardSorensenIonModel::SetupParameters(), and G4BetheBlochModel::SetupParameters().
G4double G4NistManager::GetAtomicMass (G4int Z, G4int N) const inline
Definition at line 399 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 399 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetAtomicMass().
Referenced by G4Isotope::G4Isotope().
G4double G4NistManager::GetAtomicMassAmu (const G4String & symb) const inline
Definition at line 376 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 376 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetAtomicMassAmu().
Referenced by G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4UPiNuclearCrossSection::BuildPhysicsTable(), G4CrossSectionPairGG::BuildPhysicsTable(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4AtimaFluctuations::Dispersion(), G4ElasticHadrNucleusHE::FillData(), G4TripathiCrossSection::GetElementCrossSection(), G4HadronInelasticDataSet::GetElementCrossSection(), G4HadronElasticDataSet::GetElementCrossSection(), G4CrossSectionPairGG::GetElementCrossSection(), G4PhotoNuclearCrossSection::GetElementCrossSection(), G4ElectroNuclearCrossSection::GetElementCrossSection(), G4CrossSectionElastic::GetElementCrossSection(), G4CrossSectionInelastic::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4ProtonInelasticCrossSection::GetProtonCrossSection(), G4NuclNuclDiffuseElastic::Initialise(), G4DiffuseElasticV2::Initialise(), G4DiffuseElastic::Initialise(), G4NeutronInelasticXS::Initialise(), G4ParticleInelasticXS::Initialise(), G4NeutronElasticXS::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4NuclNuclDiffuseElastic::InitialiseOnFly(), G4DiffuseElasticV2::InitialiseOnFly(), G4DiffuseElastic::InitialiseOnFly(), G4ComponentBarNucleonNucleusXsc::LoadData(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4WentzelOKandVIxSection::SampleSingleScattering(), G4ScreeningMottCrossSection::SetupKinematic(), and G4WentzelOKandVIxSection::SetupTarget().
G4double G4NistManager::GetAtomicMassAmu (G4int Z) const inline
Definition at line 383 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 383 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetAtomicMassAmu().
G4Element * G4NistManager::GetElement (size_t index) const inline
Definition at line 329 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 329 of file G4NistManager.hh
References G4Element::GetElementTable().
Referenced by export_G4NistManager().
G4ICRU90StoppingData * G4NistManager::GetICRU90StoppingData ()
Definition at line 237 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 237 of file G4NistManager.cc
References fICRU90, G4MUTEXLOCK, and G4MUTEXUNLOCK.
Referenced by G4BetheBlochModel::Initialise(), G4BraggIonModel::Initialise(), and G4BraggModel::Initialise().
G4double G4NistManager::GetIsotopeAbundance (G4int Z, G4int N) const inline
Definition at line 415 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 415 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetIsotopeAbundance().
Referenced by G4Element::AddNaturalIsotopes(), G4Evaporation::BreakFragment(), and G4ExcitationHandler::SortSecondaryFragment().
G4double G4NistManager::GetIsotopeMass (G4int Z, G4int N) const inline
Definition at line 391 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 391 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetIsotopeMass().
Referenced by export_G4NistManager().
G4double G4NistManager::GetLOGAMU (G4int Z) const inline
Definition at line 617 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 617 of file G4NistManager.hh
References LOGAZ, and Z.
G4double G4NistManager::GetLOGZ (G4int Z) const inline
Definition at line 610 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 610 of file G4NistManager.hh
References g4pow, and G4Pow::logZ().
Referenced by G4MuPairProductionModel::MaxSecondaryEnergyForElement(), G4MuPairProductionModel::SampleSecondaries(), and G4eBremParametrizedModel::SetCurrentElement().
G4Material * G4NistManager::GetMaterial (size_t index) const inline
Definition at line 467 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 467 of file G4NistManager.hh
References G4Material::GetMaterialTable().
Referenced by export_G4NistManager().
G4double G4NistManager::GetMeanIonisationEnergy (G4int Z) const inline
Definition at line 446 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 446 of file G4NistManager.hh
References G4NistMaterialBuilder::GetMeanIonisationEnergy(), and matBuilder.
Referenced by G4IonisParamElm::G4IonisParamElm().
const std::vector< G4String > & G4NistManager::GetNistElementNames () const inline
Definition at line 439 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 439 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetElementNames().
Referenced by G4Element::AddNaturalIsotopes().
G4int G4NistManager::GetNistFirstIsotopeN (G4int Z) const inline
Definition at line 423 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 423 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetNistFirstIsotopeN().
Referenced by G4Element::AddNaturalIsotopes().
const std::vector< G4String > & G4NistManager::GetNistMaterialNames () const inline
Definition at line 582 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 582 of file G4NistManager.hh
References G4NistMaterialBuilder::GetMaterialNames(), and matBuilder.
G4double G4NistManager::GetNominalDensity (G4int Z) const inline
Definition at line 453 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 453 of file G4NistManager.hh
References G4NistMaterialBuilder::GetNominalDensity(), and matBuilder.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
size_t G4NistManager::GetNumberOfElements () const inline
Definition at line 362 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 362 of file G4NistManager.hh
References nElements.
Referenced by export_G4NistManager().
size_t G4NistManager::GetNumberOfMaterials () const inline
Definition at line 322 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 322 of file G4NistManager.hh
References nMaterials.
Referenced by export_G4NistManager().
G4int G4NistManager::GetNumberOfNistIsotopes (G4int Z) const inline
Definition at line 431 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 431 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetNumberOfNistIsotopes().
Referenced by G4Element::AddNaturalIsotopes().
G4double G4NistManager::GetTotalElectronBindingEnergy (G4int Z) const inline
Definition at line 407 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 407 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetTotalElectronBindingEnergy().
G4int G4NistManager::GetVerbose () const inline
Definition at line 475 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 475 of file G4NistManager.hh
References verbose.
Referenced by export_G4NistManager().
G4int G4NistManager::GetZ (const G4String & symb) const inline
Definition at line 369 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 369 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::GetZ().
Referenced by export_G4NistManager().
G4double G4NistManager::GetZ13 (G4double Z) const inline
Definition at line 589 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 589 of file G4NistManager.hh
References G4Pow::A13(), and g4pow.
Referenced by G4GammaConversionToMuons::ComputeCrossSectionPerAtom(), G4hBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4MuBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4eBremParametrizedModel::ComputeParametrizedDXSectionPerAtom(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4MuPairProductionModel::MaxSecondaryEnergyForElement(), G4GammaConversionToMuons::PostStepDoIt(), and G4eBremParametrizedModel::SetCurrentElement().
G4double G4NistManager::GetZ13 (G4int Z) const inline
Definition at line 596 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 596 of file G4NistManager.hh
References g4pow, and G4Pow::Z13().
G4NistManager * G4NistManager::Instance (void) static
Definition at line 70 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 70 of file G4NistManager.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and instance.
Referenced by EICG4LumiDetector::AddCAL(), EICG4LumiDetector::AddLumiTracker(), G4Element::AddNaturalIsotopes(), PHG4TTLDetector::BuildBarrelTTL(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), CML2AccSaturn::buildMaterial_Kapton(), CML2AccSaturn::buildMaterial_SSteel(), CML2AccSaturn::buildMaterial_WNICU(), CML2AccSaturn::buildMaterial_XC10(), HadrontherapyModulator::BuildModulator(), G4UPiNuclearCrossSection::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), DicomPhantomZSliceHeader::CheckMaterialExists(), G4GammaConversionToMuons::ComputeCrossSectionPerAtom(), G4IonisParamMat::ComputeDensityEffectParameters(), Construct(), H02DetectorConstruction::Construct(), Par01ParallelWorldForPion::Construct(), Par01DetectorConstruction::Construct(), ExTGDetectorConstructionWithCpp::Construct(), RE01DetectorConstruction::Construct(), B1DetectorConstruction::Construct(), GB05DetectorConstruction::Construct(), GB07DetectorConstruction::Construct(), ExGflash2DetectorConstruction::Construct(), ExGflash1DetectorConstruction::Construct(), ExGflash3DetectorConstruction::Construct(), B3DetectorConstruction::Construct(), GB06DetectorConstruction::Construct(), GB01DetectorConstruction::Construct(), GB02DetectorConstruction::Construct(), STCyclotronDetectorConstruction::Construct(), GB04DetectorConstruction::Construct(), DetectorConstruction0::Construct(), ExGflashDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), ExErrorDetectorConstruction::Construct(), CML2PhantomConstruction::Construct(), CML2Ph_FullWater::Construct(), CML2AcceleratorConstruction::Construct(), RE02DetectorConstruction::Construct(), GammaKnifeDetectorConstruction::ConstructBeamLine(), Collimator100BeamLine::ConstructCollimator100BeamLine(), Collimator40BeamLine::ConstructCollimator40BeamLine(), Collimator50BeamLine::ConstructCollimator50BeamLine(), Collimator60BeamLine::ConstructCollimator60BeamLine(), Collimator70BeamLine::ConstructCollimator70BeamLine(), Collimator80BeamLine::ConstructCollimator80BeamLine(), B5DetectorConstruction::ConstructMaterials(), DetectorConstruction::ConstructMaterials(), TSDetectorConstruction::ConstructMaterials(), PHG4FCalDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4FPbScDetector::ConstructMe(), PassiveCarbonBeamLine::ConstructPassiveCarbonBeamLine(), PassiveProtonBeamLine::ConstructPassiveProtonBeamLine(), ExGflash2ParallelWorld::ConstructSD(), ExGflash1DetectorConstruction::ConstructSDandField(), PHG4ForwardDualReadoutDetector::ConstructTower(), PHG4ForwardDualReadoutDetector::ConstructTowerFCStyle(), TrentoPassiveProtonBeamLine::ConstructTrentoPassiveProtonBeamLine(), CML2WorldConstruction::create(), DNAParser::CreateLogicVolume(), XrayFluoNistMaterials::CreateMaterials(), ExN04DetectorConstruction::DefineMaterials(), XDetectorConstruction::DefineMaterials(), RE03DetectorConstruction::DefineMaterials(), B3DetectorConstruction::DefineMaterials(), RE04DetectorConstruction::DefineMaterials(), ElectronBenchmarkDetector::DefineMaterials(), B2aDetectorConstruction::DefineMaterials(), B2bDetectorConstruction::DefineMaterials(), ExUCNDetectorConstruction::DefineMaterials(), B4cDetectorConstruction::DefineMaterials(), B4dDetectorConstruction::DefineMaterials(), B4DetectorConstruction::DefineMaterials(), F06DetectorConstruction::DefineMaterials(), F05DetectorConstruction::DefineMaterials(), FFDetectorConstruction::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4AtimaFluctuations::Dispersion(), HistoManager::EndOfRun(), Par01EMShowerModel::Explode(), export_G4NistManager(), F04Materials::F04Materials(), G4tgbMaterialMgr::FindOrBuildG4Element(), G4tgbMaterialMgr::FindOrBuildG4Material(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4BetheBlochModel::G4BetheBlochModel(), G4CrossSectionDataStore::G4CrossSectionDataStore(), G4CrossSectionElastic::G4CrossSectionElastic(), G4CrossSectionInelastic::G4CrossSectionInelastic(), G4CrossSectionPairGG::G4CrossSectionPairGG(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4DNABrownianTransportation::G4DNABrownianTransportation(), G4eBremParametrizedModel::G4eBremParametrizedModel(), G4eCoulombScatteringModel::G4eCoulombScatteringModel(), G4ElasticHadrNucleusHE::G4ElasticHadrNucleusHE(), G4ElectroNuclearCrossSection::G4ElectroNuclearCrossSection(), G4EmCalculator::G4EmCalculator(), G4EmParameters::G4EmParameters(), G4EmSaturation::G4EmSaturation(), G4eSingleCoulombScatteringModel::G4eSingleCoulombScatteringModel(), G4Evaporation::G4Evaporation(), G4ExcitationHandler::G4ExcitationHandler(), G4HadronElasticDataSet::G4HadronElasticDataSet(), G4HadronInelasticDataSet::G4HadronInelasticDataSet(), G4hCoulombScatteringModel::G4hCoulombScatteringModel(), G4IonCoulombCrossSection::G4IonCoulombCrossSection(), G4IonCoulombScatteringModel::G4IonCoulombScatteringModel(), G4IonisParamElm::G4IonisParamElm(), G4Isotope::G4Isotope(), G4LindhardSorensenIonModel::G4LindhardSorensenIonModel(), G4Material::G4Material(), G4MicroElecElasticModel::G4MicroElecElasticModel(), G4MicroElecInelasticModel::G4MicroElecInelasticModel(), G4MuBremsstrahlungModel::G4MuBremsstrahlungModel(), G4MuElecElasticModel::G4MuElecElasticModel(), G4MuElecInelasticModel::G4MuElecInelasticModel(), G4MuPairProductionModel::G4MuPairProductionModel(), G4NeutronElasticXS::G4NeutronElasticXS(), G4NeutronInelasticXS::G4NeutronInelasticXS(), G4ParticleInelasticXS::G4ParticleInelasticXS(), G4PhotoNuclearCrossSection::G4PhotoNuclearCrossSection(), G4ProtonInelasticCrossSection::G4ProtonInelasticCrossSection(), G4ScreeningMottCrossSection::G4ScreeningMottCrossSection(), G4WentzelOKandVIxSection::G4WentzelOKandVIxSection(), G4WentzelVIRelModel::G4WentzelVIRelModel(), PHG4Detector::GetDetectorElement(), PHG4Detector::GetDetectorMaterial(), ePHENIXRICH::ePHENIXRICHConstruction::GetDetectorMaterial(), G4GDMLReadMaterials::GetElement(), G4TripathiCrossSection::GetElementCrossSection(), G4NeutronInelasticCrossSection::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsSihverCrossSection::GetElementCrossSection(), G4IonsShenCrossSection::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), XrayFluoNistMaterials::GetMaterial(), G4GDMLReadMaterials::GetMaterial(), G4MuonMinusBoundDecay::GetMuonDecayRate(), HadrontherapyInteractionParameters::GetNistMaterial(), G4NeutronElectronElXsc::Initialise(), G4NuclNuclDiffuseElastic::Initialise(), G4DiffuseElasticV2::Initialise(), G4DiffuseElastic::Initialise(), G4BraggIonModel::Initialise(), G4BraggModel::Initialise(), G4NuclNuclDiffuseElastic::InitialiseOnFly(), G4DiffuseElasticV2::InitialiseOnFly(), G4DiffuseElastic::InitialiseOnFly(), PHG4Reco::InitRun(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2AccSaturn::ionizationChamber(), G4TripathiLightCrossSection::IsElementApplicable(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2AccSaturn::Jaw2X(), CML2Acc2::Jaw2Y(), CML2AccSaturn::Jaw2Y(), G4ComponentBarNucleonNucleusXsc::LoadData(), main(), EICG4LumiDetector::MakeTower(), EICG4ZDCStructure::Materials(), CML2Acc2::mirror(), CML2Acc1::mirror(), CML2Acc1::MLC(), CML2Acc2::MLC(), DetectorConstruction::OtherMaterial(), G4GammaConversionToMuons::PostStepDoIt(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), CML2AccSaturn::primaryCollimator(), DicomDetectorConstruction::ReadPhantomDataNew(), DetectorConstruction::SetAbsMaterial(), DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorMaterial(), DetectorConstruction::SetBoxMaterial(), B2aDetectorConstruction::SetChamberMaterial(), B2bDetectorConstruction::SetChamberMaterial(), DetectorConstruction::SetContainerMaterial(), DetectorConstruction::SetContainMaterial(), LaserDrivenBeamLine::SetDefaultDimensions(), Collimator80BeamLine::SetDefaultDimensions(), Collimator100BeamLine::SetDefaultDimensions(), Collimator70BeamLine::SetDefaultDimensions(), Collimator60BeamLine::SetDefaultDimensions(), Collimator40BeamLine::SetDefaultDimensions(), Collimator50BeamLine::SetDefaultDimensions(), PassiveCarbonBeamLine::SetDefaultDimensions(), TrentoPassiveProtonBeamLine::SetDefaultDimensions(), PassiveProtonBeamLine::SetDefaultDimensions(), F04DetectorConstruction::SetDegraderMaterial(), DetectorConstruction::SetDetectorMaterial(), IORTDetectorConstruction::SetDiscoMaterialIORT(), IORTDetectorConstruction::SetDiscoMaterialIORT1(), DetectorConstruction::SetEcalMaterial(), STCyclotronDetectorConstruction::SetFoilMaterial(), DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGasMaterial(), DetectorConstruction::SetMaterial(), DetectorConstruction0::SetMaterial(), ExGflashDetectorConstruction::SetMaterial(), G4IonisParamMat::SetMeanExcitationEnergy(), HadrontherapyModulator::SetModulatorMaterial(), IORTDetectorConstruction::SetPhantomMaterial(), HadrontherapyDetectorConstruction::SetPhantomMaterial(), PassiveCarbonBeamLine::SetRippleFilterMaterial(), PassiveProtonBeamLine::SetRSMaterial(), TrentoPassiveProtonBeamLine::SetScattererMaterial(), DetectorConstruction::SetTankMaterial(), DetectorConstruction::SetTarget1Material(), DetectorConstruction::SetTarget2Material(), B2bDetectorConstruction::SetTargetMaterial(), B2aDetectorConstruction::SetTargetMaterial(), DetectorConstruction::SetTargetMaterial(), STCyclotronDetectorConstruction::SetTargetMaterial(), F04DetectorConstruction::SetTargetMaterial(), ParallelWorld::SetupChemistryGeometry(), DetectorConstruction::SetWorldMaterial(), F04DetectorConstruction::SetWorldMaterial(), CML2Acc1::target(), CML2Acc2::target(), CML2AccSaturn::target(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), STCyclotronDetectorConstruction::UpdateMaterial(), CML2Acc1::vacuumWindow(), CML2Acc2::vacuumWindow(), CML2AccSaturn::vacuumWindow(), HadrontherapyDetectorConstruction::VirtualLayer(), and WLSMaterials::WLSMaterials().
void G4NistManager::ListMaterials (const G4String & list) const inline
Definition at line 574 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 574 of file G4NistManager.hh
References G4NistMaterialBuilder::ListMaterials(), and matBuilder.
Referenced by export_G4NistManager(), and G4NistMessenger::SetNewValue().
void G4NistManager::PrintElement (G4int Z) const inline
Definition at line 460 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 460 of file G4NistManager.hh
References elmBuilder, and G4NistElementBuilder::PrintElement().
Referenced by G4NistMessenger::SetNewValue().
void G4NistManager::PrintElement (const G4String & symbol) const
Definition at line 161 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 161 of file G4NistManager.cc
References elmBuilder, G4NistElementBuilder::GetZ(), and G4NistElementBuilder::PrintElement().
void G4NistManager::PrintG4Element (const G4String & name) const
Definition at line 169 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 169 of file G4NistManager.cc
References G4cout, G4endl, G4Element::GetElementTable(), and G4Element::GetName().
Referenced by export_G4NistManager(), and G4NistMessenger::SetNewValue().
void G4NistManager::PrintG4Material (const G4String & name) const
Definition at line 183 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 183 of file G4NistManager.cc
References G4cout, G4endl, G4Material::GetMaterialTable(), G4Material::GetName(), and mat.
Referenced by export_G4NistManager(), and G4NistMessenger::SetNewValue().
void G4NistManager::SetDensityEffectCalculatorFlag (const G4String & mname, G4bool val)
Definition at line 255 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 255 of file G4NistManager.cc
References FindMaterial(), G4MUTEXLOCK, G4MUTEXUNLOCK, mat, and materials.
Referenced by G4NistMessenger::SetNewValue().
void G4NistManager::SetDensityEffectCalculatorFlag (G4Material * mat, G4bool val)
Definition at line 276 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 276 of file G4NistManager.cc
References G4Material::ComputeDensityEffectOnFly().
void G4NistManager::SetVerbose (G4int val)
Definition at line 197 of file G4NistManager.cc.
View newest version in sPHENIX GitHub at line 197 of file G4NistManager.cc
References elmBuilder, G4MUTEXLOCK, G4MUTEXUNLOCK, matBuilder, G4NistElementBuilder::SetVerbose(), G4NistMaterialBuilder::SetVerbose(), and verbose.
Referenced by XrayFluoNistMaterials::CreateMaterials(), ElectronBenchmarkDetector::DefineMaterials(), export_G4NistManager(), F04Materials::F04Materials(), XrayFluoNistMaterials::GetMaterial(), G4NistMessenger::SetNewValue(), and WLSMaterials::WLSMaterials().
Member Data Documentation
std::vector<G4Element*> G4NistManager::elements private
Definition at line 298 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 298 of file G4NistManager.hh
G4NistElementBuilder* G4NistManager::elmBuilder private
Definition at line 302 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 302 of file G4NistManager.hh
Referenced by FindElement(), FindOrBuildElement(), G4NistManager(), GetAtomicMass(), GetAtomicMassAmu(), GetIsotopeAbundance(), GetIsotopeMass(), GetNistElementNames(), GetNistFirstIsotopeN(), GetNumberOfNistIsotopes(), GetTotalElectronBindingEnergy(), GetZ(), PrintElement(), SetVerbose(), and ~G4NistManager().
G4ICRU90StoppingData* G4NistManager::fICRU90 private
Definition at line 301 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 301 of file G4NistManager.hh
Referenced by G4NistManager(), GetICRU90StoppingData(), and ~G4NistManager().
G4Pow* G4NistManager::g4pow private
Definition at line 305 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 305 of file G4NistManager.hh
Referenced by G4NistManager(), GetLOGZ(), and GetZ13().
G4NistManager * G4NistManager::instance = nullptr static private
Definition at line 296 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 296 of file G4NistManager.hh
Referenced by Instance().
G4double G4NistManager::LOGAZ[101] private
Definition at line 308 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 308 of file G4NistManager.hh
Referenced by G4NistManager(), and GetLOGAMU().
G4NistMaterialBuilder* G4NistManager::matBuilder private
Definition at line 303 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 303 of file G4NistManager.hh
Referenced by ConstructNewGasMaterial(), ConstructNewIdealGasMaterial(), ConstructNewMaterial(), FindMaterial(), FindOrBuildMaterial(), FindOrBuildSimpleMaterial(), FindSimpleMaterial(), G4NistManager(), GetMeanIonisationEnergy(), GetNistMaterialNames(), GetNominalDensity(), ListMaterials(), SetVerbose(), and ~G4NistManager().
std::vector<G4Material*> G4NistManager::materials private
Definition at line 299 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 299 of file G4NistManager.hh
Referenced by SetDensityEffectCalculatorFlag().
G4NistMessenger* G4NistManager::messenger private
Definition at line 304 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 304 of file G4NistManager.hh
Referenced by G4NistManager(), and ~G4NistManager().
size_t G4NistManager::nElements private
Definition at line 310 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 310 of file G4NistManager.hh
Referenced by G4NistManager(), and GetNumberOfElements().
size_t G4NistManager::nMaterials private
Definition at line 311 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 311 of file G4NistManager.hh
Referenced by G4NistManager(), and GetNumberOfMaterials().
G4double G4NistManager::POWERA27[101] private
Definition at line 307 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 307 of file G4NistManager.hh
Referenced by G4NistManager(), and GetA27().
G4int G4NistManager::verbose private
Definition at line 312 of file G4NistManager.hh.
View newest version in sPHENIX GitHub at line 312 of file G4NistManager.hh
Referenced by G4NistManager(), GetVerbose(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4NistManager.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4NistManager.cc