ECCE @ EIC Software: TSDetectorConstruction Class Reference
TSDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/include/TSDetectorConstruction.hh>
Public Types
typedef std::map< G4String,
G4Material * > MaterialCollection_t
typedef std::set
< G4LogicalVolume * > ScoringVolumes_t
Public Member Functions
TSDetectorConstruction ()
virtual ~TSDetectorConstruction ()
G4VPhysicalVolume * Construct ()
const G4ThreeVector & GetWorldDimensions () const
const ScoringVolumes_t & GetScoringVolumes () const
const G4String & GetMFDName () const
G4int GetTotalTargets () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Static Public Member Functions
static TSDetectorConstruction * Instance ()
Protected Member Functions
virtual MaterialCollection_t ConstructMaterials ()
virtual G4VPhysicalVolume * ConstructWorld (const MaterialCollection_t &)
virtual void ConstructSDandField ()
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Private Attributes
G4VPhysicalVolume * fWorldPhys
ScoringVolumes_t fScoringVolumes
G4String fWorldMaterialName
G4String fTargetMaterialName
G4String fCasingMaterialName
G4ThreeVector fWorldDim
G4ThreeVector fTargetDim
G4ThreeVector fTargetSections
G4String fMfdName
Static Private Attributes
static TSDetectorConstruction * fgInstance = 0
Detailed Description
Definition at line 73 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file TSDetectorConstruction.hh
Member Typedef Documentation
typedef std::map<G4String, G4Material*> TSDetectorConstruction::MaterialCollection_t
Definition at line 76 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file TSDetectorConstruction.hh
typedef std::set<G4LogicalVolume*> TSDetectorConstruction::ScoringVolumes_t
Definition at line 77 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file TSDetectorConstruction.hh
Constructor & Destructor Documentation
TSDetectorConstruction::TSDetectorConstruction ()
Definition at line 91 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 91 of file TSDetectorConstruction.cc
References fgInstance.
TSDetectorConstruction::~TSDetectorConstruction () virtual
Definition at line 106 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 106 of file TSDetectorConstruction.cc
References fgInstance.
Member Function Documentation
G4VPhysicalVolume * TSDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 113 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 113 of file TSDetectorConstruction.cc
References ConstructMaterials(), and ConstructWorld().
TSDetectorConstruction::MaterialCollection_t TSDetectorConstruction::ConstructMaterials () protected virtual
Definition at line 121 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 121 of file TSDetectorConstruction.cc
References fCasingMaterialName, G4NistManager::FindOrBuildMaterial(), fTargetMaterialName, fWorldMaterialName, G4NistManager::Instance(), and G4TrackingService::materials.
Referenced by Construct().
void TSDetectorConstruction::ConstructSDandField () protected virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 276 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 276 of file TSDetectorConstruction.cc
References G4SDManager::AddNewDetector(), edep, fMfdName, fScoringVolumes, G4SDManager::GetSDMpointer(), G4MultiFunctionalDetector::RegisterPrimitive(), and G4VUserDetectorConstruction::SetSensitiveDetector().
G4VPhysicalVolume * TSDetectorConstruction::ConstructWorld (const MaterialCollection_t & materials) protected virtual
Definition at line 136 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 136 of file TSDetectorConstruction.cc
References dx, dy, dz, fScoringVolumes, fTargetDim, fTargetSections, fWorldDim, fWorldPhys, k, G4VisAttributes::SetForceSolid(), G4VisAttributes::SetForceWireframe(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Construct().
const G4String& TSDetectorConstruction::GetMFDName () const inline
Definition at line 90 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file TSDetectorConstruction.hh
References fMfdName.
const ScoringVolumes_t& TSDetectorConstruction::GetScoringVolumes () const inline
Definition at line 88 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file TSDetectorConstruction.hh
References fScoringVolumes.
G4int TSDetectorConstruction::GetTotalTargets () const inline
Definition at line 91 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file TSDetectorConstruction.hh
References fTargetSections, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
const G4ThreeVector& TSDetectorConstruction::GetWorldDimensions () const inline
Definition at line 87 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file TSDetectorConstruction.hh
References fWorldDim.
Referenced by TSPrimaryGeneratorAction::GeneratePrimaries().
TSDetectorConstruction * TSDetectorConstruction::Instance (void) static
Definition at line 84 of file TSDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 84 of file TSDetectorConstruction.cc
Referenced by TSRun::ConstructMFD(), and TSPrimaryGeneratorAction::GeneratePrimaries().
Member Data Documentation
G4String TSDetectorConstruction::fCasingMaterialName private
Definition at line 105 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file TSDetectorConstruction.hh
Referenced by ConstructMaterials().
TSDetectorConstruction * TSDetectorConstruction::fgInstance = 0 static private
Definition at line 100 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file TSDetectorConstruction.hh
Referenced by TSDetectorConstruction(), and ~TSDetectorConstruction().
G4String TSDetectorConstruction::fMfdName private
Definition at line 109 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file TSDetectorConstruction.hh
Referenced by ConstructSDandField(), and GetMFDName().
ScoringVolumes_t TSDetectorConstruction::fScoringVolumes private
Definition at line 102 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file TSDetectorConstruction.hh
Referenced by ConstructSDandField(), ConstructWorld(), and GetScoringVolumes().
G4ThreeVector TSDetectorConstruction::fTargetDim private
Definition at line 107 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file TSDetectorConstruction.hh
Referenced by ConstructWorld().
G4String TSDetectorConstruction::fTargetMaterialName private
Definition at line 104 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file TSDetectorConstruction.hh
Referenced by ConstructMaterials().
G4ThreeVector TSDetectorConstruction::fTargetSections private
Definition at line 108 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 108 of file TSDetectorConstruction.hh
Referenced by ConstructWorld(), and GetTotalTargets().
G4ThreeVector TSDetectorConstruction::fWorldDim private
Definition at line 106 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file TSDetectorConstruction.hh
Referenced by ConstructWorld(), and GetWorldDimensions().
G4String TSDetectorConstruction::fWorldMaterialName private
Definition at line 103 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file TSDetectorConstruction.hh
Referenced by ConstructMaterials().
G4VPhysicalVolume* TSDetectorConstruction::fWorldPhys private
Definition at line 101 of file TSDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file TSDetectorConstruction.hh
Referenced by ConstructWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/include/TSDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/src/TSDetectorConstruction.cc