ECCE @ EIC Software: G4QuadrangularFacet Class Reference
G4QuadrangularFacet Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4QuadrangularFacet.hh>
Public Member Functions
G4QuadrangularFacet (const G4ThreeVector &Pt0, const G4ThreeVector &vt1, const G4ThreeVector &vt2, const G4ThreeVector &vt3, G4FacetVertexType)
G4QuadrangularFacet (const G4QuadrangularFacet &right)
~G4QuadrangularFacet ()
G4QuadrangularFacet & operator= (const G4QuadrangularFacet &right)
G4VFacet * GetClone ()
G4ThreeVector Distance (const G4ThreeVector &p)
G4double Distance (const G4ThreeVector &p, G4double minDist)
G4double Distance (const G4ThreeVector &p, G4double minDist, const G4bool outgoing)
G4double Extent (const G4ThreeVector axis)
G4bool Intersect (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool outgoing, G4double &distance, G4double &distFromSurface, G4ThreeVector &normal)
G4ThreeVector GetSurfaceNormal () const
G4double GetArea () const
G4ThreeVector GetPointOnFace () const
G4GeometryType GetEntityType () const
G4bool IsDefined () const
G4int GetNumberOfVertices () const
G4ThreeVector GetVertex (G4int i) const
void SetVertex (G4int i, const G4ThreeVector &val)
void SetVertices (std::vector< G4ThreeVector > *v)
G4double GetRadius () const
G4ThreeVector GetCircumcentre () const
Public Member Functions inherited from G4VFacet
G4VFacet ()
virtual ~G4VFacet ()
G4bool operator== (const G4VFacet &right) const
void ApplyTranslation (const G4ThreeVector v)
std::ostream & StreamInfo (std::ostream &os) const
G4bool IsInside (const G4ThreeVector &p) const
Private Member Functions
G4int GetVertexIndex (G4int i) const
void SetVertexIndex (G4int i, G4int val)
G4int AllocatedMemory ()
Private Attributes
G4double fRadius = 0.0
G4ThreeVector fCircumcentre
G4TriangularFacet fFacet1
G4TriangularFacet fFacet2
Additional Inherited Members
Protected Attributes inherited from G4VFacet
G4double kCarTolerance
Static Protected Attributes inherited from G4VFacet
static const G4double dirTolerance = 1.0E-14
Detailed Description
Definition at line 61 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 61 of file G4QuadrangularFacet.hh
Constructor & Destructor Documentation
G4QuadrangularFacet::G4QuadrangularFacet (const G4ThreeVector & Pt0, const G4ThreeVector & vt1, const G4ThreeVector & vt2, const G4ThreeVector & vt3, G4FacetVertexType vertexType)
Definition at line 51 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 51 of file G4QuadrangularFacet.cc
References ABSOLUTE, CLHEP::Hep3Vector::cross(), Acts::VectorHelpers::cross(), Acts::Test::delta, CLHEP::Hep3Vector::dot(), e1, e2, e3, epsilon(), fCircumcentre, fFacet1, fFacet2, fRadius, G4endl, G4Exception(), GetVertex(), h1, h2, h3, JustWarning, G4VFacet::kCarTolerance, kInfinity, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), max, message(), CLHEP::normal(), s1, G4TriangularFacet::SetSurfaceNormal(), SetVertex(), smax, t, and CLHEP::Hep3Vector::unit().
Referenced by GetClone().
G4QuadrangularFacet::G4QuadrangularFacet (const G4QuadrangularFacet & right)
Definition at line 215 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 215 of file G4QuadrangularFacet.cc
References fFacet1, fFacet2, and fRadius.
G4QuadrangularFacet::~G4QuadrangularFacet ()
Definition at line 209 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 209 of file G4QuadrangularFacet.cc
Member Function Documentation
G4int G4QuadrangularFacet::AllocatedMemory () inline private virtual
Implements G4VFacet.
Definition at line 199 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 199 of file G4QuadrangularFacet.hh
References G4TriangularFacet::AllocatedMemory(), fFacet1, and fFacet2.
G4ThreeVector G4QuadrangularFacet::Distance (const G4ThreeVector & p)
Definition at line 249 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 249 of file G4QuadrangularFacet.cc
References G4TriangularFacet::Distance(), fFacet1, fFacet2, CLHEP::Hep3Vector::mag2(), v1, and v2.
Referenced by Distance().
G4double G4QuadrangularFacet::Distance (const G4ThreeVector & p, G4double minDist) virtual
Implements G4VFacet.
Definition at line 260 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 260 of file G4QuadrangularFacet.cc
References Distance(), and CLHEP::Hep3Vector::mag().
G4double G4QuadrangularFacet::Distance (const G4ThreeVector & p, G4double minDist, const G4bool outgoing) virtual
Implements G4VFacet.
Definition at line 269 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 269 of file G4QuadrangularFacet.cc
References dir, G4VFacet::dirTolerance, Distance(), CLHEP::Hep3Vector::dot(), GetSurfaceNormal(), kInfinity, CLHEP::Hep3Vector::mag(), and v.
G4double G4QuadrangularFacet::Extent (const G4ThreeVector axis) virtual
Implements G4VFacet.
Definition at line 286 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 286 of file G4QuadrangularFacet.cc
References CLHEP::Hep3Vector::dot(), GetVertex(), and G4InuclParticleNames::sp.
G4double G4QuadrangularFacet::GetArea () const virtual
Implements G4VFacet.
Definition at line 335 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 335 of file G4QuadrangularFacet.cc
References fFacet1, fFacet2, and G4TriangularFacet::GetArea().
G4ThreeVector G4QuadrangularFacet::GetCircumcentre () const inline virtual
Implements G4VFacet.
Definition at line 135 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 135 of file G4QuadrangularFacet.hh
References fCircumcentre.
G4VFacet * G4QuadrangularFacet::GetClone () virtual
Implements G4VFacet.
Definition at line 239 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 239 of file G4QuadrangularFacet.cc
References ABSOLUTE, c, G4QuadrangularFacet(), and GetVertex().
G4String G4QuadrangularFacet::GetEntityType () const virtual
Implements G4VFacet.
Definition at line 343 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 343 of file G4QuadrangularFacet.cc
G4int G4QuadrangularFacet::GetNumberOfVertices () const inline virtual
Implements G4VFacet.
Definition at line 119 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 119 of file G4QuadrangularFacet.hh
G4ThreeVector G4QuadrangularFacet::GetPointOnFace () const virtual
Implements G4VFacet.
Definition at line 323 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 323 of file G4QuadrangularFacet.cc
References fFacet1, fFacet2, G4UniformRand, G4TriangularFacet::GetArea(), G4TriangularFacet::GetPointOnFace(), and s1.
G4double G4QuadrangularFacet::GetRadius () const inline virtual
Implements G4VFacet.
Definition at line 130 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 130 of file G4QuadrangularFacet.hh
References fRadius.
G4ThreeVector G4QuadrangularFacet::GetSurfaceNormal () const virtual
Implements G4VFacet.
Definition at line 350 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 350 of file G4QuadrangularFacet.cc
References fFacet1, and G4TriangularFacet::GetSurfaceNormal().
Referenced by Distance().
G4ThreeVector G4QuadrangularFacet::GetVertex (G4int i) const inline virtual
Implements G4VFacet.
Definition at line 124 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 124 of file G4QuadrangularFacet.hh
References fFacet1, fFacet2, and G4TriangularFacet::GetVertex().
Referenced by Extent(), G4QuadrangularFacet(), and GetClone().
G4int G4QuadrangularFacet::GetVertexIndex (G4int i) const inline private virtual
Implements G4VFacet.
Definition at line 172 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 172 of file G4QuadrangularFacet.hh
References fFacet1, fFacet2, and G4TriangularFacet::GetVertexIndex().
G4bool G4QuadrangularFacet::Intersect (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool outgoing, G4double & distance, G4double & distFromSurface, G4ThreeVector & normal) virtual
Implements G4VFacet.
Definition at line 300 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 300 of file G4QuadrangularFacet.cc
References fFacet1, fFacet2, G4TriangularFacet::Intersect(), kInfinity, and CLHEP::Hep3Vector::set().
G4bool G4QuadrangularFacet::IsDefined () const inline virtual
Implements G4VFacet.
Definition at line 167 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 167 of file G4QuadrangularFacet.hh
References fFacet1, and G4TriangularFacet::IsDefined().
G4QuadrangularFacet & G4QuadrangularFacet::operator= (const G4QuadrangularFacet & right)
Definition at line 226 of file G4QuadrangularFacet.cc.
View newest version in sPHENIX GitHub at line 226 of file G4QuadrangularFacet.cc
References fFacet1, fFacet2, and fRadius.
void G4QuadrangularFacet::SetVertex (G4int i, const G4ThreeVector & val) inline virtual
Implements G4VFacet.
Definition at line 140 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 140 of file G4QuadrangularFacet.hh
References fFacet1, fFacet2, and G4TriangularFacet::SetVertex().
Referenced by G4QuadrangularFacet().
void G4QuadrangularFacet::SetVertexIndex (G4int i, G4int val) inline private virtual
Implements G4VFacet.
Definition at line 178 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 178 of file G4QuadrangularFacet.hh
References fFacet1, fFacet2, and G4TriangularFacet::SetVertexIndex().
void G4QuadrangularFacet::SetVertices (std::vector< G4ThreeVector > * v) inline virtual
Implements G4VFacet.
Definition at line 161 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 161 of file G4QuadrangularFacet.hh
References fFacet1, fFacet2, and G4TriangularFacet::SetVertices().
Member Data Documentation
G4ThreeVector G4QuadrangularFacet::fCircumcentre private
Definition at line 110 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 110 of file G4QuadrangularFacet.hh
Referenced by G4QuadrangularFacet(), and GetCircumcentre().
G4TriangularFacet G4QuadrangularFacet::fFacet1 private
Definition at line 112 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 112 of file G4QuadrangularFacet.hh
Referenced by AllocatedMemory(), Distance(), G4QuadrangularFacet(), GetArea(), GetPointOnFace(), GetSurfaceNormal(), GetVertex(), GetVertexIndex(), Intersect(), IsDefined(), operator=(), SetVertex(), SetVertexIndex(), and SetVertices().
G4TriangularFacet G4QuadrangularFacet::fFacet2 private
Definition at line 112 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 112 of file G4QuadrangularFacet.hh
Referenced by AllocatedMemory(), Distance(), G4QuadrangularFacet(), GetArea(), GetPointOnFace(), GetVertex(), GetVertexIndex(), Intersect(), operator=(), SetVertex(), SetVertexIndex(), and SetVertices().
G4double G4QuadrangularFacet::fRadius = 0.0 private
Definition at line 108 of file G4QuadrangularFacet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4QuadrangularFacet.hh
Referenced by G4QuadrangularFacet(), GetRadius(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4QuadrangularFacet.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4QuadrangularFacet.cc