ECCE @ EIC Software: CCalSensitiveConfiguration Class Reference
CCalSensitiveConfiguration Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSensitiveConfiguration.hh>
Classes
struct GCInfo
Public Member Functions
~CCalSensitiveConfiguration ()
G4int getSensitiveFlag (const G4String &n)
G4String getFileName (const G4String &n)
Static Public Member Functions
static CCalSensitiveConfiguration * getInstance ()
Private Types
typedef std::map< G4String,
GCInfo, std::less< G4String > > CCalSensitiveConfTable
Private Member Functions
CCalSensitiveConfiguration ()
Private Attributes
CCalSensitiveConfTable theConfiguration
Static Private Attributes
static CCalSensitiveConfiguration * instance = 0
Detailed Description
Definition at line 38 of file CCalSensitiveConfiguration.hh.
View newest version in sPHENIX GitHub at line 38 of file CCalSensitiveConfiguration.hh
Member Typedef Documentation
typedef std::map<G4String, GCInfo, std::less<G4String> > CCalSensitiveConfiguration::CCalSensitiveConfTable private
Definition at line 45 of file CCalSensitiveConfiguration.hh.
View newest version in sPHENIX GitHub at line 45 of file CCalSensitiveConfiguration.hh
Constructor & Destructor Documentation
CCalSensitiveConfiguration::~CCalSensitiveConfiguration () inline
Definition at line 48 of file CCalSensitiveConfiguration.hh.
View newest version in sPHENIX GitHub at line 48 of file CCalSensitiveConfiguration.hh
CCalSensitiveConfiguration::CCalSensitiveConfiguration () private
Definition at line 83 of file CCalSensitiveConfiguration.cc.
View newest version in sPHENIX GitHub at line 83 of file CCalSensitiveConfiguration.cc
References FatalException, CCalSensitiveConfiguration::GCInfo::FileName, G4cout, G4endl, G4Exception(), jump(), openGeomFile(), readName(), CCalSensitiveConfiguration::GCInfo::SensitiveFlag, tab(), and theConfiguration.
Referenced by getInstance().
Member Function Documentation
G4String CCalSensitiveConfiguration::getFileName (const G4String & n)
Definition at line 67 of file CCalSensitiveConfiguration.cc.
View newest version in sPHENIX GitHub at line 67 of file CCalSensitiveConfiguration.cc
References G4cerr, G4endl, it, and theConfiguration.
CCalSensitiveConfiguration * CCalSensitiveConfiguration::getInstance () static
Definition at line 43 of file CCalSensitiveConfiguration.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalSensitiveConfiguration.cc
References CCalSensitiveConfiguration(), and instance.
Referenced by CCalG4Able::CCalG4Able(), and CCalDetectorConstruction::Construct().
G4int CCalSensitiveConfiguration::getSensitiveFlag (const G4String & n)
Definition at line 51 of file CCalSensitiveConfiguration.cc.
View newest version in sPHENIX GitHub at line 51 of file CCalSensitiveConfiguration.cc
References G4cerr, G4endl, it, and theConfiguration.
Referenced by CCalG4Able::CCalG4Able().
Member Data Documentation
CCalSensitiveConfiguration * CCalSensitiveConfiguration::instance = 0 static private
Definition at line 59 of file CCalSensitiveConfiguration.hh.
View newest version in sPHENIX GitHub at line 59 of file CCalSensitiveConfiguration.hh
Referenced by getInstance().
CCalSensitiveConfTable CCalSensitiveConfiguration::theConfiguration private
Definition at line 60 of file CCalSensitiveConfiguration.hh.
View newest version in sPHENIX GitHub at line 60 of file CCalSensitiveConfiguration.hh
Referenced by CCalSensitiveConfiguration(), getFileName(), and getSensitiveFlag().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSensitiveConfiguration.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalSensitiveConfiguration.cc