ECCE @ EIC Software: G4NucleiPropertiesTableAME12 Class Reference
G4NucleiPropertiesTableAME12 Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4NucleiPropertiesTableAME12.hh>
Public Types
enum { nEntries = 3353, MaxA = 295, ZMax = 120 }
Public Member Functions
~G4NucleiPropertiesTableAME12 ()
Private Member Functions
G4NucleiPropertiesTableAME12 ()
Static Private Member Functions
static G4double GetMassExcess (G4int Z, G4int A)
static G4double GetAtomicMass (G4int Z, G4int A)
static G4double GetNuclearMass (G4int Z, G4int A)
static G4double GetBindingEnergy (G4int Z, G4int A)
static G4double GetBetaDecayEnergy (G4int Z, G4int A)
static G4bool IsInTable (G4int Z, G4int A)
static G4int MaxZ (G4int A)
static G4int MinZ (G4int A)
static G4int GetIndex (G4int Z, G4int A)
Static Private Attributes
static const G4double MassExcess [nEntries]
static const G4double BetaEnergy [nEntries]
static const G4int indexArray [2][nEntries]
static const G4int shortTable [MaxA+1]
static G4ThreadLocal G4double electronMass [ZMax]
static G4ThreadLocal G4bool isIntialized = false
Friends
class G4NucleiProperties
Detailed Description
Definition at line 56 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 56 of file G4NucleiPropertiesTableAME12.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
nEntries
MaxA
ZMax
Definition at line 69 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NucleiPropertiesTableAME12.hh
Constructor & Destructor Documentation
G4NucleiPropertiesTableAME12::G4NucleiPropertiesTableAME12 () private
Definition at line 59 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 59 of file G4NucleiPropertiesTableAME12.cc
G4NucleiPropertiesTableAME12::~G4NucleiPropertiesTableAME12 () inline
Definition at line 66 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 66 of file G4NucleiPropertiesTableAME12.hh
Member Function Documentation
G4double G4NucleiPropertiesTableAME12::GetAtomicMass (G4int Z, G4int A) static private
Definition at line 154 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 154 of file G4NucleiPropertiesTableAME12.cc
References source.hepunit::amu_c2, GetIndex(), keV, and MassExcess.
Referenced by G4NucleiProperties::GetAtomicMass(), and GetNuclearMass().
G4double G4NucleiPropertiesTableAME12::GetBetaDecayEnergy (G4int Z, G4int A) static private
Definition at line 144 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 144 of file G4NucleiPropertiesTableAME12.cc
References BetaEnergy, GetIndex(), and keV.
G4double G4NucleiPropertiesTableAME12::GetBindingEnergy (G4int Z, G4int A) static private
Definition at line 134 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 134 of file G4NucleiPropertiesTableAME12.cc
References GetIndex(), keV, and MassExcess.
Referenced by G4NucleiProperties::GetBindingEnergy().
G4int G4NucleiPropertiesTableAME12::GetIndex (G4int Z, G4int A) static private
Definition at line 63 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 63 of file G4NucleiPropertiesTableAME12.cc
References A(), EventMustBeAborted, G4Exception(), indexArray, MaxA, and shortTable.
Referenced by GetAtomicMass(), GetBetaDecayEnergy(), GetBindingEnergy(), GetMassExcess(), and IsInTable().
G4double G4NucleiPropertiesTableAME12::GetMassExcess (G4int Z, G4int A) static private
Definition at line 124 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 124 of file G4NucleiPropertiesTableAME12.cc
References GetIndex(), keV, and MassExcess.
Referenced by G4NucleiProperties::AtomicMass(), and G4NucleiProperties::GetMassExcess().
G4double G4NucleiPropertiesTableAME12::GetNuclearMass (G4int Z, G4int A) static private
Definition at line 103 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 103 of file G4NucleiPropertiesTableAME12.cc
References e, source.hepunit::electron_mass_c2, electronMass, eV, GetAtomicMass(), isIntialized, Z, and ZMax.
Referenced by G4NucleiProperties::GetNuclearMass().
G4bool G4NucleiPropertiesTableAME12::IsInTable (G4int Z, G4int A) static private
Definition at line 165 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 165 of file G4NucleiPropertiesTableAME12.cc
References GetIndex().
Referenced by G4NucleiProperties::GetAtomicMass(), G4NucleiProperties::GetBindingEnergy(), G4NucleiProperties::GetMassExcess(), G4NucleiProperties::GetNuclearMass(), and G4NucleiProperties::IsInStableTable().
G4int G4NucleiPropertiesTableAME12::MaxZ (G4int A) static private
Definition at line 96 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 96 of file G4NucleiPropertiesTableAME12.cc
References A(), indexArray, and shortTable.
G4int G4NucleiPropertiesTableAME12::MinZ (G4int A) static private
Definition at line 89 of file G4NucleiPropertiesTableAME12.cc.
View newest version in sPHENIX GitHub at line 89 of file G4NucleiPropertiesTableAME12.cc
References indexArray, and shortTable.
Friends And Related Function Documentation
friend class G4NucleiProperties friend
Definition at line 74 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 74 of file G4NucleiPropertiesTableAME12.hh
Member Data Documentation
const G4double G4NucleiPropertiesTableAME12::BetaEnergy static private
Definition at line 120 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 120 of file G4NucleiPropertiesTableAME12.hh
Referenced by GetBetaDecayEnergy().
G4ThreadLocal G4double G4NucleiPropertiesTableAME12::electronMass static private
Definition at line 135 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 135 of file G4NucleiPropertiesTableAME12.hh
Referenced by GetNuclearMass().
const G4int G4NucleiPropertiesTableAME12::indexArray static private
Definition at line 126 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 126 of file G4NucleiPropertiesTableAME12.hh
Referenced by GetIndex(), MaxZ(), and MinZ().
G4ThreadLocal G4bool G4NucleiPropertiesTableAME12::isIntialized = false static private
Definition at line 136 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 136 of file G4NucleiPropertiesTableAME12.hh
Referenced by GetNuclearMass().
const G4double G4NucleiPropertiesTableAME12::MassExcess static private
Definition at line 116 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 116 of file G4NucleiPropertiesTableAME12.hh
Referenced by GetAtomicMass(), GetBindingEnergy(), and GetMassExcess().
const G4int G4NucleiPropertiesTableAME12::shortTable static private
Definition at line 132 of file G4NucleiPropertiesTableAME12.hh.
View newest version in sPHENIX GitHub at line 132 of file G4NucleiPropertiesTableAME12.hh
Referenced by GetIndex(), MaxZ(), and MinZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4NucleiPropertiesTableAME12.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4NucleiPropertiesTableAME12.cc