ECCE @ EIC Software: G4RegionModels Class Reference
G4RegionModels Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmModelManager.hh>
Private Member Functions
G4RegionModels (G4int nMod, std::vector< G4int > &indx, G4DataVector &lowE, const G4Region *reg)
~G4RegionModels ()
G4int SelectIndex (G4double e) const
G4int ModelIndex (G4int n) const
G4int NumberOfModels () const
G4double LowEdgeEnergy (G4int n) const
const G4Region * Region () const
G4RegionModels (G4RegionModels &)=delete
G4RegionModels & operator= (const G4RegionModels &right)=delete
Private Attributes
const G4Region * theRegion
G4int nModelsForRegion
G4int * theListOfModelIndexes
G4double * lowKineticEnergy
Friends
class G4EmModelManager
Detailed Description
Definition at line 81 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4EmModelManager.hh
Constructor & Destructor Documentation
G4RegionModels::G4RegionModels (G4int nMod, std::vector< G4int > & indx, G4DataVector & lowE, const G4Region * reg) private
Definition at line 59 of file G4EmModelManager.cc.
View newest version in sPHENIX GitHub at line 59 of file G4EmModelManager.cc
References lowKineticEnergy, nModelsForRegion, reg, theListOfModelIndexes, and theRegion.
G4RegionModels::~G4RegionModels () private
Definition at line 75 of file G4EmModelManager.cc.
View newest version in sPHENIX GitHub at line 75 of file G4EmModelManager.cc
References lowKineticEnergy, and theListOfModelIndexes.
G4RegionModels::G4RegionModels (G4RegionModels &) private delete
Member Function Documentation
G4double G4RegionModels::LowEdgeEnergy (G4int n) const inline private
Definition at line 111 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 111 of file G4EmModelManager.hh
References lowKineticEnergy, and n.
Referenced by G4EmModelManager::DumpModelList(), G4EmModelManager::FillDEDXVector(), and G4EmModelManager::FillLambdaVector().
G4int G4RegionModels::ModelIndex (G4int n) const inline private
Definition at line 103 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 103 of file G4EmModelManager.hh
References n, and theListOfModelIndexes.
Referenced by G4EmModelManager::DumpModelList(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4EmModelManager::GetRegionModel(), and G4EmModelManager::Initialise().
G4int G4RegionModels::NumberOfModels () const inline private
Definition at line 107 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4EmModelManager.hh
References nModelsForRegion.
Referenced by G4EmModelManager::DumpModelList(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4EmModelManager::Initialise(), and G4EmModelManager::NumberOfRegionModels().
G4RegionModels& G4RegionModels::operator= (const G4RegionModels & right) private delete
const G4Region* G4RegionModels::Region () const inline private
Definition at line 115 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4EmModelManager.hh
References theRegion.
Referenced by G4EmModelManager::DumpModelList().
G4int G4RegionModels::SelectIndex (G4double e) const inline private
Definition at line 93 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 93 of file G4EmModelManager.hh
References incremental_prev_tag::idx, lowKineticEnergy, nModelsForRegion, and theListOfModelIndexes.
Referenced by G4EmModelManager::SelectModel().
Friends And Related Function Documentation
friend class G4EmModelManager friend
Definition at line 84 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4EmModelManager.hh
Member Data Documentation
G4double* G4RegionModels::lowKineticEnergy private
Definition at line 125 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 125 of file G4EmModelManager.hh
Referenced by G4RegionModels(), LowEdgeEnergy(), SelectIndex(), and ~G4RegionModels().
G4int G4RegionModels::nModelsForRegion private
Definition at line 123 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4EmModelManager.hh
Referenced by G4RegionModels(), NumberOfModels(), and SelectIndex().
G4int* G4RegionModels::theListOfModelIndexes private
Definition at line 124 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4EmModelManager.hh
Referenced by G4RegionModels(), ModelIndex(), SelectIndex(), and ~G4RegionModels().
const G4Region* G4RegionModels::theRegion private
Definition at line 122 of file G4EmModelManager.hh.
View newest version in sPHENIX GitHub at line 122 of file G4EmModelManager.hh
Referenced by G4RegionModels(), and Region().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmModelManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmModelManager.cc