ECCE @ EIC Software: G4ParticleChange Class Reference
G4ParticleChange Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChange.hh>
Public Member Functions
G4ParticleChange ()
virtual ~G4ParticleChange ()
G4bool operator== (const G4ParticleChange &right) const
G4bool operator!= (const G4ParticleChange &right) const
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
virtual G4Step * UpdateStepForPostStep (G4Step *Step)
virtual void Initialize (const G4Track &)
const G4ThreeVector * GetMomentumDirection () const
void ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
void ProposeMomentumDirection (const G4ThreeVector &Pfinal)
const G4ThreeVector * GetPolarization () const
void ProposePolarization (G4double Px, G4double Py, G4double Pz)
void ProposePolarization (const G4ThreeVector &finalPoralization)
G4double GetEnergy () const
void ProposeEnergy (G4double finalEnergy)
G4double GetVelocity () const
void ProposeVelocity (G4double finalVelocity)
G4double GetProperTime () const
void ProposeProperTime (G4double finalProperTime)
const G4ThreeVector * GetPosition () const
void ProposePosition (G4double x, G4double y, G4double z)
void ProposePosition (const G4ThreeVector &finalPosition)
void ProposeGlobalTime (G4double t)
void ProposeLocalTime (G4double t)
G4double GetGlobalTime (G4double timeDelay=0.0) const
G4double GetLocalTime (G4double timeDelay=0.0) const
G4double GetMass () const
void ProposeMass (G4double finalMass)
G4double GetCharge () const
void ProposeCharge (G4double finalCharge)
G4double GetMagneticMoment () const
void ProposeMagneticMoment (G4double finalMagneticMoment)
G4ThreeVector GetGlobalPosition (const G4ThreeVector &displacement) const
G4ThreeVector CalcMomentum (G4double energy, G4ThreeVector direction, G4double mass) const
void AddSecondary (G4Track *aSecondary)
void AddSecondary (G4DynamicParticle *aSecondary, G4bool IsGoodForTracking=false)
void AddSecondary (G4DynamicParticle *aSecondary, G4ThreeVector position, G4bool IsGoodForTracking=false)
void AddSecondary (G4DynamicParticle *aSecondary, G4double time, G4bool IsGoodForTracking=false)
virtual void DumpInfo () const
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChange (const G4ParticleChange &right)
G4ParticleChange & operator= (const G4ParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Protected Attributes
G4ThreeVector theMomentumDirectionChange
G4ThreeVector thePolarizationChange
G4double theEnergyChange
G4double theVelocityChange
G4bool isVelocityChanged
G4ThreeVector thePositionChange
G4double theGlobalTime0
G4double theLocalTime0
G4double theTimeChange
G4double theProperTimeChange
G4double theMassChange
G4double theChargeChange
G4double theMagneticMomentChange
const G4Track * theCurrentTrack
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Additional Inherited Members
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 76 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleChange.hh
Constructor & Destructor Documentation
G4ParticleChange::G4ParticleChange ()
Definition at line 53 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleChange.cc
G4ParticleChange::~G4ParticleChange () virtual
Definition at line 67 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ParticleChange.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChange::G4ParticleChange (const G4ParticleChange & right) protected
Definition at line 77 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleChange.cc
References G4cout, G4endl, isVelocityChanged, theChargeChange, theCurrentTrack, theEnergyChange, theGlobalTime0, theLocalTime0, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theVelocityChange, and G4VParticleChange::verboseLevel.
Member Function Documentation
void G4ParticleChange::AddSecondary (G4Track * aSecondary)
Definition at line 217 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 217 of file G4ParticleChange.cc
References G4VParticleChange::AddSecondary().
Referenced by G4eLowEnergyLoss::AlongStepDoIt(), GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4MuonicAtomDecay::DecayIt(), G4SingleScatter::DoCollisionStep(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4BOptnCloning::GenerateBiasingFinalState(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4PhononScattering::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), and G4SamplingPostStepAction::Split().
void G4ParticleChange::AddSecondary (G4DynamicParticle * aSecondary, G4bool IsGoodForTracking = false)
Definition at line 167 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 167 of file G4ParticleChange.cc
References G4VParticleChange::AddSecondary(), GetGlobalTime(), G4Track::GetTouchableHandle(), G4Track::SetGoodForTrackingFlag(), G4Track::SetTouchableHandle(), theCurrentTrack, and thePositionChange.
void G4ParticleChange::AddSecondary (G4DynamicParticle * aSecondary, G4ThreeVector position, G4bool IsGoodForTracking = false)
Definition at line 183 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 183 of file G4ParticleChange.cc
References G4VParticleChange::AddSecondary(), GetGlobalTime(), G4Track::SetGoodForTrackingFlag(), and G4Track::SetTouchableHandle().
void G4ParticleChange::AddSecondary (G4DynamicParticle * aSecondary, G4double time, G4bool IsGoodForTracking = false)
Definition at line 200 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 200 of file G4ParticleChange.cc
References G4VParticleChange::AddSecondary(), G4Track::GetTouchableHandle(), G4Track::SetGoodForTrackingFlag(), G4Track::SetTouchableHandle(), theCurrentTrack, and thePositionChange.
G4ThreeVector G4ParticleChange::CalcMomentum (G4double energy, G4ThreeVector direction, G4double mass) const
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), and UpdateStepForAlongStep().
G4bool G4ParticleChange::CheckIt (const G4Track & aTrack) virtual
Reimplemented from G4VParticleChange.
Definition at line 505 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 505 of file G4ParticleChange.cc
References G4VParticleChange::accuracyForException, G4VParticleChange::accuracyForWarning, source.hepunit::c_light, G4VParticleChange::CheckIt(), DumpInfo(), EventMustBeAborted, fStopAndKill, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4Track::GetDefinition(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetLocalTime(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4Track::GetProperTime(), G4VParticleChange::GetTrackStatus(), m, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), MeV, ns, theEnergyChange, theMomentumDirectionChange, theProperTimeChange, theTimeChange, theVelocityChange, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
void G4ParticleChange::DumpInfo () const virtual
Reimplemented from G4VParticleChange.
Reimplemented in G4ParticleChangeForTransport.
Definition at line 444 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 444 of file G4ParticleChange.cc
References source.hepunit::c_light, source.hepunit::c_squared, G4VParticleChange::DumpInfo(), eplus, G4cout, G4endl, GeV, source.hepunit::hbar_Planck, MeV, mm, ns, theChargeChange, theEnergyChange, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theVelocityChange, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CheckIt(), and G4ParticleChangeForTransport::DumpInfo().
G4double G4ParticleChange::GetCharge () const
G4double G4ParticleChange::GetEnergy () const
Referenced by G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4SingleScatter::DoCollisionStep(), and G4UCNBoundaryProcess::PostStepDoIt().
G4ThreeVector G4ParticleChange::GetGlobalPosition (const G4ThreeVector & displacement) const
G4double G4ParticleChange::GetGlobalTime (G4double timeDelay = 0.0) const
Referenced by AddSecondary().
G4double G4ParticleChange::GetLocalTime (G4double timeDelay = 0.0) const
G4double G4ParticleChange::GetMagneticMoment () const
G4double G4ParticleChange::GetMass () const
const G4ThreeVector* G4ParticleChange::GetMomentumDirection () const
Referenced by G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4OpMieHG::PostStepDoIt(), and G4OpRayleigh::PostStepDoIt().
const G4ThreeVector* G4ParticleChange::GetPolarization () const
Referenced by G4OpMieHG::PostStepDoIt(), and G4OpRayleigh::PostStepDoIt().
const G4ThreeVector* G4ParticleChange::GetPosition () const
G4double G4ParticleChange::GetProperTime () const
G4double G4ParticleChange::GetVelocity () const
void G4ParticleChange::Initialize (const G4Track & track) virtual
Reimplemented from G4VParticleChange.
Reimplemented in G4ParticleChangeForTransport.
Definition at line 227 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 227 of file G4ParticleChange.cc
References G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetLocalTime(), G4DynamicParticle::GetMagneticMoment(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetPolarization(), G4Track::GetPosition(), G4DynamicParticle::GetProperTime(), G4Track::GetVelocity(), G4VParticleChange::Initialize(), isVelocityChanged, theChargeChange, theCurrentTrack, theEnergyChange, theGlobalTime0, theLocalTime0, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theVelocityChange, and track.
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4DNAElectronHoleRecombination::AtRestDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4DNAMolecularDissociation::DecayIt(), G4MuonicAtomDecay::DecayIt(), CexmcHadronicProcess::FillTotalResult(), G4BOptnCloning::GenerateBiasingFinalState(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4DNAElectronHoleRecombination::MakeReaction(), G4PhononDownconversion::PostStepDoIt(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4Channeling::PostStepDoIt(), HadrontherapyStepMax::PostStepDoIt(), XrayFluoStepMax::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4StepLimiter::PostStepDoIt(), StepLimiter::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), StepMax::PostStepDoIt(), F04StepMax::PostStepDoIt(), StepMaxProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepDoIt(), IORTStepMax::PostStepDoIt(), G4SpecialCuts::PostStepDoIt(), DMXSpecialCuts::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), ML2StepMax::PostStepDoIt(), CexmcHadronicProcess::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), XrayTelStepCut::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4VAdjointReverseReaction::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNLoss::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), and G4hImpactIonisation::PostStepDoIt().
G4bool G4ParticleChange::operator!= (const G4ParticleChange & right) const
Definition at line 157 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleChange.cc
G4ParticleChange & G4ParticleChange::operator= (const G4ParticleChange & right) protected
Definition at line 101 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleChange.cc
References G4cout, G4endl, isVelocityChanged, G4FastVector< Type, N >::SetElement(), theChargeChange, theCurrentTrack, theEnergyChange, theGlobalTime0, G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, theLocalTime0, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, G4VParticleChange::theNumberOfSecondaries, thePolarizationChange, thePositionChange, theProperTimeChange, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, theTimeChange, G4VParticleChange::theTrueStepLength, theVelocityChange, and G4VParticleChange::verboseLevel.
G4bool G4ParticleChange::operator== (const G4ParticleChange & right) const
Definition at line 152 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 152 of file G4ParticleChange.cc
void G4ParticleChange::ProposeCharge (G4double finalCharge)
void G4ParticleChange::ProposeEnergy (G4double finalEnergy)
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4DNABrownianTransportation::Diffusion(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4SingleScatter::DoCollisionStep(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4PhononDownconversion::PostStepDoIt(), G4PhononScattering::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepDoIt(), DMXSpecialCuts::PostStepDoIt(), G4SpecialCuts::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), and G4AdjointIonIonisationModel::SampleSecondaries().
void G4ParticleChange::ProposeGlobalTime (G4double t)
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), and G4ITTransportation::AlongStepDoIt().
void G4ParticleChange::ProposeLocalTime (G4double t)
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), and G4MuonicAtomDecay::DecayIt().
void G4ParticleChange::ProposeMagneticMoment (G4double finalMagneticMoment)
void G4ParticleChange::ProposeMass (G4double finalMass)
void G4ParticleChange::ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4DNABrownianTransportation::Diffusion(), G4SingleScatter::DoCollisionStep(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4Channeling::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), and G4AdjointhIonisationModel::SampleSecondaries().
void G4ParticleChange::ProposeMomentumDirection (const G4ThreeVector & Pfinal)
void G4ParticleChange::ProposePolarization (G4double Px, G4double Py, G4double Pz)
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4Channeling::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), and G4OpBoundaryProcess::PostStepDoIt().
void G4ParticleChange::ProposePolarization (const G4ThreeVector & finalPoralization)
void G4ParticleChange::ProposePosition (G4double x, G4double y, G4double z)
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4NeutrinoElectronProcess::PostStepDoIt().
void G4ParticleChange::ProposePosition (const G4ThreeVector & finalPosition)
void G4ParticleChange::ProposeProperTime (G4double finalProperTime)
Referenced by G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), and G4CoupledTransportation::AlongStepDoIt().
void G4ParticleChange::ProposeVelocity (G4double finalVelocity)
Referenced by G4ITTransportation::AlongStepDoIt(), G4ITTransportation::ComputeStep(), G4PhononReflection::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), and G4OpBoundaryProcess::PostStepDoIt().
G4Step * G4ParticleChange::UpdateStepForAlongStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Reimplemented in G4ParticleChangeForTransport.
Definition at line 263 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 263 of file G4ParticleChange.cc
References G4StepPoint::AddGlobalTime(), G4StepPoint::AddLocalTime(), G4StepPoint::AddPolarization(), G4StepPoint::AddPosition(), G4StepPoint::AddProperTime(), CalcMomentum(), G4Track::CalculateVelocity(), CheckIt(), G4VParticleChange::debugFlag, energy, G4StepPoint::GetKineticEnergy(), G4StepPoint::GetMomentum(), G4StepPoint::GetPolarization(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProperTime(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, isVelocityChanged, CLHEP::Hep3Vector::mag(), mass, G4StepPoint::SetCharge(), G4StepPoint::SetKineticEnergy(), G4Track::SetKineticEnergy(), G4StepPoint::SetMagneticMoment(), G4StepPoint::SetMass(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetVelocity(), G4StepPoint::SetWeight(), theChargeChange, theEnergyChange, theLocalTime0, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, G4VParticleChange::theParentWeight, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theVelocityChange, and UpdateStepInfo().
G4Step * G4ParticleChange::UpdateStepForAtRest (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Reimplemented in G4ParticleChangeForTransport.
Definition at line 401 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 401 of file G4ParticleChange.cc
References G4StepPoint::AddGlobalTime(), G4Track::CalculateVelocity(), CheckIt(), G4VParticleChange::debugFlag, G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, isVelocityChanged, G4StepPoint::SetCharge(), G4StepPoint::SetKineticEnergy(), G4StepPoint::SetLocalTime(), G4StepPoint::SetMagneticMoment(), G4StepPoint::SetMass(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPolarization(), G4StepPoint::SetPosition(), G4StepPoint::SetProperTime(), G4StepPoint::SetVelocity(), G4StepPoint::SetWeight(), theChargeChange, theEnergyChange, theLocalTime0, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, G4VParticleChange::theParentWeight, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theVelocityChange, and UpdateStepInfo().
G4Step * G4ParticleChange::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Reimplemented in G4ParticleChangeForTransport.
Definition at line 347 of file G4ParticleChange.cc.
View newest version in sPHENIX GitHub at line 347 of file G4ParticleChange.cc
References G4StepPoint::AddGlobalTime(), G4Track::CalculateVelocity(), CheckIt(), G4VParticleChange::debugFlag, G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, isVelocityChanged, G4StepPoint::SetCharge(), G4StepPoint::SetKineticEnergy(), G4Track::SetKineticEnergy(), G4StepPoint::SetLocalTime(), G4StepPoint::SetMagneticMoment(), G4StepPoint::SetMass(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPolarization(), G4StepPoint::SetPosition(), G4StepPoint::SetProperTime(), G4StepPoint::SetVelocity(), G4StepPoint::SetWeight(), theChargeChange, theEnergyChange, theLocalTime0, theMagneticMomentChange, theMassChange, theMomentumDirectionChange, G4VParticleChange::theParentWeight, thePolarizationChange, thePositionChange, theProperTimeChange, theTimeChange, theVelocityChange, and UpdateStepInfo().
G4Step* G4ParticleChange::UpdateStepInfo (G4Step * Step) protected
Referenced by UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAtRest(), UpdateStepForAtRest(), and UpdateStepForPostStep().
Member Data Documentation
G4bool G4ParticleChange::isVelocityChanged protected
Definition at line 234 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 234 of file G4ParticleChange.hh
Referenced by G4ParticleChange(), Initialize(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theChargeChange protected
Definition at line 254 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 254 of file G4ParticleChange.hh
Referenced by DumpInfo(), G4ParticleChange(), Initialize(), operator=(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
const G4Track* G4ParticleChange::theCurrentTrack protected
Definition at line 260 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 260 of file G4ParticleChange.hh
Referenced by AddSecondary(), G4ParticleChange(), Initialize(), and operator=().
G4double G4ParticleChange::theEnergyChange protected
Definition at line 230 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChange(), Initialize(), G4ParticleChangeForTransport::operator=(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theGlobalTime0 protected
Definition at line 240 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 240 of file G4ParticleChange.hh
Referenced by G4ParticleChange(), Initialize(), and operator=().
G4double G4ParticleChange::theLocalTime0 protected
Definition at line 242 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 242 of file G4ParticleChange.hh
Referenced by G4ParticleChange(), Initialize(), operator=(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theMagneticMomentChange protected
Definition at line 257 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 257 of file G4ParticleChange.hh
Referenced by DumpInfo(), G4ParticleChange(), Initialize(), operator=(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theMassChange protected
Definition at line 251 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 251 of file G4ParticleChange.hh
Referenced by DumpInfo(), G4ParticleChange(), Initialize(), operator=(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChange::theMomentumDirectionChange protected
Definition at line 220 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChange(), Initialize(), G4ParticleChangeForTransport::operator=(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChange::thePolarizationChange protected
Definition at line 227 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 227 of file G4ParticleChange.hh
Referenced by DumpInfo(), G4ParticleChange(), Initialize(), G4ParticleChangeForTransport::operator=(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChange::thePositionChange protected
Definition at line 237 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 237 of file G4ParticleChange.hh
Referenced by AddSecondary(), DumpInfo(), G4ParticleChange(), Initialize(), G4ParticleChangeForTransport::operator=(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theProperTimeChange protected
Definition at line 248 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 248 of file G4ParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChange(), Initialize(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theTimeChange protected
Definition at line 245 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 245 of file G4ParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChange(), Initialize(), G4ParticleChangeForTransport::operator=(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChange::theVelocityChange protected
Definition at line 233 of file G4ParticleChange.hh.
View newest version in sPHENIX GitHub at line 233 of file G4ParticleChange.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChange(), Initialize(), G4ParticleChangeForTransport::operator=(), operator=(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), UpdateStepForAlongStep(), UpdateStepForAtRest(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChange.hh
geant4/tree/geant4-10.6-release/source/track/src/G4ParticleChange.cc