ECCE @ EIC Software: G4PolarizationHelper Class Reference
G4PolarizationHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizationHelper.hh>
Static Public Member Functions
static G4ThreeVector GetFrame (const G4ThreeVector &, const G4ThreeVector &)
static G4ThreeVector GetParticleFrameX (const G4ThreeVector &)
static G4ThreeVector GetParticleFrameY (const G4ThreeVector &)
static G4ThreeVector GetRandomFrame (const G4ThreeVector &)
static G4ThreeVector GetSpinInPRF (const G4ThreeVector &uZ, const G4ThreeVector &spin)
static void TestPolarizationTransformations ()
static void TestInteractionFrame ()
Detailed Description
Definition at line 48 of file G4PolarizationHelper.hh.
View newest version in sPHENIX GitHub at line 48 of file G4PolarizationHelper.hh
Member Function Documentation
G4ThreeVector G4PolarizationHelper::GetFrame (const G4ThreeVector & mom1, const G4ThreeVector & mom2) static
Definition at line 47 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PolarizationHelper.cc
References CLHEP::Hep3Vector::cross(), and CLHEP::normal().
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
G4ThreeVector G4PolarizationHelper::GetParticleFrameX (const G4ThreeVector & uZ) static
Definition at line 66 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 66 of file G4PolarizationHelper.cc
References Acts::VectorHelpers::perp(), sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), and GetRandomFrame().
G4ThreeVector G4PolarizationHelper::GetParticleFrameY (const G4ThreeVector & uZ) static
Definition at line 54 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PolarizationHelper.cc
References sqr(), CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), GetRandomFrame(), G4StokesVector::InvRotateAz(), G4StokesVector::RotateAz(), and TestPolarizationTransformations().
G4ThreeVector G4PolarizationHelper::GetRandomFrame (const G4ThreeVector & mom1) static
Definition at line 80 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 80 of file G4PolarizationHelper.cc
References G4UniformRand, GetParticleFrameX(), GetParticleFrameY(), CLHEP::normal(), phi, and pi.
Referenced by G4PolarizedPEEffectModel::SampleSecondaries().
G4ThreeVector G4PolarizationHelper::GetSpinInPRF (const G4ThreeVector & uZ, const G4ThreeVector & spin) static
Definition at line 89 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 89 of file G4PolarizationHelper.cc
References Acts::VectorHelpers::perp(), sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4PolarizationHelper::TestInteractionFrame () static
Definition at line 143 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 143 of file G4PolarizationHelper.cc
References G4cout, CLHEP::Hep3Vector::rotateUz(), and theta().
Referenced by G4PolarizationMessenger::SetNewValue().
void G4PolarizationHelper::TestPolarizationTransformations () static
Definition at line 107 of file G4PolarizationHelper.cc.
View newest version in sPHENIX GitHub at line 107 of file G4PolarizationHelper.cc
References CLHEP::Hep3Vector::cross(), G4cout, GetParticleFrameY(), CLHEP::Hep3Vector::mag(), pi, and theta().
Referenced by G4PolarizationMessenger::SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizationHelper.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizationHelper.cc