ECCE @ EIC Software: G4VTrajectoryModel Class Reference
G4VTrajectoryModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VTrajectoryModel.hh>
Public Member Functions
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const =0
virtual void Print (std::ostream &ostr) const =0
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Private Member Functions
G4VTrajectoryModel (const G4VTrajectoryModel &)
G4VTrajectoryModel & operator= (const G4VTrajectoryModel &)
Private Attributes
G4String fName
G4bool fVerbose
G4VisTrajContext * fpContext
Detailed Description
Definition at line 43 of file G4VTrajectoryModel.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VTrajectoryModel.hh
Constructor & Destructor Documentation
G4VTrajectoryModel::G4VTrajectoryModel (const G4String & name, G4VisTrajContext * fpContext = 0)
Definition at line 36 of file G4VTrajectoryModel.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VTrajectoryModel.cc
References fpContext.
G4VTrajectoryModel::~G4VTrajectoryModel () virtual
Definition at line 47 of file G4VTrajectoryModel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VTrajectoryModel.cc
References fpContext.
G4VTrajectoryModel::G4VTrajectoryModel (const G4VTrajectoryModel &) private
Member Function Documentation
virtual void G4VTrajectoryModel::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const pure virtual
Implemented in G4TrajectoryDrawByCharge, G4TrajectoryDrawByAttribute, G4TrajectoryDrawByEncounteredVolume, G4TrajectoryDrawByParticleID, G4TrajectoryDrawByOriginVolume, and G4TrajectoryGenericDrawer.
Referenced by G4VisManager::DispatchToModel().
const G4VisTrajContext & G4VTrajectoryModel::GetContext () const
Definition at line 53 of file G4VTrajectoryModel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VTrajectoryModel.cc
References fpContext.
Referenced by G4HepRepFileSceneHandler::BeginModeling(), G4TrajectoryGenericDrawer::Draw(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByAttribute::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), G4TrajectoryDrawByCharge::Draw(), G4TrajectoryGenericDrawer::Print(), G4TrajectoryDrawByOriginVolume::Print(), G4TrajectoryDrawByParticleID::Print(), G4TrajectoryDrawByEncounteredVolume::Print(), G4TrajectoryDrawByAttribute::Print(), and G4TrajectoryDrawByCharge::Print().
G4bool G4VTrajectoryModel::GetVerbose () const
Definition at line 73 of file G4VTrajectoryModel.cc.
View newest version in sPHENIX GitHub at line 73 of file G4VTrajectoryModel.cc
References fVerbose.
Referenced by G4TrajectoryGenericDrawer::Draw(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByAttribute::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), and G4TrajectoryDrawByCharge::Draw().
G4String G4VTrajectoryModel::Name () const
Definition at line 61 of file G4VTrajectoryModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VTrajectoryModel.cc
References fName.
Referenced by G4TrajectoryGenericDrawer::Draw(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), G4TrajectoryDrawByAttribute::Draw(), G4TrajectoryDrawByCharge::Draw(), G4TrajectoryGenericDrawer::Print(), G4TrajectoryDrawByOriginVolume::Print(), G4TrajectoryDrawByParticleID::Print(), G4TrajectoryDrawByEncounteredVolume::Print(), G4TrajectoryDrawByAttribute::Print(), and G4TrajectoryDrawByCharge::Print().
G4VTrajectoryModel& G4VTrajectoryModel::operator= (const G4VTrajectoryModel &) private
virtual void G4VTrajectoryModel::Print (std::ostream & ostr) const pure virtual
Implemented in G4TrajectoryDrawByCharge, G4TrajectoryDrawByAttribute, G4TrajectoryDrawByEncounteredVolume, G4TrajectoryDrawByParticleID, G4TrajectoryDrawByOriginVolume, and G4TrajectoryGenericDrawer.
void G4VTrajectoryModel::SetVerbose (const G4bool & verbose)
Definition at line 67 of file G4VTrajectoryModel.cc.
View newest version in sPHENIX GitHub at line 67 of file G4VTrajectoryModel.cc
References fVerbose.
Member Data Documentation
G4String G4VTrajectoryModel::fName private
Definition at line 75 of file G4VTrajectoryModel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VTrajectoryModel.hh
Referenced by Name().
G4VisTrajContext* G4VTrajectoryModel::fpContext private
Definition at line 77 of file G4VTrajectoryModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VTrajectoryModel.hh
Referenced by G4VTrajectoryModel(), GetContext(), and ~G4VTrajectoryModel().
G4bool G4VTrajectoryModel::fVerbose private
Definition at line 76 of file G4VTrajectoryModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VTrajectoryModel.hh
Referenced by GetVerbose(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4VTrajectoryModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4VTrajectoryModel.cc