ECCE @ EIC Software: G4AssemblyVolume Class Reference
G4AssemblyVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4AssemblyVolume.hh>
Public Member Functions
G4AssemblyVolume ()
G4AssemblyVolume (G4LogicalVolume *volume, G4ThreeVector &translation, G4RotationMatrix *rotation)
~G4AssemblyVolume ()
void AddPlacedVolume (G4LogicalVolume *pPlacedVolume, G4ThreeVector &translation, G4RotationMatrix *rotation)
void AddPlacedVolume (G4LogicalVolume *pPlacedVolume, G4Transform3D &transformation)
void AddPlacedAssembly (G4AssemblyVolume *pAssembly, G4Transform3D &transformation)
void AddPlacedAssembly (G4AssemblyVolume *pAssembly, G4ThreeVector &translation, G4RotationMatrix *rotation)
void MakeImprint (G4LogicalVolume *pMotherLV, G4ThreeVector &translationInMother, G4RotationMatrix *pRotationInMother, G4int copyNumBase=0, G4bool surfCheck=false)
void MakeImprint (G4LogicalVolume *pMotherLV, G4Transform3D &transformation, G4int copyNumBase=0, G4bool surfCheck=false)
std::vector< G4VPhysicalVolume * >
::iterator GetVolumesIterator ()
std::size_t TotalImprintedVolumes () const
G4Transform3D & GetImprintTransformation (unsigned int imprintID)
std::vector< G4AssemblyTriplet >
::iterator GetTripletsIterator ()
std::size_t TotalTriplets () const
unsigned int GetImprintsCount () const
unsigned int GetInstanceCount () const
unsigned int GetAssemblyID () const
Protected Member Functions
void SetInstanceCount (unsigned int value)
void SetAssemblyID (unsigned int value)
void InstanceCountPlus ()
void InstanceCountMinus ()
void SetImprintsCount (unsigned int value)
void ImprintsCountPlus ()
void ImprintsCountMinus ()
Private Member Functions
void MakeImprint (G4AssemblyVolume *pAssembly, G4LogicalVolume *pMotherLV, G4Transform3D &transformation, G4int copyNumBase=0, G4bool surfCheck=false)
Private Attributes
std::vector< G4AssemblyTriplet > fTriplets
std::vector< G4VPhysicalVolume * > fPVStore
unsigned int fImprintsCounter
unsigned int fAssemblyID = 0
std::map< unsigned int,
G4Transform3D > fImprintsTransf
Static Private Attributes
static G4ThreadLocal unsigned int fsInstanceCounter = 0
Detailed Description
Definition at line 53 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 53 of file G4AssemblyVolume.hh
Constructor & Destructor Documentation
G4AssemblyVolume::G4AssemblyVolume ()
Definition at line 45 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 45 of file G4AssemblyVolume.cc
References fAssemblyID, G4endl, G4Exception(), G4AssemblyStore::GetAssembly(), G4AssemblyStore::GetInstance(), GetInstanceCount(), InstanceCountPlus(), JustWarning, message(), G4AssemblyStore::Register(), SetAssemblyID(), and SetImprintsCount().
G4AssemblyVolume::G4AssemblyVolume (G4LogicalVolume * volume, G4ThreeVector & translation, G4RotationMatrix * rotation)
Definition at line 68 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 68 of file G4AssemblyVolume.cc
References AddPlacedVolume(), fAssemblyID, G4endl, G4Exception(), G4AssemblyStore::GetAssembly(), G4AssemblyStore::GetInstance(), GetInstanceCount(), InstanceCountPlus(), JustWarning, message(), G4AssemblyStore::Register(), SetAssemblyID(), and SetImprintsCount().
G4AssemblyVolume::~G4AssemblyVolume ()
Definition at line 94 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 94 of file G4AssemblyVolume.cc
References G4AssemblyStore::DeRegister(), fPVStore, fTriplets, G4AssemblyStore::GetInstance(), and InstanceCountMinus().
Member Function Documentation
void G4AssemblyVolume::AddPlacedAssembly (G4AssemblyVolume * pAssembly, G4Transform3D & transformation)
Definition at line 180 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 180 of file G4AssemblyVolume.cc
References fTriplets, HepGeom::Transform3D::getDecomposition(), HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), r, scale, and v.
Referenced by PHG4TpcEndCapDetector::ConstructElectronics(), and G4GDMLReadStructure::PhysvolRead().
void G4AssemblyVolume::AddPlacedAssembly (G4AssemblyVolume * pAssembly, G4ThreeVector & translation, G4RotationMatrix * rotation)
Definition at line 165 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 165 of file G4AssemblyVolume.cc
References fTriplets.
void G4AssemblyVolume::AddPlacedVolume (G4LogicalVolume * pPlacedVolume, G4ThreeVector & translation, G4RotationMatrix * rotation)
Definition at line 128 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 128 of file G4AssemblyVolume.cc
References fTriplets.
Referenced by PHG4TpcEndCapDetector::AddLayer(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4mRICHDetector::build_mRICH_wall_hside(), PHG4TTLDetector::BuildBarrelTTL(), G02DetectorConstruction::ConstructAssembly(), PHG4TpcEndCapDetector::ConstructElectronics(), G4tgbVolume::ConstructG4PhysVol(), PHG4InnerHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructHcalScintillatorAssembly(), G4EicDircDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructWagonWheel(), G4AssemblyVolume(), TrentoPassiveProtonBeamLine::HadrontherapyBeamMonitoring(), and G4GDMLReadStructure::PhysvolRead().
void G4AssemblyVolume::AddPlacedVolume (G4LogicalVolume * pPlacedVolume, G4Transform3D & transformation)
Definition at line 142 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 142 of file G4AssemblyVolume.cc
References fTriplets, HepGeom::Transform3D::getDecomposition(), HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), r, scale, and v.
unsigned int G4AssemblyVolume::GetAssemblyID () const inline
Referenced by MakeImprint().
unsigned int G4AssemblyVolume::GetImprintsCount () const inline
Referenced by MakeImprint().
G4Transform3D& G4AssemblyVolume::GetImprintTransformation (unsigned int imprintID) inline
Referenced by G4GDMLWriteStructure::TraverseVolumeTree().
unsigned int G4AssemblyVolume::GetInstanceCount () const
Definition at line 377 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 377 of file G4AssemblyVolume.cc
References fsInstanceCounter.
Referenced by G4AssemblyVolume().
std::vector<G4AssemblyTriplet>::iterator G4AssemblyVolume::GetTripletsIterator () inline
Referenced by G4GDMLWriteStructure::AssemblyWrite().
std::vector<G4VPhysicalVolume*>::iterator G4AssemblyVolume::GetVolumesIterator () inline
Referenced by BeastMagnetDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), and PHG4MvtxDetector::SetDisplayProperty().
void G4AssemblyVolume::ImprintsCountMinus () inline protected
void G4AssemblyVolume::ImprintsCountPlus () inline protected
Referenced by MakeImprint().
void G4AssemblyVolume::InstanceCountMinus () protected
Definition at line 392 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 392 of file G4AssemblyVolume.cc
References fsInstanceCounter.
Referenced by ~G4AssemblyVolume().
void G4AssemblyVolume::InstanceCountPlus () protected
Definition at line 387 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 387 of file G4AssemblyVolume.cc
References fsInstanceCounter.
Referenced by G4AssemblyVolume().
void G4AssemblyVolume::MakeImprint (G4LogicalVolume * pMotherLV, G4ThreeVector & translationInMother, G4RotationMatrix * pRotationInMother, G4int copyNumBase = 0, G4bool surfCheck = false)
Definition at line 336 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 336 of file G4AssemblyVolume.cc
References CLHEP::HepRotation::IDENTITY, and Acts::Test::transform.
Referenced by PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4mRICHDetector::build_mRICH_wall_hside(), PHG4TTLDetector::BuildBarrelTTL(), G02DetectorConstruction::ConstructAssembly(), G4tgbVolume::ConstructG4PhysVol(), PHG4InnerHcalDetector::ConstructInnerHcal(), BeastMagnetDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructMe(), G4EicDircDetector::ConstructMe(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtxPassiveVol(), PHG4OuterHcalDetector::ConstructOuterHcal(), MakeImprint(), and G4GDMLReadStructure::PhysvolRead().
void G4AssemblyVolume::MakeImprint (G4LogicalVolume * pMotherLV, G4Transform3D & transformation, G4int copyNumBase = 0, G4bool surfCheck = false)
Definition at line 363 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 363 of file G4AssemblyVolume.cc
References MakeImprint().
void G4AssemblyVolume::MakeImprint (G4AssemblyVolume * pAssembly, G4LogicalVolume * pMotherLV, G4Transform3D & transformation, G4int copyNumBase = 0, G4bool surfCheck = false) private
Definition at line 239 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 239 of file G4AssemblyVolume.cc
References FatalException, fImprintsTransf, fPVStore, fTriplets, G4Exception(), GetAssemblyID(), GetImprintsCount(), G4LogicalVolume::GetNoDaughters(), pyG4VTouchable::GetRotation, ImprintsCountPlus(), G4ReflectionFactory::Instance(), MakeImprint(), and G4ReflectionFactory::Place().
void G4AssemblyVolume::SetAssemblyID (unsigned int value) inline protected
Referenced by G4AssemblyVolume().
void G4AssemblyVolume::SetImprintsCount (unsigned int value) inline protected
Referenced by G4AssemblyVolume().
void G4AssemblyVolume::SetInstanceCount (unsigned int value) inline protected
Definition at line 382 of file G4AssemblyVolume.cc.
View newest version in sPHENIX GitHub at line 382 of file G4AssemblyVolume.cc
References fsInstanceCounter.
std::size_t G4AssemblyVolume::TotalImprintedVolumes () const inline
Referenced by BeastMagnetDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), and PHG4MvtxDetector::SetDisplayProperty().
std::size_t G4AssemblyVolume::TotalTriplets () const inline
Referenced by G4GDMLWriteStructure::AssemblyWrite().
Member Data Documentation
unsigned int G4AssemblyVolume::fAssemblyID = 0 private
Definition at line 217 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 217 of file G4AssemblyVolume.hh
Referenced by G4AssemblyVolume().
unsigned int G4AssemblyVolume::fImprintsCounter private
Definition at line 209 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 209 of file G4AssemblyVolume.hh
std::map<unsigned int, G4Transform3D> G4AssemblyVolume::fImprintsTransf private
Definition at line 221 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 221 of file G4AssemblyVolume.hh
Referenced by MakeImprint().
std::vector<G4VPhysicalVolume*> G4AssemblyVolume::fPVStore private
Definition at line 198 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 198 of file G4AssemblyVolume.hh
Referenced by MakeImprint(), and ~G4AssemblyVolume().
G4ThreadLocal unsigned int G4AssemblyVolume::fsInstanceCounter = 0 static private
Definition at line 213 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 213 of file G4AssemblyVolume.hh
Referenced by GetInstanceCount(), InstanceCountMinus(), InstanceCountPlus(), and SetInstanceCount().
std::vector<G4AssemblyTriplet> G4AssemblyVolume::fTriplets private
Definition at line 193 of file G4AssemblyVolume.hh.
View newest version in sPHENIX GitHub at line 193 of file G4AssemblyVolume.hh
Referenced by AddPlacedAssembly(), AddPlacedVolume(), MakeImprint(), and ~G4AssemblyVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4AssemblyVolume.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4AssemblyVolume.cc