ECCE @ EIC Software: G4ParticleHPLegendreTable Class Reference
G4ParticleHPLegendreTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLegendreTable.hh>
Public Member Functions
G4ParticleHPLegendreTable ()
~G4ParticleHPLegendreTable ()
void operator= (const G4ParticleHPLegendreTable &aSet)
void Init (std::istream &aDataFile)
void Init (G4double e, G4int n)
void SetEnergy (G4double energy)
void SetTemperature (G4double temp)
void SetCoeff (G4int l, G4double coeff)
void SetRepresentation (G4int aRep)
G4double GetCoeff (G4int l)
G4double GetEnergy ()
G4double GetTemperature ()
G4int GetNumberOfPoly ()
G4int GetRepresentation ()
const G4InterpolationManager & GetManager ()
Private Attributes
G4int theRep
G4double theEnergy
G4double theTemp
G4int nCoeff
G4InterpolationManager theManager
G4double * theCoeff
Detailed Description
Definition at line 39 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPLegendreTable.hh
Constructor & Destructor Documentation
G4ParticleHPLegendreTable::G4ParticleHPLegendreTable () inline
Definition at line 42 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPLegendreTable.hh
References nCoeff, theCoeff, theEnergy, theRep, and theTemp.
G4ParticleHPLegendreTable::~G4ParticleHPLegendreTable () inline
Definition at line 50 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPLegendreTable.hh
References theCoeff.
Member Function Documentation
G4double G4ParticleHPLegendreTable::GetCoeff (G4int l) inline
Definition at line 98 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPLegendreTable.hh
References theCoeff.
Referenced by G4ParticleHPLegendreStore::GetCoeff(), and G4ParticleHPLegendreStore::Integrate().
G4double G4ParticleHPLegendreTable::GetEnergy () inline
Definition at line 99 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPLegendreTable.hh
References theEnergy.
Referenced by G4ParticleHPLegendreStore::GetEnergy(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPLegendreStore::SampleDiscreteTwoBody(), G4ParticleHPLegendreStore::SampleElastic(), and G4ParticleHPLegendreStore::SampleMax().
const G4InterpolationManager& G4ParticleHPLegendreTable::GetManager () inline
Definition at line 103 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPLegendreTable.hh
References theManager.
G4int G4ParticleHPLegendreTable::GetNumberOfPoly () inline
Definition at line 101 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPLegendreTable.hh
References nCoeff.
Referenced by G4ParticleHPLegendreStore::GetNumberOfPoly(), G4ParticleHPLegendreStore::Integrate(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPLegendreStore::SampleDiscreteTwoBody(), G4ParticleHPLegendreStore::SampleElastic(), and G4ParticleHPLegendreStore::SampleMax().
G4int G4ParticleHPLegendreTable::GetRepresentation () inline
Definition at line 102 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPLegendreTable.hh
References theRep.
Referenced by G4ParticleHPDiscreteTwoBody::Sample().
G4double G4ParticleHPLegendreTable::GetTemperature (void) inline
Definition at line 100 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPLegendreTable.hh
References theTemp.
Referenced by G4ParticleHPLegendreStore::GetTemperature().
void G4ParticleHPLegendreTable::Init (std::istream & aDataFile) inline
Definition at line 70 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPLegendreTable.hh
References CLHEP::eV, and SetCoeff().
Referenced by G4ParticleHPLegendreStore::Init(), G4ParticleHPDiscreteTwoBody::Init(), and G4ParticleHPPhotonDist::InitAngular().
void G4ParticleHPLegendreTable::Init (G4double e, G4int n) inline
Definition at line 84 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPLegendreTable.hh
References e, nCoeff, theCoeff, and theEnergy.
void G4ParticleHPLegendreTable::operator= (const G4ParticleHPLegendreTable & aSet) inline
Definition at line 52 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPLegendreTable.hh
References nCoeff, theCoeff, theEnergy, theManager, theRep, and theTemp.
void G4ParticleHPLegendreTable::SetCoeff (G4int l, G4double coeff) inline
Definition at line 95 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPLegendreTable.hh
References theCoeff.
Referenced by G4ParticleHPDiscreteTwoBody::Init(), Init(), and G4ParticleHPLegendreStore::SetCoeff().
void G4ParticleHPLegendreTable::SetEnergy (G4double energy) inline
Definition at line 93 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPLegendreTable.hh
References energy, and theEnergy.
Referenced by G4ParticleHPLegendreStore::SetEnergy().
void G4ParticleHPLegendreTable::SetRepresentation (G4int aRep) inline
Definition at line 96 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPLegendreTable.hh
References theRep.
Referenced by G4ParticleHPDiscreteTwoBody::Init().
void G4ParticleHPLegendreTable::SetTemperature (G4double temp) inline
Definition at line 94 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPLegendreTable.hh
References theTemp.
Referenced by G4ParticleHPLegendreStore::SetTemperature().
Member Data Documentation
G4int G4ParticleHPLegendreTable::nCoeff private
Definition at line 109 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPLegendreTable.hh
Referenced by G4ParticleHPLegendreTable(), GetNumberOfPoly(), Init(), and operator=().
G4double* G4ParticleHPLegendreTable::theCoeff private
Definition at line 111 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPLegendreTable.hh
Referenced by G4ParticleHPLegendreTable(), GetCoeff(), Init(), operator=(), SetCoeff(), and ~G4ParticleHPLegendreTable().
G4double G4ParticleHPLegendreTable::theEnergy private
Definition at line 107 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPLegendreTable.hh
Referenced by G4ParticleHPLegendreTable(), GetEnergy(), Init(), operator=(), and SetEnergy().
G4InterpolationManager G4ParticleHPLegendreTable::theManager private
Definition at line 110 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPLegendreTable.hh
Referenced by GetManager(), and operator=().
G4int G4ParticleHPLegendreTable::theRep private
Definition at line 106 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPLegendreTable.hh
Referenced by G4ParticleHPLegendreTable(), GetRepresentation(), operator=(), and SetRepresentation().
G4double G4ParticleHPLegendreTable::theTemp private
Definition at line 108 of file G4ParticleHPLegendreTable.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPLegendreTable.hh
Referenced by G4ParticleHPLegendreTable(), GetTemperature(), operator=(), and SetTemperature().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLegendreTable.hh