ECCE @ EIC Software: G4PreCompoundIon Class Reference
G4PreCompoundIon Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundIon.hh>
Public Member Functions
G4PreCompoundIon (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4PreCompoundIon ()
Public Member Functions inherited from G4PreCompoundFragment
G4PreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4PreCompoundFragment ()
G4double CalcEmissionProbability (const G4Fragment &aFragment)
G4double SampleKineticEnergy (const G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundFragment
G4VPreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4VPreCompoundFragment ()
void Initialize (const G4Fragment &aFragment)
G4bool IsItPossible (const G4Fragment &aFragment) const
G4ReactionProduct * GetReactionProduct () const
G4int GetA () const
G4int GetZ () const
G4int GetRestA () const
G4int GetRestZ () const
G4double GetBindingEnergy () const
G4double GetEnergyThreshold () const
G4double GetEmissionProbability () const
G4double GetNuclearMass () const
G4double GetRestNuclearMass () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Protected Member Functions
virtual G4double GetRj (G4int NumberParticles, G4int NumberCharged) const =0
virtual G4double GetBeta () const
virtual G4double ProbabilityDistributionFunction (G4double eKin, const G4Fragment &aFragment)
virtual G4double FactorialFactor (G4int N, G4int P) const =0
virtual G4double CoalescenceFactor (G4int A) const =0
Protected Member Functions inherited from G4PreCompoundFragment
virtual G4double GetAlpha () const =0
G4double CrossSection (G4double ekin) const
Private Member Functions
G4PreCompoundIon ()
G4PreCompoundIon (const G4PreCompoundIon &right)
const G4PreCompoundIon & operator= (const G4PreCompoundIon &right)
G4bool operator== (const G4PreCompoundIon &right) const
G4bool operator!= (const G4PreCompoundIon &right) const
Private Attributes
G4double fact
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundFragment
G4NuclearLevelData * fNucData
G4DeexPrecoParameters * theParameters
G4Pow * g4calc
G4int theA
G4int theZ
G4int theResA
G4int theResZ
G4int theFragA
G4int theFragZ
G4double theResA13
G4double theBindingEnergy
G4double theMinKinEnergy
G4double theMaxKinEnergy
G4double theResMass
G4double theReducedMass
G4double theMass
G4double theEmissionProbability
G4double theCoulombBarrier
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 41 of file G4PreCompoundIon.hh.
View newest version in sPHENIX GitHub at line 41 of file G4PreCompoundIon.hh
Constructor & Destructor Documentation
G4PreCompoundIon::G4PreCompoundIon (const G4ParticleDefinition * part, G4VCoulombBarrier * aCoulombBarrier)
Definition at line 48 of file G4PreCompoundIon.cc.
View newest version in sPHENIX GitHub at line 48 of file G4PreCompoundIon.cc
References fact, G4DeexPrecoParameters::GetR0(), CLHEP::millibarn, CLHEP::pi, and G4VPreCompoundFragment::theParameters.
G4PreCompoundIon::~G4PreCompoundIon () virtual
Definition at line 56 of file G4PreCompoundIon.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PreCompoundIon.cc
G4PreCompoundIon::G4PreCompoundIon () private
G4PreCompoundIon::G4PreCompoundIon (const G4PreCompoundIon & right) private
Member Function Documentation
virtual G4double G4PreCompoundIon::CoalescenceFactor (G4int A) const protected pure virtual
Implemented in G4PreCompoundAlpha, G4PreCompoundDeuteron, G4PreCompoundHe3, and G4PreCompoundTriton.
Referenced by ProbabilityDistributionFunction().
virtual G4double G4PreCompoundIon::FactorialFactor (G4int N, G4int P) const protected pure virtual
Implemented in G4PreCompoundAlpha, G4PreCompoundDeuteron, G4PreCompoundHe3, and G4PreCompoundTriton.
Referenced by ProbabilityDistributionFunction().
G4double G4PreCompoundIon::GetBeta () const protected virtual
Implements G4PreCompoundFragment.
Definition at line 101 of file G4PreCompoundIon.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PreCompoundIon.cc
References G4VPreCompoundFragment::theCoulombBarrier.
virtual G4double G4PreCompoundIon::GetRj (G4int NumberParticles, G4int NumberCharged) const protected pure virtual
Implemented in G4PreCompoundAlpha, G4PreCompoundDeuteron, G4PreCompoundHe3, and G4PreCompoundTriton.
Referenced by ProbabilityDistributionFunction().
G4bool G4PreCompoundIon::operator!= (const G4PreCompoundIon & right) const private
const G4PreCompoundIon& G4PreCompoundIon::operator= (const G4PreCompoundIon & right) private
G4bool G4PreCompoundIon::operator== (const G4PreCompoundIon & right) const private
G4double G4PreCompoundIon::ProbabilityDistributionFunction (G4double eKin, const G4Fragment & aFragment) protected virtual
Implements G4PreCompoundFragment.
Definition at line 60 of file G4PreCompoundIon.cc.
View newest version in sPHENIX GitHub at line 60 of file G4PreCompoundIon.cc
References A(), CoalescenceFactor(), G4PreCompoundFragment::CrossSection(), fact, FactorialFactor(), G4VPreCompoundFragment::fNucData, G4VPreCompoundFragment::g4calc, G4VPreCompoundFragment::GetA(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), GetRj(), H, max, N, P, CLHEP::pi2, G4Pow::powN(), G4VPreCompoundFragment::theBindingEnergy, G4VPreCompoundFragment::theFragA, G4VPreCompoundFragment::theFragZ, G4VPreCompoundFragment::theMaxKinEnergy, G4VPreCompoundFragment::theReducedMass, G4VPreCompoundFragment::theResA, and G4VPreCompoundFragment::theResZ.
Member Data Documentation
G4double G4PreCompoundIon::fact private
Definition at line 75 of file G4PreCompoundIon.hh.
View newest version in sPHENIX GitHub at line 75 of file G4PreCompoundIon.hh
Referenced by G4PreCompoundIon(), and ProbabilityDistributionFunction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundIon.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4PreCompoundIon.cc