ECCE @ EIC Software: G4BinaryCascade Class Reference
G4BinaryCascade Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4BinaryCascade.hh>
Public Member Functions
G4BinaryCascade (G4VPreCompoundModel *ptr=0)
virtual ~G4BinaryCascade ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &theNucleus)
virtual G4ReactionProductVector * Propagate (G4KineticTrackVector *, G4V3DNucleus *)
virtual void ModelDescription (std::ostream &) const
virtual void PropagateModelDescription (std::ostream &) const
Public Member Functions inherited from G4VIntraNuclearTransportModel
G4VIntraNuclearTransportModel (const G4String &mName="CascadeModel", G4VPreCompoundModel *ptr=nullptr)
virtual ~G4VIntraNuclearTransportModel ()
virtual G4ReactionProductVector * PropagateNuclNucl (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus, G4V3DNucleus *theProjectileNucleus)
void SetDeExcitation (G4VPreCompoundModel *ptr)
void Set3DNucleus (G4V3DNucleus *const value)
void SetPrimaryProjectile (const G4HadProjectile &aPrimary)
const G4String & GetModelName () const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4BinaryCascade (const G4BinaryCascade &right)
const G4BinaryCascade & operator= (G4BinaryCascade &right)
G4bool operator== (G4BinaryCascade &right)
G4bool operator!= (G4BinaryCascade &right)
void PrintWelcomeMessage ()
void BuildTargetList ()
G4bool BuildLateParticleCollisions (G4KineticTrackVector *secondaries)
void FindCollisions (G4KineticTrackVector *)
void FindDecayCollision (G4KineticTrack *)
void FindLateParticleCollision (G4KineticTrack *)
G4ReactionProductVector * DeExcite ()
G4ReactionProductVector * DecayVoidNucleus ()
G4ReactionProductVector * ProductsAddFinalState (G4ReactionProductVector *products, G4KineticTrackVector &finalState)
G4ReactionProductVector * ProductsAddPrecompound (G4ReactionProductVector *products, G4ReactionProductVector *preco)
G4bool ApplyCollision (G4CollisionInitialState *)
G4bool Capture (G4bool verbose=false)
G4bool Absorb ()
G4bool CheckPauliPrinciple (G4KineticTrackVector *)
G4double GetExcitationEnergy ()
void CorrectFinalPandE ()
G4double CorrectShortlivedPrimaryForFermi (G4KineticTrack *primary, G4KineticTrackVector target_collection)
G4bool CorrectShortlivedFinalsForFermi (G4KineticTrackVector *products, G4double initial_Efermi)
void UpdateTracksAndCollisions (G4KineticTrackVector *oldSecondaries, G4KineticTrackVector *oldTarget, G4KineticTrackVector *newSecondaries)
G4bool DoTimeStep (G4double timeStep)
G4KineticTrackVector * CorrectBarionsOnBoundary (G4KineticTrackVector *in, G4KineticTrackVector *out)
G4Fragment * FindFragments ()
void StepParticlesOut ()
G4LorentzVector GetFinal4Momentum ()
G4LorentzVector GetFinalNucleusMomentum ()
G4ReactionProductVector * Propagate1H1 (G4KineticTrackVector *, G4V3DNucleus *)
G4double GetIonMass (G4int Z, G4int A)
G4int GetTotalCharge (std::vector< G4KineticTrack * > &aV)
G4int GetTotalBaryonCharge (std::vector< G4KineticTrack * > &aV)
G4ReactionProductVector * HighEnergyModelFSProducts (G4ReactionProductVector *, G4KineticTrackVector *secondaries)
G4ReactionProductVector * FillVoidNucleusProducts (G4ReactionProductVector *)
G4ThreeVector GetSpherePoint (G4double r, const G4LorentzVector &momentumdirection)
void ClearAndDestroy (G4KineticTrackVector *ktv)
void ClearAndDestroy (G4ReactionProductVector *rpv)
G4ReactionProductVector * ProductsAddFakeGamma (G4ReactionProductVector *products)
void PrintKTVector (G4KineticTrackVector *ktv, std::string comment=std::string(""))
void PrintKTVector (G4KineticTrack *kt, std::string comment=std::string(""))
void DebugApplyCollisionFail (G4CollisionInitialState *collision, G4KineticTrackVector *products)
void DebugApplyCollision (G4CollisionInitialState *collision, G4KineticTrackVector *products)
G4bool DebugFinalEpConservation (const G4HadProjectile &aTrack, G4ReactionProductVector *products)
G4bool DebugEpConservation (const G4String where)
G4bool CheckChargeAndBaryonNumber (G4String where)
Private Attributes
G4KineticTrackVector theProjectileList
G4KineticTrackVector theTargetList
G4KineticTrackVector theSecondaryList
G4KineticTrackVector theCapturedList
G4KineticTrackVector theFinalState
G4ExcitationHandler * theExcitationHandler
G4CollisionManager * theCollisionMgr
G4Scatterer * theH1Scatterer
std::vector< G4BCAction * > theImR
G4BCDecay * theDecay
G4BCLateParticle * theLateParticle
G4VFieldPropagation * thePropagator
G4DecayKineticTracks decayKTV
G4double theCurrentTime
G4double theBCminP
G4double theCutOnP
G4double theCutOnPAbsorb
G4LorentzVector theInitial4Mom
G4LorentzVector theProjectile4Momentum
G4int currentA
G4int currentZ
G4int lateA
G4int lateZ
G4int initialZ
G4int initialA
G4int projectileA
G4int projectileZ
G4double massInNucleus
G4double initial_nuclear_mass
G4double currentInitialEnergy
G4LorentzRotation precompoundLorentzboost
G4double theOuterRadius
G4bool thePrimaryEscape
const G4ParticleDefinition * thePrimaryType
G4ThreeVector theMomentumTransfer
Static Private Attributes
static G4int theBIC_ID = -1
Additional Inherited Members
Protected Member Functions inherited from G4VIntraNuclearTransportModel
G4V3DNucleus * Get3DNucleus () const
G4VPreCompoundModel * GetDeExcitation () const
const G4HadProjectile * GetPrimaryProjectile () const
Protected Attributes inherited from G4VIntraNuclearTransportModel
G4String theTransportModelName
G4V3DNucleus * the3DNucleus
G4VPreCompoundModel * theDeExcitation
const G4HadProjectile * thePrimaryProjectile
Detailed Description
Definition at line 72 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BinaryCascade.hh
Constructor & Destructor Documentation
G4BinaryCascade::G4BinaryCascade (G4VPreCompoundModel * ptr = 0)
Definition at line 120 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 120 of file G4BinaryCascade.cc
References G4ShortLivedConstructor::ConstructParticle(), currentA, currentInitialEnergy, currentZ, G4HadronicInteractionRegistry::FindModel(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4VIntraNuclearTransportModel::GetDeExcitation(), G4VPreCompoundModel::GetExcitationHandler(), GeV, initial_nuclear_mass, initialA, initialZ, G4HadronicInteractionRegistry::Instance(), lateA, lateZ, massInNucleus, MeV, perCent, projectileA, projectileZ, G4PhysicsModelCatalog::Register(), G4VIntraNuclearTransportModel::SetDeExcitation(), G4HadronicInteraction::SetEnergyMomentumCheckLevels(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theBCminP, theBIC_ID, theCollisionMgr, theCurrentTime, theCutOnP, theCutOnPAbsorb, theDecay, theExcitationHandler, theH1Scatterer, theImR, theLateParticle, theOuterRadius, thePrimaryEscape, thePrimaryType, and thePropagator.
G4BinaryCascade::~G4BinaryCascade () virtual
Definition at line 189 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 189 of file G4BinaryCascade.cc
References ClearAndDestroy(), theCapturedList, theCollisionMgr, theH1Scatterer, theImR, theLateParticle, thePropagator, theSecondaryList, and theTargetList.
G4BinaryCascade::G4BinaryCascade (const G4BinaryCascade & right) private
Member Function Documentation
G4bool G4BinaryCascade::Absorb () private
Definition at line 1484 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1484 of file G4BinaryCascade.cc
References CheckPauliPrinciple(), ClearAndDestroy(), G4Absorber::FindAbsorbers(), G4Absorber::FindProducts(), G4Absorber::GetAbsorbers(), G4Absorber::GetProducts(), G4KineticTrack::GetState(), G4KineticTrack::inside, theCutOnPAbsorb, theSecondaryList, theTargetList, UpdateTracksAndCollisions(), and G4Absorber::WillBeAbsorbed().
Referenced by Propagate(), and StepParticlesOut().
G4bool G4BinaryCascade::ApplyCollision (G4CollisionInitialState * collision) private
Definition at line 1258 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1258 of file G4BinaryCascade.cc
References CheckPauliPrinciple(), ClearAndDestroy(), CorrectShortlivedFinalsForFermi(), CorrectShortlivedPrimaryForFermi(), currentA, currentZ, DebugApplyCollision(), DebugApplyCollisionFail(), eplus, FindDecayCollision(), G4cerr, G4cout, G4endl, G4lrint(), G4KineticTrack::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4KineticTrack::GetDefinition(), G4CollisionInitialState::GetFinalState(), G4CollisionInitialState::GetGenerator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4CollisionInitialState::GetPrimary(), G4KineticTrack::GetState(), G4CollisionInitialState::GetTargetBaryonNumber(), G4CollisionInitialState::GetTargetCharge(), G4CollisionInitialState::GetTargetCollection(), G4KineticTrack::GetTrackingMomentum(), G4KineticTrack::gone_out, G4KineticTrack::Hit(), G4KineticTrack::inside, it, lateA, lateZ, G4KineticTrack::miss_nucleus, G4KineticTrack::outside, G4CollisionManager::Print(), G4CollisionInitialState::Print(), PrintKTVector(), G4CollisionManager::RemoveTracksCollisions(), G4KineticTrack::Set4Momentum(), theCollisionMgr, theFinalState, thePropagator, and UpdateTracksAndCollisions().
Referenced by Propagate(), and StepParticlesOut().
G4HadFinalState * G4BinaryCascade::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & theNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 270 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 270 of file G4BinaryCascade.cc
References G4HadFinalState::AddSecondary(), G4HadronicInteraction::ApplyYourself(), G4HadFinalState::Clear(), G4CollisionManager::ClearAndDestroy(), ClearAndDestroy(), CLHEP::HepLorentzVector::e(), fermi, G4cerr, G4endl, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetGlobalTime(), G4HadProjectile::GetKineticEnergy(), G4V3DNucleus::GetOuterRadius(), GetSpherePoint(), G4Nucleus::GetZ_asInt(), G4VFieldPropagation::Init(), G4V3DNucleus::Init(), isAlive, CLHEP::HepLorentzVector::m(), G4Neutron::NeutronDefinition(), G4KineticTrack::outside, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), Propagate(), Propagate1H1(), G4Proton::ProtonDefinition(), radius, G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetMomentumChange(), G4KineticTrack::SetState(), G4HadFinalState::SetStatusChange(), stopAndKill, G4VIntraNuclearTransportModel::the3DNucleus, theBCminP, theCollisionMgr, theCurrentTime, G4VIntraNuclearTransportModel::theDeExcitation, G4HadronicInteraction::theParticleChange, thePrimaryEscape, thePrimaryType, thePropagator, Acts::VectorHelpers::time(), CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
G4bool G4BinaryCascade::BuildLateParticleCollisions (G4KineticTrackVector * secondaries) private
Definition at line 863 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 863 of file G4BinaryCascade.cc
References DBL_MAX, CLHEP::HepLorentzVector::e(), eplus, FindLateParticleCollision(), G4cout, G4endl, G4lrint(), G4HadProjectile::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4VIntraNuclearTransportModel::GetPrimaryProjectile(), initial_nuclear_mass, lateA, lateZ, massInNucleus, mom, projectileA, projectileZ, theProjectile4Momentum, theSecondaryList, and G4KineticTrack::undefined.
Referenced by Propagate().
void G4BinaryCascade::BuildTargetList () private
Definition at line 790 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 790 of file G4BinaryCascade.cc
References G4Nucleon::AreYouHit(), ClearAndDestroy(), currentA, currentInitialEnergy, currentZ, CLHEP::HepLorentzVector::e(), G4cerr, G4cout, G4endl, G4V3DNucleus::GetCharge(), G4Nucleon::GetDefinition(), GetIonMass(), G4V3DNucleus::GetMassNumber(), G4Nucleon::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Nucleon::GetPosition(), initial_nuclear_mass, initialA, initialZ, G4KineticTrack::inside, CLHEP::Hep3Vector::mag2(), massInNucleus, mom, G4Neutron::Neutron(), G4InuclParticleNames::nucleon(), pos(), CLHEP::HepLorentzVector::setE(), G4KineticTrack::SetNucleon(), G4KineticTrack::SetState(), sqr(), G4V3DNucleus::StartLoop(), G4VIntraNuclearTransportModel::the3DNucleus, theInitial4Mom, theProjectile4Momentum, theTargetList, and CLHEP::HepLorentzVector::vect().
Referenced by Propagate().
G4bool G4BinaryCascade::Capture (G4bool verbose = false) private
Definition at line 1548 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1548 of file G4BinaryCascade.cc
References CLHEP::HepLorentzVector::e(), energy, G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), G4RKPropagation::GetBarrier(), G4KineticTrack::GetDefinition(), G4RKPropagation::GetField(), G4ParticleDefinition::GetPDGEncoding(), G4KineticTrack::GetPosition(), G4KineticTrack::GetState(), G4KineticTrack::Hit(), G4KineticTrack::inside, CLHEP::Hep3Vector::mag(), G4Neutron::Neutron(), G4Proton::Proton(), theCapturedList, theCutOnP, theOuterRadius, thePropagator, theSecondaryList, and UpdateTracksAndCollisions().
Referenced by Propagate(), and StepParticlesOut().
G4bool G4BinaryCascade::CheckChargeAndBaryonNumber (G4String where) private
Definition at line 3169 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3169 of file G4BinaryCascade.cc
References currentA, currentZ, eplus, G4cout, G4endl, G4lrint(), G4V3DNucleus::GetCharge(), G4V3DNucleus::GetMassNumber(), G4KineticTrack::inside, lateA, lateZ, projectileA, projectileZ, G4VIntraNuclearTransportModel::the3DNucleus, theCapturedList, theFinalState, and theSecondaryList.
G4bool G4BinaryCascade::CheckPauliPrinciple (G4KineticTrackVector * products) private
Definition at line 1616 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1616 of file G4BinaryCascade.cc
References A(), G4V3DNucleus::CoulombBarrier(), d, CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4V3DNucleus::GetCharge(), G4VNuclearDensity::GetDensity(), G4FermiMomentum::GetFermiMomentum(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGEncoding(), G4FermiMomentum::Init(), CLHEP::HepLorentzVector::mag(), MeV, mom, G4Neutron::Neutron(), pos(), G4Proton::Proton(), sqr(), G4VIntraNuclearTransportModel::the3DNucleus, thePropagator, and Z.
Referenced by Absorb(), and ApplyCollision().
void G4BinaryCascade::ClearAndDestroy (G4KineticTrackVector * ktv) private
Definition at line 2806 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2806 of file G4BinaryCascade.cc
Referenced by Absorb(), ApplyCollision(), ApplyYourself(), BuildTargetList(), Propagate(), Propagate1H1(), and ~G4BinaryCascade().
void G4BinaryCascade::ClearAndDestroy (G4ReactionProductVector * rpv) private
Definition at line 2816 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2816 of file G4BinaryCascade.cc
G4KineticTrackVector * G4BinaryCascade::CorrectBarionsOnBoundary (G4KineticTrackVector * in, G4KineticTrackVector * out) private
Definition at line 2298 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2298 of file G4BinaryCascade.cc
References G4KineticTrack::captured, currentA, currentZ, eplus, G4cerr, G4cout, G4endl, G4lrint(), G4RKPropagation::GetBarrier(), GetIonMass(), G4ParticleDefinition::GetPDGMass(), massInNucleus, G4KineticTrack::miss_nucleus, G4Neutron::Neutron(), PrintKTVector(), G4Proton::Proton(), theCapturedList, thePropagator, theSecondaryList, and theTargetList.
Referenced by DoTimeStep().
void G4BinaryCascade::CorrectFinalPandE () private
Definition at line 1918 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1918 of file G4BinaryCascade.cc
References CLHEP::HepLorentzVector::boostVector(), currentA, currentZ, CLHEP::HepLorentzVector::e(), G4cerr, G4cout, G4endl, GetFinal4Momentum(), GetIonMass(), CLHEP::HepLorentzRotation::inverse(), CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), massInNucleus, max, PrintKTVector(), G4InuclParticleNames::s0, theFinalState, and CLHEP::Hep3Vector::unit().
Referenced by Propagate().
G4bool G4BinaryCascade::CorrectShortlivedFinalsForFermi (G4KineticTrackVector * products, G4double initial_Efermi) private
Definition at line 1878 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1878 of file G4BinaryCascade.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::e(), CLHEP::HepLorentzVector::mag2(), mom, thePropagator, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by ApplyCollision().
G4double G4BinaryCascade::CorrectShortlivedPrimaryForFermi (G4KineticTrack * primary, G4KineticTrackVector target_collection) private
Definition at line 1849 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1849 of file G4BinaryCascade.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::e(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGEncoding(), G4KineticTrack::GetPosition(), G4KineticTrack::GetState(), G4KineticTrack::inside, G4Neutron::Neutron(), thePropagator, and G4KineticTrack::Update4Momentum().
Referenced by ApplyCollision().
void G4BinaryCascade::DebugApplyCollision (G4CollisionInitialState * collision, G4KineticTrackVector * products) private
Definition at line 3221 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3221 of file G4BinaryCascade.cc
References currentA, currentInitialEnergy, currentZ, Acts::Test::delta, CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4RKPropagation::GetBarrier(), G4ParticleDefinition::GetBaryonNumber(), G4KineticTrack::GetDefinition(), G4RKPropagation::GetField(), GetIonMass(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4KineticTrack::GetPosition(), G4CollisionInitialState::GetPrimary(), G4CollisionInitialState::GetTargetCollection(), GetTotalCharge(), it, PrintKTVector(), and thePropagator.
Referenced by ApplyCollision().
void G4BinaryCascade::DebugApplyCollisionFail (G4CollisionInitialState * collision, G4KineticTrackVector * products) private
Definition at line 3136 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3136 of file G4BinaryCascade.cc
References kdfinder::abs(), G4cout, G4endl, G4KineticTrack::GetDefinition(), G4CollisionInitialState::GetGenerator(), G4ParticleDefinition::GetParticleName(), G4CollisionInitialState::GetPrimary(), G4CollisionInitialState::GetTargetCollection(), it, and PrintKTVector().
Referenced by ApplyCollision().
G4bool G4BinaryCascade::DebugEpConservation (const G4String where) private
Definition at line 3342 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3342 of file G4BinaryCascade.cc
References kdfinder::abs(), e, G4cout, G4endl, G4HadFinalState::GetWeightChange(), theCapturedList, theFinalState, theMomentumTransfer, G4HadronicInteraction::theParticleChange, theSecondaryList, and theTargetList.
G4bool G4BinaryCascade::DebugFinalEpConservation (const G4HadProjectile & aTrack, G4ReactionProductVector * products) private
Definition at line 3307 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3307 of file G4BinaryCascade.cc
References kdfinder::abs(), e, CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4HadProjectile::Get4Momentum(), GetFinal4Momentum(), G4HadFinalState::GetWeightChange(), MeV, perCent, theInitial4Mom, and G4HadronicInteraction::theParticleChange.
G4ReactionProductVector * G4BinaryCascade::DecayVoidNucleus () private
Definition at line 1021 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1021 of file G4BinaryCascade.cc
References CLHEP::HepLorentzVector::boostVector(), G4FermiPhaseSpaceDecay::Decay(), G4INCL::ClusterDecay::decay(), GetFinal4Momentum(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), mass, MeV, precompoundLorentzboost, CLHEP::HepLorentzRotation::set(), G4ReactionProduct::SetCreatorModel(), CLHEP::HepLorentzVector::setE(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), sqr(), theBIC_ID, theCapturedList, theTargetList, and CLHEP::HepLorentzVector::vect().
Referenced by DeExcite().
G4ReactionProductVector * G4BinaryCascade::DeExcite () private
Definition at line 945 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 945 of file G4BinaryCascade.cc
References G4ExcitationHandler::BreakItUp(), DecayVoidNucleus(), G4VPreCompoundModel::DeExcite(), CLHEP::HepLorentzVector::e(), FindFragments(), G4cout, G4endl, G4Fragment::GetA_asInt(), GetFinalNucleusMomentum(), G4Fragment::GetMomentum(), G4ReactionProduct::SetCreatorModel(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), theBIC_ID, theCapturedList, G4VIntraNuclearTransportModel::theDeExcitation, theExcitationHandler, and theTargetList.
Referenced by Propagate().
G4bool G4BinaryCascade::DoTimeStep (G4double timeStep) private
Definition at line 2111 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2111 of file G4BinaryCascade.cc
References G4KineticTrack::captured, CorrectBarionsOnBoundary(), currentA, currentZ, Acts::IntegrationTest::debug, G4ping::dump(), G4CollisionManager::Entries(), G4cerr, G4cout, G4endl, G4VFieldPropagation::GetMomentumTransfer(), G4CollisionManager::GetNextCollision(), G4CollisionInitialState::GetPrimary(), GetTotalCharge(), G4KineticTrack::gone_out, G4KineticTrack::inside, G4KineticTrack::miss_nucleus, G4KineticTrack::outside, PrintKTVector(), G4ping::push_back(), theCapturedList, theCollisionMgr, theCurrentTime, theFinalState, theMomentumTransfer, thePropagator, theSecondaryList, theTargetList, G4VFieldPropagation::Transport(), and UpdateTracksAndCollisions().
Referenced by Propagate(), and StepParticlesOut().
G4ReactionProductVector * G4BinaryCascade::FillVoidNucleusProducts (G4ReactionProductVector * products) private
Definition at line 2902 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2902 of file G4BinaryCascade.cc
References kdfinder::abs(), G4DecayKineticTracks::Decay(), decayKTV, CLHEP::HepLorentzVector::e(), G4CollisionManager::Entries(), G4cout, G4endl, G4UniformRand, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4CollisionInitialState::GetFinalState(), G4ReactionProduct::GetMomentum(), G4CollisionManager::GetNextCollision(), G4CollisionInitialState::GetTargetCollection(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), initial_nuclear_mass, CLHEP::Hep3Vector::mag(), MeV, perCent, G4CollisionManager::RemoveCollision(), reverse, G4ReactionProduct::SetCreatorModel(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetNewlyAdded(), G4ReactionProduct::SetTotalEnergy(), theBIC_ID, theCapturedList, theCollisionMgr, theFinalState, theMomentumTransfer, theProjectile4Momentum, theSecondaryList, theTargetList, and CLHEP::HepLorentzVector::vect().
Referenced by Propagate().
void G4BinaryCascade::FindCollisions (G4KineticTrackVector * secondaries) private
Definition at line 1178 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1178 of file G4BinaryCascade.cc
References G4CollisionManager::AddCollision(), theCollisionMgr, theCurrentTime, theImR, and theTargetList.
Referenced by Propagate(), StepParticlesOut(), and UpdateTracksAndCollisions().
void G4BinaryCascade::FindDecayCollision (G4KineticTrack * secondary) private
Definition at line 1202 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1202 of file G4BinaryCascade.cc
References G4CollisionManager::AddCollision(), G4BCDecay::GetCollisions(), theCollisionMgr, theCurrentTime, theDecay, and theTargetList.
Referenced by ApplyCollision().
G4Fragment * G4BinaryCascade::FindFragments () private
Definition at line 2503 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2503 of file G4BinaryCascade.cc
References a, eplus, G4cout, G4endl, G4lrint(), GetExcitationEnergy(), GetFinalNucleusMomentum(), G4V3DNucleus::GetMassNumber(), GetTotalCharge(), PrintKTVector(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), G4Fragment::SetNumberOfParticles(), G4VIntraNuclearTransportModel::the3DNucleus, theCapturedList, theSecondaryList, theTargetList, and z.
Referenced by DeExcite().
void G4BinaryCascade::FindLateParticleCollision (G4KineticTrack * secondary) private
Definition at line 1214 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1214 of file G4BinaryCascade.cc
References G4CollisionManager::AddCollision(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4BCLateParticle::GetCollisions(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4KineticTrack::GetState(), G4KineticTrack::inside, G4KineticTrack::miss_nucleus, G4KineticTrack::outside, G4KineticTrack::SetState(), theCollisionMgr, theCurrentTime, theLateParticle, thePropagator, and theTargetList.
Referenced by BuildLateParticleCollisions().
G4double G4BinaryCascade::GetExcitationEnergy () private
Definition at line 697 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 697 of file G4BinaryCascade.cc
References A(), currentA, currentZ, Acts::IntegrationTest::debug, G4ping::dump(), G4cerr, G4cout, G4endl, G4V3DNucleus::GetCharge(), GetFinalNucleusMomentum(), GetIonMass(), G4V3DNucleus::GetMassNumber(), G4ParticleDefinition::GetPDGMass(), GetTotalCharge(), CLHEP::HepLorentzVector::mag(), MeV, G4Neutron::Neutron(), G4ping::push_back(), G4VIntraNuclearTransportModel::the3DNucleus, theCapturedList, theInitial4Mom, theTargetList, and Z.
Referenced by FindFragments(), Propagate(), and StepParticlesOut().
G4LorentzVector G4BinaryCascade::GetFinal4Momentum () private
Definition at line 2584 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2584 of file G4BinaryCascade.cc
References currentA, currentZ, CLHEP::HepLorentzVector::e(), G4cerr, G4endl, CLHEP::HepLorentzVector::m(), theFinalState, theInitial4Mom, theProjectile4Momentum, and CLHEP::HepLorentzVector::vect().
Referenced by CorrectFinalPandE(), DebugFinalEpConservation(), DecayVoidNucleus(), GetFinalNucleusMomentum(), and Propagate().
G4LorentzVector G4BinaryCascade::GetFinalNucleusMomentum () private
Definition at line 2621 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2621 of file G4BinaryCascade.cc
References CLHEP::HepLorentzVector::e(), G4cerr, G4cout, G4endl, GetFinal4Momentum(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), precompoundLorentzboost, CLHEP::HepLorentzRotation::set(), theCapturedList, and CLHEP::HepLorentzVector::vect().
Referenced by DeExcite(), FindFragments(), GetExcitationEnergy(), and Propagate().
G4double G4BinaryCascade::GetIonMass (G4int Z, G4int A) private
Definition at line 2869 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2869 of file G4BinaryCascade.cc
References G4cerr, G4endl, G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), mass, and G4Neutron::Neutron().
Referenced by BuildTargetList(), CorrectBarionsOnBoundary(), CorrectFinalPandE(), DebugApplyCollision(), and GetExcitationEnergy().
G4ThreeVector G4BinaryCascade::GetSpherePoint (G4double r, const G4LorentzVector & momentumdirection) private
Definition at line 2764 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2764 of file G4BinaryCascade.cc
References CLHEP::Hep3Vector::cross(), G4UniformRand, mom, CLHEP::Hep3Vector::orthogonal(), sqr(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), x1, and x2.
Referenced by ApplyYourself().
G4int G4BinaryCascade::GetTotalBaryonCharge (std::vector< G4KineticTrack * > & aV) inline private
Definition at line 148 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 148 of file G4BinaryCascade.hh
References G4lrint().
G4int G4BinaryCascade::GetTotalCharge (std::vector< G4KineticTrack * > & aV) inline private
Definition at line 138 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 138 of file G4BinaryCascade.hh
References G4lrint().
Referenced by DebugApplyCollision(), DoTimeStep(), FindFragments(), and GetExcitationEnergy().
G4ReactionProductVector * G4BinaryCascade::HighEnergyModelFSProducts (G4ReactionProductVector * products, G4KineticTrackVector * secondaries) private
Definition at line 3084 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3084 of file G4BinaryCascade.cc
References G4Alpha::AlphaDefinition(), currentA, currentZ, G4Deuteron::DeuteronDefinition(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4He3::He3Definition(), massInNucleus, G4Neutron::NeutronDefinition(), G4Proton::ProtonDefinition(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetNewlyAdded(), G4ReactionProduct::SetTotalEnergy(), and G4Triton::TritonDefinition().
Referenced by Propagate().
void G4BinaryCascade::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4VIntraNuclearTransportModel.
Definition at line 202 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 202 of file G4BinaryCascade.cc
References G4VPreCompoundModel::DeExciteModelDescription(), G4HadronicInteraction::GetModelName(), G4ExcitationHandler::ModelDescription(), G4VIntraNuclearTransportModel::theDeExcitation, and theExcitationHandler.
G4bool G4BinaryCascade::operator!= (G4BinaryCascade & right) inline private
Definition at line 93 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BinaryCascade.hh
const G4BinaryCascade& G4BinaryCascade::operator= (G4BinaryCascade & right) private
G4bool G4BinaryCascade::operator== (G4BinaryCascade & right) inline private
Definition at line 92 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BinaryCascade.hh
void G4BinaryCascade::PrintKTVector (G4KineticTrackVector * ktv, std::string comment = std::string("")) private
Definition at line 2826 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2826 of file G4BinaryCascade.cc
References G4cout, and G4endl.
Referenced by ApplyCollision(), CorrectBarionsOnBoundary(), CorrectFinalPandE(), DebugApplyCollision(), DebugApplyCollisionFail(), DoTimeStep(), FindFragments(), Propagate(), Propagate1H1(), StepParticlesOut(), and UpdateTracksAndCollisions().
void G4BinaryCascade::PrintKTVector (G4KineticTrack * kt, std::string comment = std::string("")) private
Definition at line 2847 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2847 of file G4BinaryCascade.cc
References fermi, G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGEncoding(), G4KineticTrack::GetPosition(), G4KineticTrack::GetState(), G4KineticTrack::GetTrackingMomentum(), G4KineticTrack::IsParticipant(), CLHEP::Hep3Vector::mag(), CLHEP::HepLorentzVector::mag(), MeV, mom, pos(), and CLHEP::HepLorentzVector::vect().
void G4BinaryCascade::PrintWelcomeMessage () private
Definition at line 3130 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3130 of file G4BinaryCascade.cc
References G4cout, and G4endl.
G4ReactionProductVector * G4BinaryCascade::ProductsAddFakeGamma (G4ReactionProductVector * products) private
Definition at line 3409 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 3409 of file G4BinaryCascade.cc
G4ReactionProductVector * G4BinaryCascade::ProductsAddFinalState (G4ReactionProductVector * products, G4KineticTrackVector & finalState) private
Definition at line 1109 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1109 of file G4BinaryCascade.cc
References CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ReactionProduct::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGStable(), G4KineticTrack::IsParticipant(), G4ParticleDefinition::IsShortLived(), G4ReactionProduct::SetCreatorModel(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetNewlyAdded(), G4ReactionProduct::SetTotalEnergy(), theBIC_ID, and CLHEP::HepLorentzVector::vect().
Referenced by Propagate().
G4ReactionProductVector * G4BinaryCascade::ProductsAddPrecompound (G4ReactionProductVector * products, G4ReactionProductVector * preco) private
Definition at line 1144 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1144 of file G4BinaryCascade.cc
References G4cout, G4endl, and precompoundLorentzboost.
Referenced by Propagate().
G4ReactionProductVector * G4BinaryCascade::Propagate (G4KineticTrackVector * secondaries, G4V3DNucleus * aNucleus) virtual
Implements G4VIntraNuclearTransportModel.
Definition at line 403 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 403 of file G4BinaryCascade.cc
References _CheckChargeAndBaryonNumber_, _DebugEpConservation, Absorb(), ApplyCollision(), BuildLateParticleCollisions(), BuildTargetList(), Capture(), G4CollisionManager::ClearAndDestroy(), ClearAndDestroy(), CorrectFinalPandE(), currentZ, Acts::IntegrationTest::debug, G4INCL::ClusterDecay::decay(), DeExcite(), DoTimeStep(), G4CollisionManager::Entries(), FillVoidNucleusProducts(), FindCollisions(), G4cerr, G4cout, G4endl, G4CollisionInitialState::GetCollisionTime(), GetExcitationEnergy(), GetFinal4Momentum(), GetFinalNucleusMomentum(), G4V3DNucleus::GetMass(), G4CollisionManager::GetNextCollision(), G4V3DNucleus::GetOuterRadius(), HighEnergyModelFSProducts(), G4VFieldPropagation::Init(), CLHEP::Hep3Vector::mag(), CLHEP::HepLorentzVector::mag(), MeV, PrintKTVector(), ProductsAddFinalState(), ProductsAddPrecompound(), G4Proton::Proton(), G4CollisionManager::RemoveCollision(), StepParticlesOut(), G4VIntraNuclearTransportModel::the3DNucleus, theCapturedList, theCollisionMgr, theCurrentTime, theCutOnP, theFinalState, theMomentumTransfer, theOuterRadius, thePrimaryEscape, theProjectile4Momentum, thePropagator, theSecondaryList, and theTargetList.
Referenced by ApplyYourself(), and G4BinaryLightIonReaction::Interact().
G4ReactionProductVector * G4BinaryCascade::Propagate1H1 (G4KineticTrackVector * secondaries, G4V3DNucleus * nucleus) private
Definition at line 2668 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2668 of file G4BinaryCascade.cc
References ClearAndDestroy(), CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4V3DNucleus::GetCharge(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGStable(), G4ParticleDefinition::IsShortLived(), mass, mom, G4Neutron::NeutronDefinition(), pos(), PrintKTVector(), G4Proton::ProtonDefinition(), G4Scatterer::Scatter(), G4ReactionProduct::SetCreatorModel(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), theBIC_ID, theFinalState, theH1Scatterer, and CLHEP::HepLorentzVector::vect().
Referenced by ApplyYourself().
void G4BinaryCascade::PropagateModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4VIntraNuclearTransportModel.
Definition at line 229 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 229 of file G4BinaryCascade.cc
References G4VPreCompoundModel::DeExciteModelDescription(), G4HadronicInteraction::GetModelName(), G4ExcitationHandler::ModelDescription(), G4VIntraNuclearTransportModel::theDeExcitation, and theExcitationHandler.
void G4BinaryCascade::StepParticlesOut () private
Definition at line 1700 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 1700 of file G4BinaryCascade.cc
References Absorb(), ApplyCollision(), Capture(), currentZ, DBL_MAX, DoTimeStep(), G4CollisionManager::Entries(), FindCollisions(), G4cerr, G4cout, G4endl, G4CollisionInitialState::GetCollisionTime(), G4KineticTrack::GetDefinition(), GetExcitationEnergy(), G4CollisionManager::GetNextCollision(), G4ParticleDefinition::GetParticleName(), G4KineticTrack::GetState(), G4KineticTrack::GetTrackingMomentum(), G4KineticTrack::inside, CLHEP::Hep3Vector::mag(), ns, G4KineticTrack::outside, PrintKTVector(), G4CollisionManager::RemoveCollision(), theCapturedList, theCollisionMgr, theCurrentTime, theFinalState, theMomentumTransfer, thePropagator, theSecondaryList, and theTargetList.
Referenced by Propagate().
void G4BinaryCascade::UpdateTracksAndCollisions (G4KineticTrackVector * oldSecondaries, G4KineticTrackVector * oldTarget, G4KineticTrackVector * newSecondaries) private
Definition at line 2026 of file G4BinaryCascade.cc.
View newest version in sPHENIX GitHub at line 2026 of file G4BinaryCascade.cc
References FindCollisions(), PrintKTVector(), G4CollisionManager::RemoveTracksCollisions(), theCollisionMgr, theSecondaryList, theTargetList, and G4KineticTrack::undefined.
Referenced by Absorb(), ApplyCollision(), Capture(), and DoTimeStep().
Member Data Documentation
G4int G4BinaryCascade::currentA private
Definition at line 210 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 210 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), BuildTargetList(), CheckChargeAndBaryonNumber(), CorrectBarionsOnBoundary(), CorrectFinalPandE(), DebugApplyCollision(), DoTimeStep(), G4BinaryCascade(), GetExcitationEnergy(), GetFinal4Momentum(), and HighEnergyModelFSProducts().
G4double G4BinaryCascade::currentInitialEnergy private
Definition at line 213 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 213 of file G4BinaryCascade.hh
Referenced by BuildTargetList(), DebugApplyCollision(), and G4BinaryCascade().
G4int G4BinaryCascade::currentZ private
Definition at line 210 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 210 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), BuildTargetList(), CheckChargeAndBaryonNumber(), CorrectBarionsOnBoundary(), CorrectFinalPandE(), DebugApplyCollision(), DoTimeStep(), G4BinaryCascade(), GetExcitationEnergy(), GetFinal4Momentum(), HighEnergyModelFSProducts(), Propagate(), and StepParticlesOut().
G4DecayKineticTracks G4BinaryCascade::decayKTV private
Definition at line 202 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 202 of file G4BinaryCascade.hh
Referenced by FillVoidNucleusProducts().
G4double G4BinaryCascade::initial_nuclear_mass private
Definition at line 212 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 212 of file G4BinaryCascade.hh
Referenced by BuildLateParticleCollisions(), BuildTargetList(), FillVoidNucleusProducts(), and G4BinaryCascade().
G4int G4BinaryCascade::initialA private
Definition at line 211 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 211 of file G4BinaryCascade.hh
Referenced by BuildTargetList(), and G4BinaryCascade().
G4int G4BinaryCascade::initialZ private
Definition at line 211 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 211 of file G4BinaryCascade.hh
Referenced by BuildTargetList(), and G4BinaryCascade().
G4int G4BinaryCascade::lateA private
Definition at line 210 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 210 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), BuildLateParticleCollisions(), CheckChargeAndBaryonNumber(), and G4BinaryCascade().
G4int G4BinaryCascade::lateZ private
Definition at line 210 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 210 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), BuildLateParticleCollisions(), CheckChargeAndBaryonNumber(), and G4BinaryCascade().
G4double G4BinaryCascade::massInNucleus private
Definition at line 212 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 212 of file G4BinaryCascade.hh
Referenced by BuildLateParticleCollisions(), BuildTargetList(), CorrectBarionsOnBoundary(), CorrectFinalPandE(), G4BinaryCascade(), and HighEnergyModelFSProducts().
G4LorentzRotation G4BinaryCascade::precompoundLorentzboost private
Definition at line 214 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 214 of file G4BinaryCascade.hh
Referenced by DecayVoidNucleus(), GetFinalNucleusMomentum(), and ProductsAddPrecompound().
G4int G4BinaryCascade::projectileA private
Definition at line 211 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 211 of file G4BinaryCascade.hh
Referenced by BuildLateParticleCollisions(), CheckChargeAndBaryonNumber(), and G4BinaryCascade().
G4int G4BinaryCascade::projectileZ private
Definition at line 211 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 211 of file G4BinaryCascade.hh
Referenced by BuildLateParticleCollisions(), CheckChargeAndBaryonNumber(), and G4BinaryCascade().
G4double G4BinaryCascade::theBCminP private
Definition at line 205 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 205 of file G4BinaryCascade.hh
Referenced by ApplyYourself(), and G4BinaryCascade().
G4int G4BinaryCascade::theBIC_ID = -1 static private
Definition at line 219 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 219 of file G4BinaryCascade.hh
Referenced by DecayVoidNucleus(), DeExcite(), FillVoidNucleusProducts(), G4BinaryCascade(), ProductsAddFinalState(), and Propagate1H1().
G4KineticTrackVector G4BinaryCascade::theCapturedList private
Definition at line 189 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 189 of file G4BinaryCascade.hh
Referenced by Capture(), CheckChargeAndBaryonNumber(), CorrectBarionsOnBoundary(), DebugEpConservation(), DecayVoidNucleus(), DeExcite(), DoTimeStep(), FillVoidNucleusProducts(), FindFragments(), GetExcitationEnergy(), GetFinalNucleusMomentum(), Propagate(), StepParticlesOut(), and ~G4BinaryCascade().
G4CollisionManager* G4BinaryCascade::theCollisionMgr private
Definition at line 194 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 194 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), ApplyYourself(), DoTimeStep(), FillVoidNucleusProducts(), FindCollisions(), FindDecayCollision(), FindLateParticleCollision(), G4BinaryCascade(), Propagate(), StepParticlesOut(), UpdateTracksAndCollisions(), and ~G4BinaryCascade().
G4double G4BinaryCascade::theCurrentTime private
Definition at line 204 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 204 of file G4BinaryCascade.hh
Referenced by ApplyYourself(), DoTimeStep(), FindCollisions(), FindDecayCollision(), FindLateParticleCollision(), G4BinaryCascade(), Propagate(), and StepParticlesOut().
G4double G4BinaryCascade::theCutOnP private
Definition at line 206 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 206 of file G4BinaryCascade.hh
Referenced by Capture(), G4BinaryCascade(), and Propagate().
G4double G4BinaryCascade::theCutOnPAbsorb private
Definition at line 207 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 207 of file G4BinaryCascade.hh
Referenced by Absorb(), and G4BinaryCascade().
G4BCDecay* G4BinaryCascade::theDecay private
Definition at line 199 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 199 of file G4BinaryCascade.hh
Referenced by FindDecayCollision(), and G4BinaryCascade().
G4ExcitationHandler* G4BinaryCascade::theExcitationHandler private
Definition at line 193 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 193 of file G4BinaryCascade.hh
Referenced by DeExcite(), G4BinaryCascade(), ModelDescription(), and PropagateModelDescription().
G4KineticTrackVector G4BinaryCascade::theFinalState private
Definition at line 190 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 190 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), CheckChargeAndBaryonNumber(), CorrectFinalPandE(), DebugEpConservation(), DoTimeStep(), FillVoidNucleusProducts(), GetFinal4Momentum(), Propagate(), Propagate1H1(), and StepParticlesOut().
G4Scatterer* G4BinaryCascade::theH1Scatterer private
Definition at line 196 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 196 of file G4BinaryCascade.hh
Referenced by G4BinaryCascade(), Propagate1H1(), and ~G4BinaryCascade().
std::vector<G4BCAction *> G4BinaryCascade::theImR private
Definition at line 198 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 198 of file G4BinaryCascade.hh
Referenced by FindCollisions(), G4BinaryCascade(), and ~G4BinaryCascade().
G4LorentzVector G4BinaryCascade::theInitial4Mom private
Definition at line 208 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 208 of file G4BinaryCascade.hh
Referenced by BuildTargetList(), DebugFinalEpConservation(), GetExcitationEnergy(), and GetFinal4Momentum().
G4BCLateParticle* G4BinaryCascade::theLateParticle private
Definition at line 200 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 200 of file G4BinaryCascade.hh
Referenced by FindLateParticleCollision(), G4BinaryCascade(), and ~G4BinaryCascade().
G4ThreeVector G4BinaryCascade::theMomentumTransfer private
Definition at line 218 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 218 of file G4BinaryCascade.hh
Referenced by DebugEpConservation(), DoTimeStep(), FillVoidNucleusProducts(), Propagate(), and StepParticlesOut().
G4double G4BinaryCascade::theOuterRadius private
Definition at line 215 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 215 of file G4BinaryCascade.hh
Referenced by Capture(), G4BinaryCascade(), and Propagate().
G4bool G4BinaryCascade::thePrimaryEscape private
Definition at line 216 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 216 of file G4BinaryCascade.hh
Referenced by ApplyYourself(), G4BinaryCascade(), and Propagate().
const G4ParticleDefinition* G4BinaryCascade::thePrimaryType private
Definition at line 217 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 217 of file G4BinaryCascade.hh
Referenced by ApplyYourself(), and G4BinaryCascade().
G4LorentzVector G4BinaryCascade::theProjectile4Momentum private
Definition at line 209 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 209 of file G4BinaryCascade.hh
Referenced by BuildLateParticleCollisions(), BuildTargetList(), FillVoidNucleusProducts(), GetFinal4Momentum(), and Propagate().
G4KineticTrackVector G4BinaryCascade::theProjectileList private
Definition at line 186 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 186 of file G4BinaryCascade.hh
G4VFieldPropagation* G4BinaryCascade::thePropagator private
Definition at line 201 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 201 of file G4BinaryCascade.hh
Referenced by ApplyCollision(), ApplyYourself(), Capture(), CheckPauliPrinciple(), CorrectBarionsOnBoundary(), CorrectShortlivedFinalsForFermi(), CorrectShortlivedPrimaryForFermi(), DebugApplyCollision(), DoTimeStep(), FindLateParticleCollision(), G4BinaryCascade(), Propagate(), StepParticlesOut(), and ~G4BinaryCascade().
G4KineticTrackVector G4BinaryCascade::theSecondaryList private
Definition at line 188 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 188 of file G4BinaryCascade.hh
Referenced by Absorb(), BuildLateParticleCollisions(), Capture(), CheckChargeAndBaryonNumber(), CorrectBarionsOnBoundary(), DebugEpConservation(), DoTimeStep(), FillVoidNucleusProducts(), FindFragments(), Propagate(), StepParticlesOut(), UpdateTracksAndCollisions(), and ~G4BinaryCascade().
G4KineticTrackVector G4BinaryCascade::theTargetList private
Definition at line 187 of file G4BinaryCascade.hh.
View newest version in sPHENIX GitHub at line 187 of file G4BinaryCascade.hh
Referenced by Absorb(), BuildTargetList(), CorrectBarionsOnBoundary(), DebugEpConservation(), DecayVoidNucleus(), DeExcite(), DoTimeStep(), FillVoidNucleusProducts(), FindCollisions(), FindDecayCollision(), FindFragments(), FindLateParticleCollision(), GetExcitationEnergy(), Propagate(), StepParticlesOut(), UpdateTracksAndCollisions(), and ~G4BinaryCascade().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4BinaryCascade.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4BinaryCascade.cc