ECCE @ EIC Software: G4VisCommandSceneAddUserAction Class Reference
G4VisCommandSceneAddUserAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh>
Public Member Functions
G4VisCommandSceneAddUserAction ()
virtual ~G4VisCommandSceneAddUserAction ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommandScene
G4VVisCommandScene ()
virtual ~G4VVisCommandScene ()
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Types
enum ActionType { runDuration, endOfEvent, endOfRun }
Private Member Functions
G4VisCommandSceneAddUserAction (const G4VisCommandSceneAddUserAction &)
G4VisCommandSceneAddUserAction & operator= (const G4VisCommandSceneAddUserAction &)
void AddVisAction (const G4String &name, G4VUserVisAction *, G4Scene *, ActionType, G4VisManager::Verbosity)
Private Attributes
G4UIcmdWithAString * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommandScene
G4String CurrentSceneName ()
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 424 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 424 of file G4VisCommandsSceneAdd.hh
Member Enumeration Documentation
enum G4VisCommandSceneAddUserAction::ActionType private
Enumerator:
runDuration
endOfEvent
endOfRun
Definition at line 433 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 433 of file G4VisCommandsSceneAdd.hh
Constructor & Destructor Documentation
G4VisCommandSceneAddUserAction::G4VisCommandSceneAddUserAction ()
Definition at line 2758 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2758 of file G4VisCommandsSceneAdd.cc
References G4VisCommandSceneAddText2D::fpCommand.
G4VisCommandSceneAddUserAction::~G4VisCommandSceneAddUserAction () virtual
Definition at line 2773 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2773 of file G4VisCommandsSceneAdd.cc
References G4VisCommandSceneAddText2D::fpCommand.
G4VisCommandSceneAddUserAction::G4VisCommandSceneAddUserAction (const G4VisCommandSceneAddUserAction &) private
Member Function Documentation
void G4VisCommandSceneAddUserAction::AddVisAction (const G4String & name, G4VUserVisAction * visAction, G4Scene * pScene, G4VisCommandSceneAddUserAction::ActionType type, G4VisManager::Verbosity verbosity) private
Definition at line 2840 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2840 of file G4VisCommandsSceneAdd.cc
References G4VisManager::confirmations, G4VVisCommand::fpVisManager, G4cout, G4endl, G4VVisCommand::G4VisCommandsSceneAddUnsuccessful(), G4VisExtent::GetExtentRadius(), G4VisManager::GetUserVisActionExtents(), if(), G4VisManager::parameters, G4VModel::SetExtent(), G4VModel::SetGlobalDescription(), G4VModel::SetGlobalTag(), G4VModel::SetType(), and G4VisManager::warnings.
G4String G4VisCommandSceneAddUserAction::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 2777 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2777 of file G4VisCommandsSceneAdd.cc
G4VisCommandSceneAddUserAction& G4VisCommandSceneAddUserAction::operator= (const G4VisCommandSceneAddUserAction &) private
void G4VisCommandSceneAddUserAction::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 2782 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2782 of file G4VisCommandsSceneAdd.cc
References G4VVisCommand::CheckSceneAndNotifyHandlers(), G4VisManager::errors, G4VVisCommand::fpVisManager, G4cerr, G4cout, G4endl, G4VisManager::GetCurrentScene(), G4VisManager::GetEndOfEventUserVisActions(), G4VisManager::GetEndOfRunUserVisActions(), G4VisManager::GetRunDurationUserVisActions(), G4VisManager::GetVerbosity(), and G4VisManager::warnings.
Member Data Documentation
G4UIcmdWithAString* G4VisCommandSceneAddUserAction::fpCommand private
Definition at line 436 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 436 of file G4VisCommandsSceneAdd.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSceneAdd.cc