ECCE @ EIC Software: G4VHighEnergyGenerator Class Reference
G4VHighEnergyGenerator Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VHighEnergyGenerator.hh>
Public Member Functions
G4VHighEnergyGenerator (const G4String &modelName="High Energy Generator")
~G4VHighEnergyGenerator () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &, G4Nucleus &) final
virtual G4V3DNucleus * GetWoundedNucleus () const =0
virtual G4V3DNucleus * GetProjectileNucleus () const
virtual G4KineticTrackVector * Scatter (const G4Nucleus &theNucleus, const G4DynamicParticle &thePrimary)=0
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4VHighEnergyGenerator (const G4VHighEnergyGenerator &right)
const G4VHighEnergyGenerator & operator= (const G4VHighEnergyGenerator &right)
G4bool operator== (const G4VHighEnergyGenerator &right) const
G4bool operator!= (const G4VHighEnergyGenerator &right) const
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 48 of file G4VHighEnergyGenerator.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VHighEnergyGenerator.hh
Constructor & Destructor Documentation
G4VHighEnergyGenerator::G4VHighEnergyGenerator (const G4String & modelName = "High Energy Generator")
Definition at line 33 of file G4VHighEnergyGenerator.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VHighEnergyGenerator.cc
G4VHighEnergyGenerator::~G4VHighEnergyGenerator () override
Definition at line 38 of file G4VHighEnergyGenerator.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VHighEnergyGenerator.cc
G4VHighEnergyGenerator::G4VHighEnergyGenerator (const G4VHighEnergyGenerator & right) private
Member Function Documentation
G4HadFinalState * G4VHighEnergyGenerator::ApplyYourself (const G4HadProjectile & , G4Nucleus &) final virtual
Implements G4HadronicInteraction.
Definition at line 43 of file G4VHighEnergyGenerator.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VHighEnergyGenerator.cc
G4V3DNucleus * G4VHighEnergyGenerator::GetProjectileNucleus () const virtual
Reimplemented in G4FTFModel, G4VPartonStringModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Definition at line 53 of file G4VHighEnergyGenerator.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VHighEnergyGenerator.cc
References FatalException, G4Exception(), and G4HadronicInteraction::GetModelName().
Referenced by G4TheoFSGenerator::ApplyYourself().
virtual G4V3DNucleus* G4VHighEnergyGenerator::GetWoundedNucleus () const pure virtual
Implemented in G4FTFModel, G4VPartonStringModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Referenced by G4TheoFSGenerator::ApplyYourself().
void G4VHighEnergyGenerator::ModelDescription (std::ostream & outFile) const override virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4FTFModel, G4VPartonStringModel, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, and G4QGSModel< G4QGSParticipants >.
Definition at line 48 of file G4VHighEnergyGenerator.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VHighEnergyGenerator.cc
Referenced by G4TheoFSGenerator::ModelDescription().
G4bool G4VHighEnergyGenerator::operator!= (const G4VHighEnergyGenerator & right) const private
const G4VHighEnergyGenerator& G4VHighEnergyGenerator::operator= (const G4VHighEnergyGenerator & right) private
G4bool G4VHighEnergyGenerator::operator== (const G4VHighEnergyGenerator & right) const private
virtual G4KineticTrackVector* G4VHighEnergyGenerator::Scatter (const G4Nucleus & theNucleus, const G4DynamicParticle & thePrimary) pure virtual
Implemented in G4VPartonStringModel.
Referenced by G4TheoFSGenerator::ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VHighEnergyGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4VHighEnergyGenerator.cc