ECCE @ EIC Software: G4VisCommandSceneAddDate::Date Struct Reference
G4VisCommandSceneAddDate::Date Struct Reference
Public Member Functions
Date (G4VisManager *vm, G4int size, G4double x, G4double y, G4Text::Layout layout, const G4String &date)
void operator() (G4VGraphicsScene &, const G4Transform3D &, const G4ModelingParameters *)
Public Attributes
G4VisManager * fpVisManager
G4Timer fTimer
G4int fSize
G4double fX
G4double fY
G4Text::Layout fLayout
G4String fDate
Detailed Description
Definition at line 101 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VisCommandsSceneAdd.hh
Constructor & Destructor Documentation
G4VisCommandSceneAddDate::Date::Date (G4VisManager * vm, G4int size, G4double x, G4double y, G4Text::Layout layout, const G4String & date) inline
Definition at line 103 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VisCommandsSceneAdd.hh
Member Function Documentation
void G4VisCommandSceneAddDate::Date::operator() (G4VGraphicsScene & sceneHandler, const G4Transform3D & , const G4ModelingParameters *)
Definition at line 463 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 463 of file G4VisCommandsSceneAdd.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives2D(), G4VGraphicsScene::EndPrimitives2D(), G4Text::SetLayout(), G4VMarker::SetScreenSize(), G4Visible::SetVisAttributes(), and Acts::VectorHelpers::time().
Member Data Documentation
G4String G4VisCommandSceneAddDate::Date::fDate
Definition at line 114 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VisCommandsSceneAdd.hh
G4Text::Layout G4VisCommandSceneAddDate::Date::fLayout
Definition at line 113 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VisCommandsSceneAdd.hh
G4VisManager* G4VisCommandSceneAddDate::Date::fpVisManager
Definition at line 109 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VisCommandsSceneAdd.hh
G4int G4VisCommandSceneAddDate::Date::fSize
Definition at line 111 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VisCommandsSceneAdd.hh
G4Timer G4VisCommandSceneAddDate::Date::fTimer
Definition at line 110 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VisCommandsSceneAdd.hh
G4double G4VisCommandSceneAddDate::Date::fX
Definition at line 112 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VisCommandsSceneAdd.hh
G4double G4VisCommandSceneAddDate::Date::fY
Definition at line 112 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VisCommandsSceneAdd.hh
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSceneAdd.cc