ECCE @ EIC Software: IORTGeometryController Class Reference
IORTGeometryController Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/include/IORTGeometryController.hh>
Public Member Functions
IORTGeometryController ()
~IORTGeometryController ()
void SetGeometry (G4String)
void UpdateGeometry ()
Private Member Functions
void registerGeometry (G4VUserDetectorConstruction *detector)
Detailed Description
Controller for geometry selection
This controller is called by the geometry messenger and used to select the geometry. Each available geometry must have unique name and it must be known by the geometry controller.
Definition at line 54 of file IORTGeometryController.hh.
View newest version in sPHENIX GitHub at line 54 of file IORTGeometryController.hh
Constructor & Destructor Documentation
IORTGeometryController::IORTGeometryController ()
Definition at line 53 of file IORTGeometryController.cc.
View newest version in sPHENIX GitHub at line 53 of file IORTGeometryController.cc
IORTGeometryController::~IORTGeometryController ()
Definition at line 57 of file IORTGeometryController.cc.
View newest version in sPHENIX GitHub at line 57 of file IORTGeometryController.cc
Member Function Documentation
void IORTGeometryController::registerGeometry (G4VUserDetectorConstruction * detector) private
Definition at line 107 of file IORTGeometryController.cc.
View newest version in sPHENIX GitHub at line 107 of file IORTGeometryController.cc
References G4RunManager::GeometryHasBeenModified(), G4RunManager::GetRunManager(), and G4RunManager::SetUserInitialization().
Referenced by SetGeometry().
void IORTGeometryController::SetGeometry (G4String name)
Select a geometry by name.
Definition at line 61 of file IORTGeometryController.cc.
View newest version in sPHENIX GitHub at line 61 of file IORTGeometryController.cc
References G4cout, G4endl, and registerGeometry().
Referenced by main().
void IORTGeometryController::UpdateGeometry ()
Definition at line 115 of file IORTGeometryController.cc.
View newest version in sPHENIX GitHub at line 115 of file IORTGeometryController.cc
References pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/include/IORTGeometryController.hh
geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/src/IORTGeometryController.cc