ECCE @ EIC Software: G4FermiFragment Class Reference
G4FermiFragment Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiFragment.hh>
Public Member Functions
G4FermiFragment (G4int anA, G4int aZ, G4int sp, G4double exc)
~G4FermiFragment ()
G4int GetA (void) const
G4int GetZ (void) const
G4int GetSpin (void) const
G4double GetExcitationEnergy (void) const
G4double GetFragmentMass (void) const
G4double GetTotalEnergy (void) const
G4double GetCoulombBarrier (G4int Ares, G4int Zres, G4double Eex) const
G4bool operator== (const G4FermiFragment &right) const
Private Member Functions
G4FermiFragment (const G4FermiFragment &right)
const G4FermiFragment & operator= (const G4FermiFragment &right)
G4bool operator!= (const G4FermiFragment &right) const
Private Attributes
G4double excitEnergy
G4double fragmentMass
G4CoulombBarrier * cBarrier
G4int A
G4int Z
G4int spin
Detailed Description
Definition at line 38 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 38 of file G4FermiFragment.hh
Constructor & Destructor Documentation
G4FermiFragment::G4FermiFragment (G4int anA, G4int aZ, G4int sp, G4double exc) explicit
Definition at line 35 of file G4FermiFragment.cc.
View newest version in sPHENIX GitHub at line 35 of file G4FermiFragment.cc
References A, cBarrier, fragmentMass, G4NucleiProperties::GetNuclearMass(), and Z.
G4FermiFragment::~G4FermiFragment ()
Definition at line 42 of file G4FermiFragment.cc.
View newest version in sPHENIX GitHub at line 42 of file G4FermiFragment.cc
References cBarrier.
G4FermiFragment::G4FermiFragment (const G4FermiFragment & right) private
Member Function Documentation
G4int G4FermiFragment::GetA (void) const inline
Definition at line 46 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 46 of file G4FermiFragment.hh
References A.
Referenced by G4FermiDecayProbability::ComputeProbability(), G4FermiFragmentsPoolVI::Dump(), G4FermiFragmentsPoolVI::DumpFragment(), G4FermiPair::G4FermiPair(), G4FermiPair::GetDynamicMinMass(), G4FermiFragmentsPoolVI::Initialise(), and G4FermiFragmentsPoolVI::IsInPhysPairs().
G4double G4FermiFragment::GetCoulombBarrier (G4int Ares, G4int Zres, G4double Eex) const inline
Definition at line 76 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FermiFragment.hh
References cBarrier, and G4CoulombBarrier::GetCoulombBarrier().
Referenced by G4FermiDecayProbability::ComputeProbability(), G4FermiPair::GetDynamicMinMass(), and G4FermiFragmentsPoolVI::Initialise().
G4double G4FermiFragment::GetExcitationEnergy (void) const inline
Definition at line 61 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 61 of file G4FermiFragment.hh
References excitEnergy.
Referenced by G4FermiFragmentsPoolVI::Dump(), G4FermiFragmentsPoolVI::DumpFragment(), G4FermiFragmentsPoolVI::HasChannels(), and G4FermiBreakUpVI::SampleDecay().
G4double G4FermiFragment::GetFragmentMass (void) const inline
Definition at line 66 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 66 of file G4FermiFragment.hh
References fragmentMass.
Referenced by G4FermiFragmentsPoolVI::DumpFragment().
G4int G4FermiFragment::GetSpin (void) const inline
Definition at line 56 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 56 of file G4FermiFragment.hh
References spin.
Referenced by G4FermiDecayProbability::ComputeProbability(), G4FermiFragmentsPoolVI::Dump(), G4FermiFragmentsPoolVI::DumpFragment(), and G4FermiFragmentsPoolVI::Initialise().
G4double G4FermiFragment::GetTotalEnergy (void) const inline
Definition at line 71 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 71 of file G4FermiFragment.hh
References excitEnergy, and fragmentMass.
Referenced by G4FermiFragmentsPoolVI::ClosestChannels(), G4FermiDecayProbability::ComputeProbability(), G4FermiFragmentsPoolVI::Dump(), G4FermiPair::G4FermiPair(), G4FermiPair::GetDynamicMinMass(), G4FermiFragmentsPoolVI::Initialise(), and G4FermiBreakUpVI::SampleDecay().
G4int G4FermiFragment::GetZ (void) const inline
Definition at line 51 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 51 of file G4FermiFragment.hh
References Z.
Referenced by G4FermiFragmentsPoolVI::ClosestChannels(), G4FermiDecayProbability::ComputeProbability(), G4FermiFragmentsPoolVI::Dump(), G4FermiFragmentsPoolVI::DumpFragment(), G4FermiPair::G4FermiPair(), G4FermiPair::GetDynamicMinMass(), G4FermiFragmentsPoolVI::HasChannels(), and G4FermiFragmentsPoolVI::Initialise().
G4bool G4FermiFragment::operator!= (const G4FermiFragment & right) const private
const G4FermiFragment& G4FermiFragment::operator= (const G4FermiFragment & right) private
G4bool G4FermiFragment::operator== (const G4FermiFragment & right) const inline
Definition at line 81 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FermiFragment.hh
References A, kdfinder::abs(), excitEnergy, and Z.
Member Data Documentation
G4int G4FermiFragment::A private
Definition at line 94 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 94 of file G4FermiFragment.hh
Referenced by G4FermiFragment(), GetA(), and operator==().
G4CoulombBarrier* G4FermiFragment::cBarrier private
Definition at line 92 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 92 of file G4FermiFragment.hh
Referenced by G4FermiFragment(), GetCoulombBarrier(), and ~G4FermiFragment().
G4double G4FermiFragment::excitEnergy private
Definition at line 89 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 89 of file G4FermiFragment.hh
Referenced by GetExcitationEnergy(), GetTotalEnergy(), and operator==().
G4double G4FermiFragment::fragmentMass private
Definition at line 90 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FermiFragment.hh
Referenced by G4FermiFragment(), GetFragmentMass(), and GetTotalEnergy().
G4int G4FermiFragment::spin private
Definition at line 96 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 96 of file G4FermiFragment.hh
Referenced by GetSpin().
G4int G4FermiFragment::Z private
Definition at line 95 of file G4FermiFragment.hh.
View newest version in sPHENIX GitHub at line 95 of file G4FermiFragment.hh
Referenced by G4FermiFragment(), GetZ(), and operator==().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiFragment.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/src/G4FermiFragment.cc