ECCE @ EIC Software: G3RotTable Class Reference
G3RotTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3RotTable.hh>
Public Member Functions
G3RotTable ()
virtual ~G3RotTable ()
G4RotationMatrix * Get (G4int id) const
void Put (G4int id, G4RotationMatrix *matrix)
void Clear ()
Private Attributes
G3RotMatrixVector * fRotVector
Detailed Description
Definition at line 52 of file G3RotTable.hh.
View newest version in sPHENIX GitHub at line 52 of file G3RotTable.hh
Constructor & Destructor Documentation
G3RotTable::G3RotTable ()
Definition at line 32 of file G3RotTable.cc.
View newest version in sPHENIX GitHub at line 32 of file G3RotTable.cc
References fRotVector.
G3RotTable::~G3RotTable () virtual
Definition at line 37 of file G3RotTable.cc.
View newest version in sPHENIX GitHub at line 37 of file G3RotTable.cc
References fRotVector.
Member Function Documentation
void G3RotTable::Clear ()
Definition at line 58 of file G3RotTable.cc.
View newest version in sPHENIX GitHub at line 58 of file G3RotTable.cc
References a, and fRotVector.
G4RotationMatrix * G3RotTable::Get (G4int id) const
Definition at line 43 of file G3RotTable.cc.
View newest version in sPHENIX GitHub at line 43 of file G3RotTable.cc
References fRotVector, G3RotTableEntry::GetID(), and G3RotTableEntry::GetMatrix().
Referenced by G3toG4BuildPVTree(), and GetTransform3D().
void G3RotTable::Put (G4int id, G4RotationMatrix * matrix)
Definition at line 52 of file G3RotTable.cc.
View newest version in sPHENIX GitHub at line 52 of file G3RotTable.cc
References fRotVector.
Referenced by G4gsrotm().
Member Data Documentation
G3RotMatrixVector* G3RotTable::fRotVector private
Definition at line 67 of file G3RotTable.hh.
View newest version in sPHENIX GitHub at line 67 of file G3RotTable.hh
Referenced by Clear(), G3RotTable(), Get(), Put(), and ~G3RotTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3RotTable.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3RotTable.cc