ECCE @ EIC Software: G4HtmlPPReporter Class Reference
G4HtmlPPReporter Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/utils/include/G4HtmlPPReporter.hh>
Public Member Functions
G4HtmlPPReporter ()
virtual ~G4HtmlPPReporter ()
virtual void Print (const G4String &option="")
Public Member Functions inherited from G4VParticlePropertyReporter
G4VParticlePropertyReporter ()
virtual ~G4VParticlePropertyReporter ()
G4bool operator== (const G4VParticlePropertyReporter &right) const
G4bool operator!= (const G4VParticlePropertyReporter &right) const
virtual G4bool FillList (G4String name)
virtual void Clear ()
const G4PPDContainer & GetList () const
Private Member Functions
void SparseOption (const G4String &option)
void GenerateIndex ()
void GeneratePropertyTable (const G4ParticleDefinition *)
void PrintHeader (std::ofstream &)
void PrintFooter (std::ofstream &)
Private Attributes
G4String baseDir
G4String comment
Static Private Attributes
static const char * sTABLE = "<TABLE WIDTH="
static const char * eTABLE = "</TABLE>"
static const char * sTR = "<TR>"
static const char * eTR = "</TR>"
static const char * sTD = "<TD>"
static const char * eTD = "</TD>"
static const char * sB = "<B>"
static const char * eB = "</B>"
static const char * sLFONT = "<FONT SIZE = +1>"
static const char * eLFONT = "</FONT>"
static const char * sSYMBOL = "<FONT FACE = \"symbol\" >"
static const char * eSYMBOL = "</FONT>"
static const char * sSUP = "<SUP>"
static const char * eSUP = "</SUP>"
static const char * sSUB = "<SUB>"
static const char * eSUB = "</SUB>"
Additional Inherited Members
Public Types inherited from G4VParticlePropertyReporter
typedef std::vector
< G4ParticlePropertyData * > G4PPDContainer
Protected Attributes inherited from G4VParticlePropertyReporter
G4PPDContainer pList
G4ParticlePropertyTable * pPropertyTable
Detailed Description
Definition at line 44 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 44 of file G4HtmlPPReporter.hh
Constructor & Destructor Documentation
G4HtmlPPReporter::G4HtmlPPReporter ()
Definition at line 46 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 46 of file G4HtmlPPReporter.cc
G4HtmlPPReporter::~G4HtmlPPReporter () virtual
Definition at line 51 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HtmlPPReporter.cc
Member Function Documentation
void G4HtmlPPReporter::GenerateIndex () private
Definition at line 82 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 82 of file G4HtmlPPReporter.cc
References baseDir, comment, eLFONT, eplus, eSUP, eTABLE, eTD, eTR, G4ParticleTable::FindParticle(), test::fname, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), GeV, ns, G4VParticlePropertyReporter::pList, PrintFooter(), PrintHeader(), sLFONT, sSUP, sTABLE, sTD, and sTR.
Referenced by Print().
void G4HtmlPPReporter::GeneratePropertyTable (const G4ParticleDefinition * particle) private
Definition at line 164 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 164 of file G4HtmlPPReporter.cc
References baseDir, eB, G4DecayTable::entries(), eplus, eSUP, eSYMBOL, eTABLE, eTD, eTR, G4endl, G4ParticleDefinition::GetAntiQuarkContent(), G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughter(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4VDecayChannel::GetKinematicsName(), G4VDecayChannel::GetNumberOfDaughters(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGiConjugation(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGStable(), G4ParticleDefinition::GetPDGWidth(), G4ParticleDefinition::GetQuarkContent(), GeV, G4ParticleDefinition::IsShortLived(), MeV, PrintFooter(), PrintHeader(), sB, second, sSUP, sSYMBOL, sTABLE, sTD, sTR, and tesla.
Referenced by Print().
void G4HtmlPPReporter::Print (const G4String & option = "") virtual
Implements G4VParticlePropertyReporter.
Definition at line 55 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 55 of file G4HtmlPPReporter.cc
References G4ParticleTable::FindParticle(), GenerateIndex(), GeneratePropertyTable(), G4ParticleTable::GetParticleTable(), particle, G4VParticlePropertyReporter::pList, and SparseOption().
void G4HtmlPPReporter::PrintFooter (std::ofstream & outFile) private
Definition at line 352 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 352 of file G4HtmlPPReporter.cc
References G4endl.
Referenced by GenerateIndex(), and GeneratePropertyTable().
void G4HtmlPPReporter::PrintHeader (std::ofstream & outFile) private
Definition at line 337 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 337 of file G4HtmlPPReporter.cc
References G4endl.
Referenced by GenerateIndex(), and GeneratePropertyTable().
void G4HtmlPPReporter::SparseOption (const G4String & option) private
Definition at line 68 of file G4HtmlPPReporter.cc.
View newest version in sPHENIX GitHub at line 68 of file G4HtmlPPReporter.cc
References baseDir, comment, and G4String::isNull().
Referenced by Print().
Member Data Documentation
G4String G4HtmlPPReporter::baseDir private
Definition at line 76 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), GeneratePropertyTable(), and SparseOption().
G4String G4HtmlPPReporter::comment private
Definition at line 77 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and SparseOption().
const char * G4HtmlPPReporter::eB = "</B>" static private
Definition at line 69 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 69 of file G4HtmlPPReporter.hh
Referenced by GeneratePropertyTable().
const char * G4HtmlPPReporter::eLFONT = "</FONT>" static private
Definition at line 70 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex().
const char * G4HtmlPPReporter::eSUB = "</SUB>" static private
Definition at line 73 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 73 of file G4HtmlPPReporter.hh
const char * G4HtmlPPReporter::eSUP = "</SUP>" static private
Definition at line 72 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::eSYMBOL = "</FONT>" static private
Definition at line 71 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 71 of file G4HtmlPPReporter.hh
Referenced by GeneratePropertyTable().
const char * G4HtmlPPReporter::eTABLE = "</TABLE>" static private
Definition at line 66 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 66 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::eTD = "</TD>" static private
Definition at line 68 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::eTR = "</TR>" static private
Definition at line 67 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::sB = "<B>" static private
Definition at line 69 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 69 of file G4HtmlPPReporter.hh
Referenced by GeneratePropertyTable().
const char * G4HtmlPPReporter::sLFONT = "<FONT SIZE = +1>" static private
Definition at line 70 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex().
const char * G4HtmlPPReporter::sSUB = "<SUB>" static private
Definition at line 73 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 73 of file G4HtmlPPReporter.hh
const char * G4HtmlPPReporter::sSUP = "<SUP>" static private
Definition at line 72 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::sSYMBOL = "<FONT FACE = \"symbol\" >" static private
Definition at line 71 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 71 of file G4HtmlPPReporter.hh
Referenced by GeneratePropertyTable().
const char * G4HtmlPPReporter::sTABLE = "<TABLE WIDTH=" static private
Definition at line 66 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 66 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::sTD = "<TD>" static private
Definition at line 68 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
const char * G4HtmlPPReporter::sTR = "<TR>" static private
Definition at line 67 of file G4HtmlPPReporter.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HtmlPPReporter.hh
Referenced by GenerateIndex(), and GeneratePropertyTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/utils/include/G4HtmlPPReporter.hh
geant4/tree/geant4-10.6-release/source/particles/utils/src/G4HtmlPPReporter.cc