ECCE @ EIC Software: G4AntiNuclElastic Class Reference
G4AntiNuclElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4AntiNuclElastic.hh>
Public Member Functions
G4AntiNuclElastic ()
~G4AntiNuclElastic () override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double SampleThetaCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double SampleThetaLab (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double CalculateParticleBeta (const G4ParticleDefinition *particle, G4double momentum)
G4double CalculateZommerfeld (G4double beta, G4double Z1, G4double Z2)
G4double CalculateAm (G4double momentum, G4double n, G4double Z)
G4double DampFactor (G4double z)
G4double BesselJzero (G4double z)
G4double BesselJone (G4double z)
G4double BesselOneByArg (G4double z)
G4double GetcosTeta1 (G4double plab, G4int A)
G4ComponentAntiNuclNuclearXS * GetComponentCrossSection ()
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4AntiNuclElastic & operator= (const G4AntiNuclElastic &right)
G4AntiNuclElastic (const G4AntiNuclElastic &)
Private Attributes
G4ComponentAntiNuclNuclearXS * cs
const G4ParticleDefinition * fParticle
G4double fTetaCMS
G4double fThetaLab
G4double fWaveVector
G4double fBeta
G4double fZommerfeld
G4double fAm
G4double fRa
G4double fRef
G4double fceff
G4ThreeVector fbst
G4double fptot
G4double fTmax
G4ParticleDefinition * theAProton
G4ParticleDefinition * theANeutron
G4ParticleDefinition * theADeuteron
G4ParticleDefinition * theATriton
G4ParticleDefinition * theAAlpha
G4ParticleDefinition * theAHe3
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4ParticleDefinition * theDeuteron
G4ParticleDefinition * theAlpha
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 46 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 46 of file G4AntiNuclElastic.hh
Constructor & Destructor Documentation
G4AntiNuclElastic::G4AntiNuclElastic () explicit
Definition at line 56 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 56 of file G4AntiNuclElastic.cc
References G4Alpha::Alpha(), G4AntiAlpha::AntiAlpha(), G4AntiDeuteron::AntiDeuteron(), G4AntiHe3::AntiHe3(), G4AntiNeutron::AntiNeutron(), G4AntiProton::AntiProton(), G4AntiTriton::AntiTriton(), cs, G4Deuteron::Deuteron(), fAm, fBeta, fceff, fParticle, fptot, fRa, fRef, fTetaCMS, fThetaLab, fTmax, fWaveVector, fZommerfeld, G4CrossSectionDataSetRegistry::GetComponentCrossSection(), G4CrossSectionDataSetRegistry::Instance(), G4Neutron::Neutron(), G4Proton::Proton(), reg, theAAlpha, theADeuteron, theAHe3, theAlpha, theANeutron, theAProton, theATriton, theDeuteron, theNeutron, and theProton.
G4AntiNuclElastic::~G4AntiNuclElastic () override
Definition at line 94 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 94 of file G4AntiNuclElastic.cc
G4AntiNuclElastic::G4AntiNuclElastic (const G4AntiNuclElastic &) private
Member Function Documentation
G4double G4AntiNuclElastic::BesselJone (G4double z)
Definition at line 589 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 589 of file G4AntiNuclElastic.cc
Referenced by BesselOneByArg().
G4double G4AntiNuclElastic::BesselJzero (G4double z)
Definition at line 538 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 538 of file G4AntiNuclElastic.cc
Referenced by SampleInvariantT().
G4double G4AntiNuclElastic::BesselOneByArg (G4double z)
Definition at line 636 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 636 of file G4AntiNuclElastic.cc
References BesselJone(), x, and x2.
Referenced by SampleInvariantT().
G4double G4AntiNuclElastic::CalculateAm (G4double momentum, G4double n, G4double Z)
Definition at line 522 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 522 of file G4AntiNuclElastic.cc
References G4Pow::A13(), source.hepunit::Bohr_radius, fAm, G4Pow::GetInstance(), source.hepunit::hbarc, k, and n.
Referenced by SampleInvariantT().
G4double G4AntiNuclElastic::CalculateParticleBeta (const G4ParticleDefinition * particle, G4double momentum)
Definition at line 499 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 499 of file G4AntiNuclElastic.cc
References a, fBeta, G4ParticleDefinition::GetPDGMass(), and mass.
Referenced by SampleInvariantT().
G4double G4AntiNuclElastic::CalculateZommerfeld (G4double beta, G4double Z1, G4double Z2)
Definition at line 513 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 513 of file G4AntiNuclElastic.cc
References source.hepunit::fine_structure_const, and fZommerfeld.
Referenced by SampleInvariantT().
G4double G4AntiNuclElastic::DampFactor (G4double z)
Definition at line 479 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 479 of file G4AntiNuclElastic.cc
References f3.
Referenced by SampleInvariantT().
G4ComponentAntiNuclNuclearXS * G4AntiNuclElastic::GetComponentCrossSection () inline
Definition at line 121 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 121 of file G4AntiNuclElastic.hh
References cs.
Referenced by DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), AntiBaryonPhysics::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), and G4HadronElasticPhysics::ConstructProcess().
G4double G4AntiNuclElastic::GetcosTeta1 (G4double plab, G4int A)
Definition at line 655 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 655 of file G4AntiNuclElastic.cc
References fermi, G4Pow::GetInstance(), source.hepunit::hbarc, and G4Pow::Z23().
Referenced by SampleInvariantT().
G4AntiNuclElastic& G4AntiNuclElastic::operator= (const G4AntiNuclElastic & right) private
G4double G4AntiNuclElastic::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) override virtual
Reimplemented from G4HadronicInteraction.
Definition at line 99 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 99 of file G4AntiNuclElastic.cc
References kdfinder::abs(), BesselJzero(), BesselOneByArg(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CalculateAm(), CalculateParticleBeta(), CalculateZommerfeld(), cs, DampFactor(), CLHEP::HepLorentzVector::e(), energy, fbst, fceff, fptot, fRa, fRef, fTetaCMS, fTmax, fWaveVector, G4Exp(), G4Log(), G4UniformRand, G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4ParticleDefinition::GetBaryonNumber(), GetcosTeta1(), G4ComponentAntiNuclNuclearXS::GetElasticElementCrossSection(), G4Pow::GetInstance(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), GeV, G4He3::He3(), CLHEP::Hep3Vector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, millibarn, n, particle, phi, pi, Q, S(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sqr(), T, theAAlpha, theADeuteron, theAHe3, theAlpha, theANeutron, theAProton, theATriton, theDeuteron, theProton, G4Triton::Triton(), twopi, CLHEP::HepLorentzVector::vect(), x, Z, Z1, G4Pow::Z13(), and Z2.
Referenced by SampleThetaCMS(), and SampleThetaLab().
G4double G4AntiNuclElastic::SampleThetaCMS (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A)
Definition at line 387 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 387 of file G4AntiNuclElastic.cc
References fptot, fTetaCMS, fTmax, G4cout, G4endl, G4UniformRand, GeV, SampleInvariantT(), T, and G4HadronicInteraction::verboseLevel.
G4double G4AntiNuclElastic::SampleThetaLab (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A)
Definition at line 423 of file G4AntiNuclElastic.cc.
View newest version in sPHENIX GitHub at line 423 of file G4AntiNuclElastic.cc
References CLHEP::HepLorentzVector::boost(), fbst, fptot, fThetaLab, fTmax, G4cout, G4endl, G4UniformRand, G4ParticleDefinition::GetPDGMass(), GeV, phi, SampleInvariantT(), T, CLHEP::Hep3Vector::theta(), theta(), twopi, v, G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4ComponentAntiNuclNuclearXS* G4AntiNuclElastic::cs private
Definition at line 89 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 89 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), GetComponentCrossSection(), and SampleInvariantT().
G4double G4AntiNuclElastic::fAm private
Definition at line 97 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AntiNuclElastic.hh
Referenced by CalculateAm(), and G4AntiNuclElastic().
G4double G4AntiNuclElastic::fBeta private
Definition at line 95 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AntiNuclElastic.hh
Referenced by CalculateParticleBeta(), and G4AntiNuclElastic().
G4ThreeVector G4AntiNuclElastic::fbst private
Definition at line 102 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AntiNuclElastic.hh
Referenced by SampleInvariantT(), and SampleThetaLab().
G4double G4AntiNuclElastic::fceff private
Definition at line 100 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
const G4ParticleDefinition* G4AntiNuclElastic::fParticle private
Definition at line 90 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 90 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic().
G4double G4AntiNuclElastic::fptot private
Definition at line 103 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), SampleInvariantT(), SampleThetaCMS(), and SampleThetaLab().
G4double G4AntiNuclElastic::fRa private
Definition at line 98 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4double G4AntiNuclElastic::fRef private
Definition at line 99 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4double G4AntiNuclElastic::fTetaCMS private
Definition at line 92 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 92 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), SampleInvariantT(), and SampleThetaCMS().
G4double G4AntiNuclElastic::fThetaLab private
Definition at line 93 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 93 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleThetaLab().
G4double G4AntiNuclElastic::fTmax private
Definition at line 104 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), SampleInvariantT(), SampleThetaCMS(), and SampleThetaLab().
G4double G4AntiNuclElastic::fWaveVector private
Definition at line 94 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 94 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4double G4AntiNuclElastic::fZommerfeld private
Definition at line 96 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AntiNuclElastic.hh
Referenced by CalculateZommerfeld(), and G4AntiNuclElastic().
G4ParticleDefinition* G4AntiNuclElastic::theAAlpha private
Definition at line 110 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theADeuteron private
Definition at line 108 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theAHe3 private
Definition at line 111 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theAlpha private
Definition at line 116 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theANeutron private
Definition at line 107 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theAProton private
Definition at line 106 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theATriton private
Definition at line 109 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theDeuteron private
Definition at line 115 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
G4ParticleDefinition* G4AntiNuclElastic::theNeutron private
Definition at line 114 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic().
G4ParticleDefinition* G4AntiNuclElastic::theProton private
Definition at line 113 of file G4AntiNuclElastic.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AntiNuclElastic.hh
Referenced by G4AntiNuclElastic(), and SampleInvariantT().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4AntiNuclElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4AntiNuclElastic.cc