ECCE @ EIC Software: G4ParallelWorldProcessStore Class Reference
G4ParallelWorldProcessStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4ParallelWorldProcessStore.hh>
Public Member Functions
virtual ~G4ParallelWorldProcessStore ()
void SetParallelWorld (G4ParallelWorldProcess *proc, G4String parallelWorldName)
void UpdateWorlds ()
G4ParallelWorldProcess * GetProcess (G4String parallelWorldName)
void Clear ()
Static Public Member Functions
static
G4ParallelWorldProcessStore * GetInstance ()
static
G4ParallelWorldProcessStore * GetInstanceIfExist ()
Private Member Functions
G4ParallelWorldProcessStore ()
Static Private Attributes
static G4ThreadLocal
G4ParallelWorldProcessStore * fInstance =0
Additional Inherited Members
Public Attributes inherited from std::map< K, T >
K keys
STL member.
T elements
STL member.
Detailed Description
Definition at line 61 of file G4ParallelWorldProcessStore.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParallelWorldProcessStore.hh
Constructor & Destructor Documentation
G4ParallelWorldProcessStore::G4ParallelWorldProcessStore () private
Definition at line 47 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParallelWorldProcessStore.cc
Referenced by GetInstance().
G4ParallelWorldProcessStore::~G4ParallelWorldProcessStore () virtual
Definition at line 50 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ParallelWorldProcessStore.cc
References Clear(), and fInstance.
Member Function Documentation
void G4ParallelWorldProcessStore::Clear ()
Definition at line 96 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ParallelWorldProcessStore.cc
References fInstance.
Referenced by ~G4ParallelWorldProcessStore().
G4ParallelWorldProcessStore * G4ParallelWorldProcessStore::GetInstance (void) static
Definition at line 35 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ParallelWorldProcessStore.cc
References fInstance, and G4ParallelWorldProcessStore().
Referenced by G4ParallelWorldProcess::G4ParallelWorldProcess(), G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
G4ParallelWorldProcessStore * G4ParallelWorldProcessStore::GetInstanceIfExist () static
Definition at line 42 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ParallelWorldProcessStore.cc
References fInstance.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
G4ParallelWorldProcess * G4ParallelWorldProcessStore::GetProcess (G4String parallelWorldName)
Definition at line 88 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ParallelWorldProcessStore.cc
References fInstance.
void G4ParallelWorldProcessStore::SetParallelWorld (G4ParallelWorldProcess * proc, G4String parallelWorldName)
Definition at line 56 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParallelWorldProcessStore.cc
References FatalException, fInstance, and G4Exception().
Referenced by G4ParallelWorldProcess::G4ParallelWorldProcess(), and UpdateWorlds().
void G4ParallelWorldProcessStore::UpdateWorlds ()
Definition at line 81 of file G4ParallelWorldProcessStore.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ParallelWorldProcessStore.cc
References fInstance, and SetParallelWorld().
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
Member Data Documentation
G4ThreadLocal G4ParallelWorldProcessStore * G4ParallelWorldProcessStore::fInstance =0 static private
Definition at line 69 of file G4ParallelWorldProcessStore.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParallelWorldProcessStore.hh
Referenced by Clear(), GetInstance(), GetInstanceIfExist(), GetProcess(), SetParallelWorld(), UpdateWorlds(), and ~G4ParallelWorldProcessStore().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4ParallelWorldProcessStore.hh
geant4/tree/geant4-10.6-release/source/processes/scoring/src/G4ParallelWorldProcessStore.cc