ECCE @ EIC Software: G4VTwistSurface::CurrentStatus Class Reference
G4VTwistSurface::CurrentStatus Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh>
Public Member Functions
CurrentStatus ()
virtual ~CurrentStatus ()
G4ThreeVector GetXX (G4int i) const
G4double GetDistance (G4int i) const
G4int GetAreacode (G4int i) const
G4int GetNXX () const
G4bool IsDone () const
G4bool IsValid (G4int i) const
void SetCurrentStatus (G4int i, G4ThreeVector &xx, G4double &dist, G4int &areacode, G4bool &isvalid, G4int nxx, EValidate validate, const G4ThreeVector *p, const G4ThreeVector *v=nullptr)
void ResetfDone (EValidate validate, const G4ThreeVector *p, const G4ThreeVector *v=nullptr)
void DebugPrint () const
Private Attributes
G4double fDistance [G4VSURFACENXX]
G4ThreeVector fXX [G4VSURFACENXX]
G4int fAreacode [G4VSURFACENXX]
G4bool fIsValid [G4VSURFACENXX]
G4int fNXX
G4ThreeVector fLastp
G4ThreeVector fLastv
EValidate fLastValidate
G4bool fDone
Detailed Description
Definition at line 239 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 239 of file G4VTwistSurface.hh
Constructor & Destructor Documentation
G4VTwistSurface::CurrentStatus::CurrentStatus ()
Definition at line 1172 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1172 of file G4VTwistSurface.cc
References fAreacode, fDistance, fDone, fIsValid, fLastp, fLastv, fLastValidate, fNXX, fXX, G4VSURFACENXX, kInfinity, G4VTwistSurface::kUninitialized, CLHEP::Hep3Vector::set(), and G4VTwistSurface::sOutside.
G4VTwistSurface::CurrentStatus::~CurrentStatus () virtual
Definition at line 1191 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1191 of file G4VTwistSurface.cc
Member Function Documentation
void G4VTwistSurface::CurrentStatus::DebugPrint () const
Definition at line 1267 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1267 of file G4VTwistSurface.cc
References G4cout, and G4endl.
G4int G4VTwistSurface::CurrentStatus::GetAreacode (G4int i) const inline
Definition at line 248 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 248 of file G4VTwistSurface.hh
References fAreacode.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4double G4VTwistSurface::CurrentStatus::GetDistance (G4int i) const inline
Definition at line 247 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 247 of file G4VTwistSurface.hh
References fDistance.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4int G4VTwistSurface::CurrentStatus::GetNXX () const inline
Definition at line 249 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 249 of file G4VTwistSurface.hh
References fNXX.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4ThreeVector G4VTwistSurface::CurrentStatus::GetXX (G4int i) const inline
Definition at line 246 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 246 of file G4VTwistSurface.hh
References fXX.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4bool G4VTwistSurface::CurrentStatus::IsDone () const inline
Definition at line 250 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 250 of file G4VTwistSurface.hh
References fDone.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4bool G4VTwistSurface::CurrentStatus::IsValid (G4int i) const inline
Definition at line 251 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 251 of file G4VTwistSurface.hh
References fIsValid.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
void G4VTwistSurface::CurrentStatus::ResetfDone (EValidate validate, const G4ThreeVector * p, const G4ThreeVector * v = nullptr)
Definition at line 1239 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1239 of file G4VTwistSurface.cc
References G4VSURFACENXX, kInfinity, G4VTwistSurface::kUninitialized, G4VTwistSurface::sOutside, and xx.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
void G4VTwistSurface::CurrentStatus::SetCurrentStatus (G4int i, G4ThreeVector & xx, G4double & dist, G4int & areacode, G4bool & isvalid, G4int nxx, EValidate validate, const G4ThreeVector * p, const G4ThreeVector * v = nullptr)
Definition at line 1199 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1199 of file G4VTwistSurface.cc
References FatalException, G4Exception(), kInfinity, v, and xx.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
Member Data Documentation
G4int G4VTwistSurface::CurrentStatus::fAreacode[G4VSURFACENXX] private
Definition at line 274 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 274 of file G4VTwistSurface.hh
Referenced by CurrentStatus(), and GetAreacode().
G4double G4VTwistSurface::CurrentStatus::fDistance[G4VSURFACENXX] private
Definition at line 272 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 272 of file G4VTwistSurface.hh
Referenced by CurrentStatus(), and GetDistance().
G4bool G4VTwistSurface::CurrentStatus::fDone private
Definition at line 280 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 280 of file G4VTwistSurface.hh
Referenced by CurrentStatus(), and IsDone().
G4bool G4VTwistSurface::CurrentStatus::fIsValid[G4VSURFACENXX] private
Definition at line 275 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 275 of file G4VTwistSurface.hh
Referenced by CurrentStatus(), and IsValid().
G4ThreeVector G4VTwistSurface::CurrentStatus::fLastp private
Definition at line 277 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 277 of file G4VTwistSurface.hh
Referenced by CurrentStatus().
G4ThreeVector G4VTwistSurface::CurrentStatus::fLastv private
Definition at line 278 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 278 of file G4VTwistSurface.hh
Referenced by CurrentStatus().
EValidate G4VTwistSurface::CurrentStatus::fLastValidate private
Definition at line 279 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 279 of file G4VTwistSurface.hh
Referenced by CurrentStatus().
G4int G4VTwistSurface::CurrentStatus::fNXX private
Definition at line 276 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 276 of file G4VTwistSurface.hh
Referenced by CurrentStatus(), and GetNXX().
G4ThreeVector G4VTwistSurface::CurrentStatus::fXX[G4VSURFACENXX] private
Definition at line 273 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 273 of file G4VTwistSurface.hh
Referenced by CurrentStatus(), and GetXX().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4VTwistSurface.cc