ECCE @ EIC Software: genericDetector Class Reference
genericDetector Class Reference abstract
#include <ecce-detectors/blob/master/FastPID/dRICH/genericDetector.h>
Public Types
enum EDetector_t { kBarrel, kForward }
Public Types inherited from PID
enum type { pi_k, k_p }
Public Member Functions
genericDetector ()=default
virtual ~genericDetector ()=default
void setType (EDetector_t val)
void setName (string val)
void setLength (double val)
void setRadius (double val)
void setPositionZ (double val)
void setRadiusIn (double val)
void setRadiusOut (double val)
void setMagneticField (double val)
virtual bool valid (double eta, double p) override
virtual double numSigma (double eta, double p, PID::type PID) override=0
virtual double maxP (double eta, double numSigma, PID::type PID) override=0
virtual double minP (double eta, double numSigma, PID::type PID) override=0
string name () override
void description () override
double maxPt (double eta, double numSigma, PID::type PID)
double minPt (double eta, double numSigma, PID::type PID)
Public Member Functions inherited from PID
PID ()
virtual ~PID ()
virtual double maxP (double eta, double p, double numSigma, PID::type PID)=0
Protected Member Functions
double etaMin ()
double etaMax ()
double ptMin ()
double pMin (double eta)
bool isHit (double eta, double p)
double trackLength (double eta)
Protected Attributes
string mName = "genericDetector"
string mDescription = "Detector description"
EDetector_t mType = kBarrel
double mLength = 200.
double mRadius = 200.
double mPositionZ = 200.
double mRadiusIn = 20.
double mRadiusOut = 200.
double mMagneticField = 2.
const double mLightSpeed = 29.9792458
const double mMassElectron = 0.00051099891
const double mMassPion = 0.13957018
const double mMassKaon = 0.493677
const double mMassProton = 0.93827208816
Detailed Description
Author
R+Preghenella pregh.nosp@m.enel.nosp@m.la@bo.nosp@m..inf.nosp@m.n.it
Date
March 2020
Definition at line 10 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 10 of file genericDetector.h
Member Enumeration Documentation
enum genericDetector::EDetector_t
Enumerator:
kBarrel
kForward
Definition at line 16 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 16 of file genericDetector.h
Constructor & Destructor Documentation
genericDetector::genericDetector () default
virtual genericDetector::~genericDetector () virtual default
Member Function Documentation
void genericDetector::description () inline override virtual
Implements PID.
Definition at line 34 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 34 of file genericDetector.h
References mDescription.
double genericDetector::etaMax () protected
Definition at line 79 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 79 of file genericDetector.h
References kBarrel, kForward, mLength, mPositionZ, mRadius, mRadiusIn, and mType.
double genericDetector::etaMin () protected
Definition at line 67 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 67 of file genericDetector.h
References kBarrel, kForward, mLength, mPositionZ, mRadius, mRadiusOut, and mType.
Referenced by isHit().
bool genericDetector::isHit (double eta, double p) inline protected
Definition at line 45 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 45 of file genericDetector.h
References etaMin(), and pMin().
Referenced by valid().
virtual double genericDetector::maxP (double eta, double numSigma, PID::type PID) override pure virtual
Implemented in genericRICH.
Referenced by maxPt().
double genericDetector::maxPt (double eta, double numSigma, PID::type PID) inline
Definition at line 36 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 36 of file genericDetector.h
References maxP().
virtual double genericDetector::minP (double eta, double numSigma, PID::type PID) override pure virtual
Implements PID.
Implemented in genericRICH.
double genericDetector::minPt (double eta, double numSigma, PID::type PID) inline
Definition at line 37 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 37 of file genericDetector.h
References ptMin().
string genericDetector::name () inline override virtual
Implements PID.
Definition at line 33 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 33 of file genericDetector.h
References mName.
virtual double genericDetector::numSigma (double eta, double p, PID::type PID) override pure virtual
Implemented in genericRICH.
double genericDetector::pMin (double eta) inline protected
Definition at line 44 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 44 of file genericDetector.h
References ptMin().
Referenced by isHit(), and genericRICH::minP().
double genericDetector::ptMin () protected
Definition at line 91 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 91 of file genericDetector.h
References kBarrel, kForward, mMagneticField, mRadius, mRadiusIn, and mType.
Referenced by minPt(), and pMin().
void genericDetector::setLength (double val) inline
Definition at line 21 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 21 of file genericDetector.h
References mLength.
Referenced by dualRICH_aerogel::dualRICH_aerogel(), and dualRICH_C2F6::dualRICH_C2F6().
void genericDetector::setMagneticField (double val) inline
Definition at line 26 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 26 of file genericDetector.h
References mMagneticField.
void genericDetector::setName (string val) inline
Definition at line 20 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 20 of file genericDetector.h
References mName.
Referenced by dualRICH_aerogel::dualRICH_aerogel(), and dualRICH_C2F6::dualRICH_C2F6().
void genericDetector::setPositionZ (double val) inline
Definition at line 23 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 23 of file genericDetector.h
References mPositionZ.
Referenced by dualRICH_aerogel::dualRICH_aerogel(), and dualRICH_C2F6::dualRICH_C2F6().
void genericDetector::setRadius (double val) inline
Definition at line 22 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 22 of file genericDetector.h
References mRadius.
void genericDetector::setRadiusIn (double val) inline
Definition at line 24 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 24 of file genericDetector.h
References mRadiusIn.
Referenced by dualRICH_aerogel::dualRICH_aerogel(), and dualRICH_C2F6::dualRICH_C2F6().
void genericDetector::setRadiusOut (double val) inline
Definition at line 25 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 25 of file genericDetector.h
References mRadiusOut.
Referenced by dualRICH_aerogel::dualRICH_aerogel(), and dualRICH_C2F6::dualRICH_C2F6().
void genericDetector::setType (EDetector_t val) inline
setters
Definition at line 19 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 19 of file genericDetector.h
References mType.
Referenced by dualRICH_aerogel::dualRICH_aerogel(), and dualRICH_C2F6::dualRICH_C2F6().
double genericDetector::trackLength (double eta) protected
Definition at line 103 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 103 of file genericDetector.h
References kBarrel, kForward, mPositionZ, mRadius, mType, and theta().
virtual bool genericDetector::valid (double eta, double p) inline override virtual
methods to override
Implements PID.
Definition at line 29 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 29 of file genericDetector.h
References isHit().
Member Data Documentation
string genericDetector::mDescription = "Detector description" protected
Definition at line 49 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 49 of file genericDetector.h
Referenced by description().
double genericDetector::mLength = 200. protected
Definition at line 51 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 51 of file genericDetector.h
Referenced by etaMax(), etaMin(), genericRICH::numberOfPhotons(), and setLength().
const double genericDetector::mLightSpeed = 29.9792458 protected
Definition at line 58 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 58 of file genericDetector.h
double genericDetector::mMagneticField = 2. protected
Definition at line 56 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 56 of file genericDetector.h
Referenced by ptMin(), and setMagneticField().
const double genericDetector::mMassElectron = 0.00051099891 protected
Definition at line 59 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 59 of file genericDetector.h
const double genericDetector::mMassKaon = 0.493677 protected
Definition at line 61 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 61 of file genericDetector.h
Referenced by genericRICH::maxP(), genericRICH::minP(), and genericRICH::numSigma().
const double genericDetector::mMassPion = 0.13957018 protected
Definition at line 60 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 60 of file genericDetector.h
Referenced by genericRICH::maxP(), genericRICH::minP(), and genericRICH::numSigma().
const double genericDetector::mMassProton = 0.93827208816 protected
Definition at line 62 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 62 of file genericDetector.h
Referenced by genericRICH::maxP(), genericRICH::minP(), and genericRICH::numSigma().
string genericDetector::mName = "genericDetector" protected
Definition at line 48 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 48 of file genericDetector.h
Referenced by name(), and setName().
double genericDetector::mPositionZ = 200. protected
Definition at line 53 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 53 of file genericDetector.h
Referenced by etaMax(), etaMin(), setPositionZ(), and trackLength().
double genericDetector::mRadius = 200. protected
Definition at line 52 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 52 of file genericDetector.h
Referenced by etaMax(), etaMin(), ptMin(), setRadius(), and trackLength().
double genericDetector::mRadiusIn = 20. protected
Definition at line 54 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 54 of file genericDetector.h
Referenced by etaMax(), ptMin(), and setRadiusIn().
double genericDetector::mRadiusOut = 200. protected
Definition at line 55 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 55 of file genericDetector.h
Referenced by etaMin(), and setRadiusOut().
EDetector_t genericDetector::mType = kBarrel protected
Definition at line 50 of file genericDetector.h.
View newest version in sPHENIX GitHub at line 50 of file genericDetector.h
Referenced by etaMax(), etaMin(), ptMin(), setType(), and trackLength().
The documentation for this class was generated from the following file:
ecce-detectors/blob/master/FastPID/dRICH/genericDetector.h