ECCE @ EIC Software: G4MoleculeIterator< MOLECULE > Class Template Reference
G4MoleculeIterator< MOLECULE > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MoleculeIterator.hh>
Public Member Functions
G4MoleculeIterator (MAP &_map)
virtual ~G4MoleculeIterator ()
G4MoleculeIterator (const G4MoleculeIterator &right)
G4MoleculeIterator & operator= (const G4MoleculeIterator &right)
G4bool operator++ (int)
G4bool operator++ ()
void reset ()
G4bool operator() ()
const G4String & Name ()
MOLECULE * value ()
Protected Types
typedef std::map< G4String,
MOLECULE * > MAP
Protected Attributes
MAP * fMap
G4bool fDefined
MAP::iterator fIt
Detailed Description
template<typename MOLECULE>
class G4MoleculeIterator< MOLECULE >
Definition at line 52 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 52 of file G4MoleculeIterator.hh
Member Typedef Documentation
template<typename MOLECULE > typedef std::map<G4String, MOLECULE*> G4MoleculeIterator< MOLECULE >::MAP protected
Definition at line 55 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 55 of file G4MoleculeIterator.hh
Constructor & Destructor Documentation
template<typename MOLECULE > G4MoleculeIterator< MOLECULE >::G4MoleculeIterator (MAP & _map) inline
Definition at line 61 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 61 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined.
template<typename MOLECULE > virtual G4MoleculeIterator< MOLECULE >::~G4MoleculeIterator () inline virtual
Definition at line 67 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 67 of file G4MoleculeIterator.hh
template<typename MOLECULE > G4MoleculeIterator< MOLECULE >::G4MoleculeIterator (const G4MoleculeIterator< MOLECULE > & right) inline
Definition at line 72 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 72 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined, G4MoleculeIterator< MOLECULE >::fIt, and G4MoleculeIterator< MOLECULE >::fMap.
Member Function Documentation
template<typename MOLECULE > const G4String& G4MoleculeIterator< MOLECULE >::Name () inline
Definition at line 123 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 123 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fIt.
template<typename MOLECULE > G4bool G4MoleculeIterator< MOLECULE >::operator() () inline
Definition at line 107 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 107 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined, G4MoleculeIterator< MOLECULE >::fIt, and G4MoleculeIterator< MOLECULE >::fMap.
template<typename MOLECULE > G4bool G4MoleculeIterator< MOLECULE >::operator++ (int) inline
Definition at line 88 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 88 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined, G4MoleculeIterator< MOLECULE >::fIt, and G4MoleculeIterator< MOLECULE >::fMap.
template<typename MOLECULE > G4bool G4MoleculeIterator< MOLECULE >::operator++ () inline
Definition at line 95 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 95 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined, G4MoleculeIterator< MOLECULE >::fIt, and G4MoleculeIterator< MOLECULE >::fMap.
template<typename MOLECULE > G4MoleculeIterator& G4MoleculeIterator< MOLECULE >::operator= (const G4MoleculeIterator< MOLECULE > & right) inline
Definition at line 79 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 79 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined, G4MoleculeIterator< MOLECULE >::fIt, and G4MoleculeIterator< MOLECULE >::fMap.
template<typename MOLECULE > void G4MoleculeIterator< MOLECULE >::reset () inline
Definition at line 102 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 102 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fDefined.
Referenced by G4VUserChemistryList::BuildPhysicsTable(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), and G4EmDNAChemistry_option2::ConstructProcess().
template<typename MOLECULE > MOLECULE* G4MoleculeIterator< MOLECULE >::value () inline
Definition at line 128 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 128 of file G4MoleculeIterator.hh
References G4MoleculeIterator< MOLECULE >::fIt.
Referenced by G4VUserChemistryList::BuildPhysicsTable(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), and G4MolecularConfiguration::ScaleAllDiffusionCoefficientsOnWater().
Member Data Documentation
template<typename MOLECULE > G4bool G4MoleculeIterator< MOLECULE >::fDefined protected
Definition at line 57 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MoleculeIterator.hh
Referenced by G4MoleculeIterator< MOLECULE >::G4MoleculeIterator(), G4MoleculeIterator< MOLECULE >::operator()(), G4MoleculeIterator< MOLECULE >::operator++(), G4MoleculeIterator< MOLECULE >::operator=(), and G4MoleculeIterator< MOLECULE >::reset().
template<typename MOLECULE > MAP::iterator G4MoleculeIterator< MOLECULE >::fIt protected
Definition at line 58 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 58 of file G4MoleculeIterator.hh
Referenced by G4MoleculeIterator< MOLECULE >::G4MoleculeIterator(), G4MoleculeIterator< MOLECULE >::Name(), G4MoleculeIterator< MOLECULE >::operator()(), G4MoleculeIterator< MOLECULE >::operator++(), G4MoleculeIterator< MOLECULE >::operator=(), and G4MoleculeIterator< MOLECULE >::value().
template<typename MOLECULE > MAP* G4MoleculeIterator< MOLECULE >::fMap protected
Definition at line 56 of file G4MoleculeIterator.hh.
View newest version in sPHENIX GitHub at line 56 of file G4MoleculeIterator.hh
Referenced by G4MoleculeIterator< MOLECULE >::G4MoleculeIterator(), G4MoleculeIterator< MOLECULE >::operator()(), G4MoleculeIterator< MOLECULE >::operator++(), and G4MoleculeIterator< MOLECULE >::operator=().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MoleculeIterator.hh