ECCE @ EIC Software: G4ChargeExchange Class Reference
G4ChargeExchange Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ChargeExchange.hh>
Public Member Functions
G4ChargeExchange ()
~G4ChargeExchange () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
void SetLowestEnergyLimit (G4double value)
G4double SampleT (G4double p, G4int A)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4ParticleDefinition * theAProton
G4ParticleDefinition * theANeutron
G4ParticleDefinition * thePiPlus
G4ParticleDefinition * thePiMinus
G4ParticleDefinition * thePiZero
G4ParticleDefinition * theKPlus
G4ParticleDefinition * theKMinus
G4ParticleDefinition * theK0S
G4ParticleDefinition * theK0L
G4ParticleDefinition * theL
G4ParticleDefinition * theAntiL
G4ParticleDefinition * theSPlus
G4ParticleDefinition * theASPlus
G4ParticleDefinition * theSMinus
G4ParticleDefinition * theASMinus
G4ParticleDefinition * theS0
G4ParticleDefinition * theAS0
G4ParticleDefinition * theXiMinus
G4ParticleDefinition * theXi0
G4ParticleDefinition * theAXiMinus
G4ParticleDefinition * theAXi0
G4ParticleDefinition * theOmega
G4ParticleDefinition * theAOmega
G4ParticleDefinition * theD
G4ParticleDefinition * theT
G4ParticleDefinition * theA
G4ParticleDefinition * theHe3
G4double lowestEnergyLimit
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 51 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ChargeExchange.hh
Constructor & Destructor Documentation
G4ChargeExchange::G4ChargeExchange () explicit
Definition at line 55 of file G4ChargeExchange.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ChargeExchange.cc
References G4Alpha::Alpha(), G4AntiLambda::AntiLambda(), G4AntiNeutron::AntiNeutron(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiSigmaZero::AntiSigmaZero(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), G4Deuteron::Deuteron(), G4HadronicInteraction::GetMaxEnergy(), GeV, G4He3::He3(), G4HadronicParameters::Instance(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), G4Lambda::Lambda(), lowestEnergyLimit, MeV, G4Neutron::Neutron(), G4OmegaMinus::OmegaMinus(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), theA, theANeutron, theAntiL, theAOmega, theAProton, theAS0, theASMinus, theASPlus, theAXi0, theAXiMinus, theD, theHe3, theK0L, theK0S, theKMinus, theKPlus, theL, theNeutron, theOmega, thePiMinus, thePiPlus, thePiZero, theProton, theS0, theSMinus, theSPlus, theT, theXi0, theXiMinus, G4Triton::Triton(), G4XiMinus::XiMinus(), and G4XiZero::XiZero().
G4ChargeExchange::~G4ChargeExchange () override
Definition at line 93 of file G4ChargeExchange.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ChargeExchange.cc
Member Function Documentation
G4HadFinalState * G4ChargeExchange::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) override virtual
Implements G4HadronicInteraction.
Definition at line 96 of file G4ChargeExchange.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ChargeExchange.cc
References A(), kdfinder::abs(), G4HadFinalState::AddSecondary(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4HadFinalState::Clear(), CLHEP::HepLorentzVector::e(), e1, G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4HadronicInteraction::GetRecoilEnergyThreshold(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, lowestEnergyLimit, max, MeV, N, phi, SampleT(), G4DynamicParticle::SetDefinition(), G4HadFinalState::SetEnergyChange(), G4DynamicParticle::SetKineticEnergy(), G4HadFinalState::SetLocalEnergyDeposit(), G4HadFinalState::SetMomentumChange(), G4HadFinalState::SetStatusChange(), stopAndKill, t, theA, theANeutron, theAProton, theD, theHe3, theK0L, theK0S, theKMinus, theKPlus, theL, theNeutron, G4HadronicInteraction::theParticleChange, thePiMinus, thePiPlus, thePiZero, theProton, theS0, theSMinus, theSPlus, theT, twopi, v1, G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
G4double G4ChargeExchange::SampleT (G4double p, G4int A)
Definition at line 308 of file G4ChargeExchange.cc.
View newest version in sPHENIX GitHub at line 308 of file G4ChargeExchange.cc
References bb, G4Exp(), G4Log(), G4UniformRand, G4Pow::GetInstance(), G4Pow::powZ(), t, x1, x2, and y.
Referenced by ApplyYourself().
void G4ChargeExchange::SetLowestEnergyLimit (G4double value) inline
Definition at line 101 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ChargeExchange.hh
References lowestEnergyLimit.
Member Data Documentation
G4double G4ChargeExchange::lowestEnergyLimit private
Definition at line 98 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), G4ChargeExchange(), and SetLowestEnergyLimit().
G4ParticleDefinition* G4ChargeExchange::theA private
Definition at line 95 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theANeutron private
Definition at line 71 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theAntiL private
Definition at line 80 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theAOmega private
Definition at line 92 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theAProton private
Definition at line 70 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theAS0 private
Definition at line 86 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theASMinus private
Definition at line 84 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theASPlus private
Definition at line 82 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theAXi0 private
Definition at line 90 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theAXiMinus private
Definition at line 89 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theD private
Definition at line 93 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theHe3 private
Definition at line 96 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theK0L private
Definition at line 78 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theK0S private
Definition at line 77 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theKMinus private
Definition at line 76 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theKPlus private
Definition at line 75 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theL private
Definition at line 79 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theNeutron private
Definition at line 69 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theOmega private
Definition at line 91 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::thePiMinus private
Definition at line 73 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::thePiPlus private
Definition at line 72 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::thePiZero private
Definition at line 74 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theProton private
Definition at line 68 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theS0 private
Definition at line 85 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theSMinus private
Definition at line 83 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theSPlus private
Definition at line 81 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theT private
Definition at line 94 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChargeExchange.hh
Referenced by ApplyYourself(), and G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theXi0 private
Definition at line 88 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
G4ParticleDefinition* G4ChargeExchange::theXiMinus private
Definition at line 87 of file G4ChargeExchange.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChargeExchange.hh
Referenced by G4ChargeExchange().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ChargeExchange.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4ChargeExchange.cc