ECCE @ EIC Software: G4VParticleHPEDis Class Reference
G4VParticleHPEDis Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4VParticleHPEDis.hh>
Public Member Functions
G4VParticleHPEDis ()
virtual ~G4VParticleHPEDis ()
virtual void Init (std::istream &theData)=0
virtual G4double GetFractionalProbability (G4double anEnergy)=0
virtual G4double Sample (G4double anEnergy)=0
Detailed Description
Definition at line 39 of file G4VParticleHPEDis.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VParticleHPEDis.hh
Constructor & Destructor Documentation
G4VParticleHPEDis::G4VParticleHPEDis () inline
Definition at line 42 of file G4VParticleHPEDis.hh.
View newest version in sPHENIX GitHub at line 42 of file G4VParticleHPEDis.hh
virtual G4VParticleHPEDis::~G4VParticleHPEDis () inline virtual
Definition at line 45 of file G4VParticleHPEDis.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VParticleHPEDis.hh
Member Function Documentation
virtual G4double G4VParticleHPEDis::GetFractionalProbability (G4double anEnergy) pure virtual
Implemented in G4ParticleHPArbitaryTab, G4ParticleHPMadlandNixSpectrum, G4ParticleHPSimpleEvapSpectrum, G4ParticleHPWattSpectrum, G4ParticleHPFissionSpectrum, and G4ParticleHPEvapSpectrum.
Referenced by G4ParticleHPEnergyDistribution::Sample().
virtual void G4VParticleHPEDis::Init (std::istream & theData) pure virtual
Implemented in G4ParticleHPMadlandNixSpectrum, G4ParticleHPArbitaryTab, G4ParticleHPSimpleEvapSpectrum, G4ParticleHPFissionSpectrum, G4ParticleHPWattSpectrum, and G4ParticleHPEvapSpectrum.
Referenced by G4ParticleHPEnergyDistribution::Init().
virtual G4double G4VParticleHPEDis::Sample (G4double anEnergy) pure virtual
Implemented in G4ParticleHPArbitaryTab, G4ParticleHPMadlandNixSpectrum, G4ParticleHPSimpleEvapSpectrum, G4ParticleHPFissionSpectrum, G4ParticleHPWattSpectrum, and G4ParticleHPEvapSpectrum.
Referenced by G4ParticleHPEnergyDistribution::Sample().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4VParticleHPEDis.hh