ECCE @ EIC Software: PHG4RICHSteppingAction Class Reference
PHG4RICHSteppingAction Class Reference
This class defines the user stepping action for the ePHENIX RICH volumes within Fun4All.
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4rich/PHG4RICHSteppingAction.h>
Public Member Functions
PHG4RICHSteppingAction (PHG4RICHDetector *)
virtual ~PHG4RICHSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
virtual void SetInterfacePointers (PHCompositeNode *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Member Functions
bool MakeHit (const G4Step *aStep)
Private Attributes
PHG4RICHDetector * detector_
PHG4HitContainer * hits_
PHG4Hit * hit
G4OpBoundaryProcessStatus fExpectedNextStatus
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
This class defines the user stepping action for the ePHENIX RICH volumes within Fun4All.
Optical photons can be absorbed/detected at the optical surface of the photocathode. The efficiency for detection is a parameter of this optical surface defined during detector construction (set in ePHENIXRICH::RICH_Geometry). The x,y,z positions of where the photons are detected are stored in a PHG4Hits collection.
See Also
ePHENIXRICH::RICH_Geometry
ePHENIXRICH::ePHENIXRICHConstruction
PHG4RICHDetector
PHG4RICHSteppingAction
PHG4RICHSubsystem
Definition at line 42 of file PHG4RICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4RICHSteppingAction.h
Constructor & Destructor Documentation
PHG4RICHSteppingAction::PHG4RICHSteppingAction (PHG4RICHDetector * detector)
Definition at line 47 of file PHG4RICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file PHG4RICHSteppingAction.cc
virtual PHG4RICHSteppingAction::~PHG4RICHSteppingAction () inline virtual
Definition at line 46 of file PHG4RICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4RICHSteppingAction.h
Member Function Documentation
bool PHG4RICHSteppingAction::MakeHit (const G4Step * aStep) private
Definition at line 149 of file PHG4RICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 149 of file PHG4RICHSteppingAction.cc
References PHG4HitContainer::AddHit(), cm, detector_, edep, PHG4Hit::get_hit_id(), G4VTouchable::GetCopyNumber(), G4StepPoint::GetGlobalTime(), PHG4HitContainer::GetID(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetTotalEnergyDeposit(), G4Track::GetTouchable(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetUserInformation(), G4VTouchable::GetVolume(), GeV, hit, hits_, nanosecond, G4InuclParticleNames::pp, PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by UserSteppingAction().
void PHG4RICHSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
Definition at line 233 of file PHG4RICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 233 of file PHG4RICHSteppingAction.cc
References hits_.
void PHG4RICHSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 55 of file PHG4RICHSteppingAction.cc.
View newest version in sPHENIX GitHub at line 55 of file PHG4RICHSteppingAction.cc
References Absorption, BackScattering, Detection, FatalException, fExpectedNextStatus, fGeomBoundary, FresnelReflection, G4Exception(), G4Track::GetDefinition(), G4VPhysicalVolume::GetName(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4ProcessManager::GetProcessList(), G4ProcessManager::GetProcessListLength(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4OpBoundaryProcess::GetStatus(), G4StepPoint::GetStepStatus(), G4Step::GetTrack(), LambertianReflection, LobeReflection, MakeHit(), G4OpticalPhoton::OpticalPhotonDefinition(), Acts::UnitConstants::pm, SpikeReflection, StepTooSmall, TotalInternalReflection, and Acts::Undefined.
Member Data Documentation
PHG4RICHDetector* PHG4RICHSteppingAction::detector_ private
Definition at line 55 of file PHG4RICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4RICHSteppingAction.h
Referenced by MakeHit().
G4OpBoundaryProcessStatus PHG4RICHSteppingAction::fExpectedNextStatus private
Definition at line 59 of file PHG4RICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4RICHSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* PHG4RICHSteppingAction::hit private
Definition at line 57 of file PHG4RICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4RICHSteppingAction.h
Referenced by MakeHit().
PHG4HitContainer* PHG4RICHSteppingAction::hits_ private
Definition at line 56 of file PHG4RICHSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4RICHSteppingAction.h
Referenced by MakeHit(), and SetInterfacePointers().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4rich/PHG4RICHSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4rich/PHG4RICHSteppingAction.cc