ECCE @ EIC Software: CML2Ph_BoxInBox Class Reference
CML2Ph_BoxInBox Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Ph_BoxInBox.hh>
Public Member Functions
CML2Ph_BoxInBox ()
~CML2Ph_BoxInBox (void)
bool Construct (G4VPhysicalVolume *PVWorld)
G4VPhysicalVolume * getPhysicalVolume ()
G4ThreeVector getHalfContainerSize ()
void writeInfo ()
Private Attributes
G4VPhysicalVolume * PVWorld
G4VPhysicalVolume * boxInSidePV
G4VPhysicalVolume * layerPV
G4VPhysicalVolume * OutMinusInBoxPV
G4ThreeVector centreBoxInside
G4double halfBoxInside_Thickness
G4ThreeVector halfSize
G4ThreeVector centre
Detailed Description
Definition at line 60 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 60 of file ML2Ph_BoxInBox.hh
Constructor & Destructor Documentation
CML2Ph_BoxInBox::CML2Ph_BoxInBox ()
Definition at line 46 of file ML2Ph_BoxInBox.cc.
View newest version in sPHENIX GitHub at line 46 of file ML2Ph_BoxInBox.cc
References centre, halfSize, mm, and CLHEP::Hep3Vector::set().
CML2Ph_BoxInBox::~CML2Ph_BoxInBox (void)
Definition at line 53 of file ML2Ph_BoxInBox.cc.
View newest version in sPHENIX GitHub at line 53 of file ML2Ph_BoxInBox.cc
Member Function Documentation
bool CML2Ph_BoxInBox::Construct (G4VPhysicalVolume * PVWorld)
Definition at line 61 of file ML2Ph_BoxInBox.cc.
View newest version in sPHENIX GitHub at line 61 of file ML2Ph_BoxInBox.cc
References A(), G4Material::AddElement(), G4Region::AddRootLogicalVolume(), G4Colour::Blue(), boxInSidePV, centre, centreBoxInside, cm, cm3, d, G4NistManager::FindOrBuildMaterial(), Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetName(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4Colour::Gray(), halfBoxInside_Thickness, halfSize, G4NistManager::Instance(), G4TTL::layer, layerMaterial(), layerPV, mm, mole, OutMinusInBoxPV, G4DRCALO::SETTING::PMMA, PVWorld, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4VisAttributes::SetLineWidth(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and Z.
Referenced by CML2PhantomConstruction::Construct().
G4ThreeVector CML2Ph_BoxInBox::getHalfContainerSize () inline
Definition at line 67 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 67 of file ML2Ph_BoxInBox.hh
References halfSize.
Referenced by CML2PhantomConstruction::design().
G4VPhysicalVolume* CML2Ph_BoxInBox::getPhysicalVolume () inline
Definition at line 66 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Ph_BoxInBox.hh
References PVWorld.
Referenced by CML2PhantomConstruction::Construct().
void CML2Ph_BoxInBox::writeInfo ()
Definition at line 56 of file ML2Ph_BoxInBox.cc.
View newest version in sPHENIX GitHub at line 56 of file ML2Ph_BoxInBox.cc
References centreBoxInside, G4cout, G4endl, halfBoxInside_Thickness, and mm.
Referenced by CML2PhantomConstruction::Construct().
Member Data Documentation
G4VPhysicalVolume* CML2Ph_BoxInBox::boxInSidePV private
Definition at line 71 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 71 of file ML2Ph_BoxInBox.hh
Referenced by Construct().
G4ThreeVector CML2Ph_BoxInBox::centre private
Definition at line 77 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2Ph_BoxInBox.hh
Referenced by CML2Ph_BoxInBox(), and Construct().
G4ThreeVector CML2Ph_BoxInBox::centreBoxInside private
Definition at line 75 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2Ph_BoxInBox.hh
Referenced by Construct(), and writeInfo().
G4double CML2Ph_BoxInBox::halfBoxInside_Thickness private
Definition at line 76 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 76 of file ML2Ph_BoxInBox.hh
Referenced by Construct(), and writeInfo().
G4ThreeVector CML2Ph_BoxInBox::halfSize private
Definition at line 77 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2Ph_BoxInBox.hh
Referenced by CML2Ph_BoxInBox(), Construct(), and getHalfContainerSize().
G4VPhysicalVolume* CML2Ph_BoxInBox::layerPV private
Definition at line 72 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 72 of file ML2Ph_BoxInBox.hh
Referenced by Construct().
G4VPhysicalVolume* CML2Ph_BoxInBox::OutMinusInBoxPV private
Definition at line 73 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2Ph_BoxInBox.hh
Referenced by Construct().
G4VPhysicalVolume* CML2Ph_BoxInBox::PVWorld private
Definition at line 70 of file ML2Ph_BoxInBox.hh.
View newest version in sPHENIX GitHub at line 70 of file ML2Ph_BoxInBox.hh
Referenced by Construct(), and getPhysicalVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Ph_BoxInBox.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Ph_BoxInBox.cc