ECCE @ EIC Software: G4MuPairProductionModel Class Reference
G4MuPairProductionModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4MuPairProductionModel.hh>
Public Member Functions
G4MuPairProductionModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="muPairProd")
virtual ~G4MuPairProductionModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double) override
void SetLowestKineticEnergy (G4double e)
void SetParticle (const G4ParticleDefinition *)
G4MuPairProductionModel & operator= (const G4MuPairProductionModel &right)=delete
G4MuPairProductionModel (const G4MuPairProductionModel &)=delete
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
G4double ComputMuPairLoss (G4double Z, G4double tkin, G4double cut, G4double tmax)
G4double ComputeMicroscopicCrossSection (G4double tkin, G4double Z, G4double cut)
virtual G4double ComputeDMicroscopicCrossSection (G4double tkin, G4double Z, G4double pairEnergy)
G4double MaxSecondaryEnergyForElement (G4double kineticEnergy, G4double Z)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
const G4ParticleDefinition * particle
G4NistManager * nist
G4double factorForCross
G4double sqrte
G4double particleMass
G4double z13
G4double z23
G4double lnZ
G4int currentZ
G4ParticleDefinition * theElectron
G4ParticleDefinition * thePositron
G4ParticleChangeForLoss * fParticleChange
G4double minPairEnergy
G4double lowestKinEnergy
G4int nzdat
G4int nYBinPerDecade
size_t nbiny
size_t nbine
G4double ymin
G4double dy
G4double emin
G4double emax
G4bool fTableToFile
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Static Protected Attributes
static const G4double xgi [8]
static const G4double wgi [8]
Private Member Functions
void MakeSamplingTables ()
void StoreTables () const
G4bool RetrieveTables ()
void DataCorrupted (G4int Z, G4double logTkin) const
G4double FindScaledEnergy (G4int Z, G4double rand, G4double logTkin, G4double yymin, G4double yymax)
Detailed Description
Definition at line 72 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 72 of file G4MuPairProductionModel.hh
Constructor & Destructor Documentation
G4MuPairProductionModel::G4MuPairProductionModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "muPairProd") explicit
Definition at line 108 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 108 of file G4MuPairProductionModel.cc
References G4Electron::Electron(), emax, emin, G4ParticleDefinition::GetPDGMass(), G4NistManager::Instance(), lnZ, lowestKinEnergy, max, nist, particleMass, G4Positron::Positron(), SetParticle(), TeV, theElectron, thePositron, z13, and z23.
G4MuPairProductionModel::~G4MuPairProductionModel () virtual
Definition at line 145 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 145 of file G4MuPairProductionModel.cc
G4MuPairProductionModel::G4MuPairProductionModel (const G4MuPairProductionModel &) delete
Member Function Documentation
G4double G4MuPairProductionModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 419 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 419 of file G4MuPairProductionModel.cc
References ComputeMicroscopicCrossSection(), Acts::VectorHelpers::cross(), lowestKinEnergy, max, MaxSecondaryEnergyForElement(), min, and minPairEnergy.
G4double G4MuPairProductionModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 204 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 204 of file G4MuPairProductionModel.cc
References ComputMuPairLoss(), G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), lowestKinEnergy, max, MaxSecondaryEnergyForElement(), minPairEnergy, and Z.
G4double G4MuPairProductionModel::ComputeDMicroscopicCrossSection (G4double tkin, G4double Z, G4double pairEnergy) protected virtual
Reimplemented in G4hPairProductionModel.
Definition at line 306 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 306 of file G4MuPairProductionModel.cc
References a0, Acts::VectorHelpers::cross(), e, e3, CLHEP::electron_mass_c2, source.hepunit::electron_mass_c2, factorForCross, fe, Acts::UnitConstants::fm, G4Exp(), G4Log(), max, particleMass, sqrte, sum, wgi, xgi, G4InuclParticleNames::xi0, z13, z2, and z23.
Referenced by ComputeMicroscopicCrossSection(), ComputMuPairLoss(), and MakeSamplingTables().
G4double G4MuPairProductionModel::ComputeMicroscopicCrossSection (G4double tkin, G4double Z, G4double cut) protected
Definition at line 268 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 268 of file G4MuPairProductionModel.cc
References ak1, ak2, ComputeDMicroscopicCrossSection(), Acts::VectorHelpers::cross(), G4Exp(), G4Log(), hhh, max, MaxSecondaryEnergyForElement(), minPairEnergy, wgi, x, and xgi.
Referenced by ComputeCrossSectionPerAtom().
G4double G4MuPairProductionModel::ComputMuPairLoss (G4double Z, G4double tkin, G4double cut, G4double tmax) protected
Definition at line 231 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 231 of file G4MuPairProductionModel.cc
References ak1, ak2, ComputeDMicroscopicCrossSection(), G4Exp(), G4Log(), hhh, max, min, minPairEnergy, wgi, x, and xgi.
Referenced by ComputeDEDXPerVolume().
void G4MuPairProductionModel::DataCorrupted (G4int Z, G4double logTkin) const private
Definition at line 652 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 652 of file G4MuPairProductionModel.cc
References FatalException, G4Exception(), G4Exp(), G4VEmModel::GetName(), and G4VEmModel::IsMaster().
Referenced by FindScaledEnergy(), RetrieveTables(), and StoreTables().
G4double G4MuPairProductionModel::FindScaledEnergy (G4int Z, G4double rand, G4double logTkin, G4double yymin, G4double yymax) inline private
Definition at line 220 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 220 of file G4MuPairProductionModel.hh
References DataCorrupted(), G4VEmModel::fElementData, G4Physics2DVector::FindLinearX(), G4ElementData::GetElement2DData(), and G4Physics2DVector::Value().
Referenced by SampleSecondaries().
void G4MuPairProductionModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) override virtual
Implements G4VEmModel.
Definition at line 159 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 159 of file G4MuPairProductionModel.cc
References dy, emax, emin, G4VEmModel::fElementData, fParticleChange, fTableToFile, G4Log(), G4VEmModel::GetParticleChangeForLoss(), G4VEmModel::HighEnergyLimit(), G4VEmModel::InitialiseElementSelectors(), G4EmParameters::Instance(), G4VEmModel::IsMaster(), G4VEmModel::LowEnergyLimit(), lowestKinEnergy, MakeSamplingTables(), max, minPairEnergy, nbine, nbiny, nYBinPerDecade, particle, G4EmParameters::RetrieveMuDataFromFile(), RetrieveTables(), SetParticle(), StoreTables(), and ymin.
Referenced by G4TablesForExtrapolator::ComputeMuonDEDX().
void G4MuPairProductionModel::InitialiseLocal (const G4ParticleDefinition * p, G4VEmModel * masterModel) override virtual
Reimplemented from G4VEmModel.
Definition at line 193 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 193 of file G4MuPairProductionModel.cc
References G4VEmModel::fElementData, G4VEmModel::GetElementData(), G4VEmModel::GetElementSelectors(), G4VEmModel::HighEnergyLimit(), lowestKinEnergy, particle, and G4VEmModel::SetElementSelectors().
void G4MuPairProductionModel::MakeSamplingTables () private
Definition at line 443 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 443 of file G4MuPairProductionModel.cc
References ComputeDMicroscopicCrossSection(), dy, emax, emin, fac, G4VEmModel::fElementData, G4Exp(), G4Log(), imax, G4ElementData::InitialiseForElement(), it, MaxSecondaryEnergyForElement(), MeV, minPairEnergy, nbine, nbiny, nzdat, G4Physics2DVector::PutValue(), G4Physics2DVector::PutX(), G4Physics2DVector::PutY(), x, ymax, ymin, Z, and zdat.
Referenced by Initialise().
G4double G4MuPairProductionModel::MaxSecondaryEnergyForElement (G4double kineticEnergy, G4double Z) inline protected
Definition at line 204 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 204 of file G4MuPairProductionModel.hh
References currentZ, G4lrint(), G4NistManager::GetLOGZ(), G4NistManager::GetZ13(), lnZ, nist, particleMass, sqrte, Z, z13, and z23.
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), ComputeMicroscopicCrossSection(), MakeSamplingTables(), and SampleSecondaries().
G4double G4MuPairProductionModel::MinPrimaryEnergy (const G4Material * , const G4ParticleDefinition * , G4double cut) override virtual
Reimplemented from G4VEmModel.
Definition at line 150 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 150 of file G4MuPairProductionModel.cc
References lowestKinEnergy, and max.
G4MuPairProductionModel& G4MuPairProductionModel::operator= (const G4MuPairProductionModel & right) delete
G4bool G4MuPairProductionModel::RetrieveTables () private
Definition at line 680 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 680 of file G4MuPairProductionModel.cc
References DataCorrupted(), dir, G4VEmModel::fElementData, G4ParticleDefinition::GetParticleName(), in, G4ElementData::InitialiseForElement(), nbine, nbiny, nzdat, particle, G4Physics2DVector::Retrieve(), Z, and zdat.
Referenced by Initialise().
void G4MuPairProductionModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicParticle, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 512 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 512 of file G4MuPairProductionModel.cc
References currentZ, source.hepunit::electron_mass_c2, FindScaledEnergy(), fParticleChange, G4Exp(), G4Log(), G4UniformRand, G4InuclParticleNames::gam, G4DynamicParticle::GetKineticEnergy(), G4NistManager::GetLOGZ(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4Element::GetZ(), lnZ, max, MaxSecondaryEnergyForElement(), MeV, min, minPairEnergy, nist, nzdat, particle, particleMass, phi, r, rmax(), CLHEP::Hep3Vector::rotateUz(), G4VEmModel::SelectRandomAtom(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), theElectron, thePositron, theta(), twopi, CLHEP::Hep3Vector::unit(), x, x2, ymin, and zdat.
void G4MuPairProductionModel::SetLowestKineticEnergy (G4double e) inline
Definition at line 185 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4MuPairProductionModel.hh
References e, and lowestKinEnergy.
Referenced by G4ePairProduction::InitialiseEnergyLossProcess(), and G4MuPairProduction::InitialiseEnergyLossProcess().
void G4MuPairProductionModel::SetParticle (const G4ParticleDefinition * p) inline
Definition at line 193 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 193 of file G4MuPairProductionModel.hh
References G4ParticleDefinition::GetPDGMass(), particle, and particleMass.
Referenced by G4MuPairProductionModel(), and Initialise().
void G4MuPairProductionModel::StoreTables () const private
Definition at line 665 of file G4MuPairProductionModel.cc.
View newest version in sPHENIX GitHub at line 665 of file G4MuPairProductionModel.cc
References DataCorrupted(), G4VEmModel::fElementData, G4ElementData::GetElement2DData(), G4ParticleDefinition::GetParticleName(), nzdat, particle, G4Physics2DVector::Store(), Z, and zdat.
Referenced by Initialise().
Member Data Documentation
G4int G4MuPairProductionModel::currentZ protected
Definition at line 158 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4MuPairProductionModel.hh
Referenced by MaxSecondaryEnergyForElement(), and SampleSecondaries().
G4double G4MuPairProductionModel::dy protected
Definition at line 176 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4MuPairProductionModel.hh
Referenced by Initialise(), and MakeSamplingTables().
G4double G4MuPairProductionModel::emax protected
Definition at line 178 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 178 of file G4MuPairProductionModel.hh
Referenced by G4MuPairProductionModel(), Initialise(), and MakeSamplingTables().
G4double G4MuPairProductionModel::emin protected
Definition at line 177 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4MuPairProductionModel.hh
Referenced by G4MuPairProductionModel(), Initialise(), and MakeSamplingTables().
G4double G4MuPairProductionModel::factorForCross protected
Definition at line 152 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), and ComputeDMicroscopicCrossSection().
G4ParticleChangeForLoss* G4MuPairProductionModel::fParticleChange protected
Definition at line 164 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4MuPairProductionModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4bool G4MuPairProductionModel::fTableToFile protected
Definition at line 180 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4MuPairProductionModel.hh
Referenced by Initialise().
G4double G4MuPairProductionModel::lnZ protected
Definition at line 157 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4MuPairProductionModel.hh
Referenced by G4MuPairProductionModel(), MaxSecondaryEnergyForElement(), and SampleSecondaries().
G4double G4MuPairProductionModel::lowestKinEnergy protected
Definition at line 167 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4MuPairProductionModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), G4MuPairProductionModel(), Initialise(), InitialiseLocal(), MinPrimaryEnergy(), and SetLowestKineticEnergy().
G4double G4MuPairProductionModel::minPairEnergy protected
Definition at line 166 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4MuPairProductionModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), ComputeMicroscopicCrossSection(), ComputMuPairLoss(), Initialise(), MakeSamplingTables(), and SampleSecondaries().
size_t G4MuPairProductionModel::nbine protected
Definition at line 174 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4MuPairProductionModel.hh
Referenced by Initialise(), MakeSamplingTables(), and RetrieveTables().
size_t G4MuPairProductionModel::nbiny protected
Definition at line 173 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4MuPairProductionModel.hh
Referenced by Initialise(), MakeSamplingTables(), and RetrieveTables().
G4NistManager* G4MuPairProductionModel::nist protected
Definition at line 150 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4MuPairProductionModel.hh
Referenced by G4MuPairProductionModel(), MaxSecondaryEnergyForElement(), and SampleSecondaries().
G4int G4MuPairProductionModel::nYBinPerDecade protected
Definition at line 172 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4MuPairProductionModel.hh
Referenced by Initialise().
G4int G4MuPairProductionModel::nzdat protected
Definition at line 169 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4MuPairProductionModel.hh
Referenced by MakeSamplingTables(), RetrieveTables(), SampleSecondaries(), and StoreTables().
const G4ParticleDefinition* G4MuPairProductionModel::particle protected
Definition at line 149 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 149 of file G4MuPairProductionModel.hh
Referenced by Initialise(), InitialiseLocal(), RetrieveTables(), SampleSecondaries(), SetParticle(), and StoreTables().
G4double G4MuPairProductionModel::particleMass protected
Definition at line 154 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), ComputeDMicroscopicCrossSection(), G4MuPairProductionModel(), MaxSecondaryEnergyForElement(), SampleSecondaries(), and SetParticle().
G4double G4MuPairProductionModel::sqrte protected
Definition at line 153 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), ComputeDMicroscopicCrossSection(), and MaxSecondaryEnergyForElement().
G4ParticleDefinition* G4MuPairProductionModel::theElectron protected
Definition at line 162 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4MuPairProductionModel.hh
Referenced by G4MuPairProductionModel(), and SampleSecondaries().
G4ParticleDefinition* G4MuPairProductionModel::thePositron protected
Definition at line 163 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4MuPairProductionModel.hh
Referenced by G4MuPairProductionModel(), and SampleSecondaries().
const G4double G4MuPairProductionModel::wgi static protected
Initial value:
=
  { 0.0506, 0.1112, 0.1569, 0.1813, 0.1813, 0.1569, 0.1112, 0.0506 }
Definition at line 160 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), ComputeDMicroscopicCrossSection(), ComputeMicroscopicCrossSection(), and ComputMuPairLoss().
const G4double G4MuPairProductionModel::xgi static protected
Initial value:
=
  { 0.0199, 0.1017, 0.2372, 0.4083, 0.5917, 0.7628, 0.8983, 0.9801 }
Definition at line 160 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), ComputeDMicroscopicCrossSection(), ComputeMicroscopicCrossSection(), and ComputMuPairLoss().
G4double G4MuPairProductionModel::ymin protected
Definition at line 175 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 175 of file G4MuPairProductionModel.hh
Referenced by Initialise(), MakeSamplingTables(), and SampleSecondaries().
G4double G4MuPairProductionModel::z13 protected
Definition at line 155 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), ComputeDMicroscopicCrossSection(), G4MuPairProductionModel(), and MaxSecondaryEnergyForElement().
G4double G4MuPairProductionModel::z23 protected
Definition at line 156 of file G4MuPairProductionModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4MuPairProductionModel.hh
Referenced by G4hPairProductionModel::ComputeDMicroscopicCrossSection(), ComputeDMicroscopicCrossSection(), G4MuPairProductionModel(), and MaxSecondaryEnergyForElement().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4MuPairProductionModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/src/G4MuPairProductionModel.cc