ECCE @ EIC Software: G4MTRunManager Class Reference
G4MTRunManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4MTRunManager.hh>
Public Types
enum WorkerActionRequest
typedef std::map< G4int,
G4VPhysicalVolume * > masterWorlds_t
Public Types inherited from G4RunManager
enum RMType { sequentialRM, masterRM, workerRM }
Public Member Functions
G4MTRunManager ()
virtual ~G4MTRunManager ()
void SetNumberOfThreads (G4int n)
G4int GetNumberOfThreads () const
void SetPinAffinity (G4int n=1)
G4int GetPinAffinity () const
virtual void Initialize ()
virtual void InitializeEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void TerminateOneEvent ()
virtual void ProcessOneEvent (G4int i_event)
virtual void ConstructScoringWorlds ()
virtual void RunTermination ()
virtual G4bool SetUpAnEvent (G4Event *, long &s1, long &s2, long &s3, G4bool reseedRequired=true)
virtual G4int SetUpNEvents (G4Event *, G4SeedsQueue *seedsQueue, G4bool reseedRequired=true)
std::vector< G4String > GetCommandStack ()
size_t GetNumberActiveThreads () const
virtual void ThisWorkerReady ()
virtual void ThisWorkerEndEventLoop ()
const CLHEP::HepRandomEngine * getMasterRandomEngine () const
virtual void SetUserInitialization (G4VUserPhysicsList *userPL)
virtual void SetUserInitialization (G4VUserDetectorConstruction *userDC)
virtual void SetUserInitialization (G4UserWorkerInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerThreadInitialization *userInit)
virtual void SetUserInitialization (G4VUserActionInitialization *userInit)
virtual void SetUserAction (G4UserRunAction *userAction)
virtual void SetUserAction (G4VUserPrimaryGeneratorAction *userAction)
virtual void SetUserAction (G4UserEventAction *userAction)
virtual void SetUserAction (G4UserStackingAction *userAction)
virtual void SetUserAction (G4UserTrackingAction *userAction)
virtual void SetUserAction (G4UserSteppingAction *userAction)
void MergeScores (const G4ScoringManager *localScoringManager)
void MergeRun (const G4Run *localRun)
virtual void RequestWorkersProcessCommandsStack ()
virtual void ThisWorkerProcessCommandsStackDone ()
virtual WorkerActionRequest ThisWorkerWaitForNextAction ()
void SetEventModulo (G4int i=1)
G4int GetEventModulo () const
virtual void AbortRun (G4bool softAbort=false)
virtual void AbortEvent ()
Public Member Functions inherited from G4RunManager
G4RunManager ()
virtual ~G4RunManager ()
virtual void BeamOn (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
virtual void InitializeGeometry ()
virtual void InitializePhysics ()
virtual G4bool ConfirmBeamOnCondition ()
virtual void RunInitialization ()
virtual void DoEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void TerminateEventLoop ()
virtual G4Event * GenerateEvent (G4int i_event)
virtual void AnalyzeEvent (G4Event *anEvent)
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
virtual void RestoreRandomNumberStatus (const G4String &fileN)
const G4VUserDetectorConstruction * GetUserDetectorConstruction () const
const G4VUserPhysicsList * GetUserPhysicsList () const
const G4VUserActionInitialization * GetUserActionInitialization () const
G4VUserActionInitialization * GetNonConstUserActionInitialization () const
const G4UserWorkerInitialization * GetUserWorkerInitialization () const
const
G4UserWorkerThreadInitialization * GetUserWorkerThreadInitialization () const
const G4UserRunAction * GetUserRunAction () const
const
G4VUserPrimaryGeneratorAction * GetUserPrimaryGeneratorAction () const
const G4UserEventAction * GetUserEventAction () const
const G4UserStackingAction * GetUserStackingAction () const
const G4UserTrackingAction * GetUserTrackingAction () const
const G4UserSteppingAction * GetUserSteppingAction () const
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
const G4String & GetVersionString () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
void StoreRandomNumberStatusToG4Event (G4int vl)
G4int GetFlagRandomNumberStatusToG4Event () const
void SetRandomNumberStore (G4bool flag)
G4bool GetRandomNumberStore () const
void SetRandomNumberStoreDir (const G4String &dir)
const G4String & GetRandomNumberStoreDir () const
const G4String & GetRandomNumberStatusForThisRun () const
const G4String & GetRandomNumberStatusForThisEvent () const
void SetRandomNumberStorePerEvent (G4bool flag)
G4bool GetRandomNumberStorePerEvent () const
void GeometryHasBeenModified (G4bool prop=true)
void ReinitializeGeometry (G4bool destroyFirst=false, G4bool prop=true)
void PhysicsHasBeenModified ()
void CutOffHasBeenModified ()
void ReOptimizeMotherOf (G4VPhysicalVolume *)
void ReOptimize (G4LogicalVolume *)
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
G4int GetPrintProgress ()
void SetPrintProgress (G4int i)
void SetGeometryToBeOptimized (G4bool vl)
G4bool GetGeometryToBeOptimized ()
void SetNumberOfEventsToBeStored (G4int val)
const G4Run * GetCurrentRun () const
G4Run * GetNonConstCurrentRun () const
const G4Event * GetCurrentEvent () const
const G4Event * GetPreviousEvent (G4int i) const
void SetRunIDCounter (G4int i)
G4int GetNumberOfParallelWorld () const
void SetNumberOfEventsToBeProcessed (G4int val)
G4int GetNumberOfEventsToBeProcessed () const
G4int GetNumberOfSelectEvents () const
G4String GetSelectMacro () const
void SetDCtable (G4DCtable *DCtbl)
RMType GetRunManagerType () const
virtual void RestoreRndmEachEvent (G4bool)
void GeometryDirectlyUpdated (G4bool val=true)
Static Public Member Functions
static G4ScoringManager * GetMasterScoringManager ()
static masterWorlds_t & GetMasterWorlds ()
static void addWorld (G4int counter, G4VPhysicalVolume *w)
static G4MTRunManager * GetMasterRunManager ()
static G4RunManagerKernel * GetMasterRunManagerKernel ()
static G4MTRunManagerKernel * GetMTMasterRunManagerKernel ()
static G4int SeedOncePerCommunication ()
static void SetSeedOncePerCommunication (G4int val)
Static Public Member Functions inherited from G4RunManager
static G4RunManager * GetRunManager ()
static G4bool IfGeometryHasBeenDestroyed ()
Protected Member Functions
virtual G4bool InitializeSeeds (G4int)
virtual void PrepareCommandsStack ()
virtual void StoreRNGStatus (const G4String &filenamePrefix)
virtual void rndmSaveThisRun ()
virtual void rndmSaveThisEvent ()
virtual void CreateAndStartWorkers ()
virtual void WaitForReadyWorkers ()
virtual void WaitForEndEventLoopWorkers ()
virtual void TerminateWorkers ()
virtual void NewActionRequest (WorkerActionRequest newRequest)
void RefillSeeds ()
Protected Member Functions inherited from G4RunManager
void CleanUpPreviousEvents ()
void CleanUpUnnecessaryEvents (G4int keepNEvents)
void StackPreviousEvent (G4Event *anEvent)
G4RunManager (RMType rmType)
void UpdateScoring ()
virtual void DeleteUserInitializations ()
Protected Attributes
G4int numberOfEventToBeProcessed
WorkerActionRequest nextActionRequest
G4int eventModuloDef
G4int eventModulo
G4int nSeedsUsed
G4int nSeedsFilled
G4int nSeedsMax
G4int nSeedsPerEvent
double * randDbl
G4MTBarrier beginOfEventLoopBarrier
G4MTBarrier endOfEventLoopBarrier
G4MTBarrier nextActionRequestBarrier
G4MTBarrier processUIBarrier
Protected Attributes inherited from G4RunManager
G4RunManagerKernel * kernel
G4EventManager * eventManager
G4VUserDetectorConstruction * userDetector
G4VUserPhysicsList * physicsList
G4VUserActionInitialization * userActionInitialization
G4UserWorkerInitialization * userWorkerInitialization
G4UserWorkerThreadInitialization * userWorkerThreadInitialization
G4UserRunAction * userRunAction
G4VUserPrimaryGeneratorAction * userPrimaryGeneratorAction
G4UserEventAction * userEventAction
G4UserStackingAction * userStackingAction
G4UserTrackingAction * userTrackingAction
G4UserSteppingAction * userSteppingAction
G4bool geometryInitialized
G4bool physicsInitialized
G4bool runAborted
G4bool initializedAtLeastOnce
G4bool geometryToBeOptimized
G4int runIDCounter
G4int verboseLevel
G4int printModulo
G4Timer * timer
G4DCtable * DCtable
G4Run * currentRun
G4Event * currentEvent
std::list< G4Event * > * previousEvents
G4int n_perviousEventsToBeStored
G4int numberOfEventToBeProcessed
G4bool storeRandomNumberStatus
G4int storeRandomNumberStatusToG4Event
G4String randomNumberStatusDir
G4String randomNumberStatusForThisRun
G4String randomNumberStatusForThisEvent
G4bool rngStatusEventsFlag
G4VPhysicalVolume * currentWorld
G4int nParallelWorlds
G4String msgText
G4int n_select_msg
G4int numberOfEventProcessed
G4String selectMacro
G4bool fakeRun
G4bool isScoreNtupleWriter
RMType runManagerType
G4bool geometryDirectlyUpdated
Static Protected Attributes
static G4int seedOncePerCommunication = 0
Static Protected Attributes inherited from G4RunManager
static G4bool fGeometryHasBeenDestroyed = false
Private Types
typedef std::list< G4Thread * > G4ThreadsList
Private Attributes
G4int nworkers
G4int forcedNwokers
G4int pinAffinity
G4ThreadsList threads
std::vector< G4String > uiCmdsForWorkers
CLHEP::HepRandomEngine * masterRNGEngine
G4MTRunManagerKernel * MTkernel
Static Private Attributes
static G4ScoringManager * masterScM = 0
static masterWorlds_t masterWorlds = G4MTRunManager::masterWorlds_t()
static G4MTRunManager * fMasterRM = 0
Detailed Description
Definition at line 51 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4MTRunManager.hh
Member Typedef Documentation
typedef std::list<G4Thread*> G4MTRunManager::G4ThreadsList private
Definition at line 120 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4MTRunManager.hh
typedef std::map<G4int,G4VPhysicalVolume*> G4MTRunManager::masterWorlds_t
Definition at line 161 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 161 of file G4MTRunManager.hh
Member Enumeration Documentation
enum G4MTRunManager::WorkerActionRequest
Definition at line 200 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 200 of file G4MTRunManager.hh
Constructor & Destructor Documentation
G4MTRunManager::G4MTRunManager ()
Definition at line 78 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 78 of file G4MTRunManager.cc
References FatalException, fMasterRM, forcedNwokers, G4cout, G4endl, G4Exception(), G4Threading::G4GetNumberOfCores(), G4RunManagerKernel::GetNumberOfStaticAllocators(), G4ScoringManager::GetScoringManagerIfExist(), G4UImanager::GetUIpointer(), JustWarning, G4RunManager::kernel, masterRNGEngine, masterScM, MTkernel, nSeedsMax, nSeedsPerEvent, numberOfEventToBeProcessed, nworkers, randDbl, and G4UImanager::SetMasterUIManager().
G4MTRunManager::~G4MTRunManager () virtual
Definition at line 154 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 154 of file G4MTRunManager.cc
References randDbl, and TerminateWorkers().
Member Function Documentation
void G4MTRunManager::AbortEvent () virtual
Reimplemented from G4RunManager.
Definition at line 605 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 605 of file G4MTRunManager.cc
void G4MTRunManager::AbortRun (G4bool softAbort = false) virtual
Reimplemented from G4RunManager.
Definition at line 589 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 589 of file G4MTRunManager.cc
References G4MTRunManagerKernel::BroadcastAbortRun(), G4cerr, G4endl, G4State_EventProc, G4State_GeomClosed, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), MTkernel, and G4RunManager::runAborted.
static void G4MTRunManager::addWorld (G4int counter, G4VPhysicalVolume * w) inline static
Definition at line 164 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 164 of file G4MTRunManager.hh
References masterWorlds.
Referenced by ConstructScoringWorlds().
void G4MTRunManager::ConstructScoringWorlds () virtual
Reimplemented from G4RunManager.
Definition at line 425 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 425 of file G4MTRunManager.cc
References addWorld(), G4RunManager::ConstructScoringWorlds(), G4TransportationManager::GetNoWorlds(), G4ScoringManager::GetScoringManagerIfExist(), G4TransportationManager::GetTransportationManager(), G4TransportationManager::GetWorldsIterator(), masterScM, and masterWorlds.
void G4MTRunManager::CreateAndStartWorkers () protected virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 270 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 270 of file G4MTRunManager.cc
References G4UserWorkerThreadInitialization::CreateAndStartWorker(), NewActionRequest(), nworkers, G4WorkerThread::SetNumberThreads(), G4WorkerThread::SetThreadId(), threads, and G4RunManager::userWorkerThreadInitialization.
Referenced by InitializeEventLoop().
std::vector< G4String > G4MTRunManager::GetCommandStack ()
Definition at line 264 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 264 of file G4MTRunManager.cc
References uiCmdsForWorkers.
Referenced by G4WorkerRunManager::DoWork(), and tbbTask::execute().
G4int G4MTRunManager::GetEventModulo () const inline
Definition at line 235 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 235 of file G4MTRunManager.hh
References eventModuloDef.
Referenced by G4WorkerRunManager::GenerateEvent().
const CLHEP::HepRandomEngine* G4MTRunManager::getMasterRandomEngine () const inline
Definition at line 165 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 165 of file G4MTRunManager.hh
References masterRNGEngine.
Referenced by tbbTask::execute(), G4WorkerRunManager::SetupDefaultRNGEngine(), and G4MTRunManagerKernel::StartThread().
G4MTRunManager * G4MTRunManager::GetMasterRunManager () static
Definition at line 59 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 59 of file G4MTRunManager.cc
References fMasterRM.
Referenced by G4VisManager::BeginOfRun(), UltraDetectorConstruction::ConstructReflector(), G4TheMTRayTracer::CreateBitMap(), G4TrajectoriesModel::DescribeYourselfTo(), G4WorkerRunManager::DoWork(), G4VisManager::Draw(), G4VisManager::EndOfEvent(), G4VisManager::EndOfRun(), tbbTask::execute(), G4WorkerRunManager::GenerateEvent(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), G4WorkerRunManager::MergePartialResults(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VSceneHandler::ProcessScene(), G4TheMTRayTracer::RestoreUserActions(), G4WorkerRunManager::RunInitialization(), G4WorkerRunManager::RunTermination(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), UltraDetectorConstruction::SetReflectionType(), G4WorkerRunManager::SetupDefaultRNGEngine(), G4MTRunManagerKernel::StartThread(), G4TheMTRayTracer::StoreUserActions(), G4RunManagerKernel::WorkerDefineWorldVolume(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
G4RunManagerKernel * G4MTRunManager::GetMasterRunManagerKernel () static
Definition at line 68 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 68 of file G4MTRunManager.cc
References fMasterRM, and G4RunManager::kernel.
Referenced by G4WorkerRunManager::InitializeGeometry().
static G4ScoringManager* G4MTRunManager::GetMasterScoringManager () inline static
Definition at line 162 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 162 of file G4MTRunManager.hh
References masterScM.
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), and G4WorkerRunManager::G4WorkerRunManager().
static masterWorlds_t& G4MTRunManager::GetMasterWorlds () inline static
Definition at line 163 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 163 of file G4MTRunManager.hh
References masterWorlds.
Referenced by G4RunManagerKernel::WorkerDefineWorldVolume(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
G4MTRunManagerKernel * G4MTRunManager::GetMTMasterRunManagerKernel () static
Definition at line 73 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 73 of file G4MTRunManager.cc
References fMasterRM, and MTkernel.
size_t G4MTRunManager::GetNumberActiveThreads () const inline
Definition at line 106 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MTRunManager.hh
References threads.
Referenced by NewActionRequest(), RequestWorkersProcessCommandsStack(), WaitForEndEventLoopWorkers(), and WaitForReadyWorkers().
G4int G4MTRunManager::GetNumberOfThreads () const inline
Definition at line 57 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MTRunManager.hh
References nworkers.
Referenced by main().
G4int G4MTRunManager::GetPinAffinity () const inline
Definition at line 59 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 59 of file G4MTRunManager.hh
References pinAffinity.
Referenced by G4MTRunManagerKernel::StartThread().
void G4MTRunManager::Initialize (void) virtual
G4UImanager::GetUIpointer()->SetIgnoreCmdNotFound(true);
Reimplemented from G4RunManager.
Definition at line 230 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 230 of file G4MTRunManager.cc
References G4RunManager::BeamOn(), G4RunManager::Initialize(), and G4RunManager::SetRunIDCounter().
Referenced by main().
void G4MTRunManager::InitializeEventLoop (G4int n_event, const char * macroFile = 0, G4int n_select = -1) virtual
Reimplemented from G4RunManager.
Definition at line 291 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 291 of file G4MTRunManager.cc
References CreateAndStartWorkers(), eventModulo, eventModuloDef, G4RunManager::fakeRun, G4TemplateRNGHelper< T >::Fill(), CLHEP::HepRandomEngine::flatArray(), G4Exception(), G4TemplateRNGHelper< T >::GetInstance(), InitializeSeeds(), int(), JustWarning, masterRNGEngine, G4RunManager::msgText, MTkernel, G4RunManager::n_select_msg, nSeedsFilled, nSeedsMax, nSeedsPerEvent, nSeedsUsed, G4RunManager::numberOfEventProcessed, numberOfEventToBeProcessed, nworkers, PrepareCommandsStack(), randDbl, seedOncePerCommunication, G4RunManager::selectMacro, G4MTRunManagerKernel::SetUpDecayChannels(), G4Timer::Start(), TIMEMORY_AUTO_TIMER, G4RunManager::timer, G4RunManager::userWorkerThreadInitialization, G4RunManager::verboseLevel, and WaitForReadyWorkers().
virtual G4bool G4MTRunManager::InitializeSeeds (G4int) inline protected virtual
Definition at line 93 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MTRunManager.hh
Referenced by InitializeEventLoop().
void G4MTRunManager::MergeRun (const G4Run * localRun)
Definition at line 511 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 511 of file G4MTRunManager.cc
References G4RunManager::currentRun, and G4Run::Merge().
Referenced by G4WorkerRunManager::MergePartialResults().
void G4MTRunManager::MergeScores (const G4ScoringManager * localScoringManager)
Definition at line 505 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 505 of file G4MTRunManager.cc
References masterScM, and G4ScoringManager::Merge().
Referenced by G4WorkerRunManager::MergePartialResults().
void G4MTRunManager::NewActionRequest (G4MTRunManager::WorkerActionRequest newRequest) protected virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 630 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 630 of file G4MTRunManager.cc
References GetNumberActiveThreads(), nextActionRequest, nextActionRequestBarrier, G4MTBarrier::ReleaseBarrier(), and G4MTBarrier::Wait().
Referenced by CreateAndStartWorkers(), RequestWorkersProcessCommandsStack(), and TerminateWorkers().
void G4MTRunManager::PrepareCommandsStack () protected virtual
Definition at line 253 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 253 of file G4MTRunManager.cc
References G4UImanager::GetCommandStack(), G4UImanager::GetUIpointer(), it, and uiCmdsForWorkers.
Referenced by InitializeEventLoop(), and RequestWorkersProcessCommandsStack().
void G4MTRunManager::ProcessOneEvent (G4int i_event) virtual
Reimplemented from G4RunManager.
Definition at line 244 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 244 of file G4MTRunManager.cc
void G4MTRunManager::RefillSeeds () protected
Definition at line 388 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 388 of file G4MTRunManager.cc
References eventModulo, CLHEP::HepRandomEngine::flatArray(), G4TemplateRNGHelper< T >::GetInstance(), masterRNGEngine, nSeedsFilled, nSeedsMax, nSeedsPerEvent, numberOfEventToBeProcessed, nworkers, randDbl, G4TemplateRNGHelper< T >::Refill(), and seedOncePerCommunication.
Referenced by SetUpAnEvent(), and SetUpNEvents().
void G4MTRunManager::RequestWorkersProcessCommandsStack () virtual
Definition at line 643 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 643 of file G4MTRunManager.cc
References GetNumberActiveThreads(), NewActionRequest(), PrepareCommandsStack(), processUIBarrier, G4MTBarrier::SetActiveThreads(), and G4MTBarrier::WaitForReadyWorkers().
Referenced by G4RunMessenger::SetNewValue(), and TerminateWorkers().
void G4MTRunManager::rndmSaveThisEvent () protected virtual
Reimplemented from G4RunManager.
Definition at line 199 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 199 of file G4MTRunManager.cc
References FatalException, and G4Exception().
void G4MTRunManager::rndmSaveThisRun () protected virtual
Reimplemented from G4RunManager.
Definition at line 171 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4MTRunManager.cc
References G4UImanager::ApplyCommand(), G4RunManager::currentRun, G4cerr, G4cout, G4endl, G4Run::GetRunID(), G4UImanager::GetUIpointer(), G4RunManager::randomNumberStatusDir, G4RunManager::storeRandomNumberStatus, and G4RunManager::verboseLevel.
void G4MTRunManager::RunTermination () virtual
Reimplemented from G4RunManager.
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 412 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 412 of file G4MTRunManager.cc
References G4RunManager::RunTermination(), G4RunManager::TerminateEventLoop(), and WaitForEndEventLoopWorkers().
Referenced by SimpleTbbMasterRunManager::RunTermination().
static G4int G4MTRunManager::SeedOncePerCommunication () inline static
Definition at line 258 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 258 of file G4MTRunManager.hh
References seedOncePerCommunication.
Referenced by G4WorkerRunManager::GenerateEvent(), and G4RunMessenger::GetCurrentValue().
void G4MTRunManager::SetEventModulo (G4int i = 1) inline
Definition at line 234 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 234 of file G4MTRunManager.hh
References eventModuloDef.
void G4MTRunManager::SetNumberOfThreads (G4int n)
Definition at line 205 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 205 of file G4MTRunManager.cc
References forcedNwokers, G4Exception(), JustWarning, n, nworkers, and threads.
Referenced by main().
void G4MTRunManager::SetPinAffinity (G4int n = 1)
Definition at line 653 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 653 of file G4MTRunManager.cc
References FatalException, G4Exception(), n, and pinAffinity.
static void G4MTRunManager::SetSeedOncePerCommunication (G4int val) inline static
Definition at line 259 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 259 of file G4MTRunManager.hh
References seedOncePerCommunication.
Referenced by G4RunMessenger::SetNewValue().
G4bool G4MTRunManager::SetUpAnEvent (G4Event * evt, long & s1, long & s2, long & s3, G4bool reseedRequired = true) virtual
Definition at line 517 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 517 of file G4MTRunManager.cc
References G4TemplateRNGHelper< T >::GetInstance(), G4TemplateRNGHelper< T >::GetSeed(), nSeedsFilled, nSeedsPerEvent, nSeedsUsed, G4RunManager::numberOfEventProcessed, numberOfEventToBeProcessed, RefillSeeds(), and G4Event::SetEventID().
Referenced by G4WorkerRunManager::GenerateEvent().
G4int G4MTRunManager::SetUpNEvents (G4Event * evt, G4SeedsQueue * seedsQueue, G4bool reseedRequired = true) virtual
Definition at line 539 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 539 of file G4MTRunManager.cc
References eventModulo, G4TemplateRNGHelper< T >::GetInstance(), G4TemplateRNGHelper< T >::GetSeed(), nSeedsFilled, nSeedsPerEvent, nSeedsUsed, G4RunManager::numberOfEventProcessed, numberOfEventToBeProcessed, RefillSeeds(), G4RunManager::runAborted, seedOncePerCommunication, and G4Event::SetEventID().
Referenced by G4WorkerRunManager::GenerateEvent().
void G4MTRunManager::SetUserAction (G4UserRunAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 469 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 469 of file G4MTRunManager.cc
References G4UserRunAction::SetMaster(), and G4RunManager::SetUserAction().
Referenced by G4TheMTRayTracer::RestoreUserActions(), and G4TheMTRayTracer::StoreUserActions().
void G4MTRunManager::SetUserAction (G4VUserPrimaryGeneratorAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 475 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 475 of file G4MTRunManager.cc
References FatalException, and G4Exception().
void G4MTRunManager::SetUserAction (G4UserEventAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 481 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 481 of file G4MTRunManager.cc
References FatalException, and G4Exception().
void G4MTRunManager::SetUserAction (G4UserStackingAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 487 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 487 of file G4MTRunManager.cc
References FatalException, and G4Exception().
void G4MTRunManager::SetUserAction (G4UserTrackingAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 493 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 493 of file G4MTRunManager.cc
References FatalException, and G4Exception().
void G4MTRunManager::SetUserAction (G4UserSteppingAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 499 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 499 of file G4MTRunManager.cc
References FatalException, and G4Exception().
void G4MTRunManager::SetUserInitialization (G4VUserPhysicsList * userPL) virtual
Reimplemented from G4RunManager.
Definition at line 458 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 458 of file G4MTRunManager.cc
References G4RunManager::SetUserInitialization().
Referenced by main(), G4TheMTRayTracer::RestoreUserActions(), and G4TheMTRayTracer::StoreUserActions().
void G4MTRunManager::SetUserInitialization (G4VUserDetectorConstruction * userDC) virtual
Reimplemented from G4RunManager.
Definition at line 464 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 464 of file G4MTRunManager.cc
References G4RunManager::SetUserInitialization().
void G4MTRunManager::SetUserInitialization (G4UserWorkerInitialization * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 442 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 442 of file G4MTRunManager.cc
References G4RunManager::userWorkerInitialization.
void G4MTRunManager::SetUserInitialization (G4UserWorkerThreadInitialization * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 447 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 447 of file G4MTRunManager.cc
References G4RunManager::userWorkerThreadInitialization.
void G4MTRunManager::SetUserInitialization (G4VUserActionInitialization * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 452 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 452 of file G4MTRunManager.cc
References G4VUserActionInitialization::BuildForMaster(), and G4RunManager::userActionInitialization.
void G4MTRunManager::StoreRNGStatus (const G4String & filenamePrefix) protected virtual
Reimplemented from G4RunManager.
Definition at line 164 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 164 of file G4MTRunManager.cc
References G4RunManager::randomNumberStatusDir.
void G4MTRunManager::TerminateOneEvent () virtual
Reimplemented from G4RunManager.
Definition at line 248 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 248 of file G4MTRunManager.cc
void G4MTRunManager::TerminateWorkers () protected virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 569 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 569 of file G4MTRunManager.cc
References G4UserWorkerThreadInitialization::JoinWorker(), NewActionRequest(), RequestWorkersProcessCommandsStack(), t, threads, and G4RunManager::userWorkerThreadInitialization.
Referenced by ~G4MTRunManager().
void G4MTRunManager::ThisWorkerEndEventLoop () virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 626 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 626 of file G4MTRunManager.cc
References endOfEventLoopBarrier, and G4MTBarrier::ThisWorkerReady().
Referenced by G4WorkerRunManager::RunTermination().
void G4MTRunManager::ThisWorkerProcessCommandsStackDone () virtual
Definition at line 650 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 650 of file G4MTRunManager.cc
References processUIBarrier, and G4MTBarrier::ThisWorkerReady().
Referenced by G4WorkerRunManager::DoWork().
void G4MTRunManager::ThisWorkerReady () virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 616 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 616 of file G4MTRunManager.cc
References beginOfEventLoopBarrier, and G4MTBarrier::ThisWorkerReady().
Referenced by G4WorkerRunManager::RunInitialization().
G4MTRunManager::WorkerActionRequest G4MTRunManager::ThisWorkerWaitForNextAction () virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 638 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 638 of file G4MTRunManager.cc
References nextActionRequest, nextActionRequestBarrier, and G4MTBarrier::ThisWorkerReady().
Referenced by G4WorkerRunManager::DoWork().
void G4MTRunManager::WaitForEndEventLoopWorkers () protected virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 620 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 620 of file G4MTRunManager.cc
References beginOfEventLoopBarrier, endOfEventLoopBarrier, GetNumberActiveThreads(), G4MTBarrier::ReleaseBarrier(), G4MTBarrier::ResetCounter(), and G4MTBarrier::Wait().
Referenced by RunTermination().
void G4MTRunManager::WaitForReadyWorkers () protected virtual
Reimplemented in SimpleTbbMasterRunManager.
Definition at line 610 of file G4MTRunManager.cc.
View newest version in sPHENIX GitHub at line 610 of file G4MTRunManager.cc
References beginOfEventLoopBarrier, endOfEventLoopBarrier, GetNumberActiveThreads(), G4MTBarrier::ReleaseBarrier(), G4MTBarrier::ResetCounter(), and G4MTBarrier::Wait().
Referenced by InitializeEventLoop().
Member Data Documentation
G4MTBarrier G4MTRunManager::beginOfEventLoopBarrier protected
Definition at line 262 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 262 of file G4MTRunManager.hh
Referenced by ThisWorkerReady(), WaitForEndEventLoopWorkers(), and WaitForReadyWorkers().
G4MTBarrier G4MTRunManager::endOfEventLoopBarrier protected
Definition at line 263 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 263 of file G4MTRunManager.hh
Referenced by ThisWorkerEndEventLoop(), WaitForEndEventLoopWorkers(), and WaitForReadyWorkers().
G4int G4MTRunManager::eventModulo protected
Definition at line 224 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 224 of file G4MTRunManager.hh
Referenced by InitializeEventLoop(), RefillSeeds(), and SetUpNEvents().
G4int G4MTRunManager::eventModuloDef protected
Definition at line 223 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 223 of file G4MTRunManager.hh
Referenced by GetEventModulo(), InitializeEventLoop(), and SetEventModulo().
G4MTRunManager * G4MTRunManager::fMasterRM = 0 static private
Definition at line 171 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 171 of file G4MTRunManager.hh
Referenced by G4MTRunManager(), GetMasterRunManager(), GetMasterRunManagerKernel(), and GetMTMasterRunManagerKernel().
G4int G4MTRunManager::forcedNwokers private
Definition at line 115 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4MTRunManager.hh
Referenced by G4MTRunManager(), and SetNumberOfThreads().
CLHEP::HepRandomEngine* G4MTRunManager::masterRNGEngine private
Definition at line 126 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4MTRunManager.hh
Referenced by G4MTRunManager(), getMasterRandomEngine(), InitializeEventLoop(), and RefillSeeds().
G4ScoringManager * G4MTRunManager::masterScM = 0 static private
Definition at line 168 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 168 of file G4MTRunManager.hh
Referenced by ConstructScoringWorlds(), G4MTRunManager(), GetMasterScoringManager(), and MergeScores().
G4MTRunManager::masterWorlds_t G4MTRunManager::masterWorlds = G4MTRunManager::masterWorlds_t() static private
Definition at line 169 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4MTRunManager.hh
Referenced by addWorld(), ConstructScoringWorlds(), and GetMasterWorlds().
G4MTRunManagerKernel* G4MTRunManager::MTkernel private
Definition at line 172 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 172 of file G4MTRunManager.hh
Referenced by AbortRun(), G4MTRunManager(), GetMTMasterRunManagerKernel(), and InitializeEventLoop().
WorkerActionRequest G4MTRunManager::nextActionRequest protected
Definition at line 219 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 219 of file G4MTRunManager.hh
Referenced by NewActionRequest(), and ThisWorkerWaitForNextAction().
G4MTBarrier G4MTRunManager::nextActionRequestBarrier protected
Definition at line 264 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 264 of file G4MTRunManager.hh
Referenced by NewActionRequest(), and ThisWorkerWaitForNextAction().
G4int G4MTRunManager::nSeedsFilled protected
Definition at line 226 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 226 of file G4MTRunManager.hh
Referenced by InitializeEventLoop(), RefillSeeds(), SetUpAnEvent(), and SetUpNEvents().
G4int G4MTRunManager::nSeedsMax protected
Definition at line 227 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 227 of file G4MTRunManager.hh
Referenced by G4MTRunManager(), InitializeEventLoop(), and RefillSeeds().
G4int G4MTRunManager::nSeedsPerEvent protected
Definition at line 228 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 228 of file G4MTRunManager.hh
Referenced by G4MTRunManager(), InitializeEventLoop(), RefillSeeds(), SetUpAnEvent(), and SetUpNEvents().
G4int G4MTRunManager::nSeedsUsed protected
Definition at line 225 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 225 of file G4MTRunManager.hh
Referenced by InitializeEventLoop(), SetUpAnEvent(), and SetUpNEvents().
G4int G4MTRunManager::numberOfEventToBeProcessed protected
Definition at line 142 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 142 of file G4MTRunManager.hh
Referenced by SimpleTbbMasterRunManager::CreateAndStartWorkers(), G4MTRunManager(), InitializeEventLoop(), RefillSeeds(), SetUpAnEvent(), and SetUpNEvents().
G4int G4MTRunManager::nworkers private
Definition at line 113 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4MTRunManager.hh
Referenced by CreateAndStartWorkers(), G4MTRunManager(), GetNumberOfThreads(), InitializeEventLoop(), RefillSeeds(), and SetNumberOfThreads().
G4int G4MTRunManager::pinAffinity private
Definition at line 117 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4MTRunManager.hh
Referenced by GetPinAffinity(), and SetPinAffinity().
G4MTBarrier G4MTRunManager::processUIBarrier protected
Definition at line 265 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 265 of file G4MTRunManager.hh
Referenced by RequestWorkersProcessCommandsStack(), and ThisWorkerProcessCommandsStackDone().
double* G4MTRunManager::randDbl protected
Definition at line 229 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 229 of file G4MTRunManager.hh
Referenced by G4MTRunManager(), InitializeEventLoop(), RefillSeeds(), and ~G4MTRunManager().
G4int G4MTRunManager::seedOncePerCommunication = 0 static protected
Definition at line 242 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 242 of file G4MTRunManager.hh
Referenced by InitializeEventLoop(), RefillSeeds(), SeedOncePerCommunication(), SetSeedOncePerCommunication(), and SetUpNEvents().
G4ThreadsList G4MTRunManager::threads private
Definition at line 121 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4MTRunManager.hh
Referenced by CreateAndStartWorkers(), GetNumberActiveThreads(), SetNumberOfThreads(), and TerminateWorkers().
std::vector<G4String> G4MTRunManager::uiCmdsForWorkers private
Definition at line 124 of file G4MTRunManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4MTRunManager.hh
Referenced by GetCommandStack(), and PrepareCommandsStack().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4MTRunManager.hh
geant4/tree/geant4-10.6-release/source/run/src/G4MTRunManager.cc