ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh File Reference
G4VTwistSurface.hh File Reference
#include <CLHEP/Units/SystemOfUnits.h>
#include "G4VSolid.hh"
#include "geomdefs.hh"
#include "G4RotationMatrix.hh"
#include "G4VTwistSurface.icc"
Classes
class G4VTwistSurface
class G4VTwistSurface::CurrentStatus
class G4VTwistSurface::Boundary
class G4VTwistSurface::G4SurfCurNormal
class G4VTwistSurface::G4SurfSideQuery
struct Intersection
Macros
#define G4VSURFACENXX 10
Functions
G4bool DistanceSort (const Intersection &a, const Intersection &b)
G4bool EqualIntersection (const Intersection &a, const Intersection &b)
Macro Definition Documentation
#define G4VSURFACENXX 10
Definition at line 46 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VTwistSurface.hh
Referenced by G4VTwistSurface::CurrentStatus::CurrentStatus(), G4VTwistSurface::DistanceTo(), G4VTwistSurface::DistanceToIn(), G4VTwistSurface::DistanceToOut(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), and G4VTwistSurface::CurrentStatus::ResetfDone().
Function Documentation
G4bool DistanceSort (const Intersection & a, const Intersection & b) inline
Definition at line 361 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 361 of file G4VTwistSurface.hh
References Intersection::distance.
Referenced by G4TwistBoxSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), and G4TwistTrapAlphaSide::DistanceToSurface().
G4bool EqualIntersection (const Intersection & a, const Intersection & b) inline
Definition at line 367 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 367 of file G4VTwistSurface.hh
References E, CLHEP::mm, and Intersection::xx.
Referenced by G4TwistBoxSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), and G4TwistTrapAlphaSide::DistanceToSurface().