ECCE @ EIC Software: G4CutTubs Class Reference
G4CutTubs Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4CutTubs.hh>
Public Member Functions
G4CutTubs (const G4String &pName, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi, G4ThreeVector pLowNorm, G4ThreeVector pHighNorm)
~G4CutTubs ()
G4double GetInnerRadius () const
G4double GetOuterRadius () const
G4double GetZHalfLength () const
G4double GetStartPhiAngle () const
G4double GetDeltaPhiAngle () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
G4ThreeVector GetLowNorm () const
G4ThreeVector GetHighNorm () const
void SetInnerRadius (G4double newRMin)
void SetOuterRadius (G4double newRMax)
void SetZHalfLength (G4double newDz)
void SetStartPhiAngle (G4double newSPhi, G4bool trig=true)
void SetDeltaPhiAngle (G4double newDPhi)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4CutTubs (__void__ &)
G4CutTubs (const G4CutTubs &rhs)
G4CutTubs & operator= (const G4CutTubs &rhs)
G4double GetRMin () const
G4double GetRMax () const
G4double GetDz () const
G4double GetSPhi () const
G4double GetDPhi () const
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Member Functions
void Initialize ()
void CheckSPhiAngle (G4double sPhi)
void CheckDPhiAngle (G4double dPhi)
void CheckPhiAngles (G4double sPhi, G4double dPhi)
void InitializeTrigonometry ()
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
G4bool IsCrossingCutPlanes () const
G4double GetCutZ (const G4ThreeVector &p) const
void GetMaxMinZ (G4double &zmin, G4double &zmax) const
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Private Attributes
G4double kRadTolerance
G4double kAngTolerance
G4double fRMin
G4double fRMax
G4double fDz
G4double fSPhi
G4double fDPhi
G4double sinCPhi
G4double cosCPhi
G4double cosHDPhi
G4double cosHDPhiOT
G4double cosHDPhiIT
G4double sinSPhi
G4double cosSPhi
G4double sinEPhi
G4double cosEPhi
G4bool fPhiFullCutTube = false
G4double halfCarTolerance
G4double halfRadTolerance
G4double halfAngTolerance
G4ThreeVector fLowNorm
G4ThreeVector fHighNorm
Additional Inherited Members
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 59 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 59 of file G4CutTubs.hh
Constructor & Destructor Documentation
G4CutTubs::G4CutTubs (const G4String & pName, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi, G4ThreeVector pLowNorm, G4ThreeVector pHighNorm)
Definition at line 58 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 58 of file G4CutTubs.cc
References CheckPhiAngles(), FatalException, fHighNorm, fLowNorm, G4endl, G4Exception(), G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4VSolid::GetName(), G4GeometryTolerance::GetRadialTolerance(), halfAngTolerance, halfCarTolerance, halfRadTolerance, JustWarning, kAngTolerance, G4VSolid::kCarTolerance, kRadTolerance, CLHEP::Hep3Vector::mag2(), message(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Clone().
G4CutTubs::~G4CutTubs ()
Definition at line 171 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 171 of file G4CutTubs.cc
G4CutTubs::G4CutTubs (__void__ & a)
Definition at line 157 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 157 of file G4CutTubs.cc
G4CutTubs::G4CutTubs (const G4CutTubs & rhs)
Definition at line 179 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 179 of file G4CutTubs.cc
Member Function Documentation
G4ThreeVector G4CutTubs::ApproxSurfaceNormal (const G4ThreeVector & p) const protected
Definition at line 645 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 645 of file G4CutTubs.cc
References cosEPhi, cosSPhi, G4VSolid::DumpInfo(), fDPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, fSPhi, G4Exception(), JustWarning, kNEPhi, kNRMax, kNRMin, kNSPhi, kNZ, min, norm, phi, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by SurfaceNormal().
void G4CutTubs::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 232 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 232 of file G4CutTubs.cc
References G4GeomTools::DiskExtent(), G4VSolid::DumpInfo(), dz, G4Exception(), GetCosEndPhi(), GetCosStartPhi(), GetDeltaPhiAngle(), GetHighNorm(), GetInnerRadius(), GetLowNorm(), G4VSolid::GetName(), GetOuterRadius(), GetSinEndPhi(), GetSinStartPhi(), GetZHalfLength(), JustWarning, max, message(), min, norm, pi, pMax, rmax(), CLHEP::Hep3Vector::set(), twopi, CLHEP::Hep2Vector::x(), CLHEP::Hep3Vector::x(), CLHEP::Hep2Vector::y(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), z1, and z2.
Referenced by CalculateExtent().
G4bool G4CutTubs::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 349 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 349 of file G4CutTubs.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), deg, GetCosEndPhi(), GetCosStartPhi(), GetDeltaPhiAngle(), GetInnerRadius(), GetOuterRadius(), GetSinEndPhi(), GetSinStartPhi(), k, pMax, rmax(), twopi, and CLHEP::Hep3Vector::z().
void G4CutTubs::CheckDPhiAngle (G4double dPhi) inline protected
void G4CutTubs::CheckPhiAngles (G4double sPhi, G4double dPhi) inline protected
Referenced by G4CutTubs().
void G4CutTubs::CheckSPhiAngle (G4double sPhi) inline protected
G4VSolid * G4CutTubs::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 1791 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1791 of file G4CutTubs.cc
References G4CutTubs().
G4Polyhedron * G4CutTubs::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1904 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1904 of file G4CutTubs.cc
References HepPolyhedron::createPolyhedron(), fDPhi, fDz, fRMax, fRMin, fSPhi, GetCutZ(), HepPolyhedron::GetFacet(), HepPolyhedron::GetNoFacets(), HepPolyhedron::GetNoVertices(), HepPolyhedron::GetVertex(), k, G4VSolid::kCarTolerance, n, G4InuclParticleNames::nn, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4CutTubs::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 1899 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1899 of file G4CutTubs.cc
References G4VGraphicsScene::AddSolid().
G4double G4CutTubs::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 789 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 789 of file G4CutTubs.cc
References b, c, cosCPhi, cosEPhi, cosHDPhiIT, cosSPhi, d, CLHEP::Hep3Vector::dot(), fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, GetCutZ(), halfCarTolerance, halfRadTolerance, kInfinity, kRadTolerance, sinCPhi, sinEPhi, sinSPhi, t1, t2, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4CutTubs::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1242 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1242 of file G4CutTubs.cc
References cosCPhi, cosEPhi, cosHDPhi, cosSPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, max, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
G4double G4CutTubs::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 1302 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1302 of file G4CutTubs.cc
References b, c, cosCPhi, cosEPhi, cosSPhi, d2, deltaR(), CLHEP::Hep3Vector::dot(), G4VSolid::DumpInfo(), false, fDPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, fSPhi, G4cout, G4endl, G4Exception(), halfAngTolerance, halfCarTolerance, JustWarning, G4VSolid::kCarTolerance, kEPhi, kInfinity, kMZ, kNull, kPZ, kRadTolerance, kRMax, kRMin, kSPhi, message(), mm, pi, sinCPhi, sinEPhi, sinSPhi, t1, t2, true, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4CutTubs::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1735 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1735 of file G4CutTubs.cc
References cosCPhi, cosEPhi, cosSPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, min, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
G4double G4CutTubs::GetCosEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4CutTubs::GetCosStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4CutTubs::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
G4double G4CutTubs::GetCutZ (const G4ThreeVector & p) const protected
Definition at line 1987 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1987 of file G4CutTubs.cc
References fDz, fHighNorm, fLowNorm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CreatePolyhedron(), DistanceToIn(), GetMaxMinZ(), GetPointOnSurface(), and IsCrossingCutPlanes().
G4double G4CutTubs::GetDeltaPhiAngle () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
G4double G4CutTubs::GetDPhi () const inline
G4double G4CutTubs::GetDz () const inline
G4GeometryType G4CutTubs::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 1782 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1782 of file G4CutTubs.cc
G4ThreeVector G4CutTubs::GetHighNorm () const inline
Referenced by BoundingLimits(), PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
G4double G4CutTubs::GetInnerRadius () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
G4ThreeVector G4CutTubs::GetLowNorm () const inline
Referenced by BoundingLimits(), PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
void G4CutTubs::GetMaxMinZ (G4double & zmin, G4double & zmax) const protected
Definition at line 2011 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 2011 of file G4CutTubs.cc
References cosEPhi, cosSPhi, fDPhi, fDz, fHighNorm, fLowNorm, fRMax, fRMin, fSPhi, GetCutZ(), max, min, pi, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), z, and z1.
G4double G4CutTubs::GetOuterRadius () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
G4ThreeVector G4CutTubs::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1825 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1825 of file G4CutTubs.cc
References cosEPhi, cosSPhi, fDPhi, fDz, fRMax, fRMin, fSPhi, GetCutZ(), G4CSGSolid::GetRadiusInRing(), phi, G4INCL::DeJongSpin::shoot(), sinEPhi, sinSPhi, and twopi.
G4double G4CutTubs::GetRMax () const inline
G4double G4CutTubs::GetRMin () const inline
G4double G4CutTubs::GetSinEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4CutTubs::GetSinStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4CutTubs::GetSPhi () const inline
G4double G4CutTubs::GetStartPhiAngle () const inline
Referenced by PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
G4double G4CutTubs::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
G4double G4CutTubs::GetZHalfLength () const inline
Referenced by BoundingLimits(), PHG4GDMLWriteSolids::CutTubeWrite(), and G4GDMLWriteSolids::CutTubeWrite().
void G4CutTubs::Initialize () inline protected
void G4CutTubs::InitializeTrigonometry () inline protected
EInside G4CutTubs::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 460 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 460 of file G4CutTubs.cc
References fDPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, fSPhi, halfAngTolerance, halfCarTolerance, halfRadTolerance, in, kAngTolerance, kInside, kOutside, kSurface, r2, twopi, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
G4bool G4CutTubs::IsCrossingCutPlanes () const protected
Definition at line 1964 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1964 of file G4CutTubs.cc
References fDz, fRMax, and GetCutZ().
G4CutTubs & G4CutTubs::operator= (const G4CutTubs & rhs)
Definition at line 200 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 200 of file G4CutTubs.cc
References cosCPhi, cosEPhi, cosHDPhiIT, cosHDPhiOT, cosSPhi, fDPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, fSPhi, halfAngTolerance, halfCarTolerance, halfRadTolerance, kAngTolerance, kRadTolerance, G4CSGSolid::operator=(), sinCPhi, sinEPhi, and sinSPhi.
void G4CutTubs::SetDeltaPhiAngle (G4double newDPhi) inline
void G4CutTubs::SetInnerRadius (G4double newRMin) inline
void G4CutTubs::SetOuterRadius (G4double newRMax) inline
void G4CutTubs::SetStartPhiAngle (G4double newSPhi, G4bool trig = true) inline
void G4CutTubs::SetZHalfLength (G4double newDz) inline
std::ostream & G4CutTubs::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 1800 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 1800 of file G4CutTubs.cc
References degree, fDPhi, fDz, fHighNorm, fLowNorm, fRMax, fRMin, fSPhi, G4VSolid::GetName(), and mm.
G4ThreeVector G4CutTubs::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 542 of file G4CutTubs.cc.
View newest version in sPHENIX GitHub at line 542 of file G4CutTubs.cc
References ApproxSurfaceNormal(), cosEPhi, cosSPhi, fDPhi, fDz, fHighNorm, fLowNorm, fPhiFullCutTube, fRMax, fRMin, fSPhi, G4cout, G4endl, G4Exception(), halfAngTolerance, halfCarTolerance, JustWarning, kInfinity, norm, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4CutTubs::cosCPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4CutTubs::cosEPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4CutTubs::cosHDPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by DistanceToIn().
G4double G4CutTubs::cosHDPhiIT private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by DistanceToIn(), and operator=().
G4double G4CutTubs::cosHDPhiOT private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by operator=().
G4double G4CutTubs::cosSPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4CutTubs::fDPhi private
Definition at line 195 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 195 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4CutTubs::fDz private
Definition at line 195 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 195 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCutZ(), GetMaxMinZ(), GetPointOnSurface(), Inside(), IsCrossingCutPlanes(), operator=(), StreamInfo(), and SurfaceNormal().
G4ThreeVector G4CutTubs::fHighNorm private
Definition at line 212 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 212 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4CutTubs(), GetCutZ(), GetMaxMinZ(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4ThreeVector G4CutTubs::fLowNorm private
Definition at line 212 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 212 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4CutTubs(), GetCutZ(), GetMaxMinZ(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4bool G4CutTubs::fPhiFullCutTube = false private
Definition at line 204 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 204 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4CutTubs::fRMax private
Definition at line 195 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 195 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), Inside(), IsCrossingCutPlanes(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4CutTubs::fRMin private
Definition at line 195 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 195 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4CutTubs::fSPhi private
Definition at line 195 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 195 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4CutTubs::halfAngTolerance private
Definition at line 208 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 208 of file G4CutTubs.hh
Referenced by DistanceToOut(), G4CutTubs(), Inside(), operator=(), and SurfaceNormal().
G4double G4CutTubs::halfCarTolerance private
Definition at line 208 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 208 of file G4CutTubs.hh
Referenced by DistanceToIn(), DistanceToOut(), G4CutTubs(), Inside(), operator=(), and SurfaceNormal().
G4double G4CutTubs::halfRadTolerance private
Definition at line 208 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 208 of file G4CutTubs.hh
Referenced by DistanceToIn(), G4CutTubs(), Inside(), and operator=().
G4double G4CutTubs::kAngTolerance private
Definition at line 191 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 191 of file G4CutTubs.hh
Referenced by G4CutTubs(), Inside(), and operator=().
G4double G4CutTubs::kRadTolerance private
Definition at line 191 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 191 of file G4CutTubs.hh
Referenced by DistanceToIn(), DistanceToOut(), G4CutTubs(), and operator=().
G4double G4CutTubs::sinCPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4CutTubs::sinEPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4CutTubs::sinSPhi private
Definition at line 199 of file G4CutTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4CutTubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetMaxMinZ(), GetPointOnSurface(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4CutTubs.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4CutTubs.cc