ECCE @ EIC Software: G4LENDManager Class Reference
G4LENDManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDManager.hh>
Public Member Functions
G4GIDI_target * GetLENDTarget (G4ParticleDefinition *, G4String, G4int iZ, G4int iA, G4int iM=0)
std::vector< G4String > IsLENDTargetAvailable (G4ParticleDefinition *, G4int iZ, G4int iA, G4int iM=0)
G4int GetNucleusEncoding (G4int iZ, G4int iA, G4int iM)
G4NistElementBuilder * GetNistElementBuilder ()
G4int GetVerboseLevel ()
G4bool RequestChangeOfVerboseLevel (G4int)
G4double GetExcitationEnergyOfExcitedIsomer (G4int, G4int, G4int)
Static Public Member Functions
static G4LENDManager * GetInstance ()
Private Member Functions
G4LENDManager ()
G4LENDManager (const G4LENDManager &)
G4LENDManager & operator= (const G4LENDManager &)
~G4LENDManager ()
void printBanner ()
Private Attributes
G4int verboseLevel
std::vector< lend_target > v_lend_target
std::map< G4ParticleDefinition
*, G4GIDI * > proj_lend_map
G4IonTable * ionTable
G4NistElementBuilder * nistElementBuilder
std::map< G4int, G4double > mExcitationEnergy
Static Private Attributes
static G4LENDManager * lend_manager = NULL
Detailed Description
Definition at line 63 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LENDManager.hh
Constructor & Destructor Documentation
G4LENDManager::G4LENDManager () private
Definition at line 56 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 56 of file G4LENDManager.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), CLHEP::eV, G4Gamma::Gamma(), G4ParticleTable::GetIonTable(), GetNucleusEncoding(), G4ParticleTable::GetParticleTable(), G4He3::He3(), ionTable, mExcitationEnergy, G4Neutron::Neutron(), nistElementBuilder, proj_lend_map, G4Proton::Proton(), G4Triton::Triton(), and v_lend_target.
Referenced by GetInstance().
G4LENDManager::G4LENDManager (const G4LENDManager &) private
G4LENDManager::~G4LENDManager () private
Definition at line 184 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 184 of file G4LENDManager.cc
References it, nistElementBuilder, proj_lend_map, and v_lend_target.
Member Function Documentation
G4double G4LENDManager::GetExcitationEnergyOfExcitedIsomer (G4int iZ, G4int iA, G4int iM)
Definition at line 407 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 407 of file G4LENDManager.cc
References G4cout, G4endl, GetNucleusEncoding(), it, and mExcitationEnergy.
Referenced by G4LENDElastic::ApplyYourself().
static G4LENDManager* G4LENDManager::GetInstance (void) inline static
Definition at line 77 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 77 of file G4LENDManager.hh
References G4LENDManager(), and lend_manager.
Referenced by G4LENDElastic::ApplyYourself(), G4LENDCrossSection::G4LENDCrossSection(), G4LENDModel::G4LENDModel(), and G4LENDUsedTarget::searchTarget().
G4GIDI_target * G4LENDManager::GetLENDTarget (G4ParticleDefinition * proj, G4String evaluation, G4int iZ, G4int iA, G4int iM = 0)
Definition at line 208 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 208 of file G4LENDManager.cc
References lend_target::evaluation, G4cout, G4endl, G4IonTable::GetIonName(), G4GIDI::getNamesOfAvailableLibraries(), GetNucleusEncoding(), G4ParticleDefinition::GetParticleName(), ionTable, G4GIDI::isThisDataAvailable(), it, lend_target::lend, proj, lend_target::proj, proj_lend_map, G4GIDI::readTarget(), second, lend_target::target, lend_target::target_code, v_lend_target, and verboseLevel.
Referenced by G4LENDUsedTarget::searchTarget().
G4NistElementBuilder* G4LENDManager::GetNistElementBuilder () inline
Definition at line 87 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 87 of file G4LENDManager.hh
References nistElementBuilder.
Referenced by G4LENDModel::create_used_target_map(), and G4LENDCrossSection::create_used_target_map().
G4int G4LENDManager::GetNucleusEncoding (G4int iZ, G4int iA, G4int iM)
Definition at line 343 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 343 of file G4LENDManager.cc
References G4IonTable::GetNucleusEncoding(), and ionTable.
Referenced by G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4LENDManager(), GetExcitationEnergyOfExcitedIsomer(), G4LENDCrossSection::GetIsoCrossSection(), GetLENDTarget(), G4LENDCombinedModel::HasData(), G4LENDGammaModel::HasData(), and G4LENDCrossSection::IsIsoApplicable().
G4int G4LENDManager::GetVerboseLevel () inline
Definition at line 89 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4LENDManager.hh
References verboseLevel.
Referenced by G4LENDModel::DumpLENDTargetInfo(), G4LENDCrossSection::DumpLENDTargetInfo(), and G4LENDModel::returnUnchanged().
std::vector< G4String > G4LENDManager::IsLENDTargetAvailable (G4ParticleDefinition * proj, G4int iZ, G4int iA, G4int iM = 0)
Definition at line 318 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 318 of file G4LENDManager.cc
References G4cout, G4endl, G4GIDI::getNamesOfAvailableLibraries(), G4ParticleDefinition::GetParticleName(), proj_lend_map, and second.
Referenced by G4LENDUsedTarget::searchTarget().
G4LENDManager& G4LENDManager::operator= (const G4LENDManager &) private
void G4LENDManager::printBanner () private
Definition at line 353 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 353 of file G4LENDManager.cc
References G4cout, and G4endl.
G4bool G4LENDManager::RequestChangeOfVerboseLevel (G4int newValue)
Definition at line 391 of file G4LENDManager.cc.
View newest version in sPHENIX GitHub at line 391 of file G4LENDManager.cc
References G4cout, G4endl, and verboseLevel.
Referenced by G4LENDModel::create_used_target_map(), and G4LENDCrossSection::create_used_target_map().
Member Data Documentation
G4IonTable* G4LENDManager::ionTable private
Definition at line 104 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4LENDManager.hh
Referenced by G4LENDManager(), GetLENDTarget(), and GetNucleusEncoding().
G4LENDManager * G4LENDManager::lend_manager = NULL static private
Definition at line 66 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LENDManager.hh
Referenced by GetInstance().
std::map< G4int , G4double > G4LENDManager::mExcitationEnergy private
Definition at line 112 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 112 of file G4LENDManager.hh
Referenced by G4LENDManager(), and GetExcitationEnergyOfExcitedIsomer().
G4NistElementBuilder* G4LENDManager::nistElementBuilder private
Definition at line 106 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4LENDManager.hh
Referenced by G4LENDManager(), GetNistElementBuilder(), and ~G4LENDManager().
std::map< G4ParticleDefinition* , G4GIDI* > G4LENDManager::proj_lend_map private
Definition at line 100 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4LENDManager.hh
Referenced by G4LENDManager(), GetLENDTarget(), IsLENDTargetAvailable(), and ~G4LENDManager().
std::vector< lend_target > G4LENDManager::v_lend_target private
Definition at line 97 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 97 of file G4LENDManager.hh
Referenced by G4LENDManager(), GetLENDTarget(), and ~G4LENDManager().
G4int G4LENDManager::verboseLevel private
Definition at line 95 of file G4LENDManager.hh.
View newest version in sPHENIX GitHub at line 95 of file G4LENDManager.hh
Referenced by GetLENDTarget(), GetVerboseLevel(), and RequestChangeOfVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDManager.cc