ECCE @ EIC Software: G4NavigationLevel Class Reference
G4NavigationLevel Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationLevel.hh>
Public Member Functions
G4NavigationLevel (G4VPhysicalVolume *newPtrPhysVol, const G4AffineTransform &newT, EVolume newVolTp, G4int newRepNo=-1)
G4NavigationLevel (G4VPhysicalVolume *newPtrPhysVol, const G4AffineTransform &levelAbove, const G4AffineTransform &relativeCurrent, EVolume newVolTp, G4int newRepNo=-1)
G4NavigationLevel ()
G4NavigationLevel (const G4NavigationLevel &)
~G4NavigationLevel ()
G4NavigationLevel & operator= (const G4NavigationLevel &right)
G4VPhysicalVolume * GetPhysicalVolume () const
const G4AffineTransform * GetTransformPtr () const
const G4AffineTransform & GetTransform () const
EVolume GetVolumeType () const
G4int GetReplicaNo () const
const G4AffineTransform * GetPtrTransform () const
void * operator new (size_t)
void operator delete (void *aLevel)
void * operator new (size_t, void *)
void operator delete (void *ptr, void *)
Private Attributes
G4NavigationLevelRep * fLevelRep
Detailed Description
Definition at line 49 of file G4NavigationLevel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4NavigationLevel.hh
Constructor & Destructor Documentation
G4NavigationLevel::G4NavigationLevel (G4VPhysicalVolume * newPtrPhysVol, const G4AffineTransform & newT, EVolume newVolTp, G4int newRepNo = -1)
Definition at line 39 of file G4NavigationLevel.cc.
View newest version in sPHENIX GitHub at line 39 of file G4NavigationLevel.cc
References fLevelRep.
G4NavigationLevel::G4NavigationLevel (G4VPhysicalVolume * newPtrPhysVol, const G4AffineTransform & levelAbove, const G4AffineTransform & relativeCurrent, EVolume newVolTp, G4int newRepNo = -1)
Definition at line 47 of file G4NavigationLevel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4NavigationLevel.cc
References fLevelRep.
G4NavigationLevel::G4NavigationLevel ()
Definition at line 60 of file G4NavigationLevel.cc.
View newest version in sPHENIX GitHub at line 60 of file G4NavigationLevel.cc
References fLevelRep.
G4NavigationLevel::G4NavigationLevel (const G4NavigationLevel & right)
Definition at line 65 of file G4NavigationLevel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4NavigationLevel.cc
References G4NavigationLevelRep::AddAReference(), and fLevelRep.
G4NavigationLevel::~G4NavigationLevel ()
Definition at line 71 of file G4NavigationLevel.cc.
View newest version in sPHENIX GitHub at line 71 of file G4NavigationLevel.cc
References fLevelRep, and G4NavigationLevelRep::RemoveAReference().
Member Function Documentation
G4VPhysicalVolume* G4NavigationLevel::GetPhysicalVolume () const inline
const G4AffineTransform* G4NavigationLevel::GetPtrTransform () const inline
G4int G4NavigationLevel::GetReplicaNo () const inline
const G4AffineTransform& G4NavigationLevel::GetTransform () const inline
const G4AffineTransform* G4NavigationLevel::GetTransformPtr () const inline
EVolume G4NavigationLevel::GetVolumeType () const inline
void G4NavigationLevel::operator delete (void * aLevel) inline
void G4NavigationLevel::operator delete (void * ptr, void *) inline
void* G4NavigationLevel::operator new (size_t) inline
void* G4NavigationLevel::operator new (size_t , void *) inline
G4NavigationLevel & G4NavigationLevel::operator= (const G4NavigationLevel & right)
Definition at line 76 of file G4NavigationLevel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4NavigationLevel.cc
References G4NavigationLevelRep::AddAReference(), fLevelRep, and G4NavigationLevelRep::RemoveAReference().
Member Data Documentation
G4NavigationLevelRep* G4NavigationLevel::fLevelRep private
Definition at line 100 of file G4NavigationLevel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4NavigationLevel.hh
Referenced by G4NavigationLevel(), operator=(), and ~G4NavigationLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationLevel.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4NavigationLevel.cc