ECCE @ EIC Software: CLHEP::RandChiSquare Class Reference
CLHEP::RandChiSquare Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandChiSquare.h>
Public Member Functions
RandChiSquare (HepRandomEngine &anEngine, double a=1)
RandChiSquare (HepRandomEngine *anEngine, double a=1)
virtual ~RandChiSquare ()
double fire ()
double fire (double a)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double a)
double operator() ()
double operator() (double a)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double a)
static void shootArray (const int size, double *vect, double a=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double a)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double a=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Private Member Functions
static double genChiSquare (HepRandomEngine *anEngine, double a)
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double defaultA
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 36 of file RandChiSquare.h.
View newest version in sPHENIX GitHub at line 36 of file RandChiSquare.h
Constructor & Destructor Documentation
CLHEP::RandChiSquare::RandChiSquare (HepRandomEngine & anEngine, double a = 1) inline
CLHEP::RandChiSquare::RandChiSquare (HepRandomEngine * anEngine, double a = 1) inline
CLHEP::RandChiSquare::~RandChiSquare () virtual
Definition at line 27 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 27 of file RandChiSquare.cc
Member Function Documentation
static std::string CLHEP::RandChiSquare::distributionName () inline static
Definition at line 95 of file RandChiSquare.h.
View newest version in sPHENIX GitHub at line 95 of file RandChiSquare.h
HepRandomEngine & CLHEP::RandChiSquare::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 25 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 25 of file RandChiSquare.cc
References localEngine.
double CLHEP::RandChiSquare::fire () inline
Referenced by fireArray().
double CLHEP::RandChiSquare::fire (double a)
Definition at line 39 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 39 of file RandChiSquare.cc
References a, genChiSquare(), and localEngine.
void CLHEP::RandChiSquare::fireArray (const int size, double * vect)
Definition at line 57 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 57 of file RandChiSquare.cc
References defaultA, fire(), and v.
void CLHEP::RandChiSquare::fireArray (const int size, double * vect, double a)
Definition at line 62 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 62 of file RandChiSquare.cc
References fire(), and v.
double CLHEP::RandChiSquare::genChiSquare (HepRandomEngine * anEngine, double a) static private
Definition at line 68 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 68 of file RandChiSquare.cc
References a, b, CLHEP_THREAD_LOCAL, CLHEP::HepRandomEngine::flat(), r, Acts::UnitConstants::u, v, z, and zz.
Referenced by fire(), and shoot().
std::istream & CLHEP::RandChiSquare::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 148 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 148 of file RandChiSquare.cc
References defaultA, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandChiSquare::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 24 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 24 of file RandChiSquare.cc
Referenced by get(), and put().
double CLHEP::RandChiSquare::operator() () inline virtual
Reimplemented from CLHEP::HepRandom.
double CLHEP::RandChiSquare::operator() (double a) inline
std::ostream & CLHEP::RandChiSquare::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 137 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 137 of file RandChiSquare.cc
References defaultA, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
static double CLHEP::RandChiSquare::shoot () inline static
Referenced by shootArray().
double CLHEP::RandChiSquare::shoot (double a) static
Definition at line 34 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 34 of file RandChiSquare.cc
References genChiSquare(), and CLHEP::HepRandom::getTheEngine().
static double CLHEP::RandChiSquare::shoot (HepRandomEngine * anEngine) inline static
double CLHEP::RandChiSquare::shoot (HepRandomEngine * anEngine, double a) static
Definition at line 30 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 30 of file RandChiSquare.cc
References genChiSquare().
void CLHEP::RandChiSquare::shootArray (const int size, double * vect, double a = 1.0) static
Definition at line 43 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 43 of file RandChiSquare.cc
References shoot(), and v.
void CLHEP::RandChiSquare::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double a = 1.0) static
Definition at line 49 of file RandChiSquare.cc.
View newest version in sPHENIX GitHub at line 49 of file RandChiSquare.cc
References shoot(), and v.
Member Data Documentation
double CLHEP::RandChiSquare::defaultA private
Definition at line 103 of file RandChiSquare.h.
View newest version in sPHENIX GitHub at line 103 of file RandChiSquare.h
Referenced by fireArray(), get(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandChiSquare::localEngine private
Definition at line 102 of file RandChiSquare.h.
View newest version in sPHENIX GitHub at line 102 of file RandChiSquare.h
Referenced by engine(), and fire().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandChiSquare.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandChiSquare.cc