ECCE @ EIC Software: G4tgbGeometryDumper Class Reference
G4tgbGeometryDumper Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbGeometryDumper.hh>
Public Member Functions
~G4tgbGeometryDumper ()
void DumpGeometry (const G4String &fname)
G4VPhysicalVolume * GetTopPhysVol ()
void DumpPhysVol (G4VPhysicalVolume *pv)
void DumpPVPlacement (G4VPhysicalVolume *pv, const G4String &lvName, G4int copyNo=-999)
void DumpPVParameterised (G4PVParameterised *pv)
void DumpPVReplica (G4PVReplica *pv, const G4String &lvName)
G4String DumpLogVol (G4LogicalVolume *lv, G4String extraName="", G4VSolid *solid=0, G4Material *mate=0)
G4String DumpMaterial (G4Material *mat)
void DumpElement (G4Element *ele)
void DumpIsotope (G4Isotope *ele)
G4String DumpSolid (G4VSolid *solid, const G4String &extraName="")
void DumpBooleanVolume (const G4String &solidType, G4VSolid *so)
void DumpSolidParams (G4VSolid *so)
std::vector< G4double > GetSolidParams (const G4VSolid *so)
void DumpPolySections (G4int zPlanes, G4double *z, G4double *rmin, G4double *rmax)
G4String DumpRotationMatrix (G4RotationMatrix *rotm)
Static Public Member Functions
static G4tgbGeometryDumper * GetInstance ()
Private Member Functions
G4tgbGeometryDumper ()
std::vector< G4VPhysicalVolume * > GetPVChildren (G4LogicalVolume *lv)
G4String GetTGSolidType (const G4String &solidtype)
G4double MatDeterminant (G4RotationMatrix *ro)
G4double approxTo0 (G4double val)
G4String AddQuotes (const G4String &str)
G4String GetIsotopeName (G4Isotope *)
template<class TYP >
G4String GetObjectName (TYP *obj, std::map< G4String, TYP * > objectsDumped)
G4bool CheckIfLogVolExists (const G4String &name, G4LogicalVolume *pt)
G4bool CheckIfPhysVolExists (const G4String &name, G4VPhysicalVolume *)
G4String LookForExistingRotation (const G4RotationMatrix *rotm)
G4String SupressRefl (G4String name)
G4String SubstituteRefl (G4String name)
G4bool Same2G4Isotopes (G4Isotope *ele1, G4Isotope *ele2)
const G4String & FindSolidName (G4VSolid *solid)
Private Attributes
std::ofstream * theFile
std::map< G4String, G4Material * > theMaterials
std::map< G4String, G4Element * > theElements
std::map< G4String, G4Isotope * > theIsotopes
std::map< G4String, G4VSolid * > theSolids
std::map< G4String,
G4LogicalVolume * > theLogVols
std::map< G4String,
G4VPhysicalVolume * > thePhysVols
std::map< G4String,
G4RotationMatrix * > theRotMats
G4int theRotationNumber
Static Private Attributes
static G4ThreadLocal
G4tgbGeometryDumper * theInstance = 0
Detailed Description
Definition at line 56 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 56 of file G4tgbGeometryDumper.hh
Constructor & Destructor Documentation
G4tgbGeometryDumper::~G4tgbGeometryDumper ()
Definition at line 134 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 134 of file G4tgbGeometryDumper.cc
G4tgbGeometryDumper::G4tgbGeometryDumper () private
Definition at line 82 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 82 of file G4tgbGeometryDumper.cc
Referenced by GetInstance().
Member Function Documentation
G4String G4tgbGeometryDumper::AddQuotes (const G4String & str) private
Definition at line 1113 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1113 of file G4tgbGeometryDumper.cc
References FALSE, and TRUE.
Referenced by DumpBooleanVolume(), DumpElement(), DumpIsotope(), DumpLogVol(), DumpMaterial(), DumpPVPlacement(), DumpPVReplica(), DumpRotationMatrix(), and DumpSolid().
G4double G4tgbGeometryDumper::approxTo0 (G4double val) private
Definition at line 1102 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1102 of file G4tgbGeometryDumper.cc
References G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), and precision.
Referenced by DumpBooleanVolume(), and DumpRotationMatrix().
G4bool G4tgbGeometryDumper::CheckIfLogVolExists (const G4String & name, G4LogicalVolume * pt) private
Definition at line 1256 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1256 of file G4tgbGeometryDumper.cc
References theLogVols.
Referenced by DumpPhysVol().
G4bool G4tgbGeometryDumper::CheckIfPhysVolExists (const G4String & name, G4VPhysicalVolume * pt) private
Definition at line 1286 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1286 of file G4tgbGeometryDumper.cc
References G4cerr, G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), pt, and thePhysVols.
Referenced by DumpPVPlacement(), and DumpPVReplica().
void G4tgbGeometryDumper::DumpBooleanVolume (const G4String & solidType, G4VSolid * so)
Definition at line 698 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 698 of file G4tgbGeometryDumper.cc
References AddQuotes(), approxTo0(), DumpRotationMatrix(), DumpSolid(), FindSolidName(), G4endl, G4DisplacedSolid::GetConstituentMovedSolid(), G4BooleanSolid::GetConstituentSolid(), GetObjectName(), G4DisplacedSolid::GetObjectTranslation(), pos(), theSolids, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DumpSolid().
void G4tgbGeometryDumper::DumpElement (G4Element * ele)
Definition at line 578 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 578 of file G4tgbGeometryDumper.cc
References AddQuotes(), DumpIsotope(), ele, Acts::UnitConstants::g, G4endl, G4Element::GetA(), G4Element::GetIsotopeVector(), G4Element::GetNumberOfIsotopes(), GetObjectName(), G4Element::GetRelativeAbundanceVector(), G4Element::GetSymbol(), G4Element::GetZ(), mole, theElements, and theIsotopes.
Referenced by DumpMaterial().
void G4tgbGeometryDumper::DumpGeometry (const G4String & fname)
Definition at line 99 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 99 of file G4tgbGeometryDumper.cc
References DumpPhysVol(), GetTopPhysVol(), and theFile.
Referenced by ExTGRunAction::BeginOfRunAction().
void G4tgbGeometryDumper::DumpIsotope (G4Isotope * ele)
Definition at line 626 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 626 of file G4tgbGeometryDumper.cc
References AddQuotes(), Acts::UnitConstants::g, G4endl, G4Isotope::GetA(), G4Isotope::GetN(), GetObjectName(), G4Isotope::GetZ(), mole, and theIsotopes.
Referenced by DumpElement().
G4String G4tgbGeometryDumper::DumpLogVol (G4LogicalVolume * lv, G4String extraName = "", G4VSolid * solid = 0, G4Material * mate = 0)
Definition at line 460 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 460 of file G4tgbGeometryDumper.cc
References AddQuotes(), DumpMaterial(), DumpSolid(), G4endl, G4LogicalVolume::GetMaterial(), G4LogicalVolume::GetName(), GetObjectName(), G4LogicalVolume::GetSolid(), SubstituteRefl(), SupressRefl(), and theLogVols.
Referenced by DumpPhysVol(), and DumpPVParameterised().
G4String G4tgbGeometryDumper::DumpMaterial (G4Material * mat)
Definition at line 500 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 500 of file G4tgbGeometryDumper.cc
References AddQuotes(), atmosphere, cm3, DumpElement(), eV, Acts::UnitConstants::g, G4endl, G4Material::GetA(), G4Material::GetDensity(), G4Material::GetElementVector(), G4Material::GetFractionVector(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), G4Material::GetNumberOfElements(), GetObjectName(), G4Material::GetPressure(), G4Material::GetState(), G4Material::GetTemperature(), G4Material::GetZ(), kelvin, kStateGas, kStateLiquid, kStateSolid, kStateUndefined, mat, mole, theElements, and theMaterials.
Referenced by DumpLogVol().
void G4tgbGeometryDumper::DumpPhysVol (G4VPhysicalVolume * pv)
Definition at line 139 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 139 of file G4tgbGeometryDumper.cc
References CheckIfLogVolExists(), DumpLogVol(), DumpPVParameterised(), DumpPVPlacement(), DumpPVReplica(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMotherLogical(), G4LogicalVolume::GetName(), GetPVChildren(), G4ReflectionFactory::Instance(), G4VPhysicalVolume::IsParameterised(), G4ReflectionFactory::IsReflected(), and G4VPhysicalVolume::IsReplicated().
Referenced by DumpGeometry().
void G4tgbGeometryDumper::DumpPolySections (G4int zPlanes, G4double * z, G4double * rmin, G4double * rmax)
void G4tgbGeometryDumper::DumpPVParameterised (G4PVParameterised * pv)
Definition at line 267 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 267 of file G4tgbGeometryDumper.cc
References G4VPVParameterisation::ComputeDimensions(), G4VPVParameterisation::ComputeMaterial(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), G4UIcommand::ConvertToString(), DumpLogVol(), DumpPVPlacement(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4PVParameterised::GetParameterisation(), G4PVParameterised::GetReplicationData(), GetSolidParams(), offset, and width.
Referenced by DumpPhysVol().
void G4tgbGeometryDumper::DumpPVPlacement (G4VPhysicalVolume * pv, const G4String & lvName, G4int copyNo = -999)
Definition at line 205 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 205 of file G4tgbGeometryDumper.cc
References AddQuotes(), CheckIfPhysVolExists(), CLHEP::HepRotation::colX(), CLHEP::HepRotation::colY(), CLHEP::HepRotation::colZ(), G4UIcommand::ConvertToString(), DumpRotationMatrix(), G4cout, G4endl, G4VPhysicalVolume::GetCopyNo(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4VPhysicalVolume::GetRotation(), G4VPhysicalVolume::GetTranslation(), G4tgrMessenger::GetVerboseLevel(), G4ReflectionFactory::Instance(), G4ReflectionFactory::IsReflected(), pos(), SubstituteRefl(), thePhysVols, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DumpPhysVol(), and DumpPVParameterised().
void G4tgbGeometryDumper::DumpPVReplica (G4PVReplica * pv, const G4String & lvName)
Definition at line 393 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 393 of file G4tgbGeometryDumper.cc
References AddQuotes(), CheckIfPhysVolExists(), deg, FatalException, G4endl, G4Exception(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4PVReplica::GetReplicationData(), kPhi, kRadial3D, kRho, kUndefined, kXAxis, kYAxis, kZAxis, offset, SubstituteRefl(), thePhysVols, and width.
Referenced by DumpPhysVol().
G4String G4tgbGeometryDumper::DumpRotationMatrix (G4RotationMatrix * rotm)
Definition at line 1006 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1006 of file G4tgbGeometryDumper.cc
References AddQuotes(), approxTo0(), G4UIcommand::ConvertToString(), deg, G4endl, LookForExistingRotation(), MatDeterminant(), CLHEP::HepRotation::phiX(), CLHEP::HepRotation::phiY(), CLHEP::HepRotation::phiZ(), theRotationNumber, theRotMats, CLHEP::HepRotation::thetaX(), CLHEP::HepRotation::thetaY(), CLHEP::HepRotation::thetaZ(), v, CLHEP::HepRotation::xx(), CLHEP::HepRotation::xy(), CLHEP::HepRotation::xz(), CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
Referenced by DumpBooleanVolume(), and DumpPVPlacement().
G4String G4tgbGeometryDumper::DumpSolid (G4VSolid * solid, const G4String & extraName = "")
Definition at line 643 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 643 of file G4tgbGeometryDumper.cc
References AddQuotes(), DumpBooleanVolume(), DumpSolidParams(), FatalException, G4Exception(), G4ReflectedSolid::GetConstituentMovedSolid(), G4VSolid::GetEntityType(), G4VSolid::GetName(), GetObjectName(), GetTGSolidType(), and theSolids.
Referenced by DumpBooleanVolume(), and DumpLogVol().
void G4tgbGeometryDumper::DumpSolidParams (G4VSolid * so)
Definition at line 749 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 749 of file G4tgbGeometryDumper.cc
References G4endl, and GetSolidParams().
Referenced by DumpSolid().
const G4String & G4tgbGeometryDumper::FindSolidName (G4VSolid * solid) private
Definition at line 1353 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1353 of file G4tgbGeometryDumper.cc
References FatalException, G4String::first(), G4Exception(), and theSolids.
Referenced by DumpBooleanVolume().
G4tgbGeometryDumper * G4tgbGeometryDumper::GetInstance (void) static
Definition at line 88 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 88 of file G4tgbGeometryDumper.cc
References G4tgbGeometryDumper(), and theInstance.
Referenced by ExTGRunAction::BeginOfRunAction().
G4String G4tgbGeometryDumper::GetIsotopeName (G4Isotope * isot) private
Definition at line 1160 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1160 of file G4tgbGeometryDumper.cc
References G4UIcommand::ConvertToString(), G4String::first(), G4Isotope::GetName(), Same2G4Isotopes(), and theIsotopes.
template<class TYP > G4String G4tgbGeometryDumper::GetObjectName (TYP * obj, std::map< G4String, TYP * > objectsDumped) private
Definition at line 1214 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1214 of file G4tgbGeometryDumper.cc
References G4UIcommand::ConvertToString(), and G4String::first().
Referenced by DumpBooleanVolume(), DumpElement(), DumpIsotope(), DumpLogVol(), DumpMaterial(), and DumpSolid().
std::vector< G4VPhysicalVolume * > G4tgbGeometryDumper::GetPVChildren (G4LogicalVolume * lv) private
Definition at line 1055 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1055 of file G4tgbGeometryDumper.cc
References G4cout, G4endl, G4PhysicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), and G4tgrMessenger::GetVerboseLevel().
Referenced by DumpPhysVol().
std::vector< G4double > G4tgbGeometryDumper::GetSolidParams (const G4VSolid * so)
Definition at line 761 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 761 of file G4tgbGeometryDumper.cc
References deg, FatalException, G4Exception(), G4TwistedTrap::GetAzimuthalAnglePhi(), G4GenericPolycone::GetCorner(), G4Polycone::GetCorner(), G4Polyhedra::GetCorner(), G4Tubs::GetDeltaPhiAngle(), G4Cons::GetDeltaPhiAngle(), G4Sphere::GetDeltaPhiAngle(), G4Sphere::GetDeltaThetaAngle(), G4Torus::GetDPhi(), G4TwistedTubs::GetDPhi(), G4EllipticalTube::GetDx(), G4EllipticalTube::GetDy(), G4EllipticalTube::GetDz(), G4GenericPolycone::GetEndPhi(), G4VSolid::GetEntityType(), G4Hype::GetInnerRadius(), G4Tubs::GetInnerRadius(), G4Sphere::GetInnerRadius(), G4TwistedTubs::GetInnerRadius(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4Hype::GetInnerStereo(), G4GenericPolycone::GetNumRZCorner(), G4Polycone::GetNumRZCorner(), G4Polyhedra::GetNumRZCorner(), G4Polyhedra::GetNumSide(), G4Polycone::GetOriginalParameters(), G4Polyhedra::GetOriginalParameters(), G4Hype::GetOuterRadius(), G4Tubs::GetOuterRadius(), G4Sphere::GetOuterRadius(), G4TwistedTubs::GetOuterRadius(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Hype::GetOuterStereo(), G4TwistedBox::GetPhiTwist(), G4TwistedTrd::GetPhiTwist(), G4TwistedTrap::GetPhiTwist(), G4TwistedTubs::GetPhiTwist(), G4TwistedTrap::GetPolarAngleTheta(), G4Orb::GetRadius(), G4Torus::GetRmax(), G4Torus::GetRmin(), G4Torus::GetRtor(), G4Ellipsoid::GetSemiAxisMax(), G4Torus::GetSPhi(), G4GenericPolycone::GetStartPhi(), G4Polycone::GetStartPhi(), G4Polyhedra::GetStartPhi(), G4Tubs::GetStartPhiAngle(), G4Cons::GetStartPhiAngle(), G4Sphere::GetStartPhiAngle(), G4Sphere::GetStartThetaAngle(), G4Para::GetSymAxis(), G4Trap::GetSymAxis(), G4Para::GetTanAlpha(), G4Trap::GetTanAlpha1(), G4Trap::GetTanAlpha2(), GetTGSolidType(), G4TwistedTrap::GetTiltAngleAlpha(), G4TwistedTrd::GetX1HalfLength(), G4TwistedTrap::GetX1HalfLength(), G4TwistedTrd::GetX2HalfLength(), G4TwistedTrap::GetX2HalfLength(), G4TwistedTrap::GetX3HalfLength(), G4TwistedTrap::GetX4HalfLength(), G4TwistedBox::GetXHalfLength(), G4Box::GetXHalfLength(), G4Para::GetXHalfLength(), G4Trd::GetXHalfLength1(), G4Trap::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trap::GetXHalfLength2(), G4Trap::GetXHalfLength3(), G4Trap::GetXHalfLength4(), G4TwistedTrd::GetY1HalfLength(), G4TwistedTrap::GetY1HalfLength(), G4TwistedTrd::GetY2HalfLength(), G4TwistedTrap::GetY2HalfLength(), G4TwistedBox::GetYHalfLength(), G4Box::GetYHalfLength(), G4Para::GetYHalfLength(), G4Trd::GetYHalfLength1(), G4Trap::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trap::GetYHalfLength2(), G4Ellipsoid::GetZBottomCut(), G4TwistedBox::GetZHalfLength(), G4TwistedTrd::GetZHalfLength(), G4Box::GetZHalfLength(), G4Trd::GetZHalfLength(), G4Para::GetZHalfLength(), G4Hype::GetZHalfLength(), G4Tubs::GetZHalfLength(), G4TwistedTrap::GetZHalfLength(), G4Cons::GetZHalfLength(), G4TwistedTubs::GetZHalfLength(), G4Trap::GetZHalfLength(), G4Ellipsoid::GetZTopCut(), G4PolyconeHistorical::Opening_angle, G4PolyhedraHistorical::Opening_angle, G4PolyconeSideRZ::r, G4PolyhedraSideRZ::r, G4PolyconeSideRZ::z, and G4PolyhedraSideRZ::z.
Referenced by DumpPVParameterised(), and DumpSolidParams().
G4String G4tgbGeometryDumper::GetTGSolidType (const G4String & solidtype) private
Definition at line 1080 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1080 of file G4tgbGeometryDumper.cc
Referenced by DumpSolid(), and GetSolidParams().
G4VPhysicalVolume * G4tgbGeometryDumper::GetTopPhysVol ()
Definition at line 108 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 108 of file G4tgbGeometryDumper.cc
References G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), and G4VPhysicalVolume::GetMotherLogical().
Referenced by DumpGeometry().
G4String G4tgbGeometryDumper::LookForExistingRotation (const G4RotationMatrix * rotm) private
Definition at line 1318 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1318 of file G4tgbGeometryDumper.cc
References G4String::first(), and theRotMats.
Referenced by DumpRotationMatrix().
G4double G4tgbGeometryDumper::MatDeterminant (G4RotationMatrix * ro) private
Definition at line 1092 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1092 of file G4tgbGeometryDumper.cc
References r, CLHEP::HepRotation::rep3x3(), CLHEP::HepRep3x3::xx_, CLHEP::HepRep3x3::xy_, CLHEP::HepRep3x3::xz_, CLHEP::HepRep3x3::yx_, CLHEP::HepRep3x3::yy_, CLHEP::HepRep3x3::yz_, CLHEP::HepRep3x3::zx_, CLHEP::HepRep3x3::zy_, and CLHEP::HepRep3x3::zz_.
Referenced by DumpRotationMatrix().
G4bool G4tgbGeometryDumper::Same2G4Isotopes (G4Isotope * ele1, G4Isotope * ele2) private
Definition at line 1337 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1337 of file G4tgbGeometryDumper.cc
References G4Isotope::GetA(), G4Isotope::GetN(), and G4Isotope::GetZ().
Referenced by GetIsotopeName().
G4String G4tgbGeometryDumper::SubstituteRefl (G4String name) private
Definition at line 1148 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1148 of file G4tgbGeometryDumper.cc
Referenced by DumpLogVol(), DumpPVPlacement(), and DumpPVReplica().
G4String G4tgbGeometryDumper::SupressRefl (G4String name) private
Definition at line 1137 of file G4tgbGeometryDumper.cc.
View newest version in sPHENIX GitHub at line 1137 of file G4tgbGeometryDumper.cc
Referenced by DumpLogVol().
Member Data Documentation
std::map<G4String,G4Element*> G4tgbGeometryDumper::theElements private
Definition at line 114 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 114 of file G4tgbGeometryDumper.hh
Referenced by DumpElement(), and DumpMaterial().
std::ofstream* G4tgbGeometryDumper::theFile private
Definition at line 111 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 111 of file G4tgbGeometryDumper.hh
Referenced by DumpGeometry().
G4ThreadLocal G4tgbGeometryDumper * G4tgbGeometryDumper::theInstance = 0 static private
Definition at line 109 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 109 of file G4tgbGeometryDumper.hh
Referenced by GetInstance().
std::map<G4String,G4Isotope*> G4tgbGeometryDumper::theIsotopes private
Definition at line 115 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 115 of file G4tgbGeometryDumper.hh
Referenced by DumpElement(), DumpIsotope(), and GetIsotopeName().
std::map<G4String,G4LogicalVolume*> G4tgbGeometryDumper::theLogVols private
Definition at line 117 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 117 of file G4tgbGeometryDumper.hh
Referenced by CheckIfLogVolExists(), and DumpLogVol().
std::map<G4String,G4Material*> G4tgbGeometryDumper::theMaterials private
Definition at line 113 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 113 of file G4tgbGeometryDumper.hh
Referenced by DumpMaterial().
std::map<G4String,G4VPhysicalVolume*> G4tgbGeometryDumper::thePhysVols private
Definition at line 118 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 118 of file G4tgbGeometryDumper.hh
Referenced by CheckIfPhysVolExists(), DumpPVPlacement(), and DumpPVReplica().
G4int G4tgbGeometryDumper::theRotationNumber private
Definition at line 121 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 121 of file G4tgbGeometryDumper.hh
Referenced by DumpRotationMatrix().
std::map<G4String,G4RotationMatrix*> G4tgbGeometryDumper::theRotMats private
Definition at line 119 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 119 of file G4tgbGeometryDumper.hh
Referenced by DumpRotationMatrix(), and LookForExistingRotation().
std::map<G4String,G4VSolid*> G4tgbGeometryDumper::theSolids private
Definition at line 116 of file G4tgbGeometryDumper.hh.
View newest version in sPHENIX GitHub at line 116 of file G4tgbGeometryDumper.hh
Referenced by DumpBooleanVolume(), DumpSolid(), and FindSolidName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbGeometryDumper.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbGeometryDumper.cc