ECCE @ EIC Software: G4GenericIon Class Reference
G4GenericIon Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4GenericIon.hh>
Static Public Member Functions
static G4GenericIon * Definition ()
static G4GenericIon * GenericIonDefinition ()
static G4GenericIon * GenericIon ()
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4GenericIon ()
~G4GenericIon ()
Static Private Attributes
static G4GenericIon * theInstance = 0
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 56 of file G4GenericIon.hh.
View newest version in sPHENIX GitHub at line 56 of file G4GenericIon.hh
Constructor & Destructor Documentation
G4GenericIon::G4GenericIon () inline private
Definition at line 60 of file G4GenericIon.hh.
View newest version in sPHENIX GitHub at line 60 of file G4GenericIon.hh
G4GenericIon::~G4GenericIon () inline private
Definition at line 61 of file G4GenericIon.hh.
View newest version in sPHENIX GitHub at line 61 of file G4GenericIon.hh
Member Function Documentation
G4GenericIon * G4GenericIon::Definition () static
!!! !!! this particle should not be used for tracking !!! all properties except name and type are meaningless !!!
Definition at line 48 of file G4GenericIon.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GenericIon.cc
References eplus, G4ParticleTable::FindParticle(), G4Ions::G4Ions(), G4ParticleTable::GetParticleTable(), GeV, MeV, G4ParticleTable::SetGenericIon(), and theInstance.
Referenced by G4IonParametrisedLossModel::G4IonParametrisedLossModel(), GenericIon(), GenericIonDefinition(), and G4HadronicProcessStore::Print().
G4GenericIon * G4GenericIon::GenericIon () static
Definition at line 92 of file G4GenericIon.cc.
View newest version in sPHENIX GitHub at line 92 of file G4GenericIon.cc
References Definition().
Referenced by G4EmModelActivator::ActivateMicroElec(), G4EmModelActivator::ActivatePAI(), G4IonPhysicsXS::AddProcess(), PhysicsList::AddRadioactiveDecay(), G4INCLXXInterface::ApplyYourself(), G4EmCorrections::BuildCorrectionVector(), G4RadioactiveDecayBase::BuildPhysicsTable(), G4RadioactiveDecay::BuildPhysicsTable(), DMXPhysicsList::ConstructGeneral(), BiasedRDPhysics::ConstructParticle(), G4RadioactiveDecayPhysics::ConstructParticle(), G4IonElasticPhysics::ConstructParticle(), IonPhysics::ConstructProcess(), BiasedRDPhysics::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4IonPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4HadronicProcessStore::DumpHtml(), G4AdjointIonIonisationModel::G4AdjointIonIonisationModel(), G4EmCalculator::G4EmCalculator(), G4VMultipleScattering::G4VMultipleScattering(), PhysicsList::GetProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4VEmProcess::PreparePhysicsTable(), G4ionIonisation::StreamProcessInfo(), and G4INCLXXInterface::toINCLParticleType().
G4GenericIon * G4GenericIon::GenericIonDefinition () static
Definition at line 87 of file G4GenericIon.cc.
View newest version in sPHENIX GitHub at line 87 of file G4GenericIon.cc
References Definition().
Referenced by PhysicsList::ConstructBarions(), G4IonConstructor::ConstructLightIons(), GammaKnifeParticles::ConstructParticle(), G4EmDNAPhysics_option3::ConstructParticle(), G4EmDNAPhysics_stationary::ConstructParticle(), G4EmDNAPhysics_stationary_option2::ConstructParticle(), G4EmDNAPhysics_stationary_option4::ConstructParticle(), G4EmDNAPhysics_stationary_option6::ConstructParticle(), G4EmDNAPhysics::ConstructParticle(), G4EmDNAPhysics_option1::ConstructParticle(), G4EmLivermorePhysics::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmDNAPhysics_option2::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmDNAPhysics_option4::ConstructParticle(), G4EmDNAPhysics_option5::ConstructParticle(), G4EmDNAPhysics_option8::ConstructParticle(), G4EmDNAPhysics_option7::ConstructParticle(), ExUCNPhysicsList::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructParticle(), F06PhysicsList::ConstructParticle(), PhysicsList::ConstructParticle(), G4EmLEPTSPhysics::ConstructParticle(), G4EmDNAPhysics_option6::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), G4SpinDecayPhysics::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), F04PhysicsList::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), G4DNAIonisation::IsApplicable(), and G4MicroElecInelastic::IsApplicable().
Member Data Documentation
G4GenericIon * G4GenericIon::theInstance = 0 static private
Definition at line 59 of file G4GenericIon.hh.
View newest version in sPHENIX GitHub at line 59 of file G4GenericIon.hh
Referenced by Definition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4GenericIon.hh
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/src/G4GenericIon.cc