ECCE @ EIC Software: G4VExternalNavigation Class Reference
G4VExternalNavigation Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4VExternalNavigation.hh>
Public Member Functions
G4VExternalNavigation ()
virtual ~G4VExternalNavigation ()
virtual G4bool LevelLocate (G4NavigationHistory &history, const G4VPhysicalVolume *blockedVol, const G4int blockedNum, const G4ThreeVector &globalPoint, const G4ThreeVector *globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector &localPoint)=0
virtual G4double ComputeStep (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume **pBlockedPhysical, G4int &blockedReplicaNo)=0
virtual G4double ComputeSafety (const G4ThreeVector &globalpoint, const G4NavigationHistory &history, const G4double pMaxLength=DBL_MAX)=0
virtual G4VExternalNavigation * Clone ()=0
virtual EInside Inside (const G4VSolid *solid, const G4ThreeVector &position, const G4ThreeVector &direction)
virtual void RelocateWithinVolume (G4VPhysicalVolume *motherPhysical, const G4ThreeVector &localPoint)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void CheckMode (G4bool mode)
Protected Attributes
G4bool fCheck = false
G4int fVerbose = 0
Detailed Description
Definition at line 44 of file G4VExternalNavigation.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VExternalNavigation.hh
Constructor & Destructor Documentation
G4VExternalNavigation::G4VExternalNavigation ()
Definition at line 37 of file G4VExternalNavigation.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VExternalNavigation.cc
G4VExternalNavigation::~G4VExternalNavigation () virtual
Definition at line 45 of file G4VExternalNavigation.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VExternalNavigation.cc
Member Function Documentation
void G4VExternalNavigation::CheckMode (G4bool mode) inline
Definition at line 113 of file G4VExternalNavigation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VExternalNavigation.hh
References fCheck.
virtual G4VExternalNavigation* G4VExternalNavigation::Clone () pure virtual
virtual G4double G4VExternalNavigation::ComputeSafety (const G4ThreeVector & globalpoint, const G4NavigationHistory & history, const G4double pMaxLength = DBL_MAX) pure virtual
Referenced by G4Navigator::ComputeSafety().
virtual G4double G4VExternalNavigation::ComputeStep (const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo) pure virtual
Referenced by G4Navigator::ComputeStep().
G4int G4VExternalNavigation::GetVerboseLevel () const inline
Definition at line 109 of file G4VExternalNavigation.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VExternalNavigation.hh
References fVerbose.
EInside G4VExternalNavigation::Inside (const G4VSolid * solid, const G4ThreeVector & position, const G4ThreeVector & direction) virtual
Definition at line 53 of file G4VExternalNavigation.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VExternalNavigation.cc
References G4VSolid::Inside().
Referenced by G4Navigator::LocateGlobalPointAndSetup().
virtual G4bool G4VExternalNavigation::LevelLocate (G4NavigationHistory & history, const G4VPhysicalVolume * blockedVol, const G4int blockedNum, const G4ThreeVector & globalPoint, const G4ThreeVector * globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector & localPoint) pure virtual
Referenced by G4Navigator::LocateGlobalPointAndSetup().
void G4VExternalNavigation::RelocateWithinVolume (G4VPhysicalVolume * motherPhysical, const G4ThreeVector & localPoint) virtual
Definition at line 64 of file G4VExternalNavigation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VExternalNavigation.cc
Referenced by G4Navigator::LocateGlobalPointWithinVolume().
void G4VExternalNavigation::SetVerboseLevel (G4int level) inline
Definition at line 110 of file G4VExternalNavigation.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VExternalNavigation.hh
References fVerbose.
Member Data Documentation
G4bool G4VExternalNavigation::fCheck = false protected
Definition at line 120 of file G4VExternalNavigation.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VExternalNavigation.hh
Referenced by CheckMode().
G4int G4VExternalNavigation::fVerbose = 0 protected
Definition at line 121 of file G4VExternalNavigation.hh.
View newest version in sPHENIX GitHub at line 121 of file G4VExternalNavigation.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4VExternalNavigation.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4VExternalNavigation.cc