ECCE @ EIC Software: G4BremsstrahlungCrossSectionHandler Class Reference
G4BremsstrahlungCrossSectionHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4BremsstrahlungCrossSectionHandler.hh>
Public Member Functions
G4BremsstrahlungCrossSectionHandler (const G4VEnergySpectrum *spectrum, G4VDataSetAlgorithm *interpolation)
~G4BremsstrahlungCrossSectionHandler ()
G4double GetCrossSectionAboveThresholdForElement (G4double energy, G4double cutEnergy, G4int Z)
Public Member Functions inherited from G4VCrossSectionHandler
G4VCrossSectionHandler ()
G4VCrossSectionHandler (G4VDataSetAlgorithm *interpolation, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int nBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
virtual ~G4VCrossSectionHandler ()
void Initialise (G4VDataSetAlgorithm *interpolation=0, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int numberOfBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
G4int SelectRandomAtom (const G4MaterialCutsCouple *couple, G4double e) const
const G4Element * SelectRandomElement (const G4MaterialCutsCouple *material, G4double e) const
G4int SelectRandomShell (G4int Z, G4double e) const
G4VEMDataSet * BuildMeanFreePathForMaterials (const G4DataVector *energyCuts=0)
G4double FindValue (G4int Z, G4double e) const
G4double FindValue (G4int Z, G4double e, G4int shellIndex) const
G4double ValueForMaterial (const G4Material *material, G4double e) const
void LoadData (const G4String &dataFile)
void LoadNonLogData (const G4String &dataFile)
void LoadShellData (const G4String &dataFile)
void PrintData () const
void Clear ()
Protected Member Functions
std::vector< G4VEMDataSet * > * BuildCrossSectionsForMaterials (const G4DataVector &energyVector, const G4DataVector *energyCuts)
Protected Member Functions inherited from G4VCrossSectionHandler
G4int NumberOfComponents (G4int Z) const
void ActiveElements ()
virtual G4VDataSetAlgorithm * CreateInterpolation ()
const G4VDataSetAlgorithm * GetInterpolation () const
Private Member Functions
G4BremsstrahlungCrossSectionHandler & operator= (const G4BremsstrahlungCrossSectionHandler &right)
G4BremsstrahlungCrossSectionHandler (const G4BremsstrahlungCrossSectionHandler &)
Private Attributes
const G4VEnergySpectrum * theBR
G4VDataSetAlgorithm * interp
Detailed Description
Definition at line 62 of file G4BremsstrahlungCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BremsstrahlungCrossSectionHandler.hh
Constructor & Destructor Documentation
G4BremsstrahlungCrossSectionHandler::G4BremsstrahlungCrossSectionHandler (const G4VEnergySpectrum * spectrum, G4VDataSetAlgorithm * interpolation)
Definition at line 73 of file G4BremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 73 of file G4BremsstrahlungCrossSectionHandler.cc
References interp.
G4BremsstrahlungCrossSectionHandler::~G4BremsstrahlungCrossSectionHandler ()
Definition at line 82 of file G4BremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 82 of file G4BremsstrahlungCrossSectionHandler.cc
References interp.
G4BremsstrahlungCrossSectionHandler::G4BremsstrahlungCrossSectionHandler (const G4BremsstrahlungCrossSectionHandler &) private
Member Function Documentation
std::vector< G4VEMDataSet * > * G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials (const G4DataVector & energyVector, const G4DataVector * energyCuts) protected virtual
Implements G4VCrossSectionHandler.
Definition at line 90 of file G4BremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 90 of file G4BremsstrahlungCrossSectionHandler.cc
References G4VEMDataSet::AddComponent(), bin, G4VDataSetAlgorithm::Clone(), e, G4VCrossSectionHandler::FindValue(), G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4Material::GetVecNbOfAtomsPerVolume(), interp, material(), G4VEnergySpectrum::Probability(), theBR, and Z.
G4double G4BremsstrahlungCrossSectionHandler::GetCrossSectionAboveThresholdForElement (G4double energy, G4double cutEnergy, G4int Z)
Definition at line 168 of file G4BremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 168 of file G4BremsstrahlungCrossSectionHandler.cc
References G4VCrossSectionHandler::FindValue(), G4VEnergySpectrum::Probability(), and theBR.
G4BremsstrahlungCrossSectionHandler& G4BremsstrahlungCrossSectionHandler::operator= (const G4BremsstrahlungCrossSectionHandler & right) private
Member Data Documentation
G4VDataSetAlgorithm* G4BremsstrahlungCrossSectionHandler::interp private
Definition at line 89 of file G4BremsstrahlungCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BremsstrahlungCrossSectionHandler.hh
Referenced by BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler(), and ~G4BremsstrahlungCrossSectionHandler().
const G4VEnergySpectrum* G4BremsstrahlungCrossSectionHandler::theBR private
Definition at line 87 of file G4BremsstrahlungCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 87 of file G4BremsstrahlungCrossSectionHandler.hh
Referenced by BuildCrossSectionsForMaterials(), and GetCrossSectionAboveThresholdForElement().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4BremsstrahlungCrossSectionHandler.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4BremsstrahlungCrossSectionHandler.cc