ECCE @ EIC Software: G4VPreCompoundModel Class Reference
G4VPreCompoundModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VPreCompoundModel.hh>
Public Member Functions
G4VPreCompoundModel (G4ExcitationHandler *ptr=nullptr, const G4String &modelName="PrecompoundModel")
virtual ~G4VPreCompoundModel ()
virtual G4ReactionProductVector * DeExcite (G4Fragment &aFragment)=0
virtual void DeExciteModelDescription (std::ostream &outFile) const =0
void SetExcitationHandler (G4ExcitationHandler *ptr)
G4ExcitationHandler * GetExcitationHandler () const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)=0
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4VPreCompoundModel (const G4VPreCompoundModel &)=delete
const G4VPreCompoundModel & operator= (const G4VPreCompoundModel &right)=delete
G4bool operator== (const G4VPreCompoundModel &right) const =delete
G4bool operator!= (const G4VPreCompoundModel &right) const =delete
Private Attributes
G4ExcitationHandler * theExcitationHandler
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 58 of file G4VPreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VPreCompoundModel.hh
Constructor & Destructor Documentation
G4VPreCompoundModel::G4VPreCompoundModel (G4ExcitationHandler * ptr = nullptr, const G4String & modelName = "PrecompoundModel") explicit
Definition at line 40 of file G4VPreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 40 of file G4VPreCompoundModel.cc
G4VPreCompoundModel::~G4VPreCompoundModel () virtual
Definition at line 45 of file G4VPreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VPreCompoundModel.cc
G4VPreCompoundModel::G4VPreCompoundModel (const G4VPreCompoundModel &) private delete
Member Function Documentation
virtual G4ReactionProductVector* G4VPreCompoundModel::DeExcite (G4Fragment & aFragment) pure virtual
Implemented in G4PreCompoundModel, and G4AblaInterface.
Referenced by G4MuMinusCapturePrecompound::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4PreCompoundDeexcitation::deExcite(), G4BinaryCascade::DeExcite(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4GeneratorPrecompoundInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
void G4VPreCompoundModel::DeExciteModelDescription (std::ostream & outFile) const pure virtual
Implemented in G4PreCompoundModel, and G4AblaInterface.
Definition at line 48 of file G4VPreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VPreCompoundModel.cc
Referenced by G4BinaryCascade::ModelDescription(), and G4BinaryCascade::PropagateModelDescription().
G4ExcitationHandler * G4VPreCompoundModel::GetExcitationHandler () const inline
Definition at line 92 of file G4VPreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VPreCompoundModel.hh
References theExcitationHandler.
Referenced by G4BinaryCascade::G4BinaryCascade(), G4BinaryLightIonReaction::G4BinaryLightIonReaction(), G4INCLXXInterface::G4INCLXXInterface(), G4PreCompoundModel::InitialiseModel(), G4PreCompoundModel::PerformEquilibriumEmission(), G4BinaryLightIonReaction::SetPrecompound(), and G4PreCompoundModel::~G4PreCompoundModel().
G4bool G4VPreCompoundModel::operator!= (const G4VPreCompoundModel & right) const private delete
const G4VPreCompoundModel& G4VPreCompoundModel::operator= (const G4VPreCompoundModel & right) private delete
G4bool G4VPreCompoundModel::operator== (const G4VPreCompoundModel & right) const private delete
void G4VPreCompoundModel::SetExcitationHandler (G4ExcitationHandler * ptr) inline
Definition at line 87 of file G4VPreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VPreCompoundModel.hh
References theExcitationHandler.
Referenced by G4PreCompoundModel::G4PreCompoundModel(), and G4BinaryLightIonReaction::SetDeExcitation().
Member Data Documentation
G4ExcitationHandler* G4VPreCompoundModel::theExcitationHandler private
Definition at line 84 of file G4VPreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VPreCompoundModel.hh
Referenced by GetExcitationHandler(), and SetExcitationHandler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VPreCompoundModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4VPreCompoundModel.cc