ECCE @ EIC Software: G4VMarker Class Reference
G4VMarker Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VMarker.hh>
Public Types
enum FillStyle { noFill, hashed, filled }
enum SizeType { none, world, screen }
Public Member Functions
G4VMarker ()
G4VMarker (const G4VMarker &)
G4VMarker (const G4Point3D &position)
virtual ~G4VMarker ()
G4VMarker & operator= (const G4VMarker &)
G4bool operator!= (const G4VMarker &) const
G4Point3D GetPosition () const
SizeType GetSizeType () const
G4double GetWorldSize () const
G4double GetWorldDiameter () const
G4double GetWorldRadius () const
G4double GetScreenSize () const
G4double GetScreenDiameter () const
G4double GetScreenRadius () const
FillStyle GetFillStyle () const
void SetPosition (const G4Point3D &)
void SetSize (SizeType, G4double)
void SetDiameter (SizeType, G4double)
void SetRadius (SizeType, G4double)
void SetWorldSize (G4double)
void SetWorldDiameter (G4double)
void SetWorldRadius (G4double)
void SetScreenSize (G4double)
void SetScreenDiameter (G4double)
void SetScreenRadius (G4double)
void SetFillStyle (FillStyle)
virtual const G4String & GetInfo () const
virtual void SetInfo (const G4String &info)
Public Member Functions inherited from G4Visible
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Private Attributes
G4Point3D fPosition
G4double fWorldSize
G4double fScreenSize
FillStyle fFillStyle
G4String fInfo
Friends
std::ostream & operator<< (std::ostream &os, const G4VMarker &)
Additional Inherited Members
Protected Attributes inherited from G4Visible
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Detailed Description
Definition at line 90 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VMarker.hh
Member Enumeration Documentation
enum G4VMarker::FillStyle
Enumerator:
noFill
hashed
filled
Definition at line 96 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 96 of file G4VMarker.hh
enum G4VMarker::SizeType
Enumerator:
none
world
screen
Definition at line 97 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 97 of file G4VMarker.hh
Constructor & Destructor Documentation
G4VMarker::G4VMarker ()
Definition at line 34 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VMarker.cc
G4VMarker::G4VMarker (const G4VMarker & mk)
Definition at line 43 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VMarker.cc
G4VMarker::G4VMarker (const G4Point3D & position)
Definition at line 52 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 52 of file G4VMarker.cc
G4VMarker::~G4VMarker () virtual
Definition at line 62 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 62 of file G4VMarker.cc
Member Function Documentation
FillStyle G4VMarker::GetFillStyle () const
Referenced by G4HepRepSceneHandler::setMarker().
virtual const G4String& G4VMarker::GetInfo () const virtual
G4Point3D G4VMarker::GetPosition () const
Referenced by G4HepRepSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), and G4TextModel::G4TextModel().
G4double G4VMarker::GetScreenDiameter () const
G4double G4VMarker::GetScreenRadius () const
G4double G4VMarker::GetScreenSize () const
Referenced by G4TextModel::G4TextModel(), and G4VSceneHandler::GetMarkerSize().
G4VMarker::SizeType G4VMarker::GetSizeType () const
Definition at line 111 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 111 of file G4VMarker.cc
References fScreenSize, fWorldSize, none, screen, and world.
G4double G4VMarker::GetWorldDiameter () const
G4double G4VMarker::GetWorldRadius () const
Referenced by G4HepRepFileSceneHandler::AddPrimitive().
G4double G4VMarker::GetWorldSize () const
Referenced by G4VSceneHandler::GetMarkerSize().
G4bool G4VMarker::operator!= (const G4VMarker & mk) const
Definition at line 75 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 75 of file G4VMarker.cc
References fFillStyle, fInfo, fPosition, fScreenSize, and fWorldSize.
G4VMarker & G4VMarker::operator= (const G4VMarker & mk)
Definition at line 64 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VMarker.cc
References fFillStyle, fInfo, fPosition, fScreenSize, fWorldSize, and G4Visible::operator=().
Referenced by G4Text::operator=().
void G4VMarker::SetDiameter (SizeType , G4double)
void G4VMarker::SetFillStyle (FillStyle)
Referenced by ExN04MuonHit::Draw(), ExN04TrackerHit::Draw(), eRositaTrackerHit::Draw(), ExTGTrackerHit::Draw(), RE01TrackerHit::Draw(), RE05MuonHit::Draw(), RE05TrackerHit::Draw(), ExP01TrackerHit::Draw(), B2TrackerHit::Draw(), XAluminumElectrodeHit::Draw(), ExN02TrackerHit::Draw(), DMXPmtHit::Draw(), B5DriftChamberHit::Draw(), TrackerHit::Draw(), H02MuonHit::Draw(), CexmcScenePrimitives::DrawRadialLine(), CexmcEventAction::DrawTrackPoints(), LXeTrajectory::DrawTrajectory(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), G4BlineEventAction::EndOfEventAction(), and CexmcScenePrimitives::MarkTargetCenter().
virtual void G4VMarker::SetInfo (const G4String & info) virtual
void G4VMarker::SetPosition (const G4Point3D &)
Referenced by G4VSceneHandler::AddPrimitive(), G4GPSModel::DescribeYourselfTo(), and CexmcEventAction::DrawTrackPoints().
void G4VMarker::SetRadius (SizeType , G4double)
void G4VMarker::SetScreenDiameter (G4double)
Referenced by G4GPSModel::DescribeYourselfTo().
void G4VMarker::SetScreenRadius (G4double)
void G4VMarker::SetScreenSize (G4double)
Referenced by G4VSceneHandler::AddPrimitive(), UVA_VisAction::Draw(), ExN04MuonHit::Draw(), ExN04TrackerHit::Draw(), ExTGTrackerHit::Draw(), RE01TrackerHit::Draw(), eRositaTrackerHit::Draw(), RE05MuonHit::Draw(), RE05TrackerHit::Draw(), ExP01TrackerHit::Draw(), B2TrackerHit::Draw(), XAluminumElectrodeHit::Draw(), ExN02TrackerHit::Draw(), B5DriftChamberHit::Draw(), DMXPmtHit::Draw(), TrackerHit::Draw(), H02MuonHit::Draw(), G4ScoreLogColorMap::DrawColorChartText(), G4VScoreColorMap::DrawColorChartText(), CexmcScenePrimitives::DrawRadialLine(), CexmcEventAction::DrawReconstructionData(), CexmcEventAction::DrawTrackPoints(), LXeTrajectory::DrawTrajectory(), G4BlineEventAction::EndOfEventAction(), G4AxesModel::G4AxesModel(), G4ViewParameters::G4ViewParameters(), CexmcScenePrimitives::MarkTargetCenter(), G4VisCommandSceneAddDate::Date::operator()(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VisCommandSceneAddLogo2D::Logo2D::operator()(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
void G4VMarker::SetSize (SizeType sizeType, G4double size)
Definition at line 118 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 118 of file G4VMarker.cc
References fScreenSize, fWorldSize, screen, and world.
Referenced by G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), and G4VSceneHandler::RequestPrimitives().
void G4VMarker::SetWorldDiameter (G4double)
void G4VMarker::SetWorldRadius (G4double)
void G4VMarker::SetWorldSize (G4double)
Referenced by G4VSceneHandler::AddPrimitive().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4VMarker & marker) friend
Definition at line 88 of file G4VMarker.cc.
View newest version in sPHENIX GitHub at line 88 of file G4VMarker.cc
Member Data Documentation
FillStyle G4VMarker::fFillStyle private
Definition at line 151 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 151 of file G4VMarker.hh
Referenced by operator!=(), operator<<(), and operator=().
G4String G4VMarker::fInfo private
Definition at line 154 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 154 of file G4VMarker.hh
Referenced by operator!=(), operator<<(), and operator=().
G4Point3D G4VMarker::fPosition private
Definition at line 148 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 148 of file G4VMarker.hh
Referenced by operator!=(), operator<<(), and operator=().
G4double G4VMarker::fScreenSize private
Definition at line 150 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 150 of file G4VMarker.hh
Referenced by GetSizeType(), operator!=(), operator<<(), operator=(), and SetSize().
G4double G4VMarker::fWorldSize private
Definition at line 149 of file G4VMarker.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VMarker.hh
Referenced by GetSizeType(), operator!=(), operator<<(), operator=(), and SetSize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VMarker.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4VMarker.cc