ECCE @ EIC Software: CLHEP::HepBoostX Class Reference
CLHEP::HepBoostX Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/BoostX.h>
Public Member Functions
HepBoostX ()
HepBoostX (const HepBoostX &b)
HepBoostX (HepBoostX &&b)=default
HepBoostX & operator= (const HepBoostX &m)
HepBoostX & operator= (HepBoostX &&m)=default
HepBoostX & set (double beta)
HepBoostX (double beta)
double beta () const
double gamma () const
Hep3Vector boostVector () const
Hep3Vector getDirection () const
double xx () const
double xy () const
double xz () const
double xt () const
double yx () const
double yy () const
double yz () const
double yt () const
double zx () const
double zy () const
double zz () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
HepRep4x4 rep4x4 () const
HepRep4x4Symmetric rep4x4Symmetric () const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
int compare (const HepBoostX &b) const
bool operator== (const HepBoostX &b) const
bool operator!= (const HepBoostX &b) const
bool operator<= (const HepBoostX &b) const
bool operator>= (const HepBoostX &b) const
bool operator< (const HepBoostX &b) const
bool operator> (const HepBoostX &b) const
bool isIdentity () const
double distance2 (const HepBoostX &b) const
double distance2 (const HepBoost &b) const
double distance2 (const HepRotation &r) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoostX &b) const
double howNear (const HepBoost &b) const
double howNear (const HepRotation &r) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoostX &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepBoost &b, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepBoostX operator* (const HepBoostX &b) const
HepLorentzRotation operator* (const HepBoost &b) const
HepLorentzRotation operator* (const HepRotation &r) const
HepLorentzRotation operator* (const HepLorentzRotation &lt) const
HepBoostX inverse () const
HepBoostX & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepLorentzVector vectorMultiplication (const HepLorentzVector &w) const
HepLorentzRotation matrixMultiplication (const HepRep4x4 &m) const
HepLorentzRotation matrixMultiplication (const HepRep4x4Symmetric &m) const
HepBoostX (double beta, double gamma)
Protected Attributes
double beta_
double gamma_
Friends
HepBoostX inverseOf (const HepBoostX &b)
Detailed Description
Author
Definition at line 41 of file BoostX.h.
View newest version in sPHENIX GitHub at line 41 of file BoostX.h
Constructor & Destructor Documentation
CLHEP::HepBoostX::HepBoostX () inline
Referenced by operator*().
CLHEP::HepBoostX::HepBoostX (const HepBoostX & b) inline
CLHEP::HepBoostX::HepBoostX (HepBoostX && b) inline default
CLHEP::HepBoostX::HepBoostX (double beta) inline
CLHEP::HepBoostX::HepBoostX (double beta, double gamma) inline protected
Member Function Documentation
double CLHEP::HepBoostX::beta () const inline
Referenced by operator*().
Hep3Vector CLHEP::HepBoostX::boostVector () const inline
Referenced by decompose().
HepLorentzVector CLHEP::HepBoostX::col1 () const inline
HepLorentzVector CLHEP::HepBoostX::col2 () const inline
HepLorentzVector CLHEP::HepBoostX::col3 () const inline
HepLorentzVector CLHEP::HepBoostX::col4 () const inline
int CLHEP::HepBoostX::compare (const HepBoostX & b) const inline
void CLHEP::HepBoostX::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 57 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 57 of file BoostX.cc
References boostVector().
void CLHEP::HepBoostX::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 64 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 64 of file BoostX.cc
References boostVector().
void CLHEP::HepBoostX::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 69 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 69 of file BoostX.cc
References boostVector().
void CLHEP::HepBoostX::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 76 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 76 of file BoostX.cc
References boostVector().
double CLHEP::HepBoostX::distance2 (const HepBoostX & b) const inline
Referenced by distance2(), and isNear().
double CLHEP::HepBoostX::distance2 (const HepBoost & b) const
Definition at line 83 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 83 of file BoostX.cc
References CLHEP::HepBoost::distance2().
double CLHEP::HepBoostX::distance2 (const HepRotation & r) const
Definition at line 87 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 87 of file BoostX.cc
References norm2(), and CLHEP::HepRotation::norm2().
double CLHEP::HepBoostX::distance2 (const HepLorentzRotation & lt) const
Definition at line 93 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 93 of file BoostX.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
double CLHEP::HepBoostX::gamma () const inline
Hep3Vector CLHEP::HepBoostX::getDirection () const inline
static double CLHEP::HepBoostX::getTolerance () inline static
double CLHEP::HepBoostX::howNear (const HepBoostX & b) const inline
double CLHEP::HepBoostX::howNear (const HepBoost & b) const inline
double CLHEP::HepBoostX::howNear (const HepRotation & r) const inline
double CLHEP::HepBoostX::howNear (const HepLorentzRotation & lt) const inline
HepBoostX CLHEP::HepBoostX::inverse () const inline
HepBoostX& CLHEP::HepBoostX::invert () inline
bool CLHEP::HepBoostX::isIdentity () const inline
bool CLHEP::HepBoostX::isNear (const HepBoostX & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoostX::isNear (const HepBoost & b, double epsilon = Hep4RotationInterface::tolerance) const inline
bool CLHEP::HepBoostX::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 102 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 102 of file BoostX.cc
References norm2(), and CLHEP::HepRotation::norm2().
bool CLHEP::HepBoostX::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 109 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 109 of file BoostX.cc
References CLHEP::HepLorentzRotation::decompose(), distance2(), CLHEP::HepRotation::norm2(), and r1.
HepLorentzRotation CLHEP::HepBoostX::matrixMultiplication (const HepRep4x4 & m) const protected
HepLorentzRotation CLHEP::HepBoostX::matrixMultiplication (const HepRep4x4Symmetric & m) const protected
double CLHEP::HepBoostX::norm2 () const inline
Referenced by distance2(), and isNear().
bool CLHEP::HepBoostX::operator!= (const HepBoostX & b) const inline
HepLorentzVector CLHEP::HepBoostX::operator() (const HepLorentzVector & w) const inline
HepLorentzVector CLHEP::HepBoostX::operator* (const HepLorentzVector & w) const inline
HepBoostX CLHEP::HepBoostX::operator* (const HepBoostX & b) const
Definition at line 139 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 139 of file BoostX.cc
References beta(), and HepBoostX().
HepLorentzRotation CLHEP::HepBoostX::operator* (const HepBoost & b) const
Definition at line 142 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 142 of file BoostX.cc
References b.
HepLorentzRotation CLHEP::HepBoostX::operator* (const HepRotation & r) const
Definition at line 146 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 146 of file BoostX.cc
References r.
HepLorentzRotation CLHEP::HepBoostX::operator* (const HepLorentzRotation & lt) const
Definition at line 150 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 150 of file BoostX.cc
bool CLHEP::HepBoostX::operator< (const HepBoostX & b) const inline
bool CLHEP::HepBoostX::operator<= (const HepBoostX & b) const inline
HepBoostX& CLHEP::HepBoostX::operator= (const HepBoostX & m) inline
HepBoostX& CLHEP::HepBoostX::operator= (HepBoostX && m) inline default
bool CLHEP::HepBoostX::operator== (const HepBoostX & b) const inline
bool CLHEP::HepBoostX::operator> (const HepBoostX & b) const inline
bool CLHEP::HepBoostX::operator>= (const HepBoostX & b) const inline
std::ostream & CLHEP::HepBoostX::print (std::ostream & os) const
Definition at line 157 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 157 of file BoostX.cc
References beta_, and gamma_.
void CLHEP::HepBoostX::rectify ()
Definition at line 122 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 122 of file BoostX.cc
References beta_, and gamma_.
HepRep4x4 CLHEP::HepBoostX::rep4x4 () const
Definition at line 39 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 39 of file BoostX.cc
References beta_, and gamma_.
HepRep4x4Symmetric CLHEP::HepBoostX::rep4x4Symmetric () const
Definition at line 47 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 47 of file BoostX.cc
References beta_, and gamma_.
HepLorentzVector CLHEP::HepBoostX::row1 () const inline
HepLorentzVector CLHEP::HepBoostX::row2 () const inline
HepLorentzVector CLHEP::HepBoostX::row3 () const inline
HepLorentzVector CLHEP::HepBoostX::row4 () const inline
HepBoostX & CLHEP::HepBoostX::set (double beta)
Definition at line 23 of file BoostX.cc.
View newest version in sPHENIX GitHub at line 23 of file BoostX.cc
References beta_, and gamma_.
static double CLHEP::HepBoostX::setTolerance (double tol) inline static
double CLHEP::HepBoostX::tt () const inline
double CLHEP::HepBoostX::tx () const inline
double CLHEP::HepBoostX::ty () const inline
double CLHEP::HepBoostX::tz () const inline
HepLorentzVector CLHEP::HepBoostX::vectorMultiplication (const HepLorentzVector & w) const inline protected
double CLHEP::HepBoostX::xt () const inline
double CLHEP::HepBoostX::xx () const inline
double CLHEP::HepBoostX::xy () const inline
double CLHEP::HepBoostX::xz () const inline
double CLHEP::HepBoostX::yt () const inline
double CLHEP::HepBoostX::yx () const inline
double CLHEP::HepBoostX::yy () const inline
double CLHEP::HepBoostX::yz () const inline
double CLHEP::HepBoostX::zt () const inline
double CLHEP::HepBoostX::zx () const inline
double CLHEP::HepBoostX::zy () const inline
double CLHEP::HepBoostX::zz () const inline
Friends And Related Function Documentation
HepBoostX inverseOf (const HepBoostX & b) friend
Member Data Documentation
double CLHEP::HepBoostX::beta_ protected
Definition at line 210 of file BoostX.h.
View newest version in sPHENIX GitHub at line 210 of file BoostX.h
Referenced by print(), rectify(), rep4x4(), rep4x4Symmetric(), and set().
double CLHEP::HepBoostX::gamma_ protected
Definition at line 211 of file BoostX.h.
View newest version in sPHENIX GitHub at line 211 of file BoostX.h
Referenced by print(), rectify(), rep4x4(), rep4x4Symmetric(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/BoostX.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/BoostX.cc