ECCE @ EIC Software: PrimaryKiller Class Reference
PrimaryKiller Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/PrimaryKiller.hh>
Public Member Functions
PrimaryKiller (G4String name, G4int depth=0)
virtual ~PrimaryKiller ()
void SetEnergyThreshold (double energy)
void SetMinLossEnergyLimit (double energy)
void SetMaxLossEnergyLimit (double energy)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
PrimaryKiller (G4String name, G4int depth=0)
virtual ~PrimaryKiller ()
void SetEnergyThreshold (double energy)
void SetMinLossEnergyLimit (double energy)
void SetMaxLossEnergyLimit (double energy)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Private Attributes
double fELoss
double fELossRange_Min
double fELossRange_Max
double fKineticE_Min
G4UIcmdWithADoubleAndUnit * fpELossUI
G4UIcmdWithADoubleAndUnit * fpAbortEventIfELossUpperThan
G4UIcmdWithADoubleAndUnit * fpMinKineticE
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Kill the primary particle:
either after a given energy loss
or after the primary particle has reached a given energy
Definition at line 51 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 51 of file PrimaryKiller.hh
Constructor & Destructor Documentation
PrimaryKiller::PrimaryKiller (G4String name, G4int depth = 0)
Definition at line 55 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 55 of file PrimaryKiller.cc
References DBL_MAX, fELoss, fELossRange_Max, fELossRange_Min, fKineticE_Min, fpAbortEventIfELossUpperThan, fpELossUI, and fpMinKineticE.
PrimaryKiller::~PrimaryKiller () virtual
Definition at line 74 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 74 of file PrimaryKiller.cc
PrimaryKiller::PrimaryKiller (G4String name, G4int depth = 0)
virtual PrimaryKiller::~PrimaryKiller () virtual
Member Function Documentation
void PrimaryKiller::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 157 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 157 of file PrimaryKiller.cc
References fELoss.
Referenced by Initialize().
virtual void PrimaryKiller::clear () virtual
Reimplemented from G4VPrimitiveScorer.
void PrimaryKiller::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 164 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 164 of file PrimaryKiller.cc
virtual void PrimaryKiller::DrawAll () virtual
Reimplemented from G4VPrimitiveScorer.
virtual void PrimaryKiller::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
void PrimaryKiller::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 151 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 151 of file PrimaryKiller.cc
virtual void PrimaryKiller::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
void PrimaryKiller::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 144 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 144 of file PrimaryKiller.cc
References clear().
void PrimaryKiller::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 169 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 169 of file PrimaryKiller.cc
virtual void PrimaryKiller::PrintAll () virtual
Reimplemented from G4VPrimitiveScorer.
virtual G4bool PrimaryKiller::ProcessHits (G4Step * , G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
G4bool PrimaryKiller::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 93 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 93 of file PrimaryKiller.cc
References G4RunManager::AbortEvent(), FALSE, fELoss, fELossRange_Max, fELossRange_Min, fKineticE_Min, fStopAndKill, G4BestUnit, G4cout, G4endl, G4EventManager::GetConstCurrentEvent(), G4Event::GetEventID(), G4EventManager::GetEventManager(), G4StepPoint::GetKineticEnergy(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4RunManager::GetRunManager(), G4Step::GetTrack(), G4Track::GetTrackID(), track, and TRUE.
void PrimaryKiller::SetEnergyThreshold (double energy) inline
Set energy under which the particle should be killed
Definition at line 72 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 72 of file PrimaryKiller.hh
References energy, and fKineticE_Min.
void PrimaryKiller::SetEnergyThreshold (double energy) inline
Set energy under which the particle should be killed
Definition at line 72 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 72 of file PrimaryKiller.hh
References energy, and fKineticE_Min.
void PrimaryKiller::SetMaxLossEnergyLimit (double energy) inline
Set the energy loss from which the event is aborted
Definition at line 84 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 84 of file PrimaryKiller.hh
References energy, and fELossRange_Max.
void PrimaryKiller::SetMaxLossEnergyLimit (double energy) inline
Set the energy loss from which the event is aborted
Definition at line 84 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 84 of file PrimaryKiller.hh
References energy, and fELossRange_Max.
void PrimaryKiller::SetMinLossEnergyLimit (double energy) inline
Set the energy loss from which the primary is killed
Definition at line 78 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 78 of file PrimaryKiller.hh
References energy, and fELossRange_Min.
void PrimaryKiller::SetMinLossEnergyLimit (double energy) inline
Set the energy loss from which the primary is killed
Definition at line 78 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 78 of file PrimaryKiller.hh
References energy, and fELossRange_Min.
virtual void PrimaryKiller::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Method related to G4UImessenger used to control energy cuts through macro file
Reimplemented from G4UImessenger.
void PrimaryKiller::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Method related to G4UImessenger used to control energy cuts through macro file
Reimplemented from G4UImessenger.
Definition at line 79 of file PrimaryKiller.cc.
View newest version in sPHENIX GitHub at line 79 of file PrimaryKiller.cc
References fELossRange_Max, fELossRange_Min, fpAbortEventIfELossUpperThan, fpELossUI, and G4UIcmdWithADoubleAndUnit::GetNewDoubleValue().
Member Data Documentation
double PrimaryKiller::fELoss private
Definition at line 55 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryKiller.hh
Referenced by clear(), PrimaryKiller(), and ProcessHits().
double PrimaryKiller::fELossRange_Max private
Definition at line 58 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 58 of file PrimaryKiller.hh
Referenced by PrimaryKiller(), ProcessHits(), SetMaxLossEnergyLimit(), and SetNewValue().
double PrimaryKiller::fELossRange_Min private
Definition at line 57 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryKiller.hh
Referenced by PrimaryKiller(), ProcessHits(), SetMinLossEnergyLimit(), and SetNewValue().
double PrimaryKiller::fKineticE_Min private
Definition at line 59 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryKiller.hh
Referenced by PrimaryKiller(), ProcessHits(), and SetEnergyThreshold().
G4UIcmdWithADoubleAndUnit * PrimaryKiller::fpAbortEventIfELossUpperThan private
Definition at line 62 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 62 of file PrimaryKiller.hh
Referenced by PrimaryKiller(), and SetNewValue().
G4UIcmdWithADoubleAndUnit * PrimaryKiller::fpELossUI private
Definition at line 61 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 61 of file PrimaryKiller.hh
Referenced by PrimaryKiller(), and SetNewValue().
G4UIcmdWithADoubleAndUnit * PrimaryKiller::fpMinKineticE private
Definition at line 63 of file PrimaryKiller.hh.
View newest version in sPHENIX GitHub at line 63 of file PrimaryKiller.hh
Referenced by PrimaryKiller().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/PrimaryKiller.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/PrimaryKiller.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/PrimaryKiller.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/PrimaryKiller.cc