ECCE @ EIC Software: RE05TrackerHit Class Reference
RE05TrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05TrackerHit.hh>
Public Member Functions
RE05TrackerHit ()
virtual ~RE05TrackerHit ()
RE05TrackerHit (const RE05TrackerHit &right)
const RE05TrackerHit & operator= (const RE05TrackerHit &right)
G4bool operator== (const RE05TrackerHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
virtual void Draw ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
virtual void Print ()
void SetEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos ()
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
Private Attributes
G4double fEdep
G4ThreeVector fPos
Static Private Attributes
static std::map< G4String,
G4AttDef > fAttDefs
Detailed Description
Definition at line 42 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 42 of file RE05TrackerHit.hh
Constructor & Destructor Documentation
RE05TrackerHit::RE05TrackerHit ()
Definition at line 46 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 46 of file RE05TrackerHit.cc
RE05TrackerHit::~RE05TrackerHit () virtual
Definition at line 53 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 53 of file RE05TrackerHit.cc
RE05TrackerHit::RE05TrackerHit (const RE05TrackerHit & right)
Definition at line 58 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 58 of file RE05TrackerHit.cc
References fEdep, and fPos.
Member Function Documentation
std::vector< G4AttValue > * RE05TrackerHit::CreateAttValues () const virtual
Reimplemented from G4VHit.
Definition at line 112 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 112 of file RE05TrackerHit.cc
void RE05TrackerHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 83 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 83 of file RE05TrackerHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, fPos, G4VVisManager::GetConcreteInstance(), G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
const std::map< G4String, G4AttDef > * RE05TrackerHit::GetAttDefs () const virtual
Reimplemented from G4VHit.
Definition at line 100 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 100 of file RE05TrackerHit.cc
References fAttDefs.
G4double RE05TrackerHit::GetEdep () inline
Definition at line 68 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 68 of file RE05TrackerHit.hh
References fEdep.
G4ThreeVector RE05TrackerHit::GetPos () inline
Definition at line 72 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 72 of file RE05TrackerHit.hh
References fPos.
void RE05TrackerHit::operator delete (void * aHit) inline
Definition at line 86 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 86 of file RE05TrackerHit.hh
References RE05TrackerHitAllocator.
void * RE05TrackerHit::operator new (size_t) inline
Definition at line 80 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 80 of file RE05TrackerHit.hh
References RE05TrackerHitAllocator.
const RE05TrackerHit & RE05TrackerHit::operator= (const RE05TrackerHit & right)
Definition at line 67 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 67 of file RE05TrackerHit.cc
References fEdep, and fPos.
G4bool RE05TrackerHit::operator== (const RE05TrackerHit & right) const
Definition at line 76 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 76 of file RE05TrackerHit.cc
void RE05TrackerHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 124 of file RE05TrackerHit.cc.
View newest version in sPHENIX GitHub at line 124 of file RE05TrackerHit.cc
void RE05TrackerHit::SetEdep (G4double de) inline
Definition at line 66 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 66 of file RE05TrackerHit.hh
References fEdep.
Referenced by RE05TrackerSD::ProcessHits().
void RE05TrackerHit::SetPos (G4ThreeVector xyz) inline
Definition at line 70 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 70 of file RE05TrackerHit.hh
References fPos.
Referenced by RE05TrackerSD::ProcessHits().
Member Data Documentation
std::map< G4String, G4AttDef > RE05TrackerHit::fAttDefs static private
Definition at line 63 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 63 of file RE05TrackerHit.hh
Referenced by GetAttDefs().
G4double RE05TrackerHit::fEdep private
Definition at line 61 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 61 of file RE05TrackerHit.hh
Referenced by GetEdep(), operator=(), RE05TrackerHit(), and SetEdep().
G4ThreeVector RE05TrackerHit::fPos private
Definition at line 62 of file RE05TrackerHit.hh.
View newest version in sPHENIX GitHub at line 62 of file RE05TrackerHit.hh
Referenced by Draw(), GetPos(), operator=(), RE05TrackerHit(), and SetPos().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05TrackerHit.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/src/RE05TrackerHit.cc