ECCE @ EIC Software: G4ParticleChangeForGamma Class Reference
G4ParticleChangeForGamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForGamma.hh>
Public Member Functions
G4ParticleChangeForGamma ()
virtual ~G4ParticleChangeForGamma ()
G4Step * UpdateStepForAtRest (G4Step *pStep)
G4Step * UpdateStepForPostStep (G4Step *Step)
void InitializeForPostStep (const G4Track &)
void AddSecondary (G4DynamicParticle *aParticle)
G4double GetProposedKineticEnergy () const
void SetProposedKineticEnergy (G4double proposedKinEnergy)
const G4ThreeVector & GetProposedMomentumDirection () const
void ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
void ProposeMomentumDirection (const G4ThreeVector &Pfinal)
const G4ThreeVector & GetProposedPolarization () const
void ProposePolarization (const G4ThreeVector &dir)
void ProposePolarization (G4double Px, G4double Py, G4double Pz)
const G4Track * GetCurrentTrack () const
virtual void DumpInfo () const
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
virtual void Initialize (const G4Track &)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChangeForGamma (const G4ParticleChangeForGamma &right)
G4ParticleChangeForGamma & operator= (const G4ParticleChangeForGamma &right)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Private Attributes
const G4Track * currentTrack
G4double proposedKinEnergy
G4ThreeVector proposedMomentumDirection
G4ThreeVector proposedPolarization
Additional Inherited Members
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 57 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleChangeForGamma.hh
Constructor & Destructor Documentation
G4ParticleChangeForGamma::G4ParticleChangeForGamma ()
Definition at line 48 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleChangeForGamma.cc
References G4VParticleChange::debugFlag, G4cout, G4endl, NormalCondition, G4VParticleChange::theSteppingControlFlag, and G4VParticleChange::verboseLevel.
G4ParticleChangeForGamma::~G4ParticleChangeForGamma () virtual
Definition at line 60 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleChangeForGamma.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForGamma::G4ParticleChangeForGamma (const G4ParticleChangeForGamma & right) protected
Definition at line 69 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleChangeForGamma.cc
References currentTrack, G4cout, G4endl, proposedKinEnergy, proposedMomentumDirection, proposedPolarization, and G4VParticleChange::verboseLevel.
Member Function Documentation
void G4ParticleChangeForGamma::AddSecondary (G4DynamicParticle * aParticle)
Definition at line 122 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 122 of file G4ParticleChangeForGamma.cc
References G4VParticleChange::AddSecondary(), currentTrack, G4Track::GetGlobalTime(), G4Track::GetPosition(), G4Track::GetTouchableHandle(), and G4Track::SetTouchableHandle().
G4bool G4ParticleChangeForGamma::CheckIt (const G4Track & aTrack) virtual
Reimplemented from G4VParticleChange.
Definition at line 198 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 198 of file G4ParticleChangeForGamma.cc
References G4VParticleChange::accuracyForException, G4VParticleChange::accuracyForWarning, G4VParticleChange::CheckIt(), DumpInfo(), EventMustBeAborted, G4cout, G4endl, G4Exception(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), m, MeV, proposedKinEnergy, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4ParticleChangeForGamma::DumpInfo () const virtual
Reimplemented from G4VParticleChange.
Definition at line 180 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 180 of file G4ParticleChangeForGamma.cc
References G4VParticleChange::DumpInfo(), G4cout, G4endl, MeV, proposedKinEnergy, proposedMomentumDirection, and proposedPolarization.
Referenced by CheckIt().
const G4Track * G4ParticleChangeForGamma::GetCurrentTrack () const inline
Definition at line 153 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParticleChangeForGamma.hh
References currentTrack.
Referenced by G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNAMeltonAttachmentModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4DNATransformElectronModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), and G4DNAPTBExcitationModel::SampleSecondaries().
G4double G4ParticleChangeForGamma::GetProposedKineticEnergy () const inline
Definition at line 123 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ParticleChangeForGamma.hh
References proposedKinEnergy.
Referenced by G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplySecondaryBiasing(), and G4VEmProcess::PostStepDoIt().
const G4ThreeVector & G4ParticleChangeForGamma::GetProposedMomentumDirection () const inline
Definition at line 134 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ParticleChangeForGamma.hh
References proposedMomentumDirection.
Referenced by G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplySecondaryBiasing(), and G4LEPTSElasticModel::SampleSecondaries().
const G4ThreeVector & G4ParticleChangeForGamma::GetProposedPolarization () const inline
Definition at line 159 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ParticleChangeForGamma.hh
References proposedPolarization.
void G4ParticleChangeForGamma::InitializeForPostStep (const G4Track & track) inline
Definition at line 178 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ParticleChangeForGamma.hh
References currentTrack, G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), G4Track::GetPolarization(), G4Track::GetTrackStatus(), G4Track::GetWeight(), G4VParticleChange::InitializeSecondaries(), G4VParticleChange::isParentWeightProposed, proposedKinEnergy, proposedMomentumDirection, proposedPolarization, G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNonIonizingEnergyDeposit, G4VParticleChange::theParentWeight, G4VParticleChange::theStatusChange, and track.
Referenced by G4eplusAnnihilation::AtRestDoIt(), G4GammaGeneralProcess::PostStepDoIt(), and G4VEmProcess::PostStepDoIt().
G4ParticleChangeForGamma & G4ParticleChangeForGamma::operator= (const G4ParticleChangeForGamma & right) protected
Definition at line 82 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleChangeForGamma.cc
References currentTrack, G4cout, G4endl, proposedKinEnergy, proposedMomentumDirection, proposedPolarization, G4FastVector< Type, N >::SetElement(), G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNumberOfSecondaries, G4VParticleChange::theParentWeight, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, and G4VParticleChange::verboseLevel.
void G4ParticleChangeForGamma::ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz) inline
Definition at line 146 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ParticleChangeForGamma.hh
References proposedMomentumDirection, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplySecondaryBiasing(), G4LEPTSRotExcitationModel::SampleSecondaries(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSIonisationModel::SampleSecondaries(), G4LEPTSVibExcitationModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4DNASancheExcitationModel::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), MyKleinNishinaCompton::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
void G4ParticleChangeForGamma::ProposeMomentumDirection (const G4ThreeVector & Pfinal) inline
Definition at line 140 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ParticleChangeForGamma.hh
References dir, and proposedMomentumDirection.
void G4ParticleChangeForGamma::ProposePolarization (const G4ThreeVector & dir) inline
Definition at line 165 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ParticleChangeForGamma.hh
References dir, and proposedPolarization.
Referenced by G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
void G4ParticleChangeForGamma::ProposePolarization (G4double Px, G4double Py, G4double Pz) inline
Definition at line 171 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ParticleChangeForGamma.hh
References proposedPolarization, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
void G4ParticleChangeForGamma::SetProposedKineticEnergy (G4double proposedKinEnergy) inline
Definition at line 128 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleChangeForGamma.hh
References energy, and proposedKinEnergy.
Referenced by G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplySecondaryBiasing(), G4ElectronCapture::PostStepDoIt(), G4LEPTSVibExcitationModel::SampleSecondaries(), G4LEPTSDissociationModel::SampleSecondaries(), G4LEPTSElasticModel::SampleSecondaries(), G4LEPTSIonisationModel::SampleSecondaries(), G4LEPTSPositroniumModel::SampleSecondaries(), G4LEPTSRotExcitationModel::SampleSecondaries(), G4LEPTSAttachmentModel::SampleSecondaries(), G4LEPTSExcitationModel::SampleSecondaries(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4DNAMeltonAttachmentModel::SampleSecondaries(), MyKleinNishinaCompton::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), G4DNASancheExcitationModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4DNAMillerGreenExcitationModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
G4Step * G4ParticleChangeForGamma::UpdateStepForAtRest (G4Step * pStep) virtual
Reimplemented from G4VParticleChange.
Definition at line 139 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 139 of file G4ParticleChangeForGamma.cc
References G4Step::AddTotalEnergyDeposit(), G4Step::GetPostStepPoint(), G4VParticleChange::isParentWeightProposed, G4Step::SetStepLength(), G4StepPoint::SetWeight(), G4VParticleChange::theLocalEnergyDeposit, and G4VParticleChange::theParentWeight.
G4Step * G4ParticleChangeForGamma::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 151 of file G4ParticleChangeForGamma.cc.
View newest version in sPHENIX GitHub at line 151 of file G4ParticleChangeForGamma.cc
References G4Step::AddNonIonizingEnergyDeposit(), G4Step::AddTotalEnergyDeposit(), G4Track::CalculateVelocity(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetPDGMass(), G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, proposedKinEnergy, proposedMomentumDirection, proposedPolarization, G4StepPoint::SetKineticEnergy(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPolarization(), G4StepPoint::SetVelocity(), G4StepPoint::SetWeight(), G4VParticleChange::theLocalEnergyDeposit, G4VParticleChange::theNonIonizingEnergyDeposit, and G4VParticleChange::theParentWeight.
Member Data Documentation
const G4Track* G4ParticleChangeForGamma::currentTrack private
Definition at line 108 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleChangeForGamma.hh
Referenced by AddSecondary(), G4ParticleChangeForGamma(), GetCurrentTrack(), InitializeForPostStep(), and operator=().
G4double G4ParticleChangeForGamma::proposedKinEnergy private
Definition at line 111 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleChangeForGamma.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForGamma(), GetProposedKineticEnergy(), InitializeForPostStep(), operator=(), SetProposedKineticEnergy(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChangeForGamma::proposedMomentumDirection private
Definition at line 114 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleChangeForGamma.hh
Referenced by DumpInfo(), G4ParticleChangeForGamma(), GetProposedMomentumDirection(), InitializeForPostStep(), operator=(), ProposeMomentumDirection(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChangeForGamma::proposedPolarization private
Definition at line 117 of file G4ParticleChangeForGamma.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleChangeForGamma.hh
Referenced by DumpInfo(), G4ParticleChangeForGamma(), GetProposedPolarization(), InitializeForPostStep(), operator=(), ProposePolarization(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForGamma.hh
geant4/tree/geant4-10.6-release/source/track/src/G4ParticleChangeForGamma.cc