ECCE @ EIC Software: CLHEP::RandFlat Class Reference
CLHEP::RandFlat Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandFlat.h>
Public Member Functions
RandFlat (HepRandomEngine &anEngine)
RandFlat (HepRandomEngine &anEngine, double width)
RandFlat (HepRandomEngine &anEngine, double a, double b)
RandFlat (HepRandomEngine *anEngine)
RandFlat (HepRandomEngine *anEngine, double width)
RandFlat (HepRandomEngine *anEngine, double a, double b)
virtual ~RandFlat ()
double fire ()
double fire (double width)
double fire (double a, double b)
long fireInt (long n)
long fireInt (long a1, long n)
int fireBit ()
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double lx, double dx)
double operator() ()
double operator() (double width)
double operator() (double a, double b)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double width)
static double shoot (double a, double b)
static long shootInt (long n)
static long shootInt (long a1, long n)
static int shootBit ()
static void shootArray (const int size, double *vect)
static void shootArray (const int size, double *vect, double lx, double dx)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double width)
static double shoot (HepRandomEngine *anEngine, double a, double b)
static long shootInt (HepRandomEngine *anEngine, long n)
static long shootInt (HepRandomEngine *anEngine, long a1, long n)
static int shootBit (HepRandomEngine *)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double lx, double dx)
static std::string distributionName ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Private Member Functions
void fireBits ()
Static Private Member Functions
static void shootBits ()
static void shootBits (HepRandomEngine *)
Private Attributes
unsigned long randomInt
unsigned long firstUnusedBit
std::shared_ptr< HepRandomEngine > localEngine
double defaultWidth
double defaultA
double defaultB
Static Private Attributes
static const unsigned long MSB = 1ul<<RandFlat::MSBBits
static const int MSBBits = 15
static CLHEP_THREAD_LOCAL
unsigned long staticRandomInt = 0
static CLHEP_THREAD_LOCAL
unsigned long staticFirstUnusedBit = 0
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Gabri.nosp@m.ele..nosp@m.Cosmo.nosp@m.@cer.nosp@m.n.ch
Definition at line 41 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 41 of file RandFlat.h
Constructor & Destructor Documentation
CLHEP::RandFlat::RandFlat (HepRandomEngine & anEngine) inline
CLHEP::RandFlat::RandFlat (HepRandomEngine & anEngine, double width) inline
CLHEP::RandFlat::RandFlat (HepRandomEngine & anEngine, double a, double b) inline
CLHEP::RandFlat::RandFlat (HepRandomEngine * anEngine) inline
CLHEP::RandFlat::RandFlat (HepRandomEngine * anEngine, double width) inline
CLHEP::RandFlat::RandFlat (HepRandomEngine * anEngine, double a, double b) inline
CLHEP::RandFlat::~RandFlat () virtual
Definition at line 43 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 43 of file RandFlat.cc
Member Function Documentation
static std::string CLHEP::RandFlat::distributionName () inline static
Definition at line 136 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 136 of file RandFlat.h
Referenced by restoreDistState(), and saveDistState().
HepRandomEngine & CLHEP::RandFlat::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 41 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 41 of file RandFlat.cc
References localEngine.
double CLHEP::RandFlat::fire () inline
Referenced by fireArray(), and operator()().
double CLHEP::RandFlat::fire (double width) inline
double CLHEP::RandFlat::fire (double a, double b) inline
void CLHEP::RandFlat::fireArray (const int size, double * vect)
Definition at line 85 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 85 of file RandFlat.cc
References defaultA, defaultB, and fire().
void CLHEP::RandFlat::fireArray (const int size, double * vect, double lx, double dx)
Definition at line 93 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 93 of file RandFlat.cc
References fire().
int CLHEP::RandFlat::fireBit () inline
void CLHEP::RandFlat::fireBits () inline private
long CLHEP::RandFlat::fireInt (long n) inline
long CLHEP::RandFlat::fireInt (long a1, long n) inline
std::istream & CLHEP::RandFlat::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 170 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 170 of file RandFlat.cc
References defaultA, defaultB, defaultWidth, firstUnusedBit, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), randomInt, and t.
Referenced by CLHEP::RandBit::get().
std::string CLHEP::RandFlat::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 40 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 40 of file RandFlat.cc
Referenced by get(), and put().
double CLHEP::RandFlat::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 46 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 46 of file RandFlat.cc
References defaultA, defaultB, and fire().
double CLHEP::RandFlat::operator() (double width)
Definition at line 50 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 50 of file RandFlat.cc
References fire().
double CLHEP::RandFlat::operator() (double a, double b)
Definition at line 54 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 54 of file RandFlat.cc
References fire().
std::ostream & CLHEP::RandFlat::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 154 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 154 of file RandFlat.cc
References defaultA, defaultB, defaultWidth, CLHEP::DoubConv::dto2longs(), firstUnusedBit, name(), gammaraytel::pr, randomInt, and t.
Referenced by CLHEP::RandBit::put().
std::istream & CLHEP::RandFlat::restoreDistState (std::istream & is) static
Definition at line 210 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 210 of file RandFlat.cc
References c1, c2, distributionName(), staticFirstUnusedBit, and staticRandomInt.
Referenced by CLHEP::StaticRandomStates::restore(), CLHEP::RandBit::restoreDistState(), and restoreFullState().
void CLHEP::RandFlat::restoreEngineStatus (const char filename[] = "Config.conf") static
Definition at line 117 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 117 of file RandFlat.cc
References CLHEP::HepRandom::getTheEngine(), in, CLHEP::HepRandomEngine::restoreStatus(), staticFirstUnusedBit, and staticRandomInt.
std::istream & CLHEP::RandFlat::restoreFullState (std::istream & is) static
Definition at line 241 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 241 of file RandFlat.cc
References restoreDistState(), and CLHEP::HepRandom::restoreFullState().
Referenced by CLHEP::RandBit::restoreFullState().
std::ostream & CLHEP::RandFlat::saveDistState (std::ostream & os) static
Definition at line 201 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 201 of file RandFlat.cc
References distributionName(), CLHEP::prec, staticFirstUnusedBit, and staticRandomInt.
Referenced by CLHEP::StaticRandomStates::save(), CLHEP::RandBit::saveDistState(), and saveFullState().
void CLHEP::RandFlat::saveEngineStatus (const char filename[] = "Config.conf") static
Definition at line 102 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 102 of file RandFlat.cc
References demo::app, CLHEP::HepRandom::getTheEngine(), CLHEP::HepRandomEngine::saveStatus(), staticFirstUnusedBit, and staticRandomInt.
std::ostream & CLHEP::RandFlat::saveFullState (std::ostream & os) static
Definition at line 235 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 235 of file RandFlat.cc
References saveDistState(), and CLHEP::HepRandom::saveFullState().
Referenced by CLHEP::RandBit::saveFullState().
double CLHEP::RandFlat::shoot () static
Definition at line 58 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 58 of file RandFlat.cc
References CLHEP::HepRandomEngine::flat(), and CLHEP::HepRandom::getTheEngine().
Referenced by atl_ran(), CLHEP::RandBreitWigner::fireM2(), flowAfterburner(), IORTPrimaryGeneratorAction::GeneratePrimaries(), CCalPrimaryGeneratorAction::GeneratePrimaries(), G4ParticleHPProduct::GetMultiplicity(), shootArray(), and CLHEP::RandBreitWigner::shootM2().
static double CLHEP::RandFlat::shoot (double width) inline static
static double CLHEP::RandFlat::shoot (double a, double b) inline static
static double CLHEP::RandFlat::shoot (HepRandomEngine * anEngine) inline static
static double CLHEP::RandFlat::shoot (HepRandomEngine * anEngine, double width) inline static
static double CLHEP::RandFlat::shoot (HepRandomEngine * anEngine, double a, double b) inline static
void CLHEP::RandFlat::shootArray (const int size, double * vect) static
Definition at line 62 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 62 of file RandFlat.cc
References CLHEP::HepRandomEngine::flatArray(), and CLHEP::HepRandom::getTheEngine().
void CLHEP::RandFlat::shootArray (const int size, double * vect, double lx, double dx) static
Definition at line 66 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 66 of file RandFlat.cc
References shoot().
static void CLHEP::RandFlat::shootArray (HepRandomEngine * anEngine, const int size, double * vect) inline static
void CLHEP::RandFlat::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double lx, double dx) static
Definition at line 75 of file RandFlat.cc.
View newest version in sPHENIX GitHub at line 75 of file RandFlat.cc
References shoot().
static int CLHEP::RandFlat::shootBit () inline static
static int CLHEP::RandFlat::shootBit (HepRandomEngine *) inline static
static void CLHEP::RandFlat::shootBits () inline static private
static void CLHEP::RandFlat::shootBits (HepRandomEngine *) inline static private
static long CLHEP::RandFlat::shootInt (long n) inline static
static long CLHEP::RandFlat::shootInt (long a1, long n) inline static
static long CLHEP::RandFlat::shootInt (HepRandomEngine * anEngine, long n) inline static
static long CLHEP::RandFlat::shootInt (HepRandomEngine * anEngine, long a1, long n) inline static
Member Data Documentation
double CLHEP::RandFlat::defaultA private
Definition at line 201 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 201 of file RandFlat.h
Referenced by fireArray(), get(), operator()(), and put().
double CLHEP::RandFlat::defaultB private
Definition at line 202 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 202 of file RandFlat.h
Referenced by fireArray(), get(), operator()(), and put().
double CLHEP::RandFlat::defaultWidth private
Definition at line 200 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 200 of file RandFlat.h
Referenced by get(), and put().
unsigned long CLHEP::RandFlat::firstUnusedBit private
Definition at line 195 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 195 of file RandFlat.h
Referenced by get(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandFlat::localEngine private
Definition at line 199 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 199 of file RandFlat.h
Referenced by engine().
const unsigned long CLHEP::RandFlat::MSB = 1ul<<RandFlat::MSBBits static private
Definition at line 190 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 190 of file RandFlat.h
const int CLHEP::RandFlat::MSBBits = 15 static private
Definition at line 191 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 191 of file RandFlat.h
unsigned long CLHEP::RandFlat::randomInt private
Definition at line 194 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 194 of file RandFlat.h
Referenced by get(), and put().
CLHEP_THREAD_LOCAL unsigned long CLHEP::RandFlat::staticFirstUnusedBit = 0 static private
Definition at line 197 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 197 of file RandFlat.h
Referenced by restoreDistState(), restoreEngineStatus(), saveDistState(), and saveEngineStatus().
CLHEP_THREAD_LOCAL unsigned long CLHEP::RandFlat::staticRandomInt = 0 static private
Definition at line 196 of file RandFlat.h.
View newest version in sPHENIX GitHub at line 196 of file RandFlat.h
Referenced by restoreDistState(), restoreEngineStatus(), saveDistState(), and saveEngineStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandFlat.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandFlat.cc