ECCE @ EIC Software: CexmcSimpleEnergyDeposit Class Reference
CexmcSimpleEnergyDeposit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcSimpleEnergyDeposit.hh>
Public Member Functions
CexmcSimpleEnergyDeposit (const G4String &name)
void Initialize (G4HCofThisEvent *hcOfThisEvent)
void EndOfEvent (G4HCofThisEvent *hcOfThisEvent)
void DrawAll (void)
void PrintAll (void)
void clear (void)
Public Member Functions inherited from CexmcPrimitiveScorer
CexmcPrimitiveScorer (const G4String &name)
virtual ~CexmcPrimitiveScorer ()
void InitializeMessenger (void)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
G4int GetIndex (G4Step *step)
G4bool ProcessHits (G4Step *step, G4TouchableHistory *tHistory)
Protected Member Functions inherited from CexmcPrimitiveScorer
void PrintHeader (G4int nmbOfEntries) const
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Protected Attributes
CexmcEnergyDepositCollection * eventMap
Private Attributes
G4int hcId
Detailed Description
Definition at line 59 of file CexmcSimpleEnergyDeposit.hh.
View newest version in sPHENIX GitHub at line 59 of file CexmcSimpleEnergyDeposit.hh
Constructor & Destructor Documentation
CexmcSimpleEnergyDeposit::CexmcSimpleEnergyDeposit (const G4String & name) explicit
Definition at line 49 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 49 of file CexmcSimpleEnergyDeposit.cc
Member Function Documentation
void CexmcSimpleEnergyDeposit::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 94 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 94 of file CexmcSimpleEnergyDeposit.cc
References G4VTHitsMap< T, Map_t >::clear(), and eventMap.
void CexmcSimpleEnergyDeposit::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 100 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 100 of file CexmcSimpleEnergyDeposit.cc
void CexmcSimpleEnergyDeposit::EndOfEvent (G4HCofThisEvent * hcOfThisEvent) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 87 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 87 of file CexmcSimpleEnergyDeposit.cc
References G4VPrimitiveScorer::GetVerboseLevel(), and PrintAll().
G4int CexmcSimpleEnergyDeposit::GetIndex (G4Step * step) protected virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 55 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 55 of file CexmcSimpleEnergyDeposit.cc
Referenced by ProcessHits().
void CexmcSimpleEnergyDeposit::Initialize (G4HCofThisEvent * hcOfThisEvent) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 75 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 75 of file CexmcSimpleEnergyDeposit.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, eventMap, G4VPrimitiveScorer::GetCollectionID(), G4VSensitiveDetector::GetName(), hcId, and G4VPrimitiveScorer::primitiveName.
void CexmcSimpleEnergyDeposit::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 105 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 105 of file CexmcSimpleEnergyDeposit.cc
References G4VTHitsMap< T, Map_t >::entries(), eventMap, G4BestUnit, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), and CexmcPrimitiveScorer::PrintHeader().
Referenced by EndOfEvent().
G4bool CexmcSimpleEnergyDeposit::ProcessHits (G4Step * step, G4TouchableHistory * tHistory) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 61 of file CexmcSimpleEnergyDeposit.cc.
View newest version in sPHENIX GitHub at line 61 of file CexmcSimpleEnergyDeposit.cc
References G4VTHitsMap< T, Map_t >::add(), eventMap, GetIndex(), and G4Step::GetTotalEnergyDeposit().
Member Data Documentation
CexmcEnergyDepositCollection* CexmcSimpleEnergyDeposit::eventMap protected
Definition at line 81 of file CexmcSimpleEnergyDeposit.hh.
View newest version in sPHENIX GitHub at line 81 of file CexmcSimpleEnergyDeposit.hh
Referenced by clear(), Initialize(), CexmcEnergyDepositInCalorimeter::PrintAll(), CexmcEnergyDepositInLeftRightSet::PrintAll(), PrintAll(), and ProcessHits().
G4int CexmcSimpleEnergyDeposit::hcId private
Definition at line 84 of file CexmcSimpleEnergyDeposit.hh.
View newest version in sPHENIX GitHub at line 84 of file CexmcSimpleEnergyDeposit.hh
Referenced by Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcSimpleEnergyDeposit.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcSimpleEnergyDeposit.cc