ECCE @ EIC Software: G4ChannelingTrackData Class Reference
G4ChannelingTrackData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingTrackData.hh>
Public Member Functions
G4ChannelingTrackData ()
~G4ChannelingTrackData ()
void Print () const
void Reset ()
G4double GetDensity ()
void SetNuD (G4double aDouble)
G4double GetNuD ()
void SetElD (G4double aDouble)
G4double GetElD ()
void SetEFX (G4double aDouble)
G4double GetEFX ()
void SetEFY (G4double aDouble)
G4double GetEFY ()
G4ThreeVector GetMomCh ()
void SetMomCh (G4ThreeVector a3vec)
G4ThreeVector GetPosCh ()
void SetPosCh (G4ThreeVector a3vec)
Public Member Functions inherited from G4VAuxiliaryTrackInformation
G4VAuxiliaryTrackInformation ()
virtual ~G4VAuxiliaryTrackInformation ()
Private Attributes
const G4Channeling * fChannelingProcess
G4ThreeVector fDBL
G4ThreeVector fMomCh
G4ThreeVector fPosCh
G4double fNuD
G4double fElD
G4double fEFX
G4double fEFY
Friends
class G4Channeling
Detailed Description
Definition at line 48 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ChannelingTrackData.hh
Constructor & Destructor Documentation
G4ChannelingTrackData::G4ChannelingTrackData ()
Definition at line 30 of file G4ChannelingTrackData.cc.
View newest version in sPHENIX GitHub at line 30 of file G4ChannelingTrackData.cc
G4ChannelingTrackData::~G4ChannelingTrackData ()
Definition at line 43 of file G4ChannelingTrackData.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ChannelingTrackData.cc
Member Function Documentation
G4double G4ChannelingTrackData::GetDensity () inline
Definition at line 68 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ChannelingTrackData.hh
References fElD, and fNuD.
Referenced by G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
G4double G4ChannelingTrackData::GetEFX () inline
Definition at line 77 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChannelingTrackData.hh
References fEFX.
G4double G4ChannelingTrackData::GetEFY () inline
Definition at line 80 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChannelingTrackData.hh
References fEFY.
G4double G4ChannelingTrackData::GetElD () inline
Definition at line 74 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ChannelingTrackData.hh
References fElD.
Referenced by G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
G4ThreeVector G4ChannelingTrackData::GetMomCh () inline
Definition at line 82 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChannelingTrackData.hh
References fMomCh.
Referenced by G4Channeling::PostStepDoIt().
G4double G4ChannelingTrackData::GetNuD () inline
Definition at line 71 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ChannelingTrackData.hh
References fNuD.
Referenced by G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
G4ThreeVector G4ChannelingTrackData::GetPosCh () inline
Definition at line 85 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChannelingTrackData.hh
References fPosCh.
Referenced by G4Channeling::UpdateParameters().
void G4ChannelingTrackData::Print (void) const virtual
Reimplemented from G4VAuxiliaryTrackInformation.
Definition at line 47 of file G4ChannelingTrackData.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ChannelingTrackData.cc
References CLHEP::angstrom, fElD, fMomCh, fNuD, fPosCh, G4cout, G4endl, and CLHEP::GeV.
void G4ChannelingTrackData::Reset () inline
Definition at line 61 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ChannelingTrackData.hh
References fChannelingProcess, fDBL, fElD, fMomCh, fNuD, and fPosCh.
Referenced by G4Channeling::GetMeanFreePath(), and G4Channeling::PostStepDoIt().
void G4ChannelingTrackData::SetEFX (G4double aDouble) inline
Definition at line 76 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ChannelingTrackData.hh
References fEFX.
Referenced by G4Channeling::UpdateParameters().
void G4ChannelingTrackData::SetEFY (G4double aDouble) inline
Definition at line 79 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ChannelingTrackData.hh
References fEFY.
Referenced by G4Channeling::UpdateParameters().
void G4ChannelingTrackData::SetElD (G4double aDouble) inline
Definition at line 73 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ChannelingTrackData.hh
References fElD.
Referenced by G4Channeling::UpdateParameters().
void G4ChannelingTrackData::SetMomCh (G4ThreeVector a3vec) inline
Definition at line 83 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChannelingTrackData.hh
References fMomCh.
Referenced by G4Channeling::UpdateParameters().
void G4ChannelingTrackData::SetNuD (G4double aDouble) inline
Definition at line 70 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ChannelingTrackData.hh
References fNuD.
Referenced by G4Channeling::UpdateParameters().
void G4ChannelingTrackData::SetPosCh (G4ThreeVector a3vec) inline
Definition at line 86 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChannelingTrackData.hh
References fPosCh.
Referenced by G4Channeling::UpdateParameters().
Friends And Related Function Documentation
friend class G4Channeling friend
Definition at line 49 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ChannelingTrackData.hh
Member Data Documentation
const G4Channeling* G4ChannelingTrackData::fChannelingProcess private
Definition at line 58 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ChannelingTrackData.hh
Referenced by Reset().
G4ThreeVector G4ChannelingTrackData::fDBL private
Definition at line 92 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChannelingTrackData.hh
Referenced by Reset().
G4double G4ChannelingTrackData::fEFX private
Definition at line 103 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ChannelingTrackData.hh
Referenced by GetEFX(), and SetEFX().
G4double G4ChannelingTrackData::fEFY private
Definition at line 104 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ChannelingTrackData.hh
Referenced by GetEFY(), and SetEFY().
G4double G4ChannelingTrackData::fElD private
Definition at line 101 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ChannelingTrackData.hh
Referenced by GetDensity(), GetElD(), Print(), Reset(), and SetElD().
G4ThreeVector G4ChannelingTrackData::fMomCh private
Definition at line 97 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ChannelingTrackData.hh
Referenced by GetMomCh(), Print(), Reset(), and SetMomCh().
G4double G4ChannelingTrackData::fNuD private
Definition at line 100 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ChannelingTrackData.hh
Referenced by GetDensity(), GetNuD(), Print(), Reset(), and SetNuD().
G4ThreeVector G4ChannelingTrackData::fPosCh private
Definition at line 98 of file G4ChannelingTrackData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ChannelingTrackData.hh
Referenced by GetPosCh(), Print(), Reset(), and SetPosCh().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingTrackData.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/src/G4ChannelingTrackData.cc