ECCE @ EIC Software: macros/blob/master/common/G4_BToF.C File Reference
G4_BToF.C File Reference
#include <GlobalVariables.C>
#include <fun4all/Fun4AllServer.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
Namespaces
namespace Enable
namespace BTOF
Macros
#define MACRO_G4BToF_C
Functions
void BToFInit ()
double Build_G4_BTof (PHG4Reco *g4Reco, double tof_rad=82.0, double zpos=-60.0, double tof_length=400.0)
double BToFSetup (PHG4Reco *g4Reco)
void BToF_Reco (int verbosity=0)
Variables
bool Enable::BTOF = false
bool Enable::BTOF_OVERLAPCHECK = false
int Enable::BTOF_VERBOSITY = 0
const int BTOF::gas_lyr = 6
const int BTOF::mrpc_inn_lyr = 5
const double BTOF::rad = 76.5
const double BTOF::zpos = -60.0
const double BTOF::length = 400.
int BTOF::subsysID = 0
Macro Definition Documentation
#define MACRO_G4BToF_C
Definition at line 2 of file G4_BToF.C.
View newest version in sPHENIX GitHub at line 2 of file G4_BToF.C
Function Documentation
void BToF_Reco (int verbosity = 0)
Definition at line 550 of file G4_BToF.C.
View newest version in sPHENIX GitHub at line 550 of file G4_BToF.C
References Fun4AllServer::instance().
void BToFInit ()
Definition at line 33 of file G4_BToF.C.
View newest version in sPHENIX GitHub at line 33 of file G4_BToF.C
References BTOF::length, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, and BlackHoleGeometry::min_z.
Referenced by G4Init().
double BToFSetup (PHG4Reco * g4Reco)
Definition at line 519 of file G4_BToF.C.
View newest version in sPHENIX GitHub at line 519 of file G4_BToF.C
References PHG4TrackFastSim::add_cylinder_state(), Build_G4_BTof(), TRACKING::FastKalmanFilter(), BTOF::gas_lyr, BTOF::length, TRACKING::ProjectionNames, BTOF::rad, radius, and BTOF::zpos.
Referenced by G4Setup().
double Build_G4_BTof (PHG4Reco * g4Reco, double tof_rad = 82.0, double zpos = -60.0, double tof_length = 400.0)
Definition at line 40 of file G4_BToF.C.
View newest version in sPHENIX GitHub at line 40 of file G4_BToF.C
References Enable::BTOF_OVERLAPCHECK, Enable::BTOF_VERBOSITY, ETOF::gas_gap, BTOF::gas_lyr, G4TTL::layer, max, BTOF::mrpc_inn_lyr, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), BTOF::subsysID, PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and BTOF::zpos.
Referenced by BToFSetup().