ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/particles/pyG4DynamicParticle.cc File Reference
pyG4DynamicParticle.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4DynamicParticle.hh"
#include "G4PrimaryParticle.hh"
Functions
void export_G4DynamicParticle ()
Function Documentation
void export_G4DynamicParticle ()
Definition at line 41 of file pyG4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4DynamicParticle.cc
References G4DynamicParticle::DumpInfo(), G4DynamicParticle::GetCharge(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetOccupancy(), G4DynamicParticle::GetPDGcode(), G4DynamicParticle::GetPolarization(), G4DynamicParticle::GetPreAssignedDecayProperTime(), G4DynamicParticle::GetPrimaryParticle(), G4DynamicParticle::GetProperTime(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), G4DynamicParticle::GetTotalOccupancy(), G4DynamicParticle::GetVerboseLevel(), and G4DynamicParticle::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().