ECCE @ EIC Software: DicomRegularDetectorConstruction Class Reference
DicomRegularDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomRegularDetectorConstruction.hh>
Public Member Functions
DicomRegularDetectorConstruction ()
~DicomRegularDetectorConstruction ()
Public Member Functions inherited from DicomDetectorConstruction
DicomDetectorConstruction ()
~DicomDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
G4int GetTotalVoxels () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
virtual void ConstructPhantom ()
Additional Inherited Members
Protected Member Functions inherited from DicomDetectorConstruction
void InitialisationOfMaterials ()
void ReadPhantomData ()
void ReadPhantomDataNew ()
void ReadVoxelDensities (std::ifstream &fin)
void ReadPhantomDataFile (const G4String &fname)
void MergeZSliceHeaders ()
G4Material * BuildMaterialWithChangingDensity (const G4Material *origMate, G4float density, G4String newMateName)
void ConstructPhantomContainer ()
void ConstructPhantomContainerNew ()
void SetScorer (G4LogicalVolume *voxel_logic)
virtual void ConstructSDandField ()
Protected Attributes inherited from DicomDetectorConstruction
G4Material * fAir
G4Box * fWorld_solid
G4LogicalVolume * fWorld_logic
G4VPhysicalVolume * fWorld_phys
G4Box * fContainer_solid
G4LogicalVolume * fContainer_logic
G4VPhysicalVolume * fContainer_phys
G4int fNoFiles
std::vector< G4Material * > fOriginalMaterials
std::vector< G4Material * > fMaterials
size_t * fMateIDs
std::map< G4int, G4double > fDensityDiffs
std::vector
< DicomPhantomZSliceHeader * > fZSliceHeaders
DicomPhantomZSliceHeader * fZSliceHeaderMerged
G4int fNVoxelX
G4int fNVoxelY
G4int fNVoxelZ
G4double fVoxelHalfDimX
G4double fVoxelHalfDimY
G4double fVoxelHalfDimZ
G4double fMinX
G4double fMinY
G4double fMinZ
G4double fMaxX
G4double fMaxY
G4double fMaxZ
std::map< G4int, G4Material * > thePhantomMaterialsOriginal
DicomPhantomZSliceMerged * fMergedSlices
std::set< G4LogicalVolume * > fScorers
G4bool fConstructed
Detailed Description
DicomRegularDetectorConstruction class
Construct the phantom using DicomPhantomParameterisatin
History: 30.11.07 First version
Author
P. Arce
Definition at line 50 of file DicomRegularDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 50 of file DicomRegularDetectorConstruction.hh
Constructor & Destructor Documentation
DicomRegularDetectorConstruction::DicomRegularDetectorConstruction ()
Definition at line 52 of file DicomRegularDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 52 of file DicomRegularDetectorConstruction.cc
DicomRegularDetectorConstruction::~DicomRegularDetectorConstruction ()
Definition at line 58 of file DicomRegularDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 58 of file DicomRegularDetectorConstruction.cc
Member Function Documentation
void DicomRegularDetectorConstruction::ConstructPhantom () private virtual
Implements DicomDetectorConstruction.
Definition at line 63 of file DicomRegularDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 63 of file DicomRegularDetectorConstruction.cc
References G4PhantomParameterisation::BuildContainerSolid(), G4PhantomParameterisation::CheckVoxelsFillContainer(), DicomDetectorConstruction::fContainer_logic, DicomDetectorConstruction::fContainer_phys, DicomDetectorConstruction::fContainer_solid, DicomDetectorConstruction::fMateIDs, DicomDetectorConstruction::fMaterials, DicomDetectorConstruction::fNVoxelX, DicomDetectorConstruction::fNVoxelY, DicomDetectorConstruction::fNVoxelZ, DicomDetectorConstruction::fVoxelHalfDimX, DicomDetectorConstruction::fVoxelHalfDimY, DicomDetectorConstruction::fVoxelHalfDimZ, G4cout, G4endl, G4VisAttributes::GetInvisible(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), kXAxis, G4PhantomParameterisation::SetMaterialIndices(), G4PhantomParameterisation::SetMaterials(), G4PhantomParameterisation::SetNoVoxel(), G4PVParameterised::SetRegularStructureId(), DicomDetectorConstruction::SetScorer(), G4LogicalVolume::SetVisAttributes(), and G4PhantomParameterisation::SetVoxelDimensions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomRegularDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomRegularDetectorConstruction.cc