ECCE @ EIC Software: CLHEP::RandBreitWigner Class Reference
CLHEP::RandBreitWigner Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandBreitWigner.h>
Public Member Functions
RandBreitWigner (HepRandomEngine &anEngine, double a=1.0, double b=0.2)
RandBreitWigner (HepRandomEngine *anEngine, double a=1.0, double b=0.2)
virtual ~RandBreitWigner ()
double fire ()
double fire (double a, double b)
double fire (double a, double b, double c)
double fireM2 ()
double fireM2 (double a, double b)
double fireM2 (double a, double b, double c)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double a, double b)
void fireArray (const int size, double *vect, double a, double b, double c)
double operator() ()
double operator() (double a, double b)
double operator() (double a, double b, double c)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot (double a=1.0, double b=0.2)
static double shoot (double a, double b, double c)
static double shootM2 (double a=1.0, double b=0.2)
static double shootM2 (double a, double b, double c)
static void shootArray (const int size, double *vect)
static void shootArray (const int size, double *vect, double a, double b)
static void shootArray (const int size, double *vect, double a, double b, double c)
static double shoot (HepRandomEngine *anEngine, double a=1.0, double b=0.2)
static double shoot (HepRandomEngine *anEngine, double a, double b, double c)
static double shootM2 (HepRandomEngine *anEngine, double a=1.0, double b=0.2)
static double shootM2 (HepRandomEngine *anEngine, double a, double b, double c)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double a, double b)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double a, double b, double c)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double defaultA
double defaultB
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Gabri.nosp@m.ele..nosp@m.Cosmo.nosp@m.@cer.nosp@m.n.ch
Definition at line 36 of file RandBreitWigner.h.
View newest version in sPHENIX GitHub at line 36 of file RandBreitWigner.h
Constructor & Destructor Documentation
CLHEP::RandBreitWigner::RandBreitWigner (HepRandomEngine & anEngine, double a = 1.0, double b = 0.2) inline
CLHEP::RandBreitWigner::RandBreitWigner (HepRandomEngine * anEngine, double a = 1.0, double b = 0.2) inline
CLHEP::RandBreitWigner::~RandBreitWigner () virtual
Definition at line 32 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 32 of file RandBreitWigner.cc
Member Function Documentation
static std::string CLHEP::RandBreitWigner::distributionName () inline static
Definition at line 130 of file RandBreitWigner.h.
View newest version in sPHENIX GitHub at line 130 of file RandBreitWigner.h
HepRandomEngine & CLHEP::RandBreitWigner::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 30 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 30 of file RandBreitWigner.cc
References localEngine.
double CLHEP::RandBreitWigner::fire ()
Definition at line 197 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 197 of file RandBreitWigner.cc
References defaultA, and defaultB.
Referenced by fireArray(), and operator()().
double CLHEP::RandBreitWigner::fire (double a, double b)
Definition at line 202 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 202 of file RandBreitWigner.cc
References CLHEP::halfpi, and localEngine.
double CLHEP::RandBreitWigner::fire (double a, double b, double c)
Definition at line 212 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 212 of file RandBreitWigner.cc
References localEngine.
void CLHEP::RandBreitWigner::fireArray (const int size, double * vect)
Definition at line 256 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 256 of file RandBreitWigner.cc
References defaultA, defaultB, fire(), and v.
void CLHEP::RandBreitWigner::fireArray (const int size, double * vect, double a, double b)
Definition at line 262 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 262 of file RandBreitWigner.cc
References fire(), and v.
void CLHEP::RandBreitWigner::fireArray (const int size, double * vect, double a, double b, double c)
Definition at line 269 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 269 of file RandBreitWigner.cc
References fire(), and v.
double CLHEP::RandBreitWigner::fireM2 ()
Definition at line 224 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 224 of file RandBreitWigner.cc
References defaultA, and defaultB.
double CLHEP::RandBreitWigner::fireM2 (double a, double b)
Definition at line 229 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 229 of file RandBreitWigner.cc
References CLHEP::halfpi, localEngine, and CLHEP::RandFlat::shoot().
double CLHEP::RandBreitWigner::fireM2 (double a, double b, double c)
Definition at line 241 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 241 of file RandBreitWigner.cc
References localEngine, max, CLHEP::RandFlat::shoot(), and tmp.
std::istream & CLHEP::RandBreitWigner::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 290 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 290 of file RandBreitWigner.cc
References defaultA, defaultB, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandBreitWigner::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 29 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 29 of file RandBreitWigner.cc
Referenced by get(), and put().
double CLHEP::RandBreitWigner::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 35 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 35 of file RandBreitWigner.cc
References defaultA, defaultB, and fire().
double CLHEP::RandBreitWigner::operator() (double a, double b)
Definition at line 39 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 39 of file RandBreitWigner.cc
References fire().
double CLHEP::RandBreitWigner::operator() (double a, double b, double c)
Definition at line 43 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 43 of file RandBreitWigner.cc
References fire().
std::ostream & CLHEP::RandBreitWigner::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 277 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 277 of file RandBreitWigner.cc
References defaultA, defaultB, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
double CLHEP::RandBreitWigner::shoot (double a = 1.0, double b = 0.2) static
Definition at line 47 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 47 of file RandBreitWigner.cc
References CLHEP::HepRandomEngine::flat(), CLHEP::HepRandom::getTheEngine(), and CLHEP::halfpi.
Referenced by shootArray().
double CLHEP::RandBreitWigner::shoot (double a, double b, double c) static
Definition at line 57 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 57 of file RandBreitWigner.cc
References CLHEP::HepRandomEngine::flat(), and CLHEP::HepRandom::getTheEngine().
double CLHEP::RandBreitWigner::shoot (HepRandomEngine * anEngine, double a = 1.0, double b = 0.2) static
Definition at line 119 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 119 of file RandBreitWigner.cc
References CLHEP::HepRandomEngine::flat(), and CLHEP::halfpi.
double CLHEP::RandBreitWigner::shoot (HepRandomEngine * anEngine, double a, double b, double c) static
Definition at line 130 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 130 of file RandBreitWigner.cc
References CLHEP::HepRandomEngine::flat().
void CLHEP::RandBreitWigner::shootArray (const int size, double * vect) static
Definition at line 96 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 96 of file RandBreitWigner.cc
References shoot(), and v.
void CLHEP::RandBreitWigner::shootArray (const int size, double * vect, double a, double b) static
Definition at line 102 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 102 of file RandBreitWigner.cc
References shoot(), and v.
void CLHEP::RandBreitWigner::shootArray (const int size, double * vect, double a, double b, double c) static
Definition at line 109 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 109 of file RandBreitWigner.cc
References shoot(), and v.
void CLHEP::RandBreitWigner::shootArray (HepRandomEngine * anEngine, const int size, double * vect) static
Definition at line 172 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 172 of file RandBreitWigner.cc
References shoot(), and v.
void CLHEP::RandBreitWigner::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double a, double b) static
Definition at line 179 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 179 of file RandBreitWigner.cc
References shoot(), and v.
void CLHEP::RandBreitWigner::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double a, double b, double c) static
Definition at line 187 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 187 of file RandBreitWigner.cc
References shoot(), and v.
double CLHEP::RandBreitWigner::shootM2 (double a = 1.0, double b = 0.2) static
Definition at line 69 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 69 of file RandBreitWigner.cc
References CLHEP::halfpi, and CLHEP::RandFlat::shoot().
double CLHEP::RandBreitWigner::shootM2 (double a, double b, double c) static
Definition at line 81 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 81 of file RandBreitWigner.cc
References max, CLHEP::RandFlat::shoot(), and tmp.
double CLHEP::RandBreitWigner::shootM2 (HepRandomEngine * anEngine, double a = 1.0, double b = 0.2) static
Definition at line 143 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 143 of file RandBreitWigner.cc
References CLHEP::halfpi, and CLHEP::RandFlat::shoot().
double CLHEP::RandBreitWigner::shootM2 (HepRandomEngine * anEngine, double a, double b, double c) static
Definition at line 156 of file RandBreitWigner.cc.
View newest version in sPHENIX GitHub at line 156 of file RandBreitWigner.cc
References max, CLHEP::RandFlat::shoot(), and tmp.
Member Data Documentation
double CLHEP::RandBreitWigner::defaultA private
Definition at line 136 of file RandBreitWigner.h.
View newest version in sPHENIX GitHub at line 136 of file RandBreitWigner.h
Referenced by fire(), fireArray(), fireM2(), get(), operator()(), and put().
double CLHEP::RandBreitWigner::defaultB private
Definition at line 137 of file RandBreitWigner.h.
View newest version in sPHENIX GitHub at line 137 of file RandBreitWigner.h
Referenced by fire(), fireArray(), fireM2(), get(), operator()(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandBreitWigner::localEngine private
Definition at line 135 of file RandBreitWigner.h.
View newest version in sPHENIX GitHub at line 135 of file RandBreitWigner.h
Referenced by engine(), fire(), and fireM2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandBreitWigner.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandBreitWigner.cc