ECCE @ EIC Software: G4tgbMaterialMixture Class Reference
G4tgbMaterialMixture Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixture.hh>
Public Member Functions
G4tgbMaterialMixture ()
virtual ~G4tgbMaterialMixture ()
virtual const G4String & GetComponent (G4int i) const
virtual G4double GetFraction (G4int i) const
G4tgbMaterialMixture & operator= (const G4tgbMaterialMixture &)
Public Member Functions inherited from G4tgbMaterial
G4tgbMaterial ()
virtual ~G4tgbMaterial ()
G4tgbMaterial (G4tgrMaterial *tgr)
virtual G4Material * BuildG4Material ()=0
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfMaterials () const
G4double GetA () const
G4double GetZ () const
const G4String & GetType () const
G4tgrMaterial * GetTgrMate () const
Protected Member Functions
virtual void TransformToFractionsByWeight ()
Additional Inherited Members
Protected Attributes inherited from G4tgbMaterial
G4tgrMaterial * theTgrMate
G4Material * theG4Mate
Detailed Description
Definition at line 49 of file G4tgbMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialMixture.hh
Constructor & Destructor Documentation
G4tgbMaterialMixture::G4tgbMaterialMixture ()
Definition at line 38 of file G4tgbMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 38 of file G4tgbMaterialMixture.cc
G4tgbMaterialMixture::~G4tgbMaterialMixture () virtual
Definition at line 44 of file G4tgbMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 44 of file G4tgbMaterialMixture.cc
Member Function Documentation
const G4String & G4tgbMaterialMixture::GetComponent (G4int i) const virtual
Definition at line 50 of file G4tgbMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 50 of file G4tgbMaterialMixture.cc
References G4tgrMaterial::GetComponent(), and G4tgbMaterial::theTgrMate.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
G4double G4tgbMaterialMixture::GetFraction (G4int i) const virtual
Definition at line 57 of file G4tgbMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgbMaterialMixture.cc
References G4tgrMaterial::GetFraction(), and G4tgbMaterial::theTgrMate.
Referenced by G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
G4tgbMaterialMixture & G4tgbMaterialMixture::operator= (const G4tgbMaterialMixture &)
Definition at line 65 of file G4tgbMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 65 of file G4tgbMaterialMixture.cc
void G4tgbMaterialMixture::TransformToFractionsByWeight () protected virtual
Reimplemented in G4tgbMaterialMixtureByNoAtoms, and G4tgbMaterialMixtureByVolume.
Definition at line 72 of file G4tgbMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 72 of file G4tgbMaterialMixture.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixture.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterialMixture.cc