ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_energyAngular.cc File Reference
MCGIDI_energyAngular.cc File Reference
#include <string.h>
#include "MCGIDI_fromTOM.h"
#include "MCGIDI.h"
#include "MCGIDI_misc.h"
Functions
static int MCGIDI_energyAngular_linear_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
MCGIDI_energyAngular * MCGIDI_energyAngular_new (statusMessageReporting *smr)
int MCGIDI_energyAngular_initialize (statusMessageReporting *, MCGIDI_energyAngular *energyAngular)
MCGIDI_energyAngular * MCGIDI_energyAngular_free (statusMessageReporting *smr, MCGIDI_energyAngular *energyAngular)
int MCGIDI_energyAngular_release (statusMessageReporting *smr, MCGIDI_energyAngular *energyAngular)
int MCGIDI_energyAngular_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
int MCGIDI_energyAngular_sampleDistribution (statusMessageReporting *smr, MCGIDI_distribution *distribution, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
Function Documentation
MCGIDI_energyAngular* MCGIDI_energyAngular_free (statusMessageReporting * smr, MCGIDI_energyAngular * energyAngular)
Definition at line 39 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_energyAngular.cc
References MCGIDI_energyAngular_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_release(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_energyAngular_new().
int MCGIDI_energyAngular_initialize (statusMessageReporting * , MCGIDI_energyAngular * energyAngular)
Definition at line 31 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_energyAngular.cc
Referenced by MCGIDI_energyAngular_new(), and MCGIDI_energyAngular_release().
static int MCGIDI_energyAngular_linear_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution) static
Definition at line 89 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 89 of file MCGIDI_energyAngular.cc
References MCGIDI_pdfsOfXGivenW_s::dist, e, MCGIDI_distribution_s::energyAngular, check_license::err(), MCGIDI_energyAngular_s::frame, MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, xDataTOM_W_XYs_s::length, xDataTOM_V_W_XYs_s::length, MCGIDI_distributionType_energyAngular_e, MCGIDI_energyAngular_free(), MCGIDI_energyAngular_new(), MCGIDI_fromTOM_interpolation(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), nfu_Okay, nfu_statusMessage(), norm, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_energyAngular_s::pdfOfEpGivenE, MCGIDI_energyAngular_s::pdfOfMuGivenEAndEp, ptwXY_add_double(), ptwXY_free(), ptwXY_integrateDomain(), ptwXY_new(), ptwXY_setValueAtX(), smr_isOk(), smr_malloc2, smr_setReportError2, smr_unknownID, xDataTOM_V_W_XYs_s::subAxes, MCGIDI_distribution_s::type, xDataTOM_XYs_s::value, xDataTOM_W_XYs_s::value, xDataTOM_V_W_XYs_s::W_XYs, MCGIDI_pdfsOfXGivenW_s::Ws, xDataTOM_frame_invalid, xDataTOM_subAxes_getUnit(), xDataTOME_getOneElementByName(), xDataTOME_getXDataIfID(), xDataTOM_W_XYs_s::XYs, and y.
Referenced by MCGIDI_energyAngular_parseFromTOM().
MCGIDI_energyAngular* MCGIDI_energyAngular_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_energyAngular.cc
References MCGIDI_energyAngular_free(), MCGIDI_energyAngular_initialize(), and smr_malloc2.
Referenced by MCGIDI_energyAngular_linear_parseFromTOM().
int MCGIDI_energyAngular_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 64 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 64 of file MCGIDI_energyAngular.cc
References check_license::err(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM(), smr_setReportError2, smr_unknownID, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
int MCGIDI_energyAngular_release (statusMessageReporting * smr, MCGIDI_energyAngular * energyAngular)
Definition at line 48 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI_energyAngular.cc
References MCGIDI_energyAngular_initialize(), MCGIDI_sampling_pdfsOfXGivenW_release(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_energyAngular_s::pdfOfEpGivenE, MCGIDI_energyAngular_s::pdfOfMuGivenEAndEp, and smr_freeMemory().
Referenced by MCGIDI_energyAngular_free().
int MCGIDI_energyAngular_sampleDistribution (statusMessageReporting * smr, MCGIDI_distribution * distribution, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 180 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 180 of file MCGIDI_energyAngular.cc
References MCGIDI_distribution_s::energyAngular, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_energyAngular_s::frame, MCGIDI_sampling_doubleDistribution(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_energyAngular_s::pdfOfEpGivenE, and MCGIDI_energyAngular_s::pdfOfMuGivenEAndEp.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().