ECCE @ EIC Software: G4HelixMixedStepper Class Reference
G4HelixMixedStepper Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4HelixMixedStepper.hh>
Public Member Functions
G4HelixMixedStepper (G4Mag_EqRhs *EqRhs, G4int StepperNumber=-1, G4double Angle_threshold=-1.0)
~G4HelixMixedStepper ()
void Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[])
void DumbStepper (const G4double y[], G4ThreeVector Bfld, G4double h, G4double yout[])
G4double DistChord () const
void SetVerbose (G4int newvalue)
void PrintCalls ()
G4MagIntegratorStepper * SetupStepper (G4Mag_EqRhs *EqRhs, G4int StepperName)
void SetAngleThreshold (G4double val)
G4double GetAngleThreshold ()
G4int IntegratorOrder () const
Public Member Functions inherited from G4MagHelicalStepper
G4MagHelicalStepper (G4Mag_EqRhs *EqRhs)
virtual ~G4MagHelicalStepper ()
G4MagHelicalStepper (const G4MagHelicalStepper &)=delete
G4MagHelicalStepper & operator= (const G4MagHelicalStepper &)=delete
G4double DistChord () const
Public Member Functions inherited from G4MagIntegratorStepper
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, G4bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
G4MagIntegratorStepper (const G4MagIntegratorStepper &)=delete
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)=delete
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
G4bool IsFSAL () const
Private Attributes
G4MagIntegratorStepper * fRK4Stepper = nullptr
G4int fStepperNumber = -1
G4double fAngle_threshold = -1.0
G4int fVerbose = 0
G4int fNumCallsRK4 = 0
G4int fNumCallsHelix = 0
Additional Inherited Members
Protected Member Functions inherited from G4MagHelicalStepper
void LinearStep (const G4double yIn[], G4double h, G4double yHelix[]) const
void AdvanceHelix (const G4double yIn[], G4ThreeVector Bfld, G4double h, G4double yHelix[], G4double yHelix2[]=0)
void MagFieldEvaluate (const G4double y[], G4ThreeVector &Bfield)
G4double GetInverseCurve (const G4double Momentum, const G4double Bmag)
void SetAngCurve (const G4double Ang)
G4double GetAngCurve () const
void SetCurve (const G4double Curve)
G4double GetCurve () const
void SetRadHelix (const G4double Rad)
G4double GetRadHelix () const
Detailed Description
Definition at line 62 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HelixMixedStepper.hh
Constructor & Destructor Documentation
G4HelixMixedStepper::G4HelixMixedStepper (G4Mag_EqRhs * EqRhs, G4int StepperNumber = -1, G4double Angle_threshold = -1.0)
Definition at line 65 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 65 of file G4HelixMixedStepper.cc
References fAngle_threshold, fRK4Stepper, fStepperNumber, pi, and SetupStepper().
G4HelixMixedStepper::~G4HelixMixedStepper ()
Definition at line 91 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 91 of file G4HelixMixedStepper.cc
References fRK4Stepper, fVerbose, and PrintCalls().
Member Function Documentation
G4double G4HelixMixedStepper::DistChord () const virtual
Implements G4MagIntegratorStepper.
Definition at line 178 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 178 of file G4HelixMixedStepper.cc
References G4MagHelicalStepper::GetAngCurve(), G4MagHelicalStepper::GetRadHelix(), pi, and twopi.
void G4HelixMixedStepper::DumbStepper (const G4double y[], G4ThreeVector Bfld, G4double h, G4double yout[]) virtual
Implements G4MagHelicalStepper.
Definition at line 169 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 169 of file G4HelixMixedStepper.cc
References G4MagHelicalStepper::AdvanceHelix().
G4double G4HelixMixedStepper::GetAngleThreshold () inline
Definition at line 99 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 99 of file G4HelixMixedStepper.hh
References fAngle_threshold.
G4int G4HelixMixedStepper::IntegratorOrder () const inline virtual
Implements G4MagIntegratorStepper.
Definition at line 100 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 100 of file G4HelixMixedStepper.hh
void G4HelixMixedStepper::PrintCalls ()
Definition at line 207 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 207 of file G4HelixMixedStepper.cc
References fNumCallsHelix, fNumCallsRK4, G4cout, and G4endl.
Referenced by ~G4HelixMixedStepper().
void G4HelixMixedStepper::SetAngleThreshold (G4double val) inline
Definition at line 98 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 98 of file G4HelixMixedStepper.hh
References fAngle_threshold.
G4MagIntegratorStepper * G4HelixMixedStepper::SetupStepper (G4Mag_EqRhs * EqRhs, G4int StepperName)
Definition at line 216 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 216 of file G4HelixMixedStepper.cc
References fVerbose, G4cout, and G4endl.
Referenced by G4HelixMixedStepper().
void G4HelixMixedStepper::SetVerbose (G4int newvalue) inline
Definition at line 91 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HelixMixedStepper.hh
References fVerbose.
void G4HelixMixedStepper::Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[]) virtual
Reimplemented from G4MagHelicalStepper.
Definition at line 98 of file G4HelixMixedStepper.cc.
View newest version in sPHENIX GitHub at line 98 of file G4HelixMixedStepper.cc
References kdfinder::abs(), G4MagHelicalStepper::AdvanceHelix(), fAngle_threshold, fNumCallsHelix, fNumCallsRK4, fRK4Stepper, G4MagHelicalStepper::GetInverseCurve(), CLHEP::Hep3Vector::mag(), G4MagHelicalStepper::MagFieldEvaluate(), G4MagHelicalStepper::SetAngCurve(), G4MagHelicalStepper::SetCurve(), and G4MagIntegratorStepper::Stepper().
Member Data Documentation
G4double G4HelixMixedStepper::fAngle_threshold = -1.0 private
Definition at line 109 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 109 of file G4HelixMixedStepper.hh
Referenced by G4HelixMixedStepper(), GetAngleThreshold(), SetAngleThreshold(), and Stepper().
G4int G4HelixMixedStepper::fNumCallsHelix = 0 private
Definition at line 117 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 117 of file G4HelixMixedStepper.hh
Referenced by PrintCalls(), and Stepper().
G4int G4HelixMixedStepper::fNumCallsRK4 = 0 private
Definition at line 116 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 116 of file G4HelixMixedStepper.hh
Referenced by PrintCalls(), and Stepper().
G4MagIntegratorStepper* G4HelixMixedStepper::fRK4Stepper = nullptr private
Definition at line 104 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 104 of file G4HelixMixedStepper.hh
Referenced by G4HelixMixedStepper(), Stepper(), and ~G4HelixMixedStepper().
G4int G4HelixMixedStepper::fStepperNumber = -1 private
Definition at line 106 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 106 of file G4HelixMixedStepper.hh
Referenced by G4HelixMixedStepper().
G4int G4HelixMixedStepper::fVerbose = 0 private
Definition at line 114 of file G4HelixMixedStepper.hh.
View newest version in sPHENIX GitHub at line 114 of file G4HelixMixedStepper.hh
Referenced by SetupStepper(), SetVerbose(), and ~G4HelixMixedStepper().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4HelixMixedStepper.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4HelixMixedStepper.cc