ECCE @ EIC Software: G4WeightWindowBiasing Class Reference
G4WeightWindowBiasing Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4WeightWindowBiasing.hh>
Public Member Functions
G4WeightWindowBiasing (const G4String &name="NoParallelWP")
G4WeightWindowBiasing (G4GeometrySampler *mgs, G4VWeightWindowAlgorithm *wwAlg, G4PlaceOfAction placeOfAction, const G4String &name="NoParallelWP")
virtual ~G4WeightWindowBiasing ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
G4WeightWindowBiasing & operator= (const G4WeightWindowBiasing &right)
G4WeightWindowBiasing (const G4WeightWindowBiasing &)
Private Attributes
G4GeometrySampler * fGeomSampler
G4VWeightWindowAlgorithm * fWWalg
G4PlaceOfAction fPlaceOfAction
G4bool paraFlag
G4String paraName
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 41 of file G4WeightWindowBiasing.hh.
View newest version in sPHENIX GitHub at line 41 of file G4WeightWindowBiasing.hh
Constructor & Destructor Documentation
G4WeightWindowBiasing::G4WeightWindowBiasing (const G4String & name = "NoParallelWP")
Definition at line 59 of file G4WeightWindowBiasing.cc.
View newest version in sPHENIX GitHub at line 59 of file G4WeightWindowBiasing.cc
G4WeightWindowBiasing::G4WeightWindowBiasing (G4GeometrySampler * mgs, G4VWeightWindowAlgorithm * wwAlg, G4PlaceOfAction placeOfAction, const G4String & name = "NoParallelWP")
Definition at line 65 of file G4WeightWindowBiasing.cc.
View newest version in sPHENIX GitHub at line 65 of file G4WeightWindowBiasing.cc
References paraFlag, and paraName.
G4WeightWindowBiasing::~G4WeightWindowBiasing () virtual
Definition at line 76 of file G4WeightWindowBiasing.cc.
View newest version in sPHENIX GitHub at line 76 of file G4WeightWindowBiasing.cc
G4WeightWindowBiasing::G4WeightWindowBiasing (const G4WeightWindowBiasing &) private
Member Function Documentation
void G4WeightWindowBiasing::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 81 of file G4WeightWindowBiasing.cc.
View newest version in sPHENIX GitHub at line 81 of file G4WeightWindowBiasing.cc
void G4WeightWindowBiasing::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 86 of file G4WeightWindowBiasing.cc.
View newest version in sPHENIX GitHub at line 86 of file G4WeightWindowBiasing.cc
References G4GeometrySampler::AddProcess(), G4GeometrySampler::Configure(), fGeomSampler, fPlaceOfAction, fWWalg, G4cout, G4endl, G4WeightWindowStore::GetInstance(), paraFlag, paraName, G4GeometrySampler::PrepareWeightWindow(), and G4GeometrySampler::SetParallel().
G4WeightWindowBiasing& G4WeightWindowBiasing::operator= (const G4WeightWindowBiasing & right) private
Member Data Documentation
G4GeometrySampler* G4WeightWindowBiasing::fGeomSampler private
Definition at line 65 of file G4WeightWindowBiasing.hh.
View newest version in sPHENIX GitHub at line 65 of file G4WeightWindowBiasing.hh
Referenced by ConstructProcess().
G4PlaceOfAction G4WeightWindowBiasing::fPlaceOfAction private
Definition at line 67 of file G4WeightWindowBiasing.hh.
View newest version in sPHENIX GitHub at line 67 of file G4WeightWindowBiasing.hh
Referenced by ConstructProcess().
G4VWeightWindowAlgorithm* G4WeightWindowBiasing::fWWalg private
Definition at line 66 of file G4WeightWindowBiasing.hh.
View newest version in sPHENIX GitHub at line 66 of file G4WeightWindowBiasing.hh
Referenced by ConstructProcess().
G4bool G4WeightWindowBiasing::paraFlag private
Definition at line 69 of file G4WeightWindowBiasing.hh.
View newest version in sPHENIX GitHub at line 69 of file G4WeightWindowBiasing.hh
Referenced by ConstructProcess(), and G4WeightWindowBiasing().
G4String G4WeightWindowBiasing::paraName private
Definition at line 70 of file G4WeightWindowBiasing.hh.
View newest version in sPHENIX GitHub at line 70 of file G4WeightWindowBiasing.hh
Referenced by ConstructProcess(), and G4WeightWindowBiasing().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4WeightWindowBiasing.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/src/G4WeightWindowBiasing.cc