ECCE @ EIC Software: CLHEP::DualRand Class Reference
CLHEP::DualRand Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/DualRand.h>
Classes
class IntegerCong
class Tausworthe
Public Member Functions
DualRand ()
DualRand (long seed)
DualRand (std::istream &is)
DualRand (int rowIndex, int colIndex)
virtual ~DualRand ()
double flat ()
void flatArray (const int size, double *vect)
void setSeed (long seed, int)
void setSeeds (const long *seeds, int)
void saveStatus (const char filename[]="DualRand.conf") const
void restoreStatus (const char filename[]="DualRand.conf")
void showStatus () const
operator double ()
operator float ()
operator unsigned int ()
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Public Attributes
static const unsigned int VECTOR_STATE_SIZE = 9
Private Attributes
int numEngines
Tausworthe tausworthe
IntegerCong integerCong
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Definition at line 49 of file DualRand.h.
View newest version in sPHENIX GitHub at line 49 of file DualRand.h
Constructor & Destructor Documentation
CLHEP::DualRand::DualRand ()
Definition at line 76 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 76 of file DualRand.cc
References CLHEP::HepRandomEngine::theSeed.
CLHEP::DualRand::DualRand (long seed)
Definition at line 85 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 85 of file DualRand.cc
References seed, and CLHEP::HepRandomEngine::theSeed.
CLHEP::DualRand::DualRand (std::istream & is)
Definition at line 94 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 94 of file DualRand.cc
CLHEP::DualRand::DualRand (int rowIndex, int colIndex)
Definition at line 101 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 101 of file DualRand.cc
References CLHEP::HepRandomEngine::theSeed.
CLHEP::DualRand::~DualRand () virtual
Definition at line 110 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 110 of file DualRand.cc
Member Function Documentation
std::string CLHEP::DualRand::beginTag () static
Definition at line 244 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 244 of file DualRand.cc
static std::string CLHEP::DualRand::engineName () inline static
Definition at line 96 of file DualRand.h.
View newest version in sPHENIX GitHub at line 96 of file DualRand.h
Referenced by restoreStatus().
double CLHEP::DualRand::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 112 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 112 of file DualRand.cc
References integerCong, CLHEP::HepRandomEngine::nearlyTwoToMinus_54(), t, tausworthe, CLHEP::HepRandomEngine::twoToMinus_32(), and CLHEP::HepRandomEngine::twoToMinus_53().
Referenced by flatArray().
void CLHEP::DualRand::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 121 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 121 of file DualRand.cc
References flat().
std::istream & CLHEP::DualRand::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 227 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 227 of file DualRand.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::DualRand::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 284 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 284 of file DualRand.cc
References getState(), and VECTOR_STATE_SIZE.
std::istream & CLHEP::DualRand::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 248 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 248 of file DualRand.cc
References CLHEP::DualRand::Tausworthe::get(), CLHEP::DualRand::IntegerCong::get(), integerCong, CLHEP::MarkerLen, CLHEP::possibleKeywordInput(), tausworthe, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
Referenced by get(), and restoreStatus().
bool CLHEP::DualRand::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 298 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 298 of file DualRand.cc
References CLHEP::DualRand::Tausworthe::get(), CLHEP::DualRand::IntegerCong::get(), integerCong, and tausworthe.
std::string CLHEP::DualRand::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 68 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 68 of file DualRand.cc
CLHEP::DualRand::operator double () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 195 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 195 of file DualRand.cc
References G4AblaRandom::flat().
CLHEP::DualRand::operator float () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 199 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 199 of file DualRand.cc
CLHEP::DualRand::operator unsigned int () virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 205 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 205 of file DualRand.cc
std::ostream & CLHEP::DualRand::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 209 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 209 of file DualRand.cc
References put(), and v.
std::vector< unsigned long > CLHEP::DualRand::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 219 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 219 of file DualRand.cc
References integerCong, CLHEP::DualRand::Tausworthe::put(), CLHEP::DualRand::IntegerCong::put(), tausworthe, and v.
Referenced by put(), and saveStatus().
void CLHEP::DualRand::restoreStatus (const char filename[] = "DualRand.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 149 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 149 of file DualRand.cc
References CLHEP::HepRandomEngine::checkFile(), engineName(), CLHEP::DualRand::Tausworthe::get(), CLHEP::DualRand::IntegerCong::get(), getState(), in, integerCong, CLHEP::possibleKeywordInput(), tausworthe, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
void CLHEP::DualRand::saveStatus (const char filename[] = "DualRand.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 138 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 138 of file DualRand.cc
References put(), and v.
void CLHEP::DualRand::setSeed (long seed, int) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 127 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 127 of file DualRand.cc
References integerCong, seed, tausworthe, and CLHEP::HepRandomEngine::theSeed.
Referenced by setSeeds().
void CLHEP::DualRand::setSeeds (const long * seeds, int) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 133 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 133 of file DualRand.cc
References setSeed(), and CLHEP::HepRandomEngine::theSeeds.
void CLHEP::DualRand::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 180 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 180 of file DualRand.cc
References integerCong, gammaraytel::pr, CLHEP::DualRand::Tausworthe::put(), CLHEP::DualRand::IntegerCong::put(), tausworthe, and CLHEP::HepRandomEngine::theSeed.
Member Data Documentation
IntegerCong CLHEP::DualRand::integerCong private
Definition at line 137 of file DualRand.h.
View newest version in sPHENIX GitHub at line 137 of file DualRand.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
int CLHEP::DualRand::numEngines private
Definition at line 135 of file DualRand.h.
View newest version in sPHENIX GitHub at line 135 of file DualRand.h
Tausworthe CLHEP::DualRand::tausworthe private
Definition at line 136 of file DualRand.h.
View newest version in sPHENIX GitHub at line 136 of file DualRand.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), and showStatus().
const unsigned int CLHEP::DualRand::VECTOR_STATE_SIZE = 9 static
Definition at line 102 of file DualRand.h.
View newest version in sPHENIX GitHub at line 102 of file DualRand.h
Referenced by get(), getState(), and restoreStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/DualRand.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/DualRand.cc