ECCE @ EIC Software: G4ExcitedXiConstructor Class Reference
G4ExcitedXiConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedXiConstructor.hh>
Public Types
enum { NStates = 5 }
enum { NumberOfDecayModes = 4 }
Public Member Functions
G4ExcitedXiConstructor ()
virtual ~G4ExcitedXiConstructor ()
Public Member Functions inherited from G4ExcitedBaryonConstructor
G4ExcitedBaryonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedBaryonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Member Functions
virtual G4bool Exist (G4int)
virtual G4int GetQuarkContents (G4int, G4int)
virtual G4String GetName (G4int iIso3, G4int iState)
virtual G4String GetMultipletName (G4int iState)
virtual G4double GetMass (G4int state, G4int iso)
virtual G4double GetWidth (G4int state, G4int iso)
virtual G4int GetiSpin (G4int iState)
virtual G4int GetiParity (G4int iState)
virtual G4int GetEncodingOffset (G4int iState)
virtual G4DecayTable * CreateDecayTable (const G4String &name, G4int iIso3, G4int iState, G4bool fAnti=false)
Protected Member Functions inherited from G4ExcitedBaryonConstructor
virtual void ConstructParticle (G4int indexOfState)
virtual void ConstructAntiParticle (G4int indexOfState)
virtual G4double GetCharge (G4int iIsoSpin3)
virtual G4int GetEncoding (G4int iIsoSpin3, G4int idxState)
Private Types
enum { XiIsoSpin = 1 }
enum { XiPi =0, XiGamma =1, LambdaK =2, SigmaK =3 }
Private Member Functions
G4DecayTable * AddXiPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddXiGammaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaKMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddSigmaKMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
Static Private Attributes
static const char * name [NStates]
static const G4double mass [NStates]
static const G4double width [NStates]
static const G4int iSpin [NStates]
static const G4int iParity [NStates]
static const G4int encodingOffset [NStates]
static const G4double bRatio [NStates][NumberOfDecayModes]
Additional Inherited Members
Protected Attributes inherited from G4ExcitedBaryonConstructor
G4int NumberOfStates
G4int iIsoSpin
const G4String type
const G4int iConjugation
const G4int iGParity
const G4int leptonNumber
const G4int baryonNumber
Detailed Description
Definition at line 42 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ExcitedXiConstructor.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
NStates
Definition at line 77 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ExcitedXiConstructor.hh
anonymous enum private
Enumerator:
XiIsoSpin
Definition at line 79 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ExcitedXiConstructor.hh
anonymous enum
Enumerator:
NumberOfDecayModes
Definition at line 90 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ExcitedXiConstructor.hh
anonymous enum private
Enumerator:
XiPi
XiGamma
LambdaK
SigmaK
Definition at line 92 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ExcitedXiConstructor.hh
Constructor & Destructor Documentation
G4ExcitedXiConstructor::G4ExcitedXiConstructor ()
Definition at line 46 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ExcitedXiConstructor.cc
G4ExcitedXiConstructor::~G4ExcitedXiConstructor () virtual
Definition at line 52 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ExcitedXiConstructor.cc
Member Function Documentation
G4DecayTable * G4ExcitedXiConstructor::AddLambdaKMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 109 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 109 of file G4ExcitedXiConstructor.cc
References G4DecayTable::Insert(), G4InuclParticleNames::lambda, and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedXiConstructor::AddSigmaKMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 150 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 150 of file G4ExcitedXiConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedXiConstructor::AddXiGammaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 86 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ExcitedXiConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedXiConstructor::AddXiPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 209 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 209 of file G4ExcitedXiConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedXiConstructor::CreateDecayTable (const G4String & name, G4int iIso3, G4int iState, G4bool fAnti = false) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 56 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedXiConstructor.cc
References AddLambdaKMode(), AddSigmaKMode(), AddXiGammaMode(), AddXiPiMode(), bRatio, LambdaK, SigmaK, XiGamma, and XiPi.
virtual G4bool G4ExcitedXiConstructor::Exist (G4int) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 52 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ExcitedXiConstructor.hh
G4int G4ExcitedXiConstructor::GetEncodingOffset (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 111 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ExcitedXiConstructor.hh
References encodingOffset.
G4int G4ExcitedXiConstructor::GetiParity (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 105 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ExcitedXiConstructor.hh
References iParity.
G4int G4ExcitedXiConstructor::GetiSpin (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 99 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ExcitedXiConstructor.hh
References iSpin.
G4double G4ExcitedXiConstructor::GetMass (G4int state, G4int iso) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 284 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 284 of file G4ExcitedXiConstructor.cc
References Acts::UnitConstants::fm, GeV, and mass.
G4String G4ExcitedXiConstructor::GetMultipletName (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 139 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ExcitedXiConstructor.hh
G4String G4ExcitedXiConstructor::GetName (G4int iIso3, G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 145 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ExcitedXiConstructor.hh
References particle.
G4int G4ExcitedXiConstructor::GetQuarkContents (G4int iQ, G4int iIso3) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 117 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ExcitedXiConstructor.hh
G4double G4ExcitedXiConstructor::GetWidth (G4int state, G4int iso) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 293 of file G4ExcitedXiConstructor.cc.
View newest version in sPHENIX GitHub at line 293 of file G4ExcitedXiConstructor.cc
References MeV, and width.
Member Data Documentation
const G4double G4ExcitedXiConstructor::bRatio static private
Initial value:
=
{
   {  0.98, 0.02,  0.0,  0.0},
   {  0.10,  0.0, 0.70, 0.20},
   {  0.15,  0.0, 0.70, 0.15},
   {  0.25,  0.0, 0.50, 0.25},
   {  0.10,  0.0, 0.20, 0.70}
}
Definition at line 94 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ExcitedXiConstructor.hh
Referenced by CreateDecayTable().
const G4int G4ExcitedXiConstructor::encodingOffset static private
Initial value:
= {
      0, 20000, 10000, 30000, 10000
}
Definition at line 87 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ExcitedXiConstructor.hh
Referenced by GetEncodingOffset().
const G4int G4ExcitedXiConstructor::iParity static private
Initial value:
= {
   +1,  +1,   -1,  -1,  +1
}
Definition at line 86 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ExcitedXiConstructor.hh
Referenced by GetiParity().
const G4int G4ExcitedXiConstructor::iSpin static private
Initial value:
= {
    3,   3,   3,   3,   5
}
Definition at line 85 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitedXiConstructor.hh
Referenced by GetiSpin().
const G4double G4ExcitedXiConstructor::mass static private
Initial value:
= {
 1.5318*GeV, 1.690*GeV, 1.823*GeV, 1.950*GeV,  2.025*GeV
}
Definition at line 83 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ExcitedXiConstructor.hh
Referenced by GetMass().
const char * G4ExcitedXiConstructor::name static private
Initial value:
= {
   "xi(1530)", "xi(1690)", "xi(1820)", "xi(1950)", "xi(2030)"
}
Definition at line 82 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ExcitedXiConstructor.hh
const G4double G4ExcitedXiConstructor::width static private
Initial value:
= {
    9.1*MeV,  50.0*MeV,  24.0*MeV,  60.0*MeV,  20.0*MeV
}
Definition at line 84 of file G4ExcitedXiConstructor.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ExcitedXiConstructor.hh
Referenced by GetWidth().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedXiConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ExcitedXiConstructor.cc