ECCE @ EIC Software: G4FissLib Class Reference
G4FissLib Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4FissLib.hh>
Public Member Functions
G4FissLib ()
~G4FissLib ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
const std::pair< G4double,
G4double > GetFatalEnergyCheckLevels () const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4FissionLibrary theLibrary
G4double * xSec
G4ParticleHPChannel * theFission
G4String dirName
G4int numEle
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 132 of file G4FissLib.hh.
View newest version in sPHENIX GitHub at line 132 of file G4FissLib.hh
Constructor & Destructor Documentation
G4FissLib::G4FissLib ()
Definition at line 64 of file G4FissLib.cc.
View newest version in sPHENIX GitHub at line 64 of file G4FissLib.cc
References dirName, G4cout, G4endl, G4Element::GetElementTable(), G4Element::GetNumberOfElements(), G4ParticleHPChannel::Init(), MeV, numEle, G4ParticleHPChannel::Register(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theFission, and theLibrary.
G4FissLib::~G4FissLib ()
Definition at line 90 of file G4FissLib.cc.
View newest version in sPHENIX GitHub at line 90 of file G4FissLib.cc
References theFission.
Member Function Documentation
G4HadFinalState * G4FissLib::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 96 of file G4FissLib.cc.
View newest version in sPHENIX GitHub at line 96 of file G4FissLib.cc
References G4ParticleHPChannel::ApplyYourself(), G4ParticleHPManager::CloseReactionWhiteBoard(), G4UniformRand, G4Material::GetElement(), G4Element::GetElementTable(), G4Element::GetIndex(), G4ParticleHPManager::GetInstance(), G4Element::GetIsotope(), G4HadProjectile::GetMaterial(), G4Isotope::GetN(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4ParticleHPManager::GetReactionWhiteBoard(), G4ParticleHPReactionWhiteBoard::GetTargA(), G4Material::GetTemperature(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4Material::GetVecNbOfAtomsPerVolume(), G4ParticleHPChannel::GetXsec(), n, G4ParticleHPManager::OpenReactionWhiteBoard(), G4Nucleus::SetIsotope(), G4Nucleus::SetParameters(), sum, theFission, and xSec.
const std::pair< G4double, G4double > G4FissLib::GetFatalEnergyCheckLevels () const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 148 of file G4FissLib.cc.
View newest version in sPHENIX GitHub at line 148 of file G4FissLib.cc
References GeV, and perCent.
Member Data Documentation
G4String G4FissLib::dirName private
Definition at line 148 of file G4FissLib.hh.
View newest version in sPHENIX GitHub at line 148 of file G4FissLib.hh
Referenced by G4FissLib().
G4int G4FissLib::numEle private
Definition at line 149 of file G4FissLib.hh.
View newest version in sPHENIX GitHub at line 149 of file G4FissLib.hh
Referenced by G4FissLib().
G4ParticleHPChannel* G4FissLib::theFission private
Definition at line 147 of file G4FissLib.hh.
View newest version in sPHENIX GitHub at line 147 of file G4FissLib.hh
Referenced by ApplyYourself(), G4FissLib(), and ~G4FissLib().
G4FissionLibrary G4FissLib::theLibrary private
Definition at line 143 of file G4FissLib.hh.
View newest version in sPHENIX GitHub at line 143 of file G4FissLib.hh
Referenced by G4FissLib().
G4double* G4FissLib::xSec private
Definition at line 146 of file G4FissLib.hh.
View newest version in sPHENIX GitHub at line 146 of file G4FissLib.hh
Referenced by ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4FissLib.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4FissLib.cc