ECCE @ EIC Software: LXeUserTrackInformation Class Reference
LXeUserTrackInformation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeUserTrackInformation.hh>
Public Member Functions
LXeUserTrackInformation ()
virtual ~LXeUserTrackInformation ()
void SetTrackStatusFlags (int s)
void AddTrackStatusFlag (int s)
int GetTrackStatus () const
void IncReflections ()
G4int GetReflectionCount () const
void SetForceDrawTrajectory (G4bool b)
G4bool GetForceDrawTrajectory ()
virtual void Print () const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Private Attributes
int fStatus
G4int fReflections
G4bool fForcedraw
Additional Inherited Members
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Definition at line 50 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 50 of file LXeUserTrackInformation.hh
Constructor & Destructor Documentation
LXeUserTrackInformation::LXeUserTrackInformation ()
Definition at line 35 of file LXeUserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 35 of file LXeUserTrackInformation.cc
LXeUserTrackInformation::~LXeUserTrackInformation () virtual
Definition at line 40 of file LXeUserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 40 of file LXeUserTrackInformation.cc
Member Function Documentation
void LXeUserTrackInformation::AddTrackStatusFlag (int s)
Definition at line 44 of file LXeUserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 44 of file LXeUserTrackInformation.cc
References active, fStatus, and inactive.
Referenced by LXeSteppingAction::UserSteppingAction().
G4bool LXeUserTrackInformation::GetForceDrawTrajectory () inline
Definition at line 69 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 69 of file LXeUserTrackInformation.hh
References fForcedraw.
Referenced by LXeTrackingAction::PostUserTrackingAction().
G4int LXeUserTrackInformation::GetReflectionCount () const inline
Definition at line 66 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 66 of file LXeUserTrackInformation.hh
References fReflections.
int LXeUserTrackInformation::GetTrackStatus () const inline
Definition at line 63 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 63 of file LXeUserTrackInformation.hh
References fStatus.
Referenced by LXeTrackingAction::PostUserTrackingAction(), and LXePMTSD::ProcessHits_constStep().
void LXeUserTrackInformation::IncReflections () inline
Definition at line 65 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 65 of file LXeUserTrackInformation.hh
References fReflections.
Referenced by LXeSteppingAction::UserSteppingAction().
virtual void LXeUserTrackInformation::Print (void) const inline virtual
Reimplemented from G4VUserTrackInformation.
Definition at line 71 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 71 of file LXeUserTrackInformation.hh
void LXeUserTrackInformation::SetForceDrawTrajectory (G4bool b) inline
Definition at line 68 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 68 of file LXeUserTrackInformation.hh
References b, and fForcedraw.
Referenced by LXeSteppingAction::UserSteppingAction().
void LXeUserTrackInformation::SetTrackStatusFlags (int s) inline
Definition at line 58 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 58 of file LXeUserTrackInformation.hh
References fStatus.
Member Data Documentation
G4bool LXeUserTrackInformation::fForcedraw private
Definition at line 77 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 77 of file LXeUserTrackInformation.hh
Referenced by GetForceDrawTrajectory(), and SetForceDrawTrajectory().
G4int LXeUserTrackInformation::fReflections private
Definition at line 76 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 76 of file LXeUserTrackInformation.hh
Referenced by GetReflectionCount(), and IncReflections().
int LXeUserTrackInformation::fStatus private
Definition at line 71 of file LXeUserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 71 of file LXeUserTrackInformation.hh
Referenced by AddTrackStatusFlag(), GetTrackStatus(), and SetTrackStatusFlags().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeUserTrackInformation.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeUserTrackInformation.cc