ECCE @ EIC Software: F04EventAction Class Reference
F04EventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04EventAction.hh>
Public Member Functions
F04EventAction (F04RunAction *)
virtual ~F04EventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
G4int GetEventNo ()
void SetEventVerbose (G4int)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
F04RunAction * fRunaction
F04EventActionMessenger * fEventMessenger
G4int fVerboseLevel
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 40 of file F04EventAction.hh.
View newest version in sPHENIX GitHub at line 40 of file F04EventAction.hh
Constructor & Destructor Documentation
F04EventAction::F04EventAction (F04RunAction * runAction)
Definition at line 47 of file F04EventAction.cc.
View newest version in sPHENIX GitHub at line 47 of file F04EventAction.cc
References fEventMessenger.
F04EventAction::~F04EventAction () virtual
Definition at line 55 of file F04EventAction.cc.
View newest version in sPHENIX GitHub at line 55 of file F04EventAction.cc
References fEventMessenger.
Member Function Documentation
void F04EventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 62 of file F04EventAction.cc.
View newest version in sPHENIX GitHub at line 62 of file F04EventAction.cc
References fVerboseLevel, G4cout, G4endl, and G4Event::GetEventID().
void F04EventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 74 of file F04EventAction.cc.
View newest version in sPHENIX GitHub at line 74 of file F04EventAction.cc
References fRunaction, fVerboseLevel, G4cout, G4endl, G4Threading::G4GetThreadId(), G4Event::GetEventID(), and F04RunAction::GetRndmFreq().
G4int F04EventAction::GetEventNo ()
Definition at line 89 of file F04EventAction.cc.
View newest version in sPHENIX GitHub at line 89 of file F04EventAction.cc
References G4UserEventAction::fpEventManager, G4EventManager::GetConstCurrentEvent(), and G4Event::GetEventID().
void F04EventAction::SetEventVerbose (G4int level)
Definition at line 96 of file F04EventAction.cc.
View newest version in sPHENIX GitHub at line 96 of file F04EventAction.cc
References fVerboseLevel.
Referenced by F04EventActionMessenger::SetNewValue().
Member Data Documentation
F04EventActionMessenger* F04EventAction::fEventMessenger private
Definition at line 58 of file F04EventAction.hh.
View newest version in sPHENIX GitHub at line 58 of file F04EventAction.hh
Referenced by F04EventAction(), and ~F04EventAction().
F04RunAction* F04EventAction::fRunaction private
Definition at line 57 of file F04EventAction.hh.
View newest version in sPHENIX GitHub at line 57 of file F04EventAction.hh
Referenced by EndOfEventAction().
G4int F04EventAction::fVerboseLevel private
Definition at line 60 of file F04EventAction.hh.
View newest version in sPHENIX GitHub at line 60 of file F04EventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), and SetEventVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04EventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04EventAction.cc