ECCE @ EIC Software: PHG4LFHcalSteppingAction Class Reference
PHG4LFHcalSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4LFHcalSteppingAction.h>
Public Member Functions
PHG4LFHcalSteppingAction (PHG4LFHcalDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4LFHcalSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
virtual void SetHitNodeName (const std::string &, const std::string &)
Set the G4HIT node names from Subsystem rather than constructing your own.
Private Attributes
PHG4LFHcalDetector * m_Detector = nullptr
pointer to the detector
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
PHG4Shower * m_SaveShower = nullptr
int m_ActiveFlag = 0
int m_AbsorberTruthFlag = 0
int m_BlackHoleFlag = 0
int m_NlayersPerTowerSeg = 10
double m_zdepthtailcatcher = 100000
int m_NLayerTailCatcherOffset = 0
Detailed Description
Definition at line 19 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 19 of file PHG4LFHcalSteppingAction.h
Constructor & Destructor Documentation
PHG4LFHcalSteppingAction::PHG4LFHcalSteppingAction (PHG4LFHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 41 of file PHG4LFHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file PHG4LFHcalSteppingAction.cc
PHG4LFHcalSteppingAction::~PHG4LFHcalSteppingAction () virtual
destructor
Definition at line 53 of file PHG4LFHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file PHG4LFHcalSteppingAction.cc
References m_Hit.
Member Function Documentation
void PHG4LFHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 286 of file PHG4LFHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 286 of file PHG4LFHcalSteppingAction.cc
References PHG4Detector::GetName(), m_AbsorberHitContainer, m_Detector, m_HitContainer, PHG4LFHcalDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4LFHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 63 of file PHG4LFHcalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 63 of file PHG4LFHcalSteppingAction.cc
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), cm, edep, fAtRestDoItProc, fGeomBoundary, fStopAndKill, fUndefined, fWorldBoundary, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4LFHcalDetector::get_Layer(), PHG4Hit::get_light_yield(), G4IonisParamMat::GetBirksConstant(), G4VPhysicalVolume::GetCopyNo(), G4StepPoint::GetGlobalTime(), PHG4HitContainer::GetID(), G4Material::GetIonisation(), G4Track::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4Track::GetMaterialCutsCouple(), PHG4Detector::GetName(), G4Material::GetName(), G4Step::GetNonIonizingEnergyDeposit(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), G4Track::GetUserInformation(), PHG4SteppingAction::GetVisibleEnergyDeposition(), G4VTouchable::GetVolume(), GeV, int(), PHG4LFHcalDetector::IsInLFHcal(), G4TTL::layer, m_AbsorberHitContainer, m_AbsorberTruthFlag, m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_NlayersPerTowerSeg, m_SaveHitContainer, m_SaveShower, nanosecond, G4InuclParticleNames::pp, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_index_l(), PHG4Hit::set_light_yield(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), G4Track::SetTrackStatus(), PHG4SteppingAction::Verbosity(), Acts::Test::volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
PHG4HitContainer* PHG4LFHcalSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 40 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4LFHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4LFHcalSteppingAction::m_AbsorberTruthFlag = 0 private
Definition at line 46 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4LFHcalSteppingAction::m_ActiveFlag = 0 private
Definition at line 45 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4LFHcalSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 47 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4LFHcalDetector* PHG4LFHcalSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 36 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4LFHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4LFHcalSteppingAction::m_Hit = nullptr private
Definition at line 42 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction(), and ~PHG4LFHcalSteppingAction().
PHG4HitContainer* PHG4LFHcalSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 39 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 39 of file PHG4LFHcalSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4LFHcalSteppingAction::m_NlayersPerTowerSeg = 10 private
Definition at line 48 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction().
int PHG4LFHcalSteppingAction::m_NLayerTailCatcherOffset = 0 private
Definition at line 50 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file PHG4LFHcalSteppingAction.h
PHG4HitContainer* PHG4LFHcalSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 41 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction().
PHG4Shower* PHG4LFHcalSteppingAction::m_SaveShower = nullptr private
Definition at line 43 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4LFHcalSteppingAction.h
Referenced by UserSteppingAction().
double PHG4LFHcalSteppingAction::m_zdepthtailcatcher = 100000 private
Definition at line 49 of file PHG4LFHcalSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4LFHcalSteppingAction.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4LFHcalSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4LFHcalSteppingAction.cc