ECCE @ EIC Software: G4PionDecayMakeSpin Class Reference
G4PionDecayMakeSpin Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/decay/include/G4PionDecayMakeSpin.hh>
Public Member Functions
G4PionDecayMakeSpin (const G4String &processName="Decay")
virtual ~G4PionDecayMakeSpin ()
virtual void ProcessDescription (std::ostream &outFile) const override
Public Member Functions inherited from G4Decay
G4Decay (const G4String &processName="Decay")
virtual ~G4Decay ()
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4VParticleChange * AtRestDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual G4bool IsApplicable (const G4ParticleDefinition &) override
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual void StartTracking (G4Track *) override
virtual void EndTracking () override
void SetExtDecayer (G4VExtDecayer *)
const G4VExtDecayer * GetExtDecayer () const
G4double GetRemainderLifeTime () const
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void DaughterPolarization (const G4Track &aTrack, G4DecayProducts *products) override
Protected Member Functions inherited from G4Decay
virtual G4VParticleChange * DecayIt (const G4Track &aTrack, const G4Step &aStep)
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *condition) override
Private Member Functions
G4PionDecayMakeSpin (const G4PionDecayMakeSpin &right)
G4PionDecayMakeSpin & operator= (const G4PionDecayMakeSpin &right)
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4Decay
G4int verboseLevel
const G4double HighestValue
G4double fRemainderLifeTime
G4ParticleChangeForDecay fParticleChangeForDecay
G4VExtDecayer * pExtDecayer
Detailed Description
Definition at line 39 of file G4PionDecayMakeSpin.hh.
View newest version in sPHENIX GitHub at line 39 of file G4PionDecayMakeSpin.hh
Constructor & Destructor Documentation
G4PionDecayMakeSpin::G4PionDecayMakeSpin (const G4String & processName = "Decay")
Definition at line 38 of file G4PionDecayMakeSpin.cc.
View newest version in sPHENIX GitHub at line 38 of file G4PionDecayMakeSpin.cc
References DECAY_PionMakeSpin, and G4VProcess::SetProcessSubType().
G4PionDecayMakeSpin::~G4PionDecayMakeSpin () virtual
Definition at line 46 of file G4PionDecayMakeSpin.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PionDecayMakeSpin.cc
G4PionDecayMakeSpin::G4PionDecayMakeSpin (const G4PionDecayMakeSpin & right) private
Member Function Documentation
void G4PionDecayMakeSpin::DaughterPolarization (const G4Track & aTrack, G4DecayProducts * products) override protected virtual
Reimplemented from G4Decay.
Definition at line 48 of file G4PionDecayMakeSpin.cc.
View newest version in sPHENIX GitHub at line 48 of file G4PionDecayMakeSpin.cc
References G4DecayProducts::entries(), G4ParticleTable::FindParticle(), G4RandomDirection(), G4DynamicParticle::GetCharge(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentum(), G4DecayProducts::GetParentParticle(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), scale, G4DynamicParticle::SetPolarization(), CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4PionDecayMakeSpin& G4PionDecayMakeSpin::operator= (const G4PionDecayMakeSpin & right) private
void G4PionDecayMakeSpin::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4Decay.
Definition at line 150 of file G4PionDecayMakeSpin.cc.
View newest version in sPHENIX GitHub at line 150 of file G4PionDecayMakeSpin.cc
References G4VProcess::GetProcessName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/decay/include/G4PionDecayMakeSpin.hh
geant4/tree/geant4-10.6-release/source/processes/decay/src/G4PionDecayMakeSpin.cc