ECCE @ EIC Software: G4AdjointTrackingAction Class Reference
G4AdjointTrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4AdjointTrackingAction.hh>
Public Member Functions
G4AdjointTrackingAction (G4AdjointSteppingAction *anAction)
virtual ~G4AdjointTrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
void RegisterAtEndOfAdjointTrack ()
void ClearEndOfAdjointTrackInfoVectors ()
void SetUserForwardTrackingAction (G4UserTrackingAction *anAction)
G4ThreeVector GetPositionAtEndOfLastAdjointTrack (size_t i=0)
G4ThreeVector GetDirectionAtEndOfLastAdjointTrack (size_t i=0)
G4double GetEkinAtEndOfLastAdjointTrack (size_t i=0)
G4double GetEkinNucAtEndOfLastAdjointTrack (size_t i=0)
G4double GetWeightAtEndOfLastAdjointTrack (size_t i=0)
G4double GetCosthAtEndOfLastAdjointTrack (size_t i=0)
const G4String & GetFwdParticleNameAtEndOfLastAdjointTrack ()
G4int GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack (size_t i=0)
G4bool GetIsAdjointTrackingMode ()
G4int GetLastFwdParticleIndex (size_t i=0)
size_t GetNbOfAdointTracksReachingTheExternalSurface ()
void SetListOfPrimaryFwdParticles (std::vector< G4ParticleDefinition * > *aListOfParticles)
Public Member Functions inherited from G4UserTrackingAction
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
Private Attributes
G4AdjointSteppingAction * theAdjointSteppingAction
G4UserTrackingAction * theUserFwdTrackingAction
G4bool is_adjoint_tracking_mode
G4ThreeVector last_pos
G4ThreeVector last_direction
G4double last_ekin
G4double last_ekin_nuc
G4double last_cos_th
G4String last_fwd_part_name
G4int last_fwd_part_PDGEncoding
G4double last_weight
G4int last_fwd_part_index
std::vector
< G4ParticleDefinition * > * pListOfPrimaryFwdParticles
std::vector< G4ThreeVector > last_pos_vec
std::vector< G4ThreeVector > last_direction_vec
std::vector< G4double > last_ekin_vec
std::vector< G4double > last_ekin_nuc_vec
std::vector< G4double > last_cos_th_vec
std::vector< G4double > last_weight_vec
std::vector< G4int > last_fwd_part_PDGEncoding_vec
std::vector< G4int > last_fwd_part_index_vec
Additional Inherited Members
Protected Attributes inherited from G4UserTrackingAction
G4TrackingManager * fpTrackingManager
Detailed Description
Definition at line 51 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file G4AdjointTrackingAction.hh
Constructor & Destructor Documentation
G4AdjointTrackingAction::G4AdjointTrackingAction (G4AdjointSteppingAction * anAction)
Definition at line 42 of file G4AdjointTrackingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file G4AdjointTrackingAction.cc
G4AdjointTrackingAction::~G4AdjointTrackingAction () virtual
Definition at line 47 of file G4AdjointTrackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file G4AdjointTrackingAction.cc
Member Function Documentation
void G4AdjointTrackingAction::ClearEndOfAdjointTrackInfoVectors ()
Definition at line 118 of file G4AdjointTrackingAction.cc.
View newest version in sPHENIX GitHub at line 118 of file G4AdjointTrackingAction.cc
References last_cos_th_vec, last_direction_vec, last_ekin_nuc_vec, last_ekin_vec, last_fwd_part_index_vec, last_fwd_part_PDGEncoding_vec, last_pos_vec, and last_weight_vec.
Referenced by G4AdjointSimManager::ClearEndOfAdjointTrackInfoVectors().
G4double G4AdjointTrackingAction::GetCosthAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 77 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointTrackingAction.hh
References last_cos_th_vec.
Referenced by G4AdjointSimManager::GetCosthAtEndOfLastAdjointTrack().
G4ThreeVector G4AdjointTrackingAction::GetDirectionAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 73 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file G4AdjointTrackingAction.hh
References last_direction_vec.
Referenced by G4AdjointSimManager::GetDirectionAtEndOfLastAdjointTrack().
G4double G4AdjointTrackingAction::GetEkinAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 74 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 74 of file G4AdjointTrackingAction.hh
References last_ekin_vec.
Referenced by G4AdjointSimManager::GetEkinAtEndOfLastAdjointTrack().
G4double G4AdjointTrackingAction::GetEkinNucAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 75 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4AdjointTrackingAction.hh
References last_ekin_nuc_vec.
Referenced by G4AdjointSimManager::GetEkinNucAtEndOfLastAdjointTrack().
const G4String& G4AdjointTrackingAction::GetFwdParticleNameAtEndOfLastAdjointTrack () inline
Definition at line 78 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AdjointTrackingAction.hh
References last_fwd_part_name.
Referenced by G4AdjointSimManager::GetFwdParticleNameAtEndOfLastAdjointTrack().
G4int G4AdjointTrackingAction::GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 79 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 79 of file G4AdjointTrackingAction.hh
References last_fwd_part_PDGEncoding_vec.
Referenced by G4AdjointSimManager::GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack().
G4bool G4AdjointTrackingAction::GetIsAdjointTrackingMode () inline
Definition at line 80 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 80 of file G4AdjointTrackingAction.hh
References is_adjoint_tracking_mode.
Referenced by G4AdjointSimManager::GetAdjointTrackingMode().
G4int G4AdjointTrackingAction::GetLastFwdParticleIndex (size_t i = 0) inline
Definition at line 81 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 81 of file G4AdjointTrackingAction.hh
References last_fwd_part_index_vec.
Referenced by G4AdjointSimManager::GetFwdParticleIndexAtEndOfLastAdjointTrack().
size_t G4AdjointTrackingAction::GetNbOfAdointTracksReachingTheExternalSurface () inline
Definition at line 83 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4AdjointTrackingAction.hh
References last_pos_vec.
Referenced by G4AdjointStackingAction::ClassifyNewTrack(), and G4AdjointSimManager::GetNbOfAdointTracksReachingTheExternalSurface().
G4ThreeVector G4AdjointTrackingAction::GetPositionAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 72 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 72 of file G4AdjointTrackingAction.hh
References last_pos_vec.
Referenced by G4AdjointSimManager::GetPositionAtEndOfLastAdjointTrack().
G4double G4AdjointTrackingAction::GetWeightAtEndOfLastAdjointTrack (size_t i = 0) inline
Definition at line 76 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AdjointTrackingAction.hh
References last_weight_vec.
Referenced by G4AdjointSimManager::GetWeightAtEndOfLastAdjointTrack().
void G4AdjointTrackingAction::PostUserTrackingAction (const G4Track * aTrack) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 66 of file G4AdjointTrackingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file G4AdjointTrackingAction.cc
References G4ParticleTable::FindParticle(), G4ParticleDefinition::GetBaryonNumber(), G4AdjointSteppingAction::GetDidAdjParticleReachTheExtSource(), G4AdjointSteppingAction::GetLastEkin(), G4AdjointSteppingAction::GetLastMomentum(), G4AdjointSteppingAction::GetLastPartDef(), G4AdjointSteppingAction::GetLastPosition(), G4AdjointSteppingAction::GetLastWeight(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGEncoding(), is_adjoint_tracking_mode, last_cos_th, last_cos_th_vec, last_direction, last_direction_vec, last_ekin, last_ekin_nuc, last_ekin_nuc_vec, last_ekin_vec, last_fwd_part_index, last_fwd_part_index_vec, last_fwd_part_name, last_fwd_part_PDGEncoding, last_fwd_part_PDGEncoding_vec, last_pos, last_pos_vec, last_weight, last_weight_vec, CLHEP::Hep3Vector::mag(), pListOfPrimaryFwdParticles, G4UserTrackingAction::PostUserTrackingAction(), G4String::remove(), theAdjointSteppingAction, theUserFwdTrackingAction, and CLHEP::Hep3Vector::z().
void G4AdjointTrackingAction::PreUserTrackingAction (const G4Track * aTrack) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 51 of file G4AdjointTrackingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file G4AdjointTrackingAction.cc
References G4String::contains(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleType(), G4Track::GetWeight(), is_adjoint_tracking_mode, G4UserTrackingAction::PreUserTrackingAction(), G4AdjointSteppingAction::SetAdjointTrackingMode(), G4AdjointSteppingAction::SetPrimWeight(), theAdjointSteppingAction, and theUserFwdTrackingAction.
void G4AdjointTrackingAction::RegisterAtEndOfAdjointTrack ()
void G4AdjointTrackingAction::SetListOfPrimaryFwdParticles (std::vector< G4ParticleDefinition * > * aListOfParticles) inline
Definition at line 84 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 84 of file G4AdjointTrackingAction.hh
References pListOfPrimaryFwdParticles.
Referenced by G4AdjointSimManager::G4AdjointSimManager().
void G4AdjointTrackingAction::SetUserForwardTrackingAction (G4UserTrackingAction * anAction) inline
Definition at line 70 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file G4AdjointTrackingAction.hh
References theUserFwdTrackingAction.
Referenced by G4AdjointSimManager::SetAdjointActions().
Member Data Documentation
G4bool G4AdjointTrackingAction::is_adjoint_tracking_mode private
Definition at line 91 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 91 of file G4AdjointTrackingAction.hh
Referenced by GetIsAdjointTrackingMode(), PostUserTrackingAction(), and PreUserTrackingAction().
G4double G4AdjointTrackingAction::last_cos_th private
Definition at line 99 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4double> G4AdjointTrackingAction::last_cos_th_vec private
Definition at line 110 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetCosthAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
G4ThreeVector G4AdjointTrackingAction::last_direction private
Definition at line 97 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4ThreeVector> G4AdjointTrackingAction::last_direction_vec private
Definition at line 107 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetDirectionAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
G4double G4AdjointTrackingAction::last_ekin private
Definition at line 98 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
G4double G4AdjointTrackingAction::last_ekin_nuc private
Definition at line 98 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4double> G4AdjointTrackingAction::last_ekin_nuc_vec private
Definition at line 109 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetEkinNucAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
std::vector<G4double> G4AdjointTrackingAction::last_ekin_vec private
Definition at line 108 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetEkinAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
G4int G4AdjointTrackingAction::last_fwd_part_index private
Definition at line 103 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4int> G4AdjointTrackingAction::last_fwd_part_index_vec private
Definition at line 113 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetLastFwdParticleIndex(), and PostUserTrackingAction().
G4String G4AdjointTrackingAction::last_fwd_part_name private
Definition at line 100 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AdjointTrackingAction.hh
Referenced by GetFwdParticleNameAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
G4int G4AdjointTrackingAction::last_fwd_part_PDGEncoding private
Definition at line 101 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4int> G4AdjointTrackingAction::last_fwd_part_PDGEncoding_vec private
Definition at line 112 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetFwdParticlePDGEncodingAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
G4ThreeVector G4AdjointTrackingAction::last_pos private
Definition at line 96 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4ThreeVector> G4AdjointTrackingAction::last_pos_vec private
Definition at line 106 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetNbOfAdointTracksReachingTheExternalSurface(), GetPositionAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
G4double G4AdjointTrackingAction::last_weight private
Definition at line 102 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction().
std::vector<G4double> G4AdjointTrackingAction::last_weight_vec private
Definition at line 111 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AdjointTrackingAction.hh
Referenced by ClearEndOfAdjointTrackInfoVectors(), GetWeightAtEndOfLastAdjointTrack(), and PostUserTrackingAction().
std::vector<G4ParticleDefinition*>* G4AdjointTrackingAction::pListOfPrimaryFwdParticles private
Definition at line 104 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction(), and SetListOfPrimaryFwdParticles().
G4AdjointSteppingAction* G4AdjointTrackingAction::theAdjointSteppingAction private
Definition at line 89 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 89 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction(), and PreUserTrackingAction().
G4UserTrackingAction* G4AdjointTrackingAction::theUserFwdTrackingAction private
Definition at line 90 of file G4AdjointTrackingAction.hh.
View newest version in sPHENIX GitHub at line 90 of file G4AdjointTrackingAction.hh
Referenced by PostUserTrackingAction(), PreUserTrackingAction(), and SetUserForwardTrackingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4AdjointTrackingAction.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4AdjointTrackingAction.cc