ECCE @ EIC Software: G4XXXSGSceneHandler Class Reference
G4XXXSGSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXSGSceneHandler.hh>
Public Member Functions
G4XXXSGSceneHandler (G4VGraphicsSystem &system, const G4String &name)
virtual ~G4XXXSGSceneHandler ()
void AddSolid (const G4Box &)
void AddSolid (const G4Cons &cons)
void AddSolid (const G4Tubs &tubs)
void AddSolid (const G4Trd &trd)
void AddSolid (const G4Trap &trap)
void AddSolid (const G4Sphere &sphere)
void AddSolid (const G4Para &para)
void AddSolid (const G4Torus &torus)
void AddSolid (const G4Polycone &polycone)
void AddSolid (const G4Polyhedra &polyhedra)
void AddSolid (const G4Orb &orb)
void AddSolid (const G4Ellipsoid &ellipsoid)
void AddSolid (const G4TessellatedSolid &tess)
void AddSolid (const G4VSolid &solid)
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
void PostAddSolid ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Polymarker &polymarker)
void AddPrimitive (const G4Scale &scale)
void BeginPrimitives (const G4Transform3D &objectTransformation)
void EndPrimitives ()
void ClearStore ()
void ClearTransientStore ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void AddCompound (const G4VTrajectory &)
virtual void AddCompound (const G4VHit &)
virtual void AddCompound (const G4VDigi &)
virtual void AddCompound (const G4THitsMap< G4double > &)
virtual void AddCompound (const G4THitsMap< G4StatDouble > &)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Protected Member Functions
void CreateCurrentItem (const G4String &)
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes
SceneGraph fSceneGraph
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Static Protected Attributes
static G4int fSceneIdCount = 0
Friends
class G4XXXSGViewer
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Detailed Description
Definition at line 65 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 65 of file G4XXXSGSceneHandler.hh
Constructor & Destructor Documentation
G4XXXSGSceneHandler::G4XXXSGSceneHandler (G4VGraphicsSystem & system, const G4String & name)
Definition at line 53 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 53 of file G4XXXSGSceneHandler.cc
G4XXXSGSceneHandler::~G4XXXSGSceneHandler () virtual
Definition at line 58 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 58 of file G4XXXSGSceneHandler.cc
Member Function Documentation
void G4XXXSGSceneHandler::AddPrimitive (const G4Polyline & polyline) virtual
Implements G4VSceneHandler.
Definition at line 250 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 250 of file G4XXXSGSceneHandler.cc
References G4cout, and G4endl.
void G4XXXSGSceneHandler::AddPrimitive (const G4Text & text) virtual
Implements G4VSceneHandler.
Definition at line 266 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 266 of file G4XXXSGSceneHandler.cc
References G4cout, and G4endl.
void G4XXXSGSceneHandler::AddPrimitive (const G4Circle & circle) virtual
Implements G4VSceneHandler.
Definition at line 284 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 284 of file G4XXXSGSceneHandler.cc
References G4cout, G4endl, G4VSceneHandler::GetMarkerSize(), G4VSceneHandler::screen, and G4VSceneHandler::world.
void G4XXXSGSceneHandler::AddPrimitive (const G4Square & square) virtual
Implements G4VSceneHandler.
Definition at line 314 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 314 of file G4XXXSGSceneHandler.cc
References G4cout, G4endl, G4VSceneHandler::GetMarkerSize(), G4VSceneHandler::screen, and G4VSceneHandler::world.
void G4XXXSGSceneHandler::AddPrimitive (const G4Polyhedron & polyhedron) virtual
Implements G4VSceneHandler.
Definition at line 344 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 344 of file G4XXXSGSceneHandler.cc
References G4VSceneHandler::fpViewer, G4cout, G4endl, G4VSceneHandler::GetDrawingStyle(), G4ViewParameters::hlr, G4ViewParameters::hsr, and G4ViewParameters::wireframe.
void G4XXXSGSceneHandler::AddPrimitive (const G4Polymarker & polymarker) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 126 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 126 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4XXXSGSceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 128 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 128 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4XXXSGSceneHandler::AddSolid (const G4Box & box) virtual
Reimplemented from G4VSceneHandler.
Definition at line 232 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 232 of file G4XXXSGSceneHandler.cc
References G4cout, G4endl, G4VSolid::GetName(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), and G4Box::GetZHalfLength().
void G4XXXSGSceneHandler::AddSolid (const G4Cons & cons) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 80 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 80 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Tubs & tubs) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 82 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 82 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Trd & trd) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 84 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 84 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Trap & trap) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 86 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 86 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Sphere & sphere) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 88 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 88 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Para & para) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 90 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 90 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Torus & torus) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 92 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 92 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Polycone & polycone) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 94 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 94 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Polyhedra & polyhedra) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 96 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 96 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Orb & orb) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 98 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 98 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 100 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 100 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4TessellatedSolid & tess) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 102 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 102 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::AddSolid (const G4VSolid & solid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 104 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 104 of file G4XXXSGSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4XXXSGSceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
Definition at line 213 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 213 of file G4XXXSGSceneHandler.cc
References G4VSceneHandler::BeginPrimitives().
void G4XXXSGSceneHandler::ClearStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 402 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 402 of file G4XXXSGSceneHandler.cc
References JA::Clear(), and fSceneGraph.
void G4XXXSGSceneHandler::ClearTransientStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 407 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 407 of file G4XXXSGSceneHandler.cc
References JA::Clear(), and fSceneGraph.
void G4XXXSGSceneHandler::CreateCurrentItem (const G4String &) protected
Definition at line 89 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 89 of file G4XXXSGSceneHandler.cc
References G4VSceneHandler::fpModel, fSceneGraph, G4PhysicalVolumeModel::GetDrawnPVPath(), and JA::Insert().
void G4XXXSGSceneHandler::EndPrimitives () virtual
Reimplemented from G4VSceneHandler.
Definition at line 218 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 218 of file G4XXXSGSceneHandler.cc
References G4VSceneHandler::EndPrimitives().
void G4XXXSGSceneHandler::PostAddSolid () virtual
Reimplemented from G4VSceneHandler.
Definition at line 207 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 207 of file G4XXXSGSceneHandler.cc
References G4VSceneHandler::PostAddSolid().
void G4XXXSGSceneHandler::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes & visAttribs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 200 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 200 of file G4XXXSGSceneHandler.cc
References G4VSceneHandler::PreAddSolid().
Friends And Related Function Documentation
friend class G4XXXSGViewer friend
Definition at line 67 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 67 of file G4XXXSGSceneHandler.hh
Member Data Documentation
SceneGraph G4XXXSGSceneHandler::fSceneGraph protected
Definition at line 154 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 154 of file G4XXXSGSceneHandler.hh
Referenced by ClearStore(), ClearTransientStore(), and CreateCurrentItem().
G4int G4XXXSGSceneHandler::fSceneIdCount = 0 static protected
Definition at line 148 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 148 of file G4XXXSGSceneHandler.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/XXX/include/G4XXXSGSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/XXX/src/G4XXXSGSceneHandler.cc