ECCE @ EIC Software: G4CachedMagneticField Class Reference
G4CachedMagneticField Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4CachedMagneticField.hh>
Public Member Functions
G4CachedMagneticField (G4MagneticField *, G4double distanceConst)
virtual ~G4CachedMagneticField ()
G4CachedMagneticField (const G4CachedMagneticField &r)
G4CachedMagneticField & operator= (const G4CachedMagneticField &p)
virtual void GetFieldValue (const G4double Point[4], G4double *Bfield) const
G4double GetConstDistance () const
void SetConstDistance (G4double dist)
G4int GetCountCalls () const
G4int GetCountEvaluations () const
void ClearCounts ()
void ReportStatistics ()
virtual G4Field * Clone () const
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Protected Attributes
G4int fCountCalls = 0
G4int fCountEvaluations = 0
Private Attributes
G4MagneticField * fpMagneticField = nullptr
G4double fDistanceConst
G4ThreeVector fLastLocation
G4ThreeVector fLastValue
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 41 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 41 of file G4CachedMagneticField.hh
Constructor & Destructor Documentation
G4CachedMagneticField::G4CachedMagneticField (G4MagneticField * pMagField, G4double distanceConst)
Definition at line 33 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 33 of file G4CachedMagneticField.cc
References ClearCounts().
Referenced by Clone().
G4CachedMagneticField::~G4CachedMagneticField () virtual
Definition at line 53 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 53 of file G4CachedMagneticField.cc
G4CachedMagneticField::G4CachedMagneticField (const G4CachedMagneticField & r)
Definition at line 66 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 66 of file G4CachedMagneticField.cc
References ClearCounts(), fDistanceConst, fLastLocation, fLastValue, and fpMagneticField.
Member Function Documentation
void G4CachedMagneticField::ClearCounts () inline
Definition at line 61 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 61 of file G4CachedMagneticField.hh
References fCountCalls, and fCountEvaluations.
Referenced by G4CachedMagneticField(), and operator=().
G4Field * G4CachedMagneticField::Clone () const virtual
Reimplemented from G4Field.
Definition at line 41 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 41 of file G4CachedMagneticField.cc
References G4Field::Clone(), fDistanceConst, fLastLocation, fLastValue, fpMagneticField, and G4CachedMagneticField().
G4double G4CachedMagneticField::GetConstDistance () const inline
Definition at line 56 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 56 of file G4CachedMagneticField.hh
References fDistanceConst.
Referenced by G4NystromRK4::GetDistanceForConstantField().
G4int G4CachedMagneticField::GetCountCalls () const inline
Definition at line 59 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 59 of file G4CachedMagneticField.hh
References fCountCalls.
G4int G4CachedMagneticField::GetCountEvaluations () const inline
Definition at line 60 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CachedMagneticField.hh
References fCountEvaluations.
void G4CachedMagneticField::GetFieldValue (const G4double Point[4], G4double * Bfield) const virtual
Implements G4MagneticField.
Definition at line 90 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 90 of file G4CachedMagneticField.cc
References fCountCalls, fCountEvaluations, fDistanceConst, fLastLocation, fLastValue, fpMagneticField, G4MagneticField::GetFieldValue(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4CachedMagneticField & G4CachedMagneticField::operator= (const G4CachedMagneticField & p)
Definition at line 77 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 77 of file G4CachedMagneticField.cc
References ClearCounts(), fDistanceConst, fLastLocation, fLastValue, fpMagneticField, and G4MagneticField::operator=().
void G4CachedMagneticField::ReportStatistics ()
Definition at line 58 of file G4CachedMagneticField.cc.
View newest version in sPHENIX GitHub at line 58 of file G4CachedMagneticField.cc
References fCountCalls, fCountEvaluations, G4cout, and G4endl.
void G4CachedMagneticField::SetConstDistance (G4double dist) inline
Definition at line 57 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 57 of file G4CachedMagneticField.hh
References fDistanceConst.
Referenced by G4NystromRK4::SetDistanceForConstantField().
Member Data Documentation
G4int G4CachedMagneticField::fCountCalls = 0 mutable protected
Definition at line 68 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 68 of file G4CachedMagneticField.hh
Referenced by ClearCounts(), GetCountCalls(), GetFieldValue(), and ReportStatistics().
G4int G4CachedMagneticField::fCountEvaluations = 0 mutable protected
Definition at line 68 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 68 of file G4CachedMagneticField.hh
Referenced by ClearCounts(), GetCountEvaluations(), GetFieldValue(), and ReportStatistics().
G4double G4CachedMagneticField::fDistanceConst private
Definition at line 73 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CachedMagneticField.hh
Referenced by Clone(), G4CachedMagneticField(), GetConstDistance(), GetFieldValue(), operator=(), and SetConstDistance().
G4ThreeVector G4CachedMagneticField::fLastLocation mutable private
Definition at line 78 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 78 of file G4CachedMagneticField.hh
Referenced by Clone(), G4CachedMagneticField(), GetFieldValue(), and operator=().
G4ThreeVector G4CachedMagneticField::fLastValue mutable private
Definition at line 79 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CachedMagneticField.hh
Referenced by Clone(), G4CachedMagneticField(), GetFieldValue(), and operator=().
G4MagneticField* G4CachedMagneticField::fpMagneticField = nullptr private
Definition at line 72 of file G4CachedMagneticField.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CachedMagneticField.hh
Referenced by Clone(), G4CachedMagneticField(), GetFieldValue(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4CachedMagneticField.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4CachedMagneticField.cc