ECCE @ EIC Software: G4AlphaEvaporationProbability Class Reference
G4AlphaEvaporationProbability Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4AlphaEvaporationProbability.hh>
Public Member Functions
G4AlphaEvaporationProbability ()
~G4AlphaEvaporationProbability () override
Public Member Functions inherited from G4EvaporationProbability
G4EvaporationProbability (G4int anA, G4int aZ, G4double aGamma)
~G4EvaporationProbability () override
virtual G4double TotalProbability (const G4Fragment &fragment, G4double minKinEnergy, G4double maxKinEnergy, G4double CB, G4double exEnergy)
G4double ComputeProbability (G4double K, G4double CB) override
G4double SampleKineticEnergy (G4double minKinEnergy, G4double maxKinEnergy, G4double CB)
Public Member Functions inherited from G4VEmissionProbability
G4VEmissionProbability (G4int Z, G4int A)
virtual ~G4VEmissionProbability ()
void Initialise ()
virtual G4double EmissionProbability (const G4Fragment &fragment, G4double anEnergy)
G4int GetZ (void) const
G4int GetA (void) const
void SetDecayKinematics (G4int Z, G4int A, G4double rmass, G4double fmass)
G4double GetRecoilExcitation () const
void SetEvapExcitation (G4double exc)
G4double GetProbability () const
void ResetProbability ()
G4double SampleEnergy ()
Protected Member Functions
G4double CalcAlphaParam (const G4Fragment &fragment) override
G4double CalcBetaParam (const G4Fragment &fragment) override
Private Member Functions
G4AlphaEvaporationProbability (const G4AlphaEvaporationProbability &right)
const
G4AlphaEvaporationProbability & operator= (const G4AlphaEvaporationProbability &right)
G4bool operator== (const G4AlphaEvaporationProbability &right) const
G4bool operator!= (const G4AlphaEvaporationProbability &right) const
Additional Inherited Members
Protected Attributes inherited from G4VEmissionProbability
G4int OPTxs
G4int pVerbose
G4int theZ
G4int theA
G4int resZ
G4int resA
G4double pMass
G4double pEvapMass
G4double pResMass
G4double pProbability
G4NuclearLevelData * pNuclearLevelData
G4Pow * pG4pow
Detailed Description
Definition at line 41 of file G4AlphaEvaporationProbability.hh.
View newest version in sPHENIX GitHub at line 41 of file G4AlphaEvaporationProbability.hh
Constructor & Destructor Documentation
G4AlphaEvaporationProbability::G4AlphaEvaporationProbability () explicit
Definition at line 38 of file G4AlphaEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 38 of file G4AlphaEvaporationProbability.cc
G4AlphaEvaporationProbability::~G4AlphaEvaporationProbability () override
Definition at line 42 of file G4AlphaEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 42 of file G4AlphaEvaporationProbability.cc
G4AlphaEvaporationProbability::G4AlphaEvaporationProbability (const G4AlphaEvaporationProbability & right) private
Member Function Documentation
G4double G4AlphaEvaporationProbability::CalcAlphaParam (const G4Fragment & fragment) override protected virtual
Reimplemented from G4EvaporationProbability.
Definition at line 45 of file G4AlphaEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 45 of file G4AlphaEvaporationProbability.cc
References C(), G4VEmissionProbability::GetZ(), and G4Fragment::GetZ_asInt().
G4double G4AlphaEvaporationProbability::CalcBetaParam (const G4Fragment & fragment) override protected virtual
Reimplemented from G4EvaporationProbability.
Definition at line 77 of file G4AlphaEvaporationProbability.cc.
View newest version in sPHENIX GitHub at line 77 of file G4AlphaEvaporationProbability.cc
G4bool G4AlphaEvaporationProbability::operator!= (const G4AlphaEvaporationProbability & right) const private
const G4AlphaEvaporationProbability& G4AlphaEvaporationProbability::operator= (const G4AlphaEvaporationProbability & right) private
G4bool G4AlphaEvaporationProbability::operator== (const G4AlphaEvaporationProbability & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4AlphaEvaporationProbability.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4AlphaEvaporationProbability.cc