ECCE @ EIC Software: G4ProcessVector Class Reference
G4ProcessVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessVector.hh>
Public Member Functions
G4ProcessVector ()
G4ProcessVector (size_t)
G4ProcessVector (const G4ProcessVector &)
virtual ~G4ProcessVector ()
G4ProcessVector & operator= (const G4ProcessVector &right)
G4bool operator== (const G4ProcessVector &right) const
size_t entries () const
size_t length () const
size_t size () const
size_t index (G4VProcess *aProcess) const
G4bool contains (G4VProcess *aProcess) const
G4bool insert (G4VProcess *aProcess)
G4bool insertAt (G4int i, G4VProcess *aProcess)
G4VProcess * removeAt (G4int i)
G4VProcess * removeLast ()
void clear ()
G4VProcess *const & operator[] (G4int i) const
G4VProcess *const & operator() (G4int i) const
G4VProcess *& operator[] (G4int i)
G4VProcess *& operator() (G4int i)
Protected Types
typedef std::vector< G4VProcess * > G4ProcVector
Protected Attributes
G4ProcVector * pProcVector
Detailed Description
Definition at line 43 of file G4ProcessVector.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ProcessVector.hh
Member Typedef Documentation
typedef std::vector<G4VProcess*> G4ProcessVector::G4ProcVector protected
Definition at line 99 of file G4ProcessVector.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ProcessVector.hh
Constructor & Destructor Documentation
G4ProcessVector::G4ProcessVector ()
Definition at line 35 of file G4ProcessVector.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ProcessVector.cc
References pProcVector.
G4ProcessVector::G4ProcessVector (size_t siz) explicit
Definition at line 40 of file G4ProcessVector.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ProcessVector.cc
References pProcVector.
G4ProcessVector::G4ProcessVector (const G4ProcessVector & right)
Definition at line 45 of file G4ProcessVector.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ProcessVector.cc
References pProcVector.
G4ProcessVector::~G4ProcessVector () virtual
Definition at line 60 of file G4ProcessVector.cc.
View newest version in sPHENIX GitHub at line 60 of file G4ProcessVector.cc
References pProcVector.
Member Function Documentation
void G4ProcessVector::clear ()
Referenced by G4ProcessManager::CreateGPILvectors(), and G4ProcessManager::~G4ProcessManager().
G4bool G4ProcessVector::contains (G4VProcess * aProcess) const
Referenced by G4GlobalFastSimulationManager::ShowSetup().
size_t G4ProcessVector::entries () const
Referenced by G4ProcessManager::ActivateProcess(), G4ProcessManager::AddProcess(), G4ProcessManager::CreateGPILvectors(), G4ITStepProcessor::DealWithSecondaries(), G4ProcessManager::DumpInfo(), G4ProcessManager::EndTracking(), G4ProcessManager::FindInsertPosition(), G4ProcessManager::G4ProcessManager(), G4SteppingManager::GetProcessNumber(), G4ProcessManager::InActivateProcess(), G4ProcessManager::InsertAt(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4ProcessManager::RemoveAt(), G4ProcessManager::RemoveProcess(), G4ProcessManager::SetProcessOrderingToSecond(), G4ITStepProcessor::SetupGeneralProcessInfo(), G4ProcessManager::StartTracking(), and WLSSteppingAction::UserSteppingAction().
size_t G4ProcessVector::index (G4VProcess * aProcess) const
G4bool G4ProcessVector::insert (G4VProcess * aProcess)
Referenced by G4ProcessManager::AddProcess(), G4ProcessManager::CreateGPILvectors(), G4ProcessTable::ExtractProcesses(), and G4ProcessManager::G4ProcessManager().
G4bool G4ProcessVector::insertAt (G4int i, G4VProcess * aProcess)
Referenced by G4ProcessManager::InsertAt().
size_t G4ProcessVector::length () const
Referenced by P6DExtDecayerPhysics::ConstructProcess(), G4ProcessPlacer::PrintProcVec(), G4ProcessTableMessenger::SetNewValue(), and G4ProcessTable::SetProcessActivation().
G4VProcess* const& G4ProcessVector::operator() (G4int i) const
G4VProcess* & G4ProcessVector::operator() (G4int i)
G4ProcessVector & G4ProcessVector::operator= (const G4ProcessVector & right)
Definition at line 73 of file G4ProcessVector.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ProcessVector.cc
References pProcVector.
G4bool G4ProcessVector::operator== (const G4ProcessVector & right) const
G4VProcess* const& G4ProcessVector::operator[] (G4int i) const
G4VProcess* & G4ProcessVector::operator[] (G4int i)
G4VProcess* G4ProcessVector::removeAt (G4int i)
Referenced by G4ProcessManager::RemoveAt(), and G4ProcessManager::RemoveProcess().
G4VProcess* G4ProcessVector::removeLast ()
Referenced by G4ProcessManager::AddProcess().
size_t G4ProcessVector::size () const
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), G4EmCalculator::ActiveForParticle(), G4ITStepProcessor::ActiveOnlyITProcess(), G4BiasingHelper::AddLimiterProcess(), G4hImpactIonisation::AlongStepDoIt(), RunAction::BeginOfRunAction(), G4VUserChemistryList::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4PhysicsListHelper::CheckParticleList(), G4NeutronCrossSectionXS::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4TheRayTracer::CreateBitMap(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4PhysListUtil::FindCaptureProcess(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4PhysListUtil::FindFissionProcess(), G4VHadronPhysics::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmCalculator::FindProcess(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4HadronElasticPhysics::GetElasticProcess(), G4BiasingProcessInterface::IsFirstPostStepDoItInterface(), G4BiasingProcessInterface::IsFirstPostStepGPILInterface(), G4BiasingProcessInterface::IsLastPostStepDoItInterface(), G4BiasingProcessInterface::IsLastPostStepGPILInterface(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VUserPhysicsList::PreparePhysicsTable(), G4PhysicsListHelper::RegisterProcess(), G4BiasingProcessInterface::ReorderBiasingVectorAsGPIL(), G4VUserPhysicsList::RetrievePhysicsTable(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), and G4VUserPhysicsList::StorePhysicsTable().
Member Data Documentation
G4ProcVector* G4ProcessVector::pProcVector protected
Definition at line 101 of file G4ProcessVector.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ProcessVector.hh
Referenced by G4ProcessVector(), operator=(), and ~G4ProcessVector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessVector.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4ProcessVector.cc