ECCE @ EIC Software: boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index > Struct Template Reference
boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index > Struct Template Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/source/boost/detail/indexing_suite_detail.hpp>
Static Public Member Functions
static void slicing_not_suported ()
static object base_get_slice (Container &container, PySliceObject *slice)
static void base_set_slice (Container &container, PySliceObject *slice, PyObject *v)
static void base_delete_slice (Container &container, PySliceObject *slice)
Detailed Description
template<class Container, class DerivedPolicies, class ProxyHandler, class Data, class Index>
struct boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >
Definition at line 708 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 708 of file indexing_suite_detail.hpp
Member Function Documentation
template<class Container , class DerivedPolicies , class ProxyHandler , class Data , class Index > static void boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::base_delete_slice (Container & container, PySliceObject * slice) inline static
Definition at line 731 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 731 of file indexing_suite_detail.hpp
References boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::slicing_not_suported().
template<class Container , class DerivedPolicies , class ProxyHandler , class Data , class Index > static object boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::base_get_slice (Container & container, PySliceObject * slice) inline static
Definition at line 718 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 718 of file indexing_suite_detail.hpp
References boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::slicing_not_suported().
template<class Container , class DerivedPolicies , class ProxyHandler , class Data , class Index > static void boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::base_set_slice (Container & container, PySliceObject * slice, PyObject * v) inline static
Definition at line 725 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 725 of file indexing_suite_detail.hpp
References boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::slicing_not_suported().
template<class Container , class DerivedPolicies , class ProxyHandler , class Data , class Index > static void boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::slicing_not_suported () inline static
Definition at line 711 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 711 of file indexing_suite_detail.hpp
Referenced by boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::base_delete_slice(), boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::base_get_slice(), and boost::python::detail::no_slice_helper< Container, DerivedPolicies, ProxyHandler, Data, Index >::base_set_slice().
The documentation for this struct was generated from the following file:
geant4/tree/geant4-10.6-release/environments/g4py/source/boost/detail/indexing_suite_detail.hpp