ECCE @ EIC Software: G4EMDissociationSpectrum Class Reference
G4EMDissociationSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4EMDissociationSpectrum.hh>
Public Member Functions
G4EMDissociationSpectrum ()
~G4EMDissociationSpectrum ()
G4double GetGeneralE1Spectrum (G4double, G4double, G4double)
G4double GetGeneralE2Spectrum (G4double, G4double, G4double)
G4double GetClosestApproach (const G4double, const G4double, G4double, G4double, G4double)
Private Attributes
G4Bessel * bessel
Detailed Description
Definition at line 67 of file G4EMDissociationSpectrum.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EMDissociationSpectrum.hh
Constructor & Destructor Documentation
G4EMDissociationSpectrum::G4EMDissociationSpectrum ()
Definition at line 69 of file G4EMDissociationSpectrum.cc.
View newest version in sPHENIX GitHub at line 69 of file G4EMDissociationSpectrum.cc
References bessel.
G4EMDissociationSpectrum::~G4EMDissociationSpectrum ()
Definition at line 75 of file G4EMDissociationSpectrum.cc.
View newest version in sPHENIX GitHub at line 75 of file G4EMDissociationSpectrum.cc
References bessel.
Member Function Documentation
G4double G4EMDissociationSpectrum::GetClosestApproach (const G4double AP, const G4double ZP, G4double AT, G4double ZT, G4double b)
Definition at line 112 of file G4EMDissociationSpectrum.cc.
View newest version in sPHENIX GitHub at line 112 of file G4EMDissociationSpectrum.cc
References a0, source.hepunit::amu_c2, b, source.hepunit::elm_coupling, fermi, G4Pow::GetInstance(), halfpi, and G4Pow::powA().
G4double G4EMDissociationSpectrum::GetGeneralE1Spectrum (G4double Eg, G4double b, G4double bmin)
Definition at line 82 of file G4EMDissociationSpectrum.cc.
View newest version in sPHENIX GitHub at line 82 of file G4EMDissociationSpectrum.cc
References b, source.hepunit::fine_structure_const, source.hepunit::hbarc, n, and pi.
Referenced by G4EMDissociationCrossSection::GetCrossSectionForProjectile().
G4double G4EMDissociationSpectrum::GetGeneralE2Spectrum (G4double Eg, G4double b, G4double bmin)
Definition at line 96 of file G4EMDissociationSpectrum.cc.
View newest version in sPHENIX GitHub at line 96 of file G4EMDissociationSpectrum.cc
References b, source.hepunit::fine_structure_const, G4Pow::GetInstance(), source.hepunit::hbarc, n, pi, and G4Pow::powA().
Referenced by G4EMDissociationCrossSection::GetCrossSectionForProjectile().
Member Data Documentation
G4Bessel* G4EMDissociationSpectrum::bessel private
Definition at line 78 of file G4EMDissociationSpectrum.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EMDissociationSpectrum.hh
Referenced by G4EMDissociationSpectrum(), and ~G4EMDissociationSpectrum().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4EMDissociationSpectrum.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4EMDissociationSpectrum.cc