ECCE @ EIC Software: G4ScoringBox Class Reference
G4ScoringBox Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringBox.hh>
Public Member Functions
G4ScoringBox (G4String wName)
~G4ScoringBox ()
void List () const
void Draw (RunScore *map, G4VScoreColorMap *colorMap, G4int axflg=111)
void DrawColumn (RunScore *map, G4VScoreColorMap *colorMap, G4int idxProj, G4int idxColumn)
void SetSegmentDirection (G4int dir)
Public Member Functions inherited from G4VScoringMesh
G4VScoringMesh (const G4String &wName)
virtual ~G4VScoringMesh ()
void Construct (G4VPhysicalVolume *fWorldPhys)
void WorkerConstruct (G4VPhysicalVolume *fWorldPhys)
const G4String & GetWorldName () const
G4bool IsActive () const
void Activate (G4bool vl=true)
MeshShape GetShape () const
void Accumulate (G4THitsMap< G4double > *map)
void Accumulate (G4THitsMap< G4StatDouble > *map)
void Merge (const G4VScoringMesh *scMesh)
void Dump ()
void DrawMesh (const G4String &psName, G4VScoreColorMap *colorMap, G4int axflg=111)
void DrawMesh (const G4String &psName, G4int idxPlane, G4int iColumn, G4VScoreColorMap *colorMap)
void ResetScore ()
void SetSize (G4double size[3])
G4ThreeVector GetSize () const
void SetCenterPosition (G4double centerPosition[3])
G4ThreeVector GetTranslation () const
void RotateX (G4double delta)
void RotateY (G4double delta)
void RotateZ (G4double delta)
G4RotationMatrix GetRotationMatrix () const
void SetNumberOfSegments (G4int nSegment[3])
void GetNumberOfSegments (G4int nSegment[3])
void SetPrimitiveScorer (G4VPrimitiveScorer *ps)
void SetFilter (G4VSDFilter *filter)
void SetCurrentPrimitiveScorer (const G4String &name)
G4bool FindPrimitiveScorer (const G4String &psname)
G4bool IsCurrentPrimitiveScorerNull ()
G4String GetPSUnit (const G4String &psname)
G4String GetCurrentPSUnit ()
void SetCurrentPSUnit (const G4String &unit)
G4double GetPSUnitValue (const G4String &psname)
void SetDrawPSName (const G4String &psname)
void GetDivisionAxisNames (G4String divisionAxisNames[3])
void SetNullToCurrentPrimitiveScorer ()
void SetVerboseLevel (G4int vl)
MeshScoreMap GetScoreMap () const
G4bool ReadyForQuantity () const
void SetMeshElementLogical (G4LogicalVolume *val)
G4LogicalVolume * GetMeshElementLogical () const
void SetParallelWorldProcess (G4ParallelWorldProcess *proc)
G4ParallelWorldProcess * GetParallelWorldProcess () const
void GeometryHasBeenDestroyed ()
void SetCopyNumberLevel (G4int val)
G4int GetCopyNumberLevel () const
Protected Member Functions
virtual void SetupGeometry (G4VPhysicalVolume *fWorldPhys)
Protected Member Functions inherited from G4VScoringMesh
G4VPrimitiveScorer * GetPrimitiveScorer (const G4String &name)
Private Member Functions
G4ThreeVector GetReplicaPosition (G4int x, G4int y, G4int z)
void GetXYZ (G4int index, G4int q[3]) const
G4int GetIndex (G4int x, G4int y, G4int z) const
Private Attributes
G4int fSegmentDirection
Additional Inherited Members
Public Types inherited from G4VScoringMesh
enum MeshShape
using EventScore = G4THitsMap< G4double >
using RunScore = G4THitsMap< G4StatDouble >
using MeshScoreMap = std::map< G4String, RunScore * >
Protected Attributes inherited from G4VScoringMesh
G4String fWorldName
G4VPrimitiveScorer * fCurrentPS
G4bool fConstructed
G4bool fActive
MeshShape fShape
G4double fSize [3]
G4ThreeVector fCenterPosition
G4RotationMatrix * fRotationMatrix
G4int fNSegment [3]
MeshScoreMap fMap
G4MultiFunctionalDetector * fMFD
G4int verboseLevel
G4bool sizeIsSet
G4bool nMeshIsSet
G4String fDrawUnit
G4double fDrawUnitValue
G4String fDrawPSName
G4String fDivisionAxisNames [3]
G4LogicalVolume * fMeshElementLogical
G4ParallelWorldProcess * fParallelWorldProcess
G4bool fGeometryHasBeenDestroyed
G4int copyNumberLevel
Detailed Description
Definition at line 42 of file G4ScoringBox.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ScoringBox.hh
Constructor & Destructor Documentation
G4ScoringBox::G4ScoringBox (G4String wName)
Definition at line 54 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ScoringBox.cc
References G4VScoringMesh::fDivisionAxisNames, and G4VScoringMesh::fShape.
G4ScoringBox::~G4ScoringBox ()
Definition at line 63 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ScoringBox.cc
Member Function Documentation
void G4ScoringBox::Draw (RunScore * map, G4VScoreColorMap * colorMap, G4int axflg = 111) virtual
Implements G4VScoringMesh.
Definition at line 240 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 240 of file G4ScoringBox.cc
References G4VVisManager::BeginDraw(), c, DBL_MAX, G4VVisManager::Draw(), G4VScoreColorMap::DrawColorChart(), G4VVisManager::EndDraw(), G4VScoringMesh::fCenterPosition, G4VScoringMesh::fDrawPSName, G4VScoringMesh::fDrawUnit, G4VScoringMesh::fDrawUnitValue, G4VScoringMesh::fNSegment, G4VScoringMesh::fRotationMatrix, G4VScoringMesh::fSize, G4VVisManager::GetConcreteInstance(), G4VTHitsMap< T, Map_t >::GetMap(), G4VScoreColorMap::GetMapColor(), G4CSGSolid::GetPolyhedron(), GetReplicaPosition(), GetXYZ(), G4VScoreColorMap::IfFloatMinMax(), HepGeom::Transform3D::inverse(), pos(), scale, G4VisAttributes::SetColour(), G4VisAttributes::SetForceAuxEdgeVisible(), G4VisAttributes::SetForceSolid(), G4VScoreColorMap::SetMinMax(), G4VScoreColorMap::SetPSName(), G4VScoreColorMap::SetPSUnit(), G4Visible::SetVisAttributes(), thick, HepPolyhedron::Transform(), x, y, and z.
void G4ScoringBox::DrawColumn (RunScore * map, G4VScoreColorMap * colorMap, G4int idxProj, G4int idxColumn) virtual
Implements G4VScoringMesh.
Definition at line 522 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 522 of file G4ScoringBox.cc
References G4VVisManager::BeginDraw(), c, DBL_MAX, G4VVisManager::Draw(), G4VScoreColorMap::DrawColorChart(), G4VVisManager::EndDraw(), G4VScoringMesh::fCenterPosition, G4VScoringMesh::fDrawPSName, G4VScoringMesh::fDrawUnit, G4VScoringMesh::fDrawUnitValue, G4VScoringMesh::fNSegment, G4VScoringMesh::fRotationMatrix, G4VScoringMesh::fSize, G4cerr, G4endl, G4VVisManager::GetConcreteInstance(), G4VTHitsMap< T, Map_t >::GetMap(), G4VScoreColorMap::GetMapColor(), G4CSGSolid::GetPolyhedron(), GetReplicaPosition(), GetXYZ(), G4VScoreColorMap::IfFloatMinMax(), HepGeom::Transform3D::inverse(), pos(), scale, G4VisAttributes::SetColour(), G4VisAttributes::SetForceAuxEdgeVisible(), G4VisAttributes::SetForceSolid(), G4VScoreColorMap::SetMinMax(), G4VScoreColorMap::SetPSName(), G4VScoreColorMap::SetPSUnit(), G4Visible::SetVisAttributes(), HepPolyhedron::Transform(), x, y, and z.
G4int G4ScoringBox::GetIndex (G4int x, G4int y, G4int z) const private
Definition at line 518 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 518 of file G4ScoringBox.cc
References G4VScoringMesh::fNSegment.
G4ThreeVector G4ScoringBox::GetReplicaPosition (G4int x, G4int y, G4int z) private
Definition at line 499 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 499 of file G4ScoringBox.cc
References G4VScoringMesh::fNSegment, G4VScoringMesh::fSize, pos(), width, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Draw(), and DrawColumn().
void G4ScoringBox::GetXYZ (G4int index, G4int q[3]) const private
Definition at line 510 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 510 of file G4ScoringBox.cc
References G4VScoringMesh::fNSegment.
Referenced by Draw(), and DrawColumn().
void G4ScoringBox::List () const virtual
Reimplemented from G4VScoringMesh.
Definition at line 229 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 229 of file G4ScoringBox.cc
References cm, G4VScoringMesh::fSize, G4VScoringMesh::fWorldName, G4cout, G4endl, and G4VScoringMesh::List().
void G4ScoringBox::SetSegmentDirection (G4int dir) inline
Definition at line 59 of file G4ScoringBox.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ScoringBox.hh
References dir, and fSegmentDirection.
void G4ScoringBox::SetupGeometry (G4VPhysicalVolume * fWorldPhys) protected virtual
Implements G4VScoringMesh.
Definition at line 67 of file G4ScoringBox.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ScoringBox.cc
References G4VScoringMesh::fCenterPosition, G4VScoringMesh::fMeshElementLogical, G4VScoringMesh::fMFD, G4VScoringMesh::fNSegment, G4VScoringMesh::fRotationMatrix, G4VScoringMesh::fSize, G4VScoringMesh::fWorldName, G4cerr, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4ScoringManager::GetReplicaLevel(), kXAxis, kYAxis, kZAxis, G4LogicalVolume::SetSensitiveDetector(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and G4VScoringMesh::verboseLevel.
Member Data Documentation
G4int G4ScoringBox::fSegmentDirection private
Definition at line 70 of file G4ScoringBox.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ScoringBox.hh
Referenced by SetSegmentDirection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringBox.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoringBox.cc