ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/xDataTOM_importXML_private.h File Reference
xDataTOM_importXML_private.h File Reference
#include <expat.h>
#include <statusMessageReporting.h>
#include <xDataTOM_private.h>
Classes
struct xDataXML_docInfo_s
struct xDataXML_attribute_s
struct xDataXML_attributionList_s
struct xDataXML_text_s
struct xDataXML_elementListItem_s
struct xDataXML_elementList_s
struct xDataXMLType_s
struct xDataXML_rootElement_s
struct xDataXML_element_s
struct xDataXML_smr_s
struct xDataXML_document_s
struct xDataXML_item_s
Macros
#define XMLCALL
#define XML_Char char
#define XML_Size long
Typedefs
typedef struct xDataXMLType_s xDataXMLType
typedef struct
xDataTOM_importXMLTOM_s xDataTOM_importXMLTOM
typedef struct xDataXML_attribute_s xDataXML_attribute
typedef struct xDataXML_document_s xDataXML_document
typedef struct xDataXML_docInfo_s xDataXML_docInfo
typedef struct
xDataXML_attributionList_s xDataXML_attributionList
typedef struct xDataXML_element_s xDataXML_element
typedef struct
xDataXML_elementList_s xDataXML_elementList
typedef struct
xDataXML_elementListItem_s xDataXML_elementListItem
typedef struct
xDataXML_rootElement_s xDataXML_rootElement
typedef struct xDataXML_text_s xDataXML_text
typedef struct xDataXML_smr_s xDataXML_smr
typedef struct xDataXML_item_s xDataXML_item
typedef int(* xDTXML_toDataFunction)(statusMessageReporting *smr, xDataXMLType *, xDataXML_attributionList *, char const *)
typedef char *(* xDTXML_toStringFunction)(statusMessageReporting *smr, xDataXMLType *)
typedef int(* xDTXML_releaseFunction)(statusMessageReporting *smr, xDataXMLType *)
Enumerations
enum xDataXML_status { xDataXML_statusParsing = 1, xDataXML_statusCompleted, xDataXML_statusError }
enum xDataXML_errorCodes { xDataXML_errNone, xDataXML_errXML_ParserCreate, xDataXML_errFileError, xDataXML_errXMLParser }
enum xDataXML_itemMode { xDataXML_itemModeEnd = 0, xDataXML_itemModeElement, xDataXML_itemModeText }
enum xDataXML_xDataType { xDataXML_xDataType_Ok, xDataXML_xDataType_ConvertingToData, xDataXML_xDataType_ConvertingToString }
Functions
xDataTOM_TOM * xDataXML_importFile (statusMessageReporting *smr, char const *fileName)
xDataXML_document * xDataXML_importFile2 (statusMessageReporting *smr, char const *fileName)
void * xDataXML_freeDoc (statusMessageReporting *smr, xDataXML_document *doc)
int xDataXML_parseIsError (xDataXML_document *doc)
xDataXML_element * xDataXML_getDocumentsElement (xDataXML_document *doc)
xDataXML_element * xDataXML_getFirstElement (xDataXML_element *element)
xDataXML_element * xDataXML_getNextElement (xDataXML_element *element)
enum xDataXML_itemMode xDataXML_getFirstItem (xDataXML_element *element, xDataXML_item *item)
enum xDataXML_itemMode xDataXML_getNextItem (xDataXML_item *item)
int xDataXML_isAttributeInList (xDataXML_attributionList *attributes, char const *name)
int xDataXML_isAttributeInElement (xDataXML_element *element, char const *name)
char * xDataXML_getAttributesValue (xDataXML_attributionList *attributes, char const *name)
char const * xDataXML_getAttributesValueInElement (xDataXML_element *element, char const *name)
int xDataXML_attributeListLength (xDataXML_attributionList *attributes)
xDataXML_attribute * xDataXML_attributeByIndex (xDataXML_attributionList *attributes, int index)
int xDataXML_getCommonData (statusMessageReporting *smr, xDataXML_element *element, xDataTOM_Int *index, xDataTOM_Int *start, xDataTOM_Int *end, xDataTOM_Int *length)
int xDataXML_xDataTypeConvertAttributes (statusMessageReporting *smr, xDataXML_element *element)
xDataTOM_Int xDataXML_convertAttributeTo_xDataTOM_Int (statusMessageReporting *smr, xDataXML_element *element, char const *name, xDataTOM_Int *n, int required)
int xDataXML_convertAttributeToDouble (statusMessageReporting *smr, xDataXML_element *element, char const *name, double *d, int required)
int xDataXML_numberOfElementsByTagName (statusMessageReporting *smr, xDataXML_element *element, char const *tagName)
xDataXML_elementList * xDataXML_getElementsByTagName (statusMessageReporting *smr, xDataXML_element *element, char const *tagName)
xDataXML_element * xDataXML_getOneElementByTagName (statusMessageReporting *smr, xDataXML_element *element, char *name, int required)
void xDataXML_freeElementList (statusMessageReporting *smr, xDataXML_elementList *list)
int xDataXML_is_xDataType (statusMessageReporting *smr, xDataXMLType *xDT, char const *const type, int setMsg)
char const * xDataXML_getFileName (xDataXML_document *doc)
char const * xDataXML_getRealFileName (xDataXML_document *doc)
xDataXML_document * xDataXML_getElementsDocument (xDataXML_element *element)
void * xDataXML_get_smrUserInterfaceFromDocument (xDataXML_document *doc)
void * xDataXML_get_smrUserInterfaceFromElement (xDataXML_element *element)
int xDataXML_stringTo_xDataTOM_Int (statusMessageReporting *smr, void *smrUserInterface, char const *c, xDataTOM_Int *value, char const *endings, char **e)
int xDataXML_stringTo_double (statusMessageReporting *smr, void *smrUserInterface, char const *c, double *value, char const *endings, char **e)
int xDataXML_addToAccessed (statusMessageReporting *smr, xDataXML_element *element, int increment)
int xDataXML_getAccessed (statusMessageReporting *smr, xDataXML_element *element)
void * xDataXML_initializeData (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE, char const *ID, size_t size)
int xDataXML_axesElememtToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_axes *axes)
int xDataXML_axesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_axes *axes)
int xDataXML_XYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_XYsDataToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_XYs *XYs, int index, int length, double value, double accuracy, enum xDataTOM_subAxesType subAxesType, int axesOffest, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataXML_stringToDoubles (statusMessageReporting *smr, xDataXML_element *XE, char const *s, int length, double *d)
int xDataXML_regionsXYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_W_XYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_W_XYsDataToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_W_XYs *W_XYs, int index, double value, xDataTOM_axes *axes, int axesOffset)
int xDataXML_V_W_XYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_W_XYs_LegendreSeriesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_LegendreSeries *LegendreSeries)
int xDataXML_regionsW_XYs_LegendreSeriesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_V_W_XYs_LegendreSeriesToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_polynomialToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_KalbachMannToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
Macro Definition Documentation
#define XML_Char char
Definition at line 22 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_private.h
#define XML_Size long
Definition at line 26 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 26 of file xDataTOM_importXML_private.h
#define XMLCALL
Definition at line 18 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 18 of file xDataTOM_importXML_private.h
Typedef Documentation
typedef struct xDataTOM_importXMLTOM_s xDataTOM_importXMLTOM
Definition at line 36 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 36 of file xDataTOM_importXML_private.h
typedef struct xDataXML_attribute_s xDataXML_attribute
Definition at line 37 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 37 of file xDataTOM_importXML_private.h
typedef struct xDataXML_attributionList_s xDataXML_attributionList
Definition at line 40 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 40 of file xDataTOM_importXML_private.h
typedef struct xDataXML_docInfo_s xDataXML_docInfo
Definition at line 39 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 39 of file xDataTOM_importXML_private.h
typedef struct xDataXML_document_s xDataXML_document
Definition at line 38 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 38 of file xDataTOM_importXML_private.h
typedef struct xDataXML_element_s xDataXML_element
Definition at line 41 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 41 of file xDataTOM_importXML_private.h
typedef struct xDataXML_elementList_s xDataXML_elementList
Definition at line 42 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 42 of file xDataTOM_importXML_private.h
typedef struct xDataXML_elementListItem_s xDataXML_elementListItem
Definition at line 43 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 43 of file xDataTOM_importXML_private.h
typedef struct xDataXML_item_s xDataXML_item
Definition at line 47 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 47 of file xDataTOM_importXML_private.h
typedef struct xDataXML_rootElement_s xDataXML_rootElement
Definition at line 44 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM_importXML_private.h
typedef struct xDataXML_smr_s xDataXML_smr
Definition at line 46 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 46 of file xDataTOM_importXML_private.h
typedef struct xDataXML_text_s xDataXML_text
Definition at line 45 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 45 of file xDataTOM_importXML_private.h
typedef struct xDataXMLType_s xDataXMLType
Definition at line 29 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 29 of file xDataTOM_importXML_private.h
typedef int(* xDTXML_releaseFunction)(statusMessageReporting *smr, xDataXMLType *)
Definition at line 74 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 74 of file xDataTOM_importXML_private.h
typedef int(* xDTXML_toDataFunction)(statusMessageReporting *smr, xDataXMLType *, xDataXML_attributionList *, char const *)
Definition at line 72 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 72 of file xDataTOM_importXML_private.h
typedef char*(* xDTXML_toStringFunction)(statusMessageReporting *smr, xDataXMLType *)
Definition at line 73 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 73 of file xDataTOM_importXML_private.h
Enumeration Type Documentation
enum xDataXML_errorCodes
Enumerator:
xDataXML_errNone
xDataXML_errXML_ParserCreate
xDataXML_errFileError
xDataXML_errXMLParser
Definition at line 32 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 32 of file xDataTOM_importXML_private.h
enum xDataXML_itemMode
Enumerator:
xDataXML_itemModeEnd
xDataXML_itemModeElement
xDataXML_itemModeText
Definition at line 33 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 33 of file xDataTOM_importXML_private.h
enum xDataXML_status
Enumerator:
xDataXML_statusParsing
xDataXML_statusCompleted
xDataXML_statusError
Definition at line 31 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 31 of file xDataTOM_importXML_private.h
enum xDataXML_xDataType
Enumerator:
xDataXML_xDataType_Ok
xDataXML_xDataType_ConvertingToData
xDataXML_xDataType_ConvertingToString
Definition at line 34 of file xDataTOM_importXML_private.h.
View newest version in sPHENIX GitHub at line 34 of file xDataTOM_importXML_private.h
Function Documentation
int xDataXML_addToAccessed (statusMessageReporting * smr, xDataXML_element * element, int increment)
Definition at line 925 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 925 of file xDataTOM_importXML.cc
References xDataXML_element_s::accessed.
xDataXML_attribute* xDataXML_attributeByIndex (xDataXML_attributionList * attributes, int index)
Definition at line 512 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 512 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, and xDataXML_attributionList_s::number.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), and xDataXML_constructTOM().
int xDataXML_attributeListLength (xDataXML_attributionList * attributes)
Definition at line 505 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 505 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::number.
int xDataXML_axesElememtToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_axes * axes)
Definition at line 20 of file xDataTOM_importXML_axes.cc.
View newest version in sPHENIX GitHub at line 20 of file xDataTOM_importXML_axes.cc
References xDataXML_element_s::name, smr_setReportError3p, xDataTOM_smrLibraryID, xDataXML_axesToTOM(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), and xDataXML_getNextElement().
Referenced by xDataXML_initializeData(), and xDataXML_XYsToTOM().
int xDataXML_axesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_axes * axes)
Definition at line 45 of file xDataTOM_importXML_axes.cc.
View newest version in sPHENIX GitHub at line 45 of file xDataTOM_importXML_axes.cc
References xDataTOM_axes_s::axis, check_license::err(), n, xDataXML_element_s::name, smr_freeMemory(), smr_setReportError3, xDataTOM_axes_initialize(), xDataTOM_axis_initialize(), xDataTOM_axis_release(), xDataTOM_interpolation_set(), xDataTOM_interpolation_setFromString(), xDataTOM_interpolationFlag_linear, xDataTOM_interpolationQualifier_dependent, xDataTOM_smrLibraryID, xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getAttributesValueInElement(), xDataXML_getFirstElement(), and xDataXML_getNextElement().
Referenced by xDataXML_axesElememtToTOM().
xDataTOM_Int xDataXML_convertAttributeTo_xDataTOM_Int (statusMessageReporting * smr, xDataXML_element * element, char const * name, xDataTOM_Int * n, int required)
Definition at line 601 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 601 of file xDataTOM_importXML.cc
References e, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_getAttributesValueInElement().
Referenced by xDataXML_axesToTOM(), xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM(), xDataXML_W_XYs_XYsToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().
int xDataXML_convertAttributeToDouble (statusMessageReporting * smr, xDataXML_element * element, char const * name, double * d, int required)
Definition at line 624 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 624 of file xDataTOM_importXML.cc
References e, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_getAttributesValueInElement().
Referenced by MCGIDI_target_read(), xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM(), xDataXML_W_XYs_XYsToTOM(), and xDataXML_XYsToTOM().
void* xDataXML_freeDoc (statusMessageReporting * smr, xDataXML_document * doc)
Definition at line 188 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 188 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, xDataXML_document_s::fileName, xDataXML_document_s::realFileName, xDataXML_document_s::root, smr_freeMemory(), xDataXML_endXMLParsing(), xDataXML_freeElement(), and xDataXML_smrUserInterfaceFree().
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_importFile(), xDataXML_importFile2(), and xDataXML_mallocDoc().
void xDataXML_freeElementList (statusMessageReporting * smr, xDataXML_elementList * list)
Definition at line 706 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 706 of file xDataTOM_importXML.cc
References smr_freeMemory().
Referenced by xDataXML_getOneElementByTagName().
void* xDataXML_get_smrUserInterfaceFromDocument (xDataXML_document * doc)
Definition at line 808 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 808 of file xDataTOM_importXML.cc
References xDataXML_document_s::smrUserInterface.
Referenced by xDataXML_endXMLParsing(), and xDataXML_get_smrUserInterfaceFromElement().
void* xDataXML_get_smrUserInterfaceFromElement (xDataXML_element * element)
Definition at line 816 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 816 of file xDataTOM_importXML.cc
References xDataXML_get_smrUserInterfaceFromDocument(), and xDataXML_getElementsDocument().
Referenced by xDataXML_addElementToRoot(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_getCommonData(), xDataXML_getOneElementByTagName(), xDataXML_is_xDataType(), xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_stringToDoubles(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().
int xDataXML_getAccessed (statusMessageReporting * smr, xDataXML_element * element)
Definition at line 933 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 933 of file xDataTOM_importXML.cc
References xDataXML_element_s::accessed.
char* xDataXML_getAttributesValue (xDataXML_attributionList * attributes, char const * name)
Definition at line 486 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 486 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, xDataXML_attribute_s::name, xDataXML_attributionList_s::number, and xDataXML_attribute_s::value.
Referenced by xDataXML_getAttributesValueInElement().
char const* xDataXML_getAttributesValueInElement (xDataXML_element * element, char const * name)
Definition at line 498 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 498 of file xDataTOM_importXML.cc
References xDataXML_element_s::attributes, and xDataXML_getAttributesValue().
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), and xDataXML_regionsXYs_regionToTOM().
int xDataXML_getCommonData (statusMessageReporting * smr, xDataXML_element * element, xDataTOM_Int * index, xDataTOM_Int * start, xDataTOM_Int * end, xDataTOM_Int * length)
Definition at line 542 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 542 of file xDataTOM_importXML.cc
References xDataXMLType_s::end, xDataXML_element_s::fullName, xDataXMLType_s::ID, xDataXMLType_s::index, xDataXMLType_s::length, smr_setReportError3, xDataXMLType_s::start, xDataTOM_smrLibraryID, xDataXML_element_s::xDataTypeInfo, and xDataXML_get_smrUserInterfaceFromElement().
xDataXML_element* xDataXML_getDocumentsElement (xDataXML_document * doc)
Definition at line 413 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 413 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, and xDataXML_document_s::root.
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), and xDataXML_importFile().
xDataXML_elementList* xDataXML_getElementsByTagName (statusMessageReporting * smr, xDataXML_element * element, char const * tagName)
Definition at line 658 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 658 of file xDataTOM_importXML.cc
References xDataXML_elementListItem_s::element, xDataXML_elementList_s::items, n, xDataXML_elementList_s::n, xDataXML_element_s::name, smr_malloc2, xDataXML_elementListItem_s::sortString, xDataXML_getFirstElement(), xDataXML_getNextElement(), and xDataXML_numberOfElementsByTagName().
Referenced by xDataXML_getOneElementByTagName().
xDataXML_document* xDataXML_getElementsDocument (xDataXML_element * element)
Definition at line 798 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 798 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::parentRoot, xDataXML_element_s::parentRoot, and xDataXML_rootElement_s::xData_doc.
Referenced by xDataXML_get_smrUserInterfaceFromElement().
char const* xDataXML_getFileName (xDataXML_document * doc)
Definition at line 767 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 767 of file xDataTOM_importXML.cc
References xDataXML_document_s::fileName.
xDataXML_element* xDataXML_getFirstElement (xDataXML_element * element)
Definition at line 414 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 414 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, and xDataXML_element_s::childrenRoot.
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_getElementsByTagName(), xDataXML_getFirstItem(), xDataXML_KalbachMannToTOM(), xDataXML_numberOfElementsByTagName(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), and xDataXML_XYsToTOM().
enum xDataXML_itemMode xDataXML_getFirstItem (xDataXML_element * element, xDataXML_item * item)
Definition at line 419 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 419 of file xDataTOM_importXML.cc
References xDataXML_item_s::element, xDataXML_text_s::length, xDataXML_item_s::mode, xDataXML_item_s::parentElement, xDataXML_text_s::text, xDataXML_element_s::text, xDataXML_item_s::text, xDataXML_item_s::textLength, xDataXML_element_s::textOffset, xDataXML_item_s::textOffset, xDataXML_getFirstElement(), xDataXML_itemModeElement, xDataXML_itemModeEnd, and xDataXML_itemModeText.
xDataXML_element* xDataXML_getNextElement (xDataXML_element * element)
Definition at line 415 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 415 of file xDataTOM_importXML.cc
References xDataXML_element_s::next.
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_getElementsByTagName(), xDataXML_KalbachMannToTOM(), xDataXML_numberOfElementsByTagName(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), and xDataXML_XYsToTOM().
enum xDataXML_itemMode xDataXML_getNextItem (xDataXML_item * item)
Definition at line 439 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 439 of file xDataTOM_importXML.cc
References xDataXML_item_s::element, xDataXML_text_s::length, xDataXML_item_s::mode, xDataXML_element_s::next, xDataXML_item_s::parentElement, xDataXML_text_s::text, xDataXML_element_s::text, xDataXML_item_s::text, xDataXML_item_s::textLength, xDataXML_element_s::textOffset, xDataXML_item_s::textOffset, xDataXML_itemModeElement, xDataXML_itemModeEnd, and xDataXML_itemModeText.
xDataXML_element* xDataXML_getOneElementByTagName (statusMessageReporting * smr, xDataXML_element * element, char * name, int required)
Definition at line 684 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 684 of file xDataTOM_importXML.cc
References xDataXML_elementListItem_s::element, xDataXML_element_s::fullName, xDataXML_elementList_s::items, xDataXML_elementList_s::n, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_freeElementList(), xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_getElementsByTagName().
char const* xDataXML_getRealFileName (xDataXML_document * doc)
Definition at line 774 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 774 of file xDataTOM_importXML.cc
References xDataXML_document_s::realFileName.
xDataTOM_TOM* xDataXML_importFile (statusMessageReporting * smr, char const * fileName)
Definition at line 63 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 63 of file xDataTOM_importXML.cc
References xDataTOM_TOM_s::root, xDataTOM_freeTOM(), xDataTOM_mallocTOM(), xDataTOM_setFileNameTOM(), xDataXML_constructTOM(), xDataXML_freeDoc(), xDataXML_getDocumentsElement(), and xDataXML_importFile2().
Referenced by xDataTOM_importFile().
xDataXML_document* xDataXML_importFile2 (statusMessageReporting * smr, char const * fileName)
Definition at line 90 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 90 of file xDataTOM_importXML.cc
References buffer, close(), f, n, Acts::open, xDataXML_document_s::smr, smr_isOk(), smr_setReportError2, xDataTOM_smrLibraryID, xDataXML_endXMLParsing(), xDataXML_errFileError, xDataXML_freeDoc(), xDataXML_mallocDoc(), xDataXML_parse(), and xDataXML_setFileName().
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), and xDataXML_importFile().
void* xDataXML_initializeData (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE, char const * ID, size_t size)
Definition at line 1009 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 1009 of file xDataTOM_importXML.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, smr_freeMemory(), xData_initializeData(), xDataTOM_element_s::xDataInfo, and xDataXML_axesElememtToTOM().
Referenced by xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsToTOM().
int xDataXML_is_xDataType (statusMessageReporting * smr, xDataXMLType * xDT, char const *const type, int setMsg)
Definition at line 753 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 753 of file xDataTOM_importXML.cc
References xDataXMLType_s::element, xDataXML_element_s::fullName, xDataXMLType_s::ID, smr_setReportError3, xDataTOM_smrLibraryID, and xDataXML_get_smrUserInterfaceFromElement().
int xDataXML_isAttributeInElement (xDataXML_element * element, char const * name)
Definition at line 479 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 479 of file xDataTOM_importXML.cc
References xDataXML_element_s::attributes, and xDataXML_isAttributeInList().
int xDataXML_isAttributeInList (xDataXML_attributionList * attributes, char const * name)
Definition at line 467 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 467 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, xDataXML_attribute_s::name, and xDataXML_attributionList_s::number.
Referenced by xDataXML_isAttributeInElement().
int xDataXML_KalbachMannToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 21 of file xDataTOM_importXML_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 21 of file xDataTOM_importXML_KalbachMann.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_KalbachMann_s::coefficients, xDataTOM_xDataInfo_s::data, check_license::err(), BTOF::length, xDataXML_element_s::name, xDataTOM_KalbachMann_s::numberOfEnergies, smr_freeMemory(), smr_setReportError3, xDataTOM_KalbachMann_s::type, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getLabel(), xDataTOM_KalbachMann_ID, xDataTOM_KalbachMann_initialize(), xDataTOM_KalbachMannType_fr, xDataTOM_KalbachMannType_fra, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getAttributesValueInElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_KalbachMannCoefficientsToTOM(), and xDataXML_numberOfElementsByTagName().
Referenced by xDataXML_constructTOM().
int xDataXML_numberOfElementsByTagName (statusMessageReporting * smr, xDataXML_element * element, char const * tagName)
Definition at line 647 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 647 of file xDataTOM_importXML.cc
References n, xDataXML_element_s::name, xDataXML_getFirstElement(), and xDataXML_getNextElement().
Referenced by xDataXML_getElementsByTagName(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsDataToTOM().
int xDataXML_parseIsError (xDataXML_document * doc)
Definition at line 406 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 406 of file xDataTOM_importXML.cc
References xDataXML_document_s::status, and xDataXML_statusError.
int xDataXML_polynomialToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 20 of file xDataTOM_importXML_polynomial.cc.
View newest version in sPHENIX GitHub at line 20 of file xDataTOM_importXML_polynomial.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_polynomial_s::coefficients, xDataTOM_xDataInfo_s::data, check_license::err(), BTOF::length, xDataXML_element_s::name, smr_freeMemory(), smr_setReportError3p, xDataXML_text_s::text, xDataXML_element_s::text, xDataTOM_element_s::xDataInfo, xDataTOM_polynomial_ID, xDataTOM_polynomial_initialize(), xDataTOM_polynomial_release(), xDataTOM_smrLibraryID, xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), and xDataXML_stringToDoubles().
Referenced by xDataXML_constructTOM().
int xDataXML_regionsW_XYs_LegendreSeriesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_regionsW_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_regionsW_XYs_LegendreSeries.cc
References xDataTOM_regionsW_XYs_LegendreSeries_s::axes, xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), BTOF::length, xDataXML_element_s::name, smr_setReportError3, xDataTOM_regionsW_XYs_LegendreSeries_s::W_XYs_LegendreSeries, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getLabel(), xDataTOM_regionsW_XYs_LegendreSeries_ID, xDataTOM_regionsW_XYs_LegendreSeries_initialize(), xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_numberOfElementsByTagName(), and xDataXML_regionsW_XYs_LegendreSeries_regionToTOM().
Referenced by xDataXML_constructTOM().
int xDataXML_regionsXYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 23 of file xDataTOM_importXML_regionsXYs.cc.
View newest version in sPHENIX GitHub at line 23 of file xDataTOM_importXML_regionsXYs.cc
References xDataTOM_regionsXYs_s::axes, xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), xDataTOM_regionsXYs_s::length, xDataXML_element_s::name, smr_malloc2, smr_setReportError3, xDataTOM_element_s::xDataInfo, xDataTOM_regionsXYs_ID, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_numberOfElementsByTagName(), xDataXML_regionsXYs_regionToTOM(), and xDataTOM_regionsXYs_s::XYs.
Referenced by xDataXML_constructTOM().
int xDataXML_stringTo_double (statusMessageReporting * smr, void * smrUserInterface, char const * c, double * value, char const * endings, char ** e)
Definition at line 891 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 891 of file xDataTOM_importXML.cc
References n, smr_setReportError3, tmp, xDataTOM_smrLibraryID, and xDataXML_shortStringForMessage().
Referenced by xDataXML_stringToDoubles().
int xDataXML_stringTo_xDataTOM_Int (statusMessageReporting * smr, void * smrUserInterface, char const * c, xDataTOM_Int * value, char const * endings, char ** e)
Definition at line 858 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 858 of file xDataTOM_importXML.cc
References n, smr_setReportError3, tmp, xDataTOM_smrLibraryID, and xDataXML_shortStringForMessage().
int xDataXML_stringToDoubles (statusMessageReporting * smr, xDataXML_element * XE, char const * s, int length, double * d)
Definition at line 96 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 96 of file xDataTOM_importXML_XYs.cc
References e1, BTOF::length, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_stringTo_double().
Referenced by xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_LegendreSeriesDataToTOM(), xDataXML_polynomialToTOM(), and xDataXML_XYsDataToTOM().
int xDataXML_V_W_XYs_LegendreSeriesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_V_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_V_W_XYs_LegendreSeries.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), int(), BTOF::length, xDataXML_element_s::name, smr_setReportError3, xDataTOM_V_W_XYs_LegendreSeries_s::W_XYs_LegendreSeries, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getLabel(), xDataTOM_smrLibraryID, xDataTOM_V_W_XYs_LegendreSeries_ID, xDataTOM_V_W_XYs_LegendreSeries_initialize(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_numberOfElementsByTagName(), and xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM().
Referenced by xDataXML_constructTOM().
int xDataXML_V_W_XYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 21 of file xDataTOM_importXML_V_W_XYs.cc.
View newest version in sPHENIX GitHub at line 21 of file xDataTOM_importXML_V_W_XYs.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), BTOF::length, xDataXML_element_s::name, smr_freeMemory(), smr_setReportError3, xDataTOM_V_W_XYs_s::W_XYs, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getLabel(), xDataTOM_smrLibraryID, xDataTOM_V_W_XYs_ID, xDataTOM_V_W_XYs_initialize(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_numberOfElementsByTagName(), and xDataXML_V_W_XYs_W_XYsToTOM().
Referenced by xDataXML_constructTOM().
int xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_LegendreSeries * LegendreSeries)
Definition at line 58 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 58 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc
References BTOF::length, xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), and xDataXML_LegendreSeriesDataToTOM().
Referenced by xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYs_LegendreSeriesToTOM().
int xDataXML_W_XYs_LegendreSeriesToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_W_XYs_LegendreSeries.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), xDataTOM_W_XYs_LegendreSeries_s::LegendreSeries, BTOF::length, xDataXML_element_s::name, smr_setReportError3, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getLabel(), xDataTOM_smrLibraryID, xDataTOM_subAxesType_proxy, xDataTOM_W_XYs_LegendreSeries_ID, xDataTOM_W_XYs_LegendreSeries_initialize(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_initializeData(), xDataXML_numberOfElementsByTagName(), and xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM().
Referenced by xDataXML_constructTOM().
int xDataXML_W_XYsDataToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_W_XYs * W_XYs, int index, double value, xDataTOM_axes * axes, int axesOffset)
Definition at line 41 of file xDataTOM_importXML_W_XYs.cc.
View newest version in sPHENIX GitHub at line 41 of file xDataTOM_importXML_W_XYs.cc
References check_license::err(), BTOF::length, xDataXML_element_s::name, smr_setReportError3, xDataTOM_axes_getLabel(), xDataTOM_smrLibraryID, xDataTOM_W_XYs_initialize(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_numberOfElementsByTagName(), xDataXML_W_XYs_XYsToTOM(), and xDataTOM_W_XYs_s::XYs.
Referenced by xDataXML_V_W_XYs_W_XYsToTOM(), and xDataXML_W_XYsToTOM().
int xDataXML_W_XYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_W_XYs.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_W_XYs.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), smr_freeMemory(), xDataTOM_element_s::xDataInfo, xDataTOM_W_XYs_ID, xDataXML_initializeData(), and xDataXML_W_XYsDataToTOM().
Referenced by xDataXML_constructTOM().
int xDataXML_xDataTypeConvertAttributes (statusMessageReporting * smr, xDataXML_element * element)
Definition at line 559 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 559 of file xDataTOM_importXML.cc
References xDataXMLType_s::end, xDataXMLType_s::endPresent, xDataXMLType_s::index, xDataXMLType_s::indexPresent, xDataXMLType_s::length, xDataXMLType_s::lengthPresent, smr_setReportError3, smr_setReportError3p, xDataXMLType_s::start, xDataXMLType_s::startPresent, xDataTOM_smrLibraryID, xDataXML_element_s::xDataTypeInfo, xDataXML_convertAttributeTo_xDataTOM_Int(), and xDataXML_get_smrUserInterfaceFromElement().
int xDataXML_XYsDataToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_XYs * XYs, int index, int length, double value, double accuracy, enum xDataTOM_subAxesType subAxesType, int axesOffest, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 76 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 76 of file xDataTOM_importXML_XYs.cc
References xDataTOM_XYs_s::accuracy, xDataTOM_XYs_s::data, check_license::err(), xDataTOM_XYs_s::index, BTOF::length, xDataTOM_XYs_s::length, smr_freeMemory(), smr_malloc2, xDataTOM_XYs_s::subAxes, xDataXML_text_s::text, xDataXML_element_s::text, xDataTOM_XYs_s::value, xDataTOM_subAxes_initialize(), and xDataXML_stringToDoubles().
Referenced by xDataXML_regionsXYs_XYsToTOM(), xDataXML_W_XYs_XYsToTOM(), and xDataXML_XYsDataToTOM2().
int xDataXML_XYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_XYs.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::element, check_license::err(), BTOF::length, xDataXML_element_s::name, smr_setReportError3p, xDataTOM_element_s::xDataInfo, xDataTOM_smrLibraryID, xDataXML_axesElememtToTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), and xDataXML_XYsDataToTOM2().
Referenced by xDataXML_constructTOM().