ECCE @ EIC Software: XrayTelAnalysis Class Reference
XrayTelAnalysis Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelAnalysis.hh>
Public Member Functions
~XrayTelAnalysis ()
void book (G4bool isMaster)
void finish (G4bool isMaster)
void analyseStepping (const G4Track &track, G4bool entering)
void Update (G4double energy, G4int threadID)
Static Public Member Functions
static XrayTelAnalysis * getInstance ()
Private Member Functions
XrayTelAnalysis ()
Private Attributes
G4double eKin
G4double x
G4double y
G4double z
G4double dirX
G4double dirY
G4double dirZ
G4String asciiFileName
G4String histFileName
std::ofstream * asciiFile
std::map< G4int, G4int > * nEnteringTracks
std::map< G4int, G4double > * totEnteringEnergy
Static Private Attributes
static XrayTelAnalysis * instance = 0
Detailed Description
Definition at line 57 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 57 of file XrayTelAnalysis.hh
Constructor & Destructor Documentation
XrayTelAnalysis::~XrayTelAnalysis ()
Definition at line 74 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 74 of file XrayTelAnalysis.cc
References asciiFile, nEnteringTracks, and totEnteringEnergy.
XrayTelAnalysis::XrayTelAnalysis () private
Definition at line 61 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 61 of file XrayTelAnalysis.cc
References asciiFile, asciiFileName, G4endl, and histFileName.
Referenced by getInstance().
Member Function Documentation
void XrayTelAnalysis::analyseStepping (const G4Track & track, G4bool entering)
Definition at line 232 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 232 of file XrayTelAnalysis.cc
References G4VAnalysisManager::AddNtupleRow(), asciiFile, dir, dirX, dirY, dirZ, eKin, G4VAnalysisManager::FillH1(), G4VAnalysisManager::FillH2(), G4VAnalysisManager::FillNtupleDColumn(), G4endl, G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4ToolsAnalysisManager::Instance(), keV, mm, pos(), right, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by XrayTelSteppingAction::UserSteppingAction().
void XrayTelAnalysis::book (G4bool isMaster)
Definition at line 94 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 94 of file XrayTelAnalysis.cc
References G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::FinishNtuple(), G4cout, G4endl, histFileName, G4ToolsAnalysisManager::Instance(), nEnteringTracks, G4VAnalysisManager::OpenFile(), G4VAnalysisManager::SetFirstHistoId(), and totEnteringEnergy.
Referenced by XrayTelRunAction::BeginOfRunAction().
void XrayTelAnalysis::finish (G4bool isMaster)
Definition at line 149 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 149 of file XrayTelAnalysis.cc
References asciiFile, G4VAnalysisManager::CloseFile(), G4cout, G4endl, G4ToolsAnalysisManager::Instance(), MeV, nEnteringTracks, part, totEnteringEnergy, and G4VAnalysisManager::Write().
Referenced by XrayTelRunAction::EndOfRunAction().
XrayTelAnalysis * XrayTelAnalysis::getInstance () static
Definition at line 85 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 85 of file XrayTelAnalysis.cc
References instance, and XrayTelAnalysis().
Referenced by XrayTelRunAction::BeginOfRunAction(), XrayTelRunAction::EndOfRunAction(), and XrayTelSteppingAction::UserSteppingAction().
void XrayTelAnalysis::Update (G4double energy, G4int threadID)
Definition at line 294 of file XrayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 294 of file XrayTelAnalysis.cc
References nEnteringTracks, and totEnteringEnergy.
Referenced by XrayTelSteppingAction::UserSteppingAction().
Member Data Documentation
std::ofstream* XrayTelAnalysis::asciiFile private
Definition at line 91 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 91 of file XrayTelAnalysis.hh
Referenced by analyseStepping(), finish(), XrayTelAnalysis(), and ~XrayTelAnalysis().
G4String XrayTelAnalysis::asciiFileName private
Definition at line 88 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 88 of file XrayTelAnalysis.hh
Referenced by XrayTelAnalysis().
G4double XrayTelAnalysis::dirX private
Definition at line 84 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 84 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
G4double XrayTelAnalysis::dirY private
Definition at line 85 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 85 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
G4double XrayTelAnalysis::dirZ private
Definition at line 86 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
G4double XrayTelAnalysis::eKin private
Definition at line 80 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 80 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
G4String XrayTelAnalysis::histFileName private
Definition at line 89 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 89 of file XrayTelAnalysis.hh
Referenced by book(), and XrayTelAnalysis().
XrayTelAnalysis * XrayTelAnalysis::instance = 0 static private
Definition at line 77 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 77 of file XrayTelAnalysis.hh
Referenced by getInstance().
std::map<G4int,G4int>* XrayTelAnalysis::nEnteringTracks private
Definition at line 94 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 94 of file XrayTelAnalysis.hh
Referenced by book(), finish(), Update(), and ~XrayTelAnalysis().
std::map<G4int,G4double>* XrayTelAnalysis::totEnteringEnergy private
Definition at line 95 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 95 of file XrayTelAnalysis.hh
Referenced by book(), finish(), Update(), and ~XrayTelAnalysis().
G4double XrayTelAnalysis::x private
Definition at line 81 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 81 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
G4double XrayTelAnalysis::y private
Definition at line 82 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 82 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
G4double XrayTelAnalysis::z private
Definition at line 83 of file XrayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 83 of file XrayTelAnalysis.hh
Referenced by analyseStepping().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelAnalysis.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/src/XrayTelAnalysis.cc