ECCE @ EIC Software: WLSTrajectory Class Reference
WLSTrajectory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSTrajectory.hh>
Public Member Functions
WLSTrajectory ()
WLSTrajectory (const G4Track *)
WLSTrajectory (WLSTrajectory &)
virtual ~WLSTrajectory ()
void * operator new (size_t)
void operator delete (void *)
int operator== (const WLSTrajectory &right) const
virtual G4int GetTrackID () const
virtual G4int GetParentID () const
virtual G4String GetParticleName () const
virtual G4double GetCharge () const
virtual G4int GetPDGEncoding () const
virtual G4ThreeVector GetInitialMomentum () const
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void AppendStep (const G4Step *aStep)
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ParticleDefinition * GetParticleDefinition ()
virtual int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
virtual void DrawTrajectory () const
Private Attributes
WLSTrajectoryPointContainer * fpPointsContainer
G4int fTrackID
G4int fParentID
G4double fPDGCharge
G4int fPDGEncoding
G4String fParticleName
G4ThreeVector fInitialMomentum
G4ParticleDefinition * fParticleDefinition
Detailed Description
Definition at line 52 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 52 of file WLSTrajectory.hh
Constructor & Destructor Documentation
WLSTrajectory::WLSTrajectory ()
Definition at line 58 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 58 of file WLSTrajectory.cc
References fParticleDefinition.
WLSTrajectory::WLSTrajectory (const G4Track * aTrack)
Definition at line 68 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 68 of file WLSTrajectory.cc
References fInitialMomentum, fParentID, fParticleDefinition, fParticleName, fPDGCharge, fPDGEncoding, fpPointsContainer, fTrackID, G4Track::GetDefinition(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), and G4Track::GetTrackID().
WLSTrajectory::WLSTrajectory (WLSTrajectory & right)
Definition at line 84 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 84 of file WLSTrajectory.cc
References fInitialMomentum, fParentID, fParticleDefinition, fParticleName, fPDGCharge, fPDGEncoding, fpPointsContainer, and fTrackID.
WLSTrajectory::~WLSTrajectory () virtual
Definition at line 104 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 104 of file WLSTrajectory.cc
References fpPointsContainer.
Member Function Documentation
void WLSTrajectory::AppendStep (const G4Step * aStep) virtual
Implements G4VTrajectory.
Definition at line 125 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 125 of file WLSTrajectory.cc
References fpPointsContainer.
std::vector< G4AttValue > * WLSTrajectory::CreateAttValues () const virtual
Reimplemented from G4VTrajectory.
Definition at line 197 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 197 of file WLSTrajectory.cc
References G4UIcommand::ConvertToString(), fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fTrackID, G4BestUnit, G4cout, GetAttDefs(), GetPointEntries(), CLHEP::Hep3Vector::mag(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * WLSTrajectory::GetAttDefs () const virtual
Reimplemented from G4VTrajectory.
Definition at line 155 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 155 of file WLSTrajectory.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues().
virtual G4double WLSTrajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 78 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 78 of file WLSTrajectory.hh
References fPDGCharge.
virtual G4ThreeVector WLSTrajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 80 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 80 of file WLSTrajectory.hh
References fInitialMomentum.
virtual G4int WLSTrajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 76 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 76 of file WLSTrajectory.hh
References fParentID.
G4ParticleDefinition * WLSTrajectory::GetParticleDefinition ()
Definition at line 132 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 132 of file WLSTrajectory.cc
References fParticleName, and G4ParticleTable::GetParticleTable().
virtual G4String WLSTrajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 77 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 77 of file WLSTrajectory.hh
References fParticleName.
virtual G4int WLSTrajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 79 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 79 of file WLSTrajectory.hh
References fPDGEncoding.
virtual G4VTrajectoryPoint* WLSTrajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Definition at line 93 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 93 of file WLSTrajectory.hh
References fpPointsContainer.
virtual int WLSTrajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Definition at line 91 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 91 of file WLSTrajectory.hh
References fpPointsContainer.
Referenced by CreateAttValues(), and MergeTrajectory().
virtual G4int WLSTrajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 75 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 75 of file WLSTrajectory.hh
References fTrackID.
void WLSTrajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Definition at line 139 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 139 of file WLSTrajectory.cc
References fpPointsContainer, GetPointEntries(), and second.
void WLSTrajectory::operator delete (void * aTrajectory) inline
Definition at line 126 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 126 of file WLSTrajectory.hh
References WLSTrajectoryAllocator.
void * WLSTrajectory::operator new (size_t) inline
Definition at line 120 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 120 of file WLSTrajectory.hh
References WLSTrajectoryAllocator.
int WLSTrajectory::operator== (const WLSTrajectory & right) const inline
Definition at line 70 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 70 of file WLSTrajectory.hh
void WLSTrajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4VTrajectory.
Definition at line 116 of file WLSTrajectory.cc.
View newest version in sPHENIX GitHub at line 116 of file WLSTrajectory.cc
References G4VTrajectory::ShowTrajectory().
Member Data Documentation
G4ThreeVector WLSTrajectory::fInitialMomentum private
Definition at line 112 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 112 of file WLSTrajectory.hh
Referenced by CreateAttValues(), GetInitialMomentum(), and WLSTrajectory().
G4int WLSTrajectory::fParentID private
Definition at line 108 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 108 of file WLSTrajectory.hh
Referenced by CreateAttValues(), GetParentID(), and WLSTrajectory().
G4ParticleDefinition* WLSTrajectory::fParticleDefinition private
Definition at line 114 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 114 of file WLSTrajectory.hh
Referenced by WLSTrajectory().
G4String WLSTrajectory::fParticleName private
Definition at line 111 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 111 of file WLSTrajectory.hh
Referenced by CreateAttValues(), GetParticleDefinition(), GetParticleName(), and WLSTrajectory().
G4double WLSTrajectory::fPDGCharge private
Definition at line 109 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 109 of file WLSTrajectory.hh
Referenced by CreateAttValues(), GetCharge(), and WLSTrajectory().
G4int WLSTrajectory::fPDGEncoding private
Definition at line 110 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 110 of file WLSTrajectory.hh
Referenced by CreateAttValues(), GetPDGEncoding(), and WLSTrajectory().
WLSTrajectoryPointContainer* WLSTrajectory::fpPointsContainer private
Definition at line 105 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 105 of file WLSTrajectory.hh
Referenced by AppendStep(), GetPoint(), GetPointEntries(), MergeTrajectory(), WLSTrajectory(), and ~WLSTrajectory().
G4int WLSTrajectory::fTrackID private
Definition at line 107 of file WLSTrajectory.hh.
View newest version in sPHENIX GitHub at line 107 of file WLSTrajectory.hh
Referenced by CreateAttValues(), GetTrackID(), and WLSTrajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSTrajectory.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSTrajectory.cc