ECCE @ EIC Software: G4AblaVirtualData Class Reference
G4AblaVirtualData Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4AblaVirtualData.hh>
Public Member Functions
G4bool setAlpha (G4int A, G4int Z, G4double value)
G4bool setEcnz (G4int A, G4int Z, G4double value)
G4bool setVgsld (G4int A, G4int Z, G4double value)
G4bool setPace2 (G4int A, G4int Z, G4double value)
G4bool setRms (G4int A, G4int Z, G4double value)
G4bool setMexp (G4int A, G4int Z, G4double value)
G4bool setMexpID (G4int A, G4int Z, G4int value)
G4bool setBeta2 (G4int A, G4int Z, G4double value)
G4bool setBeta4 (G4int A, G4int Z, G4double value)
G4double getAlpha (G4int A, G4int Z)
G4double getEcnz (G4int A, G4int Z)
G4double getVgsld (G4int A, G4int Z)
G4double getPace2 (G4int A, G4int Z)
G4double getRms (G4int A, G4int Z)
G4double getMexp (G4int A, G4int Z)
G4int getMexpID (G4int A, G4int Z)
G4double getBeta2 (G4int A, G4int Z)
G4double getBeta4 (G4int A, G4int Z)
G4int getAlphaRows ()
G4int getAlphaCols ()
G4int getPaceRows ()
G4int getPaceCols ()
virtual G4bool readData ()=0
Protected Member Functions
G4AblaVirtualData ()
virtual ~G4AblaVirtualData ()
Private Attributes
G4double alpha [alphaRows][alphaCols]
G4double ecnz [alphaRows][alphaCols]
G4double vgsld [alphaRows][alphaCols]
G4double pace2 [paceRows][paceCols]
G4double rms [rmsRows][rmsCols]
G4double mexp [massRows][massCols]
G4int mexpid [massRows][massCols]
G4double beta2 [betaRows][betaCols]
G4double beta4 [betaRows][betaCols]
Static Private Attributes
static const G4int alphaRows = 154
static const G4int alphaCols = 99
static const G4int paceRows = 500
static const G4int paceCols = 500
static const G4int rmsRows = 154
static const G4int rmsCols = 99
static const G4int betaRows = 251
static const G4int betaCols = 137
static const G4int massRows = 154
static const G4int massCols = 13
Detailed Description
An interface to data used by ABLA. This interface allows us to abstract the actual source of data. Currently the data is read from datafiles by using class G4AblaDataFile.
See Also
G4AblaDataFile
Definition at line 55 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 55 of file G4AblaVirtualData.hh
Constructor & Destructor Documentation
G4AblaVirtualData::G4AblaVirtualData () protected
Constructor, destructor
Definition at line 41 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 41 of file G4AblaVirtualData.cc
Referenced by G4AblaDataFile::G4AblaDataFile().
G4AblaVirtualData::~G4AblaVirtualData () protected virtual
Definition at line 45 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 45 of file G4AblaVirtualData.cc
Member Function Documentation
double G4AblaVirtualData::getAlpha (G4int A, G4int Z)
Get the value of Alpha.
Definition at line 111 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 111 of file G4AblaVirtualData.cc
References A(), alpha, and Z.
Referenced by G4Abla::initEvapora().
int G4AblaVirtualData::getAlphaCols ()
Definition at line 161 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 161 of file G4AblaVirtualData.cc
References alphaCols.
int G4AblaVirtualData::getAlphaRows ()
Definition at line 156 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 156 of file G4AblaVirtualData.cc
References alphaRows.
double G4AblaVirtualData::getBeta2 (G4int A, G4int Z)
Get the value of beta2 deformation.
Definition at line 146 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 146 of file G4AblaVirtualData.cc
References A(), beta2, and Z.
Referenced by G4Abla::initEvapora().
double G4AblaVirtualData::getBeta4 (G4int A, G4int Z)
Get the value of beta4 deformation.
Definition at line 151 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 151 of file G4AblaVirtualData.cc
References A(), beta4, and Z.
Referenced by G4Abla::initEvapora().
double G4AblaVirtualData::getEcnz (G4int A, G4int Z)
Get the value of Ecnz.
Definition at line 116 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 116 of file G4AblaVirtualData.cc
References A(), ecnz, and Z.
Referenced by G4Abla::initEvapora().
double G4AblaVirtualData::getMexp (G4int A, G4int Z)
Get the value of experimental masses.
Definition at line 136 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 136 of file G4AblaVirtualData.cc
References A(), mexp, and Z.
Referenced by G4Abla::initEvapora().
int G4AblaVirtualData::getMexpID (G4int A, G4int Z)
Get the value of experimental masses ID.
Definition at line 141 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 141 of file G4AblaVirtualData.cc
References A(), mexpid, and Z.
Referenced by G4Abla::initEvapora().
double G4AblaVirtualData::getPace2 (G4int A, G4int Z)
Get the value of Pace2.
Definition at line 126 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 126 of file G4AblaVirtualData.cc
References A(), pace2, and Z.
Referenced by G4Abla::initEvapora(), and G4AblaDataFile::readData().
int G4AblaVirtualData::getPaceCols ()
Definition at line 169 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 169 of file G4AblaVirtualData.cc
References paceCols.
Referenced by G4AblaDataFile::readData().
int G4AblaVirtualData::getPaceRows ()
Definition at line 165 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 165 of file G4AblaVirtualData.cc
References paceRows.
Referenced by G4AblaDataFile::readData().
double G4AblaVirtualData::getRms (G4int A, G4int Z)
Get the value of RMS.
Definition at line 131 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 131 of file G4AblaVirtualData.cc
References A(), rms, and Z.
Referenced by G4Abla::initEvapora().
double G4AblaVirtualData::getVgsld (G4int A, G4int Z)
Get the value of Vgsld.
Definition at line 121 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 121 of file G4AblaVirtualData.cc
References A(), vgsld, and Z.
Referenced by G4Abla::initEvapora().
virtual G4bool G4AblaVirtualData::readData () pure virtual
Implemented in G4AblaDataFile.
bool G4AblaVirtualData::setAlpha (G4int A, G4int Z, G4double value)
Set the value of Alpha.
Definition at line 47 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 47 of file G4AblaVirtualData.cc
References A(), alpha, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setBeta2 (G4int A, G4int Z, G4double value)
Set the value of beta2 deformation.
Definition at line 96 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 96 of file G4AblaVirtualData.cc
References A(), beta2, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setBeta4 (G4int A, G4int Z, G4double value)
Set the value of beta4 deformation.
Definition at line 103 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 103 of file G4AblaVirtualData.cc
References A(), beta4, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setEcnz (G4int A, G4int Z, G4double value)
Set the value of Ecnz.
Definition at line 54 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 54 of file G4AblaVirtualData.cc
References A(), ecnz, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setMexp (G4int A, G4int Z, G4double value)
Set the value of experimental masses.
Definition at line 82 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 82 of file G4AblaVirtualData.cc
References A(), mexp, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setMexpID (G4int A, G4int Z, G4int value)
Set the value of experimental masses ID.
Definition at line 89 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 89 of file G4AblaVirtualData.cc
References A(), mexpid, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setPace2 (G4int A, G4int Z, G4double value)
Set the value of Pace2.
Definition at line 68 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 68 of file G4AblaVirtualData.cc
References A(), pace2, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setRms (G4int A, G4int Z, G4double value)
Set the value of RMS.
Definition at line 75 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 75 of file G4AblaVirtualData.cc
References A(), rms, and Z.
Referenced by G4AblaDataFile::readData().
bool G4AblaVirtualData::setVgsld (G4int A, G4int Z, G4double value)
Set the value of Vgsld.
Definition at line 61 of file G4AblaVirtualData.cc.
View newest version in sPHENIX GitHub at line 61 of file G4AblaVirtualData.cc
References A(), vgsld, and Z.
Referenced by G4AblaDataFile::readData().
Member Data Documentation
G4double G4AblaVirtualData::alpha[alphaRows][alphaCols] private
Definition at line 185 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 185 of file G4AblaVirtualData.hh
Referenced by getAlpha(), and setAlpha().
const G4int G4AblaVirtualData::alphaCols = 99 static private
Definition at line 171 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 171 of file G4AblaVirtualData.hh
Referenced by getAlphaCols().
const G4int G4AblaVirtualData::alphaRows = 154 static private
Definition at line 170 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 170 of file G4AblaVirtualData.hh
Referenced by getAlphaRows().
G4double G4AblaVirtualData::beta2[betaRows][betaCols] private
Definition at line 192 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 192 of file G4AblaVirtualData.hh
Referenced by getBeta2(), and setBeta2().
G4double G4AblaVirtualData::beta4[betaRows][betaCols] private
Definition at line 193 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 193 of file G4AblaVirtualData.hh
Referenced by getBeta4(), and setBeta4().
const G4int G4AblaVirtualData::betaCols = 137 static private
Definition at line 180 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 180 of file G4AblaVirtualData.hh
const G4int G4AblaVirtualData::betaRows = 251 static private
Definition at line 179 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 179 of file G4AblaVirtualData.hh
G4double G4AblaVirtualData::ecnz[alphaRows][alphaCols] private
Definition at line 186 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 186 of file G4AblaVirtualData.hh
Referenced by getEcnz(), and setEcnz().
const G4int G4AblaVirtualData::massCols = 13 static private
Definition at line 183 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 183 of file G4AblaVirtualData.hh
const G4int G4AblaVirtualData::massRows = 154 static private
Definition at line 182 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 182 of file G4AblaVirtualData.hh
G4double G4AblaVirtualData::mexp[massRows][massCols] private
Definition at line 190 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 190 of file G4AblaVirtualData.hh
Referenced by getMexp(), and setMexp().
G4int G4AblaVirtualData::mexpid[massRows][massCols] private
Definition at line 191 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 191 of file G4AblaVirtualData.hh
Referenced by getMexpID(), and setMexpID().
G4double G4AblaVirtualData::pace2[paceRows][paceCols] private
Definition at line 188 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 188 of file G4AblaVirtualData.hh
Referenced by getPace2(), and setPace2().
const G4int G4AblaVirtualData::paceCols = 500 static private
Definition at line 174 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 174 of file G4AblaVirtualData.hh
Referenced by getPaceCols().
const G4int G4AblaVirtualData::paceRows = 500 static private
Definition at line 173 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 173 of file G4AblaVirtualData.hh
Referenced by getPaceRows().
G4double G4AblaVirtualData::rms[rmsRows][rmsCols] private
Definition at line 189 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 189 of file G4AblaVirtualData.hh
Referenced by getRms(), and setRms().
const G4int G4AblaVirtualData::rmsCols = 99 static private
Definition at line 177 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 177 of file G4AblaVirtualData.hh
const G4int G4AblaVirtualData::rmsRows = 154 static private
Definition at line 176 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 176 of file G4AblaVirtualData.hh
G4double G4AblaVirtualData::vgsld[alphaRows][alphaCols] private
Definition at line 187 of file G4AblaVirtualData.hh.
View newest version in sPHENIX GitHub at line 187 of file G4AblaVirtualData.hh
Referenced by getVgsld(), and setVgsld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4AblaVirtualData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/src/G4AblaVirtualData.cc