ECCE @ EIC Software: G4DNAWaterExcitationStructure Class Reference
G4DNAWaterExcitationStructure Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAWaterExcitationStructure.hh>
Public Member Functions
G4DNAWaterExcitationStructure ()
virtual ~G4DNAWaterExcitationStructure ()
G4double ExcitationEnergy (G4int level)
G4int NumberOfLevels ()
Private Attributes
G4int nLevels
std::vector< G4double > energyConstant
Detailed Description
Definition at line 33 of file G4DNAWaterExcitationStructure.hh.
View newest version in sPHENIX GitHub at line 33 of file G4DNAWaterExcitationStructure.hh
Constructor & Destructor Documentation
G4DNAWaterExcitationStructure::G4DNAWaterExcitationStructure ()
Definition at line 29 of file G4DNAWaterExcitationStructure.cc.
View newest version in sPHENIX GitHub at line 29 of file G4DNAWaterExcitationStructure.cc
References energyConstant, eV, and nLevels.
G4DNAWaterExcitationStructure::~G4DNAWaterExcitationStructure () virtual
Definition at line 41 of file G4DNAWaterExcitationStructure.cc.
View newest version in sPHENIX GitHub at line 41 of file G4DNAWaterExcitationStructure.cc
Member Function Documentation
G4double G4DNAWaterExcitationStructure::ExcitationEnergy (G4int level)
Definition at line 45 of file G4DNAWaterExcitationStructure.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DNAWaterExcitationStructure.cc
References energyConstant, and nLevels.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), G4EmDNAChemistry_option2::ConstructDissociationChannels(), G4DNAChemistryManager::CreateWaterMolecule(), G4TDNAOneStepThermalizationModel< MODEL >::G4TDNAOneStepThermalizationModel(), G4DNABornExcitationModel1::SampleSecondaries(), G4DNABornExcitationModel2::SampleSecondaries(), and G4DNAPTBExcitationModel::SampleSecondaries().
G4int G4DNAWaterExcitationStructure::NumberOfLevels () inline
Definition at line 43 of file G4DNAWaterExcitationStructure.hh.
View newest version in sPHENIX GitHub at line 43 of file G4DNAWaterExcitationStructure.hh
References nLevels.
Referenced by G4DNAMillerGreenExcitationModel::Initialise().
Member Data Documentation
std::vector<G4double> G4DNAWaterExcitationStructure::energyConstant private
Definition at line 52 of file G4DNAWaterExcitationStructure.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DNAWaterExcitationStructure.hh
Referenced by ExcitationEnergy(), and G4DNAWaterExcitationStructure().
G4int G4DNAWaterExcitationStructure::nLevels private
Definition at line 50 of file G4DNAWaterExcitationStructure.hh.
View newest version in sPHENIX GitHub at line 50 of file G4DNAWaterExcitationStructure.hh
Referenced by ExcitationEnergy(), G4DNAWaterExcitationStructure(), and NumberOfLevels().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAWaterExcitationStructure.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4DNAWaterExcitationStructure.cc