ECCE @ EIC Software: G4ErrorRunManagerHelper Class Reference
G4ErrorRunManagerHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorRunManagerHelper.hh>
Public Member Functions
G4ErrorRunManagerHelper ()
virtual ~G4ErrorRunManagerHelper ()
void SetUserInitialization (G4VUserDetectorConstruction *userInit)
void SetUserInitialization (G4VPhysicalVolume *userInit)
void SetUserInitialization (G4VUserPhysicsList *userInit)
void SetUserAction (G4UserTrackingAction *userAction)
void SetUserAction (G4UserSteppingAction *userAction)
void RunInitialization ()
void InitializeGeometry ()
void InitializePhysics ()
void RunTermination ()
G4VUserPhysicsList * GetUserPhysicsList () const
Static Public Member Functions
static G4ErrorRunManagerHelper * GetRunManagerKernel ()
Private Attributes
G4VUserPhysicsList * theUserPhysicsList
G4VPhysicalVolume * theUserWorld
G4RunManagerKernel * theG4RunManagerKernel
Static Private Attributes
static G4ThreadLocal
G4ErrorRunManagerHelper * fRunManagerKernel = 0
Detailed Description
Definition at line 52 of file G4ErrorRunManagerHelper.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ErrorRunManagerHelper.hh
Constructor & Destructor Documentation
G4ErrorRunManagerHelper::G4ErrorRunManagerHelper ()
Definition at line 55 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ErrorRunManagerHelper.cc
References FatalException, fRunManagerKernel, G4cout, G4endl, G4Exception(), G4RunManagerKernel::GetRunManagerKernel(), G4RunManagerKernel::SetVerboseLevel(), theG4RunManagerKernel, theUserPhysicsList, and theUserWorld.
G4ErrorRunManagerHelper::~G4ErrorRunManagerHelper () virtual
Definition at line 80 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ErrorRunManagerHelper.cc
Member Function Documentation
G4ErrorRunManagerHelper * G4ErrorRunManagerHelper::GetRunManagerKernel () static
Definition at line 50 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ErrorRunManagerHelper.cc
References fRunManagerKernel.
Referenced by G4ErrorPropagatorManager::StartG4ErrorRunManagerHelper().
G4VUserPhysicsList* G4ErrorRunManagerHelper::GetUserPhysicsList () const inline
Definition at line 88 of file G4ErrorRunManagerHelper.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ErrorRunManagerHelper.hh
References theUserPhysicsList.
Referenced by InitializePhysics().
void G4ErrorRunManagerHelper::InitializeGeometry ()
Definition at line 107 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 107 of file G4ErrorRunManagerHelper.cc
References G4RunManagerKernel::DefineWorldVolume(), FatalException, G4Exception(), G4TransportationManager::GetTransportationManager(), theG4RunManagerKernel, and theUserWorld.
Referenced by G4ErrorPropagatorManager::InitGeant4e().
void G4ErrorRunManagerHelper::InitializePhysics ()
Definition at line 129 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 129 of file G4ErrorRunManagerHelper.cc
References G4cout, G4endl, G4Exception(), G4RunManager::GetRunManager(), GetUserPhysicsList(), G4RunManagerKernel::InitializePhysics(), JustWarning, message(), G4RunManagerKernel::SetPhysics(), theG4RunManagerKernel, and theUserPhysicsList.
Referenced by G4ErrorPropagatorManager::InitGeant4e().
void G4ErrorRunManagerHelper::RunInitialization ()
Definition at line 160 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 160 of file G4ErrorRunManagerHelper.cc
References G4RunManagerKernel::RunInitialization(), and theG4RunManagerKernel.
Referenced by G4ErrorPropagatorManager::InitGeant4e().
void G4ErrorRunManagerHelper::RunTermination ()
Definition at line 182 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 182 of file G4ErrorRunManagerHelper.cc
References G4RunManagerKernel::RunTermination(), and theG4RunManagerKernel.
Referenced by G4ErrorPropagatorManager::RunTermination().
void G4ErrorRunManagerHelper::SetUserAction (G4UserTrackingAction * userAction)
Definition at line 167 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 167 of file G4ErrorRunManagerHelper.cc
References G4EventManager::GetEventManager(), and G4EventManager::SetUserAction().
void G4ErrorRunManagerHelper::SetUserAction (G4UserSteppingAction * userAction)
Definition at line 175 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ErrorRunManagerHelper.cc
References G4EventManager::GetEventManager(), and G4EventManager::SetUserAction().
void G4ErrorRunManagerHelper::SetUserInitialization (G4VUserDetectorConstruction * userInit)
Definition at line 86 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ErrorRunManagerHelper.cc
References G4VUserDetectorConstruction::Construct(), and theUserWorld.
Referenced by G4ErrorPropagatorManager::SetUserInitialization().
void G4ErrorRunManagerHelper::SetUserInitialization (G4VPhysicalVolume * userInit)
Definition at line 93 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ErrorRunManagerHelper.cc
References theUserWorld.
void G4ErrorRunManagerHelper::SetUserInitialization (G4VUserPhysicsList * userInit)
Definition at line 100 of file G4ErrorRunManagerHelper.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ErrorRunManagerHelper.cc
References theUserPhysicsList.
Member Data Documentation
G4ThreadLocal G4ErrorRunManagerHelper * G4ErrorRunManagerHelper::fRunManagerKernel = 0 static private
Definition at line 93 of file G4ErrorRunManagerHelper.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ErrorRunManagerHelper.hh
Referenced by G4ErrorRunManagerHelper(), and GetRunManagerKernel().
G4RunManagerKernel* G4ErrorRunManagerHelper::theG4RunManagerKernel private
Definition at line 98 of file G4ErrorRunManagerHelper.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ErrorRunManagerHelper.hh
Referenced by G4ErrorRunManagerHelper(), InitializeGeometry(), InitializePhysics(), RunInitialization(), and RunTermination().
G4VUserPhysicsList* G4ErrorRunManagerHelper::theUserPhysicsList private
Definition at line 95 of file G4ErrorRunManagerHelper.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ErrorRunManagerHelper.hh
Referenced by G4ErrorRunManagerHelper(), GetUserPhysicsList(), InitializePhysics(), and SetUserInitialization().
G4VPhysicalVolume* G4ErrorRunManagerHelper::theUserWorld private
Definition at line 96 of file G4ErrorRunManagerHelper.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ErrorRunManagerHelper.hh
Referenced by G4ErrorRunManagerHelper(), InitializeGeometry(), and SetUserInitialization().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorRunManagerHelper.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorRunManagerHelper.cc