ECCE @ EIC Software: G4LossTableBuilder Class Reference
G4LossTableBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4LossTableBuilder.hh>
Public Member Functions
G4LossTableBuilder (G4bool master=true)
virtual ~G4LossTableBuilder ()
void BuildDEDXTable (G4PhysicsTable *dedxTable, const std::vector< G4PhysicsTable * > &)
void BuildRangeTable (const G4PhysicsTable *dedxTable, G4PhysicsTable *rangeTable, G4bool useBM=false)
void BuildInverseRangeTable (const G4PhysicsTable *rangeTable, G4PhysicsTable *invRangeTable, G4bool useBM=false)
G4PhysicsTable * BuildTableForModel (G4PhysicsTable *table, G4VEmModel *model, const G4ParticleDefinition *, G4double emin, G4double emax, G4bool spline)
void InitialiseBaseMaterials (const G4PhysicsTable *table=nullptr)
const std::vector< G4int > * GetCoupleIndexes () const
const std::vector< G4double > * GetDensityFactors () const
G4bool GetFlag (size_t idx)
void SetSplineFlag (G4bool flag)
void SetInitialisationFlag (G4bool flag)
Private Member Functions
G4LossTableBuilder & operator= (const G4LossTableBuilder &right)
G4LossTableBuilder (const G4LossTableBuilder &)
Private Attributes
G4EmParameters * theParameters
G4bool splineFlag
G4bool isInitialized
G4bool isMaster
Static Private Attributes
static std::vector< G4double > * theDensityFactor = nullptr
static std::vector< G4int > * theDensityIdx = nullptr
static std::vector< G4bool > * theFlag = nullptr
Detailed Description
Definition at line 60 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4LossTableBuilder.hh
Constructor & Destructor Documentation
G4LossTableBuilder::G4LossTableBuilder (G4bool master = true)
Definition at line 78 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 78 of file G4LossTableBuilder.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, G4EmParameters::Instance(), isInitialized, isMaster, splineFlag, theDensityFactor, theDensityIdx, theFlag, and theParameters.
G4LossTableBuilder::~G4LossTableBuilder () virtual
Definition at line 103 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 103 of file G4LossTableBuilder.cc
References isMaster, theDensityFactor, theDensityIdx, and theFlag.
G4LossTableBuilder::G4LossTableBuilder (const G4LossTableBuilder &) private
Member Function Documentation
void G4LossTableBuilder::BuildDEDXTable (G4PhysicsTable * dedxTable, const std::vector< G4PhysicsTable * > & list)
Definition at line 140 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 140 of file G4LossTableBuilder.cc
References G4PhysicsVector::FillSecondDerivatives(), G4PhysicsVector::GetVectorLength(), InitialiseBaseMaterials(), k, G4PhysicsVector::PutValue(), G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), and splineFlag.
Referenced by G4LossTableManager::BuildTables().
void G4LossTableBuilder::BuildInverseRangeTable (const G4PhysicsTable * rangeTable, G4PhysicsTable * invRangeTable, G4bool useBM = false)
Definition at line 259 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 259 of file G4LossTableBuilder.cc
References e, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), G4PhysicsVector::GetVectorLength(), G4LPhysicsFreeVector::PutValues(), r, G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), splineFlag, theFlag, and v.
Referenced by G4LossTableManager::BuildTables(), and G4TablesForExtrapolator::Initialisation().
void G4LossTableBuilder::BuildRangeTable (const G4PhysicsTable * dedxTable, G4PhysicsTable * rangeTable, G4bool useBM = false)
Definition at line 174 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 174 of file G4LossTableBuilder.cc
References energy, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), G4PhysicsVector::GetVectorLength(), k, n, G4PhysicsVector::PutValue(), G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), splineFlag, sum, v, and G4PhysicsVector::Value().
Referenced by G4LossTableManager::BuildTables(), and G4TablesForExtrapolator::Initialisation().
G4PhysicsTable * G4LossTableBuilder::BuildTableForModel (G4PhysicsTable * table, G4VEmModel * model, const G4ParticleDefinition * part, G4double emin, G4double emax, G4bool spline)
Definition at line 360 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 360 of file G4LossTableBuilder.cc
References G4PhysicsTable::clearAndDestroy(), G4PhysicsVector::Energy(), CLHEP::eV, G4PhysicsVector::FillSecondDerivatives(), GetFlag(), G4PhysicsTable::GetFlag(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), InitialiseBaseMaterials(), mat, max, G4VEmModel::MinPrimaryEnergy(), n, G4EmParameters::NumberOfBinsPerDecade(), G4PhysicsTableHelper::PreparePhysicsTable(), G4PhysicsVector::PutValue(), G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), theParameters, G4VEmModel::UseBaseMaterials(), and G4VEmModel::Value().
Referenced by G4VMscModel::GetParticleChangeForMSC().
const std::vector< G4int > * G4LossTableBuilder::GetCoupleIndexes () const
Definition at line 117 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 117 of file G4LossTableBuilder.cc
References theDensityIdx.
Referenced by G4VEnergyLossProcess::BuildLambdaTable(), G4VEmModel::G4VEmModel(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VEnergyLossProcess::SetDEDXTable(), and G4VEnergyLossProcess::SetLambdaTable().
const std::vector< G4double > * G4LossTableBuilder::GetDensityFactors () const
Definition at line 124 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 124 of file G4LossTableBuilder.cc
References theDensityFactor.
Referenced by G4VEnergyLossProcess::BuildLambdaTable(), G4VEmModel::G4VEmModel(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VEnergyLossProcess::SetDEDXTable(), and G4VEnergyLossProcess::SetLambdaTable().
G4bool G4LossTableBuilder::GetFlag (size_t idx)
Definition at line 131 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 131 of file G4LossTableBuilder.cc
References incremental_prev_tag::idx, InitialiseBaseMaterials(), and theFlag.
Referenced by G4VEnergyLossProcess::BuildDEDXTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4GammaGeneralProcess::BuildPhysicsTable(), and BuildTableForModel().
void G4LossTableBuilder::InitialiseBaseMaterials (const G4PhysicsTable * table = nullptr)
Definition at line 291 of file G4LossTableBuilder.cc.
View newest version in sPHENIX GitHub at line 291 of file G4LossTableBuilder.cc
References G4PhysicsTable::GetFlag(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), isInitialized, isMaster, mat, theDensityFactor, theDensityIdx, and theFlag.
Referenced by BuildDEDXTable(), BuildTableForModel(), GetFlag(), G4TablesForExtrapolator::Initialisation(), G4VEmProcess::PreparePhysicsTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
G4LossTableBuilder& G4LossTableBuilder::operator= (const G4LossTableBuilder & right) private
void G4LossTableBuilder::SetInitialisationFlag (G4bool flag) inline
Definition at line 128 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 128 of file G4LossTableBuilder.hh
References isInitialized.
Referenced by G4LossTableManager::ResetParameters().
void G4LossTableBuilder::SetSplineFlag (G4bool flag) inline
Definition at line 123 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 123 of file G4LossTableBuilder.hh
References splineFlag.
Referenced by G4LossTableManager::ResetParameters().
Member Data Documentation
G4bool G4LossTableBuilder::isInitialized private
Definition at line 112 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 112 of file G4LossTableBuilder.hh
Referenced by G4LossTableBuilder(), InitialiseBaseMaterials(), and SetInitialisationFlag().
G4bool G4LossTableBuilder::isMaster private
Definition at line 113 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 113 of file G4LossTableBuilder.hh
Referenced by G4LossTableBuilder(), InitialiseBaseMaterials(), and ~G4LossTableBuilder().
G4bool G4LossTableBuilder::splineFlag private
Definition at line 111 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 111 of file G4LossTableBuilder.hh
Referenced by BuildDEDXTable(), BuildInverseRangeTable(), BuildRangeTable(), G4LossTableBuilder(), and SetSplineFlag().
std::vector< G4double > * G4LossTableBuilder::theDensityFactor = nullptr static private
Definition at line 115 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 115 of file G4LossTableBuilder.hh
Referenced by G4LossTableBuilder(), GetDensityFactors(), InitialiseBaseMaterials(), and ~G4LossTableBuilder().
std::vector< G4int > * G4LossTableBuilder::theDensityIdx = nullptr static private
Definition at line 116 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 116 of file G4LossTableBuilder.hh
Referenced by G4LossTableBuilder(), GetCoupleIndexes(), InitialiseBaseMaterials(), and ~G4LossTableBuilder().
std::vector< G4bool > * G4LossTableBuilder::theFlag = nullptr static private
Definition at line 117 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 117 of file G4LossTableBuilder.hh
Referenced by BuildInverseRangeTable(), G4LossTableBuilder(), GetFlag(), InitialiseBaseMaterials(), and ~G4LossTableBuilder().
G4EmParameters* G4LossTableBuilder::theParameters private
Definition at line 109 of file G4LossTableBuilder.hh.
View newest version in sPHENIX GitHub at line 109 of file G4LossTableBuilder.hh
Referenced by BuildTableForModel(), and G4LossTableBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4LossTableBuilder.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4LossTableBuilder.cc