ECCE @ EIC Software: G4ViewParameters Class Reference
G4ViewParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4ViewParameters.hh>
Public Types
enum DrawingStyle {
wireframe, hlr, hsr, hlhsr,
cloud
}
enum CutawayMode { cutawayUnion, cutawayIntersection }
enum RotationStyle { constrainUpDirection, freeRotation }
Public Member Functions
G4ViewParameters ()
~G4ViewParameters ()
G4bool operator!= (const G4ViewParameters &) const
DrawingStyle GetDrawingStyle () const
G4int GetNumberOfCloudPoints () const
G4bool IsAuxEdgeVisible () const
G4bool IsCulling () const
G4bool IsCullingInvisible () const
G4bool IsDensityCulling () const
G4double GetVisibleDensity () const
G4bool IsCullingCovered () const
G4int GetCBDAlgorithmNumber () const
const std::vector< G4double > & GetCBDParameters () const
G4bool IsSection () const
const G4Plane3D & GetSectionPlane () const
G4bool IsCutaway () const
CutawayMode GetCutawayMode () const
const G4Planes & GetCutawayPlanes () const
G4bool IsExplode () const
G4double GetExplodeFactor () const
const G4Point3D & GetExplodeCentre () const
G4int GetNoOfSides () const
const G4Vector3D & GetViewpointDirection () const
const G4Vector3D & GetUpVector () const
G4double GetFieldHalfAngle () const
G4double GetZoomFactor () const
const G4Vector3D & GetScaleFactor () const
const G4Point3D & GetCurrentTargetPoint () const
G4double GetDolly () const
G4bool GetLightsMoveWithCamera () const
const G4Vector3D & GetLightpointDirection () const
G4Vector3D & GetActualLightpointDirection ()
const G4VisAttributes * GetDefaultVisAttributes () const
const G4VisAttributes * GetDefaultTextVisAttributes () const
const G4VMarker & GetDefaultMarker () const
G4double GetGlobalMarkerScale () const
G4double GetGlobalLineWidthScale () const
G4bool IsMarkerNotHidden () const
unsigned int GetWindowSizeHintX () const
unsigned int GetWindowSizeHintY () const
G4int GetWindowAbsoluteLocationHintX (G4int) const
G4int GetWindowAbsoluteLocationHintY (G4int) const
G4int GetWindowLocationHintX () const
G4int GetWindowLocationHintY () const
const G4String & GetXGeometryString () const
bool IsWindowSizeHintX () const
bool IsWindowSizeHintY () const
bool IsWindowLocationHintX () const
bool IsWindowLocationHintY () const
G4bool IsAutoRefresh () const
const G4Colour & GetBackgroundColour () const
G4bool IsPicking () const
RotationStyle GetRotationStyle () const
const std::vector
< G4ModelingParameters::VisAttributesModifier > & GetVisAttributesModifiers () const
G4double GetStartTime () const
G4double GetEndTime () const
G4double GetFadeFactor () const
G4bool IsDisplayHeadTime () const
G4double GetDisplayHeadTimeX () const
G4double GetDisplayHeadTimeY () const
G4double GetDisplayHeadTimeSize () const
G4double GetDisplayHeadTimeRed () const
G4double GetDisplayHeadTimeGreen () const
G4double GetDisplayHeadTimeBlue () const
G4bool IsDisplayLightFront () const
G4double GetDisplayLightFrontX () const
G4double GetDisplayLightFrontY () const
G4double GetDisplayLightFrontZ () const
G4double GetDisplayLightFrontT () const
G4double GetDisplayLightFrontRed () const
G4double GetDisplayLightFrontGreen () const
G4double GetDisplayLightFrontBlue () const
G4double GetCameraDistance (G4double radius) const
G4double GetNearDistance (G4double cameraDistance, G4double radius) const
G4double GetFarDistance (G4double cameraDistance, G4double nearDistance, G4double radius) const
G4double GetFrontHalfHeight (G4double nearDistance, G4double radius) const
void SetDrawingStyle (G4ViewParameters::DrawingStyle style)
G4int SetNumberOfCloudPoints (G4int)
void SetAuxEdgeVisible (G4bool)
void SetCulling (G4bool)
void SetCullingInvisible (G4bool)
void SetDensityCulling (G4bool)
void SetVisibleDensity (G4double visibleDensity)
void SetCullingCovered (G4bool)
void SetCBDAlgorithmNumber (G4int)
void SetCBDParameters (const std::vector< G4double > &)
void SetSectionPlane (const G4Plane3D &sectionPlane)
void UnsetSectionPlane ()
void SetCutawayMode (CutawayMode)
void AddCutawayPlane (const G4Plane3D &cutawayPlane)
void ChangeCutawayPlane (size_t index, const G4Plane3D &cutawayPlane)
void ClearCutawayPlanes ()
void SetExplodeFactor (G4double explodeFactor)
void UnsetExplodeFactor ()
void SetExplodeCentre (const G4Point3D &explodeCentre)
G4int SetNoOfSides (G4int nSides)
void SetViewpointDirection (const G4Vector3D &viewpointDirection)
void SetViewAndLights (const G4Vector3D &viewpointDirection)
void SetUpVector (const G4Vector3D &upVector)
void SetFieldHalfAngle (G4double fieldHalfAngle)
void SetOrthogonalProjection ()
void SetPerspectiveProjection (G4double fieldHalfAngle=30.*CLHEP::deg)
void SetZoomFactor (G4double zoomFactor)
void MultiplyZoomFactor (G4double zoomFactorMultiplier)
void SetScaleFactor (const G4Vector3D &scaleFactor)
void MultiplyScaleFactor (const G4Vector3D &scaleFactorMultiplier)
void SetCurrentTargetPoint (const G4Point3D &currentTargetPoint)
void SetDolly (G4double dolly)
void IncrementDolly (G4double dollyIncrement)
void SetLightpointDirection (const G4Vector3D &lightpointDirection)
void SetLightsMoveWithCamera (G4bool moves)
void SetPan (G4double right, G4double up)
void IncrementPan (G4double right, G4double up)
void IncrementPan (G4double right, G4double up, G4double forward)
void SetDefaultVisAttributes (const G4VisAttributes &)
void SetDefaultColour (const G4Colour &)
void SetDefaultTextVisAttributes (const G4VisAttributes &)
void SetDefaultTextColour (const G4Colour &)
void SetDefaultMarker (const G4VMarker &defaultMarker)
void SetGlobalMarkerScale (G4double globalMarkerScale)
void SetGlobalLineWidthScale (G4double globalLineWidthScale)
void SetMarkerHidden ()
void SetMarkerNotHidden ()
void SetWindowSizeHint (G4int xHint, G4int yHint)
void SetWindowLocationHint (G4int xHint, G4int yHint)
void SetXGeometryString (const G4String &)
void SetAutoRefresh (G4bool)
void SetBackgroundColour (const G4Colour &)
void SetPicking (G4bool)
void SetRotationStyle (RotationStyle)
void ClearVisAttributesModifiers ()
void AddVisAttributesModifier (const G4ModelingParameters::VisAttributesModifier &)
void SetStartTime (G4double)
void SetEndTime (G4double)
void SetFadeFactor (G4double)
void SetDisplayHeadTime (G4bool)
void SetDisplayHeadTimeX (G4double)
void SetDisplayHeadTimeY (G4double)
void SetDisplayHeadTimeSize (G4double)
void SetDisplayHeadTimeRed (G4double)
void SetDisplayHeadTimeGreen (G4double)
void SetDisplayHeadTimeBlue (G4double)
void SetDisplayLightFront (G4bool)
void SetDisplayLightFrontX (G4double)
void SetDisplayLightFrontY (G4double)
void SetDisplayLightFrontZ (G4double)
void SetDisplayLightFrontT (G4double)
void SetDisplayLightFrontRed (G4double)
void SetDisplayLightFrontGreen (G4double)
void SetDisplayLightFrontBlue (G4double)
G4String CameraAndLightingCommands (const G4Point3D standardTargetPoint) const
G4String DrawingStyleCommands () const
G4String SceneModifyingCommands () const
G4String TouchableCommands () const
G4String TimeWindowCommands () const
void PrintDifferences (const G4ViewParameters &v) const
Static Public Member Functions
static G4ViewParameters * CatmullRomCubicSplineInterpolation (const std::vector< G4ViewParameters > &views, G4int nInterpolationPoints=50)
Private Types
enum {
fNoValue = 0, fXValue = 0x0001, fYValue = 0x0002, fWidthValue = 0x0004,
fHeightValue = 0x0008, fAllValues = 0x000F, fXNegative = 0x0010, fYNegative = 0x0020
}
Private Member Functions
G4int ParseGeometry (const char *string, G4int *x, G4int *y, unsigned int *width, unsigned int *height)
G4int ReadInteger (char *string, char **NextString)
Private Attributes
DrawingStyle fDrawingStyle
G4int fNumberOfCloudPoints
G4bool fAuxEdgeVisible
G4bool fCulling
G4bool fCullInvisible
G4bool fDensityCulling
G4double fVisibleDensity
G4bool fCullCovered
G4int fCBDAlgorithmNumber
std::vector< G4double > fCBDParameters
G4bool fSection
G4Plane3D fSectionPlane
CutawayMode fCutawayMode
G4Planes fCutawayPlanes
G4double fExplodeFactor
G4Point3D fExplodeCentre
G4int fNoOfSides
G4Vector3D fViewpointDirection
G4Vector3D fUpVector
G4double fFieldHalfAngle
G4double fZoomFactor
G4Vector3D fScaleFactor
G4Point3D fCurrentTargetPoint
G4double fDolly
G4bool fLightsMoveWithCamera
G4Vector3D fRelativeLightpointDirection
G4Vector3D fActualLightpointDirection
G4VisAttributes fDefaultVisAttributes
G4VisAttributes fDefaultTextVisAttributes
G4VMarker fDefaultMarker
G4double fGlobalMarkerScale
G4double fGlobalLineWidthScale
G4bool fMarkerNotHidden
G4int fWindowSizeHintX
G4int fWindowSizeHintY
G4int fWindowLocationHintX
G4int fWindowLocationHintY
G4bool fWindowLocationHintXNegative
G4bool fWindowLocationHintYNegative
G4String fXGeometryString
G4int fGeometryMask
G4bool fAutoRefresh
G4Colour fBackgroundColour
G4bool fPicking
RotationStyle fRotationStyle
std::vector
< G4ModelingParameters::VisAttributesModifier > fVisAttributesModifiers
G4double fStartTime
G4double fEndTime
G4double fFadeFactor
G4bool fDisplayHeadTime
G4double fDisplayHeadTimeX
G4double fDisplayHeadTimeY
G4double fDisplayHeadTimeSize
G4double fDisplayHeadTimeRed
G4double fDisplayHeadTimeGreen
G4double fDisplayHeadTimeBlue
G4bool fDisplayLightFront
G4double fDisplayLightFrontX
G4double fDisplayLightFrontY
G4double fDisplayLightFrontZ
G4double fDisplayLightFrontT
G4double fDisplayLightFrontRed
G4double fDisplayLightFrontGreen
G4double fDisplayLightFrontBlue
Friends
std::ostream & operator<< (std::ostream &, const DrawingStyle &)
std::ostream & operator<< (std::ostream &, const G4ViewParameters &)
Detailed Description
Definition at line 90 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ViewParameters.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
fNoValue
fXValue
fYValue
fWidthValue
fHeightValue
fAllValues
fXNegative
fYNegative
Definition at line 391 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 391 of file G4ViewParameters.hh
enum G4ViewParameters::CutawayMode
Enumerator:
cutawayUnion
cutawayIntersection
Definition at line 102 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ViewParameters.hh
enum G4ViewParameters::DrawingStyle
Enumerator:
wireframe
hlr
hsr
hlhsr
cloud
Definition at line 94 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ViewParameters.hh
enum G4ViewParameters::RotationStyle
Enumerator:
constrainUpDirection
freeRotation
Definition at line 107 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ViewParameters.hh
Constructor & Destructor Documentation
G4ViewParameters::G4ViewParameters ()
Definition at line 43 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ViewParameters.cc
References fDefaultMarker, fNoOfSides, HepPolyhedron::GetNumberOfRotationSteps(), and G4VMarker::SetScreenSize().
G4ViewParameters::~G4ViewParameters ()
Definition at line 118 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ViewParameters.cc
Member Function Documentation
void G4ViewParameters::AddCutawayPlane (const G4Plane3D & cutawayPlane)
Definition at line 180 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 180 of file G4ViewParameters.cc
References fCutawayPlanes, G4cerr, and G4endl.
Referenced by G4VisCommandViewerAddCutawayPlane::SetNewValue().
void G4ViewParameters::AddVisAttributesModifier (const G4ModelingParameters::VisAttributesModifier & vam)
Definition at line 298 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 298 of file G4ViewParameters.cc
References G4ModelingParameters::VisAttributesModifier::GetPVNameCopyNoPath(), G4ModelingParameters::VisAttributesModifier::GetVisAttributes(), and G4ModelingParameters::VisAttributesModifier::GetVisAttributesSignifier().
Referenced by G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerSave::SetNewValue().
G4String G4ViewParameters::CameraAndLightingCommands (const G4Point3D standardTargetPoint) const
Definition at line 314 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 314 of file G4ViewParameters.cc
References c, deg, G4BestUnit, G4Colour::GetAlpha(), G4Colour::GetBlue(), G4Colour::GetColour(), G4Colour::GetGreen(), and G4Colour::GetRed().
G4ViewParameters * G4ViewParameters::CatmullRomCubicSplineInterpolation (const std::vector< G4ViewParameters > & views, G4int nInterpolationPoints = 50) static
Definition at line 1388 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1388 of file G4ViewParameters.cc
References a, alpha, b, c, CONTINUITY, d, fActualLightpointDirection, fBackgroundColour, fCurrentTargetPoint, fCutawayPlanes, fDolly, fEndTime, fExplodeCentre, fExplodeFactor, fFieldHalfAngle, fGlobalLineWidthScale, fGlobalMarkerScale, fRelativeLightpointDirection, fScaleFactor, fSectionPlane, fStartTime, fUpVector, fViewpointDirection, fVisAttributesModifiers, fVisibleDensity, fZoomFactor, G4Exception(), h10, h11, INTERPOLATE, INTERPOLATECOLOUR, INTERPOLATELOG, INTERPOLATEPLANE, INTERPOLATEPOINT, INTERPOLATEUNITVECTOR, INTERPOLATEVECTOR, JustWarning, n, G4VisAttributes::SetColour(), t, HepGeom::BasicVector3D< T >::unit(), v, G4ModelingParameters::VASColour, x, y, and z.
Referenced by G4VVisCommand::InterpolateViews().
void G4ViewParameters::ChangeCutawayPlane (size_t index, const G4Plane3D & cutawayPlane)
Definition at line 192 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 192 of file G4ViewParameters.cc
References G4cerr, and G4endl.
Referenced by G4VisCommandViewerChangeCutawayPlane::SetNewValue().
void G4ViewParameters::ClearCutawayPlanes ()
Referenced by G4VisCommandViewerClearCutawayPlanes::SetNewValue().
void G4ViewParameters::ClearVisAttributesModifiers ()
Referenced by G4VisCommandViewerClearVisAttributesModifiers::SetNewValue().
G4String G4ViewParameters::DrawingStyleCommands () const
Definition at line 403 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 403 of file G4ViewParameters.cc
References cloud, fAuxEdgeVisible, fDrawingStyle, fGlobalLineWidthScale, fGlobalMarkerScale, fMarkerNotHidden, fNumberOfCloudPoints, hlhsr, hlr, hsr, and wireframe.
G4Vector3D & G4ViewParameters::GetActualLightpointDirection ()
Definition at line 127 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 127 of file G4ViewParameters.cc
References fActualLightpointDirection, fViewpointDirection, and SetViewAndLights().
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4RayTracerViewer::SetView().
const G4Colour& G4ViewParameters::GetBackgroundColour () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VisCommandsViewerSet::SetNewValue(), and G4RayTracerViewer::SetView().
G4double G4ViewParameters::GetCameraDistance (G4double radius) const
Definition at line 140 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 140 of file G4ViewParameters.cc
References fDolly, fFieldHalfAngle, and radius.
Referenced by operator<<(), and G4RayTracerViewer::SetView().
G4int G4ViewParameters::GetCBDAlgorithmNumber () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisCommandViewerColourByDensity::SetNewValue().
const std::vector<G4double>& G4ViewParameters::GetCBDParameters () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisCommandViewerColourByDensity::SetNewValue().
const G4Point3D& G4ViewParameters::GetCurrentTargetPoint () const
Referenced by G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandViewerPan::SetNewValue(), and G4RayTracerViewer::SetView().
CutawayMode G4ViewParameters::GetCutawayMode () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
const G4Planes& G4ViewParameters::GetCutawayPlanes () const
Referenced by G4VisCommandViewerAddCutawayPlane::SetNewValue(), and G4VisCommandViewerChangeCutawayPlane::SetNewValue().
const G4VMarker& G4ViewParameters::GetDefaultMarker () const
const G4VisAttributes* G4ViewParameters::GetDefaultTextVisAttributes () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), and G4VisCommandsViewerSet::SetNewValue().
const G4VisAttributes* G4ViewParameters::GetDefaultVisAttributes () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisCommandsViewerSet::SetNewValue().
G4double G4ViewParameters::GetDisplayHeadTimeBlue () const
G4double G4ViewParameters::GetDisplayHeadTimeGreen () const
G4double G4ViewParameters::GetDisplayHeadTimeRed () const
G4double G4ViewParameters::GetDisplayHeadTimeSize () const
G4double G4ViewParameters::GetDisplayHeadTimeX () const
G4double G4ViewParameters::GetDisplayHeadTimeY () const
G4double G4ViewParameters::GetDisplayLightFrontBlue () const
G4double G4ViewParameters::GetDisplayLightFrontGreen () const
G4double G4ViewParameters::GetDisplayLightFrontRed () const
G4double G4ViewParameters::GetDisplayLightFrontT () const
G4double G4ViewParameters::GetDisplayLightFrontX () const
G4double G4ViewParameters::GetDisplayLightFrontY () const
G4double G4ViewParameters::GetDisplayLightFrontZ () const
G4double G4ViewParameters::GetDolly () const
Referenced by G4DAWNFILEViewer::SendViewParameters(), G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerDolly::SetNewValue().
DrawingStyle G4ViewParameters::GetDrawingStyle () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), G4VSceneHandler::GetDrawingStyle(), G4DAWNFILEViewer::SendDrawingStyleToDAWNGUI(), G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerDefaultStyle::SetNewValue(), and G4VisCommandDrawLogicalVolume::SetNewValue().
G4double G4ViewParameters::GetEndTime () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
const G4Point3D& G4ViewParameters::GetExplodeCentre () const
Referenced by G4VSceneHandler::CreateModelingParameters(), and G4VisCommandsViewerSet::SetNewValue().
G4double G4ViewParameters::GetExplodeFactor () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisCommandsViewerSet::SetNewValue().
G4double G4ViewParameters::GetFadeFactor () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
G4double G4ViewParameters::GetFarDistance (G4double cameraDistance, G4double nearDistance, G4double radius) const
Definition at line 159 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 159 of file G4ViewParameters.cc
References radius.
Referenced by operator<<().
G4double G4ViewParameters::GetFieldHalfAngle () const
Referenced by G4RayTracerViewer::DrawView(), G4DAWNFILEViewer::SendViewParameters(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
G4double G4ViewParameters::GetFrontHalfHeight (G4double nearDistance, G4double radius) const
Definition at line 167 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 167 of file G4ViewParameters.cc
References fFieldHalfAngle, and fZoomFactor.
Referenced by operator<<(), and G4RayTracerViewer::SetView().
G4double G4ViewParameters::GetGlobalLineWidthScale () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
G4double G4ViewParameters::GetGlobalMarkerScale () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
const G4Vector3D& G4ViewParameters::GetLightpointDirection () const
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
G4bool G4ViewParameters::GetLightsMoveWithCamera () const
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
G4double G4ViewParameters::GetNearDistance (G4double cameraDistance, G4double radius) const
Definition at line 151 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 151 of file G4ViewParameters.cc
References radius.
Referenced by operator<<(), and G4RayTracerViewer::SetView().
G4int G4ViewParameters::GetNoOfSides () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VSceneHandler::GetNoOfSides().
G4int G4ViewParameters::GetNumberOfCloudPoints () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VSceneHandler::RequestPrimitives().
RotationStyle G4ViewParameters::GetRotationStyle () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
const G4Vector3D& G4ViewParameters::GetScaleFactor () const
Referenced by G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerScale::SetNewValue().
const G4Plane3D& G4ViewParameters::GetSectionPlane () const
Referenced by G4VSceneHandler::CreateSectionSolid(), and G4VisCommandsViewerSet::SetNewValue().
G4double G4ViewParameters::GetStartTime () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
const G4Vector3D& G4ViewParameters::GetUpVector () const
Referenced by G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4RayTracerViewer::SetView().
const G4Vector3D& G4ViewParameters::GetViewpointDirection () const
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4RayTracerViewer::SetView().
const std::vector<G4ModelingParameters::VisAttributesModifier>& G4ViewParameters::GetVisAttributesModifiers () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), and G4VSceneHandler::CreateModelingParameters().
G4double G4ViewParameters::GetVisibleDensity () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisCommandsViewerSet::SetNewValue().
G4int G4ViewParameters::GetWindowAbsoluteLocationHintX (G4int sizeX) const
Definition at line 1243 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1243 of file G4ViewParameters.cc
References fWindowLocationHintX, fWindowLocationHintXNegative, and fWindowSizeHintX.
G4int G4ViewParameters::GetWindowAbsoluteLocationHintY (G4int sizeY) const
Definition at line 1250 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1250 of file G4ViewParameters.cc
References fWindowLocationHintY, fWindowLocationHintYNegative, and fWindowSizeHintY.
G4int G4ViewParameters::GetWindowLocationHintX () const
G4int G4ViewParameters::GetWindowLocationHintY () const
unsigned int G4ViewParameters::GetWindowSizeHintX () const
Referenced by G4RayTracerViewer::Initialise().
unsigned int G4ViewParameters::GetWindowSizeHintY () const
Referenced by G4RayTracerViewer::Initialise().
const G4String& G4ViewParameters::GetXGeometryString () const
Referenced by G4VisCommandViewerClone::SetNewValue().
G4double G4ViewParameters::GetZoomFactor () const
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerZoom::SetNewValue().
void G4ViewParameters::IncrementDolly (G4double dollyIncrement)
Referenced by G4VisCommandViewerDolly::SetNewValue().
void G4ViewParameters::IncrementPan (G4double right, G4double up)
Definition at line 287 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 287 of file G4ViewParameters.cc
Referenced by G4VisCommandViewerPan::SetNewValue().
void G4ViewParameters::IncrementPan (G4double right, G4double up, G4double forward)
Definition at line 291 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 291 of file G4ViewParameters.cc
References HepGeom::BasicVector3D< T >::cross(), fCurrentTargetPoint, fUpVector, and fViewpointDirection.
G4bool G4ViewParameters::IsAutoRefresh () const
Referenced by G4VisManager::EndOfRun(), G4VVisCommand::RefreshIfRequired(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandSceneNotifyHandlers::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), and G4VisCommandViewerInterpolate::SetNewValue().
G4bool G4ViewParameters::IsAuxEdgeVisible () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::GetAuxEdgeVisible(), and G4VisCommandsViewerSet::SetNewValue().
G4bool G4ViewParameters::IsCulling () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), G4VisManager::CreateViewer(), G4VisCommandGeometrySetDaughtersInvisible::SetNewValue(), G4VisCommandGeometrySetVisibility::SetNewValue(), and G4VisCommandGeometrySetVisibility::SetNewValueOnLV().
G4bool G4ViewParameters::IsCullingCovered () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisManager::CreateViewer().
G4bool G4ViewParameters::IsCullingInvisible () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), G4VisManager::CreateViewer(), G4VisCommandGeometrySetVisibility::SetNewValue(), and G4VisCommandGeometrySetVisibility::SetNewValueOnLV().
G4bool G4ViewParameters::IsCutaway () const
Referenced by G4VSceneHandler::CreateModelingParameters(), operator!=(), operator<<(), and PrintDifferences().
G4bool G4ViewParameters::IsDensityCulling () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VSceneHandler::CreateModelingParameters(), and G4VisCommandsViewerSet::SetNewValue().
G4bool G4ViewParameters::IsDisplayHeadTime () const
G4bool G4ViewParameters::IsDisplayLightFront () const
G4bool G4ViewParameters::IsExplode () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), operator!=(), and PrintDifferences().
G4bool G4ViewParameters::IsMarkerNotHidden () const
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandDrawLogicalVolume::SetNewValue().
G4bool G4ViewParameters::IsPicking () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
G4bool G4ViewParameters::IsSection () const
Referenced by G4VSceneHandler::CreateModelingParameters(), G4VSceneHandler::CreateSectionSolid(), and G4VisCommandsViewerSet::SetNewValue().
bool G4ViewParameters::IsWindowLocationHintX () const
bool G4ViewParameters::IsWindowLocationHintY () const
bool G4ViewParameters::IsWindowSizeHintX () const
bool G4ViewParameters::IsWindowSizeHintY () const
void G4ViewParameters::MultiplyScaleFactor (const G4Vector3D & scaleFactorMultiplier)
Definition at line 121 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ViewParameters.cc
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
Referenced by G4VisCommandViewerScale::SetNewValue().
void G4ViewParameters::MultiplyZoomFactor (G4double zoomFactorMultiplier)
Referenced by G4VisCommandViewerZoom::SetNewValue().
G4bool G4ViewParameters::operator!= (const G4ViewParameters & v) const
Definition at line 1056 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1056 of file G4ViewParameters.cc
References fAutoRefresh, fAuxEdgeVisible, fBackgroundColour, fCBDAlgorithmNumber, fCBDParameters, fCullCovered, fCulling, fCullInvisible, fCurrentTargetPoint, fCutawayPlanes, fDefaultMarker, fDefaultTextVisAttributes, fDefaultVisAttributes, fDensityCulling, fDisplayHeadTime, fDisplayHeadTimeBlue, fDisplayHeadTimeGreen, fDisplayHeadTimeRed, fDisplayHeadTimeSize, fDisplayHeadTimeX, fDisplayHeadTimeY, fDisplayLightFront, fDisplayLightFrontBlue, fDisplayLightFrontGreen, fDisplayLightFrontRed, fDisplayLightFrontT, fDisplayLightFrontX, fDisplayLightFrontY, fDisplayLightFrontZ, fDolly, fDrawingStyle, fEndTime, fExplodeCentre, fExplodeFactor, fFadeFactor, fFieldHalfAngle, fGeometryMask, fGlobalLineWidthScale, fGlobalMarkerScale, fLightsMoveWithCamera, fMarkerNotHidden, fNoOfSides, fNumberOfCloudPoints, fPicking, fRelativeLightpointDirection, fRotationStyle, fScaleFactor, fSection, fSectionPlane, fStartTime, fUpVector, fViewpointDirection, fVisAttributesModifiers, fVisibleDensity, fWindowSizeHintX, fWindowSizeHintY, fXGeometryString, fZoomFactor, IsCutaway(), and IsExplode().
int G4ViewParameters::ParseGeometry (const char * string, G4int * x, G4int * y, unsigned int * width, unsigned int * height) private
Definition at line 1271 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1271 of file G4ViewParameters.cc
References fHeightValue, fNoValue, fWidthValue, fXNegative, fXValue, fYNegative, fYValue, mask, and ReadInteger().
Referenced by SetXGeometryString().
void G4ViewParameters::PrintDifferences (const G4ViewParameters & v) const
Definition at line 740 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 740 of file G4ViewParameters.cc
References fAutoRefresh, fAuxEdgeVisible, fBackgroundColour, fCBDAlgorithmNumber, fCBDParameters, fCullCovered, fCulling, fCullInvisible, fCurrentTargetPoint, fCutawayPlanes, fDefaultMarker, fDefaultTextVisAttributes, fDefaultVisAttributes, fDensityCulling, fDisplayHeadTime, fDisplayHeadTimeBlue, fDisplayHeadTimeGreen, fDisplayHeadTimeRed, fDisplayHeadTimeSize, fDisplayHeadTimeX, fDisplayHeadTimeY, fDisplayLightFront, fDisplayLightFrontBlue, fDisplayLightFrontGreen, fDisplayLightFrontRed, fDisplayLightFrontT, fDisplayLightFrontX, fDisplayLightFrontY, fDisplayLightFrontZ, fDolly, fDrawingStyle, fEndTime, fExplodeCentre, fExplodeFactor, fFadeFactor, fFieldHalfAngle, fGeometryMask, fGlobalLineWidthScale, fGlobalMarkerScale, fLightsMoveWithCamera, fMarkerNotHidden, fNoOfSides, fNumberOfCloudPoints, fPicking, fRelativeLightpointDirection, fRotationStyle, fScaleFactor, fSection, fSectionPlane, fStartTime, fUpVector, fViewpointDirection, fVisAttributesModifiers, fVisibleDensity, fWindowSizeHintX, fWindowSizeHintY, fXGeometryString, fZoomFactor, G4cout, G4endl, IsCutaway(), and IsExplode().
G4int G4ViewParameters::ReadInteger (char * string, char ** NextString) private
Definition at line 1364 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1364 of file G4ViewParameters.cc
Referenced by ParseGeometry().
G4String G4ViewParameters::SceneModifyingCommands () const
Definition at line 459 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 459 of file G4ViewParameters.cc
References cm3, cutawayUnion, fCBDAlgorithmNumber, fCBDParameters, fCullCovered, fCulling, fCullInvisible, fCutawayMode, fCutawayPlanes, fDensityCulling, fExplodeCentre, fExplodeFactor, fNoOfSides, fSection, fSectionPlane, fVisibleDensity, Acts::UnitConstants::g, G4BestUnit, HepGeom::Plane3D< T >::normal(), and HepGeom::Plane3D< T >::point().
void G4ViewParameters::SetAutoRefresh (G4bool)
Referenced by G4VisCommandDrawView::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerInterpolate::SetNewValue().
void G4ViewParameters::SetAuxEdgeVisible (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetBackgroundColour (const G4Colour &)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetCBDAlgorithmNumber (G4int)
Referenced by G4VisCommandViewerColourByDensity::SetNewValue().
void G4ViewParameters::SetCBDParameters (const std::vector< G4double > &)
Referenced by G4VisCommandViewerColourByDensity::SetNewValue().
void G4ViewParameters::SetCulling (G4bool)
Referenced by G4HepRepViewer::G4HepRepViewer(), and G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetCullingCovered (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetCullingInvisible (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetCurrentTargetPoint (const G4Point3D & currentTargetPoint)
Referenced by G4VisCommandsTouchable::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
void G4ViewParameters::SetCutawayMode (CutawayMode)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDefaultColour (const G4Colour &)
void G4ViewParameters::SetDefaultMarker (const G4VMarker & defaultMarker)
void G4ViewParameters::SetDefaultTextColour (const G4Colour &)
void G4ViewParameters::SetDefaultTextVisAttributes (const G4VisAttributes &)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDefaultVisAttributes (const G4VisAttributes &)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDensityCulling (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTime (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTimeBlue (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTimeGreen (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTimeRed (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTimeSize (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTimeX (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayHeadTimeY (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFront (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontBlue (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontGreen (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontRed (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontT (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontX (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontY (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDisplayLightFrontZ (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetDolly (G4double dolly)
Referenced by G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerDolly::SetNewValue().
void G4ViewParameters::SetDrawingStyle (G4ViewParameters::DrawingStyle style)
Referenced by G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerDefaultStyle::SetNewValue().
void G4ViewParameters::SetEndTime (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetExplodeCentre (const G4Point3D & explodeCentre)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetExplodeFactor (G4double explodeFactor)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetFadeFactor (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetFieldHalfAngle (G4double fieldHalfAngle)
Referenced by G4RayTracerViewer::DrawView(), G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
void G4ViewParameters::SetGlobalLineWidthScale (G4double globalLineWidthScale)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetGlobalMarkerScale (G4double globalMarkerScale)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetLightpointDirection (const G4Vector3D & lightpointDirection)
Definition at line 276 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 276 of file G4ViewParameters.cc
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
void G4ViewParameters::SetLightsMoveWithCamera (G4bool moves)
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
void G4ViewParameters::SetMarkerHidden ()
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetMarkerNotHidden ()
Referenced by G4VisCommandsViewerSet::SetNewValue().
G4int G4ViewParameters::SetNoOfSides (G4int nSides)
Definition at line 219 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 219 of file G4ViewParameters.cc
References fDefaultVisAttributes, fNoOfSides, G4cout, G4endl, and G4VisAttributes::GetMinLineSegmentsPerCircle().
Referenced by G4VisCommandsViewerSet::SetNewValue().
G4int G4ViewParameters::SetNumberOfCloudPoints (G4int nPoints)
Definition at line 231 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 231 of file G4ViewParameters.cc
References fNumberOfCloudPoints, G4cout, and G4endl.
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetOrthogonalProjection ()
void G4ViewParameters::SetPan (G4double right, G4double up)
Definition at line 281 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 281 of file G4ViewParameters.cc
References HepGeom::BasicVector3D< T >::cross(), fCurrentTargetPoint, fUpVector, and fViewpointDirection.
Referenced by G4VisCommandViewerPan::SetNewValue().
void G4ViewParameters::SetPerspectiveProjection (G4double fieldHalfAngle = 30.*CLHEP::deg)
void G4ViewParameters::SetPicking (G4bool)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetRotationStyle (RotationStyle)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetScaleFactor (const G4Vector3D & scaleFactor)
Referenced by G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerScale::SetNewValue().
void G4ViewParameters::SetSectionPlane (const G4Plane3D & sectionPlane)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetStartTime (G4double)
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetUpVector (const G4Vector3D & upVector)
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
void G4ViewParameters::SetViewAndLights (const G4Vector3D & viewpointDirection)
Definition at line 244 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 244 of file G4ViewParameters.cc
References HepGeom::BasicVector3D< T >::cross(), G4cout, G4endl, HepGeom::BasicVector3D< T >::unit(), HepGeom::BasicVector3D< T >::x(), and HepGeom::BasicVector3D< T >::y().
Referenced by GetActualLightpointDirection(), and G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetViewpointDirection (const G4Vector3D & viewpointDirection)
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerCopyViewFrom::SetNewValue().
void G4ViewParameters::SetVisibleDensity (G4double visibleDensity)
Definition at line 202 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ViewParameters.cc
References cm3, fVisibleDensity, Acts::UnitConstants::g, G4BestUnit, G4cout, and G4endl.
Referenced by G4VisCommandsViewerSet::SetNewValue().
void G4ViewParameters::SetWindowLocationHint (G4int xHint, G4int yHint)
void G4ViewParameters::SetWindowSizeHint (G4int xHint, G4int yHint)
void G4ViewParameters::SetXGeometryString (const G4String & geomStringArg)
Definition at line 1160 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 1160 of file G4ViewParameters.cc
References fGeometryMask, fHeightValue, fWidthValue, fWindowLocationHintX, fWindowLocationHintXNegative, fWindowLocationHintY, fWindowLocationHintYNegative, fWindowSizeHintX, fWindowSizeHintY, fXGeometryString, fXNegative, fXValue, fYNegative, fYValue, G4cout, G4endl, Acts::UnitConstants::h, ParseGeometry(), w, x, and y.
Referenced by G4VisManager::CreateViewer().
void G4ViewParameters::SetZoomFactor (G4double zoomFactor)
Referenced by G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerZoom::SetNewValue().
G4String G4ViewParameters::TimeWindowCommands () const
Definition at line 685 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 685 of file G4ViewParameters.cc
References fDisplayHeadTime, fDisplayHeadTimeBlue, fDisplayHeadTimeGreen, fDisplayHeadTimeRed, fDisplayHeadTimeSize, fDisplayHeadTimeX, fDisplayHeadTimeY, fDisplayLightFront, fDisplayLightFrontBlue, fDisplayLightFrontGreen, fDisplayLightFrontRed, fDisplayLightFrontT, fDisplayLightFrontX, fDisplayLightFrontY, fDisplayLightFrontZ, fEndTime, fFadeFactor, fStartTime, mm, and ns.
G4String G4ViewParameters::TouchableCommands () const
Definition at line 542 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 542 of file G4ViewParameters.cc
References c, G4VisAttributes::cloud, G4VisAttributes::dashed, G4VisAttributes::dotted, fVisAttributesModifiers, G4Colour::GetAlpha(), G4Colour::GetBlue(), G4VisAttributes::GetColour(), G4VisAttributes::GetForcedDrawingStyle(), G4VisAttributes::GetForcedLineSegmentsPerCircle(), G4VisAttributes::GetForcedNumberOfCloudPoints(), G4Colour::GetGreen(), G4VisAttributes::GetLineStyle(), G4VisAttributes::GetLineWidth(), G4Colour::GetRed(), G4VisAttributes::IsDaughtersInvisible(), G4VisAttributes::IsForceAuxEdgeVisible(), G4VisAttributes::IsForcedAuxEdgeVisible(), G4VisAttributes::IsForceDrawingStyle(), G4VisAttributes::IsVisible(), G4VisAttributes::solid, G4VisAttributes::unbroken, G4ModelingParameters::VASColour, G4ModelingParameters::VASDaughtersInvisible, G4ModelingParameters::VASForceAuxEdgeVisible, G4ModelingParameters::VASForceCloud, G4ModelingParameters::VASForceLineSegmentsPerCircle, G4ModelingParameters::VASForceNumberOfCloudPoints, G4ModelingParameters::VASForceSolid, G4ModelingParameters::VASForceWireframe, G4ModelingParameters::VASLineStyle, G4ModelingParameters::VASLineWidth, G4ModelingParameters::VASVisibility, and G4VisAttributes::wireframe.
void G4ViewParameters::UnsetExplodeFactor ()
void G4ViewParameters::UnsetSectionPlane ()
Referenced by G4VisCommandsViewerSet::SetNewValue().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const DrawingStyle & style) friend
Definition at line 858 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 858 of file G4ViewParameters.cc
std::ostream& operator<< (std::ostream & os, const G4ViewParameters & v) friend
Definition at line 876 of file G4ViewParameters.cc.
View newest version in sPHENIX GitHub at line 876 of file G4ViewParameters.cc
Member Data Documentation
G4Vector3D G4ViewParameters::fActualLightpointDirection private
Definition at line 356 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 356 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), GetActualLightpointDirection(), and operator<<().
G4bool G4ViewParameters::fAutoRefresh private
Definition at line 375 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 375 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), and PrintDifferences().
G4bool G4ViewParameters::fAuxEdgeVisible private
Definition at line 330 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 330 of file G4ViewParameters.hh
Referenced by DrawingStyleCommands(), operator!=(), operator<<(), and PrintDifferences().
G4Colour G4ViewParameters::fBackgroundColour private
Definition at line 376 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 376 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), and PrintDifferences().
G4int G4ViewParameters::fCBDAlgorithmNumber private
Definition at line 336 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 336 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
std::vector<G4double> G4ViewParameters::fCBDParameters private
Definition at line 337 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 337 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4bool G4ViewParameters::fCullCovered private
Definition at line 335 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 335 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4bool G4ViewParameters::fCulling private
Definition at line 331 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 331 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4bool G4ViewParameters::fCullInvisible private
Definition at line 332 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 332 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4Point3D G4ViewParameters::fCurrentTargetPoint private
Definition at line 351 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 351 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), IncrementPan(), operator!=(), operator<<(), PrintDifferences(), and SetPan().
CutawayMode G4ViewParameters::fCutawayMode private
Definition at line 340 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 340 of file G4ViewParameters.hh
Referenced by SceneModifyingCommands().
G4Planes G4ViewParameters::fCutawayPlanes private
Definition at line 341 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 341 of file G4ViewParameters.hh
Referenced by AddCutawayPlane(), CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4VMarker G4ViewParameters::fDefaultMarker private
Definition at line 359 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 359 of file G4ViewParameters.hh
Referenced by G4ViewParameters(), operator!=(), operator<<(), and PrintDifferences().
G4VisAttributes G4ViewParameters::fDefaultTextVisAttributes private
Definition at line 358 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 358 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), and PrintDifferences().
G4VisAttributes G4ViewParameters::fDefaultVisAttributes private
Definition at line 357 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 357 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SetNoOfSides().
G4bool G4ViewParameters::fDensityCulling private
Definition at line 333 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 333 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4bool G4ViewParameters::fDisplayHeadTime private
Definition at line 382 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 382 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayHeadTimeBlue private
Definition at line 385 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 385 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayHeadTimeGreen private
Definition at line 385 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 385 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayHeadTimeRed private
Definition at line 385 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 385 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayHeadTimeSize private
Definition at line 384 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 384 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayHeadTimeX private
Definition at line 383 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 383 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayHeadTimeY private
Definition at line 383 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 383 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4bool G4ViewParameters::fDisplayLightFront private
Definition at line 386 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 386 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontBlue private
Definition at line 389 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 389 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontGreen private
Definition at line 389 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 389 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontRed private
Definition at line 389 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 389 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontT private
Definition at line 387 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 387 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontX private
Definition at line 387 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 387 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontY private
Definition at line 387 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 387 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDisplayLightFrontZ private
Definition at line 387 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 387 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fDolly private
Definition at line 352 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 352 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), GetCameraDistance(), operator!=(), operator<<(), and PrintDifferences().
DrawingStyle G4ViewParameters::fDrawingStyle private
Definition at line 327 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 327 of file G4ViewParameters.hh
Referenced by DrawingStyleCommands(), operator!=(), operator<<(), and PrintDifferences().
G4double G4ViewParameters::fEndTime private
Definition at line 380 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 380 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4Point3D G4ViewParameters::fExplodeCentre private
Definition at line 343 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 343 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4double G4ViewParameters::fExplodeFactor private
Definition at line 342 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 342 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4double G4ViewParameters::fFadeFactor private
Definition at line 381 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 381 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4double G4ViewParameters::fFieldHalfAngle private
Definition at line 348 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 348 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), GetCameraDistance(), GetFrontHalfHeight(), operator!=(), operator<<(), and PrintDifferences().
G4int G4ViewParameters::fGeometryMask private
Definition at line 374 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 374 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SetXGeometryString().
G4double G4ViewParameters::fGlobalLineWidthScale private
Definition at line 361 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 361 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), DrawingStyleCommands(), operator!=(), operator<<(), and PrintDifferences().
G4double G4ViewParameters::fGlobalMarkerScale private
Definition at line 360 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 360 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), DrawingStyleCommands(), operator!=(), operator<<(), and PrintDifferences().
G4bool G4ViewParameters::fLightsMoveWithCamera private
Definition at line 353 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 353 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), and PrintDifferences().
G4bool G4ViewParameters::fMarkerNotHidden private
Definition at line 362 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 362 of file G4ViewParameters.hh
Referenced by DrawingStyleCommands(), operator!=(), operator<<(), and PrintDifferences().
G4int G4ViewParameters::fNoOfSides private
Definition at line 344 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 344 of file G4ViewParameters.hh
Referenced by G4ViewParameters(), operator!=(), operator<<(), PrintDifferences(), SceneModifyingCommands(), and SetNoOfSides().
G4int G4ViewParameters::fNumberOfCloudPoints private
Definition at line 328 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 328 of file G4ViewParameters.hh
Referenced by DrawingStyleCommands(), operator!=(), operator<<(), PrintDifferences(), and SetNumberOfCloudPoints().
G4bool G4ViewParameters::fPicking private
Definition at line 377 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 377 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), and PrintDifferences().
G4Vector3D G4ViewParameters::fRelativeLightpointDirection private
Definition at line 354 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 354 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), and PrintDifferences().
RotationStyle G4ViewParameters::fRotationStyle private
Definition at line 378 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 378 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), and PrintDifferences().
G4Vector3D G4ViewParameters::fScaleFactor private
Definition at line 350 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 350 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), and PrintDifferences().
G4bool G4ViewParameters::fSection private
Definition at line 338 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 338 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4Plane3D G4ViewParameters::fSectionPlane private
Definition at line 339 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 339 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and SceneModifyingCommands().
G4double G4ViewParameters::fStartTime private
Definition at line 380 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 380 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and TimeWindowCommands().
G4Vector3D G4ViewParameters::fUpVector private
Definition at line 346 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 346 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), IncrementPan(), operator!=(), operator<<(), PrintDifferences(), and SetPan().
G4Vector3D G4ViewParameters::fViewpointDirection private
Definition at line 345 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 345 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), GetActualLightpointDirection(), IncrementPan(), operator!=(), operator<<(), PrintDifferences(), and SetPan().
std::vector<G4ModelingParameters::VisAttributesModifier> G4ViewParameters::fVisAttributesModifiers private
Definition at line 379 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 379 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), and TouchableCommands().
G4double G4ViewParameters::fVisibleDensity private
Definition at line 334 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 334 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), operator!=(), operator<<(), PrintDifferences(), SceneModifyingCommands(), and SetVisibleDensity().
G4int G4ViewParameters::fWindowLocationHintX private
Definition at line 369 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 369 of file G4ViewParameters.hh
Referenced by GetWindowAbsoluteLocationHintX(), and SetXGeometryString().
G4bool G4ViewParameters::fWindowLocationHintXNegative private
Definition at line 371 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 371 of file G4ViewParameters.hh
Referenced by GetWindowAbsoluteLocationHintX(), and SetXGeometryString().
G4int G4ViewParameters::fWindowLocationHintY private
Definition at line 370 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 370 of file G4ViewParameters.hh
Referenced by GetWindowAbsoluteLocationHintY(), and SetXGeometryString().
G4bool G4ViewParameters::fWindowLocationHintYNegative private
Definition at line 372 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 372 of file G4ViewParameters.hh
Referenced by GetWindowAbsoluteLocationHintY(), and SetXGeometryString().
G4int G4ViewParameters::fWindowSizeHintX private
Definition at line 367 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 367 of file G4ViewParameters.hh
Referenced by GetWindowAbsoluteLocationHintX(), operator!=(), operator<<(), PrintDifferences(), and SetXGeometryString().
G4int G4ViewParameters::fWindowSizeHintY private
Definition at line 368 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 368 of file G4ViewParameters.hh
Referenced by GetWindowAbsoluteLocationHintY(), operator!=(), PrintDifferences(), and SetXGeometryString().
G4String G4ViewParameters::fXGeometryString private
Definition at line 373 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 373 of file G4ViewParameters.hh
Referenced by operator!=(), operator<<(), PrintDifferences(), and SetXGeometryString().
G4double G4ViewParameters::fZoomFactor private
Definition at line 349 of file G4ViewParameters.hh.
View newest version in sPHENIX GitHub at line 349 of file G4ViewParameters.hh
Referenced by CatmullRomCubicSplineInterpolation(), GetFrontHalfHeight(), operator!=(), operator<<(), and PrintDifferences().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4ViewParameters.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4ViewParameters.cc