ECCE @ EIC Software: G4SmoothTrajectory Class Reference
G4SmoothTrajectory Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4SmoothTrajectory.hh>
Public Member Functions
G4SmoothTrajectory ()
G4SmoothTrajectory (const G4Track *aTrack)
G4SmoothTrajectory (G4SmoothTrajectory &)
virtual ~G4SmoothTrajectory ()
G4SmoothTrajectory & operator= (const G4SmoothTrajectory &)=delete
G4int operator== (const G4SmoothTrajectory &r) const
void * operator new (size_t)
void operator delete (void *)
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4double GetInitialKineticEnergy () const
G4ThreeVector GetInitialMomentum () const
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void DrawTrajectory () const
virtual void AppendStep (const G4Step *aStep)
virtual int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ParticleDefinition * GetParticleDefinition ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
Private Types
using TrajectoryPointContainer = std::vector< G4VTrajectoryPoint * >
Private Attributes
TrajectoryPointContainer * positionRecord
G4int fTrackID
G4int fParentID
G4int PDGEncoding
G4double PDGCharge
G4String ParticleName
G4double initialKineticEnergy
G4ThreeVector initialMomentum
Detailed Description
Definition at line 58 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 58 of file G4SmoothTrajectory.hh
Member Typedef Documentation
using G4SmoothTrajectory::TrajectoryPointContainer = std::vector<G4VTrajectoryPoint*> private
Definition at line 61 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 61 of file G4SmoothTrajectory.hh
Constructor & Destructor Documentation
G4SmoothTrajectory::G4SmoothTrajectory ()
Definition at line 61 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 61 of file G4SmoothTrajectory.cc
G4SmoothTrajectory::G4SmoothTrajectory (const G4Track * aTrack)
Definition at line 67 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 67 of file G4SmoothTrajectory.cc
References fParentID, fTrackID, G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4Track::GetPosition(), G4Track::GetTrackID(), initialKineticEnergy, initialMomentum, ParticleName, PDGCharge, PDGEncoding, and positionRecord.
G4SmoothTrajectory::G4SmoothTrajectory (G4SmoothTrajectory & right)
Definition at line 86 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 86 of file G4SmoothTrajectory.cc
References fParentID, fTrackID, initialKineticEnergy, initialMomentum, ParticleName, PDGCharge, PDGEncoding, and positionRecord.
G4SmoothTrajectory::~G4SmoothTrajectory () virtual
Definition at line 104 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 104 of file G4SmoothTrajectory.cc
References positionRecord.
Member Function Documentation
void G4SmoothTrajectory::AppendStep (const G4Step * aStep) virtual
Implements G4VTrajectory.
Definition at line 213 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 213 of file G4SmoothTrajectory.cc
References G4Step::GetPointerToVectorOfAuxiliaryPoints(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), and positionRecord.
std::vector< G4AttValue > * G4SmoothTrajectory::CreateAttValues () const virtual
Reimplemented from G4VTrajectory.
Definition at line 176 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 176 of file G4SmoothTrajectory.cc
References G4UIcommand::ConvertToString(), fParentID, fTrackID, G4BestUnit, G4cout, GetAttDefs(), GetPointEntries(), initialKineticEnergy, initialMomentum, CLHEP::Hep3Vector::mag(), ParticleName, PDGCharge, PDGEncoding, and Acts::Test::values.
void G4SmoothTrajectory::DrawTrajectory () const virtual
Reimplemented from G4VTrajectory.
Definition at line 125 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 125 of file G4SmoothTrajectory.cc
References G4VTrajectory::DrawTrajectory().
const std::map< G4String, G4AttDef > * G4SmoothTrajectory::GetAttDefs () const virtual
Reimplemented from G4VTrajectory.
Definition at line 132 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 132 of file G4SmoothTrajectory.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
G4double G4SmoothTrajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 89 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 89 of file G4SmoothTrajectory.hh
References PDGCharge.
G4double G4SmoothTrajectory::GetInitialKineticEnergy () const inline
Definition at line 93 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 93 of file G4SmoothTrajectory.hh
References initialKineticEnergy.
G4ThreeVector G4SmoothTrajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 95 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 95 of file G4SmoothTrajectory.hh
References initialMomentum.
G4int G4SmoothTrajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 85 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 85 of file G4SmoothTrajectory.hh
References fParentID.
G4ParticleDefinition * G4SmoothTrajectory::GetParticleDefinition (void)
Definition at line 220 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 220 of file G4SmoothTrajectory.cc
References G4ParticleTable::GetParticleTable(), and ParticleName.
G4String G4SmoothTrajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 87 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 87 of file G4SmoothTrajectory.hh
References ParticleName.
G4int G4SmoothTrajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 91 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 91 of file G4SmoothTrajectory.hh
References PDGEncoding.
virtual G4VTrajectoryPoint* G4SmoothTrajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Definition at line 103 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 103 of file G4SmoothTrajectory.hh
References positionRecord.
virtual int G4SmoothTrajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Definition at line 102 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 102 of file G4SmoothTrajectory.hh
References positionRecord.
Referenced by CreateAttValues(), and MergeTrajectory().
G4int G4SmoothTrajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 83 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 83 of file G4SmoothTrajectory.hh
References fTrackID.
void G4SmoothTrajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Definition at line 225 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 225 of file G4SmoothTrajectory.cc
References GetPointEntries(), and positionRecord.
void G4SmoothTrajectory::operator delete (void * aTrajectory) inline
Definition at line 135 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 135 of file G4SmoothTrajectory.hh
References aSmoothTrajectoryAllocator().
void * G4SmoothTrajectory::operator new (size_t) inline
Definition at line 128 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 128 of file G4SmoothTrajectory.hh
References aSmoothTrajectoryAllocator().
G4SmoothTrajectory& G4SmoothTrajectory::operator= (const G4SmoothTrajectory &) delete
G4int G4SmoothTrajectory::operator== (const G4SmoothTrajectory & r) const inline
Definition at line 77 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 77 of file G4SmoothTrajectory.hh
void G4SmoothTrajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4VTrajectory.
Definition at line 118 of file G4SmoothTrajectory.cc.
View newest version in sPHENIX GitHub at line 118 of file G4SmoothTrajectory.cc
References G4VTrajectory::ShowTrajectory().
Member Data Documentation
G4int G4SmoothTrajectory::fParentID private
Definition at line 118 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 118 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), and GetParentID().
G4int G4SmoothTrajectory::fTrackID private
Definition at line 117 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 117 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), and GetTrackID().
G4double G4SmoothTrajectory::initialKineticEnergy private
Definition at line 122 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 122 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), and GetInitialKineticEnergy().
G4ThreeVector G4SmoothTrajectory::initialMomentum private
Definition at line 123 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 123 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), and GetInitialMomentum().
G4String G4SmoothTrajectory::ParticleName private
Definition at line 121 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 121 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), GetParticleDefinition(), and GetParticleName().
G4double G4SmoothTrajectory::PDGCharge private
Definition at line 120 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 120 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), and GetCharge().
G4int G4SmoothTrajectory::PDGEncoding private
Definition at line 119 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 119 of file G4SmoothTrajectory.hh
Referenced by CreateAttValues(), G4SmoothTrajectory(), and GetPDGEncoding().
TrajectoryPointContainer* G4SmoothTrajectory::positionRecord private
Definition at line 116 of file G4SmoothTrajectory.hh.
View newest version in sPHENIX GitHub at line 116 of file G4SmoothTrajectory.hh
Referenced by AppendStep(), G4SmoothTrajectory(), GetPoint(), GetPointEntries(), MergeTrajectory(), and ~G4SmoothTrajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4SmoothTrajectory.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4SmoothTrajectory.cc