ECCE @ EIC Software: G4VScoreNtupleWriter Class Reference
G4VScoreNtupleWriter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoreNtupleWriter.hh>
Public Member Functions
virtual ~G4VScoreNtupleWriter ()
virtual G4bool Book (G4HCofThisEvent *hce)=0
virtual void OpenFile ()=0
virtual void Fill (G4HCofThisEvent *hce, G4int eventNumber)=0
virtual void Write ()=0
Static Public Member Functions
static G4VScoreNtupleWriter * Instance ()
Protected Member Functions
G4VScoreNtupleWriter ()
virtual G4VScoreNtupleWriter * CreateInstance () const =0
Static Protected Attributes
static G4VScoreNtupleWriter * fgMasterInstance = 0
static G4ThreadLocal
G4VScoreNtupleWriter * fgInstance = 0
Detailed Description
Definition at line 42 of file G4VScoreNtupleWriter.hh.
View newest version in sPHENIX GitHub at line 42 of file G4VScoreNtupleWriter.hh
Constructor & Destructor Documentation
G4VScoreNtupleWriter::~G4VScoreNtupleWriter () virtual
Definition at line 86 of file G4VScoreNtupleWriter.cc.
View newest version in sPHENIX GitHub at line 86 of file G4VScoreNtupleWriter.cc
References fgInstance.
G4VScoreNtupleWriter::G4VScoreNtupleWriter () protected
Definition at line 59 of file G4VScoreNtupleWriter.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VScoreNtupleWriter.cc
References FatalException, fgInstance, fgMasterInstance, G4Exception(), and G4Threading::IsWorkerThread().
Member Function Documentation
virtual G4bool G4VScoreNtupleWriter::Book (G4HCofThisEvent * hce) pure virtual
Implemented in G4TScoreNtupleWriter< T >.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
virtual G4VScoreNtupleWriter* G4VScoreNtupleWriter::CreateInstance () const protected pure virtual
Implemented in G4TScoreNtupleWriter< T >.
Referenced by Instance().
virtual void G4VScoreNtupleWriter::Fill (G4HCofThisEvent * hce, G4int eventNumber) pure virtual
Implemented in G4TScoreNtupleWriter< T >.
Referenced by G4RunManager::UpdateScoring().
G4VScoreNtupleWriter * G4VScoreNtupleWriter::Instance (void) static
Definition at line 37 of file G4VScoreNtupleWriter.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VScoreNtupleWriter.cc
References CreateInstance(), fgInstance, fgMasterInstance, and G4Threading::IsWorkerThread().
Referenced by G4WorkerRunManager::RunInitialization(), G4RunManager::RunInitialization(), G4RunManager::RunTermination(), and G4RunManager::UpdateScoring().
virtual void G4VScoreNtupleWriter::OpenFile () pure virtual
Implemented in G4TScoreNtupleWriter< T >.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
virtual void G4VScoreNtupleWriter::Write () pure virtual
Implemented in G4TScoreNtupleWriter< T >.
Referenced by G4RunManager::RunTermination().
Member Data Documentation
G4ThreadLocal G4VScoreNtupleWriter * G4VScoreNtupleWriter::fgInstance = 0 static protected
Definition at line 62 of file G4VScoreNtupleWriter.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VScoreNtupleWriter.hh
Referenced by G4VScoreNtupleWriter(), Instance(), and ~G4VScoreNtupleWriter().
G4VScoreNtupleWriter * G4VScoreNtupleWriter::fgMasterInstance = 0 static protected
Definition at line 61 of file G4VScoreNtupleWriter.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VScoreNtupleWriter.hh
Referenced by G4VScoreNtupleWriter(), and Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoreNtupleWriter.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4VScoreNtupleWriter.cc