ECCE @ EIC Software: G4PhysicsTableHelper Class Reference
G4PhysicsTableHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4PhysicsTableHelper.hh>
Static Public Member Functions
static G4PhysicsTable * PreparePhysicsTable (G4PhysicsTable *physTable)
static G4bool RetrievePhysicsTable (G4PhysicsTable *physTable, const G4String &fileName, G4bool ascii)
static void SetPhysicsVector (G4PhysicsTable *physTable, size_t idx, G4PhysicsVector *vec)
static void SetVerboseLevel (G4int value)
static G4int GetVerboseLevel ()
Protected Member Functions
G4PhysicsTableHelper ()
~G4PhysicsTableHelper ()
G4PhysicsTableHelper (const G4PhysicsTableHelper &right)
G4PhysicsTableHelper & operator= (const G4PhysicsTableHelper &)
Static Protected Attributes
static G4ThreadLocal G4int verboseLevel = 1
Detailed Description
Definition at line 51 of file G4PhysicsTableHelper.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PhysicsTableHelper.hh
Constructor & Destructor Documentation
G4PhysicsTableHelper::G4PhysicsTableHelper () protected
Definition at line 46 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PhysicsTableHelper.cc
G4PhysicsTableHelper::~G4PhysicsTableHelper () protected
Definition at line 50 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PhysicsTableHelper.cc
G4PhysicsTableHelper::G4PhysicsTableHelper (const G4PhysicsTableHelper & right) protected
Definition at line 54 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PhysicsTableHelper.cc
Member Function Documentation
G4int G4PhysicsTableHelper::GetVerboseLevel () static
Definition at line 235 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 235 of file G4PhysicsTableHelper.cc
References verboseLevel.
G4PhysicsTableHelper & G4PhysicsTableHelper::operator= (const G4PhysicsTableHelper &) protected
Definition at line 58 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PhysicsTableHelper.cc
G4PhysicsTable * G4PhysicsTableHelper::PreparePhysicsTable (G4PhysicsTable * physTable) static
Definition at line 64 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 64 of file G4PhysicsTableHelper.cc
References G4PhysicsTable::ClearFlag(), FatalException, G4cerr, G4endl, G4Exception(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), incremental_prev_tag::idx, G4MaterialCutsCouple::IsRecalcNeeded(), G4MaterialCutsCouple::IsUsed(), physTable, G4PhysicsTable::ResetFlagArray(), G4PhysicsTable::resize(), and verboseLevel.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4LossTableBuilder::BuildTableForModel(), G4LossTableManager::BuildTables(), G4WentzelVIModel::Initialise(), G4EmDataHandler::MakeTable(), and G4VEnergyLossProcess::PreparePhysicsTable().
G4bool G4PhysicsTableHelper::RetrievePhysicsTable (G4PhysicsTable * physTable, const G4String & fileName, G4bool ascii) static
Definition at line 137 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 137 of file G4PhysicsTableHelper.cc
References G4PhysicsTable::ClearFlag(), G4cerr, G4endl, G4Exception(), G4MCCIndexConversionTable::GetIndex(), G4ProductionCutsTable::GetMCCIndexConversionTable(), G4ProductionCutsTable::GetProductionCutsTable(), incremental_prev_tag::idx, G4MCCIndexConversionTable::IsUsed(), JustWarning, G4PhysicsTable::RetrievePhysicsTable(), G4MCCIndexConversionTable::size(), and verboseLevel.
Referenced by G4EmDataHandler::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), and G4VEnergyLossProcess::RetrieveTable().
void G4PhysicsTableHelper::SetPhysicsVector (G4PhysicsTable * physTable, size_t idx, G4PhysicsVector * vec) static
Definition at line 199 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 199 of file G4PhysicsTableHelper.cc
References G4PhysicsTable::ClearFlag(), G4cerr, G4endl, G4Exception(), incremental_prev_tag::idx, JustWarning, and verboseLevel.
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4LossTableBuilder::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4LossTableBuilder::BuildInverseRangeTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LossTableBuilder::BuildRangeTable(), G4LossTableBuilder::BuildTableForModel(), and G4GammaGeneralProcess::InitialiseProcess().
void G4PhysicsTableHelper::SetVerboseLevel (G4int value) static
Definition at line 230 of file G4PhysicsTableHelper.cc.
View newest version in sPHENIX GitHub at line 230 of file G4PhysicsTableHelper.cc
References verboseLevel.
Member Data Documentation
G4ThreadLocal G4int G4PhysicsTableHelper::verboseLevel = 1 static protected
Definition at line 86 of file G4PhysicsTableHelper.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PhysicsTableHelper.hh
Referenced by GetVerboseLevel(), PreparePhysicsTable(), RetrievePhysicsTable(), SetPhysicsVector(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4PhysicsTableHelper.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4PhysicsTableHelper.cc