ECCE @ EIC Software: G4ChannelingOptrMultiParticleChangeCrossSection Class Reference
G4ChannelingOptrMultiParticleChangeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingOptrMultiParticleChangeCrossSection.hh>
Public Member Functions
G4ChannelingOptrMultiParticleChangeCrossSection ()
virtual ~G4ChannelingOptrMultiParticleChangeCrossSection ()
void AddParticle (G4String particleName)
void AddChargedParticles ()
void StartTracking (const G4Track *track)
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartRun ()
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
Private Attributes
std::map< const
G4ParticleDefinition
*, G4ChannelingOptrChangeCrossSection * > fBOptrForParticle
std::vector< const
G4ParticleDefinition * > fParticlesToBias
G4ChannelingOptrChangeCrossSection * fCurrentOperator
G4int fnInteractions
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 50 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
Constructor & Destructor Documentation
G4ChannelingOptrMultiParticleChangeCrossSection::G4ChannelingOptrMultiParticleChangeCrossSection ()
Definition at line 38 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 38 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc
References AddChargedParticles().
virtual G4ChannelingOptrMultiParticleChangeCrossSection::~G4ChannelingOptrMultiParticleChangeCrossSection () inline virtual
Definition at line 53 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
Member Function Documentation
void G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles ()
Definition at line 69 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc
References AddParticle(), aParticleIterator, G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), particle, G4ParticleTableIterator< K, V >::reset(), and G4ParticleTableIterator< K, V >::value().
Referenced by G4ChannelingOptrMultiParticleChangeCrossSection().
void G4ChannelingOptrMultiParticleChangeCrossSection::AddParticle (G4String particleName)
Definition at line 47 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc
References fBOptrForParticle, G4ParticleTable::FindParticle(), fParticlesToBias, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), JustWarning, and particle.
Referenced by AddChargedParticles().
void G4ChannelingOptrMultiParticleChangeCrossSection::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 110 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc
References fCurrentOperator, fnInteractions, and G4VBiasingOperator::ReportOperationApplied().
virtual G4VBiasingOperation* G4ChannelingOptrMultiParticleChangeCrossSection::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 75 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
virtual G4VBiasingOperation* G4ChannelingOptrMultiParticleChangeCrossSection::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline private virtual
Implements G4VBiasingOperator.
Definition at line 78 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
G4VBiasingOperation * G4ChannelingOptrMultiParticleChangeCrossSection::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) private virtual
Implements G4VBiasingOperator.
Definition at line 87 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 87 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc
References fCurrentOperator, and G4VBiasingOperator::GetProposedOccurenceBiasingOperation().
void G4ChannelingOptrMultiParticleChangeCrossSection::StartTracking (const G4Track * track) virtual
Reimplemented from G4VBiasingOperator.
Definition at line 97 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ChannelingOptrMultiParticleChangeCrossSection.cc
References fBOptrForParticle, fCurrentOperator, fnInteractions, G4Track::GetParticleDefinition(), and it.
Member Data Documentation
std::map< const G4ParticleDefinition*, G4ChannelingOptrChangeCrossSection* > G4ChannelingOptrMultiParticleChangeCrossSection::fBOptrForParticle private
Definition at line 104 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
Referenced by AddParticle(), and StartTracking().
G4ChannelingOptrChangeCrossSection* G4ChannelingOptrMultiParticleChangeCrossSection::fCurrentOperator private
Definition at line 106 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
Referenced by OperationApplied(), ProposeOccurenceBiasingOperation(), and StartTracking().
G4int G4ChannelingOptrMultiParticleChangeCrossSection::fnInteractions private
Definition at line 109 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
Referenced by OperationApplied(), and StartTracking().
std::vector< const G4ParticleDefinition* > G4ChannelingOptrMultiParticleChangeCrossSection::fParticlesToBias private
Definition at line 105 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ChannelingOptrMultiParticleChangeCrossSection.hh
Referenced by AddParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingOptrMultiParticleChangeCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/src/G4ChannelingOptrMultiParticleChangeCrossSection.cc