ECCE @ EIC Software: G4MoleculeDefinition Class Reference
G4MoleculeDefinition Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MoleculeDefinition.hh>
Public Member Functions
G4MoleculeDefinition (const G4String &name, G4double mass, G4double diffCoeff, G4int charge=0, G4int electronicLevels=0, G4double radius=-1, G4int atomsNumber=-1, G4double lifetime=-1, G4String aType="", G4FakeParticleID ID=G4FakeParticleID::Create())
virtual ~G4MoleculeDefinition ()
void SetLevelOccupation (G4int, G4int eNb=2)
void SetDiffusionCoefficient (G4double)
G4double GetDiffusionCoefficient () const
void SetAtomsNumber (G4int)
G4int GetAtomsNumber () const
void SetVanDerVaalsRadius (G4double)
G4double GetVanDerVaalsRadius () const
G4MolecularConfiguration * NewConfiguration (const G4String &excitedStateLabel)
G4MolecularConfiguration * NewConfigurationWithElectronOccupancy (const G4String &excitedStateLabel, const G4ElectronOccupancy &, double decayTime=0.)
G4MolecularConfiguration * GetConfigurationWithLabel (const G4String &molecularConfLabel)
void AddDecayChannel (const G4MolecularConfiguration *molConf, const G4MolecularDissociationChannel *channel)
void AddDecayChannel (const G4String &molecularConfLabel, const G4MolecularDissociationChannel *channel)
const std::vector< const
G4MolecularDissociationChannel * > * GetDecayChannels (const G4MolecularConfiguration *) const
const std::vector< const
G4MolecularDissociationChannel * > * GetDecayChannels (const G4String &) const
const
G4MolecularDissociationTable * GetDecayTable () const
G4MolecularDissociationTable * GetDecayTable ()
G4double GetDecayTime () const
const G4ElectronOccupancy * GetGroundStateElectronOccupancy () const
G4int GetCharge () const
const G4String & GetName () const
G4double GetMass () const
const G4String & GetType () const
G4int GetNbElectrons () const
G4int GetNbMolecularShells () const
const G4String & GetFormatedName () const
void SetFormatedName (const G4String &name)
void Finalize ()
void Serialize (std::ostream &)
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Static Public Member Functions
static G4MoleculeDefinition * Load (std::istream &)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions
G4MoleculeDefinition ()
G4MoleculeDefinition (const G4MoleculeDefinition &)
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Private Member Functions
const G4MoleculeDefinition & operator= (const G4MoleculeDefinition &right)
Private Attributes
G4int fCharge
G4double fDiffusionCoefficient
G4int fAtomsNb
G4double fVanDerVaalsRadius
G4String fFormatedName
G4ElectronOccupancy * fElectronOccupancy
G4MolecularDissociationTable * fDecayTable
Additional Inherited Members
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 76 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MoleculeDefinition.hh
Constructor & Destructor Documentation
G4MoleculeDefinition::G4MoleculeDefinition (const G4String & name, G4double mass, G4double diffCoeff, G4int charge = 0, G4int electronicLevels = 0, G4double radius = -1, G4int atomsNumber = -1, G4double lifetime = -1, G4String aType = "", G4FakeParticleID ID = G4FakeParticleID::Create())
Definition at line 45 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 45 of file G4MoleculeDefinition.cc
References charge, fCharge, fDecayTable, fElectronOccupancy, G4MoleculeTable::Insert(), and G4MoleculeTable::Instance().
G4MoleculeDefinition::~G4MoleculeDefinition () virtual
Definition at line 130 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 130 of file G4MoleculeDefinition.cc
References fDecayTable, and fElectronOccupancy.
G4MoleculeDefinition::G4MoleculeDefinition () protected
Referenced by G4DamagedDeoxyribose::Definition(), G4DamagedAdenine::Definition(), G4H2::Definition(), G4H2O::Definition(), G4H2O2::Definition(), G4H3O::Definition(), G4Hydrogen::Definition(), G4OH::Definition(), G4Electron_aq::Definition(), G4DamagedGuanine::Definition(), G4DamagedThymine::Definition(), G4DamagedCytosine::Definition(), G4Deoxyribose::Definition(), G4Phosphate::Definition(), G4Adenine::Definition(), G4Guanine::Definition(), G4Thymine::Definition(), G4Cytosine::Definition(), G4ModifiedHistone::Definition(), G4Histone::Definition(), and Load().
G4MoleculeDefinition::G4MoleculeDefinition (const G4MoleculeDefinition & right) protected
Definition at line 286 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 286 of file G4MoleculeDefinition.cc
References fCharge, fDecayTable, and fElectronOccupancy.
Member Function Documentation
void G4MoleculeDefinition::AddDecayChannel (const G4MolecularConfiguration * molConf, const G4MolecularDissociationChannel * channel)
Definition at line 223 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 223 of file G4MoleculeDefinition.cc
References G4MolecularDissociationTable::AddChannel(), and fDecayTable.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4EmDNAChemistry_option2::ConstructDissociationChannels().
void G4MoleculeDefinition::AddDecayChannel (const G4String & molecularConfLabel, const G4MolecularDissociationChannel * channel)
Definition at line 208 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 208 of file G4MoleculeDefinition.cc
References G4MolecularDissociationTable::AddChannel(), fDecayTable, and G4MolecularConfiguration::GetMolecularConfiguration().
void G4MoleculeDefinition::Finalize ()
Definition at line 320 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 320 of file G4MoleculeDefinition.cc
References G4MoleculeTable::Finalize(), and G4MoleculeTable::Instance().
G4int G4MoleculeDefinition::GetAtomsNumber () const inline
Definition at line 226 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 226 of file G4MoleculeDefinition.hh
References fAtomsNb.
G4int G4MoleculeDefinition::GetCharge () const inline
Definition at line 211 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 211 of file G4MoleculeDefinition.hh
References fCharge.
Referenced by G4MolecularConfiguration::CreateMolecularConfiguration(), G4MolecularConfiguration::G4MolecularConfiguration(), and G4MolecularConfiguration::GetOrCreateMolecularConfiguration().
G4MolecularConfiguration * G4MoleculeDefinition::GetConfigurationWithLabel (const G4String & molecularConfLabel)
Definition at line 160 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 160 of file G4MoleculeDefinition.cc
References G4MolecularConfiguration::GetMolecularConfiguration().
const vector< const G4MolecularDissociationChannel * > * G4MoleculeDefinition::GetDecayChannels (const G4MolecularConfiguration * conf) const
Definition at line 259 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 259 of file G4MoleculeDefinition.cc
References fDecayTable, and G4MolecularDissociationTable::GetDecayChannels().
const vector< const G4MolecularDissociationChannel * > * G4MoleculeDefinition::GetDecayChannels (const G4String & ExState) const
Definition at line 236 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 236 of file G4MoleculeDefinition.cc
References FatalErrorInArgument, fDecayTable, G4Exception(), G4MolecularDissociationTable::GetDecayChannels(), and GetName().
const G4MolecularDissociationTable * G4MoleculeDefinition::GetDecayTable () const inline
Definition at line 283 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 283 of file G4MoleculeDefinition.hh
References fDecayTable.
G4MolecularDissociationTable * G4MoleculeDefinition::GetDecayTable () inline
Definition at line 288 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 288 of file G4MoleculeDefinition.hh
References fDecayTable.
G4double G4MoleculeDefinition::GetDecayTime () const inline
Definition at line 216 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 216 of file G4MoleculeDefinition.hh
References G4ParticleDefinition::GetPDGLifeTime().
G4double G4MoleculeDefinition::GetDiffusionCoefficient () const inline
Definition at line 206 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 206 of file G4MoleculeDefinition.hh
References fDiffusionCoefficient.
const G4String& G4MoleculeDefinition::GetFormatedName () const inline
Definition at line 159 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 159 of file G4MoleculeDefinition.hh
References fFormatedName.
const G4ElectronOccupancy * G4MoleculeDefinition::GetGroundStateElectronOccupancy () const inline
Definition at line 241 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 241 of file G4MoleculeDefinition.hh
References fElectronOccupancy.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), G4EmDNAChemistry_option2::ConstructDissociationChannels(), G4MolecularConfiguration::CreateMolecularConfiguration(), G4Molecule::G4Molecule(), and G4MolecularConfiguration::GetOrCreateMolecularConfiguration().
G4double G4MoleculeDefinition::GetMass () const inline
Definition at line 252 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 252 of file G4MoleculeDefinition.hh
References G4ParticleDefinition::GetPDGMass().
const G4String & G4MoleculeDefinition::GetName (void) const inline
Definition at line 246 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 246 of file G4MoleculeDefinition.hh
References G4ParticleDefinition::GetParticleName().
Referenced by G4MolecularConfiguration::CreateMolecularConfiguration(), GetDecayChannels(), G4MolecularConfiguration::GetOrCreateMolecularConfiguration(), G4MoleculeTable::Insert(), NewConfiguration(), and NewConfigurationWithElectronOccupancy().
G4int G4MoleculeDefinition::GetNbElectrons () const inline
Definition at line 262 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 262 of file G4MoleculeDefinition.hh
References fElectronOccupancy, and G4ElectronOccupancy::GetTotalOccupancy().
Referenced by G4MolecularConfiguration::G4MolecularConfiguration().
G4int G4MoleculeDefinition::GetNbMolecularShells () const inline
Definition at line 273 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 273 of file G4MoleculeDefinition.hh
References fElectronOccupancy, and G4ElectronOccupancy::GetSizeOfOrbit().
const G4String & G4MoleculeDefinition::GetType () const inline
Definition at line 257 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 257 of file G4MoleculeDefinition.hh
References G4ParticleDefinition::GetParticleSubType().
G4double G4MoleculeDefinition::GetVanDerVaalsRadius () const inline
Definition at line 236 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 236 of file G4MoleculeDefinition.hh
References fVanDerVaalsRadius.
G4MoleculeDefinition * G4MoleculeDefinition::Load (std::istream & in) static
Definition at line 75 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 75 of file G4MoleculeDefinition.cc
References charge, G4MoleculeDefinition(), mass, radius, and READ().
G4MolecularConfiguration * G4MoleculeDefinition::NewConfiguration (const G4String & excitedStateLabel)
Definition at line 147 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 147 of file G4MoleculeDefinition.cc
References G4MolecularConfiguration::CreateMolecularConfiguration(), and GetName().
Referenced by G4DNAElectronHoleRecombination::BuildDissociationChannels().
G4MolecularConfiguration * G4MoleculeDefinition::NewConfigurationWithElectronOccupancy (const G4String & excitedStateLabel, const G4ElectronOccupancy & elecConf, double decayTime = 0.)
Definition at line 170 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 170 of file G4MoleculeDefinition.cc
References G4MolecularConfiguration::CreateMolecularConfiguration(), GetName(), and G4MolecularConfiguration::SetDecayTime().
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4EmDNAChemistry_option2::ConstructDissociationChannels().
const G4MoleculeDefinition & G4MoleculeDefinition::operator= (const G4MoleculeDefinition & right) private
Definition at line 310 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 310 of file G4MoleculeDefinition.cc
void G4MoleculeDefinition::Serialize (std::ostream & out)
Definition at line 108 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 108 of file G4MoleculeDefinition.cc
References fAtomsNb, fCharge, fDiffusionCoefficient, fElectronOccupancy, fVanDerVaalsRadius, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), G4ElectronOccupancy::GetSizeOfOrbit(), and WRITE().
void G4MoleculeDefinition::SetAtomsNumber (G4int val) inline
Definition at line 221 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 221 of file G4MoleculeDefinition.hh
References fAtomsNb.
void G4MoleculeDefinition::SetDiffusionCoefficient (G4double value) inline
Definition at line 201 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 201 of file G4MoleculeDefinition.hh
References fDiffusionCoefficient.
void G4MoleculeDefinition::SetFormatedName (const G4String & name) inline
Definition at line 165 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 165 of file G4MoleculeDefinition.hh
References fFormatedName.
void G4MoleculeDefinition::SetLevelOccupation (G4int shell, G4int eNb = 2)
Definition at line 190 of file G4MoleculeDefinition.cc.
View newest version in sPHENIX GitHub at line 190 of file G4MoleculeDefinition.cc
References G4ElectronOccupancy::AddElectron(), fElectronOccupancy, G4ElectronOccupancy::GetOccupancy(), and G4ElectronOccupancy::RemoveElectron().
void G4MoleculeDefinition::SetVanDerVaalsRadius (G4double val) inline
Definition at line 231 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 231 of file G4MoleculeDefinition.hh
References fVanDerVaalsRadius.
Member Data Documentation
G4int G4MoleculeDefinition::fAtomsNb private
Definition at line 192 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 192 of file G4MoleculeDefinition.hh
Referenced by GetAtomsNumber(), Serialize(), and SetAtomsNumber().
G4int G4MoleculeDefinition::fCharge private
Definition at line 183 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 183 of file G4MoleculeDefinition.hh
Referenced by G4MoleculeDefinition(), GetCharge(), and Serialize().
G4MolecularDissociationTable* G4MoleculeDefinition::fDecayTable private
Definition at line 198 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 198 of file G4MoleculeDefinition.hh
Referenced by AddDecayChannel(), G4MoleculeDefinition(), GetDecayChannels(), GetDecayTable(), and ~G4MoleculeDefinition().
G4double G4MoleculeDefinition::fDiffusionCoefficient private
Definition at line 190 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 190 of file G4MoleculeDefinition.hh
Referenced by GetDiffusionCoefficient(), Serialize(), and SetDiffusionCoefficient().
G4ElectronOccupancy* G4MoleculeDefinition::fElectronOccupancy private
Definition at line 197 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 197 of file G4MoleculeDefinition.hh
Referenced by G4MoleculeDefinition(), GetGroundStateElectronOccupancy(), GetNbElectrons(), GetNbMolecularShells(), Serialize(), SetLevelOccupation(), and ~G4MoleculeDefinition().
G4String G4MoleculeDefinition::fFormatedName private
Definition at line 195 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 195 of file G4MoleculeDefinition.hh
Referenced by GetFormatedName(), and SetFormatedName().
G4double G4MoleculeDefinition::fVanDerVaalsRadius private
Definition at line 193 of file G4MoleculeDefinition.hh.
View newest version in sPHENIX GitHub at line 193 of file G4MoleculeDefinition.hh
Referenced by GetVanDerVaalsRadius(), Serialize(), and SetVanDerVaalsRadius().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MoleculeDefinition.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4MoleculeDefinition.cc