ECCE @ EIC Software: eIDMLInterface Class Reference
eIDMLInterface Class Reference
Definition of this analysis module class.
#include <analysis/blob/master/eIDML/src/eIDMLInterface.h>
Classes
struct CaloData
Public Member Functions
eIDMLInterface (const std::vector< std::string > &names={"BECAL"}, const std::string &fname="eIDMLInterface.root")
Constructor.
virtual ~eIDMLInterface ()
int Init (PHCompositeNode *)
SubsysReco initialize processing method.
int process_event (PHCompositeNode *)
SubsysReco event processing method.
int End (PHCompositeNode *)
SubsysReco end processing method.
void setMinJetPt (float minjetpt)
Set the minimum jet pT to cut on.
void setMinClusPt (float mincluspt)
Set the minimum cluster pT to cut on.
void analyzeTracks (bool analyzeTracks)
Set things to analyze.
void analyzeClusters (bool analyzeClusters)
void analyzeJets (bool analyzeJets)
void analyzeTruth (bool analyzeTruth)
void setEtaRange (double min, double max)
Public Member Functions inherited from SubsysReco
~SubsysReco () override
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
void Print (const std::string &="ALL") const override
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void getTracks (PHCompositeNode *topNode)
Methods for grabbing the data.
void getTruthJets (PHCompositeNode *topNode)
void getReconstructedJets (PHCompositeNode *topNode)
void getEMCalClusters (PHCompositeNode *topNode)
void getHEPMCTruth (PHCompositeNode *topNode)
void getPHG4Truth (PHCompositeNode *topNode)
void initializeVariables ()
void initializeTrees ()
Private Attributes
std::pair< double, double > m_etaRange {-.5, .5}
SvtxEvalStack * _svtxevalstack = nullptr
std::vector< std::string > _calo_names
std::map< std::string, CaloData > m_CaloDataMap
std::string m_outfilename
String to contain the outfile name containing the trees.
Fun4AllHistoManager * m_hm
Fun4All Histogram Manager tool.
float m_minjetpt
A float for cutting on jet pt.
float m_mincluspt
A float for cutting on cluster pt.
bool m_analyzeTracks
A boolean for running over tracks.
bool m_analyzeClusters
A boolean for running over clusters.
bool m_analyzeJets
A boolean for running over jets.
bool m_analyzeTruth
A boolean for collecting hepmc information.
TFile * m_outfile
TFile to hold the following TTrees and histograms.
TTree * m_clustertree
TTree * m_tracktree
TTree * m_hepmctree
TTree * m_truthtree
TTree * m_recojettree
TTree * m_truthjettree
TH1 * m_phi_h
TH2 * m_eta_phi_h
JetEvalStack * m_jetEvalStack = nullptr
int m_partid1
HEPMC Tree variables.
int m_partid2
double m_x1
double m_x2
int m_mpi
int m_process_id
double m_truthenergy
double m_trutheta
double m_truthphi
double m_truthpx
double m_truthpy
double m_truthpz
double m_truthpt
double m_truthp
int m_numparticlesinevent
int m_truthpid
double m_tr_px
Track variables.
double m_tr_py
double m_tr_pz
double m_tr_p
double m_tr_pt
double m_tr_phi
double m_tr_eta
int m_charge
double m_chisq
int m_ndf
double m_dca
double m_tr_x
double m_tr_y
double m_tr_z
float m_tr_pion_loglikelihood
float m_tr_kaon_loglikelihood
float m_tr_proton_loglikelihood
int m_truth_is_primary
double m_truthtrackpx
double m_truthtrackpy
double m_truthtrackpz
double m_truthtrackp
double m_truthtracke
double m_truthtrackpt
double m_truthtrackphi
double m_truthtracketa
int m_truthtrackpid
double m_recojetpt
Reconstructed jet variables.
int m_recojetid
double m_recojetpx
double m_recojetpy
double m_recojetpz
double m_recojetphi
double m_recojetp
double m_recojetenergy
double m_recojeteta
int m_truthjetid
double m_truthjetp
double m_truthjetphi
double m_truthjeteta
double m_truthjetpt
double m_truthjetenergy
double m_truthjetpx
double m_truthjetpy
double m_truthjetpz
double m_dR
double m_clusenergy
Cluster variables.
double m_cluseta
double m_clustheta
double m_cluspt
double m_clusphi
double m_cluspx
double m_cluspy
double m_cluspz
double m_E_4x4
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition of this analysis module class.
Definition at line 34 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 34 of file eIDMLInterface.h
Constructor & Destructor Documentation
eIDMLInterface::eIDMLInterface (const std::vector< std::string > & names = {"BECAL"}, const std::string & filename = "eIDMLInterface.root")
Constructor.
This class demonstrates the construction and use of an analysis module within the EIC Fun4All framework. It is intended to show how to obtain physics objects from the analysis tree, and then write them out to a ROOT tree and file for further offline analysis. Constructor of module
Initialize variables and trees so we don't accidentally access memory that was never allocated
Definition at line 79 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 79 of file eIDMLInterface.cc
References initializeTrees(), and initializeVariables().
eIDMLInterface::~eIDMLInterface () virtual
Destructor of module
Definition at line 105 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 105 of file eIDMLInterface.cc
Member Function Documentation
void eIDMLInterface::analyzeClusters (bool analyzeClusters) inline
Definition at line 61 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 61 of file eIDMLInterface.h
References analyzeClusters(), and m_analyzeClusters.
Referenced by analyzeClusters().
void eIDMLInterface::analyzeJets (bool analyzeJets) inline
Definition at line 62 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 62 of file eIDMLInterface.h
References analyzeJets(), and m_analyzeJets.
Referenced by analyzeJets().
void eIDMLInterface::analyzeTracks (bool analyzeTracks) inline
Set things to analyze.
Definition at line 60 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 60 of file eIDMLInterface.h
References analyzeTracks(), and m_analyzeTracks.
Referenced by analyzeTracks().
void eIDMLInterface::analyzeTruth (bool analyzeTruth) inline
Definition at line 63 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 63 of file eIDMLInterface.h
References analyzeTruth(), and m_analyzeTruth.
Referenced by analyzeTruth().
int eIDMLInterface::End (PHCompositeNode * topNode) virtual
SubsysReco end processing method.
End the module and finish any data collection. Clean up any remaining loose ends
Change to the outfile
Write out any other histograms
Write and close the outfile
Clean up pointers and associated histos/trees in TFile
Reimplemented from SubsysReco.
Definition at line 546 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 546 of file eIDMLInterface.cc
References m_eta_phi_h, m_outfile, m_phi_h, m_truthtree, and Fun4AllBase::Verbosity().
void eIDMLInterface::getEMCalClusters (PHCompositeNode * topNode) private
This method gets clusters from the EMCal and stores them in a tree. It also demonstrates how to get trigger emulator information. Clusters from other containers can be obtained in a similar way (e.g. clusters from the HCal, etc.)
Get the raw cluster container Note: other cluster containers exist as well. Check out the node tree when you run a simulation, for example look for the node CLUSTER_EEMC
Get the global vertex to determine the appropriate pseudorapidity of the clusters
Trigger emulator
Can obtain some trigger information if desired
Loop over the EMCal clusters
Get this cluster
Get cluster characteristics This helper class determines the photon characteristics depending on the vertex position This is important for e.g. eta determination and E_T determination
Definition at line 1095 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 1095 of file eIDMLInterface.cc
References GlobalVertexMap::begin(), GlobalVertexMap::empty(), CaloTriggerInfo::get_best_EMCal_4x4_E(), GlobalVertex::get_x(), GlobalVertex::get_y(), GlobalVertex::get_z(), RawClusterContainer::getClusters(), RawClusterUtility::GetECoreVec(), m_clusenergy, m_cluseta, m_clusphi, m_cluspt, m_cluspx, m_cluspy, m_cluspz, m_clustertree, m_clustheta, m_E_4x4, m_eta_phi_h, m_mincluspt, m_phi_h, and PHWHERE.
void eIDMLInterface::getHEPMCTruth (PHCompositeNode * topNode) private
This method gets all of the HEPMC truth particles from the node tree and stores them in a ROOT TTree. The HEPMC truth particles are what, for example, directly comes out of PYTHIA and thus gives you all of the associated parton information
Get the node from the node tree
If the node was not properly put on the tree, return
Could have some print statements for debugging with verbosity
You can iterate over the number of events in a hepmc event for pile up events where you have multiple hard scatterings per bunch crossing
Get the event
Get the event characteristics, inherited from HepMC classes
Get the parton info
Get the parton info as determined from HEPMC
Are there multiple partonic intercations in a p+p event
Get the PYTHIA signal process id identifying the 2-to-2 hard process
Loop over all the truth particles and get their information
Get each pythia particle characteristics
Fill the truth tree
Definition at line 581 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 581 of file eIDMLInterface.cc
References PHHepMCGenEventMap::begin(), PHHepMCGenEventMap::end(), PHHepMCGenEvent::getEvent(), m_hepmctree, m_mpi, m_numparticlesinevent, m_partid1, m_partid2, m_process_id, m_truthenergy, m_trutheta, m_truthphi, m_truthpid, m_truthpt, m_truthpx, m_truthpy, m_truthpz, m_x1, m_x2, PHWHERE, and Fun4AllBase::Verbosity().
void eIDMLInterface::getPHG4Truth (PHCompositeNode * topNode) private
This function collects the truth PHG4 stable particles that are produced from PYTHIA, or some other event generator. These are the stable particles, e.g. there are not any (for example) partons here.
G4 truth particle node
Get the primary particle range
Loop over the G4 truth (stable) particles
Get this truth particle
Get this particles momentum, etc.
Check for nans
Fill the g4 truth tree
Definition at line 671 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 671 of file eIDMLInterface.cc
References PHG4Particle::get_e(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), m_truthenergy, m_trutheta, m_truthp, m_truthphi, m_truthpid, m_truthpt, m_truthpx, m_truthpy, m_truthpz, m_truthtree, and PHWHERE.
void eIDMLInterface::getReconstructedJets (PHCompositeNode * topNode) private
Get the reconstructed jets and store them in a tree
Get the reconstructed tower jets
Get the truth jets
Iterate over the reconstructed jets
Set the matched truth jet characteristics to 0
Check to make sure the truth jet node is available
Match the reconstructed jet to the closest truth jet in delta R space Iterate over the truth jets
Determine the distance in eta phi space between the reconstructed and truth jets
If this truth jet is closer than the previous truth jet, it is closer and thus should be considered the truth jet
Definition at line 960 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 960 of file eIDMLInterface.cc
References JetMap::begin(), JetMap::end(), Jet::get_e(), Jet::get_eta(), Jet::get_id(), Jet::get_p(), Jet::get_phi(), Jet::get_pt(), Jet::get_px(), Jet::get_py(), Jet::get_pz(), JetEvalStack::get_reco_eval(), m_dR, m_jetEvalStack, m_minjetpt, m_recojetenergy, m_recojeteta, m_recojetid, m_recojetp, m_recojetphi, m_recojetpt, m_recojetpx, m_recojetpy, m_recojetpz, m_recojettree, m_truthjetenergy, m_truthjeteta, m_truthjetid, m_truthjetp, m_truthjetphi, m_truthjetpt, m_truthjetpx, m_truthjetpy, m_truthjetpz, JetRecoEval::max_truth_jet_by_energy(), JetEvalStack::next_event(), PHWHERE, and Fun4AllBase::Verbosity().
void eIDMLInterface::getTracks (PHCompositeNode * topNode) private
Methods for grabbing the data.
This method gets the tracks as reconstructed from the tracker. It also compares the reconstructed track to its truth track.
Tracks node
Get the range for primary tracks
Get the reconstructed track info
Ensure that the reco track is a fast sim track
Get truth track info that matches this reconstructed track
Definition at line 721 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 721 of file eIDMLInterface.cc
References SvtxTrackMap::begin(), SvtxTrackMap::end(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_dca(), PHG4Particle::get_e(), SvtxTrack::get_eta(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_phi(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_pz(), EICPIDParticle::get_SumLogLikelyhood(), SvtxTrack_FastSim::get_truth_track_id(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::is_primary(), EICPIDDefs::KaonCandiate, m_charge, m_chisq, m_dca, m_ndf, m_tr_eta, m_tr_kaon_loglikelihood, m_tr_p, m_tr_phi, m_tr_pion_loglikelihood, m_tr_proton_loglikelihood, m_tr_pt, m_tr_px, m_tr_py, m_tr_pz, m_tr_x, m_tr_y, m_tr_z, m_tracktree, m_truth_is_primary, m_truthtracke, m_truthtracketa, m_truthtrackp, m_truthtrackphi, m_truthtrackpid, m_truthtrackpt, m_truthtrackpx, m_truthtrackpy, m_truthtrackpz, PHWHERE, EICPIDDefs::PionCandiate, EICPIDDefs::ProtonCandiate, track, and Fun4AllBase::Verbosity().
void eIDMLInterface::getTruthJets (PHCompositeNode * topNode) private
Method that gets the truth jets and stores them in a tree
Get the truth jet node
Get reco jets associated to truth jets to study e.g. jet efficiencies
Iterate over the truth jets
Only collect truthjets above the _minjetpt cut
Iterate over the reconstructed jets
Determine the distance in eta phi space between the reconstructed and truth jets
If this truth jet is closer than the previous truth jet, it is closer and thus should be considered the truth jet
Fill the truthjet tree
Definition at line 828 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 828 of file eIDMLInterface.cc
References JetTruthEval::all_truth_particles(), JetMap::begin(), JetMap::end(), Jet::get_e(), Jet::get_eta(), Jet::get_id(), Jet::get_p(), Jet::get_phi(), Jet::get_pt(), Jet::get_px(), Jet::get_py(), Jet::get_pz(), JetEvalStack::get_truth_eval(), m_dR, m_jetEvalStack, m_minjetpt, m_recojetenergy, m_recojeteta, m_recojetid, m_recojetp, m_recojetphi, m_recojetpt, m_recojetpx, m_recojetpy, m_recojetpz, m_truthjetenergy, m_truthjeteta, m_truthjetp, m_truthjetphi, m_truthjetpt, m_truthjetpx, m_truthjetpy, m_truthjetpz, m_truthjettree, JetEvalStack::next_event(), PHWHERE, and Fun4AllBase::Verbosity().
int eIDMLInterface::Init (PHCompositeNode * topNode) virtual
SubsysReco initialize processing method.
Initialize the module and prepare looping over events
Reimplemented from SubsysReco.
Definition at line 112 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 112 of file eIDMLInterface.cc
References m_eta_phi_h, m_outfile, m_outfilename, m_phi_h, and Fun4AllBase::Verbosity().
void eIDMLInterface::initializeTrees () private
This function puts all of the tree branch assignments in one place so as to not clutter up the eIDMLInterface::Init function.
Definition at line 1180 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 1180 of file eIDMLInterface.cc
References _calo_names, m_CaloDataMap, m_charge, m_chisq, m_dca, m_eta_phi_h, m_ndf, m_outfile, m_phi_h, m_tr_eta, m_tr_p, m_tr_phi, m_tr_pt, m_tr_px, m_tr_py, m_tr_pz, m_tr_x, m_tr_y, m_tr_z, m_truthenergy, m_trutheta, m_truthp, m_truthphi, m_truthpid, m_truthpt, m_truthpx, m_truthpy, m_truthpz, m_truthtree, and xyzt.
Referenced by eIDMLInterface().
void eIDMLInterface::initializeVariables () private
This function initializes all of the member variables in this class so that there are no variables that might not be set before e.g. writing them to the output trees.
Definition at line 1343 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 1343 of file eIDMLInterface.cc
References _calo_names, m_CaloDataMap, m_charge, m_chisq, m_dca, m_dR, m_mpi, m_ndf, m_numparticlesinevent, m_partid1, m_partid2, m_process_id, m_recojetenergy, m_recojeteta, m_recojetid, m_recojetp, m_recojetphi, m_recojetpt, m_recojetpx, m_recojetpy, m_recojetpz, m_tr_eta, m_tr_kaon_loglikelihood, m_tr_p, m_tr_phi, m_tr_pion_loglikelihood, m_tr_proton_loglikelihood, m_tr_pt, m_tr_px, m_tr_py, m_tr_pz, m_tr_x, m_tr_y, m_tr_z, m_truthenergy, m_trutheta, m_truthjetenergy, m_truthjeteta, m_truthjetid, m_truthjetp, m_truthjetphi, m_truthjetpt, m_truthjetpx, m_truthjetpy, m_truthjetpz, m_truthp, m_truthphi, m_truthpid, m_truthpt, m_truthpx, m_truthpy, m_truthpz, m_truthtracke, m_truthtracketa, m_truthtrackp, m_truthtrackphi, m_truthtrackpid, m_truthtrackpt, m_truthtrackpy, m_truthtrackpz, m_x1, and m_x2.
Referenced by eIDMLInterface(), and process_event().
int eIDMLInterface::process_event (PHCompositeNode * topNode) virtual
SubsysReco event processing method.
Main workhorse function where each event is looped over and data from each event is collected from the node tree for analysis
G4 truth particle node
Get the primary particle range
Loop over the G4 truth (stable) particles
Get this truth particle
Get this particles momentum, etc.
Check for nans
Get the reconstructed track info
Loop over the G4 truth (stable) particles
Fill the g4 truth tree
Loop over the G4 truth (stable) particles
Reimplemented from SubsysReco.
Definition at line 131 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 131 of file eIDMLInterface.cc
References _calo_names, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, kdfinder::abs(), SvtxTrack_v1::begin_states(), RawTowerDefs::decode_index1(), RawTowerDefs::decode_index1v2(), RawTowerDefs::decode_index2(), RawTowerDefs::decode_index2v2(), RawTowerDefs::decode_index3v2(), RawTowerDefs::encode_towerid(), SvtxTrack_v1::end_states(), energy, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_bineta(), RawTowerGeom::get_binl(), RawTowerGeom::get_binphi(), RawTowerGeomContainer::get_calorimeter_id(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), SvtxTrack_v1::get_charge(), SvtxTrack_v1::get_chisq(), SvtxTrack_v1::get_dca(), PHG4Particle::get_e(), RawTower::get_energy(), SvtxTrack_v1::get_eta(), SvtxTrack_v1::get_ndf(), SvtxTrack_v1::get_phi(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrack_v1::get_px(), PHG4Particle::get_py(), SvtxTrack_v1::get_py(), PHG4Particle::get_pz(), SvtxTrack_v1::get_pz(), RawTowerGeomContainer::get_tower_geometries(), RawTowerGeomContainer::get_tower_geometry(), PHG4Particle::get_track_id(), SvtxTrack_FastSim::get_truth_track_id(), SvtxTrack_v1::get_x(), SvtxTrack_v1::get_y(), SvtxTrack_v1::get_z(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTower(), RawTowerGeom::identify(), SvtxTrack_FastSim::identify(), RawTower::identify(), initializeVariables(), G4TTL::layer, m_CaloDataMap, m_charge, m_chisq, m_dca, m_etaRange, m_ndf, M_PI, m_tr_eta, m_tr_p, m_tr_phi, m_tr_pt, m_tr_px, m_tr_py, m_tr_pz, m_tr_x, m_tr_y, m_tr_z, m_truthenergy, m_trutheta, m_truthp, m_truthphi, m_truthpid, m_truthpt, m_truthpx, m_truthpy, m_truthpz, m_truthtree, PHWHERE, r2, track, and Fun4AllBase::Verbosity().
void eIDMLInterface::setEtaRange (double min, double max) inline
Definition at line 65 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 65 of file eIDMLInterface.h
References m_etaRange, max, and min.
Referenced by Fun4All_ReadDST_eIDML().
void eIDMLInterface::setMinClusPt (float mincluspt) inline
Set the minimum cluster pT to cut on.
Definition at line 57 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 57 of file eIDMLInterface.h
References m_mincluspt.
void eIDMLInterface::setMinJetPt (float minjetpt) inline
Set the minimum jet pT to cut on.
Definition at line 54 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 54 of file eIDMLInterface.h
References m_minjetpt.
Member Data Documentation
std::vector<std::string> eIDMLInterface::_calo_names private
Definition at line 75 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 75 of file eIDMLInterface.h
Referenced by initializeTrees(), initializeVariables(), and process_event().
SvtxEvalStack* eIDMLInterface::_svtxevalstack = nullptr private
Definition at line 74 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 74 of file eIDMLInterface.h
bool eIDMLInterface::m_analyzeClusters private
A boolean for running over clusters.
Definition at line 117 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 117 of file eIDMLInterface.h
Referenced by analyzeClusters().
bool eIDMLInterface::m_analyzeJets private
A boolean for running over jets.
Definition at line 120 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 120 of file eIDMLInterface.h
Referenced by analyzeJets().
bool eIDMLInterface::m_analyzeTracks private
A boolean for running over tracks.
Definition at line 114 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 114 of file eIDMLInterface.h
Referenced by analyzeTracks().
bool eIDMLInterface::m_analyzeTruth private
A boolean for collecting hepmc information.
Definition at line 123 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 123 of file eIDMLInterface.h
Referenced by analyzeTruth().
std::map<std::string, CaloData> eIDMLInterface::m_CaloDataMap private
Definition at line 99 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 99 of file eIDMLInterface.h
Referenced by initializeTrees(), initializeVariables(), and process_event().
int eIDMLInterface::m_charge private
Definition at line 179 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 179 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_chisq private
Definition at line 180 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 180 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_clusenergy private
Cluster variables.
Definition at line 222 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 222 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_cluseta private
Definition at line 223 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 223 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_clusphi private
Definition at line 226 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 226 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_cluspt private
Definition at line 225 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 225 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_cluspx private
Definition at line 227 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 227 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_cluspy private
Definition at line 228 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 228 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_cluspz private
Definition at line 229 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 229 of file eIDMLInterface.h
Referenced by getEMCalClusters().
TTree* eIDMLInterface::m_clustertree private
Definition at line 127 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 127 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_clustheta private
Definition at line 224 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 224 of file eIDMLInterface.h
Referenced by getEMCalClusters().
double eIDMLInterface::m_dca private
Definition at line 182 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 182 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_dR private
Definition at line 219 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 219 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_E_4x4 private
Definition at line 230 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 230 of file eIDMLInterface.h
Referenced by getEMCalClusters().
TH2* eIDMLInterface::m_eta_phi_h private
Definition at line 134 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 134 of file eIDMLInterface.h
Referenced by End(), getEMCalClusters(), Init(), and initializeTrees().
std::pair<double, double> eIDMLInterface::m_etaRange {-.5, .5} private
Definition at line 72 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 72 of file eIDMLInterface.h
Referenced by process_event(), and setEtaRange().
TTree* eIDMLInterface::m_hepmctree private
Definition at line 129 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 129 of file eIDMLInterface.h
Referenced by getHEPMCTruth().
Fun4AllHistoManager* eIDMLInterface::m_hm private
Fun4All Histogram Manager tool.
Definition at line 105 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 105 of file eIDMLInterface.h
JetEvalStack* eIDMLInterface::m_jetEvalStack = nullptr private
Definition at line 136 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 136 of file eIDMLInterface.h
Referenced by getReconstructedJets(), and getTruthJets().
float eIDMLInterface::m_mincluspt private
A float for cutting on cluster pt.
Definition at line 111 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 111 of file eIDMLInterface.h
Referenced by getEMCalClusters(), and setMinClusPt().
float eIDMLInterface::m_minjetpt private
A float for cutting on jet pt.
Definition at line 108 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 108 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and setMinJetPt().
int eIDMLInterface::m_mpi private
Definition at line 158 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 158 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
int eIDMLInterface::m_ndf private
Definition at line 181 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 181 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
int eIDMLInterface::m_numparticlesinevent private
Definition at line 168 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 168 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
TFile* eIDMLInterface::m_outfile private
TFile to hold the following TTrees and histograms.
Definition at line 126 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 126 of file eIDMLInterface.h
Referenced by End(), Init(), and initializeTrees().
std::string eIDMLInterface::m_outfilename private
String to contain the outfile name containing the trees.
Definition at line 102 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 102 of file eIDMLInterface.h
Referenced by Init().
int eIDMLInterface::m_partid1 private
HEPMC Tree variables.
Make variables for the relevant trees
Definition at line 154 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 154 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
int eIDMLInterface::m_partid2 private
Definition at line 155 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 155 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
TH1* eIDMLInterface::m_phi_h private
Definition at line 133 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 133 of file eIDMLInterface.h
Referenced by End(), getEMCalClusters(), Init(), and initializeTrees().
int eIDMLInterface::m_process_id private
Definition at line 159 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 159 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
double eIDMLInterface::m_recojetenergy private
Definition at line 208 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 208 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojeteta private
Definition at line 209 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 209 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
int eIDMLInterface::m_recojetid private
Definition at line 202 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 202 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojetp private
Definition at line 207 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 207 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojetphi private
Definition at line 206 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 206 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojetpt private
Reconstructed jet variables.
Definition at line 201 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 201 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojetpx private
Definition at line 203 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 203 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojetpy private
Definition at line 204 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 204 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_recojetpz private
Definition at line 205 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 205 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
TTree* eIDMLInterface::m_recojettree private
Definition at line 131 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 131 of file eIDMLInterface.h
Referenced by getReconstructedJets().
double eIDMLInterface::m_tr_eta private
Definition at line 178 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 178 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
float eIDMLInterface::m_tr_kaon_loglikelihood private
Definition at line 187 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 187 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_tr_p private
Definition at line 175 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 175 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_phi private
Definition at line 177 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 177 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
float eIDMLInterface::m_tr_pion_loglikelihood private
Definition at line 186 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 186 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
float eIDMLInterface::m_tr_proton_loglikelihood private
Definition at line 188 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 188 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_tr_pt private
Definition at line 176 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 176 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_px private
Track variables.
Definition at line 172 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 172 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_py private
Definition at line 173 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 173 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_pz private
Definition at line 174 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 174 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_x private
Definition at line 183 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 183 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_y private
Definition at line 184 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 184 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_tr_z private
Definition at line 185 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 185 of file eIDMLInterface.h
Referenced by getTracks(), initializeTrees(), initializeVariables(), and process_event().
TTree* eIDMLInterface::m_tracktree private
Definition at line 128 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 128 of file eIDMLInterface.h
Referenced by getTracks().
int eIDMLInterface::m_truth_is_primary private
Definition at line 189 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 189 of file eIDMLInterface.h
Referenced by getTracks().
double eIDMLInterface::m_truthenergy private
Definition at line 160 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 160 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_trutheta private
Definition at line 161 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 161 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthjetenergy private
Definition at line 215 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 215 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_truthjeteta private
Definition at line 213 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 213 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
int eIDMLInterface::m_truthjetid private
Definition at line 210 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 210 of file eIDMLInterface.h
Referenced by getReconstructedJets(), and initializeVariables().
double eIDMLInterface::m_truthjetp private
Definition at line 211 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 211 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_truthjetphi private
Definition at line 212 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 212 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_truthjetpt private
Definition at line 214 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 214 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_truthjetpx private
Definition at line 216 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 216 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_truthjetpy private
Definition at line 217 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 217 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
double eIDMLInterface::m_truthjetpz private
Definition at line 218 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 218 of file eIDMLInterface.h
Referenced by getReconstructedJets(), getTruthJets(), and initializeVariables().
TTree* eIDMLInterface::m_truthjettree private
Definition at line 132 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 132 of file eIDMLInterface.h
Referenced by getTruthJets().
double eIDMLInterface::m_truthp private
Definition at line 167 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 167 of file eIDMLInterface.h
Referenced by getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthphi private
Definition at line 162 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 162 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
int eIDMLInterface::m_truthpid private
Definition at line 169 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 169 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthpt private
Definition at line 166 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 166 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthpx private
Definition at line 163 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 163 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthpy private
Definition at line 164 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 164 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthpz private
Definition at line 165 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 165 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), getPHG4Truth(), initializeTrees(), initializeVariables(), and process_event().
double eIDMLInterface::m_truthtracke private
Definition at line 194 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 194 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_truthtracketa private
Definition at line 197 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 197 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_truthtrackp private
Definition at line 193 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 193 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_truthtrackphi private
Definition at line 196 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 196 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
int eIDMLInterface::m_truthtrackpid private
Definition at line 198 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 198 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_truthtrackpt private
Definition at line 195 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 195 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_truthtrackpx private
Definition at line 190 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 190 of file eIDMLInterface.h
Referenced by getTracks().
double eIDMLInterface::m_truthtrackpy private
Definition at line 191 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 191 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
double eIDMLInterface::m_truthtrackpz private
Definition at line 192 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 192 of file eIDMLInterface.h
Referenced by getTracks(), and initializeVariables().
TTree* eIDMLInterface::m_truthtree private
Definition at line 130 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 130 of file eIDMLInterface.h
Referenced by End(), getPHG4Truth(), initializeTrees(), and process_event().
double eIDMLInterface::m_x1 private
Definition at line 156 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 156 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
double eIDMLInterface::m_x2 private
Definition at line 157 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 157 of file eIDMLInterface.h
Referenced by getHEPMCTruth(), and initializeVariables().
The documentation for this class was generated from the following files:
analysis/blob/master/eIDML/src/eIDMLInterface.h
analysis/blob/master/eIDML/src/eIDMLInterface.cc