ECCE @ EIC Software: DicomBeamDevicePos Class Reference
DicomBeamDevicePos Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeamDevicePos.hh>
Public Member Functions
DicomBeamDevicePos (DRTBeamLimitingDevicePositionSequence::Item bldpsItem)
~DicomBeamDevicePos ()
void DumpToFile (std::ofstream &out)
void Print (std::ostream &out)
Public Member Functions inherited from DicomVBeamDevice
void SetNumberOfLeafJawPairs (Sint32 dat)
Sint32 GetNumberOfLeafJawPairs () const
void SetType (OFString dat)
OFString GetType () const
void AddPositionBoundary (Float64 dat)
Float64 GetPositionBoundary (size_t ii)
Additional Inherited Members
Protected Member Functions inherited from DicomVBeamDevice
DicomVBeamDevice ()
~DicomVBeamDevice ()
Protected Attributes inherited from DicomVBeamDevice
OFString theType
Sint32 theNumberOfLeafJawPairs
std::vector< Float64 > thePositionBoundaries
Detailed Description
Definition at line 31 of file DicomBeamDevicePos.hh.
View newest version in sPHENIX GitHub at line 31 of file DicomBeamDevicePos.hh
Constructor & Destructor Documentation
DicomBeamDevicePos::DicomBeamDevicePos (DRTBeamLimitingDevicePositionSequence::Item bldpsItem)
Definition at line 31 of file DicomBeamDevicePos.cc.
View newest version in sPHENIX GitHub at line 31 of file DicomBeamDevicePos.cc
References DicomVBeamDevice::AddPositionBoundary(), G4cout, G4endl, DicomVBeamDevice::SetNumberOfLeafJawPairs(), and DicomVBeamDevice::SetType().
DicomBeamDevicePos::~DicomBeamDevicePos () inline
Definition at line 35 of file DicomBeamDevicePos.hh.
View newest version in sPHENIX GitHub at line 35 of file DicomBeamDevicePos.hh
Member Function Documentation
void DicomBeamDevicePos::DumpToFile (std::ofstream & out) virtual
Implements DicomVBeamDevice.
Definition at line 53 of file DicomBeamDevicePos.cc.
View newest version in sPHENIX GitHub at line 53 of file DicomBeamDevicePos.cc
References G4endl, DicomVBeamDevice::theNumberOfLeafJawPairs, DicomVBeamDevice::thePositionBoundaries, DicomVBeamDevice::theType, and nlohmann::to_string().
void DicomBeamDevicePos::Print (std::ostream & out) virtual
Implements DicomVBeamDevice.
Definition at line 64 of file DicomBeamDevicePos.cc.
View newest version in sPHENIX GitHub at line 64 of file DicomBeamDevicePos.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeamDevicePos.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomBeamDevicePos.cc