ECCE @ EIC Software: G4PhotoElectricAngularGeneratorSauterGavrila Class Reference
G4PhotoElectricAngularGeneratorSauterGavrila Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PhotoElectricAngularGeneratorSauterGavrila.hh>
Public Member Functions
G4PhotoElectricAngularGeneratorSauterGavrila ()
~G4PhotoElectricAngularGeneratorSauterGavrila ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double e=0.0, G4int shellId=0, const G4Material *mat=0)
void PrintGeneratorInformation () const
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Private Member Functions
G4PhotoElectricAngularGeneratorSauterGavrila & operator= (const G4PhotoElectricAngularGeneratorSauterGavrila &right)
G4PhotoElectricAngularGeneratorSauterGavrila (const G4PhotoElectricAngularGeneratorSauterGavrila &)
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 57 of file G4PhotoElectricAngularGeneratorSauterGavrila.hh.
View newest version in sPHENIX GitHub at line 57 of file G4PhotoElectricAngularGeneratorSauterGavrila.hh
Constructor & Destructor Documentation
G4PhotoElectricAngularGeneratorSauterGavrila::G4PhotoElectricAngularGeneratorSauterGavrila ()
Definition at line 54 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc.
View newest version in sPHENIX GitHub at line 54 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc
G4PhotoElectricAngularGeneratorSauterGavrila::~G4PhotoElectricAngularGeneratorSauterGavrila ()
Definition at line 58 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc
G4PhotoElectricAngularGeneratorSauterGavrila::G4PhotoElectricAngularGeneratorSauterGavrila (const G4PhotoElectricAngularGeneratorSauterGavrila &) private
Member Function Documentation
G4PhotoElectricAngularGeneratorSauterGavrila& G4PhotoElectricAngularGeneratorSauterGavrila::operator= (const G4PhotoElectricAngularGeneratorSauterGavrila & right) private
void G4PhotoElectricAngularGeneratorSauterGavrila::PrintGeneratorInformation () const
Definition at line 104 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc.
View newest version in sPHENIX GitHub at line 104 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc
References G4cout, and G4endl.
G4ThreeVector & G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection (const G4DynamicParticle * dp, G4double e = 0.0, G4int shellId = 0, const G4Material * mat = 0) virtual
Implements G4VEmAngularDistribution.
Definition at line 62 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PhotoElectricAngularGeneratorSauterGavrila.cc
References b, source.hepunit::electron_mass_c2, G4VEmAngularDistribution::fLocalDirection, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), and twopi.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PhotoElectricAngularGeneratorSauterGavrila.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4PhotoElectricAngularGeneratorSauterGavrila.cc