ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4LogicalVolume.cc File Reference
pyG4LogicalVolume.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4LogicalVolume.hh"
#include "G4Material.hh"
#include "G4VSolid.hh"
#include "G4FieldManager.hh"
#include "G4VSensitiveDetector.hh"
#include "G4UserLimits.hh"
#include "G4SmartVoxelHeader.hh"
#include "G4MaterialCutsCouple.hh"
#include "G4FastSimulationManager.hh"
#include "G4VisAttributes.hh"
Namespaces
namespace pyG4LogicalVolume
Functions
void export_G4LogicalVolume ()
Variables
void(G4LogicalVolume::* pyG4LogicalVolume::f1_SetVisAttributes)(const G4VisAttributes *) = &G4LogicalVolume::SetVisAttributes
void(G4LogicalVolume::* pyG4LogicalVolume::f2_SetVisAttributes)(const G4VisAttributes &) = &G4LogicalVolume::SetVisAttributes
G4VSolid *(G4LogicalVolume::* pyG4LogicalVolume::f1_GetSolid)() const = &G4LogicalVolume::GetSolid
void(G4LogicalVolume::* pyG4LogicalVolume::f1_SetSolid)(G4VSolid *) = &G4LogicalVolume::SetSolid
Function Documentation
void export_G4LogicalVolume ()
Definition at line 71 of file pyG4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 71 of file pyG4LogicalVolume.cc
References G4LogicalVolume::AddDaughter(), G4LogicalVolume::ClearDaughters(), pyG4LogicalVolume::f1_GetSolid, pyG4LogicalVolume::f1_SetSolid, pyG4LogicalVolume::f1_SetVisAttributes, pyG4LogicalVolume::f2_SetVisAttributes, G4LogicalVolume::GetBiasWeight(), G4LogicalVolume::GetDaughter(), G4LogicalVolume::GetFastSimulationManager(), G4LogicalVolume::GetFieldManager(), G4LogicalVolume::GetMass(), G4LogicalVolume::GetMaterial(), G4LogicalVolume::GetMaterialCutsCouple(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSensitiveDetector(), G4LogicalVolume::GetSmartless(), G4LogicalVolume::GetUserLimits(), G4LogicalVolume::GetVisAttributes(), G4LogicalVolume::GetVoxelHeader(), init(), G4LogicalVolume::IsAncestor(), G4LogicalVolume::IsDaughter(), G4LogicalVolume::IsRegion(), G4LogicalVolume::IsRootRegion(), G4LogicalVolume::IsToOptimise(), G4LogicalVolume::PropagateRegion(), G4LogicalVolume::RemoveDaughter(), G4LogicalVolume::SetBiasWeight(), G4LogicalVolume::SetFieldManager(), G4LogicalVolume::SetMaterial(), G4LogicalVolume::SetMaterialCutsCouple(), G4LogicalVolume::SetName(), G4LogicalVolume::SetOptimisation(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetRegionRootFlag(), G4LogicalVolume::SetSensitiveDetector(), G4LogicalVolume::SetSmartless(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVoxelHeader(), G4LogicalVolume::TotalVolumeEntities(), and G4LogicalVolume::UpdateMaterial().
Referenced by BOOST_PYTHON_MODULE().