ECCE @ EIC Software: B02ImportanceDetectorConstruction Class Reference
B02ImportanceDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/include/B02ImportanceDetectorConstruction.hh>
Public Member Functions
B02ImportanceDetectorConstruction (G4String worldName)
virtual ~B02ImportanceDetectorConstruction ()
const G4VPhysicalVolume & GetPhysicalVolumeByName (const G4String &name) const
G4VPhysicalVolume & GetWorldVolumeAddress () const
G4String ListPhysNamesAsG4String ()
G4String GetCellName (G4int i)
G4GeometryCell GetGeometryCell (G4int i)
G4VPhysicalVolume * GetWorldVolume ()
void SetSensitive ()
virtual void Construct ()
virtual void ConstructSD ()
G4VIStore * CreateImportanceStore ()
G4VWeightWindowStore * CreateWeightWindowStore ()
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Attributes
B02PVolumeStore fPVolumeStore
std::vector< G4LogicalVolume * > fLogicalVolumeVector
G4VPhysicalVolume * fGhostWorld
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 48 of file B02ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 48 of file B02ImportanceDetectorConstruction.hh
Constructor & Destructor Documentation
B02ImportanceDetectorConstruction::B02ImportanceDetectorConstruction (G4String worldName)
Definition at line 63 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 63 of file B02ImportanceDetectorConstruction.cc
B02ImportanceDetectorConstruction::~B02ImportanceDetectorConstruction () virtual
Definition at line 71 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 71 of file B02ImportanceDetectorConstruction.cc
References fLogicalVolumeVector.
Member Function Documentation
void B02ImportanceDetectorConstruction::Construct (void) virtual
Implements G4VUserParallelWorld.
Definition at line 78 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 78 of file B02ImportanceDetectorConstruction.cc
References B02PVolumeStore::AddPVolume(), cm, deg, fGhostWorld, fLogicalVolumeVector, fPVolumeStore, G4cout, G4endl, GetCellName(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4VUserParallelWorld::GetWorld(), and SetSensitive().
void B02ImportanceDetectorConstruction::ConstructSD () virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 266 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 266 of file B02ImportanceDetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4PSTrackLength::DivideByVelocity(), fCurrent_In, fLogicalVolumeVector, G4SDManager::GetSDMpointer(), it, G4PSTrackLength::MultiplyKineticEnergy(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VSensitiveDetector::SetFilter(), G4VUserParallelWorld::SetSensitiveDetector(), G4PSTrackLength::Weighted(), and G4PSNofCollision::Weighted().
G4VIStore * B02ImportanceDetectorConstruction::CreateImportanceStore ()
Definition at line 336 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 336 of file B02ImportanceDetectorConstruction.cc
References G4IStore::AddImportanceGeometryCell(), fPVolumeStore, G4cout, G4endl, G4Exception(), GetGeometryCell(), G4IStore::GetInstance(), G4VUserParallelWorld::GetName(), G4VPhysicalVolume::GetName(), G4GeometryCell::GetPhysicalVolume(), G4GeometryCell::GetReplicaNumber(), GetWorldVolumeAddress(), RunMustBeAborted, and B02PVolumeStore::Size().
Referenced by main().
G4VWeightWindowStore * B02ImportanceDetectorConstruction::CreateWeightWindowStore ()
Definition at line 392 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 392 of file B02ImportanceDetectorConstruction.cc
References G4WeightWindowStore::AddLowerWeights(), fPVolumeStore, G4cout, G4endl, G4Exception(), GetGeometryCell(), G4WeightWindowStore::GetInstance(), G4VUserParallelWorld::GetName(), G4VPhysicalVolume::GetName(), G4GeometryCell::GetPhysicalVolume(), G4GeometryCell::GetReplicaNumber(), GetWorldVolumeAddress(), GeV, n, RunMustBeAborted, G4WeightWindowStore::SetGeneralUpperEnergyBounds(), and B02PVolumeStore::Size().
G4String B02ImportanceDetectorConstruction::GetCellName (G4int i)
Definition at line 204 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 204 of file B02ImportanceDetectorConstruction.cc
Referenced by Construct(), B02RunAction::EndOfRunAction(), and GetGeometryCell().
G4GeometryCell B02ImportanceDetectorConstruction::GetGeometryCell (G4int i)
Definition at line 217 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 217 of file B02ImportanceDetectorConstruction.cc
References fGhostWorld, fPVolumeStore, G4cout, G4endl, GetCellName(), and B02PVolumeStore::GetPVolume().
Referenced by CreateImportanceStore(), and CreateWeightWindowStore().
const G4VPhysicalVolume & B02ImportanceDetectorConstruction::GetPhysicalVolumeByName (const G4String & name) const
Definition at line 191 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 191 of file B02ImportanceDetectorConstruction.cc
References fPVolumeStore, and B02PVolumeStore::GetPVolume().
G4VPhysicalVolume * B02ImportanceDetectorConstruction::GetWorldVolume ()
Definition at line 240 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 240 of file B02ImportanceDetectorConstruction.cc
References fGhostWorld.
Referenced by main().
G4VPhysicalVolume & B02ImportanceDetectorConstruction::GetWorldVolumeAddress () const
Definition at line 234 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 234 of file B02ImportanceDetectorConstruction.cc
References fGhostWorld.
Referenced by CreateImportanceStore(), and CreateWeightWindowStore().
G4String B02ImportanceDetectorConstruction::ListPhysNamesAsG4String ()
Definition at line 197 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 197 of file B02ImportanceDetectorConstruction.cc
References fPVolumeStore, and B02PVolumeStore::GetPNames().
void B02ImportanceDetectorConstruction::SetSensitive ()
Definition at line 246 of file B02ImportanceDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 246 of file B02ImportanceDetectorConstruction.cc
Referenced by Construct().
Member Data Documentation
G4VPhysicalVolume* B02ImportanceDetectorConstruction::fGhostWorld private
Definition at line 82 of file B02ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file B02ImportanceDetectorConstruction.hh
Referenced by Construct(), GetGeometryCell(), GetWorldVolume(), and GetWorldVolumeAddress().
std::vector< G4LogicalVolume * > B02ImportanceDetectorConstruction::fLogicalVolumeVector private
Definition at line 78 of file B02ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 78 of file B02ImportanceDetectorConstruction.hh
Referenced by Construct(), ConstructSD(), and ~B02ImportanceDetectorConstruction().
B02PVolumeStore B02ImportanceDetectorConstruction::fPVolumeStore private
Definition at line 75 of file B02ImportanceDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file B02ImportanceDetectorConstruction.hh
Referenced by Construct(), CreateImportanceStore(), CreateWeightWindowStore(), GetGeometryCell(), GetPhysicalVolumeByName(), and ListPhysNamesAsG4String().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/include/B02ImportanceDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/src/B02ImportanceDetectorConstruction.cc