ECCE @ EIC Software: cheprep::IndentPrintWriter Class Reference
cheprep::IndentPrintWriter Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/IndentPrintWriter.h>
Public Member Functions
IndentPrintWriter (std::ostream *out, int level=0)
virtual ~IndentPrintWriter ()
void close ()
IndentPrintWriter & operator<< (const std::string &s)
IndentPrintWriter & operator<< (std::ostream &(*pf)(std::ostream &))
void println (const std::string &s)
void print (const std::string &s)
void println ()
void indent ()
void outdent ()
int getIndent () const
void setIndent (const int level)
std::string getIndentString () const
void setIndentString (const std::string &indentString)
Private Member Functions
void doIndent ()
Private Attributes
std::ostream * out
bool closed
int indentLevel
bool indented
std::string indentString
Detailed Description
Definition at line 21 of file IndentPrintWriter.h.
View newest version in sPHENIX GitHub at line 21 of file IndentPrintWriter.h
Constructor & Destructor Documentation
cheprep::IndentPrintWriter::IndentPrintWriter (std::ostream * out, int level = 0)
Definition at line 14 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 14 of file IndentPrintWriter.cc
cheprep::IndentPrintWriter::~IndentPrintWriter () virtual
Definition at line 22 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 22 of file IndentPrintWriter.cc
Member Function Documentation
void cheprep::IndentPrintWriter::close (void)
Definition at line 25 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 25 of file IndentPrintWriter.cc
References closed, and out.
Referenced by cheprep::XMLWriter::close(), cheprep::XMLWriter::closeTag(), and cheprep::XMLWriter::~XMLWriter().
void cheprep::IndentPrintWriter::doIndent () private
Definition at line 57 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 57 of file IndentPrintWriter.cc
References indented, indentLevel, indentString, and out.
Referenced by operator<<().
int cheprep::IndentPrintWriter::getIndent () const
Definition at line 72 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 72 of file IndentPrintWriter.cc
References indentLevel.
Referenced by cheprep::XMLWriter::printAttributes().
string cheprep::IndentPrintWriter::getIndentString () const
Definition at line 80 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 80 of file IndentPrintWriter.cc
References indentString.
Referenced by cheprep::XMLWriter::openDoc().
void cheprep::IndentPrintWriter::indent ()
Definition at line 64 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 64 of file IndentPrintWriter.cc
References indentLevel.
Referenced by cheprep::XMLWriter::openTag(), and cheprep::XMLWriter::printAttributes().
IndentPrintWriter & cheprep::IndentPrintWriter::operator<< (const std::string & s)
Definition at line 32 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 32 of file IndentPrintWriter.cc
References doIndent(), indented, and out.
IndentPrintWriter& cheprep::IndentPrintWriter::operator<< (std::ostream &(*)(std::ostream &) pf)
void cheprep::IndentPrintWriter::outdent ()
Definition at line 68 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 68 of file IndentPrintWriter.cc
References indentLevel.
Referenced by cheprep::XMLWriter::closeTag(), and cheprep::XMLWriter::printAttributes().
void cheprep::IndentPrintWriter::print (const std::string & s)
Definition at line 48 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 48 of file IndentPrintWriter.cc
void cheprep::IndentPrintWriter::println (const std::string & s)
Definition at line 44 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 44 of file IndentPrintWriter.cc
void cheprep::IndentPrintWriter::println ()
Definition at line 52 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 52 of file IndentPrintWriter.cc
References indented, and out.
void cheprep::IndentPrintWriter::setIndent (const int level)
Definition at line 76 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 76 of file IndentPrintWriter.cc
References indentLevel.
void cheprep::IndentPrintWriter::setIndentString (const std::string & indentString)
Definition at line 84 of file IndentPrintWriter.cc.
View newest version in sPHENIX GitHub at line 84 of file IndentPrintWriter.cc
References indentString.
Referenced by cheprep::XMLWriter::openDoc(), and cheprep::XMLWriter::XMLWriter().
Member Data Documentation
bool cheprep::IndentPrintWriter::closed private
Definition at line 44 of file IndentPrintWriter.h.
View newest version in sPHENIX GitHub at line 44 of file IndentPrintWriter.h
Referenced by close().
bool cheprep::IndentPrintWriter::indented private
Definition at line 46 of file IndentPrintWriter.h.
View newest version in sPHENIX GitHub at line 46 of file IndentPrintWriter.h
Referenced by doIndent(), operator<<(), and println().
int cheprep::IndentPrintWriter::indentLevel private
Definition at line 45 of file IndentPrintWriter.h.
View newest version in sPHENIX GitHub at line 45 of file IndentPrintWriter.h
Referenced by doIndent(), getIndent(), indent(), outdent(), and setIndent().
std::string cheprep::IndentPrintWriter::indentString private
Definition at line 47 of file IndentPrintWriter.h.
View newest version in sPHENIX GitHub at line 47 of file IndentPrintWriter.h
Referenced by doIndent(), getIndentString(), and setIndentString().
std::ostream* cheprep::IndentPrintWriter::out private
Definition at line 43 of file IndentPrintWriter.h.
View newest version in sPHENIX GitHub at line 43 of file IndentPrintWriter.h
Referenced by close(), doIndent(), operator<<(), and println().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/IndentPrintWriter.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/IndentPrintWriter.cc