ECCE @ EIC Software: G4ParticleHPCaptureData Class Reference
G4ParticleHPCaptureData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPCaptureData.hh>
Public Member Functions
G4ParticleHPCaptureData ()
~G4ParticleHPCaptureData ()
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int, G4int, const G4Element *, const G4Material *)
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, G4double aT)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
void IgnoreOnFlightDopplerBroadening ()
void EnableOnFlightDopplerBroadening ()
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4PhysicsTable * theCrossSections
G4bool onFlightDB
G4bool instanceOfWorker
G4double ke_cache
G4double xs_cache
const G4Element * element_cache
const G4Material * material_cache
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 51 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPCaptureData.hh
Constructor & Destructor Documentation
G4ParticleHPCaptureData::G4ParticleHPCaptureData ()
Definition at line 50 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPCaptureData.cc
References element_cache, instanceOfWorker, G4Threading::IsWorkerThread(), ke_cache, material_cache, MeV, onFlightDB, G4VCrossSectionDataSet::SetMaxKinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theCrossSections, and xs_cache.
G4ParticleHPCaptureData::~G4ParticleHPCaptureData ()
Definition at line 72 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPCaptureData.cc
References G4PhysicsTable::clearAndDestroy(), instanceOfWorker, and theCrossSections.
Member Function Documentation
void G4ParticleHPCaptureData::BuildPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 120 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 120 of file G4ParticleHPCaptureData.cc
References G4PhysicsTable::clearAndDestroy(), G4cout, G4endl, G4ThreadLocal, G4ParticleHPManager::GetCaptureCrossSections(), G4Element::GetElementTable(), G4ParticleHPManager::GetInstance(), G4Element::GetNumberOfElements(), G4ParticleHPData::Instance(), G4Threading::IsWorkerThread(), G4ParticleHPData::MakePhysicsVector(), G4Neutron::Neutron(), onFlightDB, G4PhysicsTable::push_back(), G4ParticleHPManager::RegisterCaptureCrossSections(), and theCrossSections.
void G4ParticleHPCaptureData::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 298 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 298 of file G4ParticleHPCaptureData.cc
void G4ParticleHPCaptureData::DumpPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 165 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 165 of file G4ParticleHPCaptureData.cc
References barn, eV, G4cout, G4endl, G4ThreadLocal, G4Element::GetElementTable(), G4Pow::GetInstance(), G4Element::GetNumberOfElements(), MeV, G4Neutron::Neutron(), and G4Pow::powA().
void G4ParticleHPCaptureData::EnableOnFlightDopplerBroadening () inline
Definition at line 83 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPCaptureData.hh
References onFlightDB.
G4double G4ParticleHPCaptureData::GetCrossSection (const G4DynamicParticle * aP, const G4Element * anE, G4double aT)
Definition at line 218 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 218 of file G4ParticleHPCaptureData.cc
References kdfinder::abs(), eps, G4DynamicParticle::GetDefinition(), G4Element::GetIndex(), G4ReactionProduct::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4DynamicParticle::GetMomentum(), G4Element::GetN(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetThermalNucleus(), G4Element::GetZ(), source.hepunit::k_Boltzmann, kelvin, G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag(), max, G4Neutron::Neutron(), onFlightDB, G4ReactionProduct::SetMomentum(), and theCrossSections.
Referenced by GetIsoCrossSection().
G4double G4ParticleHPCaptureData::GetIsoCrossSection (const G4DynamicParticle * dp, G4int , G4int , const G4Isotope * , const G4Element * element, const G4Material * material) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 94 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPCaptureData.cc
References element_cache, GetCrossSection(), G4DynamicParticle::GetKineticEnergy(), ke_cache, material(), material_cache, and xs_cache.
G4int G4ParticleHPCaptureData::GetVerboseLevel () const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 290 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 290 of file G4ParticleHPCaptureData.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::GetVerboseLevel().
void G4ParticleHPCaptureData::IgnoreOnFlightDopplerBroadening () inline
Definition at line 82 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPCaptureData.hh
References onFlightDB.
G4bool G4ParticleHPCaptureData::IsIsoApplicable (const G4DynamicParticle * dp, G4int , G4int , const G4Element * , const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 81 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPCaptureData.cc
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4VCrossSectionDataSet::GetMaxKinEnergy(), G4VCrossSectionDataSet::GetMinKinEnergy(), and G4Neutron::Neutron().
void G4ParticleHPCaptureData::SetVerboseLevel (G4int newValue) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 294 of file G4ParticleHPCaptureData.cc.
View newest version in sPHENIX GitHub at line 294 of file G4ParticleHPCaptureData.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::SetVerboseLevel().
Member Data Documentation
const G4Element* G4ParticleHPCaptureData::element_cache private
Definition at line 99 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPCaptureData.hh
Referenced by G4ParticleHPCaptureData(), and GetIsoCrossSection().
G4bool G4ParticleHPCaptureData::instanceOfWorker private
Definition at line 95 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPCaptureData.hh
Referenced by G4ParticleHPCaptureData(), and ~G4ParticleHPCaptureData().
G4double G4ParticleHPCaptureData::ke_cache private
Definition at line 97 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPCaptureData.hh
Referenced by G4ParticleHPCaptureData(), and GetIsoCrossSection().
const G4Material* G4ParticleHPCaptureData::material_cache private
Definition at line 100 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPCaptureData.hh
Referenced by G4ParticleHPCaptureData(), and GetIsoCrossSection().
G4bool G4ParticleHPCaptureData::onFlightDB private
Definition at line 94 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPCaptureData.hh
Referenced by BuildPhysicsTable(), EnableOnFlightDopplerBroadening(), G4ParticleHPCaptureData(), GetCrossSection(), and IgnoreOnFlightDopplerBroadening().
G4PhysicsTable* G4ParticleHPCaptureData::theCrossSections private
Definition at line 92 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPCaptureData.hh
Referenced by BuildPhysicsTable(), G4ParticleHPCaptureData(), GetCrossSection(), and ~G4ParticleHPCaptureData().
G4double G4ParticleHPCaptureData::xs_cache private
Definition at line 98 of file G4ParticleHPCaptureData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPCaptureData.hh
Referenced by G4ParticleHPCaptureData(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPCaptureData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPCaptureData.cc