ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/hijing1_383/hijing1.383.f File Reference
hijing1.383.f File Reference
Functions/Subroutines
subroutine hijing (BMIN0, BMAX0)
subroutine hijset (efrm)
function fnkick (X)
function fnkick2 (X)
function fnstru (X)
function fnstrum (X)
function fnstrus (X)
subroutine hiboost
subroutine quench (JPJT, NTP)
subroutine hijfrg (JTP, NTP, IERROR)
subroutine hijsrt (JPJT, NPT)
subroutine attrad (IERROR)
subroutine ar3jet (S, X1, X3, JL)
subroutine arorie (S, X1, X3, JL)
subroutine atrobo (THE, PHI, BEX, BEY, BEZ, IMIN, IMAX, IERROR)
subroutine hijhrd (JP, JT, JOUT, JFLG, IOPJET0)
subroutine jetini (JP, JT, I_TRIG)
subroutine hijini
subroutine attflv (ID, IDQ, IDQQ)
subroutine hijcsc (JP, JT)
subroutine hijels (PSC1, PSC2)
subroutine hijsft (JP, JT, JOUT, IERROR)
subroutine hijflv (ID)
subroutine hiptdi (PT, PTMAX, IOPT)
subroutine hijwds (IA, IDH, XHIGH)
function wdsax (X)
function rwdsax (X)
function wdsax1 (X)
function wdsax2 (X)
function profile (XB)
function flap (X)
function fgp1 (X)
function fgp2 (X)
function fgp3 (X)
function flap1 (X)
function flap2 (X)
subroutine hifun (I, XMIN, XMAX, FHB)
function hirnd (I)
function hirnd2 (I, XMIN, XMAX)
subroutine hijcrs
function ftot (X)
function fhin (X)
function ftotjet (X)
function ftotrig (X)
function fnjet (X)
function sgmin (N)
function omg0 (X)
function romg (X)
function bk (X)
subroutine crsjet
function fjet (X, WGT)
function fjetrig (X, WGT)
function ghvq (Y1, Y2, AMT2)
function gphoton (Y1, Y2, PT2)
function g (Y1, Y2, PT2)
function subcrs1 (T, U)
function subcrs2 (T, U)
function subcrs3 (T, U)
function subcrs4 (T, U)
function subcrs5 (T, U)
function subcrs6 (T, U)
function subcrs7 (T, U)
subroutine parton (F, X1, X2, QQ)
function gmre (X)
function gmin (N)
subroutine vegas (FXN, AVGI, SD, CHI2A)
subroutine aran9 (QRAN, NDIM)
function gauss1 (F, A, B, EPS)
function gauss2 (F, A, B, EPS)
function gauss3 (F, A, B, EPS)
function gauss4 (F, A, B, EPS)
subroutine title
Function/Subroutine Documentation
subroutine ar3jet (S, X1, X3, JL)
Definition at line 2194 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 2194 of file hijing1.383.f
References a, c, common(), d, c2_factory< float_type >::exp(), fg(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), k, le, min, n, RanSeed::nseed(), rlu(), c2_factory< float_type >::sqrt(), v, x1, x2, x3, y, and ymax.
subroutine aran9 (dimension(10) QRAN, NDIM)
Definition at line 5797 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5797 of file hijing1.383.f
References common(), and rlu().
subroutine arorie (S, X1, X3, JL)
Definition at line 2250 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 2250 of file hijing1.383.f
References common(), c2_factory< float_type >::cos(), e1, e3, HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), k, max, min, n, RanSeed::nseed(), G4StokesVector::p1(), G4StokesVector::p3(), CLHEP::HepEulerAngles::psi(), pt1, rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulangl(), v, w, x1, x2, and x3.
subroutine atrobo (THE, PHI, BEX, BEY, BEZ, IMIN, IMAX, IERROR)
Definition at line 2307 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 2307 of file hijing1.383.f
References common(), c2_factory< float_type >::cos(), e, imax, k, n, phi, c2_factory< float_type >::sin(), and v.
subroutine attflv (ID, IDQ, IDQQ)
Definition at line 3392 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 3392 of file hijing1.383.f
References common(), FW::HepMC3Particle::id(), RanSeed::nseed(), rlu(), and x.
subroutine attrad (IERROR)
Definition at line 2070 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 2070 of file hijing1.383.f
References ar3jet(), arorie(), atrobo(), common(), e, c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), imax, k, m, max, min, n, G4StokesVector::p1(), G4StokesVector::p2(), G4StokesVector::p3(), phi, rlu(), c2_factory< float_type >::sqrt(), theta(), ulangl(), v, wp, x1, and x3.
function bk (X)
Definition at line 5001 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5001 of file hijing1.383.f
References bk, c2_factory< float_type >::exp(), x, and x4.
subroutine crsjet ()
Definition at line 5012 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5012 of file hijing1.383.f
References common(), f, fjet(), fjetrig(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), it, n, and vegas().
function fgp1 (X)
Definition at line 4707 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4707 of file hijing1.383.f
References bb, common(), fgp1(), fgp2(), gauss3(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), phi, x, and z1.
function fgp2 (X)
Definition at line 4718 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4718 of file hijing1.383.f
References bb, common(), fgp2(), fgp3(), gauss4(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), phi, x, and z1.
function fgp3 (X)
Definition at line 4729 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4729 of file hijing1.383.f
References bb, common(), c2_factory< float_type >::cos(), fgp3(), phi, r1, r2, c2_factory< float_type >::sqrt(), wdsax1(), wdsax2(), x, and z1.
function fhin (X)
Definition at line 4894 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4894 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), fhin(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), omg0(), and x.
function fjet (dimension(10) X, WGT)
Definition at line 5082 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5082 of file hijing1.383.f
References common(), fjet(), g, HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), pt2, x, CLHEP::HepBoost::xt(), y1, and y2.
function fjetrig (dimension(10) X, WGT)
Definition at line 5102 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5102 of file hijing1.383.f
References common(), fjetrig(), g, ghvq(), gphoton(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), max, pt2, x, CLHEP::HepBoost::xt(), y1, and y2.
function flap (X)
Definition at line 4696 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4696 of file hijing1.383.f
References bb, common(), fgp1(), flap(), gauss2(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), phi, x, and z1.
function flap1 (X)
Definition at line 4739 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4739 of file hijing1.383.f
References bb, common(), flap1(), phi, r, c2_factory< float_type >::sqrt(), wdsax1(), x, and z1.
function flap2 (X)
Definition at line 4748 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4748 of file hijing1.383.f
References bb, common(), flap2(), phi, r, c2_factory< float_type >::sqrt(), wdsax2(), x, and z1.
function fnjet (X)
Definition at line 4925 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4925 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), fnjet(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), n, omg0(), sgmin(), and x.
function fnkick (X)
Definition at line 1005 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1005 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), fnkick(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), c2_factory< float_type >::sqrt(), and x.
function fnkick2 (X)
Definition at line 1014 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1014 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), fnkick2(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), and x.
function fnstru (X)
Definition at line 1023 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1023 of file hijing1.383.f
References common(), fnstru(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), and x.
function fnstrum (X)
Definition at line 1033 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1033 of file hijing1.383.f
References common(), fnstrum(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), and x.
function fnstrus (X)
Definition at line 1042 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1042 of file hijing1.383.f
References common(), fnstrus(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), and x.
function ftot (X)
Definition at line 4884 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4884 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), ftot(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), omg0(), and x.
function ftotjet (X)
Definition at line 4904 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4904 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), ftotjet(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), omg0(), and x.
function ftotrig (X)
Definition at line 4914 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4914 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), ftotrig(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), omg0(), and x.
function g (Y1, Y2, PT2)
Definition at line 5205 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5205 of file hijing1.383.f
References common(), f, g, g4, HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), parton(), pt2, subcrs1(), subcrs2(), subcrs3(), subcrs4(), subcrs5(), subcrs6(), subcrs7(), t, x1, x2, CLHEP::HepBoost::xt(), y1, y2, and z.
function gauss1 (external F, A, B, EPS)
Definition at line 5809 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5809 of file hijing1.383.f
References a, b, bb, c1, c2, e, eps, f, gauss1(), w, x, and y.
function gauss2 (external F, A, B, EPS)
Definition at line 5851 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5851 of file hijing1.383.f
References a, b, bb, c1, c2, e, eps, f, gauss2(), w, x, and y.
function gauss3 (external F, A, B, EPS)
Definition at line 5893 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5893 of file hijing1.383.f
References a, b, bb, c1, c2, e, eps, f, gauss3(), w, x, and y.
function gauss4 (external F, A, B, EPS)
Definition at line 5936 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5936 of file hijing1.383.f
References a, b, bb, c1, c2, e, eps, f, gauss4(), w, x, and y.
function ghvq (Y1, Y2, AMT2)
Definition at line 5140 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5140 of file hijing1.383.f
References common(), f, ghvq(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), parton(), x1, x2, CLHEP::HepBoost::xt(), y1, and y2.
function gmin (N)
Definition at line 5456 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5456 of file hijing1.383.f
References common(), HiMain1::eatt(), gmin(), HiParnt::hint1(), HiParnt::hipr1(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), HiMain1::jatt(), HijJet2::k1sg(), HijJet2::k2sg(), HiMain2::katt(), HijJet1::kfpj(), HijJet1::kftj(), n, HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HiMain1::np(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HiMain1::nt(), HijJet1::ntj(), HiMain2::patt(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), HijCrdn::yp(), HijCrdn::yt(), and z.
function gmre (X)
Definition at line 5440 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5440 of file hijing1.383.f
References gmre(), x, and z.
function gphoton (Y1, Y2, PT2)
Definition at line 5170 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5170 of file hijing1.383.f
References common(), f, gphoton(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), parton(), pt2, t, x1, x2, CLHEP::HepBoost::xt(), y1, y2, and z.
subroutine hiboost ()
Definition at line 1053 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1053 of file hijing1.383.f
References common(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), k, n, c2_factory< float_type >::sqrt(), v, and y.
subroutine hifun (I, XMIN, XMAX, external FHB)
Definition at line 4763 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4763 of file hijing1.383.f
References common(), gauss1(), xmax, xmin, and xx.
subroutine hijcrs ()
Definition at line 4837 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4837 of file hijing1.383.f
References common(), crsjet(), fhin(), fnjet(), ftot(), ftotjet(), ftotrig(), gauss1(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), and n.
subroutine hijcsc (JP, JT)
Definition at line 3446 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 3446 of file hijing1.383.f
References bb, common(), dx, dy, dz, c2_factory< float_type >::exp(), hijels(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), k, max, HiStrng::nfp(), HiStrng::nft(), RanSeed::nseed(), pt, r2, rlu(), romg(), c2_factory< float_type >::sqrt(), HijCrdn::yp(), and HijCrdn::yt().
subroutine hijels (dimension(5) PSC1, dimension(5) PSC2)
Definition at line 3580 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 3580 of file hijing1.383.f
References bb, common(), c2_factory< float_type >::cos(), c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), min, RanSeed::nseed(), phi, rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), and CLHEP::HepBoost::tt().
subroutine hijflv (ID)
Definition at line 4506 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4506 of file hijing1.383.f
References common(), FW::HepMC3Particle::id(), RanSeed::nseed(), and rlu().
subroutine hijfrg (JTP, NTP, IERROR)
Definition at line 1629 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1629 of file hijing1.383.f
References attrad(), common(), HiParnt::hint1(), HiParnt::hipr1(), hirobo(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), k, HijJet2::k1sg(), HijJet2::k2sg(), HijJet1::kfpj(), HijJet1::kftj(), luedit(), luexec(), n, HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HijJet1::ntj(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), rlu(), c2_factory< float_type >::sqrt(), and v.
subroutine hijhrd (JP, JT, JOUT, JFLG, IOPJET0)
Definition at line 2366 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 2366 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HijJet4::iadr(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), it, k, HijJet2::k1sg(), HijJet2::k2sg(), HijJet4::kfdr(), HijJet1::kfpj(), HijJet1::kftj(), n, HijJet4::ndr(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HijJet1::ntj(), HijJet4::pdr(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), pyp(), HijJet2::pysg(), pythia(), HijJet2::pzsg(), rlu(), c2_factory< float_type >::sqrt(), sw, ulmass(), v, wp, HijCrdn::yp(), and HijCrdn::yt().
subroutine hijing (BMIN0, BMAX0)
Definition at line 193 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 193 of file hijing1.383.f
References bb, common(), c2_factory< float_type >::cos(), kdfinder::Helix< T >::cx(), e, HiMain1::eatt(), c2_factory< float_type >::exp(), hiboost(), hijcsc(), hijfrg(), hijhrd(), hijini(), hijsft(), HiParnt::hint1(), HiParnt::hipr1(), hirnd(), HijJet4::iadr(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), int(), HiMain1::jatt(), jetini(), k, HijJet2::k1sg(), HijJet2::k2sg(), HiMain2::katt(), HijJet4::kfdr(), HijJet1::kfpj(), HijJet1::kftj(), Acts::Logger::log(), luedit(), lulist(), max, min, n, HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HijJet4::ndr(), HiStrng::nfp(), HiStrng::nft(), G4Abla::nint(), HijJet2::njsg(), HiMain1::np(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HiMain1::nt(), HijJet1::ntj(), HiMain2::patt(), HijJet4::pdr(), HijJet2::pesg(), phi, HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), quench(), r, r2, rlu(), romg(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), PHTimer::stop(), CLHEP::HepBoost::tt(), v, x, y1, y2, y3, HijCrdn::yp(), and HijCrdn::yt().
subroutine hijini ()
Definition at line 3294 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 3294 of file hijing1.383.f
References attflv(), common(), HiParnt::hint1(), HiParnt::hipr1(), HijJet4::iadr(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), HijJet2::k1sg(), HijJet2::k2sg(), HijJet4::kfdr(), HijJet1::kfpj(), HijJet1::kftj(), HijJet4::ndr(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HijJet1::ntj(), HijJet4::pdr(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), rlu(), c2_factory< float_type >::sqrt(), and ulmass().
subroutine hijset (efrm)
Definition at line 795 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 795 of file hijing1.383.f
References common(), efrm, fnkick(), fnkick2(), fnstru(), fnstrum(), fnstrus(), hifun(), hijcrs(), hijwds(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), lugive(), HiStrng::nfp(), HiStrng::nft(), proj, pt, rmax(), c2_factory< float_type >::sqrt(), targ, title(), x, HijCrdn::yp(), and HijCrdn::yt().
subroutine hijsft (JP, JT, JOUT, IERROR)
Definition at line 3659 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 3659 of file hijing1.383.f
References bb, common(), c2_factory< float_type >::cos(), d1, d2, e, c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), hirnd2(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), HijJet2::k1sg(), HijJet2::k2sg(), HijJet1::kfpj(), HijJet1::kftj(), max, min, HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HijJet1::ntj(), HijJet2::pesg(), phi, HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), r1, r2, rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), sw, ulangl(), ulmass(), wp, x1, x2, xmax, xmin, HijCrdn::yp(), and HijCrdn::yt().
subroutine hijsrt (JPJT, NPT)
Definition at line 1932 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1932 of file hijing1.383.f
References common(), e, HijJet1::kfpj(), HijJet1::kftj(), HijJet1::npj(), HijJet1::ntj(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), and y.
subroutine hijwds (IA, IDH, XHIGH)
Definition at line 4547 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4547 of file hijing1.383.f
References a, common(), d, gauss1(), hifun(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), r, G4StatDouble::rms(), rwdsax(), c2_factory< float_type >::sqrt(), w, and wdsax().
subroutine hiptdi (PT, PTMAX, IOPT)
Definition at line 4520 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4520 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), hirnd2(), HiParnt::ihnt2(), HiParnt::ihpr2(), max, min, RanSeed::nseed(), pt, rlu(), and c2_factory< float_type >::sqrt().
function hirnd (I)
Definition at line 4778 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4778 of file hijing1.383.f
References common(), hirnd(), RanSeed::nseed(), rlu(), and xx.
function hirnd2 (I, XMIN, XMAX)
Definition at line 4806 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4806 of file hijing1.383.f
References common(), hirnd2(), jmax, RanSeed::nseed(), rlu(), xmax, xmin, and xx.
subroutine jetini (JP, JT, I_TRIG)
Definition at line 3029 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 3029 of file hijing1.383.f
References common(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), max, min, HiStrng::nfp(), HiStrng::nft(), pt, pyinit(), targ, HijCrdn::yp(), and HijCrdn::yt().
function omg0 (X)
Definition at line 4954 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4954 of file hijing1.383.f
References bk, common(), gauss2(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), omg0(), c2_factory< float_type >::sqrt(), x, and x4.
subroutine parton (dimension(2,7) F, X1, X2, QQ)
Definition at line 5311 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5311 of file hijing1.383.f
References dfe::Variable::as(), common(), f, gmre(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), n, x1, and x2.
function profile (XB)
Definition at line 4673 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4673 of file hijing1.383.f
References bb, common(), flap(), flap1(), flap2(), gauss1(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), phi, profile(), Fun4AllFileOutStream::xb(), and z1.
subroutine quench (JPJT, NTP)
Definition at line 1088 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 1088 of file hijing1.383.f
References bb, common(), c2_factory< float_type >::cos(), dx, dy, c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), HijJet2::k1sg(), HijJet2::k2sg(), HijJet1::kfpj(), HijJet1::kftj(), max, CLHEP::HepLorentzVector::mt(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HijJet1::ntj(), HijJet2::pesg(), phi, HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), pt, HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), rlu(), c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), ulangl(), v1, v2, v3, HijCrdn::yp(), and HijCrdn::yt().
function romg (X)
Definition at line 4968 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4968 of file hijing1.383.f
References common(), int(), omg0(), romg(), and x.
function rwdsax (X)
Definition at line 4630 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4630 of file hijing1.383.f
References rwdsax(), wdsax(), and x.
function sgmin (N)
Definition at line 4941 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4941 of file hijing1.383.f
References n, sgmin(), and z.
function subcrs1 (T, U)
Definition at line 5259 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5259 of file hijing1.383.f
References subcrs1(), and t.
function subcrs2 (T, U)
Definition at line 5266 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5266 of file hijing1.383.f
References subcrs2(), and t.
function subcrs3 (T, U)
Definition at line 5273 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5273 of file hijing1.383.f
References subcrs3(), and t.
function subcrs4 (T, U)
Definition at line 5281 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5281 of file hijing1.383.f
References subcrs4(), and t.
function subcrs5 (T, U)
Definition at line 5289 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5289 of file hijing1.383.f
References subcrs5(), and t.
function subcrs6 (T, U)
Definition at line 5296 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5296 of file hijing1.383.f
References subcrs6(), and t.
function subcrs7 (T, U)
Definition at line 5303 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5303 of file hijing1.383.f
References subcrs7(), and t.
subroutine title ()
Definition at line 5980 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5980 of file hijing1.383.f
References x.
subroutine vegas (external FXN, AVGI, SD, CHI2A)
Definition at line 5567 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 5567 of file hijing1.383.f
References aran9(), common(), d, dx, f, f2, fb(), it, k, kg, G4Abla::mod(), one, r, and x.
function wdsax (X)
Definition at line 4618 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4618 of file hijing1.383.f
References common(), d, c2_factory< float_type >::exp(), r, c2_factory< float_type >::sqrt(), w, wdsax(), and x.
function wdsax1 (X)
Definition at line 4638 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4638 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), c2_factory< float_type >::sqrt(), wdsax1(), and x.
function wdsax2 (X)
Definition at line 4654 of file hijing1.383.f.
View newest version in sPHENIX GitHub at line 4654 of file hijing1.383.f
References common(), c2_factory< float_type >::exp(), HiParnt::hint1(), HiParnt::hipr1(), HiParnt::ihnt2(), HiParnt::ihpr2(), c2_factory< float_type >::sqrt(), wdsax2(), and x.