ECCE @ EIC Software: G4TextPPRetriever Class Reference
G4TextPPRetriever Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/utils/include/G4TextPPRetriever.hh>
Public Member Functions
G4TextPPRetriever ()
virtual ~G4TextPPRetriever ()
virtual void Retrieve (const G4String &option="")
Public Member Functions inherited from G4VParticlePropertyRetriever
G4VParticlePropertyRetriever ()
virtual ~G4VParticlePropertyRetriever ()
G4bool operator== (const G4VParticlePropertyRetriever &right) const
G4bool operator!= (const G4VParticlePropertyRetriever &right) const
Protected Member Functions
void SparseOption (const G4String &option)
G4bool ModifyPropertyTable (const G4ParticleDefinition *)
Protected Attributes
G4String baseDir
Protected Attributes inherited from G4VParticlePropertyRetriever
G4ParticlePropertyTable * pPropertyTable
Detailed Description
Definition at line 45 of file G4TextPPRetriever.hh.
View newest version in sPHENIX GitHub at line 45 of file G4TextPPRetriever.hh
Constructor & Destructor Documentation
G4TextPPRetriever::G4TextPPRetriever ()
Definition at line 48 of file G4TextPPRetriever.cc.
View newest version in sPHENIX GitHub at line 48 of file G4TextPPRetriever.cc
G4TextPPRetriever::~G4TextPPRetriever () virtual
Definition at line 53 of file G4TextPPRetriever.cc.
View newest version in sPHENIX GitHub at line 53 of file G4TextPPRetriever.cc
Member Function Documentation
G4bool G4TextPPRetriever::ModifyPropertyTable (const G4ParticleDefinition * particle) protected
Definition at line 91 of file G4TextPPRetriever.cc.
View newest version in sPHENIX GitHub at line 91 of file G4TextPPRetriever.cc
References baseDir, charge, G4DecayTable::entries(), eplus, G4cout, G4endl, G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4VDecayChannel::GetNumberOfDaughters(), G4ParticleDefinition::GetParticleName(), G4ParticlePropertyTable::GetParticleProperty(), G4ParticlePropertyData::GetPDGCharge(), G4ParticlePropertyData::GetPDGEncoding(), G4ParticlePropertyData::GetPDGiConjugation(), G4ParticlePropertyData::GetPDGiIsospin(), G4ParticlePropertyData::GetPDGiParity(), G4ParticlePropertyData::GetPDGiSpin(), G4ParticlePropertyData::GetPDGLifeTime(), G4ParticlePropertyData::GetPDGMass(), G4ParticlePropertyData::GetPDGWidth(), GeV, incremental_prev_tag::idx, in, mass, G4VParticlePropertyRetriever::pPropertyTable, second, G4VDecayChannel::SetBR(), G4ParticlePropertyTable::SetParticleProperty(), G4ParticlePropertyData::SetPDGCharge(), G4ParticlePropertyData::SetPDGLifeTime(), G4ParticlePropertyData::SetPDGMass(), G4ParticlePropertyData::SetPDGWidth(), and width.
Referenced by Retrieve().
void G4TextPPRetriever::Retrieve (const G4String & option = "") virtual
Implements G4VParticlePropertyRetriever.
Definition at line 58 of file G4TextPPRetriever.cc.
View newest version in sPHENIX GitHub at line 58 of file G4TextPPRetriever.cc
References G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), ModifyPropertyTable(), particle, G4ParticleTableIterator< K, V >::reset(), SparseOption(), theParticleIterator, and G4ParticleTableIterator< K, V >::value().
void G4TextPPRetriever::SparseOption (const G4String & option) protected
Definition at line 76 of file G4TextPPRetriever.cc.
View newest version in sPHENIX GitHub at line 76 of file G4TextPPRetriever.cc
References baseDir, and G4String::isNull().
Referenced by Retrieve().
Member Data Documentation
G4String G4TextPPRetriever::baseDir protected
Definition at line 62 of file G4TextPPRetriever.hh.
View newest version in sPHENIX GitHub at line 62 of file G4TextPPRetriever.hh
Referenced by ModifyPropertyTable(), and SparseOption().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/utils/include/G4TextPPRetriever.hh
geant4/tree/geant4-10.6-release/source/particles/utils/src/G4TextPPRetriever.cc