ECCE @ EIC Software: G4DNAPTBAugerModel Class Reference
G4DNAPTBAugerModel Class Reference
The G4DNAPTBAugerModel class Implement the PTB Auger model.
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAPTBAugerModel.hh>
Public Member Functions
G4DNAPTBAugerModel (const G4String &modelName)
G4DNAPTBAugerModel Constructor.
virtual ~G4DNAPTBAugerModel ()
~G4DNAPTBAugerModel Destructor
virtual void Initialise ()
Initialise Set the verbose value.
void SetCutForAugerElectrons (G4double cut)
SetCutForAugerElectrons Set the cut for the auger electrons production.
void ComputeAugerEffect (std::vector< G4DynamicParticle * > *fvect, const G4String &materialNameIni, G4double bindingEnergy)
ComputeAugerEffect Main method to be called by the ionisation model.
Private Member Functions
void GenerateAugerWithRandomDirection (std::vector< G4DynamicParticle * > *fvect, G4double kineticEnergy)
GenerateAugerWithRandomDirection Generates the auger particle.
G4double CalculAugerEnergyFor (G4int atomId)
CalculAugerEnergyFor.
G4int DetermineIonisedAtom (G4int atomId, const G4String &materialName, G4double bindingEnergy)
DetermineIonisedAtom.
G4DNAPTBAugerModel (G4DNAPTBAugerModel &)
G4DNAPTBAugerModel & operator= (const G4DNAPTBAugerModel &right)
Private Attributes
const G4String modelName
name of the auger model
G4int verboseLevel
G4double minElectronEnergy
Detailed Description
The G4DNAPTBAugerModel class Implement the PTB Auger model.
Definition at line 60 of file G4DNAPTBAugerModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4DNAPTBAugerModel.hh
Constructor & Destructor Documentation
G4DNAPTBAugerModel::G4DNAPTBAugerModel (const G4String & modelName)
G4DNAPTBAugerModel Constructor.
Parameters
modelName
Definition at line 41 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4DNAPTBAugerModel.cc
References G4cout, G4endl, and modelName.
G4DNAPTBAugerModel::~G4DNAPTBAugerModel () virtual
~G4DNAPTBAugerModel Destructor
Definition at line 47 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4DNAPTBAugerModel.cc
References G4cout, G4endl, modelName, and verboseLevel.
G4DNAPTBAugerModel::G4DNAPTBAugerModel (G4DNAPTBAugerModel &) private
Member Function Documentation
G4double G4DNAPTBAugerModel::CalculAugerEnergyFor (G4int atomId) private
CalculAugerEnergyFor.
Parameters
atomId
Returns
the auger particle energy
Definition at line 136 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 136 of file G4DNAPTBAugerModel.cc
References kdfinder::abs(), eV, f1, f2, f3, G4UniformRand, and Y.
Referenced by ComputeAugerEffect().
void G4DNAPTBAugerModel::ComputeAugerEffect (std::vector< G4DynamicParticle * > * fvect, const G4String & materialNameIni, G4double bindingEnergy)
ComputeAugerEffect Main method to be called by the ionisation model.
Parameters
fvect
materialNameIni
bindingEnergy
Definition at line 65 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4DNAPTBAugerModel.cc
References CalculAugerEnergyFor(), DetermineIonisedAtom(), g4zmq::exit(), G4cerr, G4endl, and GenerateAugerWithRandomDirection().
Referenced by G4DNAPTBIonisationModel::SampleSecondaries().
G4int G4DNAPTBAugerModel::DetermineIonisedAtom (G4int atomId, const G4String & materialName, G4double bindingEnergy) private
DetermineIonisedAtom.
Parameters
atomId
materialName
bindingEnergy
Returns
the id of the chosen ionised atom
Definition at line 104 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 104 of file G4DNAPTBAugerModel.cc
Referenced by ComputeAugerEffect().
void G4DNAPTBAugerModel::GenerateAugerWithRandomDirection (std::vector< G4DynamicParticle * > * fvect, G4double kineticEnergy) private
GenerateAugerWithRandomDirection Generates the auger particle.
Parameters
fvect
kineticEnergy
Definition at line 188 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 188 of file G4DNAPTBAugerModel.cc
References G4Electron::Electron(), G4UniformRand, and twopi.
Referenced by ComputeAugerEffect().
void G4DNAPTBAugerModel::Initialise () virtual
Initialise Set the verbose value.
Definition at line 52 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4DNAPTBAugerModel.cc
References G4cout, G4endl, and verboseLevel.
Referenced by G4DNAPTBIonisationModel::Initialise().
G4DNAPTBAugerModel& G4DNAPTBAugerModel::operator= (const G4DNAPTBAugerModel & right) private
void G4DNAPTBAugerModel::SetCutForAugerElectrons (G4double cut)
SetCutForAugerElectrons Set the cut for the auger electrons production.
Parameters
cut
Definition at line 181 of file G4DNAPTBAugerModel.cc.
View newest version in sPHENIX GitHub at line 181 of file G4DNAPTBAugerModel.cc
References minElectronEnergy.
Member Data Documentation
G4double G4DNAPTBAugerModel::minElectronEnergy private
Definition at line 105 of file G4DNAPTBAugerModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4DNAPTBAugerModel.hh
Referenced by SetCutForAugerElectrons().
const G4String G4DNAPTBAugerModel::modelName private
name of the auger model
Definition at line 102 of file G4DNAPTBAugerModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4DNAPTBAugerModel.hh
Referenced by G4DNAPTBAugerModel(), and ~G4DNAPTBAugerModel().
G4int G4DNAPTBAugerModel::verboseLevel private
Definition at line 104 of file G4DNAPTBAugerModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNAPTBAugerModel.hh
Referenced by Initialise(), and ~G4DNAPTBAugerModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAPTBAugerModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAPTBAugerModel.cc