ECCE @ EIC Software: pyRandomize Namespace Reference
pyRandomize Namespace Reference
Functions
void f1_setTheSeed (long seed)
void f2_setTheSeed (long seed, int lux)
void f1_setTheSeeds (const list &seedList)
void f2_setTheSeeds (const list &seedList, int aux)
list f_getTheSeeds ()
list f_getTheTableSeeds (int index)
void f1_saveEngineStatus ()
void f2_saveEngineStatus (const char *filename)
void f1_restoreEngineStatus ()
void f2_restoreEngineStatus (const char *filename)
int f1_RandBit_shootBit ()
double f1_RandGaussQ_shoot ()
double f2_RandGaussQ_shoot (double mean, double stdDev)
double f_G4UniformRand ()
Function Documentation
int pyRandomize::f1_RandBit_shootBit ()
Definition at line 146 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 146 of file pyRandomize.cc
Referenced by export_Randomize().
double pyRandomize::f1_RandGaussQ_shoot ()
Definition at line 152 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 152 of file pyRandomize.cc
References G4INCL::DeJongSpin::shoot().
Referenced by export_Randomize().
void pyRandomize::f1_restoreEngineStatus ()
Definition at line 135 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 135 of file pyRandomize.cc
Referenced by export_Randomize().
void pyRandomize::f1_saveEngineStatus ()
Definition at line 124 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 124 of file pyRandomize.cc
Referenced by export_Randomize().
void pyRandomize::f1_setTheSeed (long seed)
Definition at line 45 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 45 of file pyRandomize.cc
Referenced by export_Randomize().
void pyRandomize::f1_setTheSeeds (const list & seedList)
Definition at line 56 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 56 of file pyRandomize.cc
References incremental_prev_tag::idx.
Referenced by export_Randomize().
double pyRandomize::f2_RandGaussQ_shoot (double mean, double stdDev)
Definition at line 157 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 157 of file pyRandomize.cc
References G4INCL::DeJongSpin::shoot().
Referenced by export_Randomize().
void pyRandomize::f2_restoreEngineStatus (const char * filename)
Definition at line 140 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 140 of file pyRandomize.cc
Referenced by export_Randomize().
void pyRandomize::f2_saveEngineStatus (const char * filename)
Definition at line 129 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 129 of file pyRandomize.cc
Referenced by export_Randomize().
void pyRandomize::f2_setTheSeed (long seed, int lux)
Definition at line 50 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 50 of file pyRandomize.cc
Referenced by export_Randomize().
void pyRandomize::f2_setTheSeeds (const list & seedList, int aux)
Definition at line 76 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 76 of file pyRandomize.cc
References incremental_prev_tag::idx.
Referenced by export_Randomize().
double pyRandomize::f_G4UniformRand ()
Definition at line 164 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 164 of file pyRandomize.cc
References G4UniformRand.
Referenced by export_Randomize().
list pyRandomize::f_getTheSeeds ()
Definition at line 96 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 96 of file pyRandomize.cc
References incremental_prev_tag::idx.
Referenced by export_Randomize().
list pyRandomize::f_getTheTableSeeds (int index)
Definition at line 110 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 110 of file pyRandomize.cc
Referenced by export_Randomize().