ECCE @ EIC Software: G4ParticleHPLegendreStore Class Reference
G4ParticleHPLegendreStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLegendreStore.hh>
Public Member Functions
G4ParticleHPLegendreStore (G4int n)
~G4ParticleHPLegendreStore ()
void Init (G4int i, G4double e, G4int n)
void SetNPoints (G4int n)
void SetEnergy (G4int i, G4double energy)
void SetTemperature (G4int i, G4double temp)
void SetCoeff (G4int i, G4int l, G4double coeff)
void SetCoeff (G4int i, G4ParticleHPLegendreTable *theTable)
G4double GetCoeff (G4int i, G4int l)
G4double GetEnergy (G4int i)
G4double GetTemperature (G4int i)
G4int GetNumberOfPoly (G4int i)
G4double SampleDiscreteTwoBody (G4double anEnergy)
G4double SampleElastic (G4double anEnergy)
G4double Sample (G4double energy)
G4double SampleMax (G4double energy)
G4double Integrate (G4int k, G4double costh)
void InitInterpolation (std::istream &aDataFile)
void SetManager (G4InterpolationManager &aManager)
Private Attributes
G4int nEnergy
G4ParticleHPLegendreTable * theCoeff
G4InterpolationManager theManager
Detailed Description
Definition at line 37 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleHPLegendreStore.hh
Constructor & Destructor Documentation
G4ParticleHPLegendreStore::G4ParticleHPLegendreStore (G4int n) inline
Definition at line 41 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPLegendreStore.hh
References n, nEnergy, and theCoeff.
G4ParticleHPLegendreStore::~G4ParticleHPLegendreStore () inline
Definition at line 47 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPLegendreStore.hh
References theCoeff.
Member Function Documentation
G4double G4ParticleHPLegendreStore::GetCoeff (G4int i, G4int l) inline
Definition at line 68 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::GetCoeff(), and theCoeff.
Referenced by SampleDiscreteTwoBody(), SampleElastic(), and SampleMax().
G4double G4ParticleHPLegendreStore::GetEnergy (G4int i) inline
Definition at line 69 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::GetEnergy(), and theCoeff.
Referenced by Sample(), SampleDiscreteTwoBody(), SampleElastic(), and SampleMax().
G4int G4ParticleHPLegendreStore::GetNumberOfPoly (G4int i) inline
Definition at line 71 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::GetNumberOfPoly(), and theCoeff.
G4double G4ParticleHPLegendreStore::GetTemperature (G4int i) inline
Definition at line 70 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::GetTemperature(), and theCoeff.
void G4ParticleHPLegendreStore::Init (G4int i, G4double e, G4int n) inline
Definition at line 52 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::Init(), and theCoeff.
Referenced by G4ParticleHPElasticFS::Init(), G4ParticleHPAngular::Init(), and G4ParticleHPContAngularPar::Sample().
void G4ParticleHPLegendreStore::InitInterpolation (std::istream & aDataFile) inline
Definition at line 79 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPLegendreStore.hh
References G4InterpolationManager::Init(), and theManager.
Referenced by G4ParticleHPElasticFS::Init(), and G4ParticleHPAngular::Init().
G4double G4ParticleHPLegendreStore::Integrate (G4int k, G4double costh)
Definition at line 323 of file G4ParticleHPLegendreStore.cc.
View newest version in sPHENIX GitHub at line 323 of file G4ParticleHPLegendreStore.cc
References G4ParticleHPLegendreTable::GetCoeff(), G4ParticleHPLegendreTable::GetNumberOfPoly(), G4ParticleHPFastLegendre::Integrate(), k, and theCoeff.
Referenced by Sample().
G4double G4ParticleHPLegendreStore::Sample (G4double energy)
Definition at line 270 of file G4ParticleHPLegendreStore.cc.
View newest version in sPHENIX GitHub at line 270 of file G4ParticleHPLegendreStore.cc
References DBL_MAX, energy, G4UniformRand, GetEnergy(), G4ParticleHPLegendreTable::GetEnergy(), G4InterpolationManager::GetScheme(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetY(), Integrate(), G4ParticleHPInterpolator::Interpolate(), it, max, nEnergy, norm, G4ParticleHPVector::SetData(), theCoeff, theManager, x1, x2, y, y1, and y2.
G4double G4ParticleHPLegendreStore::SampleDiscreteTwoBody (G4double anEnergy)
Definition at line 44 of file G4ParticleHPLegendreStore.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPLegendreStore.cc
References G4ParticleHPFastLegendre::Evaluate(), G4cout, G4endl, G4UniformRand, GetCoeff(), GetEnergy(), G4ParticleHPLegendreTable::GetEnergy(), G4ParticleHPLegendreTable::GetNumberOfPoly(), G4InterpolationManager::GetScheme(), G4ParticleHPInterpolator::Interpolate(), legend, max, nEnergy, theCoeff, theManager, v1, v2, x, x1, and x2.
Referenced by G4ParticleHPDiscreteTwoBody::Sample().
G4double G4ParticleHPLegendreStore::SampleElastic (G4double anEnergy)
Definition at line 202 of file G4ParticleHPLegendreStore.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ParticleHPLegendreStore.cc
References G4ParticleHPFastLegendre::Evaluate(), G4cout, G4endl, G4UniformRand, GetCoeff(), GetEnergy(), G4ParticleHPLegendreTable::GetEnergy(), G4ParticleHPLegendreTable::GetNumberOfPoly(), G4InterpolationManager::GetScheme(), G4ParticleHPInterpolator::Interpolate(), legend, max, nEnergy, theCoeff, theManager, v1, v2, x, x1, and x2.
Referenced by G4ParticleHPElasticFS::ApplyYourself().
G4double G4ParticleHPLegendreStore::SampleMax (G4double energy)
Definition at line 126 of file G4ParticleHPLegendreStore.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPLegendreStore.cc
References G4ParticleHPFastLegendre::Evaluate(), G4cout, G4endl, G4UniformRand, GetCoeff(), GetEnergy(), G4ParticleHPLegendreTable::GetEnergy(), G4ParticleHPLegendreTable::GetNumberOfPoly(), G4InterpolationManager::GetScheme(), G4ParticleHPInterpolator::Interpolate(), legend, max, nEnergy, theCoeff, theManager, v1, v2, x, x1, and x2.
Referenced by G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPContAngularPar::Sample(), and G4ParticleHPAngular::SampleAndUpdate().
void G4ParticleHPLegendreStore::SetCoeff (G4int i, G4int l, G4double coeff) inline
Definition at line 59 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::SetCoeff(), and theCoeff.
Referenced by G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPElasticFS::Init(), G4ParticleHPAngular::Init(), G4ParticleHPDiscreteTwoBody::Sample(), and G4ParticleHPContAngularPar::Sample().
void G4ParticleHPLegendreStore::SetCoeff (G4int i, G4ParticleHPLegendreTable * theTable) inline
Definition at line 60 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPLegendreStore.hh
References nEnergy, and theCoeff.
void G4ParticleHPLegendreStore::SetEnergy (G4int i, G4double energy) inline
Definition at line 57 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::SetEnergy(), and theCoeff.
void G4ParticleHPLegendreStore::SetManager (G4InterpolationManager & aManager) inline
Definition at line 84 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPLegendreStore.hh
References theManager.
Referenced by G4ParticleHPDiscreteTwoBody::Sample(), and G4ParticleHPContAngularPar::Sample().
void G4ParticleHPLegendreStore::SetNPoints (G4int n) inline
Definition at line 56 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPLegendreStore.hh
References n, and nEnergy.
void G4ParticleHPLegendreStore::SetTemperature (G4int i, G4double temp) inline
Definition at line 58 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPLegendreStore.hh
References G4ParticleHPLegendreTable::SetTemperature(), and theCoeff.
Referenced by G4ParticleHPElasticFS::Init(), and G4ParticleHPAngular::Init().
Member Data Documentation
G4int G4ParticleHPLegendreStore::nEnergy private
Definition at line 91 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPLegendreStore.hh
Referenced by G4ParticleHPLegendreStore(), Sample(), SampleDiscreteTwoBody(), SampleElastic(), SampleMax(), SetCoeff(), and SetNPoints().
G4ParticleHPLegendreTable* G4ParticleHPLegendreStore::theCoeff private
Definition at line 92 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPLegendreStore.hh
Referenced by G4ParticleHPLegendreStore(), GetCoeff(), GetEnergy(), GetNumberOfPoly(), GetTemperature(), Init(), Integrate(), Sample(), SampleDiscreteTwoBody(), SampleElastic(), SampleMax(), SetCoeff(), SetEnergy(), SetTemperature(), and ~G4ParticleHPLegendreStore().
G4InterpolationManager G4ParticleHPLegendreStore::theManager private
Definition at line 93 of file G4ParticleHPLegendreStore.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPLegendreStore.hh
Referenced by InitInterpolation(), Sample(), SampleDiscreteTwoBody(), SampleElastic(), SampleMax(), and SetManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLegendreStore.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPLegendreStore.cc