ECCE @ EIC Software: G4THnManager< T > Class Template Reference
G4THnManager< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4THnManager.hh>
Public Member Functions
G4THnManager (const G4AnalysisManagerState &state, const G4String &hnType)
virtual ~G4THnManager ()
G4bool Reset ()
G4bool IsEmpty () const
Protected Member Functions
void AddTVector (const std::vector< T * > &tVector)
std::vector< T * >::iterator BeginT ()
std::vector< T * >::iterator EndT ()
std::vector< T * >::const_iterator BeginConstT () const
std::vector< T * >::const_iterator EndConstT () const
T * GetTInFunction (G4int id, G4String functionName, G4bool warn=true, G4bool onlyIfActive=true) const
G4int RegisterT (T *t, const G4String &name)
G4int GetTId (const G4String &name, G4bool warn=true) const
Protected Attributes
const G4AnalysisManagerState & fState
std::vector< T * > fTVector
std::map< G4String, G4int > fNameIdMap
std::shared_ptr< G4HnManager > fHnManager
Detailed Description
template<typename T>
class G4THnManager< T >
Definition at line 46 of file G4THnManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4THnManager.hh
Constructor & Destructor Documentation
template<typename T> G4THnManager< T >::G4THnManager (const G4AnalysisManagerState & state, const G4String & hnType)
template<typename T> virtual G4THnManager< T >::~G4THnManager () virtual
Member Function Documentation
template<typename T> void G4THnManager< T >::AddTVector (const std::vector< T * > & tVector) protected
template<typename T> std::vector<T*>::const_iterator G4THnManager< T >::BeginConstT () const protected
template<typename T> std::vector<T*>::iterator G4THnManager< T >::BeginT () protected
template<typename T> std::vector<T*>::const_iterator G4THnManager< T >::EndConstT () const protected
template<typename T> std::vector<T*>::iterator G4THnManager< T >::EndT () protected
template<typename T> G4int G4THnManager< T >::GetTId (const G4String & name, G4bool warn = true) const protected
template<typename T> T* G4THnManager< T >::GetTInFunction (G4int id, G4String functionName, G4bool warn = true, G4bool onlyIfActive = true) const protected
template<typename T> G4bool G4THnManager< T >::IsEmpty () const
Referenced by G4XmlAnalysisManager::CloseFileImpl(), G4RootAnalysisManager::CloseFileImpl(), G4XmlAnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), and G4RootAnalysisManager::WriteImpl().
template<typename T> G4int G4THnManager< T >::RegisterT (T * t, const G4String & name) protected
template<typename T> G4bool G4THnManager< T >::Reset ()
Referenced by G4ToolsAnalysisReader::Reset(), and G4ToolsAnalysisManager::Reset().
Member Data Documentation
template<typename T> std::shared_ptr<G4HnManager> G4THnManager< T >::fHnManager protected
Definition at line 82 of file G4THnManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4THnManager.hh
template<typename T> std::map<G4String, G4int> G4THnManager< T >::fNameIdMap protected
Definition at line 81 of file G4THnManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4THnManager.hh
template<typename T> const G4AnalysisManagerState& G4THnManager< T >::fState protected
Definition at line 79 of file G4THnManager.hh.
View newest version in sPHENIX GitHub at line 79 of file G4THnManager.hh
template<typename T> std::vector<T*> G4THnManager< T >::fTVector protected
Definition at line 80 of file G4THnManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4THnManager.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4THnManager.hh