ECCE @ EIC Software: G4PenelopeCrossSection Class Reference
G4PenelopeCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeCrossSection.hh>
Public Member Functions
G4PenelopeCrossSection (size_t nOfEnergyPoints, size_t nOfShells=0)
~G4PenelopeCrossSection ()
G4double GetTotalCrossSection (G4double energy) const
Returns total cross section at the given energy.
G4double GetHardCrossSection (G4double energy) const
Returns hard cross section at the given energy.
G4double GetSoftStoppingPower (G4double energy) const
Returns the total stopping power due to soft collisions.
G4double GetShellCrossSection (size_t shellID, G4double energy) const
Returns the hard cross section for the given shell (per molecule)
G4double GetNormalizedShellCrossSection (size_t shellID, G4double energy) const
Returns the hard cross section for the given shell (normalized to 1)
size_t GetNumberOfShells () const
void AddCrossSectionPoint (size_t binNumber, G4double energy, G4double XH0, G4double XH1, G4double XH2, G4double XS0, G4double XS1, G4double XS2)
void AddShellCrossSectionPoint (size_t binNumber, size_t shellID, G4double energy, G4double xs)
void NormalizeShellCrossSections ()
Private Member Functions
G4PenelopeCrossSection & operator= (const G4PenelopeCrossSection &right)
G4PenelopeCrossSection (const G4PenelopeCrossSection &)
Private Attributes
G4bool isNormalized
size_t numberOfEnergyPoints
size_t numberOfShells
G4PhysicsTable * softCrossSections
G4PhysicsTable * hardCrossSections
G4PhysicsTable * shellCrossSections
G4PhysicsTable * shellNormalizedCrossSections
Detailed Description
Definition at line 71 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PenelopeCrossSection.hh
Constructor & Destructor Documentation
G4PenelopeCrossSection::G4PenelopeCrossSection (size_t nOfEnergyPoints, size_t nOfShells = 0)
Definition at line 44 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 44 of file G4PenelopeCrossSection.cc
References FatalException, G4endl, G4Exception(), hardCrossSections, isNormalized, numberOfEnergyPoints, numberOfShells, G4PhysicsTable::push_back(), shellCrossSections, shellNormalizedCrossSections, and softCrossSections.
G4PenelopeCrossSection::~G4PenelopeCrossSection ()
Definition at line 97 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 97 of file G4PenelopeCrossSection.cc
References hardCrossSections, shellCrossSections, shellNormalizedCrossSections, and softCrossSections.
G4PenelopeCrossSection::G4PenelopeCrossSection (const G4PenelopeCrossSection &) private
Member Function Documentation
void G4PenelopeCrossSection::AddCrossSectionPoint (size_t binNumber, G4double energy, G4double XH0, G4double XH1, G4double XH2, G4double XS0, G4double XS1, G4double XS2)
Public interface for the master thread
Definition at line 123 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 123 of file G4PenelopeCrossSection.cc
References cm2, e, eV, G4cout, G4endl, hardCrossSections, max, numberOfEnergyPoints, G4PhysicsFreeVector::PutValue(), and softCrossSections.
Referenced by G4PenelopeIonisationXSHandler::BuildXSTable(), and G4PenelopeBremsstrahlungModel::BuildXSTable().
void G4PenelopeCrossSection::AddShellCrossSectionPoint (size_t binNumber, size_t shellID, G4double energy, G4double xs)
Definition at line 183 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 183 of file G4PenelopeCrossSection.cc
References cm2, e, G4cout, G4endl, max, numberOfEnergyPoints, numberOfShells, G4PhysicsFreeVector::PutValue(), and shellCrossSections.
Referenced by G4PenelopeIonisationXSHandler::BuildXSTable().
G4double G4PenelopeCrossSection::GetHardCrossSection (G4double energy) const
Returns hard cross section at the given energy.
Definition at line 268 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 268 of file G4PenelopeCrossSection.cc
References G4cout, G4endl, G4Exp(), G4PhysicsVector::GetVectorLength(), hardCrossSections, numberOfEnergyPoints, and G4PhysicsVector::Value().
Referenced by G4PenelopeBremsstrahlungModel::CrossSectionPerVolume(), and G4PenelopeIonisationModel::CrossSectionPerVolume().
G4double G4PenelopeCrossSection::GetNormalizedShellCrossSection (size_t shellID, G4double energy) const
Returns the hard cross section for the given shell (normalized to 1)
Definition at line 363 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 363 of file G4PenelopeCrossSection.cc
References G4cout, G4endl, G4Exp(), G4PhysicsVector::GetVectorLength(), isNormalized, numberOfEnergyPoints, numberOfShells, shellNormalizedCrossSections, and G4PhysicsVector::Value().
Referenced by G4PenelopeIonisationModel::SampleFinalStateElectron(), and G4PenelopeIonisationModel::SampleFinalStatePositron().
size_t G4PenelopeCrossSection::GetNumberOfShells () const inline
Definition at line 93 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PenelopeCrossSection.hh
References numberOfShells.
G4double G4PenelopeCrossSection::GetShellCrossSection (size_t shellID, G4double energy) const
Returns the hard cross section for the given shell (per molecule)
Definition at line 327 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 327 of file G4PenelopeCrossSection.cc
References G4cout, G4endl, G4Exp(), G4PhysicsVector::GetVectorLength(), numberOfEnergyPoints, numberOfShells, shellCrossSections, and G4PhysicsVector::Value().
Referenced by G4PenelopeIonisationCrossSection::CrossSection().
G4double G4PenelopeCrossSection::GetSoftStoppingPower (G4double energy) const
Returns the total stopping power due to soft collisions.
Definition at line 298 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 298 of file G4PenelopeCrossSection.cc
References G4cout, G4endl, G4Exp(), G4PhysicsVector::GetVectorLength(), numberOfEnergyPoints, softCrossSections, and G4PhysicsVector::Value().
Referenced by G4PenelopeBremsstrahlungModel::ComputeDEDXPerVolume(), and G4PenelopeIonisationModel::ComputeDEDXPerVolume().
G4double G4PenelopeCrossSection::GetTotalCrossSection (G4double energy) const
Returns total cross section at the given energy.
Definition at line 224 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 224 of file G4PenelopeCrossSection.cc
References G4cout, G4endl, G4Exp(), G4PhysicsVector::GetVectorLength(), hardCrossSections, numberOfEnergyPoints, softCrossSections, and G4PhysicsVector::Value().
Referenced by G4PenelopeIonisationModel::CrossSectionPerVolume().
void G4PenelopeCrossSection::NormalizeShellCrossSections ()
Definition at line 411 of file G4PenelopeCrossSection.cc.
View newest version in sPHENIX GitHub at line 411 of file G4PenelopeCrossSection.cc
References G4cout, G4endl, G4Exp(), G4PhysicsVector::GetLowEdgeEnergy(), isNormalized, normFactor, numberOfEnergyPoints, numberOfShells, G4PhysicsFreeVector::PutValue(), shellCrossSections, and shellNormalizedCrossSections.
Referenced by G4PenelopeIonisationXSHandler::BuildXSTable().
G4PenelopeCrossSection& G4PenelopeCrossSection::operator= (const G4PenelopeCrossSection & right) private
Member Data Documentation
G4PhysicsTable* G4PenelopeCrossSection::hardCrossSections private
Definition at line 121 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PenelopeCrossSection.hh
Referenced by AddCrossSectionPoint(), G4PenelopeCrossSection(), GetHardCrossSection(), GetTotalCrossSection(), and ~G4PenelopeCrossSection().
G4bool G4PenelopeCrossSection::isNormalized private
Definition at line 110 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 110 of file G4PenelopeCrossSection.hh
Referenced by G4PenelopeCrossSection(), GetNormalizedShellCrossSection(), and NormalizeShellCrossSections().
size_t G4PenelopeCrossSection::numberOfEnergyPoints private
Definition at line 112 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PenelopeCrossSection.hh
Referenced by AddCrossSectionPoint(), AddShellCrossSectionPoint(), G4PenelopeCrossSection(), GetHardCrossSection(), GetNormalizedShellCrossSection(), GetShellCrossSection(), GetSoftStoppingPower(), GetTotalCrossSection(), and NormalizeShellCrossSections().
size_t G4PenelopeCrossSection::numberOfShells private
Definition at line 113 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PenelopeCrossSection.hh
Referenced by AddShellCrossSectionPoint(), G4PenelopeCrossSection(), GetNormalizedShellCrossSection(), GetNumberOfShells(), GetShellCrossSection(), and NormalizeShellCrossSections().
G4PhysicsTable* G4PenelopeCrossSection::shellCrossSections private
Definition at line 124 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PenelopeCrossSection.hh
Referenced by AddShellCrossSectionPoint(), G4PenelopeCrossSection(), GetShellCrossSection(), NormalizeShellCrossSections(), and ~G4PenelopeCrossSection().
G4PhysicsTable* G4PenelopeCrossSection::shellNormalizedCrossSections private
Definition at line 125 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PenelopeCrossSection.hh
Referenced by G4PenelopeCrossSection(), GetNormalizedShellCrossSection(), NormalizeShellCrossSections(), and ~G4PenelopeCrossSection().
G4PhysicsTable* G4PenelopeCrossSection::softCrossSections private
Definition at line 118 of file G4PenelopeCrossSection.hh.
View newest version in sPHENIX GitHub at line 118 of file G4PenelopeCrossSection.hh
Referenced by AddCrossSectionPoint(), G4PenelopeCrossSection(), GetSoftStoppingPower(), GetTotalCrossSection(), and ~G4PenelopeCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4PenelopeCrossSection.cc