ECCE @ EIC Software: FW::Geant4::MMDetectorConstruction Class Reference
FW::Geant4::MMDetectorConstruction Class Reference
constructing the detector in Geant4 this can be used with GDML and TGeo iput
#include <acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMDetectorConstruction.hpp>
Public Member Functions
MMDetectorConstruction ()
Constructor.
G4VPhysicalVolume * Construct () finaloverride
void setTGeoGeometry (TGeoNode *tgeoNode)
void setGdmlInput (std::string gdmlFile)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
TGeoNode * m_tgeoNode
std::string * m_gdmlFile
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
constructing the detector in Geant4 this can be used with GDML and TGeo iput
implement it with conversion from TGeo
Definition at line 30 of file MMDetectorConstruction.hpp.
View newest version in sPHENIX GitHub at line 30 of file MMDetectorConstruction.hpp
Constructor & Destructor Documentation
FW::Geant4::MMDetectorConstruction::MMDetectorConstruction ()
Constructor.
Definition at line 14 of file MMDetectorConstruction.cpp.
View newest version in sPHENIX GitHub at line 14 of file MMDetectorConstruction.cpp
Member Function Documentation
G4VPhysicalVolume * FW::Geant4::MMDetectorConstruction::Construct (void) final override virtual
Construct method
Returns
the world volume as G4VPhysicalVolume
Implements G4VUserDetectorConstruction.
Definition at line 17 of file MMDetectorConstruction.cpp.
View newest version in sPHENIX GitHub at line 17 of file MMDetectorConstruction.cpp
References G4GDMLParser::GetWorldVolume(), parser(), and G4GDMLParser::Read().
void FW::Geant4::MMDetectorConstruction::setGdmlInput (std::string gdmlFile)
Set the path and name to the GDML file
Parameters
gdmlFile is the path+name of the GDML file
Definition at line 43 of file MMDetectorConstruction.cpp.
View newest version in sPHENIX GitHub at line 43 of file MMDetectorConstruction.cpp
void FW::Geant4::MMDetectorConstruction::setTGeoGeometry (TGeoNode * tgeoNode)
Set the world TGeoNode to be transformed into a Geant4 geometry
Parameters
tgeoNode is the world not in ROOT::TGeo
Definition at line 39 of file MMDetectorConstruction.cpp.
View newest version in sPHENIX GitHub at line 39 of file MMDetectorConstruction.cpp
Member Data Documentation
std::string* FW::Geant4::MMDetectorConstruction::m_gdmlFile private
Definition at line 50 of file MMDetectorConstruction.hpp.
View newest version in sPHENIX GitHub at line 50 of file MMDetectorConstruction.hpp
TGeoNode* FW::Geant4::MMDetectorConstruction::m_tgeoNode private
Definition at line 49 of file MMDetectorConstruction.hpp.
View newest version in sPHENIX GitHub at line 49 of file MMDetectorConstruction.hpp
The documentation for this class was generated from the following files:
acts/blob/master/Examples/Algorithms/Geant4/include/ACTFW/Plugins/Geant4/MMDetectorConstruction.hpp
acts/blob/master/Examples/Algorithms/Geant4/src/MMDetectorConstruction.cpp