ECCE @ EIC Software: G4INCL::NKToNKpiChannel Class Reference
G4INCL::NKToNKpiChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNKToNKpiChannel.hh>
Public Member Functions
NKToNKpiChannel (Particle *, Particle *)
virtual ~NKToNKpiChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (NKToNKpiChannel)
Private Attributes
Particle * particle1
Particle * particle2
Static Private Attributes
static const G4double angularSlope = 4.
Detailed Description
Definition at line 47 of file G4INCLNKToNKpiChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNKToNKpiChannel.hh
Constructor & Destructor Documentation
G4INCL::NKToNKpiChannel::NKToNKpiChannel (Particle * p1, Particle * p2)
Definition at line 51 of file G4INCLNKToNKpiChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLNKToNKpiChannel.cc
G4INCL::NKToNKpiChannel::~NKToNKpiChannel () virtual
Definition at line 55 of file G4INCLNKToNKpiChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNKToNKpiChannel.cc
Member Function Documentation
void G4INCL::NKToNKpiChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 57 of file G4INCLNKToNKpiChannel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNKToNKpiChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), angularSlope, G4INCL::PhaseSpaceGenerator::generateBiased(), G4INCL::ParticleTable::getIsospin(), G4INCL::ParticleTable::getKaonType(), G4INCL::ParticleTable::getNucleonType(), G4INCL::ParticleTable::getPionType(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4InuclParticleNames::nucleon(), particle1, particle2, G4InuclParticleNames::pion(), G4INCL::PiZero, G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::KinematicsUtils::totalEnergyInCM(), and zero.
G4INCL::NKToNKpiChannel::INCL_DECLARE_ALLOCATION_POOL (NKToNKpiChannel) private
Member Data Documentation
const G4double G4INCL::NKToNKpiChannel::angularSlope = 4. static private
Definition at line 57 of file G4INCLNKToNKpiChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNKToNKpiChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::NKToNKpiChannel::particle1 private
Definition at line 55 of file G4INCLNKToNKpiChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNKToNKpiChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NKToNKpiChannel::particle2 private
Definition at line 55 of file G4INCLNKToNKpiChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNKToNKpiChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNKToNKpiChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNKToNKpiChannel.cc