ECCE @ EIC Software: G4LindhardSorensenIonModel Class Reference
G4LindhardSorensenIonModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4LindhardSorensenIonModel.hh>
Public Member Functions
G4LindhardSorensenIonModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="LindhardSorensen")
virtual ~G4LindhardSorensenIonModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *couple) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) override
virtual G4double GetParticleCharge (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) override
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double &eloss, G4double &, G4double length) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual void StartTracking (G4Track *)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) override
G4double GetChargeSquareRatio () const
void SetChargeSquareRatio (G4double val)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void SetupParameters ()
void SetParticle (const G4ParticleDefinition *p)
G4LindhardSorensenIonModel & operator= (const G4LindhardSorensenIonModel &right)=delete
G4LindhardSorensenIonModel (const G4LindhardSorensenIonModel &)=delete
Private Attributes
const G4ParticleDefinition * particle
G4ParticleDefinition * theElectron
G4EmCorrections * corr
G4ParticleChangeForLoss * fParticleChange
G4NistManager * nist
G4int Zin
G4double mass
G4double tlimit
G4double spin
G4double magMoment2
G4double chargeSquare
G4double charge
G4double ratio
G4double formfact
G4double twoln10
Static Private Attributes
static G4LindhardSorensenData * lsdata = nullptr
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 60 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4LindhardSorensenIonModel.hh
Constructor & Destructor Documentation
G4LindhardSorensenIonModel::G4LindhardSorensenIonModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "LindhardSorensen") explicit
Definition at line 64 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 64 of file G4LindhardSorensenIonModel.cc
References corr, G4Electron::Electron(), G4LossTableManager::EmCorrections(), fParticleChange, G4LossTableManager::Instance(), G4NistManager::Instance(), MeV, nist, G4VEmModel::SetLowEnergyLimit(), SetParticle(), and theElectron.
G4LindhardSorensenIonModel::~G4LindhardSorensenIonModel () virtual
Definition at line 81 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4LindhardSorensenIonModel.cc
G4LindhardSorensenIonModel::G4LindhardSorensenIonModel (const G4LindhardSorensenIonModel &) private delete
Member Function Documentation
G4double G4LindhardSorensenIonModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 195 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 195 of file G4LindhardSorensenIonModel.cc
References ComputeCrossSectionPerElectron().
G4double G4LindhardSorensenIonModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) virtual
Definition at line 162 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 162 of file G4LindhardSorensenIonModel.cc
References chargeSquare, Acts::VectorHelpers::cross(), G4Log(), mass, MaxSecondaryEnergy(), min, spin, tlimit, and source.hepunit::twopi_mc2_rcl2.
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4LindhardSorensenIonModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 221 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 221 of file G4LindhardSorensenIonModel.cc
References G4EmCorrections::BarkasCorrection(), chargeSquare, corr, G4IonisParamMat::DensityCorrection(), source.hepunit::electron_mass_c2, G4Log(), G4InuclParticleNames::gam, G4Material::GetElectronDensity(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), mass, max, MaxSecondaryEnergy(), min, G4EmCorrections::ShellCorrection(), spin, twoln10, source.hepunit::twopi_mc2_rcl2, and x.
void G4LindhardSorensenIonModel::CorrectionsAlongStep (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double & eloss, G4double & , G4double length) override virtual
Reimplemented from G4VEmModel.
Definition at line 271 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 271 of file G4LindhardSorensenIonModel.cc
References G4EmCorrections::BarkasCorrection(), charge, chargeSquare, corr, e, G4InuclParticleNames::gam, G4DynamicParticle::GetDefinition(), G4LindhardSorensenData::GetDeltaL(), G4Material::GetElectronDensity(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4VEmModel::GetModelOfFluctuations(), lsdata, mass, SetParticle(), G4VEmFluctuationModel::SetParticleAndCharge(), source.hepunit::twopi_mc2_rcl2, and Zin.
G4double G4LindhardSorensenIonModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 207 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 207 of file G4LindhardSorensenIonModel.cc
References ComputeCrossSectionPerElectron(), and G4Material::GetElectronDensity().
G4double G4LindhardSorensenIonModel::GetChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 111 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 111 of file G4LindhardSorensenIonModel.cc
References chargeSquare.
G4double G4LindhardSorensenIonModel::GetChargeSquareRatio () const inline protected
Definition at line 173 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4LindhardSorensenIonModel.hh
References chargeSquare.
G4double G4LindhardSorensenIonModel::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 121 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 121 of file G4LindhardSorensenIonModel.cc
References charge.
void G4LindhardSorensenIonModel::Initialise (const G4ParticleDefinition * p, const G4DataVector &) override virtual
Implements G4VEmModel.
Definition at line 86 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 86 of file G4LindhardSorensenIonModel.cc
References fParticleChange, G4VEmModel::GetAngularDistribution(), G4VEmModel::GetParticleChangeForLoss(), G4VEmModel::IsMaster(), lsdata, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), SetParticle(), and G4VEmModel::UseAngularGeneratorFlag().
G4double G4LindhardSorensenIonModel::MaxSecondaryEnergy (const G4ParticleDefinition * pd, G4double kinEnergy) override protected virtual
Reimplemented from G4VEmModel.
Definition at line 428 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 428 of file G4LindhardSorensenIonModel.cc
References source.hepunit::electron_mass_c2, mass, ratio, and SetParticle().
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), and SampleSecondaries().
G4double G4LindhardSorensenIonModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple * couple) override virtual
Reimplemented from G4VEmModel.
Definition at line 153 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 153 of file G4LindhardSorensenIonModel.cc
References G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), and G4IonisParamMat::GetMeanExcitationEnergy().
G4LindhardSorensenIonModel& G4LindhardSorensenIonModel::operator= (const G4LindhardSorensenIonModel & right) private delete
void G4LindhardSorensenIonModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 308 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 308 of file G4LindhardSorensenIonModel.cc
References Acts::Test::delta, e, source.hepunit::electron_mass_c2, f, f1, CLHEP::HepRandomEngine::flat(), CLHEP::HepRandomEngine::flatArray(), formfact, fParticleChange, G4cout, G4endl, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4DynamicParticle::GetTotalMomentum(), magMoment2, mass, mat, MaxSecondaryEnergy(), min, phi, CLHEP::Hep3Vector::rotateUz(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SelectRandomAtomNumber(), CLHEP::Hep3Vector::set(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), spin, theElectron, tlimit, twopi, CLHEP::Hep3Vector::unit(), G4VEmModel::UseAngularGeneratorFlag(), x, x1, x2, and Z.
void G4LindhardSorensenIonModel::SetChargeSquareRatio (G4double val) inline protected
Definition at line 180 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4LindhardSorensenIonModel.hh
References chargeSquare.
void G4LindhardSorensenIonModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 163 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4LindhardSorensenIonModel.hh
References particle, and SetupParameters().
Referenced by CorrectionsAlongStep(), G4LindhardSorensenIonModel(), Initialise(), and MaxSecondaryEnergy().
void G4LindhardSorensenIonModel::SetupParameters () private
Definition at line 130 of file G4LindhardSorensenIonModel.cc.
View newest version in sPHENIX GitHub at line 130 of file G4LindhardSorensenIonModel.cc
References source.hepunit::c_squared, charge, chargeSquare, e, source.hepunit::electron_mass_c2, eplus, formfact, G4lrint(), G4NistManager::GetA27(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), GeV, source.hepunit::hbar_Planck, G4VEmModel::inveplus, magMoment2, mass, nist, particle, ratio, spin, tlimit, x, and Zin.
Referenced by SetParticle().
Member Data Documentation
G4double G4LindhardSorensenIonModel::charge private
Definition at line 154 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4LindhardSorensenIonModel.hh
Referenced by CorrectionsAlongStep(), GetParticleCharge(), and SetupParameters().
G4double G4LindhardSorensenIonModel::chargeSquare private
Definition at line 153 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4LindhardSorensenIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), CorrectionsAlongStep(), GetChargeSquareRatio(), SetChargeSquareRatio(), and SetupParameters().
G4EmCorrections* G4LindhardSorensenIonModel::corr private
Definition at line 144 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4LindhardSorensenIonModel.hh
Referenced by ComputeDEDXPerVolume(), CorrectionsAlongStep(), and G4LindhardSorensenIonModel().
G4double G4LindhardSorensenIonModel::formfact private
Definition at line 156 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4LindhardSorensenIonModel.hh
Referenced by SampleSecondaries(), and SetupParameters().
G4ParticleChangeForLoss* G4LindhardSorensenIonModel::fParticleChange private
Definition at line 145 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4LindhardSorensenIonModel.hh
Referenced by G4LindhardSorensenIonModel(), Initialise(), and SampleSecondaries().
G4LindhardSorensenData * G4LindhardSorensenIonModel::lsdata = nullptr static private
Definition at line 140 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 140 of file G4LindhardSorensenIonModel.hh
Referenced by CorrectionsAlongStep(), and Initialise().
G4double G4LindhardSorensenIonModel::magMoment2 private
Definition at line 152 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4LindhardSorensenIonModel.hh
Referenced by SampleSecondaries(), and SetupParameters().
G4double G4LindhardSorensenIonModel::mass private
Definition at line 149 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 149 of file G4LindhardSorensenIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), CorrectionsAlongStep(), MaxSecondaryEnergy(), SampleSecondaries(), and SetupParameters().
G4NistManager* G4LindhardSorensenIonModel::nist private
Definition at line 146 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4LindhardSorensenIonModel.hh
Referenced by G4LindhardSorensenIonModel(), and SetupParameters().
const G4ParticleDefinition* G4LindhardSorensenIonModel::particle private
Definition at line 142 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 142 of file G4LindhardSorensenIonModel.hh
Referenced by SetParticle(), and SetupParameters().
G4double G4LindhardSorensenIonModel::ratio private
Definition at line 155 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4LindhardSorensenIonModel.hh
Referenced by MaxSecondaryEnergy(), and SetupParameters().
G4double G4LindhardSorensenIonModel::spin private
Definition at line 151 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4LindhardSorensenIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), SampleSecondaries(), and SetupParameters().
G4ParticleDefinition* G4LindhardSorensenIonModel::theElectron private
Definition at line 143 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 143 of file G4LindhardSorensenIonModel.hh
Referenced by G4LindhardSorensenIonModel(), and SampleSecondaries().
G4double G4LindhardSorensenIonModel::tlimit private
Definition at line 150 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4LindhardSorensenIonModel.hh
Referenced by ComputeCrossSectionPerElectron(), SampleSecondaries(), and SetupParameters().
G4double G4LindhardSorensenIonModel::twoln10 private
Definition at line 157 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4LindhardSorensenIonModel.hh
Referenced by ComputeDEDXPerVolume().
G4int G4LindhardSorensenIonModel::Zin private
Definition at line 148 of file G4LindhardSorensenIonModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4LindhardSorensenIonModel.hh
Referenced by CorrectionsAlongStep(), and SetupParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4LindhardSorensenIonModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4LindhardSorensenIonModel.cc