ECCE @ EIC Software: CCalAMaterial Class Reference
CCalAMaterial Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalAMaterial.hh>
Public Member Functions
CCalAMaterial (G4String mat, G4double dens, G4int nelem, CCalAMaterial **constituents, G4double *weights)
CCalAMaterial (G4String elemat, G4double Aeff, G4double dens)
CCalAMaterial (const CCalAMaterial &)
virtual ~CCalAMaterial ()
G4double Aeff () const
CCalAMaterial & operator= (const CCalAMaterial &)
Public Member Functions inherited from CCalMaterial
CCalMaterial (G4String mat, G4double dens, G4int nelem, CCalMaterial **constituents, G4double *weights, FractionType=FTWeight)
CCalMaterial (const CCalMaterial &)
virtual ~CCalMaterial ()
G4String Name () const
G4double Density () const
G4int NElements () const
G4String Element (G4int i) const
G4double Weight (G4int i) const
G4bool operator== (const CCalMaterial &) const
G4bool operator!= (const CCalMaterial &) const
CCalMaterial & operator= (const CCalMaterial &)
Protected Member Functions
void computeAeff (G4int nconst, CCalAMaterial **constituents, G4double *weights)
Protected Member Functions inherited from CCalMaterial
CCalMaterial ()
void computeDensity (int nconst, CCalMaterial **constituents, double *weights, FractionType ft)
void closeMaterial ()
Protected Attributes
double aEff
Protected Attributes inherited from CCalMaterial
G4String name
G4double density
G4int nElem
G4String * theElements
G4double * theWeights
Friends
std::ostream & operator<< (std::ostream &, const CCalAMaterial &)
Additional Inherited Members
Public Types inherited from CCalMaterial
enum FractionType { FTWeight, FTVolume }
Detailed Description
Definition at line 38 of file CCalAMaterial.hh.
View newest version in sPHENIX GitHub at line 38 of file CCalAMaterial.hh
Constructor & Destructor Documentation
CCalAMaterial::CCalAMaterial (G4String mat, G4double dens, G4int nelem, CCalAMaterial ** constituents, G4double * weights)
Definition at line 33 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 33 of file CCalAMaterial.cc
References Aeff(), CCalMaterial::closeMaterial(), computeAeff(), CCalMaterial::computeDensity(), CCalMaterial::density, CCalMaterial::Element(), CCalMaterial::FTVolume, mat, CCalMaterial::nElem, CCalMaterial::NElements(), CCalMaterial::theElements, CCalMaterial::theWeights, and CCalMaterial::Weight().
CCalAMaterial::CCalAMaterial (G4String elemat, G4double Aeff, G4double dens)
Definition at line 64 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 64 of file CCalAMaterial.cc
References aEff, CCalMaterial::density, CCalMaterial::nElem, CCalMaterial::theElements, and CCalMaterial::theWeights.
CCalAMaterial::CCalAMaterial (const CCalAMaterial & mat)
Definition at line 81 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 81 of file CCalAMaterial.cc
References CCalMaterial::density, CCalMaterial::name, CCalMaterial::nElem, CCalMaterial::theElements, and CCalMaterial::theWeights.
CCalAMaterial::~CCalAMaterial () virtual
Definition at line 77 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 77 of file CCalAMaterial.cc
Member Function Documentation
G4double CCalAMaterial::Aeff () const inline
Definition at line 52 of file CCalAMaterial.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalAMaterial.hh
References aEff.
Referenced by CCalAMaterial(), and computeAeff().
void CCalAMaterial::computeAeff (G4int nconst, CCalAMaterial ** constituents, G4double * weights) protected
Definition at line 114 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 114 of file CCalAMaterial.cc
References Aeff(), and aEff.
Referenced by CCalAMaterial().
CCalAMaterial & CCalAMaterial::operator= (const CCalAMaterial & mat)
Definition at line 94 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 94 of file CCalAMaterial.cc
References aEff, CCalMaterial::density, CCalMaterial::name, CCalMaterial::nElem, CCalMaterial::theElements, and CCalMaterial::theWeights.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCalAMaterial & mat) friend
Definition at line 122 of file CCalAMaterial.cc.
View newest version in sPHENIX GitHub at line 122 of file CCalAMaterial.cc
Member Data Documentation
double CCalAMaterial::aEff protected
Definition at line 61 of file CCalAMaterial.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalAMaterial.hh
Referenced by Aeff(), CCalAMaterial(), computeAeff(), operator<<(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalAMaterial.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalAMaterial.cc