ECCE @ EIC Software: coresoftware/blob/master/generators/JEWEL/medium-simple.f File Reference
medium-simple.f File Reference
Functions/Subroutines
subroutine medinit (FILE, id, etam, mass)
subroutine mednextevt
double precision function getcentrality ()
subroutine pickvtx (X, Y)
subroutine setb (BVAL)
subroutine getscatterer (X, Y, Z, T, TYPE, PX, PY, PZ, E, MS)
subroutine avscatcen (X, Y, Z, T, PX, PY, PZ, E, m)
subroutine maxscatcen (PX, PY, PZ, E, m)
DOUBLE PRECISION function getmd (X1, Y1, Z1, T1)
DOUBLE PRECISION function getms (X2, Y2, Z2, T2)
DOUBLE PRECISION function getneff (X3, Y3, Z3, T3)
DOUBLE PRECISION function gettemp (X4, Y4, Z4, T4)
DOUBLE PRECISION function gettempmax ()
DOUBLE PRECISION function getmdmax ()
DOUBLE PRECISION function getmdmin ()
DOUBLE PRECISION function getmsmax ()
DOUBLE PRECISION function getnatmdmin ()
DOUBLE PRECISION function getltimemax ()
DOUBLE PRECISION function getneffmax ()
DOUBLE PRECISION function npart (XX1, YY1, XX2, YY2)
DOUBLE PRECISION function nthick (X1, Y1)
subroutine calcta ()
subroutine calcxsection ()
DOUBLE PRECISION function medderiv (XVAL, W)
Function/Subroutine Documentation
subroutine avscatcen (double precision X, double precision Y, double precision Z, double precision T, double precision PX, double precision PY, double precision PZ, double precision E, double precision m)
Definition at line 371 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 371 of file medium-simple.f
References CLHEP::HepLorentzRotation::boost(), common(), e, getms(), Acts::Logger::log(), m, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), t, x, y, and z.
Referenced by getpnorad1(), getqvec(), and getsscat().
subroutine calcta ()
Definition at line 709 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 709 of file medium-simple.f
References a, b, common(), d, e, eps, HiMain1::n0(), odeint(), r, rmax(), and y.
Referenced by medinit().
subroutine calcxsection ()
Definition at line 751 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 751 of file medium-simple.f
References a, b, common(), d, c2_factory< float_type >::exp(), HiMain1::n0(), nthick(), x, and y.
Referenced by medinit().
double precision function getcentrality ()
Definition at line 245 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 245 of file medium-simple.f
References common().
Referenced by getcentrality().
DOUBLE PRECISION function getltimemax ()
Definition at line 605 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 605 of file medium-simple.f
References a, common(), d, gettempmax(), and HiMain1::n0().
Referenced by genevent(), and getltimemax().
DOUBLE PRECISION function getmd (double precision X1, double precision Y1, double precision Z1, double precision T1)
Definition at line 421 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 421 of file medium-simple.f
References common(), gettemp(), max, t1, x1, y1, and z1.
Referenced by doinstatescat(), getdeltat(), getmd(), getms(), getpnorad1(), getqvec(), getscatterer(), and getsscat().
DOUBLE PRECISION function getmdmax ()
Definition at line 535 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 535 of file medium-simple.f
References common(), gettempmax(), and max.
Referenced by getdeltat(), getmdmax(), getmsmax(), getsscat(), and xsecint().
DOUBLE PRECISION function getmdmin ()
Definition at line 547 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 547 of file medium-simple.f
References a, common(), d, max, and HiMain1::n0().
Referenced by getdeltat(), getmdmin(), getnatmdmin(), getsscat(), and xsecint().
DOUBLE PRECISION function getms (double precision X2, double precision Y2, double precision Z2, double precision T2)
Definition at line 433 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 433 of file medium-simple.f
References getmd(), c2_factory< float_type >::sqrt(), t2, x2, y2, and z2.
Referenced by avscatcen(), doinstatescat(), getdeltat(), getms(), getqvec(), getscatterer(), and makebranch().
DOUBLE PRECISION function getmsmax ()
Definition at line 569 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 569 of file medium-simple.f
References getmdmax(), and c2_factory< float_type >::sqrt().
Referenced by getdeltat(), getmsmax(), maxscatcen(), splitfncint(), and xsecint().
DOUBLE PRECISION function getnatmdmin ()
Definition at line 577 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 577 of file medium-simple.f
References a, common(), d, getmdmin(), HiMain1::n0(), pi, and t.
Referenced by getdeltat(), and getnatmdmin().
DOUBLE PRECISION function getneff (double precision X3, double precision Y3, double precision Z3, double precision T3)
Definition at line 441 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 441 of file medium-simple.f
References a, common(), d, gettemp(), HiMain1::n0(), pi, c2_factory< float_type >::sqrt(), G4Abla::tau(), x3, and y3.
Referenced by doinstatescat(), getdeltat(), and getneff().
DOUBLE PRECISION function getneffmax ()
Definition at line 627 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 627 of file medium-simple.f
References a, common(), d, gettempmax(), HiMain1::n0(), and pi.
Referenced by getdeltat(), and getneffmax().
subroutine getscatterer (double precision X, double precision Y, double precision Z, double precision T, integer TYPE, double precision PX, double precision PY, double precision PZ, double precision E, double precision MS)
Definition at line 292 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 292 of file medium-simple.f
References a, CLHEP::HepLorentzRotation::boost(), common(), c2_factory< float_type >::cos(), d, e, e2, c2_factory< float_type >::exp(), getmd(), getms(), gettemp(), Acts::Logger::log(), ms, HiMain1::n0(), phi, pi, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), pyr(), CLHEP::HepLorentzVector::pz(), r, c2_factory< float_type >::sin(), c2_factory< float_type >::sqrt(), t, G4Abla::tau(), theta(), Acts::TrackState< source_link_t, parameters_t >::type(), x, y, and z.
Referenced by getqvec().
DOUBLE PRECISION function gettemp (double precision X4, double precision Y4, double precision Z4, double precision T4)
Definition at line 464 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 464 of file medium-simple.f
References a, common(), d, Acts::Logger::log(), HiMain1::n0(), npart, nthick(), pi, c2_factory< float_type >::sqrt(), G4Abla::tau(), x4, and y4.
Referenced by doinstatescat(), dokinematics(), getmd(), getneff(), getscatterer(), getsscat(), gettemp(), gettempmax(), and makesplitting().
DOUBLE PRECISION function gettempmax ()
Definition at line 516 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 516 of file medium-simple.f
References a, common(), d, gettemp(), and HiMain1::n0().
Referenced by getltimemax(), getmdmax(), getneffmax(), and gettempmax().
subroutine maxscatcen (double precision PX, double precision PY, double precision PZ, double precision E, double precision m)
Definition at line 397 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 397 of file medium-simple.f
References CLHEP::HepLorentzRotation::boost(), common(), e, getmsmax(), m, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), and CLHEP::HepLorentzVector::pz().
Referenced by getsscat(), insudaint(), pdfint(), splitfncint(), and xsecint().
DOUBLE PRECISION function medderiv (double precision XVAL, integer W)
Definition at line 797 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 797 of file medium-simple.f
References a, b, common(), d, c2_factory< float_type >::exp(), HiMain1::n0(), r, c2_factory< float_type >::sqrt(), and w.
Referenced by deriv(), and medderiv().
subroutine medinit (character*80 FILE, integer id, double precision etam, integer mass)
Definition at line 61 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 61 of file medium-simple.f
References a, CLHEP::HepLorentzRotation::boost(), calcta(), calcxsection(), common(), d, file, FW::HepMC3Particle::id(), mass, HiMain1::n0(), pos, rmax(), nlohmann::detail::lexer< BasicJsonType >::scan(), Acts::detail::VoidNavigator::status(), true, and kdfinder::TVector< T >::unit().
Referenced by init().
subroutine mednextevt ()
Definition at line 207 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 207 of file medium-simple.f
References a, common(), d, HiMain1::n0(), pyr(), and r.
Referenced by genevent(), and init().
DOUBLE PRECISION function npart (double precision XX1, double precision YY1, double precision XX2, double precision YY2)
Definition at line 650 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 650 of file medium-simple.f
References a, common(), d, c2_factory< float_type >::exp(), HiMain1::n0(), npart, and nthick().
DOUBLE PRECISION function nthick (double precision X1, double precision Y1)
Definition at line 667 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 667 of file medium-simple.f
References a, b, c, common(), d, int(), Acts::IVisualization::line(), max, min, HiMain1::n0(), r, rmax(), c2_factory< float_type >::sqrt(), x1, and y1.
Referenced by calcxsection(), gettemp(), npart(), and pickvtx().
subroutine pickvtx (double precision X, double precision Y)
Definition at line 255 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 255 of file medium-simple.f
References common(), nthick(), pyr(), c2_factory< float_type >::sqrt(), x, x1, x2, y, y1, y2, and z.
Referenced by genevent().
subroutine setb (double precision BVAL)
Definition at line 280 of file medium-simple.f.
View newest version in sPHENIX GitHub at line 280 of file medium-simple.f
References common().