ECCE @ EIC Software: eIDMLInterface::CaloData Struct Reference
eIDMLInterface::CaloData Struct Reference
Public Member Functions
void initializeVariables ()
Public Attributes
std::vector< float > m_TTree_proj_vec = {0, 0, 0, 0}
std::vector< float > m_TTree_proj_p_vec = {0, 0, 0}
int nTowerInPatch = m_sizeTowerPatch * m_sizeTowerPatch
std::vector< float > m_TTree_Tower_dEta = std::vector<float>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
std::vector< float > m_TTree_Tower_dPhi = std::vector<float>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
std::vector< int > m_TTree_Tower_iEta_patch = std::vector<int>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
std::vector< int > m_TTree_Tower_iPhi_patch = std::vector<int>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
std::vector< float > m_TTree_Tower_E = std::vector<float>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
float m_E3x3 = 0
float m_E5x5 = 0
float m_E7x7 = 0
int m_centralTowerBinEta = 0
int m_centralTowerBinPhi = 0
Static Public Attributes
static const int m_sizeTowerPatch = 7
Detailed Description
Definition at line 79 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 79 of file eIDMLInterface.h
Member Function Documentation
void eIDMLInterface::CaloData::initializeVariables ()
Definition at line 1321 of file eIDMLInterface.cc.
View newest version in sPHENIX GitHub at line 1321 of file eIDMLInterface.cc
References m_centralTowerBinEta, m_centralTowerBinPhi, m_E3x3, m_E5x5, m_E7x7, m_TTree_proj_p_vec, m_TTree_proj_vec, m_TTree_Tower_dEta, m_TTree_Tower_dPhi, m_TTree_Tower_E, m_TTree_Tower_iEta_patch, and m_TTree_Tower_iPhi_patch.
Member Data Documentation
int eIDMLInterface::CaloData::m_centralTowerBinEta = 0
Definition at line 93 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 93 of file eIDMLInterface.h
Referenced by initializeVariables().
int eIDMLInterface::CaloData::m_centralTowerBinPhi = 0
Definition at line 94 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 94 of file eIDMLInterface.h
Referenced by initializeVariables().
float eIDMLInterface::CaloData::m_E3x3 = 0
Definition at line 90 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 90 of file eIDMLInterface.h
Referenced by initializeVariables().
float eIDMLInterface::CaloData::m_E5x5 = 0
Definition at line 91 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 91 of file eIDMLInterface.h
Referenced by initializeVariables().
float eIDMLInterface::CaloData::m_E7x7 = 0
Definition at line 92 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 92 of file eIDMLInterface.h
Referenced by initializeVariables().
const int eIDMLInterface::CaloData::m_sizeTowerPatch = 7 static
Definition at line 83 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 83 of file eIDMLInterface.h
std::vector<float> eIDMLInterface::CaloData::m_TTree_proj_p_vec = {0, 0, 0}
Definition at line 82 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 82 of file eIDMLInterface.h
Referenced by initializeVariables().
std::vector<float> eIDMLInterface::CaloData::m_TTree_proj_vec = {0, 0, 0, 0}
Definition at line 81 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 81 of file eIDMLInterface.h
Referenced by initializeVariables().
std::vector<float> eIDMLInterface::CaloData::m_TTree_Tower_dEta = std::vector<float>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
Definition at line 85 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 85 of file eIDMLInterface.h
Referenced by initializeVariables().
std::vector<float> eIDMLInterface::CaloData::m_TTree_Tower_dPhi = std::vector<float>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
Definition at line 86 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 86 of file eIDMLInterface.h
Referenced by initializeVariables().
std::vector<float> eIDMLInterface::CaloData::m_TTree_Tower_E = std::vector<float>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
Definition at line 89 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 89 of file eIDMLInterface.h
Referenced by initializeVariables().
std::vector<int> eIDMLInterface::CaloData::m_TTree_Tower_iEta_patch = std::vector<int>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
Definition at line 87 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 87 of file eIDMLInterface.h
Referenced by initializeVariables().
std::vector<int> eIDMLInterface::CaloData::m_TTree_Tower_iPhi_patch = std::vector<int>(m_sizeTowerPatch * m_sizeTowerPatch, 0)
Definition at line 88 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 88 of file eIDMLInterface.h
Referenced by initializeVariables().
int eIDMLInterface::CaloData::nTowerInPatch = m_sizeTowerPatch * m_sizeTowerPatch
Definition at line 84 of file eIDMLInterface.h.
View newest version in sPHENIX GitHub at line 84 of file eIDMLInterface.h
The documentation for this struct was generated from the following files:
analysis/blob/master/eIDML/src/eIDMLInterface.h
analysis/blob/master/eIDML/src/eIDMLInterface.cc