ECCE @ EIC Software: G4FTFBinaryPiKBuilder Class Reference
G4FTFBinaryPiKBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBinaryPiKBuilder.hh>
Public Member Functions
G4FTFBinaryPiKBuilder (G4bool quasiElastic=false)
virtual ~G4FTFBinaryPiKBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPiKBuilder
G4VPiKBuilder ()=default
virtual ~G4VPiKBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
Detailed Description
Definition at line 58 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4FTFBinaryPiKBuilder.hh
Constructor & Destructor Documentation
G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder (G4bool quasiElastic = false)
Definition at line 51 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 51 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFBinaryPiKBuilder::~G4FTFBinaryPiKBuilder () virtual
Definition at line 75 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 75 of file G4FTFBinaryPiKBuilder.cc
References theQuasiElastic, and theStringDecay.
Member Function Documentation
virtual void G4FTFBinaryPiKBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 64 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4FTFBinaryPiKBuilder.hh
void G4FTFBinaryPiKBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 82 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 82 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4FTFBinaryPiKBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 90 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 90 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4FTFBinaryPiKBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 98 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 98 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4FTFBinaryPiKBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 105 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 105 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4FTFBinaryPiKBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 112 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 112 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4FTFBinaryPiKBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 119 of file G4FTFBinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 119 of file G4FTFBinaryPiKBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4FTFBinaryPiKBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 72 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4FTFBinaryPiKBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4FTFBinaryPiKBuilder::theCascade private
Definition at line 78 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFBinaryPiKBuilder.hh
Referenced by G4FTFBinaryPiKBuilder().
G4double G4FTFBinaryPiKBuilder::theMin private
Definition at line 82 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4FTFBinaryPiKBuilder.hh
Referenced by Build(), G4FTFBinaryPiKBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFBinaryPiKBuilder::theModel private
Definition at line 77 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FTFBinaryPiKBuilder.hh
Referenced by Build(), and G4FTFBinaryPiKBuilder().
G4QuasiElasticChannel* G4FTFBinaryPiKBuilder::theQuasiElastic private
Definition at line 81 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FTFBinaryPiKBuilder.hh
Referenced by G4FTFBinaryPiKBuilder(), and ~G4FTFBinaryPiKBuilder().
G4ExcitedStringDecay* G4FTFBinaryPiKBuilder::theStringDecay private
Definition at line 80 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FTFBinaryPiKBuilder.hh
Referenced by G4FTFBinaryPiKBuilder(), and ~G4FTFBinaryPiKBuilder().
G4FTFModel* G4FTFBinaryPiKBuilder::theStringModel private
Definition at line 79 of file G4FTFBinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFBinaryPiKBuilder.hh
Referenced by G4FTFBinaryPiKBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBinaryPiKBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFBinaryPiKBuilder.cc