ECCE @ EIC Software: G4LENDElastic Class Reference
G4LENDElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDElastic.hh>
Public Member Functions
G4LENDElastic (G4ParticleDefinition *pd)
~G4LENDElastic ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
Public Member Functions inherited from G4LENDModel
G4LENDModel (G4String name="LENDModel")
~G4LENDModel ()
void ChangeDefaultEvaluation (G4String name)
void AllowNaturalAbundanceTarget ()
void AllowAnyCandidateTarget ()
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpLENDTargetInfo (G4bool force=false)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void InitialiseModel ()
Additional Inherited Members
Protected Member Functions inherited from G4LENDModel
void create_used_target_map ()
void recreate_used_target_map ()
G4GIDI_target * get_target_from_map (G4int nuclear_code)
G4HadFinalState * returnUnchanged (const G4HadProjectile &aTrack, G4HadFinalState *theResult)
Protected Attributes inherited from G4LENDModel
G4ParticleDefinition * proj
G4LENDManager * lend_manager
std::map< G4int,
G4LENDUsedTarget * > usedTarget_map
Detailed Description
Definition at line 44 of file G4LENDElastic.hh.
View newest version in sPHENIX GitHub at line 44 of file G4LENDElastic.hh
Constructor & Destructor Documentation
G4LENDElastic::G4LENDElastic (G4ParticleDefinition * pd) inline
Definition at line 49 of file G4LENDElastic.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LENDElastic.hh
References G4LENDModel::create_used_target_map(), and G4LENDModel::proj.
G4LENDElastic::~G4LENDElastic () inline
Definition at line 59 of file G4LENDElastic.hh.
View newest version in sPHENIX GitHub at line 59 of file G4LENDElastic.hh
Member Function Documentation
G4HadFinalState * G4LENDElastic::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Reimplemented from G4LENDModel.
Definition at line 37 of file G4LENDElastic.cc.
View newest version in sPHENIX GitHub at line 37 of file G4LENDElastic.cc
References G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), G4UniformRand, G4HadProjectile::Get4Momentum(), G4LENDModel::get_target_from_map(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4GIDI_target::getElasticFinalState(), G4LENDManager::GetExcitationEnergyOfExcitedIsomer(), G4Pow::GetInstance(), G4LENDManager::GetInstance(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4Nucleus::GetIsotope(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4Isotope::Getm(), G4ReactionProduct::GetMass(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4LENDManager::GetNucleusEncoding(), G4ParticleDefinition::GetPDGMass(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), source.hepunit::k_Boltzmann, G4LENDModel::lend_manager, G4ReactionProduct::Lorentz(), mass, MeV, MyRNG(), CLHEP::Hep3Vector::phi(), phi, G4Pow::powA(), G4LENDModel::returnUnchanged(), G4DynamicParticle::SetDefinition(), G4HadFinalState::SetEnergyChange(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetMomentumChange(), G4ReactionProduct::SetTotalEnergy(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4INCL::DeJongSpin::shoot(), G4HadronicInteraction::theParticleChange, CLHEP::Hep3Vector::theta(), theta(), theTarget, tP, twopi, v, and CLHEP::HepLorentzVector::vect().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDElastic.cc