ECCE @ EIC Software: G4INCL::NKbToS2piChannel Class Reference
G4INCL::NKbToS2piChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNKbToS2piChannel.hh>
Public Member Functions
NKbToS2piChannel (Particle *, Particle *)
virtual ~NKbToS2piChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (NKbToS2piChannel)
Private Attributes
Particle * particle1
Particle * particle2
Static Private Attributes
static const G4double angularSlope = 4.
Detailed Description
Definition at line 47 of file G4INCLNKbToS2piChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNKbToS2piChannel.hh
Constructor & Destructor Documentation
G4INCL::NKbToS2piChannel::NKbToS2piChannel (Particle * p1, Particle * p2)
Definition at line 51 of file G4INCLNKbToS2piChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLNKbToS2piChannel.cc
G4INCL::NKbToS2piChannel::~NKbToS2piChannel () virtual
Definition at line 55 of file G4INCLNKbToS2piChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNKbToS2piChannel.cc
Member Function Documentation
void G4INCL::NKbToS2piChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 57 of file G4INCLNKbToS2piChannel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNKbToS2piChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), angularSlope, G4INCL::PhaseSpaceGenerator::generateBiased(), G4INCL::ParticleTable::getIsospin(), G4INCL::ParticleTable::getPionType(), G4INCL::Particle::getPosition(), G4INCL::ParticleTable::getSigmaType(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4InuclParticleNames::nucleon(), particle1, particle2, G4InuclParticleNames::pion(), G4INCL::PiZero, G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::SigmaZero, G4INCL::KinematicsUtils::totalEnergyInCM(), and zero.
G4INCL::NKbToS2piChannel::INCL_DECLARE_ALLOCATION_POOL (NKbToS2piChannel) private
Member Data Documentation
const G4double G4INCL::NKbToS2piChannel::angularSlope = 4. static private
Definition at line 57 of file G4INCLNKbToS2piChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNKbToS2piChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::NKbToS2piChannel::particle1 private
Definition at line 55 of file G4INCLNKbToS2piChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNKbToS2piChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NKbToS2piChannel::particle2 private
Definition at line 55 of file G4INCLNKbToS2piChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNKbToS2piChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNKbToS2piChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNKbToS2piChannel.cc