ECCE @ EIC Software: EmAcceptance Class Reference
EmAcceptance Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/EmAcceptance.hh>
Public Member Functions
EmAcceptance ()
~EmAcceptance ()
void BeginOfAcceptance (const G4String &title, G4int stat)
void EndOfAcceptance ()
void EmAcceptanceGauss (const G4String &title, G4int stat, G4double avr, G4double avr0, G4double rms, G4double limit)
EmAcceptance ()
~EmAcceptance ()
void BeginOfAcceptance (const G4String &title, G4int stat)
void EndOfAcceptance ()
void EmAcceptanceGauss (const G4String &title, G4int stat, G4double avr, G4double avr0, G4double rms, G4double limit)
EmAcceptance ()
~EmAcceptance ()
void BeginOfAcceptance (const G4String &title, G4int stat)
void EndOfAcceptance ()
void EmAcceptanceGauss (const G4String &title, G4int stat, G4double avr, G4double avr0, G4double rms, G4double limit)
Private Member Functions
EmAcceptance & operator= (const EmAcceptance &right)
EmAcceptance (const EmAcceptance &)
Private Attributes
G4bool fIsAccepted
Detailed Description
Definition at line 40 of file EmAcceptance.hh.
View newest version in sPHENIX GitHub at line 40 of file EmAcceptance.hh
Constructor & Destructor Documentation
EmAcceptance::EmAcceptance ()
Definition at line 37 of file EmAcceptance.cc.
View newest version in sPHENIX GitHub at line 37 of file EmAcceptance.cc
EmAcceptance::~EmAcceptance ()
Definition at line 43 of file EmAcceptance.cc.
View newest version in sPHENIX GitHub at line 43 of file EmAcceptance.cc
EmAcceptance::EmAcceptance ()
EmAcceptance::~EmAcceptance ()
EmAcceptance::EmAcceptance ()
EmAcceptance::~EmAcceptance ()
EmAcceptance::EmAcceptance (const EmAcceptance &) private
Member Function Documentation
void EmAcceptance::BeginOfAcceptance (const G4String & title, G4int stat)
Definition at line 48 of file EmAcceptance.cc.
View newest version in sPHENIX GitHub at line 48 of file EmAcceptance.cc
References fIsAccepted, G4cout, and G4endl.
Referenced by Run::EndOfRun(), and HistoManager::EndOfRun().
void EmAcceptance::BeginOfAcceptance (const G4String & title, G4int stat)
void EmAcceptance::BeginOfAcceptance (const G4String & title, G4int stat)
void EmAcceptance::EmAcceptanceGauss (const G4String & title, G4int stat, G4double avr, G4double avr0, G4double rms, G4double limit)
Definition at line 67 of file EmAcceptance.cc.
View newest version in sPHENIX GitHub at line 67 of file EmAcceptance.cc
References fIsAccepted, G4cout, G4endl, and x.
Referenced by Run::EndOfRun(), and HistoManager::EndOfRun().
void EmAcceptance::EmAcceptanceGauss (const G4String & title, G4int stat, G4double avr, G4double avr0, G4double rms, G4double limit)
void EmAcceptance::EmAcceptanceGauss (const G4String & title, G4int stat, G4double avr, G4double avr0, G4double rms, G4double limit)
void EmAcceptance::EndOfAcceptance ()
Definition at line 57 of file EmAcceptance.cc.
View newest version in sPHENIX GitHub at line 57 of file EmAcceptance.cc
References fIsAccepted, G4cout, and G4endl.
Referenced by Run::EndOfRun(), and HistoManager::EndOfRun().
void EmAcceptance::EndOfAcceptance ()
void EmAcceptance::EndOfAcceptance ()
EmAcceptance& EmAcceptance::operator= (const EmAcceptance & right) private
Member Data Documentation
G4bool EmAcceptance::fIsAccepted private
Definition at line 54 of file EmAcceptance.hh.
View newest version in sPHENIX GitHub at line 54 of file EmAcceptance.hh
Referenced by BeginOfAcceptance(), EmAcceptanceGauss(), and EndOfAcceptance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/EmAcceptance.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/EmAcceptance.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/EmAcceptance.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/EmAcceptance.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/EmAcceptance.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/EmAcceptance.cc