ECCE @ EIC Software: G4RichTrajectoryPoint Class Reference
G4RichTrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4RichTrajectoryPoint.hh>
Public Member Functions
G4RichTrajectoryPoint ()
G4RichTrajectoryPoint (const G4Track *)
G4RichTrajectoryPoint (const G4Step *)
G4RichTrajectoryPoint (const G4RichTrajectoryPoint &right)
virtual ~G4RichTrajectoryPoint ()
const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
void * operator new (size_t)
void operator delete (void *aRichTrajectoryPoint)
G4bool operator== (const G4RichTrajectoryPoint &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4TrajectoryPoint
G4TrajectoryPoint ()
G4TrajectoryPoint (G4ThreeVector pos)
G4TrajectoryPoint (const G4TrajectoryPoint &right)
virtual ~G4TrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const G4TrajectoryPoint &right) const
const G4ThreeVector GetPosition () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
Private Member Functions
G4RichTrajectoryPoint & operator= (const G4RichTrajectoryPoint &)
Private Attributes
std::vector< G4ThreeVector > * fpAuxiliaryPointVector
G4double fTotEDep
G4double fRemainingEnergy
const G4VProcess * fpProcess
G4StepStatus fPreStepPointStatus
G4StepStatus fPostStepPointStatus
G4double fPreStepPointGlobalTime
G4double fPostStepPointGlobalTime
G4TouchableHandle fpPreStepPointVolume
G4TouchableHandle fpPostStepPointVolume
G4double fPreStepPointWeight
G4double fPostStepPointWeight
Detailed Description
Definition at line 71 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RichTrajectoryPoint.hh
Constructor & Destructor Documentation
G4RichTrajectoryPoint::G4RichTrajectoryPoint ()
Definition at line 69 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 69 of file G4RichTrajectoryPoint.cc
G4RichTrajectoryPoint::G4RichTrajectoryPoint (const G4Track * aTrack)
Definition at line 82 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 82 of file G4RichTrajectoryPoint.cc
G4RichTrajectoryPoint::G4RichTrajectoryPoint (const G4Step * aStep)
Definition at line 98 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 98 of file G4RichTrajectoryPoint.cc
References fPostStepPointGlobalTime, fPostStepPointStatus, fPostStepPointWeight, fpPostStepPointVolume, fpPreStepPointVolume, fpProcess, fPreStepPointGlobalTime, fPreStepPointStatus, fPreStepPointWeight, fRemainingEnergy, fTotEDep, G4Track::GetCurrentStepNumber(), G4StepPoint::GetGlobalTime(), G4StepPoint::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4StepPoint::GetStepStatus(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), and G4StepPoint::GetWeight().
G4RichTrajectoryPoint::G4RichTrajectoryPoint (const G4RichTrajectoryPoint & right)
Definition at line 122 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 122 of file G4RichTrajectoryPoint.cc
G4RichTrajectoryPoint::~G4RichTrajectoryPoint () virtual
Definition at line 138 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 138 of file G4RichTrajectoryPoint.cc
References fpAuxiliaryPointVector.
Member Function Documentation
std::vector< G4AttValue > * G4RichTrajectoryPoint::CreateAttValues () const virtual
Reimplemented from G4TrajectoryPoint.
Definition at line 235 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 235 of file G4RichTrajectoryPoint.cc
References G4TrajectoryPoint::CreateAttValues(), fpAuxiliaryPointVector, fPostStepPointGlobalTime, fPostStepPointStatus, fPostStepPointWeight, fpPostStepPointVolume, fpPreStepPointVolume, fpProcess, fPreStepPointGlobalTime, fPreStepPointStatus, fPreStepPointWeight, fRemainingEnergy, fTotEDep, G4BestUnit, G4cout, GetAttDefs(), G4VProcess::GetProcessName(), G4VProcess::GetProcessType(), G4VProcess::GetProcessTypeName(), G4VTouchable::GetVolume(), Path(), Status(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * G4RichTrajectoryPoint::GetAttDefs () const virtual
Reimplemented from G4TrajectoryPoint.
Definition at line 151 of file G4RichTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 151 of file G4RichTrajectoryPoint.cc
References G4TrajectoryPoint::GetAttDefs(), and G4AttDefStore::GetInstance().
Referenced by CreateAttValues(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
const std::vector<G4ThreeVector>* G4RichTrajectoryPoint::GetAuxiliaryPoints () const inline virtual
Reimplemented from G4VTrajectoryPoint.
Definition at line 89 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RichTrajectoryPoint.hh
References fpAuxiliaryPointVector.
void G4RichTrajectoryPoint::operator delete (void * aRichTrajectoryPoint) inline
Definition at line 128 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 128 of file G4RichTrajectoryPoint.hh
References aRichTrajectoryPointAllocator().
void * G4RichTrajectoryPoint::operator new (size_t) inline
Definition at line 121 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 121 of file G4RichTrajectoryPoint.hh
References aRichTrajectoryPointAllocator().
G4RichTrajectoryPoint& G4RichTrajectoryPoint::operator= (const G4RichTrajectoryPoint &) private
G4bool G4RichTrajectoryPoint::operator== (const G4RichTrajectoryPoint & right) const inline
Definition at line 95 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RichTrajectoryPoint.hh
Member Data Documentation
std::vector<G4ThreeVector>* G4RichTrajectoryPoint::fpAuxiliaryPointVector private
Definition at line 105 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 105 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), GetAuxiliaryPoints(), and ~G4RichTrajectoryPoint().
G4double G4RichTrajectoryPoint::fPostStepPointGlobalTime private
Definition at line 112 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 112 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4StepStatus G4RichTrajectoryPoint::fPostStepPointStatus private
Definition at line 110 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4double G4RichTrajectoryPoint::fPostStepPointWeight private
Definition at line 116 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 116 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4TouchableHandle G4RichTrajectoryPoint::fpPostStepPointVolume private
Definition at line 114 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4TouchableHandle G4RichTrajectoryPoint::fpPreStepPointVolume private
Definition at line 113 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 113 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
const G4VProcess* G4RichTrajectoryPoint::fpProcess private
Definition at line 108 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 108 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4double G4RichTrajectoryPoint::fPreStepPointGlobalTime private
Definition at line 111 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4StepStatus G4RichTrajectoryPoint::fPreStepPointStatus private
Definition at line 109 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 109 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4double G4RichTrajectoryPoint::fPreStepPointWeight private
Definition at line 115 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 115 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4double G4RichTrajectoryPoint::fRemainingEnergy private
Definition at line 107 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 107 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
G4double G4RichTrajectoryPoint::fTotEDep private
Definition at line 106 of file G4RichTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 106 of file G4RichTrajectoryPoint.hh
Referenced by CreateAttValues(), and G4RichTrajectoryPoint().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4RichTrajectoryPoint.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4RichTrajectoryPoint.cc