ECCE @ EIC Software: G4CascadParticle Class Reference
G4CascadParticle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadParticle.hh>
Public Member Functions
G4CascadParticle ()
G4CascadParticle (const G4InuclElementaryParticle &particle, const G4ThreeVector &pos, G4int izone, G4double cpath, G4int gen)
~G4CascadParticle ()
G4CascadParticle (const G4CascadParticle &cpart)
G4CascadParticle & operator= (const G4CascadParticle &cpart)
void fill (const G4InuclElementaryParticle &particle, const G4ThreeVector &pos, G4int izone, G4double cpath, G4int gen)
const G4InuclElementaryParticle & getParticle () const
G4InuclElementaryParticle & getParticle ()
G4int getGeneration () const
void setGeneration (G4int gen)
G4int getHistoryId () const
void setHistoryId (G4int id)
G4LorentzVector getMomentum () const
void updateParticleMomentum (const G4LorentzVector &mom)
const G4ThreeVector & getPosition () const
void updatePosition (const G4ThreeVector &pos)
void incrementReflectionCounter ()
G4int getNumberOfReflections () const
void resetReflection ()
G4bool reflectedNow () const
void initializePath (G4double npath)
void incrementCurrentPath (G4double npath)
G4double getCurrentPath () const
void updateZone (G4int izone)
G4int getCurrentZone () const
void setMovingInsideNuclei (G4bool isMovingIn=true)
G4bool movingInsideNuclei () const
G4double getPathToTheNextZone (G4double rz_in, G4double rz_out)
void propagateAlongThePath (G4double path)
G4bool young (G4double young_path_cut, G4double cpath) const
void print (std::ostream &os) const
Private Attributes
G4int verboseLevel
G4InuclElementaryParticle theParticle
G4ThreeVector position
G4int current_zone
G4double current_path
G4bool movingIn
G4int reflectionCounter
G4bool reflected
G4int generation
G4int historyId
Detailed Description
Definition at line 49 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 49 of file G4CascadParticle.hh
Constructor & Destructor Documentation
G4CascadParticle::G4CascadParticle ()
Definition at line 46 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 46 of file G4CascadParticle.cc
References G4cout, G4endl, and verboseLevel.
G4CascadParticle::G4CascadParticle (const G4InuclElementaryParticle & particle, const G4ThreeVector & pos, G4int izone, G4double cpath, G4int gen)
Definition at line 56 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 56 of file G4CascadParticle.cc
References G4cout, G4endl, G4InuclParticle::getDefinition(), G4ParticleDefinition::GetParticleName(), and verboseLevel.
G4CascadParticle::~G4CascadParticle () inline
Definition at line 59 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 59 of file G4CascadParticle.hh
G4CascadParticle::G4CascadParticle (const G4CascadParticle & cpart) inline
Definition at line 63 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 63 of file G4CascadParticle.hh
Member Function Documentation
void G4CascadParticle::fill (const G4InuclElementaryParticle & particle, const G4ThreeVector & pos, G4int izone, G4double cpath, G4int gen)
Definition at line 91 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 91 of file G4CascadParticle.cc
References current_path, current_zone, G4cout, G4endl, generation, historyId, movingIn, particle, pos(), reflected, reflectionCounter, theParticle, and verboseLevel.
G4double G4CascadParticle::getCurrentPath () const inline
Definition at line 104 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 104 of file G4CascadParticle.hh
References current_path.
G4int G4CascadParticle::getCurrentZone () const inline
Definition at line 107 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 107 of file G4CascadParticle.hh
References current_zone.
Referenced by G4NucleiModel::boundaryTransition(), G4NucleiModel::choosePointAlongTraj(), G4IntraNucleiCascader::decayTrappedParticle(), G4NucleiModel::generateInteractionPartners(), G4NucleiModel::generateParticleFate(), G4NucleiModel::inverseMeanFreePath(), G4CascadeHistory::PrintEntry(), G4NucleiModel::stillInside(), and G4NucleiModel::worthToPropagate().
G4int G4CascadParticle::getGeneration () const inline
Definition at line 76 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CascadParticle.hh
References generation.
Referenced by G4IntraNucleiCascader::decayTrappedParticle(), G4NucleiModel::generateParticleFate(), G4NucleiModel::isProjectile(), and G4CascadeHistory::PrintEntry().
G4int G4CascadParticle::getHistoryId () const inline
Definition at line 79 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CascadParticle.hh
References historyId.
Referenced by G4CascadeHistory::AddEntry(), G4CascadeHistory::AssignHistoryID(), and G4CascadeHistory::DropEntry().
G4LorentzVector G4CascadParticle::getMomentum () const inline
Definition at line 82 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CascadParticle.hh
References G4InuclParticle::getMomentum(), and theParticle.
Referenced by G4NucleiModel::boundaryTransition(), G4NucleiModel::choosePointAlongTraj(), G4NucleiModel::generateInteractionPartners(), getPathToTheNextZone(), G4CascadeHistory::PrintEntry(), and propagateAlongThePath().
G4int G4CascadParticle::getNumberOfReflections () const inline
Definition at line 97 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 97 of file G4CascadParticle.hh
References reflectionCounter.
Referenced by G4IntraNucleiCascader::generateCascade().
const G4InuclElementaryParticle& G4CascadParticle::getParticle () const inline
Definition at line 73 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CascadParticle.hh
References theParticle.
Referenced by G4CollisionOutput::addOutgoingParticle(), G4NucleiModel::boundaryTransition(), G4IntraNucleiCascader::decayTrappedParticle(), G4NucleiModel::forceFirst(), G4IntraNucleiCascader::generateCascade(), G4NucleiModel::generateInteractionPartners(), G4NucleiModel::generateParticleFate(), G4CascadeHistory::GuessTarget(), G4NucleiModel::inverseMeanFreePath(), G4ParticleLargerEkin::operator()(), G4ParticleLargerBeta::operator()(), G4IntraNucleiCascader::particleCanInteract(), G4CascadeHistory::PrintEntry(), G4IntraNucleiCascader::processSecondary(), G4IntraNucleiCascader::processTrappedParticle(), and G4NucleiModel::worthToPropagate().
G4InuclElementaryParticle& G4CascadParticle::getParticle () inline
Definition at line 74 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CascadParticle.hh
References theParticle.
G4double G4CascadParticle::getPathToTheNextZone (G4double rz_in, G4double rz_out)
Definition at line 108 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 108 of file G4CascadParticle.cc
References kdfinder::abs(), current_zone, d2, CLHEP::Hep3Vector::dot(), e, G4cout, G4endl, getMomentum(), CLHEP::Hep3Vector::mag2(), mom, movingIn, G4InuclParticleNames::pp, CLHEP::HepLorentzVector::vect(), and verboseLevel.
Referenced by G4NucleiModel::generateInteractionPartners().
const G4ThreeVector& G4CascadParticle::getPosition () const inline
Definition at line 90 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 90 of file G4CascadParticle.hh
References position.
Referenced by G4NucleiModel::boundaryTransition(), G4NucleiModel::choosePointAlongTraj(), G4IntraNucleiCascader::decayTrappedParticle(), G4NucleiModel::generateParticleFate(), and G4CascadeHistory::PrintEntry().
void G4CascadParticle::incrementCurrentPath (G4double npath) inline
Definition at line 103 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 103 of file G4CascadParticle.hh
References current_path.
Referenced by G4NucleiModel::generateParticleFate().
void G4CascadParticle::incrementReflectionCounter () inline
Definition at line 93 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 93 of file G4CascadParticle.hh
References reflected, and reflectionCounter.
Referenced by G4NucleiModel::boundaryTransition().
void G4CascadParticle::initializePath (G4double npath) inline
Definition at line 102 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 102 of file G4CascadParticle.hh
References current_path.
Referenced by G4IntraNucleiCascader::processSecondary().
G4bool G4CascadParticle::movingInsideNuclei () const inline
Definition at line 110 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 110 of file G4CascadParticle.hh
References movingIn.
Referenced by G4NucleiModel::boundaryTransition().
G4CascadParticle & G4CascadParticle::operator= (const G4CascadParticle & cpart)
Definition at line 72 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 72 of file G4CascadParticle.cc
References current_path, current_zone, generation, historyId, movingIn, position, reflected, reflectionCounter, theParticle, and verboseLevel.
void G4CascadParticle::print (std::ostream & os) const
Definition at line 186 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 186 of file G4CascadParticle.cc
References current_path, current_zone, G4endl, reflectionCounter, and theParticle.
Referenced by operator<<().
void G4CascadParticle::propagateAlongThePath (G4double path)
Definition at line 170 of file G4CascadParticle.cc.
View newest version in sPHENIX GitHub at line 170 of file G4CascadParticle.cc
References G4cout, G4endl, getMomentum(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and verboseLevel.
Referenced by G4NucleiModel::generateParticleFate().
G4bool G4CascadParticle::reflectedNow () const inline
Definition at line 100 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 100 of file G4CascadParticle.hh
References reflected.
Referenced by G4NucleiModel::worthToPropagate().
void G4CascadParticle::resetReflection () inline
Definition at line 99 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 99 of file G4CascadParticle.hh
References reflected.
Referenced by G4NucleiModel::boundaryTransition().
void G4CascadParticle::setGeneration (G4int gen) inline
Definition at line 77 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CascadParticle.hh
References generation.
Referenced by G4IntraNucleiCascader::processSecondary().
void G4CascadParticle::setHistoryId (G4int id) inline
Definition at line 80 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 80 of file G4CascadParticle.hh
References historyId.
Referenced by G4CascadeHistory::AssignHistoryID().
void G4CascadParticle::setMovingInsideNuclei (G4bool isMovingIn = true) inline
Definition at line 109 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 109 of file G4CascadParticle.hh
References movingIn.
Referenced by G4IntraNucleiCascader::processSecondary().
void G4CascadParticle::updateParticleMomentum (const G4LorentzVector & mom) inline
Definition at line 86 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 86 of file G4CascadParticle.hh
References G4InuclParticle::setMomentum(), and theParticle.
Referenced by G4NucleiModel::boundaryTransition().
void G4CascadParticle::updatePosition (const G4ThreeVector & pos) inline
Definition at line 91 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 91 of file G4CascadParticle.hh
References pos().
Referenced by G4NucleiModel::choosePointAlongTraj(), G4NucleiModel::generateParticleFate(), and G4IntraNucleiCascader::processSecondary().
void G4CascadParticle::updateZone (G4int izone) inline
Definition at line 106 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 106 of file G4CascadParticle.hh
References current_zone.
Referenced by G4NucleiModel::boundaryTransition(), G4NucleiModel::choosePointAlongTraj(), and G4IntraNucleiCascader::processSecondary().
G4bool G4CascadParticle::young (G4double young_path_cut, G4double cpath) const inline
Definition at line 115 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 115 of file G4CascadParticle.hh
References current_path.
Referenced by G4NucleiModel::generateInteractionLength().
Member Data Documentation
G4double G4CascadParticle::current_path private
Definition at line 126 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CascadParticle.hh
Referenced by fill(), getCurrentPath(), incrementCurrentPath(), initializePath(), operator=(), print(), and young().
G4int G4CascadParticle::current_zone private
Definition at line 125 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 125 of file G4CascadParticle.hh
Referenced by fill(), getCurrentZone(), getPathToTheNextZone(), operator=(), print(), and updateZone().
G4int G4CascadParticle::generation private
Definition at line 130 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 130 of file G4CascadParticle.hh
Referenced by fill(), getGeneration(), operator=(), and setGeneration().
G4int G4CascadParticle::historyId private
Definition at line 131 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 131 of file G4CascadParticle.hh
Referenced by fill(), getHistoryId(), operator=(), and setHistoryId().
G4bool G4CascadParticle::movingIn private
Definition at line 127 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 127 of file G4CascadParticle.hh
Referenced by fill(), getPathToTheNextZone(), movingInsideNuclei(), operator=(), and setMovingInsideNuclei().
G4ThreeVector G4CascadParticle::position private
Definition at line 124 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 124 of file G4CascadParticle.hh
Referenced by getPosition(), and operator=().
G4bool G4CascadParticle::reflected private
Definition at line 129 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 129 of file G4CascadParticle.hh
Referenced by fill(), incrementReflectionCounter(), operator=(), reflectedNow(), and resetReflection().
G4int G4CascadParticle::reflectionCounter private
Definition at line 128 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 128 of file G4CascadParticle.hh
Referenced by fill(), getNumberOfReflections(), incrementReflectionCounter(), operator=(), and print().
G4InuclElementaryParticle G4CascadParticle::theParticle private
Definition at line 123 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 123 of file G4CascadParticle.hh
Referenced by fill(), getMomentum(), getParticle(), operator=(), print(), and updateParticleMomentum().
G4int G4CascadParticle::verboseLevel private
Definition at line 122 of file G4CascadParticle.hh.
View newest version in sPHENIX GitHub at line 122 of file G4CascadParticle.hh
Referenced by fill(), G4CascadParticle(), getPathToTheNextZone(), operator=(), and propagateAlongThePath().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadParticle.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadParticle.cc