ECCE @ EIC Software: pyG4TwistedTubs Namespace Reference
pyG4TwistedTubs Namespace Reference
Functions
G4TwistedTubs * f1_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4double dphi)
G4TwistedTubs * f2_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4int nseg, G4double totphi)
G4TwistedTubs * f3_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4double dphi)
G4TwistedTubs * f4_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4int nseg, G4double totphi)
Variables
G4double(G4TwistedTubs::* f1_GetEndInnerRadius)(G4int) const = &G4TwistedTubs::GetEndInnerRadius
G4double(G4TwistedTubs::* f2_GetEndInnerRadius)(G4int) const = &G4TwistedTubs::GetEndInnerRadius
G4double(G4TwistedTubs::* f1_GetEndOuterRadius)(G4int) const = &G4TwistedTubs::GetEndOuterRadius
G4double(G4TwistedTubs::* f2_GetEndOuterRadius)() const = &G4TwistedTubs::GetEndOuterRadius
Function Documentation
G4TwistedTubs* pyG4TwistedTubs::f1_CreateTwistedTubs (const G4String & name, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4double dphi)
Definition at line 56 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 56 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
G4TwistedTubs* pyG4TwistedTubs::f2_CreateTwistedTubs (const G4String & name, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4int nseg, G4double totphi)
Definition at line 67 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 67 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
G4TwistedTubs* pyG4TwistedTubs::f3_CreateTwistedTubs (const G4String & name, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4double dphi)
Definition at line 79 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 79 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
G4TwistedTubs* pyG4TwistedTubs::f4_CreateTwistedTubs (const G4String & name, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4int nseg, G4double totphi)
Definition at line 91 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 91 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
Variable Documentation
G4double(G4TwistedTubs::* pyG4TwistedTubs::f1_GetEndInnerRadius)(G4int) const = &G4TwistedTubs::GetEndInnerRadius
Definition at line 43 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 43 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
G4double(G4TwistedTubs::* pyG4TwistedTubs::f1_GetEndOuterRadius)(G4int) const = &G4TwistedTubs::GetEndOuterRadius
Definition at line 49 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 49 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
G4double(G4TwistedTubs::* pyG4TwistedTubs::f2_GetEndInnerRadius)(G4int) const = &G4TwistedTubs::GetEndInnerRadius
Definition at line 45 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 45 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().
G4double(G4TwistedTubs::* pyG4TwistedTubs::f2_GetEndOuterRadius)() const = &G4TwistedTubs::GetEndOuterRadius
Definition at line 51 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 51 of file pyG4TwistedTubs.cc
Referenced by export_G4TwistedTubs().