ECCE @ EIC Software: G4VIntraNuclearTransportModel Class Reference
G4VIntraNuclearTransportModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VIntraNuclearTransportModel.hh>
Public Member Functions
G4VIntraNuclearTransportModel (const G4String &mName="CascadeModel", G4VPreCompoundModel *ptr=nullptr)
virtual ~G4VIntraNuclearTransportModel ()
virtual G4ReactionProductVector * Propagate (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus)=0
virtual G4ReactionProductVector * PropagateNuclNucl (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus, G4V3DNucleus *theProjectileNucleus)
void SetDeExcitation (G4VPreCompoundModel *ptr)
void Set3DNucleus (G4V3DNucleus *const value)
void SetPrimaryProjectile (const G4HadProjectile &aPrimary)
const G4String & GetModelName () const
virtual void ModelDescription (std::ostream &outFile) const
virtual void PropagateModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)=0
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Member Functions
G4V3DNucleus * Get3DNucleus () const
G4VPreCompoundModel * GetDeExcitation () const
const G4HadProjectile * GetPrimaryProjectile () const
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes
G4String theTransportModelName
G4V3DNucleus * the3DNucleus
G4VPreCompoundModel * theDeExcitation
const G4HadProjectile * thePrimaryProjectile
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Private Member Functions
G4VIntraNuclearTransportModel (const G4VIntraNuclearTransportModel &right)=delete
const
G4VIntraNuclearTransportModel & operator= (const G4VIntraNuclearTransportModel &right)=delete
G4bool operator== (const G4VIntraNuclearTransportModel &right) const =delete
G4bool operator!= (const G4VIntraNuclearTransportModel &right) const =delete
Detailed Description
Definition at line 63 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VIntraNuclearTransportModel.hh
Constructor & Destructor Documentation
G4VIntraNuclearTransportModel::G4VIntraNuclearTransportModel (const G4String & mName = "CascadeModel", G4VPreCompoundModel * ptr = nullptr) explicit
Definition at line 41 of file G4VIntraNuclearTransportModel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VIntraNuclearTransportModel.cc
G4VIntraNuclearTransportModel::~G4VIntraNuclearTransportModel () virtual
Definition at line 47 of file G4VIntraNuclearTransportModel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VIntraNuclearTransportModel.cc
G4VIntraNuclearTransportModel::G4VIntraNuclearTransportModel (const G4VIntraNuclearTransportModel & right) private delete
Member Function Documentation
G4V3DNucleus * G4VIntraNuclearTransportModel::Get3DNucleus () const inline protected
Definition at line 121 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4VIntraNuclearTransportModel.hh
References the3DNucleus.
G4VPreCompoundModel * G4VIntraNuclearTransportModel::GetDeExcitation () const inline protected
Definition at line 131 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4VIntraNuclearTransportModel.hh
References theDeExcitation.
Referenced by G4BinaryCascade::G4BinaryCascade().
const G4String & G4VIntraNuclearTransportModel::GetModelName () const inline
Definition at line 116 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VIntraNuclearTransportModel.hh
References theTransportModelName.
const G4HadProjectile * G4VIntraNuclearTransportModel::GetPrimaryProjectile () const inline protected
Definition at line 144 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4VIntraNuclearTransportModel.hh
References thePrimaryProjectile.
Referenced by G4BinaryCascade::BuildLateParticleCollisions(), G4GeneratorPrecompoundInterface::Propagate(), G4CascadeInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
void G4VIntraNuclearTransportModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4INCLXXInterface, G4CascadeInterface, and G4BinaryCascade.
Definition at line 54 of file G4VIntraNuclearTransportModel.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VIntraNuclearTransportModel.cc
References FatalException, G4endl, and G4Exception().
G4bool G4VIntraNuclearTransportModel::operator!= (const G4VIntraNuclearTransportModel & right) const private delete
const G4VIntraNuclearTransportModel& G4VIntraNuclearTransportModel::operator= (const G4VIntraNuclearTransportModel & right) private delete
G4bool G4VIntraNuclearTransportModel::operator== (const G4VIntraNuclearTransportModel & right) const private delete
virtual G4ReactionProductVector* G4VIntraNuclearTransportModel::Propagate (G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus) pure virtual
Implemented in G4INCLXXInterface, G4CascadeInterface, G4UrQMD1_3Model, G4BinaryCascade, G4HIJING_Model, and G4GeneratorPrecompoundInterface.
Referenced by G4TheoFSGenerator::ApplyYourself().
void G4VIntraNuclearTransportModel::PropagateModelDescription (std::ostream & outFile) const virtual
Reimplemented in G4BinaryCascade, and G4GeneratorPrecompoundInterface.
Definition at line 61 of file G4VIntraNuclearTransportModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VIntraNuclearTransportModel.cc
References G4endl.
Referenced by G4TheoFSGenerator::ModelDescription().
G4ReactionProductVector * G4VIntraNuclearTransportModel::PropagateNuclNucl (G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus, G4V3DNucleus * theProjectileNucleus) virtual
Reimplemented in G4GeneratorPrecompoundInterface.
Definition at line 68 of file G4VIntraNuclearTransportModel.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VIntraNuclearTransportModel.cc
References FatalException, and G4Exception().
Referenced by G4TheoFSGenerator::ApplyYourself().
void G4VIntraNuclearTransportModel::Set3DNucleus (G4V3DNucleus *const value) inline
Definition at line 126 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4VIntraNuclearTransportModel.hh
References the3DNucleus.
void G4VIntraNuclearTransportModel::SetDeExcitation (G4VPreCompoundModel * ptr) inline
Definition at line 137 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 137 of file G4VIntraNuclearTransportModel.hh
References theDeExcitation.
Referenced by G4QGSBuilder::BuildModel(), B03PhysicsList::ConstructHad(), G4BinaryCascade::G4BinaryCascade(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4NeutrinoNucleusModel::G4NeutrinoNucleusModel(), and G4INCLXXInterfaceStore::UseAblaDeExcitation().
void G4VIntraNuclearTransportModel::SetPrimaryProjectile (const G4HadProjectile & aPrimary) inline
Definition at line 150 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4VIntraNuclearTransportModel.hh
References thePrimaryProjectile.
Referenced by G4TheoFSGenerator::ApplyYourself().
Member Data Documentation
G4V3DNucleus* G4VIntraNuclearTransportModel::the3DNucleus protected
Definition at line 109 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VIntraNuclearTransportModel.hh
Referenced by G4BinaryCascade::ApplyYourself(), G4BinaryCascade::BuildTargetList(), G4BinaryCascade::CheckChargeAndBaryonNumber(), G4BinaryCascade::CheckPauliPrinciple(), G4BinaryCascade::FindFragments(), Get3DNucleus(), G4BinaryCascade::GetExcitationEnergy(), G4BinaryCascade::Propagate(), and Set3DNucleus().
G4VPreCompoundModel* G4VIntraNuclearTransportModel::theDeExcitation protected
Definition at line 111 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VIntraNuclearTransportModel.hh
Referenced by G4BinaryCascade::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4BinaryCascade::DeExcite(), G4INCLXXInterface::G4INCLXXInterface(), GetDeExcitation(), G4INCLXXInterface::GetDeExcitationModelName(), G4BinaryCascade::ModelDescription(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::PropagateModelDescription(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), and SetDeExcitation().
const G4HadProjectile* G4VIntraNuclearTransportModel::thePrimaryProjectile protected
Definition at line 113 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VIntraNuclearTransportModel.hh
Referenced by GetPrimaryProjectile(), and SetPrimaryProjectile().
G4String G4VIntraNuclearTransportModel::theTransportModelName protected
Definition at line 107 of file G4VIntraNuclearTransportModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VIntraNuclearTransportModel.hh
Referenced by GetModelName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4VIntraNuclearTransportModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4VIntraNuclearTransportModel.cc