ECCE @ EIC Software: CexmcParticleGun Class Reference
CexmcParticleGun Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcParticleGun.hh>
Public Member Functions
CexmcParticleGun (CexmcPhysicsManager *physicsManager, G4int nmbOfParticles=1)
~CexmcParticleGun ()
void PrepareForNewEvent (void)
const G4ThreeVector & GetOrigPosition (void) const
const G4ThreeVector & GetOrigDirection (void) const
G4double GetOrigMomentumAmp (void) const
void SetOrigPosition (const G4ThreeVector &position, G4bool fromMessenger=true)
void SetOrigDirection (const G4ThreeVector &direction, G4bool fromMessenger=true)
void SetOrigMomentumAmp (G4double momentumAmp, G4bool fromMessenger=true)
void SetBeamParticle (G4ParticleDefinition *particleDefinition, G4bool fromMessenger=true)
Public Member Functions inherited from G4ParticleGun
G4ParticleGun ()
G4ParticleGun (G4int numberofparticles)
G4ParticleGun (G4ParticleDefinition *particleDef, G4int numberofparticles=1)
virtual ~G4ParticleGun ()
virtual void GeneratePrimaryVertex (G4Event *evt)
void SetParticleDefinition (G4ParticleDefinition *aParticleDefinition)
void SetParticleEnergy (G4double aKineticEnergy)
void SetParticleMomentum (G4double aMomentum)
void SetParticleMomentum (G4ParticleMomentum aMomentum)
void SetParticleMomentumDirection (G4ParticleMomentum aMomentumDirection)
void SetParticleCharge (G4double aCharge)
void SetParticlePolarization (G4ThreeVector aVal)
void SetNumberOfParticles (G4int i)
G4ParticleDefinition * GetParticleDefinition () const
G4ParticleMomentum GetParticleMomentumDirection () const
G4double GetParticleEnergy () const
G4double GetParticleMomentum () const
G4double GetParticleCharge () const
G4ThreeVector GetParticlePolarization () const
G4int GetNumberOfParticles () const
Public Member Functions inherited from G4VPrimaryGenerator
G4VPrimaryGenerator ()
virtual ~G4VPrimaryGenerator ()
G4ThreeVector GetParticlePosition ()
G4double GetParticleTime ()
void SetParticlePosition (G4ThreeVector aPosition)
void SetParticleTime (G4double aTime)
Private Attributes
CexmcPhysicsManager * physicsManager
G4ThreeVector origPos
G4ThreeVector origDir
G4double origMomentumAmp
CexmcParticleGunMessenger * messenger
Additional Inherited Members
Static Public Member Functions inherited from G4VPrimaryGenerator
static G4bool CheckVertexInsideWorld (const G4ThreeVector &pos)
Protected Member Functions inherited from G4ParticleGun
virtual void SetInitialValues ()
Protected Attributes inherited from G4ParticleGun
G4int NumberOfParticlesToBeGenerated
G4ParticleDefinition * particle_definition
G4ParticleMomentum particle_momentum_direction
G4double particle_energy
G4double particle_momentum
G4double particle_charge
G4ThreeVector particle_polarization
Detailed Description
Definition at line 55 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 55 of file CexmcParticleGun.hh
Constructor & Destructor Documentation
CexmcParticleGun::CexmcParticleGun (CexmcPhysicsManager * physicsManager, G4int nmbOfParticles = 1) explicit
Definition at line 48 of file CexmcParticleGun.cc.
View newest version in sPHENIX GitHub at line 48 of file CexmcParticleGun.cc
References messenger.
CexmcParticleGun::~CexmcParticleGun ()
Definition at line 58 of file CexmcParticleGun.cc.
View newest version in sPHENIX GitHub at line 58 of file CexmcParticleGun.cc
References messenger.
Member Function Documentation
const G4ThreeVector & CexmcParticleGun::GetOrigDirection (void) const inline
Definition at line 113 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 113 of file CexmcParticleGun.hh
References origDir.
Referenced by CexmcPrimaryGeneratorAction::GeneratePrimaries(), and CexmcChargeExchangeReconstructor::Reconstruct().
G4double CexmcParticleGun::GetOrigMomentumAmp (void) const inline
Definition at line 119 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 119 of file CexmcParticleGun.hh
References origMomentumAmp.
Referenced by CexmcPrimaryGeneratorAction::GeneratePrimaries(), CexmcChargeExchangeReconstructor::Reconstruct(), and CexmcChargeExchangeReconstructor::SetExpectedMomentumAmpDiff().
const G4ThreeVector & CexmcParticleGun::GetOrigPosition (void) const inline
Definition at line 107 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 107 of file CexmcParticleGun.hh
References origPos.
Referenced by CexmcPrimaryGeneratorAction::GeneratePrimaries().
void CexmcParticleGun::PrepareForNewEvent (void) inline
Definition at line 99 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 99 of file CexmcParticleGun.hh
References G4ParticleGun::particle_energy, and G4ParticleGun::particle_momentum.
Referenced by CexmcPrimaryGeneratorAction::GeneratePrimaries().
void CexmcParticleGun::SetBeamParticle (G4ParticleDefinition * particleDefinition, G4bool fromMessenger = true) inline
Definition at line 157 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 157 of file CexmcParticleGun.hh
References CexmcCmdIsNotAllowed, G4ParticleGun::SetParticleDefinition(), and ThrowExceptionIfProjectIsRead().
Referenced by CexmcParticleGunMessenger::SetNewValue().
void CexmcParticleGun::SetOrigDirection (const G4ThreeVector & direction, G4bool fromMessenger = true) inline
Definition at line 135 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 135 of file CexmcParticleGun.hh
References CexmcCmdIsNotAllowed, origDir, physicsManager, CexmcPhysicsManager::SetMaxIL(), and ThrowExceptionIfProjectIsRead().
Referenced by CexmcParticleGunMessenger::SetNewValue().
void CexmcParticleGun::SetOrigMomentumAmp (G4double momentumAmp, G4bool fromMessenger = true) inline
Definition at line 147 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 147 of file CexmcParticleGun.hh
References CexmcCmdIsNotAllowed, origMomentumAmp, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcParticleGunMessenger::SetNewValue().
void CexmcParticleGun::SetOrigPosition (const G4ThreeVector & position, G4bool fromMessenger = true) inline
Definition at line 125 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 125 of file CexmcParticleGun.hh
References CexmcCmdIsNotAllowed, origPos, position, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcParticleGunMessenger::SetNewValue().
Member Data Documentation
CexmcParticleGunMessenger* CexmcParticleGun::messenger private
Definition at line 95 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 95 of file CexmcParticleGun.hh
Referenced by CexmcParticleGun(), and ~CexmcParticleGun().
G4ThreeVector CexmcParticleGun::origDir private
Definition at line 90 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 90 of file CexmcParticleGun.hh
Referenced by GetOrigDirection(), and SetOrigDirection().
G4double CexmcParticleGun::origMomentumAmp private
Definition at line 92 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 92 of file CexmcParticleGun.hh
Referenced by GetOrigMomentumAmp(), and SetOrigMomentumAmp().
G4ThreeVector CexmcParticleGun::origPos private
Definition at line 88 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 88 of file CexmcParticleGun.hh
Referenced by GetOrigPosition(), and SetOrigPosition().
CexmcPhysicsManager* CexmcParticleGun::physicsManager private
Definition at line 86 of file CexmcParticleGun.hh.
View newest version in sPHENIX GitHub at line 86 of file CexmcParticleGun.hh
Referenced by SetOrigDirection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcParticleGun.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcParticleGun.cc