ECCE @ EIC Software: G4DNAMolecularReaction Class Reference
G4DNAMolecularReaction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAMolecularReaction.hh>
Public Member Functions
G4DNAMolecularReaction ()
G4DNAMolecularReaction (G4VDNAReactionModel *)
~G4DNAMolecularReaction () override=default
G4DNAMolecularReaction (const G4DNAMolecularReaction &other)=delete
G4DNAMolecularReaction & operator= (const G4DNAMolecularReaction &other)=delete
G4bool TestReactibility (const G4Track &, const G4Track &, double currentStepTime, bool userStepTimeLimit) override
std::unique_ptr
< G4ITReactionChange > MakeReaction (const G4Track &, const G4Track &) override
void SetReactionModel (G4VDNAReactionModel *)
Public Member Functions inherited from G4VITReactionProcess
G4VITReactionProcess ()=default
virtual ~G4VITReactionProcess ()=default
G4VITReactionProcess (const G4VITReactionProcess &other)=delete
G4VITReactionProcess & operator= (const G4VITReactionProcess &other)=delete
virtual void Initialize ()
virtual G4bool IsApplicable (const G4ITType &, const G4ITType &) const
virtual void SetReactionTable (const G4ITReactionTable *)
Protected Attributes
const
G4DNAMolecularReactionTable *& fMolReactionTable
G4VDNAReactionModel * fpReactionModel
Protected Attributes inherited from G4VITReactionProcess
const G4ITReactionTable * fpReactionTable = nullptr
G4String fName
Detailed Description
G4DNAMolecularReaction is the reaction process used in G4DNAMolecularStepByStepModel. It test whether molecules can react after testing. If so, the reaction is made.
Deprecated:
This class will be removed
Definition at line 61 of file G4DNAMolecularReaction.hh.
View newest version in sPHENIX GitHub at line 61 of file G4DNAMolecularReaction.hh
Constructor & Destructor Documentation
G4DNAMolecularReaction::G4DNAMolecularReaction ()
Definition at line 46 of file G4DNAMolecularReaction.cc.
View newest version in sPHENIX GitHub at line 46 of file G4DNAMolecularReaction.cc
G4DNAMolecularReaction::G4DNAMolecularReaction (G4VDNAReactionModel * pReactionModel) explicit
Definition at line 53 of file G4DNAMolecularReaction.cc.
View newest version in sPHENIX GitHub at line 53 of file G4DNAMolecularReaction.cc
References fpReactionModel.
G4DNAMolecularReaction::~G4DNAMolecularReaction () override default
G4DNAMolecularReaction::G4DNAMolecularReaction (const G4DNAMolecularReaction & other) delete
Member Function Documentation
std::unique_ptr< G4ITReactionChange > G4DNAMolecularReaction::MakeReaction (const G4Track & trackA, const G4Track & trackB) override virtual
Implements G4VITReactionProcess.
Definition at line 81 of file G4DNAMolecularReaction.cc.
View newest version in sPHENIX GitHub at line 81 of file G4DNAMolecularReaction.cc
References G4ITReactionChange::AddSecondary(), G4Molecule::BuildTrack(), fAlive, fMolReactionTable, G4Track::GetGlobalTime(), G4Molecule::GetMolecularConfiguration(), GetMolecule(), G4DNAMolecularReactionData::GetNbProducts(), G4Track::GetPosition(), G4DNAMolecularReactionTable::GetReactionData(), G4ITReactionChange::Initialize(), G4ITFinder< T >::Instance(), G4ITReactionChange::KillParents(), and G4ITFinder< T >::Push().
G4DNAMolecularReaction& G4DNAMolecularReaction::operator= (const G4DNAMolecularReaction & other) delete
void G4DNAMolecularReaction::SetReactionModel (G4VDNAReactionModel * pReactionModel)
Definition at line 120 of file G4DNAMolecularReaction.cc.
View newest version in sPHENIX GitHub at line 120 of file G4DNAMolecularReaction.cc
References fpReactionModel.
G4bool G4DNAMolecularReaction::TestReactibility (const G4Track & trackA, const G4Track & trackB, double currentStepTime, bool userStepTimeLimit) override virtual
Implements G4VITReactionProcess.
Definition at line 59 of file G4DNAMolecularReaction.cc.
View newest version in sPHENIX GitHub at line 59 of file G4DNAMolecularReaction.cc
References G4VDNAReactionModel::FindReaction(), fpReactionModel, G4Molecule::GetMolecularConfiguration(), GetMolecule(), and G4VDNAReactionModel::GetReactionRadius().
Member Data Documentation
const G4DNAMolecularReactionTable*& G4DNAMolecularReaction::fMolReactionTable protected
Definition at line 80 of file G4DNAMolecularReaction.hh.
View newest version in sPHENIX GitHub at line 80 of file G4DNAMolecularReaction.hh
Referenced by MakeReaction().
G4VDNAReactionModel* G4DNAMolecularReaction::fpReactionModel protected
Definition at line 81 of file G4DNAMolecularReaction.hh.
View newest version in sPHENIX GitHub at line 81 of file G4DNAMolecularReaction.hh
Referenced by G4DNAMolecularReaction(), SetReactionModel(), and TestReactibility().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAMolecularReaction.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAMolecularReaction.cc