ECCE @ EIC Software: G4VTHitsMap< T, Map_t > Class Template Reference
G4VTHitsMap< T, Map_t > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4THitsMap.hh>
Public Types
typedef G4VTHitsMap< T, Map_t > this_type
typedef T value_type
typedef Map_t map_type
typedef map_type::iterator iterator
typedef map_type::const_iterator const_iterator
Public Member Functions
G4VTHitsMap ()
G4VTHitsMap (G4String detName, G4String colNam)
virtual ~G4VTHitsMap ()
G4bool operator== (const G4VTHitsMap< T, Map_t > &right) const
template<typename U , typename MapU_t >
this_type & operator+= (const G4VTHitsMap< U, MapU_t > &right) const
virtual void DrawAllHits ()
virtual void PrintAllHits ()
Map_t * GetContainer () const
Map_t::size_type size ()
Map_t::size_type GetIndex (iterator itr)
Map_t::size_type GetIndex (const_iterator itr) const
template<typename MapU_t = Map_t, enable_if_t< !is_mmap_t(MapU_t), int > = 0>
T * GetObject (G4int idx) const
template<typename MapU_t = Map_t, enable_if_t< is_mmap_t(MapU_t), int > = 0>
T * GetObject (G4int idx) const
T * GetObject (iterator itr) const
const T * GetObject (const_iterator itr) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Map_t * GetMap () const
size_t entries () const
void clear ()
virtual G4VHit * GetHit (size_t) const
virtual size_t GetSize () const
template<typename U = T, typename MapU_t = Map_t, enable_if_t< is_same_t(U, T)&&!is_mmap_t(MapU_t), int > = 0>
size_t add (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t add (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t add (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0>
size_t add (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0>
size_t add (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t add (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t add (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U *&aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U &aHit) const
template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0>
size_t set (const G4int &key, U &aHit) const
template<typename MapU_t = Map_t, enable_if_t<!is_mmap_t(MapU_t), int > = 0>
T * operator[] (G4int key) const
template<typename MapU_t = Map_t, enable_if_t< is_mmap_t(MapU_t), int > = 0>
T * operator[] (G4int key) const
Public Member Functions inherited from G4HitsCollection
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
Public Member Functions inherited from G4VHitsCollection
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
G4String GetName ()
G4String GetSDname ()
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
G4String GetName ()
G4String GetSDname ()
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
const G4String & GetName () const
const G4String & GetSDname () const
void SetColID (G4int i)
G4int GetColID () const
Private Types
typedef std::multimap< G4int, T * > mmap_t
typedef std::pair< G4int, T * > pair_t
typedef
std::unordered_multimap< G4int,
T * > uommap_t
template<bool _Bp, typename _Tp = void>
using enable_if_t = typename std::enable_if< _Bp, _Tp >::type
Private Member Functions
template<typename U = T, enable_if_t< is_fundamental_t(U), int > = 0>
T * allocate () const
template<typename U = T, enable_if_t<!is_fundamental_t(U), int > = 0>
T * allocate () const
Additional Inherited Members
Protected Attributes inherited from G4HitsCollection
void * theCollection
Detailed Description
template<typename T, typename Map_t = std::map<G4int, T*>>
class G4VTHitsMap< T, Map_t >
Definition at line 48 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 48 of file G4THitsMap.hh
Member Typedef Documentation
template<typename T, typename Map_t = std::map<G4int, T*>> typedef map_type::const_iterator G4VTHitsMap< T, Map_t >::const_iterator
Definition at line 80 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 80 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<bool _Bp, typename _Tp = void> using G4VTHitsMap< T, Map_t >::enable_if_t = typename std::enable_if<_Bp, _Tp>::type private
Definition at line 62 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 62 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef map_type::iterator G4VTHitsMap< T, Map_t >::iterator
Definition at line 79 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 79 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef Map_t G4VTHitsMap< T, Map_t >::map_type
Definition at line 78 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 78 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef std::multimap<G4int, T*> G4VTHitsMap< T, Map_t >::mmap_t private
Definition at line 51 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 51 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef std::pair<G4int, T*> G4VTHitsMap< T, Map_t >::pair_t private
Definition at line 52 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 52 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef G4VTHitsMap<T, Map_t> G4VTHitsMap< T, Map_t >::this_type
Definition at line 76 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 76 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef std::unordered_multimap<G4int, T*> G4VTHitsMap< T, Map_t >::uommap_t private
Definition at line 53 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 53 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> typedef T G4VTHitsMap< T, Map_t >::value_type
Definition at line 77 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 77 of file G4THitsMap.hh
Constructor & Destructor Documentation
template<typename T , typename Map_t > G4VTHitsMap< T, Map_t >::G4VTHitsMap ()
Definition at line 474 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 474 of file G4THitsMap.hh
template<typename T , typename Map_t > G4VTHitsMap< T, Map_t >::G4VTHitsMap (G4String detName, G4String colNam)
Definition at line 482 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 482 of file G4THitsMap.hh
References G4HitsCollection::theCollection.
template<typename T , typename Map_t > G4VTHitsMap< T, Map_t >::~G4VTHitsMap () virtual
Definition at line 491 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 491 of file G4THitsMap.hh
Member Function Documentation
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t< is_same_t(U, T)&&!is_mmap_t(MapU_t), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U *& aHit) const inline
Definition at line 177 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 177 of file G4THitsMap.hh
Referenced by G4PSDoseDeposit::ProcessHits(), G4PSNofStep::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), G4PSNofCollision::ProcessHits(), G4PSTermination::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSPopulation::ProcessHits(), G4PSPassageTrackLength::ProcessHits(), G4PSPassageCellCurrent::ProcessHits(), G4PSPassageCellFlux::ProcessHits(), G4PSNofSecondary::ProcessHits(), G4PSCellFlux::ProcessHits(), G4PSTrackLength::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcSimpleEnergyDeposit::ProcessHits(), ScoreSpecies::ProcessHits(), and G4RTRun::RecordEvent().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U *& aHit) const inline
Definition at line 192 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 192 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U *& aHit) const inline
Definition at line 205 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 205 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U & aHit) const inline
Definition at line 224 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 224 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U & aHit) const inline
Definition at line 240 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 240 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U & aHit) const inline
Definition at line 254 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 254 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::add (const G4int & key, U & aHit) const inline
Definition at line 267 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 267 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, enable_if_t< is_fundamental_t(U), int > = 0> T* G4VTHitsMap< T, Map_t >::allocate () const inline private
Definition at line 66 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 66 of file G4THitsMap.hh
Referenced by G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::add(), and G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::set().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, enable_if_t<!is_fundamental_t(U), int > = 0> T* G4VTHitsMap< T, Map_t >::allocate () const inline private
Definition at line 72 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 72 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> iterator G4VTHitsMap< T, Map_t >::begin () inline
Definition at line 142 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 142 of file G4THitsMap.hh
Referenced by TSRunAction::EndOfRunAction().
template<typename T, typename Map_t = std::map<G4int, T*>> const_iterator G4VTHitsMap< T, Map_t >::begin () const inline
Definition at line 144 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 144 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> const_iterator G4VTHitsMap< T, Map_t >::cbegin () const inline
Definition at line 146 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 146 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> const_iterator G4VTHitsMap< T, Map_t >::cend () const inline
Definition at line 147 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 147 of file G4THitsMap.hh
template<typename T , typename Map_t > void G4VTHitsMap< T, Map_t >::clear (void) inline
Definition at line 537 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 537 of file G4THitsMap.hh
Referenced by G4PSCellCharge::clear(), G4PSEnergyDeposit::clear(), G4PSDoseDeposit::clear(), G4PSNofStep::clear(), G4PSTermination::clear(), G4PSTrackCounter::clear(), G4PSNofCollision::clear(), G4PSMinKinEAtGeneration::clear(), G4PSPassageTrackLength::clear(), G4PSPassageCellCurrent::clear(), G4PSPopulation::clear(), G4PSPassageCellFlux::clear(), G4PSTrackLength::clear(), CexmcSimpleEnergyDeposit::clear(), G4PSNofSecondary::clear(), G4PSCellFlux::clear(), CexmcTrackPoints::clear(), G4PSSphereSurfaceCurrent::clear(), G4PSCylinderSurfaceFlux::clear(), G4PSSphereSurfaceFlux::clear(), G4PSFlatSurfaceCurrent::clear(), G4PSCylinderSurfaceCurrent::clear(), G4PSFlatSurfaceFlux::clear(), ScoreSpecies::clear(), and G4RTRun::~G4RTRun().
template<typename T , typename Map_t > void G4VTHitsMap< T, Map_t >::DrawAllHits () virtual
Reimplemented from G4VHitsCollection.
Definition at line 510 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 510 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> iterator G4VTHitsMap< T, Map_t >::end () inline
Definition at line 143 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 143 of file G4THitsMap.hh
Referenced by TSRunAction::EndOfRunAction().
template<typename T, typename Map_t = std::map<G4int, T*>> const_iterator G4VTHitsMap< T, Map_t >::end () const inline
Definition at line 145 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 145 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> size_t G4VTHitsMap< T, Map_t >::entries () const inline
Definition at line 155 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 155 of file G4THitsMap.hh
Referenced by ML2Run::DumpAllScorer(), B01Run::DumpAllScorer(), B02Run::DumpAllScorer(), B03Run::DumpAllScorer(), RE02Run::DumpAllScorer(), CexmcTrackPointsInCalorimeter::PrintAll(), CexmcEnergyDepositInCalorimeter::PrintAll(), G4PSEnergyDeposit::PrintAll(), G4PSCellCharge::PrintAll(), G4PSDoseDeposit::PrintAll(), CexmcEnergyDepositInLeftRightSet::PrintAll(), CexmcTrackPointsInLeftRightSet::PrintAll(), G4PSNofStep::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSTrackCounter::PrintAll(), G4PSMinKinEAtGeneration::PrintAll(), G4PSNofCollision::PrintAll(), G4PSTermination::PrintAll(), G4PSPassageCellCurrent::PrintAll(), G4PSPopulation::PrintAll(), CexmcSimpleEnergyDeposit::PrintAll(), CexmcTrackPoints::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSNofSecondary::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), and ScoreSpecies::PrintAll().
template<typename T, typename Map_t = std::map<G4int, T*>> Map_t* G4VTHitsMap< T, Map_t >::GetContainer () const inline
Definition at line 114 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 114 of file G4THitsMap.hh
Referenced by G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::begin(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::cbegin(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::cend(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::end(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::GetObject(), and G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::size().
template<typename T, typename Map_t = std::map<G4int, T*>> virtual G4VHit* G4VTHitsMap< T, Map_t >::GetHit (size_t) const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 161 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 161 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> Map_t::size_type G4VTHitsMap< T, Map_t >::GetIndex (iterator itr) inline
Definition at line 120 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 120 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> Map_t::size_type G4VTHitsMap< T, Map_t >::GetIndex (const_iterator itr) const inline
Definition at line 123 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 123 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> Map_t* G4VTHitsMap< T, Map_t >::GetMap () const inline
Definition at line 151 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 151 of file G4THitsMap.hh
Referenced by G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::add(), G4GMocrenFileSceneHandler::AddCompound(), G4TheMTRayTracer::CreateBitMap(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), B01Run::DumpAllScorer(), B03Run::DumpAllScorer(), B02Run::DumpAllScorer(), ElectronRun::DumpData(), B3aEventAction::EndOfEventAction(), DicomRunAction::EndOfRunAction(), RE06Run::FindMinimum(), B4dEventAction::GetSum(), RE06Run::GetTotal(), RE06Run::Merge(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::operator+=(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator+=(), G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::operator[](), G4MPIscorerMerger::Pack(), CexmcEnergyDepositInCalorimeter::PrintAll(), CexmcTrackPointsInCalorimeter::PrintAll(), G4PSEnergyDeposit::PrintAll(), G4PSCellCharge::PrintAll(), CexmcEnergyDepositInLeftRightSet::PrintAll(), CexmcTrackPointsInLeftRightSet::PrintAll(), G4PSDoseDeposit::PrintAll(), G4PSNofStep::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSMinKinEAtGeneration::PrintAll(), G4PSNofCollision::PrintAll(), G4PSTrackCounter::PrintAll(), G4PSTermination::PrintAll(), G4PSPassageCellCurrent::PrintAll(), G4PSPopulation::PrintAll(), CexmcSimpleEnergyDeposit::PrintAll(), CexmcTrackPoints::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSNofSecondary::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), ScoreSpecies::PrintAll(), RE06Run::RecordEvent(), B3bRun::RecordEvent(), Run::RecordEvent(), and G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >::set().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename MapU_t = Map_t, enable_if_t< !is_mmap_t(MapU_t), int > = 0> T* G4VTHitsMap< T, Map_t >::GetObject (G4int idx) const inline
Definition at line 127 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 127 of file G4THitsMap.hh
Referenced by TSRunAction::EndOfRunAction().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename MapU_t = Map_t, enable_if_t< is_mmap_t(MapU_t), int > = 0> T* G4VTHitsMap< T, Map_t >::GetObject (G4int idx) const inline
Definition at line 131 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 131 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> T* G4VTHitsMap< T, Map_t >::GetObject (iterator itr) const inline
Definition at line 136 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 136 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> const T* G4VTHitsMap< T, Map_t >::GetObject (const_iterator itr) const inline
Definition at line 139 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 139 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> virtual size_t G4VTHitsMap< T, Map_t >::GetSize () const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 162 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 162 of file G4THitsMap.hh
Referenced by G4VScoringMesh::Accumulate(), G4MPIscorerMerger::CalculatePackSize(), RE06Run::FindMinimum(), RE06Run::GetTotal(), and G4MPIscorerMerger::Pack().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U , typename MapU_t > this_type& G4VTHitsMap< T, Map_t >::operator+= (const G4VTHitsMap< U, MapU_t > & right) const inline
Definition at line 97 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 97 of file G4THitsMap.hh
template<typename T, typename Map_t> G4bool G4VTHitsMap< T, Map_t >::operator== (const G4VTHitsMap< T, Map_t > & right) const
Definition at line 502 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 502 of file G4THitsMap.hh
References G4VHitsCollection::collectionName.
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename MapU_t = Map_t, enable_if_t<!is_mmap_t(MapU_t), int > = 0> T* G4VTHitsMap< T, Map_t >::operator[] (G4int key) const inline
Definition at line 432 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 432 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename MapU_t = Map_t, enable_if_t< is_mmap_t(MapU_t), int > = 0> T* G4VTHitsMap< T, Map_t >::operator[] (G4int key) const inline
Definition at line 442 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 442 of file G4THitsMap.hh
template<typename T , typename Map_t > void G4VTHitsMap< T, Map_t >::PrintAllHits () virtual
Reimplemented from G4VHitsCollection.
Definition at line 516 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 516 of file G4THitsMap.hh
References G4cout, and G4endl.
Referenced by G4VScoringMesh::Accumulate().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U *& aHit) const inline
Definition at line 287 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 287 of file G4THitsMap.hh
Referenced by RE06Run::Merge(), G4PSMinKinEAtGeneration::ProcessHits(), CexmcTrackPoints::ProcessHits(), RE06Run::RecordEvent(), and G4MPIscorerMerger::UnPackHitStatDoubleMap().
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U *& aHit) const inline
Definition at line 301 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 301 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U *& aHit) const inline
Definition at line 319 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 319 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U *& aHit) const inline
Definition at line 336 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 336 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U & aHit) const inline
Definition at line 362 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 362 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U & aHit) const inline
Definition at line 379 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 379 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&!is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U & aHit) const inline
Definition at line 394 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 394 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> template<typename U = T, typename MapU_t = Map_t, enable_if_t<(!is_same_t(U, T)&&is_mmap_t(MapU_t)), int > = 0> size_t G4VTHitsMap< T, Map_t >::set (const G4int & key, U & aHit) const inline
Definition at line 411 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 411 of file G4THitsMap.hh
template<typename T, typename Map_t = std::map<G4int, T*>> Map_t::size_type G4VTHitsMap< T, Map_t >::size (void) inline
Definition at line 117 of file G4THitsMap.hh.
View newest version in sPHENIX GitHub at line 117 of file G4THitsMap.hh
Referenced by TSRunAction::EndOfRunAction().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4THitsMap.hh