ECCE @ EIC Software: CexmcRun Class Reference
CexmcRun Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRun.hh>
Public Member Functions
CexmcRun ()
void IncrementNmbOfHitsSampled (G4int index)
void IncrementNmbOfHitsSampledFull (G4int index)
void IncrementNmbOfHitsTriggeredRealRange (G4int index)
void IncrementNmbOfHitsTriggeredRecRange (G4int index)
void IncrementNmbOfOrphanHits (G4int index)
void IncrementNmbOfFalseHitsTriggeredEDT (void)
void IncrementNmbOfFalseHitsTriggeredRec (void)
void IncrementNmbOfSavedEvents (void)
void IncrementNmbOfSavedFastEvents (void)
const CexmcNmbOfHitsInRanges & GetNmbOfHitsSampled (void) const
const CexmcNmbOfHitsInRanges & GetNmbOfHitsSampledFull (void) const
const CexmcNmbOfHitsInRanges & GetNmbOfHitsTriggeredRealRange (void) const
const CexmcNmbOfHitsInRanges & GetNmbOfHitsTriggeredRecRange (void) const
const CexmcNmbOfHitsInRanges & GetNmbOfOrphanHits (void) const
G4int GetNmbOfFalseHitsTriggeredEDT (void) const
G4int GetNmbOfFalseHitsTriggeredRec (void) const
G4int GetNmbOfSavedEvents (void) const
G4int GetNmbOfSavedFastEvents (void) const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
CexmcNmbOfHitsInRanges nmbOfHitsSampled
CexmcNmbOfHitsInRanges nmbOfHitsSampledFull
CexmcNmbOfHitsInRanges nmbOfHitsTriggeredRealRange
CexmcNmbOfHitsInRanges nmbOfHitsTriggeredRecRange
CexmcNmbOfHitsInRanges nmbOfOrphanHits
G4int nmbOfFalseHitsTriggeredEDT
G4int nmbOfFalseHitsTriggeredRec
G4int nmbOfSavedEvents
G4int nmbOfSavedFastEvents
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Definition at line 56 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcRun.hh
Constructor & Destructor Documentation
CexmcRun::CexmcRun ()
Definition at line 47 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 47 of file CexmcRun.cc
Member Function Documentation
G4int CexmcRun::GetNmbOfFalseHitsTriggeredEDT (void) const inline
Definition at line 157 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 157 of file CexmcRun.hh
References nmbOfFalseHitsTriggeredEDT.
Referenced by CexmcRunAction::EndOfRunAction().
G4int CexmcRun::GetNmbOfFalseHitsTriggeredRec (void) const inline
Definition at line 163 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 163 of file CexmcRun.hh
References nmbOfFalseHitsTriggeredRec.
Referenced by CexmcRunAction::EndOfRunAction().
const CexmcNmbOfHitsInRanges & CexmcRun::GetNmbOfHitsSampled (void) const inline
Definition at line 123 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 123 of file CexmcRun.hh
References nmbOfHitsSampled.
Referenced by CexmcRunAction::EndOfRunAction().
const CexmcNmbOfHitsInRanges & CexmcRun::GetNmbOfHitsSampledFull (void) const inline
Definition at line 130 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 130 of file CexmcRun.hh
References nmbOfHitsSampledFull.
Referenced by CexmcRunAction::EndOfRunAction().
const CexmcNmbOfHitsInRanges & CexmcRun::GetNmbOfHitsTriggeredRealRange (void) const inline
Definition at line 137 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 137 of file CexmcRun.hh
References nmbOfHitsTriggeredRealRange.
Referenced by CexmcRunAction::EndOfRunAction().
const CexmcNmbOfHitsInRanges & CexmcRun::GetNmbOfHitsTriggeredRecRange (void) const inline
Definition at line 144 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 144 of file CexmcRun.hh
References nmbOfHitsTriggeredRecRange.
Referenced by CexmcRunAction::EndOfRunAction().
const CexmcNmbOfHitsInRanges & CexmcRun::GetNmbOfOrphanHits (void) const inline
Definition at line 151 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 151 of file CexmcRun.hh
References nmbOfOrphanHits.
Referenced by CexmcRunAction::EndOfRunAction().
G4int CexmcRun::GetNmbOfSavedEvents (void) const inline
Definition at line 169 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 169 of file CexmcRun.hh
References nmbOfSavedEvents.
G4int CexmcRun::GetNmbOfSavedFastEvents (void) const inline
Definition at line 175 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 175 of file CexmcRun.hh
References nmbOfSavedFastEvents.
void CexmcRun::IncrementNmbOfFalseHitsTriggeredEDT (void)
Definition at line 111 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 111 of file CexmcRun.cc
References nmbOfFalseHitsTriggeredEDT.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfFalseHitsTriggeredRec (void)
Definition at line 117 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 117 of file CexmcRun.cc
References nmbOfFalseHitsTriggeredRec.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfHitsSampled (G4int index)
Definition at line 54 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 54 of file CexmcRun.cc
References nmbOfHitsSampled.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfHitsSampledFull (G4int index)
Definition at line 65 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 65 of file CexmcRun.cc
References nmbOfHitsSampledFull.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfHitsTriggeredRealRange (G4int index)
Definition at line 76 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 76 of file CexmcRun.cc
References nmbOfHitsTriggeredRealRange.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfHitsTriggeredRecRange (G4int index)
Definition at line 88 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 88 of file CexmcRun.cc
References nmbOfHitsTriggeredRecRange.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfOrphanHits (G4int index)
Definition at line 100 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 100 of file CexmcRun.cc
References nmbOfOrphanHits.
Referenced by CexmcEventAction::UpdateRunHits().
void CexmcRun::IncrementNmbOfSavedEvents (void)
Definition at line 123 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 123 of file CexmcRun.cc
References nmbOfSavedEvents.
void CexmcRun::IncrementNmbOfSavedFastEvents (void)
Definition at line 129 of file CexmcRun.cc.
View newest version in sPHENIX GitHub at line 129 of file CexmcRun.cc
References nmbOfSavedFastEvents.
Member Data Documentation
G4int CexmcRun::nmbOfFalseHitsTriggeredEDT private
Definition at line 112 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 112 of file CexmcRun.hh
Referenced by GetNmbOfFalseHitsTriggeredEDT(), and IncrementNmbOfFalseHitsTriggeredEDT().
G4int CexmcRun::nmbOfFalseHitsTriggeredRec private
Definition at line 114 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 114 of file CexmcRun.hh
Referenced by GetNmbOfFalseHitsTriggeredRec(), and IncrementNmbOfFalseHitsTriggeredRec().
CexmcNmbOfHitsInRanges CexmcRun::nmbOfHitsSampled private
Definition at line 102 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 102 of file CexmcRun.hh
Referenced by GetNmbOfHitsSampled(), and IncrementNmbOfHitsSampled().
CexmcNmbOfHitsInRanges CexmcRun::nmbOfHitsSampledFull private
Definition at line 104 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 104 of file CexmcRun.hh
Referenced by GetNmbOfHitsSampledFull(), and IncrementNmbOfHitsSampledFull().
CexmcNmbOfHitsInRanges CexmcRun::nmbOfHitsTriggeredRealRange private
Definition at line 106 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 106 of file CexmcRun.hh
Referenced by GetNmbOfHitsTriggeredRealRange(), and IncrementNmbOfHitsTriggeredRealRange().
CexmcNmbOfHitsInRanges CexmcRun::nmbOfHitsTriggeredRecRange private
Definition at line 108 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 108 of file CexmcRun.hh
Referenced by GetNmbOfHitsTriggeredRecRange(), and IncrementNmbOfHitsTriggeredRecRange().
CexmcNmbOfHitsInRanges CexmcRun::nmbOfOrphanHits private
Definition at line 110 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 110 of file CexmcRun.hh
Referenced by GetNmbOfOrphanHits(), and IncrementNmbOfOrphanHits().
G4int CexmcRun::nmbOfSavedEvents private
Definition at line 116 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 116 of file CexmcRun.hh
Referenced by GetNmbOfSavedEvents(), and IncrementNmbOfSavedEvents().
G4int CexmcRun::nmbOfSavedFastEvents private
Definition at line 118 of file CexmcRun.hh.
View newest version in sPHENIX GitHub at line 118 of file CexmcRun.hh
Referenced by GetNmbOfSavedFastEvents(), and IncrementNmbOfSavedFastEvents().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRun.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcRun.cc