ECCE @ EIC Software: G4GHEKinematicsVector Class Reference
G4GHEKinematicsVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4GHEKinematicsVector.hh>
Public Member Functions
G4GHEKinematicsVector ()
~G4GHEKinematicsVector ()
G4GHEKinematicsVector (const G4GHEKinematicsVector &p)
G4GHEKinematicsVector & operator= (const G4GHEKinematicsVector &p)
void SetMomentum (G4ParticleMomentum mom)
void SetMomentumAndUpdate (G4ParticleMomentum mom)
const G4ParticleMomentum GetMomentum () const
void SetMomentum (G4double x, G4double y, G4double z)
void SetMomentumAndUpdate (G4double x, G4double y, G4double z)
void SetMomentum (G4double x, G4double y)
void SetMomentumAndUpdate (G4double x, G4double y)
void SetMomentum (G4double z)
void SetMomentumAndUpdate (G4double z)
void SetEnergy (G4double e)
void SetEnergyAndUpdate (G4double e)
void SetKineticEnergy (G4double ekin)
void SetKineticEnergyAndUpdate (G4double ekin)
G4double GetEnergy ()
G4double GetKineticEnergy ()
void SetMass (G4double mas)
void SetMassAndUpdate (G4double mas)
G4double GetMass ()
void SetCharge (G4double c)
G4double GetCharge ()
void SetTOF (G4double t)
G4double GetTOF ()
void SetSide (G4int sid)
G4int GetSide ()
void setFlag (G4bool f)
G4bool getFlag ()
void SetCode (G4int c)
void SetParticleDef (G4ParticleDefinition *c)
G4int GetCode ()
G4ParticleDefinition * GetParticleDef ()
void SetZero ()
void Add (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Sub (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Lor (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
G4double CosAng (const G4GHEKinematicsVector &p)
G4double Ang (const G4GHEKinematicsVector &p)
G4double Dot4 (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
G4double Impu (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Add3 (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Sub3 (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Cross (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
G4double Dot (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Smul (const G4GHEKinematicsVector &p, G4double h)
void SmulAndUpdate (const G4GHEKinematicsVector &p, G4double h)
void Norz (const G4GHEKinematicsVector &p)
G4double Length ()
void Exch (G4GHEKinematicsVector &p1)
void Defs1 (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2)
void Defs (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &p2, G4GHEKinematicsVector &my, G4GHEKinematicsVector &mz)
void Trac (const G4GHEKinematicsVector &p1, const G4GHEKinematicsVector &mx, const G4GHEKinematicsVector &my, const G4GHEKinematicsVector &mz)
void Print (G4int LLL)
Public Attributes
G4ParticleMomentum momentum
G4double energy
G4double kineticEnergy
G4double mass
G4double charge
G4double timeOfFlight
G4int side
G4bool flag
G4int code
G4ParticleDefinition * particleDef
Detailed Description
Definition at line 50 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 50 of file G4GHEKinematicsVector.hh
Constructor & Destructor Documentation
G4GHEKinematicsVector::G4GHEKinematicsVector () inline
Definition at line 54 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GHEKinematicsVector.hh
References charge, energy, flag, kineticEnergy, mass, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, and timeOfFlight.
G4GHEKinematicsVector::~G4GHEKinematicsVector () inline
Definition at line 70 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 70 of file G4GHEKinematicsVector.hh
G4GHEKinematicsVector::G4GHEKinematicsVector (const G4GHEKinematicsVector & p) inline
Definition at line 73 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GHEKinematicsVector.hh
References charge, code, energy, flag, kineticEnergy, mass, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, timeOfFlight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Function Documentation
void G4GHEKinematicsVector::Add (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 361 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 361 of file G4GHEKinematicsVector.hh
References b, charge, code, energy, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, momentum, and particleDef.
void G4GHEKinematicsVector::Add3 (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 456 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 456 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4GHEKinematicsVector::Ang (const G4GHEKinematicsVector & p) inline
Definition at line 424 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 424 of file G4GHEKinematicsVector.hh
References a, kdfinder::abs(), CLHEP::Hep3Vector::mag2(), momentum, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4GHEKinematicsVector::CosAng (const G4GHEKinematicsVector & p) inline
Definition at line 411 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 411 of file G4GHEKinematicsVector.hh
References a, kdfinder::abs(), CLHEP::Hep3Vector::mag2(), momentum, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Cross (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 474 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 474 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Defs (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2, G4GHEKinematicsVector & my, G4GHEKinematicsVector & mz) inline
Definition at line 608 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 608 of file G4GHEKinematicsVector.hh
References CLHEP::Hep3Vector::mag(), momentum, G4InuclParticleNames::pp, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Defs1 (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 579 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 579 of file G4GHEKinematicsVector.hh
References kdfinder::abs(), CLHEP::halfpi, CLHEP::Hep3Vector::mag(), momentum, CLHEP::pi, pt2, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4GHEKinematicsVector::Dot (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 487 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 487 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4GHEKinematicsVector::Dot4 (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 438 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 438 of file G4GHEKinematicsVector.hh
References energy, momentum, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Exch (G4GHEKinematicsVector & p1) inline
Definition at line 548 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 548 of file G4GHEKinematicsVector.hh
References mx.
G4double G4GHEKinematicsVector::GetCharge () inline
Definition at line 311 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 311 of file G4GHEKinematicsVector.hh
References charge.
G4int G4GHEKinematicsVector::GetCode () inline
Definition at line 338 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 338 of file G4GHEKinematicsVector.hh
References code.
G4double G4GHEKinematicsVector::GetEnergy () inline
Definition at line 260 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 260 of file G4GHEKinematicsVector.hh
References energy.
G4bool G4GHEKinematicsVector::getFlag () inline
Definition at line 329 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 329 of file G4GHEKinematicsVector.hh
References flag.
G4double G4GHEKinematicsVector::GetKineticEnergy () inline
Definition at line 263 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 263 of file G4GHEKinematicsVector.hh
References kineticEnergy.
G4double G4GHEKinematicsVector::GetMass () inline
Definition at line 305 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 305 of file G4GHEKinematicsVector.hh
References mass.
const G4ParticleMomentum G4GHEKinematicsVector::GetMomentum (void) const inline
Definition at line 123 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 123 of file G4GHEKinematicsVector.hh
References momentum.
G4ParticleDefinition* G4GHEKinematicsVector::GetParticleDef () inline
Definition at line 341 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 341 of file G4GHEKinematicsVector.hh
References particleDef.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
G4int G4GHEKinematicsVector::GetSide () inline
Definition at line 323 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 323 of file G4GHEKinematicsVector.hh
References side.
G4double G4GHEKinematicsVector::GetTOF () inline
Definition at line 317 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 317 of file G4GHEKinematicsVector.hh
References timeOfFlight.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
G4double G4GHEKinematicsVector::Impu (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 447 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 447 of file G4GHEKinematicsVector.hh
References energy, momentum, sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4GHEKinematicsVector::Length () inline
Definition at line 542 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 542 of file G4GHEKinematicsVector.hh
References CLHEP::Hep3Vector::mag(), and momentum.
void G4GHEKinematicsVector::Lor (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 393 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 393 of file G4GHEKinematicsVector.hh
References a, code, CLHEP::Hep3Vector::dot(), energy, flag, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, sqr(), timeOfFlight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Norz (const G4GHEKinematicsVector & p) inline
Definition at line 522 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 522 of file G4GHEKinematicsVector.hh
References a, charge, code, energy, flag, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, timeOfFlight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4GHEKinematicsVector& G4GHEKinematicsVector::operator= (const G4GHEKinematicsVector & p) inline
Definition at line 90 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GHEKinematicsVector.hh
References charge, code, energy, flag, kineticEnergy, mass, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, timeOfFlight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Print (G4int LLL) inline
Definition at line 674 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 674 of file G4GHEKinematicsVector.hh
References charge, energy, flag, G4cout, G4endl, kineticEnergy, mass, momentum, particleDef, side, timeOfFlight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::SetCharge (G4double c) inline
Definition at line 308 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 308 of file G4GHEKinematicsVector.hh
References c, and charge.
void G4GHEKinematicsVector::SetCode (G4int c) inline
Definition at line 332 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 332 of file G4GHEKinematicsVector.hh
References c.
void G4GHEKinematicsVector::SetEnergy (G4double e) inline
Definition at line 180 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 180 of file G4GHEKinematicsVector.hh
References e, and energy.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation().
void G4GHEKinematicsVector::SetEnergyAndUpdate (G4double e) inline
Definition at line 183 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 183 of file G4GHEKinematicsVector.hh
References e, energy, G4UniformRand, kineticEnergy, CLHEP::Hep3Vector::mag(), mass, momentum, phi, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation().
void G4GHEKinematicsVector::setFlag (G4bool f) inline
Definition at line 326 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 326 of file G4GHEKinematicsVector.hh
References f, and flag.
void G4GHEKinematicsVector::SetKineticEnergy (G4double ekin) inline
Definition at line 220 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 220 of file G4GHEKinematicsVector.hh
References kineticEnergy.
void G4GHEKinematicsVector::SetKineticEnergyAndUpdate (G4double ekin) inline
Definition at line 223 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 223 of file G4GHEKinematicsVector.hh
References energy, G4UniformRand, kineticEnergy, CLHEP::Hep3Vector::mag(), mass, momentum, phi, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
void G4GHEKinematicsVector::SetMass (G4double mas) inline
Definition at line 266 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 266 of file G4GHEKinematicsVector.hh
References mass.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
void G4GHEKinematicsVector::SetMassAndUpdate (G4double mas) inline
Definition at line 269 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 269 of file G4GHEKinematicsVector.hh
References energy, G4UniformRand, kineticEnergy, CLHEP::Hep3Vector::mag(), mass, max, momentum, phi, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::SetMomentum (G4ParticleMomentum mom) inline
Definition at line 111 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 111 of file G4GHEKinematicsVector.hh
References mom, and momentum.
void G4GHEKinematicsVector::SetMomentum (G4double x, G4double y, G4double z) inline
Definition at line 126 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 126 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
void G4GHEKinematicsVector::SetMomentum (G4double x, G4double y) inline
Definition at line 146 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 146 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), and CLHEP::Hep3Vector::setY().
void G4GHEKinematicsVector::SetMomentum (G4double z) inline
Definition at line 164 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 164 of file G4GHEKinematicsVector.hh
References momentum, and CLHEP::Hep3Vector::setZ().
void G4GHEKinematicsVector::SetMomentumAndUpdate (G4ParticleMomentum mom) inline
Definition at line 114 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 114 of file G4GHEKinematicsVector.hh
References energy, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, mom, and momentum.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation().
void G4GHEKinematicsVector::SetMomentumAndUpdate (G4double x, G4double y, G4double z) inline
Definition at line 135 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 135 of file G4GHEKinematicsVector.hh
References energy, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
void G4GHEKinematicsVector::SetMomentumAndUpdate (G4double x, G4double y) inline
Definition at line 154 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GHEKinematicsVector.hh
References energy, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, momentum, CLHEP::Hep3Vector::setX(), and CLHEP::Hep3Vector::setY().
void G4GHEKinematicsVector::SetMomentumAndUpdate (G4double z) inline
Definition at line 171 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 171 of file G4GHEKinematicsVector.hh
References energy, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, momentum, and CLHEP::Hep3Vector::setZ().
void G4GHEKinematicsVector::SetParticleDef (G4ParticleDefinition * c) inline
Definition at line 335 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 335 of file G4GHEKinematicsVector.hh
References c, and particleDef.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
void G4GHEKinematicsVector::SetSide (G4int sid) inline
Definition at line 320 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 320 of file G4GHEKinematicsVector.hh
References side.
void G4GHEKinematicsVector::SetTOF (G4double t) inline
Definition at line 314 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 314 of file G4GHEKinematicsVector.hh
References t, and timeOfFlight.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
void G4GHEKinematicsVector::SetZero () inline
Definition at line 344 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 344 of file G4GHEKinematicsVector.hh
References charge, energy, flag, kineticEnergy, mass, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, and timeOfFlight.
Referenced by G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), and G4AntiNeutronAnnihilationAtRest::GenerateSecondaries().
void G4GHEKinematicsVector::Smul (const G4GHEKinematicsVector & p, G4double h) inline
Definition at line 495 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 495 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::SmulAndUpdate (const G4GHEKinematicsVector & p, G4double h) inline
Definition at line 504 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 504 of file G4GHEKinematicsVector.hh
References charge, code, energy, flag, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, momentum, particleDef, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), side, timeOfFlight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Sub (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 377 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 377 of file G4GHEKinematicsVector.hh
References b, charge, code, energy, kineticEnergy, CLHEP::Hep3Vector::mag2(), mass, max, momentum, and particleDef.
void G4GHEKinematicsVector::Sub3 (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & p2) inline
Definition at line 465 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 465 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4GHEKinematicsVector::Trac (const G4GHEKinematicsVector & p1, const G4GHEKinematicsVector & mx, const G4GHEKinematicsVector & my, const G4GHEKinematicsVector & mz) inline
Definition at line 654 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 654 of file G4GHEKinematicsVector.hh
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4GHEKinematicsVector::charge
Definition at line 687 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 687 of file G4GHEKinematicsVector.hh
Referenced by Add(), G4GHEKinematicsVector(), GetCharge(), Norz(), operator=(), Print(), SetCharge(), SetZero(), SmulAndUpdate(), and Sub().
G4int G4GHEKinematicsVector::code
Definition at line 691 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 691 of file G4GHEKinematicsVector.hh
Referenced by Add(), G4GHEKinematicsVector(), GetCode(), Lor(), Norz(), operator=(), SmulAndUpdate(), and Sub().
G4double G4GHEKinematicsVector::energy
Definition at line 684 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 684 of file G4GHEKinematicsVector.hh
Referenced by Add(), Dot4(), G4GHEKinematicsVector(), GetEnergy(), Impu(), Lor(), Norz(), operator=(), Print(), SetEnergy(), SetEnergyAndUpdate(), SetKineticEnergyAndUpdate(), SetMassAndUpdate(), SetMomentumAndUpdate(), SetZero(), SmulAndUpdate(), and Sub().
G4bool G4GHEKinematicsVector::flag
Definition at line 690 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 690 of file G4GHEKinematicsVector.hh
Referenced by G4GHEKinematicsVector(), getFlag(), Lor(), Norz(), operator=(), Print(), setFlag(), SetZero(), and SmulAndUpdate().
G4double G4GHEKinematicsVector::kineticEnergy
Definition at line 685 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 685 of file G4GHEKinematicsVector.hh
Referenced by Add(), G4GHEKinematicsVector(), GetKineticEnergy(), Lor(), Norz(), operator=(), Print(), SetEnergyAndUpdate(), SetKineticEnergy(), SetKineticEnergyAndUpdate(), SetMassAndUpdate(), SetMomentumAndUpdate(), SetZero(), SmulAndUpdate(), and Sub().
G4double G4GHEKinematicsVector::mass
Definition at line 686 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 686 of file G4GHEKinematicsVector.hh
Referenced by Add(), G4GHEKinematicsVector(), GetMass(), Lor(), Norz(), operator=(), Print(), SetEnergyAndUpdate(), SetKineticEnergyAndUpdate(), SetMass(), SetMassAndUpdate(), SetMomentumAndUpdate(), SetZero(), SmulAndUpdate(), and Sub().
G4ParticleMomentum G4GHEKinematicsVector::momentum
Definition at line 683 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 683 of file G4GHEKinematicsVector.hh
Referenced by Add(), Add3(), Ang(), CosAng(), Cross(), Defs(), Defs1(), Dot(), Dot4(), G4GHEKinematicsVector(), GetMomentum(), Impu(), Length(), Lor(), Norz(), operator=(), Print(), SetEnergyAndUpdate(), SetKineticEnergyAndUpdate(), SetMassAndUpdate(), SetMomentum(), SetMomentumAndUpdate(), SetZero(), Smul(), SmulAndUpdate(), Sub(), Sub3(), and Trac().
G4ParticleDefinition* G4GHEKinematicsVector::particleDef
Definition at line 692 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 692 of file G4GHEKinematicsVector.hh
Referenced by Add(), G4GHEKinematicsVector(), GetParticleDef(), Lor(), Norz(), operator=(), Print(), SetParticleDef(), SetZero(), SmulAndUpdate(), and Sub().
G4int G4GHEKinematicsVector::side
Definition at line 689 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 689 of file G4GHEKinematicsVector.hh
Referenced by G4GHEKinematicsVector(), GetSide(), Lor(), Norz(), operator=(), Print(), SetSide(), SetZero(), and SmulAndUpdate().
G4double G4GHEKinematicsVector::timeOfFlight
Definition at line 688 of file G4GHEKinematicsVector.hh.
View newest version in sPHENIX GitHub at line 688 of file G4GHEKinematicsVector.hh
Referenced by G4GHEKinematicsVector(), GetTOF(), Lor(), Norz(), operator=(), Print(), SetTOF(), SetZero(), and SmulAndUpdate().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4GHEKinematicsVector.hh