ECCE @ EIC Software: G4Radioactivation Class Reference
G4Radioactivation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4Radioactivation.hh>
Public Member Functions
G4Radioactivation (const G4String &processName="Radioactivation")
~G4Radioactivation ()
virtual void ProcessDescription (std::ostream &outFile) const
G4DecayTable * GetDecayTable1 (const G4ParticleDefinition *)
void SetDecayBias (G4String filename)
void SetHLThreshold (G4double hl)
void SetSourceTimeProfile (G4String filename)
G4bool IsRateTableReady (const G4ParticleDefinition &)
void CalculateChainsFromParent (const G4ParticleDefinition &)
void GetChainsFromParent (const G4ParticleDefinition &)
void SetDecayRate (G4int, G4int, G4double, G4int, std::vector< G4double >, std::vector< G4double >)
std::vector
< G4RadioactivityTable * > GetTheRadioactivityTables ()
void SetAnalogueMonteCarlo (G4bool r)
G4bool IsAnalogueMonteCarlo ()
void SetBRBias (G4bool r)
void SetSplitNuclei (G4int r)
G4int GetSplitNuclei ()
G4VParticleChange * DecayIt (const G4Track &theTrack, const G4Step &theStep)
Public Member Functions inherited from G4RadioactiveDecayBase
G4RadioactiveDecayBase (const G4String &processName="RadioactiveDecayBase")
~G4RadioactiveDecayBase ()
G4bool IsApplicable (const G4ParticleDefinition &)
G4DecayTable * GetDecayTable (const G4ParticleDefinition *)
void SelectAVolume (const G4String aVolume)
void DeselectAVolume (const G4String aVolume)
void SelectAllVolumes ()
void DeselectAllVolumes ()
void SetICM (G4bool icm)
void SetARM (G4bool arm)
G4DecayTable * LoadDecayTable (const G4ParticleDefinition &theParentNucleus)
void AddUserDecayDataFile (G4int Z, G4int A, G4String filename)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetNucleusLimits (G4NucleusLimits theNucleusLimits1)
G4NucleusLimits GetNucleusLimits () const
void SetDecayDirection (const G4ThreeVector &theDir)
const G4ThreeVector & GetDecayDirection () const
void SetDecayHalfAngle (G4double halfAngle=0.*CLHEP::deg)
G4double GetDecayHalfAngle () const
void SetDecayCollimation (const G4ThreeVector &theDir, G4double halfAngle=0.*CLHEP::deg)
void BuildPhysicsTable (const G4ParticleDefinition &)
G4VParticleChange * DecayIt (const G4Track &theTrack, const G4Step &theStep)
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double ConvolveSourceTimeProfile (const G4double, const G4double)
G4double GetDecayTime ()
G4int GetDecayTimeBin (const G4double aDecayTime)
G4double GetMeanLifeTime (const G4Track &theTrack, G4ForceCondition *condition)
void AddDeexcitationSpectrumForBiasMode (G4ParticleDefinition *apartDef, G4double weight, G4double currenTime, std::vector< double > &weights_v, std::vector< double > &times_v, std::vector< G4DynamicParticle * > &secondaries_v)
Protected Member Functions inherited from G4RadioactiveDecayBase
void DecayAnalog (const G4Track &theTrack)
G4DecayProducts * DoDecay (const G4ParticleDefinition &theParticleDef)
void CollimateDecay (G4DecayProducts *products)
void CollimateDecayProduct (G4DynamicParticle *product)
G4ThreeVector ChooseCollimationDirection () const
G4double GetMeanFreePath (const G4Track &theTrack, G4double previousStepSize, G4ForceCondition *condition)
G4double GetMeanLifeTime (const G4Track &theTrack, G4ForceCondition *condition)
Protected Attributes
G4RadioactivationMessenger * theRadioactivationMessenger
Protected Attributes inherited from G4RadioactiveDecayBase
G4ParticleChangeForRadDecay fParticleChangeForRadDecay
G4RadioactiveDecayBaseMessenger * theRadioactiveDecayBaseMessenger
G4PhotonEvaporation * photonEvaporation
std::vector< G4String > ValidVolumes
bool isAllVolumesMode
DecayTableMap * dkmap
Private Member Functions
G4VParticleChange * AtRestDoIt (const G4Track &theTrack, const G4Step &theStep)
G4VParticleChange * PostStepDoIt (const G4Track &theTrack, const G4Step &theStep)
Private Attributes
G4bool AnalogueMC
G4bool BRBias
G4int NSplit
G4double halflifethreshold
G4int NSourceBin
G4double SBin [100]
G4double SProfile [100]
G4int NDecayBin
G4double DBin [100]
G4double DProfile [100]
G4RadioactiveDecayRatesToDaughter ratesToDaughter
G4RadioactiveDecayRates theDecayRateVector
G4RadioactiveDecayChainsFromParent chainsFromParent
G4RadioactiveDecayParentChainTable theParentChainTable
std::vector
< G4RadioactivityTable * > theRadioactivityTables
G4int decayWindows [100]
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Static Protected Attributes inherited from G4RadioactiveDecayBase
static const G4double levelTolerance = 10.0*eV
Detailed Description
Definition at line 55 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 55 of file G4Radioactivation.hh
Constructor & Destructor Documentation
G4Radioactivation::G4Radioactivation (const G4String & processName = "Radioactivation")
Definition at line 93 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 93 of file G4Radioactivation.cc
References AnalogueMC, BRBias, DBin, decayWindows, DProfile, G4cout, G4endl, G4RadioactiveDecayBase::GetVerboseLevel(), halflifethreshold, nanosecond, NDecayBin, NSourceBin, NSplit, SBin, SProfile, theRadioactivationMessenger, and theRadioactivityTables.
G4Radioactivation::~G4Radioactivation ()
Definition at line 139 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 139 of file G4Radioactivation.cc
References theRadioactivationMessenger.
Member Function Documentation
void G4Radioactivation::AddDeexcitationSpectrumForBiasMode (G4ParticleDefinition * apartDef, G4double weight, G4double currenTime, std::vector< double > & weights_v, std::vector< double > & times_v, std::vector< G4DynamicParticle * > & secondaries_v) protected
Definition at line 1098 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 1098 of file G4Radioactivation.cc
References G4ITDecay::DecayIt(), G4DecayProducts::entries(), G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), G4RadioactiveDecayBase::photonEvaporation, and G4DecayProducts::PopProducts().
Referenced by DecayIt().
G4VParticleChange* G4Radioactivation::AtRestDoIt (const G4Track & theTrack, const G4Step & theStep) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 177 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 177 of file G4Radioactivation.hh
References DecayIt().
void G4Radioactivation::CalculateChainsFromParent (const G4ParticleDefinition & theParentNucleus)
Definition at line 342 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 342 of file G4Radioactivation.cc
References A(), kdfinder::abs(), allowed, chainsFromParent, E, e, G4DecayTable::entries(), G4cout, G4endl, G4Exception(), G4VDecayChannel::GetBR(), G4NuclearDecay::GetDaughterExcitation(), G4NuclearDecay::GetDaughterNucleus(), G4DecayTable::GetDecayChannel(), G4NuclearDecay::GetDecayMode(), GetDecayTable1(), G4NuclearLevelData::GetInstance(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4NuclearLevelData::GetLevelManager(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGLifeTime(), G4RadioactiveDecayBase::GetVerboseLevel(), halflifethreshold, G4DecayTable::Insert(), G4RadioactiveDecayBase::IsApplicable(), IT, JustWarning, k, G4RadioactiveDecayBase::levelTolerance, G4LevelManager::LifeTime(), MeV, G4LevelManager::NearestLevelEnergy(), G4LevelManager::NearestLevelIndex(), noFloat, ns, G4LevelManager::NumberOfTransitions(), G4RadioactiveDecayBase::photonEvaporation, ratesToDaughter, SetDecayRate(), G4RadioactiveDecayChainsFromParent::SetIonName(), G4RadioactiveDecayChainsFromParent::SetItsRates(), theDecayRateVector, theParentChainTable, and Z.
Referenced by DecayIt().
G4double G4Radioactivation::ConvolveSourceTimeProfile (const G4double t, const G4double tau) protected
Definition at line 198 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 198 of file G4Radioactivation.cc
References G4cout, G4endl, G4Exception(), G4RadioactiveDecayBase::GetVerboseLevel(), JustWarning, NSourceBin, SBin, and SProfile.
Referenced by DecayIt().
G4VParticleChange * G4Radioactivation::DecayIt (const G4Track & theTrack, const G4Step & theStep)
Definition at line 785 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 785 of file G4Radioactivation.cc
References AddDeexcitationSpectrumForBiasMode(), G4ParticleChangeForRadDecay::AddSecondary(), AnalogueMC, BRBias, CalculateChainsFromParent(), G4VProcess::ClearNumberOfInteractionLengthLeft(), ConvolveSourceTimeProfile(), DBin, G4RadioactiveDecayBase::DecayAnalog(), decayWindows, G4RadioactiveDecayBase::DoDecay(), DProfile, G4DecayTable::DumpInfo(), G4DecayTable::entries(), G4DecayProducts::entries(), G4RadioactiveDecayBase::fParticleChangeForRadDecay, fStopAndKill, G4cout, G4endl, G4UniformRand, GetChainsFromParent(), G4DecayTable::GetDecayChannel(), GetDecayTable1(), GetDecayTime(), GetDecayTimeBin(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4Track::GetLocalTime(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGStable(), G4Track::GetPosition(), G4Track::GetTouchableHandle(), G4RadioactiveDecayBase::GetVerboseLevel(), G4Track::GetVolume(), G4Track::GetWeight(), G4ParticleChangeForDecay::Initialize(), G4RadioactiveDecayBase::isAllVolumesMode, G4RadioactiveDecayBase::IsApplicable(), IsRateTableReady(), n, NSplit, G4DecayProducts::PopProducts(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForDecay::ProposeLocalTime(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), G4Track::SetGoodForTrackingFlag(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), theDecayRateVector, theRadioactivityTables, G4RadioactiveDecayBase::ValidVolumes, and weight.
Referenced by AtRestDoIt(), and PostStepDoIt().
void G4Radioactivation::GetChainsFromParent (const G4ParticleDefinition & aParticle)
Definition at line 173 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 173 of file G4Radioactivation.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4RadioactiveDecayBase::GetVerboseLevel(), theDecayRateVector, and theParentChainTable.
Referenced by DecayIt().
G4DecayTable * G4Radioactivation::GetDecayTable1 (const G4ParticleDefinition * aNucleus)
Definition at line 144 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 144 of file G4Radioactivation.cc
References G4RadioactiveDecayBase::dkmap, G4ParticleDefinition::GetParticleName(), and G4RadioactiveDecayBase::LoadDecayTable().
Referenced by CalculateChainsFromParent(), and DecayIt().
G4double G4Radioactivation::GetDecayTime () protected
Definition at line 260 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 260 of file G4Radioactivation.cc
References DBin, DProfile, G4cout, G4endl, G4Exception(), G4UniformRand, G4RadioactiveDecayBase::GetVerboseLevel(), and JustWarning.
Referenced by DecayIt().
G4int G4Radioactivation::GetDecayTimeBin (const G4double aDecayTime) protected
Definition at line 289 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 289 of file G4Radioactivation.cc
References DBin, G4Exception(), and JustWarning.
Referenced by DecayIt().
G4double G4Radioactivation::GetMeanLifeTime (const G4Track & theTrack, G4ForceCondition * condition) protected virtual
Implements G4VRestDiscreteProcess.
Definition at line 313 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 313 of file G4Radioactivation.cc
References AnalogueMC, and G4RadioactiveDecayBase::GetMeanLifeTime().
G4int G4Radioactivation::GetSplitNuclei () inline
Definition at line 128 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4Radioactivation.hh
References NSplit.
std::vector<G4RadioactivityTable*> G4Radioactivation::GetTheRadioactivityTables () inline
Definition at line 98 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Radioactivation.hh
References theRadioactivityTables.
Referenced by Run::WriteActivity().
G4bool G4Radioactivation::IsAnalogueMonteCarlo () inline
Definition at line 113 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4Radioactivation.hh
References AnalogueMC.
Referenced by Run::WriteActivity().
G4bool G4Radioactivation::IsRateTableReady (const G4ParticleDefinition & aParticle)
Definition at line 160 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 160 of file G4Radioactivation.cc
References G4ParticleDefinition::GetParticleName(), and theParentChainTable.
Referenced by DecayIt().
G4VParticleChange* G4Radioactivation::PostStepDoIt (const G4Track & theTrack, const G4Step & theStep) inline private virtual
Reimplemented from G4VRestDiscreteProcess.
Definition at line 181 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Radioactivation.hh
References DecayIt().
void G4Radioactivation::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4RadioactiveDecayBase.
Definition at line 127 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 127 of file G4Radioactivation.cc
void G4Radioactivation::SetAnalogueMonteCarlo (G4bool r) inline
Definition at line 106 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 106 of file G4Radioactivation.hh
References AnalogueMC, e, halflifethreshold, r, and CLHEP::s.
void G4Radioactivation::SetBRBias (G4bool r) inline
Definition at line 116 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 116 of file G4Radioactivation.hh
References AnalogueMC, BRBias, and r.
void G4Radioactivation::SetDecayBias (G4String filename)
Definition at line 726 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 726 of file G4Radioactivation.cc
References AnalogueMC, bin, DBin, decayWindows, DProfile, FatalException, G4cout, G4endl, G4Exception(), G4RadioactiveDecayBase::GetVerboseLevel(), in, JustWarning, NDecayBin, and theRadioactivityTables.
void G4Radioactivation::SetDecayRate (G4int theZ, G4int theA, G4double theE, G4int theG, std::vector< G4double > theCoefficients, std::vector< G4double > theTaos)
Definition at line 326 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 326 of file G4Radioactivation.cc
References ratesToDaughter, G4RadioactiveDecayRatesToDaughter::SetA(), G4RadioactiveDecayRatesToDaughter::SetDecayRateC(), G4RadioactiveDecayRatesToDaughter::SetE(), G4RadioactiveDecayRatesToDaughter::SetGeneration(), G4RadioactiveDecayRatesToDaughter::SetTaos(), and G4RadioactiveDecayRatesToDaughter::SetZ().
Referenced by CalculateChainsFromParent().
void G4Radioactivation::SetHLThreshold (G4double hl) inline
Definition at line 71 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Radioactivation.hh
References halflifethreshold.
void G4Radioactivation::SetSourceTimeProfile (G4String filename)
Definition at line 677 of file G4Radioactivation.cc.
View newest version in sPHENIX GitHub at line 677 of file G4Radioactivation.cc
References AnalogueMC, bin, FatalException, G4cout, G4endl, G4Exception(), G4RadioactiveDecayBase::GetVerboseLevel(), in, JustWarning, NSourceBin, SBin, and SProfile.
void G4Radioactivation::SetSplitNuclei (G4int r) inline
Definition at line 122 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 122 of file G4Radioactivation.hh
References AnalogueMC, NSplit, and r.
Member Data Documentation
G4bool G4Radioactivation::AnalogueMC private
Definition at line 154 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 154 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), GetMeanLifeTime(), IsAnalogueMonteCarlo(), SetAnalogueMonteCarlo(), SetBRBias(), SetDecayBias(), SetSourceTimeProfile(), and SetSplitNuclei().
G4bool G4Radioactivation::BRBias private
Definition at line 155 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 155 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), and SetBRBias().
G4RadioactiveDecayChainsFromParent G4Radioactivation::chainsFromParent private
Definition at line 169 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Radioactivation.hh
Referenced by CalculateChainsFromParent().
G4double G4Radioactivation::DBin[100] private
Definition at line 164 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 164 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), GetDecayTime(), GetDecayTimeBin(), and SetDecayBias().
G4int G4Radioactivation::decayWindows[100] private
Definition at line 174 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 174 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), and SetDecayBias().
G4double G4Radioactivation::DProfile[100] private
Definition at line 165 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 165 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), GetDecayTime(), and SetDecayBias().
G4double G4Radioactivation::halflifethreshold private
Definition at line 158 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 158 of file G4Radioactivation.hh
Referenced by CalculateChainsFromParent(), G4Radioactivation(), SetAnalogueMonteCarlo(), and SetHLThreshold().
G4int G4Radioactivation::NDecayBin private
Definition at line 163 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 163 of file G4Radioactivation.hh
Referenced by G4Radioactivation(), and SetDecayBias().
G4int G4Radioactivation::NSourceBin private
Definition at line 160 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 160 of file G4Radioactivation.hh
Referenced by ConvolveSourceTimeProfile(), G4Radioactivation(), and SetSourceTimeProfile().
G4int G4Radioactivation::NSplit private
Definition at line 156 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 156 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), GetSplitNuclei(), and SetSplitNuclei().
G4RadioactiveDecayRatesToDaughter G4Radioactivation::ratesToDaughter private
Definition at line 167 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 167 of file G4Radioactivation.hh
Referenced by CalculateChainsFromParent(), and SetDecayRate().
G4double G4Radioactivation::SBin[100] private
Definition at line 161 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 161 of file G4Radioactivation.hh
Referenced by ConvolveSourceTimeProfile(), G4Radioactivation(), and SetSourceTimeProfile().
G4double G4Radioactivation::SProfile[100] private
Definition at line 162 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 162 of file G4Radioactivation.hh
Referenced by ConvolveSourceTimeProfile(), G4Radioactivation(), and SetSourceTimeProfile().
G4RadioactiveDecayRates G4Radioactivation::theDecayRateVector private
Definition at line 168 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 168 of file G4Radioactivation.hh
Referenced by CalculateChainsFromParent(), DecayIt(), and GetChainsFromParent().
G4RadioactiveDecayParentChainTable G4Radioactivation::theParentChainTable private
Definition at line 170 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4Radioactivation.hh
Referenced by CalculateChainsFromParent(), GetChainsFromParent(), and IsRateTableReady().
G4RadioactivationMessenger* G4Radioactivation::theRadioactivationMessenger protected
Definition at line 150 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Radioactivation.hh
Referenced by G4Radioactivation(), and ~G4Radioactivation().
std::vector<G4RadioactivityTable*> G4Radioactivation::theRadioactivityTables private
Definition at line 173 of file G4Radioactivation.hh.
View newest version in sPHENIX GitHub at line 173 of file G4Radioactivation.hh
Referenced by DecayIt(), G4Radioactivation(), GetTheRadioactivityTables(), and SetDecayBias().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4Radioactivation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4Radioactivation.cc