ECCE @ EIC Software: G4INCL::Book Class Reference
G4INCL::Book Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLBook.hh>
Public Member Functions
Book ()
~Book ()
void reset ()
void incrementAcceptedCollisions ()
void incrementBlockedCollisions ()
void incrementAcceptedDecays ()
void incrementBlockedDecays ()
void incrementAvatars (AvatarType type)
void incrementCascading ()
void decrementCascading ()
void incrementEmittedClusters ()
void incrementEnergyViolationInteraction ()
void setFirstCollisionTime (const G4double t)
G4double getFirstCollisionTime () const
void setFirstCollisionXSec (const G4double x)
G4double getFirstCollisionXSec () const
void setFirstCollisionSpectatorPosition (const G4double x)
G4double getFirstCollisionSpectatorPosition () const
void setFirstCollisionSpectatorMomentum (const G4double x)
G4double getFirstCollisionSpectatorMomentum () const
void setFirstCollisionIsElastic (const G4bool e)
G4bool getFirstCollisionIsElastic () const
void setCurrentTime (G4double t)
G4double getCurrentTime () const
G4int getAcceptedCollisions () const
G4int getBlockedCollisions () const
G4int getAcceptedDecays () const
G4int getBlockedDecays () const
G4int getAvatars (AvatarType type) const
G4int getCascading () const
G4int getEmittedClusters () const
G4int getEnergyViolationInteraction () const
Private Attributes
G4int nAcceptedCollisions
G4int nBlockedCollisions
G4int nAcceptedDecays
G4int nBlockedDecays
G4double currentTime
G4double firstCollisionTime
G4double firstCollisionXSec
G4double firstCollisionSpectatorPosition
G4double firstCollisionSpectatorMomentum
G4bool firstCollisionIsElastic
std::map< AvatarType, G4int > nAvatars
G4int nCascading
G4int nEmittedClusters
G4int nEnergyViolationInteraction
Detailed Description
Definition at line 45 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 45 of file G4INCLBook.hh
Constructor & Destructor Documentation
G4INCL::Book::Book () inline
Definition at line 47 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLBook.hh
References reset().
G4INCL::Book::~Book () inline
Definition at line 50 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 50 of file G4INCLBook.hh
Member Function Documentation
void G4INCL::Book::decrementCascading () inline
Definition at line 78 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 78 of file G4INCLBook.hh
References nCascading.
Referenced by G4INCL::SurfaceAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
G4int G4INCL::Book::getAcceptedCollisions () const inline
Definition at line 100 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 100 of file G4INCLBook.hh
References nAcceptedCollisions.
Referenced by G4INCL::Nucleus::fillEventInfo(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::PauliStrictStandard::isBlocked(), G4INCL::Nucleus::isEventTransparent(), G4INCL::BinaryCollisionAvatar::postInteraction(), and G4INCL::InteractionAvatar::shouldUseLocalEnergy().
G4int G4INCL::Book::getAcceptedDecays () const inline
Definition at line 102 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 102 of file G4INCLBook.hh
References nAcceptedDecays.
Referenced by G4INCL::Nucleus::fillEventInfo(), and G4INCL::Nucleus::isEventTransparent().
G4int G4INCL::Book::getAvatars (AvatarType type) const inline
Definition at line 104 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 104 of file G4INCLBook.hh
References nAvatars.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4int G4INCL::Book::getBlockedCollisions () const inline
Definition at line 101 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 101 of file G4INCLBook.hh
References nBlockedCollisions.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4int G4INCL::Book::getBlockedDecays () const inline
Definition at line 103 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 103 of file G4INCLBook.hh
References nBlockedDecays.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4int G4INCL::Book::getCascading () const inline
Definition at line 105 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 105 of file G4INCLBook.hh
References nCascading.
Referenced by G4INCL::INCL::continueCascade().
G4double G4INCL::Book::getCurrentTime () const inline
Definition at line 98 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 98 of file G4INCLBook.hh
References currentTime.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::emitInsideKaon(), G4INCL::Nucleus::emitInsideLambda(), G4INCL::Nucleus::emitInsidePions(), G4INCL::Nucleus::emitInsideStrangeParticles(), and G4INCL::BinaryCollisionAvatar::postInteraction().
G4int G4INCL::Book::getEmittedClusters () const inline
Definition at line 106 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 106 of file G4INCLBook.hh
References nEmittedClusters.
Referenced by G4INCL::Nucleus::isEventTransparent().
G4int G4INCL::Book::getEnergyViolationInteraction () const inline
Definition at line 107 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 107 of file G4INCLBook.hh
Referenced by G4INCL::Nucleus::fillEventInfo().
G4bool G4INCL::Book::getFirstCollisionIsElastic () const inline
Definition at line 95 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 95 of file G4INCLBook.hh
References firstCollisionIsElastic.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4double G4INCL::Book::getFirstCollisionSpectatorMomentum () const inline
Definition at line 92 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 92 of file G4INCLBook.hh
References firstCollisionSpectatorMomentum.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4double G4INCL::Book::getFirstCollisionSpectatorPosition () const inline
Definition at line 89 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 89 of file G4INCLBook.hh
References firstCollisionSpectatorPosition.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4double G4INCL::Book::getFirstCollisionTime () const inline
Definition at line 83 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 83 of file G4INCLBook.hh
References firstCollisionTime.
Referenced by G4INCL::Nucleus::fillEventInfo().
G4double G4INCL::Book::getFirstCollisionXSec () const inline
Definition at line 86 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 86 of file G4INCLBook.hh
References firstCollisionXSec.
Referenced by G4INCL::Nucleus::fillEventInfo().
void G4INCL::Book::incrementAcceptedCollisions () inline
Definition at line 72 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLBook.hh
References nAcceptedCollisions.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Book::incrementAcceptedDecays () inline
Definition at line 74 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 74 of file G4INCLBook.hh
References nAcceptedDecays.
Referenced by G4INCL::DecayAvatar::postInteraction().
void G4INCL::Book::incrementAvatars (AvatarType type) inline
Definition at line 76 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 76 of file G4INCLBook.hh
References nAvatars.
Referenced by G4INCL::CascadeAction::beforeAvatarDefaultAction().
void G4INCL::Book::incrementBlockedCollisions () inline
Definition at line 73 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 73 of file G4INCLBook.hh
References nBlockedCollisions.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Book::incrementBlockedDecays () inline
Definition at line 75 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLBook.hh
References nBlockedDecays.
Referenced by G4INCL::DecayAvatar::postInteraction().
void G4INCL::Book::incrementCascading () inline
Definition at line 77 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 77 of file G4INCLBook.hh
References nCascading.
Referenced by G4INCL::Nucleus::insertParticle(), G4INCL::Store::loadParticles(), and G4INCL::InteractionAvatar::postInteraction().
void G4INCL::Book::incrementEmittedClusters () inline
Definition at line 79 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 79 of file G4INCLBook.hh
References nEmittedClusters.
Referenced by G4INCL::SurfaceAvatar::getChannel().
void G4INCL::Book::incrementEnergyViolationInteraction () inline
Definition at line 80 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 80 of file G4INCLBook.hh
References nEnergyViolationInteraction.
Referenced by G4INCL::InteractionAvatar::enforceEnergyConservation().
void G4INCL::Book::reset () inline
Definition at line 52 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 52 of file G4INCLBook.hh
References G4INCL::CollisionAvatarType, currentTime, G4INCL::DecayAvatarType, firstCollisionIsElastic, firstCollisionSpectatorMomentum, firstCollisionSpectatorPosition, firstCollisionTime, firstCollisionXSec, nAcceptedCollisions, nAcceptedDecays, nAvatars, nBlockedCollisions, nBlockedDecays, nCascading, nEmittedClusters, nEnergyViolationInteraction, G4INCL::ParticleEntryAvatarType, and G4INCL::SurfaceAvatarType.
Referenced by Book(), G4INCL::INCL::initializeTarget(), and G4INCL::Store::~Store().
void G4INCL::Book::setCurrentTime (G4double t) inline
Definition at line 97 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 97 of file G4INCLBook.hh
References currentTime, and t.
Referenced by G4INCL::StandardPropagationModel::propagate().
void G4INCL::Book::setFirstCollisionIsElastic (const G4bool e) inline
Definition at line 94 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 94 of file G4INCLBook.hh
References e, and firstCollisionIsElastic.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Book::setFirstCollisionSpectatorMomentum (const G4double x) inline
Definition at line 91 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 91 of file G4INCLBook.hh
References firstCollisionSpectatorMomentum, and x.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Book::setFirstCollisionSpectatorPosition (const G4double x) inline
Definition at line 88 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 88 of file G4INCLBook.hh
References firstCollisionSpectatorPosition, and x.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Book::setFirstCollisionTime (const G4double t) inline
Definition at line 82 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 82 of file G4INCLBook.hh
References firstCollisionTime, and t.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
void G4INCL::Book::setFirstCollisionXSec (const G4double x) inline
Definition at line 85 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 85 of file G4INCLBook.hh
References firstCollisionXSec, and x.
Referenced by G4INCL::BinaryCollisionAvatar::postInteraction().
Member Data Documentation
G4double G4INCL::Book::currentTime private
Definition at line 114 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 114 of file G4INCLBook.hh
Referenced by getCurrentTime(), reset(), and setCurrentTime().
G4bool G4INCL::Book::firstCollisionIsElastic private
Definition at line 119 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 119 of file G4INCLBook.hh
Referenced by getFirstCollisionIsElastic(), reset(), and setFirstCollisionIsElastic().
G4double G4INCL::Book::firstCollisionSpectatorMomentum private
Definition at line 118 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 118 of file G4INCLBook.hh
Referenced by getFirstCollisionSpectatorMomentum(), reset(), and setFirstCollisionSpectatorMomentum().
G4double G4INCL::Book::firstCollisionSpectatorPosition private
Definition at line 117 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 117 of file G4INCLBook.hh
Referenced by getFirstCollisionSpectatorPosition(), reset(), and setFirstCollisionSpectatorPosition().
G4double G4INCL::Book::firstCollisionTime private
Definition at line 115 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 115 of file G4INCLBook.hh
Referenced by getFirstCollisionTime(), reset(), and setFirstCollisionTime().
G4double G4INCL::Book::firstCollisionXSec private
Definition at line 116 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 116 of file G4INCLBook.hh
Referenced by getFirstCollisionXSec(), reset(), and setFirstCollisionXSec().
G4int G4INCL::Book::nAcceptedCollisions private
Definition at line 107 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 107 of file G4INCLBook.hh
Referenced by getAcceptedCollisions(), incrementAcceptedCollisions(), and reset().
G4int G4INCL::Book::nAcceptedDecays private
Definition at line 112 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 112 of file G4INCLBook.hh
Referenced by getAcceptedDecays(), incrementAcceptedDecays(), and reset().
std::map<AvatarType,G4int> G4INCL::Book::nAvatars private
Definition at line 120 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 120 of file G4INCLBook.hh
Referenced by getAvatars(), incrementAvatars(), and reset().
G4int G4INCL::Book::nBlockedCollisions private
Definition at line 111 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 111 of file G4INCLBook.hh
Referenced by getBlockedCollisions(), incrementBlockedCollisions(), and reset().
G4int G4INCL::Book::nBlockedDecays private
Definition at line 113 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 113 of file G4INCLBook.hh
Referenced by getBlockedDecays(), incrementBlockedDecays(), and reset().
G4int G4INCL::Book::nCascading private
Definition at line 121 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 121 of file G4INCLBook.hh
Referenced by decrementCascading(), getCascading(), incrementCascading(), and reset().
G4int G4INCL::Book::nEmittedClusters private
Definition at line 122 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 122 of file G4INCLBook.hh
Referenced by getEmittedClusters(), incrementEmittedClusters(), and reset().
G4int G4INCL::Book::nEnergyViolationInteraction private
Definition at line 123 of file G4INCLBook.hh.
View newest version in sPHENIX GitHub at line 123 of file G4INCLBook.hh
Referenced by incrementEnergyViolationInteraction(), and reset().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLBook.hh