ECCE @ EIC Software: G4ParticleHPFissionBaseFS Class Reference
G4ParticleHPFissionBaseFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionBaseFS.hh>
Classes
struct toBeCached
Public Member Functions
G4ParticleHPFissionBaseFS ()
virtual ~G4ParticleHPFissionBaseFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &bit, G4ParticleDefinition *)
G4DynamicParticleVector * ApplyYourself (G4int Prompt)
virtual G4double GetXsec (G4double anEnergy)
virtual G4ParticleHPVector * GetXsec ()
void SetNeutronRP (const G4ReactionProduct &aNeutron)
void SetTarget (const G4ReactionProduct &aTarget)
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
virtual G4ParticleHPFinalState * New ()=0
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Member Functions
G4HadFinalState * ApplyYourself (const G4HadProjectile &)
Private Attributes
G4ParticleHPVector * theXsection
G4ParticleHPEnergyDistribution theEnergyDistribution
G4ParticleHPAngular theAngularDistribution
G4Cache< toBeCached > fCache
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 42 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPFissionBaseFS.hh
Constructor & Destructor Documentation
G4ParticleHPFissionBaseFS::G4ParticleHPFissionBaseFS () inline
Definition at line 53 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPFissionBaseFS.hh
References G4ParticleHPFinalState::hasXsec, and theXsection.
virtual G4ParticleHPFissionBaseFS::~G4ParticleHPFissionBaseFS () inline virtual
Definition at line 59 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleHPFissionBaseFS.hh
References theXsection.
Member Function Documentation
G4DynamicParticleVector * G4ParticleHPFissionBaseFS::ApplyYourself (G4int Prompt)
Definition at line 96 of file G4ParticleHPFissionBaseFS.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPFissionBaseFS.cc
References fCache, G4Cache< VALTYPE >::Get(), G4ReactionProduct::GetKineticEnergy(), G4ParticleHPFinalState::HasFSData(), it, G4ReactionProduct::Lorentz(), G4Neutron::Neutron(), G4ParticleHPEnergyDistribution::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4DynamicParticle::SetMomentum(), theAngularDistribution, and theEnergyDistribution.
Referenced by G4ParticleHPFCFissionFS::ApplyYourself(), G4ParticleHPTCFissionFS::ApplyYourself(), G4ParticleHPSCFissionFS::ApplyYourself(), G4ParticleHPLCFissionFS::ApplyYourself(), and G4ParticleHPFFFissionFS::ApplyYourself().
G4HadFinalState* G4ParticleHPFissionBaseFS::ApplyYourself (const G4HadProjectile &) inline private virtual
Reimplemented from G4ParticleHPFinalState.
Reimplemented in G4ParticleHPLCFissionFS, G4ParticleHPSCFissionFS, and G4ParticleHPTCFissionFS.
Definition at line 93 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPFissionBaseFS.hh
virtual G4double G4ParticleHPFissionBaseFS::GetXsec (G4double anEnergy) inline virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 69 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPFissionBaseFS.hh
References G4ParticleHPVector::GetY(), max, and theXsection.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
virtual G4ParticleHPVector* G4ParticleHPFissionBaseFS::GetXsec () inline virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 74 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleHPFissionBaseFS.hh
References theXsection.
void G4ParticleHPFissionBaseFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & bit, G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Reimplemented in G4ParticleHPLCFissionFS, G4ParticleHPSCFissionFS, and G4ParticleHPTCFissionFS.
Definition at line 45 of file G4ParticleHPFissionBaseFS.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPFissionBaseFS.cc
References kdfinder::abs(), eV, INPUTHEPMC::filename, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPFinalState::hasAnyData, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPEnergyDistribution::Init(), G4ParticleHPAngular::Init(), G4ParticleHPVector::Init(), G4ParticleHPFinalState::SetAZMs(), theAngularDistribution, theEnergyDistribution, G4ParticleHPFinalState::theNames, G4ParticleHPFinalState::theNDLDataA, G4ParticleHPFinalState::theNDLDataZ, theXsection, and G4INCL::CrossSections::total().
Referenced by G4ParticleHPFCFissionFS::Init(), G4ParticleHPTCFissionFS::Init(), G4ParticleHPSCFissionFS::Init(), and G4ParticleHPLCFissionFS::Init().
void G4ParticleHPFissionBaseFS::SetNeutronRP (const G4ReactionProduct & aNeutron) inline
Definition at line 79 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPFissionBaseFS.hh
References fCache, G4Cache< VALTYPE >::Get(), G4ParticleHPAngular::SetProjectileRP(), and theAngularDistribution.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
void G4ParticleHPFissionBaseFS::SetTarget (const G4ReactionProduct & aTarget) inline
Definition at line 85 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPFissionBaseFS.hh
References fCache, G4Cache< VALTYPE >::Get(), G4ParticleHPAngular::SetTarget(), and theAngularDistribution.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
Member Data Documentation
G4Cache<toBeCached> G4ParticleHPFissionBaseFS::fCache private
Definition at line 99 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPFissionBaseFS.hh
Referenced by ApplyYourself(), SetNeutronRP(), and SetTarget().
G4ParticleHPAngular G4ParticleHPFissionBaseFS::theAngularDistribution private
Definition at line 97 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPFissionBaseFS.hh
Referenced by ApplyYourself(), Init(), SetNeutronRP(), and SetTarget().
G4ParticleHPEnergyDistribution G4ParticleHPFissionBaseFS::theEnergyDistribution private
Definition at line 96 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPFissionBaseFS.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPVector* G4ParticleHPFissionBaseFS::theXsection private
Definition at line 95 of file G4ParticleHPFissionBaseFS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPFissionBaseFS.hh
Referenced by G4ParticleHPFissionBaseFS(), GetXsec(), Init(), and ~G4ParticleHPFissionBaseFS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionBaseFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPFissionBaseFS.cc