ECCE @ EIC Software: GFlashShowerModel Class Reference
GFlashShowerModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashShowerModel.hh>
Public Member Functions
GFlashShowerModel (G4String, G4Envelope *)
GFlashShowerModel (G4String)
~GFlashShowerModel ()
G4bool ModelTrigger (const G4FastTrack &)
G4bool IsApplicable (const G4ParticleDefinition &)
void DoIt (const G4FastTrack &, G4FastStep &)
void SetFlagParamType (G4int I)
void SetFlagParticleContainment (G4int I)
void SetStepInX0 (G4double Lenght)
void SetParameterisation (GVFlashShowerParameterisation &DP)
void SetHitMaker (GFlashHitMaker &Maker)
void SetParticleBounds (GFlashParticleBounds &SpecificBound)
G4int GetFlagParamType ()
G4int GetFlagParticleContainment ()
G4double GetStepInX0 ()
Public Member Functions inherited from G4VFastSimulationModel
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Public Attributes
GFlashParticleBounds * PBound
GVFlashShowerParameterisation * Parameterisation
Private Member Functions
void ElectronDoIt (const G4FastTrack &, G4FastStep &)
G4bool CheckParticleDefAndContainment (const G4FastTrack &fastTrack)
G4bool CheckContainment (const G4FastTrack &fastTrack)
Private Attributes
GFlashHitMaker * HMaker
GFlashShowerModelMessenger * Messenger
G4int FlagParamType
G4int FlagParticleContainment
0=no GFlash 1=only em showers parametrized
G4double StepInX0
0=no check ///1=only fully contained...
G4double EnergyStop
Detailed Description
Definition at line 59 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 59 of file GFlashShowerModel.hh
Constructor & Destructor Documentation
GFlashShowerModel::GFlashShowerModel (G4String modelName, G4Envelope * envelope)
Definition at line 56 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 56 of file GFlashShowerModel.cc
References FlagParamType, FlagParticleContainment, Messenger, and StepInX0.
GFlashShowerModel::GFlashShowerModel (G4String modelName)
Definition at line 67 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 67 of file GFlashShowerModel.cc
References FlagParamType, FlagParticleContainment, Messenger, and StepInX0.
GFlashShowerModel::~GFlashShowerModel ()
Definition at line 77 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 77 of file GFlashShowerModel.cc
References Messenger.
Member Function Documentation
G4bool GFlashShowerModel::CheckContainment (const G4FastTrack & fastTrack) private
Definition at line 137 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 137 of file GFlashShowerModel.cc
References CLHEP::Hep3Vector::cross(), filter, GVFlashShowerParameterisation::GetAveR90(), GVFlashShowerParameterisation::GetAveT90(), G4FastTrack::GetEnvelopeSolid(), G4FastTrack::GetPrimaryTrackLocalDirection(), G4FastTrack::GetPrimaryTrackLocalPosition(), G4VSolid::Inside(), kOutside, CLHEP::Hep3Vector::orthogonal(), Parameterisation, Acts::IntegrationTest::R, and Z.
Referenced by CheckParticleDefAndContainment().
G4bool GFlashShowerModel::CheckParticleDefAndContainment (const G4FastTrack & fastTrack) private
Definition at line 119 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 119 of file GFlashShowerModel.cc
References CheckContainment(), G4Electron::ElectronDefinition(), filter, FlagParticleContainment, G4Track::GetDefinition(), G4FastTrack::GetPrimaryTrack(), and G4Positron::PositronDefinition().
Referenced by ModelTrigger().
void GFlashShowerModel::DoIt (const G4FastTrack & fastTrack, G4FastStep & fastStep) virtual
Implements G4VFastSimulationModel.
Definition at line 179 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 179 of file GFlashShowerModel.cc
References G4Electron::ElectronDefinition(), ElectronDoIt(), G4Track::GetDefinition(), G4FastTrack::GetPrimaryTrack(), and G4Positron::PositronDefinition().
void GFlashShowerModel::ElectronDoIt (const G4FastTrack & fastTrack, G4FastStep & fastStep) private
Generate longitudinal profile
Initialisation of long. loop variables
Begin Longitudinal Loop
End Loop
Definition at line 190 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 190 of file GFlashShowerModel.cc
References GFlashSamplingShowerParameterisation::ApplySampling(), CLHEP::Hep3Vector::cross(), dir, G4VSolid::DistanceToOut(), Dz, EnergyStop, GVFlashShowerParameterisation::GenerateLongitudinalProfile(), GVFlashShowerParameterisation::GeneratePhi(), GVFlashShowerParameterisation::GenerateRadius(), G4FastTrack::GetEnvelopeSolid(), G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), GVFlashShowerParameterisation::GetNspot(), G4Track::GetPosition(), G4FastTrack::GetPrimaryTrack(), G4FastTrack::GetPrimaryTrackLocalDirection(), G4FastTrack::GetPrimaryTrackLocalPosition(), GVFlashShowerParameterisation::GetX0(), HMaker, GVFlashShowerParameterisation::IntegrateEneLongitudinal(), GVFlashShowerParameterisation::IntegrateNspLongitudinal(), G4FastStep::KillPrimaryTrack(), GFlashHitMaker::make(), max, min, CLHEP::Hep3Vector::orthogonal(), Parameterisation, pos(), GFlashEnergySpot::SetEnergy(), GFlashEnergySpot::SetPosition(), G4FastStep::SetPrimaryTrackPathLength(), G4FastStep::SetTotalEnergyDeposited(), G4InuclParticleNames::sp, and StepInX0.
Referenced by DoIt().
G4int GFlashShowerModel::GetFlagParamType () inline
Definition at line 90 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 90 of file GFlashShowerModel.hh
References FlagParamType.
Referenced by GFlashShowerModelMessenger::GetCurrentValue().
G4int GFlashShowerModel::GetFlagParticleContainment () inline
Definition at line 92 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 92 of file GFlashShowerModel.hh
References FlagParticleContainment.
G4double GFlashShowerModel::GetStepInX0 () inline
Definition at line 94 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 94 of file GFlashShowerModel.hh
References StepInX0.
G4bool GFlashShowerModel::IsApplicable (const G4ParticleDefinition & particleType) virtual
Implements G4VFastSimulationModel.
Definition at line 83 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 83 of file GFlashShowerModel.cc
References G4Electron::ElectronDefinition(), and G4Positron::PositronDefinition().
G4bool GFlashShowerModel::ModelTrigger (const G4FastTrack & fastTrack) virtual
Implements G4VFastSimulationModel.
Definition at line 94 of file GFlashShowerModel.cc.
View newest version in sPHENIX GitHub at line 94 of file GFlashShowerModel.cc
References CheckParticleDefAndContainment(), EnergyStop, FlagParamType, GVFlashShowerParameterisation::GenerateLongitudinalProfile(), G4Track::GetDefinition(), GFlashParticleBounds::GetEneToKill(), G4Track::GetKineticEnergy(), GFlashParticleBounds::GetMaxEneToParametrise(), GFlashParticleBounds::GetMinEneToParametrise(), G4FastTrack::GetPrimaryTrack(), Parameterisation, and PBound.
void GFlashShowerModel::SetFlagParamType (G4int I) inline
Definition at line 75 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 75 of file GFlashShowerModel.hh
References FlagParamType.
Referenced by GFlashShowerModelMessenger::SetNewValue().
void GFlashShowerModel::SetFlagParticleContainment (G4int I) inline
Definition at line 77 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 77 of file GFlashShowerModel.hh
References FlagParticleContainment.
Referenced by GFlashShowerModelMessenger::SetNewValue().
void GFlashShowerModel::SetHitMaker (GFlashHitMaker & Maker) inline
Definition at line 83 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 83 of file GFlashShowerModel.hh
References HMaker.
Referenced by ExGflash2ParallelWorld::ConstructSD(), ExGflash1DetectorConstruction::ConstructSDandField(), ExGflash3DetectorConstruction::ConstructSDandField(), and ExGflashDetectorConstruction::ConstructSDandField().
void GFlashShowerModel::SetParameterisation (GVFlashShowerParameterisation & DP) inline
Definition at line 81 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 81 of file GFlashShowerModel.hh
References Parameterisation.
Referenced by ExGflash2ParallelWorld::ConstructSD(), ExGflash1DetectorConstruction::ConstructSDandField(), ExGflash3DetectorConstruction::ConstructSDandField(), and ExGflashDetectorConstruction::ConstructSDandField().
void GFlashShowerModel::SetParticleBounds (GFlashParticleBounds & SpecificBound) inline
Definition at line 85 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 85 of file GFlashShowerModel.hh
References PBound.
Referenced by ExGflash2ParallelWorld::ConstructSD(), ExGflash1DetectorConstruction::ConstructSDandField(), ExGflash3DetectorConstruction::ConstructSDandField(), and ExGflashDetectorConstruction::ConstructSDandField().
void GFlashShowerModel::SetStepInX0 (G4double Lenght) inline
Definition at line 79 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 79 of file GFlashShowerModel.hh
References StepInX0.
Referenced by GFlashShowerModelMessenger::SetNewValue().
Member Data Documentation
G4double GFlashShowerModel::EnergyStop private
Definition at line 120 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 120 of file GFlashShowerModel.hh
Referenced by ElectronDoIt(), and ModelTrigger().
G4int GFlashShowerModel::FlagParamType private
Definition at line 117 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 117 of file GFlashShowerModel.hh
Referenced by GetFlagParamType(), GFlashShowerModel(), ModelTrigger(), and SetFlagParamType().
G4int GFlashShowerModel::FlagParticleContainment private
0=no GFlash 1=only em showers parametrized
Definition at line 118 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 118 of file GFlashShowerModel.hh
Referenced by CheckParticleDefAndContainment(), GetFlagParticleContainment(), GFlashShowerModel(), and SetFlagParticleContainment().
GFlashHitMaker* GFlashShowerModel::HMaker private
Definition at line 113 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 113 of file GFlashShowerModel.hh
Referenced by ElectronDoIt(), and SetHitMaker().
GFlashShowerModelMessenger* GFlashShowerModel::Messenger private
Definition at line 114 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 114 of file GFlashShowerModel.hh
Referenced by GFlashShowerModel(), and ~GFlashShowerModel().
GVFlashShowerParameterisation* GFlashShowerModel::Parameterisation
Definition at line 101 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 101 of file GFlashShowerModel.hh
Referenced by CheckContainment(), ElectronDoIt(), ModelTrigger(), and SetParameterisation().
GFlashParticleBounds* GFlashShowerModel::PBound
Definition at line 100 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 100 of file GFlashShowerModel.hh
Referenced by GFlashShowerModelMessenger::GetCurrentValue(), ModelTrigger(), GFlashShowerModelMessenger::SetNewValue(), and SetParticleBounds().
G4double GFlashShowerModel::StepInX0 private
0=no check ///1=only fully contained...
Definition at line 119 of file GFlashShowerModel.hh.
View newest version in sPHENIX GitHub at line 119 of file GFlashShowerModel.hh
Referenced by ElectronDoIt(), GetStepInX0(), GFlashShowerModel(), and SetStepInX0().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashShowerModel.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/GFlashShowerModel.cc