ECCE @ EIC Software: G4AntiBarionBuilder Class Reference
G4AntiBarionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4AntiBarionBuilder.hh>
Public Member Functions
G4AntiBarionBuilder ()
virtual ~G4AntiBarionBuilder ()
virtual void Build () finaloverride
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4AntiProtonInelasticProcess * theAntiProtonInelastic
G4AntiNeutronInelasticProcess * theAntiNeutronInelastic
G4AntiDeuteronInelasticProcess * theAntiDeuteronInelastic
G4AntiTritonInelasticProcess * theAntiTritonInelastic
G4AntiHe3InelasticProcess * theAntiHe3Inelastic
G4AntiAlphaInelasticProcess * theAntiAlphaInelastic
std::vector
< G4VAntiBarionBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 48 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 48 of file G4AntiBarionBuilder.hh
Constructor & Destructor Documentation
G4AntiBarionBuilder::G4AntiBarionBuilder ()
Definition at line 44 of file G4AntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4AntiBarionBuilder.cc
References theAntiAlphaInelastic, theAntiDeuteronInelastic, theAntiHe3Inelastic, theAntiNeutronInelastic, theAntiProtonInelastic, and theAntiTritonInelastic.
virtual G4AntiBarionBuilder::~G4AntiBarionBuilder () inline virtual
Definition at line 52 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4AntiBarionBuilder.hh
Member Function Documentation
void G4AntiBarionBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 56 of file G4AntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 56 of file G4AntiBarionBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4AntiAlpha::AntiAlpha(), G4AntiDeuteron::AntiDeuteron(), G4AntiHe3::AntiHe3(), G4AntiNeutron::AntiNeutron(), G4AntiProton::AntiProton(), G4AntiTriton::AntiTriton(), G4ParticleDefinition::GetProcessManager(), theAntiAlphaInelastic, theAntiDeuteronInelastic, theAntiHe3Inelastic, theAntiNeutronInelastic, theAntiProtonInelastic, theAntiTritonInelastic, theModelCollections, and wasActivated.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), and G4HadronPhysicsQGSP_BIC_HP::ConstructProcess().
void G4AntiBarionBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 90 of file G4AntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 90 of file G4AntiBarionBuilder.cc
References G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
Member Data Documentation
G4AntiAlphaInelasticProcess* G4AntiBarionBuilder::theAntiAlphaInelastic private
Definition at line 63 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4AntiBarionBuilder.hh
Referenced by Build(), and G4AntiBarionBuilder().
G4AntiDeuteronInelasticProcess* G4AntiBarionBuilder::theAntiDeuteronInelastic private
Definition at line 60 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4AntiBarionBuilder.hh
Referenced by Build(), and G4AntiBarionBuilder().
G4AntiHe3InelasticProcess* G4AntiBarionBuilder::theAntiHe3Inelastic private
Definition at line 62 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4AntiBarionBuilder.hh
Referenced by Build(), and G4AntiBarionBuilder().
G4AntiNeutronInelasticProcess* G4AntiBarionBuilder::theAntiNeutronInelastic private
Definition at line 59 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4AntiBarionBuilder.hh
Referenced by Build(), and G4AntiBarionBuilder().
G4AntiProtonInelasticProcess* G4AntiBarionBuilder::theAntiProtonInelastic private
Definition at line 58 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4AntiBarionBuilder.hh
Referenced by Build(), and G4AntiBarionBuilder().
G4AntiTritonInelasticProcess* G4AntiBarionBuilder::theAntiTritonInelastic private
Definition at line 61 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AntiBarionBuilder.hh
Referenced by Build(), and G4AntiBarionBuilder().
std::vector<G4VAntiBarionBuilder *> G4AntiBarionBuilder::theModelCollections private
Definition at line 65 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4AntiBarionBuilder.hh
Referenced by Build(), and RegisterMe().
G4bool G4AntiBarionBuilder::wasActivated private
Definition at line 67 of file G4AntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4AntiBarionBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4AntiBarionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4AntiBarionBuilder.cc