ECCE @ EIC Software: G4StatMFFragment Class Reference
G4StatMFFragment Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFFragment.hh>
Public Member Functions
G4StatMFFragment (G4int anA, G4int aZ)
virtual ~G4StatMFFragment ()
G4bool operator== (const G4StatMFFragment &right) const
G4bool operator!= (const G4StatMFFragment &right) const
G4double GetCoulombEnergy (void) const
G4double GetEnergy (const G4double T) const
G4double GetInvLevelDensity (void) const
G4int GetA (void) const
G4int GetZ (void) const
void SetPosition (const G4ThreeVector &aPosition)
G4ThreeVector & GetPosition (void)
void SetMomentum (const G4ThreeVector &aMomentum)
G4ThreeVector & GetMomentum (void)
G4Fragment * GetFragment (const G4double T)
G4double GetNuclearMass (void)
Private Member Functions
G4StatMFFragment ()
G4StatMFFragment (const G4StatMFFragment &right)
G4StatMFFragment & operator= (const G4StatMFFragment &right)
G4double CalcExcitationEnergy (const G4double T)
Private Attributes
G4int theA
G4int theZ
G4ThreeVector _position
G4ThreeVector _momentum
Detailed Description
Definition at line 40 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 40 of file G4StatMFFragment.hh
Constructor & Destructor Documentation
G4StatMFFragment::G4StatMFFragment (G4int anA, G4int aZ) inline
Definition at line 44 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 44 of file G4StatMFFragment.hh
virtual G4StatMFFragment::~G4StatMFFragment () inline virtual
Definition at line 52 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 52 of file G4StatMFFragment.hh
G4StatMFFragment::G4StatMFFragment () inline private
Definition at line 57 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 57 of file G4StatMFFragment.hh
G4StatMFFragment::G4StatMFFragment (const G4StatMFFragment & right) private
Definition at line 37 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 37 of file G4StatMFFragment.cc
Member Function Documentation
G4double G4StatMFFragment::CalcExcitationEnergy (const G4double T) private
Definition at line 114 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 114 of file G4StatMFFragment.cc
References kdfinder::abs(), G4StatMFParameters::Beta(), G4StatMFParameters::DBetaDT(), e, G4StatMFParameters::GetBeta0(), G4Pow::GetInstance(), GetInvLevelDensity(), theA, and G4Pow::Z23().
Referenced by GetFragment().
G4int G4StatMFFragment::GetA (void) const inline
Definition at line 76 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 76 of file G4StatMFFragment.hh
References theA.
G4double G4StatMFFragment::GetCoulombEnergy (void) const
Definition at line 63 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 63 of file G4StatMFFragment.cc
References G4StatMFParameters::GetCoulomb(), and theZ.
Referenced by GetEnergy().
G4double G4StatMFFragment::GetEnergy (const G4double T) const
Definition at line 72 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 72 of file G4StatMFFragment.cc
References G4StatMFParameters::DBetaDT(), G4cout, G4endl, G4StatMFParameters::GetBeta0(), GetCoulombEnergy(), G4StatMFParameters::GetCriticalTemp(), G4Pow::GetInstance(), GetInvLevelDensity(), G4NucleiProperties::GetMassExcess(), theA, theZ, and G4Pow::Z23().
G4Fragment * G4StatMFFragment::GetFragment (const G4double T)
Definition at line 105 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 105 of file G4StatMFFragment.cc
References _momentum, CalcExcitationEnergy(), GetNuclearMass(), CLHEP::Hep3Vector::mag2(), theA, and theZ.
G4double G4StatMFFragment::GetInvLevelDensity (void) const
Definition at line 96 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 96 of file G4StatMFFragment.cc
References G4StatMFParameters::GetEpsilon0(), and theA.
Referenced by CalcExcitationEnergy(), and GetEnergy().
G4ThreeVector& G4StatMFFragment::GetMomentum (void) inline
Definition at line 86 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 86 of file G4StatMFFragment.hh
References _momentum.
G4double G4StatMFFragment::GetNuclearMass (void) inline
Definition at line 90 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 90 of file G4StatMFFragment.hh
References G4IonTable::GetIonMass(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), theA, and theZ.
Referenced by GetFragment().
G4ThreeVector& G4StatMFFragment::GetPosition (void) inline
Definition at line 82 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 82 of file G4StatMFFragment.hh
References _position.
G4int G4StatMFFragment::GetZ (void) const inline
Definition at line 78 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 78 of file G4StatMFFragment.hh
References theZ.
G4bool G4StatMFFragment::operator!= (const G4StatMFFragment & right) const
Definition at line 57 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 57 of file G4StatMFFragment.cc
G4StatMFFragment & G4StatMFFragment::operator= (const G4StatMFFragment & right) private
Definition at line 45 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 45 of file G4StatMFFragment.cc
G4bool G4StatMFFragment::operator== (const G4StatMFFragment & right) const
Definition at line 51 of file G4StatMFFragment.cc.
View newest version in sPHENIX GitHub at line 51 of file G4StatMFFragment.cc
void G4StatMFFragment::SetMomentum (const G4ThreeVector & aMomentum) inline
Definition at line 84 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 84 of file G4StatMFFragment.hh
References _momentum.
void G4StatMFFragment::SetPosition (const G4ThreeVector & aPosition) inline
Definition at line 80 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 80 of file G4StatMFFragment.hh
References _position.
Member Data Documentation
G4ThreeVector G4StatMFFragment::_momentum private
Definition at line 107 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 107 of file G4StatMFFragment.hh
Referenced by GetFragment(), GetMomentum(), and SetMomentum().
G4ThreeVector G4StatMFFragment::_position private
Definition at line 105 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 105 of file G4StatMFFragment.hh
Referenced by GetPosition(), and SetPosition().
G4int G4StatMFFragment::theA private
Definition at line 101 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 101 of file G4StatMFFragment.hh
Referenced by CalcExcitationEnergy(), GetA(), GetEnergy(), GetFragment(), GetInvLevelDensity(), and GetNuclearMass().
G4int G4StatMFFragment::theZ private
Definition at line 103 of file G4StatMFFragment.hh.
View newest version in sPHENIX GitHub at line 103 of file G4StatMFFragment.hh
Referenced by GetCoulombEnergy(), GetEnergy(), GetFragment(), GetNuclearMass(), and GetZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFFragment.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFFragment.cc