ECCE @ EIC Software: G4VCollision Class Reference
G4VCollision Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VCollision.hh>
Public Member Functions
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual G4String GetName () const =0
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
G4int GetNumberOfPartons (const G4ParticleDefinition *aP) const
virtual const G4CollisionVector * GetComponents () const
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const =0
virtual const
G4VAngularDistribution * GetAngularDistribution () const =0
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const =0
Private Member Functions
G4VCollision (const G4VCollision &right)
const G4VCollision & operator= (const G4VCollision &right)
Detailed Description
Definition at line 39 of file G4VCollision.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VCollision.hh
Constructor & Destructor Documentation
G4VCollision::G4VCollision ()
Definition at line 34 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VCollision.cc
G4VCollision::G4VCollision (void * s1, void * s2, void * s3, void * s4, void * s5, void * s6, void * s7)
Definition at line 142 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 142 of file G4VCollision.cc
G4VCollision::~G4VCollision () virtual
Definition at line 37 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VCollision.cc
G4VCollision::G4VCollision (const G4VCollision & right) private
Member Function Documentation
G4double G4VCollision::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Reimplemented in G4CollisionComposite, G4CollisionMesonBaryonToResonance, and G4CollisionNN.
Definition at line 54 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VCollision.cc
References G4VCrossSectionSource::CrossSection(), and GetCrossSectionSource().
Referenced by G4Scatterer::GetCrossSection(), G4Scatterer::GetTimeToInteraction(), Print(), and G4Scatterer::Scatter().
void G4VCollision::establish_G4MT_TLS_G4VCollision ()
Definition at line 143 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 143 of file G4VCollision.cc
Referenced by G4VScatteringCollision::establish_G4MT_TLS_G4VScatteringCollision().
virtual G4KineticTrackVector* G4VCollision::FinalState (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const pure virtual
Implemented in G4CollisionComposite, G4VAnnihilationCollision, G4VScatteringCollision, and G4VElasticCollision.
Referenced by G4Scatterer::Scatter().
virtual const G4VAngularDistribution* G4VCollision::GetAngularDistribution () const protected pure virtual
Implemented in G4CollisionComposite, G4CollisionPN, G4VAnnihilationCollision, G4VScatteringCollision, G4CollisionMesonBaryonElastic, G4CollisionNNElastic, G4CollisionnpElastic, and G4CollisionNN.
Referenced by G4VElasticCollision::FinalState().
virtual const G4CollisionVector* G4VCollision::GetComponents () const inline protected virtual
Reimplemented in G4CollisionComposite, G4CollisionNN, G4CollisionNNToDeltaDelta1700, G4CollisionNNToDeltaDelta1600, G4CollisionNNToDeltaDelta1620, G4CollisionNNToNDelta1620, G4CollisionNNToNDelta1700, G4CollisionNNToNDelta1900, G4CollisionNNToNDelta1905, G4CollisionNNToNDelta1910, G4CollisionNNToNDelta1920, G4CollisionNNToNDelta1930, G4CollisionNNToNDelta1950, G4CollisionNNToDeltaDelta1900, G4CollisionNNToDeltaDelta1905, G4CollisionNNToDeltaDelta1910, G4CollisionNNToDeltaDelta1920, G4CollisionNNToDeltaDelta1930, G4CollisionNNToDeltaDelta1950, G4CollisionNNToNDelta, and G4CollisionNNToNDelta1600.
Definition at line 79 of file G4VCollision.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VCollision.hh
Referenced by Print().
virtual const G4VCrossSectionSource* G4VCollision::GetCrossSectionSource () const protected pure virtual
Implemented in G4ConcreteMesonBaryonToResonance, G4ConcreteNNTwoBodyResonance, G4CollisionComposite, G4CollisionPN, G4CollisionNNElastic, G4CollisionnpElastic, G4CollisionMesonBaryonElastic, and G4CollisionNN.
Referenced by CrossSection(), and Print().
virtual const std::vector<G4String>& G4VCollision::GetListOfColliders (G4int whichOne) const protected pure virtual
Implemented in G4CollisionMesonBaryonToResonance, G4CollisionPN, G4CollisionMesonBaryon, G4CollisionNN, G4CollisionNNElastic, G4CollisionnpElastic, G4CollisionMesonBaryonElastic, G4ConcreteNNTwoBodyResonance, G4ConcreteMesonBaryonToResonance, G4CollisionNNToNNstar, G4CollisionNStarNToNN, G4CollisionNNToNDeltastar, G4CollisionNNToDeltaDelta, G4CollisionNNToDeltaDeltastar, G4CollisionNNToDeltaNstar, G4CollisionNNToDeltaDelta1600, G4CollisionNNToDeltaDelta1620, G4CollisionNNToDeltaDelta1700, G4CollisionNNToDeltaDelta1900, G4CollisionNNToDeltaDelta1905, G4CollisionNNToDeltaDelta1910, G4CollisionNNToDeltaDelta1920, G4CollisionNNToDeltaDelta1930, G4CollisionNNToDeltaDelta1950, G4CollisionNNToNDelta, G4CollisionNNToNDelta1600, G4CollisionNNToNDelta1620, G4CollisionNNToNDelta1700, G4CollisionNNToNDelta1900, G4CollisionNNToNDelta1905, G4CollisionNNToNDelta1910, G4CollisionNNToNDelta1920, G4CollisionNNToNDelta1930, and G4CollisionNNToNDelta1950.
virtual G4String G4VCollision::GetName () const pure virtual
Implemented in G4ConcreteNNTwoBodyResonance, G4ConcreteMesonBaryonToResonance, G4CollisionPN, G4CollisionMesonBaryon, G4CollisionMesonBaryonToResonance, G4CollisionNNElastic, G4CollisionnpElastic, G4ConcreteNNToDeltaDelta, G4CollisionMesonBaryonElastic, G4CollisionNN, G4ConcreteNNToDeltaDeltastar, G4ConcreteNNToDeltaNstar, G4ConcreteNNToNDelta, G4ConcreteNNToNDeltaStar, G4ConcreteNNToNNStar, G4ConcreteNStarNToNN, G4CollisionNNToNNstar, G4CollisionNStarNToNN, G4CollisionNNToDeltaDeltastar, G4CollisionNNToNDeltastar, G4CollisionNNToDeltaDelta, G4CollisionNNToDeltaNstar, G4CollisionNNToDeltaDelta1600, G4CollisionNNToDeltaDelta1620, G4CollisionNNToDeltaDelta1700, G4CollisionNNToDeltaDelta1900, G4CollisionNNToDeltaDelta1905, G4CollisionNNToDeltaDelta1910, G4CollisionNNToDeltaDelta1920, G4CollisionNNToDeltaDelta1930, G4CollisionNNToDeltaDelta1950, G4CollisionNNToNDelta, G4CollisionNNToNDelta1600, G4CollisionNNToNDelta1620, G4CollisionNNToNDelta1700, G4CollisionNNToNDelta1900, G4CollisionNNToNDelta1905, G4CollisionNNToNDelta1910, G4CollisionNNToNDelta1920, G4CollisionNNToNDelta1930, and G4CollisionNNToNDelta1950.
Referenced by Print().
G4int G4VCollision::GetNumberOfPartons (const G4ParticleDefinition * aP) const inline protected
Definition at line 68 of file G4VCollision.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VCollision.hh
References G4ParticleDefinition::GetAntiQuarkContent(), and G4ParticleDefinition::GetQuarkContent().
Referenced by G4CollisionMesonBaryonElastic::IsInCharge().
virtual G4bool G4VCollision::IsInCharge (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const pure virtual
Implemented in G4CollisionComposite, G4ConcreteNNTwoBodyResonance, G4ConcreteMesonBaryonToResonance, G4CollisionMesonBaryonElastic, G4CollisionNNElastic, G4CollisionnpElastic, and G4GeneralNNCollision.
Referenced by G4Scatterer::FindCollision(), and Print().
G4bool G4VCollision::operator!= (const G4VCollision & right) const
Definition at line 48 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VCollision.cc
const G4VCollision& G4VCollision::operator= (const G4VCollision & right) private
G4bool G4VCollision::operator== (const G4VCollision & right) const
Definition at line 42 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 42 of file G4VCollision.cc
void G4VCollision::Print (void) const virtual
Definition at line 70 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 70 of file G4VCollision.cc
References components, G4cout, G4endl, GetComponents(), GetCrossSectionSource(), GetName(), and G4VCrossSectionSource::Print().
Referenced by Print().
void G4VCollision::Print (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Definition at line 101 of file G4VCollision.cc.
View newest version in sPHENIX GitHub at line 101 of file G4VCollision.cc
References components, CrossSection(), G4cout, G4endl, GetComponents(), GetCrossSectionSource(), GetName(), IsInCharge(), G4VCrossSectionSource::Print(), and Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VCollision.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4VCollision.cc