ECCE @ EIC Software: macros/blob/master/common/G4_B0ECAL.C File Reference
G4_B0ECAL.C File Reference
#include <GlobalVariables.C>
#include <eicg4b0ecal/B0RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <eicg4b0ecal/EICG4B0ECALSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <eiccaloreco/RawClusterBuilderkMA.h>
#include <eiccaloreco/RawClusterBuilderHelper.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4B0ECAL
Macros
#define MACRO_G4B0ECAL_C
Functions
void B0ECALInit ()
void B0ECALSetup (PHG4Reco *g4Reco)
void B0ECAL_Cells (int verbosity=0)
void B0ECAL_Towers ()
void B0ECAL_Clusters ()
void B0ECAL_Eval (const std::string &outputfile)
Variables
bool Enable::B0ECAL = false
bool Enable::B0ECAL_ABSORBER = false
bool Enable::B0ECAL_CELL = false
bool Enable::B0ECAL_TOWER = false
bool Enable::B0ECAL_CLUSTER = false
bool Enable::B0ECAL_EVAL = false
bool Enable::B0ECAL_OVERLAPCHECK = false
int Enable::B0ECAL_VERBOSITY = 0
double G4B0ECAL::minz = 678
double G4B0ECAL::maxz = 698
double G4B0ECAL::radius = 20
RawTowerDigitizer::enu_digi_algorithm G4B0ECAL::TowerDigi = RawTowerDigitizer::kNo_digitization
Macro Definition Documentation
#define MACRO_G4B0ECAL_C
Definition at line 2 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 2 of file G4_B0ECAL.C
Function Documentation
void B0ECAL_Cells (int verbosity = 0)
Definition at line 79 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 79 of file G4_B0ECAL.C
void B0ECAL_Clusters ()
Definition at line 117 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 117 of file G4_B0ECAL.C
References Enable::B0ECAL_VERBOSITY, RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void B0ECAL_Eval (const std::string & outputfile)
Definition at line 131 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 131 of file G4_B0ECAL.C
References Enable::B0ECAL_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void B0ECAL_Towers ()
Definition at line 84 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 84 of file G4_B0ECAL.C
References Enable::B0ECAL_VERBOSITY, RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), B0RawTowerBuilderByHitIndex::Detector(), B0RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), B0RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void B0ECALInit ()
Definition at line 70 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 70 of file G4_B0ECAL.C
Referenced by G4Init().
void B0ECALSetup (PHG4Reco * g4Reco)
Definition at line 74 of file G4_B0ECAL.C.
View newest version in sPHENIX GitHub at line 74 of file G4_B0ECAL.C