ECCE @ EIC Software: G4LEPTSDistribution Class Reference
G4LEPTSDistribution Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4LEPTSDistribution.hh>
Public Member Functions
G4LEPTSDistribution ()
void ReadFile (G4String fileName)
G4bool ReadFile (FILE *fp, G4int nData)
G4double Sample (G4double, G4double)
G4bool IsFileFound () const
Private Attributes
int NoBins
G4double E [NMAX]
G4double f [NMAX]
G4double F [NMAX]
G4double eF [NMAX]
G4bool bFileFound
Detailed Description
Definition at line 36 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 36 of file G4LEPTSDistribution.hh
Constructor & Destructor Documentation
G4LEPTSDistribution::G4LEPTSDistribution ()
Definition at line 29 of file G4LEPTSDistribution.cc.
View newest version in sPHENIX GitHub at line 29 of file G4LEPTSDistribution.cc
Member Function Documentation
G4bool G4LEPTSDistribution::IsFileFound () const inline
Definition at line 45 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 45 of file G4LEPTSDistribution.hh
References bFileFound.
void G4LEPTSDistribution::ReadFile (G4String fileName)
Definition at line 34 of file G4LEPTSDistribution.cc.
View newest version in sPHENIX GitHub at line 34 of file G4LEPTSDistribution.cc
References bFileFound, E, eF, f, F, fclose(), fp, NMAX, NoBins, printf(), and sum.
Referenced by G4LEPTSElossDistr::ReadFile().
G4bool G4LEPTSDistribution::ReadFile (FILE * fp, G4int nData)
Definition at line 98 of file G4LEPTSDistribution.cc.
View newest version in sPHENIX GitHub at line 98 of file G4LEPTSDistribution.cc
References bFileFound, E, eF, F, f, NMAX, NoBins, printf(), and sum.
G4double G4LEPTSDistribution::Sample (G4double eMin, G4double eMax)
Definition at line 158 of file G4LEPTSDistribution.cc.
View newest version in sPHENIX GitHub at line 158 of file G4LEPTSDistribution.cc
References E, F, G4UniformRand, k, and NoBins.
Referenced by G4LEPTSElossDistr::Sample().
Member Data Documentation
G4bool G4LEPTSDistribution::bFileFound private
Definition at line 53 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 53 of file G4LEPTSDistribution.hh
Referenced by IsFileFound(), and ReadFile().
G4double G4LEPTSDistribution::E[NMAX] private
Definition at line 52 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LEPTSDistribution.hh
Referenced by ReadFile(), and Sample().
G4double G4LEPTSDistribution::eF[NMAX] private
Definition at line 52 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LEPTSDistribution.hh
Referenced by ReadFile().
G4double G4LEPTSDistribution::F[NMAX] private
Definition at line 52 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LEPTSDistribution.hh
Referenced by ReadFile(), and Sample().
G4double G4LEPTSDistribution::f[NMAX] private
Definition at line 52 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LEPTSDistribution.hh
Referenced by ReadFile().
int G4LEPTSDistribution::NoBins private
Definition at line 50 of file G4LEPTSDistribution.hh.
View newest version in sPHENIX GitHub at line 50 of file G4LEPTSDistribution.hh
Referenced by ReadFile(), and Sample().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4LEPTSDistribution.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4LEPTSDistribution.cc