ECCE @ EIC Software: CexmcEnergyDepositDigitizerMessenger Class Reference
CexmcEnergyDepositDigitizerMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEnergyDepositDigitizerMessenger.hh>
Public Member Functions
CexmcEnergyDepositDigitizerMessenger (CexmcEnergyDepositDigitizer *energyDepositDigitiser)
~CexmcEnergyDepositDigitizerMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CexmcEnergyDepositDigitizer * energyDepositDigitizer
G4UIcmdWithADoubleAndUnit * setMonitorThreshold
G4UIcmdWithADoubleAndUnit * setVetoCountersThreshold
G4UIcmdWithADoubleAndUnit * setLeftVetoCounterThreshold
G4UIcmdWithADoubleAndUnit * setRightVetoCounterThreshold
G4UIcmdWithADoubleAndUnit * setCalorimetersThreshold
G4UIcmdWithADoubleAndUnit * setLeftCalorimeterThreshold
G4UIcmdWithADoubleAndUnit * setRightCalorimeterThreshold
G4UIcmdWithAString * setCalorimeterTriggerAlgorithm
G4UIcmdWithAString * setOuterCrystalsVetoAlgorithm
G4UIcmdWithADouble * setOuterCrystalsVetoFraction
G4UIcmdWithABool * applyFiniteCrystalResolution
G4UIcmdWith3Vector * addCrystalResolutionRange
G4UIcmdWithoutParameter * clearCrystalResolutionData
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 59 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file CexmcEnergyDepositDigitizerMessenger.hh
Constructor & Destructor Documentation
CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger (CexmcEnergyDepositDigitizer * energyDepositDigitiser) explicit
Definition at line 56 of file CexmcEnergyDepositDigitizerMessenger.cc.
View newest version in sPHENIX GitHub at line 56 of file CexmcEnergyDepositDigitizerMessenger.cc
References addCrystalResolutionRange, applyFiniteCrystalResolution, G4UIcommand::AvailableForStates(), CexmcMessenger::calorimeterEDDirName, CexmcMessenger::calorimeterLeftEDDirName, CexmcMessenger::calorimeterRightEDDirName, clearCrystalResolutionData, CexmcMessenger::detectorDirName, G4State_Idle, G4State_PreInit, CexmcMessenger::monitorEDDirName, setCalorimetersThreshold, setCalorimeterTriggerAlgorithm, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), setLeftCalorimeterThreshold, setLeftVetoCounterThreshold, setMonitorThreshold, setOuterCrystalsVetoAlgorithm, setOuterCrystalsVetoFraction, G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), setRightCalorimeterThreshold, setRightVetoCounterThreshold, G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), setVetoCountersThreshold, CexmcMessenger::vetoCounterEDDirName, CexmcMessenger::vetoCounterLeftEDDirName, and CexmcMessenger::vetoCounterRightEDDirName.
CexmcEnergyDepositDigitizerMessenger::~CexmcEnergyDepositDigitizerMessenger ()
Definition at line 238 of file CexmcEnergyDepositDigitizerMessenger.cc.
View newest version in sPHENIX GitHub at line 238 of file CexmcEnergyDepositDigitizerMessenger.cc
References addCrystalResolutionRange, applyFiniteCrystalResolution, clearCrystalResolutionData, setCalorimetersThreshold, setCalorimeterTriggerAlgorithm, setLeftCalorimeterThreshold, setLeftVetoCounterThreshold, setMonitorThreshold, setOuterCrystalsVetoAlgorithm, setOuterCrystalsVetoFraction, setRightCalorimeterThreshold, setRightVetoCounterThreshold, and setVetoCountersThreshold.
Member Function Documentation
void CexmcEnergyDepositDigitizerMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 256 of file CexmcEnergyDepositDigitizerMessenger.cc.
View newest version in sPHENIX GitHub at line 256 of file CexmcEnergyDepositDigitizerMessenger.cc
References addCrystalResolutionRange, CexmcEnergyDepositDigitizer::AddCrystalResolutionRange(), applyFiniteCrystalResolution, CexmcEnergyDepositDigitizer::ApplyFiniteCrystalResolution(), CexmcAllCrystalsMakeEDTriggerThreshold, CexmcFractionOfEDInOuterCrystalsVeto, CexmcInnerCrystalsMakeEDTriggerThreshold, CexmcMaximumEDInASingleOuterCrystalVeto, CexmcNoOuterCrystalsVeto, clearCrystalResolutionData, CexmcEnergyDepositDigitizer::ClearCrystalResolutionData(), energyDepositDigitizer, G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), max, min, CexmcEnergyDepositDigitizer::SetCalorimeterLeftThreshold(), CexmcEnergyDepositDigitizer::SetCalorimeterRightThreshold(), setCalorimetersThreshold, CexmcEnergyDepositDigitizer::SetCalorimetersThreshold(), setCalorimeterTriggerAlgorithm, CexmcEnergyDepositDigitizer::SetCalorimeterTriggerAlgorithm(), setLeftCalorimeterThreshold, setLeftVetoCounterThreshold, setMonitorThreshold, CexmcEnergyDepositDigitizer::SetMonitorThreshold(), setOuterCrystalsVetoAlgorithm, CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoAlgorithm(), setOuterCrystalsVetoFraction, CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoFraction(), setRightCalorimeterThreshold, setRightVetoCounterThreshold, CexmcEnergyDepositDigitizer::SetVetoCounterLeftThreshold(), CexmcEnergyDepositDigitizer::SetVetoCounterRightThreshold(), setVetoCountersThreshold, CexmcEnergyDepositDigitizer::SetVetoCountersThreshold(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4UIcmdWith3Vector* CexmcEnergyDepositDigitizerMessenger::addCrystalResolutionRange private
Definition at line 95 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 95 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithABool* CexmcEnergyDepositDigitizerMessenger::applyFiniteCrystalResolution private
Definition at line 93 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithoutParameter* CexmcEnergyDepositDigitizerMessenger::clearCrystalResolutionData private
Definition at line 97 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 97 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
CexmcEnergyDepositDigitizer* CexmcEnergyDepositDigitizerMessenger::energyDepositDigitizer private
Definition at line 71 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setCalorimetersThreshold private
Definition at line 81 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithAString* CexmcEnergyDepositDigitizerMessenger::setCalorimeterTriggerAlgorithm private
Definition at line 87 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setLeftCalorimeterThreshold private
Definition at line 83 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setLeftVetoCounterThreshold private
Definition at line 77 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setMonitorThreshold private
Definition at line 73 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithAString* CexmcEnergyDepositDigitizerMessenger::setOuterCrystalsVetoAlgorithm private
Definition at line 89 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADouble* CexmcEnergyDepositDigitizerMessenger::setOuterCrystalsVetoFraction private
Definition at line 91 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setRightCalorimeterThreshold private
Definition at line 85 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setRightVetoCounterThreshold private
Definition at line 79 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
G4UIcmdWithADoubleAndUnit* CexmcEnergyDepositDigitizerMessenger::setVetoCountersThreshold private
Definition at line 75 of file CexmcEnergyDepositDigitizerMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file CexmcEnergyDepositDigitizerMessenger.hh
Referenced by CexmcEnergyDepositDigitizerMessenger(), SetNewValue(), and ~CexmcEnergyDepositDigitizerMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEnergyDepositDigitizerMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcEnergyDepositDigitizerMessenger.cc