ECCE @ EIC Software: G4GeometryCell Class Reference
G4GeometryCell Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4GeometryCell.hh>
Public Member Functions
G4GeometryCell (const G4VPhysicalVolume &aVolume, G4int RepNum)
G4GeometryCell (const G4GeometryCell &rhs)
G4GeometryCell & operator= (const G4GeometryCell &rhs)
~G4GeometryCell ()
const G4VPhysicalVolume & GetPhysicalVolume () const
G4int GetReplicaNumber () const
Private Attributes
const G4VPhysicalVolume * fVPhysicalVolume = nullptr
G4int fRepNum = 0
Detailed Description
Definition at line 44 of file G4GeometryCell.hh.
View newest version in sPHENIX GitHub at line 44 of file G4GeometryCell.hh
Constructor & Destructor Documentation
G4GeometryCell::G4GeometryCell (const G4VPhysicalVolume & aVolume, G4int RepNum)
Definition at line 33 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 33 of file G4GeometryCell.cc
G4GeometryCell::G4GeometryCell (const G4GeometryCell & rhs)
Definition at line 53 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 53 of file G4GeometryCell.cc
G4GeometryCell::~G4GeometryCell ()
Definition at line 38 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 38 of file G4GeometryCell.cc
Member Function Documentation
const G4VPhysicalVolume & G4GeometryCell::GetPhysicalVolume (void) const
Definition at line 42 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 42 of file G4GeometryCell.cc
References fVPhysicalVolume.
Referenced by G4IStore::AddImportanceGeometryCell(), G4IStore::ChangeImportance(), B02ImportanceDetectorConstruction::CreateImportanceStore(), B02ImportanceDetectorConstruction::CreateWeightWindowStore(), G4WeightWindowStore::IsKnown(), G4IStore::IsKnown(), main(), operator!=(), G4GeometryCellComp::operator()(), operator<<(), and operator==().
G4int G4GeometryCell::GetReplicaNumber () const
Definition at line 47 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 47 of file G4GeometryCell.cc
References fRepNum.
Referenced by B02ImportanceDetectorConstruction::CreateImportanceStore(), B02ImportanceDetectorConstruction::CreateWeightWindowStore(), main(), operator!=(), G4GeometryCellComp::operator()(), operator<<(), and operator==().
G4GeometryCell & G4GeometryCell::operator= (const G4GeometryCell & rhs)
Definition at line 58 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 58 of file G4GeometryCell.cc
References fRepNum, and fVPhysicalVolume.
Member Data Documentation
G4int G4GeometryCell::fRepNum = 0 private
Definition at line 69 of file G4GeometryCell.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GeometryCell.hh
Referenced by GetReplicaNumber(), and operator=().
const G4VPhysicalVolume* G4GeometryCell::fVPhysicalVolume = nullptr private
Definition at line 66 of file G4GeometryCell.hh.
View newest version in sPHENIX GitHub at line 66 of file G4GeometryCell.hh
Referenced by GetPhysicalVolume(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4GeometryCell.hh
geant4/tree/geant4-10.6-release/source/geometry/biasing/src/G4GeometryCell.cc