ECCE @ EIC Software: G4VMultiBodyMomDst Class Reference
G4VMultiBodyMomDst Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4VMultiBodyMomDst.hh>
Public Member Functions
G4VMultiBodyMomDst (const G4String &name, G4int verbose=0)
virtual ~G4VMultiBodyMomDst ()
virtual G4double GetMomentum (G4int ptype, const G4double &ekin) const =0
virtual void setVerboseLevel (G4int verbose=0)
virtual const G4String & GetName () const
Protected Attributes
G4String theName
G4int verboseLevel
Detailed Description
Definition at line 40 of file G4VMultiBodyMomDst.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VMultiBodyMomDst.hh
Constructor & Destructor Documentation
G4VMultiBodyMomDst::G4VMultiBodyMomDst (const G4String & name, G4int verbose = 0)
Definition at line 34 of file G4VMultiBodyMomDst.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VMultiBodyMomDst.cc
References G4cout, G4endl, theName, and verboseLevel.
virtual G4VMultiBodyMomDst::~G4VMultiBodyMomDst () inline virtual
Definition at line 43 of file G4VMultiBodyMomDst.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VMultiBodyMomDst.hh
Member Function Documentation
virtual G4double G4VMultiBodyMomDst::GetMomentum (G4int ptype, const G4double & ekin) const pure virtual
Implemented in G4InuclParamMomDst.
Referenced by G4CascadeFinalStateAlgorithm::FillMagnitudes().
virtual const G4String& G4VMultiBodyMomDst::GetName (void) const inline virtual
Definition at line 48 of file G4VMultiBodyMomDst.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VMultiBodyMomDst.hh
References theName.
Referenced by G4CascadeFinalStateAlgorithm::ChooseGenerators().
virtual void G4VMultiBodyMomDst::setVerboseLevel (G4int verbose = 0) inline virtual
Definition at line 47 of file G4VMultiBodyMomDst.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VMultiBodyMomDst.hh
References verboseLevel.
Referenced by G4MultiBodyMomentumDist::passVerbose().
Member Data Documentation
G4String G4VMultiBodyMomDst::theName protected
Definition at line 51 of file G4VMultiBodyMomDst.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VMultiBodyMomDst.hh
Referenced by G4VMultiBodyMomDst(), and GetName().
G4int G4VMultiBodyMomDst::verboseLevel protected
Definition at line 52 of file G4VMultiBodyMomDst.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VMultiBodyMomDst.hh
Referenced by G4VMultiBodyMomDst(), and setVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4VMultiBodyMomDst.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4VMultiBodyMomDst.cc