ECCE @ EIC Software: G4ProcessManager Class Reference
G4ProcessManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessManager.hh>
Public Types
enum { SizeOfProcVectorArray = 6 }
Public Member Functions
G4ProcessManager (G4ProcessManager &right)
G4ProcessManager (const G4ParticleDefinition *aParticleType)
~G4ProcessManager ()
G4bool operator== (const G4ProcessManager &right) const
G4bool operator!= (const G4ProcessManager &right) const
G4ProcessVector * GetProcessList () const
G4int GetProcessListLength () const
G4int GetProcessIndex (G4VProcess *) const
G4ProcessVector * GetProcessVector (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4ProcessVector * GetAtRestProcessVector (G4ProcessVectorTypeIndex typ=typeGPIL) const
G4ProcessVector * GetAlongStepProcessVector (G4ProcessVectorTypeIndex typ=typeGPIL) const
G4ProcessVector * GetPostStepProcessVector (G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetProcessVectorIndex (G4VProcess *aProcess, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetAtRestIndex (G4VProcess *aProcess, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetAlongStepIndex (G4VProcess *aProcess, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int GetPostStepIndex (G4VProcess *aProcess, G4ProcessVectorTypeIndex typ=typeGPIL) const
G4int AddProcess (G4VProcess *aProcess, G4int ordAtRestDoIt=ordInActive, G4int ordAlongSteptDoIt=ordInActive, G4int ordPostStepDoIt=ordInActive)
G4int AddRestProcess (G4VProcess *aProcess, G4int ord=ordDefault)
G4int AddDiscreteProcess (G4VProcess *aProcess, G4int ord=ordDefault)
G4int AddContinuousProcess (G4VProcess *aProcess, G4int ord=ordDefault)
G4int GetProcessOrdering (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
void SetProcessOrdering (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt, G4int ordDoIt=ordDefault)
void SetProcessOrderingToFirst (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
void SetProcessOrderingToSecond (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
void SetProcessOrderingToLast (G4VProcess *aProcess, G4ProcessVectorDoItIndex idDoIt)
G4VProcess * RemoveProcess (G4VProcess *aProcess)
G4VProcess * RemoveProcess (G4int index)
G4VProcess * SetProcessActivation (G4VProcess *aProcess, G4bool fActive)
G4VProcess * SetProcessActivation (G4int index, G4bool fActive)
G4bool GetProcessActivation (G4VProcess *aProcess) const
G4bool GetProcessActivation (G4int index) const
G4ParticleDefinition * GetParticleType () const
void SetParticleType (const G4ParticleDefinition *)
G4VProcess * GetProcess (const G4String &) const
void StartTracking (G4Track *aTrack=0)
void EndTracking ()
void DumpInfo ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Protected Member Functions
G4int InsertAt (G4int position, G4VProcess *process, G4int ivec)
G4int RemoveAt (G4int position, G4VProcess *process, G4int ivec)
G4int FindInsertPosition (G4int ord, G4int ivec)
G4int GetProcessVectorId (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL) const
void CheckOrderingParameters (G4VProcess *) const
Protected Attributes
G4int verboseLevel
Private Types
typedef std::vector
< G4ProcessAttribute * > G4ProcessAttrVector
Private Member Functions
G4ProcessManager & operator= (const G4ProcessManager &right)
G4ProcessManager ()
G4ProcessAttribute * GetAttribute (G4int index) const
G4ProcessAttribute * GetAttribute (G4VProcess *aProcess) const
G4VProcess * ActivateProcess (G4int index)
G4VProcess * InActivateProcess (G4int index)
void CreateGPILvectors ()
void SetIndexToProcessVector (G4int ivec)
Private Attributes
G4ProcessVector * theProcVector [SizeOfProcVectorArray]
G4ProcessAttrVector * theAttrVector
const G4ParticleDefinition * theParticleType
G4int numberOfProcesses
G4ProcessVector * theProcessList
G4bool duringTracking
G4bool isSetOrderingFirstInvoked [NDoit]
G4bool isSetOrderingLastInvoked [NDoit]
Static Private Attributes
static G4ThreadLocal
G4ProcessManagerMessenger * fProcessManagerMessenger = 0
static G4ThreadLocal G4int counterOfObjects = 0
Detailed Description
Definition at line 95 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ProcessManager.hh
Member Typedef Documentation
typedef std::vector<G4ProcessAttribute*> G4ProcessManager::G4ProcessAttrVector private
Definition at line 293 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 293 of file G4ProcessManager.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
SizeOfProcVectorArray
Definition at line 288 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 288 of file G4ProcessManager.hh
Constructor & Destructor Documentation
G4ProcessManager::G4ProcessManager (G4ProcessManager & right)
Definition at line 99 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ProcessManager.cc
References counterOfObjects, G4ProcessVector::entries(), FatalException, G4cout, G4endl, G4Exception(), G4ProcessTable::GetProcessTable(), GetVerboseLevel(), incremental_prev_tag::idx, G4ProcessVector::insert(), G4ProcessTable::Insert(), isSetOrderingFirstInvoked, isSetOrderingLastInvoked, NDoit, numberOfProcesses, SizeOfProcVectorArray, theAttrVector, theProcessList, and theProcVector.
G4ProcessManager::G4ProcessManager () private
Definition at line 171 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4ProcessManager.cc
References G4Exception(), isSetOrderingFirstInvoked, isSetOrderingLastInvoked, JustWarning, NDoit, SizeOfProcVectorArray, and theProcVector.
G4ProcessManager::G4ProcessManager (const G4ParticleDefinition * aParticleType)
Definition at line 52 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ProcessManager.cc
References counterOfObjects, FatalException, fProcessManagerMessenger, G4Exception(), isSetOrderingFirstInvoked, isSetOrderingLastInvoked, NDoit, SizeOfProcVectorArray, theAttrVector, theProcessList, and theProcVector.
G4ProcessManager::~G4ProcessManager ()
Definition at line 205 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 205 of file G4ProcessManager.cc
References G4ProcessVector::clear(), counterOfObjects, fProcessManagerMessenger, G4cout, G4endl, GetVerboseLevel(), SizeOfProcVectorArray, theAttrVector, theProcessList, and theProcVector.
Member Function Documentation
G4VProcess * G4ProcessManager::ActivateProcess (G4int index) private
Definition at line 1036 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1036 of file G4ProcessManager.cc
References G4ProcessVector::entries(), FatalException, G4cout, G4endl, G4Exception(), G4State_Init, G4State_PreInit, GetAttribute(), G4StateManager::GetCurrentState(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4StateManager::GetStateManager(), GetVerboseLevel(), incremental_prev_tag::idx, G4ProcessAttribute::idxProcVector, G4ProcessAttribute::isActive, SizeOfProcVectorArray, theParticleType, and theProcVector.
Referenced by RemoveProcess(), and SetProcessActivation().
G4int G4ProcessManager::AddContinuousProcess (G4VProcess * aProcess, G4int ord = ordDefault)
Referenced by G4ErrorPhysicsList::ConstructEM(), and export_G4ProcessManager().
G4int G4ProcessManager::AddDiscreteProcess (G4VProcess * aProcess, G4int ord = ordDefault)
Referenced by G4EmModelActivator::ActivateMicroElec(), G4IonPhysicsXS::AddProcess(), G4IonPhysics::AddProcess(), G4IonPhysicsPHP::AddProcess(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), F04PhysicsList::AddStepMax(), HadrontherapyPhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), PhysicsList::AddStepMax(), ML2PhysicsList::AddStepMax(), ExN02PhysicsList::AddStepMax(), IORTPhysicsList::AddStepMax(), DMXPhysicsList::AddTransportation(), LBE::AddTransportation(), G4AlphaBuilder::Build(), G4He3Builder::Build(), G4DeuteronBuilder::Build(), G4PionBuilder::Build(), G4TritonBuilder::Build(), G4AntiBarionBuilder::Build(), G4BertiniElectroNuclearBuilder::Build(), G4PiKBuilder::Build(), G4KaonBuilder::Build(), G4ProtonBuilder::Build(), G4NeutronBuilder::Build(), G4HyperonFTFPBuilder::Build(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), PhysicsList::ConstructHighEnergy(), DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), XPhysicsList::ConstructProcess(), G4ChannelingPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), GammaNuclearPhysics::ConstructProcess(), StepMaxBuilder::ConstructProcess(), NeutronHPphysics::ConstructProcess(), PhysListEmStandard::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), MuNuclearBuilder::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), StepLimiterBuilder::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), TransitionRadiationPhysics::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), CexmcStudiedPhysics< Process >::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructUCN(), export_G4ProcessManager(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4VHadronPhysics::FindFissionProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmModelActivator::FindOrAddProcess(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), PHG4Reco::InitRun(), and G4RunManagerKernel::SetScoreSplitter().
G4int G4ProcessManager::AddProcess (G4VProcess * aProcess, G4int ordAtRestDoIt = ordInActive, G4int ordAlongSteptDoIt = ordInActive, G4int ordPostStepDoIt = ordInActive)
Definition at line 452 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 452 of file G4ProcessManager.cc
References CheckOrderingParameters(), CreateGPILvectors(), G4ProcessVector::entries(), FatalException, FindInsertPosition(), G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4ProcessTable::GetProcessTable(), GetVerboseLevel(), incremental_prev_tag::idx, G4ProcessAttribute::idxProcessList, G4ProcessAttribute::idxProcVector, G4ProcessVector::insert(), G4ProcessTable::Insert(), InsertAt(), G4VProcess::IsApplicable(), numberOfProcesses, G4ProcessAttribute::ordProcVector, G4ProcessVector::removeLast(), G4VProcess::SetProcessManager(), SizeOfProcVectorArray, theAttrVector, theParticleType, theProcessList, and verboseLevel.
Referenced by G4FastSimulationHelper::ActivateFastSimulation(), G4BiasingHelper::ActivateNonPhysicsBiasing(), G4BiasingHelper::ActivatePhysicsBiasing(), PhysicsList::AddDarkMatter(), XrayFluoPhysicsList::AddDecay(), G4BiasingHelper::AddLimiterProcess(), Par02PhysicsList::AddParameterisation(), G4ProcessPlacer::AddProcessAs(), B03PhysicsList::AddScoringProcess(), G4PhysicsListHelper::AddTransportation(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), PhysListEmStandard::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), G4ParallelWorldPhysics::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), F04PhysicsList::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), export_G4ProcessManager(), PHG4Reco::InitRun(), and G4PhysicsListHelper::RegisterProcess().
G4int G4ProcessManager::AddRestProcess (G4VProcess * aProcess, G4int ord = ordDefault)
Referenced by DMXPhysicsList::ConstructHad(), AntiBaryonPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), F04PhysicsList::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), and export_G4ProcessManager().
void G4ProcessManager::CheckOrderingParameters (G4VProcess * aProcess) const protected
Definition at line 1288 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1288 of file G4ProcessManager.cc
References FatalException, G4cerr, G4cout, G4endl, G4Exception(), GetAttribute(), G4VProcess::GetProcessName(), GetVerboseLevel(), G4VProcess::isAlongStepDoItIsEnabled(), G4VProcess::isAtRestDoItIsEnabled(), G4VProcess::isPostStepDoItIsEnabled(), and G4ProcessAttribute::ordProcVector.
Referenced by AddProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
void G4ProcessManager::CreateGPILvectors () private
Definition at line 1182 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1182 of file G4ProcessManager.cc
References G4ProcessVector::clear(), G4ProcessVector::entries(), GetAttribute(), G4ProcessAttribute::idxProcVector, G4ProcessVector::insert(), k, SizeOfProcVectorArray, theProcessList, and theProcVector.
Referenced by AddProcess(), RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
void G4ProcessManager::DumpInfo ()
Definition at line 1124 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1124 of file G4ProcessManager.cc
References G4ProcessVector::entries(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessTypeName(), incremental_prev_tag::idx, G4ProcessAttribute::idxProcVector, G4ProcessAttribute::ordProcVector, theParticleType, theProcessList, and verboseLevel.
Referenced by G4ProcessTable::DumpInfo(), export_G4ProcessManager(), and G4ProcessManagerMessenger::SetNewValue().
void G4ProcessManager::EndTracking ()
Definition at line 1222 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1222 of file G4ProcessManager.cc
References duringTracking, G4ProcessVector::entries(), GetAttribute(), incremental_prev_tag::idx, G4ProcessAttribute::isActive, and theProcessList.
Referenced by G4TrackingManager::ProcessOneTrack(), and G4ErrorPropagator::Propagate().
G4int G4ProcessManager::FindInsertPosition (G4int ord, G4int ivec) protected
Definition at line 430 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 430 of file G4ProcessManager.cc
References G4ProcessVector::entries(), G4ProcessAttribute::idxProcVector, INT_MAX, numberOfProcesses, ordLast, G4ProcessAttribute::ordProcVector, theProcVector, and tmp.
Referenced by AddProcess(), and SetProcessOrdering().
G4int G4ProcessManager::GetAlongStepIndex (G4VProcess * aProcess, G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by export_G4ProcessManager().
G4ProcessVector* G4ProcessManager::GetAlongStepProcessVector (G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by G4RunManagerKernel::ConfirmCoupledTransportation(), G4SteppingManager::GetProcessNumber(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4ProcessPlacer::PrintAlongStepDoItVec(), G4ProcessPlacer::PrintAlongStepGPILVec(), and G4ITStepProcessor::SetupGeneralProcessInfo().
G4int G4ProcessManager::GetAtRestIndex (G4VProcess * aProcess, G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by export_G4ProcessManager().
G4ProcessVector* G4ProcessManager::GetAtRestProcessVector (G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by G4hImpactIonisation::AlongStepDoIt(), G4ITStepProcessor::DealWithSecondaries(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4SteppingManager::GetProcessNumber(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4ITStepProcessor::SetupGeneralProcessInfo().
G4ProcessAttribute * G4ProcessManager::GetAttribute (G4int index) const private
Definition at line 285 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 285 of file G4ProcessManager.cc
References FatalException, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), numberOfProcesses, theAttrVector, and theParticleType.
Referenced by ActivateProcess(), CheckOrderingParameters(), CreateGPILvectors(), EndTracking(), GetAttribute(), GetProcessOrdering(), GetProcessVectorIndex(), InActivateProcess(), RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), SetProcessOrderingToSecond(), and StartTracking().
G4ProcessAttribute * G4ProcessManager::GetAttribute (G4VProcess * aProcess) const private
Definition at line 349 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 349 of file G4ProcessManager.cc
References GetAttribute(), and GetProcessIndex().
G4ParticleDefinition* G4ProcessManager::GetParticleType () const
Referenced by G4BiasingHelper::AddLimiterProcess(), G4ProcessTable::DumpInfo(), export_G4ProcessManager(), G4ProcessTable::FindProcess(), G4ProcessTable::Insert(), G4ProcessTable::Remove(), G4ProcessTable::SetProcessActivation(), and G4ParallelGeometriesLimiterProcess::SetProcessManager().
G4int G4ProcessManager::GetPostStepIndex (G4VProcess * aProcess, G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by export_G4ProcessManager().
G4ProcessVector* G4ProcessManager::GetPostStepProcessVector (G4ProcessVectorTypeIndex typ = typeGPIL) const
Referenced by G4HadronElasticPhysics::GetElasticProcess(), G4SteppingManager::GetProcessNumber(), G4BiasingProcessInterface::IsFirstPostStepDoItInterface(), G4BiasingProcessInterface::IsFirstPostStepGPILInterface(), G4BiasingProcessInterface::IsLastPostStepDoItInterface(), G4BiasingProcessInterface::IsLastPostStepGPILInterface(), G4ProcessPlacer::PrintPostStepDoItVec(), G4ProcessPlacer::PrintPostStepGPILVec(), G4BiasingProcessInterface::ReorderBiasingVectorAsGPIL(), G4ITStepProcessor::SetupGeneralProcessInfo(), and WLSSteppingAction::UserSteppingAction().
G4VProcess * G4ProcessManager::GetProcess (const G4String & processName) const
Definition at line 1234 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1234 of file G4ProcessManager.cc
References G4VProcess::GetProcessName(), k, and numberOfProcesses.
Referenced by NeutronHPphysics::ConstructProcess().
G4bool G4ProcessManager::GetProcessActivation (G4VProcess * aProcess) const
Definition at line 1261 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1261 of file G4ProcessManager.cc
References GetProcessIndex().
Referenced by G4EmCalculator::ActiveForParticle().
G4bool G4ProcessManager::GetProcessActivation (G4int index) const
Definition at line 1268 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1268 of file G4ProcessManager.cc
References G4cout, and GetVerboseLevel().
G4int G4ProcessManager::GetProcessIndex (G4VProcess *) const
Referenced by export_G4ProcessManager(), GetAttribute(), GetProcessActivation(), GetProcessVectorIndex(), RemoveProcess(), G4ProcessTable::SetProcessActivation(), and SetProcessActivation().
G4ProcessVector* G4ProcessManager::GetProcessList () const
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), G4EmCalculator::ActiveForParticle(), G4ITStepProcessor::ActiveOnlyITProcess(), G4BiasingHelper::AddLimiterProcess(), G4ProcessPlacer::AddProcessAs(), RunAction::BeginOfRunAction(), G4hImpactIonisation::BuildPhysicsTable(), G4VUserChemistryList::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4PhysicsListHelper::CheckParticleList(), G4NeutronCrossSectionXS::ConstructProcess(), P6DExtDecayerPhysics::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4TheRayTracer::CreateBitMap(), G4EmDNAPhysicsActivator::DeactivateNuclearStopping(), G4LossTableManager::DumpHtml(), G4PhysListUtil::FindCaptureProcess(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4PhysListUtil::FindFissionProcess(), G4VHadronPhysics::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmModelActivator::FindOrAddProcess(), G4EmCalculator::FindProcess(), G4ProcessTable::FindProcesses(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), PhysicsList::GetProcess(), G4EmDNAPhysicsActivator::HasMsc(), G4EmModelActivator::HasMsc(), G4VUserPhysicsList::PreparePhysicsTable(), G4PhysicsListHelper::RegisterProcess(), G4ProcessManagerMessenger::SetCurrentParticle(), G4EmConfigurator::SetModelForRegion(), G4ProcessTable::SetProcessActivation(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), G4GlobalFastSimulationManager::ShowSetup(), GB07BOptrLeadingParticle::StartRun(), LXeSteppingAction::UserSteppingAction(), and PHG4RICHSteppingAction::UserSteppingAction().
G4int G4ProcessManager::GetProcessListLength () const
Referenced by G4EmDNAPhysicsActivator::DeactivateNuclearStopping(), G4LossTableManager::DumpHtml(), export_G4ProcessManager(), G4EmModelActivator::FindOrAddProcess(), PhysicsList::GetProcess(), G4EmDNAPhysicsActivator::HasMsc(), G4EmModelActivator::HasMsc(), G4EmConfigurator::SetModelForRegion(), PHG4RICHSteppingAction::UserSteppingAction(), and LXeSteppingAction::UserSteppingAction().
G4int G4ProcessManager::GetProcessOrdering (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 648 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 648 of file G4ProcessManager.cc
References GetAttribute(), GetProcessVectorId(), G4ProcessAttribute::ordProcVector, and typeDoIt.
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), and export_G4ProcessManager().
G4ProcessVector* G4ProcessManager::GetProcessVector (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL) const
G4int G4ProcessManager::GetProcessVectorId (G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL) const protected
Referenced by GetProcessOrdering(), GetProcessVectorIndex(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
G4int G4ProcessManager::GetProcessVectorIndex (G4VProcess * aProcess, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL) const
Definition at line 245 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 245 of file G4ProcessManager.cc
References G4cout, G4endl, GetAttribute(), G4ParticleDefinition::GetParticleName(), GetProcessIndex(), G4VProcess::GetProcessName(), GetProcessVectorId(), G4ProcessAttribute::idxProcVector, theParticleType, and verboseLevel.
Referenced by export_G4ProcessManager().
G4int G4ProcessManager::GetVerboseLevel () const
Referenced by ActivateProcess(), AddProcess(), CheckOrderingParameters(), G4ProcessTable::DumpInfo(), export_G4ProcessManager(), G4ProcessManager(), GetAttribute(), G4ProcessManagerMessenger::GetCurrentValue(), GetProcessActivation(), InActivateProcess(), InsertAt(), RemoveAt(), SetProcessOrdering(), SetProcessOrderingToSecond(), and ~G4ProcessManager().
G4VProcess * G4ProcessManager::InActivateProcess (G4int index) private
Definition at line 957 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 957 of file G4ProcessManager.cc
References G4ProcessVector::entries(), FatalException, G4cout, G4endl, G4Exception(), G4State_Init, G4State_PreInit, GetAttribute(), G4StateManager::GetCurrentState(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4StateManager::GetStateManager(), GetVerboseLevel(), incremental_prev_tag::idx, G4ProcessAttribute::idxProcVector, G4ProcessAttribute::isActive, SizeOfProcVectorArray, theParticleType, and theProcVector.
Referenced by SetProcessActivation().
G4int G4ProcessManager::InsertAt (G4int position, G4VProcess * process, G4int ivec) protected
Definition at line 355 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 355 of file G4ProcessManager.cc
References G4ProcessVector::entries(), G4cout, G4endl, GetVerboseLevel(), G4ProcessAttribute::idxProcVector, G4ProcessVector::insertAt(), numberOfProcesses, and theProcVector.
Referenced by AddProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
G4bool G4ProcessManager::operator!= (const G4ProcessManager & right) const
Definition at line 1118 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1118 of file G4ProcessManager.cc
G4ProcessManager & G4ProcessManager::operator= (const G4ProcessManager & right) private
Definition at line 197 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 197 of file G4ProcessManager.cc
References G4Exception(), and JustWarning.
G4bool G4ProcessManager::operator== (const G4ProcessManager & right) const
Definition at line 1112 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1112 of file G4ProcessManager.cc
G4int G4ProcessManager::RemoveAt (G4int position, G4VProcess * process, G4int ivec) protected
Definition at line 390 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 390 of file G4ProcessManager.cc
References G4ProcessVector::entries(), G4cout, G4endl, GetVerboseLevel(), G4ProcessAttribute::idxProcVector, numberOfProcesses, ordInActive, G4ProcessAttribute::ordProcVector, G4ProcessVector::removeAt(), and theProcVector.
Referenced by RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
G4VProcess * G4ProcessManager::RemoveProcess (G4VProcess * aProcess)
Definition at line 642 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 642 of file G4ProcessManager.cc
References GetProcessIndex().
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), NeutronHPphysics::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), F04PhysicsList::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), and G4ProcessPlacer::RemoveProcess().
G4VProcess * G4ProcessManager::RemoveProcess (G4int index)
Definition at line 568 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 568 of file G4ProcessManager.cc
References ActivateProcess(), CreateGPILvectors(), G4ProcessVector::entries(), FatalException, G4Exception(), GetAttribute(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4ProcessTable::GetProcessTable(), incremental_prev_tag::idx, G4ProcessAttribute::idxProcessList, G4ProcessAttribute::idxProcVector, G4ProcessAttribute::isActive, numberOfProcesses, G4ProcessTable::Remove(), G4ProcessVector::removeAt(), RemoveAt(), SizeOfProcVectorArray, theAttrVector, theParticleType, theProcessList, and theProcVector.
void G4ProcessManager::SetIndexToProcessVector (G4int ivec) private
void G4ProcessManager::SetParticleType (const G4ParticleDefinition *)
Referenced by export_G4ProcessManager().
G4VProcess * G4ProcessManager::SetProcessActivation (G4VProcess * aProcess, G4bool fActive)
Definition at line 1246 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1246 of file G4ProcessManager.cc
References GetProcessIndex().
Referenced by G4ITStepProcessor::ActiveOnlyITProcess(), G4ProcessManagerMessenger::SetNewValue(), and G4ProcessTable::SetProcessActivation().
G4VProcess * G4ProcessManager::SetProcessActivation (G4int index, G4bool fActive)
Definition at line 1254 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1254 of file G4ProcessManager.cc
References ActivateProcess(), and InActivateProcess().
void G4ProcessManager::SetProcessOrdering (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt, G4int ordDoIt = ordDefault)
Definition at line 669 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 669 of file G4ProcessManager.cc
References CheckOrderingParameters(), CreateGPILvectors(), FindInsertPosition(), G4cout, G4endl, GetAttribute(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), GetProcessVectorId(), GetVerboseLevel(), G4ProcessAttribute::idxProcVector, InsertAt(), ordLast, G4ProcessAttribute::ordProcVector, RemoveAt(), theParticleType, typeDoIt, and verboseLevel.
Referenced by G4FastSimulationHelper::ActivateFastSimulation(), XrayFluoPhysicsList::AddDecay(), B03PhysicsList::AddScoringProcess(), G4AdjointPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), G4ParallelWorldPhysics::ConstructProcess(), F04PhysicsList::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), export_G4ProcessManager(), PHG4Reco::InitRun(), G4PhysicsListHelper::RegisterProcess(), and SetProcessOrderingToLast().
void G4ProcessManager::SetProcessOrderingToFirst (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 757 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 757 of file G4ProcessManager.cc
References CheckOrderingParameters(), CreateGPILvectors(), G4cout, G4endl, G4Exception(), GetAttribute(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), GetProcessVectorId(), G4ProcessAttribute::idxProcVector, InsertAt(), isSetOrderingFirstInvoked, JustWarning, G4ProcessAttribute::ordProcVector, RemoveAt(), theParticleType, typeDoIt, and verboseLevel.
Referenced by G4PhysicsListHelper::AddTransportation(), G4AdjointPhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructProcess(), export_G4ProcessManager(), and G4PhysicsListHelper::RegisterProcess().
void G4ProcessManager::SetProcessOrderingToLast (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 937 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 937 of file G4ProcessManager.cc
References G4Exception(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), isSetOrderingLastInvoked, JustWarning, ordLast, SetProcessOrdering(), and theParticleType.
Referenced by G4FastSimulationHelper::ActivateFastSimulation(), G4BiasingHelper::AddLimiterProcess(), DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4OpticalPhysics::ConstructProcess(), export_G4ProcessManager(), PHG4Reco::InitRun(), and G4PhysicsListHelper::RegisterProcess().
void G4ProcessManager::SetProcessOrderingToSecond (G4VProcess * aProcess, G4ProcessVectorDoItIndex idDoIt)
Definition at line 834 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 834 of file G4ProcessManager.cc
References CheckOrderingParameters(), CreateGPILvectors(), G4ProcessVector::entries(), G4cout, G4endl, GetAttribute(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), GetProcessVectorId(), GetVerboseLevel(), G4ProcessAttribute::idxProcVector, InsertAt(), INT_MAX, numberOfProcesses, G4ProcessAttribute::ordProcVector, RemoveAt(), theParticleType, theProcVector, tmp, typeDoIt, and verboseLevel.
Referenced by G4BiasingHelper::AddLimiterProcess(), G4ProcessPlacer::AddProcessAs(), B03PhysicsList::AddScoringProcess(), G4ParallelWorldPhysics::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
void G4ProcessManager::SetVerboseLevel (G4int value)
Referenced by LBE::ConstructGeneral(), G4ProcessTable::DumpInfo(), export_G4ProcessManager(), and G4ProcessManagerMessenger::SetNewValue().
void G4ProcessManager::StartTracking (G4Track * aTrack = 0)
Definition at line 1211 of file G4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 1211 of file G4ProcessManager.cc
References duringTracking, G4ProcessVector::entries(), GetAttribute(), incremental_prev_tag::idx, G4ProcessAttribute::isActive, and theProcessList.
Referenced by G4ErrorPropagator::InitG4Track(), G4TrackingManager::ProcessOneTrack(), and G4ITTrackingManager::StartTracking().
Member Data Documentation
G4ThreadLocal G4int G4ProcessManager::counterOfObjects = 0 static private
Definition at line 355 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 355 of file G4ProcessManager.hh
Referenced by G4ProcessManager(), and ~G4ProcessManager().
G4bool G4ProcessManager::duringTracking private
Definition at line 333 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 333 of file G4ProcessManager.hh
Referenced by EndTracking(), and StartTracking().
G4ThreadLocal G4ProcessManagerMessenger * G4ProcessManager::fProcessManagerMessenger = 0 static private
Definition at line 354 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 354 of file G4ProcessManager.hh
Referenced by G4ProcessManager(), and ~G4ProcessManager().
G4bool G4ProcessManager::isSetOrderingFirstInvoked[NDoit] private
Definition at line 337 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 337 of file G4ProcessManager.hh
Referenced by G4ProcessManager(), and SetProcessOrderingToFirst().
G4bool G4ProcessManager::isSetOrderingLastInvoked[NDoit] private
Definition at line 338 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 338 of file G4ProcessManager.hh
Referenced by G4ProcessManager(), and SetProcessOrderingToLast().
G4int G4ProcessManager::numberOfProcesses private
Definition at line 328 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 328 of file G4ProcessManager.hh
Referenced by AddProcess(), FindInsertPosition(), G4ProcessManager(), GetAttribute(), GetProcess(), InsertAt(), RemoveAt(), RemoveProcess(), and SetProcessOrderingToSecond().
G4ProcessAttrVector* G4ProcessManager::theAttrVector private
Definition at line 294 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 294 of file G4ProcessManager.hh
Referenced by AddProcess(), G4ProcessManager(), GetAttribute(), RemoveProcess(), and ~G4ProcessManager().
const G4ParticleDefinition* G4ProcessManager::theParticleType private
Definition at line 325 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 325 of file G4ProcessManager.hh
Referenced by ActivateProcess(), AddProcess(), DumpInfo(), GetAttribute(), GetProcessVectorIndex(), InActivateProcess(), RemoveProcess(), SetProcessOrdering(), SetProcessOrderingToFirst(), SetProcessOrderingToLast(), and SetProcessOrderingToSecond().
G4ProcessVector* G4ProcessManager::theProcessList private
Definition at line 329 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 329 of file G4ProcessManager.hh
Referenced by AddProcess(), CreateGPILvectors(), DumpInfo(), EndTracking(), G4ProcessManager(), RemoveProcess(), StartTracking(), and ~G4ProcessManager().
G4ProcessVector* G4ProcessManager::theProcVector[SizeOfProcVectorArray] private
Definition at line 290 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 290 of file G4ProcessManager.hh
Referenced by ActivateProcess(), CreateGPILvectors(), FindInsertPosition(), G4ProcessManager(), InActivateProcess(), InsertAt(), RemoveAt(), RemoveProcess(), SetProcessOrderingToSecond(), and ~G4ProcessManager().
G4int G4ProcessManager::verboseLevel protected
Definition at line 351 of file G4ProcessManager.hh.
View newest version in sPHENIX GitHub at line 351 of file G4ProcessManager.hh
Referenced by AddProcess(), DumpInfo(), GetProcessVectorIndex(), SetProcessOrdering(), SetProcessOrderingToFirst(), and SetProcessOrderingToSecond().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessManager.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4ProcessManager.cc