ECCE @ EIC Software: G4QAOLowEnergyLoss Class Reference
G4QAOLowEnergyLoss Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4QAOLowEnergyLoss.hh>
Public Member Functions
G4QAOLowEnergyLoss (const G4String &name)
~G4QAOLowEnergyLoss ()
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const
G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const
G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4double EnergyLoss (const G4Material *material, G4double kineticEnergy, G4double zParticle) const
G4int GetNumberOfShell (const G4Material *material) const
G4double GetShellEnergy (const G4Material *material, G4int nbOfTheShell) const
G4double GetOscillatorEnergy (const G4Material *material, G4int nbOfTheShell) const
G4double GetShellStrength (const G4Material *material, G4int nbOfTheShell) const
G4double GetOccupationNumber (G4int Z, G4int ShellNb) const
G4double GetL0 (G4double normEnergy) const
G4double GetL1 (G4double normEnergy) const
G4double GetL2 (G4double normEnergy) const
Private Attributes
G4int numberOfMaterials
G4int sizeL0
G4int sizeL1
G4int sizeL2
Static Private Attributes
static const G4int materialAvailable [6] = {13,14,29,73,79,78}
static const G4int nbofShellForMaterial [6] = {3,3,4,6,6,6 }
static const G4double alShellEnergy [3] ={ 2795e-6, 202e-6, 16.9e-6}
static const G4double alShellStrength [3] ={ 0.1349, 0.6387, 0.2264}
static const G4double siShellEnergy [3] ={ 3179e-6, 249e-6, 20.3e-6 }
static const G4double siShellStrength [3] ={ 0.1222, 0.5972, 0.2806}
static const G4double cuShellEnergy [4] ={ 16931e-6, 1930e-6, 199e-6, 39.6e-6}
static const G4double cuShellStrength [4] ={ 0.0505, 0.2561, 0.4913, 0.2021}
static const G4double taShellEnergy [6] ={ 88926e-6, 18012e-6, 3210e-6, 575e-6, 108.7e-6, 30.8e-6}
static const G4double taShellStrength [6] ={ 0.0126, 0.0896, 0.2599, 0.3413, 0.2057, 0.0908}
static const G4double auShellEnergy [6] ={ 96235e-6, 25918e-6, 4116e-6, 599e-6, 87.3e-6, 36.9e-6}
static const G4double auShellStrength [6] ={ 0.0139, 0.0803, 0.2473, 0.423, 0.1124, 0.1231}
static const G4double ptShellEnergy [6] ={ 95017e-6, 25590e-6, 4063e-6, 576e-6, 81.9e-6, 31.4e-6}
static const G4double ptShellStrength [6] ={ 0.0129, 0.0745, 0.2295, 0.4627, 0.1324, 0.0879}
static const G4double L0 [67][2]
static const G4double L1 [22][2]
static const G4double L2 [14][2]
static const G4int nbOfElectronPerSubShell [1540]
static const G4int fNumberOfShells [101]
Detailed Description
Definition at line 53 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 53 of file G4QAOLowEnergyLoss.hh
Constructor & Destructor Documentation
G4QAOLowEnergyLoss::G4QAOLowEnergyLoss (const G4String & name)
Definition at line 70 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 70 of file G4QAOLowEnergyLoss.cc
References numberOfMaterials, sizeL0, sizeL1, and sizeL2.
G4QAOLowEnergyLoss::~G4QAOLowEnergyLoss ()
Definition at line 80 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 80 of file G4QAOLowEnergyLoss.cc
Member Function Documentation
G4double G4QAOLowEnergyLoss::EnergyLoss (const G4Material * material, G4double kineticEnergy, G4double zParticle) const private
Definition at line 171 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 171 of file G4QAOLowEnergyLoss.cc
References source.hepunit::c_light, source.hepunit::c_squared, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, GetL0(), GetL1(), GetL2(), GetNumberOfShell(), GetShellEnergy(), GetShellStrength(), source.hepunit::hbarc_squared, source.hepunit::proton_mass_c2, twopi, and v.
Referenced by TheValue().
G4double G4QAOLowEnergyLoss::GetL0 (G4double normEnergy) const private
Definition at line 366 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 366 of file G4QAOLowEnergyLoss.cc
References L0, n, and sizeL0.
Referenced by EnergyLoss().
G4double G4QAOLowEnergyLoss::GetL1 (G4double normEnergy) const private
Definition at line 384 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 384 of file G4QAOLowEnergyLoss.cc
References L1, n, and sizeL1.
Referenced by EnergyLoss().
G4double G4QAOLowEnergyLoss::GetL2 (G4double normEnergy) const private
Definition at line 404 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 404 of file G4QAOLowEnergyLoss.cc
References L2, n, and sizeL2.
Referenced by EnergyLoss().
G4int G4QAOLowEnergyLoss::GetNumberOfShell (const G4Material * material) const private
Definition at line 253 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 253 of file G4QAOLowEnergyLoss.cc
References fNumberOfShells, G4Material::GetZ(), materialAvailable, nbofShellForMaterial, numberOfMaterials, and Z.
Referenced by EnergyLoss().
G4double G4QAOLowEnergyLoss::GetOccupationNumber (G4int Z, G4int ShellNb) const private
Definition at line 356 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 356 of file G4QAOLowEnergyLoss.cc
References fNumberOfShells, nbOfElectronPerSubShell, Z, and z.
Referenced by GetOscillatorEnergy(), and GetShellStrength().
G4double G4QAOLowEnergyLoss::GetOscillatorEnergy (const G4Material * material, G4int nbOfTheShell) const private
Definition at line 297 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 297 of file G4QAOLowEnergyLoss.cc
References cm3, e, Acts::UnitConstants::g, G4Exp(), G4Element::GetAtomicShell(), G4Material::GetDensity(), G4Material::GetElement(), G4Element::GetN(), GetOccupationNumber(), G4Element::GetZ(), and Z.
Referenced by GetShellEnergy().
G4double G4QAOLowEnergyLoss::GetShellEnergy (const G4Material * material, G4int nbOfTheShell) const private
Definition at line 274 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 274 of file G4QAOLowEnergyLoss.cc
References alShellEnergy, auShellEnergy, cuShellEnergy, G4cout, G4endl, G4Material::GetName(), G4Material::GetNumberOfElements(), GetOscillatorEnergy(), G4Material::GetZ(), ptShellEnergy, siShellEnergy, and taShellEnergy.
Referenced by EnergyLoss().
G4double G4QAOLowEnergyLoss::GetShellStrength (const G4Material * material, G4int nbOfTheShell) const private
Definition at line 334 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 334 of file G4QAOLowEnergyLoss.cc
References alShellStrength, auShellStrength, cuShellStrength, G4cout, G4endl, G4Material::GetName(), G4Material::GetNumberOfElements(), GetOccupationNumber(), G4Material::GetZ(), ptShellStrength, siShellStrength, taShellStrength, and Z.
Referenced by EnergyLoss().
G4double G4QAOLowEnergyLoss::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 84 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 84 of file G4QAOLowEnergyLoss.cc
References MeV.
G4double G4QAOLowEnergyLoss::HighEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 99 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 99 of file G4QAOLowEnergyLoss.cc
References MeV.
G4bool G4QAOLowEnergyLoss::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 111 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 111 of file G4QAOLowEnergyLoss.cc
References G4AntiProton::AntiProtonDefinition(), G4DynamicParticle::GetDefinition(), and G4Material::GetNumberOfElements().
G4bool G4QAOLowEnergyLoss::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 127 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 127 of file G4QAOLowEnergyLoss.cc
References G4AntiProton::AntiProtonDefinition(), and G4Material::GetNumberOfElements().
G4double G4QAOLowEnergyLoss::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 91 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 91 of file G4QAOLowEnergyLoss.cc
References keV.
G4double G4QAOLowEnergyLoss::LowEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 104 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 104 of file G4QAOLowEnergyLoss.cc
References keV.
G4double G4QAOLowEnergyLoss::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 146 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 146 of file G4QAOLowEnergyLoss.cc
References energy, EnergyLoss(), eplus, G4DynamicParticle::GetCharge(), and G4DynamicParticle::GetKineticEnergy().
G4double G4QAOLowEnergyLoss::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 158 of file G4QAOLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 158 of file G4QAOLowEnergyLoss.cc
References EnergyLoss(), eplus, and G4ParticleDefinition::GetPDGCharge().
Member Data Documentation
const G4double G4QAOLowEnergyLoss::alShellEnergy ={ 2795e-6, 202e-6, 16.9e-6} static private
Definition at line 123 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 123 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellEnergy().
const G4double G4QAOLowEnergyLoss::alShellStrength ={ 0.1349, 0.6387, 0.2264} static private
Definition at line 124 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellStrength().
const G4double G4QAOLowEnergyLoss::auShellEnergy ={ 96235e-6, 25918e-6, 4116e-6, 599e-6, 87.3e-6, 36.9e-6} static private
Definition at line 131 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 131 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellEnergy().
const G4double G4QAOLowEnergyLoss::auShellStrength ={ 0.0139, 0.0803, 0.2473, 0.423, 0.1124, 0.1231} static private
Definition at line 132 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 132 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellStrength().
const G4double G4QAOLowEnergyLoss::cuShellEnergy ={ 16931e-6, 1930e-6, 199e-6, 39.6e-6} static private
Definition at line 127 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 127 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellEnergy().
const G4double G4QAOLowEnergyLoss::cuShellStrength ={ 0.0505, 0.2561, 0.4913, 0.2021} static private
Definition at line 128 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 128 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellStrength().
const G4int G4QAOLowEnergyLoss::fNumberOfShells static private
Initial value:
=
{
 0 ,
 1 ,  1 ,  2 ,  2 ,  3 ,    3 ,  4 ,  4 ,  3 ,  4 ,
 5 ,  5 ,  6 ,  6 ,  6 ,    6 ,  6 ,  7 ,  8 ,  8 ,
 9 ,  9 ,  9 ,  9 ,  9 ,    9 ,  9 , 10 , 10 , 10 ,
11 , 11 , 11 , 11 , 11 ,   12 , 13 , 13 , 14 , 14 ,
14 , 14 , 14 , 14 , 14 ,   15 , 15 , 15 , 16 , 16 ,
16 , 16 , 16 , 17 , 18 ,   18 , 19 , 19 , 19 , 19 ,
19 , 19 , 19 , 20 , 19 ,   19 , 19 , 19 , 19 , 20 ,
21 , 21 , 21 , 21 , 21 ,   21 , 21 , 21 , 22 , 22 ,
23 , 23 , 23 , 23 , 24 ,   24 , 25 , 25 , 26 , 26 ,
27 , 27 , 27 , 26 , 26 ,   27 , 27 , 26 , 26 , 26
}
Definition at line 143 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 143 of file G4QAOLowEnergyLoss.hh
Referenced by GetNumberOfShell(), and GetOccupationNumber().
const G4double G4QAOLowEnergyLoss::L0 static private
Definition at line 139 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 139 of file G4QAOLowEnergyLoss.hh
Referenced by GetL0().
const G4double G4QAOLowEnergyLoss::L1 static private
Initial value:
=
{
  {0.00,       -0.000001},
  {0.10,       -0.00001},
  {0.20,       -0.00049},
  {0.30,       -0.00084},
  {0.40,  0.00085},
  {0.50,  0.00519},
  {0.60,  0.01198},
  {0.70,  0.02074},
  {0.80,  0.03133},
  {0.90,  0.04369},
  {1.00,  0.06035},
  {2.00,  0.24023},
  {3.00,  0.44284},
  {4.00,  0.62012},
  {5.00,  0.77031},
  {6.00,  0.90390},
  {7.00,  1.02705},
  {8.00,  1.10867},
  {9.00,  1.17546},
  {10.00,       1.21599},
  {15.00, 1.24349},
  {20.00, 1.16752}
}
Definition at line 140 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 140 of file G4QAOLowEnergyLoss.hh
Referenced by GetL1().
const G4double G4QAOLowEnergyLoss::L2 static private
Initial value:
=
{
  {0.00,  0.000001},
  {0.10,  0.00001},
  {0.20,  0.00000},
  {0.40,       -0.00120},
  {0.60,       -0.00036},
  {0.80,  0.00372},
  {1.00,  0.01298},
  {2.00,  0.08296},
  {4.00,  0.21953},
  {6.00,  0.23903},
  {8.00,  0.20893},
  {10.00, 0.10879},
  {20.00,      -0.88409},
  {40.00,      -1.13902}
}
Definition at line 141 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 141 of file G4QAOLowEnergyLoss.hh
Referenced by GetL2().
const G4int G4QAOLowEnergyLoss::materialAvailable = {13,14,29,73,79,78} static private
Definition at line 118 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 118 of file G4QAOLowEnergyLoss.hh
Referenced by GetNumberOfShell().
const G4int G4QAOLowEnergyLoss::nbOfElectronPerSubShell static private
Definition at line 142 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 142 of file G4QAOLowEnergyLoss.hh
Referenced by GetOccupationNumber().
const G4int G4QAOLowEnergyLoss::nbofShellForMaterial = {3,3,4,6,6,6 } static private
Definition at line 122 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 122 of file G4QAOLowEnergyLoss.hh
Referenced by GetNumberOfShell().
G4int G4QAOLowEnergyLoss::numberOfMaterials private
Definition at line 136 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 136 of file G4QAOLowEnergyLoss.hh
Referenced by G4QAOLowEnergyLoss(), and GetNumberOfShell().
const G4double G4QAOLowEnergyLoss::ptShellEnergy ={ 95017e-6, 25590e-6, 4063e-6, 576e-6, 81.9e-6, 31.4e-6} static private
Definition at line 133 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 133 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellEnergy().
const G4double G4QAOLowEnergyLoss::ptShellStrength ={ 0.0129, 0.0745, 0.2295, 0.4627, 0.1324, 0.0879} static private
Definition at line 134 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 134 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellStrength().
const G4double G4QAOLowEnergyLoss::siShellEnergy ={ 3179e-6, 249e-6, 20.3e-6 } static private
Definition at line 125 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 125 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellEnergy().
const G4double G4QAOLowEnergyLoss::siShellStrength ={ 0.1222, 0.5972, 0.2806} static private
Definition at line 126 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 126 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellStrength().
G4int G4QAOLowEnergyLoss::sizeL0 private
Definition at line 145 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 145 of file G4QAOLowEnergyLoss.hh
Referenced by G4QAOLowEnergyLoss(), and GetL0().
G4int G4QAOLowEnergyLoss::sizeL1 private
Definition at line 146 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 146 of file G4QAOLowEnergyLoss.hh
Referenced by G4QAOLowEnergyLoss(), and GetL1().
G4int G4QAOLowEnergyLoss::sizeL2 private
Definition at line 147 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 147 of file G4QAOLowEnergyLoss.hh
Referenced by G4QAOLowEnergyLoss(), and GetL2().
const G4double G4QAOLowEnergyLoss::taShellEnergy ={ 88926e-6, 18012e-6, 3210e-6, 575e-6, 108.7e-6, 30.8e-6} static private
Definition at line 129 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 129 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellEnergy().
const G4double G4QAOLowEnergyLoss::taShellStrength ={ 0.0126, 0.0896, 0.2599, 0.3413, 0.2057, 0.0908} static private
Definition at line 130 of file G4QAOLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 130 of file G4QAOLowEnergyLoss.hh
Referenced by GetShellStrength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4QAOLowEnergyLoss.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4QAOLowEnergyLoss.cc