ECCE @ EIC Software: G4RootMainNtupleManager Class Reference
G4RootMainNtupleManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootMainNtupleManager.hh>
Public Member Functions
G4RootMainNtupleManager (G4RootNtupleManager *ntupleBuilder, G4bool rowWise, const G4AnalysisManagerState &state)
~G4RootMainNtupleManager ()
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Protected Types
using NtupleType = tools::wroot::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Protected Member Functions
void CreateNtuple (const tools::ntuple_booking &ntupleBooking, G4bool warn=true)
void CreateNtuplesFromBooking ()
G4bool Merge ()
G4bool Reset (G4bool deleteNtuple)
void SetNtupleFile (std::shared_ptr< tools::wroot::file > rfile)
void SetNtupleDirectory (tools::wroot::directory *directory)
void SetRowWise (G4bool rowWise)
std::shared_ptr
< tools::wroot::file > GetNtupleFile () const
tools::wroot::directory * GetNtupleDirectory () const
const std::vector
< NtupleDescriptionType * > & GetNtupleDescriptionVector ()
const std::vector
< tools::wroot::ntuple * > & GetNtupleVector ()
unsigned int GetBasketEntries () const
Private Attributes
G4RootNtupleManager * fNtupleBuilder
G4bool fRowWise
std::shared_ptr
< tools::wroot::file > fNtupleFile
tools::wroot::directory * fNtupleDirectory
std::vector
< tools::wroot::ntuple * > fNtupleVector
Friends
class G4RootPNtupleManager
class G4RootNtupleManager
Additional Inherited Members
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 50 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RootMainNtupleManager.hh
Member Typedef Documentation
using G4RootMainNtupleManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType> protected
Definition at line 64 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RootMainNtupleManager.hh
using G4RootMainNtupleManager::NtupleType = tools::wroot::ntuple protected
Definition at line 63 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RootMainNtupleManager.hh
Constructor & Destructor Documentation
G4RootMainNtupleManager::G4RootMainNtupleManager (G4RootNtupleManager * ntupleBuilder, G4bool rowWise, const G4AnalysisManagerState & state) explicit
Definition at line 37 of file G4RootMainNtupleManager.cc.
View newest version in sPHENIX GitHub at line 37 of file G4RootMainNtupleManager.cc
G4RootMainNtupleManager::~G4RootMainNtupleManager ()
Definition at line 48 of file G4RootMainNtupleManager.cc.
View newest version in sPHENIX GitHub at line 48 of file G4RootMainNtupleManager.cc
Member Function Documentation
void G4RootMainNtupleManager::CreateNtuple (const tools::ntuple_booking & ntupleBooking, G4bool warn = true) protected
Definition at line 58 of file G4RootMainNtupleManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RootMainNtupleManager.cc
References fNtupleBuilder, fNtupleDirectory, fNtupleVector, fRowWise, G4BaseAnalysisManager::fState, G4endl, G4Exception(), G4RootNtupleManager::GetBasketSize(), G4AnalysisManagerState::GetVerboseL3(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and ntuple.
Referenced by CreateNtuplesFromBooking().
void G4RootMainNtupleManager::CreateNtuplesFromBooking () protected
Definition at line 99 of file G4RootMainNtupleManager.cc.
View newest version in sPHENIX GitHub at line 99 of file G4RootMainNtupleManager.cc
References CreateNtuple(), fNtupleBuilder, fNtupleDirectory, G4endl, G4Exception(), G4RootNtupleManager::GetNtupleDescriptionVector(), and JustWarning.
unsigned int G4RootMainNtupleManager::GetBasketEntries () const inline protected
Definition at line 110 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RootMainNtupleManager.hh
References fNtupleBuilder, and G4RootNtupleManager::GetBasketEntries().
Referenced by G4RootPNtupleManager::CreateNtuple().
const std::vector<NtupleDescriptionType*>& G4RootMainNtupleManager::GetNtupleDescriptionVector () inline protected
Definition at line 80 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RootMainNtupleManager.hh
References fNtupleBuilder, and G4RootNtupleManager::GetNtupleDescriptionVector().
tools::wroot::directory * G4RootMainNtupleManager::GetNtupleDirectory () const inline protected
Definition at line 107 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4RootMainNtupleManager.hh
References fNtupleDirectory.
std::shared_ptr< tools::wroot::file > G4RootMainNtupleManager::GetNtupleFile () const inline protected
Definition at line 104 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4RootMainNtupleManager.hh
References fNtupleFile.
Referenced by G4RootPNtupleManager::CreateNtuple().
const std::vector<tools::wroot::ntuple*>& G4RootMainNtupleManager::GetNtupleVector () inline protected
Definition at line 82 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RootMainNtupleManager.hh
References fNtupleVector.
Referenced by G4RootPNtupleManager::CreateNtuplesFromMain(), and G4RootPNtupleManager::GetMainNtupleInFunction().
G4bool G4RootMainNtupleManager::Merge () protected
Definition at line 124 of file G4RootMainNtupleManager.cc.
View newest version in sPHENIX GitHub at line 124 of file G4RootMainNtupleManager.cc
References fNtupleVector, and ntuple.
G4bool G4RootMainNtupleManager::Reset (G4bool deleteNtuple) protected
Definition at line 134 of file G4RootMainNtupleManager.cc.
View newest version in sPHENIX GitHub at line 134 of file G4RootMainNtupleManager.cc
References fNtupleVector, and ntuple.
void G4RootMainNtupleManager::SetNtupleDirectory (tools::wroot::directory * directory) inline protected
Definition at line 98 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RootMainNtupleManager.hh
References fNtupleDirectory.
void G4RootMainNtupleManager::SetNtupleFile (std::shared_ptr< tools::wroot::file > rfile) inline protected
Definition at line 95 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RootMainNtupleManager.hh
References fNtupleFile, and propagation_timing::rfile.
void G4RootMainNtupleManager::SetRowWise (G4bool rowWise) inline protected
Definition at line 101 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4RootMainNtupleManager.hh
References fRowWise.
Friends And Related Function Documentation
friend class G4RootNtupleManager friend
Definition at line 53 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RootMainNtupleManager.hh
friend class G4RootPNtupleManager friend
Definition at line 52 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RootMainNtupleManager.hh
Member Data Documentation
G4RootNtupleManager* G4RootMainNtupleManager::fNtupleBuilder private
Definition at line 88 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RootMainNtupleManager.hh
Referenced by CreateNtuple(), CreateNtuplesFromBooking(), GetBasketEntries(), and GetNtupleDescriptionVector().
tools::wroot::directory* G4RootMainNtupleManager::fNtupleDirectory private
Definition at line 91 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RootMainNtupleManager.hh
Referenced by CreateNtuple(), CreateNtuplesFromBooking(), GetNtupleDirectory(), and SetNtupleDirectory().
std::shared_ptr<tools::wroot::file> G4RootMainNtupleManager::fNtupleFile private
Definition at line 90 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RootMainNtupleManager.hh
Referenced by GetNtupleFile(), and SetNtupleFile().
std::vector<tools::wroot::ntuple*> G4RootMainNtupleManager::fNtupleVector private
Definition at line 92 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RootMainNtupleManager.hh
Referenced by CreateNtuple(), GetNtupleVector(), Merge(), and Reset().
G4bool G4RootMainNtupleManager::fRowWise private
Definition at line 89 of file G4RootMainNtupleManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RootMainNtupleManager.hh
Referenced by CreateNtuple(), and SetRowWise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootMainNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/root/src/G4RootMainNtupleManager.cc