ECCE @ EIC Software: G4eplusPolarizedAnnihilation Class Reference
G4eplusPolarizedAnnihilation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4eplusPolarizedAnnihilation.hh>
Public Member Functions
G4eplusPolarizedAnnihilation (const G4String &name="pol-annihil")
virtual ~G4eplusPolarizedAnnihilation ()
virtual void PrintInfo () override
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
Public Member Functions inherited from G4eplusAnnihilation
G4eplusAnnihilation (const G4String &name="annihil")
virtual ~G4eplusAnnihilation ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) final
virtual G4VParticleChange * AtRestDoIt (const G4Track &track, const G4Step &stepData) override
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition) override
virtual void ProcessDescription (std::ostream &) const override
Public Member Functions inherited from G4VEmProcess
G4VEmProcess (const G4String &name, G4ProcessType type=fElectromagnetic)
virtual ~G4VEmProcess ()
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void StartTracking (G4Track *) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
virtual G4VEmProcess * GetEmProcess (const G4String &name)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double ComputeCrossSectionPerAtom (G4double kineticEnergy, G4double Z, G4double A=0., G4double cut=0.0)
G4double MeanFreePath (const G4Track &track)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple, G4double logKinEnergy)
void SetLambdaBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
void SetMinKinEnergyPrim (G4double e)
void SetMaxKinEnergy (G4double e)
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * LambdaTablePrim () const
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * SecondaryParticle () const
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t idxRegion) const
void AddEmModel (G4int, G4VEmModel *, const G4Region *region=nullptr)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
void UpdateEmModel (const G4String &, G4double, G4double)
G4int GetNumberOfModels () const
G4int GetNumberOfRegionModels (size_t couple_index) const
G4VEmModel * GetRegionModel (G4int idx, size_t couple_index) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
const G4VEmModel * GetCurrentModel () const
const G4Element * GetCurrentElement () const
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
G4double CrossSectionBiasingFactor () const
void ActivateForcedInteraction (G4double length=0.0, const G4String &r="", G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void SetEmMasterProcess (const G4VEmProcess *)
void SetIntegral (G4bool val)
void SetBuildTableFlag (G4bool val)
void CurrentSetup (const G4MaterialCutsCouple *, G4double energy)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
void CleanTables ()
void BuildAsymmetryTables (const G4ParticleDefinition &part)
G4double ComputeAsymmetry (G4double energy, const G4MaterialCutsCouple *couple, const G4ParticleDefinition &particle, G4double cut, G4double &tasm)
G4double ComputeSaturationFactor (const G4Track &aTrack)
G4eplusPolarizedAnnihilation & operator= (const G4eplusPolarizedAnnihilation &right)
G4eplusPolarizedAnnihilation (const G4eplusPolarizedAnnihilation &)
Private Attributes
G4bool isInitialised
G4PolarizedAnnihilationModel * emModel
G4ThreeVector theTargetPolarization
G4PhysicsTable * theAsymmetryTable
G4PhysicsTable * theTransverseAsymmetryTable
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4eplusAnnihilation
virtual void StreamProcessInfo (std::ostream &outFile) const override
virtual void InitialiseProcess (const G4ParticleDefinition *) override
Protected Attributes inherited from G4VEmProcess
G4LossTableManager * lManager
G4EmParameters * theParameters
G4EmBiasingManager * biasManager
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theElectron
G4ParticleChangeForGamma fParticleChange
std::vector< G4DynamicParticle * > secParticles
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t currentCoupleIndex
size_t basedCoupleIndex
G4int mainSecondaries
G4int secID
G4int fluoID
G4int augerID
G4int biasID
G4bool isTheMaster
G4double mfpKinEnergy
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepLambda
Detailed Description
Definition at line 62 of file G4eplusPolarizedAnnihilation.hh.
View newest version in sPHENIX GitHub at line 62 of file G4eplusPolarizedAnnihilation.hh
Constructor & Destructor Documentation
G4eplusPolarizedAnnihilation::G4eplusPolarizedAnnihilation (const G4String & name = "pol-annihil") explicit
Definition at line 73 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 73 of file G4eplusPolarizedAnnihilation.cc
References emModel, and G4VEmProcess::SetEmModel().
G4eplusPolarizedAnnihilation::~G4eplusPolarizedAnnihilation () virtual
Definition at line 84 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 84 of file G4eplusPolarizedAnnihilation.cc
References CleanTables().
G4eplusPolarizedAnnihilation::G4eplusPolarizedAnnihilation (const G4eplusPolarizedAnnihilation &) private
Member Function Documentation
void G4eplusPolarizedAnnihilation::BuildAsymmetryTables (const G4ParticleDefinition & part) private
Definition at line 248 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 248 of file G4eplusPolarizedAnnihilation.cc
References CleanTables(), ComputeAsymmetry(), G4PhysicsTable::GetFlag(), G4PhysicsVector::GetLowEdgeEnergy(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4VEmProcess::LambdaBinning(), G4VEmProcess::LambdaPhysicsVector(), G4PhysicsTableHelper::PreparePhysicsTable(), G4PhysicsVector::PutValue(), G4PhysicsTableHelper::SetPhysicsVector(), theAsymmetryTable, and theTransverseAsymmetryTable.
Referenced by BuildPhysicsTable().
void G4eplusPolarizedAnnihilation::BuildPhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VEmProcess.
Definition at line 235 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 235 of file G4eplusPolarizedAnnihilation.cc
References BuildAsymmetryTables(), G4VEmProcess::BuildPhysicsTable(), and G4VProcess::GetMasterProcess().
void G4eplusPolarizedAnnihilation::CleanTables () private
Definition at line 91 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 91 of file G4eplusPolarizedAnnihilation.cc
References G4PhysicsTable::clearAndDestroy(), theAsymmetryTable, and theTransverseAsymmetryTable.
Referenced by BuildAsymmetryTables(), and ~G4eplusPolarizedAnnihilation().
G4double G4eplusPolarizedAnnihilation::ComputeAsymmetry (G4double energy, const G4MaterialCutsCouple * couple, const G4ParticleDefinition & particle, G4double cut, G4double & tasm) private
Definition at line 292 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 292 of file G4eplusPolarizedAnnihilation.cc
References G4VEmModel::CrossSection(), emModel, G4PolarizedAnnihilationModel::SetBeamPolarization(), G4PolarizedAnnihilationModel::SetTargetPolarization(), and theTargetPolarization.
Referenced by BuildAsymmetryTables().
G4double G4eplusPolarizedAnnihilation::ComputeSaturationFactor (const G4Track & aTrack) private
Definition at line 165 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 165 of file G4eplusPolarizedAnnihilation.cc
References G4VEmProcess::CurrentMaterialCutsCoupleIndex(), G4cout, G4endl, G4Exception(), G4Track::GetDynamicParticle(), G4PolarizationManager::GetInstance(), G4DynamicParticle::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4PolarizationHelper::GetParticleFrameX(), G4PolarizationHelper::GetParticleFrameY(), G4Track::GetPolarization(), G4Track::GetVolume(), G4PolarizationManager::GetVolumePolarization(), G4PolarizationManager::IsPolarized(), JustWarning, G4PhysicsVector::Value(), G4VProcess::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GetMeanFreePath(), and PostStepGetPhysicalInteractionLength().
G4double G4eplusPolarizedAnnihilation::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VEmProcess.
Definition at line 107 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 107 of file G4eplusPolarizedAnnihilation.cc
References ComputeSaturationFactor(), DBL_MAX, G4cout, G4endl, G4VEmProcess::GetMeanFreePath(), mfp, mm, theAsymmetryTable, theTransverseAsymmetryTable, and G4VProcess::verboseLevel.
G4eplusPolarizedAnnihilation& G4eplusPolarizedAnnihilation::operator= (const G4eplusPolarizedAnnihilation & right) private
G4double G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VEmProcess.
Definition at line 125 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 125 of file G4eplusPolarizedAnnihilation.cc
References ComputeSaturationFactor(), G4VProcess::currentInteractionLength, DBL_MAX, G4cout, G4endl, max, mm, G4VEmProcess::PostStepGetPhysicalInteractionLength(), theAsymmetryTable, G4VProcess::theNumberOfInteractionLengthLeft, theTransverseAsymmetryTable, G4VProcess::verboseLevel, and x.
void G4eplusPolarizedAnnihilation::PrintInfo () override virtual
Reimplemented from G4VEmProcess.
Definition at line 329 of file G4eplusPolarizedAnnihilation.cc.
View newest version in sPHENIX GitHub at line 329 of file G4eplusPolarizedAnnihilation.cc
References G4cout, and G4endl.
Member Data Documentation
G4PolarizedAnnihilationModel* G4eplusPolarizedAnnihilation::emModel private
Definition at line 105 of file G4eplusPolarizedAnnihilation.hh.
View newest version in sPHENIX GitHub at line 105 of file G4eplusPolarizedAnnihilation.hh
Referenced by ComputeAsymmetry(), and G4eplusPolarizedAnnihilation().
G4bool G4eplusPolarizedAnnihilation::isInitialised private
Definition at line 102 of file G4eplusPolarizedAnnihilation.hh.
View newest version in sPHENIX GitHub at line 102 of file G4eplusPolarizedAnnihilation.hh
G4PhysicsTable* G4eplusPolarizedAnnihilation::theAsymmetryTable private
Definition at line 108 of file G4eplusPolarizedAnnihilation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4eplusPolarizedAnnihilation.hh
Referenced by BuildAsymmetryTables(), CleanTables(), GetMeanFreePath(), and PostStepGetPhysicalInteractionLength().
G4ThreeVector G4eplusPolarizedAnnihilation::theTargetPolarization private
Definition at line 106 of file G4eplusPolarizedAnnihilation.hh.
View newest version in sPHENIX GitHub at line 106 of file G4eplusPolarizedAnnihilation.hh
Referenced by ComputeAsymmetry().
G4PhysicsTable* G4eplusPolarizedAnnihilation::theTransverseAsymmetryTable private
Definition at line 109 of file G4eplusPolarizedAnnihilation.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eplusPolarizedAnnihilation.hh
Referenced by BuildAsymmetryTables(), CleanTables(), GetMeanFreePath(), and PostStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4eplusPolarizedAnnihilation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4eplusPolarizedAnnihilation.cc