ECCE @ EIC Software: G4TritonBuilder Class Reference
G4TritonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4TritonBuilder.hh>
Public Member Functions
G4TritonBuilder ()
virtual ~G4TritonBuilder ()
virtual void Build () finaloverride
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TritonInelasticProcess * theTritonInelastic
std::vector< G4VTritonBuilder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 48 of file G4TritonBuilder.hh.
View newest version in sPHENIX GitHub at line 48 of file G4TritonBuilder.hh
Constructor & Destructor Documentation
G4TritonBuilder::G4TritonBuilder ()
Definition at line 57 of file G4TritonBuilder.cc.
View newest version in sPHENIX GitHub at line 57 of file G4TritonBuilder.cc
References theTritonInelastic.
virtual G4TritonBuilder::~G4TritonBuilder () inline virtual
Definition at line 52 of file G4TritonBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4TritonBuilder.hh
Member Function Documentation
void G4TritonBuilder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 44 of file G4TritonBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4TritonBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4ParticleDefinition::GetProcessManager(), theModelCollections, theTritonInelastic, G4Triton::Triton(), and wasActivated.
void G4TritonBuilder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 62 of file G4TritonBuilder.cc.
View newest version in sPHENIX GitHub at line 62 of file G4TritonBuilder.cc
References G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Member Data Documentation
std::vector<G4VTritonBuilder *> G4TritonBuilder::theModelCollections private
Definition at line 62 of file G4TritonBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4TritonBuilder.hh
Referenced by Build(), and RegisterMe().
G4TritonInelasticProcess* G4TritonBuilder::theTritonInelastic private
Definition at line 60 of file G4TritonBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4TritonBuilder.hh
Referenced by Build(), and G4TritonBuilder().
G4bool G4TritonBuilder::wasActivated private
Definition at line 64 of file G4TritonBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4TritonBuilder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4TritonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4TritonBuilder.cc