ECCE @ EIC Software: G4DecayStrongResonances Class Reference
G4DecayStrongResonances Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4DecayStrongResonances.hh>
Public Member Functions
G4DecayStrongResonances ()
~G4DecayStrongResonances ()
G4ReactionProductVector * Propagate (G4KineticTrackVector *theSecondaries, G4V3DNucleus *)
Private Member Functions
G4bool operator== (G4DecayStrongResonances &right)
G4bool operator!= (G4DecayStrongResonances &right)
Detailed Description
Definition at line 45 of file G4DecayStrongResonances.hh.
View newest version in sPHENIX GitHub at line 45 of file G4DecayStrongResonances.hh
Constructor & Destructor Documentation
G4DecayStrongResonances::G4DecayStrongResonances ()
Definition at line 44 of file G4DecayStrongResonances.cc.
View newest version in sPHENIX GitHub at line 44 of file G4DecayStrongResonances.cc
G4DecayStrongResonances::~G4DecayStrongResonances ()
Definition at line 46 of file G4DecayStrongResonances.cc.
View newest version in sPHENIX GitHub at line 46 of file G4DecayStrongResonances.cc
Member Function Documentation
G4bool G4DecayStrongResonances::operator!= (G4DecayStrongResonances & right) inline private
Definition at line 53 of file G4DecayStrongResonances.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DecayStrongResonances.hh
G4bool G4DecayStrongResonances::operator== (G4DecayStrongResonances & right) inline private
Definition at line 52 of file G4DecayStrongResonances.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DecayStrongResonances.hh
G4ReactionProductVector * G4DecayStrongResonances::Propagate (G4KineticTrackVector * theSecondaries, G4V3DNucleus *)
Definition at line 49 of file G4DecayStrongResonances.cc.
View newest version in sPHENIX GitHub at line 49 of file G4DecayStrongResonances.cc
References G4INCL::ClusterDecay::decay(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGMass(), it, G4ReactionProduct::SetDefinition(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), CLHEP::HepLorentzVector::t(), and CLHEP::HepLorentzVector::vect().
Referenced by G4TheoFSGenerator::ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4DecayStrongResonances.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4DecayStrongResonances.cc