ECCE @ EIC Software: G4HumanPhantomEventAction Class Reference
G4HumanPhantomEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomEventAction.hh>
Public Member Functions
G4HumanPhantomEventAction ()
~G4HumanPhantomEventAction ()
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
void Fill (G4String bodypartName, G4double energyDeposit)
void totalEventEnergyDeposit ()
Private Attributes
G4int hitCollectionID
std::map< std::string, G4double > energyTotal
G4String bodypartName
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 38 of file G4HumanPhantomEventAction.hh.
View newest version in sPHENIX GitHub at line 38 of file G4HumanPhantomEventAction.hh
Constructor & Destructor Documentation
G4HumanPhantomEventAction::G4HumanPhantomEventAction ()
Definition at line 39 of file G4HumanPhantomEventAction.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HumanPhantomEventAction.cc
G4HumanPhantomEventAction::~G4HumanPhantomEventAction ()
Definition at line 45 of file G4HumanPhantomEventAction.cc.
View newest version in sPHENIX GitHub at line 45 of file G4HumanPhantomEventAction.cc
Member Function Documentation
void G4HumanPhantomEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Definition at line 49 of file G4HumanPhantomEventAction.cc.
View newest version in sPHENIX GitHub at line 49 of file G4HumanPhantomEventAction.cc
References energyTotal, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), and hitCollectionID.
void G4HumanPhantomEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 101 of file G4HumanPhantomEventAction.cc.
View newest version in sPHENIX GitHub at line 101 of file G4HumanPhantomEventAction.cc
References edep, G4THitsCollection< T >::entries(), Fill(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), hitCollectionID, and totalEventEnergyDeposit().
void G4HumanPhantomEventAction::Fill (G4String bodypartName, G4double energyDeposit) private
Definition at line 128 of file G4HumanPhantomEventAction.cc.
View newest version in sPHENIX GitHub at line 128 of file G4HumanPhantomEventAction.cc
References energyTotal.
Referenced by EndOfEventAction().
void G4HumanPhantomEventAction::totalEventEnergyDeposit () private
Definition at line 135 of file G4HumanPhantomEventAction.cc.
View newest version in sPHENIX GitHub at line 135 of file G4HumanPhantomEventAction.cc
References energyTotal, G4HumanPhantomRunAction::Fill(), G4RunManager::GetRunManager(), and G4RunManager::GetUserRunAction().
Referenced by EndOfEventAction().
Member Data Documentation
G4String G4HumanPhantomEventAction::bodypartName private
Definition at line 54 of file G4HumanPhantomEventAction.hh.
View newest version in sPHENIX GitHub at line 54 of file G4HumanPhantomEventAction.hh
std::map<std::string,G4double> G4HumanPhantomEventAction::energyTotal private
Definition at line 53 of file G4HumanPhantomEventAction.hh.
View newest version in sPHENIX GitHub at line 53 of file G4HumanPhantomEventAction.hh
Referenced by BeginOfEventAction(), Fill(), and totalEventEnergyDeposit().
G4int G4HumanPhantomEventAction::hitCollectionID private
Definition at line 52 of file G4HumanPhantomEventAction.hh.
View newest version in sPHENIX GitHub at line 52 of file G4HumanPhantomEventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4HumanPhantomEventAction.cc