ECCE @ EIC Software: G4DensityEffectData Class Reference
G4DensityEffectData Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4DensityEffectData.hh>
Public Member Functions
G4DensityEffectData ()
~G4DensityEffectData ()
G4int GetElementIndex (G4int Z, G4State mState) const
G4int GetIndex (const G4String &matName) const
void PrintData (const G4String &matName) const
void DumpData () const
G4double GetPlasmaEnergy (G4int idx) const
G4double GetAdjustmentFactor (G4int idx) const
G4double GetCdensity (G4int idx) const
G4double GetX0density (G4int idx) const
G4double GetX1density (G4int idx) const
G4double GetAdensity (G4int idx) const
G4double GetMdensity (G4int idx) const
G4double GetDelta0density (G4int idx) const
G4double GetErrorDensity (G4int idx) const
G4double GetMeanIonisationPotential (G4int idx) const
Private Member Functions
void Initialize ()
void AddMaterial (G4double *val, const G4String &matName)
G4DensityEffectData & operator= (const G4DensityEffectData &right)=delete
G4DensityEffectData (const G4DensityEffectData &)=delete
Private Attributes
G4double data [NDENSDATA][NDENSARRAY]
std::vector< G4String > names
G4int indexZ [NDENSELEM]
G4State state [NDENSELEM]
G4int index
Detailed Description
Definition at line 60 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 60 of file G4DensityEffectData.hh
Constructor & Destructor Documentation
G4DensityEffectData::G4DensityEffectData () explicit
Definition at line 52 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 52 of file G4DensityEffectData.cc
References Initialize().
G4DensityEffectData::~G4DensityEffectData ()
Definition at line 59 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 59 of file G4DensityEffectData.cc
G4DensityEffectData::G4DensityEffectData (const G4DensityEffectData &) private delete
Member Function Documentation
void G4DensityEffectData::AddMaterial (G4double * val, const G4String & matName) private
Definition at line 1324 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 1324 of file G4DensityEffectData.cc
References CLHEP::eV, index, names, and NDENSARRAY.
Referenced by Initialize().
void G4DensityEffectData::DumpData () const
Definition at line 1361 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 1361 of file G4DensityEffectData.cc
References eV, G4cout, G4endl, names, NDENSARRAY, and NDENSDATA.
Referenced by PrintData().
G4double G4DensityEffectData::GetAdensity (G4int idx) const inline
Definition at line 138 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 138 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
G4double G4DensityEffectData::GetAdjustmentFactor (G4int idx) const inline
Definition at line 118 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 118 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
G4double G4DensityEffectData::GetCdensity (G4int idx) const inline
Definition at line 123 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 123 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
G4double G4DensityEffectData::GetDelta0density (G4int idx) const inline
Definition at line 148 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 148 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
G4int G4DensityEffectData::GetElementIndex (G4int Z, G4State mState) const
Definition at line 1301 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 1301 of file G4DensityEffectData.cc
References incremental_prev_tag::idx, indexZ, kStateUndefined, NDENSELEM, state, and Z.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters(), and G4ICRU73QOModel::GetOscillatorEnergy().
G4double G4DensityEffectData::GetErrorDensity (G4int idx) const inline
Definition at line 153 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 153 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
G4int G4DensityEffectData::GetIndex (const G4String & matName) const
Definition at line 1311 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 1311 of file G4DensityEffectData.cc
References incremental_prev_tag::idx, names, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters(), G4IonisParamMat::FindMeanExcitationEnergy(), and PrintData().
G4double G4DensityEffectData::GetMdensity (G4int idx) const inline
Definition at line 143 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 143 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
G4double G4DensityEffectData::GetMeanIonisationPotential (G4int idx) const inline
Definition at line 158 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 158 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::FindMeanExcitationEnergy().
G4double G4DensityEffectData::GetPlasmaEnergy (G4int idx) const inline
Definition at line 113 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 113 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters(), and G4ICRU73QOModel::GetOscillatorEnergy().
G4double G4DensityEffectData::GetX0density (G4int idx) const inline
Definition at line 128 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 128 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
G4double G4DensityEffectData::GetX1density (G4int idx) const inline
Definition at line 133 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 133 of file G4DensityEffectData.hh
References DBL_MAX, incremental_prev_tag::idx, and NDENSDATA.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters().
void G4DensityEffectData::Initialize () private
Definition at line 63 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 63 of file G4DensityEffectData.cc
References AddMaterial(), indexZ, kStateGas, kStateSolid, M10, M11, M12, M13, M14, M20, M21, M22, M23, M24, M30, M31, M32, M33, M34, M40, M41, M42, M43, M44, NDENSARRAY, NDENSELEM, and state.
Referenced by G4DensityEffectData().
G4DensityEffectData& G4DensityEffectData::operator= (const G4DensityEffectData & right) private delete
void G4DensityEffectData::PrintData (const G4String & matName) const
Definition at line 1335 of file G4DensityEffectData.cc.
View newest version in sPHENIX GitHub at line 1335 of file G4DensityEffectData.cc
References DumpData(), CLHEP::eV, G4cout, G4endl, GetIndex(), and incremental_prev_tag::idx.
Referenced by G4NistMessenger::SetNewValue().
Member Data Documentation
G4double G4DensityEffectData::data[NDENSDATA][NDENSARRAY] private
Definition at line 102 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 102 of file G4DensityEffectData.hh
G4int G4DensityEffectData::index private
Definition at line 109 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 109 of file G4DensityEffectData.hh
Referenced by AddMaterial().
G4int G4DensityEffectData::indexZ[NDENSELEM] private
Definition at line 106 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 106 of file G4DensityEffectData.hh
Referenced by GetElementIndex(), and Initialize().
std::vector<G4String> G4DensityEffectData::names private
Definition at line 103 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 103 of file G4DensityEffectData.hh
Referenced by AddMaterial(), DumpData(), and GetIndex().
G4State G4DensityEffectData::state[NDENSELEM] private
Definition at line 107 of file G4DensityEffectData.hh.
View newest version in sPHENIX GitHub at line 107 of file G4DensityEffectData.hh
Referenced by GetElementIndex(), and Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4DensityEffectData.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4DensityEffectData.cc