ECCE @ EIC Software: G4EzWorld Class Reference
G4EzWorld Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/G4EzWorld.hh>
Public Member Functions
G4EzWorld ()
~G4EzWorld ()
Static Public Member Functions
static G4VPhysicalVolume * GetWorldVolume ()
static void Reset (G4double dx, G4double dy, G4double dz)
static void Resize (G4double dx, G4double dy, G4double dz)
static void SetMaterial (G4Material *amaterial)
static void SetVisibility (G4bool qvis)
Static Protected Member Functions
static G4VPhysicalVolume * CreateWorld (G4double dx=1.*m, G4double dy=1.*m, G4double dz=1.*m)
Static Protected Attributes
static G4VPhysicalVolume * world = G4EzWorld::CreateWorld()
Detailed Description
Definition at line 49 of file G4EzWorld.hh.
View newest version in sPHENIX GitHub at line 49 of file G4EzWorld.hh
Constructor & Destructor Documentation
G4EzWorld::G4EzWorld ()
Definition at line 50 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 50 of file G4EzWorld.cc
G4EzWorld::~G4EzWorld ()
Definition at line 56 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 56 of file G4EzWorld.cc
References world.
Member Function Documentation
G4VPhysicalVolume * G4EzWorld::CreateWorld (G4double dx = 1.*m, G4double dy = 1.*m, G4double dz = 1.*m) static protected
Definition at line 65 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 65 of file G4EzWorld.cc
References Acts::UnitConstants::g, G4Material::GetMaterial(), mole, and source.hepunit::universe_mean_density.
Referenced by Reset().
G4VPhysicalVolume * G4EzWorld::GetWorldVolume () inline static
Definition at line 73 of file G4EzWorld.hh.
View newest version in sPHENIX GitHub at line 73 of file G4EzWorld.hh
References world.
Referenced by EzDetectorConstruction::Construct().
void G4EzWorld::Reset (G4double dx, G4double dy, G4double dz) static
Definition at line 96 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 96 of file G4EzWorld.cc
References CreateWorld(), G4RunManager::GetRunManager(), and world.
Referenced by pyEZgeom::ResetWorld().
void G4EzWorld::Resize (G4double dx, G4double dy, G4double dz) static
Definition at line 108 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 108 of file G4EzWorld.cc
References pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and world.
Referenced by pyEZgeom::ResizeWorld().
void G4EzWorld::SetMaterial (G4Material * amaterial) static
Definition at line 122 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 122 of file G4EzWorld.cc
References world.
Referenced by pyEZgeom::SetWorldMaterial().
void G4EzWorld::SetVisibility (G4bool qvis) static
Definition at line 130 of file G4EzWorld.cc.
View newest version in sPHENIX GitHub at line 130 of file G4EzWorld.cc
References world.
Referenced by pyEZgeom::SetWorldVisibility().
Member Data Documentation
G4VPhysicalVolume * G4EzWorld::world = G4EzWorld::CreateWorld() static protected
Definition at line 52 of file G4EzWorld.hh.
View newest version in sPHENIX GitHub at line 52 of file G4EzWorld.hh
Referenced by test.MyDetectorConstruction::__init__(), test.MyDetectorConstruction::Construct(), GetWorldVolume(), Reset(), Resize(), SetMaterial(), SetVisibility(), and ~G4EzWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/G4EzWorld.hh
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/G4EzWorld.cc