ECCE @ EIC Software: G4RDVeLowEnergyLoss Class Reference
G4RDVeLowEnergyLoss Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDVeLowEnergyLoss.hh>
Public Member Functions
G4RDVeLowEnergyLoss (const G4String &, G4ProcessType aType=fNotDefined)
G4RDVeLowEnergyLoss (G4RDVeLowEnergyLoss &)
virtual ~G4RDVeLowEnergyLoss ()
virtual G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)=0
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &Step)=0
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)=0
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &Step)=0
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static void SetRndmStep (G4bool value)
static void SetEnlossFluc (G4bool value)
static void SetStepFunction (G4double c1, G4double c2)
Protected Member Functions
G4double GetLossWithFluct (const G4DynamicParticle *aParticle, const G4MaterialCutsCouple *couple, G4double MeanLoss, G4double step)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Static Protected Member Functions
static G4PhysicsTable * BuildRangeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *theRangeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildLabTimeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *theLabTimeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildProperTimeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *ProperTimeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffATable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffATable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffBTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffBTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffCTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffCTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildInverseRangeTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theRangeCoeffATable, G4PhysicsTable *theRangeCoeffBTable, G4PhysicsTable *theRangeCoeffCTable, G4PhysicsTable *theInverseRangeTable, G4double Tmin, G4double Tmax, G4int nbin)
Protected Attributes
const G4Material * lastMaterial
G4int imat
G4double f1Fluct
G4double f2Fluct
G4double e1Fluct
G4double e2Fluct
G4double rateFluct
G4double ipotFluct
G4double e1LogFluct
G4double e2LogFluct
G4double ipotLogFluct
const G4int nmaxCont1
const G4int nmaxCont2
Static Protected Attributes
static G4double ParticleMass
static G4double taulow
static G4double tauhigh
static G4double ltaulow
static G4double ltauhigh
static G4double dRoverRange = 20*perCent
static G4double finalRange = 200*micrometer
static G4double c1lim = dRoverRange
static G4double c2lim = 2.*(1.-dRoverRange)*finalRange
static G4double c3lim = -(1.-dRoverRange)*finalRange*finalRange
static G4bool rndmStepFlag = false
static G4bool EnlossFlucFlag = true
Private Member Functions
G4RDVeLowEnergyLoss ()
G4RDVeLowEnergyLoss & operator= (const G4RDVeLowEnergyLoss &right)
Static Private Member Functions
static void BuildRangeVector (G4PhysicsTable *theDEDXTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector *rangeVector)
static void BuildRangeVectorNew (const G4PhysicsTable *, G4int, G4int, G4PhysicsLogVector *)
static G4double RangeIntLin (G4PhysicsVector *physicsVector, G4int nbin)
static G4double RangeIntLog (G4PhysicsVector *physicsVector, G4int nbin)
static void BuildLabTimeVector (G4PhysicsTable *theDEDXTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector *rangeVector)
static void BuildProperTimeVector (G4PhysicsTable *theDEDXTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector *rangeVector)
static G4double LabTimeIntLog (G4PhysicsVector *physicsVector, G4int nbin)
static G4double ProperTimeIntLog (G4PhysicsVector *physicsVector, G4int nbin)
static void InvertRangeVector (G4PhysicsTable *theRangeTable, G4PhysicsTable *theRangeCoeffATable, G4PhysicsTable *theRangeCoeffBTable, G4PhysicsTable *theRangeCoeffCTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector *rangeVector)
Detailed Description
Definition at line 76 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RDVeLowEnergyLoss.hh
Constructor & Destructor Documentation
G4RDVeLowEnergyLoss::G4RDVeLowEnergyLoss (const G4String & aName, G4ProcessType aType = fNotDefined)
Definition at line 83 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 83 of file G4RDVeLowEnergyLoss.cc
G4RDVeLowEnergyLoss::G4RDVeLowEnergyLoss (G4RDVeLowEnergyLoss & right)
Definition at line 99 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 99 of file G4RDVeLowEnergyLoss.cc
G4RDVeLowEnergyLoss::~G4RDVeLowEnergyLoss () virtual
Definition at line 93 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 93 of file G4RDVeLowEnergyLoss.cc
G4RDVeLowEnergyLoss::G4RDVeLowEnergyLoss () private
Definition at line 71 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 71 of file G4RDVeLowEnergyLoss.cc
References FatalException, and G4Exception().
Member Function Documentation
virtual G4VParticleChange* G4RDVeLowEnergyLoss::AlongStepDoIt (const G4Track & track, const G4Step & Step) pure virtual
Reimplemented from G4VContinuousDiscreteProcess.
Implemented in G4eLowEnergyLoss.
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildInverseRangeTable (G4PhysicsTable * theRangeTable, G4PhysicsTable * theRangeCoeffATable, G4PhysicsTable * theRangeCoeffBTable, G4PhysicsTable * theRangeCoeffCTable, G4PhysicsTable * theInverseRangeTable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 512 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 512 of file G4RDVeLowEnergyLoss.cc
References b, G4PhysicsTable::clearAndDestroy(), e, G4PhysicsVector::GetLowEdgeEnergy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsVector::GetValue(), G4PhysicsVector::GetVectorLength(), G4PhysicsTable::insert(), G4PhysicsVector::PutValue(), and v.
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildLabTimeTable (G4PhysicsTable * theDEDXTable, G4PhysicsTable * theLabTimeTable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 260 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 260 of file G4RDVeLowEnergyLoss.cc
References BuildLabTimeVector(), G4PhysicsTable::clearAndDestroy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), and G4PhysicsTable::insert().
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
void G4RDVeLowEnergyLoss::BuildLabTimeVector (G4PhysicsTable * theDEDXTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector * rangeVector) static private
Definition at line 326 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 326 of file G4RDVeLowEnergyLoss.cc
References source.hepunit::c_light, G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetValue(), keV, LabTimeIntLog(), ltauhigh, ltaulow, ParticleMass, and G4PhysicsVector::PutValue().
Referenced by BuildLabTimeTable().
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildProperTimeTable (G4PhysicsTable * theDEDXTable, G4PhysicsTable * ProperTimeTable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 293 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 293 of file G4RDVeLowEnergyLoss.cc
References BuildProperTimeVector(), G4PhysicsTable::clearAndDestroy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), and G4PhysicsTable::insert().
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
void G4RDVeLowEnergyLoss::BuildProperTimeVector (G4PhysicsTable * theDEDXTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector * rangeVector) static private
Definition at line 386 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 386 of file G4RDVeLowEnergyLoss.cc
References source.hepunit::c_light, G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetValue(), keV, ltauhigh, ltaulow, ParticleMass, ProperTimeIntLog(), and G4PhysicsVector::PutValue().
Referenced by BuildProperTimeTable().
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildRangeCoeffATable (G4PhysicsTable * theRangeTable, G4PhysicsTable * theCoeffATable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 637 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 637 of file G4RDVeLowEnergyLoss.cc
References G4PhysicsTable::clearAndDestroy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsVector::GetValue(), G4PhysicsTable::insert(), G4PhysicsVector::PutValue(), and w.
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildRangeCoeffBTable (G4PhysicsTable * theRangeTable, G4PhysicsTable * theCoeffBTable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 699 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 699 of file G4RDVeLowEnergyLoss.cc
References G4PhysicsTable::clearAndDestroy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsVector::GetValue(), G4PhysicsTable::insert(), G4PhysicsVector::PutValue(), and w.
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildRangeCoeffCTable (G4PhysicsTable * theRangeTable, G4PhysicsTable * theCoeffCTable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 760 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 760 of file G4RDVeLowEnergyLoss.cc
References G4PhysicsTable::clearAndDestroy(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsVector::GetValue(), G4PhysicsTable::insert(), G4PhysicsVector::PutValue(), and w.
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
G4PhysicsTable * G4RDVeLowEnergyLoss::BuildRangeTable (G4PhysicsTable * theDEDXTable, G4PhysicsTable * theRangeTable, G4double Tmin, G4double Tmax, G4int nbin) static protected
Definition at line 126 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 126 of file G4RDVeLowEnergyLoss.cc
References BuildRangeVector(), G4PhysicsTable::clearAndDestroy(), G4PhysicsTable::insert(), and G4PhysicsTable::length().
Referenced by G4eLowEnergyLoss::BuildDEDXTable().
void G4RDVeLowEnergyLoss::BuildRangeVector (G4PhysicsTable * theDEDXTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector * rangeVector) static private
Definition at line 157 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 157 of file G4RDVeLowEnergyLoss.cc
References energy, G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetValue(), n, and G4PhysicsVector::PutValue().
Referenced by BuildRangeTable().
static void G4RDVeLowEnergyLoss::BuildRangeVectorNew (const G4PhysicsTable * , G4int , G4int , G4PhysicsLogVector *) static private
virtual G4double G4RDVeLowEnergyLoss::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) pure virtual
Implements G4VContinuousDiscreteProcess.
Implemented in G4eLowEnergyLoss.
G4double G4RDVeLowEnergyLoss::GetLossWithFluct (const G4DynamicParticle * aParticle, const G4MaterialCutsCouple * couple, G4double MeanLoss, G4double step) protected
Definition at line 821 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 821 of file G4RDVeLowEnergyLoss.cc
References C(), e1Fluct, e1LogFluct, e2Fluct, e2LogFluct, source.hepunit::electron_mass_c2, eV, f1Fluct, f2Fluct, G4Poisson(), G4UniformRand, G4Material::GetElectronDensity(), G4IonisParamMat::GetEnergy0fluct(), G4IonisParamMat::GetEnergy1fluct(), G4IonisParamMat::GetEnergy2fluct(), G4IonisParamMat::GetF1fluct(), G4IonisParamMat::GetF2fluct(), G4MaterialCutsCouple::GetIndex(), G4Material::GetIonisation(), G4DynamicParticle::GetKineticEnergy(), G4IonisParamMat::GetLogEnergy1fluct(), G4IonisParamMat::GetLogEnergy2fluct(), G4IonisParamMat::GetLogMeanExcEnergy(), G4MaterialCutsCouple::GetMaterial(), G4IonisParamMat::GetMeanExcitationEnergy(), G4ProductionCutsTable::GetProductionCutsTable(), G4IonisParamMat::GetRateionexcfluct(), imat, ipotFluct, ipotLogFluct, k, lastMaterial, max, nmaxCont1, nmaxCont2, ParticleMass, rateFluct, G4INCL::DeJongSpin::shoot(), source.hepunit::twopi_mc2_rcl2, and w.
Referenced by G4eLowEnergyLoss::AlongStepDoIt().
virtual G4double G4RDVeLowEnergyLoss::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) pure virtual
Implements G4VContinuousDiscreteProcess.
Implemented in G4eLowEnergyLoss, G4LowEnergyBremsstrahlung, and G4LowEnergyIonisation.
void G4RDVeLowEnergyLoss::InvertRangeVector (G4PhysicsTable * theRangeTable, G4PhysicsTable * theRangeCoeffATable, G4PhysicsTable * theRangeCoeffBTable, G4PhysicsTable * theRangeCoeffCTable, G4double Tmin, G4double Tmax, G4int nbin, G4int materialIndex, G4PhysicsLogVector * rangeVector) static private
Definition at line 581 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 581 of file G4RDVeLowEnergyLoss.cc
References A(), B(), C(), G4PhysicsVector::GetLowEdgeEnergy(), and G4PhysicsVector::PutValue().
G4double G4RDVeLowEnergyLoss::LabTimeIntLog (G4PhysicsVector * physicsVector, G4int nbin) static private
Definition at line 446 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 446 of file G4RDVeLowEnergyLoss.cc
References source.hepunit::c_light, G4PhysicsVector::GetValue(), ltauhigh, ltaulow, and ParticleMass.
Referenced by BuildLabTimeVector().
G4RDVeLowEnergyLoss& G4RDVeLowEnergyLoss::operator= (const G4RDVeLowEnergyLoss & right) private
virtual G4VParticleChange* G4RDVeLowEnergyLoss::PostStepDoIt (const G4Track & track, const G4Step & Step) pure virtual
Reimplemented from G4VContinuousDiscreteProcess.
Implemented in G4eLowEnergyLoss, G4LowEnergyBremsstrahlung, and G4LowEnergyIonisation.
G4double G4RDVeLowEnergyLoss::ProperTimeIntLog (G4PhysicsVector * physicsVector, G4int nbin) static private
Definition at line 479 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 479 of file G4RDVeLowEnergyLoss.cc
References source.hepunit::c_light, G4PhysicsVector::GetValue(), ltauhigh, ltaulow, and ParticleMass.
Referenced by BuildProperTimeVector().
G4double G4RDVeLowEnergyLoss::RangeIntLin (G4PhysicsVector * physicsVector, G4int nbin) static private
Definition at line 195 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 195 of file G4RDVeLowEnergyLoss.cc
References G4PhysicsVector::GetValue(), ParticleMass, tauhigh, and taulow.
G4double G4RDVeLowEnergyLoss::RangeIntLog (G4PhysicsVector * physicsVector, G4int nbin) static private
Definition at line 226 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 226 of file G4RDVeLowEnergyLoss.cc
References G4PhysicsVector::GetValue(), ltauhigh, ltaulow, and ParticleMass.
void G4RDVeLowEnergyLoss::SetEnlossFluc (G4bool value) static
Definition at line 112 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 112 of file G4RDVeLowEnergyLoss.cc
References EnlossFlucFlag.
void G4RDVeLowEnergyLoss::SetRndmStep (G4bool value) static
Definition at line 107 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 107 of file G4RDVeLowEnergyLoss.cc
References rndmStepFlag.
void G4RDVeLowEnergyLoss::SetStepFunction (G4double c1, G4double c2) static
Definition at line 117 of file G4RDVeLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 117 of file G4RDVeLowEnergyLoss.cc
References c1, c1lim, c2, c2lim, c3lim, dRoverRange, and finalRange.
Member Data Documentation
G4double G4RDVeLowEnergyLoss::c1lim = dRoverRange static protected
Definition at line 236 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 236 of file G4RDVeLowEnergyLoss.hh
Referenced by SetStepFunction().
G4double G4RDVeLowEnergyLoss::c2lim = 2.*(1.-dRoverRange)*finalRange static protected
Definition at line 236 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 236 of file G4RDVeLowEnergyLoss.hh
Referenced by SetStepFunction().
G4double G4RDVeLowEnergyLoss::c3lim = -(1.-dRoverRange)*finalRange*finalRange static protected
Definition at line 236 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 236 of file G4RDVeLowEnergyLoss.hh
Referenced by SetStepFunction().
G4double G4RDVeLowEnergyLoss::dRoverRange = 20*perCent static protected
Definition at line 233 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 233 of file G4RDVeLowEnergyLoss.hh
Referenced by SetStepFunction().
G4double G4RDVeLowEnergyLoss::e1Fluct protected
Definition at line 124 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::e1LogFluct protected
Definition at line 125 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 125 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::e2Fluct protected
Definition at line 124 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::e2LogFluct protected
Definition at line 125 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 125 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4bool G4RDVeLowEnergyLoss::EnlossFlucFlag = true static protected
Definition at line 239 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 239 of file G4RDVeLowEnergyLoss.hh
Referenced by G4eLowEnergyLoss::AlongStepDoIt(), and SetEnlossFluc().
G4double G4RDVeLowEnergyLoss::f1Fluct protected
Definition at line 124 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::f2Fluct protected
Definition at line 124 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::finalRange = 200*micrometer static protected
Definition at line 235 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 235 of file G4RDVeLowEnergyLoss.hh
Referenced by SetStepFunction().
G4int G4RDVeLowEnergyLoss::imat protected
Definition at line 123 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 123 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::ipotFluct protected
Definition at line 124 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::ipotLogFluct protected
Definition at line 125 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 125 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
const G4Material* G4RDVeLowEnergyLoss::lastMaterial protected
Definition at line 122 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 122 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::ltauhigh static protected
Definition at line 230 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 230 of file G4RDVeLowEnergyLoss.hh
Referenced by BuildLabTimeVector(), BuildProperTimeVector(), LabTimeIntLog(), ProperTimeIntLog(), and RangeIntLog().
G4double G4RDVeLowEnergyLoss::ltaulow static protected
Definition at line 230 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 230 of file G4RDVeLowEnergyLoss.hh
Referenced by BuildLabTimeVector(), BuildProperTimeVector(), LabTimeIntLog(), ProperTimeIntLog(), and RangeIntLog().
const G4int G4RDVeLowEnergyLoss::nmaxCont1 protected
Definition at line 127 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 127 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
const G4int G4RDVeLowEnergyLoss::nmaxCont2 protected
Definition at line 127 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 127 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4double G4RDVeLowEnergyLoss::ParticleMass static protected
Definition at line 230 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 230 of file G4RDVeLowEnergyLoss.hh
Referenced by G4eLowEnergyLoss::BuildDEDXTable(), BuildLabTimeVector(), BuildProperTimeVector(), GetLossWithFluct(), LabTimeIntLog(), ProperTimeIntLog(), RangeIntLin(), and RangeIntLog().
G4double G4RDVeLowEnergyLoss::rateFluct protected
Definition at line 124 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDVeLowEnergyLoss.hh
Referenced by GetLossWithFluct().
G4bool G4RDVeLowEnergyLoss::rndmStepFlag = false static protected
Definition at line 238 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 238 of file G4RDVeLowEnergyLoss.hh
Referenced by SetRndmStep().
G4double G4RDVeLowEnergyLoss::tauhigh static protected
Definition at line 230 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 230 of file G4RDVeLowEnergyLoss.hh
Referenced by RangeIntLin().
G4double G4RDVeLowEnergyLoss::taulow static protected
Definition at line 230 of file G4RDVeLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 230 of file G4RDVeLowEnergyLoss.hh
Referenced by RangeIntLin().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDVeLowEnergyLoss.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDVeLowEnergyLoss.cc