ECCE @ EIC Software: G4GIDI_target Class Reference
G4GIDI_target Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4GIDI_target.hh>
Public Member Functions
void init (const char *fileName)
G4GIDI_target (const char *fileName)
G4GIDI_target (std::string const &fileName)
~G4GIDI_target ()
std::string * getName (void)
std::string * getFilename (void)
int getZ (void)
int getA (void)
int getM (void)
double getMass (void)
int getTemperatures (double *temperatures)
int readTemperature (int index)
std::string getEqualProbableBinSampleMethod (void)
int setEqualProbableBinSampleMethod (std::string method)
int getNumberOfChannels (void)
int getNumberOfProductionChannels (void)
channelID getChannelsID (int channelIndex)
std::vector< channelID > * getChannelIDs (void)
std::vector< channelID > * getProductionChannelIDs (void)
std::vector< double > * getEnergyGridAtTIndex (int index)
double getTotalCrossSectionAtE (double e_in, double temperature)
double getElasticCrossSectionAtE (double e_in, double temperature)
double getCaptureCrossSectionAtE (double e_in, double temperature)
double getFissionCrossSectionAtE (double e_in, double temperature)
double getOthersCrossSectionAtE (double e_in, double temperature)
double sumChannelCrossSectionAtE (int nIndices, int *indices, double e_in, double temperature)
int sampleChannelCrossSectionAtE (int nIndices, int *indices, double e_in, double temperature, double(*rng)(void *), void *rngState)
double getElasticFinalState (double e_in, double temperature, double(*rng)(void *), void *rngState)
std::vector< G4GIDI_Product > * getCaptureFinalState (double e_in, double temperature, double(*rng)(void *), void *rngState)
std::vector< G4GIDI_Product > * getFissionFinalState (double e_in, double temperature, double(*rng)(void *), void *rngState)
std::vector< G4GIDI_Product > * getOthersFinalState (double e_in, double temperature, double(*rng)(void *), void *rngState)
std::vector< G4GIDI_Product > * getFinalState (int nIndices, int *indices, double e_in, double temperature, double(*rng)(void *), void *rngState)
double getReactionsThreshold (int index)
double getReactionsDomain (int index, double *EMin, double *EMax)
Public Attributes
std::string equalProbableBinSampleMethod
int nElasticIndices
int nCaptureIndices
int nFissionIndices
int nOthersIndices
int * elasticIndices
int * captureIndices
int * fissionIndices
int * othersIndices
GIDI::statusMessageReporting smr
int projectilesPOPID
std::string name
std::string sourceFilename
double mass
GIDI::MCGIDI_target * target
Detailed Description
Definition at line 58 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 58 of file G4GIDI_target.hh
Constructor & Destructor Documentation
G4GIDI_target::G4GIDI_target (const char * fileName)
Definition at line 44 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 44 of file G4GIDI_target.cc
References init().
G4GIDI_target::G4GIDI_target (std::string const & fileName)
Definition at line 51 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 51 of file G4GIDI_target.cc
References init().
G4GIDI_target::~G4GIDI_target ()
Definition at line 134 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 134 of file G4GIDI_target.cc
References MCGIDI_target_free(), smr_freeMemory(), and smr_release().
Member Function Documentation
int G4GIDI_target::getA (void)
Definition at line 158 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 158 of file G4GIDI_target.cc
double G4GIDI_target::getCaptureCrossSectionAtE (double e_in, double temperature)
Definition at line 284 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 284 of file G4GIDI_target.cc
Referenced by G4LENDCaptureCrossSection::getLENDCrossSection().
vector< G4GIDI_Product > * G4GIDI_target::getCaptureFinalState (double e_in, double temperature, double(*)(void *) rng, void * rngState)
Definition at line 371 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 371 of file G4GIDI_target.cc
Referenced by G4LENDCapture::ApplyYourself().
vector< channelID > * G4GIDI_target::getChannelIDs (void)
Definition at line 241 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 241 of file G4GIDI_target.cc
References MCGIDI_target_heated_getReactionAtIndex(), MCGIDI_target_numberOfReactions(), n, and MCGIDI_reaction_s::outputChannelStr.
channelID G4GIDI_target::getChannelsID (int channelIndex)
Definition at line 228 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 228 of file G4GIDI_target.cc
References MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_reaction_s::outputChannelStr, and smr_print().
double G4GIDI_target::getElasticCrossSectionAtE (double e_in, double temperature)
Definition at line 277 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 277 of file G4GIDI_target.cc
Referenced by G4LENDElasticCrossSection::getLENDCrossSection().
double G4GIDI_target::getElasticFinalState (double e_in, double temperature, double(*)(void *) rng, void * rngState)
Definition at line 342 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 342 of file G4GIDI_target.cc
References MCGIDI_decaySamplingInfo_s::isVelocity, MCGIDI_outputChannel_getProductAtIndex(), MCGIDI_product_sampleMu(), MCGIDI_quantityLookupMode_pointwise, MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_reaction_s::outputChannel, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_quantitiesLookupModes::setCrossSectionMode(), MCGIDI_quantitiesLookupModes::setProjectileEnergy(), MCGIDI_quantitiesLookupModes::setTemperature(), and smr_print().
Referenced by G4LENDModel::ApplyYourself(), and G4LENDElastic::ApplyYourself().
std::vector<double>* G4GIDI_target::getEnergyGridAtTIndex (int index)
string G4GIDI_target::getEqualProbableBinSampleMethod (void)
Definition at line 193 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 193 of file G4GIDI_target.cc
string * G4GIDI_target::getFilename (void)
Definition at line 147 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 147 of file G4GIDI_target.cc
vector< G4GIDI_Product > * G4GIDI_target::getFinalState (int nIndices, int * indices, double e_in, double temperature, double(*)(void *) rng, void * rngState)
Definition at line 392 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 392 of file G4GIDI_target.cc
References MCGIDI_POP_s::A, MCGIDI_sampledProductsData_s::birthTimeSec, MCGIDI_decaySamplingInfo_s::isVelocity, MCGIDI_sampledProductsData_s::kineticEnergy, MCGIDI_POP_s::m, MCGIDI_quantityLookupMode_pointwise, MCGIDI_sampledProducts_initialize(), MCGIDI_sampledProducts_release(), MCGIDI_target_heated_sampleIndexReactionProductsAtE(), n, MCGIDI_sampledProductsData_s::pop, MCGIDI_sampledProductsDatas_s::products, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, MCGIDI_sampledProductsData_s::pz_vz, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_quantitiesLookupModes::setCrossSectionMode(), MCGIDI_quantitiesLookupModes::setProjectileEnergy(), MCGIDI_quantitiesLookupModes::setTemperature(), smr_isOk(), smr_print(), and MCGIDI_POP_s::Z.
double G4GIDI_target::getFissionCrossSectionAtE (double e_in, double temperature)
Definition at line 291 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 291 of file G4GIDI_target.cc
Referenced by G4LENDFissionCrossSection::getLENDCrossSection().
vector< G4GIDI_Product > * G4GIDI_target::getFissionFinalState (double e_in, double temperature, double(*)(void *) rng, void * rngState)
Definition at line 378 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 378 of file G4GIDI_target.cc
Referenced by G4LENDFission::ApplyYourself().
int G4GIDI_target::getM (void)
Definition at line 165 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 165 of file G4GIDI_target.cc
double G4GIDI_target::getMass (void)
Definition at line 172 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 172 of file G4GIDI_target.cc
References mass.
string * G4GIDI_target::getName (void)
Definition at line 143 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 143 of file G4GIDI_target.cc
int G4GIDI_target::getNumberOfChannels (void)
Definition at line 214 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 214 of file G4GIDI_target.cc
References MCGIDI_target_numberOfReactions().
int G4GIDI_target::getNumberOfProductionChannels (void)
Definition at line 221 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 221 of file G4GIDI_target.cc
References MCGIDI_target_numberOfProductionReactions().
double G4GIDI_target::getOthersCrossSectionAtE (double e_in, double temperature)
Definition at line 298 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 298 of file G4GIDI_target.cc
Referenced by G4LENDInelasticCrossSection::getLENDCrossSection().
vector< G4GIDI_Product > * G4GIDI_target::getOthersFinalState (double e_in, double temperature, double(*)(void *) rng, void * rngState)
Definition at line 385 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 385 of file G4GIDI_target.cc
Referenced by G4LENDInelastic::ApplyYourself().
vector< channelID > * G4GIDI_target::getProductionChannelIDs (void)
Definition at line 257 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 257 of file G4GIDI_target.cc
double G4GIDI_target::getReactionsDomain (int index, double * EMin, double * EMax)
Definition at line 461 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 461 of file G4GIDI_target.cc
References MCGIDI_target_heated_getReactionsDomain().
double G4GIDI_target::getReactionsThreshold (int index)
Definition at line 454 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 454 of file G4GIDI_target.cc
References MCGIDI_target_heated_getReactionsThreshold().
int G4GIDI_target::getTemperatures (double * temperatures)
Definition at line 179 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 179 of file G4GIDI_target.cc
References MCGIDI_target_getTemperatures().
double G4GIDI_target::getTotalCrossSectionAtE (double e_in, double temperature)
Definition at line 264 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 264 of file G4GIDI_target.cc
References MCGIDI_quantityLookupMode_pointwise, MCGIDI_target_getTotalCrossSectionAtTAndE(), MCGIDI_quantitiesLookupModes::setCrossSectionMode(), MCGIDI_quantitiesLookupModes::setProjectileEnergy(), and MCGIDI_quantitiesLookupModes::setTemperature().
int G4GIDI_target::getZ (void)
Definition at line 151 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 151 of file G4GIDI_target.cc
void G4GIDI_target::init (const char * fileName)
Definition at line 58 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 58 of file G4GIDI_target.cc
References G4GIDI_targetMass(), mass, MCGIDI_reaction_getENDF_MTNumber(), MCGIDI_target_heated_getReactionAtIndex(), MCGIDI_target_newRead(), MCGIDI_target_numberOfReactions(), n, printf(), smr_initialize(), smr_isOk(), smr_malloc2, smr_print(), and smr_status_Ok.
int G4GIDI_target::readTemperature (int index)
Definition at line 186 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 186 of file G4GIDI_target.cc
References MCGIDI_target_readHeatedTarget().
int G4GIDI_target::sampleChannelCrossSectionAtE (int nIndices, int * indices, double e_in, double temperature, double(*)(void *) rng, void * rngState)
Definition at line 322 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 322 of file G4GIDI_target.cc
References MCGIDI_quantityLookupMode_pointwise, MCGIDI_target_getIndexReactionCrossSectionAtE(), MCGIDI_quantitiesLookupModes::setCrossSectionMode(), MCGIDI_quantitiesLookupModes::setProjectileEnergy(), and MCGIDI_quantitiesLookupModes::setTemperature().
int G4GIDI_target::setEqualProbableBinSampleMethod (std::string method)
Definition at line 200 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 200 of file G4GIDI_target.cc
double G4GIDI_target::sumChannelCrossSectionAtE (int nIndices, int * indices, double e_in, double temperature)
Definition at line 305 of file G4GIDI_target.cc.
View newest version in sPHENIX GitHub at line 305 of file G4GIDI_target.cc
References MCGIDI_quantityLookupMode_pointwise, MCGIDI_target_getIndexReactionCrossSectionAtE(), MCGIDI_quantitiesLookupModes::setCrossSectionMode(), MCGIDI_quantitiesLookupModes::setProjectileEnergy(), and MCGIDI_quantitiesLookupModes::setTemperature().
Member Data Documentation
int * G4GIDI_target::captureIndices
Definition at line 64 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 64 of file G4GIDI_target.hh
int* G4GIDI_target::elasticIndices
Definition at line 64 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 64 of file G4GIDI_target.hh
std::string G4GIDI_target::equalProbableBinSampleMethod
Definition at line 62 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 62 of file G4GIDI_target.hh
int * G4GIDI_target::fissionIndices
Definition at line 64 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 64 of file G4GIDI_target.hh
double G4GIDI_target::mass
Definition at line 71 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 71 of file G4GIDI_target.hh
std::string G4GIDI_target::name
Definition at line 69 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GIDI_target.hh
int G4GIDI_target::nCaptureIndices
Definition at line 63 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GIDI_target.hh
int G4GIDI_target::nElasticIndices
Definition at line 63 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GIDI_target.hh
int G4GIDI_target::nFissionIndices
Definition at line 63 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GIDI_target.hh
int G4GIDI_target::nOthersIndices
Definition at line 63 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GIDI_target.hh
int * G4GIDI_target::othersIndices
Definition at line 64 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 64 of file G4GIDI_target.hh
int G4GIDI_target::projectilesPOPID
Definition at line 68 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 68 of file G4GIDI_target.hh
GIDI::statusMessageReporting G4GIDI_target::smr
Definition at line 67 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 67 of file G4GIDI_target.hh
std::string G4GIDI_target::sourceFilename
Definition at line 70 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 70 of file G4GIDI_target.hh
GIDI::MCGIDI_target* G4GIDI_target::target
Definition at line 72 of file G4GIDI_target.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GIDI_target.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4GIDI_target.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4GIDI_target.cc