ECCE @ EIC Software: G4MPIrandomSeedGenerator Class Reference
G4MPIrandomSeedGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPIrandomSeedGenerator.hh>
Public Member Functions
G4MPIrandomSeedGenerator ()
~G4MPIrandomSeedGenerator ()
Public Member Functions inherited from G4VMPIseedGenerator
G4VMPIseedGenerator ()
virtual ~G4VMPIseedGenerator ()
void SetMasterSeed (G4long aseed)
G4long GetMasterSeed () const
const std::vector< G4long > & GetSeedList () const
Protected Member Functions
G4bool CheckDoubleCount ()
virtual void GenerateSeeds ()
Additional Inherited Members
Protected Attributes inherited from G4VMPIseedGenerator
G4long master_seed_
std::vector< G4long > seed_list_
Detailed Description
Definition at line 33 of file G4MPIrandomSeedGenerator.hh.
View newest version in sPHENIX GitHub at line 33 of file G4MPIrandomSeedGenerator.hh
Constructor & Destructor Documentation
G4MPIrandomSeedGenerator::G4MPIrandomSeedGenerator ()
Definition at line 34 of file G4MPIrandomSeedGenerator.cc.
View newest version in sPHENIX GitHub at line 34 of file G4MPIrandomSeedGenerator.cc
References GenerateSeeds().
G4MPIrandomSeedGenerator::~G4MPIrandomSeedGenerator ()
Definition at line 41 of file G4MPIrandomSeedGenerator.cc.
View newest version in sPHENIX GitHub at line 41 of file G4MPIrandomSeedGenerator.cc
Member Function Documentation
G4bool G4MPIrandomSeedGenerator::CheckDoubleCount () protected
Definition at line 46 of file G4MPIrandomSeedGenerator.cc.
View newest version in sPHENIX GitHub at line 46 of file G4MPIrandomSeedGenerator.cc
References G4UniformRand, G4MPImanager::GetManager(), G4VMPIseedGenerator::seed_list_, and x.
Referenced by GenerateSeeds().
void G4MPIrandomSeedGenerator::GenerateSeeds () protected virtual
Implements G4VMPIseedGenerator.
Definition at line 66 of file G4MPIrandomSeedGenerator.cc.
View newest version in sPHENIX GitHub at line 66 of file G4MPIrandomSeedGenerator.cc
References CheckDoubleCount(), G4UniformRand, G4MPImanager::GetManager(), seed, G4VMPIseedGenerator::seed_list_, and x.
Referenced by G4MPIrandomSeedGenerator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPIrandomSeedGenerator.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/src/G4MPIrandomSeedGenerator.cc