ECCE @ EIC Software: G4RadioactiveDecayChainsFromParent Class Reference
G4RadioactiveDecayChainsFromParent Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactiveDecayChainsFromParent.hh>
Public Member Functions
G4RadioactiveDecayChainsFromParent ()
virtual ~G4RadioactiveDecayChainsFromParent ()
G4RadioactiveDecayChainsFromParent (const G4RadioactiveDecayChainsFromParent &)
G4RadioactiveDecayChainsFromParent & operator= (const G4RadioactiveDecayChainsFromParent &)
G4bool operator== (const G4RadioactiveDecayChainsFromParent &right) const
G4bool operator!= (const G4RadioactiveDecayChainsFromParent &right) const
G4String GetIonName () const
void SetIonName (G4String name)
G4RadioactiveDecayRates GetItsRates () const
void SetItsRates (G4RadioactiveDecayRates arate)
Protected Attributes
G4String ionName
G4RadioactiveDecayRates itsRates
Detailed Description
Definition at line 65 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RadioactiveDecayChainsFromParent.hh
Constructor & Destructor Documentation
G4RadioactiveDecayChainsFromParent::G4RadioactiveDecayChainsFromParent ()
Definition at line 30 of file G4RadioactiveDecayChainsFromParent.cc.
View newest version in sPHENIX GitHub at line 30 of file G4RadioactiveDecayChainsFromParent.cc
G4RadioactiveDecayChainsFromParent::~G4RadioactiveDecayChainsFromParent () virtual
Definition at line 53 of file G4RadioactiveDecayChainsFromParent.cc.
View newest version in sPHENIX GitHub at line 53 of file G4RadioactiveDecayChainsFromParent.cc
G4RadioactiveDecayChainsFromParent::G4RadioactiveDecayChainsFromParent (const G4RadioactiveDecayChainsFromParent & right)
Definition at line 35 of file G4RadioactiveDecayChainsFromParent.cc.
View newest version in sPHENIX GitHub at line 35 of file G4RadioactiveDecayChainsFromParent.cc
References ionName, and itsRates.
Member Function Documentation
G4String G4RadioactiveDecayChainsFromParent::GetIonName () const inline
Definition at line 82 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RadioactiveDecayChainsFromParent.hh
References ionName.
G4RadioactiveDecayRates G4RadioactiveDecayChainsFromParent::GetItsRates () const inline
Definition at line 87 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RadioactiveDecayChainsFromParent.hh
References itsRates.
G4bool G4RadioactiveDecayChainsFromParent::operator!= (const G4RadioactiveDecayChainsFromParent & right) const inline
Definition at line 77 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RadioactiveDecayChainsFromParent.hh
G4RadioactiveDecayChainsFromParent & G4RadioactiveDecayChainsFromParent::operator= (const G4RadioactiveDecayChainsFromParent & right)
Definition at line 43 of file G4RadioactiveDecayChainsFromParent.cc.
View newest version in sPHENIX GitHub at line 43 of file G4RadioactiveDecayChainsFromParent.cc
References ionName, and itsRates.
G4bool G4RadioactiveDecayChainsFromParent::operator== (const G4RadioactiveDecayChainsFromParent & right) const inline
Definition at line 75 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RadioactiveDecayChainsFromParent.hh
void G4RadioactiveDecayChainsFromParent::SetIonName (G4String name) inline
Definition at line 83 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RadioactiveDecayChainsFromParent.hh
References ionName.
Referenced by G4Radioactivation::CalculateChainsFromParent(), and G4RadioactiveDecay::CalculateChainsFromParent().
void G4RadioactiveDecayChainsFromParent::SetItsRates (G4RadioactiveDecayRates arate) inline
Definition at line 90 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RadioactiveDecayChainsFromParent.hh
References itsRates.
Referenced by G4Radioactivation::CalculateChainsFromParent(), and G4RadioactiveDecay::CalculateChainsFromParent().
Member Data Documentation
G4String G4RadioactiveDecayChainsFromParent::ionName protected
Definition at line 93 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4RadioactiveDecayChainsFromParent.hh
Referenced by G4RadioactiveDecayChainsFromParent(), GetIonName(), operator=(), and SetIonName().
G4RadioactiveDecayRates G4RadioactiveDecayChainsFromParent::itsRates protected
Definition at line 94 of file G4RadioactiveDecayChainsFromParent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RadioactiveDecayChainsFromParent.hh
Referenced by G4RadioactiveDecayChainsFromParent(), GetItsRates(), operator=(), and SetItsRates().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactiveDecayChainsFromParent.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4RadioactiveDecayChainsFromParent.cc