ECCE @ EIC Software: CexmcChargeExchangeReconstructor Class Reference
CexmcChargeExchangeReconstructor Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcChargeExchangeReconstructor.hh>
Public Member Functions
CexmcChargeExchangeReconstructor (const CexmcProductionModel *productionModel)
~CexmcChargeExchangeReconstructor ()
void Reconstruct (const CexmcEnergyDepositStore *edStore)
G4double GetOutputParticleMass (void) const
G4double GetNucleusOutputParticleMass (void) const
const CexmcProductionModelData & GetProductionModelData (void) const
void UseTableMass (G4bool on)
void UseMassCut (G4bool on)
void SetMassCutOPCenter (G4double value)
void SetMassCutNOPCenter (G4double value)
void SetMassCutOPWidth (G4double value)
void SetMassCutNOPWidth (G4double value)
void SetMassCutEllipseAngle (G4double value)
void UseAbsorbedEnergyCut (G4bool on)
void SetAbsorbedEnergyCutCLCenter (G4double value)
void SetAbsorbedEnergyCutCRCenter (G4double value)
void SetAbsorbedEnergyCutCLWidth (G4double value)
void SetAbsorbedEnergyCutCRWidth (G4double value)
void SetAbsorbedEnergyCutEllipseAngle (G4double value)
void SetExpectedMomentumAmp (G4double)
void SetExpectedMomentumAmpDiff (G4double)
void SetEDCollectionAlgorithm (CexmcEDCollectionAlgoritm value)
void SetupBeamParticle (void)
G4bool IsTableMassUsed (void) const
G4bool IsMassCutUsed (void) const
G4double GetMassCutOPCenter (void) const
G4double GetMassCutNOPCenter (void) const
G4double GetMassCutOPWidth (void) const
G4double GetMassCutNOPWidth (void) const
G4double GetMassCutEllipseAngle (void) const
G4bool HasMassCutTriggered (void) const
G4bool IsAbsorbedEnergyCutUsed (void) const
G4double GetAbsorbedEnergyCutCLCenter (void) const
G4double GetAbsorbedEnergyCutCRCenter (void) const
G4double GetAbsorbedEnergyCutCLWidth (void) const
G4double GetAbsorbedEnergyCutCRWidth (void) const
G4double GetAbsorbedEnergyCutEllipseAngle (void) const
G4double GetExpectedMomentumAmp (void) const
CexmcEDCollectionAlgoritm GetEDCollectionAlgorithm (void) const
G4bool HasAbsorbedEnergyCutTriggered (void) const
G4bool HasFullTrigger (void) const
Public Member Functions inherited from CexmcReconstructor
CexmcReconstructor ()
virtual ~CexmcReconstructor ()
void SetCalorimeterEntryPointDefinitionAlgorithm (CexmcCalorimeterEntryPointDefinitionAlgorithm algo)
void SetCalorimeterEntryPointDepthDefinitionAlgorithm (CexmcCalorimeterEntryPointDepthDefinitionAlgorithm algo)
void SetCrystalSelectionAlgorithm (CexmcCrystalSelectionAlgorithm algo)
void UseInnerRefCrystal (G4bool on=true)
void SetCalorimeterEntryPointDepth (G4double depth)
CexmcCalorimeterEntryPointDefinitionAlgorithm GetCalorimeterEntryPointDefinitionAlgorithm (void) const
CexmcCalorimeterEntryPointDepthDefinitionAlgorithm GetCalorimeterEntryPointDepthDefinitionAlgorithm (void) const
CexmcCrystalSelectionAlgorithm GetCrystalSelectionAlgorithm (void) const
G4bool IsInnerRefCrystalUsed (void) const
G4double GetCalorimeterEntryPointDepth (void) const
const G4ThreeVector & GetCalorimeterEPLeftPosition (void) const
const G4ThreeVector & GetCalorimeterEPRightPosition (void) const
const G4ThreeVector & GetCalorimeterEPLeftDirection (void) const
const G4ThreeVector & GetCalorimeterEPRightDirection (void) const
const G4ThreeVector & GetTargetEPPosition (void) const
const G4ThreeVector & GetTargetEPDirection (void) const
const G4ThreeVector & GetCalorimeterEPLeftWorldPosition (void) const
const G4ThreeVector & GetCalorimeterEPRightWorldPosition (void) const
const G4ThreeVector & GetCalorimeterEPLeftWorldDirection (void) const
const G4ThreeVector & GetCalorimeterEPRightWorldDirection (void) const
const G4ThreeVector & GetTargetEPWorldPosition (void) const
const G4ThreeVector & GetTargetEPWorldDirection (void) const
G4double GetTheAngle (void) const
G4bool HasBasicTrigger (void) const
Private Attributes
G4double outputParticleMass
G4double nucleusOutputParticleMass
CexmcProductionModelData productionModelData
G4bool useTableMass
G4bool useMassCut
G4double massCutOPCenter
G4double massCutNOPCenter
G4double massCutOPWidth
G4double massCutNOPWidth
G4double massCutEllipseAngle
G4bool useAbsorbedEnergyCut
G4double absorbedEnergyCutCLCenter
G4double absorbedEnergyCutCRCenter
G4double absorbedEnergyCutCLWidth
G4double absorbedEnergyCutCRWidth
G4double absorbedEnergyCutEllipseAngle
G4double expectedMomentumAmp
CexmcEDCollectionAlgoritm edCollectionAlgorithm
G4bool hasMassCutTriggered
G4bool hasAbsorbedEnergyCutTriggered
G4bool beamParticleIsInitialized
CexmcParticleGun * particleGun
CexmcChargeExchangeReconstructorMessenger * messenger
Additional Inherited Members
Protected Member Functions inherited from CexmcReconstructor
void ReconstructEntryPoints (const CexmcEnergyDepositStore *edStore)
void ReconstructTargetPoint (void)
void ReconstructAngle (void)
Protected Attributes inherited from CexmcReconstructor
G4bool hasBasicTrigger
CexmcCalorimeterEntryPointDefinitionAlgorithm epDefinitionAlgorithm
CexmcCalorimeterEntryPointDepthDefinitionAlgorithm epDepthDefinitionAlgorithm
CexmcCrystalSelectionAlgorithm csAlgorithm
G4bool useInnerRefCrystal
G4double epDepth
G4ThreeVector calorimeterEPLeftPosition
G4ThreeVector calorimeterEPRightPosition
G4ThreeVector calorimeterEPLeftDirection
G4ThreeVector calorimeterEPRightDirection
G4ThreeVector targetEPPosition
G4ThreeVector targetEPDirection
G4ThreeVector calorimeterEPLeftWorldPosition
G4ThreeVector calorimeterEPRightWorldPosition
G4ThreeVector calorimeterEPLeftWorldDirection
G4ThreeVector calorimeterEPRightWorldDirection
G4ThreeVector targetEPWorldPosition
G4ThreeVector targetEPWorldDirection
G4double theAngle
G4double calorimeterEDLeftAdjacent
G4double calorimeterEDRightAdjacent
G4bool collectEDInAdjacentCrystals
Detailed Description
Definition at line 57 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 57 of file CexmcChargeExchangeReconstructor.hh
Constructor & Destructor Documentation
CexmcChargeExchangeReconstructor::CexmcChargeExchangeReconstructor (const CexmcProductionModel * productionModel)
Definition at line 57 of file CexmcChargeExchangeReconstructor.cc.
View newest version in sPHENIX GitHub at line 57 of file CexmcChargeExchangeReconstructor.cc
References CexmcWeirdException, CexmcProductionModel::GetIncidentParticle(), CexmcProductionModel::GetNucleusOutputParticle(), CexmcProductionModel::GetNucleusParticle(), CexmcProductionModel::GetOutputParticle(), CexmcPrimaryGeneratorAction::GetParticleGun(), G4RunManager::GetRunManager(), G4RunManager::GetUserPrimaryGeneratorAction(), CexmcProductionModelData::incidentParticle, messenger, CexmcProductionModelData::nucleusOutputParticle, CexmcProductionModelData::nucleusParticle, CexmcProductionModelData::outputParticle, particleGun, and productionModelData.
CexmcChargeExchangeReconstructor::~CexmcChargeExchangeReconstructor ()
Definition at line 97 of file CexmcChargeExchangeReconstructor.cc.
View newest version in sPHENIX GitHub at line 97 of file CexmcChargeExchangeReconstructor.cc
References messenger.
Member Function Documentation
G4double CexmcChargeExchangeReconstructor::GetAbsorbedEnergyCutCLCenter (void) const inline
Definition at line 383 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 383 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCLCenter.
G4double CexmcChargeExchangeReconstructor::GetAbsorbedEnergyCutCLWidth (void) const inline
Definition at line 397 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 397 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCLWidth.
G4double CexmcChargeExchangeReconstructor::GetAbsorbedEnergyCutCRCenter (void) const inline
Definition at line 390 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 390 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCRCenter.
G4double CexmcChargeExchangeReconstructor::GetAbsorbedEnergyCutCRWidth (void) const inline
Definition at line 404 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 404 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCRWidth.
G4double CexmcChargeExchangeReconstructor::GetAbsorbedEnergyCutEllipseAngle (void) const inline
Definition at line 412 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 412 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutEllipseAngle.
CexmcEDCollectionAlgoritm CexmcChargeExchangeReconstructor::GetEDCollectionAlgorithm (void) const inline
Definition at line 426 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 426 of file CexmcChargeExchangeReconstructor.hh
References edCollectionAlgorithm.
G4double CexmcChargeExchangeReconstructor::GetExpectedMomentumAmp (void) const inline
Definition at line 418 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 418 of file CexmcChargeExchangeReconstructor.hh
References expectedMomentumAmp.
G4double CexmcChargeExchangeReconstructor::GetMassCutEllipseAngle (void) const inline
Definition at line 362 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 362 of file CexmcChargeExchangeReconstructor.hh
References massCutEllipseAngle.
G4double CexmcChargeExchangeReconstructor::GetMassCutNOPCenter (void) const inline
Definition at line 341 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 341 of file CexmcChargeExchangeReconstructor.hh
References massCutNOPCenter.
G4double CexmcChargeExchangeReconstructor::GetMassCutNOPWidth (void) const inline
Definition at line 355 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 355 of file CexmcChargeExchangeReconstructor.hh
References massCutNOPWidth.
G4double CexmcChargeExchangeReconstructor::GetMassCutOPCenter (void) const inline
Definition at line 334 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 334 of file CexmcChargeExchangeReconstructor.hh
References massCutOPCenter.
G4double CexmcChargeExchangeReconstructor::GetMassCutOPWidth (void) const inline
Definition at line 348 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 348 of file CexmcChargeExchangeReconstructor.hh
References massCutOPWidth.
G4double CexmcChargeExchangeReconstructor::GetNucleusOutputParticleMass (void) const inline
Definition at line 205 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 205 of file CexmcChargeExchangeReconstructor.hh
References nucleusOutputParticleMass.
Referenced by CexmcEventAction::PrintReconstructedData().
G4double CexmcChargeExchangeReconstructor::GetOutputParticleMass (void) const inline
Definition at line 198 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 198 of file CexmcChargeExchangeReconstructor.hh
References outputParticleMass.
Referenced by CexmcEventAction::PrintReconstructedData().
const CexmcProductionModelData & CexmcChargeExchangeReconstructor::GetProductionModelData (void) const inline
Definition at line 213 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 213 of file CexmcChargeExchangeReconstructor.hh
References productionModelData.
Referenced by CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEventAction::EndOfEventAction(), and CexmcEventAction::PrintReconstructedData().
G4bool CexmcChargeExchangeReconstructor::HasAbsorbedEnergyCutTriggered (void) const inline
Definition at line 432 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 432 of file CexmcChargeExchangeReconstructor.hh
References hasAbsorbedEnergyCutTriggered.
Referenced by CexmcEventAction::PrintReconstructedData().
G4bool CexmcChargeExchangeReconstructor::HasFullTrigger (void) const virtual
Reimplemented from CexmcReconstructor.
Definition at line 288 of file CexmcChargeExchangeReconstructor.cc.
View newest version in sPHENIX GitHub at line 288 of file CexmcChargeExchangeReconstructor.cc
References hasAbsorbedEnergyCutTriggered, CexmcReconstructor::hasBasicTrigger, hasMassCutTriggered, useAbsorbedEnergyCut, and useMassCut.
Referenced by CexmcEventAction::EndOfEventAction().
G4bool CexmcChargeExchangeReconstructor::HasMassCutTriggered (void) const inline
Definition at line 369 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 369 of file CexmcChargeExchangeReconstructor.hh
References hasMassCutTriggered.
Referenced by CexmcEventAction::PrintReconstructedData().
G4bool CexmcChargeExchangeReconstructor::IsAbsorbedEnergyCutUsed (void) const inline
Definition at line 376 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 376 of file CexmcChargeExchangeReconstructor.hh
References useAbsorbedEnergyCut.
Referenced by CexmcEventAction::PrintReconstructedData().
G4bool CexmcChargeExchangeReconstructor::IsMassCutUsed (void) const inline
Definition at line 328 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 328 of file CexmcChargeExchangeReconstructor.hh
References useMassCut.
Referenced by CexmcEventAction::PrintReconstructedData().
G4bool CexmcChargeExchangeReconstructor::IsTableMassUsed (void) const inline
Definition at line 322 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 322 of file CexmcChargeExchangeReconstructor.hh
References useTableMass.
void CexmcChargeExchangeReconstructor::Reconstruct (const CexmcEnergyDepositStore * edStore) virtual
Reimplemented from CexmcReconstructor.
Definition at line 113 of file CexmcChargeExchangeReconstructor.cc.
View newest version in sPHENIX GitHub at line 113 of file CexmcChargeExchangeReconstructor.cc
References absorbedEnergyCutCLCenter, absorbedEnergyCutCLWidth, absorbedEnergyCutCRCenter, absorbedEnergyCutCRWidth, absorbedEnergyCutEllipseAngle, beamParticleIsInitialized, CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CexmcEnergyDepositStore::calorimeterEDLeft, CexmcReconstructor::calorimeterEDLeftAdjacent, CexmcEnergyDepositStore::calorimeterEDRight, CexmcReconstructor::calorimeterEDRightAdjacent, CexmcReconstructor::calorimeterEPLeftWorldPosition, CexmcReconstructor::calorimeterEPRightWorldPosition, CexmcBeamAndIncidentParticlesMismatch, CexmcCollectEDInAdjacentCrystals, CexmcReconstructor::collectEDInAdjacentCrystals, edCollectionAlgorithm, expectedMomentumAmp, CexmcParticleGun::GetOrigDirection(), CexmcParticleGun::GetOrigMomentumAmp(), G4ParticleGun::GetParticleDefinition(), G4ParticleDefinition::GetPDGMass(), hasAbsorbedEnergyCutTriggered, CexmcReconstructor::hasBasicTrigger, hasMassCutTriggered, CexmcProductionModelData::incidentParticle, CexmcProductionModelData::incidentParticleLAB, CexmcProductionModelData::incidentParticleSCM, CLHEP::Hep3Vector::mag2(), massCutEllipseAngle, massCutNOPCenter, massCutNOPWidth, massCutOPCenter, massCutOPWidth, CexmcProductionModelData::nucleusOutputParticleLAB, nucleusOutputParticleMass, CexmcProductionModelData::nucleusOutputParticleSCM, CexmcProductionModelData::nucleusParticle, CexmcProductionModelData::nucleusParticleLAB, CexmcProductionModelData::nucleusParticleSCM, CexmcProductionModelData::outputParticle, CexmcProductionModelData::outputParticleLAB, outputParticleMass, CexmcProductionModelData::outputParticleSCM, particleGun, productionModelData, CexmcReconstructor::ReconstructAngle(), CexmcReconstructor::ReconstructEntryPoints(), CexmcReconstructor::ReconstructTargetPoint(), CLHEP::Hep3Vector::setMag(), CexmcReconstructor::targetEPWorldPosition, CexmcReconstructor::theAngle, useAbsorbedEnergyCut, useMassCut, and useTableMass.
Referenced by CexmcEventAction::EndOfEventAction().
void CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCLCenter (G4double value) inline
Definition at line 273 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 273 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCLCenter.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCLWidth (G4double value) inline
Definition at line 287 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 287 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCLWidth.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCRCenter (G4double value) inline
Definition at line 280 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 280 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCRCenter.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCRWidth (G4double value) inline
Definition at line 294 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 294 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutCRWidth.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutEllipseAngle (G4double value) inline
Definition at line 301 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 301 of file CexmcChargeExchangeReconstructor.hh
References absorbedEnergyCutEllipseAngle.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetEDCollectionAlgorithm (CexmcEDCollectionAlgoritm value) inline
Definition at line 315 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 315 of file CexmcChargeExchangeReconstructor.hh
References edCollectionAlgorithm.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetExpectedMomentumAmp (G4double value) inline
Definition at line 308 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 308 of file CexmcChargeExchangeReconstructor.hh
References expectedMomentumAmp.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetExpectedMomentumAmpDiff (G4double value)
Definition at line 301 of file CexmcChargeExchangeReconstructor.cc.
View newest version in sPHENIX GitHub at line 301 of file CexmcChargeExchangeReconstructor.cc
References expectedMomentumAmp, CexmcParticleGun::GetOrigMomentumAmp(), and particleGun.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetMassCutEllipseAngle (G4double value) inline
Definition at line 259 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 259 of file CexmcChargeExchangeReconstructor.hh
References massCutEllipseAngle.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetMassCutNOPCenter (G4double value) inline
Definition at line 238 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 238 of file CexmcChargeExchangeReconstructor.hh
References massCutNOPCenter.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetMassCutNOPWidth (G4double value) inline
Definition at line 252 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 252 of file CexmcChargeExchangeReconstructor.hh
References massCutNOPWidth.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetMassCutOPCenter (G4double value) inline
Definition at line 231 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 231 of file CexmcChargeExchangeReconstructor.hh
References massCutOPCenter.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetMassCutOPWidth (G4double value) inline
Definition at line 245 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 245 of file CexmcChargeExchangeReconstructor.hh
References massCutOPWidth.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::SetupBeamParticle (void)
Definition at line 103 of file CexmcChargeExchangeReconstructor.cc.
View newest version in sPHENIX GitHub at line 103 of file CexmcChargeExchangeReconstructor.cc
References beamParticleIsInitialized, CexmcBeamAndIncidentParticlesMismatch, G4ParticleGun::GetParticleDefinition(), CexmcProductionModelData::incidentParticle, particleGun, and productionModelData.
Referenced by CexmcEventAction::BeamParticleChangeHook().
void CexmcChargeExchangeReconstructor::UseAbsorbedEnergyCut (G4bool on) inline
Definition at line 266 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 266 of file CexmcChargeExchangeReconstructor.hh
References useAbsorbedEnergyCut.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::UseMassCut (G4bool on) inline
Definition at line 225 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 225 of file CexmcChargeExchangeReconstructor.hh
References useMassCut.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
void CexmcChargeExchangeReconstructor::UseTableMass (G4bool on) inline
Definition at line 219 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 219 of file CexmcChargeExchangeReconstructor.hh
References useTableMass.
Referenced by CexmcChargeExchangeReconstructorMessenger::SetNewValue().
Member Data Documentation
G4double CexmcChargeExchangeReconstructor::absorbedEnergyCutCLCenter private
Definition at line 170 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 170 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetAbsorbedEnergyCutCLCenter(), Reconstruct(), and SetAbsorbedEnergyCutCLCenter().
G4double CexmcChargeExchangeReconstructor::absorbedEnergyCutCLWidth private
Definition at line 174 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 174 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetAbsorbedEnergyCutCLWidth(), Reconstruct(), and SetAbsorbedEnergyCutCLWidth().
G4double CexmcChargeExchangeReconstructor::absorbedEnergyCutCRCenter private
Definition at line 172 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 172 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetAbsorbedEnergyCutCRCenter(), Reconstruct(), and SetAbsorbedEnergyCutCRCenter().
G4double CexmcChargeExchangeReconstructor::absorbedEnergyCutCRWidth private
Definition at line 176 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 176 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetAbsorbedEnergyCutCRWidth(), Reconstruct(), and SetAbsorbedEnergyCutCRWidth().
G4double CexmcChargeExchangeReconstructor::absorbedEnergyCutEllipseAngle private
Definition at line 178 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 178 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetAbsorbedEnergyCutEllipseAngle(), Reconstruct(), and SetAbsorbedEnergyCutEllipseAngle().
G4bool CexmcChargeExchangeReconstructor::beamParticleIsInitialized private
Definition at line 190 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 190 of file CexmcChargeExchangeReconstructor.hh
Referenced by Reconstruct(), and SetupBeamParticle().
CexmcEDCollectionAlgoritm CexmcChargeExchangeReconstructor::edCollectionAlgorithm private
Definition at line 182 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 182 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetEDCollectionAlgorithm(), Reconstruct(), and SetEDCollectionAlgorithm().
G4double CexmcChargeExchangeReconstructor::expectedMomentumAmp private
Definition at line 180 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 180 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetExpectedMomentumAmp(), Reconstruct(), SetExpectedMomentumAmp(), and SetExpectedMomentumAmpDiff().
G4bool CexmcChargeExchangeReconstructor::hasAbsorbedEnergyCutTriggered private
Definition at line 187 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 187 of file CexmcChargeExchangeReconstructor.hh
Referenced by HasAbsorbedEnergyCutTriggered(), HasFullTrigger(), and Reconstruct().
G4bool CexmcChargeExchangeReconstructor::hasMassCutTriggered private
Definition at line 185 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 185 of file CexmcChargeExchangeReconstructor.hh
Referenced by HasFullTrigger(), HasMassCutTriggered(), and Reconstruct().
G4double CexmcChargeExchangeReconstructor::massCutEllipseAngle private
Definition at line 166 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 166 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetMassCutEllipseAngle(), Reconstruct(), and SetMassCutEllipseAngle().
G4double CexmcChargeExchangeReconstructor::massCutNOPCenter private
Definition at line 160 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 160 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetMassCutNOPCenter(), Reconstruct(), and SetMassCutNOPCenter().
G4double CexmcChargeExchangeReconstructor::massCutNOPWidth private
Definition at line 164 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 164 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetMassCutNOPWidth(), Reconstruct(), and SetMassCutNOPWidth().
G4double CexmcChargeExchangeReconstructor::massCutOPCenter private
Definition at line 158 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 158 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetMassCutOPCenter(), Reconstruct(), and SetMassCutOPCenter().
G4double CexmcChargeExchangeReconstructor::massCutOPWidth private
Definition at line 162 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 162 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetMassCutOPWidth(), Reconstruct(), and SetMassCutOPWidth().
CexmcChargeExchangeReconstructorMessenger* CexmcChargeExchangeReconstructor::messenger private
Definition at line 194 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 194 of file CexmcChargeExchangeReconstructor.hh
Referenced by CexmcChargeExchangeReconstructor(), and ~CexmcChargeExchangeReconstructor().
G4double CexmcChargeExchangeReconstructor::nucleusOutputParticleMass private
Definition at line 148 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 148 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetNucleusOutputParticleMass(), and Reconstruct().
G4double CexmcChargeExchangeReconstructor::outputParticleMass private
Definition at line 146 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 146 of file CexmcChargeExchangeReconstructor.hh
Referenced by GetOutputParticleMass(), and Reconstruct().
CexmcParticleGun* CexmcChargeExchangeReconstructor::particleGun private
Definition at line 192 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 192 of file CexmcChargeExchangeReconstructor.hh
Referenced by CexmcChargeExchangeReconstructor(), Reconstruct(), SetExpectedMomentumAmpDiff(), and SetupBeamParticle().
CexmcProductionModelData CexmcChargeExchangeReconstructor::productionModelData private
Definition at line 151 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 151 of file CexmcChargeExchangeReconstructor.hh
Referenced by CexmcChargeExchangeReconstructor(), GetProductionModelData(), Reconstruct(), and SetupBeamParticle().
G4bool CexmcChargeExchangeReconstructor::useAbsorbedEnergyCut private
Definition at line 168 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 168 of file CexmcChargeExchangeReconstructor.hh
Referenced by HasFullTrigger(), IsAbsorbedEnergyCutUsed(), Reconstruct(), and UseAbsorbedEnergyCut().
G4bool CexmcChargeExchangeReconstructor::useMassCut private
Definition at line 156 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 156 of file CexmcChargeExchangeReconstructor.hh
Referenced by HasFullTrigger(), IsMassCutUsed(), Reconstruct(), and UseMassCut().
G4bool CexmcChargeExchangeReconstructor::useTableMass private
Definition at line 154 of file CexmcChargeExchangeReconstructor.hh.
View newest version in sPHENIX GitHub at line 154 of file CexmcChargeExchangeReconstructor.hh
Referenced by IsTableMassUsed(), Reconstruct(), and UseTableMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcChargeExchangeReconstructor.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcChargeExchangeReconstructor.cc