ECCE @ EIC Software: G4GDMLReadDefine Class Reference
G4GDMLReadDefine Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadDefine.hh>
Public Member Functions
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void MaterialsRead (const xercesc::DOMElement *const)=0
virtual void SetupRead (const xercesc::DOMElement *const)=0
virtual void SolidsRead (const xercesc::DOMElement *const)=0
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)=0
virtual void Volume_contentRead (const xercesc::DOMElement *const)=0
virtual void StructureRead (const xercesc::DOMElement *const)=0
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
virtual G4LogicalVolume * GetVolume (const G4String &) const =0
virtual G4String GetSetup (const G4String &)=0
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Protected Attributes
std::map< G4String, G4double > quantityMap
std::map< G4String, G4ThreeVector > positionMap
std::map< G4String, G4ThreeVector > rotationMap
std::map< G4String, G4ThreeVector > scaleMap
std::map< G4String, G4GDMLMatrix > matrixMap
Protected Attributes inherited from G4GDMLRead
G4GDMLEvaluator eval
G4bool validate
G4bool check
G4bool dostrip
Detailed Description
Definition at line 69 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GDMLReadDefine.hh
Constructor & Destructor Documentation
G4GDMLReadDefine::G4GDMLReadDefine () protected
Definition at line 123 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 123 of file G4GDMLReadDefine.cc
G4GDMLReadDefine::~G4GDMLReadDefine () protected virtual
Definition at line 127 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 127 of file G4GDMLReadDefine.cc
Member Function Documentation
void G4GDMLReadDefine::ConstantRead (const xercesc::DOMElement * const constantElement) protected
Definition at line 145 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 145 of file G4GDMLReadDefine.cc
References G4GDMLEvaluator::DefineConstant(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), and G4GDMLRead::Transcode().
Referenced by DefineRead().
void G4GDMLReadDefine::DefineRead (const xercesc::DOMElement * const defineElement) virtual
Implements G4GDMLRead.
Definition at line 466 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 466 of file G4GDMLReadDefine.cc
References ConstantRead(), ExpressionRead(), FatalException, G4cout, G4endl, G4Exception(), MatrixRead(), PositionRead(), QuantityRead(), RotationRead(), ScaleRead(), G4GDMLRead::Transcode(), and VariableRead().
Referenced by G4GDMLReadMaterials::MaterialsRead(), and G4GDMLReadSolids::SolidsRead().
void G4GDMLReadDefine::ExpressionRead (const xercesc::DOMElement * const expElement) protected
Definition at line 180 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 180 of file G4GDMLReadDefine.cc
References G4GDMLEvaluator::DefineConstant(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), and G4GDMLRead::Transcode().
Referenced by DefineRead().
G4double G4GDMLReadDefine::GetConstant (const G4String & ref)
Definition at line 578 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 578 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, and G4GDMLEvaluator::GetConstant().
G4GDMLMatrix G4GDMLReadDefine::GetMatrix (const G4String & ref)
Definition at line 632 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 632 of file G4GDMLReadDefine.cc
References FatalException, G4Exception(), and matrixMap.
Referenced by G4GDMLReadMaterials::PropertyRead(), and G4GDMLReadSolids::PropertyRead().
G4ThreeVector G4GDMLReadDefine::GetPosition (const G4String & ref)
Definition at line 599 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 599 of file G4GDMLReadDefine.cc
References FatalException, G4Exception(), and positionMap.
Referenced by G4GDMLReadSolids::BooleanRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadParamvol::ParametersRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadSolids::QuadrangularRead(), G4GDMLReadStructure::ReplicaRead(), G4GDMLReadSolids::TetRead(), and G4GDMLReadSolids::TriangularRead().
G4double G4GDMLReadDefine::GetQuantity (const G4String & ref)
Definition at line 588 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 588 of file G4GDMLReadDefine.cc
References FatalException, G4Exception(), and quantityMap.
Referenced by G4GDMLReadMaterials::MaterialRead().
G4ThreeVector G4GDMLReadDefine::GetRotation (const G4String & ref)
Definition at line 610 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 610 of file G4GDMLReadDefine.cc
References FatalException, G4Exception(), and rotationMap.
Referenced by G4GDMLReadSolids::BooleanRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadParamvol::ParametersRead(), G4GDMLReadStructure::PhysvolRead(), and G4GDMLReadStructure::ReplicaRead().
G4RotationMatrix G4GDMLReadDefine::GetRotationMatrix (const G4ThreeVector & angles) protected
Definition at line 132 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 132 of file G4GDMLReadDefine.cc
References CLHEP::HepRotation::rectify(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4GDMLReadSolids::BooleanRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadStructure::PhysvolRead(), and G4GDMLReadSolids::ReflectedSolidRead().
G4ThreeVector G4GDMLReadDefine::GetScale (const G4String & ref)
Definition at line 621 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 621 of file G4GDMLReadDefine.cc
References FatalException, G4Exception(), and scaleMap.
Referenced by G4GDMLReadStructure::PhysvolRead(), and G4GDMLReadSolids::ScaledSolidRead().
G4double G4GDMLReadDefine::GetVariable (const G4String & ref)
Definition at line 583 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 583 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, and G4GDMLEvaluator::GetVariable().
G4bool G4GDMLReadDefine::IsValidID (const G4String & ref) const
Definition at line 573 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 573 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, and G4GDMLEvaluator::IsVariable().
void G4GDMLReadDefine::MatrixRead (const xercesc::DOMElement * const matrixElement) protected
Definition at line 216 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 216 of file G4GDMLReadDefine.cc
References G4GDMLEvaluator::DefineMatrix(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), G4GDMLEvaluator::EvaluateInteger(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), matrixMap, G4GDMLMatrix::Set(), G4GDMLRead::Transcode(), and Acts::Test::values.
Referenced by DefineRead().
void G4GDMLReadDefine::PositionRead (const xercesc::DOMElement * const positionElement) protected
Definition at line 272 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 272 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), position, positionMap, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and G4GDMLRead::Transcode().
Referenced by DefineRead().
void G4GDMLReadDefine::QuantityRead (const xercesc::DOMElement * const element) protected
Definition at line 428 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 428 of file G4GDMLReadDefine.cc
References G4GDMLEvaluator::DefineConstant(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4UnitDefinition::GetValueOf(), quantityMap, and G4GDMLRead::Transcode().
Referenced by DefineRead().
G4String G4GDMLReadDefine::RefRead (const xercesc::DOMElement * const element) protected
Definition at line 541 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 541 of file G4GDMLReadDefine.cc
References FatalException, G4Exception(), and G4GDMLRead::Transcode().
Referenced by G4GDMLReadSolids::BooleanRead(), G4GDMLReadStructure::BorderSurfaceRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadMaterials::MaterialRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadParamvol::ParametersRead(), G4GDMLReadParamvol::ParamvolRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadStructure::ReplicaRead(), G4GDMLReadStructure::ReplicavolRead(), G4GDMLReadSolids::ScaledSolidRead(), G4GDMLReadSetup::SetupRead(), G4GDMLReadStructure::SkinSurfaceRead(), G03ColorReader::VolumeRead(), and G4GDMLReadStructure::VolumeRead().
void G4GDMLReadDefine::RotationRead (const xercesc::DOMElement * const rotationElement) protected
Definition at line 315 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 315 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), rotationMap, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and G4GDMLRead::Transcode().
Referenced by DefineRead().
void G4GDMLReadDefine::ScaleRead (const xercesc::DOMElement * const scaleElement) protected
Definition at line 357 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 357 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), scale, scaleMap, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and G4GDMLRead::Transcode().
Referenced by DefineRead().
void G4GDMLReadDefine::VariableRead (const xercesc::DOMElement * const variableElement) protected
Definition at line 394 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 394 of file G4GDMLReadDefine.cc
References G4GDMLEvaluator::DefineVariable(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), and G4GDMLRead::Transcode().
Referenced by DefineRead().
void G4GDMLReadDefine::VectorRead (const xercesc::DOMElement * const vectorElement, G4ThreeVector & vec) protected
Definition at line 504 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 504 of file G4GDMLReadDefine.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4UnitDefinition::GetValueOf(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and G4GDMLRead::Transcode().
Referenced by G4GDMLReadSolids::BooleanRead(), G4GDMLReadSolids::MultiUnionNodeRead(), G4GDMLReadParamvol::ParametersRead(), G4GDMLReadStructure::PhysvolRead(), G4GDMLReadStructure::ReplicaRead(), and G4GDMLReadSolids::ScaledSolidRead().
Member Data Documentation
std::map<G4String,G4GDMLMatrix> G4GDMLReadDefine::matrixMap protected
Definition at line 109 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 109 of file G4GDMLReadDefine.hh
Referenced by GetMatrix(), and MatrixRead().
std::map<G4String,G4ThreeVector> G4GDMLReadDefine::positionMap protected
Definition at line 106 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 106 of file G4GDMLReadDefine.hh
Referenced by GetPosition(), and PositionRead().
std::map<G4String,G4double> G4GDMLReadDefine::quantityMap protected
Definition at line 105 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 105 of file G4GDMLReadDefine.hh
Referenced by GetQuantity(), and QuantityRead().
std::map<G4String,G4ThreeVector> G4GDMLReadDefine::rotationMap protected
Definition at line 107 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GDMLReadDefine.hh
Referenced by GetRotation(), and RotationRead().
std::map<G4String,G4ThreeVector> G4GDMLReadDefine::scaleMap protected
Definition at line 108 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 108 of file G4GDMLReadDefine.hh
Referenced by GetScale(), and ScaleRead().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadDefine.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLReadDefine.cc