ECCE @ EIC Software: G4OrlicLiXsModel Class Reference
G4OrlicLiXsModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4OrlicLiXsModel.hh>
Public Member Functions
G4OrlicLiXsModel ()
virtual ~G4OrlicLiXsModel ()
G4double CalculateL1CrossSection (G4int zTarget, G4double energyIncident)
G4double CalculateL2CrossSection (G4int zTarget, G4double energyIncident)
G4double CalculateL3CrossSection (G4int zTarget, G4double energyIncident)
Private Member Functions
G4OrlicLiXsModel (const G4OrlicLiXsModel &)
G4OrlicLiXsModel & operator= (const G4OrlicLiXsModel &right)
Private Attributes
G4AtomicTransitionManager * transitionManager
Detailed Description
Definition at line 54 of file G4OrlicLiXsModel.hh.
View newest version in sPHENIX GitHub at line 54 of file G4OrlicLiXsModel.hh
Constructor & Destructor Documentation
G4OrlicLiXsModel::G4OrlicLiXsModel ()
Definition at line 52 of file G4OrlicLiXsModel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4OrlicLiXsModel.cc
References G4AtomicTransitionManager::Instance(), and transitionManager.
G4OrlicLiXsModel::~G4OrlicLiXsModel () virtual
Definition at line 59 of file G4OrlicLiXsModel.cc.
View newest version in sPHENIX GitHub at line 59 of file G4OrlicLiXsModel.cc
G4OrlicLiXsModel::G4OrlicLiXsModel (const G4OrlicLiXsModel &) private
Member Function Documentation
G4double G4OrlicLiXsModel::CalculateL1CrossSection (G4int zTarget, G4double energyIncident)
Definition at line 70 of file G4OrlicLiXsModel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4OrlicLiXsModel.cc
References a0, barn, G4AtomicShell::BindingEnergy(), G4Exp(), keV, G4AtomicTransitionManager::Shell(), transitionManager, and x.
Referenced by G4empCrossSection::CrossSection(), and G4empCrossSection::GetCrossSection().
G4double G4OrlicLiXsModel::CalculateL2CrossSection (G4int zTarget, G4double energyIncident)
Definition at line 214 of file G4OrlicLiXsModel.cc.
View newest version in sPHENIX GitHub at line 214 of file G4OrlicLiXsModel.cc
References a0, barn, G4AtomicShell::BindingEnergy(), source.hepunit::electron_mass_c2, G4Exp(), G4ParticleDefinition::GetPDGMass(), keV, G4Proton::Proton(), G4AtomicTransitionManager::Shell(), transitionManager, and x.
Referenced by G4empCrossSection::CrossSection(), and G4empCrossSection::GetCrossSection().
G4double G4OrlicLiXsModel::CalculateL3CrossSection (G4int zTarget, G4double energyIncident)
Definition at line 320 of file G4OrlicLiXsModel.cc.
View newest version in sPHENIX GitHub at line 320 of file G4OrlicLiXsModel.cc
References a0, barn, G4AtomicShell::BindingEnergy(), source.hepunit::electron_mass_c2, G4Exp(), G4ParticleDefinition::GetPDGMass(), keV, G4Proton::Proton(), G4AtomicTransitionManager::Shell(), transitionManager, and x.
Referenced by G4empCrossSection::CrossSection(), and G4empCrossSection::GetCrossSection().
G4OrlicLiXsModel& G4OrlicLiXsModel::operator= (const G4OrlicLiXsModel & right) private
Member Data Documentation
G4AtomicTransitionManager* G4OrlicLiXsModel::transitionManager private
Definition at line 78 of file G4OrlicLiXsModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4OrlicLiXsModel.hh
Referenced by CalculateL1CrossSection(), CalculateL2CrossSection(), CalculateL3CrossSection(), and G4OrlicLiXsModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4OrlicLiXsModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4OrlicLiXsModel.cc