ECCE @ EIC Software: G4H2Messenger Class Reference
G4H2Messenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4H2Messenger.hh>
Public Member Functions
G4H2Messenger (G4VAnalysisManager *manager)
virtual ~G4H2Messenger ()
virtual void SetNewValue (G4UIcommand *command, G4String value) final
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void CreateH2Cmd ()
void SetH2Cmd ()
Private Attributes
G4VAnalysisManager * fManager
Associated class.
std::unique_ptr
< G4AnalysisMessengerHelper > fHelper
std::unique_ptr< G4UIdirectory > fDirectory
std::unique_ptr< G4UIcommand > fCreateH2Cmd
std::unique_ptr< G4UIcommand > fSetH2Cmd
std::unique_ptr< G4UIcommand > fSetH2XCmd
std::unique_ptr< G4UIcommand > fSetH2YCmd
std::unique_ptr< G4UIcommand > fSetH2TitleCmd
std::unique_ptr< G4UIcommand > fSetH2XAxisCmd
std::unique_ptr< G4UIcommand > fSetH2YAxisCmd
std::unique_ptr< G4UIcommand > fSetH2ZAxisCmd
std::unique_ptr< G4UIcommand > fSetH2XAxisLogCmd
std::unique_ptr< G4UIcommand > fSetH2YAxisLogCmd
std::unique_ptr< G4UIcommand > fSetH2ZAxisLogCmd
G4int fXId
G4AnalysisMessengerHelper::BinData fXData
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 45 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 45 of file G4H2Messenger.hh
Constructor & Destructor Documentation
G4H2Messenger::G4H2Messenger (G4VAnalysisManager * manager) explicit
Definition at line 42 of file G4H2Messenger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4H2Messenger.cc
References CreateH2Cmd(), fDirectory, fHelper, fSetH2TitleCmd, fSetH2XAxisCmd, fSetH2XAxisLogCmd, fSetH2XCmd, fSetH2YAxisCmd, fSetH2YAxisLogCmd, fSetH2YCmd, fSetH2ZAxisCmd, fSetH2ZAxisLogCmd, and SetH2Cmd().
G4H2Messenger::~G4H2Messenger () virtual
Definition at line 77 of file G4H2Messenger.cc.
View newest version in sPHENIX GitHub at line 77 of file G4H2Messenger.cc
Member Function Documentation
void G4H2Messenger::CreateH2Cmd () private
Definition at line 85 of file G4H2Messenger.cc.
View newest version in sPHENIX GitHub at line 85 of file G4H2Messenger.cc
References fCreateH2Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4H2Messenger().
void G4H2Messenger::SetH2Cmd () private
Definition at line 176 of file G4H2Messenger.cc.
View newest version in sPHENIX GitHub at line 176 of file G4H2Messenger.cc
References fSetH2Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4H2Messenger().
void G4H2Messenger::SetNewValue (G4UIcommand * command, G4String value) final virtual
Reimplemented from G4UImessenger.
Definition at line 258 of file G4H2Messenger.cc.
View newest version in sPHENIX GitHub at line 258 of file G4H2Messenger.cc
References G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToInt(), G4VAnalysisManager::CreateH2(), fCreateH2Cmd, fHelper, fManager, G4AnalysisMessengerHelper::BinData::fNbins, G4AnalysisMessengerHelper::BinData::fSbinScheme, fSetH2Cmd, fSetH2TitleCmd, fSetH2XAxisCmd, fSetH2XAxisLogCmd, fSetH2XCmd, fSetH2YAxisCmd, fSetH2YAxisLogCmd, fSetH2YCmd, fSetH2ZAxisCmd, fSetH2ZAxisLogCmd, G4AnalysisMessengerHelper::BinData::fSfcn, G4AnalysisMessengerHelper::BinData::fSunit, G4AnalysisMessengerHelper::BinData::fVmax, G4AnalysisMessengerHelper::BinData::fVmin, fXData, fXId, G4UIcommand::GetParameterEntries(), G4Analysis::GetUnitValue(), Dataset::parameters, G4VAnalysisManager::SetH2(), G4VAnalysisManager::SetH2Title(), G4VAnalysisManager::SetH2XAxisIsLog(), G4VAnalysisManager::SetH2XAxisTitle(), G4VAnalysisManager::SetH2YAxisIsLog(), G4VAnalysisManager::SetH2YAxisTitle(), G4VAnalysisManager::SetH2ZAxisIsLog(), G4VAnalysisManager::SetH2ZAxisTitle(), title(), G4Analysis::Tokenize(), and xaxis.
Member Data Documentation
std::unique_ptr<G4UIcommand> G4H2Messenger::fCreateH2Cmd private
Definition at line 62 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4H2Messenger.hh
Referenced by CreateH2Cmd(), and SetNewValue().
std::unique_ptr<G4UIdirectory> G4H2Messenger::fDirectory private
Definition at line 60 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4H2Messenger.hh
Referenced by G4H2Messenger().
std::unique_ptr<G4AnalysisMessengerHelper> G4H2Messenger::fHelper private
Definition at line 59 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
G4VAnalysisManager* G4H2Messenger::fManager private
Associated class.
Definition at line 58 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 58 of file G4H2Messenger.hh
Referenced by SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2Cmd private
Definition at line 63 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4H2Messenger.hh
Referenced by SetH2Cmd(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2TitleCmd private
Definition at line 66 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2XAxisCmd private
Definition at line 67 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2XAxisLogCmd private
Definition at line 70 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2XCmd private
Definition at line 64 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2YAxisCmd private
Definition at line 68 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2YAxisLogCmd private
Definition at line 71 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2YCmd private
Definition at line 65 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2ZAxisCmd private
Definition at line 69 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H2Messenger::fSetH2ZAxisLogCmd private
Definition at line 72 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4H2Messenger.hh
Referenced by G4H2Messenger(), and SetNewValue().
G4AnalysisMessengerHelper::BinData G4H2Messenger::fXData private
Definition at line 75 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4H2Messenger.hh
Referenced by SetNewValue().
G4int G4H2Messenger::fXId private
Definition at line 74 of file G4H2Messenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4H2Messenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4H2Messenger.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4H2Messenger.cc