ECCE @ EIC Software: cheprep::GZIPOutputStreamBuffer Class Reference
cheprep::GZIPOutputStreamBuffer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/GZIPOutputStreamBuffer.h>
Public Member Functions
GZIPOutputStreamBuffer (std::streambuf *outbuf)
int overflow (int)
void setFilename (const std::string &filename)
void setComment (const std::string &comment)
void close ()
virtual ~GZIPOutputStreamBuffer ()
Public Member Functions inherited from cheprep::DeflateOutputStreamBuffer
DeflateOutputStreamBuffer (std::streambuf *buffer)
void init (bool compress)
void finish ()
virtual ~DeflateOutputStreamBuffer ()
Private Member Functions
void writeHeader ()
void writeTrailer ()
Private Attributes
std::string filename
std::string comment
bool open
Additional Inherited Members
Protected Member Functions inherited from cheprep::DeflateOutputStreamBuffer
int overflow (int c=EOF)
bool flushOut ()
void putUI (unsigned int ui)
void putUS (unsigned short us)
void putUB (unsigned char ub)
void putS (const std::string s)
std::streampos pos ()
unsigned int getSize ()
unsigned int getCRC ()
Detailed Description
Definition at line 14 of file GZIPOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 14 of file GZIPOutputStreamBuffer.h
Constructor & Destructor Documentation
cheprep::GZIPOutputStreamBuffer::GZIPOutputStreamBuffer (std::streambuf * outbuf)
Definition at line 12 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 12 of file GZIPOutputStreamBuffer.cc
References cheprep::DeflateOutputStreamBuffer::init().
cheprep::GZIPOutputStreamBuffer::~GZIPOutputStreamBuffer () virtual
Definition at line 36 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 36 of file GZIPOutputStreamBuffer.cc
References close().
Member Function Documentation
void cheprep::GZIPOutputStreamBuffer::close (void)
Definition at line 27 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 27 of file GZIPOutputStreamBuffer.cc
References false, cheprep::DeflateOutputStreamBuffer::finish(), open, and writeTrailer().
Referenced by ~GZIPOutputStreamBuffer().
int cheprep::GZIPOutputStreamBuffer::overflow (int c)
Definition at line 40 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 40 of file GZIPOutputStreamBuffer.cc
References open, cheprep::DeflateOutputStreamBuffer::overflow(), and writeHeader().
void cheprep::GZIPOutputStreamBuffer::setComment (const std::string & comment)
Definition at line 23 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 23 of file GZIPOutputStreamBuffer.cc
References c, and comment.
void cheprep::GZIPOutputStreamBuffer::setFilename (const std::string & filename)
Definition at line 19 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 19 of file GZIPOutputStreamBuffer.cc
References filename.
void cheprep::GZIPOutputStreamBuffer::writeHeader () private
Definition at line 48 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 48 of file GZIPOutputStreamBuffer.cc
References comment, filename, cheprep::DeflateOutputStreamBuffer::putS(), cheprep::DeflateOutputStreamBuffer::putUB(), and cheprep::DeflateOutputStreamBuffer::putUI().
Referenced by overflow().
void cheprep::GZIPOutputStreamBuffer::writeTrailer () private
Definition at line 72 of file GZIPOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 72 of file GZIPOutputStreamBuffer.cc
References cheprep::DeflateOutputStreamBuffer::getCRC(), cheprep::DeflateOutputStreamBuffer::getSize(), and cheprep::DeflateOutputStreamBuffer::putUI().
Referenced by close().
Member Data Documentation
std::string cheprep::GZIPOutputStreamBuffer::comment private
Definition at line 34 of file GZIPOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 34 of file GZIPOutputStreamBuffer.h
Referenced by setComment(), and writeHeader().
std::string cheprep::GZIPOutputStreamBuffer::filename private
Definition at line 33 of file GZIPOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 33 of file GZIPOutputStreamBuffer.h
Referenced by setFilename(), and writeHeader().
bool cheprep::GZIPOutputStreamBuffer::open private
Definition at line 35 of file GZIPOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 35 of file GZIPOutputStreamBuffer.h
Referenced by close(), and overflow().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/GZIPOutputStreamBuffer.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/GZIPOutputStreamBuffer.cc