ECCE @ EIC Software: G4TrajectoryPoint Class Reference
G4TrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4TrajectoryPoint.hh>
Public Member Functions
G4TrajectoryPoint ()
G4TrajectoryPoint (G4ThreeVector pos)
G4TrajectoryPoint (const G4TrajectoryPoint &right)
virtual ~G4TrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const G4TrajectoryPoint &right) const
const G4ThreeVector GetPosition () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
virtual const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
Private Attributes
G4ThreeVector fPosition
Detailed Description
Definition at line 59 of file G4TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 59 of file G4TrajectoryPoint.hh
Constructor & Destructor Documentation
G4TrajectoryPoint::G4TrajectoryPoint ()
Definition at line 52 of file G4TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 52 of file G4TrajectoryPoint.cc
References fPosition.
G4TrajectoryPoint::G4TrajectoryPoint (G4ThreeVector pos)
Definition at line 57 of file G4TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 57 of file G4TrajectoryPoint.cc
References fPosition, and pos().
G4TrajectoryPoint::G4TrajectoryPoint (const G4TrajectoryPoint & right)
Definition at line 62 of file G4TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 62 of file G4TrajectoryPoint.cc
G4TrajectoryPoint::~G4TrajectoryPoint () virtual
Definition at line 67 of file G4TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 67 of file G4TrajectoryPoint.cc
Member Function Documentation
std::vector< G4AttValue > * G4TrajectoryPoint::CreateAttValues () const virtual
Reimplemented from G4VTrajectoryPoint.
Reimplemented in G4RichTrajectoryPoint, WLSTrajectoryPoint, and F04TrajectoryPoint.
Definition at line 84 of file G4TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 84 of file G4TrajectoryPoint.cc
References fPosition, G4BestUnit, G4cout, GetAttDefs(), and Acts::Test::values.
Referenced by G4RichTrajectoryPoint::CreateAttValues().
const std::map< G4String, G4AttDef > * G4TrajectoryPoint::GetAttDefs () const virtual
Reimplemented from G4VTrajectoryPoint.
Reimplemented in G4RichTrajectoryPoint, WLSTrajectoryPoint, and F04TrajectoryPoint.
Definition at line 71 of file G4TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 71 of file G4TrajectoryPoint.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues(), G4RichTrajectoryPoint::GetAttDefs(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
const G4ThreeVector G4TrajectoryPoint::GetPosition (void) const inline virtual
Implements G4VTrajectoryPoint.
Definition at line 80 of file G4TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TrajectoryPoint.hh
References fPosition.
Referenced by RE01Trajectory::DrawTrajectory(), and RE01Trajectory::ShowTrajectory().
void G4TrajectoryPoint::operator delete (void * aTrajectoryPoint) inline
Definition at line 106 of file G4TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 106 of file G4TrajectoryPoint.hh
References aTrajectoryPointAllocator().
void * G4TrajectoryPoint::operator new (size_t) inline
Definition at line 99 of file G4TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 99 of file G4TrajectoryPoint.hh
References aTrajectoryPointAllocator().
G4bool G4TrajectoryPoint::operator== (const G4TrajectoryPoint & right) const inline
Definition at line 76 of file G4TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 76 of file G4TrajectoryPoint.hh
Member Data Documentation
G4ThreeVector G4TrajectoryPoint::fPosition private
Definition at line 92 of file G4TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 92 of file G4TrajectoryPoint.hh
Referenced by CreateAttValues(), G4TrajectoryPoint(), and GetPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4TrajectoryPoint.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4TrajectoryPoint.cc