ECCE @ EIC Software: G4FastList_iterator< OBJECT > Struct Template Reference
G4FastList_iterator< OBJECT > Struct Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh>
Public Types
typedef G4FastList_iterator
< OBJECT > _Self
typedef G4FastListNode< OBJECT > _Node
Public Member Functions
G4FastList_iterator ()=default
G4FastList_iterator (_Node *__x)
G4FastList_iterator (const G4FastList_iterator &right)=default
_Self & operator= (const G4FastList_iterator &right)=default
_Node * GetNode ()
const _Node * GetNode () const
OBJECT * operator* ()
const OBJECT * operator* () const
OBJECT * operator-> ()
const OBJECT * operator-> () const
_Self & operator++ ()
_Self operator++ (int)
_Self & operator-- ()
_Self operator-- (int)
G4bool operator== (const _Self &__x) const
G4bool operator!= (const _Self &__x) const
Public Attributes
_Node * fpNode = nullptr
Detailed Description
template<typename OBJECT>
struct G4FastList_iterator< OBJECT >
G4FastList_iterator enables to go through the tracks contained by a list.
Definition at line 60 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 60 of file G4FastList.hh
Member Typedef Documentation
template<typename OBJECT> typedef G4FastListNode<OBJECT> G4FastList_iterator< OBJECT >::_Node
Definition at line 461 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 461 of file G4FastList.hh
template<typename OBJECT> typedef G4FastList_iterator<OBJECT> G4FastList_iterator< OBJECT >::_Self
Definition at line 460 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 460 of file G4FastList.hh
Constructor & Destructor Documentation
template<typename OBJECT> G4FastList_iterator< OBJECT >::G4FastList_iterator () default
template<typename OBJECT> G4FastList_iterator< OBJECT >::G4FastList_iterator (_Node * __x) inline explicit
Definition at line 465 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 465 of file G4FastList.hh
template<typename OBJECT> G4FastList_iterator< OBJECT >::G4FastList_iterator (const G4FastList_iterator< OBJECT > & right) default
Member Function Documentation
template<typename OBJECT> _Node* G4FastList_iterator< OBJECT >::GetNode () inline
Definition at line 473 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 473 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode.
Referenced by G4FastList_const_iterator< OBJECT >::operator=(), and G4ManyFastLists< G4Track >::RemoveLists().
template<typename OBJECT> const _Node* G4FastList_iterator< OBJECT >::GetNode () const inline
Definition at line 478 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 478 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode.
template<typename OBJECT> G4bool G4FastList_iterator< OBJECT >::operator!= (const _Self & __x) const inline
Definition at line 528 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 528 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode.
template<typename OBJECT> OBJECT* G4FastList_iterator< OBJECT >::operator* ()
template<typename OBJECT> const OBJECT* G4FastList_iterator< OBJECT >::operator* () const
template<typename OBJECT> _Self& G4FastList_iterator< OBJECT >::operator++ () inline
Definition at line 496 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 496 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode, and G4FastListNode< OBJECT >::GetNext().
template<typename OBJECT> _Self G4FastList_iterator< OBJECT >::operator++ (int) inline
Definition at line 502 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 502 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode, and G4FastListNode< OBJECT >::GetNext().
template<typename OBJECT> _Self& G4FastList_iterator< OBJECT >::operator-- () inline
Definition at line 510 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 510 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode, and G4FastListNode< OBJECT >::GetPrevious().
template<typename OBJECT> _Self G4FastList_iterator< OBJECT >::operator-- (int) inline
Definition at line 516 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 516 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode, and G4FastListNode< OBJECT >::GetPrevious().
template<typename OBJECT> OBJECT* G4FastList_iterator< OBJECT >::operator-> ()
template<typename OBJECT> const OBJECT* G4FastList_iterator< OBJECT >::operator-> () const
template<typename OBJECT> _Self& G4FastList_iterator< OBJECT >::operator= (const G4FastList_iterator< OBJECT > & right) default
template<typename OBJECT> G4bool G4FastList_iterator< OBJECT >::operator== (const _Self & __x) const inline
Definition at line 523 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 523 of file G4FastList.hh
References G4FastList_iterator< OBJECT >::fpNode.
Member Data Documentation
template<typename OBJECT> _Node* G4FastList_iterator< OBJECT >::fpNode = nullptr
Definition at line 535 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 535 of file G4FastList.hh
Referenced by G4FastList_iterator< OBJECT >::GetNode(), G4FastList_iterator< OBJECT >::operator!=(), G4FastList_iterator< OBJECT >::operator++(), G4FastList_iterator< OBJECT >::operator--(), and G4FastList_iterator< OBJECT >::operator==().
The documentation for this struct was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh