ECCE @ EIC Software: RunInitManager Class Reference
RunInitManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/RunInitObserver.hh>
Public Member Functions
void Initialize ()
void Initialize ()
void Initialize ()
void Initialize ()
void Initialize ()
Static Public Member Functions
static RunInitManager * Instance ()
static RunInitManager * Instance ()
static RunInitManager * Instance ()
static RunInitManager * Instance ()
static RunInitManager * Instance ()
Protected Member Functions
RunInitManager ()
~RunInitManager ()
void Insert (RunInitObserver *)
RunInitManager ()
~RunInitManager ()
void Insert (RunInitObserver *)
RunInitManager ()
~RunInitManager ()
void Insert (RunInitObserver *)
RunInitManager ()
~RunInitManager ()
void Insert (RunInitObserver *)
RunInitManager ()
~RunInitManager ()
void Insert (RunInitObserver *)
Protected Attributes
std::vector< RunInitObserver * > fObservers
Static Protected Attributes
static G4ThreadLocal
RunInitManager * fgInstance
Friends
class RunInitObserver
Detailed Description
Definition at line 56 of file RunInitObserver.hh.
View newest version in sPHENIX GitHub at line 56 of file RunInitObserver.hh
Constructor & Destructor Documentation
RunInitManager::RunInitManager () protected
Definition at line 42 of file RunInitObserver.cc.
View newest version in sPHENIX GitHub at line 42 of file RunInitObserver.cc
References fgInstance.
Referenced by Instance().
RunInitManager::~RunInitManager () protected
Definition at line 49 of file RunInitObserver.cc.
View newest version in sPHENIX GitHub at line 49 of file RunInitObserver.cc
RunInitManager::RunInitManager () protected
RunInitManager::~RunInitManager () protected
RunInitManager::RunInitManager () protected
RunInitManager::~RunInitManager () protected
RunInitManager::RunInitManager () protected
RunInitManager::~RunInitManager () protected
RunInitManager::RunInitManager () protected
RunInitManager::~RunInitManager () protected
Member Function Documentation
void RunInitManager::Initialize ()
void RunInitManager::Initialize ()
Definition at line 78 of file RunInitObserver.cc.
View newest version in sPHENIX GitHub at line 78 of file RunInitObserver.cc
References fObservers, and it.
void RunInitManager::Initialize ()
void RunInitManager::Initialize ()
void RunInitManager::Initialize ()
void RunInitManager::Insert (RunInitObserver *) protected
void RunInitManager::Insert (RunInitObserver * observer) protected
Definition at line 88 of file RunInitObserver.cc.
View newest version in sPHENIX GitHub at line 88 of file RunInitObserver.cc
References fObservers.
Referenced by RunInitObserver::RunInitObserver().
void RunInitManager::Insert (RunInitObserver *) protected
void RunInitManager::Insert (RunInitObserver *) protected
void RunInitManager::Insert (RunInitObserver *) protected
static RunInitManager* RunInitManager::Instance () static
RunInitManager * RunInitManager::Instance (void) static
Definition at line 69 of file RunInitObserver.cc.
View newest version in sPHENIX GitHub at line 69 of file RunInitObserver.cc
References fgInstance, and RunInitManager().
Referenced by RunInitObserver::RunInitObserver().
static RunInitManager* RunInitManager::Instance () static
static RunInitManager* RunInitManager::Instance () static
static RunInitManager* RunInitManager::Instance () static
Friends And Related Function Documentation
RunInitObserver friend
Definition at line 63 of file RunInitObserver.hh.
View newest version in sPHENIX GitHub at line 63 of file RunInitObserver.hh
Member Data Documentation
G4ThreadLocal RunInitManager * RunInitManager::fgInstance static protected
Definition at line 69 of file RunInitObserver.hh.
View newest version in sPHENIX GitHub at line 69 of file RunInitObserver.hh
Referenced by Instance(), and RunInitManager().
std::vector< RunInitObserver * > RunInitManager::fObservers protected
Definition at line 68 of file RunInitObserver.hh.
View newest version in sPHENIX GitHub at line 68 of file RunInitObserver.hh
Referenced by Initialize(), and Insert().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/RunInitObserver.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/RunInitObserver.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/RunInitObserver.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/RunInitObserver.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/RunInitObserver.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/RunInitObserver.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/RunInitObserver.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/RunInitObserver.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/RunInitObserver.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/RunInitObserver.cc