ECCE @ EIC Software: F04RunAction Class Reference
F04RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04RunAction.hh>
Public Member Functions
F04RunAction ()
virtual ~F04RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetRndmFreq (G4int val)
G4int GetRndmFreq ()
void SetAutoSeed (const G4bool val)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
F04RunActionMessenger * fRunMessenger
G4int fSaveRndm
G4bool fAutoSeed
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 41 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 41 of file F04RunAction.hh
Constructor & Destructor Documentation
F04RunAction::F04RunAction ()
Definition at line 43 of file F04RunAction.cc.
View newest version in sPHENIX GitHub at line 43 of file F04RunAction.cc
References fRunMessenger.
F04RunAction::~F04RunAction () virtual
Definition at line 51 of file F04RunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file F04RunAction.cc
References fRunMessenger.
Member Function Documentation
void F04RunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 59 of file F04RunAction.cc.
View newest version in sPHENIX GitHub at line 59 of file F04RunAction.cc
References fAutoSeed, fSaveRndm, G4cout, G4endl, G4Threading::G4GetThreadId(), G4UniformRand, G4Run::GetRunID(), G4RunManager::GetRunManager(), G4RunManager::SetRandomNumberStore(), G4RunManager::SetRandomNumberStoreDir(), and Acts::VectorHelpers::time().
void F04RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 91 of file F04RunAction.cc.
View newest version in sPHENIX GitHub at line 91 of file F04RunAction.cc
References fSaveRndm, and G4Threading::G4GetThreadId().
G4int F04RunAction::GetRndmFreq () inline
Definition at line 54 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file F04RunAction.hh
References fSaveRndm.
Referenced by F04EventAction::EndOfEventAction().
void F04RunAction::SetAutoSeed (const G4bool val) inline
Definition at line 56 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file F04RunAction.hh
References fAutoSeed.
Referenced by F04RunActionMessenger::SetNewValue().
void F04RunAction::SetRndmFreq (G4int val) inline
Definition at line 53 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 53 of file F04RunAction.hh
References fSaveRndm.
Referenced by F04RunActionMessenger::SetNewValue().
Member Data Documentation
G4bool F04RunAction::fAutoSeed private
Definition at line 63 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file F04RunAction.hh
Referenced by BeginOfRunAction(), and SetAutoSeed().
F04RunActionMessenger* F04RunAction::fRunMessenger private
Definition at line 60 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file F04RunAction.hh
Referenced by F04RunAction(), and ~F04RunAction().
G4int F04RunAction::fSaveRndm private
Definition at line 62 of file F04RunAction.hh.
View newest version in sPHENIX GitHub at line 62 of file F04RunAction.hh
Referenced by BeginOfRunAction(), EndOfRunAction(), GetRndmFreq(), and SetRndmFreq().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04RunAction.cc