ECCE @ EIC Software: G4ElasticData Class Reference
G4ElasticData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ElasticHadrNucleusHE.hh>
Public Member Functions
G4ElasticData (const G4ParticleDefinition *h, G4int Z, G4int A, const G4double *e)
~G4ElasticData ()
Private Member Functions
void DefineNucleusParameters (G4int A)
G4ElasticData & operator= (const G4ElasticData &right)
G4ElasticData (const G4ElasticData &)
Private Attributes
G4double R1
G4double R2
G4double Pnucl
G4double Aeff
G4double dQ2
G4double massA
G4double massA2
G4double maxQ2 [NENERGY]
std::vector< G4double > fCumProb [NENERGY]
Friends
class G4ElasticHadrNucleusHE
Detailed Description
Definition at line 62 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ElasticHadrNucleusHE.hh
Constructor & Destructor Documentation
G4ElasticData::G4ElasticData (const G4ParticleDefinition * h, G4int Z, G4int A, const G4double * e)
Definition at line 97 of file G4ElasticHadrNucleusHE.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ElasticHadrNucleusHE.cc
References G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), invGeV, NENERGY, ONQ2, and G4Proton::Proton().
G4ElasticData::~G4ElasticData () inline
Definition at line 72 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ElasticHadrNucleusHE.hh
G4ElasticData::G4ElasticData (const G4ElasticData &) private
Member Function Documentation
void G4ElasticData::DefineNucleusParameters (G4int A) private
Definition at line 133 of file G4ElasticHadrNucleusHE.cc.
View newest version in sPHENIX GitHub at line 133 of file G4ElasticHadrNucleusHE.cc
References A(), G4Exp(), and G4Log().
G4ElasticData& G4ElasticData::operator= (const G4ElasticData & right) private
Friends And Related Function Documentation
friend class G4ElasticHadrNucleusHE friend
Definition at line 65 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ElasticHadrNucleusHE.hh
Member Data Documentation
G4double G4ElasticData::Aeff private
Definition at line 82 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ElasticHadrNucleusHE.hh
G4double G4ElasticData::dQ2 private
Definition at line 83 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ElasticHadrNucleusHE.hh
Referenced by G4ElasticHadrNucleusHE::HadronNucleusQ2_2().
std::vector<G4double> G4ElasticData::fCumProb[NENERGY] private
Definition at line 87 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ElasticHadrNucleusHE.hh
Referenced by G4ElasticHadrNucleusHE::HadronNucleusQ2_2().
G4double G4ElasticData::massA private
Definition at line 84 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ElasticHadrNucleusHE.hh
G4double G4ElasticData::massA2 private
Definition at line 85 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ElasticHadrNucleusHE.hh
G4double G4ElasticData::maxQ2[NENERGY] private
Definition at line 86 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ElasticHadrNucleusHE.hh
Referenced by G4ElasticHadrNucleusHE::HadronNucleusQ2_2().
G4double G4ElasticData::Pnucl private
Definition at line 82 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ElasticHadrNucleusHE.hh
G4double G4ElasticData::R1 private
Definition at line 82 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ElasticHadrNucleusHE.hh
Referenced by G4ElasticHadrNucleusHE::HadronNucleusQ2_2().
G4double G4ElasticData::R2 private
Definition at line 82 of file G4ElasticHadrNucleusHE.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ElasticHadrNucleusHE.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ElasticHadrNucleusHE.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4ElasticHadrNucleusHE.cc