ECCE @ EIC Software: ExTGRCDetectorBuilder Class Reference
ExTGRCDetectorBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/P03/include/ExTGRCDetectorBuilder.hh>
Public Member Functions
ExTGRCDetectorBuilder ()
~ExTGRCDetectorBuilder ()
const G4tgrVolume * ReadDetector ()
virtual G4VPhysicalVolume * ConstructDetector (const G4tgrVolume *tgrVoltop)
Public Member Functions inherited from G4tgbDetectorBuilder
G4tgbDetectorBuilder ()
virtual ~G4tgbDetectorBuilder ()
Private Attributes
ExTGRCLineProcessor * fTlproc
Detailed Description
Detector builder class implementing cuts per region
Changes: creation May 2007
Author
: P. Arce
Definition at line 45 of file ExTGRCDetectorBuilder.hh.
View newest version in sPHENIX GitHub at line 45 of file ExTGRCDetectorBuilder.hh
Constructor & Destructor Documentation
ExTGRCDetectorBuilder::ExTGRCDetectorBuilder ()
Definition at line 38 of file ExTGRCDetectorBuilder.cc.
View newest version in sPHENIX GitHub at line 38 of file ExTGRCDetectorBuilder.cc
ExTGRCDetectorBuilder::~ExTGRCDetectorBuilder ()
Definition at line 44 of file ExTGRCDetectorBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file ExTGRCDetectorBuilder.cc
References fTlproc.
Member Function Documentation
G4VPhysicalVolume * ExTGRCDetectorBuilder::ConstructDetector (const G4tgrVolume * tgrVoltop) virtual
Reimplemented from G4tgbDetectorBuilder.
Definition at line 67 of file ExTGRCDetectorBuilder.cc.
View newest version in sPHENIX GitHub at line 67 of file ExTGRCDetectorBuilder.cc
References ExTGRCRegionCutsMgr::BuildProductionCuts(), ExTGRCRegionCutsMgr::BuildRegions(), G4tgbDetectorBuilder::ConstructDetector(), and ExTGRCRegionCutsMgr::GetInstance().
Referenced by ExTGDetectorConstructionWithCuts::Construct().
const G4tgrVolume * ExTGRCDetectorBuilder::ReadDetector () virtual
Reimplemented from G4tgbDetectorBuilder.
Definition at line 50 of file ExTGRCDetectorBuilder.cc.
View newest version in sPHENIX GitHub at line 50 of file ExTGRCDetectorBuilder.cc
References fTlproc, G4tgrFileReader::GetInstance(), G4tgrVolumeMgr::GetInstance(), G4tgrVolumeMgr::GetTopVolume(), G4tgrFileReader::ReadFiles(), and G4tgrFileReader::SetLineProcessor().
Referenced by ExTGDetectorConstructionWithCuts::Construct().
Member Data Documentation
ExTGRCLineProcessor* ExTGRCDetectorBuilder::fTlproc private
Definition at line 56 of file ExTGRCDetectorBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file ExTGRCDetectorBuilder.hh
Referenced by ReadDetector(), and ~ExTGRCDetectorBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/P03/include/ExTGRCDetectorBuilder.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/P03/src/ExTGRCDetectorBuilder.cc