ECCE @ EIC Software: Par01ParallelWorldForPion Class Reference
Par01ParallelWorldForPion Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01ParallelWorldForPion.hh>
Public Member Functions
Par01ParallelWorldForPion (G4String worldName)
~Par01ParallelWorldForPion ()
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Member Functions
virtual void Construct ()
virtual void ConstructSD ()
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 36 of file Par01ParallelWorldForPion.hh.
View newest version in sPHENIX GitHub at line 36 of file Par01ParallelWorldForPion.hh
Constructor & Destructor Documentation
Par01ParallelWorldForPion::Par01ParallelWorldForPion (G4String worldName)
Definition at line 45 of file Par01ParallelWorldForPion.cc.
View newest version in sPHENIX GitHub at line 45 of file Par01ParallelWorldForPion.cc
Par01ParallelWorldForPion::~Par01ParallelWorldForPion ()
Definition at line 51 of file Par01ParallelWorldForPion.cc.
View newest version in sPHENIX GitHub at line 51 of file Par01ParallelWorldForPion.cc
Member Function Documentation
void Par01ParallelWorldForPion::Construct (void) private virtual
Implements G4VUserParallelWorld.
Definition at line 56 of file Par01ParallelWorldForPion.cc.
View newest version in sPHENIX GitHub at line 56 of file Par01ParallelWorldForPion.cc
References G4Region::AddRootLogicalVolume(), cm, G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4VUserParallelWorld::GetWorld(), G4NistManager::Instance(), and G4LogicalVolume::SetMaterial().
void Par01ParallelWorldForPion::ConstructSD () private virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 106 of file Par01ParallelWorldForPion.cc.
View newest version in sPHENIX GitHub at line 106 of file Par01ParallelWorldForPion.cc
References G4RegionStore::GetInstance(), and G4RegionStore::GetRegion().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01ParallelWorldForPion.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01ParallelWorldForPion.cc