ECCE @ EIC Software: G4ParticleDefinition Class Reference
G4ParticleDefinition Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticleDefinition.hh>
Inherited by G4AdjointElectron, G4AdjointElectronFI, G4AdjointGamma, G4AdjointIons, G4AdjointPositron, G4AdjointProton, G4AntiBMesonZero, G4AntiBsMesonZero, G4AntiDMesonZero, G4AntiKaonZero, G4AntiLambda, G4AntiLambdab, G4AntiLambdacPlus, G4AntiNeutrinoE, G4AntiNeutrinoMu, G4AntiNeutrinoTau, G4AntiNeutron, G4AntiOmegabMinus, G4AntiOmegacZero, G4AntiOmegaMinus, G4AntiProton, G4AntiSigmabMinus, G4AntiSigmabPlus, G4AntiSigmabZero, G4AntiSigmacPlus, G4AntiSigmacPlusPlus, G4AntiSigmacZero, G4AntiSigmaMinus, G4AntiSigmaPlus, G4AntiSigmaZero, G4AntiXibMinus, G4AntiXibZero, G4AntiXicPlus, G4AntiXicZero, G4AntiXiMinus, G4AntiXiZero, G4BcMesonMinus, G4BcMesonPlus, G4BMesonMinus, G4BMesonPlus, G4BMesonZero, G4BsMesonZero, G4ChargedGeantino, G4DMesonMinus, G4DMesonPlus, G4DMesonZero, G4DNAIons, G4DsMesonMinus, G4DsMesonPlus, G4Electron, G4Eta, G4Etac, G4EtaPrime, G4Gamma, G4Geantino, G4Ions, G4JPsi, G4KaonMinus, G4KaonPlus, G4KaonZero, G4KaonZeroLong, G4KaonZeroShort, G4Lambda, G4Lambdab, G4LambdacPlus, G4LDMHi, G4LDMHiBar, G4LDMPhoton, G4MoleculeDefinition, G4Monopole, G4MuonMinus, G4MuonPlus, G4NeutrinoE, G4NeutrinoMu, G4NeutrinoTau, G4OmegabMinus, G4OmegacZero, G4OmegaMinus, G4OpticalPhoton, G4PhononLong, G4PhononTransFast, G4PhononTransSlow, G4PionMinus, G4PionPlus, G4PionZero, G4Positron, G4SigmabMinus, G4SigmabPlus, G4SigmabZero, G4SigmacPlus, G4SigmacPlusPlus, G4SigmacZero, G4SigmaMinus, G4SigmaPlus, G4SigmaZero, G4TauMinus, G4TauPlus, G4UnknownParticle, G4Upsilon, G4VShortLivedParticle, G4XibMinus, G4XibZero, G4XicPlus, G4XicZero, G4XiMinus, and G4XiZero.
Public Member Functions
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Static Public Member Functions
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Protected Types
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Private Member Functions
const G4ParticleDefinition & operator= (const G4ParticleDefinition &r)
Private Attributes
G4ProcessManager * theProcessManagerShadow
G4int g4particleDefinitionInstanceID
G4String theParticleName
G4double thePDGMass
G4double thePDGWidth
G4double thePDGCharge
G4int thePDGiSpin
G4double thePDGSpin
G4int thePDGiParity
G4int thePDGiConjugation
G4int thePDGiGParity
G4int thePDGiIsospin
G4int thePDGiIsospin3
G4double thePDGIsospin
G4double thePDGIsospin3
G4double thePDGMagneticMoment
G4int theLeptonNumber
G4int theBaryonNumber
G4String theParticleType
G4String theParticleSubType
G4int thePDGEncoding
G4int theAntiPDGEncoding
G4bool fShortLivedFlag
G4bool thePDGStable
G4double thePDGLifeTime
G4DecayTable * theDecayTable
G4ParticleTable * theParticleTable
G4int theAtomicNumber
G4int theAtomicMass
G4int verboseLevel
G4bool fApplyCutsFlag
Static Private Attributes
static G4PART_DLL G4PDefManager subInstanceManager
Friends
class G4ParticlePropertyTable
Detailed Description
Definition at line 72 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleDefinition.hh
Member Enumeration Documentation
anonymous enum protected
Enumerator:
NumberOfQuarkFlavor
Definition at line 265 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 265 of file G4ParticleDefinition.hh
Constructor & Destructor Documentation
G4ParticleDefinition::G4ParticleDefinition (const G4String & aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String & pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable * decaytable, G4bool shortlived = false, const G4String & subType = "", G4int anti_encoding = 0, G4double magneticMoment = 0.0)
Definition at line 73 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleDefinition.cc
References kdfinder::abs(), eplus, FillQuarkContents(), fShortLivedFlag, G4cout, G4endl, G4Exception(), g4particleDefinitionInstanceID, G4State_PreInit, GetBaryonNumber(), G4StateManager::GetCurrentState(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), GetPDGCharge(), G4StateManager::GetStateManager(), G4ParticleTable::GetVerboseLevel(), GetVerboseLevel(), G4ParticleTable::Insert(), G4IonTable::IsAntiIon(), G4IonTable::IsIon(), JustWarning, SetAtomicMass(), SetAtomicNumber(), theAntiPDGEncoding, theParticleTable, theParticleType, thePDGEncoding, theProcessManagerShadow, and verboseLevel.
G4ParticleDefinition::~G4ParticleDefinition () virtual
Definition at line 199 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 199 of file G4ParticleDefinition.cc
References G4cout, G4endl, G4Exception(), G4State_PreInit, G4StateManager::GetCurrentState(), GetParticleName(), G4ParticleTable::GetParticleTable(), G4StateManager::GetStateManager(), JustWarning, return(), theDecayTable, and verboseLevel.
G4ParticleDefinition::G4ParticleDefinition (const G4ParticleDefinition & right) protected
Definition at line 184 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 184 of file G4ParticleDefinition.cc
References FatalException, and G4Exception().
G4ParticleDefinition::G4ParticleDefinition () protected
Definition at line 191 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 191 of file G4ParticleDefinition.cc
References FatalException, and G4Exception().
Referenced by G4PhononLong::Definition(), G4PhononTransSlow::Definition(), G4PhononTransFast::Definition(), G4EtaPrime::Definition(), G4Upsilon::Definition(), G4BcMesonMinus::Definition(), G4BcMesonPlus::Definition(), G4MuonPlus::Definition(), G4AntiNeutron::Definition(), G4AntiXicPlus::Definition(), G4BMesonMinus::Definition(), G4AntiNeutrinoMu::Definition(), G4BMesonPlus::Definition(), G4PionZero::Definition(), G4BMesonZero::Definition(), G4PionPlus::Definition(), G4PionMinus::Definition(), G4BsMesonZero::Definition(), G4AntiXicZero::Definition(), G4KaonZero::Definition(), G4KaonPlus::Definition(), G4KaonMinus::Definition(), G4DMesonMinus::Definition(), G4Lambda::Definition(), G4DMesonPlus::Definition(), G4Eta::Definition(), G4AntiXiMinus::Definition(), G4DMesonZero::Definition(), G4DsMesonMinus::Definition(), G4AntiLambdacPlus::Definition(), G4AntiOmegabMinus::Definition(), G4DsMesonPlus::Definition(), G4AntiXiZero::Definition(), G4AntiOmegacZero::Definition(), G4JPsi::Definition(), G4AntiSigmaZero::Definition(), G4LambdacPlus::Definition(), G4AntiKaonZero::Definition(), G4AntiOmegaMinus::Definition(), G4AntiBsMesonZero::Definition(), G4AntiBMesonZero::Definition(), G4XiZero::Definition(), G4OmegabMinus::Definition(), G4XicZero::Definition(), G4XicPlus::Definition(), G4KaonZeroLong::Definition(), G4KaonZeroShort::Definition(), G4SigmaZero::Definition(), G4OmegacZero::Definition(), G4AntiProton::Definition(), G4OmegaMinus::Definition(), G4NeutrinoTau::Definition(), G4NeutrinoE::Definition(), G4MuonMinus::Definition(), G4AntiNeutrinoE::Definition(), G4SigmacPlus::Definition(), G4AntiNeutrinoTau::Definition(), G4Electron::Definition(), G4SigmacPlusPlus::Definition(), G4AntiSigmacPlus::Definition(), G4SigmacZero::Definition(), G4SigmaMinus::Definition(), G4TauMinus::Definition(), G4SigmaPlus::Definition(), G4AntiSigmacPlusPlus::Definition(), G4AntiSigmacZero::Definition(), G4NeutrinoMu::Definition(), G4AntiLambda::Definition(), G4AntiDMesonZero::Definition(), G4AntiSigmaMinus::Definition(), G4XiMinus::Definition(), G4AntiSigmaPlus::Definition(), G4TauPlus::Definition(), G4AntiSigmabMinus::Definition(), G4SigmabPlus::Definition(), G4AntiXibZero::Definition(), G4Etac::Definition(), G4XibZero::Definition(), G4SigmabZero::Definition(), G4AntiSigmabZero::Definition(), G4AntiXibMinus::Definition(), G4AntiSigmabPlus::Definition(), G4XibMinus::Definition(), G4SigmabMinus::Definition(), G4Positron::Definition(), G4Lambdab::Definition(), G4AntiLambdab::Definition(), G4OpticalPhoton::Definition(), G4Geantino::Definition(), G4Gamma::Definition(), G4UnknownParticle::Definition(), G4ChargedGeantino::Definition(), G4AdjointElectron::Definition(), G4AdjointPositron::Definition(), G4AdjointElectronFI::Definition(), G4AdjointProton::Definition(), and G4AdjointGamma::Definition().
Member Function Documentation
G4double G4ParticleDefinition::CalculateAnomaly () const
Definition at line 421 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 421 of file G4ParticleDefinition.cc
References CLHEP::c_squared, CLHEP::eplus, G4Exception(), CLHEP::hbar_Planck, JustWarning, thePDGCharge, thePDGiSpin, thePDGMagneticMoment, and thePDGMass.
void G4ParticleDefinition::Clean () static
Definition at line 250 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 250 of file G4ParticleDefinition.cc
References G4PDefManager::FreeSlave(), and subInstanceManager.
Referenced by G4ParticleTable::~G4ParticleTable().
void G4ParticleDefinition::DumpTable () const
Definition at line 330 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 330 of file G4ParticleDefinition.cc
References G4DecayTable::DumpInfo(), eplus, fShortLivedFlag, G4BestUnit, G4cout, G4endl, GetAntiPDGEncoding(), GetAtomicMass(), GetAtomicNumber(), GetIonLifeTime(), G4ParticleTable::GetIonTable(), GeV, G4IonTable::IsAntiIon(), IsGeneralIon(), G4IonTable::IsIon(), MeV, ns, tesla, theAntiQuarkContent, theBaryonNumber, theDecayTable, theLeptonNumber, theParticleName, theParticleSubType, theParticleTable, theParticleType, thePDGCharge, thePDGEncoding, thePDGiConjugation, thePDGiGParity, thePDGiIsospin, thePDGiIsospin3, thePDGiParity, thePDGiSpin, thePDGLifeTime, thePDGMagneticMoment, thePDGMass, thePDGStable, thePDGWidth, and theQuarkContent.
Referenced by G4ParticleTable::DumpTable(), G4IonTable::DumpTable(), export_G4ParticleDefinition(), G4ParticlePropertyMessenger::SetNewValue(), and G4ParticleMessenger::SetNewValue().
G4int G4ParticleDefinition::FillQuarkContents () protected
Definition at line 263 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 263 of file G4ParticleDefinition.cc
References G4PDGCodeChecker::CheckCharge(), G4PDGCodeChecker::CheckPDGCode(), eplus, G4cout, G4endl, G4Exception(), G4PDGCodeChecker::GetAntiQuarkContent(), G4PDGCodeChecker::GetQuarkContent(), G4PDGCodeChecker::GetSpin(), JustWarning, NumberOfQuarkFlavor, G4PDGCodeChecker::SetVerboseLevel(), theAntiQuarkContent, theParticleType, thePDGCharge, thePDGEncoding, thePDGiSpin, theQuarkContent, and verboseLevel.
Referenced by G4ParticleDefinition().
G4int G4ParticleDefinition::GetAntiPDGEncoding () const inline
Definition at line 147 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ParticleDefinition.hh
References theAntiPDGEncoding.
Referenced by DumpTable(), export_G4ParticleDefinition(), G4ParticlePropertyTable::GetParticleProperty(), and G4BetheHeitler5DModel::SetLeptonPair().
G4int G4ParticleDefinition::GetAntiQuarkContent (G4int flavor) const
Referenced by G4RPGInelastic::CheckQnums(), G4ElementaryParticleCollider::collide(), G4XAqmTotal::CrossSection(), export_G4ParticleDefinition(), G4HtmlPPReporter::GeneratePropertyTable(), G4VCollision::GetNumberOfPartons(), G4InuclElementaryParticle::getStrangeness(), and G4XAnnihilationChannel::NormalizedClebsch().
G4bool G4ParticleDefinition::GetApplyCutsFlag () const
Referenced by G4ITStepProcessor::DealWithSecondaries(), export_G4ParticleDefinition(), G4VUserPhysicsList::GetApplyCuts(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), and G4SteppingManager::InvokePSDIP().
G4int G4ParticleDefinition::GetAtomicMass () const
Referenced by G4SDParticleFilter::Accept(), G4INCLXXInterface::AccurateProjectile(), G4CollisionOutput::addOutgoingParticles(), PHG4TruthTrackingAction::AddParticle(), G4ParticleHPFinalState::adjust_final_state(), G4LENDCapture::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4QMDReaction::calcOffSetOfCollision(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4IonTable::Contains(), G4CascadeInterface::createBullet(), G4SFDecay::DecayIt(), G4MuonicAtomDecay::DecayIt(), DumpTable(), export_G4ParticleDefinition(), G4IonTable::FindIon(), G4IonTable::FindIonInMaster(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4ECDecay::G4ECDecay(), G4FissionProductYieldDist::G4GetFission(), G4ITDecay::G4ITDecay(), G4NeutronDecay::G4NeutronDecay(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TritonDecay::G4TritonDecay(), G4InuclNuclei::getA(), G4IonProtonCrossSection::GetElementCrossSection(), G4IonTable::GetMuonicAtom(), G4IonTable::GetNucleusMass(), G4IonTable::Insert(), G4IonTable::InsertWorker(), G4IonTable::IsAntiIon(), G4HadronicAbsorptionBertini::IsApplicable(), G4CascadeInterface::IsApplicable(), G4IonTable::IsIon(), STCyclotronSensitiveTarget::ProcessHits(), G4DNARuddIonisationExtendedModel::ProposedSampledEnergy(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4IntraNucleiCascader::releaseSecondary(), G4IonTable::Remove(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4FissionProductYieldDist::SortProbability(), and G4INCLXXInterface::toINCLParticleSpecies().
G4int G4ParticleDefinition::GetAtomicNumber () const
Referenced by G4SDParticleFilter::Accept(), G4CollisionOutput::addOutgoingParticles(), PHG4TruthTrackingAction::AddParticle(), G4ParticleHPFinalState::adjust_final_state(), G4LENDCapture::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4QMDReaction::calcOffSetOfCollision(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4IonTable::Contains(), G4CascadeInterface::createBullet(), G4ECDecay::DecayIt(), G4SFDecay::DecayIt(), G4MuonicAtomDecay::DecayIt(), DumpTable(), G4EmCorrections::EffectiveChargeCorrection(), export_G4ParticleDefinition(), G4IonTable::FindIon(), G4IonTable::FindIonInMaster(), G4AlphaDecay::G4AlphaDecay(), G4BetaMinusDecay::G4BetaMinusDecay(), G4BetaPlusDecay::G4BetaPlusDecay(), G4DNAIons::G4DNAIons(), G4ECDecay::G4ECDecay(), G4FissionProductYieldDist::G4GetFission(), G4Ions::G4Ions(), G4ITDecay::G4ITDecay(), G4NeutronDecay::G4NeutronDecay(), G4ProtonDecay::G4ProtonDecay(), G4SFDecay::G4SFDecay(), G4TritonDecay::G4TritonDecay(), G4PrimaryTransformer::GenerateSingleTrack(), G4IonProtonCrossSection::GetElementCrossSection(), G4IonTable::GetMuonicAtom(), G4IonTable::GetNucleusMass(), G4InuclNuclei::getZ(), G4IonTable::Insert(), G4IonTable::InsertWorker(), G4IonTable::IsAntiIon(), G4IonTable::IsIon(), STCyclotronSensitiveTarget::ProcessHits(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4IntraNucleiCascader::releaseSecondary(), G4IonTable::Remove(), G4FissionProductYieldDist::SortProbability(), and G4INCLXXInterface::toINCLParticleSpecies().
G4int G4ParticleDefinition::GetBaryonNumber () const inline
Definition at line 144 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParticleDefinition.hh
References theBaryonNumber.
Referenced by G4INCLXXInterface::AccurateProjectile(), G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode(), G4BinaryCascade::ApplyCollision(), G4BinaryLightIonReaction::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4InuclElementaryParticle::baryon(), G4ParticleHPInelasticBaseFS::BaseApply(), G4HadLeadBias::Bias(), G4WilsonAblationModel::BreakItUp(), G4EmCorrections::BuildCorrectionVector(), G4QGSParticipants::BuildInteractions(), G4BinaryCascade::BuildLateParticleCollisions(), G4CrossSectionElastic::BuildPhysicsTable(), G4CrossSectionInelastic::BuildPhysicsTable(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4RPGInelastic::CheckQnums(), G4ElementaryParticleCollider::collide(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4SPSEneDistribution::ConvertEPNToEnergy(), G4BinaryCascade::DebugApplyCollision(), G4KineticTrack::Decay(), G4QGSParticipants::DeterminePartonMomenta(), export_G4ParticleDefinition(), G4HadronicProcessStore::FindProcess(), G4AdjointIons::G4AdjointIons(), G4DNAIons::G4DNAIons(), G4Ions::G4Ions(), G4ParticleDefinition(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4QMDParticipant::GetBaryonNumber(), G4TripathiCrossSection::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4IonsSihverCrossSection::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4GeneralSpaceNNCrossSection::GetElementCrossSection(), G4MesonAbsorption::GetFinalState(), G4EnergyRangeManager::GetHadronicInteraction(), G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection(), G4IonsShenCrossSection::GetIsoCrossSection(), G4QMDParticipant::GetNuc(), G4ParticlePropertyTable::GetParticleProperty(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), G4FTFModel::Init(), G4FTFParameters::InitForInteraction(), G4NuclNuclDiffuseElastic::Initialise(), G4NuclNuclDiffuseElastic::InitialiseOnFly(), G4NuclNuclDiffuseElastic::InitParameters(), G4NuclNuclDiffuseElastic::InitParametersGla(), G4IonTable::IsAntiIon(), G4HadronicAbsorptionFritiof::IsApplicable(), G4TripathiCrossSection::IsElementApplicable(), G4IonsSihverCrossSection::IsElementApplicable(), G4IonsKoxCrossSection::IsElementApplicable(), G4IonsShenCrossSection::IsElementApplicable(), G4TripathiLightCrossSection::IsElementApplicable(), G4GeneralSpaceNNCrossSection::IsElementApplicable(), G4IonTable::IsIon(), G4AdjointTrackingAction::PostUserTrackingAction(), G4HadronicProcessStore::Print(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4NuclNuclDiffuseElastic::SampleCoulombMuCMS(), G4AntiNuclElastic::SampleInvariantT(), G4Scatterer::Scatter(), G4VPartonStringModel::Scatter(), G4WilsonAblationModel::SelectSecondariesByDefault(), G4AtimaEnergyLossModel::SetParticle(), G4BetheBlochModel::SetParticle(), G4ParticleHPInelasticCompFS::two_body_reaction(), and G4AdjointSteppingAction::UserSteppingAction().
G4DecayTable* G4ParticleDefinition::GetDecayTable () const
Referenced by G4DecayWithSpin::AtRestDoIt(), G4KineticTrack::Decay(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4IntraNucleiCascader::decayTrappedParticle(), export_G4ParticleDefinition(), G4KineticTrack::G4KineticTrack(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4SampleResonance::GetMinimumMass(), G4PrimaryTransformer::IsGoodForTrack(), G4TextPPRetriever::ModifyPropertyTable(), G4DecayWithSpin::PostStepDoIt(), G4DecayTableMessenger::SetCurrentParticle(), and G4ParticleGun::SetParticleDefinition().
G4int G4ParticleDefinition::GetInstanceID () const inline
Referenced by G4VUserPhysicsList::RemoveProcessManager().
G4double G4ParticleDefinition::GetIonLifeTime () const
Referenced by DumpTable().
G4int G4ParticleDefinition::GetLeptonNumber () const inline
Definition at line 143 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 143 of file G4ParticleDefinition.hh
References theLeptonNumber.
Referenced by G4HadLeadBias::Bias(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4DNARuddIonisationModel::DifferentialCrossSection(), export_G4ParticleDefinition(), G4ParticlePropertyTable::GetParticleProperty(), G4DNAMillerGreenExcitationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4AtimaEnergyLossModel::SetupParameters(), and G4BetheBlochModel::SetupParameters().
G4ProcessManager* G4ParticleDefinition::GetMasterProcessManager () const inline
Referenced by G4VUserChemistryList::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4VUserPhysicsList::InitializeProcessManager(), G4VUserPhysicsList::PreparePhysicsTable(), and G4WorkerRunManagerKernel::SetupShadowProcess().
G4int G4ParticleDefinition::GetParticleDefinitionID () const
Referenced by G4IonTable::AddProcessManager(), G4IonTable::CreateIon(), G4RunManagerKernel::PropagateGenericIonID(), G4StackManager::PushOneTrack(), and G4RunManagerKernel::SetupPhysics().
const G4String& G4ParticleDefinition::GetParticleName () const inline
Definition at line 120 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ParticleDefinition.hh
References theParticleName.
Referenced by G4INCLXXInterface::AccurateProjectile(), G4VEmProcess::ActivateForcedInteraction(), G4ProcessManager::ActivateProcess(), G4ITStepProcessor::ActiveOnlyITProcess(), G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles(), G4CollisionManager::AddCollision(), G4VHadronPhysics::AddElasticCrossSection(), G4VHadronPhysics::AddInelasticCrossSection(), PhysicsList::AddIonGasModels(), G4BiasingHelper::AddLimiterProcess(), PhysicsList::AddMaxStepSize(), G4CollisionOutput::addOutgoingParticles(), PHG4TruthTrackingAction::AddParticle(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), G4ProcessManager::AddProcess(), G4IonTable::AddProcessManager(), G4EmModelActivator::AddStandardScattering(), HistoManager::AddTargetStep(), PhysicsList::AddTrackingCut(), G4PhysicsListHelper::AddTransportation(), DMXPhysicsList::AddTransportation(), LBE::AddTransportation(), G4ParticleHPFinalState::adjust_final_state(), G4ErrorEnergyLoss::AlongStepDoIt(), G4BinaryCascade::ApplyCollision(), BiasingOperation::ApplyFinalStateBiasing(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4GenericBiasingPhysics::AssociateParallelGeometries(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronBuilder::Barion(), G4ParticleHPInelasticBaseFS::BaseApply(), RunAction::BeginOfRunAction(), G4WilsonAblationModel::BreakItUp(), G4EmCorrections::BuildCorrectionVector(), G4VEnergyLossProcess::BuildDEDXTable(), G4VUserPhysicsList::BuildIntegralPhysicsTable(), G4QGSParticipants::BuildInteractions(), G4VEnergyLossProcess::BuildLambdaTable(), G4hImpactIonisation::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4DNAModelInterface::BuildMaterialParticleModelTable(), G4PiNuclearCrossSection::BuildPhysicsTable(), G4ChargeExchangeProcess::BuildPhysicsTable(), G4UPiNuclearCrossSection::BuildPhysicsTable(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4VLEPTSModel::BuildPhysicsTable(), G4CrossSectionPairGG::BuildPhysicsTable(), G4LowECapture::BuildPhysicsTable(), G4BGGNucleonElasticXS::BuildPhysicsTable(), G4BGGNucleonInelasticXS::BuildPhysicsTable(), G4NeutronElasticXS::BuildPhysicsTable(), G4NeutronInelasticXS::BuildPhysicsTable(), G4ParticleInelasticXS::BuildPhysicsTable(), G4BGGPionElasticXS::BuildPhysicsTable(), G4NeutronCaptureXS::BuildPhysicsTable(), G4hImpactIonisation::BuildPhysicsTable(), G4BGGPionInelasticXS::BuildPhysicsTable(), G4CrossSectionDataStore::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4VUserChemistryList::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4LossTableManager::BuildPhysicsTable(), G4VEmProcess::BuildPhysicsTable(), G4DNABrownianTransportation::BuildPhysicsTable(), G4VMultipleScattering::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4ScreenedNuclearRecoil::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4HadronCrossSections::CalcScatteringCrossSections(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4PhysicsListHelper::CheckParticleList(), G4RPGInelastic::CheckQnums(), G4HadronicProcess::CheckResult(), G4VParticleChange::CheckSecondary(), G4EicDircStackingAction::ClassifyNewTrack(), F04StackingAction::ClassifyNewTrack(), CCalStackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), G4LightTargetCollider::collide(), G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4RadioactiveDecayBase::CollimateDecayProduct(), G4RadioactiveDecay::CollimateDecayProduct(), G4ParticleHPInelasticCompFS::CompositeApply(), G4EmCalculator::ComputeCrossSectionPerAtom(), G4EmCalculator::ComputeCrossSectionPerShell(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4EmCalculator::ComputeDEDX(), G4PenelopeIonisationModel::ComputeDEDXPerVolume(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4EmCalculator::ComputeMeanFreePath(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4EmCalculator::ComputeNuclearDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4AdjointCSManager::ComputeTotalAdjointCS(), G4ITModelProcessor::ComputeTrackReaction(), G4WentzelOKandVIxSection::ComputeTransportCrossSectionPerAtom(), G4TablesForExtrapolator::ComputeTrasportXS(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), LBE::ConstructGeneral(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4MuonicAtomHelper::ConstructMuonicAtom(), DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), ExUCNExtraPhysics::ConstructProcess(), PhysListEmStandard::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), G4UnknownDecayPhysics::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4NeutronTrackingCut::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4DecayPhysics::ConstructProcess(), TSPhysicsList::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructUCN(), G4VRangeToEnergyConverter::Convert(), G4VRangeToEnergyConverter::ConvertCutToKineticEnergy(), G4ProductionCutsTable::ConvertRangeToEnergy(), G4LossTableManager::CopyTables(), G4CascadeInterface::createBullet(), CCaloSD::createNewHit(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4DNADingfelderChargeDecreaseModel::CrossSectionPerVolume(), G4DNADingfelderChargeIncreaseModel::CrossSectionPerVolume(), G4DNABornExcitationModel1::CrossSectionPerVolume(), G4DNABornExcitationModel2::CrossSectionPerVolume(), G4DNAMillerGreenExcitationModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNABornIonisationModel2::CrossSectionPerVolume(), G4DNAIonElasticModel::CrossSectionPerVolume(), G4MicroElecElasticModel::CrossSectionPerVolume(), G4MuElecElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNACPA100ElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4MicroElecInelasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), G4DNAModelInterface::CrossSectionPerVolume(), G4DNAPTBExcitationModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), G4DNAPTBElasticModel::CrossSectionPerVolume(), G4DNAPTBIonisationModel::CrossSectionPerVolume(), G4BinaryCascade::DebugApplyCollisionFail(), G4KineticTrack::Decay(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4ContinuousGainOfEnergy::DefineMaterial(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4QGSParticipants::DeterminePartonMomenta(), G4DNAPTBIonisationModel::DifferentialCrossSection(), G4GlobalFastSimulationManager::DisplayRegion(), G4RadioactiveDecayBase::DoDecay(), G4RadioactiveDecay::DoDecay(), G4EmElementSelector::Dump(), G4HadronicProcessStore::Dump(), G4CrossSectionDataStore::DumpFastPath(), G4DecayTable::DumpInfo(), G4ParticleHPChannelList::DumpInfo(), G4ProcessTable::DumpInfo(), G4ProcessManager::DumpInfo(), G4LENDModel::DumpLENDTargetInfo(), G4LENDCrossSection::DumpLENDTargetInfo(), G4VUserPhysicsList::DumpList(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4IonTable::DumpTable(), G4ExceptionHandler::DumpTrackInfo(), G4EmCorrections::EffectiveChargeCorrection(), Run::EndOfRun(), HistoManager::EndOfRun(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), G4ConcreteNNTwoBodyResonance::establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), export_G4ParticleDefinition(), F04Trajectory::F04Trajectory(), G4ElasticHadrNucleusHE::FillData(), G4VDecayChannel::FillDaughters(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4QGSParticipants::FinalizeKinematics(), G4VScatteringCollision::FinalState(), G4ParticleInelasticXS::FindDirectoryPath(), G4EmCalculator::FindEmModel(), G4EmCalculator::FindEnergyLossProcess(), G4VHadronPhysics::FindInelasticProcess(), G4VEmProcess::FindLambdaMax(), G4BinaryCascade::FindLateParticleCollision(), G4ProcessTable::FindProcess(), F01RunAction::findTransportation(), G4QGSMFragmentation::FragmentString(), G4ExcitedStringDecay::FragmentStrings(), G4CascadParticle::G4CascadParticle(), G4ConcreteNNToDeltaDeltastar::G4ConcreteNNToDeltaDeltastar(), G4ConcreteNNToDeltaNstar::G4ConcreteNNToDeltaNstar(), G4ConcreteNNToNDeltaStar::G4ConcreteNNToNDeltaStar(), G4ConcreteNNToNNStar::G4ConcreteNNToNNStar(), G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance(), G4ConcreteNStarNToNN::G4ConcreteNStarNToNN(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4Fragment::G4Fragment(), G4FissionProductYieldDist::G4GetFission(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleHPInelastic::G4ParticleHPInelastic(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4ParticleInelasticXS::G4ParticleInelasticXS(), G4PartonPair::G4PartonPair(), G4RunManagerKernel::G4RunManagerKernel(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4XAnnihilationChannel::G4XAnnihilationChannel(), G4XResonance::G4XResonance(), G4HtmlPPReporter::GenerateIndex(), STCyclotronPrimaryGeneratorAction::GeneratePrimaries(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), WLSPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), UltraPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4ElementaryParticleCollider::generateSCMmuonAbsorption(), G4ElementaryParticleCollider::generateSCMpionAbsorption(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4PrimaryTransformer::GenerateSingleTrack(), PHG4ParticleGeneratorBase::get_pdgname(), G4AdjointCSManager::GetAdjointParticleEquivalent(), G4ProcessManager::GetAttribute(), G4Radioactivation::GetChainsFromParent(), G4RadioactiveDecay::GetChainsFromParent(), G4CrossSectionDataStore::GetCrossSection(), G4EmCalculator::GetCrossSectionPerVolume(), G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4EmCalculator::GetCSDARange(), G4ParticleGunMessenger::GetCurrentValue(), G4UserPhysicsListMessenger::GetCurrentValue(), G4ParticleMessenger::GetCurrentValue(), G4RadioactiveDecayBase::GetDecayTable(), G4RadioactiveDecay::GetDecayTable(), G4Radioactivation::GetDecayTable1(), G4EmCalculator::GetDEDX(), G4NeutrinoElectronNcXsc::GetElementCrossSection(), G4PiNuclearCrossSection::GetElementCrossSection(), G4NeutrinoElectronCcXsc::GetElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4ParticleInelasticXS::GetElementCrossSection(), G4BGGNucleonElasticXS::GetElementCrossSection(), G4BGGNucleonInelasticXS::GetElementCrossSection(), G4BGGPionElasticXS::GetElementCrossSection(), G4BGGPionInelasticXS::GetElementCrossSection(), G4VCrossSectionDataSet::GetElementCrossSection(), G4RPGReaction::GetFinalStateNucleons(), G4AdjointCSManager::GetForwardParticleEquivalent(), G4ProductionCuts::GetIndex(), G4MuNeutrinoNucleusTotXsc::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), G4CrossSectionDataStore::GetIsoCrossSection(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4EmCalculator::GetKinEnergy(), G4LENDManager::GetLENDTarget(), G4QGSParticipants::GetList(), G4SynchrotronRadiation::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4EmCalculator::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4EmModelManager::GetModel(), G4MoleculeDefinition::GetName(), G4DNABornIonisationModel1::GetPartialCrossSection(), G4VMscModel::GetParticleChangeForMSC(), G4ParticleTable::GetParticleName(), G4ParticlePropertyTable::GetParticleProperty(), G4VProcess::GetPhysicsTableFileName(), F01PrimaryGeneratorAction::GetPrimaryName(), F02PrimaryGeneratorAction::GetPrimaryName(), F03PrimaryGeneratorAction::GetPrimaryName(), G4ProcessPlacer::GetProcessManager(), G4SteppingManager::GetProcessNumber(), G4ProcessManager::GetProcessVectorIndex(), PhysicsList::GetRange(), G4EmCalculator::GetRangeFromRestricteDEDX(), G4Scintillation::GetScintillationYieldByParticleType(), G4UAtomicDeexcitation::GetShellIonisationCrossSectionPerAtom(), CCaloSD::getStepInfo(), G4Pythia6Decayer::ImportDecayProducts(), G4ProcessManager::InActivateProcess(), G4FTFModel::Init(), G4ParticleHPIsoData::Init(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADummyModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNABornIonisationModel1::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4DNATransformElectronModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4DNAVacuumModel::Initialise(), G4PAIPhotModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4EmBiasingManager::Initialise(), G4DNAPTBExcitationModel::Initialise(), G4DNAPTBElasticModel::Initialise(), G4PAIModel::Initialise(), G4BraggIonModel::Initialise(), G4DNAPTBIonisationModel::Initialise(), G4ICRU73QOModel::Initialise(), G4UrbanAdjointMscModel::Initialise(), G4BraggModel::Initialise(), G4TDNAOneStepThermalizationModel< MODEL >::Initialise(), G4EmModelManager::Initialise(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4DNAChargeIncrease::InitialiseProcess(), G4DNAAttachment::InitialiseProcess(), G4DNAElastic::InitialiseProcess(), G4DNAChargeDecrease::InitialiseProcess(), G4DNAExcitation::InitialiseProcess(), G4DNAIonisation::InitialiseProcess(), G4DNAVibExcitation::InitialiseProcess(), G4MuElecInelastic::InitialiseProcess(), G4MicroElecInelastic::InitialiseProcess(), G4CoulombScattering::InitialiseProcess(), G4VUserPhysicsList::InitializeProcessManager(), PHG4Reco::InitRun(), G4DecayTable::Insert(), G4ProcessTable::Insert(), G4ParticleTable::Insert(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4IonTable::IsAntiIon(), G4NeutrinoElectronNcModel::IsApplicable(), G4NeutrinoElectronCcModel::IsApplicable(), G4NeutronElectronElModel::IsApplicable(), G4NuMuNucleusCcModel::IsApplicable(), G4NuMuNucleusNcModel::IsApplicable(), G4NeutrinoNucleusModel::IsApplicable(), G4DNAMolecularDissociation::IsApplicable(), G4UnknownDecay::IsApplicable(), G4NeutronKiller::IsApplicable(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), G4Cerenkov::IsApplicable(), G4ParallelWorldScoringProcess::IsAtRestRequired(), G4ParallelWorldProcess::IsAtRestRequired(), G4NeutrinoElectronNcXsc::IsElementApplicable(), G4NeutrinoElectronCcXsc::IsElementApplicable(), G4NeutronElectronElXsc::IsElementApplicable(), G4IonTable::IsIon(), G4MuNeutrinoNucleusTotXsc::IsIsoApplicable(), G4LENDManager::IsLENDTargetAvailable(), G4IonTable::IsLightAntiIon(), G4IonTable::IsLightIon(), G4ParticleInelasticXS::IsoCrossSection(), G4Radioactivation::IsRateTableReady(), G4RadioactiveDecay::IsRateTableReady(), G4GeneralParticleSource::ListSource(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4LossTableManager::LocalPhysicsTables(), G4LundStringFragmentation::Loop_toFragmentString(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4HadronBuilder::Meson(), G4TextPPRetriever::ModifyPropertyTable(), G4VShortLivedParticle::operator!=(), operator<<(), G4VShortLivedParticle::operator==(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), G4LossTableManager::ParticleHaveNoLoss(), G4VLongitudinalStringDecay::PossibleHadronMass(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4AdjointTrackingAction::PostUserTrackingAction(), G4EmConfigurator::PrepareModels(), G4LossTableManager::PreparePhysicsTable(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VUserPhysicsList::PreparePhysicsTable(), RE01TrackInformation::Print(), G4PrimaryParticle::Print(), CCalPrimaryGeneratorAction::print(), G4InuclNuclei::print(), G4HadronicProcessStore::Print(), G3PartTable::PrintAll(), G4EmCalculator::PrintDEDXTable(), G4CascadeHistory::PrintEntry(), G4HadronicProcessStore::PrintHtml(), G4EmCalculator::PrintInverseRangeTable(), RE01EventAction::PrintPrimary(), G4EmCalculator::PrintRangeTable(), CexmcEventAction::PrintTrackPoints(), G4ComponentSAIDTotalXS::PrintWarning(), STCyclotronSensitiveTarget::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), DMXScintSD::ProcessHits(), G4IntraNucleiCascader::processSecondary(), G4BinaryCascade::ProductsAddFinalState(), G4GeneratorPrecompoundInterface::Propagate(), G4CascadeInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4StackManager::PushOneTrack(), G4QGSParticipants::PutOnMassShell(), G4DNAPTBIonisationModel::RandomizeEjectedElectronEnergyFromCumulated(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), G4QGSParticipants::ReggeonCascade(), G4AdjointCSManager::RegisterAdjointParticle(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4AdjointCSManager::RegisterEmProcess(), G4AdjointCSManager::RegisterEnergyLossProcess(), G4LossTableManager::RegisterExtraParticle(), G4HadronicProcessStore::RegisterParticle(), G4PhysicsListHelper::RegisterProcess(), G4IntraNucleiCascader::releaseSecondary(), G4ProcessTable::Remove(), G4ParticleTable::Remove(), G4IonTable::Remove(), G4ProcessManager::RemoveProcess(), G4VUserPhysicsList::RemoveProcessManager(), G4TransportationLogger::ReportLoopingTrack(), G4EmDataHandler::RetrievePhysicsTable(), G4GammaGeneralProcess::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrievePhysicsTable(), G4VUserPhysicsList::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrieveTable(), G4MuPairProductionModel::RetrieveTables(), Run::Run(), G4ParticleHPProduct::Sample(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4NeutrinoElectronNcModel::SampleElectronTkin(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4ElasticHadrNucleusHE::SampleInvariantT(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNAEmfietzoglouExcitationModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4DNAModelInterface::SampleSecondaries(), G4DNAPTBExcitationModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4Scatterer::Scatter(), G4QuasiElasticChannel::Scatter(), G4VPartonStringModel::Scatter(), Run::ScoreNewTrack(), G4DecayTable::SelectADecayChannel(), G4MoleculeDefinition::Serialize(), G4VEmAdjointModel::SetAdjointEquivalentOfDirectPrimaryParticleDefinition(), G4VEmProcess::SetCrossSectionBiasingFactor(), G4DecayTableMessenger::SetCurrentParticle(), G4ParticlePropertyMessenger::SetCurrentParticle(), G4VDecayChannel::SetDaughter(), G4PrimaryTransformer::SetDecayProducts(), G4DynamicParticle::SetDefinition(), G4AtimaEnergyLossModel::SetGenericIon(), G4BetheBlochModel::SetGenericIon(), G4VEnergyLossProcess::SetInverseRangeTable(), G4VEnergyLossProcess::SetLambdaTable(), G4BetheHeitler5DModel::SetLeptonPair(), G4EmConfigurator::SetModelForRegion(), G4ParticleMessenger::SetNewValue(), OpNovicePrimaryGeneratorAction::SetOptPhotonPolar(), PrimaryGeneratorAction::SetOptPhotonPolar(), WLSPrimaryGeneratorAction::SetOptPhotonPolar(), G4VDecayChannel::SetParent(), G4UrbanAdjointMscModel::SetParticle(), G4VUserPhysicsList::SetParticleCuts(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentum(), G4RunManagerKernel::SetPhysics(), G4ProcessTable::SetProcessActivation(), G4ParallelGeometriesLimiterProcess::SetProcessManager(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToFirst(), G4ProcessManager::SetProcessOrderingToLast(), G4ProcessManager::SetProcessOrderingToSecond(), G4VEnergyLossProcess::SetRangeTableForLoss(), G4VEnergyLossProcess::SetSecondaryRangeTable(), G4VEnergyLossProcess::SetSubLambdaTable(), G4ITStepProcessor::SetupGeneralProcessInfo(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4GlobalFastSimulationManager::ShowSetup(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4QGSMFragmentation::SplitLast(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::Splitup(), G4LundStringFragmentation::Splitup(), GB05BOptrSplitAndKillByCrossSection::StartRun(), F04SteppingVerbose::StepInfo(), G4BinaryCascade::StepParticlesOut(), G4EmDataHandler::StorePhysicsTable(), G4VMultipleScattering::StorePhysicsTable(), G4VEmProcess::StorePhysicsTable(), G4VEnergyLossProcess::StorePhysicsTable(), G4VUserPhysicsList::StorePhysicsTable(), G4MuPairProductionModel::StoreTables(), G4VEnergyLossProcess::StreamInfo(), G4VMultipleScattering::StreamInfo(), G4VEmProcess::StreamInfo(), G4DNAPTBElasticModel::Theta(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4ITTrackingInteractivity::TrackBanner(), G4VITSteppingVerbose::TrackBanner(), G4TrackingManager::TrackBanner(), G4ITSteppingVerbose::TrackingEnded(), F04SteppingVerbose::TrackingStarted(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), G4AdjointPrimaryGeneratorAction::UpdateListOfPrimaryParticles(), PHG4IonGun::UpdateParticle(), G4EmCalculator::UpdateParticle(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), WLSTrajectory::WLSTrajectory(), G4FastPathHadronicCrossSection::fastPathEntry::~fastPathEntry(), and ~G4ParticleDefinition().
const G4String& G4ParticleDefinition::GetParticleSubType () const inline
Definition at line 142 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ParticleDefinition.hh
References theParticleSubType.
Referenced by G4HadronBuilder::Build(), G4HadronBuilder::BuildHighSpin(), G4HadronBuilder::BuildLowSpin(), G4hImpactIonisation::BuildPhysicsTable(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4DiffractiveExcitation::CreateStrings(), G4FragmentingString::DecayIsQuark(), export_G4ParticleDefinition(), G4CollisionNNElastic::G4CollisionNNElastic(), G4CollisionnpElastic::G4CollisionnpElastic(), G4MoleculeDefinition::GetType(), G4FragmentingString::IsAFourQuarkString(), G4VEmProcess::PreparePhysicsTable(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4VUserPhysicsList::RemoveProcessManager(), G4RPGReaction::Rotate(), G4LundStringFragmentation::SplitLast(), G4QGSMFragmentation::Splitup(), G4LundStringFragmentation::Splitup(), and G4FragmentingString::StableIsQuark().
G4ParticleTable* G4ParticleDefinition::GetParticleTable () const
Referenced by export_G4ParticleDefinition().
const G4String& G4ParticleDefinition::GetParticleType () const inline
Definition at line 141 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ParticleDefinition.hh
References theParticleType.
Referenced by G4PhysicsListHelper::AddTransportation(), G4QMDReaction::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4LowECapture::BuildPhysicsTable(), G4hImpactIonisation::BuildPhysicsTable(), G4QMDReaction::calcOffSetOfCollision(), G4PhysicsListHelper::CheckParticleList(), G4AdjointStackingAction::ClassifyNewTrack(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), LBE::ConstructGeneral(), G4DiffractiveExcitation::CreateStrings(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), RE01Trajectory::DrawTrajectory(), export_G4ParticleDefinition(), G4VDecayChannel::FillDaughters(), G4VParticlePropertyReporter::FillList(), G4EmCalculator::FindEmModel(), G4EmCalculator::FindEnergyLossProcess(), G4HadronicProcessStore::FindProcess(), G4Parton::G4Parton(), G4PartonPair::G4PartonPair(), G4HtmlPPReporter::GeneratePropertyTable(), G4Scintillation::GetScintillationYieldByParticleType(), G4BraggIonModel::Initialise(), G4BraggModel::Initialise(), G4CoulombScattering::InitialiseProcess(), G4IonTable::IsAntiIon(), G4MuonicAtomDecay::IsApplicable(), G4MuElecInelastic::IsApplicable(), G4DNAMolecularDissociation::IsApplicable(), G4RadioactiveDecayBase::IsApplicable(), G4ionIonisation::IsApplicable(), G4RadioactiveDecay::IsApplicable(), G4ScreenedNuclearRecoil::IsApplicable(), G4IonTable::IsIon(), G4XAnnihilationChannel::NormalizedClebsch(), G4AdjointTrackingAction::PostUserTrackingAction(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4AdjointTrackingAction::PreUserTrackingAction(), STCyclotronSensitiveTarget::ProcessHits(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4MoleculeDefinition::Serialize(), G4ContinuousGainOfEnergy::SetDirectParticle(), G4ParticleMessenger::SetNewValue(), G4INCLXXInterface::toINCLParticleType(), G4EmCalculator::UpdateParticle(), and G4AdjointSteppingAction::UserSteppingAction().
G4double G4ParticleDefinition::GetPDGCharge () const inline
Definition at line 124 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ParticleDefinition.hh
References thePDGCharge.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles(), ExN02PhysicsList::AddStepMax(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4NuclearStopping::AlongStepDoIt(), G4BinaryCascade::ApplyCollision(), G4BinaryLightIonReaction::ApplyYourself(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LFission::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4GenericBiasingPhysics::AssociateParallelGeometries(), G4HadronBuilder::Barion(), G4ParticleHPInelasticBaseFS::BaseApply(), RunAction::BeginOfRunAction(), SteppingAction::BirksAttenuation(), G4WilsonAblationModel::BreakItUp(), G4DiffuseElasticV2::BuildAngleTable(), G4DiffuseElastic::BuildAngleTable(), G4ErrorTrajState::BuildCharge(), G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4QGSParticipants::BuildInteractions(), G4hImpactIonisation::BuildLambdaTable(), G4BinaryCascade::BuildLateParticleCollisions(), G4hImpactIonisation::BuildPhysicsTable(), G4VXTRenergyLoss::BuildPhysicsTable(), G4BinaryCascade::BuildTargetList(), G4QMDReaction::calcOffSetOfCollision(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4PhysicsListHelper::CheckParticleList(), G4RPGInelastic::CheckQnums(), StackingAction::ClassifyNewTrack(), ExN04StackingAction::ClassifyNewTrack(), RE05StackingAction::ClassifyNewTrack(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ComponentGGNuclNuclXsc::ComputeCoulombBarier(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4hImpactIonisation::ComputeDEDX(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), RunAction::ComputeMscHighland(), Run::ComputeMscHighland(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), eRositaPhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4ChannelingPhysics::ConstructProcess(), PhysListEmStandard::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), TSPhysicsList::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4AtimaEnergyLossModel::CorrectionsAlongStep(), G4HadronNucleonXsc::CoulombBarrier(), G4NuclearRadii::CoulombFactor(), G4KineticTrack::Decay(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4AtimaFluctuations::Dispersion(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4ionEffectiveCharge::EffectiveCharge(), G4EmCorrections::EffectiveChargeCorrection(), export_G4ParticleDefinition(), F04Trajectory::F04Trajectory(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), G4VScatteringCollision::FinalState(), G4Absorber::FindAbsorbers(), G4MesonAbsorption::FindAndFillCluster(), G4Absorber::FindProducts(), G4AdjointIons::G4AdjointIons(), G4ConcreteNNToDeltaDeltastar::G4ConcreteNNToDeltaDeltastar(), G4DNAIons::G4DNAIons(), G4Ions::G4Ions(), G4ParticleDefinition(), G4PrimaryParticle::G4PrimaryParticle(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), STCyclotronPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4QMDParticipant::GetChargeInUnitOfEplus(), G4VEmModel::GetChargeSquareRatio(), G4NuclNuclDiffuseElastic::GetCoulombElasticXsc(), G4DiffuseElastic::GetCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetCoulombIntegralXsc(), G4DiffuseElastic::GetCoulombIntegralXsc(), G4NuclNuclDiffuseElastic::GetCoulombTotalXsc(), G4DiffuseElastic::GetCoulombTotalXsc(), G4EnergyLossTables::GetDEDX(), G4VMscModel::GetDEDX(), G4NuclNuclDiffuseElastic::GetDiffuseElasticSumXsc(), G4DiffuseElastic::GetDiffuseElasticSumXsc(), G4PiNuclearCrossSection::GetElementCrossSection(), G4TripathiCrossSection::GetElementCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4EMDissociationCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4GeneralSpaceNNCrossSection::GetElementCrossSection(), G4VMscModel::GetEnergy(), G4MesonAbsorption::GetFinalState(), G4IonsShenCrossSection::GetIsoCrossSection(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4VEmModel::GetParticleCharge(), G4ParticlePropertyTable::GetParticleProperty(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4EnergyLossTables::GetPreciseDEDX(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4EnergyLossTables::GetPreciseRangeFromEnergy(), G4EnergyLossTables::GetRange(), G4VMscModel::GetRange(), G4UAtomicDeexcitation::GetShellIonisationCrossSectionPerAtom(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4HadronNucleonXsc::HadronNucleonXscPDG(), G4FTFModel::Init(), G4NuclNuclDiffuseElastic::InitDynParameters(), G4FTFParameters::InitForInteraction(), G4ErrorPropagator::InitG4Track(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4GoudsmitSaundersonMscModel::Initialise(), G4hhIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4BohrFluctuations::InitialiseMe(), G4UniversalFluctuation::InitialiseMe(), G4AtimaFluctuations::InitialiseMe(), G4IonFluctuations::InitialiseMe(), G4NuclNuclDiffuseElastic::InitParameters(), G4NuclNuclDiffuseElastic::InitParametersGla(), G4EmCorrections::IonHighOrderCorrections(), HadrontherapyStepMax::IsApplicable(), G4Channeling::IsApplicable(), StepMax::IsApplicable(), XrayFluoStepMax::IsApplicable(), F04StepMax::IsApplicable(), StepMaxProcess::IsApplicable(), StepLimiter::IsApplicable(), G4LDMBremsstrahlung::IsApplicable(), IORTStepMax::IsApplicable(), G4ErrorEnergyLoss::IsApplicable(), ML2StepMax::IsApplicable(), G4CoulombScattering::IsApplicable(), G4VTransitionRadiation::IsApplicable(), G4alphaIonisation::IsApplicable(), G4TransitionRadiation::IsApplicable(), G4hPairProduction::IsApplicable(), G4MuElecInelastic::IsApplicable(), G4eMultipleScattering::IsApplicable(), G4hhIonisation::IsApplicable(), G4hBremsstrahlung::IsApplicable(), G4MuMultipleScattering::IsApplicable(), G4HadronStoppingProcess::IsApplicable(), G4hMultipleScattering::IsApplicable(), G4eAdjointMultipleScattering::IsApplicable(), Par02FastSimModelTracker::IsApplicable(), G4NuclearStopping::IsApplicable(), G4MuPairProduction::IsApplicable(), G4AdjointhMultipleScattering::IsApplicable(), G4ionIonisation::IsApplicable(), G4hImpactIonisation::IsApplicable(), G4MuBremsstrahlung::IsApplicable(), G4VXTRenergyLoss::IsApplicable(), G4SynchrotronRadiation::IsApplicable(), G4hIonisation::IsApplicable(), G4MuIonisation::IsApplicable(), G4Cerenkov::IsApplicable(), G4Scintillation::IsApplicable(), G4TripathiLightCrossSection::IsElementApplicable(), G4HadronNucleonXsc::KaonNucleonXscVG(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4HadronBuilder::Meson(), G4Monopole::MonopoleDefinition(), G4CollisionComposite::Resolve::operator()(), G4DNAMillerGreenExcitationModel::PartialCrossSection(), G4SynchrotronRadiation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4EmConfigurator::PrepareModels(), G4VEnergyLossProcess::PreparePhysicsTable(), B5DriftChamberSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), G4EnergyLossTables::Register(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4ParticleHPContAngularPar::Sample(), G4AntiNuclElastic::SampleInvariantT(), G4Scatterer::Scatter(), G4QuasiElasticChannel::Scatter(), G4VPartonStringModel::Scatter(), G4WilsonAblationModel::SelectSecondariesByDefault(), G4DynamicParticle::SetDefinition(), G4ContinuousGainOfEnergy::SetDirectParticle(), G4hImpactIonisation::SetElectronicStoppingPowerModel(), G4EmConfigurator::SetModelForRegion(), G4UrbanMscModel::SetParticle(), G4UrbanAdjointMscModel::SetParticle(), G4PAIPhotModel::SetParticle(), G4ICRU73QOModel::SetParticle(), G4PAIModel::SetParticle(), G4AtimaEnergyLossModel::SetParticle(), G4BraggModel::SetParticle(), G4BetheBlochModel::SetParticle(), G4BraggIonModel::SetParticle(), G4GoudsmitSaundersonMscModel::SetParticle(), G4AtimaFluctuations::SetParticleAndCharge(), G4IonFluctuations::SetParticleAndCharge(), G4ParticleGun::SetParticleDefinition(), DMXParticleSource::SetParticleDefinition(), G4PrimaryParticle::SetParticleDefinition(), G4SingleParticleSource::SetParticleDefinition(), G4PrimaryParticle::SetPDGcode(), G4EnergyLossForExtrapolator::SetupKinematics(), G4EmCorrections::SetupKinematics(), G4AtimaEnergyLossModel::SetupParameters(), G4LindhardSorensenIonModel::SetupParameters(), G4BetheBlochModel::SetupParameters(), G4WentzelOKandVIxSection::SetupParticle(), G4IonCoulombCrossSection::SetupParticle(), G4DecayWithSpin::Spin_Precession(), G4EnergySplitter::SplitEnergyInVolumes(), G4NuclNuclDiffuseElastic::TestAngleTable(), G4DiffuseElastic::TestAngleTable(), G4IonYangFluctuationModel::TheValue(), G4hIonEffChargeSquare::TheValue(), G4hNuclearStoppingModel::TheValue(), G4QAOLowEnergyLoss::TheValue(), G4ParticleHPInelasticCompFS::two_body_reaction(), G4Channeling::UpdateParameters(), G4EmCalculator::UpdateParticle(), PHG4ZDCSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), G4EmSaturation::VisibleEnergyDeposition(), and WLSTrajectory::WLSTrajectory().
G4int G4ParticleDefinition::GetPDGEncoding () const inline
Definition at line 146 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ParticleDefinition.hh
References thePDGEncoding.
Referenced by G4ITStepProcessor::ActiveOnlyITProcess(), G4BiasingHelper::AddLimiterProcess(), PHG4TruthTrackingAction::AddParticle(), G4CoupledTransportation::AlongStepDoIt(), G4FTFAnnihilation::Annihilate(), G4ChargeExchange::ApplyYourself(), G4GenericBiasingPhysics::AssociateParallelGeometries(), G4HadronBuilder::Barion(), G4QGSParticipants::BuildInteractions(), G4ChargeExchangeProcess::BuildPhysicsTable(), G4RPGInelastic::CalculateMomenta(), G4BinaryCascade::Capture(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4BinaryCascade::CheckPauliPrinciple(), G4HadronicProcess::CheckResult(), G4GenericBiasingPhysics::ConstructProcess(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4DiffractiveExcitation::CreateStrings(), G4XPDGTotal::CrossSection(), G4BinaryCascade::DebugApplyCollision(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), export_G4ParticleDefinition(), F04Trajectory::F04Trajectory(), G4RKPropagation::FieldTransport(), G4HadronicProcess::FillResult(), G4ParticleTable::FindParticle(), F01RunAction::findTransportation(), G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral(), G4Fragment::G4Fragment(), G4FissionProductYieldDist::G4GetFission(), G4PrimaryParticle::G4PrimaryParticle(), G4ReactionProduct::G4ReactionProduct(), G4Reggeons::G4Reggeons(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), CML2PrimaryGenerationAction::GeneratePrimaries(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4PrimaryTransformer::GenerateSingleTrack(), PHG4ParticleGeneratorBase::get_pdgcode(), G4ChipsComponentXS::GetElasticElementCrossSection(), G4QuasiElasticChannel::GetFraction(), G4ChipsComponentXS::GetInelasticElementCrossSection(), G4ChipsAntiBaryonInelasticXS::GetIsoCrossSection(), G4ChipsHyperonInelasticXS::GetIsoCrossSection(), G4ChipsHyperonElasticXS::GetIsoCrossSection(), G4ChipsAntiBaryonElasticXS::GetIsoCrossSection(), G4LundStringFragmentation::GetLightConeZ(), G4FTFParameters::GetMinMass(), G4ParticlePropertyTable::GetParticleProperty(), G4SteppingManager::GetProcessNumber(), G4ChipsComponentXS::GetTotalElementCrossSection(), G4ComponentSAIDTotalXS::GetType(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), G4HadronNucleonXsc::HadronNucleonXsc(), G4HadronNucleonXsc::HadronNucleonXscVU(), G4Pythia6Decayer::ImportDecayProducts(), G4RKPropagation::Init(), G4FTFParameters::InitForInteraction(), G4BetheHeitler5DModel::Initialise(), G4VMscModel::InitialiseParameters(), G4ParticleTable::Insert(), G4EmCorrections::IonHighOrderCorrections(), G4ParallelWorldScoringProcess::IsAtRestRequired(), G4ParallelWorldProcess::IsAtRestRequired(), G4HadronBuilder::Meson(), G4XAnnihilationChannel::NormalizedClebsch(), G4ReactionProduct::operator=(), G4NuclearRadii::ParticleRadius(), G4VLongitudinalStringDecay::PossibleHadronMass(), MCTruthTrackingAction::PostUserTrackingAction(), G4AdjointTrackingAction::PostUserTrackingAction(), G4CollisionManager::Print(), G4CollisionInitialState::Print(), G4BinaryCascade::PrintKTVector(), ScreenSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4VLongitudinalStringDecay::QuarkSplitup(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4ParticleTable::Remove(), RMC01AnalysisManager::RMC01AnalysisManager(), G4ChipsElasticModel::SampleInvariantT(), G4HadronElastic::SampleInvariantT(), G4ElasticHadrNucleusHE::SampleInvariantT(), G4SPBaryon::SampleQuarkAndDiquark(), G4QuasiElasticChannel::Scatter(), G4Parton::SetDefinition(), G4ReactionProduct::SetDefinition(), G4BetheHeitler5DModel::SetLeptonPair(), G4VLongitudinalStringDecay::SetMinimalStringMass(), G4PrimaryParticle::SetParticleDefinition(), RMC01AnalysisManager::SetPrimaryExpSpectrumForAdjointSim(), RMC01AnalysisManager::SetPrimaryPowerLawSpectrumForAdjointSim(), G4ITStepProcessor::SetupGeneralProcessInfo(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4LundStringFragmentation::SplitLast(), G4DiffractiveSplitableHadron::SplitUp(), G4QGSMFragmentation::Splitup(), G4LundStringFragmentation::Splitup(), MCTruthTrackingAction::TrackToBeStored(), G4RKPropagation::Transport(), PHG4IonGun::UpdateParticle(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), G4EmSaturation::VisibleEnergyDeposition(), WLSTrajectory::WLSTrajectory(), and G4ParticleTable::WorkerG4ParticleTable().
G4int G4ParticleDefinition::GetPDGiConjugation () const inline
Definition at line 129 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ParticleDefinition.hh
References thePDGiConjugation.
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), export_G4ParticleDefinition(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), and G4ParticlePropertyTable::GetParticleProperty().
G4int G4ParticleDefinition::GetPDGiGParity () const inline
Definition at line 134 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ParticleDefinition.hh
References thePDGiGParity.
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), export_G4ParticleDefinition(), and G4ParticlePropertyTable::GetParticleProperty().
G4int G4ParticleDefinition::GetPDGiIsospin () const inline
Definition at line 132 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleDefinition.hh
References thePDGiIsospin.
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), G4VXResonance::DetailedBalance(), G4ConcreteNNTwoBodyResonance::establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), export_G4ParticleDefinition(), G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance(), G4Parton::G4Parton(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4ParticlePropertyTable::GetParticleProperty(), G4VXResonance::IsospinCorrection(), and G4XAnnihilationChannel::NormalizedClebsch().
G4int G4ParticleDefinition::GetPDGiIsospin3 () const inline
Definition at line 133 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ParticleDefinition.hh
References thePDGiIsospin3.
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), G4VXResonance::DetailedBalance(), export_G4ParticleDefinition(), G4ConcreteMesonBaryonToResonance::GetOutgoingParticle(), G4ParticlePropertyTable::GetParticleProperty(), G4VXResonance::IsospinCorrection(), and G4XAnnihilationChannel::NormalizedClebsch().
G4int G4ParticleDefinition::GetPDGiParity () const inline
Definition at line 128 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleDefinition.hh
References thePDGiParity.
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), export_G4ParticleDefinition(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4VDecayChannel::GetAngularMomentum(), and G4ParticlePropertyTable::GetParticleProperty().
G4double G4ParticleDefinition::GetPDGIsospin () const inline
Definition at line 130 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ParticleDefinition.hh
References thePDGIsospin.
Referenced by export_G4ParticleDefinition().
G4double G4ParticleDefinition::GetPDGIsospin3 () const inline
Definition at line 131 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ParticleDefinition.hh
References thePDGIsospin3.
Referenced by export_G4ParticleDefinition(), and G4Parton::G4Parton().
G4int G4ParticleDefinition::GetPDGiSpin () const inline
Definition at line 127 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ParticleDefinition.hh
References thePDGiSpin.
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), G4XAnnihilationChannel::CrossSection(), G4VXResonance::DegeneracyFactor(), G4ConcreteNNTwoBodyResonance::establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), export_G4ParticleDefinition(), G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance(), G4Parton::G4Parton(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4VDecayChannel::GetAngularMomentum(), G4ParticlePropertyTable::GetParticleProperty(), and G4VXResonance::IsospinCorrection().
G4double G4ParticleDefinition::GetPDGLifeTime () const
Referenced by G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4RadioactiveDecayBase::DecayAnalog(), G4RadioactiveDecay::DecayIt(), export_G4ParticleDefinition(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4ParticlePropertyMessenger::GetCurrentValue(), G4MoleculeDefinition::GetDecayTime(), G4IonTable::GetLifeTime(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanLifeTime(), G4Decay::GetMeanLifeTime(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), G4ParticlePropertyTable::GetParticleProperty(), G4RadioactiveDecayBase::IsApplicable(), G4Decay::IsApplicable(), G4RadioactiveDecay::IsApplicable(), G4Decay::PostStepGetPhysicalInteractionLength(), STCyclotronSensitiveTarget::ProcessHits(), G4MoleculeDefinition::Serialize(), and G4ParticlePropertyMessenger::SetNewValue().
G4double G4ParticleDefinition::GetPDGMagneticMoment () const inline
Definition at line 136 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ParticleDefinition.hh
References thePDGMagneticMoment.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), G4HtmlPPReporter::GeneratePropertyTable(), G4ParticlePropertyTable::GetParticleProperty(), G4DynamicParticle::SetDefinition(), G4AtimaEnergyLossModel::SetupParameters(), G4LindhardSorensenIonModel::SetupParameters(), and G4BetheBlochModel::SetupParameters().
G4double G4ParticleDefinition::GetPDGMass () const inline
Definition at line 122 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ParticleDefinition.hh
References thePDGMass.
Referenced by G4EmDNAPhysicsActivator::AddHeliumModels0(), PhysicsList::AddIonGasModels(), PHG4TruthTrackingAction::AddParticle(), G4ParticleHPFinalState::adjust_final_state(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4NuclearStopping::AlongStepDoIt(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), G4FTFAnnihilation::Annihilate(), G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LENDModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4LFission::Atomas(), G4ParticleHPInelasticBaseFS::BaseApply(), G4KineticTrackVector::BoostBeam(), G4ExcitationHandler::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4CollisionComposite::BufferCrossSection(), G4NuclNuclDiffuseElastic::BuildAngleTable(), G4DiffuseElasticV2::BuildAngleTable(), G4DiffuseElastic::BuildAngleTable(), G4EmCorrections::BuildCorrectionVector(), G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4hImpactIonisation::BuildLambdaTable(), G4hImpactIonisation::BuildPhysicsTable(), G4hRDEnergyLoss::BuildRangeTable(), G4hhElastic::BuildTableT(), G4hhElastic::BuildTableTest(), G4BinaryCascade::BuildTargetList(), G4QMDReaction::calcOffSetOfCollision(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4ecpssrFormFactorKxsModel::CalculateCrossSection(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4ElectroVDNuclearModel::CalculateHadronicVertex(), G4MuonVDNuclearModel::CalculateHadronicVertex(), G4PaulKxsModel::CalculateKCrossSection(), G4ecpssrFormFactorLixsModel::CalculateL1CrossSection(), G4ecpssrBaseLixsModel::CalculateL1CrossSection(), G4ecpssrFormFactorLixsModel::CalculateL2CrossSection(), G4ecpssrBaseLixsModel::CalculateL2CrossSection(), G4OrlicLiXsModel::CalculateL2CrossSection(), G4ecpssrFormFactorLixsModel::CalculateL3CrossSection(), G4ecpssrBaseLixsModel::CalculateL3CrossSection(), G4OrlicLiXsModel::CalculateL3CrossSection(), G4ecpssrFormFactorMixsModel::CalculateMiCrossSection(), G4RPGInelastic::CalculateMomenta(), G4AntiNuclElastic::CalculateParticleBeta(), G4NuclNuclDiffuseElastic::CalculateParticleBeta(), G4DiffuseElastic::CalculateParticleBeta(), G4ecpssrBaseLixsModel::CalculateVelocity(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4RPGKMinusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), CexmcChargeExchangeProductionModel< OutputParticle >::CexmcChargeExchangeProductionModel(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4HadronicProcess::CheckResult(), G4QuasiElRatios::ChExer(), G4NeutrinoNucleusModel::ClusterDecay(), G4NeutrinoNucleusModel::CoherentPion(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ComponentGGNuclNuclXsc::ComputeCoulombBarier(), G4AnnihiToMuPair::ComputeCrossSectionPerAtom(), G4ComponentGGNuclNuclXsc::ComputeCrossSections(), G4KokoulinMuonNuclearXS::ComputeDDMicroscopicCrossSection(), G4hImpactIonisation::ComputeDEDX(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4KokoulinMuonNuclearXS::ComputeMicroscopicCrossSection(), G4HadronElastic::ComputeMomentumCMS(), RunAction::ComputeMscHighland(), Run::ComputeMscHighland(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4NIELCalculator::ComputeNIEL(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4BinaryCascade::CorrectBarionsOnBoundary(), G4HadronNucleonXsc::CoulombBarrier(), G4NuclearRadii::CoulombFactor(), G4CollisionNN::CrossSection(), G4XAnnihilationChannel::CrossSection(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4empCrossSection::CrossSection(), G4MicroElecInelasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), G4PionDecayMakeSpin::DaughterPolarization(), G4BinaryCascade::DebugApplyCollision(), G4KineticTrack::Decay(), G4RadioactiveDecayBase::DecayAnalog(), G4AlphaDecay::DecayIt(), G4TritonDecay::DecayIt(), G4ECDecay::DecayIt(), G4NeutronDecay::DecayIt(), G4ProtonDecay::DecayIt(), G4SFDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4ITDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4IntraNucleiCascader::decayTrappedParticle(), G4AdjointCSManager::DefineCurrentParticle(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), G4MuonPlus::Definition(), G4MuonMinus::Definition(), G4TauMinus::Definition(), G4TauPlus::Definition(), G4VXResonance::DetailedBalance(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4AtimaFluctuations::Dispersion(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4RadioactiveDecayBase::DoDecay(), G4RadioactiveDecay::DoDecay(), G4ionEffectiveCharge::EffectiveCharge(), G4EmCorrections::EffectiveChargeCorrection(), CexmcEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), Run::EndOfRun(), HistoManager::EndOfRun(), G4ConcreteNNTwoBodyResonance::establish_G4MT_TLS_G4ConcreteNNTwoBodyResonance(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4SPSEneDistribution::ExpInterpolation(), export_G4ParticleDefinition(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), G4VDecayChannel::FillDaughters(), G4VDecayChannel::FillParent(), Run::FillPerEvent(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4NeutrinoNucleusModel::FinalBarion(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4VElasticCollision::FinalState(), G4VCrossSectionSource::FindLightParticle(), G4Absorber::FindProducts(), G4ExcitedStringDecay::FragmentStrings(), G4AnnihiToMuPair::G4AnnihiToMuPair(), G4BetheHeitler5DModel::G4BetheHeitler5DModel(), G4ChipsKaonMinusElasticXS::G4ChipsKaonMinusElasticXS(), G4ChipsKaonPlusElasticXS::G4ChipsKaonPlusElasticXS(), G4ChipsKaonPlusInelasticXS::G4ChipsKaonPlusInelasticXS(), G4ChipsNeutronElasticXS::G4ChipsNeutronElasticXS(), G4ChipsProtonElasticXS::G4ChipsProtonElasticXS(), G4ConcreteNNTwoBodyResonance::G4ConcreteNNTwoBodyResonance(), G4DynamicParticle::G4DynamicParticle(), G4ee2KChargedModel::G4ee2KChargedModel(), G4ee2KNeutralModel::G4ee2KNeutralModel(), G4eeTo3PiModel::G4eeTo3PiModel(), G4eeToPGammaModel::G4eeToPGammaModel(), G4eeToTwoPiModel::G4eeToTwoPiModel(), G4ElasticData::G4ElasticData(), G4EmCaptureCascade::G4EmCaptureCascade(), G4Fragment::G4Fragment(), G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay(), G4FissionProductYieldDist::G4GetFission(), G4hhElastic::G4hhElastic(), G4IonParametrisedLossModel::G4IonParametrisedLossModel(), G4KineticTrack::G4KineticTrack(), G4LDMBremModel::G4LDMBremModel(), G4LightTargetCollider::G4LightTargetCollider(), G4MuMinusCapturePrecompound::G4MuMinusCapturePrecompound(), G4MuonMinusBoundDecay::G4MuonMinusBoundDecay(), G4MuPairProductionModel::G4MuPairProductionModel(), G4PrimaryParticle::G4PrimaryParticle(), G4ReactionProduct::G4ReactionProduct(), G4RToEConvForElectron::G4RToEConvForElectron(), G4RToEConvForPositron::G4RToEConvForPositron(), G4RToEConvForProton::G4RToEConvForProton(), G4VPreCompoundFragment::G4VPreCompoundFragment(), G4HadDecayGenerator::Generate(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4QMDParticipant::Get4Momentum(), PHG4ParticleGeneratorBase::get_mass(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4Nucleus::GetBiasedThermalNucleus(), G4empCrossSection::GetCrossSection(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ChipsComponentXS::GetElasticElementCrossSection(), G4NeutrinoElectronCcXsc::GetElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4IonProtonCrossSection::GetElementCrossSection(), G4BinaryCascade::GetExcitationEnergy(), G4SigmaPlusField::GetField(), G4KaonZeroField::GetField(), G4SigmaMinusField::GetField(), G4SigmaZeroField::GetField(), G4AntiProtonField::GetField(), G4KaonMinusField::GetField(), G4KaonPlusField::GetField(), G4PionPlusField::GetField(), G4PionZeroField::GetField(), G4PionMinusField::GetField(), G4MesonAbsorption::GetFinalState(), G4NuclNuclDiffuseElastic::GetHadronNucleonXscNS(), G4ChipsComponentXS::GetInelasticElementCrossSection(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4BinaryCascade::GetIonMass(), G4LundStringFragmentation::GetLightConeZ(), G4QMDParticipant::GetMass(), G4Fancy3DNucleus::GetMass(), G4Parton::GetMass(), G4MoleculeDefinition::GetMass(), G4VTransitionRadiation::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4SampleResonance::GetMinimumMass(), G4QMDNucleus::GetNuclearMass(), G4NucleiProperties::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), G4InuclNuclei::getNucleiMass(), G4IonTable::GetNucleusMass(), G4VMscModel::GetParticleChangeForMSC(), G4InuclElementaryParticle::getParticleMass(), G4ParticlePropertyTable::GetParticleProperty(), G4ParticleHPPhotonDist::GetPhotons(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4ChipsHyperonElasticXS::GetQ2max(), G4ChipsProtonElasticXS::GetQ2max(), G4ChipsKaonPlusElasticXS::GetQ2max(), G4ChipsPionPlusElasticXS::GetQ2max(), G4ChipsAntiBaryonElasticXS::GetQ2max(), G4ChipsKaonMinusElasticXS::GetQ2max(), G4ChipsPionMinusElasticXS::GetQ2max(), G4ChipsNeutronElasticXS::GetQ2max(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4UAtomicDeexcitation::GetShellIonisationCrossSectionPerAtom(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4ChipsComponentXS::GetTotalElementCrossSection(), G4HadronNucleonXsc::HadronNucleonXscEL(), G4HadronNucleonXsc::HadronNucleonXscNS(), G4HadronNucleonXsc::HadronNucleonXscPDG(), G4HadronNucleonXsc::HadronNucleonXscVU(), G4RKPropagation::Init(), G4ParticleHPNBodyPhaseSpace::Init(), G4NuclNuclDiffuseElastic::InitDynParameters(), G4FTFParameters::InitForInteraction(), G4BetheBlochModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4BraggIonModel::Initialise(), G4BraggModel::Initialise(), G4eeCrossSections::Initialise(), G4hPairProduction::InitialiseEnergyLossProcess(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4ePairProduction::InitialiseEnergyLossProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4MuPairProduction::InitialiseEnergyLossProcess(), G4ionIonisation::InitialiseEnergyLossProcess(), G4MuIonisation::InitialiseEnergyLossProcess(), G4hIonisation::InitialiseEnergyLossProcess(), G4HadProjectile::InitialiseLocal(), G4BohrFluctuations::InitialiseMe(), G4UniversalFluctuation::InitialiseMe(), G4AtimaFluctuations::InitialiseMe(), G4IonFluctuations::InitialiseMe(), G4ElasticHadrNucleusHE::InitialiseModel(), G4CoulombScattering::InitialiseProcess(), G4INCL::ParticleTable::initialize(), G4QGSMSplitableHadron::InitParameters(), G4NuclNuclDiffuseElastic::InitParameters(), G4NuclNuclDiffuseElastic::InitParametersGla(), G4KineticTrack::IntegrandFunction2(), G4BinaryLightIonReaction::Interact(), G4EmCorrections::IonHighOrderCorrections(), G4LDMBremsstrahlung::IsApplicable(), G4NeutrinoElectronCcModel::IsApplicable(), G4hPairProduction::IsApplicable(), G4hBremsstrahlung::IsApplicable(), G4hhIonisation::IsApplicable(), G4MuPairProduction::IsApplicable(), G4hImpactIonisation::IsApplicable(), G4MuBremsstrahlung::IsApplicable(), G4MuIonisation::IsApplicable(), G4hIonisation::IsApplicable(), G4Decay::IsApplicable(), G4Cerenkov::IsApplicable(), G4NeutrinoElectronCcXsc::IsElementApplicable(), G4HadronNucleonXsc::KaonNucleonXscVG(), G4LDMHiBar::LDMHiBarDefinition(), G4LDMHi::LDMHiDefinition(), G4LDMPhoton::LDMPhotonDefinition(), G4SPSEneDistribution::LinearInterpolation(), G4SPSEneDistribution::LogInterpolation(), G4hBetheBlochModel::LowEnergyLimit(), G4GeneratorPrecompoundInterface::MakeCoalescence(), G4MuonVDNuclearModel::MakeSamplingTable(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4RPGInelastic::MarkLeadingStrangeParticle(), G4NeutrinoNucleusModel::MesonDecay(), G4PixeCrossSectionHandler::MicroscopicCrossSection(), G4ResonanceNames::MinMass(), G4CoulombScattering::MinPrimaryEnergy(), G4mplIonisation::MinPrimaryEnergy(), G4ionIonisation::MinPrimaryEnergy(), G4Monopole::MonopoleDefinition(), G4RPGReaction::NuclearReaction(), G4ReactionProduct::operator=(), G4VLongitudinalStringDecay::PossibleHadronMass(), G4SynchrotronRadiation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4DecayStrongResonances::Propagate(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4DNARuddIonisationExtendedModel::ProposedSampledEnergy(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), G4MuElecInelasticModel::RandomizeEjectedElectronDirection(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4RPGPionSuppression::ReactionStage(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), CexmcChargeExchangeReconstructor::Reconstruct(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4ParticleHPContAngularPar::Sample(), G4hhElastic::SampleBisectionalT(), G4NeutrinoElectronCcModel::SampleCosCMS(), G4DNARuddAngle::SampleDirectionForShell(), G4DNABornAngle::SampleDirectionForShell(), G4AntiNuclElastic::SampleInvariantT(), G4LEpp::SampleInvariantT(), G4LEnp::SampleInvariantT(), G4LEHadronProtonElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4hhElastic::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4ElasticHadrNucleusHE::SampleInvariantT(), G4SampleResonance::SampleMass(), G4LMsdGenerator::SampleMx(), G4VScatteringCollision::SampleResonanceMass(), G4DNADingfelderChargeDecreaseModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4DiffuseElasticV2::SampleTableThetaCMS(), G4NuclNuclDiffuseElastic::SampleTableThetaCMS(), G4DiffuseElastic::SampleTableThetaCMS(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4GammaTransition::SampleTransition(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), G4QuasiElasticChannel::Scatter(), G4QuasiElRatios::Scatter(), HistoManager::ScoreNewTrack(), G4DecayTable::SelectADecayChannel(), G4WilsonAblationModel::SelectSecondariesByDefault(), G4MoleculeDefinition::Serialize(), G4PrimaryParticle::Set4Momentum(), G4DynamicParticle::Set4Momentum(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ContinuousGainOfEnergy::SetDirectParticle(), G4VLongitudinalStringDecay::SetMinMasses(), G4PrimaryParticle::SetMomentum(), G4ParticlePropertyMessenger::SetNewValue(), G4mplIonisationModel::SetParticle(), G4eBremsstrahlungRelModel::SetParticle(), G4mplIonisationWithDeltaModel::SetParticle(), G4MuPairProductionModel::SetParticle(), G4eBremParametrizedModel::SetParticle(), G4UrbanMscModel::SetParticle(), G4UrbanAdjointMscModel::SetParticle(), G4MuBetheBlochModel::SetParticle(), G4PAIPhotModel::SetParticle(), G4MuBremsstrahlungModel::SetParticle(), G4ICRU73QOModel::SetParticle(), G4PAIModel::SetParticle(), G4BraggModel::SetParticle(), G4BraggIonModel::SetParticle(), G4GoudsmitSaundersonMscModel::SetParticle(), G4UniversalFluctuation::SetParticleAndCharge(), G4AtimaFluctuations::SetParticleAndCharge(), G4IonFluctuations::SetParticleAndCharge(), G4PrimaryParticle::SetParticleDefinition(), G4ParticleGun::SetParticleMomentum(), G4PrimaryParticle::SetPDGcode(), G4EnergyLossForExtrapolator::SetupKinematics(), G4EmCorrections::SetupKinematics(), G4AtimaEnergyLossModel::SetupParameters(), G4LindhardSorensenIonModel::SetupParameters(), G4BetheBlochModel::SetupParameters(), G4WentzelOKandVIxSection::SetupParticle(), G4IonCoulombCrossSection::SetupParticle(), G4ScreeningMottCrossSection::SetupParticle(), G4eSingleCoulombScatteringModel::SetupParticle(), G4IonCoulombScatteringModel::SetupParticle(), G4hCoulombScatteringModel::SetupParticle(), G4eCoulombScatteringModel::SetupParticle(), G4RayShooter::Shoot(), G4SPSEneDistribution::SplineInterpolation(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4QGSMFragmentation::SplitLast(), G4LundStringFragmentation::SplitLast(), G4VEmProcess::StartTracking(), G4VEnergyLossProcess::StartTracking(), SteppingAction::SteppingAction(), G4NuclNuclDiffuseElastic::TestAngleTable(), G4DiffuseElastic::TestAngleTable(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4IonYangFluctuationModel::TheValue(), G4IonChuFluctuationModel::TheValue(), G4hBetheBlochModel::TheValue(), G4hParametrisedLossModel::TheValue(), G4hNuclearStoppingModel::TheValue(), G4hIonEffChargeSquare::TheValue(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4ChipsProtonInelasticXS::ThresholdMomentum(), G4ChipsPionPlusInelasticXS::ThresholdMomentum(), G4GeneralPhaseSpaceDecay::TwoBodyDecayIt(), G4EmCalculator::UpdateParticle(), and G4ParticleChangeForGamma::UpdateStepForPostStep().
G4double G4ParticleDefinition::GetPDGSpin () const inline
Definition at line 126 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleDefinition.hh
References thePDGSpin.
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4hBremsstrahlungModel::ComputeDMicroscopicCrossSection(), G4LDMBremModel::ComputeDMicroscopicCrossSection(), G4AdjointhIonisationModel::DefineProjectileProperty(), G4AdjointIonIonisationModel::DefineProjectileProperty(), export_G4ParticleDefinition(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), G4hIonisation::InitialiseEnergyLossProcess(), G4PixeCrossSectionHandler::MicroscopicCrossSection(), G4hImpactIonisation::MicroscopicCrossSection(), G4hImpactIonisation::PostStepDoIt(), G4DynamicParticle::SetDefinition(), G4BraggModel::SetParticle(), G4BraggIonModel::SetParticle(), G4AtimaEnergyLossModel::SetupParameters(), G4LindhardSorensenIonModel::SetupParameters(), G4BetheBlochModel::SetupParameters(), G4WentzelOKandVIxSection::SetupParticle(), G4IonCoulombCrossSection::SetupParticle(), G4ScreeningMottCrossSection::SetupParticle(), and G4FieldTrackUpdator::Update().
G4bool G4ParticleDefinition::GetPDGStable () const
Referenced by G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode(), G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4EmExtraPhysics::ConstructProcess(), G4Decay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), export_G4ParticleDefinition(), G4HtmlPPReporter::GeneratePropertyTable(), G4ParticlePropertyMessenger::GetCurrentValue(), G4MuonicAtomDecay::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4Decay::GetMeanLifeTime(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), STCyclotronSensitiveTarget::ProcessHits(), G4BinaryCascade::ProductsAddFinalState(), and G4BinaryCascade::Propagate1H1().
G4double G4ParticleDefinition::GetPDGWidth () const inline
Definition at line 123 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ParticleDefinition.hh
References thePDGWidth.
Referenced by G4HadronicProcess::CheckResult(), G4AntiSigmaZero::Definition(), G4PionZero::Definition(), G4SigmaZero::Definition(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), export_G4ParticleDefinition(), G4VDecayChannel::FillDaughters(), G4ExcitedStringDecay::FragmentStrings(), G4KineticTrack::G4KineticTrack(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4ParticlePropertyTable::GetParticleProperty(), G4SampleResonance::SampleMass(), G4XAnnihilationChannel::VariablePartialWidth(), and G4XAnnihilationChannel::VariableWidth().
G4ProcessManager * G4ParticleDefinition::GetProcessManager () const
Definition at line 257 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 257 of file G4ParticleDefinition.cc
References G4MT_pmanager, and g4particleDefinitionInstanceID.
Referenced by G4EmModelActivator::ActivateMicroElec(), G4EmCalculator::ActiveForParticle(), G4ITStepProcessor::ActiveOnlyITProcess(), PhysicsList::AddDarkMatter(), XrayFluoPhysicsList::AddDecay(), Par02PhysicsList::AddParameterisation(), G4IonPhysicsXS::AddProcess(), G4IonPhysics::AddProcess(), G4IonPhysicsPHP::AddProcess(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), G4IonTable::AddProcessManager(), B03PhysicsList::AddScoringProcess(), F04PhysicsList::AddStepMax(), HadrontherapyPhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), PhysicsList::AddStepMax(), ML2PhysicsList::AddStepMax(), ExN02PhysicsList::AddStepMax(), IORTPhysicsList::AddStepMax(), G4PhysicsListHelper::AddTransportation(), DMXPhysicsList::AddTransportation(), LBE::AddTransportation(), G4hImpactIonisation::AlongStepDoIt(), G4GenericBiasingPhysics::AssociateParallelGeometries(), RunAction::BeginOfRunAction(), G4AlphaBuilder::Build(), G4He3Builder::Build(), G4AntiBarionBuilder::Build(), G4DeuteronBuilder::Build(), G4PionBuilder::Build(), G4TritonBuilder::Build(), G4BertiniElectroNuclearBuilder::Build(), G4PiKBuilder::Build(), G4KaonBuilder::Build(), G4ProtonBuilder::Build(), G4NeutronBuilder::Build(), G4HyperonFTFPBuilder::Build(), G4hImpactIonisation::BuildPhysicsTable(), G4VUserChemistryList::BuildPhysicsTable(), G4VUserPhysicsList::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4PhysicsListHelper::CheckParticleList(), G4BOptrForceCollision::ConfigureForWorker(), G4RunManagerKernel::ConfirmCoupledTransportation(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), PhysicsList::ConstructHighEnergy(), DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), XPhysicsList::ConstructProcess(), G4ChannelingPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructProcess(), GammaNuclearPhysics::ConstructProcess(), StepMaxBuilder::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), NeutronHPphysics::ConstructProcess(), PhysicsListEMstd::ConstructProcess(), PhysListEmStandard::ConstructProcess(), G4NeutronCrossSectionXS::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), StepLimiterBuilder::ConstructProcess(), G4ParallelWorldPhysics::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), MuNuclearBuilder::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), TransitionRadiationPhysics::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), G4NeutronTrackingCut::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), F04PhysicsList::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), P6DExtDecayerPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), GammaRayTelMuonPhysics::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), CexmcStudiedPhysics< Process >::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), ExUCNExtraPhysics::ConstructUCN(), G4TheRayTracer::CreateBitMap(), G4IonTable::CreateIon(), G4ITStepProcessor::DealWithSecondaries(), export_G4ParticleDefinition(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4PhysListUtil::FindCaptureProcess(), G4VHadronPhysics::FindCaptureProcess(), G4VHadronPhysics::FindElasticProcess(), G4PhysListUtil::FindFissionProcess(), G4VHadronPhysics::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4VHadronPhysics::FindInelasticProcess(), G4EmModelActivator::FindOrAddProcess(), G4EmCalculator::FindProcess(), F01RunAction::findTransportation(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4HadronElasticPhysics::GetElasticProcess(), PhysicsList::GetProcess(), G4ITStepProcessor::GetProcessInfo(), G4ProcessPlacer::GetProcessManager(), G4SteppingManager::GetProcessNumber(), G4ErrorPropagator::InitG4Track(), G4VUserPhysicsList::InitializeProcessManager(), PHG4Reco::InitRun(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VUserPhysicsList::PreparePhysicsTable(), G4TrackingManager::ProcessOneTrack(), G4ErrorPropagator::Propagate(), G4PhysicsListHelper::RegisterProcess(), G4VUserPhysicsList::RemoveProcessManager(), G4VUserPhysicsList::RetrievePhysicsTable(), G4ProcessManagerMessenger::SetCurrentParticle(), G4EmConfigurator::SetModelForRegion(), G4UserPhysicsListMessenger::SetNewValue(), G4RunManagerKernel::SetScoreSplitter(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), G4GlobalFastSimulationManager::ShowSetup(), GB01BOptrChangeCrossSection::StartRun(), GB07BOptrLeadingParticle::StartRun(), G4ChannelingOptrChangeCrossSection::StartRun(), GB05BOptrSplitAndKillByCrossSection::StartRun(), GB06BOptrSplitAndKillByImportance::StartRun(), G4ITTrackingManager::StartTracking(), G4VUserPhysicsList::StorePhysicsTable(), PHG4RICHSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), and WLSSteppingAction::UserSteppingAction().
G4int G4ParticleDefinition::GetQuarkContent (G4int flavor) const
Referenced by G4RPGInelastic::CheckQnums(), G4ElementaryParticleCollider::collide(), G4IonTable::Contains(), G4XAqmTotal::CrossSection(), export_G4ParticleDefinition(), G4IonTable::FindIon(), G4IonTable::FindIonInMaster(), G4HtmlPPReporter::GeneratePropertyTable(), G4VCollision::GetNumberOfPartons(), G4InuclElementaryParticle::getStrangeness(), G4IonTable::Insert(), G4IonTable::InsertWorker(), Par02FastSimModelHCal::IsApplicable(), G4XAnnihilationChannel::NormalizedClebsch(), and G4IonTable::Remove().
const G4PDefManager & G4ParticleDefinition::GetSubInstanceManager () static
Definition at line 243 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 243 of file G4ParticleDefinition.cc
References subInstanceManager.
Referenced by G4ParticlesWorkspace::G4ParticlesWorkspace().
G4int G4ParticleDefinition::GetVerboseLevel () const
Referenced by export_G4ParticleDefinition(), and G4ParticleDefinition().
G4bool G4ParticleDefinition::IsGeneralIon () const
Referenced by PHG4TruthTrackingAction::AddParticle(), G4IonTable::AddProcessManager(), DumpTable(), G4IonTable::GetLifeTime(), G4VUserPhysicsList::InitializeProcessManager(), G4RunManagerKernel::PropagateGenericIonID(), G4NIELCalculator::RecoilEnergy(), and G4RunManagerKernel::SetupPhysics().
G4bool G4ParticleDefinition::IsMuonicAtom () const
G4bool G4ParticleDefinition::IsShortLived () const inline
Definition at line 157 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleDefinition.hh
References fShortLivedFlag.
Referenced by XrayFluoPhysicsList::AddDecay(), F04PhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), G4GenericBiasingPhysics::AssociateParallelGeometries(), G4VUserPhysicsList::BuildPhysicsTable(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4HadronicProcess::CheckResult(), eRositaPhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), PhysListEmStandard::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), StepLimiterBuilder::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4XResonance::CrossSection(), G4DecayKineticTracks::Decay(), G4KineticTrack::Decay(), G4VXResonance::DetailedBalance(), export_G4ParticleDefinition(), G4ExcitedStringDecay::FragmentStrings(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4KineticTrack::G4KineticTrack(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4HtmlPPReporter::GeneratePropertyTable(), G4BCDecay::GetCollisions(), G4PrimaryTransformer::GetDefinition(), G4SampleResonance::GetMinimumMass(), StepMax::IsApplicable(), StepMaxProcess::IsApplicable(), StepLimiter::IsApplicable(), G4CoulombScattering::IsApplicable(), G4MuElecInelastic::IsApplicable(), G4alphaIonisation::IsApplicable(), G4hhIonisation::IsApplicable(), G4MuMultipleScattering::IsApplicable(), G4eMultipleScattering::IsApplicable(), G4hMultipleScattering::IsApplicable(), G4eAdjointMultipleScattering::IsApplicable(), G4NuclearStopping::IsApplicable(), G4AdjointhMultipleScattering::IsApplicable(), G4ionIonisation::IsApplicable(), G4SynchrotronRadiation::IsApplicable(), G4hIonisation::IsApplicable(), G4Cerenkov::IsApplicable(), G4Scintillation::IsApplicable(), G4PrimaryTransformer::IsGoodForTrack(), G4VXResonance::IsospinCorrection(), G4VUserPhysicsList::PreparePhysicsTable(), G4BinaryCascade::ProductsAddFinalState(), G4BinaryCascade::Propagate1H1(), and G4ParticleGun::SetParticleDefinition().
G4bool G4ParticleDefinition::operator!= (const G4ParticleDefinition & right) const
Definition at line 237 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 237 of file G4ParticleDefinition.cc
References theParticleName.
const G4ParticleDefinition & G4ParticleDefinition::operator= (const G4ParticleDefinition & r) private
Definition at line 225 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 225 of file G4ParticleDefinition.cc
G4bool G4ParticleDefinition::operator== (const G4ParticleDefinition & right) const
Definition at line 232 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 232 of file G4ParticleDefinition.cc
References theParticleName.
void G4ParticleDefinition::SetAntiPDGEncoding (G4int aEncoding)
Referenced by G4ShortLivedConstructor::ConstructMesons(), G4ExcitedMesonConstructor::ConstructMesons(), G4ShortLivedConstructor::ConstructQuarks(), G4IonTable::CreateIon(), G4AdjointAlpha::Definition(), G4AdjointDeuteron::Definition(), G4AdjointTriton::Definition(), G4AdjointHe3::Definition(), and G4InuclNuclei::makeNuclearFragment().
void G4ParticleDefinition::SetApplyCutsFlag (G4bool flg)
Definition at line 403 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 403 of file G4ParticleDefinition.cc
References fApplyCutsFlag, G4cout, G4endl, and theParticleName.
Referenced by export_G4ParticleDefinition(), and G4VUserPhysicsList::SetApplyCuts().
void G4ParticleDefinition::SetAtomicMass (G4int) protected
Referenced by G4AdjointIons::G4AdjointIons(), G4DNAIons::G4DNAIons(), G4Ions::G4Ions(), and G4ParticleDefinition().
void G4ParticleDefinition::SetAtomicNumber (G4int) protected
Referenced by G4AdjointIons::G4AdjointIons(), G4DNAIons::G4DNAIons(), G4Ions::G4Ions(), and G4ParticleDefinition().
void G4ParticleDefinition::SetDecayTable (G4DecayTable * aDecayTable)
Referenced by G4ExcitedBaryonConstructor::ConstructAntiParticle(), G4ShortLivedConstructor::ConstructBaryons(), G4ShortLivedConstructor::ConstructMesons(), G4ExcitedMesonConstructor::ConstructMesons(), G4ExcitedBaryonConstructor::ConstructParticle(), G4EtaPrime::Definition(), G4TauPlus::Definition(), G4TauMinus::Definition(), G4AntiNeutron::Definition(), G4MuonMinus::Definition(), G4AntiXiMinus::Definition(), G4PionPlus::Definition(), G4AntiKaonZero::Definition(), G4KaonZeroShort::Definition(), G4Eta::Definition(), G4KaonZero::Definition(), G4AntiXiZero::Definition(), G4KaonMinus::Definition(), G4Lambda::Definition(), G4KaonPlus::Definition(), G4KaonZeroLong::Definition(), G4XiZero::Definition(), G4XiMinus::Definition(), G4SigmaZero::Definition(), G4AntiLambda::Definition(), G4SigmaMinus::Definition(), G4SigmacZero::Definition(), G4AntiOmegaMinus::Definition(), G4OmegaMinus::Definition(), G4AntiSigmacPlusPlus::Definition(), G4MuonPlus::Definition(), G4PionMinus::Definition(), G4PionZero::Definition(), G4AntiSigmacPlus::Definition(), G4SigmacPlus::Definition(), G4SigmacPlusPlus::Definition(), G4AntiSigmacZero::Definition(), G4AntiSigmaZero::Definition(), G4SigmaPlus::Definition(), G4AntiSigmaMinus::Definition(), G4AntiSigmaPlus::Definition(), G4SigmabMinus::Definition(), G4SigmabZero::Definition(), G4Neutron::Definition(), G4AntiSigmabZero::Definition(), G4AntiSigmabPlus::Definition(), G4AntiSigmabMinus::Definition(), G4SigmabPlus::Definition(), export_G4ParticleDefinition(), G4LDMPhoton::LDMPhotonDefinition(), and F04PhysicsListMessenger::SetNewValue().
void G4ParticleDefinition::SetMasterProcessManager (G4ProcessManager * aNewPM) inline
Referenced by G4VUserPhysicsList::InitializeProcessManager().
void G4ParticleDefinition::SetParticleDefinitionID (G4int id = -1)
Definition at line 436 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 436 of file G4ParticleDefinition.cc
References G4PDefManager::CreateSubInstance(), FatalException, G4Exception(), G4MT_pmanager, g4particleDefinitionInstanceID, isGeneralIon, isMuonicAtom, subInstanceManager, and theParticleName.
Referenced by G4IonTable::AddProcessManager(), G4RunManagerKernel::PropagateGenericIonID(), SetProcessManager(), and G4RunManagerKernel::SetupPhysics().
void G4ParticleDefinition::SetParticleSubType (const G4String & subtype) protected
Referenced by G4DiQuarks::G4DiQuarks(), G4Gluons::G4Gluons(), G4Quarks::G4Quarks(), G4ExcitedBaryons::SetMultipletName(), and G4ExcitedMesons::SetMultipletName().
void G4ParticleDefinition::SetPDGLifeTime (G4double aLifeTime) inline
Definition at line 163 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ParticleDefinition.hh
References thePDGLifeTime.
Referenced by G4AntiSigmaZero::Definition(), G4PionZero::Definition(), G4SigmaZero::Definition(), export_G4ParticleDefinition(), and G4ParticlePropertyMessenger::SetNewValue().
void G4ParticleDefinition::SetPDGMagneticMoment (G4double mageticMoment)
Referenced by G4MuonicAtomHelper::ConstructMuonicAtom(), G4IonTable::CreateIon(), G4OmegaMinus::Definition(), G4AntiLambda::Definition(), G4MuonPlus::Definition(), G4TauMinus::Definition(), G4TauPlus::Definition(), G4MuonMinus::Definition(), G4Electron::Definition(), G4AntiNeutron::Definition(), G4Lambda::Definition(), G4AntiOmegaMinus::Definition(), G4SigmaMinus::Definition(), G4SigmaPlus::Definition(), G4AntiProton::Definition(), G4XiMinus::Definition(), G4XiZero::Definition(), G4AntiSigmaMinus::Definition(), G4AntiSigmaPlus::Definition(), G4AntiXiMinus::Definition(), G4AntiXiZero::Definition(), G4Triton::Definition(), G4Neutron::Definition(), G4Positron::Definition(), G4Proton::Definition(), G4Deuteron::Definition(), G4AntiHe3::Definition(), G4AntiDeuteron::Definition(), G4AntiTriton::Definition(), G4He3::Definition(), G4AdjointHe3::Definition(), G4AdjointTriton::Definition(), G4AdjointDeuteron::Definition(), G4AdjointProton::Definition(), G4AdjointPositron::Definition(), G4AdjointElectronFI::Definition(), and G4AdjointElectron::Definition().
void G4ParticleDefinition::SetPDGStable (const G4bool aFlag) inline
Definition at line 160 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ParticleDefinition.hh
References thePDGStable.
Referenced by export_G4ParticleDefinition(), and G4ParticlePropertyMessenger::SetNewValue().
void G4ParticleDefinition::SetProcessManager (G4ProcessManager * aProcessManager)
Definition at line 460 of file G4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 460 of file G4ParticleDefinition.cc
References G4Exception(), G4Threading::G4GetThreadId(), G4MT_pmanager, g4particleDefinitionInstanceID, isGeneralIon, JustWarning, SetParticleDefinitionID(), and theParticleName.
Referenced by G4AdjointPhysicsList::ConstructEM(), export_G4ParticleDefinition(), G4VUserPhysicsList::InitializeProcessManager(), and G4VUserPhysicsList::RemoveProcessManager().
void G4ParticleDefinition::SetVerboseLevel (G4int value)
Referenced by export_G4ParticleDefinition(), G4ParticleTable::Insert(), and G4ParticlePropertyMessenger::SetNewValue().
Friends And Related Function Documentation
friend class G4ParticlePropertyTable friend
Definition at line 80 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleDefinition.hh
Member Data Documentation
G4bool G4ParticleDefinition::fApplyCutsFlag private
Definition at line 369 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 369 of file G4ParticleDefinition.hh
Referenced by SetApplyCutsFlag().
G4bool G4ParticleDefinition::fShortLivedFlag private
Definition at line 345 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 345 of file G4ParticleDefinition.hh
Referenced by DumpTable(), G4ParticleDefinition(), and IsShortLived().
G4int G4ParticleDefinition::g4particleDefinitionInstanceID private
Definition at line 233 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 233 of file G4ParticleDefinition.hh
Referenced by G4ParticleDefinition(), GetProcessManager(), SetParticleDefinitionID(), and SetProcessManager().
G4bool G4ParticleDefinition::isGeneralIon protected
Definition at line 372 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 372 of file G4ParticleDefinition.hh
Referenced by G4Ions::G4Ions(), G4MuonicAtom::G4MuonicAtom(), SetParticleDefinitionID(), and SetProcessManager().
G4bool G4ParticleDefinition::isMuonicAtom protected
Definition at line 373 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 373 of file G4ParticleDefinition.hh
Referenced by G4MuonicAtom::G4MuonicAtom(), and SetParticleDefinitionID().
G4PDefManager G4ParticleDefinition::subInstanceManager static private
Definition at line 236 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 236 of file G4ParticleDefinition.hh
Referenced by Clean(), GetSubInstanceManager(), and SetParticleDefinitionID().
G4int G4ParticleDefinition::theAntiPDGEncoding private
Definition at line 340 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 340 of file G4ParticleDefinition.hh
Referenced by G4ParticleDefinition(), GetAntiPDGEncoding(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::theAntiQuarkContent[NumberOfQuarkFlavor] protected
Definition at line 267 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 267 of file G4ParticleDefinition.hh
Referenced by DumpTable(), FillQuarkContents(), G4ParticlePropertyTable::GetParticleProperty(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::theAtomicMass private
Definition at line 366 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 366 of file G4ParticleDefinition.hh
G4int G4ParticleDefinition::theAtomicNumber private
Definition at line 365 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 365 of file G4ParticleDefinition.hh
G4int G4ParticleDefinition::theBaryonNumber private
Definition at line 327 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 327 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetBaryonNumber(), and G4ParticlePropertyTable::SetParticleProperty().
G4DecayTable* G4ParticleDefinition::theDecayTable private
Definition at line 358 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 358 of file G4ParticleDefinition.hh
Referenced by DumpTable(), and ~G4ParticleDefinition().
G4int G4ParticleDefinition::theLeptonNumber private
Definition at line 324 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 324 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetLeptonNumber(), and G4ParticlePropertyTable::SetParticleProperty().
G4String G4ParticleDefinition::theParticleName private
Definition at line 277 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 277 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetParticleName(), operator!=(), operator==(), SetApplyCutsFlag(), SetParticleDefinitionID(), and SetProcessManager().
G4String G4ParticleDefinition::theParticleSubType private
Definition at line 333 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 333 of file G4ParticleDefinition.hh
Referenced by DumpTable(), and GetParticleSubType().
G4ParticleTable* G4ParticleDefinition::theParticleTable private
Definition at line 363 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 363 of file G4ParticleDefinition.hh
Referenced by DumpTable(), and G4ParticleDefinition().
G4String G4ParticleDefinition::theParticleType private
Definition at line 330 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 330 of file G4ParticleDefinition.hh
Referenced by DumpTable(), FillQuarkContents(), G4ParticleDefinition(), and GetParticleType().
G4double G4ParticleDefinition::thePDGCharge private
Definition at line 291 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 291 of file G4ParticleDefinition.hh
Referenced by CalculateAnomaly(), DumpTable(), FillQuarkContents(), GetPDGCharge(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGEncoding private
Definition at line 337 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 337 of file G4ParticleDefinition.hh
Referenced by DumpTable(), FillQuarkContents(), G4ParticleDefinition(), GetPDGEncoding(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGiConjugation private
Definition at line 308 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 308 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetPDGiConjugation(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGiGParity private
Definition at line 311 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 311 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetPDGiGParity(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGiIsospin private
Definition at line 314 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 314 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetPDGiIsospin(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGiIsospin3 private
Definition at line 315 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 315 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetPDGiIsospin3(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGiParity private
Definition at line 304 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 304 of file G4ParticleDefinition.hh
Referenced by DumpTable(), GetPDGiParity(), and G4ParticlePropertyTable::SetParticleProperty().
G4double G4ParticleDefinition::thePDGIsospin private
Definition at line 317 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 317 of file G4ParticleDefinition.hh
Referenced by GetPDGIsospin(), and G4ParticlePropertyTable::SetParticleProperty().
G4double G4ParticleDefinition::thePDGIsospin3 private
Definition at line 318 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 318 of file G4ParticleDefinition.hh
Referenced by GetPDGIsospin3(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::thePDGiSpin private
Definition at line 298 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 298 of file G4ParticleDefinition.hh
Referenced by CalculateAnomaly(), DumpTable(), FillQuarkContents(), GetPDGiSpin(), and G4ParticlePropertyTable::SetParticleProperty().
G4double G4ParticleDefinition::thePDGLifeTime private
Definition at line 354 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 354 of file G4ParticleDefinition.hh
Referenced by DumpTable(), G4ParticlePropertyTable::SetParticleProperty(), and SetPDGLifeTime().
G4double G4ParticleDefinition::thePDGMagneticMoment private
Definition at line 321 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 321 of file G4ParticleDefinition.hh
Referenced by CalculateAnomaly(), DumpTable(), GetPDGMagneticMoment(), and G4ParticlePropertyTable::SetParticleProperty().
G4double G4ParticleDefinition::thePDGMass private
Definition at line 283 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 283 of file G4ParticleDefinition.hh
Referenced by CalculateAnomaly(), DumpTable(), GetPDGMass(), and G4ParticlePropertyTable::SetParticleProperty().
G4double G4ParticleDefinition::thePDGSpin private
Definition at line 301 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 301 of file G4ParticleDefinition.hh
Referenced by GetPDGSpin(), and G4ParticlePropertyTable::SetParticleProperty().
G4bool G4ParticleDefinition::thePDGStable private
Definition at line 349 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 349 of file G4ParticleDefinition.hh
Referenced by DumpTable(), and SetPDGStable().
G4double G4ParticleDefinition::thePDGWidth private
Definition at line 286 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 286 of file G4ParticleDefinition.hh
Referenced by DumpTable(), and GetPDGWidth().
G4ProcessManager* G4ParticleDefinition::theProcessManagerShadow private
Definition at line 229 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 229 of file G4ParticleDefinition.hh
Referenced by G4ParticleDefinition().
G4int G4ParticleDefinition::theQuarkContent[NumberOfQuarkFlavor] protected
Definition at line 266 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 266 of file G4ParticleDefinition.hh
Referenced by DumpTable(), FillQuarkContents(), G4ParticlePropertyTable::GetParticleProperty(), and G4ParticlePropertyTable::SetParticleProperty().
G4int G4ParticleDefinition::verboseLevel private
Definition at line 368 of file G4ParticleDefinition.hh.
View newest version in sPHENIX GitHub at line 368 of file G4ParticleDefinition.hh
Referenced by FillQuarkContents(), G4ParticleDefinition(), and ~G4ParticleDefinition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticleDefinition.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4ParticleDefinition.cc