ECCE @ EIC Software: G4SolidExtentList Class Reference
G4SolidExtentList Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4SolidExtentList.hh>
Public Member Functions
G4SolidExtentList ()
G4SolidExtentList (const EAxis targetAxis, const G4VoxelLimits &voxelLimits)
~G4SolidExtentList ()
void AddSurface (const G4ClippablePolygon &surface)
G4bool GetExtent (G4double &min, G4double &max) const
Protected Attributes
EAxis axis
G4bool limited = false
G4double minLimit
G4double maxLimit
G4ClippablePolygon minSurface
G4ClippablePolygon maxSurface
G4ClippablePolygon minAbove
G4ClippablePolygon maxBelow
Detailed Description
Definition at line 45 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 45 of file G4SolidExtentList.hh
Constructor & Destructor Documentation
G4SolidExtentList::G4SolidExtentList ()
Definition at line 37 of file G4SolidExtentList.cc.
View newest version in sPHENIX GitHub at line 37 of file G4SolidExtentList.cc
References axis, INT_MAX, kZAxis, maxLimit, and minLimit.
G4SolidExtentList::G4SolidExtentList (const EAxis targetAxis, const G4VoxelLimits & voxelLimits)
Definition at line 46 of file G4SolidExtentList.cc.
View newest version in sPHENIX GitHub at line 46 of file G4SolidExtentList.cc
References axis, G4VoxelLimits::GetMaxExtent(), G4VoxelLimits::GetMinExtent(), INT_MAX, G4VoxelLimits::IsLimited(), limited, maxLimit, and minLimit.
G4SolidExtentList::~G4SolidExtentList ()
Definition at line 66 of file G4SolidExtentList.cc.
View newest version in sPHENIX GitHub at line 66 of file G4SolidExtentList.cc
Member Function Documentation
void G4SolidExtentList::AddSurface (const G4ClippablePolygon & surface)
Definition at line 73 of file G4SolidExtentList.cc.
View newest version in sPHENIX GitHub at line 73 of file G4SolidExtentList.cc
References axis, G4ClippablePolygon::BehindOf(), G4ClippablePolygon::GetExtent(), G4ClippablePolygon::InFrontOf(), max, maxBelow, maxLimit, maxSurface, min, minAbove, minLimit, and minSurface.
Referenced by G4PolyPhiFace::CalculateExtent(), G4PolyconeSide::CalculateExtent(), and G4PolyhedraSide::CalculateExtent().
G4bool G4SolidExtentList::GetExtent (G4double & min, G4double & max) const
Definition at line 110 of file G4SolidExtentList.cc.
View newest version in sPHENIX GitHub at line 110 of file G4SolidExtentList.cc
References axis, G4ClippablePolygon::Empty(), G4ClippablePolygon::GetExtent(), G4GeometryTolerance::GetInstance(), G4ClippablePolygon::GetNormal(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, maxLimit, maxSurface, minAbove, minLimit, and minSurface.
Referenced by G4VCSGfaceted::CalculateExtent().
Member Data Documentation
EAxis G4SolidExtentList::axis protected
Definition at line 61 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 61 of file G4SolidExtentList.hh
Referenced by AddSurface(), G4SolidExtentList(), and GetExtent().
G4bool G4SolidExtentList::limited = false protected
Definition at line 62 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 62 of file G4SolidExtentList.hh
Referenced by G4SolidExtentList().
G4ClippablePolygon G4SolidExtentList::maxBelow protected
Definition at line 66 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4SolidExtentList.hh
Referenced by AddSurface().
G4double G4SolidExtentList::maxLimit protected
Definition at line 64 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 64 of file G4SolidExtentList.hh
Referenced by AddSurface(), G4SolidExtentList(), and GetExtent().
G4ClippablePolygon G4SolidExtentList::maxSurface protected
Definition at line 66 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4SolidExtentList.hh
Referenced by AddSurface(), and GetExtent().
G4ClippablePolygon G4SolidExtentList::minAbove protected
Definition at line 66 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4SolidExtentList.hh
Referenced by AddSurface(), and GetExtent().
G4double G4SolidExtentList::minLimit protected
Definition at line 63 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 63 of file G4SolidExtentList.hh
Referenced by AddSurface(), G4SolidExtentList(), and GetExtent().
G4ClippablePolygon G4SolidExtentList::minSurface protected
Definition at line 66 of file G4SolidExtentList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4SolidExtentList.hh
Referenced by AddSurface(), and GetExtent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4SolidExtentList.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4SolidExtentList.cc