ECCE @ EIC Software: G4DNACPA100IonisationModel Class Reference
G4DNACPA100IonisationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNACPA100IonisationModel.hh>
Public Member Functions
G4DNACPA100IonisationModel (const G4ParticleDefinition *p=0, const G4String &nam="DNACPA100IonisationModel")
virtual ~G4DNACPA100IonisationModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &=*(new G4DataVector()))
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
G4double DifferentialCrossSection (G4ParticleDefinition *aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
void SelectFasterComputation (G4bool input)
void SelectUseDcs (G4bool input)
void SelectStationary (G4bool input)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Types
typedef std::map< G4String,
G4String, std::less< G4String > > MapFile
typedef std::map< G4String,
G4DNACrossSectionDataSet
*, std::less< G4String > > MapData
typedef std::map< G4double,
std::map< G4double, G4double > > TriDimensionMap
typedef std::map< G4double,
std::vector< G4double > > VecMap
Private Member Functions
G4double RandomizeEjectedElectronEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomizeEjectedElectronEnergyFromCompositionSampling (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomTransferedEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
void RandomizeEjectedElectronDirection (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4double outgoingParticleEnergy, G4double &cosTheta, G4double &phi)
G4double Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
G4int RandomSelect (G4double energy, const G4String &particle)
G4DNACPA100IonisationModel & operator= (const G4DNACPA100IonisationModel &right)
G4DNACPA100IonisationModel (const G4DNACPA100IonisationModel &)
Private Attributes
G4bool statCode
G4bool fasterCode
G4bool useDcs
const std::vector< G4double > * fpMolWaterDensity
G4VAtomDeexcitation * fAtomDeexcitation
std::map< G4String, G4double,
std::less< G4String > > lowEnergyLimit
std::map< G4String, G4double,
std::less< G4String > > highEnergyLimit
G4bool isInitialised
G4int verboseLevel
MapFile tableFile
MapData tableData
G4DNACPA100WaterIonisationStructure waterStructure
TriDimensionMap eDiffCrossSectionData [6]
TriDimensionMap eNrjTransfData [6]
std::vector< G4double > eTdummyVec
VecMap eVecm
VecMap eProbaShellMap [6]
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 60 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4DNACPA100IonisationModel.hh
Member Typedef Documentation
typedef std::map<G4String,G4DNACrossSectionDataSet*,std::less<G4String> > G4DNACPA100IonisationModel::MapData private
Definition at line 120 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4DNACPA100IonisationModel.hh
typedef std::map<G4String,G4String,std::less<G4String> > G4DNACPA100IonisationModel::MapFile private
Definition at line 117 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4DNACPA100IonisationModel.hh
typedef std::map<G4double, std::map<G4double, G4double> > G4DNACPA100IonisationModel::TriDimensionMap private
Definition at line 153 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4DNACPA100IonisationModel.hh
typedef std::map<G4double, std::vector<G4double> > G4DNACPA100IonisationModel::VecMap private
Definition at line 160 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4DNACPA100IonisationModel.hh
Constructor & Destructor Documentation
G4DNACPA100IonisationModel::G4DNACPA100IonisationModel (const G4ParticleDefinition * p = 0, const G4String & nam = "DNACPA100IonisationModel")
Definition at line 55 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4DNACPA100IonisationModel.cc
References eV, fasterCode, fAtomDeexcitation, fParticleChangeForGamma, fpMolWaterDensity, G4cout, G4endl, G4VEmModel::SetDeexcitationFlag(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), statCode, useDcs, and verboseLevel.
G4DNACPA100IonisationModel::~G4DNACPA100IonisationModel () virtual
Definition at line 101 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 101 of file G4DNACPA100IonisationModel.cc
References eVecm, pos(), and tableData.
G4DNACPA100IonisationModel::G4DNACPA100IonisationModel (const G4DNACPA100IonisationModel &) private
Member Function Documentation
G4double G4DNACPA100IonisationModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 251 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 251 of file G4DNACPA100IonisationModel.cc
References cm, G4Electron::ElectronDefinition(), eV, FatalException, G4DNACrossSectionDataSet::FindValue(), G4cout, G4endl, G4Exception(), G4Material::GetIndex(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), pos(), tableData, and verboseLevel.
G4double G4DNACPA100IonisationModel::DifferentialCrossSection (G4ParticleDefinition * aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
Definition at line 570 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 570 of file G4DNACPA100IonisationModel.cc
References e, eDiffCrossSectionData, G4Electron::ElectronDefinition(), eTdummyVec, eV, eVecm, G4DNACPA100WaterIonisationStructure::IonisationEnergy(), k, QuadInterpolator(), t1, t2, and waterStructure.
Referenced by RandomizeEjectedElectronEnergy().
void G4DNACPA100IonisationModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector & = *(new G4DataVector())) virtual
Implements G4VEmModel.
Definition at line 120 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 120 of file G4DNACPA100IonisationModel.cc
References G4LossTableManager::AtomDeexcitation(), eDiffCrossSectionData, G4InuclParticleNames::electron, G4Electron::ElectronDefinition(), eNrjTransfData, eProbaShellMap, eTdummyVec, eV, eVecm, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, fpMolWaterDensity, G4cout, G4endl, G4Exception(), G4Material::GetMaterial(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4LossTableManager::Instance(), G4DNAMolecularMaterial::Instance(), isInitialised, keV, G4DNACrossSectionDataSet::LoadData(), G4VEmModel::LowEnergyLimit(), m, tableData, tableFile, useDcs, and verboseLevel.
G4double G4DNACPA100IonisationModel::Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 646 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 646 of file G4DNACPA100IonisationModel.cc
References a, b, d1, d2, e1, fasterCode, and useDcs.
Referenced by QuadInterpolator().
G4DNACPA100IonisationModel& G4DNACPA100IonisationModel::operator= (const G4DNACPA100IonisationModel & right) private
G4double G4DNACPA100IonisationModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 710 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 710 of file G4DNACPA100IonisationModel.cc
References Interpolate().
Referenced by DifferentialCrossSection().
void G4DNACPA100IonisationModel::RandomizeEjectedElectronDirection (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4double outgoingParticleEnergy, G4double & cosTheta, G4double & phi) private
Definition at line 555 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 555 of file G4DNACPA100IonisationModel.cc
References source.hepunit::electron_mass_c2, G4UniformRand, k, and twopi.
Referenced by SampleSecondaries().
G4double G4DNACPA100IonisationModel::RandomizeEjectedElectronEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 471 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 471 of file G4DNACPA100IonisationModel.cc
References DifferentialCrossSection(), G4Electron::ElectronDefinition(), eV, G4UniformRand, G4DNACPA100WaterIonisationStructure::IonisationEnergy(), k, Acts::Test::step(), and waterStructure.
Referenced by SampleSecondaries().
G4double G4DNACPA100IonisationModel::RandomizeEjectedElectronEnergyFromCompositionSampling (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 1025 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 1025 of file G4DNACPA100IonisationModel.cc
References bb, F, G4UniformRand, r1, r2, t, and Acts::UnitConstants::u.
Referenced by SampleSecondaries().
G4double G4DNACPA100IonisationModel::RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 847 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 847 of file G4DNACPA100IonisationModel.cc
References eV.
Referenced by SampleSecondaries().
G4int G4DNACPA100IonisationModel::RandomSelect (G4double energy, const G4String & particle) private
Definition at line 726 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 726 of file G4DNACPA100IonisationModel.cc
References FatalException, G4VEMDataSet::FindValue(), G4Exception(), G4UniformRand, G4DNACrossSectionDataSet::GetComponent(), n, G4DNACrossSectionDataSet::NumberOfComponents(), pos(), and tableData.
Referenced by SampleSecondaries().
G4double G4DNACPA100IonisationModel::RandomTransferedEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 866 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 866 of file G4DNACPA100IonisationModel.cc
References e, G4Electron::ElectronDefinition(), G4UniformRand, k, k1, and k2.
void G4DNACPA100IonisationModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * , const G4DynamicParticle * particle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 303 of file G4DNACPA100IonisationModel.cc.
View newest version in sPHENIX GitHub at line 303 of file G4DNACPA100IonisationModel.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4DNAChemistryManager::CreateWaterMolecule(), eIonizedMolecule, G4Electron::Electron(), source.hepunit::electron_mass_c2, G4Electron::ElectronDefinition(), eV, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, G4cout, G4endl, G4Exception(), G4VAtomDeexcitation::GenerateParticles(), G4VAtomDeexcitation::GetAtomicShell(), G4ParticleChangeForGamma::GetCurrentTrack(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4VEmModel::HighEnergyLimit(), G4DNAChemistryManager::Instance(), G4DNACPA100WaterIonisationStructure::IonisationEnergy(), k, G4VEmModel::LowEnergyLimit(), phi, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), RandomizeEjectedElectronDirection(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCompositionSampling(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), RandomSelect(), CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), statCode, CLHEP::Hep3Vector::unit(), useDcs, verboseLevel, waterStructure, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4DNACPA100IonisationModel::SelectFasterComputation (G4bool input) inline
Definition at line 179 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4DNACPA100IonisationModel.hh
References fasterCode.
void G4DNACPA100IonisationModel::SelectStationary (G4bool input) inline
Definition at line 195 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 195 of file G4DNACPA100IonisationModel.hh
References statCode.
void G4DNACPA100IonisationModel::SelectUseDcs (G4bool input) inline
Definition at line 186 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 186 of file G4DNACPA100IonisationModel.hh
References useDcs.
Member Data Documentation
TriDimensionMap G4DNACPA100IonisationModel::eDiffCrossSectionData[6] private
Definition at line 155 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4DNACPA100IonisationModel.hh
Referenced by DifferentialCrossSection(), and Initialise().
TriDimensionMap G4DNACPA100IonisationModel::eNrjTransfData[6] private
Definition at line 156 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4DNACPA100IonisationModel.hh
Referenced by Initialise().
VecMap G4DNACPA100IonisationModel::eProbaShellMap[6] private
Definition at line 164 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4DNACPA100IonisationModel.hh
Referenced by Initialise().
std::vector<G4double> G4DNACPA100IonisationModel::eTdummyVec private
Definition at line 158 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4DNACPA100IonisationModel.hh
Referenced by DifferentialCrossSection(), and Initialise().
VecMap G4DNACPA100IonisationModel::eVecm private
Definition at line 162 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4DNACPA100IonisationModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and ~G4DNACPA100IonisationModel().
G4bool G4DNACPA100IonisationModel::fasterCode private
Definition at line 100 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4DNACPA100IonisationModel.hh
Referenced by G4DNACPA100IonisationModel(), Initialise(), Interpolate(), SampleSecondaries(), and SelectFasterComputation().
G4VAtomDeexcitation* G4DNACPA100IonisationModel::fAtomDeexcitation private
Definition at line 107 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4DNACPA100IonisationModel.hh
Referenced by G4DNACPA100IonisationModel(), Initialise(), and SampleSecondaries().
G4ParticleChangeForGamma* G4DNACPA100IonisationModel::fParticleChangeForGamma protected
Definition at line 94 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4DNACPA100IonisationModel.hh
Referenced by G4DNACPA100IonisationModel(), Initialise(), and SampleSecondaries().
const std::vector<G4double>* G4DNACPA100IonisationModel::fpMolWaterDensity private
Definition at line 104 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNACPA100IonisationModel.hh
Referenced by G4DNACPA100IonisationModel(), and Initialise().
std::map<G4String,G4double,std::less<G4String> > G4DNACPA100IonisationModel::highEnergyLimit private
Definition at line 110 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DNACPA100IonisationModel.hh
G4bool G4DNACPA100IonisationModel::isInitialised private
Definition at line 112 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4DNACPA100IonisationModel.hh
Referenced by Initialise().
std::map<G4String,G4double,std::less<G4String> > G4DNACPA100IonisationModel::lowEnergyLimit private
Definition at line 109 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4DNACPA100IonisationModel.hh
G4bool G4DNACPA100IonisationModel::statCode private
Definition at line 98 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4DNACPA100IonisationModel.hh
Referenced by G4DNACPA100IonisationModel(), SampleSecondaries(), and SelectStationary().
MapData G4DNACPA100IonisationModel::tableData private
Definition at line 121 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4DNACPA100IonisationModel.hh
Referenced by CrossSectionPerVolume(), Initialise(), RandomSelect(), and ~G4DNACPA100IonisationModel().
MapFile G4DNACPA100IonisationModel::tableFile private
Definition at line 118 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4DNACPA100IonisationModel.hh
Referenced by Initialise().
G4bool G4DNACPA100IonisationModel::useDcs private
Definition at line 101 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4DNACPA100IonisationModel.hh
Referenced by G4DNACPA100IonisationModel(), Initialise(), Interpolate(), SampleSecondaries(), and SelectUseDcs().
G4int G4DNACPA100IonisationModel::verboseLevel private
Definition at line 113 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4DNACPA100IonisationModel.hh
Referenced by CrossSectionPerVolume(), G4DNACPA100IonisationModel(), Initialise(), and SampleSecondaries().
G4DNACPA100WaterIonisationStructure G4DNACPA100IonisationModel::waterStructure private
Definition at line 125 of file G4DNACPA100IonisationModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4DNACPA100IonisationModel.hh
Referenced by DifferentialCrossSection(), RandomizeEjectedElectronEnergy(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNACPA100IonisationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNACPA100IonisationModel.cc