ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyRBE.cc File Reference
HadrontherapyRBE.cc File Reference
#include "HadrontherapyRBE.hh"
#include "HadrontherapyMatrix.hh"
#include "G4UnitsTable.hh"
#include "G4SystemOfUnits.hh"
#include "G4GenericMessenger.hh"
#include "G4Pow.hh"
#include <fstream>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <algorithm>
#include <sstream>
#include <numeric>
Macros
#define width 15L
Functions
vector< G4String > split (const G4String &line, const G4String &delimiter)
Split string into parts using a delimiter.
Variables
const std::map< G4String, G4int > elements
Macro Definition Documentation
#define width 15L
Definition at line 43 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 43 of file HadrontherapyRBE.cc
Referenced by HadrontherapyRBE::StoreAlphaAndBeta(), and HadrontherapyRBE::StoreRBE().
Function Documentation
vector<G4String> split (const G4String & line, const G4String & delimiter)
Split string into parts using a delimiter.
Parameters
line a string to be splitted
delimiter a string to be looked for
Usage: Help function for reading CSV Also remove spaces and quotes around. Note: If delimiter is inside a string, the function fails!
Definition at line 120 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 120 of file HadrontherapyRBE.cc
References G4String::both, pos(), and G4String::strip().
Referenced by PHNodeIterator::cd(), Acts::detail::LoopProtection< path_arborter_t >::debugLog(), Acts::DirectNavigator::debugLog(), Acts::Propagator< stepper_t, navigator_t >::debugLog(), Acts::Navigator::debugLog(), make_release::get_branches(), release_notes::get_label_groups(), AllSiliconTrackerDetector::InsertVolumes(), HadrontherapyRBE::LoadLEMTable(), check_license::main(), PHNodeIOManager::NodeExist(), parseArgs(), rangeParser(), mcscore::read_next_vertex(), Fun4AllDstInputManager::ReadNextEventSyncObject(), PHNodeIOManager::reconstructNodeTree(), FW::RootMaterialDecorator::RootMaterialDecorator(), incremental_prev_tag::split_version(), PHIODataNode< T >::SplitLevel(), Acts::Test::testObjString(), Acts::Test::testPlyString(), and make_release::zenodo().
Variable Documentation
const std::map<G4String, G4int> elements
Initial value:
= {
    {"H", 1},
    {"He", 2},
    {"Li", 3},
    {"Be", 4},
    {"B", 5},
    {"C", 6},
    {"N", 7},
    {"O", 8},
    {"F", 9},
    {"Ne", 10}
}
Definition at line 48 of file HadrontherapyRBE.cc.
View newest version in sPHENIX GitHub at line 48 of file HadrontherapyRBE.cc
Referenced by BOOST_AUTO_TEST_CASE(), F04Materials::CreateMaterials(), WLSMaterials::CreateMaterials(), XrayFluoNistMaterials::CreateMaterials(), kdfinder::find_vertex_seeds(), HadrontherapyRBE::LoadLEMTable(), G4GDMLRead::StripNames(), Acts::Test::testPlyString(), and FW::Geant4::MMSteppingAction::UserSteppingAction().