ECCE @ EIC Software: G4UnitDefinition Class Reference
G4UnitDefinition Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4UnitsTable.hh>
Public Member Functions
G4UnitDefinition (const G4String &name, const G4String &symbol, const G4String &category, G4double value)
~G4UnitDefinition ()
G4bool operator== (const G4UnitDefinition &) const
G4bool operator!= (const G4UnitDefinition &) const
const G4String & GetName () const
const G4String & GetSymbol () const
G4double GetValue () const
void PrintDefinition ()
Static Public Member Functions
static void BuildUnitsTable ()
static void PrintUnitsTable ()
static void ClearUnitsTable ()
static G4UnitsTable & GetUnitsTable ()
static G4bool IsUnitDefined (const G4String &)
static G4double GetValueOf (const G4String &)
static G4String GetCategory (const G4String &)
Private Member Functions
G4UnitDefinition (const G4UnitDefinition &)
G4UnitDefinition & operator= (const G4UnitDefinition &)
Private Attributes
G4String Name
G4String SymbolName
G4double Value
size_t CategoryIndex
Static Private Attributes
static G4ThreadLocal G4UnitsTable * pUnitsTable = 0
static G4ThreadLocal G4bool unitsTableDestroyed = false
Detailed Description
Definition at line 80 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UnitsTable.hh
Constructor & Destructor Documentation
G4UnitDefinition::G4UnitDefinition (const G4String & name, const G4String & symbol, const G4String & category, G4double value)
Definition at line 76 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 76 of file G4UnitsTable.cc
References CategoryIndex, FatalException, G4Exception(), GetName(), G4Threading::IsMasterThread(), pUnitsTable, and unitsTableDestroyed.
Referenced by BuildUnitsTable().
G4UnitDefinition::~G4UnitDefinition ()
Definition at line 116 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 116 of file G4UnitsTable.cc
G4UnitDefinition::G4UnitDefinition (const G4UnitDefinition & right) private
Definition at line 121 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 121 of file G4UnitsTable.cc
References right.
Member Function Documentation
void G4UnitDefinition::BuildUnitsTable () static
Definition at line 239 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 239 of file G4UnitsTable.cc
References ampere, angstrom, atmosphere, bar, barn, becquerel, centimeter, centimeter2, centimeter3, cL, cm, cm2, cm3, coulomb, curie, degree, dL, electronvolt, eplus, eV, fermi, Acts::UnitConstants::g, G4UnitDefinition(), gauss, GeV, gigaelectronvolt, gram, gray, hep_pascal, hertz, joule, kelvin, keV, kg, kiloelectronvolt, kilogauss, kilogram, kilohertz, kilometer, kilometer2, kilometer3, kilovolt, liter, m, m3, megaelectronvolt, megahertz, megavolt, meter, meter2, meter3, MeV, mg, microampere, microbarn, micrometer, microsecond, milliampere, millibarn, milligram, millimeter, millimeter2, millimeter3, milliradian, millisecond, mL, mole, nanoampere, nanobarn, nanometer, nanosecond, newton, parsec, petaelectronvolt, picobarn, picosecond, radian, second, steradian, teraelectronvolt, tesla, volt, watt, and weber.
Referenced by export_G4UnitsTable(), GetUnitsTable(), G4DimensionedTypeUtils::GetUnitValue(), and main().
void G4UnitDefinition::ClearUnitsTable () static
Definition at line 402 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 402 of file G4UnitsTable.cc
References G4Threading::IsMasterThread(), pUnitsTable, and unitsTableDestroyed.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
G4String G4UnitDefinition::GetCategory (const G4String & str) static
Definition at line 207 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 207 of file G4UnitsTable.cc
References FatalException, G4Exception(), GetUnitsTable(), message(), and pUnitsTable.
Referenced by G4GDMLReadMaterials::AtomRead(), G4GDMLReadParamvol::Box_dimensionsRead(), G4GDMLReadSolids::BoxRead(), G4UIcommand::CategoryOf(), G4VPrimitiveScorer::CheckAndSetUnit(), G4GDMLReadParamvol::Cone_dimensionsRead(), G4GDMLReadSolids::ConeRead(), G4GDMLReadSolids::CutTubeRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadMaterials::DRead(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadParamvol::Ellipsoid_dimensionsRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), export_G4UnitsTable(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4GDMLReadParamvol::Hype_dimensionsRead(), G4GDMLReadSolids::HypeRead(), G4GDMLParser::ImportRegions(), G4GDMLReadMaterials::MEERead(), G4GDMLReadParamvol::Orb_dimensionsRead(), G4GDMLReadSolids::OrbRead(), G4GDMLReadParamvol::Para_dimensionsRead(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLReadSolids::ParaRead(), G4GDMLReadParamvol::Polycone_dimensionsRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLReadDefine::PositionRead(), G4GDMLReadMaterials::PRead(), G4VVisCommand::ProvideValueOfUnit(), G4GDMLReadSolids::QuadrangularRead(), G4GDMLReadStructure::QuantityRead(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadDefine::RotationRead(), G4GDMLReadParamvol::Sphere_dimensionsRead(), G4GDMLReadSolids::SphereRead(), G4AttCheck::Standard(), G4GDMLReadSolids::TetRead(), G4GDMLReadParamvol::Torus_dimensionsRead(), G4GDMLReadSolids::TorusRead(), G4GDMLReadParamvol::Trap_dimensionsRead(), G4GDMLReadSolids::TrapRead(), G4GDMLReadParamvol::Trd_dimensionsRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadMaterials::TRead(), G4GDMLReadSolids::TriangularRead(), G4GDMLReadParamvol::Tube_dimensionsRead(), G4GDMLReadSolids::TubeRead(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), and G4GDMLReadSolids::XtruRead().
const G4String& G4UnitDefinition::GetName () const inline
Referenced by export_G4UnitsTable(), G4UnitDefinition(), and G4DimensionedTypeUtils::HasName::operator()().
const G4String& G4UnitDefinition::GetSymbol () const inline
Referenced by export_G4UnitsTable(), and G4DimensionedTypeUtils::HasName::operator()().
G4UnitsTable & G4UnitDefinition::GetUnitsTable () static
Definition at line 156 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 156 of file G4UnitsTable.cc
References BuildUnitsTable(), G4Threading::IsMasterThread(), and pUnitsTable.
Referenced by export_G4UnitsTable(), G4AttCheck::G4AttCheck(), G4BestUnit::G4BestUnit(), G4GDMLRead::G4GDMLRead(), G4RunManagerKernel::G4RunManagerKernel(), GetCategory(), G4DimensionedTypeUtils::GetUnitValue(), GetValueOf(), G4RunManagerKernel::InitializePhysics(), IsUnitDefined(), operator<<(), G4RunManagerKernel::RunInitialization(), G4RunManagerKernel::SetupPhysics(), and G4UIcommand::UnitsList().
G4double G4UnitDefinition::GetValue () const inline
Referenced by export_G4UnitsTable().
G4double G4UnitDefinition::GetValueOf (const G4String & str) static
Definition at line 186 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 186 of file G4UnitsTable.cc
References FatalException, G4Exception(), GetUnitsTable(), and message().
Referenced by G4GDMLReadMaterials::AtomRead(), G4GDMLReadParamvol::Box_dimensionsRead(), G4GDMLReadSolids::BoxRead(), G4VPrimitiveScorer::CheckAndSetUnit(), G4GDMLReadParamvol::Cone_dimensionsRead(), G4GDMLReadSolids::ConeRead(), G4GDMLReadSolids::CutTubeRead(), G4GDMLReadStructure::DivisionvolRead(), G4GDMLReadMaterials::DRead(), G4GDMLReadSolids::ElconeRead(), G4GDMLReadParamvol::Ellipsoid_dimensionsRead(), G4GDMLReadSolids::EllipsoidRead(), G4GDMLReadSolids::EltubeRead(), export_G4UnitsTable(), G4ScoreQuantityMessenger::FParticleWithEnergyCommand(), G4GDMLReadSolids::GenericPolyconeRead(), G4GDMLReadSolids::GenericPolyhedraRead(), G4GDMLReadSolids::GenTrapRead(), G4tgrUtils::GetDouble(), G4Analysis::GetUnitValue(), G4GDMLReadParamvol::Hype_dimensionsRead(), G4GDMLReadSolids::HypeRead(), G4GDMLParser::ImportRegions(), G4GDMLReadMaterials::MEERead(), G4GDMLReadParamvol::Orb_dimensionsRead(), G4GDMLReadSolids::OrbRead(), G4GDMLReadParamvol::Para_dimensionsRead(), G4GDMLReadSolids::ParaboloidRead(), G4GDMLReadSolids::ParaRead(), G4GDMLReadParamvol::Polycone_dimensionsRead(), G4GDMLReadSolids::PolyconeRead(), G4GDMLReadParamvol::Polyhedra_dimensionsRead(), G4GDMLReadSolids::PolyhedraRead(), G4GDMLReadDefine::PositionRead(), G4GDMLReadMaterials::PRead(), G4VVisCommand::ProvideValueOfUnit(), G4GDMLReadSolids::QuadrangularRead(), G4GDMLReadStructure::QuantityRead(), G4GDMLReadDefine::QuantityRead(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadDefine::RotationRead(), HistoManager::SetHisto(), G4ScoreQuantityMessenger::SetNewValue(), RMC01AnalysisManagerMessenger::SetNewValue(), G4AdjointSimMessenger::SetNewValue(), G4GDMLReadParamvol::Sphere_dimensionsRead(), G4GDMLReadSolids::SphereRead(), G4AttCheck::Standard(), G4GDMLReadSolids::TetRead(), G4GDMLReadParamvol::Torus_dimensionsRead(), G4GDMLReadSolids::TorusRead(), G4GDMLReadParamvol::Trap_dimensionsRead(), G4GDMLReadSolids::TrapRead(), G4GDMLReadParamvol::Trd_dimensionsRead(), G4GDMLReadSolids::TrdRead(), G4GDMLReadMaterials::TRead(), G4GDMLReadSolids::TriangularRead(), G4GDMLReadParamvol::Tube_dimensionsRead(), G4GDMLReadSolids::TubeRead(), G4GDMLReadSolids::TwistedboxRead(), G4GDMLReadSolids::TwistedtrapRead(), G4GDMLReadSolids::TwistedtrdRead(), G4GDMLReadSolids::TwistedtubsRead(), G4UIcommand::ValueOf(), G4GDMLReadDefine::VectorRead(), and G4GDMLReadSolids::XtruRead().
G4bool G4UnitDefinition::IsUnitDefined (const G4String & str) static
Definition at line 169 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 169 of file G4UnitsTable.cc
References GetUnitsTable().
Referenced by G4VVisCommand::ConvertToDoublePair(), and G4VVisCommand::ProvideValueOfUnit().
G4bool G4UnitDefinition::operator!= (const G4UnitDefinition & right) const
Definition at line 149 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 149 of file G4UnitsTable.cc
G4UnitDefinition & G4UnitDefinition::operator= (const G4UnitDefinition & right) private
Definition at line 128 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 128 of file G4UnitsTable.cc
References CategoryIndex, Name, SymbolName, and Value.
G4bool G4UnitDefinition::operator== (const G4UnitDefinition & right) const
Definition at line 142 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 142 of file G4UnitsTable.cc
void G4UnitDefinition::PrintDefinition ()
Definition at line 229 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 229 of file G4UnitsTable.cc
References CategoryIndex, G4cout, G4endl, Name, SymbolName, and Value.
Referenced by export_G4UnitsTable().
void G4UnitDefinition::PrintUnitsTable () static
Definition at line 390 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 390 of file G4UnitsTable.cc
References G4cout, and pUnitsTable.
Referenced by export_G4UnitsTable(), FW::Geant4::MMPrimaryGeneratorAction::MMPrimaryGeneratorAction(), and G4UnitsMessenger::SetNewValue().
Member Data Documentation
size_t G4UnitDefinition::CategoryIndex private
Definition at line 125 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 125 of file G4UnitsTable.hh
Referenced by G4UnitDefinition(), operator=(), and PrintDefinition().
G4String G4UnitDefinition::Name private
Definition at line 118 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 118 of file G4UnitsTable.hh
Referenced by operator=(), and PrintDefinition().
G4ThreadLocal G4UnitsTable * G4UnitDefinition::pUnitsTable = 0 static private
Definition at line 122 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 122 of file G4UnitsTable.hh
Referenced by ClearUnitsTable(), G4UnitDefinition(), GetCategory(), GetUnitsTable(), and PrintUnitsTable().
G4String G4UnitDefinition::SymbolName private
Definition at line 119 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 119 of file G4UnitsTable.hh
Referenced by operator=(), and PrintDefinition().
G4ThreadLocal G4bool G4UnitDefinition::unitsTableDestroyed = false static private
Definition at line 123 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 123 of file G4UnitsTable.hh
Referenced by ClearUnitsTable(), and G4UnitDefinition().
G4double G4UnitDefinition::Value private
Definition at line 120 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 120 of file G4UnitsTable.hh
Referenced by operator=(), and PrintDefinition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4UnitsTable.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4UnitsTable.cc