ECCE @ EIC Software: PerspectiveVisAction Class Reference
PerspectiveVisAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/visualization/perspective/include/PerspectiveVisAction.hh>
Public Member Functions
PerspectiveVisAction ()
void SetOptionString (const G4String &optionString)
void SetScene (const G4String &scene)
virtual void Draw ()
Public Member Functions inherited from G4VUserVisAction
G4VUserVisAction ()
virtual ~G4VUserVisAction ()
void operator() (G4VGraphicsScene &scene, const G4Transform3D &trans, const G4ModelingParameters *pMP)
Private Member Functions
void ExtendedDraw (const G4VSolid &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())
void RoomAndChair ()
void Chair (const G4VisAttributes &, const G4Transform3D &)
Private Attributes
G4VVisManager * fpVisManager
G4String fOptionString
G4String fScene
G4double fRoomX
G4double fRoomY
G4double fRoomZ
G4double fWindowX
G4double fWindowY
G4double fWindowZ
G4double fWindowSillHeight
G4double fWindowOffset
G4double fDoorFrameX
G4double fDoorFrameY
G4double fDoorFrameZ
G4double fDoorFrameOffset
G4double fDoorX
G4double fDoorY
G4double fDoorZ
G4double fChairX
G4double fChairY
G4double fChairZ
G4double fChairSeat
G4double fChairThickness
Additional Inherited Members
Protected Attributes inherited from G4VUserVisAction
G4VGraphicsScene * fpSceneHandler
const G4Transform3D * fpTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 49 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 49 of file PerspectiveVisAction.hh
Constructor & Destructor Documentation
PerspectiveVisAction::PerspectiveVisAction ()
Definition at line 45 of file PerspectiveVisAction.cc.
View newest version in sPHENIX GitHub at line 45 of file PerspectiveVisAction.cc
Member Function Documentation
void PerspectiveVisAction::Chair (const G4VisAttributes & visAtts, const G4Transform3D & transform) private
Definition at line 144 of file PerspectiveVisAction.cc.
View newest version in sPHENIX GitHub at line 144 of file PerspectiveVisAction.cc
Referenced by RoomAndChair().
void PerspectiveVisAction::Draw () virtual
Implements G4VUserVisAction.
Definition at line 76 of file PerspectiveVisAction.cc.
View newest version in sPHENIX GitHub at line 76 of file PerspectiveVisAction.cc
References fpVisManager, fScene, G4VVisManager::GetConcreteInstance(), and RoomAndChair().
void PerspectiveVisAction::ExtendedDraw (const G4VSolid & solid, const G4VisAttributes & visAtts, const G4Transform3D & objectTransformation = G4Transform3D()) private
Definition at line 172 of file PerspectiveVisAction.cc.
View newest version in sPHENIX GitHub at line 172 of file PerspectiveVisAction.cc
References A(), kdfinder::abs(), HepPolyhedron::GetNextEdge(), HepPolyhedron::GetNextFacet(), G4VSolid::GetPolyhedron(), m, n, G4Visible::SetVisAttributes(), HepGeom::BasicVector3D< T >::unit(), v1, v2, X, x, HepGeom::BasicVector3D< T >::x(), Y, HepGeom::BasicVector3D< T >::y(), y, Z, HepGeom::BasicVector3D< T >::z(), and z.
Referenced by RoomAndChair().
void PerspectiveVisAction::RoomAndChair () private
Definition at line 92 of file PerspectiveVisAction.cc.
View newest version in sPHENIX GitHub at line 92 of file PerspectiveVisAction.cc
References A(), B(), C(), Chair(), G4Colour::Cyan(), D(), deg, E, ExtendedDraw(), fChairY, fDoorFrameOffset, fDoorFrameX, fDoorFrameY, fDoorFrameZ, fDoorX, fDoorY, fDoorZ, fRoomX, fRoomY, fRoomZ, fWindowOffset, fWindowSillHeight, fWindowX, fWindowY, fWindowZ, G4Colour::Red(), and G4VisAttributes::SetForceWireframe().
Referenced by Draw().
void PerspectiveVisAction::SetOptionString (const G4String & optionString) inline
Definition at line 52 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PerspectiveVisAction.hh
References fOptionString.
void PerspectiveVisAction::SetScene (const G4String & scene) inline
Definition at line 54 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PerspectiveVisAction.hh
References fScene.
Member Data Documentation
G4double PerspectiveVisAction::fChairSeat private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
G4double PerspectiveVisAction::fChairThickness private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
G4double PerspectiveVisAction::fChairX private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
G4double PerspectiveVisAction::fChairY private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fChairZ private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
G4double PerspectiveVisAction::fDoorFrameOffset private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fDoorFrameX private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fDoorFrameY private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fDoorFrameZ private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fDoorX private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fDoorY private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fDoorZ private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4String PerspectiveVisAction::fOptionString private
Definition at line 63 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 63 of file PerspectiveVisAction.hh
Referenced by SetOptionString().
G4VVisManager* PerspectiveVisAction::fpVisManager private
Definition at line 62 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 62 of file PerspectiveVisAction.hh
Referenced by Draw().
G4double PerspectiveVisAction::fRoomX private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fRoomY private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fRoomZ private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4String PerspectiveVisAction::fScene private
Definition at line 64 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 64 of file PerspectiveVisAction.hh
Referenced by Draw(), and SetScene().
G4double PerspectiveVisAction::fWindowOffset private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fWindowSillHeight private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fWindowX private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fWindowY private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
G4double PerspectiveVisAction::fWindowZ private
Definition at line 65 of file PerspectiveVisAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PerspectiveVisAction.hh
Referenced by RoomAndChair().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/visualization/perspective/include/PerspectiveVisAction.hh
geant4/tree/geant4-10.6-release/examples/extended/visualization/perspective/src/PerspectiveVisAction.cc