ECCE @ EIC Software: G4tgbRotationMatrix Class Reference
G4tgbRotationMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbRotationMatrix.hh>
Public Member Functions
G4tgbRotationMatrix ()
~G4tgbRotationMatrix ()
G4tgbRotationMatrix (G4tgrRotationMatrix *tgr)
G4RotationMatrix * BuildG4RotMatrix ()
G4RotationMatrix * BuildG4RotMatrixFrom3 (std::vector< G4double > &values)
G4RotationMatrix * BuildG4RotMatrixFrom6 (std::vector< G4double > &values)
G4RotationMatrix * BuildG4RotMatrixFrom9 (std::vector< G4double > &values)
G4String GetName ()
Private Attributes
G4tgrRotationMatrix * theTgrRM
Detailed Description
Definition at line 51 of file G4tgbRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 51 of file G4tgbRotationMatrix.hh
Constructor & Destructor Documentation
G4tgbRotationMatrix::G4tgbRotationMatrix ()
Definition at line 42 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 42 of file G4tgbRotationMatrix.cc
G4tgbRotationMatrix::~G4tgbRotationMatrix ()
Definition at line 49 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgbRotationMatrix.cc
G4tgbRotationMatrix::G4tgbRotationMatrix (G4tgrRotationMatrix * tgr)
Definition at line 55 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgbRotationMatrix.cc
Member Function Documentation
G4RotationMatrix * G4tgbRotationMatrix::BuildG4RotMatrix ()
Definition at line 62 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 62 of file G4tgbRotationMatrix.cc
References BuildG4RotMatrixFrom3(), BuildG4RotMatrixFrom6(), BuildG4RotMatrixFrom9(), G4UIcommand::ConvertToString(), FatalException, G4Exception(), G4tgrRotationMatrix::GetValues(), theTgrRM, and Acts::Test::values.
Referenced by G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix().
G4RotationMatrix * G4tgbRotationMatrix::BuildG4RotMatrixFrom3 (std::vector< G4double > & values)
Definition at line 87 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 87 of file G4tgbRotationMatrix.cc
References G4cout, G4endl, GetName(), G4tgrMessenger::GetVerboseLevel(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), and CLHEP::HepRotation::rotateZ().
Referenced by BuildG4RotMatrix().
G4RotationMatrix * G4tgbRotationMatrix::BuildG4RotMatrixFrom6 (std::vector< G4double > & values)
Definition at line 109 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 109 of file G4tgbRotationMatrix.cc
References G4cout, G4endl, GetName(), G4tgrMessenger::GetVerboseLevel(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by BuildG4RotMatrix().
G4RotationMatrix * G4tgbRotationMatrix::BuildG4RotMatrixFrom9 (std::vector< G4double > & values)
Definition at line 149 of file G4tgbRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 149 of file G4tgbRotationMatrix.cc
References G4cout, G4endl, GetName(), G4tgrMessenger::GetVerboseLevel(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by BuildG4RotMatrix().
G4String G4tgbRotationMatrix::GetName (void) inline
Definition at line 68 of file G4tgbRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgbRotationMatrix.hh
References G4tgrRotationMatrix::GetName(), and theTgrRM.
Referenced by BuildG4RotMatrixFrom3(), BuildG4RotMatrixFrom6(), BuildG4RotMatrixFrom9(), and G4tgbRotationMatrixMgr::CopyRotMats().
Member Data Documentation
G4tgrRotationMatrix* G4tgbRotationMatrix::theTgrRM private
Definition at line 72 of file G4tgbRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgbRotationMatrix.hh
Referenced by BuildG4RotMatrix(), and GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbRotationMatrix.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbRotationMatrix.cc