ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4GIDI_mass.cc File Reference
G4GIDI_mass.cc File Reference
#include <string.h>
#include <statusMessageReporting.h>
#include "G4GIDI_mass.hh"
#include "G4GIDI_Misc.hh"
Classes
struct ZAMass
Functions
double G4GIDI_targetMass (const char *targetSymbol)
double G4GIDI_Z_AMass (int iZ, int iA)
Variables
static struct ZAMass ZAMasses []
Function Documentation
double G4GIDI_targetMass (const char * targetSymbol)
Definition at line 875 of file G4GIDI_mass.cc.
View newest version in sPHENIX GitHub at line 875 of file G4GIDI_mass.cc
References mass, ZAMass::mass, n, ZAMass::symbol, and ZAMasses.
Referenced by G4GIDI_Z_AMass(), and G4GIDI_target::init().
double G4GIDI_Z_AMass (int iZ, int iA)
Definition at line 891 of file G4GIDI_mass.cc.
View newest version in sPHENIX GitHub at line 891 of file G4GIDI_mass.cc
References G4GIDI_Misc_Z_A_m_ToName(), G4GIDI_targetMass(), mass, and smr_freeMemory().
Variable Documentation
struct ZAMass ZAMasses[] static
Definition at line 47 of file G4GIDI_mass.cc.
View newest version in sPHENIX GitHub at line 47 of file G4GIDI_mass.cc
Referenced by G4GIDI_targetMass().