ECCE @ EIC Software: G4ParticleHPInelasticBaseFS Class Reference
G4ParticleHPInelasticBaseFS Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInelasticBaseFS.hh>
Public Member Functions
G4ParticleHPInelasticBaseFS ()
virtual ~G4ParticleHPInelasticBaseFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &bit, G4ParticleDefinition *)
void BaseApply (const G4HadProjectile &theTrack, G4ParticleDefinition **theDefs, G4int nDef)
void InitGammas (G4double AR, G4double ZR)
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)=0
virtual G4ParticleHPFinalState * New ()=0
virtual G4double GetXsec (G4double anEnergy)
virtual G4ParticleHPVector * GetXsec ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Protected Attributes
G4ParticleHPVector * theXsection
G4ParticleHPEnergyDistribution * theEnergyDistribution
G4ParticleHPAngular * theAngularDistribution
G4ParticleHPEnAngCorrelation * theEnergyAngData
G4ParticleHPPhotonDist * theFinalStatePhotons
G4double theNuclearMassDifference
G4ParticleHPDeExGammas theGammas
G4String gammaPath
G4double Qvalue
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Detailed Description
Definition at line 43 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPInelasticBaseFS.hh
Constructor & Destructor Documentation
G4ParticleHPInelasticBaseFS::G4ParticleHPInelasticBaseFS () inline
Definition at line 47 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPInelasticBaseFS.hh
References G4ParticleHPFinalState::hasXsec, Qvalue, theAngularDistribution, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, theNuclearMassDifference, and theXsection.
virtual G4ParticleHPInelasticBaseFS::~G4ParticleHPInelasticBaseFS () inline virtual
Definition at line 61 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPInelasticBaseFS.hh
References theAngularDistribution, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, and theXsection.
Member Function Documentation
virtual G4HadFinalState* G4ParticleHPInelasticBaseFS::ApplyYourself (const G4HadProjectile & theTrack) pure virtual
Reimplemented from G4ParticleHPFinalState.
Implemented in G4ParticleHP2AInelasticFS, G4ParticleHP3NAInelasticFS, G4ParticleHP3NInelasticFS, G4ParticleHP3NPInelasticFS, G4ParticleHP4NInelasticFS, G4ParticleHP2N2AInelasticFS, G4ParticleHP2NAInelasticFS, G4ParticleHP2NDInelasticFS, G4ParticleHP2NInelasticFS, G4ParticleHP2NPInelasticFS, G4ParticleHP2PInelasticFS, G4ParticleHP3AInelasticFS, G4ParticleHPDAInelasticFS, G4ParticleHPN2AInelasticFS, G4ParticleHPN2PInelasticFS, G4ParticleHPN3AInelasticFS, G4ParticleHPNAInelasticFS, G4ParticleHPND2AInelasticFS, G4ParticleHPNDInelasticFS, G4ParticleHPNHe3InelasticFS, G4ParticleHPNPAInelasticFS, G4ParticleHPNPInelasticFS, G4ParticleHPNT2AInelasticFS, G4ParticleHPNTInelasticFS, G4ParticleHPNXInelasticFS, G4ParticleHPPAInelasticFS, G4ParticleHPPDInelasticFS, G4ParticleHPPTInelasticFS, G4ParticleHPD2AInelasticFS, and G4ParticleHPT2AInelasticFS.
void G4ParticleHPInelasticBaseFS::BaseApply (const G4HadProjectile & theTrack, G4ParticleDefinition ** theDefs, G4int nDef)
Definition at line 187 of file G4ParticleHPInelasticBaseFS.cc.
View newest version in sPHENIX GitHub at line 187 of file G4ParticleHPInelasticBaseFS.cc
References kdfinder::abs(), G4HadFinalState::AddSecondary(), G4ParticleHPFinalState::adjust_final_state(), G4Alpha::Alpha(), G4HadFinalState::Clear(), G4Deuteron::Deuteron(), CEMC_TOWER::emin, eps, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4HadProjectile::Get4Momentum(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), G4Nucleus::GetBiasedThermalNucleus(), G4NucleiProperties::GetBindingEnergy(), G4ParticleHPDeExGammas::GetDecayGammas(), G4HadProjectile::GetDefinition(), G4ReactionProduct::GetDefinition(), G4DynamicParticle::GetDefinition(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4ParticleHPDeExGammas::GetLevelEnergy(), G4ReactionProduct::GetMass(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4DynamicParticle::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4ParticleHPDeExGammas::GetNumberOfLevels(), G4HadFinalState::GetNumberOfSecondaries(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPAngular::GetTargetMass(), G4ParticleHPEnAngCorrelation::GetTargetMass(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalEnergy(), G4ParticleHPEnAngCorrelation::GetTotalMeanEnergy(), G4ParticleHPFinalState::HasFSData(), G4He3::He3(), G4ParticleHPNBodyPhaseSpace::Init(), CLHEP::keV, G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), maxA, CLHEP::MeV, G4Neutron::Neutron(), G4Proton::Proton(), G4Cache< VALTYPE >::Put(), Qvalue, G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPEnergyDistribution::Sample(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4VParticleHPEnergyAngular::SetProjectileRP(), G4ParticleHPAngular::SetProjectileRP(), G4ParticleHPEnAngCorrelation::SetProjectileRP(), G4VParticleHPEnergyAngular::SetQValue(), G4HadFinalState::SetStatusChange(), G4VParticleHPEnergyAngular::SetTarget(), G4ParticleHPAngular::SetTarget(), G4ParticleHPEnAngCorrelation::SetTarget(), G4ReactionProduct::SetTotalEnergy(), stopAndKill, theAngularDistribution, G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, theGammas, theNuclearMassDifference, G4ParticleHPFinalState::theProjectile, G4ParticleHPFinalState::theResult, CLHEP::Hep3Vector::theta(), theTarget, G4Triton::Triton(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and z1.
Referenced by G4ParticleHPD2AInelasticFS::ApplyYourself(), G4ParticleHPT2AInelasticFS::ApplyYourself(), G4ParticleHPPTInelasticFS::ApplyYourself(), G4ParticleHPPDInelasticFS::ApplyYourself(), G4ParticleHPPAInelasticFS::ApplyYourself(), G4ParticleHPNXInelasticFS::ApplyYourself(), G4ParticleHPNTInelasticFS::ApplyYourself(), G4ParticleHP2NDInelasticFS::ApplyYourself(), G4ParticleHPNPInelasticFS::ApplyYourself(), G4ParticleHP3AInelasticFS::ApplyYourself(), G4ParticleHPNHe3InelasticFS::ApplyYourself(), G4ParticleHPN2PInelasticFS::ApplyYourself(), G4ParticleHPN3AInelasticFS::ApplyYourself(), G4ParticleHPNAInelasticFS::ApplyYourself(), G4ParticleHPND2AInelasticFS::ApplyYourself(), G4ParticleHP2NInelasticFS::ApplyYourself(), G4ParticleHP2PInelasticFS::ApplyYourself(), G4ParticleHPDAInelasticFS::ApplyYourself(), G4ParticleHP2NPInelasticFS::ApplyYourself(), G4ParticleHPNT2AInelasticFS::ApplyYourself(), G4ParticleHPNDInelasticFS::ApplyYourself(), G4ParticleHPNPAInelasticFS::ApplyYourself(), G4ParticleHPN2AInelasticFS::ApplyYourself(), G4ParticleHP2NAInelasticFS::ApplyYourself(), G4ParticleHP2N2AInelasticFS::ApplyYourself(), G4ParticleHP3NInelasticFS::ApplyYourself(), G4ParticleHP2AInelasticFS::ApplyYourself(), G4ParticleHP3NAInelasticFS::ApplyYourself(), G4ParticleHP3NPInelasticFS::ApplyYourself(), and G4ParticleHP4NInelasticFS::ApplyYourself().
virtual G4double G4ParticleHPInelasticBaseFS::GetXsec (G4double anEnergy) inline virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 82 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPInelasticBaseFS.hh
References G4ParticleHPVector::GetY(), max, and theXsection.
virtual G4ParticleHPVector* G4ParticleHPInelasticBaseFS::GetXsec () inline virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 87 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPInelasticBaseFS.hh
References theXsection.
void G4ParticleHPInelasticBaseFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & bit, G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Reimplemented in G4ParticleHPN2AInelasticFS, G4ParticleHPN2PInelasticFS, G4ParticleHPN3AInelasticFS, G4ParticleHPNAInelasticFS, G4ParticleHPND2AInelasticFS, G4ParticleHPNDInelasticFS, G4ParticleHPNHe3InelasticFS, G4ParticleHPNPAInelasticFS, G4ParticleHPNPInelasticFS, G4ParticleHPNT2AInelasticFS, G4ParticleHPNTInelasticFS, G4ParticleHPNXInelasticFS, G4ParticleHPPAInelasticFS, G4ParticleHPPDInelasticFS, G4ParticleHPPTInelasticFS, and G4ParticleHPT2AInelasticFS.
Definition at line 77 of file G4ParticleHPInelasticBaseFS.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPInelasticBaseFS.cc
References kdfinder::abs(), CLHEP::eV, INPUTHEPMC::filename, G4cout, G4endl, gammaPath, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPFinalState::hasAnyData, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPEnergyDistribution::Init(), G4ParticleHPAngular::Init(), G4ParticleHPEnAngCorrelation::Init(), G4ParticleHPVector::Init(), G4ParticleHPPhotonDist::InitAngular(), G4ParticleHPPhotonDist::InitEnergies(), G4ParticleHPPhotonDist::InitMean(), G4ParticleHPPhotonDist::InitPartials(), INT_MAX, Qvalue, G4ParticleHPFinalState::SetAZMs(), theAngularDistribution, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, G4ParticleHPFinalState::theNames, G4ParticleHPFinalState::theNDLDataA, G4ParticleHPFinalState::theNDLDataZ, G4ParticleHPFinalState::theProjectile, theXsection, and G4INCL::CrossSections::total().
Referenced by G4ParticleHPD2AInelasticFS::Init(), G4ParticleHPT2AInelasticFS::Init(), G4ParticleHPPTInelasticFS::Init(), G4ParticleHPPDInelasticFS::Init(), G4ParticleHPPAInelasticFS::Init(), G4ParticleHPNXInelasticFS::Init(), G4ParticleHPNTInelasticFS::Init(), G4ParticleHP2NDInelasticFS::Init(), G4ParticleHPNPInelasticFS::Init(), G4ParticleHP3AInelasticFS::Init(), G4ParticleHPNHe3InelasticFS::Init(), G4ParticleHPN2PInelasticFS::Init(), G4ParticleHPN3AInelasticFS::Init(), G4ParticleHPNAInelasticFS::Init(), G4ParticleHPND2AInelasticFS::Init(), G4ParticleHP2NInelasticFS::Init(), G4ParticleHP2PInelasticFS::Init(), G4ParticleHPDAInelasticFS::Init(), G4ParticleHP2NPInelasticFS::Init(), G4ParticleHPNT2AInelasticFS::Init(), G4ParticleHPNDInelasticFS::Init(), G4ParticleHPNPAInelasticFS::Init(), G4ParticleHPN2AInelasticFS::Init(), G4ParticleHP2NAInelasticFS::Init(), G4ParticleHP2N2AInelasticFS::Init(), G4ParticleHP3NInelasticFS::Init(), G4ParticleHP2AInelasticFS::Init(), G4ParticleHP3NAInelasticFS::Init(), G4ParticleHP3NPInelasticFS::Init(), and G4ParticleHP4NInelasticFS::Init().
void G4ParticleHPInelasticBaseFS::InitGammas (G4double AR, G4double ZR)
Definition at line 51 of file G4ParticleHPInelasticBaseFS.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPInelasticBaseFS.cc
References eps, gammaPath, G4NucleiProperties::GetBindingEnergy(), in, G4ParticleHPDeExGammas::Init(), G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theGammas, and theNuclearMassDifference.
Referenced by G4ParticleHPD2AInelasticFS::Init(), G4ParticleHPT2AInelasticFS::Init(), G4ParticleHPPTInelasticFS::Init(), G4ParticleHPPDInelasticFS::Init(), G4ParticleHPPAInelasticFS::Init(), G4ParticleHPNXInelasticFS::Init(), G4ParticleHPNTInelasticFS::Init(), G4ParticleHP2NDInelasticFS::Init(), G4ParticleHPNPInelasticFS::Init(), G4ParticleHP3AInelasticFS::Init(), G4ParticleHPNHe3InelasticFS::Init(), G4ParticleHPN2PInelasticFS::Init(), G4ParticleHPN3AInelasticFS::Init(), G4ParticleHPNAInelasticFS::Init(), G4ParticleHPND2AInelasticFS::Init(), G4ParticleHP2NInelasticFS::Init(), G4ParticleHP2PInelasticFS::Init(), G4ParticleHPDAInelasticFS::Init(), G4ParticleHP2NPInelasticFS::Init(), G4ParticleHPNT2AInelasticFS::Init(), G4ParticleHPNDInelasticFS::Init(), G4ParticleHPNPAInelasticFS::Init(), G4ParticleHPN2AInelasticFS::Init(), G4ParticleHP2NAInelasticFS::Init(), G4ParticleHP2N2AInelasticFS::Init(), G4ParticleHP3NInelasticFS::Init(), G4ParticleHP2AInelasticFS::Init(), G4ParticleHP3NAInelasticFS::Init(), G4ParticleHP3NPInelasticFS::Init(), and G4ParticleHP4NInelasticFS::Init().
virtual G4ParticleHPFinalState* G4ParticleHPInelasticBaseFS::New () pure virtual
Implements G4ParticleHPFinalState.
Implemented in G4ParticleHP2AInelasticFS, G4ParticleHP3NAInelasticFS, G4ParticleHP3NInelasticFS, G4ParticleHP3NPInelasticFS, G4ParticleHP4NInelasticFS, G4ParticleHP2N2AInelasticFS, G4ParticleHP2NAInelasticFS, G4ParticleHP2NDInelasticFS, G4ParticleHP2NInelasticFS, G4ParticleHP2NPInelasticFS, G4ParticleHP2PInelasticFS, G4ParticleHP3AInelasticFS, G4ParticleHPDAInelasticFS, G4ParticleHPN2AInelasticFS, G4ParticleHPN2PInelasticFS, G4ParticleHPN3AInelasticFS, G4ParticleHPNAInelasticFS, G4ParticleHPND2AInelasticFS, G4ParticleHPNDInelasticFS, G4ParticleHPNHe3InelasticFS, G4ParticleHPNPAInelasticFS, G4ParticleHPNPInelasticFS, G4ParticleHPNT2AInelasticFS, G4ParticleHPNTInelasticFS, G4ParticleHPNXInelasticFS, G4ParticleHPPAInelasticFS, G4ParticleHPPDInelasticFS, G4ParticleHPPTInelasticFS, G4ParticleHPD2AInelasticFS, and G4ParticleHPT2AInelasticFS.
Member Data Documentation
G4String G4ParticleHPInelasticBaseFS::gammaPath protected
Definition at line 99 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ParticleHPInelasticBaseFS.hh
Referenced by Init(), and InitGammas().
G4double G4ParticleHPInelasticBaseFS::Qvalue protected
Definition at line 101 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), G4ParticleHPInelasticBaseFS(), and Init().
G4ParticleHPAngular* G4ParticleHPInelasticBaseFS::theAngularDistribution protected
Definition at line 93 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), G4ParticleHPInelasticBaseFS(), Init(), and ~G4ParticleHPInelasticBaseFS().
G4ParticleHPEnAngCorrelation* G4ParticleHPInelasticBaseFS::theEnergyAngData protected
Definition at line 94 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), G4ParticleHPInelasticBaseFS(), Init(), and ~G4ParticleHPInelasticBaseFS().
G4ParticleHPEnergyDistribution* G4ParticleHPInelasticBaseFS::theEnergyDistribution protected
Definition at line 92 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), G4ParticleHPInelasticBaseFS(), Init(), and ~G4ParticleHPInelasticBaseFS().
G4ParticleHPPhotonDist* G4ParticleHPInelasticBaseFS::theFinalStatePhotons protected
Definition at line 96 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), G4ParticleHPInelasticBaseFS(), Init(), and ~G4ParticleHPInelasticBaseFS().
G4ParticleHPDeExGammas G4ParticleHPInelasticBaseFS::theGammas protected
Definition at line 98 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), and InitGammas().
G4double G4ParticleHPInelasticBaseFS::theNuclearMassDifference protected
Definition at line 97 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPInelasticBaseFS.hh
Referenced by BaseApply(), G4ParticleHPInelasticBaseFS(), and InitGammas().
G4ParticleHPVector* G4ParticleHPInelasticBaseFS::theXsection protected
Definition at line 91 of file G4ParticleHPInelasticBaseFS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPInelasticBaseFS.hh
Referenced by G4ParticleHPInelasticBaseFS(), GetXsec(), Init(), and ~G4ParticleHPInelasticBaseFS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInelasticBaseFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPInelasticBaseFS.cc