ECCE @ EIC Software: G4ICRU73QOModel Class Reference
G4ICRU73QOModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4ICRU73QOModel.hh>
Public Member Functions
G4ICRU73QOModel (const G4ParticleDefinition *p=0, const G4String &nam="ICRU73QO")
~G4ICRU73QOModel ()=default
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) final
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) final
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void SetParticle (const G4ParticleDefinition *p)
void SetLowestKinEnergy (G4double val)
G4double DEDX (const G4Material *material, G4double kineticEnergy)
G4double DEDXPerElement (G4int Z, G4double kineticEnergy)
G4int GetNumberOfShells (G4int Z) const
G4double GetShellEnergy (G4int Z, G4int nbOfTheShell) const
G4double GetOscillatorEnergy (G4int Z, G4int nbOfTheShell) const
G4double GetShellStrength (G4int Z, G4int nbOfTheShell) const
G4double GetL0 (G4double normEnergy) const
G4double GetL1 (G4double normEnergy) const
G4double GetL2 (G4double normEnergy) const
G4ICRU73QOModel & operator= (const G4ICRU73QOModel &right)=delete
G4ICRU73QOModel (const G4ICRU73QOModel &)=delete
Private Attributes
const G4ParticleDefinition * particle
G4ParticleDefinition * theElectron
G4ParticleChangeForLoss * fParticleChange
G4DensityEffectData * denEffData
G4double mass
G4double charge
G4double chargeSquare
G4double massRate
G4double ratio
G4double lowestKinEnergy
G4bool isInitialised
G4int indexZ [100]
G4int sizeL0
G4int sizeL1
G4int sizeL2
Static Private Attributes
static const G4int NQOELEM = 26
static const G4int NQODATA = 130
static const G4int ZElementAvailable [NQOELEM]
static const G4int startElemIndex [NQOELEM]
static const G4int nbofShellsForElement [NQOELEM]
static const G4double ShellEnergy [NQODATA]
static const G4double SubShellOccupation [NQODATA]
static const G4double L0 [67][2]
static const G4double L1 [22][2]
static const G4double L2 [14][2]
static const G4double factorBethe [99]
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 70 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ICRU73QOModel.hh
Constructor & Destructor Documentation
G4ICRU73QOModel::G4ICRU73QOModel (const G4ParticleDefinition * p = 0, const G4String & nam = "ICRU73QO") explicit
Definition at line 66 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ICRU73QOModel.cc
References charge, chargeSquare, denEffData, G4Electron::Electron(), fParticleChange, indexZ, keV, lowestKinEnergy, mass, massRate, MeV, NQOELEM, ratio, G4VEmModel::SetHighEnergyLimit(), SetParticle(), sizeL0, sizeL1, sizeL2, theElectron, and ZElementAvailable.
G4ICRU73QOModel::~G4ICRU73QOModel () default
G4ICRU73QOModel::G4ICRU73QOModel (const G4ICRU73QOModel &) private delete
Member Function Documentation
G4double G4ICRU73QOModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 148 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 148 of file G4ICRU73QOModel.cc
References ComputeCrossSectionPerElectron(), and Acts::VectorHelpers::cross().
G4double G4ICRU73QOModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) final virtual
Definition at line 123 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ICRU73QOModel.cc
References chargeSquare, Acts::VectorHelpers::cross(), energy, G4Log(), mass, MaxSecondaryEnergy(), min, and CLHEP::twopi_mc2_rcl2.
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4ICRU73QOModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Reimplemented in G4ICRU73NoDeltaModel.
Definition at line 177 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 177 of file G4ICRU73QOModel.cc
References chargeSquare, DEDX(), G4Log(), G4InuclParticleNames::gam, G4Material::GetElectronDensity(), lowestKinEnergy, mass, massRate, MaxSecondaryEnergy(), SetParticle(), source.hepunit::twopi_mc2_rcl2, and x.
Referenced by G4ICRU73NoDeltaModel::ComputeDEDXPerVolume().
void G4ICRU73QOModel::CorrectionsAlongStep (const G4MaterialCutsCouple * , const G4DynamicParticle * , G4double & eloss, G4double & niel, G4double length) override virtual
Reimplemented from G4VEmModel.
Definition at line 405 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 405 of file G4ICRU73QOModel.cc
G4double G4ICRU73QOModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Reimplemented in G4ICRU73NoDeltaModel.
Definition at line 162 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 162 of file G4ICRU73QOModel.cc
References ComputeCrossSectionPerElectron(), Acts::VectorHelpers::cross(), and G4Material::GetElectronDensity().
G4double G4ICRU73QOModel::DEDX (const G4Material * material, G4double kineticEnergy) private
Definition at line 206 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 206 of file G4ICRU73QOModel.cc
References DEDXPerElement(), G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Element::GetZ(), and G4Element::GetZasInt().
Referenced by ComputeDEDXPerVolume().
G4double G4ICRU73QOModel::DEDXPerElement (G4int Z, G4double kineticEnergy) private
Definition at line 230 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 230 of file G4ICRU73QOModel.cc
References CLHEP::c_light, charge, chargeSquare, CLHEP::electron_mass_c2, factorBethe, CLHEP::fine_structure_const, G4InuclParticleNames::gam, GetL0(), GetL1(), GetL2(), GetNumberOfShells(), GetShellEnergy(), GetShellStrength(), max, min, source.hepunit::proton_mass_c2, CLHEP::twopi_mc2_rcl2, v, and Z.
Referenced by DEDX().
G4double G4ICRU73QOModel::GetL0 (G4double normEnergy) const private
Definition at line 346 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 346 of file G4ICRU73QOModel.cc
References L0, n, and sizeL0.
Referenced by DEDXPerElement().
G4double G4ICRU73QOModel::GetL1 (G4double normEnergy) const private
Definition at line 366 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 366 of file G4ICRU73QOModel.cc
References L1, n, and sizeL1.
Referenced by DEDXPerElement().
G4double G4ICRU73QOModel::GetL2 (G4double normEnergy) const private
Definition at line 386 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 386 of file G4ICRU73QOModel.cc
References L2, n, and sizeL2.
Referenced by DEDXPerElement().
G4int G4ICRU73QOModel::GetNumberOfShells (G4int Z) const private
Definition at line 298 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 298 of file G4ICRU73QOModel.cc
References G4AtomicShells::GetNumberOfShells(), indexZ, nbofShellsForElement, and Z.
Referenced by DEDXPerElement().
G4double G4ICRU73QOModel::GetOscillatorEnergy (G4int Z, G4int nbOfTheShell) const private
Definition at line 273 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 273 of file G4ICRU73QOModel.cc
References denEffData, G4Exp(), G4AtomicShells::GetBindingEnergy(), G4DensityEffectData::GetElementIndex(), G4AtomicShells::GetNumberOfElectrons(), G4DensityEffectData::GetPlasmaEnergy(), incremental_prev_tag::idx, kStateUndefined, and Z.
Referenced by GetShellEnergy().
G4double G4ICRU73QOModel::GetShellEnergy (G4int Z, G4int nbOfTheShell) const private
Definition at line 312 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 312 of file G4ICRU73QOModel.cc
References CLHEP::eV, GetOscillatorEnergy(), incremental_prev_tag::idx, indexZ, ShellEnergy, startElemIndex, and Z.
Referenced by DEDXPerElement().
G4double G4ICRU73QOModel::GetShellStrength (G4int Z, G4int nbOfTheShell) const private
Definition at line 329 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 329 of file G4ICRU73QOModel.cc
References G4AtomicShells::GetNumberOfElectrons(), incremental_prev_tag::idx, indexZ, startElemIndex, SubShellOccupation, and Z.
Referenced by DEDXPerElement().
void G4ICRU73QOModel::Initialise (const G4ParticleDefinition * p, const G4DataVector &) override virtual
Implements G4VEmModel.
Definition at line 99 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ICRU73QOModel.cc
References denEffData, fParticleChange, G4VEmModel::GetAngularDistribution(), G4Material::GetMaterialTable(), G4VEmModel::GetParticleChangeForLoss(), G4ParticleDefinition::GetParticleName(), isInitialised, particle, pname(), G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), SetParticle(), and G4VEmModel::UseAngularGeneratorFlag().
G4double G4ICRU73QOModel::MaxSecondaryEnergy (const G4ParticleDefinition * pd, G4double kinEnergy) final protected virtual
Reimplemented from G4VEmModel.
Definition at line 491 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 491 of file G4ICRU73QOModel.cc
References source.hepunit::electron_mass_c2, mass, particle, ratio, and SetParticle().
Referenced by ComputeCrossSectionPerElectron(), and ComputeDEDXPerVolume().
G4ICRU73QOModel& G4ICRU73QOModel::operator= (const G4ICRU73QOModel & right) private delete
void G4ICRU73QOModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 414 of file G4ICRU73QOModel.cc.
View newest version in sPHENIX GitHub at line 414 of file G4ICRU73QOModel.cc
References Acts::Test::delta, source.hepunit::electron_mass_c2, energy, f, fParticleChange, G4cout, G4endl, G4UniformRand, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), mass, mat, G4VEmModel::MaxSecondaryKinEnergy(), min, phi, CLHEP::Hep3Vector::rotateUz(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SelectRandomAtomNumber(), CLHEP::Hep3Vector::set(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), theElectron, twopi, CLHEP::Hep3Vector::unit(), G4VEmModel::UseAngularGeneratorFlag(), x, xmax, and Z.
void G4ICRU73QOModel::SetLowestKinEnergy (G4double val) inline private
Definition at line 208 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 208 of file G4ICRU73QOModel.hh
References lowestKinEnergy.
void G4ICRU73QOModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 196 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ICRU73QOModel.hh
References charge, chargeSquare, CLHEP::electron_mass_c2, CLHEP::eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, massRate, particle, CLHEP::proton_mass_c2, and ratio.
Referenced by ComputeDEDXPerVolume(), G4ICRU73QOModel(), Initialise(), and MaxSecondaryEnergy().
Member Data Documentation
G4double G4ICRU73QOModel::charge private
Definition at line 159 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ICRU73QOModel.hh
Referenced by DEDXPerElement(), G4ICRU73QOModel(), and SetParticle().
G4double G4ICRU73QOModel::chargeSquare private
Definition at line 160 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ICRU73QOModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), DEDXPerElement(), G4ICRU73QOModel(), and SetParticle().
G4DensityEffectData* G4ICRU73QOModel::denEffData private
Definition at line 156 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), GetOscillatorEnergy(), and Initialise().
const G4double G4ICRU73QOModel::factorBethe static private
Initial value:
= { 1.0,
0.9637, 0.9872, 0.9469, 0.9875, 0.91, 0.989, 0.9507, 0.9773, 0.8621, 0.979,
0.8357, 0.868, 0.9417, 0.9466, 0.8911, 0.905, 0.944, 0.9607, 0.928, 0.96,
0.9098, 0.976, 0.8425, 0.8099, 0.7858, 0.947, 0.7248, 0.9106, 0.9246, 0.6821,
0.7223, 0.9784, 0.774, 0.7953, 0.829, 0.9405, 0.8318, 0.8583, 0.8563, 0.8481,
0.8207, 0.9033, 0.8063, 0.7837, 0.7818, 0.744, 0.875, 0.7693, 0.7871, 0.8459,
0.8231, 0.8462, 0.853, 0.8736, 0.856, 0.8762, 0.8629, 0.8323, 0.8064, 0.7828,
0.7533, 0.7273, 0.7093, 0.7157, 0.6823, 0.6612, 0.6418, 0.6395, 0.6323, 0.6221,
0.6497, 0.6746, 0.8568, 0.8541, 0.6958, 0.6962, 0.7051, 0.863, 0.8588, 0.7226,
0.7454, 0.78, 0.7783, 0.7996, 0.8216, 0.8632, 0.8558, 0.8792, 0.8745, 0.8676,
0.8321, 0.8272, 0.7999, 0.7934, 0.7787, 0.7851, 0.7692, 0.7598}
Definition at line 190 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 190 of file G4ICRU73QOModel.hh
Referenced by DEDXPerElement().
G4ParticleChangeForLoss* G4ICRU73QOModel::fParticleChange private
Definition at line 155 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), Initialise(), and SampleSecondaries().
G4int G4ICRU73QOModel::indexZ[100] private
Definition at line 179 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), GetNumberOfShells(), GetShellEnergy(), and GetShellStrength().
G4bool G4ICRU73QOModel::isInitialised private
Definition at line 165 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ICRU73QOModel.hh
Referenced by Initialise().
const G4double G4ICRU73QOModel::L0 static private
Definition at line 182 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4ICRU73QOModel.hh
Referenced by GetL0().
const G4double G4ICRU73QOModel::L1 static private
Initial value:
=
{
  {0.00,       -0.000001},
  {0.10,       -0.00001},
  {0.20,       -0.00049},
  {0.30,       -0.00084},
  {0.40,        0.00085},
  {0.50,        0.00519},
  {0.60,        0.01198},
  {0.70,        0.02074},
  {0.80,        0.03133},
  {0.90,        0.04369},
  {1.00,        0.06035},
  {2.00,        0.24023},
  {3.00,        0.44284},
  {4.00,        0.62012},
  {5.00,        0.77031},
  {6.00,        0.90390},
  {7.00,        1.02705},
  {8.00,        1.10867},
  {9.00,        1.17546},
  {10.00,       1.21599},
  {15.00,        1.24349},
  {20.00,        1.16752}
}
Definition at line 183 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 183 of file G4ICRU73QOModel.hh
Referenced by GetL1().
const G4double G4ICRU73QOModel::L2 static private
Initial value:
=
{
  {0.00,        0.000001},
  {0.10,        0.00001},
  {0.20,        0.00000},
  {0.40,       -0.00120},
  {0.60,       -0.00036},
  {0.80,        0.00372},
  {1.00,        0.01298},
  {2.00,        0.08296},
  {4.00,        0.21953},
  {6.00,        0.23903},
  {8.00,        0.20893},
  {10.00,       0.10879},
  {20.00,      -0.88409},
  {40.00,      -1.13902}
}
Definition at line 184 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ICRU73QOModel.hh
Referenced by GetL2().
G4double G4ICRU73QOModel::lowestKinEnergy private
Definition at line 163 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ICRU73QOModel.hh
Referenced by ComputeDEDXPerVolume(), G4ICRU73QOModel(), and SetLowestKinEnergy().
G4double G4ICRU73QOModel::mass private
Definition at line 158 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ICRU73QOModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), G4ICRU73QOModel(), MaxSecondaryEnergy(), SampleSecondaries(), and SetParticle().
G4double G4ICRU73QOModel::massRate private
Definition at line 161 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ICRU73QOModel.hh
Referenced by ComputeDEDXPerVolume(), G4ICRU73QOModel(), and SetParticle().
const G4int G4ICRU73QOModel::nbofShellsForElement static private
Initial value:
=
  {1,1,2,3,3,3,3,4,5,4,
   5,5,5,5,6,4,6,6,
   7,6,6,8,7,7,9,9}
Definition at line 175 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ICRU73QOModel.hh
Referenced by GetNumberOfShells().
const G4int G4ICRU73QOModel::NQODATA = 130 static private
Definition at line 169 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ICRU73QOModel.hh
const G4int G4ICRU73QOModel::NQOELEM = 26 static private
Definition at line 168 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel().
const G4ParticleDefinition* G4ICRU73QOModel::particle private
Definition at line 153 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ICRU73QOModel.hh
Referenced by Initialise(), MaxSecondaryEnergy(), and SetParticle().
G4double G4ICRU73QOModel::ratio private
Definition at line 162 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), MaxSecondaryEnergy(), and SetParticle().
const G4double G4ICRU73QOModel::ShellEnergy static private
Initial value:
=
  {
    19.2,
    41.8,
    209.11, 21.68,
    486.2, 60.95, 23.43,
    732.61, 100.646, 23.550,
    965.1, 129.85, 31.60,
    1525.9, 234.9, 56.18,
    2701, 476.5, 150.42, 16.89,
    3206.1, 586.4, 186.8, 23.52, 14.91,
    5551.6, 472.43, 124.85, 22.332,
    8554.6, 850.58, 93.47, 39.19, 19.46,
    12254.7, 1279.29, 200.35, 49.19, 17.66,
    14346.9, 1532.28, 262.71, 74.37, 23.03,
    15438.5, 1667.96, 294.1, 70.69, 16.447,
    19022.1, 2150.79, 455.79, 179.87, 57.89, 20.95,
    24643, 2906.4, 366.85, 22.24,
    34394, 4365.3, 589.36, 129.42, 35.59, 18.42,
    43664.3, 5824.91, 909.79, 175.47, 54.89, 19.63,
    49948, 6818.2, 1036.1, 172.65, 70.89, 33.87, 14.54,
    58987, 8159, 1296.6, 356.75, 101.03, 16.52,
    88926, 18012, 3210, 575, 108.7, 30.8,
    115025.9, 17827.44, 3214.36, 750.41, 305.21, 105.50, 38.09, 21.25,
    128342, 20254, 3601.8, 608.1, 115.0, 42.75, 17.04,
    131872, 20903, 3757.4, 682.1, 105.2, 44.89, 17.575,
    154449, 25067, 5105.0, 987.44, 247.59, 188.1, 40.61, 19.2, 15.17,
    167282, 27868, 6022.7, 1020.4, 244.81, 51.33, 13, 11.06, 14.43
}
Definition at line 176 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ICRU73QOModel.hh
Referenced by GetShellEnergy().
G4int G4ICRU73QOModel::sizeL0 private
Definition at line 186 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 186 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), and GetL0().
G4int G4ICRU73QOModel::sizeL1 private
Definition at line 187 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 187 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), and GetL1().
G4int G4ICRU73QOModel::sizeL2 private
Definition at line 188 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), and GetL2().
const G4int G4ICRU73QOModel::startElemIndex static private
Initial value:
=
  {0,1,2,4,7,10,13,16,20,25,
   29,34,39,44,49,55,59,65,
   71,78,84,90,98,105,112,121}
Definition at line 174 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ICRU73QOModel.hh
Referenced by GetShellEnergy(), and GetShellStrength().
const G4double G4ICRU73QOModel::SubShellOccupation static private
Initial value:
=
  {
    1.000,
    2.000,
    1.930, 2.070,
    1.992, 1.841, 2.167,
    1.741, 1.680, 3.579,
    1.802, 1.849, 4.349,
    1.788, 2.028, 6.184,
    1.623, 2.147, 6.259, 2.971,
    1.631, 2.094, 6.588, 2.041, 1.646,
    1.535, 8.655, 1.706, 6.104,
    1.581, 8.358, 8.183, 2.000, 1.878,
    1.516, 8.325, 8.461, 6.579, 1.119,
    1.422, 7.81, 8.385, 8.216, 2.167,
    1.458, 8.049, 8.79, 9.695, 1.008,
    1.442, 7.791, 7.837, 10.122, 2.463, 2.345,
    1.645, 7.765, 19.192, 7.398,
    1.313, 6.409, 19.229, 8.633, 5.036, 1.380,
    1.295, 6.219, 18.751, 8.748, 10.184, 1.803,
    1.277, 6.099, 20.386, 8.011, 10.007, 2.272, 1.948,
    1.563, 6.312, 21.868, 5.762, 11.245, 7.250,
    0.9198, 6.5408, 18.9727, 24.9149, 15.0161, 6.6284,
    1.202, 5.582, 19.527, 18.741, 8.411, 14.387, 4.042, 2.108,
    1.159, 5.467, 18.802, 33.905, 8.300, 9.342, 1.025,
    1.124, 5.331, 18.078, 34.604, 8.127, 10.414, 1.322,
    2.000, 8.000, 18.000, 18.000, 14.000, 8.000, 10.000, 2.000, 2.000,
    2.000, 8.000, 18.000, 32.000, 18.000, 8.000, 2.000, 1.000, 3.000
}
Definition at line 177 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ICRU73QOModel.hh
Referenced by GetShellStrength().
G4ParticleDefinition* G4ICRU73QOModel::theElectron private
Definition at line 154 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel(), and SampleSecondaries().
const G4int G4ICRU73QOModel::ZElementAvailable static private
Initial value:
=
  {1,2,4,6,7,8,10,13,14,-18,
   22,26,28,29,32,36,42,47,
   50,54,73,74,78,79,82,92}
Definition at line 170 of file G4ICRU73QOModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ICRU73QOModel.hh
Referenced by G4ICRU73QOModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4ICRU73QOModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4ICRU73QOModel.cc