ECCE @ EIC Software: G4ErrorPropagationNavigator Class Reference
G4ErrorPropagationNavigator Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4ErrorPropagationNavigator.hh>
Public Member Functions
G4ErrorPropagationNavigator ()
~G4ErrorPropagationNavigator ()
G4double ComputeStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
G4double ComputeSafety (const G4ThreeVector &globalpoint, const G4double pProposedMaxLength=DBL_MAX, const G4bool keepState=true)
G4ThreeVector GetGlobalExitNormal (const G4ThreeVector &point, G4bool *valid)
G4double TargetSafetyFromPoint (const G4ThreeVector &pGlobalpoint)
Public Member Functions inherited from G4Navigator
G4Navigator ()
G4Navigator (const G4Navigator &)=delete
G4Navigator & operator= (const G4Navigator &)=delete
virtual ~G4Navigator ()
G4double CheckNextStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
virtual G4VPhysicalVolume * ResetHierarchyAndLocate (const G4ThreeVector &point, const G4ThreeVector &direction, const G4TouchableHistory &h)
virtual G4VPhysicalVolume * LocateGlobalPointAndSetup (const G4ThreeVector &point, const G4ThreeVector *direction=nullptr, const G4bool pRelativeSearch=true, const G4bool ignoreDirection=true)
virtual void LocateGlobalPointWithinVolume (const G4ThreeVector &position)
void LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector &position, const G4ThreeVector &direction, G4TouchableHandle &oldTouchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, const G4ThreeVector &direction, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void SetGeometricallyLimitedStep ()
virtual G4bool RecheckDistanceToCurrentBoundary (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double CurrentProposedStepLength, G4double *prDistance, G4double *prNewSafety=nullptr) const
G4VPhysicalVolume * GetWorldVolume () const
void SetWorldVolume (G4VPhysicalVolume *pWorld)
G4GRSVolume * CreateGRSVolume () const
G4GRSSolid * CreateGRSSolid () const
G4TouchableHistory * CreateTouchableHistory () const
G4TouchableHistory * CreateTouchableHistory (const G4NavigationHistory *) const
virtual G4TouchableHistoryHandle CreateTouchableHistoryHandle () const
virtual G4ThreeVector GetLocalExitNormal (G4bool *valid)
virtual G4ThreeVector GetLocalExitNormalAndCheck (const G4ThreeVector &point, G4bool *valid)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
G4bool IsActive () const
void Activate (G4bool flag)
G4bool EnteredDaughterVolume () const
G4bool ExitedMotherVolume () const
void CheckMode (G4bool mode)
G4bool IsCheckModeActive () const
void SetPushVerbosity (G4bool mode)
void PrintState () const
const G4AffineTransform & GetGlobalToLocalTransform () const
const G4AffineTransform GetLocalToGlobalTransform () const
G4AffineTransform GetMotherToDaughterTransform (G4VPhysicalVolume *dVolume, G4int dReplicaNo, EVolume dVolumeType)
void ResetStackAndState ()
G4int SeverityOfZeroStepping (G4int *noZeroSteps) const
G4ThreeVector GetCurrentLocalCoordinate () const
G4ThreeVector NetTranslation () const
G4RotationMatrix NetRotation () const
void EnableBestSafety (G4bool value=false)
G4VExternalNavigation * GetExternalNavigation () const
void SetExternalNavigation (G4VExternalNavigation *externalNav)
G4Navigator * Clone () const
Additional Inherited Members
Protected Member Functions inherited from G4Navigator
void SetSavedState ()
void RestoreSavedState ()
virtual void ResetState ()
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &rGlobPoint) const
G4ThreeVector ComputeLocalAxis (const G4ThreeVector &pVec) const
EVolume VolumeType (const G4VPhysicalVolume *pVol) const
EVolume CharacteriseDaughters (const G4LogicalVolume *pLog) const
G4int GetDaughtersRegularStructureId (const G4LogicalVolume *pLv) const
virtual void SetupHierarchy ()
G4bool CheckOverlapsIterative (G4VPhysicalVolume *vol)
Protected Attributes inherited from G4Navigator
G4double kCarTolerance
G4double fMinStep
G4double fSqTol
G4NavigationHistory fHistory
G4bool fEnteredDaughter
G4bool fExitedMother
G4bool fWasLimitedByGeometry = false
G4ThreeVector fStepEndPoint
G4ThreeVector fLastStepEndPointLocal
G4int fVerbose = 0
Detailed Description
Definition at line 44 of file G4ErrorPropagationNavigator.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ErrorPropagationNavigator.hh
Constructor & Destructor Documentation
G4ErrorPropagationNavigator::G4ErrorPropagationNavigator ()
Definition at line 44 of file G4ErrorPropagationNavigator.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ErrorPropagationNavigator.cc
G4ErrorPropagationNavigator::~G4ErrorPropagationNavigator ()
Definition at line 51 of file G4ErrorPropagationNavigator.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ErrorPropagationNavigator.cc
Member Function Documentation
G4double G4ErrorPropagationNavigator::ComputeSafety (const G4ThreeVector & globalpoint, const G4double pProposedMaxLength = DBL_MAX, const G4bool keepState = true) virtual
Reimplemented from G4Navigator.
Definition at line 154 of file G4ErrorPropagationNavigator.cc.
View newest version in sPHENIX GitHub at line 154 of file G4ErrorPropagationNavigator.cc
References G4Navigator::ComputeSafety(), min, and TargetSafetyFromPoint().
G4double G4ErrorPropagationNavigator::ComputeStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety) virtual
Reimplemented from G4Navigator.
Definition at line 58 of file G4ErrorPropagationNavigator.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ErrorPropagationNavigator.cc
References G4Navigator::ComputeStep(), DBL_MAX, G4ErrorTarget::Dump(), G4cout, G4endl, G4ErrorState_Propagating, G4ErrorState_TargetCloserThanBoundary, G4ErrorTarget::GetDistanceFromPoint(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorPropagatorData::GetTarget(), min, G4ErrorPropagatorData::SetState(), TargetSafetyFromPoint(), and G4ErrorPropagatorData::verbose().
G4ThreeVector G4ErrorPropagationNavigator::GetGlobalExitNormal (const G4ThreeVector & point, G4bool * valid) virtual
Reimplemented from G4Navigator.
Definition at line 169 of file G4ErrorPropagationNavigator.cc.
View newest version in sPHENIX GitHub at line 169 of file G4ErrorPropagationNavigator.cc
References G4ErrorTarget_CylindricalSurface, G4ErrorTarget_GeomVolume, G4ErrorTarget_PlaneSurface, G4ErrorTarget_TrkL, G4Exception(), G4ErrorTarget::GetDistanceFromPoint(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4Navigator::GetGlobalExitNormal(), G4ErrorSurfaceTarget::GetTangentPlane(), G4ErrorPropagatorData::GetTarget(), G4ErrorTarget::GetType(), JustWarning, G4Navigator::kCarTolerance, CLHEP::normal(), and HepGeom::Plane3D< T >::normal().
G4double G4ErrorPropagationNavigator::TargetSafetyFromPoint (const G4ThreeVector & pGlobalpoint)
Definition at line 133 of file G4ErrorPropagationNavigator.cc.
View newest version in sPHENIX GitHub at line 133 of file G4ErrorPropagationNavigator.cc
References DBL_MAX, G4ErrorTarget::GetDistanceFromPoint(), G4ErrorPropagatorData::GetErrorPropagatorData(), and G4ErrorPropagatorData::GetTarget().
Referenced by ComputeSafety(), and ComputeStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4ErrorPropagationNavigator.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4ErrorPropagationNavigator.cc