ECCE @ EIC Software: G4ITReaction Class Reference
G4ITReaction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITReaction.hh>
Public Member Functions
virtual ~G4ITReaction ()
G4Track * GetReactant (G4Track *trackA)
std::pair< G4Track *, G4Track * > GetReactants () const
std::size_t GetHash () const
double GetTime ()
void RemoveMe ()
void AddIterator (G4ITReactionPerTrackPtr reactionPerTrack, G4ITReactionList::iterator it)
void AddIterator (G4ITReactionPerTimeIt it)
Static Public Member Functions
static G4ITReactionPtr New (double time, G4Track *trackA, G4Track *trackB)
Public Attributes
double fTime
std::pair< G4Track *, G4Track * > fReactants
G4ReactionPerTrackIt fReactionPerTrack
G4ITReactionPerTimeIt * fReactionPerTimeIt
Private Member Functions
G4ITReaction (double time, G4Track *, G4Track *)
Detailed Description
Definition at line 79 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ITReaction.hh
Constructor & Destructor Documentation
G4ITReaction::G4ITReaction (double time, G4Track * trackA, G4Track * trackB) private
Definition at line 69 of file G4ITReaction.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ITReaction.cc
References fReactionPerTimeIt.
Referenced by New().
G4ITReaction::~G4ITReaction () virtual
Definition at line 80 of file G4ITReaction.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ITReaction.cc
References fReactionPerTimeIt.
Member Function Documentation
void G4ITReaction::AddIterator (G4ITReactionPerTrackPtr reactionPerTrack, G4ITReactionList::iterator it) inline
Definition at line 101 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ITReaction.hh
References fReactionPerTrack.
void G4ITReaction::AddIterator (G4ITReactionPerTimeIt it) inline
Definition at line 107 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ITReaction.hh
References fReactionPerTimeIt.
std::size_t G4ITReaction::GetHash () const
Definition at line 61 of file G4ITReaction.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ITReaction.cc
References fReactants, hash(), and hash_combine().
G4Track* G4ITReaction::GetReactant (G4Track * trackA) inline
Definition at line 89 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ITReaction.hh
References fReactants.
std::pair<G4Track*, G4Track*> G4ITReaction::GetReactants () const inline
Definition at line 95 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ITReaction.hh
References fReactants.
double G4ITReaction::GetTime () inline
Definition at line 97 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ITReaction.hh
References fTime.
static G4ITReactionPtr G4ITReaction::New (double time, G4Track * trackA, G4Track * trackB) inline static
Definition at line 83 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ITReaction.hh
References G4ITReaction().
Referenced by G4ITReactionSet::AddReaction().
void G4ITReaction::RemoveMe ()
Definition at line 86 of file G4ITReaction.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ITReaction.cc
References fReactionPerTimeIt, fReactionPerTrack, G4ITReactionSet::GetReactionsPerTime(), G4ITReactionSet::Instance(), and it.
Member Data Documentation
std::pair<G4Track*, G4Track*> G4ITReaction::fReactants
Definition at line 113 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ITReaction.hh
Referenced by GetHash(), GetReactant(), and GetReactants().
G4ITReactionPerTimeIt* G4ITReaction::fReactionPerTimeIt
Definition at line 115 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ITReaction.hh
Referenced by AddIterator(), G4ITReaction(), RemoveMe(), and ~G4ITReaction().
G4ReactionPerTrackIt G4ITReaction::fReactionPerTrack
Definition at line 114 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ITReaction.hh
Referenced by AddIterator(), and RemoveMe().
double G4ITReaction::fTime
Definition at line 112 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ITReaction.hh
Referenced by GetTime().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITReaction.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITReaction.cc