ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/G4gsposp.cc File Reference
G4gsposp.cc File Reference
#include "G3G4Interface.hh"
#include "G3toG4.hh"
#include "G3VolTable.hh"
#include "G3toG4MakeSolid.hh"
#include "G3Division.hh"
#include "G4SystemOfUnits.hh"
#include "G4VSolid.hh"
Functions
G4bool G3NegVolPars (G4double pars[], G4int *nparpt, G3VolTableEntry *vte, G3VolTableEntry *mvte, const char routine[])
void PG4gsposp (G4String *tokens)
void G4ProcessDaughters (G3VolTableEntry *vte)
void G4CloneDaughters (G3VolTableEntry *vte, G3VolTableEntry *vteClone)
void G4CreateCloneVTE (G3VolTableEntry *vte, G3VolTableEntry *mvte, G4double pars[], G4int npar, G4int num, G4double x, G4double y, G4double z, G4int irot, G4String vonly)
void G4gsposp (G4String vname, G4int num, G4String vmoth, G4double x, G4double y, G4double z, G4int irot, G4String vonly, G4double pars[], G4int npar)
Function Documentation
G4bool G3NegVolPars (G4double pars[], G4int * nparpt, G3VolTableEntry * vte, G3VolTableEntry * mvte, const char routine[])
Definition at line 180 of file G3NegVolPars.cc.
View newest version in sPHENIX GitHub at line 180 of file G3NegVolPars.cc
References FALSE, G3CalcParamsFn(), G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), and TRUE.
Referenced by G4CreateCloneVTE(), and G4ProcessDaughters().
void G4CloneDaughters (G3VolTableEntry * vte, G3VolTableEntry * vteClone)
Definition at line 126 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 126 of file G4gsposp.cc
References G3VolTableEntry::AddClone(), G3VolTableEntry::AddDaughter(), G3VolTableEntry::AddG3Pos(), G3VolTableEntry::AddMother(), G4String::append(), G3Vol, G3VolTableEntry::GetDaughter(), G3VolTableEntry::GetDivision(), G3VolTableEntry::GetG3PosCopy(), G3VolTableEntry::GetMasterClone(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNmed(), G3VolTableEntry::GetNoClones(), G3VolTableEntry::GetNoDaughters(), G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), gSeparator, G3VolTableEntry::HasNegPars(), G3VolTableEntry::NPCopies(), G3VolTable::PutVTE(), G3VolTableEntry::SetDivision(), and G3Division::UpdateVTE().
Referenced by G4CreateCloneVTE().
void G4CreateCloneVTE (G3VolTableEntry * vte, G3VolTableEntry * mvte, G4double pars[], G4int npar, G4int num, G4double x, G4double y, G4double z, G4int irot, G4String vonly)
Definition at line 192 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 192 of file G4gsposp.cc
References G3VolTableEntry::AddClone(), G3VolTableEntry::AddDaughter(), G3VolTableEntry::AddG3Pos(), G3VolTableEntry::AddMother(), G4String::append(), cm, G3NegVolPars(), G3toG4MakeSolid(), G3Vol, G4CloneDaughters(), G4ProcessDaughters(), G3VolTableEntry::GetClone(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNmed(), G3VolTableEntry::GetNoClones(), G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), gSeparator, num, offset, G3VolTable::PutVTE(), G3VolTableEntry::SetHasNegPars(), G3VolTableEntry::SetName(), and G3VolTableEntry::SetSolid().
Referenced by G4gspos(), and G4gsposp().
void G4gsposp (G4String vname, G4int num, G4String vmoth, G4double x, G4double y, G4double z, G4int irot, G4String vonly, G4double pars[], G4int npar)
Definition at line 296 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 296 of file G4gsposp.cc
References FatalException, G3Vol, G4CreateCloneVTE(), G4Exception(), and G3VolTable::GetVTE().
Referenced by PG4gsposp().
void G4ProcessDaughters (G3VolTableEntry * vte)
Definition at line 65 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 65 of file G4gsposp.cc
References FatalException, G3NegVolPars(), G3toG4MakeSolid(), G4cerr, G4endl, G4Exception(), G3VolTableEntry::GetDaughter(), G3VolTableEntry::GetDivision(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNoDaughters(), G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), G3VolTableEntry::HasNegPars(), G3VolTableEntry::SetHasNegPars(), G3VolTableEntry::SetNRpar(), G3VolTableEntry::SetSolid(), and G3Division::UpdateVTE().
Referenced by G4CreateCloneVTE().
void PG4gsposp (G4String * tokens)
Definition at line 41 of file G4gsposp.cc.
View newest version in sPHENIX GitHub at line 41 of file G4gsposp.cc
References G3fillParams(), G4gsposp(), Ipar, num, PTgsposp, Rpar, Spar, x, y, and z.
Referenced by G3CLEval().