ECCE @ EIC Software: HEPREP::HepRepAttValue Class Reference
HEPREP::HepRepAttValue Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepAttValue.h>
Public Member Functions
virtual ~HepRepAttValue ()
Destructor.
virtual std::string getName ()=0
virtual std::string getLowerCaseName ()=0
virtual int getType ()=0
virtual std::string getTypeName ()=0
virtual int showLabel ()=0
virtual std::string getString ()=0
virtual std::string getLowerCaseString ()=0
virtual std::string getAsString ()=0
virtual std::vector< double > getColor ()=0
virtual int64 getLong ()=0
virtual int getInteger ()=0
virtual double getDouble ()=0
virtual bool getBoolean ()=0
virtual HepRepAttValue * copy ()=0
Detailed Description
HepRepAttValue interface.
Author
Mark Donszelmann
Definition at line 24 of file HepRepAttValue.h.
View newest version in sPHENIX GitHub at line 24 of file HepRepAttValue.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepAttValue::~HepRepAttValue () inline virtual
Destructor.
Definition at line 28 of file HepRepAttValue.h.
View newest version in sPHENIX GitHub at line 28 of file HepRepAttValue.h
Member Function Documentation
virtual HepRepAttValue* HEPREP::HepRepAttValue::copy () pure virtual
Returns a deep copy of this attvalue.
Returns
copy of this attvalue.
Implemented in cheprep::DefaultHepRepAttValue.
virtual std::string HEPREP::HepRepAttValue::getAsString () pure virtual
Returns value as string.
Returns
value (of any type) in string format.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by cheprep::XMLHepRepWriter::write().
virtual bool HEPREP::HepRepAttValue::getBoolean () pure virtual
Returns value as boolean.
Returns
value as boolean.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by G4HepRepSceneHandler::setAttribute(), and cheprep::XMLHepRepWriter::write().
virtual std::vector<double> HEPREP::HepRepAttValue::getColor () pure virtual
Returns value as Color.
Returns
value as Color.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by G4HepRepSceneHandler::setAttribute(), and cheprep::XMLHepRepWriter::write().
virtual double HEPREP::HepRepAttValue::getDouble () pure virtual
Returns value as double.
Returns
value as double.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by G4HepRepSceneHandler::setAttribute(), and cheprep::XMLHepRepWriter::write().
virtual int HEPREP::HepRepAttValue::getInteger () pure virtual
Returns value as int.
Returns
value as integer.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by G4HepRepSceneHandler::setAttribute(), and cheprep::XMLHepRepWriter::write().
virtual int64 HEPREP::HepRepAttValue::getLong () pure virtual
Returns value as long.
Returns
value as long.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by cheprep::XMLHepRepWriter::write().
virtual std::string HEPREP::HepRepAttValue::getLowerCaseName () pure virtual
Returns lowercased name of the attvalue.
Returns
Lowercased Name.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by cheprep::DefaultHepRepAttribute::addAttValue().
virtual std::string HEPREP::HepRepAttValue::getLowerCaseString () pure virtual
Returns value as lowercase string.
Returns
value as string (if type is string).
Implemented in cheprep::DefaultHepRepAttValue.
virtual std::string HEPREP::HepRepAttValue::getName () pure virtual
Returns name of the attvalue.
Returns
Capitalized Name.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by cheprep::XMLHepRepWriter::write().
virtual std::string HEPREP::HepRepAttValue::getString () pure virtual
Returns value as string.
Returns
value as string (if type is string).
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by G4HepRepSceneHandler::setAttribute(), and cheprep::XMLHepRepWriter::write().
virtual int HEPREP::HepRepAttValue::getType () pure virtual
Returns type of the attvalue, defined in HepRepConstants with names TYPE_xxx.
Returns
type.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by cheprep::XMLHepRepWriter::write().
virtual std::string HEPREP::HepRepAttValue::getTypeName () pure virtual
Returns the Java-like name for the type of this attvalue.
Returns
type name.
Implemented in cheprep::DefaultHepRepAttValue.
virtual int HEPREP::HepRepAttValue::showLabel () pure virtual
Returns the flag bits for showing this attvalue as a label, defined in HepRepConstants with names SHOW_xxx.
Returns
flag bits if should be shown as label.
Implemented in cheprep::DefaultHepRepAttValue.
Referenced by cheprep::XMLHepRepWriter::write().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepAttValue.h