ECCE @ EIC Software: G4WentzelOKandVIxSection Class Reference
G4WentzelOKandVIxSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WentzelOKandVIxSection.hh>
Public Member Functions
G4WentzelOKandVIxSection (G4bool comb=true)
virtual ~G4WentzelOKandVIxSection ()
void Initialise (const G4ParticleDefinition *, G4double CosThetaLim)
void SetupParticle (const G4ParticleDefinition *)
G4double SetupKinematic (G4double kinEnergy, const G4Material *mat)
G4double SetupTarget (G4int Z, G4double cut)
G4double ComputeTransportCrossSectionPerAtom (G4double CosThetaMax)
G4ThreeVector & SampleSingleScattering (G4double CosThetaMin, G4double CosThetaMax, G4double elecRatio)
G4double ComputeSecondTransportMoment (G4double CosThetaMax)
G4double ComputeNuclearCrossSection (G4double CosThetaMin, G4double CosThetaMax)
G4double ComputeElectronCrossSection (G4double CosThetaMin, G4double CosThetaMax)
void SetTargetMass (G4double value)
G4double GetMomentumSquare () const
G4double GetCosThetaNuc () const
G4double GetCosThetaElec () const
Protected Member Functions
void ComputeMaxElectronScattering (G4double cut)
void InitialiseA ()
G4double FlatFormfactor (G4double x)
Protected Attributes
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theElectron
const G4ParticleDefinition * thePositron
const G4Material * currentMaterial
G4NistManager * fNistManager
G4Pow * fG4pow
G4ScreeningMottCrossSection * fMottXSection
G4ThreeVector temp
G4double numlimit
G4int nwarnings
G4int nwarnlimit
G4NuclearFormfactorType fNucFormfactor
G4bool isCombined
G4double coeff
G4double cosTetMaxElec
G4double cosTetMaxNuc
G4double cosThetaMax
G4double alpha2
const G4ParticleDefinition * particle
G4double chargeSquare
G4double charge3
G4double spin
G4double mass
G4double tkin
G4double mom2
G4double momCM2
G4double invbeta2
G4double kinFactor
G4double etag
G4double ecut
G4double lowEnergyLimit
G4int targetZ
G4double targetMass
G4double screenZ
G4double formfactA
G4double factorA2
G4double factB
G4double factB1
G4double factD
G4double fMottFactor
G4double gam0pcmp
G4double pcmp2
Static Protected Attributes
static G4double ScreenRSquareElec [100] = {0.0}
static G4double ScreenRSquare [100] = {0.0}
static G4double FormFactor [100] = {0.0}
Private Member Functions
G4WentzelOKandVIxSection & operator= (const G4WentzelOKandVIxSection &right)=delete
G4WentzelOKandVIxSection (const G4WentzelOKandVIxSection &)=delete
Detailed Description
Definition at line 73 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 73 of file G4WentzelOKandVIxSection.hh
Constructor & Destructor Documentation
G4WentzelOKandVIxSection::G4WentzelOKandVIxSection (G4bool comb = true) explicit
Definition at line 70 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 70 of file G4WentzelOKandVIxSection.cc
References charge3, chargeSquare, source.hepunit::classic_electr_radius, coeff, cosTetMaxElec, cosTetMaxNuc, currentMaterial, DBL_MAX, ecut, G4Electron::Electron(), source.hepunit::electron_mass_c2, etag, eV, factB, factB1, factD, factorA2, fExponentialNF, fG4pow, source.hepunit::fine_structure_const, fMottFactor, fMottXSection, fNistManager, fNucFormfactor, formfactA, gam0pcmp, G4Pow::GetInstance(), G4NistManager::Instance(), invbeta2, kinFactor, lowEnergyLimit, mass, mom2, momCM2, particle, pcmp2, CLHEP::pi, G4Positron::Positron(), G4Proton::Proton(), CLHEP::proton_mass_c2, screenZ, spin, targetMass, targetZ, theElectron, thePositron, theProton, tkin, and twopi.
G4WentzelOKandVIxSection::~G4WentzelOKandVIxSection () virtual
Definition at line 109 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 109 of file G4WentzelOKandVIxSection.cc
References fMottXSection.
G4WentzelOKandVIxSection::G4WentzelOKandVIxSection (const G4WentzelOKandVIxSection &) private delete
Member Function Documentation
G4double G4WentzelOKandVIxSection::ComputeElectronCrossSection (G4double CosThetaMin, G4double CosThetaMax) inline
Definition at line 236 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 236 of file G4WentzelOKandVIxSection.hh
References cosTetMaxElec, fMottFactor, kinFactor, max, and screenZ.
Referenced by G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeTransportXSectionPerVolume(), G4hCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
void G4WentzelOKandVIxSection::ComputeMaxElectronScattering (G4double cut) protected
Definition at line 415 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 415 of file G4WentzelOKandVIxSection.cc
References cosTetMaxElec, source.hepunit::electron_mass_c2, mass, MeV, min, mom2, particle, ratio, t, t1, theElectron, and tkin.
Referenced by SetupTarget().
G4double G4WentzelOKandVIxSection::ComputeNuclearCrossSection (G4double CosThetaMin, G4double CosThetaMax) inline
Definition at line 226 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 226 of file G4WentzelOKandVIxSection.hh
References fMottFactor, kinFactor, screenZ, and targetZ.
Referenced by G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeTransportXSectionPerVolume(), G4hCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
G4double G4WentzelOKandVIxSection::ComputeSecondTransportMoment (G4double CosThetaMax)
Definition at line 445 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 445 of file G4WentzelOKandVIxSection.cc
Referenced by G4WentzelVIModel::ComputeSecondMoment().
G4double G4WentzelOKandVIxSection::ComputeTransportCrossSectionPerAtom (G4double CosThetaMax)
Definition at line 263 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 263 of file G4WentzelOKandVIxSection.cc
References cosTetMaxElec, factB, fb(), formfactA, G4cout, G4endl, G4Log(), G4ParticleDefinition::GetParticleName(), kinFactor, max, mom2, numlimit, nwarnings, nwarnlimit, particle, screenZ, targetZ, tkin, x, x1, x2, and y.
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), and G4WentzelVIModel::ComputeTransportXSectionPerVolume().
G4double G4WentzelOKandVIxSection::FlatFormfactor (G4double x) inline protected
Definition at line 245 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 245 of file G4WentzelOKandVIxSection.hh
Referenced by SampleSingleScattering().
G4double G4WentzelOKandVIxSection::GetCosThetaElec () const inline
Definition at line 218 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 218 of file G4WentzelOKandVIxSection.hh
References cosTetMaxElec.
G4double G4WentzelOKandVIxSection::GetCosThetaNuc () const inline
Definition at line 211 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 211 of file G4WentzelOKandVIxSection.hh
References cosTetMaxNuc.
G4double G4WentzelOKandVIxSection::GetMomentumSquare () const inline
Definition at line 204 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 204 of file G4WentzelOKandVIxSection.hh
References mom2.
Referenced by G4eCoulombScatteringModel::SampleSecondaries().
void G4WentzelOKandVIxSection::Initialise (const G4ParticleDefinition * p, G4double CosThetaLim)
Definition at line 116 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 116 of file G4WentzelOKandVIxSection.cc
References a, cosThetaMax, currentMaterial, DBL_MAX, ecut, etag, factorA2, G4EmParameters::FactorForAngleLimit(), CLHEP::fermi, fMottXSection, fNucFormfactor, CLHEP::hbarc, G4ScreeningMottCrossSection::Initialise(), InitialiseA(), G4EmParameters::Instance(), isCombined, mom2, momCM2, G4EmParameters::NuclearFormfactorType(), ScreenRSquare, SetupParticle(), targetZ, theElectron, thePositron, and tkin.
Referenced by G4WentzelVIModel::Initialise(), G4hCoulombScatteringModel::Initialise(), and G4eCoulombScatteringModel::Initialise().
void G4WentzelOKandVIxSection::InitialiseA () protected
Definition at line 148 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 148 of file G4WentzelOKandVIxSection.cc
References a0, alpha2, source.hepunit::electron_mass_c2, fG4pow, fNistManager, FormFactor, G4Exp(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4NistManager::GetA27(), G4EmParameters::Instance(), MeV, G4EmParameters::ScreeningFactor(), ScreenRSquare, ScreenRSquareElec, x, and G4Pow::Z13().
Referenced by Initialise().
G4WentzelOKandVIxSection& G4WentzelOKandVIxSection::operator= (const G4WentzelOKandVIxSection & right) private delete
G4ThreeVector & G4WentzelOKandVIxSection::SampleSingleScattering (G4double CosThetaMin, G4double CosThetaMax, G4double elecRatio)
Definition at line 352 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 352 of file G4WentzelOKandVIxSection.cc
References G4Pow::A13(), cosTetMaxElec, factB, factB1, factD, fExponentialNF, fFlatNF, fG4pow, fGaussianNF, CLHEP::HepRandomEngine::flat(), FlatFormfactor(), Acts::UnitConstants::fm, fMottFactor, fMottXSection, fNistManager, fNucFormfactor, formfactA, G4Exp(), G4NistManager::GetAtomicMassAmu(), max, MeV, mom2, phi, G4ScreeningMottCrossSection::RatioMottRutherfordCosT(), screenZ, CLHEP::Hep3Vector::set(), G4ScreeningMottCrossSection::SetupKinematic(), targetZ, temp, tkin, twopi, x, and z1.
Referenced by G4WentzelVIModel::SampleScattering(), G4hCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
void G4WentzelOKandVIxSection::SetTargetMass (G4double value) inline
Definition at line 196 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 196 of file G4WentzelOKandVIxSection.hh
References factD, mom2, and targetMass.
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIRelModel::DefineMaterial(), G4hCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), and SetupTarget().
G4double G4WentzelOKandVIxSection::SetupKinematic (G4double kinEnergy, const G4Material * mat)
Definition at line 203 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 203 of file G4WentzelOKandVIxSection.cc
References cosTetMaxNuc, cosThetaMax, currentMaterial, factB, factorA2, G4IonisParamMat::GetInvA23(), G4Material::GetIonisation(), invbeta2, isCombined, mass, mat, max, mom2, spin, and tkin.
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeGeomPathLength(), G4WentzelVIModel::ComputeSecondMoment(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTrueStepLength(), and G4eCoulombScatteringModel::SampleSecondaries().
void G4WentzelOKandVIxSection::SetupParticle (const G4ParticleDefinition * p)
Definition at line 186 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 186 of file G4WentzelOKandVIxSection.cc
References kdfinder::abs(), charge3, chargeSquare, currentMaterial, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), mass, particle, spin, targetZ, and tkin.
Referenced by Initialise(), G4hCoulombScatteringModel::SetupParticle(), G4eCoulombScatteringModel::SetupParticle(), and G4WentzelVIModel::SetupParticle().
G4double G4WentzelOKandVIxSection::SetupTarget (G4int Z, G4double cut)
Definition at line 221 of file G4WentzelOKandVIxSection.cc.
View newest version in sPHENIX GitHub at line 221 of file G4WentzelOKandVIxSection.cc
References alpha2, CLHEP::amu_c2, chargeSquare, coeff, ComputeMaxElectronScattering(), cosTetMaxElec, cosTetMaxNuc, etag, fG4pow, fMottFactor, fMottXSection, fNistManager, formfactA, FormFactor, G4NistManager::GetAtomicMassAmu(), invbeta2, kinFactor, mass, MeV, min, mom2, particle, CLHEP::proton_mass_c2, ScreenRSquare, ScreenRSquareElec, screenZ, SetTargetMass(), targetZ, theElectron, theProton, tkin, Z, and G4Pow::Z23().
Referenced by G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeSecondMoment(), G4WentzelVIModel::ComputeTransportXSectionPerVolume(), G4WentzelVIModel::SampleScattering(), G4hCoulombScatteringModel::SampleSecondaries(), and G4eCoulombScatteringModel::SampleSecondaries().
Member Data Documentation
G4double G4WentzelOKandVIxSection::alpha2 protected
Definition at line 148 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 148 of file G4WentzelOKandVIxSection.hh
Referenced by InitialiseA(), and SetupTarget().
G4double G4WentzelOKandVIxSection::charge3 protected
Definition at line 154 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 154 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and SetupParticle().
G4double G4WentzelOKandVIxSection::chargeSquare protected
Definition at line 153 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 153 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), SetupParticle(), and SetupTarget().
G4double G4WentzelOKandVIxSection::coeff protected
Definition at line 144 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 144 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and SetupTarget().
G4double G4WentzelOKandVIxSection::cosTetMaxElec protected
Definition at line 145 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 145 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeElectronCrossSection(), ComputeMaxElectronScattering(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), GetCosThetaElec(), SampleSingleScattering(), and SetupTarget().
G4double G4WentzelOKandVIxSection::cosTetMaxNuc protected
Definition at line 146 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 146 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), GetCosThetaNuc(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), and SetupTarget().
G4double G4WentzelOKandVIxSection::cosThetaMax protected
Definition at line 147 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 147 of file G4WentzelOKandVIxSection.hh
Referenced by Initialise(), G4WentzelVIRelXSection::SetupKinematic(), and SetupKinematic().
const G4Material* G4WentzelOKandVIxSection::currentMaterial protected
Definition at line 124 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 124 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), Initialise(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), and SetupParticle().
G4double G4WentzelOKandVIxSection::ecut protected
Definition at line 163 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 163 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and Initialise().
G4double G4WentzelOKandVIxSection::etag protected
Definition at line 162 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 162 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), Initialise(), and SetupTarget().
G4double G4WentzelOKandVIxSection::factB protected
Definition at line 172 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 172 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), SampleSingleScattering(), G4WentzelVIRelXSection::SetupKinematic(), and SetupKinematic().
G4double G4WentzelOKandVIxSection::factB1 protected
Definition at line 173 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 173 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and SampleSingleScattering().
G4double G4WentzelOKandVIxSection::factD protected
Definition at line 174 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 174 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), SampleSingleScattering(), SetTargetMass(), and G4WentzelVIRelXSection::SetupKinematic().
G4double G4WentzelOKandVIxSection::factorA2 protected
Definition at line 171 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 171 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), Initialise(), G4WentzelVIRelXSection::SetupKinematic(), and SetupKinematic().
G4Pow* G4WentzelOKandVIxSection::fG4pow protected
Definition at line 127 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 127 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), InitialiseA(), SampleSingleScattering(), and SetupTarget().
G4double G4WentzelOKandVIxSection::fMottFactor protected
Definition at line 175 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 175 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeElectronCrossSection(), ComputeNuclearCrossSection(), G4WentzelOKandVIxSection(), SampleSingleScattering(), and SetupTarget().
G4ScreeningMottCrossSection* G4WentzelOKandVIxSection::fMottXSection protected
Definition at line 129 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 129 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), Initialise(), SampleSingleScattering(), SetupTarget(), and ~G4WentzelOKandVIxSection().
G4NistManager* G4WentzelOKandVIxSection::fNistManager protected
Definition at line 126 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 126 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), InitialiseA(), SampleSingleScattering(), and SetupTarget().
G4NuclearFormfactorType G4WentzelOKandVIxSection::fNucFormfactor protected
Definition at line 139 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 139 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), Initialise(), and SampleSingleScattering().
G4double G4WentzelOKandVIxSection::formfactA protected
Definition at line 170 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 170 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), SampleSingleScattering(), and SetupTarget().
G4double G4WentzelOKandVIxSection::FormFactor = {0.0} static protected
Definition at line 181 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 181 of file G4WentzelOKandVIxSection.hh
Referenced by InitialiseA(), and SetupTarget().
G4double G4WentzelOKandVIxSection::gam0pcmp protected
Definition at line 176 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 176 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection().
G4double G4WentzelOKandVIxSection::invbeta2 protected
Definition at line 160 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 160 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), and SetupTarget().
G4bool G4WentzelOKandVIxSection::isCombined protected
Definition at line 141 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 141 of file G4WentzelOKandVIxSection.hh
Referenced by Initialise(), G4WentzelVIRelXSection::SetupKinematic(), and SetupKinematic().
G4double G4WentzelOKandVIxSection::kinFactor protected
Definition at line 161 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 161 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeElectronCrossSection(), ComputeNuclearCrossSection(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), and SetupTarget().
G4double G4WentzelOKandVIxSection::lowEnergyLimit protected
Definition at line 164 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 164 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection().
G4double G4WentzelOKandVIxSection::mass protected
Definition at line 156 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 156 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeMaxElectronScattering(), G4WentzelOKandVIxSection(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), SetupParticle(), and SetupTarget().
G4double G4WentzelOKandVIxSection::mom2 protected
Definition at line 158 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 158 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeMaxElectronScattering(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), GetMomentumSquare(), Initialise(), SampleSingleScattering(), SetTargetMass(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), and SetupTarget().
G4double G4WentzelOKandVIxSection::momCM2 protected
Definition at line 159 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 159 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and Initialise().
G4double G4WentzelOKandVIxSection::numlimit protected
Definition at line 133 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 133 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeTransportCrossSectionPerAtom().
G4int G4WentzelOKandVIxSection::nwarnings protected
Definition at line 136 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 136 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeTransportCrossSectionPerAtom().
G4int G4WentzelOKandVIxSection::nwarnlimit protected
Definition at line 137 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 137 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeTransportCrossSectionPerAtom().
const G4ParticleDefinition* G4WentzelOKandVIxSection::particle protected
Definition at line 151 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 151 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeMaxElectronScattering(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), SetupParticle(), and SetupTarget().
G4double G4WentzelOKandVIxSection::pcmp2 protected
Definition at line 177 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 177 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection().
G4double G4WentzelOKandVIxSection::ScreenRSquare = {0.0} static protected
Definition at line 180 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 180 of file G4WentzelOKandVIxSection.hh
Referenced by Initialise(), InitialiseA(), and SetupTarget().
G4double G4WentzelOKandVIxSection::ScreenRSquareElec = {0.0} static protected
Definition at line 179 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 179 of file G4WentzelOKandVIxSection.hh
Referenced by InitialiseA(), and SetupTarget().
G4double G4WentzelOKandVIxSection::screenZ protected
Definition at line 169 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 169 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeElectronCrossSection(), ComputeNuclearCrossSection(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), SampleSingleScattering(), and SetupTarget().
G4double G4WentzelOKandVIxSection::spin protected
Definition at line 155 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 155 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), and SetupParticle().
G4double G4WentzelOKandVIxSection::targetMass protected
Definition at line 168 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 168 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), SetTargetMass(), and G4WentzelVIRelXSection::SetupKinematic().
G4int G4WentzelOKandVIxSection::targetZ protected
Definition at line 167 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 167 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeNuclearCrossSection(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), Initialise(), SampleSingleScattering(), SetupParticle(), and SetupTarget().
G4ThreeVector G4WentzelOKandVIxSection::temp protected
Definition at line 131 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 131 of file G4WentzelOKandVIxSection.hh
Referenced by SampleSingleScattering().
const G4ParticleDefinition* G4WentzelOKandVIxSection::theElectron protected
Definition at line 122 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 122 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeMaxElectronScattering(), G4WentzelOKandVIxSection(), Initialise(), and SetupTarget().
const G4ParticleDefinition* G4WentzelOKandVIxSection::thePositron protected
Definition at line 123 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 123 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and Initialise().
const G4ParticleDefinition* G4WentzelOKandVIxSection::theProton protected
Definition at line 121 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 121 of file G4WentzelOKandVIxSection.hh
Referenced by G4WentzelOKandVIxSection(), and SetupTarget().
G4double G4WentzelOKandVIxSection::tkin protected
Definition at line 157 of file G4WentzelOKandVIxSection.hh.
View newest version in sPHENIX GitHub at line 157 of file G4WentzelOKandVIxSection.hh
Referenced by ComputeMaxElectronScattering(), ComputeTransportCrossSectionPerAtom(), G4WentzelOKandVIxSection(), Initialise(), SampleSingleScattering(), G4WentzelVIRelXSection::SetupKinematic(), SetupKinematic(), SetupParticle(), and SetupTarget().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4WentzelOKandVIxSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4WentzelOKandVIxSection.cc