ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/ml2.cc File Reference
ml2.cc File Reference
#include "ML2Main.hh"
#include "ML2PrimaryGenerationAction.hh"
#include "ML2WorldConstruction.hh"
#include "ML2PhysicsList.hh"
#include "ML2SteppingAction.hh"
#include "ML2EventAction.hh"
#include "ML2TrackingAction.hh"
#include "G4ios.hh"
#include "G4UImanager.hh"
#include "G4ScoringManager.hh"
#include "G4Timer.hh"
#include "G4VisExecutive.hh"
#include "G4UIExecutive.hh"
Functions
void visio (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 56 of file ml2.cc.
View newest version in sPHENIX GitHub at line 56 of file ml2.cc
References G4UImanager::ApplyCommand(), SGeneralData::bCompareExp, G4RunManager::BeamOn(), CML2CInputData::bOnlyVisio, CML2WorldConstruction::checkVolumeOverlap(), CML2WorldConstruction::create(), CML2PrimaryGenerationAction::design(), SGeneralData::fileExperimentalData, SGeneralData::fileExperimentalDataOut, G4cout, G4endl, SInputData::generalData, CML2AcceleratorConstruction::getAcceleratorIsoCentre(), CML2CInputData::getbOnlyVisio(), CML2WorldConstruction::getCML2AcceleratorConstruction(), CML2PrimaryGenerationAction::GetInstance(), CML2WorldConstruction::GetInstance(), CML2PrimaryGenerationAction::getNrecycling(), G4ScoringManager::GetScoringManager(), CLHEP::HepRandom::getTheSeed(), G4UImanager::GetUIpointer(), G4Timer::GetUserElapsed(), Initialize(), CML2PrimaryGenerationAction::inizialize(), CML2CInputData::inputData, SGeneralData::maxNumberOfEvents, SGeneralData::nBeam, SGeneralData::nMaxLoop, SvoxelSegmentation::nX, SvoxelSegmentation::nY, SvoxelSegmentation::nZ, SInputData::primaryParticleData, SGeneralData::saving_in_Selected_Voxels_every_events, SGeneralData::seed, CLHEP::HepRandom::setTheEngine(), CLHEP::HepRandom::setTheSeed(), G4ScoringManager::SetVerboseLevel(), G4Timer::Start(), SGeneralData::StartFileInputData, G4Timer::Stop(), CML2Convergence::stopRun(), visio(), and SInputData::voxelSegmentation.
void visio (int argc, char * argv[])
Definition at line 44 of file ml2.cc.
View newest version in sPHENIX GitHub at line 44 of file ml2.cc
References G4UImanager::GetUIpointer(), and Initialize().
Referenced by main().