ECCE @ EIC Software: G4GDMLWriteDefine Class Reference
G4GDMLWriteDefine Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteDefine.hh>
Public Member Functions
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void MaterialsWrite (xercesc::DOMElement *)=0
virtual void SolidsWrite (xercesc::DOMElement *)=0
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
G4GDMLWriteDefine ()
virtual ~G4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from G4GDMLWrite
G4GDMLWrite ()
virtual ~G4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (G4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
xercesc::DOMElement * defineElement
Protected Attributes inherited from G4GDMLWrite
G4String SchemaLocation
xercesc::DOMDocument * doc
xercesc::DOMElement * extElement
xercesc::DOMElement * userinfoElement
XMLCh tempStr [10000]
G4GDMLAuxListType auxList
Static Protected Attributes
static const G4double kRelativePrecision = DBL_EPSILON
static const G4double kAngularPrecision = DBL_EPSILON
static const G4double kLinearPrecision = DBL_EPSILON
Static Protected Attributes inherited from G4GDMLWrite
static G4bool addPointerToName = true
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Detailed Description
Definition at line 48 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 48 of file G4GDMLWriteDefine.hh
Constructor & Destructor Documentation
G4GDMLWriteDefine::G4GDMLWriteDefine () protected
Definition at line 41 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 41 of file G4GDMLWriteDefine.cc
G4GDMLWriteDefine::~G4GDMLWriteDefine () protected virtual
Definition at line 46 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 46 of file G4GDMLWriteDefine.cc
Member Function Documentation
void G4GDMLWriteDefine::AddPosition (const G4String & name, const G4ThreeVector & pos) inline
Definition at line 69 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GDMLWriteDefine.hh
References defineElement, and Position_vectorWrite().
Referenced by G4GDMLWriteSolids::TessellatedWrite(), and G4GDMLWriteSolids::TetWrite().
void G4GDMLWriteDefine::DefineWrite (xercesc::DOMElement * element) virtual
Implements G4GDMLWrite.
Definition at line 130 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 130 of file G4GDMLWriteDefine.cc
References defineElement, G4cout, G4endl, and G4GDMLWrite::NewElement().
void G4GDMLWriteDefine::FirstpositionWrite (xercesc::DOMElement * element, const G4String & name, const G4ThreeVector & pos) inline
Definition at line 66 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 66 of file G4GDMLWriteDefine.hh
References Position_vectorWrite().
Referenced by G4GDMLWriteSolids::BooleanWrite().
void G4GDMLWriteDefine::FirstrotationWrite (xercesc::DOMElement * element, const G4String & name, const G4ThreeVector & rot) inline
Definition at line 63 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GDMLWriteDefine.hh
References Rotation_vectorWrite().
Referenced by G4GDMLWriteSolids::BooleanWrite().
G4ThreeVector G4GDMLWriteDefine::GetAngles (const G4RotationMatrix & mtx)
Definition at line 50 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 50 of file G4GDMLWriteDefine.cc
References E, mat, CLHEP::HepRotation::rectify(), x, CLHEP::HepRotation::xx(), y, CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), z, CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
Referenced by G4GDMLWriteStructure::AssemblyWrite(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::MultiUnionWrite(), G4GDMLWriteParamvol::ParametersWrite(), G4GDMLWriteStructure::PhysvolWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
void G4GDMLWriteDefine::Position_vectorWrite (xercesc::DOMElement * element, const G4String & tag, const G4String & name, const G4ThreeVector & pos) protected
Definition at line 114 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 114 of file G4GDMLWriteDefine.cc
References kLinearPrecision, mm, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by AddPosition(), FirstpositionWrite(), and PositionWrite().
void G4GDMLWriteDefine::PositionWrite (xercesc::DOMElement * element, const G4String & name, const G4ThreeVector & pos) inline
Definition at line 60 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 60 of file G4GDMLWriteDefine.hh
References Position_vectorWrite().
Referenced by G4GDMLWriteStructure::AssemblyWrite(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::MultiUnionWrite(), G4GDMLWriteParamvol::ParametersWrite(), G4GDMLWriteStructure::PhysvolWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
void G4GDMLWriteDefine::Rotation_vectorWrite (xercesc::DOMElement * element, const G4String & tag, const G4String & name, const G4ThreeVector & rot) protected
Definition at line 97 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 97 of file G4GDMLWriteDefine.cc
References degree, kAngularPrecision, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by FirstrotationWrite(), and RotationWrite().
void G4GDMLWriteDefine::RotationWrite (xercesc::DOMElement * element, const G4String & name, const G4ThreeVector & rot) inline
Definition at line 57 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 57 of file G4GDMLWriteDefine.hh
References Rotation_vectorWrite().
Referenced by G4GDMLWriteStructure::AssemblyWrite(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::MultiUnionWrite(), G4GDMLWriteParamvol::ParametersWrite(), G4GDMLWriteStructure::PhysvolWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
void G4GDMLWriteDefine::Scale_vectorWrite (xercesc::DOMElement * element, const G4String & tag, const G4String & name, const G4ThreeVector & scl) protected
Definition at line 78 of file G4GDMLWriteDefine.cc.
View newest version in sPHENIX GitHub at line 78 of file G4GDMLWriteDefine.cc
References kRelativePrecision, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by ScaleWrite().
void G4GDMLWriteDefine::ScaleWrite (xercesc::DOMElement * element, const G4String & name, const G4ThreeVector & scl) inline
Definition at line 54 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GDMLWriteDefine.hh
References Scale_vectorWrite().
Referenced by G4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteSolids::ScaledWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
Member Data Documentation
xercesc::DOMElement* G4GDMLWriteDefine::defineElement protected
Definition at line 92 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GDMLWriteDefine.hh
Referenced by AddPosition(), DefineWrite(), G4GDMLWriteMaterials::PropertyVectorWrite(), G4GDMLWriteMaterials::PropertyWrite(), and G4GDMLWriteSolids::PropertyWrite().
const G4double G4GDMLWriteDefine::kAngularPrecision = DBL_EPSILON static protected
Definition at line 89 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GDMLWriteDefine.hh
Referenced by G4GDMLWriteStructure::AssemblyWrite(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::MultiUnionWrite(), G4GDMLWriteStructure::PhysvolWrite(), Rotation_vectorWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
const G4double G4GDMLWriteDefine::kLinearPrecision = DBL_EPSILON static protected
Definition at line 90 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GDMLWriteDefine.hh
Referenced by G4GDMLWriteStructure::AssemblyWrite(), G4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::MultiUnionWrite(), G4GDMLWriteStructure::PhysvolWrite(), Position_vectorWrite(), G4GDMLWriteSolids::ScaledWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
const G4double G4GDMLWriteDefine::kRelativePrecision = DBL_EPSILON static protected
Definition at line 88 of file G4GDMLWriteDefine.hh.
View newest version in sPHENIX GitHub at line 88 of file G4GDMLWriteDefine.hh
Referenced by G4GDMLWriteStructure::PhysvolWrite(), Scale_vectorWrite(), and G4GDMLWriteStructure::TraverseVolumeTree().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteDefine.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLWriteDefine.cc