ECCE @ EIC Software: HEPREP::HepRepInstanceTree Class Reference
HEPREP::HepRepInstanceTree Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepInstanceTree.h>
Public Member Functions
virtual ~HepRepInstanceTree ()
Destructor.
virtual void overlay (HepRepInstanceTree *instanceTree)=0
virtual void addInstance (HepRepInstance *instance)=0
virtual void removeInstance (HepRepInstance *instance)=0
virtual std::vector
< HepRepInstance * > getInstances ()=0
virtual void addInstanceTree (HepRepTreeID *instanceTree)=0
virtual std::vector
< HepRepTreeID * > getInstanceTreeList ()=0
virtual HepRepTreeID * getTypeTree ()=0
virtual HepRepInstanceTree * copy (HepRepTypeTree *typeTree, HepRepSelectFilter *filter=NULL)=0
Public Member Functions inherited from HEPREP::HepRepTreeID
virtual ~HepRepTreeID ()
Destructor.
virtual std::string getName ()=0
virtual std::string getVersion ()=0
virtual std::string getQualifier ()=0
virtual void setQualifier (std::string qualifier)=0
Detailed Description
HepRepInstanceTree interface.
Author
Mark Donszelmann
Definition at line 28 of file HepRepInstanceTree.h.
View newest version in sPHENIX GitHub at line 28 of file HepRepInstanceTree.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepInstanceTree::~HepRepInstanceTree () inline virtual
Destructor.
Definition at line 32 of file HepRepInstanceTree.h.
View newest version in sPHENIX GitHub at line 32 of file HepRepInstanceTree.h
Member Function Documentation
virtual void HEPREP::HepRepInstanceTree::addInstance (HepRepInstance * instance) pure virtual
Adds an instance to this instancetree.
Parameters
instance to be added.
Implemented in cheprep::DefaultHepRepInstanceTree.
Referenced by cheprep::DefaultHepRepInstance::DefaultHepRepInstance().
virtual void HEPREP::HepRepInstanceTree::addInstanceTree (HepRepTreeID * instanceTree) pure virtual
Adds a related instance tree to this instancetree.
Parameters
instanceTree related instancetree.
Implemented in cheprep::DefaultHepRepInstanceTree.
Referenced by G4HepRepSceneHandler::closeHepRep().
virtual HepRepInstanceTree* HEPREP::HepRepInstanceTree::copy (HepRepTypeTree * typeTree, HepRepSelectFilter * filter = NULL) pure virtual
Returns a deep copy of this instancetree.
Parameters
filter to filter the instances.
Returns
copy of this instancetree.
Implemented in cheprep::DefaultHepRepInstanceTree.
virtual std::vector<HepRepInstance *> HEPREP::HepRepInstanceTree::getInstances () pure virtual
Returns a collection of instances.
Returns
collection of HepRepInstances.
Implemented in cheprep::DefaultHepRepInstanceTree.
Referenced by cheprep::XMLHepRepWriter::write().
virtual std::vector<HepRepTreeID *> HEPREP::HepRepInstanceTree::getInstanceTreeList () pure virtual
Returns a collection of associated instance trees.
Returns
collection of HepRepTreeIDs.
Implemented in cheprep::DefaultHepRepInstanceTree.
Referenced by cheprep::XMLHepRepWriter::write().
virtual HepRepTreeID* HEPREP::HepRepInstanceTree::getTypeTree () pure virtual
Returns the associated typetree.
Returns
TreeID of the associated typetree.
Implemented in cheprep::DefaultHepRepInstanceTree.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void HEPREP::HepRepInstanceTree::overlay (HepRepInstanceTree * instanceTree) pure virtual
Overlays the instance tree on the current tree.
The list of instances of the instanceTree has to be the same as the current tree.
Implemented in cheprep::DefaultHepRepInstanceTree.
virtual void HEPREP::HepRepInstanceTree::removeInstance (HepRepInstance * instance) pure virtual
Removes an instance from this instancetree.
Parameters
instance to be removed.
Implemented in cheprep::DefaultHepRepInstanceTree.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepInstanceTree.h