ECCE @ EIC Software: G4QMDParameters Class Reference
G4QMDParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDParameters.hh>
Public Member Functions
~G4QMDParameters ()
G4double Get_wl ()
G4double Get_cl ()
G4double Get_hbc ()
G4double Get_rho0 ()
G4double Get_gamm ()
G4double Get_cpw ()
G4double Get_cph ()
G4double Get_epsx ()
G4double Get_cpc ()
G4double Get_cs ()
G4double Get_c0 ()
G4double Get_c0p ()
G4double Get_clp ()
G4double Get_c3 ()
G4double Get_c3p ()
G4double Get_csp ()
G4double Get_cdp ()
Static Public Member Functions
static G4QMDParameters * GetInstance ()
Protected Attributes
G4double wl
G4double cl
G4double hbc
G4double rho0
G4double gamm
G4double c0
G4double c3
G4double cs
G4double cpw
G4double cph
G4double epsx
G4double cpc
G4double c0p
G4double clp
G4double c3p
G4double csp
G4double cdp
Private Member Functions
G4QMDParameters ()
Static Private Attributes
static G4ThreadLocal
G4QMDParameters * parameters = NULL
Detailed Description
Definition at line 42 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 42 of file G4QMDParameters.hh
Constructor & Destructor Documentation
G4QMDParameters::G4QMDParameters () private
Definition at line 36 of file G4QMDParameters.cc.
View newest version in sPHENIX GitHub at line 36 of file G4QMDParameters.cc
References G4Pow::A13(), c0, c0p, c3, c3p, cdp, cl, clp, cpc, cph, cpw, cs, csp, epsx, gamm, G4Pow::GetInstance(), hbc, pi, G4Pow::powA(), rho0, and wl.
Referenced by GetInstance().
G4QMDParameters::~G4QMDParameters ()
Definition at line 101 of file G4QMDParameters.cc.
View newest version in sPHENIX GitHub at line 101 of file G4QMDParameters.cc
Member Function Documentation
G4double G4QMDParameters::Get_c0 () inline
Definition at line 67 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 67 of file G4QMDParameters.hh
References c0.
Referenced by G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_c0p () inline
Definition at line 68 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 68 of file G4QMDParameters.hh
References c0p.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus().
G4double G4QMDParameters::Get_c3 () inline
Definition at line 70 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QMDParameters.hh
References c3.
Referenced by G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_c3p () inline
Definition at line 71 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDParameters.hh
References c3p.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus().
G4double G4QMDParameters::Get_cdp () inline
Definition at line 73 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDParameters.hh
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus().
G4double G4QMDParameters::Get_cl () inline
Definition at line 58 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QMDParameters.hh
References cl.
Referenced by G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_clp () inline
Definition at line 69 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QMDParameters.hh
References clp.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus().
G4double G4QMDParameters::Get_cpc () inline
Definition at line 65 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QMDParameters.hh
References cpc.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), and G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_cph () inline
Definition at line 63 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 63 of file G4QMDParameters.hh
References cph.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), and G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_cpw () inline
Definition at line 62 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 62 of file G4QMDParameters.hh
References cpw.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), and G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_cs () inline
Definition at line 66 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 66 of file G4QMDParameters.hh
References cs.
Referenced by G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_csp () inline
Definition at line 72 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QMDParameters.hh
References csp.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus().
G4double G4QMDParameters::Get_epsx () inline
Definition at line 64 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QMDParameters.hh
References epsx.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus().
G4double G4QMDParameters::Get_gamm () inline
Definition at line 61 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 61 of file G4QMDParameters.hh
References gamm.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), and G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_hbc () inline
Definition at line 59 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 59 of file G4QMDParameters.hh
References hbc.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), G4QMDMeanField::G4QMDMeanField(), and G4QMDNucleus::G4QMDNucleus().
G4double G4QMDParameters::Get_rho0 () inline
Definition at line 60 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 60 of file G4QMDParameters.hh
References rho0.
Referenced by G4QMDMeanField::G4QMDMeanField().
G4double G4QMDParameters::Get_wl () inline
Definition at line 57 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 57 of file G4QMDParameters.hh
References wl.
Referenced by G4QMDMeanField::G4QMDMeanField().
static G4QMDParameters* G4QMDParameters::GetInstance (void) inline static
Definition at line 49 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 49 of file G4QMDParameters.hh
References G4QMDParameters(), and parameters.
Referenced by G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), G4QMDMeanField::G4QMDMeanField(), and G4QMDNucleus::G4QMDNucleus().
Member Data Documentation
G4double G4QMDParameters::c0 protected
Definition at line 90 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_c0().
G4double G4QMDParameters::c0p protected
Definition at line 97 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_c0p().
G4double G4QMDParameters::c3 protected
Definition at line 90 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_c3().
G4double G4QMDParameters::c3p protected
Definition at line 97 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_c3p().
G4double G4QMDParameters::cdp protected
Definition at line 97 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QMDParameters.hh
Referenced by G4QMDParameters().
G4double G4QMDParameters::cl protected
Definition at line 77 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_cl().
G4double G4QMDParameters::clp protected
Definition at line 97 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_clp().
G4double G4QMDParameters::cpc protected
Definition at line 96 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 96 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_cpc().
G4double G4QMDParameters::cph protected
Definition at line 94 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_cph().
G4double G4QMDParameters::cpw protected
Definition at line 93 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 93 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_cpw().
G4double G4QMDParameters::cs protected
Definition at line 90 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_cs().
G4double G4QMDParameters::csp protected
Definition at line 97 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_csp().
G4double G4QMDParameters::epsx protected
Definition at line 95 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 95 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_epsx().
G4double G4QMDParameters::gamm protected
Definition at line 80 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_gamm().
G4double G4QMDParameters::hbc protected
Definition at line 78 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_hbc().
G4ThreadLocal G4QMDParameters * G4QMDParameters::parameters = NULL static private
Definition at line 44 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 44 of file G4QMDParameters.hh
Referenced by GetInstance().
G4double G4QMDParameters::rho0 protected
Definition at line 79 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_rho0().
G4double G4QMDParameters::wl protected
Definition at line 73 of file G4QMDParameters.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDParameters.hh
Referenced by G4QMDParameters(), and Get_wl().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDParameters.cc