ECCE @ EIC Software: G4AnalysisManagerState Class Reference
G4AnalysisManagerState Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4AnalysisManagerState.hh>
Public Member Functions
G4AnalysisManagerState (const G4String &type, G4bool isMaster)
G4String GetType () const
G4bool GetIsMaster () const
G4bool GetIsActivation () const
G4int GetVerboseLevel () const
const G4AnalysisVerbose * GetVerboseL1 () const
const G4AnalysisVerbose * GetVerboseL2 () const
const G4AnalysisVerbose * GetVerboseL3 () const
const G4AnalysisVerbose * GetVerboseL4 () const
G4int GetCompressionLevel () const
Private Member Functions
G4AnalysisManagerState ()
G4AnalysisManagerState (const G4AnalysisManagerState &)
G4AnalysisManagerState & operator= (const G4AnalysisManagerState &)
void SetIsActivation (G4bool isActivation)
void SetVerboseLevel (G4int verboseLevel)
void SetCompressionLevel (G4int level)
Private Attributes
G4String fType
G4bool fIsMaster
G4bool fIsActivation
G4int fVerboseLevel
G4int fCompressionLevel
G4AnalysisVerbose fVerboseL1
G4AnalysisVerbose fVerboseL2
G4AnalysisVerbose fVerboseL3
G4AnalysisVerbose fVerboseL4
G4AnalysisVerbose * fpVerboseL1
G4AnalysisVerbose * fpVerboseL2
G4AnalysisVerbose * fpVerboseL3
G4AnalysisVerbose * fpVerboseL4
Friends
class G4VAnalysisManager
class G4VAnalysisReader
class G4ParameterManager
Detailed Description
Definition at line 38 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 38 of file G4AnalysisManagerState.hh
Constructor & Destructor Documentation
G4AnalysisManagerState::G4AnalysisManagerState (const G4String & type, G4bool isMaster)
Definition at line 35 of file G4AnalysisManagerState.cc.
View newest version in sPHENIX GitHub at line 35 of file G4AnalysisManagerState.cc
G4AnalysisManagerState::G4AnalysisManagerState () private
G4AnalysisManagerState::G4AnalysisManagerState (const G4AnalysisManagerState &) private
Member Function Documentation
G4int G4AnalysisManagerState::GetCompressionLevel () const inline
Definition at line 119 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 119 of file G4AnalysisManagerState.hh
References fCompressionLevel.
Referenced by G4VAnalysisManager::GetCompressionLevel(), G4RootFileManager::OpenFile(), and G4RootFileManager::OpenNtupleFiles().
G4bool G4AnalysisManagerState::GetIsActivation () const inline
Definition at line 101 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AnalysisManagerState.hh
References fIsActivation.
Referenced by G4RootMpiPNtupleManager::AddNtupleRow(), G4RootPNtupleManager::AddNtupleRow(), G4RootMpiPNtupleManager::CreateNtuplesFromBooking(), G4H1ToolsManager::FillH1(), G4H2ToolsManager::FillH2(), G4H3ToolsManager::FillH3(), G4TNtupleManager< tools::wroot::ntuple >::FillNtupleTColumn(), G4TNtupleManager< tools::hdf5::ntuple >::FillNtupleTColumn(), G4RootMpiPNtupleManager::FillNtupleTColumn(), G4RootPNtupleManager::FillNtupleTColumn(), G4P1ToolsManager::FillP1(), G4P2ToolsManager::FillP2(), G4RootMpiNtupleManager::InitializeRanks(), G4VAnalysisManager::IsActive(), G4MPIToolsManager::Merge(), G4RootMpiNtupleManager::Merge(), G4PlotManager::PlotAndWrite(), G4MPIToolsManager::Receive(), and G4MPIToolsManager::Send().
G4bool G4AnalysisManagerState::GetIsMaster () const inline
Definition at line 98 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AnalysisManagerState.hh
References fIsMaster.
Referenced by G4RootAnalysisManager::CloseFileImpl(), G4BaseFileManager::GetFullFileName(), G4BaseFileManager::GetNtupleFileName(), G4XmlAnalysisManager::OpenFileImpl(), G4CsvAnalysisManager::~G4CsvAnalysisManager(), G4CsvAnalysisReader::~G4CsvAnalysisReader(), G4Hdf5AnalysisManager::~G4Hdf5AnalysisManager(), G4Hdf5AnalysisReader::~G4Hdf5AnalysisReader(), G4RootAnalysisManager::~G4RootAnalysisManager(), G4RootAnalysisReader::~G4RootAnalysisReader(), G4XmlAnalysisManager::~G4XmlAnalysisManager(), and G4XmlAnalysisReader::~G4XmlAnalysisReader().
G4String G4AnalysisManagerState::GetType () const inline
Definition at line 95 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AnalysisManagerState.hh
References fType.
Referenced by G4BaseFileManager::GetFileType().
const G4AnalysisVerbose * G4AnalysisManagerState::GetVerboseL1 () const inline
Definition at line 107 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AnalysisManagerState.hh
References fpVerboseL1.
Referenced by G4Hdf5FileManager::CloseFile(), G4PlotManager::CloseFile(), G4XmlAnalysisManager::CloseFileImpl(), G4RootAnalysisManager::CloseFileImpl(), G4XmlFileManager::CloseHnFile(), G4CsvFileManager::CloseNtupleFile(), G4XmlFileManager::CloseNtupleFile(), G4XmlFileManager::CreateHnFile(), G4CsvFileManager::CreateNtupleFile(), G4XmlFileManager::CreateNtupleFile(), G4PlotManager::G4PlotManager(), G4MPIToolsManager::Merge(), G4PlotManager::OpenFile(), G4RootMpiAnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4RootAnalysisManager::OpenFileImpl(), G4RootFileManager::OpenNtupleFiles(), G4CsvRFileManager::OpenRFile(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), G4Hdf5RFileManager::OpenRFile(), G4CsvAnalysisReader::ReadH1Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH3Impl(), G4CsvAnalysisReader::ReadP1Impl(), G4CsvAnalysisReader::ReadP2Impl(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), G4RootAnalysisManager::SetNtupleRowWise(), G4VAnalysisManager::WriteAscii(), G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), G4RootMpiAnalysisManager::WriteNtuple(), and G4RootAnalysisManager::WriteNtuple().
const G4AnalysisVerbose * G4AnalysisManagerState::GetVerboseL2 () const inline
Definition at line 110 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AnalysisManagerState.hh
References fpVerboseL2.
Referenced by G4H1ToolsManager::AddH1(), G4H2ToolsManager::AddH2(), G4H3ToolsManager::AddH3(), G4P1ToolsManager::AddP1(), G4P2ToolsManager::AddP2(), G4XmlAnalysisManager::CloseFileImpl(), G4Hdf5FileManager::CreateDirectory(), G4H1ToolsManager::CreateH1(), G4H2ToolsManager::CreateH2(), G4H3ToolsManager::CreateH3(), G4RootFileManager::CreateHistoDirectory(), G4RootMpiPNtupleManager::CreateNtuple(), G4RootPNtupleManager::CreateNtuple(), G4RootFileManager::CreateNtupleDirectory(), G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), G4P1ToolsManager::CreateP1(), G4P2ToolsManager::CreateP2(), G4Hdf5RFileManager::OpenDirectory(), G4CsvAnalysisReader::ReadH1Impl(), G4XmlAnalysisReader::ReadH1Impl(), G4Hdf5AnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4Hdf5AnalysisReader::ReadH2Impl(), G4RootAnalysisReader::ReadH3Impl(), G4XmlAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadH3Impl(), G4CsvAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadNtupleImpl(), G4RootAnalysisReader::ReadNtupleImpl(), G4CsvAnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4Hdf5AnalysisReader::ReadP1Impl(), G4CsvAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP2Impl(), G4Hdf5AnalysisReader::ReadP2Impl(), G4CsvAnalysisReader::ReadP2Impl(), G4RootAnalysisReader::ReadP2Impl(), G4RootNtupleManager::SetCreateMode(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), G4XmlRNtupleManager::SetNtupleDColumn(), G4XmlRNtupleManager::SetNtupleFColumn(), G4XmlRNtupleManager::SetNtupleIColumn(), G4RootAnalysisManager::SetNtupleMergingMode(), and G4RootMpiNtupleManager::WaitBuffer().
const G4AnalysisVerbose * G4AnalysisManagerState::GetVerboseL3 () const inline
Definition at line 113 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AnalysisManagerState.hh
References fpVerboseL3.
Referenced by G4RootMpiPNtupleManager::AddNtupleRow(), G4RootPNtupleManager::AddNtupleRow(), G4RootAnalysisManager::ClearNtupleManagers(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootMainNtupleManager::CreateNtuple(), G4RootMpiPNtupleManager::CreateNtuple(), G4RootPNtupleManager::CreateNtuple(), G4RootAnalysisManager::CreateNtupleManagers(), G4RootMpiPNtupleManager::CreateNtuplesFromBooking(), G4MPIToolsManager::Merge(), G4RootMpiPNtupleManager::Merge(), G4RootPNtupleManager::Merge(), G4PlotManager::PlotAndWrite(), G4VAnalysisManager::WriteAscii(), G4H1ToolsManager::WriteOnAscii(), and G4PlotManager::WritePage().
const G4AnalysisVerbose * G4AnalysisManagerState::GetVerboseL4 () const inline
Definition at line 116 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AnalysisManagerState.hh
References fpVerboseL4.
Referenced by G4H1ToolsManager::AddH1(), G4H2ToolsManager::AddH2(), G4H3ToolsManager::AddH3(), G4RootMpiPNtupleManager::AddNtupleRow(), G4RootPNtupleManager::AddNtupleRow(), G4P1ToolsManager::AddP1(), G4P2ToolsManager::AddP2(), G4RootAnalysisManager::ClearNtupleManagers(), G4Hdf5FileManager::CloseFile(), G4PlotManager::CloseFile(), G4XmlAnalysisManager::CloseFileImpl(), G4XmlFileManager::CloseHnFile(), G4CsvFileManager::CloseNtupleFile(), G4XmlFileManager::CloseNtupleFile(), G4Hdf5FileManager::CreateDirectory(), G4H1ToolsManager::CreateH1(), G4H2ToolsManager::CreateH2(), G4H3ToolsManager::CreateH3(), G4RootFileManager::CreateHistoDirectory(), G4XmlFileManager::CreateHnFile(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootMainNtupleManager::CreateNtuple(), G4RootMpiPNtupleManager::CreateNtuple(), G4RootPNtupleManager::CreateNtuple(), G4RootFileManager::CreateNtupleDirectory(), G4CsvFileManager::CreateNtupleFile(), G4XmlFileManager::CreateNtupleFile(), G4RootAnalysisManager::CreateNtupleManagers(), G4RootMpiPNtupleManager::CreateNtuplesFromBooking(), G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), G4P1ToolsManager::CreateP1(), G4P2ToolsManager::CreateP2(), G4H1ToolsManager::FillH1(), G4H2ToolsManager::FillH2(), G4H3ToolsManager::FillH3(), G4TNtupleManager< tools::hdf5::ntuple >::FillNtupleTColumn(), G4TNtupleManager< tools::wroot::ntuple >::FillNtupleTColumn(), G4RootMpiPNtupleManager::FillNtupleTColumn(), G4RootPNtupleManager::FillNtupleTColumn(), G4P1ToolsManager::FillP1(), G4P2ToolsManager::FillP2(), G4MPIToolsManager::Merge(), G4RootMpiPNtupleManager::Merge(), G4RootPNtupleManager::Merge(), G4Hdf5RFileManager::OpenDirectory(), G4PlotManager::OpenFile(), G4RootMpiAnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4RootAnalysisManager::OpenFileImpl(), G4RootFileManager::OpenNtupleFiles(), G4CsvRFileManager::OpenRFile(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), G4Hdf5RFileManager::OpenRFile(), G4CsvAnalysisReader::ReadH1Impl(), G4Hdf5AnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH1Impl(), G4XmlAnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH2Impl(), G4Hdf5AnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadH3Impl(), G4RootAnalysisReader::ReadH3Impl(), G4CsvAnalysisReader::ReadH3Impl(), G4RootAnalysisReader::ReadNtupleImpl(), G4CsvAnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4Hdf5AnalysisReader::ReadNtupleImpl(), G4CsvAnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP1Impl(), G4Hdf5AnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP2Impl(), G4XmlAnalysisReader::ReadP2Impl(), G4Hdf5AnalysisReader::ReadP2Impl(), G4CsvAnalysisReader::ReadP2Impl(), G4RootNtupleManager::SetCreateMode(), G4H1ToolsManager::SetH1(), G4H2ToolsManager::SetH2(), G4H3ToolsManager::SetH3(), G4XmlRNtupleManager::SetNtupleDColumn(), G4XmlRNtupleManager::SetNtupleFColumn(), G4XmlRNtupleManager::SetNtupleIColumn(), G4RootAnalysisManager::SetNtupleMergingMode(), G4P1ToolsManager::SetP1(), G4P2ToolsManager::SetP2(), G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), G4RootMpiAnalysisManager::WriteNtuple(), G4RootAnalysisManager::WriteNtuple(), and G4PlotManager::WritePage().
G4int G4AnalysisManagerState::GetVerboseLevel () const inline
Definition at line 104 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AnalysisManagerState.hh
References fVerboseLevel.
G4AnalysisManagerState& G4AnalysisManagerState::operator= (const G4AnalysisManagerState &) private
void G4AnalysisManagerState::SetCompressionLevel (G4int level) inline private
Definition at line 92 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 92 of file G4AnalysisManagerState.hh
References fCompressionLevel.
Referenced by G4VAnalysisManager::SetCompressionLevel().
void G4AnalysisManagerState::SetIsActivation (G4bool isActivation) inline private
Definition at line 89 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 89 of file G4AnalysisManagerState.hh
References fIsActivation.
Referenced by G4VAnalysisManager::SetActivation().
void G4AnalysisManagerState::SetVerboseLevel (G4int verboseLevel) private
Definition at line 58 of file G4AnalysisManagerState.cc.
View newest version in sPHENIX GitHub at line 58 of file G4AnalysisManagerState.cc
References fpVerboseL1, fpVerboseL2, fpVerboseL3, fpVerboseL4, fVerboseL1, fVerboseL2, fVerboseL3, fVerboseL4, and fVerboseLevel.
Referenced by G4VAnalysisReader::SetVerboseLevel(), and G4VAnalysisManager::SetVerboseLevel().
Friends And Related Function Documentation
friend class G4ParameterManager friend
Definition at line 43 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 43 of file G4AnalysisManagerState.hh
friend class G4VAnalysisManager friend
Definition at line 41 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 41 of file G4AnalysisManagerState.hh
friend class G4VAnalysisReader friend
Definition at line 42 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 42 of file G4AnalysisManagerState.hh
Member Data Documentation
G4int G4AnalysisManagerState::fCompressionLevel private
Definition at line 76 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AnalysisManagerState.hh
Referenced by GetCompressionLevel(), and SetCompressionLevel().
G4bool G4AnalysisManagerState::fIsActivation private
Definition at line 74 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 74 of file G4AnalysisManagerState.hh
Referenced by GetIsActivation(), and SetIsActivation().
G4bool G4AnalysisManagerState::fIsMaster private
Definition at line 73 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 73 of file G4AnalysisManagerState.hh
Referenced by GetIsMaster().
G4AnalysisVerbose* G4AnalysisManagerState::fpVerboseL1 private
Definition at line 81 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 81 of file G4AnalysisManagerState.hh
Referenced by GetVerboseL1(), and SetVerboseLevel().
G4AnalysisVerbose* G4AnalysisManagerState::fpVerboseL2 private
Definition at line 82 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 82 of file G4AnalysisManagerState.hh
Referenced by GetVerboseL2(), and SetVerboseLevel().
G4AnalysisVerbose* G4AnalysisManagerState::fpVerboseL3 private
Definition at line 83 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 83 of file G4AnalysisManagerState.hh
Referenced by GetVerboseL3(), and SetVerboseLevel().
G4AnalysisVerbose* G4AnalysisManagerState::fpVerboseL4 private
Definition at line 84 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 84 of file G4AnalysisManagerState.hh
Referenced by GetVerboseL4(), and SetVerboseLevel().
G4String G4AnalysisManagerState::fType private
Definition at line 72 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 72 of file G4AnalysisManagerState.hh
Referenced by GetType().
G4AnalysisVerbose G4AnalysisManagerState::fVerboseL1 private
Definition at line 77 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AnalysisManagerState.hh
Referenced by SetVerboseLevel().
G4AnalysisVerbose G4AnalysisManagerState::fVerboseL2 private
Definition at line 78 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AnalysisManagerState.hh
Referenced by SetVerboseLevel().
G4AnalysisVerbose G4AnalysisManagerState::fVerboseL3 private
Definition at line 79 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 79 of file G4AnalysisManagerState.hh
Referenced by SetVerboseLevel().
G4AnalysisVerbose G4AnalysisManagerState::fVerboseL4 private
Definition at line 80 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 80 of file G4AnalysisManagerState.hh
Referenced by SetVerboseLevel().
G4int G4AnalysisManagerState::fVerboseLevel private
Definition at line 75 of file G4AnalysisManagerState.hh.
View newest version in sPHENIX GitHub at line 75 of file G4AnalysisManagerState.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4AnalysisManagerState.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4AnalysisManagerState.cc