ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/run/pyG4RunManager.cc File Reference
pyG4RunManager.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4RunManager.hh"
#include "G4VUserDetectorConstruction.hh"
#include "G4VUserPhysicsList.hh"
#include "G4UserRunAction.hh"
#include "G4VUserPrimaryGeneratorAction.hh"
#include "G4UserEventAction.hh"
#include "G4UserStackingAction.hh"
#include "G4UserTrackingAction.hh"
#include "G4UserSteppingAction.hh"
#include "G4Region.hh"
#include "G4Run.hh"
#include "G4Event.hh"
Namespaces
namespace pyG4RunManager
Functions
pyG4RunManager::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_DefineWorldVolume, DefineWorldVolume, 1, 2) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_GeometryHasBeenModified
void export_G4RunManager ()
Variables
void(G4RunManager::* pyG4RunManager::f1_SetUserInitialization)(G4VUserDetectorConstruction *) = &G4RunManager::SetUserInitialization
void(G4RunManager::* pyG4RunManager::f2_SetUserInitialization)(G4VUserPhysicsList *) = &G4RunManager::SetUserInitialization
void(G4RunManager::* pyG4RunManager::f1_SetUserAction)(G4UserRunAction *) = &G4RunManager::SetUserAction
void(G4RunManager::* pyG4RunManager::f2_SetUserAction)(G4VUserPrimaryGeneratorAction *) = &G4RunManager::SetUserAction
void(G4RunManager::* pyG4RunManager::f3_SetUserAction)(G4UserEventAction *) = &G4RunManager::SetUserAction
void(G4RunManager::* pyG4RunManager::f4_SetUserAction)(G4UserStackingAction *) = &G4RunManager::SetUserAction
void(G4RunManager::* pyG4RunManager::f5_SetUserAction)(G4UserTrackingAction *) = &G4RunManager::SetUserAction
void(G4RunManager::* pyG4RunManager::f6_SetUserAction)(G4UserSteppingAction *) = &G4RunManager::SetUserAction
void(G4RunManager::* pyG4RunManager::f1_DumpRegion)(const G4String &) const = &G4RunManager::DumpRegion
void(G4RunManager::* pyG4RunManager::f2_DumpRegion)(G4Region *) const = &G4RunManager::DumpRegion
pyG4RunManager::GeometryHasBeenModified
Function Documentation
void export_G4RunManager ()
Definition at line 102 of file pyG4RunManager.cc.
View newest version in sPHENIX GitHub at line 102 of file pyG4RunManager.cc
References G4RunManager::AbortEvent(), G4RunManager::AbortRun(), G4RunManager::BeamOn(), G4RunManager::DefineWorldVolume(), pyG4RunManager::f1_DumpRegion, pyG4RunManager::f1_SetUserAction, pyG4RunManager::f1_SetUserInitialization, pyG4RunManager::f2_DumpRegion, pyG4RunManager::f2_SetUserAction, pyG4RunManager::f2_SetUserInitialization, pyG4RunManager::f3_SetUserAction, pyG4RunManager::f4_SetUserAction, pyG4RunManager::f5_SetUserAction, pyG4RunManager::f6_SetUserAction, G4RunManager::GeometryHasBeenModified(), G4RunManager::GetCurrentEvent(), G4RunManager::GetCurrentRun(), G4RunManager::GetGeometryToBeOptimized(), G4RunManager::GetRandomNumberStore(), G4RunManager::GetRandomNumberStoreDir(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4RunManager::GetUserEventAction(), G4RunManager::GetUserPhysicsList(), G4RunManager::GetUserPrimaryGeneratorAction(), G4RunManager::GetUserRunAction(), G4RunManager::GetUserStackingAction(), G4RunManager::GetUserSteppingAction(), G4RunManager::GetUserTrackingAction(), G4RunManager::GetVerboseLevel(), G4RunManager::GetVersionString(), G4RunManager::Initialize(), G4RunManager::PhysicsHasBeenModified(), G4RunManager::RestoreRandomNumberStatus(), G4RunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisRun(), G4RunManager::SetRandomNumberStore(), G4RunManager::SetRandomNumberStoreDir(), G4RunManager::SetRunIDCounter(), and G4RunManager::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().