ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/HEPRandom/include/G4RandomTools.hh File Reference
G4RandomTools.hh File Reference
#include <CLHEP/Units/PhysicalConstants.h>
#include "globals.hh"
#include "Randomize.hh"
#include "G4TwoVector.hh"
#include "G4ThreeVector.hh"
#include "G4RandomDirection.hh"
Functions
G4ThreeVector G4LambertianRand (const G4ThreeVector &normal)
G4ThreeVector G4PlaneVectorRand (const G4ThreeVector &normal)
G4double G4RandomRadiusInRing (G4double rmin, G4double rmax)
G4TwoVector G4RandomPointInEllipse (G4double a, G4double b)
G4TwoVector G4RandomPointOnEllipse (G4double a, G4double b)
G4ThreeVector G4RandomPointOnEllipsoid (G4double a, G4double b, G4double c)
Function Documentation
G4ThreeVector G4LambertianRand (const G4ThreeVector & normal) inline
Definition at line 58 of file G4RandomTools.hh.
View newest version in sPHENIX GitHub at line 58 of file G4RandomTools.hh
References G4RandomDirection(), and G4UniformRand.
Referenced by G4OpBoundaryProcess::DoReflection().
G4ThreeVector G4PlaneVectorRand (const G4ThreeVector & normal) inline
Definition at line 85 of file G4RandomTools.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RandomTools.hh
References CLHEP::Hep3Vector::cross(), G4UniformRand, CLHEP::Hep3Vector::orthogonal(), phi, and CLHEP::twopi.
G4TwoVector G4RandomPointInEllipse (G4double a, G4double b) inline
Definition at line 115 of file G4RandomTools.hh.
View newest version in sPHENIX GitHub at line 115 of file G4RandomTools.hh
References bb, G4UniformRand, x, and y.
Referenced by G4EllipticalTube::GetPointOnSurface(), G4Ellipsoid::GetPointOnSurface(), and G4EllipticalCone::GetPointOnSurface().
G4TwoVector G4RandomPointOnEllipse (G4double a, G4double b) inline
Definition at line 132 of file G4RandomTools.hh.
View newest version in sPHENIX GitHub at line 132 of file G4RandomTools.hh
References A(), kdfinder::abs(), B(), G4UniformRand, max, phi, CLHEP::twopi, x, and y.
Referenced by G4EllipticalTube::GetPointOnSurface().
G4ThreeVector G4RandomPointOnEllipsoid (G4double a, G4double b, G4double c) inline
Definition at line 155 of file G4RandomTools.hh.
View newest version in sPHENIX GitHub at line 155 of file G4RandomTools.hh
References A(), kdfinder::abs(), B(), C(), G4RandomDirection(), G4UniformRand, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4RandomRadiusInRing (G4double rmin, G4double rmax) inline
Definition at line 100 of file G4RandomTools.hh.
View newest version in sPHENIX GitHub at line 100 of file G4RandomTools.hh
References G4UniformRand, and k.
Referenced by G4EllipticalCone::GetPointOnSurface(), and G4CSGSolid::GetRadiusInRing().