ECCE @ EIC Software: G4NuclearDecay Class Reference
G4NuclearDecay Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4NuclearDecay.hh>
Public Member Functions
G4NuclearDecay (const G4String &channelName, const G4RadioactiveDecayMode &mode, const G4double &excitation, const G4Ions::G4FloatLevelBase &floatingLevel)
virtual ~G4NuclearDecay ()
G4RadioactiveDecayMode GetDecayMode ()
G4double GetDaughterExcitation ()
G4Ions::G4FloatLevelBase GetFloatingLevel ()
G4ParticleDefinition * GetDaughterNucleus ()
void SetHLThreshold (G4double HLT)
G4double GetHLThreshold ()
virtual void DumpNuclearInfo ()=0
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
virtual G4DecayProducts * DecayIt (G4double parentMass=-1.0)=0
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Protected Attributes
const G4RadioactiveDecayMode theMode
Protected Attributes inherited from G4VDecayChannel
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Private Attributes
const G4double daughterEx
const G4Ions::G4FloatLevelBase floatingLevel
G4double halflifeThreshold
Additional Inherited Members
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 43 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 43 of file G4NuclearDecay.hh
Constructor & Destructor Documentation
G4NuclearDecay::G4NuclearDecay (const G4String & channelName, const G4RadioactiveDecayMode & mode, const G4double & excitation, const G4Ions::G4FloatLevelBase & floatingLevel)
Definition at line 37 of file G4NuclearDecay.cc.
View newest version in sPHENIX GitHub at line 37 of file G4NuclearDecay.cc
G4NuclearDecay::~G4NuclearDecay () virtual
Definition at line 45 of file G4NuclearDecay.cc.
View newest version in sPHENIX GitHub at line 45 of file G4NuclearDecay.cc
Member Function Documentation
virtual void G4NuclearDecay::DumpNuclearInfo () pure virtual
Implemented in G4ITDecay, G4BetaMinusDecay, G4BetaPlusDecay, G4NeutronDecay, G4ProtonDecay, G4SFDecay, G4ECDecay, G4AlphaDecay, and G4TritonDecay.
G4double G4NuclearDecay::GetDaughterExcitation () inline
Definition at line 55 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 55 of file G4NuclearDecay.hh
References daughterEx.
Referenced by G4Radioactivation::CalculateChainsFromParent(), and G4RadioactiveDecay::CalculateChainsFromParent().
G4ParticleDefinition* G4NuclearDecay::GetDaughterNucleus () inline
Definition at line 59 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 59 of file G4NuclearDecay.hh
References G4VDecayChannel::GetDaughter().
Referenced by G4Radioactivation::CalculateChainsFromParent(), and G4RadioactiveDecay::CalculateChainsFromParent().
G4RadioactiveDecayMode G4NuclearDecay::GetDecayMode () inline
Definition at line 53 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 53 of file G4NuclearDecay.hh
References theMode.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4RadioactiveDecayBase::LoadDecayTable(), and G4RadioactiveDecay::LoadDecayTable().
G4Ions::G4FloatLevelBase G4NuclearDecay::GetFloatingLevel () inline
Definition at line 57 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 57 of file G4NuclearDecay.hh
References floatingLevel.
G4double G4NuclearDecay::GetHLThreshold () inline
Definition at line 62 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 62 of file G4NuclearDecay.hh
References halflifeThreshold.
void G4NuclearDecay::SetHLThreshold (G4double HLT) inline
Definition at line 61 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 61 of file G4NuclearDecay.hh
References halflifeThreshold.
Referenced by G4RadioactiveDecay::LoadDecayTable().
Member Data Documentation
const G4double G4NuclearDecay::daughterEx private
Definition at line 71 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NuclearDecay.hh
Referenced by GetDaughterExcitation().
const G4Ions::G4FloatLevelBase G4NuclearDecay::floatingLevel private
Definition at line 72 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 72 of file G4NuclearDecay.hh
Referenced by GetFloatingLevel().
G4double G4NuclearDecay::halflifeThreshold private
Definition at line 73 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 73 of file G4NuclearDecay.hh
Referenced by GetHLThreshold(), and SetHLThreshold().
const G4RadioactiveDecayMode G4NuclearDecay::theMode protected
Definition at line 67 of file G4NuclearDecay.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NuclearDecay.hh
Referenced by G4ECDecay::DecayIt(), G4ECDecay::DumpNuclearInfo(), and GetDecayMode().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4NuclearDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4NuclearDecay.cc