ECCE @ EIC Software: G4INCL::DeltaDecayChannel Class Reference
G4INCL::DeltaDecayChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLDeltaDecayChannel.hh>
Public Member Functions
DeltaDecayChannel (Particle *, ThreeVector const &)
virtual ~DeltaDecayChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Static Public Member Functions
static G4double computeDecayTime (Particle *p)
Private Member Functions
void sampleAngles (G4double *, G4double *, G4double *)
Private Attributes
Particle * theParticle
ThreeVector const incidentDirection
Detailed Description
Definition at line 49 of file G4INCLDeltaDecayChannel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4INCLDeltaDecayChannel.hh
Constructor & Destructor Documentation
G4INCL::DeltaDecayChannel::DeltaDecayChannel (Particle * p, ThreeVector const & dir)
Definition at line 46 of file G4INCLDeltaDecayChannel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4INCLDeltaDecayChannel.cc
G4INCL::DeltaDecayChannel::~DeltaDecayChannel () virtual
Definition at line 50 of file G4INCLDeltaDecayChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLDeltaDecayChannel.cc
Member Function Documentation
G4double G4INCL::DeltaDecayChannel::computeDecayTime (Particle * p) static
Definition at line 52 of file G4INCLDeltaDecayChannel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4INCLDeltaDecayChannel.cc
References G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::ParticleTable::effectivePionMass, G4INCL::Particle::getEnergy(), G4INCL::Particle::getMass(), G4INCL::PhysicalConstants::hc, m, G4INCL::KinematicsUtils::momentumInCM(), and G4INCL::Random::shoot().
Referenced by G4INCL::StandardPropagationModel::generateDecays().
void G4INCL::DeltaDecayChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 78 of file G4INCLDeltaDecayChannel.cc.
View newest version in sPHENIX GitHub at line 78 of file G4INCLDeltaDecayChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), G4INCL::Particle::adjustEnergyFromMomentum(), G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, e, G4INCL::ParticleTable::getINCLMass(), G4INCL::Particle::getMass(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), incidentDirection, INCL_FATAL, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Neutron, G4INCL::ThreeVector::perp(), G4INCL::PiMinus, G4InuclParticleNames::pion(), G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, sampleAngles(), G4INCL::Particle::setHelicity(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), G4INCL::Random::shoot(), t1, t2, theParticle, and G4INCL::UnknownParticle.
void G4INCL::DeltaDecayChannel::sampleAngles (G4double * ctet_par, G4double * stet_par, G4double * phi_par) private
Definition at line 65 of file G4INCLDeltaDecayChannel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLDeltaDecayChannel.cc
References kdfinder::abs(), G4INCL::Particle::getHelicity(), G4INCL::Random::shoot(), G4INCL::Math::sign(), theParticle, and G4INCL::Math::twoPi.
Referenced by fillFinalState().
Member Data Documentation
ThreeVector const G4INCL::DeltaDecayChannel::incidentDirection private
Definition at line 61 of file G4INCLDeltaDecayChannel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4INCLDeltaDecayChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::DeltaDecayChannel::theParticle private
Definition at line 60 of file G4INCLDeltaDecayChannel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLDeltaDecayChannel.hh
Referenced by fillFinalState(), and sampleAngles().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLDeltaDecayChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLDeltaDecayChannel.cc