ECCE @ EIC Software: G4IntraNucleiCascader Class Reference
G4IntraNucleiCascader Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4IntraNucleiCascader.hh>
Public Member Functions
G4IntraNucleiCascader ()
virtual ~G4IntraNucleiCascader ()
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
void rescatter (G4InuclParticle *bullet, G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus, G4CollisionOutput &globalOutput)
void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4CascadeColliderBase
G4CascadeColliderBase (const G4String &name, G4int verbose=0)
virtual ~G4CascadeColliderBase ()
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Protected Member Functions
G4bool initialize (G4InuclParticle *bullet, G4InuclParticle *target)
void newCascade (G4int itry)
void setupCascade ()
void generateCascade ()
G4bool finishCascade ()
void finalize (G4int itry, G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
G4InuclParticle * createTarget (G4V3DNucleus *theNucleus)
void preloadCascade (G4V3DNucleus *theNucleus, G4KineticTrackVector *theSecondaries)
void copyWoundedNucleus (G4V3DNucleus *theNucleus)
void copySecondaries (G4KineticTrackVector *theSecondaries)
void processSecondary (const G4KineticTrack *aSecondary)
void releaseSecondary (const G4KineticTrack *aSecondary)
void processTrappedParticle (const G4CascadParticle &trapped)
void decayTrappedParticle (const G4CascadParticle &trapped)
G4bool particleCanInteract (const G4CascadParticle &cpart) const
Protected Member Functions inherited from G4CascadeColliderBase
virtual G4bool useEPCollider (G4InuclParticle *bullet, G4InuclParticle *target) const
virtual G4bool inelasticInteractionPossible (G4InuclParticle *bullet, G4InuclParticle *target, G4double ekin) const
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &fragment, G4CollisionOutput &output)
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, const std::vector< G4InuclElementaryParticle > &particles)
Protected Member Functions inherited from G4VCascadeCollider
virtual void setName (const G4String &name)
Private Member Functions
G4IntraNucleiCascader (const G4IntraNucleiCascader &)
G4IntraNucleiCascader & operator= (const G4IntraNucleiCascader &)
Private Attributes
G4NucleiModel * model
G4ElementaryParticleCollider * theElementaryParticleCollider
G4CascadeRecoilMaker * theRecoilMaker
G4CascadeCoalescence * theClusterMaker
G4CascadeHistory * theCascadeHistory
G4InuclNuclei * tnuclei
G4InuclNuclei * bnuclei
G4InuclElementaryParticle * bparticle
G4double minimum_recoil_A
G4double coulombBarrier
G4InuclNuclei * nucleusTarget
G4InuclElementaryParticle * protonTarget
G4CollisionOutput output
std::vector< G4CascadParticle > cascad_particles
std::vector< G4CascadParticle > new_cascad_particles
G4ExitonConfiguration theExitonConfiguration
std::vector< G4ThreeVector > hitNucleons
Static Private Attributes
static const G4int itry_max = 100
static const G4int reflection_cut = 50
static const G4double small_ekin = 0.001*MeV
static const G4double quasielast_cut = 1*MeV
Additional Inherited Members
Protected Attributes inherited from G4CascadeColliderBase
G4InteractionCase interCase
G4CascadeCheckBalance * balance
Detailed Description
Definition at line 88 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 88 of file G4IntraNucleiCascader.hh
Constructor & Destructor Documentation
G4IntraNucleiCascader::G4IntraNucleiCascader ()
Definition at line 166 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 166 of file G4IntraNucleiCascader.cc
References G4CascadeParameters::doCoalescence(), G4CascadeParameters::showHistory(), theCascadeHistory, and theClusterMaker.
G4IntraNucleiCascader::~G4IntraNucleiCascader () virtual
Definition at line 181 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 181 of file G4IntraNucleiCascader.cc
References model, nucleusTarget, protonTarget, theCascadeHistory, theClusterMaker, theElementaryParticleCollider, and theRecoilMaker.
G4IntraNucleiCascader::G4IntraNucleiCascader (const G4IntraNucleiCascader &) private
Member Function Documentation
void G4IntraNucleiCascader::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & globalOutput) virtual
Implements G4VCascadeCollider.
Definition at line 204 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 204 of file G4IntraNucleiCascader.cc
References finalize(), finishCascade(), G4cout, G4endl, generateCascade(), initialize(), itry_max, newCascade(), G4CascadeHistory::Print(), setupCascade(), theCascadeHistory, and G4VCascadeCollider::verboseLevel.
Referenced by G4InuclCollider::collide().
void G4IntraNucleiCascader::copySecondaries (G4KineticTrackVector * theSecondaries) protected
Definition at line 738 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 738 of file G4IntraNucleiCascader.cc
References cascad_particles, G4cout, G4endl, G4CollisionOutput::numberOfOutgoingNuclei(), G4CollisionOutput::numberOfOutgoingParticles(), output, processSecondary(), and G4VCascadeCollider::verboseLevel.
Referenced by preloadCascade().
void G4IntraNucleiCascader::copyWoundedNucleus (G4V3DNucleus * theNucleus) protected
Definition at line 707 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 707 of file G4IntraNucleiCascader.cc
References G4Nucleon::AreYouHit(), G4ExitonConfiguration::clear(), G4cout, G4endl, G4V3DNucleus::GetNextNucleon(), G4Nucleon::GetParticleType(), G4Nucleon::GetPosition(), hitNucleons, G4ExitonConfiguration::incrementHoles(), G4ExitonConfiguration::neutronHoles, G4ExitonConfiguration::protonHoles, G4V3DNucleus::StartLoop(), theExitonConfiguration, G4InuclElementaryParticle::type(), and G4VCascadeCollider::verboseLevel.
Referenced by preloadCascade().
G4InuclParticle * G4IntraNucleiCascader::createTarget (G4V3DNucleus * theNucleus) protected
Definition at line 678 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 678 of file G4IntraNucleiCascader.cc
References G4InuclElementaryParticle::fill(), G4InuclNuclei::fill(), G4V3DNucleus::GetCharge(), G4V3DNucleus::GetMassNumber(), G4InuclParticleNames::neutron, nucleusTarget, G4InuclParticleNames::proton, and protonTarget.
Referenced by rescatter().
void G4IntraNucleiCascader::decayTrappedParticle (const G4CascadParticle & trapped) protected
Definition at line 870 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 870 of file G4IntraNucleiCascader.cc
References G4CollisionOutput::addOutgoingParticle(), G4DecayProducts::Boost(), cascad_particles, G4VDecayChannel::DecayIt(), G4DecayProducts::entries(), G4cerr, G4cout, G4endl, G4CascadParticle::getCurrentZone(), G4ParticleDefinition::GetDecayTable(), G4InuclParticle::getDefinition(), G4InuclParticle::getEnergy(), G4CascadParticle::getGeneration(), G4InuclParticle::getMomentum(), G4CascadParticle::getParticle(), G4ParticleDefinition::GetPDGMass(), G4CascadParticle::getPosition(), G4CascadeChannelTables::GetTable(), G4InuclParticle::INCascader, output, G4DecayTable::SelectADecayChannel(), G4InuclElementaryParticle::type(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and G4VCascadeCollider::verboseLevel.
Referenced by processTrappedParticle().
void G4IntraNucleiCascader::finalize (G4int itry, G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & globalOutput) protected
Definition at line 656 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 656 of file G4IntraNucleiCascader.cc
References G4CollisionOutput::add(), G4cout, G4endl, itry_max, output, G4CollisionOutput::trivialise(), and G4VCascadeCollider::verboseLevel.
Referenced by collide(), and rescatter().
G4bool G4IntraNucleiCascader::finishCascade () protected
Definition at line 507 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 507 of file G4IntraNucleiCascader.cc
References kdfinder::abs(), G4CollisionOutput::acceptable(), G4CascadeRecoilMaker::addExcitonConfiguration(), G4CollisionOutput::addOutgoingParticle(), G4CollisionOutput::addOutgoingParticles(), G4CollisionOutput::addRecoilFragment(), cascad_particles, G4CascadeRecoilMaker::collide(), G4CascadeCoalescence::FindClusters(), G4cerr, G4cout, G4endl, G4InteractionCase::getBullet(), G4CollisionOutput::getOutgoingParticles(), G4InuclElementaryParticle::getParticleMass(), G4CascadeRecoilMaker::getRecoilA(), G4CascadeRecoilMaker::getRecoilExcitation(), G4CascadeRecoilMaker::getRecoilMomentum(), G4CascadeRecoilMaker::getRecoilZ(), G4InteractionCase::getTarget(), G4CascadeRecoilMaker::goodFragment(), G4CascadeRecoilMaker::goodNucleus(), G4InuclParticle::INCascader, G4CascadeColliderBase::interCase, CLHEP::HepLorentzVector::m(), G4CascadeRecoilMaker::makeRecoilFragment(), mass, minimum_recoil_A, G4CollisionOutput::numberOfOutgoingParticles(), output, G4CollisionOutput::printCollisionOutput(), quasielast_cut, G4CollisionOutput::setOnShell(), G4CascadeRecoilMaker::setRecoilExcitation(), G4CascadeCoalescence::setVerboseLevel(), G4CollisionOutput::setVerboseLevel(), small_ekin, theClusterMaker, theExitonConfiguration, theRecoilMaker, G4VCascadeCollider::verboseLevel, and G4CascadeRecoilMaker::wholeEvent().
Referenced by collide(), and rescatter().
void G4IntraNucleiCascader::generateCascade () protected
Definition at line 361 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 361 of file G4IntraNucleiCascader.cc
References G4CascadeHistory::AddEntry(), G4CollisionOutput::addOutgoingParticle(), G4CascadeHistory::AddVertex(), cascad_particles, G4CascadeRecoilMaker::collide(), coulombBarrier, G4cout, G4endl, G4Exp(), G4UniformRand, G4InteractionCase::getBullet(), G4InuclParticle::getCharge(), G4InuclParticle::getKineticEnergy(), G4InuclParticle::getMass(), G4CascadParticle::getNumberOfReflections(), G4CollisionOutput::getOutgoingParticles(), G4CascadParticle::getParticle(), G4CascadeRecoilMaker::getRecoilA(), G4InteractionCase::getTarget(), G4InuclNuclei::getZ(), G4ExitonConfiguration::incrementHoles(), G4CascadeColliderBase::interCase, mass, minimum_recoil_A, new_cascad_particles, output, particleCanInteract(), processTrappedParticle(), Q, reflection_cut, theCascadeHistory, theElementaryParticleCollider, theExitonConfiguration, theRecoilMaker, tnuclei, and G4VCascadeCollider::verboseLevel.
Referenced by collide(), and rescatter().
G4bool G4IntraNucleiCascader::initialize (G4InuclParticle * bullet, G4InuclParticle * target) protected
Definition at line 251 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 251 of file G4IntraNucleiCascader.cc
References bnuclei, bparticle, coulombBarrier, CLHEP::HepLorentzVector::e(), G4InuclSpecialFunctions::G4cbrt(), G4cerr, G4cout, G4endl, G4InuclNuclei::getA(), G4InteractionCase::getBullet(), G4InuclParticle::getMomentum(), G4InteractionCase::getTarget(), G4InuclNuclei::getZ(), G4CascadeColliderBase::interCase, minimum_recoil_A, G4InteractionCase::set(), G4CascadeRecoilMaker::setTolerance(), small_ekin, theRecoilMaker, tnuclei, G4VCascadeCollider::verboseLevel, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by collide(), and rescatter().
void G4IntraNucleiCascader::newCascade (G4int itry) protected
Definition at line 303 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 303 of file G4IntraNucleiCascader.cc
References cascad_particles, G4CascadeHistory::Clear(), G4ExitonConfiguration::clear(), G4InteractionCase::code(), G4cout, G4endl, G4CascadeColliderBase::interCase, new_cascad_particles, output, G4CollisionOutput::reset(), theCascadeHistory, theExitonConfiguration, and G4VCascadeCollider::verboseLevel.
Referenced by collide(), and rescatter().
G4IntraNucleiCascader& G4IntraNucleiCascader::operator= (const G4IntraNucleiCascader &) private
G4bool G4IntraNucleiCascader::particleCanInteract (const G4CascadParticle & cpart) const protected
Definition at line 930 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 930 of file G4IntraNucleiCascader.cc
References G4CascadParticle::getParticle(), G4CascadeChannelTables::GetTable(), and G4InuclElementaryParticle::type().
Referenced by generateCascade().
void G4IntraNucleiCascader::preloadCascade (G4V3DNucleus * theNucleus, G4KineticTrackVector * theSecondaries) protected
Definition at line 698 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 698 of file G4IntraNucleiCascader.cc
References copySecondaries(), copyWoundedNucleus(), G4cout, G4endl, and G4VCascadeCollider::verboseLevel.
Referenced by rescatter().
void G4IntraNucleiCascader::processSecondary (const G4KineticTrack * aSecondary) protected
Definition at line 763 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 763 of file G4IntraNucleiCascader.cc
References cascad_particles, G4InuclElementaryParticle::fill(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4CascadParticle::getParticle(), G4ParticleDefinition::GetParticleName(), G4KineticTrack::GetPosition(), GeV, G4CascadParticle::initializePath(), CLHEP::Hep3Vector::mag(), releaseSecondary(), G4CascadParticle::setGeneration(), G4CascadParticle::setMovingInsideNuclei(), G4InuclElementaryParticle::type(), G4CascadParticle::updatePosition(), G4CascadParticle::updateZone(), and G4VCascadeCollider::verboseLevel.
Referenced by copySecondaries().
void G4IntraNucleiCascader::processTrappedParticle (const G4CascadParticle & trapped) protected
Definition at line 838 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 838 of file G4IntraNucleiCascader.cc
References G4CollisionOutput::addOutgoingParticle(), decayTrappedParticle(), G4CascadeHistory::DropEntry(), G4cout, G4endl, G4CascadParticle::getParticle(), G4InuclElementaryParticle::hyperon(), G4ExitonConfiguration::incrementQP(), G4InuclElementaryParticle::nucleon(), output, theCascadeHistory, theExitonConfiguration, G4InuclElementaryParticle::type(), and G4VCascadeCollider::verboseLevel.
Referenced by generateCascade().
void G4IntraNucleiCascader::releaseSecondary (const G4KineticTrack * aSecondary) protected
Definition at line 804 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 804 of file G4IntraNucleiCascader.cc
References G4InuclElementaryParticle::fill(), G4InuclNuclei::fill(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4KineticTrack::GetDefinition(), G4CollisionOutput::getOutgoingNuclei(), G4CollisionOutput::getOutgoingParticles(), G4ParticleDefinition::GetParticleName(), GeV, ipart, G4CollisionOutput::numberOfOutgoingNuclei(), G4CollisionOutput::numberOfOutgoingParticles(), output, and G4VCascadeCollider::verboseLevel.
Referenced by processSecondary().
void G4IntraNucleiCascader::rescatter (G4InuclParticle * bullet, G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus, G4CollisionOutput & globalOutput) virtual
Reimplemented from G4CascadeColliderBase.
Definition at line 227 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 227 of file G4IntraNucleiCascader.cc
References createTarget(), finalize(), finishCascade(), G4cout, G4endl, generateCascade(), initialize(), itry_max, newCascade(), preloadCascade(), G4CascadeHistory::Print(), theCascadeHistory, and G4VCascadeCollider::verboseLevel.
Referenced by G4InuclCollider::rescatter().
void G4IntraNucleiCascader::setupCascade () protected
Definition at line 321 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 321 of file G4IntraNucleiCascader.cc
References ab, G4CollisionOutput::addOutgoingParticles(), G4InuclElementaryParticle::baryon(), bnuclei, bparticle, cascad_particles, G4cout, G4endl, G4InuclNuclei::getA(), G4InuclParticle::getCharge(), G4InuclNuclei::getZ(), G4InteractionCase::hadNucleus(), G4ExitonConfiguration::incrementHoles(), G4ExitonConfiguration::incrementQP(), G4CascadeColliderBase::interCase, G4InuclSpecialFunctions::inuclRndm(), output, theExitonConfiguration, tnuclei, and G4VCascadeCollider::verboseLevel.
Referenced by collide().
void G4IntraNucleiCascader::setVerboseLevel (G4int verbose = 0) virtual
Reimplemented from G4CascadeColliderBase.
Definition at line 191 of file G4IntraNucleiCascader.cc.
View newest version in sPHENIX GitHub at line 191 of file G4IntraNucleiCascader.cc
References G4CascadeHistory::setVerboseLevel(), G4VCascadeCollider::setVerboseLevel(), G4CascadeCoalescence::setVerboseLevel(), G4CascadeColliderBase::setVerboseLevel(), theCascadeHistory, theClusterMaker, theElementaryParticleCollider, and theRecoilMaker.
Referenced by G4InuclCollider::setVerboseLevel().
Member Data Documentation
G4InuclNuclei* G4IntraNucleiCascader::bnuclei private
Definition at line 146 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 146 of file G4IntraNucleiCascader.hh
Referenced by initialize(), and setupCascade().
G4InuclElementaryParticle* G4IntraNucleiCascader::bparticle private
Definition at line 147 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 147 of file G4IntraNucleiCascader.hh
Referenced by initialize(), and setupCascade().
std::vector<G4CascadParticle> G4IntraNucleiCascader::cascad_particles private
Definition at line 158 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 158 of file G4IntraNucleiCascader.hh
Referenced by copySecondaries(), decayTrappedParticle(), finishCascade(), generateCascade(), newCascade(), processSecondary(), and setupCascade().
G4double G4IntraNucleiCascader::coulombBarrier private
Definition at line 150 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 150 of file G4IntraNucleiCascader.hh
Referenced by generateCascade(), and initialize().
std::vector<G4ThreeVector> G4IntraNucleiCascader::hitNucleons private
Definition at line 162 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 162 of file G4IntraNucleiCascader.hh
Referenced by copyWoundedNucleus().
const G4int G4IntraNucleiCascader::itry_max = 100 static private
Definition at line 103 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 103 of file G4IntraNucleiCascader.hh
Referenced by collide(), finalize(), and rescatter().
G4double G4IntraNucleiCascader::minimum_recoil_A private
Definition at line 149 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 149 of file G4IntraNucleiCascader.hh
Referenced by finishCascade(), generateCascade(), and initialize().
G4NucleiModel* G4IntraNucleiCascader::model private
Definition at line 138 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 138 of file G4IntraNucleiCascader.hh
Referenced by ~G4IntraNucleiCascader().
std::vector<G4CascadParticle> G4IntraNucleiCascader::new_cascad_particles private
Definition at line 159 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 159 of file G4IntraNucleiCascader.hh
Referenced by generateCascade(), and newCascade().
G4InuclNuclei* G4IntraNucleiCascader::nucleusTarget private
Definition at line 153 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 153 of file G4IntraNucleiCascader.hh
Referenced by createTarget(), and ~G4IntraNucleiCascader().
G4CollisionOutput G4IntraNucleiCascader::output private
Definition at line 157 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 157 of file G4IntraNucleiCascader.hh
Referenced by copySecondaries(), decayTrappedParticle(), finalize(), finishCascade(), generateCascade(), newCascade(), processTrappedParticle(), releaseSecondary(), and setupCascade().
G4InuclElementaryParticle* G4IntraNucleiCascader::protonTarget private
Definition at line 154 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 154 of file G4IntraNucleiCascader.hh
Referenced by createTarget(), and ~G4IntraNucleiCascader().
const G4double G4IntraNucleiCascader::quasielast_cut = 1*MeV static private
Definition at line 106 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 106 of file G4IntraNucleiCascader.hh
Referenced by finishCascade().
const G4int G4IntraNucleiCascader::reflection_cut = 50 static private
Definition at line 104 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 104 of file G4IntraNucleiCascader.hh
Referenced by generateCascade().
const G4double G4IntraNucleiCascader::small_ekin = 0.001*MeV static private
Definition at line 105 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 105 of file G4IntraNucleiCascader.hh
Referenced by finishCascade(), and initialize().
G4CascadeHistory* G4IntraNucleiCascader::theCascadeHistory private
Definition at line 142 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 142 of file G4IntraNucleiCascader.hh
Referenced by collide(), G4IntraNucleiCascader(), generateCascade(), newCascade(), processTrappedParticle(), rescatter(), setVerboseLevel(), and ~G4IntraNucleiCascader().
G4CascadeCoalescence* G4IntraNucleiCascader::theClusterMaker private
Definition at line 141 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 141 of file G4IntraNucleiCascader.hh
Referenced by finishCascade(), G4IntraNucleiCascader(), setVerboseLevel(), and ~G4IntraNucleiCascader().
G4ElementaryParticleCollider* G4IntraNucleiCascader::theElementaryParticleCollider private
Definition at line 139 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 139 of file G4IntraNucleiCascader.hh
Referenced by generateCascade(), setVerboseLevel(), and ~G4IntraNucleiCascader().
G4ExitonConfiguration G4IntraNucleiCascader::theExitonConfiguration private
Definition at line 160 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 160 of file G4IntraNucleiCascader.hh
Referenced by copyWoundedNucleus(), finishCascade(), generateCascade(), newCascade(), processTrappedParticle(), and setupCascade().
G4CascadeRecoilMaker* G4IntraNucleiCascader::theRecoilMaker private
Definition at line 140 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 140 of file G4IntraNucleiCascader.hh
Referenced by finishCascade(), generateCascade(), initialize(), setVerboseLevel(), and ~G4IntraNucleiCascader().
G4InuclNuclei* G4IntraNucleiCascader::tnuclei private
Definition at line 145 of file G4IntraNucleiCascader.hh.
View newest version in sPHENIX GitHub at line 145 of file G4IntraNucleiCascader.hh
Referenced by generateCascade(), initialize(), and setupCascade().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4IntraNucleiCascader.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4IntraNucleiCascader.cc