ECCE @ EIC Software: G4INCL::DeuteronDensity Namespace Reference
G4INCL::DeuteronDensity Namespace Reference
Static class for the deuteron density.
Functions
G4double densityR (const G4double r)
PDF for a nucleon in r space.
G4double derivDensityR (const G4double r)
First derivative of the r-space density function.
G4double densityP (const G4double p)
PDF for a nucleon in p space.
G4double wavefunctionR (const G4int l, const G4double r)
G4double wavefunctionP (const G4int l, const G4double p)
G4double derivWavefunctionR (const G4int l, const G4double r)
Detailed Description
Static class for the deuteron density.
Function Documentation
G4double G4INCL::DeuteronDensity::densityP (const G4double p)
PDF for a nucleon in p space.
The distribution is normalised to 1.
Parameters
p nucleon momentum [MeV/c]
Returns
4 * pi * p^2 * d|psi|^2/dp
Definition at line 117 of file G4INCLDeuteronDensity.cc.
View newest version in sPHENIX GitHub at line 117 of file G4INCLDeuteronDensity.cc
References wavefunctionP().
Referenced by G4INCL::NuclearDensityFunctions::ParisP::operator()().
G4double G4INCL::DeuteronDensity::densityR (const G4double r)
PDF for a nucleon in r space.
The distribution is normalised to 1.
Parameters
r distance from the deuteron centre [fm]
Returns
4 * pi * r^2 * |psi|^2
Definition at line 103 of file G4INCLDeuteronDensity.cc.
View newest version in sPHENIX GitHub at line 103 of file G4INCLDeuteronDensity.cc
References wavefunctionR().
Referenced by G4INCL::NuclearDensityFunctions::ParisR::operator()().
G4double G4INCL::DeuteronDensity::derivDensityR (const G4double r)
First derivative of the r-space density function.
Parameters
r distance from the deuteron centre [fm]
Returns
d|psi|^2/dr
Definition at line 109 of file G4INCLDeuteronDensity.cc.
View newest version in sPHENIX GitHub at line 109 of file G4INCLDeuteronDensity.cc
References derivWavefunctionR(), G4INCL::Math::twoPi, and wavefunctionR().
G4double G4INCL::DeuteronDensity::derivWavefunctionR (const G4int l, const G4double r)
Definition at line 143 of file G4INCLDeuteronDensity.cc.
View newest version in sPHENIX GitHub at line 143 of file G4INCLDeuteronDensity.cc
References e, max, and r.
Referenced by derivDensityR().
G4double G4INCL::DeuteronDensity::wavefunctionP (const G4int l, const G4double p)
Definition at line 163 of file G4INCLDeuteronDensity.cc.
View newest version in sPHENIX GitHub at line 163 of file G4INCLDeuteronDensity.cc
References G4INCL::PhysicalConstants::hc.
Referenced by densityP().
G4double G4INCL::DeuteronDensity::wavefunctionR (const G4int l, const G4double r)
Definition at line 123 of file G4INCLDeuteronDensity.cc.
View newest version in sPHENIX GitHub at line 123 of file G4INCLDeuteronDensity.cc
References e, max, and r.
Referenced by densityR(), and derivDensityR().