ECCE @ EIC Software: ExN04StackingActionMessenger Class Reference
ExN04StackingActionMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04StackingActionMessenger.hh>
Public Member Functions
ExN04StackingActionMessenger (ExN04StackingAction *msa)
~ExN04StackingActionMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
virtual G4String GetCurrentValue (G4UIcommand *command)
ExN04StackingActionMessenger (ExN04StackingAction *msa)
~ExN04StackingActionMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
ExN04StackingAction * fMyAction
G4UIcmdWithAnInteger * fMuonCmd
G4UIcmdWithAnInteger * fIsoMuonCmd
G4UIcmdWithAnInteger * fIsoCmd
G4UIcmdWithADoubleAndUnit * fRoiCmd
ExN04StackingAction * myAction
G4UIcmdWithAnInteger * muonCmd
G4UIcmdWithAnInteger * isomuonCmd
G4UIcmdWithAnInteger * isoCmd
G4UIcmdWithADoubleAndUnit * roiCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 41 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 41 of file ExN04StackingActionMessenger.hh
Constructor & Destructor Documentation
ExN04StackingActionMessenger::ExN04StackingActionMessenger (ExN04StackingAction * msa)
Definition at line 39 of file ExN04StackingActionMessenger.cc.
View newest version in sPHENIX GitHub at line 39 of file ExN04StackingActionMessenger.cc
ExN04StackingActionMessenger::~ExN04StackingActionMessenger ()
Definition at line 69 of file ExN04StackingActionMessenger.cc.
View newest version in sPHENIX GitHub at line 69 of file ExN04StackingActionMessenger.cc
References fIsoCmd, fIsoMuonCmd, fMuonCmd, and fRoiCmd.
ExN04StackingActionMessenger::ExN04StackingActionMessenger (ExN04StackingAction * msa)
ExN04StackingActionMessenger::~ExN04StackingActionMessenger ()
Member Function Documentation
G4String ExN04StackingActionMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 92 of file ExN04StackingActionMessenger.cc.
View newest version in sPHENIX GitHub at line 92 of file ExN04StackingActionMessenger.cc
References G4UIcommand::ConvertToString(), fIsoCmd, fIsoMuonCmd, fMuonCmd, fMyAction, fRoiCmd, ExN04StackingAction::GetNIsolation(), ExN04StackingAction::GetNRequestIsoMuon(), ExN04StackingAction::GetNRequestMuon(), and ExN04StackingAction::GetRoIAngle().
G4String ExN04StackingActionMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
void ExN04StackingActionMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 79 of file ExN04StackingActionMessenger.cc.
View newest version in sPHENIX GitHub at line 79 of file ExN04StackingActionMessenger.cc
void ExN04StackingActionMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Member Data Documentation
G4UIcmdWithAnInteger* ExN04StackingActionMessenger::fIsoCmd private
Definition at line 54 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04StackingActionMessenger.hh
Referenced by GetCurrentValue(), and ~ExN04StackingActionMessenger().
G4UIcmdWithAnInteger* ExN04StackingActionMessenger::fIsoMuonCmd private
Definition at line 53 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file ExN04StackingActionMessenger.hh
Referenced by GetCurrentValue(), and ~ExN04StackingActionMessenger().
G4UIcmdWithAnInteger* ExN04StackingActionMessenger::fMuonCmd private
Definition at line 52 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 52 of file ExN04StackingActionMessenger.hh
Referenced by GetCurrentValue(), and ~ExN04StackingActionMessenger().
ExN04StackingAction* ExN04StackingActionMessenger::fMyAction private
Definition at line 50 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file ExN04StackingActionMessenger.hh
Referenced by GetCurrentValue().
G4UIcmdWithADoubleAndUnit* ExN04StackingActionMessenger::fRoiCmd private
Definition at line 55 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04StackingActionMessenger.hh
Referenced by GetCurrentValue(), and ~ExN04StackingActionMessenger().
G4UIcmdWithAnInteger* ExN04StackingActionMessenger::isoCmd private
Definition at line 57 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04StackingActionMessenger.hh
G4UIcmdWithAnInteger* ExN04StackingActionMessenger::isomuonCmd private
Definition at line 56 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file ExN04StackingActionMessenger.hh
G4UIcmdWithAnInteger* ExN04StackingActionMessenger::muonCmd private
Definition at line 55 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04StackingActionMessenger.hh
ExN04StackingAction* ExN04StackingActionMessenger::myAction private
Definition at line 52 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 52 of file ExN04StackingActionMessenger.hh
G4UIcmdWithADoubleAndUnit* ExN04StackingActionMessenger::roiCmd private
Definition at line 58 of file ExN04StackingActionMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file ExN04StackingActionMessenger.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04StackingActionMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04StackingActionMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04StackingActionMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04StackingActionMessenger.cc