ECCE @ EIC Software: PHG4FPbScRegionSteppingAction Class Reference
PHG4FPbScRegionSteppingAction Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4FPbScRegionSteppingAction.h>
Public Member Functions
PHG4FPbScRegionSteppingAction (PHG4FPbScDetector *)
constructor
virtual ~PHG4FPbScRegionSteppingAction ()
destroctor
virtual void UserSteppingAction (const G4Step *)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
PHG4FPbScDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 14 of file PHG4FPbScRegionSteppingAction.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4FPbScRegionSteppingAction.h
Constructor & Destructor Documentation
PHG4FPbScRegionSteppingAction::PHG4FPbScRegionSteppingAction (PHG4FPbScDetector * detector)
constructor
Definition at line 31 of file PHG4FPbScRegionSteppingAction.cc.
View newest version in sPHENIX GitHub at line 31 of file PHG4FPbScRegionSteppingAction.cc
virtual PHG4FPbScRegionSteppingAction::~PHG4FPbScRegionSteppingAction () inline virtual
destroctor
Definition at line 21 of file PHG4FPbScRegionSteppingAction.h.
View newest version in sPHENIX GitHub at line 21 of file PHG4FPbScRegionSteppingAction.h
Member Function Documentation
void PHG4FPbScRegionSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Definition at line 125 of file PHG4FPbScRegionSteppingAction.cc.
View newest version in sPHENIX GitHub at line 125 of file PHG4FPbScRegionSteppingAction.cc
References detector_, PHG4Detector::GetName(), and hits_.
void PHG4FPbScRegionSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
stepping action
Reimplemented from G4UserSteppingAction.
Definition at line 39 of file PHG4FPbScRegionSteppingAction.cc.
View newest version in sPHENIX GitHub at line 39 of file PHG4FPbScRegionSteppingAction.cc
References PHG4HitContainer::AddHit(), cm, detector_, edep, fGeomBoundary, fUndefined, PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), G4StepPoint::GetGlobalTime(), PHG4HitContainer::GetID(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetUserInformation(), G4VTouchable::GetVolume(), GeV, hit, hits_, PHG4FPbScDetector::isInScintillator(), nanosecond, G4InuclParticleNames::pp, PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), Acts::Test::volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
PHG4FPbScDetector* PHG4FPbScRegionSteppingAction::detector_ private
pointer to the detector
Definition at line 33 of file PHG4FPbScRegionSteppingAction.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4FPbScRegionSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4FPbScRegionSteppingAction::hit private
Definition at line 37 of file PHG4FPbScRegionSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4FPbScRegionSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4FPbScRegionSteppingAction::hits_ private
pointer to hit container
Definition at line 36 of file PHG4FPbScRegionSteppingAction.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4FPbScRegionSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4FPbScRegionSteppingAction.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4FPbScRegionSteppingAction.cc