ECCE @ EIC Software: G4FermiBreakUpVI Class Reference
G4FermiBreakUpVI Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiBreakUpVI.hh>
Public Member Functions
G4FermiBreakUpVI ()
~G4FermiBreakUpVI () final
void Initialise () final
G4bool IsApplicable (G4int ZZ, G4int AA, G4double etot) const final
void BreakFragment (G4FragmentVector *, G4Fragment *theNucleus) final
Public Member Functions inherited from G4VFermiBreakUp
G4VFermiBreakUp ()
virtual ~G4VFermiBreakUp ()
void SetVerbose (G4int val)
Private Member Functions
void InitialisePool ()
G4bool SampleDecay ()
G4FermiBreakUpVI (const G4FermiBreakUpVI &right)=delete
const G4FermiBreakUpVI & operator= (const G4FermiBreakUpVI &right)=delete
G4bool operator== (const G4FermiBreakUpVI &right) const =delete
G4bool operator!= (const G4FermiBreakUpVI &right) const =delete
Private Attributes
const G4FermiDecayProbability * theDecay
CLHEP::HepRandomEngine * rndmEngine
G4int maxZ
G4int maxA
G4int Z
G4int A
G4int spin
G4double mass
G4double excitation
G4double tolerance
G4double elim
const G4FermiFragment * frag1
const G4FermiFragment * frag2
G4LorentzVector lv0
G4ThreeVector boostVector
std::vector< G4double > prob
std::vector< const
G4FermiFragment * > frag
std::vector< G4LorentzVector > lvect
Static Private Attributes
static G4FermiFragmentsPoolVI * thePool = nullptr
Additional Inherited Members
Protected Attributes inherited from G4VFermiBreakUp
G4int verbose
Detailed Description
Definition at line 46 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 46 of file G4FermiBreakUpVI.hh
Constructor & Destructor Documentation
G4FermiBreakUpVI::G4FermiBreakUpVI () explicit
Definition at line 46 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 46 of file G4FermiBreakUpVI.cc
References A, elim, excitation, frag, frag1, frag2, Initialise(), lvect, mass, CLHEP::MeV, prob, spin, tolerance, and Z.
G4FermiBreakUpVI::~G4FermiBreakUpVI () final
Definition at line 59 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 59 of file G4FermiBreakUpVI.cc
References G4Threading::IsMasterThread(), and thePool.
G4FermiBreakUpVI::G4FermiBreakUpVI (const G4FermiBreakUpVI & right) private delete
Member Function Documentation
void G4FermiBreakUpVI::BreakFragment (G4FragmentVector * theResult, G4Fragment * theNucleus) final virtual
Implements G4VFermiBreakUp.
Definition at line 96 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 96 of file G4FermiBreakUpVI.cc
References A, excitation, f, frag, G4cout, G4endl, G4Fragment::GetA_asInt(), G4Fragment::GetCreationTime(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4Fragment::GetMomentum(), G4Fragment::GetZ_asInt(), imax, lv0, lvect, mass, rndmEngine, SampleDecay(), G4Fragment::SetCreationTime(), G4Fragment::SetSpin(), spin, Acts::VectorHelpers::time(), G4VFermiBreakUp::verbose, and Z.
void G4FermiBreakUpVI::Initialise () final virtual
Implements G4VFermiBreakUp.
Definition at line 67 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 67 of file G4FermiBreakUpVI.cc
References elim, G4FermiFragmentsPoolVI::FermiDecayProbability(), G4cout, G4endl, G4FermiFragmentsPoolVI::GetEnergyLimit(), InitialisePool(), theDecay, thePool, and G4VFermiBreakUp::verbose.
Referenced by G4FermiBreakUpVI().
void G4FermiBreakUpVI::InitialisePool () private
Definition at line 77 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 77 of file G4FermiBreakUpVI.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and thePool.
Referenced by Initialise().
G4bool G4FermiBreakUpVI::IsApplicable (G4int ZZ, G4int AA, G4double etot) const final virtual
Implements G4VFermiBreakUp.
Definition at line 90 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 90 of file G4FermiBreakUpVI.cc
References elim, G4FermiFragmentsPoolVI::HasChannels(), maxZ, and thePool.
G4bool G4FermiBreakUpVI::operator!= (const G4FermiBreakUpVI & right) const private delete
const G4FermiBreakUpVI& G4FermiBreakUpVI::operator= (const G4FermiBreakUpVI & right) private delete
G4bool G4FermiBreakUpVI::operator== (const G4FermiBreakUpVI & right) const private delete
G4bool G4FermiBreakUpVI::SampleDecay () private
Definition at line 156 of file G4FermiBreakUpVI.cc.
View newest version in sPHENIX GitHub at line 156 of file G4FermiBreakUpVI.cc
References A, kdfinder::abs(), CLHEP::HepLorentzVector::boost(), boostVector, CLHEP::HepLorentzVector::boostVector(), G4FermiFragmentsPoolVI::ClosestChannels(), G4FermiDecayProbability::ComputeProbability(), CLHEP::HepLorentzVector::e(), e1, e2, excitation, CLHEP::HepRandomEngine::flat(), frag, frag1, frag2, G4cout, G4endl, G4RandomDirection(), G4FermiChannels::GetChannels(), G4FermiChannels::GetExcitation(), G4FermiFragment::GetExcitationEnergy(), G4FermiPair::GetFragment1(), G4FermiPair::GetFragment2(), G4FermiChannels::GetNumberOfChannels(), G4FermiChannels::GetPair(), G4FermiFragment::GetTotalEnergy(), lv0, lvect, mass, G4InuclParticleNames::nn, prob, rndmEngine, G4FermiChannels::SamplePair(), CLHEP::HepLorentzVector::set(), theDecay, thePool, tolerance, v, G4VFermiBreakUp::verbose, and Z.
Referenced by BreakFragment().
Member Data Documentation
G4int G4FermiBreakUpVI::A private
Definition at line 84 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 84 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), G4FermiBreakUpVI(), and SampleDecay().
G4ThreeVector G4FermiBreakUpVI::boostVector private
Definition at line 96 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 96 of file G4FermiBreakUpVI.hh
Referenced by SampleDecay().
G4double G4FermiBreakUpVI::elim private
Definition at line 90 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FermiBreakUpVI.hh
Referenced by G4FermiBreakUpVI(), Initialise(), and IsApplicable().
G4double G4FermiBreakUpVI::excitation private
Definition at line 88 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 88 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), G4FermiBreakUpVI(), and SampleDecay().
std::vector<const G4FermiFragment*> G4FermiBreakUpVI::frag private
Definition at line 99 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 99 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), G4FermiBreakUpVI(), and SampleDecay().
const G4FermiFragment* G4FermiBreakUpVI::frag1 private
Definition at line 92 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 92 of file G4FermiBreakUpVI.hh
Referenced by G4FermiBreakUpVI(), and SampleDecay().
const G4FermiFragment* G4FermiBreakUpVI::frag2 private
Definition at line 93 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 93 of file G4FermiBreakUpVI.hh
Referenced by G4FermiBreakUpVI(), and SampleDecay().
G4LorentzVector G4FermiBreakUpVI::lv0 private
Definition at line 95 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 95 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), and SampleDecay().
std::vector<G4LorentzVector> G4FermiBreakUpVI::lvect private
Definition at line 100 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 100 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), G4FermiBreakUpVI(), and SampleDecay().
G4double G4FermiBreakUpVI::mass private
Definition at line 87 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 87 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), G4FermiBreakUpVI(), and SampleDecay().
G4int G4FermiBreakUpVI::maxA private
Definition at line 81 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FermiBreakUpVI.hh
G4int G4FermiBreakUpVI::maxZ private
Definition at line 80 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FermiBreakUpVI.hh
Referenced by IsApplicable().
std::vector<G4double> G4FermiBreakUpVI::prob private
Definition at line 98 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 98 of file G4FermiBreakUpVI.hh
Referenced by G4FermiBreakUpVI(), and SampleDecay().
CLHEP::HepRandomEngine* G4FermiBreakUpVI::rndmEngine private
Definition at line 78 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), and SampleDecay().
G4int G4FermiBreakUpVI::spin private
Definition at line 85 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 85 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), and G4FermiBreakUpVI().
const G4FermiDecayProbability* G4FermiBreakUpVI::theDecay private
Definition at line 76 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FermiBreakUpVI.hh
Referenced by Initialise(), and SampleDecay().
G4FermiFragmentsPoolVI * G4FermiBreakUpVI::thePool = nullptr static private
Definition at line 75 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FermiBreakUpVI.hh
Referenced by Initialise(), InitialisePool(), IsApplicable(), SampleDecay(), and ~G4FermiBreakUpVI().
G4double G4FermiBreakUpVI::tolerance private
Definition at line 89 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 89 of file G4FermiBreakUpVI.hh
Referenced by G4FermiBreakUpVI(), and SampleDecay().
G4int G4FermiBreakUpVI::Z private
Definition at line 83 of file G4FermiBreakUpVI.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FermiBreakUpVI.hh
Referenced by BreakFragment(), G4FermiBreakUpVI(), and SampleDecay().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiBreakUpVI.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/src/G4FermiBreakUpVI.cc