ECCE @ EIC Software: G4Transportation Class Reference
G4Transportation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4Transportation.hh>
Public Member Functions
G4Transportation (G4int verbosityLevel=1)
~G4Transportation ()
G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &stepData)
G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4ForceCondition *pForceCond)
G4bool FieldExertedForce ()
G4PropagatorInField * GetPropagatorInField ()
void SetPropagatorInField (G4PropagatorInField *pFieldPropagator)
G4double GetThresholdWarningEnergy () const
G4double GetThresholdImportantEnergy () const
G4int GetThresholdTrials () const
void SetThresholdWarningEnergy (G4double newEnWarn)
void SetThresholdImportantEnergy (G4double newEnImp)
void SetThresholdTrials (G4int newMaxTrials)
void SetHighLooperThresholds ()
void SetLowLooperThresholds ()
void PushThresholdsToLogger ()
void ReportLooperThresholds ()
G4double GetMaxEnergyKilled () const
G4double GetSumEnergyKilled () const
void ResetKilledStatistics (G4int report=1)
void EnableShortStepOptimisation (G4bool optimise=true)
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
void StartTracking (G4Track *aTrack)
virtual void ProcessDescription (std::ostream &outFile) const
void PrintStatistics (std::ostream &outStr) const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static G4bool EnableMagneticMoment (G4bool useMoment=true)
static G4bool EnableGravity (G4bool useGravity=true)
static void SetSilenceLooperWarnings (G4bool val)
static G4bool GetSilenceLooperWarnings ()
static G4bool EnableUseMagneticMoment (G4bool useMoment=true)
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions
G4bool DoesAnyFieldExist ()
void ReportMissingLogger (const char *methodName)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Attributes
G4Navigator * fLinearNavigator
G4PropagatorInField * fFieldPropagator
G4ThreeVector fTransportEndPosition = G4ThreeVector(0.0, 0.0, 0.0)
G4ThreeVector fTransportEndMomentumDir = G4ThreeVector(0.0, 0.0, 0.0)
G4double fTransportEndKineticEnergy = 0.0
G4ThreeVector fTransportEndSpin = G4ThreeVector(0.0, 0.0, 0.0)
G4bool fMomentumChanged = true
G4bool fEndGlobalTimeComputed = false
G4double fCandidateEndGlobalTime = 0.0
G4bool fAnyFieldExists = false
G4bool fParticleIsLooping = false
G4bool fNewTrack = true
G4bool fFirstStepInVolume = true
G4bool fLastStepInVolume = false
G4bool fGeometryLimitedStep = true
G4bool fFieldExertedForce = false
G4TouchableHandle fCurrentTouchableHandle
G4ThreeVector fPreviousSftOrigin
G4double fPreviousSafety
G4ParticleChangeForTransport fParticleChange
G4double fEndPointDistance
G4double fThreshold_Warning_Energy = 1.0 * CLHEP::keV
G4double fThreshold_Important_Energy = 1.0 * CLHEP::MeV
G4int fThresholdTrials = 10
G4int fAbandonUnstableTrials = 0
G4int fNoLooperTrials = 0
G4double fSumEnergyKilled = 0.0
G4double fSumEnerSqKilled = 0.0
G4double fMaxEnergyKilled = -1.0
G4int fMaxEnergyKilledPDG = 0
unsigned long fNumLoopersKilled = 0
G4double fSumEnergyKilled_NonElectron = 0.0
G4double fSumEnerSqKilled_NonElectron = 0.0
G4double fMaxEnergyKilled_NonElectron = -1.0
G4int fMaxEnergyKilled_NonElecPDG = 0
unsigned long fNumLoopersKilled_NonElectron = 0
G4double fSumEnergySaved = 0.0
G4double fMaxEnergySaved = -1.0
G4double fSumEnergyUnstableSaved = 0.0
G4bool fShortStepOptimisation
G4SafetyHelper * fpSafetyHelper
G4TransportationLogger * fpLogger
Static Private Attributes
static G4bool fUseMagneticMoment =false
static G4bool fUseGravity = false
static G4bool fSilenceLooperWarnings = false
Friends
class G4CoupledTransportation
Additional Inherited Members
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 60 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 60 of file G4Transportation.hh
Constructor & Destructor Documentation
G4Transportation::G4Transportation (G4int verbosityLevel = 1)
Definition at line 69 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 69 of file G4Transportation.cc
References DoesAnyFieldExist(), fAnyFieldExists, fCurrentTouchableHandle, fFieldPropagator, fLinearNavigator, fParticleChange, fpLogger, fpSafetyHelper, fShortStepOptimisation, G4cout, G4endl, G4ThreadLocal, G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, PushThresholdsToLogger(), SetHighLooperThresholds(), G4VProcess::SetProcessSubType(), G4VProcess::SetVerboseLevel(), TRANSPORTATION, and G4VProcess::verboseLevel.
G4Transportation::~G4Transportation ()
Definition at line 127 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 127 of file G4Transportation.cc
References fpLogger, fSumEnergyKilled, G4cout, and PrintStatistics().
Member Function Documentation
G4VParticleChange * G4Transportation::AlongStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 536 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 536 of file G4Transportation.cc
References fAbandonUnstableTrials, fCandidateEndGlobalTime, fEndGlobalTimeComputed, fFieldPropagator, fMaxEnergyKilled, fMaxEnergyKilled_NonElecPDG, fMaxEnergyKilled_NonElectron, fMaxEnergyKilledPDG, fMaxEnergySaved, fMomentumChanged, fNoLooperTrials, fNumLoopersKilled, fNumLoopersKilled_NonElectron, fParticleChange, fParticleIsLooping, fpLogger, fSilenceLooperWarnings, fStopAndKill, fSumEnergyKilled, fSumEnergyKilled_NonElectron, fSumEnergySaved, fSumEnergyUnstableSaved, fSumEnerSqKilled, fSumEnerSqKilled_NonElectron, fThreshold_Important_Energy, fThreshold_Warning_Energy, fThresholdTrials, fTransportEndKineticEnergy, fTransportEndMomentumDir, fTransportEndPosition, fTransportEndSpin, G4cout, G4endl, G4ThreadLocal, G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetLocalTime(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetPDGStable(), G4Step::GetPreStepPoint(), G4Track::GetProperTime(), G4Track::GetStepLength(), G4Track::GetTotalEnergy(), G4StepPoint::GetVelocity(), G4PropagatorInField::GimmeTrajectoryVectorAndForgetIt(), G4ParticleChangeForTransport::Initialize(), max, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeGlobalTime(), G4ParticleChange::ProposeLocalTime(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4ParticleChange::ProposePosition(), G4ParticleChange::ProposeProperTime(), G4VParticleChange::ProposeTrackStatus(), G4TransportationLogger::ReportLoopingTrack(), G4ParticleChangeForTransport::SetMomentumChanged(), G4ParticleChangeForTransport::SetPointerToVectorOfAuxiliaryPoints(), and G4VProcess::verboseLevel.
G4double G4Transportation::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 182 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 182 of file G4Transportation.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PropagatorInField::ComputeStep(), G4Navigator::ComputeStep(), G4FieldManager::ConfigureForTrack(), G4FieldManager::DoesFieldChangeEnergy(), false, fCandidateEndGlobalTime, fEndGlobalTimeComputed, fEndPointDistance, fFieldExertedForce, fFieldPropagator, fFirstStepInVolume, fGeometryLimitedStep, G4PropagatorInField::FindAndSetFieldManager(), fLastStepInVolume, fLinearNavigator, fMomentumChanged, fNewTrack, fParticleChange, fParticleIsLooping, fPreviousSafety, fPreviousSftOrigin, fpSafetyHelper, fShortStepOptimisation, fThreshold_Important_Energy, fTransportEndKineticEnergy, fTransportEndMomentumDir, fTransportEndPosition, fTransportEndSpin, fUseGravity, fUseMagneticMoment, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4DynamicParticle::GetCharge(), G4PropagatorInField::GetCurrentEquationOfMotion(), G4PropagatorInField::GetCurrentFieldManager(), G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4FieldTrack::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4FieldTrack::GetLabTimeOfFlight(), G4DynamicParticle::GetMagneticMoment(), G4DynamicParticle::GetMass(), G4FieldTrack::GetMomentumDir(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGSpin(), G4Track::GetPolarization(), G4FieldTrack::GetPosition(), G4Track::GetPosition(), G4FieldTrack::GetSpin(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetVolume(), G4Field::IsGravityActive(), G4PropagatorInField::IsLastStepInVolume(), G4PropagatorInField::IsParticleLooping(), JustWarning, CLHEP::Hep3Vector::mag2(), message(), MeV, min, perMillion, perThousand, G4VParticleChange::ProposeFirstStepInVolume(), G4VParticleChange::ProposeTrueStepLength(), G4EquationOfMotion::SetChargeMomentumMass(), G4SafetyHelper::SetCurrentSafety(), sqr(), true, and G4VProcess::verboseLevel.
G4VParticleChange* G4Transportation::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 147 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 147 of file G4Transportation.hh
G4double G4Transportation::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 143 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 143 of file G4Transportation.hh
G4bool G4Transportation::DoesAnyFieldExist () protected
Referenced by G4Transportation(), and StartTracking().
G4bool G4Transportation::EnableGravity (G4bool useGravity = true) static
Definition at line 871 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 871 of file G4Transportation.cc
References fUseGravity, and G4CoupledTransportation::fUseGravity.
Referenced by ExUCNExtraPhysics::ConstructProcess(), and main().
G4bool G4Transportation::EnableMagneticMoment (G4bool useMoment = true) static
Definition at line 860 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 860 of file G4Transportation.cc
References fUseMagneticMoment, and G4CoupledTransportation::fUseMagneticMoment.
Referenced by EnableUseMagneticMoment().
void G4Transportation::EnableShortStepOptimisation (G4bool optimise = true) inline
static G4bool G4Transportation::EnableUseMagneticMoment (G4bool useMoment = true) inline static
Definition at line 138 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 138 of file G4Transportation.hh
References EnableMagneticMoment().
G4bool G4Transportation::FieldExertedForce () inline
Definition at line 96 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Transportation.hh
References fFieldExertedForce.
G4double G4Transportation::GetMaxEnergyKilled () const inline
G4PropagatorInField* G4Transportation::GetPropagatorInField ()
G4bool G4Transportation::GetSilenceLooperWarnings () static
Definition at line 891 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 891 of file G4Transportation.cc
References fSilenceLooperWarnings.
G4double G4Transportation::GetSumEnergyKilled () const inline
G4double G4Transportation::GetThresholdImportantEnergy () const inline
G4int G4Transportation::GetThresholdTrials () const inline
G4double G4Transportation::GetThresholdWarningEnergy () const inline
G4VParticleChange * G4Transportation::PostStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 696 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 696 of file G4Transportation.cc
References G4Navigator::EnteredDaughterVolume(), G4Navigator::ExitedMotherVolume(), fCurrentTouchableHandle, fFieldExertedForce, fFieldPropagator, fFirstStepInVolume, fGeometryLimitedStep, fLastStepInVolume, fLinearNavigator, fParticleChange, fStopAndKill, G4VPhysicalVolume::GetLogicalVolume(), G4MaterialCutsCouple::GetMaterial(), G4LogicalVolume::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4LogicalVolume::GetMaterialCutsCouple(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetSensitiveDetector(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4VTouchable::GetVolume(), G4PropagatorInField::IsLastStepInVolume(), G4Navigator::LocateGlobalPointWithinVolume(), G4VParticleChange::ProposeFirstStepInVolume(), G4VParticleChange::ProposeLastStepInVolume(), G4VParticleChange::ProposeTrackStatus(), G4Navigator::SetGeometricallyLimitedStep(), G4ParticleChangeForTransport::SetMaterialCutsCoupleInTouchable(), G4ParticleChangeForTransport::SetMaterialInTouchable(), G4ParticleChangeForTransport::SetSensitiveDetectorInTouchable(), G4ParticleChangeForTransport::SetTouchableHandle(), and true.
G4double G4Transportation::PostStepGetPhysicalInteractionLength (const G4Track & , G4double previousStepSize, G4ForceCondition * pForceCond) virtual
Implements G4VProcess.
Definition at line 684 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 684 of file G4Transportation.cc
References DBL_MAX, fFieldExertedForce, and Forced.
void G4Transportation::PrintStatistics (std::ostream & outStr) const
Definition at line 139 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 139 of file G4Transportation.cc
References fMaxEnergyKilled, fMaxEnergyKilled_NonElecPDG, fMaxEnergyKilled_NonElectron, fMaxEnergyKilledPDG, fMaxEnergySaved, fNumLoopersKilled, fNumLoopersKilled_NonElectron, fSumEnergyKilled, fSumEnergyKilled_NonElectron, fSumEnergySaved, fSumEnergyUnstableSaved, G4endl, and CLHEP::MeV.
Referenced by ~G4Transportation().
void G4Transportation::ProcessDescription (std::ostream & outFile) const virtual
Reimplemented from G4VProcess.
Definition at line 950 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 950 of file G4Transportation.cc
References G4endl, and CLHEP::MeV.
void G4Transportation::PushThresholdsToLogger ()
Referenced by G4Transportation(), ReportLooperThresholds(), SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4Transportation::ReportLooperThresholds ()
Definition at line 942 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 942 of file G4Transportation.cc
References fpLogger, PushThresholdsToLogger(), and G4TransportationLogger::ReportLooperThresholds().
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4Transportation::ReportMissingLogger (const char * methodName) protected
Definition at line 931 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 931 of file G4Transportation.cc
References G4Exception(), JustWarning, and message().
void G4Transportation::ResetKilledStatistics (G4int report = 1) inline
void G4Transportation::SetHighLooperThresholds ()
Definition at line 899 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 899 of file G4Transportation.cc
References CLHEP::MeV, PushThresholdsToLogger(), ReportLooperThresholds(), SetThresholdImportantEnergy(), SetThresholdTrials(), SetThresholdWarningEnergy(), and G4VProcess::verboseLevel.
Referenced by G4Transportation().
void G4Transportation::SetLowLooperThresholds ()
Definition at line 915 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 915 of file G4Transportation.cc
References CLHEP::keV, CLHEP::MeV, PushThresholdsToLogger(), ReportLooperThresholds(), SetThresholdImportantEnergy(), SetThresholdTrials(), SetThresholdWarningEnergy(), and G4VProcess::verboseLevel.
void G4Transportation::SetPropagatorInField (G4PropagatorInField * pFieldPropagator)
void G4Transportation::SetSilenceLooperWarnings (G4bool val) static
Definition at line 883 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 883 of file G4Transportation.cc
References fSilenceLooperWarnings.
void G4Transportation::SetThresholdImportantEnergy (G4double newEnImp) inline
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4Transportation::SetThresholdTrials (G4int newMaxTrials) inline
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4Transportation::SetThresholdWarningEnergy (G4double newEnWarn) inline
Referenced by SetHighLooperThresholds(), and SetLowLooperThresholds().
void G4Transportation::StartTracking (G4Track * aTrack) virtual
Reimplemented from G4VProcess.
Definition at line 810 of file G4Transportation.cc.
View newest version in sPHENIX GitHub at line 810 of file G4Transportation.cc
References G4FieldManagerStore::ClearAllChordFindersState(), G4PropagatorInField::ClearPropagatorState(), DoesAnyFieldExist(), fAnyFieldExists, fCurrentTouchableHandle, fFieldPropagator, fFirstStepInVolume, fLastStepInVolume, fNewTrack, fNoLooperTrials, fPreviousSafety, fPreviousSftOrigin, G4FieldManagerStore::GetInstance(), G4Track::GetTouchableHandle(), G4PropagatorInField::PrepareNewTrack(), and G4VProcess::StartTracking().
Friends And Related Function Documentation
friend class G4CoupledTransportation friend
Definition at line 240 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 240 of file G4Transportation.hh
Member Data Documentation
G4int G4Transportation::fAbandonUnstableTrials = 0 private
Definition at line 209 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 209 of file G4Transportation.hh
Referenced by AlongStepDoIt().
G4bool G4Transportation::fAnyFieldExists = false private
Definition at line 179 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 179 of file G4Transportation.hh
Referenced by G4Transportation(), and StartTracking().
G4double G4Transportation::fCandidateEndGlobalTime = 0.0 private
Definition at line 176 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 176 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4TouchableHandle G4Transportation::fCurrentTouchableHandle private
Definition at line 191 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 191 of file G4Transportation.hh
Referenced by G4Transportation(), PostStepDoIt(), and StartTracking().
G4bool G4Transportation::fEndGlobalTimeComputed = false private
Definition at line 175 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 175 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4double G4Transportation::fEndPointDistance private
Definition at line 200 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 200 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4bool G4Transportation::fFieldExertedForce = false private
Definition at line 189 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 189 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), FieldExertedForce(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4PropagatorInField* G4Transportation::fFieldPropagator private
Definition at line 167 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 167 of file G4Transportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4Transportation(), PostStepDoIt(), and StartTracking().
G4bool G4Transportation::fFirstStepInVolume = true private
Definition at line 183 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 183 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4bool G4Transportation::fGeometryLimitedStep = true private
Definition at line 186 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 186 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and PostStepDoIt().
G4bool G4Transportation::fLastStepInVolume = false private
Definition at line 184 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4Navigator* G4Transportation::fLinearNavigator private
Definition at line 166 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 166 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4Transportation(), and PostStepDoIt().
G4double G4Transportation::fMaxEnergyKilled = -1.0 private
Definition at line 219 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4int G4Transportation::fMaxEnergyKilled_NonElecPDG = 0 private
Definition at line 225 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 225 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4Transportation::fMaxEnergyKilled_NonElectron = -1.0 private
Definition at line 224 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 224 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4int G4Transportation::fMaxEnergyKilledPDG = 0 private
Definition at line 220 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 220 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4Transportation::fMaxEnergySaved = -1.0 private
Definition at line 228 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 228 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4bool G4Transportation::fMomentumChanged = true private
Definition at line 174 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 174 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4bool G4Transportation::fNewTrack = true private
Definition at line 182 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4int G4Transportation::fNoLooperTrials = 0 private
Definition at line 213 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and StartTracking().
unsigned long G4Transportation::fNumLoopersKilled = 0 private
Definition at line 221 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
unsigned long G4Transportation::fNumLoopersKilled_NonElectron = 0 private
Definition at line 226 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 226 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4ParticleChangeForTransport G4Transportation::fParticleChange private
Definition at line 197 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 197 of file G4Transportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4Transportation(), and PostStepDoIt().
G4bool G4Transportation::fParticleIsLooping = false private
Definition at line 181 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4TransportationLogger* G4Transportation::fpLogger private
Definition at line 236 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 236 of file G4Transportation.hh
Referenced by AlongStepDoIt(), G4Transportation(), ReportLooperThresholds(), and ~G4Transportation().
G4double G4Transportation::fPreviousSafety private
Definition at line 194 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 194 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4ThreeVector G4Transportation::fPreviousSftOrigin private
Definition at line 193 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 193 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4SafetyHelper* G4Transportation::fpSafetyHelper private
Definition at line 235 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 235 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and G4Transportation().
G4bool G4Transportation::fShortStepOptimisation private
Definition at line 233 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 233 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and G4Transportation().
G4bool G4Transportation::fSilenceLooperWarnings = false static private
Definition at line 243 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 243 of file G4Transportation.hh
Referenced by AlongStepDoIt(), GetSilenceLooperWarnings(), and SetSilenceLooperWarnings().
G4double G4Transportation::fSumEnergyKilled = 0.0 private
Definition at line 217 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Transportation.hh
Referenced by AlongStepDoIt(), PrintStatistics(), and ~G4Transportation().
G4double G4Transportation::fSumEnergyKilled_NonElectron = 0.0 private
Definition at line 222 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 222 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4Transportation::fSumEnergySaved = 0.0 private
Definition at line 227 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 227 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4Transportation::fSumEnergyUnstableSaved = 0.0 private
Definition at line 229 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 229 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and PrintStatistics().
G4double G4Transportation::fSumEnerSqKilled = 0.0 private
Definition at line 218 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 218 of file G4Transportation.hh
Referenced by AlongStepDoIt().
G4double G4Transportation::fSumEnerSqKilled_NonElectron = 0.0 private
Definition at line 223 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Transportation.hh
Referenced by AlongStepDoIt().
G4double G4Transportation::fThreshold_Important_Energy = 1.0 * CLHEP::MeV private
Definition at line 205 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 205 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4double G4Transportation::fThreshold_Warning_Energy = 1.0 * CLHEP::keV private
Definition at line 204 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 204 of file G4Transportation.hh
Referenced by AlongStepDoIt().
G4int G4Transportation::fThresholdTrials = 10 private
Definition at line 206 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 206 of file G4Transportation.hh
Referenced by AlongStepDoIt().
G4double G4Transportation::fTransportEndKineticEnergy = 0.0 private
Definition at line 172 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 172 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4Transportation::fTransportEndMomentumDir = G4ThreeVector(0.0, 0.0, 0.0) private
Definition at line 171 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 171 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4Transportation::fTransportEndPosition = G4ThreeVector(0.0, 0.0, 0.0) private
Definition at line 170 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4Transportation::fTransportEndSpin = G4ThreeVector(0.0, 0.0, 0.0) private
Definition at line 173 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 173 of file G4Transportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4bool G4Transportation::fUseGravity = false static private
Definition at line 242 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 242 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), EnableGravity(), and G4CoupledTransportation::EnableGravity().
G4bool G4Transportation::fUseMagneticMoment =false static private
Definition at line 241 of file G4Transportation.hh.
View newest version in sPHENIX GitHub at line 241 of file G4Transportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), EnableMagneticMoment(), and G4CoupledTransportation::EnableMagneticMoment().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4Transportation.hh
geant4/tree/geant4-10.6-release/source/processes/transportation/src/G4Transportation.cc