ECCE @ EIC Software: G4MPIToolsManager Class Reference
G4MPIToolsManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4MPIToolsManager.hh>
Public Member Functions
G4MPIToolsManager (const G4AnalysisManagerState &state, tools::histo::hmpi *hmpi)
virtual ~G4MPIToolsManager ()
template<typename T >
G4bool Merge (const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector)
Private Member Functions
template<typename T >
G4bool Send (G4int nofActiveT, const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector)
template<typename T >
G4bool Receive (G4int nofActiveT, const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector)
Private Attributes
const G4AnalysisManagerState & fState
tools::histo::hmpi * fHmpi
Detailed Description
Definition at line 43 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4MPIToolsManager.hh
Constructor & Destructor Documentation
G4MPIToolsManager::G4MPIToolsManager (const G4AnalysisManagerState & state, tools::histo::hmpi * hmpi) inline
Definition at line 46 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4MPIToolsManager.hh
virtual G4MPIToolsManager::~G4MPIToolsManager () inline virtual
Definition at line 49 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 49 of file G4MPIToolsManager.hh
Member Function Documentation
template<typename T > G4bool G4MPIToolsManager::Merge (const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector) inline
Definition at line 175 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 175 of file G4MPIToolsManager.hh
References fHmpi, fState, G4endl, G4Exception(), G4AnalysisManagerState::GetIsActivation(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL3(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), Receive(), and Send().
Referenced by G4ToolsAnalysisManager::MergeImpl().
template<typename T > G4bool G4MPIToolsManager::Receive (G4int nofActiveT, const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector) private
Definition at line 113 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4MPIToolsManager.hh
References fHmpi, fState, G4endl, G4Exception(), G4AnalysisManagerState::GetIsActivation(), JustWarning, and T.
Referenced by Merge().
template<typename T > G4bool G4MPIToolsManager::Send (G4int nofActiveT, const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector) private
Definition at line 77 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 77 of file G4MPIToolsManager.hh
References fHmpi, fState, G4Exception(), G4AnalysisManagerState::GetIsActivation(), and JustWarning.
Referenced by Merge().
Member Data Documentation
tools::histo::hmpi* G4MPIToolsManager::fHmpi private
Definition at line 70 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 70 of file G4MPIToolsManager.hh
Referenced by Merge(), Receive(), and Send().
const G4AnalysisManagerState& G4MPIToolsManager::fState private
Definition at line 69 of file G4MPIToolsManager.hh.
View newest version in sPHENIX GitHub at line 69 of file G4MPIToolsManager.hh
Referenced by Merge(), Receive(), and Send().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4MPIToolsManager.hh