ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_particle.cc File Reference
MCGIDI_particle.cc File Reference
#include <string.h>
#include "MCGIDI.h"
Functions
MCGIDI_particle * MCGIDI_particle_new (statusMessageReporting *smr)
int MCGIDI_particle_initialize (statusMessageReporting *, MCGIDI_particle *particle)
MCGIDI_particle * MCGIDI_particle_free (statusMessageReporting *smr, MCGIDI_particle *particle)
int MCGIDI_particle_release (statusMessageReporting *, MCGIDI_particle *particle)
int MCGIDI_particle_freeInternalList (statusMessageReporting *smr)
MCGIDI_particle * MCGIDI_particle_getInternalID (statusMessageReporting *smr, const char *const name, MCGIDI_POPs *pops)
int MCGIDI_particle_printInternalSortedList (statusMessageReporting *)
Variables
static int initialSizeOfList = 1000
static int incrementalSizeOfList = 1000
static int numberOfParticles = 0
static int sizeOfParticleSortedList = 0
static MCGIDI_particle ** particleSortedList = NULL
static MCGIDI_particle * particleList = NULL
static MCGIDI_particle * particleListEnd = NULL
Function Documentation
MCGIDI_particle* MCGIDI_particle_free (statusMessageReporting * smr, MCGIDI_particle * particle)
Definition at line 39 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_particle.cc
References MCGIDI_particle_release(), MCGIDI_particle_s::next, numberOfParticles, particleList, particleListEnd, particleSortedList, MCGIDI_particle_s::prior, and smr_freeMemory().
Referenced by MCGIDI_particle_freeInternalList(), and MCGIDI_particle_getInternalID().
int MCGIDI_particle_freeInternalList (statusMessageReporting * smr)
Definition at line 70 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 70 of file MCGIDI_particle.cc
References MCGIDI_particle_free(), particleList, particleSortedList, and smr_freeMemory().
MCGIDI_particle* MCGIDI_particle_getInternalID (statusMessageReporting * smr, const char *const name, MCGIDI_POPs * pops)
Definition at line 79 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 79 of file MCGIDI_particle.cc
References A(), MCGIDI_particle_s::A, check_license::err(), incrementalSizeOfList, initialSizeOfList, m, MCGIDI_particle_s::m, MCGIDI_POP_s::mass_MeV, MCGIDI_particle_s::mass_MeV, max, MCGIDI_AMU2MeV, MCGIDI_miscNameToZAm(), MCGIDI_particle_free(), MCGIDI_particle_new(), MCGIDI_particleMass_AMU(), MCGIDI_POPs_findParticle(), min, MCGIDI_particle_s::name, MCGIDI_particle_s::next, numberOfParticles, MCGIDI_particle_s::ordinal, particle, particleList, particleListEnd, particleSortedList, MCGIDI_particle_s::prior, sizeOfParticleSortedList, smr_allocateCopyString(), smr_isOk(), smr_realloc2, Z, and MCGIDI_particle_s::Z.
int MCGIDI_particle_initialize (statusMessageReporting * , MCGIDI_particle * particle)
Definition at line 31 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_new().
MCGIDI_particle* MCGIDI_particle_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_particle.cc
References MCGIDI_particle_initialize(), particle, and smr_malloc2.
Referenced by MCGIDI_particle_getInternalID().
int MCGIDI_particle_printInternalSortedList (statusMessageReporting *)
Definition at line 159 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 159 of file MCGIDI_particle.cc
References numberOfParticles, particleSortedList, and printf().
int MCGIDI_particle_release (statusMessageReporting * , MCGIDI_particle * particle)
Definition at line 62 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 62 of file MCGIDI_particle.cc
References MCGIDI_particle_s::name, and smr_freeMemory().
Referenced by MCGIDI_particle_free().
Variable Documentation
int incrementalSizeOfList = 1000 static
Definition at line 13 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 13 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_getInternalID().
int initialSizeOfList = 1000 static
Definition at line 13 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 13 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_getInternalID().
int numberOfParticles = 0 static
Definition at line 14 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 14 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_free(), MCGIDI_particle_getInternalID(), MCGIDI_particle_printInternalSortedList(), and G4INCL::IAvatar::toString().
MCGIDI_particle* particleList = NULL static
Definition at line 16 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 16 of file MCGIDI_particle.cc
MCGIDI_particle * particleListEnd = NULL static
Definition at line 16 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 16 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_free(), and MCGIDI_particle_getInternalID().
MCGIDI_particle** particleSortedList = NULL static
Definition at line 15 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 15 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_free(), MCGIDI_particle_freeInternalList(), MCGIDI_particle_getInternalID(), and MCGIDI_particle_printInternalSortedList().
int sizeOfParticleSortedList = 0 static
Definition at line 14 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 14 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_getInternalID().