ECCE @ EIC Software: B2PrimaryGeneratorAction Class Reference
B2PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/include/B2PrimaryGeneratorAction.hh>
Public Member Functions
B2PrimaryGeneratorAction ()
virtual ~B2PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
void SetRandomFlag (G4bool)
B2PrimaryGeneratorAction ()
virtual ~B2PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
void SetRandomFlag (G4bool)
B2PrimaryGeneratorAction ()
virtual ~B2PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
void SetRandomFlag (G4bool)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
Detailed Description
The primary generator action class with particle gum.
It defines a single particle which hits the Tracker perpendicular to the input face. The type of the particle can be changed via the G4 build-in commands of G4ParticleGun class (see the macros provided with this example).
Definition at line 46 of file B2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 46 of file B2PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
B2PrimaryGeneratorAction::B2PrimaryGeneratorAction ()
Definition at line 45 of file B2PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 45 of file B2PrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), GeV, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), and G4ParticleGun::SetParticleMomentumDirection().
B2PrimaryGeneratorAction::~B2PrimaryGeneratorAction () virtual
Definition at line 63 of file B2PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 63 of file B2PrimaryGeneratorAction.cc
References fParticleGun.
B2PrimaryGeneratorAction::B2PrimaryGeneratorAction ()
virtual B2PrimaryGeneratorAction::~B2PrimaryGeneratorAction () virtual
B2PrimaryGeneratorAction::B2PrimaryGeneratorAction ()
virtual B2PrimaryGeneratorAction::~B2PrimaryGeneratorAction () virtual
Member Function Documentation
void B2PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 70 of file B2PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 70 of file B2PrimaryGeneratorAction.cc
References fParticleGun, G4cerr, G4endl, G4ParticleGun::GeneratePrimaryVertex(), G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetSolid(), G4LogicalVolumeStore::GetVolume(), G4Box::GetZHalfLength(), and G4VPrimaryGenerator::SetParticlePosition().
virtual void B2PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void B2PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
G4ParticleGun* B2PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 54 of file B2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file B2PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* B2PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 54 of file B2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file B2PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* B2PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 54 of file B2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file B2PrimaryGeneratorAction.hh
References fParticleGun.
void B2PrimaryGeneratorAction::SetRandomFlag (G4bool)
void B2PrimaryGeneratorAction::SetRandomFlag (G4bool)
void B2PrimaryGeneratorAction::SetRandomFlag (G4bool)
Member Data Documentation
G4ParticleGun * B2PrimaryGeneratorAction::fParticleGun private
Definition at line 60 of file B2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file B2PrimaryGeneratorAction.hh
Referenced by B2PrimaryGeneratorAction(), GeneratePrimaries(), GetParticleGun(), and ~B2PrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/include/B2PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/B2PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2a/src/B2PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/src/B2PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/src/B2PrimaryGeneratorAction.cc