ECCE @ EIC Software: G4ParallelWorldPhysics Class Reference
G4ParallelWorldPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4ParallelWorldPhysics.hh>
Public Member Functions
G4ParallelWorldPhysics (const G4String &name="ParallelWP", G4bool layerdMass=false)
virtual ~G4ParallelWorldPhysics ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
G4ParallelWorldPhysics & operator= (const G4ParallelWorldPhysics &right)
G4ParallelWorldPhysics (const G4ParallelWorldPhysics &)
Private Attributes
G4bool fLayeredMass
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 39 of file G4ParallelWorldPhysics.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParallelWorldPhysics.hh
Constructor & Destructor Documentation
G4ParallelWorldPhysics::G4ParallelWorldPhysics (const G4String & name = "ParallelWP", G4bool layerdMass = false)
Definition at line 56 of file G4ParallelWorldPhysics.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParallelWorldPhysics.cc
G4ParallelWorldPhysics::~G4ParallelWorldPhysics () virtual
Definition at line 62 of file G4ParallelWorldPhysics.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ParallelWorldPhysics.cc
G4ParallelWorldPhysics::G4ParallelWorldPhysics (const G4ParallelWorldPhysics &) private
Member Function Documentation
void G4ParallelWorldPhysics::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 67 of file G4ParallelWorldPhysics.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ParallelWorldPhysics.cc
void G4ParallelWorldPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 72 of file G4ParallelWorldPhysics.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ParallelWorldPhysics.cc
References G4ProcessManager::AddProcess(), fLayeredMass, G4TransportationManager::GetParallelWorld(), G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), G4TransportationManager::GetTransportationManager(), idxAlongStep, idxAtRest, idxPostStep, G4ParallelWorldProcess::IsAtRestRequired(), G4VPhysicsConstructor::namePhysics, particle, G4ParallelWorldProcess::SetLayeredMaterialFlag(), G4ParallelWorldProcess::SetParallelWorld(), G4ProcessManager::SetProcessOrdering(), and G4ProcessManager::SetProcessOrderingToSecond().
Referenced by HadrontherapyPhysicsList::ConstructProcess().
G4ParallelWorldPhysics& G4ParallelWorldPhysics::operator= (const G4ParallelWorldPhysics & right) private
Member Data Documentation
G4bool G4ParallelWorldPhysics::fLayeredMass private
Definition at line 62 of file G4ParallelWorldPhysics.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ParallelWorldPhysics.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4ParallelWorldPhysics.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/src/G4ParallelWorldPhysics.cc