ECCE @ EIC Software: CLHEP::RandExpZiggurat Class Reference
CLHEP::RandExpZiggurat Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandExpZiggurat.h>
Public Member Functions
RandExpZiggurat (HepRandomEngine &anEngine, double mean=1.0)
RandExpZiggurat (HepRandomEngine *anEngine, double mean=1.0)
virtual ~RandExpZiggurat ()
float fire ()
float fire (float mean)
void fireArray (const int size, float *vect)
void fireArray (const int size, double *vect)
void fireArray (const int size, float *vect, float mean)
void fireArray (const int size, double *vect, double mean)
virtual double operator() ()
float operator() (float mean)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static float shoot ()
static float shoot (float mean)
static void shootArray (const int size, float *vect, float mean=1.0)
static void shootArray (const int size, double *vect, double mean=1.0)
static float shoot (HepRandomEngine *anEngine)
static float shoot (HepRandomEngine *anEngine, float mean)
static void shootArray (HepRandomEngine *anEngine, const int size, float *vect, float mean=1.0)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double mean=1.0)
static std::string distributionName ()
static bool ziggurat_init ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Protected Member Functions
static unsigned long ziggurat_SHR3 (HepRandomEngine *anEngine)
static float ziggurat_UNI (HepRandomEngine *anEngine)
static float ziggurat_REXP (HepRandomEngine *anEngine)
static float ziggurat_efix (unsigned long jz, HepRandomEngine *anEngine)
Static Protected Attributes
static CLHEP_THREAD_LOCAL
unsigned long kn [128]
static CLHEP_THREAD_LOCAL
unsigned long ke [256]
static CLHEP_THREAD_LOCAL float wn [128]
static CLHEP_THREAD_LOCAL float fn [128]
static CLHEP_THREAD_LOCAL float we [256]
static CLHEP_THREAD_LOCAL float fe [256]
static CLHEP_THREAD_LOCAL bool ziggurat_is_init = false
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Private Member Functions
RandExpZiggurat (const RandExpZiggurat &d)
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double defaultMean
Detailed Description
Author
ATLAS
Definition at line 36 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 36 of file RandExpZiggurat.h
Constructor & Destructor Documentation
CLHEP::RandExpZiggurat::RandExpZiggurat (HepRandomEngine & anEngine, double mean = 1.0) inline
Definition at line 158 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 158 of file RandExpZiggurat.h
CLHEP::RandExpZiggurat::RandExpZiggurat (HepRandomEngine * anEngine, double mean = 1.0) inline
Definition at line 162 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 162 of file RandExpZiggurat.h
CLHEP::RandExpZiggurat::~RandExpZiggurat () virtual
Definition at line 18 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 18 of file RandExpZiggurat.cc
CLHEP::RandExpZiggurat::RandExpZiggurat (const RandExpZiggurat & d) private
Definition at line 21 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 21 of file RandExpZiggurat.cc
Member Function Documentation
static std::string CLHEP::RandExpZiggurat::distributionName () inline static
Definition at line 109 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 109 of file RandExpZiggurat.h
HepRandomEngine & CLHEP::RandExpZiggurat::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 16 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 16 of file RandExpZiggurat.cc
References localEngine.
float CLHEP::RandExpZiggurat::fire () inline
Definition at line 85 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 85 of file RandExpZiggurat.h
References defaultMean, and fire().
Referenced by fire(), fireArray(), and operator()().
float CLHEP::RandExpZiggurat::fire (float mean) inline
Definition at line 86 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 86 of file RandExpZiggurat.h
References localEngine, and ziggurat_REXP().
void CLHEP::RandExpZiggurat::fireArray (const int size, float * vect)
Definition at line 50 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 50 of file RandExpZiggurat.cc
References defaultMean, and fire().
void CLHEP::RandExpZiggurat::fireArray (const int size, double * vect)
Definition at line 55 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 55 of file RandExpZiggurat.cc
References defaultMean, and fire().
void CLHEP::RandExpZiggurat::fireArray (const int size, float * vect, float mean)
Definition at line 60 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 60 of file RandExpZiggurat.cc
References fire().
void CLHEP::RandExpZiggurat::fireArray (const int size, double * vect, double mean)
Definition at line 65 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 65 of file RandExpZiggurat.cc
References fire().
std::istream & CLHEP::RandExpZiggurat::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 88 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 88 of file RandExpZiggurat.cc
References defaultMean, CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), and t.
std::string CLHEP::RandExpZiggurat::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 14 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 14 of file RandExpZiggurat.cc
Referenced by get(), and put().
double CLHEP::RandExpZiggurat::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 25 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 25 of file RandExpZiggurat.cc
References defaultMean, and fire().
float CLHEP::RandExpZiggurat::operator() (float mean) inline
Definition at line 99 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 99 of file RandExpZiggurat.h
References fire().
std::ostream & CLHEP::RandExpZiggurat::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 70 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 70 of file RandExpZiggurat.cc
References defaultMean, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, and t.
static float CLHEP::RandExpZiggurat::shoot () inline static
Definition at line 56 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 56 of file RandExpZiggurat.h
References CLHEP::HepRandom::getTheEngine(), and shoot().
Referenced by shoot(), and shootArray().
static float CLHEP::RandExpZiggurat::shoot (float mean) inline static
Definition at line 57 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 57 of file RandExpZiggurat.h
References CLHEP::HepRandom::getTheEngine(), and shoot().
Referenced by shoot().
static float CLHEP::RandExpZiggurat::shoot (HepRandomEngine * anEngine) inline static
Definition at line 70 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 70 of file RandExpZiggurat.h
References ziggurat_REXP().
static float CLHEP::RandExpZiggurat::shoot (HepRandomEngine * anEngine, float mean) inline static
Definition at line 71 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 71 of file RandExpZiggurat.h
References shoot().
Referenced by shoot().
void CLHEP::RandExpZiggurat::shootArray (const int size, float * vect, float mean = 1.0) static
Definition at line 30 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 30 of file RandExpZiggurat.cc
References shoot().
void CLHEP::RandExpZiggurat::shootArray (const int size, double * vect, double mean = 1.0) static
Definition at line 35 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 35 of file RandExpZiggurat.cc
References shoot().
void CLHEP::RandExpZiggurat::shootArray (HepRandomEngine * anEngine, const int size, float * vect, float mean = 1.0) static
Definition at line 40 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 40 of file RandExpZiggurat.cc
References shoot().
void CLHEP::RandExpZiggurat::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double mean = 1.0) static
Definition at line 45 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 45 of file RandExpZiggurat.cc
References shoot().
float CLHEP::RandExpZiggurat::ziggurat_efix (unsigned long jz, HepRandomEngine * anEngine) static protected
Definition at line 109 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 109 of file RandExpZiggurat.cc
References fe, ke, we, x, ziggurat_init(), ziggurat_is_init, ziggurat_SHR3(), and ziggurat_UNI().
Referenced by ziggurat_REXP().
bool CLHEP::RandExpZiggurat::ziggurat_init () static
Definition at line 129 of file RandExpZiggurat.cc.
View newest version in sPHENIX GitHub at line 129 of file RandExpZiggurat.cc
References fe, fn, ke, kn, we, wn, and ziggurat_is_init.
Referenced by ziggurat_efix(), and ziggurat_REXP().
static float CLHEP::RandExpZiggurat::ziggurat_REXP (HepRandomEngine * anEngine) inline static protected
Definition at line 137 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 137 of file RandExpZiggurat.h
References ke, we, ziggurat_efix(), ziggurat_init(), ziggurat_is_init, and ziggurat_SHR3().
Referenced by fire(), and shoot().
static unsigned long CLHEP::RandExpZiggurat::ziggurat_SHR3 (HepRandomEngine * anEngine) inline static protected
Definition at line 135 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 135 of file RandExpZiggurat.h
Referenced by ziggurat_efix(), and ziggurat_REXP().
static float CLHEP::RandExpZiggurat::ziggurat_UNI (HepRandomEngine * anEngine) inline static protected
Definition at line 136 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 136 of file RandExpZiggurat.h
References CLHEP::HepRandomEngine::flat().
Referenced by ziggurat_efix().
Member Data Documentation
double CLHEP::RandExpZiggurat::defaultMean private
Definition at line 151 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 151 of file RandExpZiggurat.h
Referenced by fire(), fireArray(), get(), operator()(), and put().
CLHEP_THREAD_LOCAL float CLHEP::RandExpZiggurat::fe static protected
Definition at line 131 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 131 of file RandExpZiggurat.h
Referenced by ziggurat_efix(), and ziggurat_init().
CLHEP_THREAD_LOCAL float CLHEP::RandExpZiggurat::fn static protected
Definition at line 131 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 131 of file RandExpZiggurat.h
Referenced by ziggurat_init().
CLHEP_THREAD_LOCAL unsigned long CLHEP::RandExpZiggurat::ke static protected
Definition at line 130 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 130 of file RandExpZiggurat.h
Referenced by ziggurat_efix(), ziggurat_init(), and ziggurat_REXP().
CLHEP_THREAD_LOCAL unsigned long CLHEP::RandExpZiggurat::kn static protected
Definition at line 130 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 130 of file RandExpZiggurat.h
Referenced by ziggurat_init().
std::shared_ptr<HepRandomEngine> CLHEP::RandExpZiggurat::localEngine private
Definition at line 150 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 150 of file RandExpZiggurat.h
Referenced by engine(), and fire().
CLHEP_THREAD_LOCAL float CLHEP::RandExpZiggurat::we static protected
Definition at line 131 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 131 of file RandExpZiggurat.h
Referenced by ziggurat_efix(), ziggurat_init(), and ziggurat_REXP().
CLHEP_THREAD_LOCAL float CLHEP::RandExpZiggurat::wn static protected
Definition at line 131 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 131 of file RandExpZiggurat.h
Referenced by ziggurat_init().
CLHEP_THREAD_LOCAL bool CLHEP::RandExpZiggurat::ziggurat_is_init = false static protected
Definition at line 133 of file RandExpZiggurat.h.
View newest version in sPHENIX GitHub at line 133 of file RandExpZiggurat.h
Referenced by ziggurat_efix(), ziggurat_init(), and ziggurat_REXP().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandExpZiggurat.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandExpZiggurat.cc