ECCE @ EIC Software: G4VRML2FileSceneHandler Class Reference
G4VRML2FileSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/VRML/include/G4VRML2FileSceneHandler.hh>
Public Member Functions
G4VRML2FileSceneHandler (G4VRML2File &system, const G4String &name="")
virtual ~G4VRML2FileSceneHandler ()
void AddSolid (const G4Box &)
void AddSolid (const G4Cons &)
void AddSolid (const G4Tubs &)
void AddSolid (const G4Trd &)
void AddSolid (const G4Trap &)
void AddSolid (const G4Sphere &)
void AddSolid (const G4Para &)
void AddSolid (const G4Torus &)
void AddSolid (const G4Polycone &polycone)
void AddSolid (const G4Polyhedra &polyhedra)
void AddSolid (const G4Orb &orb)
void AddSolid (const G4Ellipsoid &ellipsoid)
void AddSolid (const G4TessellatedSolid &tess)
void AddSolid (const G4VSolid &)
void AddCompound (const G4VTrajectory &traj)
void AddCompound (const G4VHit &hit)
void AddCompound (const G4VDigi &digi)
void AddCompound (const G4THitsMap< G4double > &hits)
void AddCompound (const G4THitsMap< G4StatDouble > &hits)
void BeginPrimitives (const G4Transform3D &objectTransformation)
void EndPrimitives ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polymarker &polymarker)
void AddPrimitive (const G4Scale &scale)
void ClearTransientStore ()
void BeginModeling ()
void EndModeling ()
void VRMLBeginModeling ()
void VRMLEndModeling ()
void connectPort ()
void closePort ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Public Attributes
std::ofstream fDest
Private Member Functions
void SendMaterialNode (const G4VisAttributes *pAV)
void SendMaterialNode ()
void SendLineColor (const G4VisAttributes *pAV)
void SendMarkerColor (const G4VMarker &mark)
void SendMarkerWorldPosition (const G4VMarker &mark)
G4double GetMarkerHalfSize (const G4VMarker &mark)
void GetMarkerWorldPosition (const G4VMarker &mark, double *pX, double *pY, double *pZ)
G4bool isConnected ()
G4bool IsPVPickable ()
void SetPVPickability (G4bool on_off)
G4double SetPVTransparency ()
G4double GetPVTransparency ()
Private Attributes
char fVRMLFileDestDir [256]
char fVRMLFileName [256]
G4VRML2File & fSystem
G4bool fFlagDestOpen
G4int fMaxFileNum
G4bool fPVPickable
G4double fPVTransparency
Static Private Attributes
static G4int fSceneIdCount = 0
Friends
class G4VRML2FileViewer
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Definition at line 44 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VRML2FileSceneHandler.hh
Constructor & Destructor Documentation
G4VRML2FileSceneHandler::G4VRML2FileSceneHandler (G4VRML2File & system, const G4String & name = "")
Definition at line 74 of file G4VRML2FileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VRML2FileSceneHandler.cc
References DEFAULT_MAX_WRL_FILE_NUM, fMaxFileNum, fVRMLFileDestDir, fVRMLFileName, SetPVPickability(), SetPVTransparency(), and VRMLFILE_DEST_DIR.
G4VRML2FileSceneHandler::~G4VRML2FileSceneHandler () virtual
Definition at line 119 of file G4VRML2FileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 119 of file G4VRML2FileSceneHandler.cc
References G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), and VRMLEndModeling().
Member Function Documentation
void G4VRML2FileSceneHandler::AddCompound (const G4VTrajectory & traj) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 76 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4VRML2FileSceneHandler::AddCompound (const G4VHit & hit) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 79 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4VRML2FileSceneHandler::AddCompound (const G4VDigi & digi) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 82 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4VRML2FileSceneHandler::AddCompound (const G4THitsMap< G4double > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 85 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4VRML2FileSceneHandler::AddCompound (const G4THitsMap< G4StatDouble > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 88 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4VRML2FileSceneHandler::AddPrimitive (const G4Polyline &) virtual
Implements G4VSceneHandler.
void G4VRML2FileSceneHandler::AddPrimitive (const G4Polyhedron &) virtual
Implements G4VSceneHandler.
void G4VRML2FileSceneHandler::AddPrimitive (const G4Text &) virtual
Implements G4VSceneHandler.
void G4VRML2FileSceneHandler::AddPrimitive (const G4Circle &) virtual
Implements G4VSceneHandler.
void G4VRML2FileSceneHandler::AddPrimitive (const G4Square &) virtual
Implements G4VSceneHandler.
void G4VRML2FileSceneHandler::AddPrimitive (const G4Polymarker & polymarker) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 100 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4VRML2FileSceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 102 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4VRML2FileSceneHandler::AddSolid (const G4Box &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Cons &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Tubs &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Trd &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Trap &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Sphere &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Para &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Torus &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::AddSolid (const G4Polycone & polycone) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 60 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4VRML2FileSceneHandler::AddSolid (const G4Polyhedra & polyhedra) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 63 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4VRML2FileSceneHandler::AddSolid (const G4Orb & orb) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 66 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4VRML2FileSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 69 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4VRML2FileSceneHandler::AddSolid (const G4TessellatedSolid & tess) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 72 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VRML2FileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4VRML2FileSceneHandler::AddSolid (const G4VSolid &) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::BeginModeling () virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::ClearTransientStore () virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::closePort ()
Definition at line 198 of file G4VRML2FileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 198 of file G4VRML2FileSceneHandler.cc
References ENV_VRML_VIEWER, G4VisManager::errors, false, fDest, fFlagDestOpen, fVRMLFileName, G4cout, G4endl, G4VisManager::GetVerbosity(), NO_VRML_VIEWER, system(), and void().
void G4VRML2FileSceneHandler::connectPort ()
Definition at line 136 of file G4VRML2FileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 136 of file G4VRML2FileSceneHandler.cc
References DEFAULT_WRL_FILE_NAME, G4VisManager::errors, fDest, fFlagDestOpen, INPUTHEPMC::filename, fin, fMaxFileNum, fVRMLFileDestDir, fVRMLFileName, G4cout, G4endl, G4VisManager::GetVerbosity(), true, and WRL_FILE_HEADER.
void G4VRML2FileSceneHandler::EndModeling () virtual
Reimplemented from G4VSceneHandler.
void G4VRML2FileSceneHandler::EndPrimitives () virtual
Reimplemented from G4VSceneHandler.
G4double G4VRML2FileSceneHandler::GetMarkerHalfSize (const G4VMarker & mark) private
void G4VRML2FileSceneHandler::GetMarkerWorldPosition (const G4VMarker & mark, double * pX, double * pY, double * pZ) private
G4double G4VRML2FileSceneHandler::GetPVTransparency () inline private
Definition at line 137 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 137 of file G4VRML2FileSceneHandler.hh
References fPVTransparency.
G4bool G4VRML2FileSceneHandler::isConnected () inline private
Definition at line 132 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 132 of file G4VRML2FileSceneHandler.hh
References fFlagDestOpen.
G4bool G4VRML2FileSceneHandler::IsPVPickable () inline private
Definition at line 134 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 134 of file G4VRML2FileSceneHandler.hh
References fPVPickable.
void G4VRML2FileSceneHandler::SendLineColor (const G4VisAttributes * pAV) private
void G4VRML2FileSceneHandler::SendMarkerColor (const G4VMarker & mark) private
void G4VRML2FileSceneHandler::SendMarkerWorldPosition (const G4VMarker & mark) private
void G4VRML2FileSceneHandler::SendMaterialNode (const G4VisAttributes * pAV) private
void G4VRML2FileSceneHandler::SendMaterialNode () private
void G4VRML2FileSceneHandler::SetPVPickability (G4bool on_off) inline private
Definition at line 135 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 135 of file G4VRML2FileSceneHandler.hh
References fPVPickable.
Referenced by G4VRML2FileSceneHandler().
G4double G4VRML2FileSceneHandler::SetPVTransparency () private
Referenced by G4VRML2FileSceneHandler().
void G4VRML2FileSceneHandler::VRMLBeginModeling ()
Referenced by G4VRML2FileViewer::DrawView().
void G4VRML2FileSceneHandler::VRMLEndModeling ()
Referenced by G4VRML2FileViewer::ShowView(), and ~G4VRML2FileSceneHandler().
Friends And Related Function Documentation
friend class G4VRML2FileViewer friend
Definition at line 46 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VRML2FileSceneHandler.hh
Member Data Documentation
std::ofstream G4VRML2FileSceneHandler::fDest
Definition at line 155 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 155 of file G4VRML2FileSceneHandler.hh
Referenced by G4VRML2FileViewer::ClearView(), closePort(), and connectPort().
G4bool G4VRML2FileSceneHandler::fFlagDestOpen private
Definition at line 145 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 145 of file G4VRML2FileSceneHandler.hh
Referenced by G4VRML2FileViewer::ClearView(), closePort(), connectPort(), and isConnected().
G4int G4VRML2FileSceneHandler::fMaxFileNum private
Definition at line 147 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VRML2FileSceneHandler.hh
Referenced by connectPort(), and G4VRML2FileSceneHandler().
G4bool G4VRML2FileSceneHandler::fPVPickable private
Definition at line 149 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VRML2FileSceneHandler.hh
Referenced by IsPVPickable(), and SetPVPickability().
G4double G4VRML2FileSceneHandler::fPVTransparency private
Definition at line 150 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 150 of file G4VRML2FileSceneHandler.hh
Referenced by GetPVTransparency().
G4int G4VRML2FileSceneHandler::fSceneIdCount = 0 static private
Definition at line 152 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 152 of file G4VRML2FileSceneHandler.hh
G4VRML2File& G4VRML2FileSceneHandler::fSystem private
Definition at line 144 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 144 of file G4VRML2FileSceneHandler.hh
char G4VRML2FileSceneHandler::fVRMLFileDestDir[256] private
Definition at line 141 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 141 of file G4VRML2FileSceneHandler.hh
Referenced by connectPort(), and G4VRML2FileSceneHandler().
char G4VRML2FileSceneHandler::fVRMLFileName[256] private
Definition at line 142 of file G4VRML2FileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 142 of file G4VRML2FileSceneHandler.hh
Referenced by G4VRML2FileViewer::ClearView(), closePort(), connectPort(), and G4VRML2FileSceneHandler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/VRML/include/G4VRML2FileSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/VRML/src/G4VRML2FileSceneHandler.cc