ECCE @ EIC Software: pyG4EmCalculator Namespace Reference
pyG4EmCalculator Namespace Reference
Functions
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_ComputeCrossSectionPerAtom, ComputeCrossSectionPerAtom, 5, 6) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(g_ComputeCrossSectionPerAtom
Variables
G4double(G4EmCalculator::* f1_GetDEDX)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetDEDX
G4double(G4EmCalculator::* f2_GetDEDX)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetDEDX
G4double(G4EmCalculator::* f1_GetRange)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetRange
G4double(G4EmCalculator::* f2_GetRange)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetRange
G4double(G4EmCalculator::* f1_GetKinEnergy)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetKinEnergy
G4double(G4EmCalculator::* f2_GetKinEnergy)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetKinEnergy
G4double(G4EmCalculator::* f1_GetCrossSectionPerVolume)(G4double, const G4ParticleDefinition *, const G4String &, const G4Material *, const G4Region *) = &G4EmCalculator::GetCrossSectionPerVolume
G4double(G4EmCalculator::* f2_GetCrossSectionPerVolume)(G4double, const G4String &, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetCrossSectionPerVolume
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_GetCrossSectionPerVolume,
GetCrossSectionPerVolume,
4, 5) G4double(G4EmCalculator
G4double(G4EmCalculator::* f2_GetMeanFreePath)(G4double, const G4String &, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetMeanFreePath
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_GetMeanFreePath,
GetMeanFreePath,
4, 5) G4double(G4EmCalculator
G4double(G4EmCalculator::* f2_ComputeDEDX)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeDEDX
G4double(G4EmCalculator::* f1_ComputeNuclearDEDX)(G4double, const G4ParticleDefinition *, const G4Material *) = &G4EmCalculator::ComputeNuclearDEDX
G4double(G4EmCalculator::* f2_ComputeNuclearDEDX)(G4double, const G4String &, const G4String &) = &G4EmCalculator::ComputeNuclearDEDX
G4double(G4EmCalculator::* f1_ComputeElectronicDEDX)(G4double, const G4ParticleDefinition *, const G4Material *, G4double) = &G4EmCalculator::ComputeElectronicDEDX
G4double(G4EmCalculator::* f2_ComputeElectronicDEDX)(G4double, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeElectronicDEDX
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_ComputeElectronicDEDX,
ComputeElectronicDEDX,
3, 4) G4double(G4EmCalculator
G4double(G4EmCalculator::* f2_ComputeTotalDEDX)(G4double, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeTotalDEDX
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_ComputeTotalDEDX,
ComputeTotalDEDX,
3, 4) G4double(G4EmCalculator
G4double(G4EmCalculator::* f2_ComputeCrossSectionPerVolume)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeCrossSectionPerVolume
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_ComputeCrossSectionPerVolume,
ComputeCrossSectionPerVolume,
4, 5) G4double(G4EmCalculator
G4double(G4EmCalculator::* f2_ComputeCrossSectionPerAtom)(G4double, const G4String &, const G4String &, const G4Element *, G4double) = &G4EmCalculator::ComputeCrossSectionPerAtom
ComputeCrossSectionPerAtom
G4double(G4EmCalculator::* f1_ComputeEnergyCutFromRangeCut)(G4double, const G4ParticleDefinition *, const G4Material *) = &G4EmCalculator::ComputeEnergyCutFromRangeCut
G4double(G4EmCalculator::* f2_ComputeEnergyCutFromRangeCut)(G4double range, const G4String &, const G4String &) = &G4EmCalculator::ComputeEnergyCutFromRangeCut
G4double(G4EmCalculator::* f1_ComputeMeanFreePath)(G4double, const G4ParticleDefinition *, const G4String &, const G4Material *, G4double) = &G4EmCalculator::ComputeMeanFreePath
G4double(G4EmCalculator::* f2_ComputeMeanFreePath)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeMeanFreePath
Function Documentation
pyG4EmCalculator::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_ComputeCrossSectionPerAtom , ComputeCrossSectionPerAtom , 5 , 6)
Variable Documentation
pyG4EmCalculator::ComputeCrossSectionPerAtom
Definition at line 179 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 179 of file pyG4EmCalculator.cc
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeElectronicDEDX)(G4double, const G4ParticleDefinition *, const G4Material *, G4double) = &G4EmCalculator::ComputeElectronicDEDX
Definition at line 131 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 131 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeEnergyCutFromRangeCut)(G4double, const G4ParticleDefinition *, const G4Material *) = &G4EmCalculator::ComputeEnergyCutFromRangeCut
Definition at line 183 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 183 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeMeanFreePath)(G4double, const G4ParticleDefinition *, const G4String &, const G4Material *, G4double) = &G4EmCalculator::ComputeMeanFreePath
Definition at line 192 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 192 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeNuclearDEDX)(G4double, const G4ParticleDefinition *, const G4Material *) = &G4EmCalculator::ComputeNuclearDEDX
Definition at line 122 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 122 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetCrossSectionPerVolume)(G4double, const G4ParticleDefinition *, const G4String &, const G4Material *, const G4Region *) = &G4EmCalculator::GetCrossSectionPerVolume
Definition at line 82 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 82 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetDEDX)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetDEDX
Definition at line 49 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 49 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetKinEnergy)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetKinEnergy
Definition at line 71 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 71 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetRange)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetRange
Definition at line 60 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 60 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_ComputeCrossSectionPerVolume, ComputeCrossSectionPerVolume, 4, 5) G4double (G4EmCalculator G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeCrossSectionPerAtom)(G4double, const G4String &, const G4String &, const G4Element *, G4double) = &G4EmCalculator::ComputeCrossSectionPerAtom
Definition at line 172 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 172 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_ComputeTotalDEDX, ComputeTotalDEDX, 3, 4) G4double (G4EmCalculator G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeCrossSectionPerVolume)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeCrossSectionPerVolume
Definition at line 159 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 159 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_GetMeanFreePath, GetMeanFreePath, 4, 5) G4double (G4EmCalculator G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeDEDX)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeDEDX
Definition at line 115 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 115 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeElectronicDEDX)(G4double, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeElectronicDEDX
Definition at line 135 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 135 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeEnergyCutFromRangeCut)(G4double range, const G4String &, const G4String &) = &G4EmCalculator::ComputeEnergyCutFromRangeCut
Definition at line 187 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 187 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeMeanFreePath)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeMeanFreePath
Definition at line 197 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 197 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeNuclearDEDX)(G4double, const G4String &, const G4String &) = &G4EmCalculator::ComputeNuclearDEDX
Definition at line 126 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 126 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_ComputeElectronicDEDX, ComputeElectronicDEDX, 3, 4) G4double (G4EmCalculator G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeTotalDEDX)(G4double, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeTotalDEDX
Definition at line 147 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 147 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetCrossSectionPerVolume)(G4double, const G4String &, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetCrossSectionPerVolume
Definition at line 87 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 87 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetDEDX)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetDEDX
Definition at line 53 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 53 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetKinEnergy)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetKinEnergy
Definition at line 75 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 75 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_GetCrossSectionPerVolume, GetCrossSectionPerVolume, 4, 5) G4double (G4EmCalculator G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetMeanFreePath)(G4double, const G4String &, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetMeanFreePath
Definition at line 101 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 101 of file pyG4EmCalculator.cc
Referenced by export_G4EmCalculator().
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetRange)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetRange
Definition at line 64 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 64 of file pyG4EmCalculator.cc