ECCE @ EIC Software: GammaRayTelAnalysis Class Reference
GammaRayTelAnalysis Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelAnalysis.hh>
Public Member Functions
virtual ~GammaRayTelAnalysis ()
void BeginOfRun ()
void EndOfRun ()
void EndOfEvent (G4int flag)
void Init ()
void Finish ()
void SetHisto2DMode (G4String str)
G4String GetHisto2DMode ()
void InsertPositionXZ (double x, double z)
void InsertPositionYZ (double y, double z)
void InsertEnergy (double en)
void InsertHits (int nplane)
void setNtuple (float E, float p, float x, float y, float z)
Static Public Member Functions
static GammaRayTelAnalysis * getInstance ()
Private Member Functions
GammaRayTelAnalysis ()
void Plot ()
Private Attributes
const
GammaRayTelDetectorConstruction * GammaRayTelDetector
G4String histo2DMode
G4String histoFileName
GammaRayTelAnalysisMessenger * analysisMessenger
Static Private Attributes
static GammaRayTelAnalysis * instance = 0
Detailed Description
Definition at line 70 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 70 of file GammaRayTelAnalysis.hh
Constructor & Destructor Documentation
GammaRayTelAnalysis::~GammaRayTelAnalysis () virtual
Definition at line 80 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 80 of file GammaRayTelAnalysis.cc
References Finish(), and G4ToolsAnalysisManager::Instance().
GammaRayTelAnalysis::GammaRayTelAnalysis () private
Definition at line 67 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 67 of file GammaRayTelAnalysis.cc
References analysisMessenger, GammaRayTelDetector, G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), and histoFileName.
Referenced by getInstance().
Member Function Documentation
void GammaRayTelAnalysis::BeginOfRun ()
Definition at line 149 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 149 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::FinishNtuple(), G4cout, G4endl, GammaRayTelDetector, GammaRayTelDetectorConstruction::GetNbOfTKRLayers(), GammaRayTelDetectorConstruction::GetNbOfTKRStrips(), GammaRayTelDetectorConstruction::GetNbOfTKRTiles(), GammaRayTelDetectorConstruction::GetTKRSizeXY(), GammaRayTelDetectorConstruction::GetTKRSizeZ(), histo2DMode, histoFileName, G4ToolsAnalysisManager::Instance(), N, G4VAnalysisManager::OpenFile(), and G4VAnalysisManager::SetFirstHistoId().
Referenced by GammaRayTelRunAction::BeginOfRunAction().
void GammaRayTelAnalysis::EndOfEvent (G4int flag)
Definition at line 238 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 238 of file GammaRayTelAnalysis.cc
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelAnalysis::EndOfRun ()
Definition at line 228 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 228 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::CloseFile(), G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
Referenced by GammaRayTelRunAction::EndOfRunAction().
void GammaRayTelAnalysis::Finish ()
Definition at line 90 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 90 of file GammaRayTelAnalysis.cc
References analysisMessenger.
Referenced by ~GammaRayTelAnalysis().
G4String GammaRayTelAnalysis::GetHisto2DMode () inline
Definition at line 87 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 87 of file GammaRayTelAnalysis.hh
References histo2DMode.
Referenced by GammaRayTelEventAction::EndOfEventAction().
GammaRayTelAnalysis * GammaRayTelAnalysis::getInstance () static
Definition at line 96 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 96 of file GammaRayTelAnalysis.cc
References GammaRayTelAnalysis(), and instance.
Referenced by GammaRayTelRunAction::BeginOfRunAction(), GammaRayTelEventAction::EndOfEventAction(), GammaRayTelRunAction::EndOfRunAction(), and main().
void GammaRayTelAnalysis::Init ()
Definition at line 87 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 87 of file GammaRayTelAnalysis.cc
void GammaRayTelAnalysis::InsertEnergy (double en)
Definition at line 117 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 117 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::FillH1(), and G4ToolsAnalysisManager::Instance().
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelAnalysis::InsertHits (int nplane)
Definition at line 124 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 124 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::FillH1(), and G4ToolsAnalysisManager::Instance().
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelAnalysis::InsertPositionXZ (double x, double z)
Definition at line 103 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 103 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::FillH2(), and G4ToolsAnalysisManager::Instance().
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelAnalysis::InsertPositionYZ (double y, double z)
Definition at line 110 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 110 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::FillH2(), and G4ToolsAnalysisManager::Instance().
Referenced by GammaRayTelEventAction::EndOfEventAction().
void GammaRayTelAnalysis::Plot () private
void GammaRayTelAnalysis::SetHisto2DMode (G4String str) inline
Definition at line 86 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 86 of file GammaRayTelAnalysis.hh
References histo2DMode.
Referenced by GammaRayTelAnalysisMessenger::SetNewValue().
void GammaRayTelAnalysis::setNtuple (float E, float p, float x, float y, float z)
Definition at line 130 of file GammaRayTelAnalysis.cc.
View newest version in sPHENIX GitHub at line 130 of file GammaRayTelAnalysis.cc
References G4VAnalysisManager::AddNtupleRow(), G4VAnalysisManager::FillNtupleDColumn(), and G4ToolsAnalysisManager::Instance().
Referenced by GammaRayTelEventAction::EndOfEventAction().
Member Data Documentation
GammaRayTelAnalysisMessenger* GammaRayTelAnalysis::analysisMessenger private
Definition at line 114 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 114 of file GammaRayTelAnalysis.hh
Referenced by Finish(), and GammaRayTelAnalysis().
const GammaRayTelDetectorConstruction* GammaRayTelAnalysis::GammaRayTelDetector private
Definition at line 109 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 109 of file GammaRayTelAnalysis.hh
Referenced by BeginOfRun(), and GammaRayTelAnalysis().
G4String GammaRayTelAnalysis::histo2DMode private
Definition at line 111 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 111 of file GammaRayTelAnalysis.hh
Referenced by BeginOfRun(), GetHisto2DMode(), and SetHisto2DMode().
G4String GammaRayTelAnalysis::histoFileName private
Definition at line 112 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 112 of file GammaRayTelAnalysis.hh
Referenced by BeginOfRun(), and GammaRayTelAnalysis().
GammaRayTelAnalysis * GammaRayTelAnalysis::instance = 0 static private
Definition at line 107 of file GammaRayTelAnalysis.hh.
View newest version in sPHENIX GitHub at line 107 of file GammaRayTelAnalysis.hh
Referenced by getInstance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelAnalysis.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelAnalysis.cc