ECCE @ EIC Software: ECCEFastPIDMap Class Reference
ECCEFastPIDMap Class Reference abstract
#include <ecce-detectors/blob/master/FastPID/ECCEFastPIDMap.h>
Public Types
typedef std::map
< EICPIDDefs::PIDCandidate,
float > PIDCandidate_LogLikelihood_map
Public Member Functions
ECCEFastPIDMap (const std::string &name="ECCEFastPIDMap")
virtual ~ECCEFastPIDMap ()
virtual
PIDCandidate_LogLikelihood_map getFastSmearLogLikelihood (int truth_pid, const double momentum, const double theta) const =0
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
int m_Verbosity = 0
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 15 of file ECCEFastPIDMap.h.
View newest version in sPHENIX GitHub at line 15 of file ECCEFastPIDMap.h
Member Typedef Documentation
typedef std::map<EICPIDDefs::PIDCandidate, float> ECCEFastPIDMap::PIDCandidate_LogLikelihood_map
Definition at line 22 of file ECCEFastPIDMap.h.
View newest version in sPHENIX GitHub at line 22 of file ECCEFastPIDMap.h
Constructor & Destructor Documentation
ECCEFastPIDMap::ECCEFastPIDMap (const std::string & name = "ECCEFastPIDMap")
Definition at line 10 of file ECCEFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 10 of file ECCEFastPIDMap.cc
ECCEFastPIDMap::~ECCEFastPIDMap () virtual
Definition at line 13 of file ECCEFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 13 of file ECCEFastPIDMap.cc
Member Function Documentation
virtual PIDCandidate_LogLikelihood_map ECCEFastPIDMap::getFastSmearLogLikelihood (int truth_pid, const double momentum, const double theta) const pure virtual
Implemented in ECCEdRICHFastPIDMap, ECCEmRICHFastPIDMap, and ECCEhpDIRCFastPIDMap.
Referenced by ECCEFastPIDReco::process_event().
virtual void ECCEFastPIDMap::Verbosity (const int ival) inline virtual
Sets the verbosity of this module (0 by default=quiet).
Definition at line 32 of file ECCEFastPIDMap.h.
View newest version in sPHENIX GitHub at line 32 of file ECCEFastPIDMap.h
References m_Verbosity.
Referenced by mRICHReco(), RICHReco(), and Test_ECCEFastPIDMap().
virtual int ECCEFastPIDMap::Verbosity () const inline virtual
Gets the verbosity of this module.
Definition at line 35 of file ECCEFastPIDMap.h.
View newest version in sPHENIX GitHub at line 35 of file ECCEFastPIDMap.h
References m_Verbosity.
Referenced by ECCEmRICHFastPIDMap::getFastSmearLogLikelihood(), ECCEdRICHFastPIDMap::getFastSmearLogLikelihood(), and ECCEdRICHFastPIDMap::numSigma().
Member Data Documentation
int ECCEFastPIDMap::m_Verbosity = 0 private
The verbosity level. 0 means not verbose at all.
Definition at line 39 of file ECCEFastPIDMap.h.
View newest version in sPHENIX GitHub at line 39 of file ECCEFastPIDMap.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
ecce-detectors/blob/master/FastPID/ECCEFastPIDMap.h
ecce-detectors/blob/master/FastPID/ECCEFastPIDMap.cc