ECCE @ EIC Software: G4HadronicProcess Class Reference
G4HadronicProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadronicProcess.hh>
Public Member Functions
G4HadronicProcess (const G4String &processName="Hadronic", G4ProcessType procType=fHadronic)
G4HadronicProcess (const G4String &processName, G4HadronicProcessType subType)
~G4HadronicProcess () override
void RegisterMe (G4HadronicInteraction *a)
G4double GetElementCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4double GetMicroscopicCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
void PreparePhysicsTable (const G4ParticleDefinition &) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
void DumpPhysicsTable (const G4ParticleDefinition &p)
void AddDataSet (G4VCrossSectionDataSet *aDataSet)
std::vector
< G4HadronicInteraction * > & GetHadronicInteractionList ()
G4HadronicInteraction * GetHadronicModel (const G4String &)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
const G4Nucleus * GetTargetNucleus () const
const G4Isotope * GetTargetIsotope ()
void ProcessDescription (std::ostream &outFile) const override
void BiasCrossSectionByFactor (G4double aScale)
void MultiplyCrossSectionBy (G4double factor)
G4double CrossSectionFactor () const
void SetIntegral (G4bool val)
void SetEpReportLevel (G4int level)
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
G4CrossSectionDataStore * GetCrossSectionDataStore ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4HadronicInteraction * ChooseHadronicInteraction (const G4HadProjectile &aHadProjectile, G4Nucleus &aTargetNucleus, const G4Material *aMaterial, const G4Element *anElement)
G4Nucleus * GetTargetNucleusPointer ()
void DumpState (const G4Track &, const G4String &, G4ExceptionDescription &)
G4HadronicInteraction * GetHadronicInteraction () const
G4double GetLastCrossSection ()
void FillResult (G4HadFinalState *aR, const G4Track &aT)
G4HadFinalState * CheckResult (const G4HadProjectile &thePro, const G4Nucleus &targetNucleus, G4HadFinalState *result)
void CheckEnergyMomentumConservation (const G4Track &, const G4Nucleus &)
Protected Attributes
G4HadProjectile thePro
G4ParticleChange * theTotalResult
G4double fWeight
G4int epReportLevel
Private Member Functions
void InitialiseLocal ()
G4double XBiasSurvivalProbability ()
G4double XBiasSecondaryWeight ()
G4HadronicProcess & operator= (const G4HadronicProcess &right)
G4HadronicProcess (const G4HadronicProcess &)
void GetEnergyMomentumCheckEnvvars ()
Private Attributes
G4EnergyRangeManager theEnergyRangeManager
G4HadronicInteraction * theInteraction
G4CrossSectionDataStore * theCrossSectionDataStore
G4HadronicProcessStore * theProcessStore
G4Nucleus targetNucleus
bool G4HadronicProcess_debug_flag
bool useIntegralXS
G4int nMatWarn
G4int nICelectrons
G4int idxIC
std::pair< G4double, G4double > epCheckLevels
G4bool levelsSetByProcess
std::vector
< G4VLeadingParticleBiasing * > theBias
G4double theInitialNumberOfInteractionLength
G4double aScaleFactor
G4bool xBiasOn
G4double theLastCrossSection
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 68 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HadronicProcess.hh
Constructor & Destructor Documentation
G4HadronicProcess::G4HadronicProcess (const G4String & processName = "Hadronic", G4ProcessType procType = fHadronic)
Definition at line 83 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 83 of file G4HadronicProcess.cc
References fHadronInelastic, InitialiseLocal(), and G4VProcess::SetProcessSubType().
G4HadronicProcess::G4HadronicProcess (const G4String & processName, G4HadronicProcessType subType)
Definition at line 93 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 93 of file G4HadronicProcess.cc
References InitialiseLocal(), and G4VProcess::SetProcessSubType().
G4HadronicProcess::~G4HadronicProcess () override
Definition at line 101 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 101 of file G4HadronicProcess.cc
References G4HadronicProcessStore::DeRegister(), theCrossSectionDataStore, theProcessStore, and theTotalResult.
G4HadronicProcess::G4HadronicProcess (const G4HadronicProcess &) private
Member Function Documentation
void G4HadronicProcess::AddDataSet (G4VCrossSectionDataSet * aDataSet)
Definition at line 774 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 774 of file G4HadronicProcess.cc
References G4CrossSectionDataStore::AddDataSet(), and theCrossSectionDataStore.
Referenced by G4VHadronPhysics::AddCaptureCrossSection(), G4VHadronPhysics::AddElasticCrossSection(), G4VHadronPhysics::AddFissionCrossSection(), G4VHadronPhysics::AddInelasticCrossSection(), G4IonPhysicsXS::AddProcess(), G4IonPhysics::AddProcess(), G4IonPhysicsPHP::AddProcess(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), G4HadronElasticPhysics::AddXSection(), BiasingOperation::BiasingOperation(), G4NeutronLENDBuilder::Build(), G4ProtonPHPBuilder::Build(), G4AlphaPHPBuilder::Build(), G4NeutronPHPBuilder::Build(), G4He3PHPBuilder::Build(), G4DeuteronPHPBuilder::Build(), G4TritonPHPBuilder::Build(), G4LENDBertiniGammaElectroNuclearBuilder::Build(), G4BinaryPiKBuilder::Build(), G4BertiniPiKBuilder::Build(), G4BinaryPionBuilder::Build(), G4PrecoProtonBuilder::Build(), G4BertiniKaonBuilder::Build(), G4BertiniPionBuilder::Build(), G4INCLXXPionBuilder::Build(), G4PrecoNeutronBuilder::Build(), G4INCLXXNeutronBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4FTFBinaryPionBuilder::Build(), G4FTFBinaryProtonBuilder::Build(), G4FTFPPionBuilder::Build(), G4FTFPProtonBuilder::Build(), G4FTFBinaryPiKBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4FTFPAntiBarionBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4FTFBinaryNeutronBuilder::Build(), G4QGSPPiKBuilder::Build(), G4QGSPPionBuilder::Build(), G4QGSPProtonBuilder::Build(), G4FTFPPiKBuilder::Build(), G4QGSBinaryNeutronBuilder::Build(), G4FTFPNeutronBuilder::Build(), G4QGSPNeutronBuilder::Build(), G4INCLXXProtonBuilder::Build(), G4HyperonFTFPBuilder::Build(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4EmExtraPhysics::ConstructLENDGammaNuclear(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), HadronElasticPhysicsHP::ConstructProcess(), NeutronHPphysics::ConstructProcess(), G4ThermalNeutrons::ConstructProcess(), G4NeutronCrossSectionXS::ConstructProcess(), G4HadronElasticPhysicsPHP::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsLEND::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFP_BERT_TRV::ExtraConfiguration(), G4HadronPhysicsQGS_BIC::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsFTF_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsFTFP_BERT::ExtraConfiguration(), G4HadronPhysicsINCLXX::ExtraConfiguration(), G4ChargeExchangeProcess::G4ChargeExchangeProcess(), G4HadronCaptureProcess::G4HadronCaptureProcess(), G4HadronFissionProcess::G4HadronFissionProcess(), and G4MuonNuclearProcess::G4MuonNuclearProcess().
void G4HadronicProcess::BiasCrossSectionByFactor (G4double aScale)
Definition at line 494 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 494 of file G4HadronicProcess.cc
References aScaleFactor, G4Exception(), G4VProcess::GetProcessName(), JustWarning, and xBiasOn.
Referenced by MultiplyCrossSectionBy().
void G4HadronicProcess::BuildPhysicsTable (const G4ParticleDefinition & p) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4HadronStoppingProcess, and G4ChargeExchangeProcess.
Definition at line 188 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 188 of file G4HadronicProcess.cc
References G4EnergyRangeManager::BuildPhysicsTable(), G4CrossSectionDataStore::BuildPhysicsTable(), G4HadronicProcessStore::Instance(), G4HadronicProcessStore::PrintInfo(), theCrossSectionDataStore, and theEnergyRangeManager.
Referenced by G4ChargeExchangeProcess::BuildPhysicsTable(), and G4GammaGeneralProcess::BuildPhysicsTable().
void G4HadronicProcess::CheckEnergyMomentumConservation (const G4Track & aTrack, const G4Nucleus & aNucleus) protected
Definition at line 599 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 599 of file G4HadronicProcess.cc
References kdfinder::abs(), DBL_MAX, CLHEP::HepLorentzVector::e(), CLHEP::electron_mass_c2, epCheckLevels, epReportLevel, false, G4String::first(), fStopAndKill, G4cerr, G4cout, G4endl, G4lrint(), G4DynamicParticle::Get4Momentum(), G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetBaryonNumber(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4ParticleChange::GetEnergy(), G4HadronicInteraction::GetEnergyMomentumCheckLevels(), GetHadronicInteraction(), G4Track::GetKineticEnergy(), G4HadronicInteraction::GetModelName(), G4Track::GetMomentum(), G4ParticleChange::GetMomentumDirection(), G4NucleiProperties::GetNuclearMass(), G4VParticleChange::GetNumberOfSecondaries(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4VProcess::GetProcessName(), G4VParticleChange::GetSecondary(), G4VParticleChange::GetTrackStatus(), G4Nucleus::GetZ_asInt(), levelsSetByProcess, CLHEP::Hep3Vector::mag(), MeV, min, nICelectrons, G4Track::SetKineticEnergy(), G4Track::SetMomentumDirection(), theTotalResult, and CLHEP::HepLorentzVector::vect().
Referenced by G4HadronStoppingProcess::AtRestDoIt(), G4HadronElasticProcess::PostStepDoIt(), and PostStepDoIt().
G4HadFinalState * G4HadronicProcess::CheckResult (const G4HadProjectile & thePro, const G4Nucleus & targetNucleus, G4HadFinalState * result) protected
Definition at line 507 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 507 of file G4HadronicProcess.cc
References kdfinder::abs(), G4HadFinalState::Clear(), incremental_prev_tag::desc, CLHEP::HepLorentzVector::e(), epReportLevel, EventMustBeAborted, G4endl, G4Exception(), G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4HadFinalState::GetEnergyChange(), G4HadronicInteraction::GetFatalEnergyCheckLevels(), GetHadronicInteraction(), G4HadProjectile::GetKineticEnergy(), G4HadFinalState::GetLocalEnergyDeposit(), G4DynamicParticle::GetMass(), G4HadronicInteraction::GetModelName(), G4NucleiProperties::GetNuclearMass(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), G4VProcess::GetProcessName(), G4HadFinalState::GetSecondary(), G4HadFinalState::GetStatusChange(), G4HadProjectile::GetTotalEnergy(), G4DynamicParticle::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), G4ParticleDefinition::IsShortLived(), JustWarning, MeV, and stopAndKill.
Referenced by G4HadronStoppingProcess::AtRestDoIt(), G4HadronElasticProcess::PostStepDoIt(), and PostStepDoIt().
G4HadronicInteraction* G4HadronicProcess::ChooseHadronicInteraction (const G4HadProjectile & aHadProjectile, G4Nucleus & aTargetNucleus, const G4Material * aMaterial, const G4Element * anElement) inline protected
Definition at line 135 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 135 of file G4HadronicProcess.hh
References G4EnergyRangeManager::GetHadronicInteraction(), and theEnergyRangeManager.
Referenced by G4HadronStoppingProcess::AtRestDoIt(), G4HadronElasticProcess::PostStepDoIt(), and PostStepDoIt().
G4double G4HadronicProcess::CrossSectionFactor () const inline
Definition at line 152 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 152 of file G4HadronicProcess.hh
References aScaleFactor.
void G4HadronicProcess::DumpPhysicsTable (const G4ParticleDefinition & p)
Definition at line 769 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 769 of file G4HadronicProcess.cc
References G4CrossSectionDataStore::DumpPhysicsTable(), and theCrossSectionDataStore.
void G4HadronicProcess::DumpState (const G4Track & aTrack, const G4String & method, G4ExceptionDescription & ed) protected
Definition at line 744 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 744 of file G4HadronicProcess.cc
References G4endl, G4Track::GetKineticEnergy(), G4Track::GetMaterial(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4Track::GetParentID(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4VProcess::GetProcessName(), G4Track::GetTrackID(), G4Track::GetVolume(), CLHEP::GeV, and CLHEP::mm.
Referenced by G4HadronStoppingProcess::AtRestDoIt(), FillResult(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and PostStepDoIt().
void G4HadronicProcess::FillResult (G4HadFinalState * aR, const G4Track & aT) protected
Definition at line 387 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 387 of file G4HadronicProcess.cc
References kdfinder::abs(), G4ParticleChange::AddSecondary(), G4HadFinalState::Clear(), dir, DumpState(), e, CLHEP::eV, fAlive, fStopAndKill, fStopButAlive, fWeight, G4endl, G4Exception(), G4HadronicProcess_debug_flag, G4Nucleus::GetA_asInt(), G4ProcessManager::GetAtRestProcessVector(), G4HadSecondary::GetCreatorModelType(), G4DynamicParticle::GetDefinition(), G4HadFinalState::GetEnergyChange(), G4Track::GetGlobalTime(), G4PhysicsModelCatalog::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4HadFinalState::GetLocalEnergyDeposit(), G4DynamicParticle::GetMass(), G4HadFinalState::GetMomentumChange(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4Track::GetPosition(), G4ParticleDefinition::GetProcessManager(), G4HadFinalState::GetSecondary(), G4HadFinalState::GetStatusChange(), G4HadSecondary::GetTime(), G4Track::GetTouchableHandle(), G4Track::GetTrackID(), G4HadSecondary::GetWeight(), G4Nucleus::GetZ_asInt(), CLHEP::GeV, incremental_prev_tag::idx, idxIC, JustWarning, CLHEP::keV, mass, max, nICelectrons, part, G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4Track::SetCreatorModelIndex(), G4DynamicParticle::SetKineticEnergy(), G4DynamicParticle::SetMass(), G4DynamicParticle::SetMomentumDirection(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), G4ProcessVector::size(), stopAndKill, targetNucleus, theTotalResult, Acts::VectorHelpers::time(), and track.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and PostStepDoIt().
G4CrossSectionDataStore* G4HadronicProcess::GetCrossSectionDataStore () inline
Definition at line 173 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 173 of file G4HadronicProcess.hh
References theCrossSectionDataStore.
Referenced by G4ChargeExchangeProcess::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4ElectronNuclearProcess::G4ElectronNuclearProcess(), G4PhotoNuclearProcess::G4PhotoNuclearProcess(), G4PositronNuclearProcess::G4PositronNuclearProcess(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4HadronicProcessStore::Print(), G4HadronicProcessStore::PrintHtml(), and G4GammaGeneralProcess::SampleSecondaries().
G4double G4HadronicProcess::GetElementCrossSection (const G4DynamicParticle * part, const G4Element * elm, const G4Material * mat = nullptr)
Definition at line 158 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 158 of file G4HadronicProcess.cc
References G4Exception(), G4CrossSectionDataStore::GetCrossSection(), G4VProcess::GetProcessName(), G4Element::GetZasInt(), JustWarning, max, nMatWarn, nmax, and theCrossSectionDataStore.
Referenced by G4HadronicProcessStore::GetCaptureCrossSectionPerAtom(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerAtom(), G4HadronicProcessStore::GetElasticCrossSectionPerAtom(), G4HadronicProcessStore::GetFissionCrossSectionPerAtom(), G4HadronicProcessStore::GetInelasticCrossSectionPerAtom(), and GetMicroscopicCrossSection().
void G4HadronicProcess::GetEnergyMomentumCheckEnvvars () private
Definition at line 128 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 128 of file G4HadronicProcess.cc
References DBL_MAX, epCheckLevels, epReportLevel, and levelsSetByProcess.
Referenced by InitialiseLocal().
std::pair<G4double, G4double> G4HadronicProcess::GetEnergyMomentumCheckLevels () const inline
Definition at line 169 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 169 of file G4HadronicProcess.hh
References epCheckLevels.
Referenced by G4HadronicProcessStore::SetProcessAbsLevel(), and G4HadronicProcessStore::SetProcessRelLevel().
G4HadronicInteraction* G4HadronicProcess::GetHadronicInteraction () const inline protected
Definition at line 181 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 181 of file G4HadronicProcess.hh
References theInteraction.
Referenced by CheckEnergyMomentumConservation(), and CheckResult().
std::vector< G4HadronicInteraction * > & G4HadronicProcess::GetHadronicInteractionList ()
Definition at line 780 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 780 of file G4HadronicProcess.cc
References G4EnergyRangeManager::GetHadronicInteractionList(), and theEnergyRangeManager.
Referenced by G4ThermalNeutrons::ConstructProcess(), G4HadronElasticPhysics::GetElasticModel(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), and G4NeutrinoElectronProcess::PostStepDoIt().
G4HadronicInteraction * G4HadronicProcess::GetHadronicModel (const G4String & modelName)
Definition at line 786 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 786 of file G4HadronicProcess.cc
References G4EnergyRangeManager::GetHadronicInteractionList(), and theEnergyRangeManager.
G4double G4HadronicProcess::GetLastCrossSection () inline protected
Definition at line 185 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 185 of file G4HadronicProcess.hh
References theLastCrossSection.
G4double G4HadronicProcess::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition *) override virtual
Implements G4VDiscreteProcess.
Reimplemented in G4MuNeutrinoNucleusProcess, and G4NeutrinoElectronProcess.
Definition at line 196 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 196 of file G4HadronicProcess.cc
References aScaleFactor, G4CrossSectionDataStore::ComputeCrossSection(), DBL_MAX, G4Track::GetDynamicParticle(), G4Track::GetMaterial(), theCrossSectionDataStore, and theLastCrossSection.
G4double G4HadronicProcess::GetMicroscopicCrossSection (const G4DynamicParticle * part, const G4Element * elm, const G4Material * mat = nullptr) inline
Definition at line 90 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HadronicProcess.hh
References GetElementCrossSection(), and mat.
const G4Isotope* G4HadronicProcess::GetTargetIsotope () inline
Definition at line 126 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 126 of file G4HadronicProcess.hh
References G4Nucleus::GetIsotope(), and targetNucleus.
const G4Nucleus* G4HadronicProcess::GetTargetNucleus () const inline
Definition at line 122 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 122 of file G4HadronicProcess.hh
References targetNucleus.
G4Nucleus* G4HadronicProcess::GetTargetNucleusPointer () inline protected
Definition at line 144 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 144 of file G4HadronicProcess.hh
References targetNucleus.
Referenced by G4HadronStoppingProcess::AtRestDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4MuNeutrinoNucleusProcess::PostStepDoIt().
void G4HadronicProcess::InitialiseLocal () private
Definition at line 108 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 108 of file G4HadronicProcess.cc
References aScaleFactor, fWeight, G4HadronicProcess_debug_flag, GetEnergyMomentumCheckEnvvars(), idxIC, G4HadronicProcessStore::Instance(), nICelectrons, nMatWarn, G4HadronicProcessStore::Register(), G4VParticleChange::SetSecondaryWeightByProcess(), theCrossSectionDataStore, theInitialNumberOfInteractionLength, theInteraction, theLastCrossSection, theProcessStore, theTotalResult, useIntegralXS, and xBiasOn.
Referenced by G4HadronicProcess().
void G4HadronicProcess::MultiplyCrossSectionBy (G4double factor)
Definition at line 489 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 489 of file G4HadronicProcess.cc
References BiasCrossSectionByFactor().
G4HadronicProcess& G4HadronicProcess::operator= (const G4HadronicProcess & right) private
G4VParticleChange * G4HadronicProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Reimplemented in G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, and G4HadronElasticProcess.
Definition at line 208 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 208 of file G4HadronicProcess.cc
References G4HadronicInteraction::ApplyYourself(), aScaleFactor, CheckEnergyMomentumConservation(), CheckResult(), ChooseHadronicInteraction(), G4VParticleChange::Clear(), G4VProcess::ClearNumberOfInteractionLengthLeft(), G4CrossSectionDataStore::ComputeCrossSection(), G4KaonZero::Definition(), G4AntiKaonZero::Definition(), G4KaonZeroLong::Definition(), G4KaonZeroShort::Definition(), DumpState(), epReportLevel, fAlive, FatalException, FillResult(), fKillTrackAndSecondaries, fPostponeToNextEvent, fStopAndKill, fSuspend, fWeight, G4endl, G4Exception(), G4Hadronic_Random_File, G4UniformRand, G4Nucleus::GetA_asInt(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetMaterial(), G4HadronicInteraction::GetModelName(), G4Element::GetName(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4HadFinalState::GetSecondary(), G4Track::GetTrackStatus(), G4HadProjectile::GetTrafoToLab(), G4Track::GetWeight(), G4Nucleus::GetZ_asInt(), G4HadProjectile::Initialise(), G4ParticleChange::Initialize(), JustWarning, G4VParticleChange::ProposeWeight(), G4HadronicException::Report(), G4CrossSectionDataStore::SampleZandA(), CLHEP::HepRandom::saveEngineStatus(), G4DynamicParticle::SetDefinition(), G4HadFinalState::SetTrafoToLab(), targetNucleus, theCrossSectionDataStore, theInteraction, theLastCrossSection, thePro, and theTotalResult.
Referenced by BiasingOperation::ApplyFinalStateBiasing(), and G4GammaGeneralProcess::SampleSecondaries().
void G4HadronicProcess::PreparePhysicsTable (const G4ParticleDefinition & p) override virtual
Reimplemented from G4VProcess.
Reimplemented in G4HadronStoppingProcess, G4MuNeutrinoNucleusProcess, and G4NeutrinoElectronProcess.
Definition at line 180 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 180 of file G4HadronicProcess.cc
References G4HadronicProcess_debug_flag, G4HadronicProcessStore::RegisterParticle(), and theProcessStore.
Referenced by G4MuNeutrinoNucleusProcess::PreparePhysicsTable(), G4NeutrinoElectronProcess::PreparePhysicsTable(), and G4GammaGeneralProcess::PreparePhysicsTable().
void G4HadronicProcess::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Reimplemented in G4HadronStoppingProcess, G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, G4HadronicAbsorptionFritiofWithBinaryCascade, G4HadronElasticProcess, G4MuonMinusCapture, G4HadronFissionProcess, G4HadronCaptureProcess, G4HadronicAbsorptionFritiof, G4PhotoNuclearProcess, G4PhotoCaptureProcess, G4HadronicAbsorptionBertini, G4NeutronInelasticProcess, G4PhotoFissionProcess, G4AntiAlphaInelasticProcess, G4AntiDeuteronInelasticProcess, G4AntiHe3InelasticProcess, G4AntiNeutronInelasticProcess, G4ElectronNuclearProcess, G4IonInelasticProcess, G4MuonNuclearProcess, G4PionMinusInelasticProcess, G4AlphaInelasticProcess, G4AntiOmegaMinusInelasticProcess, G4AntiProtonInelasticProcess, G4AntiSigmaMinusInelasticProcess, G4AntiSigmaPlusInelasticProcess, G4AntiTritonInelasticProcess, G4AntiXiMinusInelasticProcess, G4AntiXiZeroInelasticProcess, G4DeuteronInelasticProcess, G4KaonMinusInelasticProcess, G4KaonPlusInelasticProcess, G4KaonZeroLInelasticProcess, G4KaonZeroSInelasticProcess, G4LambdaInelasticProcess, G4OmegaMinusInelasticProcess, G4PionPlusInelasticProcess, G4ProtonInelasticProcess, G4SigmaMinusInelasticProcess, G4SigmaPlusInelasticProcess, G4TritonInelasticProcess, G4XiMinusInelasticProcess, G4XiZeroInelasticProcess, G4AntiLambdaInelasticProcess, G4He3InelasticProcess, G4PositronNuclearProcess, G4AntiBMesonZeroInelasticProcess, G4AntiBsMesonZeroInelasticProcess, G4AntiDMesonZeroInelasticProcess, G4AntiLambdabInelasticProcess, G4AntiLambdacPlusInelasticProcess, G4AntiOmegabMinusInelasticProcess, G4AntiOmegacZeroInelasticProcess, G4AntiXibMinusInelasticProcess, G4AntiXibZeroInelasticProcess, G4AntiXicPlusInelasticProcess, G4AntiXicZeroInelasticProcess, G4BcMesonMinusInelasticProcess, G4BcMesonPlusInelasticProcess, G4BMesonMinusInelasticProcess, G4BMesonPlusInelasticProcess, G4BMesonZeroInelasticProcess, G4BsMesonZeroInelasticProcess, G4DMesonMinusInelasticProcess, G4DMesonPlusInelasticProcess, G4DMesonZeroInelasticProcess, G4DsMesonMinusInelasticProcess, G4DsMesonPlusInelasticProcess, G4LambdabInelasticProcess, G4LambdacPlusInelasticProcess, G4OmegabMinusInelasticProcess, G4OmegacZeroInelasticProcess, G4XibMinusInelasticProcess, G4XibZeroInelasticProcess, G4XicPlusInelasticProcess, and G4XicZeroInelasticProcess.
Definition at line 363 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 363 of file G4HadronicProcess.cc
Referenced by G4HadronicProcessStore::PrintHtml(), and G4GammaGeneralProcess::ProcessDescription().
void G4HadronicProcess::RegisterMe (G4HadronicInteraction * a)
Definition at line 141 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 141 of file G4HadronicProcess.cc
References FatalException, G4endl, G4Exception(), G4HadronicInteraction::GetModelName(), G4VProcess::GetProcessName(), G4HadronicProcessStore::Instance(), G4HadronicProcessStore::RegisterInteraction(), G4EnergyRangeManager::RegisterMe(), G4HadronicException::Report(), and theEnergyRangeManager.
Referenced by G4IonPhysicsXS::AddProcess(), G4IonPhysics::AddProcess(), G4IonPhysicsPHP::AddProcess(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), BiasingOperation::BiasingOperation(), G4AlphaPHPBuilder::Build(), G4NeutronLENDBuilder::Build(), G4ProtonPHPBuilder::Build(), G4NeutronPHPBuilder::Build(), G4BertiniElectroNuclearBuilder::Build(), G4He3PHPBuilder::Build(), G4DeuteronPHPBuilder::Build(), G4TritonPHPBuilder::Build(), G4LENDBertiniGammaElectroNuclearBuilder::Build(), G4BinaryProtonBuilder::Build(), G4BinaryTritonBuilder::Build(), G4BertiniPiKBuilder::Build(), G4BinaryAlphaBuilder::Build(), G4PrecoProtonBuilder::Build(), G4BinaryDeuteronBuilder::Build(), G4BinaryHe3Builder::Build(), G4BertiniProtonBuilder::Build(), G4BinaryPiKBuilder::Build(), G4BinaryPionBuilder::Build(), G4BertiniKaonBuilder::Build(), G4BertiniNeutronBuilder::Build(), G4BertiniPionBuilder::Build(), G4BinaryNeutronBuilder::Build(), G4FTFBinaryKaonBuilder::Build(), G4INCLXXPionBuilder::Build(), G4PrecoNeutronBuilder::Build(), G4FTFBinaryPionBuilder::Build(), G4FTFBinaryProtonBuilder::Build(), G4FTFPKaonBuilder::Build(), G4FTFPPionBuilder::Build(), G4FTFPProtonBuilder::Build(), G4INCLXXNeutronBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4FTFBinaryPiKBuilder::Build(), G4FTFPAntiBarionBuilder::Build(), G4QGSBinaryKaonBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4QGSPKaonBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4QGSPProtonBuilder::Build(), G4QGSPPionBuilder::Build(), G4FTFBinaryNeutronBuilder::Build(), G4FTFPPiKBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4QGSPPiKBuilder::Build(), G4FTFPNeutronBuilder::Build(), G4QGSBinaryNeutronBuilder::Build(), G4QGSPNeutronBuilder::Build(), G4INCLXXProtonBuilder::Build(), G4HyperonFTFPBuilder::Build(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4EmExtraPhysics::ConstructLENDGammaNuclear(), ProtonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), GammaNuclearPhysics::ConstructProcess(), HadronElasticPhysicsHP::ConstructProcess(), NeutronHPphysics::ConstructProcess(), G4ThermalNeutrons::ConstructProcess(), G4HadronElasticPhysicsPHP::ConstructProcess(), MuNuclearBuilder::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsLEND::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsFTFP_BERT_TRV::ExtraConfiguration(), G4HadronPhysicsQGS_BIC::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsFTF_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BIC::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsFTFP_BERT::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsINCLXX::ExtraConfiguration(), G4HadronicAbsorptionBertini::G4HadronicAbsorptionBertini(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4MuonMinusCapture::G4MuonMinusCapture(), and CexmcHadronicProcess::RegisterProductionModel().
void G4HadronicProcess::SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel) inline
Definition at line 163 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 163 of file G4HadronicProcess.hh
References epCheckLevels, and levelsSetByProcess.
Referenced by G4HadronicProcessStore::SetProcessAbsLevel(), and G4HadronicProcessStore::SetProcessRelLevel().
void G4HadronicProcess::SetEpReportLevel (G4int level) inline
Definition at line 160 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 160 of file G4HadronicProcess.hh
References epReportLevel.
void G4HadronicProcess::SetIntegral (G4bool val) inline
Definition at line 156 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 156 of file G4HadronicProcess.hh
References useIntegralXS.
G4double G4HadronicProcess::XBiasSecondaryWeight () private
Definition at line 378 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 378 of file G4HadronicProcess.cc
References aScaleFactor, G4Exp(), and G4VProcess::GetTotalNumberOfInteractionLengthTraversed().
G4double G4HadronicProcess::XBiasSurvivalProbability () private
Definition at line 369 of file G4HadronicProcess.cc.
View newest version in sPHENIX GitHub at line 369 of file G4HadronicProcess.cc
References aScaleFactor, G4Exp(), and G4VProcess::GetTotalNumberOfInteractionLengthTraversed().
Member Data Documentation
G4double G4HadronicProcess::aScaleFactor private
Definition at line 253 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 253 of file G4HadronicProcess.hh
Referenced by BiasCrossSectionByFactor(), CrossSectionFactor(), GetMeanFreePath(), InitialiseLocal(), PostStepDoIt(), XBiasSecondaryWeight(), and XBiasSurvivalProbability().
std::pair<G4double, G4double> G4HadronicProcess::epCheckLevels private
Definition at line 246 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 246 of file G4HadronicProcess.hh
Referenced by CheckEnergyMomentumConservation(), GetEnergyMomentumCheckEnvvars(), GetEnergyMomentumCheckLevels(), and SetEnergyMomentumCheckLevels().
G4int G4HadronicProcess::epReportLevel protected
Definition at line 221 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 221 of file G4HadronicProcess.hh
Referenced by G4HadronStoppingProcess::AtRestDoIt(), CheckEnergyMomentumConservation(), CheckResult(), GetEnergyMomentumCheckEnvvars(), G4HadronElasticProcess::PostStepDoIt(), PostStepDoIt(), and SetEpReportLevel().
G4double G4HadronicProcess::fWeight protected
Definition at line 219 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 219 of file G4HadronicProcess.hh
Referenced by FillResult(), InitialiseLocal(), and PostStepDoIt().
bool G4HadronicProcess::G4HadronicProcess_debug_flag private
Definition at line 235 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 235 of file G4HadronicProcess.hh
Referenced by FillResult(), InitialiseLocal(), and PreparePhysicsTable().
G4int G4HadronicProcess::idxIC private
Definition at line 243 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 243 of file G4HadronicProcess.hh
Referenced by FillResult(), and InitialiseLocal().
G4bool G4HadronicProcess::levelsSetByProcess private
Definition at line 247 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 247 of file G4HadronicProcess.hh
Referenced by CheckEnergyMomentumConservation(), GetEnergyMomentumCheckEnvvars(), and SetEnergyMomentumCheckLevels().
G4int G4HadronicProcess::nICelectrons private
Definition at line 241 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 241 of file G4HadronicProcess.hh
Referenced by CheckEnergyMomentumConservation(), FillResult(), and InitialiseLocal().
G4int G4HadronicProcess::nMatWarn private
Definition at line 239 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 239 of file G4HadronicProcess.hh
Referenced by GetElementCrossSection(), and InitialiseLocal().
G4Nucleus G4HadronicProcess::targetNucleus private
Definition at line 233 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 233 of file G4HadronicProcess.hh
Referenced by FillResult(), GetTargetIsotope(), GetTargetNucleus(), GetTargetNucleusPointer(), and PostStepDoIt().
std::vector<G4VLeadingParticleBiasing*> G4HadronicProcess::theBias private
Definition at line 249 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 249 of file G4HadronicProcess.hh
G4CrossSectionDataStore* G4HadronicProcess::theCrossSectionDataStore private
Definition at line 229 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 229 of file G4HadronicProcess.hh
Referenced by AddDataSet(), BuildPhysicsTable(), DumpPhysicsTable(), GetCrossSectionDataStore(), GetElementCrossSection(), GetMeanFreePath(), InitialiseLocal(), PostStepDoIt(), and ~G4HadronicProcess().
G4EnergyRangeManager G4HadronicProcess::theEnergyRangeManager private
Definition at line 225 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 225 of file G4HadronicProcess.hh
Referenced by BuildPhysicsTable(), ChooseHadronicInteraction(), GetHadronicInteractionList(), GetHadronicModel(), and RegisterMe().
G4double G4HadronicProcess::theInitialNumberOfInteractionLength private
Definition at line 251 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 251 of file G4HadronicProcess.hh
Referenced by InitialiseLocal().
G4HadronicInteraction* G4HadronicProcess::theInteraction private
Definition at line 227 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 227 of file G4HadronicProcess.hh
Referenced by GetHadronicInteraction(), InitialiseLocal(), and PostStepDoIt().
G4double G4HadronicProcess::theLastCrossSection private
Definition at line 255 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 255 of file G4HadronicProcess.hh
Referenced by GetLastCrossSection(), GetMeanFreePath(), InitialiseLocal(), and PostStepDoIt().
G4HadProjectile G4HadronicProcess::thePro protected
Definition at line 215 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 215 of file G4HadronicProcess.hh
Referenced by G4HadronStoppingProcess::AtRestDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and PostStepDoIt().
G4HadronicProcessStore* G4HadronicProcess::theProcessStore private
Definition at line 231 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 231 of file G4HadronicProcess.hh
Referenced by InitialiseLocal(), PreparePhysicsTable(), and ~G4HadronicProcess().
G4ParticleChange* G4HadronicProcess::theTotalResult protected
Definition at line 217 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 217 of file G4HadronicProcess.hh
Referenced by G4HadronStoppingProcess::AtRestDoIt(), CheckEnergyMomentumConservation(), FillResult(), InitialiseLocal(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), PostStepDoIt(), and ~G4HadronicProcess().
bool G4HadronicProcess::useIntegralXS private
Definition at line 237 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 237 of file G4HadronicProcess.hh
Referenced by InitialiseLocal(), and SetIntegral().
G4bool G4HadronicProcess::xBiasOn private
Definition at line 254 of file G4HadronicProcess.hh.
View newest version in sPHENIX GitHub at line 254 of file G4HadronicProcess.hh
Referenced by BiasCrossSectionByFactor(), and InitialiseLocal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadronicProcess.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/src/G4HadronicProcess.cc