ECCE @ EIC Software: Par02FastSimModelHCal Class Reference
Par02FastSimModelHCal Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02FastSimModelHCal.hh>
Public Member Functions
Par02FastSimModelHCal (G4String aModelName, G4Region *aEnvelope, Par02DetectorParametrisation::Parametrisation aParamType)
Par02FastSimModelHCal (G4String aModelName, G4Region *aEnvelope)
Par02FastSimModelHCal (G4String aModelName)
~Par02FastSimModelHCal ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticle)
virtual G4bool ModelTrigger (const G4FastTrack &aFastTrack)
virtual void DoIt (const G4FastTrack &aFastTrack, G4FastStep &aFastStep)
Public Member Functions inherited from G4VFastSimulationModel
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Private Attributes
Par02DetectorParametrisation * fCalculateParametrisation
Par02DetectorParametrisation::Parametrisation fParametrisation
A parametrisation type.
Detailed Description
Shortcut to the ordinary tracking for hadronic calorimeters.
Fast simulation model describes what should be done instead of a normal tracking. Instead of the ordinary tracking, a particle deposits its energy at the entrance to the hadronic calorimeter and its value is smeared (by Par02Smearer::SmearMomentum()). Based on G4 examples/extended/parametrisations/Par01/include/Par01EMShowerModel.hh .
Author
Anna Zaborowska
Definition at line 46 of file Par02FastSimModelHCal.hh.
View newest version in sPHENIX GitHub at line 46 of file Par02FastSimModelHCal.hh
Constructor & Destructor Documentation
Par02FastSimModelHCal::Par02FastSimModelHCal (G4String aModelName, G4Region * aEnvelope, Par02DetectorParametrisation::Parametrisation aParamType)
A constructor.
Parameters
aModelName A name of the fast simulation model.
aEnvelope A region where the model can take over the ordinary tracking.
aParamType A parametrisation type.
Definition at line 46 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 46 of file Par02FastSimModelHCal.cc
Par02FastSimModelHCal::Par02FastSimModelHCal (G4String aModelName, G4Region * aEnvelope)
A constructor.
Parameters
aModelName A name of the fast simulation model.
aEnvelope A region where the model can take over the ordinary tracking.
Definition at line 53 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 53 of file Par02FastSimModelHCal.cc
Par02FastSimModelHCal::Par02FastSimModelHCal (G4String aModelName)
A constructor.
Parameters
aModelName A name of the fast simulation model.
Definition at line 60 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 60 of file Par02FastSimModelHCal.cc
Par02FastSimModelHCal::~Par02FastSimModelHCal ()
Definition at line 66 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 66 of file Par02FastSimModelHCal.cc
Member Function Documentation
void Par02FastSimModelHCal::DoIt (const G4FastTrack & aFastTrack, G4FastStep & aFastStep) virtual
Smears the energy deposit and saves it, together with the position of the deposit, the hadronic calorimeter resolution and efficiency to the Par02PrimaryParticleInformation.
Parameters
aFastTrack A track.
aFastStep A step.
Implements G4VFastSimulationModel.
Definition at line 92 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 92 of file Par02FastSimModelHCal.cc
References kdfinder::abs(), Par02DetectorParametrisation::eHCAL, fCalculateParametrisation, Par02Output::FillHistogram(), fParametrisation, Par02EventInformation::GetDoSmearing(), G4Track::GetDynamicParticle(), G4EventManager::GetEventManager(), G4Track::GetKineticEnergy(), G4Track::GetMomentum(), G4Track::GetParentID(), G4Track::GetPosition(), G4DynamicParticle::GetPrimaryParticle(), G4FastTrack::GetPrimaryTrack(), G4EventManager::GetUserInformation(), Par02Output::Instance(), Par02Smearer::Instance(), G4FastStep::KillPrimaryTrack(), CLHEP::Hep3Vector::mag(), MeV, G4FastStep::ProposePrimaryTrackPathLength(), G4FastStep::ProposeTotalEnergyDeposited(), Par02PrimaryParticleInformation::SetHCalEfficiency(), Par02PrimaryParticleInformation::SetHCalEnergy(), Par02PrimaryParticleInformation::SetHCalPosition(), and Par02PrimaryParticleInformation::SetHCalResolution().
G4bool Par02FastSimModelHCal::IsApplicable (const G4ParticleDefinition & aParticle) virtual
Checks if this model should be applied to this particle type.
Parameters
aParticle A particle definition (type).
Implements G4VFastSimulationModel.
Definition at line 70 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 70 of file Par02FastSimModelHCal.cc
References G4ParticleDefinition::GetQuarkContent().
G4bool Par02FastSimModelHCal::ModelTrigger (const G4FastTrack & aFastTrack) virtual
Checks if the model should be applied, taking into account the kinematics of a track.
Parameters
aFastTrack A track.
Implements G4VFastSimulationModel.
Definition at line 86 of file Par02FastSimModelHCal.cc.
View newest version in sPHENIX GitHub at line 86 of file Par02FastSimModelHCal.cc
Member Data Documentation
Par02DetectorParametrisation* Par02FastSimModelHCal::fCalculateParametrisation private
A pointer to Par02DetectorParametrisation used to get the efficiency and resolution of the detector for a given particle and parametrisation type.
Definition at line 87 of file Par02FastSimModelHCal.hh.
View newest version in sPHENIX GitHub at line 87 of file Par02FastSimModelHCal.hh
Referenced by DoIt().
Par02DetectorParametrisation::Parametrisation Par02FastSimModelHCal::fParametrisation private
A parametrisation type.
Definition at line 90 of file Par02FastSimModelHCal.hh.
View newest version in sPHENIX GitHub at line 90 of file Par02FastSimModelHCal.hh
Referenced by DoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02FastSimModelHCal.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/src/Par02FastSimModelHCal.cc