ECCE @ EIC Software: G4ASCIITree Class Reference
G4ASCIITree Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/Tree/include/G4ASCIITree.hh>
Public Member Functions
G4ASCIITree ()
virtual ~G4ASCIITree ()
G4VSceneHandler * CreateSceneHandler (const G4String &name="")
G4VViewer * CreateViewer (G4VSceneHandler &, const G4String &name="")
G4int GetVerbosity () const
G4String GetOutFileName () const
void SetVerbosity (G4int verbosity)
void SetOutFileName (const G4String &name)
Public Member Functions inherited from G4VTree
G4VTree (const G4String &name, const G4String &nickname, const G4String &description, Functionality f)
virtual ~G4VTree ()
Public Member Functions inherited from G4VGraphicsSystem
G4VGraphicsSystem (const G4String &name, Functionality f)
G4VGraphicsSystem (const G4String &name, const G4String &nickname, Functionality f)
G4VGraphicsSystem (const G4String &name, const G4String &nickname, const G4String &description, Functionality f)
virtual ~G4VGraphicsSystem ()
const G4String & GetName () const
const G4String & GetNickname () const
const std::vector< G4String > & GetNicknames () const
const G4String & GetDescription () const
Functionality GetFunctionality () const
virtual G4bool IsUISessionCompatible () const
void AddNickname (const G4String &nickname)
Protected Attributes
G4int fVerbosity
G4ASCIITreeMessenger * fpMessenger
G4String fOutFileName
Additional Inherited Members
Public Types inherited from G4VGraphicsSystem
enum Functionality {
noFunctionality, nonEuclidian, twoD, twoDStore,
threeD, threeDInteractive, virtualReality, fileWriter
}
Detailed Description
Definition at line 40 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ASCIITree.hh
Constructor & Destructor Documentation
G4ASCIITree::G4ASCIITree ()
Definition at line 37 of file G4ASCIITree.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ASCIITree.cc
References fpMessenger.
G4ASCIITree::~G4ASCIITree () virtual
Definition at line 49 of file G4ASCIITree.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ASCIITree.cc
References fpMessenger.
Member Function Documentation
G4VSceneHandler * G4ASCIITree::CreateSceneHandler (const G4String & name = "") virtual
Implements G4VGraphicsSystem.
Definition at line 53 of file G4ASCIITree.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ASCIITree.cc
G4VViewer * G4ASCIITree::CreateViewer (G4VSceneHandler & scene, const G4String & name = "") virtual
Implements G4VGraphicsSystem.
Definition at line 58 of file G4ASCIITree.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ASCIITree.cc
References G4cout, and G4endl.
G4String G4ASCIITree::GetOutFileName () const inline
Definition at line 47 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ASCIITree.hh
References fOutFileName.
G4int G4ASCIITree::GetVerbosity () const inline
Definition at line 46 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ASCIITree.hh
References fVerbosity.
Referenced by G4ASCIITreeSceneHandler::EndModeling(), G4ASCIITreeSceneHandler::RequestPrimitives(), and G4ASCIITreeSceneHandler::WriteHeader().
void G4ASCIITree::SetOutFileName (const G4String & name) inline
Definition at line 49 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ASCIITree.hh
References fOutFileName.
void G4ASCIITree::SetVerbosity (G4int verbosity) inline
Definition at line 48 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ASCIITree.hh
References fVerbosity.
Member Data Documentation
G4String G4ASCIITree::fOutFileName protected
Definition at line 53 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ASCIITree.hh
Referenced by GetOutFileName(), and SetOutFileName().
G4ASCIITreeMessenger* G4ASCIITree::fpMessenger protected
Definition at line 52 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ASCIITree.hh
Referenced by G4ASCIITree(), and ~G4ASCIITree().
G4int G4ASCIITree::fVerbosity protected
Definition at line 51 of file G4ASCIITree.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ASCIITree.hh
Referenced by GetVerbosity(), and SetVerbosity().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/Tree/include/G4ASCIITree.hh
geant4/tree/geant4-10.6-release/source/visualization/Tree/src/G4ASCIITree.cc