ECCE @ EIC Software: G4PhysicalVolumeStore Class Reference
G4PhysicalVolumeStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4PhysicalVolumeStore.hh>
Public Member Functions
G4VPhysicalVolume * GetVolume (const G4String &name, G4bool verbose=true) const
virtual ~G4PhysicalVolumeStore ()
Static Public Member Functions
static void Register (G4VPhysicalVolume *pSolid)
static void DeRegister (G4VPhysicalVolume *pSolid)
static G4PhysicalVolumeStore * GetInstance ()
static void SetNotifier (G4VStoreNotifier *pNotifier)
static void Clean ()
Protected Member Functions
G4PhysicalVolumeStore ()
Static Private Attributes
static G4PhysicalVolumeStore * fgInstance = nullptr
static G4ThreadLocal
G4VStoreNotifier * fgNotifier = nullptr
static G4ThreadLocal G4bool locked = false
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 58 of file G4PhysicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PhysicalVolumeStore.hh
Constructor & Destructor Documentation
G4PhysicalVolumeStore::~G4PhysicalVolumeStore () virtual
Definition at line 59 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PhysicalVolumeStore.cc
References Clean(), and G4VPhysicalVolume::Clean().
G4PhysicalVolumeStore::G4PhysicalVolumeStore () protected
Definition at line 49 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PhysicalVolumeStore.cc
Member Function Documentation
void G4PhysicalVolumeStore::Clean () static
Definition at line 69 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 69 of file G4PhysicalVolumeStore.cc
References fgNotifier, G4cout, G4endl, GetInstance(), G4GeometryManager::IsGeometryClosed(), locked, G4VNotifier::NotifyDeRegistration(), and pos().
Referenced by PHG4PhenixDetector::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4RunManager::ReinitializeGeometry(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), and ~G4PhysicalVolumeStore().
void G4PhysicalVolumeStore::DeRegister (G4VPhysicalVolume * pSolid) static
Definition at line 135 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 135 of file G4PhysicalVolumeStore.cc
References fgNotifier, GetInstance(), G4VPhysicalVolume::GetMotherLogical(), locked, G4VNotifier::NotifyDeRegistration(), and G4LogicalVolume::RemoveDaughter().
Referenced by HadrontherapyDetectorROGeometry::UpdateROGeometry(), and G4VPhysicalVolume::~G4VPhysicalVolume().
G4PhysicalVolumeStore * G4PhysicalVolumeStore::GetInstance (void) static
Definition at line 180 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 180 of file G4PhysicalVolumeStore.cc
References fgInstance.
Referenced by G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), HadrontherapyDetectorConstruction::CheckOverlaps(), Clean(), G4AdjointPosOnPhysVolGenerator::ComputeTransformationFromPhysVolToWorld(), DMXParticleSource::ConfineSourceToVolume(), G4SPSPosDistribution::ConfineSourceToVolume(), PHG4PhenixDetector::Construct(), GB06ParallelWorldForSlices::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), GB06ParallelWorldForSlices::ConstructSD(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume(), DetectorConstruction::DefineVolumes(), DeRegister(), G4GeometryWorkspace::DestroyWorkspace(), G4GlobalFastSimulationManager::DisplayRegion(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), DicomIntersectVolume::GetPhantomParam(), G4EnergySplitter::GetPhantomParam(), DicomIntersectVolume::GetPhysicalVolumes(), G4GDMLReadStructure::GetPhysvol(), G4tgbGeometryDumper::GetPVChildren(), G4tgbGeometryDumper::GetTopPhysVol(), GetVolume(), G4GeometryWorkspace::InitialisePhysicalVolumes(), CexmcSetup::ReadRightDetectors(), Register(), G4RunManager::ReinitializeGeometry(), SetNotifier(), G4ScoringRealWorld::SetupGeometry(), G4RegionStore::SetWorldVolume(), G4GDMLRead::StripNames(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
G4VPhysicalVolume * G4PhysicalVolumeStore::GetVolume (const G4String & name, G4bool verbose = true) const
Definition at line 158 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 158 of file G4PhysicalVolumeStore.cc
References G4endl, G4Exception(), GetInstance(), JustWarning, and message().
Referenced by GB06ParallelWorldForSlices::Construct(), GB06ParallelWorldForSlices::ConstructSD(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4GDMLReadStructure::GetPhysvol(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
void G4PhysicalVolumeStore::Register (G4VPhysicalVolume * pSolid) static
Definition at line 124 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 124 of file G4PhysicalVolumeStore.cc
References fgNotifier, GetInstance(), and G4VNotifier::NotifyRegistration().
Referenced by G4VPhysicalVolume::G4VPhysicalVolume().
void G4PhysicalVolumeStore::SetNotifier (G4VStoreNotifier * pNotifier) static
Definition at line 114 of file G4PhysicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 114 of file G4PhysicalVolumeStore.cc
References fgNotifier, and GetInstance().
Member Data Documentation
G4PhysicalVolumeStore * G4PhysicalVolumeStore::fgInstance = nullptr static private
Definition at line 88 of file G4PhysicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PhysicalVolumeStore.hh
Referenced by GetInstance().
G4ThreadLocal G4VStoreNotifier * G4PhysicalVolumeStore::fgNotifier = nullptr static private
Definition at line 89 of file G4PhysicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PhysicalVolumeStore.hh
Referenced by Clean(), DeRegister(), Register(), and SetNotifier().
G4ThreadLocal G4bool G4PhysicalVolumeStore::locked = false static private
Definition at line 90 of file G4PhysicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PhysicalVolumeStore.hh
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4PhysicalVolumeStore.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4PhysicalVolumeStore.cc