ECCE @ EIC Software: CexmcSensitiveDetectorMessenger Class Reference
CexmcSensitiveDetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcSensitiveDetectorMessenger.hh>
Public Member Functions
CexmcSensitiveDetectorMessenger (G4VPrimitiveScorer *scorer)
~CexmcSensitiveDetectorMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4VPrimitiveScorer * scorer
G4UIdirectory * detectorPath
G4UIcmdWithAnInteger * setVerboseLevel
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 55 of file CexmcSensitiveDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file CexmcSensitiveDetectorMessenger.hh
Constructor & Destructor Documentation
CexmcSensitiveDetectorMessenger::CexmcSensitiveDetectorMessenger (G4VPrimitiveScorer * scorer) explicit
Definition at line 55 of file CexmcSensitiveDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 55 of file CexmcSensitiveDetectorMessenger.cc
References G4UIcommand::AvailableForStates(), CexmcWeirdException, CexmcMessenger::detectorDirName, detectorPath, G4State_Idle, G4State_PreInit, G4VPrimitiveScorer::GetMultiFunctionalDetector(), G4VPrimitiveScorer::GetName(), G4UImanager::GetUIpointer(), scorer, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), and setVerboseLevel.
CexmcSensitiveDetectorMessenger::~CexmcSensitiveDetectorMessenger ()
Definition at line 88 of file CexmcSensitiveDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 88 of file CexmcSensitiveDetectorMessenger.cc
References detectorPath, and setVerboseLevel.
Member Function Documentation
void CexmcSensitiveDetectorMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 95 of file CexmcSensitiveDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 95 of file CexmcSensitiveDetectorMessenger.cc
References G4UIcmdWithAnInteger::GetNewIntValue(), scorer, setVerboseLevel, and G4VPrimitiveScorer::SetVerboseLevel().
Member Data Documentation
G4UIdirectory* CexmcSensitiveDetectorMessenger::detectorPath private
Definition at line 69 of file CexmcSensitiveDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file CexmcSensitiveDetectorMessenger.hh
Referenced by CexmcSensitiveDetectorMessenger(), and ~CexmcSensitiveDetectorMessenger().
G4VPrimitiveScorer* CexmcSensitiveDetectorMessenger::scorer private
Definition at line 67 of file CexmcSensitiveDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file CexmcSensitiveDetectorMessenger.hh
Referenced by CexmcSensitiveDetectorMessenger(), and SetNewValue().
G4UIcmdWithAnInteger* CexmcSensitiveDetectorMessenger::setVerboseLevel private
Definition at line 71 of file CexmcSensitiveDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file CexmcSensitiveDetectorMessenger.hh
Referenced by CexmcSensitiveDetectorMessenger(), SetNewValue(), and ~CexmcSensitiveDetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcSensitiveDetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcSensitiveDetectorMessenger.cc