ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4FieldManager.cc File Reference
pyG4FieldManager.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4FieldManager.hh"
#include "G4Field.hh"
#include "G4ChordFinder.hh"
#include "G4MagneticField.hh"
#include "G4Track.hh"
Namespaces
namespace pyG4FieldManager
Functions
void export_G4FieldManager ()
Variables
G4ChordFinder *(G4FieldManager::* pyG4FieldManager::f1_GetChordFinder)() = &G4FieldManager::GetChordFinder
const G4ChordFinder
*(G4FieldManager::* pyG4FieldManager::f2_GetChordFinder)() const = &G4FieldManager::GetChordFinder
Function Documentation
void export_G4FieldManager ()
Definition at line 62 of file pyG4FieldManager.cc.
View newest version in sPHENIX GitHub at line 62 of file pyG4FieldManager.cc
References G4FieldManager::ConfigureForTrack(), G4FieldManager::CreateChordFinder(), G4FieldManager::DoesFieldChangeEnergy(), G4FieldManager::DoesFieldExist(), pyG4FieldManager::f1_GetChordFinder, pyG4FieldManager::f2_GetChordFinder, G4FieldManager::GetDeltaIntersection(), G4FieldManager::GetDeltaOneStep(), G4FieldManager::GetDetectorField(), G4FieldManager::GetMaximumEpsilonStep(), G4FieldManager::GetMinimumEpsilonStep(), G4FieldManager::SetAccuraciesWithDeltaOneStep(), G4FieldManager::SetChordFinder(), G4FieldManager::SetDeltaIntersection(), G4FieldManager::SetDeltaOneStep(), G4FieldManager::SetDetectorField(), G4FieldManager::SetFieldChangesEnergy(), G4FieldManager::SetMaximumEpsilonStep(), and G4FieldManager::SetMinimumEpsilonStep().
Referenced by BOOST_PYTHON_MODULE().