ECCE @ EIC Software: G4BaseRNtupleManager Class Reference
G4BaseRNtupleManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4BaseRNtupleManager.hh>
Public Member Functions
G4BaseRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseRNtupleManager ()
G4BaseRNtupleManager (const G4BaseRNtupleManager &rhs)=delete
G4BaseRNtupleManager & operator= (const G4BaseRNtupleManager &rhs)=delete
Public Member Functions inherited from G4VRNtupleManager
G4VRNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VRNtupleManager ()
G4VRNtupleManager (const G4VRNtupleManager &rhs)=delete
G4VRNtupleManager & operator= (const G4VRNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Protected Member Functions
virtual G4bool SetNtupleIColumn (const G4String &columnName, G4int &value) final
virtual G4bool SetNtupleFColumn (const G4String &columnName, G4float &value) final
virtual G4bool SetNtupleDColumn (const G4String &columnName, G4double &value) final
virtual G4bool SetNtupleSColumn (const G4String &columnName, G4String &value) final
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, G4int &value)=0
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, G4float &value)=0
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, G4double &value)=0
virtual G4bool SetNtupleSColumn (G4int ntupleId, const G4String &columnName, G4String &value)=0
virtual G4bool SetNtupleIColumn (const G4String &columnName, std::vector< G4int > &vector) final
virtual G4bool SetNtupleFColumn (const G4String &columnName, std::vector< G4float > &vector) final
virtual G4bool SetNtupleDColumn (const G4String &columnName, std::vector< G4double > &vector) final
virtual G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, std::vector< G4int > &vector)=0
virtual G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, std::vector< G4float > &vector)=0
virtual G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, std::vector< G4double > &vector)=0
virtual G4bool GetNtupleRow () final
virtual G4bool GetNtupleRow (G4int ntupleId)=0
virtual G4int GetNofNtuples () const =0
Private Member Functions
G4int GetCurrentNtupleId () const
Friends
class G4VAnalysisReader
Additional Inherited Members
Protected Attributes inherited from G4BaseAnalysisManager
const G4AnalysisManagerState & fState
G4int fFirstId
G4bool fLockFirstId
Detailed Description
Definition at line 40 of file G4BaseRNtupleManager.hh.
View newest version in sPHENIX GitHub at line 40 of file G4BaseRNtupleManager.hh
Constructor & Destructor Documentation
G4BaseRNtupleManager::G4BaseRNtupleManager (const G4AnalysisManagerState & state) explicit
Definition at line 32 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 32 of file G4BaseRNtupleManager.cc
G4BaseRNtupleManager::~G4BaseRNtupleManager () virtual
Definition at line 38 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4BaseRNtupleManager.cc
G4BaseRNtupleManager::G4BaseRNtupleManager (const G4BaseRNtupleManager & rhs) delete
Member Function Documentation
G4int G4BaseRNtupleManager::GetCurrentNtupleId () const private
Definition at line 46 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 46 of file G4BaseRNtupleManager.cc
References G4BaseAnalysisManager::fFirstId, and GetNofNtuples().
Referenced by SetNtupleDColumn(), SetNtupleFColumn(), SetNtupleIColumn(), and SetNtupleSColumn().
virtual G4int G4BaseRNtupleManager::GetNofNtuples () const protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, and G4TRNtupleManager< tools::hdf5::ntuple >.
Referenced by GetCurrentNtupleId().
G4bool G4BaseRNtupleManager::GetNtupleRow () final protected virtual
Implements G4VRNtupleManager.
Definition at line 100 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 100 of file G4BaseRNtupleManager.cc
References G4BaseAnalysisManager::fFirstId.
virtual G4bool G4BaseRNtupleManager::GetNtupleRow (G4int ntupleId) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, and G4TRNtupleManager< tools::hdf5::ntuple >.
G4BaseRNtupleManager& G4BaseRNtupleManager::operator= (const G4BaseRNtupleManager & rhs) delete
G4bool G4BaseRNtupleManager::SetNtupleDColumn (const G4String & columnName, G4double & value) final protected virtual
Implements G4VRNtupleManager.
Definition at line 65 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 65 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId().
Referenced by SetNtupleDColumn().
virtual G4bool G4BaseRNtupleManager::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, G4double & value) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, and G4TRNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseRNtupleManager::SetNtupleDColumn (const G4String & columnName, std::vector< G4double > & vector) final protected virtual
Implements G4VRNtupleManager.
Definition at line 93 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 93 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId(), and SetNtupleDColumn().
virtual G4bool G4BaseRNtupleManager::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, std::vector< G4double > & vector) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, G4TRNtupleManager< tools::hdf5::ntuple >, and G4XmlRNtupleManager.
G4bool G4BaseRNtupleManager::SetNtupleFColumn (const G4String & columnName, G4float & value) final protected virtual
Implements G4VRNtupleManager.
Definition at line 58 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId().
Referenced by SetNtupleFColumn().
virtual G4bool G4BaseRNtupleManager::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, G4float & value) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, and G4TRNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseRNtupleManager::SetNtupleFColumn (const G4String & columnName, std::vector< G4float > & vector) final protected virtual
Implements G4VRNtupleManager.
Definition at line 86 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 86 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId(), and SetNtupleFColumn().
virtual G4bool G4BaseRNtupleManager::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, std::vector< G4float > & vector) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, G4TRNtupleManager< tools::hdf5::ntuple >, and G4XmlRNtupleManager.
G4bool G4BaseRNtupleManager::SetNtupleIColumn (const G4String & columnName, G4int & value) final protected virtual
Implements G4VRNtupleManager.
Definition at line 52 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 52 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId().
Referenced by SetNtupleIColumn().
virtual G4bool G4BaseRNtupleManager::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, G4int & value) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, and G4TRNtupleManager< tools::hdf5::ntuple >.
G4bool G4BaseRNtupleManager::SetNtupleIColumn (const G4String & columnName, std::vector< G4int > & vector) final protected virtual
Implements G4VRNtupleManager.
Definition at line 79 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId(), and SetNtupleIColumn().
virtual G4bool G4BaseRNtupleManager::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, std::vector< G4int > & vector) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, G4TRNtupleManager< tools::hdf5::ntuple >, and G4XmlRNtupleManager.
G4bool G4BaseRNtupleManager::SetNtupleSColumn (const G4String & columnName, G4String & value) final protected virtual
Implements G4VRNtupleManager.
Definition at line 72 of file G4BaseRNtupleManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4BaseRNtupleManager.cc
References GetCurrentNtupleId().
virtual G4bool G4BaseRNtupleManager::SetNtupleSColumn (G4int ntupleId, const G4String & columnName, G4String & value) protected pure virtual
Implements G4VRNtupleManager.
Implemented in G4TRNtupleManager< TNTUPLE >, G4TRNtupleManager< tools::aida::ntuple >, G4TRNtupleManager< tools::rcsv::ntuple >, G4TRNtupleManager< tools::rroot::ntuple >, and G4TRNtupleManager< tools::hdf5::ntuple >.
Friends And Related Function Documentation
friend class G4VAnalysisReader friend
Definition at line 44 of file G4BaseRNtupleManager.hh.
View newest version in sPHENIX GitHub at line 44 of file G4BaseRNtupleManager.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4BaseRNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4BaseRNtupleManager.cc