ECCE @ EIC Software: G4FTFBinaryPionBuilder Class Reference
G4FTFBinaryPionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBinaryPionBuilder.hh>
Public Member Functions
G4FTFBinaryPionBuilder (G4bool quasiElastic=false)
virtual ~G4FTFBinaryPionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPionBuilder
G4VPionBuilder ()=default
virtual ~G4VPionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
G4double theMax
Detailed Description
Definition at line 57 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4FTFBinaryPionBuilder.hh
Constructor & Destructor Documentation
G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder (G4bool quasiElastic = false)
Definition at line 50 of file G4FTFBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 50 of file G4FTFBinaryPionBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFBinaryPionBuilder::~G4FTFBinaryPionBuilder () virtual
Definition at line 75 of file G4FTFBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 75 of file G4FTFBinaryPionBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4FTFBinaryPionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPionBuilder.
Definition at line 63 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4FTFBinaryPionBuilder.hh
void G4FTFBinaryPionBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 84 of file G4FTFBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 84 of file G4FTFBinaryPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFBinaryPionBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 93 of file G4FTFBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 93 of file G4FTFBinaryPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4FTFBinaryPionBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 68 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4FTFBinaryPionBuilder.hh
References theMax.
virtual void G4FTFBinaryPionBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4FTFBinaryPionBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4FTFBinaryPionBuilder::theCascade private
Definition at line 74 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FTFBinaryPionBuilder.hh
Referenced by G4FTFBinaryPionBuilder().
G4double G4FTFBinaryPionBuilder::theMax private
Definition at line 79 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFBinaryPionBuilder.hh
Referenced by Build(), G4FTFBinaryPionBuilder(), and SetMaxEnergy().
G4double G4FTFBinaryPionBuilder::theMin private
Definition at line 78 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFBinaryPionBuilder.hh
Referenced by Build(), G4FTFBinaryPionBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFBinaryPionBuilder::theModel private
Definition at line 73 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFBinaryPionBuilder.hh
Referenced by Build(), and G4FTFBinaryPionBuilder().
G4QuasiElasticChannel* G4FTFBinaryPionBuilder::theQuasiElastic private
Definition at line 77 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FTFBinaryPionBuilder.hh
Referenced by G4FTFBinaryPionBuilder(), and ~G4FTFBinaryPionBuilder().
G4ExcitedStringDecay* G4FTFBinaryPionBuilder::theStringDecay private
Definition at line 76 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FTFBinaryPionBuilder.hh
Referenced by G4FTFBinaryPionBuilder(), and ~G4FTFBinaryPionBuilder().
G4FTFModel* G4FTFBinaryPionBuilder::theStringModel private
Definition at line 75 of file G4FTFBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FTFBinaryPionBuilder.hh
Referenced by G4FTFBinaryPionBuilder(), and ~G4FTFBinaryPionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFBinaryPionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFBinaryPionBuilder.cc