ECCE @ EIC Software: G4P2Messenger Class Reference
G4P2Messenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4P2Messenger.hh>
Public Member Functions
G4P2Messenger (G4VAnalysisManager *manager)
virtual ~G4P2Messenger ()
virtual void SetNewValue (G4UIcommand *command, G4String value) final
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void CreateP2Cmd ()
void SetP2Cmd ()
Private Attributes
G4VAnalysisManager * fManager
Associated class.
std::unique_ptr
< G4AnalysisMessengerHelper > fHelper
std::unique_ptr< G4UIdirectory > fDirectory
std::unique_ptr< G4UIcommand > fCreateP2Cmd
std::unique_ptr< G4UIcommand > fSetP2Cmd
std::unique_ptr< G4UIcommand > fSetP2XCmd
std::unique_ptr< G4UIcommand > fSetP2YCmd
std::unique_ptr< G4UIcommand > fSetP2ZCmd
std::unique_ptr< G4UIcommand > fSetP2TitleCmd
std::unique_ptr< G4UIcommand > fSetP2XAxisCmd
std::unique_ptr< G4UIcommand > fSetP2YAxisCmd
std::unique_ptr< G4UIcommand > fSetP2ZAxisCmd
std::unique_ptr< G4UIcommand > fSetP2XAxisLogCmd
std::unique_ptr< G4UIcommand > fSetP2YAxisLogCmd
std::unique_ptr< G4UIcommand > fSetP2ZAxisLogCmd
G4int fXId
G4int fYId
G4AnalysisMessengerHelper::BinData fXData
G4AnalysisMessengerHelper::BinData fYData
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 45 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 45 of file G4P2Messenger.hh
Constructor & Destructor Documentation
G4P2Messenger::G4P2Messenger (G4VAnalysisManager * manager) explicit
Definition at line 42 of file G4P2Messenger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4P2Messenger.cc
References CreateP2Cmd(), fDirectory, fHelper, fSetP2TitleCmd, fSetP2XAxisCmd, fSetP2XAxisLogCmd, fSetP2XCmd, fSetP2YAxisCmd, fSetP2YAxisLogCmd, fSetP2YCmd, fSetP2ZAxisCmd, fSetP2ZAxisLogCmd, fSetP2ZCmd, and SetP2Cmd().
G4P2Messenger::~G4P2Messenger () virtual
Definition at line 77 of file G4P2Messenger.cc.
View newest version in sPHENIX GitHub at line 77 of file G4P2Messenger.cc
Member Function Documentation
void G4P2Messenger::CreateP2Cmd () private
Definition at line 85 of file G4P2Messenger.cc.
View newest version in sPHENIX GitHub at line 85 of file G4P2Messenger.cc
References fCreateP2Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4P2Messenger().
void G4P2Messenger::SetNewValue (G4UIcommand * command, G4String value) final virtual
Reimplemented from G4UImessenger.
Definition at line 301 of file G4P2Messenger.cc.
View newest version in sPHENIX GitHub at line 301 of file G4P2Messenger.cc
References G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToInt(), G4VAnalysisManager::CreateP2(), fCreateP2Cmd, fHelper, fManager, G4AnalysisMessengerHelper::BinData::fNbins, G4AnalysisMessengerHelper::BinData::fSbinScheme, fSetP2Cmd, fSetP2TitleCmd, fSetP2XAxisCmd, fSetP2XAxisLogCmd, fSetP2XCmd, fSetP2YAxisCmd, fSetP2YAxisLogCmd, fSetP2YCmd, fSetP2ZAxisCmd, fSetP2ZAxisLogCmd, fSetP2ZCmd, G4AnalysisMessengerHelper::BinData::fSfcn, G4AnalysisMessengerHelper::ValueData::fSfcn, G4AnalysisMessengerHelper::BinData::fSunit, G4AnalysisMessengerHelper::ValueData::fSunit, G4AnalysisMessengerHelper::BinData::fVmax, G4AnalysisMessengerHelper::ValueData::fVmax, G4AnalysisMessengerHelper::BinData::fVmin, G4AnalysisMessengerHelper::ValueData::fVmin, fXData, fXId, fYData, fYId, G4UIcommand::GetParameterEntries(), G4Analysis::GetUnitValue(), Dataset::parameters, G4VAnalysisManager::SetP2(), G4VAnalysisManager::SetP2Title(), G4VAnalysisManager::SetP2XAxisIsLog(), G4VAnalysisManager::SetP2XAxisTitle(), G4VAnalysisManager::SetP2YAxisIsLog(), G4VAnalysisManager::SetP2YAxisTitle(), G4VAnalysisManager::SetP2ZAxisIsLog(), G4VAnalysisManager::SetP2ZAxisTitle(), title(), G4Analysis::Tokenize(), and xaxis.
void G4P2Messenger::SetP2Cmd () private
Definition at line 199 of file G4P2Messenger.cc.
View newest version in sPHENIX GitHub at line 199 of file G4P2Messenger.cc
References fSetP2Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4P2Messenger().
Member Data Documentation
std::unique_ptr<G4UIcommand> G4P2Messenger::fCreateP2Cmd private
Definition at line 62 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4P2Messenger.hh
Referenced by CreateP2Cmd(), and SetNewValue().
std::unique_ptr<G4UIdirectory> G4P2Messenger::fDirectory private
Definition at line 60 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4P2Messenger.hh
Referenced by G4P2Messenger().
std::unique_ptr<G4AnalysisMessengerHelper> G4P2Messenger::fHelper private
Definition at line 59 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
G4VAnalysisManager* G4P2Messenger::fManager private
Associated class.
Definition at line 58 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 58 of file G4P2Messenger.hh
Referenced by SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2Cmd private
Definition at line 63 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4P2Messenger.hh
Referenced by SetNewValue(), and SetP2Cmd().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2TitleCmd private
Definition at line 67 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2XAxisCmd private
Definition at line 68 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2XAxisLogCmd private
Definition at line 71 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2XCmd private
Definition at line 64 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2YAxisCmd private
Definition at line 69 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2YAxisLogCmd private
Definition at line 72 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2YCmd private
Definition at line 65 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2ZAxisCmd private
Definition at line 70 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2ZAxisLogCmd private
Definition at line 73 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P2Messenger::fSetP2ZCmd private
Definition at line 66 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4P2Messenger.hh
Referenced by G4P2Messenger(), and SetNewValue().
G4AnalysisMessengerHelper::BinData G4P2Messenger::fXData private
Definition at line 77 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4P2Messenger.hh
Referenced by SetNewValue().
G4int G4P2Messenger::fXId private
Definition at line 75 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4P2Messenger.hh
Referenced by SetNewValue().
G4AnalysisMessengerHelper::BinData G4P2Messenger::fYData private
Definition at line 78 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4P2Messenger.hh
Referenced by SetNewValue().
G4int G4P2Messenger::fYId private
Definition at line 76 of file G4P2Messenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4P2Messenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4P2Messenger.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4P2Messenger.cc