ECCE @ EIC Software: G4tgrElementSimple Class Reference
G4tgrElementSimple Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrElementSimple.hh>
Public Member Functions
G4tgrElementSimple ()
~G4tgrElementSimple ()
G4tgrElementSimple (const std::vector< G4String > &wl)
G4double GetZ () const
G4double GetA () const
Public Member Functions inherited from G4tgrElement
G4tgrElement ()
virtual ~G4tgrElement ()
const G4String & GetName () const
const G4String & GetSymbol () const
const G4String & GetType () const
Private Attributes
G4double theZ
G4double theA
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrElementSimple &obj)
Additional Inherited Members
Protected Attributes inherited from G4tgrElement
G4String theName
G4String theSymbol
G4String theType
Detailed Description
Definition at line 48 of file G4tgrElementSimple.hh.
View newest version in sPHENIX GitHub at line 48 of file G4tgrElementSimple.hh
Constructor & Destructor Documentation
G4tgrElementSimple::G4tgrElementSimple ()
Definition at line 42 of file G4tgrElementSimple.cc.
View newest version in sPHENIX GitHub at line 42 of file G4tgrElementSimple.cc
G4tgrElementSimple::~G4tgrElementSimple ()
Definition at line 49 of file G4tgrElementSimple.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgrElementSimple.cc
G4tgrElementSimple::G4tgrElementSimple (const std::vector< G4String > & wl)
Definition at line 55 of file G4tgrElementSimple.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgrElementSimple.cc
References G4tgrUtils::CheckWLsize(), Acts::UnitConstants::g, G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), mole, theA, G4tgrElement::theName, G4tgrElement::theSymbol, G4tgrElement::theType, theZ, and WLSIZE_EQ.
Member Function Documentation
G4double G4tgrElementSimple::GetA () const inline
Definition at line 60 of file G4tgrElementSimple.hh.
View newest version in sPHENIX GitHub at line 60 of file G4tgrElementSimple.hh
References theA.
Referenced by G4tgbElement::BuildG4ElementSimple().
G4double G4tgrElementSimple::GetZ () const inline
Definition at line 59 of file G4tgrElementSimple.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrElementSimple.hh
References theZ.
Referenced by G4tgbElement::BuildG4ElementSimple().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrElementSimple & obj) friend
Definition at line 77 of file G4tgrElementSimple.cc.
View newest version in sPHENIX GitHub at line 77 of file G4tgrElementSimple.cc
Member Data Documentation
G4double G4tgrElementSimple::theA private
Definition at line 67 of file G4tgrElementSimple.hh.
View newest version in sPHENIX GitHub at line 67 of file G4tgrElementSimple.hh
Referenced by G4tgrElementSimple(), GetA(), and operator<<().
G4double G4tgrElementSimple::theZ private
Definition at line 66 of file G4tgrElementSimple.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgrElementSimple.hh
Referenced by G4tgrElementSimple(), GetZ(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrElementSimple.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrElementSimple.cc