ECCE @ EIC Software: G4WilsonAblationModel Class Reference
G4WilsonAblationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/ablation/include/G4WilsonAblationModel.hh>
Public Types
typedef std::vector
< G4ParticleDefinition * > VectorOfFragmentTypes
Public Member Functions
G4WilsonAblationModel ()
virtual ~G4WilsonAblationModel ()
G4FragmentVector * BreakItUp (const G4Fragment &theNucleus)
void SetProduceSecondaries (G4bool)
G4bool GetProduceSecondaries ()
void SetVerboseLevel (G4int)
G4int GetVerboseLevel ()
Public Member Functions inherited from G4VEvaporation
G4VEvaporation ()
virtual ~G4VEvaporation ()
virtual void BreakFragment (G4FragmentVector *, G4Fragment *theNucleus)
virtual void InitialiseChannels ()
virtual void SetPhotonEvaporation (G4VEvaporationChannel *ptr)
void SetFermiBreakUp (G4VFermiBreakUp *ptr)
G4VFermiBreakUp * GetFermiBreakUp () const
G4VEvaporationChannel * GetPhotonEvaporation ()
G4VEvaporationChannel * GetFissionChannel ()
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
size_t GetNumberOfChannels () const
Private Member Functions
void SelectSecondariesByEvaporation (G4Fragment *)
void SelectSecondariesByDefault (G4ThreeVector)
void PrintWelcomeMessage ()
Private Attributes
G4bool produceSecondaries
G4int verboseLevel
G4double B
G4int nFragTypes
G4ParticleDefinition * fragType [6]
G4FragmentVector * fragmentVector
VectorOfFragmentTypes evapType
G4double fSig [200]
Additional Inherited Members
Protected Member Functions inherited from G4VEvaporation
void CleanChannels ()
Protected Attributes inherited from G4VEvaporation
G4VEvaporationChannel * thePhotonEvaporation
G4VFermiBreakUp * theFBU
G4int OPTxs
G4bool useSICB
std::vector
< G4VEvaporationChannel * > * theChannels
G4VEvaporationFactory * theChannelFactory
Detailed Description
Definition at line 84 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4WilsonAblationModel.hh
Member Typedef Documentation
typedef std::vector<G4ParticleDefinition*> G4WilsonAblationModel::VectorOfFragmentTypes
Definition at line 90 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4WilsonAblationModel.hh
Constructor & Destructor Documentation
G4WilsonAblationModel::G4WilsonAblationModel ()
Definition at line 116 of file G4WilsonAblationModel.cc.
View newest version in sPHENIX GitHub at line 116 of file G4WilsonAblationModel.cc
References G4Alpha::Alpha(), B, G4Deuteron::Deuteron(), fragmentVector, fragType, fSig, G4VEvaporationFactory::GetChannel(), G4He3::He3(), MeV, G4Neutron::Neutron(), nFragTypes, G4VEvaporation::OPTxs, PrintWelcomeMessage(), produceSecondaries, G4Proton::Proton(), G4VEvaporation::theChannelFactory, G4VEvaporation::theChannels, G4Triton::Triton(), G4VEvaporation::useSICB, and verboseLevel.
G4WilsonAblationModel::~G4WilsonAblationModel () virtual
Definition at line 171 of file G4WilsonAblationModel.cc.
View newest version in sPHENIX GitHub at line 171 of file G4WilsonAblationModel.cc
Member Function Documentation
G4FragmentVector * G4WilsonAblationModel::BreakItUp (const G4Fragment & theNucleus)
Definition at line 177 of file G4WilsonAblationModel.cc.
View newest version in sPHENIX GitHub at line 177 of file G4WilsonAblationModel.cc
References A(), kdfinder::abs(), B(), CLHEP::HepLorentzVector::boost(), e, CLHEP::HepLorentzVector::e(), eV, CLHEP::HepLorentzVector::findBoostToCM(), G4cout, G4endl, G4Exp(), G4UniformRand, G4Fragment::GetA_asInt(), G4ParticleDefinition::GetBaryonNumber(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4Pow::GetInstance(), G4ParticleTable::GetIonTable(), G4Fragment::GetMomentum(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Fragment::GetZ_asInt(), mass, max, MeV, min, n, n1, G4Neutron::Neutron(), G4Pow::powA(), G4Pow::powZ(), G4Proton::Proton(), Acts::IntegrationTest::R, CLHEP::HepLorentzVector::setE(), sum, and Z.
G4bool G4WilsonAblationModel::GetProduceSecondaries () inline
Definition at line 120 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4WilsonAblationModel.hh
References produceSecondaries.
G4int G4WilsonAblationModel::GetVerboseLevel () inline
Definition at line 128 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4WilsonAblationModel.hh
References verboseLevel.
void G4WilsonAblationModel::PrintWelcomeMessage () private
Definition at line 587 of file G4WilsonAblationModel.cc.
View newest version in sPHENIX GitHub at line 587 of file G4WilsonAblationModel.cc
References G4cout, and G4endl.
Referenced by G4WilsonAblationModel().
void G4WilsonAblationModel::SelectSecondariesByDefault (G4ThreeVector boost) private
Definition at line 559 of file G4WilsonAblationModel.cc.
View newest version in sPHENIX GitHub at line 559 of file G4WilsonAblationModel.cc
References A(), CLHEP::HepLorentzVector::boost(), e, eV, evapType, fragmentVector, G4UniformRand, G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, phi, rad, twopi, and Z.
void G4WilsonAblationModel::SelectSecondariesByEvaporation (G4Fragment * intermediateNucleus) private
Definition at line 435 of file G4WilsonAblationModel.cc.
View newest version in sPHENIX GitHub at line 435 of file G4WilsonAblationModel.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4UniformRand, G4He3::He3(), G4Neutron::Neutron(), G4Proton::Proton(), and G4Triton::Triton().
void G4WilsonAblationModel::SetProduceSecondaries (G4bool produceSecondaries1) inline
Definition at line 116 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4WilsonAblationModel.hh
void G4WilsonAblationModel::SetVerboseLevel (G4int verboseLevel1) inline
Definition at line 124 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 124 of file G4WilsonAblationModel.hh
References verboseLevel.
Referenced by G4WilsonAbrasionModel::G4WilsonAbrasionModel(), G4WilsonAbrasionModel::SetUseAblation(), and G4WilsonAbrasionModel::SetVerboseLevel().
Member Data Documentation
G4double G4WilsonAblationModel::B private
Definition at line 106 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel().
VectorOfFragmentTypes G4WilsonAblationModel::evapType private
Definition at line 110 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4WilsonAblationModel.hh
Referenced by SelectSecondariesByDefault().
G4FragmentVector* G4WilsonAblationModel::fragmentVector private
Definition at line 109 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel(), and SelectSecondariesByDefault().
G4ParticleDefinition* G4WilsonAblationModel::fragType[6] private
Definition at line 108 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel().
G4double G4WilsonAblationModel::fSig[200] private
Definition at line 111 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel().
G4int G4WilsonAblationModel::nFragTypes private
Definition at line 107 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel().
G4bool G4WilsonAblationModel::produceSecondaries private
Definition at line 104 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel(), and GetProduceSecondaries().
G4int G4WilsonAblationModel::verboseLevel private
Definition at line 105 of file G4WilsonAblationModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4WilsonAblationModel.hh
Referenced by G4WilsonAblationModel(), GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/ablation/include/G4WilsonAblationModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/ablation/src/G4WilsonAblationModel.cc