ECCE @ EIC Software: ExUCNDetectorConstruction Class Reference
ExUCNDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/ucn/include/ExUCNDetectorConstruction.hh>
Public Member Functions
ExUCNDetectorConstruction ()
virtual ~ExUCNDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
Private Attributes
G4Material * fVacuum
G4Material * fGuideMaterial
Static Private Attributes
static G4ThreadLocal
G4UniformGravityField * fField = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 46 of file ExUCNDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 46 of file ExUCNDetectorConstruction.hh
Constructor & Destructor Documentation
ExUCNDetectorConstruction::ExUCNDetectorConstruction ()
Definition at line 73 of file ExUCNDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 73 of file ExUCNDetectorConstruction.cc
References DefineMaterials().
ExUCNDetectorConstruction::~ExUCNDetectorConstruction () virtual
Definition at line 82 of file ExUCNDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 82 of file ExUCNDetectorConstruction.cc
References fField.
Member Function Documentation
G4VPhysicalVolume * ExUCNDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 127 of file ExUCNDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 127 of file ExUCNDetectorConstruction.cc
References DBL_MAX, fGuideMaterial, fVacuum, G4VisAttributes::GetInvisible(), m, mm, G4VisAttributes::SetForceSolid(), G4VisAttributes::SetForceWireframe(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and twopi.
void ExUCNDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 212 of file ExUCNDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 212 of file ExUCNDetectorConstruction.cc
References fField, G4TransportationManager::GetFieldManager(), G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetTransportationManager(), mm, G4FieldManager::SetAccuraciesWithDeltaOneStep(), G4FieldManager::SetChordFinder(), G4ChordFinder::SetDeltaChord(), G4FieldManager::SetDeltaIntersection(), G4FieldManager::SetDetectorField(), G4PropagatorInField::SetMaximumEpsilonStep(), G4PropagatorInField::SetMinimumEpsilonStep(), and propagation_timing::stepper.
void ExUCNDetectorConstruction::DefineMaterials () private
Definition at line 89 of file ExUCNDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 89 of file ExUCNDetectorConstruction.cc
References G4MaterialPropertiesTable::AddConstProperty(), degree, e, eV, fGuideMaterial, G4NistManager::FindOrBuildMaterial(), fVacuum, G4cout, G4endl, G4Material::GetMaterialTable(), G4NistManager::Instance(), nm, G4Material::SetMaterialPropertiesTable(), and G4UCNMaterialPropertiesTable::SetMicroRoughnessParameters().
Referenced by ExUCNDetectorConstruction().
Member Data Documentation
G4ThreadLocal G4UniformGravityField * ExUCNDetectorConstruction::fField = 0 static private
Definition at line 63 of file ExUCNDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 63 of file ExUCNDetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExUCNDetectorConstruction().
G4Material* ExUCNDetectorConstruction::fGuideMaterial private
Definition at line 61 of file ExUCNDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 61 of file ExUCNDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4Material* ExUCNDetectorConstruction::fVacuum private
Definition at line 60 of file ExUCNDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file ExUCNDetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/ucn/include/ExUCNDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/ucn/src/ExUCNDetectorConstruction.cc