ECCE @ EIC Software: G4KM_OpticalEqRhs Class Reference
G4KM_OpticalEqRhs Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4KM_OpticalEqRhs.hh>
Public Member Functions
G4KM_OpticalEqRhs (G4KM_DummyField *field, G4V3DNucleus *nucleus)
~G4KM_OpticalEqRhs ()
virtual void EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const
virtual void SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double MassXc2)
void SetFactor (G4double mass, G4double opticalParameter)
Public Member Functions inherited from G4Mag_EqRhs
G4Mag_EqRhs (G4MagneticField *magField)
virtual ~G4Mag_EqRhs ()
G4double FCof () const
Public Member Functions inherited from G4EquationOfMotion
G4EquationOfMotion (G4Field *Field)
virtual ~G4EquationOfMotion ()
void RightHandSide (const G4double y[], G4double dydx[]) const
void EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const
void GetFieldValue (const G4double Point[4], G4double Field[]) const
const G4Field * GetFieldObj () const
G4Field * GetFieldObj ()
void SetFieldObj (G4Field *pField)
Private Attributes
G4V3DNucleus * theNucleus
G4double theFactor
G4double theMass
Detailed Description
Definition at line 49 of file G4KM_OpticalEqRhs.hh.
View newest version in sPHENIX GitHub at line 49 of file G4KM_OpticalEqRhs.hh
Constructor & Destructor Documentation
G4KM_OpticalEqRhs::G4KM_OpticalEqRhs (G4KM_DummyField * field, G4V3DNucleus * nucleus)
Definition at line 45 of file G4KM_OpticalEqRhs.cc.
View newest version in sPHENIX GitHub at line 45 of file G4KM_OpticalEqRhs.cc
References theFactor, and theMass.
G4KM_OpticalEqRhs::~G4KM_OpticalEqRhs () inline
Definition at line 69 of file G4KM_OpticalEqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4KM_OpticalEqRhs.hh
Member Function Documentation
void G4KM_OpticalEqRhs::EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const virtual
Implements G4Mag_EqRhs.
Definition at line 71 of file G4KM_OpticalEqRhs.cc.
View newest version in sPHENIX GitHub at line 71 of file G4KM_OpticalEqRhs.cc
References source.hepunit::c_light, deriv(), e, G4VNuclearDensity::GetDeriv(), G4V3DNucleus::GetNuclearDensity(), pos(), theFactor, theMass, and theNucleus.
void G4KM_OpticalEqRhs::SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double MassXc2) virtual
Reimplemented from G4Mag_EqRhs.
Definition at line 94 of file G4KM_OpticalEqRhs.cc.
View newest version in sPHENIX GitHub at line 94 of file G4KM_OpticalEqRhs.cc
void G4KM_OpticalEqRhs::SetFactor (G4double mass, G4double opticalParameter)
Definition at line 54 of file G4KM_OpticalEqRhs.cc.
View newest version in sPHENIX GitHub at line 54 of file G4KM_OpticalEqRhs.cc
References A(), G4InuclSpecialFunctions::bindingEnergy(), G4lrint(), G4NucleiProperties::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4V3DNucleus::GetMassNumber(), source.hepunit::hbarc, mass, source.hepunit::neutron_mass_c2, pi, source.hepunit::proton_mass_c2, theFactor, theMass, theNucleus, and Z.
Referenced by G4RKPropagation::Init().
Member Data Documentation
G4double G4KM_OpticalEqRhs::theFactor private
Definition at line 65 of file G4KM_OpticalEqRhs.hh.
View newest version in sPHENIX GitHub at line 65 of file G4KM_OpticalEqRhs.hh
Referenced by EvaluateRhsGivenB(), G4KM_OpticalEqRhs(), and SetFactor().
G4double G4KM_OpticalEqRhs::theMass private
Definition at line 66 of file G4KM_OpticalEqRhs.hh.
View newest version in sPHENIX GitHub at line 66 of file G4KM_OpticalEqRhs.hh
Referenced by EvaluateRhsGivenB(), G4KM_OpticalEqRhs(), and SetFactor().
G4V3DNucleus* G4KM_OpticalEqRhs::theNucleus private
Definition at line 64 of file G4KM_OpticalEqRhs.hh.
View newest version in sPHENIX GitHub at line 64 of file G4KM_OpticalEqRhs.hh
Referenced by EvaluateRhsGivenB(), and SetFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4KM_OpticalEqRhs.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4KM_OpticalEqRhs.cc