ECCE @ EIC Software: acts/blob/master/Tests/UnitTests/Core/Material/InteractionsTests.cpp File Reference
InteractionsTests.cpp File Reference
#include <boost/test/data/test_case.hpp>
#include <boost/test/unit_test.hpp>
#include "Acts/Material/Interactions.hpp"
#include "Acts/Tests/CommonHelpers/PredefinedMaterials.hpp"
#include "Acts/Utilities/PdgParticle.hpp"
#include "Acts/Utilities/Units.hpp"
Functions
BOOST_DATA_TEST_CASE (energy_loss_consistency, thickness *particle *momentum, x, i, m, q, p)
BOOST_DATA_TEST_CASE (multiple_scattering_consistency, thickness *particle *momentum, x, i, m, q, p)
BOOST_DATA_TEST_CASE (vacuum, thickness *particle *momentum, x, i, m, q, p)
Variables
static constexpr Acts::Material material = Acts::Test::makeSilicon()
static double valuesThickness [] = {200_um, 1_mm}
static auto thickness = data::make(valuesThickness)
static int pdg []
static double mass [] = {511_keV, 105.7_MeV, 139.6_MeV, 938.3_MeV}
static double charge [] = {-1_e, -1_e, 1_e, 1_e}
static auto particle = data::make(pdg) ^ data::make(mass) ^ data::make(charge)
static auto momentum_low = data::xrange(100_MeV, 10_GeV, 100_MeV)
static auto momentum_med = data::xrange(10_GeV, 100_GeV, 10_GeV)
static auto momentum_high = data::xrange(100_GeV, 10_TeV, 100_GeV)
static auto momentum = momentum_low + momentum_med + momentum_high
Function Documentation
BOOST_DATA_TEST_CASE (energy_loss_consistency , thickness *particle * momentum, x , i , m , q , p)
Definition at line 41 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 41 of file InteractionsTests.cpp
References Acts::computeEnergyLossBethe(), Acts::computeEnergyLossLandau(), Acts::computeEnergyLossLandauSigma(), Acts::computeEnergyLossLandauSigmaQOverP(), Acts::computeEnergyLossMean(), Acts::computeEnergyLossMode(), Acts::computeEnergyLossRadiative(), and material.
BOOST_DATA_TEST_CASE (multiple_scattering_consistency , thickness *particle * momentum, x , i , m , q , p)
Definition at line 70 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 70 of file InteractionsTests.cpp
References Acts::computeMultipleScatteringTheta0(), m, material, and x.
BOOST_DATA_TEST_CASE (vacuum , thickness *particle * momentum, x , i , m , q , p)
Definition at line 94 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 94 of file InteractionsTests.cpp
References Acts::computeEnergyLossBethe(), Acts::computeEnergyLossLandau(), Acts::computeEnergyLossLandauSigma(), Acts::computeEnergyLossLandauSigmaQOverP(), Acts::computeEnergyLossMean(), Acts::computeEnergyLossMode(), Acts::computeEnergyLossRadiative(), Acts::computeMultipleScatteringTheta0(), m, and x.
Variable Documentation
double charge[] = {-1_e, -1_e, 1_e, 1_e} static
Definition at line 30 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 30 of file InteractionsTests.cpp
Referenced by G4TrajectoryChargeFilter::Add(), G4HadronBuilder::Barion(), RunAction::BeginOfRunAction(), SteppingAction::BirksAttenuation(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::detail::boundState(), Acts::AtlasStepper< ConstantBField >::boundState(), FW::HepMC3Particle::charge(), PHActsSiliconSeeding::circleFitSeed(), StackingAction::ClassifyNewTrack(), Acts::Test::consistencyCheck(), Acts::IntegrationTest::constant_field_propagation(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4StepLimiterPhysics::ConstructProcess(), G4TrajectoryChargeFilter::ConvertToCharge(), G4TrajectoryDrawByCharge::ConvertToCharge(), Acts::IntegrationTest::covariance_bound(), Acts::IntegrationTest::covariance_curvilinear(), G4IonTable::CreateIon(), PHActsSiliconSeeding::createSvtxTrack(), Acts::detail::curvilinearState(), Acts::AtlasStepper< ConstantBField >::curvilinearState(), G4TrajectoryDrawByCharge::Draw(), G4ionEffectiveCharge::EffectiveCharge(), G4ionEffectiveCharge::EffectiveChargeSquareRatio(), G4hImpactIonisation::ElectronicLossFluctuation(), G4IonDEDXScalingICRU73::EquilibriumCharge(), G4TrajectoryChargeFilter::Evaluate(), PHTpcEventExporter::exportEvent(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), SvtxEvaluator::fillOutputNtuples(), G4Absorber::FindAbsorbers(), G4Absorber::FindProducts(), Acts::IntegrationTest::foward_backward(), G4ChargeState::G4ChargeState(), G4MolecularConfiguration::G4MolecularConfiguration(), G4MoleculeDefinition::G4MoleculeDefinition(), G4AtomicFormFactor::Get(), PHGenFit::Track::get_charge(), PHGenFit2::Track::get_charge(), PHTpcTrackFollower::get_projected_coordinate(), G4ExcitedBaryonConstructor::GetCharge(), G4ExcitedMesonConstructor::GetCharge(), PHActsSiliconSeeding::getCharge(), G4PiNuclearCrossSection::GetElementCrossSection(), G4AtomicFormFactor::GetIndex(), G4VXTRenergyLoss::GetMeanFreePath(), G4CollisionOutput::getTotalCharge(), gustep(), G4MolecularConfiguration::G4MolecularConfigurationManager::Insert(), kspart(), kstpar(), G4MoleculeDefinition::Load(), PHActsTrkFitter::loopTracks(), main(), PHActsSiliconSeeding::makeSvtxTracks(), G4HadronBuilder::Meson(), G4TextPPRetriever::ModifyPropertyTable(), FW::HepMC3Particle::particle(), PG4gspart(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), PHTpcTracker::Process(), B5DriftChamberSD::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorMSC(), Acts::Test::runTest(), G4TrajectoryDrawByCharge::Set(), Acts::ChargedPolicy::setCharge(), G4ChargeState::SetCharge(), G4ChargeState::SetChargeSpinMoments(), G4ChargeState::SetMagneticCharge(), Acts::AtlasStepper< ConstantBField >::step(), G4IonYangFluctuationModel::TheValue(), G4hIonEffChargeSquare::TheValue(), Acts::IntegrationTest::to_cylinder(), Acts::IntegrationTest::to_surface(), Acts::AtlasStepper< ConstantBField >::update(), and PHG4ZDCSteppingAction::UserSteppingAction().
double mass[] = {511_keV, 105.7_MeV, 139.6_MeV, 938.3_MeV} static
Definition at line 29 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 29 of file InteractionsTests.cpp
Referenced by G4NeutronRadCapture::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4LFission::Atomas(), G4NucleiProperties::AtomicMass(), G4DecayProducts::Boost(), G4Nucleon::Boost(), G4InuclEvaporation::BreakItUp(), G4ExcitationHandler::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), GPUTPCTrackParam::CalculateFitParameters(), G4AntiNuclElastic::CalculateParticleBeta(), G4NuclNuclDiffuseElastic::CalculateParticleBeta(), G4DiffuseElastic::CalculateParticleBeta(), G4Track::CalculateVelocity(), G4INCL::Nucleus::computeCenterOfMass(), CCalMaterial::computeDensity(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4MuonicAtomHelper::ConstructMuonicAtom(), G4IonTable::CreateIon(), G4BinaryCascade::DecayVoidNucleus(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), G4DamagedDeoxyribose::Definition(), G4DamagedAdenine::Definition(), G4Electron_aq::Definition(), G4H2::Definition(), G4H2O::Definition(), G4H2O2::Definition(), G4H3O::Definition(), G4OH::Definition(), G4Hydrogen::Definition(), G4DamagedGuanine::Definition(), G4DamagedThymine::Definition(), G4DamagedCytosine::Definition(), G4Deoxyribose::Definition(), G4Phosphate::Definition(), G4Adenine::Definition(), G4Guanine::Definition(), G4Thymine::Definition(), G4Cytosine::Definition(), G4ModifiedHistone::Definition(), G4Histone::Definition(), G4GEMProbability::Dump(), G4VDecayChannel::DynamicalMass(), G4ionEffectiveCharge::EffectiveCharge(), G4ASCIITreeSceneHandler::EndModeling(), Run::EndOfRun(), HistoManager::EndOfRun(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), G4IonDEDXScalingICRU73::EquilibriumCharge(), G4KineticTrack::EvaluateCMMomentum(), G4SPSEneDistribution::ExpInterpolation(), G4INCL::EventInfo::fillInverseKinematics(), Run::FillPerEvent(), G4NucleiModel::fillPotentials(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), ActsFatras::findMass(), G4VEmissionProbability::FindRecoilExcitation(), G4IntraNucleiCascader::finishCascade(), G4GIDI_targetMass(), G4GIDI_Z_AMass(), G4MonopolePhysicsMessenger::G4MonopolePhysicsMessenger(), G4INCL::KinematicsUtils::gammaFromKineticEnergy(), CexmcReimplementedGenbod::Generate(), G4IntraNucleiCascader::generateCascade(), G4BigBanger::generateMomentumModules(), G4RPGReaction::GenerateNBodyEvent(), G4RPGReaction::GenerateNBodyEventT(), G4NucleiModel::generateNucleonMomentum(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), MedicalBeam::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4SPSEneDistribution::GenUserHistEnergies(), G4NistElementBuilder::GetAtomicMass(), G4ParticleHPNBodyPhaseSpace::GetEmax(), G4NucleiModel::getFermiKinetic(), G4INCL::Particle::getInvariantMass(), G4BinaryCascade::GetIonMass(), G4NistElementBuilder::GetIsotopeMass(), G4INCL::KinematicsUtils::getLocalEnergy(), G4GIDI_target::getMass(), G4VarNtp::getMass(), G4VXTRenergyLoss::GetMeanFreePath(), getnewmass(), G4QMDNucleus::GetNuclearMass(), G4NucleiProperties::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), G4InuclNuclei::getNucleiMass(), G4IonTable::GetNucleusMass(), G4UAtomicDeexcitation::GetShellIonisationCrossSectionPerAtom(), G4HadronNucleonXsc::HadronNucleonXscVU(), HadrontherapyMatrix::HadrontherapyMatrix(), init(), G4RKPropagation::Init(), G4GIDI_target::init(), G4CoulombScattering::InitialiseProcess(), initpythia(), G4KineticTrack::IntegrandFunction1(), G4KineticTrack::IntegrandFunction2(), G4KineticTrack::IntegrandFunction3(), G4KineticTrack::IntegrandFunction4(), G4BinaryLightIonReaction::Interact(), G4DecayProducts::IsChecked(), jewel(), G4eeToHadronsMultiModel::LabToCM(), G4SPSEneDistribution::LinearInterpolation(), G4MoleculeDefinition::Load(), G4SPSEneDistribution::LogInterpolation(), main(), G4CascadeDeexciteBase::makeFragment(), QAG4SimulationKFParticle::makeHepLV(), G4InuclNuclei::makeNuclearFragment(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_particleMass_AMU(), MCGIDI_target_heated_parseParticle(), medinit(), genericRICH::minP(), G4mplIonisation::MinPrimaryEnergy(), G4CoulombScattering::MinPrimaryEnergy(), G4TextPPRetriever::ModifyPropertyTable(), G4NucleiProperties::NuclearMass(), PoP_getMassInUnitOf(), PoP_makeParticle(), PoPs_getBDFLS_mass(), PoPs_getMassInUnitOf_atIndex(), PoPs_particleLoadInfo(), PoPs_particleMass_AMU(), G4VLongitudinalStringDecay::PossibleHadronMass(), G4VXTRenergyLoss::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), printLine(), PHHepMCParticleSelectorDecayProductChain::process_event(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4ErrorFreeTrajState::PropagateErrorIoni(), pypdfu(), pyresd(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4INCLXXInterface::remnant4MomentumScaling(), KFParticle_particleList::returnPDGMass(), G4DNABornAngle::SampleDirectionForShell(), G4DNARuddAngle::SampleDirectionForShell(), G4ElasticHadrNucleusHE::SampleInvariantT(), G4eeToHadronsModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), HistoManager::ScoreNewTrack(), G4WilsonAblationModel::SelectSecondariesByDefault(), G4KM_OpticalEqRhs::SetFactor(), G4INCL::Particle::setMass(), CexmcReimplementedGenbod::SetMaxWeight(), G4InuclParticle::setMomentum(), G4DynamicParticle::SetMomentum(), G4MonopolePhysics::SetMonopoleMass(), G4MonopolePhysicsMessenger::SetNewValue(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleMomentum(), G4RayShooter::Shoot(), G4LightTargetCollider::SingleNucleonScattering(), G4SPSEneDistribution::SplineInterpolation(), G4IonYangFluctuationModel::TheValue(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4ParticleChange::UpdateStepForAlongStep().
constexpr Acts::Material material = Acts::Test::makeSilicon() static
Definition at line 21 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 21 of file InteractionsTests.cpp
Referenced by BOOST_DATA_TEST_CASE().
auto momentum = momentum_low + momentum_med + momentum_high static
Definition at line 36 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 36 of file InteractionsTests.cpp
Referenced by TrackEvaluation::add_truth_information(), AddFlowToParent(), PHTpcResiduals::addTrackState(), XrayFluoAnalysisManager::analyseStepping(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4DecayProducts::Boost(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::detail::boundState(), G4InuclEvaporation::BreakItUp(), G4NeutronElectronElModel::CalculateAm(), G4RPGInelastic::CalculateMomenta(), Acts::computeEnergyLossRadiative(), Acts::Test::consistencyCheck(), G4INCL::CoulombNonRelativistic::coulombDeviation(), G4Pythia6Decayer::CreateDynamicParticle(), Acts::detail::curvilinearState(), G4KineticTrack::Decay(), Acts::deriveEnergyLossRadiativeQOverP(), G4INCL::CoulombNonRelativistic::distortOut(), G4GEMChannel::EmittedFragment(), example(), G4INCL::RecombinationChannel::fillFinalState(), ActsEvaluator::fillProtoTrack(), ActsTransformations::fillSvtxTrackStates(), flowAfterburner(), G4INCL::PhaseSpaceRauboldLynch::generateEvent(), G4FragmentingString::Get4Momentum(), G4ExcitedString::Get4Momentum(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4ChipsComponentXS::GetElasticElementCrossSection(), G4NeutronElectronElXsc::GetElementNonRelXsc(), ECCEhpDIRCFastPIDMap::getFastSmearLogLikelihood(), G4ChipsComponentXS::GetInelasticElementCrossSection(), G4VarNtp::getMomentumSum(), G4Pythia6Decayer::GetParticleMomentum(), G4NeutronElectronElXsc::GetRosenbluthXsc(), G4ChipsComponentXS::GetTotalElementCrossSection(), G4VarNtp::getTotalThreeMomentum(), HepMCG4Interface::HepMC2G4(), G4Pythia6Decayer::ImportDecayProducts(), field_utils::inverseCurvatureRadius(), G4DecayProducts::IsChecked(), G4UCNBoundaryProcess::LDiffRefl(), PHActsTrkFitter::loopTracks(), PHActsTrackProjection::makeTrackParams(), PHTpcResiduals::makeTrackParams(), MoveDescendantsToParent(), G4UCNBoundaryProcess::MRDiffRefl(), G4UCNBoundaryProcess::MRDiffTrans(), G4INCL::TransmissionChannel::particleLeaves(), G4LowEnergyBremsstrahlung::PostStepDoIt(), ECCEFastPIDReco::process_event(), G4FastStep::ProposePrimaryTrackFinalMomentumDirection(), G4INCL::Cluster::putParticlesOffShell(), G4RPGFragmentation::ReactionStage(), G4INCL::ParticleSampler::sampleOneParticleWithoutRPCorrelation(), scan_mom(), G4INCL::Particle::setFrozenMomentum(), G4INCL::Particle::setMomentum(), G4RPGInelastic::SetUpChange(), G4INCL::StandardPropagationModel::shootParticle(), Acts::AtlasStepper< ConstantBField >::step(), G4AblaInterface::toG4Particle(), G4INCLXXInterface::toG4Particle(), G4ExcitedString::TransformToAlignedCms(), G4FragmentingString::TransformToAlignedCms(), G4ExcitedString::TransformToCenterOfMass(), G4FragmentingString::TransformToCenterOfMass(), Acts::MaterialInteractor::UpdateResult(), and ActsEvaluator::visitTrackStates().
auto momentum_high = data::xrange(100_GeV, 10_TeV, 100_GeV) static
Definition at line 35 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 35 of file InteractionsTests.cpp
auto momentum_low = data::xrange(100_MeV, 10_GeV, 100_MeV) static
Definition at line 33 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 33 of file InteractionsTests.cpp
auto momentum_med = data::xrange(10_GeV, 100_GeV, 10_GeV) static
Definition at line 34 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 34 of file InteractionsTests.cpp
auto particle = data::make(pdg) ^ data::make(mass) ^ data::make(charge) static
Definition at line 31 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 31 of file InteractionsTests.cpp
Referenced by G4EmModelActivator::ActivateEmOptions(), G4ITStepProcessor::ActiveOnlyITProcess(), CML2ExpVoxels::add(), G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles(), XrayFluoPhysicsList::AddDecay(), PhysicsList::AddDecay(), G4EmExtraParameters::AddPAIModel(), Par02PhysicsList::AddParameterisation(), PHG4ParticleGeneratorBase::AddParticle(), GB02BOptrMultiParticleForceCollision::AddParticle(), KFParticle_Container::addParticle(), BiasingOperator::AddParticle(), G4ChannelingOptrMultiParticleChangeCrossSection::AddParticle(), MCTruthManager::AddParticle(), GB01BOptrMultiParticleChangeCrossSection::AddParticle(), B03PhysicsList::AddScoringProcess(), F04PhysicsList::AddStepMax(), HadrontherapyPhysicsList::AddStepMax(), XrayFluoPhysicsList::AddStepMax(), PhysicsList::AddStepMax(), ML2PhysicsList::AddStepMax(), ExN02PhysicsList::AddStepMax(), IORTPhysicsList::AddStepMax(), PhysicsList::AddTrackingCut(), G4PhysicsListHelper::AddTransportation(), DMXPhysicsList::AddTransportation(), LBE::AddTransportation(), SvtxHitEval::all_hits_from(), SvtxClusterEval::all_truth_clusters(), JetTruthEval::all_truth_hits(), JetRecoEval::all_truth_jets(), SvtxHitEval::all_truth_particles(), SvtxClusterEval::all_truth_particles(), SvtxVertexEval::all_truth_points(), CaloRawClusterEval::all_truth_primary_particles(), JetTruthEval::all_truth_showers(), G4hImpactIonisation::AlongStepDoIt(), PHG4TpcDirectLaser::AppendLaserTrack(), PHSartreParticleTrigger::Apply(), G4GenericBiasingPhysics::AssociateParallelGeometries(), B1PrimaryGeneratorAction::B1PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), RunAction::BeginOfRunAction(), BOOST_AUTO_TEST_CASE(), G4ErrorTrajState::BuildCharge(), G4VUserPhysicsList::BuildPhysicsTable(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), G4PhysicsListHelper::CheckParticleList(), KFParticle_Tools::constrainToVertex(), G4ExcitedBaryonConstructor::ConstructAntiParticle(), G4ShortLivedConstructor::ConstructBaryons(), eRositaPhysicsList::ConstructEM(), PhysicsList::ConstructEM(), B03PhysicsList::ConstructEM(), ExN02PhysicsList::ConstructEM(), G4ErrorPhysicsList::ConstructEM(), DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), XrayTelPhysicsList::ConstructEM(), G4AdjointPhysicsList::ConstructEM(), PurgMagPhysicsList::ConstructEM(), eRositaPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructGeneral(), ExN02PhysicsList::ConstructGeneral(), DMXPhysicsList::ConstructGeneral(), LBE::ConstructGeneral(), Par02PhysicsList::ConstructGeneral(), XrayTelPhysicsList::ConstructGeneral(), G4AdjointPhysicsList::ConstructGeneral(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), PhysicsList::ConstructHighEnergy(), G4ShortLivedConstructor::ConstructMesons(), G4ExcitedMesonConstructor::ConstructMesons(), DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), G4ExcitedBaryonConstructor::ConstructParticle(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), XPhysicsList::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4ChannelingPhysics::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), ExUCNExtraPhysics::ConstructProcess(), StepMaxBuilder::ConstructProcess(), PhysListEmStandard::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), G4ParallelWorldPhysics::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), StepLimiterBuilder::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4NeutronTrackingCut::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4UnknownDecayPhysics::ConstructProcess(), G4ErrorPhysicsList::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4DecayPhysics::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), TSPhysicsList::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), P6DExtDecayerPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), CexmcStudiedPhysics< Process >::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4ShortLivedConstructor::ConstructQuarks(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), ExUCNExtraPhysics::ConstructUCN(), ActsFatras::Simulator< charged_selector_t, charged_simulator_t, neutral_selector_t, neutral_simulator_t >::copyOutputs(), G4IonParametrisedLossModel::CorrectionsAlongStep(), FW::HepMC3Event::createGenVertex(), G4NonEquilibriumEvaporator::deExcite(), Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction(), G4INCL::CoulombNonRelativistic::distortOut(), G4TrajectoryDrawByParticleID::Draw(), G4VUserPhysicsList::DumpList(), G4hImpactIonisation::ElectronicLossFluctuation(), PHG4TruthEventAction::EndOfEventAction(), Run::EndOfRun(), HistoManager::EndOfRun(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), RunAction::EnergySpectrumOfSecondaries(), G4QMDSystem::EraseParticipant(), GIDI_settings::eraseParticle(), eRositaPrimaryGeneratorAction::eRositaPrimaryGeneratorAction(), G4TrajectoryParticleFilter::Evaluate(), FW::PrintParticles::execute(), FW::FlattenEvent::execute(), FW::TruthTrackFinder::execute(), FW::ParticleSmearing::execute(), FW::TruthVerticesToTracksAlgorithm::execute(), ExN02PrimaryGeneratorAction::ExN02PrimaryGeneratorAction(), ExP01PrimaryGeneratorAction::ExP01PrimaryGeneratorAction(), ExTGPrimaryGeneratorAction::ExTGPrimaryGeneratorAction(), ExUCNPrimaryGeneratorAction::ExUCNPrimaryGeneratorAction(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F05PrimaryGeneratorAction::F05PrimaryGeneratorAction(), F06PrimaryGeneratorAction::F06PrimaryGeneratorAction(), FCALPrimaryGeneratorAction::FCALPrimaryGeneratorAction(), G4CascadParticle::fill(), G4VParticlePropertyReporter::FillList(), EventEvaluator::fillOutputNtuples(), EventEvaluatorEIC::fillOutputNtuples(), FW::HepMC3Event::finalState(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), G4ParticleTable::FindParticle(), Fun4All_photonDispersion(), G4BOptrForceCollision::G4BOptrForceCollision(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), GammaKnifeActionInitialization::GammaKnifeActionInitialization(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), GB07PrimaryGeneratorAction::GB07PrimaryGeneratorAction(), G4NucleiModel::generateInteractionPartners(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), B5PrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), MedicalBeam::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4INCL::StandardPropagationModel::generateUpdatedCollisions(), FastJetAlgoSub::get_jets(), FastJetAlgo::get_jets(), SvtxVertexEval::get_ntracks_contribution(), BaseTruthEval::get_particle(), BaseTruthEval::get_primary_particle(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4UserPhysicsListMessenger::GetCurrentValue(), G4ParticleMessenger::GetCurrentValue(), G4NuclNuclDiffuseElastic::GetDiffuseElasticSumXsc(), G4DiffuseElastic::GetDiffuseElasticSumXsc(), G4NuclNuclDiffuseElastic::GetDiffuseElasticXsc(), G4DiffuseElastic::GetDiffuseElasticXsc(), G4DNAModelInterface::GetDNAModel(), G4VDNAModel::GetHighELimit(), G4VDNAModel::GetLowELimit(), G4VarNtp::getMass(), G4OpRayleigh::GetMeanFreePath(), G4ExcitedLambdaConstructor::GetName(), G4ExcitedSigmaConstructor::GetName(), G4ExcitedXiConstructor::GetName(), G4ExcitedDeltaConstructor::GetName(), G4ExcitedNucleonConstructor::GetName(), G4ExcitedMesonConstructor::GetName(), GIDI_settings::getParticle(), pyG4ParticleTable::GetParticleList(), G4PrimaryVertex::GetPrimary(), G4ITStepProcessor::GetProcessInfo(), G4ProcessPlacer::GetProcessManager(), QAG4SimulationKFParticle::getTruthTrack(), KFParticle_truthAndDetTools::getTruthTrack(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), G4Pythia6Decayer::ImportDecayProducts(), G4ErrorPropagator::InitG4Track(), G4DNABornExcitationModel1::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNABornIonisationModel2::Initialise(), G4PenelopeIonisationModel::Initialise(), G4VUserPhysicsList::InitializeProcessManager(), PHG4Reco::InitRun(), G4ParticleTable::Insert(), G4NuclNuclDiffuseElastic::IntegralElasticProb(), G4DiffuseElastic::IntegralElasticProb(), KFParticle_Container::KFParticle_Container(), main(), SvtxClusterEval::max_truth_particle_by_cluster_energy(), SvtxHitEval::max_truth_particle_by_energy(), SvtxClusterEval::max_truth_particle_by_energy(), MCGIDI_particle_getInternalID(), MCGIDI_particle_new(), FW::Geant4::MMPrimaryGeneratorAction::MMPrimaryGeneratorAction(), MyPrimaryGeneratorActionFromFile::MyPrimaryGeneratorActionFromFile(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), FW::Pythia8Generator::operator()(), FW::ParametricProcessGenerator::operator()(), KFParticle_Container::operator=(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), PyG4ParticleList::p_begin(), PyG4ParticleList::p_end(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), G4LossTableManager::PreparePhysicsTable(), G4TextPPReporter::Print(), G4HtmlPPReporter::Print(), CaloEvaluator::printInputInfo(), KFParticle_DST::printNode(), SvtxEvaluator::printOutputInfo(), PHSiliconTruthTrackSeeding::Process(), PHTruthTrackSeeding::Process(), PHG4ParticleGun::process_event(), MomentumEvaluator::process_event(), PHG4InEventReadBack::process_event(), PHG4IonGun::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGenerator_flat_pT::process_event(), PHG4ParticleGeneratorD0::process_event(), HepMCNodeReader::process_event(), PHSartre::process_event(), PHG4DstCompressReco::process_event(), CreateCZHitContainer::process_event(), PHG4SimpleEventGenerator::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), PHG4DSTReader::process_event(), TpcRS::process_event(), PHG4TrackFastSim::process_event(), B0TrackFastSim::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), H02MuonSD::ProcessHits(), UltraPMTSD::ProcessHits(), CexmcTrackPoints::ProcessHits(), PHG4TruthEventAction::ProcessShowers(), G4RunManagerKernel::PropagateGenericIonID(), PHG4TruthEventAction::PruneShowers(), PurgMagPrimaryGeneratorAction::PurgMagPrimaryGeneratorAction(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::RE06PrimaryGeneratorAction(), FW::CsvParticleReader::read(), FW::EventGenerator::read(), G4ParticleTable::Remove(), G4CollisionOutput::removeOutgoingParticle(), FW::HepMC3Vertex::removeParticleIn(), FW::HepMC3Vertex::removeParticleOut(), G4VUserPhysicsList::RemoveProcessManager(), KFParticle_Container::Reset(), G4TextPPRetriever::Retrieve(), G4DNARuddAngle::SampleDirectionForShell(), G4AntiNuclElastic::SampleInvariantT(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4NuclNuclDiffuseElastic::SampleThetaCMS(), G4DiffuseElastic::SampleThetaCMS(), Run::ScoreNewTrack(), HistoManager::ScoreNewTrack(), G4TrajectoryDrawByOriginVolume::Set(), G4TrajectoryDrawByParticleID::Set(), PrimaryGeneratorAction::SetDefaultKinematic(), IORTPrimaryGeneratorAction::SetDefaultPrimaryParticle(), MCGIDI_quantitiesLookupModes::setGroupIndex(), G4VDNAModel::SetHighELimit(), G4VDNAModel::SetLowELimit(), G4UserPhysicsListMessenger::SetNewValue(), G4ParticleMessenger::SetNewValue(), Run::SetPrimary(), G4RunManagerKernel::SetScoreSplitter(), G4ITStepProcessor::SetupGeneralProcessInfo(), G4RunManagerKernel::SetupPhysics(), G4RayShooter::Shoot(), G4GlobalFastSimulationManager::ShowSetup(), ActsFatras::ParticleSimulator< propagator_t, physics_list_t, hit_surface_selector_t >::simulate(), G4VUserPhysicsList::StorePhysicsTable(), G4CollisionOutput::trivialise(), TSPrimaryGeneratorAction::TSPrimaryGeneratorAction(), G4IonDEDXScalingICRU73::UpdateCacheParticle(), G4IonParametrisedLossModel::UpdateDEDXCache(), G4IonParametrisedLossModel::UpdateRangeCache(), PHG4EPDSteppingAction::UserSteppingAction(), G4ParticleTable::WorkerG4ParticleTable(), FW::TrackFinderPerformanceWriter::Impl::write(), FW::TrackFitterPerformanceWriter::writeT(), FW::CsvParticleWriter::writeT(), FW::RootParticleWriter::writeT(), FW::RootTrajectoryWriter::writeT(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction(), and XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction().
int pdg[] static
Initial value:
= {Acts::eElectron, Acts::eMuon, Acts::ePionPlus,
                    Acts::eProton}
Definition at line 27 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 27 of file InteractionsTests.cpp
Referenced by BOOST_DATA_TEST_CASE(), G4NeutrinoNucleusModel::CoherentPion(), G4XMesonBaryonElastic::CrossSection(), example(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMeson(), findByPdg(), G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral(), RE01Trajectory::GetAttDefs(), RE04Trajectory::GetAttDefs(), G4ChipsAntiBaryonInelasticXS::GetIsoCrossSection(), G4ChipsHyperonElasticXS::GetIsoCrossSection(), G4ChipsHyperonInelasticXS::GetIsoCrossSection(), G4ChipsAntiBaryonElasticXS::GetIsoCrossSection(), G4HadronNucleonXsc::HadronNucleonXsc(), G4Pythia6Decayer::ImportDecayProducts(), main(), Acts::makeAbsolutePdgParticle(), ActsFatras::BetheBloch::operator()(), FW::Pythia8Generator::operator()(), FW::ParametricProcessGenerator::operator()(), G4CollisionComposite::Resolve::operator()(), Acts::operator<<(), G4NuclearRadii::ParticleRadius(), plot_map(), PHGenFitTrackProjection::process_event(), HadrontherapyDetectorSD::ProcessHits(), G4HadronElastic::SampleInvariantT(), scan_mom(), and HadrontherapySteppingAction::UserSteppingAction().
auto thickness = data::make(valuesThickness) static
Definition at line 25 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 25 of file InteractionsTests.cpp
Referenced by AddLayers_GEMDrift(), AddLayers_MiniTPCDrift(), Acts::CylinderVolumeBuilder::analyzeContent(), BMMGSetup(), Acts::Test::Layers::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_AUTO_TEST_CASE(), PHG4TpcDigitizer::CalculateCylinderCellADCScale(), PHG4InttDigitizer::CalculateLadderCellADCScale(), InttClusterizer::CalculateLadderThresholds(), PHG4MvtxDigitizer::CalculateMvtxLadderCellADCScale(), Acts::DD4hepLayerBuilder::centralLayers(), Acts::computeEnergyLossBethe(), Acts::computeEnergyLossLandau(), Acts::computeEnergyLossLandauSigma(), Acts::computeEnergyLossLandauSigmaQOverP(), G4MIRDRibCage::Construct(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4MicromegasDetector::construct_micromegas(), PHG4TpcEndCapDetector::ConstructEndCapAssembly(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4TpcDetector::ConstructTpcCageVolume(), PHG4TpcDetector::ConstructTpcGasVolume(), RawTowerBuilder::CreateNodes(), Acts::CylinderVolumeBounds::CylinderVolumeBounds(), Acts::deriveEnergyLossBetheQOverP(), Acts::deriveEnergyLossLandauQOverP(), Acts::DD4hepLayerBuilder::endcapLayers(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), FW::DigitizationAlgorithm::execute(), fullMaterial(), MyPrimaryGeneratorActionFromFile::GeneratePrimaries(), get_thickness(), PHG4CylinderGeom_Spacalv3::identify(), PHG4CylinderGeom_Spacalv2::identify(), PHG4CylinderGeom_Spacalv1::identify(), HcalRawTowerBuilder::InitRun(), main(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), Acts::ProtoLayer::measure(), MicromegasClusterizer::process_event(), PHG4CylinderGeom_Spacalv1::SetDefault(), LaserDrivenBeamLine::SetFirstCollimatorThickness(), LaserDrivenBeamLine::SetSecondCollimatorThickness(), FW::Obj::ObjSurfaceWriter::write(), and FW::Obj::writeTube().
double valuesThickness[] = {200_um, 1_mm} static
Definition at line 24 of file InteractionsTests.cpp.
View newest version in sPHENIX GitHub at line 24 of file InteractionsTests.cpp