ECCE @ EIC Software: G4PAIySection Class Reference
G4PAIySection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIySection.hh>
Public Member Functions
G4PAIySection ()
~G4PAIySection ()=default
void Initialize (const G4Material *material, G4double maxEnergyTransfer, G4double betaGammaSq, G4SandiaTable *)
void ComputeLowEnergyCof (const G4Material *material)
void InitPAI ()
void NormShift (G4double betaGammaSq)
void SplainPAI (G4double betaGammaSq)
G4double RutherfordIntegral (G4int intervalNumber, G4double limitLow, G4double limitHigh)
G4double ImPartDielectricConst (G4int intervalNumber, G4double energy)
G4double RePartDielectricConst (G4double energy)
G4double DifPAIySection (G4int intervalNumber, G4double betaGammaSq)
G4double PAIdNdxCerenkov (G4int intervalNumber, G4double betaGammaSq)
G4double PAIdNdxPlasmon (G4int intervalNumber, G4double betaGammaSq)
void IntegralPAIySection ()
void IntegralCerenkov ()
void IntegralPlasmon ()
G4double SumOverInterval (G4int intervalNumber)
G4double SumOverIntervaldEdx (G4int intervalNumber)
G4double SumOverInterCerenkov (G4int intervalNumber)
G4double SumOverInterPlasmon (G4int intervalNumber)
G4double SumOverBorder (G4int intervalNumber, G4double energy)
G4double SumOverBorderdEdx (G4int intervalNumber, G4double energy)
G4double SumOverBordCerenkov (G4int intervalNumber, G4double energy)
G4double SumOverBordPlasmon (G4int intervalNumber, G4double energy)
G4double GetStepEnergyLoss (G4double step)
G4double GetStepCerenkovLoss (G4double step)
G4double GetStepPlasmonLoss (G4double step)
G4double GetLorentzFactor (G4int j) const
G4int GetNumberOfGammas () const
G4int GetSplineSize () const
G4int GetIntervalNumber () const
G4double GetEnergyInterval (G4int i)
G4double GetDifPAIySection (G4int i)
G4double GetPAIdNdxCrenkov (G4int i)
G4double GetPAIdNdxPlasmon (G4int i)
G4double GetMeanEnergyLoss () const
G4double GetMeanCerenkovLoss () const
G4double GetMeanPlasmonLoss () const
G4double GetNormalizationCof () const
G4double GetPAItable (G4int i, G4int j) const
G4double GetSplineEnergy (G4int i) const
G4double GetIntegralPAIySection (G4int i) const
G4double GetIntegralPAIdEdx (G4int i) const
G4double GetIntegralCerenkov (G4int i) const
G4double GetIntegralPlasmon (G4int i) const
void SetVerbose (G4int v)
Private Member Functions
void CallError (G4int i, const G4String &methodName) const
Private Attributes
G4int fIntervalNumber
G4double fNormalizationCof
G4double betaBohr
G4double betaBohr4
G4double fDensity
G4double fElectronDensity
G4double fLowEnergyCof
G4int fSplineNumber
G4int fVerbose
G4SandiaTable * fSandia
G4DataVector fEnergyInterval
G4DataVector fA1
G4DataVector fA2
G4DataVector fA3
G4DataVector fA4
G4DataVector fSplineEnergy
G4DataVector fRePartDielectricConst
G4DataVector fImPartDielectricConst
G4DataVector fIntegralTerm
G4DataVector fDifPAIySection
G4DataVector fdNdxCerenkov
G4DataVector fdNdxPlasmon
G4DataVector fIntegralPAIySection
G4DataVector fIntegralPAIdEdx
G4DataVector fIntegralCerenkov
G4DataVector fIntegralPlasmon
G4double fPAItable [500][112]
Static Private Attributes
static const G4double fDelta = 0.005
static const G4double fError = 0.005
static G4int fNumberOfGammas = 111
static const G4double fLorentzFactor [112]
static const G4int fRefGammaNumber = 29
static const G4int fMaxSplineSize = 500
Detailed Description
Definition at line 51 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PAIySection.hh
Constructor & Destructor Documentation
G4PAIySection::G4PAIySection () explicit
Definition at line 75 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 75 of file G4PAIySection.cc
References source.hepunit::fine_structure_const.
G4PAIySection::~G4PAIySection () default
Member Function Documentation
void G4PAIySection::CallError (G4int i, const G4String & methodName) const private
Definition at line 1348 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1348 of file G4PAIySection.cc
References FatalException, and G4Exception().
Referenced by GetIntegralCerenkov(), GetIntegralPAIdEdx(), GetIntegralPAIySection(), GetIntegralPlasmon(), and GetSplineEnergy().
void G4PAIySection::ComputeLowEnergyCof (const G4Material * material)
Definition at line 245 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 245 of file G4PAIySection.cc
References G4Material::GetElement(), G4Material::GetNumberOfElements(), and G4Element::GetZ().
G4double G4PAIySection::DifPAIySection (G4int intervalNumber, G4double betaGammaSq)
Definition at line 589 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 589 of file G4PAIySection.cc
References e, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, source.hepunit::hbarc, max, pi, x1, x2, x3, x4, x5, and x6.
G4double G4PAIySection::GetDifPAIySection (G4int i) inline
Definition at line 123 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 123 of file G4PAIySection.hh
References fDifPAIySection.
G4double G4PAIySection::GetEnergyInterval (G4int i) inline
Definition at line 121 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PAIySection.hh
References fEnergyInterval.
G4double G4PAIySection::GetIntegralCerenkov (G4int i) const inline
Definition at line 221 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 221 of file G4PAIySection.hh
References CallError(), fIntegralCerenkov, and fSplineNumber.
G4double G4PAIySection::GetIntegralPAIdEdx (G4int i) const inline
Definition at line 215 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 215 of file G4PAIySection.hh
References CallError(), fIntegralPAIdEdx, and fSplineNumber.
G4double G4PAIySection::GetIntegralPAIySection (G4int i) const inline
Definition at line 209 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 209 of file G4PAIySection.hh
References CallError(), fIntegralPAIySection, and fSplineNumber.
G4double G4PAIySection::GetIntegralPlasmon (G4int i) const inline
Definition at line 227 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 227 of file G4PAIySection.hh
References CallError(), fIntegralPlasmon, and fSplineNumber.
G4int G4PAIySection::GetIntervalNumber () const inline
Definition at line 119 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PAIySection.hh
References fIntervalNumber.
G4double G4PAIySection::GetLorentzFactor (G4int j) const
Definition at line 109 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 109 of file G4PAIySection.cc
G4double G4PAIySection::GetMeanCerenkovLoss () const inline
Definition at line 128 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 128 of file G4PAIySection.hh
References fIntegralCerenkov.
G4double G4PAIySection::GetMeanEnergyLoss () const inline
Definition at line 127 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PAIySection.hh
References fIntegralPAIySection.
G4double G4PAIySection::GetMeanPlasmonLoss () const inline
Definition at line 129 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 129 of file G4PAIySection.hh
References fIntegralPlasmon.
G4double G4PAIySection::GetNormalizationCof () const inline
Definition at line 131 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 131 of file G4PAIySection.hh
References fNormalizationCof.
G4int G4PAIySection::GetNumberOfGammas () const inline
Definition at line 115 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PAIySection.hh
References fNumberOfGammas.
G4double G4PAIySection::GetPAIdNdxCrenkov (G4int i) inline
Definition at line 124 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PAIySection.hh
References fdNdxCerenkov.
G4double G4PAIySection::GetPAIdNdxPlasmon (G4int i) inline
Definition at line 125 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PAIySection.hh
References fdNdxPlasmon.
G4double G4PAIySection::GetPAItable (G4int i, G4int j) const inline
Definition at line 198 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 198 of file G4PAIySection.hh
References fPAItable.
G4double G4PAIySection::GetSplineEnergy (G4int i) const inline
Definition at line 203 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 203 of file G4PAIySection.hh
References CallError(), fSplineEnergy, and fSplineNumber.
G4int G4PAIySection::GetSplineSize () const inline
Definition at line 117 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PAIySection.hh
References fSplineNumber.
G4double G4PAIySection::GetStepCerenkovLoss (G4double step)
Definition at line 1275 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1275 of file G4PAIySection.cc
References G4Poisson(), G4UniformRand, position, and Acts::Test::step().
G4double G4PAIySection::GetStepEnergyLoss (G4double step)
Definition at line 1238 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1238 of file G4PAIySection.cc
References G4Poisson(), G4UniformRand, position, and Acts::Test::step().
G4double G4PAIySection::GetStepPlasmonLoss (G4double step)
Definition at line 1312 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1312 of file G4PAIySection.cc
References G4Poisson(), G4UniformRand, position, and Acts::Test::step().
G4double G4PAIySection::ImPartDielectricConst (G4int intervalNumber, G4double energy)
Definition at line 511 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 511 of file G4PAIySection.cc
References source.hepunit::hbarc, and k.
void G4PAIySection::Initialize (const G4Material * material, G4double maxEnergyTransfer, G4double betaGammaSq, G4SandiaTable * sandia)
Definition at line 118 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 118 of file G4PAIySection.cc
References eV, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetElectronDensity(), G4SandiaTable::GetMaxInterval(), G4SandiaTable::GetSandiaMatTablePAI(), and keV.
void G4PAIySection::InitPAI ()
Definition at line 278 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 278 of file G4PAIySection.cc
void G4PAIySection::IntegralCerenkov ()
Definition at line 785 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 785 of file G4PAIySection.cc
References k.
void G4PAIySection::IntegralPAIySection ()
Definition at line 754 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 754 of file G4PAIySection.cc
References k.
void G4PAIySection::IntegralPlasmon ()
Definition at line 816 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 816 of file G4PAIySection.cc
References k.
void G4PAIySection::NormShift (G4double betaGammaSq)
Definition at line 329 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 329 of file G4PAIySection.cc
References source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, source.hepunit::hbarc, k, pi, and x.
G4double G4PAIySection::PAIdNdxCerenkov (G4int intervalNumber, G4double betaGammaSq)
Definition at line 656 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 656 of file G4PAIySection.cc
References e, source.hepunit::fine_structure_const, source.hepunit::hbarc, pi, x3, and x5.
G4double G4PAIySection::PAIdNdxPlasmon (G4int intervalNumber, G4double betaGammaSq)
Definition at line 715 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 715 of file G4PAIySection.cc
References e, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, source.hepunit::hbarc, max, and pi.
G4double G4PAIySection::RePartDielectricConst (G4double energy)
Definition at line 534 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 534 of file G4PAIySection.cc
References c1, c2, source.hepunit::hbarc, pi, x1, and x2.
G4double G4PAIySection::RutherfordIntegral (G4int intervalNumber, G4double limitLow, G4double limitHigh)
Definition at line 489 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 489 of file G4PAIySection.cc
References c1, c2, k, x1, and x2.
void G4PAIySection::SetVerbose (G4int v) inline
Definition at line 142 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PAIySection.hh
References fVerbose, and v.
void G4PAIySection::SplainPAI (G4double betaGammaSq)
Definition at line 402 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 402 of file G4PAIySection.cc
References a, b, Acts::Test::delta, k, x, x1, x2, y, and y2.
G4double G4PAIySection::SumOverBordCerenkov (G4int intervalNumber, G4double energy)
Definition at line 1116 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1116 of file G4PAIySection.cc
References a, b, c, d, and x1.
G4double G4PAIySection::SumOverBorder (G4int intervalNumber, G4double energy)
Definition at line 990 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 990 of file G4PAIySection.cc
References a, b, d, and x1.
G4double G4PAIySection::SumOverBorderdEdx (G4int intervalNumber, G4double energy)
Definition at line 1060 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1060 of file G4PAIySection.cc
References a, b, d, and x1.
G4double G4PAIySection::SumOverBordPlasmon (G4int intervalNumber, G4double energy)
Definition at line 1185 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 1185 of file G4PAIySection.cc
References a, b, c, d, and x1.
G4double G4PAIySection::SumOverInterCerenkov (G4int intervalNumber)
Definition at line 919 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 919 of file G4PAIySection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIySection::SumOverInterPlasmon (G4int intervalNumber)
Definition at line 956 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 956 of file G4PAIySection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIySection::SumOverInterval (G4int intervalNumber)
Definition at line 843 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 843 of file G4PAIySection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIySection::SumOverIntervaldEdx (G4int intervalNumber)
Definition at line 885 of file G4PAIySection.cc.
View newest version in sPHENIX GitHub at line 885 of file G4PAIySection.cc
References a, kdfinder::abs(), b, c, e, and x1.
Member Data Documentation
G4double G4PAIySection::betaBohr private
Definition at line 162 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 162 of file G4PAIySection.hh
G4double G4PAIySection::betaBohr4 private
Definition at line 163 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 163 of file G4PAIySection.hh
G4DataVector G4PAIySection::fA1 private
Definition at line 174 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 174 of file G4PAIySection.hh
G4DataVector G4PAIySection::fA2 private
Definition at line 175 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 175 of file G4PAIySection.hh
G4DataVector G4PAIySection::fA3 private
Definition at line 176 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 176 of file G4PAIySection.hh
G4DataVector G4PAIySection::fA4 private
Definition at line 177 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 177 of file G4PAIySection.hh
const G4double G4PAIySection::fDelta = 0.005 static private
Definition at line 150 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 150 of file G4PAIySection.hh
G4double G4PAIySection::fDensity private
Definition at line 165 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 165 of file G4PAIySection.hh
G4DataVector G4PAIySection::fDifPAIySection private
Definition at line 186 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 186 of file G4PAIySection.hh
Referenced by GetDifPAIySection().
G4DataVector G4PAIySection::fdNdxCerenkov private
Definition at line 187 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 187 of file G4PAIySection.hh
Referenced by GetPAIdNdxCrenkov().
G4DataVector G4PAIySection::fdNdxPlasmon private
Definition at line 188 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 188 of file G4PAIySection.hh
Referenced by GetPAIdNdxPlasmon().
G4double G4PAIySection::fElectronDensity private
Definition at line 166 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PAIySection.hh
G4DataVector G4PAIySection::fEnergyInterval private
Definition at line 173 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 173 of file G4PAIySection.hh
Referenced by GetEnergyInterval().
const G4double G4PAIySection::fError = 0.005 static private
Definition at line 151 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 151 of file G4PAIySection.hh
G4DataVector G4PAIySection::fImPartDielectricConst private
Definition at line 184 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 184 of file G4PAIySection.hh
G4DataVector G4PAIySection::fIntegralCerenkov private
Definition at line 192 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 192 of file G4PAIySection.hh
Referenced by GetIntegralCerenkov(), and GetMeanCerenkovLoss().
G4DataVector G4PAIySection::fIntegralPAIdEdx private
Definition at line 191 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 191 of file G4PAIySection.hh
Referenced by GetIntegralPAIdEdx().
G4DataVector G4PAIySection::fIntegralPAIySection private
Definition at line 190 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 190 of file G4PAIySection.hh
Referenced by GetIntegralPAIySection(), and GetMeanEnergyLoss().
G4DataVector G4PAIySection::fIntegralPlasmon private
Definition at line 193 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 193 of file G4PAIySection.hh
Referenced by GetIntegralPlasmon(), and GetMeanPlasmonLoss().
G4DataVector G4PAIySection::fIntegralTerm private
Definition at line 185 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 185 of file G4PAIySection.hh
G4int G4PAIySection::fIntervalNumber private
Definition at line 159 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 159 of file G4PAIySection.hh
Referenced by GetIntervalNumber().
const G4double G4PAIySection::fLorentzFactor static private
Initial value:
=
{
0.0,
1.094989e+00, 1.107813e+00, 1.122369e+00, 1.138890e+00, 1.157642e+00,
1.178925e+00, 1.203082e+00, 1.230500e+00, 1.261620e+00, 1.296942e+00,
1.337032e+00, 1.382535e+00, 1.434181e+00, 1.492800e+00, 1.559334e+00,
1.634850e+00, 1.720562e+00, 1.817845e+00, 1.928263e+00, 2.053589e+00,
2.195835e+00, 2.357285e+00, 2.540533e+00, 2.748522e+00, 2.984591e+00,
3.252533e+00, 3.556649e+00, 3.901824e+00, 4.293602e+00, 4.738274e+00,
5.242981e+00, 5.815829e+00, 6.466019e+00, 7.203990e+00, 8.041596e+00,
8.992288e+00, 1.007133e+01, 1.129606e+01, 1.268614e+01, 1.426390e+01,
1.605467e+01, 1.808721e+01, 2.039417e+01, 2.301259e+01, 2.598453e+01,
2.935771e+01, 3.318630e+01, 3.753180e+01, 4.246399e+01, 4.806208e+01,
5.441597e+01, 6.162770e+01, 6.981310e+01, 7.910361e+01, 8.964844e+01,
1.016169e+02, 1.152013e+02, 1.306197e+02, 1.481198e+02, 1.679826e+02,
1.905270e+02, 2.161152e+02, 2.451581e+02, 2.781221e+02, 3.155365e+02,
3.580024e+02, 4.062016e+02, 4.609081e+02, 5.230007e+02, 5.934765e+02,
6.734672e+02, 7.642575e+02, 8.673056e+02, 9.842662e+02, 1.117018e+03,
1.267692e+03, 1.438709e+03, 1.632816e+03, 1.853128e+03, 2.103186e+03,
2.387004e+03, 2.709140e+03, 3.074768e+03, 3.489760e+03, 3.960780e+03,
4.495394e+03, 5.102185e+03, 5.790900e+03, 6.572600e+03, 7.459837e+03,
8.466860e+03, 9.609843e+03, 1.090714e+04, 1.237959e+04, 1.405083e+04,
1.594771e+04, 1.810069e+04, 2.054434e+04, 2.331792e+04, 2.646595e+04,
3.003901e+04, 3.409446e+04, 3.869745e+04, 4.392189e+04, 4.985168e+04,
5.658206e+04, 6.422112e+04, 7.289153e+04, 8.273254e+04, 9.390219e+04,
1.065799e+05
}
Definition at line 154 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 154 of file G4PAIySection.hh
G4double G4PAIySection::fLowEnergyCof private
Definition at line 167 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 167 of file G4PAIySection.hh
const G4int G4PAIySection::fMaxSplineSize = 500 static private
Definition at line 180 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 180 of file G4PAIySection.hh
G4double G4PAIySection::fNormalizationCof private
Definition at line 160 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 160 of file G4PAIySection.hh
Referenced by GetNormalizationCof().
G4int G4PAIySection::fNumberOfGammas = 111 static private
Definition at line 153 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 153 of file G4PAIySection.hh
Referenced by GetNumberOfGammas().
G4double G4PAIySection::fPAItable[500][112] private
Definition at line 195 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 195 of file G4PAIySection.hh
Referenced by GetPAItable().
const G4int G4PAIySection::fRefGammaNumber = 29 static private
Definition at line 157 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 157 of file G4PAIySection.hh
G4DataVector G4PAIySection::fRePartDielectricConst private
Definition at line 183 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 183 of file G4PAIySection.hh
G4SandiaTable* G4PAIySection::fSandia private
Definition at line 171 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 171 of file G4PAIySection.hh
G4DataVector G4PAIySection::fSplineEnergy private
Definition at line 182 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 182 of file G4PAIySection.hh
Referenced by GetSplineEnergy().
G4int G4PAIySection::fSplineNumber private
Definition at line 168 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PAIySection.hh
Referenced by GetIntegralCerenkov(), GetIntegralPAIdEdx(), GetIntegralPAIySection(), GetIntegralPlasmon(), GetSplineEnergy(), and GetSplineSize().
G4int G4PAIySection::fVerbose private
Definition at line 169 of file G4PAIySection.hh.
View newest version in sPHENIX GitHub at line 169 of file G4PAIySection.hh
Referenced by SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIySection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PAIySection.cc