ECCE @ EIC Software: G4VDNAReactionModel Class Reference
G4VDNAReactionModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4VDNAReactionModel.hh>
Public Member Functions
G4VDNAReactionModel ()
G4VDNAReactionModel (const G4VDNAReactionModel &)=delete
G4VDNAReactionModel & operator= (const G4VDNAReactionModel &)=delete
virtual ~G4VDNAReactionModel ()
virtual void Initialise (const G4MolecularConfiguration *, const G4Track &)
virtual void InitialiseToPrint (const G4MolecularConfiguration *)=0
virtual G4double GetReactionRadius (const G4MolecularConfiguration *, const G4MolecularConfiguration *)=0
virtual G4double GetReactionRadius (int)=0
virtual G4bool FindReaction (const G4Track &, const G4Track &, G4double, G4double &, G4bool)=0
void SetReactionTable (const G4DNAMolecularReactionTable *)
const G4DNAMolecularReactionTable * GetReactionTable ()
Protected Attributes
const G4DNAMolecularReactionTable * fpReactionTable
Detailed Description
G4VDNAReactionModel is an interface used by the G4DNAMolecularReaction process. It defines how the reaction radius should be calculated and whether two molecules can indeed react.
Definition at line 60 of file G4VDNAReactionModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VDNAReactionModel.hh
Constructor & Destructor Documentation
G4VDNAReactionModel::G4VDNAReactionModel ()
Definition at line 29 of file G4VDNAReactionModel.cc.
View newest version in sPHENIX GitHub at line 29 of file G4VDNAReactionModel.cc
G4VDNAReactionModel::G4VDNAReactionModel (const G4VDNAReactionModel &) delete
G4VDNAReactionModel::~G4VDNAReactionModel () virtual default
Member Function Documentation
virtual G4bool G4VDNAReactionModel::FindReaction (const G4Track & , const G4Track & , G4double , G4double & , G4bool) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
Referenced by G4DNAMolecularReaction::TestReactibility().
virtual G4double G4VDNAReactionModel::GetReactionRadius (const G4MolecularConfiguration * , const G4MolecularConfiguration *) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), G4DNAMolecularReactionTable::PrintTable(), and G4DNAMolecularReaction::TestReactibility().
virtual G4double G4VDNAReactionModel::GetReactionRadius (int) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
const G4DNAMolecularReactionTable * G4VDNAReactionModel::GetReactionTable ()
Definition at line 41 of file G4VDNAReactionModel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VDNAReactionModel.cc
References fpReactionTable.
Referenced by G4DNAMolecularReactionTable::PrintTable().
virtual void G4VDNAReactionModel::Initialise (const G4MolecularConfiguration * , const G4Track &) inline virtual
Reimplemented in G4DNASmoluchowskiReactionModel.
Definition at line 68 of file G4VDNAReactionModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VDNAReactionModel.hh
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep().
virtual void G4VDNAReactionModel::InitialiseToPrint (const G4MolecularConfiguration *) pure virtual
Implemented in G4DNASmoluchowskiReactionModel.
Referenced by G4DNAMolecularReactionTable::PrintTable().
G4VDNAReactionModel& G4VDNAReactionModel::operator= (const G4VDNAReactionModel &) delete
void G4VDNAReactionModel::SetReactionTable (const G4DNAMolecularReactionTable * pReactionTable)
Definition at line 36 of file G4VDNAReactionModel.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VDNAReactionModel.cc
References fpReactionTable.
Referenced by G4DNAMolecularReactionTable::PrintTable().
Member Data Documentation
const G4DNAMolecularReactionTable* G4VDNAReactionModel::fpReactionTable protected
Definition at line 82 of file G4VDNAReactionModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VDNAReactionModel.hh
Referenced by G4DNASmoluchowskiReactionModel::GetReactionRadius(), GetReactionTable(), G4DNASmoluchowskiReactionModel::Initialise(), G4DNASmoluchowskiReactionModel::InitialiseToPrint(), and SetReactionTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4VDNAReactionModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4VDNAReactionModel.cc