ECCE @ EIC Software: G4ParameterisationTrdX Class Reference
G4ParameterisationTrdX Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationTrd.hh>
Public Member Functions
G4ParameterisationTrdX (EAxis axis, G4int nCopies, G4double width, G4double offset, G4VSolid *motherSolid, DivisionType divType)
~G4ParameterisationTrdX ()
void CheckParametersValidity ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Trd &trd, const G4int copyNo, const G4VPhysicalVolume *pv) const
void ComputeDimensions (G4Trap &trd, const G4int copyNo, const G4VPhysicalVolume *pv) const
G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
Public Member Functions inherited from G4VParameterisationTrd
G4VParameterisationTrd (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationTrd ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void ComputeTrapParams ()
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VParameterisationTrd
G4bool bDivInTrap = false
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 75 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParameterisationTrd.hh
Constructor & Destructor Documentation
G4ParameterisationTrdX::G4ParameterisationTrdX (EAxis axis, G4int nCopies, G4double width, G4double offset, G4VSolid * motherSolid, DivisionType divType)
Definition at line 79 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ParameterisationTrd.cc
References G4VParameterisationTrd::bDivInTrap, G4VDivisionParameterisation::CalculateNDiv(), G4VDivisionParameterisation::CalculateWidth(), CheckParametersValidity(), DivNDIV, DivWIDTH, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4VDivisionParameterisation::kCarTolerance, offset, G4VDivisionParameterisation::SetType(), and G4VDivisionParameterisation::verbose.
G4ParameterisationTrdX::~G4ParameterisationTrdX ()
Definition at line 118 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ParameterisationTrd.cc
Member Function Documentation
void G4ParameterisationTrdX::CheckParametersValidity () virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 255 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 255 of file G4ParameterisationTrd.cc
References G4VDivisionParameterisation::CheckParametersValidity().
Referenced by G4ParameterisationTrdX().
void G4ParameterisationTrdX::ComputeDimensions (G4Trd & trd, const G4int copyNo, const G4VPhysicalVolume * pv) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 179 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 179 of file G4ParameterisationTrd.cc
References G4VSolid::DumpInfo(), G4VDivisionParameterisation::fhgap, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), G4Trd::SetAllParameters(), and G4VDivisionParameterisation::verbose.
void G4ParameterisationTrdX::ComputeDimensions (G4Trap & trd, const G4int copyNo, const G4VPhysicalVolume * pv) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 216 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 216 of file G4ParameterisationTrd.cc
References G4VSolid::DumpInfo(), G4VDivisionParameterisation::fhgap, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4cout, G4endl, G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), G4Trap::SetAllParameters(), and G4VDivisionParameterisation::verbose.
void G4ParameterisationTrdX::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 102 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 104 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 106 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 108 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 110 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 112 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 114 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 116 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 118 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 120 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdX::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 122 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ParameterisationTrd.hh
G4VSolid * G4ParameterisationTrdX::ComputeSolid (const G4int i, G4VPhysicalVolume * pv) virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 201 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 201 of file G4ParameterisationTrd.cc
References G4VParameterisationTrd::bDivInTrap, G4VDivisionParameterisation::ComputeSolid(), and G4VDivisionParameterisation::fmotherSolid.
void G4ParameterisationTrdX::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 132 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 132 of file G4ParameterisationTrd.cc
References G4VParameterisationTrd::bDivInTrap, FatalException, G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Exception(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), kXAxis, message(), Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), CLHEP::Hep3Vector::setX(), and G4VDivisionParameterisation::verbose.
void G4ParameterisationTrdX::ComputeTrapParams () private
Definition at line 281 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 281 of file G4ParameterisationTrd.cc
G4double G4ParameterisationTrdX::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 123 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ParameterisationTrd.cc
References G4VDivisionParameterisation::fmotherSolid, G4Trd::GetXHalfLength1(), and G4Trd::GetXHalfLength2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationTrd.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationTrd.cc