ECCE @ EIC Software: pyG4UserStackingAction::CB_G4UserStackingAction Struct Reference
pyG4UserStackingAction::CB_G4UserStackingAction Struct Reference
Public Member Functions
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
void NewStage ()
void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 42 of file pyG4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file pyG4UserStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack pyG4UserStackingAction::CB_G4UserStackingAction::ClassifyNewTrack (const G4Track * aTrack) inline virtual
Reimplemented from G4UserStackingAction.
Definition at line 46 of file pyG4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file pyG4UserStackingAction.cc
References G4UserStackingAction::ClassifyNewTrack(), and f.
void pyG4UserStackingAction::CB_G4UserStackingAction::NewStage () inline virtual
Reimplemented from G4UserStackingAction.
Definition at line 54 of file pyG4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4UserStackingAction.cc
References f, and G4UserStackingAction::NewStage().
void pyG4UserStackingAction::CB_G4UserStackingAction::PrepareNewEvent () inline virtual
Reimplemented from G4UserStackingAction.
Definition at line 62 of file pyG4UserStackingAction.cc.
View newest version in sPHENIX GitHub at line 62 of file pyG4UserStackingAction.cc
References f, and G4UserStackingAction::PrepareNewEvent().
The documentation for this struct was generated from the following file:
geant4/tree/geant4-10.6-release/environments/g4py/source/event/pyG4UserStackingAction.cc