ECCE @ EIC Software: G4BOptnCloning Class Reference
G4BOptnCloning Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnCloning.hh>
Public Member Functions
G4BOptnCloning (G4String name)
virtual ~G4BOptnCloning ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *condition)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
void SetCloneWeights (G4double clone1Weight, G4double clone2Weight)
G4Track * GetCloneTrack () const
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4double fClone1W
G4double fClone2W
G4ParticleChange fParticleChange
G4Track * fCloneTrack
Detailed Description
Definition at line 47 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 47 of file G4BOptnCloning.hh
Constructor & Destructor Documentation
G4BOptnCloning::G4BOptnCloning (G4String name)
Definition at line 29 of file G4BOptnCloning.cc.
View newest version in sPHENIX GitHub at line 29 of file G4BOptnCloning.cc
G4BOptnCloning::~G4BOptnCloning () virtual
Definition at line 37 of file G4BOptnCloning.cc.
View newest version in sPHENIX GitHub at line 37 of file G4BOptnCloning.cc
Member Function Documentation
virtual G4VParticleChange* G4BOptnCloning::ApplyFinalStateBiasing (const G4BiasingProcessInterface * , const G4Track * , const G4Step * , G4bool &) inline virtual
Implements G4VBiasingOperation.
Definition at line 59 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BOptnCloning.hh
virtual G4double G4BOptnCloning::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition * condition) inline virtual
Implements G4VBiasingOperation.
Definition at line 64 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BOptnCloning.hh
References NotForced.
G4VParticleChange * G4BOptnCloning::GenerateBiasingFinalState (const G4Track * track, const G4Step *) virtual
Implements G4VBiasingOperation.
Definition at line 40 of file G4BOptnCloning.cc.
View newest version in sPHENIX GitHub at line 40 of file G4BOptnCloning.cc
References G4ParticleChange::AddSecondary(), fClone1W, fClone2W, fCloneTrack, fParticleChange, G4ParticleChange::Initialize(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::SetNumberOfSecondaries(), G4VParticleChange::SetSecondaryWeightByProcess(), and G4Track::SetWeight().
G4Track* G4BOptnCloning::GetCloneTrack () const inline
Definition at line 78 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BOptnCloning.hh
References fCloneTrack.
Referenced by G4BOptrForceCollision::OperationApplied().
virtual const G4VBiasingInteractionLaw* G4BOptnCloning::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) inline virtual
Implements G4VBiasingOperation.
Definition at line 58 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BOptnCloning.hh
void G4BOptnCloning::SetCloneWeights (G4double clone1Weight, G4double clone2Weight) inline
Definition at line 76 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 76 of file G4BOptnCloning.hh
References fClone1W, and fClone2W.
Referenced by G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation().
Member Data Documentation
G4double G4BOptnCloning::fClone1W private
Definition at line 81 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 81 of file G4BOptnCloning.hh
Referenced by GenerateBiasingFinalState(), and SetCloneWeights().
G4double G4BOptnCloning::fClone2W private
Definition at line 81 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 81 of file G4BOptnCloning.hh
Referenced by GenerateBiasingFinalState(), and SetCloneWeights().
G4Track* G4BOptnCloning::fCloneTrack private
Definition at line 84 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 84 of file G4BOptnCloning.hh
Referenced by GenerateBiasingFinalState(), and GetCloneTrack().
G4ParticleChange G4BOptnCloning::fParticleChange private
Definition at line 83 of file G4BOptnCloning.hh.
View newest version in sPHENIX GitHub at line 83 of file G4BOptnCloning.hh
Referenced by GenerateBiasingFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnCloning.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptnCloning.cc