ECCE @ EIC Software: G4PhysicsConstructorRegistry Class Reference
G4PhysicsConstructorRegistry Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/factory/include/G4PhysicsConstructorRegistry.hh>
Public Member Functions
~G4PhysicsConstructorRegistry ()
void Register (G4VPhysicsConstructor *)
void DeRegister (G4VPhysicsConstructor *)
void Clean ()
void AddFactory (G4String, G4VBasePhysConstrFactory *)
G4VPhysicsConstructor * GetPhysicsConstructor (const G4String &name)
G4bool IsKnownPhysicsConstructor (const G4String &name)
std::vector< G4String > AvailablePhysicsConstructors () const
void PrintAvailablePhysicsConstructors () const
Static Public Member Functions
static
G4PhysicsConstructorRegistry * Instance ()
Private Member Functions
G4PhysicsConstructorRegistry ()
Private Attributes
std::vector
< G4VPhysicsConstructor * > physConstr
std::map< G4String,
G4VBasePhysConstrFactory * > factories
Static Private Attributes
static G4ThreadLocal
G4PhysicsConstructorRegistry * theInstance = 0
Detailed Description
Definition at line 56 of file G4PhysicsConstructorRegistry.hh.
View newest version in sPHENIX GitHub at line 56 of file G4PhysicsConstructorRegistry.hh
Constructor & Destructor Documentation
G4PhysicsConstructorRegistry::~G4PhysicsConstructorRegistry ()
Definition at line 65 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 65 of file G4PhysicsConstructorRegistry.cc
References Clean().
G4PhysicsConstructorRegistry::G4PhysicsConstructorRegistry () private
Definition at line 62 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PhysicsConstructorRegistry.cc
Referenced by Instance().
Member Function Documentation
void G4PhysicsConstructorRegistry::AddFactory (G4String name, G4VBasePhysConstrFactory * factory)
Definition at line 111 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 111 of file G4PhysicsConstructorRegistry.cc
References factories.
Referenced by G4PhysicsConstructorFactory< T >::G4PhysicsConstructorFactory().
std::vector< G4String > G4PhysicsConstructorRegistry::AvailablePhysicsConstructors () const
Definition at line 143 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 143 of file G4PhysicsConstructorRegistry.cc
References factories.
Referenced by G4PhysListRegistry::DeconstructPhysListName(), and PrintAvailablePhysicsConstructors().
void G4PhysicsConstructorRegistry::Clean ()
Definition at line 70 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 70 of file G4PhysicsConstructorRegistry.cc
References n, and physConstr.
Referenced by ~G4PhysicsConstructorRegistry().
void G4PhysicsConstructorRegistry::DeRegister (G4VPhysicsConstructor * p)
Definition at line 97 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 97 of file G4PhysicsConstructorRegistry.cc
References n, and physConstr.
G4VPhysicsConstructor * G4PhysicsConstructorRegistry::GetPhysicsConstructor (const G4String & name)
Definition at line 116 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 116 of file G4PhysicsConstructorRegistry.cc
References factories, FatalException, G4endl, and G4Exception().
Referenced by G4PhysListRegistry::GetModularPhysicsList().
G4PhysicsConstructorRegistry * G4PhysicsConstructorRegistry::Instance (void) static
Definition at line 53 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 53 of file G4PhysicsConstructorRegistry.cc
References G4PhysicsConstructorRegistry(), G4ThreadLocal, and theInstance.
Referenced by G4PhysListRegistry::DeconstructPhysListName(), G4PhysicsConstructorFactory< T >::G4PhysicsConstructorFactory(), G4PhysListRegistry::GetModularPhysicsList(), G4PhysListRegistry::PrintAvailablePhysLists(), and TG4GenericPhysicsList< T >::RegisterPhysicsConstructor().
G4bool G4PhysicsConstructorRegistry::IsKnownPhysicsConstructor (const G4String & name)
Definition at line 137 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 137 of file G4PhysicsConstructorRegistry.cc
References factories.
Referenced by G4PhysListRegistry::DeconstructPhysListName(), and G4PhysListRegistry::PrintAvailablePhysLists().
void G4PhysicsConstructorRegistry::PrintAvailablePhysicsConstructors () const
Definition at line 154 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 154 of file G4PhysicsConstructorRegistry.cc
References AvailablePhysicsConstructors(), G4cout, G4endl, and n.
void G4PhysicsConstructorRegistry::Register (G4VPhysicsConstructor * p)
Definition at line 85 of file G4PhysicsConstructorRegistry.cc.
View newest version in sPHENIX GitHub at line 85 of file G4PhysicsConstructorRegistry.cc
References n, and physConstr.
Member Data Documentation
std::map<G4String, G4VBasePhysConstrFactory*> G4PhysicsConstructorRegistry::factories private
Definition at line 92 of file G4PhysicsConstructorRegistry.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PhysicsConstructorRegistry.hh
Referenced by AddFactory(), AvailablePhysicsConstructors(), GetPhysicsConstructor(), and IsKnownPhysicsConstructor().
std::vector<G4VPhysicsConstructor*> G4PhysicsConstructorRegistry::physConstr private
Definition at line 90 of file G4PhysicsConstructorRegistry.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PhysicsConstructorRegistry.hh
Referenced by Clean(), DeRegister(), and Register().
G4ThreadLocal G4PhysicsConstructorRegistry * G4PhysicsConstructorRegistry::theInstance = 0 static private
Definition at line 88 of file G4PhysicsConstructorRegistry.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PhysicsConstructorRegistry.hh
Referenced by Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/factory/include/G4PhysicsConstructorRegistry.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/factory/src/G4PhysicsConstructorRegistry.cc