ECCE @ EIC Software: G4ePolarizedIonisation Class Reference
G4ePolarizedIonisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4ePolarizedIonisation.hh>
Public Member Functions
G4ePolarizedIonisation (const G4String &name="pol-eIoni")
virtual ~G4ePolarizedIonisation ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override
virtual void PrintInfo () override
Public Member Functions inherited from G4VEnergyLossProcess
G4VEnergyLossProcess (const G4String &name="EnergyLoss", G4ProcessType type=fElectromagnetic)
virtual ~G4VEnergyLossProcess ()
virtual void ProcessDescription (std::ostream &outFile) const override
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
G4PhysicsTable * BuildDEDXTable (G4EmTableType tType=fRestricted)
G4PhysicsTable * BuildLambdaTable (G4EmTableType tType=fRestricted)
virtual void StartTracking (G4Track *) override
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection) override
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4double SampleSubCutSecondaries (std::vector< G4Track * > &, const G4Step &, G4VEmModel *model, G4int matIdx)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
G4double GetDEDXDispersion (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double length)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double MeanFreePath (const G4Track &track)
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t &idx) const
void AddEmModel (G4int, G4VEmModel *, G4VEmFluctuationModel *fluc=0, const G4Region *region=nullptr)
void UpdateEmModel (const G4String &, G4double, G4double)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
G4int NumberOfModels () const
void SetFluctModel (G4VEmFluctuationModel *)
G4VEmFluctuationModel * FluctModel ()
void SetBaseParticle (const G4ParticleDefinition *p)
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * BaseParticle () const
const G4ParticleDefinition * SecondaryParticle () const
void ActivateSubCutoff (G4bool val, const G4Region *region=nullptr)
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
void ActivateForcedInteraction (G4double length, const G4String &region, G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void AddCollaborativeProcess (G4VEnergyLossProcess *)
void SetLossFluctuations (G4bool val)
void SetIntegral (G4bool val)
G4bool IsIntegral () const
void SetIonisation (G4bool val)
G4bool IsIonisationProcess () const
void SetLinearLossLimit (G4double val)
void SetStepFunction (G4double v1, G4double v2, G4bool lock=true)
void SetLowestEnergyLimit (G4double)
G4int NumberOfSubCutoffRegions () const
void SetDEDXTable (G4PhysicsTable *p, G4EmTableType tType)
void SetCSDARangeTable (G4PhysicsTable *pRange)
void SetRangeTableForLoss (G4PhysicsTable *p)
void SetSecondaryRangeTable (G4PhysicsTable *p)
void SetInverseRangeTable (G4PhysicsTable *p)
void SetLambdaTable (G4PhysicsTable *p)
void SetSubLambdaTable (G4PhysicsTable *p)
void SetDEDXBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
G4double MinKinEnergy () const
void SetMaxKinEnergy (G4double e)
G4double MaxKinEnergy () const
G4double CrossSectionBiasingFactor () const
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetDEDX (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetDEDXForSubsec (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRange (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetCSDARange (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetRangeForLoss (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4double GetKineticEnergy (G4double range, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *)
G4double GetLambda (G4double kineticEnergy, const G4MaterialCutsCouple *, G4double logKineticEnergy)
G4bool TablesAreBuilt () const
G4PhysicsTable * DEDXTable () const
G4PhysicsTable * DEDXTableForSubsec () const
G4PhysicsTable * DEDXunRestrictedTable () const
G4PhysicsTable * IonisationTable () const
G4PhysicsTable * IonisationTableForSubsec () const
G4PhysicsTable * CSDARangeTable () const
G4PhysicsTable * SecondaryRangeTable () const
G4PhysicsTable * RangeTableForLoss () const
G4PhysicsTable * InverseRangeTable () const
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * SubLambdaTable () const
const G4Element * GetCurrentElement () const
void SetDynamicMassCharge (G4double massratio, G4double charge2ratio)
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void InitialiseEnergyLossProcess (const G4ParticleDefinition *, const G4ParticleDefinition *) override
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *, G4double cut) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
Protected Member Functions inherited from G4VEnergyLossProcess
virtual void StreamProcessInfo (std::ostream &) const
virtual G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety) override
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *, G4double cut)
size_t CurrentMaterialCutsCoupleIndex () const
void SelectModel (G4double kinEnergy)
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Member Functions
void CleanTables ()
void BuildAsymmetryTables (const G4ParticleDefinition &part)
G4double ComputeAsymmetry (G4double energy, const G4MaterialCutsCouple *couple, const G4ParticleDefinition &particle, G4double cut, G4double &tasm)
G4double ComputeSaturationFactor (const G4Track &aTrack)
G4ePolarizedIonisation & operator= (const G4ePolarizedIonisation &right)=delete
G4ePolarizedIonisation (const G4ePolarizedIonisation &)=delete
Private Attributes
G4ParticleDefinition * theElectron
G4VEmFluctuationModel * flucModel
G4PolarizedMollerBhabhaModel * emModel
G4bool isElectron
G4bool isInitialised
G4ThreeVector theTargetPolarization
G4PhysicsTable * theAsymmetryTable
G4PhysicsTable * theTransverseAsymmetryTable
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VEnergyLossProcess
G4ParticleChangeForLoss fParticleChange
const G4Material * currentMaterial
const G4MaterialCutsCouple * currentCouple
size_t currentCoupleIndex
G4double preStepLambda
G4double fRange
G4double computedRange
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepScaledEnergy
G4double preStepLogScaledEnergy
G4double preStepRangeEnergy
G4double mfpKinEnergy
Detailed Description
Definition at line 65 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ePolarizedIonisation.hh
Constructor & Destructor Documentation
G4ePolarizedIonisation::G4ePolarizedIonisation (const G4String & name = "pol-eIoni") explicit
Definition at line 69 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ePolarizedIonisation.cc
References emModel, fIonisation, flucModel, G4VProcess::SetProcessSubType(), G4VEnergyLossProcess::SetSecondaryParticle(), theElectron, and G4VProcess::verboseLevel.
G4ePolarizedIonisation::~G4ePolarizedIonisation () virtual
Definition at line 87 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 87 of file G4ePolarizedIonisation.cc
References CleanTables().
G4ePolarizedIonisation::G4ePolarizedIonisation (const G4ePolarizedIonisation &) private delete
Member Function Documentation
void G4ePolarizedIonisation::BuildAsymmetryTables (const G4ParticleDefinition & part) private
Definition at line 295 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 295 of file G4ePolarizedIonisation.cc
References CleanTables(), ComputeAsymmetry(), G4PhysicsVector::Energy(), G4ProductionCutsTable::GetEnergyCutsVector(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsVector::GetVectorLength(), G4PhysicsTable::insertAt(), G4VEnergyLossProcess::LambdaPhysicsVector(), G4PhysicsTableHelper::PreparePhysicsTable(), G4PhysicsVector::PutValue(), theAsymmetryTable, and theTransverseAsymmetryTable.
Referenced by BuildPhysicsTable().
void G4ePolarizedIonisation::BuildPhysicsTable (const G4ParticleDefinition & part) override protected virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 281 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 281 of file G4ePolarizedIonisation.cc
References BuildAsymmetryTables(), G4VEnergyLossProcess::BuildPhysicsTable(), and G4VProcess::GetMasterProcess().
void G4ePolarizedIonisation::CleanTables () private
Definition at line 94 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 94 of file G4ePolarizedIonisation.cc
References G4PhysicsTable::clearAndDestroy(), theAsymmetryTable, and theTransverseAsymmetryTable.
Referenced by BuildAsymmetryTables(), and ~G4ePolarizedIonisation().
G4double G4ePolarizedIonisation::ComputeAsymmetry (G4double energy, const G4MaterialCutsCouple * couple, const G4ParticleDefinition & particle, G4double cut, G4double & tasm) private
Definition at line 335 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 335 of file G4ePolarizedIonisation.cc
References G4VEmModel::CrossSection(), emModel, G4cout, isElectron, G4PolarizedMollerBhabhaModel::SetBeamPolarization(), G4PolarizedMollerBhabhaModel::SetTargetPolarization(), and theTargetPolarization.
Referenced by BuildAsymmetryTables().
G4double G4ePolarizedIonisation::ComputeSaturationFactor (const G4Track & aTrack) private
Definition at line 211 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 211 of file G4ePolarizedIonisation.cc
References G4VEnergyLossProcess::CurrentMaterialCutsCoupleIndex(), energy, G4cout, G4endl, G4Exception(), G4Track::GetDynamicParticle(), G4PolarizationManager::GetInstance(), G4DynamicParticle::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4PolarizationHelper::GetParticleFrameX(), G4PolarizationHelper::GetParticleFrameY(), G4Track::GetPolarization(), G4Track::GetVolume(), G4PolarizationManager::GetVolumePolarization(), G4PolarizationManager::IsPolarized(), G4StokesVector::IsZero(), JustWarning, MeV, G4PhysicsVector::Value(), G4VProcess::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GetMeanFreePath(), and PostStepGetPhysicalInteractionLength().
G4double G4ePolarizedIonisation::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 156 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 156 of file G4ePolarizedIonisation.cc
References ComputeSaturationFactor(), DBL_MAX, G4cout, G4endl, G4VEnergyLossProcess::GetMeanFreePath(), mfp, mm, theAsymmetryTable, theTransverseAsymmetryTable, and G4VProcess::verboseLevel.
void G4ePolarizedIonisation::InitialiseEnergyLossProcess (const G4ParticleDefinition * part, const G4ParticleDefinition *) override protected virtual
Implements G4VEnergyLossProcess.
Definition at line 127 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 127 of file G4ePolarizedIonisation.cc
References G4VEnergyLossProcess::AddEmModel(), emModel, flucModel, G4VEnergyLossProcess::FluctModel(), G4EmParameters::Instance(), isElectron, isInitialised, G4EmParameters::MaxKinEnergy(), G4EmParameters::MinKinEnergy(), G4Positron::Positron(), G4VEnergyLossProcess::SetEmModel(), G4VEnergyLossProcess::SetFluctModel(), G4VEmModel::SetHighEnergyLimit(), and G4VEmModel::SetLowEnergyLimit().
G4bool G4ePolarizedIonisation::IsApplicable (const G4ParticleDefinition & p) override virtual
Implements G4VEnergyLossProcess.
Definition at line 121 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ePolarizedIonisation.cc
References G4Electron::Electron(), and G4Positron::Positron().
G4double G4ePolarizedIonisation::MinPrimaryEnergy (const G4ParticleDefinition * , const G4Material * , G4double cut) override protected virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 111 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ePolarizedIonisation.cc
References isElectron, and x.
G4ePolarizedIonisation& G4ePolarizedIonisation::operator= (const G4ePolarizedIonisation & right) private delete
G4double G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 174 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 174 of file G4ePolarizedIonisation.cc
References ComputeSaturationFactor(), G4VProcess::currentInteractionLength, DBL_MAX, G4cout, G4endl, max, mm, G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), theAsymmetryTable, G4VProcess::theNumberOfInteractionLengthLeft, theTransverseAsymmetryTable, G4VProcess::verboseLevel, and x.
void G4ePolarizedIonisation::PrintInfo () override virtual
Reimplemented from G4VEnergyLossProcess.
Definition at line 151 of file G4ePolarizedIonisation.cc.
View newest version in sPHENIX GitHub at line 151 of file G4ePolarizedIonisation.cc
Member Data Documentation
G4PolarizedMollerBhabhaModel* G4ePolarizedIonisation::emModel private
Definition at line 119 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ePolarizedIonisation.hh
Referenced by ComputeAsymmetry(), G4ePolarizedIonisation(), and InitialiseEnergyLossProcess().
G4VEmFluctuationModel* G4ePolarizedIonisation::flucModel private
Definition at line 118 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ePolarizedIonisation.hh
Referenced by G4ePolarizedIonisation(), and InitialiseEnergyLossProcess().
G4bool G4ePolarizedIonisation::isElectron private
Definition at line 121 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ePolarizedIonisation.hh
Referenced by ComputeAsymmetry(), InitialiseEnergyLossProcess(), and MinPrimaryEnergy().
G4bool G4ePolarizedIonisation::isInitialised private
Definition at line 122 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ePolarizedIonisation.hh
Referenced by InitialiseEnergyLossProcess().
G4PhysicsTable* G4ePolarizedIonisation::theAsymmetryTable private
Definition at line 127 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ePolarizedIonisation.hh
Referenced by BuildAsymmetryTables(), CleanTables(), GetMeanFreePath(), and PostStepGetPhysicalInteractionLength().
G4ParticleDefinition* G4ePolarizedIonisation::theElectron private
Definition at line 117 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ePolarizedIonisation.hh
Referenced by G4ePolarizedIonisation().
G4ThreeVector G4ePolarizedIonisation::theTargetPolarization private
Definition at line 125 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ePolarizedIonisation.hh
Referenced by ComputeAsymmetry().
G4PhysicsTable* G4ePolarizedIonisation::theTransverseAsymmetryTable private
Definition at line 128 of file G4ePolarizedIonisation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ePolarizedIonisation.hh
Referenced by BuildAsymmetryTables(), CleanTables(), GetMeanFreePath(), and PostStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4ePolarizedIonisation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4ePolarizedIonisation.cc