ECCE @ EIC Software: G4VAngularDistribution Class Reference
G4VAngularDistribution Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VAngularDistribution.hh>
Public Member Functions
G4VAngularDistribution ()
virtual ~G4VAngularDistribution ()
virtual G4double CosTheta (G4double s, G4double m1, G4double m2) const =0
virtual G4double Phi () const
Detailed Description
Definition at line 54 of file G4VAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VAngularDistribution.hh
Constructor & Destructor Documentation
G4VAngularDistribution::G4VAngularDistribution () inline
Definition at line 60 of file G4VAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VAngularDistribution.hh
virtual G4VAngularDistribution::~G4VAngularDistribution () inline virtual
Definition at line 62 of file G4VAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VAngularDistribution.hh
Member Function Documentation
virtual G4double G4VAngularDistribution::CosTheta (G4double s, G4double m1, G4double m2) const pure virtual
Implemented in G4AngularDistributionNP, G4AngularDistributionPP, and G4AngularDistribution.
Referenced by G4VElasticCollision::FinalState(), and G4VScatteringCollision::FinalState().
virtual G4double G4VAngularDistribution::Phi () const inline virtual
Reimplemented in G4AngularDistributionNP, and G4AngularDistributionPP.
Definition at line 66 of file G4VAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VAngularDistribution.hh
References G4UniformRand, and CLHEP::pi.
Referenced by G4VElasticCollision::FinalState(), and G4VScatteringCollision::FinalState().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VAngularDistribution.hh