ECCE @ EIC Software: CexmcEnergyDepositInCalorimeter Class Reference
CexmcEnergyDepositInCalorimeter Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEnergyDepositInCalorimeter.hh>
Public Member Functions
CexmcEnergyDepositInCalorimeter (const G4String &name, const CexmcSetup *setup)
void PrintAll (void)
Public Member Functions inherited from CexmcEnergyDepositInLeftRightSet
CexmcEnergyDepositInLeftRightSet (const G4String &name, const CexmcSetup *setup)
void PrintAll (void)
Public Member Functions inherited from CexmcSimpleEnergyDeposit
CexmcSimpleEnergyDeposit (const G4String &name)
void Initialize (G4HCofThisEvent *hcOfThisEvent)
void EndOfEvent (G4HCofThisEvent *hcOfThisEvent)
void DrawAll (void)
void PrintAll (void)
void clear (void)
Public Member Functions inherited from CexmcPrimitiveScorer
CexmcPrimitiveScorer (const G4String &name)
virtual ~CexmcPrimitiveScorer ()
void InitializeMessenger (void)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Static Public Member Functions
static G4int GetRow (G4int index)
static G4int GetColumn (G4int index)
static G4int GetCopyDepth1BitsOffset (void)
Static Public Member Functions inherited from CexmcEnergyDepositInLeftRightSet
static CexmcSide GetSide (G4int index)
static G4int GetLeftRightBitsOffset (void)
Protected Member Functions
G4int GetIndex (G4Step *step)
Protected Member Functions inherited from CexmcEnergyDepositInLeftRightSet
G4int GetIndex (G4Step *step)
Protected Member Functions inherited from CexmcSimpleEnergyDeposit
G4int GetIndex (G4Step *step)
G4bool ProcessHits (G4Step *step, G4TouchableHistory *tHistory)
Protected Member Functions inherited from CexmcPrimitiveScorer
void PrintHeader (G4int nmbOfEntries) const
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Static Protected Attributes
static const G4int copyDepth1BitsOffset = 8
Static Protected Attributes inherited from CexmcEnergyDepositInLeftRightSet
static const G4int leftRightBitsOffset = 16
Additional Inherited Members
Protected Attributes inherited from CexmcEnergyDepositInLeftRightSet
const CexmcSetup * setup
Detailed Description
Definition at line 52 of file CexmcEnergyDepositInCalorimeter.hh.
View newest version in sPHENIX GitHub at line 52 of file CexmcEnergyDepositInCalorimeter.hh
Constructor & Destructor Documentation
CexmcEnergyDepositInCalorimeter::CexmcEnergyDepositInCalorimeter (const G4String & name, const CexmcSetup * setup)
Definition at line 54 of file CexmcEnergyDepositInCalorimeter.cc.
View newest version in sPHENIX GitHub at line 54 of file CexmcEnergyDepositInCalorimeter.cc
Member Function Documentation
G4int CexmcEnergyDepositInCalorimeter::GetColumn (G4int index) inline static
Definition at line 84 of file CexmcEnergyDepositInCalorimeter.hh.
View newest version in sPHENIX GitHub at line 84 of file CexmcEnergyDepositInCalorimeter.hh
References copyDepth1BitsOffset.
Referenced by CexmcEnergyDepositDigitizer::Digitize().
G4int CexmcEnergyDepositInCalorimeter::GetCopyDepth1BitsOffset (void) inline static
Definition at line 91 of file CexmcEnergyDepositInCalorimeter.hh.
View newest version in sPHENIX GitHub at line 91 of file CexmcEnergyDepositInCalorimeter.hh
References copyDepth1BitsOffset.
G4int CexmcEnergyDepositInCalorimeter::GetIndex (G4Step * step) protected virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 61 of file CexmcEnergyDepositInCalorimeter.cc.
View newest version in sPHENIX GitHub at line 61 of file CexmcEnergyDepositInCalorimeter.cc
References copyDepth1BitsOffset, G4Step::GetPreStepPoint(), CexmcSetup::IsRightCalorimeter(), CexmcEnergyDepositInLeftRightSet::leftRightBitsOffset, and CexmcEnergyDepositInLeftRightSet::setup.
G4int CexmcEnergyDepositInCalorimeter::GetRow (G4int index) inline static
Definition at line 76 of file CexmcEnergyDepositInCalorimeter.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcEnergyDepositInCalorimeter.hh
References copyDepth1BitsOffset, and CexmcEnergyDepositInLeftRightSet::leftRightBitsOffset.
Referenced by CexmcEnergyDepositDigitizer::Digitize().
void CexmcEnergyDepositInCalorimeter::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 81 of file CexmcEnergyDepositInCalorimeter.cc.
View newest version in sPHENIX GitHub at line 81 of file CexmcEnergyDepositInCalorimeter.cc
References copyDepth1BitsOffset, G4VTHitsMap< T, Map_t >::entries(), CexmcSimpleEnergyDeposit::eventMap, G4BestUnit, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), CexmcEnergyDepositInLeftRightSet::leftRightBitsOffset, and CexmcPrimitiveScorer::PrintHeader().
Member Data Documentation
const G4int CexmcEnergyDepositInCalorimeter::copyDepth1BitsOffset = 8 static protected
Definition at line 72 of file CexmcEnergyDepositInCalorimeter.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcEnergyDepositInCalorimeter.hh
Referenced by GetColumn(), GetCopyDepth1BitsOffset(), GetIndex(), GetRow(), and PrintAll().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEnergyDepositInCalorimeter.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcEnergyDepositInCalorimeter.cc