ECCE @ EIC Software: G4EmLowEParameters Class Reference
G4EmLowEParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmLowEParameters.hh>
Public Member Functions
G4EmLowEParameters ()
~G4EmLowEParameters ()
void Initialise ()
void SetFluo (G4bool val)
G4bool Fluo () const
void SetBeardenFluoDir (G4bool val)
G4bool BeardenFluoDir () const
void SetAuger (G4bool val)
G4bool Auger () const
void SetPixe (G4bool val)
G4bool Pixe () const
void SetDeexcitationIgnoreCut (G4bool val)
G4bool DeexcitationIgnoreCut () const
void SetDNAFast (G4bool val)
G4bool DNAFast () const
void SetDNAStationary (G4bool val)
G4bool DNAStationary () const
void SetDNAElectronMsc (G4bool val)
G4bool DNAElectronMsc () const
void SetDNAeSolvationSubType (G4DNAModelSubType val)
G4DNAModelSubType DNAeSolvationSubType () const
void SetPIXECrossSectionModel (const G4String &)
const G4String & PIXECrossSectionModel ()
void SetPIXEElectronCrossSectionModel (const G4String &)
const G4String & PIXEElectronCrossSectionModel ()
void AddMicroElec (const G4String &region)
const std::vector< G4String > & RegionsMicroElec () const
void AddDNA (const G4String &region, const G4String &type)
const std::vector< G4String > & RegionsDNA () const
const std::vector< G4String > & TypesDNA () const
void SetDeexActiveRegion (const G4String &region, G4bool fdeex, G4bool fauger, G4bool fpixe)
void DefineRegParamForDeex (G4VAtomDeexcitation *) const
G4EmLowEParameters (G4EmLowEParameters &)=delete
G4EmLowEParameters & operator= (const G4EmLowEParameters &right)=delete
Private Member Functions
G4String CheckRegion (const G4String &) const
void PrintWarning (G4ExceptionDescription &ed) const
Private Attributes
G4EmLowEParametersMessenger * theMessenger
G4bool fluo
G4bool beardenFluoDir
G4bool auger
G4bool pixe
G4bool deexIgnoreCut
G4bool dnaFast
G4bool dnaStationary
G4bool dnaMsc
G4DNAModelSubType dnaElectronSolvation
G4String namePIXE
G4String nameElectronPIXE
std::vector< G4String > m_regnamesME
std::vector< G4String > m_regnamesDNA
std::vector< G4String > m_typesDNA
std::vector< G4String > m_regnamesDeex
std::vector< G4bool > m_fluo
std::vector< G4bool > m_auger
std::vector< G4bool > m_pixe
Detailed Description
Definition at line 58 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 58 of file G4EmLowEParameters.hh
Constructor & Destructor Documentation
G4EmLowEParameters::G4EmLowEParameters () explicit
Definition at line 53 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 53 of file G4EmLowEParameters.cc
References Initialise(), and theMessenger.
G4EmLowEParameters::~G4EmLowEParameters ()
Definition at line 61 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 61 of file G4EmLowEParameters.cc
References theMessenger.
G4EmLowEParameters::G4EmLowEParameters (G4EmLowEParameters &) delete
Member Function Documentation
void G4EmLowEParameters::AddDNA (const G4String & region, const G4String & type)
Definition at line 228 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 228 of file G4EmLowEParameters.cc
References CheckRegion(), m_regnamesDNA, m_typesDNA, and r.
Referenced by G4EmParameters::AddDNA(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::AddMicroElec (const G4String & region)
Definition at line 213 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 213 of file G4EmLowEParameters.cc
References CheckRegion(), m_regnamesME, and r.
Referenced by G4EmParameters::AddMicroElec(), and G4EmLowEParametersMessenger::SetNewValue().
G4bool G4EmLowEParameters::Auger () const
Definition at line 113 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 113 of file G4EmLowEParameters.cc
References auger.
Referenced by G4EmParameters::Auger(), G4EmParameters::AugerCascade(), and G4EmParameters::StreamInfo().
G4bool G4EmLowEParameters::BeardenFluoDir () const
Definition at line 102 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 102 of file G4EmLowEParameters.cc
References beardenFluoDir.
Referenced by G4EmParameters::BeardenFluoDir(), and G4EmParameters::StreamInfo().
G4String G4EmLowEParameters::CheckRegion (const G4String & reg) const private
Definition at line 204 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 204 of file G4EmLowEParameters.cc
References r, and reg.
Referenced by AddDNA(), AddMicroElec(), and SetDeexActiveRegion().
G4bool G4EmLowEParameters::DeexcitationIgnoreCut () const
Definition at line 134 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 134 of file G4EmLowEParameters.cc
References deexIgnoreCut.
Referenced by G4EmParameters::DeexcitationIgnoreCut(), and G4EmParameters::StreamInfo().
void G4EmLowEParameters::DefineRegParamForDeex (G4VAtomDeexcitation * ptr) const
Definition at line 277 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 277 of file G4EmLowEParameters.cc
References m_auger, m_fluo, m_pixe, m_regnamesDeex, n, and G4VAtomDeexcitation::SetDeexcitationActiveRegion().
Referenced by G4EmParameters::DefineRegParamForDeex().
G4bool G4EmLowEParameters::DNAElectronMsc () const
Definition at line 164 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 164 of file G4EmLowEParameters.cc
References dnaMsc.
Referenced by G4EmParameters::DNAElectronMsc(), and G4EmParameters::StreamInfo().
G4DNAModelSubType G4EmLowEParameters::DNAeSolvationSubType () const
Definition at line 174 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 174 of file G4EmLowEParameters.cc
References dnaElectronSolvation.
Referenced by G4EmParameters::DNAeSolvationSubType(), and G4EmParameters::StreamInfo().
G4bool G4EmLowEParameters::DNAFast () const
Definition at line 144 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 144 of file G4EmLowEParameters.cc
References dnaFast.
Referenced by G4EmParameters::DNAFast(), and G4EmParameters::StreamInfo().
G4bool G4EmLowEParameters::DNAStationary () const
Definition at line 154 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 154 of file G4EmLowEParameters.cc
References dnaStationary.
Referenced by G4EmParameters::DNAStationary(), and G4EmParameters::StreamInfo().
G4bool G4EmLowEParameters::Fluo () const
Definition at line 92 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 92 of file G4EmLowEParameters.cc
References fluo.
Referenced by G4EmParameters::Fluo(), and G4EmParameters::StreamInfo().
void G4EmLowEParameters::Initialise ()
Definition at line 68 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 68 of file G4EmLowEParameters.cc
References auger, beardenFluoDir, deexIgnoreCut, dnaElectronSolvation, dnaFast, dnaMsc, dnaStationary, fluo, fMeesungnoen2002eSolvation, nameElectronPIXE, namePIXE, and pixe.
Referenced by G4EmLowEParameters(), and G4EmParameters::SetDefaults().
G4EmLowEParameters& G4EmLowEParameters::operator= (const G4EmLowEParameters & right) delete
G4bool G4EmLowEParameters::Pixe () const
Definition at line 124 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 124 of file G4EmLowEParameters.cc
References pixe.
Referenced by G4EmParameters::Pixe(), and G4EmParameters::StreamInfo().
const G4String & G4EmLowEParameters::PIXECrossSectionModel ()
Definition at line 184 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 184 of file G4EmLowEParameters.cc
References namePIXE.
Referenced by G4EmParameters::PIXECrossSectionModel(), and G4EmParameters::StreamInfo().
const G4String & G4EmLowEParameters::PIXEElectronCrossSectionModel ()
Definition at line 194 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 194 of file G4EmLowEParameters.cc
References nameElectronPIXE.
Referenced by G4EmParameters::PIXEElectronCrossSectionModel(), and G4EmParameters::StreamInfo().
void G4EmLowEParameters::PrintWarning (G4ExceptionDescription & ed) const private
Definition at line 199 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 199 of file G4EmLowEParameters.cc
References G4Exception(), and JustWarning.
const std::vector< G4String > & G4EmLowEParameters::RegionsDNA () const
Definition at line 239 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 239 of file G4EmLowEParameters.cc
References m_regnamesDNA.
Referenced by G4EmParameters::RegionsDNA().
const std::vector< G4String > & G4EmLowEParameters::RegionsMicroElec () const
Definition at line 223 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 223 of file G4EmLowEParameters.cc
References m_regnamesME.
Referenced by G4EmParameters::RegionsMicroElec().
void G4EmLowEParameters::SetAuger (G4bool val)
Definition at line 107 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 107 of file G4EmLowEParameters.cc
References auger, and fluo.
Referenced by G4EmParameters::SetAuger(), G4EmParameters::SetAugerCascade(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetBeardenFluoDir (G4bool val)
Definition at line 97 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 97 of file G4EmLowEParameters.cc
References beardenFluoDir.
Referenced by G4EmParameters::SetBeardenFluoDir(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetDeexActiveRegion (const G4String & region, G4bool fdeex, G4bool fauger, G4bool fpixe)
Definition at line 250 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 250 of file G4EmLowEParameters.cc
References CheckRegion(), fluo, m_auger, m_fluo, m_pixe, m_regnamesDeex, and r.
Referenced by G4EmParameters::SetDeexActiveRegion(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetDeexcitationIgnoreCut (G4bool val)
Definition at line 129 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 129 of file G4EmLowEParameters.cc
References deexIgnoreCut.
Referenced by G4EmParameters::SetDeexcitationIgnoreCut(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetDNAElectronMsc (G4bool val)
Definition at line 159 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 159 of file G4EmLowEParameters.cc
References dnaMsc.
Referenced by G4EmParameters::SetDNAElectronMsc(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetDNAeSolvationSubType (G4DNAModelSubType val)
Definition at line 169 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 169 of file G4EmLowEParameters.cc
References dnaElectronSolvation.
Referenced by G4EmParameters::SetDNAeSolvationSubType(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetDNAFast (G4bool val)
Definition at line 139 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 139 of file G4EmLowEParameters.cc
References dnaFast.
Referenced by G4EmParameters::SetDNAFast(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetDNAStationary (G4bool val)
Definition at line 149 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 149 of file G4EmLowEParameters.cc
References dnaStationary.
Referenced by G4EmParameters::SetDNAStationary(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetFluo (G4bool val)
Definition at line 87 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 87 of file G4EmLowEParameters.cc
References fluo.
Referenced by G4EmParameters::SetFluo(), and G4EmLowEParametersMessenger::SetNewValue().
void G4EmLowEParameters::SetPixe (G4bool val)
Definition at line 118 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 118 of file G4EmLowEParameters.cc
References fluo, and pixe.
Referenced by G4EmLowEParametersMessenger::SetNewValue(), and G4EmParameters::SetPixe().
void G4EmLowEParameters::SetPIXECrossSectionModel (const G4String & sss)
Definition at line 179 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 179 of file G4EmLowEParameters.cc
References namePIXE, and sss.
Referenced by G4EmLowEParametersMessenger::SetNewValue(), and G4EmParameters::SetPIXECrossSectionModel().
void G4EmLowEParameters::SetPIXEElectronCrossSectionModel (const G4String & sss)
Definition at line 189 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 189 of file G4EmLowEParameters.cc
References nameElectronPIXE, and sss.
Referenced by G4EmLowEParametersMessenger::SetNewValue(), and G4EmParameters::SetPIXEElectronCrossSectionModel().
const std::vector< G4String > & G4EmLowEParameters::TypesDNA () const
Definition at line 244 of file G4EmLowEParameters.cc.
View newest version in sPHENIX GitHub at line 244 of file G4EmLowEParameters.cc
References m_typesDNA.
Referenced by G4EmParameters::TypesDNA().
Member Data Documentation
G4bool G4EmLowEParameters::auger private
Definition at line 132 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 132 of file G4EmLowEParameters.hh
Referenced by Auger(), Initialise(), and SetAuger().
G4bool G4EmLowEParameters::beardenFluoDir private
Definition at line 131 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 131 of file G4EmLowEParameters.hh
Referenced by BeardenFluoDir(), Initialise(), and SetBeardenFluoDir().
G4bool G4EmLowEParameters::deexIgnoreCut private
Definition at line 134 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 134 of file G4EmLowEParameters.hh
Referenced by DeexcitationIgnoreCut(), Initialise(), and SetDeexcitationIgnoreCut().
G4DNAModelSubType G4EmLowEParameters::dnaElectronSolvation private
Definition at line 140 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 140 of file G4EmLowEParameters.hh
Referenced by DNAeSolvationSubType(), Initialise(), and SetDNAeSolvationSubType().
G4bool G4EmLowEParameters::dnaFast private
Definition at line 136 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 136 of file G4EmLowEParameters.hh
Referenced by DNAFast(), Initialise(), and SetDNAFast().
G4bool G4EmLowEParameters::dnaMsc private
Definition at line 138 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 138 of file G4EmLowEParameters.hh
Referenced by DNAElectronMsc(), Initialise(), and SetDNAElectronMsc().
G4bool G4EmLowEParameters::dnaStationary private
Definition at line 137 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 137 of file G4EmLowEParameters.hh
Referenced by DNAStationary(), Initialise(), and SetDNAStationary().
G4bool G4EmLowEParameters::fluo private
Definition at line 130 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 130 of file G4EmLowEParameters.hh
Referenced by Fluo(), Initialise(), SetAuger(), SetDeexActiveRegion(), SetFluo(), and SetPixe().
std::vector<G4bool> G4EmLowEParameters::m_auger private
Definition at line 152 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 152 of file G4EmLowEParameters.hh
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
std::vector<G4bool> G4EmLowEParameters::m_fluo private
Definition at line 151 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 151 of file G4EmLowEParameters.hh
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
std::vector<G4bool> G4EmLowEParameters::m_pixe private
Definition at line 153 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 153 of file G4EmLowEParameters.hh
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
std::vector<G4String> G4EmLowEParameters::m_regnamesDeex private
Definition at line 150 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 150 of file G4EmLowEParameters.hh
Referenced by DefineRegParamForDeex(), and SetDeexActiveRegion().
std::vector<G4String> G4EmLowEParameters::m_regnamesDNA private
Definition at line 147 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 147 of file G4EmLowEParameters.hh
Referenced by AddDNA(), and RegionsDNA().
std::vector<G4String> G4EmLowEParameters::m_regnamesME private
Definition at line 145 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 145 of file G4EmLowEParameters.hh
Referenced by AddMicroElec(), and RegionsMicroElec().
std::vector<G4String> G4EmLowEParameters::m_typesDNA private
Definition at line 148 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 148 of file G4EmLowEParameters.hh
Referenced by AddDNA(), and TypesDNA().
G4String G4EmLowEParameters::nameElectronPIXE private
Definition at line 143 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 143 of file G4EmLowEParameters.hh
Referenced by Initialise(), PIXEElectronCrossSectionModel(), and SetPIXEElectronCrossSectionModel().
G4String G4EmLowEParameters::namePIXE private
Definition at line 142 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 142 of file G4EmLowEParameters.hh
Referenced by Initialise(), PIXECrossSectionModel(), and SetPIXECrossSectionModel().
G4bool G4EmLowEParameters::pixe private
Definition at line 133 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 133 of file G4EmLowEParameters.hh
Referenced by Initialise(), Pixe(), and SetPixe().
G4EmLowEParametersMessenger* G4EmLowEParameters::theMessenger private
Definition at line 128 of file G4EmLowEParameters.hh.
View newest version in sPHENIX GitHub at line 128 of file G4EmLowEParameters.hh
Referenced by G4EmLowEParameters(), and ~G4EmLowEParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmLowEParameters.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmLowEParameters.cc