ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pymodG4geometry.cc File Reference
pymodG4geometry.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4GeometryManager ()
void export_G4VTouchable ()
void export_G4TouchableHistory ()
void export_G4VPhysicalVolume ()
void export_G4PVPlacement ()
void export_G4PVReplica ()
void export_G4LogicalVolume ()
void export_G4Region ()
void export_G4VSolid ()
void export_G4Box ()
void export_G4Cons ()
void export_G4Para ()
void export_G4Torus ()
void export_G4Trd ()
void export_G4Orb ()
void export_G4Sphere ()
void export_G4Trap ()
void export_G4Tubs ()
void export_G4Polycone ()
void export_G4Polyhedra ()
void export_G4EllipticalTube ()
void export_G4Ellipsoid ()
void export_G4EllipticalCone ()
void export_G4Hype ()
void export_G4Tet ()
void export_G4TwistedBox ()
void export_G4TwistedTrap ()
void export_G4TwistedTrd ()
void export_G4TwistedTubs ()
void export_G4BooleanSolid ()
void export_G4UnionSolid ()
void export_G4IntersectionSolid ()
void export_G4SubtractionSolid ()
void export_G4TransportationManager ()
void export_G4Navigator ()
void export_G4FieldManager ()
void export_G4Field ()
void export_G4MagneticField ()
void export_G4UniformMagField ()
void export_G4ChordFinder ()
BOOST_PYTHON_MODULE (G4geometry)
Function Documentation
BOOST_PYTHON_MODULE (G4geometry)
Definition at line 79 of file pymodG4geometry.cc.
View newest version in sPHENIX GitHub at line 79 of file pymodG4geometry.cc
References export_G4BooleanSolid(), export_G4Box(), export_G4ChordFinder(), export_G4Cons(), export_G4Ellipsoid(), export_G4EllipticalCone(), export_G4EllipticalTube(), export_G4Field(), export_G4FieldManager(), export_G4GeometryManager(), export_G4Hype(), export_G4IntersectionSolid(), export_G4LogicalVolume(), export_G4MagneticField(), export_G4Navigator(), export_G4Orb(), export_G4Para(), export_G4Polycone(), export_G4Polyhedra(), export_G4PVPlacement(), export_G4PVReplica(), export_G4Region(), export_G4Sphere(), export_G4SubtractionSolid(), export_G4Tet(), export_G4Torus(), export_G4TouchableHistory(), export_G4TransportationManager(), export_G4Trap(), export_G4Trd(), export_G4Tubs(), export_G4TwistedBox(), export_G4TwistedTrap(), export_G4TwistedTrd(), export_G4TwistedTubs(), export_G4UniformMagField(), export_G4UnionSolid(), export_G4VPhysicalVolume(), export_G4VSolid(), and export_G4VTouchable().
void export_G4BooleanSolid ()
Definition at line 39 of file pyG4BooleanSolid.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4BooleanSolid.cc
References G4BooleanSolid::GetAreaAccuracy(), G4BooleanSolid::GetAreaStatistics(), G4BooleanSolid::GetCubVolEpsilon(), G4BooleanSolid::GetCubVolStatistics(), G4BooleanSolid::GetPointOnSurface(), G4BooleanSolid::SetAreaAccuracy(), G4BooleanSolid::SetAreaStatistics(), G4BooleanSolid::SetCubVolEpsilon(), and G4BooleanSolid::SetCubVolStatistics().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Box ()
Definition at line 54 of file pyG4Box.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Box.cc
References pyG4Box::CreateBox(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ChordFinder ()
Definition at line 51 of file pyG4ChordFinder.cc.
View newest version in sPHENIX GitHub at line 51 of file pyG4ChordFinder.cc
References G4ChordFinder::GetDeltaChord(), G4ChordFinder::SetDeltaChord(), and G4ChordFinder::SetVerbose().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Cons ()
Definition at line 55 of file pyG4Cons.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4Cons.cc
References pyG4Cons::CreateCons(), G4Cons::GetDeltaPhiAngle(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Cons::GetStartPhiAngle(), G4Cons::GetZHalfLength(), init(), G4Cons::SetDeltaPhiAngle(), G4Cons::SetInnerRadiusMinusZ(), G4Cons::SetInnerRadiusPlusZ(), G4Cons::SetOuterRadiusMinusZ(), G4Cons::SetOuterRadiusPlusZ(), G4Cons::SetStartPhiAngle(), and G4Cons::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Ellipsoid ()
Definition at line 61 of file pyG4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 61 of file pyG4Ellipsoid.cc
References pyG4Ellipsoid::CreateEllipsoid(), G4Ellipsoid::GetSemiAxisMax(), G4Ellipsoid::GetZBottomCut(), G4Ellipsoid::GetZTopCut(), init(), G4Ellipsoid::SetSemiAxis(), and G4Ellipsoid::SetZCuts().
Referenced by BOOST_PYTHON_MODULE().
void export_G4EllipticalCone ()
Definition at line 57 of file pyG4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 57 of file pyG4EllipticalCone.cc
References pyG4EllipticalCone::CreateEllipticalCone(), G4EllipticalCone::GetSemiAxisMax(), G4EllipticalCone::GetZTopCut(), G4EllipticalCone::SetSemiAxis(), and G4EllipticalCone::SetZCut().
Referenced by BOOST_PYTHON_MODULE().
void export_G4EllipticalTube ()
Definition at line 56 of file pyG4EllipticalTube.cc.
View newest version in sPHENIX GitHub at line 56 of file pyG4EllipticalTube.cc
References pyG4EllipticalTube::CreateEllipticalTube(), G4EllipticalTube::GetDx(), G4EllipticalTube::GetDy(), G4EllipticalTube::GetDz(), G4EllipticalTube::SetDx(), G4EllipticalTube::SetDy(), and G4EllipticalTube::SetDz().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Field ()
Definition at line 39 of file pyG4Field.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4Field.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4FieldManager ()
Definition at line 62 of file pyG4FieldManager.cc.
View newest version in sPHENIX GitHub at line 62 of file pyG4FieldManager.cc
References G4FieldManager::ConfigureForTrack(), G4FieldManager::CreateChordFinder(), G4FieldManager::DoesFieldChangeEnergy(), G4FieldManager::DoesFieldExist(), pyG4FieldManager::f1_GetChordFinder, pyG4FieldManager::f2_GetChordFinder, G4FieldManager::GetDeltaIntersection(), G4FieldManager::GetDeltaOneStep(), G4FieldManager::GetDetectorField(), G4FieldManager::GetMaximumEpsilonStep(), G4FieldManager::GetMinimumEpsilonStep(), G4FieldManager::SetAccuraciesWithDeltaOneStep(), G4FieldManager::SetChordFinder(), G4FieldManager::SetDeltaIntersection(), G4FieldManager::SetDeltaOneStep(), G4FieldManager::SetDetectorField(), G4FieldManager::SetFieldChangesEnergy(), G4FieldManager::SetMaximumEpsilonStep(), and G4FieldManager::SetMinimumEpsilonStep().
Referenced by BOOST_PYTHON_MODULE().
void export_G4GeometryManager ()
Definition at line 52 of file pyG4GeometryManager.cc.
View newest version in sPHENIX GitHub at line 52 of file pyG4GeometryManager.cc
References G4GeometryManager::CloseGeometry(), G4GeometryManager::GetInstance(), G4GeometryManager::IsGeometryClosed(), G4GeometryManager::OpenGeometry(), and G4GeometryManager::SetWorldMaximumExtent().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Hype ()
Definition at line 61 of file pyG4Hype.cc.
View newest version in sPHENIX GitHub at line 61 of file pyG4Hype.cc
References pyG4Hype::CreateHype(), G4Hype::GetInnerRadius(), G4Hype::GetInnerStereo(), G4Hype::GetOuterRadius(), G4Hype::GetOuterStereo(), G4Hype::GetZHalfLength(), init(), G4Hype::SetInnerRadius(), G4Hype::SetInnerStereo(), G4Hype::SetOuterRadius(), G4Hype::SetOuterStereo(), and G4Hype::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4IntersectionSolid ()
Definition at line 39 of file pyG4IntersctionSolid.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4IntersctionSolid.cc
References init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4LogicalVolume ()
Definition at line 71 of file pyG4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 71 of file pyG4LogicalVolume.cc
References G4LogicalVolume::AddDaughter(), G4LogicalVolume::ClearDaughters(), pyG4LogicalVolume::f1_GetSolid, pyG4LogicalVolume::f1_SetSolid, pyG4LogicalVolume::f1_SetVisAttributes, pyG4LogicalVolume::f2_SetVisAttributes, G4LogicalVolume::GetBiasWeight(), G4LogicalVolume::GetDaughter(), G4LogicalVolume::GetFastSimulationManager(), G4LogicalVolume::GetFieldManager(), G4LogicalVolume::GetMass(), G4LogicalVolume::GetMaterial(), G4LogicalVolume::GetMaterialCutsCouple(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSensitiveDetector(), G4LogicalVolume::GetSmartless(), G4LogicalVolume::GetUserLimits(), G4LogicalVolume::GetVisAttributes(), G4LogicalVolume::GetVoxelHeader(), init(), G4LogicalVolume::IsAncestor(), G4LogicalVolume::IsDaughter(), G4LogicalVolume::IsRegion(), G4LogicalVolume::IsRootRegion(), G4LogicalVolume::IsToOptimise(), G4LogicalVolume::PropagateRegion(), G4LogicalVolume::RemoveDaughter(), G4LogicalVolume::SetBiasWeight(), G4LogicalVolume::SetFieldManager(), G4LogicalVolume::SetMaterial(), G4LogicalVolume::SetMaterialCutsCouple(), G4LogicalVolume::SetName(), G4LogicalVolume::SetOptimisation(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetRegionRootFlag(), G4LogicalVolume::SetSensitiveDetector(), G4LogicalVolume::SetSmartless(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVoxelHeader(), G4LogicalVolume::TotalVolumeEntities(), and G4LogicalVolume::UpdateMaterial().
Referenced by BOOST_PYTHON_MODULE().
void export_G4MagneticField ()
Definition at line 90 of file pyG4MagneticField.cc.
View newest version in sPHENIX GitHub at line 90 of file pyG4MagneticField.cc
References G4MagneticField::DoesFieldChangeEnergy(), and pyG4MagneticField::f1_GetFieldValue.
Referenced by BOOST_PYTHON_MODULE().
void export_G4Navigator ()
Definition at line 41 of file pyG4Navigator.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4Navigator.cc
References G4Navigator::GetVerboseLevel(), G4Navigator::GetWorldVolume(), G4Navigator::IsActive(), G4Navigator::PrintState(), and G4Navigator::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Orb ()
Definition at line 53 of file pyG4Orb.cc.
View newest version in sPHENIX GitHub at line 53 of file pyG4Orb.cc
References pyG4Orb::CreateOrb(), G4Orb::GetRadius(), and G4Orb::SetRadius().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Para ()
Definition at line 55 of file pyG4Para.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4Para.cc
References pyG4Para::CreatePara(), G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetXHalfLength(), G4Para::GetYHalfLength(), G4Para::GetZHalfLength(), init(), G4Para::SetAllParameters(), G4Para::SetAlpha(), G4Para::SetTanAlpha(), G4Para::SetThetaAndPhi(), G4Para::SetXHalfLength(), G4Para::SetYHalfLength(), and G4Para::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Polycone ()
Definition at line 91 of file pyG4Polycone.cc.
View newest version in sPHENIX GitHub at line 91 of file pyG4Polycone.cc
References pyG4Polycone::f1_CreatePolycone(), pyG4Polycone::f2_CreatePolycone(), G4Polycone::GetEndPhi(), G4Polycone::GetNumRZCorner(), G4Polycone::GetStartPhi(), and G4Polycone::IsOpen().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Polyhedra ()
Definition at line 92 of file pyG4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 92 of file pyG4Polyhedra.cc
References pyG4Polyhedra::f1_CreatePolyhedra(), pyG4Polyhedra::f2_CreatePolyhedra(), G4Polyhedra::GetEndPhi(), G4Polyhedra::GetNumRZCorner(), G4Polyhedra::GetNumSide(), G4Polyhedra::GetStartPhi(), G4Polyhedra::IsGeneric(), and G4Polyhedra::IsOpen().
Referenced by BOOST_PYTHON_MODULE().
void export_G4PVPlacement ()
Definition at line 53 of file pyG4PVPlacement.cc.
View newest version in sPHENIX GitHub at line 53 of file pyG4PVPlacement.cc
References G4PVPlacement::CheckOverlaps(), G4VERSION_NUMBER, and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4PVReplica ()
Definition at line 40 of file pyG4PVReplica.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4PVReplica.cc
References G4PVReplica::GetMultiplicity(), and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Region ()
Definition at line 46 of file pyG4Region.cc.
View newest version in sPHENIX GitHub at line 46 of file pyG4Region.cc
References G4Region::AddRootLogicalVolume(), G4Region::BelongsTo(), G4Region::ClearFastSimulationManager(), G4Region::ClearMap(), G4Region::ClearMaterialList(), G4Region::FindCouple(), G4Region::GetFastSimulationManager(), G4Region::GetName(), G4Region::GetNumberOfMaterials(), G4Region::GetNumberOfRootVolumes(), G4Region::GetParentRegion(), G4Region::GetProductionCuts(), G4Region::GetUserInformation(), G4Region::GetUserLimits(), G4Region::GetWorldPhysical(), G4Region::IsModified(), G4Region::RegionModified(), G4Region::RegisterMaterialCouplePair(), G4Region::RemoveRootLogicalVolume(), G4Region::ScanVolumeTree(), G4Region::SetFastSimulationManager(), G4Region::SetName(), G4Region::SetProductionCuts(), G4Region::SetUserInformation(), G4Region::SetUserLimits(), G4Region::SetWorld(), and G4Region::UpdateMaterialList().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Sphere ()
Definition at line 56 of file pyG4Sphere.cc.
View newest version in sPHENIX GitHub at line 56 of file pyG4Sphere.cc
References pyG4Sphere::CreateSphere(), G4Sphere::GetDeltaPhiAngle(), G4Sphere::GetDeltaThetaAngle(), G4Sphere::GetInsideRadius(), G4Sphere::GetOuterRadius(), G4Sphere::GetStartPhiAngle(), G4Sphere::GetStartThetaAngle(), init(), G4Sphere::SetDeltaPhiAngle(), G4Sphere::SetDeltaThetaAngle(), G4Sphere::SetInsideRadius(), G4Sphere::SetOuterRadius(), G4Sphere::SetStartPhiAngle(), and G4Sphere::SetStartThetaAngle().
Referenced by BOOST_PYTHON_MODULE().
void export_G4SubtractionSolid ()
Definition at line 39 of file pyG4SubtractionSolid.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4SubtractionSolid.cc
References init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Tet ()
Definition at line 54 of file pyG4Tet.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Tet.cc
References pyG4Tet::CreateTet(), and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Torus ()
Definition at line 54 of file pyG4Torus.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Torus.cc
References pyG4Torus::CreateTorus(), G4Torus::GetDPhi(), G4Torus::GetRmax(), G4Torus::GetRmin(), G4Torus::GetRtor(), G4Torus::GetSPhi(), and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TouchableHistory ()
Definition at line 39 of file pyG4TouchableHistory.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4TouchableHistory.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4TransportationManager ()
Definition at line 41 of file pyG4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4TransportationManager.cc
References G4TransportationManager::GetFieldManager(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetTransportationManager(), G4TransportationManager::SetFieldManager(), G4TransportationManager::SetNavigatorForTracking(), and G4TransportationManager::SetPropagatorInField().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Trap ()
Definition at line 101 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 101 of file pyG4Trap.cc
References pyG4Trap::f1_CreateTrap(), pyG4Trap::f2_CreateTrap(), pyG4Trap::f3_CreateTrap(), pyG4Trap::f4_CreateTrap(), pyG4Trap::f5_CreateTrap(), pyG4Trap::f6_CreateTrap(), G4Trap::GetSidePlane(), G4Trap::GetSymAxis(), G4Trap::GetTanAlpha1(), G4Trap::GetTanAlpha2(), G4Trap::GetXHalfLength1(), G4Trap::GetXHalfLength2(), G4Trap::GetXHalfLength3(), G4Trap::GetXHalfLength4(), G4Trap::GetYHalfLength1(), G4Trap::GetYHalfLength2(), G4Trap::GetZHalfLength(), init(), and G4Trap::SetAllParameters().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Trd ()
Definition at line 54 of file pyG4Trd.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Trd.cc
References pyG4Trd::CreateTrd(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), init(), G4Trd::SetXHalfLength1(), G4Trd::SetXHalfLength2(), G4Trd::SetYHalfLength1(), G4Trd::SetYHalfLength2(), and G4Trd::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Tubs ()
Definition at line 54 of file pyG4Tubs.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Tubs.cc
References pyG4Tubs::CreateTubs(), G4Tubs::GetDeltaPhiAngle(), G4Tubs::GetDPhi(), G4Tubs::GetDz(), G4Tubs::GetInnerRadius(), G4Tubs::GetOuterRadius(), G4Tubs::GetRMax(), G4Tubs::GetRMin(), G4Tubs::GetSPhi(), G4Tubs::GetStartPhiAngle(), G4Tubs::GetZHalfLength(), init(), G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TwistedBox ()
Definition at line 57 of file pyG4TwistedBox.cc.
View newest version in sPHENIX GitHub at line 57 of file pyG4TwistedBox.cc
References pyG4TwistedBox::CreateTwistedBox(), G4TwistedBox::GetPhiTwist(), G4TwistedBox::GetXHalfLength(), G4TwistedBox::GetYHalfLength(), and G4TwistedBox::GetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TwistedTrap ()
Definition at line 69 of file pyG4TwistedTrap.cc.
View newest version in sPHENIX GitHub at line 69 of file pyG4TwistedTrap.cc
References pyG4TwistedTrap::f1_CreateTwistedTrap(), pyG4TwistedTrap::f2_CreateTwistedTrap(), and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TwistedTrd ()
Definition at line 56 of file pyG4TwistedTrd.cc.
View newest version in sPHENIX GitHub at line 56 of file pyG4TwistedTrd.cc
References pyG4TwistedTrd::CreateTwistedTrd(), G4TwistedTrd::GetPhiTwist(), G4TwistedTrd::GetX1HalfLength(), G4TwistedTrd::GetX2HalfLength(), G4TwistedTrd::GetY1HalfLength(), G4TwistedTrd::GetY2HalfLength(), G4TwistedTrd::GetZHalfLength(), and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TwistedTubs ()
Definition at line 112 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 112 of file pyG4TwistedTubs.cc
References pyG4TwistedTubs::f1_CreateTwistedTubs(), pyG4TwistedTubs::f1_GetEndInnerRadius, pyG4TwistedTubs::f1_GetEndOuterRadius, pyG4TwistedTubs::f2_CreateTwistedTubs(), pyG4TwistedTubs::f2_GetEndInnerRadius, pyG4TwistedTubs::f2_GetEndOuterRadius, pyG4TwistedTubs::f3_CreateTwistedTubs(), pyG4TwistedTubs::f4_CreateTwistedTubs(), G4TwistedTubs::GetDPhi(), G4TwistedTubs::GetEndPhi(), G4TwistedTubs::GetEndZ(), G4TwistedTubs::GetInnerRadius(), G4TwistedTubs::GetInnerStereo(), G4TwistedTubs::GetKappa(), G4TwistedTubs::GetOuterRadius(), G4TwistedTubs::GetOuterStereo(), G4TwistedTubs::GetPhiTwist(), G4TwistedTubs::GetTanInnerStereo(), G4TwistedTubs::GetTanInnerStereo2(), G4TwistedTubs::GetTanOuterStereo(), G4TwistedTubs::GetTanOuterStereo2(), G4TwistedTubs::GetZHalfLength(), and init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UniformMagField ()
Definition at line 39 of file pyG4UniformMagField.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4UniformMagField.cc
References G4UniformMagField::GetConstantFieldValue(), and G4UniformMagField::SetFieldValue().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UnionSolid ()
Definition at line 39 of file pyG4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4UnionSolid.cc
References init().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VPhysicalVolume ()
Definition at line 57 of file pyG4VPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 57 of file pyG4VPhysicalVolume.cc
References pyG4VPhysicalVolume::f1_GetRotation, pyG4VPhysicalVolume::f2_GetRotation, G4VPhysicalVolume::GetCopyNo(), G4VPhysicalVolume::GetFrameRotation(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetMultiplicity(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::GetObjectRotationValue(), G4VPhysicalVolume::GetObjectTranslation(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetTranslation(), G4VPhysicalVolume::IsMany(), G4VPhysicalVolume::IsParameterised(), G4VPhysicalVolume::IsReplicated(), G4VPhysicalVolume::SetCopyNo(), G4VPhysicalVolume::SetLogicalVolume(), G4VPhysicalVolume::SetMotherLogical(), G4VPhysicalVolume::SetName(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VSolid ()
Definition at line 40 of file pyG4VSolid.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4VSolid.cc
References G4VSolid::DumpInfo(), G4VSolid::GetCubicVolume(), G4VSolid::GetName(), G4VSolid::GetPointOnSurface(), G4VSolid::GetSurfaceArea(), and G4VSolid::SetName().
Referenced by BOOST_PYTHON_MODULE().
void export_G4VTouchable ()
Definition at line 65 of file pyG4VTouchable.cc.
View newest version in sPHENIX GitHub at line 65 of file pyG4VTouchable.cc
References G4VTouchable::GetHistoryDepth(), G4VTouchable::GetReplicaNumber(), G4VTouchable::GetRotation(), G4VTouchable::GetSolid(), G4VTouchable::GetTranslation(), G4VTouchable::GetVolume(), and G4VTouchable::MoveUpHistory().
Referenced by BOOST_PYTHON_MODULE().