ECCE @ EIC Software: ExGflashEventAction Class Reference
ExGflashEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflashEventAction.hh>
Public Member Functions
ExGflashEventAction ()
~ExGflashEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
ExGflashEventAction ()
~ExGflashEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
ExGflashEventAction ()
~ExGflashEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
ExGflashEventAction (ExGflashDetectorConstruction *det)
~ExGflashEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4int fNevent
G4double fDtime
G4int fCalorimeterCollectionId
G4Timer fTimerIntern
ExGflashDetectorConstruction * fDet
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 37 of file ExGflashEventAction.hh.
View newest version in sPHENIX GitHub at line 37 of file ExGflashEventAction.hh
Constructor & Destructor Documentation
ExGflashEventAction::ExGflashEventAction ()
Definition at line 50 of file ExGflashEventAction.cc.
View newest version in sPHENIX GitHub at line 50 of file ExGflashEventAction.cc
ExGflashEventAction::~ExGflashEventAction ()
Definition at line 58 of file ExGflashEventAction.cc.
View newest version in sPHENIX GitHub at line 58 of file ExGflashEventAction.cc
References fDtime, fNevent, G4cout, and G4endl.
ExGflashEventAction::ExGflashEventAction ()
ExGflashEventAction::~ExGflashEventAction ()
ExGflashEventAction::ExGflashEventAction ()
ExGflashEventAction::~ExGflashEventAction ()
ExGflashEventAction::ExGflashEventAction (ExGflashDetectorConstruction * det)
Definition at line 53 of file ExGflashEventAction.cc.
View newest version in sPHENIX GitHub at line 53 of file ExGflashEventAction.cc
ExGflashEventAction::~ExGflashEventAction ()
Member Function Documentation
void ExGflashEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 67 of file ExGflashEventAction.cc.
View newest version in sPHENIX GitHub at line 67 of file ExGflashEventAction.cc
References fNevent, fTimerIntern, G4cout, G4endl, G4Event::GetEventID(), and G4Timer::Start().
virtual void ExGflashEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
virtual void ExGflashEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
virtual void ExGflashEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
void ExGflashEventAction::EndOfEventAction (const G4Event * evt) virtual
Hits in sensitive Detector
Computing (x,y,z) of vertex of initial particles
For all Hits in sensitive detector
Reimplemented from G4UserEventAction.
Definition at line 77 of file ExGflashEventAction.cc.
View newest version in sPHENIX GitHub at line 77 of file ExGflashEventAction.cc
References CLHEP::Hep3Vector::cross(), G4TrajectoryContainer::entries(), G4THitsCollection< T >::entries(), fCalorimeterCollectionId, fDtime, fNevent, fTimerIntern, G4cout, G4endl, G4SDManager::GetCollectionID(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4PrimaryParticle::GetMomentum(), G4PrimaryVertex::GetPosition(), G4PrimaryVertex::GetPrimary(), G4Event::GetPrimaryVertex(), G4Timer::GetRealElapsed(), G4SDManager::GetSDMpointer(), G4Timer::GetSystemElapsed(), G4Event::GetTrajectoryContainer(), G4Timer::GetUserElapsed(), GeV, CLHEP::Hep3Vector::mag(), max, mom, num, G4Timer::Stop(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
virtual void ExGflashEventAction::EndOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
virtual void ExGflashEventAction::EndOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
virtual void ExGflashEventAction::EndOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Member Data Documentation
G4int ExGflashEventAction::fCalorimeterCollectionId private
Definition at line 48 of file ExGflashEventAction.hh.
View newest version in sPHENIX GitHub at line 48 of file ExGflashEventAction.hh
Referenced by EndOfEventAction().
ExGflashDetectorConstruction* ExGflashEventAction::fDet private
Definition at line 48 of file ExGflashEventAction.hh.
View newest version in sPHENIX GitHub at line 48 of file ExGflashEventAction.hh
G4double ExGflashEventAction::fDtime private
Definition at line 47 of file ExGflashEventAction.hh.
View newest version in sPHENIX GitHub at line 47 of file ExGflashEventAction.hh
Referenced by EndOfEventAction(), and ~ExGflashEventAction().
G4int ExGflashEventAction::fNevent private
Definition at line 46 of file ExGflashEventAction.hh.
View newest version in sPHENIX GitHub at line 46 of file ExGflashEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), and ~ExGflashEventAction().
G4Timer ExGflashEventAction::fTimerIntern private
Definition at line 49 of file ExGflashEventAction.hh.
View newest version in sPHENIX GitHub at line 49 of file ExGflashEventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflashEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/include/ExGflashEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/include/ExGflashEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/include/ExGflashEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/src/ExGflashEventAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/src/ExGflashEventAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/src/ExGflashEventAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/src/ExGflashEventAction.cc