ECCE @ EIC Software: G4UniformElectricField Class Reference
G4UniformElectricField Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4UniformElectricField.hh>
Public Member Functions
G4UniformElectricField (const G4ThreeVector &FieldVector)
G4UniformElectricField (G4double vField, G4double vTheta, G4double vPhi)
virtual ~G4UniformElectricField ()
G4UniformElectricField (const G4UniformElectricField &p)
G4UniformElectricField & operator= (const G4UniformElectricField &p)
virtual void GetFieldValue (const G4double pos[4], G4double *field) const
virtual G4Field * Clone () const
Public Member Functions inherited from G4ElectricField
G4ElectricField ()
virtual ~G4ElectricField ()
G4ElectricField (const G4ElectricField &r)
G4ElectricField & operator= (const G4ElectricField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4ElectroMagneticField
G4ElectroMagneticField ()
virtual ~G4ElectroMagneticField ()
G4ElectroMagneticField (const G4ElectroMagneticField &r)
G4ElectroMagneticField & operator= (const G4ElectroMagneticField &p)
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Private Attributes
G4double fFieldComponents [6]
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 41 of file G4UniformElectricField.hh.
View newest version in sPHENIX GitHub at line 41 of file G4UniformElectricField.hh
Constructor & Destructor Documentation
G4UniformElectricField::G4UniformElectricField (const G4ThreeVector & FieldVector)
Definition at line 35 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 35 of file G4UniformElectricField.cc
References fFieldComponents, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Clone().
G4UniformElectricField::G4UniformElectricField (G4double vField, G4double vTheta, G4double vPhi)
Definition at line 45 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 45 of file G4UniformElectricField.cc
References FatalException, fFieldComponents, G4Exception(), pi, and twopi.
G4UniformElectricField::~G4UniformElectricField () virtual
Definition at line 63 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 63 of file G4UniformElectricField.cc
G4UniformElectricField::G4UniformElectricField (const G4UniformElectricField & p)
Definition at line 68 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 68 of file G4UniformElectricField.cc
References fFieldComponents.
Member Function Documentation
G4Field * G4UniformElectricField::Clone () const virtual
Reimplemented from G4Field.
Definition at line 89 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 89 of file G4UniformElectricField.cc
References fFieldComponents, and G4UniformElectricField().
void G4UniformElectricField::GetFieldValue (const G4double pos[4], G4double * field) const virtual
Implements G4ElectricField.
Definition at line 98 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 98 of file G4UniformElectricField.cc
References fFieldComponents.
G4UniformElectricField & G4UniformElectricField::operator= (const G4UniformElectricField & p)
Definition at line 78 of file G4UniformElectricField.cc.
View newest version in sPHENIX GitHub at line 78 of file G4UniformElectricField.cc
References fFieldComponents, and G4ElectricField::operator=().
Member Data Documentation
G4double G4UniformElectricField::fFieldComponents[6] private
Definition at line 64 of file G4UniformElectricField.hh.
View newest version in sPHENIX GitHub at line 64 of file G4UniformElectricField.hh
Referenced by Clone(), G4UniformElectricField(), GetFieldValue(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4UniformElectricField.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4UniformElectricField.cc