ECCE @ EIC Software: G4PionMinusField Class Reference
G4PionMinusField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4PionMinusField.hh>
Public Member Functions
G4PionMinusField (G4V3DNucleus *nucleus, G4double coeff=0.042 *CLHEP::fermi)
virtual ~G4PionMinusField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
virtual G4double GetCoeff ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
Private Member Functions
G4PionMinusField (const G4PionMinusField &right)
const G4PionMinusField & operator= (const G4PionMinusField &right)
G4bool operator== (const G4PionMinusField &right) const
G4bool operator!= (const G4PionMinusField &right) const
Private Attributes
G4double theCoeff
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 47 of file G4PionMinusField.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PionMinusField.hh
Constructor & Destructor Documentation
G4PionMinusField::G4PionMinusField (G4V3DNucleus * nucleus, G4double coeff = 0.042*CLHEP::fermi)
Definition at line 49 of file G4PionMinusField.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PionMinusField.cc
References theCoeff.
G4PionMinusField::~G4PionMinusField () virtual
Definition at line 56 of file G4PionMinusField.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PionMinusField.cc
G4PionMinusField::G4PionMinusField (const G4PionMinusField & right) private
Member Function Documentation
G4double G4PionMinusField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 78 of file G4PionMinusField.cc.
View newest version in sPHENIX GitHub at line 78 of file G4PionMinusField.cc
References A(), G4V3DNucleus::GetCharge(), G4Pow::GetInstance(), G4V3DNucleus::GetMassNumber(), MeV, G4VNuclearField::theNucleus, Z, and G4Pow::Z13().
Referenced by GetField().
virtual G4double G4PionMinusField::GetCoeff () inline virtual
Reimplemented from G4VNuclearField.
Definition at line 64 of file G4PionMinusField.hh.
View newest version in sPHENIX GitHub at line 64 of file G4PionMinusField.hh
References theCoeff.
G4double G4PionMinusField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 59 of file G4PionMinusField.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PionMinusField.cc
References A(), G4InuclSpecialFunctions::bindingEnergy(), G4lrint(), GetBarrier(), G4NucleiProperties::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4VNuclearDensity::GetDensity(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, CLHEP::Hep3Vector::mag(), source.hepunit::neutron_mass_c2, pi, G4PionMinus::PionMinus(), source.hepunit::proton_mass_c2, G4VNuclearField::radius, theCoeff, G4VNuclearField::theNucleus, and Z.
G4bool G4PionMinusField::operator!= (const G4PionMinusField & right) const private
const G4PionMinusField& G4PionMinusField::operator= (const G4PionMinusField & right) private
G4bool G4PionMinusField::operator== (const G4PionMinusField & right) const private
Member Data Documentation
G4double G4PionMinusField::theCoeff private
Definition at line 67 of file G4PionMinusField.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PionMinusField.hh
Referenced by G4PionMinusField(), GetCoeff(), and GetField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4PionMinusField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4PionMinusField.cc