ECCE @ EIC Software: PHG4CylinderStripDetector Class Reference
PHG4CylinderStripDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4barrelmmg/PHG4CylinderStripDetector.h>
Public Member Functions
PHG4CylinderStripDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4CylinderStripDetector ()
destructor
void ConstructMe (G4LogicalVolume *world)
construct
bool IsInTileC (G4VPhysicalVolume *) const
bool IsInTileZ (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
void BuildMaterials ()
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
G4VSolid * GetHollowBar ()
Private Attributes
PHParameters * m_Params
G4VPhysicalVolume * m_CylinderPhysicalVolume
std::set< G4VPhysicalVolume * > m_CylinderCPhysicalVolume
std::set< G4VPhysicalVolume * > m_CylinderZPhysicalVolume
int m_Layer
std::string m_SuperDetector
double thickness
double barwidth
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 17 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 17 of file PHG4CylinderStripDetector.h
Constructor & Destructor Documentation
PHG4CylinderStripDetector::PHG4CylinderStripDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 38 of file PHG4CylinderStripDetector.cc.
View newest version in sPHENIX GitHub at line 38 of file PHG4CylinderStripDetector.cc
References barwidth, and mm.
virtual PHG4CylinderStripDetector::~PHG4CylinderStripDetector () inline virtual
destructor
Definition at line 24 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 24 of file PHG4CylinderStripDetector.h
Member Function Documentation
void PHG4CylinderStripDetector::BuildMaterials ()
Definition at line 597 of file PHG4CylinderStripDetector.cc.
View newest version in sPHENIX GitHub at line 597 of file PHG4CylinderStripDetector.cc
References G4Material::AddMaterial(), atmosphere, cm3, Acts::UnitConstants::g, PHG4Detector::GetDetectorMaterial(), G4Material::GetName(), kelvin, kStateGas, and kStateSolid.
Referenced by ConstructMe().
void PHG4CylinderStripDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 90 of file PHG4CylinderStripDetector.cc.
View newest version in sPHENIX GitHub at line 90 of file PHG4CylinderStripDetector.cc
References barwidth, G4Colour::Black(), G4Colour::Brown(), BuildMaterials(), cm, color(), components, deg, BlackHoleGeometry::gap, PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), PHG4Detector::GetDetectorMaterial(), GetHollowBar(), PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), G4Colour::Green(), G4Colour::Grey(), isfinite, m_CylinderCPhysicalVolume, m_CylinderPhysicalVolume, m_CylinderZPhysicalVolume, m_Params, mm, PHG4Detector::OverlapCheck(), radian, radius, CLHEP::HepRotation::rotateZ(), CLHEP::HepRotation::setDelta(), G4VisAttributes::SetForceLineSegmentsPerCircle(), G4VisAttributes::SetForceSolid(), PHG4Subsystem::SetLogicalVolume(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), thick, thickness, twopi, um, and G4Colour::White().
int PHG4CylinderStripDetector::get_Layer () const inline
Definition at line 36 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 36 of file PHG4CylinderStripDetector.h
References m_Layer.
Referenced by PHG4CylinderStripSteppingAction::UserSteppingAction().
G4VSolid * PHG4CylinderStripDetector::GetHollowBar () private
Definition at line 705 of file PHG4CylinderStripDetector.cc.
View newest version in sPHENIX GitHub at line 705 of file PHG4CylinderStripDetector.cc
References bar, barwidth, cm, PHParameters::get_double_param(), BTOF::length, m_Params, and mm.
Referenced by ConstructMe().
bool PHG4CylinderStripDetector::IsInTileC (G4VPhysicalVolume * volume) const
Definition at line 63 of file PHG4CylinderStripDetector.cc.
View newest version in sPHENIX GitHub at line 63 of file PHG4CylinderStripDetector.cc
References m_CylinderCPhysicalVolume.
Referenced by PHG4CylinderStripSteppingAction::UserSteppingAction().
bool PHG4CylinderStripDetector::IsInTileZ (G4VPhysicalVolume * volume) const
Definition at line 77 of file PHG4CylinderStripDetector.cc.
View newest version in sPHENIX GitHub at line 77 of file PHG4CylinderStripDetector.cc
References m_CylinderZPhysicalVolume.
Referenced by PHG4CylinderStripSteppingAction::UserSteppingAction().
void PHG4CylinderStripDetector::SuperDetector (const std::string & name) inline
Definition at line 34 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4CylinderStripDetector.h
References m_SuperDetector.
Referenced by PHG4CylinderStripSubsystem::InitRunSubsystem(), PHG4CylinderStripSteppingAction::SetInterfacePointers(), and PHG4CylinderStripSteppingAction::UserSteppingAction().
const std::string PHG4CylinderStripDetector::SuperDetector () const inline
Definition at line 35 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 35 of file PHG4CylinderStripDetector.h
References m_SuperDetector.
Member Data Documentation
double PHG4CylinderStripDetector::barwidth private
Definition at line 52 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4CylinderStripDetector.h
Referenced by ConstructMe(), GetHollowBar(), and PHG4CylinderStripDetector().
std::set<G4VPhysicalVolume *> PHG4CylinderStripDetector::m_CylinderCPhysicalVolume private
Definition at line 43 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4CylinderStripDetector.h
Referenced by ConstructMe(), and IsInTileC().
G4VPhysicalVolume* PHG4CylinderStripDetector::m_CylinderPhysicalVolume private
Definition at line 42 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 42 of file PHG4CylinderStripDetector.h
Referenced by ConstructMe().
std::set<G4VPhysicalVolume *> PHG4CylinderStripDetector::m_CylinderZPhysicalVolume private
Definition at line 44 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4CylinderStripDetector.h
Referenced by ConstructMe(), and IsInTileZ().
int PHG4CylinderStripDetector::m_Layer private
Definition at line 48 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4CylinderStripDetector.h
Referenced by get_Layer().
PHParameters* PHG4CylinderStripDetector::m_Params private
Definition at line 40 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 40 of file PHG4CylinderStripDetector.h
Referenced by ConstructMe(), and GetHollowBar().
std::string PHG4CylinderStripDetector::m_SuperDetector private
Definition at line 49 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 49 of file PHG4CylinderStripDetector.h
Referenced by SuperDetector().
double PHG4CylinderStripDetector::thickness private
Definition at line 51 of file PHG4CylinderStripDetector.h.
View newest version in sPHENIX GitHub at line 51 of file PHG4CylinderStripDetector.h
Referenced by ConstructMe().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4barrelmmg/PHG4CylinderStripDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4barrelmmg/PHG4CylinderStripDetector.cc