ECCE @ EIC Software: G4QuasiElasticChannel Class Reference
G4QuasiElasticChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/theo_high_energy/include/G4QuasiElasticChannel.hh>
Public Member Functions
G4QuasiElasticChannel ()
~G4QuasiElasticChannel ()
G4double GetFraction (G4Nucleus &theNucleus, const G4DynamicParticle &thePrimary)
G4KineticTrackVector * Scatter (G4Nucleus &theNucleus, const G4DynamicParticle &thePrimary)
Private Member Functions
G4QuasiElasticChannel (const G4QuasiElasticChannel &)
const G4QuasiElasticChannel & operator= (const G4QuasiElasticChannel &)
G4bool operator== (const G4QuasiElasticChannel &) const
G4bool operator!= (const G4QuasiElasticChannel &) const
Private Attributes
G4QuasiElRatios * theQuasiElastic
G4V3DNucleus * the3DNucleus
Detailed Description
Definition at line 51 of file G4QuasiElasticChannel.hh.
View newest version in sPHENIX GitHub at line 51 of file G4QuasiElasticChannel.hh
Constructor & Destructor Documentation
G4QuasiElasticChannel::G4QuasiElasticChannel ()
Definition at line 61 of file G4QuasiElasticChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4QuasiElasticChannel.cc
G4QuasiElasticChannel::~G4QuasiElasticChannel ()
Definition at line 66 of file G4QuasiElasticChannel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4QuasiElasticChannel.cc
References the3DNucleus, and theQuasiElastic.
G4QuasiElasticChannel::G4QuasiElasticChannel (const G4QuasiElasticChannel &) private
Member Function Documentation
G4double G4QuasiElasticChannel::GetFraction (G4Nucleus & theNucleus, const G4DynamicParticle & thePrimary)
Definition at line 72 of file G4QuasiElasticChannel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4QuasiElasticChannel.cc
References G4cout, G4endl, G4Nucleus::GetA_asInt(), G4DynamicParticle::GetDefinition(), G4Nucleus::GetN_asInt(), G4ParticleDefinition::GetPDGEncoding(), G4QuasiElRatios::GetRatios(), G4DynamicParticle::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), and theQuasiElastic.
Referenced by G4TheoFSGenerator::ApplyYourself().
G4bool G4QuasiElasticChannel::operator!= (const G4QuasiElasticChannel &) const private
const G4QuasiElasticChannel& G4QuasiElasticChannel::operator= (const G4QuasiElasticChannel &) private
G4bool G4QuasiElasticChannel::operator== (const G4QuasiElasticChannel &) const private
G4KineticTrackVector * G4QuasiElasticChannel::Scatter (G4Nucleus & theNucleus, const G4DynamicParticle & thePrimary)
Definition at line 96 of file G4QuasiElasticChannel.cc.
View newest version in sPHENIX GitHub at line 96 of file G4QuasiElasticChannel.cc
References A(), kdfinder::abs(), CLHEP::HepLorentzVector::e(), G4cout, G4endl, G4lrint(), G4UniformRand, G4DynamicParticle::Get4Momentum(), G4Nucleus::GetA_asInt(), G4DynamicParticle::GetDefinition(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4V3DNucleus::GetMass(), G4V3DNucleus::GetNucleons(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetZ_asInt(), in, G4V3DNucleus::Init(), CLHEP::Hep3Vector::mag2(), MeV, G4Neutron::Neutron(), G4QuasiElRatios::Scatter(), CLHEP::HepLorentzVector::setE(), sqr(), the3DNucleus, theQuasiElastic, CLHEP::HepLorentzVector::vect(), and Z.
Referenced by G4TheoFSGenerator::ApplyYourself().
Member Data Documentation
G4V3DNucleus* G4QuasiElasticChannel::the3DNucleus private
Definition at line 71 of file G4QuasiElasticChannel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QuasiElasticChannel.hh
Referenced by Scatter(), and ~G4QuasiElasticChannel().
G4QuasiElRatios* G4QuasiElasticChannel::theQuasiElastic private
Definition at line 70 of file G4QuasiElasticChannel.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QuasiElasticChannel.hh
Referenced by GetFraction(), Scatter(), and ~G4QuasiElasticChannel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/theo_high_energy/include/G4QuasiElasticChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/theo_high_energy/src/G4QuasiElasticChannel.cc