ECCE @ EIC Software: Dicom2PrimaryGeneratorAction Class Reference
Dicom2PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/include/Dicom2PrimaryGeneratorAction.hh>
Public Member Functions
Dicom2PrimaryGeneratorAction ()
virtual ~Dicom2PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
G4Box * fEnvelopeBox
G4VPhysicalVolume * fEnvelopeVol
G4ThreeVector fPosCenter
G4ThreeVector fPosDelta
G4double fGeomFactor
Detailed Description
The primary generator action class with particle gun.
The default kinematic is a 6 MeV gamma, randomly distribued in front of the phantom across 80% of the (X,Y) phantom size.
Definition at line 47 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 47 of file Dicom2PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
Dicom2PrimaryGeneratorAction::Dicom2PrimaryGeneratorAction ()
Definition at line 49 of file Dicom2PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 49 of file Dicom2PrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), MeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), and G4ParticleGun::SetParticleMomentumDirection().
Dicom2PrimaryGeneratorAction::~Dicom2PrimaryGeneratorAction () virtual
Definition at line 70 of file Dicom2PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 70 of file Dicom2PrimaryGeneratorAction.cc
References fParticleGun.
Member Function Documentation
void Dicom2PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 77 of file Dicom2PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 77 of file Dicom2PrimaryGeneratorAction.cc
References Acts::Test::delta, fEnvelopeBox, fEnvelopeVol, fGeomFactor, fParticleGun, fPosCenter, fPosDelta, G4Exception(), G4RandomDirection(), G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetObjectTranslation(), G4LogicalVolume::GetSolid(), G4LogicalVolumeStore::GetVolume(), G4PhysicalVolumeStore::GetVolume(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), JustWarning, pos(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
const G4ParticleGun* Dicom2PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 57 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file Dicom2PrimaryGeneratorAction.hh
References fParticleGun.
Member Data Documentation
G4Box* Dicom2PrimaryGeneratorAction::fEnvelopeBox private
Definition at line 61 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 61 of file Dicom2PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4VPhysicalVolume* Dicom2PrimaryGeneratorAction::fEnvelopeVol private
Definition at line 62 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 62 of file Dicom2PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4double Dicom2PrimaryGeneratorAction::fGeomFactor private
Definition at line 65 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file Dicom2PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4ParticleGun* Dicom2PrimaryGeneratorAction::fParticleGun private
Definition at line 60 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file Dicom2PrimaryGeneratorAction.hh
Referenced by Dicom2PrimaryGeneratorAction(), GeneratePrimaries(), GetParticleGun(), and ~Dicom2PrimaryGeneratorAction().
G4ThreeVector Dicom2PrimaryGeneratorAction::fPosCenter private
Definition at line 63 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 63 of file Dicom2PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4ThreeVector Dicom2PrimaryGeneratorAction::fPosDelta private
Definition at line 64 of file Dicom2PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 64 of file Dicom2PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/include/Dicom2PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/src/Dicom2PrimaryGeneratorAction.cc