ECCE @ EIC Software: G4GMocrenIO Class Reference
G4GMocrenIO Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/gMocren/include/G4GMocrenIO.hh>
Public Member Functions
G4GMocrenIO ()
~G4GMocrenIO ()
void initialize ()
void setFileName (std::string &_filename)
void setFileName (char *_filename)
std::string & getFileName ()
bool storeData (char *_filename)
bool storeData ()
bool storeData2 (char *_filename)
bool storeData2 ()
bool storeData3 (char *_filename)
bool storeData3 ()
bool storeData4 (char *_filename)
bool storeData4 ()
bool retrieveData (char *_filename)
bool retrieveData ()
bool retrieveData2 (char *_filename)
bool retrieveData2 ()
bool retrieveData3 (char *_filename)
bool retrieveData3 ()
bool retrieveData4 (char *_filename)
bool retrieveData4 ()
std::string & getID ()
void setID ()
void setID (std::string &_id)
std::string & getVersion ()
void setVersion (std::string &_version)
void setLittleEndianInput (bool _little)
void setLittleEndianOutput (bool _little)
std::string & getComment ()
void setComment (std::string &_comment)
void setVoxelSpacing (float _spacing[3])
void getVoxelSpacing (float _spacing[3])
int & getNumberOfEvents ()
void setNumberOfEvents (int &_numberOfEvents)
void addOneEvent ()
void setPointerToModalityData (unsigned int &_pointer)
unsigned int getPointerToModalityData ()
void addPointerToDoseDistData (unsigned int &_pointer)
unsigned int getPointerToDoseDistData (int _elem=0)
void setPointerToROIData (unsigned int &_pointer)
unsigned int getPointerToROIData ()
void setPointerToTrackData (unsigned int &_pointer)
unsigned int getPointerToTrackData ()
void getModalityImageSize (int _size[3])
void setModalityImageSize (int _size[3])
void getModalityImageVoxelSpacing (float _size[3])
void setModalityImageVoxelSpacing (float _size[3])
void setModalityImageScale (double &_scale)
double getModalityImageScale ()
void setModalityImage (short *_image)
short * getModalityImage (int _z)
void clearModalityImage ()
void setModalityImageDensityMap (std::vector< float > &_map)
std::vector< float > & getModalityImageDensityMap ()
void setModalityImageMinMax (short _minmax[2])
void getModalityImageMinMax (short _minmax[2])
short getModalityImageMax ()
short getModalityImageMin ()
void setModalityCenterPosition (float _center[3])
void getModalityCenterPosition (float _center[3])
std::string getModalityImageUnit ()
void setModalityImageUnit (std::string &_unit)
short convertDensityToHU (float &_dens)
void newDoseDist ()
int getNumDoseDist ()
std::string getDoseDistUnit (int _num=0)
void setDoseDistUnit (std::string &_unit, int _num=0)
void getDoseDistSize (int _size[3], int _num=0)
void setDoseDistSize (int _size[3], int _num=0)
void setDoseDistMinMax (short _minmax[2], int _num=0)
void getDoseDistMinMax (short _minmax[2], int _num=0)
void setDoseDistMinMax (double _minmax[2], int _num=0)
void getDoseDistMinMax (double _minmax[2], int _num=0)
void setDoseDistScale (double &_scale, int _num=0)
double getDoseDistScale (int _num=0)
void setShortDoseDist (short *_image, int _num=0)
void getShortDoseDist (short *_data, int _z, int _num=0)
void getShortDoseDistMinMax (short _minmax[2], int _num=0)
void setDoseDist (double *_image, int _num=0)
double * getDoseDist (int _z, int _num=0)
bool addDoseDist (std::vector< double * > &_image, int _num=0)
void getDoseDistCenterPosition (float _center[3], int _num=0)
void setDoseDistCenterPosition (float _center[3], int _num=0)
std::string getDoseDistName (int _num=0)
void setDoseDistName (std::string _name, int _num=0)
void copyDoseDist (std::vector< class GMocrenDataPrimitive< double > > &_dose)
bool mergeDoseDist (std::vector< class GMocrenDataPrimitive< double > > &_dose)
void clearDoseDistAll ()
void newROI ()
int getNumROI ()
double getROIScale (int _num=0)
void setROIScale (double &_scale, int _num=0)
short * getROI (int _z, int _num=0)
void setROI (short *_image, int _num=0)
void getROISize (int _size[3], int _num=0)
void setROISize (int _size[3], int _num=0)
void getROICenterPosition (float _center[3], int _num=0)
void setROICenterPosition (float _center[3], int _num=0)
void getROIMinMax (short _minmax[2], int _num=0)
void setROIMinMax (short _minmax[2], int _num=0)
void clearROIAll ()
int getNumTracks ()
int getNumTracks4 ()
std::vector< float * > & getTracks ()
void getTrack (int _num, std::vector< float * > &_steps, std::vector< unsigned char * > &_color)
void addTrack (float *_tracks)
void setTracks (std::vector< float * > &_tracks)
std::vector< unsigned char * > & getTrackColors ()
void addTrackColor (unsigned char *_colors)
void setTrackColors (std::vector< unsigned char * > &_trackColors)
void copyTracks (std::vector< float * > &_tracks, std::vector< unsigned char * > &_colors)
void mergeTracks (std::vector< float * > &_tracks, std::vector< unsigned char * > &_colors)
void addTrack (std::vector< float * > &_steps, unsigned char _color[3])
void notStoredTracks ()
void translateTracks (std::vector< float > &_translateo)
void clearTracks ()
int getNumberOfDetectors ()
void addDetector (std::string &_name, std::vector< float * > &_det, unsigned char _color[3])
void getDetector (int _num, std::vector< float * > &_edges, std::vector< unsigned char * > &_color, std::string &_detectorName)
void translateDetector (std::vector< float > &_translate)
void clearDetector ()
void setVerboseLevel (int _level)
template<typename T >
void convertEndian (char *_val, T &_rval)
Public Attributes
bool kTracksWillBeStored
Static Public Attributes
static std::string kId
static std::string kVersion = "2.0.0"
static std::string kFileName = "dose.gdd"
static char kLittleEndianInput = true
static char kLittleEndianOutput = true
static std::string kComment
static int kNumberOfEvents = 0
static unsigned int kPointerToModalityData = 0
static std::vector< unsigned int > kPointerToDoseDistData
static unsigned int kPointerToROIData = 0
static unsigned int kPointerToTrackData = 0
static unsigned int kPointerToDetectorData = 0
static float kVoxelSpacing [3] = {0., 0., 0.}
static class
GMocrenDataPrimitive< short > kModality
static std::vector< float > kModalityImageDensityMap
static std::string kModalityUnit = "g/cm3 "
static std::vector< class
GMocrenDataPrimitive< double > > kDose
static std::string kDoseUnit = "keV "
static std::vector< class
GMocrenDataPrimitive< short > > kRoi
static std::vector< float * > kSteps
static std::vector< unsigned
char * > kStepColors
static std::vector< class
GMocrenTrack > kTracks
static std::vector< class
GMocrenDetector > kDetectors
static int kVerbose = 0
Protected Member Functions
bool isDoseEmpty ()
void calcDoseDistScale ()
bool isROIEmpty ()
template<typename Type >
void convertEndian (char *, Type &)
template<typename T >
void invertByteOrder (char *_val, T &_rval)
Private Member Functions
void calcPointers4 ()
void calcPointers3 ()
void calcPointers2 ()
Detailed Description
Definition at line 166 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 166 of file G4GMocrenIO.hh
Constructor & Destructor Documentation
G4GMocrenIO::G4GMocrenIO ()
Definition at line 401 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 401 of file G4GMocrenIO.cc
G4GMocrenIO::~G4GMocrenIO ()
Definition at line 407 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 407 of file G4GMocrenIO.cc
Member Function Documentation
void G4GMocrenIO::addDetector (std::string & _name, std::vector< float * > & _det, unsigned char _color[3])
Definition at line 3948 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3948 of file G4GMocrenIO.cc
References GMocrenDetector::Edge::endPoint, kDetectors, GMocrenDetector::setColor(), GMocrenDetector::setDetector(), GMocrenDetector::setName(), and GMocrenDetector::Edge::startPoint.
Referenced by G4GMocrenFileSceneHandler::ExtractDetector(), and retrieveData4().
bool G4GMocrenIO::addDoseDist (std::vector< double * > & _image, int _num = 0)
Definition at line 3633 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3633 of file G4GMocrenIO.cc
References getDoseDistSize(), kDose, and z.
void G4GMocrenIO::addOneEvent ()
Definition at line 3142 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3142 of file G4GMocrenIO.cc
References kNumberOfEvents.
void G4GMocrenIO::addPointerToDoseDistData (unsigned int & _pointer)
Definition at line 3154 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3154 of file G4GMocrenIO.cc
References kPointerToDoseDistData.
Referenced by calcPointers3(), calcPointers4(), retrieveData3(), and retrieveData4().
void G4GMocrenIO::addTrack (float * _tracks)
Definition at line 3841 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3841 of file G4GMocrenIO.cc
References kSteps.
Referenced by G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::EndSavingGdd(), mergeTracks(), retrieveData2(), retrieveData3(), and retrieveData4().
void G4GMocrenIO::addTrack (std::vector< float * > & _steps, unsigned char _color[3])
Definition at line 3891 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3891 of file G4GMocrenIO.cc
References GMocrenTrack::Step::endPoint, kTracks, GMocrenTrack::setColor(), GMocrenTrack::setTrack(), GMocrenTrack::Step::startPoint, propagation_timing::steps, and track.
void G4GMocrenIO::addTrackColor (unsigned char * _colors)
Definition at line 3850 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3850 of file G4GMocrenIO.cc
References kStepColors.
Referenced by mergeTracks(), and retrieveData3().
void G4GMocrenIO::calcDoseDistScale () protected
Definition at line 3726 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3726 of file G4GMocrenIO.cc
References DOSERANGE, int(), kDose, and scale.
Referenced by storeData2(), storeData3(), and storeData4().
void G4GMocrenIO::calcPointers2 () private
Definition at line 3310 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3310 of file G4GMocrenIO.cc
References getDoseDistSize(), getModalityImageMinMax(), getModalityImageSize(), getNumTracks(), getROISize(), isROIEmpty(), kPointerToDoseDistData, setPointerToModalityData(), setPointerToROIData(), and setPointerToTrackData().
Referenced by storeData2().
void G4GMocrenIO::calcPointers3 () private
Definition at line 3255 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3255 of file G4GMocrenIO.cc
References addPointerToDoseDistData(), getDoseDistSize(), getModalityImageMinMax(), getModalityImageSize(), getNumDoseDist(), getNumTracks(), getROISize(), isROIEmpty(), kPointerToDoseDistData, setPointerToModalityData(), setPointerToROIData(), and setPointerToTrackData().
Referenced by storeData3().
void G4GMocrenIO::calcPointers4 () private
Definition at line 3181 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3181 of file G4GMocrenIO.cc
References addPointerToDoseDistData(), G4cout, G4endl, getDoseDistSize(), getModalityImageMinMax(), getModalityImageSize(), getNumDoseDist(), getROISize(), isROIEmpty(), kDetectors, kPointerToDetectorData, kPointerToDoseDistData, kPointerToTrackData, kTracks, kVerbose, setPointerToModalityData(), setPointerToROIData(), and setPointerToTrackData().
Referenced by storeData4().
void G4GMocrenIO::clearDetector () inline
Definition at line 451 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 451 of file G4GMocrenIO.hh
References kDetectors.
Referenced by G4GMocrenFileSceneHandler::BeginSavingGdd().
void G4GMocrenIO::clearDoseDistAll ()
Definition at line 3705 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3705 of file G4GMocrenIO.cc
References getNumDoseDist(), isDoseEmpty(), and kDose.
Referenced by G4GMocrenFileSceneHandler::BeginSavingGdd().
void G4GMocrenIO::clearModalityImage ()
Definition at line 3390 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3390 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::clearImage(), and kModality.
void G4GMocrenIO::clearROIAll ()
Definition at line 3811 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3811 of file G4GMocrenIO.cc
References getNumROI(), isROIEmpty(), and kRoi.
Referenced by G4GMocrenFileSceneHandler::BeginSavingGdd().
void G4GMocrenIO::clearTracks () inline
Definition at line 439 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 439 of file G4GMocrenIO.hh
References kTracks.
Referenced by G4GMocrenFileSceneHandler::BeginSavingGdd().
short G4GMocrenIO::convertDensityToHU (float & _dens)
Definition at line 3445 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3445 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getMinMax(), int(), kModality, and kModalityImageDensityMap.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
template<typename Type > void G4GMocrenIO::convertEndian (char * , Type &) protected
Referenced by retrieveData2(), retrieveData3(), and retrieveData4().
template<typename T > void G4GMocrenIO::convertEndian (char * _val, T & _rval)
Definition at line 4009 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 4009 of file G4GMocrenIO.cc
References kLittleEndianInput, kLittleEndianOutput, and T.
void G4GMocrenIO::copyDoseDist (std::vector< class GMocrenDataPrimitive< double > > & _dose)
Definition at line 3675 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3675 of file G4GMocrenIO.cc
References kDose.
void G4GMocrenIO::copyTracks (std::vector< float * > & _tracks, std::vector< unsigned char * > & _colors)
Definition at line 3859 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3859 of file G4GMocrenIO.cc
References kStepColors, and kSteps.
std::string& G4GMocrenIO::getComment () inline
Definition at line 274 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 274 of file G4GMocrenIO.hh
References kComment.
void G4GMocrenIO::getDetector (int _num, std::vector< float * > & _edges, std::vector< unsigned char * > & _color, std::string & _detectorName)
Definition at line 3970 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3970 of file G4GMocrenIO.cc
References color(), G4VisManager::errors, FatalException, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), and kDetectors.
double * G4GMocrenIO::getDoseDist (int _z, int _num = 0)
Definition at line 3610 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3610 of file G4GMocrenIO.cc
References isDoseEmpty(), and kDose.
void G4GMocrenIO::getDoseDistCenterPosition (float _center[3], int _num = 0)
Definition at line 3654 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3654 of file G4GMocrenIO.cc
References isDoseEmpty(), and kDose.
Referenced by storeData3(), and storeData4().
void G4GMocrenIO::getDoseDistMinMax (short _minmax[2], int _num = 0)
Definition at line 3511 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3511 of file G4GMocrenIO.cc
References isDoseEmpty(), kDose, and scale.
void G4GMocrenIO::getDoseDistMinMax (double _minmax[2], int _num = 0)
Definition at line 3526 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3526 of file G4GMocrenIO.cc
References isDoseEmpty(), and kDose.
std::string G4GMocrenIO::getDoseDistName (int _num = 0)
Definition at line 3666 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3666 of file G4GMocrenIO.cc
References isDoseEmpty(), and kDose.
Referenced by storeData4().
double G4GMocrenIO::getDoseDistScale (int _num = 0)
Definition at line 3539 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3539 of file G4GMocrenIO.cc
References isDoseEmpty(), and kDose.
Referenced by storeData3(), and storeData4().
void G4GMocrenIO::getDoseDistSize (int _size[3], int _num = 0)
Definition at line 3491 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3491 of file G4GMocrenIO.cc
References isDoseEmpty(), and kDose.
Referenced by addDoseDist(), calcPointers2(), calcPointers3(), and calcPointers4().
std::string G4GMocrenIO::getDoseDistUnit (int _num = 0)
Definition at line 3475 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3475 of file G4GMocrenIO.cc
References kDoseUnit.
std::string& G4GMocrenIO::getFileName () inline
Definition at line 240 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 240 of file G4GMocrenIO.hh
References kFileName.
std::string& G4GMocrenIO::getID () inline
Definition at line 261 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 261 of file G4GMocrenIO.hh
References kId.
void G4GMocrenIO::getModalityCenterPosition (float _center[3])
Definition at line 3430 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3430 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getCenterPosition(), isROIEmpty(), and kModality.
short * G4GMocrenIO::getModalityImage (int _z)
Definition at line 3386 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3386 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getImage(), and kModality.
std::vector< float > & G4GMocrenIO::getModalityImageDensityMap ()
Definition at line 3398 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3398 of file G4GMocrenIO.cc
References kModalityImageDensityMap.
short G4GMocrenIO::getModalityImageMax ()
Definition at line 3413 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3413 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getMinMax(), and kModality.
short G4GMocrenIO::getModalityImageMin ()
Definition at line 3419 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3419 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getMinMax(), and kModality.
void G4GMocrenIO::getModalityImageMinMax (short _minmax[2])
Definition at line 3407 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3407 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getMinMax(), and kModality.
Referenced by calcPointers2(), calcPointers3(), and calcPointers4().
double G4GMocrenIO::getModalityImageScale ()
Definition at line 3376 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3376 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getScale(), and kModality.
void G4GMocrenIO::getModalityImageSize (int _size[3])
Definition at line 3362 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3362 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::getSize(), and kModality.
Referenced by calcPointers2(), calcPointers3(), and calcPointers4().
std::string G4GMocrenIO::getModalityImageUnit ()
Definition at line 3438 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3438 of file G4GMocrenIO.cc
References kModalityUnit.
void G4GMocrenIO::getModalityImageVoxelSpacing (float _size[3])
int G4GMocrenIO::getNumberOfDetectors ()
Definition at line 3945 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3945 of file G4GMocrenIO.cc
References kDetectors.
int & G4GMocrenIO::getNumberOfEvents ()
Definition at line 3136 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3136 of file G4GMocrenIO.cc
References kNumberOfEvents.
int G4GMocrenIO::getNumDoseDist ()
Definition at line 3470 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3470 of file G4GMocrenIO.cc
References kDose.
Referenced by calcPointers3(), calcPointers4(), clearDoseDistAll(), storeData3(), and storeData4().
int G4GMocrenIO::getNumROI ()
Definition at line 3746 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3746 of file G4GMocrenIO.cc
References kRoi.
Referenced by clearROIAll().
int G4GMocrenIO::getNumTracks ()
Definition at line 3835 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3835 of file G4GMocrenIO.cc
References kSteps.
Referenced by calcPointers2(), and calcPointers3().
int G4GMocrenIO::getNumTracks4 ()
Definition at line 3838 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3838 of file G4GMocrenIO.cc
References kTracks.
unsigned int G4GMocrenIO::getPointerToDoseDistData (int _elem = 0)
Definition at line 3157 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3157 of file G4GMocrenIO.cc
References kPointerToDoseDistData.
unsigned int G4GMocrenIO::getPointerToModalityData ()
Definition at line 3150 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3150 of file G4GMocrenIO.cc
References kPointerToModalityData.
unsigned int G4GMocrenIO::getPointerToROIData ()
Definition at line 3169 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3169 of file G4GMocrenIO.cc
References kPointerToROIData.
unsigned int G4GMocrenIO::getPointerToTrackData ()
Definition at line 3176 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3176 of file G4GMocrenIO.cc
References kPointerToTrackData.
short * G4GMocrenIO::getROI (int _z, int _num = 0)
Definition at line 3767 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3767 of file G4GMocrenIO.cc
References isROIEmpty(), and kRoi.
void G4GMocrenIO::getROICenterPosition (float _center[3], int _num = 0)
Definition at line 3803 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3803 of file G4GMocrenIO.cc
References isROIEmpty(), and kRoi.
void G4GMocrenIO::getROIMinMax (short _minmax[2], int _num = 0)
Definition at line 3791 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3791 of file G4GMocrenIO.cc
References isROIEmpty(), and kRoi.
double G4GMocrenIO::getROIScale (int _num = 0)
Definition at line 3755 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3755 of file G4GMocrenIO.cc
References isROIEmpty(), and kRoi.
void G4GMocrenIO::getROISize (int _size[3], int _num = 0)
Definition at line 3779 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3779 of file G4GMocrenIO.cc
References isROIEmpty(), and kRoi.
Referenced by calcPointers2(), calcPointers3(), and calcPointers4().
void G4GMocrenIO::getShortDoseDist (short * _data, int _z, int _num = 0)
Definition at line 3575 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3575 of file G4GMocrenIO.cc
References G4VisManager::errors, FatalException, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), kDose, and scale.
Referenced by storeData2(), storeData3(), and storeData4().
void G4GMocrenIO::getShortDoseDistMinMax (short _minmax[2], int _num = 0)
Definition at line 3598 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3598 of file G4GMocrenIO.cc
References kDose, and scale.
Referenced by storeData2(), storeData3(), and storeData4().
void G4GMocrenIO::getTrack (int _num, std::vector< float * > & _steps, std::vector< unsigned char * > & _color)
Definition at line 3909 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3909 of file G4GMocrenIO.cc
References color(), G4VisManager::errors, FatalException, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), and kTracks.
std::vector< unsigned char * > & G4GMocrenIO::getTrackColors ()
Definition at line 3856 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3856 of file G4GMocrenIO.cc
References kStepColors.
std::vector< float * > & G4GMocrenIO::getTracks ()
Definition at line 3847 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3847 of file G4GMocrenIO.cc
References kSteps.
std::string & G4GMocrenIO::getVersion ()
Definition at line 3120 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3120 of file G4GMocrenIO.cc
References kVersion.
void G4GMocrenIO::getVoxelSpacing (float _spacing[3])
Definition at line 3131 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3131 of file G4GMocrenIO.cc
References kVoxelSpacing.
void G4GMocrenIO::initialize ()
Definition at line 412 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 412 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::clear(), kComment, kDose, kDoseUnit, kFileName, kId, kLittleEndianInput, kLittleEndianOutput, kModality, kModalityImageDensityMap, kModalityUnit, kNumberOfEvents, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kStepColors, kSteps, kTracksWillBeStored, kVerbose, kVersion, and kVoxelSpacing.
template<typename T > void G4GMocrenIO::invertByteOrder (char * _val, T & _rval) protected
Definition at line 4027 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 4027 of file G4GMocrenIO.cc
References T.
Referenced by storeData4().
bool G4GMocrenIO::isDoseEmpty () protected
Definition at line 3715 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3715 of file G4GMocrenIO.cc
References kDose.
Referenced by clearDoseDistAll(), getDoseDist(), getDoseDistCenterPosition(), getDoseDistMinMax(), getDoseDistName(), getDoseDistScale(), getDoseDistSize(), storeData2(), storeData3(), and storeData4().
bool G4GMocrenIO::isROIEmpty () protected
Definition at line 3821 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3821 of file G4GMocrenIO.cc
References kRoi.
Referenced by calcPointers2(), calcPointers3(), calcPointers4(), clearROIAll(), getModalityCenterPosition(), getROI(), getROICenterPosition(), getROIMinMax(), getROIScale(), getROISize(), storeData2(), storeData3(), and storeData4().
bool G4GMocrenIO::mergeDoseDist (std::vector< class GMocrenDataPrimitive< double > > & _dose)
Definition at line 3682 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3682 of file G4GMocrenIO.cc
References G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), kDose, kVerbose, and num.
void G4GMocrenIO::mergeTracks (std::vector< float * > & _tracks, std::vector< unsigned char * > & _colors)
Definition at line 3879 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3879 of file G4GMocrenIO.cc
References addTrack(), and addTrackColor().
void G4GMocrenIO::newDoseDist ()
Definition at line 3466 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3466 of file G4GMocrenIO.cc
References kDose.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd(), retrieveData2(), retrieveData3(), and retrieveData4().
void G4GMocrenIO::newROI ()
Definition at line 3742 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3742 of file G4GMocrenIO.cc
References kRoi.
Referenced by retrieveData2(), retrieveData3(), and retrieveData4().
void G4GMocrenIO::notStoredTracks () inline
Definition at line 437 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 437 of file G4GMocrenIO.hh
References kTracksWillBeStored.
bool G4GMocrenIO::retrieveData (char * _filename)
Definition at line 1646 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1646 of file G4GMocrenIO.cc
References kFileName, and retrieveData().
bool G4GMocrenIO::retrieveData ()
Definition at line 1594 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1594 of file G4GMocrenIO.cc
References G4VisManager::errors, FatalException, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), in, int(), kFileName, retrieveData2(), retrieveData3(), and retrieveData4().
Referenced by retrieveData(), retrieveData2(), retrieveData3(), and retrieveData4().
bool G4GMocrenIO::retrieveData2 (char * _filename)
Definition at line 3088 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3088 of file G4GMocrenIO.cc
References kFileName, and retrieveData().
bool G4GMocrenIO::retrieveData2 ()
Definition at line 2623 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 2623 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::addImage(), addTrack(), convertEndian(), Acts::Logging::DEBUG, G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), IDLENGTH, in, int(), kDose, kFileName, kId, kLittleEndianInput, kModality, kModalityImageDensityMap, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kSteps, kVerbose, kVersion, kVoxelSpacing, newDoseDist(), newROI(), scale, GMocrenDataPrimitive< T >::setMinMax(), GMocrenDataPrimitive< T >::setScale(), GMocrenDataPrimitive< T >::setSize(), G4InuclParticleNames::tp, VERLENGTH, and z.
Referenced by retrieveData().
bool G4GMocrenIO::retrieveData3 (char * _filename)
Definition at line 2617 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 2617 of file G4GMocrenIO.cc
References kFileName, and retrieveData().
bool G4GMocrenIO::retrieveData3 ()
Definition at line 2185 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 2185 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::addImage(), addPointerToDoseDistData(), addTrack(), addTrackColor(), convertEndian(), Acts::Logging::DEBUG, G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), in, int(), kComment, kDose, kDoseUnit, kFileName, kLittleEndianInput, kModality, kModalityImageDensityMap, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kVerbose, kVersion, kVoxelSpacing, newDoseDist(), newROI(), scale, setComment(), setDoseDistUnit(), GMocrenDataPrimitive< T >::setMinMax(), setModalityImageUnit(), GMocrenDataPrimitive< T >::setScale(), GMocrenDataPrimitive< T >::setSize(), G4InuclParticleNames::tp, and z.
Referenced by retrieveData().
bool G4GMocrenIO::retrieveData4 (char * _filename)
Definition at line 2179 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 2179 of file G4GMocrenIO.cc
References kFileName, and retrieveData().
bool G4GMocrenIO::retrieveData4 ()
Definition at line 1652 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1652 of file G4GMocrenIO.cc
References addDetector(), GMocrenDataPrimitive< T >::addImage(), addPointerToDoseDistData(), addTrack(), convertEndian(), Acts::Logging::DEBUG, G4VisManager::errors, G4cout, G4endl, G4VisManager::GetVerbosity(), in, int(), k, kComment, kDose, kDoseUnit, kFileName, kLittleEndianInput, kModality, kModalityImageDensityMap, kPointerToDetectorData, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kVerbose, kVersion, kVoxelSpacing, newDoseDist(), newROI(), scale, setComment(), setDoseDistName(), setDoseDistUnit(), GMocrenDataPrimitive< T >::setMinMax(), setModalityImageUnit(), GMocrenDataPrimitive< T >::setScale(), GMocrenDataPrimitive< T >::setSize(), propagation_timing::steps, and z.
Referenced by retrieveData().
void G4GMocrenIO::setComment (std::string & _comment) inline
Definition at line 275 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 275 of file G4GMocrenIO.hh
References kComment.
Referenced by retrieveData3(), and retrieveData4().
void G4GMocrenIO::setDoseDist (double * _image, int _num = 0)
Definition at line 3606 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3606 of file G4GMocrenIO.cc
References kDose.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::setDoseDistCenterPosition (float _center[3], int _num = 0)
Definition at line 3650 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3650 of file G4GMocrenIO.cc
References kDose.
void G4GMocrenIO::setDoseDistMinMax (short _minmax[2], int _num = 0)
Definition at line 3504 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3504 of file G4GMocrenIO.cc
References kDose, and scale.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::setDoseDistMinMax (double _minmax[2], int _num = 0)
Definition at line 3522 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3522 of file G4GMocrenIO.cc
References kDose.
void G4GMocrenIO::setDoseDistName (std::string _name, int _num = 0)
Definition at line 3662 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3662 of file G4GMocrenIO.cc
References kDose.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd(), and retrieveData4().
void G4GMocrenIO::setDoseDistScale (double & _scale, int _num = 0)
Definition at line 3535 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3535 of file G4GMocrenIO.cc
References kDose.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::setDoseDistSize (int _size[3], int _num = 0)
Definition at line 3497 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3497 of file G4GMocrenIO.cc
References kDose.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::setDoseDistUnit (std::string & _unit, int _num = 0)
Definition at line 3481 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3481 of file G4GMocrenIO.cc
References kDoseUnit.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd(), retrieveData3(), and retrieveData4().
void G4GMocrenIO::setFileName (std::string & _filename) inline
Definition at line 237 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 237 of file G4GMocrenIO.hh
References kFileName.
void G4GMocrenIO::setFileName (char * _filename) inline
Definition at line 238 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 238 of file G4GMocrenIO.hh
References kFileName.
void G4GMocrenIO::setID ()
Definition at line 3093 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3093 of file G4GMocrenIO.cc
References kId, t, Acts::VectorHelpers::time(), and G4InuclParticleNames::tm.
void G4GMocrenIO::setID (std::string & _id) inline
Definition at line 263 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 263 of file G4GMocrenIO.hh
References kId.
void G4GMocrenIO::setLittleEndianInput (bool _little)
Definition at line 3124 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3124 of file G4GMocrenIO.cc
References kLittleEndianInput.
void G4GMocrenIO::setLittleEndianOutput (bool _little)
Definition at line 3125 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3125 of file G4GMocrenIO.cc
References kLittleEndianOutput.
void G4GMocrenIO::setModalityCenterPosition (float _center[3])
Definition at line 3426 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3426 of file G4GMocrenIO.cc
References kModality, and GMocrenDataPrimitive< T >::setCenterPosition().
void G4GMocrenIO::setModalityImage (short * _image)
Definition at line 3382 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3382 of file G4GMocrenIO.cc
References GMocrenDataPrimitive< T >::addImage(), and kModality.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::setModalityImageDensityMap (std::vector< float > & _map)
Definition at line 3395 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3395 of file G4GMocrenIO.cc
References kModalityImageDensityMap.
Referenced by G4GMocrenFileSceneHandler::BeginSavingGdd().
void G4GMocrenIO::setModalityImageMinMax (short _minmax[2])
Definition at line 3402 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3402 of file G4GMocrenIO.cc
References kModality, and GMocrenDataPrimitive< T >::setMinMax().
Referenced by G4GMocrenFileSceneHandler::BeginSavingGdd().
void G4GMocrenIO::setModalityImageScale (double & _scale)
Definition at line 3372 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3372 of file G4GMocrenIO.cc
References kModality, and GMocrenDataPrimitive< T >::setScale().
void G4GMocrenIO::setModalityImageSize (int _size[3])
Definition at line 3366 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3366 of file G4GMocrenIO.cc
References kModality, and GMocrenDataPrimitive< T >::setSize().
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::setModalityImageUnit (std::string & _unit)
Definition at line 3441 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3441 of file G4GMocrenIO.cc
References kModalityUnit.
Referenced by retrieveData3(), and retrieveData4().
void G4GMocrenIO::setModalityImageVoxelSpacing (float _size[3])
void G4GMocrenIO::setNumberOfEvents (int & _numberOfEvents)
Definition at line 3139 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3139 of file G4GMocrenIO.cc
References kNumberOfEvents.
void G4GMocrenIO::setPointerToModalityData (unsigned int & _pointer)
Definition at line 3147 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3147 of file G4GMocrenIO.cc
References kPointerToModalityData.
Referenced by calcPointers2(), calcPointers3(), and calcPointers4().
void G4GMocrenIO::setPointerToROIData (unsigned int & _pointer)
Definition at line 3166 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3166 of file G4GMocrenIO.cc
References kPointerToROIData.
Referenced by calcPointers2(), calcPointers3(), and calcPointers4().
void G4GMocrenIO::setPointerToTrackData (unsigned int & _pointer)
Definition at line 3173 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3173 of file G4GMocrenIO.cc
References kPointerToTrackData.
Referenced by calcPointers2(), calcPointers3(), and calcPointers4().
void G4GMocrenIO::setROI (short * _image, int _num = 0)
Definition at line 3763 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3763 of file G4GMocrenIO.cc
References kRoi.
void G4GMocrenIO::setROICenterPosition (float _center[3], int _num = 0)
Definition at line 3799 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3799 of file G4GMocrenIO.cc
References kRoi.
void G4GMocrenIO::setROIMinMax (short _minmax[2], int _num = 0)
Definition at line 3787 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3787 of file G4GMocrenIO.cc
References kRoi.
void G4GMocrenIO::setROIScale (double & _scale, int _num = 0)
Definition at line 3751 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3751 of file G4GMocrenIO.cc
References kRoi.
void G4GMocrenIO::setROISize (int _size[3], int _num = 0)
Definition at line 3775 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3775 of file G4GMocrenIO.cc
References kRoi.
void G4GMocrenIO::setShortDoseDist (short * _image, int _num = 0)
Definition at line 3556 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3556 of file G4GMocrenIO.cc
References kDose, and scale.
void G4GMocrenIO::setTrackColors (std::vector< unsigned char * > & _trackColors)
Definition at line 3853 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3853 of file G4GMocrenIO.cc
References kStepColors.
void G4GMocrenIO::setTracks (std::vector< float * > & _tracks)
Definition at line 3844 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3844 of file G4GMocrenIO.cc
References kSteps.
void G4GMocrenIO::setVerboseLevel (int _level)
Definition at line 4045 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 4045 of file G4GMocrenIO.cc
References kVerbose.
void G4GMocrenIO::setVersion (std::string & _version)
Definition at line 3121 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3121 of file G4GMocrenIO.cc
References kVersion.
void G4GMocrenIO::setVoxelSpacing (float _spacing[3])
Definition at line 3128 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3128 of file G4GMocrenIO.cc
References kVoxelSpacing.
Referenced by G4GMocrenFileSceneHandler::AddSolid().
bool G4GMocrenIO::storeData (char * _filename)
Definition at line 457 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 457 of file G4GMocrenIO.cc
References storeData4().
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
bool G4GMocrenIO::storeData ()
Definition at line 453 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 453 of file G4GMocrenIO.cc
References storeData4().
Referenced by storeData2().
bool G4GMocrenIO::storeData2 (char * _filename)
Definition at line 1589 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1589 of file G4GMocrenIO.cc
References kFileName, and storeData().
bool G4GMocrenIO::storeData2 ()
Definition at line 1331 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1331 of file G4GMocrenIO.cc
References calcDoseDistScale(), calcPointers2(), Acts::Logging::DEBUG, G4cout, G4endl, GMocrenDataPrimitive< T >::getImage(), GMocrenDataPrimitive< T >::getMinMax(), GMocrenDataPrimitive< T >::getScale(), getShortDoseDist(), getShortDoseDistMinMax(), GMocrenDataPrimitive< T >::getSize(), IDLENGTH, int(), isDoseEmpty(), isROIEmpty(), kDose, kFileName, kId, kLittleEndianOutput, kModality, kModalityImageDensityMap, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kSteps, kVerbose, kVersion, kVoxelSpacing, ofile, scale, G4InuclParticleNames::tp, VERLENGTH, and z.
bool G4GMocrenIO::storeData3 (char * _filename)
bool G4GMocrenIO::storeData3 ()
Definition at line 1032 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1032 of file G4GMocrenIO.cc
References calcDoseDistScale(), calcPointers3(), Acts::Logging::DEBUG, G4VisManager::errors, G4cout, G4endl, getDoseDistCenterPosition(), getDoseDistScale(), GMocrenDataPrimitive< T >::getImage(), GMocrenDataPrimitive< T >::getMinMax(), getNumDoseDist(), GMocrenDataPrimitive< T >::getScale(), getShortDoseDist(), getShortDoseDistMinMax(), GMocrenDataPrimitive< T >::getSize(), G4VisManager::GetVerbosity(), int(), isDoseEmpty(), isROIEmpty(), kComment, kDose, kDoseUnit, kFileName, kLittleEndianOutput, kModality, kModalityImageDensityMap, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kStepColors, kSteps, kVerbose, kVoxelSpacing, ofile, scale, G4InuclParticleNames::tp, and z.
bool G4GMocrenIO::storeData4 (char * _filename)
Definition at line 1325 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 1325 of file G4GMocrenIO.cc
References kFileName, and storeData4().
bool G4GMocrenIO::storeData4 ()
Definition at line 461 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 461 of file G4GMocrenIO.cc
References calcDoseDistScale(), calcPointers4(), Acts::Logging::DEBUG, G4cout, G4endl, getDoseDistCenterPosition(), getDoseDistName(), getDoseDistScale(), GMocrenDataPrimitive< T >::getImage(), GMocrenDataPrimitive< T >::getMinMax(), getNumDoseDist(), GMocrenDataPrimitive< T >::getScale(), getShortDoseDist(), getShortDoseDistMinMax(), GMocrenDataPrimitive< T >::getSize(), int(), invertByteOrder(), isDoseEmpty(), isROIEmpty(), kComment, kDetectors, kDose, kDoseUnit, kFileName, kLittleEndianOutput, kModality, kModalityImageDensityMap, kPointerToDetectorData, kPointerToDoseDistData, kPointerToModalityData, kPointerToROIData, kPointerToTrackData, kRoi, kTracks, kTracksWillBeStored, kVerbose, kVoxelSpacing, ofile, scale, and z.
Referenced by storeData(), and storeData4().
void G4GMocrenIO::translateDetector (std::vector< float > & _translate)
Definition at line 4000 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 4000 of file G4GMocrenIO.cc
References kDetectors.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
void G4GMocrenIO::translateTracks (std::vector< float > & _translateo)
Definition at line 3934 of file G4GMocrenIO.cc.
View newest version in sPHENIX GitHub at line 3934 of file G4GMocrenIO.cc
References kTracks.
Referenced by G4GMocrenFileSceneHandler::EndSavingGdd().
Member Data Documentation
std::string G4GMocrenIO::kComment static
Definition at line 181 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 181 of file G4GMocrenIO.hh
Referenced by getComment(), initialize(), retrieveData3(), retrieveData4(), setComment(), storeData3(), and storeData4().
std::vector< class GMocrenDetector > G4GMocrenIO::kDetectors static
Definition at line 222 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 222 of file G4GMocrenIO.hh
Referenced by addDetector(), calcPointers4(), clearDetector(), getDetector(), getNumberOfDetectors(), storeData4(), and translateDetector().
std::vector< class GMocrenDataPrimitive< double > > G4GMocrenIO::kDose static
Definition at line 207 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 207 of file G4GMocrenIO.hh
Referenced by addDoseDist(), calcDoseDistScale(), clearDoseDistAll(), copyDoseDist(), getDoseDist(), getDoseDistCenterPosition(), getDoseDistMinMax(), getDoseDistName(), getDoseDistScale(), getDoseDistSize(), getNumDoseDist(), getShortDoseDist(), getShortDoseDistMinMax(), initialize(), isDoseEmpty(), mergeDoseDist(), newDoseDist(), retrieveData2(), retrieveData3(), retrieveData4(), setDoseDist(), setDoseDistCenterPosition(), setDoseDistMinMax(), setDoseDistName(), setDoseDistScale(), setDoseDistSize(), setShortDoseDist(), storeData2(), storeData3(), and storeData4().
std::string G4GMocrenIO::kDoseUnit = "keV " static
Definition at line 209 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 209 of file G4GMocrenIO.hh
Referenced by getDoseDistUnit(), initialize(), retrieveData3(), retrieveData4(), setDoseDistUnit(), storeData3(), and storeData4().
std::string G4GMocrenIO::kFileName = "dose.gdd" static
Definition at line 175 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 175 of file G4GMocrenIO.hh
Referenced by getFileName(), initialize(), retrieveData(), retrieveData2(), retrieveData3(), retrieveData4(), setFileName(), storeData2(), storeData3(), and storeData4().
std::string G4GMocrenIO::kId static
Definition at line 169 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 169 of file G4GMocrenIO.hh
Referenced by getID(), initialize(), retrieveData2(), setID(), and storeData2().
char G4GMocrenIO::kLittleEndianInput = true static
Definition at line 178 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 178 of file G4GMocrenIO.hh
Referenced by convertEndian(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), and setLittleEndianInput().
char G4GMocrenIO::kLittleEndianOutput = true static
Definition at line 179 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 179 of file G4GMocrenIO.hh
Referenced by convertEndian(), initialize(), setLittleEndianOutput(), storeData2(), storeData3(), and storeData4().
class GMocrenDataPrimitive< short > G4GMocrenIO::kModality static
Definition at line 201 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 201 of file G4GMocrenIO.hh
Referenced by clearModalityImage(), convertDensityToHU(), getModalityCenterPosition(), getModalityImage(), getModalityImageMax(), getModalityImageMin(), getModalityImageMinMax(), getModalityImageScale(), getModalityImageSize(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setModalityCenterPosition(), setModalityImage(), setModalityImageMinMax(), setModalityImageScale(), setModalityImageSize(), storeData2(), storeData3(), and storeData4().
std::vector< float > G4GMocrenIO::kModalityImageDensityMap static
Definition at line 203 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 203 of file G4GMocrenIO.hh
Referenced by convertDensityToHU(), getModalityImageDensityMap(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setModalityImageDensityMap(), storeData2(), storeData3(), and storeData4().
std::string G4GMocrenIO::kModalityUnit = "g/cm3 " static
Definition at line 204 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 204 of file G4GMocrenIO.hh
Referenced by getModalityImageUnit(), initialize(), and setModalityImageUnit().
int G4GMocrenIO::kNumberOfEvents = 0 static
Definition at line 184 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 184 of file G4GMocrenIO.hh
Referenced by addOneEvent(), getNumberOfEvents(), initialize(), and setNumberOfEvents().
unsigned int G4GMocrenIO::kPointerToDetectorData = 0 static
Definition at line 195 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 195 of file G4GMocrenIO.hh
Referenced by calcPointers4(), retrieveData4(), and storeData4().
std::vector< unsigned int > G4GMocrenIO::kPointerToDoseDistData static
Definition at line 189 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 189 of file G4GMocrenIO.hh
Referenced by addPointerToDoseDistData(), calcPointers2(), calcPointers3(), calcPointers4(), getPointerToDoseDistData(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), storeData2(), storeData3(), and storeData4().
unsigned int G4GMocrenIO::kPointerToModalityData = 0 static
Definition at line 187 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 187 of file G4GMocrenIO.hh
Referenced by getPointerToModalityData(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setPointerToModalityData(), storeData2(), storeData3(), and storeData4().
unsigned int G4GMocrenIO::kPointerToROIData = 0 static
Definition at line 191 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 191 of file G4GMocrenIO.hh
Referenced by getPointerToROIData(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setPointerToROIData(), storeData2(), storeData3(), and storeData4().
unsigned int G4GMocrenIO::kPointerToTrackData = 0 static
Definition at line 193 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 193 of file G4GMocrenIO.hh
Referenced by calcPointers4(), getPointerToTrackData(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setPointerToTrackData(), storeData2(), storeData3(), and storeData4().
std::vector< class GMocrenDataPrimitive< short > > G4GMocrenIO::kRoi static
Definition at line 212 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 212 of file G4GMocrenIO.hh
Referenced by clearROIAll(), getNumROI(), getROI(), getROICenterPosition(), getROIMinMax(), getROIScale(), getROISize(), initialize(), isROIEmpty(), newROI(), retrieveData2(), retrieveData3(), retrieveData4(), setROI(), setROICenterPosition(), setROIMinMax(), setROIScale(), setROISize(), storeData2(), storeData3(), and storeData4().
std::vector< unsigned char * > G4GMocrenIO::kStepColors static
Definition at line 216 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 216 of file G4GMocrenIO.hh
Referenced by addTrackColor(), copyTracks(), getTrackColors(), initialize(), setTrackColors(), and storeData3().
std::vector< float * > G4GMocrenIO::kSteps static
Definition at line 215 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 215 of file G4GMocrenIO.hh
Referenced by addTrack(), copyTracks(), getNumTracks(), getTracks(), initialize(), retrieveData2(), setTracks(), storeData2(), and storeData3().
std::vector< class GMocrenTrack > G4GMocrenIO::kTracks static
Definition at line 218 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 218 of file G4GMocrenIO.hh
Referenced by addTrack(), calcPointers4(), clearTracks(), getNumTracks4(), getTrack(), storeData4(), and translateTracks().
bool G4GMocrenIO::kTracksWillBeStored
Definition at line 219 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 219 of file G4GMocrenIO.hh
Referenced by initialize(), notStoredTracks(), and storeData4().
int G4GMocrenIO::kVerbose = 0 static
Definition at line 225 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 225 of file G4GMocrenIO.hh
Referenced by calcPointers4(), initialize(), mergeDoseDist(), retrieveData2(), retrieveData3(), retrieveData4(), setVerboseLevel(), storeData2(), storeData3(), and storeData4().
std::string G4GMocrenIO::kVersion = "2.0.0" static
Definition at line 172 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 172 of file G4GMocrenIO.hh
Referenced by getVersion(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setVersion(), and storeData2().
float G4GMocrenIO::kVoxelSpacing = {0., 0., 0.} static
Definition at line 198 of file G4GMocrenIO.hh.
View newest version in sPHENIX GitHub at line 198 of file G4GMocrenIO.hh
Referenced by getVoxelSpacing(), initialize(), retrieveData2(), retrieveData3(), retrieveData4(), setVoxelSpacing(), storeData2(), storeData3(), and storeData4().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/gMocren/include/G4GMocrenIO.hh
geant4/tree/geant4-10.6-release/source/visualization/gMocren/src/G4GMocrenIO.cc