ECCE @ EIC Software: CML2AcceleratorConstruction Class Reference
CML2AcceleratorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2AcceleratorConstruction.hh>
Public Member Functions
CML2AcceleratorConstruction (void)
~CML2AcceleratorConstruction (void)
bool Construct (G4VPhysicalVolume *PVWorld, G4bool bOnlyVisio)
G4VPhysicalVolume * getPhysicalVolume (void)
void resetAccelerator ()
void setAcceleratorName (G4String val)
void setAcceleratorMacFileName (G4String val)
G4String getCurrentRotationString ()
G4String getNextAcceleratorXRotationName ()
void setIsoCentre (G4double val)
void setRotation90Y (G4bool val)
void addAcceleratorRotationsX (G4double val)
G4double getAcceleratorIsoCentre ()
G4String getAcceleratorName ()
G4String getAcceleratorMacFileName ()
G4double getZ_Value_PhaseSpaceBeforeJaws ()
G4bool getRotation90Y ()
void writeInfo ()
G4RotationMatrix * rotateAccelerator ()
G4RotationMatrix * rotateAccelerator (G4double angleX)
Static Public Member Functions
static
CML2AcceleratorConstruction * GetInstance (void)
Private Member Functions
bool design (void)
Private Attributes
CML2AcceleratorConstructionMessenger * acceleratorConstructionMessenger
G4String AcceleratorName
G4String AcceleratorMacFileName
G4String nextAcceleratorXRotationName
G4VPhysicalVolume * PVAccWorld
G4int idCurrentRotationX
G4double currentRotationX
G4double isoCentre
G4double Z_Value_PhaseSpaceBeforeJaws
std::vector< G4double > rotationsX
G4ThreeVector initialCentre
G4bool bRotate90Y
G4bool bOnlyVisio
CML2Accelerator * accelerator
Static Private Attributes
static
CML2AcceleratorConstruction * instance = 0
Detailed Description
Definition at line 65 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file ML2AcceleratorConstruction.hh
Constructor & Destructor Documentation
CML2AcceleratorConstruction::CML2AcceleratorConstruction (void)
Definition at line 51 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 51 of file ML2AcceleratorConstruction.cc
CML2AcceleratorConstruction::~CML2AcceleratorConstruction (void)
Definition at line 57 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 57 of file ML2AcceleratorConstruction.cc
Member Function Documentation
void CML2AcceleratorConstruction::addAcceleratorRotationsX (G4double val) inline
Definition at line 84 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2AcceleratorConstruction.hh
References rotationsX.
bool CML2AcceleratorConstruction::Construct (G4VPhysicalVolume * PVWorld, G4bool bOnlyVisio)
Definition at line 113 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 113 of file ML2AcceleratorConstruction.cc
References pyEMSTDpl::Construct(), G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4NistManager::Instance(), mm, CLHEP::Hep3Vector::set(), and G4Colour::White().
bool CML2AcceleratorConstruction::design (void) private
Definition at line 77 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 77 of file ML2AcceleratorConstruction.cc
References G4UImanager::ApplyCommand(), G4cout, G4endl, CML2AccSaturn::GetInstance(), CML2Acc2::GetInstance(), CML2Acc1::GetInstance(), and G4UImanager::GetUIpointer().
G4double CML2AcceleratorConstruction::getAcceleratorIsoCentre () inline
Definition at line 86 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file ML2AcceleratorConstruction.hh
References isoCentre.
Referenced by main().
G4String CML2AcceleratorConstruction::getAcceleratorMacFileName () inline
Definition at line 88 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file ML2AcceleratorConstruction.hh
References AcceleratorMacFileName.
G4String CML2AcceleratorConstruction::getAcceleratorName () inline
Definition at line 87 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file ML2AcceleratorConstruction.hh
References AcceleratorName.
Referenced by CML2WorldConstruction::create().
G4String CML2AcceleratorConstruction::getCurrentRotationString ()
Definition at line 193 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 193 of file ML2AcceleratorConstruction.cc
References deg.
Referenced by CML2RunAction::BeginOfRunAction().
CML2AcceleratorConstruction * CML2AcceleratorConstruction::GetInstance (void) static
Definition at line 63 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 63 of file ML2AcceleratorConstruction.cc
References instance.
Referenced by CML2RunAction::BeginOfRunAction(), and CML2WorldConstruction::CML2WorldConstruction().
G4String CML2AcceleratorConstruction::getNextAcceleratorXRotationName () inline
Definition at line 80 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file ML2AcceleratorConstruction.hh
References nextAcceleratorXRotationName.
G4VPhysicalVolume* CML2AcceleratorConstruction::getPhysicalVolume (void) inline
Definition at line 72 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 72 of file ML2AcceleratorConstruction.hh
References PVAccWorld.
G4bool CML2AcceleratorConstruction::getRotation90Y () inline
Definition at line 90 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file ML2AcceleratorConstruction.hh
References bRotate90Y.
G4double CML2AcceleratorConstruction::getZ_Value_PhaseSpaceBeforeJaws () inline
Definition at line 89 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file ML2AcceleratorConstruction.hh
References Z_Value_PhaseSpaceBeforeJaws.
void CML2AcceleratorConstruction::resetAccelerator ()
Definition at line 72 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file ML2AcceleratorConstruction.cc
G4RotationMatrix * CML2AcceleratorConstruction::rotateAccelerator ()
Definition at line 156 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 156 of file ML2AcceleratorConstruction.cc
G4RotationMatrix * CML2AcceleratorConstruction::rotateAccelerator (G4double angleX)
Definition at line 171 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 171 of file ML2AcceleratorConstruction.cc
References G4GeometryManager::CloseGeometry(), deg, G4RunManager::GeometryHasBeenModified(), G4GeometryManager::GetInstance(), G4RunManager::GetRunManager(), CLHEP::inverseOf(), G4GeometryManager::OpenGeometry(), CLHEP::HepRotation::rotateX(), and CLHEP::HepRotation::rotateY().
void CML2AcceleratorConstruction::setAcceleratorMacFileName (G4String val) inline
Definition at line 76 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file ML2AcceleratorConstruction.hh
References AcceleratorMacFileName.
void CML2AcceleratorConstruction::setAcceleratorName (G4String val) inline
Definition at line 75 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2AcceleratorConstruction.hh
References AcceleratorName.
void CML2AcceleratorConstruction::setIsoCentre (G4double val) inline
Definition at line 81 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file ML2AcceleratorConstruction.hh
References isoCentre.
void CML2AcceleratorConstruction::setRotation90Y (G4bool val) inline
Definition at line 82 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file ML2AcceleratorConstruction.hh
References bRotate90Y.
void CML2AcceleratorConstruction::writeInfo ()
Definition at line 147 of file ML2AcceleratorConstruction.cc.
View newest version in sPHENIX GitHub at line 147 of file ML2AcceleratorConstruction.cc
References deg, G4cout, and G4endl.
Referenced by CML2RunAction::BeginOfRunAction().
Member Data Documentation
CML2Accelerator* CML2AcceleratorConstruction::accelerator private
Definition at line 110 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file ML2AcceleratorConstruction.hh
CML2AcceleratorConstructionMessenger* CML2AcceleratorConstruction::acceleratorConstructionMessenger private
Definition at line 98 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 98 of file ML2AcceleratorConstruction.hh
G4String CML2AcceleratorConstruction::AcceleratorMacFileName private
Definition at line 100 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file ML2AcceleratorConstruction.hh
Referenced by getAcceleratorMacFileName(), and setAcceleratorMacFileName().
G4String CML2AcceleratorConstruction::AcceleratorName private
Definition at line 100 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file ML2AcceleratorConstruction.hh
Referenced by getAcceleratorName(), and setAcceleratorName().
G4bool CML2AcceleratorConstruction::bOnlyVisio private
Definition at line 107 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file ML2AcceleratorConstruction.hh
G4bool CML2AcceleratorConstruction::bRotate90Y private
Definition at line 107 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file ML2AcceleratorConstruction.hh
Referenced by getRotation90Y(), and setRotation90Y().
G4double CML2AcceleratorConstruction::currentRotationX private
Definition at line 104 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file ML2AcceleratorConstruction.hh
G4int CML2AcceleratorConstruction::idCurrentRotationX private
Definition at line 103 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file ML2AcceleratorConstruction.hh
G4ThreeVector CML2AcceleratorConstruction::initialCentre private
Definition at line 106 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file ML2AcceleratorConstruction.hh
CML2AcceleratorConstruction * CML2AcceleratorConstruction::instance = 0 static private
Definition at line 99 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file ML2AcceleratorConstruction.hh
G4double CML2AcceleratorConstruction::isoCentre private
Definition at line 104 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file ML2AcceleratorConstruction.hh
Referenced by getAcceleratorIsoCentre(), and setIsoCentre().
G4String CML2AcceleratorConstruction::nextAcceleratorXRotationName private
Definition at line 100 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file ML2AcceleratorConstruction.hh
Referenced by getNextAcceleratorXRotationName().
G4VPhysicalVolume* CML2AcceleratorConstruction::PVAccWorld private
Definition at line 102 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file ML2AcceleratorConstruction.hh
Referenced by getPhysicalVolume().
std::vector<G4double> CML2AcceleratorConstruction::rotationsX private
Definition at line 105 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file ML2AcceleratorConstruction.hh
Referenced by addAcceleratorRotationsX().
G4double CML2AcceleratorConstruction::Z_Value_PhaseSpaceBeforeJaws private
Definition at line 104 of file ML2AcceleratorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file ML2AcceleratorConstruction.hh
Referenced by getZ_Value_PhaseSpaceBeforeJaws().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2AcceleratorConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2AcceleratorConstruction.cc