ECCE @ EIC Software: G4BasePhantomBuilder Class Reference
G4BasePhantomBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4BasePhantomBuilder.hh>
Public Member Functions
G4BasePhantomBuilder ()
virtual ~G4BasePhantomBuilder ()
virtual void BuildHead (const G4String &, G4bool, G4bool)
virtual void BuildTrunk (const G4String &, G4bool, G4bool)
virtual void BuildLeftLeg (const G4String &, G4bool, G4bool)
virtual void BuildRightLeg (const G4String &, G4bool, G4bool)
virtual void BuildUpperSpine (const G4String &, G4bool, G4bool)
virtual void BuildMiddleLowerSpine (const G4String &, G4bool, G4bool)
virtual void BuildLeftLegBone (const G4String &, G4bool, G4bool)
virtual void BuildRightLegBone (const G4String &, G4bool, G4bool)
virtual void BuildLeftArmBone (const G4String &, G4bool, G4bool)
virtual void BuildRightArmBone (const G4String &, G4bool, G4bool)
virtual void BuildSkull (const G4String &, G4bool, G4bool)
virtual void BuildRibCage (const G4String &, G4bool, G4bool)
virtual void BuildPelvis (const G4String &, G4bool, G4bool)
virtual void BuildLeftScapula (const G4String &, G4bool, G4bool)
virtual void BuildRightScapula (const G4String &, G4bool, G4bool)
virtual void BuildLeftClavicle (const G4String &, G4bool, G4bool)
virtual void BuildRightClavicle (const G4String &, G4bool, G4bool)
virtual void BuildBrain (const G4String &, G4bool, G4bool)
virtual void BuildHeart (const G4String &, G4bool, G4bool)
virtual void BuildLeftLung (const G4String &, G4bool, G4bool)
virtual void BuildRightLung (const G4String &, G4bool, G4bool)
virtual void BuildStomach (const G4String &, G4bool, G4bool)
virtual void BuildSmallIntestine (const G4String &, G4bool, G4bool)
virtual void BuildUpperLargeIntestine (const G4String &, G4bool, G4bool)
virtual void BuildLowerLargeIntestine (const G4String &, G4bool, G4bool)
virtual void BuildLeftKidney (const G4String &, G4bool, G4bool)
virtual void BuildRightKidney (const G4String &, G4bool, G4bool)
virtual void BuildLeftAdrenal (const G4String &, G4bool, G4bool)
virtual void BuildRightAdrenal (const G4String &, G4bool, G4bool)
virtual void BuildLiver (const G4String &, G4bool, G4bool)
virtual void BuildPancreas (const G4String &, G4bool, G4bool)
virtual void BuildSpleen (const G4String &, G4bool, G4bool)
virtual void BuildUrinaryBladder (const G4String &, G4bool, G4bool)
virtual void BuildThyroid (const G4String &, G4bool, G4bool)
virtual void BuildThymus (const G4String &, G4bool, G4bool)
virtual void BuildLeftOvary (const G4String &, G4bool, G4bool)
virtual void BuildRightOvary (const G4String &, G4bool, G4bool)
virtual void BuildUterus (const G4String &, G4bool, G4bool)
virtual void BuildLeftBreast (const G4String &, G4bool, G4bool)
virtual void BuildRightBreast (const G4String &, G4bool, G4bool)
virtual void BuildVoxelLeftBreast (const G4String &, G4bool, G4bool)
virtual void BuildVoxelRightBreast (const G4String &, G4bool, G4bool)
virtual void BuildMaleGenitalia (const G4String &, G4bool, G4bool)
virtual void BuildLeftTeste (const G4String &, G4bool, G4bool)
virtual void BuildRightTeste (const G4String &, G4bool, G4bool)
virtual void SetModel (G4String)
virtual void SetMotherVolume (G4VPhysicalVolume *)
virtual G4VPhysicalVolume * GetPhantom ()
Detailed Description
Definition at line 35 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 35 of file G4BasePhantomBuilder.hh
Constructor & Destructor Documentation
G4BasePhantomBuilder::G4BasePhantomBuilder ()
Definition at line 31 of file G4BasePhantomBuilder.cc.
View newest version in sPHENIX GitHub at line 31 of file G4BasePhantomBuilder.cc
G4BasePhantomBuilder::~G4BasePhantomBuilder () virtual
Definition at line 34 of file G4BasePhantomBuilder.cc.
View newest version in sPHENIX GitHub at line 34 of file G4BasePhantomBuilder.cc
Member Function Documentation
virtual void G4BasePhantomBuilder::BuildBrain (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder, and G4PhantomHeadBuilder.
Definition at line 61 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildHead (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder, and G4PhantomHeadBuilder.
Definition at line 42 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 42 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildHeart (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 62 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BasePhantomBuilder.hh
References return().
virtual void G4BasePhantomBuilder::BuildLeftAdrenal (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 71 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftArmBone (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 51 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 51 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftBreast (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4FemaleBuilder.
Definition at line 82 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftClavicle (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 58 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftKidney (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 69 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftLeg (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 44 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 44 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftLegBone (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 49 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 49 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftLung (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 63 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BasePhantomBuilder.hh
References return().
virtual void G4BasePhantomBuilder::BuildLeftOvary (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4CustomFemaleBuilder, and G4FemaleBuilder.
Definition at line 79 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftScapula (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 56 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildLeftTeste (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4MaleBuilder.
Definition at line 87 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4BasePhantomBuilder.hh
virtual void G4BasePhantomBuilder::BuildLiver (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 73 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4BasePhantomBuilder.hh
References return().
virtual void G4BasePhantomBuilder::BuildLowerLargeIntestine (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 68 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildMaleGenitalia (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4MaleBuilder.
Definition at line 86 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4BasePhantomBuilder.hh
virtual void G4BasePhantomBuilder::BuildMiddleLowerSpine (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 48 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 48 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildPancreas (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 74 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildPelvis (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 55 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 55 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRibCage (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 54 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightAdrenal (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 72 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightArmBone (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 52 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightBreast (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4FemaleBuilder.
Definition at line 83 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightClavicle (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 59 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightKidney (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 70 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightLeg (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 45 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 45 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightLegBone (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 50 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightLung (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 64 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BasePhantomBuilder.hh
References return().
virtual void G4BasePhantomBuilder::BuildRightOvary (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4CustomFemaleBuilder, and G4FemaleBuilder.
Definition at line 80 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightScapula (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 57 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildRightTeste (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4MaleBuilder.
Definition at line 88 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 88 of file G4BasePhantomBuilder.hh
virtual void G4BasePhantomBuilder::BuildSkull (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder, and G4PhantomHeadBuilder.
Definition at line 53 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 53 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildSmallIntestine (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 66 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildSpleen (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 75 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildStomach (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 65 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildThymus (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 78 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildThyroid (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 77 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4BasePhantomBuilder.hh
References return().
virtual void G4BasePhantomBuilder::BuildTrunk (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 43 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 43 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildUpperLargeIntestine (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 67 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildUpperSpine (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 47 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 47 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildUrinaryBladder (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4PhantomBuilder.
Definition at line 76 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildUterus (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4CustomFemaleBuilder, and G4FemaleBuilder.
Definition at line 81 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildVoxelLeftBreast (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4CustomFemaleBuilder.
Definition at line 84 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 84 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::BuildVoxelRightBreast (const G4String & , G4bool , G4bool) inline virtual
Reimplemented in G4CustomFemaleBuilder.
Definition at line 85 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual G4VPhysicalVolume* G4BasePhantomBuilder::GetPhantom () inline virtual
Reimplemented in G4PhantomBuilder, and G4PhantomHeadBuilder.
Definition at line 92 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::SetModel (G4String) inline virtual
Reimplemented in G4PhantomBuilder, and G4PhantomHeadBuilder.
Definition at line 90 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BasePhantomBuilder.hh
References return().
Referenced by G4HumanPhantomConstruction::Construct().
virtual void G4BasePhantomBuilder::SetMotherVolume (G4VPhysicalVolume *) inline virtual
Reimplemented in G4PhantomBuilder, and G4PhantomHeadBuilder.
Definition at line 91 of file G4BasePhantomBuilder.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BasePhantomBuilder.hh
Referenced by G4HumanPhantomConstruction::Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4BasePhantomBuilder.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4BasePhantomBuilder.cc