ECCE @ EIC Software: G4StatMFMacroTemperature Class Reference
G4StatMFMacroTemperature Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroTemperature.hh>
Public Member Functions
G4StatMFMacroTemperature (const G4double anA, const G4double aZ, const G4double ExEnergy, const G4double FreeE0, const G4double kappa, std::vector< G4VStatMFMacroCluster * > *ClusterVector)
~G4StatMFMacroTemperature ()
G4double operator() (const G4double T)
G4double GetMeanMultiplicity (void) const
G4double GetChemicalPotentialMu (void) const
G4double GetChemicalPotentialNu (void) const
G4double GetTemperature (void) const
G4double GetEntropy (void) const
G4double CalcTemperature (void)
Private Member Functions
G4StatMFMacroTemperature ()
G4StatMFMacroTemperature (const G4StatMFMacroTemperature &)
G4StatMFMacroTemperature & operator= (const G4StatMFMacroTemperature &right)
G4bool operator== (const G4StatMFMacroTemperature &right) const
G4bool operator!= (const G4StatMFMacroTemperature &right) const
G4double FragsExcitEnergy (const G4double T)
void CalcChemicalPotentialNu (const G4double T)
Private Attributes
G4double theA
G4double theZ
G4double _ExEnergy
G4double _FreeInternalE0
G4double _Kappa
G4double _MeanMultiplicity
G4double _MeanTemperature
G4double _ChemPotentialMu
G4double _ChemPotentialNu
G4double _MeanEntropy
std::vector
< G4VStatMFMacroCluster * > * _theClusters
Detailed Description
Definition at line 41 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 41 of file G4StatMFMacroTemperature.hh
Constructor & Destructor Documentation
G4StatMFMacroTemperature::G4StatMFMacroTemperature (const G4double anA, const G4double aZ, const G4double ExEnergy, const G4double FreeE0, const G4double kappa, std::vector< G4VStatMFMacroCluster * > * ClusterVector)
Definition at line 46 of file G4StatMFMacroTemperature.cc.
View newest version in sPHENIX GitHub at line 46 of file G4StatMFMacroTemperature.cc
G4StatMFMacroTemperature::~G4StatMFMacroTemperature ()
Definition at line 62 of file G4StatMFMacroTemperature.cc.
View newest version in sPHENIX GitHub at line 62 of file G4StatMFMacroTemperature.cc
G4StatMFMacroTemperature::G4StatMFMacroTemperature () private
G4StatMFMacroTemperature::G4StatMFMacroTemperature (const G4StatMFMacroTemperature &) inline private
Definition at line 61 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 61 of file G4StatMFMacroTemperature.hh
Member Function Documentation
void G4StatMFMacroTemperature::CalcChemicalPotentialNu (const G4double T) private
Definition at line 185 of file G4StatMFMacroTemperature.cc.
View newest version in sPHENIX GitHub at line 185 of file G4StatMFMacroTemperature.cc
References _ChemPotentialMu, _ChemPotentialNu, _Kappa, _MeanMultiplicity, _theClusters, G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), G4StatMFMacroChemicalPotential::GetChemicalPotentialMu(), G4StatMFMacroChemicalPotential::GetMeanMultiplicity(), theA, and theZ.
Referenced by FragsExcitEnergy().
G4double G4StatMFMacroTemperature::CalcTemperature (void)
Definition at line 65 of file G4StatMFMacroTemperature.cc.
View newest version in sPHENIX GitHub at line 65 of file G4StatMFMacroTemperature.cc
References _ExEnergy, _MeanTemperature, kdfinder::abs(), G4Solver< Function >::Brent(), G4Solver< Function >::Crenshaw(), e, G4cerr, G4cout, G4endl, G4Solver< Function >::GetRoot(), max, MeV, operator()(), G4Solver< Function >::SetIntervalLimits(), and theA.
Referenced by G4StatMFMacroCanonical::CalculateTemperature().
G4double G4StatMFMacroTemperature::FragsExcitEnergy (const G4double T) private
Definition at line 149 of file G4StatMFMacroTemperature.cc.
View newest version in sPHENIX GitHub at line 149 of file G4StatMFMacroTemperature.cc
References _FreeInternalE0, _Kappa, _MeanEntropy, _theClusters, G4Pow::A13(), CalcChemicalPotentialNu(), source.hepunit::elm_coupling, G4Pow::GetInstance(), G4StatMFParameters::GetKappaCoulomb(), G4StatMFParameters::Getr0(), pi, Acts::IntegrationTest::R, theA, theZ, and G4Pow::Z13().
Referenced by operator()().
G4double G4StatMFMacroTemperature::GetChemicalPotentialMu (void) const inline
Definition at line 73 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 73 of file G4StatMFMacroTemperature.hh
References _ChemPotentialMu.
Referenced by G4StatMFMacroCanonical::CalculateTemperature().
G4double G4StatMFMacroTemperature::GetChemicalPotentialNu (void) const inline
Definition at line 75 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 75 of file G4StatMFMacroTemperature.hh
References _ChemPotentialNu.
Referenced by G4StatMFMacroCanonical::CalculateTemperature().
G4double G4StatMFMacroTemperature::GetEntropy (void) const inline
Definition at line 79 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 79 of file G4StatMFMacroTemperature.hh
References _MeanEntropy.
Referenced by G4StatMFMacroCanonical::CalculateTemperature().
G4double G4StatMFMacroTemperature::GetMeanMultiplicity (void) const inline
Definition at line 71 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 71 of file G4StatMFMacroTemperature.hh
References _MeanMultiplicity.
Referenced by G4StatMFMacroCanonical::CalculateTemperature().
G4double G4StatMFMacroTemperature::GetTemperature (void) const inline
Definition at line 77 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 77 of file G4StatMFMacroTemperature.hh
References _MeanTemperature.
G4bool G4StatMFMacroTemperature::operator!= (const G4StatMFMacroTemperature & right) const private
G4double G4StatMFMacroTemperature::operator() (const G4double T) inline
Definition at line 52 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 52 of file G4StatMFMacroTemperature.hh
References _ExEnergy, and FragsExcitEnergy().
Referenced by CalcTemperature().
G4StatMFMacroTemperature& G4StatMFMacroTemperature::operator= (const G4StatMFMacroTemperature & right) private
G4bool G4StatMFMacroTemperature::operator== (const G4StatMFMacroTemperature & right) const private
Member Data Documentation
G4double G4StatMFMacroTemperature::_ChemPotentialMu private
Definition at line 105 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 105 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), and GetChemicalPotentialMu().
G4double G4StatMFMacroTemperature::_ChemPotentialNu private
Definition at line 107 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 107 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), and GetChemicalPotentialNu().
G4double G4StatMFMacroTemperature::_ExEnergy private
Definition at line 95 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 95 of file G4StatMFMacroTemperature.hh
Referenced by CalcTemperature(), and operator()().
G4double G4StatMFMacroTemperature::_FreeInternalE0 private
Definition at line 97 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 97 of file G4StatMFMacroTemperature.hh
Referenced by FragsExcitEnergy().
G4double G4StatMFMacroTemperature::_Kappa private
Definition at line 99 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 99 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), and FragsExcitEnergy().
G4double G4StatMFMacroTemperature::_MeanEntropy private
Definition at line 109 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 109 of file G4StatMFMacroTemperature.hh
Referenced by FragsExcitEnergy(), and GetEntropy().
G4double G4StatMFMacroTemperature::_MeanMultiplicity private
Definition at line 101 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 101 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), and GetMeanMultiplicity().
G4double G4StatMFMacroTemperature::_MeanTemperature private
Definition at line 103 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 103 of file G4StatMFMacroTemperature.hh
Referenced by CalcTemperature(), and GetTemperature().
std::vector<G4VStatMFMacroCluster*>* G4StatMFMacroTemperature::_theClusters private
Definition at line 111 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 111 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), and FragsExcitEnergy().
G4double G4StatMFMacroTemperature::theA private
Definition at line 91 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 91 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), CalcTemperature(), and FragsExcitEnergy().
G4double G4StatMFMacroTemperature::theZ private
Definition at line 93 of file G4StatMFMacroTemperature.hh.
View newest version in sPHENIX GitHub at line 93 of file G4StatMFMacroTemperature.hh
Referenced by CalcChemicalPotentialNu(), and FragsExcitEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroTemperature.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMacroTemperature.cc