ECCE @ EIC Software: G4UserEventAction Class Reference
G4UserEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4UserEventAction.hh>
Inherited by B1EventAction, B1EventAction, B1EventAction, B2EventAction, B2EventAction, B2EventAction, B3aEventAction, B4aEventAction, B4aEventAction, B4bEventAction, B4cEventAction, B4dEventAction, B5EventAction, CB_G4UserEventAction, CCalEventAction, CexmcEventAction, CML2EventAction, demo.MyEventAction, DicomEventAction, DMXEventAction, doiPETEventAction, eRositaEventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, ExGflashEventAction, ExGflashEventAction, ExGflashEventAction, ExGflashEventAction, ExN02EventAction, ExN04EventAction, ExN04EventAction, ExP01EventAction, F04EventAction, FCALTBEventAction, FW::Geant4::MMEventAction, G4BlineEventAction, G4HumanPhantomEventAction, G4MultiEventAction, GammaRayTelEventAction, H02EventAction, HadrontherapyEventAction, IORTEventAction, LXeEventAction, MCTruthEventAction, Par02EventAction, PHG4PhenixEventAction, PurgMagEventAction, QEventAction, RE01EventAction, RE02EventAction, RE04EventAction, RE05EventAction, RMC01AdjointEventAction, RMC01EventAction, root_test.MyEventAction, run.MyEventAction, test.MyEventAction, test.MyEventAction, UltraEventAction, WLSEventAction, and XrayFluoEventAction.
Public Member Functions
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
virtual void BeginOfEventAction (const G4Event *anEvent)
virtual void EndOfEventAction (const G4Event *anEvent)
Protected Attributes
G4EventManager * fpEventManager
Detailed Description
Definition at line 50 of file G4UserEventAction.hh.
View newest version in sPHENIX GitHub at line 50 of file G4UserEventAction.hh
Constructor & Destructor Documentation
G4UserEventAction::G4UserEventAction ()
Definition at line 35 of file G4UserEventAction.cc.
View newest version in sPHENIX GitHub at line 35 of file G4UserEventAction.cc
References FatalException, G4Exception(), and G4ParticleTable::GetParticleTable().
G4UserEventAction::~G4UserEventAction () virtual
Definition at line 51 of file G4UserEventAction.cc.
View newest version in sPHENIX GitHub at line 51 of file G4UserEventAction.cc
Member Function Documentation
void G4UserEventAction::BeginOfEventAction (const G4Event * anEvent) virtual
Reimplemented in B4aEventAction, CexmcEventAction, G4MultiEventAction, G4BlineEventAction, UltraEventAction, DMXEventAction, XrayFluoEventAction, RMC01AdjointEventAction, EventAction, EventAction, EventAction, GammaRayTelEventAction, EventAction, EventAction, Par02EventAction, RMC01EventAction, DicomEventAction, EventAction, EventAction, doiPETEventAction, CML2EventAction, IORTEventAction, B5EventAction, RE02EventAction, PurgMagEventAction, MCTruthEventAction, EventAction, RE04EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, WLSEventAction, ExP01EventAction, FW::Geant4::MMEventAction, FCALTBEventAction, B4cEventAction, EventAction, EventAction, EventAction, EventAction, EventAction, LXeEventAction, EventAction, B3aEventAction, B4aEventAction, B4dEventAction, EventAction, EventAction, EventAction, EventAction, ExN02EventAction, CCalEventAction, EventAction, F04EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, B4bEventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, QEventAction, B1EventAction, B1EventAction, RE01EventAction, eRositaEventAction, HadrontherapyEventAction, G4HumanPhantomEventAction, B2EventAction, B2EventAction, B2EventAction, B1EventAction, ExN04EventAction, RE05EventAction, CB_G4UserEventAction, EventAction, EventAction, ExGflashEventAction, ExN04EventAction, ExGflashEventAction, ExGflashEventAction, ExGflashEventAction, H02EventAction, EventAction, EventAction, EventAction, and PHG4PhenixEventAction.
Definition at line 54 of file G4UserEventAction.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UserEventAction.cc
Referenced by CB_G4UserEventAction::BeginOfEventAction(), G4EventManager::DoProcessing(), and export_G4UserEventAction().
void G4UserEventAction::EndOfEventAction (const G4Event * anEvent) virtual
Reimplemented in B4aEventAction, CexmcEventAction, G4MultiEventAction, G4BlineEventAction, UltraEventAction, DMXEventAction, XrayFluoEventAction, RMC01AdjointEventAction, Par02EventAction, EventAction, EventAction, EventAction, GammaRayTelEventAction, EventAction, EventAction, RMC01EventAction, DicomEventAction, EventAction, EventAction, doiPETEventAction, CML2EventAction, FW::Geant4::MMEventAction, IORTEventAction, B5EventAction, EventAction, RE02EventAction, PurgMagEventAction, MCTruthEventAction, RE04EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, WLSEventAction, ExP01EventAction, FCALTBEventAction, B4cEventAction, EventAction, EventAction, EventAction, EventAction, EventAction, LXeEventAction, CB_G4UserEventAction, EventAction, B3aEventAction, B4aEventAction, B4dEventAction, EventAction, EventAction, EventAction, EventAction, ExN02EventAction, CCalEventAction, EventAction, F04EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, B4bEventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, EventAction, QEventAction, B1EventAction, B1EventAction, RE01EventAction, eRositaEventAction, HadrontherapyEventAction, G4HumanPhantomEventAction, B2EventAction, B2EventAction, B2EventAction, B1EventAction, ExN04EventAction, RE05EventAction, EventAction, EventAction, ExGflashEventAction, ExN04EventAction, ExGflashEventAction, ExGflashEventAction, ExGflashEventAction, H02EventAction, EventAction, EventAction, EventAction, and PHG4PhenixEventAction.
Definition at line 57 of file G4UserEventAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UserEventAction.cc
Referenced by G4EventManager::DoProcessing(), CB_G4UserEventAction::EndOfEventAction(), and export_G4UserEventAction().
virtual void G4UserEventAction::SetEventManager (G4EventManager * value) inline virtual
Reimplemented in G4MultiEventAction.
Definition at line 55 of file G4UserEventAction.hh.
View newest version in sPHENIX GitHub at line 55 of file G4UserEventAction.hh
References fpEventManager.
Referenced by G4EventManager::SetUserAction().
Member Data Documentation
G4EventManager* G4UserEventAction::fpEventManager protected
Definition at line 62 of file G4UserEventAction.hh.
View newest version in sPHENIX GitHub at line 62 of file G4UserEventAction.hh
Referenced by RE01EventAction::EndOfEventAction(), F04EventAction::GetEventNo(), WLSEventAction::GetEventNo(), and SetEventManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4UserEventAction.hh
geant4/tree/geant4-10.6-release/source/event/src/G4UserEventAction.cc