ECCE @ EIC Software: G4ASTARStopping Class Reference
G4ASTARStopping Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4ASTARStopping.hh>
Public Member Functions
G4ASTARStopping ()
~G4ASTARStopping ()
void Initialise ()
G4int GetIndex (const G4Material *) const
G4int GetIndex (const G4String &) const
G4double GetElectronicDEDX (G4int idx, G4double energy) const
G4double GetElectronicDEDX (const G4Material *, G4double energy) const
Private Member Functions
void AddData (const G4float *s, const G4Material *)
void FindData (G4int idx, const G4Material *)
void PrintWarning (G4int idx) const
G4ASTARStopping & operator= (const G4ASTARStopping &right)=delete
G4ASTARStopping (const G4ASTARStopping &)=delete
Private Attributes
size_t nvectors
G4double emin
std::vector< const G4Material * > materials
std::vector
< G4LPhysicsFreeVector * > sdata
Detailed Description
Definition at line 61 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ASTARStopping.hh
Constructor & Destructor Documentation
G4ASTARStopping::G4ASTARStopping () explicit
Definition at line 54 of file G4ASTARStopping.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ASTARStopping.cc
References Initialise().
G4ASTARStopping::~G4ASTARStopping ()
Definition at line 62 of file G4ASTARStopping.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ASTARStopping.cc
References nvectors, and sdata.
G4ASTARStopping::G4ASTARStopping (const G4ASTARStopping &) private delete
Member Function Documentation
void G4ASTARStopping::AddData (const G4float * s, const G4Material * mat) private
Definition at line 352 of file G4ASTARStopping.cc.
View newest version in sPHENIX GitHub at line 352 of file G4ASTARStopping.cc
References fac, G4PhysicsVector::FillSecondDerivatives(), materials, nvectors, G4LPhysicsFreeVector::PutValues(), sdata, G4PhysicsVector::SetSpline(), T0, and v.
Referenced by FindData().
void G4ASTARStopping::FindData (G4int idx, const G4Material * mat) private
Definition at line 124 of file G4ASTARStopping.cc.
View newest version in sPHENIX GitHub at line 124 of file G4ASTARStopping.cc
References AddData(), e1, e2, e3, e4, e5, e6, and f.
Referenced by Initialise().
G4double G4ASTARStopping::GetElectronicDEDX (G4int idx, G4double energy) const inline
Definition at line 128 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ASTARStopping.hh
References emin, incremental_prev_tag::idx, nvectors, PrintWarning(), and sdata.
Referenced by G4BraggIonModel::DEDX(), and GetElectronicDEDX().
G4double G4ASTARStopping::GetElectronicDEDX (const G4Material * mat, G4double energy) const inline
Definition at line 140 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ASTARStopping.hh
References GetElectronicDEDX(), and GetIndex().
G4int G4ASTARStopping::GetIndex (const G4Material * mat) const inline
Definition at line 99 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ASTARStopping.hh
References incremental_prev_tag::idx, materials, and nvectors.
Referenced by G4BraggIonModel::DEDX(), and GetElectronicDEDX().
G4int G4ASTARStopping::GetIndex (const G4String & nam) const inline
Definition at line 113 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ASTARStopping.hh
References incremental_prev_tag::idx, materials, and nvectors.
void G4ASTARStopping::Initialise ()
Definition at line 81 of file G4ASTARStopping.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ASTARStopping.cc
References FindData(), G4Material::GetChemicalFormula(), G4Material::GetMaterialTable(), G4Material::GetName(), G4Material::GetNumberOfMaterials(), mat, materials, molecularIndex, molecularName, nameNIST, numberOfMolecula, and nvectors.
Referenced by G4ASTARStopping(), and G4BraggIonModel::Initialise().
G4ASTARStopping& G4ASTARStopping::operator= (const G4ASTARStopping & right) private delete
void G4ASTARStopping::PrintWarning (G4int idx) const private
Definition at line 71 of file G4ASTARStopping.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ASTARStopping.cc
References G4Exception(), JustWarning, and nvectors.
Referenced by GetElectronicDEDX().
Member Data Documentation
G4double G4ASTARStopping::emin private
Definition at line 92 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ASTARStopping.hh
Referenced by GetElectronicDEDX().
std::vector<const G4Material*> G4ASTARStopping::materials private
Definition at line 93 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ASTARStopping.hh
Referenced by AddData(), GetIndex(), and Initialise().
size_t G4ASTARStopping::nvectors private
Definition at line 91 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ASTARStopping.hh
Referenced by AddData(), GetElectronicDEDX(), GetIndex(), Initialise(), PrintWarning(), and ~G4ASTARStopping().
std::vector<G4LPhysicsFreeVector*> G4ASTARStopping::sdata private
Definition at line 94 of file G4ASTARStopping.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ASTARStopping.hh
Referenced by AddData(), GetElectronicDEDX(), and ~G4ASTARStopping().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4ASTARStopping.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4ASTARStopping.cc