ECCE @ EIC Software: G4EmExtraParametersMessenger Class Reference
G4EmExtraParametersMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmExtraParametersMessenger.hh>
Public Member Functions
G4EmExtraParametersMessenger (G4EmExtraParameters *)
virtual ~G4EmExtraParametersMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String) override
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4EmExtraParameters * theParameters
G4UIcmdWithABool * dirSplitCmd
G4UIcmdWithABool * qeCmd
G4UIcmdWithADoubleAndUnit * dirSplitRadiusCmd
G4UIcommand * paiCmd
G4UIcommand * mscoCmd
G4UIcommand * SubSecCmd
G4UIcommand * bfCmd
G4UIcommand * fiCmd
G4UIcommand * bsCmd
G4UIcommand * StepFuncCmd
G4UIcommand * StepFuncCmd1
G4UIcmdWith3VectorAndUnit * dirSplitTargetCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 64 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4EmExtraParametersMessenger.hh
Constructor & Destructor Documentation
G4EmExtraParametersMessenger::G4EmExtraParametersMessenger (G4EmExtraParameters * ptr) explicit
Definition at line 58 of file G4EmExtraParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 58 of file G4EmExtraParametersMessenger.cc
References G4UIcommand::AvailableForStates(), bfCmd, bsCmd, dirSplitCmd, dirSplitRadiusCmd, dirSplitTargetCmd, fiCmd, G4State_Idle, G4State_PreInit, mscoCmd, paiCmd, part, qeCmd, G4UIparameter::SetDefaultUnit(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIparameter::SetParameterRange(), StepFuncCmd, StepFuncCmd1, and SubSecCmd.
G4EmExtraParametersMessenger::~G4EmExtraParametersMessenger () virtual
Definition at line 227 of file G4EmExtraParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 227 of file G4EmExtraParametersMessenger.cc
References bfCmd, bsCmd, dirSplitCmd, dirSplitRadiusCmd, dirSplitTargetCmd, fiCmd, mscoCmd, paiCmd, qeCmd, StepFuncCmd, StepFuncCmd1, and SubSecCmd.
Member Function Documentation
void G4EmExtraParametersMessenger::SetNewValue (G4UIcommand * command, G4String newValue) override virtual
Reimplemented from G4UImessenger.
Definition at line 245 of file G4EmExtraParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 245 of file G4EmExtraParametersMessenger.cc
References G4EmExtraParameters::ActivateForcedInteraction(), G4EmExtraParameters::ActivateSecondaryBiasing(), G4EmExtraParameters::AddPAIModel(), G4EmExtraParameters::AddPhysics(), G4UImanager::ApplyCommand(), bfCmd, bsCmd, dirSplitCmd, dirSplitRadiusCmd, dirSplitTargetCmd, e, fb(), fiCmd, G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UImanager::GetUIpointer(), mscoCmd, paiCmd, qeCmd, r, G4InuclParticleNames::s0, s1, G4EmExtraParameters::SetDirectionalSplitting(), G4EmExtraParameters::SetDirectionalSplittingRadius(), G4EmExtraParameters::SetDirectionalSplittingTarget(), G4EmExtraParameters::SetProcessBiasingFactor(), G4EmExtraParameters::SetQuantumEntanglement(), G4EmExtraParameters::SetStepFunction(), G4EmExtraParameters::SetStepFunctionMuHad(), G4EmExtraParameters::SetSubCutoff(), StepFuncCmd, StepFuncCmd1, SubSecCmd, t, theParameters, v1, v2, and G4UIcommand::ValueOf().
Member Data Documentation
G4UIcommand* G4EmExtraParametersMessenger::bfCmd private
Definition at line 86 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::bsCmd private
Definition at line 88 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcmdWithABool* G4EmExtraParametersMessenger::dirSplitCmd private
Definition at line 77 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcmdWithADoubleAndUnit* G4EmExtraParametersMessenger::dirSplitRadiusCmd private
Definition at line 80 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcmdWith3VectorAndUnit* G4EmExtraParametersMessenger::dirSplitTargetCmd private
Definition at line 92 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::fiCmd private
Definition at line 87 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::mscoCmd private
Definition at line 83 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::paiCmd private
Definition at line 82 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcmdWithABool* G4EmExtraParametersMessenger::qeCmd private
Definition at line 78 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::StepFuncCmd private
Definition at line 89 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::StepFuncCmd1 private
Definition at line 90 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4UIcommand* G4EmExtraParametersMessenger::SubSecCmd private
Definition at line 85 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4EmExtraParametersMessenger.hh
Referenced by G4EmExtraParametersMessenger(), SetNewValue(), and ~G4EmExtraParametersMessenger().
G4EmExtraParameters* G4EmExtraParametersMessenger::theParameters private
Definition at line 75 of file G4EmExtraParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4EmExtraParametersMessenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmExtraParametersMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmExtraParametersMessenger.cc