ECCE @ EIC Software: G4AttCheck Class Reference
G4AttCheck Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4AttCheck.hh>
Public Member Functions
G4AttCheck (const std::vector< G4AttValue > *values, const std::map< G4String, G4AttDef > *definitions)
~G4AttCheck ()
const std::vector< G4AttValue > * GetAttValues () const
const std::map< G4String,
G4AttDef > * GetAttDefs () const
G4bool Check (const G4String &leader="") const
G4bool Standard (std::vector< G4AttValue > *standardValues, std::map< G4String, G4AttDef > *standardDefinitions) const
Private Member Functions
void AddValuesAndDefs (std::vector< G4AttValue > *newValues, std::map< G4String, G4AttDef > *newDefinitions, const G4String &oldName, const G4String &name, const G4String &value, const G4String &extra, const G4String &description="") const
void Init ()
Private Attributes
const std::vector< G4AttValue > * fpValues
const std::map< G4String,
G4AttDef > * fpDefinitions
Static Private Attributes
static G4ThreadLocal G4bool fFirst = true
static G4ThreadLocal std::set
< G4String > * fUnitCategories = 0
static G4ThreadLocal std::map
< G4String, G4String > * fStandardUnits = 0
static G4ThreadLocal std::set
< G4String > * fCategories = 0
static G4ThreadLocal std::set
< G4String > * fUnits = 0
static G4ThreadLocal std::set
< G4String > * fValueTypes = 0
Friends
std::ostream & operator<< (std::ostream &, const G4AttCheck &)
Detailed Description
Definition at line 56 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 56 of file G4AttCheck.hh
Constructor & Destructor Documentation
G4AttCheck::G4AttCheck (const std::vector< G4AttValue > * values, const std::map< G4String, G4AttDef > * definitions)
Definition at line 51 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 51 of file G4AttCheck.cc
References G4UnitDefinition::GetUnitsTable(), and lightions::Init().
G4AttCheck::~G4AttCheck ()
Definition at line 109 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 109 of file G4AttCheck.cc
Member Function Documentation
void G4AttCheck::AddValuesAndDefs (std::vector< G4AttValue > * newValues, std::map< G4String, G4AttDef > * newDefinitions, const G4String & oldName, const G4String & name, const G4String & value, const G4String & extra, const G4String & description = "") const private
Definition at line 331 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 331 of file G4AttCheck.cc
References fpDefinitions.
Referenced by Standard().
G4bool G4AttCheck::Check (const G4String & leader = "") const
Definition at line 122 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 122 of file G4AttCheck.cc
References error, fCategories, fpDefinitions, fpValues, fUnits, fValueTypes, G4cerr, G4endl, G4ThreadLocal, and print().
Referenced by G4XXXStoredSceneHandler::PreAddSolid().
const std::map<G4String,G4AttDef>* G4AttCheck::GetAttDefs () const inline
Definition at line 70 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 70 of file G4AttCheck.hh
References fpDefinitions.
const std::vector<G4AttValue>* G4AttCheck::GetAttValues () const inline
Definition at line 66 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 66 of file G4AttCheck.hh
References fpValues.
void G4AttCheck::Init () private
Definition at line 113 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 113 of file G4AttCheck.cc
References fCategories, fStandardUnits, fUnitCategories, fUnits, and fValueTypes.
G4bool G4AttCheck::Standard (std::vector< G4AttValue > * standardValues, std::map< G4String, G4AttDef > * standardDefinitions) const
Definition at line 350 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 350 of file G4AttCheck.cc
References AddValuesAndDefs(), G4UIcommand::ConvertTo3Vector(), G4UIcommand::ConvertToDimensioned3Vector(), G4UIcommand::ConvertToDimensionedDouble(), G4UIcommand::ConvertToString(), error, fCategories, fpDefinitions, fpValues, fUnitCategories, fUnits, fValueTypes, G4cerr, G4endl, G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), G4String::strip(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4XXXStoredSceneHandler::PreAddSolid().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4AttCheck & ac) friend
Definition at line 248 of file G4AttCheck.cc.
View newest version in sPHENIX GitHub at line 248 of file G4AttCheck.cc
Member Data Documentation
G4ThreadLocal std::set< G4String > * G4AttCheck::fCategories = 0 static private
Definition at line 105 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AttCheck.hh
Referenced by Check(), Init(), operator<<(), and Standard().
G4ThreadLocal G4bool G4AttCheck::fFirst = true static private
Definition at line 102 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AttCheck.hh
const std::map<G4String,G4AttDef>* G4AttCheck::fpDefinitions private
Definition at line 100 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AttCheck.hh
Referenced by AddValuesAndDefs(), Check(), GetAttDefs(), operator<<(), and Standard().
const std::vector<G4AttValue>* G4AttCheck::fpValues private
Definition at line 99 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AttCheck.hh
Referenced by Check(), GetAttValues(), operator<<(), and Standard().
G4ThreadLocal std::map< G4String, G4String > * G4AttCheck::fStandardUnits = 0 static private
Definition at line 104 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AttCheck.hh
Referenced by Init().
G4ThreadLocal std::set< G4String > * G4AttCheck::fUnitCategories = 0 static private
Definition at line 103 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AttCheck.hh
Referenced by Init(), and Standard().
G4ThreadLocal std::set< G4String > * G4AttCheck::fUnits = 0 static private
Definition at line 106 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AttCheck.hh
Referenced by Check(), Init(), operator<<(), and Standard().
G4ThreadLocal std::set< G4String > * G4AttCheck::fValueTypes = 0 static private
Definition at line 107 of file G4AttCheck.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AttCheck.hh
Referenced by Check(), Init(), operator<<(), and Standard().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4AttCheck.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4AttCheck.cc