ECCE @ EIC Software: G4QGSPPionBuilder Class Reference
G4QGSPPionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPPionBuilder.hh>
Public Member Functions
G4QGSPPionBuilder (G4bool quasiElastic=false)
virtual ~G4QGSPPionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPionBuilder
G4VPionBuilder ()=default
virtual ~G4VPionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4QGSMFragmentation * theQGSM
G4double theMin
Detailed Description
Definition at line 58 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QGSPPionBuilder.hh
Constructor & Destructor Documentation
G4QGSPPionBuilder::G4QGSPPionBuilder (G4bool quasiElastic = false)
Definition at line 52 of file G4QGSPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 52 of file G4QGSPPionBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSPPionBuilder::~G4QGSPPionBuilder () virtual
Definition at line 75 of file G4QGSPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 75 of file G4QGSPPionBuilder.cc
References theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSPPionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPionBuilder.
Definition at line 65 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QGSPPionBuilder.hh
void G4QGSPPionBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 84 of file G4QGSPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 84 of file G4QGSPPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSPPionBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 93 of file G4QGSPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 93 of file G4QGSPPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSPPionBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 69 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QGSPPionBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4QGSPPionBuilder::theCascade private
Definition at line 75 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSPPionBuilder.hh
Referenced by G4QGSPPionBuilder().
G4double G4QGSPPionBuilder::theMin private
Definition at line 80 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QGSPPionBuilder.hh
Referenced by Build(), G4QGSPPionBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSPPionBuilder::theModel private
Definition at line 74 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSPPionBuilder.hh
Referenced by Build(), and G4QGSPPionBuilder().
G4QGSMFragmentation* G4QGSPPionBuilder::theQGSM private
Definition at line 79 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QGSPPionBuilder.hh
Referenced by G4QGSPPionBuilder(), and ~G4QGSPPionBuilder().
G4QuasiElasticChannel* G4QGSPPionBuilder::theQuasiElastic private
Definition at line 78 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPPionBuilder.hh
Referenced by G4QGSPPionBuilder(), and ~G4QGSPPionBuilder().
G4ExcitedStringDecay* G4QGSPPionBuilder::theStringDecay private
Definition at line 77 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSPPionBuilder.hh
Referenced by G4QGSPPionBuilder(), and ~G4QGSPPionBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSPPionBuilder::theStringModel private
Definition at line 76 of file G4QGSPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSPPionBuilder.hh
Referenced by G4QGSPPionBuilder(), and ~G4QGSPPionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPPionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSPPionBuilder.cc