ECCE @ EIC Software: G4QMDGroundStateNucleus Class Reference
G4QMDGroundStateNucleus Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDGroundStateNucleus.hh>
Public Member Functions
G4QMDGroundStateNucleus ()
G4QMDGroundStateNucleus (G4int z, G4int a)
~G4QMDGroundStateNucleus ()
Public Member Functions inherited from G4QMDNucleus
G4QMDNucleus ()
G4LorentzVector Get4Momentum ()
G4int GetMassNumber ()
G4int GetAtomicNumber ()
void CalEnergyAndAngularMomentumInCM ()
G4double GetNuclearMass ()
void SetTotalPotential (G4double x)
G4double GetExcitationEnergy ()
G4int GetAngularMomentum ()
Public Member Functions inherited from G4QMDSystem
G4QMDSystem ()
virtual ~G4QMDSystem ()
void SetParticipant (G4QMDParticipant *particle)
void SetSystem (G4QMDSystem *, G4ThreeVector, G4ThreeVector)
void SubtractSystem (G4QMDSystem *)
G4QMDParticipant * EraseParticipant (G4int i)
void DeleteParticipant (G4int i)
void InsertParticipant (G4QMDParticipant *particle, G4int j)
G4int GetTotalNumberOfParticipant ()
G4QMDParticipant * GetParticipant (G4int i)
void IncrementCollisionCounter ()
G4int GetNOCollision ()
void ShowParticipants ()
void Clear ()
Private Member Functions
void packNucleons ()
void killCMMotionAndAngularM ()
G4bool samplingPosition (G4int)
G4bool samplingMomentum (G4int)
Private Attributes
G4int maxTrial
G4double r00
G4double r01
G4double saa
G4double rada
G4double radb
G4double dsam
G4double ddif
G4double dsam2
G4double ddif2
G4double cdp
G4double c0p
G4double clp
G4double c3p
G4double csp
G4double hbc
G4double gamm
G4double cpw
G4double cph
G4double epsx
G4double cpc
G4double rmax
G4double rt00
G4double radm
std::vector< G4double > phase_g
std::vector< G4double > rho_l
std::vector< G4double > d_pot
G4double ebini
G4double edepth
G4double epse
G4QMDMeanField * meanfield
Additional Inherited Members
Protected Attributes inherited from G4QMDSystem
std::vector< G4QMDParticipant * > participants
Detailed Description
Definition at line 45 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 45 of file G4QMDGroundStateNucleus.hh
Constructor & Destructor Documentation
G4QMDGroundStateNucleus::G4QMDGroundStateNucleus ()
G4QMDGroundStateNucleus::G4QMDGroundStateNucleus (G4int z, G4int a)
Definition at line 38 of file G4QMDGroundStateNucleus.cc.
View newest version in sPHENIX GitHub at line 38 of file G4QMDGroundStateNucleus.cc
References a, G4Pow::A13(), c0p, c3p, cdp, clp, cpc, cph, cpw, csp, ddif, ddif2, dsam, dsam2, ebini, epsx, G4Exp(), gamm, G4QMDParameters::Get_c0p(), G4QMDParameters::Get_c3p(), G4QMDParameters::Get_cdp(), G4QMDParameters::Get_clp(), G4QMDParameters::Get_cpc(), G4QMDParameters::Get_cph(), G4QMDParameters::Get_cpw(), G4QMDParameters::Get_csp(), G4QMDParameters::Get_epsx(), G4QMDParameters::Get_gamm(), G4QMDParameters::Get_hbc(), G4QMDParameters::GetInstance(), G4Pow::GetInstance(), G4QMDNucleus::GetMassNumber(), hbc, meanfield, G4Neutron::Neutron(), packNucleons(), Dataset::parameters, G4Proton::Proton(), r, r00, r01, rada, radb, radm, rmax, rt00, saa, G4QMDSystem::SetParticipant(), and G4QMDMeanField::SetSystem().
G4QMDGroundStateNucleus::~G4QMDGroundStateNucleus () inline
Definition at line 50 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 50 of file G4QMDGroundStateNucleus.hh
References d_pot, and rho_l.
Member Function Documentation
void G4QMDGroundStateNucleus::killCMMotionAndAngularM () private
Definition at line 726 of file G4QMDGroundStateNucleus.cc.
View newest version in sPHENIX GitHub at line 726 of file G4QMDGroundStateNucleus.cc
References CLHEP::Hep3Vector::cross(), G4QMDNucleus::GetMassNumber(), k, G4QMDSystem::participants, r, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, and CLHEP::Hep3Vector::z().
Referenced by packNucleons().
void G4QMDGroundStateNucleus::packNucleons () private
Definition at line 129 of file G4QMDGroundStateNucleus.cc.
View newest version in sPHENIX GitHub at line 129 of file G4QMDGroundStateNucleus.cc
References kdfinder::abs(), c0p, c3p, G4QMDMeanField::Cal2BodyQuantities(), G4QMDMeanField::CalGraduate(), cdp, clp, csp, d_pot, ebini, epse, G4cout, G4endl, gamm, G4QMDNucleus::GetAtomicNumber(), G4NucleiProperties::GetBindingEnergy(), G4QMDMeanField::GetFFp(), G4QMDMeanField::GetFFr(), G4Pow::GetInstance(), G4QMDNucleus::GetMassNumber(), G4QMDMeanField::GetRHA(), G4QMDMeanField::GetRHE(), G4QMDMeanField::GetTotalPotential(), k, killCMMotionAndAngularM(), maxTrial, meanfield, G4QMDSystem::participants, phase_g, G4Pow::powA(), rho_l, samplingMomentum(), and samplingPosition().
Referenced by G4QMDGroundStateNucleus().
G4bool G4QMDGroundStateNucleus::samplingMomentum (G4int i) private
Definition at line 532 of file G4QMDGroundStateNucleus.cc.
View newest version in sPHENIX GitHub at line 532 of file G4QMDGroundStateNucleus.cc
References G4Pow::A13(), kdfinder::abs(), cpc, cph, cpw, d_pot, DBL_MAX, CLHEP::Hep3Vector::diff2(), ebini, edepth, epsx, G4cout, G4endl, G4Exp(), G4UniformRand, G4Pow::GetInstance(), G4QMDNucleus::GetMassNumber(), G4QMDMeanField::GetRR2(), hbc, maxTrial, meanfield, G4QMDSystem::participants, phase(), phase_g, pi, and rho_l.
Referenced by packNucleons().
G4bool G4QMDGroundStateNucleus::samplingPosition (G4int i) private
Definition at line 431 of file G4QMDGroundStateNucleus.cc.
View newest version in sPHENIX GitHub at line 431 of file G4QMDGroundStateNucleus.cc
References ddif2, dsam2, G4cout, G4endl, G4Exp(), G4UniformRand, maxTrial, G4QMDSystem::participants, r2, radm, rmax, rt00, and saa.
Referenced by packNucleons().
Member Data Documentation
G4double G4QMDGroundStateNucleus::c0p private
Definition at line 74 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and packNucleons().
G4double G4QMDGroundStateNucleus::c3p private
Definition at line 74 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and packNucleons().
G4double G4QMDGroundStateNucleus::cdp private
Definition at line 73 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and packNucleons().
G4double G4QMDGroundStateNucleus::clp private
Definition at line 74 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and packNucleons().
G4double G4QMDGroundStateNucleus::cpc private
Definition at line 81 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 81 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingMomentum().
G4double G4QMDGroundStateNucleus::cph private
Definition at line 79 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingMomentum().
G4double G4QMDGroundStateNucleus::cpw private
Definition at line 78 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingMomentum().
G4double G4QMDGroundStateNucleus::csp private
Definition at line 74 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and packNucleons().
std::vector< G4double > G4QMDGroundStateNucleus::d_pot private
Definition at line 88 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 88 of file G4QMDGroundStateNucleus.hh
Referenced by packNucleons(), samplingMomentum(), and ~G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::ddif private
Definition at line 71 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::ddif2 private
Definition at line 71 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingPosition().
G4double G4QMDGroundStateNucleus::dsam private
Definition at line 71 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::dsam2 private
Definition at line 71 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingPosition().
G4double G4QMDGroundStateNucleus::ebini private
Definition at line 89 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 89 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), packNucleons(), and samplingMomentum().
G4double G4QMDGroundStateNucleus::edepth private
Definition at line 90 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QMDGroundStateNucleus.hh
Referenced by samplingMomentum().
G4double G4QMDGroundStateNucleus::epse private
Definition at line 91 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 91 of file G4QMDGroundStateNucleus.hh
Referenced by packNucleons().
G4double G4QMDGroundStateNucleus::epsx private
Definition at line 80 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingMomentum().
G4double G4QMDGroundStateNucleus::gamm private
Definition at line 77 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and packNucleons().
G4double G4QMDGroundStateNucleus::hbc private
Definition at line 76 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingMomentum().
G4int G4QMDGroundStateNucleus::maxTrial private
Definition at line 64 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QMDGroundStateNucleus.hh
Referenced by packNucleons(), samplingMomentum(), and samplingPosition().
G4QMDMeanField* G4QMDGroundStateNucleus::meanfield private
Definition at line 94 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), packNucleons(), and samplingMomentum().
std::vector< G4double > G4QMDGroundStateNucleus::phase_g private
Definition at line 85 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 85 of file G4QMDGroundStateNucleus.hh
Referenced by packNucleons(), and samplingMomentum().
G4double G4QMDGroundStateNucleus::r00 private
Definition at line 69 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::r01 private
Definition at line 69 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::rada private
Definition at line 69 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::radb private
Definition at line 69 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::radm private
Definition at line 83 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingPosition().
std::vector< G4double > G4QMDGroundStateNucleus::rho_l private
Definition at line 87 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 87 of file G4QMDGroundStateNucleus.hh
Referenced by packNucleons(), samplingMomentum(), and ~G4QMDGroundStateNucleus().
G4double G4QMDGroundStateNucleus::rmax private
Definition at line 83 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingPosition().
G4double G4QMDGroundStateNucleus::rt00 private
Definition at line 83 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingPosition().
G4double G4QMDGroundStateNucleus::saa private
Definition at line 69 of file G4QMDGroundStateNucleus.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QMDGroundStateNucleus.hh
Referenced by G4QMDGroundStateNucleus(), and samplingPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDGroundStateNucleus.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDGroundStateNucleus.cc