ECCE @ EIC Software: G4INCL::Clustering Namespace Reference
G4INCL::Clustering Namespace Reference
Cluster formation.
Functions
Cluster * getCluster (Nucleus *n, Particle *p)
Call the clustering algorithm.
G4bool clusterCanEscape (Nucleus const *const n, Cluster const *const c)
Determine whether the cluster can escape or not.
IClusteringModel * getClusteringModel ()
Get the clustering model.
void setClusteringModel (IClusteringModel *const model)
Set the clustering model.
void deleteClusteringModel ()
Delete the clustering model.
void initialize (Config const *const theConfig)
Initialize the clustering model based on the Config object.
Detailed Description
Cluster formation.
Function Documentation
G4bool G4INCL::Clustering::clusterCanEscape (Nucleus const *const n, Cluster const *const c)
Determine whether the cluster can escape or not.
Definition at line 68 of file G4INCLClustering.cc.
View newest version in sPHENIX GitHub at line 68 of file G4INCLClustering.cc
Referenced by G4INCL::SurfaceAvatar::getChannel().
void G4INCL::Clustering::deleteClusteringModel ()
Delete the clustering model.
Definition at line 78 of file G4INCLClustering.cc.
View newest version in sPHENIX GitHub at line 78 of file G4INCLClustering.cc
Referenced by G4INCL::INCL::~INCL().
Cluster * G4INCL::Clustering::getCluster (Nucleus * n, Particle * p)
Call the clustering algorithm.
Choose a cluster candidate to be produced. At this point we don't yet decide if it can pass through the Coulomb barrier or not.
Definition at line 58 of file G4INCLClustering.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLClustering.cc
References c.
Referenced by G4INCL::SurfaceAvatar::getChannel().
IClusteringModel * G4INCL::Clustering::getClusteringModel ()
Get the clustering model.
Definition at line 72 of file G4INCLClustering.cc.
View newest version in sPHENIX GitHub at line 72 of file G4INCLClustering.cc
void G4INCL::Clustering::initialize (Config const *const theConfig)
Initialize the clustering model based on the Config object.
Definition at line 83 of file G4INCLClustering.cc.
View newest version in sPHENIX GitHub at line 83 of file G4INCLClustering.cc
References G4INCL::Config::getClusterAlgorithm(), G4INCL::IntercomparisonClusterAlgorithm, and setClusteringModel().
Referenced by G4INCL::INCL::INCL(), G4INCL::ParticleTable::initialize(), and Acts::Navigator::status().
void G4INCL::Clustering::setClusteringModel (IClusteringModel *const model)
Set the clustering model.
Definition at line 74 of file G4INCLClustering.cc.
View newest version in sPHENIX GitHub at line 74 of file G4INCLClustering.cc
Referenced by initialize().