ECCE @ EIC Software: G4InuclParamAngDst Class Reference
G4InuclParamAngDst Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclParamAngDst.hh>
Public Member Functions
G4InuclParamAngDst (const G4String &name, const G4double(&abnC)[2][4][4], G4int verbose=0)
virtual ~G4InuclParamAngDst ()
virtual G4double GetCosTheta (G4int ptype, G4double ekin) const
virtual G4double GetCosTheta (const G4double &ekin, const G4double &pcm) const
Public Member Functions inherited from G4VThreeBodyAngDst
G4VThreeBodyAngDst (const G4String &name, G4int verbose=0)
virtual ~G4VThreeBodyAngDst ()
Public Member Functions inherited from G4VTwoBodyAngDst
G4VTwoBodyAngDst (const G4String &name, G4int verbose=0)
virtual ~G4VTwoBodyAngDst ()
virtual void setVerboseLevel (G4int verbose=0)
virtual const G4String & GetName () const
Protected Attributes
const G4double(& coeffAB)[2][4][4]
Detailed Description
Definition at line 41 of file G4InuclParamAngDst.hh.
View newest version in sPHENIX GitHub at line 41 of file G4InuclParamAngDst.hh
Constructor & Destructor Documentation
G4InuclParamAngDst::G4InuclParamAngDst (const G4String & name, const G4double(&) abnC[2][4][4], G4int verbose = 0) inline
Definition at line 44 of file G4InuclParamAngDst.hh.
View newest version in sPHENIX GitHub at line 44 of file G4InuclParamAngDst.hh
virtual G4InuclParamAngDst::~G4InuclParamAngDst () inline virtual
Definition at line 49 of file G4InuclParamAngDst.hh.
View newest version in sPHENIX GitHub at line 49 of file G4InuclParamAngDst.hh
Member Function Documentation
G4double G4InuclParamAngDst::GetCosTheta (G4int ptype, G4double ekin) const virtual
Implements G4VThreeBodyAngDst.
Definition at line 44 of file G4InuclParamAngDst.cc.
View newest version in sPHENIX GitHub at line 44 of file G4InuclParamAngDst.cc
References G4cout, G4endl, G4InuclSpecialFunctions::inuclRndm(), G4InuclParticleNames::neu, G4InuclParticleNames::pro, and G4InuclSpecialFunctions::randomInuclPowers().
virtual G4double G4InuclParamAngDst::GetCosTheta (const G4double & ekin, const G4double & pcm) const inline virtual
Reimplemented from G4VThreeBodyAngDst.
Definition at line 55 of file G4InuclParamAngDst.hh.
View newest version in sPHENIX GitHub at line 55 of file G4InuclParamAngDst.hh
References G4VThreeBodyAngDst::GetCosTheta().
Member Data Documentation
const G4double(& G4InuclParamAngDst::coeffAB)[2][4][4] protected
Definition at line 60 of file G4InuclParamAngDst.hh.
View newest version in sPHENIX GitHub at line 60 of file G4InuclParamAngDst.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclParamAngDst.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InuclParamAngDst.cc