ECCE @ EIC Software: G4VBiasingOperation Class Reference
G4VBiasingOperation Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4VBiasingOperation.hh>
Public Member Functions
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)=0
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)=0
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)=0
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)=0
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
const G4String fName
std::size_t fUniqueID
Detailed Description
Definition at line 76 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VBiasingOperation.hh
Constructor & Destructor Documentation
G4VBiasingOperation::G4VBiasingOperation (G4String name)
Definition at line 29 of file G4VBiasingOperation.cc.
View newest version in sPHENIX GitHub at line 29 of file G4VBiasingOperation.cc
References fUniqueID, G4BiasingOperationManager::GetInstance(), and G4BiasingOperationManager::Register().
G4VBiasingOperation::~G4VBiasingOperation () virtual
Definition at line 36 of file G4VBiasingOperation.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VBiasingOperation.cc
Member Function Documentation
virtual void G4VBiasingOperation::AlongMoveBy (const G4BiasingProcessInterface * , const G4Step * , G4double) inline virtual
Reimplemented in G4BOptnForceFreeFlight.
Definition at line 139 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 139 of file G4VBiasingOperation.hh
Referenced by G4BiasingProcessInterface::AlongStepDoIt().
virtual G4VParticleChange* G4VBiasingOperation::ApplyFinalStateBiasing (const G4BiasingProcessInterface * , const G4Track * , const G4Step * , G4bool &) pure virtual
Implemented in G4BOptnForceCommonTruncatedExp, G4BOptnLeadingParticle, GB04BOptnBremSplitting, G4BOptnForceFreeFlight, G4BOptnChangeCrossSection, GB06BOptnSplitAndKillByImportance, G4BOptnCloning, GB05BOptnSplitAndKillByCrossSection, GB03BOptnSplitOrKillOnBoundary, and BiasingOperation.
Referenced by G4BiasingProcessInterface::PostStepDoIt().
virtual G4double G4VBiasingOperation::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) pure virtual
Implemented in G4BOptnForceCommonTruncatedExp, GB04BOptnBremSplitting, G4BOptnLeadingParticle, GB06BOptnSplitAndKillByImportance, G4BOptnForceFreeFlight, GB05BOptnSplitAndKillByCrossSection, GB03BOptnSplitOrKillOnBoundary, G4BOptnChangeCrossSection, G4BOptnCloning, and BiasingOperation.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength().
virtual G4VParticleChange* G4VBiasingOperation::GenerateBiasingFinalState (const G4Track * , const G4Step *) pure virtual
Implemented in G4BOptnForceCommonTruncatedExp, GB06BOptnSplitAndKillByImportance, GB04BOptnBremSplitting, GB05BOptnSplitAndKillByCrossSection, G4BOptnLeadingParticle, G4BOptnForceFreeFlight, GB03BOptnSplitOrKillOnBoundary, G4BOptnCloning, G4BOptnChangeCrossSection, and BiasingOperation.
Referenced by G4BiasingProcessInterface::PostStepDoIt().
const G4String& G4VBiasingOperation::GetName (void) const inline
Definition at line 198 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 198 of file G4VBiasingOperation.hh
References fName.
std::size_t G4VBiasingOperation::GetUniqueID () const inline
Definition at line 199 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 199 of file G4VBiasingOperation.hh
References fUniqueID.
virtual G4double G4VBiasingOperation::ProposeAlongStepLimit (const G4BiasingProcessInterface *) inline virtual
Reimplemented in G4BOptnForceCommonTruncatedExp.
Definition at line 127 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VBiasingOperation.hh
References DBL_MAX.
Referenced by G4BiasingProcessInterface::AlongStepGetPhysicalInteractionLength().
virtual G4GPILSelection G4VBiasingOperation::ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection) inline virtual
Reimplemented in G4BOptnForceCommonTruncatedExp.
Definition at line 131 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 131 of file G4VBiasingOperation.hh
Referenced by G4BiasingProcessInterface::AlongStepGetPhysicalInteractionLength().
virtual const G4VBiasingInteractionLaw* G4VBiasingOperation::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) pure virtual
Implemented in G4BOptnForceCommonTruncatedExp, G4BOptnForceFreeFlight, G4BOptnLeadingParticle, GB04BOptnBremSplitting, BiasingOperation, G4BOptnChangeCrossSection, G4BOptnCloning, GB06BOptnSplitAndKillByImportance, GB03BOptnSplitOrKillOnBoundary, and GB05BOptnSplitAndKillByCrossSection.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength().
Member Data Documentation
const G4String G4VBiasingOperation::fName private
Definition at line 203 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 203 of file G4VBiasingOperation.hh
Referenced by GetName().
std::size_t G4VBiasingOperation::fUniqueID private
Definition at line 205 of file G4VBiasingOperation.hh.
View newest version in sPHENIX GitHub at line 205 of file G4VBiasingOperation.hh
Referenced by G4VBiasingOperation(), and GetUniqueID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4VBiasingOperation.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/management/src/G4VBiasingOperation.cc