ECCE @ EIC Software: G4FieldTrackUpdator Class Reference
G4FieldTrackUpdator Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4FieldTrackUpdator.hh>
Static Public Member Functions
static G4FieldTrack * CreateFieldTrack (const G4Track *)
static void Update (G4FieldTrack *, const G4Track *)
Private Member Functions
G4FieldTrackUpdator ()
~G4FieldTrackUpdator ()
Detailed Description
Definition at line 42 of file G4FieldTrackUpdator.hh.
View newest version in sPHENIX GitHub at line 42 of file G4FieldTrackUpdator.hh
Constructor & Destructor Documentation
G4FieldTrackUpdator::G4FieldTrackUpdator () inline private
Definition at line 45 of file G4FieldTrackUpdator.hh.
View newest version in sPHENIX GitHub at line 45 of file G4FieldTrackUpdator.hh
G4FieldTrackUpdator::~G4FieldTrackUpdator () inline private
Definition at line 46 of file G4FieldTrackUpdator.hh.
View newest version in sPHENIX GitHub at line 46 of file G4FieldTrackUpdator.hh
Member Function Documentation
G4FieldTrack * G4FieldTrackUpdator::CreateFieldTrack (const G4Track * trk) static
Definition at line 44 of file G4FieldTrackUpdator.cc.
View newest version in sPHENIX GitHub at line 44 of file G4FieldTrackUpdator.cc
References G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4Track::GetMomentumDirection(), G4DynamicParticle::GetPolarization(), and G4Track::GetPosition().
void G4FieldTrackUpdator::Update (G4FieldTrack * ftrk, const G4Track * trk) static
Definition at line 59 of file G4FieldTrackUpdator.cc.
View newest version in sPHENIX GitHub at line 59 of file G4FieldTrackUpdator.cc
References G4cerr, G4cout, G4endl, G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetMagneticMoment(), G4DynamicParticle::GetMass(), G4FieldTrack::GetMomentum(), G4Track::GetMomentum(), G4Track::GetMomentumDirection(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetPDGSpin(), G4DynamicParticle::GetPolarization(), G4Track::GetPosition(), G4Track::GetProperTime(), CLHEP::Hep3Vector::mag2(), G4FieldTrack::SetChargeAndMoments(), G4FieldTrack::SetPDGSpin(), G4FieldTrack::SetProperTimeOfFlight(), G4FieldTrack::SetRestMass(), G4FieldTrack::SetSpin(), and G4FieldTrack::UpdateState().
Referenced by G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::AlongStepGetPhysicalInteractionLength(), and Par02FastSimModelTracker::DoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4FieldTrackUpdator.hh
geant4/tree/geant4-10.6-release/source/track/src/G4FieldTrackUpdator.cc