ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_uncorrelated.cc File Reference
MCGIDI_uncorrelated.cc File Reference
#include <string.h>
#include <cmath>
#include "MCGIDI_fromTOM.h"
Functions
int MCGIDI_uncorrelated_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution, ptwXYPoints *norms, enum MCGIDI_energyType energyType, double gammaEnergy_MeV)
int MCGIDI_uncorrelated_sampleDistribution (statusMessageReporting *smr, MCGIDI_distribution *distribution, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
Function Documentation
int MCGIDI_uncorrelated_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution, ptwXYPoints * norms, enum MCGIDI_energyType energyType, double gammaEnergy_MeV)
Definition at line 18 of file MCGIDI_uncorrelated.cc.
View newest version in sPHENIX GitHub at line 18 of file MCGIDI_uncorrelated.cc
References check_license::err(), MCGIDI_angular_parseFromTOM(), MCGIDI_distributionType_uncorrelated_e, MCGIDI_energy_parseFromTOM(), MCGIDI_energyType_discreteGamma, MCGIDI_energyType_primaryGamma, MCGIDI_distribution_s::type, and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
int MCGIDI_uncorrelated_sampleDistribution (statusMessageReporting * smr, MCGIDI_distribution * distribution, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 43 of file MCGIDI_uncorrelated.cc.
View newest version in sPHENIX GitHub at line 43 of file MCGIDI_uncorrelated.cc
References MCGIDI_distribution_s::angular, MCGIDI_distribution_s::energy, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_angular_sampleMu(), and MCGIDI_energy_sampleEnergy().
Referenced by MCGIDI_outputChannel_sampleProductsAtE().