ECCE @ EIC Software: G4INCL::PauliStrictStandard Class Reference
G4INCL::PauliStrictStandard Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLPauliStrictStandard.hh>
Public Member Functions
PauliStrictStandard ()
~PauliStrictStandard ()
PauliStrictStandard (const PauliStrictStandard &rhs)
Dummy copy constructor to silence Coverity warning.
PauliStrictStandard & operator= (const PauliStrictStandard &rhs)
Dummy assignment operator to silence Coverity warning.
G4bool isBlocked (ParticleList const &, Nucleus const *const)
Public Member Functions inherited from G4INCL::IPauli
IPauli ()
virtual ~IPauli ()
Private Attributes
IPauli * theStrictBlocker
IPauli * theStandardBlocker
Detailed Description
Definition at line 46 of file G4INCLPauliStrictStandard.hh.
View newest version in sPHENIX GitHub at line 46 of file G4INCLPauliStrictStandard.hh
Constructor & Destructor Documentation
G4INCL::PauliStrictStandard::PauliStrictStandard ()
Definition at line 45 of file G4INCLPauliStrictStandard.cc.
View newest version in sPHENIX GitHub at line 45 of file G4INCLPauliStrictStandard.cc
References theStandardBlocker, and theStrictBlocker.
G4INCL::PauliStrictStandard::~PauliStrictStandard ()
Definition at line 50 of file G4INCLPauliStrictStandard.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLPauliStrictStandard.cc
References theStandardBlocker, and theStrictBlocker.
G4INCL::PauliStrictStandard::PauliStrictStandard (const PauliStrictStandard & rhs)
Dummy copy constructor to silence Coverity warning.
Member Function Documentation
G4bool G4INCL::PauliStrictStandard::isBlocked (ParticleList const & particleList, Nucleus const * const nucleus) virtual
Implements G4INCL::IPauli.
Definition at line 55 of file G4INCLPauliStrictStandard.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLPauliStrictStandard.cc
References G4INCL::Book::getAcceptedCollisions(), G4INCL::Store::getBook(), G4INCL::Nucleus::getStore(), G4INCL::IPauli::isBlocked(), theStandardBlocker, and theStrictBlocker.
PauliStrictStandard& G4INCL::PauliStrictStandard::operator= (const PauliStrictStandard & rhs)
Dummy assignment operator to silence Coverity warning.
Member Data Documentation
IPauli * G4INCL::PauliStrictStandard::theStandardBlocker private
Definition at line 60 of file G4INCLPauliStrictStandard.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLPauliStrictStandard.hh
Referenced by isBlocked(), PauliStrictStandard(), and ~PauliStrictStandard().
IPauli* G4INCL::PauliStrictStandard::theStrictBlocker private
Definition at line 60 of file G4INCLPauliStrictStandard.hh.
View newest version in sPHENIX GitHub at line 60 of file G4INCLPauliStrictStandard.hh
Referenced by isBlocked(), PauliStrictStandard(), and ~PauliStrictStandard().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLPauliStrictStandard.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLPauliStrictStandard.cc