ECCE @ EIC Software: G4BGGNucleonElasticXS Class Reference
G4BGGNucleonElasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGNucleonElasticXS.hh>
Public Member Functions
G4BGGNucleonElasticXS (const G4ParticleDefinition *)
~G4BGGNucleonElasticXS () final
G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat) final
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm, const G4Material *mat) final
G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat) final
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void CrossSectionDescription (std::ostream &) const final
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4double CoulombFactor (G4double kinEnergy, G4int Z)
G4BGGNucleonElasticXS & operator= (const G4BGGNucleonElasticXS &right)
G4BGGNucleonElasticXS (const G4BGGNucleonElasticXS &)
Private Attributes
G4double fGlauberEnergy
G4double fLowEnergy
const G4ParticleDefinition * theProton
G4ComponentGGHadronNucleusXsc * fGlauber
G4NucleonNuclearCrossSection * fNucleon
G4HadronNucleonXsc * fHadron
G4bool isProton
G4bool isMaster
Static Private Attributes
static G4double theGlauberFacP [93] = {0.0}
static G4double theCoulombFacP [93] = {0.0}
static G4double theGlauberFacN [93] = {0.0}
static G4double theCoulombFacN [93] = {0.0}
static G4int theA [93] = {0}
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 63 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BGGNucleonElasticXS.hh
Constructor & Destructor Documentation
G4BGGNucleonElasticXS::G4BGGNucleonElasticXS (const G4ParticleDefinition * p) explicit
Definition at line 63 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 63 of file G4BGGNucleonElasticXS.cc
References fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fNucleon, GeV, isMaster, isProton, MeV, G4Proton::Proton(), G4VCrossSectionDataSet::SetForAllAtomsAndEnergies(), theProton, and G4VCrossSectionDataSet::verboseLevel.
G4BGGNucleonElasticXS::~G4BGGNucleonElasticXS () final
Definition at line 81 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 81 of file G4BGGNucleonElasticXS.cc
References fHadron.
G4BGGNucleonElasticXS::G4BGGNucleonElasticXS (const G4BGGNucleonElasticXS &) private
Member Function Documentation
void G4BGGNucleonElasticXS::BuildPhysicsTable (const G4ParticleDefinition & p) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 167 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 167 of file G4BGGNucleonElasticXS.cc
References A(), G4NucleonNuclearCrossSection::BuildPhysicsTable(), CoulombFactor(), FatalException, fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fNucleon, G4cout, G4endl, G4Exception(), G4lrint(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4NistManager::GetAtomicMassAmu(), G4NucleonNuclearCrossSection::GetElasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), G4ParticleDefinition::GetParticleName(), G4NistManager::Instance(), isMaster, isProton, mom, G4Neutron::Neutron(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetKineticEnergy(), theA, theCoulombFacN, theCoulombFacP, theGlauberFacN, theGlauberFacP, theProton, and G4VCrossSectionDataSet::verboseLevel.
G4double G4BGGNucleonElasticXS::CoulombFactor (G4double kinEnergy, G4int Z) private
Definition at line 262 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 262 of file G4BGGNucleonElasticXS.cc
References G4NuclearRadii::CoulombFactor(), isProton, theA, and theProton.
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
void G4BGGNucleonElasticXS::CrossSectionDescription (std::ostream & outFile) const final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 273 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 273 of file G4BGGNucleonElasticXS.cc
G4double G4BGGNucleonElasticXS::GetElementCrossSection (const G4DynamicParticle * dp, G4int Z, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 108 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 108 of file G4BGGNucleonElasticXS.cc
References barn, CoulombFactor(), Acts::VectorHelpers::cross(), fGlauber, fGlauberEnergy, fLowEnergy, fNucleon, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4NucleonNuclearCrossSection::GetElasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), GetIsoCrossSection(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), CLHEP::GeV, isProton, min, theA, theCoulombFacN, theCoulombFacP, theGlauberFacN, theGlauberFacP, G4VCrossSectionDataSet::verboseLevel, and Z.
G4double G4BGGNucleonElasticXS::GetIsoCrossSection (const G4DynamicParticle * dp, G4int Z, G4int A, const G4Isotope * iso = nullptr, const G4Element * elm = nullptr, const G4Material * mat = nullptr) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 143 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 143 of file G4BGGNucleonElasticXS.cc
References barn, Acts::VectorHelpers::cross(), fHadron, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4HadronNucleonXsc::GetElasticHadronNucleonXsc(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), CLHEP::GeV, G4HadronNucleonXsc::HadronNucleonXscNS(), theProton, and G4VCrossSectionDataSet::verboseLevel.
Referenced by GetElementCrossSection().
G4bool G4BGGNucleonElasticXS::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 89 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 89 of file G4BGGNucleonElasticXS.cc
G4bool G4BGGNucleonElasticXS::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * elm, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 97 of file G4BGGNucleonElasticXS.cc.
View newest version in sPHENIX GitHub at line 97 of file G4BGGNucleonElasticXS.cc
G4BGGNucleonElasticXS& G4BGGNucleonElasticXS::operator= (const G4BGGNucleonElasticXS & right) private
Member Data Documentation
G4ComponentGGHadronNucleusXsc* G4BGGNucleonElasticXS::fGlauber private
Definition at line 107 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 107 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonElasticXS(), and GetElementCrossSection().
G4double G4BGGNucleonElasticXS::fGlauberEnergy private
Definition at line 97 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 97 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonElasticXS(), and GetElementCrossSection().
G4HadronNucleonXsc* G4BGGNucleonElasticXS::fHadron private
Definition at line 109 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 109 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonElasticXS(), GetIsoCrossSection(), and ~G4BGGNucleonElasticXS().
G4double G4BGGNucleonElasticXS::fLowEnergy private
Definition at line 98 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 98 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonElasticXS(), and GetElementCrossSection().
G4NucleonNuclearCrossSection* G4BGGNucleonElasticXS::fNucleon private
Definition at line 108 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGNucleonElasticXS(), and GetElementCrossSection().
G4bool G4BGGNucleonElasticXS::isMaster private
Definition at line 111 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 111 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), and G4BGGNucleonElasticXS().
G4bool G4BGGNucleonElasticXS::isProton private
Definition at line 110 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 110 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactor(), G4BGGNucleonElasticXS(), and GetElementCrossSection().
G4int G4BGGNucleonElasticXS::theA = {0} static private
Definition at line 104 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 104 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactor(), and GetElementCrossSection().
G4double G4BGGNucleonElasticXS::theCoulombFacN = {0.0} static private
Definition at line 103 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 103 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGNucleonElasticXS::theCoulombFacP = {0.0} static private
Definition at line 101 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGNucleonElasticXS::theGlauberFacN = {0.0} static private
Definition at line 102 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 102 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGNucleonElasticXS::theGlauberFacP = {0.0} static private
Definition at line 100 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 100 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
const G4ParticleDefinition* G4BGGNucleonElasticXS::theProton private
Definition at line 106 of file G4BGGNucleonElasticXS.hh.
View newest version in sPHENIX GitHub at line 106 of file G4BGGNucleonElasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactor(), G4BGGNucleonElasticXS(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGNucleonElasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4BGGNucleonElasticXS.cc