ECCE @ EIC Software: G4NucleusLimits Class Reference
G4NucleusLimits Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4NucleusLimits.hh>
Public Member Functions
G4NucleusLimits ()
G4NucleusLimits (G4int aMin1, G4int aMax1, G4int zMin1, G4int zMax1)
~G4NucleusLimits ()
G4int GetAMin () const
G4int GetAMax () const
G4int GetZMin () const
G4int GetZMax () const
Private Attributes
G4int aMin
G4int aMax
G4int zMin
G4int zMax
Friends
std::ostream & operator<< (std::ostream &s, const G4NucleusLimits &q)
Detailed Description
Definition at line 58 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 58 of file G4NucleusLimits.hh
Constructor & Destructor Documentation
G4NucleusLimits::G4NucleusLimits ()
Definition at line 56 of file G4NucleusLimits.cc.
View newest version in sPHENIX GitHub at line 56 of file G4NucleusLimits.cc
G4NucleusLimits::G4NucleusLimits (G4int aMin1, G4int aMax1, G4int zMin1, G4int zMax1)
Definition at line 65 of file G4NucleusLimits.cc.
View newest version in sPHENIX GitHub at line 65 of file G4NucleusLimits.cc
References t.
G4NucleusLimits::~G4NucleusLimits ()
Definition at line 114 of file G4NucleusLimits.cc.
View newest version in sPHENIX GitHub at line 114 of file G4NucleusLimits.cc
Member Function Documentation
G4int G4NucleusLimits::GetAMax () const inline
Definition at line 94 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 94 of file G4NucleusLimits.hh
References aMax.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
G4int G4NucleusLimits::GetAMin () const inline
Definition at line 91 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 91 of file G4NucleusLimits.hh
References aMin.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
G4int G4NucleusLimits::GetZMax () const inline
Definition at line 100 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 100 of file G4NucleusLimits.hh
References zMax.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
G4int G4NucleusLimits::GetZMin () const inline
Definition at line 97 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 97 of file G4NucleusLimits.hh
References zMin.
Referenced by G4UIcmdWithNucleusLimits::ConvertToString(), G4RadioactiveDecayBase::IsApplicable(), G4RadioactiveDecay::IsApplicable(), operator<<(), and G4UIcmdWithNucleusLimits::SetDefaultValue().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & s, const G4NucleusLimits & q) friend
Definition at line 118 of file G4NucleusLimits.cc.
View newest version in sPHENIX GitHub at line 118 of file G4NucleusLimits.cc
Member Data Documentation
G4int G4NucleusLimits::aMax private
Definition at line 81 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 81 of file G4NucleusLimits.hh
Referenced by GetAMax().
G4int G4NucleusLimits::aMin private
Definition at line 80 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 80 of file G4NucleusLimits.hh
Referenced by GetAMin().
G4int G4NucleusLimits::zMax private
Definition at line 83 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 83 of file G4NucleusLimits.hh
Referenced by GetZMax().
G4int G4NucleusLimits::zMin private
Definition at line 82 of file G4NucleusLimits.hh.
View newest version in sPHENIX GitHub at line 82 of file G4NucleusLimits.hh
Referenced by GetZMin().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4NucleusLimits.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4NucleusLimits.cc