ECCE @ EIC Software: MCTruthTrackingAction Class Reference
MCTruthTrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/MCTruthTrackingAction.hh>
Public Member Functions
MCTruthTrackingAction ()
virtual ~MCTruthTrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
Public Member Functions inherited from G4UserTrackingAction
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
Private Member Functions
G4bool TrackToBeStored (const G4Track *)
Private Attributes
G4LorentzVector fmom
Additional Inherited Members
Protected Attributes inherited from G4UserTrackingAction
G4TrackingManager * fpTrackingManager
Detailed Description
Definition at line 46 of file MCTruthTrackingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file MCTruthTrackingAction.hh
Constructor & Destructor Documentation
MCTruthTrackingAction::MCTruthTrackingAction ()
Definition at line 52 of file MCTruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 52 of file MCTruthTrackingAction.cc
MCTruthTrackingAction::~MCTruthTrackingAction () virtual
Definition at line 58 of file MCTruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file MCTruthTrackingAction.cc
Member Function Documentation
void MCTruthTrackingAction::PostUserTrackingAction (const G4Track * track) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 76 of file MCTruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 76 of file MCTruthTrackingAction.cc
References fmom, G4UserTrackingAction::fpTrackingManager, G4Track::GetDefinition(), MCTruthTrackInformation::GetDirectParent(), G4Track::GetGlobalTime(), MCTruthManager::GetInstance(), G4Track::GetLocalTime(), G4Track::GetParentID(), G4ParticleDefinition::GetPDGEncoding(), G4Track::GetPosition(), G4Track::GetTrackID(), G4Track::GetUserInformation(), G4Track::GetVertexPosition(), G4TrackingManager::GimmeSecondaries(), MCTruthTrackInformation::SetDirectParent(), G4Track::SetParentID(), G4Track::SetUserInformation(), and TrackToBeStored().
void MCTruthTrackingAction::PreUserTrackingAction (const G4Track * track) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 63 of file MCTruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 63 of file MCTruthTrackingAction.cc
References fmom, G4UserTrackingAction::fpTrackingManager, G4Track::GetMomentum(), G4Track::GetTotalEnergy(), G4Track::GetUserInformation(), and G4TrackingManager::SetUserTrackInformation().
G4bool MCTruthTrackingAction::TrackToBeStored (const G4Track * track) private
Definition at line 122 of file MCTruthTrackingAction.cc.
View newest version in sPHENIX GitHub at line 122 of file MCTruthTrackingAction.cc
References CLHEP::HepLorentzVector::e(), fmom, MCTruthManager::GetConfig(), G4Track::GetDefinition(), MCTruthManager::GetInstance(), MCTruthConfig::GetMinE(), MCTruthConfig::GetParticleTypes(), and G4ParticleDefinition::GetPDGEncoding().
Referenced by PostUserTrackingAction().
Member Data Documentation
G4LorentzVector MCTruthTrackingAction::fmom private
Definition at line 59 of file MCTruthTrackingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file MCTruthTrackingAction.hh
Referenced by PostUserTrackingAction(), PreUserTrackingAction(), and TrackToBeStored().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/MCTruthTrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/src/MCTruthTrackingAction.cc