ECCE @ EIC Software: G4HadronicProcessStore Class Reference
G4HadronicProcessStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadronicProcessStore.hh>
Public Member Functions
~G4HadronicProcessStore ()
void Clean ()
G4double GetCrossSectionPerAtom (const G4ParticleDefinition *particle, G4double kineticEnergy, const G4VProcess *process, const G4Element *element, const G4Material *material=nullptr)
G4double GetCrossSectionPerVolume (const G4ParticleDefinition *particle, G4double kineticEnergy, const G4VProcess *process, const G4Material *material)
G4double GetInelasticCrossSectionPerVolume (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Material *material)
G4double GetInelasticCrossSectionPerAtom (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Element *anElement, const G4Material *mat=nullptr)
G4double GetInelasticCrossSectionPerIsotope (const G4ParticleDefinition *aParticle, G4double kineticEnergy, G4int Z, G4int A)
G4double GetElasticCrossSectionPerVolume (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Material *material)
G4double GetElasticCrossSectionPerAtom (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Element *anElement, const G4Material *mat=0)
G4double GetElasticCrossSectionPerIsotope (const G4ParticleDefinition *aParticle, G4double kineticEnergy, G4int Z, G4int A)
G4double GetCaptureCrossSectionPerVolume (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Material *material)
G4double GetCaptureCrossSectionPerAtom (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Element *anElement, const G4Material *mat=nullptr)
G4double GetCaptureCrossSectionPerIsotope (const G4ParticleDefinition *aParticle, G4double kineticEnergy, G4int Z, G4int A)
G4double GetFissionCrossSectionPerVolume (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Material *material)
G4double GetFissionCrossSectionPerAtom (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Element *anElement, const G4Material *mat=nullptr)
G4double GetFissionCrossSectionPerIsotope (const G4ParticleDefinition *aParticle, G4double kineticEnergy, G4int Z, G4int A)
G4double GetChargeExchangeCrossSectionPerVolume (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Material *material)
G4double GetChargeExchangeCrossSectionPerAtom (const G4ParticleDefinition *aParticle, G4double kineticEnergy, const G4Element *anElement, const G4Material *mat=nullptr)
G4double GetChargeExchangeCrossSectionPerIsotope (const G4ParticleDefinition *aParticle, G4double kineticEnergy, G4int Z, G4int A)
void Register (G4HadronicProcess *)
void RegisterParticle (G4HadronicProcess *, const G4ParticleDefinition *)
void RegisterInteraction (G4HadronicProcess *, G4HadronicInteraction *)
void DeRegister (G4HadronicProcess *)
void RegisterExtraProcess (G4VProcess *)
void RegisterParticleForExtraProcess (G4VProcess *, const G4ParticleDefinition *)
void DeRegisterExtraProcess (G4VProcess *)
void SetBuildXSTable (G4bool val)
G4bool GetBuildXSTable () const
void PrintInfo (const G4ParticleDefinition *)
void Dump (G4int level)
void DumpHtml ()
void PrintHtml (const G4ParticleDefinition *, std::ofstream &)
void PrintModelHtml (const G4HadronicInteraction *model) const
void SetVerbose (G4int val)
G4int GetVerbose ()
G4HadronicProcess * FindProcess (const G4ParticleDefinition *, G4HadronicProcessType subType)
void SetEpReportLevel (G4int level)
void SetProcessAbsLevel (G4double absoluteLevel)
void SetProcessRelLevel (G4double relativeLevel)
Static Public Member Functions
static G4HadronicProcessStore * Instance ()
Private Types
typedef const
G4ParticleDefinition * PD
typedef G4HadronicProcess * HP
typedef G4HadronicInteraction * HI
Private Member Functions
G4HadronicProcessStore ()
void Print (G4int idxProcess, G4int idxParticle)
G4String HtmlFileName (const G4String &) const
Private Attributes
std::vector< G4HadronicProcess * > process
std::vector
< G4HadronicInteraction * > model
std::vector< G4String > modelName
std::vector< PD > particle
std::vector< G4int > wasPrinted
std::multimap< PD, HP > p_map
std::multimap< HP, HI > m_map
std::vector< G4VProcess * > extraProcess
std::multimap< PD, G4VProcess * > ep_map
G4int n_proc
G4int n_model
G4int n_part
G4int n_extra
G4int verbose
G4bool buildTableStart
G4bool buildXSTable
HP currentProcess
PD currentParticle
PD theGenericIon
G4DynamicParticle localDP
G4HadronicEPTestMessenger * theEPTestMessenger
Static Private Attributes
static G4ThreadLocal
G4HadronicProcessStore * instance = nullptr
Friends
class G4ThreadLocalSingleton< G4HadronicProcessStore >
Detailed Description
Definition at line 67 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HadronicProcessStore.hh
Member Typedef Documentation
typedef G4HadronicInteraction* G4HadronicProcessStore::HI private
Definition at line 229 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 229 of file G4HadronicProcessStore.hh
typedef G4HadronicProcess* G4HadronicProcessStore::HP private
Definition at line 228 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 228 of file G4HadronicProcessStore.hh
typedef const G4ParticleDefinition* G4HadronicProcessStore::PD private
Definition at line 227 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 227 of file G4HadronicProcessStore.hh
Constructor & Destructor Documentation
G4HadronicProcessStore::~G4HadronicProcessStore ()
Definition at line 78 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 78 of file G4HadronicProcessStore.cc
References Clean(), and theEPTestMessenger.
G4HadronicProcessStore::G4HadronicProcessStore () private
Definition at line 114 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 114 of file G4HadronicProcessStore.cc
References buildTableStart, buildXSTable, currentParticle, currentProcess, G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), n_extra, n_model, n_part, n_proc, theEPTestMessenger, theGenericIon, and verbose.
Member Function Documentation
void G4HadronicProcessStore::Clean ()
Definition at line 86 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 86 of file G4HadronicProcessStore.cc
References extraProcess, n_extra, n_proc, and process.
Referenced by ~G4HadronicProcessStore().
void G4HadronicProcessStore::DeRegister (G4HadronicProcess * proc)
Definition at line 478 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 478 of file G4HadronicProcessStore.cc
References DeRegisterExtraProcess(), n_proc, and process.
Referenced by G4HadronicProcess::~G4HadronicProcess().
void G4HadronicProcessStore::DeRegisterExtraProcess (G4VProcess * proc)
Definition at line 543 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 543 of file G4HadronicProcessStore.cc
References extraProcess, G4cout, G4endl, G4VProcess::GetProcessName(), n_extra, and verbose.
Referenced by DeRegister(), G4AntiNeutronAnnihilationAtRest::~G4AntiNeutronAnnihilationAtRest(), and G4MuonMinusAtomicCapture::~G4MuonMinusAtomicCapture().
void G4HadronicProcessStore::Dump (G4int level)
Definition at line 764 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 764 of file G4HadronicProcessStore.cc
References ep_map, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), it, n_part, n_proc, p_map, part, particle, pname(), Print(), process, and wasPrinted.
Referenced by PrintInfo().
void G4HadronicProcessStore::DumpHtml ()
Definition at line 587 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 587 of file G4HadronicProcessStore.cc
References G4Alpha::Alpha(), G4Electron::Electron(), G4Gamma::Gamma(), G4GenericIon::GenericIon(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4Lambda::Lambda(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4Positron::Positron(), PrintHtml(), and G4Proton::Proton().
Referenced by PrintInfo().
G4HadronicProcess * G4HadronicProcessStore::FindProcess (const G4ParticleDefinition * part, G4HadronicProcessType subType)
Definition at line 904 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 904 of file G4HadronicProcessStore.cc
References currentParticle, currentProcess, G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetParticleType(), G4VProcess::GetProcessSubType(), it, localDP, p_map, part, G4DynamicParticle::SetDefinition(), and theGenericIon.
Referenced by GetCaptureCrossSectionPerAtom(), GetChargeExchangeCrossSectionPerAtom(), GetElasticCrossSectionPerAtom(), GetFissionCrossSectionPerAtom(), and GetInelasticCrossSectionPerAtom().
G4bool G4HadronicProcessStore::GetBuildXSTable () const
Definition at line 566 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 566 of file G4HadronicProcessStore.cc
References buildXSTable.
G4double G4HadronicProcessStore::GetCaptureCrossSectionPerAtom (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Element * anElement, const G4Material * mat = nullptr)
Definition at line 291 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 291 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fCapture, FindProcess(), G4HadronicProcess::GetElementCrossSection(), localDP, and G4DynamicParticle::SetKineticEnergy().
Referenced by HistoManager::EndOfRun(), GetCaptureCrossSectionPerVolume(), and GetCrossSectionPerAtom().
G4double G4HadronicProcessStore::GetCaptureCrossSectionPerIsotope (const G4ParticleDefinition * aParticle, G4double kineticEnergy, G4int Z, G4int A)
Definition at line 307 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 307 of file G4HadronicProcessStore.cc
G4double G4HadronicProcessStore::GetCaptureCrossSectionPerVolume (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Material * material)
Definition at line 271 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 271 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), GetCaptureCrossSectionPerAtom(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), and G4Material::GetVecNbOfAtomsPerVolume().
Referenced by GetCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetChargeExchangeCrossSectionPerAtom (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Element * anElement, const G4Material * mat = nullptr)
Definition at line 383 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 383 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fChargeExchange, FindProcess(), G4HadronicProcess::GetElementCrossSection(), localDP, and G4DynamicParticle::SetKineticEnergy().
Referenced by HistoManager::EndOfRun(), GetChargeExchangeCrossSectionPerVolume(), and GetCrossSectionPerAtom().
G4double G4HadronicProcessStore::GetChargeExchangeCrossSectionPerIsotope (const G4ParticleDefinition * aParticle, G4double kineticEnergy, G4int Z, G4int A)
Definition at line 399 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 399 of file G4HadronicProcessStore.cc
G4double G4HadronicProcessStore::GetChargeExchangeCrossSectionPerVolume (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Material * material)
Definition at line 363 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 363 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), GetChargeExchangeCrossSectionPerAtom(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), and G4Material::GetVecNbOfAtomsPerVolume().
Referenced by GetCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetCrossSectionPerAtom (const G4ParticleDefinition * particle, G4double kineticEnergy, const G4VProcess * process, const G4Element * element, const G4Material * material = nullptr)
Definition at line 132 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 132 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fCapture, fChargeExchange, fFission, fHadronElastic, fHadronInelastic, GetCaptureCrossSectionPerAtom(), GetChargeExchangeCrossSectionPerAtom(), GetElasticCrossSectionPerAtom(), GetFissionCrossSectionPerAtom(), GetInelasticCrossSectionPerAtom(), and G4VProcess::GetProcessSubType().
Referenced by Run::EndOfRun().
G4double G4HadronicProcessStore::GetCrossSectionPerVolume (const G4ParticleDefinition * particle, G4double kineticEnergy, const G4VProcess * process, const G4Material * material)
Definition at line 156 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 156 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fCapture, fChargeExchange, fFission, fHadronElastic, fHadronInelastic, GetCaptureCrossSectionPerVolume(), GetChargeExchangeCrossSectionPerVolume(), GetElasticCrossSectionPerVolume(), GetFissionCrossSectionPerVolume(), GetInelasticCrossSectionPerVolume(), and G4VProcess::GetProcessSubType().
Referenced by Run::EndOfRun().
G4double G4HadronicProcessStore::GetElasticCrossSectionPerAtom (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Element * anElement, const G4Material * mat = 0)
Definition at line 199 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 199 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fHadronElastic, FindProcess(), G4HadronicProcess::GetElementCrossSection(), localDP, and G4DynamicParticle::SetKineticEnergy().
Referenced by HistoManager::EndOfRun(), GetCrossSectionPerAtom(), and GetElasticCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetElasticCrossSectionPerIsotope (const G4ParticleDefinition * aParticle, G4double kineticEnergy, G4int Z, G4int A)
Definition at line 215 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 215 of file G4HadronicProcessStore.cc
G4double G4HadronicProcessStore::GetElasticCrossSectionPerVolume (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Material * material)
Definition at line 179 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 179 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), GetElasticCrossSectionPerAtom(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), and G4Material::GetVecNbOfAtomsPerVolume().
Referenced by HistoManager::EndOfRun(), and GetCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetFissionCrossSectionPerAtom (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Element * anElement, const G4Material * mat = nullptr)
Definition at line 337 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 337 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fFission, FindProcess(), G4HadronicProcess::GetElementCrossSection(), localDP, and G4DynamicParticle::SetKineticEnergy().
Referenced by HistoManager::EndOfRun(), GetCrossSectionPerAtom(), and GetFissionCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetFissionCrossSectionPerIsotope (const G4ParticleDefinition * aParticle, G4double kineticEnergy, G4int Z, G4int A)
Definition at line 353 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 353 of file G4HadronicProcessStore.cc
G4double G4HadronicProcessStore::GetFissionCrossSectionPerVolume (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Material * material)
Definition at line 317 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 317 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), G4Material::GetElementVector(), GetFissionCrossSectionPerAtom(), G4Material::GetNumberOfElements(), and G4Material::GetVecNbOfAtomsPerVolume().
Referenced by GetCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetInelasticCrossSectionPerAtom (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Element * anElement, const G4Material * mat = nullptr)
Definition at line 245 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 245 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), fHadronInelastic, FindProcess(), G4HadronicProcess::GetElementCrossSection(), localDP, and G4DynamicParticle::SetKineticEnergy().
Referenced by HistoManager::EndOfRun(), GetCrossSectionPerAtom(), and GetInelasticCrossSectionPerVolume().
G4double G4HadronicProcessStore::GetInelasticCrossSectionPerIsotope (const G4ParticleDefinition * aParticle, G4double kineticEnergy, G4int Z, G4int A)
Definition at line 261 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 261 of file G4HadronicProcessStore.cc
G4double G4HadronicProcessStore::GetInelasticCrossSectionPerVolume (const G4ParticleDefinition * aParticle, G4double kineticEnergy, const G4Material * material)
Definition at line 225 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 225 of file G4HadronicProcessStore.cc
References Acts::VectorHelpers::cross(), G4Material::GetElementVector(), GetInelasticCrossSectionPerAtom(), G4Material::GetNumberOfElements(), and G4Material::GetVecNbOfAtomsPerVolume().
Referenced by HistoManager::EndOfRun(), and GetCrossSectionPerVolume().
G4int G4HadronicProcessStore::GetVerbose ()
Definition at line 897 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 897 of file G4HadronicProcessStore.cc
References verbose.
G4String G4HadronicProcessStore::HtmlFileName (const G4String & in) const private
Definition at line 744 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 744 of file G4HadronicProcessStore.cc
References it, and Acts::Test::transform.
Referenced by PrintHtml(), and PrintModelHtml().
G4HadronicProcessStore * G4HadronicProcessStore::Instance (void) static
Definition at line 67 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 67 of file G4HadronicProcessStore.cc
References G4ThreadLocalSingleton< T >::Instance(), and instance.
Referenced by G4AntiNeutronAnnihilationAtRest::BuildPhysicsTable(), G4HadronStoppingProcess::BuildPhysicsTable(), G4MuonMinusAtomicCapture::BuildPhysicsTable(), G4HadronicProcess::BuildPhysicsTable(), G4RadioactiveDecayBase::BuildPhysicsTable(), G4RadioactiveDecay::BuildPhysicsTable(), G4NeutronTrackingCut::ConstructProcess(), Run::EndOfRun(), HistoManager::EndOfRun(), G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest(), G4HadronStoppingProcess::G4HadronStoppingProcess(), G4MuonMinusAtomicCapture::G4MuonMinusAtomicCapture(), G4RadioactiveDecay::G4RadioactiveDecay(), G4RadioactiveDecayBase::G4RadioactiveDecayBase(), G4HadronicProcess::InitialiseLocal(), PHG4Reco::InitRun(), main(), G4AntiNeutronAnnihilationAtRest::PreparePhysicsTable(), G4HadronStoppingProcess::PreparePhysicsTable(), G4MuonMinusAtomicCapture::PreparePhysicsTable(), G4HadronicProcess::RegisterMe(), G4AntiNeutronAnnihilationAtRest::~G4AntiNeutronAnnihilationAtRest(), and G4MuonMinusAtomicCapture::~G4MuonMinusAtomicCapture().
void G4HadronicProcessStore::Print (G4int idxProcess, G4int idxParticle) private
Definition at line 839 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 839 of file G4HadronicProcessStore.cc
References kdfinder::abs(), G4GenericIon::Definition(), G4CrossSectionDataStore::DumpPhysicsTable(), G4BestUnit, G4cout, G4endl, G4ParticleDefinition::GetBaryonNumber(), G4HadronicProcess::GetCrossSectionDataStore(), G4HadronicInteraction::GetMaxEnergy(), G4HadronicInteraction::GetMinEnergy(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), m_map, modelName, n_model, part, particle, process, and wasPrinted.
Referenced by Dump().
void G4HadronicProcessStore::PrintHtml (const G4ParticleDefinition * theParticle, std::ofstream & outFile)
Definition at line 635 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 635 of file G4HadronicProcessStore.cc
References G4CrossSectionDataStore::DumpHtml(), ep_map, G4HadronicProcess::GetCrossSectionDataStore(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), GeV, HtmlFileName(), it, m_map, p_map, PrintModelHtml(), G4HadronicProcess::ProcessDescription(), and G4VProcess::ProcessDescription().
Referenced by DumpHtml().
void G4HadronicProcessStore::PrintInfo (const G4ParticleDefinition * part)
Definition at line 573 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 573 of file G4HadronicProcessStore.cc
References buildTableStart, Dump(), DumpHtml(), G4HadronicInteractionRegistry::InitialiseModels(), G4HadronicInteractionRegistry::Instance(), n_part, particle, and verbose.
Referenced by G4AntiNeutronAnnihilationAtRest::BuildPhysicsTable(), G4MuonMinusAtomicCapture::BuildPhysicsTable(), G4HadronStoppingProcess::BuildPhysicsTable(), and G4HadronicProcess::BuildPhysicsTable().
void G4HadronicProcessStore::PrintModelHtml (const G4HadronicInteraction * model) const
Definition at line 721 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 721 of file G4HadronicProcessStore.cc
References G4HadronicInteraction::GetModelName(), HtmlFileName(), and G4HadronicInteraction::ModelDescription().
Referenced by PrintHtml().
void G4HadronicProcessStore::Register (G4HadronicProcess * proc)
Definition at line 409 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 409 of file G4HadronicProcessStore.cc
References G4cout, G4endl, G4VProcess::GetProcessName(), n_proc, process, and verbose.
Referenced by G4HadronicProcess::InitialiseLocal().
void G4HadronicProcessStore::RegisterExtraProcess (G4VProcess * proc)
Definition at line 491 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 491 of file G4HadronicProcessStore.cc
References extraProcess, G4cout, G4endl, G4VProcess::GetProcessName(), n_extra, n_proc, process, and verbose.
Referenced by G4NeutronTrackingCut::ConstructProcess(), G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest(), G4HadronStoppingProcess::G4HadronStoppingProcess(), G4MuonMinusAtomicCapture::G4MuonMinusAtomicCapture(), G4RadioactiveDecay::G4RadioactiveDecay(), and G4RadioactiveDecayBase::G4RadioactiveDecayBase().
void G4HadronicProcessStore::RegisterInteraction (G4HadronicProcess * proc, G4HadronicInteraction * mod)
Definition at line 459 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 459 of file G4HadronicProcessStore.cc
References G4HadronicInteraction::GetModelName(), k, m_map, modelName, n_model, n_proc, and process.
Referenced by G4HadronicProcess::RegisterMe().
void G4HadronicProcessStore::RegisterParticle (G4HadronicProcess * proc, const G4ParticleDefinition * part)
Definition at line 424 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 424 of file G4HadronicProcessStore.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), it, n_part, n_proc, p_map, particle, process, verbose, and wasPrinted.
Referenced by G4HadronicProcess::PreparePhysicsTable().
void G4HadronicProcessStore::RegisterParticleForExtraProcess (G4VProcess * proc, const G4ParticleDefinition * part)
Definition at line 512 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 512 of file G4HadronicProcessStore.cc
References ep_map, extraProcess, it, n_extra, n_part, particle, and wasPrinted.
Referenced by G4RadioactiveDecayBase::BuildPhysicsTable(), G4RadioactiveDecay::BuildPhysicsTable(), G4NeutronTrackingCut::ConstructProcess(), G4AntiNeutronAnnihilationAtRest::PreparePhysicsTable(), G4MuonMinusAtomicCapture::PreparePhysicsTable(), and G4HadronStoppingProcess::PreparePhysicsTable().
void G4HadronicProcessStore::SetBuildXSTable (G4bool val)
Definition at line 559 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 559 of file G4HadronicProcessStore.cc
References buildXSTable.
void G4HadronicProcessStore::SetEpReportLevel (G4int level)
Definition at line 947 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 947 of file G4HadronicProcessStore.cc
References G4cout, G4endl, and process.
Referenced by G4HadronicEPTestMessenger::SetNewValue().
void G4HadronicProcessStore::SetProcessAbsLevel (G4double absoluteLevel)
Definition at line 958 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 958 of file G4HadronicProcessStore.cc
References G4cout, G4endl, G4HadronicProcess::GetEnergyMomentumCheckLevels(), process, and G4HadronicProcess::SetEnergyMomentumCheckLevels().
Referenced by G4HadronicEPTestMessenger::SetNewValue().
void G4HadronicProcessStore::SetProcessRelLevel (G4double relativeLevel)
Definition at line 973 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 973 of file G4HadronicProcessStore.cc
References G4cout, G4endl, G4HadronicProcess::GetEnergyMomentumCheckLevels(), process, and G4HadronicProcess::SetEnergyMomentumCheckLevels().
Referenced by G4HadronicEPTestMessenger::SetNewValue().
void G4HadronicProcessStore::SetVerbose (G4int val)
Definition at line 883 of file G4HadronicProcessStore.cc.
View newest version in sPHENIX GitHub at line 883 of file G4HadronicProcessStore.cc
References n_model, n_proc, process, and verbose.
Referenced by PHG4Reco::InitRun(), and main().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4HadronicProcessStore > friend
Definition at line 70 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HadronicProcessStore.hh
Member Data Documentation
G4bool G4HadronicProcessStore::buildTableStart private
Definition at line 252 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 252 of file G4HadronicProcessStore.hh
Referenced by G4HadronicProcessStore(), and PrintInfo().
G4bool G4HadronicProcessStore::buildXSTable private
Definition at line 253 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 253 of file G4HadronicProcessStore.hh
Referenced by G4HadronicProcessStore(), GetBuildXSTable(), and SetBuildXSTable().
PD G4HadronicProcessStore::currentParticle private
Definition at line 257 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 257 of file G4HadronicProcessStore.hh
Referenced by FindProcess(), and G4HadronicProcessStore().
HP G4HadronicProcessStore::currentProcess private
Definition at line 256 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 256 of file G4HadronicProcessStore.hh
Referenced by FindProcess(), and G4HadronicProcessStore().
std::multimap<PD,G4VProcess*> G4HadronicProcessStore::ep_map private
Definition at line 243 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 243 of file G4HadronicProcessStore.hh
Referenced by Dump(), PrintHtml(), and RegisterParticleForExtraProcess().
std::vector<G4VProcess*> G4HadronicProcessStore::extraProcess private
Definition at line 242 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 242 of file G4HadronicProcessStore.hh
Referenced by Clean(), DeRegisterExtraProcess(), RegisterExtraProcess(), and RegisterParticleForExtraProcess().
G4ThreadLocal G4HadronicProcessStore * G4HadronicProcessStore::instance = nullptr static private
Definition at line 225 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 225 of file G4HadronicProcessStore.hh
Referenced by Instance().
G4DynamicParticle G4HadronicProcessStore::localDP private
Definition at line 260 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 260 of file G4HadronicProcessStore.hh
Referenced by FindProcess(), GetCaptureCrossSectionPerAtom(), GetChargeExchangeCrossSectionPerAtom(), GetElasticCrossSectionPerAtom(), GetFissionCrossSectionPerAtom(), and GetInelasticCrossSectionPerAtom().
std::multimap<HP,HI> G4HadronicProcessStore::m_map private
Definition at line 239 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 239 of file G4HadronicProcessStore.hh
Referenced by Print(), PrintHtml(), and RegisterInteraction().
std::vector<G4HadronicInteraction*> G4HadronicProcessStore::model private
Definition at line 233 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 233 of file G4HadronicProcessStore.hh
std::vector<G4String> G4HadronicProcessStore::modelName private
Definition at line 234 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 234 of file G4HadronicProcessStore.hh
Referenced by Print(), and RegisterInteraction().
G4int G4HadronicProcessStore::n_extra private
Definition at line 249 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 249 of file G4HadronicProcessStore.hh
Referenced by Clean(), DeRegisterExtraProcess(), G4HadronicProcessStore(), RegisterExtraProcess(), and RegisterParticleForExtraProcess().
G4int G4HadronicProcessStore::n_model private
Definition at line 247 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 247 of file G4HadronicProcessStore.hh
Referenced by G4HadronicProcessStore(), Print(), RegisterInteraction(), and SetVerbose().
G4int G4HadronicProcessStore::n_part private
Definition at line 248 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 248 of file G4HadronicProcessStore.hh
Referenced by Dump(), G4HadronicProcessStore(), PrintInfo(), RegisterParticle(), and RegisterParticleForExtraProcess().
G4int G4HadronicProcessStore::n_proc private
Definition at line 246 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 246 of file G4HadronicProcessStore.hh
Referenced by Clean(), DeRegister(), Dump(), G4HadronicProcessStore(), Register(), RegisterExtraProcess(), RegisterInteraction(), RegisterParticle(), and SetVerbose().
std::multimap<PD,HP> G4HadronicProcessStore::p_map private
Definition at line 238 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 238 of file G4HadronicProcessStore.hh
Referenced by Dump(), FindProcess(), PrintHtml(), and RegisterParticle().
std::vector<PD> G4HadronicProcessStore::particle private
Definition at line 235 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 235 of file G4HadronicProcessStore.hh
Referenced by Dump(), Print(), PrintInfo(), RegisterParticle(), and RegisterParticleForExtraProcess().
std::vector<G4HadronicProcess*> G4HadronicProcessStore::process private
Definition at line 232 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 232 of file G4HadronicProcessStore.hh
Referenced by Clean(), DeRegister(), Dump(), Print(), Register(), RegisterExtraProcess(), RegisterInteraction(), RegisterParticle(), SetEpReportLevel(), SetProcessAbsLevel(), SetProcessRelLevel(), and SetVerbose().
G4HadronicEPTestMessenger* G4HadronicProcessStore::theEPTestMessenger private
Definition at line 262 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 262 of file G4HadronicProcessStore.hh
Referenced by G4HadronicProcessStore(), and ~G4HadronicProcessStore().
PD G4HadronicProcessStore::theGenericIon private
Definition at line 258 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 258 of file G4HadronicProcessStore.hh
Referenced by FindProcess(), and G4HadronicProcessStore().
G4int G4HadronicProcessStore::verbose private
Definition at line 251 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 251 of file G4HadronicProcessStore.hh
Referenced by DeRegisterExtraProcess(), G4HadronicProcessStore(), GetVerbose(), PrintInfo(), Register(), RegisterExtraProcess(), RegisterParticle(), and SetVerbose().
std::vector<G4int> G4HadronicProcessStore::wasPrinted private
Definition at line 236 of file G4HadronicProcessStore.hh.
View newest version in sPHENIX GitHub at line 236 of file G4HadronicProcessStore.hh
Referenced by Dump(), Print(), RegisterParticle(), and RegisterParticleForExtraProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadronicProcessStore.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/src/G4HadronicProcessStore.cc