ECCE @ EIC Software: G4P1ToolsManager Class Reference
G4P1ToolsManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4P1ToolsManager.hh>
Public Member Functions
G4P1ToolsManager (const G4AnalysisManagerState &state)
virtual ~G4P1ToolsManager ()
G4int AddP1 (const G4String &name, tools::histo::p1d *p1d)
void AddP1Vector (const std::vector< tools::histo::p1d * > &p1Vector)
tools::histo::p1d * GetP1 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::p1d * >
::iterator BeginP1 ()
std::vector< tools::histo::p1d * >
::iterator EndP1 ()
std::vector< tools::histo::p1d * >
::const_iterator BeginConstP1 () const
std::vector< tools::histo::p1d * >
::const_iterator EndConstP1 () const
const std::vector
< tools::histo::p1d * > & GetP1Vector () const
const std::vector
< G4HnInformation * > & GetHnVector () const
Public Member Functions inherited from G4VP1Manager
G4VP1Manager ()
virtual ~G4VP1Manager ()
G4VP1Manager (const G4VP1Manager &rhs)=delete
G4VP1Manager & operator= (const G4VP1Manager &rhs)=delete
Public Member Functions inherited from G4THnManager< tools::histo::p1d >
G4THnManager (const G4AnalysisManagerState &state, const G4String &hnType)
virtual ~G4THnManager ()
G4bool Reset ()
G4bool IsEmpty () const
Protected Member Functions
virtual G4int CreateP1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinScheme="linear") final
virtual G4int CreateP1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none") final
virtual G4bool SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinScheme="linear") final
virtual G4bool SetP1 (G4int id, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none") final
virtual G4bool ScaleP1 (G4int id, G4double factor) final
virtual G4bool FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0) final
virtual G4int GetP1Id (const G4String &name, G4bool warn=true) const final
virtual G4int GetP1Nbins (G4int id) const final
virtual G4double GetP1Xmin (G4int id) const final
virtual G4double GetP1Xmax (G4int id) const final
virtual G4double GetP1XWidth (G4int id) const final
virtual G4double GetP1Ymin (G4int id) const final
virtual G4double GetP1Ymax (G4int id) const final
virtual G4bool SetP1Title (G4int id, const G4String &title) final
virtual G4bool SetP1XAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetP1YAxisTitle (G4int id, const G4String &title) final
virtual G4String GetP1Title (G4int id) const final
virtual G4String GetP1XAxisTitle (G4int id) const final
virtual G4String GetP1YAxisTitle (G4int id) const final
virtual std::shared_ptr
< G4HnManager > GetHnManager () final
Protected Member Functions inherited from G4THnManager< tools::histo::p1d >
void AddTVector (const std::vector< tools::histo::p1d * > &tVector)
std::vector< tools::histo::p1d * >
::iterator BeginT ()
std::vector< tools::histo::p1d * >
::iterator EndT ()
std::vector< tools::histo::p1d * >
::const_iterator BeginConstT () const
std::vector< tools::histo::p1d * >
::const_iterator EndConstT () const
tools::histo::p1d * GetTInFunction (G4int id, G4String functionName, G4bool warn=true, G4bool onlyIfActive=true) const
G4int RegisterT (tools::histo::p1d *t, const G4String &name)
G4int GetTId (const G4String &name, G4bool warn=true) const
Private Member Functions
void AddP1Information (const G4String &name, const G4String &xunitName, const G4String &yunitName, const G4String &xfcnName, const G4String &yfcnName, G4BinScheme xbinScheme) const
Static Private Attributes
static const G4int kDimension = 1
Additional Inherited Members
Protected Attributes inherited from G4THnManager< tools::histo::p1d >
const G4AnalysisManagerState & fState
std::vector< tools::histo::p1d * > fTVector
std::map< G4String, G4int > fNameIdMap
std::shared_ptr< G4HnManager > fHnManager
Detailed Description
Definition at line 52 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 52 of file G4P1ToolsManager.hh
Constructor & Destructor Documentation
G4P1ToolsManager::G4P1ToolsManager (const G4AnalysisManagerState & state) explicit
Definition at line 48 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 48 of file G4P1ToolsManager.cc
G4P1ToolsManager::~G4P1ToolsManager () virtual
Definition at line 54 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4P1ToolsManager.cc
Member Function Documentation
G4int G4P1ToolsManager::AddP1 (const G4String & name, tools::histo::p1d * p1d)
Definition at line 557 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 557 of file G4P1ToolsManager.cc
References AddP1Information(), G4THnManager< tools::histo::p1d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::p1d >::RegisterT().
Referenced by G4CsvAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP1Impl(), and G4Hdf5AnalysisReader::ReadP1Impl().
void G4P1ToolsManager::AddP1Information (const G4String & name, const G4String & xunitName, const G4String & yunitName, const G4String & xfcnName, const G4String & yfcnName, G4BinScheme xbinScheme) const private
Definition at line 236 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 236 of file G4P1ToolsManager.cc
References G4HnInformation::AddDimension(), and G4THnManager< tools::histo::p1d >::fHnManager.
Referenced by AddP1(), and CreateP1().
void G4P1ToolsManager::AddP1Vector (const std::vector< tools::histo::p1d * > & p1Vector)
Definition at line 580 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 580 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::AddTVector().
Referenced by G4XmlAnalysisManager::WriteP1(), G4CsvAnalysisManager::WriteP1(), G4Hdf5AnalysisManager::WriteP1(), and G4RootAnalysisManager::WriteP1().
std::vector< tools::histo::p1d * >::const_iterator G4P1ToolsManager::BeginConstP1 () const inline
Definition at line 178 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 178 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::BeginConstT().
std::vector< tools::histo::p1d * >::iterator G4P1ToolsManager::BeginP1 () inline
Definition at line 171 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 171 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::BeginT().
G4int G4P1ToolsManager::CreateP1 (const G4String & name, const G4String & title, G4int nbins, G4double xmin, G4double xmax, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinScheme = "linear") final protected virtual
Implements G4VP1Manager.
Definition at line 253 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 253 of file G4P1ToolsManager.cc
References AddP1Information(), G4THnManager< tools::histo::p1d >::fState, G4Analysis::GetBinScheme(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::p1d >::RegisterT().
G4int G4P1ToolsManager::CreateP1 (const G4String & name, const G4String & title, const std::vector< G4double > & edges, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none") final protected virtual
Implements G4VP1Manager.
Definition at line 288 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 288 of file G4P1ToolsManager.cc
References AddP1Information(), G4THnManager< tools::histo::p1d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::p1d >::RegisterT().
std::vector< tools::histo::p1d * >::const_iterator G4P1ToolsManager::EndConstP1 () const inline
Definition at line 182 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 182 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::EndConstT().
std::vector< tools::histo::p1d * >::iterator G4P1ToolsManager::EndP1 () inline
Definition at line 174 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 174 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::EndT().
G4bool G4P1ToolsManager::FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight = 1.0) final protected virtual
Implements G4VP1Manager.
Definition at line 399 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 399 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::fHnManager, G4THnManager< tools::histo::p1d >::fState, G4AnalysisManagerState::GetIsActivation(), G4THnManager< tools::histo::p1d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kX, G4Analysis::kY, G4AnalysisVerbose::Message(), and weight.
std::shared_ptr< G4HnManager > G4P1ToolsManager::GetHnManager () inline final protected virtual
Implements G4VP1Manager.
Definition at line 191 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 191 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::fHnManager.
const std::vector< G4HnInformation * > & G4P1ToolsManager::GetHnVector () const inline
Definition at line 188 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 188 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::fHnManager.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisManager::WriteP1(), G4CsvAnalysisManager::WriteP1(), G4Hdf5AnalysisManager::WriteP1(), and G4RootAnalysisManager::WriteP1().
tools::histo::p1d * G4P1ToolsManager::GetP1 (G4int id, G4bool warn = true, G4bool onlyIfActive = true) const
Definition at line 587 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 587 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction().
G4int G4P1ToolsManager::GetP1Id (const G4String & name, G4bool warn = true) const final protected virtual
Implements G4VP1Manager.
Definition at line 434 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 434 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTId().
G4int G4P1ToolsManager::GetP1Nbins (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 440 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 440 of file G4P1ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::p1d >::GetTInFunction(), and G4Analysis::kX.
G4String G4P1ToolsManager::GetP1Title (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 525 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 525 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction(), and G4Analysis::GetTitle().
const std::vector< tools::histo::p1d * > & G4P1ToolsManager::GetP1Vector () const inline
Definition at line 185 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 185 of file G4P1ToolsManager.hh
References G4THnManager< tools::histo::p1d >::fTVector.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisManager::WriteP1(), G4CsvAnalysisManager::WriteP1(), G4Hdf5AnalysisManager::WriteP1(), and G4RootAnalysisManager::WriteP1().
G4String G4P1ToolsManager::GetP1XAxisTitle (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 535 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 535 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::p1d >::GetTInFunction(), and G4Analysis::kX.
G4double G4P1ToolsManager::GetP1Xmax (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 460 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 460 of file G4P1ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::p1d >::GetTInFunction(), and G4Analysis::kX.
G4double G4P1ToolsManager::GetP1Xmin (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 449 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 449 of file G4P1ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::p1d >::GetTInFunction(), and G4Analysis::kX.
G4double G4P1ToolsManager::GetP1XWidth (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 469 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 469 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::fHnManager, G4THnManager< tools::histo::p1d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kX.
G4String G4P1ToolsManager::GetP1YAxisTitle (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 544 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 544 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::p1d >::GetTInFunction(), and G4Analysis::kY.
G4double G4P1ToolsManager::GetP1Ymax (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 489 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 489 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction().
G4double G4P1ToolsManager::GetP1Ymin (G4int id) const final protected virtual
Implements G4VP1Manager.
Definition at line 478 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 478 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction().
G4bool G4P1ToolsManager::ScaleP1 (G4int id, G4double factor) final protected virtual
Implements G4VP1Manager.
Definition at line 390 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 390 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction().
G4bool G4P1ToolsManager::SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinScheme = "linear") final protected virtual
Implements G4VP1Manager.
Definition at line 320 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 320 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::fHnManager, G4THnManager< tools::histo::p1d >::fState, G4Analysis::GetBinScheme(), G4THnManager< tools::histo::p1d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4P1ToolsManager::SetP1 (G4int id, const std::vector< G4double > & edges, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none") final protected virtual
Implements G4VP1Manager.
Definition at line 356 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 356 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::fHnManager, G4THnManager< tools::histo::p1d >::fState, G4THnManager< tools::histo::p1d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4P1ToolsManager::SetP1Title (G4int id, const G4String & title) final protected virtual
Implements G4VP1Manager.
Definition at line 498 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 498 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction(), and SetTitle().
G4bool G4P1ToolsManager::SetP1XAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VP1Manager.
Definition at line 507 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 507 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction(), G4Analysis::kX, and G4Analysis::SetAxisTitle().
G4bool G4P1ToolsManager::SetP1YAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VP1Manager.
Definition at line 516 of file G4P1ToolsManager.cc.
View newest version in sPHENIX GitHub at line 516 of file G4P1ToolsManager.cc
References G4THnManager< tools::histo::p1d >::GetTInFunction(), G4Analysis::kY, and G4Analysis::SetAxisTitle().
Member Data Documentation
const G4int G4P1ToolsManager::kDimension = 1 static private
Definition at line 166 of file G4P1ToolsManager.hh.
View newest version in sPHENIX GitHub at line 166 of file G4P1ToolsManager.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4P1ToolsManager.hh
geant4/tree/geant4-10.6-release/source/analysis/hntools/src/G4P1ToolsManager.cc