ECCE @ EIC Software: PrtOpBoundaryProcess Class Reference
PrtOpBoundaryProcess Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/PrtOpBoundaryProcess.h>
Public Member Functions
PrtOpBoundaryProcess ()
~PrtOpBoundaryProcess () override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
Public Member Functions inherited from G4OpBoundaryProcess
G4OpBoundaryProcess (const G4String &processName="OpBoundary", G4ProcessType type=fOptical)
virtual ~G4OpBoundaryProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *condition) override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4OpBoundaryProcessStatus GetStatus () const
virtual void SetInvokeSD (G4bool)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Public Attributes
G4EicDircDetector * m_Detector
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 9 of file PrtOpBoundaryProcess.h.
View newest version in sPHENIX GitHub at line 9 of file PrtOpBoundaryProcess.h
Constructor & Destructor Documentation
PrtOpBoundaryProcess::PrtOpBoundaryProcess ()
Definition at line 7 of file PrtOpBoundaryProcess.cxx.
View newest version in sPHENIX GitHub at line 7 of file PrtOpBoundaryProcess.cxx
PrtOpBoundaryProcess::~PrtOpBoundaryProcess () inline override
Definition at line 13 of file PrtOpBoundaryProcess.h.
View newest version in sPHENIX GitHub at line 13 of file PrtOpBoundaryProcess.h
Member Function Documentation
G4VParticleChange * PrtOpBoundaryProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 11 of file PrtOpBoundaryProcess.cxx.
View newest version in sPHENIX GitHub at line 11 of file PrtOpBoundaryProcess.cxx
References FresnelRefraction, fStopAndKill, G4VPhysicalVolume::GetName(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4OpBoundaryProcess::GetStatus(), G4OpBoundaryProcess::PostStepDoIt(), G4VParticleChange::ProposeTrackStatus(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4EicDircDetector* PrtOpBoundaryProcess::m_Detector
Definition at line 18 of file PrtOpBoundaryProcess.h.
View newest version in sPHENIX GitHub at line 18 of file PrtOpBoundaryProcess.h
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/PrtOpBoundaryProcess.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eicdirc/PrtOpBoundaryProcess.cxx