ECCE @ EIC Software: G4MolecularDissociationChannel Class Reference
G4MolecularDissociationChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularDissociationChannel.hh>
Public Types
using Product = const G4MolecularConfiguration
using ProductList = std::vector< Product * >
Public Member Functions
G4MolecularDissociationChannel ()
G4MolecularDissociationChannel (const G4String &)
~G4MolecularDissociationChannel ()=default
G4MolecularDissociationChannel (const G4MolecularDissociationChannel &)=default
G4MolecularDissociationChannel & operator= (const G4MolecularDissociationChannel &right)=default
void AddProduct (Product *, G4double displacement=0.)
void SetName (const G4String &)
void SetEnergy (G4double)
void SetProbability (G4double)
void SetDecayTime (G4double)
void SetRMSMotherMoleculeDisplacement (G4double)
void SetDisplacementType (DisplacementType)
const G4String & GetName () const
G4int GetNbProducts () const
Product * GetProduct (int) const
const std::vector< G4double > & GetRMSProductsDisplacement () const
G4double GetEnergy () const
G4double GetProbability () const
G4double GetDecayTime () const
G4double GetRMSMotherMoleculeDisplacement () const
DisplacementType GetDisplacementType () const
G4double GetRMSRadialDisplacementOfProduct (Product *)
Private Attributes
DisplacementType fDisplacementType
G4String fName
ProductList fProductsVector
G4double fReleasedEnergy
G4double fProbability
G4double fDecayTime
G4double fRMSMotherMoleculeDisplacement
std::vector< G4double > fRMSProductsDisplacementVector
Detailed Description
Definition at line 63 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4MolecularDissociationChannel.hh
Member Typedef Documentation
using G4MolecularDissociationChannel::Product = const G4MolecularConfiguration
Definition at line 74 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4MolecularDissociationChannel.hh
using G4MolecularDissociationChannel::ProductList = std::vector<Product*>
Definition at line 75 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4MolecularDissociationChannel.hh
Constructor & Destructor Documentation
G4MolecularDissociationChannel::G4MolecularDissociationChannel ()
Definition at line 49 of file G4MolecularDissociationChannel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4MolecularDissociationChannel.cc
G4MolecularDissociationChannel::G4MolecularDissociationChannel (const G4String & aName) explicit
Definition at line 41 of file G4MolecularDissociationChannel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4MolecularDissociationChannel.cc
References fName.
G4MolecularDissociationChannel::~G4MolecularDissociationChannel () default
G4MolecularDissociationChannel::G4MolecularDissociationChannel (const G4MolecularDissociationChannel &) default
Member Function Documentation
void G4MolecularDissociationChannel::AddProduct (Product * pProduct, G4double displacement = 0.)
Definition at line 60 of file G4MolecularDissociationChannel.cc.
View newest version in sPHENIX GitHub at line 60 of file G4MolecularDissociationChannel.cc
References fProductsVector, and fRMSProductsDisplacementVector.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4EmDNAChemistry_option2::ConstructDissociationChannels().
G4double G4MolecularDissociationChannel::GetDecayTime () const inline
Definition at line 181 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4MolecularDissociationChannel.hh
References fDecayTime.
DisplacementType G4MolecularDissociationChannel::GetDisplacementType () const inline
Definition at line 205 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 205 of file G4MolecularDissociationChannel.hh
References fDisplacementType.
Referenced by G4DNAWaterDissociationDisplacer::GetMotherMoleculeDisplacement(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
G4double G4MolecularDissociationChannel::GetEnergy () const inline
Definition at line 167 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4MolecularDissociationChannel.hh
References fReleasedEnergy.
Referenced by G4DNAMolecularDissociation::DecayIt().
const G4String & G4MolecularDissociationChannel::GetName (void) const inline
Definition at line 152 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4MolecularDissociationChannel.hh
References fName.
Referenced by G4DNAMolecularDissociation::DecayIt(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
G4int G4MolecularDissociationChannel::GetNbProducts () const
Definition at line 69 of file G4MolecularDissociationChannel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4MolecularDissociationChannel.cc
References fProductsVector.
Referenced by G4DNAMolecularDissociation::DecayIt(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
G4double G4MolecularDissociationChannel::GetProbability () const inline
Definition at line 174 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4MolecularDissociationChannel.hh
References fProbability.
Referenced by G4MolecularDissociationTable::CheckDataConsistency(), and G4DNAMolecularDissociation::DecayIt().
G4MolecularDissociationChannel::Product * G4MolecularDissociationChannel::GetProduct (int index) const
Definition at line 76 of file G4MolecularDissociationChannel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4MolecularDissociationChannel.cc
References fProductsVector.
Referenced by G4DNAMolecularDissociation::DecayIt(), and G4DNAWaterDissociationDisplacer::GetProductsDisplacement().
G4double G4MolecularDissociationChannel::GetRMSMotherMoleculeDisplacement () const inline
Definition at line 189 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 189 of file G4MolecularDissociationChannel.hh
References fRMSMotherMoleculeDisplacement.
const std::vector< G4double > & G4MolecularDissociationChannel::GetRMSProductsDisplacement () const inline
Definition at line 160 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4MolecularDissociationChannel.hh
References fRMSProductsDisplacementVector.
G4double G4MolecularDissociationChannel::GetRMSRadialDisplacementOfProduct (Product * pProduct)
Definition at line 84 of file G4MolecularDissociationChannel.cc.
View newest version in sPHENIX GitHub at line 84 of file G4MolecularDissociationChannel.cc
References fProductsVector, fRMSProductsDisplacementVector, and it.
G4MolecularDissociationChannel& G4MolecularDissociationChannel::operator= (const G4MolecularDissociationChannel & right) default
void G4MolecularDissociationChannel::SetDecayTime (G4double value) inline
Definition at line 136 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 136 of file G4MolecularDissociationChannel.hh
References fDecayTime.
void G4MolecularDissociationChannel::SetDisplacementType (DisplacementType aDisplacementType) inline
Definition at line 197 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 197 of file G4MolecularDissociationChannel.hh
References fDisplacementType.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4EmDNAChemistry_option2::ConstructDissociationChannels().
void G4MolecularDissociationChannel::SetEnergy (G4double value) inline
Definition at line 122 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4MolecularDissociationChannel.hh
References fReleasedEnergy.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4EmDNAChemistry_option2::ConstructDissociationChannels().
void G4MolecularDissociationChannel::SetName (const G4String & value) inline
Definition at line 115 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4MolecularDissociationChannel.hh
References fName.
void G4MolecularDissociationChannel::SetProbability (G4double value) inline
Definition at line 129 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4MolecularDissociationChannel.hh
References fProbability.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), and G4EmDNAChemistry_option2::ConstructDissociationChannels().
void G4MolecularDissociationChannel::SetRMSMotherMoleculeDisplacement (G4double value) inline
Definition at line 145 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4MolecularDissociationChannel.hh
References fRMSMotherMoleculeDisplacement.
Member Data Documentation
G4double G4MolecularDissociationChannel::fDecayTime private
Definition at line 107 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4MolecularDissociationChannel.hh
Referenced by GetDecayTime(), and SetDecayTime().
DisplacementType G4MolecularDissociationChannel::fDisplacementType private
Definition at line 102 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4MolecularDissociationChannel.hh
Referenced by GetDisplacementType(), and SetDisplacementType().
G4String G4MolecularDissociationChannel::fName private
Definition at line 103 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4MolecularDissociationChannel.hh
Referenced by G4MolecularDissociationChannel(), GetName(), and SetName().
G4double G4MolecularDissociationChannel::fProbability private
Definition at line 106 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MolecularDissociationChannel.hh
Referenced by GetProbability(), and SetProbability().
ProductList G4MolecularDissociationChannel::fProductsVector private
Definition at line 104 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4MolecularDissociationChannel.hh
Referenced by AddProduct(), GetNbProducts(), GetProduct(), and GetRMSRadialDisplacementOfProduct().
G4double G4MolecularDissociationChannel::fReleasedEnergy private
Definition at line 105 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4MolecularDissociationChannel.hh
Referenced by GetEnergy(), and SetEnergy().
G4double G4MolecularDissociationChannel::fRMSMotherMoleculeDisplacement private
Definition at line 109 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4MolecularDissociationChannel.hh
Referenced by GetRMSMotherMoleculeDisplacement(), and SetRMSMotherMoleculeDisplacement().
std::vector<G4double> G4MolecularDissociationChannel::fRMSProductsDisplacementVector private
Definition at line 110 of file G4MolecularDissociationChannel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4MolecularDissociationChannel.hh
Referenced by AddProduct(), GetRMSProductsDisplacement(), and GetRMSRadialDisplacementOfProduct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MolecularDissociationChannel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4MolecularDissociationChannel.cc