ECCE @ EIC Software: geant4/tree/geant4-10.6-release/config/liblist.c File Reference
liblist.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>
#include <errno.h>
#include <stdlib.h>
Macros
#define BUFSIZE 1000000
#define TRIGSIZE 1000
#define NLIBMAX 200
Functions
char ** parsedir (char *directory, int *argc)
int main (int argc, char **argv)
Variables
char * optarg
int optind
int opterr
int optopt
Macro Definition Documentation
#define BUFSIZE 1000000
Definition at line 40 of file liblist.c.
View newest version in sPHENIX GitHub at line 40 of file liblist.c
Referenced by G4UItcsh::G4UItcsh(), main(), G4MPIbatch::ReadCommand(), G4UIbatch::ReadCommand(), and G4UIExecutive::SelectSessionByFile().
#define NLIBMAX 200
Definition at line 42 of file liblist.c.
View newest version in sPHENIX GitHub at line 42 of file liblist.c
Referenced by main().
#define TRIGSIZE 1000
Definition at line 41 of file liblist.c.
View newest version in sPHENIX GitHub at line 41 of file liblist.c
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 126 of file liblist.c.
View newest version in sPHENIX GitHub at line 126 of file liblist.c
References buffer, bufferPtr, BUFSIZE, c, g4zmq::exit(), fclose(), fp, NLIBMAX, optarg, optind, parsedir(), G4InuclParticleNames::pp, printf(), and TRIGSIZE.
char** parsedir (char * directory, int * argc)
Definition at line 47 of file liblist.c.
View newest version in sPHENIX GitHub at line 47 of file liblist.c
References g4zmq::exit(), and phelp().
Referenced by main().
Variable Documentation
char* optarg
Referenced by main(), and G4MPImanager::ParseArguments().
int opterr
Referenced by G4MPImanager::ParseArguments().
int optind
Referenced by main(), and G4MPImanager::ParseArguments().
int optopt