ECCE @ EIC Software: CexmcRunManagerMessenger Class Reference
CexmcRunManagerMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRunManagerMessenger.hh>
Public Member Functions
CexmcRunManagerMessenger (CexmcRunManager *runManager)
~CexmcRunManagerMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CexmcRunManager * runManager
G4UIcmdWithAString * setProductionModel
G4UIcmdWithAString * setGdmlFile
G4UIcmdWithAString * setGuiMacro
G4UIcmdWithAString * setEventCountPolicy
G4UIcmdWithAString * setEventDataVerboseLevel
G4UIcmdWithoutParameter * registerScenePrimitives
G4UIcmdWithABool * validateGdmlFile
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 57 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file CexmcRunManagerMessenger.hh
Constructor & Destructor Documentation
CexmcRunManagerMessenger::CexmcRunManagerMessenger (CexmcRunManager * runManager) explicit
Definition at line 53 of file CexmcRunManagerMessenger.cc.
View newest version in sPHENIX GitHub at line 53 of file CexmcRunManagerMessenger.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, CexmcMessenger::geometryDirName, CexmcMessenger::physicsDirName, registerScenePrimitives, CexmcMessenger::runDirName, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), setEventCountPolicy, setEventDataVerboseLevel, setGdmlFile, G4UIcommand::SetGuidance(), setGuiMacro, G4UIcmdWithAString::SetParameterName(), G4UIcmdWithABool::SetParameterName(), setProductionModel, validateGdmlFile, and CexmcMessenger::visDirName.
CexmcRunManagerMessenger::~CexmcRunManagerMessenger ()
Definition at line 163 of file CexmcRunManagerMessenger.cc.
View newest version in sPHENIX GitHub at line 163 of file CexmcRunManagerMessenger.cc
References registerScenePrimitives, setEventCountPolicy, setEventDataVerboseLevel, setGdmlFile, setGuiMacro, setProductionModel, and validateGdmlFile.
Member Function Documentation
void CexmcRunManagerMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 180 of file CexmcRunManagerMessenger.cc.
View newest version in sPHENIX GitHub at line 180 of file CexmcRunManagerMessenger.cc
References CexmcCountAllEvents, CexmcCountEventsWithInteraction, CexmcCountEventsWithTrigger, CexmcEtaProduction, CexmcPionZeroProduction, CexmcUnknownProductionModel, CexmcWriteEventDataOnEveryEDT, CexmcWriteEventDataOnEveryTPT, CexmcWriteNoEventData, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithAnInteger::GetNewIntValue(), registerScenePrimitives, CexmcRunManager::RegisterScenePrimitives(), runManager, setEventCountPolicy, CexmcRunManager::SetEventCountPolicy(), setEventDataVerboseLevel, CexmcRunManager::SetEventDataVerboseLevel(), setGdmlFile, CexmcRunManager::SetGdmlFileName(), CexmcRunManager::SetGdmlFileValidation(), setGuiMacro, CexmcRunManager::SetGuiMacroName(), setProductionModel, CexmcRunManager::SetProductionModelType(), and validateGdmlFile.
Member Data Documentation
G4UIcmdWithoutParameter* CexmcRunManagerMessenger::registerScenePrimitives private
Definition at line 88 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
CexmcRunManager* CexmcRunManagerMessenger::runManager private
Definition at line 68 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcRunManagerMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* CexmcRunManagerMessenger::setEventCountPolicy private
Definition at line 76 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
G4UIcmdWithAString* CexmcRunManagerMessenger::setEventDataVerboseLevel private
Definition at line 78 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
G4UIcmdWithAString* CexmcRunManagerMessenger::setGdmlFile private
Definition at line 72 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
G4UIcmdWithAString* CexmcRunManagerMessenger::setGuiMacro private
Definition at line 74 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
G4UIcmdWithAString* CexmcRunManagerMessenger::setProductionModel private
Definition at line 70 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
G4UIcmdWithABool* CexmcRunManagerMessenger::validateGdmlFile private
Definition at line 90 of file CexmcRunManagerMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file CexmcRunManagerMessenger.hh
Referenced by CexmcRunManagerMessenger(), SetNewValue(), and ~CexmcRunManagerMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRunManagerMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcRunManagerMessenger.cc