ECCE @ EIC Software: G4tgrUtils Class Reference
G4tgrUtils Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrUtils.hh>
Public Member Functions
G4tgrUtils ()
~G4tgrUtils ()
Static Public Member Functions
static G4bool IsSeparator (char)
static G4bool IsNumber (const G4String &str)
static G4bool IsInteger (const G4double val, const G4double precision=1.e-6)
static G4bool IsFunction (const G4String &word)
static G4bool WordIsUnit (const G4String &word)
static void Dump3v (const G4ThreeVector &vec, const char *msg)
static void Dumprm (const G4RotationMatrix &rm, const char *msg)
static void DumpVS (const std::vector< G4String > &wl, const char *msg)
static void DumpVS (const std::vector< G4String > &wl, const char *msg, std::ostream &outs)
static void CheckWLsize (const std::vector< G4String > &wl, unsigned int nWCheck, WLSIZEtype st, const G4String &methodName)
static G4bool CheckListSize (unsigned int nWreal, unsigned int nWcheck, WLSIZEtype st, G4String &outstr)
static G4String SubColon (const G4String &str)
static G4String GetString (const G4String &str)
static G4double GetDouble (const G4String &str, G4double unitval=1.)
static G4int GetInt (const G4String &str)
static G4bool GetBool (const G4String &str)
static G4RotationMatrix GetRotationFromDirection (G4ThreeVector dir)
static G4bool AreWordsEquivalent (const G4String &word1, const G4String &word2)
Static Private Attributes
static G4ThreadLocal
G4tgrEvaluator * theEvaluator = 0
Detailed Description
Definition at line 53 of file G4tgrUtils.hh.
View newest version in sPHENIX GitHub at line 53 of file G4tgrUtils.hh
Constructor & Destructor Documentation
G4tgrUtils::G4tgrUtils ()
Definition at line 52 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 52 of file G4tgrUtils.cc
References theEvaluator.
G4tgrUtils::~G4tgrUtils ()
Definition at line 59 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 59 of file G4tgrUtils.cc
References theEvaluator.
Member Function Documentation
G4bool G4tgrUtils::AreWordsEquivalent (const G4String & word1, const G4String & word2) static
Definition at line 672 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 672 of file G4tgrUtils.cc
References FatalException, and G4Exception().
Referenced by ExTGRCRegionCutsMgr::FindRegionData(), and G4tgrVolumeMgr::FindVolumes().
G4bool G4tgrUtils::CheckListSize (unsigned int nWreal, unsigned int nWcheck, WLSIZEtype st, G4String & outstr) static
Definition at line 497 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 497 of file G4tgrUtils.cc
References G4cerr, G4endl, WLSIZE_EQ, WLSIZE_GE, WLSIZE_GT, WLSIZE_LE, WLSIZE_LT, and WLSIZE_NE.
Referenced by G4tgbPlaceParameterisation::CheckNExtraData(), and CheckWLsize().
void G4tgrUtils::CheckWLsize (const std::vector< G4String > & wl, unsigned int nWCheck, WLSIZEtype st, const G4String & methodName) static
Definition at line 475 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 475 of file G4tgrUtils.cc
References CheckListSize(), G4UIcommand::ConvertToString(), DumpVS(), FatalException, and G4Exception().
Referenced by G4tgrVolume::AddCheckOverlaps(), G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceReplica(), G4tgrVolume::AddRGBColour(), G4tgrVolume::AddVisibility(), G4tgrParameterMgr::CheckIfNewParameter(), G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), G4tgrIsotope::G4tgrIsotope(), G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), G4tgrPlaceDivRep::G4tgrPlaceDivRep(), G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), and G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrUtils::Dump3v (const G4ThreeVector & vec, const char * msg) static
Definition at line 126 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 126 of file G4tgrUtils.cc
References G4cout, and G4endl.
void G4tgrUtils::Dumprm (const G4RotationMatrix & rm, const char * msg) static
Definition at line 134 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 134 of file G4tgrUtils.cc
References G4cout, G4endl, CLHEP::HepRotation::xx(), CLHEP::HepRotation::xy(), CLHEP::HepRotation::xz(), CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
void G4tgrUtils::DumpVS (const std::vector< G4String > & wl, const char * msg) static
Definition at line 158 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 158 of file G4tgrUtils.cc
References G4cout.
Referenced by G4tgrRotationMatrixFactory::AddRotMatrix(), CheckWLsize(), G4tgrMaterialFactory::ErrorAlreadyExists(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrLineProcessor::ProcessLine(), and G4tgrFileReader::ReadFiles().
void G4tgrUtils::DumpVS (const std::vector< G4String > & wl, const char * msg, std::ostream & outs) static
Definition at line 144 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 144 of file G4tgrUtils.cc
References G4endl.
G4bool G4tgrUtils::GetBool (const G4String & str) static
Definition at line 448 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 448 of file G4tgrUtils.cc
References FatalException, and G4Exception().
Referenced by G4tgrVolume::AddCheckOverlaps(), and G4tgrVolume::AddVisibility().
G4double G4tgrUtils::GetDouble (const G4String & str, G4double unitval = 1.) static
Definition at line 205 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 205 of file G4tgrUtils.cc
References G4UIcommand::ConvertToString(), DBL_MAX, DBL_MIN, HepTool::Evaluator::evaluate(), FatalException, G4tgrParameterMgr::FindParameter(), FLT_MAX, FLT_MIN, G4cout, G4endl, G4Exception(), G4tgrParameterMgr::GetInstance(), G4UnitDefinition::GetValueOf(), G4tgrMessenger::GetVerboseLevel(), INT_MAX, INT_MIN, IsFunction(), IsNumber(), HepTool::Evaluator::OK, G4tgrEvaluator::print_error(), HepTool::Evaluator::status(), theEvaluator, and WordIsUnit().
Referenced by G4tgrParameterMgr::AddParameterNumber(), G4tgrVolume::AddPlaceReplica(), G4tgrVolume::AddRGBColour(), G4tgrSolid::FillSolidParams(), G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), G4tgrIsotope::G4tgrIsotope(), G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), G4tgrPlaceDivRep::G4tgrPlaceDivRep(), G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), G4tgrRotationMatrix::G4tgrRotationMatrix(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetInt(), G4tgrLineProcessor::ProcessLine(), and ExTGRCRegionData::SetCutsData().
G4int G4tgrUtils::GetInt (const G4String & str) static
Definition at line 430 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 430 of file G4tgrUtils.cc
References FatalException, G4Exception(), GetDouble(), and IsInteger().
Referenced by G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), G4tgrIsotope::G4tgrIsotope(), G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrPlaceDivRep::G4tgrPlaceDivRep(), G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), and G4tgrVolumeDivision::G4tgrVolumeDivision().
G4RotationMatrix G4tgrUtils::GetRotationFromDirection (G4ThreeVector dir) static
Definition at line 626 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 626 of file G4tgrUtils.cc
References G4UIcommand::ConvertToString(), G4Exception(), G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), JustWarning, CLHEP::Hep3Vector::mag(), pi, CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4String G4tgrUtils::GetString (const G4String & str) static
Definition at line 180 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 180 of file G4tgrUtils.cc
References G4tgrParameterMgr::FindParameter(), G4cout, G4endl, G4tgrParameterMgr::GetInstance(), and G4tgrMessenger::GetVerboseLevel().
Referenced by G4tgrMaterialFactory::AddElementFromIsotopes(), G4tgrMaterialFactory::AddElementSimple(), G4tgrMaterialFactory::AddIsotope(), G4tgrMaterialFactory::AddMaterialMixture(), G4tgrMaterialFactory::AddMaterialSimple(), G4tgrRotationMatrixFactory::AddRotMatrix(), G4tgrElementFromIsotopes::G4tgrElementFromIsotopes(), G4tgrElementSimple::G4tgrElementSimple(), G4tgrIsotope::G4tgrIsotope(), G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), G4tgrPlaceDivRep::G4tgrPlaceDivRep(), G4tgrPlaceParameterisation::G4tgrPlaceParameterisation(), G4tgrPlaceSimple::G4tgrPlaceSimple(), G4tgrRotationMatrix::G4tgrRotationMatrix(), G4tgrSolid::G4tgrSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrVolume::G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), and G4tgrLineProcessor::ProcessLine().
G4bool G4tgrUtils::IsFunction (const G4String & word) static
Definition at line 595 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 595 of file G4tgrUtils.cc
Referenced by GetDouble().
G4bool G4tgrUtils::IsInteger (const G4double val, const G4double precision = 1.e-6) static
Definition at line 112 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 112 of file G4tgrUtils.cc
Referenced by GetInt().
G4bool G4tgrUtils::IsNumber (const G4String & str) static
Definition at line 81 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 81 of file G4tgrUtils.cc
Referenced by GetDouble(), and WordIsUnit().
G4bool G4tgrUtils::IsSeparator (char ch) static
Definition at line 66 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 66 of file G4tgrUtils.cc
G4String G4tgrUtils::SubColon (const G4String & str) static
Definition at line 165 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 165 of file G4tgrUtils.cc
References FatalException, and G4Exception().
G4bool G4tgrUtils::WordIsUnit (const G4String & word) static
Definition at line 556 of file G4tgrUtils.cc.
View newest version in sPHENIX GitHub at line 556 of file G4tgrUtils.cc
References IsNumber().
Referenced by GetDouble().
Member Data Documentation
G4ThreadLocal G4tgrEvaluator * G4tgrUtils::theEvaluator = 0 static private
Definition at line 107 of file G4tgrUtils.hh.
View newest version in sPHENIX GitHub at line 107 of file G4tgrUtils.hh
Referenced by G4tgrUtils(), GetDouble(), and ~G4tgrUtils().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrUtils.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrUtils.cc