ECCE @ EIC Software: G4TrajectoryDrawByParticleID Class Reference
G4TrajectoryDrawByParticleID Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByParticleID.hh>
Public Member Functions
G4TrajectoryDrawByParticleID (const G4String &name="Unspecified", G4VisTrajContext *context=0)
virtual ~G4TrajectoryDrawByParticleID ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const
virtual void Print (std::ostream &ostr) const
void SetDefault (const G4String &)
void SetDefault (const G4Colour &)
void Set (const G4String &particle, const G4String &colour)
void Set (const G4String &particle, const G4Colour &colour)
Public Member Functions inherited from G4VTrajectoryModel
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Private Attributes
G4ModelColourMap< G4String > fMap
G4Colour fDefault
Detailed Description
Definition at line 43 of file G4TrajectoryDrawByParticleID.hh.
View newest version in sPHENIX GitHub at line 43 of file G4TrajectoryDrawByParticleID.hh
Constructor & Destructor Documentation
G4TrajectoryDrawByParticleID::G4TrajectoryDrawByParticleID (const G4String & name = "Unspecified", G4VisTrajContext * context = 0)
Definition at line 34 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 34 of file G4TrajectoryDrawByParticleID.cc
References Set().
G4TrajectoryDrawByParticleID::~G4TrajectoryDrawByParticleID () virtual
Definition at line 47 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TrajectoryDrawByParticleID.cc
Member Function Documentation
void G4TrajectoryDrawByParticleID::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const virtual
Implements G4VTrajectoryModel.
Definition at line 50 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 50 of file G4TrajectoryDrawByParticleID.cc
References G4TrajectoryDrawerUtils::DrawLineAndPoints(), fDefault, fMap, G4cout, G4endl, G4ModelColourMap< T >::GetColour(), G4VTrajectoryModel::GetContext(), G4VTrajectory::GetParticleName(), G4VTrajectoryModel::GetVerbose(), G4VTrajectoryModel::Name(), particle, G4VisTrajContext::Print(), and G4VisTrajContext::SetLineColour().
void G4TrajectoryDrawByParticleID::Print (std::ostream & ostr) const virtual
Implements G4VTrajectoryModel.
Definition at line 107 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 107 of file G4TrajectoryDrawByParticleID.cc
References fDefault, fMap, G4cout, G4endl, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and G4ModelColourMap< T >::Print().
void G4TrajectoryDrawByParticleID::Set (const G4String & particle, const G4String & colour)
Definition at line 95 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 95 of file G4TrajectoryDrawByParticleID.cc
References fMap, and G4ModelColourMap< T >::Set().
Referenced by G4TrajectoryDrawByParticleID().
void G4TrajectoryDrawByParticleID::Set (const G4String & particle, const G4Colour & colour)
Definition at line 101 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 101 of file G4TrajectoryDrawByParticleID.cc
References fMap, and particle.
void G4TrajectoryDrawByParticleID::SetDefault (const G4String & colour)
Definition at line 72 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 72 of file G4TrajectoryDrawByParticleID.cc
References G4Exception(), G4Colour::GetColour(), JustWarning, and G4Colour::White().
void G4TrajectoryDrawByParticleID::SetDefault (const G4Colour & colour)
Definition at line 89 of file G4TrajectoryDrawByParticleID.cc.
View newest version in sPHENIX GitHub at line 89 of file G4TrajectoryDrawByParticleID.cc
References fDefault.
Member Data Documentation
G4Colour G4TrajectoryDrawByParticleID::fDefault private
Definition at line 69 of file G4TrajectoryDrawByParticleID.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TrajectoryDrawByParticleID.hh
Referenced by Draw(), Print(), and SetDefault().
G4ModelColourMap<G4String> G4TrajectoryDrawByParticleID::fMap private
Definition at line 68 of file G4TrajectoryDrawByParticleID.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrajectoryDrawByParticleID.hh
Referenced by Draw(), Print(), and Set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByParticleID.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryDrawByParticleID.cc