ECCE @ EIC Software: tbbTask Class Reference
tbbTask Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/tbbTask.hh>
Public Member Functions
tbbTask (G4int anId, tbb::concurrent_queue< const G4Run * > *output=0, G4int nEvts=1)
virtual ~tbbTask ()
tbb::task * execute ()
unsigned int GetSlotId ()
Private Attributes
G4int m_nEvents
G4int m_taskID
tbb::concurrent_queue< const
G4Run * > * m_output
G4bool m_beamOnCondition
Detailed Description
Definition at line 35 of file tbbTask.hh.
View newest version in sPHENIX GitHub at line 35 of file tbbTask.hh
Constructor & Destructor Documentation
tbbTask::tbbTask (G4int anId, tbb::concurrent_queue< const G4Run * > * output = 0, G4int nEvts = 1)
Definition at line 42 of file tbbTask.cc.
View newest version in sPHENIX GitHub at line 42 of file tbbTask.cc
tbbTask::~tbbTask () virtual
Definition at line 52 of file tbbTask.cc.
View newest version in sPHENIX GitHub at line 52 of file tbbTask.cc
Member Function Documentation
tbb::task * tbbTask::execute ()
Definition at line 61 of file tbbTask.cc.
View newest version in sPHENIX GitHub at line 61 of file tbbTask.cc
References G4UImanager::ApplyCommand(), G4VUserActionInitialization::Build(), G4WorkerThread::BuildGeometryAndPhysicsVector(), G4UserWorkerThreadInitialization::CreateWorkerRunManager(), G4cout, G4endl, G4Threading::G4SetThreadId(), G4ThreadLocal, G4MTRunManager::GetCommandStack(), G4MTRunManager::getMasterRandomEngine(), G4MTRunManager::GetMasterRunManager(), G4RunManager::GetNonConstUserActionInitialization(), G4RunManager::GetNumberOfSelectEvents(), G4RunManager::GetSelectMacro(), G4UImanager::GetUIpointer(), G4RunManager::GetUserActionInitialization(), G4RunManager::GetUserDetectorConstruction(), G4RunManager::GetUserPhysicsList(), G4RunManager::GetUserWorkerInitialization(), G4RunManager::GetUserWorkerThreadInitialization(), G4VUserActionInitialization::InitializeSteppingVerbose(), it, m_beamOnCondition, m_nEvents, m_output, G4VSteppingVerbose::SetInstance(), G4UImanager::SetUpForAThread(), G4UserWorkerThreadInitialization::SetupRNGEngine(), G4UserWorkerInitialization::WorkerInitialize(), and G4UserWorkerInitialization::WorkerStart().
unsigned int tbbTask::GetSlotId ()
Member Data Documentation
G4bool tbbTask::m_beamOnCondition private
Definition at line 46 of file tbbTask.hh.
View newest version in sPHENIX GitHub at line 46 of file tbbTask.hh
Referenced by execute().
G4int tbbTask::m_nEvents private
Definition at line 43 of file tbbTask.hh.
View newest version in sPHENIX GitHub at line 43 of file tbbTask.hh
Referenced by execute().
tbb::concurrent_queue<const G4Run*>* tbbTask::m_output private
Definition at line 45 of file tbbTask.hh.
View newest version in sPHENIX GitHub at line 45 of file tbbTask.hh
Referenced by execute().
G4int tbbTask::m_taskID private
Definition at line 44 of file tbbTask.hh.
View newest version in sPHENIX GitHub at line 44 of file tbbTask.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/tbbTask.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/src/tbbTask.cc