ECCE @ EIC Software: G4ParticleHPVector Class Reference
G4ParticleHPVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPVector.hh>
Public Member Functions
G4ParticleHPVector ()
G4ParticleHPVector (G4int n)
~G4ParticleHPVector ()
G4ParticleHPVector & operator= (const G4ParticleHPVector &right)
void SetVerbose (G4int ff)
void Times (G4double factor)
void SetPoint (G4int i, const G4ParticleHPDataPoint &it)
void SetData (G4int i, G4double x, G4double y)
void SetX (G4int i, G4double e)
void SetEnergy (G4int i, G4double e)
void SetY (G4int i, G4double x)
void SetXsec (G4int i, G4double x)
G4double GetEnergy (G4int i) const
G4double GetXsec (G4int i)
G4double GetX (G4int i) const
const G4ParticleHPDataPoint & GetPoint (G4int i) const
void Hash ()
void ReHash ()
G4double GetXsec (G4double e)
G4double GetXsec (G4double e, G4int min)
G4double GetY (G4double x)
G4int GetVectorLength () const
G4double GetY (G4int i)
G4double GetY (G4int i) const
void Dump ()
void InitInterpolation (std::istream &aDataFile)
void Init (std::istream &aDataFile, G4int total, G4double ux=1., G4double uy=1.)
void Init (std::istream &aDataFile, G4double ux=1., G4double uy=1.)
void ThinOut (G4double precision)
void SetLabel (G4double aLabel)
G4double GetLabel ()
void CleanUp ()
void Merge (G4ParticleHPVector *active, G4ParticleHPVector *passive)
void Merge (G4InterpolationScheme aScheme, G4double aValue, G4ParticleHPVector *active, G4ParticleHPVector *passive)
G4double SampleLin ()
G4double Sample ()
G4double * Debug ()
void IntegrateAndNormalise ()
void Integrate ()
G4double GetIntegral ()
void SetInterpolationManager (const G4InterpolationManager &aManager)
const G4InterpolationManager & GetInterpolationManager () const
void SetInterpolationManager (G4InterpolationManager &aMan)
void SetScheme (G4int aPoint, const G4InterpolationScheme &aScheme)
G4InterpolationScheme GetScheme (G4int anIndex)
G4double GetMeanX ()
std::vector< G4double > GetBlocked ()
std::vector< G4double > GetBuffered ()
G4double Get15percentBorder ()
G4double Get50percentBorder ()
Private Member Functions
void Check (G4int i)
G4bool IsBlocked (G4double aX)
Private Attributes
G4ParticleHPInterpolator theLin
G4double totalIntegral
G4ParticleHPDataPoint * theData
G4InterpolationManager theManager
G4double * theIntegral
G4int nEntries
G4int nPoints
G4double label
G4ParticleHPInterpolator theInt
G4int Verbose
G4int isFreed
G4ParticleHPHash theHash
G4double maxValue
std::vector< G4double > theBlocked
std::vector< G4double > theBuffered
G4double the15percentBorderCash
G4double the50percentBorderCash
Friends
G4ParticleHPVector & operator+ (G4ParticleHPVector &left, G4ParticleHPVector &right)
Detailed Description
Definition at line 56 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPVector.hh
Constructor & Destructor Documentation
G4ParticleHPVector::G4ParticleHPVector ()
Definition at line 83 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPVector.cc
References DBL_MAX, isFreed, label, maxValue, nEntries, nPoints, the15percentBorderCash, the50percentBorderCash, theData, theIntegral, totalIntegral, and Verbose.
G4ParticleHPVector::G4ParticleHPVector (G4int n)
Definition at line 98 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPVector.cc
References DBL_MAX, isFreed, label, max, maxValue, nEntries, nPoints, the15percentBorderCash, the50percentBorderCash, theData, theIntegral, totalIntegral, and Verbose.
G4ParticleHPVector::~G4ParticleHPVector ()
Definition at line 113 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPVector.cc
References G4ParticleHPHash::Clear(), isFreed, theData, theHash, and theIntegral.
Member Function Documentation
void G4ParticleHPVector::Check (G4int i) private
Definition at line 218 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 218 of file G4ParticleHPVector.cc
References nEntries, nPoints, and theData.
Referenced by SetData(), SetEnergy(), SetX(), SetXsec(), and SetY().
void G4ParticleHPVector::CleanUp () inline
Definition at line 261 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 261 of file G4ParticleHPVector.hh
References G4InterpolationManager::CleanUp(), G4ParticleHPHash::Clear(), DBL_MAX, maxValue, nEntries, theHash, theIntegral, and theManager.
Referenced by Merge().
G4double* G4ParticleHPVector::Debug () inline
Definition at line 368 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 368 of file G4ParticleHPVector.hh
References theIntegral.
void G4ParticleHPVector::Dump ()
Definition at line 205 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 205 of file G4ParticleHPVector.cc
References G4cout, G4endl, G4ParticleHPDataPoint::GetX(), G4ParticleHPDataPoint::GetY(), nEntries, and theData.
G4double G4ParticleHPVector::Get15percentBorder ()
Definition at line 479 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 479 of file G4ParticleHPVector.cc
References DBL_MAX, GetVectorLength(), G4ParticleHPDataPoint::GetX(), IntegrateAndNormalise(), min, the15percentBorderCash, theData, and theIntegral.
G4double G4ParticleHPVector::Get50percentBorder ()
Definition at line 507 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 507 of file G4ParticleHPVector.cc
References DBL_MAX, GetVectorLength(), G4ParticleHPDataPoint::GetX(), IntegrateAndNormalise(), it, G4ParticleHPInterpolator::Lin(), the50percentBorderCash, theData, theIntegral, theLin, x, x1, x2, y1, and y2.
std::vector<G4double> G4ParticleHPVector::GetBlocked () inline
Definition at line 538 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 538 of file G4ParticleHPVector.hh
References theBlocked.
std::vector<G4double> G4ParticleHPVector::GetBuffered () inline
Definition at line 539 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 539 of file G4ParticleHPVector.hh
References theBuffered.
G4double G4ParticleHPVector::GetEnergy (G4int i) const inline
Definition at line 125 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleHPVector.hh
References G4ParticleHPDataPoint::GetX(), and theData.
Referenced by G4ParticleHPChannel::DumpInfo(), G4ParticleHPElementData::Harmonise(), G4ParticleHPChannel::Harmonise(), G4ParticleHPArbitaryTab::Init(), and Merge().
G4double G4ParticleHPVector::GetIntegral () inline
Definition at line 477 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 477 of file G4ParticleHPVector.hh
References Integrate(), and totalIntegral.
Referenced by G4ParticleHPLabAngularEnergy::Sample().
const G4InterpolationManager& G4ParticleHPVector::GetInterpolationManager () const inline
Definition at line 488 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 488 of file G4ParticleHPVector.hh
References theManager.
Referenced by G4ParticleHPLabAngularEnergy::Sample().
G4double G4ParticleHPVector::GetLabel () inline
Definition at line 256 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 256 of file G4ParticleHPVector.hh
References label.
Referenced by Merge(), G4ParticleHPLabAngularEnergy::Sample(), and G4ParticleHPArbitaryTab::Sample().
G4double G4ParticleHPVector::GetMeanX () inline
Definition at line 508 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 508 of file G4ParticleHPVector.hh
References G4ParticleHPInterpolator::GetBinIntegral(), G4InterpolationManager::GetScheme(), G4ParticleHPInterpolator::GetWeightedBinIntegral(), G4ParticleHPDataPoint::GetX(), G4ParticleHPDataPoint::GetY(), nEntries, theData, theInt, and theManager.
Referenced by G4ParticleHPLabAngularEnergy::Sample().
const G4ParticleHPDataPoint& G4ParticleHPVector::GetPoint (G4int i) const inline
Definition at line 133 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ParticleHPVector.hh
References theData.
Referenced by G4ParticleHPIsoData::FillChannelData(), and operator=().
G4InterpolationScheme G4ParticleHPVector::GetScheme (G4int anIndex) inline
Definition at line 503 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 503 of file G4ParticleHPVector.hh
References G4InterpolationManager::GetScheme(), and theManager.
Referenced by Merge().
G4int G4ParticleHPVector::GetVectorLength () const inline
Definition at line 199 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 199 of file G4ParticleHPVector.hh
References nEntries.
Referenced by G4ParticleHPData::DoPhysicsVector(), G4ParticleHPChannel::DumpInfo(), G4ParticleHPIsoData::FillChannelData(), Get15percentBorder(), Get50percentBorder(), G4ParticleHPPhotonDist::GetPhotons(), GetX(), GetY(), G4ParticleHPElementData::Harmonise(), G4ParticleHPChannel::Harmonise(), G4ParticleHPArbitaryTab::Init(), Integrate(), IntegrateAndNormalise(), Merge(), operator+(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), Sample(), SampleLin(), and ThinOut().
G4double G4ParticleHPVector::GetX (G4int i) const inline
Definition at line 127 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ParticleHPVector.hh
References GetVectorLength(), G4ParticleHPDataPoint::GetX(), and theData.
Referenced by G4ParticleHPData::DoPhysicsVector(), G4ParticleHPPhotonDist::GetPhotons(), GetXsec(), Hash(), Integrate(), operator+(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), and Sample().
G4double G4ParticleHPVector::GetXsec (G4int i) inline
Definition at line 126 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPVector.hh
References G4ParticleHPDataPoint::GetY(), and theData.
Referenced by G4ParticleHPChannel::DumpInfo(), G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPIsoData::GetXsec(), G4ParticleHPChannel::GetXsec(), GetY(), G4ParticleHPElementData::Harmonise(), G4ParticleHPChannel::Harmonise(), and Merge().
G4double G4ParticleHPVector::GetXsec (G4double e)
Definition at line 149 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 149 of file G4ParticleHPVector.cc
References kdfinder::abs(), e, G4ParticleHPHash::GetMinIndex(), G4InterpolationManager::GetScheme(), G4ParticleHPDataPoint::GetX(), GetX(), G4ParticleHPDataPoint::GetY(), Hash(), G4ParticleHPInterpolator::Interpolate(), G4Threading::IsWorkerThread(), min, nEntries, G4ParticleHPHash::Prepared(), theData, theHash, theInt, theManager, and y.
G4double G4ParticleHPVector::GetXsec (G4double e, G4int min) inline
Definition at line 157 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleHPVector.hh
References e, G4InterpolationManager::GetScheme(), G4ParticleHPDataPoint::GetX(), GetX(), G4ParticleHPDataPoint::GetY(), G4ParticleHPInterpolator::Interpolate(), nEntries, theData, theInt, theManager, and y.
G4double G4ParticleHPVector::GetY (G4double x) inline
Definition at line 198 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 198 of file G4ParticleHPVector.hh
References GetXsec().
Referenced by G4ParticleHPData::DoPhysicsVector(), G4ParticleHPParticleYield::GetDelayed(), G4ParticleHPEvapSpectrum::GetFractionalProbability(), G4ParticleHPFissionSpectrum::GetFractionalProbability(), G4ParticleHPWattSpectrum::GetFractionalProbability(), G4ParticleHPSimpleEvapSpectrum::GetFractionalProbability(), G4ParticleHPMadlandNixSpectrum::GetFractionalProbability(), G4ParticleHPArbitaryTab::GetFractionalProbability(), G4ParticleHPParticleYield::GetMean(), G4ParticleHPProduct::GetMeanYield(), G4ParticleHPProduct::GetMultiplicity(), G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPParticleYield::GetPrompt(), G4ParticleHPFissionBaseFS::GetXsec(), G4ParticleHPInelasticBaseFS::GetXsec(), Hash(), operator+(), G4ParticleHPEvapSpectrum::Sample(), G4ParticleHPFissionSpectrum::Sample(), G4ParticleHPWattSpectrum::Sample(), G4ParticleHPSimpleEvapSpectrum::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPMadlandNixSpectrum::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), Sample(), ThinOut(), and Times().
G4double G4ParticleHPVector::GetY (G4int i) inline
Definition at line 201 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 201 of file G4ParticleHPVector.hh
References GetVectorLength(), G4ParticleHPDataPoint::GetY(), and theData.
G4double G4ParticleHPVector::GetY (G4int i) const inline
Definition at line 208 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 208 of file G4ParticleHPVector.hh
References GetVectorLength(), G4ParticleHPDataPoint::GetY(), and theData.
void G4ParticleHPVector::Hash () inline
Definition at line 135 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ParticleHPVector.hh
References GetX(), GetY(), nEntries, G4ParticleHPHash::SetData(), theHash, x, and y.
Referenced by G4ParticleHPIsoData::FillChannelData(), GetXsec(), G4ParticleHPProduct::Init(), G4ParticleHPChannel::Register(), and ReHash().
void G4ParticleHPVector::Init (std::istream & aDataFile, G4int total, G4double ux = 1., G4double uy = 1.) inline
Definition at line 221 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 221 of file G4ParticleHPVector.hh
References nEntries, SetData(), G4ParticleHPHash::SetData(), theHash, G4INCL::CrossSections::total(), ux, uy, x, and y.
Referenced by G4ParticleHPEvapSpectrum::Init(), G4ParticleHPWattSpectrum::Init(), G4ParticleHPFissionSpectrum::Init(), G4ParticleHPSimpleEvapSpectrum::Init(), G4ParticleHPArbitaryTab::Init(), G4ParticleHPMadlandNixSpectrum::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPLabAngularEnergy::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4ParticleHPProduct::Init(), Init(), G4ParticleHPParticleYield::InitDelayed(), G4ParticleHPPhotonDist::InitEnergies(), G4ParticleHPParticleYield::InitMean(), G4ParticleHPPhotonDist::InitMean(), G4ParticleHPPhotonDist::InitPartials(), G4ParticleHPParticleYield::InitPrompt(), and G4ParticleHPThermalScatteringData::readData().
void G4ParticleHPVector::Init (std::istream & aDataFile, G4double ux = 1., G4double uy = 1.) inline
Definition at line 237 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 237 of file G4ParticleHPVector.hh
References G4InterpolationManager::Init(), Init(), nEntries, nPoints, theData, theManager, G4INCL::CrossSections::total(), ux, and uy.
void G4ParticleHPVector::InitInterpolation (std::istream & aDataFile) inline
Definition at line 216 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 216 of file G4ParticleHPVector.hh
References G4InterpolationManager::Init(), and theManager.
void G4ParticleHPVector::Integrate () inline
Definition at line 423 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 423 of file G4ParticleHPVector.hh
References a, kdfinder::abs(), b, CHISTO, CLINLIN, CLINLOG, CLOGLIN, CLOGLOG, G4Exp(), G4Log(), G4Pow::GetInstance(), G4InterpolationManager::GetScheme(), GetVectorLength(), G4ParticleHPDataPoint::GetX(), GetX(), G4ParticleHPDataPoint::GetY(), HISTO, LINLIN, LINLOG, LOGLIN, LOGLOG, nEntries, G4Pow::powA(), sum, theData, theManager, totalIntegral, UHISTO, ULINLIN, ULINLOG, ULOGLIN, ULOGLOG, x1, x2, y1, and y2.
Referenced by GetIntegral().
void G4ParticleHPVector::IntegrateAndNormalise () inline
Definition at line 373 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 373 of file G4ParticleHPVector.hh
References kdfinder::abs(), G4ParticleHPInterpolator::GetBinIntegral(), G4InterpolationManager::GetScheme(), GetVectorLength(), G4ParticleHPDataPoint::GetX(), G4ParticleHPDataPoint::GetY(), nEntries, sum, theData, theInt, theIntegral, theManager, G4INCL::CrossSections::total(), x1, and y1.
Referenced by Get15percentBorder(), Get50percentBorder(), G4ParticleHPArbitaryTab::Init(), Sample(), and SampleLin().
G4bool G4ParticleHPVector::IsBlocked (G4double aX) private
Definition at line 355 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 355 of file G4ParticleHPVector.cc
References kdfinder::abs(), MeV, and theBlocked.
Referenced by Sample().
void G4ParticleHPVector::Merge (G4ParticleHPVector * active, G4ParticleHPVector * passive) inline
Definition at line 273 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 273 of file G4ParticleHPVector.hh
References a, kdfinder::abs(), active, G4InterpolationManager::AppendScheme(), CleanUp(), GetEnergy(), GetScheme(), GetVectorLength(), GetXsec(), n, Acts::passive, SetData(), t, theManager, and tmp.
Referenced by G4ParticleHPLabAngularEnergy::Sample(), and G4ParticleHPDiscreteTwoBody::Sample().
void G4ParticleHPVector::Merge (G4InterpolationScheme aScheme, G4double aValue, G4ParticleHPVector * active, G4ParticleHPVector * passive)
Definition at line 233 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 233 of file G4ParticleHPVector.cc
References a, kdfinder::abs(), active, G4InterpolationManager::AppendScheme(), CleanUp(), GetEnergy(), GetLabel(), GetScheme(), GetVectorLength(), GetXsec(), G4ParticleHPInterpolator::Interpolate(), n, Acts::passive, G4ParticleHPHash::Prepared(), ReHash(), SetData(), t, theHash, theInt, theManager, and tmp.
G4ParticleHPVector & G4ParticleHPVector::operator= (const G4ParticleHPVector & right)
Definition at line 125 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleHPVector.cc
References GetPoint(), label, nEntries, SetPoint(), the15percentBorderCash, the50percentBorderCash, theHash, theIntegral, theManager, totalIntegral, and Verbose.
void G4ParticleHPVector::ReHash () inline
Definition at line 150 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParticleHPVector.hh
References G4ParticleHPHash::Clear(), Hash(), and theHash.
Referenced by Merge(), and ThinOut().
G4double G4ParticleHPVector::Sample ()
Definition at line 372 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 372 of file G4ParticleHPVector.cc
References G4cout, G4endl, G4UniformRand, GetVectorLength(), G4ParticleHPDataPoint::GetX(), GetX(), G4ParticleHPDataPoint::GetY(), GetY(), IntegrateAndNormalise(), IsBlocked(), max, SetY(), test(), theBuffered, theData, theIntegral, x1, x2, y1, and y2.
Referenced by G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPEvapSpectrum::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPArbitaryTab::Sample(), and G4ParticleHPPartial::Sample().
G4double G4ParticleHPVector::SampleLin () inline
Definition at line 324 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 324 of file G4ParticleHPVector.hh
References kdfinder::abs(), G4UniformRand, GetVectorLength(), G4ParticleHPDataPoint::GetX(), IntegrateAndNormalise(), G4ParticleHPInterpolator::Lin(), theData, theIntegral, theLin, x1, x2, y1, and y2.
void G4ParticleHPVector::SetData (G4int i, G4double x, G4double y) inline
Definition at line 96 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPVector.hh
References Check(), maxValue, G4ParticleHPDataPoint::SetData(), theData, and y.
Referenced by G4ParticleHPPartial::GetY(), G4ParticleHPElementData::Harmonise(), G4ParticleHPChannel::Harmonise(), Init(), Merge(), operator+(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPLegendreStore::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), and SetPoint().
void G4ParticleHPVector::SetEnergy (G4int i, G4double e) inline
Definition at line 108 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPVector.hh
References Check(), G4ParticleHPDataPoint::SetX(), and theData.
void G4ParticleHPVector::SetInterpolationManager (const G4InterpolationManager & aManager) inline
Definition at line 483 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 483 of file G4ParticleHPVector.hh
References theManager.
Referenced by G4ParticleHPPartial::GetY(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), and G4ParticleHPPartial::Sample().
void G4ParticleHPVector::SetInterpolationManager (G4InterpolationManager & aMan) inline
Definition at line 493 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 493 of file G4ParticleHPVector.hh
References theManager.
void G4ParticleHPVector::SetLabel (G4double aLabel) inline
Definition at line 251 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 251 of file G4ParticleHPVector.hh
References label.
Referenced by G4ParticleHPArbitaryTab::Init(), and G4ParticleHPLabAngularEnergy::Init().
void G4ParticleHPVector::SetPoint (G4int i, const G4ParticleHPDataPoint & it) inline
Definition at line 89 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPVector.hh
References G4ParticleHPDataPoint::GetX(), G4ParticleHPDataPoint::GetY(), SetData(), x, and y.
Referenced by G4ParticleHPIsoData::FillChannelData(), and operator=().
void G4ParticleHPVector::SetScheme (G4int aPoint, const G4InterpolationScheme & aScheme) inline
Definition at line 498 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 498 of file G4ParticleHPVector.hh
References G4InterpolationManager::AppendScheme(), and theManager.
Referenced by G4ParticleHPPartial::GetY(), and G4ParticleHPPartial::Sample().
void G4ParticleHPVector::SetVerbose (G4int ff) inline
Definition at line 71 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPVector.hh
References ff, and Verbose.
void G4ParticleHPVector::SetX (G4int i, G4double e) inline
Definition at line 103 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPVector.hh
References Check(), G4ParticleHPDataPoint::SetX(), and theData.
Referenced by G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), and G4ParticleHPPartial::Sample().
void G4ParticleHPVector::SetXsec (G4int i, G4double x) inline
Definition at line 119 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ParticleHPVector.hh
References Check(), maxValue, G4ParticleHPDataPoint::SetY(), theData, and x.
void G4ParticleHPVector::SetY (G4int i, G4double x) inline
Definition at line 113 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPVector.hh
References Check(), maxValue, G4ParticleHPDataPoint::SetY(), theData, and x.
Referenced by G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPPartial::Sample(), and Sample().
void G4ParticleHPVector::ThinOut (G4double precision)
Definition at line 296 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 296 of file G4ParticleHPVector.cc
References kdfinder::abs(), GetVectorLength(), G4ParticleHPDataPoint::GetX(), G4ParticleHPDataPoint::GetY(), GetY(), G4ParticleHPInterpolator::Lin(), nEntries, nPoints, G4ParticleHPHash::Prepared(), ReHash(), start(), theData, theHash, theInt, x, x1, x2, y, y1, and y2.
Referenced by G4ParticleHPElementData::Init(), operator+(), and G4ParticleHPIsoData::ThinOut().
void G4ParticleHPVector::Times (G4double factor) inline
Definition at line 76 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPVector.hh
References GetY(), nEntries, G4ParticleHPDataPoint::SetY(), theData, and theIntegral.
Referenced by G4ParticleHPChannel::UpdateData().
Friends And Related Function Documentation
G4ParticleHPVector& operator+ (G4ParticleHPVector & left, G4ParticleHPVector & right) friend
Definition at line 40 of file G4ParticleHPVector.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPVector.cc
Member Data Documentation
G4int G4ParticleHPVector::isFreed private
Definition at line 571 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 571 of file G4ParticleHPVector.hh
Referenced by G4ParticleHPVector(), and ~G4ParticleHPVector().
G4double G4ParticleHPVector::label private
Definition at line 566 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 566 of file G4ParticleHPVector.hh
Referenced by G4ParticleHPVector(), GetLabel(), operator=(), and SetLabel().
G4double G4ParticleHPVector::maxValue private
Definition at line 574 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 574 of file G4ParticleHPVector.hh
Referenced by CleanUp(), G4ParticleHPVector(), SetData(), SetXsec(), and SetY().
G4int G4ParticleHPVector::nEntries private
Definition at line 564 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 564 of file G4ParticleHPVector.hh
Referenced by Check(), CleanUp(), Dump(), G4ParticleHPVector(), GetMeanX(), GetVectorLength(), GetXsec(), Hash(), Init(), Integrate(), IntegrateAndNormalise(), operator=(), ThinOut(), and Times().
G4int G4ParticleHPVector::nPoints private
Definition at line 565 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 565 of file G4ParticleHPVector.hh
Referenced by Check(), G4ParticleHPVector(), Init(), and ThinOut().
G4double G4ParticleHPVector::the15percentBorderCash private
Definition at line 578 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 578 of file G4ParticleHPVector.hh
Referenced by G4ParticleHPVector(), Get15percentBorder(), and operator=().
G4double G4ParticleHPVector::the50percentBorderCash private
Definition at line 579 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 579 of file G4ParticleHPVector.hh
Referenced by G4ParticleHPVector(), Get50percentBorder(), and operator=().
std::vector<G4double> G4ParticleHPVector::theBlocked private
Definition at line 576 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 576 of file G4ParticleHPVector.hh
Referenced by GetBlocked(), and IsBlocked().
std::vector<G4double> G4ParticleHPVector::theBuffered private
Definition at line 577 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 577 of file G4ParticleHPVector.hh
Referenced by GetBuffered(), and Sample().
G4ParticleHPDataPoint* G4ParticleHPVector::theData private
Definition at line 561 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 561 of file G4ParticleHPVector.hh
Referenced by Check(), Dump(), G4ParticleHPVector(), Get15percentBorder(), Get50percentBorder(), GetEnergy(), GetMeanX(), GetPoint(), GetX(), GetXsec(), GetY(), Init(), Integrate(), IntegrateAndNormalise(), Sample(), SampleLin(), SetData(), SetEnergy(), SetX(), SetXsec(), SetY(), ThinOut(), Times(), and ~G4ParticleHPVector().
G4ParticleHPHash G4ParticleHPVector::theHash private
Definition at line 573 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 573 of file G4ParticleHPVector.hh
Referenced by CleanUp(), GetXsec(), Hash(), Init(), Merge(), operator=(), ReHash(), ThinOut(), and ~G4ParticleHPVector().
G4ParticleHPInterpolator G4ParticleHPVector::theInt private
Definition at line 568 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 568 of file G4ParticleHPVector.hh
Referenced by GetMeanX(), GetXsec(), IntegrateAndNormalise(), Merge(), and ThinOut().
G4double* G4ParticleHPVector::theIntegral private
Definition at line 563 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 563 of file G4ParticleHPVector.hh
Referenced by CleanUp(), Debug(), G4ParticleHPVector(), Get15percentBorder(), Get50percentBorder(), IntegrateAndNormalise(), operator=(), Sample(), SampleLin(), Times(), and ~G4ParticleHPVector().
G4ParticleHPInterpolator G4ParticleHPVector::theLin private
Definition at line 555 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 555 of file G4ParticleHPVector.hh
Referenced by Get50percentBorder(), and SampleLin().
G4InterpolationManager G4ParticleHPVector::theManager private
Definition at line 562 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 562 of file G4ParticleHPVector.hh
Referenced by CleanUp(), GetInterpolationManager(), GetMeanX(), GetScheme(), GetXsec(), Init(), InitInterpolation(), Integrate(), IntegrateAndNormalise(), Merge(), operator=(), SetInterpolationManager(), and SetScheme().
G4double G4ParticleHPVector::totalIntegral private
Definition at line 559 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 559 of file G4ParticleHPVector.hh
Referenced by G4ParticleHPVector(), GetIntegral(), Integrate(), and operator=().
G4int G4ParticleHPVector::Verbose private
Definition at line 569 of file G4ParticleHPVector.hh.
View newest version in sPHENIX GitHub at line 569 of file G4ParticleHPVector.hh
Referenced by G4ParticleHPVector(), operator=(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPVector.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPVector.cc