ECCE @ EIC Software: G4VisAttributes Class Reference
G4VisAttributes Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VisAttributes.hh>
Public Types
enum LineStyle { unbroken, dashed, dotted }
enum ForcedDrawingStyle { wireframe, solid, cloud }
Public Member Functions
G4VisAttributes ()
G4VisAttributes (G4bool visibility)
G4VisAttributes (const G4Colour &colour)
G4VisAttributes (G4bool visibility, const G4Colour &colour)
G4VisAttributes (const G4VisAttributes &)
~G4VisAttributes ()
G4VisAttributes & operator= (const G4VisAttributes &)
G4bool operator!= (const G4VisAttributes &a) const
G4bool operator== (const G4VisAttributes &a) const
void SetVisibility (G4bool=true)
void SetDaughtersInvisible (G4bool=true)
void SetColour (const G4Colour &)
void SetColor (const G4Color &)
void SetColour (G4double red, G4double green, G4double blue, G4double alpha=1.)
void SetColor (G4double red, G4double green, G4double blue, G4double alpha=1.)
void SetLineStyle (LineStyle)
void SetLineWidth (G4double)
void SetForceWireframe (G4bool=true)
void SetForceSolid (G4bool=true)
void SetForceCloud (G4bool=true)
void SetForceNumberOfCloudPoints (G4int nPoints)
void SetForceAuxEdgeVisible (G4bool=true)
void SetForceLineSegmentsPerCircle (G4int nSegments)
void SetStartTime (G4double)
void SetEndTime (G4double)
void SetAttValues (const std::vector< G4AttValue > *)
void SetAttDefs (const std::map< G4String, G4AttDef > *)
G4bool IsVisible () const
G4bool IsDaughtersInvisible () const
const G4Colour & GetColour () const
const G4Color & GetColor () const
LineStyle GetLineStyle () const
G4double GetLineWidth () const
G4bool IsForceDrawingStyle () const
ForcedDrawingStyle GetForcedDrawingStyle () const
G4int GetForcedNumberOfCloudPoints () const
G4bool IsForceAuxEdgeVisible () const
G4bool IsForcedAuxEdgeVisible () const
G4bool IsForceLineSegmentsPerCircle () const
G4int GetForcedLineSegmentsPerCircle () const
G4double GetStartTime () const
G4double GetEndTime () const
const std::vector< G4AttValue > * CreateAttValues () const
const std::map< G4String,
G4AttDef > * GetAttDefs () const
Static Public Member Functions
static const G4VisAttributes & GetInvisible ()
static G4int GetMinLineSegmentsPerCircle ()
Static Public Attributes
static const G4VisAttributes Invisible = G4VisAttributes (false)
static constexpr G4int fMinLineSegmentsPerCircle = 3
static constexpr G4double fVeryLongTime = 1.e100 * CLHEP::ns
Private Attributes
G4bool fVisible
G4bool fDaughtersInvisible
G4Colour fColour
LineStyle fLineStyle
G4double fLineWidth
G4bool fForceDrawingStyle
ForcedDrawingStyle fForcedStyle
G4int fForcedNumberOfCloudPoints
G4bool fForceAuxEdgeVisible
G4bool fForcedAuxEdgeVisible
G4int fForcedLineSegmentsPerCircle
G4double fStartTime
G4double fEndTime
const std::vector< G4AttValue > * fAttValues
const std::map< G4String,
G4AttDef > * fAttDefs
Friends
std::ostream & operator<< (std::ostream &os, const G4VisAttributes &a)
Detailed Description
Definition at line 69 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VisAttributes.hh
Member Enumeration Documentation
enum G4VisAttributes::ForcedDrawingStyle
Enumerator:
wireframe
solid
cloud
Definition at line 76 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VisAttributes.hh
enum G4VisAttributes::LineStyle
Enumerator:
unbroken
dashed
dotted
Definition at line 75 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VisAttributes.hh
Constructor & Destructor Documentation
G4VisAttributes::G4VisAttributes ()
Definition at line 36 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VisAttributes.cc
Referenced by GetInvisible().
G4VisAttributes::G4VisAttributes (G4bool visibility)
Definition at line 54 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VisAttributes.cc
G4VisAttributes::G4VisAttributes (const G4Colour & colour)
Definition at line 72 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VisAttributes.cc
G4VisAttributes::G4VisAttributes (G4bool visibility, const G4Colour & colour)
Definition at line 90 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 90 of file G4VisAttributes.cc
G4VisAttributes::G4VisAttributes (const G4VisAttributes & va)
Definition at line 109 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 109 of file G4VisAttributes.cc
G4VisAttributes::~G4VisAttributes ()
Definition at line 132 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 132 of file G4VisAttributes.cc
Member Function Documentation
const std::vector< G4AttValue > * G4VisAttributes::CreateAttValues () const
Definition at line 225 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 225 of file G4VisAttributes.cc
Referenced by G4VSceneHandler::LoadAtts(), and G4XXXStoredSceneHandler::PreAddSolid().
const std::map<G4String,G4AttDef>* G4VisAttributes::GetAttDefs () const
Referenced by G4VSceneHandler::LoadAtts(), and G4XXXStoredSceneHandler::PreAddSolid().
const G4Color& G4VisAttributes::GetColor () const
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4GMocrenFileSceneHandler::AddPrimitive(), G03ColorWriter::ColorWrite(), and export_G4VisAttributes().
const G4Colour& G4VisAttributes::GetColour () const
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4RTRun::Attenuate(), G4TheRayTracer::Attenuate(), G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), G4RTRun::GetSurfaceColour(), G4TheRayTracer::GetSurfaceColour(), operator<<(), G4VisCommandsViewerSet::SetNewValue(), G4ViewParameters::TouchableCommands(), and G4RTSteppingAction::UserSteppingAction().
G4double G4VisAttributes::GetEndTime () const
G4VisAttributes::ForcedDrawingStyle G4VisAttributes::GetForcedDrawingStyle () const
Definition at line 215 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 215 of file G4VisAttributes.cc
References fForceDrawingStyle, fForcedStyle, and wireframe.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), G4ViewParameters::TouchableCommands(), G4RTSteppingAction::UserSteppingAction(), G4RTRun::ValidColour(), and G4TheRayTracer::ValidColour().
G4int G4VisAttributes::GetForcedLineSegmentsPerCircle () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), G4PhysicalVolumeModel::DescribeSolid(), G4VSceneHandler::GetNoOfSides(), operator<<(), and G4ViewParameters::TouchableCommands().
G4int G4VisAttributes::GetForcedNumberOfCloudPoints () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), operator<<(), and G4ViewParameters::TouchableCommands().
const G4VisAttributes & G4VisAttributes::GetInvisible () static
Definition at line 166 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 166 of file G4VisAttributes.cc
References G4VisAttributes().
Referenced by EICG4LumiDetector::AddCAL(), EICG4LumiDetector::AddLumiMag_MagCore(), UltraFresnelLens::BuildLens(), HadrontherapyModulator::BuildSteps(), G4MIRDRibCage::Construct(), Par01DetectorConstruction::Construct(), RE05DetectorConstruction::Construct(), GeometryConstruction::Construct(), ExGflash2DetectorConstruction::Construct(), B3DetectorConstruction::Construct(), ExGflash1DetectorConstruction::Construct(), ExGflash3DetectorConstruction::Construct(), FCALCryostatVolumes::Construct(), FCALEMModule::Construct(), ExUCNDetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), LXeDetectorConstruction::Construct(), FCALTestbeamSetup::Construct(), XrayTelDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), RE02DetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), GammaKnifeDetectorConstruction::ConstructBeamLine(), DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), Collimator100BeamLine::ConstructCollimator100BeamLine(), Collimator40BeamLine::ConstructCollimator40BeamLine(), Collimator50BeamLine::ConstructCollimator50BeamLine(), Collimator60BeamLine::ConstructCollimator60BeamLine(), Collimator70BeamLine::ConstructCollimator70BeamLine(), Collimator80BeamLine::ConstructCollimator80BeamLine(), LaserDrivenBeamLine::ConstructLaserDrivenBeamLine(), PassiveCarbonBeamLine::ConstructPassiveCarbonBeamLine(), GammaRayTelDetectorConstruction::ConstructPayload(), DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), BrachyDetectorConstruction::ConstructPhantom(), XrayTelDetectorConstruction::ConstructTelescope(), TrentoPassiveProtonBeamLine::ConstructTrentoPassiveProtonBeamLine(), G4HumanPhantomConstruction::ConstructWorld(), B4dDetectorConstruction::DefineVolumes(), B4cDetectorConstruction::DefineVolumes(), B4DetectorConstruction::DefineVolumes(), export_G4VisAttributes(), LaserDrivenBeamLine::FaradayCup(), G4BuildGeom(), F04ElementField::GetVisAttribute(), G4GDMLReadStructure::GetWorldVolume(), PassiveCarbonBeamLine::HadrontherapyRippleFilter(), EICG4LumiDetector::MakeTower(), XDetectorConstruction::SetupGeometry(), RE04DetectorConstruction::SetupGeometry(), GB03DetectorConstruction::SetupGeometry(), RE06DetectorConstruction::SetupGeometry(), and G3toG4DetectorConstruction::SimpleConstruct().
LineStyle G4VisAttributes::GetLineStyle () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), G4HepRepSceneHandler::setLine(), and G4ViewParameters::TouchableCommands().
G4double G4VisAttributes::GetLineWidth () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), G4VSceneHandler::GetLineWidth(), operator<<(), G4HepRepSceneHandler::setLine(), and G4ViewParameters::TouchableCommands().
static G4int G4VisAttributes::GetMinLineSegmentsPerCircle () static
Referenced by G4VSceneHandler::GetNoOfSides(), operator<<(), G4ModelingParameters::SetNoOfSides(), and G4ViewParameters::SetNoOfSides().
G4double G4VisAttributes::GetStartTime () const
G4bool G4VisAttributes::IsDaughtersInvisible () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), and G4ViewParameters::TouchableCommands().
G4bool G4VisAttributes::IsForceAuxEdgeVisible () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), and G4ViewParameters::TouchableCommands().
G4bool G4VisAttributes::IsForcedAuxEdgeVisible () const
Definition at line 220 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 220 of file G4VisAttributes.cc
References fForceAuxEdgeVisible, and fForcedAuxEdgeVisible.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), G4VSceneHandler::GetAuxEdgeVisible(), operator<<(), and G4ViewParameters::TouchableCommands().
G4bool G4VisAttributes::IsForceDrawingStyle () const
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), operator<<(), G4ViewParameters::TouchableCommands(), G4RTSteppingAction::UserSteppingAction(), G4RTRun::ValidColour(), and G4TheRayTracer::ValidColour().
G4bool G4VisAttributes::IsForceLineSegmentsPerCircle () const
Referenced by G4PhysicalVolumeModel::DescribeSolid(), and G4VSceneHandler::GetNoOfSides().
G4bool G4VisAttributes::IsVisible () const
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4PhysicalVolumeModel::DescribeAndDescend(), G4HepRepSceneHandler::dontWrite(), export_G4VisAttributes(), G4GMocrenFileSceneHandler::IsVisible(), operator<<(), G4HepRepSceneHandler::setVisibility(), G4ViewParameters::TouchableCommands(), G4RTSteppingAction::UserSteppingAction(), G4RTRun::ValidColour(), and G4TheRayTracer::ValidColour().
G4bool G4VisAttributes::operator!= (const G4VisAttributes & a) const
Definition at line 304 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 304 of file G4VisAttributes.cc
References fAttDefs, fAttValues, fColour, fDaughtersInvisible, fEndTime, fForceAuxEdgeVisible, fForcedAuxEdgeVisible, fForcedLineSegmentsPerCircle, fForceDrawingStyle, fForcedStyle, fLineStyle, fLineWidth, fStartTime, and fVisible.
Referenced by operator==().
G4VisAttributes & G4VisAttributes::operator= (const G4VisAttributes & rhs)
Definition at line 135 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 135 of file G4VisAttributes.cc
References fAttDefs, fAttValues, fColour, fDaughtersInvisible, fEndTime, fForceAuxEdgeVisible, fForcedAuxEdgeVisible, fForcedLineSegmentsPerCircle, fForcedNumberOfCloudPoints, fForceDrawingStyle, fForcedStyle, fLineStyle, fLineWidth, fStartTime, and fVisible.
G4bool G4VisAttributes::operator== (const G4VisAttributes & a) const
Definition at line 333 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 333 of file G4VisAttributes.cc
References operator!=().
void G4VisAttributes::SetAttDefs (const std::map< G4String, G4AttDef > *)
Referenced by export_G4VisAttributes().
void G4VisAttributes::SetAttValues (const std::vector< G4AttValue > *)
Referenced by export_G4VisAttributes().
void G4VisAttributes::SetColor (const G4Color &)
Referenced by PHG4InnerHcalDisplayAction::ApplyDisplayAction(), PHG4OuterHcalDisplayAction::ApplyDisplayAction(), PHG4TpcDisplayAction::ApplyDisplayAction(), G4LBLVtxDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), eRositaDetectorConstruction::Construct(), PHG4ECAPToFDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), EICG4BwdDetector::ConstructMe(), and EICG4B0ECALDetector::ConstructMe().
void G4VisAttributes::SetColor (G4double red, G4double green, G4double blue, G4double alpha = 1.)
void G4VisAttributes::SetColour (const G4Colour &)
Referenced by BeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4BbcDisplayAction::ApplyDisplayAction(), PHG4MvtxDisplayAction::ApplyDisplayAction(), G4JLeicBeamLineMagnetDisplayAction::ApplyDisplayAction(), G4JLeicDIRCDisplayAction::ApplyDisplayAction(), G4JLeicVTXDisplayAction::ApplyDisplayAction(), AllSi_Al_support_DisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), AllSiliconTrackerDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), BeastMagnetDisplayAction::ApplyDisplayAction(), PHG4ForwardDualReadoutDisplayAction::ApplyDisplayAction(), PHG4BarrelEcalDisplayAction::ApplyDisplayAction(), PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4CrystalCalorimeterDisplayAction::ApplyDisplayAction(), PHG4ZDCDisplayAction::ApplyDisplayAction(), PHG4HybridHomogeneousCalorimeterDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4EPDDisplayAction::ApplyDisplayAction(), PHG4InttDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), PHG4BackwardHcalDisplayAction::ApplyDisplayAction(), PHG4ForwardEcalDisplayAction::ApplyDisplayAction(), PHG4ForwardHcalDisplayAction::ApplyDisplayAction(), PHG4LFHcalDisplayAction::ApplyDisplayAction(), G4EicDircDisplayAction::ApplyDisplayAction(), G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D(), G4ViewParameters::CatmullRomCubicSplineInterpolation(), CellParameterisation::CellParameterisation(), G4tgbVolume::ConstructG4LogVol(), PHG4TRDDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4ECAPToFDetector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructSandwichVolume(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), G4PhysicalVolumeModel::DescribeAndDescend(), G4GPSModel::DescribeYourselfTo(), PHG4Detector::DisplayVolume(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), ExN04CalorimeterHit::Draw(), RE01CalorimeterHit::Draw(), ExGflashHit::Draw(), RE05CalorimeterHit::Draw(), Par01CalorimeterHit::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), G4ArrowModel::G4ArrowModel(), G4DrawVoxels::G4DrawVoxels(), G4VisCommandSceneAddLine::Line::Line(), G4VisCommandSceneAddLine2D::Line2D::Line2D(), G4VisCommandSceneAddFrame::Frame::operator()(), PHG4Utils::SetColour(), PHG4GDMLDetector::SetDisplayProperty(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4EicDircDetector::SetVisualization(), NeuronLoadDataFile::SingleNeuronSWCfile(), and G4VViewer::TouchableSetColour().
void G4VisAttributes::SetColour (G4double red, G4double green, G4double blue, G4double alpha = 1.)
void G4VisAttributes::SetDaughtersInvisible (G4bool = true)
Referenced by DetectorConstruction::ConstructLine(), G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), F04ElementField::GetVisAttribute(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetEndTime (G4double)
Referenced by XAluminumElectrodeHit::Draw().
void G4VisAttributes::SetForceAuxEdgeVisible (G4bool visibility = true)
Definition at line 209 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 209 of file G4VisAttributes.cc
References fForceAuxEdgeVisible, fForcedAuxEdgeVisible, and visibility().
Referenced by G4VSceneHandler::AddSolidWithAuxiliaryEdges(), G4PhysicalVolumeModel::DescribeAndDescend(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), export_G4VisAttributes(), EICG4LumiDetector::MakeTower(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetForceCloud (G4bool force = true)
Definition at line 189 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 189 of file G4VisAttributes.cc
References cloud, fForceDrawingStyle, and fForcedStyle.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetForceLineSegmentsPerCircle (G4int nSegments)
Definition at line 230 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 230 of file G4VisAttributes.cc
References fForcedLineSegmentsPerCircle, fMinLineSegmentsPerCircle, G4cout, and G4endl.
Referenced by PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), PHG4CylinderStripDetector::ConstructMe(), G4PhysicalVolumeModel::DescribeAndDescend(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetForceNumberOfCloudPoints (G4int nPoints)
Definition at line 198 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 198 of file G4VisAttributes.cc
References fForcedNumberOfCloudPoints, G4cout, and G4endl.
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetForceSolid (G4bool force = true)
Definition at line 180 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 180 of file G4VisAttributes.cc
References fForceDrawingStyle, fForcedStyle, and solid.
Referenced by EICG4LumiDetector::AddCuboid(), AllSi_Al_support_Detector::addDetectorSection(), EicFRichDetector::addDetectorSection(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), EICG4LumiDetector::AddLumiExitWindow(), EICG4LumiDetector::AddLumiMag_OuterVessel(), EICG4LumiDetector::AddLumiTracker(), EICG4LumiDetector::AddLumiWindow(), EICG4LumiDetector::AddRecCone(), EICG4LumiDetector::AddTriangularTrapezoid(), PHG4BbcDisplayAction::ApplyDisplayAction(), PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4BarrelEcalDisplayAction::ApplyDisplayAction(), PHG4CrystalCalorimeterDisplayAction::ApplyDisplayAction(), PHG4ZDCDisplayAction::ApplyDisplayAction(), PHG4EPDDisplayAction::ApplyDisplayAction(), PHG4InttDisplayAction::ApplyDisplayAction(), PHG4HybridHomogeneousCalorimeterDisplayAction::ApplyDisplayAction(), PHG4MvtxDisplayAction::ApplyDisplayAction(), G4JLeicBeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4TpcDisplayAction::ApplyDisplayAction(), G4JLeicDIRCDisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), G4JLeicVTXDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), AllSi_Al_support_DisplayAction::ApplyDisplayAction(), PHG4InnerHcalDisplayAction::ApplyDisplayAction(), AllSiliconTrackerDisplayAction::ApplyDisplayAction(), PHG4OuterHcalDisplayAction::ApplyDisplayAction(), G4LBLVtxDisplayAction::ApplyDisplayAction(), BeastMagnetDisplayAction::ApplyDisplayAction(), BeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4ForwardDualReadoutDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), PHG4ForwardEcalDisplayAction::ApplyDisplayAction(), PHG4ForwardHcalDisplayAction::ApplyDisplayAction(), PHG4LFHcalDisplayAction::ApplyDisplayAction(), G4EicDircDisplayAction::ApplyDisplayAction(), PHG4BackwardHcalDisplayAction::ApplyDisplayAction(), DetectorConstruction::AtomisticView(), DetectorConstruction::BarycenterView(), PHG4mRICHDetector::build_lens(), G4MIRDLeftLegBone::Construct(), G4MIRDLiver::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDBrain::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDPelvis::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDThyroid::Construct(), G4MIRDUpperLargeIntestine::Construct(), B03DetectorConstruction::Construct(), G4MIRDThymus::Construct(), G4MIRDHead::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDPancreas::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDRightArmBone::Construct(), G4MIRDUrinaryBladder::Construct(), B02DetectorConstruction::Construct(), B01DetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), PurgMagDetectorConstruction::ConstructCalorimeter(), DetectorConstruction::ConstructLine(), PHG4TRDDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4ECAPToFDetector::ConstructMe(), G4JLeicVTXDetector::ConstructMe(), G4JLeicDIRCDetector::ConstructMe(), EICG4RPDetector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), PHG4BeamlineMagnetDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), EICG4dRICHDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4FCalDetector::ConstructMe(), PHG4FPbScDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), GammaRayTelDetectorConstruction::ConstructPayload(), PHG4CEmcTestBeamDetector::ConstructSandwichVolume(), EICG4BwdDetector::ConstructTower(), EICG4B0ECALDetector::ConstructTower(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), G4HumanPhantomConstruction::ConstructWorld(), TSDetectorConstruction::ConstructWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), G4GPSModel::DescribeYourselfTo(), PHG4Detector::DisplayVolume(), UVA_VisAction::Draw(), G4ScoringCylinder::Draw(), G4ScoringBox::Draw(), ExN04CalorimeterHit::Draw(), RE01CalorimeterHit::Draw(), RE05CalorimeterHit::Draw(), ExGflashHit::Draw(), LXePMTHit::Draw(), Par01CalorimeterHit::Draw(), G4ScoringCylinder::DrawColumn(), G4ScoringBox::DrawColumn(), export_G4VisAttributes(), CML2AccSaturn::flatteningFilter(), G4ArrowModel::G4ArrowModel(), CML2AccSaturn::Jaw1X(), CML2AccSaturn::Jaw1Y(), CML2Acc2::primaryCollimator(), DetectorConstruction::ResiduesView(), EICG4ZDCStructure::SetColors(), PHG4GDMLDetector::SetDisplayProperty(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4EicDircDetector::SetVisualization(), and LXeMainVolume::VisAttributes().
void G4VisAttributes::SetForceWireframe (G4bool force = true)
Definition at line 171 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 171 of file G4VisAttributes.cc
References fForceDrawingStyle, fForcedStyle, and wireframe.
Referenced by PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4BarrelEcalDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), PHG4InttDisplayAction::ApplyDisplayAction(), PHG4HybridHomogeneousCalorimeterDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), PHG4ForwardEcalDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), PHG4LFHcalDisplayAction::ApplyDisplayAction(), PHG4mRICHDetector::build_lens(), ExN04DetectorConstruction::Construct(), Par01DetectorConstruction::Construct(), RE01DetectorConstruction::Construct(), RE05DetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), doiPETDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), GammaRayTelDetectorConstruction::ConstructPayload(), doiPETDetectorConstruction::ConstructPhantom(), UltraDetectorConstruction::ConstructReflector(), TSDetectorConstruction::ConstructWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), G4LogicalVolumeModel::DescribeSolid(), ExN04CalorimeterHit::Draw(), RE01CalorimeterHit::Draw(), ExGflashHit::Draw(), Par01CalorimeterHit::Draw(), export_G4VisAttributes(), PerspectiveVisAction::RoomAndChair(), G4VisCommandsTouchableSet::SetNewValue(), CCalG4Able::setVisType(), and G4EicDircDetector::SetVisualization().
void G4VisAttributes::SetLineStyle (LineStyle)
Referenced by G4PhysicalVolumeModel::DescribeAndDescend(), export_G4VisAttributes(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetLineWidth (G4double)
Referenced by G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D(), G4MIRDBrain::Construct(), G4MIRDSkull::Construct(), CML2Ph_BoxInBox::Construct(), EICG4dRICHDetector::ConstructMe(), G4PhysicalVolumeModel::DescribeAndDescend(), G4VFieldModel::DescribeYourselfTo(), CexmcScenePrimitives::DrawRadialLine(), G4TrajectoryDrawerUtils::DrawWithoutTime(), G4TrajectoryDrawerUtils::DrawWithTime(), export_G4VisAttributes(), CexmcScenePrimitives::HighlightInnerCrystals(), G4VisCommandSceneAddLine::Line::Line(), G4VisCommandSceneAddLine2D::Line2D::Line2D(), G4VisCommandSceneAddFrame::Frame::operator()(), and G4VisCommandsTouchableSet::SetNewValue().
void G4VisAttributes::SetStartTime (G4double)
Referenced by XAluminumElectrodeHit::Draw().
void G4VisAttributes::SetVisibility (G4bool = true)
Referenced by BeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4BbcDisplayAction::ApplyDisplayAction(), PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4ZDCDisplayAction::ApplyDisplayAction(), PHG4EPDDisplayAction::ApplyDisplayAction(), PHG4HybridHomogeneousCalorimeterDisplayAction::ApplyDisplayAction(), PHG4InttDisplayAction::ApplyDisplayAction(), PHG4PhenixDisplayAction::ApplyDisplayAction(), G4JLeicBeamLineMagnetDisplayAction::ApplyDisplayAction(), G4JLeicDIRCDisplayAction::ApplyDisplayAction(), G4JLeicVTXDisplayAction::ApplyDisplayAction(), PHG4MvtxDisplayAction::ApplyDisplayAction(), AllSi_Al_support_DisplayAction::ApplyDisplayAction(), AllSiliconTrackerDisplayAction::ApplyDisplayAction(), PHG4TpcDisplayAction::ApplyDisplayAction(), G4LBLVtxDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4InnerHcalDisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), PHG4OuterHcalDisplayAction::ApplyDisplayAction(), BeastMagnetDisplayAction::ApplyDisplayAction(), PHG4ForwardDualReadoutDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4BarrelEcalDisplayAction::ApplyDisplayAction(), PHG4CrystalCalorimeterDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), PHG4ForwardEcalDisplayAction::ApplyDisplayAction(), PHG4ForwardHcalDisplayAction::ApplyDisplayAction(), PHG4LFHcalDisplayAction::ApplyDisplayAction(), G4EicDircDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), PHG4BackwardHcalDisplayAction::ApplyDisplayAction(), PHG4mRICHDetector::build_lens(), ExUCNDetectorConstruction::Construct(), eRositaDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2PhantomConstruction::Construct(), doiPETDetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), DMXDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), ExN03DetectorConstruction::ConstructCalorimeter(), PurgMagDetectorConstruction::ConstructCalorimeter(), DetectorConstruction::ConstructDetector(), G4tgbVolume::ConstructG4LogVol(), DetectorConstruction::ConstructLine(), PHG4ECAPToFDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4TRDDetector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), EICG4dRICHDetector::ConstructMe(), PHG4BeamlineMagnetDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4FCalDetector::ConstructMe(), PHG4FPbScDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), GammaRayTelDetectorConstruction::ConstructPayload(), doiPETDetectorConstruction::ConstructPhantom(), UltraDetectorConstruction::ConstructReflector(), PHG4CEmcTestBeamDetector::ConstructSandwichVolume(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), UltraDetectorConstruction::ConstructUVscope(), DetectorConstruction::ConstructWorld(), TSDetectorConstruction::ConstructWorld(), G4PhysicalVolumeModel::DescribeAndDescend(), PHG4Detector::DisplayVolume(), export_G4VisAttributes(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), DicomPhantomParameterisationColour::ReadColourData(), DicomNestedPhantomParameterisation::ReadColourData(), PHG4GDMLDetector::SetDisplayProperty(), G4VisCommandsTouchableSet::SetNewValue(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), XDetectorConstruction::SetupGeometry(), RE03DetectorConstruction::SetupGeometry(), RE04DetectorConstruction::SetupGeometry(), GB03DetectorConstruction::SetupGeometry(), RE06DetectorConstruction::SetupGeometry(), CCalG4Able::setVisType(), G4EicDircDetector::SetVisualization(), G3toG4DetectorConstruction::SimpleConstruct(), CML2Acc2::target(), G4VViewer::TouchableSetVisibility(), and CML2Acc2::vacuumWindow().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4VisAttributes & a) friend
Definition at line 242 of file G4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 242 of file G4VisAttributes.cc
Member Data Documentation
const std::map<G4String,G4AttDef>* G4VisAttributes::fAttDefs private
Definition at line 170 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
const std::vector<G4AttValue>* G4VisAttributes::fAttValues private
Definition at line 169 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 169 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
G4Colour G4VisAttributes::fColour private
Definition at line 156 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 156 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
G4bool G4VisAttributes::fDaughtersInvisible private
Definition at line 155 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 155 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
G4double G4VisAttributes::fEndTime private
Definition at line 168 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
G4bool G4VisAttributes::fForceAuxEdgeVisible private
Definition at line 164 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 164 of file G4VisAttributes.hh
Referenced by IsForcedAuxEdgeVisible(), operator!=(), operator<<(), operator=(), and SetForceAuxEdgeVisible().
G4bool G4VisAttributes::fForcedAuxEdgeVisible private
Definition at line 165 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 165 of file G4VisAttributes.hh
Referenced by IsForcedAuxEdgeVisible(), operator!=(), operator<<(), operator=(), and SetForceAuxEdgeVisible().
G4int G4VisAttributes::fForcedLineSegmentsPerCircle private
Definition at line 166 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 166 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), operator=(), and SetForceLineSegmentsPerCircle().
G4int G4VisAttributes::fForcedNumberOfCloudPoints private
Definition at line 162 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 162 of file G4VisAttributes.hh
Referenced by operator=(), and SetForceNumberOfCloudPoints().
G4bool G4VisAttributes::fForceDrawingStyle private
Definition at line 160 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 160 of file G4VisAttributes.hh
Referenced by GetForcedDrawingStyle(), operator!=(), operator<<(), operator=(), SetForceCloud(), SetForceSolid(), and SetForceWireframe().
ForcedDrawingStyle G4VisAttributes::fForcedStyle private
Definition at line 161 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 161 of file G4VisAttributes.hh
Referenced by GetForcedDrawingStyle(), operator!=(), operator<<(), operator=(), SetForceCloud(), SetForceSolid(), and SetForceWireframe().
LineStyle G4VisAttributes::fLineStyle private
Definition at line 157 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 157 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
G4double G4VisAttributes::fLineWidth private
Definition at line 158 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 158 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
constexpr G4int G4VisAttributes::fMinLineSegmentsPerCircle = 3 static
Definition at line 146 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 146 of file G4VisAttributes.hh
Referenced by SetForceLineSegmentsPerCircle().
G4double G4VisAttributes::fStartTime private
Definition at line 168 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
constexpr G4double G4VisAttributes::fVeryLongTime = 1.e100 * CLHEP::ns static
Definition at line 149 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VisAttributes.hh
Referenced by G4VisCommandsViewerSet::G4VisCommandsViewerSet().
G4bool G4VisAttributes::fVisible private
Definition at line 154 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 154 of file G4VisAttributes.hh
Referenced by operator!=(), operator<<(), and operator=().
const G4VisAttributes G4VisAttributes::Invisible = G4VisAttributes (false) static
Definition at line 92 of file G4VisAttributes.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VisAttributes.hh
Referenced by doiPETDetectorConstruction::Construct(), EICG4ZDCStructure::ConstructCrystalTowers(), EICG4ZDCStructure::ConstructEMLayers(), EICG4ZDCStructure::ConstructHCSciLayers(), EICG4ZDCStructure::ConstructHCSiliconLayers(), EICG4dRICHDetector::ConstructMe(), and EICG4ZDCDetector::ConstructMe().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VisAttributes.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4VisAttributes.cc