ECCE @ EIC Software: G4UserTimeStepAction Class Reference
G4UserTimeStepAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4UserTimeStepAction.hh>
Public Member Functions
G4UserTimeStepAction ()
G4UserTimeStepAction (const G4UserTimeStepAction &)
virtual ~G4UserTimeStepAction ()
virtual void StartProcessing ()
virtual void NewStage ()
virtual void UserPreTimeStepAction ()
virtual void UserPostTimeStepAction ()
virtual void UserReactionAction (const G4Track &, const G4Track &, const std::vector< G4Track * > *)
virtual void EndProcessing ()
Protected Member Functions
void SetMinimumTimeSteps (std::map< double, double > *)
void AddTimeStep (double, double)
Private Member Functions
G4UserTimeStepAction & operator= (const G4UserTimeStepAction &)
Detailed Description
G4UserTimeStepAction is used by G4Scheduler.
StartProcessing called before processing
TimeStepAction called at every global step
UserReactionAction called when a reaction occurs
EndProcessing called after processing
Definition at line 68 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 68 of file G4UserTimeStepAction.hh
Constructor & Destructor Documentation
G4UserTimeStepAction::G4UserTimeStepAction ()
Definition at line 38 of file G4UserTimeStepAction.cc.
View newest version in sPHENIX GitHub at line 38 of file G4UserTimeStepAction.cc
G4UserTimeStepAction::G4UserTimeStepAction (const G4UserTimeStepAction &)
Definition at line 44 of file G4UserTimeStepAction.cc.
View newest version in sPHENIX GitHub at line 44 of file G4UserTimeStepAction.cc
G4UserTimeStepAction::~G4UserTimeStepAction () virtual
Definition at line 41 of file G4UserTimeStepAction.cc.
View newest version in sPHENIX GitHub at line 41 of file G4UserTimeStepAction.cc
Member Function Documentation
void G4UserTimeStepAction::AddTimeStep (double startingTime, double timeStep) protected
Definition at line 57 of file G4UserTimeStepAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UserTimeStepAction.cc
References G4VScheduler::Instance().
Referenced by TimeStepAction::TimeStepAction().
virtual void G4UserTimeStepAction::EndProcessing () inline virtual
Reimplemented in TimeStepAction, TimeStepAction, and TimeStepAction.
Definition at line 92 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 92 of file G4UserTimeStepAction.hh
Referenced by G4Scheduler::Process().
virtual void G4UserTimeStepAction::NewStage () inline virtual
Definition at line 76 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 76 of file G4UserTimeStepAction.hh
Referenced by G4Scheduler::DoProcess().
G4UserTimeStepAction & G4UserTimeStepAction::operator= (const G4UserTimeStepAction &) private
Definition at line 46 of file G4UserTimeStepAction.cc.
View newest version in sPHENIX GitHub at line 46 of file G4UserTimeStepAction.cc
void G4UserTimeStepAction::SetMinimumTimeSteps (std::map< double, double > * timeSteps) protected
Definition at line 52 of file G4UserTimeStepAction.cc.
View newest version in sPHENIX GitHub at line 52 of file G4UserTimeStepAction.cc
References G4VScheduler::Instance().
virtual void G4UserTimeStepAction::StartProcessing () inline virtual
Reimplemented in TimeStepAction, TimeStepAction, and TimeStepAction.
Definition at line 75 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4UserTimeStepAction.hh
Referenced by G4Scheduler::Process().
virtual void G4UserTimeStepAction::UserPostTimeStepAction () inline virtual
Reimplemented in TimeStepAction, TimeStepAction, and TimeStepAction.
Definition at line 84 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 84 of file G4UserTimeStepAction.hh
Referenced by G4Scheduler::Stepping().
virtual void G4UserTimeStepAction::UserPreTimeStepAction () inline virtual
In this method, the user can use : G4Scheduler::Instance()->GetGlobalTime(), to know the current simulation time G4Scheduler::Instance()->GetTimeStep(), to know the selected minimum time WARNING : The call of this method happens before the call of DoIT methods
Reimplemented in TimeStepAction, TimeStepAction, and TimeStepAction.
Definition at line 83 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4UserTimeStepAction.hh
Referenced by G4Scheduler::Stepping().
virtual void G4UserTimeStepAction::UserReactionAction (const G4Track & , const G4Track & , const std::vector< G4Track * > *) inline virtual
Inform about a reaction
Reimplemented in TimeStepAction, TimeStepAction, TimeStepAction, and TimeStepAction.
Definition at line 89 of file G4UserTimeStepAction.hh.
View newest version in sPHENIX GitHub at line 89 of file G4UserTimeStepAction.hh
Referenced by G4ITModelProcessor::ComputeTrackReaction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4UserTimeStepAction.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4UserTimeStepAction.cc