ECCE @ EIC Software: G4ParticleHPList Class Reference
G4ParticleHPList Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPList.hh>
Public Member Functions
G4ParticleHPList ()
~G4ParticleHPList ()
void SetValue (G4int i, G4double y)
G4double GetValue (G4int i)
G4int GetListLength ()
void Dump ()
void Init (std::istream &aDataFile, G4int nPar, G4double unit=1.)
void Init (std::istream &aDataFile, G4double unit=1.)
void SetLabel (G4double aLabel)
G4double GetLabel ()
Private Member Functions
void Check (G4int i)
Private Attributes
G4double theLabel
G4double * theData
G4int nEntries
G4int nPoints
Detailed Description
Definition at line 36 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPList.hh
Constructor & Destructor Documentation
G4ParticleHPList::G4ParticleHPList () inline
Definition at line 40 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPList.hh
References nEntries, nPoints, theData, and theLabel.
G4ParticleHPList::~G4ParticleHPList () inline
Definition at line 48 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPList.hh
References theData.
Member Function Documentation
void G4ParticleHPList::Check (G4int i) private
Definition at line 36 of file G4ParticleHPList.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPList.cc
References nEntries, nPoints, and theData.
Referenced by SetValue().
void G4ParticleHPList::Dump ()
Definition at line 92 of file G4ParticleHPList.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPList.cc
References G4cout, G4endl, theData, and theLabel.
Referenced by G4ParticleHPContAngularPar::Dump().
G4double G4ParticleHPList::GetLabel () inline
Definition at line 70 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPList.hh
References theLabel.
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation(), G4ParticleHPContAngularPar::PrepareTableInterpolation(), and G4ParticleHPContAngularPar::Sample().
G4int G4ParticleHPList::GetListLength () inline
Definition at line 60 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPList.hh
References nEntries.
Referenced by GetValue().
G4double G4ParticleHPList::GetValue (G4int i)
Definition at line 77 of file G4ParticleHPList.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPList.cc
References GetListLength(), nEntries, and theData.
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation(), G4ParticleHPParticleYield::GetDecayConstant(), and G4ParticleHPContAngularPar::Sample().
void G4ParticleHPList::Init (std::istream & aDataFile, G4int nPar, G4double unit = 1.)
Definition at line 54 of file G4ParticleHPList.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPList.cc
References SetValue(), and y.
Referenced by G4ParticleHPContAngularPar::Init(), and G4ParticleHPParticleYield::InitDelayed().
void G4ParticleHPList::Init (std::istream & aDataFile, G4double unit = 1.)
Definition at line 65 of file G4ParticleHPList.cc.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPList.cc
References SetValue(), G4INCL::CrossSections::total(), and y.
void G4ParticleHPList::SetLabel (G4double aLabel) inline
Definition at line 68 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPList.hh
References theLabel.
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation(), and G4ParticleHPContAngularPar::Init().
void G4ParticleHPList::SetValue (G4int i, G4double y) inline
Definition at line 53 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPList.hh
References Check(), theData, and y.
Referenced by G4ParticleHPContAngularPar::BuildByInterpolation(), and Init().
Member Data Documentation
G4int G4ParticleHPList::nEntries private
Definition at line 79 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPList.hh
Referenced by Check(), G4ParticleHPList(), GetListLength(), and GetValue().
G4int G4ParticleHPList::nPoints private
Definition at line 80 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPList.hh
Referenced by Check(), and G4ParticleHPList().
G4double* G4ParticleHPList::theData private
Definition at line 78 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPList.hh
Referenced by Check(), Dump(), G4ParticleHPList(), GetValue(), SetValue(), and ~G4ParticleHPList().
G4double G4ParticleHPList::theLabel private
Definition at line 76 of file G4ParticleHPList.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPList.hh
Referenced by Dump(), G4ParticleHPList(), GetLabel(), and SetLabel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPList.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPList.cc