ECCE @ EIC Software: P6DExtDecayerPhysics Class Reference
P6DExtDecayerPhysics Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.hh>
Public Member Functions
P6DExtDecayerPhysics (const G4String &name="ExtDecayer")
virtual ~P6DExtDecayerPhysics ()
void SetForceDecay (EDecayType force_decay_type)
EDecayType GetForceDecay ()
P6DExtDecayerPhysics (const G4String &name="ExtDecayer")
virtual ~P6DExtDecayerPhysics ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Member Functions
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Private Member Functions
P6DExtDecayerPhysics (const P6DExtDecayerPhysics &right)
Not implemented.
P6DExtDecayerPhysics & operator= (const P6DExtDecayerPhysics &right)
Not implemented.
P6DExtDecayerPhysics (const P6DExtDecayerPhysics &right)
Not implemented.
P6DExtDecayerPhysics & operator= (const P6DExtDecayerPhysics &right)
Not implemented.
Private Attributes
bool _active_force_decay
EDecayType _force_decay_type
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
The builder for external decayer.
The external decayer is added to all instantiated decay processes
Author
I. Hrivnacova; IPN Orsay
Definition at line 48 of file P6DExtDecayerPhysics.hh.
View newest version in sPHENIX GitHub at line 48 of file P6DExtDecayerPhysics.hh
Constructor & Destructor Documentation
P6DExtDecayerPhysics::P6DExtDecayerPhysics (const G4String & name = "ExtDecayer")
Standard constructor
Definition at line 56 of file P6DExtDecayerPhysics.cc.
View newest version in sPHENIX GitHub at line 56 of file P6DExtDecayerPhysics.cc
P6DExtDecayerPhysics::~P6DExtDecayerPhysics () virtual
Destructor
Definition at line 66 of file P6DExtDecayerPhysics.cc.
View newest version in sPHENIX GitHub at line 66 of file P6DExtDecayerPhysics.cc
P6DExtDecayerPhysics::P6DExtDecayerPhysics (const P6DExtDecayerPhysics & right) private
Not implemented.
P6DExtDecayerPhysics::P6DExtDecayerPhysics (const G4String & name = "ExtDecayer")
virtual P6DExtDecayerPhysics::~P6DExtDecayerPhysics () virtual
P6DExtDecayerPhysics::P6DExtDecayerPhysics (const P6DExtDecayerPhysics & right) private
Not implemented.
Member Function Documentation
virtual void P6DExtDecayerPhysics::ConstructParticle () protected virtual
Implements G4VPhysicsConstructor.
void P6DExtDecayerPhysics::ConstructParticle (void) protected virtual
Nothing to be done here
Implements G4VPhysicsConstructor.
Definition at line 77 of file P6DExtDecayerPhysics.cc.
View newest version in sPHENIX GitHub at line 77 of file P6DExtDecayerPhysics.cc
virtual void P6DExtDecayerPhysics::ConstructProcess () protected virtual
Implements G4VPhysicsConstructor.
void P6DExtDecayerPhysics::ConstructProcess (void) protected virtual
Loop over all particles instantiated and add external decayer to all decay processes if External decayer is set
Implements G4VPhysicsConstructor.
Definition at line 84 of file P6DExtDecayerPhysics.cc.
View newest version in sPHENIX GitHub at line 84 of file P6DExtDecayerPhysics.cc
References _active_force_decay, _force_decay_type, aParticleIterator, G4INCL::ClusterDecay::decay(), G4Pythia6Decayer::ForceDecayType(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4ProcessVector::length(), particle, G4Decay::SetExtDecayer(), G4Pythia6Decayer::SetVerboseLevel(), and G4VPhysicsConstructor::verboseLevel.
EDecayType P6DExtDecayerPhysics::GetForceDecay () inline
Definition at line 59 of file P6DExtDecayerPhysics.hh.
View newest version in sPHENIX GitHub at line 59 of file P6DExtDecayerPhysics.hh
References _force_decay_type.
P6DExtDecayerPhysics& P6DExtDecayerPhysics::operator= (const P6DExtDecayerPhysics & right) private
Not implemented.
P6DExtDecayerPhysics& P6DExtDecayerPhysics::operator= (const P6DExtDecayerPhysics & right) private
Not implemented.
void P6DExtDecayerPhysics::SetForceDecay (EDecayType force_decay_type) inline
Definition at line 54 of file P6DExtDecayerPhysics.hh.
View newest version in sPHENIX GitHub at line 54 of file P6DExtDecayerPhysics.hh
References _active_force_decay, and _force_decay_type.
Referenced by PHG4Reco::Init().
Member Data Documentation
bool P6DExtDecayerPhysics::_active_force_decay private
Definition at line 73 of file P6DExtDecayerPhysics.hh.
View newest version in sPHENIX GitHub at line 73 of file P6DExtDecayerPhysics.hh
Referenced by ConstructProcess(), and SetForceDecay().
EDecayType P6DExtDecayerPhysics::_force_decay_type private
Definition at line 74 of file P6DExtDecayerPhysics.hh.
View newest version in sPHENIX GitHub at line 74 of file P6DExtDecayerPhysics.hh
Referenced by ConstructProcess(), GetForceDecay(), and SetForceDecay().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/include/P6DExtDecayerPhysics.hh
coresoftware/blob/master/simulation/g4simulation/g4decayer/P6DExtDecayerPhysics.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/src/P6DExtDecayerPhysics.cc