ECCE @ EIC Software: G4CascadeRecoilMaker Class Reference
G4CascadeRecoilMaker Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeRecoilMaker.hh>
Public Member Functions
G4CascadeRecoilMaker (G4double tolerance=0.001 *CLHEP::MeV)
virtual ~G4CascadeRecoilMaker ()
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output, const std::vector< G4CascadParticle > &cparticles)
void setTolerance (G4double tolerance)
void setRecoilExcitation (G4double Eexc)
G4InuclNuclei * makeRecoilNuclei (G4InuclParticle::Model model=G4InuclParticle::DefaultModel)
G4Fragment * makeRecoilFragment ()
void addExcitonConfiguration (const G4ExitonConfiguration exciton)
G4int getRecoilA () const
G4int getRecoilZ () const
G4double getRecoilExcitation () const
const G4LorentzVector & getRecoilMomentum () const
G4bool goodFragment () const
G4bool goodRecoil () const
G4bool wholeEvent () const
G4bool unphysicalRecoil () const
G4bool goodNucleus () const
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
virtual void setVerboseLevel (G4int verbose=0)
Protected Member Functions
void fillRecoil ()
G4double deltaM () const
Protected Member Functions inherited from G4VCascadeCollider
virtual void setName (const G4String &name)
Private Member Functions
G4CascadeRecoilMaker (const G4CascadeRecoilMaker &)
G4CascadeRecoilMaker & operator= (const G4CascadeRecoilMaker &)
Private Attributes
G4CascadeCheckBalance * balance
G4double excTolerance
G4double inputEkin
G4int recoilA
G4int recoilZ
G4LorentzVector recoilMomentum
G4double excitationEnergy
G4ExitonConfiguration theExcitons
G4InuclNuclei theRecoilNuclei
G4Fragment theRecoilFragment
Additional Inherited Members
Protected Attributes inherited from G4VCascadeCollider
G4String theName
G4int verboseLevel
Detailed Description
Definition at line 64 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CascadeRecoilMaker.hh
Constructor & Destructor Documentation
G4CascadeRecoilMaker::G4CascadeRecoilMaker (G4double tolerance = 0.001*CLHEP::MeV) explicit
Definition at line 66 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 66 of file G4CascadeRecoilMaker.cc
References balance, and G4VCascadeCollider::theName.
G4CascadeRecoilMaker::~G4CascadeRecoilMaker () virtual
Definition at line 73 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 73 of file G4CascadeRecoilMaker.cc
References balance.
G4CascadeRecoilMaker::G4CascadeRecoilMaker (const G4CascadeRecoilMaker &) private
Member Function Documentation
void G4CascadeRecoilMaker::addExcitonConfiguration (const G4ExitonConfiguration exciton) inline
Definition at line 88 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 88 of file G4CascadeRecoilMaker.hh
References theExcitons.
Referenced by G4IntraNucleiCascader::finishCascade().
void G4CascadeRecoilMaker::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & output) virtual
Implements G4VCascadeCollider.
Definition at line 80 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 80 of file G4CascadeRecoilMaker.cc
References balance, G4CascadeCheckBalance::collide(), fillRecoil(), G4cout, G4endl, G4InuclParticle::getKineticEnergy(), inputEkin, G4VCascadeCollider::setVerboseLevel(), and G4VCascadeCollider::verboseLevel.
Referenced by G4IntraNucleiCascader::finishCascade(), and G4IntraNucleiCascader::generateCascade().
void G4CascadeRecoilMaker::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & output, const std::vector< G4CascadParticle > & cparticles)
Definition at line 96 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 96 of file G4CascadeRecoilMaker.cc
References balance, G4CascadeCheckBalance::collide(), fillRecoil(), G4cout, G4endl, G4InuclParticle::getKineticEnergy(), inputEkin, G4VCascadeCollider::setVerboseLevel(), and G4VCascadeCollider::verboseLevel.
G4double G4CascadeRecoilMaker::deltaM () const protected
Definition at line 200 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 200 of file G4CascadeRecoilMaker.cc
References G4InuclNuclei::getNucleiMass(), CLHEP::HepLorentzVector::m(), recoilA, recoilMomentum, and recoilZ.
Referenced by fillRecoil().
void G4CascadeRecoilMaker::fillRecoil () protected
Definition at line 115 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 115 of file G4CascadeRecoilMaker.cc
References kdfinder::abs(), balance, G4ExitonConfiguration::clear(), G4CascadeCheckBalance::deltaB(), G4CascadeCheckBalance::deltaLV(), deltaM(), G4CascadeCheckBalance::deltaQ(), CLHEP::HepLorentzVector::e(), excitationEnergy, excTolerance, G4cout, G4endl, GeV, goodFragment(), CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), recoilA, recoilMomentum, recoilZ, theExcitons, and G4VCascadeCollider::verboseLevel.
Referenced by collide().
G4int G4CascadeRecoilMaker::getRecoilA () const inline
Definition at line 93 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 93 of file G4CascadeRecoilMaker.hh
References recoilA.
Referenced by G4IntraNucleiCascader::finishCascade(), and G4IntraNucleiCascader::generateCascade().
G4double G4CascadeRecoilMaker::getRecoilExcitation () const inline
Definition at line 95 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 95 of file G4CascadeRecoilMaker.hh
References excitationEnergy.
Referenced by G4IntraNucleiCascader::finishCascade().
const G4LorentzVector& G4CascadeRecoilMaker::getRecoilMomentum () const inline
Definition at line 96 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 96 of file G4CascadeRecoilMaker.hh
References recoilMomentum.
Referenced by G4IntraNucleiCascader::finishCascade().
G4int G4CascadeRecoilMaker::getRecoilZ () const inline
Definition at line 94 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CascadeRecoilMaker.hh
References recoilZ.
Referenced by G4IntraNucleiCascader::finishCascade().
G4bool G4CascadeRecoilMaker::goodFragment () const
Definition at line 208 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 208 of file G4CascadeRecoilMaker.cc
References recoilA, and recoilZ.
Referenced by fillRecoil(), G4IntraNucleiCascader::finishCascade(), goodNucleus(), and goodRecoil().
G4bool G4CascadeRecoilMaker::goodNucleus () const
Definition at line 234 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 234 of file G4CascadeRecoilMaker.cc
References G4InuclSpecialFunctions::bindingEnergy(), excitationEnergy, excTolerance, G4cerr, G4cout, G4endl, GeV, goodFragment(), goodRecoil(), inputEkin, keV, recoilA, recoilZ, and G4VCascadeCollider::verboseLevel.
Referenced by G4IntraNucleiCascader::finishCascade().
G4bool G4CascadeRecoilMaker::goodRecoil () const
Definition at line 212 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 212 of file G4CascadeRecoilMaker.cc
References excitationEnergy, excTolerance, and goodFragment().
Referenced by goodNucleus(), makeRecoilFragment(), makeRecoilNuclei(), and unphysicalRecoil().
G4Fragment * G4CascadeRecoilMaker::makeRecoilFragment ()
Definition at line 164 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 164 of file G4CascadeRecoilMaker.cc
References excitationEnergy, G4cout, G4endl, G4InuclNuclei::getNucleiMass(), GeV, goodRecoil(), G4ExitonConfiguration::neutronHoles, G4ExitonConfiguration::neutronQuasiParticles, G4ExitonConfiguration::protonHoles, G4ExitonConfiguration::protonQuasiParticles, recoilA, recoilMomentum, recoilZ, G4Fragment::SetMomentum(), G4Fragment::SetNumberOfExcitedParticle(), G4Fragment::SetNumberOfHoles(), CLHEP::HepLorentzVector::setVectM(), G4Fragment::SetZandA_asInt(), theExcitons, G4VCascadeCollider::theName, theRecoilFragment, CLHEP::HepLorentzVector::vect(), G4VCascadeCollider::verboseLevel, and wholeEvent().
Referenced by G4IntraNucleiCascader::finishCascade().
G4InuclNuclei * G4CascadeRecoilMaker::makeRecoilNuclei (G4InuclParticle::Model model = G4InuclParticle::DefaultModel)
Definition at line 143 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 143 of file G4CascadeRecoilMaker.cc
References excitationEnergy, G4InuclNuclei::fill(), G4cout, G4endl, goodRecoil(), recoilA, recoilMomentum, recoilZ, G4InuclNuclei::setExitonConfiguration(), theExcitons, G4VCascadeCollider::theName, theRecoilNuclei, G4VCascadeCollider::verboseLevel, and wholeEvent().
G4CascadeRecoilMaker& G4CascadeRecoilMaker::operator= (const G4CascadeRecoilMaker &) private
void G4CascadeRecoilMaker::setRecoilExcitation (G4double Eexc) inline
Definition at line 81 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 81 of file G4CascadeRecoilMaker.hh
References excitationEnergy.
Referenced by G4IntraNucleiCascader::finishCascade().
void G4CascadeRecoilMaker::setTolerance (G4double tolerance) inline
Definition at line 79 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CascadeRecoilMaker.hh
References excTolerance.
Referenced by G4IntraNucleiCascader::initialize().
G4bool G4CascadeRecoilMaker::unphysicalRecoil () const inline
Definition at line 102 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 102 of file G4CascadeRecoilMaker.hh
References goodRecoil(), and wholeEvent().
G4bool G4CascadeRecoilMaker::wholeEvent () const
Definition at line 216 of file G4CascadeRecoilMaker.cc.
View newest version in sPHENIX GitHub at line 216 of file G4CascadeRecoilMaker.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::e(), excTolerance, G4cout, G4endl, GeV, recoilA, recoilMomentum, recoilZ, CLHEP::HepLorentzVector::rho(), and G4VCascadeCollider::verboseLevel.
Referenced by G4IntraNucleiCascader::finishCascade(), makeRecoilFragment(), makeRecoilNuclei(), and unphysicalRecoil().
Member Data Documentation
G4CascadeCheckBalance* G4CascadeRecoilMaker::balance private
Definition at line 111 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 111 of file G4CascadeRecoilMaker.hh
Referenced by collide(), fillRecoil(), G4CascadeRecoilMaker(), and ~G4CascadeRecoilMaker().
G4double G4CascadeRecoilMaker::excitationEnergy private
Definition at line 120 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 120 of file G4CascadeRecoilMaker.hh
Referenced by fillRecoil(), getRecoilExcitation(), goodNucleus(), goodRecoil(), makeRecoilFragment(), makeRecoilNuclei(), and setRecoilExcitation().
G4double G4CascadeRecoilMaker::excTolerance private
Definition at line 113 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 113 of file G4CascadeRecoilMaker.hh
Referenced by fillRecoil(), goodNucleus(), goodRecoil(), setTolerance(), and wholeEvent().
G4double G4CascadeRecoilMaker::inputEkin private
Definition at line 115 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 115 of file G4CascadeRecoilMaker.hh
Referenced by collide(), and goodNucleus().
G4int G4CascadeRecoilMaker::recoilA private
Definition at line 117 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 117 of file G4CascadeRecoilMaker.hh
Referenced by deltaM(), fillRecoil(), getRecoilA(), goodFragment(), goodNucleus(), makeRecoilFragment(), makeRecoilNuclei(), and wholeEvent().
G4LorentzVector G4CascadeRecoilMaker::recoilMomentum private
Definition at line 119 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 119 of file G4CascadeRecoilMaker.hh
Referenced by deltaM(), fillRecoil(), getRecoilMomentum(), makeRecoilFragment(), makeRecoilNuclei(), and wholeEvent().
G4int G4CascadeRecoilMaker::recoilZ private
Definition at line 118 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 118 of file G4CascadeRecoilMaker.hh
Referenced by deltaM(), fillRecoil(), getRecoilZ(), goodFragment(), goodNucleus(), makeRecoilFragment(), makeRecoilNuclei(), and wholeEvent().
G4ExitonConfiguration G4CascadeRecoilMaker::theExcitons private
Definition at line 122 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 122 of file G4CascadeRecoilMaker.hh
Referenced by addExcitonConfiguration(), fillRecoil(), makeRecoilFragment(), and makeRecoilNuclei().
G4Fragment G4CascadeRecoilMaker::theRecoilFragment private
Definition at line 125 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 125 of file G4CascadeRecoilMaker.hh
Referenced by makeRecoilFragment().
G4InuclNuclei G4CascadeRecoilMaker::theRecoilNuclei private
Definition at line 124 of file G4CascadeRecoilMaker.hh.
View newest version in sPHENIX GitHub at line 124 of file G4CascadeRecoilMaker.hh
Referenced by makeRecoilNuclei().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeRecoilMaker.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeRecoilMaker.cc