ECCE @ EIC Software: G4Gamma Class Reference
G4Gamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/bosons/include/G4Gamma.hh>
Public Member Functions
~G4Gamma ()
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Static Public Member Functions
static G4Gamma * Definition ()
static G4Gamma * GammaDefinition ()
static G4Gamma * Gamma ()
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4Gamma ()
Static Private Attributes
static G4Gamma * theInstance = 0
Additional Inherited Members
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 49 of file G4Gamma.hh.
View newest version in sPHENIX GitHub at line 49 of file G4Gamma.hh
Constructor & Destructor Documentation
G4Gamma::G4Gamma () inline private
Definition at line 55 of file G4Gamma.hh.
View newest version in sPHENIX GitHub at line 55 of file G4Gamma.hh
G4Gamma::~G4Gamma () inline
Definition at line 58 of file G4Gamma.hh.
View newest version in sPHENIX GitHub at line 58 of file G4Gamma.hh
Member Function Documentation
G4Gamma * G4Gamma::Definition () static
Definition at line 48 of file G4Gamma.cc.
View newest version in sPHENIX GitHub at line 48 of file G4Gamma.cc
References G4ParticleTable::FindParticle(), G4ParticleDefinition::G4ParticleDefinition(), G4ParticleTable::GetParticleTable(), MeV, and theInstance.
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4RadioactiveDecayBase::CollimateDecay(), G4RadioactiveDecay::CollimateDecay(), Gamma(), GammaDefinition(), G4FissionProductYieldDist::Initialize(), Par02FastSimModelEMCal::IsApplicable(), G4InuclElementaryParticle::makeDefinition(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), GB07BOptrLeadingParticle::StartRun(), GB07BOptrLeadingParticle::StartTracking(), G4InuclElementaryParticle::type(), BrachySteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), and XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction().
G4Gamma * G4Gamma::Gamma () static
Definition at line 85 of file G4Gamma.cc.
View newest version in sPHENIX GitHub at line 85 of file G4Gamma.cc
References Definition().
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4EmModelActivator::ActivateEmOptions(), Run::AddSecondaryTrack(), HistoManager::AddTargetStep(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4AdjointPhotoElectricModel::AdjointCrossSectionPerAtom(), G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPCaptureFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4HadLeadBias::Bias(), G4BertiniElectroNuclearBuilder::Build(), G4LENDBertiniGammaElectroNuclearBuilder::Build(), G4GammaGeneralProcess::BuildPhysicsTable(), G4MuonVDNuclearModel::CalculateEMVertex(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4ParticleHPInelasticCompFS::CompositeApply(), G4EmCalculator::ComputeDEDXForCutInRange(), G4EmCalculator::ComputeGammaAttenuationLength(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), PhysicsList::ConstructHighEnergy(), G4EmExtraPhysics::ConstructLENDGammaNuclear(), G4EmDNAPhysics_option3::ConstructParticle(), G4EmDNAPhysics_stationary::ConstructParticle(), G4EmDNAPhysics_stationary_option2::ConstructParticle(), G4EmDNAPhysics_stationary_option4::ConstructParticle(), G4EmDNAPhysics_stationary_option6::ConstructParticle(), G4EmDNAPhysics::ConstructParticle(), G4EmDNAPhysics_option1::ConstructParticle(), G4EmDNAPhysics_option2::ConstructParticle(), G4EmLivermorePhysics::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), G4EmDNAPhysics_option5::ConstructParticle(), G4EmDNAPhysics_option7::ConstructParticle(), G4EmDNAPhysics_option8::ConstructParticle(), G4EmDNAPhysics_option4::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructParticle(), G4EmLEPTSPhysics::ConstructParticle(), G4EmDNAPhysics_option6::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), G4EmExtraPhysics::ConstructParticle(), GammaLeptoNuclearPhysics::ConstructProcess(), GammaNuclearPhysics::ConstructProcess(), PhysicsListEMstd::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), Run::CountParticles(), G4SFDecay::DecayIt(), G4LowEnergyIonisation::DeexciteAtom(), G4AdjointComptonModel::DiffCrossSectionPerAtomPrimToScatPrim(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecond(), G4LossTableManager::DumpHtml(), G4HadronicProcessStore::DumpHtml(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), G4AdjointComptonModel::G4AdjointComptonModel(), G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel(), G4ComponentGGHadronNucleusXsc::G4ComponentGGHadronNucleusXsc(), G4eBremParametrizedModel::G4eBremParametrizedModel(), G4eBremsstrahlung::G4eBremsstrahlung(), G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel(), G4eeToHadrons::G4eeToHadrons(), G4eeToHadronsModel::G4eeToHadronsModel(), G4eeToTwoGammaModel::G4eeToTwoGammaModel(), G4EmBiasingManager::G4EmBiasingManager(), G4EmCaptureCascade::G4EmCaptureCascade(), G4eplusAnnihilation::G4eplusAnnihilation(), G4eplusTo2GammaOKVIModel::G4eplusTo2GammaOKVIModel(), G4eplusTo3GammaOKVIModel::G4eplusTo3GammaOKVIModel(), G4HadronNucleonXsc::G4HadronNucleonXsc(), G4KleinNishinaCompton::G4KleinNishinaCompton(), G4KleinNishinaModel::G4KleinNishinaModel(), G4LENDManager::G4LENDManager(), G4LivermorePhotoElectricModel::G4LivermorePhotoElectricModel(), G4LivermorePolarizedPhotoElectricGDModel::G4LivermorePolarizedPhotoElectricGDModel(), G4LivermorePolarizedPhotoElectricModel::G4LivermorePolarizedPhotoElectricModel(), G4MuBremsstrahlung::G4MuBremsstrahlung(), G4MuBremsstrahlungModel::G4MuBremsstrahlungModel(), G4PEEffectFluoModel::G4PEEffectFluoModel(), G4VAtomDeexcitation::G4VAtomDeexcitation(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4RDAtomicDeexcitation::GenerateFluorescence(), G4AtomicDeexcitation::GenerateFluorescence(), G4UAtomicDeexcitation::GenerateFluorescence(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), G4ParticleHPGamma::GetDecayGammas(), G4AdjointCSManager::GetForwardParticleEquivalent(), G4ParticleHPPhotonDist::GetPhotons(), G4EmModelManager::Initialise(), G4ePolarizedBremsstrahlung::InitialiseEnergyLossProcess(), G4JAEAElasticScattering::IsApplicable(), G4RayleighScattering::IsApplicable(), G4LowEnergyRayleigh::IsApplicable(), G4LowEnergyCompton::IsApplicable(), G4LowEnergyGammaConversion::IsApplicable(), G4LowEnergyPhotoElectric::IsApplicable(), G4PolarizedGammaConversion::IsApplicable(), G4LowEnergyPolarizedCompton::IsApplicable(), G4ComptonScattering::IsApplicable(), G4PolarizedCompton::IsApplicable(), G4GammaConversion::IsApplicable(), G4PolarizedPhotoElectricEffect::IsApplicable(), G4PhotoElectricEffect::IsApplicable(), main(), G4RPGReaction::NuclearReaction(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), RMC01SD::ProcessHits(), Run::Run(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4eeToPGammaModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), G4VEmAdjointModel::SetAdjointEquivalentOfDirectPrimaryParticleDefinition(), GammaKnifePhysicsList::SetCutForGamma(), GammaRayTelPhysicsList::SetCutForGamma(), STCyclotronPhysicsList::SetCutForGamma(), PhysicsList::SetCutForGamma(), XrayFluoPhysicsList::SetCutForGamma(), IORTPhysicsList::SetCutForGamma(), RMC01AnalysisManager::SetPrimaryExpSpectrumForAdjointSim(), RMC01AnalysisManager::SetPrimaryPowerLawSpectrumForAdjointSim(), G4AblaInterface::toG4ParticleDefinition(), and G4INCLXXInterface::toG4ParticleDefinition().
G4Gamma * G4Gamma::GammaDefinition () static
Definition at line 80 of file G4Gamma.cc.
View newest version in sPHENIX GitHub at line 80 of file G4Gamma.cc
References Definition().
Referenced by G4LFission::ApplyYourself(), DMXStackingAction::ClassifyNewTrack(), eRositaPhysicsList::ConstructBosons(), PhysicsList::ConstructBosons(), ExN02PhysicsList::ConstructBosons(), Par02PhysicsList::ConstructBosons(), XrayTelPhysicsList::ConstructBosons(), G4AdjointPhysicsList::ConstructBosons(), PurgMagPhysicsList::ConstructBosons(), DMXPhysicsList::ConstructMyBosons(), LBE::ConstructMyBosons(), GammaKnifeParticles::ConstructParticle(), G4BosonConstructor::ConstructParticle(), STCyclotronPhysicsList::ConstructParticle(), XrayFluoPhysicsList::ConstructParticle(), PhysicsListEMstd::ConstructParticle(), PhysicsList::ConstructParticle(), G4ErrorPhysicsList::ConstructParticle(), G4SpinDecayPhysics::ConstructParticle(), G4XMesonBaryonElastic::CrossSection(), G4QGSParticipants::DeterminePartonMomenta(), Par01PiModel::DoIt(), RE01Trajectory::DrawTrajectory(), Par01EMShowerModel::Explode(), G4ParticleTypeConverter::G4ParticleTypeConverter(), G4XPDGTotal::G4XPDGTotal(), G4Scintillation::GetScintillationYieldByParticleType(), Par01EMShowerModel::IsApplicable(), eRositaTrackerSD::ProcessHits(), and G4PenelopePhotoElectricModel::SampleSecondaries().
Member Data Documentation
G4Gamma * G4Gamma::theInstance = 0 static private
Definition at line 52 of file G4Gamma.hh.
View newest version in sPHENIX GitHub at line 52 of file G4Gamma.hh
Referenced by Definition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/bosons/include/G4Gamma.hh
geant4/tree/geant4-10.6-release/source/particles/bosons/src/G4Gamma.cc