ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_KalbachMann.cc File Reference
MCGIDI_KalbachMann.cc File Reference
#include <string.h>
#include <cmath>
#include "MCGIDI_fromTOM.h"
#include "MCGIDI_misc.h"
#include "MCGIDI_private.h"
Functions
static int MCGIDI_KalbachMann_parseFromTOM2 (statusMessageReporting *smr, int dataPerEout, int index, xDataTOM_KalbachMannCoefficients *coefficientsXData, double energyInFactor, double energyOutFactor, MCGIDI_KalbachMann *KalbachMann)
static double MCGIDI_KalbachMann_S_a_or_b (double Z_AB, double N_AB, double Z_C, double N_C, double I_ab)
MCGIDI_KalbachMann * MCGIDI_KalbachMann_new (statusMessageReporting *smr, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
int MCGIDI_KalbachMann_initialize (statusMessageReporting *, MCGIDI_KalbachMann *KalbachMann, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
MCGIDI_KalbachMann * MCGIDI_KalbachMann_free (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann)
int MCGIDI_KalbachMann_release (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann)
int MCGIDI_KalbachMann_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
int MCGIDI_KalbachMann_sampleEp (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
Variables
const double C1 = 0.04
const double C2 = 1.8e-6
Function Documentation
MCGIDI_KalbachMann* MCGIDI_KalbachMann_free (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann)
Definition at line 61 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_release(), MCGIDI_KalbachMann_new(), and MCGIDI_KalbachMann_parseFromTOM().
int MCGIDI_KalbachMann_initialize (statusMessageReporting * , MCGIDI_KalbachMann * KalbachMann, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
Definition at line 51 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_s::dists, MCGIDI_pdfsOfXGivenW_s::interpolationWY, and MCGIDI_pdfsOfXGivenW_s::interpolationXY.
Referenced by MCGIDI_KalbachMann_new(), and MCGIDI_KalbachMann_release().
MCGIDI_KalbachMann* MCGIDI_KalbachMann_new (statusMessageReporting * smr, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
Definition at line 39 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_free(), MCGIDI_KalbachMann_initialize(), and smr_malloc2.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
int MCGIDI_KalbachMann_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 89 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 89 of file MCGIDI_KalbachMann.cc
References MCGIDI_POP_s::A, xDataTOM_xDataInfo_s::axes, xDataTOM_KalbachMann_s::coefficients, xDataTOM_xDataInfo_s::data, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, MCGIDI_KalbachMann_s::energyToMeVFactor, check_license::err(), MCGIDI_KalbachMann_s::frame, MCGIDI_distribution_s::KalbachMann, MCGIDI_KalbachMann_s::Ma, MCGIDI_KalbachMann_s::massFactor, MCGIDI_KalbachMann_s::mb, MCGIDI_distributionType_KalbachMann_e, MCGIDI_fromTOM_interpolation(), MCGIDI_KalbachMann_free(), MCGIDI_KalbachMann_new(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_KalbachMann_S_a_or_b(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), MCGIDI_product_getTargetHeated(), MCGIDI_target_heated_getPOPForProjectile(), MCGIDI_target_heated_getPOPForTarget(), xDataTOM_KalbachMann_s::numberOfEnergies, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_product_s::pop, MCGIDI_distribution_s::product, MCGIDI_KalbachMann_s::ras, MCGIDI_KalbachMann_s::Sa, MCGIDI_KalbachMann_s::Sb, smr_isOk(), smr_malloc2, xDataTOM_KalbachMann_s::type, MCGIDI_distribution_s::type, MCGIDI_pdfsOfXGivenW_s::Ws, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getUnit(), xDataTOM_frame_invalid, xDataTOM_KalbachMannType_fra, xDataTOME_getOneElementByName(), and MCGIDI_POP_s::Z.
Referenced by MCGIDI_energyAngular_parseFromTOM().
static int MCGIDI_KalbachMann_parseFromTOM2 (statusMessageReporting * smr, int dataPerEout, int index, xDataTOM_KalbachMannCoefficients * coefficientsXData, double energyInFactor, double energyOutFactor, MCGIDI_KalbachMann * KalbachMann) static
Definition at line 207 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 207 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_ras_s::as, MCGIDI_pdfOfX_s::cdf, xDataTOM_KalbachMannCoefficients_s::coefficients, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, e, check_license::err(), MCGIDI_pdfsOfXGivenW_s::interpolationXY, xDataTOM_KalbachMannCoefficients_s::length, n, nfu_Okay, nfu_statusMessage(), norm, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_pdfOfX_s::numberOfXs, MCGIDI_pdfOfX_s::pdf, ptwX_free(), ptwX_getPointAtIndex_Unsafely(), ptwXY_free(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_new(), ptwXY_runningIntegral(), ptwXY_setValueAtX(), MCGIDI_KalbachMann_s::ras, MCGIDI_KalbachMann_ras_s::rs, smr_freeMemory(), smr_malloc2, smr_setReportError2, smr_unknownID, xDataTOM_KalbachMannCoefficients_s::value, MCGIDI_pdfsOfXGivenW_s::Ws, ptwXYPoint_s::x, MCGIDI_pdfOfX_s::Xs, and ptwXYPoint_s::y.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
int MCGIDI_KalbachMann_release (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann)
Definition at line 70 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 70 of file MCGIDI_KalbachMann.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, MCGIDI_KalbachMann_initialize(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, ptwXY_interpolationLinLin, MCGIDI_KalbachMann_s::ras, MCGIDI_KalbachMann_ras_s::rs, smr_freeMemory(), MCGIDI_pdfsOfXGivenW_s::Ws, and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_KalbachMann_free().
static double MCGIDI_KalbachMann_S_a_or_b (double Z_AB, double N_AB, double Z_C, double N_C, double I_ab) static
Definition at line 279 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 279 of file MCGIDI_KalbachMann.cc
References G4Pow::A13(), G4Pow::GetInstance(), and S().
Referenced by MCGIDI_KalbachMann_parseFromTOM().
int MCGIDI_KalbachMann_sampleEp (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 294 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 294 of file MCGIDI_KalbachMann.cc
References a, MCGIDI_KalbachMann_ras_s::as, C1, C2, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, MCGIDI_KalbachMann_s::energyToMeVFactor, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_pdfsOfXGivenW_sampled_s::frac, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_KalbachMann_s::frame, G4Exp(), G4Log(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_pdfsOfXGivenW_sampled_s::interpolationWY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::iW, MCGIDI_pdfsOfXGivenW_sampled_s::iX1, MCGIDI_pdfsOfXGivenW_sampled_s::iX2, MCGIDI_KalbachMann_s::Ma, MCGIDI_KalbachMann_s::massFactor, MCGIDI_KalbachMann_s::mb, MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_pdfsOfXGivenW_s::numberOfWs, ptwXY_interpolationFlat, ptwXY_interpolationLinLin, r, r2, MCGIDI_KalbachMann_s::ras, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_KalbachMann_ras_s::rs, MCGIDI_KalbachMann_s::Sb, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_isOk(), T, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_pdfsOfXGivenW_sampled_s::x, X1, and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
Variable Documentation
const double C1 = 0.04
Definition at line 15 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 15 of file MCGIDI_KalbachMann.cc
Referenced by G4ParticleHPKallbachMannSyst::A(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4Fissioner::deExcite(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4RKFieldIntegrator::Erf(), G4CompetitiveFission::FissionAtomicNumber(), G4QGSMFragmentation::FragmentString(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4ElasticHadrNucleusHE::HadrNucDifferCrSec(), MCGIDI_KalbachMann_sampleEp(), G4DNARuddIonisationExtendedModel::ProposedSampledEnergy(), and Acts::AtlasStepper< ConstantBField >::step().
const double C2 = 1.8e-6
Definition at line 15 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 15 of file MCGIDI_KalbachMann.cc
Referenced by G4ParticleHPKallbachMannSyst::A(), G4ecpssrBaseKxsModel::CalculateCrossSection(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4CompetitiveFission::FissionAtomicNumber(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4Fissioner::getC2(), G4StrawTubeXTRadiator::GetStackFactor(), G4ElasticHadrNucleusHE::HadrNucDifferCrSec(), MCGIDI_KalbachMann_sampleEp(), G4GammaConversionToMuons::PostStepDoIt(), G4DNARuddIonisationExtendedModel::ProposedSampledEnergy(), Acts::AtlasStepper< ConstantBField >::step(), and G4Abla::width().