ECCE @ EIC Software: G4GDMLMatrix Class Reference
G4GDMLMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadDefine.hh>
Public Member Functions
G4GDMLMatrix ()
G4GDMLMatrix (size_t rows0, size_t cols0)
G4GDMLMatrix (const G4GDMLMatrix &rhs)
G4GDMLMatrix & operator= (const G4GDMLMatrix &rhs)
~G4GDMLMatrix ()
void Set (size_t r, size_t c, G4double a)
G4double Get (size_t r, size_t c) const
size_t GetRows () const
size_t GetCols () const
Private Attributes
G4double * m
size_t rows
size_t cols
Detailed Description
Definition at line 47 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 47 of file G4GDMLReadDefine.hh
Constructor & Destructor Documentation
G4GDMLMatrix::G4GDMLMatrix ()
Definition at line 36 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 36 of file G4GDMLReadDefine.cc
G4GDMLMatrix::G4GDMLMatrix (size_t rows0, size_t cols0)
Definition at line 41 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 41 of file G4GDMLReadDefine.cc
References cols, FatalException, G4Exception(), m, and rows.
G4GDMLMatrix::G4GDMLMatrix (const G4GDMLMatrix & rhs)
Definition at line 53 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 53 of file G4GDMLReadDefine.cc
References cols, m, and rows.
G4GDMLMatrix::~G4GDMLMatrix ()
Definition at line 88 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 88 of file G4GDMLReadDefine.cc
References m.
Member Function Documentation
G4double G4GDMLMatrix::Get (size_t r, size_t c) const
Definition at line 103 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 103 of file G4GDMLReadDefine.cc
References c, cols, FatalException, G4Exception(), m, and rows.
Referenced by G4GDMLReadMaterials::PropertyRead(), and G4GDMLReadSolids::PropertyRead().
size_t G4GDMLMatrix::GetCols () const
Definition at line 118 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 118 of file G4GDMLReadDefine.cc
References cols.
Referenced by G4GDMLReadMaterials::PropertyRead(), and G4GDMLReadSolids::PropertyRead().
size_t G4GDMLMatrix::GetRows () const
Definition at line 113 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 113 of file G4GDMLReadDefine.cc
References rows.
Referenced by G4GDMLReadMaterials::PropertyRead(), and G4GDMLReadSolids::PropertyRead().
G4GDMLMatrix & G4GDMLMatrix::operator= (const G4GDMLMatrix & rhs)
Definition at line 65 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 65 of file G4GDMLReadDefine.cc
References cols, m, and rows.
void G4GDMLMatrix::Set (size_t r, size_t c, G4double a)
Definition at line 93 of file G4GDMLReadDefine.cc.
View newest version in sPHENIX GitHub at line 93 of file G4GDMLReadDefine.cc
References a, c, cols, FatalException, G4Exception(), m, and rows.
Referenced by G4GDMLReadDefine::MatrixRead().
Member Data Documentation
size_t G4GDMLMatrix::cols private
Definition at line 66 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 66 of file G4GDMLReadDefine.hh
Referenced by G4GDMLMatrix(), Get(), GetCols(), operator=(), and Set().
G4double* G4GDMLMatrix::m private
Definition at line 65 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 65 of file G4GDMLReadDefine.hh
Referenced by G4GDMLMatrix(), Get(), operator=(), Set(), and ~G4GDMLMatrix().
size_t G4GDMLMatrix::rows private
Definition at line 66 of file G4GDMLReadDefine.hh.
View newest version in sPHENIX GitHub at line 66 of file G4GDMLReadDefine.hh
Referenced by G4GDMLMatrix(), Get(), GetRows(), operator=(), and Set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadDefine.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLReadDefine.cc