ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/ptwXY_binaryOperators.cc File Reference
ptwXY_binaryOperators.cc File Reference
#include <cmath>
#include <float.h>
#include "ptwXY.h"
Functions
static double ptwXY_mod2 (double v, double m, int pythonMod)
static nfu_status ptwXY_mul2_s_ptwXY (ptwXYPoints *n, ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, double x1, double y1, double x2, double y2, int level)
static nfu_status ptwXY_div_s_ptwXY (ptwXYPoints *n, ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, double x1, double y1, double x2, double y2, int level, int isNAN1, int isNAN2)
static ptwXYPoints * ptwXY_div_ptwXY_forFlats (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int safeDivide)
static nfu_status ptwXY_getValueAtX_ignore_XOutsideDomainError (ptwXYPoints *ptwXY1, double x, double *y)
nfu_status ptwXY_slopeOffset (ptwXYPoints *ptwXY, double slope, double offset)
nfu_status ptwXY_add_double (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_sub_doubleFrom (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_sub_fromDouble (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_mul_double (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_div_doubleFrom (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_div_fromDouble (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_mod (ptwXYPoints *ptwXY, double m, int pythonMod)
ptwXYPoints * ptwXY_binary_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, double v1, double v2, double v1v2, nfu_status *status)
ptwXYPoints * ptwXY_add_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_sub_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_mul_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_mul2_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_div_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int safeDivide)
Function Documentation
nfu_status ptwXY_add_double (ptwXYPoints * ptwXY, double value)
Definition at line 40 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 40 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
ptwXYPoints* ptwXY_add_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 138 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 138 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::length, ptwXY_binary_ptwXY(), ptwXY_clone(), and sum.
Referenced by MCGIDI_target_heated_read(), and ptwXY_unitbaseInterpolate().
ptwXYPoints* ptwXY_binary_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, double v1, double v2, double v1v2, nfu_status * status)
Definition at line 108 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 108 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, BTOF::length, n, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_areDomainsMutual(), ptwXY_free(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_union(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXYPoint_s::x, ptwXYPoint_s::y, and y.
Referenced by ptwXY_add_ptwXY(), ptwXY_mul_ptwXY(), and ptwXY_sub_ptwXY().
nfu_status ptwXY_div_doubleFrom (ptwXYPoints * ptwXY, double value)
Definition at line 44 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 44 of file ptwXY_binaryOperators.cc
References nfu_divByZero, ptwXY_slopeOffset(), and ptwXYPoints_s::status.
nfu_status ptwXY_div_fromDouble (ptwXYPoints * ptwXY, double value)
Definition at line 53 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 53 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, ptwXYOverflowPoint_s::next, nfu_divByZero, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXY_interpolationOther, ptwXYPoints_s::status, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_div_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int safeDivide)
Definition at line 288 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 288 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, k, BTOF::length, ptwXYPoints_s::length, n, nfu_divByZero, nfu_getNAN(), nfu_isNAN(), nfu_Okay, nfu_otherInterpolation, nfu_XOutsideDomain, ptwXYPoints_s::points, ptwXY_areDomainsMutual(), ptwXY_div_ptwXY_forFlats(), ptwXY_div_s_ptwXY(), ptwXY_free(), ptwXY_getSlopeAtX(), ptwXY_getValueAtX(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXY_union(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXY_update_biSectionMax(), s1, v1, v2, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
static ptwXYPoints * ptwXY_div_ptwXY_forFlats (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int safeDivide) static
Definition at line 480 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 480 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, BTOF::length, n, nfu_divByZero, nfu_invalidInterpolation, nfu_Okay, ptwXYPoints_s::points, ptwXY_free(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_union(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXYPoint_s::x, ptwXYPoint_s::y, and y.
Referenced by ptwXY_div_ptwXY().
static nfu_status ptwXY_div_s_ptwXY (ptwXYPoints * n, ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, double x1, double y1, double x2, double y2, int level, int isNAN1, int isNAN2) static
Definition at line 432 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 432 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, ClosestAllowXFactor, DBL_EPSILON, dx, nfu_Okay, ptwXY_getValueAtX(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_setValueAtX(), v, v1, v2, x, x1, x2, and y.
Referenced by ptwXY_div_ptwXY().
static nfu_status ptwXY_getValueAtX_ignore_XOutsideDomainError (ptwXYPoints * ptwXY1, double x, double * y) static
Definition at line 512 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 512 of file ptwXY_binaryOperators.cc
References nfu_Okay, nfu_XOutsideDomain, and ptwXY_getValueAtX().
Referenced by ptwXY_binary_ptwXY(), ptwXY_div_ptwXY(), ptwXY_div_ptwXY_forFlats(), ptwXY_div_s_ptwXY(), ptwXY_mul2_ptwXY(), and ptwXY_mul2_s_ptwXY().
nfu_status ptwXY_mod (ptwXYPoints * ptwXY, double m, int pythonMod)
Definition at line 76 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 76 of file ptwXY_binaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_divByZero, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXY_mod2(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
static double ptwXY_mod2 (double v, double m, int pythonMod) static
Definition at line 92 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 92 of file ptwXY_binaryOperators.cc
References r.
Referenced by ptwXY_mod().
ptwXYPoints* ptwXY_mul2_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 187 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 187 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, n, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_free(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_mul2_s_ptwXY(), ptwXY_mul_ptwXY(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXY_update_biSectionMax(), v1, v2, ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y1, and y2.
static nfu_status ptwXY_mul2_s_ptwXY (ptwXYPoints * n, ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, double x1, double y1, double x2, double y2, int level) static
Definition at line 251 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 251 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, ClosestAllowXFactor, DBL_EPSILON, dx, nfu_Okay, ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_setValueAtX(), v1, v2, x, x1, x2, and y.
Referenced by ptwXY_mul2_ptwXY().
nfu_status ptwXY_mul_double (ptwXYPoints * ptwXY, double value)
Definition at line 43 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 43 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
ptwXYPoints* ptwXY_mul_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 171 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 171 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::length, ptwXY_binary_ptwXY(), and ptwXY_clone().
Referenced by ptwXY_mul2_ptwXY().
nfu_status ptwXY_slopeOffset (ptwXYPoints * ptwXY, double slope, double offset)
Definition at line 25 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 25 of file ptwXY_binaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_Okay, offset, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
Referenced by ptwXY_add_double(), ptwXY_div_doubleFrom(), ptwXY_mul_double(), ptwXY_sub_doubleFrom(), and ptwXY_sub_fromDouble().
nfu_status ptwXY_sub_doubleFrom (ptwXYPoints * ptwXY, double value)
Definition at line 41 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 41 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
nfu_status ptwXY_sub_fromDouble (ptwXYPoints * ptwXY, double value)
Definition at line 42 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 42 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
ptwXYPoints* ptwXY_sub_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 154 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 154 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::length, nfu_Okay, ptwXY_binary_ptwXY(), ptwXY_clone(), ptwXY_free(), and ptwXY_neg().