ECCE @ EIC Software: G4PhantomParameterisation Class Reference
G4PhantomParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PhantomParameterisation.hh>
Public Member Functions
G4PhantomParameterisation ()
~G4PhantomParameterisation ()
virtual void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void BuildContainerSolid (G4VPhysicalVolume *pPhysicalVol)
void BuildContainerSolid (G4VSolid *pMotherSolid)
virtual G4int GetReplicaNo (const G4ThreeVector &localPoint, const G4ThreeVector &localDir)
void SetMaterials (std::vector< G4Material * > &mates)
void SetMaterialIndices (size_t *matInd)
void SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
void SetNoVoxel (size_t nx, size_t ny, size_t nz)
G4double GetVoxelHalfX () const
G4double GetVoxelHalfY () const
G4double GetVoxelHalfZ () const
size_t GetNoVoxelX () const
size_t GetNoVoxelY () const
size_t GetNoVoxelZ () const
size_t GetNoVoxel () const
std::vector< G4Material * > GetMaterials () const
size_t * GetMaterialIndices () const
G4VSolid * GetContainerSolid () const
G4ThreeVector GetTranslation (const G4int copyNo) const
G4bool SkipEqualMaterials () const
void SetSkipEqualMaterials (G4bool skip)
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Protected Attributes
G4double fVoxelHalfX = 0.0
G4double fVoxelHalfY = 0.0
G4double fVoxelHalfZ = 0.0
size_t fNoVoxelX = 0
size_t fNoVoxelY = 0
size_t fNoVoxelZ = 0
size_t fNoVoxelXY = 0
size_t fNoVoxel = 0
std::vector< G4Material * > fMaterials
size_t * fMaterialIndices = nullptr
G4VSolid * fContainerSolid = nullptr
G4double fContainerWallX =0.0
G4double fContainerWallY =0.0
G4double fContainerWallZ =0.0
G4double kCarTolerance
G4bool bSkipEqualMaterials = true
Private Member Functions
void ComputeVoxelIndices (const G4int copyNo, size_t &nx, size_t &ny, size_t &nz) const
void CheckCopyNo (const G4int copyNo) const
Detailed Description
Definition at line 68 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PhantomParameterisation.hh
Constructor & Destructor Documentation
G4PhantomParameterisation::G4PhantomParameterisation ()
Definition at line 42 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 42 of file G4PhantomParameterisation.cc
References G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), and kCarTolerance.
G4PhantomParameterisation::~G4PhantomParameterisation ()
Definition at line 49 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PhantomParameterisation.cc
Member Function Documentation
void G4PhantomParameterisation::BuildContainerSolid (G4VPhysicalVolume * pPhysicalVol)
Definition at line 56 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PhantomParameterisation.cc
References fContainerSolid, fContainerWallX, fContainerWallY, fContainerWallZ, fNoVoxelX, fNoVoxelY, fNoVoxelZ, fVoxelHalfX, fVoxelHalfY, fVoxelHalfZ, G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::GetSolid().
Referenced by DicomRegularDetectorConstruction::ConstructPhantom().
void G4PhantomParameterisation::BuildContainerSolid (G4VSolid * pMotherSolid)
Definition at line 68 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 68 of file G4PhantomParameterisation.cc
References fContainerSolid, fContainerWallX, fContainerWallY, fContainerWallZ, fNoVoxelX, fNoVoxelY, fNoVoxelZ, fVoxelHalfX, fVoxelHalfY, and fVoxelHalfZ.
void G4PhantomParameterisation::CheckCopyNo (const G4int copyNo) const private
Definition at line 380 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 380 of file G4PhantomParameterisation.cc
References FatalErrorInArgument, fNoVoxel, G4endl, G4Exception(), and message().
Referenced by ComputeMaterial(), ComputeVoxelIndices(), GetMaterialIndex(), and GetTranslation().
void G4PhantomParameterisation::CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Definition at line 176 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 176 of file G4PhantomParameterisation.cc
References FatalException, fContainerSolid, fNoVoxelX, fNoVoxelY, fNoVoxelZ, fVoxelHalfX, fVoxelHalfY, fVoxelHalfZ, G4endl, G4Exception(), G4VSolid::GetName(), JustWarning, kCarTolerance, and message().
Referenced by DicomRegularDetectorConstruction::ConstructPhantom().
void G4PhantomParameterisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 84 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 84 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 86 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 96 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 98 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 98 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 100 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 102 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 104 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 104 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 106 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 106 of file G4PhantomParameterisation.hh
void G4PhantomParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 108 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PhantomParameterisation.hh
G4Material * G4PhantomParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = nullptr) virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in G4PartialPhantomParameterisation, and DicomPhantomParameterisationColour.
Definition at line 120 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 120 of file G4PhantomParameterisation.cc
References CheckCopyNo(), fMaterials, and GetMaterialIndex().
Referenced by G4GMocrenFileSceneHandler::AddSolid(), DicomPhantomParameterisationColour::ComputeMaterial(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), and G4RegularNavigation::LevelLocate().
G4VSolid * G4PhantomParameterisation::ComputeSolid (const G4int , G4VPhysicalVolume * pPhysicalVol) virtual
Reimplemented from G4VPVParameterisation.
Definition at line 112 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 112 of file G4PhantomParameterisation.cc
References G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::GetSolid().
void G4PhantomParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Reimplemented in G4PartialPhantomParameterisation.
Definition at line 81 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 81 of file G4PhantomParameterisation.cc
References GetTranslation(), and G4VPhysicalVolume::SetTranslation().
Referenced by G4RegularNavigation::LevelLocate().
void G4PhantomParameterisation::ComputeVoxelIndices (const G4int copyNo, size_t & nx, size_t & ny, size_t & nz) const private
Definition at line 164 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 164 of file G4PhantomParameterisation.cc
References CheckCopyNo(), fNoVoxelX, fNoVoxelXY, and fNoVoxelY.
Referenced by GetTranslation().
G4VSolid* G4PhantomParameterisation::GetContainerSolid () const inline
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials().
G4Material * G4PhantomParameterisation::GetMaterial (size_t nx, size_t ny, size_t nz) const
Definition at line 151 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 151 of file G4PhantomParameterisation.cc
References fMaterials, and GetMaterialIndex().
Referenced by DicomIntersectVolume::SetNewValue(), and G4EnergySplitter::SplitEnergyInVolumes().
G4Material * G4PhantomParameterisation::GetMaterial (size_t copyNo) const
Definition at line 157 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 157 of file G4PhantomParameterisation.cc
References fMaterials, and GetMaterialIndex().
size_t G4PhantomParameterisation::GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
Definition at line 142 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 142 of file G4PhantomParameterisation.cc
References fNoVoxelX, and fNoVoxelXY.
Referenced by DicomPhantomParameterisationColour::ComputeMaterial(), ComputeMaterial(), GetMaterial(), and DicomIntersectVolume::SetNewValue().
size_t G4PhantomParameterisation::GetMaterialIndex (size_t copyNo) const
Definition at line 131 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 131 of file G4PhantomParameterisation.cc
References CheckCopyNo(), and fMaterialIndices.
size_t* G4PhantomParameterisation::GetMaterialIndices () const inline
std::vector<G4Material*> G4PhantomParameterisation::GetMaterials () const inline
Referenced by DicomIntersectVolume::SetNewValue().
size_t G4PhantomParameterisation::GetNoVoxel () const inline
Referenced by G4RegularNavigation::LevelLocate().
size_t G4PhantomParameterisation::GetNoVoxelX () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
size_t G4PhantomParameterisation::GetNoVoxelY () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
size_t G4PhantomParameterisation::GetNoVoxelZ () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
G4int G4PhantomParameterisation::GetReplicaNo (const G4ThreeVector & localPoint, const G4ThreeVector & localDir) virtual
Reimplemented in G4PartialPhantomParameterisation.
Definition at line 223 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 223 of file G4PhantomParameterisation.cc
References FatalErrorInArgument, fContainerSolid, fContainerWallX, fContainerWallY, fContainerWallZ, fNoVoxelX, fNoVoxelXY, fNoVoxelY, fNoVoxelZ, fVoxelHalfX, fVoxelHalfY, fVoxelHalfZ, G4endl, G4Exception(), G4VSolid::GetName(), G4VSolid::Inside(), JustWarning, kCarTolerance, kOutside, message(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4RegularNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), and G4RegularNavigation::LevelLocate().
G4ThreeVector G4PhantomParameterisation::GetTranslation (const G4int copyNo) const
Definition at line 93 of file G4PhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 93 of file G4PhantomParameterisation.cc
References CheckCopyNo(), ComputeVoxelIndices(), fContainerWallX, fContainerWallY, fContainerWallZ, fVoxelHalfX, fVoxelHalfY, and fVoxelHalfZ.
Referenced by G4RegularNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), and ComputeTransformation().
G4double G4PhantomParameterisation::GetVoxelHalfX () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
G4double G4PhantomParameterisation::GetVoxelHalfY () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
G4double G4PhantomParameterisation::GetVoxelHalfZ () const inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and DicomIntersectVolume::SetNewValue().
void G4PhantomParameterisation::SetMaterialIndices (size_t * matInd) inline
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
void G4PhantomParameterisation::SetMaterials (std::vector< G4Material * > & mates) inline
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
void G4PhantomParameterisation::SetNoVoxel (size_t nx, size_t ny, size_t nz)
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
void G4PhantomParameterisation::SetSkipEqualMaterials (G4bool skip)
Referenced by DicomPartialDetectorConstruction::ConstructPhantom(), and DicomPhantomParameterisationColour::DicomPhantomParameterisationColour().
void G4PhantomParameterisation::SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
Referenced by DicomRegularDetectorConstruction::ConstructPhantom(), and DicomPartialDetectorConstruction::ConstructPhantom().
G4bool G4PhantomParameterisation::SkipEqualMaterials () const
Referenced by G4RegularNavigation::ComputeStepSkippingEqualMaterials().
Member Data Documentation
G4bool G4PhantomParameterisation::bSkipEqualMaterials = true protected
Definition at line 192 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 192 of file G4PhantomParameterisation.hh
G4VSolid* G4PhantomParameterisation::fContainerSolid = nullptr protected
Definition at line 182 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 182 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), CheckVoxelsFillContainer(), and GetReplicaNo().
G4double G4PhantomParameterisation::fContainerWallX =0.0 protected
Definition at line 186 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 186 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
G4double G4PhantomParameterisation::fContainerWallY =0.0 protected
Definition at line 186 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 186 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
G4double G4PhantomParameterisation::fContainerWallZ =0.0 protected
Definition at line 186 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 186 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
size_t* G4PhantomParameterisation::fMaterialIndices = nullptr protected
Definition at line 179 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 179 of file G4PhantomParameterisation.hh
Referenced by G4PartialPhantomParameterisation::GetMaterialIndex(), and GetMaterialIndex().
std::vector<G4Material*> G4PhantomParameterisation::fMaterials protected
Definition at line 177 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 177 of file G4PhantomParameterisation.hh
Referenced by G4PartialPhantomParameterisation::ComputeMaterial(), ComputeMaterial(), G4PartialPhantomParameterisation::GetMaterial(), and GetMaterial().
size_t G4PhantomParameterisation::fNoVoxel = 0 protected
Definition at line 174 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 174 of file G4PhantomParameterisation.hh
Referenced by G4PartialPhantomParameterisation::CheckCopyNo(), and CheckCopyNo().
size_t G4PhantomParameterisation::fNoVoxelX = 0 protected
Definition at line 170 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), ComputeVoxelIndices(), G4PartialPhantomParameterisation::GetMaterialIndex(), GetMaterialIndex(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
size_t G4PhantomParameterisation::fNoVoxelXY = 0 protected
Definition at line 172 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 172 of file G4PhantomParameterisation.hh
Referenced by ComputeVoxelIndices(), G4PartialPhantomParameterisation::GetMaterialIndex(), GetMaterialIndex(), and GetReplicaNo().
size_t G4PhantomParameterisation::fNoVoxelY = 0 protected
Definition at line 170 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::ComputeVoxelIndices(), ComputeVoxelIndices(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
size_t G4PhantomParameterisation::fNoVoxelZ = 0 protected
Definition at line 170 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
G4double G4PhantomParameterisation::fVoxelHalfX = 0.0 protected
Definition at line 168 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
G4double G4PhantomParameterisation::fVoxelHalfY = 0.0 protected
Definition at line 168 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
G4double G4PhantomParameterisation::fVoxelHalfZ = 0.0 protected
Definition at line 168 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PhantomParameterisation.hh
Referenced by BuildContainerSolid(), G4PartialPhantomParameterisation::BuildContainerWalls(), CheckVoxelsFillContainer(), G4PartialPhantomParameterisation::GetReplicaNo(), GetReplicaNo(), G4PartialPhantomParameterisation::GetTranslation(), and GetTranslation().
G4double G4PhantomParameterisation::kCarTolerance protected
Definition at line 189 of file G4PhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 189 of file G4PhantomParameterisation.hh
Referenced by CheckVoxelsFillContainer(), G4PhantomParameterisation(), G4PartialPhantomParameterisation::GetReplicaNo(), and GetReplicaNo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PhantomParameterisation.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4PhantomParameterisation.cc