ECCE @ EIC Software: G4AdjointSteppingAction Class Reference
G4AdjointSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4AdjointSteppingAction.hh>
Public Member Functions
G4AdjointSteppingAction ()
~G4AdjointSteppingAction ()
void UserSteppingAction (const G4Step *)
void SetExtSourceEMax (G4double Emax)
void SetStartEvent (G4bool aBool)
G4bool GetDidAdjParticleReachTheExtSource ()
G4ThreeVector GetLastMomentum ()
G4ThreeVector GetLastPosition ()
G4double GetLastEkin ()
G4double GetLastWeight ()
void SetPrimWeight (G4double weight)
G4ParticleDefinition * GetLastPartDef ()
void SetUserAdjointSteppingAction (G4UserSteppingAction *anAction)
void SetUserForwardSteppingAction (G4UserSteppingAction *anAction)
void SetAdjointTrackingMode (G4bool aBool)
void ResetDidOneAdjPartReachExtSourceDuringEvent ()
void SetAdjointGeantinoTrackingMode (G4bool aBool)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
G4double ext_sourceEMax
G4AdjointCrossSurfChecker * theG4AdjointCrossSurfChecker
G4bool start_event
G4bool did_adj_part_reach_ext_source
G4bool did_one_adj_part_reach_ext_source_during_event
G4ThreeVector last_momentum
G4ThreeVector last_pos
G4double last_ekin
G4double last_weight
G4double prim_weight
G4ParticleDefinition * last_part_def
G4UserSteppingAction * theUserAdjointSteppingAction
G4UserSteppingAction * theUserFwdSteppingAction
G4bool is_adjoint_tracking_mode
G4bool is_adjoint_geantino_tracking_mode
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 68 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AdjointSteppingAction.hh
Constructor & Destructor Documentation
G4AdjointSteppingAction::G4AdjointSteppingAction ()
Definition at line 43 of file G4AdjointSteppingAction.cc.
View newest version in sPHENIX GitHub at line 43 of file G4AdjointSteppingAction.cc
References G4AdjointCrossSurfChecker::GetInstance(), and theG4AdjointCrossSurfChecker.
G4AdjointSteppingAction::~G4AdjointSteppingAction ()
Definition at line 53 of file G4AdjointSteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file G4AdjointSteppingAction.cc
Member Function Documentation
G4bool G4AdjointSteppingAction::GetDidAdjParticleReachTheExtSource () inline
Definition at line 78 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AdjointSteppingAction.hh
References did_adj_part_reach_ext_source.
Referenced by G4AdjointTrackingAction::PostUserTrackingAction().
G4double G4AdjointSteppingAction::GetLastEkin () inline
Definition at line 81 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 81 of file G4AdjointSteppingAction.hh
References last_ekin.
Referenced by G4AdjointTrackingAction::PostUserTrackingAction(), and G4AdjointSimManager::RegisterAtEndOfAdjointTrack().
G4ThreeVector G4AdjointSteppingAction::GetLastMomentum () inline
Definition at line 79 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 79 of file G4AdjointSteppingAction.hh
References last_momentum.
Referenced by G4AdjointTrackingAction::PostUserTrackingAction(), and G4AdjointSimManager::RegisterAtEndOfAdjointTrack().
G4ParticleDefinition* G4AdjointSteppingAction::GetLastPartDef () inline
Definition at line 84 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 84 of file G4AdjointSteppingAction.hh
References last_part_def.
Referenced by G4AdjointTrackingAction::PostUserTrackingAction(), and G4AdjointSimManager::RegisterAtEndOfAdjointTrack().
G4ThreeVector G4AdjointSteppingAction::GetLastPosition () inline
Definition at line 80 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 80 of file G4AdjointSteppingAction.hh
References last_pos.
Referenced by G4AdjointTrackingAction::PostUserTrackingAction(), and G4AdjointSimManager::RegisterAtEndOfAdjointTrack().
G4double G4AdjointSteppingAction::GetLastWeight () inline
Definition at line 82 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 82 of file G4AdjointSteppingAction.hh
References last_weight.
Referenced by G4AdjointTrackingAction::PostUserTrackingAction(), and G4AdjointSimManager::RegisterAtEndOfAdjointTrack().
void G4AdjointSteppingAction::ResetDidOneAdjPartReachExtSourceDuringEvent () inline
Definition at line 90 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 90 of file G4AdjointSteppingAction.hh
References did_one_adj_part_reach_ext_source_during_event.
Referenced by G4AdjointSimManager::ResetDidOneAdjPartReachExtSourceDuringEvent().
void G4AdjointSteppingAction::SetAdjointGeantinoTrackingMode (G4bool aBool) inline
Definition at line 92 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 92 of file G4AdjointSteppingAction.hh
References is_adjoint_geantino_tracking_mode.
void G4AdjointSteppingAction::SetAdjointTrackingMode (G4bool aBool) inline
Definition at line 89 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 89 of file G4AdjointSteppingAction.hh
References is_adjoint_tracking_mode.
Referenced by G4AdjointTrackingAction::PreUserTrackingAction().
void G4AdjointSteppingAction::SetExtSourceEMax (G4double Emax) inline
Definition at line 76 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AdjointSteppingAction.hh
References Emax, and ext_sourceEMax.
Referenced by G4AdjointSimManager::SetExtSourceEmax().
void G4AdjointSteppingAction::SetPrimWeight (G4double weight) inline
Definition at line 83 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4AdjointSteppingAction.hh
References prim_weight, and weight.
Referenced by G4AdjointTrackingAction::PreUserTrackingAction(), and G4AdjointSimManager::RegisterAdjointPrimaryWeight().
void G4AdjointSteppingAction::SetStartEvent (G4bool aBool) inline
Definition at line 77 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointSteppingAction.hh
References start_event.
void G4AdjointSteppingAction::SetUserAdjointSteppingAction (G4UserSteppingAction * anAction) inline
Definition at line 85 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointSteppingAction.hh
References theUserAdjointSteppingAction.
Referenced by G4AdjointSimManager::SetAdjointSteppingAction().
void G4AdjointSteppingAction::SetUserForwardSteppingAction (G4UserSteppingAction * anAction) inline
Definition at line 87 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 87 of file G4AdjointSteppingAction.hh
References theUserFwdSteppingAction.
Referenced by G4AdjointSimManager::DefineUserActions().
void G4AdjointSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 58 of file G4AdjointSteppingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file G4AdjointSteppingAction.cc
References G4AdjointCrossSurfChecker::CrossingOneOfTheRegisteredSurface(), did_adj_part_reach_ext_source, did_one_adj_part_reach_ext_source_during_event, ext_sourceEMax, fStopAndKill, fWorldBoundary, G4ParticleDefinition::GetBaryonNumber(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetMomentum(), G4ParticleDefinition::GetParticleType(), G4Step::GetPostStepPoint(), G4StepPoint::GetStepStatus(), G4Step::GetTrack(), G4Track::GetWeight(), is_adjoint_tracking_mode, last_ekin, last_momentum, last_part_def, last_pos, last_weight, G4Track::SetTrackStatus(), theG4AdjointCrossSurfChecker, theUserAdjointSteppingAction, theUserFwdSteppingAction, and G4UserSteppingAction::UserSteppingAction().
Member Data Documentation
G4bool G4AdjointSteppingAction::did_adj_part_reach_ext_source private
Definition at line 99 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AdjointSteppingAction.hh
Referenced by GetDidAdjParticleReachTheExtSource(), and UserSteppingAction().
G4bool G4AdjointSteppingAction::did_one_adj_part_reach_ext_source_during_event private
Definition at line 100 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AdjointSteppingAction.hh
Referenced by ResetDidOneAdjPartReachExtSourceDuringEvent(), and UserSteppingAction().
G4double G4AdjointSteppingAction::ext_sourceEMax private
Definition at line 95 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AdjointSteppingAction.hh
Referenced by SetExtSourceEMax(), and UserSteppingAction().
G4bool G4AdjointSteppingAction::is_adjoint_geantino_tracking_mode private
Definition at line 109 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AdjointSteppingAction.hh
Referenced by SetAdjointGeantinoTrackingMode().
G4bool G4AdjointSteppingAction::is_adjoint_tracking_mode private
Definition at line 108 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointSteppingAction.hh
Referenced by SetAdjointTrackingMode(), and UserSteppingAction().
G4double G4AdjointSteppingAction::last_ekin private
Definition at line 102 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AdjointSteppingAction.hh
Referenced by GetLastEkin(), and UserSteppingAction().
G4ThreeVector G4AdjointSteppingAction::last_momentum private
Definition at line 101 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AdjointSteppingAction.hh
Referenced by GetLastMomentum(), and UserSteppingAction().
G4ParticleDefinition* G4AdjointSteppingAction::last_part_def private
Definition at line 105 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AdjointSteppingAction.hh
Referenced by GetLastPartDef(), and UserSteppingAction().
G4ThreeVector G4AdjointSteppingAction::last_pos private
Definition at line 101 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AdjointSteppingAction.hh
Referenced by GetLastPosition(), and UserSteppingAction().
G4double G4AdjointSteppingAction::last_weight private
Definition at line 103 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AdjointSteppingAction.hh
Referenced by GetLastWeight(), and UserSteppingAction().
G4double G4AdjointSteppingAction::prim_weight private
Definition at line 104 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointSteppingAction.hh
Referenced by SetPrimWeight().
G4bool G4AdjointSteppingAction::start_event private
Definition at line 97 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AdjointSteppingAction.hh
Referenced by SetStartEvent().
G4AdjointCrossSurfChecker* G4AdjointSteppingAction::theG4AdjointCrossSurfChecker private
Definition at line 96 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AdjointSteppingAction.hh
Referenced by G4AdjointSteppingAction(), and UserSteppingAction().
G4UserSteppingAction* G4AdjointSteppingAction::theUserAdjointSteppingAction private
Definition at line 106 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AdjointSteppingAction.hh
Referenced by SetUserAdjointSteppingAction(), and UserSteppingAction().
G4UserSteppingAction* G4AdjointSteppingAction::theUserFwdSteppingAction private
Definition at line 107 of file G4AdjointSteppingAction.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointSteppingAction.hh
Referenced by SetUserForwardSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4AdjointSteppingAction.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4AdjointSteppingAction.cc