ECCE @ EIC Software: G4QuarkExchange Class Reference
G4QuarkExchange Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4QuarkExchange.hh>
Public Member Functions
G4QuarkExchange ()
~G4QuarkExchange ()
G4bool ExciteParticipants (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner) const
Private Member Functions
G4QuarkExchange (const G4QuarkExchange &right)
G4ThreeVector GaussianPt (G4double widthSquare, G4double maxPtSquare) const
const G4QuarkExchange & operator= (const G4QuarkExchange &right)
G4bool operator== (const G4QuarkExchange &right) const
G4bool operator!= (const G4QuarkExchange &right) const
Detailed Description
Definition at line 48 of file G4QuarkExchange.hh.
View newest version in sPHENIX GitHub at line 48 of file G4QuarkExchange.hh
Constructor & Destructor Documentation
G4QuarkExchange::G4QuarkExchange ()
Definition at line 53 of file G4QuarkExchange.cc.
View newest version in sPHENIX GitHub at line 53 of file G4QuarkExchange.cc
G4QuarkExchange::~G4QuarkExchange ()
Definition at line 55 of file G4QuarkExchange.cc.
View newest version in sPHENIX GitHub at line 55 of file G4QuarkExchange.cc
G4QuarkExchange::G4QuarkExchange (const G4QuarkExchange & right) private
Member Function Documentation
G4bool G4QuarkExchange::ExciteParticipants (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner) const
Definition at line 58 of file G4QuarkExchange.cc.
View newest version in sPHENIX GitHub at line 58 of file G4QuarkExchange.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), G4cerr, G4cout, G4endl, G4UniformRand, GaussianPt(), G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4Parton::GetDefinition(), G4Pow::GetInstance(), G4VSplitableHadron::GetNextParton(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, G4Pow::powA(), CLHEP::HepLorentzVector::rotateY(), CLHEP::HepLorentzVector::rotateZ(), S(), G4VSplitableHadron::Set4Momentum(), G4Parton::SetDefinition(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SplitUp(), sqr(), CLHEP::HepLorentzRotation::transform(), CLHEP::HepLorentzVector::transform(), CLHEP::HepLorentzVector::vect(), x, and y.
Referenced by G4QGSParticipants::PerformDiffractiveCollisions().
G4ThreeVector G4QuarkExchange::GaussianPt (G4double widthSquare, G4double maxPtSquare) const private
Definition at line 370 of file G4QuarkExchange.cc.
View newest version in sPHENIX GitHub at line 370 of file G4QuarkExchange.cc
References G4Log(), G4UniformRand, phi, pt2, and twopi.
Referenced by ExciteParticipants().
G4bool G4QuarkExchange::operator!= (const G4QuarkExchange & right) const private
const G4QuarkExchange& G4QuarkExchange::operator= (const G4QuarkExchange & right) private
G4bool G4QuarkExchange::operator== (const G4QuarkExchange & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4QuarkExchange.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4QuarkExchange.cc