ECCE @ EIC Software: DetectorBari05 Class Reference
DetectorBari05 Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/DetectorBari05.hh>
Public Member Functions
DetectorBari05 ()
~DetectorBari05 ()
G4VPhysicalVolume * Construct ()
RadiatorDescription * GetRadiatorDescription () const
Private Attributes
RadiatorDescription * fRadiatorDescription
Detailed Description
Definition at line 44 of file DetectorBari05.hh.
View newest version in sPHENIX GitHub at line 44 of file DetectorBari05.hh
Constructor & Destructor Documentation
DetectorBari05::DetectorBari05 ()
Definition at line 54 of file DetectorBari05.cc.
View newest version in sPHENIX GitHub at line 54 of file DetectorBari05.cc
DetectorBari05::~DetectorBari05 ()
Definition at line 60 of file DetectorBari05.cc.
View newest version in sPHENIX GitHub at line 60 of file DetectorBari05.cc
Member Function Documentation
G4VPhysicalVolume * DetectorBari05::Construct (void)
Definition at line 68 of file DetectorBari05.cc.
View newest version in sPHENIX GitHub at line 68 of file DetectorBari05.cc
References G4SDManager::AddNewDetector(), G4Region::AddRootLogicalVolume(), cm, cm3, RadiatorDescription::fFoilMaterial, RadiatorDescription::fFoilNumber, RadiatorDescription::fFoilThickness, RadiatorDescription::fGasMaterial, RadiatorDescription::fGasThickness, RadiatorDescription::fLogicalVolume, fRadiatorDescription, G4cout, G4endl, G4Material::GetDensity(), Materials::GetInstance(), Materials::GetMaterial(), G4Material::GetName(), G4SDManager::GetSDMpointer(), mg, micrometer, mm, and G4LogicalVolume::SetSensitiveDetector().
RadiatorDescription* DetectorBari05::GetRadiatorDescription () const inline
Definition at line 54 of file DetectorBari05.hh.
View newest version in sPHENIX GitHub at line 54 of file DetectorBari05.hh
References fRadiatorDescription.
Member Data Documentation
RadiatorDescription* DetectorBari05::fRadiatorDescription private
Definition at line 58 of file DetectorBari05.hh.
View newest version in sPHENIX GitHub at line 58 of file DetectorBari05.hh
Referenced by Construct(), and GetRadiatorDescription().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/DetectorBari05.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/DetectorBari05.cc