ECCE @ EIC Software: G4tgrRotationMatrix Class Reference
G4tgrRotationMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrRotationMatrix.hh>
Public Member Functions
G4tgrRotationMatrix ()
~G4tgrRotationMatrix ()
G4tgrRotationMatrix (const std::vector< G4String > &wl)
const G4String & GetName ()
std::vector< G4double > & GetValues ()
Private Attributes
G4String theName
std::vector< G4double > theValues
G4RotMatInputType theInputType
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrRotationMatrix &obj)
Detailed Description
Definition at line 48 of file G4tgrRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 48 of file G4tgrRotationMatrix.hh
Constructor & Destructor Documentation
G4tgrRotationMatrix::G4tgrRotationMatrix ()
Definition at line 43 of file G4tgrRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgrRotationMatrix.cc
G4tgrRotationMatrix::~G4tgrRotationMatrix ()
Definition at line 50 of file G4tgrRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 50 of file G4tgrRotationMatrix.cc
G4tgrRotationMatrix::G4tgrRotationMatrix (const std::vector< G4String > & wl)
Definition at line 56 of file G4tgrRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 56 of file G4tgrRotationMatrix.cc
References deg, FatalException, G4cout, G4endl, G4Exception(), G4tgrUtils::GetDouble(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), rm3, rm6, rm9, theInputType, theName, and theValues.
Member Function Documentation
const G4String& G4tgrRotationMatrix::GetName (void) inline
Definition at line 59 of file G4tgrRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrRotationMatrix.hh
References theName.
Referenced by G4tgrRotationMatrixFactory::AddRotMatrix(), and G4tgbRotationMatrix::GetName().
std::vector<G4double>& G4tgrRotationMatrix::GetValues () inline
Definition at line 60 of file G4tgrRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 60 of file G4tgrRotationMatrix.hh
References theValues.
Referenced by G4tgbRotationMatrix::BuildG4RotMatrix().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrRotationMatrix & obj) friend
Definition at line 108 of file G4tgrRotationMatrix.cc.
View newest version in sPHENIX GitHub at line 108 of file G4tgrRotationMatrix.cc
Member Data Documentation
G4RotMatInputType G4tgrRotationMatrix::theInputType private
Definition at line 70 of file G4tgrRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgrRotationMatrix.hh
Referenced by G4tgrRotationMatrix(), and operator<<().
G4String G4tgrRotationMatrix::theName private
Definition at line 66 of file G4tgrRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgrRotationMatrix.hh
Referenced by G4tgrRotationMatrix(), GetName(), and operator<<().
std::vector<G4double> G4tgrRotationMatrix::theValues private
Definition at line 67 of file G4tgrRotationMatrix.hh.
View newest version in sPHENIX GitHub at line 67 of file G4tgrRotationMatrix.hh
Referenced by G4tgrRotationMatrix(), GetValues(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrRotationMatrix.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrRotationMatrix.cc