ECCE @ EIC Software: MCTruthManager Class Reference
MCTruthManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/MCTruthManager.hh>
Public Member Functions
void NewEvent ()
HepMC::GenEvent * GetCurrentEvent () const
void PrintEvent ()
void AddParticle (G4LorentzVector &, G4LorentzVector &, G4LorentzVector &, G4int, G4int, G4int, G4bool)
void SetConfig (MCTruthConfig *c)
MCTruthConfig * GetConfig () const
Static Public Member Functions
static MCTruthManager * GetInstance ()
Protected Member Functions
MCTruthManager ()
virtual ~MCTruthManager ()
Private Member Functions
void PrintTree (HepMC::GenParticle *, G4String)
Private Attributes
HepMC::GenEvent * fEvent
std::vector< G4int > fPrimarybarcodes
std::map< G4int, G4int > fSegmentations
MCTruthConfig * fConfig
Detailed Description
Definition at line 51 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 51 of file MCTruthManager.hh
Constructor & Destructor Documentation
MCTruthManager::MCTruthManager () protected
Definition at line 50 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 50 of file MCTruthManager.cc
Referenced by GetInstance().
MCTruthManager::~MCTruthManager () protected virtual
Definition at line 55 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 55 of file MCTruthManager.cc
Member Function Documentation
void MCTruthManager::AddParticle (G4LorentzVector & momentum, G4LorentzVector & prodpos, G4LorentzVector & endpos, G4int pdg_id, G4int partID, G4int motherID, G4bool directParent)
Definition at line 81 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 81 of file MCTruthManager.cc
References fEvent, fPrimarybarcodes, fSegmentations, G4cerr, G4endl, it, particle, CLHEP::HepLorentzVector::t(), CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
MCTruthConfig* MCTruthManager::GetConfig () const inline
Definition at line 66 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 66 of file MCTruthManager.hh
References fConfig.
Referenced by MCTruthTrackingAction::TrackToBeStored().
HepMC::GenEvent* MCTruthManager::GetCurrentEvent () const inline
Definition at line 59 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 59 of file MCTruthManager.hh
References fEvent.
MCTruthManager * MCTruthManager::GetInstance (void) static
Definition at line 60 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 60 of file MCTruthManager.cc
References instance, and MCTruthManager().
Referenced by MCTruthEventAction::BeginOfEventAction(), MCTruthEventAction::EndOfEventAction(), main(), MCTruthTrackingAction::PostUserTrackingAction(), and MCTruthTrackingAction::TrackToBeStored().
void MCTruthManager::NewEvent ()
Definition at line 71 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 71 of file MCTruthManager.cc
References fEvent.
Referenced by MCTruthEventAction::BeginOfEventAction().
void MCTruthManager::PrintEvent ()
Definition at line 264 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 264 of file MCTruthManager.cc
References fEvent, fPrimarybarcodes, and PrintTree().
Referenced by MCTruthEventAction::EndOfEventAction().
void MCTruthManager::PrintTree (HepMC::GenParticle * particle, G4String offset) private
Definition at line 279 of file MCTruthManager.cc.
View newest version in sPHENIX GitHub at line 279 of file MCTruthManager.cc
References G4cout, G4endl, it, and part.
Referenced by PrintEvent().
void MCTruthManager::SetConfig (MCTruthConfig * c) inline
Definition at line 65 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 65 of file MCTruthManager.hh
References c, and fConfig.
Referenced by main().
Member Data Documentation
MCTruthConfig* MCTruthManager::fConfig private
Definition at line 90 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 90 of file MCTruthManager.hh
Referenced by GetConfig(), and SetConfig().
HepMC::GenEvent* MCTruthManager::fEvent private
Definition at line 76 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 76 of file MCTruthManager.hh
Referenced by AddParticle(), GetCurrentEvent(), NewEvent(), and PrintEvent().
std::vector<G4int> MCTruthManager::fPrimarybarcodes private
Definition at line 80 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 80 of file MCTruthManager.hh
Referenced by AddParticle(), and PrintEvent().
std::map<G4int,G4int> MCTruthManager::fSegmentations private
Definition at line 86 of file MCTruthManager.hh.
View newest version in sPHENIX GitHub at line 86 of file MCTruthManager.hh
Referenced by AddParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/MCTruthManager.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/src/MCTruthManager.cc