ECCE @ EIC Software: G4ChordFinderDelegate< Driver > Class Template Reference
G4ChordFinderDelegate< Driver > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4ChordFinderDelegate.hh>
Public Member Functions
virtual ~G4ChordFinderDelegate ()
G4double AdvanceChordLimitedImpl (G4FieldTrack &track, G4double hstep, G4double eps, G4double chordDistance)
void ResetStepEstimate ()
void TestChordPrint (G4int noTrials, G4int lastStepTrial, G4double dChordStep, G4double fDeltaChord, G4double nextStepTrial)
G4int GetNoCalls ()
G4int GetNoTrials ()
G4int GetNoMaxTrials ()
void SetFractions_Last_Next (G4double fractLast=0.90, G4double fractNext=0.95)
void SetFirstFraction (G4double fractFirst)
G4double GetFirstFraction ()
G4double GetFractionLast ()
G4double GetFractionNextEstimate ()
G4double GetLastStepEstimateUnc ()
void SetLastStepEstimateUnc (G4double stepEst)
Private Member Functions
Driver & GetDriver ()
G4double FindNextChord (const G4FieldTrack &yStart, G4double stepMax, G4double epsStep, G4double chordDistance, G4FieldTrack &yEnd, G4double &dyErrPos, G4double &pStepForAccuracy)
G4double NewStep (G4double stepTrialOld, G4double dChordStep, G4double fDeltaChord, G4double &stepEstimate_Unconstrained)
void AccumulateStatistics (G4int noTrials)
void PrintStatistics ()
Private Attributes
G4double fFirstFraction = 0.999
G4double fFractionLast = 1.0
G4double fFractionNextEstimate = 0.98
G4double fLastStepEstimate_Unconstrained = DBL_MAX
G4int fTotalNoTrials = 0
G4int fNoCalls = 0
G4int fmaxTrials = 0
Detailed Description
template<class Driver>
class G4ChordFinderDelegate< Driver >
Definition at line 41 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ChordFinderDelegate.hh
Constructor & Destructor Documentation
template<class Driver> virtual G4ChordFinderDelegate< Driver >::~G4ChordFinderDelegate () virtual
Member Function Documentation
template<class Driver> void G4ChordFinderDelegate< Driver >::AccumulateStatistics (G4int noTrials) private
template<class Driver> G4double G4ChordFinderDelegate< Driver >::AdvanceChordLimitedImpl (G4FieldTrack & track, G4double hstep, G4double eps, G4double chordDistance)
Referenced by G4IntegrationDriver< G4BulirschStoer >::AdvanceChordLimited().
template<class Driver> G4double G4ChordFinderDelegate< Driver >::FindNextChord (const G4FieldTrack & yStart, G4double stepMax, G4double epsStep, G4double chordDistance, G4FieldTrack & yEnd, G4double & dyErrPos, G4double & pStepForAccuracy) private
template<class Driver> Driver& G4ChordFinderDelegate< Driver >::GetDriver () private
template<class Driver> G4double G4ChordFinderDelegate< Driver >::GetFirstFraction ()
template<class Driver> G4double G4ChordFinderDelegate< Driver >::GetFractionLast ()
template<class Driver> G4double G4ChordFinderDelegate< Driver >::GetFractionNextEstimate ()
template<class Driver> G4double G4ChordFinderDelegate< Driver >::GetLastStepEstimateUnc ()
template<class Driver> G4int G4ChordFinderDelegate< Driver >::GetNoCalls ()
template<class Driver> G4int G4ChordFinderDelegate< Driver >::GetNoMaxTrials ()
template<class Driver> G4int G4ChordFinderDelegate< Driver >::GetNoTrials ()
template<class Driver> G4double G4ChordFinderDelegate< Driver >::NewStep (G4double stepTrialOld, G4double dChordStep, G4double fDeltaChord, G4double & stepEstimate_Unconstrained) private
template<class Driver> void G4ChordFinderDelegate< Driver >::PrintStatistics () private
template<class Driver> void G4ChordFinderDelegate< Driver >::ResetStepEstimate ()
Referenced by G4FSALIntegrationDriver< T >::OnStartTracking(), and G4IntegrationDriver< G4BulirschStoer >::OnStartTracking().
template<class Driver> void G4ChordFinderDelegate< Driver >::SetFirstFraction (G4double fractFirst)
template<class Driver> void G4ChordFinderDelegate< Driver >::SetFractions_Last_Next (G4double fractLast = 0.90, G4double fractNext = 0.95)
template<class Driver> void G4ChordFinderDelegate< Driver >::SetLastStepEstimateUnc (G4double stepEst)
template<class Driver> void G4ChordFinderDelegate< Driver >::TestChordPrint (G4int noTrials, G4int lastStepTrial, G4double dChordStep, G4double fDeltaChord, G4double nextStepTrial)
Member Data Documentation
template<class Driver> G4double G4ChordFinderDelegate< Driver >::fFirstFraction = 0.999 private
Definition at line 98 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ChordFinderDelegate.hh
template<class Driver> G4double G4ChordFinderDelegate< Driver >::fFractionLast = 1.0 private
Definition at line 99 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ChordFinderDelegate.hh
template<class Driver> G4double G4ChordFinderDelegate< Driver >::fFractionNextEstimate = 0.98 private
Definition at line 100 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ChordFinderDelegate.hh
template<class Driver> G4double G4ChordFinderDelegate< Driver >::fLastStepEstimate_Unconstrained = DBL_MAX private
Definition at line 101 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ChordFinderDelegate.hh
template<class Driver> G4int G4ChordFinderDelegate< Driver >::fmaxTrials = 0 private
Definition at line 105 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ChordFinderDelegate.hh
template<class Driver> G4int G4ChordFinderDelegate< Driver >::fNoCalls = 0 private
Definition at line 104 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ChordFinderDelegate.hh
template<class Driver> G4int G4ChordFinderDelegate< Driver >::fTotalNoTrials = 0 private
Definition at line 103 of file G4ChordFinderDelegate.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ChordFinderDelegate.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4ChordFinderDelegate.hh