ECCE @ EIC Software: G4HepRepMessenger Class Reference
G4HepRepMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepMessenger.hh>
Public Member Functions
virtual ~G4HepRepMessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
virtual G4String getFileDir ()
virtual G4String getFileName ()
virtual G4bool getOverwrite ()
virtual G4bool getCullInvisibles ()
virtual G4bool renderCylAsPolygons ()
virtual G4double getScale ()
virtual G4ThreeVector getCenter ()
virtual G4String getEventNumberSuffix ()
virtual G4bool appendGeometry ()
virtual G4bool addPointAttributes ()
virtual G4bool useSolids ()
virtual G4bool writeInvisibles ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Static Public Member Functions
static G4HepRepMessenger * GetInstance ()
Private Member Functions
G4HepRepMessenger ()
Private Attributes
G4UIdirectory * heprepDirectory
G4String fileDir
G4UIcmdWithAString * setFileDirCommand
G4String fileName
G4UIcmdWithAString * setFileNameCommand
G4bool overwrite
G4UIcmdWithABool * setOverwriteCommand
G4bool cullInvisibles
G4UIcmdWithABool * setCullInvisiblesCommand
G4bool cylAsPolygons
G4UIcmdWithABool * renderCylAsPolygonsCommand
G4double scale
G4UIcmdWithADouble * setScaleCommand
G4ThreeVector center
G4UIcmdWith3VectorAndUnit * setCenterCommand
G4String suffix
G4UIcmdWithAString * setEventNumberSuffixCommand
G4bool geometry
G4UIcmdWithABool * appendGeometryCommand
G4bool pointAttributes
G4UIcmdWithABool * addPointAttributesCommand
G4bool solids
G4UIcmdWithABool * useSolidsCommand
G4bool invisibles
Static Private Attributes
static G4HepRepMessenger * fpInstance = 0
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 40 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 40 of file G4HepRepMessenger.hh
Constructor & Destructor Documentation
G4HepRepMessenger::~G4HepRepMessenger () virtual
Definition at line 153 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 153 of file G4HepRepMessenger.cc
References addPointAttributesCommand, appendGeometryCommand, heprepDirectory, renderCylAsPolygonsCommand, setCenterCommand, setCullInvisiblesCommand, setEventNumberSuffixCommand, setFileDirCommand, setFileNameCommand, setOverwriteCommand, setScaleCommand, and useSolidsCommand.
G4HepRepMessenger::G4HepRepMessenger () private
Definition at line 39 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HepRepMessenger.cc
References addPointAttributesCommand, appendGeometryCommand, G4UIcommand::AvailableForStates(), G4UIcommand::ConvertToBool(), cullInvisibles, fileDir, fileName, G4State_Idle, heprepDirectory, overwrite, renderCylAsPolygonsCommand, setCenterCommand, setCullInvisiblesCommand, G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), setEventNumberSuffixCommand, setFileDirCommand, setFileNameCommand, G4UIcommand::SetGuidance(), setOverwriteCommand, G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4UIcommand::SetRange(), setScaleCommand, and useSolidsCommand.
Referenced by GetInstance().
Member Function Documentation
G4bool G4HepRepMessenger::addPointAttributes () virtual
Definition at line 258 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 258 of file G4HepRepMessenger.cc
References pointAttributes.
G4bool G4HepRepMessenger::appendGeometry () virtual
Definition at line 254 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 254 of file G4HepRepMessenger.cc
References geometry.
Referenced by G4HepRepSceneHandler::closeHepRep(), G4HepRepSceneHandler::getGeometryInstanceTree(), G4HepRepSceneHandler::getGeometryTypeTree(), and G4HepRepViewer::ShowView().
G4ThreeVector G4HepRepMessenger::getCenter () virtual
Definition at line 246 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 246 of file G4HepRepMessenger.cc
References center.
Referenced by G4HepRepFileXMLWriter::addPoint().
G4bool G4HepRepMessenger::getCullInvisibles () virtual
Definition at line 234 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 234 of file G4HepRepMessenger.cc
References cullInvisibles.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepFileSceneHandler::AddPrimitive(), and G4HepRepFileSceneHandler::AddSolid().
G4String G4HepRepMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 168 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 168 of file G4HepRepMessenger.cc
References addPointAttributesCommand, appendGeometryCommand, center, G4UIcommand::ConvertToString(), cullInvisibles, cylAsPolygons, fileDir, fileName, geometry, overwrite, pointAttributes, renderCylAsPolygonsCommand, scale, setCenterCommand, setCullInvisiblesCommand, setEventNumberSuffixCommand, setFileDirCommand, setFileNameCommand, setOverwriteCommand, setScaleCommand, solids, suffix, and useSolidsCommand.
G4String G4HepRepMessenger::getEventNumberSuffix () virtual
Definition at line 250 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 250 of file G4HepRepMessenger.cc
References suffix.
Referenced by G4HepRepSceneHandler::open().
G4String G4HepRepMessenger::getFileDir () virtual
Definition at line 222 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 222 of file G4HepRepMessenger.cc
References fileDir.
Referenced by G4HepRepFileSceneHandler::CheckFileOpen().
G4String G4HepRepMessenger::getFileName () virtual
Definition at line 226 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 226 of file G4HepRepMessenger.cc
References fileName.
Referenced by G4HepRepFileSceneHandler::CheckFileOpen().
G4HepRepMessenger * G4HepRepMessenger::GetInstance (void) static
Definition at line 33 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 33 of file G4HepRepMessenger.cc
References fpInstance, and G4HepRepMessenger().
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepFileXMLWriter::addPoint(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4HepRepSceneHandler::addTopLevelAttributes(), G4HepRepFileSceneHandler::CheckFileOpen(), G4HepRepSceneHandler::closeHepRep(), G4HepRepSceneHandler::dontWrite(), G4HepRep::G4HepRep(), G4HepRepFile::G4HepRepFile(), G4HepRepSceneHandler::getGeometryInstanceTree(), G4HepRepSceneHandler::getGeometryTypeTree(), G4HepRepSceneHandler::open(), and G4HepRepViewer::ShowView().
G4bool G4HepRepMessenger::getOverwrite () virtual
Definition at line 230 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 230 of file G4HepRepMessenger.cc
References overwrite.
Referenced by G4HepRepFileSceneHandler::CheckFileOpen().
G4double G4HepRepMessenger::getScale () virtual
Definition at line 242 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 242 of file G4HepRepMessenger.cc
References scale.
Referenced by G4HepRepFileXMLWriter::addPoint(), and G4HepRepFileSceneHandler::AddSolid().
G4bool G4HepRepMessenger::renderCylAsPolygons () virtual
Definition at line 238 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 238 of file G4HepRepMessenger.cc
References cylAsPolygons.
Referenced by G4HepRepFileSceneHandler::AddSolid().
void G4HepRepMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 196 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 196 of file G4HepRepMessenger.cc
References addPointAttributesCommand, appendGeometryCommand, center, cullInvisibles, cylAsPolygons, fileDir, fileName, geometry, G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADouble::GetNewDoubleValue(), overwrite, pointAttributes, renderCylAsPolygonsCommand, scale, setCenterCommand, setCullInvisiblesCommand, setEventNumberSuffixCommand, setFileDirCommand, setFileNameCommand, setOverwriteCommand, setScaleCommand, solids, suffix, and useSolidsCommand.
G4bool G4HepRepMessenger::useSolids () virtual
Definition at line 262 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 262 of file G4HepRepMessenger.cc
References solids.
Referenced by G4HepRepSceneHandler::AddSolid(), and G4HepRepSceneHandler::addTopLevelAttributes().
G4bool G4HepRepMessenger::writeInvisibles () virtual
Definition at line 266 of file G4HepRepMessenger.cc.
View newest version in sPHENIX GitHub at line 266 of file G4HepRepMessenger.cc
References invisibles.
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), and G4HepRepSceneHandler::dontWrite().
Member Data Documentation
G4UIcmdWithABool* G4HepRepMessenger::addPointAttributesCommand private
Definition at line 99 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 99 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithABool* G4HepRepMessenger::appendGeometryCommand private
Definition at line 96 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4ThreeVector G4HepRepMessenger::center private
Definition at line 89 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HepRepMessenger.hh
Referenced by getCenter(), GetCurrentValue(), and SetNewValue().
G4bool G4HepRepMessenger::cullInvisibles private
Definition at line 80 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), getCullInvisibles(), GetCurrentValue(), and SetNewValue().
G4bool G4HepRepMessenger::cylAsPolygons private
Definition at line 83 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HepRepMessenger.hh
Referenced by GetCurrentValue(), renderCylAsPolygons(), and SetNewValue().
G4String G4HepRepMessenger::fileDir private
Definition at line 71 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), getFileDir(), and SetNewValue().
G4String G4HepRepMessenger::fileName private
Definition at line 74 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), getFileName(), and SetNewValue().
G4HepRepMessenger * G4HepRepMessenger::fpInstance = 0 static private
Definition at line 67 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HepRepMessenger.hh
Referenced by GetInstance().
G4bool G4HepRepMessenger::geometry private
Definition at line 95 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 95 of file G4HepRepMessenger.hh
Referenced by appendGeometry(), GetCurrentValue(), and SetNewValue().
G4UIdirectory* G4HepRepMessenger::heprepDirectory private
Definition at line 69 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), and ~G4HepRepMessenger().
G4bool G4HepRepMessenger::invisibles private
Definition at line 104 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 104 of file G4HepRepMessenger.hh
Referenced by writeInvisibles().
G4bool G4HepRepMessenger::overwrite private
Definition at line 77 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), getOverwrite(), and SetNewValue().
G4bool G4HepRepMessenger::pointAttributes private
Definition at line 98 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 98 of file G4HepRepMessenger.hh
Referenced by addPointAttributes(), GetCurrentValue(), and SetNewValue().
G4UIcmdWithABool* G4HepRepMessenger::renderCylAsPolygonsCommand private
Definition at line 84 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4double G4HepRepMessenger::scale private
Definition at line 86 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HepRepMessenger.hh
Referenced by GetCurrentValue(), getScale(), and SetNewValue().
G4UIcmdWith3VectorAndUnit* G4HepRepMessenger::setCenterCommand private
Definition at line 90 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithABool* G4HepRepMessenger::setCullInvisiblesCommand private
Definition at line 81 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithAString* G4HepRepMessenger::setEventNumberSuffixCommand private
Definition at line 93 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithAString* G4HepRepMessenger::setFileDirCommand private
Definition at line 72 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithAString* G4HepRepMessenger::setFileNameCommand private
Definition at line 75 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithABool* G4HepRepMessenger::setOverwriteCommand private
Definition at line 78 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4UIcmdWithADouble* G4HepRepMessenger::setScaleCommand private
Definition at line 87 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
G4bool G4HepRepMessenger::solids private
Definition at line 101 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HepRepMessenger.hh
Referenced by GetCurrentValue(), SetNewValue(), and useSolids().
G4String G4HepRepMessenger::suffix private
Definition at line 92 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HepRepMessenger.hh
Referenced by GetCurrentValue(), getEventNumberSuffix(), and SetNewValue().
G4UIcmdWithABool* G4HepRepMessenger::useSolidsCommand private
Definition at line 102 of file G4HepRepMessenger.hh.
View newest version in sPHENIX GitHub at line 102 of file G4HepRepMessenger.hh
Referenced by G4HepRepMessenger(), GetCurrentValue(), SetNewValue(), and ~G4HepRepMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepMessenger.hh
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/G4HepRepMessenger.cc