ECCE @ EIC Software: pyG4Trap Namespace Reference
pyG4Trap Namespace Reference
Functions
G4Trap * f1_CreateTrap (const G4String &name)
G4Trap * f2_CreateTrap (const G4String &name, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
G4Trap * f3_CreateTrap (const G4String &name, const std::vector< G4ThreeVector > &pt)
G4Trap * f4_CreateTrap (const G4String &name, G4double pZ, G4double pY, G4double pX, G4double pLTX)
G4Trap * f5_CreateTrap (const G4String &name, G4double pDx1, G4double pDx2, G4double pDy1, G4double pDy2, G4double pDz)
G4Trap * f6_CreateTrap (const G4String &name, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Function Documentation
G4Trap* pyG4Trap::f1_CreateTrap (const G4String & name)
Definition at line 41 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4Trap.cc
Referenced by export_G4Trap().
G4Trap* pyG4Trap::f2_CreateTrap (const G4String & name, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
Definition at line 47 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 47 of file pyG4Trap.cc
Referenced by export_G4Trap().
G4Trap* pyG4Trap::f3_CreateTrap (const G4String & name, const std::vector< G4ThreeVector > & pt)
Definition at line 61 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 61 of file pyG4Trap.cc
Referenced by export_G4Trap().
G4Trap* pyG4Trap::f4_CreateTrap (const G4String & name, G4double pZ, G4double pY, G4double pX, G4double pLTX)
Definition at line 73 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 73 of file pyG4Trap.cc
Referenced by export_G4Trap().
G4Trap* pyG4Trap::f5_CreateTrap (const G4String & name, G4double pDx1, G4double pDx2, G4double pDy1, G4double pDy2, G4double pDz)
Definition at line 80 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 80 of file pyG4Trap.cc
Referenced by export_G4Trap().
G4Trap* pyG4Trap::f6_CreateTrap (const G4String & name, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
Definition at line 87 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 87 of file pyG4Trap.cc
Referenced by export_G4Trap().