ECCE @ EIC Software: G4RootMpiNtupleManager Class Reference
G4RootMpiNtupleManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/analysis/include/G4RootMpiNtupleManager.hh>
Public Member Functions
G4RootMpiNtupleManager (const G4AnalysisManagerState &state, G4bool rowWise, G4bool rowMode, tools::impi *impi, G4int mpiSize)
virtual ~G4RootMpiNtupleManager ()
virtual void CreateNtuplesFromBooking () final
virtual G4bool Merge () final
Public Member Functions inherited from G4RootNtupleManager
G4RootNtupleManager (const G4AnalysisManagerState &state, G4int nofMainManagers, G4bool rowWise, G4bool rowMode)
virtual ~G4RootNtupleManager ()
Public Member Functions inherited from G4TNtupleManager< tools::wroot::ntuple >
G4TNtupleManager (const G4AnalysisManagerState &state)
~G4TNtupleManager ()
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Member Functions
G4bool Send (G4int id, tools::wroot::ntuple *ntuple)
G4bool InitializeRanks ()
G4bool WaitBuffer ()
Private Attributes
tools::impi * fImpi
std::vector< G4int > fSlaveRanks
G4int fMainRank
Friends
class G4RootMpiAnalysisManager
class G4RootMpiMainNtupleManager
Additional Inherited Members
Protected Member Functions inherited from G4TNtupleManager< tools::wroot::ntuple >
G4bool IsEmpty () const
virtual G4int CreateNtuple (const G4String &name, const G4String &title) override
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) final
virtual void FinishNtuple (G4int ntupleId) final
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool AddNtupleRow (G4int ntupleId) override
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
tools::wroot::ntuple * GetNtuple () const
tools::wroot::ntuple * GetNtuple (G4int ntupleId) const
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const override
std::vector
< tools::wroot::ntuple * >
::iterator BeginNtuple ()
std::vector
< tools::wroot::ntuple * >
::iterator EndNtuple ()
std::vector
< tools::wroot::ntuple * >
::const_iterator BeginConstNtuple () const
std::vector
< tools::wroot::ntuple * >
::const_iterator EndConstNtuple () const
Protected Attributes inherited from G4TNtupleManager< tools::wroot::ntuple >
std::vector
< G4TNtupleDescription
< tools::wroot::ntuple > * > fNtupleDescriptionVector
std::vector
< tools::wroot::ntuple * > fNtupleVector
Detailed Description
Definition at line 43 of file G4RootMpiNtupleManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4RootMpiNtupleManager.hh
Constructor & Destructor Documentation
G4RootMpiNtupleManager::G4RootMpiNtupleManager (const G4AnalysisManagerState & state, G4bool rowWise, G4bool rowMode, tools::impi * impi, G4int mpiSize)
Definition at line 45 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4RootMpiNtupleManager.cc
References fMainRank, and fSlaveRanks.
G4RootMpiNtupleManager::~G4RootMpiNtupleManager () virtual
Definition at line 61 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 61 of file G4RootMpiNtupleManager.cc
Member Function Documentation
void G4RootMpiNtupleManager::CreateNtuplesFromBooking () final virtual
Reimplemented from G4TNtupleManager< tools::wroot::ntuple >.
Definition at line 295 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 295 of file G4RootMpiNtupleManager.cc
References G4TNtupleManager< TNTUPLE >::CreateNtuplesFromBooking(), G4cerr, G4endl, InitializeRanks(), and WaitBuffer().
G4bool G4RootMpiNtupleManager::InitializeRanks () private
Definition at line 152 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 152 of file G4RootMpiNtupleManager.cc
References G4TNtupleManager< tools::wroot::ntuple >::fNtupleDescriptionVector, G4BaseAnalysisManager::fState, G4AnalysisManagerState::GetIsActivation(), and Send().
Referenced by CreateNtuplesFromBooking().
G4bool G4RootMpiNtupleManager::Merge () final virtual
Reimplemented from G4RootNtupleManager.
Definition at line 313 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 313 of file G4RootMpiNtupleManager.cc
References G4TNtupleManager< tools::wroot::ntuple >::fNtupleDescriptionVector, G4BaseAnalysisManager::fState, G4cout, G4endl, and G4AnalysisManagerState::GetIsActivation().
G4bool G4RootMpiNtupleManager::Send (G4int id, tools::wroot::ntuple * ntuple) private
Definition at line 70 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 70 of file G4RootMpiNtupleManager.cc
References G4RootNtupleManager::fFileManager, fImpi, G4RootNtupleManager::fRowMode, G4RootNtupleManager::fRowWise, fSlaveRanks, G4cerr, G4cout, G4endl, it, and kTAG_NTUPLE.
Referenced by InitializeRanks().
G4bool G4RootMpiNtupleManager::WaitBuffer () private
Definition at line 172 of file G4RootMpiNtupleManager.cc.
View newest version in sPHENIX GitHub at line 172 of file G4RootMpiNtupleManager.cc
References fImpi, fMainRank, G4TNtupleManager< tools::wroot::ntuple >::fNtupleVector, fSlaveRanks, G4BaseAnalysisManager::fState, G4cerr, G4endl, G4AnalysisManagerState::GetVerboseL2(), and kTAG_NTUPLE.
Referenced by CreateNtuplesFromBooking().
Friends And Related Function Documentation
friend class G4RootMpiAnalysisManager friend
Definition at line 45 of file G4RootMpiNtupleManager.hh.
View newest version in sPHENIX GitHub at line 45 of file G4RootMpiNtupleManager.hh
friend class G4RootMpiMainNtupleManager friend
Definition at line 46 of file G4RootMpiNtupleManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4RootMpiNtupleManager.hh
Member Data Documentation
tools::impi* G4RootMpiNtupleManager::fImpi private
Definition at line 63 of file G4RootMpiNtupleManager.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RootMpiNtupleManager.hh
Referenced by Send(), and WaitBuffer().
G4int G4RootMpiNtupleManager::fMainRank private
Definition at line 65 of file G4RootMpiNtupleManager.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RootMpiNtupleManager.hh
Referenced by G4RootMpiNtupleManager(), and WaitBuffer().
std::vector<G4int> G4RootMpiNtupleManager::fSlaveRanks private
Definition at line 64 of file G4RootMpiNtupleManager.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RootMpiNtupleManager.hh
Referenced by G4RootMpiNtupleManager(), Send(), and WaitBuffer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/analysis/include/G4RootMpiNtupleManager.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/analysis/src/G4RootMpiNtupleManager.cc