ECCE @ EIC Software: G4FTFPPionBuilder Class Reference
G4FTFPPionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPPionBuilder.hh>
Public Member Functions
G4FTFPPionBuilder (G4bool quasiElastic=false)
virtual ~G4FTFPPionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPionBuilder
G4VPionBuilder ()=default
virtual ~G4VPionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4LundStringFragmentation * theLund
G4double theMin
G4double theMax
Detailed Description
Definition at line 57 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4FTFPPionBuilder.hh
Constructor & Destructor Documentation
G4FTFPPionBuilder::G4FTFPPionBuilder (G4bool quasiElastic = false)
Definition at line 44 of file G4FTFPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4FTFPPionBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theLund, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFPPionBuilder::~G4FTFPPionBuilder () virtual
Definition at line 69 of file G4FTFPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 69 of file G4FTFPPionBuilder.cc
References theLund, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4FTFPPionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPionBuilder.
Definition at line 63 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4FTFPPionBuilder.hh
void G4FTFPPionBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 78 of file G4FTFPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 78 of file G4FTFPPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4FTFPPionBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 87 of file G4FTFPPionBuilder.cc.
View newest version in sPHENIX GitHub at line 87 of file G4FTFPPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4FTFPPionBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 68 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4FTFPPionBuilder.hh
References theMax.
virtual void G4FTFPPionBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4FTFPPionBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4FTFPPionBuilder::theCascade private
Definition at line 74 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FTFPPionBuilder.hh
Referenced by G4FTFPPionBuilder().
G4LundStringFragmentation* G4FTFPPionBuilder::theLund private
Definition at line 78 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFPPionBuilder.hh
Referenced by G4FTFPPionBuilder(), and ~G4FTFPPionBuilder().
G4double G4FTFPPionBuilder::theMax private
Definition at line 80 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FTFPPionBuilder.hh
Referenced by Build(), G4FTFPPionBuilder(), and SetMaxEnergy().
G4double G4FTFPPionBuilder::theMin private
Definition at line 79 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFPPionBuilder.hh
Referenced by Build(), G4FTFPPionBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFPPionBuilder::theModel private
Definition at line 73 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFPPionBuilder.hh
Referenced by Build(), and G4FTFPPionBuilder().
G4QuasiElasticChannel* G4FTFPPionBuilder::theQuasiElastic private
Definition at line 77 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FTFPPionBuilder.hh
Referenced by G4FTFPPionBuilder(), and ~G4FTFPPionBuilder().
G4ExcitedStringDecay* G4FTFPPionBuilder::theStringDecay private
Definition at line 76 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FTFPPionBuilder.hh
Referenced by G4FTFPPionBuilder(), and ~G4FTFPPionBuilder().
G4FTFModel* G4FTFPPionBuilder::theStringModel private
Definition at line 75 of file G4FTFPPionBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FTFPPionBuilder.hh
Referenced by G4FTFPPionBuilder(), and ~G4FTFPPionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPPionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFPPionBuilder.cc