ECCE @ EIC Software: HadrontherapySteppingAction Class Reference
HadrontherapySteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapySteppingAction.hh>
Public Member Functions
HadrontherapySteppingAction (HadrontherapyRunAction *)
~HadrontherapySteppingAction ()
void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
HadrontherapyRunAction * runAction
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 47 of file HadrontherapySteppingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file HadrontherapySteppingAction.hh
Constructor & Destructor Documentation
HadrontherapySteppingAction::HadrontherapySteppingAction (HadrontherapyRunAction * run)
Definition at line 49 of file HadrontherapySteppingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file HadrontherapySteppingAction.cc
References runAction.
HadrontherapySteppingAction::~HadrontherapySteppingAction ()
Definition at line 55 of file HadrontherapySteppingAction.cc.
View newest version in sPHENIX GitHub at line 55 of file HadrontherapySteppingAction.cc
Member Function Documentation
void HadrontherapySteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 60 of file HadrontherapySteppingAction.cc.
View newest version in sPHENIX GitHub at line 60 of file HadrontherapySteppingAction.cc
References demo::app, fKillTrackAndSecondaries, G4endl, G4Track::GetDefinition(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), G4VTouchable::GetVolume(), G4Track::GetVolume(), pdg, Acts::Test::volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
HadrontherapyRunAction* HadrontherapySteppingAction::runAction private
Definition at line 56 of file HadrontherapySteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file HadrontherapySteppingAction.hh
Referenced by HadrontherapySteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapySteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapySteppingAction.cc