ECCE @ EIC Software: XrayFluoPlanePrimaryGeneratorAction Class Reference
XrayFluoPlanePrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPlanePrimaryGeneratorAction.hh>
Public Member Functions
XrayFluoPlanePrimaryGeneratorAction (const XrayFluoPlaneDetectorConstruction *)
~XrayFluoPlanePrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
void SetRndmFlag (G4String val)
void SetRndmVert (G4String val)
void SetSpectrum (G4String val)
void SetIsoVert (G4String val)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * particleGun
const
XrayFluoPlaneDetectorConstruction * XrayFluoDetector
XrayFluoPlanePrimaryGeneratorMessenger * gunMessenger
XrayFluoRunAction * runManager
G4String rndmFlag
G4String beam
G4String spectrum
G4String isoVert
Detailed Description
Definition at line 51 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 51 of file XrayFluoPlanePrimaryGeneratorAction.hh
Constructor & Destructor Documentation
XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction (const XrayFluoPlaneDetectorConstruction * XrayFluoDC)
Definition at line 54 of file XrayFluoPlanePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 54 of file XrayFluoPlanePrimaryGeneratorAction.cc
References cm, G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleTable::GetParticleTable(), XrayFluoPlaneDetectorConstruction::GetWorldSizeZ(), gunMessenger, keV, particle, particleGun, runManager, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and XrayFluoDetector.
XrayFluoPlanePrimaryGeneratorAction::~XrayFluoPlanePrimaryGeneratorAction ()
Definition at line 88 of file XrayFluoPlanePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 88 of file XrayFluoPlanePrimaryGeneratorAction.cc
References G4cout, G4endl, gunMessenger, particleGun, and runManager.
Member Function Documentation
void XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 100 of file XrayFluoPlanePrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 100 of file XrayFluoPlanePrimaryGeneratorAction.cc
References XrayFluoAnalysisManager::analysePrimaryGenerator(), static_analysis_results::analysis(), beam, Dx, Acts::Test::dX, Dy, XrayFluoDataSet::FindValue(), G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), XrayFluoRunAction::GetData(), XrayFluoRunAction::GetDataSum(), XrayFluoRunAction::GetEnergies(), XrayFluoRunAction::GetGammaSet(), XrayFluoAnalysisManager::getInstance(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleDefinition::GetParticleName(), XrayFluoPlaneDetectorConstruction::GetPlaneSizeXY(), XrayFluoPlaneDetectorConstruction::GetWorldSizeXY(), XrayFluoPlaneDetectorConstruction::GetWorldSizeZ(), isoVert, keV, m, mm, particle, particleGun, phi, pi, rad, radius, rndmFlag, runManager, G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), spectrum, sum, theta(), x, XrayFluoDetector, y, z, and G4InuclParticleNames::z0.
void XrayFluoPlanePrimaryGeneratorAction::SetIsoVert (G4String val) inline
Definition at line 72 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file XrayFluoPlanePrimaryGeneratorAction.hh
References isoVert.
Referenced by XrayFluoPlanePrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPlanePrimaryGeneratorAction::SetRndmFlag (G4String val) inline
Definition at line 63 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 63 of file XrayFluoPlanePrimaryGeneratorAction.hh
References rndmFlag.
Referenced by XrayFluoPlanePrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPlanePrimaryGeneratorAction::SetRndmVert (G4String val) inline
Definition at line 66 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file XrayFluoPlanePrimaryGeneratorAction.hh
References beam.
Referenced by XrayFluoPlanePrimaryGeneratorMessenger::SetNewValue().
void XrayFluoPlanePrimaryGeneratorAction::SetSpectrum (G4String val) inline
Definition at line 69 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file XrayFluoPlanePrimaryGeneratorAction.hh
References spectrum.
Referenced by XrayFluoPlanePrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4String XrayFluoPlanePrimaryGeneratorAction::beam private
Definition at line 89 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 89 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmVert().
XrayFluoPlanePrimaryGeneratorMessenger* XrayFluoPlanePrimaryGeneratorAction::gunMessenger private
Definition at line 82 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 82 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by XrayFluoPlanePrimaryGeneratorAction(), and ~XrayFluoPlanePrimaryGeneratorAction().
G4String XrayFluoPlanePrimaryGeneratorAction::isoVert private
Definition at line 95 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 95 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetIsoVert().
G4ParticleGun* XrayFluoPlanePrimaryGeneratorAction::particleGun private
Definition at line 76 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 76 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction(), and ~XrayFluoPlanePrimaryGeneratorAction().
G4String XrayFluoPlanePrimaryGeneratorAction::rndmFlag private
Definition at line 86 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmFlag().
XrayFluoRunAction* XrayFluoPlanePrimaryGeneratorAction::runManager private
Definition at line 83 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 83 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction(), and ~XrayFluoPlanePrimaryGeneratorAction().
G4String XrayFluoPlanePrimaryGeneratorAction::spectrum private
Definition at line 92 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 92 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetSpectrum().
const XrayFluoPlaneDetectorConstruction* XrayFluoPlanePrimaryGeneratorAction::XrayFluoDetector private
Definition at line 79 of file XrayFluoPlanePrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 79 of file XrayFluoPlanePrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and XrayFluoPlanePrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPlanePrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoPlanePrimaryGeneratorAction.cc