ECCE @ EIC Software: G4ProcessTable Class Reference
G4ProcessTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessTable.hh>
Public Types
typedef std::vector
< G4ProcTblElement * > G4ProcTableVector
typedef std::vector< G4String > G4ProcNameVector
Public Member Functions
G4ProcessTable ()
~G4ProcessTable ()
G4int Length () const
G4int Insert (G4VProcess *aProcess, G4ProcessManager *aProcMgr)
G4int Remove (G4VProcess *aProcess, G4ProcessManager *aProcMgr)
G4VProcess * FindProcess (const G4String &processName, const G4String &particleName) const
G4VProcess * FindProcess (const G4String &processName, const G4ParticleDefinition *particle) const
G4VProcess * FindProcess (const G4String &processName, const G4ProcessManager *processManager) const
G4ProcessVector * FindProcesses ()
G4ProcessVector * FindProcesses (const G4ProcessManager *processManager)
G4ProcessVector * FindProcesses (const G4String &processName)
G4ProcessVector * FindProcesses (G4ProcessType processType)
void SetProcessActivation (const G4String &processName, G4bool fActive)
void SetProcessActivation (const G4String &processName, const G4String &particleName, G4bool fActive)
void SetProcessActivation (const G4String &processName, G4ParticleDefinition *particle, G4bool fActive)
void SetProcessActivation (const G4String &processName, G4ProcessManager *processManager, G4bool fActive)
void SetProcessActivation (G4ProcessType processType, G4bool fActive)
void SetProcessActivation (G4ProcessType processType, const G4String &particleName, G4bool fActive)
void SetProcessActivation (G4ProcessType processType, G4ParticleDefinition *particle, G4bool fActive)
void SetProcessActivation (G4ProcessType processType, G4ProcessManager *processManager, G4bool fActive)
G4ProcNameVector * GetNameList ()
G4ProcTableVector * GetProcTableVector ()
void DumpInfo (G4VProcess *process, G4ParticleDefinition *particle=0)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Static Public Member Functions
static G4ProcessTable * GetProcessTable ()
Private Member Functions
G4ProcessTable (const G4ProcessTable &right)
G4ProcessTable & operator= (const G4ProcessTable &right)
G4bool operator== (const G4ProcessTable &right) const
G4bool operator!= (const G4ProcessTable &right) const
G4ProcTableVector * Find (G4ProcTableVector *procTableVector, const G4String &processName)
G4ProcTableVector * Find (G4ProcTableVector *procTableVector, G4ProcessType processType)
G4ProcessVector * ExtractProcesses (G4ProcTableVector *procTableVector)
Private Attributes
G4ProcessTableMessenger * fProcTblMessenger
G4ProcTableVector * fProcTblVector
G4ProcNameVector * fProcNameVector
G4ProcTableVector * tmpTblVector
G4int verboseLevel
Static Private Attributes
static G4ThreadLocal
G4ProcessTable * fProcessTable = nullptr
Friends
class G4ThreadLocalSingleton< G4ProcessTable >
Detailed Description
Definition at line 60 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ProcessTable.hh
Member Typedef Documentation
typedef std::vector<G4String> G4ProcessTable::G4ProcNameVector
Definition at line 137 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ProcessTable.hh
typedef std::vector<G4ProcTblElement*> G4ProcessTable::G4ProcTableVector
Definition at line 136 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ProcessTable.hh
Constructor & Destructor Documentation
G4ProcessTable::G4ProcessTable ()
Definition at line 46 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ProcessTable.cc
References fProcNameVector, fProcTblMessenger, fProcTblVector, G4cout, G4endl, tmpTblVector, and verboseLevel.
G4ProcessTable::~G4ProcessTable ()
Definition at line 61 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ProcessTable.cc
References fProcessTable, fProcNameVector, fProcTblMessenger, fProcTblVector, incremental_prev_tag::idx, and tmpTblVector.
G4ProcessTable::G4ProcessTable (const G4ProcessTable & right) private
Member Function Documentation
void G4ProcessTable::DumpInfo (G4VProcess * process, G4ParticleDefinition * particle = 0)
Definition at line 501 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 501 of file G4ProcessTable.cc
References G4ProcessManager::DumpInfo(), G4VProcess::DumpInfo(), fProcTblVector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcTblElement::GetProcess(), G4ProcTblElement::GetProcessManager(), G4ProcessManager::GetVerboseLevel(), G4VProcess::GetVerboseLevel(), incremental_prev_tag::idx, G4ProcTblElement::Length(), G4ProcessManager::SetVerboseLevel(), G4VProcess::SetVerboseLevel(), and verboseLevel.
Referenced by export_G4ProcessTable(), and G4ProcessTableMessenger::SetNewValue().
G4ProcessVector * G4ProcessTable::ExtractProcesses (G4ProcTableVector * procTableVector) private
Definition at line 340 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 340 of file G4ProcessTable.cc
References G4ProcTblElement::GetProcess(), and G4ProcessVector::insert().
Referenced by FindProcesses().
G4ProcessTable::G4ProcTableVector * G4ProcessTable::Find (G4ProcTableVector * procTableVector, const G4String & processName) private
Definition at line 283 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 283 of file G4ProcessTable.cc
References fProcTblVector, G4cout, G4endl, G4ProcTblElement::GetProcessName(), tmpTblVector, and verboseLevel.
Referenced by FindProcesses(), and SetProcessActivation().
G4ProcessTable::G4ProcTableVector * G4ProcessTable::Find (G4ProcTableVector * procTableVector, G4ProcessType processType) private
Definition at line 311 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 311 of file G4ProcessTable.cc
References fProcTblVector, G4cout, G4endl, G4ProcTblElement::GetProcess(), G4VProcess::GetProcessType(), tmpTblVector, and verboseLevel.
G4VProcess* G4ProcessTable::FindProcess (const G4String & processName, const G4String & particleName) const
Referenced by G4EmDNAChemistry::ConstructProcess(), F04PhysicsList::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), Run::EndOfRun(), PhysicsList::SetAnnihiToHadronFac(), PhysicsList::SetAnnihiToMuPairFac(), PhysicsList::SetGammaToMuPairFac(), SetProcessActivation(), and Run::WriteActivity().
G4VProcess* G4ProcessTable::FindProcess (const G4String & processName, const G4ParticleDefinition * particle) const
G4VProcess * G4ProcessTable::FindProcess (const G4String & processName, const G4ProcessManager * processManager) const
Definition at line 251 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 251 of file G4ProcessTable.cc
References G4ProcTblElement::Contains(), fProcTblVector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcTblElement::GetProcess(), G4ProcTblElement::GetProcessName(), and verboseLevel.
G4ProcessVector * G4ProcessTable::FindProcesses ()
Definition at line 352 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 352 of file G4ProcessTable.cc
References ExtractProcesses(), and fProcTblVector.
Referenced by G4ProcessTableMessenger::SetNewValue().
G4ProcessVector * G4ProcessTable::FindProcesses (const G4ProcessManager * processManager)
Definition at line 358 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 358 of file G4ProcessTable.cc
References G4ProcessManager::GetProcessList().
G4ProcessVector * G4ProcessTable::FindProcesses (const G4String & processName)
Definition at line 365 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 365 of file G4ProcessTable.cc
References ExtractProcesses(), Find(), and fProcTblVector.
G4ProcessVector * G4ProcessTable::FindProcesses (G4ProcessType processType)
Definition at line 372 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 372 of file G4ProcessTable.cc
References ExtractProcesses(), Find(), and fProcTblVector.
G4ProcNameVector* G4ProcessTable::GetNameList ()
Referenced by export_G4ProcessTable(), and G4ProcessTableMessenger::SetNewValue().
G4ProcessTable * G4ProcessTable::GetProcessTable () static
Definition at line 90 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ProcessTable.cc
References fProcessTable, and G4ThreadLocalSingleton< T >::Instance().
Referenced by G4ProcessManager::AddProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), F04PhysicsList::ConstructProcess(), G4SpinDecayPhysics::ConstructProcess(), Run::EndOfRun(), ExUCNRunAction::EndOfRunAction(), export_G4ProcessTable(), G4ProcessManager::G4ProcessManager(), G4RunManager::G4RunManager(), G4ProcessManager::RemoveProcess(), PhysicsList::SetAnnihiToHadronFac(), PhysicsList::SetAnnihiToMuPairFac(), PhysicsList::SetGammaToMuPairFac(), and Run::WriteActivity().
G4ProcTableVector* G4ProcessTable::GetProcTableVector ()
G4int G4ProcessTable::GetVerboseLevel () const
Referenced by export_G4ProcessTable(), and G4ProcessTableMessenger::GetCurrentValue().
G4int G4ProcessTable::Insert (G4VProcess * aProcess, G4ProcessManager * aProcMgr)
Definition at line 100 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ProcessTable.cc
References G4ProcTblElement::Contains(), fProcNameVector, fProcTblVector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcTblElement::GetProcess(), G4VProcess::GetProcessName(), G4ProcTblElement::Insert(), and verboseLevel.
Referenced by G4ProcessManager::AddProcess(), and G4ProcessManager::G4ProcessManager().
G4int G4ProcessTable::Length () const
Referenced by export_G4ProcessTable().
G4bool G4ProcessTable::operator!= (const G4ProcessTable & right) const private
G4ProcessTable& G4ProcessTable::operator= (const G4ProcessTable & right) private
G4bool G4ProcessTable::operator== (const G4ProcessTable & right) const private
G4int G4ProcessTable::Remove (G4VProcess * aProcess, G4ProcessManager * aProcMgr)
Definition at line 169 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 169 of file G4ProcessTable.cc
References G4ProcTblElement::Contains(), fProcNameVector, fProcTblVector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcTblElement::GetProcess(), G4ProcTblElement::GetProcessName(), G4VProcess::GetProcessName(), G4ProcTblElement::Length(), G4ProcTblElement::Remove(), and verboseLevel.
Referenced by G4ProcessManager::RemoveProcess().
void G4ProcessTable::SetProcessActivation (const G4String & processName, G4bool fActive)
Definition at line 379 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 379 of file G4ProcessTable.cc
References Find(), fProcTblVector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcTblElement::GetProcess(), G4ProcessManager::GetProcessIndex(), G4ProcTblElement::GetProcessManager(), incremental_prev_tag::idx, G4ProcTblElement::Length(), G4ProcessManager::SetProcessActivation(), and verboseLevel.
Referenced by G4ProcessTableMessenger::SetNewValue().
void G4ProcessTable::SetProcessActivation (const G4String & processName, const G4String & particleName, G4bool fActive)
void G4ProcessTable::SetProcessActivation (const G4String & processName, G4ParticleDefinition * particle, G4bool fActive)
void G4ProcessTable::SetProcessActivation (const G4String & processName, G4ProcessManager * processManager, G4bool fActive)
Definition at line 410 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 410 of file G4ProcessTable.cc
References FindProcess(), G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcessManager::GetProcessIndex(), G4ProcessManager::SetProcessActivation(), and verboseLevel.
void G4ProcessTable::SetProcessActivation (G4ProcessType processType, G4bool fActive)
Definition at line 436 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 436 of file G4ProcessTable.cc
References Find(), fProcTblVector, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcTblElement::GetProcess(), G4ProcessManager::GetProcessIndex(), G4ProcTblElement::GetProcessManager(), G4VProcess::GetProcessName(), incremental_prev_tag::idx, G4ProcTblElement::Length(), G4ProcessManager::SetProcessActivation(), and verboseLevel.
void G4ProcessTable::SetProcessActivation (G4ProcessType processType, const G4String & particleName, G4bool fActive)
void G4ProcessTable::SetProcessActivation (G4ProcessType processType, G4ParticleDefinition * particle, G4bool fActive)
void G4ProcessTable::SetProcessActivation (G4ProcessType processType, G4ProcessManager * processManager, G4bool fActive)
Definition at line 471 of file G4ProcessTable.cc.
View newest version in sPHENIX GitHub at line 471 of file G4ProcessTable.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ProcessManager::GetProcessList(), G4VProcess::GetProcessName(), G4VProcess::GetProcessType(), incremental_prev_tag::idx, G4ProcessVector::length(), G4ProcessManager::SetProcessActivation(), and verboseLevel.
void G4ProcessTable::SetVerboseLevel (G4int value)
Referenced by export_G4ProcessTable(), and G4ProcessTableMessenger::SetNewValue().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4ProcessTable > friend
Definition at line 63 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ProcessTable.hh
Member Data Documentation
G4ThreadLocal G4ProcessTable * G4ProcessTable::fProcessTable = nullptr static private
Definition at line 172 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ProcessTable.hh
Referenced by GetProcessTable(), and ~G4ProcessTable().
G4ProcNameVector* G4ProcessTable::fProcNameVector private
Definition at line 177 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ProcessTable.hh
Referenced by G4ProcessTable(), Insert(), Remove(), and ~G4ProcessTable().
G4ProcessTableMessenger* G4ProcessTable::fProcTblMessenger private
Definition at line 173 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ProcessTable.hh
Referenced by G4ProcessTable(), and ~G4ProcessTable().
G4ProcTableVector* G4ProcessTable::fProcTblVector private
Definition at line 176 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ProcessTable.hh
Referenced by DumpInfo(), Find(), FindProcess(), FindProcesses(), G4ProcessTable(), Insert(), Remove(), SetProcessActivation(), and ~G4ProcessTable().
G4ProcTableVector* G4ProcessTable::tmpTblVector private
Definition at line 180 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 180 of file G4ProcessTable.hh
Referenced by Find(), G4ProcessTable(), and ~G4ProcessTable().
G4int G4ProcessTable::verboseLevel private
Definition at line 184 of file G4ProcessTable.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ProcessTable.hh
Referenced by DumpInfo(), Find(), FindProcess(), G4ProcessTable(), Insert(), Remove(), and SetProcessActivation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcessTable.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4ProcessTable.cc