ECCE @ EIC Software: G4RunMessenger Class Reference
G4RunMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4RunMessenger.hh>
Public Member Functions
G4RunMessenger (G4RunManager *runMgr)
~G4RunMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4RunManager * runManager
G4String macroFileName
G4UIdirectory * runDirectory
G4UIcommand * beamOnCmd
G4UIcmdWithAnInteger * verboseCmd
G4UIcmdWithAnInteger * printProgCmd
G4UIcmdWithAnInteger * nThreadsCmd
G4UIcmdWithoutParameter * maxThreadsCmd
G4UIcmdWithAnInteger * pinAffinityCmd
G4UIcommand * evModCmd
G4UIcmdWithAString * dumpRegCmd
G4UIcmdWithoutParameter * dumpCoupleCmd
G4UIcmdWithABool * optCmd
G4UIcmdWithABool * brkBoECmd
G4UIcmdWithABool * brkEoECmd
G4UIcmdWithABool * abortCmd
G4UIcmdWithoutParameter * abortEventCmd
G4UIcmdWithoutParameter * initCmd
G4UIcmdWithoutParameter * geomCmd
G4UIcmdWithABool * geomRebCmd
G4UIcmdWithoutParameter * physCmd
G4UIcmdWithAnInteger * randEvtCmd
G4UIcommand * procUICmds
G4UIdirectory * randomDirectory
G4UIcmdWithAString * seedCmd
G4UIcmdWithAString * randDirCmd
G4UIcmdWithABool * savingFlagCmd
G4UIcmdWithoutParameter * saveThisRunCmd
G4UIcmdWithoutParameter * saveThisEventCmd
G4UIcmdWithAString * restoreRandCmd
G4UIcmdWithABool * saveEachEventCmd
G4UIcmdWithABool * restoreRandCmdMT
G4UIcmdWithoutParameter * constScoreCmd
G4MaterialScanner * materialScanner
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 68 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RunMessenger.hh
Constructor & Destructor Documentation
G4RunMessenger::G4RunMessenger (G4RunManager * runMgr)
Definition at line 47 of file G4RunMessenger.cc.
View newest version in sPHENIX GitHub at line 47 of file G4RunMessenger.cc
References abortCmd, abortEventCmd, G4UIcommand::AvailableForStates(), beamOnCmd, brkBoECmd, brkEoECmd, constScoreCmd, dumpCoupleCmd, dumpRegCmd, evModCmd, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_PreInit, geomCmd, geomRebCmd, initCmd, materialScanner, maxThreadsCmd, nThreadsCmd, optCmd, physCmd, pinAffinityCmd, printProgCmd, procUICmds, randDirCmd, randEvtCmd, randomDirectory, restoreRandCmd, restoreRandCmdMT, runDirectory, saveEachEventCmd, saveThisEventCmd, saveThisRunCmd, savingFlagCmd, seedCmd, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIparameter::SetParameterRange(), G4UIcommand::SetRange(), G4UIcommand::SetToBeBroadcasted(), and verboseCmd.
G4RunMessenger::~G4RunMessenger ()
Definition at line 334 of file G4RunMessenger.cc.
View newest version in sPHENIX GitHub at line 334 of file G4RunMessenger.cc
References abortCmd, abortEventCmd, beamOnCmd, brkBoECmd, brkEoECmd, constScoreCmd, dumpCoupleCmd, dumpRegCmd, evModCmd, geomCmd, geomRebCmd, initCmd, materialScanner, maxThreadsCmd, nThreadsCmd, optCmd, physCmd, pinAffinityCmd, printProgCmd, procUICmds, randDirCmd, randEvtCmd, randomDirectory, restoreRandCmd, restoreRandCmdMT, runDirectory, saveEachEventCmd, saveThisEventCmd, saveThisRunCmd, savingFlagCmd, seedCmd, and verboseCmd.
Member Function Documentation
G4String G4RunMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 559 of file G4RunMessenger.cc.
View newest version in sPHENIX GitHub at line 559 of file G4RunMessenger.cc
References G4UIcommand::ConvertToString(), evModCmd, G4cout, G4endl, G4RunManager::GetFlagRandomNumberStatusToG4Event(), G4RunManager::GetPrintProgress(), G4RunManager::GetRandomNumberStoreDir(), G4RunManager::GetRunManagerType(), G4RunManager::GetVerboseLevel(), G4RunManager::masterRM, nThreadsCmd, printProgCmd, randDirCmd, randEvtCmd, runManager, G4MTRunManager::SeedOncePerCommunication(), G4RunManager::sequentialRM, and verboseCmd.
void G4RunMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 373 of file G4RunMessenger.cc.
View newest version in sPHENIX GitHub at line 373 of file G4RunMessenger.cc
References abortCmd, G4RunManager::AbortEvent(), abortEventCmd, G4RunManager::AbortRun(), G4RunManager::BeamOn(), beamOnCmd, brkBoECmd, brkEoECmd, G4RunManager::ConstructScoringWorlds(), constScoreCmd, dumpCoupleCmd, G4ProductionCutsTable::DumpCouples(), dumpRegCmd, G4RunManager::DumpRegion(), evModCmd, FatalException, G4cerr, G4cout, G4endl, G4Exception(), G4Threading::G4GetNumberOfCores(), geomCmd, G4RunManager::GeometryHasBeenModified(), geomRebCmd, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ProductionCutsTable::GetProductionCutsTable(), G4RunManager::GetRunManagerType(), G4UImanager::GetUIpointer(), incremental_prev_tag::idx, initCmd, G4RunManager::Initialize(), macroFileName, G4RunManager::masterRM, maxThreadsCmd, nThreadsCmd, optCmd, physCmd, G4RunManager::PhysicsHasBeenModified(), pinAffinityCmd, printProgCmd, procUICmds, randDirCmd, randEvtCmd, G4RunManager::ReinitializeGeometry(), G4MTRunManager::RequestWorkersProcessCommandsStack(), restoreRandCmd, restoreRandCmdMT, G4RunManager::RestoreRandomNumberStatus(), G4RunManager::RestoreRndmEachEvent(), G4RunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisRun(), runManager, saveEachEventCmd, saveThisEventCmd, saveThisRunCmd, savingFlagCmd, seedCmd, G4RunManager::sequentialRM, G4RunManager::SetGeometryToBeOptimized(), G4UImanager::SetPauseAtBeginOfEvent(), G4UImanager::SetPauseAtEndOfEvent(), G4RunManager::SetPrintProgress(), G4RunManager::SetRandomNumberStore(), G4RunManager::SetRandomNumberStoreDir(), G4RunManager::SetRandomNumberStorePerEvent(), G4MTRunManager::SetSeedOncePerCommunication(), G4RunManager::SetVerboseLevel(), G4UImessenger::StoL(), G4RunManager::StoreRandomNumberStatusToG4Event(), and verboseCmd.
Member Data Documentation
G4UIcmdWithABool* G4RunMessenger::abortCmd private
Definition at line 96 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::abortEventCmd private
Definition at line 97 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcommand* G4RunMessenger::beamOnCmd private
Definition at line 84 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithABool* G4RunMessenger::brkBoECmd private
Definition at line 94 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithABool* G4RunMessenger::brkEoECmd private
Definition at line 95 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::constScoreCmd private
Definition at line 115 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 115 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::dumpCoupleCmd private
Definition at line 92 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAString* G4RunMessenger::dumpRegCmd private
Definition at line 91 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcommand* G4RunMessenger::evModCmd private
Definition at line 90 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::geomCmd private
Definition at line 99 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 99 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithABool* G4RunMessenger::geomRebCmd private
Definition at line 100 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 100 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::initCmd private
Definition at line 98 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4String G4RunMessenger::macroFileName private
Definition at line 80 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RunMessenger.hh
Referenced by SetNewValue().
G4MaterialScanner* G4RunMessenger::materialScanner private
Definition at line 117 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 117 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::maxThreadsCmd private
Definition at line 88 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAnInteger* G4RunMessenger::nThreadsCmd private
Definition at line 87 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithABool* G4RunMessenger::optCmd private
Definition at line 93 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::physCmd private
Definition at line 101 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 101 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAnInteger* G4RunMessenger::pinAffinityCmd private
Definition at line 89 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAnInteger* G4RunMessenger::printProgCmd private
Definition at line 86 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RunMessenger().
G4UIcommand* G4RunMessenger::procUICmds private
Definition at line 103 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 103 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAString* G4RunMessenger::randDirCmd private
Definition at line 107 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 107 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAnInteger* G4RunMessenger::randEvtCmd private
Definition at line 102 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 102 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RunMessenger().
G4UIdirectory* G4RunMessenger::randomDirectory private
Definition at line 105 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 105 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), and ~G4RunMessenger().
G4UIcmdWithAString* G4RunMessenger::restoreRandCmd private
Definition at line 111 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithABool* G4RunMessenger::restoreRandCmdMT private
Definition at line 113 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 113 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIdirectory* G4RunMessenger::runDirectory private
Definition at line 83 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), and ~G4RunMessenger().
G4RunManager* G4RunMessenger::runManager private
Definition at line 79 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RunMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIcmdWithABool* G4RunMessenger::saveEachEventCmd private
Definition at line 112 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 112 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::saveThisEventCmd private
Definition at line 110 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithoutParameter* G4RunMessenger::saveThisRunCmd private
Definition at line 109 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 109 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithABool* G4RunMessenger::savingFlagCmd private
Definition at line 108 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 108 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAString* G4RunMessenger::seedCmd private
Definition at line 106 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 106 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), SetNewValue(), and ~G4RunMessenger().
G4UIcmdWithAnInteger* G4RunMessenger::verboseCmd private
Definition at line 85 of file G4RunMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RunMessenger.hh
Referenced by G4RunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RunMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4RunMessenger.hh
geant4/tree/geant4-10.6-release/source/run/src/G4RunMessenger.cc