ECCE @ EIC Software: GammaKnifeController Class Reference
GammaKnifeController Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaknife/include/GammaKnifeController.hh>
Public Member Functions
GammaKnifeController (GammaKnifeDetectorConstruction *)
~GammaKnifeController ()
void BeamOn (G4int)
void ReadFile (std::string fileName)
Private Types
using MeshScoreMap = G4VScoringMesh::MeshScoreMap
Private Member Functions
void StoreHits ()
void PrepareHitsAccumulation ()
void AccumulateAllHits ()
void RotateForward (G4int)
void RotateBack (G4int)
Private Attributes
std::vector< G4double > phiAngles
std::vector< G4double > thetaAngles
GammaKnifeDetectorConstruction * detector
GammaKnifeMessenger * messenger
MeshScoreMap * scoreMaps
Detailed Description
Definition at line 45 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 45 of file GammaKnifeController.hh
Member Typedef Documentation
using GammaKnifeController::MeshScoreMap = G4VScoringMesh::MeshScoreMap private
Definition at line 77 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 77 of file GammaKnifeController.hh
Constructor & Destructor Documentation
GammaKnifeController::GammaKnifeController (GammaKnifeDetectorConstruction * det)
Definition at line 35 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 35 of file GammaKnifeController.cc
References detector, and messenger.
GammaKnifeController::~GammaKnifeController ()
Definition at line 42 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 42 of file GammaKnifeController.cc
References messenger.
Member Function Documentation
void GammaKnifeController::AccumulateAllHits () private
Definition at line 151 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 151 of file GammaKnifeController.cc
References G4VScoringMesh::Accumulate(), G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4ScoringManager::GetScoringManagerIfExist(), it, and scoreMaps.
Referenced by BeamOn().
void GammaKnifeController::BeamOn (G4int n_event)
Definition at line 47 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 47 of file GammaKnifeController.cc
References AccumulateAllHits(), G4RunManager::BeamOn(), GAMMAKNIFE_SOURCES, G4RunManager::GetRunManager(), PrepareHitsAccumulation(), RotateBack(), RotateForward(), and StoreHits().
Referenced by GammaKnifeMessenger::SetNewValue().
void GammaKnifeController::PrepareHitsAccumulation () private
Definition at line 92 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 92 of file GammaKnifeController.cc
References G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4VScoringMesh::GetScoreMap(), G4ScoringManager::GetScoringManagerIfExist(), it, and scoreMaps.
Referenced by BeamOn().
void GammaKnifeController::ReadFile (std::string fileName)
Definition at line 169 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 169 of file GammaKnifeController.cc
References c, degree, GAMMAKNIFE_SOURCES, phi, phiAngles, theta(), and thetaAngles.
Referenced by main(), and GammaKnifeMessenger::SetNewValue().
void GammaKnifeController::RotateBack (G4int position) private
Definition at line 78 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 78 of file GammaKnifeController.cc
References G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4ScoringManager::GetScoringManagerIfExist(), phiAngles, G4VScoringMesh::RotateX(), G4VScoringMesh::RotateZ(), and thetaAngles.
Referenced by BeamOn().
void GammaKnifeController::RotateForward (G4int position) private
Definition at line 63 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 63 of file GammaKnifeController.cc
References G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4ScoringManager::GetScoringManagerIfExist(), phiAngles, G4VScoringMesh::RotateX(), G4VScoringMesh::RotateZ(), and thetaAngles.
Referenced by BeamOn().
void GammaKnifeController::StoreHits () private
Definition at line 118 of file GammaKnifeController.cc.
View newest version in sPHENIX GitHub at line 118 of file GammaKnifeController.cc
References G4ScoringManager::GetMesh(), G4ScoringManager::GetNumberOfMesh(), G4VScoringMesh::GetScoreMap(), G4ScoringManager::GetScoringManagerIfExist(), it, and scoreMaps.
Referenced by BeamOn().
Member Data Documentation
GammaKnifeDetectorConstruction* GammaKnifeController::detector private
Definition at line 73 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 73 of file GammaKnifeController.hh
Referenced by GammaKnifeController().
GammaKnifeMessenger* GammaKnifeController::messenger private
Definition at line 75 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 75 of file GammaKnifeController.hh
Referenced by GammaKnifeController(), and ~GammaKnifeController().
std::vector<G4double> GammaKnifeController::phiAngles private
Definition at line 69 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 69 of file GammaKnifeController.hh
Referenced by ReadFile(), RotateBack(), and RotateForward().
MeshScoreMap* GammaKnifeController::scoreMaps private
Definition at line 78 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 78 of file GammaKnifeController.hh
Referenced by AccumulateAllHits(), PrepareHitsAccumulation(), and StoreHits().
std::vector<G4double> GammaKnifeController::thetaAngles private
Definition at line 71 of file GammaKnifeController.hh.
View newest version in sPHENIX GitHub at line 71 of file GammaKnifeController.hh
Referenced by ReadFile(), RotateBack(), and RotateForward().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaknife/include/GammaKnifeController.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaknife/src/GammaKnifeController.cc