ECCE @ EIC Software: G4VElasticCollision Class Reference
G4VElasticCollision Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VElasticCollision.hh>
Public Member Functions
G4VElasticCollision ()
virtual ~G4VElasticCollision ()
G4bool operator== (const G4VElasticCollision &right) const
G4bool operator!= (const G4VElasticCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const =0
virtual G4String GetName () const =0
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Additional Inherited Members
Protected Member Functions inherited from G4VCollision
G4int GetNumberOfPartons (const G4ParticleDefinition *aP) const
virtual const G4CollisionVector * GetComponents () const
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const =0
virtual const
G4VAngularDistribution * GetAngularDistribution () const =0
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const =0
Detailed Description
Definition at line 39 of file G4VElasticCollision.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VElasticCollision.hh
Constructor & Destructor Documentation
G4VElasticCollision::G4VElasticCollision ()
Definition at line 44 of file G4VElasticCollision.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VElasticCollision.cc
G4VElasticCollision::~G4VElasticCollision () virtual
Definition at line 49 of file G4VElasticCollision.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VElasticCollision.cc
Member Function Documentation
G4KineticTrackVector * G4VElasticCollision::FinalState (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 53 of file G4VElasticCollision.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VElasticCollision.cc
References CLHEP::HepLorentzVector::boostVector(), G4VAngularDistribution::CosTheta(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), G4VCollision::GetAngularDistribution(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzRotation::inverse(), CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), G4Neutron::Neutron(), G4VAngularDistribution::Phi(), phi, G4Proton::Proton(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), S(), and G4KineticTrack::Set4Momentum().
G4bool G4VElasticCollision::operator!= (const G4VElasticCollision & right) const
G4bool G4VElasticCollision::operator== (const G4VElasticCollision & right) const
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VElasticCollision.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4VElasticCollision.cc