ECCE @ EIC Software: F04TrajectoryPoint Class Reference
F04TrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04TrajectoryPoint.hh>
Public Member Functions
F04TrajectoryPoint ()
F04TrajectoryPoint (const G4Track *aTrack)
F04TrajectoryPoint (const G4Step *aStep)
F04TrajectoryPoint (const F04TrajectoryPoint &right)
virtual ~F04TrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const F04TrajectoryPoint &right) const
G4double GetTime () const
const G4ThreeVector GetMomentum () const
G4StepStatus GetStepStatus () const
G4String GetVolumeName () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4TrajectoryPoint
G4TrajectoryPoint ()
G4TrajectoryPoint (G4ThreeVector pos)
G4TrajectoryPoint (const G4TrajectoryPoint &right)
virtual ~G4TrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const G4TrajectoryPoint &right) const
const G4ThreeVector GetPosition () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
virtual const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
Private Attributes
G4double fTime
G4ThreeVector fMomentum
G4StepStatus fStepStatus
G4String fVolumeName
Detailed Description
Definition at line 46 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 46 of file F04TrajectoryPoint.hh
Constructor & Destructor Documentation
F04TrajectoryPoint::F04TrajectoryPoint ()
Definition at line 53 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 53 of file F04TrajectoryPoint.cc
F04TrajectoryPoint::F04TrajectoryPoint (const G4Track * aTrack)
Definition at line 76 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 76 of file F04TrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, fUndefined, fVolumeName, G4Track::GetGlobalTime(), G4Track::GetMomentum(), G4VPhysicalVolume::GetName(), and G4Track::GetVolume().
F04TrajectoryPoint::F04TrajectoryPoint (const G4Step * aStep)
Definition at line 59 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 59 of file F04TrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, fVolumeName, G4StepPoint::GetGlobalTime(), G4StepPoint::GetMomentum(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), and G4StepPoint::GetStepStatus().
F04TrajectoryPoint::F04TrajectoryPoint (const F04TrajectoryPoint & right)
Definition at line 87 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 87 of file F04TrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, and fVolumeName.
F04TrajectoryPoint::~F04TrajectoryPoint () virtual
Definition at line 98 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 98 of file F04TrajectoryPoint.cc
Member Function Documentation
std::vector< G4AttValue > * F04TrajectoryPoint::CreateAttValues () const virtual
Reimplemented from G4TrajectoryPoint.
Definition at line 134 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 134 of file F04TrajectoryPoint.cc
References fMomentum, fStepStatus, fTime, fVolumeName, G4BestUnit, G4cout, GetAttDefs(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * F04TrajectoryPoint::GetAttDefs () const virtual
Reimplemented from G4TrajectoryPoint.
Definition at line 102 of file F04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 102 of file F04TrajectoryPoint.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues().
const G4ThreeVector F04TrajectoryPoint::GetMomentum () const inline
Definition at line 70 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 70 of file F04TrajectoryPoint.hh
References fMomentum.
G4StepStatus F04TrajectoryPoint::GetStepStatus () const inline
Definition at line 71 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 71 of file F04TrajectoryPoint.hh
References fStepStatus.
G4double F04TrajectoryPoint::GetTime () const inline
Definition at line 69 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 69 of file F04TrajectoryPoint.hh
References fTime.
G4String F04TrajectoryPoint::GetVolumeName () const inline
Definition at line 72 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 72 of file F04TrajectoryPoint.hh
References fVolumeName.
void F04TrajectoryPoint::operator delete (void * aTrajectoryPoint) inline
Definition at line 101 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 101 of file F04TrajectoryPoint.hh
References F04TrajPointAllocator.
void * F04TrajectoryPoint::operator new (size_t) inline
Definition at line 94 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 94 of file F04TrajectoryPoint.hh
References F04TrajPointAllocator.
G4bool F04TrajectoryPoint::operator== (const F04TrajectoryPoint & right) const inline
Definition at line 64 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 64 of file F04TrajectoryPoint.hh
Member Data Documentation
G4ThreeVector F04TrajectoryPoint::fMomentum private
Definition at line 86 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 86 of file F04TrajectoryPoint.hh
Referenced by CreateAttValues(), F04TrajectoryPoint(), and GetMomentum().
G4StepStatus F04TrajectoryPoint::fStepStatus private
Definition at line 87 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 87 of file F04TrajectoryPoint.hh
Referenced by CreateAttValues(), F04TrajectoryPoint(), and GetStepStatus().
G4double F04TrajectoryPoint::fTime private
Definition at line 85 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 85 of file F04TrajectoryPoint.hh
Referenced by CreateAttValues(), F04TrajectoryPoint(), and GetTime().
G4String F04TrajectoryPoint::fVolumeName private
Definition at line 88 of file F04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 88 of file F04TrajectoryPoint.hh
Referenced by CreateAttValues(), F04TrajectoryPoint(), and GetVolumeName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04TrajectoryPoint.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04TrajectoryPoint.cc