ECCE @ EIC Software: G4ParticleHPReactionWhiteBoard Class Reference
G4ParticleHPReactionWhiteBoard Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPReactionWhiteBoard.hh>
Public Member Functions
G4ParticleHPReactionWhiteBoard ()
~G4ParticleHPReactionWhiteBoard ()
void Dump ()
void SetTargZ (G4int Z)
void SetTargA (G4int A)
void SetTargM (G4int M)
G4int GetTargZ ()
G4int GetTargA ()
G4int GetTargM ()
bool AddRecord (std::pair< G4String, G4String >)
G4String GetValue (G4String)
G4int GetValueInInt (G4String)
G4double GetValueInDouble (G4String)
Private Attributes
G4int targZ
G4int targA
G4int targM
std::map< G4String, G4String > mapStringPair
Detailed Description
Definition at line 41 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPReactionWhiteBoard.hh
Constructor & Destructor Documentation
G4ParticleHPReactionWhiteBoard::G4ParticleHPReactionWhiteBoard ()
Definition at line 33 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 33 of file G4ParticleHPReactionWhiteBoard.cc
G4ParticleHPReactionWhiteBoard::~G4ParticleHPReactionWhiteBoard ()
Definition at line 40 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPReactionWhiteBoard.cc
References mapStringPair.
Member Function Documentation
bool G4ParticleHPReactionWhiteBoard::AddRecord (std::pair< G4String, G4String > new_record)
Definition at line 61 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPReactionWhiteBoard.cc
References G4cout, G4endl, and mapStringPair.
void G4ParticleHPReactionWhiteBoard::Dump ()
Definition at line 45 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPReactionWhiteBoard.cc
References G4cout, G4endl, it, mapStringPair, targA, targM, and targZ.
G4int G4ParticleHPReactionWhiteBoard::GetTargA () inline
Definition at line 54 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPReactionWhiteBoard.hh
References targA.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), and G4FissLib::ApplyYourself().
G4int G4ParticleHPReactionWhiteBoard::GetTargM () inline
Definition at line 55 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPReactionWhiteBoard.hh
References targM.
G4int G4ParticleHPReactionWhiteBoard::GetTargZ () inline
Definition at line 53 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPReactionWhiteBoard.hh
References targZ.
G4String G4ParticleHPReactionWhiteBoard::GetValue (G4String key)
Definition at line 71 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPReactionWhiteBoard.cc
References G4cout, G4endl, it, and mapStringPair.
Referenced by GetValueInDouble(), and GetValueInInt().
G4double G4ParticleHPReactionWhiteBoard::GetValueInDouble (G4String key)
Definition at line 92 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPReactionWhiteBoard.cc
References GetValue(), and x.
G4int G4ParticleHPReactionWhiteBoard::GetValueInInt (G4String key)
Definition at line 81 of file G4ParticleHPReactionWhiteBoard.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPReactionWhiteBoard.cc
References GetValue().
void G4ParticleHPReactionWhiteBoard::SetTargA (G4int A) inline
Definition at line 51 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPReactionWhiteBoard.hh
References A(), and targA.
Referenced by G4ParticleHPChannelList::ApplyYourself(), and G4ParticleHPChannel::ApplyYourself().
void G4ParticleHPReactionWhiteBoard::SetTargM (G4int M) inline
Definition at line 52 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPReactionWhiteBoard.hh
References targM.
Referenced by G4ParticleHPChannel::ApplyYourself().
void G4ParticleHPReactionWhiteBoard::SetTargZ (G4int Z) inline
Definition at line 50 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPReactionWhiteBoard.hh
References targZ, and Z.
Referenced by G4ParticleHPChannelList::ApplyYourself(), and G4ParticleHPChannel::ApplyYourself().
Member Data Documentation
std::map< G4String,G4String > G4ParticleHPReactionWhiteBoard::mapStringPair private
Definition at line 67 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ParticleHPReactionWhiteBoard.hh
Referenced by AddRecord(), Dump(), GetValue(), and ~G4ParticleHPReactionWhiteBoard().
G4int G4ParticleHPReactionWhiteBoard::targA private
Definition at line 65 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPReactionWhiteBoard.hh
Referenced by Dump(), GetTargA(), and SetTargA().
G4int G4ParticleHPReactionWhiteBoard::targM private
Definition at line 66 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPReactionWhiteBoard.hh
Referenced by Dump(), GetTargM(), and SetTargM().
G4int G4ParticleHPReactionWhiteBoard::targZ private
Definition at line 64 of file G4ParticleHPReactionWhiteBoard.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPReactionWhiteBoard.hh
Referenced by Dump(), GetTargZ(), and SetTargZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPReactionWhiteBoard.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPReactionWhiteBoard.cc