ECCE @ EIC Software: G4VHadronModelBuilder Class Reference
G4VHadronModelBuilder Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4VHadronModelBuilder.hh>
Public Member Functions
G4VHadronModelBuilder (const G4String &name="")
virtual ~G4VHadronModelBuilder ()
G4HadronicInteraction * GetModel ()
const G4String & GetName () const
Protected Member Functions
virtual G4HadronicInteraction * BuildModel ()=0
Private Member Functions
G4VHadronModelBuilder (G4VHadronModelBuilder &)
G4VHadronModelBuilder & operator= (const G4VHadronModelBuilder &right)
Private Attributes
G4HadronicInteraction * model
G4String name
Detailed Description
Definition at line 43 of file G4VHadronModelBuilder.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VHadronModelBuilder.hh
Constructor & Destructor Documentation
G4VHadronModelBuilder::G4VHadronModelBuilder (const G4String & name = "")
Definition at line 40 of file G4VHadronModelBuilder.cc.
View newest version in sPHENIX GitHub at line 40 of file G4VHadronModelBuilder.cc
G4VHadronModelBuilder::~G4VHadronModelBuilder () virtual
Definition at line 44 of file G4VHadronModelBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VHadronModelBuilder.cc
G4VHadronModelBuilder::G4VHadronModelBuilder (G4VHadronModelBuilder &) private
Member Function Documentation
virtual G4HadronicInteraction* G4VHadronModelBuilder::BuildModel () protected pure virtual
Implemented in G4QGSBuilder, and G4FTFBuilder.
Referenced by GetModel().
G4HadronicInteraction * G4VHadronModelBuilder::GetModel ()
Definition at line 47 of file G4VHadronModelBuilder.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VHadronModelBuilder.cc
References BuildModel(), and model.
Referenced by G4VHadronPhysics::BuildModel(), G4IonPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), and G4IonQMDPhysics::ConstructProcess().
const G4String & G4VHadronModelBuilder::GetName (void) const inline
Definition at line 69 of file G4VHadronModelBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VHadronModelBuilder.hh
References name.
Referenced by G4FTFBuilder::BuildModel(), and G4QGSBuilder::BuildModel().
G4VHadronModelBuilder& G4VHadronModelBuilder::operator= (const G4VHadronModelBuilder & right) private
Member Data Documentation
G4HadronicInteraction* G4VHadronModelBuilder::model private
Definition at line 65 of file G4VHadronModelBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VHadronModelBuilder.hh
Referenced by GetModel().
G4String G4VHadronModelBuilder::name private
Definition at line 66 of file G4VHadronModelBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VHadronModelBuilder.hh
Referenced by GetName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4VHadronModelBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4VHadronModelBuilder.cc