ECCE @ EIC Software: G4SPBaryon Class Reference
G4SPBaryon Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4SPBaryon.hh>
Public Member Functions
G4SPBaryon (G4Proton *aProton)
G4SPBaryon (G4Neutron *aNeutron)
G4SPBaryon (G4Lambda *aLambda)
G4SPBaryon (G4SigmaPlus *aSigmaPlus)
G4SPBaryon (G4SigmaZero *aSigmaZero)
G4SPBaryon (G4SigmaMinus *aSigmaMinus)
G4SPBaryon (G4XiMinus *aXiMinus)
G4SPBaryon (G4XiZero *aXiZero)
G4SPBaryon (G4OmegaMinus *anOmegaMinus)
G4SPBaryon (G4AntiProton *aAntiProton)
G4SPBaryon (G4AntiNeutron *aAntiNeutron)
G4SPBaryon (G4AntiLambda *aAntiLambda)
G4SPBaryon (G4AntiSigmaPlus *aAntiSigmaPlus)
G4SPBaryon (G4AntiSigmaZero *aAntiSigmaZero)
G4SPBaryon (G4AntiSigmaMinus *aAntiSigmaMinus)
G4SPBaryon (G4AntiXiMinus *aAntiXiMinus)
G4SPBaryon (G4AntiXiZero *aAntiXiZero)
G4SPBaryon (G4AntiOmegaMinus *anAntiOmegaMinus)
G4SPBaryon (G4ParticleDefinition *aDefinition)
~G4SPBaryon ()
G4ParticleDefinition * GetDefinition ()
void SampleQuarkAndDiquark (G4int &quark, G4int &diQuark) const
void FindDiquark (G4int quark, G4int &diQuark) const
G4int FindQuark (G4int diQuark) const
G4double GetProbability (G4int diQuark) const
G4int MatchDiQuarkAndGetQuark (const G4SPBaryon &aBaryon, G4int &aDiQuark) const
Private Member Functions
G4bool operator== (const G4SPBaryon &aBaryon) const
Private Attributes
G4ParticleDefinition * theDefinition
std::vector< G4SPPartonInfo * > thePartonInfo
Detailed Description
Definition at line 56 of file G4SPBaryon.hh.
View newest version in sPHENIX GitHub at line 56 of file G4SPBaryon.hh
Constructor & Destructor Documentation
G4SPBaryon::G4SPBaryon (G4Proton * aProton)
Definition at line 159 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 159 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4Neutron * aNeutron)
Definition at line 179 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 179 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4Lambda * aLambda)
Definition at line 199 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 199 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4SigmaPlus * aSigmaPlus)
Definition at line 223 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 223 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4SigmaZero * aSigmaZero)
Definition at line 243 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 243 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4SigmaMinus * aSigmaMinus)
Definition at line 267 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 267 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4XiMinus * aXiMinus)
Definition at line 287 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 287 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4XiZero * aXiZero)
Definition at line 307 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 307 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4OmegaMinus * anOmegaMinus)
Definition at line 327 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 327 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiProton * aAntiProton)
Definition at line 169 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 169 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiNeutron * aAntiNeutron)
Definition at line 189 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 189 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiLambda * aAntiLambda)
Definition at line 211 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 211 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiSigmaPlus * aAntiSigmaPlus)
Definition at line 233 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 233 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiSigmaZero * aAntiSigmaZero)
Definition at line 255 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 255 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiSigmaMinus * aAntiSigmaMinus)
Definition at line 277 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 277 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiXiMinus * aAntiXiMinus)
Definition at line 297 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 297 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiXiZero * aAntiXiZero)
Definition at line 317 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 317 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4AntiOmegaMinus * anAntiOmegaMinus)
Definition at line 335 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 335 of file G4SPBaryon.cc
References theDefinition, and thePartonInfo.
G4SPBaryon::G4SPBaryon (G4ParticleDefinition * aDefinition)
Definition at line 344 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 344 of file G4SPBaryon.cc
References G4ParticleTable::GetParticleTable(), theDefinition, and thePartonInfo.
G4SPBaryon::~G4SPBaryon ()
Definition at line 436 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 436 of file G4SPBaryon.cc
References thePartonInfo.
Member Function Documentation
void G4SPBaryon::FindDiquark (G4int quark, G4int & diQuark) const
Definition at line 130 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 130 of file G4SPBaryon.cc
References kdfinder::abs(), G4UniformRand, sum, and thePartonInfo.
Referenced by G4BaryonSplitter::FindDiquark().
G4int G4SPBaryon::FindQuark (G4int diQuark) const
Definition at line 32 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 32 of file G4SPBaryon.cc
References kdfinder::abs(), G4UniformRand, GetProbability(), sum, and thePartonInfo.
G4ParticleDefinition* G4SPBaryon::GetDefinition () inline
Definition at line 87 of file G4SPBaryon.hh.
View newest version in sPHENIX GitHub at line 87 of file G4SPBaryon.hh
References theDefinition.
G4double G4SPBaryon::GetProbability (G4int diQuark) const
Definition at line 56 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 56 of file G4SPBaryon.cc
References kdfinder::abs(), sum, and thePartonInfo.
Referenced by FindQuark(), and MatchDiQuarkAndGetQuark().
G4int G4SPBaryon::MatchDiQuarkAndGetQuark (const G4SPBaryon & aBaryon, G4int & aDiQuark) const
Definition at line 73 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 73 of file G4SPBaryon.cc
References G4UniformRand, GetProbability(), thePartonInfo, and G4INCL::CrossSections::total().
G4bool G4SPBaryon::operator== (const G4SPBaryon & aBaryon) const private
void G4SPBaryon::SampleQuarkAndDiquark (G4int & quark, G4int & diQuark) const
Definition at line 100 of file G4SPBaryon.cc.
View newest version in sPHENIX GitHub at line 100 of file G4SPBaryon.cc
References G4UniformRand, G4ParticleDefinition::GetPDGEncoding(), sum, theDefinition, and thePartonInfo.
Referenced by G4BaryonSplitter::SplitBarion().
Member Data Documentation
G4ParticleDefinition* G4SPBaryon::theDefinition private
Definition at line 95 of file G4SPBaryon.hh.
View newest version in sPHENIX GitHub at line 95 of file G4SPBaryon.hh
Referenced by G4SPBaryon(), GetDefinition(), and SampleQuarkAndDiquark().
std::vector<G4SPPartonInfo *> G4SPBaryon::thePartonInfo private
Definition at line 96 of file G4SPBaryon.hh.
View newest version in sPHENIX GitHub at line 96 of file G4SPBaryon.hh
Referenced by FindDiquark(), FindQuark(), G4SPBaryon(), GetProbability(), MatchDiQuarkAndGetQuark(), SampleQuarkAndDiquark(), and ~G4SPBaryon().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4SPBaryon.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4SPBaryon.cc