ECCE @ EIC Software: G4Scene Class Reference
G4Scene Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4Scene.hh>
Classes
struct Model
Public Types
enum { UNLIMITED = -1 }
Public Member Functions
G4Scene (const G4String &name="scene-with-unspecified-name")
~G4Scene ()
G4bool operator== (const G4Scene &) const
G4bool operator!= (const G4Scene &) const
const G4String & GetName () const
G4bool IsEmpty () const
const std::vector< Model > & GetRunDurationModelList () const
const std::vector< Model > & GetEndOfEventModelList () const
const std::vector< Model > & GetEndOfRunModelList () const
const G4VisExtent & GetExtent () const
const G4Point3D & GetStandardTargetPoint () const
G4bool GetRefreshAtEndOfEvent () const
G4int GetMaxNumberOfKeptEvents () const
G4bool GetRefreshAtEndOfRun () const
G4bool AddRunDurationModel (G4VModel *, G4bool warn=false)
G4bool AddWorldIfEmpty (G4bool warn=false)
G4bool AddEndOfEventModel (G4VModel *, G4bool warn=false)
G4bool AddEndOfRunModel (G4VModel *, G4bool warn=false)
void SetName (const G4String &)
std::vector< Model > & SetRunDurationModelList ()
std::vector< Model > & SetEndOfEventModelList ()
std::vector< Model > & SetEndOfRunModelList ()
void SetRefreshAtEndOfEvent (G4bool)
void SetMaxNumberOfKeptEvents (G4int)
void SetRefreshAtEndOfRun (G4bool)
void CalculateExtent ()
Private Attributes
G4String fName
std::vector< Model > fRunDurationModelList
std::vector< Model > fEndOfEventModelList
std::vector< Model > fEndOfRunModelList
G4VisExtent fExtent
G4Point3D fStandardTargetPoint
G4bool fRefreshAtEndOfEvent
G4bool fRefreshAtEndOfRun
G4int fMaxNumberOfKeptEvents
Friends
std::ostream & operator<< (std::ostream &os, const G4Scene &d)
Detailed Description
Definition at line 48 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 48 of file G4Scene.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
UNLIMITED
Definition at line 54 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 54 of file G4Scene.hh
Constructor & Destructor Documentation
G4Scene::G4Scene (const G4String & name = "scene-with-unspecified-name")
Definition at line 41 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 41 of file G4Scene.cc
G4Scene::~G4Scene ()
Definition at line 48 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 48 of file G4Scene.cc
Member Function Documentation
G4bool G4Scene::AddEndOfEventModel (G4VModel * pModel, G4bool warn = false)
Definition at line 199 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 199 of file G4Scene.cc
References fEndOfEventModelList, fName, G4cout, and G4endl.
G4bool G4Scene::AddEndOfRunModel (G4VModel * pModel, G4bool warn = false)
Definition at line 219 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 219 of file G4Scene.cc
References fEndOfRunModelList, fName, G4cout, and G4endl.
G4bool G4Scene::AddRunDurationModel (G4VModel * pModel, G4bool warn = false)
Definition at line 50 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 50 of file G4Scene.cc
References CalculateExtent(), fName, fRunDurationModelList, G4cout, G4endl, and G4VModel::GetGlobalTag().
Referenced by AddWorldIfEmpty(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
G4bool G4Scene::AddWorldIfEmpty (G4bool warn = false)
Definition at line 163 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 163 of file G4Scene.cc
References AddRunDurationModel(), G4cout, G4endl, G4TransportationManager::GetTransportationManager(), and IsEmpty().
Referenced by G4RayTracerSceneHandler::G4RayTracerSceneHandler().
void G4Scene::CalculateExtent ()
Definition at line 109 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 109 of file G4Scene.cc
References G4BoundingExtentScene::AccrueBoundingExtent(), fEndOfEventModelList, fEndOfRunModelList, fExtent, fRunDurationModelList, fStandardTargetPoint, G4Exception(), G4BoundingExtentScene::GetBoundingExtent(), G4VisExtent::GetExtentCentre(), G4VisExtent::GetExtentRadius(), and JustWarning.
Referenced by AddRunDurationModel(), G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), and G4VisCommandSceneNotifyHandlers::SetNewValue().
const std::vector<Model>& G4Scene::GetEndOfEventModelList () const
Referenced by G4GMocrenFileSceneHandler::GFBeginModeling(), and G4VisCommandSceneAddTrajectories::SetNewValue().
const std::vector<Model>& G4Scene::GetEndOfRunModelList () const
const G4VisExtent& G4Scene::GetExtent () const
Referenced by G4VSceneHandler::AddPrimitive(), G4VSceneHandler::CreateSectionSolid(), G4VSceneHandler::GetExtent(), G4VSceneHandler::ProcessScene(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneShowExtents::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4RayTracerViewer::SetView().
G4int G4Scene::GetMaxNumberOfKeptEvents () const
Referenced by G4VisManager::EndOfEvent(), and G4VisManager::EndOfRun().
const G4String& G4Scene::GetName () const
Referenced by G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSceneList::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
G4bool G4Scene::GetRefreshAtEndOfEvent () const
Referenced by G4VisManager::EndOfEvent(), G4VSceneHandler::ProcessScene(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), and G4VisCommandReviewKeptEvents::SetNewValue().
G4bool G4Scene::GetRefreshAtEndOfRun () const
Referenced by G4VisManager::EndOfRun(), G4VSceneHandler::ProcessScene(), G4VisCommandSceneEndOfEventAction::SetNewValue(), and G4VisCommandSceneEndOfRunAction::SetNewValue().
const std::vector<Model>& G4Scene::GetRunDurationModelList () const
Referenced by G4ASCIITreeSceneHandler::EndModeling(), G4VisCommandViewerCentreOn::SetNewValue(), and G4VisCommandViewerRefresh::SetNewValue().
const G4Point3D& G4Scene::GetStandardTargetPoint () const
Referenced by G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), and G4RayTracerViewer::SetView().
G4bool G4Scene::IsEmpty () const
Referenced by AddWorldIfEmpty().
G4bool G4Scene::operator!= (const G4Scene & scene) const
Definition at line 296 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 296 of file G4Scene.cc
References fEndOfEventModelList, fEndOfRunModelList, fExtent, fMaxNumberOfKeptEvents, fRefreshAtEndOfEvent, fRefreshAtEndOfRun, fRunDurationModelList, and fStandardTargetPoint.
G4bool G4Scene::operator== (const G4Scene &) const
std::vector<Model>& G4Scene::SetEndOfEventModelList ()
Referenced by G4VisCommandSceneActivateModel::SetNewValue().
std::vector<Model>& G4Scene::SetEndOfRunModelList ()
Referenced by G4VisCommandSceneActivateModel::SetNewValue().
void G4Scene::SetMaxNumberOfKeptEvents (G4int)
Referenced by G4VisCommandSceneEndOfEventAction::SetNewValue().
void G4Scene::SetName (const G4String &)
void G4Scene::SetRefreshAtEndOfEvent (G4bool)
Referenced by G4VisCommandSceneEndOfEventAction::SetNewValue(), and G4VisCommandReviewKeptEvents::SetNewValue().
void G4Scene::SetRefreshAtEndOfRun (G4bool)
Referenced by G4VisCommandSceneEndOfRunAction::SetNewValue().
std::vector<Model>& G4Scene::SetRunDurationModelList ()
Referenced by G4VisCommandSceneActivateModel::SetNewValue().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4Scene & d) friend
Definition at line 239 of file G4Scene.cc.
View newest version in sPHENIX GitHub at line 239 of file G4Scene.cc
Member Data Documentation
std::vector<Model> G4Scene::fEndOfEventModelList private
Definition at line 179 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 179 of file G4Scene.hh
Referenced by AddEndOfEventModel(), CalculateExtent(), operator!=(), and operator<<().
std::vector<Model> G4Scene::fEndOfRunModelList private
Definition at line 180 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 180 of file G4Scene.hh
Referenced by AddEndOfRunModel(), CalculateExtent(), operator!=(), and operator<<().
G4VisExtent G4Scene::fExtent private
Definition at line 181 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Scene.hh
Referenced by CalculateExtent(), operator!=(), and operator<<().
G4int G4Scene::fMaxNumberOfKeptEvents private
Definition at line 185 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 185 of file G4Scene.hh
Referenced by operator!=(), and operator<<().
G4String G4Scene::fName private
Definition at line 177 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 177 of file G4Scene.hh
Referenced by AddEndOfEventModel(), AddEndOfRunModel(), and AddRunDurationModel().
G4bool G4Scene::fRefreshAtEndOfEvent private
Definition at line 183 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 183 of file G4Scene.hh
Referenced by operator!=(), and operator<<().
G4bool G4Scene::fRefreshAtEndOfRun private
Definition at line 184 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Scene.hh
Referenced by operator!=(), and operator<<().
std::vector<Model> G4Scene::fRunDurationModelList private
Definition at line 178 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 178 of file G4Scene.hh
Referenced by AddRunDurationModel(), CalculateExtent(), operator!=(), and operator<<().
G4Point3D G4Scene::fStandardTargetPoint private
Definition at line 182 of file G4Scene.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Scene.hh
Referenced by CalculateExtent(), operator!=(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4Scene.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4Scene.cc