ECCE @ EIC Software: G4SmartTrackStack Class Reference
G4SmartTrackStack Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4SmartTrackStack.hh>
Public Member Functions
G4SmartTrackStack ()
~G4SmartTrackStack ()
G4SmartTrackStack & operator= (const G4SmartTrackStack &)=delete
G4bool operator== (const G4SmartTrackStack &) const =delete
G4bool operator!= (const G4SmartTrackStack &) const =delete
void PushToStack (const G4StackedTrack &aStackedTrack)
G4StackedTrack PopFromStack ()
void clear ()
void clearAndDestroy ()
void TransferTo (G4TrackStack *aStack)
G4double getEnergyOfStack (G4TrackStack *aTrackStack)
void dumpStatistics ()
G4int GetNTrack () const
G4int GetMaxNTrack () const
Private Member Functions
G4int n_stackedTrack () const
Private Attributes
G4int fTurn
G4int nTurn
G4double energies [5]
G4TrackStack * stacks [5]
G4int maxNTracks
G4int nTracks
Detailed Description
Definition at line 40 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 40 of file G4SmartTrackStack.hh
Constructor & Destructor Documentation
G4SmartTrackStack::G4SmartTrackStack ()
Definition at line 45 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 45 of file G4SmartTrackStack.cc
References energies, nTurn, and stacks.
G4SmartTrackStack::~G4SmartTrackStack ()
Definition at line 55 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SmartTrackStack.cc
References nTurn, and stacks.
Member Function Documentation
void G4SmartTrackStack::clear (void)
Definition at line 140 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 140 of file G4SmartTrackStack.cc
References energies, fTurn, nTracks, nTurn, and stacks.
void G4SmartTrackStack::clearAndDestroy ()
Definition at line 151 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 151 of file G4SmartTrackStack.cc
References G4TrackStack::clearAndDestroy(), energies, fTurn, nTracks, nTurn, and stacks.
void G4SmartTrackStack::dumpStatistics ()
Definition at line 33 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 33 of file G4SmartTrackStack.cc
References G4cerr, G4endl, G4TrackStack::GetNTrack(), G4TrackStack::getTotalEnergy(), nTurn, and stacks.
G4double G4SmartTrackStack::getEnergyOfStack (G4TrackStack * aTrackStack)
G4int G4SmartTrackStack::GetMaxNTrack () const inline
Definition at line 60 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 60 of file G4SmartTrackStack.hh
References maxNTracks.
G4int G4SmartTrackStack::GetNTrack () const inline
Definition at line 59 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 59 of file G4SmartTrackStack.hh
References nTracks.
Referenced by n_stackedTrack(), PopFromStack(), and PushToStack().
G4int G4SmartTrackStack::n_stackedTrack () const inline private
Definition at line 64 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 64 of file G4SmartTrackStack.hh
References GetNTrack(), and stacks.
G4bool G4SmartTrackStack::operator!= (const G4SmartTrackStack &) const delete
G4SmartTrackStack& G4SmartTrackStack::operator= (const G4SmartTrackStack &) delete
G4bool G4SmartTrackStack::operator== (const G4SmartTrackStack &) const delete
G4StackedTrack G4SmartTrackStack::PopFromStack ()
Definition at line 72 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 72 of file G4SmartTrackStack.cc
References energies, fTurn, G4Track::GetDynamicParticle(), GetNTrack(), G4DynamicParticle::GetTotalEnergy(), G4StackedTrack::GetTrack(), nTracks, nTurn, G4TrackStack::PopFromStack(), and stacks.
void G4SmartTrackStack::PushToStack (const G4StackedTrack & aStackedTrack)
Definition at line 102 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 102 of file G4SmartTrackStack.cc
References electronCode, energies, fTurn, gammaCode, G4Track::GetDynamicParticle(), GetNTrack(), G4TrackStack::GetNTrack(), G4Track::GetParentID(), G4DynamicParticle::GetPDGcode(), G4TrackStack::GetSafetyValue1(), G4TrackStack::GetSafetyValue2(), G4DynamicParticle::GetTotalEnergy(), G4StackedTrack::GetTrack(), maxNTracks, neutronCode, nTracks, positronCode, G4TrackStack::PushToStack(), and stacks.
Referenced by G4TrackStack::TransferTo().
void G4SmartTrackStack::TransferTo (G4TrackStack * aStack)
Definition at line 63 of file G4SmartTrackStack.cc.
View newest version in sPHENIX GitHub at line 63 of file G4SmartTrackStack.cc
References nTracks, nTurn, stacks, and G4TrackStack::TransferTo().
Member Data Documentation
G4double G4SmartTrackStack::energies[5] private
Definition at line 77 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 77 of file G4SmartTrackStack.hh
Referenced by clear(), clearAndDestroy(), G4SmartTrackStack(), PopFromStack(), and PushToStack().
G4int G4SmartTrackStack::fTurn private
Definition at line 75 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 75 of file G4SmartTrackStack.hh
Referenced by clear(), clearAndDestroy(), PopFromStack(), and PushToStack().
G4int G4SmartTrackStack::maxNTracks private
Definition at line 84 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 84 of file G4SmartTrackStack.hh
Referenced by GetMaxNTrack(), and PushToStack().
G4int G4SmartTrackStack::nTracks private
Definition at line 85 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 85 of file G4SmartTrackStack.hh
Referenced by clear(), clearAndDestroy(), GetNTrack(), PopFromStack(), PushToStack(), and TransferTo().
G4int G4SmartTrackStack::nTurn private
Definition at line 76 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 76 of file G4SmartTrackStack.hh
Referenced by clear(), clearAndDestroy(), dumpStatistics(), G4SmartTrackStack(), PopFromStack(), TransferTo(), and ~G4SmartTrackStack().
G4TrackStack* G4SmartTrackStack::stacks[5] private
Definition at line 78 of file G4SmartTrackStack.hh.
View newest version in sPHENIX GitHub at line 78 of file G4SmartTrackStack.hh
Referenced by clear(), clearAndDestroy(), dumpStatistics(), G4SmartTrackStack(), n_stackedTrack(), PopFromStack(), PushToStack(), TransferTo(), and ~G4SmartTrackStack().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4SmartTrackStack.hh
geant4/tree/geant4-10.6-release/source/event/src/G4SmartTrackStack.cc