ECCE @ EIC Software: G4ManyFastLists_iterator< OBJECT > Struct Template Reference
G4ManyFastLists_iterator< OBJECT > Struct Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh>
Public Types
typedef G4FastList< G4FastList
< OBJECT > > ManyLists
typedef G4ManyFastLists_iterator _Self
typedef G4FastListNode< OBJECT > _Node
Public Member Functions
G4ManyFastLists_iterator (G4FastList_iterator< OBJECT > __x, typename ManyLists::iterator __it, ManyLists *__lists)
G4ManyFastLists_iterator (const G4ManyFastLists_iterator &__x)=default
_Self & operator= (const G4ManyFastLists_iterator &__x)=default
_Node * GetNode ()
G4FastList< OBJECT > * GetTrackList ()
OBJECT * operator* ()
const OBJECT * operator* () const
OBJECT * operator-> ()
const OBJECT * operator-> () const
_Self UpdateToNextValidList ()
_Self & operator++ ()
_Self operator++ (int)
_Self & operator-- ()
_Self operator-- (int)
G4bool operator== (const _Self &__x) const
G4bool operator!= (const _Self &__x) const
Public Attributes
G4FastList_iterator< OBJECT > fIterator
ManyLists::iterator fCurrentListIt
ManyLists * fLists
Protected Member Functions
void HasReachedEnd ()
Private Member Functions
G4ManyFastLists_iterator ()=default
Detailed Description
template<typename OBJECT>
struct G4ManyFastLists_iterator< OBJECT >
Definition at line 66 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4FastList.hh
Member Typedef Documentation
template<typename OBJECT> typedef G4FastListNode<OBJECT> G4ManyFastLists_iterator< OBJECT >::_Node
Definition at line 237 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 237 of file G4ManyFastLists.hh
template<typename OBJECT> typedef G4ManyFastLists_iterator G4ManyFastLists_iterator< OBJECT >::_Self
Definition at line 236 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 236 of file G4ManyFastLists.hh
template<typename OBJECT> typedef G4FastList<G4FastList<OBJECT> > G4ManyFastLists_iterator< OBJECT >::ManyLists
Definition at line 234 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 234 of file G4ManyFastLists.hh
Constructor & Destructor Documentation
template<typename OBJECT> G4ManyFastLists_iterator< OBJECT >::G4ManyFastLists_iterator () private default
template<typename OBJECT> G4ManyFastLists_iterator< OBJECT >::G4ManyFastLists_iterator (G4FastList_iterator< OBJECT > __x, typename ManyLists::iterator __it, ManyLists * __lists) inline explicit
Definition at line 247 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 247 of file G4ManyFastLists.hh
template<typename OBJECT> G4ManyFastLists_iterator< OBJECT >::G4ManyFastLists_iterator (const G4ManyFastLists_iterator< OBJECT > & __x) default
Member Function Documentation
template<typename OBJECT> _Node* G4ManyFastLists_iterator< OBJECT >::GetNode () inline
Definition at line 257 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 257 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fIterator.
template<typename OBJECT> G4FastList<OBJECT>* G4ManyFastLists_iterator< OBJECT >::GetTrackList () inline
Definition at line 262 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 262 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fCurrentListIt.
template<typename OBJECT> void G4ManyFastLists_iterator< OBJECT >::HasReachedEnd () inline protected
Definition at line 357 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 357 of file G4ManyFastLists.hh
References G4FastList< OBJECT >::empty(), G4FastList< OBJECT >::end(), G4ManyFastLists_iterator< OBJECT >::fIterator, and G4ManyFastLists_iterator< OBJECT >::fLists.
template<typename OBJECT> G4bool G4ManyFastLists_iterator< OBJECT >::operator!= (const _Self & __x) const inline
Definition at line 351 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 351 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::operator==().
template<typename OBJECT> OBJECT* G4ManyFastLists_iterator< OBJECT >::operator* () inline
Definition at line 267 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 267 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fIterator.
template<typename OBJECT> const OBJECT* G4ManyFastLists_iterator< OBJECT >::operator* () const inline
Definition at line 271 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 271 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fIterator.
template<typename OBJECT> _Self& G4ManyFastLists_iterator< OBJECT >::operator++ ()
Referenced by G4ManyFastLists_iterator< OBJECT >::operator++().
template<typename OBJECT> _Self G4ManyFastLists_iterator< OBJECT >::operator++ (int) inline
Definition at line 287 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 287 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::operator++().
template<typename OBJECT> _Self& G4ManyFastLists_iterator< OBJECT >::operator-- () inline
Definition at line 293 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 293 of file G4ManyFastLists.hh
References G4FastList< OBJECT >::begin(), G4FastList< OBJECT >::empty(), G4FastList< OBJECT >::end(), G4ManyFastLists_iterator< OBJECT >::fCurrentListIt, G4ManyFastLists_iterator< OBJECT >::fIterator, and G4ManyFastLists_iterator< OBJECT >::fLists.
Referenced by G4ManyFastLists_iterator< OBJECT >::operator--().
template<typename OBJECT> _Self G4ManyFastLists_iterator< OBJECT >::operator-- (int) inline
Definition at line 341 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 341 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::operator--().
template<typename OBJECT> OBJECT* G4ManyFastLists_iterator< OBJECT >::operator-> () inline
Definition at line 275 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 275 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fIterator.
template<typename OBJECT> const OBJECT* G4ManyFastLists_iterator< OBJECT >::operator-> () const inline
Definition at line 279 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 279 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fIterator.
template<typename OBJECT> _Self& G4ManyFastLists_iterator< OBJECT >::operator= (const G4ManyFastLists_iterator< OBJECT > & __x) default
template<typename OBJECT> G4bool G4ManyFastLists_iterator< OBJECT >::operator== (const _Self & __x) const inline
Definition at line 346 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 346 of file G4ManyFastLists.hh
References G4ManyFastLists_iterator< OBJECT >::fCurrentListIt, and G4ManyFastLists_iterator< OBJECT >::fIterator.
Referenced by G4ManyFastLists_iterator< OBJECT >::operator!=().
template<typename OBJECT> _Self G4ManyFastLists_iterator< OBJECT >::UpdateToNextValidList ()
Member Data Documentation
template<typename OBJECT> ManyLists::iterator G4ManyFastLists_iterator< OBJECT >::fCurrentListIt
Definition at line 240 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 240 of file G4ManyFastLists.hh
Referenced by G4ManyFastLists_iterator< OBJECT >::GetTrackList(), G4ManyFastLists_iterator< OBJECT >::operator--(), and G4ManyFastLists_iterator< OBJECT >::operator==().
template<typename OBJECT> G4FastList_iterator<OBJECT> G4ManyFastLists_iterator< OBJECT >::fIterator
Definition at line 239 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 239 of file G4ManyFastLists.hh
Referenced by G4ManyFastLists_iterator< OBJECT >::GetNode(), G4ManyFastLists_iterator< OBJECT >::HasReachedEnd(), G4ManyFastLists_iterator< OBJECT >::operator*(), G4ManyFastLists_iterator< OBJECT >::operator--(), G4ManyFastLists_iterator< OBJECT >::operator->(), and G4ManyFastLists_iterator< OBJECT >::operator==().
template<typename OBJECT> ManyLists* G4ManyFastLists_iterator< OBJECT >::fLists
Definition at line 241 of file G4ManyFastLists.hh.
View newest version in sPHENIX GitHub at line 241 of file G4ManyFastLists.hh
Referenced by G4ManyFastLists_iterator< OBJECT >::HasReachedEnd(), and G4ManyFastLists_iterator< OBJECT >::operator--().
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ManyFastLists.hh