ECCE @ EIC Software: G4EnergyLossForExtrapolator Class Reference
G4EnergyLossForExtrapolator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4EnergyLossForExtrapolator.hh>
Public Member Functions
G4EnergyLossForExtrapolator (G4int verb=1)
~G4EnergyLossForExtrapolator ()
G4double ComputeDEDX (G4double kinEnergy, const G4ParticleDefinition *)
G4double ComputeRange (G4double kinEnergy, const G4ParticleDefinition *)
G4double ComputeEnergy (G4double range, const G4ParticleDefinition *)
G4double EnergyAfterStep (G4double kinEnergy, G4double step, const G4Material *, const G4ParticleDefinition *)
G4double EnergyBeforeStep (G4double kinEnergy, G4double step, const G4Material *, const G4ParticleDefinition *)
G4double TrueStepLength (G4double kinEnergy, G4double step, const G4Material *, const G4ParticleDefinition *part)
G4double EnergyAfterStep (G4double kinEnergy, G4double step, const G4Material *, const G4String &particleName)
G4double EnergyBeforeStep (G4double kinEnergy, G4double step, const G4Material *, const G4String &particleName)
G4double AverageScatteringAngle (G4double kinEnergy, G4double step, const G4Material *, const G4ParticleDefinition *part)
G4double AverageScatteringAngle (G4double kinEnergy, G4double step, const G4Material *, const G4String &particleName)
G4double ComputeTrueStep (const G4Material *, const G4ParticleDefinition *part, G4double kinEnergy, G4double stepLength)
G4double EnergyDispersion (G4double kinEnergy, G4double step, const G4Material *, const G4ParticleDefinition *)
G4double EnergyDispersion (G4double kinEnergy, G4double step, const G4Material *, const G4String &particleName)
void SetVerbose (G4int val)
void SetMinKinEnergy (G4double)
void SetMaxKinEnergy (G4double)
void SetMaxEnergyTransfer (G4double)
Private Member Functions
void Initialisation ()
void BuildTables ()
G4bool SetupKinematics (const G4ParticleDefinition *, const G4Material *, G4double kinEnergy)
const G4ParticleDefinition * FindParticle (const G4String &name)
G4double ComputeValue (G4double x, const G4PhysicsTable *table, size_t idx)
const G4PhysicsTable * GetPhysicsTable (ExtTableType type) const
G4EnergyLossForExtrapolator & operator= (const G4EnergyLossForExtrapolator &right)
G4EnergyLossForExtrapolator (const G4EnergyLossForExtrapolator &)
Private Attributes
const G4ParticleDefinition * currentParticle
const G4ParticleDefinition * electron
const G4ParticleDefinition * positron
const G4ParticleDefinition * muonPlus
const G4ParticleDefinition * muonMinus
const G4ParticleDefinition * proton
G4String currentParticleName
size_t idxDedxElectron
size_t idxDedxPositron
size_t idxDedxMuon
size_t idxDedxProton
size_t idxRangeElectron
size_t idxRangePositron
size_t idxRangeMuon
size_t idxRangeProton
size_t idxInvRangeElectron
size_t idxInvRangePositron
size_t idxInvRangeMuon
size_t idxInvRangeProton
size_t idxMscElectron
const G4Material * currentMaterial
G4int index
G4double electronDensity
G4double radLength
G4double mass
G4double charge2
G4double kineticEnergy
G4double gam
G4double bg2
G4double beta2
G4double tmax
G4double linLossLimit
G4double emin
G4double emax
G4double maxEnergyTransfer
G4int nbins
G4int nmat
G4int verbose
Static Private Attributes
static G4TablesForExtrapolator * tables = nullptr
Detailed Description
Definition at line 67 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EnergyLossForExtrapolator.hh
Constructor & Destructor Documentation
G4EnergyLossForExtrapolator::G4EnergyLossForExtrapolator (G4int verb = 1) explicit
Definition at line 70 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 70 of file G4EnergyLossForExtrapolator.cc
References beta2, bg2, charge2, currentMaterial, currentParticle, electron, electronDensity, emax, emin, gam, idxDedxElectron, idxDedxMuon, idxDedxPositron, idxDedxProton, idxInvRangeElectron, idxInvRangeMuon, idxInvRangePositron, idxInvRangeProton, idxMscElectron, idxRangeElectron, idxRangeMuon, idxRangePositron, idxRangeProton, index, kineticEnergy, linLossLimit, mass, MeV, muonMinus, muonPlus, nbins, nmat, positron, proton, radLength, TeV, and tmax.
G4EnergyLossForExtrapolator::~G4EnergyLossForExtrapolator ()
Definition at line 97 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 97 of file G4EnergyLossForExtrapolator.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and tables.
G4EnergyLossForExtrapolator::G4EnergyLossForExtrapolator (const G4EnergyLossForExtrapolator &) private
Member Function Documentation
G4double G4EnergyLossForExtrapolator::AverageScatteringAngle (G4double kinEnergy, G4double step, const G4Material * mat, const G4ParticleDefinition * part) inline
Definition at line 251 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 251 of file G4EnergyLossForExtrapolator.hh
References beta2, charge2, G4Log(), gam, mass, max, CLHEP::MeV, radLength, SetupKinematics(), t, theta(), and y.
Referenced by AverageScatteringAngle(), and ComputeTrueStep().
G4double G4EnergyLossForExtrapolator::AverageScatteringAngle (G4double kinEnergy, G4double step, const G4Material * mat, const G4String & particleName) inline
Definition at line 230 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 230 of file G4EnergyLossForExtrapolator.hh
References AverageScatteringAngle(), and FindParticle().
void G4EnergyLossForExtrapolator::BuildTables () private
Definition at line 347 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 347 of file G4EnergyLossForExtrapolator.cc
References emax, emin, G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4Material::GetNumberOfMaterials(), G4TablesForExtrapolator::Initialisation(), nbins, nmat, tables, and verbose.
Referenced by Initialisation().
G4double G4EnergyLossForExtrapolator::ComputeDEDX (G4double kinEnergy, const G4ParticleDefinition * part)
Definition at line 261 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 261 of file G4EnergyLossForExtrapolator.cc
References charge2, ComputeValue(), e, electron, fDedxElectron, fDedxMuon, fDedxPositron, fDedxProton, GetPhysicsTable(), idxDedxElectron, idxDedxMuon, idxDedxPositron, idxDedxProton, mass, muonMinus, muonPlus, positron, source.hepunit::proton_mass_c2, and x.
Referenced by EnergyAfterStep(), and EnergyBeforeStep().
G4double G4EnergyLossForExtrapolator::ComputeEnergy (G4double range, const G4ParticleDefinition * part)
Definition at line 303 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 303 of file G4EnergyLossForExtrapolator.cc
References charge2, ComputeValue(), electron, fInvRangeElectron, fInvRangeMuon, fInvRangePositron, fInvRangeProton, GetPhysicsTable(), idxInvRangeElectron, idxInvRangeMuon, idxInvRangePositron, idxInvRangeProton, mass, muonMinus, muonPlus, positron, source.hepunit::proton_mass_c2, r, and x.
Referenced by EnergyAfterStep(), and EnergyBeforeStep().
G4double G4EnergyLossForExtrapolator::ComputeRange (G4double kinEnergy, const G4ParticleDefinition * part)
Definition at line 281 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 281 of file G4EnergyLossForExtrapolator.cc
References charge2, ComputeValue(), e, electron, fRangeElectron, fRangeMuon, fRangePositron, fRangeProton, GetPhysicsTable(), idxRangeElectron, idxRangeMuon, idxRangePositron, idxRangeProton, mass, muonMinus, muonPlus, positron, source.hepunit::proton_mass_c2, and x.
Referenced by EnergyAfterStep(), EnergyBeforeStep(), and TrueStepLength().
G4double G4EnergyLossForExtrapolator::ComputeTrueStep (const G4Material * mat, const G4ParticleDefinition * part, G4double kinEnergy, G4double stepLength) inline
Definition at line 270 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 270 of file G4EnergyLossForExtrapolator.hh
References AverageScatteringAngle(), and theta().
Referenced by EnergyDispersion(), and TrueStepLength().
G4double G4EnergyLossForExtrapolator::ComputeValue (G4double x, const G4PhysicsTable * table, size_t idx) inline private
Definition at line 299 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 299 of file G4EnergyLossForExtrapolator.hh
References index.
Referenced by ComputeDEDX(), ComputeEnergy(), ComputeRange(), and TrueStepLength().
G4double G4EnergyLossForExtrapolator::EnergyAfterStep (G4double kinEnergy, G4double step, const G4Material * mat, const G4ParticleDefinition * part)
Definition at line 116 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 116 of file G4EnergyLossForExtrapolator.cc
References ComputeDEDX(), ComputeEnergy(), ComputeRange(), Initialisation(), linLossLimit, nmat, r, r1, SetupKinematics(), Acts::Test::step(), and TrueStepLength().
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), EnergyAfterStep(), and G4ErrorEnergyLoss::GetContinuousStepLimit().
G4double G4EnergyLossForExtrapolator::EnergyAfterStep (G4double kinEnergy, G4double step, const G4Material * mat, const G4String & particleName) inline
Definition at line 208 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 208 of file G4EnergyLossForExtrapolator.hh
References EnergyAfterStep(), and FindParticle().
G4double G4EnergyLossForExtrapolator::EnergyBeforeStep (G4double kinEnergy, G4double step, const G4Material * mat, const G4ParticleDefinition * part)
Definition at line 141 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 141 of file G4EnergyLossForExtrapolator.cc
References ComputeDEDX(), ComputeEnergy(), ComputeRange(), Initialisation(), linLossLimit, nmat, r, r1, SetupKinematics(), Acts::Test::step(), and TrueStepLength().
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), EnergyBeforeStep(), and G4ErrorEnergyLoss::GetContinuousStepLimit().
G4double G4EnergyLossForExtrapolator::EnergyBeforeStep (G4double kinEnergy, G4double step, const G4Material * mat, const G4String & particleName) inline
Definition at line 219 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 219 of file G4EnergyLossForExtrapolator.hh
References EnergyBeforeStep(), and FindParticle().
G4double G4EnergyLossForExtrapolator::EnergyDispersion (G4double kinEnergy, G4double step, const G4Material * mat, const G4ParticleDefinition * part) inline
Definition at line 282 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 282 of file G4EnergyLossForExtrapolator.hh
References beta2, charge2, ComputeTrueStep(), electronDensity, SetupKinematics(), Acts::Test::step(), tmax, and CLHEP::twopi_mc2_rcl2.
Referenced by EnergyDispersion().
G4double G4EnergyLossForExtrapolator::EnergyDispersion (G4double kinEnergy, G4double step, const G4Material * mat, const G4String & particleName) inline
Definition at line 241 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 241 of file G4EnergyLossForExtrapolator.hh
References EnergyDispersion(), and FindParticle().
const G4ParticleDefinition * G4EnergyLossForExtrapolator::FindParticle (const G4String & name) private
Definition at line 242 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 242 of file G4EnergyLossForExtrapolator.cc
References currentParticle, currentParticleName, G4ParticleTable::FindParticle(), G4cout, G4endl, and G4ParticleTable::GetParticleTable().
Referenced by AverageScatteringAngle(), EnergyAfterStep(), EnergyBeforeStep(), and EnergyDispersion().
const G4PhysicsTable * G4EnergyLossForExtrapolator::GetPhysicsTable (ExtTableType type) const inline private
Definition at line 200 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 200 of file G4EnergyLossForExtrapolator.hh
References G4TablesForExtrapolator::GetPhysicsTable(), and tables.
Referenced by ComputeDEDX(), ComputeEnergy(), ComputeRange(), and TrueStepLength().
void G4EnergyLossForExtrapolator::Initialisation () private
Definition at line 326 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 326 of file G4EnergyLossForExtrapolator.cc
References BuildTables(), currentMaterial, currentParticle, currentParticleName, G4Electron::Electron(), electron, G4cout, G4endl, kineticEnergy, G4MuonMinus::MuonMinus(), muonMinus, G4MuonPlus::MuonPlus(), muonPlus, G4Positron::Positron(), positron, G4Proton::Proton(), proton, and verbose.
Referenced by EnergyAfterStep(), EnergyBeforeStep(), SetupKinematics(), and TrueStepLength().
G4EnergyLossForExtrapolator& G4EnergyLossForExtrapolator::operator= (const G4EnergyLossForExtrapolator & right) private
void G4EnergyLossForExtrapolator::SetMaxEnergyTransfer (G4double val) inline
Definition at line 331 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 331 of file G4EnergyLossForExtrapolator.hh
References maxEnergyTransfer.
void G4EnergyLossForExtrapolator::SetMaxKinEnergy (G4double val) inline
Definition at line 324 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 324 of file G4EnergyLossForExtrapolator.hh
References emax.
void G4EnergyLossForExtrapolator::SetMinKinEnergy (G4double val) inline
Definition at line 317 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 317 of file G4EnergyLossForExtrapolator.hh
References emin.
G4bool G4EnergyLossForExtrapolator::SetupKinematics (const G4ParticleDefinition * part, const G4Material * mat, G4double kinEnergy) private
Definition at line 194 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 194 of file G4EnergyLossForExtrapolator.cc
References beta2, bg2, charge2, currentMaterial, currentParticle, electron, source.hepunit::electron_mass_c2, electronDensity, eplus, G4cout, G4endl, gam, G4Material::GetElectronDensity(), G4Material::GetIndex(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Material::GetRadlen(), index, Initialisation(), keV, kineticEnergy, mass, mat, maxEnergyTransfer, nmat, part, positron, r, radLength, and tmax.
Referenced by AverageScatteringAngle(), EnergyAfterStep(), EnergyBeforeStep(), EnergyDispersion(), and TrueStepLength().
void G4EnergyLossForExtrapolator::SetVerbose (G4int val) inline
Definition at line 310 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 310 of file G4EnergyLossForExtrapolator.hh
References verbose.
G4double G4EnergyLossForExtrapolator::TrueStepLength (G4double kinEnergy, G4double step, const G4Material * mat, const G4ParticleDefinition * part)
Definition at line 167 of file G4EnergyLossForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 167 of file G4EnergyLossForExtrapolator.cc
References ComputeRange(), ComputeTrueStep(), ComputeValue(), electron, fMscElectron, G4Log(), GetPhysicsTable(), idxMscElectron, Initialisation(), nmat, positron, SetupKinematics(), and x.
Referenced by EnergyAfterStep(), EnergyBeforeStep(), and G4EnergySplitter::SplitEnergyInVolumes().
Member Data Documentation
G4double G4EnergyLossForExtrapolator::beta2 private
Definition at line 184 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 184 of file G4EnergyLossForExtrapolator.hh
Referenced by AverageScatteringAngle(), EnergyDispersion(), G4EnergyLossForExtrapolator(), and SetupKinematics().
G4double G4EnergyLossForExtrapolator::bg2 private
Definition at line 183 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 183 of file G4EnergyLossForExtrapolator.hh
Referenced by G4EnergyLossForExtrapolator(), and SetupKinematics().
G4double G4EnergyLossForExtrapolator::charge2 private
Definition at line 180 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 180 of file G4EnergyLossForExtrapolator.hh
Referenced by AverageScatteringAngle(), ComputeDEDX(), ComputeEnergy(), ComputeRange(), EnergyDispersion(), G4EnergyLossForExtrapolator(), and SetupKinematics().
const G4Material* G4EnergyLossForExtrapolator::currentMaterial private
Definition at line 174 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 174 of file G4EnergyLossForExtrapolator.hh
Referenced by G4EnergyLossForExtrapolator(), Initialisation(), and SetupKinematics().
const G4ParticleDefinition* G4EnergyLossForExtrapolator::currentParticle private
Definition at line 151 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 151 of file G4EnergyLossForExtrapolator.hh
Referenced by FindParticle(), G4EnergyLossForExtrapolator(), Initialisation(), and SetupKinematics().
G4String G4EnergyLossForExtrapolator::currentParticleName private
Definition at line 158 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 158 of file G4EnergyLossForExtrapolator.hh
Referenced by FindParticle(), and Initialisation().
const G4ParticleDefinition* G4EnergyLossForExtrapolator::electron private
Definition at line 152 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 152 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), ComputeEnergy(), ComputeRange(), G4EnergyLossForExtrapolator(), Initialisation(), SetupKinematics(), and TrueStepLength().
G4double G4EnergyLossForExtrapolator::electronDensity private
Definition at line 177 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 177 of file G4EnergyLossForExtrapolator.hh
Referenced by EnergyDispersion(), G4EnergyLossForExtrapolator(), and SetupKinematics().
G4double G4EnergyLossForExtrapolator::emax private
Definition at line 189 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 189 of file G4EnergyLossForExtrapolator.hh
Referenced by BuildTables(), G4EnergyLossForExtrapolator(), and SetMaxKinEnergy().
G4double G4EnergyLossForExtrapolator::emin private
Definition at line 188 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 188 of file G4EnergyLossForExtrapolator.hh
Referenced by BuildTables(), G4EnergyLossForExtrapolator(), and SetMinKinEnergy().
G4double G4EnergyLossForExtrapolator::gam private
Definition at line 182 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 182 of file G4EnergyLossForExtrapolator.hh
Referenced by AverageScatteringAngle(), G4EnergyLossForExtrapolator(), and SetupKinematics().
size_t G4EnergyLossForExtrapolator::idxDedxElectron private
Definition at line 160 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 160 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxDedxMuon private
Definition at line 162 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 162 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxDedxPositron private
Definition at line 161 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 161 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxDedxProton private
Definition at line 163 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 163 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxInvRangeElectron private
Definition at line 168 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 168 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeEnergy(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxInvRangeMuon private
Definition at line 170 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 170 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeEnergy(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxInvRangePositron private
Definition at line 169 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 169 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeEnergy(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxInvRangeProton private
Definition at line 171 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 171 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeEnergy(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxMscElectron private
Definition at line 172 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 172 of file G4EnergyLossForExtrapolator.hh
Referenced by G4EnergyLossForExtrapolator(), and TrueStepLength().
size_t G4EnergyLossForExtrapolator::idxRangeElectron private
Definition at line 164 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 164 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeRange(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxRangeMuon private
Definition at line 166 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 166 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeRange(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxRangePositron private
Definition at line 165 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 165 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeRange(), and G4EnergyLossForExtrapolator().
size_t G4EnergyLossForExtrapolator::idxRangeProton private
Definition at line 167 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 167 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeRange(), and G4EnergyLossForExtrapolator().
G4int G4EnergyLossForExtrapolator::index private
Definition at line 175 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 175 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeValue(), G4EnergyLossForExtrapolator(), and SetupKinematics().
G4double G4EnergyLossForExtrapolator::kineticEnergy private
Definition at line 181 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 181 of file G4EnergyLossForExtrapolator.hh
Referenced by G4EnergyLossForExtrapolator(), Initialisation(), and SetupKinematics().
G4double G4EnergyLossForExtrapolator::linLossLimit private
Definition at line 187 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 187 of file G4EnergyLossForExtrapolator.hh
Referenced by EnergyAfterStep(), EnergyBeforeStep(), and G4EnergyLossForExtrapolator().
G4double G4EnergyLossForExtrapolator::mass private
Definition at line 179 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 179 of file G4EnergyLossForExtrapolator.hh
Referenced by AverageScatteringAngle(), ComputeDEDX(), ComputeEnergy(), ComputeRange(), G4EnergyLossForExtrapolator(), and SetupKinematics().
G4double G4EnergyLossForExtrapolator::maxEnergyTransfer private
Definition at line 190 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 190 of file G4EnergyLossForExtrapolator.hh
Referenced by SetMaxEnergyTransfer(), and SetupKinematics().
const G4ParticleDefinition* G4EnergyLossForExtrapolator::muonMinus private
Definition at line 155 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 155 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), ComputeEnergy(), ComputeRange(), G4EnergyLossForExtrapolator(), and Initialisation().
const G4ParticleDefinition* G4EnergyLossForExtrapolator::muonPlus private
Definition at line 154 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 154 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), ComputeEnergy(), ComputeRange(), G4EnergyLossForExtrapolator(), and Initialisation().
G4int G4EnergyLossForExtrapolator::nbins private
Definition at line 192 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 192 of file G4EnergyLossForExtrapolator.hh
Referenced by BuildTables(), and G4EnergyLossForExtrapolator().
G4int G4EnergyLossForExtrapolator::nmat private
Definition at line 193 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 193 of file G4EnergyLossForExtrapolator.hh
Referenced by BuildTables(), EnergyAfterStep(), EnergyBeforeStep(), G4EnergyLossForExtrapolator(), SetupKinematics(), and TrueStepLength().
const G4ParticleDefinition* G4EnergyLossForExtrapolator::positron private
Definition at line 153 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 153 of file G4EnergyLossForExtrapolator.hh
Referenced by ComputeDEDX(), ComputeEnergy(), ComputeRange(), G4EnergyLossForExtrapolator(), Initialisation(), SetupKinematics(), and TrueStepLength().
const G4ParticleDefinition* G4EnergyLossForExtrapolator::proton private
Definition at line 156 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 156 of file G4EnergyLossForExtrapolator.hh
Referenced by G4EnergyLossForExtrapolator(), and Initialisation().
G4double G4EnergyLossForExtrapolator::radLength private
Definition at line 178 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 178 of file G4EnergyLossForExtrapolator.hh
Referenced by AverageScatteringAngle(), G4EnergyLossForExtrapolator(), and SetupKinematics().
G4TablesForExtrapolator * G4EnergyLossForExtrapolator::tables = nullptr static private
Definition at line 149 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 149 of file G4EnergyLossForExtrapolator.hh
Referenced by BuildTables(), GetPhysicsTable(), and ~G4EnergyLossForExtrapolator().
G4double G4EnergyLossForExtrapolator::tmax private
Definition at line 185 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 185 of file G4EnergyLossForExtrapolator.hh
Referenced by EnergyDispersion(), G4EnergyLossForExtrapolator(), and SetupKinematics().
G4int G4EnergyLossForExtrapolator::verbose private
Definition at line 194 of file G4EnergyLossForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 194 of file G4EnergyLossForExtrapolator.hh
Referenced by BuildTables(), Initialisation(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4EnergyLossForExtrapolator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/src/G4EnergyLossForExtrapolator.cc