ECCE @ EIC Software: G4IonisParamMat Class Reference
G4IonisParamMat Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4IonisParamMat.hh>
Public Member Functions
G4IonisParamMat (const G4Material *)
~G4IonisParamMat ()
G4double GetMeanExcitationEnergy () const
void SetMeanExcitationEnergy (G4double value)
G4double FindMeanExcitationEnergy (const G4Material *) const
G4double GetLogMeanExcEnergy () const
G4double * GetShellCorrectionVector () const
G4double GetTaul () const
G4double GetPlasmaEnergy () const
G4double GetAdjustmentFactor () const
G4double GetCdensity () const
G4double GetMdensity () const
G4double GetAdensity () const
G4double GetX0density () const
G4double GetX1density () const
G4double GetD0density () const
void SetDensityEffectParameters (G4double cd, G4double md, G4double ad, G4double x0, G4double x1, G4double d0)
void SetDensityEffectParameters (const G4Material *bmat)
void ComputeDensityEffectOnFly (G4bool)
G4double DensityCorrection (G4double x)
G4DensityEffectCalculator * GetDensityEffectCalculator ()
G4double GetDensityCorrection (G4double x)
G4double GetF1fluct () const
G4double GetF2fluct () const
G4double GetEnergy1fluct () const
G4double GetLogEnergy1fluct () const
G4double GetEnergy2fluct () const
G4double GetLogEnergy2fluct () const
G4double GetEnergy0fluct () const
G4double GetRateionexcfluct () const
G4double GetZeffective () const
G4double GetFermiEnergy () const
G4double GetLFactor () const
G4double GetInvA23 () const
void SetBirksConstant (G4double value)
G4double GetBirksConstant () const
void SetMeanEnergyPerIonPair (G4double value)
G4double GetMeanEnergyPerIonPair () const
G4IonisParamMat (__void__ &)
Static Public Member Functions
static G4DensityEffectData * GetDensityEffectData ()
Private Member Functions
void ComputeMeanParameters ()
void ComputeDensityEffectParameters ()
void ComputeFluctModel ()
void ComputeIonParameters ()
G4IonisParamMat & operator= (const G4IonisParamMat &)
G4bool operator== (const G4IonisParamMat &) const
G4bool operator!= (const G4IonisParamMat &) const
G4IonisParamMat (const G4IonisParamMat &)
Private Attributes
const G4Material * fMaterial
G4DensityEffectCalculator * fDensityEffectCalc
G4double * fShellCorrectionVector
G4double fMeanExcitationEnergy
G4double fLogMeanExcEnergy
G4double fTaul
G4double fCdensity
G4double fMdensity
G4double fAdensity
G4double fX0density
G4double fX1density
G4double fD0density
G4double fPlasmaEnergy
G4double fAdjustmentFactor
G4double fF1fluct
G4double fF2fluct
G4double fEnergy1fluct
G4double fLogEnergy1fluct
G4double fEnergy2fluct
G4double fLogEnergy2fluct
G4double fEnergy0fluct
G4double fRateionexcfluct
G4double fZeff
G4double fFermiEnergy
G4double fLfactor
G4double fInvA23
G4double fBirks
G4double fMeanEnergyPerIon
G4double twoln10
Static Private Attributes
static G4DensityEffectData * fDensityData = nullptr
Detailed Description
Definition at line 60 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 60 of file G4IonisParamMat.hh
Constructor & Destructor Documentation
G4IonisParamMat::G4IonisParamMat (const G4Material * material)
Definition at line 59 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 59 of file G4IonisParamMat.cc
References ComputeDensityEffectParameters(), ComputeFluctModel(), ComputeIonParameters(), ComputeMeanParameters(), fAdjustmentFactor, fBirks, fCdensity, fD0density, fDensityData, fDensityEffectCalc, fMeanEnergyPerIon, G4Pow::GetInstance(), G4Pow::logZ(), and twoln10.
G4IonisParamMat::~G4IonisParamMat ()
Definition at line 121 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 121 of file G4IonisParamMat.cc
References fDensityData, fDensityEffectCalc, and fShellCorrectionVector.
G4IonisParamMat::G4IonisParamMat (__void__ &)
Definition at line 85 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 85 of file G4IonisParamMat.cc
References fAdensity, fAdjustmentFactor, fBirks, fCdensity, fD0density, fDensityData, fDensityEffectCalc, fEnergy0fluct, fEnergy1fluct, fEnergy2fluct, fF1fluct, fF2fluct, fFermiEnergy, fInvA23, fLfactor, fLogEnergy1fluct, fLogEnergy2fluct, fLogMeanExcEnergy, fMdensity, fMeanEnergyPerIon, fMeanExcitationEnergy, fPlasmaEnergy, fRateionexcfluct, fTaul, fX0density, fX1density, fZeff, G4Pow::GetInstance(), G4Pow::logZ(), and twoln10.
G4IonisParamMat::G4IonisParamMat (const G4IonisParamMat &) private
Member Function Documentation
void G4IonisParamMat::ComputeDensityEffectOnFly (G4bool val)
Definition at line 525 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 525 of file G4IonisParamMat.cc
References fDensityEffectCalc, fMaterial, G4Material::GetElement(), G4Material::GetNumberOfElements(), G4AtomicShells::GetNumberOfShells(), G4Element::GetZasInt(), n, and Z.
Referenced by G4Material::ComputeDensityEffectOnFly().
void G4IonisParamMat::ComputeDensityEffectParameters () private
Definition at line 193 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 193 of file G4IonisParamMat.cc
References kdfinder::abs(), source.hepunit::classic_electr_radius, eV, fAdensity, fAdjustmentFactor, fCdensity, fD0density, fDensityData, fMaterial, fMdensity, fMeanExcitationEnergy, fPlasmaEnergy, fX0density, fX1density, G4Log(), G4DensityEffectData::GetAdensity(), G4DensityEffectData::GetAdjustmentFactor(), G4Material::GetBaseMaterial(), G4DensityEffectData::GetCdensity(), G4DensityEffectData::GetDelta0density(), G4Material::GetDensity(), G4DensityEffectData::GetElementIndex(), G4Material::GetElementVector(), G4DensityEffectData::GetIndex(), G4DensityEffectData::GetMdensity(), G4Material::GetName(), G4NistManager::GetNominalDensity(), G4Material::GetNumberOfElements(), G4DensityEffectData::GetPlasmaEnergy(), G4Material::GetPressure(), G4Material::GetState(), G4Material::GetTemperature(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetTotNbOfElectPerVolume(), G4Material::GetVecNbOfAtomsPerVolume(), G4DensityEffectData::GetX0density(), G4DensityEffectData::GetX1density(), source.hepunit::hbarc_squared, incremental_prev_tag::idx, G4NistManager::Instance(), kStateGas, kStateLiquid, kStateSolid, NTP_Temperature, pi, State, source.hepunit::STP_Pressure, and twoln10.
Referenced by G4IonisParamMat().
void G4IonisParamMat::ComputeFluctModel () private
Definition at line 386 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 386 of file G4IonisParamMat.cc
References eV, fEnergy0fluct, fEnergy1fluct, fEnergy2fluct, fF1fluct, fF2fluct, fLogEnergy1fluct, fLogEnergy2fluct, fLogMeanExcEnergy, fMaterial, fRateionexcfluct, G4Exp(), G4Log(), G4Material::GetElementVector(), G4Material::GetFractionVector(), and G4Material::GetNumberOfElements().
Referenced by G4IonisParamMat(), and SetMeanExcitationEnergy().
void G4IonisParamMat::ComputeIonParameters () private
Definition at line 409 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 409 of file G4IonisParamMat.cc
References G4Pow::A23(), fFermiEnergy, fInvA23, fLfactor, fMaterial, fZeff, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4IonisParamElm::GetFermiVelocity(), G4Pow::GetInstance(), G4Element::GetIonisation(), G4IonisParamElm::GetLFactor(), G4Element::GetN(), G4Material::GetNumberOfElements(), G4Element::GetZ(), keV, norm, weight, and z.
Referenced by G4IonisParamMat().
void G4IonisParamMat::ComputeMeanParameters () private
Definition at line 133 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 133 of file G4IonisParamMat.cc
References FindMeanExcitationEnergy(), fLogMeanExcEnergy, fMaterial, fMeanExcitationEnergy, fShellCorrectionVector, fTaul, G4Exp(), G4Log(), G4Material::GetElementVector(), G4Element::GetIonisation(), G4IonisParamElm::GetMeanExcitationEnergy(), G4Material::GetNumberOfElements(), G4Material::GetTotNbOfElectPerVolume(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZ(), and k.
Referenced by G4IonisParamMat().
G4double G4IonisParamMat::DensityCorrection (G4double x)
Definition at line 185 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 185 of file G4IonisParamMat.cc
References G4DensityEffectCalculator::ComputeDensityCorrection(), fDensityEffectCalc, and GetDensityCorrection().
Referenced by G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), and G4MuBetheBlochModel::ComputeDEDXPerVolume().
G4double G4IonisParamMat::FindMeanExcitationEnergy (const G4Material * mat) const
Definition at line 546 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 546 of file G4IonisParamMat.cc
References eV, fDensityData, G4Material::GetChemicalFormula(), G4DensityEffectData::GetIndex(), G4DensityEffectData::GetMeanIonisationPotential(), G4Material::GetName(), incremental_prev_tag::idx, and numberOfMolecula.
Referenced by G4NistMaterialBuilder::BuildMaterial(), and ComputeMeanParameters().
G4double G4IonisParamMat::GetAdensity () const inline
Definition at line 91 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 91 of file G4IonisParamMat.hh
References fAdensity.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
G4double G4IonisParamMat::GetAdjustmentFactor () const inline
Definition at line 85 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 85 of file G4IonisParamMat.hh
References fAdjustmentFactor.
G4double G4IonisParamMat::GetBirksConstant () const inline
Definition at line 152 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 152 of file G4IonisParamMat.hh
References fBirks.
Referenced by SteppingAction::BirksAttenuation(), G4EmSaturation::DumpBirksCoefficients(), G4EmSaturation::InitialiseBirksCoefficient(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and G4EmSaturation::VisibleEnergyDeposition().
G4double G4IonisParamMat::GetCdensity () const inline
Definition at line 87 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 87 of file G4IonisParamMat.hh
References fCdensity.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
G4double G4IonisParamMat::GetD0density () const inline
Definition at line 97 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 97 of file G4IonisParamMat.hh
References fD0density.
Referenced by SetDensityEffectParameters().
G4double G4IonisParamMat::GetDensityCorrection (G4double x) inline
Definition at line 240 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 240 of file G4IonisParamMat.hh
References fAdensity, fCdensity, fD0density, fMdensity, fX0density, fX1density, G4Exp(), G4Log(), twoln10, and y.
Referenced by G4DensityEffectCalculator::ComputeDensityCorrection(), and DensityCorrection().
G4DensityEffectCalculator* G4IonisParamMat::GetDensityEffectCalculator () inline
Definition at line 112 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 112 of file G4IonisParamMat.hh
References fDensityEffectCalc.
Referenced by G4Material::CopyPointersOfBaseMaterial().
G4DensityEffectData * G4IonisParamMat::GetDensityEffectData () static
Definition at line 178 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 178 of file G4IonisParamMat.cc
References fDensityData.
Referenced by G4NistMessenger::SetNewValue().
G4double G4IonisParamMat::GetEnergy0fluct () const inline
Definition at line 134 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 134 of file G4IonisParamMat.hh
References fEnergy0fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetEnergy1fluct () const inline
Definition at line 126 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 126 of file G4IonisParamMat.hh
References fEnergy1fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetEnergy2fluct () const inline
Definition at line 130 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 130 of file G4IonisParamMat.hh
References fEnergy2fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetF1fluct () const inline
Definition at line 122 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 122 of file G4IonisParamMat.hh
References fF1fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetF2fluct () const inline
Definition at line 124 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 124 of file G4IonisParamMat.hh
References fF2fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetFermiEnergy () const inline
Definition at line 142 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 142 of file G4IonisParamMat.hh
References fFermiEnergy.
Referenced by G4ionEffectiveCharge::EffectiveCharge(), and G4IonFluctuations::RelativisticFactor().
G4double G4IonisParamMat::GetInvA23 () const inline
Definition at line 146 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 146 of file G4IonisParamMat.hh
References fInvA23.
Referenced by G4CoulombScattering::MinPrimaryEnergy(), G4WentzelVIRelXSection::SetupKinematic(), and G4WentzelOKandVIxSection::SetupKinematic().
G4double G4IonisParamMat::GetLFactor () const inline
Definition at line 144 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 144 of file G4IonisParamMat.hh
References fLfactor.
G4double G4IonisParamMat::GetLogEnergy1fluct () const inline
Definition at line 128 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 128 of file G4IonisParamMat.hh
References fLogEnergy1fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetLogEnergy2fluct () const inline
Definition at line 132 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 132 of file G4IonisParamMat.hh
References fLogEnergy2fluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetLogMeanExcEnergy () const inline
Definition at line 75 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 75 of file G4IonisParamMat.hh
References fLogMeanExcEnergy.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), G4RDVeLowEnergyLoss::GetLossWithFluct(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetMdensity () const inline
Definition at line 89 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 89 of file G4IonisParamMat.hh
References fMdensity.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
G4double G4IonisParamMat::GetMeanEnergyPerIonPair () const inline
Definition at line 158 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 158 of file G4IonisParamMat.hh
References fMeanEnergyPerIon.
Referenced by G4ElectronIonPair::DumpMeanEnergyPerIonPair(), and G4ElectronIonPair::MeanNumberOfIonsAlongStep().
G4double G4IonisParamMat::GetMeanExcitationEnergy () const inline
Definition at line 69 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 69 of file G4IonisParamMat.hh
References fMeanExcitationEnergy.
Referenced by G4EmCorrections::Bethe(), G4hBetheBlochModel::BetheBlochFormula(), G4NistMaterialBuilder::BuildMaterial(), G4hImpactIonisation::BuildPhysicsTable(), G4mplIonisationModel::ComputeDEDXAhlen(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), MyMollerBhabhaModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), G4Material::CopyPointersOfBaseMaterial(), G4tgbGeometryDumper::DumpMaterial(), G4hImpactIonisation::ElectronicLossFluctuation(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4AtimaEnergyLossModel::MinEnergyCut(), G4LindhardSorensenIonModel::MinEnergyCut(), G4BetheBlochModel::MinEnergyCut(), G4MuBetheBlochModel::MinEnergyCut(), G4BraggIonModel::MinEnergyCut(), G4IonParametrisedLossModel::MinEnergyCut(), G4mplIonisationWithDeltaModel::MinEnergyCut(), operator<<(), G4hImpactIonisation::PrintInfoDefinition(), G4IonFluctuations::RelativisticFactor(), and G4UniversalFluctuation::SampleFluctuations().
G4double G4IonisParamMat::GetPlasmaEnergy () const inline
Definition at line 83 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 83 of file G4IonisParamMat.hh
References fPlasmaEnergy.
Referenced by G4DensityEffectCalculator::G4DensityEffectCalculator().
G4double G4IonisParamMat::GetRateionexcfluct () const inline
Definition at line 136 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 136 of file G4IonisParamMat.hh
References fRateionexcfluct.
Referenced by G4hImpactIonisation::ElectronicLossFluctuation(), and G4RDVeLowEnergyLoss::GetLossWithFluct().
G4double* G4IonisParamMat::GetShellCorrectionVector () const inline
Definition at line 77 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 77 of file G4IonisParamMat.hh
References fShellCorrectionVector.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), and G4EmCorrections::ShellCorrectionSTD().
G4double G4IonisParamMat::GetTaul () const inline
Definition at line 79 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 79 of file G4IonisParamMat.hh
References fTaul.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4hBetheBlochModel::LowEnergyLimit(), and G4EmCorrections::ShellCorrectionSTD().
G4double G4IonisParamMat::GetX0density () const inline
Definition at line 93 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 93 of file G4IonisParamMat.hh
References fX0density.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
G4double G4IonisParamMat::GetX1density () const inline
Definition at line 95 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 95 of file G4IonisParamMat.hh
References fX1density.
Referenced by G4hBetheBlochModel::BetheBlochFormula(), G4mplIonisationModel::ComputeDEDXAhlen(), G4EmCorrections::DensityCorrection(), and SetDensityEffectParameters().
G4double G4IonisParamMat::GetZeffective () const inline
Definition at line 140 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 140 of file G4IonisParamMat.hh
References fZeff.
Referenced by G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4AtimaFluctuations::Dispersion(), G4IonFluctuations::Dispersion(), G4ionEffectiveCharge::EffectiveCharge(), and G4GoudsmitSaundersonTable::InitSCPCorrection().
G4bool G4IonisParamMat::operator!= (const G4IonisParamMat &) const private
G4IonisParamMat& G4IonisParamMat::operator= (const G4IonisParamMat &) private
G4bool G4IonisParamMat::operator== (const G4IonisParamMat &) const private
void G4IonisParamMat::SetBirksConstant (G4double value) inline
Definition at line 150 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 150 of file G4IonisParamMat.hh
References fBirks.
Referenced by OpNoviceDetectorConstruction::Construct(), WLSMaterials::CreateMaterials(), LXeDetectorConstruction::DefineMaterials(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), G4EmSaturation::InitialiseBirksCoefficient(), and DetectorConstruction::SetTankMaterial().
void G4IonisParamMat::SetDensityEffectParameters (G4double cd, G4double md, G4double ad, G4double x0, G4double x1, G4double d0)
Definition at line 480 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 480 of file G4IonisParamMat.cc
References cd, fAdensity, fCdensity, fD0density, fMdensity, fX0density, fX1density, G4MUTEXLOCK, G4MUTEXUNLOCK, and x1.
void G4IonisParamMat::SetDensityEffectParameters (const G4Material * bmat)
Definition at line 501 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 501 of file G4IonisParamMat.cc
References fAdensity, fCdensity, fD0density, fMaterial, fMdensity, fX0density, fX1density, G4Log(), G4MUTEXLOCK, G4MUTEXUNLOCK, GetAdensity(), GetCdensity(), GetD0density(), G4Material::GetDensity(), G4Material::GetIonisation(), GetMdensity(), GetX0density(), GetX1density(), and twoln10.
void G4IonisParamMat::SetMeanEnergyPerIonPair (G4double value) inline
Definition at line 156 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 156 of file G4IonisParamMat.hh
References fMeanEnergyPerIon.
Referenced by G4ElectronIonPair::FindG4MeanEnergyPerIonPair(), and DetectorConstruction::SetPairEnergy().
void G4IonisParamMat::SetMeanExcitationEnergy (G4double value)
Definition at line 453 of file G4IonisParamMat.cc.
View newest version in sPHENIX GitHub at line 453 of file G4IonisParamMat.cc
References ComputeFluctModel(), eV, fCdensity, fLogMeanExcEnergy, fMaterial, fMeanExcitationEnergy, fX0density, fX1density, G4cout, G4endl, G4Log(), G4Material::GetName(), G4NistManager::Instance(), and twoln10.
Referenced by G4NistMaterialBuilder::BuildMaterial(), G4Material::CopyPointersOfBaseMaterial(), G4HumanPhantomMaterial::DefineMaterials(), BrachyMaterial::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), DetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), G4tgbMaterialMgr::FindOrBuildG4Material(), and G4GDMLReadMaterials::MaterialRead().
Member Data Documentation
G4double G4IonisParamMat::fAdensity private
Definition at line 201 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 201 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetAdensity(), GetDensityCorrection(), and SetDensityEffectParameters().
G4double G4IonisParamMat::fAdjustmentFactor private
Definition at line 207 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 207 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), and GetAdjustmentFactor().
G4double G4IonisParamMat::fBirks private
Definition at line 226 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 226 of file G4IonisParamMat.hh
Referenced by G4IonisParamMat(), GetBirksConstant(), and SetBirksConstant().
G4double G4IonisParamMat::fCdensity private
Definition at line 199 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 199 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetCdensity(), GetDensityCorrection(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
G4double G4IonisParamMat::fD0density private
Definition at line 204 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 204 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetD0density(), GetDensityCorrection(), and SetDensityEffectParameters().
G4DensityEffectData * G4IonisParamMat::fDensityData = nullptr static private
Definition at line 231 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 231 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), FindMeanExcitationEnergy(), G4IonisParamMat(), GetDensityEffectData(), and ~G4IonisParamMat().
G4DensityEffectCalculator* G4IonisParamMat::fDensityEffectCalc private
Definition at line 190 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 190 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectOnFly(), DensityCorrection(), G4IonisParamMat(), GetDensityEffectCalculator(), and ~G4IonisParamMat().
G4double G4IonisParamMat::fEnergy0fluct private
Definition at line 216 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 216 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetEnergy0fluct().
G4double G4IonisParamMat::fEnergy1fluct private
Definition at line 212 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 212 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetEnergy1fluct().
G4double G4IonisParamMat::fEnergy2fluct private
Definition at line 214 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 214 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetEnergy2fluct().
G4double G4IonisParamMat::fF1fluct private
Definition at line 210 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 210 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetF1fluct().
G4double G4IonisParamMat::fF2fluct private
Definition at line 211 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 211 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetF2fluct().
G4double G4IonisParamMat::fFermiEnergy private
Definition at line 221 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 221 of file G4IonisParamMat.hh
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetFermiEnergy().
G4double G4IonisParamMat::fInvA23 private
Definition at line 223 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 223 of file G4IonisParamMat.hh
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetInvA23().
G4double G4IonisParamMat::fLfactor private
Definition at line 222 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 222 of file G4IonisParamMat.hh
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetLFactor().
G4double G4IonisParamMat::fLogEnergy1fluct private
Definition at line 213 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 213 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetLogEnergy1fluct().
G4double G4IonisParamMat::fLogEnergy2fluct private
Definition at line 215 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 215 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetLogEnergy2fluct().
G4double G4IonisParamMat::fLogMeanExcEnergy private
Definition at line 195 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 195 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), ComputeMeanParameters(), G4IonisParamMat(), GetLogMeanExcEnergy(), and SetMeanExcitationEnergy().
const G4Material* G4IonisParamMat::fMaterial private
Definition at line 188 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 188 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectOnFly(), ComputeDensityEffectParameters(), ComputeFluctModel(), ComputeIonParameters(), ComputeMeanParameters(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
G4double G4IonisParamMat::fMdensity private
Definition at line 200 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 200 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetDensityCorrection(), GetMdensity(), and SetDensityEffectParameters().
G4double G4IonisParamMat::fMeanEnergyPerIon private
Definition at line 228 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 228 of file G4IonisParamMat.hh
Referenced by G4IonisParamMat(), GetMeanEnergyPerIonPair(), and SetMeanEnergyPerIonPair().
G4double G4IonisParamMat::fMeanExcitationEnergy private
Definition at line 194 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 194 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), ComputeMeanParameters(), G4IonisParamMat(), GetMeanExcitationEnergy(), and SetMeanExcitationEnergy().
G4double G4IonisParamMat::fPlasmaEnergy private
Definition at line 206 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 206 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), and GetPlasmaEnergy().
G4double G4IonisParamMat::fRateionexcfluct private
Definition at line 217 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 217 of file G4IonisParamMat.hh
Referenced by ComputeFluctModel(), G4IonisParamMat(), and GetRateionexcfluct().
G4double* G4IonisParamMat::fShellCorrectionVector private
Definition at line 191 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 191 of file G4IonisParamMat.hh
Referenced by ComputeMeanParameters(), GetShellCorrectionVector(), and ~G4IonisParamMat().
G4double G4IonisParamMat::fTaul private
Definition at line 196 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 196 of file G4IonisParamMat.hh
Referenced by ComputeMeanParameters(), G4IonisParamMat(), and GetTaul().
G4double G4IonisParamMat::fX0density private
Definition at line 202 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 202 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetDensityCorrection(), GetX0density(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
G4double G4IonisParamMat::fX1density private
Definition at line 203 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 203 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetDensityCorrection(), GetX1density(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
G4double G4IonisParamMat::fZeff private
Definition at line 220 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 220 of file G4IonisParamMat.hh
Referenced by ComputeIonParameters(), G4IonisParamMat(), and GetZeffective().
G4double G4IonisParamMat::twoln10 private
Definition at line 232 of file G4IonisParamMat.hh.
View newest version in sPHENIX GitHub at line 232 of file G4IonisParamMat.hh
Referenced by ComputeDensityEffectParameters(), G4IonisParamMat(), GetDensityCorrection(), SetDensityEffectParameters(), and SetMeanExcitationEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4IonisParamMat.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4IonisParamMat.cc