ECCE @ EIC Software: G4DNABornIonisationModel1 Class Reference
G4DNABornIonisationModel1 Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNABornIonisationModel1.hh>
Public Member Functions
G4DNABornIonisationModel1 (const G4ParticleDefinition *p=0, const G4String &nam="DNABornIonisationModel")
virtual ~G4DNABornIonisationModel1 ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &=*(new G4DataVector()))
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
virtual G4double GetPartialCrossSection (const G4Material *, G4int, const G4ParticleDefinition *, G4double)
G4double DifferentialCrossSection (G4ParticleDefinition *aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
G4double TransferedEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell, G4double random)
void SelectFasterComputation (G4bool input)
void SelectStationary (G4bool input)
void SelectSPScaling (G4bool input)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Types
typedef std::map< G4String,
G4String, std::less< G4String > > MapFile
typedef std::map< G4String,
G4DNACrossSectionDataSet
*, std::less< G4String > > MapData
typedef std::map< G4double,
std::map< G4double, G4double > > TriDimensionMap
typedef std::map< G4double,
std::vector< G4double > > VecMap
Private Member Functions
G4double RandomizeEjectedElectronEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
G4int RandomSelect (G4double energy, const G4String &particle)
G4DNABornIonisationModel1 & operator= (const G4DNABornIonisationModel1 &right)
G4DNABornIonisationModel1 (const G4DNABornIonisationModel1 &)
Private Attributes
G4bool fasterCode
G4bool statCode
G4bool spScaling
const std::vector< G4double > * fpMolWaterDensity
G4VAtomDeexcitation * fAtomDeexcitation
std::map< G4String, G4double,
std::less< G4String > > lowEnergyLimit
std::map< G4String, G4double,
std::less< G4String > > highEnergyLimit
G4bool isInitialised
G4int verboseLevel
MapFile tableFile
MapData tableData
G4DNAWaterIonisationStructure waterStructure
TriDimensionMap eDiffCrossSectionData [6]
TriDimensionMap eNrjTransfData [6]
TriDimensionMap pDiffCrossSectionData [6]
TriDimensionMap pNrjTransfData [6]
std::vector< G4double > eTdummyVec
std::vector< G4double > pTdummyVec
VecMap eVecm
VecMap pVecm
VecMap eProbaShellMap [6]
VecMap pProbaShellMap [6]
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 47 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 47 of file G4DNABornIonisationModel1.hh
Member Typedef Documentation
typedef std::map<G4String,G4DNACrossSectionDataSet*,std::less<G4String> > G4DNABornIonisationModel1::MapData private
Definition at line 118 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 118 of file G4DNABornIonisationModel1.hh
typedef std::map<G4String,G4String,std::less<G4String> > G4DNABornIonisationModel1::MapFile private
Definition at line 115 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 115 of file G4DNABornIonisationModel1.hh
typedef std::map<G4double, std::map<G4double, G4double> > G4DNABornIonisationModel1::TriDimensionMap private
Definition at line 144 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 144 of file G4DNABornIonisationModel1.hh
typedef std::map<G4double, std::vector<G4double> > G4DNABornIonisationModel1::VecMap private
Definition at line 155 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 155 of file G4DNABornIonisationModel1.hh
Constructor & Destructor Documentation
G4DNABornIonisationModel1::G4DNABornIonisationModel1 (const G4ParticleDefinition * p = 0, const G4String & nam = "DNABornIonisationModel")
Definition at line 45 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DNABornIonisationModel1.cc
References fasterCode, fAtomDeexcitation, fParticleChangeForGamma, fpMolWaterDensity, G4cout, G4endl, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), spScaling, statCode, and verboseLevel.
G4DNABornIonisationModel1::~G4DNABornIonisationModel1 () virtual
Definition at line 86 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 86 of file G4DNABornIonisationModel1.cc
References eVecm, pos(), pVecm, and tableData.
G4DNABornIonisationModel1::G4DNABornIonisationModel1 (const G4DNABornIonisationModel1 &) private
Member Function Documentation
G4double G4DNABornIonisationModel1::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 317 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 317 of file G4DNABornIonisationModel1.cc
References A(), B(), cm, G4Electron::ElectronDefinition(), eV, FatalException, G4DNACrossSectionDataSet::FindValue(), G4cout, G4endl, G4Exception(), G4Exp(), G4Material::GetIndex(), G4ParticleDefinition::GetParticleName(), highEnergyLimit, lowEnergyLimit, MeV, pos(), G4Proton::ProtonDefinition(), spScaling, tableData, and verboseLevel.
G4double G4DNABornIonisationModel1::DifferentialCrossSection (G4ParticleDefinition * aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
Definition at line 744 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 744 of file G4DNABornIonisationModel1.cc
References e, eDiffCrossSectionData, G4Electron::ElectronDefinition(), eTdummyVec, eV, eVecm, G4DNAWaterIonisationStructure::IonisationEnergy(), k, pDiffCrossSectionData, G4Proton::ProtonDefinition(), pTdummyVec, pVecm, QuadInterpolator(), t1, t2, and waterStructure.
Referenced by RandomizeEjectedElectronEnergy().
G4double G4DNABornIonisationModel1::GetPartialCrossSection (const G4Material * , G4int level, const G4ParticleDefinition * particle, G4double kineticEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 959 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 959 of file G4DNABornIonisationModel1.cc
References G4VEMDataSet::FindValue(), G4DNACrossSectionDataSet::GetComponent(), G4ParticleDefinition::GetParticleName(), pos(), and tableData.
void G4DNABornIonisationModel1::Initialise (const G4ParticleDefinition * particle, const G4DataVector & = *(new G4DataVector())) virtual
Implements G4VEmModel.
Definition at line 105 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 105 of file G4DNABornIonisationModel1.cc
References G4LossTableManager::AtomDeexcitation(), eDiffCrossSectionData, G4InuclParticleNames::electron, G4Electron::ElectronDefinition(), eNrjTransfData, eProbaShellMap, eTdummyVec, eV, eVecm, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, fpMolWaterDensity, G4cout, G4endl, G4Exception(), G4Material::GetMaterial(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), highEnergyLimit, G4VEmModel::HighEnergyLimit(), G4LossTableManager::Instance(), G4DNAMolecularMaterial::Instance(), isInitialised, keV, G4DNACrossSectionDataSet::LoadData(), lowEnergyLimit, G4VEmModel::LowEnergyLimit(), m, MeV, pDiffCrossSectionData, pNrjTransfData, pProbaShellMap, G4InuclParticleNames::proton, G4Proton::ProtonDefinition(), pTdummyVec, pVecm, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), tableData, tableFile, tmp, and verboseLevel.
G4double G4DNABornIonisationModel1::Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 871 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 871 of file G4DNABornIonisationModel1.cc
References a, b, d1, d2, e1, and fasterCode.
Referenced by QuadInterpolator(), and TransferedEnergy().
G4DNABornIonisationModel1& G4DNABornIonisationModel1::operator= (const G4DNABornIonisationModel1 & right) private
G4double G4DNABornIonisationModel1::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 935 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 935 of file G4DNABornIonisationModel1.cc
References Interpolate().
Referenced by DifferentialCrossSection(), and TransferedEnergy().
G4double G4DNABornIonisationModel1::RandomizeEjectedElectronEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 606 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 606 of file G4DNABornIonisationModel1.cc
References DifferentialCrossSection(), source.hepunit::electron_mass_c2, G4Electron::ElectronDefinition(), eV, G4UniformRand, G4DNAWaterIonisationStructure::IonisationEnergy(), k, source.hepunit::proton_mass_c2, G4Proton::ProtonDefinition(), Acts::Test::step(), and waterStructure.
Referenced by SampleSecondaries().
G4double G4DNABornIonisationModel1::RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 1037 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 1037 of file G4DNABornIonisationModel1.cc
References eV, G4UniformRand, G4DNAWaterIonisationStructure::IonisationEnergy(), TransferedEnergy(), and waterStructure.
Referenced by SampleSecondaries().
G4int G4DNABornIonisationModel1::RandomSelect (G4double energy, const G4String & particle) private
Definition at line 978 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 978 of file G4DNABornIonisationModel1.cc
References FatalException, G4VEMDataSet::FindValue(), G4Exception(), G4UniformRand, G4DNACrossSectionDataSet::GetComponent(), n, G4DNACrossSectionDataSet::NumberOfComponents(), pos(), and tableData.
Referenced by SampleSecondaries().
void G4DNABornIonisationModel1::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * particle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 407 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 407 of file G4DNABornIonisationModel1.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4DNAChemistryManager::CreateWaterMolecule(), eIonizedMolecule, G4Electron::Electron(), source.hepunit::electron_mass_c2, G4Electron::ElectronDefinition(), eV, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, G4cout, G4endl, G4Exception(), G4VAtomDeexcitation::GenerateParticles(), G4VEmModel::GetAngularDistribution(), G4VAtomDeexcitation::GetAtomicShell(), G4ParticleChangeForGamma::GetCurrentTrack(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), highEnergyLimit, G4DNAChemistryManager::Instance(), G4DNAWaterIonisationStructure::IonisationEnergy(), k, lowEnergyLimit, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), RandomSelect(), G4VEmAngularDistribution::SampleDirectionForShell(), CLHEP::Hep3Vector::set(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), statCode, CLHEP::Hep3Vector::unit(), verboseLevel, waterStructure, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4DNABornIonisationModel1::SelectFasterComputation (G4bool input) inline
Definition at line 174 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 174 of file G4DNABornIonisationModel1.hh
References fasterCode.
void G4DNABornIonisationModel1::SelectSPScaling (G4bool input) inline
Definition at line 188 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 188 of file G4DNABornIonisationModel1.hh
References spScaling.
void G4DNABornIonisationModel1::SelectStationary (G4bool input) inline
Definition at line 181 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 181 of file G4DNABornIonisationModel1.hh
References statCode.
G4double G4DNABornIonisationModel1::TransferedEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell, G4double random)
Definition at line 1064 of file G4DNABornIonisationModel1.cc.
View newest version in sPHENIX GitHub at line 1064 of file G4DNABornIonisationModel1.cc
References e, G4Electron::ElectronDefinition(), eNrjTransfData, eProbaShellMap, eTdummyVec, Interpolate(), k, k1, k2, pNrjTransfData, pProbaShellMap, G4Proton::ProtonDefinition(), pTdummyVec, and QuadInterpolator().
Referenced by RandomizeEjectedElectronEnergyFromCumulatedDcs().
Member Data Documentation
TriDimensionMap G4DNABornIonisationModel1::eDiffCrossSectionData[6] private
Definition at line 146 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 146 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), and Initialise().
TriDimensionMap G4DNABornIonisationModel1::eNrjTransfData[6] private
Definition at line 147 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 147 of file G4DNABornIonisationModel1.hh
Referenced by Initialise(), and TransferedEnergy().
VecMap G4DNABornIonisationModel1::eProbaShellMap[6] private
Definition at line 160 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 160 of file G4DNABornIonisationModel1.hh
Referenced by Initialise(), and TransferedEnergy().
std::vector<G4double> G4DNABornIonisationModel1::eTdummyVec private
Definition at line 152 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 152 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), Initialise(), and TransferedEnergy().
VecMap G4DNABornIonisationModel1::eVecm private
Definition at line 157 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 157 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), Initialise(), and ~G4DNABornIonisationModel1().
G4bool G4DNABornIonisationModel1::fasterCode private
Definition at line 93 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 93 of file G4DNABornIonisationModel1.hh
Referenced by G4DNABornIonisationModel1(), Initialise(), Interpolate(), SampleSecondaries(), and SelectFasterComputation().
G4VAtomDeexcitation* G4DNABornIonisationModel1::fAtomDeexcitation private
Definition at line 101 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 101 of file G4DNABornIonisationModel1.hh
Referenced by G4DNABornIonisationModel1(), Initialise(), and SampleSecondaries().
G4ParticleChangeForGamma* G4DNABornIonisationModel1::fParticleChangeForGamma protected
Definition at line 89 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DNABornIonisationModel1.hh
Referenced by G4DNABornIonisationModel1(), Initialise(), and SampleSecondaries().
const std::vector<G4double>* G4DNABornIonisationModel1::fpMolWaterDensity private
Definition at line 98 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 98 of file G4DNABornIonisationModel1.hh
Referenced by G4DNABornIonisationModel1(), and Initialise().
std::map<G4String,G4double,std::less<G4String> > G4DNABornIonisationModel1::highEnergyLimit private
Definition at line 104 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNABornIonisationModel1.hh
Referenced by CrossSectionPerVolume(), Initialise(), and SampleSecondaries().
G4bool G4DNABornIonisationModel1::isInitialised private
Definition at line 110 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DNABornIonisationModel1.hh
Referenced by Initialise().
std::map<G4String,G4double,std::less<G4String> > G4DNABornIonisationModel1::lowEnergyLimit private
Definition at line 103 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 103 of file G4DNABornIonisationModel1.hh
Referenced by CrossSectionPerVolume(), Initialise(), and SampleSecondaries().
TriDimensionMap G4DNABornIonisationModel1::pDiffCrossSectionData[6] private
Definition at line 149 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 149 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), and Initialise().
TriDimensionMap G4DNABornIonisationModel1::pNrjTransfData[6] private
Definition at line 150 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 150 of file G4DNABornIonisationModel1.hh
Referenced by Initialise(), and TransferedEnergy().
VecMap G4DNABornIonisationModel1::pProbaShellMap[6] private
Definition at line 161 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 161 of file G4DNABornIonisationModel1.hh
Referenced by Initialise(), and TransferedEnergy().
std::vector<G4double> G4DNABornIonisationModel1::pTdummyVec private
Definition at line 153 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 153 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), Initialise(), and TransferedEnergy().
VecMap G4DNABornIonisationModel1::pVecm private
Definition at line 158 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 158 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), Initialise(), and ~G4DNABornIonisationModel1().
G4bool G4DNABornIonisationModel1::spScaling private
Definition at line 95 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 95 of file G4DNABornIonisationModel1.hh
Referenced by CrossSectionPerVolume(), G4DNABornIonisationModel1(), and SelectSPScaling().
G4bool G4DNABornIonisationModel1::statCode private
Definition at line 94 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 94 of file G4DNABornIonisationModel1.hh
Referenced by G4DNABornIonisationModel1(), SampleSecondaries(), and SelectStationary().
MapData G4DNABornIonisationModel1::tableData private
Definition at line 119 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 119 of file G4DNABornIonisationModel1.hh
Referenced by CrossSectionPerVolume(), GetPartialCrossSection(), Initialise(), RandomSelect(), and ~G4DNABornIonisationModel1().
MapFile G4DNABornIonisationModel1::tableFile private
Definition at line 116 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 116 of file G4DNABornIonisationModel1.hh
Referenced by Initialise().
G4int G4DNABornIonisationModel1::verboseLevel private
Definition at line 111 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 111 of file G4DNABornIonisationModel1.hh
Referenced by CrossSectionPerVolume(), G4DNABornIonisationModel1(), Initialise(), and SampleSecondaries().
G4DNAWaterIonisationStructure G4DNABornIonisationModel1::waterStructure private
Definition at line 123 of file G4DNABornIonisationModel1.hh.
View newest version in sPHENIX GitHub at line 123 of file G4DNABornIonisationModel1.hh
Referenced by DifferentialCrossSection(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNABornIonisationModel1.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNABornIonisationModel1.cc