ECCE @ EIC Software: G4VMoleculeCounter Class Reference
G4VMoleculeCounter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4VMoleculeCounter.hh>
Public Types
using Reactant = const G4MolecularConfiguration
Public Member Functions
virtual void Initialize ()=0
virtual void ResetCounter ()=0
virtual void AddAMoleculeAtTime (Reactant *, G4double time, const G4ThreeVector *position=nullptr, int number=1)=0
virtual void RemoveAMoleculeAtTime (Reactant *, G4double time, const G4ThreeVector *position=nullptr, int number=1)=0
virtual void DontRegister (const G4MoleculeDefinition *)
virtual bool IsRegistered (const G4MoleculeDefinition *)
virtual void RegisterAll ()
Static Public Member Functions
static void SetInstance (G4VMoleculeCounter *)
static void DeleteInstance ()
static G4VMoleculeCounter * Instance ()
static void InitializeInstance ()
static void Use (G4bool flag=true)
static G4bool InUse ()
Protected Member Functions
G4VMoleculeCounter ()=default
virtual ~G4VMoleculeCounter ()=default
Static Protected Attributes
static G4ThreadLocal
G4VMoleculeCounter * fpInstance = nullptr
static G4bool fUse = false
Detailed Description
Definition at line 43 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VMoleculeCounter.hh
Member Typedef Documentation
using G4VMoleculeCounter::Reactant = const G4MolecularConfiguration
Definition at line 58 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VMoleculeCounter.hh
Constructor & Destructor Documentation
G4VMoleculeCounter::G4VMoleculeCounter () protected default
virtual G4VMoleculeCounter::~G4VMoleculeCounter () protected virtual default
Member Function Documentation
virtual void G4VMoleculeCounter::AddAMoleculeAtTime (Reactant * , G4double time, const G4ThreeVector * position = nullptr, int number = 1) pure virtual
void G4VMoleculeCounter::DeleteInstance () static
Definition at line 78 of file G4VMoleculeCounter.cc.
View newest version in sPHENIX GitHub at line 78 of file G4VMoleculeCounter.cc
References fpInstance.
Referenced by G4DNAChemistryManager::Clear().
virtual void G4VMoleculeCounter::DontRegister (const G4MoleculeDefinition *) inline virtual
Reimplemented in G4MoleculeCounter.
Definition at line 94 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VMoleculeCounter.hh
virtual void G4VMoleculeCounter::Initialize () pure virtual
Implemented in G4MoleculeCounter.
Referenced by InitializeInstance().
void G4VMoleculeCounter::InitializeInstance () static
Definition at line 89 of file G4VMoleculeCounter.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VMoleculeCounter.cc
References fpInstance, and Initialize().
Referenced by G4DNAChemistryManager::InitializeThread().
G4VMoleculeCounter * G4VMoleculeCounter::Instance (void) static
Definition at line 67 of file G4VMoleculeCounter.cc.
View newest version in sPHENIX GitHub at line 67 of file G4VMoleculeCounter.cc
References fpInstance.
Referenced by G4Molecule::BuildTrack(), G4DNAElectronHoleRecombination::MakeReaction(), G4DNAChemistryManager::Run(), and G4Molecule::~G4Molecule().
G4bool G4VMoleculeCounter::InUse () static
Definition at line 106 of file G4VMoleculeCounter.cc.
View newest version in sPHENIX GitHub at line 106 of file G4VMoleculeCounter.cc
References fUse.
Referenced by G4Molecule::BuildTrack(), and G4DNAElectronHoleRecombination::MakeReaction().
virtual bool G4VMoleculeCounter::IsRegistered (const G4MoleculeDefinition *) inline virtual
Reimplemented in G4MoleculeCounter.
Definition at line 98 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 98 of file G4VMoleculeCounter.hh
virtual void G4VMoleculeCounter::RegisterAll () inline virtual
Reimplemented in G4MoleculeCounter.
Definition at line 103 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VMoleculeCounter.hh
virtual void G4VMoleculeCounter::RemoveAMoleculeAtTime (Reactant * , G4double time, const G4ThreeVector * position = nullptr, int number = 1) pure virtual
virtual void G4VMoleculeCounter::ResetCounter () pure virtual
Implemented in G4MoleculeCounter.
Referenced by G4DNAChemistryManager::Run().
void G4VMoleculeCounter::SetInstance (G4VMoleculeCounter * pCounterInstance) static
Definition at line 43 of file G4VMoleculeCounter.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VMoleculeCounter.cc
References fpInstance, G4endl, G4Exception(), and JustWarning.
void G4VMoleculeCounter::Use (G4bool flag = true) static
Definition at line 99 of file G4VMoleculeCounter.cc.
View newest version in sPHENIX GitHub at line 99 of file G4VMoleculeCounter.cc
References fUse.
Member Data Documentation
G4ThreadLocal G4VMoleculeCounter * G4VMoleculeCounter::fpInstance = nullptr static protected
Definition at line 46 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VMoleculeCounter.hh
Referenced by DeleteInstance(), InitializeInstance(), Instance(), and SetInstance().
G4bool G4VMoleculeCounter::fUse = false static protected
Definition at line 47 of file G4VMoleculeCounter.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VMoleculeCounter.hh
Referenced by InUse(), and Use().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4VMoleculeCounter.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4VMoleculeCounter.cc