ECCE @ EIC Software: G4FastListNode< OBJECT > Class Template Reference
G4FastListNode< OBJECT > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh>
Public Member Functions
~G4FastListNode ()
OBJECT * GetObject ()
const OBJECT * GetObject () const
G4FastListNode< OBJECT > * GetNext ()
const G4FastListNode< OBJECT > * GetNext () const
G4FastListNode< OBJECT > * GetPrevious ()
const G4FastListNode< OBJECT > * GetPrevious () const
bool IsAttached ()
G4FastListNode (OBJECT *track=0)
void SetNext (G4FastListNode< OBJECT > *node)
void SetPrevious (G4FastListNode< OBJECT > *node)
void SetAttachedToList (bool flag)
void UnHook ()
void DetachYourSelf ()
Public Attributes
bool fAttachedToList
G4shared_ptr< _ListRef
< G4FastList< OBJECT > > > fListRef
OBJECT * fpObject
G4FastListNode< OBJECT > * fpPrevious
G4FastListNode< OBJECT > * fpNext
Private Types
typedef type_wrapper< OBJECT > ObjectW
typedef G4FastList< typename
ObjectW::type > LIST
typedef type_wrapper
< G4FastList< OBJECT > > ListW
typedef type_wrapper
< G4ManyFastLists< OBJECT > > ManyListsW
typedef type_wrapper
< G4ManyFastLists_iterator
< OBJECT > > ManyListsIteratorW
Detailed Description
template<class OBJECT>
class G4FastListNode< OBJECT >
G4FastListNode is the entity actually stored by the G4FastList. A G4FastListNode should belong only to one list. Also, an object should belong only to one list.
Definition at line 125 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 125 of file G4FastList.hh
Member Typedef Documentation
template<class OBJECT> typedef G4FastList<typename ObjectW::type> G4FastListNode< OBJECT >::LIST private
Definition at line 128 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 128 of file G4FastList.hh
template<class OBJECT> typedef type_wrapper<G4FastList<OBJECT> > G4FastListNode< OBJECT >::ListW private
Definition at line 130 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 130 of file G4FastList.hh
template<class OBJECT> typedef type_wrapper<G4ManyFastLists_iterator<OBJECT> > G4FastListNode< OBJECT >::ManyListsIteratorW private
Definition at line 134 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 134 of file G4FastList.hh
template<class OBJECT> typedef type_wrapper<G4ManyFastLists<OBJECT> > G4FastListNode< OBJECT >::ManyListsW private
Definition at line 132 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 132 of file G4FastList.hh
template<class OBJECT> typedef type_wrapper<OBJECT> G4FastListNode< OBJECT >::ObjectW private
Definition at line 127 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 127 of file G4FastList.hh
Constructor & Destructor Documentation
template<class OBJECT> G4FastListNode< OBJECT >::~G4FastListNode ()
template<class OBJECT> G4FastListNode< OBJECT >::G4FastListNode (OBJECT * track = 0)
Default constructor
Member Function Documentation
template<class OBJECT> void G4FastListNode< OBJECT >::DetachYourSelf ()
Referenced by G4FastList< G4Track >::EraseListNode().
template<class OBJECT> G4FastListNode<OBJECT>* G4FastListNode< OBJECT >::GetNext () inline
Definition at line 162 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 162 of file G4FastList.hh
Referenced by G4FastList< G4Track >::EraseListNode(), G4FastList_iterator< OBJECT >::operator++(), and G4FastList_const_iterator< OBJECT >::operator++().
template<class OBJECT> const G4FastListNode<OBJECT>* G4FastListNode< OBJECT >::GetNext () const inline
Definition at line 166 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 166 of file G4FastList.hh
template<class OBJECT> OBJECT* G4FastListNode< OBJECT >::GetObject () inline
Definition at line 152 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 152 of file G4FastList.hh
Referenced by G4FastList< G4Track >::CheckFlag(), G4FastList_const_iterator< OBJECT >::operator*(), G4FastList_const_iterator< OBJECT >::operator->(), and G4ManyFastLists< G4Track >::RemoveLists().
template<class OBJECT> const OBJECT* G4FastListNode< OBJECT >::GetObject () const inline
Definition at line 157 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 157 of file G4FastList.hh
template<class OBJECT> G4FastListNode<OBJECT>* G4FastListNode< OBJECT >::GetPrevious () inline
Definition at line 170 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 170 of file G4FastList.hh
Referenced by G4FastList_iterator< OBJECT >::operator--(), and G4FastList_const_iterator< OBJECT >::operator--().
template<class OBJECT> const G4FastListNode<OBJECT>* G4FastListNode< OBJECT >::GetPrevious () const inline
Definition at line 174 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 174 of file G4FastList.hh
template<class OBJECT> bool G4FastListNode< OBJECT >::IsAttached () inline
Definition at line 178 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 178 of file G4FastList.hh
template<class OBJECT> void G4FastListNode< OBJECT >::SetAttachedToList (bool flag) inline
Definition at line 195 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 195 of file G4FastList.hh
template<class OBJECT> void G4FastListNode< OBJECT >::SetNext (G4FastListNode< OBJECT > * node) inline
Definition at line 187 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 187 of file G4FastList.hh
template<class OBJECT> void G4FastListNode< OBJECT >::SetPrevious (G4FastListNode< OBJECT > * node) inline
Definition at line 191 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 191 of file G4FastList.hh
template<class OBJECT> void G4FastListNode< OBJECT >::UnHook ()
Member Data Documentation
template<class OBJECT> bool G4FastListNode< OBJECT >::fAttachedToList
Definition at line 204 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 204 of file G4FastList.hh
Referenced by G4FastList< G4Track >::Flag(), G4FastListNode< G4FastList< G4Track > >::IsAttached(), and G4FastListNode< G4FastList< G4Track > >::SetAttachedToList().
template<class OBJECT> G4shared_ptr<_ListRef<G4FastList<OBJECT> > > G4FastListNode< OBJECT >::fListRef
Definition at line 205 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 205 of file G4FastList.hh
Referenced by G4FastList< G4Track >::CheckFlag(), G4FastList< G4Track >::Flag(), and G4FastList< G4Track >::GetList().
template<class OBJECT> G4FastListNode<OBJECT>* G4FastListNode< OBJECT >::fpNext
Definition at line 208 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 208 of file G4FastList.hh
Referenced by G4FastListNode< G4FastList< G4Track > >::GetNext(), and G4FastListNode< G4FastList< G4Track > >::SetNext().
template<class OBJECT> OBJECT* G4FastListNode< OBJECT >::fpObject
Definition at line 206 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 206 of file G4FastList.hh
Referenced by G4FastListNode< G4Track >::DetachYourSelf(), and G4FastListNode< G4FastList< G4Track > >::GetObject().
template<class OBJECT> G4FastListNode<OBJECT>* G4FastListNode< OBJECT >::fpPrevious
Definition at line 207 of file G4FastList.hh.
View newest version in sPHENIX GitHub at line 207 of file G4FastList.hh
Referenced by G4FastListNode< G4FastList< G4Track > >::GetPrevious(), and G4FastListNode< G4FastList< G4Track > >::SetPrevious().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4FastList.hh