ECCE @ EIC Software: G3Pos Class Reference
G3Pos Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3Pos.hh>
Public Member Functions
G3Pos ()
G3Pos (G4String M, G4int C, G4ThreeVector *T, G4int R, G4String O)
G4bool operator== (const G3Pos &g3p) const
virtual ~G3Pos ()
G4String & GetMotherName ()
G4int GetIrot ()
G4ThreeVector * GetPos ()
G4int GetCopy ()
G4String & GetOnly ()
Private Attributes
G4String _MotherName
G4int _Copy
G4ThreeVector * _Position
G4int _Irot
G4String _Only
Detailed Description
Definition at line 42 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 42 of file G3Pos.hh
Constructor & Destructor Documentation
G3Pos::G3Pos () inline
Definition at line 47 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 47 of file G3Pos.hh
G3Pos::G3Pos (G4String M, G4int C, G4ThreeVector * T, G4int R, G4String O)
Definition at line 33 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 33 of file G3Pos.cc
References _Only, G4cerr, and G4endl.
G3Pos::~G3Pos () virtual
Definition at line 49 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 49 of file G3Pos.cc
Member Function Documentation
G4int G3Pos::GetCopy ()
Definition at line 67 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 67 of file G3Pos.cc
References _Copy.
Referenced by G3toG4BuildPVTree().
G4int G3Pos::GetIrot ()
Definition at line 62 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 62 of file G3Pos.cc
References _Irot.
Referenced by G3toG4BuildPVTree(), and GetTransform3D().
G4String & G3Pos::GetMotherName ()
Definition at line 57 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 57 of file G3Pos.cc
References _MotherName.
Referenced by G3toG4BuildPVTree().
G4String & G3Pos::GetOnly ()
Definition at line 77 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 77 of file G3Pos.cc
References _Only.
Referenced by G3VolTableEntry::AddG3Pos().
G4ThreeVector * G3Pos::GetPos ()
Definition at line 72 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 72 of file G3Pos.cc
References _Position.
Referenced by G3toG4BuildPVTree(), and GetTransform3D().
G4bool G3Pos::operator== (const G3Pos & g3p) const
Definition at line 52 of file G3Pos.cc.
View newest version in sPHENIX GitHub at line 52 of file G3Pos.cc
Member Data Documentation
G4int G3Pos::_Copy private
Definition at line 68 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 68 of file G3Pos.hh
Referenced by GetCopy().
G4int G3Pos::_Irot private
Definition at line 70 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 70 of file G3Pos.hh
Referenced by GetIrot().
G4String G3Pos::_MotherName private
Definition at line 67 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 67 of file G3Pos.hh
Referenced by GetMotherName().
G4String G3Pos::_Only private
Definition at line 71 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 71 of file G3Pos.hh
Referenced by G3Pos(), and GetOnly().
G4ThreeVector* G3Pos::_Position private
Definition at line 69 of file G3Pos.hh.
View newest version in sPHENIX GitHub at line 69 of file G3Pos.hh
Referenced by GetPos().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3Pos.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3Pos.cc