ECCE @ EIC Software: GammaRayTelPhysicsList Class Reference
GammaRayTelPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelPhysicsList.hh>
Public Member Functions
GammaRayTelPhysicsList ()
virtual ~GammaRayTelPhysicsList ()
void ConstructParticle ()
void SetCuts ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
void SetCutForPositron (G4double)
void AddPhysicsList (const G4String &name)
void ConstructProcess ()
void AddPackage (const G4String &name)
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Private Attributes
G4EmConfigurator em_config
G4double cutForGamma
G4double cutForElectron
G4double cutForPositron
G4bool helIsRegisted
G4bool bicIsRegisted
G4bool biciIsRegisted
G4bool locIonIonInelasticIsRegistered
G4bool radioactiveDecayIsRegisted
G4String emName
G4VPhysicsConstructor * emPhysicsList
G4VPhysicsConstructor * decPhysicsList
std::vector
< G4VPhysicsConstructor * > hadronPhys
GammaRayTelPhysicsListMessenger * pMessenger
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Detailed Description
Definition at line 41 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 41 of file GammaRayTelPhysicsList.hh
Constructor & Destructor Documentation
GammaRayTelPhysicsList::GammaRayTelPhysicsList ()
Definition at line 61 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 61 of file GammaRayTelPhysicsList.cc
References biciIsRegisted, bicIsRegisted, cutForElectron, cutForGamma, cutForPositron, decPhysicsList, G4VUserPhysicsList::defaultCutValue, emName, emPhysicsList, helIsRegisted, G4LossTableManager::Instance(), locIonIonInelasticIsRegistered, micrometer, pMessenger, radioactiveDecayIsRegisted, and G4VModularPhysicsList::SetVerboseLevel().
GammaRayTelPhysicsList::~GammaRayTelPhysicsList () virtual
Definition at line 88 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 88 of file GammaRayTelPhysicsList.cc
References decPhysicsList, emPhysicsList, hadronPhys, and pMessenger.
Member Function Documentation
void GammaRayTelPhysicsList::AddPackage (const G4String & name)
Definition at line 97 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 97 of file GammaRayTelPhysicsList.cc
References G4VModularPhysicsList::GetPhysics(), G4PhysListFactory::GetReferencePhysList(), G4VModularPhysicsList::RegisterPhysics(), and tmp.
Referenced by GammaRayTelPhysicsListMessenger::SetNewValue().
void GammaRayTelPhysicsList::AddPhysicsList (const G4String & name)
Definition at line 145 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 145 of file GammaRayTelPhysicsList.cc
References biciIsRegisted, bicIsRegisted, emName, emPhysicsList, G4cout, G4endl, hadronPhys, helIsRegisted, radioactiveDecayIsRegisted, and G4VModularPhysicsList::verboseLevel.
Referenced by GammaRayTelPhysicsListMessenger::SetNewValue().
void GammaRayTelPhysicsList::ConstructParticle (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 113 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 113 of file GammaRayTelPhysicsList.cc
References G4VPhysicsConstructor::ConstructParticle(), and decPhysicsList.
void GammaRayTelPhysicsList::ConstructProcess (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 119 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 119 of file GammaRayTelPhysicsList.cc
References G4EmConfigurator::AddModels(), G4VUserPhysicsList::AddTransportation(), G4VPhysicsConstructor::ConstructProcess(), decPhysicsList, em_config, emPhysicsList, and hadronPhys.
void GammaRayTelPhysicsList::SetCutForElectron (G4double cut)
Definition at line 244 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 244 of file GammaRayTelPhysicsList.cc
References cutForElectron, G4Electron::Electron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by GammaRayTelPhysicsListMessenger::SetNewValue().
void GammaRayTelPhysicsList::SetCutForGamma (G4double cut)
Definition at line 238 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 238 of file GammaRayTelPhysicsList.cc
References cutForGamma, G4Gamma::Gamma(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by GammaRayTelPhysicsListMessenger::SetNewValue().
void GammaRayTelPhysicsList::SetCutForPositron (G4double cut)
Definition at line 250 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 250 of file GammaRayTelPhysicsList.cc
References cutForPositron, G4Positron::Positron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by GammaRayTelPhysicsListMessenger::SetNewValue().
void GammaRayTelPhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 217 of file GammaRayTelPhysicsList.cc.
View newest version in sPHENIX GitHub at line 217 of file GammaRayTelPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), eV, G4BestUnit, G4cout, G4endl, G4ProductionCutsTable::GetProductionCutsTable(), GeV, G4VUserPhysicsList::SetCutValue(), G4ProductionCutsTable::SetEnergyRange(), and G4VModularPhysicsList::verboseLevel.
Member Data Documentation
G4bool GammaRayTelPhysicsList::biciIsRegisted private
Definition at line 70 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), and GammaRayTelPhysicsList().
G4bool GammaRayTelPhysicsList::bicIsRegisted private
Definition at line 69 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), and GammaRayTelPhysicsList().
G4double GammaRayTelPhysicsList::cutForElectron private
Definition at line 65 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file GammaRayTelPhysicsList.hh
Referenced by GammaRayTelPhysicsList(), SetCutForElectron(), and SetCuts().
G4double GammaRayTelPhysicsList::cutForGamma private
Definition at line 64 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file GammaRayTelPhysicsList.hh
Referenced by GammaRayTelPhysicsList(), SetCutForGamma(), and SetCuts().
G4double GammaRayTelPhysicsList::cutForPositron private
Definition at line 66 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 66 of file GammaRayTelPhysicsList.hh
Referenced by GammaRayTelPhysicsList(), SetCutForPositron(), and SetCuts().
G4VPhysicsConstructor* GammaRayTelPhysicsList::decPhysicsList private
Definition at line 76 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 76 of file GammaRayTelPhysicsList.hh
Referenced by ConstructParticle(), ConstructProcess(), GammaRayTelPhysicsList(), and ~GammaRayTelPhysicsList().
G4EmConfigurator GammaRayTelPhysicsList::em_config private
Definition at line 62 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file GammaRayTelPhysicsList.hh
Referenced by ConstructProcess().
G4String GammaRayTelPhysicsList::emName private
Definition at line 74 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), and GammaRayTelPhysicsList().
G4VPhysicsConstructor* GammaRayTelPhysicsList::emPhysicsList private
Definition at line 75 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 75 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), ConstructProcess(), GammaRayTelPhysicsList(), and ~GammaRayTelPhysicsList().
std::vector<G4VPhysicsConstructor*> GammaRayTelPhysicsList::hadronPhys private
Definition at line 77 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 77 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), ConstructProcess(), and ~GammaRayTelPhysicsList().
G4bool GammaRayTelPhysicsList::helIsRegisted private
Definition at line 68 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 68 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), and GammaRayTelPhysicsList().
G4bool GammaRayTelPhysicsList::locIonIonInelasticIsRegistered private
Definition at line 71 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 71 of file GammaRayTelPhysicsList.hh
Referenced by GammaRayTelPhysicsList().
GammaRayTelPhysicsListMessenger* GammaRayTelPhysicsList::pMessenger private
Definition at line 79 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 79 of file GammaRayTelPhysicsList.hh
Referenced by GammaRayTelPhysicsList(), and ~GammaRayTelPhysicsList().
G4bool GammaRayTelPhysicsList::radioactiveDecayIsRegisted private
Definition at line 72 of file GammaRayTelPhysicsList.hh.
View newest version in sPHENIX GitHub at line 72 of file GammaRayTelPhysicsList.hh
Referenced by AddPhysicsList(), and GammaRayTelPhysicsList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelPhysicsList.cc