ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/DirectAccess.cc File Reference
DirectAccess.cc File Reference
Main program of the electromagnetic/TestEm0 example.
#include "G4Material.hh"
#include "G4PEEffectFluoModel.hh"
#include "G4KleinNishinaCompton.hh"
#include "G4BetheHeitlerModel.hh"
#include "G4eeToTwoGammaModel.hh"
#include "G4MollerBhabhaModel.hh"
#include "G4SeltzerBergerModel.hh"
#include "G4BetheBlochModel.hh"
#include "G4BraggModel.hh"
#include "G4MuBetheBlochModel.hh"
#include "G4MuBremsstrahlungModel.hh"
#include "G4MuPairProductionModel.hh"
#include "globals.hh"
#include "G4UnitsTable.hh"
#include "G4SystemOfUnits.hh"
#include "G4Gamma.hh"
#include "G4Positron.hh"
#include "G4Electron.hh"
#include "G4Proton.hh"
#include "G4MuonPlus.hh"
#include "G4DataVector.hh"
#include "G4NistManager.hh"
#include "G4ParticleTable.hh"
Functions
int main ()
Detailed Description
Main program of the electromagnetic/TestEm0 example.
Definition in file DirectAccess.cc.
Function Documentation
int main ()
Definition at line 67 of file DirectAccess.cc.
View newest version in sPHENIX GitHub at line 67 of file DirectAccess.cc
References A(), G4UnitDefinition::BuildUnitsTable(), G4VEmModel::ComputeCrossSectionPerAtom(), G4VEmModel::ComputeDEDXPerVolume(), G4VEmModel::ComputeMeanFreePath(), dE, G4Electron::Electron(), Emax, Emin, G4NistManager::FindOrBuildMaterial(), G4BestUnit, G4cout, G4endl, G4Gamma::Gamma(), G4Material::GetA(), G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleTable::GetParticleTable(), G4Material::GetZ(), GeV, G4VEmModel::Initialise(), G4NistManager::Instance(), keV, material(), MeV, G4MuonPlus::MuonPlus(), G4Positron::Positron(), G4Proton::Proton(), G4VEmModel::SetCurrentCouple(), G4ParticleTable::SetReadiness(), and Z.