ECCE @ EIC Software: macros/blob/master/common/G4_hFarBwdBeamLine_EIC.C File Reference
G4_hFarBwdBeamLine_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/BeamLineMagnetSubsystem.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <eicg4zdc/EICG4ZDCHitTree.h>
#include <eicg4zdc/EICG4ZDCNtuple.h>
#include <eicg4zdc/EICG4ZDCSubsystem.h>
#include <eicg4lumi/EICG4LumiSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <TSystem.h>
Namespaces
namespace Enable
namespace hFarBwdBeamLine
Macros
#define MACRO_G4HFARBWDBEAMLINE_EIC_C
Functions
PHG4CylinderSubsystem * hFarBwdBeamLine::hFarBwdBeamLineEnclosure (nullptr)
void hFarBwdBeamLineInit ()
void hFarBwdDefineMagnets (PHG4Reco *g4Reco)
void hFarBwdDefineDetectorsIP6 (PHG4Reco *g4Reco)
void hFarBwdDefineDetectorsIP8 (PHG4Reco *g4Reco)
void hFarBwdDefineBeamPipe (PHG4Reco *g4Reco)
Variables
bool Enable::HFARBWD_MAGNETS = false
bool Enable::HFARBWD_VIRTUAL_DETECTORS = false
bool Enable::HFARBWD_PIPE = false
bool Enable::HFARBWD_OVERLAPCHECK = false
int Enable::HFARBWD_VERBOSITY = 0
bool Enable::HFARBWD_MAGNETS_IP6 = false
bool Enable::HFARBWD_MAGNETS_IP8 = false
bool Enable::HFARBWD_VIRTUAL_DETECTORS_IP6 = false
bool Enable::HFARBWD_VIRTUAL_DETECTORS_IP8 = false
double hFarBwdBeamLine::starting_z = -463
double hFarBwdBeamLine::enclosure_z_max = NAN
double hFarBwdBeamLine::enclosure_r_max = NAN
double hFarBwdBeamLine::enclosure_center = NAN
BeamLineMagnetSubsystem * hFarBwdBeamLine::B0Magnet = (nullptr)
Macro Definition Documentation
#define MACRO_G4HFARBWDBEAMLINE_EIC_C
Definition at line 2 of file G4_hFarBwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_hFarBwdBeamLine_EIC.C
Function Documentation
void hFarBwdBeamLineInit ()
Definition at line 54 of file G4_hFarBwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 54 of file G4_hFarBwdBeamLine_EIC.C
References hFarBwdBeamLine::enclosure_center, hFarBwdBeamLine::enclosure_r_max, hFarBwdBeamLine::enclosure_z_max, Enable::HFARBWD_MAGNETS, Enable::HFARBWD_MAGNETS_IP6, Enable::HFARBWD_MAGNETS_IP8, Enable::HFARBWD_VIRTUAL_DETECTORS, Enable::HFARBWD_VIRTUAL_DETECTORS_IP6, Enable::HFARBWD_VIRTUAL_DETECTORS_IP8, Enable::IP6, Enable::IP8, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and hFarBwdBeamLine::starting_z.
Referenced by G4Init().
void hFarBwdDefineBeamPipe (PHG4Reco * g4Reco)
Definition at line 588 of file G4_hFarBwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 588 of file G4_hFarBwdBeamLine_EIC.C
void hFarBwdDefineDetectorsIP6 (PHG4Reco * g4Reco)
Definition at line 284 of file G4_hFarBwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 284 of file G4_hFarBwdBeamLine_EIC.C
References Enable::BWD, hFarBwdBeamLine::enclosure_center, Enable::HFARBWD_OVERLAPCHECK, Enable::HFARBWD_VERBOSITY, Enable::HFARBWD_VIRTUAL_DETECTORS_IP6, Enable::HFARBWD_VIRTUAL_DETECTORS_IP8, hFarBwdBeamLine::hFarBwdBeamLineEnclosure(), max, Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), and Enable::VERBOSITY.
Referenced by G4Setup().
void hFarBwdDefineDetectorsIP8 (PHG4Reco * g4Reco)
Definition at line 548 of file G4_hFarBwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 548 of file G4_hFarBwdBeamLine_EIC.C
References hFarBwdBeamLine::enclosure_center, Enable::HFARBWD_OVERLAPCHECK, Enable::HFARBWD_VERBOSITY, Enable::HFARBWD_VIRTUAL_DETECTORS_IP6, Enable::HFARBWD_VIRTUAL_DETECTORS_IP8, hFarBwdBeamLine::hFarBwdBeamLineEnclosure(), max, Enable::OVERLAPCHECK, PHG4Reco::registerSubsystem(), and Enable::VERBOSITY.
Referenced by G4Setup().
void hFarBwdDefineMagnets (PHG4Reco * g4Reco)
Definition at line 92 of file G4_hFarBwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 92 of file G4_hFarBwdBeamLine_EIC.C
References angle, hFarBwdBeamLine::B0Magnet, PHG4DetectorSubsystem::BlackHole(), hFarBwdBeamLine::enclosure_center, hFarBwdBeamLine::enclosure_r_max, hFarBwdBeamLine::enclosure_z_max, Enable::HFARBWD_E_ENERGY, Enable::HFARBWD_OVERLAPCHECK, Enable::HFARBWD_VERBOSITY, hFarBwdBeamLine::hFarBwdBeamLineEnclosure(), Enable::HFARFWD_MAGNETS_IP6, Enable::HFARFWD_MAGNETS_IP8, BTOF::length, max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), hFarBwdBeamLine::starting_z, PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), x, y, and z.
Referenced by G4Setup().