ECCE @ EIC Software: G4ParameterisationTrdY Class Reference
G4ParameterisationTrdY Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationTrd.hh>
Public Member Functions
G4ParameterisationTrdY (EAxis axis, G4int nCopies, G4double width, G4double offset, G4VSolid *motherSolid, DivisionType divType)
~G4ParameterisationTrdY ()
void CheckParametersValidity ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Trd &trd, const G4int copyNo, const G4VPhysicalVolume *pv) const
Public Member Functions inherited from G4VParameterisationTrd
G4VParameterisationTrd (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationTrd ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VParameterisationTrd
G4bool bDivInTrap = false
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 129 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ParameterisationTrd.hh
Constructor & Destructor Documentation
G4ParameterisationTrdY::G4ParameterisationTrdY (EAxis axis, G4int nCopies, G4double width, G4double offset, G4VSolid * motherSolid, DivisionType divType)
Definition at line 287 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 287 of file G4ParameterisationTrd.cc
References G4VDivisionParameterisation::CalculateNDiv(), G4VDivisionParameterisation::CalculateWidth(), CheckParametersValidity(), DivNDIV, DivWIDTH, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Trd::GetYHalfLength1(), offset, G4VDivisionParameterisation::SetType(), and G4VDivisionParameterisation::verbose.
G4ParameterisationTrdY::~G4ParameterisationTrdY ()
Definition at line 319 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 319 of file G4ParameterisationTrd.cc
Member Function Documentation
void G4ParameterisationTrdY::CheckParametersValidity () virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 393 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 393 of file G4ParameterisationTrd.cc
References G4VDivisionParameterisation::CheckParametersValidity(), FatalException, G4VDivisionParameterisation::fmotherSolid, G4endl, G4Exception(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4VDivisionParameterisation::kCarTolerance, and message().
Referenced by G4ParameterisationTrdY().
void G4ParameterisationTrdY::ComputeDimensions (G4Trd & trd, const G4int copyNo, const G4VPhysicalVolume * pv) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 370 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 370 of file G4ParameterisationTrd.cc
References G4VSolid::DumpInfo(), G4VDivisionParameterisation::fhgap, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetZHalfLength(), G4Trd::SetAllParameters(), and G4VDivisionParameterisation::verbose.
void G4ParameterisationTrdY::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 150 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 152 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 154 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 156 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 158 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 160 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 162 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 164 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 164 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 166 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 168 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 170 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 172 of file G4ParameterisationTrd.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ParameterisationTrd.hh
void G4ParameterisationTrdY::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 333 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 333 of file G4ParameterisationTrd.cc
References FatalException, G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Exception(), G4Trd::GetYHalfLength1(), kYAxis, message(), Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), CLHEP::Hep3Vector::setY(), and G4VDivisionParameterisation::verbose.
G4double G4ParameterisationTrdY::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 324 of file G4ParameterisationTrd.cc.
View newest version in sPHENIX GitHub at line 324 of file G4ParameterisationTrd.cc
References G4VDivisionParameterisation::fmotherSolid, and G4Trd::GetYHalfLength1().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationTrd.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationTrd.cc