ECCE @ EIC Software: ExN04CalorimeterSD Class Reference
ExN04CalorimeterSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04CalorimeterSD.hh>
Public Member Functions
ExN04CalorimeterSD (G4String name)
~ExN04CalorimeterSD ()
virtual void Initialize (G4HCofThisEvent *HCE)
virtual G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
virtual void EndOfEvent (G4HCofThisEvent *HCE)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
ExN04CalorimeterSD (G4String name)
~ExN04CalorimeterSD ()
void Initialize (G4HCofThisEvent *HCE)
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void EndOfEvent (G4HCofThisEvent *HCE)
void clear ()
void DrawAll ()
void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
ExN04CalorimeterHitsCollection * fCalCollection
int fCellID [20][48]
const int fnumberOfCellsInZ
const int fnumberOfCellsInPhi
ExN04CalorimeterHitsCollection * CalCollection
int CellID [20][48]
const int numberOfCellsInZ
const int numberOfCellsInPhi
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 40 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 40 of file ExN04CalorimeterSD.hh
Constructor & Destructor Documentation
ExN04CalorimeterSD::ExN04CalorimeterSD (G4String name)
Definition at line 44 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 44 of file ExN04CalorimeterSD.cc
References G4VSensitiveDetector::collectionName, and G4CollectionNameVector::insert().
ExN04CalorimeterSD::~ExN04CalorimeterSD ()
Definition at line 53 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 53 of file ExN04CalorimeterSD.cc
ExN04CalorimeterSD::ExN04CalorimeterSD (G4String name)
ExN04CalorimeterSD::~ExN04CalorimeterSD ()
Member Function Documentation
void ExN04CalorimeterSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 124 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 124 of file ExN04CalorimeterSD.cc
void ExN04CalorimeterSD::clear () virtual
Reimplemented from G4VSensitiveDetector.
void ExN04CalorimeterSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 129 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 129 of file ExN04CalorimeterSD.cc
void ExN04CalorimeterSD::DrawAll () virtual
Reimplemented from G4VSensitiveDetector.
void ExN04CalorimeterSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 114 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 114 of file ExN04CalorimeterSD.cc
References fCalCollection, and G4VSensitiveDetector::GetCollectionID().
void ExN04CalorimeterSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
void ExN04CalorimeterSD::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 58 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 58 of file ExN04CalorimeterSD.cc
References G4VSensitiveDetector::collectionName, fCalCollection, fCellID, fnumberOfCellsInPhi, fnumberOfCellsInZ, k, G4VSensitiveDetector::SensitiveDetectorName, and G4VSensitiveDetector::verboseLevel.
void ExN04CalorimeterSD::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
void ExN04CalorimeterSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 134 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 134 of file ExN04CalorimeterSD.cc
void ExN04CalorimeterSD::PrintAll () virtual
Reimplemented from G4VSensitiveDetector.
G4bool ExN04CalorimeterSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) virtual
Implements G4VSensitiveDetector.
Definition at line 73 of file ExN04CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 73 of file ExN04CalorimeterSD.cc
References edep, fCalCollection, fCellID, G4cout, G4endl, G4TouchableHistory::GetHistory(), G4VPhysicalVolume::GetLogicalVolume(), G4NavigationHistory::GetTopTransform(), G4THitsCollection< T >::insert(), G4AffineTransform::Invert(), MeV, G4AffineTransform::NetRotation(), G4AffineTransform::NetTranslation(), and G4VSensitiveDetector::verboseLevel.
G4bool ExN04CalorimeterSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) virtual
Implements G4VSensitiveDetector.
Member Data Documentation
ExN04CalorimeterHitsCollection* ExN04CalorimeterSD::CalCollection private
Definition at line 55 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04CalorimeterSD.hh
int ExN04CalorimeterSD::CellID[20][48] private
Definition at line 56 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 56 of file ExN04CalorimeterSD.hh
ExN04CalorimeterHitsCollection* ExN04CalorimeterSD::fCalCollection private
Definition at line 53 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 53 of file ExN04CalorimeterSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
int ExN04CalorimeterSD::fCellID[20][48] private
Definition at line 54 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04CalorimeterSD.hh
Referenced by Initialize(), and ProcessHits().
const int ExN04CalorimeterSD::fnumberOfCellsInPhi private
Definition at line 56 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 56 of file ExN04CalorimeterSD.hh
Referenced by Initialize().
const int ExN04CalorimeterSD::fnumberOfCellsInZ private
Definition at line 55 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04CalorimeterSD.hh
Referenced by Initialize().
const int ExN04CalorimeterSD::numberOfCellsInPhi private
Definition at line 58 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 58 of file ExN04CalorimeterSD.hh
const int ExN04CalorimeterSD::numberOfCellsInZ private
Definition at line 57 of file ExN04CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04CalorimeterSD.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04CalorimeterSD.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04CalorimeterSD.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04CalorimeterSD.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04CalorimeterSD.cc