ECCE @ EIC Software: G4EmDataHandler Class Reference
G4EmDataHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmDataHandler.hh>
Public Member Functions
G4EmDataHandler (size_t nTable)
~G4EmDataHandler ()
size_t SetTable (G4PhysicsTable *)
G4PhysicsTable * MakeTable (size_t idx)
void CleanTable (size_t idx)
G4bool StorePhysicsTable (size_t idx, const G4ParticleDefinition *part, const G4String &fname, G4bool ascii)
G4bool RetrievePhysicsTable (size_t idx, const G4ParticleDefinition *part, const G4String &fname, G4bool ascii)
void SetMasterProcess (const G4VEmProcess *)
const G4VEmProcess * GetMasterProcess (size_t idx) const
const G4PhysicsTable * GetTable (size_t idx) const
G4PhysicsTable * Table (size_t idx) const
const G4PhysicsVector * GetVector (size_t itable, size_t ivec) const
const std::vector
< G4PhysicsTable * > & GetTables () const
G4EmDataHandler & operator= (const G4EmDataHandler &right)=delete
G4EmDataHandler (const G4EmDataHandler &)=delete
Private Attributes
std::vector< G4PhysicsTable * > data
size_t tLength
std::vector< const G4VEmProcess * > masterProcess
Detailed Description
Definition at line 61 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 61 of file G4EmDataHandler.hh
Constructor & Destructor Documentation
G4EmDataHandler::G4EmDataHandler (size_t nTable) explicit
Definition at line 51 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 51 of file G4EmDataHandler.cc
G4EmDataHandler::~G4EmDataHandler ()
Definition at line 58 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 58 of file G4EmDataHandler.cc
References CleanTable(), and tLength.
G4EmDataHandler::G4EmDataHandler (const G4EmDataHandler &) delete
Member Function Documentation
void G4EmDataHandler::CleanTable (size_t idx)
Definition at line 94 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 94 of file G4EmDataHandler.cc
References tLength.
Referenced by ~G4EmDataHandler().
const G4VEmProcess * G4EmDataHandler::GetMasterProcess (size_t idx) const
Definition at line 169 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 169 of file G4EmDataHandler.cc
References masterProcess.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable().
const G4PhysicsTable* G4EmDataHandler::GetTable (size_t idx) const inline
Definition at line 89 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 89 of file G4EmDataHandler.hh
References incremental_prev_tag::idx, and tLength.
const std::vector<G4PhysicsTable*>& G4EmDataHandler::GetTables () const inline
Definition at line 100 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 100 of file G4EmDataHandler.hh
References data.
Referenced by G4GammaGeneralProcess::BuildPhysicsTable().
const G4PhysicsVector* G4EmDataHandler::GetVector (size_t itable, size_t ivec) const inline
Definition at line 97 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 97 of file G4EmDataHandler.hh
Referenced by G4GammaGeneralProcess::ComputeGeneralLambda(), and G4GammaGeneralProcess::GetProbability().
G4PhysicsTable * G4EmDataHandler::MakeTable (size_t idx)
Definition at line 76 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 76 of file G4EmDataHandler.cc
References G4PhysicsTableHelper::PreparePhysicsTable(), and tLength.
Referenced by G4GammaGeneralProcess::InitialiseProcess(), and G4VEmProcess::PreparePhysicsTable().
G4EmDataHandler& G4EmDataHandler::operator= (const G4EmDataHandler & right) delete
G4bool G4EmDataHandler::RetrievePhysicsTable (size_t idx, const G4ParticleDefinition * part, const G4String & fname, G4bool ascii)
Definition at line 130 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 130 of file G4EmDataHandler.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), incremental_prev_tag::idx, G4EmParameters::Instance(), G4PhysicsTable::length(), n, G4PhysicsTableHelper::RetrievePhysicsTable(), G4EmParameters::Spline(), and G4EmParameters::Verbose().
Referenced by G4GammaGeneralProcess::RetrievePhysicsTable().
void G4EmDataHandler::SetMasterProcess (const G4VEmProcess * ptr)
Definition at line 162 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 162 of file G4EmDataHandler.cc
References masterProcess.
Referenced by G4GammaGeneralProcess::InitialiseProcess().
size_t G4EmDataHandler::SetTable (G4PhysicsTable * ptr)
Definition at line 67 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 67 of file G4EmDataHandler.cc
References tLength.
G4bool G4EmDataHandler::StorePhysicsTable (size_t idx, const G4ParticleDefinition * part, const G4String & fname, G4bool ascii)
Definition at line 106 of file G4EmDataHandler.cc.
View newest version in sPHENIX GitHub at line 106 of file G4EmDataHandler.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), and incremental_prev_tag::idx.
Referenced by G4GammaGeneralProcess::StorePhysicsTable().
G4PhysicsTable* G4EmDataHandler::Table (size_t idx) const inline
Definition at line 93 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 93 of file G4EmDataHandler.hh
References incremental_prev_tag::idx, and tLength.
Member Data Documentation
std::vector<G4PhysicsTable*> G4EmDataHandler::data private
Definition at line 108 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 108 of file G4EmDataHandler.hh
Referenced by GetTables().
std::vector<const G4VEmProcess*> G4EmDataHandler::masterProcess private
Definition at line 110 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 110 of file G4EmDataHandler.hh
Referenced by GetMasterProcess(), and SetMasterProcess().
size_t G4EmDataHandler::tLength private
Definition at line 109 of file G4EmDataHandler.hh.
View newest version in sPHENIX GitHub at line 109 of file G4EmDataHandler.hh
Referenced by CleanTable(), GetTable(), MakeTable(), SetTable(), Table(), and ~G4EmDataHandler().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmDataHandler.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmDataHandler.cc