ECCE @ EIC Software: online_distribution/blob/master/newbasic/eventcombiner.cc File Reference
eventcombiner.cc File Reference
#include "fileEventiterator.h"
#include "testEventiterator.h"
#include "phenixTypes.h"
#include "A_Event.h"
#include "ogzBuffer.h"
#include "ophBuffer.h"
#include "ospBuffer.h"
#include "EventTypes.h"
#include "oEvent.h"
#include <cstdlib>
#include <unistd.h>
#include <cstdio>
#include <string>
#include <vector>
#include <bstring.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
Macros
#define DDEVENTITERATOR 1
#define FILEEVENTITERATOR 2
#define TESTEVENTITERATOR 3
#define DDPOOL 4
#define DFILE 5
#define DNULL 6
Functions
void sig_handler (...)
void exitmsg ()
void exithelp ()
void evtcountexitmsg ()
int main (int argc, char *argv[])
Variables
oBuffer * ob
int fd
int file_open = 0
Macro Definition Documentation
#define DDEVENTITERATOR 1
Definition at line 22 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 22 of file eventcombiner.cc
#define DDPOOL 4
Definition at line 25 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 25 of file eventcombiner.cc
#define DFILE 5
Definition at line 26 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 26 of file eventcombiner.cc
#define DNULL 6
Definition at line 27 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 27 of file eventcombiner.cc
#define FILEEVENTITERATOR 2
Definition at line 23 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 23 of file eventcombiner.cc
#define TESTEVENTITERATOR 3
Definition at line 24 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 24 of file eventcombiner.cc
Function Documentation
void evtcountexitmsg ()
Definition at line 79 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 79 of file eventcombiner.cc
References COUT, and g4zmq::exit().
void exithelp ()
Definition at line 57 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 57 of file eventcombiner.cc
References COUT, and g4zmq::exit().
void exitmsg ()
Definition at line 50 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 50 of file eventcombiner.cc
References COUT, and g4zmq::exit().
int main (int argc, char * argv[])
Definition at line 91 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 91 of file eventcombiner.cc
References oBuffer::addEvent(), buffer, c, close(), COUT, E, e, evtcountexitmsg(), g4zmq::exit(), exithelp(), exitmsg(), fd, INPUTHEPMC::filename, Event::getEvtLength(), Event::getEvtSequence(), Event::identify(), it, ob, Acts::open, optarg, and optind.
void sig_handler (...)
Definition at line 244 of file changehitformat.cc.
View newest version in sPHENIX GitHub at line 244 of file changehitformat.cc
References COUT, g4zmq::exit(), and it.
Referenced by main().
Variable Documentation
int fd
Definition at line 87 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 87 of file eventcombiner.cc
Referenced by oncsSub_iddreamv0::decode_payload(), G4FileUtilities::FileExists(), gzdopen(), oncsSub_iddreamv0::iValue(), lustrf(), main(), pystrf(), and oncsSub_iddreamv0::~oncsSub_iddreamv0().
int file_open = 0
Definition at line 88 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 88 of file eventcombiner.cc
oBuffer* ob
Definition at line 86 of file eventcombiner.cc.
View newest version in sPHENIX GitHub at line 86 of file eventcombiner.cc
Referenced by main().