ECCE @ EIC Software: G4TrackStateDependent< T > Class Template Reference
G4TrackStateDependent< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4TrackState.hh>
Public Types
typedef T ClassType
typedef G4TrackState< T > StateType
typedef G4shared_ptr< StateType > StateTypeHandle
Public Member Functions
virtual ~G4TrackStateDependent ()
virtual void SetTrackState (G4shared_ptr< StateType > state)
virtual G4VTrackStateHandle PopTrackState ()
virtual G4VTrackStateHandle GetTrackState () const
virtual StateTypeHandle GetConcreteTrackState () const
virtual void LoadTrackState (G4TrackStateManager &manager)
virtual void SaveTrackState (G4TrackStateManager &manager)
virtual void NewTrackState ()
virtual StateTypeHandle CreateTrackState () const
virtual void ResetTrackState ()
Public Member Functions inherited from G4VTrackStateDependent
G4VTrackStateDependent ()
virtual ~G4VTrackStateDependent ()
Protected Member Functions
G4TrackStateDependent ()
Protected Attributes
StateTypeHandle fpTrackState
Detailed Description
template<class T>
class G4TrackStateDependent< T >
Definition at line 98 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 98 of file G4TrackState.hh
Member Typedef Documentation
template<class T> typedef T G4TrackStateDependent< T >::ClassType
Definition at line 238 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 238 of file G4TrackState.hh
template<class T> typedef G4TrackState<T> G4TrackStateDependent< T >::StateType
Definition at line 239 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 239 of file G4TrackState.hh
template<class T> typedef G4shared_ptr<StateType> G4TrackStateDependent< T >::StateTypeHandle
Definition at line 240 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 240 of file G4TrackState.hh
Constructor & Destructor Documentation
template<class T> virtual G4TrackStateDependent< T >::~G4TrackStateDependent () inline virtual
Definition at line 242 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 242 of file G4TrackState.hh
template<class T> G4TrackStateDependent< T >::G4TrackStateDependent () inline protected
Definition at line 301 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 301 of file G4TrackState.hh
Member Function Documentation
template<class T> virtual StateTypeHandle G4TrackStateDependent< T >::CreateTrackState () const inline virtual
Definition at line 290 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 290 of file G4TrackState.hh
template<class T> virtual StateTypeHandle G4TrackStateDependent< T >::GetConcreteTrackState () const inline virtual
Definition at line 264 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 264 of file G4TrackState.hh
template<class T> virtual G4VTrackStateHandle G4TrackStateDependent< T >::GetTrackState () const inline virtual
Implements G4VTrackStateDependent.
Definition at line 257 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 257 of file G4TrackState.hh
template<class T> virtual void G4TrackStateDependent< T >::LoadTrackState (G4TrackStateManager & manager) inline virtual
Implements G4VTrackStateDependent.
Definition at line 269 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 269 of file G4TrackState.hh
Referenced by G4ITTransportation::AlongStepGetPhysicalInteractionLength(), and G4DNABrownianTransportation::ComputeGeomLimit().
template<class T> virtual void G4TrackStateDependent< T >::NewTrackState () inline virtual
Implements G4VTrackStateDependent.
Definition at line 285 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 285 of file G4TrackState.hh
Referenced by G4TrackStateDependent< G4ITSafetyHelper >::LoadTrackState(), and G4ITTransportation::StartTracking().
template<class T> virtual G4VTrackStateHandle G4TrackStateDependent< T >::PopTrackState () inline virtual
Implements G4VTrackStateDependent.
Definition at line 249 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 249 of file G4TrackState.hh
template<class T> virtual void G4TrackStateDependent< T >::ResetTrackState () inline virtual
Implements G4VTrackStateDependent.
Definition at line 295 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 295 of file G4TrackState.hh
Referenced by G4ITTransportation::AlongStepGetPhysicalInteractionLength(), and G4DNABrownianTransportation::ComputeGeomLimit().
template<class T> virtual void G4TrackStateDependent< T >::SaveTrackState (G4TrackStateManager & manager) inline virtual
Implements G4VTrackStateDependent.
Definition at line 280 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 280 of file G4TrackState.hh
Referenced by G4TrackStateDependent< G4ITSafetyHelper >::LoadTrackState(), and G4ITTransportation::StartTracking().
template<class T> virtual void G4TrackStateDependent< T >::SetTrackState (G4shared_ptr< StateType > state) inline virtual
Definition at line 244 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 244 of file G4TrackState.hh
Member Data Documentation
template<class T> StateTypeHandle G4TrackStateDependent< T >::fpTrackState protected
Definition at line 305 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 305 of file G4TrackState.hh
Referenced by G4TrackStateDependent< G4ITSafetyHelper >::GetConcreteTrackState(), G4TrackStateDependent< G4ITSafetyHelper >::GetTrackState(), G4TrackStateDependent< G4ITSafetyHelper >::LoadTrackState(), G4TrackStateDependent< G4ITSafetyHelper >::NewTrackState(), G4TrackStateDependent< G4ITSafetyHelper >::PopTrackState(), G4TrackStateDependent< G4ITSafetyHelper >::ResetTrackState(), G4TrackStateDependent< G4ITSafetyHelper >::SaveTrackState(), and G4TrackStateDependent< G4ITSafetyHelper >::SetTrackState().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4TrackState.hh