ECCE @ EIC Software: G4ModelingParameters::VisAttributesModifier Class Reference
G4ModelingParameters::VisAttributesModifier Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelingParameters.hh>
Public Member Functions
VisAttributesModifier (const G4VisAttributes &visAtts, VisAttributesSignifier signifier, const PVNameCopyNoPath &path)
const G4VisAttributes & GetVisAttributes () const
VisAttributesSignifier GetVisAttributesSignifier () const
const PVNameCopyNoPath & GetPVNameCopyNoPath () const
void SetVisAttributes (const G4VisAttributes &visAtts)
void SetVisAttributesSignifier (VisAttributesSignifier signifier)
void SetPVNameCopyNoPath (const PVNameCopyNoPath &PVNameCopyNoPath)
G4bool operator!= (const VisAttributesModifier &) const
G4bool operator== (const VisAttributesModifier &rhs) const
Private Attributes
G4VisAttributes fVisAtts
VisAttributesSignifier fSignifier
PVNameCopyNoPath fPVNameCopyNoPath
Detailed Description
Definition at line 114 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ModelingParameters.hh
Constructor & Destructor Documentation
G4ModelingParameters::VisAttributesModifier::VisAttributesModifier (const G4VisAttributes & visAtts, VisAttributesSignifier signifier, const PVNameCopyNoPath & path) inline
Definition at line 117 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ModelingParameters.hh
Member Function Documentation
const PVNameCopyNoPath& G4ModelingParameters::VisAttributesModifier::GetPVNameCopyNoPath () const inline
Definition at line 125 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ModelingParameters.hh
References fPVNameCopyNoPath.
Referenced by G4ViewParameters::AddVisAttributesModifier().
const G4VisAttributes& G4ModelingParameters::VisAttributesModifier::GetVisAttributes () const inline
Definition at line 121 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ModelingParameters.hh
References fVisAtts.
Referenced by G4ViewParameters::AddVisAttributesModifier().
VisAttributesSignifier G4ModelingParameters::VisAttributesModifier::GetVisAttributesSignifier () const inline
Definition at line 123 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ModelingParameters.hh
References fSignifier.
Referenced by G4ViewParameters::AddVisAttributesModifier().
G4bool G4ModelingParameters::VisAttributesModifier::operator!= (const VisAttributesModifier & rhs) const
Definition at line 280 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 280 of file G4ModelingParameters.cc
References G4ModelingParameters::VASColour, G4ModelingParameters::VASDaughtersInvisible, G4ModelingParameters::VASForceAuxEdgeVisible, G4ModelingParameters::VASForceCloud, G4ModelingParameters::VASForceLineSegmentsPerCircle, G4ModelingParameters::VASForceNumberOfCloudPoints, G4ModelingParameters::VASForceSolid, G4ModelingParameters::VASForceWireframe, G4ModelingParameters::VASLineStyle, G4ModelingParameters::VASLineWidth, and G4ModelingParameters::VASVisibility.
Referenced by operator==().
G4bool G4ModelingParameters::VisAttributesModifier::operator== (const VisAttributesModifier & rhs) const inline
Definition at line 134 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ModelingParameters.hh
References operator!=().
void G4ModelingParameters::VisAttributesModifier::SetPVNameCopyNoPath (const PVNameCopyNoPath & PVNameCopyNoPath) inline
Definition at line 131 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ModelingParameters.hh
References fPVNameCopyNoPath.
void G4ModelingParameters::VisAttributesModifier::SetVisAttributes (const G4VisAttributes & visAtts) inline
Definition at line 127 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ModelingParameters.hh
References fVisAtts.
void G4ModelingParameters::VisAttributesModifier::SetVisAttributesSignifier (VisAttributesSignifier signifier) inline
Definition at line 129 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ModelingParameters.hh
References fSignifier.
Member Data Documentation
PVNameCopyNoPath G4ModelingParameters::VisAttributesModifier::fPVNameCopyNoPath private
Definition at line 139 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ModelingParameters.hh
Referenced by GetPVNameCopyNoPath(), and SetPVNameCopyNoPath().
VisAttributesSignifier G4ModelingParameters::VisAttributesModifier::fSignifier private
Definition at line 138 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ModelingParameters.hh
Referenced by GetVisAttributesSignifier(), and SetVisAttributesSignifier().
G4VisAttributes G4ModelingParameters::VisAttributesModifier::fVisAtts private
Definition at line 137 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ModelingParameters.hh
Referenced by GetVisAttributes(), and SetVisAttributes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelingParameters.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4ModelingParameters.cc