ECCE @ EIC Software: G4tgrFileReader Class Reference
G4tgrFileReader Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrFileReader.hh>
Public Member Functions
virtual ~G4tgrFileReader ()
G4bool ReadFiles ()
void AddTextFile (const G4String &fname)
void SetLineProcessor (G4tgrLineProcessor *lp)
G4tgrLineProcessor * GetLineProcessor () const
Static Public Member Functions
static G4tgrFileReader * GetInstance ()
Protected Member Functions
G4tgrFileReader ()
Private Attributes
std::vector< G4String > theTextFiles
G4tgrLineProcessor * theLineProcessor
Static Private Attributes
static G4ThreadLocal
G4tgrFileReader * theInstance = 0
Detailed Description
Definition at line 50 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 50 of file G4tgrFileReader.hh
Constructor & Destructor Documentation
G4tgrFileReader::~G4tgrFileReader () virtual
Definition at line 63 of file G4tgrFileReader.cc.
View newest version in sPHENIX GitHub at line 63 of file G4tgrFileReader.cc
References theInstance, and theLineProcessor.
G4tgrFileReader::G4tgrFileReader () protected
Definition at line 56 of file G4tgrFileReader.cc.
View newest version in sPHENIX GitHub at line 56 of file G4tgrFileReader.cc
References theLineProcessor.
Referenced by GetInstance().
Member Function Documentation
void G4tgrFileReader::AddTextFile (const G4String & fname) inline
Definition at line 61 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrFileReader.hh
References theTextFiles.
Referenced by G4tgbVolumeMgr::AddTextFile().
G4tgrFileReader * G4tgrFileReader::GetInstance (void) static
Definition at line 71 of file G4tgrFileReader.cc.
View newest version in sPHENIX GitHub at line 71 of file G4tgrFileReader.cc
References G4tgrFileReader(), and theInstance.
Referenced by G4tgbVolumeMgr::AddTextFile(), ExTGRCDetectorBuilder::ReadDetector(), and G4tgbDetectorBuilder::ReadDetector().
G4tgrLineProcessor* G4tgrFileReader::GetLineProcessor () const inline
Definition at line 63 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 63 of file G4tgrFileReader.hh
References theLineProcessor.
G4bool G4tgrFileReader::ReadFiles ()
Definition at line 80 of file G4tgrFileReader.cc.
View newest version in sPHENIX GitHub at line 80 of file G4tgrFileReader.cc
References G4tgrFileIn::DumpException(), G4tgrUtils::DumpVS(), FatalException, fin, G4cout, G4endl, G4Exception(), G4tgrFileIn::GetInstance(), G4tgrMessenger::GetVerboseLevel(), G4tgrFileIn::GetWordsInLine(), nlines, G4tgrLineProcessor::ProcessLine(), theLineProcessor, and theTextFiles.
Referenced by ExTGRCDetectorBuilder::ReadDetector(), and G4tgbDetectorBuilder::ReadDetector().
void G4tgrFileReader::SetLineProcessor (G4tgrLineProcessor * lp) inline
Definition at line 62 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 62 of file G4tgrFileReader.hh
References theLineProcessor.
Referenced by ExTGRCDetectorBuilder::ReadDetector().
Member Data Documentation
G4ThreadLocal G4tgrFileReader * G4tgrFileReader::theInstance = 0 static private
Definition at line 71 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgrFileReader.hh
Referenced by GetInstance(), and ~G4tgrFileReader().
G4tgrLineProcessor* G4tgrFileReader::theLineProcessor private
Definition at line 74 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 74 of file G4tgrFileReader.hh
Referenced by G4tgrFileReader(), GetLineProcessor(), ReadFiles(), SetLineProcessor(), and ~G4tgrFileReader().
std::vector<G4String> G4tgrFileReader::theTextFiles private
Definition at line 73 of file G4tgrFileReader.hh.
View newest version in sPHENIX GitHub at line 73 of file G4tgrFileReader.hh
Referenced by AddTextFile(), and ReadFiles().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrFileReader.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrFileReader.cc