ECCE @ EIC Software: G4INCLXXProtonBuilder Class Reference
G4INCLXXProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4INCLXXProtonBuilder.hh>
Public Member Functions
G4INCLXXProtonBuilder ()
virtual ~G4INCLXXProtonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4INCLXXInterface * theModel
G4VPreCompoundModel * thePreCompoundModel
G4double thePreCompoundMin
G4double thePreCompoundMax
G4double theMin
G4double theMax
Detailed Description
Builder for proton processes using the INCL++ intra-nuclear cascade model.
By default the INCL++ is used for projectile energies 0 - 3 GeV.
The builder uses INCL++ cascade model with G4ExcitationHandler de-excitation. This is implemented in interface G4INCLXXInterface.
See Also
G4INCLXXInterface
G4INCLXXNeutronBuilder
G4INCLXXPiKBuilder
Definition at line 54 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 54 of file G4INCLXXProtonBuilder.hh
Constructor & Destructor Documentation
G4INCLXXProtonBuilder::G4INCLXXProtonBuilder ()
Definition at line 37 of file G4INCLXXProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 37 of file G4INCLXXProtonBuilder.cc
References G4HadronicInteractionRegistry::FindModel(), GeV, G4HadronicInteractionRegistry::Instance(), MeV, theMax, theMin, theModel, thePreCompoundMax, thePreCompoundMin, and thePreCompoundModel.
virtual G4INCLXXProtonBuilder::~G4INCLXXProtonBuilder () inline virtual
Definition at line 58 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4INCLXXProtonBuilder.hh
Member Function Documentation
virtual void G4INCLXXProtonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Build elastic process.
No elastic process is built.
Implements G4VProtonBuilder.
Definition at line 65 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLXXProtonBuilder.hh
void G4INCLXXProtonBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Build inelastic process.
Implements G4VProtonBuilder.
Definition at line 51 of file G4INCLXXProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLXXProtonBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, theModel, thePreCompoundMax, thePreCompoundMin, and thePreCompoundModel.
virtual void G4INCLXXProtonBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Set the maximum energy limit for the model.
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 80 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4INCLXXProtonBuilder.hh
References theMax.
virtual void G4INCLXXProtonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Set the minimum energy limit for the model.
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 75 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLXXProtonBuilder.hh
References theMin.
Member Data Documentation
G4double G4INCLXXProtonBuilder::theMax private
Definition at line 90 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 90 of file G4INCLXXProtonBuilder.hh
Referenced by Build(), G4INCLXXProtonBuilder(), and SetMaxEnergy().
G4double G4INCLXXProtonBuilder::theMin private
Definition at line 89 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 89 of file G4INCLXXProtonBuilder.hh
Referenced by Build(), G4INCLXXProtonBuilder(), and SetMinEnergy().
G4INCLXXInterface* G4INCLXXProtonBuilder::theModel private
Definition at line 85 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4INCLXXProtonBuilder.hh
Referenced by Build(), and G4INCLXXProtonBuilder().
G4double G4INCLXXProtonBuilder::thePreCompoundMax private
Definition at line 88 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 88 of file G4INCLXXProtonBuilder.hh
Referenced by Build(), and G4INCLXXProtonBuilder().
G4double G4INCLXXProtonBuilder::thePreCompoundMin private
Definition at line 87 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4INCLXXProtonBuilder.hh
Referenced by Build(), and G4INCLXXProtonBuilder().
G4VPreCompoundModel* G4INCLXXProtonBuilder::thePreCompoundModel private
Definition at line 86 of file G4INCLXXProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4INCLXXProtonBuilder.hh
Referenced by Build(), and G4INCLXXProtonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4INCLXXProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4INCLXXProtonBuilder.cc