ECCE @ EIC Software: G4QMDMeanField Class Reference
G4QMDMeanField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDMeanField.hh>
Public Member Functions
G4QMDMeanField ()
~G4QMDMeanField ()
void SetSystem (G4QMDSystem *aSystem)
void SetNucleus (G4QMDNucleus *aSystem)
G4QMDSystem * GetSystem ()
void Cal2BodyQuantities ()
void Cal2BodyQuantities (G4int)
void CalGraduate ()
G4bool IsPauliBlocked (G4int)
G4double GetTotalPotential ()
G4double GetPotential (G4int)
void DoPropagation (G4double)
std::vector< G4QMDNucleus * > DoClusterJudgment ()
G4double GetRR2 (G4int i, G4int j)
G4double GetRHA (G4int i, G4int j)
G4double GetRHE (G4int i, G4int j)
G4ThreeVector GetFFr (G4int i)
G4ThreeVector GetFFp (G4int i)
std::vector< G4double > GetLocalDensity ()
std::vector< G4double > GetDepthOfPotential ()
void Update ()
Private Member Functions
G4double calPauliBlockingFactor (G4int)
Private Attributes
G4QMDSystem * system
G4double rclds
G4double hbc
G4double rho0
G4double epsx
G4double epscl
G4double cpc
G4int irelcr
G4double gamm
G4double c0
G4double c3
G4double cs
G4double cl
G4double wl
G4double c0w
G4double clw
G4double c0sw
G4double c0g
G4double c3g
G4double csg
G4double pag
G4double cpw
G4double cph
std::vector< std::vector
< G4double > > rr2
std::vector< std::vector
< G4double > > pp2
std::vector< std::vector
< G4double > > rbij
std::vector< std::vector
< G4double > > rha
std::vector< std::vector
< G4double > > rhe
std::vector< std::vector
< G4double > > rhc
std::vector< G4ThreeVector > ffr
std::vector< G4ThreeVector > ffp
std::vector< G4double > rh3d
Detailed Description
Definition at line 44 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 44 of file G4QMDMeanField.hh
Constructor & Destructor Documentation
G4QMDMeanField::G4QMDMeanField ()
Definition at line 43 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 43 of file G4QMDMeanField.cc
References c0, c0g, c0sw, c0w, c3, c3g, cl, clw, cpc, cph, cpw, cs, csg, gamm, G4QMDParameters::Get_c0(), G4QMDParameters::Get_c3(), G4QMDParameters::Get_cl(), G4QMDParameters::Get_cpc(), G4QMDParameters::Get_cph(), G4QMDParameters::Get_cpw(), G4QMDParameters::Get_cs(), G4QMDParameters::Get_gamm(), G4QMDParameters::Get_hbc(), G4QMDParameters::Get_rho0(), G4QMDParameters::Get_wl(), G4QMDParameters::GetInstance(), hbc, pag, Dataset::parameters, pi, rho0, system, and wl.
G4QMDMeanField::~G4QMDMeanField ()
Definition at line 82 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 82 of file G4QMDMeanField.cc
Member Function Documentation
void G4QMDMeanField::Cal2BodyQuantities ()
Definition at line 151 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 151 of file G4QMDMeanField.cc
References c0sw, c0w, clw, e, CLHEP::HepLorentzVector::e(), epscl, epsx, CLHEP::HepStat::erf(), G4Exp(), G4QMDParticipant::Get4Momentum(), G4QMDParticipant::GetBaryonNumber(), G4QMDParticipant::GetChargeInUnitOfEplus(), G4Pow::GetInstance(), G4QMDSystem::GetParticipant(), G4QMDParticipant::GetPosition(), G4QMDSystem::GetTotalNumberOfParticipant(), irelcr, CLHEP::HepLorentzVector::m2(), G4Pow::powN(), pp2, rbij, rha, rhc, rhe, rr2, system, and v.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), DoClusterJudgment(), DoPropagation(), G4QMDGroundStateNucleus::packNucleons(), and SetSystem().
void G4QMDMeanField::Cal2BodyQuantities (G4int i)
Definition at line 260 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 260 of file G4QMDMeanField.cc
References c0sw, c0w, clw, e, CLHEP::HepLorentzVector::e(), epscl, epsx, CLHEP::HepStat::erf(), G4Exp(), G4QMDParticipant::Get4Momentum(), G4QMDParticipant::GetBaryonNumber(), G4QMDParticipant::GetChargeInUnitOfEplus(), G4Pow::GetInstance(), G4QMDSystem::GetParticipant(), G4QMDParticipant::GetPosition(), G4QMDSystem::GetTotalNumberOfParticipant(), irelcr, CLHEP::HepLorentzVector::m2(), G4Pow::powN(), pp2, rbij, rha, rhc, rhe, rr2, system, and v.
void G4QMDMeanField::CalGraduate ()
Definition at line 392 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 392 of file G4QMDMeanField.cc
References kdfinder::abs(), c0g, c3g, cl, csg, CLHEP::HepLorentzVector::e(), ffp, ffr, G4QMDParticipant::Get4Momentum(), G4QMDParticipant::GetChargeInUnitOfEplus(), G4Pow::GetInstance(), G4QMDParticipant::GetNuc(), G4QMDSystem::GetParticipant(), G4QMDParticipant::GetPosition(), GetPotential(), G4QMDSystem::GetTotalNumberOfParticipant(), CLHEP::HepLorentzVector::m(), pag, G4Pow::powA(), rbij, rh3d, rha, rhc, system, v, and CLHEP::HepLorentzVector::v().
Referenced by DoPropagation(), and G4QMDGroundStateNucleus::packNucleons().
G4double G4QMDMeanField::calPauliBlockingFactor (G4int i) private
Definition at line 567 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 567 of file G4QMDMeanField.cc
References cpc, cph, cpw, epsx, G4Exp(), G4QMDParticipant::GetChargeInUnitOfEplus(), G4QMDParticipant::GetNuc(), G4QMDSystem::GetParticipant(), G4QMDSystem::GetTotalNumberOfParticipant(), pp2, rr2, and system.
Referenced by IsPauliBlocked().
std::vector< G4QMDNucleus * > G4QMDMeanField::DoClusterJudgment ()
Definition at line 699 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 699 of file G4QMDMeanField.cc
References G4Pow::A13(), G4Pow::A23(), Cal2BodyQuantities(), G4QMDParticipant::GetBaryonNumber(), G4Pow::GetInstance(), G4QMDSystem::GetParticipant(), G4QMDSystem::GetTotalNumberOfParticipant(), hbc, it, n, num, pi, pp2, rclds, rha, rr2, G4QMDSystem::SetParticipant(), G4QMDSystem::SubtractSystem(), system, and wl.
Referenced by G4QMDReaction::ApplyYourself().
void G4QMDMeanField::DoPropagation (G4double dt)
Definition at line 637 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 637 of file G4QMDMeanField.cc
References Cal2BodyQuantities(), CalGraduate(), ffp, ffr, G4QMDParticipant::GetMomentum(), G4QMDSystem::GetParticipant(), G4QMDParticipant::GetPosition(), G4QMDSystem::GetTotalNumberOfParticipant(), n, G4QMDParticipant::SetMomentum(), G4QMDParticipant::SetPosition(), and system.
Referenced by G4QMDReaction::ApplyYourself().
std::vector< G4double > G4QMDMeanField::GetDepthOfPotential ()
G4ThreeVector G4QMDMeanField::GetFFp (G4int i) inline
Definition at line 73 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDMeanField.hh
References ffp.
Referenced by G4QMDGroundStateNucleus::packNucleons().
G4ThreeVector G4QMDMeanField::GetFFr (G4int i) inline
Definition at line 72 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QMDMeanField.hh
References ffr.
Referenced by G4QMDGroundStateNucleus::packNucleons().
std::vector< G4double > G4QMDMeanField::GetLocalDensity ()
G4double G4QMDMeanField::GetPotential (G4int i)
Definition at line 490 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 490 of file G4QMDMeanField.cc
References kdfinder::abs(), c0, c3, cl, cs, gamm, G4QMDParticipant::GetChargeInUnitOfEplus(), G4Pow::GetInstance(), G4QMDParticipant::GetNuc(), G4QMDSystem::GetParticipant(), G4QMDSystem::GetTotalNumberOfParticipant(), n, G4Pow::powA(), rha, rhe, and system.
Referenced by CalGraduate().
G4double G4QMDMeanField::GetRHA (G4int i, G4int j) inline
Definition at line 70 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QMDMeanField.hh
References rha.
Referenced by G4QMDGroundStateNucleus::packNucleons().
G4double G4QMDMeanField::GetRHE (G4int i, G4int j) inline
Definition at line 71 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDMeanField.hh
References rhe.
Referenced by G4QMDGroundStateNucleus::packNucleons().
G4double G4QMDMeanField::GetRR2 (G4int i, G4int j) inline
Definition at line 68 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 68 of file G4QMDMeanField.hh
References rr2.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions(), and G4QMDGroundStateNucleus::samplingMomentum().
G4QMDSystem* G4QMDMeanField::GetSystem () inline
Definition at line 52 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 52 of file G4QMDMeanField.hh
References system.
Referenced by G4QMDCollision::SetMeanField().
G4double G4QMDMeanField::GetTotalPotential ()
Definition at line 526 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 526 of file G4QMDMeanField.cc
References kdfinder::abs(), c0, c3, cl, cs, gamm, G4QMDParticipant::GetChargeInUnitOfEplus(), G4Pow::GetInstance(), G4QMDParticipant::GetNuc(), G4QMDSystem::GetParticipant(), G4QMDSystem::GetTotalNumberOfParticipant(), n, G4Pow::powA(), rha, rhe, and system.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4QMDGroundStateNucleus::packNucleons(), and SetNucleus().
G4bool G4QMDMeanField::IsPauliBlocked (G4int i)
Definition at line 621 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 621 of file G4QMDMeanField.cc
References calPauliBlockingFactor(), G4UniformRand, G4QMDParticipant::GetNuc(), G4QMDSystem::GetParticipant(), and system.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision(), and G4QMDCollision::CalKinematicsOfBinaryCollisions().
void G4QMDMeanField::SetNucleus (G4QMDNucleus * aSystem)
Definition at line 135 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 135 of file G4QMDMeanField.cc
References G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), GetTotalPotential(), SetSystem(), and G4QMDNucleus::SetTotalPotential().
Referenced by G4QMDReaction::ApplyYourself().
void G4QMDMeanField::SetSystem (G4QMDSystem * aSystem)
Definition at line 89 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 89 of file G4QMDMeanField.cc
References Cal2BodyQuantities(), ffp, ffr, G4QMDSystem::GetTotalNumberOfParticipant(), n, pp2, rbij, rh3d, rha, rhc, rhe, rr2, and system.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDGroundStateNucleus::G4QMDGroundStateNucleus(), SetNucleus(), and Update().
void G4QMDMeanField::Update ()
Definition at line 966 of file G4QMDMeanField.cc.
View newest version in sPHENIX GitHub at line 966 of file G4QMDMeanField.cc
References SetSystem(), and system.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision(), and G4QMDCollision::CalKinematicsOfBinaryCollisions().
Member Data Documentation
G4double G4QMDMeanField::c0 private
Definition at line 94 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDMeanField.hh
Referenced by G4QMDMeanField(), GetPotential(), and GetTotalPotential().
G4double G4QMDMeanField::c0g private
Definition at line 98 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 98 of file G4QMDMeanField.hh
Referenced by CalGraduate(), and G4QMDMeanField().
G4double G4QMDMeanField::c0sw private
Definition at line 96 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 96 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), and G4QMDMeanField().
G4double G4QMDMeanField::c0w private
Definition at line 96 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 96 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), and G4QMDMeanField().
G4double G4QMDMeanField::c3 private
Definition at line 94 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDMeanField.hh
Referenced by G4QMDMeanField(), GetPotential(), and GetTotalPotential().
G4double G4QMDMeanField::c3g private
Definition at line 98 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 98 of file G4QMDMeanField.hh
Referenced by CalGraduate(), and G4QMDMeanField().
G4double G4QMDMeanField::cl private
Definition at line 94 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDMeanField.hh
Referenced by CalGraduate(), G4QMDMeanField(), GetPotential(), and GetTotalPotential().
G4double G4QMDMeanField::clw private
Definition at line 96 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 96 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), and G4QMDMeanField().
G4double G4QMDMeanField::cpc private
Definition at line 90 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QMDMeanField.hh
Referenced by calPauliBlockingFactor(), and G4QMDMeanField().
G4double G4QMDMeanField::cph private
Definition at line 100 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 100 of file G4QMDMeanField.hh
Referenced by calPauliBlockingFactor(), and G4QMDMeanField().
G4double G4QMDMeanField::cpw private
Definition at line 100 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 100 of file G4QMDMeanField.hh
Referenced by calPauliBlockingFactor(), and G4QMDMeanField().
G4double G4QMDMeanField::cs private
Definition at line 94 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDMeanField.hh
Referenced by G4QMDMeanField(), GetPotential(), and GetTotalPotential().
G4double G4QMDMeanField::csg private
Definition at line 98 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 98 of file G4QMDMeanField.hh
Referenced by CalGraduate(), and G4QMDMeanField().
G4double G4QMDMeanField::epscl private
Definition at line 88 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 88 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities().
G4double G4QMDMeanField::epsx private
Definition at line 88 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 88 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), and calPauliBlockingFactor().
std::vector< G4ThreeVector > G4QMDMeanField::ffp private
Definition at line 115 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 115 of file G4QMDMeanField.hh
Referenced by CalGraduate(), DoPropagation(), GetFFp(), and SetSystem().
std::vector< G4ThreeVector > G4QMDMeanField::ffr private
Definition at line 114 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 114 of file G4QMDMeanField.hh
Referenced by CalGraduate(), DoPropagation(), GetFFr(), and SetSystem().
G4double G4QMDMeanField::gamm private
Definition at line 94 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDMeanField.hh
Referenced by G4QMDMeanField(), GetPotential(), and GetTotalPotential().
G4double G4QMDMeanField::hbc private
Definition at line 87 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 87 of file G4QMDMeanField.hh
Referenced by DoClusterJudgment(), and G4QMDMeanField().
G4int G4QMDMeanField::irelcr private
Definition at line 93 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 93 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities().
G4double G4QMDMeanField::pag private
Definition at line 98 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 98 of file G4QMDMeanField.hh
Referenced by CalGraduate(), and G4QMDMeanField().
std::vector< std::vector < G4double > > G4QMDMeanField::pp2 private
Definition at line 104 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 104 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), calPauliBlockingFactor(), DoClusterJudgment(), and SetSystem().
std::vector< std::vector < G4double > > G4QMDMeanField::rbij private
Definition at line 105 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 105 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), CalGraduate(), and SetSystem().
G4double G4QMDMeanField::rclds private
Definition at line 85 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 85 of file G4QMDMeanField.hh
Referenced by DoClusterJudgment().
std::vector< G4double > G4QMDMeanField::rh3d private
Definition at line 116 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 116 of file G4QMDMeanField.hh
Referenced by CalGraduate(), and SetSystem().
std::vector< std::vector < G4double > > G4QMDMeanField::rha private
Definition at line 108 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 108 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), CalGraduate(), DoClusterJudgment(), GetPotential(), GetRHA(), GetTotalPotential(), and SetSystem().
std::vector< std::vector < G4double > > G4QMDMeanField::rhc private
Definition at line 112 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 112 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), CalGraduate(), and SetSystem().
std::vector< std::vector < G4double > > G4QMDMeanField::rhe private
Definition at line 111 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 111 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), GetPotential(), GetRHE(), GetTotalPotential(), and SetSystem().
G4double G4QMDMeanField::rho0 private
Definition at line 87 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 87 of file G4QMDMeanField.hh
Referenced by G4QMDMeanField().
std::vector< std::vector < G4double > > G4QMDMeanField::rr2 private
Definition at line 103 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 103 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), calPauliBlockingFactor(), DoClusterJudgment(), GetRR2(), and SetSystem().
G4QMDSystem* G4QMDMeanField::system private
Definition at line 83 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDMeanField.hh
Referenced by Cal2BodyQuantities(), CalGraduate(), calPauliBlockingFactor(), DoClusterJudgment(), DoPropagation(), G4QMDMeanField(), GetPotential(), GetSystem(), GetTotalPotential(), IsPauliBlocked(), SetSystem(), and Update().
G4double G4QMDMeanField::wl private
Definition at line 94 of file G4QMDMeanField.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QMDMeanField.hh
Referenced by DoClusterJudgment(), and G4QMDMeanField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDMeanField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDMeanField.cc