ECCE @ EIC Software: G4RadioactivationMessenger Class Reference
G4RadioactivationMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactivationMessenger.hh>
Public Member Functions
G4RadioactivationMessenger (G4Radioactivation *theRadioactivationContainer)
~G4RadioactivationMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4Radioactivation * theRadioactivationContainer
G4UIdirectory * grdmDirectory
G4UIcmdWithABool * analoguemcCmd
G4UIcmdWithAString * sourcetimeprofileCmd
G4UIcmdWithAString * decaybiasprofileCmd
G4UIcmdWithABool * brbiasCmd
G4UIcmdWithAnInteger * splitnucleiCmd
G4UIcmdWithADoubleAndUnit * hlthCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 53 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RadioactivationMessenger.hh
Constructor & Destructor Documentation
G4RadioactivationMessenger::G4RadioactivationMessenger (G4Radioactivation * theRadioactivationContainer)
Definition at line 41 of file G4RadioactivationMessenger.cc.
View newest version in sPHENIX GitHub at line 41 of file G4RadioactivationMessenger.cc
References analoguemcCmd, brbiasCmd, decaybiasprofileCmd, grdmDirectory, hlthCmd, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), sourcetimeprofileCmd, and splitnucleiCmd.
G4RadioactivationMessenger::~G4RadioactivationMessenger ()
Definition at line 88 of file G4RadioactivationMessenger.cc.
View newest version in sPHENIX GitHub at line 88 of file G4RadioactivationMessenger.cc
References analoguemcCmd, brbiasCmd, decaybiasprofileCmd, grdmDirectory, hlthCmd, sourcetimeprofileCmd, and splitnucleiCmd.
Member Function Documentation
void G4RadioactivationMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 100 of file G4RadioactivationMessenger.cc.
View newest version in sPHENIX GitHub at line 100 of file G4RadioactivationMessenger.cc
References analoguemcCmd, brbiasCmd, decaybiasprofileCmd, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), hlthCmd, sourcetimeprofileCmd, splitnucleiCmd, and theRadioactivationContainer.
Member Data Documentation
G4UIcmdWithABool* G4RadioactivationMessenger::analoguemcCmd private
Definition at line 65 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), SetNewValue(), and ~G4RadioactivationMessenger().
G4UIcmdWithABool* G4RadioactivationMessenger::brbiasCmd private
Definition at line 68 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), SetNewValue(), and ~G4RadioactivationMessenger().
G4UIcmdWithAString* G4RadioactivationMessenger::decaybiasprofileCmd private
Definition at line 67 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), SetNewValue(), and ~G4RadioactivationMessenger().
G4UIdirectory* G4RadioactivationMessenger::grdmDirectory private
Definition at line 64 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), and ~G4RadioactivationMessenger().
G4UIcmdWithADoubleAndUnit* G4RadioactivationMessenger::hlthCmd private
Definition at line 70 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), SetNewValue(), and ~G4RadioactivationMessenger().
G4UIcmdWithAString* G4RadioactivationMessenger::sourcetimeprofileCmd private
Definition at line 66 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), SetNewValue(), and ~G4RadioactivationMessenger().
G4UIcmdWithAnInteger* G4RadioactivationMessenger::splitnucleiCmd private
Definition at line 69 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RadioactivationMessenger.hh
Referenced by G4RadioactivationMessenger(), SetNewValue(), and ~G4RadioactivationMessenger().
G4Radioactivation* G4RadioactivationMessenger::theRadioactivationContainer private
Definition at line 62 of file G4RadioactivationMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RadioactivationMessenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4RadioactivationMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4RadioactivationMessenger.cc