ECCE @ EIC Software: LXePMTSD Class Reference
LXePMTSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXePMTSD.hh>
Public Member Functions
LXePMTSD (G4String name)
virtual ~LXePMTSD ()
virtual void Initialize (G4HCofThisEvent *)
virtual G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *)
G4bool ProcessHits_constStep (const G4Step *, G4TouchableHistory *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
void DrawAll ()
void PrintAll ()
void InitPMTs ()
void SetPmtPositions (const std::vector< G4ThreeVector > &positions)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
LXePMTHitsCollection * fPMTHitCollection
G4DataVector * fPMTPositionsX
G4DataVector * fPMTPositionsY
G4DataVector * fPMTPositionsZ
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 43 of file LXePMTSD.hh.
View newest version in sPHENIX GitHub at line 43 of file LXePMTSD.hh
Constructor & Destructor Documentation
LXePMTSD::LXePMTSD (G4String name)
Definition at line 48 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 48 of file LXePMTSD.cc
References G4VSensitiveDetector::collectionName, and G4CollectionNameVector::insert().
LXePMTSD::~LXePMTSD () virtual
Definition at line 57 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 57 of file LXePMTSD.cc
Member Function Documentation
void LXePMTSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 151 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 151 of file LXePMTSD.cc
void LXePMTSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 155 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 155 of file LXePMTSD.cc
void LXePMTSD::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 147 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 147 of file LXePMTSD.cc
void LXePMTSD::Initialize (G4HCofThisEvent * hitsCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 72 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 72 of file LXePMTSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, fPMTHitCollection, G4VSensitiveDetector::GetCollectionID(), and G4VSensitiveDetector::SensitiveDetectorName.
void LXePMTSD::InitPMTs () inline
Definition at line 63 of file LXePMTSD.hh.
View newest version in sPHENIX GitHub at line 63 of file LXePMTSD.hh
References fPMTPositionsX, fPMTPositionsY, and fPMTPositionsZ.
Referenced by LXeDetectorConstruction::ConstructSDandField().
void LXePMTSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 159 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 159 of file LXePMTSD.cc
G4bool LXePMTSD::ProcessHits (G4Step * aStep, G4TouchableHistory *) virtual
Implements G4VSensitiveDetector.
Definition at line 85 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 85 of file LXePMTSD.cc
G4bool LXePMTSD::ProcessHits_constStep (const G4Step * aStep, G4TouchableHistory *)
Definition at line 95 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 95 of file LXePMTSD.cc
References G4THitsCollection< T >::entries(), fPMTHitCollection, fPMTPositionsX, fPMTPositionsY, fPMTPositionsZ, G4Track::GetDefinition(), G4Step::GetPostStepPoint(), G4VTouchable::GetReplicaNumber(), LXeDetectorConstruction::GetSphereOn(), G4StepPoint::GetTouchable(), G4Step::GetTrack(), LXeUserTrackInformation::GetTrackStatus(), G4Track::GetUserInformation(), G4VTouchable::GetVolume(), hitSphere, LXePMTHit::IncPhotonCount(), G4THitsCollection< T >::insert(), n, G4OpticalPhoton::OpticalPhotonDefinition(), LXePMTHit::SetDrawit(), LXePMTHit::SetPMTNumber(), LXePMTHit::SetPMTPhysVol(), and LXePMTHit::SetPMTPos().
Referenced by LXeSteppingAction::UserSteppingAction().
void LXePMTSD::SetPmtPositions (const std::vector< G4ThreeVector > & positions)
Definition at line 61 of file LXePMTSD.cc.
View newest version in sPHENIX GitHub at line 61 of file LXePMTSD.cc
References fPMTPositionsX, fPMTPositionsY, fPMTPositionsZ, x, y, and z.
Referenced by LXeDetectorConstruction::ConstructSDandField().
Member Data Documentation
LXePMTHitsCollection* LXePMTSD::fPMTHitCollection private
Definition at line 77 of file LXePMTSD.hh.
View newest version in sPHENIX GitHub at line 77 of file LXePMTSD.hh
Referenced by Initialize(), and ProcessHits_constStep().
G4DataVector* LXePMTSD::fPMTPositionsX private
Definition at line 79 of file LXePMTSD.hh.
View newest version in sPHENIX GitHub at line 79 of file LXePMTSD.hh
Referenced by InitPMTs(), ProcessHits_constStep(), and SetPmtPositions().
G4DataVector* LXePMTSD::fPMTPositionsY private
Definition at line 80 of file LXePMTSD.hh.
View newest version in sPHENIX GitHub at line 80 of file LXePMTSD.hh
Referenced by InitPMTs(), ProcessHits_constStep(), and SetPmtPositions().
G4DataVector* LXePMTSD::fPMTPositionsZ private
Definition at line 81 of file LXePMTSD.hh.
View newest version in sPHENIX GitHub at line 81 of file LXePMTSD.hh
Referenced by InitPMTs(), ProcessHits_constStep(), and SetPmtPositions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXePMTSD.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXePMTSD.cc