ECCE @ EIC Software: demo Namespace Reference
demo Namespace Reference
Classes
class App
class MyPrimaryGeneratorAction
class MyRunAction
class MyEventAction
class MySteppingAction
class ScoreSD
Functions
def init_root
def hini
def hshow
def posXZ
def Configure
def ConstructGeom
Variables
tuple myDC testem0.DetectorConstruction()
tuple myPL testem0.PhysicsList()
tuple myPGA testem0.PrimaryGeneratorAction(myDC)
tuple myRA testem0.RunAction(myDC,myPGA)
tuple pg g4.G4ParticleGun()
tuple materialList testem0.getMaterialTable()
tuple particleList testem0.getParticleTable()
list enrgyList ["eV","keV","MeV","GeV","TeV","PeV"]
list cutsList ["um", "mm" , "cm", "m", "km"]
tuple app App()
tuple rand_engine Ranlux64Engine()
tuple exN03geom g4py.ExN03geom.ExN03DetectorConstruction()
tuple exN03PL g4py.EMSTDpl.PhysicsListEMstd()
tuple heprepViewer os.environ.get("G4HEPREPFILE_VIEWER")
tuple heprepDir os.environ.get("G4HEPREPFILE_DIR")
tuple heprepName os.environ.get("G4HEPREPFILE_NAME")
tuple vrmlDir os.environ.get("G4VRML_DEST_DIR")
tuple vrmlViewer os.environ.get("G4VRMLFILE_VIEWER")
Function Documentation
def demo.Configure ()
Definition at line 20 of file demo.py.
View newest version in sPHENIX GitHub at line 20 of file demo.py
References source.gControlExecute.
Referenced by G4BiasingProcessInterface.BuildPhysicsTable().
def demo.ConstructGeom ()
Definition at line 47 of file demo.py.
View newest version in sPHENIX GitHub at line 47 of file demo.py
References G4Material.GetMaterial().
def demo.hini ()
Definition at line 35 of file demo.py.
View newest version in sPHENIX GitHub at line 35 of file demo.py
Referenced by posXZ().
def demo.hshow ()
Definition at line 66 of file demo.py.
View newest version in sPHENIX GitHub at line 66 of file demo.py
def demo.init_root ()
Definition at line 18 of file demo.py.
View newest version in sPHENIX GitHub at line 18 of file demo.py
Referenced by posXZ().
def demo.posXZ (copyN)
Definition at line 140 of file demo.py.
View newest version in sPHENIX GitHub at line 140 of file demo.py
References source.gApplyUICommand, hini(), and init_root().
Referenced by demo.ScoreSD.ProcessHits().
Variable Documentation
tuple demo.app App()
Definition at line 189 of file demo.py.
View newest version in sPHENIX GitHub at line 189 of file demo.py
Referenced by G4MTcoutDestination.HandleFileCerr(), G4MTcoutDestination.HandleFileCout(), G4PenelopeRayleighModel.InitializeSamplingAlgorithm(), CLHEP::RandGauss.saveEngineStatus(), CLHEP::RandFlat.saveEngineStatus(), CML2ExpVoxels.saveResults(), HadrontherapySteppingAction.UserSteppingAction(), and EventAction.WriteFibers().
list demo.cutsList ["um", "mm" , "cm", "m", "km"]
Definition at line 45 of file demo.py.
View newest version in sPHENIX GitHub at line 45 of file demo.py
list demo.enrgyList ["eV","keV","MeV","GeV","TeV","PeV"]
Definition at line 43 of file demo.py.
View newest version in sPHENIX GitHub at line 43 of file demo.py
tuple demo.exN03geom g4py.ExN03geom.ExN03DetectorConstruction()
Definition at line 41 of file demo.py.
View newest version in sPHENIX GitHub at line 41 of file demo.py
tuple demo.exN03PL g4py.EMSTDpl.PhysicsListEMstd()
Definition at line 56 of file demo.py.
View newest version in sPHENIX GitHub at line 56 of file demo.py
tuple demo.heprepDir os.environ.get("G4HEPREPFILE_DIR")
Definition at line 121 of file demo.py.
View newest version in sPHENIX GitHub at line 121 of file demo.py
tuple demo.heprepName os.environ.get("G4HEPREPFILE_NAME")
Definition at line 122 of file demo.py.
View newest version in sPHENIX GitHub at line 122 of file demo.py
tuple demo.heprepViewer os.environ.get("G4HEPREPFILE_VIEWER")
Definition at line 120 of file demo.py.
View newest version in sPHENIX GitHub at line 120 of file demo.py
tuple demo.materialList testem0.getMaterialTable()
Definition at line 39 of file demo.py.
View newest version in sPHENIX GitHub at line 39 of file demo.py
Referenced by getMaterialTable().
tuple demo.myDC testem0.DetectorConstruction()
Definition at line 18 of file demo.py.
View newest version in sPHENIX GitHub at line 18 of file demo.py
tuple demo.myPGA testem0.PrimaryGeneratorAction(myDC)
Definition at line 25 of file demo.py.
View newest version in sPHENIX GitHub at line 25 of file demo.py
tuple demo.myPL testem0.PhysicsList()
Definition at line 21 of file demo.py.
View newest version in sPHENIX GitHub at line 21 of file demo.py
tuple demo.myRA testem0.RunAction(myDC,myPGA)
Definition at line 28 of file demo.py.
View newest version in sPHENIX GitHub at line 28 of file demo.py
tuple demo.particleList testem0.getParticleTable()
Definition at line 41 of file demo.py.
View newest version in sPHENIX GitHub at line 41 of file demo.py
tuple demo.pg g4.G4ParticleGun()
Definition at line 37 of file demo.py.
View newest version in sPHENIX GitHub at line 37 of file demo.py
Referenced by G4ParticleHPPartial.InitData(), and G4hhElastic.SetRB().
tuple demo.rand_engine Ranlux64Engine()
Definition at line 78 of file demo.py.
View newest version in sPHENIX GitHub at line 78 of file demo.py
tuple demo.vrmlDir os.environ.get("G4VRML_DEST_DIR")
Definition at line 128 of file demo.py.
View newest version in sPHENIX GitHub at line 128 of file demo.py
tuple demo.vrmlViewer os.environ.get("G4VRMLFILE_VIEWER")
Definition at line 129 of file demo.py.
View newest version in sPHENIX GitHub at line 129 of file demo.py