ECCE @ EIC Software: G4PhysicsListWorkspace Class Reference
G4PhysicsListWorkspace Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4PhysicsListWorkspace.hh>
Public Types
typedef G4TWorkspacePool
< G4PhysicsListWorkspace > pool_type
Public Member Functions
G4PhysicsListWorkspace (G4bool verbose=false)
~G4PhysicsListWorkspace ()
void UseWorkspace ()
void ReleaseWorkspace ()
void DestroyWorkspace ()
void InitialiseWorkspace ()
void SetVerbose (G4bool v)
G4bool GetVerbose ()
Static Public Member Functions
static pool_type * GetPool ()
Protected Member Functions
void InitialisePhysicsList ()
Private Attributes
G4VUPLManager * fpVUPLSIM
G4VPCManager * fpVPCSIM
G4VMPLManager * fpVMPLSIM
G4VUPLData * fpVUPLOffset
G4VPCData * fpVPCOffset
G4VMPLData * fpVMPLOffset
G4bool fVerbose
Detailed Description
Definition at line 56 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 56 of file G4PhysicsListWorkspace.hh
Member Typedef Documentation
typedef G4TWorkspacePool<G4PhysicsListWorkspace> G4PhysicsListWorkspace::pool_type
Definition at line 59 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PhysicsListWorkspace.hh
Constructor & Destructor Documentation
G4PhysicsListWorkspace::G4PhysicsListWorkspace (G4bool verbose = false)
Definition at line 36 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 36 of file G4PhysicsListWorkspace.cc
References fpVMPLOffset, fpVMPLSIM, fpVPCOffset, fpVPCSIM, fpVUPLOffset, fpVUPLSIM, G4VUPLSplitter< T >::GetOffset(), G4VModularPhysicsList::GetSubInstanceManager(), G4VPhysicsConstructor::GetSubInstanceManager(), G4VUserPhysicsList::GetSubInstanceManager(), and InitialiseWorkspace().
G4PhysicsListWorkspace::~G4PhysicsListWorkspace ()
Definition at line 56 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PhysicsListWorkspace.cc
Member Function Documentation
void G4PhysicsListWorkspace::DestroyWorkspace ()
Definition at line 112 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 112 of file G4PhysicsListWorkspace.cc
References fpVMPLSIM, fpVPCSIM, fpVUPLSIM, and G4VUPLSplitter< T >::FreeWorker().
G4PhysicsListWorkspace::pool_type * G4PhysicsListWorkspace::GetPool () static
Definition at line 34 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 34 of file G4PhysicsListWorkspace.cc
Referenced by G4WorkerThread::BuildGeometryAndPhysicsVector(), and G4WorkerThread::DestroyGeometryAndPhysicsVector().
G4bool G4PhysicsListWorkspace::GetVerbose () inline
Definition at line 71 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PhysicsListWorkspace.hh
References fVerbose.
void G4PhysicsListWorkspace::InitialisePhysicsList () protected
Definition at line 84 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 84 of file G4PhysicsListWorkspace.cc
Referenced by InitialiseWorkspace().
void G4PhysicsListWorkspace::InitialiseWorkspace ()
Definition at line 89 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 89 of file G4PhysicsListWorkspace.cc
References fpVMPLSIM, fpVPCSIM, fpVUPLSIM, fVerbose, G4cout, G4endl, InitialisePhysicsList(), G4VUPLSplitter< T >::NewSubInstances(), and G4VUPLSplitter< T >::WorkerCopySubInstanceArray().
Referenced by G4PhysicsListWorkspace().
void G4PhysicsListWorkspace::ReleaseWorkspace ()
Definition at line 77 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PhysicsListWorkspace.cc
References fpVMPLSIM, fpVPCSIM, fpVUPLSIM, and G4VUPLSplitter< T >::UseWorkArea().
void G4PhysicsListWorkspace::SetVerbose (G4bool v) inline
Definition at line 70 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PhysicsListWorkspace.hh
References fVerbose, and v.
void G4PhysicsListWorkspace::UseWorkspace ()
Definition at line 61 of file G4PhysicsListWorkspace.cc.
View newest version in sPHENIX GitHub at line 61 of file G4PhysicsListWorkspace.cc
References fpVMPLOffset, fpVMPLSIM, fpVPCOffset, fpVPCSIM, fpVUPLOffset, fpVUPLSIM, fVerbose, G4cout, G4endl, and G4VUPLSplitter< T >::UseWorkArea().
Member Data Documentation
G4VMPLData* G4PhysicsListWorkspace::fpVMPLOffset private
Definition at line 88 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PhysicsListWorkspace.hh
Referenced by G4PhysicsListWorkspace(), and UseWorkspace().
G4VMPLManager* G4PhysicsListWorkspace::fpVMPLSIM private
Definition at line 80 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 80 of file G4PhysicsListWorkspace.hh
Referenced by DestroyWorkspace(), G4PhysicsListWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4VPCData* G4PhysicsListWorkspace::fpVPCOffset private
Definition at line 87 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 87 of file G4PhysicsListWorkspace.hh
Referenced by G4PhysicsListWorkspace(), and UseWorkspace().
G4VPCManager* G4PhysicsListWorkspace::fpVPCSIM private
Definition at line 79 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 79 of file G4PhysicsListWorkspace.hh
Referenced by DestroyWorkspace(), G4PhysicsListWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4VUPLData* G4PhysicsListWorkspace::fpVUPLOffset private
Definition at line 86 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PhysicsListWorkspace.hh
Referenced by G4PhysicsListWorkspace(), and UseWorkspace().
G4VUPLManager* G4PhysicsListWorkspace::fpVUPLSIM private
Definition at line 78 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PhysicsListWorkspace.hh
Referenced by DestroyWorkspace(), G4PhysicsListWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4bool G4PhysicsListWorkspace::fVerbose private
Definition at line 90 of file G4PhysicsListWorkspace.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PhysicsListWorkspace.hh
Referenced by GetVerbose(), InitialiseWorkspace(), SetVerbose(), and UseWorkspace().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4PhysicsListWorkspace.hh
geant4/tree/geant4-10.6-release/source/run/src/G4PhysicsListWorkspace.cc