ECCE @ EIC Software: G4IInterpolator Class Reference
G4IInterpolator Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4IInterpolator.hh>
Public Member Functions
G4IInterpolator ()
virtual ~G4IInterpolator ()
virtual G4double Calculate (G4double point, G4int bin, const G4DataVector &energies, const G4DataVector &data) const =0
virtual G4IInterpolator * Clone () const =0
Private Member Functions
G4IInterpolator (const G4IInterpolator &)
G4IInterpolator & operator= (const G4IInterpolator &right)
Detailed Description
Definition at line 47 of file G4IInterpolator.hh.
View newest version in sPHENIX GitHub at line 47 of file G4IInterpolator.hh
Constructor & Destructor Documentation
G4IInterpolator::G4IInterpolator () inline
Definition at line 51 of file G4IInterpolator.hh.
View newest version in sPHENIX GitHub at line 51 of file G4IInterpolator.hh
virtual G4IInterpolator::~G4IInterpolator () inline virtual
Definition at line 53 of file G4IInterpolator.hh.
View newest version in sPHENIX GitHub at line 53 of file G4IInterpolator.hh
G4IInterpolator::G4IInterpolator (const G4IInterpolator &) private
Member Function Documentation
virtual G4double G4IInterpolator::Calculate (G4double point, G4int bin, const G4DataVector & energies, const G4DataVector & data) const pure virtual
Implemented in G4LinInterpolator, and G4LogLogInterpolator.
Referenced by G4DataSet::FindValue(), G4DataSet::IntegrationFunction(), and G4DataSet::RandomSelect().
virtual G4IInterpolator* G4IInterpolator::Clone () const pure virtual
Implemented in G4LinInterpolator, and G4LogLogInterpolator.
Referenced by G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4CompositeDataSet::LoadData(), and G4PixeCrossSectionHandler::LoadShellData().
G4IInterpolator& G4IInterpolator::operator= (const G4IInterpolator & right) private
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4IInterpolator.hh