ECCE @ EIC Software: G4VRangeToEnergyConverter Class Reference
G4VRangeToEnergyConverter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4VRangeToEnergyConverter.hh>
Public Member Functions
G4VRangeToEnergyConverter ()
G4VRangeToEnergyConverter (const G4VRangeToEnergyConverter &right)
G4VRangeToEnergyConverter & operator= (const G4VRangeToEnergyConverter &right)
virtual ~G4VRangeToEnergyConverter ()
G4bool operator== (const G4VRangeToEnergyConverter &right) const
G4bool operator!= (const G4VRangeToEnergyConverter &right) const
virtual G4double Convert (G4double rangeCut, const G4Material *material)
const G4ParticleDefinition * GetParticleType () const
const G4PhysicsTable * GetLossTable () const
virtual void Reset ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Static Public Member Functions
static void SetEnergyRange (G4double lowedge, G4double highedge)
static G4double GetLowEdgeEnergy ()
static G4double GetHighEdgeEnergy ()
static G4double GetMaxEnergyCut ()
static void SetMaxEnergyCut (G4double value)
Protected Types
typedef G4PhysicsTable G4LossTable
typedef G4PhysicsLogVector G4LossVector
typedef G4PhysicsLogVector G4RangeVector
Protected Member Functions
virtual void BuildLossTable ()
virtual G4double ComputeLoss (G4double AtomicNumber, G4double KineticEnergy)=0
virtual void BuildRangeVector (const G4Material *aMaterial, G4RangeVector *rangeVector)
G4double ConvertCutToKineticEnergy (G4RangeVector *theRangeVector, G4double theCutInLength, size_t materialIndex) const
Protected Attributes
G4double fMaxEnergyCut
const G4ParticleDefinition * theParticle
G4LossTable * theLossTable
G4int NumberOfElements
const G4int TotBin
std::vector< G4RangeVector * > fRangeVectorStore
Static Protected Attributes
static G4double LowestEnergy = 0.99e-3*MeV
static G4double HighestEnergy = 100.0e6*MeV
static G4double MaxEnergyCut = 10.0*GeV
Private Attributes
G4int verboseLevel
Detailed Description
Definition at line 57 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VRangeToEnergyConverter.hh
Member Typedef Documentation
typedef G4PhysicsTable G4VRangeToEnergyConverter::G4LossTable protected
Definition at line 114 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VRangeToEnergyConverter.hh
typedef G4PhysicsLogVector G4VRangeToEnergyConverter::G4LossVector protected
Definition at line 118 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VRangeToEnergyConverter.hh
typedef G4PhysicsLogVector G4VRangeToEnergyConverter::G4RangeVector protected
Definition at line 130 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 130 of file G4VRangeToEnergyConverter.hh
Constructor & Destructor Documentation
G4VRangeToEnergyConverter::G4VRangeToEnergyConverter ()
Definition at line 47 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VRangeToEnergyConverter.cc
References fMaxEnergyCut.
G4VRangeToEnergyConverter::G4VRangeToEnergyConverter (const G4VRangeToEnergyConverter & right)
Definition at line 54 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 54 of file G4VRangeToEnergyConverter.cc
References G4PhysicsTable::clearAndDestroy(), fMaxEnergyCut, right, and theLossTable.
G4VRangeToEnergyConverter::~G4VRangeToEnergyConverter () virtual
Definition at line 116 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 116 of file G4VRangeToEnergyConverter.cc
References Reset().
Member Function Documentation
void G4VRangeToEnergyConverter::BuildLossTable () protected virtual
Definition at line 292 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 292 of file G4VRangeToEnergyConverter.cc
References ComputeLoss(), G4PhysicsVector::Energy(), G4cout, G4endl, G4Element::GetElementTable(), G4Element::GetNumberOfElements(), GetVerboseLevel(), G4PhysicsTable::insert(), LowestEnergy, MaxEnergyCut, NumberOfElements, G4PhysicsVector::PutValue(), Reset(), theLossTable, and TotBin.
Referenced by Convert().
void G4VRangeToEnergyConverter::BuildRangeVector (const G4Material * aMaterial, G4RangeVector * rangeVector) protected virtual
Reimplemented in G4RToEConvForGamma.
Definition at line 330 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 330 of file G4VRangeToEnergyConverter.cc
References G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4PhysicsVector::GetLowEdgeEnergy(), G4Material::GetNumberOfElements(), LowestEnergy, MaxEnergyCut, G4PhysicsVector::PutValue(), G4InuclParticleNames::s0, t, and TotBin.
Referenced by Convert().
virtual G4double G4VRangeToEnergyConverter::ComputeLoss (G4double AtomicNumber, G4double KineticEnergy) protected pure virtual
Implemented in G4RToEConvForProton, G4RToEConvForGamma, G4RToEConvForElectron, and G4RToEConvForPositron.
Referenced by BuildLossTable().
G4double G4VRangeToEnergyConverter::Convert (G4double rangeCut, const G4Material * material) virtual
Reimplemented in G4RToEConvForProton.
Definition at line 147 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 147 of file G4VRangeToEnergyConverter.cc
References BuildLossTable(), BuildRangeVector(), cm3, ConvertCutToKineticEnergy(), fMaxEnergyCut, fRangeVectorStore, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetIndex(), G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), incremental_prev_tag::idx, keV, LowestEnergy, MaxEnergyCut, mm, Reset(), theParticle, and TotBin.
Referenced by G4ProductionCutsTable::ConvertRangeToEnergy(), and G4ProductionCutsTable::UpdateCoupleTable().
G4double G4VRangeToEnergyConverter::ConvertCutToKineticEnergy (G4RangeVector * theRangeVector, G4double theCutInLength, size_t materialIndex) const protected
Definition at line 378 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 378 of file G4VRangeToEnergyConverter.cc
References epsilon(), G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetParticleName(), GetVerboseLevel(), LowestEnergy, MaxEnergyCut, mm, r, r1, rmax(), T, T1, T2, T3, theParticle, TotBin, and G4PhysicsVector::Value().
Referenced by Convert().
G4double G4VRangeToEnergyConverter::GetHighEdgeEnergy () static
Definition at line 248 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 248 of file G4VRangeToEnergyConverter.cc
References HighestEnergy.
Referenced by G4ProductionCutsTable::GetHighEdgeEnergy().
const G4PhysicsTable* G4VRangeToEnergyConverter::GetLossTable () const
G4double G4VRangeToEnergyConverter::GetLowEdgeEnergy () static
Definition at line 242 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 242 of file G4VRangeToEnergyConverter.cc
References LowestEnergy.
Referenced by G4ProductionCutsTable::GetLowEdgeEnergy().
G4double G4VRangeToEnergyConverter::GetMaxEnergyCut () static
Definition at line 256 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 256 of file G4VRangeToEnergyConverter.cc
References MaxEnergyCut.
Referenced by G4ProductionCutsTable::GetMaxEnergyCut().
const G4ParticleDefinition * G4VRangeToEnergyConverter::GetParticleType () const inline
Definition at line 171 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 171 of file G4VRangeToEnergyConverter.hh
References theParticle.
G4int G4VRangeToEnergyConverter::GetVerboseLevel () const inline
Definition at line 164 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 164 of file G4VRangeToEnergyConverter.hh
References verboseLevel.
Referenced by BuildLossTable(), Convert(), ConvertCutToKineticEnergy(), G4RToEConvForElectron::G4RToEConvForElectron(), G4RToEConvForGamma::G4RToEConvForGamma(), G4RToEConvForPositron::G4RToEConvForPositron(), and G4RToEConvForProton::G4RToEConvForProton().
G4bool G4VRangeToEnergyConverter::operator!= (const G4VRangeToEnergyConverter & right) const
Definition at line 138 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 138 of file G4VRangeToEnergyConverter.cc
References right.
G4VRangeToEnergyConverter & G4VRangeToEnergyConverter::operator= (const G4VRangeToEnergyConverter & right)
Definition at line 65 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VRangeToEnergyConverter.cc
References Acts::Test::at, G4PhysicsTable::clearAndDestroy(), fMaxEnergyCut, fRangeVectorStore, G4Element::GetNumberOfElements(), incremental_prev_tag::idx, G4PhysicsTable::insert(), LowestEnergy, MaxEnergyCut, NumberOfElements, G4PhysicsVector::PutValue(), theLossTable, theParticle, TotBin, and verboseLevel.
G4bool G4VRangeToEnergyConverter::operator== (const G4VRangeToEnergyConverter & right) const
Definition at line 133 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 133 of file G4VRangeToEnergyConverter.cc
References right.
void G4VRangeToEnergyConverter::Reset () virtual
Reimplemented in G4RToEConvForProton.
Definition at line 269 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 269 of file G4VRangeToEnergyConverter.cc
References G4PhysicsTable::clearAndDestroy(), fRangeVectorStore, incremental_prev_tag::idx, NumberOfElements, and theLossTable.
Referenced by BuildLossTable(), Convert(), G4ProductionCutsTable::ResetConverters(), and ~G4VRangeToEnergyConverter().
void G4VRangeToEnergyConverter::SetEnergyRange (G4double lowedge, G4double highedge) static
Definition at line 222 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 222 of file G4VRangeToEnergyConverter.cc
References G4cerr, G4endl, G4Exception(), GeV, HighestEnergy, JustWarning, and LowestEnergy.
Referenced by G4ProductionCutsTable::SetEnergyRange().
void G4VRangeToEnergyConverter::SetMaxEnergyCut (G4double value) static
Definition at line 261 of file G4VRangeToEnergyConverter.cc.
View newest version in sPHENIX GitHub at line 261 of file G4VRangeToEnergyConverter.cc
References MaxEnergyCut.
Referenced by G4ProductionCutsTable::SetMaxEnergyCut().
void G4VRangeToEnergyConverter::SetVerboseLevel (G4int value) inline
Definition at line 158 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 158 of file G4VRangeToEnergyConverter.hh
References verboseLevel.
Referenced by G4ProductionCutsTable::SetVerboseLevel(), and G4ProductionCutsTable::UpdateCoupleTable().
Member Data Documentation
G4double G4VRangeToEnergyConverter::fMaxEnergyCut protected
Definition at line 111 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 111 of file G4VRangeToEnergyConverter.hh
Referenced by Convert(), G4VRangeToEnergyConverter(), and operator=().
std::vector< G4RangeVector* > G4VRangeToEnergyConverter::fRangeVectorStore protected
Definition at line 135 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 135 of file G4VRangeToEnergyConverter.hh
Referenced by Convert(), operator=(), and Reset().
G4double G4VRangeToEnergyConverter::HighestEnergy = 100.0e6*MeV static protected
Definition at line 109 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VRangeToEnergyConverter.hh
Referenced by GetHighEdgeEnergy(), and SetEnergyRange().
G4double G4VRangeToEnergyConverter::LowestEnergy = 0.99e-3*MeV static protected
Definition at line 109 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 109 of file G4VRangeToEnergyConverter.hh
Referenced by BuildLossTable(), BuildRangeVector(), Convert(), ConvertCutToKineticEnergy(), GetLowEdgeEnergy(), operator=(), and SetEnergyRange().
G4double G4VRangeToEnergyConverter::MaxEnergyCut = 10.0*GeV static protected
Definition at line 110 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VRangeToEnergyConverter.hh
Referenced by BuildLossTable(), BuildRangeVector(), Convert(), ConvertCutToKineticEnergy(), GetMaxEnergyCut(), operator=(), and SetMaxEnergyCut().
G4int G4VRangeToEnergyConverter::NumberOfElements protected
Definition at line 116 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VRangeToEnergyConverter.hh
Referenced by BuildLossTable(), operator=(), and Reset().
G4LossTable* G4VRangeToEnergyConverter::theLossTable protected
Definition at line 115 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VRangeToEnergyConverter.hh
Referenced by G4RToEConvForGamma::BuildAbsorptionLengthVector(), BuildLossTable(), G4VRangeToEnergyConverter(), operator=(), and Reset().
const G4ParticleDefinition* G4VRangeToEnergyConverter::theParticle protected
Definition at line 113 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VRangeToEnergyConverter.hh
Referenced by Convert(), ConvertCutToKineticEnergy(), G4RToEConvForElectron::G4RToEConvForElectron(), G4RToEConvForGamma::G4RToEConvForGamma(), G4RToEConvForPositron::G4RToEConvForPositron(), G4RToEConvForProton::G4RToEConvForProton(), GetParticleType(), and operator=().
const G4int G4VRangeToEnergyConverter::TotBin protected
Definition at line 119 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 119 of file G4VRangeToEnergyConverter.hh
Referenced by G4RToEConvForGamma::BuildAbsorptionLengthVector(), BuildLossTable(), BuildRangeVector(), Convert(), ConvertCutToKineticEnergy(), and operator=().
G4int G4VRangeToEnergyConverter::verboseLevel private
Definition at line 153 of file G4VRangeToEnergyConverter.hh.
View newest version in sPHENIX GitHub at line 153 of file G4VRangeToEnergyConverter.hh
Referenced by GetVerboseLevel(), operator=(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4VRangeToEnergyConverter.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4VRangeToEnergyConverter.cc