ECCE @ EIC Software: DMXEventAction Class Reference
DMXEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXEventAction.hh>
Public Member Functions
DMXEventAction ()
virtual ~DMXEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
void SetDrawTrksFlag (G4String val)
G4String GetDrawTrksFlag () const
void SetDrawColsFlag (G4String val)
G4String GetDrawColsFlag () const
void SetDrawHitsFlag (G4int val)
void SetSavePmtFlag (G4int val)
void SetSaveHitsFlag (G4int val)
void SetPrintModulo (G4int val)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
void writeScintHitsToFile ()
void writePmtHitsToFile (const DMXPmtHitsCollection *)
void drawTracks (const G4Event *)
Private Attributes
G4int event_id
const long * seeds
G4double energy_pri
G4int scintillatorCollID
G4int pmtCollID
G4int S_hits
G4int P_hits
G4double aveTimePmtHits
G4double totEnergy
G4double totEnergyGammas
G4double totEnergyNeutrons
G4double hitEnergy
G4double firstLXeHitTime
G4double firstParticleE
G4double particleEnergy
G4String particleName
G4String firstParticleName
G4bool gamma_ev
G4bool neutron_ev
G4bool positron_ev
G4bool electron_ev
G4bool proton_ev
G4bool other_ev
G4bool start_gamma
G4bool start_neutron
G4String drawTrksFlag
G4String drawColsFlag
G4int drawHitsFlag
G4int savePmtFlag
G4int saveHitsFlag
G4int printModulo
DMXEventActionMessenger * eventMessenger
const DMXRunAction * runAct
const DMXPrimaryGeneratorAction * genAction
std::ofstream * hitsfile
std::ofstream * pmtfile
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 58 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 58 of file DMXEventAction.hh
Constructor & Destructor Documentation
DMXEventAction::DMXEventAction ()
Definition at line 76 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 76 of file DMXEventAction.cc
References drawColsFlag, drawHitsFlag, drawTrksFlag, energy_pri, eventMessenger, pmtCollID, printModulo, saveHitsFlag, savePmtFlag, scintillatorCollID, and seeds.
DMXEventAction::~DMXEventAction () virtual
Definition at line 103 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 103 of file DMXEventAction.cc
References eventMessenger, hitsfile, and pmtfile.
Member Function Documentation
void DMXEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 120 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 120 of file DMXEventAction.cc
References energy_pri, event_id, G4BestUnit, G4cout, G4endl, genAction, G4SDManager::GetCollectionID(), DMXPrimaryGeneratorAction::GetEnergyPrimary(), G4Event::GetEventID(), DMXPrimaryGeneratorAction::GetEventSeeds(), G4RunManager::GetRunManager(), G4SDManager::GetSDMpointer(), G4RunManager::GetUserPrimaryGeneratorAction(), G4RunManager::GetUserRunAction(), pmtCollID, printModulo, runAct, scintillatorCollID, and seeds.
void DMXEventAction::drawTracks (const G4Event * evt) private
Definition at line 484 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 484 of file DMXEventAction.cc
References G4UImanager::ApplyCommand(), G4Trajectory::DrawTrajectory(), drawTrksFlag, G4TrajectoryContainer::entries(), G4Trajectory::GetCharge(), G4VVisManager::GetConcreteInstance(), G4Trajectory::GetParticleName(), G4Event::GetTrajectoryContainer(), and G4UImanager::GetUIpointer().
Referenced by EndOfEventAction().
void DMXEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 168 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 168 of file DMXEventAction.cc
References aveTimePmtHits, G4THitsCollection< T >::DrawAllHits(), drawColsFlag, drawHitsFlag, drawTracks(), drawTrksFlag, electron_ev, G4THitsCollection< T >::entries(), event_id, G4VAnalysisManager::FillH1(), firstLXeHitTime, firstParticleE, firstParticleName, G4BestUnit, G4cout, G4endl, gamma_ev, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), hitEnergy, G4ToolsAnalysisManager::Instance(), neutron_ev, other_ev, P_hits, particleEnergy, particleName, pmtCollID, positron_ev, printModulo, proton_ev, S_hits, saveHitsFlag, savePmtFlag, scintillatorCollID, start_gamma, start_neutron, Acts::VectorHelpers::time(), totEnergy, totEnergyGammas, totEnergyNeutrons, writePmtHitsToFile(), and writeScintHitsToFile().
G4String DMXEventAction::GetDrawColsFlag () const inline
Definition at line 76 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 76 of file DMXEventAction.hh
References drawColsFlag.
Referenced by DMXSteppingAction::UserSteppingAction().
G4String DMXEventAction::GetDrawTrksFlag () const inline
Definition at line 73 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 73 of file DMXEventAction.hh
References drawTrksFlag.
Referenced by DMXSteppingAction::UserSteppingAction().
void DMXEventAction::SetDrawColsFlag (G4String val) inline
Definition at line 75 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 75 of file DMXEventAction.hh
References drawColsFlag.
void DMXEventAction::SetDrawHitsFlag (G4int val) inline
Definition at line 78 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 78 of file DMXEventAction.hh
References drawHitsFlag.
void DMXEventAction::SetDrawTrksFlag (G4String val) inline
Definition at line 72 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 72 of file DMXEventAction.hh
References drawTrksFlag.
void DMXEventAction::SetPrintModulo (G4int val) inline
Definition at line 81 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 81 of file DMXEventAction.hh
References printModulo.
void DMXEventAction::SetSaveHitsFlag (G4int val) inline
Definition at line 80 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 80 of file DMXEventAction.hh
References saveHitsFlag.
void DMXEventAction::SetSavePmtFlag (G4int val) inline
Definition at line 79 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 79 of file DMXEventAction.hh
References savePmtFlag.
void DMXEventAction::writePmtHitsToFile (const DMXPmtHitsCollection * hits) private
Definition at line 418 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 418 of file DMXEventAction.cc
References G4VAnalysisManager::AddNtupleRow(), event_id, INPUTHEPMC::filename, G4VAnalysisManager::FillH2(), G4VAnalysisManager::FillNtupleDColumn(), G4cout, G4endl, G4Threading::G4GetThreadId(), DMXRunAction::GetsavepmtFile(), G4ToolsAnalysisManager::Instance(), left, mm, P_hits, pmtfile, printModulo, runAct, sss, x, y, and z.
Referenced by EndOfEventAction().
void DMXEventAction::writeScintHitsToFile () private
Definition at line 307 of file DMXEventAction.cc.
View newest version in sPHENIX GitHub at line 307 of file DMXEventAction.cc
References G4VAnalysisManager::AddNtupleRow(), aveTimePmtHits, electron_ev, energy_pri, event_id, INPUTHEPMC::filename, G4VAnalysisManager::FillH1(), G4VAnalysisManager::FillNtupleDColumn(), firstLXeHitTime, firstParticleE, firstParticleName, G4cout, G4endl, G4Threading::G4GetThreadId(), gamma_ev, DMXRunAction::GetsavehitsFile(), hitsfile, G4ToolsAnalysisManager::Instance(), keV, left, MeV, nanosecond, neutron_ev, ns, other_ev, P_hits, positron_ev, printModulo, runAct, S_hits, seeds, sss, and totEnergy.
Referenced by EndOfEventAction().
Member Data Documentation
G4double DMXEventAction::aveTimePmtHits private
Definition at line 96 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 96 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4String DMXEventAction::drawColsFlag private
Definition at line 118 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 118 of file DMXEventAction.hh
Referenced by DMXEventAction(), EndOfEventAction(), GetDrawColsFlag(), and SetDrawColsFlag().
G4int DMXEventAction::drawHitsFlag private
Definition at line 119 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 119 of file DMXEventAction.hh
Referenced by DMXEventAction(), EndOfEventAction(), and SetDrawHitsFlag().
G4String DMXEventAction::drawTrksFlag private
Definition at line 117 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 117 of file DMXEventAction.hh
Referenced by DMXEventAction(), drawTracks(), EndOfEventAction(), GetDrawTrksFlag(), and SetDrawTrksFlag().
G4bool DMXEventAction::electron_ev private
Definition at line 110 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 110 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4double DMXEventAction::energy_pri private
Definition at line 87 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 87 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), DMXEventAction(), and writeScintHitsToFile().
G4int DMXEventAction::event_id private
Definition at line 81 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 81 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), writePmtHitsToFile(), and writeScintHitsToFile().
DMXEventActionMessenger* DMXEventAction::eventMessenger private
Definition at line 123 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 123 of file DMXEventAction.hh
Referenced by DMXEventAction(), and ~DMXEventAction().
G4double DMXEventAction::firstLXeHitTime private
Definition at line 101 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 101 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4double DMXEventAction::firstParticleE private
Definition at line 102 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 102 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4String DMXEventAction::firstParticleName private
Definition at line 105 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 105 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4bool DMXEventAction::gamma_ev private
Definition at line 107 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 107 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
const DMXPrimaryGeneratorAction* DMXEventAction::genAction private
Definition at line 126 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 126 of file DMXEventAction.hh
Referenced by BeginOfEventAction().
G4double DMXEventAction::hitEnergy private
Definition at line 100 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 100 of file DMXEventAction.hh
Referenced by EndOfEventAction().
std::ofstream* DMXEventAction::hitsfile private
Definition at line 127 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 127 of file DMXEventAction.hh
Referenced by writeScintHitsToFile(), and ~DMXEventAction().
G4bool DMXEventAction::neutron_ev private
Definition at line 108 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 108 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4bool DMXEventAction::other_ev private
Definition at line 112 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 112 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4int DMXEventAction::P_hits private
Definition at line 93 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 93 of file DMXEventAction.hh
Referenced by EndOfEventAction(), writePmtHitsToFile(), and writeScintHitsToFile().
G4double DMXEventAction::particleEnergy private
Definition at line 103 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 103 of file DMXEventAction.hh
Referenced by EndOfEventAction().
G4String DMXEventAction::particleName private
Definition at line 104 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 104 of file DMXEventAction.hh
Referenced by EndOfEventAction().
G4int DMXEventAction::pmtCollID private
Definition at line 91 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 91 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), DMXEventAction(), and EndOfEventAction().
std::ofstream* DMXEventAction::pmtfile private
Definition at line 128 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 128 of file DMXEventAction.hh
Referenced by writePmtHitsToFile(), and ~DMXEventAction().
G4bool DMXEventAction::positron_ev private
Definition at line 109 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 109 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4int DMXEventAction::printModulo private
Definition at line 122 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 122 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), DMXEventAction(), EndOfEventAction(), SetPrintModulo(), writePmtHitsToFile(), and writeScintHitsToFile().
G4bool DMXEventAction::proton_ev private
Definition at line 111 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 111 of file DMXEventAction.hh
Referenced by EndOfEventAction().
const DMXRunAction* DMXEventAction::runAct private
Definition at line 125 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 125 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), writePmtHitsToFile(), and writeScintHitsToFile().
G4int DMXEventAction::S_hits private
Definition at line 92 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 92 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4int DMXEventAction::saveHitsFlag private
Definition at line 121 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 121 of file DMXEventAction.hh
Referenced by DMXEventAction(), EndOfEventAction(), and SetSaveHitsFlag().
G4int DMXEventAction::savePmtFlag private
Definition at line 120 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 120 of file DMXEventAction.hh
Referenced by DMXEventAction(), EndOfEventAction(), and SetSavePmtFlag().
G4int DMXEventAction::scintillatorCollID private
Definition at line 90 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 90 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), DMXEventAction(), and EndOfEventAction().
const long* DMXEventAction::seeds private
Definition at line 86 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 86 of file DMXEventAction.hh
Referenced by BeginOfEventAction(), DMXEventAction(), and writeScintHitsToFile().
G4bool DMXEventAction::start_gamma private
Definition at line 113 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 113 of file DMXEventAction.hh
Referenced by EndOfEventAction().
G4bool DMXEventAction::start_neutron private
Definition at line 114 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 114 of file DMXEventAction.hh
Referenced by EndOfEventAction().
G4double DMXEventAction::totEnergy private
Definition at line 97 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 97 of file DMXEventAction.hh
Referenced by EndOfEventAction(), and writeScintHitsToFile().
G4double DMXEventAction::totEnergyGammas private
Definition at line 98 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 98 of file DMXEventAction.hh
Referenced by EndOfEventAction().
G4double DMXEventAction::totEnergyNeutrons private
Definition at line 99 of file DMXEventAction.hh.
View newest version in sPHENIX GitHub at line 99 of file DMXEventAction.hh
Referenced by EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/src/DMXEventAction.cc