ECCE @ EIC Software: CCaloOrganization Class Reference
CCaloOrganization Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCaloOrganization.hh>
Public Member Functions
CCaloOrganization ()
virtual ~CCaloOrganization ()
unsigned int packindex (G4int det, G4int z, G4int eta, G4int phi) const
unsigned int packindex (G4int det, G4int depth, G4int z, G4int eta, G4int phi) const
void unpackindex (const unsigned int &idx, G4int &det, G4int &z, G4int &eta, G4int &phi) const
void unpackindex (const unsigned int &idx, G4int &det, G4int &depth, G4int &z, G4int &eta, G4int &phi) const
G4int getUnitWithMaxEnergy (std::map< G4int, G4float, std::less< G4int > > &themap)
G4float energyInMatrix (G4int nCellInEta, G4int nCellInPhi, G4int crystalWithMaxEnergy, std::map< G4int, G4float, std::less< G4int > > &themap)
Detailed Description
Definition at line 38 of file CCaloOrganization.hh.
View newest version in sPHENIX GitHub at line 38 of file CCaloOrganization.hh
Constructor & Destructor Documentation
CCaloOrganization::CCaloOrganization () inline
Definition at line 41 of file CCaloOrganization.hh.
View newest version in sPHENIX GitHub at line 41 of file CCaloOrganization.hh
virtual CCaloOrganization::~CCaloOrganization () inline virtual
Definition at line 42 of file CCaloOrganization.hh.
View newest version in sPHENIX GitHub at line 42 of file CCaloOrganization.hh
Member Function Documentation
G4float CCaloOrganization::energyInMatrix (G4int nCellInEta, G4int nCellInPhi, G4int crystalWithMaxEnergy, std::map< G4int, G4float, std::less< G4int > > & themap)
Definition at line 121 of file CCaloOrganization.cc.
View newest version in sPHENIX GitHub at line 121 of file CCaloOrganization.cc
References Acts::VectorHelpers::eta(), G4cout, G4endl, packindex(), phi, unpackindex(), and z.
G4int CCaloOrganization::getUnitWithMaxEnergy (std::map< G4int, G4float, std::less< G4int > > & themap)
Definition at line 94 of file CCaloOrganization.cc.
View newest version in sPHENIX GitHub at line 94 of file CCaloOrganization.cc
References Acts::VectorHelpers::eta(), G4cout, G4endl, phi, unpackindex(), and z.
unsigned int CCaloOrganization::packindex (G4int det, G4int z, G4int eta, G4int phi) const
Definition at line 35 of file CCaloOrganization.cc.
View newest version in sPHENIX GitHub at line 35 of file CCaloOrganization.cc
References G4cout, G4endl, and incremental_prev_tag::idx.
Referenced by energyInMatrix().
unsigned int CCaloOrganization::packindex (G4int det, G4int depth, G4int z, G4int eta, G4int phi) const
Definition at line 53 of file CCaloOrganization.cc.
View newest version in sPHENIX GitHub at line 53 of file CCaloOrganization.cc
References G4cout, G4endl, and incremental_prev_tag::idx.
void CCaloOrganization::unpackindex (const unsigned int & idx, G4int & det, G4int & z, G4int & eta, G4int & phi) const
Definition at line 73 of file CCaloOrganization.cc.
View newest version in sPHENIX GitHub at line 73 of file CCaloOrganization.cc
Referenced by energyInMatrix(), and getUnitWithMaxEnergy().
void CCaloOrganization::unpackindex (const unsigned int & idx, G4int & det, G4int & depth, G4int & z, G4int & eta, G4int & phi) const
Definition at line 83 of file CCaloOrganization.cc.
View newest version in sPHENIX GitHub at line 83 of file CCaloOrganization.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCaloOrganization.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCaloOrganization.cc