ECCE @ EIC Software: G4PhysicsListHelper Class Reference
G4PhysicsListHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4PhysicsListHelper.hh>
Public Member Functions
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void AddTransportation ()
void UseCoupledTransportation (G4bool vl=true)
void UseHighLooperThresholds ()
void UseLowLooperThresholds ()
void CheckParticleList () const
void DumpOrdingParameterTable (G4int subType=-1) const
G4PhysicsListOrderingParameter GetOrdingParameter (G4int subType) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Static Public Member Functions
static G4PhysicsListHelper * GetPhysicsListHelper ()
Private Types
typedef std::vector
< G4PhysicsListOrderingParameter > G4OrdParamTable
Private Member Functions
G4PhysicsListHelper ()
~G4PhysicsListHelper ()
void ReadOrdingParameterTable ()
void ReadInDefaultOrderingParameter ()
Private Attributes
G4ParticleTable * theParticleTable
G4ParticleTable::G4PTblDicIterator * aParticleIterator
G4bool useCoupledTransportation
G4int theLooperThresholds = 1
G4VProcess * theTransportationProcess
G4int verboseLevel
G4OrdParamTable * theTable
G4int sizeOfTable
G4String ordParamFileName
Static Private Attributes
static G4ThreadLocal
G4PhysicsListHelper * pPLHelper = nullptr
Friends
class G4ThreadLocalSingleton< G4PhysicsListHelper >
Detailed Description
Definition at line 51 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 51 of file G4PhysicsListHelper.hh
Member Typedef Documentation
typedef std::vector<G4PhysicsListOrderingParameter> G4PhysicsListHelper::G4OrdParamTable private
Definition at line 122 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 122 of file G4PhysicsListHelper.hh
Constructor & Destructor Documentation
G4PhysicsListHelper::G4PhysicsListHelper () private
Definition at line 51 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 51 of file G4PhysicsListHelper.cc
References aParticleIterator, DumpOrdingParameterTable(), G4ParticleTable::GetIterator(), G4ParticleTable::GetParticleTable(), ReadOrdingParameterTable(), theParticleTable, and verboseLevel.
G4PhysicsListHelper::~G4PhysicsListHelper () private
Definition at line 73 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 73 of file G4PhysicsListHelper.cc
References sizeOfTable, and theTable.
Member Function Documentation
void G4PhysicsListHelper::AddTransportation ()
Definition at line 209 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 209 of file G4PhysicsListHelper.cc
References G4ProcessManager::AddProcess(), aParticleIterator, FatalException, G4cout, G4endl, G4Exception(), G4RunManagerKernel::GetNumberOfParallelWorld(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetProcessManager(), G4RunManagerKernel::GetRunManagerKernel(), G4ScoringManager::GetScoringManagerIfExist(), idxAlongStep, idxPostStep, particle, G4ParticleTableIterator< K, V >::reset(), G4ProcessManager::SetProcessOrderingToFirst(), theLooperThresholds, theTransportationProcess, useCoupledTransportation, G4ParticleTableIterator< K, V >::value(), and verboseLevel.
void G4PhysicsListHelper::CheckParticleList () const
Definition at line 101 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PhysicsListHelper.cc
References aParticleIterator, FatalException, fElectromagnetic, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), incremental_prev_tag::idx, G4InuclParticleNames::isElectron(), particle, G4ParticleTableIterator< K, V >::reset(), G4ProcessVector::size(), G4ParticleTableIterator< K, V >::value(), and verboseLevel.
void G4PhysicsListHelper::DumpOrdingParameterTable (G4int subType = -1) const
Definition at line 350 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 350 of file G4PhysicsListHelper.cc
References G4cout, G4endl, G4PhysicsListOrderingParameter::isDuplicable, G4PhysicsListOrderingParameter::ordering, ordParamFileName, G4PhysicsListOrderingParameter::processSubType, G4PhysicsListOrderingParameter::processType, G4PhysicsListOrderingParameter::processTypeName, sizeOfTable, theTable, tmp, and verboseLevel.
Referenced by G4PhysicsListHelper(), and G4UserPhysicsListMessenger::SetNewValue().
G4PhysicsListOrderingParameter G4PhysicsListHelper::GetOrdingParameter (G4int subType) const
Definition at line 387 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 387 of file G4PhysicsListHelper.cc
References G4cout, G4endl, G4PhysicsListOrderingParameter::isDuplicable, G4PhysicsListOrderingParameter::ordering, ordParamFileName, G4PhysicsListOrderingParameter::processSubType, G4PhysicsListOrderingParameter::processType, G4PhysicsListOrderingParameter::processTypeName, sizeOfTable, theTable, tmp, and verboseLevel.
G4PhysicsListHelper * G4PhysicsListHelper::GetPhysicsListHelper () static
Definition at line 90 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 90 of file G4PhysicsListHelper.cc
References G4ThreadLocalSingleton< T >::Instance(), and pPLHelper.
Referenced by PhysicsList::AddDecay(), PhysicsList::AddMaxStepSize(), PhysicsList::AddRadioactiveDecay(), PhysicsList::AddTrackingCut(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), DMXPhysicsList::ConstructGeneral(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), BiasedRDPhysics::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4MuonicAtomDecayPhysics::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), G4RadioactiveDecayPhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), G4UnknownDecayPhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4DecayPhysics::ConstructProcess(), TSPhysicsList::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4VUserPhysicsList::G4VUserPhysicsList(), G4VUPLData::initialize(), main(), G4VPhysicsConstructor::RegisterProcess(), and G4UserPhysicsListMessenger::SetNewValue().
G4int G4PhysicsListHelper::GetVerboseLevel () const inline
Definition at line 142 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PhysicsListHelper.hh
References verboseLevel.
Referenced by G4MuonicAtomDecayPhysics::ConstructProcess().
void G4PhysicsListHelper::ReadInDefaultOrderingParameter () private
Definition at line 574 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 574 of file G4PhysicsListHelper.cc
References G4PhysicsListOrderingParameter::isDuplicable, G4PhysicsListOrderingParameter::ordering, G4PhysicsListOrderingParameter::processSubType, G4PhysicsListOrderingParameter::processType, G4PhysicsListOrderingParameter::processTypeName, sizeOfTable, theTable, and tmp.
Referenced by ReadOrdingParameterTable().
void G4PhysicsListHelper::ReadOrdingParameterTable () private
Definition at line 274 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 274 of file G4PhysicsListHelper.cc
References G4cout, G4endl, G4Exception(), in, G4PhysicsListOrderingParameter::isDuplicable, JustWarning, G4PhysicsListOrderingParameter::ordering, ordParamFileName, G4PhysicsListOrderingParameter::processSubType, G4PhysicsListOrderingParameter::processType, G4PhysicsListOrderingParameter::processTypeName, ReadInDefaultOrderingParameter(), sizeOfTable, theTable, tmp, and verboseLevel.
Referenced by G4PhysicsListHelper().
G4bool G4PhysicsListHelper::RegisterProcess (G4VProcess * process, G4ParticleDefinition * particle)
Definition at line 418 of file G4PhysicsListHelper.cc.
View newest version in sPHENIX GitHub at line 418 of file G4PhysicsListHelper.cc
References G4ProcessManager::AddProcess(), FatalException, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), G4VProcess::GetProcessType(), incremental_prev_tag::idx, G4PhysicsListOrderingParameter::isDuplicable, JustWarning, G4PhysicsListOrderingParameter::ordering, ordParamFileName, G4PhysicsListOrderingParameter::processSubType, G4PhysicsListOrderingParameter::processType, G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToFirst(), G4ProcessManager::SetProcessOrderingToLast(), G4ProcessVector::size(), sizeOfTable, theTable, tmp, and verboseLevel.
Referenced by PhysicsList::AddDecay(), PhysicsList::AddMaxStepSize(), PhysicsList::AddRadioactiveDecay(), PhysicsList::AddTrackingCut(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), G4MonopolePhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4UnknownDecayPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4DecayPhysics::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), TSPhysicsList::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), and G4VPhysicsConstructor::RegisterProcess().
void G4PhysicsListHelper::SetVerboseLevel (G4int value) inline
Definition at line 136 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 136 of file G4PhysicsListHelper.hh
References verboseLevel.
Referenced by G4MuonicAtomDecayPhysics::ConstructProcess().
void G4PhysicsListHelper::UseCoupledTransportation (G4bool vl = true) inline
Definition at line 130 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PhysicsListHelper.hh
References useCoupledTransportation.
void G4PhysicsListHelper::UseHighLooperThresholds () inline
Definition at line 80 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 80 of file G4PhysicsListHelper.hh
References theLooperThresholds.
void G4PhysicsListHelper::UseLowLooperThresholds () inline
Definition at line 81 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 81 of file G4PhysicsListHelper.hh
References theLooperThresholds.
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4PhysicsListHelper > friend
Definition at line 54 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 54 of file G4PhysicsListHelper.hh
Member Data Documentation
G4ParticleTable::G4PTblDicIterator* G4PhysicsListHelper::aParticleIterator private
Definition at line 113 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PhysicsListHelper.hh
Referenced by AddTransportation(), CheckParticleList(), and G4PhysicsListHelper().
G4String G4PhysicsListHelper::ordParamFileName private
Definition at line 125 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PhysicsListHelper.hh
Referenced by DumpOrdingParameterTable(), GetOrdingParameter(), ReadOrdingParameterTable(), and RegisterProcess().
G4ThreadLocal G4PhysicsListHelper * G4PhysicsListHelper::pPLHelper = nullptr static private
Definition at line 109 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 109 of file G4PhysicsListHelper.hh
Referenced by GetPhysicsListHelper().
G4int G4PhysicsListHelper::sizeOfTable private
Definition at line 124 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PhysicsListHelper.hh
Referenced by DumpOrdingParameterTable(), GetOrdingParameter(), ReadInDefaultOrderingParameter(), ReadOrdingParameterTable(), RegisterProcess(), and ~G4PhysicsListHelper().
G4int G4PhysicsListHelper::theLooperThresholds = 1 private
Definition at line 116 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PhysicsListHelper.hh
Referenced by AddTransportation(), UseHighLooperThresholds(), and UseLowLooperThresholds().
G4ParticleTable* G4PhysicsListHelper::theParticleTable private
Definition at line 112 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PhysicsListHelper.hh
Referenced by G4PhysicsListHelper().
G4OrdParamTable* G4PhysicsListHelper::theTable private
Definition at line 123 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 123 of file G4PhysicsListHelper.hh
Referenced by DumpOrdingParameterTable(), GetOrdingParameter(), ReadInDefaultOrderingParameter(), ReadOrdingParameterTable(), RegisterProcess(), and ~G4PhysicsListHelper().
G4VProcess* G4PhysicsListHelper::theTransportationProcess private
Definition at line 117 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PhysicsListHelper.hh
Referenced by AddTransportation().
G4bool G4PhysicsListHelper::useCoupledTransportation private
Definition at line 115 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PhysicsListHelper.hh
Referenced by AddTransportation(), and UseCoupledTransportation().
G4int G4PhysicsListHelper::verboseLevel private
Definition at line 119 of file G4PhysicsListHelper.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PhysicsListHelper.hh
Referenced by AddTransportation(), CheckParticleList(), DumpOrdingParameterTable(), G4PhysicsListHelper(), GetOrdingParameter(), GetVerboseLevel(), ReadOrdingParameterTable(), RegisterProcess(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4PhysicsListHelper.hh
geant4/tree/geant4-10.6-release/source/run/src/G4PhysicsListHelper.cc