ECCE @ EIC Software: G4HCIOentryT< T > Class Template Reference
G4HCIOentryT< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4HCIOentryT.hh>
Public Member Functions
G4HCIOentryT (std::string n)
~G4HCIOentryT ()
void CreateHCIOmanager (std::string detName, std::string colName)
void DeleteHCIOmanager ()
Public Member Functions inherited from G4VHCIOentry
G4VHCIOentry (std::string n)
virtual ~G4VHCIOentry ()
void SetVerboseLevel (G4int v)
std::string GetName ()
Private Attributes
G4VPHitsCollectionIO * f_manager
Additional Inherited Members
Protected Attributes inherited from G4VHCIOentry
G4int m_verbose
Detailed Description
template<class T>
class G4HCIOentryT< T >
Definition at line 44 of file G4HCIOentryT.hh.
View newest version in sPHENIX GitHub at line 44 of file G4HCIOentryT.hh
Constructor & Destructor Documentation
template<class T > G4HCIOentryT< T >::G4HCIOentryT (std::string n) inline
Definition at line 48 of file G4HCIOentryT.hh.
View newest version in sPHENIX GitHub at line 48 of file G4HCIOentryT.hh
References G4cout, G4endl, G4VHCIOentry::m_verbose, and n.
template<class T > G4HCIOentryT< T >::~G4HCIOentryT () inline
Definition at line 58 of file G4HCIOentryT.hh.
View newest version in sPHENIX GitHub at line 58 of file G4HCIOentryT.hh
Member Function Documentation
template<class T > void G4HCIOentryT< T >::CreateHCIOmanager (std::string detName, std::string colName) inline virtual
Reimplemented from G4VHCIOentry.
Definition at line 62 of file G4HCIOentryT.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HCIOentryT.hh
References G4HCIOentryT< T >::f_manager, G4cout, G4endl, G4HCIOcatalog::GetHCIOcatalog(), G4VHCIOentry::m_verbose, G4HCIOcatalog::PrintHCIOmanager(), G4HCIOcatalog::RegisterHCIOmanager(), and T.
template<class T > void G4HCIOentryT< T >::DeleteHCIOmanager () inline
Definition at line 78 of file G4HCIOentryT.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HCIOentryT.hh
Member Data Documentation
template<class T > G4VPHitsCollectionIO* G4HCIOentryT< T >::f_manager private
Definition at line 78 of file G4HCIOentryT.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HCIOentryT.hh
Referenced by G4HCIOentryT< T >::CreateHCIOmanager().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4HCIOentryT.hh