ECCE @ EIC Software: G4ParticleHPJENDLHEData Class Reference
G4ParticleHPJENDLHEData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPJENDLHEData.hh>
Public Member Functions
G4ParticleHPJENDLHEData ()
G4ParticleHPJENDLHEData (G4String, G4ParticleDefinition *)
~G4ParticleHPJENDLHEData ()
G4bool IsApplicable (const G4DynamicParticle *, const G4Element *)
G4bool IsZAApplicable (const G4DynamicParticle *, G4double, G4double)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, G4double aT)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4bool isThisInMap (G4int, G4int)
G4bool isThisNewIsotope (G4int z, G4int a)
G4PhysicsVector * readAFile (std::fstream *)
void registAPhysicsVector (G4int, G4int, G4PhysicsVector *)
G4double getXSfromThisIsotope (G4int, G4int, G4double)
Private Attributes
std::vector< G4bool > vElement
std::map< G4int, std::map
< G4int, G4PhysicsVector * > * > mIsotope
G4String reactionName
G4String particleName
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 48 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPJENDLHEData.hh
Constructor & Destructor Documentation
G4ParticleHPJENDLHEData::G4ParticleHPJENDLHEData ()
Definition at line 60 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPJENDLHEData.cc
References mIsotope.
G4ParticleHPJENDLHEData::G4ParticleHPJENDLHEData (G4String reaction, G4ParticleDefinition * pd)
Definition at line 83 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPJENDLHEData.cc
References BuildPhysicsTable(), and reactionName.
G4ParticleHPJENDLHEData::~G4ParticleHPJENDLHEData ()
Definition at line 92 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPJENDLHEData.cc
Member Function Documentation
void G4ParticleHPJENDLHEData::BuildPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 100 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPJENDLHEData.cc
References A(), FALSE, file, INPUTHEPMC::filename, G4ThreadLocal, G4Element::GetElementTable(), G4StableIsotopes::GetFirstIsotope(), G4Element::GetIsotope(), G4StableIsotopes::GetIsotopeNucleonCount(), G4Isotope::GetN(), G4ParticleHPNames::GetName(), G4Element::GetNumberOfElements(), G4StableIsotopes::GetNumberOfIsotopes(), G4ParticleDefinition::GetParticleName(), G4Element::GetZ(), in, isThisNewIsotope(), particleName, reactionName, readAFile(), registAPhysicsVector(), TRUE, vElement, and Z.
Referenced by G4ParticleHPJENDLHEData().
void G4ParticleHPJENDLHEData::DumpPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 237 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 237 of file G4ParticleHPJENDLHEData.cc
References G4Neutron::Neutron().
G4double G4ParticleHPJENDLHEData::GetCrossSection (const G4DynamicParticle * aP, const G4Element * anE, G4double aT)
Definition at line 247 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 247 of file G4ParticleHPJENDLHEData.cc
References A(), G4StableIsotopes::GetAbundance(), G4StableIsotopes::GetFirstIsotope(), G4Element::GetIsotope(), G4StableIsotopes::GetIsotopeNucleonCount(), G4DynamicParticle::GetKineticEnergy(), G4Isotope::GetN(), G4StableIsotopes::GetNumberOfIsotopes(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), getXSfromThisIsotope(), G4Element::GetZ(), perCent, and Z.
G4double G4ParticleHPJENDLHEData::getXSfromThisIsotope (G4int Z, G4int A, G4double ek) private
Definition at line 364 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 364 of file G4ParticleHPJENDLHEData.cc
References G4Pow::A23(), kdfinder::abs(), Acts::Test::delta, G4UniformRand, G4Pow::GetInstance(), G4PhysicsVector::GetValue(), it, and mIsotope.
Referenced by GetCrossSection().
G4bool G4ParticleHPJENDLHEData::IsApplicable (const G4DynamicParticle * aP, const G4Element * anE)
Definition at line 41 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPJENDLHEData.cc
References G4Element::GetIndex(), G4DynamicParticle::GetKineticEnergy(), MeV, G4Neutron::Neutron(), and vElement.
G4bool G4ParticleHPJENDLHEData::isThisInMap (G4int z, G4int a) private
Definition at line 333 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 333 of file G4ParticleHPJENDLHEData.cc
References mIsotope, and second.
Referenced by isThisNewIsotope().
G4bool G4ParticleHPJENDLHEData::isThisNewIsotope (G4int z, G4int a) inline private
Definition at line 76 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPJENDLHEData.hh
References isThisInMap().
Referenced by BuildPhysicsTable().
G4bool G4ParticleHPJENDLHEData::IsZAApplicable (const G4DynamicParticle * , G4double , G4double) inline
Definition at line 60 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPJENDLHEData.hh
G4PhysicsVector * G4ParticleHPJENDLHEData::readAFile (std::fstream * file) private
Definition at line 298 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 298 of file G4ParticleHPJENDLHEData.cc
References barn, e, eV, and G4LPhysicsFreeVector::PutValues().
Referenced by BuildPhysicsTable().
void G4ParticleHPJENDLHEData::registAPhysicsVector (G4int Z, G4int A, G4PhysicsVector * aPhysVec) private
Definition at line 342 of file G4ParticleHPJENDLHEData.cc.
View newest version in sPHENIX GitHub at line 342 of file G4ParticleHPJENDLHEData.cc
References A(), and mIsotope.
Referenced by BuildPhysicsTable().
Member Data Documentation
std::map< G4int , std::map< G4int , G4PhysicsVector* >* > G4ParticleHPJENDLHEData::mIsotope private
Definition at line 73 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPJENDLHEData.hh
Referenced by G4ParticleHPJENDLHEData(), getXSfromThisIsotope(), isThisInMap(), and registAPhysicsVector().
G4String G4ParticleHPJENDLHEData::particleName private
Definition at line 83 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPJENDLHEData.hh
Referenced by BuildPhysicsTable().
G4String G4ParticleHPJENDLHEData::reactionName private
Definition at line 82 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPJENDLHEData.hh
Referenced by BuildPhysicsTable(), and G4ParticleHPJENDLHEData().
std::vector< G4bool > G4ParticleHPJENDLHEData::vElement private
Definition at line 71 of file G4ParticleHPJENDLHEData.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPJENDLHEData.hh
Referenced by BuildPhysicsTable(), and IsApplicable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPJENDLHEData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPJENDLHEData.cc