ECCE @ EIC Software: G4eIonisationParameters Class Reference
G4eIonisationParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4eIonisationParameters.hh>
Public Member Functions
G4eIonisationParameters (G4int minZ=1, G4int maxZ=99)
~G4eIonisationParameters ()
G4double Parameter (G4int Z, G4int shellIndex, G4int parameterIndex, G4double e) const
G4double Excitation (G4int Z, G4double e) const
void PrintData () const
Private Member Functions
G4eIonisationParameters (const G4eIonisationParameters &)
G4eIonisationParameters & operator= (const G4eIonisationParameters &right)
void LoadData ()
Private Attributes
G4int zMin
G4int zMax
G4DataVector activeZ
std::map< G4int, G4VEMDataSet
*, std::less< G4int > > param
std::map< G4int, G4VEMDataSet
*, std::less< G4int > > excit
size_t length
Detailed Description
Definition at line 60 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 60 of file G4eIonisationParameters.hh
Constructor & Destructor Documentation
G4eIonisationParameters::G4eIonisationParameters (G4int minZ = 1, G4int maxZ = 99)
Definition at line 62 of file G4eIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 62 of file G4eIonisationParameters.cc
References LoadData().
G4eIonisationParameters::~G4eIonisationParameters ()
Definition at line 70 of file G4eIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 70 of file G4eIonisationParameters.cc
References activeZ, excit, param, and pos().
G4eIonisationParameters::G4eIonisationParameters (const G4eIonisationParameters &) private
Member Function Documentation
G4double G4eIonisationParameters::Excitation (G4int Z, G4double e) const
Definition at line 124 of file G4eIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 124 of file G4eIonisationParameters.cc
References e, excit, G4VEMDataSet::FindValue(), G4cout, G4endl, G4VEMDataSet::GetEnergies(), max, min, and pos().
Referenced by G4eIonisationSpectrum::Excitation().
void G4eIonisationParameters::LoadData () private
Definition at line 146 of file G4eIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 146 of file G4eIonisationParameters.cc
References a, activeZ, barn, G4DataVector::contains(), d, e, energy, excit, FatalException, file, G4cout, G4endl, G4Exception(), G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Element::GetZ(), k, length, material(), MeV, G4TrackingService::nMaterials, param, sum, Z, and z.
Referenced by G4eIonisationParameters().
G4eIonisationParameters& G4eIonisationParameters::operator= (const G4eIonisationParameters & right) private
G4double G4eIonisationParameters::Parameter (G4int Z, G4int shellIndex, G4int parameterIndex, G4double e) const
Definition at line 91 of file G4eIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 91 of file G4eIonisationParameters.cc
References e, G4VEMDataSet::FindValue(), G4cout, G4endl, G4VEMDataSet::GetComponent(), G4VEMDataSet::GetEnergies(), max, min, G4VEMDataSet::NumberOfComponents(), param, and pos().
Referenced by G4eIonisationSpectrum::AverageEnergy(), G4eIonisationSpectrum::Probability(), and G4eIonisationSpectrum::SampleEnergy().
void G4eIonisationParameters::PrintData (void) const
Definition at line 383 of file G4eIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 383 of file G4eIonisationParameters.cc
References activeZ, G4cout, G4endl, G4VEMDataSet::GetComponent(), k, length, G4VEMDataSet::NumberOfComponents(), param, pos(), G4VEMDataSet::PrintData(), and Z.
Referenced by G4eIonisationSpectrum::PrintData().
Member Data Documentation
G4DataVector G4eIonisationParameters::activeZ private
Definition at line 86 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 86 of file G4eIonisationParameters.hh
Referenced by LoadData(), PrintData(), and ~G4eIonisationParameters().
std::map<G4int,G4VEMDataSet*,std::less<G4int> > G4eIonisationParameters::excit private
Definition at line 90 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4eIonisationParameters.hh
Referenced by Excitation(), LoadData(), and ~G4eIonisationParameters().
size_t G4eIonisationParameters::length private
Definition at line 92 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 92 of file G4eIonisationParameters.hh
Referenced by LoadData(), and PrintData().
std::map<G4int,G4VEMDataSet*,std::less<G4int> > G4eIonisationParameters::param private
Definition at line 89 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 89 of file G4eIonisationParameters.hh
Referenced by LoadData(), Parameter(), PrintData(), and ~G4eIonisationParameters().
G4int G4eIonisationParameters::zMax private
Definition at line 84 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 84 of file G4eIonisationParameters.hh
G4int G4eIonisationParameters::zMin private
Definition at line 83 of file G4eIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4eIonisationParameters.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4eIonisationParameters.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4eIonisationParameters.cc