ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/chem4.cc File Reference
chem4.cc File Reference
Chem4 example.
#include "DetectorConstruction.hh"
#include "PhysicsList.hh"
#include "ActionInitialization.hh"
#include "G4RunManager.hh"
#include "G4DNAChemistryManager.hh"
#include "G4UImanager.hh"
#include "G4UIExecutive.hh"
#include "G4VisExecutive.hh"
#include "CommandLineParser.hh"
Functions
CommandLineParser * parser (0)
unsigned int noise ()
void SetSeed ()
void Parse (int &argc, char **argv)
int main (int argc, char **argv)
bool IsBracket (char c)
Variables
long seed = 0
Detailed Description
Chem4 example.
Definition in file chem4.cc.
Function Documentation
bool IsBracket (char c)
Definition at line 194 of file chem4.cc.
View newest version in sPHENIX GitHub at line 194 of file chem4.cc
Referenced by SetSeed().
int main (int argc, char ** argv)
Definition at line 76 of file chem4.cc.
View newest version in sPHENIX GitHub at line 76 of file chem4.cc
References G4UImanager::ApplyCommand(), G4UIcommand::ConvertToInt(), G4DNAPARSER::CommandLineParser::DeleteInstance(), G4cout, G4endl, G4Threading::G4GetNumberOfCores(), G4DNAPARSER::CommandLineParser::GetCommandIfActive(), G4MTRunManager::GetNumberOfThreads(), G4DNAPARSER::Command::GetOption(), G4UImanager::GetUIpointer(), G4VisManager::Initialize(), G4UIExecutive::IsGUI(), Parse(), parser(), G4WORLD::PhysicsList, G4UIExecutive::SessionStart(), G4MTRunManager::SetNumberOfThreads(), SetSeed(), and G4RunManager::SetUserInitialization().
unsigned int noise ()
Definition at line 261 of file chem4.cc.
View newest version in sPHENIX GitHub at line 261 of file chem4.cc
References file, int(), and Acts::VectorHelpers::time().
Referenced by PHG4InttDigitizer::added_noise(), PHG4TpcDigitizer::added_noise(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4MicromegasDigitizer::process_event(), and SetSeed().
void Parse (int & argc, char ** argv)
CommandLineParser* parser (0)
void SetSeed ()
Definition at line 208 of file chem4.cc.
View newest version in sPHENIX GitHub at line 208 of file chem4.cc
References buffer, G4cout, G4endl, G4DNAPARSER::CommandLineParser::GetCommandIfActive(), G4DNAPARSER::Command::GetOption(), IsBracket(), noise(), parser(), seed, and Acts::VectorHelpers::time().
Referenced by main(), and G4MPImessenger::SetNewValue().
Variable Documentation
long seed = 0
Definition at line 67 of file chem4.cc.
View newest version in sPHENIX GitHub at line 67 of file chem4.cc
Referenced by _embed_only(), B0TrackFastSim::B0TrackFastSim(), BOOST_DATA_TEST_CASE(), CLHEP::DualRand::DualRand(), Fun4AllDstPileupInputManager::Fun4AllDstPileupInputManager(), Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), Fun4AllSingleDstPileupInputManager::Fun4AllSingleDstPileupInputManager(), generate_hash_secret_salt(), G4MPIrandomSeedGenerator::GenerateSeeds(), PdbParameterMap::get_hash(), PHParameters::get_hash(), G4TemplateRNGHelper< T >::GetSeed(), CLHEP::HepJamesRandom::HepJamesRandom(), FermimotionAfterburner::Init(), sHEPGen::Init(), PHPythia8::Init(), BbcVertexFastSimReco::InitRun(), GlobalVertexFastSimReco::InitRun(), PHRandomSeed::InitSeed(), PHActsTrkFitter::loopTracks(), main(), PHActsSiliconSeeding::makeSvtxTracks(), PHTpcResiduals::makeTrackParams(), CLHEP::MixMaxRng::MixMaxRng(), CLHEP::MTwistEngine::MTwistEngine(), Par02Smearer::Par02Smearer(), PHG4InttDigitizer::PHG4InttDigitizer(), PHG4MicromegasDigitizer::PHG4MicromegasDigitizer(), PHG4MicromegasHitReco::PHG4MicromegasHitReco(), PHG4MvtxDigitizer::PHG4MvtxDigitizer(), PHG4TpcDigitizer::PHG4TpcDigitizer(), PHG4TrackFastSim::PHG4TrackFastSim(), PHG4ZDCSteppingAction::PHG4ZDCSteppingAction(), PHHepMCGenHelper::PHHepMCGenHelper(), PHCASeeding::publishSeeds(), PHSimpleKFProp::publishSeeds(), CLHEP::Ranlux64Engine::Ranlux64Engine(), CLHEP::RanluxEngine::RanluxEngine(), CLHEP::RanshiEngine::RanshiEngine(), runSeeding(), CLHEP::MixMaxRng::seed_spbox(), PHG4TpcElectronDrift::set_seed(), RawClusterBuilderTopo::set_significance(), G4MPImessenger::SetNewValue(), CLHEP::HepJamesRandom::setSeed(), CLHEP::Ranlux64Engine::setSeed(), SetSeed(), CLHEP::DualRand::setSeed(), CLHEP::RanluxEngine::setSeed(), and CLHEP::DualRand::Tausworthe::Tausworthe().