ECCE @ EIC Software: G4WeightCutOffConfigurator Class Reference
G4WeightCutOffConfigurator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4WeightCutOffConfigurator.hh>
Public Member Functions
G4WeightCutOffConfigurator (const G4VPhysicalVolume *worldvolume, const G4String &particlename, G4double wsurvival, G4double wlimit, G4double isource, G4VIStore *istore, G4bool paraflag)
virtual ~G4WeightCutOffConfigurator ()
virtual void Configure (G4VSamplerConfigurator *preConf)
virtual const G4VTrackTerminator * GetTrackTerminator () const
Public Member Functions inherited from G4VSamplerConfigurator
G4VSamplerConfigurator ()
virtual ~G4VSamplerConfigurator ()
Private Member Functions
G4WeightCutOffConfigurator (const G4WeightCutOffConfigurator &)
G4WeightCutOffConfigurator & operator= (const G4WeightCutOffConfigurator &)
Private Attributes
const G4VPhysicalVolume * fWorld
G4ProcessPlacer fPlacer
G4WeightCutOffProcess * fWeightCutOffProcess
G4bool fPlaced
G4bool paraflag
Detailed Description
Definition at line 50 of file G4WeightCutOffConfigurator.hh.
View newest version in sPHENIX GitHub at line 50 of file G4WeightCutOffConfigurator.hh
Constructor & Destructor Documentation
G4WeightCutOffConfigurator::G4WeightCutOffConfigurator (const G4VPhysicalVolume * worldvolume, const G4String & particlename, G4double wsurvival, G4double wlimit, G4double isource, G4VIStore * istore, G4bool paraflag)
Definition at line 38 of file G4WeightCutOffConfigurator.cc.
View newest version in sPHENIX GitHub at line 38 of file G4WeightCutOffConfigurator.cc
References FatalException, fWeightCutOffProcess, G4Exception(), and paraflag.
G4WeightCutOffConfigurator::~G4WeightCutOffConfigurator () virtual
Definition at line 62 of file G4WeightCutOffConfigurator.cc.
View newest version in sPHENIX GitHub at line 62 of file G4WeightCutOffConfigurator.cc
References fPlaced, fPlacer, fWeightCutOffProcess, and G4ProcessPlacer::RemoveProcess().
G4WeightCutOffConfigurator::G4WeightCutOffConfigurator (const G4WeightCutOffConfigurator &) private
Member Function Documentation
void G4WeightCutOffConfigurator::Configure (G4VSamplerConfigurator * preConf) virtual
Implements G4VSamplerConfigurator.
Definition at line 71 of file G4WeightCutOffConfigurator.cc.
View newest version in sPHENIX GitHub at line 71 of file G4WeightCutOffConfigurator.cc
References G4ProcessPlacer::AddProcessAsLastDoIt(), fPlaced, fPlacer, fWeightCutOffProcess, fWorld, G4cout, G4endl, G4VPhysicalVolume::GetName(), paraflag, and G4WeightCutOffProcess::SetParallelWorld().
Referenced by G4GeometrySampler::AddProcess().
const G4VTrackTerminator * G4WeightCutOffConfigurator::GetTrackTerminator () const virtual
Implements G4VSamplerConfigurator.
Definition at line 82 of file G4WeightCutOffConfigurator.cc.
View newest version in sPHENIX GitHub at line 82 of file G4WeightCutOffConfigurator.cc
G4WeightCutOffConfigurator& G4WeightCutOffConfigurator::operator= (const G4WeightCutOffConfigurator &) private
Member Data Documentation
G4bool G4WeightCutOffConfigurator::fPlaced private
Definition at line 76 of file G4WeightCutOffConfigurator.hh.
View newest version in sPHENIX GitHub at line 76 of file G4WeightCutOffConfigurator.hh
Referenced by Configure(), and ~G4WeightCutOffConfigurator().
G4ProcessPlacer G4WeightCutOffConfigurator::fPlacer private
Definition at line 74 of file G4WeightCutOffConfigurator.hh.
View newest version in sPHENIX GitHub at line 74 of file G4WeightCutOffConfigurator.hh
Referenced by Configure(), and ~G4WeightCutOffConfigurator().
G4WeightCutOffProcess* G4WeightCutOffConfigurator::fWeightCutOffProcess private
Definition at line 75 of file G4WeightCutOffConfigurator.hh.
View newest version in sPHENIX GitHub at line 75 of file G4WeightCutOffConfigurator.hh
Referenced by Configure(), G4WeightCutOffConfigurator(), and ~G4WeightCutOffConfigurator().
const G4VPhysicalVolume* G4WeightCutOffConfigurator::fWorld private
Definition at line 73 of file G4WeightCutOffConfigurator.hh.
View newest version in sPHENIX GitHub at line 73 of file G4WeightCutOffConfigurator.hh
Referenced by Configure().
G4bool G4WeightCutOffConfigurator::paraflag private
Definition at line 79 of file G4WeightCutOffConfigurator.hh.
View newest version in sPHENIX GitHub at line 79 of file G4WeightCutOffConfigurator.hh
Referenced by Configure(), and G4WeightCutOffConfigurator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4WeightCutOffConfigurator.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4WeightCutOffConfigurator.cc