ECCE @ EIC Software: G4InitXscPAI Class Reference
G4InitXscPAI Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4InitXscPAI.hh>
Public Member Functions
G4InitXscPAI (const G4MaterialCutsCouple *matCC)
virtual ~G4InitXscPAI ()
void KillCloseIntervals ()
void Normalisation ()
G4double RutherfordIntegral (G4int intervalNumber, G4double limitLow, G4double limitHigh)
G4double IntegralTerm (G4double omega)
G4double ImPartDielectricConst (G4int intervalNumber, G4double energy)
G4double RePartDielectricConst (G4double energy)
G4double ModuleSqDielectricConst (G4int intervalNumber, G4double energy)
G4double DifPAIxSection (G4double omega)
G4double DifPAIdEdx (G4double omega)
G4double PAIdNdxCherenkov (G4double omega)
G4double PAIdNdxPlasmon (G4double omega)
void IntegralPAIxSection (G4double bg2, G4double Tmax)
void IntegralCherenkov (G4double bg2, G4double Tmax)
void IntegralPlasmon (G4double bg2, G4double Tmax)
void IntegralPAIdEdx (G4double bg2, G4double Tmax)
G4double GetPhotonLambda (G4double omega)
G4double GetStepEnergyLoss (G4double step)
G4double GetStepCerenkovLoss (G4double step)
G4double GetStepPlasmonLoss (G4double step)
G4int GetIntervalNumber () const
G4int GetBinPAI () const
G4double GetNormalizationCof () const
G4double GetMatSandiaMatrix (G4int i, G4int j) const
G4PhysicsLogVector * GetPAIxscVector () const
G4PhysicsLogVector * GetPAIdEdxVector () const
G4PhysicsLogVector * GetPAIphotonVector () const
G4PhysicsLogVector * GetPAIelectronVector () const
G4PhysicsLogVector * GetChCosSqVector () const
G4PhysicsLogVector * GetChWidthVector () const
Private Member Functions
G4InitXscPAI & operator= (const G4InitXscPAI &right)=delete
G4InitXscPAI (const G4InitXscPAI &)=delete
Private Attributes
G4int fIntervalNumber
G4double fNormalizationCof
G4int fCurrentInterval
G4int fIntervalTmax
G4double fBetaGammaSq
G4double fTmax
G4double fDensity
G4double fElectronDensity
G4OrderedTable * fMatSandiaMatrix
G4SandiaTable * fSandia
G4PhysicsLogVector * fPAIxscVector
G4PhysicsLogVector * fPAIdEdxVector
G4PhysicsLogVector * fPAIphotonVector
G4PhysicsLogVector * fPAIelectronVector
G4PhysicsLogVector * fChCosSqVector
G4PhysicsLogVector * fChWidthVector
Static Private Attributes
static const G4double fDelta = 0.005
static const G4int fPAIbin = 100
static const G4double fSolidDensity = 0.05*g/cm3
Detailed Description
Definition at line 47 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 47 of file G4InitXscPAI.hh
Constructor & Destructor Documentation
G4InitXscPAI::G4InitXscPAI (const G4MaterialCutsCouple * matCC) explicit
Definition at line 69 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 69 of file G4InitXscPAI.cc
References fBetaGammaSq, fCurrentInterval, fDensity, fElectronDensity, fIntervalNumber, fIntervalTmax, fMatSandiaMatrix, fSandia, fTmax, G4Material::GetDensity(), G4Material::GetElectronDensity(), G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4SandiaTable::GetMaxInterval(), G4SandiaTable::GetSandiaMatTable(), KillCloseIntervals(), and Normalisation().
G4InitXscPAI::~G4InitXscPAI () virtual
Definition at line 114 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 114 of file G4InitXscPAI.cc
References fChCosSqVector, fChWidthVector, fMatSandiaMatrix, fPAIdEdxVector, fPAIelectronVector, fPAIphotonVector, fPAIxscVector, and fSandia.
G4InitXscPAI::G4InitXscPAI (const G4InitXscPAI &) private delete
Member Function Documentation
G4double G4InitXscPAI::DifPAIdEdx (G4double omega)
Definition at line 476 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 476 of file G4InitXscPAI.cc
References DifPAIxSection().
Referenced by IntegralPAIdEdx().
G4double G4InitXscPAI::DifPAIxSection (G4double omega)
Definition at line 413 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 413 of file G4InitXscPAI.cc
References e, source.hepunit::electron_mass_c2, fBetaGammaSq, fCurrentInterval, fDensity, source.hepunit::fine_structure_const, fSolidDensity, source.hepunit::hbarc, ImPartDielectricConst(), IntegralTerm(), pi, RePartDielectricConst(), x1, x2, x3, x4, x5, and x6.
Referenced by DifPAIdEdx(), and IntegralPAIxSection().
G4int G4InitXscPAI::GetBinPAI () const inline
Definition at line 105 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 105 of file G4InitXscPAI.hh
References fPAIbin.
G4PhysicsLogVector* G4InitXscPAI::GetChCosSqVector () const inline
Definition at line 116 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 116 of file G4InitXscPAI.hh
References fChCosSqVector.
G4PhysicsLogVector* G4InitXscPAI::GetChWidthVector () const inline
Definition at line 117 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 117 of file G4InitXscPAI.hh
References fChWidthVector.
G4int G4InitXscPAI::GetIntervalNumber () const inline
Definition at line 104 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 104 of file G4InitXscPAI.hh
References fIntervalNumber.
G4double G4InitXscPAI::GetMatSandiaMatrix (G4int i, G4int j) const inline
Definition at line 109 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 109 of file G4InitXscPAI.hh
References fMatSandiaMatrix.
G4double G4InitXscPAI::GetNormalizationCof () const inline
Definition at line 107 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 107 of file G4InitXscPAI.hh
References fNormalizationCof.
G4PhysicsLogVector* G4InitXscPAI::GetPAIdEdxVector () const inline
Definition at line 113 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 113 of file G4InitXscPAI.hh
References fPAIdEdxVector.
G4PhysicsLogVector* G4InitXscPAI::GetPAIelectronVector () const inline
Definition at line 115 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 115 of file G4InitXscPAI.hh
References fPAIelectronVector.
G4PhysicsLogVector* G4InitXscPAI::GetPAIphotonVector () const inline
Definition at line 114 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 114 of file G4InitXscPAI.hh
References fPAIphotonVector.
G4PhysicsLogVector* G4InitXscPAI::GetPAIxscVector () const inline
Definition at line 112 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 112 of file G4InitXscPAI.hh
References fPAIxscVector.
G4double G4InitXscPAI::GetPhotonLambda (G4double omega)
Definition at line 932 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 932 of file G4InitXscPAI.cc
References fIntervalNumber, fMatSandiaMatrix, G4cout, G4endl, and G4InuclParticleNames::lambda.
G4double G4InitXscPAI::GetStepCerenkovLoss (G4double step)
Definition at line 981 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 981 of file G4InitXscPAI.cc
References Acts::Test::step().
G4double G4InitXscPAI::GetStepEnergyLoss (G4double step)
Definition at line 969 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 969 of file G4InitXscPAI.cc
References Acts::Test::step().
G4double G4InitXscPAI::GetStepPlasmonLoss (G4double step)
Definition at line 993 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 993 of file G4InitXscPAI.cc
References Acts::Test::step().
G4double G4InitXscPAI::ImPartDielectricConst (G4int intervalNumber, G4double energy)
Definition at line 293 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 293 of file G4InitXscPAI.cc
References source.hepunit::hbarc, and k.
Referenced by DifPAIxSection(), IntegralCherenkov(), ModuleSqDielectricConst(), PAIdNdxCherenkov(), and PAIdNdxPlasmon().
void G4InitXscPAI::IntegralCherenkov (G4double bg2, G4double Tmax)
Definition at line 757 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 757 of file G4InitXscPAI.cc
References e, fBetaGammaSq, fChCosSqVector, fChWidthVector, fCurrentInterval, fIntervalNumber, fIntervalTmax, fMatSandiaMatrix, fPAIbin, fPAIphotonVector, fTmax, G4PhysicsVector::GetLowEdgeEnergy(), ImPartDielectricConst(), k, G4Integrator< T, F >::Legendre10(), ModuleSqDielectricConst(), PAIdNdxCherenkov(), G4PhysicsVector::PutValue(), RePartDielectricConst(), and width.
void G4InitXscPAI::IntegralPAIdEdx (G4double bg2, G4double Tmax)
Definition at line 677 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 677 of file G4InitXscPAI.cc
References DifPAIdEdx(), fBetaGammaSq, fCurrentInterval, fIntervalNumber, fIntervalTmax, fMatSandiaMatrix, fPAIbin, fPAIdEdxVector, fTmax, G4PhysicsVector::GetLowEdgeEnergy(), k, G4Integrator< T, F >::Legendre10(), G4PhysicsVector::PutValue(), and return().
void G4InitXscPAI::IntegralPAIxSection (G4double bg2, G4double Tmax)
Definition at line 596 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 596 of file G4InitXscPAI.cc
References DifPAIxSection(), fBetaGammaSq, fCurrentInterval, fIntervalNumber, fIntervalTmax, fMatSandiaMatrix, fPAIbin, fPAIxscVector, fTmax, G4PhysicsVector::GetLowEdgeEnergy(), k, G4Integrator< T, F >::Legendre10(), G4PhysicsVector::PutValue(), and return().
void G4InitXscPAI::IntegralPlasmon (G4double bg2, G4double Tmax)
Definition at line 853 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 853 of file G4InitXscPAI.cc
References fBetaGammaSq, fCurrentInterval, fIntervalNumber, fIntervalTmax, fMatSandiaMatrix, fPAIbin, fPAIelectronVector, fTmax, G4PhysicsVector::GetLowEdgeEnergy(), k, G4Integrator< T, F >::Legendre10(), PAIdNdxPlasmon(), and G4PhysicsVector::PutValue().
G4double G4InitXscPAI::IntegralTerm (G4double omega)
Definition at line 255 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 255 of file G4InitXscPAI.cc
References fIntervalTmax, fMatSandiaMatrix, and RutherfordIntegral().
Referenced by DifPAIxSection(), and PAIdNdxPlasmon().
void G4InitXscPAI::KillCloseIntervals ()
Definition at line 130 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 130 of file G4InitXscPAI.cc
References fDelta, fIntervalNumber, fMatSandiaMatrix, and k.
Referenced by G4InitXscPAI().
G4double G4InitXscPAI::ModuleSqDielectricConst (G4int intervalNumber, G4double energy)
Definition at line 319 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 319 of file G4InitXscPAI.cc
References ImPartDielectricConst(), and RePartDielectricConst().
Referenced by IntegralCherenkov().
void G4InitXscPAI::Normalisation ()
Definition at line 161 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 161 of file G4InitXscPAI.cc
References source.hepunit::electron_mass_c2, fElectronDensity, source.hepunit::fine_structure_const, fIntervalNumber, fNormalizationCof, source.hepunit::hbarc, pi, and RutherfordIntegral().
Referenced by G4InitXscPAI().
G4InitXscPAI& G4InitXscPAI::operator= (const G4InitXscPAI & right) private delete
G4double G4InitXscPAI::PAIdNdxCherenkov (G4double omega)
Definition at line 486 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 486 of file G4InitXscPAI.cc
References e, fBetaGammaSq, fCurrentInterval, fDensity, source.hepunit::fine_structure_const, fSolidDensity, source.hepunit::hbarc, ImPartDielectricConst(), pi, RePartDielectricConst(), x3, and x5.
Referenced by IntegralCherenkov().
G4double G4InitXscPAI::PAIdNdxPlasmon (G4double omega)
Definition at line 550 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 550 of file G4InitXscPAI.cc
References e, source.hepunit::electron_mass_c2, fBetaGammaSq, fCurrentInterval, fDensity, source.hepunit::fine_structure_const, fSolidDensity, source.hepunit::hbarc, ImPartDielectricConst(), IntegralTerm(), pi, and RePartDielectricConst().
Referenced by IntegralPlasmon().
G4double G4InitXscPAI::RePartDielectricConst (G4double energy)
Definition at line 342 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 342 of file G4InitXscPAI.cc
References kdfinder::abs(), c1, c2, fDelta, fIntervalNumber, source.hepunit::hbarc, pi, x1, and x2.
Referenced by DifPAIxSection(), IntegralCherenkov(), ModuleSqDielectricConst(), PAIdNdxCherenkov(), and PAIdNdxPlasmon().
G4double G4InitXscPAI::RutherfordIntegral (G4int intervalNumber, G4double limitLow, G4double limitHigh)
Definition at line 231 of file G4InitXscPAI.cc.
View newest version in sPHENIX GitHub at line 231 of file G4InitXscPAI.cc
References c1, c2, k, x1, and x2.
Referenced by IntegralTerm(), and Normalisation().
Member Data Documentation
G4double G4InitXscPAI::fBetaGammaSq private
Definition at line 136 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 136 of file G4InitXscPAI.hh
Referenced by DifPAIxSection(), G4InitXscPAI(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), IntegralPlasmon(), PAIdNdxCherenkov(), and PAIdNdxPlasmon().
G4PhysicsLogVector* G4InitXscPAI::fChCosSqVector private
Definition at line 152 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 152 of file G4InitXscPAI.hh
Referenced by GetChCosSqVector(), IntegralCherenkov(), and ~G4InitXscPAI().
G4PhysicsLogVector* G4InitXscPAI::fChWidthVector private
Definition at line 153 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 153 of file G4InitXscPAI.hh
Referenced by GetChWidthVector(), IntegralCherenkov(), and ~G4InitXscPAI().
G4int G4InitXscPAI::fCurrentInterval private
Definition at line 134 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 134 of file G4InitXscPAI.hh
Referenced by DifPAIxSection(), G4InitXscPAI(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), IntegralPlasmon(), PAIdNdxCherenkov(), and PAIdNdxPlasmon().
const G4double G4InitXscPAI::fDelta = 0.005 static private
Definition at line 128 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 128 of file G4InitXscPAI.hh
Referenced by KillCloseIntervals(), and RePartDielectricConst().
G4double G4InitXscPAI::fDensity private
Definition at line 138 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 138 of file G4InitXscPAI.hh
Referenced by DifPAIxSection(), G4InitXscPAI(), PAIdNdxCherenkov(), and PAIdNdxPlasmon().
G4double G4InitXscPAI::fElectronDensity private
Definition at line 139 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 139 of file G4InitXscPAI.hh
Referenced by G4InitXscPAI(), and Normalisation().
G4int G4InitXscPAI::fIntervalNumber private
Definition at line 132 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 132 of file G4InitXscPAI.hh
Referenced by G4InitXscPAI(), GetIntervalNumber(), GetPhotonLambda(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), IntegralPlasmon(), KillCloseIntervals(), Normalisation(), and RePartDielectricConst().
G4int G4InitXscPAI::fIntervalTmax private
Definition at line 135 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 135 of file G4InitXscPAI.hh
Referenced by G4InitXscPAI(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), IntegralPlasmon(), and IntegralTerm().
G4OrderedTable* G4InitXscPAI::fMatSandiaMatrix private
Definition at line 143 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 143 of file G4InitXscPAI.hh
Referenced by G4InitXscPAI(), GetMatSandiaMatrix(), GetPhotonLambda(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), IntegralPlasmon(), IntegralTerm(), KillCloseIntervals(), and ~G4InitXscPAI().
G4double G4InitXscPAI::fNormalizationCof private
Definition at line 133 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 133 of file G4InitXscPAI.hh
Referenced by GetNormalizationCof(), and Normalisation().
const G4int G4InitXscPAI::fPAIbin = 100 static private
Definition at line 129 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 129 of file G4InitXscPAI.hh
Referenced by GetBinPAI(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), and IntegralPlasmon().
G4PhysicsLogVector* G4InitXscPAI::fPAIdEdxVector private
Definition at line 149 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 149 of file G4InitXscPAI.hh
Referenced by GetPAIdEdxVector(), IntegralPAIdEdx(), and ~G4InitXscPAI().
G4PhysicsLogVector* G4InitXscPAI::fPAIelectronVector private
Definition at line 151 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 151 of file G4InitXscPAI.hh
Referenced by GetPAIelectronVector(), IntegralPlasmon(), and ~G4InitXscPAI().
G4PhysicsLogVector* G4InitXscPAI::fPAIphotonVector private
Definition at line 150 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 150 of file G4InitXscPAI.hh
Referenced by GetPAIphotonVector(), IntegralCherenkov(), and ~G4InitXscPAI().
G4PhysicsLogVector* G4InitXscPAI::fPAIxscVector private
Definition at line 148 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 148 of file G4InitXscPAI.hh
Referenced by GetPAIxscVector(), IntegralPAIxSection(), and ~G4InitXscPAI().
G4SandiaTable* G4InitXscPAI::fSandia private
Definition at line 144 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 144 of file G4InitXscPAI.hh
Referenced by G4InitXscPAI(), and ~G4InitXscPAI().
const G4double G4InitXscPAI::fSolidDensity = 0.05*g/cm3 static private
Definition at line 130 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 130 of file G4InitXscPAI.hh
Referenced by DifPAIxSection(), PAIdNdxCherenkov(), and PAIdNdxPlasmon().
G4double G4InitXscPAI::fTmax private
Definition at line 137 of file G4InitXscPAI.hh.
View newest version in sPHENIX GitHub at line 137 of file G4InitXscPAI.hh
Referenced by G4InitXscPAI(), IntegralCherenkov(), IntegralPAIdEdx(), IntegralPAIxSection(), and IntegralPlasmon().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4InitXscPAI.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4InitXscPAI.cc