ECCE @ EIC Software: G4PhysicalVolumesSearchScene Class Reference
G4PhysicalVolumesSearchScene Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumesSearchScene.hh>
Classes
struct Findings
class Matcher
Public Member Functions
G4PhysicalVolumesSearchScene (G4PhysicalVolumeModel *pSearchVolumeModel, const G4String &requiredPhysicalVolumeName, G4int requiredCopyNo=-1)
virtual ~G4PhysicalVolumesSearchScene ()
const std::vector< Findings > & GetFindings () const
Public Member Functions inherited from G4PseudoScene
G4PseudoScene ()
virtual ~G4PseudoScene ()
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
void PostAddSolid ()
void AddSolid (const G4Box &solid)
void AddSolid (const G4Cons &solid)
void AddSolid (const G4Orb &solid)
void AddSolid (const G4Para &solid)
void AddSolid (const G4Sphere &solid)
void AddSolid (const G4Torus &solid)
void AddSolid (const G4Trap &solid)
void AddSolid (const G4Trd &solid)
void AddSolid (const G4Tubs &solid)
void AddSolid (const G4Ellipsoid &solid)
void AddSolid (const G4Polycone &solid)
void AddSolid (const G4Polyhedra &solid)
void AddSolid (const G4TessellatedSolid &solid)
void AddSolid (const G4VSolid &solid)
void AddCompound (const G4VTrajectory &)
void AddCompound (const G4VHit &)
void AddCompound (const G4VDigi &)
void AddCompound (const G4THitsMap< G4double > &)
void AddCompound (const G4THitsMap< G4StatDouble > &)
void BeginPrimitives (const G4Transform3D &)
void EndPrimitives ()
void BeginPrimitives2D (const G4Transform3D &)
void EndPrimitives2D ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Scale &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polymarker &)
void AddPrimitive (const G4Polyhedron &)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
virtual const G4VisExtent & GetExtent () const
Private Member Functions
void ProcessVolume (const G4VSolid &)
Private Attributes
const G4PhysicalVolumeModel * fpSearchVolumesModel
Matcher fMatcher
G4int fRequiredCopyNo
std::vector< Findings > fFindings
Additional Inherited Members
Protected Attributes inherited from G4PseudoScene
const G4Transform3D * fpCurrentObjectTransformation
Detailed Description
Definition at line 45 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 45 of file G4PhysicalVolumesSearchScene.hh
Constructor & Destructor Documentation
G4PhysicalVolumesSearchScene::G4PhysicalVolumesSearchScene (G4PhysicalVolumeModel * pSearchVolumeModel, const G4String & requiredPhysicalVolumeName, G4int requiredCopyNo = -1)
Definition at line 39 of file G4PhysicalVolumesSearchScene.cc.
View newest version in sPHENIX GitHub at line 39 of file G4PhysicalVolumesSearchScene.cc
virtual G4PhysicalVolumesSearchScene::~G4PhysicalVolumesSearchScene () inline virtual
Definition at line 54 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 54 of file G4PhysicalVolumesSearchScene.hh
Member Function Documentation
const std::vector<Findings>& G4PhysicalVolumesSearchScene::GetFindings () const inline
Definition at line 89 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PhysicalVolumesSearchScene.hh
References fFindings.
Referenced by G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
void G4PhysicalVolumesSearchScene::ProcessVolume (const G4VSolid &) private virtual
Implements G4PseudoScene.
Definition at line 47 of file G4PhysicalVolumesSearchScene.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PhysicalVolumesSearchScene.cc
References fFindings, fMatcher, G4PseudoScene::fpCurrentObjectTransformation, fpSearchVolumesModel, fRequiredCopyNo, G4PhysicalVolumeModel::GetCurrentDepth(), G4PhysicalVolumeModel::GetCurrentPV(), G4PhysicalVolumeModel::GetCurrentPVCopyNo(), G4PhysicalVolumeModel::GetFullPVPath(), G4VPhysicalVolume::GetName(), G4PhysicalVolumeModel::GetTopPhysicalVolume(), and G4PhysicalVolumesSearchScene::Matcher::Match().
Member Data Documentation
std::vector<Findings> G4PhysicalVolumesSearchScene::fFindings private
Definition at line 111 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 111 of file G4PhysicalVolumesSearchScene.hh
Referenced by GetFindings(), and ProcessVolume().
Matcher G4PhysicalVolumesSearchScene::fMatcher private
Definition at line 109 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 109 of file G4PhysicalVolumesSearchScene.hh
Referenced by ProcessVolume().
const G4PhysicalVolumeModel* G4PhysicalVolumesSearchScene::fpSearchVolumesModel private
Definition at line 108 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PhysicalVolumesSearchScene.hh
Referenced by ProcessVolume().
G4int G4PhysicalVolumesSearchScene::fRequiredCopyNo private
Definition at line 110 of file G4PhysicalVolumesSearchScene.hh.
View newest version in sPHENIX GitHub at line 110 of file G4PhysicalVolumesSearchScene.hh
Referenced by ProcessVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumesSearchScene.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4PhysicalVolumesSearchScene.cc