ECCE @ EIC Software: B3aRunAction Class Reference
B3aRunAction Class Reference
Run action class.
#include <geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3aRunAction.hh>
Public Member Functions
B3aRunAction ()
virtual ~B3aRunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void CountEvent ()
void SumDose (G4double dose)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4Accumulable< G4int > fGoodEvents
G4Accumulable< G4double > fSumDose
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Run action class.
Definition at line 39 of file B3aRunAction.hh.
View newest version in sPHENIX GitHub at line 39 of file B3aRunAction.hh
Constructor & Destructor Documentation
B3aRunAction::B3aRunAction ()
Definition at line 41 of file B3aRunAction.cc.
View newest version in sPHENIX GitHub at line 41 of file B3aRunAction.cc
References fGoodEvents, fSumDose, gray, G4AccumulableManager::Instance(), microgray, milligray, and G4AccumulableManager::RegisterAccumulable().
B3aRunAction::~B3aRunAction () virtual
Definition at line 66 of file B3aRunAction.cc.
View newest version in sPHENIX GitHub at line 66 of file B3aRunAction.cc
Member Function Documentation
void B3aRunAction::BeginOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 71 of file B3aRunAction.cc.
View newest version in sPHENIX GitHub at line 71 of file B3aRunAction.cc
References G4cout, G4endl, G4Run::GetRunID(), G4RunManager::GetRunManager(), G4AccumulableManager::Instance(), G4AccumulableManager::Reset(), and G4RunManager::SetRandomNumberStore().
void B3aRunAction::CountEvent () inline
Definition at line 48 of file B3aRunAction.hh.
View newest version in sPHENIX GitHub at line 48 of file B3aRunAction.hh
References fGoodEvents.
Referenced by B3aEventAction::EndOfEventAction().
void B3aRunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 85 of file B3aRunAction.cc.
View newest version in sPHENIX GitHub at line 85 of file B3aRunAction.cc
References fGoodEvents, fSumDose, G4BestUnit, G4cout, G4endl, G4Run::GetNumberOfEvent(), G4ParticleGun::GetParticleDefinition(), B3PrimaryGeneratorAction::GetParticleGun(), G4ParticleDefinition::GetParticleName(), G4RunManager::GetRunManager(), G4RunManager::GetUserPrimaryGeneratorAction(), G4Accumulable< T >::GetValue(), G4AccumulableManager::Instance(), G4UserRunAction::IsMaster(), G4AccumulableManager::Merge(), and particle.
void B3aRunAction::SumDose (G4double dose) inline
Definition at line 49 of file B3aRunAction.hh.
View newest version in sPHENIX GitHub at line 49 of file B3aRunAction.hh
References dose, and fSumDose.
Referenced by B3aEventAction::EndOfEventAction().
Member Data Documentation
G4Accumulable<G4int> B3aRunAction::fGoodEvents private
Definition at line 49 of file B3aRunAction.hh.
View newest version in sPHENIX GitHub at line 49 of file B3aRunAction.hh
Referenced by B3aRunAction(), CountEvent(), and EndOfRunAction().
G4Accumulable<G4double> B3aRunAction::fSumDose private
Definition at line 53 of file B3aRunAction.hh.
View newest version in sPHENIX GitHub at line 53 of file B3aRunAction.hh
Referenced by B3aRunAction(), EndOfRunAction(), and SumDose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3aRunAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/src/B3aRunAction.cc