ECCE @ EIC Software: macros/blob/master/common/G4_FST_EIC.C File Reference
G4_FST_EIC.C File Reference
#include "GlobalVariables.C"
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4main/PHG4Reco.h>
#include <string>
Namespaces
namespace Enable
namespace G4FST
namespace G4FST::SETTING
Macros
#define MACRO_G4FSTEIC_C
Functions
int make_LANL_FST_station (string name, PHG4Reco *g4Reco, double zpos, double Rmin, double Rmax, double tSilicon, double pitch)
int make_supportCyl (string name, PHG4Reco *g4Reco, double r, double t, double length)
void FST_Init ()
void FSTSetup (PHG4Reco *g4Reco)
Variables
static bool Enable::FST = false
bool Enable::FST_OVERLAPCHECK = false
bool G4FST::SETTING::FST_TPC = false
bool G4FST::SETTING::SUPPORTCYL = false
Macro Definition Documentation
#define MACRO_G4FSTEIC_C
Definition at line 10 of file G4_FST_EIC.C.
View newest version in sPHENIX GitHub at line 10 of file G4_FST_EIC.C
Function Documentation
void FST_Init ()
Definition at line 45 of file G4_FST_EIC.C.
View newest version in sPHENIX GitHub at line 45 of file G4_FST_EIC.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and G4FST::SETTING::SUPPORTCYL.
Referenced by G4Init().
void FSTSetup (PHG4Reco * g4Reco)
Definition at line 63 of file G4_FST_EIC.C.
View newest version in sPHENIX GitHub at line 63 of file G4_FST_EIC.C
References cm, e, BlackHoleGeometry::gap, make_LANL_FST_station(), make_supportCyl(), mm, G4FST::SETTING::SUPPORTCYL, um, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup().
int make_LANL_FST_station (string name, PHG4Reco * g4Reco, double zpos, double Rmin, double Rmax, double tSilicon, double pitch)
Definition at line 121 of file G4_FST_EIC.C.
View newest version in sPHENIX GitHub at line 121 of file G4_FST_EIC.C
References PHG4TrackFastSim::add_phg4hits(), PHG4Sector::Sector_Geometry::AddLayer(), cm, PHG4Sector::Sector_Geometry::ConeEdge(), e, TRACKING::FastKalmanFilter(), TRACKING::FastKalmanFilterInnerTrack(), TRACKING::FastKalmanFilterSiliconTrack(), Enable::FST_OVERLAPCHECK, PHG4SectorSubsystem::get_geometry(), M_PI, mm, Enable::OVERLAPCHECK, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, um, PHG4Sector::Sector_Geometry::Unit_cm(), PHG4TrackFastSim::Vertical_Plane, and BTOF::zpos.
Referenced by FSTSetup().
int make_supportCyl (string name, PHG4Reco * g4Reco, double r, double t, double length)
Definition at line 199 of file G4_FST_EIC.C.
View newest version in sPHENIX GitHub at line 199 of file G4_FST_EIC.C
References Enable::FST_OVERLAPCHECK, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), and PHG4DetectorSubsystem::SetActive().
Referenced by FSTSetup().