ECCE @ EIC Software: G4TouchableHistory Class Reference
G4TouchableHistory Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4TouchableHistory.hh>
Public Member Functions
G4TouchableHistory ()
G4TouchableHistory (const G4NavigationHistory &history)
~G4TouchableHistory ()
G4VPhysicalVolume * GetVolume (G4int depth=0) const
G4VSolid * GetSolid (G4int depth=0) const
const G4ThreeVector & GetTranslation (G4int depth=0) const
const G4RotationMatrix * GetRotation (G4int depth=0) const
G4int GetReplicaNumber (G4int depth=0) const
G4int GetHistoryDepth () const
G4int MoveUpHistory (G4int num_levels=1)
void UpdateYourself (G4VPhysicalVolume *pPhysVol, const G4NavigationHistory *history=nullptr)
const G4NavigationHistory * GetHistory () const
void * operator new (size_t)
void operator delete (void *aTH)
Public Member Functions inherited from G4VTouchable
G4VTouchable ()
virtual ~G4VTouchable ()
G4int GetCopyNumber (G4int depth=0) const
Private Member Functions
G4int CalculateHistoryIndex (G4int stackDepth) const
Private Attributes
G4RotationMatrix frot
G4ThreeVector ftlate
G4NavigationHistory fhistory
Detailed Description
Definition at line 48 of file G4TouchableHistory.hh.
View newest version in sPHENIX GitHub at line 48 of file G4TouchableHistory.hh
Constructor & Destructor Documentation
G4TouchableHistory::G4TouchableHistory ()
Definition at line 39 of file G4TouchableHistory.cc.
View newest version in sPHENIX GitHub at line 39 of file G4TouchableHistory.cc
References fhistory, and G4NavigationHistory::SetFirstEntry().
G4TouchableHistory::G4TouchableHistory (const G4NavigationHistory & history)
Definition at line 47 of file G4TouchableHistory.cc.
View newest version in sPHENIX GitHub at line 47 of file G4TouchableHistory.cc
References fhistory, frot, ftlate, G4NavigationHistory::GetTopTransform(), G4AffineTransform::InverseNetRotation(), and G4AffineTransform::InverseNetTranslation().
G4TouchableHistory::~G4TouchableHistory ()
Definition at line 55 of file G4TouchableHistory.cc.
View newest version in sPHENIX GitHub at line 55 of file G4TouchableHistory.cc
Member Function Documentation
G4int G4TouchableHistory::CalculateHistoryIndex (G4int stackDepth) const inline private
Referenced by GetRotation(), and GetTranslation().
const G4NavigationHistory* G4TouchableHistory::GetHistory () const inline virtual
Reimplemented from G4VTouchable.
Referenced by F04ElementField::Construct(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4PathFinder::CreateTouchableHandle(), G4ITPathFinder::CreateTouchableHandle(), G4MultiNavigator::CreateTouchableHistoryHandle(), G4ITMultiNavigator::CreateTouchableHistoryHandle(), G4DrawVoxels::DrawVoxels(), G4FastTrack::FRecordsAffineTransformation(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4ITNavigator2::NewNavigatorState(), ExN04CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), WLSPhotonDetSD::ProcessHits_constStep(), G4Navigator::ResetHierarchyAndLocate(), G4ITNavigator1::ResetHierarchyAndLocate(), and G4ITNavigator2::ResetHierarchyAndLocate().
G4int G4TouchableHistory::GetHistoryDepth () const inline virtual
Reimplemented from G4VTouchable.
Referenced by F04ElementField::Construct(), CCaloSD::createNewHit(), CCalHcalOrganization::GetUnitID(), CCalEcalOrganization::GetUnitID(), and CCalVOrganization::Levels().
G4int G4TouchableHistory::GetReplicaNumber (G4int depth = 0) const inline virtual
Reimplemented from G4VTouchable.
Referenced by CCaloSD::createNewHit(), CCalVOrganization::DetectorLevel(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4VPrimitiveScorer::GetIndex(), CCalHcalOrganization::GetUnitID(), CCalEcalOrganization::GetUnitID(), and Par01CalorimeterSD::ProcessHits().
const G4RotationMatrix * G4TouchableHistory::GetRotation (G4int depth = 0) const virtual
Implements G4VTouchable.
Definition at line 80 of file G4TouchableHistory.cc.
View newest version in sPHENIX GitHub at line 80 of file G4TouchableHistory.cc
References CalculateHistoryIndex(), fhistory, frot, G4ThreadLocal, G4NavigationHistory::GetTransform(), and G4AffineTransform::NetRotation().
Referenced by G4Channeling::PosToLattice(), G4Channeling::PostStepDoIt(), and G4Channeling::UpdateParameters().
G4VSolid* G4TouchableHistory::GetSolid (G4int depth = 0) const inline virtual
Reimplemented from G4VTouchable.
Referenced by G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck().
const G4ThreeVector & G4TouchableHistory::GetTranslation (G4int depth = 0) const virtual
Implements G4VTouchable.
Definition at line 60 of file G4TouchableHistory.cc.
View newest version in sPHENIX GitHub at line 60 of file G4TouchableHistory.cc
References CalculateHistoryIndex(), fhistory, ftlate, G4ThreadLocal, G4NavigationHistory::GetTransform(), and G4AffineTransform::NetTranslation().
Referenced by G4Channeling::PosToLattice().
G4VPhysicalVolume* G4TouchableHistory::GetVolume (G4int depth = 0) const inline virtual
Reimplemented from G4VTouchable.
Referenced by F04ElementField::Construct(), CCalVOrganization::DetectorLevel(), G4VReadOutGeometry::FindROTouchable(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), Par01CalorimeterSD::ProcessHits(), LXeScintSD::ProcessHits(), ExGflash1SensitiveDetector::ProcessHits(), ExGflash2SensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), F02CalorimeterSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), XrayFluoSD::ProcessHits(), and FCALSteppingAction::UserSteppingAction().
G4int G4TouchableHistory::MoveUpHistory (G4int num_levels = 1) virtual
Reimplemented from G4VTouchable.
Referenced by F04ElementField::Construct(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
void G4TouchableHistory::operator delete (void * aTH) inline
void* G4TouchableHistory::operator new (size_t) inline
void G4TouchableHistory::UpdateYourself (G4VPhysicalVolume * pPhysVol, const G4NavigationHistory * history = nullptr) virtual
Reimplemented from G4VTouchable.
Referenced by G4PathFinder::CreateTouchableHandle(), G4ITPathFinder::CreateTouchableHandle(), G4MultiNavigator::CreateTouchableHistoryHandle(), and G4ITMultiNavigator::CreateTouchableHistoryHandle().
Member Data Documentation
G4NavigationHistory G4TouchableHistory::fhistory private
Definition at line 94 of file G4TouchableHistory.hh.
View newest version in sPHENIX GitHub at line 94 of file G4TouchableHistory.hh
Referenced by G4TouchableHistory(), GetRotation(), and GetTranslation().
G4RotationMatrix G4TouchableHistory::frot private
Definition at line 92 of file G4TouchableHistory.hh.
View newest version in sPHENIX GitHub at line 92 of file G4TouchableHistory.hh
Referenced by G4TouchableHistory(), and GetRotation().
G4ThreeVector G4TouchableHistory::ftlate private
Definition at line 93 of file G4TouchableHistory.hh.
View newest version in sPHENIX GitHub at line 93 of file G4TouchableHistory.hh
Referenced by G4TouchableHistory(), and GetTranslation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4TouchableHistory.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4TouchableHistory.cc