ECCE @ EIC Software: ExN04EventAction Class Reference
ExN04EventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04EventAction.hh>
Public Member Functions
ExN04EventAction ()
~ExN04EventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
ExN04EventAction ()
~ExN04EventAction ()
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4int ftrackerCollID
G4int fcalorimeterCollID
G4int fmuonCollID
G4int trackerCollID
G4int calorimeterCollID
G4int muonCollID
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 37 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 37 of file ExN04EventAction.hh
Constructor & Destructor Documentation
ExN04EventAction::ExN04EventAction ()
Definition at line 45 of file ExN04EventAction.cc.
View newest version in sPHENIX GitHub at line 45 of file ExN04EventAction.cc
ExN04EventAction::~ExN04EventAction ()
Definition at line 54 of file ExN04EventAction.cc.
View newest version in sPHENIX GitHub at line 54 of file ExN04EventAction.cc
ExN04EventAction::ExN04EventAction ()
ExN04EventAction::~ExN04EventAction ()
Member Function Documentation
void ExN04EventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Definition at line 59 of file ExN04EventAction.cc.
View newest version in sPHENIX GitHub at line 59 of file ExN04EventAction.cc
References fcalorimeterCollID, fmuonCollID, ftrackerCollID, and G4SDManager::GetSDMpointer().
void ExN04EventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
void ExN04EventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 71 of file ExN04EventAction.cc.
View newest version in sPHENIX GitHub at line 71 of file ExN04EventAction.cc
References fcalorimeterCollID, fmuonCollID, ftrackerCollID, G4cout, G4endl, G4Event::GetEventID(), G4HCofThisEvent::GetHC(), and GeV.
void ExN04EventAction::EndOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Member Data Documentation
G4int ExN04EventAction::calorimeterCollID private
Definition at line 49 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 49 of file ExN04EventAction.hh
G4int ExN04EventAction::fcalorimeterCollID private
Definition at line 47 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 47 of file ExN04EventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
G4int ExN04EventAction::fmuonCollID private
Definition at line 48 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN04EventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
G4int ExN04EventAction::ftrackerCollID private
Definition at line 46 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 46 of file ExN04EventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
G4int ExN04EventAction::muonCollID private
Definition at line 50 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 50 of file ExN04EventAction.hh
G4int ExN04EventAction::trackerCollID private
Definition at line 48 of file ExN04EventAction.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN04EventAction.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04EventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04EventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04EventAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04EventAction.cc