ECCE @ EIC Software: G4NuclearPolarizationStore Class Reference
G4NuclearPolarizationStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4NuclearPolarizationStore.hh>
Public Member Functions
~G4NuclearPolarizationStore ()
void Register (G4NuclearPolarization *ptr)
G4NuclearPolarization * FindOrBuild (G4int Z, G4int A, G4double Eexc)
void RemoveMe (G4NuclearPolarization *ptr)
Static Public Member Functions
static G4NuclearPolarizationStore * GetInstance ()
Private Member Functions
G4NuclearPolarizationStore ()
Private Attributes
G4NuclearPolarization * nuclist [maxNumStates]
G4int oldIdx
Static Private Attributes
static G4ThreadLocal
G4NuclearPolarizationStore * instance = nullptr
Friends
class G4ThreadLocalSingleton< G4NuclearPolarizationStore >
Detailed Description
Definition at line 45 of file G4NuclearPolarizationStore.hh.
View newest version in sPHENIX GitHub at line 45 of file G4NuclearPolarizationStore.hh
Constructor & Destructor Documentation
G4NuclearPolarizationStore::~G4NuclearPolarizationStore ()
Definition at line 51 of file G4NuclearPolarizationStore.cc.
View newest version in sPHENIX GitHub at line 51 of file G4NuclearPolarizationStore.cc
References maxNumStates, and nuclist.
G4NuclearPolarizationStore::G4NuclearPolarizationStore () private
Definition at line 45 of file G4NuclearPolarizationStore.cc.
View newest version in sPHENIX GitHub at line 45 of file G4NuclearPolarizationStore.cc
References maxNumStates, nuclist, and oldIdx.
Member Function Documentation
G4NuclearPolarization * G4NuclearPolarizationStore::FindOrBuild (G4int Z, G4int A, G4double Eexc)
Definition at line 79 of file G4NuclearPolarizationStore.cc.
View newest version in sPHENIX GitHub at line 79 of file G4NuclearPolarizationStore.cc
References kdfinder::abs(), CLHEP::eV, maxNumStates, nuclist, and Register().
Referenced by G4PhotonEvaporation::EmittedFragment().
G4NuclearPolarizationStore * G4NuclearPolarizationStore::GetInstance (void) static
Definition at line 36 of file G4NuclearPolarizationStore.cc.
View newest version in sPHENIX GitHub at line 36 of file G4NuclearPolarizationStore.cc
References instance, and G4ThreadLocalSingleton< T >::Instance().
Referenced by G4PhotonEvaporation::EmittedFragment().
void G4NuclearPolarizationStore::Register (G4NuclearPolarization * ptr)
Definition at line 59 of file G4NuclearPolarizationStore.cc.
View newest version in sPHENIX GitHub at line 59 of file G4NuclearPolarizationStore.cc
References incremental_prev_tag::idx, maxNumStates, nuclist, and oldIdx.
Referenced by FindOrBuild().
void G4NuclearPolarizationStore::RemoveMe (G4NuclearPolarization * ptr)
Definition at line 94 of file G4NuclearPolarizationStore.cc.
View newest version in sPHENIX GitHub at line 94 of file G4NuclearPolarizationStore.cc
References maxNumStates, nuclist, and oldIdx.
Referenced by G4PhotonEvaporation::EmittedFragment().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4NuclearPolarizationStore > friend
Definition at line 47 of file G4NuclearPolarizationStore.hh.
View newest version in sPHENIX GitHub at line 47 of file G4NuclearPolarizationStore.hh
Member Data Documentation
G4ThreadLocal G4NuclearPolarizationStore * G4NuclearPolarizationStore::instance = nullptr static private
Definition at line 69 of file G4NuclearPolarizationStore.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NuclearPolarizationStore.hh
Referenced by GetInstance().
G4NuclearPolarization* G4NuclearPolarizationStore::nuclist[maxNumStates] private
Definition at line 71 of file G4NuclearPolarizationStore.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NuclearPolarizationStore.hh
Referenced by FindOrBuild(), G4NuclearPolarizationStore(), Register(), RemoveMe(), and ~G4NuclearPolarizationStore().
G4int G4NuclearPolarizationStore::oldIdx private
Definition at line 72 of file G4NuclearPolarizationStore.hh.
View newest version in sPHENIX GitHub at line 72 of file G4NuclearPolarizationStore.hh
Referenced by G4NuclearPolarizationStore(), Register(), and RemoveMe().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4NuclearPolarizationStore.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4NuclearPolarizationStore.cc