ECCE @ EIC Software: ExGflashHit Class Reference
ExGflashHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflashHit.hh>
Public Member Functions
ExGflashHit ()
ExGflashHit (G4LogicalVolume *logVol)
~ExGflashHit ()
ExGflashHit (const ExGflashHit &right)
const ExGflashHit & operator= (const ExGflashHit &right)
G4bool operator== (const ExGflashHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
void * operator new (size_t, void *p)
void operator delete (void *, void *)
virtual void Draw ()
virtual void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4int GetCrystalNum ()
void SetCrystalNum (G4int num)
G4ThreeVector GetPos ()
void SetStart (G4ThreeVector xyz)
G4ThreeVector GetStart ()
void SetRot (G4RotationMatrix rmat)
G4RotationMatrix GetRot ()
const G4LogicalVolume * GetLogV ()
ExGflashHit ()
ExGflashHit (G4LogicalVolume *logVol)
~ExGflashHit ()
ExGflashHit (const ExGflashHit &right)
const ExGflashHit & operator= (const ExGflashHit &right)
G4bool operator== (const ExGflashHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
void * operator new (size_t, void *p)
void operator delete (void *, void *)
virtual void Draw ()
virtual void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4int GetCrystalNum ()
void SetCrystalNum (G4int num)
G4ThreeVector GetPos ()
void SetStart (G4ThreeVector xyz)
G4ThreeVector GetStart ()
void SetRot (G4RotationMatrix rmat)
G4RotationMatrix GetRot ()
const G4LogicalVolume * GetLogV ()
ExGflashHit ()
ExGflashHit (G4LogicalVolume *logVol)
~ExGflashHit ()
ExGflashHit (const ExGflashHit &right)
const ExGflashHit & operator= (const ExGflashHit &right)
G4bool operator== (const ExGflashHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
void * operator new (size_t, void *p)
void operator delete (void *, void *)
virtual void Draw ()
virtual void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4int GetCrystalNum ()
void SetCrystalNum (G4int num)
G4ThreeVector GetPos ()
void SetStart (G4ThreeVector xyz)
G4ThreeVector GetStart ()
void SetRot (G4RotationMatrix rmat)
G4RotationMatrix GetRot ()
const G4LogicalVolume * GetLogV ()
ExGflashHit ()
~ExGflashHit ()
ExGflashHit (const ExGflashHit &right)
const ExGflashHit & operator= (const ExGflashHit &right)
G4bool operator== (const ExGflashHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
void * operator new (size_t, void *p)
void operator delete (void *, void *)
virtual void Draw ()
virtual void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos ()
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
G4double fEdep
G4ThreeVector fPos
G4int fCrystalNumber
G4ThreeVector fStart
G4RotationMatrix fRot
const G4LogicalVolume * fLogV
Detailed Description
Definition at line 41 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 41 of file ExGflashHit.hh
Constructor & Destructor Documentation
ExGflashHit::ExGflashHit ()
Definition at line 45 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 45 of file ExGflashHit.cc
ExGflashHit::ExGflashHit (G4LogicalVolume * logVol)
Definition at line 51 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 51 of file ExGflashHit.cc
ExGflashHit::~ExGflashHit ()
Definition at line 57 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 57 of file ExGflashHit.cc
ExGflashHit::ExGflashHit (const ExGflashHit & right)
Definition at line 62 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 62 of file ExGflashHit.cc
References fCrystalNumber, fEdep, fLogV, fPos, fRot, and fStart.
ExGflashHit::ExGflashHit ()
ExGflashHit::ExGflashHit (G4LogicalVolume * logVol)
ExGflashHit::~ExGflashHit ()
ExGflashHit::ExGflashHit (const ExGflashHit & right)
ExGflashHit::ExGflashHit ()
ExGflashHit::ExGflashHit (G4LogicalVolume * logVol)
ExGflashHit::~ExGflashHit ()
ExGflashHit::ExGflashHit (const ExGflashHit & right)
ExGflashHit::ExGflashHit ()
ExGflashHit::~ExGflashHit ()
ExGflashHit::ExGflashHit (const ExGflashHit & right)
Member Function Documentation
void ExGflashHit::AddEdep (G4double de) inline
Definition at line 68 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 68 of file ExGflashHit.hh
References fEdep.
void ExGflashHit::AddEdep (G4double de) inline
Definition at line 73 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 73 of file ExGflashHit.hh
References fEdep.
void ExGflashHit::AddEdep (G4double de) inline
Definition at line 73 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 73 of file ExGflashHit.hh
References fEdep.
void ExGflashHit::AddEdep (G4double de) inline
Definition at line 73 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 73 of file ExGflashHit.hh
References fEdep.
virtual void ExGflashHit::Draw () virtual
Reimplemented from G4VHit.
void ExGflashHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 101 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 101 of file ExGflashHit.cc
References G4VVisManager::Draw(), fLogV, fPos, fRot, G4VVisManager::GetConcreteInstance(), G4LogicalVolume::GetVisAttributes(), G4VisAttributes::SetColour(), G4VisAttributes::SetForceSolid(), and G4VisAttributes::SetForceWireframe().
virtual void ExGflashHit::Draw () virtual
Reimplemented from G4VHit.
virtual void ExGflashHit::Draw () virtual
Reimplemented from G4VHit.
G4int ExGflashHit::GetCrystalNum () inline
Definition at line 79 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 79 of file ExGflashHit.hh
References fCrystalNumber.
G4int ExGflashHit::GetCrystalNum () inline
Definition at line 79 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 79 of file ExGflashHit.hh
References fCrystalNumber.
G4int ExGflashHit::GetCrystalNum () inline
Definition at line 79 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 79 of file ExGflashHit.hh
References fCrystalNumber.
G4double ExGflashHit::GetEdep () inline
Definition at line 70 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 70 of file ExGflashHit.hh
References fEdep.
G4double ExGflashHit::GetEdep () inline
Definition at line 75 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 75 of file ExGflashHit.hh
References fEdep.
G4double ExGflashHit::GetEdep () inline
Definition at line 75 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 75 of file ExGflashHit.hh
References fEdep.
G4double ExGflashHit::GetEdep () inline
Definition at line 75 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 75 of file ExGflashHit.hh
References fEdep.
const G4LogicalVolume* ExGflashHit::GetLogV () inline
Definition at line 94 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 94 of file ExGflashHit.hh
References fLogV.
const G4LogicalVolume* ExGflashHit::GetLogV () inline
Definition at line 94 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 94 of file ExGflashHit.hh
References fLogV.
const G4LogicalVolume* ExGflashHit::GetLogV () inline
Definition at line 94 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 94 of file ExGflashHit.hh
References fLogV.
G4ThreeVector ExGflashHit::GetPos () inline
Definition at line 74 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 74 of file ExGflashHit.hh
References fPos.
G4ThreeVector ExGflashHit::GetPos () inline
Definition at line 83 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 83 of file ExGflashHit.hh
References fPos.
G4ThreeVector ExGflashHit::GetPos () inline
Definition at line 83 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 83 of file ExGflashHit.hh
References fPos.
G4ThreeVector ExGflashHit::GetPos () inline
Definition at line 83 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 83 of file ExGflashHit.hh
References fPos.
G4RotationMatrix ExGflashHit::GetRot () inline
Definition at line 92 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 92 of file ExGflashHit.hh
References fRot.
G4RotationMatrix ExGflashHit::GetRot () inline
Definition at line 92 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 92 of file ExGflashHit.hh
References fRot.
G4RotationMatrix ExGflashHit::GetRot () inline
Definition at line 92 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 92 of file ExGflashHit.hh
References fRot.
G4ThreeVector ExGflashHit::GetStart () inline
Definition at line 87 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 87 of file ExGflashHit.hh
References fStart.
G4ThreeVector ExGflashHit::GetStart () inline
Definition at line 87 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 87 of file ExGflashHit.hh
References fStart.
G4ThreeVector ExGflashHit::GetStart () inline
Definition at line 87 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 87 of file ExGflashHit.hh
References fStart.
void ExGflashHit::operator delete (void * aHit) inline
void ExGflashHit::operator delete (void * aHit) inline
void ExGflashHit::operator delete (void * aHit) inline
void ExGflashHit::operator delete (void * aHit) inline
Definition at line 108 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 108 of file ExGflashHit.hh
References ExGflashHitAllocator.
void ExGflashHit::operator delete (void * , void *) inline
Definition at line 55 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 55 of file ExGflashHit.hh
void ExGflashHit::operator delete (void * , void *) inline
Definition at line 56 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 56 of file ExGflashHit.hh
void ExGflashHit::operator delete (void * , void *) inline
Definition at line 56 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 56 of file ExGflashHit.hh
void ExGflashHit::operator delete (void * , void *) inline
Definition at line 56 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 56 of file ExGflashHit.hh
void* ExGflashHit::operator new (size_t) inline
void* ExGflashHit::operator new (size_t) inline
void * ExGflashHit::operator new (size_t) inline
Definition at line 102 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 102 of file ExGflashHit.hh
References ExGflashHitAllocator.
void* ExGflashHit::operator new (size_t) inline
void* ExGflashHit::operator new (size_t , void * p) inline
Definition at line 53 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 53 of file ExGflashHit.hh
void* ExGflashHit::operator new (size_t , void * p) inline
Definition at line 54 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 54 of file ExGflashHit.hh
void* ExGflashHit::operator new (size_t , void * p) inline
Definition at line 54 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 54 of file ExGflashHit.hh
void* ExGflashHit::operator new (size_t , void * p) inline
Definition at line 54 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 54 of file ExGflashHit.hh
const ExGflashHit& ExGflashHit::operator= (const ExGflashHit & right)
const ExGflashHit& ExGflashHit::operator= (const ExGflashHit & right)
const ExGflashHit& ExGflashHit::operator= (const ExGflashHit & right)
const ExGflashHit & ExGflashHit::operator= (const ExGflashHit & right)
Definition at line 76 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 76 of file ExGflashHit.cc
References fCrystalNumber, fEdep, fLogV, fPos, fRot, and fStart.
G4bool ExGflashHit::operator== (const ExGflashHit & right) const
G4bool ExGflashHit::operator== (const ExGflashHit & right) const
G4bool ExGflashHit::operator== (const ExGflashHit & right) const
Definition at line 91 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 91 of file ExGflashHit.cc
References fEdep, and fPos.
G4bool ExGflashHit::operator== (const ExGflashHit & right) const
virtual void ExGflashHit::Print () virtual
Reimplemented from G4VHit.
void ExGflashHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 120 of file ExGflashHit.cc.
View newest version in sPHENIX GitHub at line 120 of file ExGflashHit.cc
virtual void ExGflashHit::Print () virtual
Reimplemented from G4VHit.
virtual void ExGflashHit::Print () virtual
Reimplemented from G4VHit.
void ExGflashHit::SetCrystalNum (G4int num) inline
Definition at line 81 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 81 of file ExGflashHit.hh
References fCrystalNumber, and num.
void ExGflashHit::SetCrystalNum (G4int num) inline
Definition at line 81 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 81 of file ExGflashHit.hh
References fCrystalNumber, and num.
void ExGflashHit::SetCrystalNum (G4int num) inline
Definition at line 81 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 81 of file ExGflashHit.hh
References fCrystalNumber, and num.
Referenced by ExGflash1SensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash2SensitiveDetector::ProcessHits().
void ExGflashHit::SetEdep (G4double de) inline
Definition at line 66 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 66 of file ExGflashHit.hh
References fEdep.
void ExGflashHit::SetEdep (G4double de) inline
Definition at line 71 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 71 of file ExGflashHit.hh
References fEdep.
void ExGflashHit::SetEdep (G4double de) inline
Definition at line 71 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 71 of file ExGflashHit.hh
References fEdep.
void ExGflashHit::SetEdep (G4double de) inline
Definition at line 71 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 71 of file ExGflashHit.hh
References fEdep.
Referenced by ExGflash1SensitiveDetector::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash2SensitiveDetector::ProcessHits().
void ExGflashHit::SetPos (G4ThreeVector xyz) inline
Definition at line 72 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 72 of file ExGflashHit.hh
References fPos.
void ExGflashHit::SetPos (G4ThreeVector xyz) inline
Definition at line 77 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 77 of file ExGflashHit.hh
References fPos.
Referenced by ExGflash1SensitiveDetector::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), and ExGflash2SensitiveDetector::ProcessHits().
void ExGflashHit::SetPos (G4ThreeVector xyz) inline
Definition at line 77 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 77 of file ExGflashHit.hh
References fPos.
void ExGflashHit::SetPos (G4ThreeVector xyz) inline
Definition at line 77 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 77 of file ExGflashHit.hh
References fPos.
void ExGflashHit::SetRot (G4RotationMatrix rmat) inline
Definition at line 90 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 90 of file ExGflashHit.hh
References fRot.
void ExGflashHit::SetRot (G4RotationMatrix rmat) inline
Definition at line 90 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 90 of file ExGflashHit.hh
References fRot.
void ExGflashHit::SetRot (G4RotationMatrix rmat) inline
Definition at line 90 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 90 of file ExGflashHit.hh
References fRot.
void ExGflashHit::SetStart (G4ThreeVector xyz) inline
Definition at line 85 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 85 of file ExGflashHit.hh
References fStart.
void ExGflashHit::SetStart (G4ThreeVector xyz) inline
Definition at line 85 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 85 of file ExGflashHit.hh
References fStart.
void ExGflashHit::SetStart (G4ThreeVector xyz) inline
Definition at line 85 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 85 of file ExGflashHit.hh
References fStart.
Member Data Documentation
G4int ExGflashHit::fCrystalNumber private
Definition at line 65 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 65 of file ExGflashHit.hh
Referenced by ExGflashHit(), GetCrystalNum(), operator=(), and SetCrystalNum().
G4double ExGflashHit::fEdep private
Definition at line 63 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 63 of file ExGflashHit.hh
Referenced by AddEdep(), ExGflashHit(), GetEdep(), operator=(), operator==(), and SetEdep().
const G4LogicalVolume * ExGflashHit::fLogV private
Definition at line 68 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 68 of file ExGflashHit.hh
Referenced by Draw(), ExGflashHit(), GetLogV(), and operator=().
G4ThreeVector ExGflashHit::fPos private
Definition at line 64 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 64 of file ExGflashHit.hh
Referenced by Draw(), ExGflashHit(), GetPos(), operator=(), operator==(), and SetPos().
G4RotationMatrix ExGflashHit::fRot private
Definition at line 67 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 67 of file ExGflashHit.hh
Referenced by Draw(), ExGflashHit(), GetRot(), operator=(), and SetRot().
G4ThreeVector ExGflashHit::fStart private
Definition at line 66 of file ExGflashHit.hh.
View newest version in sPHENIX GitHub at line 66 of file ExGflashHit.hh
Referenced by ExGflashHit(), GetStart(), operator=(), and SetStart().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/include/ExGflashHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/include/ExGflashHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/include/ExGflashHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/include/ExGflashHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash1/src/ExGflashHit.cc
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/src/ExGflashHit.cc
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash3/src/ExGflashHit.cc
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/src/ExGflashHit.cc