ECCE @ EIC Software: G4PSNofStep Class Reference
G4PSNofStep Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSNofStep.hh>
Public Member Functions
G4PSNofStep (G4String name, G4int depth=0)
virtual ~G4PSNofStep ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
void SetBoundaryFlag (G4bool flg=true)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
G4bool boundaryFlag
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 45 of file G4PSNofStep.hh.
View newest version in sPHENIX GitHub at line 45 of file G4PSNofStep.hh
Constructor & Destructor Documentation
G4PSNofStep::G4PSNofStep (G4String name, G4int depth = 0)
Definition at line 40 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 40 of file G4PSNofStep.cc
References SetUnit().
G4PSNofStep::~G4PSNofStep () virtual
Definition at line 46 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PSNofStep.cc
Member Function Documentation
void G4PSNofStep::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 70 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 70 of file G4PSNofStep.cc
References G4VTHitsMap< T, Map_t >::clear(), and EvtMap.
void G4PSNofStep::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 74 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 74 of file G4PSNofStep.cc
void G4PSNofStep::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 67 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PSNofStep.cc
void G4PSNofStep::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 60 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 60 of file G4PSNofStep.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, EvtMap, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
void G4PSNofStep::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 77 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PSNofStep.cc
References G4VPrimitiveScorer::detector, G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), and G4VSensitiveDetector::GetName().
G4bool G4PSNofStep::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 49 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PSNofStep.cc
References G4VTHitsMap< T, Map_t >::add(), boundaryFlag, EvtMap, FALSE, G4VPrimitiveScorer::GetIndex(), G4Step::GetStepLength(), and TRUE.
void G4PSNofStep::SetBoundaryFlag (G4bool flg = true) inline
Definition at line 69 of file G4PSNofStep.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSNofStep.hh
References boundaryFlag.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4PSNofStep::SetUnit (const G4String & unit) virtual
Definition at line 91 of file G4PSNofStep.cc.
View newest version in sPHENIX GitHub at line 91 of file G4PSNofStep.cc
References G4Exception(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::GetUnit(), JustWarning, G4VPrimitiveScorer::unitName, and G4VPrimitiveScorer::unitValue.
Referenced by G4PSNofStep().
Member Data Documentation
G4bool G4PSNofStep::boundaryFlag private
Definition at line 76 of file G4PSNofStep.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PSNofStep.hh
Referenced by ProcessHits(), and SetBoundaryFlag().
G4THitsMap<G4double>* G4PSNofStep::EvtMap private
Definition at line 74 of file G4PSNofStep.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PSNofStep.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int G4PSNofStep::HCID private
Definition at line 73 of file G4PSNofStep.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PSNofStep.hh
Referenced by Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSNofStep.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSNofStep.cc