ECCE @ EIC Software: G4Ellipsoid Class Reference
G4Ellipsoid Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Ellipsoid.hh>
Public Member Functions
G4Ellipsoid (const G4String &name, G4double xSemiAxis, G4double ySemiAxis, G4double zSemiAxis, G4double zBottomCut=0., G4double zTopCut=0.)
virtual ~G4Ellipsoid ()
G4double GetDx () const
G4double GetDy () const
G4double GetDz () const
G4double GetSemiAxisMax (G4int i) const
G4double GetZBottomCut () const
G4double GetZTopCut () const
void SetSemiAxis (G4double x, G4double y, G4double z)
void SetZCuts (G4double newzBottomCut, G4double newzTopCut)
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
G4ThreeVector GetPointOnSurface () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4Polyhedron * GetPolyhedron () const
G4Ellipsoid (__void__ &)
G4Ellipsoid (const G4Ellipsoid &rhs)
G4Ellipsoid & operator= (const G4Ellipsoid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
void CheckParameters ()
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
G4double LateralSurfaceArea () const
Private Attributes
G4double fDx
G4double fDy
G4double fDz
G4double fZBottomCut
G4double fZTopCut
G4double halfTolerance
G4double fXmax
G4double fYmax
G4double fRsph
G4double fR
G4double fSx
G4double fSy
G4double fSz
G4double fZMidCut
G4double fZDimCut
G4double fQ1
G4double fQ2
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4double fLateralArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 63 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 63 of file G4Ellipsoid.hh
Constructor & Destructor Documentation
G4Ellipsoid::G4Ellipsoid (const G4String & name, G4double xSemiAxis, G4double ySemiAxis, G4double zSemiAxis, G4double zBottomCut = 0., G4double zTopCut = 0.)
Definition at line 67 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 67 of file G4Ellipsoid.cc
References CheckParameters().
Referenced by Clone().
G4Ellipsoid::~G4Ellipsoid () virtual
Definition at line 93 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 93 of file G4Ellipsoid.cc
References fpPolyhedron.
G4Ellipsoid::G4Ellipsoid (__void__ & a)
Definition at line 84 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 84 of file G4Ellipsoid.cc
G4Ellipsoid::G4Ellipsoid (const G4Ellipsoid & rhs)
Definition at line 102 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 102 of file G4Ellipsoid.cc
Member Function Documentation
G4ThreeVector G4Ellipsoid::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 366 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 366 of file G4Ellipsoid.cc
References kdfinder::abs(), fR, fSx, fSy, fSz, fZDimCut, fZMidCut, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by DistanceToOut(), and SurfaceNormal().
void G4Ellipsoid::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 264 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 264 of file G4Ellipsoid.cc
References fXmax, fYmax, fZBottomCut, fZTopCut, and CLHEP::Hep3Vector::set().
Referenced by CalculateExtent().
G4bool G4Ellipsoid::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 276 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 276 of file G4Ellipsoid.cc
References BoundingLimits(), and G4BoundingEnvelope::CalculateExtent().
void G4Ellipsoid::CheckParameters () private
Definition at line 167 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 167 of file G4Ellipsoid.cc
References A(), B(), C(), FatalException, fCubicVolume, fDx, fDy, fDz, fLateralArea, fQ1, fQ2, fR, fRsph, fSurfaceArea, fSx, fSy, fSz, fXmax, fYmax, fZBottomCut, fZDimCut, fZMidCut, fZTopCut, G4Exception(), G4VSolid::GetName(), halfTolerance, G4VSolid::kCarTolerance, max, message(), min, ratio, and scale.
Referenced by G4Ellipsoid().
G4VSolid * G4Ellipsoid::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 651 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 651 of file G4Ellipsoid.cc
References G4Ellipsoid().
void G4Ellipsoid::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 253 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 253 of file G4Ellipsoid.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Ellipsoid::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 877 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 877 of file G4Ellipsoid.cc
References fDx, fDy, fDz, fZBottomCut, and fZTopCut.
Referenced by GetPolyhedron().
void G4Ellipsoid::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 859 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 859 of file G4Ellipsoid.cc
References G4VGraphicsScene::AddSolid().
G4double G4Ellipsoid::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 384 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 384 of file G4Ellipsoid.cc
References A(), kdfinder::abs(), B(), C(), D(), DBL_MAX, dz, EPS, fQ1, fQ2, fR, fRsph, fSx, fSy, fSz, fXmax, fYmax, fZBottomCut, fZDimCut, fZMidCut, fZTopCut, halfTolerance, G4VSolid::kCarTolerance, kInfinity, max, min, offset, t1, t2, tmp, v, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Ellipsoid::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 470 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 470 of file G4Ellipsoid.cc
References kdfinder::abs(), distB, fR, fSx, fSy, fSz, fXmax, fYmax, fZBottomCut, fZTopCut, max, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
G4double G4Ellipsoid::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 497 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 497 of file G4Ellipsoid.cc
References A(), kdfinder::abs(), ApproxSurfaceNormal(), B(), C(), D(), DBL_EPSILON, DBL_MAX, G4VSolid::DumpInfo(), EPS, fQ1, fQ2, fR, fSx, fSy, fSz, fZDimCut, fZMidCut, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), halfTolerance, JustWarning, max, message(), min, CLHEP::Hep3Vector::set(), tmp, CLHEP::Hep3Vector::unit(), v, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Ellipsoid::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 622 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 622 of file G4Ellipsoid.cc
References fR, fSx, fSy, fSz, fZBottomCut, fZTopCut, min, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
G4double G4Ellipsoid::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 682 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 682 of file G4Ellipsoid.cc
References fCubicVolume, fDx, fDy, fDz, fZBottomCut, fZTopCut, and CLHEP::pi.
G4double G4Ellipsoid::GetDx () const inline
Referenced by GetPointOnSurface(), and StreamInfo().
G4double G4Ellipsoid::GetDy () const inline
Referenced by GetPointOnSurface(), and StreamInfo().
G4double G4Ellipsoid::GetDz () const inline
Referenced by GetPointOnSurface(), and StreamInfo().
G4GeometryType G4Ellipsoid::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 642 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 642 of file G4Ellipsoid.cc
Referenced by StreamInfo().
G4VisExtent G4Ellipsoid::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 868 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 868 of file G4Ellipsoid.cc
References fXmax, fYmax, fZBottomCut, and fZTopCut.
G4ThreeVector G4Ellipsoid::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 781 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 781 of file G4Ellipsoid.cc
References A(), B(), C(), fLateralArea, G4QuickRand(), G4RandomPointInEllipse(), GetDx(), GetDy(), GetDz(), GetZBottomCut(), GetZTopCut(), k, LateralSurfaceArea(), max, phi, CLHEP::pi, scale, CLHEP::Hep3Vector::set(), CLHEP::twopi, G4TemplateAutoLock< _Mutex_t >::unlock(), CLHEP::Hep2Vector::x(), x, CLHEP::Hep2Vector::y(), y, and z.
G4Polyhedron * G4Ellipsoid::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 886 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 886 of file G4Ellipsoid.cc
References CreatePolyhedron(), fpPolyhedron, fRebuildPolyhedron, HepPolyhedron::GetNumberOfRotationSteps(), G4Polyhedron::GetNumberOfRotationStepsAtTimeOfCreation(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4double G4Ellipsoid::GetSemiAxisMax (G4int i) const inline
Referenced by G4GDMLWriteParamvol::Ellipsoid_dimensionsWrite(), PHG4GDMLWriteParamvol::Ellipsoid_dimensionsWrite(), PHG4GDMLWriteSolids::EllipsoidWrite(), G4GDMLWriteSolids::EllipsoidWrite(), export_G4Ellipsoid(), and G4tgbGeometryDumper::GetSolidParams().
G4double G4Ellipsoid::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 757 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 757 of file G4Ellipsoid.cc
References fDx, fDy, fDz, fSurfaceArea, fZBottomCut, fZTopCut, LateralSurfaceArea(), and CLHEP::pi.
G4double G4Ellipsoid::GetZBottomCut () const inline
Referenced by G4GDMLWriteParamvol::Ellipsoid_dimensionsWrite(), PHG4GDMLWriteParamvol::Ellipsoid_dimensionsWrite(), PHG4GDMLWriteSolids::EllipsoidWrite(), G4GDMLWriteSolids::EllipsoidWrite(), export_G4Ellipsoid(), GetPointOnSurface(), G4tgbGeometryDumper::GetSolidParams(), and StreamInfo().
G4double G4Ellipsoid::GetZTopCut () const inline
Referenced by G4GDMLWriteParamvol::Ellipsoid_dimensionsWrite(), PHG4GDMLWriteParamvol::Ellipsoid_dimensionsWrite(), PHG4GDMLWriteSolids::EllipsoidWrite(), G4GDMLWriteSolids::EllipsoidWrite(), export_G4Ellipsoid(), GetPointOnSurface(), G4tgbGeometryDumper::GetSolidParams(), and StreamInfo().
EInside G4Ellipsoid::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 295 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 295 of file G4Ellipsoid.cc
References kdfinder::abs(), fQ1, fQ2, fSx, fSy, fSz, fZDimCut, fZMidCut, halfTolerance, kInside, kOutside, kSurface, max, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
G4double G4Ellipsoid::LateralSurfaceArea () const private
Definition at line 706 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 706 of file G4Ellipsoid.cc
References Acts::VectorHelpers::cross(), dz, fDx, fDy, fDz, fZBottomCut, fZTopCut, CLHEP::halfpi, z, z1, and z2.
Referenced by GetPointOnSurface(), and GetSurfaceArea().
G4Ellipsoid & G4Ellipsoid::operator= (const G4Ellipsoid & rhs)
Definition at line 122 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 122 of file G4Ellipsoid.cc
References fCubicVolume, fDx, fDy, fDz, fLateralArea, fpPolyhedron, fQ1, fQ2, fR, fRebuildPolyhedron, fRsph, fSurfaceArea, fSx, fSy, fSz, fXmax, fYmax, fZBottomCut, fZDimCut, fZMidCut, fZTopCut, halfTolerance, and G4VSolid::operator=().
void G4Ellipsoid::SetSemiAxis (G4double x, G4double y, G4double z) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Ellipsoid().
void G4Ellipsoid::SetZCuts (G4double newzBottomCut, G4double newzTopCut) inline
Referenced by G4GDMLParameterisation::ComputeDimensions(), and export_G4Ellipsoid().
std::ostream & G4Ellipsoid::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 660 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 660 of file G4Ellipsoid.cc
References GetDx(), GetDy(), GetDz(), GetEntityType(), G4VSolid::GetName(), GetZBottomCut(), GetZTopCut(), and mm.
G4ThreeVector G4Ellipsoid::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 313 of file G4Ellipsoid.cc.
View newest version in sPHENIX GitHub at line 313 of file G4Ellipsoid.cc
References kdfinder::abs(), ApproxSurfaceNormal(), G4VSolid::DumpInfo(), fQ1, fQ2, fSx, fSy, fSz, fZDimCut, fZMidCut, G4cout, G4Exception(), G4VSolid::GetName(), halfTolerance, JustWarning, message(), mm, norm, CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Member Data Documentation
G4double G4Ellipsoid::fCubicVolume = 0.0 private
Definition at line 177 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 177 of file G4Ellipsoid.hh
Referenced by CheckParameters(), GetCubicVolume(), and operator=().
G4double G4Ellipsoid::fDx private
Definition at line 157 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 157 of file G4Ellipsoid.hh
Referenced by CheckParameters(), CreatePolyhedron(), GetCubicVolume(), GetSurfaceArea(), LateralSurfaceArea(), and operator=().
G4double G4Ellipsoid::fDy private
Definition at line 158 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 158 of file G4Ellipsoid.hh
Referenced by CheckParameters(), CreatePolyhedron(), GetCubicVolume(), GetSurfaceArea(), LateralSurfaceArea(), and operator=().
G4double G4Ellipsoid::fDz private
Definition at line 159 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 159 of file G4Ellipsoid.hh
Referenced by CheckParameters(), CreatePolyhedron(), GetCubicVolume(), GetSurfaceArea(), LateralSurfaceArea(), and operator=().
G4double G4Ellipsoid::fLateralArea = 0.0 mutable private
Definition at line 179 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 179 of file G4Ellipsoid.hh
Referenced by CheckParameters(), GetPointOnSurface(), and operator=().
G4Polyhedron* G4Ellipsoid::fpPolyhedron = nullptr mutable private
Definition at line 181 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Ellipsoid.hh
Referenced by GetPolyhedron(), operator=(), and ~G4Ellipsoid().
G4double G4Ellipsoid::fQ1 private
Definition at line 174 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 174 of file G4Ellipsoid.hh
Referenced by CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fQ2 private
Definition at line 175 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 175 of file G4Ellipsoid.hh
Referenced by CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fR private
Definition at line 168 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 168 of file G4Ellipsoid.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), DistanceToIn(), DistanceToOut(), and operator=().
G4bool G4Ellipsoid::fRebuildPolyhedron = false mutable private
Definition at line 180 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 180 of file G4Ellipsoid.hh
Referenced by GetPolyhedron(), and operator=().
G4double G4Ellipsoid::fRsph private
Definition at line 167 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 167 of file G4Ellipsoid.hh
Referenced by CheckParameters(), DistanceToIn(), and operator=().
G4double G4Ellipsoid::fSurfaceArea = 0.0 private
Definition at line 178 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 178 of file G4Ellipsoid.hh
Referenced by CheckParameters(), GetSurfaceArea(), and operator=().
G4double G4Ellipsoid::fSx private
Definition at line 169 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Ellipsoid.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fSy private
Definition at line 170 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 170 of file G4Ellipsoid.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fSz private
Definition at line 171 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 171 of file G4Ellipsoid.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fXmax private
Definition at line 165 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 165 of file G4Ellipsoid.hh
Referenced by BoundingLimits(), CheckParameters(), DistanceToIn(), GetExtent(), and operator=().
G4double G4Ellipsoid::fYmax private
Definition at line 166 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 166 of file G4Ellipsoid.hh
Referenced by BoundingLimits(), CheckParameters(), DistanceToIn(), GetExtent(), and operator=().
G4double G4Ellipsoid::fZBottomCut private
Definition at line 160 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 160 of file G4Ellipsoid.hh
Referenced by BoundingLimits(), CheckParameters(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCubicVolume(), GetExtent(), GetSurfaceArea(), LateralSurfaceArea(), and operator=().
G4double G4Ellipsoid::fZDimCut private
Definition at line 173 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 173 of file G4Ellipsoid.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fZMidCut private
Definition at line 172 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 172 of file G4Ellipsoid.hh
Referenced by ApproxSurfaceNormal(), CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Ellipsoid::fZTopCut private
Definition at line 161 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 161 of file G4Ellipsoid.hh
Referenced by BoundingLimits(), CheckParameters(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCubicVolume(), GetExtent(), GetSurfaceArea(), LateralSurfaceArea(), and operator=().
G4double G4Ellipsoid::halfTolerance private
Definition at line 164 of file G4Ellipsoid.hh.
View newest version in sPHENIX GitHub at line 164 of file G4Ellipsoid.hh
Referenced by CheckParameters(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Ellipsoid.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4Ellipsoid.cc