ECCE @ EIC Software: macros/blob/master/common/G4_BWD.C File Reference
G4_BWD.C File Reference
#include <GlobalVariables.C>
#include <eicg4bwd/BwdRawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4eiccalos/PHG4ForwardCalCellReco.h>
#include <eicg4bwd/EICG4BwdSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <eiccaloreco/RawClusterBuilderkMA.h>
#include <eiccaloreco/RawClusterBuilderHelper.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace G4BWD
Macros
#define MACRO_G4BWD_C
Functions
void BWDInit ()
void BWDSetup (PHG4Reco *g4Reco)
void BWD_Cells (int verbosity=0)
void BWD_Towers ()
void BWD_Clusters ()
void BWD_Eval (const std::string &outputfile)
Variables
bool Enable::BWD = false
bool Enable::BWDN [5] ={true,false,false,false,false}
bool Enable::BWD_ABSORBER = false
bool Enable::BWD_CELL = false
bool Enable::BWD_TOWER = false
bool Enable::BWD_CLUSTER = false
bool Enable::BWD_EVAL = false
bool Enable::BWD_OVERLAPCHECK = false
int Enable::BWD_VERBOSITY = 0
string G4BWD::mapname [5] ={"BWD_mapping_v1.txt","BWD_mapping_v2.txt","BWD_mapping_v3.txt","BWD_mapping_v4.txt","BWD_mapping_v5.txt"}
double G4BWD::minz = -5000
double G4BWD::maxz = -300
double G4BWD::radius = 100
RawTowerDigitizer::enu_digi_algorithm G4BWD::TowerDigi = RawTowerDigitizer::kNo_digitization
Macro Definition Documentation
#define MACRO_G4BWD_C
Definition at line 2 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 2 of file G4_BWD.C
Function Documentation
void BWD_Cells (int verbosity = 0)
Definition at line 81 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 81 of file G4_BWD.C
void BWD_Clusters ()
Definition at line 121 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 121 of file G4_BWD.C
References Enable::BWD_VERBOSITY, Enable::BWDN, RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void BWD_Eval (const std::string & outputfile)
Definition at line 137 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 137 of file G4_BWD.C
References Enable::BWD_VERBOSITY, Enable::BWDN, INPUTHEPMC::filename, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void BWD_Towers ()
Definition at line 86 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 86 of file G4_BWD.C
References Enable::BWD_VERBOSITY, Enable::BWDN, RawTowerDigitizer::Detector(), RawTowerCalibration::Detector(), BwdRawTowerBuilderByHitIndex::Detector(), BwdRawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, G4BWD::mapname, max, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), BwdRawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector().
void BWDInit ()
Definition at line 72 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 72 of file G4_BWD.C
Referenced by G4Init().
void BWDSetup (PHG4Reco * g4Reco)
Definition at line 76 of file G4_BWD.C.
View newest version in sPHENIX GitHub at line 76 of file G4_BWD.C