ECCE @ EIC Software: G4UniformRandPool Class Reference
G4UniformRandPool Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/HEPRandom/include/G4UniformRandPool.hh>
Public Member Functions
G4UniformRandPool ()
G4UniformRandPool (G4int ps)
~G4UniformRandPool ()
void Resize (G4int newSize)
void GetMany (G4double *rnds, G4int howMany)
G4double GetOne ()
G4int GetPoolSize () const
Static Public Member Functions
static G4double flat ()
static void flatArray (G4int howmany, G4double *rnds)
Private Member Functions
void Fill (G4int howmany)
Private Attributes
G4int size
G4double * buffer
G4int currentIdx
Detailed Description
Definition at line 55 of file G4UniformRandPool.hh.
View newest version in sPHENIX GitHub at line 55 of file G4UniformRandPool.hh
Constructor & Destructor Documentation
G4UniformRandPool::G4UniformRandPool ()
Definition at line 93 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 93 of file G4UniformRandPool.cc
References create_pool(), create_pool_align(), Fill(), and size.
Referenced by flat(), and flatArray().
G4UniformRandPool::G4UniformRandPool (G4int ps)
Definition at line 107 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 107 of file G4UniformRandPool.cc
References create_pool(), create_pool_align(), Fill(), and size.
G4UniformRandPool::~G4UniformRandPool ()
Definition at line 122 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 122 of file G4UniformRandPool.cc
References destroy_pool(), and destroy_pool_align().
Member Function Documentation
void G4UniformRandPool::Fill (G4int howmany) private
Definition at line 146 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 146 of file G4UniformRandPool.cc
References currentIdx, and size.
Referenced by G4UniformRandPool(), GetMany(), and GetOne().
G4double G4UniformRandPool::flat () static
Definition at line 228 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 228 of file G4UniformRandPool.cc
References G4UniformRandPool(), and G4AutoDelete::Register().
void G4UniformRandPool::flatArray (G4int howmany, G4double * rnds) static
Definition at line 238 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 238 of file G4UniformRandPool.cc
References G4UniformRandPool(), and G4AutoDelete::Register().
void G4UniformRandPool::GetMany (G4double * rnds, G4int howMany)
Definition at line 156 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 156 of file G4UniformRandPool.cc
References currentIdx, Fill(), and size.
G4double G4UniformRandPool::GetOne () inline
Definition at line 85 of file G4UniformRandPool.hh.
View newest version in sPHENIX GitHub at line 85 of file G4UniformRandPool.hh
References currentIdx, Fill(), and size.
G4int G4UniformRandPool::GetPoolSize () const inline
Definition at line 97 of file G4UniformRandPool.hh.
View newest version in sPHENIX GitHub at line 97 of file G4UniformRandPool.hh
References size.
void G4UniformRandPool::Resize (G4int newSize)
Definition at line 134 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 134 of file G4UniformRandPool.cc
References create_pool(), currentIdx, destroy_pool(), and size.
Member Data Documentation
G4double* G4UniformRandPool::buffer private
Definition at line 81 of file G4UniformRandPool.hh.
View newest version in sPHENIX GitHub at line 81 of file G4UniformRandPool.hh
G4int G4UniformRandPool::currentIdx private
Definition at line 82 of file G4UniformRandPool.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UniformRandPool.hh
Referenced by Fill(), GetMany(), GetOne(), and Resize().
G4int G4UniformRandPool::size private
Definition at line 80 of file G4UniformRandPool.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UniformRandPool.hh
Referenced by Fill(), G4UniformRandPool(), GetMany(), GetOne(), GetPoolSize(), and Resize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/HEPRandom/include/G4UniformRandPool.hh
geant4/tree/geant4-10.6-release/source/global/HEPRandom/src/G4UniformRandPool.cc