ECCE @ EIC Software: G4INCL::IntersectionFactory Namespace Reference
G4INCL::IntersectionFactory Namespace Reference
Functions
Intersection getEarlierTrajectoryIntersection (const ThreeVector &x0, const ThreeVector &p, const G4double r)
Compute the first intersection of a straight particle trajectory with a sphere.
Intersection getLaterTrajectoryIntersection (const ThreeVector &x0, const ThreeVector &p, const G4double r)
Compute the second intersection of a straight particle trajectory with a sphere.
std::pair< Intersection,
Intersection > getTrajectoryIntersections (const ThreeVector &x0, const ThreeVector &p, const G4double r)
Compute both intersections of a straight particle trajectory with a sphere.
Function Documentation
Intersection G4INCL::IntersectionFactory::getEarlierTrajectoryIntersection (const ThreeVector & x0, const ThreeVector & p, const G4double r) inline
Compute the first intersection of a straight particle trajectory with a sphere.
Parameters
x0 the starting position of the trajectory
p the trajectory direction
r the radius of the sphere (centred in the origin)
Returns
an Intersection. The G4bool is true if an intersection exists, in which case its position is stored in the ThreeVector and its time in the G4double.
Definition at line 124 of file G4INCLIntersection.hh.
View newest version in sPHENIX GitHub at line 124 of file G4INCLIntersection.hh
Referenced by G4INCL::CoulombNone::bringToSurface(), and G4INCL::INCL::makeCompoundNucleus().
Intersection G4INCL::IntersectionFactory::getLaterTrajectoryIntersection (const ThreeVector & x0, const ThreeVector & p, const G4double r) inline
Compute the second intersection of a straight particle trajectory with a sphere.
Parameters
x0 the starting position of the trajectory
p the trajectory direction
r the radius of the sphere (centred in the origin)
Returns
an Intersection. The G4bool is true if an intersection exists, in which case its position is stored in the ThreeVector and its time in the G4double.
Definition at line 128 of file G4INCLIntersection.hh.
View newest version in sPHENIX GitHub at line 128 of file G4INCLIntersection.hh
Referenced by G4INCL::StandardPropagationModel::getReflectionTime().
std::pair< Intersection, Intersection > G4INCL::IntersectionFactory::getTrajectoryIntersections (const ThreeVector & x0, const ThreeVector & p, const G4double r) inline
Compute both intersections of a straight particle trajectory with a sphere.
Parameters
x0 the starting position of the trajectory
p the trajectory direction
r the radius of the sphere (centred in the origin)
Returns
an Intersection. The G4bool is true if an intersection exists, in which case its position is stored in the ThreeVector and its time in the G4double.
Definition at line 132 of file G4INCLIntersection.hh.
View newest version in sPHENIX GitHub at line 132 of file G4INCLIntersection.hh