ECCE @ EIC Software: JA Namespace Reference
JA Namespace Reference
Classes
struct Node
Typedefs
typedef
G4PhysicalVolumeModel::G4PhysicalVolumeNodeID PVNodeID
typedef std::vector< PVNodeID > PVPath
Functions
void Insert (const PVNodeID *pvPath, size_t pathLength, G4int index, Node *node)
void PrintTree (std::ostream &, Node *)
void Clear (Node *)
Typedef Documentation
typedef G4PhysicalVolumeModel::G4PhysicalVolumeNodeID JA::PVNodeID
Definition at line 44 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 44 of file G4XXXSGSceneHandler.hh
typedef std::vector<PVNodeID> JA::PVPath
Definition at line 45 of file G4XXXSGSceneHandler.hh.
View newest version in sPHENIX GitHub at line 45 of file G4XXXSGSceneHandler.hh
Function Documentation
void JA::Clear (Node * node)
Definition at line 484 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 484 of file G4XXXSGSceneHandler.cc
References JA::Node::fDaughters.
Referenced by RunActionMaster::BeginOfRunAction(), G4XXXSGSceneHandler::ClearStore(), G4XXXSGSceneHandler::ClearTransientStore(), G4Scheduler::Notify(), G4SmartFilter< T >::Reset(), G4TemplateRNGHelper< T >::~G4TemplateRNGHelper(), and G4ThreadLocalSingleton< T >::~G4ThreadLocalSingleton().
void JA::Insert (const PVNodeID * pvPath, size_t pathLength, G4int index, Node * node)
Definition at line 417 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 417 of file G4XXXSGSceneHandler.cc
References JA::Node::fDaughters, G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetCopyNo(), and G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetPhysicalVolume().
Referenced by G4SpinDecayPhysics::ConstructParticle(), F04PhysicsList::ConstructParticle(), and G4XXXSGSceneHandler::CreateCurrentItem().
void JA::PrintTree (std::ostream & os, Node * node)
Definition at line 463 of file G4XXXSGSceneHandler.cc.
View newest version in sPHENIX GitHub at line 463 of file G4XXXSGSceneHandler.cc
References JA::Node::fDaughters, JA::Node::fIndex, JA::Node::fPVNodeID, G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetCopyNo(), G4VPhysicalVolume::GetName(), and G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetPhysicalVolume().
Referenced by G4XXXSGViewer::DrawFromStore().