ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/run/pyG4VUserPhysicsList.cc File Reference
pyG4VUserPhysicsList.cc File Reference
#include <boost/python.hpp>
#include "G4VUserPhysicsList.hh"
Classes
struct pyG4VUserPhysicsList::CB_G4VUserPhysicsList
Namespaces
namespace pyG4VUserPhysicsList
Functions
pyG4VUserPhysicsList::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_StorePhysicsTable, StorePhysicsTable, 0, 1) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_SetParticleCuts
void export_G4VUserPhysicsList ()
Variables
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f1_SetCutValue)(G4double, const G4String &) = &G4VUserPhysicsList::SetCutValue
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f2_SetCutValue)(G4double, const G4String &, const G4String &) = &G4VUserPhysicsList::SetCutValue
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f1_SetParticleCuts)(G4double, G4ParticleDefinition *, G4Region *) = &G4VUserPhysicsList::SetParticleCuts
void(G4VUserPhysicsList::* pyG4VUserPhysicsList::f2_SetParticleCuts)(G4double, G4ParticleDefinition *, G4Region *) = &G4VUserPhysicsList::SetParticleCuts
pyG4VUserPhysicsList::SetParticleCuts
Function Documentation
void export_G4VUserPhysicsList ()
Definition at line 88 of file pyG4VUserPhysicsList.cc.
View newest version in sPHENIX GitHub at line 88 of file pyG4VUserPhysicsList.cc
References G4VUserPhysicsList::ConstructParticle(), G4VUserPhysicsList::ConstructProcess(), G4VUserPhysicsList::DumpCutValuesTable(), G4VUserPhysicsList::DumpCutValuesTableIfRequested(), G4VUserPhysicsList::DumpList(), pyG4VUserPhysicsList::f1_SetCutValue, pyG4VUserPhysicsList::f1_SetParticleCuts, pyG4VUserPhysicsList::f2_SetCutValue, pyG4VUserPhysicsList::f2_SetParticleCuts, G4VUserPhysicsList::GetApplyCuts(), G4VUserPhysicsList::GetDefaultCutValue(), G4VUserPhysicsList::GetPhysicsTableDirectory(), G4VUserPhysicsList::GetVerboseLevel(), G4VUserPhysicsList::IsPhysicsTableRetrieved(), G4VUserPhysicsList::IsStoredInAscii(), G4VUserPhysicsList::ResetStoredInAscii(), G4VUserPhysicsList::SetCuts(), G4VUserPhysicsList::SetCutsForRegion(), G4VUserPhysicsList::SetCutsWithDefault(), G4VUserPhysicsList::SetDefaultCutValue(), G4VUserPhysicsList::SetStoredInAscii(), G4VUserPhysicsList::SetVerboseLevel(), and G4VUserPhysicsList::StorePhysicsTable().
Referenced by BOOST_PYTHON_MODULE().