ECCE @ EIC Software: G4HadronPhysicsFTFP_BERT_ATL Class Reference
G4HadronPhysicsFTFP_BERT_ATL Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTFP_BERT_ATL.hh>
Public Member Functions
G4HadronPhysicsFTFP_BERT_ATL (G4int verbose=1)
G4HadronPhysicsFTFP_BERT_ATL (const G4String &name, G4bool quasiElastic=false)
virtual ~G4HadronPhysicsFTFP_BERT_ATL ()
Public Member Functions inherited from G4HadronPhysicsFTFP_BERT
G4HadronPhysicsFTFP_BERT (G4int verbose=1)
G4HadronPhysicsFTFP_BERT (const G4String &name, G4bool quasiElastic=false)
virtual ~G4HadronPhysicsFTFP_BERT ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
virtual void Neutron () override
virtual void Proton () override
virtual void Pion () override
virtual void Kaon () override
virtual void DumpBanner () override
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4HadronPhysicsFTFP_BERT
virtual void CreateModels ()
virtual void Others ()
virtual void ExtraConfiguration ()
Protected Attributes inherited from G4HadronPhysicsFTFP_BERT
G4bool QuasiElastic
G4double minFTFP_pion
G4double maxBERT_pion
G4double minFTFP_kaon
G4double maxBERT_kaon
G4double minFTFP_proton
G4double maxBERT_proton
G4double minFTFP_neutron
G4double maxBERT_neutron
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 46 of file G4HadronPhysicsFTFP_BERT_ATL.hh.
View newest version in sPHENIX GitHub at line 46 of file G4HadronPhysicsFTFP_BERT_ATL.hh
Constructor & Destructor Documentation
G4HadronPhysicsFTFP_BERT_ATL::G4HadronPhysicsFTFP_BERT_ATL (G4int verbose = 1)
Definition at line 60 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 60 of file G4HadronPhysicsFTFP_BERT_ATL.cc
G4HadronPhysicsFTFP_BERT_ATL::G4HadronPhysicsFTFP_BERT_ATL (const G4String & name, G4bool quasiElastic = false)
Definition at line 64 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 64 of file G4HadronPhysicsFTFP_BERT_ATL.cc
References GeV, G4HadronPhysicsFTFP_BERT::maxBERT_kaon, G4HadronPhysicsFTFP_BERT::maxBERT_neutron, G4HadronPhysicsFTFP_BERT::maxBERT_pion, G4HadronPhysicsFTFP_BERT::maxBERT_proton, G4HadronPhysicsFTFP_BERT::minFTFP_kaon, G4HadronPhysicsFTFP_BERT::minFTFP_neutron, G4HadronPhysicsFTFP_BERT::minFTFP_pion, G4HadronPhysicsFTFP_BERT::minFTFP_proton, and G4HadronPhysicsFTFP_BERT::QuasiElastic.
virtual G4HadronPhysicsFTFP_BERT_ATL::~G4HadronPhysicsFTFP_BERT_ATL () inline virtual
Definition at line 51 of file G4HadronPhysicsFTFP_BERT_ATL.hh.
View newest version in sPHENIX GitHub at line 51 of file G4HadronPhysicsFTFP_BERT_ATL.hh
Member Function Documentation
void G4HadronPhysicsFTFP_BERT_ATL::DumpBanner () override private virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 79 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsFTFP_BERT_ATL.cc
References G4cout, G4endl, GeV, G4HadronPhysicsFTFP_BERT::maxBERT_pion, and G4HadronPhysicsFTFP_BERT::minFTFP_pion.
void G4HadronPhysicsFTFP_BERT_ATL::Kaon () override private virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 131 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 131 of file G4HadronPhysicsFTFP_BERT_ATL.cc
void G4HadronPhysicsFTFP_BERT_ATL::Neutron () override private virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 85 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 85 of file G4HadronPhysicsFTFP_BERT_ATL.cc
References G4VPhysicsConstructor::AddBuilder(), G4HadronPhysicsFTFP_BERT::maxBERT_neutron, G4HadronPhysicsFTFP_BERT::minFTFP_neutron, G4InuclParticleNames::neu, and G4HadronPhysicsFTFP_BERT::QuasiElastic.
void G4HadronPhysicsFTFP_BERT_ATL::Pion () override private virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 116 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 116 of file G4HadronPhysicsFTFP_BERT_ATL.cc
References G4VPhysicsConstructor::AddBuilder(), G4HadronPhysicsFTFP_BERT::maxBERT_pion, G4HadronPhysicsFTFP_BERT::minFTFP_pion, and G4HadronPhysicsFTFP_BERT::QuasiElastic.
void G4HadronPhysicsFTFP_BERT_ATL::Proton () override private virtual
Reimplemented from G4HadronPhysicsFTFP_BERT.
Definition at line 101 of file G4HadronPhysicsFTFP_BERT_ATL.cc.
View newest version in sPHENIX GitHub at line 101 of file G4HadronPhysicsFTFP_BERT_ATL.cc
References G4VPhysicsConstructor::AddBuilder(), G4HadronPhysicsFTFP_BERT::maxBERT_proton, G4HadronPhysicsFTFP_BERT::minFTFP_proton, G4InuclParticleNames::pro, and G4HadronPhysicsFTFP_BERT::QuasiElastic.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsFTFP_BERT_ATL.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsFTFP_BERT_ATL.cc