ECCE @ EIC Software: G4UIbatch Class Reference
G4UIbatch Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIbatch.hh>
Public Member Functions
G4UIbatch (const char *fileName, G4UIsession *prevSession=0)
~G4UIbatch ()
G4UIsession * GetPreviousSession () const
virtual G4UIsession * SessionStart ()
virtual void PauseSessionStart (const G4String &Prompt)
Public Member Functions inherited from G4UIsession
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
virtual G4int ReceiveG4cout (const G4String &coutString)
virtual G4int ReceiveG4cerr (const G4String &cerrString)
G4int GetLastReturnCode () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Private Member Functions
G4String ReadCommand ()
G4int ExecCommand (const G4String &command)
Private Attributes
G4UIsession * previousSession
std::ifstream macroStream
G4bool isOpened
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Public Member Functions inherited from G4UIsession
static G4int InSession ()
Protected Attributes inherited from G4UIsession
G4int ifBatch
G4int lastRC
Static Protected Attributes inherited from G4UIsession
static G4ICOMS_DLL G4int inSession = 0
Detailed Description
Definition at line 50 of file G4UIbatch.hh.
View newest version in sPHENIX GitHub at line 50 of file G4UIbatch.hh
Constructor & Destructor Documentation
G4UIbatch::G4UIbatch (const char * fileName, G4UIsession * prevSession = 0)
Definition at line 68 of file G4UIbatch.cc.
View newest version in sPHENIX GitHub at line 68 of file G4UIbatch.cc
References fParameterUnreadable, G4cerr, G4endl, G4UImanager::GetUIpointer(), in, isOpened, G4UIsession::lastRC, and macroStream.
G4UIbatch::~G4UIbatch ()
Definition at line 88 of file G4UIbatch.cc.
View newest version in sPHENIX GitHub at line 88 of file G4UIbatch.cc
References isOpened, and macroStream.
Member Function Documentation
G4int G4UIbatch::ExecCommand (const G4String & command) private
Definition at line 167 of file G4UIbatch.cc.
View newest version in sPHENIX GitHub at line 167 of file G4UIbatch.cc
References fCommandNotFound, fCommandSucceeded, fIllegalApplicationState, G4cerr, G4endl, G4UImanager::GetUIpointer(), and G4InuclParticleNames::pn.
Referenced by SessionStart().
G4UIsession * G4UIbatch::GetPreviousSession () const inline
Definition at line 80 of file G4UIbatch.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UIbatch.hh
References previousSession.
void G4UIbatch::PauseSessionStart (const G4String & Prompt) virtual
Reimplemented from G4UIsession.
Definition at line 229 of file G4UIbatch.cc.
View newest version in sPHENIX GitHub at line 229 of file G4UIbatch.cc
References G4cout, G4endl, and SessionStart().
G4String G4UIbatch::ReadCommand () private
Definition at line 96 of file G4UIbatch.cc.
View newest version in sPHENIX GitHub at line 96 of file G4UIbatch.cc
References G4String::both, BUFSIZE, G4Exception(), G4ThreadLocal, JustWarning, macroStream, G4String::replace(), G4String::strip(), Tokenize(), and G4String::trailing.
Referenced by SessionStart().
G4UIsession * G4UIbatch::SessionStart () virtual
Reimplemented from G4UIsession.
Definition at line 195 of file G4UIbatch.cc.
View newest version in sPHENIX GitHub at line 195 of file G4UIbatch.cc
References ExecCommand(), fCommandSucceeded, G4cerr, G4cout, G4endl, G4UImanager::GetUIpointer(), isOpened, G4UIsession::lastRC, previousSession, and ReadCommand().
Referenced by PauseSessionStart().
Member Data Documentation
G4bool G4UIbatch::isOpened private
Definition at line 55 of file G4UIbatch.hh.
View newest version in sPHENIX GitHub at line 55 of file G4UIbatch.hh
Referenced by G4UIbatch(), SessionStart(), and ~G4UIbatch().
std::ifstream G4UIbatch::macroStream private
Definition at line 54 of file G4UIbatch.hh.
View newest version in sPHENIX GitHub at line 54 of file G4UIbatch.hh
Referenced by G4UIbatch(), ReadCommand(), and ~G4UIbatch().
G4UIsession* G4UIbatch::previousSession private
Definition at line 52 of file G4UIbatch.hh.
View newest version in sPHENIX GitHub at line 52 of file G4UIbatch.hh
Referenced by GetPreviousSession(), and SessionStart().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIbatch.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIbatch.cc