ECCE @ EIC Software: G4SmartVoxelProxy Class Reference
G4SmartVoxelProxy Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SmartVoxelProxy.hh>
Public Member Functions
G4SmartVoxelProxy (G4SmartVoxelHeader *pHeader)
G4SmartVoxelProxy (G4SmartVoxelNode *pNode)
~G4SmartVoxelProxy ()
G4bool IsHeader () const
G4bool IsNode () const
G4SmartVoxelNode * GetNode () const
G4SmartVoxelHeader * GetHeader () const
G4bool operator== (const G4SmartVoxelProxy &v) const
Private Attributes
G4SmartVoxelHeader * fHeader = nullptr
G4SmartVoxelNode * fNode = nullptr
Detailed Description
Definition at line 48 of file G4SmartVoxelProxy.hh.
View newest version in sPHENIX GitHub at line 48 of file G4SmartVoxelProxy.hh
Constructor & Destructor Documentation
G4SmartVoxelProxy::G4SmartVoxelProxy (G4SmartVoxelHeader * pHeader) inline
Definition at line 53 of file G4SmartVoxelProxy.hh.
View newest version in sPHENIX GitHub at line 53 of file G4SmartVoxelProxy.hh
G4SmartVoxelProxy::G4SmartVoxelProxy (G4SmartVoxelNode * pNode) inline
Definition at line 57 of file G4SmartVoxelProxy.hh.
View newest version in sPHENIX GitHub at line 57 of file G4SmartVoxelProxy.hh
G4SmartVoxelProxy::~G4SmartVoxelProxy ()
Definition at line 35 of file G4SmartVoxelProxy.cc.
View newest version in sPHENIX GitHub at line 35 of file G4SmartVoxelProxy.cc
Member Function Documentation
G4SmartVoxelHeader* G4SmartVoxelProxy::GetHeader () const
Referenced by G4SmartVoxelHeader::CollectEquivalentHeaders(), G4DrawVoxels::ComputeVoxelPolyhedra(), G4SmartVoxelStat::CountHeadsAndNodes(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::operator==(), and G4VoxelSafety::SafetyForVoxelHeader().
G4SmartVoxelNode* G4SmartVoxelProxy::GetNode () const
Referenced by G4SmartVoxelHeader::CollectEquivalentNodes(), G4ParameterisedNavigation::ComputeSafety(), G4DrawVoxels::ComputeVoxelPolyhedra(), G4ParameterisedNavigation::LocateNextVoxel(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::operator==(), G4SmartVoxelHeader::RefineNodes(), and G4VoxelSafety::SafetyForVoxelHeader().
G4bool G4SmartVoxelProxy::IsHeader () const
Referenced by G4SmartVoxelHeader::CollectEquivalentHeaders(), G4DrawVoxels::ComputeVoxelPolyhedra(), and G4SmartVoxelHeader::operator==().
G4bool G4SmartVoxelProxy::IsNode () const
Referenced by G4SmartVoxelStat::CountHeadsAndNodes(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::operator==(), and G4VoxelSafety::SafetyForVoxelHeader().
G4bool G4SmartVoxelProxy::operator== (const G4SmartVoxelProxy & v) const
Member Data Documentation
G4SmartVoxelHeader* G4SmartVoxelProxy::fHeader = nullptr private
Definition at line 82 of file G4SmartVoxelProxy.hh.
View newest version in sPHENIX GitHub at line 82 of file G4SmartVoxelProxy.hh
G4SmartVoxelNode* G4SmartVoxelProxy::fNode = nullptr private
Definition at line 83 of file G4SmartVoxelProxy.hh.
View newest version in sPHENIX GitHub at line 83 of file G4SmartVoxelProxy.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SmartVoxelProxy.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4SmartVoxelProxy.cc