ECCE @ EIC Software: CexmcChargeExchangeReconstructorMessenger Class Reference
CexmcChargeExchangeReconstructorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcChargeExchangeReconstructorMessenger.hh>
Public Member Functions
CexmcChargeExchangeReconstructorMessenger (CexmcChargeExchangeReconstructor *reconstructor)
~CexmcChargeExchangeReconstructorMessenger ()
void SetNewValue (G4UIcommand *cmd, G4String value)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CexmcChargeExchangeReconstructor * reconstructor
G4UIcmdWithABool * useTableMass
G4UIcmdWithABool * useMassCut
G4UIcmdWithADoubleAndUnit * mCutOPCenter
G4UIcmdWithADoubleAndUnit * mCutNOPCenter
G4UIcmdWithADoubleAndUnit * mCutOPWidth
G4UIcmdWithADoubleAndUnit * mCutNOPWidth
G4UIcmdWithADoubleAndUnit * mCutAngle
G4UIcmdWithABool * useAbsorbedEnergyCut
G4UIcmdWithADoubleAndUnit * aeCutCLCenter
G4UIcmdWithADoubleAndUnit * aeCutCRCenter
G4UIcmdWithADoubleAndUnit * aeCutCLWidth
G4UIcmdWithADoubleAndUnit * aeCutCRWidth
G4UIcmdWithADoubleAndUnit * aeCutAngle
G4UIcmdWithADoubleAndUnit * setExpectedMomentumAmp
G4UIcmdWithADoubleAndUnit * setExpectedMomentumAmpDiff
G4UIcmdWithAString * setEDCollectionAlgorithm
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 56 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcChargeExchangeReconstructorMessenger.hh
Constructor & Destructor Documentation
CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger (CexmcChargeExchangeReconstructor * reconstructor) explicit
Definition at line 53 of file CexmcChargeExchangeReconstructorMessenger.cc.
View newest version in sPHENIX GitHub at line 53 of file CexmcChargeExchangeReconstructorMessenger.cc
References aeCutAngle, aeCutCLCenter, aeCutCLWidth, aeCutCRCenter, aeCutCRWidth, G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, CexmcChargeExchangeReconstructor::GetProductionModelData(), mCutAngle, mCutNOPCenter, mCutNOPWidth, mCutOPCenter, mCutOPWidth, reconstructor, CexmcMessenger::reconstructorDirName, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), setEDCollectionAlgorithm, setExpectedMomentumAmp, setExpectedMomentumAmpDiff, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCandidates(), useAbsorbedEnergyCut, useMassCut, and useTableMass.
CexmcChargeExchangeReconstructorMessenger::~CexmcChargeExchangeReconstructorMessenger ()
Definition at line 247 of file CexmcChargeExchangeReconstructorMessenger.cc.
View newest version in sPHENIX GitHub at line 247 of file CexmcChargeExchangeReconstructorMessenger.cc
References aeCutAngle, aeCutCLCenter, aeCutCLWidth, aeCutCRCenter, aeCutCRWidth, mCutAngle, mCutNOPCenter, mCutNOPWidth, mCutOPCenter, mCutOPWidth, setEDCollectionAlgorithm, setExpectedMomentumAmp, setExpectedMomentumAmpDiff, useAbsorbedEnergyCut, useMassCut, and useTableMass.
Member Function Documentation
void CexmcChargeExchangeReconstructorMessenger::SetNewValue (G4UIcommand * cmd, G4String value) virtual
Reimplemented from G4UImessenger.
Definition at line 268 of file CexmcChargeExchangeReconstructorMessenger.cc.
View newest version in sPHENIX GitHub at line 268 of file CexmcChargeExchangeReconstructorMessenger.cc
References aeCutAngle, aeCutCLCenter, aeCutCLWidth, aeCutCRCenter, aeCutCRWidth, CexmcCollectEDInAdjacentCrystals, CexmcCollectEDInAllCrystals, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), mCutAngle, mCutNOPCenter, mCutNOPWidth, mCutOPCenter, mCutOPWidth, reconstructor, CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCLCenter(), CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCLWidth(), CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCRCenter(), CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutCRWidth(), CexmcChargeExchangeReconstructor::SetAbsorbedEnergyCutEllipseAngle(), setEDCollectionAlgorithm, CexmcChargeExchangeReconstructor::SetEDCollectionAlgorithm(), setExpectedMomentumAmp, CexmcChargeExchangeReconstructor::SetExpectedMomentumAmp(), setExpectedMomentumAmpDiff, CexmcChargeExchangeReconstructor::SetExpectedMomentumAmpDiff(), CexmcChargeExchangeReconstructor::SetMassCutEllipseAngle(), CexmcChargeExchangeReconstructor::SetMassCutNOPCenter(), CexmcChargeExchangeReconstructor::SetMassCutNOPWidth(), CexmcChargeExchangeReconstructor::SetMassCutOPCenter(), CexmcChargeExchangeReconstructor::SetMassCutOPWidth(), useAbsorbedEnergyCut, CexmcChargeExchangeReconstructor::UseAbsorbedEnergyCut(), useMassCut, CexmcChargeExchangeReconstructor::UseMassCut(), useTableMass, and CexmcChargeExchangeReconstructor::UseTableMass().
Member Data Documentation
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::aeCutAngle private
Definition at line 94 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 94 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::aeCutCLCenter private
Definition at line 86 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::aeCutCLWidth private
Definition at line 90 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::aeCutCRCenter private
Definition at line 88 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::aeCutCRWidth private
Definition at line 92 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::mCutAngle private
Definition at line 82 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::mCutNOPCenter private
Definition at line 76 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::mCutNOPWidth private
Definition at line 80 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::mCutOPCenter private
Definition at line 74 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::mCutOPWidth private
Definition at line 78 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
CexmcChargeExchangeReconstructor* CexmcChargeExchangeReconstructorMessenger::reconstructor private
Definition at line 68 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), and SetNewValue().
G4UIcmdWithAString* CexmcChargeExchangeReconstructorMessenger::setEDCollectionAlgorithm private
Definition at line 100 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 100 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::setExpectedMomentumAmp private
Definition at line 96 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithADoubleAndUnit* CexmcChargeExchangeReconstructorMessenger::setExpectedMomentumAmpDiff private
Definition at line 98 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 98 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithABool* CexmcChargeExchangeReconstructorMessenger::useAbsorbedEnergyCut private
Definition at line 84 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithABool* CexmcChargeExchangeReconstructorMessenger::useMassCut private
Definition at line 72 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
G4UIcmdWithABool* CexmcChargeExchangeReconstructorMessenger::useTableMass private
Definition at line 70 of file CexmcChargeExchangeReconstructorMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file CexmcChargeExchangeReconstructorMessenger.hh
Referenced by CexmcChargeExchangeReconstructorMessenger(), SetNewValue(), and ~CexmcChargeExchangeReconstructorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcChargeExchangeReconstructorMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcChargeExchangeReconstructorMessenger.cc