ECCE @ EIC Software: F04PrimaryGeneratorAction Class Reference
F04PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04PrimaryGeneratorAction.hh>
Public Member Functions
F04PrimaryGeneratorAction (F04DetectorConstruction *)
virtual ~F04PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
void SetRndmFlag (G4String val)
void SetXvertex (G4double x)
void SetYvertex (G4double y)
void SetZvertex (G4double z)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
F04DetectorConstruction * fDetector
G4ParticleGun * fParticleGun
F04PrimaryGeneratorMessenger * fGunMessenger
G4String fRndmFlag
G4bool fFirst
G4AffineTransform fGlobal2local
G4double fXvertex
G4double fYvertex
G4double fZvertex
G4bool fVertexdefined
Detailed Description
Definition at line 46 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 46 of file F04PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
F04PrimaryGeneratorAction::F04PrimaryGeneratorAction (F04DetectorConstruction * detectorConstruction)
Definition at line 51 of file F04PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 51 of file F04PrimaryGeneratorAction.cc
References fDetector, fGunMessenger, fParticleGun, fXvertex, fYvertex, fZvertex, G4ParticleTable::GetParticleTable(), F04DetectorConstruction::GetTargetThickness(), MeV, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
F04PrimaryGeneratorAction::~F04PrimaryGeneratorAction () virtual
Definition at line 76 of file F04PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 76 of file F04PrimaryGeneratorAction.cc
References fGunMessenger, and fParticleGun.
Member Function Documentation
void F04PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 84 of file F04PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 84 of file F04PrimaryGeneratorAction.cc
References fDetector, fFirst, fGlobal2local, fParticleGun, fRndmFlag, fVertexdefined, fXvertex, fYvertex, fZvertex, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), G4TouchableHistory::GetHistory(), F04DetectorConstruction::GetTargetRadius(), F04DetectorConstruction::GetTargetThickness(), G4NavigationHistory::GetTopTransform(), G4TransportationManager::GetTransportationManager(), G4Navigator::GetWorldVolume(), G4AffineTransform::Inverse(), G4Navigator::LocateGlobalPointAndSetup(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), G4Navigator::SetWorldVolume(), G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), twopi, and G4InuclParticleNames::z0.
void F04PrimaryGeneratorAction::SetRndmFlag (G4String val) inline
Definition at line 57 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file F04PrimaryGeneratorAction.hh
References fRndmFlag.
Referenced by F04PrimaryGeneratorMessenger::SetNewValue().
void F04PrimaryGeneratorAction::SetXvertex (G4double x)
Definition at line 151 of file F04PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 151 of file F04PrimaryGeneratorAction.cc
References fVertexdefined, fXvertex, G4cout, G4endl, mm, and x.
Referenced by F04PrimaryGeneratorMessenger::SetNewValue().
void F04PrimaryGeneratorAction::SetYvertex (G4double y)
Definition at line 161 of file F04PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 161 of file F04PrimaryGeneratorAction.cc
References fVertexdefined, fYvertex, G4cout, G4endl, mm, and y.
Referenced by F04PrimaryGeneratorMessenger::SetNewValue().
void F04PrimaryGeneratorAction::SetZvertex (G4double z)
Definition at line 171 of file F04PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 171 of file F04PrimaryGeneratorAction.cc
References fVertexdefined, fZvertex, G4cout, G4endl, mm, and z.
Referenced by F04PrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
F04DetectorConstruction* F04PrimaryGeneratorAction::fDetector private
Definition at line 65 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file F04PrimaryGeneratorAction.hh
Referenced by F04PrimaryGeneratorAction(), and GeneratePrimaries().
G4bool F04PrimaryGeneratorAction::fFirst private
Definition at line 73 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file F04PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4AffineTransform F04PrimaryGeneratorAction::fGlobal2local private
Definition at line 75 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 75 of file F04PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
F04PrimaryGeneratorMessenger* F04PrimaryGeneratorAction::fGunMessenger private
Definition at line 69 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file F04PrimaryGeneratorAction.hh
Referenced by F04PrimaryGeneratorAction(), and ~F04PrimaryGeneratorAction().
G4ParticleGun* F04PrimaryGeneratorAction::fParticleGun private
Definition at line 67 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 67 of file F04PrimaryGeneratorAction.hh
Referenced by F04PrimaryGeneratorAction(), GeneratePrimaries(), and ~F04PrimaryGeneratorAction().
G4String F04PrimaryGeneratorAction::fRndmFlag private
Definition at line 71 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file F04PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetRndmFlag().
G4bool F04PrimaryGeneratorAction::fVertexdefined private
Definition at line 79 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 79 of file F04PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), SetXvertex(), SetYvertex(), and SetZvertex().
G4double F04PrimaryGeneratorAction::fXvertex private
Definition at line 77 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file F04PrimaryGeneratorAction.hh
Referenced by F04PrimaryGeneratorAction(), GeneratePrimaries(), and SetXvertex().
G4double F04PrimaryGeneratorAction::fYvertex private
Definition at line 77 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file F04PrimaryGeneratorAction.hh
Referenced by F04PrimaryGeneratorAction(), GeneratePrimaries(), and SetYvertex().
G4double F04PrimaryGeneratorAction::fZvertex private
Definition at line 77 of file F04PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file F04PrimaryGeneratorAction.hh
Referenced by F04PrimaryGeneratorAction(), GeneratePrimaries(), and SetZvertex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04PrimaryGeneratorAction.cc