ECCE @ EIC Software: G4VIStore Class Reference
G4VIStore Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4VIStore.hh>
Public Member Functions
G4VIStore ()
virtual ~G4VIStore ()
virtual G4double GetImportance (const G4GeometryCell &gCell) const =0
virtual G4bool IsKnown (const G4GeometryCell &gCell) const =0
virtual const G4VPhysicalVolume & GetWorldVolume () const =0
Detailed Description
Definition at line 47 of file G4VIStore.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VIStore.hh
Constructor & Destructor Documentation
G4VIStore::G4VIStore ()
Definition at line 33 of file G4VIStore.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VIStore.cc
G4VIStore::~G4VIStore () virtual
Definition at line 37 of file G4VIStore.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VIStore.cc
Member Function Documentation
virtual G4double G4VIStore::GetImportance (const G4GeometryCell & gCell) const pure virtual
Implemented in G4IStore.
Referenced by G4ImportanceProcess::PostStepDoIt(), and G4WeightCutOffProcess::PostStepDoIt().
virtual const G4VPhysicalVolume& G4VIStore::GetWorldVolume () const pure virtual
Implemented in G4IStore.
Referenced by G4GeometrySampler::PrepareImportanceSampling().
virtual G4bool G4VIStore::IsKnown (const G4GeometryCell & gCell) const pure virtual
Implemented in G4IStore.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4VIStore.hh
geant4/tree/geant4-10.6-release/source/geometry/biasing/src/G4VIStore.cc