ECCE @ EIC Software: macros/blob/master/common/G4_EventEvaluator.C File Reference
G4_EventEvaluator.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <eiceval/EventEvaluatorEIC.h>
Namespaces
namespace Enable
namespace EVENT_EVALUATOR
Macros
#define MACRO_EventEvaluator_C
Functions
void Event_Eval (const std::string &filename)
Variables
bool Enable::EVENT_EVAL = false
bool Enable::EVENT_EVAL_DO_HEPMC = false
bool Enable::EVENT_EVAL_DO_EVT_LVL = false
bool Enable::EVENT_EVAL_DO_HITS = false
bool Enable::EVENT_EVAL_DO_HITS_ABSORBER = false
bool Enable::EVENT_EVAL_DO_HITS_CALO = false
bool Enable::EVENT_EVAL_DO_HITS_BLACKHOLE = false
int EVENT_EVALUATOR::Verbosity = 0
float EVENT_EVALUATOR::EnergyThreshold = 0.05
Macro Definition Documentation
#define MACRO_EventEvaluator_C
Definition at line 2 of file G4_EventEvaluator.C.
View newest version in sPHENIX GitHub at line 2 of file G4_EventEvaluator.C
Function Documentation
void Event_Eval (const std::string & filename)
Definition at line 28 of file G4_EventEvaluator.C.
View newest version in sPHENIX GitHub at line 28 of file G4_EventEvaluator.C
References Enable::BECAL, Enable::BLACKHOLE_SAVEHITS, Enable::CEMC, Enable::DIRC_RECO, G4TRACKING::DISPLACED_VERTEX, Enable::DRCALO, Enable::EEMC, Enable::EEMC_CLUSTER, Enable::EEMCH, Enable::EHCAL, EVENT_EVALUATOR::EnergyThreshold, Enable::EVENT_EVAL_DO_EVT_LVL, Enable::EVENT_EVAL_DO_HEPMC, Enable::EVENT_EVAL_DO_HITS, Enable::EVENT_EVAL_DO_HITS_ABSORBER, Enable::EVENT_EVAL_DO_HITS_BLACKHOLE, Enable::EVENT_EVAL_DO_HITS_CALO, Enable::FEMC, Enable::FEMC_CLUSTER, Enable::FHCAL, Enable::FHCAL_CLUSTER, Enable::HCALIN, Enable::HCALOUT, Fun4AllServer::instance(), Enable::LFHCAL, Enable::mRICH_RECO, Fun4AllServer::registerSubsystem(), Enable::RICH_RECO, EventEvaluatorEIC::set_do_BECAL(), EventEvaluatorEIC::set_do_BLACKHOLE(), EventEvaluatorEIC::set_do_CEMC(), EventEvaluatorEIC::set_do_CLUSTERS(), EventEvaluatorEIC::set_do_DRCALO(), EventEvaluatorEIC::set_do_EEMC(), EventEvaluatorEIC::set_do_EEMCG(), EventEvaluatorEIC::set_do_EHCAL(), EventEvaluatorEIC::set_do_FEMC(), EventEvaluatorEIC::set_do_FHCAL(), EventEvaluatorEIC::set_do_GEOMETRY(), EventEvaluatorEIC::set_do_HCALIN(), EventEvaluatorEIC::set_do_HCALOUT(), EventEvaluatorEIC::set_do_HEPMC(), EventEvaluatorEIC::set_do_HITS(), EventEvaluatorEIC::set_do_HITS_ABSORBER(), EventEvaluatorEIC::set_do_HITS_CALO(), EventEvaluatorEIC::set_do_LFHCAL(), EventEvaluatorEIC::set_do_MCPARTICLES(), EventEvaluatorEIC::set_do_PID_LogLikelihood(), EventEvaluatorEIC::set_do_PROJECTIONS(), EventEvaluatorEIC::set_do_store_event_level_info(), EventEvaluatorEIC::set_do_TRACKS(), EventEvaluatorEIC::set_do_VERTEX(), EventEvaluatorEIC::set_reco_tracing_energy_thresholdMC(), Enable::TRACKING, G4EEMCH::SETTING::USEHYBRID, EVENT_EVALUATOR::Verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_runEvaluators().