ECCE @ EIC Software: GammaRayTelTrackerSD Class Reference
GammaRayTelTrackerSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelTrackerSD.hh>
Public Member Functions
GammaRayTelTrackerSD (G4String)
~GammaRayTelTrackerSD ()
void Initialize (G4HCofThisEvent *)
G4bool ProcessHits (G4Step *astep, G4TouchableHistory *ROHist)
void EndOfEvent (G4HCofThisEvent *)
void clear ()
void DrawAll ()
void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
GammaRayTelTrackerHitsCollection * TrackerCollection
GammaRayTelDetectorConstruction * Detector
G4int * ThitXID
G4int * ThitYID
G4int NbOfTKRLayers
G4int NbOfTKRStrips
G4int NbOfTKRChannels
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 50 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 50 of file GammaRayTelTrackerSD.hh
Constructor & Destructor Documentation
GammaRayTelTrackerSD::GammaRayTelTrackerSD (G4String name)
Definition at line 54 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 54 of file GammaRayTelTrackerSD.cc
References G4VSensitiveDetector::collectionName, Detector, GammaRayTelDetectorConstruction::GetNbOfTKRLayers(), GammaRayTelDetectorConstruction::GetNbOfTKRStrips(), GammaRayTelDetectorConstruction::GetNbOfTKRTiles(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4CollectionNameVector::insert(), NbOfTKRChannels, NbOfTKRLayers, NbOfTKRStrips, ThitXID, and ThitYID.
GammaRayTelTrackerSD::~GammaRayTelTrackerSD ()
Definition at line 74 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelTrackerSD.cc
References ThitXID, and ThitYID.
Member Function Documentation
void GammaRayTelTrackerSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 217 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 217 of file GammaRayTelTrackerSD.cc
void GammaRayTelTrackerSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 222 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 222 of file GammaRayTelTrackerSD.cc
void GammaRayTelTrackerSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 198 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 198 of file GammaRayTelTrackerSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), NbOfTKRChannels, ThitXID, ThitYID, and TrackerCollection.
void GammaRayTelTrackerSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 82 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 82 of file GammaRayTelTrackerSD.cc
References G4VSensitiveDetector::collectionName, NbOfTKRChannels, G4VSensitiveDetector::SensitiveDetectorName, ThitXID, ThitYID, and TrackerCollection.
void GammaRayTelTrackerSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 227 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 227 of file GammaRayTelTrackerSD.cc
G4bool GammaRayTelTrackerSD::ProcessHits (G4Step * astep, G4TouchableHistory * ROHist) virtual
Implements G4VSensitiveDetector.
Definition at line 96 of file GammaRayTelTrackerSD.cc.
View newest version in sPHENIX GitHub at line 96 of file GammaRayTelTrackerSD.cc
References GammaRayTelTrackerHit::AddSil(), Detector, edep, G4VPhysicalVolume::GetCopyNo(), G4VPhysicalVolume::GetName(), GammaRayTelDetectorConstruction::GetNbOfTKRStrips(), GammaRayTelDetectorConstruction::GetNbOfTKRTiles(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4TouchableHistory::GetVolume(), G4THitsCollection< T >::insert(), Acts::PrimitivesVisualization::plane, GammaRayTelTrackerHit::SetNSilPlane(), GammaRayTelTrackerHit::SetNStrip(), GammaRayTelTrackerHit::SetPlaneType(), GammaRayTelTrackerHit::SetPos(), ThitXID, ThitYID, and TrackerCollection.
Member Data Documentation
GammaRayTelDetectorConstruction* GammaRayTelTrackerSD::Detector private
Definition at line 67 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 67 of file GammaRayTelTrackerSD.hh
Referenced by GammaRayTelTrackerSD(), and ProcessHits().
G4int GammaRayTelTrackerSD::NbOfTKRChannels private
Definition at line 74 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelTrackerSD.hh
Referenced by EndOfEvent(), GammaRayTelTrackerSD(), and Initialize().
G4int GammaRayTelTrackerSD::NbOfTKRLayers private
Definition at line 72 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 72 of file GammaRayTelTrackerSD.hh
Referenced by GammaRayTelTrackerSD().
G4int GammaRayTelTrackerSD::NbOfTKRStrips private
Definition at line 73 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 73 of file GammaRayTelTrackerSD.hh
Referenced by GammaRayTelTrackerSD().
G4int* GammaRayTelTrackerSD::ThitXID private
Definition at line 69 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 69 of file GammaRayTelTrackerSD.hh
Referenced by EndOfEvent(), GammaRayTelTrackerSD(), Initialize(), ProcessHits(), and ~GammaRayTelTrackerSD().
G4int* GammaRayTelTrackerSD::ThitYID private
Definition at line 70 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 70 of file GammaRayTelTrackerSD.hh
Referenced by EndOfEvent(), GammaRayTelTrackerSD(), Initialize(), ProcessHits(), and ~GammaRayTelTrackerSD().
GammaRayTelTrackerHitsCollection* GammaRayTelTrackerSD::TrackerCollection private
Definition at line 66 of file GammaRayTelTrackerSD.hh.
View newest version in sPHENIX GitHub at line 66 of file GammaRayTelTrackerSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelTrackerSD.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelTrackerSD.cc