ECCE @ EIC Software: G4ChipsComponentXS Class Reference
G4ChipsComponentXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsComponentXS.hh>
Public Member Functions
G4ChipsComponentXS ()
virtual ~G4ChipsComponentXS ()
virtual G4double GetTotalElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double N)
virtual G4double GetTotalIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int N)
virtual G4double GetInelasticElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double N)
virtual G4double GetInelasticIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int N)
virtual G4double GetElasticElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double N)
virtual G4double GetElasticIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int N)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
Public Member Functions inherited from G4VComponentCrossSection
G4VComponentCrossSection (const G4String &nam="")
virtual ~G4VComponentCrossSection ()
G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
virtual G4double ComputeQuasiElasticRatio (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
virtual void Description (std::ostream &) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
const G4String & GetName () const
Private Member Functions
G4ChipsComponentXS & operator= (const G4ChipsComponentXS &right)
G4ChipsComponentXS (const G4ChipsComponentXS &)
Private Attributes
const G4double fUpperLimit
const G4double fLowerLimit
G4ChipsProtonElasticXS * PxsManagerEl
G4ChipsProtonInelasticXS * PxsManagerInEl
G4ChipsNeutronElasticXS * NxsManagerEl
G4ChipsNeutronInelasticXS * NxsManagerInEl
G4ChipsAntiBaryonElasticXS * PBARxsManagerEl
G4ChipsAntiBaryonInelasticXS * PBARxsManagerInEl
G4ChipsPionPlusElasticXS * PIPxsManagerEl
G4ChipsPionPlusInelasticXS * PIPxsManagerInEl
G4ChipsPionMinusElasticXS * PIMxsManagerEl
G4ChipsPionMinusInelasticXS * PIMxsManagerInEl
G4ChipsKaonPlusElasticXS * KPxsManagerEl
G4ChipsKaonPlusInelasticXS * KPxsManagerInEl
G4ChipsKaonMinusElasticXS * KMxsManagerEl
G4ChipsKaonMinusInelasticXS * KMxsManagerInEl
G4ChipsKaonZeroElasticXS * KZxsManagerEl
G4ChipsKaonZeroInelasticXS * KZxsManagerInEl
G4ChipsHyperonElasticXS * HxsManagerEl
G4ChipsHyperonInelasticXS * HxsManagerInEl
Detailed Description
Definition at line 76 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ChipsComponentXS.hh
Constructor & Destructor Documentation
G4ChipsComponentXS::G4ChipsComponentXS ()
Definition at line 45 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ChipsComponentXS.cc
References G4ChipsAntiBaryonInelasticXS::Default_Name(), G4ChipsProtonElasticXS::Default_Name(), G4ChipsProtonInelasticXS::Default_Name(), G4ChipsPionPlusElasticXS::Default_Name(), G4ChipsHyperonElasticXS::Default_Name(), G4ChipsHyperonInelasticXS::Default_Name(), G4ChipsKaonPlusElasticXS::Default_Name(), G4ChipsKaonMinusInelasticXS::Default_Name(), G4ChipsNeutronElasticXS::Default_Name(), G4ChipsNeutronInelasticXS::Default_Name(), G4ChipsPionMinusElasticXS::Default_Name(), G4ChipsPionMinusInelasticXS::Default_Name(), G4ChipsAntiBaryonElasticXS::Default_Name(), G4ChipsKaonMinusElasticXS::Default_Name(), G4ChipsKaonPlusInelasticXS::Default_Name(), G4ChipsPionPlusInelasticXS::Default_Name(), G4ChipsKaonZeroElasticXS::Default_Name(), G4ChipsKaonZeroInelasticXS::Default_Name(), G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), HxsManagerEl, HxsManagerInEl, G4CrossSectionDataSetRegistry::Instance(), KMxsManagerEl, KMxsManagerInEl, KPxsManagerEl, KPxsManagerInEl, KZxsManagerEl, KZxsManagerInEl, NxsManagerEl, NxsManagerInEl, PBARxsManagerEl, PBARxsManagerInEl, PIMxsManagerEl, PIMxsManagerInEl, PIPxsManagerEl, PIPxsManagerInEl, PxsManagerEl, and PxsManagerInEl.
G4ChipsComponentXS::~G4ChipsComponentXS () virtual
Definition at line 77 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ChipsComponentXS.cc
G4ChipsComponentXS::G4ChipsComponentXS (const G4ChipsComponentXS &) private
Member Function Documentation
virtual void G4ChipsComponentXS::BuildPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 112 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ChipsComponentXS.hh
virtual void G4ChipsComponentXS::DumpPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 116 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ChipsComponentXS.hh
G4double G4ChipsComponentXS::GetElasticElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double N) virtual
Implements G4VComponentCrossSection.
Definition at line 191 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 191 of file G4ChipsComponentXS.cc
References G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), and momentum.
G4double G4ChipsComponentXS::GetElasticIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int N) virtual
Implements G4VComponentCrossSection.
Definition at line 228 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ChipsComponentXS.cc
G4double G4ChipsComponentXS::GetInelasticElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double N) virtual
Implements G4VComponentCrossSection.
Definition at line 148 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 148 of file G4ChipsComponentXS.cc
References G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), and momentum.
G4double G4ChipsComponentXS::GetInelasticIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int N) virtual
Implements G4VComponentCrossSection.
Definition at line 186 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 186 of file G4ChipsComponentXS.cc
G4double G4ChipsComponentXS::GetTotalElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double N) virtual
Implements G4VComponentCrossSection.
Definition at line 83 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsComponentXS.cc
References G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), and momentum.
G4double G4ChipsComponentXS::GetTotalIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int N) virtual
Implements G4VComponentCrossSection.
Definition at line 143 of file G4ChipsComponentXS.cc.
View newest version in sPHENIX GitHub at line 143 of file G4ChipsComponentXS.cc
G4ChipsComponentXS& G4ChipsComponentXS::operator= (const G4ChipsComponentXS & right) private
Member Data Documentation
const G4double G4ChipsComponentXS::fLowerLimit private
Definition at line 124 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ChipsComponentXS.hh
const G4double G4ChipsComponentXS::fUpperLimit private
Definition at line 123 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ChipsComponentXS.hh
G4ChipsHyperonElasticXS* G4ChipsComponentXS::HxsManagerEl private
Definition at line 150 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsHyperonInelasticXS* G4ChipsComponentXS::HxsManagerInEl private
Definition at line 151 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsKaonMinusElasticXS* G4ChipsComponentXS::KMxsManagerEl private
Definition at line 144 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsKaonMinusInelasticXS* G4ChipsComponentXS::KMxsManagerInEl private
Definition at line 145 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsKaonPlusElasticXS* G4ChipsComponentXS::KPxsManagerEl private
Definition at line 141 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsKaonPlusInelasticXS* G4ChipsComponentXS::KPxsManagerInEl private
Definition at line 142 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsKaonZeroElasticXS* G4ChipsComponentXS::KZxsManagerEl private
Definition at line 147 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsKaonZeroInelasticXS* G4ChipsComponentXS::KZxsManagerInEl private
Definition at line 148 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsNeutronElasticXS* G4ChipsComponentXS::NxsManagerEl private
Definition at line 129 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsNeutronInelasticXS* G4ChipsComponentXS::NxsManagerInEl private
Definition at line 130 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsAntiBaryonElasticXS* G4ChipsComponentXS::PBARxsManagerEl private
Definition at line 132 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsAntiBaryonInelasticXS* G4ChipsComponentXS::PBARxsManagerInEl private
Definition at line 133 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsPionMinusElasticXS* G4ChipsComponentXS::PIMxsManagerEl private
Definition at line 138 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsPionMinusInelasticXS* G4ChipsComponentXS::PIMxsManagerInEl private
Definition at line 139 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsPionPlusElasticXS* G4ChipsComponentXS::PIPxsManagerEl private
Definition at line 135 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsPionPlusInelasticXS* G4ChipsComponentXS::PIPxsManagerInEl private
Definition at line 136 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsProtonElasticXS* G4ChipsComponentXS::PxsManagerEl private
Definition at line 126 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
G4ChipsProtonInelasticXS* G4ChipsComponentXS::PxsManagerInEl private
Definition at line 127 of file G4ChipsComponentXS.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ChipsComponentXS.hh
Referenced by G4ChipsComponentXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsComponentXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsComponentXS.cc