ECCE @ EIC Software: G4TrackingInformation Class Reference
G4TrackingInformation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4TrackingInformation.hh>
Public Member Functions
G4TrackingInformation ()
~G4TrackingInformation ()
bool IsLeadingStep ()
void SetLeadingStep (bool value)
G4shared_ptr< G4ProcessState_Lock > GetProcessState (size_t index)
void RecordProcessState (G4shared_ptr< G4ProcessState_Lock >, size_t index)
void SetStepProcessorState (G4ITStepProcessorState_Lock *)
G4ITStepProcessorState_Lock * GetStepProcessorState ()
G4TrackStateManager & GetTrackStateManager ()
G4Trajectory_Lock * GetTrajectory_Lock ()
void SetTrajectory_Lock (G4Trajectory_Lock *trajLock)
void RecordCurrentPositionNTime (G4Track *)
const G4ThreeVector & GetPreStepPosition () const
G4double GetPreStepLocalTime () const
G4double GetPreStepGlobalTime () const
void SetNavigatorState (G4ITNavigatorState_Lock *)
G4ITNavigatorState_Lock * GetNavigatorState () const
Protected Member Functions
G4TrackingInformation (const G4TrackingInformation &other)
G4TrackingInformation & operator= (const G4TrackingInformation &other)
Protected Attributes
G4bool fStepLeader
G4Trajectory_Lock * fpTrajectory_Lock
G4TrackStateManager fTrackStateManager
G4ThreeVector fRecordedTrackPosition
G4double fRecordedTrackLocalTime
G4double fRecordedTrackGlobalTime
G4ITNavigatorState_Lock * fNavigatorState
std::vector< G4shared_ptr
< G4ProcessState_Lock > > fProcessState
G4ITStepProcessorState_Lock * fpStepProcessorState
Friends
class G4ITStepProcessor
Detailed Description
The class G4TrackingInformation (hold by G4IT) emcompasses processes informations computed at the PS/AS/AtRest/InteractionLength stage, and also, the selection of processes for the given step.
Definition at line 79 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 79 of file G4TrackingInformation.hh
Constructor & Destructor Documentation
G4TrackingInformation::G4TrackingInformation ()
Definition at line 40 of file G4TrackingInformation.cc.
View newest version in sPHENIX GitHub at line 40 of file G4TrackingInformation.cc
References fNavigatorState, fpStepProcessorState, fpTrajectory_Lock, fRecordedTrackGlobalTime, and fRecordedTrackLocalTime.
G4TrackingInformation::~G4TrackingInformation ()
Definition at line 52 of file G4TrackingInformation.cc.
View newest version in sPHENIX GitHub at line 52 of file G4TrackingInformation.cc
References fNavigatorState, fProcessState, and fpStepProcessorState.
G4TrackingInformation::G4TrackingInformation (const G4TrackingInformation & other) protected
Copy constructor
Parameters
other Object to copy from
Definition at line 73 of file G4TrackingInformation.cc.
View newest version in sPHENIX GitHub at line 73 of file G4TrackingInformation.cc
References fNavigatorState, fpTrajectory_Lock, fRecordedTrackGlobalTime, and fRecordedTrackLocalTime.
Member Function Documentation
G4ITNavigatorState_Lock * G4TrackingInformation::GetNavigatorState () const inline
Definition at line 256 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 256 of file G4TrackingInformation.hh
References fNavigatorState.
Referenced by G4ITStepProcessor::InitDefineStep(), and G4ITStepProcessor::SetInitialStep().
G4double G4TrackingInformation::GetPreStepGlobalTime () const inline
Definition at line 235 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 235 of file G4TrackingInformation.hh
References fRecordedTrackGlobalTime.
Referenced by G4IT::GetPreStepGlobalTime().
G4double G4TrackingInformation::GetPreStepLocalTime () const inline
Definition at line 240 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 240 of file G4TrackingInformation.hh
References fRecordedTrackLocalTime.
Referenced by G4IT::GetPreStepLocalTime().
const G4ThreeVector & G4TrackingInformation::GetPreStepPosition () const inline
Definition at line 245 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 245 of file G4TrackingInformation.hh
References fRecordedTrackPosition.
Referenced by G4IT::GetPreStepPosition().
G4shared_ptr< G4ProcessState_Lock > G4TrackingInformation::GetProcessState (size_t index)
Every process should store the information computed at the InteractionLegth stage in the track.
Definition at line 106 of file G4TrackingInformation.cc.
View newest version in sPHENIX GitHub at line 106 of file G4TrackingInformation.cc
References FatalErrorInArgument, fProcessState, G4Exception(), and G4VITProcess::GetMaxProcessIndex().
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength(), and G4ITStepProcessor::GetAtRestIL().
G4ITStepProcessorState_Lock * G4TrackingInformation::GetStepProcessorState () inline
Definition at line 215 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 215 of file G4TrackingInformation.hh
References fpStepProcessorState.
Referenced by G4ITStepProcessor::SetupMembers().
G4TrackStateManager& G4TrackingInformation::GetTrackStateManager () inline
Definition at line 137 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 137 of file G4TrackingInformation.hh
References fTrackStateManager.
Referenced by G4ITTransportation::AlongStepGetPhysicalInteractionLength(), and G4DNABrownianTransportation::ComputeGeomLimit().
G4Trajectory_Lock* G4TrackingInformation::GetTrajectory_Lock () inline
Definition at line 147 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 147 of file G4TrackingInformation.hh
References fpTrajectory_Lock.
Referenced by ITTrackingInteractivity::AppendStep(), ITTrackingInteractivity::EndTracking(), and ITTrackingInteractivity::StartTracking().
bool G4TrackingInformation::IsLeadingStep () inline
If the track is the one having the minimum step time, then it "leads" the step. It will interact will all the other tracks will be transported.
Definition at line 90 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4TrackingInformation.hh
References fStepLeader.
G4TrackingInformation & G4TrackingInformation::operator= (const G4TrackingInformation & other) protected
Assignment operator
Parameters
other Object to assign from
Returns
A reference to this
Definition at line 85 of file G4TrackingInformation.cc.
View newest version in sPHENIX GitHub at line 85 of file G4TrackingInformation.cc
void G4TrackingInformation::RecordCurrentPositionNTime (G4Track * track)
Definition at line 120 of file G4TrackingInformation.cc.
View newest version in sPHENIX GitHub at line 120 of file G4TrackingInformation.cc
References fRecordedTrackGlobalTime, fRecordedTrackLocalTime, fRecordedTrackPosition, G4Track::GetGlobalTime(), G4Track::GetLocalTime(), and G4Track::GetPosition().
Referenced by G4IT::RecordCurrentPositionNTime().
void G4TrackingInformation::RecordProcessState (G4shared_ptr< G4ProcessState_Lock > state, size_t index) inline
Definition at line 228 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 228 of file G4TrackingInformation.hh
References fProcessState.
Referenced by G4VITProcess::StartTracking().
void G4TrackingInformation::SetLeadingStep (bool value) inline
Definition at line 94 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4TrackingInformation.hh
References fStepLeader.
Referenced by G4ITLeadingTracks::PrepareLeadingTracks(), and G4ITLeadingTracks::Reset().
void G4TrackingInformation::SetNavigatorState (G4ITNavigatorState_Lock * state) inline
Definition at line 250 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 250 of file G4TrackingInformation.hh
References fNavigatorState.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength(), and G4ITStepProcessor::SetInitialStep().
void G4TrackingInformation::SetStepProcessorState (G4ITStepProcessorState_Lock * state) inline
Definition at line 210 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 210 of file G4TrackingInformation.hh
References fpStepProcessorState.
Referenced by G4ITStepProcessor::InitDefineStep().
void G4TrackingInformation::SetTrajectory_Lock (G4Trajectory_Lock * trajLock) inline
Definition at line 152 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 152 of file G4TrackingInformation.hh
References fpTrajectory_Lock.
Referenced by ITTrackingInteractivity::EndTracking(), and ITTrackingInteractivity::StartTracking().
Friends And Related Function Documentation
friend class G4ITStepProcessor friend
Definition at line 168 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 168 of file G4TrackingInformation.hh
Member Data Documentation
G4ITNavigatorState_Lock* G4TrackingInformation::fNavigatorState protected
Definition at line 182 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 182 of file G4TrackingInformation.hh
Referenced by G4TrackingInformation(), GetNavigatorState(), SetNavigatorState(), and ~G4TrackingInformation().
std::vector<G4shared_ptr<G4ProcessState_Lock> > G4TrackingInformation::fProcessState protected
Holds the information related to processes Indexed on GetPhysIntVector (cf. G4ITStepProcessor header)
Definition at line 191 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 191 of file G4TrackingInformation.hh
Referenced by GetProcessState(), RecordProcessState(), and ~G4TrackingInformation().
G4ITStepProcessorState_Lock* G4TrackingInformation::fpStepProcessorState protected
Definition at line 194 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 194 of file G4TrackingInformation.hh
Referenced by G4TrackingInformation(), GetStepProcessorState(), SetStepProcessorState(), and ~G4TrackingInformation().
G4Trajectory_Lock* G4TrackingInformation::fpTrajectory_Lock protected
Definition at line 172 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 172 of file G4TrackingInformation.hh
Referenced by G4TrackingInformation(), GetTrajectory_Lock(), and SetTrajectory_Lock().
G4double G4TrackingInformation::fRecordedTrackGlobalTime protected
Definition at line 179 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 179 of file G4TrackingInformation.hh
Referenced by G4TrackingInformation(), GetPreStepGlobalTime(), and RecordCurrentPositionNTime().
G4double G4TrackingInformation::fRecordedTrackLocalTime protected
Definition at line 178 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 178 of file G4TrackingInformation.hh
Referenced by G4TrackingInformation(), GetPreStepLocalTime(), and RecordCurrentPositionNTime().
G4ThreeVector G4TrackingInformation::fRecordedTrackPosition protected
Definition at line 177 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 177 of file G4TrackingInformation.hh
Referenced by GetPreStepPosition(), and RecordCurrentPositionNTime().
G4bool G4TrackingInformation::fStepLeader protected
Definition at line 170 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4TrackingInformation.hh
Referenced by IsLeadingStep(), and SetLeadingStep().
G4TrackStateManager G4TrackingInformation::fTrackStateManager protected
Definition at line 174 of file G4TrackingInformation.hh.
View newest version in sPHENIX GitHub at line 174 of file G4TrackingInformation.hh
Referenced by GetTrackStateManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4TrackingInformation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4TrackingInformation.cc