ECCE @ EIC Software: G4VParticlePropertyReporter Class Reference
G4VParticlePropertyReporter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/particles/utils/include/G4VParticlePropertyReporter.hh>
Public Types
typedef std::vector
< G4ParticlePropertyData * > G4PPDContainer
Public Member Functions
G4VParticlePropertyReporter ()
virtual ~G4VParticlePropertyReporter ()
G4bool operator== (const G4VParticlePropertyReporter &right) const
G4bool operator!= (const G4VParticlePropertyReporter &right) const
virtual G4bool FillList (G4String name)
virtual void Clear ()
virtual void Print (const G4String &option)=0
const G4PPDContainer & GetList () const
Protected Attributes
G4PPDContainer pList
G4ParticlePropertyTable * pPropertyTable
Detailed Description
Definition at line 45 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VParticlePropertyReporter.hh
Member Typedef Documentation
typedef std::vector<G4ParticlePropertyData*> G4VParticlePropertyReporter::G4PPDContainer
Definition at line 63 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VParticlePropertyReporter.hh
Constructor & Destructor Documentation
G4VParticlePropertyReporter::G4VParticlePropertyReporter ()
Definition at line 40 of file G4VParticlePropertyReporter.cc.
View newest version in sPHENIX GitHub at line 40 of file G4VParticlePropertyReporter.cc
References G4ParticlePropertyTable::GetParticlePropertyTable(), and pPropertyTable.
G4VParticlePropertyReporter::~G4VParticlePropertyReporter () virtual
Definition at line 46 of file G4VParticlePropertyReporter.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VParticlePropertyReporter.cc
References G4ParticlePropertyTable::Clear(), pList, and pPropertyTable.
Member Function Documentation
void G4VParticlePropertyReporter::Clear () virtual
Definition at line 85 of file G4VParticlePropertyReporter.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VParticlePropertyReporter.cc
References pList.
G4bool G4VParticlePropertyReporter::FillList (G4String name) virtual
Definition at line 53 of file G4VParticlePropertyReporter.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VParticlePropertyReporter.cc
References G4ParticleTable::GetIterator(), G4ParticlePropertyTable::GetParticleProperty(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), particle, pList, pPropertyTable, G4ParticleTableIterator< K, V >::reset(), theParticleIterator, and G4ParticleTableIterator< K, V >::value().
const G4PPDContainer& G4VParticlePropertyReporter::GetList () const inline
Definition at line 76 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VParticlePropertyReporter.hh
References pList.
G4bool G4VParticlePropertyReporter::operator!= (const G4VParticlePropertyReporter & right) const inline
Definition at line 59 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VParticlePropertyReporter.hh
G4bool G4VParticlePropertyReporter::operator== (const G4VParticlePropertyReporter & right) const inline
Definition at line 56 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VParticlePropertyReporter.hh
virtual void G4VParticlePropertyReporter::Print (const G4String & option) pure virtual
Implemented in G4HtmlPPReporter, G4SimplePPReporter, and G4TextPPReporter.
Member Data Documentation
G4PPDContainer G4VParticlePropertyReporter::pList protected
Definition at line 79 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VParticlePropertyReporter.hh
Referenced by Clear(), FillList(), G4HtmlPPReporter::GenerateIndex(), GetList(), G4TextPPReporter::Print(), G4SimplePPReporter::Print(), G4HtmlPPReporter::Print(), and ~G4VParticlePropertyReporter().
G4ParticlePropertyTable* G4VParticlePropertyReporter::pPropertyTable protected
Definition at line 80 of file G4VParticlePropertyReporter.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VParticlePropertyReporter.hh
Referenced by FillList(), G4VParticlePropertyReporter(), and ~G4VParticlePropertyReporter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/utils/include/G4VParticlePropertyReporter.hh
geant4/tree/geant4-10.6-release/source/particles/utils/src/G4VParticlePropertyReporter.cc