ECCE @ EIC Software: G4CollisionMesonBaryonToResonance Class Reference
G4CollisionMesonBaryonToResonance Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionMesonBaryonToResonance.hh>
Public Member Functions
G4CollisionMesonBaryonToResonance ()
virtual ~G4CollisionMesonBaryonToResonance ()
Public Member Functions inherited from G4CollisionComposite
G4CollisionComposite ()
virtual ~G4CollisionComposite ()
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
void AddComponent (G4VCollision *aC)
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
virtual const G4CollisionVector * GetComponents () const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const std::vector
< G4String > & GetListOfColliders (G4int) const
Private Member Functions
G4CollisionMesonBaryonToResonance (const G4CollisionMesonBaryonToResonance &)
G4CollisionMesonBaryonToResonance & operator= (const G4CollisionMesonBaryonToResonance &)
virtual G4String GetName () const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Attributes
G4XpipNTotal thepipp
G4XpimNTotal thepimp
Detailed Description
Definition at line 44 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 44 of file G4CollisionMesonBaryonToResonance.hh
Constructor & Destructor Documentation
G4CollisionMesonBaryonToResonance::G4CollisionMesonBaryonToResonance ()
Definition at line 47 of file G4CollisionMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 47 of file G4CollisionMesonBaryonToResonance.cc
References G4CollisionComposite::AddComponent(), G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), G4PionPlus::PionPlusDefinition(), and G4Proton::ProtonDefinition().
virtual G4CollisionMesonBaryonToResonance::~G4CollisionMesonBaryonToResonance () inline virtual
Definition at line 50 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 50 of file G4CollisionMesonBaryonToResonance.hh
G4CollisionMesonBaryonToResonance::G4CollisionMesonBaryonToResonance (const G4CollisionMesonBaryonToResonance &) private
Member Function Documentation
virtual G4double G4CollisionMesonBaryonToResonance::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const inline private virtual
Reimplemented from G4CollisionComposite.
Definition at line 58 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 58 of file G4CollisionMesonBaryonToResonance.hh
References G4CollisionComposite::CrossSection().
virtual const std::vector<G4String>& G4CollisionMesonBaryonToResonance::GetListOfColliders (G4int) const inline protected virtual
Implements G4VCollision.
Definition at line 87 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 87 of file G4CollisionMesonBaryonToResonance.hh
virtual G4String G4CollisionMesonBaryonToResonance::GetName (void) const inline private virtual
Implements G4VCollision.
Definition at line 57 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 57 of file G4CollisionMesonBaryonToResonance.hh
G4CollisionMesonBaryonToResonance& G4CollisionMesonBaryonToResonance::operator= (const G4CollisionMesonBaryonToResonance &) private
Member Data Documentation
G4XpimNTotal G4CollisionMesonBaryonToResonance::thepimp private
Definition at line 95 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 95 of file G4CollisionMesonBaryonToResonance.hh
G4XpipNTotal G4CollisionMesonBaryonToResonance::thepipp private
Definition at line 94 of file G4CollisionMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CollisionMesonBaryonToResonance.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionMesonBaryonToResonance.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CollisionMesonBaryonToResonance.cc