ECCE @ EIC Software: G4ECDecay Class Reference
G4ECDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4ECDecay.hh>
Public Member Functions
G4ECDecay (const G4ParticleDefinition *theParentNucleus, const G4double &theBR, const G4double &Qvalue, const G4double &excitation, const G4Ions::G4FloatLevelBase &flb, const G4RadioactiveDecayMode &mode)
virtual ~G4ECDecay ()
virtual G4DecayProducts * DecayIt (G4double)
virtual void DumpNuclearInfo ()
void SetARM (G4bool onoff)
Public Member Functions inherited from G4NuclearDecay
G4NuclearDecay (const G4String &channelName, const G4RadioactiveDecayMode &mode, const G4double &excitation, const G4Ions::G4FloatLevelBase &floatingLevel)
virtual ~G4NuclearDecay ()
G4RadioactiveDecayMode GetDecayMode ()
G4double GetDaughterExcitation ()
G4Ions::G4FloatLevelBase GetFloatingLevel ()
G4ParticleDefinition * GetDaughterNucleus ()
void SetHLThreshold (G4double HLT)
G4double GetHLThreshold ()
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Private Member Functions
void DefineSubshellProbabilities (G4int Z, G4int A)
Private Attributes
const G4double transitionQ
G4bool applyARM
G4double PL1
G4double PL2
G4double PM1
G4double PM2
G4double PN1
G4double PN2
Static Private Attributes
static const G4double PL2overPL1 [100]
static const G4double PM2overPM1 [100]
static const G4double PN2overPN1 [100]
Additional Inherited Members
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Protected Attributes inherited from G4NuclearDecay
const G4RadioactiveDecayMode theMode
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 42 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ECDecay.hh
Constructor & Destructor Documentation
G4ECDecay::G4ECDecay (const G4ParticleDefinition * theParentNucleus, const G4double & theBR, const G4double & Qvalue, const G4double & excitation, const G4Ions::G4FloatLevelBase & flb, const G4RadioactiveDecayMode & mode)
Definition at line 47 of file G4ECDecay.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ECDecay.cc
References DefineSubshellProbabilities(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4VDecayChannel::SetBR(), G4VDecayChannel::SetDaughter(), G4VDecayChannel::SetNumberOfDaughters(), and G4VDecayChannel::SetParent().
G4ECDecay::~G4ECDecay () virtual
Definition at line 69 of file G4ECDecay.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ECDecay.cc
Member Function Documentation
G4DecayProducts * G4ECDecay::DecayIt (G4double) virtual
Implements G4VDecayChannel.
Definition at line 73 of file G4ECDecay.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ECDecay.cc
References applyARM, G4LossTableManager::AtomDeexcitation(), G4AtomicShell::BindingEnergy(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), G4EmParameters::DeexcitationIgnoreCut(), G4Electron::Electron(), FatalException, G4Exception(), G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4VAtomDeexcitation::GenerateParticles(), G4DynamicParticle::Get4Momentum(), G4ParticleDefinition::GetAtomicNumber(), G4VAtomDeexcitation::GetAtomicShell(), G4AtomicShells::GetNumberOfShells(), G4ParticleDefinition::GetPDGMass(), G4EmParameters::Instance(), G4LossTableManager::Instance(), G4VAtomDeexcitation::IsFluoActive(), keV, KshellEC, LshellEC, MshellEC, NshellEC, phi, PL1, PL2, PM1, PM2, PN1, PN2, G4DecayProducts::PushProducts(), Q, rad, ran(), G4DynamicParticle::Set4Momentum(), G4NuclearDecay::theMode, transitionQ, and twopi.
void G4ECDecay::DefineSubshellProbabilities (G4int Z, G4int A) private
Definition at line 230 of file G4ECDecay.cc.
View newest version in sPHENIX GitHub at line 230 of file G4ECDecay.cc
References PL1, PL2, PL2overPL1, PM1, PM2, PM2overPM1, PN1, PN2, and PN2overPN1.
Referenced by G4ECDecay().
void G4ECDecay::DumpNuclearInfo () virtual
Implements G4NuclearDecay.
Definition at line 212 of file G4ECDecay.cc.
View newest version in sPHENIX GitHub at line 212 of file G4ECDecay.cc
References G4cout, G4endl, G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughterName(), G4VDecayChannel::GetParentName(), G4NuclearDecay::theMode, and transitionQ.
void G4ECDecay::SetARM (G4bool onoff) inline
Definition at line 56 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ECDecay.hh
References applyARM.
Referenced by G4RadioactiveDecayBase::LoadDecayTable(), and G4RadioactiveDecay::LoadDecayTable().
Member Data Documentation
G4bool G4ECDecay::applyARM private
Definition at line 64 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ECDecay.hh
Referenced by DecayIt(), and SetARM().
G4double G4ECDecay::PL1 private
Definition at line 65 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ECDecay.hh
Referenced by DecayIt(), and DefineSubshellProbabilities().
G4double G4ECDecay::PL2 private
Definition at line 65 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ECDecay.hh
Referenced by DecayIt(), and DefineSubshellProbabilities().
const G4double G4ECDecay::PL2overPL1 static private
Initial value:
= {
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   1.8722e-04,
2.6438e-04,   3.5456e-04,   4.5790e-04,   6.1588e-04,   7.8944e-04,   9.8530e-04,   1.2030e-03,
1.4361e-03,   1.6886e-03,   1.9609e-03,   2.2641e-03,   2.5674e-03,   2.9019e-03,   3.2577e-03,
3.6338e-03,   4.0310e-03,   4.4541e-03,   4.8943e-03,   5.3620e-03,   5.8523e-03,   6.3650e-03,
6.9061e-03,   7.4607e-03,   8.0398e-03,   8.6417e-03,   9.2665e-03,   9.9150e-03,   1.0588e-02,
1.1284e-02,   1.2004e-02,   1.2744e-02,   1.3518e-02,   1.4312e-02,   1.5136e-02,   1.5981e-02,
1.6857e-02,   1.7764e-02,   1.8696e-02,   1.9682e-02,   2.0642e-02,   2.1661e-02,   2.2708e-02,
2.3788e-02,   2.4896e-02,   2.6036e-02,   2.7217e-02,   2.8409e-02,   2.9646e-02,   3.0917e-02,
3.2220e-02,   3.3561e-02,   3.4937e-02,   3.6353e-02,   3.7805e-02,   3.9297e-02,   4.0826e-02,
4.2399e-02,   4.4010e-02,   4.5668e-02,   4.7368e-02,   4.9115e-02,   5.0896e-02,   5.2744e-02,
5.4625e-02,   5.6565e-02,   5.8547e-02,   6.0593e-02,   6.2690e-02,   6.4844e-02,   6.7068e-02,
6.9336e-02,   7.1667e-02,   7.4075e-02,   7.6544e-02,   7.9085e-02,   8.1688e-02,   8.4371e-02,
8.7135e-02,   8.9995e-02,   9.2919e-02,   9.5949e-02,   9.9036e-02,   1.0226e-01,   1.0555e-01,
1.0899e-01,   1.1249e-01,   1.1613e-01,   1.1989e-01,   1.2379e-01,   1.2780e-01,   1.3196e-01,
1.3627e-01,   1.4071e-01}
Definition at line 68 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ECDecay.hh
Referenced by DefineSubshellProbabilities().
G4double G4ECDecay::PM1 private
Definition at line 65 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ECDecay.hh
Referenced by DecayIt(), and DefineSubshellProbabilities().
G4double G4ECDecay::PM2 private
Definition at line 65 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ECDecay.hh
Referenced by DecayIt(), and DefineSubshellProbabilities().
const G4double G4ECDecay::PM2overPM1 static private
Initial value:
= {
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
1.0210e-03,   1.2641e-03,   1.5231e-03,   1.7990e-03,   2.1938e-03,   2.5863e-03,   2.9621e-03,
3.3637e-03,   3.7909e-03,   4.2049e-03,   4.7021e-03,   5.1791e-03,   5.6766e-03,   6.1952e-03,
6.7045e-03,   7.2997e-03,   7.9438e-03,   8.6271e-03,   9.3294e-03,   1.0058e-02,   1.0813e-02,
1.1594e-02,   1.2408e-02,   1.3244e-02,   1.4118e-02,   1.5023e-02,   1.5962e-02,   1.6919e-02,
1.7910e-02,   1.8934e-02,   1.9986e-02,   2.1072e-02,   2.2186e-02,   2.3336e-02,   2.4524e-02,
2.5750e-02,   2.7006e-02,   2.8302e-02,   2.9629e-02,   3.0994e-02,   3.2399e-02,   3.3845e-02,
3.5328e-02,   3.6852e-02,   3.8414e-02,   4.0025e-02,   4.1673e-02,   4.3368e-02,   4.5123e-02,
4.6909e-02,   4.8767e-02,   5.0662e-02,   5.2612e-02,   5.4612e-02,   5.6662e-02,   5.8773e-02,
6.0930e-02,   6.3141e-02,   6.5413e-02,   6.7752e-02,   7.0139e-02,   7.2603e-02,   7.5127e-02,
7.7721e-02,   8.0408e-02,   8.3128e-02,   8.5949e-02,   8.8843e-02,   9.1824e-02,   9.4888e-02,
9.8025e-02,   1.0130e-01,   1.0463e-01,   1.0806e-01,   1.1159e-01,   1.1526e-01,   1.1900e-01,
1.2290e-01,   1.2688e-01,   1.3101e-01,   1.3528e-01,   1.3969e-01,   1.4425e-01,   1.4896e-01,
1.5384e-01,   1.5887e-01}
Definition at line 69 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ECDecay.hh
Referenced by DefineSubshellProbabilities().
G4double G4ECDecay::PN1 private
Definition at line 65 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ECDecay.hh
Referenced by DecayIt(), and DefineSubshellProbabilities().
G4double G4ECDecay::PN2 private
Definition at line 65 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ECDecay.hh
Referenced by DecayIt(), and DefineSubshellProbabilities().
const G4double G4ECDecay::PN2overPN1 static private
Initial value:
= {
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00,
0.0000e+00,   9.6988e-03,   1.0797e-02,   1.1706e-02,   1.2603e-02,   1.3408e-02,   1.4352e-02,
1.5511e-02,   1.6579e-02,   1.7646e-02,   1.8731e-02,   1.9886e-02,   2.1069e-02,   2.2359e-02,
2.3710e-02,   2.5058e-02,   2.6438e-02,   2.7843e-02,   2.9283e-02,   3.0762e-02,   3.2275e-02,
3.3843e-02,   3.5377e-02,   3.6886e-02,   3.8502e-02,   4.0159e-02,   4.1867e-02,   4.3617e-02,
4.5470e-02,   4.7247e-02,   4.9138e-02,   5.1065e-02,   5.3049e-02,   5.5085e-02,   5.7173e-02,
5.9366e-02,   6.1800e-02,   6.3945e-02,   6.6333e-02,   6.8785e-02,   7.1303e-02,   7.3801e-02,
7.6538e-02,   7.9276e-02,   8.2070e-02,   8.4959e-02,   8.7940e-02,   9.0990e-02,   9.4124e-02,
9.7337e-02,   1.0069e-01,   1.0410e-01,   1.0761e-01,   1.1122e-01,   1.1499e-01,   1.1882e-01,
1.2282e-01,   1.2709e-01,   1.3114e-01,   1.3549e-01,   1.4001e-01,   1.4465e-01,   1.4946e-01,
1.5443e-01,   1.5954e-01}
Definition at line 70 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ECDecay.hh
Referenced by DefineSubshellProbabilities().
const G4double G4ECDecay::transitionQ private
Definition at line 63 of file G4ECDecay.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ECDecay.hh
Referenced by DecayIt(), and DumpNuclearInfo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4ECDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4ECDecay.cc