ECCE @ EIC Software: CLHEP::RandGauss Class Reference
CLHEP::RandGauss Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGauss.h>
Public Member Functions
RandGauss (HepRandomEngine &anEngine, double mean=0.0, double stdDev=1.0)
RandGauss (HepRandomEngine *anEngine, double mean=0.0, double stdDev=1.0)
virtual ~RandGauss ()
double fire ()
double fire (double mean, double stdDev)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double mean, double stdDev)
virtual double operator() ()
virtual double operator() (double mean, double stdDev)
std::string name () const
HepRandomEngine & engine ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
bool getF () const
void setF (bool val)
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static double shoot ()
static double shoot (double mean, double stdDev)
static void shootArray (const int size, double *vect, double mean=0.0, double stdDev=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double mean, double stdDev)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double mean=0.0, double stdDev=1.0)
static std::string distributionName ()
static bool getFlag ()
static void setFlag (bool val)
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Protected Member Functions
double normal ()
Static Protected Member Functions
static double getVal ()
static void setVal (double nextVal)
Protected Attributes
double defaultMean
double defaultStdDev
std::shared_ptr< HepRandomEngine > localEngine
Private Attributes
bool set
double nextGauss
Static Private Attributes
static CLHEP_THREAD_LOCAL bool set_st = false
static CLHEP_THREAD_LOCAL double nextGauss_st = 0.0
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 41 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 41 of file RandGauss.h
Constructor & Destructor Documentation
CLHEP::RandGauss::RandGauss (HepRandomEngine & anEngine, double mean = 0.0, double stdDev = 1.0) inline
CLHEP::RandGauss::RandGauss (HepRandomEngine * anEngine, double mean = 0.0, double stdDev = 1.0) inline
CLHEP::RandGauss::~RandGauss () virtual
Definition at line 48 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 48 of file RandGauss.cc
Member Function Documentation
static std::string CLHEP::RandGauss::distributionName () inline static
Definition at line 99 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 99 of file RandGauss.h
Referenced by restoreDistState(), and saveDistState().
HepRandomEngine & CLHEP::RandGauss::engine () virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandGaussQ, and CLHEP::RandGaussZiggurat.
Definition at line 42 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 42 of file RandGauss.cc
References localEngine.
Referenced by CLHEP::RandGaussZiggurat::engine(), and CLHEP::RandGaussQ::engine().
double CLHEP::RandGauss::fire ()
Referenced by fireArray(), Par02Smearer::Gauss(), and operator()().
double CLHEP::RandGauss::fire (double mean, double stdDev) inline
void CLHEP::RandGauss::fireArray (const int size, double * vect)
Definition at line 155 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 155 of file RandGauss.cc
References defaultMean, defaultStdDev, fire(), and v.
void CLHEP::RandGauss::fireArray (const int size, double * vect, double mean, double stdDev)
Definition at line 161 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 161 of file RandGauss.cc
References fire(), and v.
std::istream & CLHEP::RandGauss::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandGaussQ, and CLHEP::RandGaussZiggurat.
Definition at line 274 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 274 of file RandGauss.cc
References c1, c2, defaultMean, defaultStdDev, CLHEP::DoubConv::longs2double(), name(), nextGauss, CLHEP::possibleKeywordInput(), and t.
Referenced by CLHEP::RandGaussZiggurat::get(), and CLHEP::RandGaussQ::get().
bool CLHEP::RandGauss::getF () const inline
Definition at line 115 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 115 of file RandGauss.h
bool CLHEP::RandGauss::getFlag () static
Definition at line 168 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 168 of file RandGauss.cc
References set_st.
Referenced by saveDistState(), saveEngineStatus(), and shoot().
double CLHEP::RandGauss::getVal () static protected
Definition at line 178 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 178 of file RandGauss.cc
References nextGauss_st.
Referenced by saveDistState(), saveEngineStatus(), and shoot().
std::string CLHEP::RandGauss::name () const virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandGaussQ, and CLHEP::RandGaussZiggurat.
Definition at line 41 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 41 of file RandGauss.cc
Referenced by get(), and put().
double CLHEP::RandGauss::normal () protected
Definition at line 129 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 129 of file RandGauss.cc
References fac, localEngine, nextGauss, r, v1, and v2.
double CLHEP::RandGauss::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandGaussQ, and CLHEP::RandGaussZiggurat.
Definition at line 51 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 51 of file RandGauss.cc
References defaultMean, defaultStdDev, and fire().
double CLHEP::RandGauss::operator() (double mean, double stdDev) virtual
Reimplemented in CLHEP::RandGaussQ, and CLHEP::RandGaussZiggurat.
Definition at line 55 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 55 of file RandGauss.cc
References fire().
std::ostream & CLHEP::RandGauss::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandGaussQ, and CLHEP::RandGaussZiggurat.
Definition at line 255 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 255 of file RandGauss.cc
References defaultMean, defaultStdDev, CLHEP::DoubConv::dto2longs(), name(), nextGauss, CLHEP::prec, and t.
Referenced by CLHEP::RandGaussZiggurat::put(), and CLHEP::RandGaussQ::put().
std::istream & CLHEP::RandGauss::restoreDistState (std::istream & is) static
Definition at line 343 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 343 of file RandGauss.cc
References c1, c2, distributionName(), CLHEP::DoubConv::longs2double(), nextGauss_st, CLHEP::possibleKeywordInput(), setFlag(), and t.
Referenced by CLHEP::StaticRandomStates::restore(), and restoreFullState().
void CLHEP::RandGauss::restoreEngineStatus (const char filename[] = "Config.conf") static
Definition at line 208 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 208 of file RandGauss.cc
References CLHEP::HepRandom::getTheEngine(), in, CLHEP::DoubConv::longs2double(), nextGauss_st, CLHEP::possibleKeywordInput(), CLHEP::HepRandomEngine::restoreStatus(), setFlag(), and t.
std::istream & CLHEP::RandGauss::restoreFullState (std::istream & is) static
Definition at line 393 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 393 of file RandGauss.cc
References restoreDistState(), and CLHEP::HepRandom::restoreFullState().
std::ostream & CLHEP::RandGauss::saveDistState (std::ostream & os) static
Definition at line 328 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 328 of file RandGauss.cc
References distributionName(), CLHEP::DoubConv::dto2longs(), getFlag(), getVal(), CLHEP::prec, and t.
Referenced by saveFullState().
void CLHEP::RandGauss::saveEngineStatus (const char filename[] = "Config.conf") static
Definition at line 188 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 188 of file RandGauss.cc
References demo::app, CLHEP::DoubConv::dto2longs(), getFlag(), CLHEP::HepRandom::getTheEngine(), getVal(), CLHEP::HepRandomEngine::saveStatus(), and t.
std::ostream & CLHEP::RandGauss::saveFullState (std::ostream & os) static
Definition at line 387 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 387 of file RandGauss.cc
References saveDistState(), and CLHEP::HepRandom::saveFullState().
Referenced by CLHEP::StaticRandomStates::save().
void CLHEP::RandGauss::setF (bool val) inline
Definition at line 117 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 117 of file RandGauss.h
void CLHEP::RandGauss::setFlag (bool val) static
Definition at line 173 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 173 of file RandGauss.cc
References set_st.
Referenced by restoreDistState(), restoreEngineStatus(), and shoot().
void CLHEP::RandGauss::setVal (double nextVal) static protected
Definition at line 183 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 183 of file RandGauss.cc
References nextGauss_st.
Referenced by shoot().
double CLHEP::RandGauss::shoot () static
Definition at line 59 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 59 of file RandGauss.cc
References fac, CLHEP::HepRandomEngine::flat(), getFlag(), CLHEP::HepRandom::getTheEngine(), getVal(), r, setFlag(), setVal(), v1, v2, and x.
Referenced by shootArray().
static double CLHEP::RandGauss::shoot (double mean, double stdDev) inline static
double CLHEP::RandGauss::shoot (HepRandomEngine * anEngine) static
Definition at line 95 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 95 of file RandGauss.cc
References fac, CLHEP::HepRandomEngine::flat(), getFlag(), getVal(), r, setFlag(), setVal(), v1, and v2.
static double CLHEP::RandGauss::shoot (HepRandomEngine * anEngine, double mean, double stdDev) inline static
void CLHEP::RandGauss::shootArray (const int size, double * vect, double mean = 0.0, double stdDev = 1.0) static
Definition at line 88 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 88 of file RandGauss.cc
References shoot(), and v.
void CLHEP::RandGauss::shootArray (HepRandomEngine * anEngine, const int size, double * vect, double mean = 0.0, double stdDev = 1.0) static
Definition at line 121 of file RandGauss.cc.
View newest version in sPHENIX GitHub at line 121 of file RandGauss.cc
References shoot(), and v.
Member Data Documentation
double CLHEP::RandGauss::defaultMean protected
Definition at line 151 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 151 of file RandGauss.h
Referenced by CLHEP::RandGaussZiggurat::fire(), CLHEP::RandGaussZiggurat::fireArray(), CLHEP::RandGaussQ::fireArray(), fireArray(), get(), CLHEP::RandGaussZiggurat::operator()(), CLHEP::RandGaussQ::operator()(), operator()(), and put().
double CLHEP::RandGauss::defaultStdDev protected
Definition at line 152 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 152 of file RandGauss.h
Referenced by CLHEP::RandGaussZiggurat::fire(), CLHEP::RandGaussZiggurat::fireArray(), CLHEP::RandGaussQ::fireArray(), fireArray(), get(), CLHEP::RandGaussZiggurat::operator()(), CLHEP::RandGaussQ::operator()(), operator()(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandGauss::localEngine protected
Definition at line 154 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 154 of file RandGauss.h
Referenced by engine(), CLHEP::RandGaussZiggurat::fire(), normal(), CLHEP::RandGaussZiggurat::operator()(), and CLHEP::RandGaussQ::operator()().
double CLHEP::RandGauss::nextGauss private
Definition at line 159 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 159 of file RandGauss.h
Referenced by get(), normal(), and put().
CLHEP_THREAD_LOCAL double CLHEP::RandGauss::nextGauss_st = 0.0 static private
Definition at line 163 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 163 of file RandGauss.h
Referenced by getVal(), restoreDistState(), restoreEngineStatus(), and setVal().
bool CLHEP::RandGauss::set private
Definition at line 158 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 158 of file RandGauss.h
CLHEP_THREAD_LOCAL bool CLHEP::RandGauss::set_st = false static private
Definition at line 162 of file RandGauss.h.
View newest version in sPHENIX GitHub at line 162 of file RandGauss.h
Referenced by getFlag(), and setFlag().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGauss.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandGauss.cc