ECCE @ EIC Software: G4VComponentCrossSection Class Reference
G4VComponentCrossSection Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4VComponentCrossSection.hh>
Public Member Functions
G4VComponentCrossSection (const G4String &nam="")
virtual ~G4VComponentCrossSection ()
G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
virtual G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4double)=0
virtual G4double GetTotalIsotopeCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)=0
G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
virtual G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4double)=0
virtual G4double GetInelasticIsotopeCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)=0
G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
virtual G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4double)=0
virtual G4double GetElasticIsotopeCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)=0
virtual G4double ComputeQuasiElasticRatio (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void Description (std::ostream &) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
const G4String & GetName () const
Private Member Functions
G4VComponentCrossSection & operator= (const G4VComponentCrossSection &right)
G4VComponentCrossSection (const G4VComponentCrossSection &)
Private Attributes
G4CrossSectionDataSetRegistry * registry
G4int verboseLevel
G4double minKinEnergy
G4double maxKinEnergy
const G4String name
Detailed Description
Definition at line 53 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VComponentCrossSection.hh
Constructor & Destructor Documentation
G4VComponentCrossSection::G4VComponentCrossSection (const G4String & nam = "") explicit
Definition at line 43 of file G4VComponentCrossSection.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VComponentCrossSection.cc
References G4CrossSectionDataSetRegistry::Instance(), G4CrossSectionDataSetRegistry::Register(), and registry.
G4VComponentCrossSection::~G4VComponentCrossSection () virtual
Definition at line 50 of file G4VComponentCrossSection.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VComponentCrossSection.cc
References G4CrossSectionDataSetRegistry::DeRegister(), and registry.
G4VComponentCrossSection::G4VComponentCrossSection (const G4VComponentCrossSection &) private
Member Function Documentation
void G4VComponentCrossSection::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented in G4ChipsComponentXS, G4ComponentGGNuclNuclXsc, G4ComponentBarNucleonNucleusXsc, and G4ComponentAntiNuclNuclearXS.
Definition at line 67 of file G4VComponentCrossSection.cc.
View newest version in sPHENIX GitHub at line 67 of file G4VComponentCrossSection.cc
Referenced by G4CrossSectionPairGG::BuildPhysicsTable(), G4CrossSectionElastic::BuildPhysicsTable(), and G4CrossSectionInelastic::BuildPhysicsTable().
G4double G4VComponentCrossSection::ComputeQuasiElasticRatio (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4int) virtual
Reimplemented in G4ComponentGGHadronNucleusXsc, and G4ComponentGGNuclNuclXsc.
Definition at line 56 of file G4VComponentCrossSection.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VComponentCrossSection.cc
void G4VComponentCrossSection::Description (std::ostream &) const virtual
Reimplemented in G4ComponentGGHadronNucleusXsc, G4ComponentSAIDTotalXS, G4ComponentGGNuclNuclXsc, and G4ComponentBarNucleonNucleusXsc.
Definition at line 63 of file G4VComponentCrossSection.cc.
View newest version in sPHENIX GitHub at line 63 of file G4VComponentCrossSection.cc
Referenced by G4CrossSectionElastic::CrossSectionDescription(), and G4CrossSectionInelastic::CrossSectionDescription().
void G4VComponentCrossSection::DumpPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented in G4ChipsComponentXS, G4ComponentGGNuclNuclXsc, and G4ComponentAntiNuclNuclearXS.
Definition at line 71 of file G4VComponentCrossSection.cc.
View newest version in sPHENIX GitHub at line 71 of file G4VComponentCrossSection.cc
Referenced by G4CrossSectionElastic::DumpPhysicsTable(), and G4CrossSectionInelastic::DumpPhysicsTable().
G4double G4VComponentCrossSection::GetElasticElementCrossSection (const G4ParticleDefinition * p, G4double kinEnergy, const G4Element * elm) inline
Definition at line 169 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 169 of file G4VComponentCrossSection.hh
References G4Element::GetN(), and G4Element::GetZasInt().
Referenced by G4CrossSectionElastic::GetElementCrossSection().
virtual G4double G4VComponentCrossSection::GetElasticElementCrossSection (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4double) pure virtual
Implemented in G4ComponentSAIDTotalXS, G4ChipsComponentXS, G4ComponentGGHadronNucleusXsc, G4ComponentGGNuclNuclXsc, G4ComponentBarNucleonNucleusXsc, and G4ComponentAntiNuclNuclearXS.
virtual G4double G4VComponentCrossSection::GetElasticIsotopeCrossSection (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4int) pure virtual
Implemented in G4ComponentSAIDTotalXS, G4ChipsComponentXS, G4ComponentGGHadronNucleusXsc, G4ComponentGGNuclNuclXsc, G4ComponentBarNucleonNucleusXsc, and G4ComponentAntiNuclNuclearXS.
Referenced by G4FTFParameters::InitForInteraction().
G4double G4VComponentCrossSection::GetInelasticElementCrossSection (const G4ParticleDefinition * p, G4double kinEnergy, const G4Element * elm) inline
Definition at line 159 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 159 of file G4VComponentCrossSection.hh
References G4Element::GetN(), and G4Element::GetZasInt().
Referenced by G4CrossSectionInelastic::GetElementCrossSection().
virtual G4double G4VComponentCrossSection::GetInelasticElementCrossSection (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4double) pure virtual
Implemented in G4ChipsComponentXS, G4ComponentSAIDTotalXS, G4ComponentAntiNuclNuclearXS, G4ComponentBarNucleonNucleusXsc, G4ComponentGGHadronNucleusXsc, and G4ComponentGGNuclNuclXsc.
virtual G4double G4VComponentCrossSection::GetInelasticIsotopeCrossSection (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4int) pure virtual
Implemented in G4ComponentSAIDTotalXS, G4ChipsComponentXS, G4ComponentGGHadronNucleusXsc, G4ComponentGGNuclNuclXsc, G4ComponentAntiNuclNuclearXS, and G4ComponentBarNucleonNucleusXsc.
G4double G4VComponentCrossSection::GetMaxKinEnergy () const inline
Definition at line 203 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 203 of file G4VComponentCrossSection.hh
References maxKinEnergy.
G4double G4VComponentCrossSection::GetMinKinEnergy () const inline
Definition at line 193 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 193 of file G4VComponentCrossSection.hh
References minKinEnergy.
const G4String & G4VComponentCrossSection::GetName (void) const inline
Definition at line 208 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 208 of file G4VComponentCrossSection.hh
References name.
Referenced by G4CrossSectionPairGG::BuildPhysicsTable().
G4double G4VComponentCrossSection::GetTotalElementCrossSection (const G4ParticleDefinition * p, G4double kinEnergy, const G4Element * elm) inline
Definition at line 149 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 149 of file G4VComponentCrossSection.hh
References G4Element::GetN(), and G4Element::GetZasInt().
virtual G4double G4VComponentCrossSection::GetTotalElementCrossSection (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4double) pure virtual
Implemented in G4ChipsComponentXS, G4ComponentSAIDTotalXS, G4ComponentAntiNuclNuclearXS, G4ComponentBarNucleonNucleusXsc, G4ComponentGGHadronNucleusXsc, and G4ComponentGGNuclNuclXsc.
virtual G4double G4VComponentCrossSection::GetTotalIsotopeCrossSection (const G4ParticleDefinition * , G4double kinEnergy, G4int , G4int) pure virtual
Implemented in G4ChipsComponentXS, G4ComponentSAIDTotalXS, G4ComponentGGHadronNucleusXsc, G4ComponentGGNuclNuclXsc, G4ComponentAntiNuclNuclearXS, and G4ComponentBarNucleonNucleusXsc.
Referenced by G4FTFParameters::InitForInteraction().
G4int G4VComponentCrossSection::GetVerboseLevel () const inline
Definition at line 183 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 183 of file G4VComponentCrossSection.hh
References verboseLevel.
Referenced by G4ComponentSAIDTotalXS::ReadData().
G4VComponentCrossSection& G4VComponentCrossSection::operator= (const G4VComponentCrossSection & right) private
void G4VComponentCrossSection::SetMaxKinEnergy (G4double value) inline
Definition at line 198 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 198 of file G4VComponentCrossSection.hh
References maxKinEnergy.
void G4VComponentCrossSection::SetMinKinEnergy (G4double value) inline
Definition at line 188 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 188 of file G4VComponentCrossSection.hh
References minKinEnergy.
void G4VComponentCrossSection::SetVerboseLevel (G4int value) inline
Definition at line 178 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 178 of file G4VComponentCrossSection.hh
References verboseLevel.
Member Data Documentation
G4double G4VComponentCrossSection::maxKinEnergy private
Definition at line 143 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 143 of file G4VComponentCrossSection.hh
Referenced by GetMaxKinEnergy(), and SetMaxKinEnergy().
G4double G4VComponentCrossSection::minKinEnergy private
Definition at line 142 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 142 of file G4VComponentCrossSection.hh
Referenced by GetMinKinEnergy(), and SetMinKinEnergy().
const G4String G4VComponentCrossSection::name private
Definition at line 145 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 145 of file G4VComponentCrossSection.hh
Referenced by GetName().
G4CrossSectionDataSetRegistry* G4VComponentCrossSection::registry private
Definition at line 138 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 138 of file G4VComponentCrossSection.hh
Referenced by G4VComponentCrossSection(), and ~G4VComponentCrossSection().
G4int G4VComponentCrossSection::verboseLevel private
Definition at line 140 of file G4VComponentCrossSection.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VComponentCrossSection.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4VComponentCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4VComponentCrossSection.cc