ECCE @ EIC Software: G4ParticleHPFissionSpectrum Class Reference
G4ParticleHPFissionSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionSpectrum.hh>
Public Member Functions
G4ParticleHPFissionSpectrum ()
~G4ParticleHPFissionSpectrum ()
void Init (std::istream &aDataFile)
G4double GetFractionalProbability (G4double anEnergy)
G4double Sample (G4double anEnergy)
Public Member Functions inherited from G4VParticleHPEDis
G4VParticleHPEDis ()
virtual ~G4VParticleHPEDis ()
Private Member Functions
G4double Maxwell (G4double anEnergy, G4double theta)
Private Attributes
G4double expm1
G4ParticleHPVector theFractionalProb
G4ParticleHPVector theThetaDist
Detailed Description
Definition at line 44 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPFissionSpectrum.hh
Constructor & Destructor Documentation
G4ParticleHPFissionSpectrum::G4ParticleHPFissionSpectrum () inline
Definition at line 47 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPFissionSpectrum.hh
References expm1, and G4Exp().
G4ParticleHPFissionSpectrum::~G4ParticleHPFissionSpectrum () inline
Definition at line 51 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPFissionSpectrum.hh
Member Function Documentation
G4double G4ParticleHPFissionSpectrum::GetFractionalProbability (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 61 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPFissionSpectrum.hh
References G4ParticleHPVector::GetY(), and theFractionalProb.
void G4ParticleHPFissionSpectrum::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEDis.
Definition at line 55 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPFissionSpectrum.hh
References CLHEP::eV, G4ParticleHPVector::Init(), theFractionalProb, and theThetaDist.
G4double G4ParticleHPFissionSpectrum::Maxwell (G4double anEnergy, G4double theta) inline private
Definition at line 95 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPFissionSpectrum.hh
References CLHEP::eV, and G4Exp().
Referenced by Sample().
G4double G4ParticleHPFissionSpectrum::Sample (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 66 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPFissionSpectrum.hh
References CLHEP::eV, G4cout, G4endl, G4UniformRand, G4ParticleHPVector::GetY(), max, Maxwell(), CLHEP::MeV, theta(), and theThetaDist.
Member Data Documentation
G4double G4ParticleHPFissionSpectrum::expm1 private
Definition at line 103 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPFissionSpectrum.hh
Referenced by G4ParticleHPFissionSpectrum().
G4ParticleHPVector G4ParticleHPFissionSpectrum::theFractionalProb private
Definition at line 105 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPFissionSpectrum.hh
Referenced by GetFractionalProbability(), and Init().
G4ParticleHPVector G4ParticleHPFissionSpectrum::theThetaDist private
Definition at line 107 of file G4ParticleHPFissionSpectrum.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPFissionSpectrum.hh
Referenced by Init(), and Sample().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionSpectrum.hh