ECCE @ EIC Software: G4NeutrinoElectronTotXsc Class Reference
G4NeutrinoElectronTotXsc Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutrinoElectronTotXsc.hh>
Public Member Functions
G4NeutrinoElectronTotXsc ()
~G4NeutrinoElectronTotXsc ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
void SetBiasingFactor (G4double bf)
void SetBiasingFactors (G4double bfCc, G4double bfNc)
G4double GetBiasingFactor ()
G4double GetCcRatio ()
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Protected Attributes
G4NeutrinoElectronCcXsc * fCcXsc
G4NeutrinoElectronNcXsc * fNcXsc
G4double fCutEnergy
G4double fBiasingFactor
G4double fCcRatio
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Detailed Description
Definition at line 42 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 42 of file G4NeutrinoElectronTotXsc.hh
Constructor & Destructor Documentation
G4NeutrinoElectronTotXsc::G4NeutrinoElectronTotXsc ()
Definition at line 41 of file G4NeutrinoElectronTotXsc.cc.
View newest version in sPHENIX GitHub at line 41 of file G4NeutrinoElectronTotXsc.cc
References fBiasingFactor, fCcRatio, fCcXsc, fCutEnergy, and fNcXsc.
G4NeutrinoElectronTotXsc::~G4NeutrinoElectronTotXsc ()
Definition at line 52 of file G4NeutrinoElectronTotXsc.cc.
View newest version in sPHENIX GitHub at line 52 of file G4NeutrinoElectronTotXsc.cc
Member Function Documentation
G4double G4NeutrinoElectronTotXsc::GetBiasingFactor () inline
Definition at line 62 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 62 of file G4NeutrinoElectronTotXsc.hh
References fBiasingFactor.
G4double G4NeutrinoElectronTotXsc::GetCcRatio () inline
Definition at line 63 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 63 of file G4NeutrinoElectronTotXsc.hh
References fCcRatio.
Referenced by G4NeutrinoElectronProcess::PostStepDoIt().
G4double G4NeutrinoElectronTotXsc::GetCutEnergy () inline
Definition at line 58 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 58 of file G4NeutrinoElectronTotXsc.hh
References fCutEnergy.
G4double G4NeutrinoElectronTotXsc::GetElementCrossSection (const G4DynamicParticle * aPart, G4int Z, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 73 of file G4NeutrinoElectronTotXsc.cc.
View newest version in sPHENIX GitHub at line 73 of file G4NeutrinoElectronTotXsc.cc
References fCcRatio, fCcXsc, fNcXsc, G4NeutrinoElectronNcXsc::GetElementCrossSection(), and G4NeutrinoElectronCcXsc::GetElementCrossSection().
Referenced by G4NeutrinoElectronProcess::PostStepDoIt().
G4bool G4NeutrinoElectronTotXsc::IsElementApplicable (const G4DynamicParticle * aPart, G4int Z, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 58 of file G4NeutrinoElectronTotXsc.cc.
View newest version in sPHENIX GitHub at line 58 of file G4NeutrinoElectronTotXsc.cc
References fCcXsc, fNcXsc, G4NeutrinoElectronNcXsc::IsElementApplicable(), and G4NeutrinoElectronCcXsc::IsElementApplicable().
void G4NeutrinoElectronTotXsc::SetBiasingFactor (G4double bf)
Definition at line 91 of file G4NeutrinoElectronTotXsc.cc.
View newest version in sPHENIX GitHub at line 91 of file G4NeutrinoElectronTotXsc.cc
References fBiasingFactor, fCcXsc, fNcXsc, G4NeutrinoElectronNcXsc::SetBiasingFactor(), and G4NeutrinoElectronCcXsc::SetBiasingFactor().
void G4NeutrinoElectronTotXsc::SetBiasingFactors (G4double bfCc, G4double bfNc)
Definition at line 102 of file G4NeutrinoElectronTotXsc.cc.
View newest version in sPHENIX GitHub at line 102 of file G4NeutrinoElectronTotXsc.cc
References fCcXsc, fNcXsc, G4NeutrinoElectronNcXsc::SetBiasingFactor(), and G4NeutrinoElectronCcXsc::SetBiasingFactor().
Referenced by G4EmExtraPhysics::ConstructProcess(), and G4NeutrinoElectronProcess::SetBiasingFactors().
void G4NeutrinoElectronTotXsc::SetCutEnergy (G4double ec) inline
Definition at line 57 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 57 of file G4NeutrinoElectronTotXsc.hh
References fCutEnergy.
Member Data Documentation
G4double G4NeutrinoElectronTotXsc::fBiasingFactor protected
Definition at line 70 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 70 of file G4NeutrinoElectronTotXsc.hh
Referenced by G4NeutrinoElectronTotXsc(), GetBiasingFactor(), and SetBiasingFactor().
G4double G4NeutrinoElectronTotXsc::fCcRatio protected
Definition at line 71 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NeutrinoElectronTotXsc.hh
Referenced by G4NeutrinoElectronTotXsc(), GetCcRatio(), and GetElementCrossSection().
G4NeutrinoElectronCcXsc* G4NeutrinoElectronTotXsc::fCcXsc protected
Definition at line 63 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 63 of file G4NeutrinoElectronTotXsc.hh
Referenced by G4NeutrinoElectronTotXsc(), GetElementCrossSection(), IsElementApplicable(), SetBiasingFactor(), and SetBiasingFactors().
G4double G4NeutrinoElectronTotXsc::fCutEnergy protected
Definition at line 69 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NeutrinoElectronTotXsc.hh
Referenced by G4NeutrinoElectronTotXsc(), GetCutEnergy(), and SetCutEnergy().
G4NeutrinoElectronNcXsc* G4NeutrinoElectronTotXsc::fNcXsc protected
Definition at line 68 of file G4NeutrinoElectronTotXsc.hh.
View newest version in sPHENIX GitHub at line 68 of file G4NeutrinoElectronTotXsc.hh
Referenced by G4NeutrinoElectronTotXsc(), GetElementCrossSection(), IsElementApplicable(), SetBiasingFactor(), and SetBiasingFactors().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutrinoElectronTotXsc.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4NeutrinoElectronTotXsc.cc