ECCE @ EIC Software: G4AdjointStackingAction Class Reference
G4AdjointStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4AdjointStackingAction.hh>
Public Member Functions
G4AdjointStackingAction (G4AdjointTrackingAction *anAction)
virtual ~G4AdjointStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
void SetUserFwdStackingAction (G4UserStackingAction *anAction)
void SetUserAdjointStackingAction (G4UserStackingAction *anAction)
void SetKillTracks (G4bool aBool)
void SetAdjointMode (G4bool aBool)
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Attributes
G4UserStackingAction * theFwdStackingAction
G4UserStackingAction * theUserAdjointStackingAction
G4bool reclassification_stage
G4bool first_reclassification_stage
G4bool kill_tracks
G4bool adjoint_mode
G4AdjointTrackingAction * theAdjointTrackingAction
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 65 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file G4AdjointStackingAction.hh
Constructor & Destructor Documentation
G4AdjointStackingAction::G4AdjointStackingAction (G4AdjointTrackingAction * anAction)
Definition at line 43 of file G4AdjointStackingAction.cc.
View newest version in sPHENIX GitHub at line 43 of file G4AdjointStackingAction.cc
References theAdjointTrackingAction, theFwdStackingAction, and theUserAdjointStackingAction.
G4AdjointStackingAction::~G4AdjointStackingAction () virtual
Definition at line 52 of file G4AdjointStackingAction.cc.
View newest version in sPHENIX GitHub at line 52 of file G4AdjointStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack G4AdjointStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 56 of file G4AdjointStackingAction.cc.
View newest version in sPHENIX GitHub at line 56 of file G4AdjointStackingAction.cc
References adjoint_mode, G4UserStackingAction::ClassifyNewTrack(), G4String::contains(), fKill, fUrgent, fWaiting, G4AdjointTrackingAction::GetNbOfAdointTracksReachingTheExternalSurface(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleType(), reclassification_stage, theAdjointTrackingAction, theFwdStackingAction, and theUserAdjointStackingAction.
void G4AdjointStackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 75 of file G4AdjointStackingAction.cc.
View newest version in sPHENIX GitHub at line 75 of file G4AdjointStackingAction.cc
References first_reclassification_stage, G4UserStackingAction::NewStage(), reclassification_stage, G4StackManager::ReClassify(), G4UserStackingAction::stackManager, theFwdStackingAction, and theUserAdjointStackingAction.
void G4AdjointStackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 86 of file G4AdjointStackingAction.cc.
View newest version in sPHENIX GitHub at line 86 of file G4AdjointStackingAction.cc
References first_reclassification_stage, G4UserStackingAction::PrepareNewEvent(), reclassification_stage, and theUserAdjointStackingAction.
void G4AdjointStackingAction::SetAdjointMode (G4bool aBool) inline
Definition at line 78 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AdjointStackingAction.hh
References adjoint_mode.
Referenced by G4AdjointSimManager::SetAdjointTrackingMode().
void G4AdjointStackingAction::SetKillTracks (G4bool aBool) inline
Definition at line 77 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointStackingAction.hh
References kill_tracks.
Referenced by G4AdjointSimManager::SetAdjointTrackingMode().
void G4AdjointStackingAction::SetUserAdjointStackingAction (G4UserStackingAction * anAction) inline
Definition at line 76 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AdjointStackingAction.hh
References theUserAdjointStackingAction.
Referenced by G4AdjointSimManager::SetAdjointStackingAction().
void G4AdjointStackingAction::SetUserFwdStackingAction (G4UserStackingAction * anAction) inline
Definition at line 75 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4AdjointStackingAction.hh
References theFwdStackingAction.
Referenced by G4AdjointSimManager::SetAdjointActions(), and G4AdjointSimManager::SetAdjointPrimaryRunAndStackingActions().
Member Data Documentation
G4bool G4AdjointStackingAction::adjoint_mode private
Definition at line 85 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointStackingAction.hh
Referenced by ClassifyNewTrack(), and SetAdjointMode().
G4bool G4AdjointStackingAction::first_reclassification_stage private
Definition at line 85 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointStackingAction.hh
Referenced by NewStage(), and PrepareNewEvent().
G4bool G4AdjointStackingAction::kill_tracks private
Definition at line 85 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointStackingAction.hh
Referenced by SetKillTracks().
G4bool G4AdjointStackingAction::reclassification_stage private
Definition at line 85 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointStackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
G4AdjointTrackingAction* G4AdjointStackingAction::theAdjointTrackingAction private
Definition at line 86 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 86 of file G4AdjointStackingAction.hh
Referenced by ClassifyNewTrack(), and G4AdjointStackingAction().
G4UserStackingAction* G4AdjointStackingAction::theFwdStackingAction private
Definition at line 83 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4AdjointStackingAction.hh
Referenced by ClassifyNewTrack(), G4AdjointStackingAction(), NewStage(), and SetUserFwdStackingAction().
G4UserStackingAction* G4AdjointStackingAction::theUserAdjointStackingAction private
Definition at line 84 of file G4AdjointStackingAction.hh.
View newest version in sPHENIX GitHub at line 84 of file G4AdjointStackingAction.hh
Referenced by ClassifyNewTrack(), G4AdjointStackingAction(), NewStage(), PrepareNewEvent(), and SetUserAdjointStackingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4AdjointStackingAction.hh
geant4/tree/geant4-10.6-release/source/event/src/G4AdjointStackingAction.cc