ECCE @ EIC Software: G4ImportanceProcess Class Reference
G4ImportanceProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4ImportanceProcess.hh>
Public Member Functions
G4ImportanceProcess (const G4VImportanceAlgorithm &aImportanceAlgorithm, const G4VIStore &aIstore, const G4VTrackTerminator *TrackTerminator, const G4String &aName="ImportanceProcess", G4bool para=false)
virtual ~G4ImportanceProcess ()
void SetParallelWorld (const G4String &parallelWorldName)
void StartTracking (G4Track *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual void KillTrack () const
virtual const G4String & GetName () const
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Public Member Functions inherited from G4VTrackTerminator
G4VTrackTerminator ()
virtual ~G4VTrackTerminator ()
Private Member Functions
G4ImportanceProcess (const G4ImportanceProcess &)
G4ImportanceProcess & operator= (const G4ImportanceProcess &)
void CopyStep (const G4Step &step)
Private Attributes
G4Step * fGhostStep
G4StepPoint * fGhostPreStepPoint
G4StepPoint * fGhostPostStepPoint
G4ParticleChange * fParticleChange
const G4VImportanceAlgorithm & fImportanceAlgorithm
const G4VIStore & fIStore
G4SamplingPostStepAction * fPostStepAction
G4TransportationManager * fTransportationManager
G4PathFinder * fPathFinder
G4String fGhostWorldName
G4VPhysicalVolume * fGhostWorld
G4Navigator * fGhostNavigator
G4int fNavigatorID
G4TouchableHandle fOldGhostTouchable
G4TouchableHandle fNewGhostTouchable
G4FieldTrack fFieldTrack
G4double fGhostSafety
G4bool fOnBoundary
G4bool fParaflag
G4FieldTrack fEndTrack
ELimited feLimited
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Protected Attributes inherited from G4VTrackTerminator
G4double kCarTolerance
Detailed Description
Definition at line 60 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ImportanceProcess.hh
Constructor & Destructor Documentation
G4ImportanceProcess::G4ImportanceProcess (const G4VImportanceAlgorithm & aImportanceAlgorithm, const G4VIStore & aIstore, const G4VTrackTerminator * TrackTerminator, const G4String & aName = "ImportanceProcess", G4bool para = false)
Definition at line 54 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ImportanceProcess.cc
References FatalException, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fParaflag, fParticleChange, fPathFinder, fPostStepAction, fTransportationManager, G4cout, G4endl, G4Exception(), G4PathFinder::GetInstance(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VProcess::GetProcessName(), G4TransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, and G4VProcess::verboseLevel.
G4ImportanceProcess::~G4ImportanceProcess () virtual
Definition at line 102 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ImportanceProcess.cc
References fParticleChange, and fPostStepAction.
G4ImportanceProcess::G4ImportanceProcess (const G4ImportanceProcess &) private
Member Function Documentation
G4VParticleChange * G4ImportanceProcess::AlongStepDoIt (const G4Track & aTrack, const G4Step &) virtual
Implements G4VProcess.
Definition at line 445 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 445 of file G4ImportanceProcess.cc
References G4VParticleChange::Initialize(), and G4VProcess::pParticleChange.
G4double G4ImportanceProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 356 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 356 of file G4ImportanceProcess.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PathFinder::ComputeStep(), DBL_MAX, feLimited, fEndTrack, fFieldTrack, fGhostNavigator, fGhostSafety, fNavigatorID, fOnBoundary, fParaflag, fPathFinder, G4Track::GetCurrentStepNumber(), G4Track::GetVolume(), kDoNot, kSharedOther, kSharedTransport, kUnique, NotCandidateForSelection, and G4FieldTrackUpdator::Update().
G4VParticleChange * G4ImportanceProcess::AtRestDoIt (const G4Track & , const G4Step &) virtual
Implements G4VProcess.
Definition at line 439 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 439 of file G4ImportanceProcess.cc
G4double G4ImportanceProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) virtual
Implements G4VProcess.
Definition at line 432 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 432 of file G4ImportanceProcess.cc
void G4ImportanceProcess::CopyStep (const G4Step & step) private
Definition at line 455 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 455 of file G4ImportanceProcess.cc
References fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fGhostStep, fOnBoundary, fPostStepDoItProc, G4Step::GetControlFlag(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4Step::SetControlFlag(), G4Step::SetStepLength(), G4StepPoint::SetStepStatus(), G4Step::SetTotalEnergyDeposit(), and G4Step::SetTrack().
Referenced by PostStepDoIt().
const G4String & G4ImportanceProcess::GetName (void) const virtual
Implements G4VTrackTerminator.
Definition at line 350 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 350 of file G4ImportanceProcess.cc
References G4VProcess::theProcessName.
void G4ImportanceProcess::KillTrack () const virtual
Implements G4VTrackTerminator.
Definition at line 345 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 345 of file G4ImportanceProcess.cc
References fParticleChange, fStopAndKill, and G4VParticleChange::ProposeTrackStatus().
G4ImportanceProcess& G4ImportanceProcess::operator= (const G4ImportanceProcess &) private
G4VParticleChange * G4ImportanceProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Implements G4VProcess.
Definition at line 210 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 210 of file G4ImportanceProcess.cc
References CopyStep(), G4PathFinder::CreateTouchableHandle(), G4SamplingPostStepAction::DoIt(), fGeomBoundary, fGhostPostStepPoint, fGhostPreStepPoint, fImportanceAlgorithm, fIStore, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fParaflag, fParticleChange, fPathFinder, fPostStepAction, fStopAndKill, G4cout, G4endl, G4VIStore::GetImportance(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4VTouchable::GetReplicaNumber(), G4Step::GetStepLength(), G4StepPoint::GetStepStatus(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4Track::GetTrackStatus(), G4Track::GetWeight(), G4ParticleChange::Initialize(), G4VTrackTerminator::kCarTolerance, and G4StepPoint::SetTouchableHandle().
G4double G4ImportanceProcess::PostStepGetPhysicalInteractionLength (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 197 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 197 of file G4ImportanceProcess.cc
References DBL_MAX, and Forced.
void G4ImportanceProcess::SetParallelWorld (const G4String & parallelWorldName)
Definition at line 121 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ImportanceProcess.cc
References fGhostNavigator, fGhostWorld, fGhostWorldName, fTransportationManager, G4cout, G4endl, G4TransportationManager::GetNavigator(), and G4TransportationManager::GetParallelWorld().
Referenced by G4ImportanceConfigurator::Configure().
void G4ImportanceProcess::StartTracking (G4Track * trk) virtual
Reimplemented from G4VProcess.
Definition at line 155 of file G4ImportanceProcess.cc.
View newest version in sPHENIX GitHub at line 155 of file G4ImportanceProcess.cc
References G4TransportationManager::ActivateNavigator(), G4PathFinder::CreateTouchableHandle(), FatalException, fGhostNavigator, fGhostPostStepPoint, fGhostPreStepPoint, fGhostSafety, fNavigatorID, fNewGhostTouchable, fOldGhostTouchable, fOnBoundary, fParaflag, fPathFinder, fTransportationManager, G4Exception(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4PathFinder::PrepareNewTrack(), and G4StepPoint::SetTouchableHandle().
Member Data Documentation
ELimited G4ImportanceProcess::feLimited private
Definition at line 160 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4FieldTrack G4ImportanceProcess::fEndTrack private
Definition at line 159 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4FieldTrack G4ImportanceProcess::fFieldTrack private
Definition at line 154 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4Navigator* G4ImportanceProcess::fGhostNavigator private
Definition at line 150 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), SetParallelWorld(), and StartTracking().
G4StepPoint* G4ImportanceProcess::fGhostPostStepPoint private
Definition at line 135 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ImportanceProcess.hh
Referenced by CopyStep(), G4ImportanceProcess(), PostStepDoIt(), and StartTracking().
G4StepPoint* G4ImportanceProcess::fGhostPreStepPoint private
Definition at line 134 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ImportanceProcess.hh
Referenced by CopyStep(), G4ImportanceProcess(), PostStepDoIt(), and StartTracking().
G4double G4ImportanceProcess::fGhostSafety private
Definition at line 155 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4Step* G4ImportanceProcess::fGhostStep private
Definition at line 133 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ImportanceProcess.hh
Referenced by CopyStep(), and G4ImportanceProcess().
G4VPhysicalVolume* G4ImportanceProcess::fGhostWorld private
Definition at line 149 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ImportanceProcess.hh
Referenced by SetParallelWorld().
G4String G4ImportanceProcess::fGhostWorldName private
Definition at line 148 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ImportanceProcess.hh
Referenced by SetParallelWorld().
const G4VImportanceAlgorithm& G4ImportanceProcess::fImportanceAlgorithm private
Definition at line 138 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ImportanceProcess.hh
Referenced by PostStepDoIt().
const G4VIStore& G4ImportanceProcess::fIStore private
Definition at line 139 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ImportanceProcess.hh
Referenced by PostStepDoIt().
G4int G4ImportanceProcess::fNavigatorID private
Definition at line 151 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepDoIt(), and StartTracking().
G4TouchableHandle G4ImportanceProcess::fNewGhostTouchable private
Definition at line 153 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ImportanceProcess.hh
Referenced by PostStepDoIt(), and StartTracking().
G4TouchableHandle G4ImportanceProcess::fOldGhostTouchable private
Definition at line 152 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ImportanceProcess.hh
Referenced by PostStepDoIt(), and StartTracking().
G4bool G4ImportanceProcess::fOnBoundary private
Definition at line 156 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), CopyStep(), PostStepDoIt(), and StartTracking().
G4bool G4ImportanceProcess::fParaflag private
Definition at line 158 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess(), PostStepDoIt(), and StartTracking().
G4ParticleChange* G4ImportanceProcess::fParticleChange private
Definition at line 137 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ImportanceProcess.hh
Referenced by G4ImportanceProcess(), KillTrack(), PostStepDoIt(), and ~G4ImportanceProcess().
G4PathFinder* G4ImportanceProcess::fPathFinder private
Definition at line 143 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 143 of file G4ImportanceProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess(), PostStepDoIt(), and StartTracking().
G4SamplingPostStepAction* G4ImportanceProcess::fPostStepAction private
Definition at line 140 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ImportanceProcess.hh
Referenced by G4ImportanceProcess(), PostStepDoIt(), and ~G4ImportanceProcess().
G4TransportationManager* G4ImportanceProcess::fTransportationManager private
Definition at line 142 of file G4ImportanceProcess.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ImportanceProcess.hh
Referenced by G4ImportanceProcess(), SetParallelWorld(), and StartTracking().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4ImportanceProcess.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4ImportanceProcess.cc