ECCE @ EIC Software: macros/blob/master/common/G4_EToF.C File Reference
G4_EToF.C File Reference
#include <GlobalVariables.C>
#include <fun4all/Fun4AllServer.h>
#include <g4etof/PHG4ECAPToFSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
Namespaces
namespace Enable
namespace ETOF
Macros
#define MACRO_G4EToF_C
Functions
void ETOFInit ()
void ETOFSetup (PHG4Reco *g4Reco)
void ETOF_Reco ()
Variables
bool Enable::ETOF = false
bool Enable::ETOF_GAS = false
bool Enable::ETOF_OVERLAPCHECK = false
int Enable::ETOF_VERBOSITY = 0
int ETOF::f_gas_lyr = 6.
int ETOF::f_mrpc_lyr = 7.
int ETOF::b_gas_lyr = 6.
int ETOF::b_mrpc_lyr = 7.
int ETOF::pcb_lyr = 3.
int ETOF::mylar_lyr = 4.
int ETOF::cu_lyr = 4.
int ETOF::carbon_lyr = 4.
int ETOF::honeycomb_lyr = 2.
double ETOF::z_start = -165.
double ETOF::R_in = 6.5
double ETOF::R_out = 68.
double ETOF::gas_gap = 0.0220
double ETOF::mrpc_thick = 0.04
double ETOF::pcb_thick = 0.06
double ETOF::cu_thick = 0.003
double ETOF::carbon_thick = 0.01
double ETOF::mylar_thick = 0.04
double ETOF::honeycomb_thick = 0.75
double ETOF::tof_width = (f_gas_lyr + b_gas_lyr) * gas_gap + (f_mrpc_lyr + b_mrpc_lyr) * mrpc_thick + carbon_lyr * carbon_thick + pcb_lyr * pcb_thick + cu_lyr * cu_thick + mylar_lyr * mylar_thick + honeycomb_lyr * honeycomb_thick
double ETOF::z_end = (z_start + tof_width)
Macro Definition Documentation
#define MACRO_G4EToF_C
Definition at line 2 of file G4_EToF.C.
View newest version in sPHENIX GitHub at line 2 of file G4_EToF.C
Function Documentation
void ETOF_Reco ()
Definition at line 118 of file G4_EToF.C.
View newest version in sPHENIX GitHub at line 118 of file G4_EToF.C
References Enable::ETOF_VERBOSITY, Fun4AllServer::instance(), max, and Enable::VERBOSITY.
void ETOFInit ()
Definition at line 52 of file G4_EToF.C.
View newest version in sPHENIX GitHub at line 52 of file G4_EToF.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, ETOF::R_out, ETOF::z_end, and ETOF::z_start.
Referenced by G4Init().
void ETOFSetup (PHG4Reco * g4Reco)
Definition at line 59 of file G4_EToF.C.
View newest version in sPHENIX GitHub at line 59 of file G4_EToF.C
References Enable::ABSORBER, PHG4TrackFastSim::add_zplane_state(), ETOF::b_gas_lyr, ETOF::carbon_thick, ETOF::cu_thick, Enable::ETOF_GAS, Enable::ETOF_OVERLAPCHECK, Enable::ETOF_VERBOSITY, ETOF::f_gas_lyr, TRACKING::FastKalmanFilter(), ETOF::gas_gap, ETOF::honeycomb_thick, Fun4AllServer::instance(), max, ETOF::mrpc_thick, ETOF::mylar_thick, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), ETOF::pcb_thick, TRACKING::ProjectionNames, ETOF::R_in, ETOF::R_out, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), and ETOF::z_start.
Referenced by G4Setup().