ECCE @ EIC Software: G4CascadeChannel Class Reference
G4CascadeChannel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeChannel.hh>
Public Member Functions
G4CascadeChannel ()
virtual ~G4CascadeChannel ()
virtual G4double getCrossSection (double ke) const =0
virtual G4double getCrossSectionSum (double ke) const =0
virtual G4int getMultiplicity (G4double ke) const =0
virtual void getOutgoingParticleTypes (std::vector< G4int > &kinds, G4int mult, G4double ke) const =0
virtual void printTable (std::ostream &os=G4cout) const =0
Detailed Description
Definition at line 42 of file G4CascadeChannel.hh.
View newest version in sPHENIX GitHub at line 42 of file G4CascadeChannel.hh
Constructor & Destructor Documentation
G4CascadeChannel::G4CascadeChannel () inline
Definition at line 44 of file G4CascadeChannel.hh.
View newest version in sPHENIX GitHub at line 44 of file G4CascadeChannel.hh
virtual G4CascadeChannel::~G4CascadeChannel () inline virtual
Definition at line 45 of file G4CascadeChannel.hh.
View newest version in sPHENIX GitHub at line 45 of file G4CascadeChannel.hh
Member Function Documentation
virtual G4double G4CascadeChannel::getCrossSection (double ke) const pure virtual
Implemented in G4CascadeFunctions< DATA, SAMP >, G4CascadeFunctions< G4CascadeNNChannelData, G4PionNucSampler >, G4CascadeFunctions< G4CascadePPChannelData, G4PionNucSampler >, and G4CascadeFunctions< G4CascadeNPChannelData, G4PionNucSampler >.
Referenced by G4LightTargetCollider::collide(), and G4NucleiModel::totalCrossSection().
virtual G4double G4CascadeChannel::getCrossSectionSum (double ke) const pure virtual
Implemented in G4CascadeFunctions< DATA, SAMP >, G4CascadeFunctions< G4CascadeNNChannelData, G4PionNucSampler >, G4CascadeFunctions< G4CascadePPChannelData, G4PionNucSampler >, and G4CascadeFunctions< G4CascadeNPChannelData, G4PionNucSampler >.
virtual G4int G4CascadeChannel::getMultiplicity (G4double ke) const pure virtual
Implemented in G4CascadeFunctions< DATA, SAMP >, G4CascadeFunctions< G4CascadeNNChannelData, G4PionNucSampler >, G4CascadeFunctions< G4CascadePPChannelData, G4PionNucSampler >, and G4CascadeFunctions< G4CascadeNPChannelData, G4PionNucSampler >.
Referenced by G4ElementaryParticleCollider::generateMultiplicity().
virtual void G4CascadeChannel::getOutgoingParticleTypes (std::vector< G4int > & kinds, G4int mult, G4double ke) const pure virtual
Implemented in G4CascadeFunctions< DATA, SAMP >, G4CascadeFunctions< G4CascadeNNChannelData, G4PionNucSampler >, G4CascadeFunctions< G4CascadePPChannelData, G4PionNucSampler >, and G4CascadeFunctions< G4CascadeNPChannelData, G4PionNucSampler >.
Referenced by G4ElementaryParticleCollider::generateOutgoingPartTypes().
virtual void G4CascadeChannel::printTable (std::ostream & os = G4cout) const pure virtual
Implemented in G4CascadeFunctions< DATA, SAMP >, G4CascadeFunctions< G4CascadeNNChannelData, G4PionNucSampler >, G4CascadeFunctions< G4CascadePPChannelData, G4PionNucSampler >, and G4CascadeFunctions< G4CascadeNPChannelData, G4PionNucSampler >.
Referenced by operator<<(), and G4CascadeChannelTables::PrintTable().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeChannel.hh