ECCE @ EIC Software: G4BOptnLeadingParticle Class Reference
G4BOptnLeadingParticle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnLeadingParticle.hh>
Public Member Functions
G4BOptnLeadingParticle (G4String name)
virtual ~G4BOptnLeadingParticle ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
void SetFurtherKillingProbability (G4double p)
G4double GetFurtherKillingProbability () const
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4ParticleChange fParticleChange
G4double fRussianRouletteKillingProbability
Detailed Description
Definition at line 54 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BOptnLeadingParticle.hh
Constructor & Destructor Documentation
G4BOptnLeadingParticle::G4BOptnLeadingParticle (G4String name)
Definition at line 33 of file G4BOptnLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 33 of file G4BOptnLeadingParticle.cc
G4BOptnLeadingParticle::~G4BOptnLeadingParticle () virtual
Definition at line 39 of file G4BOptnLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 39 of file G4BOptnLeadingParticle.cc
Member Function Documentation
G4VParticleChange * G4BOptnLeadingParticle::ApplyFinalStateBiasing (const G4BiasingProcessInterface * callingProcess, const G4Track * track, const G4Step * step, G4bool &) virtual
G4cout << G4endl;
Implements G4VBiasingOperation.
Definition at line 43 of file G4BOptnLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 43 of file G4BOptnLeadingParticle.cc
References kdfinder::abs(), G4ParticleChange::AddSecondary(), fKillTrackAndSecondaries, fParticleChange, fRussianRouletteKillingProbability, fStopAndKill, G4cout, G4endl, G4UniformRand, G4ParticleChange::GetEnergy(), G4Track::GetKineticEnergy(), G4ParticleChange::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4VProcess::GetProcessName(), G4VParticleChange::GetWeight(), G4Track::GetWeight(), G4BiasingProcessInterface::GetWrappedProcess(), incremental_prev_tag::idx, G4ParticleChange::Initialize(), G4VProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::ProposeTrackStatus(), G4Track::SetKineticEnergy(), G4Track::SetMomentumDirection(), G4VParticleChange::SetNumberOfSecondaries(), G4VParticleChange::SetSecondaryWeightByProcess(), G4Track::SetWeight(), and v.
virtual G4double G4BOptnLeadingParticle::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) inline virtual
Implements G4VBiasingOperation.
Definition at line 72 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BOptnLeadingParticle.hh
virtual G4VParticleChange* G4BOptnLeadingParticle::GenerateBiasingFinalState (const G4Track * , const G4Step *) inline virtual
Implements G4VBiasingOperation.
Definition at line 75 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BOptnLeadingParticle.hh
G4double G4BOptnLeadingParticle::GetFurtherKillingProbability () const inline
Definition at line 86 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 86 of file G4BOptnLeadingParticle.hh
References fRussianRouletteKillingProbability.
virtual const G4VBiasingInteractionLaw* G4BOptnLeadingParticle::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) inline virtual
Implements G4VBiasingOperation.
Definition at line 65 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BOptnLeadingParticle.hh
void G4BOptnLeadingParticle::SetFurtherKillingProbability (G4double p) inline
Definition at line 85 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BOptnLeadingParticle.hh
References fRussianRouletteKillingProbability.
Referenced by GB07BOptrLeadingParticle::ProposeFinalStateBiasingOperation().
Member Data Documentation
G4ParticleChange G4BOptnLeadingParticle::fParticleChange private
Definition at line 90 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BOptnLeadingParticle.hh
Referenced by ApplyFinalStateBiasing().
G4double G4BOptnLeadingParticle::fRussianRouletteKillingProbability private
Definition at line 91 of file G4BOptnLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BOptnLeadingParticle.hh
Referenced by ApplyFinalStateBiasing(), GetFurtherKillingProbability(), and SetFurtherKillingProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnLeadingParticle.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptnLeadingParticle.cc