ECCE @ EIC Software: G4AtimaEnergyLossModel Class Reference
G4AtimaEnergyLossModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4AtimaEnergyLossModel.hh>
Public Member Functions
G4AtimaEnergyLossModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="Atima")
virtual ~G4AtimaEnergyLossModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *couple) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double) override
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) override
virtual G4double GetParticleCharge (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) override
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &, G4double &, G4double) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual void StartTracking (G4Track *)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) override
G4double GetChargeSquareRatio () const
void SetChargeSquareRatio (G4double val)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void SetupParameters ()
void SetParticle (const G4ParticleDefinition *p)
void SetGenericIon (const G4ParticleDefinition *p)
G4double StoppingPower (G4double ap, G4double zp, G4double ep, G4double at, G4double zt)
G4double Bethek_dedx_e (G4double ap, G4double zp, G4double ep, G4double at, G4double zt)
G4double dedx_n (const G4double ap, const G4double zp, const G4double ep, const G4double at, const G4double zt)
G4double sezi_dedx_e (const G4double zp, const G4double ep, const G4double at, const G4double zt)
G4double sezi_p_se (const G4double energy, const G4double at, const G4double zt)
G4double EnergyTable_interpolate (G4double xval, const G4double *y)
G4AtimaEnergyLossModel & operator= (const G4AtimaEnergyLossModel &right)=delete
G4AtimaEnergyLossModel (const G4AtimaEnergyLossModel &)=delete
Private Attributes
const G4ParticleDefinition * particle
G4ParticleDefinition * theElectron
G4EmCorrections * corr
G4ParticleChangeForLoss * fParticleChange
G4NistManager * nist
G4Pow * g4calc
G4double mass
G4double tlimit
G4double spin
G4double magMoment2
G4double chargeSquare
G4double ratio
G4double formfact
G4double corrFactor
G4bool isIon
G4double MLN10
G4double atomic_mass_unit
G4double dedx_constant
G4double electron_mass
G4double fine_structure
G4double domega2dx_constant
Static Private Attributes
static G4double stepE = 0.0
static G4double tableE [200] = {0.0}
static const G4double element_atomic_weights [110]
static const G4double ls_coefficients_a [110][200]
static const G4double ls_coefficients_ahi [110][200]
static const G4double proton_stopping_coef [92][8]
static const G4double ionisation_potentials_z [121]
static const G4double atima_vfermi [92]
static const G4double atima_lambda_screening [92]
static const G4double x0 [92]
static const G4double x1 [92]
static const G4double afermi [92]
static const G4double c [92]
static const G4double m0 [92]
static const G4double del_0 [92]
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 57 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AtimaEnergyLossModel.hh
Constructor & Destructor Documentation
G4AtimaEnergyLossModel::G4AtimaEnergyLossModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "Atima") explicit
Definition at line 74 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 74 of file G4AtimaEnergyLossModel.cc
References atomic_mass_unit, corr, dedx_constant, domega2dx_constant, G4Electron::Electron(), electron_mass, G4LossTableManager::EmCorrections(), fine_structure, fParticleChange, g4calc, G4Exp(), G4Pow::GetInstance(), G4LossTableManager::Instance(), G4NistManager::Instance(), MeV, MLN10, nist, G4VEmModel::SetLowEnergyLimit(), SetParticle(), stepE, tableE, and theElectron.
G4AtimaEnergyLossModel::~G4AtimaEnergyLossModel () virtual
Definition at line 106 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 106 of file G4AtimaEnergyLossModel.cc
G4AtimaEnergyLossModel::G4AtimaEnergyLossModel (const G4AtimaEnergyLossModel &) private delete
Member Function Documentation
G4double G4AtimaEnergyLossModel::Bethek_dedx_e (G4double ap, G4double zp, G4double ep, G4double at, G4double zt) private
Definition at line 563 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 563 of file G4AtimaEnergyLossModel.cc
References G4Pow::A23(), afermi, Acts::Test::at, atomic_mass_unit, c, dedx_constant, del_0, e, electron_mass, element_atomic_weights, EnergyTable_interpolate(), Acts::VectorHelpers::eta(), f1, f2, fine_structure, g4calc, G4Exp(), G4Log(), G4lrint(), ionisation_potentials_z, ls_coefficients_a, ls_coefficients_ahi, m0, max, min, G4Pow::powA(), tableE, v1, v3, v4, x, x0, x1, and z.
Referenced by StoppingPower().
G4double G4AtimaEnergyLossModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 226 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 226 of file G4AtimaEnergyLossModel.cc
References ComputeCrossSectionPerElectron(), and Acts::VectorHelpers::cross().
G4double G4AtimaEnergyLossModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) virtual
Definition at line 195 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 195 of file G4AtimaEnergyLossModel.cc
References chargeSquare, Acts::VectorHelpers::cross(), G4Log(), mass, MaxSecondaryEnergy(), min, spin, and source.hepunit::twopi_mc2_rcl2.
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4AtimaEnergyLossModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double) override virtual
Reimplemented from G4VEmModel.
Definition at line 255 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 255 of file G4AtimaEnergyLossModel.cc
References Acts::Test::at, cm3, Acts::UnitConstants::g, G4lrint(), G4NistManager::GetAtomicMassAmu(), G4Material::GetDensity(), G4Material::GetIonisation(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4IonisParamMat::GetZeffective(), max, MeV, min, nist, and StoppingPower().
Referenced by CorrectionsAlongStep().
void G4AtimaEnergyLossModel::CorrectionsAlongStep (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double & eloss, G4double & , G4double length) override virtual
Reimplemented from G4VEmModel.
Definition at line 275 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 275 of file G4AtimaEnergyLossModel.cc
References cm, ComputeDEDXPerVolume(), DBL_MAX, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4VEmModel::GetModelOfFluctuations(), G4ParticleDefinition::GetPDGCharge(), isIon, mat, and G4VEmFluctuationModel::SetParticleAndCharge().
G4double G4AtimaEnergyLossModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 240 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 240 of file G4AtimaEnergyLossModel.cc
References ComputeCrossSectionPerElectron(), Acts::VectorHelpers::cross(), and G4Material::GetElectronDensity().
G4double G4AtimaEnergyLossModel::dedx_n (const G4double ap, const G4double zp, const G4double ep, const G4double at, const G4double zt) private
Definition at line 446 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 446 of file G4AtimaEnergyLossModel.cc
References Acts::Test::at, source.hepunit::Avogadro, epsilon(), g4calc, G4Log(), G4Pow::powA(), and sn.
Referenced by StoppingPower().
G4double G4AtimaEnergyLossModel::EnergyTable_interpolate (G4double xval, const G4double * y) private
Definition at line 651 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 651 of file G4AtimaEnergyLossModel.cc
References G4Log(), max, min, MLN10, num, r, stepE, tableE, and x.
Referenced by Bethek_dedx_e().
G4double G4AtimaEnergyLossModel::GetChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 134 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 134 of file G4AtimaEnergyLossModel.cc
References corr, corrFactor, G4EmCorrections::EffectiveChargeCorrection(), and G4EmCorrections::EffectiveChargeSquareRatio().
G4double G4AtimaEnergyLossModel::GetChargeSquareRatio () const inline protected
Definition at line 208 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 208 of file G4AtimaEnergyLossModel.hh
References chargeSquare.
G4double G4AtimaEnergyLossModel::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 146 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 146 of file G4AtimaEnergyLossModel.cc
References corr, and G4EmCorrections::GetParticleCharge().
void G4AtimaEnergyLossModel::Initialise (const G4ParticleDefinition * p, const G4DataVector &) override virtual
Implements G4VEmModel.
Definition at line 111 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 111 of file G4AtimaEnergyLossModel.cc
References fParticleChange, G4VEmModel::GetAngularDistribution(), G4VEmModel::GetParticleChangeForLoss(), G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), SetGenericIon(), SetParticle(), and G4VEmModel::UseAngularGeneratorFlag().
G4double G4AtimaEnergyLossModel::MaxSecondaryEnergy (const G4ParticleDefinition * pd, G4double kinEnergy) override protected virtual
Reimplemented from G4VEmModel.
Definition at line 410 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 410 of file G4AtimaEnergyLossModel.cc
References source.hepunit::electron_mass_c2, mass, min, ratio, SetParticle(), and tlimit.
Referenced by ComputeCrossSectionPerElectron(), and SampleSecondaries().
G4double G4AtimaEnergyLossModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple * couple) override virtual
Reimplemented from G4VEmModel.
Definition at line 186 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 186 of file G4AtimaEnergyLossModel.cc
References G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), and G4IonisParamMat::GetMeanExcitationEnergy().
G4AtimaEnergyLossModel& G4AtimaEnergyLossModel::operator= (const G4AtimaEnergyLossModel & right) private delete
void G4AtimaEnergyLossModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 294 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 294 of file G4AtimaEnergyLossModel.cc
References Acts::Test::delta, e, source.hepunit::electron_mass_c2, f, f1, CLHEP::HepRandomEngine::flat(), CLHEP::HepRandomEngine::flatArray(), formfact, fParticleChange, G4cout, G4endl, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4DynamicParticle::GetTotalMomentum(), magMoment2, mass, mat, MaxSecondaryEnergy(), min, phi, CLHEP::Hep3Vector::rotateUz(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SelectRandomAtomNumber(), CLHEP::Hep3Vector::set(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), spin, theElectron, twopi, CLHEP::Hep3Vector::unit(), G4VEmModel::UseAngularGeneratorFlag(), x, x2, and Z.
void G4AtimaEnergyLossModel::SetChargeSquareRatio (G4double val) inline protected
Definition at line 215 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 215 of file G4AtimaEnergyLossModel.hh
References chargeSquare.
void G4AtimaEnergyLossModel::SetGenericIon (const G4ParticleDefinition * p) inline private
Definition at line 201 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 201 of file G4AtimaEnergyLossModel.hh
References G4ParticleDefinition::GetParticleName(), and isIon.
Referenced by Initialise().
void G4AtimaEnergyLossModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 189 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 189 of file G4AtimaEnergyLossModel.hh
References CLHEP::eplus, G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetPDGCharge(), isIon, particle, and SetupParameters().
Referenced by G4AtimaEnergyLossModel(), Initialise(), and MaxSecondaryEnergy().
void G4AtimaEnergyLossModel::SetupParameters () private
Definition at line 158 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 158 of file G4AtimaEnergyLossModel.cc
References source.hepunit::c_squared, chargeSquare, corrFactor, DBL_MAX, e, source.hepunit::electron_mass_c2, eplus, formfact, G4lrint(), G4NistManager::GetA27(), G4ParticleDefinition::GetLeptonNumber(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), GeV, source.hepunit::hbar_Planck, magMoment2, mass, nist, particle, ratio, spin, tlimit, and x.
Referenced by SetParticle().
G4double G4AtimaEnergyLossModel::sezi_dedx_e (const G4double zp, const G4double ep, const G4double at, const G4double zt) private
Definition at line 466 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 466 of file G4AtimaEnergyLossModel.cc
References a, kdfinder::abs(), atima_lambda_screening, atima_vfermi, b, e, g4calc, G4Exp(), G4Log(), h1, max, min, G4Pow::powA(), sezi_p_se(), v, and v2.
Referenced by StoppingPower().
G4double G4AtimaEnergyLossModel::sezi_p_se (const G4double energy, const G4double at, const G4double zt) private
Definition at line 544 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 544 of file G4AtimaEnergyLossModel.cc
References Acts::Test::at, source.hepunit::Avogadro, e, energy, g4calc, G4Log(), G4Pow::powA(), proton_stopping_coef, and G4InuclParticleNames::sp.
Referenced by sezi_dedx_e().
G4double G4AtimaEnergyLossModel::StoppingPower (G4double ap, G4double zp, G4double ep, G4double at, G4double zt) private
Definition at line 423 of file G4AtimaEnergyLossModel.cc.
View newest version in sPHENIX GitHub at line 423 of file G4AtimaEnergyLossModel.cc
References G4InuclParticleNames::ap, atomic_mass_unit, Bethek_dedx_e(), dedx_n(), and sezi_dedx_e().
Referenced by ComputeDEDXPerVolume().
Member Data Documentation
const G4double G4AtimaEnergyLossModel::afermi static private
Initial value:
= {
 0.14092, 0.13443,  0.95136, 0.80392, 0.56224, 0.26142, 0.15349, 0.11778, 0.11083, .08064,
 0.07772, 0.08163,  0.08024, 0.14921, 0.23610, 0.33992, 0.19849, 0.19714, 0.19827, .15643,
 0.15754, 0.15662,  0.15436, 0.15419, 0.14973, 0.14680, 0.14474, 0.16496, 0.14339, .14714,
 0.09440, 0.07188,  0.06633, 0.06568, 0.06335, 0.07446, 0.07261, 0.07165, 0.07138, .07177,
 0.13883, 0.10525,  0.16572, 0.19342, 0.19205, 0.24178, 0.24585, 0.24609, 0.23879, .18689,
 0.16652, 0.13815,  0.23766, 0.23314, 0.18233, 0.18268, 0.18591, 0.18885, 0.23265, .23530,
 0.24280, 0.24698,  0.24448, 0.25109, 0.24453, 0.24665, 0.24638, 0.24823, 0.24889, .25295,
 0.24033, 0.22918,  0.17798, 0.15509, 0.15184, 0.12751, 0.12690, 0.11128, 0.09756, .11014,
 0.09455, 0.09359,  0.09410, 0.09282, 0.09000, 0.20798, 0.08000, 0.08804, 0.08567, 0.08655,
 0.14770,  0.19677 }
Definition at line 180 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
const G4double G4AtimaEnergyLossModel::atima_lambda_screening static private
Definition at line 177 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4AtimaEnergyLossModel.hh
Referenced by sezi_dedx_e().
const G4double G4AtimaEnergyLossModel::atima_vfermi static private
Definition at line 176 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4AtimaEnergyLossModel.hh
Referenced by sezi_dedx_e().
G4double G4AtimaEnergyLossModel::atomic_mass_unit private
Definition at line 162 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e(), G4AtimaEnergyLossModel(), and StoppingPower().
const G4double G4AtimaEnergyLossModel::c static private
Initial value:
= {
9.5835, 11.1393, 3.1221, 2.7847, 2.8477, 2.8680, 10.5400, 10.7004, 10.9653, 11.9041,
5.0526, 4.5297,  4.2395, 4.4351, 4.5214, 4.6659, 11.1421, 11.9480, 5.6423, 5.0396,
4.6949, 4.4450,  4.2659, 4.1781, 4.2702, 4.2911, 4.2601, 4.3115, 4.4190, 4.6906,
4.9353, 5.1411,  5.0510, 5.3210, 11.7307,12.5115,6.4776, 5.9867, 5.4801 , 5.1774,
5.0141, 4.8793,  4.7769, 4.7694, 4.8008, 4.9358, 5.0630, 5.2727, 5.5211, 5.5340,
5.6241, 5.7131,  5.9488, 12.7281, 6.9135, 6.3153, 5.7850, 5.7837, 5.8096, 5.8290,
5.8224, 5.8597,  6.2278, 5.8738, 5.9045, 5.9183, 5.9587, 5.9521, 5.9677, 6.3325,
5.9785, 5.7139,  5.5262, 5.4059, 5.3445, 5.3083, 5.3418, 5.4732, 5.5747, 5.9605,
6.1365, 6.2018,  6.3505, 6.4003, 6.4, 13.2839, 7., 7.0452, 6.3742, 6.2473,
6.0327, 5.8694 }
Definition at line 181 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
G4double G4AtimaEnergyLossModel::chargeSquare private
Definition at line 156 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4AtimaEnergyLossModel.hh
Referenced by ComputeCrossSectionPerElectron(), GetChargeSquareRatio(), SetChargeSquareRatio(), and SetupParameters().
G4EmCorrections* G4AtimaEnergyLossModel::corr private
Definition at line 147 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4AtimaEnergyLossModel.hh
Referenced by G4AtimaEnergyLossModel(), GetChargeSquareRatio(), and GetParticleCharge().
G4double G4AtimaEnergyLossModel::corrFactor private
Definition at line 159 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4AtimaEnergyLossModel.hh
Referenced by GetChargeSquareRatio(), and SetupParameters().
G4double G4AtimaEnergyLossModel::dedx_constant private
Definition at line 163 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e(), and G4AtimaEnergyLossModel().
const G4double G4AtimaEnergyLossModel::del_0 static private
Initial value:
= {
0.0,  0.00,  0.14, 0.14, 0.14, 0.12, 0.00, 0.00, 0.00, 0.00,
0.08, 0.08,  0.12, 0.14, 0.14, 0.14, 0.00, 0.00, 0.10, 0.14,
0.10, 0.12,  0.14, 0.14, 0.14, 0.12, 0.12, 0.10, 0.08, 0.08,
0.14, 0.14,  0.08, 0.10, 0.00, 0.00, 0.14, 0.14, 0.14, 0.14,
0.14, 0.14,  0.14, 0.14, 0.14, 0.14, 0.14, 0.14, 0.14, 0.14,
0.14, 0.14,  0.00, 0.00, 0.14, 0.14, 0.14, 0.14, 0.14, 0.14,
0.14, 0.14,  0.14, 0.14, 0.14, 0.14, 0.14, 0.14, 0.14, 0.14,
0.14, 0.14,  0.14, 0.14, 0.08, 0.10, 0.10, 0.12, 0.14, 0.14,
0.14, 0.14,  0.14, 0.14, 0.00, 0.00, 0.00, 0.14, 0.14, 0.14,
0.14, 0.14 }
Definition at line 183 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 183 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
G4double G4AtimaEnergyLossModel::domega2dx_constant private
Definition at line 166 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4AtimaEnergyLossModel.hh
Referenced by G4AtimaEnergyLossModel().
G4double G4AtimaEnergyLossModel::electron_mass private
Definition at line 164 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e(), and G4AtimaEnergyLossModel().
const G4double G4AtimaEnergyLossModel::element_atomic_weights static private
Definition at line 170 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
G4double G4AtimaEnergyLossModel::fine_structure private
Definition at line 165 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e(), and G4AtimaEnergyLossModel().
G4double G4AtimaEnergyLossModel::formfact private
Definition at line 158 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4AtimaEnergyLossModel.hh
Referenced by SampleSecondaries(), and SetupParameters().
G4ParticleChangeForLoss* G4AtimaEnergyLossModel::fParticleChange private
Definition at line 148 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4AtimaEnergyLossModel.hh
Referenced by G4AtimaEnergyLossModel(), Initialise(), and SampleSecondaries().
G4Pow* G4AtimaEnergyLossModel::g4calc private
Definition at line 150 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e(), dedx_n(), G4AtimaEnergyLossModel(), sezi_dedx_e(), and sezi_p_se().
const G4double G4AtimaEnergyLossModel::ionisation_potentials_z static private
Definition at line 174 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
G4bool G4AtimaEnergyLossModel::isIon private
Definition at line 160 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4AtimaEnergyLossModel.hh
Referenced by CorrectionsAlongStep(), SetGenericIon(), and SetParticle().
const G4double G4AtimaEnergyLossModel::ls_coefficients_a static private
Definition at line 171 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 171 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
const G4double G4AtimaEnergyLossModel::ls_coefficients_ahi static private
Definition at line 172 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
const G4double G4AtimaEnergyLossModel::m0 static private
Initial value:
= {
5.7273, 5.8347,  2.4993, 2.4339, 2.4512, 2.8697, 3.2125, 3.2913, 3.2962, 3.5771,
3.6452, 3.6166,  3.6345, 3.2546, 2.9158, 2.6456, 2.9702, 2.9618, 2.9233, 3.0745,
3.0517, 3.0302,  3.0163, 2.9896, 2.9796, 2.9632, 2.9502, 2.8430, 2.9044, 2.8652,
3.1314, 3.3306,  3.4176, 3.4317, 3.4670, 3.4051, 3.4177, 3.4435, 3.4585, 3.4533,
3.0930, 3.2549,  2.9738, 2.8707, 2.8633, 2.7239, 2.6899, 2.6772, 2.7144, 2.8576,
2.9319, 3.0354,  2.7276, 2.7414, 2.8866, 2.8906, 2.8828, 2.8592, 2.7331, 2.7050,
2.6674, 2.6403,  2.6245, 2.5977, 2.6056, 2.5849, 2.5726, 2.5573, 2.5469, 2.5141,
2.5643, 2.6155,  2.7623, 2.8447, 2.8627, 2.9608, 2.9658, 3.0417, 3.1101, 3.0519,
3.1450, 3.1608,  3.1671, 3.1830, 1.1111, 2.7409, 1.1111, 3.2454, 3.2683, 3.2610,
2.9845, 2.8171 }
Definition at line 182 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
G4double G4AtimaEnergyLossModel::magMoment2 private
Definition at line 155 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4AtimaEnergyLossModel.hh
Referenced by SampleSecondaries(), and SetupParameters().
G4double G4AtimaEnergyLossModel::mass private
Definition at line 152 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4AtimaEnergyLossModel.hh
Referenced by ComputeCrossSectionPerElectron(), MaxSecondaryEnergy(), SampleSecondaries(), and SetupParameters().
G4double G4AtimaEnergyLossModel::MLN10 private
Definition at line 161 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4AtimaEnergyLossModel.hh
Referenced by EnergyTable_interpolate(), and G4AtimaEnergyLossModel().
G4NistManager* G4AtimaEnergyLossModel::nist private
Definition at line 149 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 149 of file G4AtimaEnergyLossModel.hh
Referenced by ComputeDEDXPerVolume(), G4AtimaEnergyLossModel(), and SetupParameters().
const G4ParticleDefinition* G4AtimaEnergyLossModel::particle private
Definition at line 145 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4AtimaEnergyLossModel.hh
Referenced by SetParticle(), and SetupParameters().
const G4double G4AtimaEnergyLossModel::proton_stopping_coef static private
Definition at line 173 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4AtimaEnergyLossModel.hh
Referenced by sezi_p_se().
G4double G4AtimaEnergyLossModel::ratio private
Definition at line 157 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4AtimaEnergyLossModel.hh
Referenced by MaxSecondaryEnergy(), and SetupParameters().
G4double G4AtimaEnergyLossModel::spin private
Definition at line 154 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4AtimaEnergyLossModel.hh
Referenced by ComputeCrossSectionPerElectron(), SampleSecondaries(), and SetupParameters().
G4double G4AtimaEnergyLossModel::stepE = 0.0 static private
Definition at line 168 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 168 of file G4AtimaEnergyLossModel.hh
Referenced by EnergyTable_interpolate(), and G4AtimaEnergyLossModel().
G4double G4AtimaEnergyLossModel::tableE = {0.0} static private
Definition at line 169 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e(), EnergyTable_interpolate(), and G4AtimaEnergyLossModel().
G4ParticleDefinition* G4AtimaEnergyLossModel::theElectron private
Definition at line 146 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4AtimaEnergyLossModel.hh
Referenced by G4AtimaEnergyLossModel(), and SampleSecondaries().
G4double G4AtimaEnergyLossModel::tlimit private
Definition at line 153 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4AtimaEnergyLossModel.hh
Referenced by MaxSecondaryEnergy(), and SetupParameters().
const G4double G4AtimaEnergyLossModel::x0 static private
Initial value:
= {
1.8639, 2.2017,  0.1304, 0.0592, 0.0305, -.0178, 1.7378, 1.7541, 1.8433, 2.0735,
0.2880, 0.1499,  0.1708, 0.2014, 0.1696, 0.1580, 1.5555, 1.7635, 0.3851, 0.3228,
0.1640, 0.0957,  0.0691, 0.0340, 0.0447, -.0012, -.0187, -.0566, -.0254, 0.0049,
0.2267, 0.3376,  0.1767, 0.2258, 1.5262, 1.7158, 0.5737, 0.4585, 0.3608, 0.2957,
0.1785, 0.2267,  0.0949, 0.0599, 0.0576, 0.0563, 0.0657, 0.1281, 0.2406, 0.2879,
0.3189, 0.3296,  0.0549, 1.5630, 0.5473, 0.4190, 0.3161, 0.2713, 0.2333, 0.1984,
0.1627, 0.1520,  0.1888, 0.1058, 0.0947, 0.0822, 0.0761, 0.0648, 0.0812, 0.1199,
0.1560, 0.1965,  0.2117, 0.2167, 0.0559, 0.0891, 0.0819, 0.1484, 0.2021, 0.2756,
0.3491, 0.3776,  0.4152, 0.4267, 0.4300, 1.5368, 0.6000, 0.5991, 0.4559, 0.4202,
0.3144, 0.2260 }
Definition at line 178 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 178 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
const G4double G4AtimaEnergyLossModel::x1 static private
Initial value:
= {
3.2718, 3.6122,  1.6397, 1.6922, 1.9688, 2.3415, 4.1323, 4.3213, 4.4096, 4.6421,
3.1962, 3.0668,  3.0127, 2.8715, 2.7815, 2.7159, 4.2994, 4.4855, 3.1724, 3.1191,
3.0593, 3.0386,  3.0322, 3.0451, 3.1074, 3.1531, 3.1790, 3.1851, 3.2792, 3.3668,
3.5434, 3.6096,  3.5702, 3.6264, 4.9899, 5.0748, 3.7995, 3.6778, 3.5542, 3.4890,
3.2201, 3.2784,  3.1253, 3.0834, 3.1069, 3.0555, 3.1074, 3.1667, 3.2032, 3.2959,
3.3489, 3.4418,  3.2596, 4.7371, 3.5914, 3.4547, 3.3293, 3.3432, 3.2773, 3.3063,
3.3199, 3.3460,  3.4633, 3.3932, 3.4224, 3.4474, 3.4782, 3.4922, 3.5085, 3.6246,
3.5218, 3.4337,  3.4805, 3.4960, 3.4845, 3.5414, 3.5480, 3.6212, 3.6979, 3.7275,
3.8044, 3.8073,  3.8248, 3.8293, 4.0000, 4.9889, 4.0000, 3.9428, 3.7966, 3.7681,
3.5079, 3.3721 }
Definition at line 179 of file G4AtimaEnergyLossModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4AtimaEnergyLossModel.hh
Referenced by Bethek_dedx_e().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4AtimaEnergyLossModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4AtimaEnergyLossModel.cc