ECCE @ EIC Software: G4MicroElecElasticModel Class Reference
G4MicroElecElasticModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MicroElecElasticModel.hh>
Public Member Functions
G4MicroElecElasticModel (const G4ParticleDefinition *p=0, const G4String &nam="MicroElecElasticModel")
virtual ~G4MicroElecElasticModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
void SetKillBelowThreshold (G4double threshold)
G4double GetKillBelowThreshold ()
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Types
typedef std::map< G4String,
G4String, std::less< G4String > > MapFile
typedef std::map< G4String,
G4MicroElecCrossSectionDataSet
*, std::less< G4String > > MapData
typedef std::map< double,
std::map< double, double > > TriDimensionMap
typedef std::map< double,
std::vector< double > > VecMap
Private Member Functions
G4double Theta (G4ParticleDefinition *aParticleDefinition, G4double k, G4double integrDiff)
G4double LinLinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
G4double RandomizeCosTheta (G4double k)
G4MicroElecElasticModel & operator= (const G4MicroElecElasticModel &right)
G4MicroElecElasticModel (const G4MicroElecElasticModel &)
Private Attributes
G4Material * nistSi
G4double killBelowEnergy
G4double lowEnergyLimit
G4double lowEnergyLimitOfModel
G4double highEnergyLimit
G4bool isInitialised
G4int verboseLevel
MapFile tableFile
MapData tableData
TriDimensionMap eDiffCrossSectionData
std::vector< double > eTdummyVec
VecMap eVecm
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 51 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 51 of file G4MicroElecElasticModel.hh
Member Typedef Documentation
typedef std::map<G4String,G4MicroElecCrossSectionDataSet*,std::less<G4String> > G4MicroElecElasticModel::MapData private
Definition at line 97 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4MicroElecElasticModel.hh
typedef std::map<G4String,G4String,std::less<G4String> > G4MicroElecElasticModel::MapFile private
Definition at line 94 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4MicroElecElasticModel.hh
typedef std::map<double, std::map<double, double> > G4MicroElecElasticModel::TriDimensionMap private
Definition at line 123 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 123 of file G4MicroElecElasticModel.hh
typedef std::map<double, std::vector<double> > G4MicroElecElasticModel::VecMap private
Definition at line 128 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4MicroElecElasticModel.hh
Constructor & Destructor Documentation
G4MicroElecElasticModel::G4MicroElecElasticModel (const G4ParticleDefinition * p = 0, const G4String & nam = "MicroElecElasticModel")
Definition at line 49 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4MicroElecElasticModel.cc
References eV, G4NistManager::FindOrBuildMaterial(), fParticleChangeForGamma, G4cout, G4endl, highEnergyLimit, G4NistManager::Instance(), killBelowEnergy, lowEnergyLimit, lowEnergyLimitOfModel, MeV, nistSi, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), and verboseLevel.
G4MicroElecElasticModel::~G4MicroElecElasticModel () virtual
Definition at line 83 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 83 of file G4MicroElecElasticModel.cc
References eVecm, pos(), and tableData.
G4MicroElecElasticModel::G4MicroElecElasticModel (const G4MicroElecElasticModel &) private
Member Function Documentation
G4double G4MicroElecElasticModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 216 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 216 of file G4MicroElecElasticModel.cc
References cm, DBL_MAX, eV, FatalException, G4MicroElecCrossSectionDataSet::FindValue(), G4cout, G4endl, G4Exception(), G4Material::GetBaseMaterial(), G4ParticleDefinition::GetParticleName(), G4Material::GetTotNbOfAtomsPerVolume(), highEnergyLimit, killBelowEnergy, nistSi, pos(), tableData, and verboseLevel.
G4double G4MicroElecElasticModel::GetKillBelowThreshold () inline
Definition at line 76 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MicroElecElasticModel.hh
References killBelowEnergy.
void G4MicroElecElasticModel::Initialise (const G4ParticleDefinition * , const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 102 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 102 of file G4MicroElecElasticModel.cc
References cm, e, eDiffCrossSectionData, G4InuclParticleNames::electron, G4Electron::ElectronDefinition(), eTdummyVec, eV, eVecm, FatalException, fParticleChangeForGamma, G4cout, G4endl, G4Exception(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), highEnergyLimit, G4VEmModel::HighEnergyLimit(), isInitialised, G4MicroElecCrossSectionDataSet::LoadData(), lowEnergyLimit, G4VEmModel::LowEnergyLimit(), MeV, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), tableData, tableFile, and verboseLevel.
G4double G4MicroElecElasticModel::LinLinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 388 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 388 of file G4MicroElecElasticModel.cc
References d1, d2, and e1.
Referenced by QuadInterpolator().
G4double G4MicroElecElasticModel::LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 374 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 374 of file G4MicroElecElasticModel.cc
References d1, d2, and G4Exp().
G4double G4MicroElecElasticModel::LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 402 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 402 of file G4MicroElecElasticModel.cc
References a, and b.
G4MicroElecElasticModel& G4MicroElecElasticModel::operator= (const G4MicroElecElasticModel & right) private
G4double G4MicroElecElasticModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 417 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 417 of file G4MicroElecElasticModel.cc
References LinLinInterpolate().
G4double G4MicroElecElasticModel::RandomizeCosTheta (G4double k) private
Definition at line 447 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 447 of file G4MicroElecElasticModel.cc
References G4Electron::ElectronDefinition(), eV, G4UniformRand, pi, Theta(), and theta().
Referenced by SampleSecondaries().
void G4MicroElecElasticModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * aDynamicElectron, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 272 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 272 of file G4MicroElecElasticModel.cc
References CLHEP::Hep3Vector::cross(), fParticleChangeForGamma, fStopAndKill, G4cout, G4endl, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), highEnergyLimit, killBelowEnergy, CLHEP::Hep3Vector::orthogonal(), phi, pi, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), RandomizeCosTheta(), return(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), CLHEP::Hep3Vector::unit(), and verboseLevel.
void G4MicroElecElasticModel::SetKillBelowThreshold (G4double threshold) inline
Definition at line 140 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 140 of file G4MicroElecElasticModel.hh
References CLHEP::eV, G4Exception(), JustWarning, and killBelowEnergy.
G4double G4MicroElecElasticModel::Theta (G4ParticleDefinition * aParticleDefinition, G4double k, G4double integrDiff) private
Definition at line 319 of file G4MicroElecElasticModel.cc.
View newest version in sPHENIX GitHub at line 319 of file G4MicroElecElasticModel.cc
References G4Electron::ElectronDefinition(), k, t1, t2, and theta().
Referenced by RandomizeCosTheta().
Member Data Documentation
TriDimensionMap G4MicroElecElasticModel::eDiffCrossSectionData private
Definition at line 125 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4MicroElecElasticModel.hh
Referenced by Initialise().
std::vector<double> G4MicroElecElasticModel::eTdummyVec private
Definition at line 126 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4MicroElecElasticModel.hh
Referenced by Initialise().
VecMap G4MicroElecElasticModel::eVecm private
Definition at line 129 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4MicroElecElasticModel.hh
Referenced by Initialise(), and ~G4MicroElecElasticModel().
G4ParticleChangeForGamma* G4MicroElecElasticModel::fParticleChangeForGamma protected
Definition at line 80 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4MicroElecElasticModel.hh
Referenced by G4MicroElecElasticModel(), Initialise(), and SampleSecondaries().
G4double G4MicroElecElasticModel::highEnergyLimit private
Definition at line 88 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4MicroElecElasticModel.hh
Referenced by CrossSectionPerVolume(), G4MicroElecElasticModel(), Initialise(), and SampleSecondaries().
G4bool G4MicroElecElasticModel::isInitialised private
Definition at line 89 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MicroElecElasticModel.hh
Referenced by Initialise().
G4double G4MicroElecElasticModel::killBelowEnergy private
Definition at line 85 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MicroElecElasticModel.hh
Referenced by CrossSectionPerVolume(), G4MicroElecElasticModel(), GetKillBelowThreshold(), SampleSecondaries(), and SetKillBelowThreshold().
G4double G4MicroElecElasticModel::lowEnergyLimit private
Definition at line 86 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MicroElecElasticModel.hh
Referenced by G4MicroElecElasticModel(), and Initialise().
G4double G4MicroElecElasticModel::lowEnergyLimitOfModel private
Definition at line 87 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MicroElecElasticModel.hh
Referenced by G4MicroElecElasticModel().
G4Material* G4MicroElecElasticModel::nistSi private
Definition at line 84 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4MicroElecElasticModel.hh
Referenced by CrossSectionPerVolume(), and G4MicroElecElasticModel().
MapData G4MicroElecElasticModel::tableData private
Definition at line 98 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4MicroElecElasticModel.hh
Referenced by CrossSectionPerVolume(), Initialise(), and ~G4MicroElecElasticModel().
MapFile G4MicroElecElasticModel::tableFile private
Definition at line 95 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 95 of file G4MicroElecElasticModel.hh
Referenced by Initialise().
G4int G4MicroElecElasticModel::verboseLevel private
Definition at line 90 of file G4MicroElecElasticModel.hh.
View newest version in sPHENIX GitHub at line 90 of file G4MicroElecElasticModel.hh
Referenced by CrossSectionPerVolume(), G4MicroElecElasticModel(), Initialise(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MicroElecElasticModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4MicroElecElasticModel.cc