ECCE @ EIC Software: G4DNAMolecularDissociation Class Reference
G4DNAMolecularDissociation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNAMolecularDissociation.hh>
Public Types
using Species = const G4MoleculeDefinition
using Displacer = G4VMolecularDissociationDisplacer
Public Member Functions
G4DNAMolecularDissociation (const G4String &processName="DNAMolecularDecay", G4ProcessType type=fDecay)
G4DNAMolecularDissociation ()=delete
G4DNAMolecularDissociation (const G4DNAMolecularDissociation &right)=delete
G4DNAMolecularDissociation & operator= (const G4DNAMolecularDissociation &right)=delete
~G4DNAMolecularDissociation () override
G4bool IsApplicable (const G4ParticleDefinition &) override
G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition) override
G4VParticleChange * AtRestDoIt (const G4Track &track, const G4Step &step) override
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step) override
void SetVerbose (G4int)
void SetDisplacer (Species *, Displacer *)
Displacer * GetDisplacer (Species *)
Public Member Functions inherited from G4VITRestDiscreteProcess
G4VITRestDiscreteProcess ()=delete
G4VITRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VITRestDiscreteProcess (const G4VITRestDiscreteProcess &)=delete
G4VITRestDiscreteProcess & operator= (const G4VITRestDiscreteProcess &right)=delete
~G4VITRestDiscreteProcess () override
G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *) override
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
Public Member Functions inherited from G4VITProcess
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4bool operator== (const G4VITProcess &right) const
G4bool operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
virtual void StartTracking (G4Track *)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4VParticleChange * DecayIt (const G4Track &, const G4Step &)
G4double GetMeanLifeTime (const G4Track &, G4ForceCondition *) override
G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *) override
Private Types
using DisplacementMap = std::map< Species *, std::unique_ptr< Displacer >>
Private Attributes
G4bool fDecayAtFixedTime
DisplacementMap fDisplacementMap
G4int fVerbose
Additional Inherited Members
Static Public Member Functions inherited from G4VITProcess
static const size_t & GetMaxProcessIndex ()
Protected Attributes inherited from G4VITProcess
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Detailed Description
G4DNAMolecularDissociation should be called only for molecules. It will dissociate the molecules using the decay associated to this molecule and if a displacement scheme has been registered, it will place the products to the expected position.
Definition at line 63 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 63 of file G4DNAMolecularDissociation.hh
Member Typedef Documentation
using G4DNAMolecularDissociation::DisplacementMap = std::map<Species*, std::unique_ptr<Displacer>> private
Definition at line 104 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNAMolecularDissociation.hh
using G4DNAMolecularDissociation::Displacer = G4VMolecularDissociationDisplacer
Definition at line 74 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 74 of file G4DNAMolecularDissociation.hh
using G4DNAMolecularDissociation::Species = const G4MoleculeDefinition
Definition at line 73 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DNAMolecularDissociation.hh
Constructor & Destructor Documentation
G4DNAMolecularDissociation::G4DNAMolecularDissociation (const G4String & processName = "DNAMolecularDecay", G4ProcessType type = fDecay)
Definition at line 50 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 50 of file G4DNAMolecularDissociation.cc
References G4VProcess::aParticleChange, G4VProcess::enableAlongStepDoIt, G4VProcess::enableAtRestDoIt, G4VProcess::enablePostStepDoIt, fDecayAtFixedTime, G4VITProcess::fProposesTimeStep, fVerbose, G4cout, G4endl, G4VProcess::pParticleChange, G4VProcess::SetProcessSubType(), and G4VProcess::verboseLevel.
G4DNAMolecularDissociation::G4DNAMolecularDissociation () delete
G4DNAMolecularDissociation::G4DNAMolecularDissociation (const G4DNAMolecularDissociation & right) delete
G4DNAMolecularDissociation::~G4DNAMolecularDissociation () override default
Member Function Documentation
G4VParticleChange * G4DNAMolecularDissociation::AtRestDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VITRestDiscreteProcess.
Definition at line 314 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 314 of file G4DNAMolecularDissociation.cc
References G4VITProcess::ClearInteractionTimeLeft(), G4VITProcess::ClearNumberOfInteractionLengthLeft(), and DecayIt().
Referenced by PostStepDoIt().
G4double G4DNAMolecularDissociation::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) override virtual
Reimplemented from G4VITRestDiscreteProcess.
Definition at line 324 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 324 of file G4DNAMolecularDissociation.cc
References G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), fDecayAtFixedTime, and GetMeanLifeTime().
G4VParticleChange * G4DNAMolecularDissociation::DecayIt (const G4Track & track, const G4Step &) protected virtual
Definition at line 115 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 115 of file G4DNAMolecularDissociation.cc
References G4VProcess::aParticleChange, DBL_MAX, e, fAlive, FatalErrorInArgument, FatalException, fDisplacementMap, fStopAndKill, fVerbose, G4cout, G4endl, G4Exception(), G4UniformRand, G4MolecularDissociationChannel::GetEnergy(), G4Track::GetGlobalTime(), GetMolecule(), G4MolecularDissociationChannel::GetName(), G4VPhysicalVolume::GetName(), G4ITTransportationManager::GetNavigatorForTracking(), G4MolecularDissociationChannel::GetNbProducts(), G4Track::GetPosition(), G4MolecularDissociationChannel::GetProbability(), G4MolecularDissociationChannel::GetProduct(), G4VTouchable::GetSolid(), G4Track::GetTouchable(), G4Track::GetTrackID(), G4ITTransportationManager::GetTransportationManager(), G4VTouchable::GetVolume(), G4ParticleChange::Initialize(), G4VSolid::Inside(), it, JustWarning, kInside, min, G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::SetNumberOfSecondaries(), Acts::Test::transform, and G4AffineTransform::TransformPoint().
Referenced by AtRestDoIt().
G4DNAMolecularDissociation::Displacer * G4DNAMolecularDissociation::GetDisplacer (Species * pSpecies)
Definition at line 291 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 291 of file G4DNAMolecularDissociation.cc
References fDisplacementMap.
G4double G4DNAMolecularDissociation::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) override protected virtual
Implements G4VITRestDiscreteProcess.
Definition at line 345 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 345 of file G4DNAMolecularDissociation.cc
G4double G4DNAMolecularDissociation::GetMeanLifeTime (const G4Track & track, G4ForceCondition *) override protected virtual
Implements G4VITRestDiscreteProcess.
Definition at line 106 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 106 of file G4DNAMolecularDissociation.cc
References G4Molecule::GetDecayTime(), GetMolecule(), and G4Track::GetProperTime().
Referenced by AtRestGetPhysicalInteractionLength().
G4bool G4DNAMolecularDissociation::IsApplicable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 83 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 83 of file G4DNAMolecularDissociation.cc
References fVerbose, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), and G4ParticleDefinition::GetParticleType().
G4DNAMolecularDissociation& G4DNAMolecularDissociation::operator= (const G4DNAMolecularDissociation & right) delete
G4VParticleChange * G4DNAMolecularDissociation::PostStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VITRestDiscreteProcess.
Definition at line 337 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 337 of file G4DNAMolecularDissociation.cc
References AtRestDoIt().
G4double G4DNAMolecularDissociation::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VITRestDiscreteProcess.
Definition at line 298 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 298 of file G4DNAMolecularDissociation.cc
void G4DNAMolecularDissociation::SetDisplacer (Species * pSpecies, Displacer * pDisplacer)
Definition at line 284 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 284 of file G4DNAMolecularDissociation.cc
References fDisplacementMap.
Referenced by G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), and G4EmDNAChemistry_option2::ConstructProcess().
void G4DNAMolecularDissociation::SetVerbose (G4int verbose)
Definition at line 307 of file G4DNAMolecularDissociation.cc.
View newest version in sPHENIX GitHub at line 307 of file G4DNAMolecularDissociation.cc
References fVerbose.
Member Data Documentation
G4bool G4DNAMolecularDissociation::fDecayAtFixedTime private
Definition at line 106 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 106 of file G4DNAMolecularDissociation.hh
Referenced by AtRestGetPhysicalInteractionLength(), and G4DNAMolecularDissociation().
DisplacementMap G4DNAMolecularDissociation::fDisplacementMap private
Definition at line 107 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 107 of file G4DNAMolecularDissociation.hh
Referenced by DecayIt(), GetDisplacer(), and SetDisplacer().
G4int G4DNAMolecularDissociation::fVerbose private
Definition at line 108 of file G4DNAMolecularDissociation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4DNAMolecularDissociation.hh
Referenced by DecayIt(), G4DNAMolecularDissociation(), IsApplicable(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNAMolecularDissociation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/src/G4DNAMolecularDissociation.cc