ECCE @ EIC Software: G4INCL::RecombinationChannel Class Reference
G4INCL::RecombinationChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLRecombinationChannel.hh>
Public Member Functions
RecombinationChannel (Particle *p1, Particle *p2)
virtual ~RecombinationChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Attributes
Particle * theNucleon
Particle * theDelta
Detailed Description
Definition at line 55 of file G4INCLRecombinationChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLRecombinationChannel.hh
Constructor & Destructor Documentation
G4INCL::RecombinationChannel::RecombinationChannel (Particle * p1, Particle * p2)
Definition at line 56 of file G4INCLRecombinationChannel.cc.
View newest version in sPHENIX GitHub at line 56 of file G4INCLRecombinationChannel.cc
References G4INCL::Particle::isDelta(), theDelta, and theNucleon.
G4INCL::RecombinationChannel::~RecombinationChannel () virtual
Definition at line 69 of file G4INCLRecombinationChannel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4INCLRecombinationChannel.cc
Member Function Documentation
void G4INCL::RecombinationChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 73 of file G4INCLRecombinationChannel.cc.
View newest version in sPHENIX GitHub at line 73 of file G4INCLRecombinationChannel.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::Particle::adjustEnergyFromMomentum(), G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Particle::getMass(), G4INCL::Particle::getType(), INCL_ERROR, momentum, G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Neutron, G4INCL::Random::normVector(), G4INCL::Proton, G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), theDelta, theNucleon, and G4INCL::KinematicsUtils::totalEnergyInCM().
Member Data Documentation
Particle * G4INCL::RecombinationChannel::theDelta private
Definition at line 64 of file G4INCLRecombinationChannel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4INCLRecombinationChannel.hh
Referenced by fillFinalState(), and RecombinationChannel().
Particle* G4INCL::RecombinationChannel::theNucleon private
Definition at line 64 of file G4INCLRecombinationChannel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4INCLRecombinationChannel.hh
Referenced by fillFinalState(), and RecombinationChannel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLRecombinationChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLRecombinationChannel.cc