ECCE @ EIC Software: G4tgrVolumeAssembly Class Reference
G4tgrVolumeAssembly Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolumeAssembly.hh>
Public Member Functions
G4tgrVolumeAssembly ()
G4tgrVolumeAssembly (const std::vector< G4String > &wl)
~G4tgrVolumeAssembly ()
virtual G4tgrPlace * AddPlace (const std::vector< G4String > &wl)
const G4String & GetComponentName (G4int ii) const
const G4String & GetComponentRM (G4int ii) const
G4ThreeVector GetComponentPos (G4int ii) const
G4int GetNoComponents () const
Public Member Functions inherited from G4tgrVolume
G4tgrVolume ()
G4tgrVolume (const std::vector< G4String > &wl)
G4tgrVolume (const G4tgrVolume &vol)
virtual ~G4tgrVolume ()
G4tgrPlaceDivRep * AddPlaceReplica (const std::vector< G4String > &wl)
G4tgrPlaceParameterisation * AddPlaceParam (const std::vector< G4String > &wl)
void AddVisibility (const std::vector< G4String > &wl)
void AddRGBColour (const std::vector< G4String > &wl)
void AddCheckOverlaps (const std::vector< G4String > &wl)
const G4String & GetName () const
void SetName (const G4String &name)
const G4String & GetType () const
G4tgrSolid * GetSolid () const
const G4String & GetMaterialName () const
const std::vector< G4tgrPlace * > GetPlacements () const
G4bool GetVisibility () const
G4double * GetColour () const
G4double * GetRGBColour () const
G4bool GetCheckOverlaps () const
virtual G4tgrVolume * GetVolume (G4int ii) const
Protected Attributes
std::vector< G4String > theComponentNames
std::vector< G4String > theComponentRMs
std::vector< G4ThreeVector > theComponentPos
Protected Attributes inherited from G4tgrVolume
G4String theName
G4String theType
G4String theMaterialName
G4tgrSolid * theSolid
std::vector< G4tgrPlace * > thePlacements
G4bool theVisibility
G4double * theRGBColour
G4bool theCheckOverlaps
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrVolumeAssembly &obj)
Detailed Description
Definition at line 46 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 46 of file G4tgrVolumeAssembly.hh
Constructor & Destructor Documentation
G4tgrVolumeAssembly::G4tgrVolumeAssembly ()
Definition at line 45 of file G4tgrVolumeAssembly.cc.
View newest version in sPHENIX GitHub at line 45 of file G4tgrVolumeAssembly.cc
G4tgrVolumeAssembly::G4tgrVolumeAssembly (const std::vector< G4String > & wl)
Definition at line 57 of file G4tgrVolumeAssembly.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgrVolumeAssembly.cc
References G4tgrUtils::CheckWLsize(), G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), theComponentNames, theComponentPos, theComponentRMs, G4tgrVolume::theName, G4tgrVolume::theRGBColour, G4tgrVolume::theSolid, G4tgrVolume::theType, G4tgrVolume::theVisibility, and WLSIZE_GE.
G4tgrVolumeAssembly::~G4tgrVolumeAssembly ()
Definition at line 51 of file G4tgrVolumeAssembly.cc.
View newest version in sPHENIX GitHub at line 51 of file G4tgrVolumeAssembly.cc
Member Function Documentation
G4tgrPlace * G4tgrVolumeAssembly::AddPlace (const std::vector< G4String > & wl) virtual
Reimplemented from G4tgrVolume.
Definition at line 102 of file G4tgrVolumeAssembly.cc.
View newest version in sPHENIX GitHub at line 102 of file G4tgrVolumeAssembly.cc
References G4tgrUtils::CheckWLsize(), G4cout, G4endl, G4tgrVolumeMgr::GetInstance(), G4tgrPlace::GetParentName(), G4tgrPlace::GetType(), G4tgrMessenger::GetVerboseLevel(), readPY::pl, G4tgrVolumeMgr::RegisterParentChild(), G4tgrPlace::SetVolume(), G4tgrVolume::theName, G4tgrVolume::thePlacements, and WLSIZE_EQ.
const G4String& G4tgrVolumeAssembly::GetComponentName (G4int ii) const inline
Definition at line 57 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 57 of file G4tgrVolumeAssembly.hh
References theComponentNames.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4ThreeVector G4tgrVolumeAssembly::GetComponentPos (G4int ii) const inline
Definition at line 61 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrVolumeAssembly.hh
References theComponentPos.
Referenced by G4tgbVolume::ConstructG4PhysVol().
const G4String& G4tgrVolumeAssembly::GetComponentRM (G4int ii) const inline
Definition at line 59 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrVolumeAssembly.hh
References theComponentRMs.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4int G4tgrVolumeAssembly::GetNoComponents () const inline
Definition at line 63 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 63 of file G4tgrVolumeAssembly.hh
References theComponentNames.
Referenced by G4tgbVolume::ConstructG4PhysVol().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrVolumeAssembly & obj) friend
Definition at line 130 of file G4tgrVolumeAssembly.cc.
View newest version in sPHENIX GitHub at line 130 of file G4tgrVolumeAssembly.cc
Member Data Documentation
std::vector<G4String> G4tgrVolumeAssembly::theComponentNames protected
Definition at line 70 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgrVolumeAssembly.hh
Referenced by G4tgrVolumeAssembly(), GetComponentName(), GetNoComponents(), and operator<<().
std::vector<G4ThreeVector> G4tgrVolumeAssembly::theComponentPos protected
Definition at line 72 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgrVolumeAssembly.hh
Referenced by G4tgrVolumeAssembly(), GetComponentPos(), and operator<<().
std::vector<G4String> G4tgrVolumeAssembly::theComponentRMs protected
Definition at line 71 of file G4tgrVolumeAssembly.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgrVolumeAssembly.hh
Referenced by G4tgrVolumeAssembly(), GetComponentRM(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolumeAssembly.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrVolumeAssembly.cc