ECCE @ EIC Software: G4BiasingProcessInterface Class Reference
G4BiasingProcessInterface Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BiasingProcessInterface.hh>
Public Member Functions
G4BiasingProcessInterface (G4String name="biasWrapper(0)")
G4BiasingProcessInterface (G4VProcess *wrappedProcess, G4bool wrappedIsAtRest, G4bool wrappedIsAlongStep, G4bool wrappedIsPostStep, G4String useThisName="")
~G4BiasingProcessInterface ()
G4VProcess * GetWrappedProcess () const
G4VBiasingOperator * GetCurrentBiasingOperator () const
G4VBiasingOperator * GetPreviousBiasingOperator () const
G4VBiasingOperation * GetCurrentNonPhysicsBiasingOperation () const
G4VBiasingOperation * GetPreviousNonPhysicsBiasingOperation () const
G4VBiasingOperation * GetCurrentOccurenceBiasingOperation () const
G4VBiasingOperation * GetPreviousOccurenceBiasingOperation () const
G4VBiasingOperation * GetCurrentFinalStateBiasingOperation () const
G4VBiasingOperation * GetPreviousFinalStateBiasingOperation () const
const std::vector< const
G4BiasingProcessInterface * > & GetBiasingProcessInterfaces () const
const std::vector< const
G4BiasingProcessInterface * > & GetPhysicsBiasingProcessInterfaces () const
const std::vector< const
G4BiasingProcessInterface * > & GetNonPhysicsBiasingProcessInterfaces () const
const G4BiasingProcessSharedData * GetSharedData () const
G4bool GetIsFirstPostStepGPILInterface (G4bool physOnly=true) const
G4bool GetIsLastPostStepGPILInterface (G4bool physOnly=true) const
G4bool GetIsFirstPostStepDoItInterface (G4bool physOnly=true) const
G4bool GetIsLastPostStepDoItInterface (G4bool physOnly=true) const
G4bool IsFirstPostStepGPILInterface (G4bool physOnly=true) const
G4bool IsLastPostStepGPILInterface (G4bool physOnly=true) const
G4bool IsFirstPostStepDoItInterface (G4bool physOnly=true) const
G4bool IsLastPostStepDoItInterface (G4bool physOnly=true) const
G4bool GetWrappedProcessIsAtRest () const
G4bool GetWrappedProcessIsAlong () const
G4bool GetWrappedProcessIsPost () const
G4double GetPreviousStepSize () const
G4double GetCurrentMinimumStep () const
G4double GetProposedSafety () const
void SetProposedSafety (G4double sft)
G4double GetPostStepGPIL () const
G4double GetAlongStepGPIL () const
void StartTracking (G4Track *track)
void EndTracking ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &step)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4bool IsApplicable (const G4ParticleDefinition &pd)
virtual void BuildPhysicsTable (const G4ParticleDefinition &pd)
virtual void PreparePhysicsTable (const G4ParticleDefinition &pd)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *pd, const G4String &s, G4bool f)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *pd, const G4String &s, G4bool f)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
virtual void SetMasterProcess (G4VProcess *masterP)
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &pd)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &pd)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
const G4VProcess * GetMasterProcess () const
Static Public Member Functions
static const
G4BiasingProcessSharedData * GetSharedData (const G4ProcessManager *)
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Private Member Functions
void SetUpFirstLastFlags ()
void ResetForUnbiasedTracking ()
void ReorderBiasingVectorAsGPIL ()
G4int IdxFirstLast (G4int firstLast, G4int GPILDoIt, G4int physAll) const
void InvokeWrappedProcessPostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
Private Attributes
G4Track * fCurrentTrack
G4double fPreviousStepSize
G4double fCurrentMinimumStep
G4double fProposedSafety
G4VBiasingOperation * fOccurenceBiasingOperation
G4VBiasingOperation * fFinalStateBiasingOperation
G4VBiasingOperation * fNonPhysicsBiasingOperation
G4VBiasingOperation * fPreviousOccurenceBiasingOperation
G4VBiasingOperation * fPreviousFinalStateBiasingOperation
G4VBiasingOperation * fPreviousNonPhysicsBiasingOperation
G4bool fResetWrappedProcessInteractionLength
G4VProcess * fWrappedProcess
const G4bool fIsPhysicsBasedBiasing
const G4bool fWrappedProcessIsAtRest
const G4bool fWrappedProcessIsAlong
const G4bool fWrappedProcessIsPost
G4double fWrappedProcessPostStepGPIL
G4double fBiasingPostStepGPIL
G4double fWrappedProcessInteractionLength
G4ForceCondition fWrappedProcessForceCondition
G4ForceCondition fBiasingForceCondition
G4double fWrappedProcessAlongStepGPIL
G4double fBiasingAlongStepGPIL
G4GPILSelection fWrappedProcessGPILSelection
G4GPILSelection fBiasingGPILSelection
const G4VBiasingInteractionLaw * fBiasingInteractionLaw
const G4VBiasingInteractionLaw * fPreviousBiasingInteractionLaw
G4InteractionLawPhysical * fPhysicalInteractionLaw
G4ParticleChangeForOccurenceBiasing * fOccurenceBiasingParticleChange
G4ParticleChangeForNothing * fDummyParticleChange
G4bool fFirstLastFlags [8]
G4bool fIamFirstGPIL
const G4ProcessManager * fProcessManager
G4BiasingProcessSharedData * fSharedData
Static Private Attributes
static G4Cache< G4bool > fResetInteractionLaws
static G4Cache< G4bool > fCommonStart
static G4Cache< G4bool > fCommonEnd
static G4Cache< G4bool > fDoCommonConfigure
Additional Inherited Members
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 69 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BiasingProcessInterface.hh
Constructor & Destructor Documentation
G4BiasingProcessInterface::G4BiasingProcessInterface (G4String name = "biasWrapper(0)")
Definition at line 42 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 42 of file G4BiasingProcessInterface.cc
References fCommonEnd, fCommonStart, fDoCommonConfigure, fFirstLastFlags, fResetInteractionLaws, and G4Cache< VALTYPE >::Put().
G4BiasingProcessInterface::G4BiasingProcessInterface (G4VProcess * wrappedProcess, G4bool wrappedIsAtRest, G4bool wrappedIsAlongStep, G4bool wrappedIsPostStep, G4String useThisName = "")
Definition at line 80 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 80 of file G4BiasingProcessInterface.cc
References fCommonEnd, fCommonStart, fDoCommonConfigure, fDummyParticleChange, fFirstLastFlags, fOccurenceBiasingParticleChange, fPhysicalInteractionLaw, fResetInteractionLaws, fWrappedProcess, G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), G4Cache< VALTYPE >::Put(), and G4VProcess::SetProcessSubType().
G4BiasingProcessInterface::~G4BiasingProcessInterface ()
Definition at line 130 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 130 of file G4BiasingProcessInterface.cc
References fDummyParticleChange, fOccurenceBiasingParticleChange, and fPhysicalInteractionLaw.
Member Function Documentation
G4VParticleChange * G4BiasingProcessInterface::AlongStepDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 648 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 648 of file G4BiasingProcessInterface.cc
References G4VBiasingOperation::AlongMoveBy(), G4VProcess::AlongStepDoIt(), G4InteractionLawPhysical::ComputeNonInteractionProbabilityAt(), fBiasingInteractionLaw, G4BiasingProcessSharedData::fCurrentBiasingOperator, fDummyParticleChange, fOccurenceBiasingOperation, fOccurenceBiasingParticleChange, fPhysicalInteractionLaw, fSharedData, fWrappedProcess, fWrappedProcessIsAlong, G4endl, G4Exception(), G4VBiasingInteractionLaw::GetName(), G4Step::GetStepLength(), G4Track::GetTrackStatus(), G4ParticleChangeForNothing::Initialize(), JustWarning, G4VParticleChange::ProposeTrackStatus(), G4ParticleChangeForOccurenceBiasing::SetOccurenceWeightForNonInteraction(), and G4ParticleChangeForOccurenceBiasing::SetWrappedParticleChange().
G4double G4BiasingProcessInterface::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 569 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 569 of file G4BiasingProcessInterface.cc
References G4VProcess::AlongStepGetPhysicalInteractionLength(), DBL_MAX, fBiasingAlongStepGPIL, fBiasingGPILSelection, G4BiasingProcessSharedData::fCurrentBiasingOperator, fCurrentMinimumStep, fIsPhysicsBasedBiasing, fOccurenceBiasingOperation, fProposedSafety, fSharedData, fWrappedProcess, fWrappedProcessAlongStepGPIL, fWrappedProcessGPILSelection, fWrappedProcessIsAlong, NotCandidateForSelection, G4VBiasingOperation::ProposeAlongStepLimit(), and G4VBiasingOperation::ProposeGPILSelection().
G4VParticleChange * G4BiasingProcessInterface::AtRestDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 711 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 711 of file G4BiasingProcessInterface.cc
References G4VProcess::AtRestDoIt(), and fWrappedProcess.
G4double G4BiasingProcessInterface::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 706 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 706 of file G4BiasingProcessInterface.cc
References G4VProcess::AtRestGetPhysicalInteractionLength(), and fWrappedProcess.
void G4BiasingProcessInterface::BuildPhysicsTable (const G4ParticleDefinition & pd) virtual
Reimplemented from G4VProcess.
Definition at line 741 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 741 of file G4BiasingProcessInterface.cc
References G4VProcess::BuildPhysicsTable(), demo::Configure(), fDoCommonConfigure, fIamFirstGPIL, fWrappedProcess, G4Cache< VALTYPE >::Get(), G4VBiasingOperator::GetBiasingOperators(), G4Cache< VALTYPE >::Put(), and ReorderBiasingVectorAsGPIL().
void G4BiasingProcessInterface::BuildWorkerPhysicsTable (const G4ParticleDefinition & pd) virtual
Reimplemented from G4VProcess.
Definition at line 838 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 838 of file G4BiasingProcessInterface.cc
References G4VProcess::BuildWorkerPhysicsTable(), fDoCommonConfigure, fIamFirstGPIL, fWrappedProcess, G4Cache< VALTYPE >::Get(), G4VBiasingOperator::GetBiasingOperators(), G4Cache< VALTYPE >::Put(), and ReorderBiasingVectorAsGPIL().
void G4BiasingProcessInterface::EndTracking () virtual
Reimplemented from G4VProcess.
Definition at line 184 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 184 of file G4BiasingProcessInterface.cc
References G4VProcess::EndTracking(), fBiasingInteractionLaw, fCommonEnd, fCommonStart, G4BiasingProcessSharedData::fCurrentBiasingOperator, fCurrentTrack, fIsPhysicsBasedBiasing, fSharedData, fWrappedProcess, G4Cache< VALTYPE >::Get(), G4VBiasingOperator::GetBiasingOperators(), and G4Cache< VALTYPE >::Put().
G4double G4BiasingProcessInterface::GetAlongStepGPIL () const inline
Definition at line 153 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 153 of file G4BiasingProcessInterface.hh
References fWrappedProcessAlongStepGPIL.
Referenced by G4BOptnForceCommonTruncatedExp::ApplyFinalStateBiasing().
const std::vector< const G4BiasingProcessInterface* >& G4BiasingProcessInterface::GetBiasingProcessInterfaces () const inline
Definition at line 106 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 106 of file G4BiasingProcessInterface.hh
References fSharedData.
G4VBiasingOperator* G4BiasingProcessInterface::GetCurrentBiasingOperator () const inline
Definition at line 92 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BiasingProcessInterface.hh
References fSharedData.
G4VBiasingOperation* G4BiasingProcessInterface::GetCurrentFinalStateBiasingOperation () const inline
Definition at line 99 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 99 of file G4BiasingProcessInterface.hh
References fFinalStateBiasingOperation.
G4double G4BiasingProcessInterface::GetCurrentMinimumStep () const inline
Definition at line 148 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 148 of file G4BiasingProcessInterface.hh
References fCurrentMinimumStep.
G4VBiasingOperation* G4BiasingProcessInterface::GetCurrentNonPhysicsBiasingOperation () const inline
Definition at line 95 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 95 of file G4BiasingProcessInterface.hh
References fNonPhysicsBiasingOperation.
G4VBiasingOperation* G4BiasingProcessInterface::GetCurrentOccurenceBiasingOperation () const inline
Definition at line 97 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 97 of file G4BiasingProcessInterface.hh
References fOccurenceBiasingOperation.
Referenced by G4BOptrForceCollision::ProposeFinalStateBiasingOperation().
G4bool G4BiasingProcessInterface::GetIsFirstPostStepDoItInterface (G4bool physOnly = true) const
Definition at line 902 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 902 of file G4BiasingProcessInterface.cc
References fFirstLastFlags, and IdxFirstLast().
Referenced by G4BOptnForceFreeFlight::ApplyFinalStateBiasing().
G4bool G4BiasingProcessInterface::GetIsFirstPostStepGPILInterface (G4bool physOnly = true) const
Definition at line 888 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 888 of file G4BiasingProcessInterface.cc
References fFirstLastFlags, and IdxFirstLast().
Referenced by SetUpFirstLastFlags().
G4bool G4BiasingProcessInterface::GetIsLastPostStepDoItInterface (G4bool physOnly = true) const
Definition at line 909 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 909 of file G4BiasingProcessInterface.cc
References fFirstLastFlags, and IdxFirstLast().
G4bool G4BiasingProcessInterface::GetIsLastPostStepGPILInterface (G4bool physOnly = true) const
Definition at line 895 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 895 of file G4BiasingProcessInterface.cc
References fFirstLastFlags, and IdxFirstLast().
const std::vector< const G4BiasingProcessInterface* >& G4BiasingProcessInterface::GetNonPhysicsBiasingProcessInterfaces () const inline
Definition at line 110 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 110 of file G4BiasingProcessInterface.hh
References G4BiasingProcessSharedData::fPublicNonPhysicsBiasingProcessInterfaces, and fSharedData.
const std::vector< const G4BiasingProcessInterface* >& G4BiasingProcessInterface::GetPhysicsBiasingProcessInterfaces () const inline
Definition at line 108 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 108 of file G4BiasingProcessInterface.hh
References fSharedData.
G4double G4BiasingProcessInterface::GetPostStepGPIL () const inline
Definition at line 152 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 152 of file G4BiasingProcessInterface.hh
References fBiasingPostStepGPIL.
Referenced by G4BOptnForceCommonTruncatedExp::ApplyFinalStateBiasing().
G4VBiasingOperator* G4BiasingProcessInterface::GetPreviousBiasingOperator () const inline
Definition at line 93 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BiasingProcessInterface.hh
References G4BiasingProcessSharedData::fPreviousBiasingOperator, and fSharedData.
G4VBiasingOperation* G4BiasingProcessInterface::GetPreviousFinalStateBiasingOperation () const inline
Definition at line 100 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 100 of file G4BiasingProcessInterface.hh
References fPreviousFinalStateBiasingOperation.
G4VBiasingOperation* G4BiasingProcessInterface::GetPreviousNonPhysicsBiasingOperation () const inline
Definition at line 96 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 96 of file G4BiasingProcessInterface.hh
References fPreviousNonPhysicsBiasingOperation.
G4VBiasingOperation* G4BiasingProcessInterface::GetPreviousOccurenceBiasingOperation () const inline
Definition at line 98 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 98 of file G4BiasingProcessInterface.hh
References fPreviousOccurenceBiasingOperation.
Referenced by GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
G4double G4BiasingProcessInterface::GetPreviousStepSize () const inline
Definition at line 147 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 147 of file G4BiasingProcessInterface.hh
References fPreviousStepSize.
Referenced by GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
const G4ProcessManager * G4BiasingProcessInterface::GetProcessManager () virtual
Reimplemented from G4VProcess.
Definition at line 831 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 831 of file G4BiasingProcessInterface.cc
References fWrappedProcess, and G4VProcess::GetProcessManager().
G4double G4BiasingProcessInterface::GetProposedSafety () const inline
Definition at line 149 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 149 of file G4BiasingProcessInterface.hh
References fProposedSafety.
const G4BiasingProcessSharedData* G4BiasingProcessInterface::GetSharedData () const inline
Definition at line 114 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 114 of file G4BiasingProcessInterface.hh
References fSharedData.
Referenced by G4BOptrForceCollision::ConfigureForWorker(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), GB01BOptrChangeCrossSection::StartRun(), GB05BOptrSplitAndKillByCrossSection::StartRun(), G4ChannelingOptrChangeCrossSection::StartRun(), and GB06BOptrSplitAndKillByImportance::StartRun().
const G4BiasingProcessSharedData * G4BiasingProcessInterface::GetSharedData (const G4ProcessManager * mgr) static
Definition at line 138 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 138 of file G4BiasingProcessInterface.cc
References G4MapCache< KEYTYPE, VALTYPE >::Find(), and G4BiasingProcessSharedData::fSharedDataMap.
G4VProcess* G4BiasingProcessInterface::GetWrappedProcess () const inline
Definition at line 84 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 84 of file G4BiasingProcessInterface.hh
References fWrappedProcess.
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4BOptnForceCommonTruncatedExp::ApplyFinalStateBiasing(), G4BOptrForceCollision::ConfigureForWorker(), BiasingOperator::ProposeFinalStateBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4BOptnForceCommonTruncatedExp::ProvideOccurenceBiasingInteractionLaw(), SetMasterProcess(), GB01BOptrChangeCrossSection::StartRun(), GB05BOptrSplitAndKillByCrossSection::StartRun(), and G4ChannelingOptrChangeCrossSection::StartRun().
G4bool G4BiasingProcessInterface::GetWrappedProcessIsAlong () const inline
Definition at line 142 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 142 of file G4BiasingProcessInterface.hh
References fWrappedProcessIsAlong.
G4bool G4BiasingProcessInterface::GetWrappedProcessIsAtRest () const inline
Definition at line 141 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 141 of file G4BiasingProcessInterface.hh
References fWrappedProcessIsAtRest.
G4bool G4BiasingProcessInterface::GetWrappedProcessIsPost () const inline
Definition at line 143 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 143 of file G4BiasingProcessInterface.hh
References fWrappedProcessIsPost.
G4int G4BiasingProcessInterface::IdxFirstLast (G4int firstLast, G4int GPILDoIt, G4int physAll) const inline private
Definition at line 248 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 248 of file G4BiasingProcessInterface.hh
Referenced by GetIsFirstPostStepDoItInterface(), GetIsFirstPostStepGPILInterface(), GetIsLastPostStepDoItInterface(), GetIsLastPostStepGPILInterface(), and SetUpFirstLastFlags().
void G4BiasingProcessInterface::InvokeWrappedProcessPostStepGPIL (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) private
Definition at line 1049 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 1049 of file G4BiasingProcessInterface.cc
References condition(), fResetWrappedProcessInteractionLength, fWrappedProcess, fWrappedProcessForceCondition, fWrappedProcessInteractionLength, fWrappedProcessPostStepGPIL, G4VProcess::GetCurrentInteractionLength(), G4VProcess::PostStepGetPhysicalInteractionLength(), and G4VProcess::ResetNumberOfInteractionLengthLeft().
G4bool G4BiasingProcessInterface::IsApplicable (const G4ParticleDefinition & pd) virtual
Reimplemented from G4VProcess.
Definition at line 718 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 718 of file G4BiasingProcessInterface.cc
References fWrappedProcess, and G4VProcess::IsApplicable().
G4bool G4BiasingProcessInterface::IsFirstPostStepDoItInterface (G4bool physOnly = true) const
Definition at line 970 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 970 of file G4BiasingProcessInterface.cc
References G4BiasingProcessSharedData::fBiasingProcessInterfaces, fProcessManager, fSharedData, G4ProcessManager::GetPostStepProcessVector(), G4ProcessVector::size(), and typeDoIt.
Referenced by SetUpFirstLastFlags().
G4bool G4BiasingProcessInterface::IsFirstPostStepGPILInterface (G4bool physOnly = true) const
Definition at line 916 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 916 of file G4BiasingProcessInterface.cc
References G4BiasingProcessSharedData::fBiasingProcessInterfaces, fProcessManager, fSharedData, G4ProcessManager::GetPostStepProcessVector(), G4ProcessVector::size(), and typeGPIL.
Referenced by SetUpFirstLastFlags().
G4bool G4BiasingProcessInterface::IsLastPostStepDoItInterface (G4bool physOnly = true) const
Definition at line 997 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 997 of file G4BiasingProcessInterface.cc
References G4BiasingProcessSharedData::fBiasingProcessInterfaces, fProcessManager, fSharedData, G4ProcessManager::GetPostStepProcessVector(), G4ProcessVector::size(), and typeDoIt.
Referenced by SetUpFirstLastFlags().
G4bool G4BiasingProcessInterface::IsLastPostStepGPILInterface (G4bool physOnly = true) const
Definition at line 943 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 943 of file G4BiasingProcessInterface.cc
References G4BiasingProcessSharedData::fBiasingProcessInterfaces, fProcessManager, fSharedData, G4ProcessManager::GetPostStepProcessVector(), G4ProcessVector::size(), and typeGPIL.
Referenced by SetUpFirstLastFlags().
G4VParticleChange * G4BiasingProcessInterface::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 447 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 447 of file G4BiasingProcessInterface.cc
References G4VBiasingOperation::ApplyFinalStateBiasing(), BAC_FinalState, BAC_None, BAC_NonPhysics, G4InteractionLawPhysical::ComputeEffectiveCrossSectionAt(), G4VBiasingInteractionLaw::ComputeEffectiveCrossSectionAt(), fBiasingInteractionLaw, G4BiasingProcessSharedData::fCurrentBiasingOperator, fFinalStateBiasingOperation, fIsPhysicsBasedBiasing, fNonPhysicsBiasingOperation, fOccurenceBiasingOperation, fOccurenceBiasingParticleChange, fPhysicalInteractionLaw, fSharedData, fWrappedProcess, G4endl, G4Exception(), G4VBiasingOperation::GenerateBiasingFinalState(), G4Step::GetStepLength(), G4VParticleChange::GetTrackStatus(), G4VBiasingInteractionLaw::IsEffectiveCrossSectionInfinite(), G4VBiasingInteractionLaw::IsSingular(), JustWarning, G4VProcess::PostStepDoIt(), G4VParticleChange::ProposeTrackStatus(), G4ParticleChangeForOccurenceBiasing::SetOccurenceWeightForInteraction(), G4VParticleChange::SetSecondaryWeightByProcess(), G4ParticleChangeForOccurenceBiasing::SetWrappedParticleChange(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
G4double G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 205 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 205 of file G4BiasingProcessInterface.cc
References DBL_MAX, G4VBiasingOperation::DistanceToApplyOperation(), fBiasingAlongStepGPIL, fBiasingForceCondition, fBiasingGPILSelection, fBiasingInteractionLaw, fBiasingPostStepGPIL, G4BiasingProcessSharedData::fCurrentBiasingOperator, fFinalStateBiasingOperation, fGeomBoundary, fIamFirstGPIL, G4BiasingProcessSharedData::fIsNewOperator, fIsPhysicsBasedBiasing, G4BiasingProcessSharedData::fLeavingPreviousOperator, G4BiasingProcessSharedData::fMassGeometryOperator, fNonPhysicsBiasingOperation, fOccurenceBiasingOperation, G4BiasingProcessSharedData::fParallelGeometriesLimiterProcess, G4BiasingProcessSharedData::fParallelGeometryOperator, fPhysicalInteractionLaw, G4BiasingProcessSharedData::fPhysicsBiasingProcessInterfaces, fPreviousBiasingInteractionLaw, G4BiasingProcessSharedData::fPreviousBiasingOperator, fPreviousFinalStateBiasingOperation, fPreviousNonPhysicsBiasingOperation, fPreviousOccurenceBiasingOperation, fPreviousStepSize, fResetWrappedProcessInteractionLength, fSharedData, fWrappedProcess, fWrappedProcessAlongStepGPIL, fWrappedProcessForceCondition, fWrappedProcessGPILSelection, fWrappedProcessInteractionLength, fWrappedProcessPostStepGPIL, G4endl, G4Exception(), G4VBiasingOperator::GetBiasingOperator(), G4Track::GetCurrentStepNumber(), G4ParallelGeometriesLimiterProcess::GetCurrentVolumes(), G4VPhysicalVolume::GetLogicalVolume(), G4VBiasingOperator::GetName(), G4Step::GetPreStepPoint(), G4VBiasingInteractionLaw::GetSampledInteractionLength(), G4Track::GetStep(), G4StepPoint::GetStepStatus(), G4Track::GetVolume(), G4ParallelGeometriesLimiterProcess::GetWasLimiting(), JustWarning, NotCandidateForSelection, NotForced, G4VProcess::PostStepGetPhysicalInteractionLength(), G4VBiasingOperation::ProvideOccurenceBiasingInteractionLaw(), ResetForUnbiasedTracking(), G4VProcess::ResetNumberOfInteractionLengthLeft(), and G4InteractionLawPhysical::SetPhysicalCrossSection().
void G4BiasingProcessInterface::PreparePhysicsTable (const G4ParticleDefinition & pd) virtual
Reimplemented from G4VProcess.
Definition at line 773 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 773 of file G4BiasingProcessInterface.cc
References fWrappedProcess, G4VProcess::PreparePhysicsTable(), and SetUpFirstLastFlags().
void G4BiasingProcessInterface::PrepareWorkerPhysicsTable (const G4ParticleDefinition & pd) virtual
Reimplemented from G4VProcess.
Definition at line 868 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 868 of file G4BiasingProcessInterface.cc
References fWrappedProcess, G4VProcess::PrepareWorkerPhysicsTable(), and SetUpFirstLastFlags().
void G4BiasingProcessInterface::ReorderBiasingVectorAsGPIL () private
Definition at line 1075 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 1075 of file G4BiasingProcessInterface.cc
References clear(), G4BiasingProcessSharedData::fBiasingProcessInterfaces, fIsPhysicsBasedBiasing, fProcessManager, fSharedData, G4ProcessManager::GetPostStepProcessVector(), G4ProcessVector::size(), and typeGPIL.
Referenced by BuildPhysicsTable(), and BuildWorkerPhysicsTable().
void G4BiasingProcessInterface::ResetForUnbiasedTracking () private
Definition at line 1040 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 1040 of file G4BiasingProcessInterface.cc
References fBiasingInteractionLaw, fFinalStateBiasingOperation, fNonPhysicsBiasingOperation, and fOccurenceBiasingOperation.
Referenced by PostStepGetPhysicalInteractionLength().
void G4BiasingProcessInterface::ResetNumberOfInteractionLengthLeft () virtual
Reimplemented from G4VProcess.
Definition at line 882 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 882 of file G4BiasingProcessInterface.cc
References fWrappedProcess, and G4VProcess::ResetNumberOfInteractionLengthLeft().
G4bool G4BiasingProcessInterface::RetrievePhysicsTable (const G4ParticleDefinition * pd, const G4String & s, G4bool f) virtual
Reimplemented from G4VProcess.
Definition at line 794 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 794 of file G4BiasingProcessInterface.cc
References fWrappedProcess, and G4VProcess::RetrievePhysicsTable().
void G4BiasingProcessInterface::SetMasterProcess (G4VProcess * masterP) virtual
Reimplemented from G4VProcess.
Definition at line 725 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 725 of file G4BiasingProcessInterface.cc
References fWrappedProcess, G4VProcess::GetMasterProcess(), GetWrappedProcess(), and G4VProcess::SetMasterProcess().
void G4BiasingProcessInterface::SetProcessManager (const G4ProcessManager * mgr) virtual
Reimplemented from G4VProcess.
Definition at line 801 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 801 of file G4BiasingProcessInterface.cc
References fIsPhysicsBasedBiasing, fProcessManager, fSharedData, G4BiasingProcessSharedData::fSharedDataMap, fWrappedProcess, and G4VProcess::SetProcessManager().
void G4BiasingProcessInterface::SetProposedSafety (G4double sft) inline
Definition at line 150 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 150 of file G4BiasingProcessInterface.hh
References fProposedSafety.
void G4BiasingProcessInterface::SetUpFirstLastFlags () private
Definition at line 1024 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 1024 of file G4BiasingProcessInterface.cc
References fFirstLastFlags, fIamFirstGPIL, GetIsFirstPostStepGPILInterface(), IdxFirstLast(), IsFirstPostStepDoItInterface(), IsFirstPostStepGPILInterface(), IsLastPostStepDoItInterface(), and IsLastPostStepGPILInterface().
Referenced by PreparePhysicsTable(), and PrepareWorkerPhysicsTable().
void G4BiasingProcessInterface::StartTracking (G4Track * track) virtual
Reimplemented from G4VProcess.
Definition at line 150 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 150 of file G4BiasingProcessInterface.cc
References fBiasingInteractionLaw, fCommonEnd, fCommonStart, fCurrentTrack, fFinalStateBiasingOperation, fIsPhysicsBasedBiasing, fNonPhysicsBiasingOperation, fOccurenceBiasingOperation, fPreviousBiasingInteractionLaw, G4BiasingProcessSharedData::fPreviousBiasingOperator, fPreviousFinalStateBiasingOperation, fPreviousNonPhysicsBiasingOperation, fPreviousOccurenceBiasingOperation, fPreviousStepSize, fResetWrappedProcessInteractionLength, fSharedData, fWrappedProcess, G4Cache< VALTYPE >::Get(), G4VBiasingOperator::GetBiasingOperators(), G4Cache< VALTYPE >::Put(), G4VProcess::StartTracking(), and track.
G4bool G4BiasingProcessInterface::StorePhysicsTable (const G4ParticleDefinition * pd, const G4String & s, G4bool f) virtual
Reimplemented from G4VProcess.
Definition at line 787 of file G4BiasingProcessInterface.cc.
View newest version in sPHENIX GitHub at line 787 of file G4BiasingProcessInterface.cc
References fWrappedProcess, and G4VProcess::StorePhysicsTable().
Member Data Documentation
G4double G4BiasingProcessInterface::fBiasingAlongStepGPIL private
Definition at line 238 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 238 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and PostStepGetPhysicalInteractionLength().
G4ForceCondition G4BiasingProcessInterface::fBiasingForceCondition private
Definition at line 236 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 236 of file G4BiasingProcessInterface.hh
Referenced by PostStepGetPhysicalInteractionLength().
G4GPILSelection G4BiasingProcessInterface::fBiasingGPILSelection private
Definition at line 240 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 240 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and PostStepGetPhysicalInteractionLength().
const G4VBiasingInteractionLaw* G4BiasingProcessInterface::fBiasingInteractionLaw private
Definition at line 242 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 242 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), EndTracking(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), ResetForUnbiasedTracking(), and StartTracking().
G4double G4BiasingProcessInterface::fBiasingPostStepGPIL private
Definition at line 233 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 233 of file G4BiasingProcessInterface.hh
Referenced by GetPostStepGPIL(), and PostStepGetPhysicalInteractionLength().
G4Cache< G4bool > G4BiasingProcessInterface::fCommonEnd static private
Definition at line 267 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 267 of file G4BiasingProcessInterface.hh
Referenced by EndTracking(), G4BiasingProcessInterface(), and StartTracking().
G4Cache< G4bool > G4BiasingProcessInterface::fCommonStart static private
Definition at line 266 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 266 of file G4BiasingProcessInterface.hh
Referenced by EndTracking(), G4BiasingProcessInterface(), and StartTracking().
G4double G4BiasingProcessInterface::fCurrentMinimumStep private
Definition at line 213 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 213 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and GetCurrentMinimumStep().
G4Track* G4BiasingProcessInterface::fCurrentTrack private
Definition at line 211 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 211 of file G4BiasingProcessInterface.hh
Referenced by EndTracking(), and StartTracking().
G4Cache< G4bool > G4BiasingProcessInterface::fDoCommonConfigure static private
Definition at line 268 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 268 of file G4BiasingProcessInterface.hh
Referenced by BuildPhysicsTable(), BuildWorkerPhysicsTable(), and G4BiasingProcessInterface().
G4ParticleChangeForNothing* G4BiasingProcessInterface::fDummyParticleChange private
Definition at line 246 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 246 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), G4BiasingProcessInterface(), and ~G4BiasingProcessInterface().
G4VBiasingOperation* G4BiasingProcessInterface::fFinalStateBiasingOperation private
Definition at line 217 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 217 of file G4BiasingProcessInterface.hh
Referenced by GetCurrentFinalStateBiasingOperation(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), ResetForUnbiasedTracking(), and StartTracking().
G4bool G4BiasingProcessInterface::fFirstLastFlags[8] private
Definition at line 247 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 247 of file G4BiasingProcessInterface.hh
Referenced by G4BiasingProcessInterface(), GetIsFirstPostStepDoItInterface(), GetIsFirstPostStepGPILInterface(), GetIsLastPostStepDoItInterface(), GetIsLastPostStepGPILInterface(), and SetUpFirstLastFlags().
G4bool G4BiasingProcessInterface::fIamFirstGPIL private
Definition at line 261 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 261 of file G4BiasingProcessInterface.hh
Referenced by BuildPhysicsTable(), BuildWorkerPhysicsTable(), PostStepGetPhysicalInteractionLength(), and SetUpFirstLastFlags().
const G4bool G4BiasingProcessInterface::fIsPhysicsBasedBiasing private
Definition at line 226 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 226 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), EndTracking(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), ReorderBiasingVectorAsGPIL(), SetProcessManager(), and StartTracking().
G4VBiasingOperation* G4BiasingProcessInterface::fNonPhysicsBiasingOperation private
Definition at line 218 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 218 of file G4BiasingProcessInterface.hh
Referenced by GetCurrentNonPhysicsBiasingOperation(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), ResetForUnbiasedTracking(), and StartTracking().
G4VBiasingOperation* G4BiasingProcessInterface::fOccurenceBiasingOperation private
Definition at line 216 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 216 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), GetCurrentOccurenceBiasingOperation(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), ResetForUnbiasedTracking(), and StartTracking().
G4ParticleChangeForOccurenceBiasing* G4BiasingProcessInterface::fOccurenceBiasingParticleChange private
Definition at line 245 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 245 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), G4BiasingProcessInterface(), PostStepDoIt(), and ~G4BiasingProcessInterface().
G4InteractionLawPhysical* G4BiasingProcessInterface::fPhysicalInteractionLaw private
Definition at line 244 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 244 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), G4BiasingProcessInterface(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), and ~G4BiasingProcessInterface().
const G4VBiasingInteractionLaw* G4BiasingProcessInterface::fPreviousBiasingInteractionLaw private
Definition at line 243 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 243 of file G4BiasingProcessInterface.hh
Referenced by PostStepGetPhysicalInteractionLength(), and StartTracking().
G4VBiasingOperation* G4BiasingProcessInterface::fPreviousFinalStateBiasingOperation private
Definition at line 220 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 220 of file G4BiasingProcessInterface.hh
Referenced by GetPreviousFinalStateBiasingOperation(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4VBiasingOperation* G4BiasingProcessInterface::fPreviousNonPhysicsBiasingOperation private
Definition at line 221 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 221 of file G4BiasingProcessInterface.hh
Referenced by GetPreviousNonPhysicsBiasingOperation(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4VBiasingOperation* G4BiasingProcessInterface::fPreviousOccurenceBiasingOperation private
Definition at line 219 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 219 of file G4BiasingProcessInterface.hh
Referenced by GetPreviousOccurenceBiasingOperation(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4double G4BiasingProcessInterface::fPreviousStepSize private
Definition at line 212 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 212 of file G4BiasingProcessInterface.hh
Referenced by GetPreviousStepSize(), PostStepGetPhysicalInteractionLength(), and StartTracking().
const G4ProcessManager* G4BiasingProcessInterface::fProcessManager private
Definition at line 270 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 270 of file G4BiasingProcessInterface.hh
Referenced by IsFirstPostStepDoItInterface(), IsFirstPostStepGPILInterface(), IsLastPostStepDoItInterface(), IsLastPostStepGPILInterface(), ReorderBiasingVectorAsGPIL(), and SetProcessManager().
G4double G4BiasingProcessInterface::fProposedSafety private
Definition at line 214 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 214 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), GetProposedSafety(), and SetProposedSafety().
G4Cache< G4bool > G4BiasingProcessInterface::fResetInteractionLaws static private
Definition at line 265 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 265 of file G4BiasingProcessInterface.hh
Referenced by G4BiasingProcessInterface().
G4bool G4BiasingProcessInterface::fResetWrappedProcessInteractionLength private
Definition at line 223 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 223 of file G4BiasingProcessInterface.hh
Referenced by InvokeWrappedProcessPostStepGPIL(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4BiasingProcessSharedData* G4BiasingProcessInterface::fSharedData private
Definition at line 274 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 274 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), EndTracking(), GetBiasingProcessInterfaces(), GetCurrentBiasingOperator(), GetNonPhysicsBiasingProcessInterfaces(), GetPhysicsBiasingProcessInterfaces(), GetPreviousBiasingOperator(), GetSharedData(), IsFirstPostStepDoItInterface(), IsFirstPostStepGPILInterface(), IsLastPostStepDoItInterface(), IsLastPostStepGPILInterface(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), ReorderBiasingVectorAsGPIL(), SetProcessManager(), and StartTracking().
G4VProcess* G4BiasingProcessInterface::fWrappedProcess private
Definition at line 225 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 225 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), AtRestDoIt(), AtRestGetPhysicalInteractionLength(), BuildPhysicsTable(), BuildWorkerPhysicsTable(), EndTracking(), G4BiasingProcessInterface(), GetProcessManager(), GetWrappedProcess(), InvokeWrappedProcessPostStepGPIL(), IsApplicable(), PostStepDoIt(), PostStepGetPhysicalInteractionLength(), PreparePhysicsTable(), PrepareWorkerPhysicsTable(), ResetNumberOfInteractionLengthLeft(), RetrievePhysicsTable(), SetMasterProcess(), SetProcessManager(), StartTracking(), and StorePhysicsTable().
G4double G4BiasingProcessInterface::fWrappedProcessAlongStepGPIL private
Definition at line 237 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 237 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), GetAlongStepGPIL(), and PostStepGetPhysicalInteractionLength().
G4ForceCondition G4BiasingProcessInterface::fWrappedProcessForceCondition private
Definition at line 235 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 235 of file G4BiasingProcessInterface.hh
Referenced by InvokeWrappedProcessPostStepGPIL(), and PostStepGetPhysicalInteractionLength().
G4GPILSelection G4BiasingProcessInterface::fWrappedProcessGPILSelection private
Definition at line 239 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 239 of file G4BiasingProcessInterface.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and PostStepGetPhysicalInteractionLength().
G4double G4BiasingProcessInterface::fWrappedProcessInteractionLength private
Definition at line 234 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 234 of file G4BiasingProcessInterface.hh
Referenced by InvokeWrappedProcessPostStepGPIL(), and PostStepGetPhysicalInteractionLength().
const G4bool G4BiasingProcessInterface::fWrappedProcessIsAlong private
Definition at line 228 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 228 of file G4BiasingProcessInterface.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and GetWrappedProcessIsAlong().
const G4bool G4BiasingProcessInterface::fWrappedProcessIsAtRest private
Definition at line 227 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 227 of file G4BiasingProcessInterface.hh
Referenced by GetWrappedProcessIsAtRest().
const G4bool G4BiasingProcessInterface::fWrappedProcessIsPost private
Definition at line 229 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 229 of file G4BiasingProcessInterface.hh
Referenced by GetWrappedProcessIsPost().
G4double G4BiasingProcessInterface::fWrappedProcessPostStepGPIL private
Definition at line 232 of file G4BiasingProcessInterface.hh.
View newest version in sPHENIX GitHub at line 232 of file G4BiasingProcessInterface.hh
Referenced by InvokeWrappedProcessPostStepGPIL(), and PostStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BiasingProcessInterface.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BiasingProcessInterface.cc