ECCE @ EIC Software: G4LowEnergyBremsstrahlung Class Reference
G4LowEnergyBremsstrahlung Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyBremsstrahlung.hh>
Public Member Functions
G4LowEnergyBremsstrahlung (const G4String &processName="LowEnBrem")
~G4LowEnergyBremsstrahlung ()
G4bool IsApplicable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &particleType)
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
void SetCutForLowEnSecPhotons (G4double cut)
void SetAngularGenerator (G4RDVBremAngularDistribution *distribution)
void SetAngularGenerator (const G4String &name)
void PrintInfoDefinition ()
Public Member Functions inherited from G4eLowEnergyLoss
G4eLowEnergyLoss (const G4String &)
~G4eLowEnergyLoss ()
void BuildDEDXTable (const G4ParticleDefinition &aParticleType)
G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &Step)
void ActivateFluorescence (G4bool val)
G4bool Fluorescence () const
Public Member Functions inherited from G4RDVeLowEnergyLoss
G4RDVeLowEnergyLoss (const G4String &, G4ProcessType aType=fNotDefined)
G4RDVeLowEnergyLoss (G4RDVeLowEnergyLoss &)
virtual ~G4RDVeLowEnergyLoss ()
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
Protected Member Functions inherited from G4eLowEnergyLoss
virtual std::vector
< G4DynamicParticle * > * DeexciteAtom (const G4MaterialCutsCouple *, G4double, G4double)
Protected Member Functions inherited from G4RDVeLowEnergyLoss
G4double GetLossWithFluct (const G4DynamicParticle *aParticle, const G4MaterialCutsCouple *couple, G4double MeanLoss, G4double step)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Member Functions
G4LowEnergyBremsstrahlung (const G4LowEnergyBremsstrahlung &)
G4LowEnergyBremsstrahlung & operator= (const G4LowEnergyBremsstrahlung &right)
void BuildLossTable (const G4ParticleDefinition &ParticleType)
Private Attributes
G4RDVCrossSectionHandler * crossSectionHandler
G4RDVEMDataSet * theMeanFreePath
G4RDVEnergySpectrum * energySpectrum
G4DataVector energyBins
G4RDVBremAngularDistribution * angularDistribution
G4RDVBremAngularDistribution * TsaiAngularDistribution
G4String generatorName
G4DataVector cutForSecondaryPhotons
G4double cutForPhotons
Additional Inherited Members
Static Public Member Functions inherited from G4eLowEnergyLoss
static void SetNbOfProcesses (G4int nb)
static void PlusNbOfProcesses ()
static void MinusNbOfProcesses ()
static G4int GetNbOfProcesses ()
static void SetLowerBoundEloss (G4double val)
static void SetUpperBoundEloss (G4double val)
static void SetNbinEloss (G4int nb)
static G4double GetLowerBoundEloss ()
static G4double GetUpperBoundEloss ()
static G4int GetNbinEloss ()
Static Protected Member Functions inherited from G4RDVeLowEnergyLoss
static G4PhysicsTable * BuildRangeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *theRangeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildLabTimeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *theLabTimeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildProperTimeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *ProperTimeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffATable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffATable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffBTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffBTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffCTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffCTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildInverseRangeTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theRangeCoeffATable, G4PhysicsTable *theRangeCoeffBTable, G4PhysicsTable *theRangeCoeffCTable, G4PhysicsTable *theInverseRangeTable, G4double Tmin, G4double Tmax, G4int nbin)
Protected Attributes inherited from G4eLowEnergyLoss
G4PhysicsTable * theLossTable
G4double MinKineticEnergy
G4double Charge
G4double lastCharge
Static Protected Attributes inherited from G4eLowEnergyLoss
static G4PhysicsTable * theDEDXElectronTable = 0
static G4PhysicsTable * theDEDXPositronTable = 0
static G4PhysicsTable * theRangeElectronTable = 0
static G4PhysicsTable * theRangePositronTable = 0
static G4PhysicsTable * theInverseRangeElectronTable = 0
static G4PhysicsTable * theInverseRangePositronTable = 0
static G4PhysicsTable * theLabTimeElectronTable = 0
static G4PhysicsTable * theLabTimePositronTable = 0
static G4PhysicsTable * theProperTimeElectronTable = 0
static G4PhysicsTable * theProperTimePositronTable = 0
static G4int NbOfProcesses = 2
static G4int CounterOfElectronProcess = 0
static G4int CounterOfPositronProcess = 0
static G4PhysicsTable ** RecorderOfElectronProcess
static G4PhysicsTable ** RecorderOfPositronProcess
Detailed Description
Definition at line 68 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LowEnergyBremsstrahlung.hh
Constructor & Destructor Documentation
G4LowEnergyBremsstrahlung::G4LowEnergyBremsstrahlung (const G4String & processName = "LowEnBrem")
Definition at line 83 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 83 of file G4LowEnergyBremsstrahlung.cc
References angularDistribution, cutForPhotons, generatorName, TsaiAngularDistribution, and G4VProcess::verboseLevel.
G4LowEnergyBremsstrahlung::~G4LowEnergyBremsstrahlung ()
Definition at line 114 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 114 of file G4LowEnergyBremsstrahlung.cc
References angularDistribution, crossSectionHandler, energyBins, energySpectrum, theMeanFreePath, and TsaiAngularDistribution.
G4LowEnergyBremsstrahlung::G4LowEnergyBremsstrahlung (const G4LowEnergyBremsstrahlung &) private
Member Function Documentation
void G4LowEnergyBremsstrahlung::BuildLossTable (const G4ParticleDefinition & ParticleType) private
Definition at line 220 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 220 of file G4LowEnergyBremsstrahlung.cc
References G4RDVEnergySpectrum::AverageEnergy(), G4PhysicsTable::clearAndDestroy(), crossSectionHandler, cutForSecondaryPhotons, e, energySpectrum, G4RDVCrossSectionHandler::FindValue(), G4cout, G4endl, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4ProductionCutsTable::GetEnergyCutsVector(), G4PhysicsVector::GetLowEdgeEnergy(), G4eLowEnergyLoss::GetLowerBoundEloss(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4eLowEnergyLoss::GetNbinEloss(), G4Material::GetNumberOfElements(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4eLowEnergyLoss::GetUpperBoundEloss(), G4PhysicsTable::insert(), keV, material(), min, G4PhysicsVector::PutValue(), G4eLowEnergyLoss::theLossTable, G4VProcess::verboseLevel, and Z.
Referenced by BuildPhysicsTable().
void G4LowEnergyBremsstrahlung::BuildPhysicsTable (const G4ParticleDefinition & particleType) virtual
Reimplemented from G4VProcess.
Definition at line 125 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 125 of file G4LowEnergyBremsstrahlung.cc
References G4eLowEnergyLoss::BuildDEDXTable(), BuildLossTable(), G4eLowEnergyLoss::CounterOfElectronProcess, G4eLowEnergyLoss::CounterOfPositronProcess, crossSectionHandler, cutForSecondaryPhotons, G4Electron::Electron(), energyBins, energySpectrum, G4cout, G4endl, G4eLowEnergyLoss::GetLowerBoundEloss(), G4eLowEnergyLoss::GetNbinEloss(), G4VProcess::GetProcessName(), G4eLowEnergyLoss::GetUpperBoundEloss(), G4RDVCrossSectionHandler::Initialise(), G4RDVCrossSectionHandler::LoadShellData(), G4RDVEnergySpectrum::PrintData(), G4RDVCrossSectionHandler::PrintData(), PrintInfoDefinition(), G4eLowEnergyLoss::RecorderOfElectronProcess, G4eLowEnergyLoss::RecorderOfPositronProcess, theMeanFreePath, G4VProcess::verboseLevel, and x.
G4double G4LowEnergyBremsstrahlung::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4eLowEnergyLoss.
Definition at line 385 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 385 of file G4LowEnergyBremsstrahlung.cc
References G4RDVEMDataSet::FindValue(), G4RDVEMDataSet::GetComponent(), G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), NotForced, and theMeanFreePath.
G4bool G4LowEnergyBremsstrahlung::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4eLowEnergyLoss.
Definition at line 379 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 379 of file G4LowEnergyBremsstrahlung.cc
References G4Electron::Electron().
G4LowEnergyBremsstrahlung& G4LowEnergyBremsstrahlung::operator= (const G4LowEnergyBremsstrahlung & right) private
G4VParticleChange * G4LowEnergyBremsstrahlung::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4eLowEnergyLoss.
Definition at line 300 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 300 of file G4LowEnergyBremsstrahlung.cc
References G4ParticleChange::AddSecondary(), angularDistribution, G4VProcess::aParticleChange, crossSectionHandler, cutForSecondaryPhotons, source.hepunit::electron_mass_c2, energySpectrum, G4UniformRand, G4Gamma::Gamma(), generatorName, G4MaterialCutsCouple::GetIndex(), G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4Track::GetMomentumDirection(), G4ParticleChange::Initialize(), keV, momentum, norm, phi, G4RDVBremAngularDistribution::PolarAngle(), G4VContinuousDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), CLHEP::Hep3Vector::rotateUz(), G4RDVEnergySpectrum::SampleEnergy(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VParticleChange::SetNumberOfSecondaries(), theta(), TsaiAngularDistribution, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4LowEnergyBremsstrahlung::PrintInfoDefinition ()
Definition at line 367 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 367 of file G4LowEnergyBremsstrahlung.cc
References G4cout, G4endl, and G4VProcess::GetProcessName().
Referenced by BuildPhysicsTable().
void G4LowEnergyBremsstrahlung::SetAngularGenerator (G4RDVBremAngularDistribution * distribution)
Definition at line 401 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 401 of file G4LowEnergyBremsstrahlung.cc
References angularDistribution, and G4RDVBremAngularDistribution::PrintGeneratorInformation().
void G4LowEnergyBremsstrahlung::SetAngularGenerator (const G4String & name)
Definition at line 407 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 407 of file G4LowEnergyBremsstrahlung.cc
References angularDistribution, FatalException, G4Exception(), generatorName, and G4RDVBremAngularDistribution::PrintGeneratorInformation().
void G4LowEnergyBremsstrahlung::SetCutForLowEnSecPhotons (G4double cut)
Definition at line 396 of file G4LowEnergyBremsstrahlung.cc.
View newest version in sPHENIX GitHub at line 396 of file G4LowEnergyBremsstrahlung.cc
References cutForPhotons.
Member Data Documentation
G4RDVBremAngularDistribution* G4LowEnergyBremsstrahlung::angularDistribution private
Definition at line 114 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 114 of file G4LowEnergyBremsstrahlung.hh
Referenced by G4LowEnergyBremsstrahlung(), PostStepDoIt(), SetAngularGenerator(), and ~G4LowEnergyBremsstrahlung().
G4RDVCrossSectionHandler* G4LowEnergyBremsstrahlung::crossSectionHandler private
Definition at line 110 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 110 of file G4LowEnergyBremsstrahlung.hh
Referenced by BuildLossTable(), BuildPhysicsTable(), PostStepDoIt(), and ~G4LowEnergyBremsstrahlung().
G4double G4LowEnergyBremsstrahlung::cutForPhotons private
Definition at line 120 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 120 of file G4LowEnergyBremsstrahlung.hh
Referenced by G4LowEnergyBremsstrahlung(), and SetCutForLowEnSecPhotons().
G4DataVector G4LowEnergyBremsstrahlung::cutForSecondaryPhotons private
Definition at line 119 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 119 of file G4LowEnergyBremsstrahlung.hh
Referenced by BuildLossTable(), BuildPhysicsTable(), and PostStepDoIt().
G4DataVector G4LowEnergyBremsstrahlung::energyBins private
Definition at line 113 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 113 of file G4LowEnergyBremsstrahlung.hh
Referenced by BuildPhysicsTable(), and ~G4LowEnergyBremsstrahlung().
G4RDVEnergySpectrum* G4LowEnergyBremsstrahlung::energySpectrum private
Definition at line 112 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 112 of file G4LowEnergyBremsstrahlung.hh
Referenced by BuildLossTable(), BuildPhysicsTable(), PostStepDoIt(), and ~G4LowEnergyBremsstrahlung().
G4String G4LowEnergyBremsstrahlung::generatorName private
Definition at line 116 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 116 of file G4LowEnergyBremsstrahlung.hh
Referenced by G4LowEnergyBremsstrahlung(), PostStepDoIt(), and SetAngularGenerator().
G4RDVEMDataSet* G4LowEnergyBremsstrahlung::theMeanFreePath private
Definition at line 111 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 111 of file G4LowEnergyBremsstrahlung.hh
Referenced by BuildPhysicsTable(), GetMeanFreePath(), and ~G4LowEnergyBremsstrahlung().
G4RDVBremAngularDistribution* G4LowEnergyBremsstrahlung::TsaiAngularDistribution private
Definition at line 115 of file G4LowEnergyBremsstrahlung.hh.
View newest version in sPHENIX GitHub at line 115 of file G4LowEnergyBremsstrahlung.hh
Referenced by G4LowEnergyBremsstrahlung(), PostStepDoIt(), and ~G4LowEnergyBremsstrahlung().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyBremsstrahlung.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4LowEnergyBremsstrahlung.cc