ECCE @ EIC Software: G4OpticalPhysics Class Reference
G4OpticalPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4OpticalPhysics.hh>
Public Member Functions
G4OpticalPhysics (G4int verbose=0, const G4String &name="Optical")
virtual ~G4OpticalPhysics ()
void Configure (G4OpticalProcessIndex, G4bool)
void SetTrackSecondariesFirst (G4OpticalProcessIndex, G4bool)
void SetMaxNumPhotonsPerStep (G4int)
void SetMaxBetaChangePerStep (G4double)
void SetCerenkovStackPhotons (G4bool)
void SetCerenkovTrackSecondariesFirst (G4bool)
void SetCerenkovVerbosity (G4int)
void SetScintillationYieldFactor (G4double)
void SetScintillationExcitationRatio (G4double)
void SetScintillationByParticleType (G4bool)
void SetScintillationTrackInfo (G4bool)
void SetScintillationTrackSecondariesFirst (G4bool)
void SetFiniteRiseTime (G4bool)
void SetScintillationStackPhotons (G4bool)
void SetScintillationVerbosity (G4int)
void SetWLSTimeProfile (G4String)
void SetWLSVerbosity (G4int)
void SetBoundaryVerbosity (G4int)
void SetInvokeSD (G4bool)
void SetAbsorptionVerbosity (G4int)
void SetRayleighVerbosity (G4int)
void SetMieVerbosity (G4int)
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Member Functions
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Private Member Functions
G4OpticalPhysics (const G4OpticalPhysics &right)
Not implemented.
G4OpticalPhysics & operator= (const G4OpticalPhysics &right)
Not implemented.
void PrintStatistics () const
Private Attributes
G4OpticalPhysicsMessenger * fMessenger
std::vector< G4bool > fProcessUse
std::vector< G4bool > fProcessTrackSecondariesFirst
G4double fYieldFactor
scintillation yield factor
G4double fExcitationRatio
scintillation excitation ratio
G4bool fFiniteRiseTime
G4bool fScintillationByParticleType
G4bool fScintillationTrackInfo
G4bool fScintillationStackPhotons
option to allow stacking of secondary Scintillation photons
G4int fScintillationVerbosity
G4int fMaxNumPhotons
max number of Cerenkov photons per step
G4double fMaxBetaChange
max change of beta per step
G4bool fCerenkovStackPhotons
option to allow stacking of secondary Cerenkov photons
G4int fCerenkovVerbosity
G4String fWLSTimeProfileName
G4int fWLSVerbosity
G4int fAbsorptionVerbosity
G4int fRayleighVerbosity
G4int fMieVerbosity
G4bool fInvokeSD
G4OpBoundaryProcess to call InvokeSD method.
G4int fBoundaryVerbosity
Static Private Attributes
static G4ThreadLocal
G4Scintillation * fScintillationProcess = nullptr
static G4ThreadLocal G4Cerenkov * fCerenkovProcess = nullptr
static G4ThreadLocal G4OpWLS * fWLSProcess = nullptr
static G4ThreadLocal
G4OpAbsorption * fAbsorptionProcess = nullptr
static G4ThreadLocal G4OpRayleigh * fRayleighProcess = nullptr
static G4ThreadLocal G4OpMieHG * fMieProcess = nullptr
static G4ThreadLocal
G4OpBoundaryProcess * fBoundaryProcess = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 66 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 66 of file G4OpticalPhysics.hh
Constructor & Destructor Documentation
G4OpticalPhysics::G4OpticalPhysics (G4int verbose = 0, const G4String & name = "Optical")
Definition at line 70 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 70 of file G4OpticalPhysics.cc
References fMessenger, fProcessTrackSecondariesFirst, fProcessUse, kNoProcess, and G4VPhysicsConstructor::verboseLevel.
G4OpticalPhysics::~G4OpticalPhysics () virtual
Definition at line 104 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 104 of file G4OpticalPhysics.cc
References fMessenger.
G4OpticalPhysics::G4OpticalPhysics (const G4OpticalPhysics & right) private
Not implemented.
Member Function Documentation
void G4OpticalPhysics::Configure (G4OpticalProcessIndex index, G4bool isUse)
Definition at line 444 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 444 of file G4OpticalPhysics.cc
References fProcessUse, and kNoProcess.
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::ConstructParticle (void) protected virtual
Implements G4VPhysicsConstructor.
Definition at line 154 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 154 of file G4OpticalPhysics.cc
References G4OpticalPhoton::OpticalPhotonDefinition().
void G4OpticalPhysics::ConstructProcess (void) protected virtual
Implements G4VPhysicsConstructor.
Definition at line 161 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 161 of file G4OpticalPhysics.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4Scintillation::AddSaturation(), G4LossTableManager::EmSaturation(), fAbsorptionProcess, FatalException, fBoundaryProcess, fCerenkovProcess, fCerenkovStackPhotons, fExcitationRatio, fFiniteRiseTime, fInvokeSD, fMaxBetaChange, fMaxNumPhotons, fMieProcess, fProcessTrackSecondariesFirst, fProcessUse, fRayleighProcess, fScintillationByParticleType, fScintillationProcess, fScintillationStackPhotons, fScintillationTrackInfo, fWLSProcess, fWLSTimeProfileName, fYieldFactor, G4cout, G4endl, G4Exception(), G4VPhysicsConstructor::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), idxAtRest, idxPostStep, G4LossTableManager::Instance(), G4Cerenkov::IsApplicable(), G4Scintillation::IsApplicable(), G4OpBoundaryProcess::IsApplicable(), kAbsorption, kBoundary, kCerenkov, kMieHG, kNoProcess, kRayleigh, kScintillation, kWLS, G4VPhysicsConstructor::namePhysics, G4OpticalPhoton::OpticalPhoton(), particle, PrintStatistics(), G4Scintillation::SetFiniteRiseTime(), G4OpBoundaryProcess::SetInvokeSD(), G4Cerenkov::SetMaxBetaChangePerStep(), G4Cerenkov::SetMaxNumPhotonsPerStep(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToLast(), G4Scintillation::SetScintillationByParticleType(), G4Scintillation::SetScintillationExcitationRatio(), G4Scintillation::SetScintillationTrackInfo(), G4Scintillation::SetScintillationYieldFactor(), G4Cerenkov::SetStackPhotons(), G4Scintillation::SetStackPhotons(), G4Cerenkov::SetTrackSecondariesFirst(), G4Scintillation::SetTrackSecondariesFirst(), G4OpWLS::UseTimeProfile(), and G4VPhysicsConstructor::verboseLevel.
G4OpticalPhysics& G4OpticalPhysics::operator= (const G4OpticalPhysics & right) private
Not implemented.
void G4OpticalPhysics::PrintStatistics () const private
Definition at line 112 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 112 of file G4OpticalPhysics.cc
References fExcitationRatio, fMaxBetaChange, fMaxNumPhotons, fProcessTrackSecondariesFirst, fProcessUse, fScintillationByParticleType, fWLSTimeProfileName, fYieldFactor, G4cout, G4endl, G4OpticalProcessName(), kCerenkov, kNoProcess, kScintillation, and kWLS.
Referenced by ConstructProcess().
void G4OpticalPhysics::SetAbsorptionVerbosity (G4int ver)
Definition at line 380 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 380 of file G4OpticalPhysics.cc
References fAbsorptionProcess, fAbsorptionVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetBoundaryVerbosity (G4int ver)
Definition at line 404 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 404 of file G4OpticalPhysics.cc
References fBoundaryProcess, fBoundaryVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetCerenkovStackPhotons (G4bool val)
Definition at line 304 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 304 of file G4OpticalPhysics.cc
References fCerenkovProcess, fCerenkovStackPhotons, and G4Cerenkov::SetStackPhotons().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetCerenkovTrackSecondariesFirst (G4bool val)
Definition at line 312 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 312 of file G4OpticalPhysics.cc
References fCerenkovProcess, fProcessTrackSecondariesFirst, kCerenkov, and SetTrackSecondariesFirst().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetCerenkovVerbosity (G4int ver)
Definition at line 321 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 321 of file G4OpticalPhysics.cc
References fCerenkovProcess, fCerenkovVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetFiniteRiseTime (G4bool b)
Definition at line 420 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 420 of file G4OpticalPhysics.cc
References b, fFiniteRiseTime, fScintillationProcess, and G4Scintillation::SetFiniteRiseTime().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetInvokeSD (G4bool b)
Definition at line 428 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 428 of file G4OpticalPhysics.cc
References b, fBoundaryProcess, fInvokeSD, and G4OpBoundaryProcess::SetInvokeSD().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetMaxBetaChangePerStep (G4double val)
Limit step to the specified maximum change of beta of the parent particle
Definition at line 295 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 295 of file G4OpticalPhysics.cc
References fCerenkovProcess, fMaxBetaChange, and G4Cerenkov::SetMaxBetaChangePerStep().
Referenced by main(), and G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetMaxNumPhotonsPerStep (G4int val)
Limit step to the specified maximum number of Cerenkov photons
Definition at line 286 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 286 of file G4OpticalPhysics.cc
References fCerenkovProcess, fMaxNumPhotons, and G4Cerenkov::SetMaxNumPhotonsPerStep().
Referenced by main(), and G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetMieVerbosity (G4int ver)
Definition at line 396 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 396 of file G4OpticalPhysics.cc
References fMieProcess, fMieVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetRayleighVerbosity (G4int ver)
Definition at line 388 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 388 of file G4OpticalPhysics.cc
References fRayleighProcess, fRayleighVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationByParticleType (G4bool val)
Definition at line 346 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 346 of file G4OpticalPhysics.cc
References fScintillationByParticleType, and fScintillationProcess.
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationExcitationRatio (G4double val)
Definition at line 278 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 278 of file G4OpticalPhysics.cc
References fExcitationRatio, fScintillationProcess, and G4Scintillation::SetScintillationExcitationRatio().
Referenced by main(), and G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationStackPhotons (G4bool stackingFlag)
Definition at line 436 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 436 of file G4OpticalPhysics.cc
References fScintillationProcess, fScintillationStackPhotons, and G4Scintillation::SetStackPhotons().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationTrackInfo (G4bool val)
Definition at line 364 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 364 of file G4OpticalPhysics.cc
References fScintillationProcess, fScintillationTrackInfo, and G4Scintillation::SetScintillationTrackInfo().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationTrackSecondariesFirst (G4bool val)
Definition at line 355 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 355 of file G4OpticalPhysics.cc
References fProcessTrackSecondariesFirst, fScintillationProcess, kScintillation, and SetTrackSecondariesFirst().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationVerbosity (G4int ver)
Definition at line 372 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 372 of file G4OpticalPhysics.cc
References fScintillationProcess, fScintillationVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetScintillationYieldFactor (G4double val)
Definition at line 270 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 270 of file G4OpticalPhysics.cc
References fScintillationProcess, fYieldFactor, and G4Scintillation::SetScintillationYieldFactor().
Referenced by main(), and G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetTrackSecondariesFirst (G4OpticalProcessIndex index, G4bool trackSecondariesFirst)
Definition at line 412 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 412 of file G4OpticalPhysics.cc
References fProcessTrackSecondariesFirst, and kNoProcess.
Referenced by main(), SetCerenkovTrackSecondariesFirst(), G4OpticalPhysicsMessenger::SetNewValue(), and SetScintillationTrackSecondariesFirst().
void G4OpticalPhysics::SetWLSTimeProfile (G4String name)
Set the WLS time profile (delta or exponential)
Definition at line 329 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 329 of file G4OpticalPhysics.cc
References fWLSProcess, fWLSTimeProfileName, and G4OpWLS::UseTimeProfile().
Referenced by main(), and G4OpticalPhysicsMessenger::SetNewValue().
void G4OpticalPhysics::SetWLSVerbosity (G4int ver)
Definition at line 338 of file G4OpticalPhysics.cc.
View newest version in sPHENIX GitHub at line 338 of file G4OpticalPhysics.cc
References fWLSProcess, fWLSVerbosity, and G4VProcess::SetVerboseLevel().
Referenced by G4OpticalPhysicsMessenger::SetNewValue().
Member Data Documentation
G4ThreadLocal G4OpAbsorption * G4OpticalPhysics::fAbsorptionProcess = nullptr static private
Definition at line 180 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 180 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetAbsorptionVerbosity().
G4int G4OpticalPhysics::fAbsorptionVerbosity private
Definition at line 181 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 181 of file G4OpticalPhysics.hh
Referenced by SetAbsorptionVerbosity().
G4ThreadLocal G4OpBoundaryProcess * G4OpticalPhysics::fBoundaryProcess = nullptr static private
Definition at line 189 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 189 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), SetBoundaryVerbosity(), and SetInvokeSD().
G4int G4OpticalPhysics::fBoundaryVerbosity private
Definition at line 192 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 192 of file G4OpticalPhysics.hh
Referenced by SetBoundaryVerbosity().
G4ThreadLocal G4Cerenkov * G4OpticalPhysics::fCerenkovProcess = nullptr static private
Definition at line 166 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 166 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), SetCerenkovStackPhotons(), SetCerenkovTrackSecondariesFirst(), SetCerenkovVerbosity(), SetMaxBetaChangePerStep(), and SetMaxNumPhotonsPerStep().
G4bool G4OpticalPhysics::fCerenkovStackPhotons private
option to allow stacking of secondary Cerenkov photons
Definition at line 172 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 172 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetCerenkovStackPhotons().
G4int G4OpticalPhysics::fCerenkovVerbosity private
Definition at line 173 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 173 of file G4OpticalPhysics.hh
Referenced by SetCerenkovVerbosity().
G4double G4OpticalPhysics::fExcitationRatio private
scintillation excitation ratio
Definition at line 144 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 144 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), PrintStatistics(), and SetScintillationExcitationRatio().
G4bool G4OpticalPhysics::fFiniteRiseTime private
option to set a finite rise-time; Note: the G4Scintillation process expects the user to have set the constant material property FAST/SLOWSCINTILLATIONRISETIME
Definition at line 149 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 149 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetFiniteRiseTime().
G4bool G4OpticalPhysics::fInvokeSD private
G4OpBoundaryProcess to call InvokeSD method.
Definition at line 191 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 191 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetInvokeSD().
G4double G4OpticalPhysics::fMaxBetaChange private
max change of beta per step
Definition at line 170 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 170 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), PrintStatistics(), and SetMaxBetaChangePerStep().
G4int G4OpticalPhysics::fMaxNumPhotons private
max number of Cerenkov photons per step
Definition at line 168 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 168 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), PrintStatistics(), and SetMaxNumPhotonsPerStep().
G4OpticalPhysicsMessenger* G4OpticalPhysics::fMessenger private
Definition at line 129 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 129 of file G4OpticalPhysics.hh
Referenced by G4OpticalPhysics(), and ~G4OpticalPhysics().
G4ThreadLocal G4OpMieHG * G4OpticalPhysics::fMieProcess = nullptr static private
Definition at line 186 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 186 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetMieVerbosity().
G4int G4OpticalPhysics::fMieVerbosity private
Definition at line 187 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 187 of file G4OpticalPhysics.hh
Referenced by SetMieVerbosity().
std::vector<G4bool> G4OpticalPhysics::fProcessTrackSecondariesFirst private
Definition at line 136 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 136 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), G4OpticalPhysics(), PrintStatistics(), SetCerenkovTrackSecondariesFirst(), SetScintillationTrackSecondariesFirst(), and SetTrackSecondariesFirst().
std::vector<G4bool> G4OpticalPhysics::fProcessUse private
Definition at line 132 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 132 of file G4OpticalPhysics.hh
Referenced by Configure(), ConstructProcess(), G4OpticalPhysics(), and PrintStatistics().
G4ThreadLocal G4OpRayleigh * G4OpticalPhysics::fRayleighProcess = nullptr static private
Definition at line 183 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 183 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetRayleighVerbosity().
G4int G4OpticalPhysics::fRayleighVerbosity private
Definition at line 184 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 184 of file G4OpticalPhysics.hh
Referenced by SetRayleighVerbosity().
G4bool G4OpticalPhysics::fScintillationByParticleType private
option to allow for the light yield to be a function of particle type and deposited energy in case of non-linear light emission in scintillators
Definition at line 154 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 154 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), PrintStatistics(), and SetScintillationByParticleType().
G4ThreadLocal G4Scintillation * G4OpticalPhysics::fScintillationProcess = nullptr static private
Definition at line 139 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 139 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), SetFiniteRiseTime(), SetScintillationByParticleType(), SetScintillationExcitationRatio(), SetScintillationStackPhotons(), SetScintillationTrackInfo(), SetScintillationTrackSecondariesFirst(), SetScintillationVerbosity(), and SetScintillationYieldFactor().
G4bool G4OpticalPhysics::fScintillationStackPhotons private
option to allow stacking of secondary Scintillation photons
Definition at line 161 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 161 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetScintillationStackPhotons().
G4bool G4OpticalPhysics::fScintillationTrackInfo private
option to allow for G4ScintillationTrackInformation to be attached to a scintillation photon's track
Definition at line 158 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 158 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), and SetScintillationTrackInfo().
G4int G4OpticalPhysics::fScintillationVerbosity private
Definition at line 163 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 163 of file G4OpticalPhysics.hh
Referenced by SetScintillationVerbosity().
G4ThreadLocal G4OpWLS * G4OpticalPhysics::fWLSProcess = nullptr static private
Definition at line 176 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 176 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), SetWLSTimeProfile(), and SetWLSVerbosity().
G4String G4OpticalPhysics::fWLSTimeProfileName private
Definition at line 177 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 177 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), PrintStatistics(), and SetWLSTimeProfile().
G4int G4OpticalPhysics::fWLSVerbosity private
Definition at line 178 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 178 of file G4OpticalPhysics.hh
Referenced by SetWLSVerbosity().
G4double G4OpticalPhysics::fYieldFactor private
scintillation yield factor
Definition at line 141 of file G4OpticalPhysics.hh.
View newest version in sPHENIX GitHub at line 141 of file G4OpticalPhysics.hh
Referenced by ConstructProcess(), PrintStatistics(), and SetScintillationYieldFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4OpticalPhysics.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/src/G4OpticalPhysics.cc