ECCE @ EIC Software: G4mpi Namespace Reference
G4mpi Namespace Reference
Typedefs
typedef unsigned int rank_t
typedef std::pair< rank_t, rank_t > couple_t
typedef std::map< int,
std::vector< couple_t > > commMap_t
typedef std::function< void(std::function
< void(unsigned int)>
, std::function< void(unsigned
int)>, std::function< void(void)>
, unsigned int, unsigned int)> mergerHandler_t
Functions
commMap_t buildCommunicationMap (std::vector< rank_t > &input)
void Merge (std::function< void(unsigned int)> senderF, std::function< void(unsigned int)> receiverF, std::function< void(void)> barrierF, unsigned int commSize, unsigned int myrank)
Typedef Documentation
typedef std::map<int,std::vector<couple_t> > G4mpi::commMap_t
Definition at line 50 of file G4MPIutils.hh.
View newest version in sPHENIX GitHub at line 50 of file G4MPIutils.hh
typedef std::pair<rank_t,rank_t> G4mpi::couple_t
Definition at line 47 of file G4MPIutils.hh.
View newest version in sPHENIX GitHub at line 47 of file G4MPIutils.hh
typedef std::function<void(std::function<void(unsigned int)>, std::function<void(unsigned int)>, std::function<void(void)>, unsigned int, unsigned int)> G4mpi::mergerHandler_t
Definition at line 93 of file G4MPIutils.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MPIutils.hh
typedef unsigned int G4mpi::rank_t
Definition at line 45 of file G4MPIutils.hh.
View newest version in sPHENIX GitHub at line 45 of file G4MPIutils.hh
Function Documentation
G4mpi::commMap_t G4mpi::buildCommunicationMap (std::vector< rank_t > & input)
Definition at line 37 of file G4MPIutils.cc.
View newest version in sPHENIX GitHub at line 37 of file G4MPIutils.cc
References field_utils::copy(), FatalException, and G4Exception().
Referenced by _testMe(), and Merge().
void G4mpi::Merge (std::function< void(unsigned int)> senderF, std::function< void(unsigned int)> receiverF, std::function< void(void)> barrierF, unsigned int commSize, unsigned int myrank)
Definition at line 161 of file G4MPIutils.cc.
View newest version in sPHENIX GitHub at line 161 of file G4MPIutils.cc
References buildCommunicationMap().
Referenced by G4VUserMPIrunMerger::Merge(), and G4MPIscorerMerger::Merge().