ECCE @ EIC Software: G4KDTreeResult Class Reference
G4KDTreeResult Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDTreeResult.hh>
Public Member Functions
G4KDTreeResult (G4KDTree *)
virtual ~G4KDTreeResult ()
void * operator new (size_t)
void operator delete (void *)
void Insert (double, G4KDNode_Base *)
void Clear ()
void Sort ()
size_t GetSize () const
size_t size () const
void Rewind ()
bool End ()
void Next ()
template<typename PointT >
PointT * GetItem () const
G4KDNode_Base * GetNode () const
template<typename PointT >
PointT * GetItemNDistanceSQ (double &) const
double GetDistanceSqr () const
Protected Attributes
G4KDTree * fTree
KDTR_parent::iterator fIterator
Detailed Description
Definition at line 69 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 69 of file G4KDTreeResult.hh
Constructor & Destructor Documentation
G4KDTreeResult::G4KDTreeResult (G4KDTree * tree)
Definition at line 87 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 87 of file G4KDTreeResult.cc
References fTree, and gammaraytel::tree.
G4KDTreeResult::~G4KDTreeResult () virtual
Definition at line 94 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 94 of file G4KDTreeResult.cc
Member Function Documentation
void G4KDTreeResult::Clear ()
Definition at line 106 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 106 of file G4KDTreeResult.cc
References fIterator.
bool G4KDTreeResult::End ()
Definition at line 137 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 137 of file G4KDTreeResult.cc
References fIterator.
double G4KDTreeResult::GetDistanceSqr () const
Definition at line 147 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 147 of file G4KDTreeResult.cc
Referenced by GetItemNDistanceSQ().
template<typename PointT > PointT * G4KDTreeResult::GetItem () const
Definition at line 139 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 139 of file G4KDTreeResult.hh
References GetNode(), and G4KDNode< PointT >::GetPoint().
template<typename PointT > PointT * G4KDTreeResult::GetItemNDistanceSQ (double & dist_sq) const
Definition at line 146 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 146 of file G4KDTreeResult.hh
References GetDistanceSqr().
G4KDNode_Base * G4KDTreeResult::GetNode () const
Definition at line 152 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 152 of file G4KDTreeResult.cc
Referenced by GetItem().
size_t G4KDTreeResult::GetSize () const
Definition at line 120 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 120 of file G4KDTreeResult.cc
void G4KDTreeResult::Insert (double dis_sq, G4KDNode_Base * node)
Definition at line 100 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 100 of file G4KDTreeResult.cc
void G4KDTreeResult::Next ()
Definition at line 142 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 142 of file G4KDTreeResult.cc
References fIterator.
void G4KDTreeResult::operator delete (void * object) inline
Definition at line 133 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 133 of file G4KDTreeResult.hh
References aKDTreeAllocator().
void * G4KDTreeResult::operator new (size_t) inline
Definition at line 127 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 127 of file G4KDTreeResult.hh
References aKDTreeAllocator().
void G4KDTreeResult::Rewind ()
Definition at line 132 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 132 of file G4KDTreeResult.cc
References fIterator.
Referenced by G4KDTree::NearestInRange().
size_t G4KDTreeResult::size (void) const
Definition at line 126 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 126 of file G4KDTreeResult.cc
void G4KDTreeResult::Sort ()
Definition at line 114 of file G4KDTreeResult.cc.
View newest version in sPHENIX GitHub at line 114 of file G4KDTreeResult.cc
References CompareResNode().
Referenced by G4KDTree::NearestInRange().
Member Data Documentation
KDTR_parent::iterator G4KDTreeResult::fIterator protected
Definition at line 74 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 74 of file G4KDTreeResult.hh
Referenced by Clear(), End(), Next(), and Rewind().
G4KDTree* G4KDTreeResult::fTree protected
Definition at line 72 of file G4KDTreeResult.hh.
View newest version in sPHENIX GitHub at line 72 of file G4KDTreeResult.hh
Referenced by G4KDTreeResult().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDTreeResult.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4KDTreeResult.cc