ECCE @ EIC Software: G4TrajectoryOriginVolumeFilter Class Reference
G4TrajectoryOriginVolumeFilter Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryOriginVolumeFilter.hh>
Public Member Functions
G4TrajectoryOriginVolumeFilter (const G4String &name="Unspecified")
virtual ~G4TrajectoryOriginVolumeFilter ()
virtual bool Evaluate (const G4VTrajectory &) const
virtual void Print (std::ostream &ostr) const
virtual void Clear ()
void Add (const G4String &volume)
Public Member Functions inherited from G4SmartFilter< G4VTrajectory >
G4SmartFilter (const G4String &name)
virtual ~G4SmartFilter ()
G4bool Accept (const G4VTrajectory &) const
virtual void PrintAll (std::ostream &ostr) const
virtual void Reset ()
void SetActive (const G4bool &)
G4bool GetActive () const
void SetInvert (const G4bool &)
G4bool GetInvert () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Public Member Functions inherited from G4VFilter< G4VTrajectory >
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
G4String Name () const
G4String GetName () const
Private Attributes
std::vector< G4String > fVolumes
Additional Inherited Members
Public Types inherited from G4VFilter< G4VTrajectory >
typedef G4VTrajectory Type
Detailed Description
Definition at line 39 of file G4TrajectoryOriginVolumeFilter.hh.
View newest version in sPHENIX GitHub at line 39 of file G4TrajectoryOriginVolumeFilter.hh
Constructor & Destructor Documentation
G4TrajectoryOriginVolumeFilter::G4TrajectoryOriginVolumeFilter (const G4String & name = "Unspecified")
Definition at line 36 of file G4TrajectoryOriginVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 36 of file G4TrajectoryOriginVolumeFilter.cc
G4TrajectoryOriginVolumeFilter::~G4TrajectoryOriginVolumeFilter () virtual
Definition at line 40 of file G4TrajectoryOriginVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 40 of file G4TrajectoryOriginVolumeFilter.cc
Member Function Documentation
void G4TrajectoryOriginVolumeFilter::Add (const G4String & volume)
Definition at line 82 of file G4TrajectoryOriginVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 82 of file G4TrajectoryOriginVolumeFilter.cc
References fVolumes.
void G4TrajectoryOriginVolumeFilter::Clear () virtual
Implements G4SmartFilter< G4VTrajectory >.
Definition at line 100 of file G4TrajectoryOriginVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 100 of file G4TrajectoryOriginVolumeFilter.cc
References fVolumes.
bool G4TrajectoryOriginVolumeFilter::Evaluate (const G4VTrajectory & traj) const virtual
Implements G4SmartFilter< G4VTrajectory >.
Definition at line 43 of file G4TrajectoryOriginVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 43 of file G4TrajectoryOriginVolumeFilter.cc
References fVolumes, G4cout, G4endl, G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4TransportationManager::GetNavigatorForTracking(), G4VTrajectory::GetPoint(), G4VTrajectoryPoint::GetPosition(), G4TransportationManager::GetTransportationManager(), G4SmartFilter< G4VTrajectory >::GetVerbose(), G4Navigator::LocateGlobalPointAndSetup(), Acts::Test::navigator, and Acts::Test::volume.
void G4TrajectoryOriginVolumeFilter::Print (std::ostream & ostr) const virtual
Implements G4SmartFilter< G4VTrajectory >.
Definition at line 88 of file G4TrajectoryOriginVolumeFilter.cc.
View newest version in sPHENIX GitHub at line 88 of file G4TrajectoryOriginVolumeFilter.cc
References fVolumes, and G4endl.
Member Data Documentation
std::vector<G4String> G4TrajectoryOriginVolumeFilter::fVolumes private
Definition at line 63 of file G4TrajectoryOriginVolumeFilter.hh.
View newest version in sPHENIX GitHub at line 63 of file G4TrajectoryOriginVolumeFilter.hh
Referenced by Add(), Clear(), Evaluate(), and Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryOriginVolumeFilter.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryOriginVolumeFilter.cc