ECCE @ EIC Software: G4AblaInterface Class Reference
G4AblaInterface Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4AblaInterface.hh>
Public Member Functions
G4AblaInterface ()
virtual ~G4AblaInterface ()
virtual G4ReactionProductVector * DeExcite (G4Fragment &aFragment)
virtual G4HadFinalState * ApplyYourself (G4HadProjectile const &, G4Nucleus &)
virtual void ModelDescription (std::ostream &outFile) const
virtual void DeExciteModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4VPreCompoundModel
G4VPreCompoundModel (G4ExcitationHandler *ptr=nullptr, const G4String &modelName="PrecompoundModel")
virtual ~G4VPreCompoundModel ()
void SetExcitationHandler (G4ExcitationHandler *ptr)
G4ExcitationHandler * GetExcitationHandler () const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4ReactionProduct * toG4Particle (G4int A, G4int Z, G4int S, G4double kinE, G4double px, G4double py, G4double pz) const
Convert an Abla particle to a G4DynamicParticle.
G4ParticleDefinition * toG4ParticleDefinition (G4int A, G4int Z, G4int S) const
Convert A, Z and S to a G4ParticleDefinition.
Private Attributes
G4VarNtp * ablaResult
G4Volant * volant
G4Abla * theABLAModel
G4long eventNumber
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 50 of file G4AblaInterface.hh.
View newest version in sPHENIX GitHub at line 50 of file G4AblaInterface.hh
Constructor & Destructor Documentation
G4AblaInterface::G4AblaInterface ()
Definition at line 51 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 51 of file G4AblaInterface.cc
References G4Abla::initEvapora(), G4Abla::SetParameters(), and theABLAModel.
G4AblaInterface::~G4AblaInterface () virtual
Definition at line 62 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 62 of file G4AblaInterface.cc
References ablaResult, theABLAModel, and volant.
Member Function Documentation
virtual G4HadFinalState* G4AblaInterface::ApplyYourself (G4HadProjectile const & , G4Nucleus &) inline virtual
Implements G4HadronicInteraction.
Definition at line 57 of file G4AblaInterface.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AblaInterface.hh
G4ReactionProductVector * G4AblaInterface::DeExcite (G4Fragment & aFragment) virtual
Implements G4VPreCompoundModel.
Definition at line 68 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 68 of file G4AblaInterface.cc
References ablaResult, G4VarNtp::avv, G4Volant::clear(), G4VarNtp::clear(), G4Abla::DeexcitationAblaxx(), G4VarNtp::enerj, eventNumber, G4Fragment::GetA_asInt(), G4Fragment::GetAngularMomentum(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetMomentum(), G4Fragment::GetZ_asInt(), source.hepunit::hbar_Planck, CLHEP::Hep3Vector::mag(), MeV, G4VarNtp::ntrack, G4VarNtp::pxlab, G4VarNtp::pylab, G4VarNtp::pzlab, G4VarNtp::svv, theABLAModel, toG4Particle(), volant, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), CLHEP::HepLorentzVector::z(), and G4VarNtp::zvv.
void G4AblaInterface::DeExciteModelDescription (std::ostream & outFile) const virtual
Implements G4VPreCompoundModel.
Definition at line 150 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 150 of file G4AblaInterface.cc
void G4AblaInterface::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 146 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 146 of file G4AblaInterface.cc
G4ReactionProduct * G4AblaInterface::toG4Particle (G4int A, G4int Z, G4int S, G4double kinE, G4double px, G4double py, G4double pz) const private
Convert an Abla particle to a G4DynamicParticle.
Definition at line 128 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 128 of file G4AblaInterface.cc
References energy, MeV, momentum, r, toG4ParticleDefinition(), and CLHEP::Hep3Vector::unit().
Referenced by DeExcite().
G4ParticleDefinition * G4AblaInterface::toG4ParticleDefinition (G4int A, G4int Z, G4int S) const private
Convert A, Z and S to a G4ParticleDefinition.
Definition at line 108 of file G4AblaInterface.cc.
View newest version in sPHENIX GitHub at line 108 of file G4AblaInterface.cc
References kdfinder::abs(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4cout, G4endl, G4Gamma::Gamma(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4He3::He3(), G4Lambda::Lambda(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4Proton::Proton(), and G4Triton::Triton().
Referenced by toG4Particle().
Member Data Documentation
G4VarNtp* G4AblaInterface::ablaResult private
Definition at line 65 of file G4AblaInterface.hh.
View newest version in sPHENIX GitHub at line 65 of file G4AblaInterface.hh
Referenced by DeExcite(), and ~G4AblaInterface().
G4long G4AblaInterface::eventNumber private
Definition at line 68 of file G4AblaInterface.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AblaInterface.hh
Referenced by DeExcite().
G4Abla* G4AblaInterface::theABLAModel private
Definition at line 67 of file G4AblaInterface.hh.
View newest version in sPHENIX GitHub at line 67 of file G4AblaInterface.hh
Referenced by DeExcite(), G4AblaInterface(), and ~G4AblaInterface().
G4Volant* G4AblaInterface::volant private
Definition at line 66 of file G4AblaInterface.hh.
View newest version in sPHENIX GitHub at line 66 of file G4AblaInterface.hh
Referenced by DeExcite(), and ~G4AblaInterface().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4AblaInterface.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/src/G4AblaInterface.cc