ECCE @ EIC Software: G4FermiFragmentsPoolVI Class Reference
G4FermiFragmentsPoolVI Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiFragmentsPoolVI.hh>
Public Member Functions
G4FermiFragmentsPoolVI ()
~G4FermiFragmentsPoolVI ()
const G4FermiChannels * ClosestChannels (G4int Z, G4int A, G4double mass) const
void DumpFragment (const G4FermiFragment *) const
void Dump () const
G4bool IsPhysical (G4int Z, G4int A) const
G4bool HasChannels (G4int Z, G4int A, G4double exc) const
const G4FermiDecayProbability * FermiDecayProbability () const
G4int GetMaxZ () const
G4int GetMaxA () const
G4double GetEnergyLimit () const
G4double GetTolerance () const
Private Member Functions
void Initialise ()
G4bool IsInThePool (G4int Z, G4int A, G4double exc) const
G4bool IsInPhysPairs (const G4FermiFragment *f1, const G4FermiFragment *f2) const
G4bool IsInUnphysPairs (const G4FermiFragment *f1, const G4FermiFragment *f2) const
Private Attributes
G4double tolerance
G4double elim
G4float timelim
G4float elimf
G4FermiDecayProbability theDecay
std::vector< const
G4FermiFragment * > fragment_pool
std::vector< const
G4FermiFragment * > list_f [maxA]
std::vector< G4FermiChannels * > list_c [maxA]
std::vector< const G4FermiPair * > list_p [maxA]
Detailed Description
Definition at line 45 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 45 of file G4FermiFragmentsPoolVI.hh
Constructor & Destructor Documentation
G4FermiFragmentsPoolVI::G4FermiFragmentsPoolVI () explicit
Definition at line 39 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 39 of file G4FermiFragmentsPoolVI.cc
References elim, elimf, fragment_pool, G4DeexPrecoParameters::GetFBUEnergyLimit(), G4NuclearLevelData::GetInstance(), G4DeexPrecoParameters::GetMaxLifeTime(), G4DeexPrecoParameters::GetMinExcitation(), G4NuclearLevelData::GetParameters(), Initialise(), timelim, and tolerance.
G4FermiFragmentsPoolVI::~G4FermiFragmentsPoolVI ()
Definition at line 57 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 57 of file G4FermiFragmentsPoolVI.cc
References fragment_pool, list_c, list_p, and maxA.
Member Function Documentation
const G4FermiChannels * G4FermiFragmentsPoolVI::ClosestChannels (G4int Z, G4int A, G4double mass) const
Definition at line 67 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 67 of file G4FermiFragmentsPoolVI.cc
References A(), kdfinder::abs(), G4FermiFragment::GetTotalEnergy(), G4FermiFragment::GetZ(), list_c, list_f, tolerance, and Z.
Referenced by G4FermiBreakUpVI::SampleDecay().
void G4FermiFragmentsPoolVI::Dump () const
Definition at line 302 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 302 of file G4FermiFragmentsPoolVI.cc
References A(), DumpFragment(), elim, f, f1, f2, fragment_pool, G4cout, G4endl, G4FermiFragment::GetA(), G4FermiFragment::GetExcitationEnergy(), G4FermiPair::GetFragment1(), G4FermiPair::GetFragment2(), G4FermiFragment::GetSpin(), G4FermiFragment::GetTotalEnergy(), G4FermiFragment::GetZ(), k, list_c, list_f, list_p, max, maxA, CLHEP::MeV, source.hepunit::neutron_mass_c2, CLHEP::prec, source.hepunit::proton_mass_c2, z1, and z2.
void G4FermiFragmentsPoolVI::DumpFragment (const G4FermiFragment * f) const
Definition at line 288 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 288 of file G4FermiFragmentsPoolVI.cc
References G4cout, G4endl, G4FermiFragment::GetA(), G4FermiFragment::GetExcitationEnergy(), G4FermiFragment::GetFragmentMass(), G4FermiFragment::GetSpin(), G4FermiFragment::GetZ(), GeV, HasChannels(), and CLHEP::prec.
Referenced by Dump().
const G4FermiDecayProbability * G4FermiFragmentsPoolVI::FermiDecayProbability () const inline
Definition at line 115 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 115 of file G4FermiFragmentsPoolVI.hh
References theDecay.
Referenced by G4FermiBreakUpVI::Initialise().
G4double G4FermiFragmentsPoolVI::GetEnergyLimit () const inline
Definition at line 120 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 120 of file G4FermiFragmentsPoolVI.hh
References elim.
Referenced by G4FermiBreakUpVI::Initialise().
G4int G4FermiFragmentsPoolVI::GetMaxA () const inline
Definition at line 109 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 109 of file G4FermiFragmentsPoolVI.hh
References maxA.
G4int G4FermiFragmentsPoolVI::GetMaxZ () const inline
Definition at line 104 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 104 of file G4FermiFragmentsPoolVI.hh
References maxZ.
G4double G4FermiFragmentsPoolVI::GetTolerance () const inline
Definition at line 125 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 125 of file G4FermiFragmentsPoolVI.hh
References tolerance.
G4bool G4FermiFragmentsPoolVI::HasChannels (G4int Z, G4int A, G4double exc) const
Definition at line 117 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 117 of file G4FermiFragmentsPoolVI.cc
References A(), G4FermiFragment::GetExcitationEnergy(), G4FermiFragment::GetZ(), list_c, list_f, and Z.
Referenced by DumpFragment(), and G4FermiBreakUpVI::IsApplicable().
void G4FermiFragmentsPoolVI::Initialise () private
Definition at line 142 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 142 of file G4FermiFragmentsPoolVI.cc
References A(), G4FermiDecayProbability::ComputeProbability(), e1, e2, elim, elimf, f, f1, f2, f3, fragment_pool, G4FermiFragment::GetA(), G4FermiChannels::GetChannels(), G4FermiFragment::GetCoulombBarrier(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetLevelManager(), G4NuclearLevelData::GetMaxA(), G4NuclearLevelData::GetMinA(), G4NucleiProperties::GetNuclearMass(), G4FermiChannels::GetNumberOfChannels(), G4FermiChannels::GetProbabilities(), G4FermiFragment::GetSpin(), G4FermiFragment::GetTotalEnergy(), G4FermiFragment::GetZ(), IsInPhysPairs(), IsInThePool(), IsPhysical(), k, G4LevelManager::LevelEnergy(), G4LevelManager::LifeTime(), list_c, list_f, list_p, maxA, G4NuclearLevelData::MaxLevelEnergy(), maxZ, min, minE, G4InuclParticleNames::nn, G4LevelManager::NumberOfTransitions(), G4LevelManager::SpinTwo(), theDecay, tolerance, Z, Z1, and Z2.
Referenced by G4FermiFragmentsPoolVI().
G4bool G4FermiFragmentsPoolVI::IsInPhysPairs (const G4FermiFragment * f1, const G4FermiFragment * f2) const private
Definition at line 130 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 130 of file G4FermiFragmentsPoolVI.cc
References A(), G4FermiFragment::GetA(), and list_p.
Referenced by Initialise().
G4bool G4FermiFragmentsPoolVI::IsInThePool (G4int Z, G4int A, G4double exc) const private
Definition at line 105 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 105 of file G4FermiFragmentsPoolVI.cc
References kdfinder::abs(), fragment_pool, and tolerance.
Referenced by Initialise().
G4bool G4FermiFragmentsPoolVI::IsInUnphysPairs (const G4FermiFragment * f1, const G4FermiFragment * f2) const private
G4bool G4FermiFragmentsPoolVI::IsPhysical (G4int Z, G4int A) const
Definition at line 97 of file G4FermiFragmentsPoolVI.cc.
View newest version in sPHENIX GitHub at line 97 of file G4FermiFragmentsPoolVI.cc
References list_f, and Z.
Referenced by Initialise().
Member Data Documentation
G4double G4FermiFragmentsPoolVI::elim private
Definition at line 86 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 86 of file G4FermiFragmentsPoolVI.hh
Referenced by Dump(), G4FermiFragmentsPoolVI(), GetEnergyLimit(), and Initialise().
G4float G4FermiFragmentsPoolVI::elimf private
Definition at line 89 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 89 of file G4FermiFragmentsPoolVI.hh
Referenced by G4FermiFragmentsPoolVI(), and Initialise().
std::vector<const G4FermiFragment*> G4FermiFragmentsPoolVI::fragment_pool private
Definition at line 94 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 94 of file G4FermiFragmentsPoolVI.hh
Referenced by Dump(), G4FermiFragmentsPoolVI(), Initialise(), IsInThePool(), and ~G4FermiFragmentsPoolVI().
std::vector<G4FermiChannels*> G4FermiFragmentsPoolVI::list_c[maxA] private
Definition at line 99 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 99 of file G4FermiFragmentsPoolVI.hh
Referenced by ClosestChannels(), Dump(), HasChannels(), Initialise(), and ~G4FermiFragmentsPoolVI().
std::vector<const G4FermiFragment*> G4FermiFragmentsPoolVI::list_f[maxA] private
Definition at line 97 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 97 of file G4FermiFragmentsPoolVI.hh
Referenced by ClosestChannels(), Dump(), HasChannels(), Initialise(), and IsPhysical().
std::vector<const G4FermiPair*> G4FermiFragmentsPoolVI::list_p[maxA] private
Definition at line 101 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 101 of file G4FermiFragmentsPoolVI.hh
Referenced by Dump(), Initialise(), IsInPhysPairs(), and ~G4FermiFragmentsPoolVI().
G4FermiDecayProbability G4FermiFragmentsPoolVI::theDecay private
Definition at line 91 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 91 of file G4FermiFragmentsPoolVI.hh
Referenced by FermiDecayProbability(), and Initialise().
G4float G4FermiFragmentsPoolVI::timelim private
Definition at line 88 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 88 of file G4FermiFragmentsPoolVI.hh
Referenced by G4FermiFragmentsPoolVI().
G4double G4FermiFragmentsPoolVI::tolerance private
Definition at line 85 of file G4FermiFragmentsPoolVI.hh.
View newest version in sPHENIX GitHub at line 85 of file G4FermiFragmentsPoolVI.hh
Referenced by ClosestChannels(), G4FermiFragmentsPoolVI(), GetTolerance(), Initialise(), and IsInThePool().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiFragmentsPoolVI.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/src/G4FermiFragmentsPoolVI.cc