ECCE @ EIC Software: G3PartTable Class Reference
G3PartTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3PartTable.hh>
Public Member Functions
G3PartTable ()
virtual ~G3PartTable ()
G4ParticleDefinition * Get (G4int partid)
void Put (G4int partid, G4ParticleDefinition *partpt)
void PrintAll ()
Private Member Functions
void HashID (G4int partid, G4String *_HID)
void HashID (G4int partid, G4String &_HID)
Private Attributes
std::map< G4String,
G4ParticleDefinition
*, std::less< G4String > > PTD
Detailed Description
Definition at line 42 of file G3PartTable.hh.
View newest version in sPHENIX GitHub at line 42 of file G3PartTable.hh
Constructor & Destructor Documentation
G3PartTable::G3PartTable ()
Definition at line 37 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 37 of file G3PartTable.cc
G3PartTable::~G3PartTable () virtual
Definition at line 40 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 40 of file G3PartTable.cc
References PTD.
Member Function Documentation
G4ParticleDefinition * G3PartTable::Get (G4int partid)
Definition at line 51 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 51 of file G3PartTable.cc
References HashID(), and PTD.
void G3PartTable::HashID (G4int partid, G4String * _HID) private
Definition at line 73 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 73 of file G3PartTable.cc
Referenced by Get(), and Put().
void G3PartTable::HashID (G4int partid, G4String & _HID) private
Definition at line 66 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 66 of file G3PartTable.cc
void G3PartTable::PrintAll (void)
Definition at line 78 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 78 of file G3PartTable.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), and PTD.
Referenced by G4BuildGeom().
void G3PartTable::Put (G4int partid, G4ParticleDefinition * partpt)
Definition at line 59 of file G3PartTable.cc.
View newest version in sPHENIX GitHub at line 59 of file G3PartTable.cc
References HashID(), and PTD.
Member Data Documentation
std::map<G4String, G4ParticleDefinition*, std::less<G4String> > G3PartTable::PTD private
Definition at line 55 of file G3PartTable.hh.
View newest version in sPHENIX GitHub at line 55 of file G3PartTable.hh
Referenced by Get(), PrintAll(), Put(), and ~G3PartTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3PartTable.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3PartTable.cc