ECCE @ EIC Software: B1Run Class Reference
B1Run Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1Run.hh>
Public Member Functions
B1Run ()
virtual ~B1Run ()
virtual void Merge (const G4Run *)
virtual void AddEdep (G4double edep)
G4double GetEdep () const
G4double GetEdep2 () const
B1Run ()
virtual ~B1Run ()
virtual void Merge (const G4Run *)
void AddEdep (G4double edep)
G4double GetEdep () const
G4double GetEdep2 () const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
virtual void RecordEvent (const G4Event *)
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
G4double fEdep
G4double fEdep2
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Run class
Definition at line 41 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 41 of file B1Run.hh
Constructor & Destructor Documentation
B1Run::B1Run ()
Definition at line 34 of file B1Run.cc.
View newest version in sPHENIX GitHub at line 34 of file B1Run.cc
B1Run::~B1Run () virtual
Definition at line 42 of file B1Run.cc.
View newest version in sPHENIX GitHub at line 42 of file B1Run.cc
B1Run::B1Run ()
virtual B1Run::~B1Run () virtual
Member Function Documentation
void B1Run::AddEdep (G4double edep) virtual
Reimplemented in B1ConRun.
Definition at line 58 of file B1Run.cc.
View newest version in sPHENIX GitHub at line 58 of file B1Run.cc
References edep, fEdep, and fEdep2.
Referenced by B1ConRun::AddEdep().
void B1Run::AddEdep (G4double edep)
G4double B1Run::GetEdep () const inline
Definition at line 53 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 53 of file B1Run.hh
References fEdep.
G4double B1Run::GetEdep () const inline
Definition at line 53 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 53 of file B1Run.hh
References fEdep.
Referenced by B1ConRunAction::EndOfRunAction().
G4double B1Run::GetEdep2 () const inline
Definition at line 54 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 54 of file B1Run.hh
References fEdep2.
Referenced by B1ConRunAction::EndOfRunAction().
G4double B1Run::GetEdep2 () const inline
Definition at line 54 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 54 of file B1Run.hh
References fEdep2.
void B1Run::Merge (const G4Run * run) virtual
Reimplemented from G4Run.
Reimplemented in B1ConRun.
Definition at line 47 of file B1Run.cc.
View newest version in sPHENIX GitHub at line 47 of file B1Run.cc
References fEdep, fEdep2, and G4Run::Merge().
Referenced by B1ConRun::Merge().
virtual void B1Run::Merge (const G4Run *) virtual
Reimplemented from G4Run.
Reimplemented in B1ConRun.
Member Data Documentation
G4double B1Run::fEdep private
Definition at line 57 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 57 of file B1Run.hh
Referenced by AddEdep(), GetEdep(), and Merge().
G4double B1Run::fEdep2 private
Definition at line 58 of file B1Run.hh.
View newest version in sPHENIX GitHub at line 58 of file B1Run.hh
Referenced by AddEdep(), GetEdep2(), and Merge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1Run.hh
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/include/B1Run.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/src/B1Run.cc
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/src/B1Run.cc