ECCE @ EIC Software: G4RDEMDataSet Class Reference
G4RDEMDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDEMDataSet.hh>
Public Member Functions
G4RDEMDataSet (G4int argZ, G4RDVDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
G4RDEMDataSet (G4int argZ, G4DataVector *xData, G4DataVector *data, G4RDVDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
virtual ~G4RDEMDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4RDVEMDataSet * GetComponent (G4int) const
virtual void AddComponent (G4RDVEMDataSet *)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int) const
virtual const G4DataVector & GetData (G4int) const
virtual void SetEnergiesData (G4DataVector *xData, G4DataVector *data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int componentId=0) const
Public Member Functions inherited from G4RDVEMDataSet
G4RDVEMDataSet ()
virtual ~G4RDVEMDataSet ()
Private Member Functions
size_t FindLowerBound (G4double energy) const
size_t FindLowerBound (G4double x, G4DataVector *values) const
G4double IntegrationFunction (G4double x)
virtual void BuildPdf ()
G4String FullFileName (const G4String &fileName) const
G4RDEMDataSet ()
G4RDEMDataSet (const G4RDEMDataSet &copy)
G4RDEMDataSet & operator= (const G4RDEMDataSet &right)
Private Attributes
G4int z
G4DataVector * energies
G4DataVector * data
G4RDVDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
G4DataVector * pdf
G4bool randomSet
Detailed Description
Definition at line 54 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RDEMDataSet.hh
Constructor & Destructor Documentation
G4RDEMDataSet::G4RDEMDataSet (G4int argZ, G4RDVDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 45 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 45 of file G4RDEMDataSet.cc
References algorithm, BuildPdf(), FatalException, G4Exception(), and randomSet.
G4RDEMDataSet::G4RDEMDataSet (G4int argZ, G4DataVector * xData, G4DataVector * data, G4RDVDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 65 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 65 of file G4RDEMDataSet.cc
References algorithm, BuildPdf(), energies, FatalException, G4Exception(), and randomSet.
G4RDEMDataSet::~G4RDEMDataSet () virtual
Definition at line 98 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 98 of file G4RDEMDataSet.cc
References algorithm, data, energies, and pdf.
G4RDEMDataSet::G4RDEMDataSet () private
G4RDEMDataSet::G4RDEMDataSet (const G4RDEMDataSet & copy) private
Member Function Documentation
virtual void G4RDEMDataSet::AddComponent (G4RDVEMDataSet *) inline virtual
Implements G4RDVEMDataSet.
Definition at line 79 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RDEMDataSet.hh
void G4RDEMDataSet::BuildPdf () private virtual
Definition at line 327 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 327 of file G4RDEMDataSet.cc
References IntegrationFunction(), G4Integrator< T, F >::Legendre96(), pdf, and sum.
Referenced by G4RDEMDataSet(), and LoadData().
size_t G4RDEMDataSet::FindLowerBound (G4double energy) const private
Definition at line 279 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 279 of file G4RDEMDataSet.cc
References energies.
Referenced by FindValue(), IntegrationFunction(), and RandomSelect().
size_t G4RDEMDataSet::FindLowerBound (G4double x, G4DataVector * values) const private
Definition at line 296 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 296 of file G4RDEMDataSet.cc
G4double G4RDEMDataSet::FindValue (G4double x, G4int componentId = 0) const virtual
Implements G4RDVEMDataSet.
Definition at line 106 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 106 of file G4RDEMDataSet.cc
References algorithm, G4RDVDataSetAlgorithm::Calculate(), energies, FatalException, FindLowerBound(), and G4Exception().
G4String G4RDEMDataSet::FullFileName (const G4String & fileName) const private
Definition at line 313 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 313 of file G4RDEMDataSet.cc
References FatalException, G4Exception(), and z.
Referenced by LoadData(), and SaveData().
virtual const G4RDVEMDataSet* G4RDEMDataSet::GetComponent (G4int) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 77 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RDEMDataSet.hh
virtual const G4DataVector& G4RDEMDataSet::GetData (G4int) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 84 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RDEMDataSet.hh
References data.
virtual const G4DataVector& G4RDEMDataSet::GetEnergies (G4int) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 83 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RDEMDataSet.hh
References energies.
G4double G4RDEMDataSet::IntegrationFunction (G4double x) private
Definition at line 383 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 383 of file G4RDEMDataSet.cc
References algorithm, bin, G4RDVDataSetAlgorithm::Calculate(), G4RDLinInterpolation::Calculate(), energies, FindLowerBound(), and y.
Referenced by BuildPdf().
G4bool G4RDEMDataSet::LoadData (const G4String & fileName) virtual
Implements G4RDVEMDataSet.
Definition at line 162 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 162 of file G4RDEMDataSet.cc
References a, BuildPdf(), FatalException, FullFileName(), G4Exception(), in, message(), randomSet, SetEnergiesData(), unitData, and unitEnergies.
virtual size_t G4RDEMDataSet::NumberOfComponents (void) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 81 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RDEMDataSet.hh
G4RDEMDataSet& G4RDEMDataSet::operator= (const G4RDEMDataSet & right) private
void G4RDEMDataSet::PrintData (void) const virtual
Implements G4RDVEMDataSet.
Definition at line 121 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 121 of file G4RDEMDataSet.cc
References energies, G4cout, G4endl, pdf, unitData, and unitEnergies.
G4double G4RDEMDataSet::RandomSelect (G4int componentId = 0) const virtual
Implements G4RDVEMDataSet.
Definition at line 357 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 357 of file G4RDEMDataSet.cc
References algorithm, bin, G4RDVDataSetAlgorithm::Calculate(), G4RDLinInterpolation::Calculate(), energies, FatalException, FindLowerBound(), G4Exception(), G4UniformRand, pdf, and x.
G4bool G4RDEMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4RDVEMDataSet.
Definition at line 209 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 209 of file G4RDEMDataSet.cc
References energies, FatalException, FullFileName(), G4Exception(), left, message(), unitData, and unitEnergies.
void G4RDEMDataSet::SetEnergiesData (G4DataVector * xData, G4DataVector * data, G4int componentId) virtual
Implements G4RDVEMDataSet.
Definition at line 141 of file G4RDEMDataSet.cc.
View newest version in sPHENIX GitHub at line 141 of file G4RDEMDataSet.cc
References data, energies, FatalException, and G4Exception().
Referenced by LoadData().
Member Data Documentation
G4RDVDataSetAlgorithm* G4RDEMDataSet::algorithm private
Definition at line 114 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RDEMDataSet.hh
Referenced by FindValue(), G4RDEMDataSet(), IntegrationFunction(), RandomSelect(), and ~G4RDEMDataSet().
G4DataVector* G4RDEMDataSet::data private
Definition at line 112 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 112 of file G4RDEMDataSet.hh
Referenced by GetData(), SetEnergiesData(), and ~G4RDEMDataSet().
G4DataVector* G4RDEMDataSet::energies private
Definition at line 111 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RDEMDataSet.hh
Referenced by FindLowerBound(), FindValue(), G4RDEMDataSet(), GetEnergies(), IntegrationFunction(), PrintData(), RandomSelect(), SaveData(), SetEnergiesData(), and ~G4RDEMDataSet().
G4DataVector* G4RDEMDataSet::pdf private
Definition at line 119 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 119 of file G4RDEMDataSet.hh
Referenced by BuildPdf(), PrintData(), RandomSelect(), and ~G4RDEMDataSet().
G4bool G4RDEMDataSet::randomSet private
Definition at line 120 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 120 of file G4RDEMDataSet.hh
Referenced by G4RDEMDataSet(), and LoadData().
G4double G4RDEMDataSet::unitData private
Definition at line 117 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 117 of file G4RDEMDataSet.hh
Referenced by LoadData(), PrintData(), and SaveData().
G4double G4RDEMDataSet::unitEnergies private
Definition at line 116 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 116 of file G4RDEMDataSet.hh
Referenced by LoadData(), PrintData(), and SaveData().
G4int G4RDEMDataSet::z private
Definition at line 109 of file G4RDEMDataSet.hh.
View newest version in sPHENIX GitHub at line 109 of file G4RDEMDataSet.hh
Referenced by FullFileName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDEMDataSet.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDEMDataSet.cc