ECCE @ EIC Software: G4RDShellEMDataSet Class Reference
G4RDShellEMDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDShellEMDataSet.hh>
Public Member Functions
G4RDShellEMDataSet (G4int Z, G4RDVDataSetAlgorithm *algo, G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4RDShellEMDataSet ()
virtual G4double FindValue (G4double energy, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4RDVEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4RDVEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *energies, G4DataVector *data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4RDVEMDataSet
G4RDVEMDataSet ()
virtual ~G4RDVEMDataSet ()
Protected Member Functions
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4RDVDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Member Functions
G4String FullFileName (const G4String &fileName) const
G4RDShellEMDataSet ()
G4RDShellEMDataSet (const G4RDShellEMDataSet &copy)
G4RDShellEMDataSet & operator= (const G4RDShellEMDataSet &right)
Private Attributes
std::vector< G4RDVEMDataSet * > components
G4int z
G4RDVDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 57 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 57 of file G4RDShellEMDataSet.hh
Constructor & Destructor Documentation
G4RDShellEMDataSet::G4RDShellEMDataSet (G4int Z, G4RDVDataSetAlgorithm * algo, G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 46 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 46 of file G4RDShellEMDataSet.cc
References algorithm, FatalException, and G4Exception().
G4RDShellEMDataSet::~G4RDShellEMDataSet () virtual
Definition at line 61 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 61 of file G4RDShellEMDataSet.cc
References algorithm, and CleanUpComponents().
G4RDShellEMDataSet::G4RDShellEMDataSet () private
G4RDShellEMDataSet::G4RDShellEMDataSet (const G4RDShellEMDataSet & copy) private
Member Function Documentation
virtual void G4RDShellEMDataSet::AddComponent (G4RDVEMDataSet * dataSet) inline virtual
Implements G4RDVEMDataSet.
Definition at line 72 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 72 of file G4RDShellEMDataSet.hh
References components.
Referenced by LoadData().
void G4RDShellEMDataSet::CleanUpComponents (void) protected
Definition at line 257 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 257 of file G4RDShellEMDataSet.cc
References components.
Referenced by LoadData(), and ~G4RDShellEMDataSet().
G4double G4RDShellEMDataSet::FindValue (G4double energy, G4int componentId = 0) const virtual
Implements G4RDVEMDataSet.
Definition at line 68 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 68 of file G4RDShellEMDataSet.cc
References components.
G4String G4RDShellEMDataSet::FullFileName (const G4String & fileName) const private
Definition at line 267 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 267 of file G4RDShellEMDataSet.cc
References FatalException, G4Exception(), and z.
Referenced by LoadData(), and SaveData().
const G4RDVDataSetAlgorithm* G4RDShellEMDataSet::GetAlgorithm () const inline protected
Definition at line 88 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RDShellEMDataSet.hh
References algorithm.
virtual const G4RDVEMDataSet* G4RDShellEMDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 71 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RDShellEMDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), PrintData(), and SaveData().
virtual const G4DataVector& G4RDShellEMDataSet::GetData (G4int componentId) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 76 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RDShellEMDataSet.hh
References GetComponent(), and G4RDVEMDataSet::GetData().
virtual const G4DataVector& G4RDShellEMDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 75 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RDShellEMDataSet.hh
References GetComponent(), and G4RDVEMDataSet::GetEnergies().
G4double G4RDShellEMDataSet::GetUnitData () const inline protected
Definition at line 87 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 87 of file G4RDShellEMDataSet.hh
References unitData.
G4double G4RDShellEMDataSet::GetUnitEnergies () const inline protected
Definition at line 86 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RDShellEMDataSet.hh
References unitEnergies.
G4bool G4RDShellEMDataSet::LoadData (const G4String & fileName) virtual
Implements G4RDVEMDataSet.
Definition at line 124 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 124 of file G4RDShellEMDataSet.cc
References a, AddComponent(), algorithm, CleanUpComponents(), G4RDVDataSetAlgorithm::Clone(), FatalException, FullFileName(), G4Exception(), in, message(), unitData, and unitEnergies.
virtual size_t G4RDShellEMDataSet::NumberOfComponents (void) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 73 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 73 of file G4RDShellEMDataSet.hh
References components.
Referenced by PrintData(), and SaveData().
G4RDShellEMDataSet& G4RDShellEMDataSet::operator= (const G4RDShellEMDataSet & right) private
void G4RDShellEMDataSet::PrintData (void) const virtual
Implements G4RDVEMDataSet.
Definition at line 86 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 86 of file G4RDShellEMDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4RDVEMDataSet::PrintData().
virtual G4double G4RDShellEMDataSet::RandomSelect (G4int) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 82 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RDShellEMDataSet.hh
G4bool G4RDShellEMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4RDVEMDataSet.
Definition at line 184 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 184 of file G4RDShellEMDataSet.cc
References FatalException, FullFileName(), G4Exception(), GetComponent(), G4RDVEMDataSet::GetData(), G4RDVEMDataSet::GetEnergies(), k, left, message(), n, NumberOfComponents(), unitData, and unitEnergies.
void G4RDShellEMDataSet::SetEnergiesData (G4DataVector * energies, G4DataVector * data, G4int componentId) virtual
Implements G4RDVEMDataSet.
Definition at line 104 of file G4RDShellEMDataSet.cc.
View newest version in sPHENIX GitHub at line 104 of file G4RDShellEMDataSet.cc
References components, FatalException, G4Exception(), message(), and G4RDVEMDataSet::SetEnergiesData().
Member Data Documentation
G4RDVDataSetAlgorithm* G4RDShellEMDataSet::algorithm private
Definition at line 105 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 105 of file G4RDShellEMDataSet.hh
Referenced by G4RDShellEMDataSet(), GetAlgorithm(), LoadData(), and ~G4RDShellEMDataSet().
std::vector<G4RDVEMDataSet*> G4RDShellEMDataSet::components private
Definition at line 101 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 101 of file G4RDShellEMDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), and SetEnergiesData().
G4double G4RDShellEMDataSet::unitData private
Definition at line 108 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4RDShellEMDataSet.hh
Referenced by GetUnitData(), LoadData(), and SaveData().
G4double G4RDShellEMDataSet::unitEnergies private
Definition at line 107 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 107 of file G4RDShellEMDataSet.hh
Referenced by GetUnitEnergies(), LoadData(), and SaveData().
G4int G4RDShellEMDataSet::z private
Definition at line 103 of file G4RDShellEMDataSet.hh.
View newest version in sPHENIX GitHub at line 103 of file G4RDShellEMDataSet.hh
Referenced by FullFileName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDShellEMDataSet.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDShellEMDataSet.cc