ECCE @ EIC Software: G4SigmaMinusField Class Reference
G4SigmaMinusField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4SigmaMinusField.hh>
Public Member Functions
G4SigmaMinusField (G4V3DNucleus *nucleus, G4double coeff=0.36 *CLHEP::fermi)
virtual ~G4SigmaMinusField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
virtual G4double GetCoeff ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
Private Member Functions
G4SigmaMinusField (const G4SigmaMinusField &right)
const G4SigmaMinusField & operator= (const G4SigmaMinusField &right)
G4bool operator== (const G4SigmaMinusField &right) const
G4bool operator!= (const G4SigmaMinusField &right) const
Private Attributes
G4double theCoeff
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 46 of file G4SigmaMinusField.hh.
View newest version in sPHENIX GitHub at line 46 of file G4SigmaMinusField.hh
Constructor & Destructor Documentation
G4SigmaMinusField::G4SigmaMinusField (G4V3DNucleus * nucleus, G4double coeff = 0.36*CLHEP::fermi)
Definition at line 49 of file G4SigmaMinusField.cc.
View newest version in sPHENIX GitHub at line 49 of file G4SigmaMinusField.cc
References theCoeff.
G4SigmaMinusField::~G4SigmaMinusField () virtual
Definition at line 55 of file G4SigmaMinusField.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SigmaMinusField.cc
G4SigmaMinusField::G4SigmaMinusField (const G4SigmaMinusField & right) private
Member Function Documentation
G4double G4SigmaMinusField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 77 of file G4SigmaMinusField.cc.
View newest version in sPHENIX GitHub at line 77 of file G4SigmaMinusField.cc
References A(), G4Pow::A13(), G4V3DNucleus::GetCharge(), G4Pow::GetInstance(), G4V3DNucleus::GetMassNumber(), MeV, G4VNuclearField::theNucleus, and Z.
Referenced by GetField().
virtual G4double G4SigmaMinusField::GetCoeff () inline virtual
Reimplemented from G4VNuclearField.
Definition at line 61 of file G4SigmaMinusField.hh.
View newest version in sPHENIX GitHub at line 61 of file G4SigmaMinusField.hh
References theCoeff.
G4double G4SigmaMinusField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 58 of file G4SigmaMinusField.cc.
View newest version in sPHENIX GitHub at line 58 of file G4SigmaMinusField.cc
References A(), G4InuclSpecialFunctions::bindingEnergy(), GetBarrier(), G4NucleiProperties::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4VNuclearDensity::GetDensity(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, CLHEP::Hep3Vector::mag(), source.hepunit::neutron_mass_c2, pi, source.hepunit::proton_mass_c2, G4VNuclearField::radius, G4SigmaMinus::SigmaMinus(), theCoeff, G4VNuclearField::theNucleus, and Z.
G4bool G4SigmaMinusField::operator!= (const G4SigmaMinusField & right) const private
const G4SigmaMinusField& G4SigmaMinusField::operator= (const G4SigmaMinusField & right) private
G4bool G4SigmaMinusField::operator== (const G4SigmaMinusField & right) const private
Member Data Documentation
G4double G4SigmaMinusField::theCoeff private
Definition at line 64 of file G4SigmaMinusField.hh.
View newest version in sPHENIX GitHub at line 64 of file G4SigmaMinusField.hh
Referenced by G4SigmaMinusField(), GetCoeff(), and GetField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4SigmaMinusField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4SigmaMinusField.cc