ECCE @ EIC Software: G4AdjointPrimaryGeneratorAction Class Reference
G4AdjointPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4AdjointPrimaryGeneratorAction.hh>
Public Member Functions
G4AdjointPrimaryGeneratorAction ()
~G4AdjointPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
void SetRndmFlag (const G4String &val)
void SetEmin (G4double val)
void SetEmax (G4double val)
void SetEminIon (G4double val)
void SetEmaxIon (G4double val)
void SetSphericalAdjointPrimarySource (G4double radius, G4ThreeVector pos)
void SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume (const G4String &volume_name)
void ConsiderParticleAsPrimary (const G4String &particle_name)
void NeglectParticleAsPrimary (const G4String &particle_name)
void SetPrimaryIon (G4ParticleDefinition *adjointIon, G4ParticleDefinition *fwdIon)
void UpdateListOfPrimaryParticles ()
size_t GetNbOfAdjointPrimaryTypes ()
std::vector
< G4ParticleDefinition * > * GetListOfPrimaryFwdParticles ()
const G4String & GetPrimaryIonName ()
void SetNbPrimaryFwdGammasPerEvent (G4int nb)
void SetNbAdjointPrimaryGammasPerEvent (G4int nb)
void SetNbAdjointPrimaryElectronsPerEvent (G4int nb)
G4ParticleDefinition * GetLastGeneratedFwdPrimaryParticle ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Member Functions
G4double ComputeEnergyDistWeight (G4double energy, G4double E1, G4double E2)
G4AdjointPrimaryGeneratorAction (const G4AdjointPrimaryGeneratorAction &)
G4AdjointPrimaryGeneratorAction & operator= (const G4AdjointPrimaryGeneratorAction &)
Private Attributes
G4String rndmFlag
G4AdjointPrimaryGenerator * theAdjointPrimaryGenerator
G4double Emin
G4double Emax
G4double EminIon
G4double EmaxIon
std::vector
< G4ParticleDefinition * > ListOfPrimaryFwdParticles
std::vector
< G4ParticleDefinition * > ListOfPrimaryAdjParticles
std::map< G4String, G4bool > PrimariesConsideredInAdjointSim
size_t index_particle
G4ThreeVector pos
G4ThreeVector direction
G4ThreeVector p
G4String type_of_adjoint_source
G4double radius_spherical_source
G4ThreeVector center_spherical_source
G4int nb_fwd_gammas_per_event
G4int nb_adj_primary_gammas_per_event
G4int nb_adj_primary_electrons_per_event
G4ParticleDefinition * fwd_ion
G4ParticleDefinition * adj_ion
G4String ion_name
Detailed Description
Definition at line 77 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
G4AdjointPrimaryGeneratorAction::G4AdjointPrimaryGeneratorAction ()
Definition at line 48 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 48 of file G4AdjointPrimaryGeneratorAction.cc
References ListOfPrimaryAdjParticles, ListOfPrimaryFwdParticles, nb_adj_primary_electrons_per_event, nb_adj_primary_gammas_per_event, nb_fwd_gammas_per_event, PrimariesConsideredInAdjointSim, and theAdjointPrimaryGenerator.
G4AdjointPrimaryGeneratorAction::~G4AdjointPrimaryGeneratorAction ()
Definition at line 70 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 70 of file G4AdjointPrimaryGeneratorAction.cc
References theAdjointPrimaryGenerator.
G4AdjointPrimaryGeneratorAction::G4AdjointPrimaryGeneratorAction (const G4AdjointPrimaryGeneratorAction &) private
Member Function Documentation
G4double G4AdjointPrimaryGeneratorAction::ComputeEnergyDistWeight (G4double energy, G4double E1, G4double E2) private
Definition at line 276 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 276 of file G4AdjointPrimaryGeneratorAction.cc
References G4AdjointSimManager::GetInstance(), and G4AdjointSimManager::GetNbEvtOfLastRun().
Referenced by GeneratePrimaries().
void G4AdjointPrimaryGeneratorAction::ConsiderParticleAsPrimary (const G4String & particle_name)
Definition at line 312 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 312 of file G4AdjointPrimaryGeneratorAction.cc
References PrimariesConsideredInAdjointSim, and UpdateListOfPrimaryParticles().
Referenced by G4AdjointSimManager::ConsiderParticleAsPrimary().
void G4AdjointPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 76 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 76 of file G4AdjointPrimaryGeneratorAction.cc
References A(), G4Event::AddPrimaryVertex(), G4AdjointSimManager::ClearEndOfAdjointTrackInfoVectors(), ComputeEnergyDistWeight(), dir, Emax, EmaxIon, Emin, EminIon, G4Gamma::Gamma(), G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex(), G4AdjointSimManager::GetAdjointSourceArea(), G4Event::GetEventID(), G4AdjointSimManager::GetInstance(), G4PrimaryParticle::GetMomentum(), G4PrimaryVertex::GetPosition(), G4PrimaryVertex::GetPrimary(), G4Event::GetPrimaryVertex(), index_particle, ListOfPrimaryAdjParticles, ListOfPrimaryFwdParticles, CLHEP::Hep3Vector::mag(), n, nb_adj_primary_electrons_per_event, nb_adj_primary_gammas_per_event, nb_fwd_gammas_per_event, pi, pos, G4AdjointSimManager::ResetDidOneAdjPartReachExtSourceDuringEvent(), G4AdjointSimManager::SetAdjointTrackingMode(), G4PrimaryVertex::SetPosition(), G4PrimaryVertex::SetPrimary(), G4PrimaryVertex::SetT0(), G4PrimaryVertex::SetWeight(), theAdjointPrimaryGenerator, UpdateListOfPrimaryParticles(), weight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4ParticleDefinition* G4AdjointPrimaryGeneratorAction::GetLastGeneratedFwdPrimaryParticle () inline
Definition at line 105 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AdjointPrimaryGeneratorAction.hh
References index_particle, and ListOfPrimaryFwdParticles.
Referenced by G4AdjointSimManager::GetLastGeneratedFwdPrimaryParticle().
std::vector<G4ParticleDefinition*>* G4AdjointPrimaryGeneratorAction::GetListOfPrimaryFwdParticles () inline
Definition at line 99 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AdjointPrimaryGeneratorAction.hh
References ListOfPrimaryFwdParticles.
Referenced by G4AdjointSimManager::G4AdjointSimManager(), G4AdjointSimManager::GetListOfPrimaryFwdParticles(), G4AdjointSimManager::GetNbOfPrimaryFwdParticles(), and G4AdjointSimManager::RegisterAtEndOfAdjointTrack().
size_t G4AdjointPrimaryGeneratorAction::GetNbOfAdjointPrimaryTypes () inline
Definition at line 98 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AdjointPrimaryGeneratorAction.hh
References ListOfPrimaryAdjParticles.
Referenced by G4AdjointSimManager::RunAdjointSimulation().
const G4String& G4AdjointPrimaryGeneratorAction::GetPrimaryIonName () inline
Definition at line 101 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AdjointPrimaryGeneratorAction.hh
References ion_name.
Referenced by G4AdjointSimManager::GetPrimaryIonName().
void G4AdjointPrimaryGeneratorAction::NeglectParticleAsPrimary (const G4String & particle_name)
Definition at line 321 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 321 of file G4AdjointPrimaryGeneratorAction.cc
References PrimariesConsideredInAdjointSim, and UpdateListOfPrimaryParticles().
Referenced by G4AdjointSimManager::NeglectParticleAsPrimary().
G4AdjointPrimaryGeneratorAction& G4AdjointPrimaryGeneratorAction::operator= (const G4AdjointPrimaryGeneratorAction &) private
void G4AdjointPrimaryGeneratorAction::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume (const G4String & volume_name)
Definition at line 305 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 305 of file G4AdjointPrimaryGeneratorAction.cc
References G4AdjointPrimaryGenerator::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), theAdjointPrimaryGenerator, and type_of_adjoint_source.
Referenced by G4AdjointSimManager::DefineAdjointSourceOnTheExtSurfaceOfAVolume().
void G4AdjointPrimaryGeneratorAction::SetEmax (G4double val)
Definition at line 257 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 257 of file G4AdjointPrimaryGeneratorAction.cc
References Emax, and EmaxIon.
Referenced by G4AdjointSimManager::SetAdjointSourceEmax().
void G4AdjointPrimaryGeneratorAction::SetEmaxIon (G4double val)
Definition at line 270 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 270 of file G4AdjointPrimaryGeneratorAction.cc
References EmaxIon.
void G4AdjointPrimaryGeneratorAction::SetEmin (G4double val)
Definition at line 250 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 250 of file G4AdjointPrimaryGeneratorAction.cc
References Emin, and EminIon.
Referenced by G4AdjointSimManager::SetAdjointSourceEmin().
void G4AdjointPrimaryGeneratorAction::SetEminIon (G4double val)
Definition at line 264 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 264 of file G4AdjointPrimaryGeneratorAction.cc
References EminIon.
void G4AdjointPrimaryGeneratorAction::SetNbAdjointPrimaryElectronsPerEvent (G4int nb) inline
Definition at line 104 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointPrimaryGeneratorAction.hh
References nb_adj_primary_electrons_per_event.
Referenced by G4AdjointSimManager::SetNbAdjointPrimaryElectronsPerEvent().
void G4AdjointPrimaryGeneratorAction::SetNbAdjointPrimaryGammasPerEvent (G4int nb) inline
Definition at line 103 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AdjointPrimaryGeneratorAction.hh
References nb_adj_primary_gammas_per_event.
Referenced by G4AdjointSimManager::SetNbAdjointPrimaryGammasPerEvent().
void G4AdjointPrimaryGeneratorAction::SetNbPrimaryFwdGammasPerEvent (G4int nb) inline
Definition at line 102 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AdjointPrimaryGeneratorAction.hh
References nb_fwd_gammas_per_event.
Referenced by G4AdjointSimManager::SetNbOfPrimaryFwdGammasPerEvent().
void G4AdjointPrimaryGeneratorAction::SetPrimaryIon (G4ParticleDefinition * adjointIon, G4ParticleDefinition * fwdIon)
Definition at line 370 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 370 of file G4AdjointPrimaryGeneratorAction.cc
References adj_ion, fwd_ion, and UpdateListOfPrimaryParticles().
Referenced by G4AdjointSimManager::SetPrimaryIon().
void G4AdjointPrimaryGeneratorAction::SetRndmFlag (const G4String & val) inline
Definition at line 87 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 87 of file G4AdjointPrimaryGeneratorAction.hh
References rndmFlag.
void G4AdjointPrimaryGeneratorAction::SetSphericalAdjointPrimarySource (G4double radius, G4ThreeVector pos)
Definition at line 296 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 296 of file G4AdjointPrimaryGeneratorAction.cc
References center_spherical_source, radius, radius_spherical_source, G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource(), theAdjointPrimaryGenerator, and type_of_adjoint_source.
Referenced by G4AdjointSimManager::DefineSphericalAdjointSource(), and G4AdjointSimManager::DefineSphericalAdjointSourceWithCentreAtTheCentreOfAVolume().
void G4AdjointPrimaryGeneratorAction::UpdateListOfPrimaryParticles ()
Definition at line 330 of file G4AdjointPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 330 of file G4AdjointPrimaryGeneratorAction.cc
References adj_ion, G4ParticleTable::FindParticle(), fwd_ion, G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), ion_name, ListOfPrimaryAdjParticles, ListOfPrimaryFwdParticles, and PrimariesConsideredInAdjointSim.
Referenced by ConsiderParticleAsPrimary(), GeneratePrimaries(), NeglectParticleAsPrimary(), SetPrimaryIon(), and G4AdjointSimManager::SwitchToAdjointSimulationMode().
Member Data Documentation
G4ParticleDefinition* G4AdjointPrimaryGeneratorAction::adj_ion private
Definition at line 146 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 146 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by SetPrimaryIon(), and UpdateListOfPrimaryParticles().
G4ThreeVector G4AdjointPrimaryGeneratorAction::center_spherical_source private
Definition at line 138 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 138 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by SetSphericalAdjointPrimarySource().
G4ThreeVector G4AdjointPrimaryGeneratorAction::direction private
Definition at line 134 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 134 of file G4AdjointPrimaryGeneratorAction.hh
G4double G4AdjointPrimaryGeneratorAction::Emax private
Definition at line 121 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 121 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetEmax().
G4double G4AdjointPrimaryGeneratorAction::EmaxIon private
Definition at line 123 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 123 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), SetEmax(), and SetEmaxIon().
G4double G4AdjointPrimaryGeneratorAction::Emin private
Definition at line 120 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 120 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetEmin().
G4double G4AdjointPrimaryGeneratorAction::EminIon private
Definition at line 122 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 122 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), SetEmin(), and SetEminIon().
G4ParticleDefinition* G4AdjointPrimaryGeneratorAction::fwd_ion private
Definition at line 145 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 145 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by SetPrimaryIon(), and UpdateListOfPrimaryParticles().
size_t G4AdjointPrimaryGeneratorAction::index_particle private
Definition at line 132 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 132 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and GetLastGeneratedFwdPrimaryParticle().
G4String G4AdjointPrimaryGeneratorAction::ion_name private
Definition at line 147 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 147 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GetPrimaryIonName(), and UpdateListOfPrimaryParticles().
std::vector<G4ParticleDefinition*> G4AdjointPrimaryGeneratorAction::ListOfPrimaryAdjParticles private
Definition at line 128 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 128 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by G4AdjointPrimaryGeneratorAction(), GeneratePrimaries(), GetNbOfAdjointPrimaryTypes(), and UpdateListOfPrimaryParticles().
std::vector<G4ParticleDefinition*> G4AdjointPrimaryGeneratorAction::ListOfPrimaryFwdParticles private
Definition at line 127 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 127 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by G4AdjointPrimaryGeneratorAction(), GeneratePrimaries(), GetLastGeneratedFwdPrimaryParticle(), GetListOfPrimaryFwdParticles(), and UpdateListOfPrimaryParticles().
G4int G4AdjointPrimaryGeneratorAction::nb_adj_primary_electrons_per_event private
Definition at line 141 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 141 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by G4AdjointPrimaryGeneratorAction(), GeneratePrimaries(), and SetNbAdjointPrimaryElectronsPerEvent().
G4int G4AdjointPrimaryGeneratorAction::nb_adj_primary_gammas_per_event private
Definition at line 140 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 140 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by G4AdjointPrimaryGeneratorAction(), GeneratePrimaries(), and SetNbAdjointPrimaryGammasPerEvent().
G4int G4AdjointPrimaryGeneratorAction::nb_fwd_gammas_per_event private
Definition at line 139 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 139 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by G4AdjointPrimaryGeneratorAction(), GeneratePrimaries(), and SetNbPrimaryFwdGammasPerEvent().
G4ThreeVector G4AdjointPrimaryGeneratorAction::p private
Definition at line 134 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 134 of file G4AdjointPrimaryGeneratorAction.hh
G4ThreeVector G4AdjointPrimaryGeneratorAction::pos private
Definition at line 134 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 134 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
std::map<G4String, G4bool> G4AdjointPrimaryGeneratorAction::PrimariesConsideredInAdjointSim private
Definition at line 129 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 129 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by ConsiderParticleAsPrimary(), G4AdjointPrimaryGeneratorAction(), NeglectParticleAsPrimary(), and UpdateListOfPrimaryParticles().
G4double G4AdjointPrimaryGeneratorAction::radius_spherical_source private
Definition at line 137 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 137 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by SetSphericalAdjointPrimarySource().
G4String G4AdjointPrimaryGeneratorAction::rndmFlag private
Definition at line 113 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by SetRndmFlag().
G4AdjointPrimaryGenerator* G4AdjointPrimaryGeneratorAction::theAdjointPrimaryGenerator private
Definition at line 116 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by G4AdjointPrimaryGeneratorAction(), GeneratePrimaries(), SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), SetSphericalAdjointPrimarySource(), and ~G4AdjointPrimaryGeneratorAction().
G4String G4AdjointPrimaryGeneratorAction::type_of_adjoint_source private
Definition at line 136 of file G4AdjointPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 136 of file G4AdjointPrimaryGeneratorAction.hh
Referenced by SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), and SetSphericalAdjointPrimarySource().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4AdjointPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/source/run/src/G4AdjointPrimaryGeneratorAction.cc