ECCE @ EIC Software: G4eBremsstrahlungRelModel Class Reference
G4eBremsstrahlungRelModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4eBremsstrahlungRelModel.hh>
Classes
struct ElementData
struct LPMFuncs
Public Member Functions
G4eBremsstrahlungRelModel (const G4ParticleDefinition *p=0, const G4String &nam="eBremLPM")
virtual ~G4eBremsstrahlungRelModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double ekin, G4double cutEnergy) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double ekin, G4double zet, G4double, G4double cutEnergy, G4double maxEnergy=DBL_MAX) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double cutEnergy, G4double maxEnergy) override
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double) override
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cutEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double ComputeDXSectionPerAtom (G4double gammaEnergy)
void SetParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
G4bool fIsElectron
G4bool fIsScatOffElectron
G4bool fIsLPMActive
G4int fCurrentIZ
G4double fPrimaryParticleMass
G4double fPrimaryKinEnergy
G4double fPrimaryTotalEnergy
G4double fDensityFactor
G4double fDensityCorr
G4double fLowestKinEnergy
G4double fNucTerm
G4double fSumTerm
const G4ParticleDefinition * fPrimaryParticle
G4ParticleDefinition * fGammaParticle
G4ParticleChangeForLoss * fParticleChange
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Static Protected Attributes
static const G4double gBremFactor
static const G4double gMigdalConstant
Private Member Functions
G4double ComputeBremLoss (G4double cutEnergy)
G4double ComputeXSectionPerAtom (G4double cutEnergy)
G4double ComputeRelDXSectionPerAtom (G4double gammaEnergy)
void InitialiseElementData ()
void InitLPMFunctions ()
void ComputeLPMfunctions (G4double &funcXiS, G4double &funcGS, G4double &funcPhiS, const G4double egamma)
void GetLPMFunctions (G4double &lpmGs, G4double &lpmPhis, const G4double s)
void ComputeLPMGsPhis (G4double &funcGS, G4double &funcPhiS, const G4double varShat)
void ComputeScreeningFunctions (G4double &phi1, G4double &phi1m2, G4double &psi1, G4double &psi1m2, const G4double gam, const G4double eps)
G4eBremsstrahlungRelModel & operator= (const G4eBremsstrahlungRelModel &right)=delete
G4eBremsstrahlungRelModel (const G4eBremsstrahlungRelModel &)=delete
Private Attributes
G4bool fIsUseCompleteScreening
G4double fLPMEnergyThreshold
G4double fLPMEnergy
Static Private Attributes
static const G4int gMaxZet = 120
static const G4double gLPMconstant
static const G4double gXGL [8]
static const G4double gWGL [8]
static const G4double gFelLowZet [8]
static const G4double gFinelLowZet [8]
static LPMFuncs gLPMFuncs
static std::vector< ElementData * > gElementData
Detailed Description
Definition at line 59 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4eBremsstrahlungRelModel.hh
Constructor & Destructor Documentation
G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel (const G4ParticleDefinition * p = 0, const G4String & nam = "eBremLPM") explicit
Definition at line 116 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 116 of file G4eBremsstrahlungRelModel.cc
References fCurrentIZ, fDensityCorr, fDensityFactor, fGammaParticle, fLowestKinEnergy, fLPMEnergy, fLPMEnergyThreshold, fNucTerm, fParticleChange, fPrimaryKinEnergy, fPrimaryParticle, fPrimaryParticleMass, fPrimaryTotalEnergy, fSumTerm, G4Gamma::Gamma(), MeV, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetLowEnergyLimit(), G4VEmModel::SetLPMFlag(), and SetParticle().
G4eBremsstrahlungRelModel::~G4eBremsstrahlungRelModel () virtual
Definition at line 151 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 151 of file G4eBremsstrahlungRelModel.cc
References G4eBremsstrahlungRelModel::LPMFuncs::fIsInitialized, G4eBremsstrahlungRelModel::LPMFuncs::fLPMFuncG, G4eBremsstrahlungRelModel::LPMFuncs::fLPMFuncPhi, gElementData, gLPMFuncs, G4VEmModel::IsMaster(), and G4VEmModel::LPMFlag().
G4eBremsstrahlungRelModel::G4eBremsstrahlungRelModel (const G4eBremsstrahlungRelModel &) private delete
Member Function Documentation
G4double G4eBremsstrahlungRelModel::ComputeBremLoss (G4double cutEnergy) private
Definition at line 295 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 295 of file G4eBremsstrahlungRelModel.cc
References ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), Acts::Test::delta, fDensityCorr, fIsLPMActive, fPrimaryTotalEnergy, gWGL, gXGL, k, and max.
Referenced by ComputeDEDXPerVolume().
G4double G4eBremsstrahlungRelModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double ekin, G4double zet, G4double , G4double cutEnergy, G4double maxEnergy = DBL_MAX) override virtual
Reimplemented from G4VEmModel.
Definition at line 325 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 325 of file G4eBremsstrahlungRelModel.cc
References ComputeXSectionPerAtom(), fCurrentIZ, fPrimaryParticle, G4lrint(), gBremFactor, gMaxZet, G4VEmModel::LowEnergyLimit(), max, min, and SetParticle().
G4double G4eBremsstrahlungRelModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 241 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 241 of file G4eBremsstrahlungRelModel.cc
References ComputeBremLoss(), fCurrentIZ, fPrimaryParticle, G4lrint(), gBremFactor, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), gMaxZet, G4VEmModel::LowEnergyLimit(), max, min, G4VEmModel::SetCurrentElement(), SetParticle(), and SetupForMaterial().
G4double G4eBremsstrahlungRelModel::ComputeDXSectionPerAtom (G4double gammaEnergy) protected virtual
Reimplemented in G4SeltzerBergerModel, and G4LivermoreBremsstrahlungModel.
Definition at line 481 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 481 of file G4eBremsstrahlungRelModel.cc
References ComputeScreeningFunctions(), epsilon(), fCurrentIZ, G4eBremsstrahlungRelModel::ElementData::fEpsilonFactor, G4eBremsstrahlungRelModel::ElementData::fFz, G4eBremsstrahlungRelModel::ElementData::fGammaFactor, fIsScatOffElectron, fIsUseCompleteScreening, G4eBremsstrahlungRelModel::ElementData::fLogZ, fNucTerm, fPrimaryTotalEnergy, fSumTerm, G4eBremsstrahlungRelModel::ElementData::fZFactor1, G4eBremsstrahlungRelModel::ElementData::fZFactor11, G4eBremsstrahlungRelModel::ElementData::fZFactor2, gElementData, max, and y.
Referenced by ComputeBremLoss(), ComputeXSectionPerAtom(), and SampleSecondaries().
void G4eBremsstrahlungRelModel::ComputeLPMfunctions (G4double & funcXiS, G4double & funcGS, G4double & funcPhiS, const G4double egamma) private
Definition at line 674 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 674 of file G4eBremsstrahlungRelModel.cc
References condition(), fCurrentIZ, fDensityCorr, G4eBremsstrahlungRelModel::ElementData::fILVarS1, G4eBremsstrahlungRelModel::ElementData::fILVarS1Cond, fLPMEnergy, fPrimaryTotalEnergy, G4eBremsstrahlungRelModel::ElementData::fVarS1, G4Log(), gElementData, and GetLPMFunctions().
Referenced by ComputeRelDXSectionPerAtom().
void G4eBremsstrahlungRelModel::ComputeLPMGsPhis (G4double & funcGS, G4double & funcPhiS, const G4double varShat) private
Definition at line 713 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 713 of file G4eBremsstrahlungRelModel.cc
References G4Exp(), and CLHEP::pi.
Referenced by InitLPMFunctions().
G4double G4eBremsstrahlungRelModel::ComputeRelDXSectionPerAtom (G4double gammaEnergy) private
Definition at line 434 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 434 of file G4eBremsstrahlungRelModel.cc
References ComputeLPMfunctions(), fCurrentIZ, fIsScatOffElectron, fNucTerm, fPrimaryTotalEnergy, fSumTerm, G4eBremsstrahlungRelModel::ElementData::fZFactor1, G4eBremsstrahlungRelModel::ElementData::fZFactor11, G4eBremsstrahlungRelModel::ElementData::fZFactor2, gElementData, max, and y.
Referenced by ComputeBremLoss(), ComputeXSectionPerAtom(), and SampleSecondaries().
void G4eBremsstrahlungRelModel::ComputeScreeningFunctions (G4double & phi1, G4double & phi1m2, G4double & psi1, G4double & psi1m2, const G4double gam, const G4double eps) private
Definition at line 527 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 527 of file G4eBremsstrahlungRelModel.cc
References eps, G4Exp(), G4Log(), and G4InuclParticleNames::gam.
Referenced by ComputeDXSectionPerAtom().
G4double G4eBremsstrahlungRelModel::ComputeXSectionPerAtom (G4double cutEnergy) private
Definition at line 381 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 381 of file G4eBremsstrahlungRelModel.cc
References ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), Acts::Test::delta, fDensityCorr, fIsLPMActive, fPrimaryKinEnergy, fPrimaryTotalEnergy, G4Exp(), G4Log(), gWGL, gXGL, k, and max.
Referenced by ComputeCrossSectionPerAtom().
void G4eBremsstrahlungRelModel::GetLPMFunctions (G4double & lpmGs, G4double & lpmPhis, const G4double s) private
Definition at line 770 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 770 of file G4eBremsstrahlungRelModel.cc
References G4eBremsstrahlungRelModel::LPMFuncs::fISDelta, G4eBremsstrahlungRelModel::LPMFuncs::fLPMFuncG, G4eBremsstrahlungRelModel::LPMFuncs::fLPMFuncPhi, G4eBremsstrahlungRelModel::LPMFuncs::fSLimit, and gLPMFuncs.
Referenced by ComputeLPMfunctions().
void G4eBremsstrahlungRelModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) override virtual
Implements G4VEmModel.
Reimplemented in G4SeltzerBergerModel, G4LivermoreBremsstrahlungModel, and G4ePolarizedBremsstrahlungModel.
Definition at line 170 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 170 of file G4eBremsstrahlungRelModel.cc
References fCurrentIZ, fIsScatOffElectron, fParticleChange, G4VEmModel::GetParticleChangeForLoss(), G4VEmModel::GetTripletModel(), G4VEmModel::HighEnergyLimit(), G4VEmModel::Initialise(), InitialiseElementData(), G4VEmModel::InitialiseElementSelectors(), InitLPMFunctions(), G4VEmModel::IsMaster(), G4VEmModel::LowEnergyLimit(), G4VEmModel::LPMFlag(), and SetParticle().
Referenced by G4TablesForExtrapolator::ComputeElectronDEDX(), and G4LivermoreBremsstrahlungModel::Initialise().
void G4eBremsstrahlungRelModel::InitialiseElementData () private
Definition at line 632 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 632 of file G4eBremsstrahlungRelModel.cc
References source.hepunit::electron_mass_c2, G4eBremsstrahlungRelModel::ElementData::fEpsilonFactor, G4eBremsstrahlungRelModel::ElementData::fFz, G4eBremsstrahlungRelModel::ElementData::fGammaFactor, G4eBremsstrahlungRelModel::ElementData::fILVarS1, G4eBremsstrahlungRelModel::ElementData::fILVarS1Cond, G4eBremsstrahlungRelModel::ElementData::fLogZ, G4eBremsstrahlungRelModel::ElementData::fVarS1, G4eBremsstrahlungRelModel::ElementData::fZFactor1, G4eBremsstrahlungRelModel::ElementData::fZFactor11, G4eBremsstrahlungRelModel::ElementData::fZFactor2, G4Log(), G4lrint(), gElementData, G4Element::GetElementTable(), G4Element::GetfCoulomb(), G4Element::GetZ(), gFelLowZet, gFinelLowZet, gMaxZet, and min.
Referenced by Initialise().
void G4eBremsstrahlungRelModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) override virtual
Reimplemented from G4VEmModel.
Definition at line 192 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 192 of file G4eBremsstrahlungRelModel.cc
References G4VEmModel::GetElementSelectors(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), and G4VEmModel::SetElementSelectors().
void G4eBremsstrahlungRelModel::InitLPMFunctions () private
Definition at line 756 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 756 of file G4eBremsstrahlungRelModel.cc
References ComputeLPMGsPhis(), G4eBremsstrahlungRelModel::LPMFuncs::fISDelta, G4eBremsstrahlungRelModel::LPMFuncs::fIsInitialized, G4eBremsstrahlungRelModel::LPMFuncs::fLPMFuncG, G4eBremsstrahlungRelModel::LPMFuncs::fLPMFuncPhi, G4eBremsstrahlungRelModel::LPMFuncs::fSLimit, gLPMFuncs, and num.
Referenced by Initialise().
G4double G4eBremsstrahlungRelModel::MinPrimaryEnergy (const G4Material * , const G4ParticleDefinition * , G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 231 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 231 of file G4eBremsstrahlungRelModel.cc
References fLowestKinEnergy, and max.
G4eBremsstrahlungRelModel& G4eBremsstrahlungRelModel::operator= (const G4eBremsstrahlungRelModel & right) private delete
void G4eBremsstrahlungRelModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double cutEnergy, G4double maxEnergy) override virtual
Implements G4VEmModel.
Reimplemented in G4SeltzerBergerModel, G4LivermoreBremsstrahlungModel, and G4ePolarizedBremsstrahlungModel.
Definition at line 545 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 545 of file G4eBremsstrahlungRelModel.cc
References ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), dir, CLHEP::electron_mass_c2, fCurrentIZ, fDensityCorr, fGammaParticle, fIsLPMActive, fIsScatOffElectron, CLHEP::HepRandomEngine::flat(), CLHEP::HepRandomEngine::flatArray(), fNucTerm, fParticleChange, fPrimaryParticle, fPrimaryTotalEnergy, fStopAndKill, fSumTerm, G4eBremsstrahlungRelModel::ElementData::fZFactor1, G4eBremsstrahlungRelModel::ElementData::fZFactor2, G4Exp(), G4Log(), gElementData, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4VEmModel::GetTripletModel(), G4VEmModel::LowEnergyLimit(), max, min, G4VParticleChange::ProposeTrackStatus(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SampleSecondaries(), G4VEmModel::SecondaryThreshold(), G4VEmModel::SelectTargetAtom(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), SetupForMaterial(), and xmin.
void G4eBremsstrahlungRelModel::SetParticle (const G4ParticleDefinition * p) protected
Definition at line 200 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 200 of file G4eBremsstrahlungRelModel.cc
References G4Electron::Electron(), fIsElectron, fPrimaryParticle, fPrimaryParticleMass, and G4ParticleDefinition::GetPDGMass().
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), G4eBremsstrahlungRelModel(), Initialise(), and G4SeltzerBergerModel::Initialise().
void G4eBremsstrahlungRelModel::SetupForMaterial (const G4ParticleDefinition * , const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4VEmModel.
Reimplemented in G4SeltzerBergerModel.
Definition at line 210 of file G4eBremsstrahlungRelModel.cc.
View newest version in sPHENIX GitHub at line 210 of file G4eBremsstrahlungRelModel.cc
References fDensityCorr, fDensityFactor, fIsLPMActive, fLPMEnergy, fLPMEnergyThreshold, fPrimaryKinEnergy, fPrimaryParticleMass, fPrimaryTotalEnergy, G4Material::GetElectronDensity(), G4Material::GetRadlen(), gLPMconstant, gMigdalConstant, and G4VEmModel::LPMFlag().
Referenced by ComputeDEDXPerVolume(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), and SampleSecondaries().
Member Data Documentation
G4int G4eBremsstrahlungRelModel::fCurrentIZ protected
Definition at line 150 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), ComputeDXSectionPerAtom(), ComputeLPMfunctions(), ComputeRelDXSectionPerAtom(), G4eBremsstrahlungRelModel(), Initialise(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), and SampleSecondaries().
G4double G4eBremsstrahlungRelModel::fDensityCorr protected
Definition at line 156 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeBremLoss(), ComputeLPMfunctions(), ComputeXSectionPerAtom(), G4eBremsstrahlungRelModel(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), SampleSecondaries(), G4SeltzerBergerModel::SetupForMaterial(), and SetupForMaterial().
G4double G4eBremsstrahlungRelModel::fDensityFactor protected
Definition at line 155 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 155 of file G4eBremsstrahlungRelModel.hh
Referenced by G4eBremsstrahlungRelModel(), G4SeltzerBergerModel::SetupForMaterial(), and SetupForMaterial().
G4ParticleDefinition* G4eBremsstrahlungRelModel::fGammaParticle protected
Definition at line 166 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4eBremsstrahlungRelModel.hh
Referenced by G4eBremsstrahlungRelModel(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), and SampleSecondaries().
G4bool G4eBremsstrahlungRelModel::fIsElectron protected
Definition at line 146 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4eBremsstrahlungRelModel.hh
Referenced by G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), and SetParticle().
G4bool G4eBremsstrahlungRelModel::fIsLPMActive protected
Definition at line 148 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeBremLoss(), ComputeXSectionPerAtom(), SampleSecondaries(), G4SeltzerBergerModel::SetupForMaterial(), and SetupForMaterial().
G4bool G4eBremsstrahlungRelModel::fIsScatOffElectron protected
Definition at line 147 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), Initialise(), G4SeltzerBergerModel::Initialise(), and SampleSecondaries().
G4bool G4eBremsstrahlungRelModel::fIsUseCompleteScreening private
Definition at line 211 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 211 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeDXSectionPerAtom().
G4double G4eBremsstrahlungRelModel::fLowestKinEnergy protected
Definition at line 157 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 157 of file G4eBremsstrahlungRelModel.hh
Referenced by G4eBremsstrahlungRelModel(), G4SeltzerBergerModel::G4SeltzerBergerModel(), G4SeltzerBergerModel::Initialise(), and MinPrimaryEnergy().
G4double G4eBremsstrahlungRelModel::fLPMEnergy private
Definition at line 214 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 214 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeLPMfunctions(), G4eBremsstrahlungRelModel(), and SetupForMaterial().
G4double G4eBremsstrahlungRelModel::fLPMEnergyThreshold private
Definition at line 213 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 213 of file G4eBremsstrahlungRelModel.hh
Referenced by G4eBremsstrahlungRelModel(), and SetupForMaterial().
G4double G4eBremsstrahlungRelModel::fNucTerm protected
Definition at line 159 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), G4eBremsstrahlungRelModel(), and SampleSecondaries().
G4ParticleChangeForLoss* G4eBremsstrahlungRelModel::fParticleChange protected
Definition at line 167 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4eBremsstrahlungRelModel.hh
Referenced by G4eBremsstrahlungRelModel(), Initialise(), G4SeltzerBergerModel::Initialise(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), and SampleSecondaries().
G4double G4eBremsstrahlungRelModel::fPrimaryKinEnergy protected
Definition at line 153 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4eBremsstrahlungRelModel.hh
Referenced by G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), ComputeXSectionPerAtom(), G4eBremsstrahlungRelModel(), G4SeltzerBergerModel::SetupForMaterial(), and SetupForMaterial().
const G4ParticleDefinition* G4eBremsstrahlungRelModel::fPrimaryParticle protected
Definition at line 165 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), G4eBremsstrahlungRelModel(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), SampleSecondaries(), and SetParticle().
G4double G4eBremsstrahlungRelModel::fPrimaryParticleMass protected
Definition at line 152 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 152 of file G4eBremsstrahlungRelModel.hh
Referenced by G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4eBremsstrahlungRelModel(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), SetParticle(), and SetupForMaterial().
G4double G4eBremsstrahlungRelModel::fPrimaryTotalEnergy protected
Definition at line 154 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeBremLoss(), G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4SeltzerBergerModel::ComputeDXSectionPerAtom(), ComputeDXSectionPerAtom(), ComputeLPMfunctions(), ComputeRelDXSectionPerAtom(), ComputeXSectionPerAtom(), G4eBremsstrahlungRelModel(), G4LivermoreBremsstrahlungModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), SampleSecondaries(), G4SeltzerBergerModel::SetupForMaterial(), and SetupForMaterial().
G4double G4eBremsstrahlungRelModel::fSumTerm protected
Definition at line 160 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), G4eBremsstrahlungRelModel(), and SampleSecondaries().
const G4double G4eBremsstrahlungRelModel::gBremFactor static protected
Initial value:
= 16. * CLHEP::fine_structure_const * CLHEP::classic_electr_radius
    * CLHEP::classic_electr_radius/3.
Definition at line 162 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), and G4SeltzerBergerModel::ComputeDXSectionPerAtom().
std::vector< G4eBremsstrahlungRelModel::ElementData * > G4eBremsstrahlungRelModel::gElementData static private
Definition at line 209 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 209 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeDXSectionPerAtom(), ComputeLPMfunctions(), ComputeRelDXSectionPerAtom(), InitialiseElementData(), SampleSecondaries(), and ~G4eBremsstrahlungRelModel().
const G4double G4eBremsstrahlungRelModel::gFelLowZet static private
Initial value:
= {
  0.0, 5.3104, 4.7935, 4.7402, 4.7112, 4.6694, 4.6134, 4.5520
}
Definition at line 176 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4eBremsstrahlungRelModel.hh
Referenced by InitialiseElementData().
const G4double G4eBremsstrahlungRelModel::gFinelLowZet static private
Initial value:
= {
  0.0, 5.9173, 5.6125, 5.5377, 5.4728, 5.4174, 5.3688, 5.3236
}
Definition at line 177 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4eBremsstrahlungRelModel.hh
Referenced by InitialiseElementData().
const G4double G4eBremsstrahlungRelModel::gLPMconstant static private
Initial value:
= CLHEP::fine_structure_const * CLHEP::electron_mass_c2
    * CLHEP::electron_mass_c2 / (4. * CLHEP::pi * CLHEP::hbarc)
Definition at line 172 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4eBremsstrahlungRelModel.hh
Referenced by SetupForMaterial().
G4eBremsstrahlungRelModel::LPMFuncs G4eBremsstrahlungRelModel::gLPMFuncs static private
Definition at line 208 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 208 of file G4eBremsstrahlungRelModel.hh
Referenced by GetLPMFunctions(), InitLPMFunctions(), and ~G4eBremsstrahlungRelModel().
const G4int G4eBremsstrahlungRelModel::gMaxZet = 120 static private
Definition at line 170 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDEDXPerVolume(), and InitialiseElementData().
const G4double G4eBremsstrahlungRelModel::gMigdalConstant static protected
Initial value:
= 4. * CLHEP::pi * CLHEP::classic_electr_radius
    * CLHEP::electron_Compton_length * CLHEP::electron_Compton_length
Definition at line 163 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4eBremsstrahlungRelModel.hh
Referenced by G4SeltzerBergerModel::SetupForMaterial(), and SetupForMaterial().
const G4double G4eBremsstrahlungRelModel::gWGL static private
Initial value:
= {
  5.06142681e-02, 1.11190517e-01, 1.56853323e-01, 1.81341892e-01,
  1.81341892e-01, 1.56853323e-01, 1.11190517e-01, 5.06142681e-02
}
Definition at line 175 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 175 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeBremLoss(), and ComputeXSectionPerAtom().
const G4double G4eBremsstrahlungRelModel::gXGL static private
Initial value:
= {
  1.98550718e-02, 1.01666761e-01, 2.37233795e-01, 4.08282679e-01,
  5.91717321e-01, 7.62766205e-01, 8.98333239e-01, 9.80144928e-01
}
Definition at line 174 of file G4eBremsstrahlungRelModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4eBremsstrahlungRelModel.hh
Referenced by ComputeBremLoss(), and ComputeXSectionPerAtom().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4eBremsstrahlungRelModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4eBremsstrahlungRelModel.cc