ECCE @ EIC Software: G4eeToHadronsMultiModel Class Reference
G4eeToHadronsMultiModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeToHadronsMultiModel.hh>
Public Member Functions
G4eeToHadronsMultiModel (G4int ver=0, const G4String &nam="eeToHadrons")
virtual ~G4eeToHadronsMultiModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin=0.0, G4double maxEnergy=DBL_MAX) override
virtual void ModelDescription (std::ostream &outFile) const override
void SetCrossSecFactor (G4double fac)
G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void AddEEModel (G4Vee2hadrons *, const G4DataVector &)
G4double LabToCM (G4double)
G4eeToHadronsMultiModel & operator= (const G4eeToHadronsMultiModel &right)
G4eeToHadronsMultiModel (const G4eeToHadronsMultiModel &)
Private Attributes
G4eeCrossSections * cross
G4ParticleChangeForGamma * fParticleChange
G4double delta
std::vector< G4eeToHadronsModel * > models
std::vector< G4double > ekinMin
std::vector< G4double > ekinPeak
std::vector< G4double > ekinMax
std::vector< G4double > cumSum
G4double thKineticEnergy
G4double maxKineticEnergy
G4double csFactor
G4int nModels
G4int verbose
G4bool isInitialised
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 63 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4eeToHadronsMultiModel.hh
Constructor & Destructor Documentation
G4eeToHadronsMultiModel::G4eeToHadronsMultiModel (G4int ver = 0, const G4String & nam = "eeToHadrons") explicit
Definition at line 65 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4eeToHadronsMultiModel.cc
References cross, DBL_MAX, delta, fParticleChange, GeV, maxKineticEnergy, MeV, and thKineticEnergy.
G4eeToHadronsMultiModel::~G4eeToHadronsMultiModel () virtual
Definition at line 81 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4eeToHadronsMultiModel.cc
References cross.
G4eeToHadronsMultiModel::G4eeToHadronsMultiModel (const G4eeToHadronsMultiModel &) private
Member Function Documentation
void G4eeToHadronsMultiModel::AddEEModel (G4Vee2hadrons * mod, const G4DataVector & cuts) private
Definition at line 132 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 132 of file G4eeToHadronsMultiModel.cc
References cumSum, ekinMax, ekinMin, ekinPeak, G4Vee2hadrons::HighEnergy(), G4eeToHadronsModel::Initialise(), G4Vee2hadrons::LowEnergy(), models, G4Vee2hadrons::PeakEnergy(), G4InuclParticleNames::positron, G4Positron::Positron(), thKineticEnergy, and verbose.
Referenced by Initialise().
G4double G4eeToHadronsMultiModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) override virtual
Reimplemented from G4VEmModel.
Definition at line 162 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 162 of file G4eeToHadronsMultiModel.cc
References ComputeCrossSectionPerElectron().
G4double G4eeToHadronsMultiModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) inline
Definition at line 150 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4eeToHadronsMultiModel.hh
References csFactor, cumSum, ekinMax, ekinMin, energy, LabToCM(), models, nModels, and thKineticEnergy.
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4eeToHadronsMultiModel::CrossSectionPerVolume (const G4Material * mat, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 150 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 150 of file G4eeToHadronsMultiModel.cc
References ComputeCrossSectionPerElectron(), and G4Material::GetElectronDensity().
void G4eeToHadronsMultiModel::Initialise (const G4ParticleDefinition * , const G4DataVector & cuts) override virtual
Implements G4VEmModel.
Definition at line 88 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 88 of file G4eeToHadronsMultiModel.cc
References AddEEModel(), cross, delta, fParticleChange, G4VEmModel::GetParticleChangeForGamma(), isInitialised, maxKineticEnergy, models, and nModels.
G4double G4eeToHadronsMultiModel::LabToCM (G4double kinE_lab) inline private
Definition at line 140 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 140 of file G4eeToHadronsMultiModel.hh
References CLHEP::electron_mass_c2, and mass.
Referenced by ComputeCrossSectionPerElectron(), and SampleSecondaries().
void G4eeToHadronsMultiModel::ModelDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VEmModel.
Definition at line 198 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 198 of file G4eeToHadronsMultiModel.cc
References e1, e2, source.hepunit::electron_mass_c2, G4endl, GeV, maxKineticEnergy, thKineticEnergy, and verbose.
Referenced by G4eeToHadrons::StreamProcessInfo().
G4eeToHadronsMultiModel& G4eeToHadronsMultiModel::operator= (const G4eeToHadronsMultiModel & right) private
void G4eeToHadronsMultiModel::SampleSecondaries (std::vector< G4DynamicParticle * > * newp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin = 0.0, G4double maxEnergy = DBL_MAX) override virtual
Implements G4VEmModel.
Definition at line 174 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 174 of file G4eeToHadronsMultiModel.cc
References cumSum, energy, fParticleChange, fStopAndKill, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), LabToCM(), models, nModels, G4VParticleChange::ProposeTrackStatus(), and thKineticEnergy.
void G4eeToHadronsMultiModel::SetCrossSecFactor (G4double fac)
Definition at line 212 of file G4eeToHadronsMultiModel.cc.
View newest version in sPHENIX GitHub at line 212 of file G4eeToHadronsMultiModel.cc
References csFactor, fac, G4cout, G4endl, and verbose.
Referenced by G4eeToHadrons::InitialiseProcess(), and G4eeToHadrons::SetCrossSecFactor().
Member Data Documentation
G4eeCrossSections* G4eeToHadronsMultiModel::cross private
Definition at line 117 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eeToHadronsMultiModel.hh
Referenced by G4eeToHadronsMultiModel(), Initialise(), and ~G4eeToHadronsMultiModel().
G4double G4eeToHadronsMultiModel::csFactor private
Definition at line 130 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4eeToHadronsMultiModel.hh
Referenced by ComputeCrossSectionPerElectron(), and SetCrossSecFactor().
std::vector<G4double> G4eeToHadronsMultiModel::cumSum private
Definition at line 126 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel(), ComputeCrossSectionPerElectron(), and SampleSecondaries().
G4double G4eeToHadronsMultiModel::delta private
Definition at line 119 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4eeToHadronsMultiModel.hh
Referenced by G4eeToHadronsMultiModel(), and Initialise().
std::vector<G4double> G4eeToHadronsMultiModel::ekinMax private
Definition at line 125 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel(), and ComputeCrossSectionPerElectron().
std::vector<G4double> G4eeToHadronsMultiModel::ekinMin private
Definition at line 123 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 123 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel(), and ComputeCrossSectionPerElectron().
std::vector<G4double> G4eeToHadronsMultiModel::ekinPeak private
Definition at line 124 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 124 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel().
G4ParticleChangeForGamma* G4eeToHadronsMultiModel::fParticleChange private
Definition at line 118 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eeToHadronsMultiModel.hh
Referenced by G4eeToHadronsMultiModel(), Initialise(), and SampleSecondaries().
G4bool G4eeToHadronsMultiModel::isInitialised private
Definition at line 134 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 134 of file G4eeToHadronsMultiModel.hh
Referenced by Initialise().
G4double G4eeToHadronsMultiModel::maxKineticEnergy private
Definition at line 129 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4eeToHadronsMultiModel.hh
Referenced by G4eeToHadronsMultiModel(), Initialise(), and ModelDescription().
std::vector<G4eeToHadronsModel*> G4eeToHadronsMultiModel::models private
Definition at line 121 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel(), ComputeCrossSectionPerElectron(), Initialise(), and SampleSecondaries().
G4int G4eeToHadronsMultiModel::nModels private
Definition at line 132 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 132 of file G4eeToHadronsMultiModel.hh
Referenced by ComputeCrossSectionPerElectron(), Initialise(), and SampleSecondaries().
G4double G4eeToHadronsMultiModel::thKineticEnergy private
Definition at line 128 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel(), ComputeCrossSectionPerElectron(), G4eeToHadronsMultiModel(), ModelDescription(), and SampleSecondaries().
G4int G4eeToHadronsMultiModel::verbose private
Definition at line 133 of file G4eeToHadronsMultiModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4eeToHadronsMultiModel.hh
Referenced by AddEEModel(), ModelDescription(), and SetCrossSecFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeToHadronsMultiModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4eeToHadronsMultiModel.cc