ECCE @ EIC Software: G4QGSPPiKBuilder Class Reference
G4QGSPPiKBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPPiKBuilder.hh>
Public Member Functions
G4QGSPPiKBuilder (G4bool quasiElastic=false)
virtual ~G4QGSPPiKBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPiKBuilder
G4VPiKBuilder ()=default
virtual ~G4VPiKBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4QGSMFragmentation * theQGSM
G4double theMin
Detailed Description
Definition at line 59 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4QGSPPiKBuilder.hh
Constructor & Destructor Documentation
G4QGSPPiKBuilder::G4QGSPPiKBuilder (G4bool quasiElastic = false)
Definition at line 50 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 50 of file G4QGSPPiKBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSPPiKBuilder::~G4QGSPPiKBuilder () virtual
Definition at line 73 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 73 of file G4QGSPPiKBuilder.cc
References theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSPPiKBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 65 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QGSPPiKBuilder.hh
void G4QGSPPiKBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 82 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 82 of file G4QGSPPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSPPiKBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 91 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 91 of file G4QGSPPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSPPiKBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 100 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 100 of file G4QGSPPiKBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSPPiKBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 108 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 108 of file G4QGSPPiKBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSPPiKBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 116 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 116 of file G4QGSPPiKBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSPPiKBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 124 of file G4QGSPPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 124 of file G4QGSPPiKBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSPPiKBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 73 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QGSPPiKBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4QGSPPiKBuilder::theCascade private
Definition at line 79 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QGSPPiKBuilder.hh
Referenced by G4QGSPPiKBuilder().
G4double G4QGSPPiKBuilder::theMin private
Definition at line 84 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 84 of file G4QGSPPiKBuilder.hh
Referenced by Build(), G4QGSPPiKBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSPPiKBuilder::theModel private
Definition at line 78 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPPiKBuilder.hh
Referenced by Build(), and G4QGSPPiKBuilder().
G4QGSMFragmentation* G4QGSPPiKBuilder::theQGSM private
Definition at line 83 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QGSPPiKBuilder.hh
Referenced by G4QGSPPiKBuilder(), and ~G4QGSPPiKBuilder().
G4QuasiElasticChannel* G4QGSPPiKBuilder::theQuasiElastic private
Definition at line 82 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4QGSPPiKBuilder.hh
Referenced by G4QGSPPiKBuilder(), and ~G4QGSPPiKBuilder().
G4ExcitedStringDecay* G4QGSPPiKBuilder::theStringDecay private
Definition at line 81 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4QGSPPiKBuilder.hh
Referenced by G4QGSPPiKBuilder(), and ~G4QGSPPiKBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSPPiKBuilder::theStringModel private
Definition at line 80 of file G4QGSPPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QGSPPiKBuilder.hh
Referenced by G4QGSPPiKBuilder(), and ~G4QGSPPiKBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPPiKBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSPPiKBuilder.cc