ECCE @ EIC Software: CCalMaterialFactory Class Reference
CCalMaterialFactory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalMaterialFactory.hh>
Public Types
enum MatDescription { byWeight, byVolume, byAtomic }
Public Member Functions
~CCalMaterialFactory ()
G4Material * findMaterial (const G4String &) const
G4Element * findElement (const G4String &) const
G4Element * addElement (const G4String &, const G4String &, G4double, G4double, G4double)
G4Material * addMaterial (const G4String &nam, G4double density, G4int nconst, G4String mats[], G4double prop[], MatDescription md=byWeight)
void readElements (const G4String &)
void readMaterials (const G4String &)
Static Public Member Functions
static CCalMaterialFactory * getInstance (const G4String &, const G4String &)
static CCalMaterialFactory * getInstance (const G4String &)
static CCalMaterialFactory * getInstance ()
Protected Member Functions
void readElements (std::ifstream &)
void readMaterials (std::ifstream &)
Private Member Functions
CCalMaterialFactory ()
G4Material * findG4Material (const G4String &) const
CCalMaterial * findCCalMaterial (const G4String &) const
CCalAMaterial * findCCalAMaterial (const G4String &) const
CCalMaterial * addCCalMaterial (const G4String &nam, G4double density, G4int nconst, G4String mats[], G4double prop[], MatDescription md=byWeight)
Private Attributes
CCalMaterialTable theCCalMaterials
CCalAMaterialTable theCCalAMaterials
Static Private Attributes
static CCalMaterialFactory * instance = 0
static G4String elementfile = ""
static G4String mixturefile = ""
Detailed Description
Definition at line 47 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 47 of file CCalMaterialFactory.hh
Member Enumeration Documentation
enum CCalMaterialFactory::MatDescription
Enumerator:
byWeight
byVolume
byAtomic
Definition at line 49 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 49 of file CCalMaterialFactory.hh
Constructor & Destructor Documentation
CCalMaterialFactory::~CCalMaterialFactory ()
Definition at line 96 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 96 of file CCalMaterialFactory.cc
References theCCalAMaterials, and theCCalMaterials.
CCalMaterialFactory::CCalMaterialFactory () private
Definition at line 437 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 437 of file CCalMaterialFactory.cc
References elementfile, mixturefile, readElements(), and readMaterials().
Referenced by getInstance().
Member Function Documentation
CCalMaterial * CCalMaterialFactory::addCCalMaterial (const G4String & nam, G4double density, G4int nconst, G4String mats[], G4double prop[], MatDescription md = byWeight) private
Definition at line 277 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 277 of file CCalMaterialFactory.cc
References byAtomic, byWeight, findCCalAMaterial(), findCCalMaterial(), CCalMaterial::FTVolume, CCalMaterial::FTWeight, G4cerr, G4cout, G4endl, mat, material(), theCCalAMaterials, and theCCalMaterials.
Referenced by addMaterial(), and readMaterials().
G4Element * CCalMaterialFactory::addElement (const G4String & name, const G4String & symbol, G4double Z, G4double A, G4double density)
Definition at line 162 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 162 of file CCalMaterialFactory.cc
References Acts::UnitConstants::g, G4cout, G4endl, mole, and theCCalAMaterials.
Referenced by readElements().
G4Material * CCalMaterialFactory::addMaterial (const G4String & nam, G4double density, G4int nconst, G4String mats[], G4double prop[], MatDescription md = byWeight)
Definition at line 179 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 179 of file CCalMaterialFactory.cc
References addCCalMaterial(), and findMaterial().
CCalAMaterial * CCalMaterialFactory::findCCalAMaterial (const G4String & mat) const private
Definition at line 264 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 264 of file CCalMaterialFactory.cc
References G4cout, G4endl, mat, configureMap::Name, and theCCalAMaterials.
Referenced by addCCalMaterial(), and findCCalMaterial().
CCalMaterial * CCalMaterialFactory::findCCalMaterial (const G4String & mat) const private
Definition at line 251 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 251 of file CCalMaterialFactory.cc
References findCCalAMaterial(), G4cout, G4endl, mat, configureMap::Name, and theCCalMaterials.
Referenced by addCCalMaterial(), and findMaterial().
G4Element * CCalMaterialFactory::findElement (const G4String & mat) const
Definition at line 149 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 149 of file CCalMaterialFactory.cc
References G4cout, G4endl, G4Element::GetElementTable(), and mat.
Referenced by findMaterial().
G4Material * CCalMaterialFactory::findG4Material (const G4String & mat) const private
Definition at line 240 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 240 of file CCalMaterialFactory.cc
References G4Material::GetMaterialTable(), and mat.
Referenced by findMaterial().
G4Material * CCalMaterialFactory::findMaterial (const G4String & mat) const
Definition at line 111 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 111 of file CCalMaterialFactory.cc
References G4Material::AddElement(), cm3, CCalMaterial::Density(), CCalMaterial::Element(), FatalException, findCCalMaterial(), findElement(), findG4Material(), Acts::UnitConstants::g, G4cerr, G4cout, G4endl, G4Exception(), CCalMaterial::Name(), CCalMaterial::NElements(), and CCalMaterial::Weight().
Referenced by addMaterial(), CCalG4Hcal::constructAbsorberLayer(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), and CCalG4Hcal::constructScintillatorLayer().
CCalMaterialFactory * CCalMaterialFactory::getInstance (const G4String & matfile, const G4String & mixfile) static
Definition at line 53 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 53 of file CCalMaterialFactory.cc
References elementfile, G4cerr, G4endl, getInstance(), and mixturefile.
CCalMaterialFactory * CCalMaterialFactory::getInstance (const G4String & matfile) static
Definition at line 74 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 74 of file CCalMaterialFactory.cc
References getInstance().
CCalMaterialFactory * CCalMaterialFactory::getInstance () static
Definition at line 79 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 79 of file CCalMaterialFactory.cc
References CCalMaterialFactory(), elementfile, G4cerr, G4endl, instance, and mixturefile.
Referenced by CCalDetectorConstruction::Construct(), CCalG4Hcal::constructAbsorberLayer(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Hcal::constructScintillatorLayer(), and getInstance().
void CCalMaterialFactory::readElements (const G4String & matfile)
Definition at line 190 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 190 of file CCalMaterialFactory.cc
References findDO(), G4cerr, G4cout, G4endl, and openGeomFile().
Referenced by CCalMaterialFactory().
void CCalMaterialFactory::readElements (std::ifstream & is) protected
Definition at line 346 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 346 of file CCalMaterialFactory.cc
References A(), addElement(), G4cout, G4endl, G4Element::GetElementTable(), jump(), readName(), and Z.
void CCalMaterialFactory::readMaterials (const G4String & matfile)
Definition at line 213 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 213 of file CCalMaterialFactory.cc
References findDO(), G4cerr, G4cout, G4endl, and openGeomFile().
Referenced by CCalMaterialFactory().
void CCalMaterialFactory::readMaterials (std::ifstream & is) protected
Definition at line 373 of file CCalMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 373 of file CCalMaterialFactory.cc
References kdfinder::abs(), addCCalMaterial(), byAtomic, byVolume, byWeight, Acts::UnitConstants::g, G4cout, G4endl, jump(), kelvin, kStateGas, mixturefile, mole, pascal, readName(), theCCalMaterials, and source.hepunit::universe_mean_density.
Member Data Documentation
G4String CCalMaterialFactory::elementfile = "" static private
Definition at line 91 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 91 of file CCalMaterialFactory.hh
Referenced by CCalMaterialFactory(), and getInstance().
CCalMaterialFactory * CCalMaterialFactory::instance = 0 static private
Definition at line 89 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 89 of file CCalMaterialFactory.hh
Referenced by getInstance().
G4String CCalMaterialFactory::mixturefile = "" static private
Definition at line 92 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 92 of file CCalMaterialFactory.hh
Referenced by CCalMaterialFactory(), getInstance(), and readMaterials().
CCalAMaterialTable CCalMaterialFactory::theCCalAMaterials private
Definition at line 95 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalMaterialFactory.hh
Referenced by addCCalMaterial(), addElement(), findCCalAMaterial(), and ~CCalMaterialFactory().
CCalMaterialTable CCalMaterialFactory::theCCalMaterials private
Definition at line 94 of file CCalMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 94 of file CCalMaterialFactory.hh
Referenced by addCCalMaterial(), findCCalMaterial(), readMaterials(), and ~CCalMaterialFactory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalMaterialFactory.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalMaterialFactory.cc