ECCE @ EIC Software: G4ContinuousGainOfEnergy Class Reference
G4ContinuousGainOfEnergy Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4ContinuousGainOfEnergy.hh>
Public Member Functions
G4ContinuousGainOfEnergy (const G4String &name="EnergyGain", G4ProcessType type=fElectromagnetic)
virtual ~G4ContinuousGainOfEnergy ()
void PreparePhysicsTable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &)
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
void SetLossFluctuations (G4bool val)
void SetIsIntegral (G4bool val)
void SetDirectEnergyLossProcess (G4VEnergyLossProcess *aProcess)
void SetDirectParticle (G4ParticleDefinition *p)
Public Member Functions inherited from G4VContinuousProcess
G4VContinuousProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousProcess (G4VContinuousProcess &)
virtual ~G4VContinuousProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
Protected Member Functions inherited from G4VContinuousProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Member Functions
void DefineMaterial (const G4MaterialCutsCouple *couple)
void SetDynamicMassCharge (const G4Track &track, G4double energy)
G4ContinuousGainOfEnergy (G4ContinuousGainOfEnergy &)
G4ContinuousGainOfEnergy & operator= (const G4ContinuousGainOfEnergy &right)
Private Attributes
const G4Material * currentMaterial
const G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcut
G4double currentCutInRange
G4double preStepKinEnergy
G4double linLossLimit
G4bool lossFluctuationFlag
G4bool lossFluctuationArePossible
G4VEnergyLossProcess * theDirectEnergyLossProcess
G4ParticleDefinition * theDirectPartDef
G4bool is_integral
G4bool IsIon
G4double massRatio
G4double chargeSqRatio
G4VEmModel * currentModel
G4double preStepChargeSqRatio
G4double preStepScaledKinEnergy
G4double preStepRange
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 68 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ContinuousGainOfEnergy.hh
Constructor & Destructor Documentation
G4ContinuousGainOfEnergy::G4ContinuousGainOfEnergy (const G4String & name = "EnergyGain", G4ProcessType type = fElectromagnetic)
Definition at line 44 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ContinuousGainOfEnergy.cc
References chargeSqRatio, currentCouple, currentCoupleIndex, currentCutInRange, currentMaterialIndex, currentTcut, is_integral, IsIon, linLossLimit, lossFluctuationArePossible, lossFluctuationFlag, massRatio, preStepChargeSqRatio, preStepKinEnergy, preStepRange, and preStepScaledKinEnergy.
G4ContinuousGainOfEnergy::~G4ContinuousGainOfEnergy () virtual
Definition at line 74 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ContinuousGainOfEnergy.cc
G4ContinuousGainOfEnergy::G4ContinuousGainOfEnergy (G4ContinuousGainOfEnergy &) private
Member Function Documentation
G4VParticleChange * G4ContinuousGainOfEnergy::AlongStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4VContinuousProcess.
Definition at line 114 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 114 of file G4ContinuousGainOfEnergy.cc
References kdfinder::abs(), G4VProcess::aParticleChange, chargeSqRatio, G4VEmModel::CorrectionsAlongStep(), currentCouple, currentMaterial, currentModel, currentTcut, E, G4VEmModel::GetChargeSquareRatio(), G4VEnergyLossProcess::GetDEDX(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4VEnergyLossProcess::GetKineticEnergy(), G4VEmModel::GetModelOfFluctuations(), G4Step::GetPostStepPoint(), G4VEnergyLossProcess::GetRange(), G4Step::GetStepLength(), G4StepPoint::GetWeight(), G4ParticleChange::Initialize(), is_integral, IsIon, BTOF::length, linLossLimit, lossFluctuationFlag, massRatio, G4VEmModel::MaxSecondaryKinEnergy(), min, n, preStepKinEnergy, G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeParentWeight(), r, G4DynamicParticle::SetDefinition(), G4VEnergyLossProcess::SetDynamicMassCharge(), G4DynamicParticle::SetKineticEnergy(), G4VParticleChange::SetParentWeightByProcess(), theDirectEnergyLossProcess, theDirectPartDef, x, and x1.
void G4ContinuousGainOfEnergy::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Definition at line 91 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ContinuousGainOfEnergy.cc
void G4ContinuousGainOfEnergy::DefineMaterial (const G4MaterialCutsCouple * couple) inline private
Definition at line 172 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ContinuousGainOfEnergy.hh
References currentCouple, currentCoupleIndex, currentCutInRange, currentMaterial, currentMaterialIndex, currentTcut, G4ProductionCutsTable::GetEnergyCutsVector(), G4MaterialCutsCouple::GetIndex(), G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4ParticleDefinition::GetParticleName(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), incremental_prev_tag::idx, and theDirectPartDef.
Referenced by GetContinuousStepLimit().
G4double G4ContinuousGainOfEnergy::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) protected virtual
Implements G4VContinuousProcess.
Definition at line 267 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 267 of file G4ContinuousGainOfEnergy.cc
References chargeSqRatio, currentCouple, currentCoupleIndex, currentMaterial, currentModel, currentTcut, DBL_MAX, DefineMaterial(), G4VEmModel::GetChargeSquareRatio(), G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4VEnergyLossProcess::GetRange(), G4VEmModel::HighEnergyLimit(), IsIon, massRatio, max, maxE, min, mm, preStepChargeSqRatio, preStepKinEnergy, preStepRange, preStepScaledKinEnergy, r1, G4VEnergyLossProcess::SelectModelForMaterial(), G4VEnergyLossProcess::SetDynamicMassCharge(), theDirectEnergyLossProcess, theDirectPartDef, and x.
G4ContinuousGainOfEnergy& G4ContinuousGainOfEnergy::operator= (const G4ContinuousGainOfEnergy & right) private
void G4ContinuousGainOfEnergy::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Definition at line 81 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ContinuousGainOfEnergy.cc
void G4ContinuousGainOfEnergy::SetDirectEnergyLossProcess (G4VEnergyLossProcess * aProcess) inline
Definition at line 111 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ContinuousGainOfEnergy.hh
References theDirectEnergyLossProcess.
Referenced by G4AdjointPhysicsList::ConstructEM().
void G4ContinuousGainOfEnergy::SetDirectParticle (G4ParticleDefinition * p)
Definition at line 98 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ContinuousGainOfEnergy.cc
References chargeSqRatio, G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), IsIon, massRatio, source.hepunit::proton_mass_c2, and theDirectPartDef.
Referenced by G4AdjointPhysicsList::ConstructEM().
void G4ContinuousGainOfEnergy::SetDynamicMassCharge (const G4Track & track, G4double energy) private
Definition at line 320 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 320 of file G4ContinuousGainOfEnergy.cc
References currentMaterial, G4EmCorrections::EffectiveChargeSquareRatio(), G4LossTableManager::EmCorrections(), G4LossTableManager::Instance(), massRatio, G4VEnergyLossProcess::SetDynamicMassCharge(), theDirectEnergyLossProcess, and theDirectPartDef.
void G4ContinuousGainOfEnergy::SetIsIntegral (G4bool val) inline
Definition at line 109 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ContinuousGainOfEnergy.hh
References is_integral.
void G4ContinuousGainOfEnergy::SetLossFluctuations (G4bool val)
Definition at line 257 of file G4ContinuousGainOfEnergy.cc.
View newest version in sPHENIX GitHub at line 257 of file G4ContinuousGainOfEnergy.cc
References lossFluctuationArePossible, and lossFluctuationFlag.
Referenced by G4AdjointPhysicsList::ConstructEM().
Member Data Documentation
G4double G4ContinuousGainOfEnergy::chargeSqRatio private
Definition at line 158 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), G4ContinuousGainOfEnergy(), GetContinuousStepLimit(), and SetDirectParticle().
const G4MaterialCutsCouple* G4ContinuousGainOfEnergy::currentCouple private
Definition at line 135 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), DefineMaterial(), G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
size_t G4ContinuousGainOfEnergy::currentCoupleIndex private
Definition at line 137 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ContinuousGainOfEnergy.hh
Referenced by DefineMaterial(), G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
G4double G4ContinuousGainOfEnergy::currentCutInRange private
Definition at line 139 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ContinuousGainOfEnergy.hh
Referenced by DefineMaterial(), and G4ContinuousGainOfEnergy().
const G4Material* G4ContinuousGainOfEnergy::currentMaterial private
Definition at line 134 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), DefineMaterial(), GetContinuousStepLimit(), and SetDynamicMassCharge().
size_t G4ContinuousGainOfEnergy::currentMaterialIndex private
Definition at line 136 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ContinuousGainOfEnergy.hh
Referenced by DefineMaterial(), and G4ContinuousGainOfEnergy().
G4VEmModel* G4ContinuousGainOfEnergy::currentModel private
Definition at line 159 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), and GetContinuousStepLimit().
G4double G4ContinuousGainOfEnergy::currentTcut private
Definition at line 138 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), DefineMaterial(), G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
G4bool G4ContinuousGainOfEnergy::is_integral private
Definition at line 152 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), G4ContinuousGainOfEnergy(), and SetIsIntegral().
G4bool G4ContinuousGainOfEnergy::IsIon private
Definition at line 156 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), G4ContinuousGainOfEnergy(), GetContinuousStepLimit(), and SetDirectParticle().
G4double G4ContinuousGainOfEnergy::linLossLimit private
Definition at line 144 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), and G4ContinuousGainOfEnergy().
G4bool G4ContinuousGainOfEnergy::lossFluctuationArePossible private
Definition at line 146 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ContinuousGainOfEnergy.hh
Referenced by G4ContinuousGainOfEnergy(), and SetLossFluctuations().
G4bool G4ContinuousGainOfEnergy::lossFluctuationFlag private
Definition at line 145 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), G4ContinuousGainOfEnergy(), and SetLossFluctuations().
G4double G4ContinuousGainOfEnergy::massRatio private
Definition at line 157 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), G4ContinuousGainOfEnergy(), GetContinuousStepLimit(), SetDirectParticle(), and SetDynamicMassCharge().
G4double G4ContinuousGainOfEnergy::preStepChargeSqRatio private
Definition at line 160 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ContinuousGainOfEnergy.hh
Referenced by G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
G4double G4ContinuousGainOfEnergy::preStepKinEnergy private
Definition at line 140 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
G4double G4ContinuousGainOfEnergy::preStepRange private
Definition at line 162 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ContinuousGainOfEnergy.hh
Referenced by G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
G4double G4ContinuousGainOfEnergy::preStepScaledKinEnergy private
Definition at line 161 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ContinuousGainOfEnergy.hh
Referenced by G4ContinuousGainOfEnergy(), and GetContinuousStepLimit().
G4VEnergyLossProcess* G4ContinuousGainOfEnergy::theDirectEnergyLossProcess private
Definition at line 148 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), GetContinuousStepLimit(), SetDirectEnergyLossProcess(), and SetDynamicMassCharge().
G4ParticleDefinition* G4ContinuousGainOfEnergy::theDirectPartDef private
Definition at line 149 of file G4ContinuousGainOfEnergy.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ContinuousGainOfEnergy.hh
Referenced by AlongStepDoIt(), DefineMaterial(), GetContinuousStepLimit(), SetDirectParticle(), and SetDynamicMassCharge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4ContinuousGainOfEnergy.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4ContinuousGainOfEnergy.cc