ECCE @ EIC Software: OpNoviceSteppingAction Class Reference
OpNoviceSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNoviceSteppingAction.hh>
Public Member Functions
OpNoviceSteppingAction ()
virtual ~OpNoviceSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
G4int fScintillationCounter
G4int fCerenkovCounter
G4int fEventNumber
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Stepping action class
Definition at line 39 of file OpNoviceSteppingAction.hh.
View newest version in sPHENIX GitHub at line 39 of file OpNoviceSteppingAction.hh
Constructor & Destructor Documentation
OpNoviceSteppingAction::OpNoviceSteppingAction ()
Definition at line 41 of file OpNoviceSteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file OpNoviceSteppingAction.cc
References fCerenkovCounter, fEventNumber, and fScintillationCounter.
OpNoviceSteppingAction::~OpNoviceSteppingAction () virtual
Definition at line 51 of file OpNoviceSteppingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file OpNoviceSteppingAction.cc
Member Function Documentation
void OpNoviceSteppingAction::UserSteppingAction (const G4Step * step) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 56 of file OpNoviceSteppingAction.cc.
View newest version in sPHENIX GitHub at line 56 of file OpNoviceSteppingAction.cc
References fCerenkovCounter, fEventNumber, fScintillationCounter, G4Track::GetDynamicParticle(), G4RunManager::GetRunManager(), G4Step::GetSecondaryInCurrentStep(), G4Step::GetTrack(), G4OpticalPhoton::OpticalPhotonDefinition(), and track.
Member Data Documentation
G4int OpNoviceSteppingAction::fCerenkovCounter private
Definition at line 50 of file OpNoviceSteppingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file OpNoviceSteppingAction.hh
Referenced by OpNoviceSteppingAction(), and UserSteppingAction().
G4int OpNoviceSteppingAction::fEventNumber private
Definition at line 51 of file OpNoviceSteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file OpNoviceSteppingAction.hh
Referenced by OpNoviceSteppingAction(), and UserSteppingAction().
G4int OpNoviceSteppingAction::fScintillationCounter private
Definition at line 49 of file OpNoviceSteppingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file OpNoviceSteppingAction.hh
Referenced by OpNoviceSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNoviceSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/src/OpNoviceSteppingAction.cc