ECCE @ EIC Software: XrayFluoDataSet Class Reference
XrayFluoDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoDataSet.hh>
Public Member Functions
XrayFluoDataSet (G4int Z, G4DataVector *points, G4DataVector *values, const G4VDataSetAlgorithm *interpolation, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn)
XrayFluoDataSet (G4int Z, const G4String &dataFile, const G4VDataSetAlgorithm *interpolation, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn)
~XrayFluoDataSet ()
G4double FindValue (G4double e, G4int) const
virtual const G4VEMDataSet * GetComponent (G4int) const
virtual void AddComponent (G4VEMDataSet *)
virtual size_t NumberOfComponents () const
virtual void SetEnergiesData (G4DataVector *, G4DataVector *, int=0)
virtual G4bool SaveData (const G4String &) const
virtual G4double RandomSelect (int=0) const
void PrintData () const
const G4DataVector & GetEnergies (G4int) const
const G4DataVector & GetData (G4int) const
virtual const G4DataVector & GetLogEnergies (G4int) const
virtual const G4DataVector & GetLogData (G4int) const
virtual void SetLogEnergiesData (G4DataVector *, G4DataVector *, G4DataVector *, G4DataVector *, G4int)
virtual G4bool LoadNonLogData (const G4String &)
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
G4bool LoadData (const G4String &dataFile)
G4int FindBinLocation (G4double energy) const
Private Attributes
G4DataVector * energies
G4DataVector * data
const G4VDataSetAlgorithm * algorithm
G4double unit1
G4double unit2
size_t numberOfBins
Detailed Description
Definition at line 49 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 49 of file XrayFluoDataSet.hh
Constructor & Destructor Documentation
XrayFluoDataSet::XrayFluoDataSet (G4int Z, G4DataVector * points, G4DataVector * values, const G4VDataSetAlgorithm * interpolation, G4double unitE = CLHEP::MeV, G4double unitData = CLHEP::barn)
Definition at line 40 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 40 of file XrayFluoDataSet.cc
References energies, numberOfBins, unit1, and unit2.
XrayFluoDataSet::XrayFluoDataSet (G4int Z, const G4String & dataFile, const G4VDataSetAlgorithm * interpolation, G4double unitE = CLHEP::MeV, G4double unitData = CLHEP::barn)
Definition at line 54 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 54 of file XrayFluoDataSet.cc
References energies, LoadData(), numberOfBins, unit1, and unit2.
XrayFluoDataSet::~XrayFluoDataSet ()
Definition at line 71 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 71 of file XrayFluoDataSet.cc
References data, and energies.
Member Function Documentation
virtual void XrayFluoDataSet::AddComponent (G4VEMDataSet *) inline virtual
Implements G4VEMDataSet.
Definition at line 72 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 72 of file XrayFluoDataSet.hh
G4int XrayFluoDataSet::FindBinLocation (G4double energy) const private
Definition at line 105 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 105 of file XrayFluoDataSet.cc
References energies, and numberOfBins.
Referenced by FindValue().
G4double XrayFluoDataSet::FindValue (G4double e, G4int) const virtual
Implements G4VEMDataSet.
Definition at line 79 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 79 of file XrayFluoDataSet.cc
References algorithm, bin, G4VDataSetAlgorithm::Calculate(), energies, FindBinLocation(), and numberOfBins.
Referenced by XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoNormalization::Integrate(), XrayFluoHPGeDetectorType::ResponseFunction(), and XrayFluoSiLiDetectorType::ResponseFunction().
virtual const G4VEMDataSet* XrayFluoDataSet::GetComponent (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 70 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 70 of file XrayFluoDataSet.hh
const G4DataVector& XrayFluoDataSet::GetData (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 86 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoDataSet.hh
References data.
const G4DataVector& XrayFluoDataSet::GetEnergies (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 85 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 85 of file XrayFluoDataSet.hh
References energies.
virtual const G4DataVector& XrayFluoDataSet::GetLogData (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 89 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 89 of file XrayFluoDataSet.hh
References data.
virtual const G4DataVector& XrayFluoDataSet::GetLogEnergies (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 88 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 88 of file XrayFluoDataSet.hh
References energies.
G4bool XrayFluoDataSet::LoadData (const G4String & dataFile) private virtual
Implements G4VEMDataSet.
Definition at line 131 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 131 of file XrayFluoDataSet.cc
References a, e, energies, FatalException, file, G4endl, G4Exception(), k, unit1, and unit2.
Referenced by XrayFluoDataSet().
virtual G4bool XrayFluoDataSet::LoadNonLogData (const G4String &) inline virtual
Implements G4VEMDataSet.
Definition at line 98 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 98 of file XrayFluoDataSet.hh
virtual size_t XrayFluoDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 74 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file XrayFluoDataSet.hh
void XrayFluoDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 204 of file XrayFluoDataSet.cc.
View newest version in sPHENIX GitHub at line 204 of file XrayFluoDataSet.cc
References e, G4cout, G4endl, numberOfBins, unit1, and unit2.
virtual G4double XrayFluoDataSet::RandomSelect (int = 0) const inline virtual
Implements G4VEMDataSet.
Definition at line 81 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 81 of file XrayFluoDataSet.hh
virtual G4bool XrayFluoDataSet::SaveData (const G4String &) const inline virtual
Implements G4VEMDataSet.
Definition at line 79 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 79 of file XrayFluoDataSet.hh
virtual void XrayFluoDataSet::SetEnergiesData (G4DataVector * , G4DataVector * , int = 0) inline virtual
Implements G4VEMDataSet.
Definition at line 76 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 76 of file XrayFluoDataSet.hh
virtual void XrayFluoDataSet::SetLogEnergiesData (G4DataVector * , G4DataVector * , G4DataVector * , G4DataVector * , G4int) inline virtual
Implements G4VEMDataSet.
Definition at line 92 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 92 of file XrayFluoDataSet.hh
Member Data Documentation
const G4VDataSetAlgorithm* XrayFluoDataSet::algorithm private
Definition at line 114 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 114 of file XrayFluoDataSet.hh
Referenced by FindValue().
G4DataVector* XrayFluoDataSet::data private
Definition at line 112 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 112 of file XrayFluoDataSet.hh
Referenced by GetData(), GetLogData(), and ~XrayFluoDataSet().
G4DataVector* XrayFluoDataSet::energies private
Definition at line 111 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 111 of file XrayFluoDataSet.hh
Referenced by FindBinLocation(), FindValue(), GetEnergies(), GetLogEnergies(), LoadData(), XrayFluoDataSet(), and ~XrayFluoDataSet().
size_t XrayFluoDataSet::numberOfBins private
Definition at line 119 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 119 of file XrayFluoDataSet.hh
Referenced by FindBinLocation(), FindValue(), PrintData(), and XrayFluoDataSet().
G4double XrayFluoDataSet::unit1 private
Definition at line 116 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 116 of file XrayFluoDataSet.hh
Referenced by LoadData(), PrintData(), and XrayFluoDataSet().
G4double XrayFluoDataSet::unit2 private
Definition at line 117 of file XrayFluoDataSet.hh.
View newest version in sPHENIX GitHub at line 117 of file XrayFluoDataSet.hh
Referenced by LoadData(), PrintData(), and XrayFluoDataSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoDataSet.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoDataSet.cc