ECCE @ EIC Software: G4ParameterisationPolyhedraZ Class Reference
G4ParameterisationPolyhedraZ Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPolyhedra.hh>
Public Member Functions
G4ParameterisationPolyhedraZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *motherSolid, DivisionType divType)
~G4ParameterisationPolyhedraZ ()
void CheckParametersValidity ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Polyhedra &phedra, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VParameterisationPolyhedra
G4VParameterisationPolyhedra (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationPolyhedra ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
G4double GetR (G4double z, G4double z1, G4double r1, G4double z2, G4double r2) const
G4double GetRmin (G4double z, G4int nsegment) const
G4double GetRmax (G4double z, G4int nsegment) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNSegment = 0
G4PolyhedraHistorical * fOrigParamMother = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VDivisionParameterisation
G4String ftype
EAxis faxis
G4int fnDiv = 0
G4double fwidth = 0.0
G4double foffset = 0.0
DivisionType fDivisionType
G4VSolid * fmotherSolid = nullptr
G4bool fReflectedSolid = false
G4bool fDeleteSolid = false
G4int theVoluFirstCopyNo = 1
G4double kCarTolerance
G4double fhgap = 0.0
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 181 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 181 of file G4ParameterisationPolyhedra.hh
Constructor & Destructor Documentation
G4ParameterisationPolyhedraZ::G4ParameterisationPolyhedraZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid * motherSolid, DivisionType divType)
Definition at line 433 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 433 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::CalculateNDiv(), CheckParametersValidity(), DivNDIV, DivWIDTH, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4PolyhedraHistorical::Num_z_planes, G4VDivisionParameterisation::SetType(), G4VDivisionParameterisation::verbose, and G4PolyhedraHistorical::Z_values.
G4ParameterisationPolyhedraZ::~G4ParameterisationPolyhedraZ ()
Definition at line 467 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 467 of file G4ParameterisationPolyhedra.cc
Member Function Documentation
void G4ParameterisationPolyhedraZ::CheckParametersValidity () virtual
Reimplemented from G4VDivisionParameterisation.
Definition at line 516 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 516 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::CheckParametersValidity(), DivNDIV, DivNDIVandWIDTH, DivWIDTH, FatalException, G4VDivisionParameterisation::fDivisionType, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, fNSegment, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fReflectedSolid, G4VDivisionParameterisation::fwidth, G4endl, G4Exception(), G4VSolid::GetName(), message(), G4PolyhedraHistorical::Num_z_planes, and G4PolyhedraHistorical::Z_values.
Referenced by G4ParameterisationPolyhedraZ().
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Polyhedra & phedra, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 672 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 672 of file G4ParameterisationPolyhedra.cc
References DivNDIV, DivNDIVandWIDTH, DivWIDTH, G4VSolid::DumpInfo(), G4VDivisionParameterisation::fDivisionType, fNSegment, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fReflectedSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, GetRmax(), GetRmin(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, G4Polyhedra::Reset(), G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4Polyhedra::SetOriginalParameters(), G4PolyhedraHistorical::Start_angle, G4VDivisionParameterisation::verbose, and G4PolyhedraHistorical::Z_values.
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 208 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 208 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 210 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 210 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 212 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 212 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 214 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 214 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 216 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 216 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 218 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 218 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 220 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 222 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 222 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 224 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 224 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 226 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 228 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 228 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 230 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ParameterisationPolyhedra.hh
void G4ParameterisationPolyhedraZ::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 620 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 620 of file G4ParameterisationPolyhedra.cc
References G4VDivisionParameterisation::ChangeRotMatrix(), deg, DivNDIV, DivNDIVandWIDTH, DivWIDTH, G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fDivisionType, G4VDivisionParameterisation::foffset, fOrigParamMother, G4VDivisionParameterisation::fReflectedSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), G4VDivisionParameterisation::verbose, and G4PolyhedraHistorical::Z_values.
G4double G4ParameterisationPolyhedraZ::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 509 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 509 of file G4ParameterisationPolyhedra.cc
References kdfinder::abs(), fOrigParamMother, G4PolyhedraHistorical::Num_z_planes, and G4PolyhedraHistorical::Z_values.
G4double G4ParameterisationPolyhedraZ::GetR (G4double z, G4double z1, G4double r1, G4double z2, G4double r2) const private
Definition at line 472 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 472 of file G4ParameterisationPolyhedra.cc
References z2.
Referenced by GetRmax(), and GetRmin().
G4double G4ParameterisationPolyhedraZ::GetRmax (G4double z, G4int nsegment) const private
Definition at line 497 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 497 of file G4ParameterisationPolyhedra.cc
References fOrigParamMother, GetR(), G4PolyhedraHistorical::Rmax, and G4PolyhedraHistorical::Z_values.
Referenced by ComputeDimensions().
G4double G4ParameterisationPolyhedraZ::GetRmin (G4double z, G4int nsegment) const private
Definition at line 485 of file G4ParameterisationPolyhedra.cc.
View newest version in sPHENIX GitHub at line 485 of file G4ParameterisationPolyhedra.cc
References fOrigParamMother, GetR(), G4PolyhedraHistorical::Rmin, and G4PolyhedraHistorical::Z_values.
Referenced by ComputeDimensions().
Member Data Documentation
G4int G4ParameterisationPolyhedraZ::fNSegment = 0 private
Definition at line 234 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 234 of file G4ParameterisationPolyhedra.hh
Referenced by CheckParametersValidity(), and ComputeDimensions().
G4PolyhedraHistorical* G4ParameterisationPolyhedraZ::fOrigParamMother = nullptr private
Definition at line 235 of file G4ParameterisationPolyhedra.hh.
View newest version in sPHENIX GitHub at line 235 of file G4ParameterisationPolyhedra.hh
Referenced by CheckParametersValidity(), ComputeDimensions(), ComputeTransformation(), G4ParameterisationPolyhedraZ(), GetMaxParameter(), GetRmax(), and GetRmin().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPolyhedra.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationPolyhedra.cc