ECCE @ EIC Software: G4UIsession Class Reference
G4UIsession Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIsession.hh>
Public Member Functions
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
virtual G4UIsession * SessionStart ()
virtual void PauseSessionStart (const G4String &Prompt)
virtual G4int ReceiveG4cout (const G4String &coutString)
virtual G4int ReceiveG4cerr (const G4String &cerrString)
G4int GetLastReturnCode () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Static Public Member Functions
static G4int InSession ()
Protected Attributes
G4int ifBatch
G4int lastRC
Protected Attributes inherited from G4coutDestination
std::vector< Transformer > transformersCout
std::vector< Transformer > transformersCerr
Static Protected Attributes
static G4ICOMS_DLL G4int inSession = 0
Static Protected Attributes inherited from G4coutDestination
static G4MTGLOB_DLL
G4coutDestination * masterG4coutDestination = nullptr
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Detailed Description
Definition at line 43 of file G4UIsession.hh.
View newest version in sPHENIX GitHub at line 43 of file G4UIsession.hh
Constructor & Destructor Documentation
G4UIsession::G4UIsession ()
Definition at line 34 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 34 of file G4UIsession.cc
References inSession.
G4UIsession::G4UIsession (G4int iBatch)
Definition at line 39 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 39 of file G4UIsession.cc
G4UIsession::~G4UIsession () virtual
Definition at line 42 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 42 of file G4UIsession.cc
References ifBatch, and inSession.
Member Function Documentation
G4int G4UIsession::GetLastReturnCode () const inline
Definition at line 70 of file G4UIsession.hh.
View newest version in sPHENIX GitHub at line 70 of file G4UIsession.hh
References lastRC.
Referenced by G4UImanager::ExecuteMacroFile().
static G4int G4UIsession::InSession () inline static
Definition at line 69 of file G4UIsession.hh.
View newest version in sPHENIX GitHub at line 69 of file G4UIsession.hh
References inSession.
Referenced by G4UIcontrolMessenger::SetNewValue().
void G4UIsession::PauseSessionStart (const G4String & Prompt) virtual
Reimplemented in G4UIGainServer, G4UIterminal, G4UIbatch, G4UIGAG, G4VBasicShell, G4ZMQServer, G4VMPIsession, and PHG4UIsession.
Definition at line 47 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 47 of file G4UIsession.cc
Referenced by G4UImanager::PauseSession(), and G4VisCommandReviewKeptEvents::SetNewValue().
G4int G4UIsession::ReceiveG4cerr (const G4String & cerrString) virtual
Reimplemented from G4coutDestination.
Reimplemented in G4UIGainServer, G4UIterminal, G4UIGAG, G4ZMQServer, G4VMPIsession, and PHG4UIsession.
Definition at line 55 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 55 of file G4UIsession.cc
G4int G4UIsession::ReceiveG4cout (const G4String & coutString) virtual
Reimplemented from G4coutDestination.
Reimplemented in G4UIGainServer, G4UIterminal, G4UIGAG, G4ZMQServer, G4VMPIsession, and PHG4UIsession.
Definition at line 49 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 49 of file G4UIsession.cc
G4UIsession * G4UIsession::SessionStart () virtual
Reimplemented in G4UIGainServer, G4UIterminal, G4UIbatch, G4UIGAG, G4VBasicShell, G4ZMQServer, G4MPIsession, G4MPIbatch, and PHG4UIsession.
Definition at line 45 of file G4UIsession.cc.
View newest version in sPHENIX GitHub at line 45 of file G4UIsession.cc
Referenced by G4UImanager::ExecuteMacroFile(), and main().
Member Data Documentation
G4int G4UIsession::ifBatch protected
Definition at line 66 of file G4UIsession.hh.
View newest version in sPHENIX GitHub at line 66 of file G4UIsession.hh
Referenced by ~G4UIsession().
G4int G4UIsession::inSession = 0 static protected
Definition at line 65 of file G4UIsession.hh.
View newest version in sPHENIX GitHub at line 65 of file G4UIsession.hh
Referenced by G4UIsession(), InSession(), and ~G4UIsession().
G4int G4UIsession::lastRC protected
Definition at line 67 of file G4UIsession.hh.
View newest version in sPHENIX GitHub at line 67 of file G4UIsession.hh
Referenced by G4UIbatch::G4UIbatch(), GetLastReturnCode(), and G4UIbatch::SessionStart().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIsession.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIsession.cc