ECCE @ EIC Software: G4Region Class Reference
G4Region Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4Region.hh>
Public Member Functions
G4Region (const G4String &name)
virtual ~G4Region ()
G4Region (const G4Region &)=delete
G4Region & operator= (const G4Region &)=delete
G4bool operator== (const G4Region &rg) const
void AddRootLogicalVolume (G4LogicalVolume *lv, G4bool search=true)
void RemoveRootLogicalVolume (G4LogicalVolume *lv, G4bool scan=true)
void SetName (const G4String &name)
const G4String & GetName () const
void RegionModified (G4bool flag)
G4bool IsModified () const
void SetProductionCuts (G4ProductionCuts *cut)
G4ProductionCuts * GetProductionCuts () const
std::vector< G4LogicalVolume * >
::iterator GetRootLogicalVolumeIterator ()
std::vector< G4Material * >
::const_iterator GetMaterialIterator () const
size_t GetNumberOfMaterials () const
size_t GetNumberOfRootVolumes () const
void UpdateMaterialList ()
void ClearMaterialList ()
void ScanVolumeTree (G4LogicalVolume *lv, G4bool region)
void SetUserInformation (G4VUserRegionInformation *ui)
G4VUserRegionInformation * GetUserInformation () const
void SetUserLimits (G4UserLimits *ul)
G4UserLimits * GetUserLimits () const
void ClearMap ()
void RegisterMaterialCouplePair (G4Material *mat, G4MaterialCutsCouple *couple)
G4MaterialCutsCouple * FindCouple (G4Material *mat)
void SetFastSimulationManager (G4FastSimulationManager *fsm)
G4FastSimulationManager * GetFastSimulationManager () const
void ClearFastSimulationManager ()
void SetFieldManager (G4FieldManager *fm)
G4FieldManager * GetFieldManager () const
G4VPhysicalVolume * GetWorldPhysical () const
void SetWorld (G4VPhysicalVolume *wp)
G4bool BelongsTo (G4VPhysicalVolume *thePhys) const
G4Region * GetParentRegion (G4bool &unique) const
void SetRegionalSteppingAction (G4UserSteppingAction *rusa)
G4UserSteppingAction * GetRegionalSteppingAction () const
G4Region (__void__ &)
G4int GetInstanceID () const
void UsedInMassGeometry (G4bool val=true)
void UsedInParallelGeometry (G4bool val=true)
G4bool IsInMassGeometry () const
G4bool IsInParallelGeometry () const
Static Public Member Functions
static const G4RegionManager & GetSubInstanceManager ()
static void Clean ()
Private Types
typedef std::vector
< G4LogicalVolume * > G4RootLVList
typedef std::vector< G4Material * > G4MaterialList
typedef std::pair< G4Material
*, G4MaterialCutsCouple * > G4MaterialCouplePair
typedef std::map< G4Material
*, G4MaterialCutsCouple * > G4MaterialCoupleMap
Private Member Functions
void AddMaterial (G4Material *aMaterial)
Private Attributes
G4String fName
G4RootLVList fRootVolumes
G4MaterialList fMaterials
G4MaterialCoupleMap fMaterialCoupleMap
G4bool fRegionMod = true
G4ProductionCuts * fCut = nullptr
G4VUserRegionInformation * fUserInfo = nullptr
G4UserLimits * fUserLimits = nullptr
G4FieldManager * fFieldManager = nullptr
G4VPhysicalVolume * fWorldPhys = nullptr
G4bool fInMassGeometry = false
G4bool fInParallelGeometry = false
G4int instanceID
Static Private Attributes
static G4GEOM_DLL G4RegionManager subInstanceManager
Detailed Description
Definition at line 95 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Region.hh
Member Typedef Documentation
typedef std::map<G4Material*,G4MaterialCutsCouple*> G4Region::G4MaterialCoupleMap private
Definition at line 100 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 100 of file G4Region.hh
typedef std::pair<G4Material*,G4MaterialCutsCouple*> G4Region::G4MaterialCouplePair private
Definition at line 99 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 99 of file G4Region.hh
typedef std::vector<G4Material*> G4Region::G4MaterialList private
Definition at line 98 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Region.hh
typedef std::vector<G4LogicalVolume*> G4Region::G4RootLVList private
Definition at line 97 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 97 of file G4Region.hh
Constructor & Destructor Documentation
G4Region::G4Region (const G4String & name)
Definition at line 65 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 65 of file G4Region.cc
References G4GeomSplitter< T >::CreateSubInstance(), G4endl, G4Exception(), G4MT_fsmanager, G4MT_rsaction, G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), instanceID, JustWarning, message(), G4RegionStore::Register(), and subInstanceManager.
G4Region::~G4Region () virtual
Definition at line 111 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 111 of file G4Region.cc
References G4RegionStore::DeRegister(), fUserInfo, and G4RegionStore::GetInstance().
G4Region::G4Region (const G4Region &) delete
G4Region::G4Region (__void__ &)
Definition at line 94 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 94 of file G4Region.cc
References G4GeomSplitter< T >::CreateSubInstance(), G4MT_fsmanager, G4MT_rsaction, G4RegionStore::GetInstance(), instanceID, G4RegionStore::Register(), and subInstanceManager.
Member Function Documentation
void G4Region::AddMaterial (G4Material * aMaterial) inline private
Referenced by ScanVolumeTree().
void G4Region::AddRootLogicalVolume (G4LogicalVolume * lv, G4bool search = true)
Definition at line 283 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 283 of file G4Region.cc
References fRegionMod, fRootVolumes, pos(), ScanVolumeTree(), and G4LogicalVolume::SetRegionRootFlag().
Referenced by ExTGRCRegionCutsMgr::BuildRegions(), G4RunManagerKernel::CheckRegions(), Par01ParallelWorldForPion::Construct(), Par01DetectorConstruction::Construct(), RE01DetectorConstruction::Construct(), DetectorBarr90::Construct(), DetectorWatase86::Construct(), ExGflash2ParallelWorld::Construct(), DetectorHarris73::Construct(), DetectorSimpleALICE::Construct(), ExGflash1DetectorConstruction::Construct(), ExGflash3DetectorConstruction::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), ExGflashDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2Ph_FullWater::Construct(), HadrontherapyDetectorConstruction::ConstructDetector(), DetectorConstruction::ConstructDetector(), PHG4FCalDetector::ConstructMe(), PHG4RICHDetector::ConstructMe(), PHG4TpcDetector::ConstructTpcGasVolume(), G4RunManagerKernel::DefineWorldVolume(), export_G4Region(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4GDMLParser::ImportRegions(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2Acc2::Jaw2Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), G4ReflectionFactory::ReflectLV(), RE06DetectorConstruction::SetupGeometry(), CexmcSetup::SetupSpecialVolumes(), CML2Acc2::target(), and CML2Acc2::vacuumWindow().
G4bool G4Region::BelongsTo (G4VPhysicalVolume * thePhys) const
Definition at line 404 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 404 of file G4Region.cc
References G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetNoDaughters(), and G4LogicalVolume::GetRegion().
Referenced by G4RunManagerKernel::CheckRegions(), export_G4Region(), and SetWorld().
void G4Region::Clean () static
Definition at line 346 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 346 of file G4Region.cc
References G4GeomSplitter< T >::FreeSlave(), and subInstanceManager.
Referenced by G4RegionStore::~G4RegionStore().
void G4Region::ClearFastSimulationManager ()
Definition at line 424 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 424 of file G4Region.cc
References fName, G4endl, G4Exception(), G4MT_fsmanager, GetFastSimulationManager(), GetParentRegion(), JustWarning, and message().
Referenced by export_G4Region(), and G4FastSimulationManager::~G4FastSimulationManager().
void G4Region::ClearMap () inline
Referenced by export_G4Region().
void G4Region::ClearMaterialList ()
Definition at line 356 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 356 of file G4Region.cc
References fMaterials.
Referenced by export_G4Region(), and UpdateMaterialList().
G4MaterialCutsCouple* G4Region::FindCouple (G4Material * mat) inline
Referenced by export_G4Region(), G4PAIPhotModel::Initialise(), G4PAIModel::Initialise(), and G4LogicalVolume::UpdateMaterial().
G4FastSimulationManager * G4Region::GetFastSimulationManager () const
Definition at line 130 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 130 of file G4Region.cc
References G4MT_fsmanager.
Referenced by ClearFastSimulationManager(), G4GlobalFastSimulationManager::DisplayRegion(), G4RunManagerKernel::DumpRegion(), export_G4Region(), G4VFastSimulationModel::G4VFastSimulationModel(), G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), and G4FastSimulationManager::~G4FastSimulationManager().
G4FieldManager* G4Region::GetFieldManager () const inline
Referenced by G4VFieldModel::DescribeYourselfTo(), and G4PropagatorInField::FindAndSetFieldManager().
G4int G4Region::GetInstanceID () const inline
std::vector<G4Material*>::const_iterator G4Region::GetMaterialIterator () const inline
Referenced by ExGflash3DetectorConstruction::ConstructSDandField(), G4RunManagerKernel::DumpRegion(), and G4ProductionCutsTable::IsCoupleUsedInTheRegion().
const G4String& G4Region::GetName () const inline
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4RunManagerKernel::CheckRegions(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4RunManagerKernel::DefineWorldVolume(), G4GlobalFastSimulationManager::DisplayRegion(), G4EmModelManager::DumpModelList(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), export_G4Region(), G4EmCalculator::FindCouple(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4PAIPhotModel::Initialise(), G4EmBiasingManager::Initialise(), G4PAIModel::Initialise(), G4EmModelManager::Initialise(), G4FastSimulationManager::ListTitle(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4VEnergyLossProcess::PreparePhysicsTable(), G4EmConfigurator::SetModelForRegion(), and G4GlobalFastSimulationManager::ShowSetup().
size_t G4Region::GetNumberOfMaterials () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and G4ProductionCutsTable::IsCoupleUsedInTheRegion().
size_t G4Region::GetNumberOfRootVolumes () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and G4RunManagerKernel::SetupDefaultRegion().
G4Region * G4Region::GetParentRegion (G4bool & unique) const
Definition at line 459 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 459 of file G4Region.cc
References G4LogicalVolumeStore::GetInstance().
Referenced by ClearFastSimulationManager(), and export_G4Region().
G4ProductionCuts* G4Region::GetProductionCuts () const inline
Referenced by G4RunManagerKernel::CheckRegions(), Par01DetectorConstruction::Construct(), PHG4RICHDetector::ConstructMe(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), export_G4Region(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), G4EmCalculator::FindCouple(), G4VUserPhysicsList::GetCutValue(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4ProductionCutsTable::IsCoupleUsedInTheRegion(), G4VUserPhysicsList::SetParticleCuts(), and G4ParallelWorldProcess::SwitchMaterial().
G4UserSteppingAction * G4Region::GetRegionalSteppingAction () const
Definition at line 148 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 148 of file G4Region.cc
References G4MT_rsaction.
Referenced by G4RunManagerKernel::DumpRegion(), PHG4FCalDetector::GetSteppingAction(), PHG4FPbScDetector::GetSteppingAction(), PHG4RICHDetector::GetSteppingAction(), PHG4HcalDetector::GetSteppingAction(), G4SteppingManager::Stepping(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
std::vector<G4LogicalVolume*>::iterator G4Region::GetRootLogicalVolumeIterator () inline
Referenced by G4RunManagerKernel::DumpRegion(), and G4RunManagerKernel::SetupDefaultRegion().
const G4RegionManager & G4Region::GetSubInstanceManager () static
Definition at line 55 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 55 of file G4Region.cc
References subInstanceManager.
Referenced by G4GeometryWorkspace::G4GeometryWorkspace().
G4VUserRegionInformation* G4Region::GetUserInformation () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and RE01SteppingAction::UserSteppingAction().
G4UserLimits* G4Region::GetUserLimits () const inline
Referenced by G4RunManagerKernel::DumpRegion(), and export_G4Region().
G4VPhysicalVolume* G4Region::GetWorldPhysical () const inline
Referenced by G4RunManagerKernel::DumpRegion(), export_G4Region(), and G4FastSimulationManager::ListTitle().
G4bool G4Region::IsInMassGeometry () const inline
Referenced by G4RunManagerKernel::CheckRegions(), and G4RunManagerKernel::DumpRegion().
G4bool G4Region::IsInParallelGeometry () const inline
Referenced by G4RunManagerKernel::CheckRegions(), and G4RunManagerKernel::DumpRegion().
G4bool G4Region::IsModified () const inline
Referenced by export_G4Region().
G4Region& G4Region::operator= (const G4Region &) delete
G4bool G4Region::operator== (const G4Region & rg) const inline
void G4Region::RegionModified (G4bool flag) inline
Referenced by G4LogicalVolume::AddDaughter(), G4LogicalVolume::ClearDaughters(), export_G4Region(), and G4LogicalVolume::RemoveDaughter().
void G4Region::RegisterMaterialCouplePair (G4Material * mat, G4MaterialCutsCouple * couple) inline
Referenced by export_G4Region().
void G4Region::RemoveRootLogicalVolume (G4LogicalVolume * lv, G4bool scan = true)
Definition at line 318 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 318 of file G4Region.cc
References fRegionMod, fRootVolumes, pos(), G4LogicalVolume::SetRegionRootFlag(), and UpdateMaterialList().
Referenced by export_G4Region(), G4RunManagerKernel::SetupDefaultRegion(), XrayFluoDetectorConstruction::UpdateGeometry(), and G4LogicalVolume::~G4LogicalVolume().
void G4Region::ScanVolumeTree (G4LogicalVolume * lv, G4bool region)
Definition at line 162 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 162 of file G4Region.cc
References AddMaterial(), G4VPVParameterisation::ComputeMaterial(), FatalException, fInMassGeometry, G4endl, G4Exception(), G4Material::GetBaseMaterial(), G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4VVolumeMaterialScanner::GetMaterial(), G4LogicalVolume::GetMaterial(), G4VPVParameterisation::GetMaterialScanner(), G4VPhysicalVolume::GetMultiplicity(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4VVolumeMaterialScanner::GetNumberOfMaterials(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::IsParameterised(), G4LogicalVolume::IsRootRegion(), mat, message(), and G4LogicalVolume::SetRegion().
Referenced by AddRootLogicalVolume(), export_G4Region(), and UpdateMaterialList().
void G4Region::SetFastSimulationManager (G4FastSimulationManager * fsm)
Definition at line 121 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 121 of file G4Region.cc
References G4MT_fsmanager.
Referenced by export_G4Region(), G4FastSimulationManager::G4FastSimulationManager(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
void G4Region::SetFieldManager (G4FieldManager * fm) inline
void G4Region::SetName (const G4String & name) inline
Referenced by export_G4Region().
void G4Region::SetProductionCuts (G4ProductionCuts * cut) inline
Referenced by ExTGRCRegionCutsMgr::BuildProductionCuts(), G4RunManagerKernel::CheckRegions(), Par01DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2Ph_FullWater::Construct(), DetectorConstruction::ConstructDetector(), PHG4RICHDetector::ConstructMe(), G4RunManagerKernel::DumpRegion(), export_G4Region(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4RunManagerKernel::G4RunManagerKernel(), G4GDMLParser::ImportRegions(), CML2Acc1::ionizationChamber(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc2::Jaw2X(), CML2AccSaturn::Jaw2X(), CML2Acc2::Jaw2Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), CML2AccSaturn::primaryCollimator(), G4VUserPhysicsList::SetParticleCuts(), CexmcSetup::SetupSpecialVolumes(), CML2Acc1::target(), CML2Acc2::target(), CML2Acc1::vacuumWindow(), CML2Acc2::vacuumWindow(), and CML2AccSaturn::vacuumWindow().
void G4Region::SetRegionalSteppingAction (G4UserSteppingAction * rusa)
Definition at line 139 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 139 of file G4Region.cc
References G4MT_rsaction.
Referenced by PHG4FCalDetector::ConstructMe(), PHG4RICHDetector::ConstructMe(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
void G4Region::SetUserInformation (G4VUserRegionInformation * ui) inline
Referenced by PHG4PhenixDetector::Construct(), RE01DetectorConstruction::Construct(), and export_G4Region().
void G4Region::SetUserLimits (G4UserLimits * ul) inline
Referenced by export_G4Region(), and G4GDMLParser::ImportRegions().
void G4Region::SetWorld (G4VPhysicalVolume * wp)
Definition at line 388 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 388 of file G4Region.cc
References BelongsTo(), fWorldPhys, and wp.
Referenced by G4RunManagerKernel::CheckRegions(), and export_G4Region().
void G4Region::UpdateMaterialList ()
Definition at line 367 of file G4Region.cc.
View newest version in sPHENIX GitHub at line 367 of file G4Region.cc
References ClearMaterialList(), fRootVolumes, and ScanVolumeTree().
Referenced by export_G4Region(), and RemoveRootLogicalVolume().
void G4Region::UsedInMassGeometry (G4bool val = true) inline
Referenced by G4RunManagerKernel::CheckRegions().
void G4Region::UsedInParallelGeometry (G4bool val = true) inline
Referenced by G4RunManagerKernel::CheckRegions().
Member Data Documentation
G4ProductionCuts* G4Region::fCut = nullptr private
Definition at line 258 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 258 of file G4Region.hh
G4FieldManager* G4Region::fFieldManager = nullptr private
Definition at line 262 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 262 of file G4Region.hh
G4bool G4Region::fInMassGeometry = false private
Definition at line 266 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 266 of file G4Region.hh
Referenced by ScanVolumeTree().
G4bool G4Region::fInParallelGeometry = false private
Definition at line 267 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 267 of file G4Region.hh
G4MaterialCoupleMap G4Region::fMaterialCoupleMap private
Definition at line 255 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 255 of file G4Region.hh
G4MaterialList G4Region::fMaterials private
Definition at line 254 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 254 of file G4Region.hh
Referenced by ClearMaterialList().
G4String G4Region::fName private
Definition at line 251 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 251 of file G4Region.hh
Referenced by ClearFastSimulationManager().
G4bool G4Region::fRegionMod = true private
Definition at line 257 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 257 of file G4Region.hh
Referenced by AddRootLogicalVolume(), and RemoveRootLogicalVolume().
G4RootLVList G4Region::fRootVolumes private
Definition at line 253 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 253 of file G4Region.hh
Referenced by AddRootLogicalVolume(), RemoveRootLogicalVolume(), and UpdateMaterialList().
G4VUserRegionInformation* G4Region::fUserInfo = nullptr private
Definition at line 260 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 260 of file G4Region.hh
Referenced by ~G4Region().
G4UserLimits* G4Region::fUserLimits = nullptr private
Definition at line 261 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 261 of file G4Region.hh
G4VPhysicalVolume* G4Region::fWorldPhys = nullptr private
Definition at line 264 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 264 of file G4Region.hh
Referenced by SetWorld().
G4int G4Region::instanceID private
Definition at line 269 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 269 of file G4Region.hh
Referenced by G4Region().
G4RegionManager G4Region::subInstanceManager static private
Definition at line 271 of file G4Region.hh.
View newest version in sPHENIX GitHub at line 271 of file G4Region.hh
Referenced by Clean(), G4Region(), and GetSubInstanceManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4Region.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4Region.cc